### ISSUE TITLE
Improve Language Server for Kotlin

### ISSUE THREAD

**Issue by tomschrot** [microsoft/vscode#84896]
The Kotlin Language Server is still very "holey" and needs improvement urgently!
e.g. 
-it does not support parsing sources spread across different directories in compound workbench.
-no support for different scenarios like jvm, js, etc..

I just love VSC and would prefer it to IntelliJ for my projects. Also Kotlin as open language could benefit from VSC support.

**Comment by gjsjohnmurray** [comment]
Please raise this in the repo of the Kotlin extension you are using, maybe https://github.com/fwcd/vscode-kotlin-ide/issues

**Comment by rebornix** [comment]
Yes please file issue against the kotlin extension/
