### ISSUE TITLE
Left delete behavior in some languages is changed

### ISSUE THREAD

**Issue by tsctao** [microsoft/vscode#84897]
- VSCode Version: 1.40.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Type `สวัสดี` in the editor

2. Press backspace

Expected behavior: It should only delete `ี` character.

Actual behavior: Both `ด` and `ี` are deleted.

Does this issue occur when all extensions are disabled?: Yes

**Suggestion**
According to my understanding, VSCode has to detect if delete a combined character, only the combining character should be deleted. (Reference: http://www.catch22.net/tuts/neatpad/unicode-text-editing#backspace-vs-delete)

**Comment by adrianp97** [comment]
Hi @rebornix ,
I would like to contribute to this feature. Do you have any tips on where to start in the codebase?

**Comment by phuclv90** [comment]
I guess this is due to [Better handling for Unicode combining characters](https://code.visualstudio.com/updates/v1_40#_better-handling-for-unicode-combining-characters) in the 1.4 update

> made improvements around handling of Unicode combining characters and we treat such sequences as atomic characters (in cursor movement, editing operations, or in block cursor rendering)

**Comment by rebornix** [comment]
@alexandrudima assigning to you as you pushed more changes to this part lately.

**Comment by mcdurdin** [comment]
This also [impacts 3rd party IMEs such as Keyman](https://github.com/keymanapp/keyman/issues/2315) which rely on specific backspace semantics to function correctly for some scripts.

By convention on Windows, left-delete deletes only the final Unicode codepoint, never a cluster, while right-delete deletes the cluster to the right of the cursor. This is particularly important for complex script languages where a cluster may take 7-8 keystrokes to type, and the user does not want to be forced to retype the whole cluster when mistyping only the final keystroke.

Of course, there is always an exception. Emojis are often clusters behind the scenes, but are almost always entered atomically via a picker, and the user would not usually be expecting them to be broken apart by backspace (mind you, VS Code users are a bit of a different breed).

**Comment by mcdurdin** [comment]
Fix tested here on Insiders build today; looks good, thank you!
