### ISSUE TITLE
Opening Android Studio when using vscode must lead vscode to stop working

### ISSUE THREAD

**Issue by zhuyingqi** [microsoft/vscode#84892]
- VSCode Version:1.40.1
- OS Version:Darwin x64 18.7.0

Steps to Reproduce:

1.Opening vscode and opening a project
2.Opening Android Studio

After two steps above,my vscode will stop working and I can't even close vscode.If I try to close vscode,it will remind me that window no longer responds a moment later.I hava tried to change version of vscode but it doesn't work.I am so sorry for my bad English

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 7.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration_1.41.0-1573181501_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1.41.0-1573181670.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1573181432.tar.gz)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeUserSetup-x64-1.41.0-exploration.exe)

**Comment by zhuyingqi** [comment]
I am so sorry that it doesn't work for this issue.I use the new version but when I open Android Studio ,vscode still crashed.I wonder if you need more infomation and what can I apply for you.

**Comment by bpasero** [comment]
Can you try another Electron application and reproduce this issue so that we have a chance of reporting this against Electron itself? Best to try with Electron Fiddle: https://electronjs.org/fiddle

If the issue reproduces, please go ahead and report it at https://github.com/atom/electron
