### ISSUE TITLE
yarn web should support extension search and display

### ISSUE THREAD

**Issue by echarles** [microsoft/vscode#84894]
I am building from source with an updated `product.json` pointing to the MS marketplace.

[1] `./scripts/code.sh` allows to query the extension marketplace and display search results

<img width="321" alt="Screenshot 2019-11-15 at 08 37 41" src="https://user-images.githubusercontent.com/226720/68925639-bc54b680-0783-11ea-825e-e7f5a5cd19e6.png">

[2] `yarn web` does not display any extension search result (http://localhost:8080).

<img width="349" alt="Screenshot 2019-11-15 at 08 38 02" src="https://user-images.githubusercontent.com/226720/68925679-d393a400-0783-11ea-83f6-61268a2c7b93.png">

cc/ @bpasero @gjsjohnmurray

**Comment by echarles** [comment]
Same test with a `@builtin` search

[1] With `./dev/code.sh`

<img width="320" alt="Screenshot 2019-11-15 at 08 46 22" src="https://user-images.githubusercontent.com/226720/68925945-9380f100-0784-11ea-81e6-2da437eea7f2.png">

[2] With `yarn web`

<img width="352" alt="Screenshot 2019-11-15 at 08 46 49" src="https://user-images.githubusercontent.com/226720/68925957-9976d200-0784-11ea-9059-e4cf63a0941b.png">

**Comment by sandy081** [comment]
Closing this in favor of https://github.com/microsoft/vscode/issues/84901
