### ISSUE TITLE
HTML: embedded script not colored

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84891]
I am using web version and open workbench.html:

![image](https://user-images.githubusercontent.com/900690/68922234-63812000-077b-11ea-9a7f-34f076ae97ac.png)

**Comment by alexr00** [comment]
Appears to not just be web specific.

**Comment by alexr00** [comment]
This is https://github.com/microsoft/vscode/issues/83541
The fix for it only went into the release branch https://github.com/microsoft/vscode/commit/22d5f54e1d53417ce46bf9ec9762e8054e12e348

**Comment by alexandrudima** [comment]
Duplicate of #84401
