### ISSUE TITLE
[c#] Unexpected syntax color for nested namespace declarations

### ISSUE THREAD

**Issue by vbfox** [Microsoft/vscode#849]
![2015-12-01 10_08_59-searchkey cs - rfq-hub - visual studio code](https://cloud.githubusercontent.com/assets/131878/11496639/951fcd0e-9813-11e5-8ade-7a6ba1f353e8.png)

Namespaces contained in namespace declarations don't get any syntax coloration.

Additionally while the "Light" theme show a color for the `namespace` keyword different from the namespace name, the "Dark" one doesn't.

*Version 0.12.2*

**Comment by aeschli** [comment]
This issue was moved to atom/language-csharp#44

**Comment by aeschli** [comment]
Now tracked in https://github.com/OmniSharp/omnisharp-vscode/issues/101
