### ISSUE TITLE
F12 and go to definition, go to implementation does not work 

### ISSUE THREAD

**Issue by wissog** [microsoft/vscode#84908]
Issue Type: <b>Bug</b>

open a react project in vscode
go to a component name or a function and click F12

expected result: the file with the clicked component or function will be opened

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.1.2
easy-icons|jam|0.3.1
git-graph|mhu|1.18.0
debugger-for-chrome|msj|4.12.1
abracadabra|nic|0.11.0
vscode-react-refactor|pla|1.0.5
html-css-class-completion|Zig|1.19.0

(6 theme extensions excluded)

</details>

**Comment by wissog** [comment]
> /needsMoreInfo

what info is missing?

**Comment by mjbvz** [comment]
Please provide repo steps and example code

**Comment by wissog** [comment]
I'm opening my code in React 16.9, going to a method or class used,
clicking on F12 and nothing happens...
expecting F12 to pass me to the method or the class clicked.
It worked already, but recent updates fucked it up


*Gabi*

*"What R we living for?" :)*

**Comment by mjbvz** [comment]
Please share some example code. React intellisense works just fine for me

**Comment by wissog** [comment]
I don't think this is an issue of code. F12 just doesn't work for me...

**Comment by mjbvz** [comment]
Please share some example code

**Comment by wissog** [comment]
Here we go:

const mapState = (state) => {
  const queryResult = selectors.getQueryResult(state.search);
  const results     = queryResult.search_result;

  return {
    queryResult,
    cMap: cMapFromState(state, results),
    cuMap: cuMapFromState(state, results),
    postMap: postMapFromState(state, results),
    query: selectors.getQuery(state.search),
    pageNo: selectors.getPageNo(state.search),
    sortBy: selectors.getSortBy(state.search),
    deb: selectors.getDeb(state.search),
    pageSize: settingsSelectors.getPageSize(state.settings),
    language: settingsSelectors.getLanguage(state.settings),
    wip: selectors.getWip(state.search),
    err: selectors.getError(state.search),
  };
};

click on any yellow procedure calls does nothing... even though in this
case all these functions are in the same file
previously, F12 on a function used even to lead me into other files of my
react project



*Gabi*

*"What R we living for?" :)*

**Comment by wissog** [comment]
this one of the functions which i spoke above

const cMapFromState = (state, results) => (
  results && results.hits && Array.isArray(results.hits.hits)
    ? results.hits.hits.reduce((acc, val) => {
      if (val._source.result_type === 'collections') {
        const cID = val._source.mdb_uid;
        const c   = mdbSelectors.getDenormCollection(state.mdb, cID);
        if (c) {
          acc[cID] = c;
        }
      }
      return acc;
    }, {})
    : {}
);


*Gabi*

*"What R we living for?" :)*

**Comment by wissog** [comment]
another one: F12 on Link class, which is imported on the top of the file,
does nothing as well...

i expect that F12 will open the file where MultiLanguageLink is implemented
(it is implemented in my project)


import React from 'react';
import PropTypes from 'prop-types';
import { withNamespaces } from 'react-i18next';
import { Container, Divider } from 'semantic-ui-react';
import Link from '../Language/MultiLanguageLink';

const DidYouMean = ({suggestion, onClick, t}) => {
  const didYouMeanStr = "Did you mean "; //t(`${section}.header.text`);

  return (
    suggestion
      ? <Container>
        {didYouMeanStr}
        <Link to={onClick}>{suggestion}</Link>
        <Divider fitted />
      </Container>
      : null
  );
};



*Gabi*

*"What R we living for?" :)*

**Comment by mjbvz** [comment]
Sorry but it is not possible to test those snippets without having definitions for all the  symbols they use.  Can you please share a self contained example or the project itself?

Also, if you enabled [semantic checking](https://code.visualstudio.com/Docs/languages/javascript#_type-checking) in your JS by adding `// @ts-check` at the top, do you see any errors?

**Comment by wissog** [comment]
you can try getting that project from here
https://github.com/Bnei-Baruch/kmedia-mdb

open it with vscode latest release and try use F12 which doesn't work





*Gabi*

*"What R we living for?" :)*

**Comment by mjbvz** [comment]
F12 works for me.

Again, please share specific repo steps. For example: open file `x.js` and run `f12` on line 20. Also describe what you expect to happen in that case

**Comment by wissog** [comment]
for example i put above:

Find cMapFromState function and open the file
put cursor on mdbSelectors.getDenormCollection
click F12

nothing happens for me, but i expect that a js file in which we have the
definition of getDenormCollection will be opened and cursor will be set on
that function definition.


*Gabi*

*"What R we living for?" :)*

**Comment by mjbvz** [comment]
<img width="1280" alt="Screen Shot 2019-12-03 at 3 53 14 PM" src="https://user-images.githubusercontent.com/12821956/70099906-08f21b80-15e5-11ea-9915-017a391ce01d.png">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by wissog** [comment]
In insider it works properly!


*Gabi*

*"What R we living for?" :)*

**Comment by wissog** [comment]
but in the main release with all extensions disabled it does not work


*Gabi*

*"What R we living for?" :)*
