### ISSUE TITLE
Issue with quotes in terminal.integrated.shellArgs.windows

### ISSUE THREAD

**Issue by aaronchch** [microsoft/vscode#84904]
Issue Type: <b>Bug</b>

I was trying to pass a command to cmd.exe that contained double quotes but it didn't work.

I've simplified it down to this:
I started with a blank folder and added a workspace settings.json file:

```
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k", 
        "echo \"hello\""
    ]
}
```
In the menu I clicked Terminal, New Terminal
In the new terminal window I expected
```
"hello"
```
I got
```
\"hello\"
```

The escape character in the json string (\) is being passed through to cmd

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
The args get converted to a command line string using this algorithm: https://github.com/microsoft/node-pty/blob/f3099ad49177197203b27e9450aef7c03530c375/src/windowsPtyAgent.ts#L247

shellArgs is special on WIndows as you can also provide a `string` instead of `string[]` to avoid these sort of quoting issues by allowing you to do the quoting yourself.
