### ISSUE TITLE
Git Decoration (Gutter) ignores 1px Width Style at Startup

### ISSUE THREAD

**Issue by mrnschrmm** [microsoft/vscode#84906]
We have written the needed data
Issue Type: <b>Bug</b>

Since 1.40.0.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
auto-rename-tag|for|0.1.1
stylelint-plus|hex|0.52.3
vscode-apache|mrm|1.2.0
vscode-subword-navigation|ow|1.2.0
vscode-css-peek|pra|3.0.2
subtle-brackets|raf|3.0.0
format-html-in-php|rif|1.6.1
px-to-rem|sai|1.2.7
vscode-phpsab|val|0.0.4
gitblame|wad|3.0.1

(1 theme extensions excluded)

</details>
 into your clipboard because it was too large to send. Please paste.

**Comment by rebornix** [comment]
@mrnschrmm could you please share screenshots or recordings to help troubleshoot?

**Comment by mrnschrmm** [comment]
On Startup:
![vscode-startup](https://user-images.githubusercontent.com/13080099/69487910-d3219a00-0e62-11ea-99f4-aa4b488981f6.png)

Saving related Setting Off + On as Workaround:
![vscode-setting](https://user-images.githubusercontent.com/13080099/69487913-e9c7f100-0e62-11ea-9bb7-4fb63d793ac5.png)

Result after Workaround / Expected Result on Startup:
![vscode-expected](https://user-images.githubusercontent.com/13080099/69487923-14b24500-0e63-11ea-8b43-d43f1b3a8989.png)

**Comment by mrnschrmm** [comment]
Additional Info:
The file "setting.json" is symlinked.

**Comment by joaomoreno** [comment]
Great catch!

**Comment by joaomoreno** [comment]
Broken by https://github.com/microsoft/vscode/pull/82209
