### ISSUE TITLE
Access Violation thrown from nt.dll when using MSVC C++ x64 Debugger

### ISSUE THREAD

**Issue by esride-jts** [microsoft/vscode#84905]
- VSCode Version: 1.40.1
- OS Version: Windows 10 x64 10.0.17763

**Steps to Reproduce:**

1. Debugging a C++ application using C++ Build Tools 2019
2. After the Debugger exists an exception is thrown at 0x00007FFB09F2500E (combase.dll) in main.exe: 0xC0000005: Access violation reading location 0x0000000000000010.

Maybe it is related to [Access Violation in combase.dll](https://developercommunity.visualstudio.com/content/problem/320458/access-violation-in-combasedll-while-debugging.html)

Dump file is attached:
[main-dump.zip](https://github.com/microsoft/vscode/files/3851174/main-dump.zip)

**Comment by rebornix** [comment]
The issue seems not related to VS Code. Please file issue against the C++ extension you are using, thanks!
