### ISSUE TITLE
Python extension in wsl killing Symantec Endpoint Protection Service

### ISSUE THREAD

**Issue by NicolasHaeffner** [microsoft/vscode#84907]
- VSCode Version: 1.40.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open Remote connection to WSL
2. Open any python file so that python extension loads 

Does this issue occur when all extensions are disabled?: Yes/No
Unable to check, since WSL Extension needs to be loaded. Does not occur in pure windows. 

Not sure if this is the right place or the WSL extension or the python extension.
Whenever I open a python file (so that the extension starts the first time) in WSL my Symantec Endpoint Protection Service dies. 
I can start the Service again and everything seems to work just fine.

**Comment by aeschli** [comment]
Would you mind filing this against https://github.com/Microsoft/vscode-python and/or Symantec?
(Unfortunately the issue transferer only works if I have write access to that repo, which I haven't)
