### ISSUE TITLE
Web: Support Extensions in hosted version

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#84901]
Support Extensions when running `yarn web`

- https://github.com/microsoft/vscode/issues/84647
- https://github.com/microsoft/vscode/issues/84894

**Comment by echarles** [comment]
Thx @sandy081 and @bpasero. I will follow-up this (interested as end-user but also as potential first contribution, at least to better understand vscode internals).

**Comment by sandy081** [comment]
This is supported now.

**Comment by echarles** [comment]
@sandy081 This is awesome! Is this available in master branch only? Are there public instructions to test this new feature?

**Comment by sandy081** [comment]
It is in master and you can try it in our web playground - http://vscode-web-test-playground.azurewebsites.net
