### ISSUE TITLE
Cursor moving to end of document when pressing CTRL+S

### ISSUE THREAD

**Issue by kuldeepsinghgill** [microsoft/vscode#84909]
Issue Type: <b>Bug</b>

When saving a document by pressing CTRL+S cursor moving to end of the document.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.19008

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (5.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.21.7
vscodeintellicode|Vis|1.2.0

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Are you using format on save? Does this reproduce when running `F1> Save without Formatting`?
