### ISSUE TITLE
 I was prompted that the login session expired

### ISSUE THREAD

**Issue by JiaYifan** [microsoft/vscode#84903]
Issue Type: <b>Bug</b>

someone used my login url (https://prod.liveshare.vsengsaas.visualstudio.com/auth/login?extensionId=) to sign in with his account, then when I sign in,  I was prompted that the login session expired. what can I do?

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 31, 16|
|Memory (System)|31.31GB (26.63GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|10.1.2
prettier-vscode|esb|3.6.0
python|ms-|2019.10.44104
vsliveshare|ms-|1.0.1245
sass-indented|rob|1.5.1
code-spell-checker|str|1.7.20
markdown-all-in-one|yzh|2.5.1

</details>

**Comment by gjsjohnmurray** [comment]
Looks like your issue is specifically about using the VS Live Share extension. The contact link on that extension's Marketplace entry is https://aka.ms/vsls-support

**Comment by rebornix** [comment]
Please file against VS Live Share as suggested above, thanks!
