### ISSUE TITLE
Suggest widget top position unstable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8490]
- VSCode Version: insider
- OS Version: os x

Steps to Reproduce:

1. open suggest widget, using the keyboard scroll down
2. notice how the top of the suggest widget is unstable
3. this is not how the stable vscode behaves

![suggest](https://cloud.githubusercontent.com/assets/1926584/16448367/682412ea-3df1-11e6-9f32-a859da9b0a55.gif)

**Comment by alexandrudima** [comment]
The editor layouts the widget correctly (next to the cursor). The widget should not change its height when there is no detail

**Comment by joaomoreno** [comment]
Stable behaves this way. This has been like this forever.

Closing as designed until a better suggestion is provided.
