### ISSUE TITLE
What happened with this?

### ISSUE THREAD

**Issue by LukasCCB** [microsoft/vscode#84918]
- VSCode Version: 1.40.1
- OS Version: Win10 PRO 64x - Build 1903

Steps to Reproduce:

1. When I started giving this, I formatted the computer, stopped and then started again.
2. ![image](https://user-images.githubusercontent.com/6683056/68947168-920af500-0793-11ea-920e-173ca095e896.png)

Does this issue occur when all extensions are disabled?: Yes/No
> I don't know.

**Comment by G3Kappa** [comment]
That looks like corrupted video drivers or a bad card to me.

**Comment by LukasCCB** [comment]
> That looks like corrupted video drivers or a bad card to me.

Thx, i'll check if is card video.
![image](https://user-images.githubusercontent.com/6683056/68948008-ad76ff80-0795-11ea-9825-d6a7c71a95b2.png)

**Comment by IllusionMH** [comment]
You can also try to run VS Code with `--disable-gpu` flag from console or other ways. See https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by LukasCCB** [comment]
Already fixed with "Driver Card Update"
I have unistall and reinstall all again and all is fixed! Thanks for all here. :}
