### ISSUE TITLE
Stylistics sets not working properly (Fira Code)

### ISSUE THREAD

**Issue by pierredarrieutort** [microsoft/vscode#84917]
Hi,

When i use the ligatures codes starting by `ss` the ligatures are not considered.
Only the stylistics sets like `zero` or `onum` working. The other way around for some others (like the Fira code repo owner (third referral)

And when we push another value than `true` to `editor.fontLigatures` in settings no one ligatures work.

**Refs :**

- https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets#vs-code
- https://code.visualstudio.com/updates/v1_40#_font-feature-settings
- https://github.com/tonsky/FiraCode/issues/892
_____________
- VSCode Version: _1.40.1_
- OS Version: _Windows 10, 64-bit_

**Comment by nkempe** [comment]
Same on Linux, so it seems OS independent.

Tried without the single quotes:
```
    "editor.fontFamily": "'Fira Code'",
    "editor.fontLigatures": "ss01, ss02",
```
..which made no difference, it keeps the >= symbol with the diagonal line instead of the flat line:
![image](https://user-images.githubusercontent.com/4137019/68946177-98f53000-07b2-11ea-996e-6e294988a77c.png)

OS: Ubuntu 18.04
VScode 1.40.1
fonts-firacode version: 1.204-2 installed from ubuntu universe repository

**Comment by wboka** [comment]
I'm seeing this issue with the following version combinations:

> **VS Code**  v1.40.0 and v1.40.1

> **Fira Code** v2.0

**Comment by pierredarrieutort** [comment]
@wboka It's not a version combination problem i think, because the font added ligatures characters in the v2.0 and VS Code implemented this editable setting at 1.40.0 (Refer to second link in first post)

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/84018

Try adding `calt` to your list.

`"editor.fontLigatures": "'zero', 'ss02', 'ss03', 'ss04', 'ss05', 'calt'",`

**Comment by wboka** [comment]
@ArturoDent Doesn't seem to change anything.

`"editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss19', 'ss20', 'calt'"`

**Comment by pierredarrieutort** [comment]
The only visible changement is when i add `calt` to the array, the ligatures are okay but not the horizontal bar of `ss02` ligature

![image](https://user-images.githubusercontent.com/25182438/68978154-48a1c080-07fa-11ea-8984-d128bef64dea.png)

**Comment by ArturoDent** [comment]
Just in case: I did first delete the Fira Code v1 fonts before installing v2.   I would suggest doing that again.

**Comment by alexandrudima** [comment]
@pierredarrieutort Have you uninstalled the previous Fira Code? Restarted, and then installed the new Fira Code?

**Comment by pierredarrieutort** [comment]
I feel bad now, it was a problem to update the font, a fresh install resvoled my problems.

**Comment by wboka** [comment]
I had some old versions (v1.206 & v2.0) of the font installed along side each other. 🤦‍♂ 

Thanks for the help everyone! 🎉
