### ISSUE TITLE
Word wrap fails on lines with breakpoints in debug mode

### ISSUE THREAD

**Issue by karansapolia** [microsoft/vscode#84911]
- VSCode Version: 1.40.1
- OS Version: Windows 10, Version 1909, OS Build: 18363.476

Steps to Reproduce:

1. Open any code file in VSCode ( I tried it only with JS files).
2. Enable word wrap.
3. Put breakpoints on some lines of code, not all, in the file and enter debug mode (hit F5).
4. Open the side bar and extend it until the editor window becomes narrow enough for the lines to start breaking and wrapping into more lines.

Output:
1. As you keep extending the side bar panel, the LOC (lines of code) which have breakpoints don't break on time and go under the minimap for a while before starting to break onto newer lines.
2. LOC without breakpoints wrap correctly.

Note: Happens only while debugging.

Does this issue occur when all extensions are disabled?: Yes

**Comment by karansapolia** [comment]
Attaching a gif for reference:
![vscode-word-wrap](https://user-images.githubusercontent.com/10175625/68944609-3ca30800-07d4-11ea-8f33-797c0aada85b.gif)

**Comment by alexandrudima** [comment]
Let's track in #32856
