### ISSUE TITLE
FETCH_HEAD duplicates if the Git repository is on OneDrive

### ISSUE THREAD

**Issue by SashaIr** [microsoft/vscode#84923]
I know it's a duplicate but the other issue has been closed with an answer "Don't do that", which is very much unsatisfying. I'm using OneDrive to backup all my folders, so any repo would be in OneDrive.

The issue is as per the title: OneDrive keeps generating FETCH_HEAD duplicates whenever VSCode, or GitHub Desktop, are open. Does anyone know a fix for this behavior?

**Comment by gjsjohnmurray** [comment]
/duplicate - https://github.com/Microsoft/vscode/issues/47032#issuecomment-378177234

You got the same with Github Desktop, so it isn't a VS Code specific issue.
