### ISSUE TITLE
Overlay badge for View Container icon

### ISSUE THREAD

**Issue by kentonbmax** [microsoft/vscode#84921]
Similar functionality to SCM update number. Provide the ability to overlay a status badge numbers, symbols over View Container Icons. 

VSCODE Versions: Latest
OS: All

export the API to construct a badge for the icon. The class of the numbers is badge. The SCM icon at the start shows a small watch icon, before it shows the number of changed files.

[Original Question](https://stackoverflow.com/questions/57900587/overlay-visual-studio-code-extension-view-container-icon-to-visualize-some-chang)

![image](https://user-images.githubusercontent.com/15804484/68950338-f45ef800-0789-11ea-8e49-5e929778c859.png)

**Comment by sandy081** [comment]
/duplicate 

#62783
