### ISSUE TITLE
ctrl+s in integrated terminal while ssh'ed into Linux terminal prevents further stdout from displaying

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode#84927]
Issue Type: <b>Bug</b>

1. Open integrated terminal
1. ssh into remote 
1. press <kbd>ctrl</kbd>+<kbd>s</kbd>
1.  ssh session stops responding. 

Note:  If I start a `screen` prior to pressing <kbd>ctrl</kbd>+<kbd>s</kbd>, the ssh session still stops responding, but when I start a new terminal, ssh back into the same remote and reattach to the same screen, I can see that the ssh session that stopped responding was still receiving my commands, I was just not able to continue seeing the stdout.  See gif below.

![vscode_iterm_error](https://user-images.githubusercontent.com/12793783/68959907-08f8bb80-079d-11ea-85da-f2ffe1cb2cd5.gif)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
macros|ged|1.2.1
sftp|lix|1.12.9
python|ms-|2019.10.44104
remote-containers|ms-|0.83.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
Go|ms-|0.11.9

</details>

**Comment by Tyriar** [comment]
This is actually a feature, ctrl+s pauses the terminal, ctrl+q resumes it. See https://unix.stackexchange.com/q/137842/115410
