### ISSUE TITLE
Unable to escape \$ combination for use in PowerShell snippets

### ISSUE THREAD

**Issue by colinlwebster** [microsoft/vscode#84922]
Issue Type: <b>Bug</b>

I have tried multiple combinations of backslashes and/or double dollar and cannot get this to work. 

Steps to reproduce:
Make a powershell snippet-
```json
{
"PowerShell Test Snippet": {
"prefix": "pstest",
"body": [
"$$Root\\$$Module"
],
"description": "Testing"
}
}
```
Using this snippet outputs `$Root$Module` but should output `$Root\$Module`.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.11.0

</details>

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/33933#issuecomment-328793257

**Comment by colinlwebster** [comment]
But when I do the `\\` as listed as the solution from #33933 followed by either a `\$` or a `$$` then all I get is the $

**Comment by colinlwebster** [comment]
I figured it out. For \$ you specifically need to use \\\\$$. Adding comment here in case anyone else gets stuck on this.
