### ISSUE TITLE
Incremental search shouldn't insert item above the selection

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#84926]
* open a huge workspace
* search for something so that it takes a few minutes to complete
* while search is running start selecting/inspecting search results
* :bug: new search results are inserted above the current selection which is confusing and unexpected.

**Comment by roblourens** [comment]
Do you want them to not be sorted? Or what do you expect?

**Comment by JacksonKearl** [comment]
I think alphabetical sorting of the file path provides utility in that it makes visually scanning for a particular file's results faster. We don't seem to be doing a multithreaded though (looking at Activity Monitor), so perhaps we could search the files in the order we want them eventually displayed? Does RG allow something like that?

**Comment by roblourens** [comment]
rg is multithreaded, and you can specify the number of threads it's allowed to use. I think if you tell it to use 1, then it returns results in alphabetical order, but then it's slower.

**Comment by roblourens** [comment]
I think that the sorting will be more useful when we are able to show results in a folder tree view like the SCM tree does now.

Also I think it would be weird to be typing to trigger search, getting most of the same results, and see the results randomly shuffling themselves for each new search.

**Comment by jrieken** [comment]
How about a sort command then? The viewlet can know that I have interacted with the tree while results are coming in and offer a manual resort in that case.

**Comment by roblourens** [comment]
Would it help if we try to preserve location of the selected item when adding new items, ie don't push the selected item out of the viewport?

**Comment by jrieken** [comment]
>  ie don't push the selected item out of the viewport?

No, that won't help. I use the view as a todo list, e.g I search for all usages of a certain API in all extensions and go through them top to bottom. What would help is to mark those results that came in late and atop my selection
