### ISSUE TITLE
Symbols overlapping after ohmyzsh installed, on wsl integrated to vscode

### ISSUE THREAD

**Issue by egeant94** [microsoft/vscode#84925]
- VSCode Version: 1.40.1
- OS Version: W10 10.0.18362

Steps to Reproduce:

1. Install wsl
2. install ubuntu
3. install zsh
4. open wsl into integrated VScode terminal
5. install oh my zsh
6. get overlapping symbol only after zsh installed, looking like this :

![Code_9jRpZjXt4t](https://user-images.githubusercontent.com/56257277/68953579-7e2ab780-07c2-11ea-8446-67728df99c41.png)

Does this issue occur when all extensions are disabled?: Yes
It doesn't occur when i uninstall Oh my zsh, and neither on my ubuntu terminal.
When changing theme, it can change the overlapping arrow's color
![Code_GK3J4SU9BK](https://user-images.githubusercontent.com/56257277/68953669-a87c7500-07c2-11ea-9e01-85c862099992.png)
Changing Ohmyzsh removes the arrow or not depending on the theme, looks like it's related to the arrow symbol.
Amuse theme :
![Code_0ieOuaarBp](https://user-images.githubusercontent.com/56257277/68954133-a7981300-07c3-11ea-8efb-4da99d858f64.png)
Avit theme :
![image](https://user-images.githubusercontent.com/56257277/68954328-1b3a2000-07c4-11ea-9a3e-7c78c47040cb.png)
default theme is: robbyrussell
Didn't find similar cases nor fixes.

**Comment by Tyriar** [comment]
Can you paste in the arrow character that your prompt uses?

**Comment by egeant94** [comment]
It uses this : ➜
(can't copy paste the black arrow tho)
The other white theme, it uses this characer : ▶ but still displays the same black thing

**Comment by Tyriar** [comment]
@egeant94 what's your font set to and what terminal renderer type are you using? You can check in your settings.

Can you also share what your $PS1 variable is set to?

**Comment by egeant94** [comment]
On VScode the font isn't changed : 
![image](https://user-images.githubusercontent.com/56257277/69918848-fe197880-1476-11ea-9fca-73b5d800c8ee.png)
i've tried to install a DejaVu powerline font for my ubuntu terminal, which fixed the problem of the arrow symbol missing on my default ubuntu terminal but any of this didn't affect the vscode one.
I'm using auto for the renderer type : 
![image](https://user-images.githubusercontent.com/56257277/69918890-581a3e00-1477-11ea-8ed6-3a9718f6acf5.png)
I never touched this setting and don't know what it does.
While using the bugged theme, here is my $PS1 value :
![image](https://user-images.githubusercontent.com/56257277/69918927-9f083380-1477-11ea-9a44-423fb37c8860.png)
(the bug is still on the screenshot)
copy pasted the value : %(?:%{%}➜ :%{%}➜ ) %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)
I've tried to change the renderer type, and it seems that "canvas" has problems my setup, but changing to "dom" removed the arrow ! I guess auto mode was selecting "canvas".
![image](https://user-images.githubusercontent.com/56257277/69918980-5735dc00-1478-11ea-9a50-45baa418845b.png)

Thanks for your help ! sorry for late responses, I guess we can close the issue because the problem is fixed after changed renderer type. Thanks again !

**Comment by Tyriar** [comment]
Not yet confirmed

**Comment by Tyriar** [comment]
Not sure how this is happening as the canvas renderer is meant to re-rendered every line when they change 🤔 

Upstream: https://github.com/xtermjs/xterm.js/issues/2659
