### ISSUE TITLE
I can't stop VS Code from inserting TOC--plugin won't turn off.

### ISSUE THREAD

**Issue by abalter** [microsoft/vscode#84938]
I installed some plugin to insert a TOC into my markdown document. I didn't like it. So, I uninstalled it. Now I don't even remember which one.

However, VS Code keeps inserting a TOC! I've tried closing and restarting VS Code. I also deleted the workspace file. No matter what I do, I can't get it to stop inserting a TOC.

**Comment by abalter** [comment]
Thank you for the suggestion @vscodebot. But that is a different issue.

**Comment by rebornix** [comment]
@abalter you can disable extensions and biset to find the right extension.
