### ISSUE TITLE
VSCode incorrectly reports "Invalid version entered" for NuGet package with 4-segment version

### ISSUE THREAD

**Issue by Eilon** [microsoft/vscode#84934]
# Versions

Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Open a CSProj that has this package reference:
```xml
  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.3.0.908675" />
  </ItemGroup>
```
2. You get a warning like this:
![image](https://user-images.githubusercontent.com/202643/68965868-af3ec400-0791-11ea-89a6-e509d342edb2.png)

However, a 4-segment NuGet package version is valid (though not common).

This warning should not be present at all.

**Comment by rebornix** [comment]
It seems caused by nuget/csproject related extension, VS Code core doesn't check this file. Please file issue against related extension, thanks.

**Comment by Eilon** [comment]
Moved to https://github.com/OmniSharp/omnisharp-vscode/issues/3411.
