### ISSUE TITLE
Code helper popup intermittently 

### ISSUE THREAD

**Issue by VictorDragnea** [microsoft/vscode#84932]
Ever since my last system update on a  MacBook Pro (13-inch, 2017), I get a popup from time to time (approximately 2 minutes intervals), with the following message:

code helper (renderer) wants to use your confidential information stored in atlascode-authinfo in your keychain

The popups get more frequent after I open Visual studio code, like 5 popups in a row. After I click 'Deny' for each one of them it resumes the 'usual' 2 minutes interval.

https://imgur.com/XRMXL02
![Screenshot at Nov 15 18-42-35](https://user-images.githubusercontent.com/17453478/68960381-bb9a3f80-07d8-11ea-8833-6ecd6073089c.png)

**Comment by farmererp** [comment]
hey I really look forward to learning git

**Comment by voblak2** [comment]
I'm having the same issue. Is this an ok thing or is it malware or something?  It just started happening recently.

**Comment by Hudsonzp** [comment]
Same.  Happens everytime I open VScode now.

**Comment by rafael-trevisan** [comment]
Same here

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by VictorDragnea** [comment]
@bpasero  You are right! Disabling VSCode extensions did stop the popups. Now I need to check which extension is causing it. Thank you for your help!

**Comment by VictorDragnea** [comment]
Seems that updating all my extensions solved the issue. No more popups. It was probably one of the VScode extensions I was using.

**Comment by andtrobs** [comment]
Any idea what extension was actually causing the issue?

**Comment by VictorDragnea** [comment]
> Any idea what extension was actually causing the issue?
No. But here are my extensions, perhaps you are using some of them:

<img width="361" alt="extensions 1" src="https://user-images.githubusercontent.com/17453478/69088543-0f628e00-0a50-11ea-9be4-9bc8d2461632.png">
<img width="368" alt="extensions 2" src="https://user-images.githubusercontent.com/17453478/69088544-0f628e00-0a50-11ea-9044-79ca4beffa2a.png">

**Comment by jackfsa** [comment]
> Any idea what extension was actually causing the issue?

Had the same problem, it was the Atlassian Jira and Bitbucket extension that seemed to be causing the issue.

Disabled it and problem stopped, enabled and it happened again.

**Comment by rv-bnowak** [comment]
GitHub Pull Requests extension was causing this for me.  Did a login through the extension (opened GitHub URI for auth) and system notification stopped popping up.  FYI.

**Comment by Luke-Wilson** [comment]
I think it was GitLens for me. I disabled it and reenabled it and the popups are no longer appearing.
