### ISSUE TITLE
Very slow close of document symbols view 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#84945]
**Repo**
1. Open the js file from https://github.com/microsoft/vscode/files/3852933/extension-prod.zip
1. Open the document symbols view
1. Wait for it to populate
1. Then try closing it by clicking back in the editor

**Bug**
There are around 70000 document symbols in this file. Closing the view took around 20 seconds on my machine. I've attached the  profile:

[Profile-20191115T144855.json.zip](https://github.com/microsoft/vscode/files/3853439/Profile-20191115T144855.json.zip)

/cc @eamodio

**Comment by jrieken** [comment]
This is the old tree widget which is still used for quick outline and which is know to be slow. Assiging to @joaomoreno to continue to drive the adoption of the new tree.

**Comment by jrieken** [comment]
also cc @chrmarti
