### ISSUE TITLE
Different sizes of sidebar buttons

### ISSUE THREAD

**Issue by ruytertorres** [microsoft/vscode#84944]
Hello developers, it would be interesting to implement the option to shrink the buttons on the side configuration tab. It could add an optional method where you would have some options like: big, medium, small, extra small. This function would not only be aesthetic, but for those who, like me, work with two open codes, would gain a few more pixels of space in the development area.

functions that are available through extensions such as Open In Browser or Live Server could be added as a fixed feature of Visiual Studio.

**Comment by misolori** [comment]
Please upvote https://github.com/microsoft/vscode/issues/82996
