### ISSUE TITLE
Perform search when hitting ENTER key in search detail fields

### ISSUE THREAD

**Issue by kohlikohl** [Microsoft/vscode#8494]
Frequently, when performing a global search for some code, I find myself having to narrow down the search to files of a specific type (*.js, *.scss etc).

I pop open the "search details" section and add a pattern to match the files. 
Then I hit ENTER but nothing happens. :sob: 

It would be great to initiate a search when hitting ENTER in either the "files to include" or "files to exclude" section.

Alternatively, pressing SHIFT + TAB to return to the search box and then hitting ENTER could work as well. 
Currently, I have to press SHIFT + TAB five times to get back to the search box.

**Comment by bpasero** [comment]
This works for me. @sandy081 could it be you recently added this?

**Comment by sandy081** [comment]
@bpasero Yes, I fixed/implemented this with Global replace functionality

**Comment by kohlikohl** [comment]
Perfect. Just installed the new insider build this morning and it works now.
Awesome!
