### ISSUE TITLE
Support git config edition

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vscode#84942]
Can we have UI to edit config `user.name` and `user.email`? 

This to be supported at global level , repository level and ask at each commit and push as well.

https://github.com/eamodio/vscode-gitlens/issues/906

Here is the query.

My full name is "ABC XYZ" , if I commit and push from other applications like Visual studio , Visual studio mac , then commit history shows author as **ABC XYZ<abcxyz@company.com>** 

When I commit and push from VS code its showing **ABC <abcxyz@company.com>**

I would like to know if I change  it to **_ABC XYZ_** in VS Code or GitLens settings

Is that even possible. 

Is there setting which does below things

```bash
$ git config --global user.name "John Doe"
$ git config --global user.email "john@doe.org"
```

on VS Mac it looks like below

![image](https://user-images.githubusercontent.com/21352870/68972924-ef666c80-07ba-11ea-9c40-2a8302f9c917.png)

On Visual studio Windows

![image](https://user-images.githubusercontent.com/21352870/68965194-33507600-07a9-11ea-810d-4adf2ef02783.png)

**Comment by 5achinJani** [comment]
There's an extension which might help you regarding this.
[git-autoconfig](https://github.com/ShyykoSerhiy/git-autoconfig)
Related maybe : #86045
