### ISSUE TITLE
empty line when search bar is active

### ISSUE THREAD

**Issue by sadjadanzabizadeh** [microsoft/vscode#84956]
Issue Type: <b>Bug</b>

When in the middle of a document, if you open search box (Ctrl+F) and then scroll to the top, an extra line shows up with no line number. If, however, you open the search box at the beginning of a document, this lines does not appear.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32
latex-workshop|Jam|8.3.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
material-icon-theme|PKi|3.9.1
vscode-yaml|red|0.6.0
r-lsp|REd|0.1.4

(1 theme extensions excluded)

</details>

**Comment by PerezArmando** [comment]
I would like to work on this.

**Comment by Kiyos** [comment]
Having the same issue here. Version 1.44.2 x64 (user setup) on Windows. Here’s a quick video demonstration:
![VSCodeFindWidgetEmptyLine](https://user-images.githubusercontent.com/5103155/79899935-29950380-8416-11ea-8239-59e3291b33c6.gif)
By the way, this search bar is called Find Widget.

**Comment by rebornix** [comment]
The space above the document is intentional to ensure that  the find widget doesn't cover the text.
