### ISSUE TITLE
 Abnormal Alignment

### ISSUE THREAD

**Issue by longyun0896** [microsoft/vscode#84953]
- VSCode Version: 1.40.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Setting:
```
"editor.wordWrap": "wordWrapColumn",
"editor.wordWrapColumn": 50,
```

When I use indentation and turn on word wrap , there is an abnormal alignment to the right of the first line of text .
![2019-11-16 101803](https://user-images.githubusercontent.com/20329260/68987134-bcc37f00-0861-11ea-8f11-0cd44c67d981.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Two issues are present here:
1. the text does not fill the entire width of the editor - https://github.com/microsoft/vscode/issues/2654
2. commas are treated specially in word wrapping points computation -https://github.com/microsoft/vscode/issues/33366
