### ISSUE TITLE
win10电脑中  使用终端问题

### ISSUE THREAD

**Issue by changeplus** [microsoft/vscode#84951]
win10电脑中 使用终端问题

**Comment by changeplus** [comment]
使用终端执行一些命令时，总是第一次打开是空的，用力敲下几次回车键后，渐渐的显示出来原来执行的命令和提示。

**Comment by byyxx128** [comment]
1. English please.
2. What version of Windows 10 are you using? It may be the known bug of Windows 10 Version 1809 and has been fixed in 1903. So if you upgrade to 1903 or newer, everything should be working normally.
FYI: https://github.com/microsoft/vscode/issues/57803

**Comment by byyxx128** [comment]
1. English please.
2. What version of Windows 10 are you using? It may be the known bug of Windows 10 Version 1809 and has been fixed in 1903. So if you upgrade to 1903 or newer, everything should be working normally.

FYI: https://github.com/microsoft/vscode/issues/57803
