### ISSUE TITLE
Output test files don't delete/rename themselves after doing the same operation in src files

### ISSUE THREAD

**Issue by HarshdeepGupta** [Microsoft/vscode#8495]
- VSCode Version: 1.2.1
- OS Version: Windows 10

 I am building a VS Code extension, and on writing test cases for it, I noticed that files in _out/test_ get created automatically upon creation in _/test_ but don't get renamed or deleted.
**Steps to Reproduce:**

1. Start Yo Code and scaffold a TS extension [(Yo code)](https://code.visualstudio.com/docs/extensions/example-hello-world)
2. open the extension in VS Code and build once to get typescript compiler running on watch mode (need to select "Launch Extension" from debug pane)
3. go to _/test_ and create _main.test.ts_. See that the file is generated in _out/test_ folder.
4. Delete (or rename) _main.test.ts_ . 
5. In _/out/test_ , you will see that the old files are still there.

**Comment by bpasero** [comment]
Please report this against the typescript team. I am assuming you run "tsc -w".
