### ISSUE TITLE
强烈恳求账号支持

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#84957]
# 强烈恳求增加账号的支持

- 同步设置，扩展，快捷键，代码片段等

- 支持不同场景的setting切换

这样可以面对使用不同的编程语言开发的场景。 
还有有些时候我喜欢白天是一个setting场景。晚上是另外一个setting场景。

**Comment by nailao** [comment]
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by heartacker** [comment]
> https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

这个还是不太好用， 禁用的扩展，同时的时候直接就删除了，搞得别的地方没有装上-但是我知识在我旧的pc 上禁用了而已。。

另外没有设置切换的功能，比如我在开发某个项目的时候想要禁用一些扩展或者特殊配置， 等我开发另外一个项目的时候希望又是另外一个配置， 要是有这个setting 切换的功能就好了

**Comment by byyxx128** [comment]
1. English please.
2. They are working on sync support. Please wait~

FYI: https://github.com/microsoft/vscode/issues/83930
> 🏃 Settings sync support  (settings, extensions, key bindings, snippets) #2743 #78966 @sandy081
***
顺便吐槽一下：这么大的pinned issue你都不看嘛……当然你要是嫌字多不看我也没办法……
Didn't you see the huge pinned issue? 🤔
![image](https://user-images.githubusercontent.com/20079289/69000921-6297dd80-08a4-11ea-83c0-f77c1c03fcd5.png)

**Comment by byyxx128** [comment]
1. English please.
2. They are working on sync support. Please wait~

FYI: https://github.com/microsoft/vscode/issues/83930
> 🏃 Settings sync support  (settings, extensions, key bindings, snippets)
***
顺便吐槽一下：这么大的pinned issue你都不看嘛……当然你要是嫌字多不看我也没办法……
Didn't you see the huge pinned issue? 🤔
![image](https://user-images.githubusercontent.com/20079289/69000921-6297dd80-08a4-11ea-83c0-f77c1c03fcd5.png)

**Comment by yinyukang-cuc** [comment]
工作区不知道能不能解决你的问题

**Comment by Tidlo** [comment]
工作区（Workspace）就是为这种需求而生的，可以了解一下：
https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings
https://code.visualstudio.com/docs/editor/multi-root-workspaces
