### ISSUE TITLE
Git: Can't delete a git repo folder which is open in vscode

### ISSUE THREAD

**Issue by LambdaAlpha** [microsoft/vscode#84950]
Issue Type: <b>Bug</b>

1. create a folder named "test"
2. git init it
3. open this folder in vscode (with all user extension disabled)
4. try delete it in vscode or in file explorer
5. the system will alert that i need admin permission and then alert that i need xxx user permission to delete it, and finally the folder still cannot be deleted.
6. close vscode
7. try delete it in file explorer
8. success without any alert

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by OfficerHalf** [comment]
I've seen similar behavior trying to do a `git reset`. Even if the files aren't currently open in VS Code, but the containing folder is opened, Windows complains that it can't remove them as they are being used by another process.

**Comment by joaomoreno** [comment]
Can you find out which specific process holds a handle to which file in that folder? https://serverfault.com/questions/1966/how-do-you-find-what-process-is-holding-a-file-open-in-windows

**Comment by MuseBoy** [comment]
![image](https://user-images.githubusercontent.com/20299598/69156081-da247180-0b1d-11ea-9d35-b218633f1804.png)
@joaomoreno

**Comment by joaomoreno** [comment]
Can you find out the full Command Line of that process?

**Comment by MuseBoy** [comment]
> Can you find out the full Command Line of that process?

@joaomoreno  Sorry, I don't understand what you mean.

**Comment by joaomoreno** [comment]
Related to https://github.com/nodejs/node-v0.x-archive/issues/8371#issuecomment-193845552, very likely won't fix any time soon.

**Comment by mccart** [comment]
I do not know if this is related or not - apparently vscode is not respecting .gitignore file.
In .gitignore, there is web/app/vendor line, and when running docker-compose up, it's generating files in that app/vendor directories - and apparently vscode is generating .git/refs for those files.
That causes problems - I could not remove those directories unless I exit out of vscode

composer_1  |   [RuntimeException]
composer_1  |   Could not delete /app/vendor/phpdocumentor/reflection-common/.git/refs:
