### ISSUE TITLE
the text in the text editor starts fading away,what can I do to solve the problem?

### ISSUE THREAD

**Issue by Percius001** [microsoft/vscode#84954]
- VSCode Version:1.40
- OS Version:windows 10 home

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by Percius001** [comment]
![2019-11-16](https://user-images.githubusercontent.com/48628948/68987914-12ddf580-0855-11ea-99cb-92b935e58cd3.png)

**Comment by gjsjohnmurray** [comment]
Please launch VS Code from a command prompt like this

code --disable-gpu

Also, try updating to 1.40.1
