### ISSUE TITLE
There should be a way to view VS code where users can view only code and its output in terminal.

### ISSUE THREAD

**Issue by PranavBhattarai** [microsoft/vscode#84961]
Like this:
![Screenshot from 2019-11-16 14-19-16](https://user-images.githubusercontent.com/32763112/68990528-4718dc80-087c-11ea-841a-471eeaacadca.png)

The benefit of this that the user can write code and run it, along with doing another task in other applications. For example this:
![Screenshot from 2019-11-16 14-24-31](https://user-images.githubusercontent.com/32763112/68990570-e1792000-087c-11ea-829b-2f2d7448d8a2.png)

Now the problem is this notch:
![Screenshot from 2019-11-16 14-27-17](https://user-images.githubusercontent.com/32763112/68990611-46347a80-087d-11ea-9ea5-f2dc6e14ff30.png)

### There should be Keyboard shortcuts which hide this notch. 
It would be really helpful. It can maximize screen usage especially while users are multitasking.

**Comment by sbatten** [comment]
@PranavBhattarai I don't fully understand this request. Are you saying that you want to write code and run it in the terminal?

**Comment by PranavBhattarai** [comment]
@sbatten A visibility mode shortkey through which a user can view only two things:
1. Editor 
2. Terminal
No there things, unless **alt** pressed. Like a mini fullscreen version.

Exactly like how it is show in above picture.

**Comment by sbatten** [comment]
Ah, understood, I might consider this request a subset of another one: `Allow users to configure and save layouts`. Thoughts?

/cc @joaomoreno @isidorn
