### ISSUE TITLE
both win & linux, vsc can not recognize c function name

### ISSUE THREAD

**Issue by micyng** [microsoft/vscode#84965]
Issue Type: <b>Bug</b>

like in pjproject-2.9 (https://github.com/pjsip/pjproject), in pjlib/src/pj/ioqueue_select.c, the function name "pj_ioqueue_poll" can not be recognized, it just shows "..." in function name list when cursor located in that scope

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-117-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (11.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: x|
|OS|Linux x64 4.4.0-117-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz (8 x 2499)|
|Memory (System)|31.42GB (3.40GB free)|
|VM|100%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.47.2
code-gnu-global|aus|0.2.2
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
Go|ms-|0.11.9
rust|rus|0.7.0

</details>

**Comment by rebornix** [comment]
Please file issue against the C++ extension you are using, which provides the language feature for C files.
