### ISSUE TITLE
Global search should search file names as well 

### ISSUE THREAD

**Issue by nzig** [microsoft/vscode#84963]
Related: #75252
I think it would be useful to have Ctrl+Shift+F search also show results from file names as well as contents.

This is of course possible with Ctrl+P, but sometimes it is not obvious that I should be searching for a file name instead of contents.

As an example, I was recently reviewing some [Django](https://www.djangoproject.com/) code, and trying to find where a [command](https://docs.djangoproject.com/en/2.2/howto/custom-management-commands/) was implemented. Not being familiar with Django, I was confused when I did a Ctrl+Shift+F for the command name and found nothing. Only after some investigation did I realize that Django discovers commands by looking for certain files, and so each command is implemented in a file with the same name as the command. Thus, the name of the command does not necessarily appear in any file in the project.

I think searching for a string to find related code is a common use case, and my intuitive assumption was that Ctrl+Shift+F would find any mention of the search string in the project. Implementing this feature would IMO move the search functionality closer to user's mental model of search.

**Comment by somarlyonks** [comment]
As far as I'm concerned, you problem is that you are not familiar with `Django`🙄

#36125

**Comment by nzig** [comment]
@somarlyonks Obviously that is one problem :)
But I think it is quite common to use search to find things in code, particularly unfamiliar code.

**Comment by NotWearingPants** [comment]
As odd as this use case sounds, it does come sometimes. I think a setting to search file names as well wouldn't hurt.

**Comment by roblourens** [comment]
There is another feature request for a "search everything" but that is a very different feature from "search in text".
