### ISSUE TITLE
Markdown preview editor shows icon even though I disabled file icons

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84962]
![image](https://user-images.githubusercontent.com/900690/68991149-c8ac4280-085b-11ea-9c57-283160b21140.png)

**Comment by DiamondYuan** [comment]
i can fix this issue.

**Comment by DiamondYuan** [comment]
This issue fixed in 1.40.1 ?

```
版本: 1.40.1
提交: 8795a9889db74563ddd43eb0a897a2384129a619
日期: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```


![image](https://user-images.githubusercontent.com/9692408/69004495-0fc73000-094f-11ea-8142-5af03b97c086.png)

**Comment by mjbvz** [comment]
Still repos for me in current insiders builds: 

<img width="197" alt="Screen Shot 2019-11-18 at 10 44 18 AM" src="https://user-images.githubusercontent.com/12821956/69080215-65074e00-09f0-11ea-969a-8ad874cc437a.png">

**Comment by DiamondYuan** [comment]
> Still repos for me in current insiders builds:
> 
> <img alt="Screen Shot 2019-11-18 at 10 44 18 AM" width="197" src="https://user-images.githubusercontent.com/12821956/69080215-65074e00-09f0-11ea-969a-8ad874cc437a.png">

```
1c9fd8a597 <2019-11-18> [chrisdias] | update distro (HEAD -> master, origin/master, origin/HEAD)
```

I still can't repeat it。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/69119279-0665d100-0ad1-11ea-9a45-15952080d058.png)

**Comment by mjbvz** [comment]
@misolori, @aeschli, @sbatten Webview used the `show-file-icons` css class to toggle the icons. Was the behavior around this class changed recently? I now see that is always set, even when file icons are disabled?

![Screen Shot 2019-11-19 at 4 52 24 PM](https://user-images.githubusercontent.com/12821956/69199515-08d62400-0aed-11ea-8e0f-14e53abed0cf.png)

I believe it used to only be set if there was an active fileIcon theme. Is there some other css property we should be looking for instead?

**Comment by misolori** [comment]
I haven't updated any file icon classes

**Comment by bpasero** [comment]
@mjbvz I think the class is always there but as a user I have selected the file icon theme "none" and thus would not expect any icons. However I see the the markdown extension simply adds an icon to the editor here:

https://github.com/microsoft/vscode/blob/65050271c24788f74456cc9210931dbecf9c79c5/extensions/markdown-language-features/src/features/preview.ts#L515

So possibly this icon is just there independent of my file icon choice. I think we need to improve this and possibly not have icons in custom editors / web view editors if the user has no file icon theme enabled.

**Comment by dvrylc** [comment]
Hi can I take this issue?

**Comment by mjbvz** [comment]
@dvrylc sure
