### ISSUE TITLE
Not sure I understand the need for two settings for workbench.editor.enablePreview

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8496]
Testing #7854 

Why is there a special setting `workbench.editor.enablePreviewFromQuickOpen` ?

AFAIK editors can be opened via ctrl+click to go to definition, via ctrl+click to follow a link, from the extension host, etc.

Do you plan to add a config key for each of those? If not, why the special `workbench.editor.enablePreviewFromQuickOpen`

**Comment by bpasero** [comment]
@alexandrudima yes we have some people asking for globally enable or disable preview and some users that want to have an editor in non-preview mode when you use quick open. I do agree that eventually we would need settings for all those places.

**Comment by alexandrudima** [comment]
So the usecase you mention is 
 `workbench.editor.enablePreview = true, workbench.editor.enablePreviewFromQuickOpen = false` ?

But what does it mean when I set `workbench.editor.enablePreview = false, workbench.editor.enablePreviewFromQuickOpen = true`

**Comment by bpasero** [comment]
@alexandrudima yes you found the issue with that solution, what I really need is a way to provide settings that impact other settings below. If I had UI it would be something like VS solution to this:

![image](https://cloud.githubusercontent.com/assets/900690/16453042/ab83fb9e-3e0b-11e6-8d00-59163c314583.png)

With using JSON I am not sure how to express this.

**Comment by alexandrudima** [comment]
:+1: I don't know either. Maybe @aeschli knows

`workbench.editor.enablePreview` could be of type false | { quickOpen: boolean; }

I wasn't fishing for the issue, I simply didn't realize these two settings are hierarchical when I saw the settings description.

**Comment by bpasero** [comment]
Yeah, some UI would totally help here, just the keys is not enough.
