### ISSUE TITLE
Php - JS - HTML mixed code coloring/highlighting doesn't work whil in PHP language mode

### ISSUE THREAD

**Issue by cihanfethi-hizar** [microsoft/vscode#84974]
- VSCode Version: 1.40
- OS Version: Linux Ubuntu 18.04

Steps to Reproduce:

1. Open a php file 
2. Be sure that VS Code is in PHP Language Mode
3. Write php, js & html in this same file
4. Notice that only php expressions are highlighted. Js & Html expressions are seen as a plain non-formatted text.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, disabling / re-enabling php extensions didn't change anything.

I have to rollback to VS Code 1.39 update 2 version, in order to continue my coding.

**Comment by roblourens** [comment]
Please share a sample file and a screenshot, and tell me what theme you are using.

**Comment by cihanfethi-hizar** [comment]
I d already explained the re-produce scenario.
I am using at the moment 1.39.2, which is fine. In order to provide you screenshot, I have to re-upgrade my VS Code to 1.40, which is not possible for me because after that I will have to re-downgrade to 1.39.2 in order to continue my work.

I think I was sufficiently clear with the case.
