### ISSUE TITLE
Adding spaces

### ISSUE THREAD

**Issue by jongmana** [microsoft/vscode#84975]
Issue Type: <b>Bug</b>

Im using VSC on a Chromebook and since 1.40 I often encounter the problem that when I swtich to VSC (alt+tab | search+]) that the editor very fast keeps adding spaces until I hit a key.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 4.19.69-06666-g6c4f8cbba24e

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (8 x 1799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|4.84GB (1.49GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.1
vscode-markdownlint|Dav|0.32.0
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.1.2
prettier-vscode|esb|3.6.0
plantuml|jeb|2.13.3
asciidoctor-vscode|joa|2.7.6
vscode-styled-components|jpo|0.0.27
vscode-erd-preview|kai|4.0.4
copilot-vscode|Met|1.3.0
python|ms-|2019.10.44104
vscode-typescript-tslint-plugin|ms-|1.2.3
java|red|0.53.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.0
code-spell-checker|str|1.7.20
code-spell-checker-dutch|str|0.2.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0

</details>

**Comment by rebornix** [comment]
@Tyriar starting from you as I'm not sure if we officially support chromeos.

**Comment by Tyriar** [comment]
We do not support ChromeOS https://code.visualstudio.com/docs/supporting/requirements
