### ISSUE TITLE
Error on attempt to sync settings

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#8497]
![image](https://cloud.githubusercontent.com/assets/8189808/16450558/ef6371fe-3dfd-11e6-97ba-9753d40b5301.png)

![image](https://cloud.githubusercontent.com/assets/8189808/16450564/01cbc9ae-3dfe-11e6-85ca-41af2579c9ca.png)

I tried to upload my settings via https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync and encountered above error

**Comment by bpasero** [comment]
Please report issues for extensions to their related GH repositories.

**Comment by con-ssc** [comment]
Ok, sorry.
