### ISSUE TITLE
Code folding for #ifdef's

### ISSUE THREAD

**Issue by janwilmans** [microsoft/vscode#84977]
![image](https://user-images.githubusercontent.com/5933444/69000520-4a8a8300-08d1-11ea-82f0-724384d7a0ee.png)

I don't care who fixes it, could you please resolve it amongst yourselves, fix the relevant issue and close the other. see https://github.com/microsoft/vscode-cpptools/issues/407#issuecomment-554684494

**Comment by aeschli** [comment]
See my comment https://github.com/microsoft/vscode-cpptools/issues/407#issuecomment-554887233

https://github.com/microsoft/vscode-cpptools/issues/407 is the open issue for the feature you were requesting.
#66404 is closed
