### ISSUE TITLE
Provide an option to toogle which can move cursor automatically towards the terminal when program ask for user input inorder to give output.

### ISSUE THREAD

**Issue by PranavBhattarai** [microsoft/vscode#84986]
This feature will certainly **ramped up the speed** of programming if there was such an option for the user to enable.
![VS Code in Ubuntu 19.10](https://user-images.githubusercontent.com/32763112/69005994-75b4b700-0951-11ea-986d-7ce93c0e174c.png)

_But do not auto-move the cursor to the output terminal when there is no output because that would be a waste of time. No output appears when there is an error or when there is a "print hello world" type of program which don't ask for user input._

**Comment by Tyriar** [comment]
I don't think we should do something like this as it would involve parsing all output in the terminal which is potentially very expensive, plus stealing focus away like this is an accessibility issue. I'd suggest just getting used to ctrl+` to switch to the terminal quickly.
