### ISSUE TITLE
Allow friendly name for task input pickString options

### ISSUE THREAD

**Issue by haugerbr** [microsoft/vscode#84983]
It would be nice if we could provide a friendly name for a pickstring option so in cases where you want the option values to be something less readable, like a filepath, you could provide a more readable friendly name to the user.

**Comment by haugerbr** [comment]
@alexr00 is this able to be moved to the backlog already? Not entirely sure how the voting works.

**Comment by alexr00** [comment]
If anyone is interested in working on this, checkout https://github.com/microsoft/vscode/blob/f135502212655c34e5e8cf74d125b2b20e302386/src/vs/workbench/services/configurationResolver/browser/configurationResolverService.ts#L267
and 
https://github.com/microsoft/vscode/blob/f135502212655c34e5e8cf74d125b2b20e302386/src/vs/workbench/services/configurationResolver/common/configurationResolverSchema.ts#L53
