### ISSUE TITLE
outline view work abnormal with <linux/list.h>

### ISSUE THREAD

**Issue by luantu** [microsoft/vscode#84989]
Issue Type: <b>Bug</b>

```
#include <stdlib.h>
#include <linux/list.h>

struct list_head test_head;

struct test {
    int test;
    struct  list_head node;
};

static void test()
{
    struct test *test;

    list_for_each_entry(test, &test_head, node) {
        printf("%d\n", test->test);
    }
}

```

outline expected: function test, 
but  list_for_each_entry ..

![image](https://user-images.githubusercontent.com/5064819/69007030-4fa00e80-0973-11ea-9563-92979a9df064.png)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
thief-book|C-T|0.0.9
highlight-line-vscode|cli|0.0.1
vsc-material-theme|Equ|30.0.0
c-cpp-flylint|jbe|1.2.4
csharpextensions|jch|1.3.1
docomment|k--|0.1.8
vscode-sshfs|Kel|1.16.3
Lua|key|0.0.9
vscode-simple-icons|Lau|1.11.10
VS-code-drupal|mar|0.0.12
yang|mar|0.1.3
theme-monokai-pro-vscode|mon|1.1.14
vscode-language-pack-zh-hans|MS-|1.40.2
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.2-insiders
csharp|ms-|1.21.7
debugger-for-chrome|msj|4.12.1
korofileheader|OBK|4.3.1
material-icon-theme|PKi|3.9.1
highlight-words|rsb|0.1.4
code-settings-sync|Sha|3.4.3
guides|spy|0.9.3
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8

(4 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
I assume it's the cpptools extension (https://github.com/microsoft/vscode-cpptools) that provides the outline.
Would you mind filing the issue there? (Unfortunately the issue-transfer took only works with write access on the both repos, which I haven't)
