### ISSUE TITLE
Can't use rsync in WSL 2

### ISSUE THREAD

**Issue by gnilsson2** [microsoft/vscode#84996]
Trying to use  rsync in WSL 2 fails
Had to revert to WSL 1

**Comment by rebornix** [comment]
It doesn't seem to be related to VS Code core, thanks.

**Comment by gnilsson2** [comment]
https://code.visualstudio.com/docs/remote/troubleshooting#_questions-and-feedback
Is however related
should be updated with a hint that it only works for WSL 1
