### ISSUE TITLE
Problems when getting started

### ISSUE THREAD

**Issue by getupgetup** [microsoft/vscode#84990]
Hi, I'm trying to use vscode with WSL. Althrough I follow this [https://code.visualstudio.com/docs/cpp/config-wsl](url) step by step, i can't get the right feedback. This really annoyed me and what's the problem??
Here's my all files
c_cpp_properties.json:
![捕获](https://user-images.githubusercontent.com/10446834/69007027-35fec700-0973-11ea-958b-7028ba1ad82e.JPG)

launch.json:
![捕获](https://user-images.githubusercontent.com/10446834/69007081-f2f12380-0973-11ea-8cd7-db6011a1290f.JPG)

tasks.json:
![捕获](https://user-images.githubusercontent.com/10446834/69007088-0bf9d480-0974-11ea-94a0-7146886bb23f.JPG)

helloworld.cpp:
![捕获](https://user-images.githubusercontent.com/10446834/69007052-aad20100-0973-11ea-8d50-bc08da31e805.JPG)

and when I use ctrl+shift+B to build task, I got stucked by this:
![捕获](https://user-images.githubusercontent.com/10446834/69007095-35b2fb80-0974-11ea-9a2c-15c604d81b6c.JPG)

Can anyone help me please?

**Comment by aeschli** [comment]
@getupgetup It would be better to ask questions like this on stackoverflow. Also, you might want to translate what the error in the last screenshot says.
