### ISSUE TITLE
Lubuntu 18.04: Graphics artefacts after updating vscode

### ISSUE THREAD

**Issue by DmStrelok** [microsoft/vscode#84992]
Issue Type: <b>Bug</b>

After updating VS code I observe graphic artifacts. I observed the same issue on latest code-insiders.
This issue isn't reproduce on code_1.39.2-1571154070_amd64.
The similar issue: https://github.com/microsoft/vscode/issues/82537, https://github.com/microsoft/vscode/issues/80766
But they closed and there are no solution, therefore I open new issue.

VS code:
![2019-11-17-155600_1920x1080_scrot](https://user-images.githubusercontent.com/33811006/69008129-ec54b300-0957-11ea-9fcd-ded73b8777b6.png)
![2019-11-17_code(2)](https://user-images.githubusercontent.com/33811006/69008133-f24a9400-0957-11ea-9bd4-6b04fe69ca11.gif)
VS code-insiders:
![2019-11-17_insiders(2)](https://user-images.githubusercontent.com/33811006/69008137-01314680-0958-11ea-8788-325544606a55.gif)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.0.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3763)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (12.55GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-language-pack-ru|MS-|1.40.2
cpptools|ms-|0.26.2-insiders
vscode-arduino|vsc|0.2.28

</details>

**Comment by gjsjohnmurray** [comment]
Does it also occur if you launch with the ``` --disable-gpu``` argument?

**Comment by DmStrelok** [comment]
I have tryed launch with the --disable-gpu argument and it worked.

**Comment by deepak1556** [comment]
Since its a gpu issue vscode can't fix it on our end, will have to wait for fix from chromium, for the moment you can configure this from within vscode

```
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
```

**Comment by DmStrelok** [comment]
Ok, thanks.
It helped me.
