### ISSUE TITLE
Overtyping Brackets doesn't work after backslash

### ISSUE THREAD

**Issue by ENM185** [microsoft/vscode#84998]
- VSCode Version: 1.40.1
- OS Version: Mac 10.15

Steps to Reproduce:

1. Type `(` (so that it is completed with a `)` to the right of the cursor)
2. Type `\)`. Notice that there are now two closing parentheses, rather than one. This only happens after the recent update.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@ENM185 What programming language are you using that accepts `\)` ?

**Comment by ENM185** [comment]
@alexandrudima I'm using LaTeX with `\(...\)` blocks. However, the issue occurs in any language (even plaintext).

**Comment by alexandrudima** [comment]
This is caused by https://github.com/microsoft/vscode/commit/55afde9a02ffd082b54b7be32ab4464c6e078e4a
