### ISSUE TITLE
Go Plugin: Show Method Type in Symbol Browser

### ISSUE THREAD

**Issue by kylebrandt** [Microsoft/vscode#85]
When using the symbol browser, I have methods that are bound to different types of the same name:

![image](https://cloud.githubusercontent.com/assets/1692624/11250408/6e55bed6-8dfa-11e5-8510-0f268552c192.png)

It would be nice to see which type each of those methods are for in that view.

**Comment by DanielRosenwasser** [comment]
Sounds like this should be filed for the Go plugin's repo: https://github.com/Microsoft/vscode-go/issues/new
