### ISSUE TITLE
Code Lens using Octicon cannot be triggered

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#85007]
- VSCode Version: 1.40.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add a Code Lens which only contains octicon, like `$(check)`
2. Binding a command to that Code Lens
3. The Code Lens cannot trigger the command when clicking on it.

**Comment by jrieken** [comment]
Not a regression but an oversight with #82062 - octicons/codicons are rendered as `<span>` and the code lens widgets checks for clicks on `<a>` elements
