### ISSUE TITLE
'w' is somehow configured to paste into the terminal

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85008]
Issue Type: <b>Bug</b>

Starting with today's insiders -- the `w` key is bound to `workbench.action.terminal.paste` when `terminalFocus`

/cc @Tyriar 

VS Code version: Code - Insiders 1.41.0-insider (fe03510f9e9fb269ca35da0ea600dd95279fa2b7, 2019-11-18T05:31:02.684Z)
OS version: Windows_NT x64 10.0.19025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Roman-Popov** [comment]
Same thing here, lol

**Comment by danielstaf** [comment]
+1

**Comment by alexr00** [comment]
![image](https://user-images.githubusercontent.com/38270282/69042361-5f5e3800-09f1-11ea-98bc-4fae3155821f.png)
From default keybindings json:
```
{ "key": "w",                     "command": "workbench.action.terminal.paste",
                                     "when": "terminalFocus" },
{ "key": "w",                     "command": "workbench.action.terminal.paste",
                                     "when": "terminalFocus" },
```

**Comment by Tyriar** [comment]
Problem is https://github.com/microsoft/vscode/pull/84438 using `KeyCode.Ctrl` instead of `KeyMod.CtrlCmd`

**Comment by Tyriar** [comment]
Works as expected if you copy `w` before using the terminal 😆. Fix and new insiders coming soon.
