### ISSUE TITLE
git doesn't work when terminal is wsl 

### ISSUE THREAD

**Issue by eromoe** [microsoft/vscode#85003]
- VSCode Version: 1.4.0
- OS Version: win10
- wsl : ubuntu1804

I got `no source control provider registered` in many git repo .

Steps to Reproduce:

1. choose default terminal to wsl 
2. git not work 

----

My git path is `C:\msys64\usr\bin\git.exe` , `Gti: show ouput`  would print it .
I also installed `git` in wsl (by root).  I found terminal in vscode have no perrmission to run git when default terminal was wsl .
Then I changed default terminal to cmd , git recovered .

I think :
1. select a available git path (remember the execution terminal)
2. select default terminal shouldn't change git , unless you change git path .

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?

**Comment by eromoe** [comment]
Today I found it broken again  `Git: Show Git Output` : 
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Users\Kasim\AppData\Local\Programs\Git\cmd\git.exe
Looking for git in: C:\msys64\usr\bin\git.exe
Using git 2.21.0 from C:\msys64\usr\bin\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir

```

Terminal is OK:
![image](https://user-images.githubusercontent.com/3938751/69203524-82b6ed80-0b7f-11ea-93f2-6163ff113eaf.png)

**Comment by joaomoreno** [comment]
> Using git 2.21.0 from C:\msys64\usr\bin\git.exe

We do not support msys64 git. Only Git for Windows from https://git-scm.com/

**Comment by eromoe** [comment]
@joaomoreno  What ?  I think vscode should support git in wsl at least.

**Comment by joaomoreno** [comment]
It does support Git in WSL. Simply open a window in WSL and git will work.

**Comment by eromoe** [comment]
Yes, it isn't  . git had worked successully once I swiched terminal from wsl to cmd . 
PS: It used msys git in both terminal settings .
