### ISSUE TITLE
OUTLINE not work for C++ source files in WSL

### ISSUE THREAD

**Issue by zhangguofu** [microsoft/vscode#85002]
- VSCode Version: 1.40.1
- OS Version: WIN10 10.0.18363.476
- Extensions:
  1. Remote-WSL 0.40.3
  2. C/C++ 0.26.1
  3. C++ Intellisense 0.2.2
  4. Include Autocomplete 0.0.4

Steps to Reproduce:
1. open folder in Remote WSL (ubuntu 18.04)
2. open main.cc and it always shows that "Loading document symbols for main.cc ..."

Does this issue occur when all extensions are disabled?: Yes/No
when all extensions are disabled, OUTLINE shows that "The active editor cannot provide outline information"

furthermore, when the cursor stays at number 0, it shows "loading...", Find All References for functions gives nothing,  
![0](https://user-images.githubusercontent.com/6027358/69020374-350b7b00-09ef-11ea-9dc2-c645524eac6d.png)
![outline](https://user-images.githubusercontent.com/6027358/69020375-35a41180-09ef-11ea-87c7-d9c6e6b8e66d.png)
![reference](https://user-images.githubusercontent.com/6027358/69020376-363ca800-09ef-11ea-8edf-352059b9156a.png)

**Comment by egamma** [comment]
Please file the issue against the C++ extension.
