### ISSUE TITLE
VS 1.40.1 node debugger fails to attach if VSC started from different mounted drive on Linux

### ISSUE THREAD

**Issue by SanjayVyas** [microsoft/vscode#85005]
- VSCode Version: 1.40.1
- OS Version: Ubuntu 18.04.3

node debugging fails to stop at breakpoint if folder is opened on another mounted drive on Linux. Happens for all types of FS - ext4/ntfs etc.

Steps to Reproduce:

1. launch code
cd ~
code .
2. open a folder on another mounted disk
Ctrl-K Ctrl-O /mnt/workdisk/projects/simple
3. Select a .js file and press F5 to debug
Debugger will start but fail to attach.
Debugger will not stop at any breakpoint

4. Now launch code from mounted disk
cd /mnt/workdisk/project/simple
code .
2. open a folder on another mounted disk
Ctrl-K Ctrl-O /mnt/workdisk/projects/simple
3. Select a .js file and press F5 to debug
Debugger runs perfectly, stopping at breakpoints

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@SanjayVyas I cannot reproduce the issue you are seeing on Ubuntu with VS Code 1.40.1. 

Does the problem still occur for you if you disable all extensions?
