### ISSUE TITLE
go to definition not working

### ISSUE THREAD

**Issue by shamsulaman786** [microsoft/vscode#85017]
Issue Type: <b>Bug</b>

When I'm trying to get the definition of any method from called place. no definition found is coming.
kindly give me any solution.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 897)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (0.71GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
sublime-keybindings|ms-|4.0.3
vetur|oct|0.22.6

</details>

**Comment by jrieken** [comment]
This is not very informative and doesn't allow me to reproduce anything. Go to definition works for me, so please add more information, like in what language, in what file, at what position you are trying this etc

**Comment by xmik** [comment]
I confirm @shamsulaman786's problem. I have it in Visual Studio Code 1.38.1, working with C#. It is actually hard to reproduce, because it sometimes works (on simple cases like 2 new C# classes and one of them references the other) and sometimes not.

**Comment by xmik** [comment]
I can reproduce it with the following code:
```
using System;
using Microsoft.AspNetCore.Hosting;

namespace MyCompany.Tests
{
    public class TestServerBuilder
    {
        private IWebHostBuilder hostBuilder;

        public TestServerBuilder()
        {
            hostBuilder = new WebHostBuilder();
        }
    }
}
```

When I right-click on IWebHostBuilder and then choose "Go to definition", then there is the caption: "No definition found for 'IWebHostBuilder'".
