### ISSUE TITLE
javascript.suggest.includeAutomaticOptionalChainCompletions isn't working

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#85015]
This happens in current Insiders 1.41.0

- VSCode Version: Insiders 1.41.0
- OS Version: macOS 10.15.1

Steps to Reproduce:

1. Set `"javascript.suggest.includeAutomaticOptionalChainCompletions": false,`
2. Set `"typescript.suggest.includeAutomaticOptionalChainCompletions": false,`
3. Copy the following to a `JS` and a `TS` file:

```
const adventurer = {
    name: 'Alice',
    cat: {
        name: 'Dinah'
    }
};

const dogName = adventurer
```

4. Write `?.` in front of `const dogName = adventurer` and notice that automatic optional chain completions are still triggered.

Note: In VS Code v1.40.1 changing both settings to true doesn't trigger the completion.

Does this issue occur when all extensions are disabled? Yes

**Comment by mjbvz** [comment]
This setting controls if `?.` is automatically inserted if you accept a suggestion for an optional member.

It has no effect if you manually type out `?.`

**Comment by andrecasal** [comment]
Ah thanks for the clarification @mjbvz. How does VS Code know to suggest members that are optional if there are no interfaces in plain JS? Is TS providing the interfaces, like when Automatic Type Acquisition is used for plain JS libraries like jQuery?

**Comment by mjbvz** [comment]
Either through type inference, jsdocs, `d.ts` files (type acquisition)

**Comment by andrecasal** [comment]
Great, thanks! 👍

**Comment by andrecasal** [comment]
Hey @mjbvz, quick question: aren't optional chain completions supposed to work with this example?

```
/**
 * @param {object} adventurer Information about the adventurer.
 * @param {string} adventurer.name The name of the adventurer.
 * @param {object} adventurer.cat The adventurer's cat.
 * @param {string} adventurer.cat.name The name of the cat
 * @param {object} [adventurer.dog] The adventurer's dog.
 * @param {string} adventurer.dog.name The name of the dog.
 */
function test(adventurer) {
	const dogName = adventurer.
}
```
When I press `.` in front of `adventurer`, `dog?` shows up in the suggestions box but when I select it, the ? isn't inserted before dog as such `adventurer?.dog`. Isn't VS Code supposed to insert `adventurer?.dog` when `javascript.suggest.includeAutomaticOptionalChainCompletions` is set to true?

> I'm trying to figure this setting out as it's the last from my [playlist](https://www.youtube.com/watch?v=0P0mdawQ13A&list=PLVwLx67OHLu1HIbCihg3cohaM5eCarbiQ).

**Comment by mjbvz** [comment]
This setting only works if you have strict null checking enabled for your project. Basically, we only insert `?.` if using normal `.` would have resulted in an error instead

**Comment by andrecasal** [comment]
I thought strict null checking only applied to typescript through the `"compilerOptions": { "strictNullChecks": true }` option. I tried putting that inside the `jsconfig.js` file on a project but `adventurer.dog = null;` didn't yield an error.

Maybe I should ask the documentation team for an example/clarification?

**Comment by mjbvz** [comment]
Actually looks like there is a bug in jsdoc case. Here's simple code that demonstates how the feature works:

```js
const a = Date.now() > 10 ? { x: 1 } : undefined;

a // complete `x`
```

With the following jsconfig:

```json
{
    "compilerOptions": {
        "strict": true,
        "checkJs": true
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/35485 to track no error being generated while accessing values on optional properties in strict mode

**Comment by andrecasal** [comment]
Thanks @mjbvz! When I insert a `.` in front of a, no suggestions pop up.

**Comment by andrecasal** [comment]
They do in Insiders v1.41.0 👌

**Comment by andrecasal** [comment]
But setting `"javascript.suggest.includeAutomaticOptionalChainCompletions"` to `false` still inserts the `?.x`.
