### ISSUE TITLE
Please add array align  Feature in vscode

### ISSUE THREAD

**Issue by tarikmanoar** [microsoft/vscode#85016]
When I was using ```PHPSTROM``` there are a lot of features for code formatting and many more.
But in vscode can you guys add align the multiline array.

# here is some tip

In PhpStrom there are some facilities which are ```short array``` ```Align when multiline``` and many more
 <br><br>

*Here is an example*

http://prntscr.com/pyfkc8

[Another Link][1]

Now I want to align array in vs-code ....
# How can I do that?
## This is a normal Array
```php
$x=array(
 0 => "zero",
 123122 => "one two three",
 251=> "two five"
);
```
# Now I want Like this
```php
$x=[
   0   => "zero",
   123 => "one two three",
   25  => "two five"
];
```

Is this possible is vs-code?

  [1]: https://i.stack.imgur.com/n2vep.jpg

**Comment by egamma** [comment]
Please try the following extension https://marketplace.visualstudio.com/items?itemName=wwm.better-align
