### ISSUE TITLE
Very difficult to find file's path with tabs

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8501]
Testing #7854

1. the hover takes very long to show (maybe this hover can be made faster?)
2. I need to hover over the text and not over the tab area

**Comment by bgashler1** [comment]
I like your point @alexandrudima about making hover on the whole tab.  I too found it a little awkward when it should be very easy..  @bpasero is this doable?

As far as the timing, how about we first make that hover change and see if that fixes the problem because the hover target will be so easy to hit accurately.

I worry decreasing the delay with such a large hover area may make this hover tip popup more than is desirable.

**Comment by Tyriar** [comment]
I raised this earlier here https://github.com/Microsoft/vscode/issues/7960, wanting to be able to get at the path using just the keyboard.

**Comment by bpasero** [comment]
The hover is native and the timing cannot be changed. Introducing a custom hover is possible but we do this nowhere else. I have no good solution for this other than suggesting to disable tabs if you really need the path to be visible.

**Comment by bpasero** [comment]
There is actually an extension that just puts the full path of the file to the status bar: https://marketplace.visualstudio.com/items?itemName=RoscoP.ActiveFileInStatusBar

![image](https://cloud.githubusercontent.com/assets/900690/16540620/84237bbc-406b-11e6-8f46-a96388eb67f2.png)

**Comment by Tyriar** [comment]
@bpasero that's good enough for me :+1:

**Comment by stevencl** [comment]
That seems like a fine solution. In fact, I was convinced that we had designed that in our original mockups but it turns out we didn't. We should consider just doing this I think.

**Comment by bpasero** [comment]
I like to keep this up for an extension, if we did this out of the box, many people might find it annoying and ask for a way to disable.

**Comment by stevencl** [comment]
If this turns out to be a problem for only a few people then I'm fine with an extension. But if this turns out to be a problem for a large number of people then we really should reconsider and figure out how to solve this out of the box.

**Comment by bpasero** [comment]
Btw I still think we should maybe look into a custom hover if the native hover is so hard to be used. But we can leave this closed until we get more feedback from users once June is out 👍

**Comment by alexandrudima** [comment]
How does this extension target my specific two points above:

> 1. the hover takes very long to show (maybe this hover can be made faster?)
> 2. I need to hover over the text and not over the tab area

I understand point 1 is non-trivial as we now use the native hover.
How about point 2? Isn't that a low hanging fix?

**Comment by bpasero** [comment]
@alexandrudima sorry, those are good points, I will open a separate issue on the hover thing.

**Comment by alexandrudima** [comment]
@bpasero thank you :+1:
