### ISSUE TITLE
PHP FQCN does not match in fuzzy finder

### ISSUE THREAD

**Issue by umpirsky** [microsoft/vscode#85013]
- VSCode Version: `1.41.1`
- OS Version: `Ubuntu 18.04.3 LTS`

Steps to Reproduce:

1. `Ctrl + P` - to trigger fuzzy find
2. Type fully qualified PHP class name (e.g `Symfony\Bundle\FrameworkBundle\Controller\Controller`)

It should find PHP classes by fully qualified class names, but looks like `\` breaks matching. `Symfony/Bundle/FrameworkBundle/Controller/Controller` works, but `Symfony\Bundle\FrameworkBundle\Controller\Controller` does not.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
@umpirsky CTRL+P operates on file and path names not on class names and linux '/' is the path separator.

**Comment by umpirsky** [comment]
How to find a class then?

**Comment by egamma** [comment]
Please try one of the PHP extensions.

**Comment by umpirsky** [comment]
I already have https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense.

**Comment by egamma** [comment]
The command to navigate to a symbol in the workspace is called 'Go To Symbol in Workspace' (menu Go>Goto Symbol in Workspace...). This function should be implemented by the PHP extension you are using. If it is not then this is an issue with the PHP extension you are using and you should report the issue/feature request against the PHP extension.

An alternate PHP extension you can try is https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by umpirsky** [comment]
That one works better, thanks. Still a bit unpredictable but better.
