### ISSUE TITLE
Terminal not showing complete output unless resized

### ISSUE THREAD

**Issue by mfaheemakhtar** [microsoft/vscode#85010]
Issue Type: <b>Bug</b>

Just installed the update and looks like the terminal is broken.

I'm unable to see the complete output in the terminal unless I resize it.

Works fine with `--disable-extensions`.

Probably related to #85004.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 4.15.0-66-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 3026)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.44GB (0.78GB free)|
|Process Argv|--no-sandbox --unity-launch /home/mfa/back-end|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
prettier-vscode|esb|3.6.0
aws-cli-configure|mar|0.3.0
dotenv|mik|1.0.1
sort-lines|Tyr|1.9.0
material-theme|zhu|3.0.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
If you bisect your enabled extensions can you identify which one causes the problem?

**Comment by mfaheemakhtar** [comment]
@gjsjohnmurray, I'll do it tonight when I'm at home.

**Comment by mfaheemakhtar** [comment]
Hi, I've downgraded because of the font color being washed out/dull. Probably a theme issue (One Dark Pro). I'll see if I can replicate it on my Windows machine tonight.

**Comment by Tyriar** [comment]
When it happens can you also check devtools console (via help menu) for errors?
