### ISSUE TITLE
Debug configuration ignored sometimes

### ISSUE THREAD

**Issue by fefrei** [microsoft/vscode#85012]
Issue Type: <b>Bug</b>

Unfortunately, this issues does not reproduce reliably. However, I've seen it happen multiple times and on different systems, so I'm reporting it here.

Steps to reproduce:

1. Have a workspace with one debug configuration set up.
2. Start VS Code.
3. Go to the debug activity.
4. Observe that next to the ▷ button, your debug configuration is selected.
5. Click ▷.

The expected result, and what happens often, is that your debug configuration runs. But sometimes, what happens instead is that VS Code behaves as if no debug configuration was set. (In my case, I'm editing JS files, so VS Code asks whether it should run the current file through Chrome or Node).
Once the issue has manifested, it reproduces reliably (and drives you insane, trying to get your debug configuration right). It can be fixed reliably by choosing something else in the debug configuration dropdown (an __Add Config__ entry does the trick), switching back to your launch configuration, and then clicking ▷.

To me, it feels like there's a race condition where sometimes, the dropdown is populated but the configuration isn't actually set.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
latex-workshop|Jam|8.4.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
powershell|ms-|2019.11.0
vsliveshare|ms-|1.0.1245
debugger-for-chrome|msj|4.12.1
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.7.20
code-spell-checker-german|str|0.1.2

</details>

**Comment by isidorn** [comment]
This should be fixed in the latest.
Please let me know if you can still reproduce with vscode insdiers and I will reopen this.
You can also wait for the next stable (in a day or so) and let me know if you can still repro.

**Comment by fefrei** [comment]
I can no longer reproduce this. Thanks a lot ❤️
I'll let you know if I ever encounter this again.

**Comment by isidorn** [comment]
Thanks for letting us know, adding verified label.
