### ISSUE TITLE
Weird colors and shapes appearing in the terminal

### ISSUE THREAD

**Issue by DjigoLab** [microsoft/vscode#85019]
- VSCode Version: 1.39.2
- OS Version: Linux Mint Cinnamon Tina 19.2

Steps to Reproduce:

1. Open the terminal
2. Write or select text on it

It basically happens everytime I use vscode, making the terminal unusable for almost everything. Also font gets expanded / streched / cut etc...

Does this issue occur when all extensions are disabled?: YES
![Screenshot from 2019-11-18 09-02-12](https://user-images.githubusercontent.com/31393623/69041000-b01c6380-09e6-11ea-90c2-f4b04125566e.png)
![Screenshot from 2019-11-18 09-19-16](https://user-images.githubusercontent.com/31393623/69041001-b01c6380-09e6-11ea-9447-7c405615cc64.png)
![Screenshot from 2019-11-18 09-22-03](https://user-images.githubusercontent.com/31393623/69041004-b0b4fa00-09e6-11ea-8ea4-b07b3bbdafa4.png)

**Comment by gjsjohnmurray** [comment]
Please try launching VS Code with the ```--disable-gpu``` option and see if the problem remains.

**Comment by IllusionMH** [comment]
/needsMoreInfo

If `--disable-gpu` doesn't work, could you try different values for `terminal.integrated.rendererType` settings (especially `"dom"`)?

**Comment by Tyriar** [comment]
Looks like a problem with canvas, you can try updating your graphics driver and if that doesn't work disable the canvas renderer with this setting:

```
"terminal.integrated.rendererType": "dom"
```
