### ISSUE TITLE
VS Code shows pending changes in freshly cloned repository

### ISSUE THREAD

**Issue by CR82** [microsoft/vscode#85023]
Issue Type: <b>Bug</b>

When i clone a repository in WSL (Ubuntu) and then open the repository with VS Code, the Source Control shows pending changes, although I didn't change anything.
git status tells me that my branch is up-to -date, as it should be.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.92GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
powershell|ms-|2019.11.0
java|red|0.53.1
cmake|twx|0.0.17

</details>

**Comment by CR82** [comment]
"git config core.filemode false" fixed my problem

**Comment by lrpinto** [comment]
Thank you CR82. That worked for me, too.
