### ISSUE TITLE
Microsoft Visual C++ 14.0 required in python

### ISSUE THREAD

**Issue by chiragsd-2001** [microsoft/vscode#85026]
Issue Type: <b>Bug</b>

Tried building an app with mysql connectivity got this error while running the script

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
flask-snippets|cst|0.1.1
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
pylingo|dia|0.0.2
vsc-python-indent|Kev|1.7.0
vscode-azureappservice|ms-|0.16.1
python|ms-|2019.10.44104
azure-account|ms-|0.8.7
cpptools|ms-|0.26.1
vscode-react-native|msj|0.13.1
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
WebTemplateStudio-dev-nightly|WAS|0.0.1929801

</details>

**Comment by egamma** [comment]
/needsMoreInfo 

>Tried building an app with mysql connectivity 

Not clear what you are referring to. What exactly is 'mysql connectivity', is this an extension?

What is the error that you saw?
