### ISSUE TITLE
files: exclude is not convenient

### ISSUE THREAD

**Issue by Icaxwu** [microsoft/vscode#85025]
In the samples directory, I only care about the code under bt_box, I don't want to exclude other directories and files one by one, what is the simpler and more convenient way?

samples/
├── actions_sdk_demo
├── application_development
├── basic
├── bluetooth
├── boards
├── bt_box
├── cpp_synchronization
├── drivers
├── grove
├── hello_world
├── kernel.rst
├── mpu
├── net
├── nfc
├── philosophers
├── samples.rst
├── sensor
├── storyapp
├── subsys
├── synchronization
├── testaudio
├── test_dsp_aec
└── testing

**Comment by gjsjohnmurray** [comment]
Any reason why your workspace can't simply point to samples/bt_box  instead of samples ?
