### ISSUE TITLE
debugger not working properly since upgrade to latest version

### ISSUE THREAD

**Issue by omar-dulaimi** [microsoft/vscode#85029]
Version: 1.40.1
OS: Linux x64 4.15.0-70-generic

Steps to Reproduce:
Just using the same flow of running a configured debug. Everything was working fine until I updated vsCode yesterday. 

Does this issue occur when all extensions are disabled?: No

**Comment by egamma** [comment]
/needsMoreInfo

Please provide detailed steps so that we can reproduce the problem. Which debugger are you using? What exactly does not work properly?

**Comment by omar-dulaimi** [comment]
both node and nodemon debuggers. But it's working now, I think the restart after the installation fix it.
Thank you
