### ISSUE TITLE
桌面开启了自动隐藏任务栏之后以及最大化之后点击最大化无法取消最大化

### ISSUE THREAD

**Issue by 1549469775** [microsoft/vscode#85020]
Issue Type: <b>Bug</b>

1. 桌面开启了自动隐藏任务栏
2. 点击最大化
3. 再点击最大化无法退出最大化状态

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.8.0
vscode-sqlite|ale|0.8.0
svelte-intellisense|ard|0.7.1
mpvue-snippets|ban|1.2.2
vscode-node-readme|ben|3.0.2
thief-book|C-T|0.0.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
wxml-vscode|cny|0.1.2
vscode-wxml|cod|0.1.9
bracket-pair-colorizer|Coe|1.0.61
git-diff-and-merge-tool|dav|1.0.1
vscode-eslint|dba|1.9.1
app-migrator|deb|0.0.6
daily-anime|dee|1.2.0
vscode-faker|dee|1.3.0
githistory|don|0.4.6
gitlens|eam|10.1.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
vsc-material-theme|Equ|30.0.0
vscode-open-in-npm|fab|1.0.4
vscode-svelte-snippets|fiv|0.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.14
terminal|for|0.0.10
project-tasks|hau|1.0.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-npm-dependency|how|1.2.2
wxss-peek|htp|0.0.3
rest-client|hum|0.22.2
simple-npm-changelog|iFa|1.0.5
path-autocomplete|ion|1.13.3
hacs|ism|1.0.0
svelte-vscode|Jam|0.9.3
search-node-modules|jas|1.3.0
git-open-diff|kap|1.3.2
git-graph|mhu|1.18.0
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.8.0
vscode-language-pack-zh-hans|MS-|1.40.2
python|ms-|2019.10.44104
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
Go|ms-|0.11.9
debugger-for-chrome|msj|4.12.1
sqltools|mtx|0.21.3
vscode-paste-image|mus|1.0.4
vsc-netease-music|non|0.0.33
vetur|oct|0.22.6
vuehelper|oys|0.1.0
material-icon-theme|PKi|3.9.1
vscode-wechat|qin|0.0.6
minapp-vscode|qiu|2.2.2
reader|ren|1.1.6
rem-px|ris|0.0.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.8.0
element-ui-snippets|SS|0.3.5
ayu|tea|0.18.0
pdf|tom|0.5.1
git-rebase-shortcuts|tre|1.0.5
terminal-tabs|Tyr|0.2.0
codelf|unb|11.7.0
JavaScriptSnippets|xab|1.7.2

(3 theme extensions excluded)

</details>

**Comment by hadzhiyski** [comment]
Hello, @1549469775 
Please submit the issue in English

**Comment by 1549469775** [comment]
My English is poor,sorry!^_^

Issue Type: <b>Bug</b>

1.  i set Automatically hide the taskbar in desktop mode was true
2. click maximize
3. click unmaximize,but cannot unmaximize

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

**Comment by NieLamu** [comment]
Yes I also met this bug.

**Comment by NieLamu** [comment]
Yes I also met this bug.
