### ISSUE TITLE
Markdown syntax highlighting is broken when using `---`

### ISSUE THREAD

**Issue by deepu105** [microsoft/vscode#85027]
Issue Type: <b>Bug</b>

1. Create a markdown file
2. Add the below content
```
# A heading

Some content paragraph

---

# Another heading

Some content paragraph

---

# Another heading

Some content paragraph

---

# Another heading

Some content paragraph

---
```
3. Check the syntax highlighting

Here is a screenshot, doesn't seem like a theme issue as I can see same issue in any theme and I don't have any markdown related extensions, so seems like a core issue

![image](https://user-images.githubusercontent.com/1107223/69046576-989aa600-09f9-11ea-99ba-fb14d9862170.png)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.3.11-300.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 4300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.02GB (12.19GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.0.28
compulim-vscode-closetag|Com|1.2.0
vscode-es-beautifier|dai|1.1.0
scala|dal|0.0.5
vscode-eslint|dba|1.9.1
javascript-ejs-support|Dig|1.1.3
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.14.2
prettier-vscode|esb|3.6.0
auto-rename-tag|for|0.1.1
todo-tree|Gru|0.0.162
vscode-test-explorer|hbe|2.14.6
mark-as-excluded|jcm|0.2.6
plantuml|jeb|2.13.4
jdl|jhi|1.9.1
vscode-peacock|joh|3.2.0
vscode-deno|jus|1.3.3
intellij-idea-keybindings|k--|0.2.37
terraform|mau|1.4.0
vscode-docker|ms-|0.8.2
vscode-kubernetes-tools|ms-|1.0.7
python|ms-|2019.10.44104
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
hide-gitignored|npx|1.0.1
material-icon-theme|PKi|3.9.1
ruby|reb|0.25.3
java|red|0.53.1
vscode-yaml|red|0.6.1
vscode-sort-json|ric|1.18.0
LiveServer|rit|5.6.1
rust|rus|0.7.0
jenkinsfile-support|sec|0.1.0
shopify-liquid|sis|2.3.0
code-spell-checker|str|1.7.20
ignore-gitignore|stu|1.0.1
easy-snippet-maker|tar|0.0.6
new-blog-post|tim|0.0.6
pdf|tom|0.5.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
gitblame|wad|3.0.1
change-case|wma|1.0.0
maximize-panes|won|0.0.5

(6 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/confirmationPending

Unable to repro on my Windows env.
![image](https://user-images.githubusercontent.com/6726799/69050354-ced82580-09f9-11ea-9986-6491c92ed705.png)

Does the language mode indicator on your status line say "Markdown"?

**Comment by deepu105** [comment]
Yes, it says markdown. Let me try to reproduce on the insider's build. Btw i'm on Linux does that matter?

**Comment by deepu105** [comment]
Ok, I found the culprit, issue was with a plugin `sissel.shopify-liquid` which was messing up the syntax highlight. Sorry for the trouble
