### ISSUE TITLE
Restore type based global symbole filtering for Ctrl+P

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#8502]
@bpasero we discussed this. for details see: https://github.com/Microsoft/vscode/issues/8013

**Comment by jrieken** [comment]
If we do it lets make this change in TypeScript. With globally filtering symbols for each and every provider  we break scenarios for languages that don't happen to use any of our hand picked highly biased TypeScript symbol kinds.

**Comment by bpasero** [comment]
@jrieken that was the idea. @dbaeumer is looking into that.

**Comment by jrieken** [comment]
@bpasero You mean the existence of [container name](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1728) as in not falsy as a hint for not being global?

It does sound better I don't know if that works for all languages... If this is an issue we should add symbol kind filter to the provider (https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1784)

**Comment by bpasero** [comment]
@jrieken yeah, the idea being that Cmd+P is for top level symbols (classes, global functions) and Cmd+T is for any symbol whatsoever. Doing this via container name would be a change without API breakage.

**Comment by dbaeumer** [comment]
As discussed with @bpasero the filtering in TS can only be done if TS knows what to filter for. There are use cases where the user wants to see only 'global' symbols and where he wants to see all symbols. If the container name is not working then we could either add an additional flag to the workspaceSymbolProvider or have two distinct providers. I would opt to have options there.

**Comment by bpasero** [comment]
Anything works for me 👍
