### ISSUE TITLE
Intergrated Terminal not showing

### ISSUE THREAD

**Issue by germansak** [Microsoft/vscode#8503]
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:07:11.483Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open Visual Studio Code
2. Go to View-> Integrated Terminal
3. Terminal shows for about 1 milisecond and then it disappears.

I've tried also with the other methods for showing it with no success (Command Pallette, Shortcut)
I've also tried to change from cmd.exe to powershell. Same results

**Comment by Tyriar** [comment]
@germansak do you have non-ascii characters in the open folder's path?

**Comment by germansak** [comment]
I'm not at my home computer right now, but probably yes (I think my username has an accent - "Germán")  :-)
Could that be the issue?

**Comment by Tyriar** [comment]
That's definitely it, I'll hopefully get a change to look at this issue (#7727) more deeply next month. In the meantime the only real workaround is to move your project folder out of the folder containing those characters :frowning:

Thanks for the quick response!

**Comment by germansak** [comment]
Ok. No problem!
Thank you for your support and congratulations for this product
I really like VS Code and use it everyday!
