### ISSUE TITLE
Drag and Drop files within VSCode editor (version 1.40.0 ) on already opened file is stopped working

### ISSUE THREAD

**Issue by Uma19** [microsoft/vscode#85030]
Till  **VSCode Version 1.39.2** => drag and dropping of the file was working property on already opened webview content which contains React dnd library ( supports Native and URL files )
But after using 1.40.0 version the above feature stopped working ?
Can you help us to fix this issue

Note: Folders and files are part of workspace

**Comment by egamma** [comment]
Please provide a minimal sample so that we can reproduce the issue.
