### ISSUE TITLE
ZSH seems to couse problems

### ISSUE THREAD

**Issue by mitevdev** [microsoft/vscode#85042]
Issue Type: <b>Performance Issue</b>

After switching to zsh as default CI on mac I have many problems with the editor (it became laggy and git got broken too). Switching back to bash solves the problems.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|16.00GB (1.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
vscode-json|and|1.5.0
ng-template|Ang|0.802.3
code-gnu-global|aus|0.2.2
color-info|bie|0.5.1
npm-intellisense|chr|1.3.0
java-decompiler|dgi|0.0.2
githistory|don|0.4.6
java-debug|DSn|0.0.2
vscode-npm-script|eg2|0.3.9
todo-tree|Gru|0.0.162
angular2-switcher|inf|0.2.0
java-properties|ith|0.0.2
sftp|lix|1.12.9
cmake-tools-helper|mad|0.2.1
angular-localization-helper|man|0.2.1
rainbow-csv|mec|1.3.1
vscode-clang|mit|0.2.3
vscode-docker|ms-|0.8.2
mssql|ms-|1.7.1
cmake-tools|ms-|1.2.2
cpptools|ms-|0.26.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
vscode-react-native|msj|0.13.1
gradle-language|nac|0.2.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.12.0
vscode-manifest-yaml|Piv|1.12.0
vscode-spring-boot|Piv|1.12.0
java-ide-pack|pve|1.2.1
java|red|0.53.1
vscode-xml|red|0.9.1
vscode-sort-json|ric|1.18.0
todo-show|suy|0.2.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-java-saber|You|0.1.0
propertylist|zho|0.0.2

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
@mitevdev many team members use zsh, can you please describe your setup and provide steps so that we can reproduce your issues.

**Comment by mitevdev** [comment]
I cannot make screenshots because the problem is not visible.

I am using VSCode also having installed plugins for Angular for web development. One of the plugins is monitoring changes in source files and compiles the project newly on demand. This is working fine when the default command shell is bash.

Wenn I change it to zsh the monitoring do not work any more. The changes are not captured, I must   terminate the running development server process manually and then start it again. Every time I do this the system gets slower and laggy.

When I try to close the VSCode editor it takes some times ~30 seconds and then the system ask me if I want to wait for the process to close or just terminate it.

I am not sure if this is an VSCode issue or problem of one of the above mentioned plugins (perhaps debugger-for-chrome). You can close this issue if it is not VSCode related.

**Comment by egamma** [comment]
@mitevdev is the project using VS Code Tasks? Are there additional shell scripts involved that are ran by zsh instead of bash?

>I am using VSCode also having installed plugins for Angular for web development. 

Can you share the extensions you have installed.

**Comment by mitevdev** [comment]
> @mitevdev is the project using VS Code Tasks? Are there additional shell scripts involved that are ran by zsh instead of bash?

Yes, they get run by zsh. I can switch back to bash and try again.

> 
> > I am using VSCode also having installed plugins for Angular for web development.
> 
> Can you share the extensions you have installed.

The extensions are listed in my initial post above.

**Comment by egamma** [comment]
@mitevdev 

>The extensions are listed in my initial post above.

Sorry, I've overlooked this.

Since you are using many extensions the problem could be caused by an extension. Can you reproduce the problem when run with the extensions disabled by starting VS Code with `--disable-extensions`.

**Comment by mitevdev** [comment]
I can confirm. The problem occurs only when I use zsh shell where another zsh script gets run.

**Comment by mitevdev** [comment]
I am closing this issue. It seems it is not editor's related. Recently I had the same problem using bash shell.

**Comment by mitevdev** [comment]
UPDATE! I've found the source of the problems. 

The problems occur when I have started another Electron App (Azure Data Studio) as well which is the case in most time. It seems both applications share same data space or whatever, the changed files in MS Code appear as "changes" in Azure Data Studio which should not have anything to do with GIT (it is a database management application).

All works fine if only MS Code is running.

**Comment by everhopingandwaiting** [comment]
I have the same problems , when upgrade to v1.42.0-insider ,  I could not change the default shell to another, 
![image](https://user-images.githubusercontent.com/6021724/71641036-30193700-2cd0-11ea-920e-ec60b9c2f998.png)
![image](https://user-images.githubusercontent.com/6021724/71641043-38717200-2cd0-11ea-9e1b-b17ac2cdf605.png)
