### ISSUE TITLE
Change all occurrences changes from import statement too

### ISSUE THREAD

**Issue by akshayat** [Microsoft/vscode#8504]
- VSCode Version: 1.2.1
- OS Version: Windown 10

Steps to Reproduce:

1. Create a TS file
2. make a variable as `private core;`
3. right click and select change all occurrences
4. change the name of variable to core1
5. `import {Component} from "angular2/core";` will be changed to `import {Component} from "angular2/core2";`

**Comment by dbaeumer** [comment]
Change all occurrences is a textual change. You can use Rename (F2) to perform an semantic rename.
