### ISSUE TITLE
snippet shortcuts stopped working

### ISSUE THREAD

**Issue by mckennatim** [microsoft/vscode#85044]
Issue Type: <b>Bug</b>

After most recent upgrade snippet prefixes no longer work. Everything is turned into an emmet html tag

VS Code version: Code - Insiders 1.41.0-insider (2014f5adccbce83d347e714206903f2bbee40dcb, 2019-11-18T09:34:04.775Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-icalendar|af4|1.0.1
code-gnu-global|aus|0.2.2
vscode-database|baj|2.2.0
cpp-extentions-pack|bou|0.2.2
c-cpp-compile-run|dan|1.0.5
vscode-eslint|dba|1.9.1
code-runner|for|0.9.14
mediawiki|jak|2.1.0
svg|joc|1.0.5
prettify-json|moh|0.0.3
python|ms-|2019.10.44104
remote-containers|ms-|0.84.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.2-insiders
platformio-ide|pla|1.9.3
java|red|0.53.1
you-complete-me|Ric|1.1.0
stardog-rdf-grammars|sta|0.1.2
vscode-langserver-turtle|sta|0.1.0
rst-vscode|tht|3.0.1
ghosttext|tok|1.1.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
debug|web|0.23.1
vscode-import-cost|wix|2.12.0
spice|xua|0.0.4

(1 theme extensions excluded)

</details>

**Comment by mckennatim** [comment]
somehow editor.tab completion got turned off at the upgrade but that still doesn't fix it. Now entering the prefix and the tab just shows a little loading tooltip

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
