### ISSUE TITLE
Protocol handler not triggered when running out of sources on Windows

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#85046]
Issue Type: <b>Bug</b>

1. Run code-oss on windows
2. Paste `code-oss://github.vscode-pull-request-github-insiders/did-authenticate` into the browser and click "Open" in resulting dialog

![protocolhandlererror](https://user-images.githubusercontent.com/3672607/69074961-42236c80-09e5-11ea-893a-73043ac9e711.png)

Works on Mac still, haven't tried Linux

VS Code version: Code - OSS Dev 1.41.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.18363

**Comment by jzyrobert** [comment]
Hi, I have tracked this down to 

> src\vs\platform\url\electron-main\electronUrlListener.ts
![Code_hAI8wXQggg](https://user-images.githubusercontent.com/20613660/69281488-3f409b80-0be0-11ea-808f-64008dbe8c13.png)

It seems that when you run Code - OSS.exe, the command is missing:
![powershell_QfDBM4tjo4](https://user-images.githubusercontent.com/20613660/69281567-639c7800-0be0-11ea-9c1a-b17db4b3b6b5.png)

By hardcoding my vscode folder location in:
![Code_r5TsVoPa6R](https://user-images.githubusercontent.com/20613660/69281632-875fbe00-0be0-11ea-8804-a852c9c01d69.png)

The app is able to open:
![7u3uZo5uWg](https://user-images.githubusercontent.com/20613660/69282026-4025fd00-0be1-11ea-83a8-cef142c3aa57.gif)

Is there a command/utility function that will give this location?

**Comment by joaomoreno** [comment]
@jzyrobert Bingo!

You should add this to the array only if not [`isBuilt`](https://github.com/microsoft/vscode/blob/770877f0bc1733145da8ec727c861076e3731938/src/vs/platform/environment/common/environment.ts#L152) and you can get that path from [one of these properties](https://github.com/microsoft/vscode/blob/acd7df14592fe8a209160220815b5980c72f909f/src/vs/platform/environment/common/environment.ts#L111-L114).

**Comment by joaomoreno** [comment]
*Verification:* This is a Windows only issue.
