### ISSUE TITLE
Web: Notification positioned out of workbench

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#85056]
Notification is absolutely positioned instead of inside the boundaries of the workbench.

![image](https://user-images.githubusercontent.com/876920/69080853-96344e00-09f1-11ea-9206-900103595155.jpg)

**Comment by rebornix** [comment]
It's caused by https://github.com/microsoft/vscode/commit/844335b389f8e3a2d4410700777b23e5db3fe459, which sets the height of the workbench as `100vh`, which is target than `100%`.

**Comment by rebornix** [comment]
@bpasero @isidorn it seems the notification center is the only element not inside the workbench grid system, which might lead to above issue whenever the workbench is not taking full layout viewport (right now we only render inside visual viewport), do you think it make sense that we make the notification center a view part and render inside the workbench?

**Comment by bpasero** [comment]
@rebornix wouldn't quick open / quick pick fall into the same category? And what is your proposal for how to render this inside the grid, surely it cannot be a grid element since it needs to be positioned over others?

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/69173206-2b981680-0ab4-11ea-90df-e10e2469b2cf.png)

Quick Open is affected by this issue as `workbench` is absolute positioned, `quick-open` is using `top: 0` so it aligns to the top border of the workbench, which is the top border of `workbench-grid-view`.

But i got your point, the grid system is flat and the notification is on the z axis so we can't make it part of the grid view. The solution can be making sure that `workbench` height aligns with its inner `workbench-grid-view`.

**Comment by eamodio** [comment]
@rebornix I pushed the change to go back to manual sizing - let me know if this resolves the issue for you.

**Comment by rebornix** [comment]
Already fixed by @eamodio on master.
