### ISSUE TITLE
Remote development on Windows side of remote host

### ISSUE THREAD

**Issue by ATL-Flaneur** [microsoft/vscode#85059]
Best I can tell from the documentation, remote development requires a glibc-based Linux host as the target. It would be handy if remote development also supported connecting to Windows hosts.

I have an SSH server running on a remote Win10 host, and when I ssh to it from my development machine, I get a PowerShell terminal and land in `C:\Users\ayank>`. But connecting with VSC gives me a bash terminal in `/home/ayank`.

Maybe there's already a way to do this that I haven't found?

**Comment by egamma** [comment]
This is supported in VS Code Insiders, pls see https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_39.md#remote---ssh-for-windows-remotes
