### ISSUE TITLE
Local extensions are being synced

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85054]
This might be as designed, `"[{\"identifier\":{\"id\":\"vscode-samples.extension-terminal-sample\"},\"enabled\":true},{\"identifier\":{\"id\":\"vscode-samples.vscode-terminal-api-example\"},\"enabled\":true}]"` is send on sync. Not sure what the expected behavior is here but they are both symlinked into the extensions dir, AFAICT we can't do anything with this local extension information so there seems to be no point in persisting it.

**Comment by sandy081** [comment]
Yes, it is expensive to check if a local extension exists in gallery or not. I do not think it is harm to store this info as while installing we ignore it.

**Comment by Tyriar** [comment]
@sandy081 I saw an extension I synced from the marketplace had a uuid property, is that enough to differentiate? After thinking about this a bit more, if local extensions are included that means the syncing will continually update if you are using 2 different machines, consider:

Computer with extension A and local extension B
Computer with extension A

Whenever the second computer updates, the first will update, causing the second to update. This will cause a lot of unnecessary writes, please reconsider.

**Comment by sandy081** [comment]
Good point, I will check if it is causing such a cycle.

**Comment by sandy081** [comment]
Yes, this is causing side loaded extension to be uninstalled after sync. So fixing this by excluding such extensions.

**Comment by sandy081** [comment]
To verify:

Machine 1:
- Have a side loaded extensions (vsix) that does not exist in Marketplace
- Sync extensions

Machine 2:
- Sync should not install above extension
- Install another extension here

Machine 1:
Verify that Sync should not remove the side loaded extension

**Comment by Tyriar** [comment]
> So the right fix is to skip such extensions to be ignored while syncing on the other machine and do not remove from the server.

@sandy081 little concerning still. Does the data send to the server still bounce between containing and not containing the local extensions? This means that history would fill up very quickly and be useless in this case and also causing unnecessary traffic.

If not, how do local extensions ever get removed from the server?

**Comment by sandy081** [comment]
> how do local extensions ever get removed from the server?

When the user uninstalls the extension, it will be removed from the server. I do not think there will be too many such side loaded extensions to increase the traffic. Only reason, I consider all extensions is that I don't want to miss any info so that user cannot access after. For eg., I also sync on the other side if there is an extension with that id in the marketplace.

**Comment by Tyriar** [comment]
@sandy081 Does the data send to the server still bounce between containing and not containing the local extensions?

If I have a local extension on computer A and not on B, is the server going to sync the local extension for A, then B will remove it and that will repeat?

**Comment by sandy081** [comment]
If machine A syncs an extension X and if machine B can't sync that extension due to any reason (it is side loaded on A or it is an UI extension that machine B can't install it) then machine B just skips it (no removal).

**Comment by alexr00** [comment]
Not sure how to verify this. I don't see my local only extension get listed in the Log (Sync) output. Is that verification enough?

**Comment by sandy081** [comment]
[comment/(https://github.com/microsoft/vscode/issues/85054#issuecomment-562113338) has verification steps

**Comment by Tyriar** [comment]
Ok, if it's skipped but included in the next upload that's fine then. Just making sure we're not causing unnecessary writes since reading will be fast and writing will be slower.
