### ISSUE TITLE
Move dialog details to description row in custom dialog?

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#85057]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/35271042/69081132-338f8200-09f2-11ea-8ac2-1ebdc71f856e.png">

The list of files in the delete confirmation dialog (custom) seem to take up a huge part of the dialog. Can we move these items the detail row? 

<img width="567" alt="image" src="https://user-images.githubusercontent.com/35271042/69081382-b284ba80-09f2-11ea-8e2d-a104125fafed.png">

**Comment by isidorn** [comment]
Yes, we can change that. From your picture I think it looks prettier, however I think the most important part of that information are actually the file names, and thus I am not sure if decreasing their size is a good move here (even though it looks better). Did we check what native explorer does and finder?
@sbatten @bpasero let me knw how you feel

[Code pointer](https://github.com/Microsoft/vscode/blob/e0a43e6f6d9cac62b8f791bee8fb109123be1c37/src/vs/workbench/contrib/files/browser/fileActions.ts#L285)
The confirm message that is constructed in the `getConfirmMessage` should be set to the `details` of the dialog.

**Comment by bpasero** [comment]
I think it would be good to compare this with native dialogs on all platforms before doing a change.

**Comment by sbatten** [comment]
I am in favor, but it will be good to check native experiences. I've tested this with windows when working on dialogs and prefer it in both cases.

**Comment by misolori** [comment]
Here are all of the current native dialogs:

## Mac
![image](https://user-images.githubusercontent.com/35271042/69269722-7e420300-0b86-11ea-8bb4-27060182a260.png)

## Windows
![image](https://user-images.githubusercontent.com/35271042/69269951-e98bd500-0b86-11ea-8553-b2ddffb47924.png)

## Linux
![image](https://user-images.githubusercontent.com/35271042/69270189-5901c480-0b87-11ea-8870-a3fdeeea5328.png)

**Comment by bpasero** [comment]
We could try to change this, I am undecided. I would find it weird that the main message mentions "the following 7 files" and then the names appear as detail text. Maybe we should then also update the message text?

**Comment by sbatten** [comment]
IMO, they just look bad today. I don't think them being in the detail text makes it less clear that they are the following X files to which the message refers. If "following" is the confusing part, I'm fine with "Are you sure you want to delete 7 files?" To me, this is a header + list view and the list should not use the same font size/weight as the header.

**Comment by isidorn** [comment]
Ok, let's change it and try it out.
For now assigning to November (though might slip to December)

**Comment by isidorn** [comment]
I have changed this for insiders. Let's try it out and see if we like it.
Atm I do not think it is a bad change. Let' see how it goes.

![Screenshot 2019-12-30 at 17 33 30](https://user-images.githubusercontent.com/1926584/71590930-a9772500-2b2a-11ea-8628-33464589412b.png)

**Comment by isidorn** [comment]
@misolori can you verify this now looks as expected and add a verified label? Thanks!

**Comment by misolori** [comment]
Much better, thanks!

![image](https://user-images.githubusercontent.com/35271042/72834365-83323a00-3c3d-11ea-880f-c808314a3b13.png)
