### ISSUE TITLE
Extension git resource not available

### ISSUE THREAD

**Issue by Logerfo** [microsoft/vscode#85067]
## Steps to reproduce
1. Go to the extensions tab.
2. Look for [`logerfo.gitlab-notifications`](https://marketplace.visualstudio.com/items?itemName=logerfo.gitlab-notifications) (it also happens with others, check code below).
3. Click at "Repository".

## Expected behavior
Browser should go to https://github.com/Logerfo/gitlab-notifications.

## Actual behavior
> Unable to open 'gitlab-notifications.git': resource is not available.

## Code
[`package.json`](https://github.com/Logerfo/gitlab-notifications/blob/71a51aa86a3f4e32dd05639f6179907bc3a1585c/package.json#L22-L25):
```jsonc
{
  //...
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Logerfo/gitlab-notifications.git"
  },
  //...
}
```

## Versions
- VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z).
- OS version: Windows_NT x64 10.0.18363.

**Comment by sandy081** [comment]
Its not a valid url, Please file an issue against the extension to fix it.
