### ISSUE TITLE
Format Document Not working

### ISSUE THREAD

**Issue by AndyWDev** [microsoft/vscode#85064]
Issue Type: <b>Bug</b>

when opening a new document (XML, JSON etc) and pasting valid XML/Json etc.  the format document menu often does not appear.

After inserting a blank line or changing the text, the menu will appear. However selecting it often does nothing.  I have found sometimes it needs to be selected 4 or 5 times before it will work.

Once it works, it seems to be fine and correctly formats the document.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

**Comment by egamma** [comment]
/needsMoreInfo

can you please provide steps with an example when this happens so that we can reproduce the problem.

**Comment by AndyWDev** [comment]
Here are my repro steps.

Open vs code
File.New File
Paste XML document (that has root node)
Right mouse click to get to Format Document menu

For me, both format document & format document with  menus are missing.
Edit document (I either just insert a blank line at the top, or wrap the XML with another element.

Right mouse click again (several times) and the Format document menu eventually appears.

Note: I don't save the documents (I just used the default persistence). 

Regards

**Comment by libre-x** [comment]
Have you tried setting the file format as XML in the bottom right corner?
It's pretty important if you don't save the file.

**Comment by egamma** [comment]
@AndyWDev In the description you mention that this happens for both XML and JSON

> when opening a new document (XML, JSON etc)

Do you also have steps for to reproduce this in JSON?

**Comment by egamma** [comment]
I can reproduce it when I invoke the context menu immediately when VS Code has started. Is this the issue you are referring to? In other words, once the Format menu entries show up, they will always show up?

**Comment by AndyWDev** [comment]
yes, that appears to be the case.

When I opened a new window and pasted some xml (and chose xml doc type) the menu seemed to appear quite quickly.  When I opened vs code for the first time, I had to right mouse click to the context menu about 8 times (about 10-15 seconds) before the menu appeared.

**Comment by jrieken** [comment]
/needsMoreInfo

It seems like the extensions are slow to register. Can you attach the reading of F1 > Startup Performance
