### ISSUE TITLE
PHP syntax highlighting: Incorrect color of `$` in new $foo();

### ISSUE THREAD

**Issue by AlexMax** [microsoft/vscode#85063]
- VSCode Version: 1.40.1
- OS Version: macOS 10.14.6 (18G1012)

Steps to Reproduce:

1. Open a new PHP buffer.
2. Type the following into the buffer:

```
<?php

$xyzzy = NULL;

new $foo();
```

Does this issue occur when all extensions are disabled?: Yes

Expected Behavior:
The `$` in `$foo` has the same color as `foo`, see `$xyzzy`.

Actual Behavior:
The `$` in `$foo` does not appear to be highlighted, unlike `$xyzzy`.

This does not appear to be an issue with Atom's syntax definition - at least not in the latest stable version - because I tested the same construct there and the `$` had the correct color in both spots.

**Comment by alexr00** [comment]
It looks like this is intentional. `$` on that line is colorized as `meta.embedded` and `foo` is colorized as `variable`. @aeschli do you think we should change the theme here?

**Comment by AlexMax** [comment]
`meta.embedded` doesn't make a whole lot of sense as a selector for that sigil.  Embedded?  Embedded what?  A similar PHP construct, `new $foo` without the parenthesis, is colored correctly, as is `$$xyzzy = NULL`.  It's only `new $foo()` that has the broken coloring, which makes me think the selector choice is unintentional.

If the problem is with Atom's syntax file, and the version of Atom I was using simply wasn't on the latest version of it, I can open an issue there.

**Comment by alexr00** [comment]
@AlexMax if you are still seeing the issue, it would be worth opening an issue over in https://github.com/atom/language-php
