### ISSUE TITLE
Powershell:  Autosense is broken when referencing a function which has an Enumerated Type as a parameter

### ISSUE THREAD

**Issue by cdelcambre** [microsoft/vscode#85066]
- VSCode Version:  1.40.1
- OS Version:  Windows 10, 1903
- Powershell Extension:  2019.11.0

Steps to Reproduce:

1.  Create an Enum
2.  Create a function which references that Enum as a parameter.
3.  Call that function, there will be no autosense when populating the parameters and values for said function.

Does this issue occur when all extensions are disabled?: Yes

Simple Example
Enum AzureSqlEdition
{
	Standard
	Premium
	Basic
}

function functAutoSenseBroke
{
	param
    (
        [Parameter(Mandatory=$True)][AzureSqlEdition]$DbType,
        [Parameter(Mandatory=$True)][string]$OtherParameter
    )
    Write-Host $DbType
    Write-Host $OtherParameter
}

function functAutoSenseWorks
{
	param ( [Parameter(Mandatory=$True)][string]$DbType )
    Write-Host $DbType
}
#works but no autosense
functAutoSenseBroke -DbType ([AzureSqlEdition]::Standard) -OtherParameter "other"

#Simple Function, no Enum, autosense works, for comparison purposes
functAutoSenseWorks -DbType "test"

**Comment by egamma** [comment]
Please file the issue against the Powershell extension.
