### ISSUE TITLE
Web: Sash indicator on touch screen

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#85062]
The sash is thin and invisible in popular themes. It made it really hard to drag on a touch screen.

Swift Playground on iPad puts a rounded rectangle on the sash, which is convinent to use.

![image](https://user-images.githubusercontent.com/876920/69083549-288b2080-09f7-11ea-9adc-bddc1705453e.jpg)

When I drag the sash in Swift Playground, it also changes the color of the sash, to indicate it's in an active state. We should probably do the same thing at least for touch. cc @misolori

**Comment by joaomoreno** [comment]
#68962
