### ISSUE TITLE
typescript formatting preincrement without curly braces

### ISSUE THREAD

**Issue by devel0** [microsoft/vscode#85068]
- VSCode Version: 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37) x64
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. type follow

```ts
let a = 0;
if (a>0) ++a;
```

2. format ( ctrl+shift+I ) and results

```ts
let a = 0;
if (a > 0)++a;
```

where `++a` miss beginning space.

Correct results should:

```ts
let a = 0;
if (a > 0) ++a;
```

Note: using `postfix increment` problem doesn't exists.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/35179 to track usptream
