### ISSUE TITLE
Add advanced diff similar to SlickEdit

### ISSUE THREAD

**Issue by GlenNicholls** [microsoft/vscode#85060]
Issue Type: <b>Feature Request</b>

Visual Studio Code diff tool is not nice to use as it is annoying to have to select open files that are already open to diff. In addition to this, it does not support comparing directories. In my case when I am trying to quickly find differences between two similar checkouts of software, I would like the diff tool to denote which files are different such that I can quickly analyze differences between those files. E.g. if I have two checkouts of the same software repository on two projects, SVN is annoying to deal with so a folder diff is easier to use to differentiate which files are different. While I could look at these differences in SVN, this is not always possible if someone has something floating around that has been changed but not committed.

The below screencap from slick edit is what the diff tool should look like. It should offer the user the ability to diff a file or directory directly from a seperate window instead of forcing the user to have the files open. Sometimes, I would like to just compare two files without opening them and only open them if I find a reason to edit.

![image](https://user-images.githubusercontent.com/17171913/69082632-b0742900-09fd-11ea-9b41-0cea59909983.png)

![image](https://user-images.githubusercontent.com/17171913/69082726-efa27a00-09fd-11ea-89a0-b0f62890139c.png)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

**Comment by egamma** [comment]
>it is annoying to have to select open files that are already open to diff

This is supported and you can also compare two files from the command line, pls see https://www.meziantou.net/comparing-files-using-visual-studio-code.htm

> it does not support comparing directories.

Pls try https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders

**Comment by GlenNicholls** [comment]
@egamma 
>This is supported and you can also compare two files from the command line, pls see https://www.meziantou.net/comparing-files-using-visual-studio-code.htm

I know it suppports this. However, the entry to diff files is sometimes better with a GUI window instead of from the command line. I prefer the command line, but not everyone is like this and some people prefer using a GUI window to click to the desired files to diff.

**Comment by gjsjohnmurray** [comment]
@GlenNicholls - for me the context menu on any file in the Explorer tree (even one that I haven't opened) offers 'Select for Compare' and 'Compare with Selected'. So I'm not clear what you mean when you say you have to open the files first.

**Comment by GlenNicholls** [comment]
@gjsjohnmurray I understand that, but it only works easily if one of the files is already open, is in the same directory, or within a few levels of the hierarchy. This gets really tedious when you have to change drives to diff files, especially if you want to diff numerous files in those directories since folder diffing is not available. The point I am trying to make is that in some situations, the current method for diffing files simply is not enough. This is the same problem as the search interface, but that is a discussion for a different issue.

**Comment by GlenNicholls** [comment]
@egamma 
>Pls try https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders

I found this before, but a feature like this is something that really should be supported out of the box by VSC. This is something that is used all the time for software development and should be directly supported by the IDE. All the big IDEs that I've used directly support more advanced search window and diffing.

**Comment by fbaligand** [comment]
I agree with @GlenNicholls: comparing two folders is really an essential feature.
I use it everyday with other IDEs.

**Comment by fbaligand** [comment]
By the way, I find that "L13 Diff" extension is way better than "compare-folders":
https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff

**Comment by fbaligand** [comment]
Despite 2 extensions exist with such a feature, I would love "folder comparison" feature more integrated in IDE, that is to say, using the same way than "file comparison", with "Select for Compare" and "Compare with Selected" features.
