### ISSUE TITLE
Editor Suggestions on Enter change

### ISSUE THREAD

**Issue by rwilliams** [microsoft/vscode#85079]
It would be great if the editor suggestions feature always had the first suggestion as what you've typed so far so you can hit enter and not worry about it picking a suggestion you don't want if it doesn't match a suggestion.

The feature/setting in question
![image](https://user-images.githubusercontent.com/29144/69099427-904d6580-0a0f-11ea-94eb-a4c69e10a77d.png)

The first suggestion on this list would be `customer` so i can just hit enter like normal. Right now it'll change it to customer_type if I hit enter with "Accept Suggestion on Enter" on. 
![image](https://user-images.githubusercontent.com/29144/69099471-a9561680-0a0f-11ea-9026-42e5b0e8a7a6.png)

**Comment by gjsjohnmurray** [comment]
For another approach see #85768 and upvote if you like it.

**Comment by rwilliams** [comment]
Thanks for sharing that.
