### ISSUE TITLE
This code (below) doesn't work

### ISSUE THREAD

**Issue by joagostini** [microsoft/vscode#85073]
This code doesn't work on Visual Studio Code, but works on Code::Blocks and Eclipse using MinGW. I pretend work with VSC, but in this way isn't possible. Why no work? Tanks a lot.

 ```
#include <iostream>
  #include <string>
  using namespace std;
  int main(void)
 {
    float Ve=0, Vs=0, R1=0, R2=0;
    cout<<"Calculate the voltage division between two resistors. \nCalculation without load.\n\n"<<endl;
    cout<<"Enter known values (0 if no value is known):"<<endl;
    cout<<"Input Voltage Vs = ";
    cin >> Ve;
    cin.ignore();
    cout<<"Resistor R1 = ";
    cin >> R1;
    cin.ignore();
    cout<<"Resistor R2 = ";
    cin >> R2;
    cin.ignore();
    cout<<"Output Voltage Vs = ";
    cin >> Vs;
    cin.ignore();
    cout<<"Ve= "<<Ve<<" R1= "<<R1<<" R2= "<<R2<<" Vs= "<<Vs<<endl;
    if(Ve!=0 && R1!=0 && R2!=0 && Vs==0){
        Vs=(R2*Ve)/(R2+R1);
        cout <<"The result is: "<<Vs<<endl;}
    else cout << "\nNo value";
   return 0;
 }
```

**Comment by egamma** [comment]
>This code doesn't work on Visual Studio Code

What exactly does not work? Is there an error message?

**Comment by joagostini** [comment]
Olá
Obrigado por responder.
Não há mensagem de erro.
O programa não roda como indicado. O cursor move-se de forma espasmódica no
terminal. As frases não são completadas e até aparecem truncadas. Não
mostra todas as mensagens que deveria e as linhas exibidas se sobrepõem.
Não realiza cálculos. Um caos.

Em seg., 18 de nov. de 2019 às 18:26, Erich Gamma <notifications@github.com>
escreveu:

**Comment by joagostini** [comment]
Não entendi. A qual extensão você se refere? O que significa registrá-la no
repositório ou no marketplace? Eu só usei extensões do Visual Studio Code,
não usei de erceiros e nem fiz uma extensão. Explique melhor por favor.
Obrigado.

Em seg., 18 de nov. de 2019 às 18:24, vscodebot[bot] <
notifications@github.com> escreveu:

**Comment by libre-x** [comment]
I just tried to run your code on Ubuntu (using WSL2) with gdb and g++ installed. I used the "g++ build and debug active file" configuration and task, which I think come from the "C/C++" extension I had installed.

Everything runs and compiles with no issues.
![image](https://user-images.githubusercontent.com/57818633/69103460-23b58380-0a6e-11ea-8ab6-cd14e8c78fa7.png)

**Comment by egamma** [comment]
@libre-x thanks for jumping in.

**Comment by joagostini** [comment]
[image: Anotação 2019-11-19-2.png]

Em seg., 18 de nov. de 2019 às 20:47, libre-x <notifications@github.com>
escreveu:

**Comment by libre-x** [comment]
@joagostini I do not see the image. Please open the issue page in the browser and upload the image while commenting there, as sending images over email does not work for issues.
