### ISSUE TITLE
Expanding Terminal adds "whitespace"

### ISSUE THREAD

**Issue by mrmucox** [microsoft/vscode#85072]
Issue Type: <b>Bug</b>

open the terminal.
click the arrow to expand the terminal to fill the screen
Instead of keeping the text at the bottom, and scrolling the text up, the window will add a bunch of whitespace below the text, even when there is text to scroll

VS Code version: Code - Insiders 1.41.0-insider (eccf417b72fc0a632ec2cbd7855a681cdb8c81fa, 2019-11-14T09:50:04.822Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.26GB (20.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
orclapex-autocomplete|apn|0.0.3
jsonviewer|cci|1.2.2
bracket-pair-colorizer-2|Coe|0.0.28
vbscript|Dar|1.0.4
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.9
gc-excelviewer|Gra|2.1.32
classic-asp-html|jtj|0.1.1
rainbow-csv|mec|1.3.1
python|ms-|2019.12.49019-dev
debugger-for-chrome|msj|4.12.1
numbermonger|sof|0.5.0
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.0
plsql-language|xyz|1.8.2

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
