### ISSUE TITLE
Peek Reference doesn't focus on selected reference

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode#85075]
- VSCode Version: 1.40.1
- OS Version: Windows 10 Pro x64 Version 1903 Build 18362.418

In my C workspace I'm working in a 2 column layout. If I select a reference in Peek References and double click on it or press Enter while it's active, if the selected reference is in a file that's open in the other column, the caret in the other column moves on it but the editor doesn't focus on that column but remains on the symbol that I invoked Peek References on.

It works correctly on single column layout OR if the file is not open OR the file is open in the same column.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This is fixed in insider, go get it: https://code.visualstudio.com/insiders/
