### ISSUE TITLE
Sluggish mouse selection & cursor movement when in full screen / zen mode

### ISSUE THREAD

**Issue by qgates** [microsoft/vscode#85084]
Vscode feels generally sluggish when cursoring and dragging selections quickly in full screen or zen modes.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. With vscode windowed, load a markdown file of at least 3 screenfuls
2. Quickly drag a selection up and down, page up and down, everything's fine
3. Go into full screen mode (F11) or Zen mode
4. Quickly drag a selection up and down, selection is slow to catch up to mouse, page up and down, and vscode lags. Across all screen operations vscode generally feels more sluggish.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe #84343 is relevant. Can you try the latest Insiders release?

**Comment by qgates** [comment]
Same issue with insiders (1.41.0) and #84343 appears to be a different issue. #84362 is, at least from user perspective, a completely different issue.

Sluggishness when quickly dragging/undragging a selection, cursoring or paging only happens in full screen (F11) and zen modes, and remains permanent in those modes.

When vscode is maximised (occupying almost, but not quite, the same screen real-estate) everything is as expected ie. responsive and no lag. Same for when vscode is windowed.

**Comment by qgates** [comment]
Some additional info. The system is running an Nvidia GTS-250 graphics, dual screen. Main screen is 24" running 1920x1200 resolution, secondary is 19" square running 1280x1024.

I tried fullscreen/zen on the secondary screen and the problem is much less pronounced (but still slightly noticeable).

After disconnecting the secondary screen and rebooting (ie. running a single 1920x1200 screen setup), there is no improvement and lag remains.

**Comment by qgates** [comment]
Strangely this issue seems to have disappeared since reconfiguring the dual-screen setup. I'll close for now and reopen if the issue returns.

**Comment by qgates** [comment]
Ok, so the problem's back. It seems to have something to do with the dual screen setup which, in Windows 10, is configured to extend the display. If I switch from dual screen ('extend') to single ('only show on monitor 1') and then back again the problem goes away, but then returns after a period of time, possibly after putting the machine to sleep.

The graphics card is an Nvidia GTS 250. No other applications or software appear to have any performance issues. Let me know if further info is needed.

TIA

**Comment by deepak1556** [comment]
@qgates sorry for the delay, I tried to repro this on my dual screen setup following the steps mentioned but couldn't see any slowdown in scroll with 1.40.1. 

Can you attach a video demo, maybe I am missing something.

Also can you attach the JS profile for both slowdown scenario in dual screen and single screen setup following the instructions from https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process. Thanks!
