### ISSUE TITLE
Folding: Add setting to enable code to be folded up onto the line preceeding the open bracket

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#85083]
Feature Request: Add setting to enable code to be completely folded onto a single line (first line, or preceeding line if bracket is on it's own line), like VS does.

VS Code uses 3x as many lines to display folded code, compared to VS.  Fewer lines would allow a lot more to be displayed on screen at a time.

In C++, VS Code folds code like so:

![image](https://user-images.githubusercontent.com/49173979/69107679-08735580-0a27-11ea-8263-d8fb815a3e42.png)

VS does the following:

![image](https://user-images.githubusercontent.com/49173979/69107655-f4c7ef00-0a26-11ea-94c0-32178fc39f04.png)

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode/issues/3352#issuecomment-513696419

Dup of #3352.
