### ISSUE TITLE
Non-fluent English in error message

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/vscode#85080]
![image](https://user-images.githubusercontent.com/829827/69101430-77937e80-0a14-11ea-9ae5-3aaed437e4d5.png)

Issue Type: <b>Bug</b>

I am not precisely sure how to repro this. It occurs sometimes when I move files around. The error message is:

> File to paste was deleted or moved meanwhile. Unable to move/copy. File already exists at destination.

This could be corrected to read something like:

> The file to paste has been deleted or moved since you copied it. Additionally, a file already exists at the destination.

I'm sorry that I don't have repro steps, but hopefully it's easy to find this string in the app code / message properties.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 9|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Users/nheiner/code/prompts/dist/elements/multiselect.js:203:39 -g|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
auto-rename-tag|for|0.1.1
change-case|wma|1.0.0

</details>

**Comment by jzyrobert** [comment]
This seems to be 2 error messages, one saying 

> The file to paste has been deleted or moved since you copied it

Combined with: 

> Unable to move/copy. File already exists at destination.

I think the second error message should be one sentence, this also fits in with the other move/copy error messages.

**Comment by mjbvz** [comment]
Here's the error string if you would like to submit a pr: https://github.com/microsoft/vscode/blob/00688bf051948d9ce5000328493fd828dece4f48/src/vs/workbench/contrib/files/browser/fileActions.ts#L1049

**Comment by isidorn** [comment]
@NickHeiner I have pushed some updates to the wording as you suggested. Thanks

**Comment by NickHeiner** [comment]
Awesome! Thanks for the quick action, everyone.
