### ISSUE TITLE
Tasks: [OSX] Task no longer executes in correct user environment

### ISSUE THREAD

**Issue by davidmontemayor** [Microsoft/vscode#8508]
- VSCode Version: Insiders June 28th 2016.
- OS Version: Capitan 10.11.5

Steps to Reproduce:

1. Define a task that executes a shell script. In this shell script invoke an `npm` command
2. Result: `./build.sh: line 2: npm: command not found`

This works fine in VSCode v. 1.2.1

**Comment by dbaeumer** [comment]
@wallverb this looks very much like a dup of #8434. #7342 talks about debugger only.

**Comment by davidmontemayor** [comment]
Whoops! Totally looked for dupes but with that title, I'm not surprised I couldn't find it! The workaround of starting Code from the shell worked great.
