### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by kalpaj12** [microsoft/vscode#85089]
#84940 and #84803 share the same issue as I face, but for me it happens when I open a python file. (Lines of Code ~ 40)

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-23-generic

Steps to Reproduce:

Open a Python 2.x file.

`Extension host terminated unexpectedly` appears almost instantaneously.

Does this issue occur when all extensions are disabled?: Yes

Notes:
1. Haven't faced this issue, while working on a c/cpp/js file type.
2. Also for some reason, I can't use the indenter that comes with the Python (
ms-python.python) extension.

**Comment by gjsjohnmurray** [comment]
Does the recent #84803 fix help you? Can you test today's Insiders?

**Comment by kalpaj12** [comment]
Hi @gjsjohnmurray,

Sure, will test it on today's Insiders build. 
And, yes this commit (https://github.com/microsoft/vscode/commit/fbbb6b93e65f554b1a867df031441e19000af658) should solve the problem. I sure am using a different locale.

Thanks!
