### ISSUE TITLE
Extensions: Subpixel AA isn't working in the input box

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#85099]
There are two problems:

- The editor div has transparent background, which causes Chrome to disable subpixel AA cc @alexandrudima 
- The placeholder also has it disabled, cause unknown

This affects extensions viewlet and settings.

![image](https://user-images.githubusercontent.com/22350/69132434-5b471e80-0ab4-11ea-9c0d-aa74ce03c6be.png)

**Comment by alexandrudima** [comment]
Here is the offending CSS rule:

https://github.com/microsoft/vscode/blob/16466cb05d7f667cd47682f3cc7094cac86c9dd0/src/vs/workbench/contrib/codeEditor/browser/suggestEnabledInput/suggestEnabledInput.css#L14

The fix would be for users of this widget to set the background manually to a non-transparent background.

**Comment by joaomoreno** [comment]
Seems good for extensions, cc @sandy081 

![image](https://user-images.githubusercontent.com/22350/69222490-e0483b80-0b79-11ea-93c1-302b75351a19.png)

Still broken in search, but that might be another root cause, cc @roblourens:

![image](https://user-images.githubusercontent.com/22350/69222525-f229de80-0b79-11ea-9e41-c1e5f3e621b9.png)

**Comment by JacksonKearl** [comment]
The extensions search and the settings search use the same `suggestEnabledInput`, the text search uses it's own input

**Comment by alexr00** [comment]
Verified for settings, search, and extensions. Test search still has has broken subpixel AA.
