### ISSUE TITLE
Code lens corruption

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85093]
Issue Type: <b>Bug</b>

While heavily editing a file, I keep getting code lenses in the wrong places and overlapping code. Even closing and re-opening the file doesn't seem to help.

![image](https://user-images.githubusercontent.com/641685/69123448-60ce4580-0a6f-11ea-9cd9-05d2060ee73f.png)

/cc @jrieken 

VS Code version: Code - Insiders 1.41.0-insider (3b17b7943842e84912a5507111a6cd790db18a46, 2019-11-18T16:15:22.989Z)
OS version: Windows_NT x64 10.0.19025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Hm, likely due to the perf optimisations and the fact that code lens widgets are created lazy...
