### ISSUE TITLE
TS: Suggest class name from file

### ISSUE THREAD

**Issue by birgersp** [microsoft/vscode#85092]
When I am about create a new class in a file, I'd like VSCode to suggest the class name for me.

Example: The user wants to create a class named "Person". The user creates a new file: "**Person.ts**".
The user opens that file and starts writing: "**export class Pe**".
At this point, the user should be able to Ctrl+Space, and VSCode should provide the option to autocomplete "Person". It is the name of the file, so it is likely that the user wants this name for the class.

(FWIW IntelliJ and other IDEs from Jetbrains has this feature, and personally I find it very useful)

**Comment by gjsjohnmurray** [comment]
@birgersp did you consider using an extension that lets you define a template for new .ts files? Looks like the one mentioned in #44081 might do the job, though I've not tried it myself. Templating was also suggested in #76819 which was closed with the recommendation that an extension should do this job.

**Comment by birgersp** [comment]
@gjsjohnmurray thanks for the tip. But this suggestion is to improve VSCode, not just to get a workaround for me personally.

**Comment by birgersp** [comment]
@egamma please note that imo this could be relevant for other languages as well, not just TS.

**Comment by mjbvz** [comment]
JS/TS IntelliSense is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
