### ISSUE TITLE
markdown extension does not open relative links in remote env

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#85105]
I can reproduce it in Gitpod and VS Online. Relative links are not handled but passed through because scheme is `http`: https://github.com/microsoft/vscode/blob/db597dff739d46d487499c93fb765f6d98447ef4/extensions/markdown-language-features/preview-src/index.ts#L147

**Comment by mjbvz** [comment]
Please share steps to reproduce so that someone can try investigating this and potentially submit a PR

**Comment by akosyakov** [comment]
Unfortunately my free VS Online subscription run out 😬 But I could reproduce it by previewing any markdown file with a relative link to another file.

**Comment by mjbvz** [comment]
Can you please share repo steps for that? Also, what version of VS Code are you using?

**Comment by mjbvz** [comment]
Based on the description, I believe this is the same issue as #101203
