### ISSUE TITLE
Update routine checks for running VSCode processes on the machine in (user setup)

### ISSUE THREAD

**Issue by Glober777** [microsoft/vscode#85103]
I've noticed an issue when I tried updating my copy of VSCode (user setup) on a terminal server. I got a prompt saying that there are other instances of VSCode running and should be closed to continue. While I didn't have any other copies of VSCode running, it turned out that one other user had his copy (user setup) started on that same server, which prevented me from updating. 

This behavior seems misleading since the user setup edition is installed into the user profile and not in a shared location, hence should not depend on other instances of VSCode that were invoked from a different path.

- VSCode Version: 1.40.0 (user setup)
- OS Version: Windows Server 2016

Steps to Reproduce:

1. Establish multiple user sessions on a terminal server and start earlier version (i.e. 1.40.0) of VSCode (user setup) under each of the user
2. Initiate an update from within

**Comment by Glober777** [comment]
Forgot to mention, that the issue can be reproduced only by calling update from within the VSCode. Downloading the latest version of the user setup installer from the website an installing it on top doesn't trigger this issue.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/55775
