### ISSUE TITLE
editor.fontfamily not working for custom fonts

### ISSUE THREAD

**Issue by pikaphu** [microsoft/vscode#85101]
Issue Type: <b>Bug</b>

Today my editor font not work as expected. I had settings like this

"editor.fontFamily": "Menlo, Hack, Consolas, 'Cascadia Code', 'Courier New', monospace",

The fonts only work are Consolas and after its (except first two fonts: Menlo and Hack, they are skipped). No idea what going on and how to fix. 

*Note: I never encounter this issue until today. I already try disable all installed extension but still not fix.
*Note2: I have only User settings (no Workspace settings).

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

Extensions: none

**Comment by duncanawoods** [comment]
Same issue on Ubuntu 18.04 installed directly from .deb not snap.

User installed fonts like 'Source Code Pro' are not being picked up I do find that the system font 'Ubuntu Mono' is. This makes it sound like this issue that used to happen with snap installs not being able to access user fonts:

https://stackoverflow.com/questions/53453998/vscode-on-ubuntu-not-reading-installed-fonts

**Comment by IllusionMH** [comment]
/needsMoreInfo

@pikaphu do you have Hack and Menlo fonts installed in system? Are they named accordingly or there are files like "Menlo Regular" etc. in fonts folder?

**Comment by pikaphu** [comment]
> /needsMoreInfo
> 
> @pikaphu do you have Hack and Menlo fonts installed in system? Are they named accordingly or there are files like "Menlo Regular" etc. in fonts folder?

Hi, IllusionMH  Sorry for the missing information. I kind a newbie here. I will improve my post.

1. The font I have problem are "Menlo" and "Hack" and here is my installed font (please see in attached picture below) 
![image](https://user-images.githubusercontent.com/1812299/69142442-607a8c80-0af9-11ea-9b6b-160389b7659d.png)
![image](https://user-images.githubusercontent.com/1812299/69142540-9caded00-0af9-11ea-92d4-da3ddb70d2f2.png)

The font "Menlo" its filename is "Menlo Regular" but it Font name is "Menlo"
And The font "Hack" its filename is "Hack Regular" but it Font name is "Hack"

2. I have to say again that I have used this setting for more than 1 month and never had any problems until today. I'm not sure if this is a problem with vscode or OS, but I think this is not a file name issue. Because if yes, I must not be able to use it previously

**Comment by alexandrudima** [comment]
@pikaphu If you never had issues until today, then what has changed? Can you please try one font at a time, like `"editor.fontFamily": "Hack"` by itself. Can you also check that you don't define `"editor.fontFamily"` somewhere else, like in your workspace settings or in the folder settings? You can check by opening a new window (`Ctrl+Shift+N`) and opening an untitled file.

**Comment by pikaphu** [comment]
> @pikaphu If you never had issues until today, then what has changed? Can you please try one font at a time, like `"editor.fontFamily": "Hack"` by itself. Can you also check that you don't define `"editor.fontFamily"` somewhere else, like in your workspace settings or in the folder settings? You can check by opening a new window (`Ctrl+Shift+N`) and opening an untitled file.

Hi alexandrudima,
I try create new project like you said with one text file (please see pictures below). 
And you can see that I have only settings.json of User and workspace is not set anything.

From the picture [img1] below The text shown is using font 'Cascadia Code'.
And the picture [img2] is using font "monospace". 
And the picture [img3] I only using font "Hack" but the you can see that the text shown is definitely not font "Hack".  (https://www.dafont.com/hack.font)

[img1]
![image](https://user-images.githubusercontent.com/1812299/69172630-c9312b80-0b30-11ea-9dc9-e7d3d2df7401.png)

[img2]
![image](https://user-images.githubusercontent.com/1812299/69173018-82900100-0b31-11ea-86b0-ebdd7b37d7b0.png)

[img3]
![image](https://user-images.githubusercontent.com/1812299/69173253-02b66680-0b32-11ea-9e50-b2003f9a10f8.png)

**Comment by alexandrudima** [comment]
@pikaphu Thank you for the extra information. Let's try to troubleshoot one font at a time. Let's pick "Hack", because doing them one by one is easier.

From your [img3] I can clearly see that the font is not working.
![image](https://user-images.githubusercontent.com/1812299/69174315-1ebb0780-0b34-11ea-946c-b50040651860.png)

Is the font working in other software on the machine? Can you please open the following link in a web browser like Chrome / Firefox / Edge and post the screenshots here? -- https://jsfiddle.net/x7o4vwf2/

Here is how it looks on my machine:
![image](https://user-images.githubusercontent.com/5047891/69220917-56e33a00-0b76-11ea-98cb-43da68a92b9d.png)


I am not an expert in OS font issues, but sometimes I have heard that uninstalling the font, then restarting the machine, and then installing it fresh might help. I have installed Hack from https://github.com/source-foundry/Hack/releases , the ttf variant and then installed all 4 variants in the zip and the font works for me.

**Comment by pikaphu** [comment]
> @pikaphu Thank you for the extra information. Let's try to troubleshoot one font at a time. Let's pick "Hack", because doing them one by one is easier.
> 
> From your [img3] I can clearly see that the font is not working.
> ![image](https://user-images.githubusercontent.com/1812299/69174315-1ebb0780-0b34-11ea-946c-b50040651860.png)
> 
> Is the font working in other software on the machine? Can you please open the following link in a web browser like Chrome / Firefox / Edge and post the screenshots here? -- https://jsfiddle.net/x7o4vwf2/
> 
> Here is how it looks on my machine:
> ![image](https://user-images.githubusercontent.com/5047891/69220917-56e33a00-0b76-11ea-98cb-43da68a92b9d.png)
> 
> I am not an expert in OS font issues, but sometimes I have heard that uninstalling the font, then restarting the machine, and then installing it fresh might help. I have installed Hack from https://github.com/source-foundry/Hack/releases , the ttf variant and then installed all 4 variants in the zip and the font works for me.

@alexandrudima  I've try your method and the result is interesting (please see the picture and caption below) 

 **[img5]** 
I open this  https://jsfiddle.net/x7o4vwf2/ on Chrome, Edge and Firefox. Their result are same that the font not working. I think this is may be my machine problems.
![image](https://user-images.githubusercontent.com/1812299/69229224-a433cb80-0bb7-11ea-95f8-214f1831a9cb.png)


**[img6]** 
Then I try delete my fonts from machine and then install again like this picture 
![image](https://user-images.githubusercontent.com/1812299/69229495-15737e80-0bb8-11ea-9b10-8c71e11b7024.png)

**[img7]** 
Wow it works now! 😮   also VSCode too. 😄  I'm  happy now.
![image](https://user-images.githubusercontent.com/1812299/69230578-21604000-0bba-11ea-9eac-0c6bbd362c95.png)
https://jsfiddle.net/hx6touvq/2/


I still have problem with Menlo font that not work. But I think this issue is caused by my machine, So I will close this issue and try with another machine to find different.

Thank you everyone
And special thanks to @alexandrudima  testing solution  👍
