### ISSUE TITLE
cpu high on view files

### ISSUE THREAD

**Issue by FelixFearnley** [microsoft/vscode#85109]
open visual studio code 

open 3 or for files from porject 

cpu goes up , then settles 

now just clicking on the tabs to move between code files increases cpu to around 30 percent ( this is on an i7 4 core processor ) . 

all extenseions bar theme area switched off 

dont click on anything, now cpu settles down again 

start navigating between files again ( click on tabs ) cpu goes up again to around 30%

gpu acceleration is turned off as per release note instructions in this release 

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-70-generic

**Comment by FelixFearnley** [comment]
linux mint 18.2 = ubuntu 16.04

**Comment by egamma** [comment]
Please help us to narrow down such performance issues by following this guide.
https://github.com/microsoft/vscode/wiki/Performance-Issues
