### ISSUE TITLE
Extension update button not visible

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#8510]
- VSCode Version: 1.3.0-insider 798b41ab1cf3636a27042020a54ddfb4cfb8d23c
- OS Version: OSX 10.11.5

If second column is not wide enough, the button to update is not visible:
![image](https://cloud.githubusercontent.com/assets/1723815/16455836/c1f43d1c-3de3-11e6-8841-e971b8ace10d.png)

One need to make it bigger for button to appear:
![image](https://cloud.githubusercontent.com/assets/1723815/16455858/d49e7414-3de3-11e6-8335-5d3ba4cb23c0.png)

**Comment by Tyriar** [comment]
As mentioned in the my duplicate:

> Long term fix for this is likely to swap the text out for an icon at this point instead of just disappearing.

**Comment by philipgiuliani** [comment]
I think we could hide the icon of the extension in this size. That gives ~30% of the space.

**Comment by joaomoreno** [comment]
> I think we could hide the icon of the extension in this size. That gives ~30% of the space.

Awesome suggestion.
