### ISSUE TITLE
Folder color does not update to reflect state of files it contains in Explorer

### ISSUE THREAD

**Issue by kyonkopa** [microsoft/vscode#85112]
Issue Type: <b>Bug</b>
Steps to reproduce:  

1. Create a new file preferably a .php file
2. Enter some syntactically wrong code so that the file is highlighed red in Explorer in SideBar
3. Correct the syntax so that the red color changes back to green
4. The folder within which you created the file doesn't change its color and still stays red.

I've tested with .js and .scss files and they seem to work correctly i.e. containing folders are updated to reflect file colors.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (2.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
atlascode|atl|2.1.5
markdown-preview-github-styles|bie|0.1.6
simple-react-snippets|bur|1.2.2
laravel-goto-view|cod|1.3.2
smoothscroll|cya|1.0.4
EditorConfig|Edi|0.14.2
prettier-vscode|esb|3.6.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
beautify|Hoo|1.5.0
fontawesome-autocomplete|Jan|0.1.8
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.1245
php-docblocker|nei|2.0.1
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
vscode-yaml|red|0.5.3
laravel-artisan|rya|0.0.26
addDocComments|ste|0.0.8
ayu|tea|0.18.0
pdf|tom|0.5.1
remove-empty-lines|use|0.0.6
highlight-matching-tag|vin|0.9.5
markdown-all-in-one|yzh|2.5.1

(5 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
What does the errors panel show?

**Comment by kyonkopa** [comment]
There are no errors showing as nothing is wrong with the file itself, attached is a screenshot.

![fefefeefefef](https://user-images.githubusercontent.com/20021882/69233695-4d150300-0b85-11ea-904d-5f6d0809a2bd.PNG)

**Comment by jrieken** [comment]
I meant this view ⬇️ 

<img width="892" alt="Screenshot 2019-11-20 at 12 21 11" src="https://user-images.githubusercontent.com/1794099/69234761-3f18af80-0b90-11ea-819f-dcc78e0dc6b9.png">

**Comment by jrieken** [comment]
Also, please set the log level to trace (F1 > Log Level) and check for messages with "DecorationsService#getDecoration#getOrRetrieve"

**Comment by kyonkopa** [comment]
As you can see there are no errors, also I've set log level to trace and have restarted vscode.

![fererer3r3r3r3r3r3r3r35](https://user-images.githubusercontent.com/20021882/69235327-10e3a180-0b89-11ea-84d7-64e5c632ee2e.PNG)

**Comment by jrieken** [comment]
> also I've set log level to trace and have restarted vscode

So? What does it say?
