### ISSUE TITLE
Explorer icon disappears

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode#85119]
- VSCode Version: 1.40.0
- OS Version: Windows 10

 In the new version, every time I click a different icon the icon for Explorer disappears:

Right after opening VSCode:

![image](https://user-images.githubusercontent.com/16131590/69145788-5c814700-0ac6-11ea-8db8-804696da8e5a.png)

And when I click Search:
![image](https://user-images.githubusercontent.com/16131590/69145836-76228e80-0ac6-11ea-8484-1a487e83f01c.png)

**Comment by egamma** [comment]
/needsMoreInformation can you please a screen recording that illustrates the problem.

**Comment by moseleyi** [comment]
Here you go:

![ezgif-1-89661c169f9c](https://user-images.githubusercontent.com/16131590/69239509-4d67cb00-0b92-11ea-8c00-dfd4e5aac3b5.gif)

**Comment by ankemzi** [comment]
I have the same issue
Any solution yet? This is very provocating.

**Comment by sbatten** [comment]
@moseleyi I 100% agree that this issue would be annoying, unfortunately, I just cannot reproduce it yet, so I am not sure the cause.

@sandy081 have you seen this, or have ideas at what could be unique here?

**Comment by walaric** [comment]
I had the same issue and i fixed it by deleting my personal settings of vsc into my home.

**Comment by sandy081** [comment]
I have not seen this issue too. 

Can you please reproduce it on a fresh user data directory? You can use command line option `code --user-data-dir <path_to_dir>`  and launch code.

**Comment by moseleyi** [comment]
Version 1.41.1 still happening

**Comment by moseleyi** [comment]
If I click CTRL + SHIFT + N to open fresh window of VSCode then the icon is completely gone. Then I select OPEN FOLDER and choose different folder - the icon disappears

**Comment by sbatten** [comment]
@moseleyi I am still not able to reproduce the issue, did you try the steps provided by @sandy081
