### ISSUE TITLE
Stop updating

### ISSUE THREAD

**Issue by MarkMoretto** [microsoft/vscode#85118]
Issue Type: <b>Bug</b>

Not a bug, but please stop trying to "improve" VSCode, in particular, the design and layout.

Microsoft has a habit of ruining things and VSC, along with Excel, is already going down that path.  Please, stop. Let us enjoy something for a while.  

Whatever changes were made in the latest update...not good. I don't need a purple bottom., weird windows, unexpected theme and setting changes.  It's frustrating.  I'll happily stop using VSCode if it goes the way of Visual Studio since there are a lot of great competitors out there.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.16299

**Comment by DiamondYuan** [comment]
I think you can fork VS Code and build the old Version.

**Comment by MarkMoretto** [comment]
@DiamondYuan Thanks, Yuan! I'll try that.

I don't mind a lot of the updates, but MS rendered VS Community pretty much unusable for me and I wish there would be a "required and optional" selection list for each update.  Probably not feasible now, but maybe down the line.

**Comment by egamma** [comment]
@MarkMoretto 

Can you please file separate issues for the problems you mention above:

>Whatever changes were made in the latest update...not good. I don't need a purple bottom., weird windows, unexpected theme and setting changes.
