### ISSUE TITLE
Output console does not scroll after an error on compilation

### ISSUE THREAD

**Issue by jepessen** [microsoft/vscode#85115]
Issue Type: <b>Bug</b>

Create a cmake project.
Build it.
Make an error on source code or cmake files
Build it.
After the error, fix the error and build it again.

The output window in the last build (after the error fix) does not scroll anymore.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.2.2
vscode-database|baj|2.2.0
Doxygen|bbe|1.0.0
theme-verdandi|be5|2.0.1
vscode-icontheme-nomo-dark|be5|1.3.6
mapfile|chi|0.0.1
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
gitlens|eam|10.2.0
tslint|eg2|1.0.44
ada|Ent|0.88.0
eppz-code|epp|1.2.41
vsc-material-theme|Equ|30.0.0
file-icons|fil|1.0.19
auto-close-tag|for|0.5.6
cmake-test-adapter|fre|0.3.1
matlab|Gim|1.4.0
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.162
vscode-test-explorer|hbe|2.14.6
latex-workshop|Jam|8.4.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-idl|kur|0.1.2
vscode-simple-icons|Lau|1.11.10
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
rainbow-csv|mec|1.3.1
openapi-lint|mer|1.0.4
perl-debug|mor|0.6.3
vscode-docker|ms-|0.8.2
python|ms-|2019.11.49689
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
cmake-tools|ms-|1.2.2
cpptools|ms-|0.26.1
csharp|ms-|1.21.7
powershell|ms-|2019.11.0
mq4|ner|1.0.4
theme-dreamweaverweb|Per|1.6.2
material-icon-theme|PKi|3.9.1
webstorm-icons|pms|1.0.0
vscode-yaml|red|0.6.1
vscode-field-lights|sve|0.0.11
pdf|tom|0.5.1
cmake|twx|0.0.17
vscode-icons|vsc|9.5.0
markdown-pdf|yza|1.4.1
material-theme|zhu|3.0.3
html-css-class-completion|Zig|1.19.0

(92 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Please first file agains tthe C extension which you are usign so they investigate and provide nice reproducable steps so we can investigate more on the vscode side. Thanks
