### ISSUE TITLE
Step back and reverse continue have wrong icons

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#85111]
1. Install Mock Debug
2. Have a readme.md file, put a breakpoint and start a mock debug session
3. Notice that the Step back and reverse continue have the bad icons

Reverse continue should have the icon that is currently used for step back
Step back should have the icon that is step over rotated for 180 degrees.

I checked the code and the issue is that the step-back really uses a wrong icon [here](https://github.com/Microsoft/vscode/blob/e0a43e6f6d9cac62b8f791bee8fb109123be1c37/src/vs/base/browser/ui/codiconLabel/codicon/codicon.css#L404)
And there does not seem to be an icon called `reverse-continue`, so the reverse continue uses a continue icon [here](https://github.com/Microsoft/vscode/blob/e0a43e6f6d9cac62b8f791bee8fb109123be1c37/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L307)
The correct icon for the `reverse-continue` is what the current `step-back` icon is

found by @weinand

![Screenshot 2019-11-19 at 12 19 27](https://user-images.githubusercontent.com/1926584/69142324-d87b8f00-0ac6-11ea-8faa-fe7c0fc4db7d.png)

**Comment by misolori** [comment]
Sorry about that, this was an oversight on my part. This is fixed now:

![image](https://user-images.githubusercontent.com/35271042/69166726-90e60a80-0aa8-11ea-9e2e-9875578ac098.png)

**Comment by isidorn** [comment]
Great, thanks!
I just tried it out and it works well, thus adding verified label
