### ISSUE TITLE
Go to implementation with source file open in split view

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#85110]
Issue Type: <b>Bug</b>

If I have a two files open with one holding an implementation used in the second one, go to definition/implementation will open a new editor instead of jumping to the already open editor.

VS Code version: Code - Insiders 1.41.0-insider (1c9fd8a59787487ca71d8c5ce140569a0e036a15, 2019-11-19T06:57:37.884Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|-psn_0_12753961|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
This is controlled via the `workbench.editor.revealIfOpen` setting.

**Comment by bm-stschneider** [comment]
didn't even knew there is something like that.
