### ISSUE TITLE
Icons are not properly rendered in embedded terminal

### ISSUE THREAD

**Issue by WyRe** [microsoft/vscode#85114]
- VSCode Version: `1.40.1 8795a9889db74563ddd43eb0a897a2384129a619 x64`
- OS Version: `Linux 5.3.11-zen1-1-zen x86_64 GNU/Linux`

Steps to Reproduce:

1. Set your Terminal font in settings
2. Open the embedded terminal
3. You will get the following result

![Captura de pantalla_2019-11-19_12-42-26](https://user-images.githubusercontent.com/4059108/69144216-18dd0c00-0acb-11ea-917f-d49590b7a2c1.png)

As you can see the icons are cut. I'm not sure if this could be related with video driver, because I have a laptop with an Intel GPU (`i915` driver) and it is not showing the issue. I've not tried with a different font but I would like to use that one (`DejaVuSansMono Nerd Font`).

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Unicode width handling tracked in https://github.com/xtermjs/xterm.js/issues/1709

This will probably work with the experimental webgl renderer that just landed in Insiders:

```
"terminal.integrated.rendererType": "experimentalWebgl"
```
