### ISSUE TITLE
[UI] [Integrated Terminal] Add a "Clear Terminal" button/icon next to "Kill Terminal"

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#85128]
I tried searching for any duplicates, but it's mostly about clearing terminals via debugging sessions, killing terminals not killing correctly, etc. But, never any requested issues about UI changes to the integrated terminals itself.

![](https://i.imgur.com/BF7Bf0y.png)

As shown here, currently on Visual Studio Code 1.40.1 latest stable release, the integrated terminal only has a "Trash Bin" icon, which represents the action to "Kill the Terminal". I would like to request for a "mop or rag cloth icon", or "something that represents cleaning up" to "Clear the Terminal's Text Buffer", so I can simply wipe clean of the text buffers in the same integrated terminal instance without having to "Kill the Terminal".

Right now, there is no UI icon that allows the user to click to clear the terminal and not kill the terminal.

Hence, the feature request. Thanks.

**Comment by Tyriar** [comment]
We've discussed this before, we don't want to add more buttons to avoid cluttering the UI, you have some options though:

- Run `clear`/`cls` in the terminal
- Run clear via the command palette (F1)
- Setup a keybinding to clear the terminal

**Comment by tommai78101** [comment]
Fair enough. Thanks for letting me know.

Found a 4th option. Right-clicking and selecting "Clear" in the terminal.

![](https://i.imgur.com/8WaJ13R.png)
