### ISSUE TITLE
The contents of the file are suddenly overwritten with the contents of other files.

### ISSUE THREAD

**Issue by Johnxjj** [microsoft/vscode#85120]
First I open a file named "lfs_common.h", then I search for a variable in the file, press CTRL+F, and the content of the file will be named "CompileDef.h" file coverage. If pressing CTRL+F once will not succeed, you can succeed by pressing a few more times.

**Comment by gjsjohnmurray** [comment]
Sounds like when you open your first file you get it in [Preview Mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode)

**Comment by egamma** [comment]
Can you please add a screen recording that illustrates the problem (assuming it is not user confusion with regard to the Preview Mode).

**Comment by Johnxjj** [comment]
This problem may be caused by the Chinese character transcoding plugin. I uninstalled all the plugins yesterday and the problem can no longer be reproduced.
