### ISSUE TITLE
Menu can be lost

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#85124]
1. Open Settings.
2. Set ```"window.menuBarVisibility": "compact"```
3. On View\Appearance submenu uncheck ```Show Activity Bar```
4. Close Settings tab.

Now what?

You need to remember the Ctrl+, shortcut (Windows) to get back to the Settings tab and reinstate a menubar menu.

Perhaps in this situation the Alt key on its own could reveal the Activity Bar, making the compact menu button appear.

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by kingma-sbw** [comment]
In #121913  I reproduced this error in the gui by navigating View / Appearance / Show Menu Bar switching it off. The Alt key does not show the menu bar. (I remember it did in previous versions)

**Comment by theking2** [comment]
was the behavior of the Alt key changes since the .53 version for Windows? On Linux the menu bar still pops up when pressing Alt.

**Comment by kingma-sbw** [comment]
> was the behavior of the Alt key changed since the .53 version for Windows? On Linux the menu bar still pops up when pressing Alt.
> Version 1.53.0 Fedora. But on Windows it does not confusing a lot of coders
> 
> It is just a pain to go through all StackExhange posts to point out that Alt no longer works on Windows vscode to temporarily reveal the Menu Bar. And btw it is not in compliance with documented behaviour: https://code.visualstudio.com/docs/getstarted/userinterface

The behaviour was changed and the documentation updated now to reflect the new behavirou.

**Comment by sbatten** [comment]
unlikely to do anything here in the near future, haven't seen any feedback about losing the menu
