### ISSUE TITLE
Commit message not handled correctly

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#85126]
Issue Type: <b>Bug</b>

If you enter this commit message, the second line will be missing from the commit:
```
foo
#ticket-id closed
```

If you enter this commit message, you won't be able to commit anything:
```
#foo
#ticket-id closed
```

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (33.48GB free)|
|Process Argv|hub-ui/hub-ui.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
generateuuid|Fir|0.0.5
shell-format|fox|6.1.3
vscode-mocha-test-adapter|hbe|2.1.2
vscode-test-explorer|hbe|2.14.6
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
docthis|joe|0.7.1
terraform|mau|1.4.0
code-beautifier|mic|2.3.3
vscode-lebab|mrm|2.6.0
vscode-puglint|mrm|2.3.0
vscode-paste-image|mus|1.0.4
vscode-yaml|red|0.6.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/84201#issuecomment-553924138
