### ISSUE TITLE
Activity Bar context menu lacks option for showing menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#85122]
Issue Type: <b>Bug</b>

1. Have the Activity Bar visible.
2. Opt to have Compact menu there.
3. Context menu of Activity Bar has a 'Hide Menu' option (since #81462 I think). Select it.
4. Compact menu disappears.
5. Try to use the same context menu to bring it back, but there's no option for that. Instead you have to open Settings and reset ```window.menuBarVisibility``` to ```compact```

VS Code version: Code - Insiders 1.41.0-insider (29b99f85e54aa5af6cd4edf918a67d4f70a10aea, 2019-11-19T10:22:48.048Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sbatten** [comment]
this works as requested in the web, but not on desktop, this is intentional since the compact menu is not meant to be surfaced so easily on desktop.

**Comment by gjsjohnmurray** [comment]
> 
> 
> this works as requested in the web, but not on desktop, this is intentional since the compact menu is not meant to be surfaced so easily on desktop.

@sbatten in that case perhaps the easy way of hiding the compact menu should also not be surfaced on desktop. At the moment things are inconsistent, as I need to go to Settings to turn the compact menu on but I can then turn it off from a context menu.
