### ISSUE TITLE
Go to next error or warning filtering

### ISSUE THREAD

**Issue by giantmustache** [microsoft/vscode#85131]
As described here in my question: https://stackoverflow.com/questions/58930553/visual-studio-code-go-to-next-error-or-warning-but-not-to-info

I am using the code spell checker plugin by street side software and I am getting simple INFO issues in the issue bar. When I press `F8` I expect to go to the next error or warning, but it also goes to the next info. Filtering in the issue bar is not taken into account when pressing `F8`. I would like to request that filtering somehow works, or that there is a way to set the level in the configurations for the "go to next problem" commands.

**Comment by sandy081** [comment]
Filters in problems panel are local and not applied everywhere. This needs a new filter for go to feature.
