### ISSUE TITLE
Mac: Delete button removes selected breakpoint

### ISSUE THREAD

**Issue by burkesuitable** [microsoft/vscode#85136]
## Description

It's a small pain point that removing a specific breakpoint during a debugging session requires right clicking the breakpoint and selecting the context option `Remove Breakpoint`. It would be a more pleasant development experience if I could left click to select the breakpoint in question, press either of the Delete keyboard buttons, and the breakpoint is removed.

### VS Code
```bash
$ code --version
1.40.1
8795a9889db74563ddd43eb0a897a2384129a619
x64
```

### Operating System
macOS Catalina version 10.15.1

**Comment by isidorn** [comment]
You can use cmd + backspace to delete the breakpoint
If you do not like this keybinding you can customise it here

![Screenshot 2019-11-20 at 11 09 02](https://user-images.githubusercontent.com/1926584/69229690-3622e080-0b86-11ea-9632-c346958306c1.png)
