### ISSUE TITLE
Missing SVG file extension in Save As dialog window

### ISSUE THREAD

**Issue by Ngranger** [microsoft/vscode#85134]
For months now, regardless of the version Visual Studio Code won't allow me to take a file and just simply use the "Save As" dialog to give it a name like "Logo.svg" without the extra step of having to go the "All Files" option under "file type" in the save window.  However if I wanted to save it as XML or just about any other file extension I easily could because they are listed already.
![Screenshot 2019-11-19 09 45 160](https://user-images.githubusercontent.com/28519061/69162067-b3c8ec80-0ab1-11ea-9b7e-55d0a3f9ec2e.png)
As you can see the SVG file extension is not shown at all as an option, kindly fix this error.

**Comment by egamma** [comment]
SVG support is added by an extension and not built-into VS Code.

Try for example: https://marketplace.visualstudio.com/items?itemName=jock.svg
