### ISSUE TITLE
Stylelint doesn't work in .ts file

### ISSUE THREAD

**Issue by daviddelusenet** [microsoft/vscode#85130]
- VSCode Version:  1.40.1
- OS Version: macOS 10.15.1

### Steps to Reproduce:

I'm setting up a new project with React, Styled Components and TypeScript. I've already done this before and I'm basically reusing the exact same setup.

However, in my new project the [VS Code Stylelint extension](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint) doesn't work in `.ts`/`.tsx` files. It does work in `.js` files.

I'm using the same versions of everything and the exact same configuration. Some screenshots will follow now.

Working example of Stylelint in a `.js` file:

![Screenshot 2019-11-19 at 15 51 18](https://user-images.githubusercontent.com/1398418/69157051-ab3dd980-0ae4-11ea-944c-ebddc8e1462a.png)

Not working in a `.ts` file:

![Screenshot 2019-11-19 at 15 51 32](https://user-images.githubusercontent.com/1398418/69157067-b6910500-0ae4-11ea-9e8b-99daed1f98f1.png)

Exactly the same setup in another project, there it does work:

<img width="1792" alt="Screenshot 2019-11-19 at 15 54 07" src="https://user-images.githubusercontent.com/1398418/69157153-d7595a80-0ae4-11ea-85c6-53c59cc39561.png">

Please let me know if you need any more information, would love to provide it. This is driving me totally crazy.

**Comment by egamma** [comment]
Please file the issue against the StyleLint extension.

**Comment by daviddelusenet** [comment]
Thanks for the help @egamma !

**Comment by daviddelusenet** [comment]
I'm not sure why you close this issue @egamma. If everything is exactly the same in both projects but in one it works and in the other it doesn't, how can you be so sure that's the plugins fault instead of VS Code itself?

**Comment by daviddelusenet** [comment]
Also opened an issue on Stackoverflow: https://stackoverflow.com/questions/58940378/cant-get-vs-code-stylelint-extension-to-lint-in-ts-files

**Comment by egamma** [comment]
@davidbailey00 

>I'm not sure why you close this issue @egamma.

The issue cannot be reproduced given the steps you have provided in VS Code with all extensions disabled. Therefore the suggestion is to file the issue against the involved extension first.

**Comment by davidbailey00** [comment]
> @davidbailey00
>
>  >  I'm not sure why you close this issue @egamma.

I think you meant to tag @daviddelusenet?

**Comment by daviddelusenet** [comment]
Oh well, the author has deleted the extension.....
