### ISSUE TITLE
The last update of VSCode doesn´t work any more (OS: Win7).

### ISSUE THREAD

**Issue by ericmosvel** [microsoft/vscode#85133]
- VSCode Version: x64-1.40.1exe
- OS Version: Win7Professional

Steps to Reproduce:

1.  The last week i was working with VScode well but two days ago when i a try to open VScode didn't work, the screen went black (Vscode's layout).

Does this issue occur when all extensions are disabled?: No

**Comment by egamma** [comment]
/needsMoreInfo

>to open VScode didn't work, the screen went black (Vscode's layout).

Is there any error message when this happens?

**Comment by ericmosvel** [comment]
> /needsMoreInfo
> 
> > to open VScode didn't work, the screen went black (Vscode's layout).
> 
> Is there any error message when this happens?

Yeah look, this the error messange  @egamma 
"the window has crashed
We are sorry for the inconvenience! you can repoen the window to continue where you left off."

[https://ibb.co/cTkW4BM](url)

**Comment by egamma** [comment]
@ericmosvel is there an error message in developer tools console (Help>Toggle Developer Tools, switch to the Console tab).

**Comment by ericmosvel** [comment]
> @ericmosvel is there an error message in developer tools console (Help>Toggle Developer Tools, switch to the Console tab).
thanks!
Done. Now what should i do
