### ISSUE TITLE
PHP return type declaration not highlighted on anonymous function

### ISSUE THREAD

**Issue by tokc** [microsoft/vscode#85132]
In PHP, the return type declaration on an anonymous function (closure) is not highlighted in the same colour as the same type declaration on a named function.

Version: 1.41.0-insider
Commit: 29b99f85e54aa5af6cd4edf918a67d4f70a10aea
Date: 2019-11-19T10:25:09.288Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

Steps to Reproduce:

1. Open or create a PHP file, such that the code within is syntax-highlighted as PHP.
2. In the file, write an anonymous function.

Expected behaviour: The return type declaration on the anonymous function is highlighted in the same colour as it would be on a named function. (Blue, in the case of attached image.)

Observed behaviour: The return type declaration appears to not be highlighted. (White, in the case of attached image.)

Does this issue occur when all extensions are disabled?: Yes

<img width="1201" alt="Screenshot 2019-11-19 at 16 18 59" src="https://user-images.githubusercontent.com/9549927/69159513-569c5d80-0ae8-11ea-914d-ba5df215e6fa.png">

*Additional Information:*
The attached code snippet appears to be correct. I tested this by running the code with `php filename.php` in a terminal, and getting the expected output with no errors. I also tried a version of the code with *wrong* types declared in the closure (`$toast = function (string $letter): string {` on line 13 in the attached code snippet), and this produced TypeError as expected.

Code used to test:
```php
<?php

function doubleLetter(string $letter): string {
    return $letter . $letter;
}

$test = [
    'a',
    'b',
    'c'
];

$toast = function (string $letter): string {
    return $letter . $letter;
};

$doubledTest = array_map(function (string $letter): string {
    return $letter . $letter;
}, $test);

echo $toast('a');
```

It would appear the code block in Github exhibits the same behaviour, so that might help narrow down the issue if the source of the syntax highlighting is the same.

**Comment by alexr00** [comment]
@tokc thank you for the clear/thorough repro steps! It turns out that is has already been fixed in the repo we get the grammar from (https://github.com/atom/language-php/issues/367). I just pulled in the update so you should see the fix in the next insiders build.
