### ISSUE TITLE
Consider another color (blue) for Extension view Enable button

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8514]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 10

The beige yellow Enable button does not look compelling IMO.  I can see that you wanted to contrast the green Install button (green means go) but yellow means yield and isn't attractive.

Consider using blue which is a very common button color and will have good contrast on both light and dark themes.  We generally use blue for highlighting and in this case we want to highlight that you need to take an action to enable the extension.

**Comment by bgashler1** [comment]
We talked in UX meeting about making this button the default blue color.

**Comment by isidorn** [comment]
I like how blue blends into the viewlet - thanks for the nice suggestion.
Check it out nad let me know what you think
