### ISSUE TITLE
Test: LCD rendering

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#85143]
Refs: https://github.com/microsoft/vscode/issues/84715

- [x] Linux @octref
- [x] Windows @sbatten

Complexity: 3

This milestone we worked on making each part of the workbench render with subpixel-antialiasing. Currently the only way to find out is by making a screenshot and zooming in enough to see pixel rendering.

Here you can see the before (up - greyscale) and after (down - notice the colored pixels):

![image](https://user-images.githubusercontent.com/900690/69172102-86099500-0afd-11ea-987d-46b96d37e678.png)

Run through our UI (all views, all panels, all editors, status, title, activity bar) and find areas where you notice greyscale rendering. 

**Note:** already known issues are that quick open and notifications render with greyscale. Use the [lcd-text-rendering label and query](https://github.com/microsoft/vscode/labels/lcd-text-rendering) to find existing issues!

**Comment by octref** [comment]
One thing I'm not sure is if we count webviews such as Markdown Preview as part of our workbench UI. Currently text there are using greyscale rendering.

![image](https://user-images.githubusercontent.com/4033249/70094411-510a4180-15d7-11ea-98dc-9004fc8b4b6e.png)
