### ISSUE TITLE
Open Recent window is really tall

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85147]
I think this is new? Seems excessive

![image](https://user-images.githubusercontent.com/323878/69175139-102f0a80-0ab8-11ea-8a91-3bcf9a12032e.png)

**Comment by roblourens** [comment]
And the quickopen window is still a reasonable height

**Comment by bpasero** [comment]
Possibly a regression from @chrmarti changes to support dynamic height. I would make the picker use the same size as quick open so that we are consistent as long as we still have 2 widgets. For a user it maybe confusing that the height differs.
