### ISSUE TITLE
save not doing anything

### ISSUE THREAD

**Issue by avishai84** [microsoft/vscode#85149]
Issue Type: <b>Bug</b>

Click on "save" in menu, or press ctrl + s
Nothing happens.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.6.0

**Comment by avishai84** [comment]
https://developercommunity.visualstudio.com/content/problem/165245/save-not-doing-anything.html

**Comment by egamma** [comment]
You have reported the issue against the wrong repository. This is the Visual Studio Code repository.
