### ISSUE TITLE
Breakpoints

### ISSUE THREAD

**Issue by cmaga** [microsoft/vscode#85146]
Issue Type: <b>Bug</b>

When I run the debugger it does not stop at breakpoints....at any breakpoint anywhere.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.14
mips|kda|0.0.5
remote-wsl|ms-|0.40.3
cpptools|ms-|0.26.2-insiders
veriloghdl|msh|1.0.4
vim|vsc|1.11.3

</details>

**Comment by egamma** [comment]
/needsMoreInfo

What language are you trying to debug. From the installed extensions this could be the C++ extension, pls file the issue against this extension.
