### ISSUE TITLE
```git.ignoredRepositories``` does not support case insensitive file systems

### ISSUE THREAD

**Issue by Wowol** [microsoft/vscode#85158]
- VSCode Version: 1.40.1
- OS Version: **Windows_NT x64 10.0.19013**

Steps to Reproduce:

1. Open directory with several git repos
2. Add one repo in ```Ignored Repositories``` setting, for example ```C:\Projects\example```
3. Repo will not be ignored, because drive letter 'C' is in uppercase. It works correctly if we type ```c:\Projects\example```.

I guess this setting shouldn't look at case on case insensitive file systems (like Windows).

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
It probably doesn't matter, but it looks like the git extension isn't listening to changes on `git.ignoredRepositories` since a reload is required.

**Comment by joaomoreno** [comment]
@alexr00 The setting is read once a repository is _discovered_. Once it is open, it remains open regardless of the setting. Much like once a file is in the repo, adding it to .gitignore isn't enough, it must also be removed from the repo.
