### ISSUE TITLE
Debugger icons are not vertically aligned

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#85162]
- VSCode Version: Insiders 3b17b7943842e84912a5507111a6cd790db18a46
- OS Version: Darwin x64 18.0.0

Steps to Reproduce:

1. Set a tall line height
2. Set a breakpoint
3. Icons are misaligned

![image](https://user-images.githubusercontent.com/2230985/69197433-2784ec80-0ae6-11ea-8245-bb5001015ee2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
Breakpoints are now vertically centered:

![gif](https://user-images.githubusercontent.com/35271042/69268606-5356af80-0b84-11ea-86ea-65a722e852f8.gif)

FYI @isidorn @weinand
