### ISSUE TITLE
Enable Views to move between sidebar and panel (Part 1)

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#85164]
Aggregating prior discussions from abandoned PRs.

- [x] Update `PanelPart` with `ViewContainer` logic existing in `ActivityBarPart` with support for hiding a panel when empty https://github.com/microsoft/vscode/pull/87444
- [x] Abstract viewlet/panel creation away https://github.com/microsoft/vscode/issues/87246
- [x] Use views service to move views between containers https://github.com/microsoft/vscode/issues/87461
- [x] Support tracking view position on reload https://github.com/microsoft/vscode/pull/88656
- [x] Add generic `move to panel` / `move to sidebar` commands for movable views https://github.com/microsoft/vscode/pull/88823
- [x] Fix issue with render being called twice for header actions. https://github.com/microsoft/vscode/pull/88433
- [x] Add movable property to views and enforce icon per view https://github.com/microsoft/vscode/pull/88823
- [x] Update theming for views to support panel theming
- [x] Move search view to new model https://github.com/microsoft/vscode/pull/89190
- [x] Enable outline view to move https://github.com/microsoft/vscode/pull/89240
- [x] Enable custom views to move https://github.com/microsoft/vscode/pull/89240
- [ ] Provide method for views to persist state during move
- [ ] Introduce ability to contribute a `View` to a `Panel` for extensions (should have its own item)

**Comment by sbatten** [comment]
First PR: https://github.com/microsoft/vscode/pull/84642
From @sandy081
> My feedback on the design:

>I have a basic question on the design, why are you not using `ViewDescriptor` and `ViewRegistry` which is already an abstraction for all views (in Sidebar & Panel). There is also `ViewContainer` which can be used for the location of `ViewDescriptor`.  Currently only sidebar views use view descriptors. So my suggestion would be to start moving Panels using view descriptors by creating a new View Container for each panel (similar to viewlets). This can allow moving views not only across side bar and panel but also across each viewlet. It will also give infrastructure for providing custom views in panels.

>Current `ViewRegistry` already supports moving views from one view container to another. 

>https://github.com/microsoft/vscode/blob/88c2100793b73cebda2d7753ac4bf52060671653/src/vs/workbench/common/views.ts#L171

>Views are updated in the Viewlets when views are added/removed/moved. 

>As said, currently viewlets use view descriptors and the first step would be to let panels also us it.

**Comment by sbatten** [comment]
Follow-up PR: https://github.com/microsoft/vscode/pull/85096
From @sandy081 
>Note: We gonna use `pane` for split views.

>Not sure if we are on right track. I see it is very confusing to have `PanelViewlet` which provides functionality of `Viewlet` and `panes`. This is restricting only Viewlets to extend this functionality because of the inheritance.  

>I would suggest to do following

>1.  Move `panes` specific functionality from `PanelViewlet` to a new class called  `PaneContainer`.

>2. Lets use composition instead of inheritance. Merge `PanelViewlet` into `ViewContainerViewlet` and let `ViewContainerViewlet` uses `PaneContainer` to manage `views`.

>3. Move `views` specific functionality from `ViewContainerViewlet` into a new class called `ViewContaier` that extends `PanelContainerWidget`.  This will make `ViewContainerViewlet` slick and contains only viewlet specific knowledge.

>4. Use `ViewContaier` when moving Panels to view containers and views just like how `ViewContainerViewlet` does. 

From @isidorn 
>After discussing with @sandy081 we drew this picture together to make things more clear for everybody.

>**Current state**
![WhatsApp Image 2019-11-19 at 11 21 33 (1)](https://user-images.githubusercontent.com/1926584/69138398-e5948000-0abe-11ea-81b4-4b31ddeecf35.jpeg)

>**Future state**
![WhatsApp Image 2019-11-19 at 11 21 33](https://user-images.githubusercontent.com/1926584/69138399-e5948000-0abe-11ea-8503-d35648b24319.jpeg)


>Some notes:
>* I like the idea of renaming Split View `Panels` to `Pane`. 
>* I agree with everything @sandy081 pointed out in the previous comment. The best place to start is on the left part of the picture - restructuring the viewlet infrastructure to make it align better with our future architecture. Changing Panels is step2
>* `Viewlet` = `Composite` + `Viewlet` specifc knowledge
>* `ViewViewelet` = `Viewlet` + `ViewContainer` (knowledge about registering new views)
>* PaneContainer = A container around SplitView which can add panes, remove panes
>* `ViewContainer` = `PaneContainer` + knowledge around view, registering views etc.
>* `PaneContainer` and `ViewContainer` should probably be just merged into one class. We believe this will simplify things. This class cares about registergin views and forwarding everything to the `SplitView`

**Comment by sbatten** [comment]
@sandy081 @isidorn I got working the restructuring of design and ran into some problems. Below is the commit on my fork and I will summarize the steps taken so far.

https://github.com/sbatten/vscode/commit/9afe8b9e3d0d90cfd77f63764aa203a3be40c630

1. Rename `PanelViewlet` to `ViewPaneContainer`. This combines the concept of a `PaneContainer` and the knowledge about view registration. I just jumped to combining these concepts into one since we don't have a use to separate them currently.
2. Remove `entends Viewlet` from above `ViewPaneContainer`. This meant moving some functionality provided by `Viewlet` or its base classes into `ViewPaneContainer` but this was small and fairly simple.
3. Move all view logic from `ViewContainerViewlet` view/pane logic into `ViewPaneContainer`. This was a lot of code change and was fairly simple on the `ViewPaneContainer` side. However, on the `ViewContainerViewlet` side, we need to expose functions from `ViewPaneContainer`.

### Problems

1. `ViewContainerViewlet` frequently needs to expose functionality from `ViewPaneContainer` that it used to have direct access to but doesn't anymore due to composition. 

2. Derived classes of `ViewContainerViewlet`(e.g. SCMViewlet) assume they have access to the `ViewPane`s through inheritance. My feeling is that the majority of these implementations rely heavily on inheritance of the pane manipulation. In order to fix this, I feel I have to write a bunch of methods on `ViewPaneContainer` to expose this access.

3. The previous interface for `ViewContainerViewlet` used its access to create a standard of working with the `ViewPane`s. After exposing everything above in `ViewPaneContainer`, I will have to mirror this code in `ViewContainerViewlet`.

4. Lastly, everything I do for in the Viewlet class ends up being not `Viewlet`-specific but necessary to prevent every derived class from having to duplicate it. This means `Panel` will eventually have to do this.

### Proposal

Perhaps I am overthinking it, so I thought I would share my progress but additionally share another proposal for design structure. Here is a diagram I drew.

![image](https://user-images.githubusercontent.com/6561887/69391013-4cb06100-0c86-11ea-81c6-3a8caa7cb5d7.png)

1. `FancyComposite` (name not permanent) is a class that composes the `ViewPaneContainer`. It would take a `ViewPaneContainer` in its constructor. This allows `Panel` and `Viewlet` to benefit from the composition aspect without any duplication of code.

2. `Panel` and `Viewlet` are thin layers above `FancyComposite` to do anything specific.

3. `ViewPaneContainer` functions almost identically as it would in the previous proposal.

4. `ExplorerViewPaneContainer` and other view containers would extend `ViewPaneContainer` instead of a `Viewlet` or `Panel`.  As stated above, I feel these view containers are doing more logic relevant to the `ViewPaneContainer` than the `Viewlet` itself. Additionally, `ViewPaneContainer` is just a collection of views which is the end-goal for these contributions.

Let me know what you think of this proposal or if you have ideas on addressing my issues with the original proposal.

**Comment by isidorn** [comment]
@sbatten thanks for the nice picture. Having the `FancyComposite` makes sense to me. And if the new architecture works better for you I fully support it.
However one thing which is not clear to me is why would the `Explorer` and other views extened the `ViewPaneContainer`. Why don't we make the `ViewPaneContainer` protected in the `FancyComposite` so that the `Explorer` and other viewlets / panels can access it once they inherit from Panel / Viewlet.
I am just worried if making the `Explorer` and all other views no longer a Viewet / Panel would prove to be much more work (for example in the `ViewletService` etc...) and would change something that a lot of us are used to: Explorer being a Viewlet.

Let me know what you think.

**Comment by sandy081** [comment]
Discussed with @isidorn and here is what we think:

I also agree if the new architecture works for you, go for it. I also liked the direction where it is going that there will be no `viewlets` and `panels` in future and its all `views` and `view containers`. 

I think renaming current viewlets (Explorer, SCM and others) to view containers and extend `ViewPaneContainer` is less work, because these viewlets extend and override `ViewPaneContainer` behaviour more than providing viewlet behaviour. I am not much worried about what we are used to if we get a nice and clean design.

Also, this means that we will have single generic `Viewlet` implementation and all current viewlets register this `Viewlet` in viewlet descriptor registry with their respective ids. Once we reach this, I would recommend to move registering viewlet inside View container registry and make it an implementation detail. So it means, if I want to create a view container say `explorer` in activity bar, I would just register a view container providing my `ExplorerViewContainer` implementation. Eg:

```
Registry.as<IViewContainersRegistry>(ViewContainerExtensions.ViewContainersRegistry).registerViewContainer(
ExplorerViewContainer
'workbench.view.explorer', 
nls.localize('explore', "Explorer"),
ViewContainerLocation.Activitybar,
'codicon-files',
0)`
```

This shall register explorer ViewContainer and also internally a viewlet for explorer should be registered.


**Note:** As @isidorn said there is some code that is accessing these viewlets through viewlet service. So please make sure you take care of this by providing access to `ViewContainer` from `Viewlet`. Eg: 
https://github.com/microsoft/vscode/blob/a153842765bcfebf7243dd593339860c443372b2/src/vs/workbench/contrib/files/browser/fileActions.ts#L655-L656

**Comment by sbatten** [comment]
Added support for ViewPaneContainer in a new Panel https://github.com/microsoft/vscode/pull/87191

**Comment by sbatten** [comment]
Next steps and notes:
- [ ] Update `PanelPart` with `ViewContainer` logic existing in `ActivityBarPart`
- [ ] Support hiding a panel when empty
- [ ] Introduce ability to contribute a `View` to a `Panel`

**Comment by sandy081** [comment]
> Introduce ability to contribute a View to a Panel

@sbatten Is not this supported by adding support -> for ViewPaneContainer in a new Panel

**Comment by sandy081** [comment]
@sbatten Tracking adopting problems panel using views and view containers here - https://github.com/microsoft/vscode/issues/87243

**Comment by lukaszpolowczyk** [comment]
Will it be possible to move views between sidebars?
For example, moving Breakpoints from "Debugg and Run" to "Explorer"?

**Comment by sbatten** [comment]
Work continued in #89729
