### ISSUE TITLE
Telemetry collects geolocation data!

### ISSUE THREAD

**Issue by shasank** [microsoft/vscode#85171]
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

Telemetry collects geolocation data even though there is no explicit permission to do so.
![image](https://user-images.githubusercontent.com/4426919/69207061-9b6dd600-0b74-11ea-9ac0-7717a8738ee8.png)
This is from insight data on Azure

![image](https://user-images.githubusercontent.com/4426919/69207085-ac1e4c00-0b74-11ea-85a5-9867bc12447c.png)
Telemetry settings are enabled

Even a website on a browser has to request user for explicit permission to get location details

And on top this geolocation data is shared with all the extensions installed in my VSCode.
Is there a way to opt out sharing geolocation details and enable Telemetry only for 'Non-privacy invasive' data and errors?

**Comment by kieferrm** [comment]
@shasank can you please provide more details about
> his is from insight data on Azure
and
> on top this geolocation data is shared with all the extensions installed in my VSCode

I'm not sure I understand where you look and what you see.

**Comment by shasank** [comment]
Whenever I send an event using Telemetry
this.reporter.sendTelemetryEvent(…)
the data received on the Azure cloud  (customEvent) also contains geographical information about the user like street name, state and country.

So it’s like a user hasn’t given permission to track his location details (never prompted - whatever mechanisms VSCode might use like mapping ip addresses etc. to obtain near accurate details) but still he is being tracked.
Now any extension which uses Telemetry can access these details (of course installed in my VSCode) - yes VSCode does provide this info to extensions.

Rather it would be nice if the user’s consent is taken to obtain these details and a way to opt out.
