### ISSUE TITLE
GIT Viewlet has left-hand focus indicator, but no other viewlet does

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#8517]
- VSCode Version: 1.3.0-insider 798b41ab1cf3636a27042020a54ddfb4cfb8d23c
- OS Version: Mac OS X Yosemite

![untitled](https://cloud.githubusercontent.com/assets/11839736/16459772/fd76a9f2-3dd8-11e6-82d6-2f37b2ccc433.png)

Steps to Reproduce:

1. Open GIT viewlet and note the left-hand blue indicator
2. Now open another viewlet and note that no indicator is present.

**Comment by bpasero** [comment]
I can reproduce for any viewlet. This happens when you hide a viewlet and makes sense because our focus indicator stays on the focussed element.
