### ISSUE TITLE
script and style tags loses or incorrect auto-indent on .html file

### ISSUE THREAD

**Issue by soe-wai** [microsoft/vscode#85175]
Issue Type: <b>Bug</b>

when I typed script or style tags on indext.html or other html file extensions then hit tab or enter did'nt turn into auto-indentation next line with its right spaces or tabs, so how do I fix and where do I find to fix the problem above, thank you.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
prettier-vscode|esb|3.8.0
beautify|Hoo|1.5.0
vscode-view-in-browser|kop|1.0.5
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0

</details>

**Comment by soe-wai** [comment]
![VS Code Bug Report 2019-11-20 132804](https://user-images.githubusercontent.com/47550536/69216137-ccaccd00-0b99-11ea-8adc-864b327bffeb.png)
Screen Shot Of The Mention Problem Above.

**Comment by aeschli** [comment]
@soe-wai Sorry, form the screenshots it is not clear to me what the bug is. Can you paste a small code sample and describe the steps to see the issue?

**Comment by soe-wai** [comment]
Here's a Screen-cast For Issue.

[Vs Code Issue Report 2019-12-17 16-31-27.zip](https://github.com/microsoft/vscode/files/3972813/Vs.Code.Issue.Report.2019-12-17.16-31-27.zip)

**Comment by soe-wai** [comment]
> 
> 
> @soe-wai Sorry, form the screenshots it is not clear to me what the bug is. Can you paste a small code sample and describe the steps to see the issue?

[Vs Code Issue Report 2019-12-17 16-31-27.zip](https://github.com/microsoft/vscode/files/3972820/Vs.Code.Issue.Report.2019-12-17.16-31-27.zip)

Sorry for reply lately because of traveling, thank you.

**Comment by aeschli** [comment]
Ok, got it. The problem is that the cursor is already inside JavaScript / CSS and that languages actually don't know of the `</script>` `</style>` closing tag.
