### ISSUE TITLE
Cannot activate the 'Jira and Bitbucket (Official)' extension because it depends on the 'Git' extension, which is not loaded. Would you like to reload the window to load the extension?

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#85177]
Issue Type: <b>Bug</b>

Cannot activate the 'Jira and Bitbucket (Official)' extension because it depends on the 'Git' extension, which is not loaded. Would you like to reload the window to load the extension?
the Git extension is available. it takes a bit of time to load and meanwhile I am getting this message from Jira Extention.

![image](https://user-images.githubusercontent.com/9264813/69215661-4a6bdb00-0b90-11ea-8791-f0c4ed6cad0a.png)

Extension version: 2.1.5
VS Code version: Code - Insiders 1.41.0-insider (4934a6f487b9ed6b99b900ae0710c7b452792e20, 2019-11-20T05:25:39.619Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-64-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (1.49GB free)|
|VM|0%|
</details>

**Comment by sanket-bhalerao** [comment]
Note: I have created this issue using vscode -> Help -> Report Issue.
also selected the proper extension from the dropdown.

![image](https://user-images.githubusercontent.com/9264813/69215836-b2babc80-0b90-11ea-908a-70e4c4644035.png)

however, for some reason this bug is shown against "VSCode" for some reason.

**Comment by gjsjohnmurray** [comment]
I guess the repo for this extension isn't hosted on GitHub. Issue #73515 covers the way the issue reporter behaves in such situations.

Please locate the correct repo host via the extension's details, then log the issue there.
