### ISSUE TITLE
Cannot navigate to exact error line while running a Python file

### ISSUE THREAD

**Issue by Apoorva-GA** [microsoft/vscode#85174]
- VSCode Version:1.40.0
- OS Version:10.14.6 

Steps to Reproduce:

1. Run Python file in terminal (internal terminal)
2. Error happen, I cannot navigate to error line using cmd + click, it only jump to error file, not 
    exact error line

I see the same issue [here](https://github.com/microsoft/vscode/issues/40468)  and its closed but I am still facing this issue.

**Comment by egamma** [comment]
Please file the issue against the Python extension.

**Comment by karthiknadig** [comment]
@egamma We are not in control of the links in the terminal. The pattern that is used there should be updated to handle python style filename and line numbers.

@Tyriar /cc

**Comment by Apoorva-GA** [comment]
@karthiknadig  So the pattern needs to be updated from VSCode side?
@egamma If thats the case can you re-open this issue?

**Comment by Tyriar** [comment]
What do the links look like? Can you show a screenshot?

**Comment by Apoorva-GA** [comment]
Link looks something like `"Path_to_file", line_number`.

Here is the screenshot

![WhatsApp Image 2019-11-27 at 11 41 15 PM](https://user-images.githubusercontent.com/8462534/69749126-d2914800-116f-11ea-91a2-07dac5da9f79.jpeg)

**Comment by Tyriar** [comment]
Oh that's output. It works in the terminal:

https://github.com/microsoft/vscode/blob/9342a27189fb6e6f9397aa3a6f2c249a1d326c6f/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L40

<img width="423" alt="Screen Shot 2019-11-27 at 10 36 30 AM" src="https://user-images.githubusercontent.com/2193314/69750539-da1a0800-1101-11ea-981d-7eb6d3a9fab7.png">

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/85476
