### ISSUE TITLE
Blurry flipped cursor on line number

### ISSUE THREAD

**Issue by MrConnorKenway** [microsoft/vscode#85176]
- VSCode Version: 1.40.1
- OS Version: macOS 10.15.1

Steps to Reproduce:

1. Change the color theme to a dark theme
2. Move the mouse cursor to the line numbers
3. The mouse cursor blurs and it looks quite different from the system's default mouse cursor
<img width="496" alt="image" src="https://user-images.githubusercontent.com/32333772/69215365-75f8c080-0ba4-11ea-9405-8b8b7feade6a.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/32333772/69215369-77c28400-0ba4-11ea-8123-055081eaeba7.png">

Does this issue occur when all extensions are disabled?: Yes

Or maybe you can offer an option to disable the flipped cursor feature to solve this issue?

**Comment by alexandrudima** [comment]
@misolori Here is the CSS we have for the inverse cursor: https://github.com/microsoft/vscode/blob/ff7e302ad6c3ce70e2546ef136b1bf3163bcdeef/src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.css#L29-L34

**Comment by misolori** [comment]
@alexandrudima what was the rationale for flipping the cursor in this instance? I always thought it was a bit odd.

**Comment by alexandrudima** [comment]
I think we took it from Visual Studio or from Word, not 100% sure...

**Comment by misolori** [comment]
@alexandrudima @rebornix what do you think about making this a regular `cursor: pointer` on hover instead of using a custom one? This would match all of our other hover cursors in the gutter:

<img width="100%" src="https://user-images.githubusercontent.com/35271042/69267386-e510ed80-0b81-11ea-9398-b7be12431e3e.gif">

**Comment by alexandrudima** [comment]
@misolori We can try removing the flipped cursor, but I wouldn't make it a hand/pointer, I would just leave it as is... Having it be a pointer over the line numbers feels weird to me.

**Comment by misolori** [comment]
I'm ok with the default cursor as well, the pointer was mostly to indicate that you can select an entire line.

**Comment by misolori** [comment]
This now uses the default cursor (non-flipped) when hovering over line numbers:

![image](https://user-images.githubusercontent.com/35271042/70756095-80643100-1cf0-11ea-8ef1-0b6c216328ed.png)
