### ISSUE TITLE
When webview get focus, can't open color theme interface

### ISSUE THREAD

**Issue by forwardhuan** [microsoft/vscode#85170]
- VSCode Version: 1.40.1
- OS Version: Windows_NT x64 10.0.18362 

Steps to Reproduce:

1. Use a  webview page and click it.
2. Open Setting  --> Color Theme, can't show select color theme interface

**Comment by forwardhuan** [comment]
I made an attempt.  When the mouse removed the WebView, I called “reveal(undefine, true)”, and I  want to make the WebView lose focus, but it didn't work

**Comment by gjsjohnmurray** [comment]
Probably a duplicate of #75209

**Comment by mjbvz** [comment]
Duplicate of #75209
