### ISSUE TITLE
Generic parameter suggestion prompt exception!

### ISSUE THREAD

**Issue by dangaogit** [microsoft/vscode#85185]
Issue Type: <b>Bug</b>

exp: 
The available keys under this ‘interface’ are prompted in the suggestion list
actual:
There is no prompt and using the shortcut key 'ctrl+space' does not appear in the suggestion list

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.0.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 3284)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (2.00GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
vsc-material-theme-icons|equ|1.0.6
prettier-vscode|esb|3.8.0
vscode-language-pack-zh-hans|MS-|1.40.2
material-icon-theme|PKi|3.9.1
vscode-icons|vsc|9.5.0

(2 theme extensions excluded)

</details>

**Comment by dangaogit** [comment]
![vscode-bug](https://user-images.githubusercontent.com/56422770/69222541-a8121e80-0bb4-11ea-815d-87733855538d.gif)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

/needsMoreInfo

**Comment by dangaogit** [comment]
![vscode-bug](https://user-images.githubusercontent.com/56422770/69299161-d5111080-0c4a-11ea-881e-03702c649ac0.gif)

**Comment by mjbvz** [comment]
Text please

**Comment by dangaogit** [comment]
I don't quite understand what you mean.
My problem report can be reproduced as shown in the figure.
desc: Did not get the correct optional attribute prompt when entering, For example, if you enter 'a', you should prompt 'autoIncrement'

I'm sorry, my English is not good. Maybe it's not very accurate

**Comment by mjbvz** [comment]
Please share the text of the code displayed the gif

**Comment by dangaogit** [comment]
```typescript
interface Test {
  keyPath?: string;
  autoIncrement: boolean;
}

function test<T extends Record<string, Test>>(opt: T) {}

test({
  a: {
    keyPath: '',
    autoIncrement: false
  }
})
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/35268 to track upstream
