### ISSUE TITLE
Inconsistent icon theme colors

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#85182]
- VSCode Version: 1.40.1
- OS Version: Windows 10

Install and use [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme). It doesn't look like an issue solely caused by the theme extension.

(All buttons below are enabled except for those with caption "button disabled")

**SCM**
![image](https://user-images.githubusercontent.com/7588612/69218006-cb37d080-0baa-11ea-93e3-9598718ad64a.png)

**Search**
![image](https://user-images.githubusercontent.com/7588612/69218048-e6a2db80-0baa-11ea-9acf-0090cd44dc19.png)

**Search (button disabled)**
![image](https://user-images.githubusercontent.com/7588612/69218128-09cd8b00-0bab-11ea-8cb2-d55c3ea0afca.png)

**Extensions**
![image](https://user-images.githubusercontent.com/7588612/69218266-51ecad80-0bab-11ea-9d25-f705df9331c5.png)

**Extensions (button disabled)**
![image](https://user-images.githubusercontent.com/7588612/69218204-308bc180-0bab-11ea-98a5-014a84e4e17f.png)

cc @misolori

**Comment by misolori** [comment]
This due to our built-in extensions not using our icon font, which isn’t supported yet but is on deck next.

**Comment by misolori** [comment]
## Explorer
![image](https://user-images.githubusercontent.com/35271042/95266755-b1b26e00-07e8-11eb-99cc-9b93a00ed475.png)

## Search
![image](https://user-images.githubusercontent.com/35271042/95266774-bd059980-07e8-11eb-8e01-4a232121e56d.png)

## SCM
![image](https://user-images.githubusercontent.com/35271042/95266792-c5f66b00-07e8-11eb-8d09-e7d695f9df26.png)

## Debug
![image](https://user-images.githubusercontent.com/35271042/95266817-d60e4a80-07e8-11eb-9fba-3050376357cd.png)

## Extensions
![image](https://user-images.githubusercontent.com/35271042/95266838-e0304900-07e8-11eb-9d03-fb6b2ef23852.png)
