### ISSUE TITLE
Tables in markdown preview not rendered correctly

### ISSUE THREAD

**Issue by rfresow** [microsoft/vscode#85183]
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

A table in markdown like:
```
# Table example

Column 1 | Column 2 | Column 3
-------- | -------- | --------
Row_1_1  | Row_1_2  | Row_1_3
Row_2_1  | Row_2_2  | Row_2_3
Row_3_1  | Row_3_2  | Row_3_3
```
Is not rendered correctly anymore. It's now rendered as:

![image](https://user-images.githubusercontent.com/4982940/69218324-c48c6780-0b70-11ea-934b-c6e4a138c434.png)
While it should be rendered more or less like:
# Table example

Column 1 | Column 2 | Column 3
-------- | -------- | --------
Row_1_1  | Row_1_2  | Row_1_3
Row_2_1  | Row_2_2  | Row_2_3
Row_3_1  | Row_3_2  | Row_3_3

Steps to Reproduce:

1. Create a new file in VSCode and paste above markdown in it and save the file with a name with extension .md.

2. Right click on the file tab en choose *Open Preview*.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
It looks like you are using the github styling for the markdown preview (or at least some sort of custom style sheets)? I don't think VS Code's default table rendering has changed?

**Comment by rfresow** [comment]
The Github styling is because I published it here on Github :-). It's the default VSCode styling that's wrong. As you can see, there are some borders around the first data row and no borders around the headers and other rows.

![image](https://user-images.githubusercontent.com/4982940/69268668-df41f900-0bcf-11ea-9da1-e4a1ac05ca12.png)

**Comment by mjbvz** [comment]
VS code’s markdown preview does not normally have a white background (unless your normal code editors do too) 

What theme are you using?

**Comment by rfresow** [comment]
Just tested the code on my home computer and there it's rendered perfect. So it seems that there is something corrupt on my work computer. This issue isn't a issue anymore :-)
