### ISSUE TITLE
Replace All should run search if no search ran before

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8518]
Testing #8184.
 
- VSCode Version: Insider 6/29
- OS Version: Windows 10

Steps to Reproduce:

1.  " View: Show Search"
2.  Expand Replace field
3.  Enter a search string
4.  Tab to replace field
5.  Enter a replace string (or keep it empty)
6.  Tab to Replace All button
7.  Press Enter

You get:
<img width="804" alt="screen shot 2016-06-29 at 9 02 11 am" src="https://cloud.githubusercontent.com/assets/4674940/16459921/ccbbccb0-3dd9-11e6-8961-1e0d6f685226.png">

**Comment by sandy081** [comment]
Fixed by #8302 and #8330
