### ISSUE TITLE
Inconsistent key binding for Go Back command (workbench.action.navigateBack) between VS on Linux, VS on Windows, VS 2019 on Windows

### ISSUE THREAD

**Issue by ironyman** [microsoft/vscode#85181]
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

1. Want to to jump cursor to previous location
2. Think about what OS you're on
3. Try a bunch of key combinations because can't remember which binding is for which OS
4. Oh it's that one
5. Sad

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by egamma** [comment]
@ironyman since number of keys that can be bound on a particular platform are limited it is therefore not possible to come up with key bindings that work across all the platforms out of the box. As a user you can always customize the keybindings.
