### ISSUE TITLE
WEB: can not open any files in vscode

### ISSUE THREAD

**Issue by MasonForFun** [microsoft/vscode#85199]
- VSCode Version:commit e82dd213dde5a1b042d6c2e65dd7bd49345c683b
- OS Version:ubuntu 16.04

Steps to Reproduce:

1. yarn
2. yarn watch
3. yarn web

The following is the screenshot.
![1](https://user-images.githubusercontent.com/54615946/69241783-7613b300-0bda-11ea-8c71-b5194d2fae9c.png)

How can I open any file in my server?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
@MasonForFun `yarn web` is only used for testing purposes and only operates on an in memory file system. It is not supported to open real files.

**Comment by vegerot** [comment]
@egamma Silly question, but why not?  Is this to incentivize getting an Azure host?
