### ISSUE TITLE
Search and replace boxes should place caret in same place

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8519]
Testing #8184.

- VSCode Version: Insiders 6/29
- OS Version: Windows

Steps to Reproduce:

1. "View: Show Search"
1. Expand Search
1. Enter search string 
1. Enter replace  string
1. Use Up and Down Arrow keys to go back and forth between the search field and the replace field

-> The search field puts the caret at the beginning of the text. The replace field puts the caret at the end of the text. They should both behave the same, preferably setting the caret at the end of the text.

**Comment by sandy081** [comment]
Instead of placing the caret, right approach is to behave similarly when navigating using Tab. This will give consistent experience.
