### ISSUE TITLE
File browser tree view

### ISSUE THREAD

**Issue by monsieursheep** [microsoft/vscode#85197]
Issue Type: <b>Feature Request</b>

Can the folders be sortable by creation or modified date in the tree view

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

**Comment by isidorn** [comment]
Yes. Please use 	`"explorer.sortOrder": "modified"` setting
