### ISSUE TITLE
FS: Can't open image from custom FileSystemProvider

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#85190]
1. Change an image in a git repo.
2. In the SCM view, right click the change and select `Open File (HEAD)` to open the original image.

Git will attempt to open a Uri which has the following `query`, all properly encoded:

```
path=%2Fhome%2Fjoao%2FWork%2Ffakeproject%2Fcode_150x150.png&ref=~
```

There will be a call to `stat` with the correct Uri, with the same `query` property:

![image](https://user-images.githubusercontent.com/22350/69228099-4a191300-0b83-11ea-8e5e-a0480b2149fc.png)

But the call to `readFile` will have a Uri with a double encoded `query` property:

![image](https://user-images.githubusercontent.com/22350/69228123-51d8b780-0b83-11ea-9049-d30cf5e4cf77.png)

```
path%3D%252Fhome%252Fjoao%252FWork%252Ffakeproject%252Fcode_150x150.png%26ref%3D~
```

**Comment by joaomoreno** [comment]
Does no repro with text files.

**Comment by bpasero** [comment]
The file service is never doing anything with the URIs it gets (neither parse nor toString()). So I suspect something is going wrong maybe here:

https://github.com/microsoft/vscode/blob/9dcd33183cd7c7057f816c013336d8b087472f80/src/vs/workbench/contrib/webview/electron-browser/webviewProtocols.ts#L19

**Comment by joaomoreno** [comment]
Works great, thanks @mjbvz !
