### ISSUE TITLE
git.autofetch on AC power only

### ISSUE THREAD

**Issue by tomaszkiewicz** [microsoft/vscode#85194]
Hi, 

I use VSCode mostly to manage infrastructure-as-a-code repositories and I have many of them opened simultaneously in one workspace. The problem starts when I use my laptop on battery as git.autofetch feature starts multiple processes that take a lot of CPU and causes quicker battery drain.

I suggest adding some additional switch that disables that behavior, when laptop is on battery power.

Best regards

Łukasz Tomaszkiewicz

**Comment by lszomoru** [comment]
With the introduction of [VS Code profiles](https://code.visualstudio.com/docs/editor/profiles) you can easily create a new profile in which you disable `git.autofetch`. 
You can then easily switch to this profile when disconnecting from AC power.
