### ISSUE TITLE
activate-power-mode

### ISSUE THREAD

**Issue by hellopao** [Microsoft/vscode#852]
shall someone port this to code?
![shake](https://cloud.githubusercontent.com/assets/688415/11440971/aadfae8e-9507-11e5-8aa0-0ecc87ca84b6.gif)

**Comment by alexandrudima** [comment]
That looks so empowering

**Comment by bpasero** [comment]
:+1:

**Comment by epinapala** [comment]
:+1:

**Comment by e-cloud** [comment]
that would be nice

**Comment by Bosee** [comment]
awesome!

**Comment by CatsMiaow** [comment]
https://github.com/codeinthedark/awesome-power-mode
:+1:

**Comment by brunoamancio** [comment]
:+1:

**Comment by chrisk8er** [comment]
cool... please make it happen.

**Comment by kyleshrader** [comment]
https://code.visualstudio.com/docs/extensions/our-approach :cry:

**Comment by mikepc** [comment]
So does this mean activate power mode will never be available on vs code?

I miss it terribly. Maybe I'll stick to atom

**Comment by willin** [comment]
+1

**Comment by ElPsyCongro** [comment]
+1

**Comment by liuliangsir** [comment]
+1

**Comment by sr229** [comment]
Welp, there's my reason to trash Atom entirely

+1

**Comment by Ulydev** [comment]
We need this.

**Comment by SeaBear622** [comment]
+1

**Comment by shirai91** [comment]
+1

**Comment by pgolebiowski** [comment]
+1

**Comment by LeoNatan** [comment]
Do it!

**Comment by cike8899** [comment]
+1

**Comment by aallbrig** [comment]
+1 This is a really fun feature to have turned on!

**Comment by Vinlow** [comment]
+1 would be awsome!

**Comment by piranha771** [comment]
+1 I want this!

**Comment by WaveHack** [comment]
+1

**Comment by LeoNatan** [comment]
@WaveHack Vitriol much?

**Comment by WaveHack** [comment]
@LeoNatan No, just sarcasm

**Comment by ajit-id** [comment]
+1

**Comment by iFun** [comment]
+1

**Comment by mijailn** [comment]
+1

**Comment by ianhatton** [comment]
+1

**Comment by bmanley91** [comment]
+1

**Comment by purezhi** [comment]
+1

**Comment by VitorLuizC** [comment]
+1

**Comment by ajitid** [comment]
Why VS Code doesn't gets fun update like fixes update on April which focused on removing bugs and give this power mode top-most priority?

**Comment by MewX** [comment]
+1 always

**Comment by ryanvgates** [comment]
+1

**Comment by SirGrapefellow** [comment]
+1

**Comment by mrmlnc** [comment]
@egamma, @bpasero, @alexandrudima, please, lock this issue ✌

**Comment by Jonatthu** [comment]
+1

**Comment by egamma** [comment]
@mrmlnc thanks for the suggestion, but we only lock issues rarely. 

What I'd like to 'lock' is that users stop using +1 and follow our [Submitting Bugs guideline](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#before-submitting-an-issue)

**Comment by brunoamancio** [comment]
@egamma Probably the +1 comments started before the "Submitting Bugs guideline" were published (not sure). We're developers, if everything until now has been "+1" in this post, the next automatically follow the pattern. Please understand. I would "lock" that if new issues are filled with "+1" since their "birth".

**Comment by sr229** [comment]
does the current state of VSCode allows such to be ported easily?

**Comment by lovealbeni** [comment]
+1

**Comment by Emeryao** [comment]
any updates? any plan?
want this feature so much for VS Code

**Comment by liuliangsir** [comment]
@Emeryao no hope

**Comment by ps1dr3x** [comment]
10/10 i cannot write code without such power

**Comment by DinoFeng** [comment]
+1

**Comment by ReFleXzZ** [comment]
+1

**Comment by bpasero** [comment]
Looks like @hoovercj makes this possible via https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-power-mode

**Comment by horvay** [comment]
Big props to hoovercj! I took a stab at extending his power mode. Not sure if hoovercj wants to add it to his own or not.. I asked him. 
https://github.com/horvay/vscode-power-mode

Check out the gif.. probably buggy as heck, though :P

**Comment by houtianze** [comment]
Not to criticize, but I found the performance of Hoover's extension isn't very impressive (I encountered perceivable typing lag with it activated). I think if VSC exposes some interfaces to allow this done "properly", it would be great.

**Comment by hoovercj** [comment]
@houtianze performance is definitely a concern with the extension. I've just pushed an update which greatly improves how the explosions look and also exposes a lot more configuration options which might be useful in tweaking the performance (and also tweaking the fun!). Thanks to @horvay for some of the ideas that led to this.

![image](https://github.com/hoovercj/vscode-power-mode/blob/7b00dab2fe01ed7eed8fc4ba8536141d314680b8/images/demo.gif?raw=true)

**Comment by houtianze** [comment]
@hoovercj Thanks for informing. After update, It indeed performs better for me now.

**Comment by liuliangsir** [comment]
[@hoovercj](https://github.com/hoovercj), could you give some example for `powermode.customCss` and `powermode.customExplosions`. By the way,  after setting `powermode.customExplosions` config like `powermode.customExplosions =
 ["http://ohupawle2.bkt.clouddn.com/vscode-update.png"]`, the original explosions disappeared and the new explosions not working

**Comment by hoovercj** [comment]
@liuliangsir I am in the process of doing that right now, actually, and I've updated the readme to say that you should use https. VS Code complains if you try to load an image from an http url and refuses to load it.

Alternatively you can base64 encode it using this site: base64-image.de

**Comment by hoovercj** [comment]
@liuliangsir I have published v1.1.0 so the above snippets should work.

**Comment by liuliangsir** [comment]
@hoovercj handsome guy 👍

**Comment by oultrox** [comment]
Awesome! only horizontal shake tho. Is there a way to implement vertical shake as well? great extension anyway! I'm using it right now.

**Comment by hoovercj** [comment]
@oultrox there is vertical shake as you can see in the gif above. I'm not sure why it isn't working for you, though. You installed my version from the marketplace?

**Comment by oultrox** [comment]
Yes I did sir! but I had to update vscode. maybe should I try re installing VScode?

**Comment by faustinoaq** [comment]
![not](https://user-images.githubusercontent.com/3067335/29202457-58bd8c4c-7e36-11e7-9c47-792ccba52c51.PNG)

![1n6rbc](https://user-images.githubusercontent.com/3067335/29202411-eefa4638-7e35-11e7-8515-09bac8fd862d.jpg)

![demo](https://user-images.githubusercontent.com/3067335/29202416-f955b7d4-7e35-11e7-9d52-6b42b4bdf36f.gif)

https://github.com/hoovercj/vscode-power-mode

😆

**Comment by crisu83** [comment]
Can't we have exactly the same experience as we're used to in Atom, without the damn 🎆 . 😞

**Comment by hoovercj** [comment]
@crisu83 

Not exactly. The Atom extension creates a canvas that it writes particle animations to. VS Code doesn't expose DOM access ([and won't for the forseeable future](https://code.visualstudio.com/docs/extensionAPI/patterns-and-principles)) so I can't do that.

What I _can_ do is replace the "firework" explosions with "particle" explosions if somebody has an appropriate gif with transparent background.

I didn't find any that looked good, so I went with the best I could find.

If you find explosions you'd like to use instead of these ones,  you can do that using this setting:

```
"powermode.customExplosions": [ "<explosion url>",  "<explosion url>",  "<explosion url>" ]
```

The **combo counter** is a similar story. I made some attempts to absolutely position some decorations on the screen but was unsuccessful. They would appear and disappear as you scrolled the first or last line off the screen. I may revisit this in the future.

**Comment by crisu83** [comment]
@hoovercj Fair enough. :) I would also suggest having a designer review the features (explosions, shake, combo counter) to ensure that the experience is the best it can be. Good job nevertheless, I just think there is still room for improvement.

**Comment by hoovercj** [comment]
I'm always open to suggestions for ways to improve it. If you or anyone else has specific feedback please open an [issue](https://github.com/hoovercj/vscode-power-mode/issues/new).

I'm also open to help! VS Code has a large community with a variety of talents. Design is not one of mine, so I already have an issue open asking for [better explosions](https://github.com/hoovercj/vscode-power-mode/issues/1).

**Comment by cfxmj2014** [comment]
looking forward

**Comment by AlekSi** [comment]
Why is this issue still open?

**Comment by hoovercj** [comment]
@crisu83 another round of improvements just went out. Hopefully this is more to your liking:

![demo-presets-particles](https://user-images.githubusercontent.com/2957173/31051948-f0b71596-a676-11e7-8430-b50c20230e59.gif)

@AlekSi I assume it is still open because people aren't satisfied with the current solution. I'm of course doing the best I can, but the combo meter still isn't possible, until today my effects weren't up to par with atom, and with limited api support the performance of my extension will always be a concern.

I do think my latest changes might be enough to close this issue, though.

**Comment by crisu83** [comment]
@hoovercj Thanks! I'll try it out as soon as I have time and get back to you.

**Comment by seanmcbreen** [comment]
I'm going to go out on a limb and now close this issue - the discussion should move to @hoovercj repo.
https://github.com/hoovercj/vscode-power-mode

I would also be remiss not to say a big thanks @hoovercj for all the work here to add Power Mode to VS Code.

Happy (Exploding) Coding
Sean
VS Code Core Team
