### ISSUE TITLE
Wrong label in Source Control: File's conext menu entry "Reveal in Explorer" has to be renamed to "Reveal in Sidebar"

### ISSUE THREAD

**Issue by JayEn84** [microsoft/vscode#85205]
- VSCode Version: 1.40.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a workspace that uses Source Control.
2. Change a file.
3. Go to Source Control (Ctrl + Shift + G).
4. Right click on the changed file.
5. If you click on "Reveal in Explorer", the file is not revealed in Explorer, but in the sidebar.

Please note that there are two context menu entries when you right click on the tab of an opened file: "Reveal in sidebar" and "Reveal in Explorer", so the naming is not consistent. In Source Control, the entry should be renamed to "Reveal in sidebar".

**Comment by joaomoreno** [comment]
Related to https://github.com/microsoft/vscode/pull/83418
