### ISSUE TITLE
VS Code hangs the Computer Performance

### ISSUE THREAD

**Issue by ranadheerreddy** [microsoft/vscode#85202]
Issue Type: <b>Bug</b>

Suddenly the VS Code hangs my entire computer and then it stays there for long time without response and this comes when I'm in my project itself particularly.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (5.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
vscode-icons|vsc|9.5.0

</details>

**Comment by egamma** [comment]
/needsMoreInfo  please follow this guide to narrow down performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues

> I'm in my project itself particularly.

What are the characteristics of this project? Can you run `code --status` to get more information and attach the output.
