### ISSUE TITLE
Ability to ignore settings to sync from UI

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#85208]
Provide a way to ignore settings from Settings editor

**Comment by roblourens** [comment]
Not sure what you are asking for?

**Comment by sandy081** [comment]
You can configure settings to be ignored while syncing using setting `sync.ignoredSettings`. This is about having an action on the setting to add or remove from this list. It would be also nice to indicate that a setting is ignored  from sync if it is/

**Comment by misolori** [comment]
This what I had in mind when we discussed this feature:

![image](https://user-images.githubusercontent.com/35271042/69555496-24f81c00-0f58-11ea-9c4e-7f82fedabf7b.png)

**Comment by roblourens** [comment]
Seems fine to me. We could talk about it in the UX call.

**Comment by misolori** [comment]
Note that we won't be having one until 2 weeks due to Thanksgiving and Endgame.

**Comment by misolori** [comment]
We did this:

![image](https://user-images.githubusercontent.com/35271042/98305204-4a6a1400-1f76-11eb-9d68-f17b9881f1ee.png)
