### ISSUE TITLE
http proxy setting isn't getting used

### ISSUE THREAD

**Issue by dingusj1** [microsoft/vscode#85207]
Issue Type: <b>Bug</b>

After taking the update to 1.40.1 I'm getting the following error:
"Problems loading reference 'http://json-schema.org/draft-04/schema#/properties/multipleOf': Unable to load schema from 'http://json-schema.org/draft-04/schema' The server did not respond with any data.

for every json file I open. Issue didn't occur prior to taking update and proxy settings haven't changed. 

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
To trace the proxy handing enable `Set Log Level...` to `Verbose` and check the Output view, tab `Log (Extension Host)`
What's strange is that `http://json-schema.org/draft-04/schema` is a schema that we bundle with the JSON language server and should never be requested.
To find out more, can you add `"json.trace.server": "verbose"` to the settings and look at the Output > JSON Language Server log if you find any reference of `draft-04`

**Comment by dingusj1** [comment]
I'm not seeing any options for a verbose log level: 
![image](https://user-images.githubusercontent.com/858694/69350202-1bfd0700-0c47-11ea-8fcc-96457c100ee7.png)

where would I find that setting? I'm looking under the command palette and "Developer: Set Log Level"

I did add the json.trace.server setting and didn't see any reference to a draft-04, there is a reference to a draft-07 though.

**Comment by aeschli** [comment]
Oh, sorry, I meant `trace`
