### ISSUE TITLE
Cutting off the error text

### ISSUE THREAD

**Issue by tarurar** [Microsoft/vscode#8520]
- VSCode Version: 1.2.1
- OS Version: OS X El Capitan

Just have a look at the screenshoy attached. You will see the cutted of error description in the top of the window.

<img width="1440" alt="screen shot 2016-06-29 at 19 55 11" src="https://cloud.githubusercontent.com/assets/142044/16460530/d43ed6f8-3e38-11e6-902b-f056983f742f.png">

**Comment by bpasero** [comment]
This is obsolete with the introduction of the new problems view.

**Comment by tarurar** [comment]
@bpasero where can I get this "new problems view"?

**Comment by bpasero** [comment]
We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by tarurar** [comment]
Got it, it works fine now.
