### ISSUE TITLE
Black screen when switch windows

### ISSUE THREAD

**Issue by RubenSalazarAurea** [microsoft/vscode#85200]
Issue Type: <b>Bug</b>

In the last version, when I switch between windows (alt+tab) and return to VSCode, it is black screen and take few seconds to refresh the screen, this issue had not been happen in previous versions, please check.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (5.07GB free)|
|Process Argv|C:\CO\support-soft-qa-automation|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
cucumberautocomplete|ale|2.14.1
ng-template|Ang|0.802.3
bracket-pair-colorizer|Coe|1.0.61
idesensor-code|Cro|1.0.1933304
php-intellisense|fel|2.3.13
code-runner|for|0.9.14
Angular2|joh|8.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
java|red|0.53.1
vscode-xml|red|0.9.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1

</details>

**Comment by IllusionMH** [comment]
Most likely it is related to #84343
Could you check if it is happening with `"window.titleBarStyle": "native"` in settings?
