### ISSUE TITLE
Git FS: needs to emit events when file is gone

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#85204]
The history listens to file events and removes entries upon delete. We need to send this from git fs when an editor is no longer valid, otherwise these stick around: 

![image](https://user-images.githubusercontent.com/900690/69244389-2b2b7880-0ba5-11ea-9b5f-0956ee1058ee.png)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/ff7e302ad6c3ce70e2546ef136b1bf3163bcdeef/src/vs/workbench/services/history/browser/history.ts#L284

**Comment by joaomoreno** [comment]
@bpasero These files are never gone, an old version of a file always exists... I'm not really sure I can do anything here.

I believe this support should come from the platform: I don't want these resources to show up in these places at all.
