### ISSUE TITLE
UX: Start Settings Sync 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#85216]
This issue is to track UX for Initial Settings Sync Set up

**Comment by sandy081** [comment]
Following gif shows how to turn on settings sync. This will ask for sign in if user has not yet signed in. If this is the first time user is turning on the sync, user will be shown a quick pick to configure what to sync. This is shown only once (first time) and later user can go to settings to tweak them.


![Kapture 2019-11-20 at 16 03 55](https://user-images.githubusercontent.com/10746682/69255327-ebba5780-0bb7-11ea-9eea-d0d4745138f4.gif)

**Comment by beastdestroyer** [comment]
@sandy081 I don't really like the fact it opens up the browser just to sign in, I think it could be done better - perhaps in-house webview of simply a combination of UI and API

**Comment by sandy081** [comment]
I think we have to open the browser for call backs. @RMacfarlane Can you please provide more details?

**Comment by RMacfarlane** [comment]
I'm not sure if it's possible or not from a webview - we don't own the login page and it has to redirect to some url on completion. In that case it would be to a protocol handler for vscode. I don't know what would happen from within a webview, if that would work at all. I can do some experimenting with it.

**Comment by shanalikhan** [comment]
@sandy081 
are you guys going to implement complete solution for Settings Sync including Backend services like Git ? (like i have used Gist in Settings Sync)

Or providing a ways for extension authors to implement their own by only limited to UI and API access.

**Comment by sandy081** [comment]
Yes, plan is to provide the end to end feature in VS Code. We are still discussing if we want to allow extensions to contribute backend provider that can store data.

**Comment by sandy081** [comment]
From @joaomoreno 

Should we really ask the user again what they want to sync, once they re-enable sync?

![image](https://user-images.githubusercontent.com/22350/70060709-54a3c580-15e3-11ea-9771-58e1469faa27.png)

Reply from @Tyriar 

I think we should keep this, turning off should happen very infrequently and one of the valid reasons for this could be to reconfigure what is synced for users less familiar with settings.

**Comment by sandy081** [comment]
Moving to December to incorporated received feedback.

**Comment by sandy081** [comment]
1. Turning on Sync

<img width="286" alt="image" src="https://user-images.githubusercontent.com/10746682/72813428-9526d380-3c63-11ea-872c-b3f1ab260b9c.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/10746682/72812609-19785700-3c62-11ea-813f-b34cb37ed3ba.png">

2. You will see following dialog If you are syncing from this machine for the first time and there is data to merge (remote and local). You can choose to replace or merge.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/10746682/72812748-5f351f80-3c62-11ea-8397-bdb9cfcd4e45.png">

3. Resolving Conflicts

<img width="868" alt="image" src="https://user-images.githubusercontent.com/10746682/72813196-3f522b80-3c63-11ea-8531-cf70605a6121.png">

Clicking on `Show Conflicts` opens a diff editor as follows:

<img width="1278" alt="Screenshot 2020-01-21 at 14 34 39" src="https://user-images.githubusercontent.com/10746682/72813321-6c9ed980-3c63-11ea-99cd-e8b72b17943f.png">

4. Turn Off:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/10746682/72813509-ba1b4680-3c63-11ea-9307-9918592065b7.png">

You can turn off only on this machine or completely using following dialog

<img width="509" alt="image" src="https://user-images.githubusercontent.com/10746682/72813012-e6829300-3c62-11ea-8a5e-86d4a78496d6.png">

**Comment by Tyriar** [comment]
Feedback on flow: https://github.com/microsoft/vscode/issues/89046, https://github.com/microsoft/vscode/issues/89047, https://github.com/microsoft/vscode/issues/89049
