### ISSUE TITLE
Allow debuggers to support StepBack without ReverseContinue

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#85215]
The "ReverseContinue" action is controlled by the same `supportsStepBack` flag that "StepBack" is. This means for any debugger than can support step back, but not reverse continue, there will be an extra button on the debug toolbar that won't function.

![Screenshot 2019-11-20 at 3 02 29 pm](https://user-images.githubusercontent.com/1078012/69250012-cbce6800-0ba6-11ea-85d9-0ba8ed8a0b47.png)

**Comment by weinand** [comment]
Adding a new capability or changing the existing ones in a m^backward compatible way would be a mess.
No plans to do this.

**Comment by DanTup** [comment]
I forgot to post back here - I was actually using the wrong thing here anyway (I was implementing RestartFrame). It's done correctly now so I'm not using this now :-)
