### ISSUE TITLE
[php] Syntax highlighting of SQL query strings missing when concatenated

### ISSUE THREAD

**Issue by JayEn84** [microsoft/vscode#85213]
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.2.0
apacheconf-snippets|eim|1.3.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
githd|hui|2.1.0
smarty|imp|0.3.0
vscode-apache|mrm|1.2.0
es6-css-minify|olb|3.3.1
phpdoc-comment-vscode-plugin|rex|1.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.0.0
pdf|tom|0.5.1

</details>
Steps to Reproduce:

Create or open a PHP file and create an SQL string with a concatenation:
![vscode_sql_bug](https://user-images.githubusercontent.com/4518738/69248968-79447a00-0bad-11ea-863f-8ed1034d7898.png)

The word `WHERE` should be blue in the second string. No more syntax highlighting happens after the string was concatenated.

**Comment by alexr00** [comment]
@JayEn84 can you provide a full example that can be copy+pasted?

**Comment by JayEn84** [comment]
Sure, I have created the following example:

```
<?php

// Example of missing SQL syntax highlighting in PHP code in VS Code:

$additionalColumns = "firstsurname";
$tblsurname = "testTbl";

// this first example contains no concatenation -> works well
$sql1 = "   SELECT id, surname
            FROM testTbl
            WHERE id > 5";

// the following two examples lack SQL syntax highlighting after the (first) concatenation
$sql2 = "   SELECT id, surname, " . $additionalColumns . "
            FROM testTbl
            WHERE id > 5";

$sql3 = "   SELECT id, surname
            FROM " . $tblname . "
            WHERE id > 5";
```

This is what it looks like in my VS Code. The arrows point to the words that _should_ be highlighted in blue color:
![grafik](https://user-images.githubusercontent.com/4518738/69623498-4bdf4c80-1043-11ea-8413-685a05aabf60.png)

**Comment by itsopen** [comment]
I have another example here (see list of extensions installed at the bottom).

This code work perfectly, and is formatted correctly in Netbeans (see image below).

Vscode image example:

![image](https://user-images.githubusercontent.com/15907315/69722067-1d7a7380-110e-11ea-8df5-83989f00fc3d.png)


Netbeans image example:

![image](https://user-images.githubusercontent.com/15907315/69722231-8104a100-110e-11ea-89c5-cabaa505e2a5.png)


Copy and paste example:
```
<?php

$LABEL = "Update default date format";
$NOTES = "see label ... ".$LABEL;

$lang_code_strings = ['es_ES', 'it_IT', 'sk_SK', 'sv_SE', 'TL_tl', 'en_GB', 'da_DK', 'fr_FR', 'cy_GB', 'pt_PT'];

foreach ($lang_code_strings as $lang_code) {
	$query = "UPDATE `test`
		SET `date_format_$lang_code` = 'l, j".($lang_code == 'en_GB' ? 'S' : '')." F Y \\\\a\\\\t g:ia' 
		WHERE `date_format_$lang_code` = 'D, j\\\<\\\s\\\u\\\p\\\>S\\\<\\\/\\\s\\\u\\\p\\\> M Y - g:i a'; ";

	if ($this->db->query($query) === FALSE ) {
		$ERROR = $LABEL."- fail query (".$lang_code.") (".$query.")";
		return;
	}
}
```
```
code --install-extension Kasik96.format-indent
code --install-extension RoscoP.ActiveFileInStatusBar
code --install-extension SimoneOlivieri.visual-studio-light-theme
code --install-extension SirTori.indenticator
code --install-extension aaron-bond.better-comments
code --install-extension akamud.vscode-theme-onelight
code --install-extension Anjali.clipboard-history
code --install-extension anoff.theme-monokai-light
code --install-extension anseki.vscode-color
code --install-extension b4456609.theme-atom-one-light
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bubersson.theme-hop-light
code --install-extension carbonodev.search-vendor
code --install-extension cxfksword.goto-documentation
code --install-extension cyansprite.smoothscroll
code --install-extension dbaeumer.vscode-eslint
code --install-extension drKnoxy.eslint-disable-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension Equinusocio.vsc-material-theme
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension FerrierBenjamin.fold-unfold-all-icone
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension gerane.Theme-Dreamweaver
code --install-extension gerane.Theme-earthsong-light
code --install-extension gerane.Theme-FocusLight
code --install-extension gerane.Theme-snappy-light
code --install-extension humao.rest-client
code --install-extension ikappas.phpcs
code --install-extension jasen.theme-coda
code --install-extension karsany.vscode-ideal-theme
code --install-extension linking.evo-theme
code --install-extension lkytal.FlatUI
code --install-extension ms-vscode.csharp
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msnilshartmann.blue-light
code --install-extension mtxr.sqltools
code --install-extension nanlei.save-all
code --install-extension neilbrayfield.php-docblocker
code --install-extension obrejla.netbeans-light-theme
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension rebornix.toggle
code --install-extension ryu1kn.annotator
code --install-extension sapegin.Theme-SquirrelsongLight
code --install-extension shardulm94.trailing-spaces
code --install-extension slevesque.shader
code --install-extension small.php-ci
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension tomphilbin.lodash-snippets
code --install-extension ullissescastro.theme-bracketslight
code --install-extension vincaslt.highlight-matching-tag
code --install-extension waderyan.gitblame
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xyz.local-history
code --install-extension zenzz.theme-zxx
```

**Comment by alexr00** [comment]
I can repro, thank you for the clear examples! This looks like https://github.com/atom/language-php/issues/336 and https://github.com/atom/language-php/issues/333

It might be worth up-voting https://github.com/atom/language-php/issues/333 and asking that sql in php just be treated as a string.

**Comment by itsopen** [comment]
My pleasure.

I'm a little confused, is Vscode based on Atom?

**Comment by alexr00** [comment]
We get some of our grammar files (used for syntax highlighting) from atom language repositories 😊

**Comment by itsopen** [comment]
Ok thanks.

I upvoted (added a thumbs up) to the original (first) issue on that thread. Hopefully that's enough ... 

This feels fairly critical, as I use PHP in my daily work as I'm sure many other people do, for SQL as well as various other string related functions.
