### ISSUE TITLE
python venv debugger session timed out

### ISSUE THREAD

**Issue by sharondescalo** [microsoft/vscode#85214]
- VSCode Version:1.40.1
- OS Version:Windows_NT x64 10.0.17763

Steps to Reproduce:

1.install python 3.72
2.run py -3 -m venv .venv on working directory
3. run .venv\scripts\activate
4. try run vs code debugger

![image](https://user-images.githubusercontent.com/1915885/69249878-51f2aa80-0bb7-11ea-97dd-2c89d769d5ef.png)

![image](https://user-images.githubusercontent.com/1915885/69249797-2c65a100-0bb7-11ea-97ba-4a568e0e166d.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
Please file the issue against the python extension.
