### ISSUE TITLE
Settings sync server query strategy

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85210]
Currently I think the settings sync server is pinged every n seconds to fetch the latest values, while this is fine for development we need to reduce that significantly for production. @kieferrm and I were talking about it and we're thinking something like this:

- Ping every 5-10 minutes
- Special events (debounced)
  - The VS Code application gets focus (eg. alt+tab from a browser)
  - A new VS Code window is opened?
  - Settings is opened

**Comment by sandy081** [comment]
Updated the auto sync strategy as follows:

- Changes the auto sync interval to 5 minutes
- Sync is triggered when
  - a new window is opened
  - window is foucsed
  - Opening settings/keybindings/extensions view
