### ISSUE TITLE
Select all occurrences and cursor position while wrapping is on

### ISSUE THREAD

**Issue by mladen-dordevic** [microsoft/vscode#85220]
Issue Type: <b>Bug</b>

1. Have the Word Wrap on
2. Enter long string that will break in multiple lines eg: 
long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string&long_string& 
3. Select all occurrences of & as that is where the line will wrap
4. Press the left arrow key on the keyboard
Expected Outcome: Multiple cursors located in front of the &
Observed Outcome: Cursors that are located at the right margin where wrapping occurs will be in front of letter g instead of &

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.0
ng-template|Ang|0.802.3
ngx-translate-lookup|apk|1.2.0
vscode-intelephense-client|bme|1.2.3
npm-intellisense|chr|1.3.0
angular2-snippets|dan|1.0.21
githistory|don|0.4.6
vsc-material-theme|Equ|30.0.0
php-intellisense|fel|2.3.13
vscode-ionic-snippets|fiv|1.8.0
php-cs-fixer|jun|0.1.127
vscode-commitizen|Kni|0.8.4
graphql-for-vscode|kum|1.15.3
restructuredtext|lex|116.0.0
markdown-formatter|mer|0.7.6
vscode-language-babel|mgm|0.0.25
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
python|ms-|2019.11.49689
Go|ms-|0.11.9
debugger-for-chrome|msj|4.12.1
ngx-translate-quickcreate|nex|1.0.1
vetur|oct|0.22.6
vscode-manifest-yaml|Piv|1.12.0
code-spell-checker|str|1.7.20

</details>

**Comment by alexandrudima** [comment]
Let's track in #65815
