### ISSUE TITLE
Can't do ctrl+arrow left/rigth to do whole string selection when the Language Mode is Markdown

### ISSUE THREAD

**Issue by tifDev** [microsoft/vscode#85221]
- VSCode Version: 1.40.1 (user setup)
- Commit: 8795a9889db74563ddd43eb0a897a2384129a619
- Date: 2019-11-13T16:49:35.976Z
- Electron: 6.1.2
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS Version: Windows 10

Steps to Reproduce:

1. Change Language Mode to Markdown
2. Try select some text with ctrl+arrow left/rigth

**Comment by mjbvz** [comment]
Please explain exactly what isn't working
