### ISSUE TITLE
Test: Allow Ctrl+S to save a dirty file of a peek editor when it has focus

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#85225]
Refs: https://github.com/microsoft/vscode/issues/38317

- [x] anyOS @deepak1556
- [x] anyOS @weinand

Complexity: 2

* turn auto save off
* bring up a peek editor (alt F12) and type into it
* verify that you can save it e.g. via `CtrlCmd+S` as long as focus is inside the peek editor
* file issues if you get confused at one point about that experience

**Note:** it is currently "as designed" that the peeked editor opens as a separate tab once you start editing it because the peek editor itself does not participate in the dirty editor experience (e.g. you are not getting asked to save the file when you close the peek editor that is dirty).

**Comment by weinand** [comment]
I like the behavior since it is very intuitive.
