### ISSUE TITLE
"Automatically update imports" edits other file, but should also save it

### ISSUE THREAD

**Issue by birgersp** [microsoft/vscode#85227]
(EDIT: Temporary workaround is to use "save all")

- VSCode Version: 1.40.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a (export) class named "MyClass.ts": `export class MyClass {}`
2. Import the class in some other file: `import {MyClass} from "./Myclass"`
3. Rename "MyClass.ts" to "MyRenamedClass.ts"
4. Observe how the file name changed in the source file from step 2, but the save is not changed

When the step2 file has some unsaved changes already, this makes sense. But when the file has no unsaved changes, the automatic update of imports should also save the file. This is the behavior I am used to coming from IntelliJ, NetBeans, Visual Studio.

**Comment by mjbvz** [comment]
Similar to #47573

Not a good default at the moment though since our undo/redo only works at the individual file level

**Comment by birgersp** [comment]
> undo/redo only works at the individual file level

I don't see that as a problem blocking this feature.

The files updated during the rename should be saved only if they have unsaved changes in the first place.

Consider the following example:

- The user opens file **A** and make some changes in VSCode. The changes are not saved, the file remains open in VSCode.
- File **A** has a reference to file **B**:
```import { SomeClass } from "file_B.ts"```
- The user renames file **B**.
- File **A** gets updated but remains unsaved because it had unsaved changes before the rename.
- If the user had saved the changes in the first step, then file **A** would have been updated and saved.

This is the same behaviour as in the other IDEs I mentioned.

**Comment by mjbvz** [comment]
* I move a file and opt to update imports
* It messes up a bunch of imports in an unexpected way. Now I want to revert things.
* Today, I can simply close all the files it edited to get back to the previous state
* If we saved automatically, we'd get rid of this escape hatch

 (again, ideally undo/redo would be multifile aware but it isn't)

**Comment by numfin** [comment]
does anyone else have friends? I have only 4 friends-coders to ask :D
