### ISSUE TITLE
Debug Session Timed out while using virtual env. with  python

### ISSUE THREAD

**Issue by sharondescalo** [microsoft/vscode#85228]
- VSCode Version:1.40.1
- OS Version:Windows_NT x64 10.0.17763

Steps to Reproduce:

1. penv install 3.7.2
2. py -3 -m venv .venv
3 .venv\scripts\activate
4. run debugger - 

![image](https://user-images.githubusercontent.com/1915885/69264091-4c08c380-0bcf-11ea-8e2a-9aa56e16d793.png)
![image](https://user-images.githubusercontent.com/1915885/69264135-62af1a80-0bcf-11ea-84b7-2ac2edafa3a5.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by egamma** [comment]
Please file the issue against the python extension
