### ISSUE TITLE
The variable X is assigned but never used.PSScriptAnalyzer(PSUseDeclaredVarsMoreThanAssignments)

### ISSUE THREAD

**Issue by chosebin** [microsoft/vscode#85224]
- VSCode Version: 1.36.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1.Create function
function test
{
    $Something = $Null
    $SomeArray = @("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z")
    Get-Random $SomeArray -count 50 | ForEach-Object{[string]$Something += $_}
    return $Something
}

You will get:
The variable 'Something' is assigned but never used.PSScriptAnalyzer(PSUseDeclaredVarsMoreThanAssignments) but the function does return the value

**Comment by egamma** [comment]
Please file the issue against the Powershell extension.
