### ISSUE TITLE
Test: Allow to edit the left hand side of a diff editor if possible

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#85226]
Refs: https://github.com/microsoft/vscode/issues/4180

- [X ] anyOS @eamodio 
- [x] anyOS @alexandrudima 

Complexity: 2

* turn auto save off
* bring up a diff editor with editable left hand side (e.g. compare 2 files from explorer, or Search & Replace preview from search viewlet)
* verify you can make changes on the left and right hand side
* verify that you can save both sides e.g. via `CtrlCmd+S`
* verify you cannot type into a readonly diff editor (e.g. from SCM view)
* file issues if you get confused at one point about that experience

**Note:** it is currently "as designed" that the left hand editor opens as a separate tab once you start editing it because the left hand editor itself does not participate in the dirty editor experience (e.g. you are not getting asked to save 2 files when you close the diff editor and have made changes to both sides).

**Comment by eamodio** [comment]
Looks good -- tested on Windows

**Comment by moshfeu** [comment]
It's open the left file in a new editor tab. I'm not sure that this is the optimal UX.

![video1](https://user-images.githubusercontent.com/3723951/71320132-cae36b80-24af-11ea-9827-de31a6ff7f88.gif)

**Comment by bpasero** [comment]
As designed, otherwise we would need to show a combined save dialog when you close the editor and both sides are dirty. This solution is a good balance to keep as much of the expected behaviour as possible.
