### ISSUE TITLE
Tab under dragged tab flickers

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8523]
Test item #7852 

- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 3.13.0-34-generic

Steps to Reproduce:

1. Enable showTabs
2. Open two files
3. Drag tab of first file towards the right and left
4. -> The tabs under the mouse flicker

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7948
