### ISSUE TITLE
Add a(n easily findable?) way to disable the popup that shows 'find definition' (Peek Definition?)

### ISSUE THREAD

**Issue by Murtaya** [microsoft/vscode#85233]
Issue Type: <b>Feature Request</b>

Is there a way to disable Peek Definitions?  I assume that's what the popup is called that shows when I search for definition, get taken to the file, and then pops up in front of what I actually want to look at.  It REALLY does not help me view the definition (maybe my brain just doesn't work that way), and only gets in the way.  I couldn't find any way to turn it off in settings or on the peek definition itself.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jrieken** [comment]
Yes, there is there `editor.gotoLocation.multiple` (which will be replaced in 1.41 with `editor.gotoLocation.multiple[Definition|Declarations|...]`) Given that you are using 1.31.0 you likely don't any of those options and therefore no luck in finding them.
