### ISSUE TITLE
Reveal in Side Bar from OPEN EDITORS view

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#85238]
Currently you can "Reveal in Side Bar" **only** from editor tabs. In **OPEN EDITORS** view there's only "Reveal in Finder" and "Reveal in Side Bar" is missing.

**Comment by isidorn** [comment]
This is a fair feature request however we do not plan to address it in the immediate future. So assigning to Backlog Candidates.

**Comment by svipas** [comment]
@isidorn Maybe I can create a PR?

**Comment by isidorn** [comment]
Thanks for the offer, however we are not currently sure we want this feature in our product and due to that it is assigned to the Backlog Candidates milestone. More details about our process can be found here https://github.com/microsoft/vscode/wiki/Issues-Triaging

**Comment by svipas** [comment]
@isidorn no problem, thanks for letting me know

**Comment by gjsjohnmurray** [comment]
@svipas as long as you have `"explorer.autoReveal": true` (the default) merely clicking on an item in Open Editors should reveal it in Explorer as well as showing the contents of the open file.
