### ISSUE TITLE
Whitespace is auto trimmed despite being disabled

### ISSUE THREAD

**Issue by AvengingSyndrome** [microsoft/vscode#85236]
Issue Type: <b>Bug</b>

Save a file with whitespace at the end of a line. It will be trimmed regardless of your trim settings. Noticed in the git compare view. When trying to undo the changes it still redid the whitespace changes. I can't use vscode with this issue as code reviews will be blocked on these whitespace changes.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (8.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.32.0
EditorConfig|Edi|0.14.2
vscode-nmake-tools|Mic|2.0.191118006
python|ms-|2019.11.49689
remote-wsl|ms-|0.40.3
cpptools|ms-|0.26.1
csharp|ms-|1.21.7
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
rewrap|stk|1.9.1
spellchecker|swy|1.2.13
vscode-arduino|vsc|0.2.28

</details>

**Comment by gjsjohnmurray** [comment]
Did you reproduce this with all extensions disabled, so as to rule out it being caused by one or more of them?
