### ISSUE TITLE
Allow to keep preview for Git modified files even if enablePreview is false

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#85237]
I like to use `"workbench.editor.enablePreview": true,`, but the problem is if I have a lot of modified Git files when I'm reviewing changes all these files are opened. I suggest to keep enabled preview for Git modified files if `enablePreview` is `false`. This feature is really useful if you want to keep track of files you have opened via Go To Definition, etc., but with every Git modified file being opened which shows diffs makes it unusable...

**Comment by svipas** [comment]
If it's unclear what I wanted to say is I want to disable preview which means files are always opened and you don't need to double-click on them for everything **except** for Git modified files changes `filename.ext (Working Tree)` which are opened via SCM by looking through diff. The reason is this feature is useful, but when you're opening a lot of Git files to see diff's, etc. you end up with a lot of opened files.

**Comment by joaomoreno** [comment]
I have renamed the title from:

> Enable preview for Git modified files even if enablePreview is true

to

> Allow to keep preview for Git modified files even if enablePreview is false

**Comment by joaomoreno** [comment]
I suggest to simply have a `git.enablePreview` setting or similar.

**Comment by svipas** [comment]
@joaomoreno good idea, maybe I can create the PR?

**Comment by joaomoreno** [comment]
Yes sir!

**Comment by svipas** [comment]
What I understand is you can't have these two:

```
  "workbench.editor.enablePreview": false,
  "workbench.editor.enablePreviewFromQuickOpen": true,
```

If `workbench.editor.enablePreview` is `false` having `workbench.editor.enablePreviewFromQuickOpen` set to `true` will not work. So my feature request will not work as expected...

**Comment by joaomoreno** [comment]
Got it, gotta have @bpasero in this.

**Comment by bpasero** [comment]
Yeah setting is not ideal. The one is the global switch and the other does not work if the global switch is off. A better setting would probably be some enumeration where you can list the things to enable.

**Comment by danielo515** [comment]
I was about to open a new issue entitled `Separated enablePreview for git diff and normal files` which I think is what you are looking for.
Please, all the people interested in this feature, upvote it!
