### ISSUE TITLE
Edge of window not rendering when maximized with custom title bar

### ISSUE THREAD

**Issue by parsehex** [microsoft/vscode#85246]
Issue Type: <b>Bug</b>

When using 'custom' title bar and the window is maximized, portions of the edge of the window aren't rendered and whatever is under the window is visible. The invisible parts aren't always the same, sometimes only one of the edges fail to render. Buttons and things work like normal under the invisible parts.

Reloading with extensions disabled doesn't fix it and the issue is seen on the Insiders build. It doesn't happen if the window is fullscreen or if the native title bar is used. I also don't see it in v1.39.2

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.19028

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3380M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

![vscode](https://user-images.githubusercontent.com/1779937/69281563-7a2dd980-0bb6-11ea-9a61-721e2f054ead.PNG)

**Comment by GoaLitiuM** [comment]
I have this same exact issue in Windows 10 Insider Build 10925 (I just upgraded from 10913 which was working fine) but only when I have hardware acceleration disabled.

**Comment by GoaLitiuM** [comment]
(Off-topic but the bug report tool does not seem to include the content of recently added argv.json where I had the ``disable-hardware-acceleration`` option set to false)

**Comment by sbatten** [comment]
@GoaLitiuM, thanks I filed https://github.com/microsoft/vscode/issues/85419 with your additional comment.

**Comment by sbatten** [comment]
I am not seeing this issue on Windows 10 1909 release, possibly windows insiders specific.

**Comment by deepak1556** [comment]
@parsehex which insiders version did you try ? Can you update and try the latest version that has commit 599c076d91be1374cf51004cec610f3bcaf4c9cd

**Comment by parsehex** [comment]
Updating to the latest Insiders fixed it. The version I had originally was bd8425fa9b6427dca51e882d39b9ae764c55e08c but I also saw it in the standard install of 1.40.1 so it doesn't seem specific to Insiders.

I see Electron went from 6.1.4 to 6.1.5 between updates so maybe that fixed it

**Comment by deepak1556** [comment]
Yup we made some fixes for custom titlebar in 6.1.5, closing this as fixed then. Thanks for confirming.
