### ISSUE TITLE
Text selected in editor while dragging debug toolbar

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8524]
Test item #7815 

- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:07:11.483Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Enable showTabs
2. Open two files side-by-side
3. Start debugging
4. Drag the debugging toolbar left and right with the mouse passing over the editor tabs
5. -> Sometimes all text in the left editor is selected and then deselected again

**Comment by alexandrudima** [comment]
@isidorn Do you call e.preventDefault() ?

**Comment by isidorn** [comment]
@alexandrudima no, let me do that - thanks!

**Comment by sandy081** [comment]
Looks like not yet part of the build. So untagging

**Comment by isidorn** [comment]
Yes - this was just fixed 8 hours ago and we did not have an update yet - tomorrow morning should be good.
