### ISSUE TITLE
Powershell Else formatting

### ISSUE THREAD

**Issue by skadlec72** [microsoft/vscode#85241]
Issue Type: <b>Bug</b>

The following code executes without issue:
                if ($null -eq $LabsToProcess -or $selection -eq "Exit") {
                    Write-Host 'Nothing to process'
                } Else {
however if you right click and format document it changes the format to:
                if ($null -eq $LabsToProcess -or $selection -eq "Exit") {
                    Write-Host 'Nothing to process'
                }
                Else {
which results in:
Else : The term 'Else' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.19028

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
armsnippet|art|0.7.0
azure-arm-template-helper|ed-|0.0.17
azure-storage-explorer|for|0.1.2
prettify-json|moh|0.0.3
vscode-azurefunctions|ms-|0.20.0
vscode-azurestorage|ms-|0.7.2
mssql|ms-|1.7.1
azure-account|ms-|0.8.7
powershell|ms-|2019.11.0
azurerm-vscode-tools|msa|0.8.2
arm-snippets|sam|1.4.19
json-schema-validator|tbe|0.1.0
arm-params-generator|wil|0.8.1
armviz|yte|0.0.9

(13 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Please file the issue against the powershell extension.
