### ISSUE TITLE
Source control always expands all tree nodes, won't remember collapse in same session

### ISSUE THREAD

**Issue by Dean-NC** [microsoft/vscode#85247]
- VSCode Version: 1.40
- OS Version: Win 10 18362.418

Steps to Reproduce:

1. Open a folder/project that has some file changes in a github repo
2. Open Source-control view/panel, and collapse all tree nodes
3. Switch to any other view/panel (explorer, debug, etc.)
4. Switch back to Source-control view, and now all nodes are expanded again (it didn't remember that you collapsed some nodes).

Does this issue occur when all extensions are disabled?: Yes

For projects where you've changed several files, and where the projects has a "dist" folder that has a ton of files that automatically get changed because of a build process, this is very frustrating. It seems this view should just remember the expanded/collapsed nodes for the current session.

**Comment by joaomoreno** [comment]
This is already fixed in `master`.

**Comment by Dean-NC** [comment]
@joaomoreno What's the issue # of the duplicate?  I can't find it.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82346

Just use the [insider release](https://code.visualstudio.com/insiders) next time you want to check whether it's already fixed in `master`.
