### ISSUE TITLE
TypeError in NodeDebugAdapter while debugging

### ISSUE THREAD

**Issue by rbuckton** [microsoft/vscode#85245]
Version: 1.41.0-insider (user setup)
Commit: 213bdddb72ff7a6c8eed071420de8ddac4293cb1
Date: 2019-11-11T05:40:31.150Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Debugging a TypeScript compiler test
2. Stepped into `emitSourceFileOrBundle` function, execution pointer is in source-mapped entry for a parameter destructuring:
    ![image](https://user-images.githubusercontent.com/3902892/69280447-44c7c280-0b9b-11ea-802e-d9bece6b16fa.png)
3. After stepping through the current position, a delay occurred and the following message was printed in Debug Console:

```
C:\Program Files\nodejs\node.exe --nolazy --inspect-brk=4039 node_modules\mocha\bin\_mocha --no-timeouts --colors -g abstractProperty C:\dev\TypeScript-buddy/built/local/run.js
Debugger listening on ws://127.0.0.1:4039/683b3200-cb68-4c00-b30a-eec159fcc5ab
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

  compiler tests
    compiler tests for tests/cases/compiler/abstractProperty.ts
Error processing "variables": TypeError: Cannot destructure property `variables` of 'undefined' or 'null'.
    at NodeDebugAdapter.<anonymous> (c:\Users\rbuckton\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1167:19)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\rbuckton\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:7:58)
```

Local Node Version is v10.17.0

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Just fixed in https://github.com/microsoft/vscode-chrome-debug-core/issues/535 but I'd appreciate a log if you see it again. I tried to repro it the same way that you did and couldn't.
