### ISSUE TITLE
Web: Firefox support

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#85252]
This is a meta issue for our Firefox support in Web ([issue list](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afirefox)) and this can be used to track the limitations and gaps we currently see today on Firefox.

Currently we have two **major blockers**: Full Keybindings Support and PWA.

* Keybindings. Firefox **doesn't** allow web applications to override some of its predefined keybindings by any means, no matter if it's a in full screen mode. It means basic keyboard shortcuts like `Ctrl/Cmd+N` to create new file, `Ctrl/Cmd+W` to close current file don't work. The experience can be improved only when one of followings upstream issues are resolved
  * Override keyboard shortcuts in full screen. [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1593883)
  * `keyboard.lock` [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=700123)
  * PWA support Usually in PWA desktop mode, you can have full keybinding support [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1407202)
* PWA. Only with this, users can save Web to desktop or taskbar for quick access, and potentially full keybindings support

Besides, we have some *nice-to-haves*:

1. Clipboard read support. Currently web applications are only allowed to read clipboard in user-initiated event callbacks. It means we can't have customized keybindings or context menu entries for Paste command. https://github.com/microsoft/vscode/issues/84084
2. Unicode support for regex. We adopted Unicode mode in language definitions, find/search, etc already but Firefox is lacking support for it. [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1361876), https://github.com/microsoft/vscode/issues/83698

**Comment by rebornix** [comment]
Move this item to backlog as there are blockers that we want to track.

**Comment by miketaylr** [comment]
>     2\. Unicode support for regex. We adopted Unicode mode in language definitions, find/search, etc already but Firefox is lacking support for it. [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1361876), #83698

This should be fixed as of yesterday (in 78+: https://bugzilla.mozilla.org/show_bug.cgi?id=1361876#c21)

**Comment by digitarald** [comment]
@miketaylr and I can help from the Firefox side to find the right bugs, people and input. Feel free to cc us on similar bugs.

**Comment by rebornix** [comment]
@miketaylr @digitarald thanks for your help, I'll give it a try and do another round of accessment. For now the major blockers for us dogfood running VS Code in Firefox IMHO is still keybindings in Full Screen (https://bugzilla.mozilla.org/show_bug.cgi?id=1593883, or https://bugzilla.mozilla.org/show_bug.cgi?id=700123) and PWA (https://bugzilla.mozilla.org/show_bug.cgi?id=1407202). I can also share more details about the keybindings part if you are interested.

**Comment by digitarald** [comment]
@rebornix I can see fullscreen being important for workflows as it allows full keyboard access.

Regarding PWA and to understand how it blocks you: Do you have any insights if users are adding VS Code as installed web app? Is that something that Codespaces encourages users?

**Comment by bpasero** [comment]
> Is that something that Codespaces encourages users?

This is currently not yet supported but planned for: https://github.com/MicrosoftDocs/vsonline/issues/43

Nevertheless, in Edge for example I can save a Codespace as "App" even without official PWA support: https://twitter.com/BenjaminPasero/status/1258650064538480640

**Comment by rebornix** [comment]
@digitarald we see PWA as an environment for VS Online / Codespace users to embrace a similar desktop like experience as VS Code Desktop. For example, in PWA, users should be able to use `CMD+Q` to quit just the Codespace where in norma browser mode (no matter it's full screen or not), `CMD+Q` will quit the whole application.

**Comment by digitarald** [comment]
> @digitarald we see PWA as an environment for VS Online / Codespace users to embrace a similar desktop like experience as VS Code Desktop.

I understand the added value of PWA for this project with the additional keyboard access it provides, @rebornix. We will continue to make a case for it, listing your use cases.

But is the absence of PWA support in Firefox a strong enough reason to _block_ Firefox for online.visualstudio.com, Codespaces and co?

**Comment by kieferrm** [comment]
@digitarald FF is not blocked, it's only an info to the user. On GH Codespaces, the user can dismiss the info. This is not possible on VS Codespaces which is an oversight.
