### ISSUE TITLE
Pseudoterminal misses synchronous output in CustomExecution-based Task

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode#85257]
- VSCode Version: 1.40.1
- OS Version: Darwin x64 19.0.0

A `CustomExecution`-based task returns a `Pseudoterminal` when executed.  The `Pseudoterminal` starts the actual work when its `open()` method is called.  My understanding is that the `Pseudoterminal` indicates the task is complete by firing its `onDidClose` event.  Output written through the `Pseudoterminal` is buffered by VS Code (i.e. [looking at the code](https://github.com/microsoft/vscode/blob/5367bf6d2bbd48b4aa1ff20158c927e11f678364/src/vs/workbench/contrib/terminal/common/terminalDataBuffering.ts#L23), it uses a 5ms timeout before passing on any accumulated content to the renderer).

If the task is effectively synchronous (or just portions, thereof?), output written through the terminal will not be rendered, because the `Pseudoterminal` immediately fires the `onDidClose` event, which causes the buffer to cancel the timer, and the accumulated content is never passed onto the renderer.  At least in the case of `CustomExecution`, it seems like the `Pseudoterminal` buffered content should be "flushed" to the renderer when `onDidClose` is fired.  (I'll admit, from an API perspective, that seems weird because the terminal is being "closed", but that's because "closure" is being effectively used for "done" in this scenario.)

If needed, I can try to extract a minimal repro from the prototyping I was doing.

**Comment by Tyriar** [comment]
FYI @eamodio an edge case we missed; buffered data doesn't get flushed before Pseudoterminal.onDidClose fires.
