### ISSUE TITLE
Cursor goes missing when pressing up in vi running in vscode terminal

### ISSUE THREAD

**Issue by monkeygroover** [microsoft/vscode#85250]
Issue Type: <b>Bug</b>

Yeah, bit weird, but this is happening on both my MacBook and Ubuntu 18.04 machines, and both started after the last update.

Repro, open a file in vi in the vscode terminal, navigate with down arrow (all fine) but then press up and the cursor insert point vanishes!?  press down again and it reappears.

Anyone else seen this?

cheers

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|-psn_0_408315214|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
calva|bet|2.0.61
clj-kondo|bor|0.0.9
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.0
LogFileHighlighter|emi|2.6.0
graphviz-markdown-preview|gee|0.0.8
elixir-ls|Jak|0.2.25
vscode-squirrel-lang|mon|0.0.14
vscode-docker|ms-|0.8.2
cpptools|ms-|0.26.1
erlang|pgo|0.5.2
rust|rus|0.7.0
language-j|tik|0.4.0
shellcheck|tim|0.8.1
org-mode|too|0.5.0
vscode-lldb|vad|1.4.0

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/84299

Still need good repro steps for it so any help over there would be appreciated
