### ISSUE TITLE
execvp(3) failed.: No such file or directory when trying to build/debug using tasks

### ISSUE THREAD

**Issue by realdanielbyrne** [microsoft/vscode#85251]
Error:

     Executing task: dotnet build /Users/daniel/GitHub/em-net30/em-net30/em-net30.csproj 
     /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

     execvp(3) failed.: No such file or directory
     The terminal process terminated with exit code: 1

VSCode Version:

     Version: 1.40.1
     Commit: 8795a9889db74563ddd43eb0a897a2384129a619
     Date: 2019-11-13T16:47:44.719Z
     Electron: 6.1.2
     Chrome: 76.0.3809.146
     Node.js: 12.4.0
     V8: 7.6.303.31-electron.0
     OS: Darwin x64 19.0.0

OS Version:
     macOS Catalina Version 10.15.1

Steps to Reproduce:

1. Open .netcore project
2. press f5, or select task from debug dropdown and press play button.

- Building from command line works fine. 
- Building and debugging using Visual Studio (Mac) works fine as well.  

This issue was apparently raised earlier (last year) and since closed.  However it apparently has resurfaced.  Here is the link to the previously closed issue with the same error code.
https://github.com/Microsoft/vscode/issues/63104

**Comment by egamma** [comment]
please file the issue against the C# extension

**Comment by realdanielbyrne** [comment]
Any proof to that statement?  When I disabled the extension I get a different error, 

"Configured debug type correctly is not supported."
