### ISSUE TITLE
vs code freeze when I open a certain file

### ISSUE THREAD

**Issue by shrekuu** [microsoft/vscode#85264]
Issue Type: <b>Bug</b>

It freezes when I open this js file:
https://github.com/fex-team/ueditor/blob/dev-1.5.0/dialogs/image/image.js

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv|-psn_0_651423|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-blade-spacer|aus|1.0.3
markdown-preview-github-styles|bie|0.1.6
vscode-intelephense-client|bme|1.2.3
sqlformatter|bre|0.0.7
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.2
laravel-easy-blade-snippets|dac|1.2.1
vscode-markdownlint|Dav|0.32.0
vscode-faker|dee|1.3.0
githistory|don|0.4.6
xml|Dot|2.5.0
prettier-vscode|esb|3.8.0
vscode-nginx-conf-hint|han|0.1.0
randomeverything|hel|0.0.3
beautify|Hoo|1.5.0
wxss-peek|htp|0.0.3
vetur-wepy|hu2|0.13.6
smarty|imp|0.3.0
svn-scm|joh|2.1.3
vue-beautify2|ker|0.0.3
Angular-BeastCode|Mik|8.0.10
mssql|ms-|1.7.1
python|ms-|2019.11.49689
vetur|oct|0.22.6
laravel-blade|one|1.20.0
minapp-vscode|qiu|2.2.2
laravel-5-snippets|sac|2.0.1
vscode-nginx|sha|0.6.0
autoimport|ste|1.5.3
open-in-browser|tec|2.0.0
hosts|tom|1.1.1
vscode-input-sequence|tom|0.2.0
lorem-ipsum|Tyr|1.2.0
import-beautify|var|0.3.0
vscodeintellicode|Vis|1.2.0
vscode-js-import|wan|0.15.5
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does this reproduce if you run with all extensions disabled? If not, please bisect to identify the one causing your problem, then report on the extension's repo.

**Comment by shrekuu** [comment]
@gjsjohnmurray   I disabled all extensions and tried again. It still freezes. It says "The window is no longer responding".

**Comment by shrekuu** [comment]
I found this is the cause in my config file. Ok I think I should remove this line and use the default one.

      "editor.maxTokenizationLineLength": 2000000,
