### ISSUE TITLE
Skip and jump to breakpoint

### ISSUE THREAD

**Issue by CyberMew** [microsoft/vscode#85260]
Imagine my code go downwards like this (alphabets are breakpoints):

A
|-> B, C, D, E, F, G, H, I, J, K, L
M
|-> B, C, D, E, F, G, H, I, J, K, L
O
|-> B, C, D, E, F, G, H, I, J, K, L

Now, I want to start debugging from O instead of going through this amount of breakpoints:  
A, B, C, D, E , F, G, H, I, J, K, L, M, B, C, D, E , F, G, H, I, J, K, L, O

I could disable them and then re-enable them, but it's all over the place and I also have other disabled breakpoints, so a select all checkbox is of no much use.

Play, skip all breakpoints and continue to the selected breakpoint would be much easier in debugging. It will be very flexible in debugging A, M, O in my above examples (and definitely in every day debugging as well). I hope the reasoning/example is compelling enough.

**Comment by gjsjohnmurray** [comment]
Sounds like what #70715 asked for as a secondary request:

> and it would be very nice if there was the option, through context menu and a different key combination, to »run to cursor« while ignoring other breakpoints.

@isidorn it seems to have been overlooked there.

**Comment by isidorn** [comment]
This is a fair feature request. However we do not have immediate plans to tackle it in the near future.
