### ISSUE TITLE
support syntax highlighting for @example + code fence at the same time

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/vscode#85262]
We use typedoc which only support including code blocks wrapped in code fences https://github.com/TypeStrong/typedoc/issues/135 so we use @example tag and fenced code together to get example tag and syntax highlighting of the code in the generated docs. However, VS Code does not high light the fenced blocks in JS Doc correctly.  The intellisense tool tip doesn't either.

![image](https://user-images.githubusercontent.com/7583839/69301368-f16d6880-0bca-11ea-8744-b078043bfb6c.png)

@example + code alone, or fenced code alone works fine. It may be trivial to support the case when both are used?

![image](https://user-images.githubusercontent.com/7583839/69301535-72c4fb00-0bcb-11ea-8220-8a7b3fcfcc06.png)

**Comment by mjbvz** [comment]
What VS code version are you using?

**Comment by jeremymeng** [comment]
> What VS code version are you using?

```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by mjbvz** [comment]
As of VS Code 1.40, jsdoc markdown highlighting now lives in an extension: https://marketplace.visualstudio.com/items?itemName=bierner.jsdoc-markdown-highlighting

Can you please file the feature request against that extension instead
