### ISSUE TITLE
Some extensions detail page layout cover the terminal

### ISSUE THREAD

**Issue by yoyo837** [microsoft/vscode#85261]
Issue Type: <b>Bug</b>

All extensions disabled, see video pls: [Nov-21-2019 11-14-13.mp4.zip](https://github.com/microsoft/vscode/files/3872671/Nov-21-2019.11-14-13.mp4.zip)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
javascript-ejs-support|Dig|1.1.3
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|3.8.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.5.1
auto-close-tag|for|0.5.6
todo-tree|Gru|0.0.162
vscode-codeowners|jas|1.1.1
vscode-language-pack-zh-hans|MS-|1.40.2
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
vscode-react-native|msj|0.13.1
vetur|oct|0.22.6
rust|rus|0.7.0
stylelint|shi|0.51.0
vscode-icons|vsc|9.5.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment]
See #84395 screenshot. Is this a duplicate?

**Comment by yoyo837** [comment]
Yes, duplicated of #84395, #83209
