### ISSUE TITLE
Linux: application stopped painting

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8526]
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 3.13.0-34-generic

Steps to Reproduce:
1. Alt-Tab back and forth between Code and the file explorer
2. -> Sometimes Code shows all black while the file explorer is in the foreground

In one case it stayed all black (not sure how I got there). The window title did still update when changing the editor in focus by randomly clicking.

**Comment by chrmarti** [comment]
![no-repaint](https://cloud.githubusercontent.com/assets/9205389/16462014/2f0a2be6-3de4-11e6-8816-79665d329284.png)

**Comment by bpasero** [comment]
@chrmarti are you using Linux inside a VM like parallels?

**Comment by chrmarti** [comment]
@bpasero yes, I'm using Parallels. I might have set the VMs memory too low, not sure if that affected it, but it seemed to no longer or not as often occur after increasing that.

**Comment by bpasero** [comment]
I see this all the time and this also explains some other bugs you filed on drag and drop. Parallels is buggy.

**Comment by bpasero** [comment]
Closing, there is not much we can do imho.
