### ISSUE TITLE
Sometimes does not initialize the exception breakpoint.

### ISSUE THREAD

**Issue by actboy168** [microsoft/vscode#85279]
In the initialization phase, VSCode will send setBreakpoints, setFunctionBreakpoints, setExceptionBreakpoints, etc. to the DA. But if DA returns error after setBreakpoints, then VSCode will not send setFunctionBreakpoints and setExceptionBreakpoints.

**Comment by weinand** [comment]
That behavior sounds correct to me.
What's the problem with that?

**Comment by actboy168** [comment]
Why is this correct? I think they should be independent of each other.

If this behavior is correct, does it mean that DA should not return an error so that it can receive all breakpoint initialization?

**Comment by weinand** [comment]
yes.
