### ISSUE TITLE
Crash on Terminal Server

### ISSUE THREAD

**Issue by ReneGubler** [microsoft/vscode#85274]
- VSCode Version: 1.40.1 x64 System and Insider Preview 1.41.0 x64 System 
- OS Version: Windows Server 2016 

Steps to Reproduce:

1.Install VS Code and run it on a Terminal Server or Citrix Server
2.App Crash

Resolve the Problem: Install 1.39.2

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/84914 , please refer to it for available solutions.

**Comment by ReneGubler** [comment]
We have the issue on a Windows Terminal Server (and also on a Citrix but this is only backup scenario). What about a solutions for Windows Server without Citrix installed?

**Comment by deepak1556** [comment]
Can you follow the steps from https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows and attach the crash report.

**Comment by dpalchuk** [comment]
Confirm issue on RDS/Citrix and fix using https://code.visualstudio.com/updates/v1_39.

**Comment by deepak1556** [comment]
@dpalchuk please follow the workaround mentioned in https://github.com/microsoft/vscode/issues/84914#issuecomment-556033410 .
