### ISSUE TITLE
Replace All should be disabled while search is still running

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8527]
Testing #8184.

- VSCode Version: Insiders 6/29
- OS Version: Windows

Steps to Reproduce:

1. Use a large code base such as the vscode repo
1. "View: Show Search"
1. Expand Search
1. Enter `a` as search string 
1. Enter `b` as replace  string
1. Press Enter
1. While the search is still running press 'Replace All'

-> What the replace all dialog shows is a snapshot.

Either Replace All should be disabled while a search is running or the dialog should show the life number of search results and should enable OK only when the search finished.

**Comment by sandy081** [comment]
Fixed by #8302 and #8330
