### ISSUE TITLE
every time showing Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by pawanyoda** [microsoft/vscode#85278]
- VSCode Version: 1.40.1
- OS Version: OS Catalina 10.15.1 

Steps to Reproduce:
 
1. Its getting stuck every 10 or 15 minutes after.
2. or no keyboard keys are going to work.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
/needsMoreInfo

What extensions do you have installed. Pls provide detailed steps for how to reproduce it.
Please include the Log of the Extension host. 

![image](https://user-images.githubusercontent.com/172399/69330831-004c2d80-0c54-11ea-95fa-e0b8017e2286.png)
