### ISSUE TITLE
Constant is already declared in an unrelated folder

### ISSUE THREAD

**Issue by jeremythille** [microsoft/vscode#85280]
- VSCode Version: 1.40.1
- OS Version: Win7 x64

Steps to Reproduce:

1. Create two sibling folders anywhere : "num1" and "num2"
2. Inside each folder, create a file "number.ts"
3. Put this in each file : `const number = 1;`
4. Open both files in Code

**Issue : `number` is underlined in red in either file, with the hint saying :**

> Cannot redeclare block-scoped variable 'number'.ts (2451) number.ts (1, 7): 'number' was also declared here.

These two files are not related, not part of the same project, and in two different folders.

Does this issue occur when all extensions are disabled?: Yes/No

No, the issue does not occur if I launch using `code --disable-extensions`.
However it _does_ occur after I launch Code normally then disable all extensions manually, one by one (and restart when required) and there is no active extension left sooooo...?

**Comment by egamma** [comment]
By default the project scope of TS is the folder you have opened. To create multiple project scopes you have to define a tsconfig.json file, pls see the documentation.
