### ISSUE TITLE
Cancel Replace All confirmation dialog while search is running resets the search progress

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8528]
Testing #8184.

- VSCode Version: Insiders 6/29
- OS Version: Windows

Steps to Reproduce:

1. Use a large code base such as the vscode repo
1. "View: Show Search"
1. Expand Search
1. Enter `a` as search string 
1. Enter `b` as replace  string
1. Press Enter
1. While the search is still running press 'Replace All'
-> Search progress stops
1. Press Cancel in the dialog

I'm not sure what happens at this moment, but the search progress is reset (maybe even a new search is started) and the search seems to never finish.

**Comment by sandy081** [comment]
Fixed by #8302 and #8330
