### ISSUE TITLE
intelisense not working for local vars and imports[JS/TS/py]

### ISSUE THREAD

**Issue by SwapnilSoni1999** [microsoft/vscode#85286]
since few days I noticed vscode is not showing local variable suggestions and doesnt shows classname. it shows methods after writing whole variable name from document

- VSCode Version: 1.40.1
- OS Version: ArchLinux

![image](https://user-images.githubusercontent.com/25403317/69328239-e707a900-0c74-11ea-81d4-5dc1cc21ca6d.png)
here as you can see no variable reference is shown but when I type full variable name 

![image](https://user-images.githubusercontent.com/25403317/69328374-21714600-0c75-11ea-9a2f-25776897a781.png)

- I have tried resetting all settings ... still didnt worked
- uninstalled all extensions and reinstalled ... still didnt worked

**Comment by SwapnilSoni1999** [comment]
Update: I have to manually press `ctrl + space` to trigger suggest only then its working

**Comment by mjbvz** [comment]
Your screenshots show that intellicode is enabled. Does this still happen when intellicode is not enabled?

Also, can you share your use settings? Have you disabled `editor.quickSuggestions` for example?

**Comment by SwapnilSoni1999** [comment]
yes I have fixed now set `editor.quickSuggestions` to true and it worked, before that I always had to press `ctrl+space` sorry for dumb issues
