### ISSUE TITLE
Infinite DateTime Tree When debuging simple program.

### ISSUE THREAD

**Issue by dyzav** [microsoft/vscode#85282]
- VSCode Version: 1.40
- OS Version: LXQt 0.14.1

Steps to Reproduce:

1. .Net Core 101 from microsoft learn program. 
2. Debug on working program
3. Expand DateTime on Transactions.
4. Then Expand DateTime inside and so on. 
[
![dotnetDateIssue](https://user-images.githubusercontent.com/25512886/69326467-bbb89600-0c43-11ea-97d9-3d885b043a92.png)
](url)

**Comment by egamma** [comment]
Please file the issue against the C# extension.
