### ISSUE TITLE
Terminal turns black

### ISSUE THREAD

**Issue by MartinHolodeck** [microsoft/vscode#85283]
- VSCode Version:1.40.1
- OS Version:Windows 10 Pro 10.0.18362

Steps to Reproduce:

1.Windows disconnects additional screens
2.When screen turns back on, terminal in VS Code stays black or does not render full output

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
> Windows disconnects additional screens

Do you mean unplugging the monitor that VS Code is on?
