### ISSUE TITLE
Add a way to "close"/"disable" folder temporarily without removing it from workspace (Eclipse style)

### ISSUE THREAD

**Issue by jakub-g** [microsoft/vscode#85295]
# Scenario

- I have only one workspace. In this workspace I have about 15 folders (1 folder == 1 git repo) that are all related projects: `folder1` ... `folder15`
- Sometimes I want to do some work that only touches a few of those folders. However, when I search, I get matches from all 15 folders.
- I want to _disable_ `folder12` (to exclude it from searches etc.), but _without removing it from workspace_. I.e. the folder would be effectively dead, but would still show up on the list of folders, so it can easily be _reenabled_.

Right now AFAIU, I can only _remove_ project from workspace when I right click on it, but then I have to search for it again on disk when I want to readd it. 

# Proposal

**There should be a new option: `Disable folder` / `Enable folder`** in the menu below:

![image](https://user-images.githubusercontent.com/1437027/69337295-c9c8df80-0c60-11ea-9511-64234bfa0503.png)

Related screeshots from Eclipse:

![image](https://user-images.githubusercontent.com/1437027/69337099-5aeb8680-0c60-11ea-89ca-b2da660143da.png)
![image](https://user-images.githubusercontent.com/1437027/69337149-79ea1880-0c60-11ea-9240-ea6ee6344234.png)

# More explanation

My use case is not about resource consumption, but about:

- *avoiding search matches that are useless in CTRL-SHIFT-F / CTRL-SHIFT-H* (workspace-wide find/replace)
- *avoiding file matches that are useless in CTRL-P* (quick file open)

Assume you work on `foobar` but you have one annoying folder which has 1000 matches of `foobar` which are not relevant to your current work. You want to disable it for a day or two, or more, but not completely thrash it out from workspace.

# Alternatives

As an alternative, to prevent search matches, one could use "files to exclude" option, but this is just a small textbox, and not great from UX point of view (feels like editing PATH in Windows XP).

There's no easy way to prevent matches in quick file open though that I am aware of.

**Comment by jakub-g** [comment]
Alright yeah so the above is a dupe indeed, and the other ticket was just-closed :/ But now there's me + [another person on StackOverflow](https://stackoverflow.com/questions/54755666/how-to-close-a-folder-inside-a-workspace-vscode) with the same requirement :)

**Comment by egamma** [comment]
@jakub-g actually the motivation in Eclipse was free resources when a project is closed, which is a good goal. However, the feature was rarely used in Eclipse.

**Comment by jakub-g** [comment]
@egamma yes this is indeed the main requirement as stated in the #63963 ticket.

I actually used to use that feature in Eclipse to save resources quite often, but also to disable the projects that one would work on "once a year" but were still handy to be available if needed.

As I remember it, in Eclipse importing a new project was painful compared to VSCode (definitely not a "drag'n'drop and it works") so the ability to disable a project without having to go through a pain of readding it was a real killer to me. I loved the feature.

**Comment by brsanthu** [comment]
@egamma with all due respect, I disagree that the feature is rarely used in Eclipse. Most of my colleagues who uses Eclipses this feature which greatly helps manage number of projects. Combined that with "Filter out closed projects" options, can completely remove the noise from the workspace.

I currently have a vscode workspace with 25 projects. Many of them are not accessed that often but I keep it there so I don't have to add to workspace again. If we had this capability, that serves these multiple use cases.

**Comment by egamma** [comment]
@brsanthu 

>@egamma with all due respect, I disagree that the feature is rarely used in Eclipse. Most of my colleagues who uses Eclipses this feature which greatly helps manage number of projects. 

I'm really happy to hear that this feature is getting used in Eclipse. I'll adjust my comment.
