### ISSUE TITLE
Massive replace makes window unresponsible and then crashes the window

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8529]
Testing #8184.

- VSCode Version: Insiders 6/29
- OS Version: Windows

Steps to Reproduce:

1. Use a large code base such as the vscode repo
1. "View: Show Search"
1. Expand Search
1. Enter `a` as search string 
1. Enter `b` as replace  string
1. Press Enter
1. Wait for the search to finish
1. Press Replace All

<img width="694" alt="screen shot 2016-06-29 at 10 36 32 am" src="https://cloud.githubusercontent.com/assets/4674940/16462467/4643da9e-3de6-11e6-9ced-c7219c0534b9.png">

Then:
<img width="710" alt="screen shot 2016-06-29 at 10 37 27 am" src="https://cloud.githubusercontent.com/assets/4674940/16462474/4ece30c4-3de6-11e6-98d5-91c8b91e0820.png">

Eventually the window will crash.

We should have safeguards against this kind of abuse. Independently, the window should never become unresponsive.

**Comment by sandy081** [comment]
There are two parts for this issue

- #8369 - We had the limitation for max search results, which was taken off. I kept it back again. We need to investigate / profile before taking the limitation off
- #8371  - Making replace faster

**Comment by sandy081** [comment]
With above fixes there wont be crash or slowness. Created investigation item #8563 to lift the limitation
