### ISSUE TITLE
[MacOS Catalina] VS Code stealing focus

### ISSUE THREAD

**Issue by astoimenov** [microsoft/vscode#85294]
Issue Type: <b>Bug</b>

I'm not sure what is the problem, but after I upgraded my MacBook to MacOS Catalina VS Code keeps stealing focus and it changes the current visible space to the one with it in it

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by egamma** [comment]
/needsMoreInfo please provide steps when the focus is stolen.
