### ISSUE TITLE
File-Version and Product-Version differ

### ISSUE THREAD

**Issue by xxMUROxx** [Microsoft/vscode#853]
I want to publish VSCode with **WSUS Package Publisher** and there it is possible check for the `file version` whether the update can be updated or not, but the file version remains every release at `0.34.1.0` only the `product version` is updated. With WSUS Package Publisher I can only check for file-version.

Seen in [package.json](https://github.com/Microsoft/vscode/blob/3d93cc4fd5f1b61ee41066d689c57d7d78294a5d/package.json#L4)

Is there a reason why the product version stays at the same level and is not the same as the product-version?

**Comment by alexandrudima** [comment]
@xxMUROxx Not sure what you mean.

VSCode is built on top of [Electron](http://electron.atom.io/).

`version` in `package.json` represents the VSCode version (at `0.10.3` for now).
`electronVersion` in `package.json` represents the [version of Electron we build on](https://github.com/atom/electron/releases) (at `0.34.1` for now)

**Comment by xxMUROxx** [comment]
Regarding the information that Electron is used I have found following issue: https://github.com/maxogden/electron-packager/issues/129

**Comment by alexandrudima** [comment]
@joaomoreno Maybe you understand what this is about

**Comment by xxMUROxx** [comment]
@alexandrudima The problem is that the file-version is not equal to the VSCode version, but it is equal to the version of Electron that is used:

![vscode](https://cloud.githubusercontent.com/assets/4341039/11526380/5bb671d6-98da-11e5-9232-9c3efafa4164.png)

**Comment by alexandrudima** [comment]
Definitely @joaomoreno knows then :)

I can confirm I see the same:
![image](https://cloud.githubusercontent.com/assets/5047891/11526439/c8643b1a-98da-11e5-86b0-8137be89a1cc.png)
