### ISSUE TITLE
Maximize windows button

### ISSUE THREAD

**Issue by Ahtuz** [microsoft/vscode#85307]
please close this issue, i'm sorry, i just found out that this issue is duplicate.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Most likely duplicate of #81102

**Comment by IllusionMH** [comment]
Sorry. Sent somment 15 seconds after issue was closed and before UI was updated :(

Also you can check recent Insiders build https://code.visualstudio.com/insiders/ - I think that fix is already merged and released.

**Comment by Ahtuz** [comment]
Well, it's not your fault, sir. It's my fault that I didn't clearly check other issues similar to this one. By the way, thank you for letting me know about the Insiders build. I didn't found this problem there. I'll be using the Insiders build from now on.
Cheers! :)
