### ISSUE TITLE
[html] "Expand selection" misses { } in <script> tag

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#85306]
Because "expand selection" is language-aware, you can't use it to expand to block scope  
`{....[cursor is here]....}` in a mixed HTML/Javascript file.  Coding within the <script> tags, "expand selection" still looks for HTML "scopes" to expand to.  

**Aren't there extensions that will do this?**
I have tried many, many, and all fail in mixed HTML/CSS/JS files in one way or another.  

So, my request is either
1. "expand" to recognize when it's in a <script> tag, or
2. alternatively allow the user to toggle a "universal" mode, so that expand always just expands to ANY* next bound (matched-character pair `{[(<`, delimiter `_-`, whitespace) 
*these bounds could be user-configurable.

**Comment by ultraGentle** [comment]
I'm wondering if the cause of this is related to #85411 (can't "rename symbol" within <script> tags) in which case perhaps both individual issues should be closed in favor of something like, "some editor features do not work within <script> tags."

**Comment by aeschli** [comment]
To verify:
- Have HTML with embedde css and JavaScript
- Set cursor inside the embededded code and use `Expand Selection` multiple times
- Verify that the selection grows according to the embedded language's syntax, and then using the surrounding HTML.

**Comment by ultraGentle** [comment]
Confirmed!  Much appreciated.
