### ISSUE TITLE
Snippet generates a link

### ISSUE THREAD

**Issue by JCzz** [microsoft/vscode#85302]
- VSCode Version:  1.40.1
- OS Version: MacOs Catalina

Steps to Reproduce:

1. The following snippet generates a link for the line containing "fmt"
```
{	
	"main": {
		"scope": "go",
		"prefix": "go main application",
		"body": [
			"package ${1:name}",
			"import \"fmt \"",
			"test \"something\"",
			"",				
			"func main() {",
			"\tfmt.Println(\"hello world\")",
			"}"
		],
		"description": "Log output to console"
	}
}
```
2. use the snippet
3. When I hover the mouse over "fmt" I get a popup saying "follow link (cmd + click)

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
