### ISSUE TITLE
Don't auto-scroll to first "Find" match

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#85303]
-- Edit --
To anyone arriving here, please continue discussion at #60977, which has more traction and is thus likelier to be voted into being a feature.  Note, though, that this thread addresses some subtleties of the Find Widget behavior that aren't mentioned there, so for anyone who wants to be extra comprehensive, please see the post with the 3 cases and accompanying GIFs below.  Thanks!
-- end Edit -- 

Hello, I'm not sure if this should be considered a bug or a feature request, but it is something I run into probably 10-20 times per day.  

Dear reader, see concrete example at bottom, if that's more your thing.  

**What happens now?**  
I am often looking for instances of a string of characters on my current screen, near my current position.  So, I open the "Find" widget (Cmd+F | Ctrl+F) --  **but, as I begin typing what I'm looking for the editor immediately scrolls to the first match of whatever I've typed so far, even if that's up at the top of the document.**  Even when I finish typing what I was looking for, I then need to scroll back to wherever I was working, which is a big break of focus, especially on a long file.  

**What would you like instead?** 
So, I'd like "Find" to highlight what's typed in the "Find" widget, but not actually jump to the first match until Enter is pressed.  That way a user can use Find for visual aid on the current screen.  This could be an option in settings, or even default behavior, since you're almost certain to need to press Enter anyway to go through subsequent "Find" matches.  

**Why can't I use "Search" instead?** 
I want to see the string I'm searching for in the context of the current page, not in a list of matches.  
I usually have the sidebar hidden to save screen space.  

**Current workaround**
I can type the string I'm looking for in the main body of the editor, select it, and then let the editor  highlight other instances -- but obviously this isn't ideal, since the user shouldn't be typing non-desired code into the coding area just to look for nearby code.  

**Concrete example**: want to see nearby instances of string `xkcd`.
(This is obviously simplified, just to make the point.)
xkca  
xkca  
xkca  
xkca  
xkca  
xkca  
xkca  
xkca <-- current cursor position
xkca  
xkca  
xkcd
xkca  
xkca
xkca  
xkca  
**Upon typing "xkc", editor scrolls to top to document, highlighting "xkc", but what I actually wanted was to finish typing "d" so that I could easily see the match nearby.  When I do press "d", editor scrolls to "xkcd", but not at the same screen position as I was originally.**

**Comment by ultraGentle** [comment]
Hello!  Just wondering if this is a backlog-candidate.  It still jumps the screen as you begin typing.  Maybe highlighting while typing, and scrolling only on `Enter` would allow for more accessible use of this feature (it's quite disorienting for some).  Thanks!

**Comment by rebornix** [comment]
@ultraGentle I tried with the snippet you posted above but didn't reproduce, the Find Widget will start search from current cursor position instead of from the top of the document 

![Kapture 2020-01-27 at 14 33 49](https://user-images.githubusercontent.com/876920/73219947-2093df00-4112-11ea-849d-13bf0880d65b.gif)

**Comment by ultraGentle** [comment]
@rebornix, Sorry I didn't provide a clear enough test case.  Here is issue precisely: 

The reason you are not seeing the behavior is because the the letter `x` is already visible on the screen when you begin searching.  

There are actually **3 cases**, 2 of which are disorienting: 

**Scenario**: using `Find` to look for `Z7` in code block at bottom of screen

**Case 1**: 1. `find` string is **not** on current screen --> editor scrolls to top on type (disorienting)
![vsc1](https://user-images.githubusercontent.com/41548755/73284703-f4846680-41c2-11ea-8ec4-79a3c60fb77c.gif)

**Case 2**: `find` string **is** on screen, **after** cursor --> editor highlights, no scroll (clear) 
![vsc2](https://user-images.githubusercontent.com/41548755/73284721-fa7a4780-41c2-11ea-980e-31be3fe25f0b.gif)

**Case 3**: `find` string **is** on screen, **before** cursor --> editor scrolls to top (disorienting)
![vsc3](https://user-images.githubusercontent.com/41548755/73284843-27c6f580-41c3-11ea-8117-024f3378e630.gif)

In general, we do not wish to scroll to the first letter of our `find` term; we want to only go to the *whole* match.  And even then, we may not wish to move at all, but rather just check to see whether what we are looking for is on-screen.  

**Solution** scroll on demand, not on type.  I.e., highlight on type, but scroll only upon `enter` press (or `click`ing on the widget up/down arrows.  

I appreciate your taking the time to check my issue and respond, so I've tried to do the same and be as clear as possible.  I hope that helps!  

I do believe this is an **accessibility issue**, because having the screen change positions unexpectedly is quite disorienting.

**Comment by ultraGentle** [comment]
For your convenience, here is the "code" from my gifs above.   As is, it represents Case 1.  To reproduce Cases 2 and 3, simply change one of the `7`s in the bottom block to a `Z`.  

```
Z

0
1
2
3
4
5
6
7
8
9

00
11
22
33
44
55
66
77
88
99

000
111
222
333
444
555
666
777
888
999

0000
1111
2222
3333
4444
5555
6666
7777
8888
9999

00000
11111
22222
33333
44444
55555
66666
77777
88888
99999

000000
111111
222222
333333
444444
555555
666666
777777
888888
999999

0000000
1111111
2222222
3333333
4444444
5555555
6666666
7777777
8888888
9999999

00000000
11111111
22222222
33333333
44444444
55555555
66666666
77777777
88888888
99999999


000000000
111111111
222222222
333333333
444444444
555555555
666666666
777777777
888888888
999999999

0000000000
1111111111
2222222222
3333333333
4444444444
5555555555
6666666666
7777777777
8888888888
9999999999

00000000000
11111111111
22222222222
33333333333
44444444444
55555555555
66666666666
77777777777
88888888888
99999999999

000000000000
111111111111
222222222222
333333333333
444444444444
555555555555
666666666666
777777777777
888888888888
999999999999

0000000000000
1111111111111
2222222222222
3333333333333
4444444444444
5555555555555
6666666666666
7777777777777
8888888888888
9999999999999

00000000000000
11111111111111
22222222222222
33333333333333
44444444444444
55555555555555
66666666666666
77777777777777
88888888888888
99999999999999

000000000000000
111111111111111
222222222222222
333333333333333
444444444444444
555555555555555
666666666666666
777777777777777
888888888888888
999999999999999

0000000000000000
1111111111111111
2222222222222222
3333333333333333
4444444444444444
5555555555555555
6666666666666666
7777777777777777
8888888888888888
9999999999999999

00000000000000000
11111111111111111
22222222222222222
33333333333333333
44444444444444444
55555555555555555
66666666666666666
77777777777777777
88888888888888888
99999999999999999

1. `find` string is NOT on current screen --> editor scrolls to top on type (disorienting)   :(
2. `find` string IS on screen, AFTER cursor --> editor highlights, no scroll (clear)          :)
3. `find` string IS on screen, BEFORE cursor --> editor scrolls to top (counterproductive)  :(

000000000000000000
111111111111111111
222222222222222222
333333333333333333
444444444444444444
555555555555555555
666666666666666666
777777777777777777
888888888888888888
999999999999999999
```

**Comment by rebornix** [comment]
@ultraGentle what's your expected behavior in this case? Do you want to have auto search turned off?

**Comment by ultraGentle** [comment]
@rebornix expected behavior is that 

- on `input` to the Find Widget, the matching strings are (1) **highlighted** on screen, and (2) **decorated** in the in the scroll bar, but (3) the **position of the screen should *not* change**, no matter where the cursor happens to be, or whether the first match happens to be on the current screen.  

- only on `enter` or `click ↑|↓` should the editor jump to the next match.  

The Find Widget serves two useful functions 

- (A) It lets you **see** where matches are (on-screen highlights and scrollbar decorations)

- (B) It lets you **go** to a match.  

Right now, (B) is getting in the way of (A) in cases (1) and (3) from my example.  

If you separate these (by putting the `scroll` listener on `Enter` and the `highlight` listener on `input`) it prevents unexpected and disorienting behavior.  

I hope this helps.  I'm happy to drop it if you believe the current behavior is optimal.  But I believe it's impacting anyone who uses the Find Widget to help see things on screen.  It certainly impacts me!

**Comment by ultraGentle** [comment]
@rebornix Respectfully, Isn't this more of an accessibility bug than a feature request?  Especially with regard to its impact on screen readers (since it changes the page unexpectedly)?  

As a feature request, I don't know how anyone would know to look for it and upvote.  

In any case, thanks for working through diagnosing this issue with me.  Best wishes.

**Comment by rebornix** [comment]
I labelled it as a feature request as it's pretty close to "Disable auto search in the find widget" (which already has an issue tracking that), and I need to think about how to polish this experience.

**Comment by ultraGentle** [comment]
I had no idea there was a near duplicate! My apologies.  I will copy the non overlapping information from this thread to that one so discussion can continue there, unless you would prefer to keep them separate.

**Comment by ultraGentle** [comment]
Just noting: I believe this issue can now be closed, as I have copied over anything relevant to the more popular thread.  I'll leave that to the VSCode team's discretion, however.

**Comment by rebornix** [comment]
@ultraGentle thanks again for your feedback there, let's use that thread to track the issue.
