### ISSUE TITLE
Allow debuggers to add simple toggle checkboxes similar to Breakpoint options

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#85305]
For Dart we have some debugger settings that let the user control whether the step through just their own code, or also external packages and/or SDK sources. Currently they're buried away in the settings so they're a bit clumsy to change, and users may want to toggle them on and off while debugging.

As a solution, I've made a status bar that cycles through the options on click:

![Nov-21-2019 1-44-33 pm](https://user-images.githubusercontent.com/1078012/69343226-18787880-0c65-11ea-8ee4-076d31f96e8e.gif)

This works, but it occurred to me that debuggers already have somewhere they can add tickboxes in debug side bar under breakpoints:

<img width="313" alt="Screenshot 2019-11-21 at 2 50 28 pm" src="https://user-images.githubusercontent.com/1078012/69348561-4adaa380-0c6e-11ea-8b6c-949f7e5419e4.png">

It would be a much nicer UI to add them here as tickboxes, but it doesn't make much sense under the heading "Breakpoints". Is it reasonable to add something similar to `setExceptionBreakPointsRequest` that's more generic, for arbitrary debug toggles?

This isn't specific to Dart, [Omnisharp has a setting for `justMyCode` and `enableStepFiltering`](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#just-my-code) and nodeJS has [smart stepping](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_smart-stepping). These all seem like ideal things to expose on the debug side bar for easy toggling during a debug session.

**Comment by isidorn** [comment]
This is a fair feature request which we can keep open as a feature request for now.
To tackle this we would need to introduce a new view in the debug viewlet, which the extensions could contribute to
fyi @weinand
