### ISSUE TITLE
Block travel

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#8530]
Hello,

is there key binding / plugin which enables traveling between blocks of code (along with selection)?

Image to describe what I mean:
![http://i.imgur.com/5OHdf55.gif](http://i.imgur.com/5OHdf55.gif)

Plugin which provides this functionality in Atom editor: http://blog.atom.io/2014/03/04/this-week-in-atom-packages.html#block-travelhttpsatomiopackagesblock-travel-by-leejarvishttpsgithubcomleejarvis

**Comment by dcsan** [comment]
love this, it's hard to use an editor without it now. any solution found?

**Comment by leejarvis** [comment]
I wrote the original Atom package because I can't live without this, but it doesn't seem to be a popular request. I've recently picked up VSCode but this is holding me back a little. I'll have a shot at writing a plugin soon I hope

**Comment by leejarvis** [comment]
Oh, I guess this already exists: https://marketplace.visualstudio.com/items?itemName=sashaweiss.block-travel -- not sure why it wasn't showing up for me previously. Giving it a whirl now

**Comment by leejarvis** [comment]
That extension works well for me. I think this can be closed. Thank you @sashaweiss

**Comment by Hurtak** [comment]
Oh cool, thanks @leejarvis for pointing that out.

**Comment by sashaweiss** [comment]
Thanks for the mention - glad you're enjoying!
