### ISSUE TITLE
Add a setting to disable automated grid maximize-minimize

### ISSUE THREAD

**Issue by gardwired** [microsoft/vscode#85309]
On large 4K screens where I am using multiple row/column grid layout (eg 3x3 or more), the automated maximize behavior results in total chaos of the layout.  I like the idea but what was a small portion of the screen now becomes entirely too large and disrupts other rows.

Suggest:
* Ability to disable "Automated Resize" entirely - this isn't always desireable and annoying when I am unable to turn it off.  I click and it just goes bonkers.  I understand that if none of your editor panes are "minimize" then it doesn't happen, but then I have to keep paying attention to that which I don't want to have to do.  Although I can't reproduce it, it does feel to me that sometimes it autoresizes the newly clicked pane even if something isn't minimized (and i don't normally double-click).  It's just an annoyance in it's current "automated" functionality on large screens.
* Ability to set Automated resize to be vertical, horizontal or both  -- ie I could just snap to resize within a row.
* Ability to set the percentage of the screen that will be the new "maximized" width/height (depending on the previous vert/horiz setting).  So I can say max-width: 40%.  or even snap to my ruler (that would be pretty cool)
* Ability to click a button to unmax (undo) to return to previous layout -- ie behaves more like a min/max window.  I do like the double-click to un-max, but it returns not to the previous state, but a purely evened-out view with all panels/rows the same size. 

In general, I like snap to max on smaller screens, but at times i want to still be able to see more of what the other panels have.  I  write code in narrower columns with max length of maybe 120 chars.  This allows me to be able to have  multiple columns which makes it easier to compare code when refactoring etc.  The feature just needs more nuance imho when thinking about larger screens and complex layouts.

Thanks for all the great work....gg

**Comment by sbatten** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
@sbatten, this is @bpasero.

**Comment by gardwired** [comment]
@bpasero  would just like to encourage you to consider a simple ability to disable this feature.   on a large screen it ends up being a distraction that unpredictably blows up the screen.  thx for your consideration.

**Comment by bpasero** [comment]
I have updated the title to reflect the request.
