### ISSUE TITLE
macOS new window position is not offset as it should be

### ISSUE THREAD

**Issue by chriskrycho** [microsoft/vscode#85304]
- VSCode Version: 1.40.1
- OS Version: 10.15.1

Steps to Reproduce:

1. In Settings, set **Window: New Window Dimensions** to `inherit` (which matches the behavior of normal windows in macOS).
2. Open a Code window.
3. Open *another* Code window—whether via `code <some other directory>` or <kbd>⌘</kbd><kbd>⇧</kbd><kbd>N</kbd>.

The new window will appear in exactly the same position in the desktop as the other, covering it entirely and not at all offset.

The normal macOS behavior is for the new window to be positioned slightly offset—in equal measure down and to the right, until a new window cannot fit at that position, and then starting from the top edge of the screen and far enough left that continuing the operation will eventually bring you full circle.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@chriskrycho thanks for pointing this out. since the behavior for inherit has been around for so long, I opted to added a new option named `offset` that function as you desire.

**Comment by chriskrycho** [comment]
Makes sense to me – thanks for fixing it!
