### ISSUE TITLE
Cursor jump and scroll when switching between splits -- and highlights intervening code

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#85308]
The set up: vertical split, same file in both panes, but different positions in file.  

The problem: clicking† in a pane switch focus panes sometimes‡ causes the cursor to jump, and sometimes selects the code in between the original cursor position and the jumped-to position.  

† switching focused split via keyboard shortcut never causes this problem 
‡ maybe 10% of the time, and in half of those the selection issue also occurs

I doubt the "10%" is random; there must be something concrete causing it to happen (like maybe something is selected in the un-focused pane), but all I've discovered so far is that it's only tied to click-switching.  

When did it start?  At least a month ago.  

Related issues: searching for this issue revealed sort-of-maybe-related issues in conjunction with VSCode Vim, but I'm not using that, or the Vim extension.  I'll list them here, just in case: 

https://github.com/VSCodeVim/Vim/issues/2688
https://github.com/VSCodeVim/Vim/issues/3455
https://www.reddit.com/r/vscode/comments/8tv41k/independent_cursors_with_split_panes_on_the_same/

I wish I could give 100% reproducible steps... any suggestions for how to test this issue more systematically are welcome!

OS X 10.13.6
VSCode Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

**Comment by egamma** [comment]
/needsMoreInfo Can you reproduce the problem when you have all extensions disabled?

**Comment by ultraGentle** [comment]
Update: I've working with extensions disabled today, and I am not experiencing the problem.

However, the problem is intermittent, so I can't be sure that extensions-disabled is "proof" that it's an extension-related problem.  

Any suggestions for how I can provide more information or systematic testing are welcome.

**Comment by egamma** [comment]
@ultraGentle thanks for following-up. The VIM issues you are referring to have already been fixed in the VS Code VIM extension,  so they are not related.

Can you include the extensions you are using (`code --list-extensions`).

**Comment by ultraGentle** [comment]
Extensions below.  

Another hypothesis is that the "jump" could be related to the setting "Cursor: surrounding lines," which I have set to "10."  Some small evidence for this is that the number of lines erroneously selected is always roughly 10 or fewer -- never more than a full screen's worth, certainly.  

That said, as requested: 

**Installed extensions** (not all of these are enabled, but I didn't see a way to filter for that):
2gua.rainbow-brackets
albert.TabOut
albymor.increment-selection
Anjali.clipboard-history
arthurwhite.white
benjavr.jshintrc-generator
bierner.comment-tagged-templates
cdes.wrap-with-template-string
chunsen.bracket-select
closedcontour.very-smart-select
cmstead.jsrefactor
CoenraadS.bracket-pair-colorizer-2
dbaeumer.jshint
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
eg2.tslint
esbenp.prettier-vscode
formulahendry.auto-rename-tag
formulahendry.code-runner
fosshaas.fontsize-shortcuts
gebilaoxiong.vscode-flatland-icon-theme
gerane.Theme-Github
Gruntfuggly.activitusbar
Gruntfuggly.scoper
Gruntfuggly.todo-tree
Gruntfuggly.ubertab
gtwsky.oolory
HookyQR.minify
huizhou.githd
ispushkin.pushkin-is-white-theme
jasonlhy.vscode-browser-sync
jeremyrajan.browsersync
josee9988.minifyall
letrieu.expand-region
lukapetrovic.image-resizer
mhutchie.git-graph
morissonmaciel.typescript-auto-compiler
mrmlnc.vscode-autoprefixer
ms-vscode.vscode-typescript-tslint-plugin
msjsdiag.debugger-for-chrome
olback.es6-css-minify
ow.vscode-subword-navigation
plibither8.remove-comments
pranaygp.vscode-css-peek
pustelto.bracketeer
ritwickdey.LiveServer
ryu1kn.partial-diff
ryuta46.multi-command
sashaweiss.bracket-jumper
saviorisdead.Theme-GitHubCleanWhite
Shan.code-settings-sync
SirTori.indenticator
sohamkamani.code-eol
sporiley.css-auto-prefix
streetsidesoftware.code-spell-checker
thomaspink.theme-github
toba.vsfire
usernamehw.errorlens
v4run.transpose
vincaslt.highlight-matching-tag
VisualStudioExptTeam.vscodeintellicode
vittorioromeo.expand-selection-to-scope
vmsynkov.colonize
WallabyJs.quokka-vscode
webreflection.literally-html
xyz.local-history
yuichinukiyama.vscode-preview-server

**Comment by ultraGentle** [comment]
Just to follow up, this cursor-jump behavior sounds similar to #70306.  

As suggested in that thread, I have have attempted disabling user settings related to "global find clipboard," to see if this is the same bug, or a different one.

**Comment by rebornix** [comment]
@ultraGentle let me know if disabling global find clipboard works for you.

**Comment by ultraGentle** [comment]
It has not happened since I disabled "global find clipboard."

**Comment by lionello** [comment]
Best workaround I've found so far is to only enable one of these settings:
```
    "search.globalFindClipboard": false,
    "editor.find.globalFindClipboard": true,
```

**Comment by rebornix** [comment]
This issue was triggered by sharing find query in multiple find widgets and automatic search.
