### ISSUE TITLE
Bug with the setting `"editor.find.autoFindInSelection": "never"`

### ISSUE THREAD

**Issue by adamwirth** [microsoft/vscode#85317]
I had the setting `"editor.find.autoFindInSelection": "never"` enabled in my User-level settings. It was marked as "changed from default" by the UI, even though that _is_ the default value for it. For some reason, this seemed to make the autoFindInSelection behave like "always" across all workspaces for me. I solved the problem by clicking "reset" on the value's dropdown and restarting VSCode, as well as adding it explicitly in settings.json.

My guess is that this is something with the setting being held over from an older version. But I don't know.

**Comment by rebornix** [comment]
This usually happens when we update the schema of a setting, and we restore the legacy value incorrectly. You can delete the setting from the setting.json and then set the value from the settings ui again.
