### ISSUE TITLE
Regression: settings.json intellisense not working within quotes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8531]
- VSCode Version: code-oss-dev 1.3.0 (1739c99c7255a22c588d9a1aaa141fdc38c90813)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open user settings
2. Try add a new setting (with quotes) using intellisense

Type `"`, no intellisense popup (it should appear here):

![image](https://cloud.githubusercontent.com/assets/2193314/16463772/1c8a4886-3dec-11e6-8e80-f9612c5b4043.png)

Type `e`, intellisense popup appears:

![image](https://cloud.githubusercontent.com/assets/2193314/16463800/388f716e-3dec-11e6-8aec-76a6d76c6ea0.png)

Type `d` to refine suggestions, popup disappears:

![image](https://cloud.githubusercontent.com/assets/2193314/16463823/5387a22a-3dec-11e6-9dbe-07e6e1f6fd4b.png)

**Comment by Tyriar** [comment]
This should be fixed for June if possible, I always use quotes here and it feels very broken. This bug could also potentially have other implications for code completion providers. Please comment @aeschli

**Comment by bpasero** [comment]
I can reproduce on Mac.

**Comment by egamma** [comment]
Works on windows, but can repro on the Mac.

Requesting intellisense again after 'd' correctly shows the extensions.

**Comment by jrieken** [comment]
@aeschli The problem is that the `filterText` is set to `"e` which doesn't match the word after more typing , like `"ed`.

**Comment by aeschli** [comment]
fixed
