### ISSUE TITLE
Maximized window with custom title bar places 1px on second monitor (regression)

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#85310]
Issue Type: <b>Bug</b>

_**Workaround:** In my case it appears only after exiting Full Screen or Zen Mode. So if you don't use them often - just close and open VS Code - dimensions will be OK. If you use FS/ZM - dimensions should be ok if you activate FS/ZM again._

Similar issue was reported for 1.39 #83968 and fixed in 1.40.

However with latest Insider update it reappeared again.

![image](https://user-images.githubusercontent.com/1312662/69352440-9c425d00-0c85-11ea-9afb-65e6d61dcfdd.png)
_(maximized window is a bit wider that Windows task bar, so that 1px is rendered on second monitor)_

Steps to reproduce:
1. Make sure that `"window.titleBarStyle": "custom"` (default)
1. Make sure that you have more than 1 monitor 😄  (checked on horizontal layout of monitors)
1. Maximize window and check second monitor (contrast background image helps)

I believe after #85266

/cc @deepak1556

VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:43:20.960Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
Thanks for the report, yeah became aware of this in my setup as well. I might not target this fix for another stable recovery but rather will target the insiders.

**Comment by IllusionMH** [comment]
Noticed strange detail today:
In my case this problem appears only when I exit Full Screen or Zen Mode. If I don't use Zen Mode or trigger it again - no 1px bleed.

**Comment by miegir** [comment]
In my system it always appears when window is maximized. I alwys maximize window, so it starts maximized as well. When VS Code started maximized on the first monitor, on the other monitor there is 1px light border. But after I minimize/restore or restore/maximize window, that 1px border become dark and thus less annoying.

**Comment by IllusionMH** [comment]
I wasn't able to reproduce this one today, however I think that I saw it on Monday or last week in Insiders.

Version that works as expected for me:

Version: 1.45.0-insider (user setup)
Commit: 9328b32008089c515f39a13db9c71e57c7d36823
Date: 2020-04-22T08:44:55.510Z
Electron: 7.2.2
OS: Windows_NT x64 10.0.18363

**Comment by miegir** [comment]
I installed insiders 1.45.0-insider, but issue still exists for me. I even share my screenshot - the 1px border is displayed on the left edge of the right monitor while entire window is maximized on left one: https://ibb.co/cQ2r7Vf.

**Comment by IllusionMH** [comment]
I hoped that it was fixed over the time with Electron update, but looks like it still there and only "works on my machine" :(

**Comment by trajano** [comment]
Is it possible to disable the custom titlebar?

**Comment by frederikhors** [comment]
Same here, regression.

**Comment by pvdstel** [comment]
I can replicate this as well. It bleeds by exactly one pixel, no matter which monitor it is on. This also happens when reloading with extensions disabled. As you can see in this, the start menu on the right monitor is overlapping with a maximized VSCode on the left monitor:

![image](https://user-images.githubusercontent.com/17430732/84391419-415c5d00-abf9-11ea-8179-6ffaa49f4cf8.png)

Interestingly, this single 1px border is apparently transparent to interaction. Excuse the picture below, but I didn't have a cursor-capturing screenshot tool. You can see that Firefox's tooltip is displayed although the cursor is on the 1px border.

![image](https://user-images.githubusercontent.com/17430732/84391543-6a7ced80-abf9-11ea-9935-02d31378c4bf.png)

<details>
<summary>Installation information</summary>

<pre>
Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
</pre>

</details>

**Comment by trajano** [comment]
This happens with almost every electron app now, whether it is Discord, VSCode, Postman or Whatsapp

**Comment by deepak1556** [comment]
This should be fixed with latest insiders https://code.visualstudio.com/insiders/ , can anyone confirm. Thanks!

**Comment by IllusionMH** [comment]
@deepak1556 works as expected for me: tried maximizing/minimizing, Full Screen, Zen Mode and combinations.
Thanks!

**Comment by miegir** [comment]
I can confirm. Installed `1.50.0-insider` and it is fixed.

**Comment by deepak1556** [comment]
Thanks for testing, closing as fixed.

**Comment by IllusionMH** [comment]
@deepak1556 Do I understand correctly that Electron 9.3.0 contained fix for this one, but was reverted?

**Comment by deepak1556** [comment]
Yup reverted it for https://github.com/microsoft/vscode/issues/106801 to be addressed in next milestone.

**Comment by deepak1556** [comment]
@IllusionMH can you check if the latest insiders fixes the issue. Thanks!

**Comment by IllusionMH** [comment]
@deepak1556 yes, looks like latest insiders build fixes this issue on my PC.

Version: 1.51.0-insider (user setup)
Commit: 89c002ab02f87102d91efc83c191ef1174756c6a
Date: 2020-10-15T23:17:08.035Z
Electron: 9.3.2
