### ISSUE TITLE
Display Jupyter Notebook output text and images in order

### ISSUE THREAD

**Issue by DleanJeans** [microsoft/vscode#85311]
Let me succinctly describe this with code and outputs.

Example Code:
```
from IPython.display import display

for name, image in images_with_name.items():
  print(name)
  display(image)
```

Google Colab;
```
Name1
[Image1]
Name2
[Image2]
Name3
[Image3]
```

VS Code:
```
Name1
Name2
Name3
---------
[Image1]
[Image2]
[Image3]
```

Can we make it output like Google Colab?
I moved from Google Colab to use Jupyter on my local machine and it's kinda weird to see VS Code display texts and images in 2 different views (even with scrollbar).
It's still readable with a few pairs but things get out of hands when it's a long list.

**Comment by IllusionMH** [comment]
/causedByExtension

Please file this issue in Python extension's repo (https://github.com/microsoft/vscode-python/issues) or in repo of extension that you use for  Jupyter Notebooks
