### ISSUE TITLE
No filters suggestions for extensions search field

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#85312]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open Extensions sidebar
1. Type `@` in search field - no suggestions displayed
1. Type `@cat` - still no suggestions

![image](https://user-images.githubusercontent.com/1312662/69356200-bbdc8400-0c8b-11ea-9761-30b3e523db69.png)

There are suggestions in 1.40
![image](https://user-images.githubusercontent.com/1312662/69356160-abc4a480-0c8b-11ea-806b-619363fae34d.png)

VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:43:20.960Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Closed in favor of next issue (#85313) since that one has assignee.

**Comment by JacksonKearl** [comment]
This is a different issue, #85313 is about the popup not being in the right place

**Comment by IllusionMH** [comment]
Thanks

**Comment by JacksonKearl** [comment]
Actually, it seems this one is also about the popup not being in the right place, just more so.
![image](https://user-images.githubusercontent.com/8586769/69368644-5a96bf80-0c4f-11ea-9237-7ff2826ee68e.png)
