### ISSUE TITLE
Debugger mouseover value showing over comments

### ISSUE THREAD

**Issue by tweakimp** [microsoft/vscode#85321]
In debug mode, if you hover your cursor over a word in a comment that is equal to a variable, the value of the variable shows up.

- VSCode Version: 1.40.1 and 1.41.0-insider
- OS Version: Win10 64bit

Steps to Reproduce:
Enter this code, set a breakpoint in the `stop` line and run the file in the debugger.
Hover mouse over `var` in the comment line.
```python
var = "this is just a string"
# some comment about var
stop = "stop"
```
![image](https://user-images.githubusercontent.com/20489521/69362445-cf3d1e80-0c8e-11ea-8af8-97dcc98a53e0.png)

Does this issue occur when all extensions are disabled?: Yes (all disabled but the python extension to run the code)

**Comment by IllusionMH** [comment]
Most likely caused by Python extension and should be reported there

**Comment by tweakimp** [comment]
Ok, I will report it there. Thanks.

**Comment by tweakimp** [comment]
@IllusionMH I was sent back from https://github.com/microsoft/vscode-python/issues/8718#issuecomment-557241598

**Comment by IllusionMH** [comment]
@tweakimp I'm sorry, I was wrong with my suggestion.

I was under impression that debugger receives position of hover (similar to LS) and should not return values in this case, but it's VS Code who composes expression that will be evaluated without info about positions.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/24520

**Comment by tweakimp** [comment]
I wasnt able to find it with the search... Thanks :)
