### ISSUE TITLE
opening vs code does not load bash 

### ISSUE THREAD

**Issue by vjerin** [microsoft/vscode#85323]
- VSCode Version:1.40.1
- OS Version:kubuntu 18.04.3

when I launch vs code application and try to launch a terminal, the terminal panel opens without a bash.
This does not happen when I open a certain file using vs code(right click->open with vscode)

![Workspace 1_001](https://user-images.githubusercontent.com/32333669/69366846-18a46280-0cbd-11ea-94d0-af0a6440e517.png)

**Comment by Tyriar** [comment]
Ca you enable trace logging and check the logs after you create the terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

Also share your settings.json, see https://github.com/microsoft/vscode/wiki/Terminal-Issues#creating-great-terminal-issues
