### ISSUE TITLE
Insiders: Explorer same-level file/folder indentation mismatch in Seti icon theme

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#85336]
VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:43:20.960Z)
OS version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Enable Seti icon theme
2. Look at indentation of folder/file at same level (mismatch)

![image](https://user-images.githubusercontent.com/530988/69376116-a40ffa80-0ca1-11ea-9ba8-14439d6508e9.png)

This is not broken in 1.40.1, only Insiders.

**Comment by misolori** [comment]
This was caused by our recent padding/margin change, should be fixed now. 

![image](https://user-images.githubusercontent.com/35271042/69378696-c125d880-0c63-11ea-812f-39eaf992502d.png)

FYI @joaomoreno
