### ISSUE TITLE
Alternative command discoverability issue

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8533]
Testing #8197.

- VSCode Version: 6/29
- OS Version: Mac

I experimented with the following `package.json`.

```
{
	"name": "name",
	"description": "description",
	"author": "author",
	"version": "1.0.0",
	"publisher": "kieferrm",
	"engines": {
		"vscode": "^1.0.0"
	},
	"dependencies": {},
	"contributes": {
		"commands": [
			{
				"command": "rudi",
				"title": "Rudi Now",
				"category": "Category 1"
				// "icon": {
				// 	"dark": "darkRudi.png",
				// 	"light": "lightRudi.png"
				// }
			},
			{
				"command": "blitzen",
				"title": "Blitzen Now",
				"category": "Category 1"
			}
		],
		"menus": {
			"editor/context": [
				{
					"command": "rudi",
					"group": "myGroup",
					"when": "editorHasSelection"
				}
			],
			"explorer/context": [
				{
					"command": "rudi",
					"group": "navigation@1"
				}
			],
			"editor/title": [
				{
					"command": "rudi",
					"group": "navigation@2",
					"alt": "blitzen"
				}
			]
		}
	}
}
```

When I want to use the alternative command, I first need to hover over the action and then I can press `Option/Alt` to see the alternative.

For exploring the UI it would be more intuitive if both sequences work:
1. Hover then press `Option/Alt`
2. Keep `Option/Alt` pressed and hover of menu actions

**Comment by jrieken** [comment]
@bgashler1 ideas?

**Comment by bgashler1** [comment]
I agree with @kieferrm 's approach if we decide to keep the alt key approach.

We might also consider trying (just an idea) showing alternate commands for any area that is focused and/or hovered over when the <kbd>Alt</kbd> key is pressed (i.e. if you are focused in an editor group, any time the key is pressed you'd see the alternate commands).

This could be distracting each time you press <kbd>Alt</kbd> for say multi-cursor, but we seldom have alternate commands, and this may help with discoverability.

**Comment by jrieken** [comment]
Closing as it is now working both sequences `alt + hover` and `hover + alt`
