### ISSUE TITLE
Search panel should show one result per line, not per occurance

### ISSUE THREAD

**Issue by Glutnix** [microsoft/vscode#85333]
The search panel, when searching across files, shows multiple results per file, highlighting each occurance found as a result under each file. However, it would be good if it finds multiple occurances on the same line to not show multiple results, but show one result per line, and highlight how many occurances are on that line.

Example: search the [Bootstrap LESS](https://github.com/distros/bootstrap-less) repo for ` (a single backtick) and you'll feel the pain.

**Comment by Glutnix** [comment]
![image](https://user-images.githubusercontent.com/88983/69374589-3ac4d180-0d0b-11ea-9957-21df85bbb420.png)
here's an example: the green lines collect results from the same line

**Comment by JacksonKearl** [comment]
Thanks for reporting! This has been discussed in #31817, and our current plan going forward is to move towards a Search Editor experience, where the larger width will make showing multiple results on the same line more reasonable. See #23931.
