### ISSUE TITLE
Settings sync temporary files with warnings/errors show up in problems panel

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#85331]
<img width="75%" src="https://user-images.githubusercontent.com/35271042/69371946-a8aec180-0c55-11ea-9ad2-d0b12c1bd6d1.png" />

Create a warning in your settings file, let that get synced a few times, and notice that the problems panel keeps showing all of the temp files with the warning. 

Clicking on a file goes to:

![image](https://user-images.githubusercontent.com/35271042/69371871-874dd580-0c55-11ea-8b9d-22330349b2c3.png)

**Comment by sandy081** [comment]
Currently I am creating a temporary text model for merging which is causing for these errors. I am planning to move away from this and merge content without using model just like how keybindings merge is doing. Since it is a bigger change moving to December.
