### ISSUE TITLE
Expand all/collapse all directories in Explorer

### ISSUE THREAD

**Issue by omcnoe** [microsoft/vscode#85334]
Would be great to have a right click option to expand/collapse all directories in the file explorer. If you open too many directories, it's painful to go through & collapse them manually all one at a time.

**Comment by misolori** [comment]
We have a "collapse all" action in the explorer, as well as an action in the command palette, will this solve your issue?

![image](https://user-images.githubusercontent.com/35271042/69378892-2c6faa80-0c64-11ea-93f0-7c86c626ed1e.png)

![image](https://user-images.githubusercontent.com/35271042/69378954-4a3d0f80-0c64-11ea-8b24-40c16a5a993d.png)

**Comment by omcnoe** [comment]
Aha I had not even noticed that button on the UI...
