### ISSUE TITLE
Can't resize from some places on the top bar

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85339]
Issue Type: <b>Bug</b>

I can no longer resize the window from some places on the top bar:
![image](https://user-images.githubusercontent.com/641685/69380411-5b941500-0c80-11ea-84f9-4ae080a2ef71.png)

This doesn't seem to be all that reproducible. When it happened though, the devtools showed that the `resizer` element was hidden (`display: none`).

/cc @sbatten 

VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:43:20.960Z)
OS version: Windows_NT x64 10.0.19028

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.45GB free)|
|Process Argv|--enable-proposed-api eamodio.remotehub|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sbatten** [comment]
@eamodio the resizer gets modified when the menu is open and closed. not sure what's happening here but maybe that info can help you get an easy repro?

**Comment by adrianp97** [comment]
What exactly is the VsCode menu? We are trying to reproduce this bug as well.

**Comment by sbatten** [comment]
@adrianp97 the menu referring to file, edit, selection, etc. This is specific to Windows (or Linux if you enable the custom menu in settings.)

**Comment by eamodio** [comment]
@sbatten Yeah, unfortunately I haven't been able to get it to happen since I reported it (and it only happened 2 times)

**Comment by sbatten** [comment]
closing for now, please re-open if seen again.
