### ISSUE TITLE
Allow terminal to be dragged to side panes of editor

### ISSUE THREAD

**Issue by mrfelipenoronha** [microsoft/vscode#85346]
If the terminal could be placed as a side panel, just like a normal file, this possibility would improve the experience of people who get a lot of logs and longs reports on terminal. Particularly I feel very limited of just being able to see a fraction of the terminal in the bottom of the monitor (the other option is to make the terminal occupy the whole screen) and by having the option to drag it to the right side, for exemple, would make the experience of dealing with code and terminal output would be much more pleasant.

**Comment by mrfelipenoronha** [comment]
Also, I know we can use the `toggle panel position` option, but I can not make this action happen by dragging the terminal tab itself.

**Comment by egamma** [comment]
duplicate
