### ISSUE TITLE
VS Code gets into bad state after debugging extension with tasks 0.1.0

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#85343]
Issue Type: <b>Bug</b>

**Repo**
1. In a old extension that is still using `tasks.json` 0.1.0:

```jsonc
// Available variables which can be used inside of strings.
// ${workspaceRoot}: the root folder of the team
// ${file}: the current opened file
// ${fileBasename}: the current opened file's basename
// ${fileDirname}: the current opened file's dirname
// ${fileExtname}: the current opened file's extension
// ${cwd}: the current working directory of the spawned process

// A task runner that calls a custom npm script that compiles the extension.
{
    "version": "0.1.0",

    // we want to run npm
    "command": "npm",

    // the command is a shell script
    "isShellCommand": true,

    // show the output window only if unrecognized errors occur.
    "showOutput": "silent",

    // we run the custom script "compile" as defined in package.json
    "args": ["run", "compile", "--loglevel", "silent"],

    // The tsc compiler is started in watching mode
    "isBackground": true,

    // use the standard tsc in watch mode problem matcher to find compile problems in the output.
    "problemMatcher": "$tsc-watch"
}
```

2. Start debugging the extension using f5
1. Stop debugging (using UI).
1. Notice that you cannot close the VS Code window and that the reload command no longer works. Also, trying to start debugging never completes

VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:39:56.671Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 6, 4|
|Memory (System)|16.00GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-asciidoc-vscode|bch|0.0.7
color-info|bie|0.5.1
comment-tagged-templates|bie|0.3.0
emojisense|bie|0.5.3
folder-source-actions|bie|0.2.0
github-markdown-preview|bie|0.0.2
lit-html|bie|1.11.1
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-image-size|bie|0.0.4
markdown-mermaid|bie|1.4.1
markdown-preview-github-styles|bie|0.1.6
markdown-shiki|bie|0.1.1
markdown-yaml-preamble|bie|0.0.4
speech|bie|0.0.3
vscode-intelephense-client|bme|1.2.3
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
php-debug|fel|1.13.0
php-pack|fel|1.0.2
vscode-pull-request-github-insiders|Git|2019.11.2342
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.15.3
theme-monokai-pro-vscode|mon|1.1.14
vscode-azurefunctions|ms-|0.20.0
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.2
vscode-language-pack-de|MS-|1.40.2
vscode-language-pack-zh-hans|MS-|1.40.2
python|ms-|2019.11.49689
remote-containers|ms-|0.85.0
remote-ssh-edit-nightly|ms-|2019.11.21120
remote-ssh-nightly|ms-|2019.11.21120
remote-wsl|ms-|0.41.0
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
github-issues-prs|ms-|0.9.2
Go|ms-|0.11.9
powershell|ms-|2019.11.0
vscode-typescript-next|ms-|3.8.20191120
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
live-server-preview|neg|0.1.4
material-icon-theme|PKi|3.9.1
polacode|pnp|0.3.4
ruby|reb|0.26.0
shader|sle|1.1.4
stackery|sta|1.0.7
code-spell-checker|str|1.7.20
ayu|tea|0.18.0
sort-lines|Tyr|1.9.0
vscode-ruby|win|0.26.0
material-theme|zhu|3.0.3

(15 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Also repos with VS Code 1.40.1 with --disable-extensions

**Comment by mjbvz** [comment]
Seems related to using tasks 0.1.0. After upgrading to tasks 2.0, I can't repo this

**Comment by isidorn** [comment]
@alexr00 since chaning tasks version seem to fix, can you first look into this and drag me into the investigation if needed?

**Comment by alexr00** [comment]
Yes, this looks like a tasks issue.

**Comment by alexr00** [comment]
@mjbvz  I'm not able to reproduce the issue. Can you share the repo that you're using? I changed a task to be 0.1.0:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    // we want to run npm
    "command": "npm",
    // the command is a shell script
    "isShellCommand": true,
    // show the output window only if unrecognized errors occur.
    "showOutput": "silent",
    // we run the custom script "compile" as defined in package.json
    "args": [
        "run",
        "watch"
    ],
    // The tsc compiler is started in watching mode
    "isBackground": true,
    // use the standard tsc in watch mode problem matcher to find compile problems in the output.
    "problemMatcher": "$ts-webpack-watch"
}
```
I also tried with another extension that just used `$tsc-watch` I could F5, see the prelaunch task run, then debug. I could also stop with the UI.

**Comment by alexr00** [comment]
I could repro the only debug once issue, though I couldn't repro the other problems. I pushed a fix to the problem I could see. Please let me know if it fixes it!

**Comment by mjbvz** [comment]
Seems like that fixed the other issue for me. Thanks!
