### ISSUE TITLE
jupyter notebook Variable explorer and data viewer

### ISSUE THREAD

**Issue by Solomoons-ds** [microsoft/vscode#85349]
Issue Type: <b>Bug</b>

I usually use jupyter notebook in vscode but suddenly It can not show the Variable explorer and data viewer when I click on it . I think it was crashed or something changed
One more thing that, I see the UI of jupyter notebook changed , is not it ? all the button below the cell change to another place and it seem uncomfortable when using

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
bracket-pair-colorizer|Coe|1.0.61
prototxt|dmi|0.0.6
python-extension-pack|don|1.6.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.8.0
code-runner|for|0.9.15
gc-excelviewer|Gra|2.1.32
Python-autopep8|him|1.0.2
kite|kit|0.101.0
MagicPython|mag|1.1.0
git-graph|mhu|1.18.0
python|ms-|2019.11.50794
neuron-IPE|neu|1.0.4
swdc-vscode|sof|1.2.5
pdf|tom|0.5.1
errorlens|use|2.7.2
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0

(7 theme extensions excluded)

</details>

**Comment by misolori** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
