### ISSUE TITLE
Extension being run locally despite extensionKind: ["workspace"]

### ISSUE THREAD

**Issue by rundquist** [microsoft/vscode#85340]
- VSCode Version: 1.41.0-insider Commit 4934a6f487b9ed6b99b900ae0710c7b452792e20
- OS Version: Linux x64 4.15.0-70-generic

While I'm specifically concerned about the [extension](https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode) I help maintain I'm going to assume that this applies to any extension that doesn't automatically load in the correct execution location.

Steps to Reproduce:

1. Install an extension that requires being run remotely but that would be run locally if it weren't for `extensionKind: ["workspace"]` being added to `package.json`.
2. Open a remote development environment.
3. Open the Extensions sidebar and see that the extension is loaded locally.

Previously adding `extensionKind: ["workspace"]` to `package.json` solved this problem and that solution continued to work up to and including commit 29b99f85e54aa5af6cd4edf918a67d4f70a10aea.

**Comment by egamma** [comment]
@rundquist we maintain a list of extensions that based on testing we defined as UI extensions. Your extension is currently on this list. Have you tested that your extension works as a "workspace" extension in the remote context then we will remove your extension from this list.

**Comment by rundquist** [comment]
Yes, we've run the extension as a workspace extension and it works. Since it relies on the Git extension it doesn't work as a UI extension. This change was brought to our attention by users because our extension stopped working for them because it was no longer being run in the remote environment.

**Comment by egamma** [comment]
I've removed your extension from the UI extension list. The fix will be available in the insider version next Monday. Can you please confirm that everything is OK.

**Comment by rundquist** [comment]
I've confirmed that everything works in the latest release of Insiders. Thanks for helping us get this resolved!
