### ISSUE TITLE
VSCode failed to update extensions!

### ISSUE THREAD

**Issue by AmericanY** [microsoft/vscode#85348]
Here's my VSCode details :

Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Check attached screenshot and let me know what is causing that issue please !

![Capture](https://user-images.githubusercontent.com/27644047/69394194-00940980-0ce4-11ea-956e-e8855f1e9fd2.PNG)

**Comment by egamma** [comment]
/needsMoreInfo does this only happen for this particular extension? Does it also happen for other extensions.

**Comment by AmericanY** [comment]
@egamma yea it's happens for all !

Failed to update 'ms-python.python'.
Failed to update 'formulahendry.code-runner'.

**Comment by AmericanY** [comment]
issue resolved by changing `DNS` after verifying that i were unable to access [https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default](url)
