### ISSUE TITLE
Dropdown in e.g. Output or Terminal don't respond correctly to touch

### ISSUE THREAD

**Issue by biste5** [microsoft/vscode#85342]
- VSCode Version: 1.40.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:
Use a touch screen, in my case from MS Surface Pro 6
1. In Output window, open the dropdown to switch between 'Tasks', 'Extensions'
2. Trying to select an item by tap doesn't respond correctly
3. Holding on an item does select it, but that can't be committed neither with 'Enter' key on keyboard 

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
The output window uses the custom dropdown. Which shuold in theory work with the touch device so fyi @cleidigh 
Also fyi @rebornix since he was looking into touch devices if I am not mistaken.
