### ISSUE TITLE
Debugger: Wrong current line in source map with inlined source

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8534]
Test item #8193 
- VSCode Version: aweinand/asyncsourcemaps: Code - Insiders 1.3.0-insider (392b89ffeebbc51a8574142f9629ff4a6eac15b9, 2016-06-27T22:37:58.724Z)
- OS Version: Linux x64 3.13.0-34-generic

Steps to Reproduce:
1. Open Code with an extension project
2. Place breakpoint in 'activate' function of the extension
3. Start debugging
4. When the breakpoint is hit, step out
5. Now the current line (correctly) is on TPromise.as(...):
   try {
       return TPromise.as(extensionModule.activate.apply(global, [context]));
   } catch (err) {
       return TPromise.wrapError(err);
   }
6. Step in -> Correctly steps into TPromise.as()
7. Step out -> Correctly steps out of TPromise.as(), but incorrectly shows the current line on TPromise.wrapError(...)
8. Step in -> Correctly leaves the function (verifies we're not actually in the 'catch' case)

**Comment by weinand** [comment]
Should work now.
