### ISSUE TITLE
"Find in Folder" does not correctly fill includes filter when folder name contains [](){}

### ISSUE THREAD

**Issue by dalongi** [microsoft/vscode#85345]
Context: I was trying to build an extension which uses the workspace folder "name" field to help differentiate similar workspace folders.

It attempts to prefix a folder names using a pattern like "[Foo] folderName"

When this prefix exists, right click -> "Find in Folder..." does not behave as expected. The results are not filtered in any way, even though the UI shows an "includes" filter.

This seems to be related to how VS Code tries to parse the includes filter (which contains the custom folder name) into a Glob: https://github.com/microsoft/vscode/blob/f3e4e47164104192b9e3f8caca93ed2cdfdac5dc/src/vs/workbench/contrib/search/common/queryBuilder.ts#L448

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/16834
