### ISSUE TITLE
Use the status bar when Settings Sync is syncing?

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#85351]
I've noticed that the badge on the gear is very distracting as it pops on and off when sync is happening:

![image](https://user-images.githubusercontent.com/35271042/69397984-1af6c480-0c9d-11ea-85c8-a7960c144f6f.png)

It also took me a while to figure out that it was from the Setting Sync, I clicked into the gear hoping for an entry that would indicate was happening and saw nothing. I then had to hover on the badge to see the tooltip (which I don't think anyone would figure out). 

Should we use status bar instead for this? It's less intrusive and easier for it to appear/disappear when syncing is happening. I'd imagine we'd still use the badge for higher priority stuff like merge conflicts.

![image](https://user-images.githubusercontent.com/35271042/69397889-c3f0ef80-0c9c-11ea-88ee-b97c181483d2.png)

@RMacfarlane @Tyriar thoughts?

**Comment by Tyriar** [comment]
I'd think it would be more distracting in the status bar. Plus currently all sync stuff is accessed via the gear menu and the clock currently means updating (making a network request).

It does bring up the question to me though of how often does it actually show up? I'm not sure we should be surfacing anything on regular syncs.

**Comment by RMacfarlane** [comment]
Generally, I would prefer status notifications like this to be in the status bar so that I can easily read them.

I think I've only seen the clock icon with settings sync while in the middle of sign in, which makes sense to me. For me, the clock icon is easiest to understand when it's either triggered by a manual action (I start sign in, I check for updates), or when it results in some other icon on the gear (update downloads in background, then indicator is shown to restart). If it appears and disappears with no context, I don't know what it's trying to indicate or what to do with that information.

**Comment by Tyriar** [comment]
I'd argue the user doesn't need to see it at all, outside of the initial sync after sign in and if we add a manual sync command. Showing something on a regular period sync would just be a distraction.

**Comment by misolori** [comment]
I disagree, otherwise how else does a user know that sync is working? I think you could make this an option but I would show it by default. These indicators are what establish confidence with the user that it's working.

**Comment by Tyriar** [comment]
@misolori why would we tell the user every 5 minutes "hey there, I'm still working"? Wouldn't it be better to only bother the user when it's not working and/or when the user explicitly requests a sync?

**Comment by misolori** [comment]
I could see how it showing up every 5min would be really annoying. I think we'd still need some way to indicate to users that it's working or show when it was last synced somewhere.

**Comment by Tyriar** [comment]
@misolori I'd prefer a conflict or error icon on the gear menu just when something went wrong.

**Comment by sandy081** [comment]
I am also not a big fan of showing in the status bar given that it is a global activity and we use global activity icon for such purpose.

This activity is not just about syncing but also include signing in, refreshing token and syncing/merging.  It would be noise if we show detail progress in status bar. At the same time I agree that we shall be less aggressive and show it only when it takes more time.

**Comment by sandy081** [comment]
Delayed showing progress and is shown if syncing takes more than 1s.
