### ISSUE TITLE
workbench.action.navigate[] not working with Python interactive

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#85350]
Issue Type: <b>Bug</b>

Once I start Python interactive mode I'm unable  to navigate left/right/up/down using workbench.action.navigate[] commands. I'm in VSCode insiders. 

VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:39:56.671Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_3293988|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.1.5
vscode-database|baj|2.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.32.0
gitlens|eam|10.2.0
LogFileHighlighter|emi|2.6.0
shell-format|fox|6.1.3
seito-openfile|Fr4|1.8.5
mdmath|goe|2.4.0
gc-excelviewer|Gra|2.1.32
open-file-from-path|jac|1.3.3
latex-workshop|Jam|8.4.1
vsc-space-block-jumper|jmf|1.2.2
center-editor-window|kai|2.3.0
vscode-docker|ms-|0.8.2
python|ms-|2019.12.49019-dev
sqltools|mtx|0.21.3
neuron-IPE|neu|1.0.4
vscode-ipython|pan|0.5.0
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.6.1
vscode-dired|rru|0.0.4
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.0
emacs-mcx|tut|0.13.0
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0
org-mode|vsc|1.0.0
highlight-trailing-white-spaces|yba|0.0.2
markdown-all-in-one|yzh|2.5.1

</details>

**Comment by egamma** [comment]
Please file the issue against the python extension.
