### ISSUE TITLE
Sometimes search does not work

### ISSUE THREAD

**Issue by HUSEN88** [microsoft/vscode#85356]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ThirtySomething** [comment]
I've detected this bug also analyzing some logfiles. I'm running

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

To reproduce the bug:
1. Navigate in Windows Explorer to the folder of the log files.
2. Right click and select "Open with Code"
3. Open search dialog with CTRL + SHIFT + F
4. Enter search phrase in search box and press enter
5. The search starts but presents no results.

There are no options like "Match Case", "Match Whole Word" or "Use Regular Expression" activated.
The field for "files to include" is empty.
The field for "files to exclude" is empty.
The settings for "Files: Exclude" and "Search: Exclude" are the default settings.

The couple of files I'm searching are really plain text files.
They have extensions like ".pro", ".log", ".loge", ".logf", ".logk" or ".err".
The content is definitely available in one of these files.
A crosscheck with Notepad++ found the pattern.

When the file is opened in VSC, the file-search will find all occurences.

The concrete file has a file name like "file.name.pro" - there is more than one dot in the filename.

Is there a way to provide some kind of logfile for analysis?

Best regards

Jochen

**Comment by egamma** [comment]
@ThirtySomething this is great information but please file a separate issue, it is not clear that it is the same issue.
