### ISSUE TITLE
Quick switch fonts for every edit pages.

### ISSUE THREAD

**Issue by inf1nityhhd** [microsoft/vscode#85354]
I write mark down, HTML and python. All three are use Consolas font, but I really want every page could using  different fonts, and can quickly switch in the bottom of the editor. Just like switching the compiler. I think this function is lacking in VSCODE. VSCODE is a good editor, but every time when I want to switch the font I would go to changes in the panel.
Sorry,My English is poor..but I think you will know it.

**Comment by alexandrudima** [comment]
@inf1nityhhd You can use language specific settings in your `settings.json`:
```
"editor.fontFamily": "Consolas",
"[html]": {
  "editor.fontFamily": "Hack",
},
"[markdown]": {
  "editor.fontFamily": "Arial",
}
```
