### ISSUE TITLE
No code suggestions when filling C++ extension snippets blanks

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode#85352]
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic (Ubuntu 18.04.3 LTS)

Steps to Reproduce:

1.  type `if`;
2. choose `if` snippet from the code suggestions;
3. type variables (or funtions, snippets ...) in the first blank which is `/* condition */`;
4. there's no code suggestions when typing ...

Does this issue occur when all extensions are disabled?: 
the code snippets are provided by **C++ Extension**, so no ...

**Comment by egamma** [comment]
Please file the issue against the C++ extension
