### ISSUE TITLE
Open files that are in files.watcherExclude no longer update when contents change on disk

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85361]
Issue Type: <b>Bug</b>

Steps:
1. Open a file that is in `files.watcherExclude` -- I opened a `package.json` file inside of `node_modules`
1. Change that file outside of vscode
1. VS Code won't see the change

This works fine in 1.40.1.

VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:43:20.960Z)
OS version: Windows_NT x64 10.0.19028

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.73GB free)|
|Process Argv|--enable-proposed-api eamodio.remotehub|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by egamma** [comment]
(assigning to @Tyriar since @bpasero is out of office)

However, this looks like the correct behaviour and 1.40.1 didn't honor the setting correctly. Since the file is not being watched, VS Code will not be notified about the change.

**Comment by eamodio** [comment]
I assumed that setting would not apply if the document is open in an editor. Mainly because it's not a good experience (and it took me a while to even figure out it was because of that setting - which is defaulted too)

**Comment by Tyriar** [comment]
Somewhat related to this, the refresh button doesn't show gitignored files under node_modules:

<img width="254" alt="Screen Shot 2019-11-22 at 6 52 49 PM" src="https://user-images.githubusercontent.com/2193314/69471948-8f8f3900-0d59-11ea-8b31-3e527b413dc0.png">

<img width="237" alt="Screen Shot 2019-11-22 at 6 52 56 PM" src="https://user-images.githubusercontent.com/2193314/69471950-9158fc80-0d59-11ea-9908-250a128650a4.png">

**Comment by Tyriar** [comment]
This could have caused this weirdness with theme not being what is in settings.json https://github.com/microsoft/vscode/issues/85435

**Comment by Tyriar** [comment]
Adding @jrieken and @deepak1556 in case you know anything about recent changes in file watching, something seems to be very wrong and I haven't touched it in months.

**Comment by Tyriar** [comment]
I think this was also blocking settings sync from working until I restarted the entire application.

**Comment by Tyriar** [comment]
I'm also seeing it on Windows:

Version: 1.41.0-insider (user setup)
Commit: 599c076d91be1374cf51004cec610f3bcaf4c9cd
Date: 2019-11-22T07:25:24.031Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by deepak1556** [comment]
The only node change that went between the stable and insiders was https://github.com/electron/electron/pull/21141 , which doesn't touch file watching. I verified no other changes came in from electron side.

**Comment by eamodio** [comment]
This also applies to `settings.json` too.

**Comment by deepak1556** [comment]
@Tyriar did bisect reveal what caused the regression ?

**Comment by Tyriar** [comment]
I didn't try to bisect, also I haven't been seeing this as much, might be related to me working in WSL/mac though?

**Comment by deepak1556** [comment]
@eamodio if you are still observing this then it would be great if you can run a git bisect to narrow down the cause of regression. Thanks!

**Comment by eamodio** [comment]
@deepak1556 I can't seem to reproduce this anymore. It seems to be working as I'd expect.
