### ISSUE TITLE
IntelliSense can't active HTML DOM Style Object in JavaScript

### ISSUE THREAD

**Issue by GHC-6** [microsoft/vscode#85360]
Issue Type: <b>Feature Request</b>

![1](https://user-images.githubusercontent.com/39327091/69403894-bf791500-0d36-11ea-81e0-072b3599c1c6.gif)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment]
/question

This is expected TS (and JS) behavior.
`cloneNode` returns object with `Node` type and `Node` doesn't have `style` and bunch of other attributes that are specific to `Element`s.

You need to explicitly add JSDoc to specify type of element that will be in `copyEle` (no way to guess it is paragraph, link, div, or anything else.

```js
/**
 * @type {HTMLAnchorElement}
 */
const copyEle = document.querySelector('.elem').cloneNode();
```
![image](https://user-images.githubusercontent.com/1312662/69415337-170a8700-0d1d-11ea-9a29-0e76c40f4a1c.png)

Replace `HTMLAnchorElement` with type of element that you have.


Please let developer know if you are sure if this is closed by a mistake and provide more details.

**Comment by IllusionMH** [comment]
Also you can check related https://github.com/microsoft/TypeScript/issues/283 that should allow more specific return type for `cloneNode`
