### ISSUE TITLE
Processes still exists after quitting VSCode 

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#85363]
macOS, VSCode 1.40.1

<img width="484" alt="123" src="https://user-images.githubusercontent.com/11925432/69405655-31535d80-0d3b-11ea-94ed-cd5286696304.png">

**Comment by egamma** [comment]
What extensions are you using?

To understand what kind process are leaking pls run `code --status` during development.

**Comment by kzhui125** [comment]
Python extension

This is the second time I meet this problem, and I have to kill these processes in terminal.

I can't reproduce now.

Next time I will try to run code --status, thanks.
