### ISSUE TITLE
avoid absolute paths in workspace files

### ISSUE THREAD

**Issue by davidhewitt** [microsoft/vscode#85366]
- VSCode Version: 1.40.1
- Local OS Version: Windows 10 Insiders Build 19023
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Create a workspace in Windows with multiple root folders, e.g. `C:/Users/david/dev/foo` and `C:/Users/david/dev/bar`
2. Save the workspace
3. Execute the `Reopen in WSL` command. The folders cannot be found, because the workspace paths are translated into e.g. `/C:/Users/david/dev/foo`, but the correct translation should be `/mnt/c/Users/david/dev/foo`

As a workaround my workspace has two copies of each folder; `C:/Users/david/dev/foo` and `/mnt/c/Users/david/dev/foo`. One folder works in Windows, the other in WSL.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by davidhewitt** [comment]
I created the workspace file through the GUI. ("Add Folder to Workspace..." context menu option in the explorer panel.)

I saved the workspace file in a folder `C:/Users/David/dev/workspaces` - a sibling of the referenced folders.

**Comment by aeschli** [comment]
dup of #83156
