### ISSUE TITLE
We are not getting the no of references above the terraform resource

### ISSUE THREAD

**Issue by paramanandd** [microsoft/vscode#85375]
We are not getting the no of references above the terraform resource which shows how many places the resource is reffered for version 1.40.1

**Comment by paramanandd** [comment]
![Capture](https://user-images.githubusercontent.com/19427315/69414472-d7519880-0d38-11ea-84ce-c85f343410c4.PNG)

I want to specify the no of references where this resource is reffered but i cant find it

**Comment by paramanandd** [comment]
i have created the blue line where the desired output is "4 references" but not visible

**Comment by paramanandd** [comment]
CodeLens support is not visible

**Comment by egamma** [comment]
This indicates that the Terraform extension does not support the codelens feature. Please file an issue against the Terraform extension you are using.

**Comment by paramanandd** [comment]
where should i do that
