### ISSUE TITLE
Smoke test: verifies that 'Go To Definition' works

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#85377]
1) Running Code
       Editor
         verifies that 'Go To Definition' works:
     Error: Timeout: get text content 'div.monaco-quick-open-widget .quick-open-tree .monaco-tree-row.focused .monaco-highlighted-label' after 20 seconds.
      at /home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:8:58)

**Comment by jrieken** [comment]
I have removed those tests.
