### ISSUE TITLE
Folders not showing in the Explorer

### ISSUE THREAD

**Issue by SkrupSulten** [microsoft/vscode#85371]
- VSCode Version: 1.41.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project folder with a capital letter in its name
2. Delete a folder
3. Discard your changes (restore the folder)
4. Open a file within the restored folder
5. Most folders won't show in the explorer, while you have that file opened.
6. Hover the mouse over the file tab and see that the project folder is spelled with all lower case

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
We do not have version: 3.7.3-insiders.20191118
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please attach a short gif illustrating your problem? Thank you

**Comment by SkrupSulten** [comment]
> We do not have version: 3.7.3-insiders.20191118
> Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
> If yes, can you please attach a short gif illustrating your problem? Thank you

Sorry I reported the VS Code version wrong. It is the latest version 1.41.0-insider.

If I open my package.json file Explorer looks like this (note that I can see the src folder among others)
![image](https://user-images.githubusercontent.com/53522466/69416970-19b6ad80-0d18-11ea-9096-523367ad5e9f.png)
![image](https://user-images.githubusercontent.com/53522466/69417317-bb3dff00-0d18-11ea-8b82-ab8825f68139.png)

If I open a file I deleted and restored I cannot see those folders:
![image](https://user-images.githubusercontent.com/53522466/69416905-f8ee5800-0d17-11ea-8658-d90843b191d6.png)

See that VS Code thinks the file is located in "nemex" with lower case (might/might not be the issue):

![image](https://user-images.githubusercontent.com/53522466/69417192-74e8a000-0d18-11ea-9060-ac5a56b84394.png)

**Comment by isidorn** [comment]
Is this a new behavior you are seeing that started a couple of days ago or you are not sure if it ever worked?
I will try to repro on my Windows VM..
fyi @Tyriar for file watcher

**Comment by SkrupSulten** [comment]
I don't know if it's a new issue. I only just started using the insiders version a week ago or so.

**Comment by SkrupSulten** [comment]
Hi @isidorn 
Could you link the duplicate issue? I'm just curious :)
