### ISSUE TITLE
Should Goto > Switch Editor Group > Side Group be Center Group?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8537]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 7

Should Goto > Switch Editor Group > Side Group be Goto > Switch Editor Group > Center Group to match OPEN EDITORS LEFT, CENTER, and RIGHT grouping?

**Comment by bpasero** [comment]
@gregvanl we cannot do this because depending on the number of opened editors the side editor can either be CENTER or RIGHT so we ended up with SIDE editor.
