### ISSUE TITLE
Proxy works partially with extensions marketplace

### ISSUE THREAD

**Issue by jipipayo** [microsoft/vscode#85379]
- VSCode Version: 1.38.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Setup proxy settings with your corporate http proxy.

2. If you use "ext:git" it works and you get a lot of extensions coming from the marketplace
3. If you just type "git" you endup with this error message: We cannot connect to the extensions market at this time. please try again later.

Does this issue occur when all extensions are disabled?: Yes

these are the results of the proxy tool test :

| Test | Status | Hash or Error |
|---|---|---|
| HTTP XHR | 200 | af0c95ab552cfbdb440cd9763c61f27e87672d1d |
| HTTPS XHR | 200 | b37e90a496341ef8227aeda8f42ccca1cb698b98 |
| HTTP Node | 0 | Timeout |
| HTTPS Node | 0 | Timeout |
| HTTP Node (not strict) | 0 | Timeout |
| HTTPS Node (not strict) | 0 | Timeout |
| HTTP Node Agent | 403 | 2b43e8f5d2a104ec51b9a6283a76970a3efa884c |
| HTTPS Node Agent | 403 | 062efaf527d635dc312622be051423d14a2c7aca |
| HTTP Node Agent (not strict) | 403 | 2b43e8f5d2a104ec51b9a6283a76970a3efa884c |
| HTTPS Node Agent (not strict) | 403 | 062efaf527d635dc312622be051423d14a2c7aca |
| HTTP Electron | 200 | 1ec6bf5e0261cf1c397e563a7aa1caaf288712a5 |
| HTTPS Electron | 200 | 718211d2f5abb2f104d53707dfbaec30e1841aa0 |

Parent issue: https://github.com/microsoft/vscode/issues/85370#issuecomment-557842560

**Comment by chrmarti** [comment]
@jipipayo Thanks for providing test results. Could you provide more details on how you did the various tests?

**Comment by jipipayo** [comment]
I did the tests using the searchbox, in this 1 picture you can see i get results if i type "ext:gif"

![image](https://user-images.githubusercontent.com/1165/69638025-31649d80-105a-11ea-84f2-23969bcd2f54.png)

In this other picture you can see there is no search results if just simple type "git"

![image](https://user-images.githubusercontent.com/1165/69638201-86a0af00-105a-11ea-93e4-0d9156a1d037.png)

**Comment by chrmarti** [comment]
@sandy081 Why is the UI not always working / not working? Is this maybe a different issue?

@joaomoreno The test results suggest that the viewlet should work, don't they?

**Comment by joaomoreno** [comment]
Yup, I believe proxy isn't the issue here. There must be something else, since queries like `git @sort:rating` just work.

**Comment by sandy081** [comment]
Can you please open developer tools and show us the network requests for each case?
