### ISSUE TITLE
Add a test proxy button

### ISSUE THREAD

**Issue by jipipayo** [microsoft/vscode#85370]
I can not connect to the extensions marketplace.
Never was able to connect from our corporate network, even setting a proxy, i can not test it, i can not figure out if this proxy is ok or not, please add a TEST proxy button with some connection feedback info: success, failed, some trace output..
 That would be helpful for people behind corporate networks.

**Comment by egamma** [comment]
There is extensive documentation about setting up a proxy, pls see https://code.visualstudio.com/docs/setup/network#_proxy-server-support.

**Comment by egamma** [comment]
Also pls see this issue https://github.com/microsoft/vscode/issues/18103 it comes with a tool to test a proxy.

**Comment by egamma** [comment]
If there is something missing in the documentation, or if you proxy setup doesn't work after having gone through this documentation then please file a separate issue.

**Comment by jipipayo** [comment]
I ran the tests with the tool from #18103 , but i can not post the results on this thread, is closed.

**Comment by egamma** [comment]
@jipipayo please open a new issue.
