### ISSUE TITLE
TypeError: 'builtin_function_or_method' object is not subscriptable

### ISSUE THREAD

**Issue by j-a-lewis** [microsoft/vscode#85380]
Issue Type: <b>Bug</b>

If I run the debugger, there is no problem with the code but if I try to execute the code, the compiler or whatever flags an error.  Renaming the variable allowed the program to begin executing with no warnings.  Then I typed in some code else in the function and the error returned with no change at all to the line being flagged.  I have created a similar code line with different arrays and different variable names for the arrays and that's not flagged at all.  I have used similar code lines in other related Python scripts with no problem.  I would attach the whole .PY file but the area for drag 'n drop went away and I don't see any 'button' to attach files.  If I get a follow-up window allowing another post, I'll attach the complete file to that.

The problem is with the variable Vprev[next_state_num] below in the FOR TRANS IN TRANSITIONS: LOOP

def policy_eval_two_array(state_count, gamma, theta, pi, get_transitions):
        """
        This function uses the two-array approach to evaluate the specified policy for the specified MDP:
        
        'state_count' is the total number of states in the MDP. States are represented as 0-relative numbers.
        
        'gamma' is the MDP discount factor for rewards.
        
        'theta' is the small number threshold to signal convergence of the value function (see Iterative Policy Evaluation algorithm).
        
        'get_policy' is the stochastic policy function - it takes a state parameter and returns list of tuples, 
            where each tuple is of the form: (action, probability).  It represents the policy being evaluated.
            
        'get_transitions' is the state/reward transiton function.  It accepts two parameters, state and action, and returns
            a list of tuples, where each tuple is of the form: (next_state, reward, probabiliity).  
            
        """
        #JAL: change variable from V to Vold
        Vprev = np.zeros(state_count)
        
        
        #
        # insert code here to evaluate the policy using the in-place approach 
        #
        while True:

            # global iter_count
            # Ev += 1
        
            
            
            
            delta = 0

            for state in range(state_count):
                action = pi[state]

                Vnew = np.zeros(state_count)
                

                transitions = get_transitions(state=state, action=action)

                for trans in transitions:

                    next_state_num, reward, probability = trans
                    Vnew[state] = reward + gamma * Vprev[next_state_num]
                    

                delta = max (delta, abs(Vnew[state] - Vprev[state]))
            Vprev = Vnew.copy

            

            if delta < theta :
                break

        #
        # INSERT CODE HERE to evaluate the policy using the 2 array approach 
        #

        #JAL: change variable from V to Vold
        return list(Vprev)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.68GB (3.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
vscode-yaml|red|0.6.1

</details>
``

**Comment by j-a-lewis** [comment]
Complete Python file, not bug-free since I had an endless loop when I tried to execute before the object not subscriptable error popped up.
`# had to do "File, Download (as .Py),"" from a running Anaconda .IPYNB version of file" to get this script
# will try two ways, first by "in-place" policy evaluation, then, in a separate .Py file, by the two-array policy
# evaluation method

#!/usr/bin/env python
# coding: utf-8

# # DAT257x: Reinforcement Learning Explained
# 
# ## Lab 4: Dynamic Programming
# 
# ### Exercise 4.3 Policy Iteration

# Policy Iteration calculates the optimal policy for an MDP, given its full definition.  The full definition of an MDP is the set of states, the set of available actions for each state, the set of rewards, the discount factor, and the state/reward transition function.

# In[1]:


import test_dp               # required for testing and grading your code
import gridworld_mdp as gw   # defines the MDP for a 4x4 gridworld
import numpy as np           # needed for np.argmax extraction


# **Implement the algorithm for Policy Iteration**.  Policy Iteration calculates the optimal policy for an MDP by doing repeated steps of policy evaluation and policy improvement.
# 
# A empty function **policy_iteration** is provided below; implement the body of the function to correctly calculate the optimal policy for an MDP.  The function defines 5 parameters - a definition of each parameter is given in the comment block for the function.  For sample parameter values, see the calling code in the cell following the function.
# 
# Note that there is a subtle difference between the algorithm for Policy Evaluation, which assumes the policy is stochastic, and the Policy Evaluation step for the Policy Iteration algorithm, which assumes the policy is deterministic.  This means that you cannot directly call your previous code, but you can reuse large pieces of it for the Policy Evaluation step.

# In[ ]:


def policy_eval_two_array(state_count, gamma, theta, pi, get_transitions):
        """
        This function uses the two-array approach to evaluate the specified policy for the specified MDP:
        
        'state_count' is the total number of states in the MDP. States are represented as 0-relative numbers.
        
        'gamma' is the MDP discount factor for rewards.
        
        'theta' is the small number threshold to signal convergence of the value function (see Iterative Policy Evaluation algorithm).
        
        'get_policy' is the stochastic policy function - it takes a state parameter and returns list of tuples, 
            where each tuple is of the form: (action, probability).  It represents the policy being evaluated.
            
        'get_transitions' is the state/reward transiton function.  It accepts two parameters, state and action, and returns
            a list of tuples, where each tuple is of the form: (next_state, reward, probabiliity).  
            
        """
        #JAL: change variable from V to Vold
        Vprev = np.zeros(state_count)
        
        
        #
        # insert code here to evaluate the policy using the in-place approach 
        #
        while True:

            # global iter_count
            # Ev += 1
        
            
            
            
            delta = 0

            for state in range(state_count):
                action = pi[state]

                Vnew = np.zeros(state_count)
                

                transitions = get_transitions(state=state, action=action)

                for trans in transitions:

                    next_state_num, reward, probability = trans
                    Vnew[state] = reward + gamma * Vprev[next_state_num]
                    

                delta = max (delta, abs(Vnew[state] - Vprev[state]))
            Vprev = Vnew.copy

            

            if delta < theta :
                break




        #
        # INSERT CODE HERE to evaluate the policy using the 2 array approach 
        #

        #JAL: change variable from V to Vold
        return list(Vprev)

def policy_iteration(state_count, gamma, theta, get_available_actions, get_transitions):
    """
    This function computes the optimal value function and policy for the specified MDP, using the Policy Iteration algorithm.
    'state_count' is the total number of states in the MDP. States are represented as 0-relative numbers.
    
    'gamma' is the MDP discount factor for rewards.
    
    'theta' is the small number threshold to signal convergence of the value function (see Iterative Policy Evaluation algorithm).
    
    'get_available_actions' returns a list of the MDP available actions for the specified state parameter.
    
    'get_transitions' is the MDP state / reward transiton function.  It accepts two parameters, state and action, and returns
        a list of tuples, where each tuple is of the form: (next_state, reward, probabiliity).  
    """
    
    
    def one_step_lookahead(state, V):

        actions = get_available_actions(state)

        sizeofActions = len(actions)
        i = 0

        while i < sizeofActions:

            trans = get_transitions(state, actions[i])
            [(next_state_num, reward, probability)] = trans
            actions[i] = reward + gamma * V[next_state_num]
            i += 1
            
        return actions

    
    V = state_count*[0]                # init all state value estimates to 0
    pi = state_count*[0]
    global iter_count
    
    # init with a policy with first avail action for each state
    for s in range(state_count):
        avail_actions = get_available_actions(s)
        pi[s] = avail_actions[0]
        
    # insert code here to iterate using policy evaluation and policy improvement (see Policy Iteration algorithm)
    # evaluate policy for available actions

    while True:

        V = policy_eval_two_array(state_count=n_states, gamma=.9, theta=.001, pi=pi, \
        get_transitions=gw.get_transitions)

        print(V)

        policy_stable =  True
        iter_count += 1

        # Loop over state space
        for s in range(state_count):

            #perform one-step look ahead
            action_values = one_step_lookahead(s, V)

            #maximize over possible actions 
            best_action = avail_actions[np.argmax(action_values)]

            #best action on current policy
            chosen_action = pi[s]

            #if Bellman optimality equation not satisifed
            if(best_action != chosen_action):
                policy_stable = False

            #the new policy after acting greedily w.r.t value function
            pi[s] = best_action
            # debug line myWait = 0
                    #if Bellman optimality eqn is satisfied
        if(policy_stable):
            return (V, pi)   # return both the final value function and the final policy
        if iter_count > 1:
            return (V, pi)


      


# First, test our function using the MDP defined by gw.* functions.

# In[ ]:


n_states = gw.get_state_count()
iter_count = 0

# test our function
values, policy = policy_iteration(state_count=n_states, gamma=.9, theta=.001, get_available_actions=gw.get_available_actions,     get_transitions=gw.get_transitions)

print("Values=", values)
print("Policy=", policy)
print("Inter_Count", iter_count)


# **Expected output from running above cell:**
# 
# `
# Values= [0.0, -1.0, -1.9, -2.71, -1.0, -1.9, -2.71, -1.9, -1.9, -2.71, -1.9, -1.0, -2.71, -1.9, -1.0]
# Policy= ['up', 'left', 'left', 'down', 'up', 'up', 'up', 'down', 'up', 'up', 'down', 'down', 'up', 'right', 'right']
# `

# In[ ]:


import numpy as np
a = np.append(values, 0)
np.reshape(a, (4,4))


# Now, test our function using the test_dp helper.  The helper also uses the gw MDP, but with a different gamma value.
# If our function passes all tests, a passcode will be printed.

# In[ ]:


a = np.append(policy, policy[0])
np.reshape(a, (4,4))


# In[ ]:


# test our function using the test_db helper
test_dp.policy_iteration_test( policy_iteration ) 



# %%
`

**Comment by j-a-lewis** [comment]
If I copy just the blocks of Python code to a new file in VS Code, then run the blocks via sending a code block selection to the Interactive Window, the compiler again flags the line "Vnew[state] = reward + gamma * Vprev[next_state_num]" and I know from other tests that it is the Vprev[next_state_num] that the compiler thinks is not subscriptable.  Vprev is a 1-D numpy array with state_count size of 15, same as Vnew and according to the debugger next_state_num is the integer 0 as it should be for that cell/state being tested in the OpenAI Gym GridWorld.  I will try looking at the contents of the file in various file readers to see if there is some "hidden" character from the .IPYNB file screwing things up.

**Comment by egamma** [comment]
Please file the issue against the python extension

**Comment by j-a-lewis** [comment]
It turns out that the code I used for copying one array to another changed the object type of the array.

`Vnew[state] = reward + gamma * Vprev[next_state_num]
                

            delta = max (delta, abs(Vnew[state] - Vprev[state]))
        Vprev = Vnew.copy`

Replacing the last code line with a more official np.copyto(Vprev, Vnew) fixed things up.  Also, Vprev[:] = Vnew works when using lists to avoid any object type change.

Although Python has dynamic datatypes, if pylint or whatever could look out for such things, it might help people like me who are rank coding beginners.  I guess anything that appears in the VS Code debugger is dependent on language support but maybe some interactions between VS Coders and Pythonistas could allow us to inspect our code for unfruitful data type changes.
