### ISSUE TITLE
C++ syntax highlighting broken by line break before array square bracket

### ISSUE THREAD

**Issue by valentjn** [microsoft/vscode#85385]
- VSCode Version: 1.41.0-insider (599c076d91be1374cf51004cec610f3bcaf4c9cd, 2019-11-22T07:25:24.031Z)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open a new file.
2. Change the language mode to C++.
3. Insert the following code:
```c++
#include <iostream>

int array
[42];

// this is a comment
int variable1;
int variable2;

int main() {
  std::cout << "Hello World!\n";
  return 0;
}
```
4. Observe that the syntax highlighting between `// this is a comment` and `int main() {` (both inclusive) is broken (i.e., the text is white).
5. Remove the line break between `int array` and `[42];`.
6. Observe that the syntax highlighting is normal again.

This is especially important for deeply nested arrays, when the declaration of the array becomes too long to put it on one line.

In addition, `array` is blue if there is no whitespace (line break or space characters) before the opening square bracket, and `array` is white if there is whitespace. Is this another issue?

Due to firewall restrictions I can't upload screenshots right now, sorry.

This might be related to https://github.com/microsoft/vscode/issues/76225#issuecomment-507709353 and https://github.com/jeff-hykin/cpp-textmate-grammar/issues/279.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Looks like the the folks over at https://github.com/jeff-hykin/cpp-textmate-grammar are on top of this (as usual!). Once they've merged in their fix from https://github.com/jeff-hykin/cpp-textmate-grammar/pull/423 I'll pull in the changes.

**Comment by valentjn** [comment]
@alexr00 @matter123 Great, but I think jeff-hykin/cpp-textmate-grammar#423 is not sufficient to fix this as it only seems to be about digits after the `[` (at least according to the PR title). However, this issue is independent of having a digit there, e.g.
```c++
#define ARRAY_SIZE 10

int array
[ARRAY_SIZE];

// This is a comment that won't be formatted correctly.
```
has the same problem.

**Comment by valentjn** [comment]
@alexr00 jeff-hykin/cpp-textmate-grammar#437 has been merged to master (it's not yet in the released extension). I can confirm this fixes the formatting issue 😄

**Comment by alexr00** [comment]
Excellent. I will pull in the change in a week or so.

**Comment by valentjn** [comment]
Any updates? Still open in 1.44.0.

**Comment by alexr00** [comment]
There is a different bug that is preventing us from getting the most recent grammar changes https://github.com/jeff-hykin/cpp-textmate-grammar/issues/460

**Comment by lukstep** [comment]
Hi , 

In 1.45.0-insider, C++ syntax highlighting freeze on such case:

![image](https://user-images.githubusercontent.com/20487002/80064081-8b00c380-8537-11ea-8e16-a11ec0840840.png)

**Comment by alexr00** [comment]
We have now pulled in all the recent cpp grammar changes.
