### ISSUE TITLE
Flutter Refactor Shortcut abilities

### ISSUE THREAD

**Issue by mrgnhnt96** [microsoft/vscode#85387]
Can we have the ability to apply shortcut to refactoring options? Such as wrapping a widget in a column with the shortcut "ctrl+alt+c" or something similar?
I think it would be cool to have the option to refactor it if your selecting a widget, but also if you were on a blank line to automatically insert the widget associated with the shortcut.

**Comment by egamma** [comment]
Please file the issue against the Flutter extension.
It is possible to assign key bindings to refactorings.
