### ISSUE TITLE
Goto menu title should be "Go to"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8538]
- VSCode Version:1.2.1-stable
- OS Version:Window 7

"Go to" better matches the menu commands in the menu group "Go to File..", etc.

Not sure how localization is handling "Goto" since it isn't a real word.

**Comment by bpasero** [comment]
-1, but UX decision.

**Comment by stevencl** [comment]
How about 'Go' instead? Or 'Navigate'? I don't like 'Go to' and now that Greg has pointed it out, 'Goto' isn't great either.

**Comment by bpasero** [comment]
Works for me 👍

**Comment by bgashler1** [comment]
I don't mind "Go to", but I'm fine with "Go"

**Comment by coreh** [comment]
At least for OS X, “Go” would make the most sense. Finder has that.

![](https://cloudup.com/cVQ61_WMz-Y+)

**Comment by bgashler1** [comment]
We all agreed this would be the best approach in UX sync today, and it's similar to how others do it (e.g. Mac OS X).
