### ISSUE TITLE
Regex Expression History in Document Search

### ISSUE THREAD

**Issue by alansferreira** [microsoft/vscode#85389]
Hello, first let me say this is the best IDE ever!

I use a lot of Regular Expression searches in open documents in the IDE and it would be great if VSCode kept the search history.

Thanks.

**Comment by ArturoDent** [comment]
You can up/down arrow to cycle through the history of searches in the find widget or search panel.

**Comment by IllusionMH** [comment]
As mentioned above both Find and Find in Files have <kbd>UpArrow</kbd>/<kbd>DownArrow</kbd> and <kbd>Atl</kbd> + <kbd>UpArrow</kbd>/<kbd>DownArrow</kbd> for previous and next search history entries.
![image](https://user-images.githubusercontent.com/1312662/69439877-7930af80-0d50-11ea-9cff-45871d0ce5f7.png)

_(might be a bit different for your OS, but you can search for `history.show` in Keyboard Shortcuts view)_

Are there any problems with history?

**Comment by egamma** [comment]
As @IllusionMH points out this feature is already supported. Please file a separate issue when you find problems with the current support.

**Comment by alansferreira** [comment]
I didn't know this shortcut, thanks!

Sorry about that...
