### ISSUE TITLE
ctrl+click or F12 or ALT+F12 is not working

### ISSUE THREAD

**Issue by himajaM** [microsoft/vscode#85382]
Issue Type: <b>Feature Request</b>

ctrl+click or F12 or ALT+F12 is not working, so guide me how to enable setting in visual studio code

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

**Comment by egamma** [comment]
/needsMoreInfo do the corresponding commands e.g. Go to Definition work when invoked from the context menu?

**Comment by himajaM** [comment]
No, It is not working. (e.g. Go to Definition work when invoked from the
context menu)

**Comment by egamma** [comment]
Please follow this guide for how to track down issues with keybindings https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by aodegov** [comment]
Same issue.
After update **Definition**, or **Peek definition** (by the F1 + Alt F12 click) aren't working.
Event I don't see them in context menu.
VSCode: 1.40.2
Windows 10 x64
Would be nice to clarify the problem
Thanks

**Comment by jrieken** [comment]
I what language does this happens?

**Comment by aodegov** [comment]
JS

**Comment by mjbvz** [comment]
@himajaM Please share some example code and steps to reproduce the issue

**Comment by himajaM** [comment]
I had checked in few formats ::

Eg: <i class="fa fa-trash trash_icon" (click)="delete(Id)"></i>

1)  On press ctrl+mouse click im unable to go to defination which is in
'.ts' file.
2) I had tired using above key link i.e F12
3) Tired with " GO -> GO TO DEFINATION" from visual studio code menu
4) Tired with ALT+F12

npm version : '6.9.0',
Angular CLI: 7.3.5
Node: 10.16.3
OS: win32 x64
Angular: 7.2.9

but im unable to navigate to the method which was defined in typescript
file, since it happed few months back.

Thanks in advance .

**Comment by mjbvz** [comment]
Please share a complete code example including any referenced symbols. Also describe exactly where in the code you are running `go to definition`

**Comment by aodegov** [comment]
Anywhere, where it worked before the 1.40.2 update.
that's the list of my extensions, maybe this will help:
![image](https://user-images.githubusercontent.com/24685526/70154291-f517e980-16b8-11ea-98a0-4c1b1909c345.png)

**Comment by aodegov** [comment]
I've Fixed!!! :) 
@himajaM , in my case, it's turned out that extension by default, i suppose from MS,
which is responsible for the JS / Type script was disabled.
So, what I did I went to disabled section and set up all "disabled" extensions to "enable".
And now Definition and Peek Definition are works.
And I see them into context menu:
![image](https://user-images.githubusercontent.com/24685526/70160664-8db36700-16c3-11ea-9921-35be44f942e0.png)
So please try this approach and let me know if this helps.
Thank you.

**Comment by mjbvz** [comment]
@himajaM Can you please check this as well? If it still doesn't work, please provide the additional information so that we can investigate this

**Comment by himajaM** [comment]
@aodegov I opened up the extensions pane and I have zero extensions under the disabled tab. I tried searching for the extension to install and I came across TypeScript and JavaScript Grammer extension but couldn't find the above extension you mentioned. Is there any particular repository that I need to point to in order to get it?
@mjbvz My issue is simple. I work on Angular development. If you are familiar with Angular code development, you would know that angular code consists of typscript and html code files corresponding to certain functionalities. The TypeScript file has methods and functions declared and these functions/methods are used/referenced in the html code files. Earlier, while on the html file, if I had methods referenced, clicking on the 'Go to definition' option from the right click context menu when clicked on the method reference, would open up the typescript file that the method declared.
Since the new version update, this functionality is not working. In any of the html code windows. It is not specific or contained to a single code snippet, this is the behavior I am seeing throughout all my application codes for Angular. Unfortunately, due to our company privacy policies, I cannot share my entire code files. But seeing as this is a generic issue, I don't see a reason why the entire code file share would be necessary.
Kindly advise.
Thanks

**Comment by mjbvz** [comment]
Vs Code does not natively support angular intellisense, that would have to come from one of the extensions you installed. Please file an issue against that extension

**Comment by himajaM** [comment]
Guys, please install npm 0.3.9 extension in visual studio code, it is working fine now (able to navigate on mouse click & "Go to definition" too...
![image](https://user-images.githubusercontent.com/26132177/70707117-6f6dec80-1cfd-11ea-814f-9e5f5deab7f8.png)

**Comment by aodegov** [comment]
I would like to highly recommend VSCODE team,
to do not allow to change this functionality nowhere.
Nor by extensions installation, or by user activity.
It should be strict injected into VSCode environment with no changes.
Since, for now it's cause a lot of unexpected issues, related to definition functionality.
