### ISSUE TITLE
Workspace files are being saved one folder above

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#85394]
This happens in Insiders v1.41.0

- VSCode Version: 1.40.1
- OS Version: macOS 10.15.1

Steps to Reproduce:

1. Open a folder
2. `File` -> `Save Workspace As...`
3. Choose the folder
4. Notice that the .code-workspace file is not saved inside the folder you chose, but one folder above.

Does this issue occur when all extensions are disabled? Yes

**Comment by isidorn** [comment]
I think this is expected macOS behavior and that all macOS apps behave that way.
Can you attach a short gif which shows this behavior? Also can you check some native mac app does this differently?

**Comment by andrecasal** [comment]
Hey @isidorn, not at all. macOS works the same in this respect: you open the folder you want to save your file to. If this were the intended behavior you could never save a file to a folder that contained no child folders :)

**Comment by isidorn** [comment]
Thanks for the video, this clarifys things. 
This is not the native dialog, but the custom file picker. Forwarding to @alexr00 and she can continue the investigation

**Comment by alexr00** [comment]
I can reproduce the issue on Windows. The video was very helpful, thanks!

**Comment by alexr00** [comment]
Looks like it only happens when you don't provide a name...

**Comment by andrecasal** [comment]
You're very welcome @alexr00! Thanks for the fix 👌
