### ISSUE TITLE
Open Editors with custom fixed size.

### ISSUE THREAD

**Issue by AndreaCatania** [microsoft/vscode#85396]
I would like that the `Open Editors` panel has a fixed size; exactly like the `Outline` panel.

I come from QtCreator and I'm really used to not use Tabs, but rather organize the files in this little list, but since in VsCode this panel  keeps changing its shape I'm not able to memorize its position and is really uncomfortable for me (to the point that I'm spending some time to write this issue).

I've already found that this problem was discussed before here: https://github.com/Microsoft/vscode/issues/491 and (_in theory_) fixed here: https://github.com/microsoft/vscode/pull/39734 but honestly is not clear to me how to enable this feature.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/43501
