### ISSUE TITLE
Creating a closing quote when typing a contraction in a comment

### ISSUE THREAD

**Issue by jonmon6691** [Microsoft/vscode#8539]
- VSCode Version: 1.2.1
- OS Version: Windows 10.0.10586

Steps to Reproduce:
1. Be editing python document
2. Be typing in a comment
3. Type a contraction such as isn't
4. Notice that the editor creates a closing apostrophe that is inappropriate in this context.

**Comment by bpasero** [comment]
Not sure if this is inside the extension or core. But I have seen issues with wrong auto closing often in selfhost too.

**Comment by joaomoreno** [comment]
Well... this has been there since day 1.

@alexandrudima @jrieken @aeschli Does anyone know how JavaScript solves this, since it's solved there?
