### ISSUE TITLE
Minimap#createSampleData is eager (and slowish?)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#85393]
I have profiled startup with `code-insiders --prof-startup` and I notice that Minimap sample data stands out

* I don't have the minimap enabled so please don't do this
* 56ms seems quite slow on my beefy machine, but it might be an outlier 

[prof-ab08.renderer.cpuprofile.zip](https://github.com/microsoft/vscode/files/3880344/prof-ab08.renderer.cpuprofile.zip)

<img width="630" alt="Screenshot 2019-11-22 at 17 04 27" src="https://user-images.githubusercontent.com/1794099/69441004-2522cc80-0d4a-11ea-84b0-644b68933260.png">

**Comment by connor4312** [comment]
Thanks for the tag, this was a lot faster when I was measuring it earlier, I'll find the time to look into this more today. You're running at the default 1x minimap scale on Catalina?

**Comment by connor4312** [comment]
In 057b535b78 we prebake the small scale minimaps (where font size doesn't matter) which eliminates the boot up time cost. Ultimately the perf hit is just in drawing fonts, which takes a lot of effort on the canvas and is somewhat unavoidable in cases where the font is visible on larger minimaps.

**Comment by jrieken** [comment]
Thanks for jumping on this so quickly. 

>  You're running at the default 1x minimap scale on Catalina?

No minimap enabled... So, there might be more low hanging fruit

**Comment by connor4312** [comment]
You're right. We were maintaining the minimap options, which entailed creating the char renderer, even if we never actually rendered anything. Fixed in 3d772fb164 -- we'll now create it once lazily.
