### ISSUE TITLE
Toggle sidebar doesn't work when focus on terminal

### ISSUE THREAD

**Issue by JerryGoyal** [microsoft/vscode#85390]
ctrl+b toggles the visibility of sidebar when cursor focus is in editor but it doesn't work when cursor focus is in terminal.

- VSCode Version: 1.40.1
- VSCode Terminal: Integrated PowerShell 6.2.3
- OS Version: Windows 10

**Comment by JerryGoyal** [comment]
it's not a duplicate as marked by the evil AI

**Comment by egamma** [comment]
/needsMoreInfo this works for me and I cannot reproduce this given the steps provided. Can you please provide more info for this issue can be reproduced, e.g., what platform? Does it also happen when you use another shell than the Powershell?

**Comment by JerryGoyal** [comment]
Issue is there, even when I run `code --disable-extensions`. Instead of hiding sidebar it types `^B^B` in powershell. I tried with bash, cmd etc but no luck.
Interestingly issue happens only on the terminal pane, not on other panes like problems,output,debug console.
Here's the screenshot.
![image](https://user-images.githubusercontent.com/7106086/69441246-5ca46f80-0d70-11ea-9b3f-c0a483c52cf0.png)

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
This is by design, you can add `workbench.action.toggleSidebarVisibility` to the `terminal.integrated.commandsToSkipShell` setting to get it to work if you don't use ctrl+b in the terminal:

```json
"terminal.integrated.commandsToSkipShell": [
    "workbench.action.toggleSidebarVisibility"
]
```

**Comment by JerryGoyal** [comment]
@Tyriar thanks, that worked like charm
