### ISSUE TITLE
Faster Intellisense for c#

### ISSUE THREAD

**Issue by SamHSmith** [microsoft/vscode#85397]
I switched from monodevelop to vscode about a month a go and so far the transition has been great. Although there is one thing I still can't wrap my head around.
VSCode is supposed to be light and faster than a full IDE. Yet monodevelop's intellisense is somehow able to be both faster and provide better predictions than vscode.

Maybe some optimization could be done to make it faster. It seems like the speed is proportional to project size.

**Comment by mjbvz** [comment]
Please file this against the c# extension
