### ISSUE TITLE
Bring back beetle to Debug icon

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#85395]
![image](https://user-images.githubusercontent.com/1312662/69442565-7a181000-0d55-11ea-8371-9ab43de7914a.png)

I tried to show new icon to other devs (~10) but only one guessed what does it mean.
Other suggestions were: Tests, Indent, Go to Line.
Personally I was confused when I tried to click on Debug with a glance, but had to click on unfamiliar icon to be sure that this is debug.

I doubt that beetle is harder to associate with bug and debug.
Could you please clarify why there was wrong with "beetle ison" and led to a decision to replace Debug icon?
It was refreshed with last round of icon updates and looks obvious (even if not behind crossed circle) but new one is less obvious.

/cc @misolori

**Comment by misolori** [comment]
Thanks for the feedback. We're trying to help address the issue with users who either don't associate "run" with "debug" or don't know what a debugger is. We get a lot of this feedback from students and Python users. So this is one of the ways that we're experimenting with addressing that. We're also listening to our current users and the community, so thanks for this feedback!

**Comment by AlbertoBonfiglio** [comment]
I second @IllusionMH opinion. Nobody in my IT department said debug. Most were wondering if it was ident.

**Comment by changeling** [comment]
Where in the source is the associate new take on the icon, I have a thought, but would like to take a stab graphically. Is the svg in here?

**Comment by isidorn** [comment]
Bring back The Beatles! We need more good bands.
🐞

**Comment by elitistsnob** [comment]
I'm forced to agree with complaints surrounding the new icon. My reasoning is based on the fact this new icon does not convey `code` or `debugging` in any visual context. It more closely resembles a playlist queue icon found in most media player interfaces. Look at the attached examples, showing Spotify's queue icon, with VScode's new debug icon below for comparison. 

![Screen Shot 2019-11-26 at 9 28 12 AM](https://user-images.githubusercontent.com/538261/69645898-eab07c80-1034-11ea-8b8d-e6c619de1899.png)

![Screen Shot 2019-11-26 at 9 28 31 AM](https://user-images.githubusercontent.com/538261/69645905-ec7a4000-1034-11ea-8a81-92467b2e4ea2.png)

**Comment by isidorn** [comment]
Very good point.

**Comment by isidorn** [comment]
@misolori I just reverted the new icon, since we decided to go back to the drawing board I think it is better to rever earlier than later.
We can discuss maybe next ux meeting

**Comment by changeling** [comment]
While y’all are at the drawing board, here’sa thought:

The new icon might work if the > was simply replaced with the beetle highlighting the indented  line instead.

**Comment by IllusionMH** [comment]
Will be really small and hard to recognize bug there and even harder to recognize intent to "Run" there.

Beetle with ▷ in it instead × might be another option.
Please rung this bug (bugged code) slow for me :)

**Comment by IllusionMH** [comment]
Sorry for bumping closes issue in advance.

I like new icon ![image](https://user-images.githubusercontent.com/1312662/70796216-5a02cc00-1daa-11ea-87fb-1efed8bf0431.png)

Thanks again for been open to feedback!

_If you add a bit of imagination you can see a beetle with a big pegleg which can symbolize the fact that you might not observe bug after a fix, but root cause is still there and you only forced it to retreat for a time._

**Comment by BLUEBOUNCE** [comment]
You are doing god's work. Thanks for saving the bugs!

**Comment by misolori** [comment]
Just so everyone knows, we'll be going with this icon that overlays the run/play button above the bug:

![image](https://user-images.githubusercontent.com/35271042/71193380-e267ed80-223e-11ea-84c7-bcf25a95ee0a.png)
