### ISSUE TITLE
Menus created before opening window

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#85392]
<img width="729" alt="Screenshot 2019-11-22 at 16 55 25" src="https://user-images.githubusercontent.com/1794099/69440327-ef311880-0d48-11ea-8f0a-3971ad5000d6.png">

Checkout the attached chart and profile info. It seem that we spend time creating update-uris and menus *before* restoring windows. This seems like some very low hanging perf improvements here.

[prof-ab08.main.cpuprofile.zip](https://github.com/microsoft/vscode/files/3880299/prof-ab08.main.cpuprofile.zip)

**Comment by sbatten** [comment]
@jrieken don't we need to do this because on macOS, the menus are available before the window is ready?

**Comment by jrieken** [comment]
This is just about the order of calls, first restore a window (if there one to be restored), then (without waiting) restore the menus. Restoring/loading a menu takes a while and happens in another process which gives the main process enough slack time to du stuff like this (and also means we should try to restore the window asap)

**Comment by bpasero** [comment]
I recently added support for lifecycle phases on main as well and we could experiment with creating the menu in the `AfterWindowOpen` phase. 

For example, the Windows jumplist is created in that phase:

https://github.com/microsoft/vscode/blob/6b2b68207e264a724a9d5db472d8520da0db33b4/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L81
