### ISSUE TITLE
Go to definition is broken in VS Code Insiders

### ISSUE THREAD

**Issue by snjeza** [microsoft/vscode#85403]
- VSCode Version: VS Code Insiders 1.41
- OS Version: Fedora 30

Steps to Reproduce:

VS Code Insiders:

![tcode-insiders](https://user-images.githubusercontent.com/388609/69449002-1a703380-0d5a-11ea-891e-4552fc7f267d.gif)

VS Code 1.40.1

![tcode](https://user-images.githubusercontent.com/388609/69449035-2d830380-0d5a-11ea-8760-a76ac65a373d.gif)

Related issue: https://github.com/eclipse/eclipse.jdt.ls/pull/1281#issuecomment-557624213

**Comment by mjbvz** [comment]
Text:

```js
class a {
    constructor() {
        this.test();
    }
    test() {}
}
```


@jrieken I think this is an intentional change for #73081

**Comment by jrieken** [comment]
Yes, that's the new design: Going to definition on a definition -> Run Go to References -> Running to references with a single result -> To go single reference. Anways, this can also be configured via `editor.gotoLocation.alternativeDefinitionCommand`, e.g an empty value will disable this behaviour

**Comment by SSJ9899TDylan** [comment]
That's what she said!
