### ISSUE TITLE
sync.settings is not a registered configuration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85408]
I got this error when enabling sync via gear menu. That setting isn't even referenced in my settings file?

<img width="450" alt="Screen Shot 2019-11-22 at 10 20 06 AM" src="https://user-images.githubusercontent.com/2193314/69450319-ba559f00-0d11-11ea-876e-5bf49933ad8a.png">

**Comment by sandy081** [comment]
Fixed with latest insiders.
