### ISSUE TITLE
Make global activity multi activity aware

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85404]
I enabled settings sync, and saw a badge for that at one point. Now Insiders has an update, but there is no badge on the gear.

![image](https://user-images.githubusercontent.com/323878/69449605-28996200-0d10-11ea-94ef-def16adf7276.png)

**Comment by Tyriar** [comment]
I also spotted this https://github.com/microsoft/vscode/issues/85409

**Comment by sandy081** [comment]
I do not think global activity is multi activity aware, hence activities are not shown correctly.
