### ISSUE TITLE
working tree for changed files, should preview for saved files

### ISSUE THREAD

**Issue by daksamit** [microsoft/vscode#85407]
- VSCode Version: 1.40.1
- OS Version: mint 19

Steps to Reproduce:

1. Open some file and make changes and save
2. ctrl + shift + G -> look at changes (working tree)

![image](https://user-images.githubusercontent.com/7165997/69449460-43dd8f00-0d5b-11ea-8f9d-28639664e7b0.png)

3. Make some changes on file again (do not save)

![image](https://user-images.githubusercontent.com/7165997/69449523-64a5e480-0d5b-11ea-8c6b-ca3dc2010200.png)

4. Working tree preview shows that line changed, even if file isn't saved.

I think it may be misleading while working on multiple files at time. 
It should preview only changes only for saved files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
>  It should preview only changes only for saved files.

I really disagree with this. Disabling the current behavior would mean that you wouldn't see any changes while you type and only once you save, which a *lot* more people would find disturbing.

Closing as designed.
