### ISSUE TITLE
Respect metered connections on Windows 10

### ISSUE THREAD

**Issue by Weetbix** [Microsoft/vscode#8540]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:
1. Connect to a Wifi network 
2. Set the connection type as metered (`Wifi > Advanced Settings > Turn metered connection on`) 
3. Open Resource Monitor
4. Switch to the network tab
5. Start VS Code
6. Notice VS Code updates happen normally, and there is general ongoing network usage from `code.exe` and `git-remote-https.exe`

VSCode should respect metered connections, as sometimes you may need to tether to your mobile to get some work done and it would be nice if it has 0 network usage when the connection was metered. In the very least it should not download any updates over metered connections.

**Comment by bpasero** [comment]
Likely needs support from our framework to detect.

**Comment by osnoser1** [comment]
I am from Venezuela and many times I must use the data of my phone due to the bad connection to internet. This feature would be great. 😢
