### ISSUE TITLE
Settings sync replaces "1" badge from update

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85409]
Repro:

1. Have an update available
2. Sign in to settings sync

There will be no badge as sync is probably replacing the badge.

<img width="47" alt="Screen Shot 2019-11-22 at 10 21 57 AM" src="https://user-images.githubusercontent.com/2193314/69450436-fc7ee080-0d11-11ea-9f7c-8f2fcf2be323.png">

<img width="237" alt="Screen Shot 2019-11-22 at 10 21 55 AM" src="https://user-images.githubusercontent.com/2193314/69450431-f8eb5980-0d11-11ea-9672-0a8e10f8e59a.png">

**Comment by gjsjohnmurray** [comment]
Maybe already #85404
