### ISSUE TITLE
Intergrated powershell terminal first line not showing

### ISSUE THREAD

**Issue by AvrumFocus** [microsoft/vscode#85401]
Issue Type: <b>Bug</b>
## System info
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763
Extensions disabled

## Issue
When I launch the integrated terminal (not to be confused with the intergrated console we get when we install the powershell extension.) the first line (Prompt) is not being shown and the cursor starts in the middle of the terminal a little scrolled down (not right at the top like it should be). Only when I press enter does the prompt come up and then it looks normal.

## Screenshot
![ZTM17TRRHQ](https://user-images.githubusercontent.com/42219106/69448633-f5ae9880-0d26-11ea-86d9-efa5651becfd.gif)

**Comment by AvrumFocus** [comment]
I did another screen capture so you can see the text doesn't either start at the top of the console rather 
is scrolled down.

![nnju9Hntrb](https://user-images.githubusercontent.com/42219106/69449852-d06f5980-0d29-11ea-9cf0-ff10c0e7eb19.gif)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
