### ISSUE TITLE
Feature request: add confirmation dialog to `Synchronize Changes` button

### ISSUE THREAD

**Issue by vagarenko** [Microsoft/vscode#8541]
'Synchronize Changes' button is located directly under file explorer and next to 'Show Errors' button so it can be clicked accidentially. Once clicked it performs git pull & push without any confirmation.

I think having such a tiny button, silently performing such a significant action, may cause troubles.

Can you add confirmation dialog for this button or/and move it somewhere?

**Comment by joaomoreno** [comment]
Very likely won't happen as it would annoy most users.

We can have it under a setting though, as it appears there are more people with that opinion. cc @chrmarti

**Comment by chrmarti** [comment]
Not favoring a confirmation dialog, just surprised my change was pushed.

**Comment by joaomoreno** [comment]
There is now a `git.confirmSync` setting which, when `true`, will enable a confirmation dialog to popup before every sync.
