### ISSUE TITLE
User Markdown Styling Conflicts with Markdown-Language-Features in Confusing Ways

### ISSUE THREAD

**Issue by phoenix-meadowlark** [microsoft/vscode#85414]
Issue Type: <b>Bug</b>
To reproduce the issue, include the following in test.md, and the code referenced in the block in a separate style sheet.
```
This is a code block that is very difficult to style.

VS Code provides the option to use custom markdown styling as so:
"markdown.styles": [
  "./style.css"
],

However the stylesheet that can be found here:
extensions/markdown-language-features/media/markdown.css
is applied after the css that the user specifies.

Including the following in style.css does nothing
pre {
  background-color: red;
}
because it is overridden by the Markdown-Language-Features stylesheet using
the class .vscode-dark

Including the code below in style.css has the desired effect, but it is not very 
user-friendly, as one has to dig into the Webview Developer Tools to see that this
is the class that overrides what they were trying to do.
.vscode-dark pre {
  background-color: red;
}
```

An easy solution is to comment out the contents of markdown.css wherever it is on your system, but that's not very elegant. Would it be possible to include an option to disable Markdown-Language-Features styling (and that alone) so that user's don't run into this issue? Or alternatively, if the styling could be applied before the user's styling, then they would have the oppertunity to clear it with a css reset.

Thank you!

VS Code version: Code - Insiders 1.41.0-insider (f24f483428f592a262dc73d68a3f05745c562b31, 2019-11-21T10:39:56.671Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.19.0
unique-lines|bib|1.0.0
vscode-multi-line-tricks|big|0.0.3
simple-react-snippets|bur|1.2.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
python-extension-pack|don|1.6.0
vscode-html-css|ecm|0.2.3
tslint|eg2|1.0.44
vsc-material-theme|Equ|30.0.0
jsonnet|hep|0.1.0
latex-workshop|Jam|8.4.1
vscode-styled-components|jpo|0.0.27
simple-vim|jpo|0.0.5
language-julia|jul|0.12.3
vsc-python-indent|Kev|1.8.1
MagicPython|mag|1.1.0
rainbow-csv|mec|1.3.1
select-part-of-word|mle|1.0.1
theme-monokai-pro-vscode|mon|1.1.14
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.12.49019-dev
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
vsliveshare|ms-|1.0.1293
color-highlight|nau|2.3.0
emoji|Per|0.0.3
material-icon-theme|PKi|3.9.1
java|red|0.53.1
vscode-yaml|red|0.6.1
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vscode-scss-formatter|sib|1.4.2
code-spell-checker|str|1.7.20
sort-lines|Tyr|1.9.0
highlight-matching-tag|vin|0.9.5
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
jinja|who|0.0.8
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.0.3

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is working as expected; here are relevant rules from `markdown.css` that need to be overridden: https://github.com/microsoft/vscode/blob/e5f0077f408e68b35b5e06f22a283d4d5b3ad94a/extensions/markdown-language-features/media/markdown.css#L183

The intent of user styles are to augment the base styles and unfortunately there is no way I can see to provide a base, theme aware style rule for code blocks that can be overridden by less specific user style rule

**Comment by phoenix-meadowlark** [comment]
Ah, that makes sense. Thanks for the response!
