### ISSUE TITLE
Find in Files doesn't look in non-workspace files that haven't been opened

### ISSUE THREAD

**Issue by nchen63** [microsoft/vscode#85416]
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.67-2rodete2-amd64
Steps to Reproduce:

1. create 2 files, each with the same text
1. on the command line, run `code file1 file2`
2. in vscode, control-shift-f to search for text in both files
3. issue: text is only found in 1 file

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
What's happening here is that the file isn't actually loaded until you view it. If you open the tab with the second file, it will appear in further searches. 

Also, this isn't specific to opening file from the command line, it's any file not in a workspace that haven't been viewed yet.

**Comment by JacksonKearl** [comment]
\duplicate 62488
