### ISSUE TITLE
Emmet suggestions not working in HTML

### ISSUE THREAD

**Issue by belikeswap** [microsoft/vscode#85413]
Issue Type: <b>Bug</b>

Emmet is not giving me suggestions as I type. I have the hit the backspace key after I type a few characters to get the suggestions. For example, if I Want suggestions for a <div> element, I have to first type "di", then hit the backspace button to make it a "d" and then only I am starting to emmet suggestions of <div> and other elements.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
copy-relative-path|ale|0.0.2
vscode-intelephense-client|bme|1.2.3
phpserver|bra|2.4.6
vscode-eslint|dba|1.9.1
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.8.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
code-runner|for|0.9.15
jquery-snippets|Hri|1.0.0
kite|kit|0.101.0
vscode-docker|ms-|0.8.2
python|ms-|2019.11.50794
remote-wsl|ms-|0.40.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.22.6
format-html-in-php|rif|1.6.1
vue-vscode-snippets|sdr|1.8.0
html5-boilerplate|sid|1.0.3
material-theme|zhu|3.0.3
html-css-class-completion|Zig|1.19.0

</details>

**Comment by octref** [comment]
> For example, if I Want suggestions for a element, I have to first type "di", then hit the backspace button to make it a "d" and then only I am starting to emmet suggestions of
and other elements.

Can you be more specific? What did you input exactly, what element you are looking for, and what is showing up?
