### ISSUE TITLE
[html] can't "rename symbol" within <script> tags

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#85411]
**Problem**
In an HTML file with <script> tags, the "rename symbol" command is unavailable.   
VSCode 1.40.1

**Workaround**
"find and replace," but that's always a bit scarier, because it requires vigilance to avoid renaming the wrong thing.  

**Example**  
`<p>catalog</p> ` 
`<script>`  
`let cat = 'hiss';`  
`cat = 'purr';`  
`</script>` 

**Desired behavior:** 
select `cat` --> **rename symbol** to "feline" --> should just replace the variable `cat` with `feline`, leaving "catalog" alone.  

But, this option is unavailable.  

So, the alternative is to find-and-replace all --> "cat" to "feline" --> "felinealog". 
Or need to go one-by-one and check, which can be tricky in a long file.  
Of course, you can be clever searching for " cat " with spaces, but this is just a simple example.  

**Possible solutions**
In an HTML file, the rename could either affect all so-named symbols in all <script> tags in the file, or local to the current <script> tag.  

Thanks for considering this!

**Comment by ultraGentle** [comment]
I'm wondering if the cause of this is related to #85306, "Expand selection" misses { } in <script> tag, in which case perhaps both individual issues should be closed in favor of something like, "some editor features do not work within <script> tags."

**Comment by aeschli** [comment]
It's just not implemented yet.

**Comment by ultraGentle** [comment]
Thanks for the response.  Good to know.

**Comment by stagefright5** [comment]
Hey @aeschli , Can you provide any details on this? Is it in the roadmap?

**Comment by aeschli** [comment]
No, it's not on the roadmap. Help is welcome!

**Comment by chenjigeng** [comment]
@aeschli can you check this? I did it by borrowing its [ideas](https://github.com/microsoft/vscode-css-languageservice/blob/982dc8849a81e0f77c12b57c34e2da5263b93f2e/src/services/cssNavigation.ts#L270)
