### ISSUE TITLE
Toggle devloper error

### ISSUE THREAD

**Issue by AmericanY** [microsoft/vscode#85426]
[Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362](url)

I don't understand what should i do with those error which appears once i open toggle dev..

console.ts:137 [Extension Host] Error Python Extension: 2019-11-23 02:40:25: [TypeError: Cannot convert object to primitive value	at Array.join (<anonymous>)	at Array.toString (<anonymous>)	at c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:1:12808	at Array.forEach (<anonymous>)	at Object.l [as sendTelemetryEvent] (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:1:12730)	at S.sendSettingsTelemetry (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:75:631341)	at Timeout._onTimeout (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:1:83209)	at listOnTimeout (internal/timers.js:531:17)	at processTimers (internal/timers.js:475:7)]
t.log @ console.ts:137
console.ts:137 [Extension Host] Error Python Extension: 2019-11-23 02:40:25: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
t.log @ console.ts:137
console.ts:137 [Extension Host] Error Python Extension: 2019-11-23 02:40:25: Detection of Python Interpreter for Command py and args -3.7 failed as file Python 3.7 not found!

 -3.8-64 does not exist
t.log @ console.ts:137
console.ts:137 [Extension Host] Error Python Extension: 2019-11-23 02:40:25: Detection of Python Interpreter for Command py and args -2 failed as file Python 2 not found!

 -3.8-64 does not exist
t.log @ console.ts:137
console.ts:137 [Extension Host] Error Python Extension: 2019-11-23 02:40:25: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.8-64 does not exist
t.log @ console.ts:137
console.ts:137 [Extension Host] Error Python Extension: 2019-11-23 02:40:25: Failed to parse interpreter information for 'C:\Users\AmericaN\AppData\Local\Microsoft\WindowsApps\python.exe' with JSON Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640 [SyntaxError: Unexpected token P in JSON at position 0	at JSON.parse (<anonymous>)	at t.WindowsStorePythonProcess.getInterpreterInformation (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:9:39934)	at async getInterpreterInformation (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:75:1105031)	at async getInterpreterDetails (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:75:1136642)	at async Promise.all (index 1)]
t.log @ console.ts:137
console.ts:137 [Extension Host] Git installation not found.
t.log @ console.ts:137
console.ts:137 [Extension Host] Error Python Extension: 2019-11-23 02:40:25: Failed to parse interpreter information for 'C:\Users\AmericaN\AppData\Local\Microsoft\WindowsApps\python3.exe' with JSON Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640 [SyntaxError: Unexpected token P in JSON at position 0	at JSON.parse (<anonymous>)	at t.WindowsStorePythonProcess.getInterpreterInformation (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:9:39934)	at async getInterpreterInformation (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:75:1105031)	at async getInterpreterDetails (c:\Users\AmericaN\.vscode\extensions\ms-python.python-2019.11.50794\out\client\extension.js:75:1136642)	at async Promise.all (index 2)]
t.log @ console.ts:137
2console.ts:137 [Extension Host] (node:8008) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

**Comment by egamma** [comment]
This is an error message from the Python extension. Please report the issue against the Python extension.
