### ISSUE TITLE
Settings key representation in visual settings editor

### ISSUE THREAD

**Issue by go2sh** [microsoft/vscode#85421]
- VSCode Version: 1.40.1
- OS Version: Linux x64

Steps to Reproduce:
1. Have an extension, where the name of the extension and the first part of settings keys differ.
2. Open the visual settings editor
3. Goto the extension settings

The first part of the key will be shown in the Title: e.g "C/C++ > ..." for the C/C++ Extension. I realized to late as there is no documentation about that, that the name of my extension and the first key element must match to get rid of it. It would be nice to have a way around that, like drop the first element from the view, if it is not the only element.

There are quite some extension out there, where the condition is met.

**Comment by roblourens** [comment]
Can you give a specific example of what the problem is and what you suggest? I don't quite understand.

**Comment by go2sh** [comment]
![grafik](https://user-images.githubusercontent.com/150886/69524318-0436c300-0f66-11ea-9aea-1251387431a3.png)
In the Snapshot you see the key "azure.cloud" with the Prefix "Azure: ", the name of the extension is "azure-account". So the first part of the key gets rendered as part of the title.
![grafik](https://user-images.githubusercontent.com/150886/69524554-95a63500-0f66-11ea-8a72-ac8126952973.png)
Compare it to the key "git.allowForcePush", the first part of the key didn't get rendered.

The first behavior happens alot as this is not part of the documentation, it would be nice to have a way to get the second behavior without matching extension name and setting key. It would make the settings easier to read.

**Comment by roblourens** [comment]
Ok I see. There is an issue to give extensions more ability to customize their settings UI: https://github.com/microsoft/vscode/issues/70589
