### ISSUE TITLE
MacOS Terminal: Cursoredover characters in low DPI display very small

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#85423]
Issue Type: <b>Bug</b>

Primary display is retina, secondary (where the bug occurs) isn't.

![image](https://user-images.githubusercontent.com/8586769/69468851-b7bf6d80-0d42-11ea-92a6-0ca63f95bdf6.png)
![image](https://user-images.githubusercontent.com/8586769/69468857-bbeb8b00-0d42-11ea-9032-6c77579c692d.png)

VS Code version: Code - Insiders 1.41.0-insider (599c076d91be1374cf51004cec610f3bcaf4c9cd, 2019-11-22T07:19:06.796Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (4.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
tsl-problem-matcher|eam|0.1.0
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
vscode-pull-request-github|Git|0.13.0
graphql-for-vscode|kum|1.15.3
find-jump|mks|1.2.4
vscode-selection-flip|mle|1.0.0
python|ms-|2019.11.50794
remote-containers|ms-|0.85.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.41.0
vscode-remote-extensionpack|ms-|0.17.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1293
debugger-for-chrome|msj|4.12.1
subtle-brackets|raf|3.0.0
colored-console-log|reh|1.0.7
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
vscode-multiclip|sle|0.1.5
code-spell-checker|str|1.7.20
ayu|tea|0.18.0
polacode-fork|Tox|0.6.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Looks like it's probably this? https://github.com/xtermjs/xterm.js/issues/2137

/duplicate
