### ISSUE TITLE
Typescript constants are not using variable intellisense icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85429]
I think it's been like this for a while for TypeScript.

![image](https://user-images.githubusercontent.com/2193314/69470854-45548a80-0d4e-11ea-8267-74cea1671aee.png)

Expected to use this icon:

![image](https://user-images.githubusercontent.com/2193314/69470858-5a311e00-0d4e-11ea-996c-0cb66308612a.png)

As per the documentation:

![image](https://user-images.githubusercontent.com/2193314/69470867-6a48fd80-0d4e-11ea-96b5-6dc657bca0eb.png)

https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions

**Comment by mjbvz** [comment]
For `const` variables, we  use the `constant` symbol type. @misolori Thoughts on changing this?

**Comment by misolori** [comment]
I'm fine to change it, I'm not sure where what symbols are mapped to are stored though.

**Comment by Tyriar** [comment]
Personally I'd prefer the same variable icon or something much closer to it as I like to just treat constants as variables generally. One of the biggest problems is that the documentation doesn't even mention the icon -> https://github.com/microsoft/vscode/issues/85430
