### ISSUE TITLE
Multi-select in the Explorer: Delete deselected folder instead of selected ones

### ISSUE THREAD

**Issue by fireattack** [microsoft/vscode#85437]
Exactly the same issue as #43233, it doesn't seem to be fixed here (or re-introduced).

- VSCode Version: 1.41-insiders
- OS Version: Win7x64

Steps to Reproduce:

1. Multi-select several folders/files in the explorer.
1. Deselect a single folder (CTRL+Click)
1. Use the delete key on the keyboard

Expected: It should delete the folders/files still in the multi-selection
Actual: It wants to delete the de-selected folder/file

![bug](https://user-images.githubusercontent.com/4130991/69472573-85793480-0d71-11ea-8275-8fd5dfb02bf0.gif)

**Comment by isidorn** [comment]
This issue is also present in vscode stable, so not an immediate regression.
The issue here is that we always respect focus when you are triggering commands.
And in this particular case the focus does not really repesetn what you want to do.

Bottom line I think the list / tree should not focus an element if it is removed from the selection.
The focus should remain unchanged. Only if clicked one more time.

Let me know what you think @joaomoreno

**Comment by joaomoreno** [comment]
Not sure I agree, since the focus is later on used as an anchor point for contiguous multiple selection.

Maybe the better fix would be to disregard focus and just use selection *if* there is multiple selection and the driving user action was the keyboard.

**Comment by fireattack** [comment]
Any idea why it was reintroduced, by the way? Assuming it was fixed last time.

**Comment by isidorn** [comment]
Yes, we could disregard focus if there is multiple selection. However commands are not aware how they are triggered via keyboard or via context menu.

As to why it was reintroduced: I do not know, my best guess would be that I did some ugly workaround to make it work and than later when refactoring the code I removed the workaround. Sorry for not remembering more.

**Comment by fireattack** [comment]
I personally think this should be addressed for a few reasons.

1. Most importantly, this bug has serious consequence: the users may accidentally delete a file and therefore data loss.
1. This is clearly a bug, not a feature request. So I'm not sure why it applies to whatever the bot linked above ("decision-making process"). 
1. It has been reported before and presumably fixed, but reintroduced (therefore it shouldn't be "out-of-scope" *this time*.)

**Comment by totaleo** [comment]
+1
