### ISSUE TITLE
Rename symbol on variable "r" in python3 causes raw string identifier to be changed as well.

### ISSUE THREAD

**Issue by corpseboat** [microsoft/vscode#85436]
Issue Type: <b>Bug</b>

Enter in 
```
r"test"
r = 0
 ```
F2 or right click to rename symbol `r` in the second line to "test". This results in 

```
rtest"test"
test = 0
```

This should only change the symbol indicated, instead of appending 'test' to the prefix for the string.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
vscode-markdownlint|Dav|0.32.0
todo-tree|Gru|0.0.162
python|ms-|2019.11.50794

</details>

**Comment by corpseboat** [comment]
Similar (but not identical) bug found in f-string handling:
```
f"test"
f = 0
```
maps to
```
test"test"
test = 0
```
In this case, the renamed 'f' is replaced, rather than appended, but this is still unwanted behavior.

**Comment by egamma** [comment]
Please file the issue against the Python extension.
