### ISSUE TITLE
Weird state where settings UI shows active theme but settings.json shows a different theme

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85435]
Settings UI showing correct theme:

![image](https://user-images.githubusercontent.com/2193314/69472325-98820980-0d5d-11ea-9f0b-59be8804c813.png)

settings.json showing incorrect theme:

![image](https://user-images.githubusercontent.com/2193314/69472334-ad5e9d00-0d5d-11ea-9640-fc6776be3af4.png)

I was trying to get settings sync working and failing, I also changed my theme a while ago on a different window. Not sure exactly how I got in this state.

**Comment by Tyriar** [comment]
Could be related to https://github.com/microsoft/vscode/issues/85361

**Comment by sandy081** [comment]
I think this should be other way around. UI is having wrong value as the source of truth is settings file.

**Comment by Tyriar** [comment]
Pretty sure it's https://github.com/microsoft/vscode/issues/85361, settings ui and workbench never got the file event. Let's track there
