### ISSUE TITLE
Feature Request: Command line flag to disable files.autosave setting

### ISSUE THREAD

**Issue by StaticSphere** [Microsoft/vscode#8543]
As of version 1.2.1, if I have files.autosave set to anything other than "off", and am using VSCode as my Git editor, we run the risk of "saving" a commit message before we're actually done writing it.  VSCode currently has the -w flag, which keeps it from closing until the application is deliberately closed, but the file still auto-saves if that's how the developer normally works (they have files.autosave set to something other than "off").

It would be nice to do something like this to ensure that VSCode won't persist changes until the application is closed:

`code.exe --wait --new-window --no-auto-save`

Either that, or override specific workspace settings from the cli

`code.exe --wait --new-window --override-settings "files.autosave=off"`

**Comment by bpasero** [comment]
@StaticSphere but the whole point of -w is that the external application should only continue after the window is closed so auto save should really not cause any issues?

**Comment by StaticSphere** [comment]
No, it looks like you're absolutely right.  My test yesterday was against a file, not a git commit, which was obviously a mistake.  The --wait flag definitely doesn't allow the commit until VSCode is closed.

I'll go ahead and close this issue if you're OK with that.
