### ISSUE TITLE
SCSS recommendation dosen't work.

### ISSUE THREAD

**Issue by Somrat37** [microsoft/vscode#85439]
When I write a user snippet in scss and press enter, after that it does not recommend anything if i do not press the mouse pointer somewhere else and go back to there. 

But it was working on 1.24 version. Don't know what happens in the next versions. I am still looking for this solution and when a new version comes i thought the issue might fixed. but it didn't.... :(

**Comment by egamma** [comment]
/needsMoreInfo

>When I write a user snippet in scss and press enter, after that it does not recommend anything if i do not press the mouse pointer somewhere else and go back to there.

please provide more detailed steps for how to reproduce the issue.

>after that it does not recommend anything

What are the expected recommendations?

What extensions are you using?
