### ISSUE TITLE
At debug pausing, "this" in A.constructor() shows undefined when target=ES6 and A extends B and A.constructor() has lambda function.

### ISSUE THREAD

**Issue by MR-L-2015** [microsoft/vscode#85433]
- VSCode Version: 1.40.1
- OS Version: Windows 10

Steps to Reproduce:

1. tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "sourceMap": true,
    "strict": true,
    "esModuleInterop": true
  }
}

2. main.ts
class SUPER{}

class main extends SUPER
{
    constructor()
    {
        super();
        debugger;
        let aa = this;
        //**
        let bb = ()=>{
            console.log(this);
        };
        //*/
    }
}
new main();

![image](https://user-images.githubusercontent.com/13444742/69471966-d889d080-0ddf-11ea-9cfc-ed4ee6a79d95.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
What node version? Works for me.

![image](https://user-images.githubusercontent.com/323878/69499818-f8d29180-0eaa-11ea-8ed3-43762f3aebbb.png)

It shows 'undefined' in the variables window, but I see the same behavior in chrome devtools.

Note that there are lots of oddities around how 'this' work in a debugger, due to optimizations that the runtime makes, and there's probably nothing I can improve here. But let me know if you see a difference between vscode and chrome devtools.

**Comment by MR-L-2015** [comment]
C:\Users\ys>node -v
v10.15.3

(1) A extends B
(2) ES6
(3) lambda have ref to this, likes
let bb = ()=>{
console.log(this);   //<----- this appear here
};

I need your full test code.

**Comment by MR-L-2015** [comment]
Here's full nodejs proj
[test_this_undefined.zip](https://github.com/microsoft/vscode/files/3884546/test_this_undefined.zip)

**Comment by MR-L-2015** [comment]
class SUPER {

}

class main extends SUPER {
    constructor() {
        super();
        debugger;
        let aa = this;
        /**
        let bb = () => {
            console.log(this);  //ref "this" here, bug appear
        };
        /*/
        let bb = ()=>{
            console.log("no this here");   //bug gone
        };
        //*/
    }
}

new main();

**Comment by MR-L-2015** [comment]
![GIF](https://user-images.githubusercontent.com/13444742/69507582-00a73a00-0f6e-11ea-90cf-2998722a6343.gif)

**Comment by roblourens** [comment]
With that version, I see the same, and the same in chrome devtools, so I can't do anything to improve this. But it looks like it gets better in more recent versions of node.
