### ISSUE TITLE
After uninstalling the VSCode and installing the new version the old option still exists

### ISSUE THREAD

**Issue by saish-borkar** [microsoft/vscode#85448]
This issues I was facing when I installed the 1st VSCode version and then uninstalled it.
- OS Version: 1903 (OS build 18362.476)
- VSCode Version: 

![image](https://user-images.githubusercontent.com/13750931/69475795-9076a800-0df7-11ea-8657-8d8f663f7dfc.png)

I'm facing the below issue.

- After uninstalling the old version of VSCode and installing the new version why I'm still seeing the open with code option twice.

![image](https://user-images.githubusercontent.com/13750931/69475824-fe22d400-0df7-11ea-9aee-4dbd34f70068.png)

Tried the solution suggested by @shanselman.

- Removed the entry from the registry and restarted the explorer but also same result no solution.

**Comment by joaomoreno** [comment]
This is really odd. I can't reproduce on my machine. Can you manually check the following registry keys?

- HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\VSCode
- HKEY_CURRENT_USER\Software\Classes\Drive\shell\VSCode

**Comment by saish-borkar** [comment]
Hi @joaomoreno , 
Thanks for replying. Below is the screen shot of my registry keys both of them have the same value can that might be the problem?

![image](https://user-images.githubusercontent.com/13750931/69897015-dab5d700-136b-11ea-9a05-9a608204ca66.png)

**Comment by joaomoreno** [comment]
First of all, thanks for being a LONG TIME fan (I can see that `Ticino` key).

Can you check whether the same keys exist in `HKEY_LOCAL_MACHINE`?

**Comment by saish-borkar** [comment]
Hi @joaomoreno ,
I checked but there are no keys in `HKEY_LOCAL_MACHINE`
under both the locations in Drive and Directory. Please check the below images.

Drive Image

![image](https://user-images.githubusercontent.com/13750931/69918411-8e67b580-1497-11ea-9dc9-5b5fb79a9e66.png)

Directory Image

![image](https://user-images.githubusercontent.com/13750931/69918437-e69eb780-1497-11ea-8d29-509c85b724d6.png)

**Comment by joaomoreno** [comment]
So, if you uninstall VS Code, do the HKEY_CURRENT_USER keys stick around?

**Comment by saish-borkar** [comment]
Hi @joaomoreno ,
After uninstalling the VS Code, the HKEY_CURRENT_USER keys are deleted. But that option still exists and after clicking that I'm getting the following error hope that might help.

![image](https://user-images.githubusercontent.com/13750931/70079007-d7e80a00-1629-11ea-9883-7aed33184503.png)

![image](https://user-images.githubusercontent.com/13750931/70079022-e3d3cc00-1629-11ea-8ac4-a60dc2beafac.png)

**Comment by joaomoreno** [comment]
@saish-borkar Can you search for `Open with Code` in the entire registry using Find?

**Comment by saish-borkar** [comment]
Hi @joaomoreno ,
Sorry for late reply. Yes I found one entry in the registry it's under the tikino folder.

![image](https://user-images.githubusercontent.com/13750931/73609367-f56a2d80-45f2-11ea-9c8b-6d8143b37fc4.png)
