### ISSUE TITLE
Menus shouldn't ever start with a separator

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85440]
Issue Type: <b>Bug</b>

This is not reproducible in stable (1.40.1)

![image](https://user-images.githubusercontent.com/641685/69473660-f249fa00-0d84-11ea-9914-672ab0651dbb.png)

VS Code version: Code - Insiders 1.41.0-insider (599c076d91be1374cf51004cec610f3bcaf4c9cd, 2019-11-22T07:25:24.031Z)
OS version: Windows_NT x64 10.0.19028

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sbatten** [comment]
so, it is true that this should never happen and I could add some logic to prevent it in the menus very easily, but I am very curious why this happened since I've never seen it before.

**Comment by eamodio** [comment]
Yeah, I don't know why it started, but it doesn't happen in 1.40.1

**Comment by sbatten** [comment]
fyi @jrieken
