### ISSUE TITLE
Breakpoints in Coffeescript 

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8545]
Test item #8193 
- VSCode Version: aweinand/asyncsourcemaps Code - Insiders 1.3.0-insider (392b89ffeebbc51a8574142f9629ff4a6eac15b9, 2016-06-27T22:37:58.724Z)
- OS Version: Linux x64 3.13.0-34-generic
- Coffeescript 1.10.0

Steps to Reproduce:
1. Launch config:

```
        {
            "name": "Coffee",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/coffee/target.js",
            "cwd": "${workspaceRoot}/coffee",
            "sourceMaps": true,
            "stopOnEntry": false,
            "smartStep": false
        }
```
1. Coffescript:

```
log =
  warnings: 0
  warn: (args...) ->
    log.warnings++
    console.log "Warning:", args...

log.warn "There!"
```
1. Compiling with: coffee --compile --map --watch coffee/
2. Add breakpoints on at 'log.warnings++' and 'console.log ...'
3. Start debugging
4. Unexpected: The breakpoints move up by one line
5. Debugger stops at the 'log.warnings++' line
6. Unexpected: The 'args' variable is shown with value 'undefined' in the debugger and hover
7. Continue
8. Unexpected (?): The debugger stops at the 'warn: (args...) ->' line

**Comment by weinand** [comment]
Should work now.
