### ISSUE TITLE
Cannot use Font Ligatures When fira code's Stylistic sets are enabled for all language

### ISSUE THREAD

**Issue by TimilsinaBimal** [microsoft/vscode#85457]
- VSCode Version:1.40.1 (system setup)
- OS Version:Windows_NT x64 10.0.18363

Steps to Reproduce:

1. When enabling font ligatures along with stylistic sets of Fira Code for all languages ,one of these don't work.
`"editor.fontLigatures": "'ss01','ss02','zero'",`
`"editor.fontLigatures":true`

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
And see https://stackoverflow.com/questions/58965575/vscode-update-to-stylistic-sets-in-fira-code I've put the info from both issues into a SO question/answer.

**Comment by TimilsinaBimal** [comment]
It worked! by using calt.
`"editor.fontLigatures": "'ss01','ss02','zero','calt'",`
thank you!
