### ISSUE TITLE
Dark theme editor background issue

### ISSUE THREAD

**Issue by jorasmhj** [microsoft/vscode#85452]
Part of the editor has different background color
![Screenshot from 2019-11-23 17-39-53](https://user-images.githubusercontent.com/10026356/69478226-4d78fc80-0e18-11ea-9e39-30214519cbbd.png)

**Comment by sagebind** [comment]
I've been seeing this one as well.

- Version: 1.40.1
- OS: Ubuntu 18.04.03
- Graphics: Intel HD Graphics 530

**Comment by egamma** [comment]
/needsMoreInfo what theme are you using?

>Part of the editor has different background color

Please indicate which part of the editor has a different background color than expected.
Please note, that line 14 has a different background because it is the current line and this is the expected behaviour.

**Comment by sagebind** [comment]
Images speak a thousand words, so I increased the contrast of the image provided by the original reporter to highlight the differently-colored areas of the background:

![69478226-4d78fc80-0e18-11ea-9e39-30214519cbbd](https://user-images.githubusercontent.com/2192863/69482678-05d87d80-0de4-11ea-8650-d8f3775d2aed.png)

In the original image, some areas of the background (notably behind the areas where text is being rendered) have the color #292D3E, while other areas of the background are a slightly different shade at #2B2A3F.

**Comment by sagebind** [comment]
On some themes, this bug is more noticeable than others. Here is a screenshot using the built-in "Tomorrow Night Blue" theme:

![Screenshot from 2019-11-23 11-32-58](https://user-images.githubusercontent.com/2192863/69482763-235a1700-0de5-11ea-83b0-bd7a94f47d5b.png)

**Comment by Grommers00** [comment]
Would I be able to attempt the fix?

**Comment by CodeDotJS** [comment]
I'm facing the same issue. https://github.com/microsoft/vscode/issues/85539 

Is there any way to fix it?

**Comment by deepak1556** [comment]
How does it look when you try the following ?

```
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
```

**Comment by CodeDotJS** [comment]
@deepak1556 Yes, it worked for me.

Thank You.

**Comment by jorasmhj** [comment]
> How does it look when you try the following ?
> 
> ```
> * Command Palette search for "Configure Runtime Arguments"
> * Set `disable-hardware-acceleration: true`
> * Restart
> ```

Nope..not working

**Comment by jorasmhj** [comment]
Setting `disable-hardware-acceleration: true` worked

**Comment by sagebind** [comment]
Is there an upstream Electron issue we can link this to? Disabling hardware acceleration is a good workaround, but it isn't a true fix.

**Comment by deepak1556** [comment]
@sagebind hardware accelerated rendering support comes from chromium, if you can repro the issue with chromium browser on your machine with https://vscode-web-test-playground.azurewebsites.net/ , we can report it to chromium issue tracker.
