### ISSUE TITLE
wrong order of next/prev buttons at touchbar

### ISSUE THREAD

**Issue by macrozone** [microsoft/vscode#85453]
I reopen this, because it got closed multiple times, despite beeing unresolved.

issue is described here: https://github.com/microsoft/vscode/issues/35906

happens on a fresh installed macbook 16 inch late 2019 with mac os catalina 10.15.1 and vscode 1.40.1.

Reproduction:

- install vscode on macbook with touchbar
- start vscode
- look at the touchbar
- see the unintuitive arrangement of navigation buttons

**Comment by macrozone** [comment]
https://github.com/microsoft/vscode/issues/35906#issuecomment-434259372 suggest that it might be related to different locales

and indeed, the order is correct when i change the language to en (from de). Looks like a code-smell where someone iterates over these buttons sorted by their labels...

**Comment by bpasero** [comment]
Up for grab if someone has an easy fix.

**Comment by macrozone** [comment]
@bpasero my fix was to change the locale to english 🤦‍♂ which is ok, its anyway often better to just switch your tools to english as a developer: if you have some error message, its easier to google it.

for example, it needed to debug something in the horrible internet explorer and it reported its already cryptic errors in german...

**Comment by bpasero** [comment]
@macrozone you mean VSCode's locale or something else?

**Comment by macrozone** [comment]
@bpasero yes, you can change vscodes language to english: https://stackoverflow.com/questions/36868322/how-to-change-ui-language-in-visual-studio-code
