### ISSUE TITLE
Support to create a new file/folder using an inline action

### ISSUE THREAD

**Issue by 5eyegeo** [microsoft/vscode#85454]
Default features is enough good for creating new files and folder with in the vs code.  But it can still improve. As show in below gif.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50432591/69478408-1c013080-0e1a-11ea-90b1-82a8ee230fb6.gif)

**Comment by isidorn** [comment]
This is a fair feature request, however it is not currently on our plan thus assigning to backlog canddiates
