### ISSUE TITLE
Markdown rendering in Monokai has flaws

### ISSUE THREAD

**Issue by chodorowicz** [microsoft/vscode#85466]
Markdown rendering in bundled Monokai has following flaws:

- links in lists don't are not properly coloured
- headings are not bold
- quotes are not rendered in italic
- bold text is not rendered as bold
- italic text is not rendered in italic font

![image](https://user-images.githubusercontent.com/119451/69485207-8a56ea80-0e3c-11ea-90c4-dbfd4c9907e8.png)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by chodorowicz** [comment]
Sure! Maybe VS Code team has a more thorough test file for markdown file. Anyway, that's the one I've used for testing.

```
# Heading 1
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
###### Heading 6


One morning, when Gregor Samsa woke from troubled dreams, he ~~found~~ himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.

> One morning, when Gregor Samsa woke from troubled dreams, he ~~found~~ himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. [1][]

**bold** __bold__
*italic* _italic_
[Link](http://a.com)
![Image](http://url/a.png)
`inline code`

- list
- list
- [Example](https://example.com)

1. one
2. two
3. [Example](https://example.com)

```js
const a = "a";
```


horizontal rule 👇

---

[1]: https://example.com "Example"
```
