### ISSUE TITLE
MarkdownString in CompletionItem.documentation is very slow to render images with large SVG data URL

### ISSUE THREAD

**Issue by sqd** [microsoft/vscode#85464]
- VSCode Version: 1.41.0-insider
- OS Version: Linux x64 5.3.0-arch1-1-ARCH

```
Version: 1.41.0-insider
Commit: a747d264d668a947eeacd3492b60df6ce8dee6b4
Date: 2019-11-23T11:12:35.768Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-arch1-1-ARCH

```
Steps to Reproduce:

1. Create a `vscode.MarkdownString` with an image with a large SVG data URL. For example: `![graphics](large SVG data url)`
2. Set this `MarkdownString` as a `CompletionItem.documentation`.
3. It takes a while to render this completion documentation and hangs the whole editor in the process. However, when the SVG is not encoded as a data URL and the filepath of this SVG is used instead, it's rendered very quickly. But this doesn't work well with Remote.

Example SVG and the corresponding data URL:
https://s.hanyou.dev/vscode-issue-svg/image.svg
https://s.hanyou.dev/vscode-issue-svg/dataurl.txt

**Comment by jrieken** [comment]
Sure, that somewhat to be expected... That data-uri is 1.8MB and the only solution I see is a workaround to simply drop such long markdown.

**Comment by sqd** [comment]
It's not slow when you use the SVG file though. Is base64 decoding that much of an overhead?

**Comment by jrieken** [comment]
Sure, an inline-url is always much, much slower then a pointer-url, esp when soo large
