### ISSUE TITLE
client area goes blank, no further action will be displayed there

### ISSUE THREAD

**Issue by ssepan2** [microsoft/vscode#85463]
Issue Type: <b>Bug</b>

using vscode to open code folders and perform stage/commits to a series of local git repositories. All goes well for several commits, then client area goes blank when opening a folder and nothign will display there . When vscode is closed and re-opened, opened folder is selected in folders and can proceed normally for a few more projects.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3491)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|7.73GB (1.06GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.3
pascal-formatter|ale|2.2.0
meld-diff|dan|1.0.5
vscode-solution-explorer|fer|0.3.5
vscode-pull-request-github|Git|0.13.0
roslynator|jos|2.2.0
vscode-icon-theme|jtl|1.6.5
csharp|ms-|1.21.8

(2 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Can you attach the log generated when this issue happens by running `code --verbose` ?

**Comment by ssepan2** [comment]
Thanks, I will use this going forward. I just ran a dozen or so Open Folders in a row with no error, but when it happened I was doing Git  Commits and Pushes in between, and it happened after 3 - 4 of them, several times. Cannot re-create that scenario now; maybe when I have a lot of updates again...

**Comment by ssepan2** [comment]
Have not seen issue lately. Closing.
