### ISSUE TITLE
Where are the settings

### ISSUE THREAD

**Issue by Legends** [microsoft/vscode#85461]
Why is this hidden? Under which menu item can I find the settings for extensions???

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Legends** [comment]
I want to change the following setting for an extension:

**Extension Settings
This extension contributes the following settings:

px-to-rem.px-per-rem: number of pixels per rem. Default is 16px.**

**Comment by Legends** [comment]
**Where is this ???**

I don't have this menu path anywhere!

![image](https://user-images.githubusercontent.com/966368/69482974-47881900-0e22-11ea-988c-d7889022a439.png)

**Comment by mdlauriers** [comment]
Hi @Legends , 

Is this what you're looking for? 
Under File->Preferences->Settings ?

![image](https://user-images.githubusercontent.com/20861648/69483757-51e1ed00-0df9-11ea-8ed0-239ff81f03f6.png)

![image](https://user-images.githubusercontent.com/20861648/69483765-60300900-0df9-11ea-8b0c-70c5a9621397.png)

You can also see the JSON format of the settings by clicking the "Open Settings (JSON)" button located at the top right corner. (where you can add your plugin settings)

![image](https://user-images.githubusercontent.com/20861648/69483780-9077a780-0df9-11ea-8d5b-f4a78d7111b9.png)


If you're using Windows you can also use the Ctrl+, shortcut.

Hopefully this can help you!

**Comment by Legends** [comment]
**Yes thanks a lot**. Everything looks the same in VsCode, gray color on dark background, no coloured icons for easier distinction.

A ok, here are the extension settings:

![image](https://user-images.githubusercontent.com/966368/69484066-182bd900-0e2f-11ea-8c3a-ba413438a64c.png)
