### ISSUE TITLE
Investigate why configuration via symlinks no longer update

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8547]
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open settings
2. Change a setting that should have an immediate impact, notice there is no change

I have a feeling this is because I have my settings.json symlinked and it's not being watched correctly.

```
❯ ls -la ~/.config/Code\ -\ Insiders/User
total 16
drwx------ 4 daniel daniel 4096 Jun 23 22:46 .
drwx------ 8 daniel daniel 4096 Jun 27 03:38 ..
drwx------ 2 daniel daniel 4096 Mar  2 10:58 snippets
drwxrwxr-x 5 daniel daniel 4096 Jun 27 02:24 workspaceStorage
lrwxrwxrwx 1 daniel daniel   47 May 21 16:20 keybindings.json -> /home/daniel/.config/Code/User/keybindings.json
lrwxrwxrwx 1 daniel daniel   44 May 21 16:20 settings.json -> /home/daniel/.config/Code/User/settings.json
```

**Comment by bpasero** [comment]
That is a scenario we do not support officially.

**Comment by Tyriar** [comment]
It worked completely fine until a few days ago FYI. I've been using this setup for several months.

**Comment by Tyriar** [comment]
@bpasero any idea what could have changed with this? Did someone touch any watching logic recently? I'd rather fix this in vscode than change my dotfiles to duplicate the files.

**Comment by bpasero** [comment]
No nothing changed as far as I know, but feel free to investigate and PR me if you found something.
