### ISSUE TITLE
IBM blockchain platform issue 

### ISSUE THREAD

**Issue by turboyin** [microsoft/vscode#85474]
What mean "Unsupported engine for fabric-shim@1.4.2: wanted: {"node":"^8.9.0","npm":"^5.5.1"} (current: {"node":"13.1.0","npm":"6.12.1"}) " ??

**Comment by apalaniuk** [comment]
Nothing to do with VS Code. Your versions of node/npm are outside [the range](https://docs.npmjs.com/misc/semver) of those `fabric-shim@1.4.2` claims to work with. [It's advisory only by default](https://docs.npmjs.com/files/package.json#engines).
