### ISSUE TITLE
Compiler path with spaces and arguments is missing double quotes " around path.

### ISSUE THREAD

**Issue by AMDphreak** [microsoft/vscode#85478]
- VSCode Version: 1.40.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open C/C++ Configurations page
2. Go to `Configuration Name` section.
  a. Notice that the default config (Win32)'s Compiler path is a string with spaces, without double quotes.
3. Add Configuration. Name it "Linux".
4. Enter any string in the `Compiler Path` field like `C:/Program Files/LLVM/bin/clang.exe`.

![image](https://user-images.githubusercontent.com/1058978/69488997-bfad0980-0e37-11ea-8e19-f35c519a0bee.png)

The program will complain when it saves:
```
Compiler path with spaces and arguments is missing double quotes " around the path.
```
If you put double quotes around it and then switch back to the default config (Win32), and then switch back to the Linux config, it strips the double quotes from the string and complains some more.

If you are patient enough to click the single line of pixels around the text box to get the drop-down menu to show you the detected compilers on the system, and you then select the exact same compiler path, it will insert the path, without quotes, and complain some more.

----

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
Please report the issue against the C++ extension.
