### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by CatKinKitKat** [microsoft/vscode#85473]
I can't save ' é ' in any encoding, and it is messing with my batch scripts. My teacher wants explicitly this with that special character.
What can I do? Is it a problem from VSCode encoding mechanisms or just plain batch incompatibility?

**Comment by CatKinKitKat** [comment]
Here's the little garbage I wrote, if it helps or something...
Down here:


ECHO OFF

ECHO EugenioEngWD

setlocal enableDelayedExpansion

set OriginalDir=%CD%

set EugenioPath="C:\Program Files\Eugénio"
set WordsPath="B:\Users\gonca\Downloads\EugenioEngWD\words_dic"
set SentencesPath="B:\Users\gonca\Downloads\EugenioEngWD\sentences_dic"

robocopy %WordsPath% %EugenioPath%
robocopy %SentencesPath% %EugenioPath%

cd %EugenioPath%

rename words.txt geral.pal
rename words_pairs.txt geral.par
rename sentences.txt geral.frs
rename sentences_pairs.txt geral.paf

ECHO TUDO COPIADO COM SUCESSO

PAUSE

**Comment by sunbohong** [comment]
Hi,@CatKinKitKat  You can Set the file encoding globally or per workspace by using the files.encoding setting in User Settings or Workspace Settings.
https://code.visualstudio.com/docs/editor/codebasics#_file-encoding-support

**Comment by CatKinKitKat** [comment]
Thanks. I will try that and update you with the result.
