### ISSUE TITLE
OUTPUT PROBLEM

### ISSUE THREAD

**Issue by shihaoxinji** [microsoft/vscode#85477]
Issue Type: <b>Bug</b>

when  I use code runner，the output is different from debug console。
my test code is ：
`a = '{0:^8}\t{1:{3}^8}\t{2:^8}'
print(a.format('学生序号', '姓名', '分数', chr(12288)))
print(a.format('01', '张三', '80', chr(12288)))
print(a.format('02', '诸葛小三', '80', chr(12288)))`
output display：
![image](https://user-images.githubusercontent.com/53935835/69488454-721ab600-0ea4-11ea-8fa7-5f7b2f9f412e.png)
but when i use debug，dubug console display：
![image](https://user-images.githubusercontent.com/53935835/69488471-98405600-0ea4-11ea-9be6-0406b264b46f.png)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (4.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.0
code-runner|for|0.9.15
vscode-language-pack-zh-hans|MS-|1.40.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
vscode-yaml|red|0.6.1
python|tht|0.2.3

</details>

**Comment by egamma** [comment]
This output is produced by the python debugger, please file the issue against the python extension.
