### ISSUE TITLE
Absolute paths in Go test output not clickable links in the output panel

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode#85476]
This was originally reported in https://github.com/microsoft/vscode-go/issues/1719, but it was thought that this is a broader issue.

### Versions

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0 [macOS 10.14.6 (18G87)]

### Steps to Reproduce

1. Install the Go extension.
2. Make a directory named foo.
3. Make a file foo_test.go in directory foo containing this:

```go
package foo

import "testing"

func TestFoo(t *testing.T) {
    panic("show stacktrace")
}
```

4. Run the test, either using CodeLens or right-clicking on the function and clicking "Go: Test Function At Cursor".
5. Observe the file paths in the panic stack trace in the test output that aren't clickable:

<img width="774" src="https://user-images.githubusercontent.com/63830/69488530-51f4e380-0e1f-11ea-9ecd-dda3f59a1a0d.png">

### Does this issue occur when all extensions are disabled?

Unknown. I only work with Go code, which is what triggered this particular output. Perhaps other languages also trigger output with /usr/local paths, but I don't know offhand how to make that happen without an extension.

**Comment by sandy081** [comment]
@isidorn Assume you are responsible for output link computation and hence assigning to you.

**Comment by isidorn** [comment]
Unfortunetly we do not have a unified link detection strategy. So debug has its own `LinkDetector` and output uses the editor `LinkDetector` from [here](https://github.com/Microsoft/vscode-distro/blob/64ce8af52777bb856aac78800918a38832f2c65d/src/vs/editor/contrib/links/links.ts#L100)
Leaving this open as a feature request though
