### ISSUE TITLE
Move some menu items into a "New tab" page

### ISSUE THREAD

**Issue by AMDphreak** [microsoft/vscode#85470]
The VSCode editor is not by any measure a discoverable interface. 90% of the important things in VSCode are hidden in the `Ctrl Shift P` command that opens the unintuitive command interface. Other features are stuffed in ad-hoc places in the side-bar and in the main menu's drop-down lists.

I use VSCode with main menu hidden and side-bar hidden to have a clean distraction-free coding experience.

To access the settings and preferences, it would be very nice to have a "Home page" or "New page" similar to the "Welcome" page that has important links in it. The "Welcome" page is limited in its usefulness because it is not summonable at will and only shows on startup.

Having a "New" page would be in line with VSCode's general design pattern of making things very tab-oriented.

![image](https://user-images.githubusercontent.com/1058978/69486694-1acd0500-0e14-11ea-9aee-c6cf3c7acbbb.png)

It would also be nice to be able to manage multiple projects in the same window. Currently, managing projects in multiple windows means that all but one of the projects must be closed when shutting down VSCode. This is dysfunctional for multi-project workflows. An idea would be to provide a single process that manages the other project windows and re-launches them when launching the main program. This does, however, interrupt the flow between multiple projects, since Microsoft Windows is miserable at coordinating multiple windows within the same application (ironically).

**Comment by chrmarti** [comment]
You could assign a keybinding to the Welcome page. And there is a setting to restore all windows after restart:
![image](https://user-images.githubusercontent.com/9205389/69522156-00ed0880-0f61-11ea-81e4-f21a53bfede9.png)
