### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by adigon2006** [microsoft/vscode#85487]
Issue Type: <b>Bug</b>

Ctrl + Space

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.1
react-native-snippet|jun|0.5.5
mssql|ms-|1.7.1
python|ms-|2019.11.50794
powershell|ms-|2019.11.0
vscode-typescript-next|ms-|3.8.20191123
vscode-react-native|msj|0.13.1
JavaScriptSnippets|Tem|0.5.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by egamma** [comment]
/needsMoreInfo

where exactly does Intellisense not working, please provide detailed steps an provide a sample.

**Comment by mikionakajima** [comment]
Hello,
I also can not use InteIliSence.

I'm using vscode(1.40.1) on linux(Lubuntu19.10) with PlatformIO.
When I install PlarformIO, the system  installs 'c/c++' extension automatically.
IntelliSence works fine with 'c/c++' extension Version 0.26.1: October 28, 2019 
IntelliSence  can not work with Version 0.26.2-insiders2.
I downgrade the extension by using its preference, but the system update it automatically.......
I should mange the version of extension every 5 min.

**Comment by egamma** [comment]
@mikionakajima this looks like another issue, the original reporter doesn't have this extension installed. Please file a new issue with reproducible steps against the C++ extension.
