### ISSUE TITLE
multi cursor + ctrl

### ISSUE THREAD

**Issue by PuyaGoodarzi** [microsoft/vscode#85485]
Issue Type: <b>Feature Request</b>

Ctrl + multi cursor does not working to select some seperated lines in one page

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17134

**Comment by egamma** [comment]
/needsMoreInfo please describe in detail the expected behaviour and illustrate it with screenshots.
