### ISSUE TITLE
File count on problems view title doesn't match filtered problem count

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#85486]
Issue Type: <b>Bug</b>

I have a spell checking extension that contributes a bunch of `Info`'s for each file. In the Problems panel's filter, I filter those out. Yet, the Problem's panel title still counts them, even though I have marked them as not relevant. I think the problem count in the title should reflect how many problems there are, minus those which have been filtered out. 

![image](https://user-images.githubusercontent.com/8586769/69491102-6ba92180-0e45-11ea-89a2-0d2a92cffdd5.png)

Note that if I type a filter query, rather than check a filter type, I get a message saying "Showing N of M". At the very least, this should also appear when I filter by type. 

But ideally, the problems title would always reflect the number of problems in the tree.

**Comment by sandy081** [comment]
/duplicate

#74902
