### ISSUE TITLE
powershell ext - processing of quoted string that contains @ doesn't recognize terminating quote

### ISSUE THREAD

**Issue by mlhickey** [Microsoft/vscode#8548]
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:07:11.483Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Enter function  $next = $jsonObj.'@odata.nextlink'
2. Parser treats this as an unbalanced/unterminated string, all subsequent text color coded as string content

[example.ps1.txt](https://github.com/Microsoft/vscode/files/340445/example.ps1.txt)

**Comment by bpasero** [comment]
Please report this against the Powershell extension. Thanks!
