### ISSUE TITLE
File Save Polkit pkexec Sudo Error using --file-write: EACCES: permission denied

### ISSUE THREAD

**Issue by dimyself** [microsoft/vscode#85481]
- VSCode Version: 1.40.1
- OS Version: Linux 5.3.12-arch1-1

Steps to Reproduce:

1. I try to save a file owned by root and it prompts for sudo.
2. I give my sudo password, and it fails with the below info

Does this issue occur when all extensions are disabled?: Yes/No

I am getting this same error, but I have electron 6.1.1. I'm getting a similar error:

```
Failed to save 'file.py': Command failed: cd "/home/myuserid"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; \"/usr/bin/code\" --file-write \"/tmp/code-elevated-rukwep\" \"/usr/lib/python3.7/site-packages/.....file.py\"" Error using --file-write: EACCES: permission denied, open '/tmp/code-elevated-rukwep'
```
![Screenshot_2019-11-23_23-12-52](https://user-images.githubusercontent.com/36783626/69490025-e6bf0780-0e46-11ea-9ebe-abd106b5e141.png)

When I check permissions of the file it's referencing: /tmp/code-elevated-rukwep ...permissions seem like they should be accessible. The file is owned by my id:

```
$ ls -la /tmp/code-elevated-ystztl 
-rw-r--r-- 1 myuserid myuserid 14932 Nov 23 23:20 /tmp/code-elevated-ystztl
$ 
```
However, the file I'm trying to write to or overwrite is located in /usr. The file is owned by root:

```
$ ls -la /usr/lib/python3.7/site-packages/....file.py
-rw-r--r-- 1 root root 14931 Nov 23 03:15 /usr/lib/python3.7/site-packages/....file.py
$
```

Also, if I run any normal sudo command in the terminal window through vscode terminal, that works fine...

Thanks

**Comment by bpasero** [comment]
@jorangreef may I ask if you have a clue?

**Comment by jorangreef** [comment]
@bpasero, sure, I am going to be away the next few days but will help out with this when I can.

In the meantime, is this Arch Linux?

**Comment by bpasero** [comment]
@dimyself what exact OS is this?
