### ISSUE TITLE
CTRL N opens a new file and its not editable

### ISSUE THREAD

**Issue by diaraujo13** [microsoft/vscode#85492]
Issue Type: <b>Bug</b>

CTRL+N
Creates a new file UNtitled
It's blocked for edition

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|15.54GB (1.75GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|10.6.0
html-class-suggestions|And|1.0.7
Handlebars|and|0.4.1
dustjs|Azk|0.1.1
spellright|ban|3.0.48
color-info|bie|0.5.1
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
bower|don|0.0.3
jquerysnippets|don|0.0.1
bowerwatcher|eal|0.0.1
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
carbon-now-sh|eri|1.2.0
php-intellisense|fel|2.3.13
file-icons|fil|1.0.19
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.15
terminal|for|0.0.10
vscode-yarn|gam|1.6.0
package-watcher|Gre|0.0.2
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.5.0
vscode-git-tags|how|1.4.3
gsap-snippets|Hri|1.0.0
gsap-code-snippets|iha|1.0.1
path-autocomplete|ion|1.13.3
easy-icons|jam|0.3.1
svg|joc|1.0.5
vscode-peacock|joh|3.2.0
vscode-colorize|kam|0.8.15
vscode-gutter-preview|kis|0.23.0
node-module-intellisense|lei|1.5.0
quicktask|lky|3.5.5
code-beautifier|mic|2.3.3
gitignore|mic|1.0.1
vs-deploy|mkl|14.0.0
vscode-scss|mrm|0.8.1
vscode-language-pack-pt-BR|MS-|1.40.2
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.1
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
gi|rub|0.2.11
vscode-sass-format|sas|1.1.6
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
vscode-spotify|shy|3.1.0
code-spell-checker|str|1.7.20
vscode-gulp|tan|0.0.4
wordpress-snippet|tun|1.1.5
markdown-all-in-one|yzh|2.5.1
material-theme|zhu|3.1.0

(5 theme extensions excluded)

</details>

**Comment by egamma** [comment]
/needsMoreInfo cannot reproduce given the information provided.
