### ISSUE TITLE
vscode does not load any extensions

### ISSUE THREAD

**Issue by MK-SMK** [microsoft/vscode#85494]
Issue Type: <b>Bug</b>

I have installed the following extensions:
austin.code-gnu-global-0.2.2
ms-vscode.cmake-tools-1.2.2
ms-vscode.cpptools-0.26.1
twxs.cmake-0.0.17
vscode-icons-team.vscode-icons-9.5.0

The extensionlist via F1-> "Developer: Show running extensions"  is empty.
I can't debug. If I push on Debug->Add Configuration, nothing happens. In the statusbar the text "Activating Extensions..." appears but takes no effect.

The list is still empty, no config.json file is opened. And if I create a config.json file manually, nothing happens. If I then start debugging nothing still happens.

The extension folders all have user rights.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.3.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (12.66GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cmake-tools|ms-|1.2.2
cpptools|ms-|0.26.1
cmake|twx|0.0.17
vscode-icons|vsc|9.5.0

</details>

**Comment by MK-SMK** [comment]
ps: I've reinstalled vscode several times. I installed it via apt install, via deb package, even the insider preview.. everytime the same problem. On my Laptop, I have installed the newest version of vscode too, there I can normaly debug. Everything works fine there. It has Linux Mint installed too. It has installed Linux Kernel 5.3.6-050306.

**Comment by egamma** [comment]
/needsMoreInfo are there any error message in the Console of the Developer Tools (Help>Toggle Developer Tools)?

**Comment by MK-SMK** [comment]
I've fixed ist by myself: I had to unset the environment variable `LD_LIBRARY_PATH`. I determined the files, who `export` this variable at startup and commented them out. Now, everything works fine.
