### ISSUE TITLE
Insider build always starts language server with debug options

### ISSUE THREAD

**Issue by jvalkeal** [microsoft/vscode#85490]
EDIT from @egamma: The reporter implements a custom language server https://github.com/spring-projects-experimental/vscode-spring-cloud-dataflow using the vscode-language client 

----

I have a different `run` and `debug` arguments in `ServerOptions` and it looks like even if I install my extension via vsix file debug options are used instead of run options when extension is activated and language server gets started.

This only happens with current `1.41.0-insider` and `1.40.1` is working as expected.

```
Version: 1.41.0-insider
Commit: a747d264d668a947eeacd3492b60df6ce8dee6b4
Date: 2019-11-23T11:12:35.768Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-70-generic
```
Didn't really find any matching issues either from vscode or vscode-languageserver-node so created a new one.

I think easiest way to see this is to use `azure-pipelines-vscode` and see processes:

```
/usr/share/code/code /home/jvalkealahti/.vscode/extensions/ms-azure-devops.azure-pipelines-1.157.4/node_modules/azure-pipelines-language-server/server.js --node-ipc --clientProcessId=25308

/usr/share/code-insiders/code-insiders --nolazy --inspect=6009 /home/jvalkealahti/.vscode-insiders/extensions/ms-azure-devops.azure-pipelines-1.157.4/node_modules/azure-pipelines-language-server/server.js --node-ipc --clientProcessId=26210
```

As they use different options per https://github.com/microsoft/azure-pipelines-vscode/blob/e953e22614191b18540c6d36b608098be6eae7cc/src/extension.ts#L96-L99

**Comment by jvalkeal** [comment]
Our extension is still in development and thus difficult to use as it's not in a marketplace but as I said I found similar behaviour with `azure-pipelines-vscode` extension, afaik.

**Comment by dbaeumer** [comment]
This is very likely a side effect that the extension host is now started using --ìnspect-port`.

@jrieken before that change how did we start the extension host.

The problem is very likely here where we test if we need to start the language server in debug mode.

**Comment by dbaeumer** [comment]
I made my checks more precise here: 

https://github.com/microsoft/vscode-languageserver-node/commit/4f8e3e18f5ac181cd6a5f7e11d4d601c5d9bd511

To fix this for the recovery build we decided to remove `--inspect-port` internally from the process execArgv again.

@jrieken @chrmarti told me this would be doable for you. I assign the issue to you so that we have something to track.

**Comment by dbaeumer** [comment]
Extension host started with:

<img width="400" alt="capture" src="https://user-images.githubusercontent.com/1931590/69557928-acb94700-0fa7-11ea-8bf7-fd5404b2c5a0.png">

Servers still without `--inspect` 

<img width="429" alt="capture" src="https://user-images.githubusercontent.com/1931590/69558016-d3777d80-0fa7-11ea-8aaa-ee41a08b18c9.png">

and

<img width="412" alt="capture" src="https://user-images.githubusercontent.com/1931590/69558095-ef7b1f00-0fa7-11ea-9729-2cd9b5478891.png">
