### ISSUE TITLE
Visual Studio crashes by Clicking on Help->About

### ISSUE THREAD

**Issue by MK-SMK** [microsoft/vscode#85493]
Issue Type: <b>Bug</b>

By Clicking on the menu entry Help->About, vscode crashes.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.3.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.57GB (12.30GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
systemverilog|eir|0.9.1
cpptools|ms-|0.26.1
veriloghdl|msh|1.0.4
vivado-ucf-constraints|msh|0.0.3
vscode-icons|vsc|9.5.0

</details>

**Comment by MK-SMK** [comment]
I allready checked for duplicates. I could not find a duplicate nor a solution

**Comment by deepak1556** [comment]
@MK-SMK can your try the latest insiders https://code.visualstudio.com/insiders/ and see if it still crashes.

Also what does the terminal print when you run the stable version with `code --verbose` ?

**Comment by MK-SMK** [comment]
[log_about.txt](https://github.com/microsoft/vscode/files/3885532/log_about.txt)

**Comment by deepak1556** [comment]
Thanks for the log!

> /opt/Xilinx/14.7/ISE_DS/ISE/lib/lin64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found

seems to be the culprit thats preventing loading any native node modules bundled with vscode, You should update `libstdc++` package for your distro.

Once done make sure `> strings <path-to-library>/libstdc++.so.6 | grep GLIBCXX_3.4.18` has one of its content.

Closing this out as no further action can be taken on vscode end.

**Comment by MK-SMK** [comment]
libstdc++.so.6 is already up to date 
[libstd_log.txt](https://github.com/microsoft/vscode/files/3889054/libstd_log.txt)

And this is the result for the grep command:
[glibcx_log.txt](https://github.com/microsoft/vscode/files/3889057/glibcx_log.txt)

**Comment by deepak1556** [comment]
what does `strings <path-to-library>/libstdc++.so.6 | grep CXXABI` print ? Is this library from the same path as the one vscode was trying to use, from your original log `/opt/Xilinx/14.7/ISE_DS/ISE/lib/lin64/libstdc++.so.6` ?
