### ISSUE TITLE
Q# (python.vs code) new console >python file

### ISSUE THREAD

**Issue by Hydrogen-c** [microsoft/vscode#85496]
from <...> 
Red underline error prompt.
It's not appropriate Error

**Comment by Hydrogen-c** [comment]
<img width="831" alt="Annotation 2019-11-25 091036" src="https://user-images.githubusercontent.com/51038863/69505190-81ad0400-0f63-11ea-9fe3-c756bd5fa34c.png">

A small mistake.

**Comment by egamma** [comment]
Please file the issue against the quantum extension.
