### ISSUE TITLE
Pinch to zoom causes UI confusion

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vscode#8549]
- VSCode Version: 1.3.0-insiders 798b41ab1cf3636a27042020a54ddfb4cfb8d23c
- OS Version: 10.11.5

1. Use a Mac's trackpad and the pinch to zoom gesture within a Code window
2. The content's size is heavily zoomed in or out
3. There's no obvious way to reset the zoom level

Anything I'm missing about this? If not, can we improve this or disable pinch to zoom completely?

**Comment by bpasero** [comment]
Yeah, I raised similar issues.

**Comment by alexandrudima** [comment]
Let's track in #8282
