### ISSUE TITLE
do not try to reconnect on real quit

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#855]
I think we should start to look into a solution to this because we are now adding workarounds for this issue when running unit tests: The issue is that when the unit test is done, I quit the PH with process.exit(). This nicely closes the window but the debugger wants to reconnect right after and fails (not with an error message, but its weird to see the debug viewlet progress spinning for 2 seconds). 

We also see this when you Cmd+Q the extension host to terminate the session.

I am open to ideas what to do here, somehow the PH needs to signal back how it was terminated.

**Comment by isidorn** [comment]
I have exposed the rawAttach in my debug api, Ben will try it out and we see if something else is needed.

**Comment by egamma** [comment]
Update from @weinand 

We have finished the restructuring work on ExtensionHost (EH) debugging and I've verified that it works on OS X, Windows, and Linux.
It feels snappier and the VS Code debugger no longer waits 5 seconds after the user has closed the EH window. 

The only remaining issue I've seen so far is that on Windows pressing the red debug Stop button, doesn't close the EH window.
So you have to close the EH window manually.
This seems to be a timing issue and I'll investigate right after this mail (It is a Heisenbug that does not occur when trying to  debug the problem...).
