### ISSUE TITLE
Unable to open the application (version 1.40 of VSC) on Mac OS 10.15.1

### ISSUE THREAD

**Issue by ZachBucek** [microsoft/vscode#85503]
Seems like this issue regarding Catalina is still a problem:
"Visual Studio Code can't be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information."

**Comment by egamma** [comment]
duplicate of https://github.com/microsoft/vscode/issues/74782

**Comment by sathishstar** [comment]
Still having the issue while installing by home-brew command prompt..

<img width="922" alt="Screenshot 2019-11-26 at 10 26 00 PM" src="https://user-images.githubusercontent.com/14369878/69655202-13b82800-109c-11ea-916d-45c69e936a9a.png">
