### ISSUE TITLE
VS Code is not able to copy text after a  NUL character to clipboard

### ISSUE THREAD

**Issue by raze92** [microsoft/vscode#85508]
Issue Type: <b>Bug</b>

I want to copy entries of a logfile in VS Code to the clipboard. From time to time the logfile contains the ASCII charackter NUL (null).  If I want to copy a part of the log, which contains the char NUL, then VS Code copies only the text up to the NUL character, everything behind the NUL char (NUL included) get lost. 

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
stackoverflow-search|Ale|1.2.0
bracket-pair-colorizer-2|Coe|0.0.28
LogFileHighlighter|emi|2.6.0
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.162
vscode-peacock|joh|3.2.0
svn-scm|joh|2.1.3
rainbow-csv|mec|1.3.1
python|ms-|2019.11.50794
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.1
title|nil|0.1.0
code-spell-checker|str|1.7.20
mako|tom|0.2.0
code-navigation|vik|0.2.0
clang-format|xav|1.9.0
vscode-proto3|zxh|0.3.0

</details>

**Comment by alexdima** [comment]
I believe Chromium does not write strings after a null character to the clipboard on Windows. I am not sure if this is a Chromium limitation or a Windows limitation, but AFAIK there is nothing special in our code that would prohibit this.

**Comment by alexdima** [comment]
I believe this is a Windows limitation, I have tried Notepad and SublimeText and I cannot get anything after a NUL character in the plaintext clipboard.

Given this latest finding, I will close the issue since, IMHO, this is an OS limitation

**Comment by raze92** [comment]
I can copy the complete text in notepad++ into the clipboard if there is a NULL character in it. Only the NULL character itself will not be saved to the clipboard, but the rest of it will be. So its not a Windows limitation. 

Is it not possible to implement it in VS Code that it just copies all the text in the clipboard without a NULL character? Removing all Null character before set into the clipboard.

**Comment by alexdima** [comment]
> I can copy the complete text in notepad++ into the clipboard if there is a NULL character in it. Only the NULL character itself will not be saved to the clipboard, but the rest of it will be. So it's not a Windows limitation.

Interesting. That sounds like Notepad++ has implemented a workaround where they remove NULL characters from the text before writing to the Windows clipboard. That means that technically a different string is written to the clipboard than the initial one.

So if I open a file with a NULL character, do ctrl+a and create a new file and do ctrl+v, the contents of the files will be 99% the same, the NULL characters will be missing from the second file. IMHO that is also broken, but in a different, perhaps more subtle way.
