### ISSUE TITLE
Extract to constant is not multicursor aware.

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#85507]
Issue Type: <b>Feature Request</b>

Ex: 

```ts
let foo = computeThing()
let bar = computeThing()
let baz = computeThing() 
```

Select `computeThing()`. 
Run `Select all occurrences of find match` (or just select them yourself). 
Run `Extract to Constant in ... scope`
Bug: only the first instance gets renamed. I think if there is a multicursor selection over many identical items, they should all be replaced by the constant.

VS Code version: Code - Insiders 1.41.0-insider (a747d264d668a947eeacd3492b60df6ce8dee6b4, 2019-11-23T11:08:24.747Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
This quickly gets complex. Multiselect of the same expression maybe makes sense, but different expressions?

I don't think the use case is strong enough to warrant the complexity this would add

**Comment by JacksonKearl** [comment]
I think the use case is very strong, and we can make it only apply if the expressions are identical. 

This is probably the most common refactor I perform, as I do it whenever I notice I'm using the same expression in a number of places. 

My steps:
1. Select an instance of the expression
2. Copy
3. select all occurrences (Cmd+Shift+L)
4. type the new name
5. Navigate to top of containing scope and type `const [type the new name again] = [paste]`.

Currently thats my best bet, the other option is to:
1. Select an instance of the expression
2. Extract Constant
3. Type the name
4. Manually select the next instance
5. Command+D a bunch of times to select all (being careful to not go one too far)
6. Type the new name again.

With this proposal:
1. Select an instance of the expression
2. Select all occurrences (Cmd+Shift+L)
3. Extract Constant
4. Type the name

Much easier.

**Comment by mjbvz** [comment]
I understand the desire, but JS/TS refactorings have no concept of multiple selections today so this would be a large amount of work

I also think there are more discoverable ways this could be implemented, since multi-cursor is a fairly advanced feature. My proposal is that this is more automated:

- You select an expression and run extract constant
- If there are other instances of the same expressions in the current scope, then:
    - Either automatically include those 
    - Or show a prompt asking if those should be included as well

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/35349 for this
