### ISSUE TITLE
Tabs in high contrast are difficult to differentiate when the editor is not active

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8550]
#7854

- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 4.4.0-24-generic

![image](https://cloud.githubusercontent.com/assets/2193314/16472868/ee05b19a-3e1c-11e6-931e-fb60be8c5c24.png)

It's actually higher contrast on a dark theme 

![image](https://cloud.githubusercontent.com/assets/2193314/16472880/0bc419b0-3e1d-11e6-9b81-d08a7d9ebbec.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8564
