### ISSUE TITLE
native es-Module IntelliSense import does not import correct path.

### ISSUE THREAD

**Issue by xXACCEXx** [microsoft/vscode#85502]
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-31-generic snap

Steps to Reproduce:

1. Create an ES Module and export something
    `export const something = 'something';`
2. Create another file and start typing 'something' to trigger suggestions
    ![image](https://user-images.githubusercontent.com/13444599/69499608-ef4b3700-0f47-11ea-93ca-4ab345c76f8d.png)
3. Press 'Enter' or something to apply this prompt
    ![image (1)](https://user-images.githubusercontent.com/13444599/69499620-0ee25f80-0f48-11ea-8ac6-8a7885eb3026.png)
4. Run in Browser (or Node.js with --experimental-modules flag)
    ![image](https://user-images.githubusercontent.com/13444599/69499659-83b59980-0f48-11ea-8318-9dfa36f849b3.png)

Does this issue occur when all extensions are disabled?: Yes

My goal is to import files using the IntelliSense prompts for the correct module (native JS with ES Modules).

I would expect the path to be correctly injected, however the extension is missing, which does not comply with ES module standards for paths.

What I am seeing instead, is an almost complete path. But it is missing the file extension (if it is needed)

Currently, I am supplying the file extension manually afterwards the IntelliSense inserts the path.

This is only a problem when using ES Modules and browser/Node.js, as the cjs pattern is fine with resolving the extension (either at compile or run time, respectively)

**Comment by mjbvz** [comment]
Thanks. This is currently tracked upstream by https://github.com/microsoft/TypeScript/issues/28288

I've marked it as a priority feature for TS since we see this reported fairly often
