### ISSUE TITLE
Extension development: Support ICU

### ISSUE THREAD

**Issue by mechatroner** [microsoft/vscode#85517]
I was developing my extension and discovered that "ICU" is currently not supported in VSCode.
When I create a util.TextDecoder object (you can reproduce this in the debug console):
```
const util = require('util');
let decoder = new util.TextDecoder('utf-8', {fatal: true, stream: true});
```

I get the following error:
```"fatal" option is not supported on Node.js compiled without ICU```

Please add ICU support.

As far as I know it is impossible to reliably decode utf-8 data in Node without util.TextDecoder.

**Comment by mechatroner** [comment]
Relevant links:
https://github.com/electron/electron/issues/2563
https://github.com/nodejs/node/issues/26115
https://github.com/electron/electron/issues/18733

**Comment by egamma** [comment]
duplicate upstream issue.
