### ISSUE TITLE
gup-process has 100% cpu usage

### ISSUE THREAD

**Issue by SamuelZon258** [microsoft/vscode#85519]
![580DD7E9-B74C-45E8-94A3-4046772F66AF](https://user-images.githubusercontent.com/17244763/69515658-378b4900-0f8a-11ea-923d-d0f26caaef72.png)

**Comment by egamma** [comment]
/needsMoreInfo please follow this guide to narrow down performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues.

**Comment by ZonSamuel** [comment]
I have not installed any extensions
![1574677718900](https://user-images.githubusercontent.com/17244763/69532851-a5973680-0fb1-11ea-9555-b7b5e1cfc714.jpg)

**Comment by egamma** [comment]
Closing - since the issue was reported performance work happened in tsserver, pls reopen a new issue if the problem still shows up using the guidelines described here https://github.com/microsoft/vscode/wiki/Performance-Issues.
