### ISSUE TITLE
Tab high contrast border shifts tab text when active

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8551]
#7854

- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 4.4.0-24-generic

Notice the text is aligned slightly differently. Whenever you make a tab active, both the previously active and the new active tab text shifts by 1 px. I think it may also shift horizontally too.

![image](https://cloud.githubusercontent.com/assets/2193314/16472915/8ff72cc2-3e1d-11e6-9ea5-2dd6f66bfc3b.png)

**Comment by bpasero** [comment]
When you enable HC mode, for me many areas of the UI have this issue, not just tabs. I do not think this is a big deal but moving to our HC master @bgashler1

**Comment by bgashler1** [comment]
Yeah, that bothered me too.  It's fixed in my latest PR #8238.

Borders were offsetting the active tab, so I added transparent borders on all inactive tabs.

**Comment by Tyriar** [comment]
`outline` is typically used for this over `border` as the outline is overlayed on top, not inserted around the element.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8564
