### ISSUE TITLE
Lost all unstaged work!!

### ISSUE THREAD

**Issue by t3db0t** [microsoft/vscode#85512]
Issue Type: <b>Bug</b>

I had made a number of changes to various files. I went to commit as always, and I noticed that the "current branch" was a hex string, not the name of a branch as usual. I couldn't find any branch id that it referred to. When I went to make the commit, it said I couldn't make a commit because I hadn't checked out a branch. When I checked out the branch I thought I was already on, I lost all my work!!

I checked all my stashes. I checked all my other branches. I see nothing at all because I never got to make a commit.

Then on a whim I decided to try hitting "undo" on each file I had made changes on—even though they already show as "saved" and thus have no changes to revert—and lo and behold, I got my work back!!

I don't know how to reproduce this, but this seems like a potentially serious bug, so I hope it's helpful somehow...

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|4.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.12.1

</details>

**Comment by joaomoreno** [comment]
Great that you have "recovered" your work. It seems like you never lost it at all.

---

Something doesn't fit right in the story. First you mention:

> When I checked out the branch I thought I was already on, I lost all my work!!

Which means that the files are no longer listed in the Git view... but then:

> Then on a whim I decided to try hitting "undo" on each file I had made changes on

How is that possible?
How did you do this, if the files weren't listed in the view?

**Comment by t3db0t** [comment]
I'm not sure why you're being so condescending. For all intents and purposes, VSCode indicated that the code was lost. It was only by chance that I discovered that "undo" would have any effect, even though the files were displaying as saved and unedited, in which state "undo" would normally not do anything.

> Something doesn't fit right in the story

Why are you acting like you're a lawyer and I'm on trial? Do you think I'm making up bullshit and taking the time to submit an issue because I like wasting my own time?

This is what happened:

a) I went to make a commit as usual. I noticed that the lower-left branch name displayed a hex string of about 10 digits with an asterisk instead of the normal branch name that has always been there. I had never seen this happen before and I'm not sure what put it into this state.

b) Upon attempting to commit, I received an error message that said something like "You cannot commit because no branch has been selected." I thought that was pretty bizarre, as I did of course have all my files checked out and I was editing them.

c) Because I figured there was no way I could accidentally lose any work, I clicked on the branch name and checked out the branch I thought I was on. At this point, all my changes disappeared, and the files appear unedited (which is what happens normally when you check out a branch, except that normally git would require me to stash existing changes).

I don't know how to replicate it, unfortunately, and I understand that this is not actionable. But jesus, I figured someone might at least want to know this happened. If you don't want to believe me, I guess that's your prerogative.

**Comment by joaomoreno** [comment]
Apologies if I came out wrong. I'm trying to be concise and ask the right questions. I do believe you, but I also have to get the facts straight, in order to understand where the issue happened.

> At this point, all my changes disappeared, and the files appear unedited (which is what happens normally when you check out a branch, except that normally git would require me to stash existing changes).

Is it possible that your changes were all in untracked files which are simply ignored by `.gitignore` in the branch to which you checked out?

**Comment by t3db0t** [comment]
> How did you click "undo" on each file if all the changes disappeared

I'm not exactly sure what you mean. I mean this is part of the strange behavior. I had made changes to the file. Saved. Tried to commit. Forced to checkout a branch (that I thought was already checked out). Changes were wiped and files reverted to the last commit in that branch (which is what normally happens when you check out a branch, except normally git doesn't let you toss changes without explicitly forcing it).

The file editors at that point looked like normal files that didn't have any unsaved changes. I hit "undo" anyway. Maybe that itself is a bug. And undo brought my changes back somehow.

> untracked files which are simply ignored by .gitignore

No, these are all files I've successfully committed many many times, and have since as well.

Very strange :( I wish I could offer something more. I think the heart of the problem was that somehow I got into this strange state where either git or VSCode thought I didn't have a branch checked out. Where normally it says the branch name in the bottom left, it just had a hash that didn't correspond to any commits or branches (that I know of).

Anyway—I don't think there's any more information I can provide, but on the off chance this happens again to someone, maybe we'll at least know it wasn't an isolated incident? :/

**Comment by joaomoreno** [comment]
I mean that there isn't any undo button to click, if the files do not appear in the SCM view. Do you maybe mean the simple editor undo, as in Ctrl Z?

> Very strange :( I wish I could offer something more. I think the heart of the problem was that somehow I got into this strange state where either git or VSCode thought I didn't have a branch checked out. Where normally it says the branch name in the bottom left, it just had a hash that didn't correspond to any commits or branches (that I know of).

Yes, this is called detached mode in git. You can get to it simply by checking out a commit directly instead of a branch. For example `git checkout HEAD~`.

> Anyway—I don't think there's any more information I can provide, but on the off chance this happens again to someone, maybe we'll at least know it wasn't an isolated incident? :/

I'll definitely keep it in mind! :+1:

**Comment by t3db0t** [comment]
> Do you maybe mean the simple editor undo, as in Ctrl Z

Ah, yes, that's what I meant. There were no files in the SCM view at all.

**Comment by joaomoreno** [comment]
Ah that explains my confusion, sorry about that! Let me know if you do manage to reproduce the issue. Thanks for the input!
