### ISSUE TITLE
Breakpoints reordering randomly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85514]
I added a breakpoint on the line and another on some column. Then I started typing (in a different file) and the breakpoints flip around on each keystroke. Not in debug mode.

![Nov-24-2019 19-56-35](https://user-images.githubusercontent.com/323878/69511352-9900d880-0ef4-11ea-85a1-9ab5293d1fc3.gif)

**Comment by isidorn** [comment]
Good catch.
The issue was that breakpoint were flipping location in the sorter if one breakpoint had the column and the other not.
