### ISSUE TITLE
Commands executed by 'command:' links in hovers no longer receive arguments

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85521]
Issue Type: <b>Bug</b>

`command:` links in hovers no longer pass arguments to the executed command

Not sure exactly when this started, but it works fine in 1.40.1.

/cc @jrieken 

VS Code version: Code - Insiders 1.41.0-insider (b8d63e0fcf76f828c7ebb7939afbb58215df0f42, 2019-11-25T05:37:42.790Z)
OS version: Windows_NT x64 10.0.19030

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
You can see the issue with GitLens:
![image](https://user-images.githubusercontent.com/641685/69520328-5e199780-0f2a-11ea-9e4b-328fd7a9790f.png)

In 1.40.1 that link will open a diff, but in 1.41 it doesn't do anything

**Comment by jrieken** [comment]
This regressed from https://github.com/microsoft/vscode/issues/83645 - the markdown renderer how gives URI as string and somehow encoding breads along the way...
