### ISSUE TITLE
Git does not work unless you open the project from the Git root

### ISSUE THREAD

**Issue by yordis** [microsoft/vscode#85528]
```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0
```

Steps to Reproduce:

1. Open a JavaScript lerna mono-repo from inside one of the packages instead of the root
2. Change some files
2. Notice the Git tab doesn't pick up the changes unless you open the project from the root

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?

**Comment by yordis** [comment]
It seems that it is working again in the latest version.
