### ISSUE TITLE
php. Issue parsing code. Colorization is broken after solr syntax

### ISSUE THREAD

**Issue by aksineDby** [microsoft/vscode#85525]
![Снимок экрана от 2019-11-25 11-45-03](https://user-images.githubusercontent.com/34752422/69525443-2d148380-0f79-11ea-8022-fd1cb16aea3f.png)
code line:
$query .= " AND date:[" . $data['date'] . " TO " . $data['date'] . "] ";

All after " AND date:[" has the wrong color scheme

**Comment by alexr00** [comment]
Moved to the repo that owns the PHP grammar: https://github.com/atom/language-php/issues/374
