### ISSUE TITLE
JSON completion adds colon to value

### ISSUE THREAD

**Issue by ChaosinaCan** [microsoft/vscode#85520]
Issue Type: <b>Bug</b>

When using a JSON schema so that vscode provides completion suggestions, typing a JSON key followed by <kbd>:</kbd> completes the key and adds any braces/quotes necessary for the value, but then puts a colon inside the value.

![json bug](https://user-images.githubusercontent.com/760836/69518837-2a387500-0f1e-11ea-8c88-a0ebd21f5322.gif)

**Expected:** typing `"name":` or `name:` completes to `"name": ""` (or `[]`, `{}`, etc.)

**Actual:** it completes to `"name": ":"` (or `"name": [:]`, `"name": {:}`, etc.)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.58GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Joel/source/repos/vscode-kll|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
chronicler|arc|0.1.4

</details>

**Comment by ChaosinaCan** [comment]
Looks like this is #42544?

**Comment by aeschli** [comment]
Yes, we need  #42544. Until then I'll have to either remove the commit character or no longer add a value.

**Comment by aeschli** [comment]
@jrieken What do you think?
I almost would need to provide a proposal per commit character. If it's `:`, I complete just the property, if it's `,` or enter, I also add a vale (the default value).

**Comment by jrieken** [comment]
Yeah, you'll need #42544 which plan to change the commit character so that a character can express if it wants to be inserted or not.

**Comment by aeschli** [comment]
It's no just with `:` but also with `,` that we insert automatically.

I disabled the commit characters for now as we wait for the new API.
