### ISSUE TITLE
vscode should warn on bad tslint.json format

### ISSUE THREAD

**Issue by maasha** [microsoft/vscode#85537]
A miss-placed comma in the json file cost my an hour of debugging. Perhaps vscode could pass on the error generated:

```
 ./node_modules/.bin/tslint -c tslint.json --project .
Failed to load client/tslint.json: Unexpected string in JSON at position 699 in client/tslint.json
```

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please provide example of wrong JSON content?
VSCode warns about invalid JSON (even in JSON with comments)

**Comment by maasha** [comment]
The below offending `tslist.json` file:

```
{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended",
        "tslint-sonarts",
        "tslint-consistent-codestyle"
    ],
    "jsRules": {},
    "rules": {
        "arrow-parens": [true, "ban-single-arg-parens"],
        "curly": [true, "ignore-same-line"],
		"max-classes-per-file": { "options": 1 },
        "member-ordering": false,
		"member-access": false,
        "no-console": false,
		"no-empty": false,
        "object-literal-sort-keys": false,
        "ordered-imports": false,
		"radix": false,
        "prefer-for-of": false,
        "max-line-length": [true, 130],
        "cognitive-complexity": [true, 12],
        "array-type": [true, "array"]
        "naming-convention": [
            true,
            { "type": "default", "format": "camelCase" },
            { "type": "property", "modifiers": ["public", "static"], "format": "UPPER_CASE" },
            { "type": "class", "format": "PascalCase" },
            { "type": "interface", "format": "PascalCase" },
            { "type": "enum", "format": "PascalCase" },
            { "type": "variable", "modifiers": ["global", "const"], "format": ["camelCase","UPPER_CASE"] }
        ]
    },
    "rulesDirectory": []
}
```

**Comment by IllusionMH** [comment]
Works as expected from me for both **JSON** and **JSON with Comments** types of file
![image](https://user-images.githubusercontent.com/1312662/69552005-5dbee200-0fa6-11ea-97ba-73e89f47bdfa.png)

Is it reproducible without extensions?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by maasha** [comment]
I am afraid you misunderstood the problem :oD. The tslint extension fails silently because of a bad `tslint.json` config file.

**Comment by IllusionMH** [comment]
> tslint extension fails silently

This is the first mention of extension that causes problems.

Please report against extension that you use (most likely it is https://github.com/Microsoft/vscode-typescript-tslint-plugin/issues)

/causedByExtension
