### ISSUE TITLE
Visual Studio Code SSH Connection doesn't work

### ISSUE THREAD

**Issue by Himalaye** [microsoft/vscode#85538]
Hi

I try to connect to a Remote Explorer via Visual Studio Code.
I installed everything according to the documentation.
Now my problem lies within adding my ssh key which I generated through putty.
The private and public key have been moved to the same folder as the config file (C:\Users\My User.ssh)
I tried to add another line of code to the config file

    IdentityFile C:\Users\My User.ssh\ssh.pub

I tried different variations as well f.e.

    "C:\Users\My User.ssh\ssh.pub"
    ~/.ssh/ssh.pub
    etc.

(I also tried everything with ssh.ppk)

Errormessages:

    no such identity: C:\Users\My User\.ssh\ssh.pub: no such file or directory
    --> Happens when I write the Path with " "
    C:\Users\My User/.ssh/config line 8: garbage at end of line; "User\.ssh\ssh.pub.
    --> Happens when I write the Path w/o " "
    Load key "C:/Users/My User/.ssh/ssh.pub": invalid format
    --> Happens when I write the Path with a frontslash and " " or when I write the Code according to the documentation: ~/.ssh/ssh.pub

I assume, that one of the problems is, that my Username has a whitespace.

My questions are:

    How do I change the IdentiyFile Path that the whitespace is getting ignored?
    How do I have to write the filepaths in windows since the one in the documentation doesnt seem to work?

Thanks in advance.

**Comment by mailwl** [comment]
try "^"
`C:\Users\My^ User\.ssh\ssh.pub`

**Comment by Himalaye** [comment]
![grafik](https://user-images.githubusercontent.com/33008092/69543042-08c2a200-0f8d-11ea-905a-4cf6cc2f27c0.png)
Still getting this error.

![grafik](https://user-images.githubusercontent.com/33008092/69543085-1f68f900-0f8d-11ea-924e-35dcdee66b76.png)
This is my Config.

**Comment by mailwl** [comment]
put the whole path in "". Anything changes?

**Comment by Himalaye** [comment]
I figured it out.
Yes I had to use "" and additionaly remove the .pub at the end.
Somehow he doesn't understand the .pub ending.
It works now.
Thanks a lot!

PS: How can I pin my solution here on github?
