### ISSUE TITLE
Synced settings don't respect existing indentation amount or type 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85543]
After syncing this morning in the conflict resolution state the indentation was all off which I don't doesn't happen when you add new settings via settings UI.

```json
{
  (lots of settings indented with 2 spaces),
  "terminal.integrated.windowsEnableConpty": false,
  "terminal.integrated.rendererType": "experimentalWebgl",

  "terminal.integrated.minimumContrastRatio": 11,
"terminal.integrated.commandsToSkipShell": [
	"workbench.action.toggleSidebarVisibility"
],
"terminal.integrated.enableBell": true,
"debug.toolBarLocation": "docked",
"git.enableStatusBarSync": false,
"remote.SSH.enableHostsExplorer": true,
"terminal.integrated.splitCwd": "initial",
"workbench.statusBar.visible": true,
"editor.accessibilitySupport": "off",
"a": {
	(snip)
},
"editor.fontSize": 13,
"terminal.integrated.fontSize": 13,
"explorer.compressSingleChildFolders": true,
"workbench.dialogs.useSimplified": "true"
}
```

**Comment by sandy081** [comment]
Currently I am hardcoding the indentation to tab and hence it is. I would probably read the indentation config from settings and use it.

**Comment by Tyriar** [comment]
Also right now it's really mangling my settings file. The _order_ and indentation of settings is important to me, even more so than for keybindings as that's how I manage them.

**Comment by Tyriar** [comment]
Moved that to https://github.com/microsoft/vscode/issues/85716 as it's different to indentation
