### ISSUE TITLE
Make initial debug / run view extensible

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#85548]
We need to introduce a contributable menu to the Debug: Start view such that each extension can contribute commands tehre.

We would have to enforce `when` context on top of these contributed commands just so the view does not end up being a jungle. For example `when activeFile is python` add the python commands.

An open question is how these contributed commands would look like, would it also be a blue button, or is there a `...` affordance which when clicked shows all the contributed commands.

**Comment by isidorn** [comment]
For now I believe a better approach is for each extension to contribute a view, for example https://github.com/microsoft/vscode-python/issues/9268

Due to that pushing this feature request out of this milestone and we can reconsider this in the future if needed.

**Comment by isidorn** [comment]
Debug start view can now be contributed to. We still need to:

- [ ] show button as disabled
- [ ]  add telemetry
- [ ] render keybindings
- [ ]  figure out a context for extensions to use
- [ ] make sure my buttons are at the top

**Comment by gjsjohnmurray** [comment]
This seems to have landed in today's Insiders. I noticed that we're getting a focus rectangle that doesn't occur on Stable:

![image](https://user-images.githubusercontent.com/6726799/74916894-8f392500-53be-11ea-97b6-0c9e823e4ab8.png)

**Comment by isidorn** [comment]
@gjsjohnmurray correct. We decided to change that behavior, that focus is first passed to the view, and then the user can navigate to focus what button / text he wants. We think this makes the most sense from the accessibility standpoint.

**Comment by isidorn** [comment]
@connor4312 @roblourens please note that the debug start view is now contributable to.
You could potentially add an action to open the Javascript Debugger.
I am still thinking about context keys and will keep you updated on that.
Here's an example how Git extension contributes a button to the explorer view

https://github.com/microsoft/vscode/blob/093ada38305dc4b26bdfb62ae86bca245cb9d233/extensions/git/package.json#L1858
The id of the debug start view is `workbench.debug.startView`

fyi @weinand

**Comment by weinand** [comment]
I think the contributed action should open the debug terminal.

**Comment by isidorn** [comment]
After some pondering I decided on the following context key:
`debugStartLanguage`
This context key will be set to the last active editor language that any debugger is interested in.

So for example, user open a javascript file, and the open a json file.
The context key will have the value `javascript`. Since no debugger is interested in json files.
I believe this context key will convey the right notion of what a user is interested in debugging.

Since context keys luckliy now support OR I  I suggest that javascript debugger contributes a Debugger Terminal command when `debugStartLanguage == 'javascript' || debugStartLanguage == 'typescript'...`. All the language from [here](https://github.com/microsoft/vscode-js-debug/blob/master/package.json)

If there are better ideas on what context key to use to not have the view cluttered I am open for suggestions. 

@connor4312 let me know if you do not have time to contribute the "Debug Terminal" action and I can also provide a PR.

Follow up item to show button as disabled https://github.com/microsoft/vscode/issues/91141

**Comment by isidorn** [comment]
I will also store the value of the context key per workspace storage.
So when a user starts vscode again and has no editor open that we preserve the last language he was interetsed in. Thus the contributed buttons would still be there.

**Comment by joaomoreno** [comment]
@isidorn Telemetry is in: https://github.com/microsoft/vscode/commit/a1f61fd0fec2e3dbe159264f4b69148554fcbfd9

**Comment by isidorn** [comment]
Thanks a lot! Very elegant :)

**Comment by joaomoreno** [comment]
@isidorn And here's preconditions for button enablement (internal only): https://github.com/microsoft/vscode/commit/0c1c8f2760967f4a950af36e0482b78ea2916a34

**Comment by isidorn** [comment]
Awesome, adopted it for debug. 🎉

**Comment by connor4312** [comment]
I probably won't have time to do this before endgame, but would be happy to accept a PR or take care of it next iteration.

**Comment by isidorn** [comment]
Dear debug protocol implementers,

Debug welcome view is now supporting contributing welcome content via static `package.json` API.
Thus extensions can contribute text and buttons to the welcome view. The idea is to introduce actions and help text that should make it easier for users to start debugging.
Please note that we would like to keep this view **not cluttered**, thus we highly recommend that you use the context key `debugStartLanguage`. More about this context key can be found in my comment [here](https://github.com/microsoft/vscode/issues/85548#issuecomment-589619873).


API details here https://github.com/microsoft/vscode/issues/89080
This is still **proposed API** and we are in the transition of making the API final - which should happen in the March milestone.
Also note that we are discussing to show this view not only when `launch.json` is missing but when users are not debugging. More details here https://github.com/microsoft/vscode/pull/92096
**Example** how to js-debug did this https://github.com/microsoft/vscode-js-debug/commit/9e6dc67323cac2068f0369503525617f2b987c15

@ntotten, @pieandcakes, @gregg-miskelly, @MSLaguana, @DanTup, @devoncarew, @WebFreak001, @roblourens, @andysterland, @Kode, @hbenl, @Kode, @ayuckhulk, @iradul, @lukaszunity, @miniwolf, @svaarala, @yurydelendik, @vshaxe, @APerricone, @vshaxe, @phoityne, @vshaxe, @vshaxe, @akaroml, @ptrthomas, @vadimcn, @dibyendumajumdar, @weinand, @weinand, @ivanbuhov, @weinand, @joelday, @raix, @richterger, @felixfbecker, @daviwil, @rkeithhill, @glennsarti, @jpogran, @DonJayamanne, @MSLaguana, @rebornix, @joshtynjala, @luabud @testforstephen

**Comment by pieandcakes** [comment]
@wardengnaw

**Comment by raix** [comment]
Do we have to support translations in the wellcome text?

**Comment by isidorn** [comment]
@raix that would be great, since the welcome text is user facing and all user facing text should be translated.
