### ISSUE TITLE
Version 1.40.1 issue in win 7.

### ISSUE THREAD

**Issue by malvarezieps** [microsoft/vscode#85546]
- VSCode Version: x64-1.40.1exe
- OS Version: Win7Professional
- Gpu: Intel HD Graphics (integrated with motherboard)

Steps to Reproduce:

1. Install the last update vscode (1.40.1)
2. Start the program
3. Black window with no controls.

Does this issue occur when all extensions are disabled?: Yes

I unistall the program and reinstall it, but the same issue appear, then I install the version 1.39, disable all the extensions and reinstall the ver. 1.40.1, but is the same.

![errorvscode](https://user-images.githubusercontent.com/32777196/69549692-c175ea80-0f67-11ea-8c07-aa5829134f6b.jpg)

**Comment by deepak1556** [comment]
@malvarezieps can you follow the instructions from here https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows and provide the crash log. Thanks!
