### ISSUE TITLE
Git: Synchronize changes stays in a loop

### ISSUE THREAD

**Issue by leonfgomez** [microsoft/vscode#85541]
- VSCode Version: 1.40.1
- OS Version: Oracle Linux 7

I use the following two commands to avoid having to re-enter my password every time (this is in an internally hosted github).

  git config --global credential.helper cache
  git config --global credential.helper 'cache --timeout=172800'

Commit works, but when I try to sync VS Code stays in a loop (the small circular arrow spins and doesn't stop). I have to re-start VS Code and then everything works fine i.e. I can sync as many times as I want without having to enter my credentials.

Steps to Reproduce:

1. apply the config above
2. commit changes
3. press Synchronize Changes
4. enter user name and password
5. sync stays in a loop

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What if you run `git pull` from the command line? Does that work?
