### ISSUE TITLE
Group or turn off problems by subproject 

### ISSUE THREAD

**Issue by lfarkas** [microsoft/vscode#85551]
We've got a root Java project with many subprojects (and even subprojects has sub projects). One developer usually working only a few of these subproject but depends (have to build) many (or all) of the other subprojects. But one given developer only would like to see his own project's problems. Unfortunately the problems window contains all other project's problems. What's more we've got one core subproject with many problems but we still have to use it. Currently it's not possible to group or turn off problems by projects and not able to find his own problems. Which means the problems window currently totally unusable. The best would be if we can turn on/off the problems by projects or at least group by project and close all other project's problems.

This is a multi project gradle project with many subproject so we can't simple delete them.

Is there any solution for this?

Without this feature it's hardly usable for a larger java project.

**Comment by sandy081** [comment]
Looks to me a feature request for Java extension to generate problems per project.
