### ISSUE TITLE
"Continue" action button in CALL STACK doesn't work

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#85550]
Insider or stable

- set breakpoint in line "hello world"
- run Cluster sample
- in browser open "localhost:8000"

Observe: one debug session should break on breakpoint

- press that debug session's "continue" action multiple times

Observe: debug session doesn't continue.

- now press "continue" action in debug toolbar twice

Observe: debug session resumes

**Comment by isidorn** [comment]
Great catch. I have fixed how the contexts are passed to actions. Though this was a bigger change so we shuold keep our eyes open for breakages.
