### ISSUE TITLE
RegExp causes Visual Studio Code to freeze

### ISSUE THREAD

**Issue by jhputtick** [microsoft/vscode#85552]
Issue Type: <b>Bug</b>

Open a workspace
Enter Shift-Ctrl-F (Find in Files)
Ensure "Match Case" is enabled
Ensure "Use Regular Expression" is enabled
Ensure "Match Whole Word" is disabled
Enter the following regular expression:

^(.*[^_])*some_string

When you hit Enter to perform the search, it freezes. After about 15 seconds, VSCode pops up a prompt "The window is no longer responding", and gives you the option to Reopen / Keep Waiting / Close.

I have tried this in two completely unrelated workspaces, one of which has only 4 small text files (other than files excluded from the project).

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (11.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|0.5.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.1
vscode-hexdump|sle|1.7.2
mib|Ver|0.0.4

</details>

**Comment by roblourens** [comment]
It sounds like this regex is triggering catastrophic backtracking: https://github.com/microsoft/vscode/issues/30874#issuecomment-315861140

**Comment by terryrankine** [comment]
can replicate this.
`{{eventIDValue}}`

regex
`\{\{(.*)\}\}` works
`\{\{(.*)+\}\}` freezes - my mistake.
