### ISSUE TITLE
总是黑屏

### ISSUE THREAD

**Issue by iRuxu** [microsoft/vscode#85553]
Issue Type: <b>Bug</b>

最近的某次升级后，只要切到其他视窗，切回来的时候都会有长时间的黑屏，以前并无此现象。

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (20.99GB free)|
|Process Argv|H:\wwwroot\wordpress|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
flask-snippets|cst|0.1.1
vscode-eslint|dba|1.9.1
tslint|eg2|1.0.44
prettier-vscode|esb|3.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
code-runner|for|0.9.15
gc-excelviewer|Gra|2.1.32
minify|Hoo|0.4.3
rest-client|hum|0.23.0
mysql-syntax|jak|1.3.1
docthis|joe|0.7.1
vscode-insertdatestring|jsy|2.2.4
swift|Kas|0.1.0
Kotlin|mat|1.7.0
vscode-apache|mrm|1.2.0
language-gettext|mro|0.1.1
vscode-language-pack-zh-hans|MS-|1.40.2
mssql|ms-|1.7.1
python|ms-|2019.11.50794
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.1
vscode-react-native|msj|0.13.1
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
java|red|0.53.1
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.6.9
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-todo-highlight|way|1.0.4
ascii-unicode-escape|yar|0.1.0
json|Zai|1.0.2

</details>

**Comment by sandy081** [comment]
*english-please

**Comment by iRuxu** [comment]
After an update ( I can't remember which one , but it happened recently )
Now it always will be blackscreen when I switched to another app everytime.
I didn't installed some special plugins recently I remembered.
So .. But I don't know whether it occured in others computers.
Sorry.

**Comment by sandy081** [comment]
Can you please try to reproduce by disabling all extensions?

**Comment by iRuxu** [comment]
I tried . I think it because some php extends
