### ISSUE TITLE
VSCode JSDoc @property description doesn't work in IntelliSense

### ISSUE THREAD

**Issue by orangebokov** [microsoft/vscode#85554]
VSCode Version: 1.40.1
OS Version: macOS 10.14.6

``` js
/** @typedef {Object.<string, any>} type
 * @property {string} prop1 - Missing Description 1
 * @property {string} prop2 - Missing Description 2
*/

/** @type {type} */
var a = {
    prop1: null,
    prop2: null
}

/** @type {type}
 * @class */
function b(){
    this.prop1 = null;
    this.prop2 = null;
}

var c = new b();
```

![Снимок экрана 2019-11-25 в 20 29 03](https://user-images.githubusercontent.com/39646729/69564908-ecdaf280-0fc4-11ea-8cbf-368b92a151da.png)
![Снимок экрана 2019-11-25 в 20 29 10](https://user-images.githubusercontent.com/39646729/69564914-efd5e300-0fc4-11ea-97c3-b72239ec13ec.png)
![Снимок экрана 2019-11-25 в 20 29 24](https://user-images.githubusercontent.com/39646729/69564921-f3696a00-0fc4-11ea-8c48-8102b7e0a2da.png)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/35346 to track upstream
