### ISSUE TITLE
Format document does not uncollapse all regions

### ISSUE THREAD

**Issue by rslavey** [microsoft/vscode#85562]
When I choose to format a document, and VSCode makes any formatting changes, it uncollapses everything. It would be nice to make the formatting changes while keeping the items' collapse state.

**Comment by aeschli** [comment]
This is likely caused by an extension. I just tested with the built-in HTML formatter, and no code was unfolded.
Please run with extensions disabled. If you still see it, please reopen and add a small example.

See https://github.com/microsoft/vscode/issues/54266
