### ISSUE TITLE
The newest 'c/c++' extension(Version 0.26.2-insiders2) kills IntelliSence feature by loosing include paths in PlatformIO IDE.

### ISSUE THREAD

**Issue by mikionakajima** [microsoft/vscode#85568]
OS: Linux(Lubuntu 19.10)
VSCode:1.40.1
Extensions: PlatformIO IDE(1.10.0), C/C++(0.26.1, 0.26.2-insiders2)
Target: NodeMCU-32s

I'm using VSCode for development of an IoT on NodeMCU-32s.
Since PlatformIO IDE has IntelliSence feature, I moved from Arduino IDE.
The IntelliSence feature does not work after the system updated the extension up to '0.26.2-insiders'.

---0.26.1
When I import a project, the system automatically create 'c_cpp_properties.json'.
---0.26.2-insiders2
When I import a project, the system does not create 'c_cpp_properties.json'.

---0.26.1
When the file, 'c_cpp_properties.json', exists, the system refers the appropriate include files.
---0.26.2-insiders2
Even if the file, 'c_cpp_properties.json', exists, the system does not refer some include files, such as "Arduino.h" and files in lib directory.

I could avoid this phenomenon by 
1. Install Another Version.
2. Disable Auto Updating Extensions.

**Comment by sandy081** [comment]
please file the issue against the extension.
