### ISSUE TITLE
JavaScript/TypeScript: No IntelliSense in some contexts like import

### ISSUE THREAD

**Issue by vp2177** [microsoft/vscode#85567]
Ideally, there should be auto-suggest (aka. IntelliSense/auto-completion) even in the following contexts:

* `export {} ` -> should suggest `from`
* similarly, `import {} ` -> should suggest `from`
* `for (... ` -> should suggest `in` and `of`
* TS: `interface ... ` should suggest `extends`
* TS: in type declarations, `: ` -> should also suggest `typeof`

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please split these into separate issues and [file bug reports upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
