### ISSUE TITLE
Installing VS Code can break DNF

### ISSUE THREAD

**Issue by karai17** [Microsoft/vscode#8556]
- VSCode Version: 1.2.1
- OS Version: Fedora 24 Kernel 4.5.5-300

Steps to Reproduce:
1. Fresh install Fedora 24
2. Install Fedy
3. Install VS Code from Fedy

When VS Code installs, it overwrites a line in `/etc/dnf/dnf.conf` from:

```
installonlypkgs=kernel installonlypkg(kernel) installonlypkg(kernel-module) installonlypkg(vm)
```

to:

```
installonlypkgs=electron
```

This causes the following error when trying to run `dnf upgrade` on `kernel`:

```
[Karai@himegoto ~] $ sudo dnf upgrade
[sudo] password for Karai: 
Last metadata expiration check: 0:47:42 ago on Thu Jun 30 01:37:33 2016.
Dependencies resolved.
Error: The operation would result in removing the booted kernel: kernel-core-4.5.5-300.fc24.x86_64.

[Karai@himegoto ~] $ sudo dnf install kernel
[sudo] password for Karai: 
Last metadata expiration check: 0:53:37 ago on Thu Jun 30 01:37:33 2016.
Package kernel-4.5.5-300.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
================================================================================
 Package                   Arch        Version               Repository    Size
================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 kernel                    x86_64      4.5.7-300.fc24        updates       70 k
 kernel-core               x86_64      4.5.7-300.fc24        updates       19 M
 kernel-modules            x86_64      4.5.7-300.fc24        updates       21 M
 kernel-modules-extra      x86_64      4.5.7-300.fc24        updates      2.2 M

Transaction Summary
================================================================================
Skip  4 Packages

Nothing to do.
Complete!
[Karai@himegoto ~] $ 
```

What VS Code should be doing is appending `electron` to the `installonlypkgs` list, not overwrite it.

**Comment by karai17** [comment]
More information here: https://bugzilla.redhat.com/show_bug.cgi?id=1347999#c2

**Comment by Tyriar** [comment]
This is an upstream problem right? Also I'm not sure where the "electron" is coming from, it isn't referenced anywhere in the [rpm spec file](https://github.com/Microsoft/vscode/blob/master/resources/linux/rpm/code.spec.template)?

**Comment by karai17** [comment]
As far as I know, VSCode is the only thing I use that runs on electron, and
this was a fresh install of Fedora 24.

**Comment by piptravels** [comment]
I have a fresh Fedora 24 XFCE spin and I'm getting what I believe to be the same error:
Failed to synchronize cache for repo 'atrpms', disabling.
Last metadata expiration check: 0:16:01 ago on Sat Jul  2 09:41:09 2016.
Dependencies resolved.
Error: The operation would result in removing the booted kernel: kernel-core-4.5.7-300.fc24.x86_64.

I read this https://bugzilla.redhat.com/show_bug.cgi?id=1347999#c2 but don't want to edit until I know it's not going to bork my install since this is my work machine. Is the VSCode added from the MS TrueType fonts core? If so, would this be fixed by removing it?

**Comment by Tyriar** [comment]
Our rpm package/yum repo should not touch this file afaik https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
