### ISSUE TITLE
Extension incorrectly reporting an update available

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8557]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Was greeted by a (1) indicator immediately after updating.

![image](https://cloud.githubusercontent.com/assets/2193314/16478850/4fafae3a-3e51-11e6-854b-28bdd1096b70.png)

Restarting showed same thing, no errors in console.

**Comment by isidorn** [comment]
Can not repro on my machine -> might be some corner case -> july, joao

**Comment by Tyriar** [comment]
@isidorn I just looked back and I notice there is an update for editorconfig. Looking at the screenshot, the author for editorconfig is blocked out where the update button should be. This is probably some style/css class related issue where the update button is not being shown correctly. Given this knowledge it may be easy to fix the issue?

**Comment by Tyriar** [comment]
I have a repro:

1. Have an extension update available
2. Toggle extension viewlet
3. Resize panel down until the update button disappears, notice the author is cut off and not truncated correctly as the update button seems to still take up the space

Long term fix for this is likely to swap the text out for an icon at this point instead of just disappearing.

**Comment by isidorn** [comment]
Sounds like a dup of #8510
Thanks for more details though!
