### ISSUE TITLE
Issue with C++ type checking with pointers

### ISSUE THREAD

**Issue by DamianRivas** [microsoft/vscode#85570]
Issue Type: <b>Bug</b>

There is a bug with VS Code's type checking when it comes to dynamically allocated arrays of pointers. It could be more general than this, but this is when I saw the error.

For example...
```
a value of type "HashMap::Node **" cannot be used to initialize an entity of type "HashMap::Node **"
```

Clearly they are both the same type, and my application builds and runs fine, so something seems to be up with the way VS Code is checking these types.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.3.0-22-generic
Remote OS version: Linux x64 4.15.0-70-generic
Remote OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3002)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.52GB (0.20GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: 172.16.56.128|
|OS|Linux x64 4.15.0-70-generic|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (1 x 1799)|
|Memory (System)|1.92GB (0.28GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 172.16.56.128|
|OS|Linux x64 4.15.0-70-generic|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (1 x 1799)|
|Memory (System)|1.92GB (0.28GB free)|
|VM|100%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.1
bracket-pair-colorizer|Coe|1.0.61
javascript-ejs-support|Dig|1.1.3
auto-close-tag|for|0.5.6
xtend-lang|Gra|0.1.0
bats|jet|0.1.7
yarn-lock-syntax|mar|0.1.3
dotenv|mik|1.0.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
material-icon-theme|PKi|3.9.2
slim|sia|0.1.2
gitconfig|sid|2.0.1
vscode-ruby|win|0.26.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the c++ extension
