### ISSUE TITLE
"Freeze" after searching for symbol

### ISSUE THREAD

**Issue by LonJonn** [microsoft/vscode#85572]
Issue Type: <b>Bug</b>

'Go to Symbol in File' freeze's VS Code after being used a second time. First time works fine, but once I try again, I can't input any values into the search box or anywhere else in VS Code. The editor still seems to be working though (blinking cursor), just not taking input.

This does not happen on my macbook but DOES happen on a clean install of the insider release for windows as well.

I have also disabled all extensions and reset to default settings.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo What language are you coding in? Can you reproduce it with a workspace containing code you can share?

**Comment by LonJonn** [comment]
Happens with javascript and typescript. Even with a workspace of one js file:

```
// symboltest.js
function sym() {
  return ";(";
}

function bol() {
  return "D;";
}

```

**Comment by gjsjohnmurray** [comment]
/confirmationPending - I was unable to reproduce this. I opened a fresh VS Code, created a new file (which I didn't save), set its language mode to Javascript, pasted in your example, then used the Command Palette or Ctrl+Shift+O to "Go to Symbol in File..." and jump between sym and bol.

Can you post a screen recording?

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
