### ISSUE TITLE
"Installing packages..." stays in the status bar after installing OmniSharp and its dependencies 

### ISSUE THREAD

**Issue by SalvatoreMeschini** [microsoft/vscode#85584]
- VSCode Version: 1.40.1
- OS Version: Windows 10, Version 1903 (OS Build 18362.476)

Steps to Reproduce:

1. I opened a .cs file and Visual Studio Code started downloading the C# dependencies 
2. Despite the fact that the installation process finished (?), the status bar is stuck with "Installing packages...". Hovering that item, it displays the following tooltip: Installing package 'Razor Language Server (Windows / x64).

![Installing packages](https://user-images.githubusercontent.com/11814081/69608621-2133ca80-1028-11ea-9b04-7cb45a3914b8.png)

Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (32059 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (47489 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (50372 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished

**Comment by sandy081** [comment]
Please file the issue against the C# extension.
