### ISSUE TITLE
workbench.view.git should show and focus git panel

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8558]
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open a folder without a git repository
2. Open a file and focus editor
3. <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>g</kbd>, notice focus is still in the editor

**Comment by ramya-rao-a** [comment]
@joaomoreno  After the above fix, the editor does lose focus, the "Initialize git repository" button gets focus for a second, after which the button loses focus. The button should retain focus.
I tested in Windows with the latest Insiders build

**Comment by joaomoreno** [comment]
Wow. I see it too. Someone broken this... thanks @ramya-rao-a

**Comment by Tyriar** [comment]
Verification works :tada: :sparkles:

**Comment by joaomoreno** [comment]
Well... it was definitely resolved... something else changed since that steals the focus. :/
