### ISSUE TITLE
Notification Toast Background

### ISSUE THREAD

**Issue by Jabor047** [microsoft/vscode#85588]
Currently the Notification Center background Colour and Notification Toast background Colour are the same.I would like the option to theme each one differently so as the notification Toast can stand out more and the Notification center can properties of the theme applied.

**Comment by bpasero** [comment]
Up for grab if someone wants to implement this.

**Comment by hypercubestart** [comment]
Hi! If you don't mind, I would like to give this a shot.

@Jabor047 
Would it be acceptable for the Notification Center and the Notification Toast to each have a setting to set the background color? Should it also have a setting to set the background color on hover/selected?

And, I couldn't find what you meant by Notification Center, so as clarification 
![image](https://user-images.githubusercontent.com/24601452/70719645-386cec00-1ca7-11ea-8a00-b3db9247cfff.png)
Is the top header the Notification Center?

**Comment by Jabor047** [comment]
@hypercubestart 
Yes to both the questions on the second paragraph (after you mentioned me).
By Notification Center I meant the area with the "This workspace has extension recommendations". The area where the highlighted notification is grey in the photo attached
![Screenshot (157)](https://user-images.githubusercontent.com/18696686/70805795-e0c7a100-1dca-11ea-9641-e5a3bef11d4e.png)
 below

**Comment by hypercubestart** [comment]
@Jabor047 which area is the Notification Toast?

**Comment by Jabor047** [comment]
Yes, the notification "pop ups" you get at the bottom right.

**Comment by bpasero** [comment]
@Jabor047 wouldn't such a color require that all the other notification colors need to be customized for toasts vs. notification center too? Otherwise, you could change the background color in toasts but not tweak any other appearance.

**Comment by Jabor047** [comment]
@bpasero I don't quite get your question, could you  please elaborate.

**Comment by bpasero** [comment]
@Jabor047 there are various colors for notifications, including foreground colors. They are all being used for notification toasts as well as in the notification center. Now that we introduce a separate background color for notification toasts only, wouldn't this require that all of the other notification colors can be configured for toasts vs center as well? 

Example: I may decide as a theme author to set the notification toast background color to yellow. Now when I want the foreground color to be blue, it would also be blue in the center where the background color is not yellow.

**Comment by Jabor047** [comment]
@bpasero My way of think was the notification should have a different background but maintains the overall theme, not to have a different color combination but I do see your point and I agree with it, if the theme author wishes to theme every notification toast component they should.
@hypercubestart what do you think?

**Comment by hypercubestart** [comment]
Yeah I agree, if we introduce a way of separately setting the notification background color, all other color settings should also be able to be set separately from toast vs center.

However, I am not sure what whether this level of customization is necessary.
@Jabor047 do you have a good use case why someone may want to theme toasts/center differrent?

**Comment by bpasero** [comment]
Here is my verdict: we cannot add a new color to a system of colors that you can override without allowing all the other colors to be overridden too. Take this for example:

![image](https://user-images.githubusercontent.com/900690/71777037-1c552580-2f9b-11ea-81c5-86bb545e8dec.png)

The theme author decided to make the toast background red. But anything else cannot be changed without also changing the color of the notification in the center.

**Comment by Jabor047** [comment]
@bpasero and @hypercubestart I was on holiday, I couldn't reply sooner.
There are cases where theming the toast background does not require changing the other colors. if the "other colors" match with a dark background e.g grey and black. 
Separating the theming of toast colors from the center colors is amazing for customization of themes and since it caters for the scenarios outlined above. I think separating all the notification center and toast should be the most appropriate action
