### ISSUE TITLE
Sometimes search and replace bar have no anti-aliasing

### ISSUE THREAD

**Issue by akiirui** [microsoft/vscode#85589]
Sometimes, search and replace bar not have anti-aliasing:

![no](https://user-images.githubusercontent.com/3736910/69614715-890d0400-106e-11ea-9b69-86b7cf3349ef.png)

Normal situation:

![have](https://user-images.githubusercontent.com/3736910/69614768-a641d280-106e-11ea-9a54-201a3023a347.png)

- VSCode Version: 1.40.2
- OS Version: Arch Linux
- Desktop environment: GNOME 3.34 with **text-scaling-factor 1.5**

Steps to Reproduce:

1. New file
2. Ctrl + F or Ctrl + H

Does this issue occur when all extensions are disabled?
Yes

Also test on insiders build 1574746489, same as 1.40.2.
Only happens after 1.40 update

**Comment by roblourens** [comment]
Can you try this in Insiders? We have made some antialiasing improvements this month.

**Comment by akiirui** [comment]
> Also test on insiders build 1574746489, same as 1.40.2.
> Only happens after 1.40 update

@roblourens Yes, I have try in latset Insiders:

- Version: 1.41.0-insider
- Commit: a8158aee897bea1c1ec6545b55c4f7d0de57ed38
- Date: 2019-11-26T21:17:16.825Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Linux x64 5.4.0-arch1-1

Same as stable 1.40.2:
![Screenshot from 2019-11-27 09-29-53](https://user-images.githubusercontent.com/3736910/69685782-97076700-10f8-11ea-878a-276dc19db02b.png)

**Comment by roblourens** [comment]
Can you check other input elements, like in the search viewlet, to see if they show the same thing? This is just a `<textarea>` with the placeholder attribute, and I don't think there's much I can do...

**Comment by akiirui** [comment]
@roblourens Thanks for reply.

> Can you check other input elements, like in the search viewlet, to see if they show the same thing?

Only `div.editor-widget.find-widget` have this issue.

More infomations:

Item | Value
-- | --
GPU Status | 2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled

And more tests:
- 1.40.* with `--disable-gpu`:
No this issue
- 1.39.2 without `--disable-gpu`:
No this issue

**Comment by akiirui** [comment]
More info:

Trigger when first time open `find-widget`. (or other conditions)
Fix when change to another tab.

![example](https://user-images.githubusercontent.com/3736910/69708417-87a70e80-1136-11ea-8f5e-d08199712012.gif)

**Comment by roblourens** [comment]
No idea, @rebornix

**Comment by rebornix** [comment]
I don't know but I'll try to reproduce this issue.

**Comment by rebornix** [comment]
Didn't reproduce by any means. @deepak1556 could you help provide guidance on this? It would be great if you can share how to set up the machine to reproduce anti aliasing related issue.

**Comment by deepak1556** [comment]
@rebornix I use the magnifier app on windows with lcd display, the AA will be pretty obvious in it, or in the web version you can use the eye dropper tool from devtools.

This might most likely be a system specific issue. @akiirui if you can run https://github.com/derat/font-config-info and provide the font info, we can try using the same config to see if it helps repro the issue.

Also can you check if the issue repros with https://vscode-web-test-playground.azurewebsites.net/ on chromium ?

**Comment by akiirui** [comment]
@deepak1556 thanks for reply, here is `font-config-info` ouput:
<details>
<summary>font-config-info</summary>

```
Running at Wed Dec  4 16:59:53 2019

GtkSettings:
gtk-font-name        "Sans 10"
gtk-xft-antialias    1 (yes)
gtk-xft-hinting      0 (no)
gtk-xft-hintstyle    "hintnone"
gtk-xft-rgba         "none"
gtk-xft-dpi          147456 (144.00 DPI)

GTK 2.0 styles:
GtkLabel             "Sans 10"
GtkMenuItem          "Sans 10"
GtkToolbar           "Sans 10"

GSettings (org.gnome.desktop.interface):
font-name            "Sans 10"
text-scaling-factor  1.50

X11 display info:
screen pixels        3840x2160
screen size          1016x572 mm (96.00x95.92 DPI)

X resources (xrdb):
Xft.antialias        "1"
Xft.hinting          "0"
Xft.hintstyle        "hintnone"
Xft.rgba             "none"
Xft.dpi              "144"

XSETTINGS:
Xft/Hinting          0
Xft/Antialias        1
Gtk/FontName         "Sans 10"
Xft/HintStyle        "hintnone"
Xft/DPI              147456
Xft/RGBA             "none"

Fontconfig (Sans 10):
requested size       10 points
family               Roboto
pixelsize            10.42 pixels
size                 10 points
antialias            [no match]
hinting              1
autohint             0
embeddedbitmap       1
hintstyle            1 (slight)
rgba                 [no match]

Fontconfig (default pattern):
antialias            [no match]
hinting              1
autohint             0
embeddedbitmap       1
hintstyle            1 (slight)
rgba                 [no match]

Fontconfig (default match):
family               Roboto
pixelsize            12.50 pixels
size                 12 points
antialias            [no match]
hinting              1
autohint             0
embeddedbitmap       1
hintstyle            1 (slight)
rgba                 [no match]

Fontconfig (non-family/size defaults):
antialias            [no match]
hinting              1
autohint             0
embeddedbitmap       1
hintstyle            1 (slight)
rgba                 [no match]
```

</details>

and my fontconfig

<details>
<summary>fontconfig</summary>

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <alias binding="strong">
        <family>serif</family>
        <prefer>
            <family>PT Serif</family>
            <family>Noto Serif</family>
            <family>Noto Serif CJK SC</family>
            <family>Noto Serif CJK TC</family>
            <family>Noto Serif CJK JP</family>
            <family>Noto Serif CJK KR</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>
    <alias binding="strong">
        <family>sans-serif</family>
        <prefer>
            <family>Roboto</family>
            <family>Noto Sans</family>
            <family>Noto Sans CJK SC</family>
            <family>Noto Sans CJK TC</family>
            <family>Noto Sans CJK JP</family>
            <family>Noto Sans CJK KR</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>
    <alias binding="strong">
        <family>monospace</family>
        <prefer>
            <family>Fira Code</family>
            <family>Noto Sans Mono</family>
            <family>Noto Sans Mono CJK SC</family>
            <family>Noto Sans Mono CJK TC</family>
            <family>Noto Sans Mono CJK JP</family>
            <family>Noto Sans Mono CJK KR</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>
    <match target="pattern">
        <test qual="any" name="family">
            <string>Cantarell</string>
        </test>
        <edit name="family" mode="assign" binding="same">
            <string>Roboto</string>
        </edit>
    </match>
</fontconfig>
```

</details>

> Also can you check if the issue repros with https://vscode-web-test-playground.azurewebsites.net/ on chromium ?

I checked in web vscode, it's not have this issue (chromium version 78.0.3904.108)

**Comment by deepak1556** [comment]
@akiirui thanks for the configs and sorry for the delay, I will try this out tomorrow and respond back.

**Comment by art40100** [comment]
So this is not related to breadcrumbs as I had stated here https://github.com/microsoft/vscode/issues/85272 ?
My posted screenshots are more extreme and it still seems to random. Still occuring on 1.41.0

**Comment by akiirui** [comment]
Already fixed Thanks.

**Comment by art40100** [comment]
still not fixed
![ddd](https://user-images.githubusercontent.com/33236770/75762350-331dbb80-5d43-11ea-90e8-3e338a3b326a.PNG)

**Comment by akiirui** [comment]
This issues are regress at 1.43.2

**Comment by akiirui** [comment]
I am sure this is an upstream problem, I reproduced it in chromium UI.

Closed.
