### ISSUE TITLE
IME always input in advance

### ISSUE THREAD

**Issue by xjArea** [microsoft/vscode#85583]
- VSCode Version: 1.40.1
- OS Version: Window7 X64

When I use QQ IME to input Chinese, Notepad ++ and SublimeTetx3.0 will not output in advance. Only after I confirm the input, what I want to enter will appear in the editor, but in VSCode, it will always be in When I have n’t decided what to enter, I wrote the content into the editor. The picture below shows the performance of the input method in Notepad ++ and VSCode. It can be found that Notepad ++ will only enter the content into the editor after the selection is determined：
![输入法](https://user-images.githubusercontent.com/35623539/69604894-b3a09200-1059-11ea-84d6-285b798b1593.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
This is simply how web browsers work, since we run on Electron which is built with Chromium, we work like web browsers.

**Comment by xjArea** [comment]
@alexandrudima Thanks for your reply, I tested it and found that the input of Chrome is indeed like this, but when I use IE and Firefox, and some other Webkit Core browsers, their effects is similar to Notepad++ instead of VSCode, maybe These browsers have made special adjustments for IME, so can I also set them in VSCode to achieve effects like Notepad++ 😲 ?

**Comment by alexdima** [comment]
@rebornix Can you please confirm that we are working OK? I believe it is fine to have differences compared to Notepad++, as long as it is possible to input Chinese OK.

**Comment by xjArea** [comment]
So there's no future for this feature? OK, forget it. 😅

**Comment by rebornix** [comment]
We are working fine currently even though the experience differs from some other applications. I doubt that we can do anything special to improve it without introducing bugs at this moment.
