### ISSUE TITLE
Translation files are not recognized

### ISSUE THREAD

**Issue by Kanuility** [microsoft/vscode#85599]
I am sry for my bad english 

- VSCode Version: 14.02

Steps to Reproduce:

First of all you need to install al extension so you can Programm for Microsoft dynamics Business central.

1. Make a Normal unedit translation file
2. Edit it in some Language like German
3. Translate it normaly 
4. Make new Fields ore somthing too translate
5. Copy unedit translation file into translatet so it get replaced
6. Set target to you language and translate it
7. Start web client use thise language an see no translations there.

**Comment by sandy081** [comment]
I do think this is a feature that comes out of the box from VS Code and looks like it is from an external extension.
