### ISSUE TITLE
Visual Studio Code always add folder to the current workspace

### ISSUE THREAD

**Issue by ronint84** [microsoft/vscode#85598]
This is what I'd like to achieve: I have Visual Studio code open and a folder is open in the workspace.

If I now drag another folder in the File Explorer onto the Visual Studio Code icon in the taskbar (with the mouse), I want that folder to be added to the workspace.

I can only get it to either open a new window or overwrite my existing folder with the new one -> but thats not what i want to achieve.

Is there a solution for OSX soon ?

**Comment by isidorn** [comment]
Just drag and drop to the explorer should work and works fine for me on OS X.
Droping on the taskbar is not supported.
You can also Right click on the explroer > add folder to workspace
