### ISSUE TITLE
can't find .csv file

### ISSUE THREAD

**Issue by SkyNalix** [microsoft/vscode#85594]
Hello
so my problem is that i need to load a .csv file from my program
this is how look my folders :
![image](https://user-images.githubusercontent.com/56894341/69625700-729f8200-1047-11ea-803a-0ce1c1cbf694.png)

when i run the program i see this in the terminal : 
Trouble reading labyrinthe1.csv file
java.io.FileNotFoundException: labyrinthe1.csv (The specified file can not be found)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.util.Scanner.<init>(Scanner.java:611)
        at Labyrinthe.chargeLabyrinthe(Labyrinthe.java:11)
        at Labyrinthe.main(Labyrinthe.java:143)
D:\Bureau\Cours\Licence_Informatique_Diderot\Semestre-1\IP1-Java\labyrinthe1.csv

i translated it a bit, because it was in french

But when i put the labyrinthe1.csv file in the IP1-Java folder
it work fine, but this will create a mess in my files
so i have to put everything related with this program in TP10 folder
i tried this : 
![image](https://user-images.githubusercontent.com/56894341/69626037-1be67800-1048-11ea-8e9c-df6e1456a626.png)
i added at the top of my program "package aaa;"

but even so he can't find it
so i ask here for help :(

(I have to specify that there is no problem in my program, it was coded by my teacher, and everything worked when i tried it on school's computer )

**Comment by gjsjohnmurray** [comment]
/question this is unlikely to be VSCode-specific.
