### ISSUE TITLE
Feature Request: File backups

### ISSUE THREAD

**Issue by andym196** [microsoft/vscode#85593]
I would like to see a feature where you can enable file backups so every time you save a file in VS Code (or every x seconds) it creates a backup copy of the current file somewhere.

 I'm currently using this saveBackup extension for this:
https://marketplace.visualstudio.com/items?itemName=purplestone.savebackup
Which works great, but I feel this feature should be built in. This backup feature is built in to Notepad++ without installing any extensions too which creates a backup after x seconds and creates a backup on file save.

The feature settings could include:
- The dir path where the backup files should save.
- How long the backup files should last for before they are auto-deleted (1 week, 1 month, 1 year, forever).  (not included with the saveBackup extension, the files last forever and so will have to delete the files when you no longer want them on your machine).
- Backup the file on save or every x seconds of the current file. (not included with the saveBackup extension, it's save only). I prefer the the files to backup on save.

Note: The vscodebot message that has come up is different from this question which is about backing up settings.

**Comment by sandy081** [comment]
VS Code supports hot exit feature that supports backing up files which are dirty. May I know why do you want to back up a file that is already saved?

**Comment by andym196** [comment]
One example: I remember once when I was working on Notepad++, my computer suddenly turned off, when I turned the computer back on, the file I was working on was corrupted, and every time I tried to open this file in any editor, the file was just corrupted. The last time I did a manual backup was a few weeks before that, so all the work I did on that file in the last few weeks would've been lost, but Notepad++ saves backup files of the files you're currently working on regularly, so I was able to use that.
