### ISSUE TITLE
extensionManagementService depends on telemetryService which is NOT registered

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8559]
Seeing this running out of sources on master:

```
~/Development/Microsoft/monaco/scripts> ./code.sh 
[createInstance] extensionManagementService depends on telemetryService which is NOT registered.

```

**Comment by jrieken** [comment]
That for sure the shared process in which a injector is set up but no telemetry service is around. Either have the service or use `@optional`

**Comment by joaomoreno** [comment]
Oops... experiment leftovers... 👍

**Comment by jrieken** [comment]
@joaomoreno You should run the instantiation service in [`strict`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/instantiation/common/instantiationService.ts#L24)-mode to see this early

**Comment by joaomoreno** [comment]
So... when in development it is not strict by default, correct?

**Comment by jrieken** [comment]
No. When the flag is set to `true` it will throw when a dependency cannot be fulfilled. The only reason this isn't the default are tons of tests that use incomplete containers

**Comment by joaomoreno** [comment]
Got it.
