### ISSUE TITLE
Run tasks in a particular working directory

### ISSUE THREAD

**Issue by kojoru** [Microsoft/vscode#856]
Suppose I have a complex project with several directories, each sporting its own `makefile`. I'd like to set up several tasks (e. g. build dir1, build dir2). However there's no working directory option to be set in VS Code, so I'm unable to complete the task. 

Maybe that's actually possible, then it's a documentation issue since I was unable to find a way by reading it. What do you suggest?

**Comment by kojoru** [comment]
@dbaeumer do you think that feature will be accepted if I implemented it as a pull request?

**Comment by dbaeumer** [comment]
@kojoru yes, PR are always welcome.

**Comment by dbaeumer** [comment]
[Addressed in new terminal runner]

The new terminal runner support specifying commands per tasks which allows to set the cwd per task.

**Comment by robert-goheen-cko** [comment]
@dbaeumer Can you post a link to any information or examples on how to set this up in the tasks.json?

**Comment by dbaeumer** [comment]
https://code.visualstudio.com/updates/v1_10#_task-support

**Comment by ahaverty** [comment]
cwd is available under options e.g:
```
{
    "taskName": "Run tests",
    "type": "shell",
    "command": "npm run test",
    "group": "test",
    "options": {
            "cwd": "${workspaceFolder}/functions"
    },
    "presentation": {
            "reveal": "always",
            "panel": "new"
    }
}
```

**Comment by dbaeumer** [comment]
@ahaverty thanks.

I will close the issue since the new terminal runner is now the default. There are no plans to support this in the old output runner.

**Comment by ahaverty** [comment]
👍 Not sure what you mean @dbaeumer, 
options.cwd is setting the working directory for the task's command for me in the latest release (1.17.1) in v2.0.0 tasks. (I'm just filling in the blanks for anyone else that stumbles across this issue.)

(_Is this outdated? I can't find anything about setting the cwd in the [docs](https://code.visualstudio.com/docs/editor/tasks)_)

**Comment by dbaeumer** [comment]
For the documentation see here: https://code.visualstudio.com/docs/editor/tasks-appendix
