### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by mikemillerworldpay** [microsoft/vscode#85607]
Issue Type: <b>Bug</b>

Intellisense/Code Completion is not working. 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|10.2.0
git-project-manager|fel|1.7.1
Db2connect-win|IBM|1.1.0
r|Iku|1.1.8
r|Mik|0.0.6
python|ms-|2019.11.50794
sqltools|mtx|0.21.3
change-case|wma|1.0.0
plsql-language|xyz|1.8.2

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please elaborate on what file intelli-sense is not working. A screenshot or a gif or steps to reproduce would be helpful.
