### ISSUE TITLE
Übersetzungsdatein (xlf) werden nicht gefunden 

### ISSUE THREAD

**Issue by Kanuility** [microsoft/vscode#85600]
Issue Type: <b>Bug</b>

Über die genau vorgehensweise bin ich mit nicht sicher, aber ich kann Ihnen einige ungenau schritte erläutern wie dieser Fehler entstanden ist.
Visual Studio Code version: 14.02

Schritt 1: Al Language installieren 
Schritt 2: Taste F1 Drücken und befehl Al: Go nutzen
Schritt 3: Eine tabelle Erstellen und eine Liste (der inhalt der Tabelle ist in diesem Falle egal)
Schritt 4: Launch.json auf Ihren Business central 14 Server einstellen
Schritt 5: Erstmaliges anlegen einer Übersetzungdatei (xlf) 
Beschreibung:
Ich habe in App.json mit   "features": ["TranslationFile"]  eine Übersetzungsdatei erstellt.
Schritt 6: Veröffentlichen und Schließen
Schritt 7: Umbenenen der Übersetztungsdatei in "de-DE.xlf"
Schritt 8: "target-language" auf  "target-language="de-DE"" ändern
Schritt 9: Übersetzen 
Schritt 10: Erneut veröffentlichen und Schließen
Schritt 11: Neue Felder hinzufügen mit entsprechenden Captions
Schritt 12: Erneut veröffentlichen Schließen
Schritt 13: Alle Daten aus der Unübersetzte datei (Standart) Kopieren und in der Übersetzten alles mit diesen Daten ersetzten
Schritt 14: "target-language" auf  "target-language="de-DE"" ändern
Schritt 15:  Übersetzen 
Schritt 16: Erneut veröffentliche nun sollten nur die Captions zusehen sein und die Übersetzungsdatei wird ignoriert 

Ich habe keine ahnung wie ich den Fehler besser Beschreiben soll.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|1.0.21
al|Mic|3.0.106655
vscode-language-pack-de|MS-|1.40.2
cpptools|ms-|0.26.1
al-var-helper|ras|2.4.0
crs-al-language-extension|wal|1.1.21

</details>

**Comment by sandy081** [comment]
Please file this issue against the extension that is providing this behaviour.
