### ISSUE TITLE
Open all closed tags(i.e. <div>) shortcut for huge file (i.e. html )

### ISSUE THREAD

**Issue by cvddev** [microsoft/vscode#85602]

**Comment by cvddev** [comment]
Missing feature of a shortcut or in menu.

**Comment by IllusionMH** [comment]
Do you mean folded/collapsed components (content hidden, chevron near line number faces right)?
![image](https://user-images.githubusercontent.com/1312662/69647478-3b929600-1072-11ea-8398-94f78593d545.png)
_(JS example)_

If yes, these are Fold/Unfold commands. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and type `>fold` to see folding/unfolding commands.
