### ISSUE TITLE
Keyboard input disabled when opening a new editor (macOS)

### ISSUE THREAD

**Issue by TheSonOfThomp** [microsoft/vscode#85609]
Issue Type: <b>Bug</b>

When I have a file open and use `CMD + \` to open the file in a separate column, all keyboard inputs are disabled on that file.
Similarly, inputs are disabled when using `CMD + OPT + 2`.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|/Users/athompson/Documents/GitHub/confluence-zeplin-embed-addon|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
vscode-file-templates|bam|1.1.0
bracket-pair-colorizer-2|Coe|0.0.28
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.9
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.9.0
sass-lint|gle|1.0.6
docthis|joe|0.7.1
rainbow-csv|mec|1.3.1
Angular-BeastCode|Mik|8.1.2
theme-monokai-pro-vscode|mon|1.1.14
python|ms-|2019.11.50794
sublime-keybindings|ms-|4.0.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
storybook-snippets|nor|0.0.5
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
vscode-template-literal-editor|pli|0.9.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
code-spell-checker|str|1.7.20
markdown-all-in-one|yzh|2.5.1
material-theme|zhu|3.1.2

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please try to reproduce it by disabling all extensions?
