### ISSUE TITLE
Typescript Auto-import doesn't respect whitespace style

### ISSUE THREAD

**Issue by smbkr** [microsoft/vscode#85605]
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

When automatically importing in a Typescript project, the curly braces surrounding the imported object are padded with whitespace as follows:
```ts
import { Context } from './context';
```

Some of the projects I work on follow a different style-guide that prohibits whitespace within the import braces, ie.:
```ts
import {Context} from './context';
```

There doesn't appear to be a way to configure VS Code to format automatically added imports as such at the moment. Is it possible to configure it to behave this way?

**Comment by mjbvz** [comment]
Have you configured the built-in js/ts formatter to do remove whitespace in import destructurings?

**Comment by smbkr** [comment]
Thanks @mjbvz, I managed to find and configure the setting, and it now works as desired. I did search through the settings initially but couldn't find the correct one until I searched again. For future reference, the setting is `typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces`.
