### ISSUE TITLE
Electron crash: async hook stack has become corrupted

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#85601]
I stumbled upon this by chance, investigating https://github.com/microsoft/vscode/issues/84425

```ts
KeybindingsRegistry.registerKeybindingRule({
	id: SetEditorLayoutAPICommand.ID,
	args: { orientation: 0, groups: [{ groups: [{}, {}], size: 0.5 }, { groups: [{}], size: 0.5 }] },
	weight: 999999,
	when: undefined,
	primary: KeyMod.CtrlCmd | KeyCode.KEY_P
});
```

1. `git checkout 47736a99f1c0ea7150e5774f37952bdc6e0fa5d4`
2. Open `apiCommands.ts` and append the snippet above at the end, and automatically add imports
3. Run out of sources
4. Press Ctrl/Cmd+P
5. Close the editor to the right

Electron will just freeze after printing out the exception to the devtools. Error in terminal:

```
Error: async hook stack has become corrupted (actual: 6316, expected: 0)
```

Could it be related to https://github.com/microsoft/vscode/issues/83994? cc @roblourens

**Comment by deepak1556** [comment]
Thanks for the test case, I am able to repro the issue. This is a different one, `async_hooks` don't work with electron at the moment 

Relevant discussions:
https://github.com/electron/electron/pull/12109#pullrequestreview-252043639 
https://github.com/electron/electron/pull/18452
https://github.com/electron/electron/issues/19466

You can workaround this temporarily by setting the following env variable `export NODE_OPTIONS="--no-force-async-hooks-checks"`

**Comment by MaxYari** [comment]
@deepak1556 what does "workaround" means in that case? There must be a reason for this to be a hard error, I suspect muting it will just lead to some unexpected execution behaviours. If that's the case - that's not really a valid workaround by any means.

**Comment by DanTup** [comment]
I don't know if this is useful (or even the same issue), but I got this same error message in a CI run on GitHub actions (seems like a flake, as only one bot failed with it):

```
Error: async hook stack has become corrupted (actual: 1391, expected: 0)

 1: 0x10e6d1ae4 node::InternalCallbackScope::Close() [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10e6d1999 node::InternalCallbackScope::Close() [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

 3: 0x10e6d1da3 node::InternalCallbackScope::Close() [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

 4: 0x10e6d1fd1 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

 5: 0x10e7056a5 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x10e8403fd uv_check_stop [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

 7: 0x10e83ab59 uv_run [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

 8: 0x1091a5731 AtomInitializeICUandStartNode [/Users/runner/runners/2.262.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
```

https://github.com/Dart-Code/Dart-Code/runs/692332413#step:15:225

**Comment by debchy** [comment]
in the main page of Electron, just add bellow environment variable. it will stop the cras.
`process.env["NODE_OPTIONS"] = '--no-force-async-hooks-checks';`

**Comment by yogithecoder** [comment]
I had the Same issue and my application screen went blank and white. Later i discovered it all happened because i was getting an element by id as file in html input which was actually a text. After i commented out that line , my application was working. 
I think when the javascript hits any silly bug the electron app crashes and shows that error

**Comment by basiclaser** [comment]
> in the main page of Electron, just add bellow environment variable. it will stop the cras.
> `process.env["NODE_OPTIONS"] = '--no-force-async-hooks-checks';`

This is currently not working for me in line 1 of main file

**Comment by basiclaser** [comment]
> > in the main page of Electron, just add bellow environment variable. it will stop the cras.
> > `process.env["NODE_OPTIONS"] = '--no-force-async-hooks-checks';`
> 
> This is currently not working for me in line 1 of main file

It was related to an invalid file path for a tray icon:
```
main.tray = new Tray("/invalid/file/path.png");
```
The issue was fixed by fixing the file path. Shame the error didn't mention the underlying issue. without `'--no-force-async-hooks-checks'` and fixed path everything is fine.

**Comment by debchy** [comment]
> > > in the main page of Electron, just add bellow environment variable. it will stop the cras.
> > > `process.env["NODE_OPTIONS"] = '--no-force-async-hooks-checks';`
> > 
> > 
> > This is currently not working for me in line 1 of main file
> 
> It was related to an invalid file path for a tray icon:
> 
> ```
> main.tray = new Tray("/invalid/file/path.png");
> ```
> 
> The issue was fixed by fixing the file path. Shame the error didn't mention the underlying issue. without `'--no-force-async-hooks-checks'` and fixed path everything is fine.

So, your issue is not related to "async hook stack".

**Comment by basiclaser** [comment]
> > > > in the main page of Electron, just add bellow environment variable. it will stop the cras.
> > > > `process.env["NODE_OPTIONS"] = '--no-force-async-hooks-checks';`
> > > 
> > > 
> > > This is currently not working for me in line 1 of main file
> > 
> > 
> > It was related to an invalid file path for a tray icon:
> > ```
> > main.tray = new Tray("/invalid/file/path.png");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The issue was fixed by fixing the file path. Shame the error didn't mention the underlying issue. without `'--no-force-async-hooks-checks'` and fixed path everything is fine.
> 
> So, your issue is not related to "async hook stack".

i did receive the `Error: async hook stack has become corrupted (actual: 1391, expected: 0)` error, but im not an expert on why :D
I resolved the issue in the way i mentioned though.

**Comment by deepak1556** [comment]
Closing since workbench no longer runs with Nodejs integration.
