### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by saeefahmed** [microsoft/vscode#85604]
Issue Type: <b>Bug</b>

when I switch between windows screen goes black for couple of seconds

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61

</details>

**Comment by IllusionMH** [comment]
@saeefahmed have you see this issue before recent update to 1.40.<b>2</b> ?
This version included fix exactly for this problem. #84343

/cc @deepak1556

**Comment by deepak1556** [comment]
@IllusionMH yup thats fine :) 

@saeefahmed can you attach a video demo of what you are observing.
