### ISSUE TITLE
Misleading "Discard All Changes" Icon

### ISSUE THREAD

**Issue by lschnoller** [microsoft/vscode#85611]
Issue Type: <b>Bug</b>

The "discard all changes" icon in the source control module is completely misleading and dangerous. I clicked that button (and impulsively confirmed) thinking it would reload the commit file list and instead it completely wiped out a month of work (because i hadn't committed in that whole period). If a button is going to delete something i would find a trash can a much better option than a rounded arrow, which resembles the reload button of any browser, even if it's backwards. Given the complete mess that can be done in an involuntary delete like this one, i would recommend changing the icon to something like a trash can and having a restore option of some sort in case someone clicks it by mistake.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ant-design-vue-helper|ant|1.0.6
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.1
sepaswitch|Fut|1.0.2
gc-excelviewer|Gra|2.1.32
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
vue-vscode-snippets|sdr|1.8.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by joaomoreno** [comment]
Sorry you have lost all your work. There's been lots of discussion around this feature, present in many tools, and we do show a very alarming dialog which you must confirm. The dialog mentions exactly what's going to happen, including the word `DELETED` in all caps, making the decision quite voluntary. I highly recommend saving your work often and having backups. This could have happened with any tool, including command line git.
