### ISSUE TITLE
VS code cannot download update

### ISSUE THREAD

**Issue by zigzack001** [microsoft/vscode#85615]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

VS code shows update available, it start downloading but took long time. After closing it it shows update available. Every time I need to reinstall VScode.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.93GB (35.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
es7-react-js-snippets|dsz|2.4.4
vsc-material-theme|Equ|30.0.0
python|ms-|2019.11.50794
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.2
vscode-css-peek|pra|3.0.2
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.0

</details>

**Comment by joaomoreno** [comment]
Can you try changing the `update.enableWindowsBackgroundUpdates` setting to `false` and see whether this fixes it?
