### ISSUE TITLE
Settings sync disable and delete data command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85618]
There should be some command that allows users to turn off and delete their data.

**Comment by Tyriar** [comment]
We should have this command also to cause other machines of the user to disable sync. I think we could do this by turning sync off when an unexpected `0` etag shows up as that means that the server went from some records to zero records.

**Comment by sandy081** [comment]
/duplicate

This will be covered as part of settings sync ux - #85216

**Comment by sandy081** [comment]
Reconsidered to handle this separately.

**Comment by sandy081** [comment]
@Tyriar Does the server supports indicating that sync is turned off everywhere? I think eTag `0` is already used for no resource. May be we can use a different predefined eTag for this scenario?

**Comment by Tyriar** [comment]
@sandy081 if you delete all data from the server, an etag of 0 will be sent back as the latest as you say. So if a client tries to sync with a non-0 etag and it gets back 0, it then knows that all sync data has been deleted and turned off.

**Comment by sandy081** [comment]
You can now turn off sync in all your devices by checking the check box in turn off confirmation dialog.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/10746682/72424929-0ad40080-3787-11ea-9d20-32f5601108f7.png">
