### ISSUE TITLE
Associated language

### ISSUE THREAD

**Issue by omgthecolorpurple** [microsoft/vscode#85614]
Issue Type: <b>Bug</b>

make a new file, configure associated language for file, choose language, get unable to write into user settings. Please open user settings to correct errors/warnings in it and try again. So I do open it, look around and I have no idea about what the issue is besides to just write the language association in myself

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
Open the settings file and see if there are any errors in that file. You can do that by
- Opening Settings Editor
- Click on the button on the top right corner to open settings file
