### ISSUE TITLE
HTML `method ` attribute value's description

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#85610]
This happens in Insiders v1.41.0
- VSCode Version: 1.40.2
- OS Version: macOS 10.15.1

Steps to Reproduce:

1. Copy this HTML `<form action="" method=""></form>`
2. Put your cursor inside the `method="|"` of the `form` tag and `ctrl+space` for autocompletion.
3. Notice the visual bug in the value's description box.

<img width="1054" alt="Screenshot 2019-11-26 at 16 27 03" src="https://user-images.githubusercontent.com/22457463/69653172-af30a500-106a-11ea-9214-9448ff842d51.png">

Does this issue occur when all extensions are disabled? Yes

**Comment by octref** [comment]
Verifier: Verify you get this:

![image](https://user-images.githubusercontent.com/4033249/69764068-faf35500-1123-11ea-81cf-a886925e4cfc.png)
