### ISSUE TITLE
Settings sync history command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85619]
There should be some command to view old versions of settings.

**Comment by bronson** [comment]
Yes please. Having a view that shows what changed over time is very useful.

Example: https://github.com/bronson/dotfiles/commits/master/.vscode/settings.json

**Comment by sandy081** [comment]
![image (1)](https://user-images.githubusercontent.com/10746682/76545256-bfd62100-6489-11ea-9989-0af5be04c9dc.png)

![image](https://user-images.githubusercontent.com/10746682/76545260-c06eb780-6489-11ea-902e-fc6e0813e0b5.png)

**Comment by sandy081** [comment]
Reopening as there is a bug on server.
