### ISSUE TITLE
Vs Code c++ doesn't work

### ISSUE THREAD

**Issue by ViperKey** [microsoft/vscode#85616]
Whith the new version snippets does not work
![Screenshot (4)](https://user-images.githubusercontent.com/58229802/69659961-9b436e00-107f-11ea-984f-3184f1d13179.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo
By "the new version" do you mean new VS Code version? 1.40.2? Or 1.41.0-insider? Or new extension version?

Also, what version were you previously using and not seeing this problem?
