### ISSUE TITLE
Many icons are shifted down and to the right on the high contrast theme

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8561]
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

This seems to be happening with several different icons (panel, tab editor actions).

Dark+

![image](https://cloud.githubusercontent.com/assets/2193314/16479485/73944118-3e55-11e6-9c51-3fb5be0adcb7.png)

HC

![image](https://cloud.githubusercontent.com/assets/2193314/16479500/86dd37c0-3e55-11e6-874c-7c5c1f449b51.png)

**Comment by bpasero** [comment]
Not anymore.
