### ISSUE TITLE
Notification text overflow

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85617]
![image](https://user-images.githubusercontent.com/323878/69661193-cb1a5380-1036-11ea-9fa0-67df6ff9c1b1.png)

Expands to
![image](https://user-images.githubusercontent.com/323878/69661152-ba69dd80-1036-11ea-9778-eb96539b9e52.png)

I see this when debugging the vscode-pwa extension and it fails to activate.

**Comment by bpasero** [comment]
This may be related to our overflow changes for LCD rendering.

**Comment by bpasero** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/900690/70228460-addf3680-1754-11ea-87cd-2dae413e644e.png)

Code I use to manually trigger:

`notificationService.error("Activating extension 'ms-vscode.js-debug' failed: command 'extension.pwa-node-debug.pickNodeProcess' already exists.");`

@roblourens can you try if you reproduce?

**Comment by roblourens** [comment]
I saw it randomly again, let me try to get a consistent repro

![image](https://user-images.githubusercontent.com/323878/70262342-09a3c280-1749-11ea-8b79-982426f76d99.png)

**Comment by roblourens** [comment]
That line of code does it for me too

![image](https://user-images.githubusercontent.com/323878/70262621-8d5daf00-1749-11ea-9cab-f15ca5303bda.png)

My previous screenshot was on Windows, this is on Mac

**Comment by roblourens** [comment]
Can't repro it in an extension, but there is an extra line after the second message which makes me think the height is not calculated correctly

![image](https://user-images.githubusercontent.com/323878/70262854-f04f4600-1749-11ea-8b00-a488a3fa217a.png)

**Comment by bpasero** [comment]
@roblourens so you can reproduce it with my sample code? Also from a fresh working dir?

**Comment by roblourens** [comment]
Yeah, I paste that code somewhere, launch Code - OSS with some new `--user-data-dir`, and it still reproes.

**Comment by bpasero** [comment]
@roblourens macOS? external monitor?

**Comment by bpasero** [comment]
Also, how do you end up triggering the notification expansion, using mouse click?

**Comment by roblourens** [comment]
macOS, the macbook display currently, I also saw it on an external monitor. Yeah mouse click

**Comment by bpasero** [comment]
@roblourens time to debug this. The key method to look at is the one to compute the height of the message when it gets expanded. Steps:
* bring up the notification
* add a breakpoint into [`getHeight`](https://github.com/microsoft/vscode/blob/a416c77e56ef0314ae00633faa04878151610de8/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L47)
* expand the notification
* step through and have the values show up inline to compare with:

![image](https://user-images.githubusercontent.com/900690/70370198-5c55b980-18c4-11ea-94e9-62ac24e1e7ad.png)

**Comment by bpasero** [comment]
Also of interest, how the offset helper is looking like. That is the one I render the message into and then compute its dimensions:

![image](https://user-images.githubusercontent.com/900690/70370235-e9990e00-18c4-11ea-8708-4316de112c26.png)

Breakpoint to here: https://github.com/microsoft/vscode/blob/a416c77e56ef0314ae00633faa04878151610de8/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L95

**Comment by roblourens** [comment]
Seems that the width of the offset helper is not correct, so it's measured at 2 lines when it actually wraps to 3. This fixes it

`this.offsetHelper.style.width = `calc(100% - ${10 /* padding */ + 26 /* severity icon */ + (actions * 24) /* 24px per action */ + 10 /* other padding */}px)`;`

https://github.com/microsoft/vscode/blob/2bb6cfc16a88281b75cfdaced340308ff89a849e/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L88

**Comment by bpasero** [comment]
@roblourens I pushed a change to put the severity width to `26px` from `24px`, can you try? I do not understand where you take the additional `10px` padding from? Can you explain?

**Comment by roblourens** [comment]
`.notification-list-item` is 450px. But the 100% in `.notification-offset-helper`'s is being resolved to `460px`. I am comparing it to stable, where `.notification-offset-helper` is based on `450px` and I have no idea why they are different.

**Comment by roblourens** [comment]
The extra 10 seems to come from the margin on `.notification-toast` but that margin is also there in stable and it isn't a problem, and I don't know why.

**Comment by bpasero** [comment]
I pushed a change to simply take 450px as the width, I am not sure why it was going to 460 but it should be OK now.
