### ISSUE TITLE
search window not resized on split

### ISSUE THREAD

**Issue by johngrabner** [microsoft/vscode#85629]
Issue Type: <b>Bug</b>

1) ctrl-f to open the search window
2) stretch the search window so it covers more than half of the main window
3) split right

Observe the search window controls (Aa, full word, x of x, ^v, find in selection) are no longer visible.

Should resize the search window so it fits in the new split window.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (36.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.8.2
python|ms-|2019.11.50794
LiveServer|rit|5.6.1

</details>

**Comment by rebornix** [comment]
Good catch!
