### ISSUE TITLE
Borked bracket matching in Rust

### ISSUE THREAD

**Issue by Barugon** [microsoft/vscode#85620]
Issue Type: <b>Bug</b>

The highlighted brackets are incorrect when editing Rust files. Please see screenshot and note where the cursor is vs where the brackets are highlighted.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.3.11-300.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 1964)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|9.73GB (3.43GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.5.0
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.32.0
godot-tools|gee|0.3.7
rainbow-csv|mec|1.3.1
cpptools|ms-|0.26.1
rust|rus|0.7.0
vscode-lldb|vad|1.4.1

</details>

![Screenshot from 2019-11-26 10-41-55](https://user-images.githubusercontent.com/16503728/69663277-c5267180-103a-11ea-81c1-9eb049de9be3.png)

**Comment by Barugon** [comment]
This is possibly the same bug as #84281

**Comment by alexandrudima** [comment]
@Barugon I have tried with the file at https://github.com/Barugon/CotA/blob/5baf3fdc0beef31e1a8c8bd2cb0afe7f4f65f4bd/thread_pool/src/lib.rs

But for me, when I place the cursor on line 124, the bracket highlights are correct:
![image](https://user-images.githubusercontent.com/5047891/70063864-caf6f680-15e8-11ea-993a-8e910604b19c.png)

**Comment by Barugon** [comment]
@alexandrudima 
I disabled the rust-lang extension and it works correctly. This is their issue so I'm closing this one.
