### ISSUE TITLE
"escape" clears error messages

### ISSUE THREAD

**Issue by loftusa** [microsoft/vscode#85627]
Small feature request -- it'd be nice if `escape` cleared the VSCode error boxes that appear in the bottom right so that we don't have to click on them.

e.g., `escape` would map to "dismiss" here:

<img width="670" alt="Screenshot 2019-11-26 14 40 29" src="https://user-images.githubusercontent.com/12386450/69667064-4b52b000-105b-11ea-8156-d661efda0fff.png">

**Comment by bpasero** [comment]
It does. ESC is registered as command to close notifications. If this does not work for you you possibly changed keybindings or have an extension that steals it?
