### ISSUE TITLE
Status bar items get cut off

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85638]
Been seeing this lately:

![image](https://user-images.githubusercontent.com/323878/69680182-fdd84200-105e-11ea-8cec-93ef46e6f884.png)

Not sure how sizing is supposed to work here or what changed but I can debug more if you don't see it.

![Nov-26-2019 15-13-41](https://user-images.githubusercontent.com/323878/69680299-69221400-105f-11ea-8dc0-3182c6fc6262.gif)

**Comment by isidorn** [comment]
Ben is on vacation. I did not see this. @roblourens if you think this is a recent regression and should be fixed please speak up

**Comment by roblourens** [comment]
It's only in Insiders. Pretty easy to repro. Have you worked on the status bar? Might still be worth looking into if someone is able.

**Comment by isidorn** [comment]
I have not worked on the status bar. However I can look into this if time permits. Assigning for now to both of us and December.

**Comment by roblourens** [comment]
I looked at it a bit and @sandy081 I think it's from https://github.com/Microsoft/vscode/commit/dd4f9d1a73cb74c3e384ab30e3711aaacecffc13

**Comment by sandy081** [comment]
Yes, recently I have changed the wrapping in status bar.

Can I have steps to repro please?

**Comment by roblourens** [comment]
Just make the window narrower until the left and right sides run into each other.

**Comment by sandy081** [comment]
Made status bar items on the left remain (not hidden) and status bar items on the right wraps as the size reduces.
