### ISSUE TITLE
Highlight primary cursor differently than other cursors

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#85630]
With the addition of [auto selecting matching tags](https://github.com/microsoft/vscode/issues/47069#issuecomment-557644701) in HTML, it becomes harder to see which one is the active cursor:

![auto-selection](https://user-images.githubusercontent.com/4033249/69450026-0e13b880-0d11-11ea-8505-9fbc2a8fc6ba.gif)

I suggest adding a new color key so themes can show primary cursor differently than other cursors. This would make it possible to understand where the cursor would go to when you press ESC in a multi-cursor mode as well.

**Comment by octref** [comment]
Duplicate of #86947.

**Comment by akbyrd** [comment]
I have a PR available for this: https://github.com/microsoft/vscode/pull/181991
