### ISSUE TITLE
Investigate removing Max results limitation for Search and replace results

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#8563]
Investigate removing Max results limitation for Search and replace results

Currently we set max limit to 10000. We need to investigate on lifting this.

**Comment by sandy081** [comment]
@chrmarti Assigning this to you.

I see that you are working on improving the performance for Search results. Currently we have an hard limitation of 2048. But we never measure what is the threshold. Since you are already exercising Search performance this would be a good one to look at.

Thanks

**Comment by haerfest** [comment]
I noticed #8529. An improvement may be to not open all files in which terms were found and replaced. As a software engineer myself I sometimes have to make many changes (just today some 33k machine names in 280 XML files).

Version 1.3.1 crashed on me, but even if it had worked, I would have stared at many open files. And there's no shortcut to "save all" and "close all" :(

I had to revert to Notepad++, which simply makes the changes in-place on disk, without opening all files. Maybe doing something similar is an option?

**Comment by nkkollaw** [comment]
This would be nice to fix/improve.

I have to open Atom just to do find/replace.

**Comment by markdreyer** [comment]
There should at least be a warning telling the user that not all the occurrences have been replaced. It is very misleading when "Replace All" only replaces the first 10000 items.

**Comment by NiklasBr** [comment]
Please increase this number or make it configurable

**Comment by agrexgh** [comment]
Same here.
I'd like you to make the number configurable.
I'd like to set this to "No Limit" also, hopefully.

**Comment by ali3nnn** [comment]
The current upper bound for search in VSCode is 19999 occurrences. Is there a way to change it?

**Comment by skupjoe** [comment]
Please make this maximum / upper boundary configurable.

**Comment by rzhao271** [comment]
I wonder what `search.maxResults` is measuring?

![maxres](https://user-images.githubusercontent.com/7199958/123849676-ecf05200-d8cd-11eb-99ab-860900f0e5c0.PNG)

Also, when I set it to 2000, I see 4000 results show up when I search a single letter. @roblourens

**Comment by roblourens** [comment]
You will also get results in open files beyond the limit

**Comment by jrieken** [comment]
This is a bit of a foot gun... Using some ridicules high value freeses VS Code eventually. Will create a separate issue for that
