### ISSUE TITLE
There are never Code Actions available for Python

### ISSUE THREAD

**Issue by rafwaf** [microsoft/vscode#85639]
I'm writing code in Python, and I was hoping to refactor out a method. I searched for a way to do that, and that's when I realized that Code actions are never available, regardless of what code I select, even when I click 'ctrl+.'
I don't know what minimal code would replicate this, and I suspect it's not in my own code, so there is probably no point in including it.
I'm wondering if this is happening to me because of something in my local environment/setup or is every Python/VSCode user seeing this bug, and what can I do about it. Let me know what further info you might need.
Thank you.

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1.Write and select any Python code
2.Press 'ctrl + .' to try to bring up Code Actions
3.No Code Actions will be available.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, because there are no Code Actions and refactoring without the extension.

**Comment by sandy081** [comment]
File issue against Python extension
