### ISSUE TITLE
Activity bar’s border vanishes when it is moved to the right

### ISSUE THREAD

**Issue by m2u-84** [microsoft/vscode#85637]
**Environment specs:**

- VSCode Version: 1.40.2
- OS Version: Windows 10 Pro (1909) x64

**Steps to Reproduce:**

1. Open VS Code
2. Open one item of the activity bar, e. g. the SCM tab
3. Load editor’s global settings.json
4. Add the following block to it:
```
    "workbench.colorCustomizations": {
        "activityBar.activeBorder": "#ffffff",
        "activityBar.activeBackground": "#425080"
    }
```
5. Save the settings file → activity bar tab appears with background color and border as expected
6. Now also add the following setting:
```
    "workbench.sideBar.location": "right"
```
7. Save the settings file → activity bar moves to the right and tab still appears with background color (expected), but the white border is suddenly gone (unexpected), cf. this screenshot:

![activity-bar-border-bug](https://user-images.githubusercontent.com/11140006/69678933-30a62880-10a7-11ea-90f6-6e6c1d6a71bc.png)

Does this issue occur when all extensions are disabled?: Yes

Thanks for taking a look at this and keep up the great work!

**Comment by misolori** [comment]
@m2u-84 does this happen with all views or just the SCM view? Does it change if you open a project with Git? I'm not able to reproduce, though I do see that the border is small.
