### ISSUE TITLE
can't open a folder twice

### ISSUE THREAD

**Issue by rorschachYoung** [microsoft/vscode#85647]
there is a vue project and a nodejs project in a folder ,i want open this folder twice ,one for vue, one for server,but it only open the folder once, it's hard to working in mixin project.

**Comment by IllusionMH** [comment]
/question

You can do this using `>Workspaces: Duplicate Workspace in New Window` from Command Palette (<kbd>F1</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
