### ISSUE TITLE
Show Fixes hard codes the keyboard shortcut

### ISSUE THREAD

**Issue by mbward** [microsoft/vscode#85640]
I've set Ctrl+. to `editor.action.goToDeclaration`.

When I edit a `.ts` file, I see a lightbulb. When I hover over it, it says "Show Fixes (Ctrl+.)". Then I press Ctrl+., and it goes to the declaration, it does not show fixes.

vscode 1.39.2 on Linux.

**Comment by gjsjohnmurray** [comment]
Do you also have ```problems.action.showQuickFixes``` bound to the same key combination? See https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts for advice on finding conflicts.

**Comment by mjbvz** [comment]
You need to also unbind: `problems.action.showQuickFixes`. Otherwise it is still a valid keybinding as there can be cases where goToDeclaration is disabled but quick fixes are enabled (such as if a language only provides quick fixes but not go to definition support)
