### ISSUE TITLE
Trigger suggestion shortcut on Mac not working

### ISSUE THREAD

**Issue by vr19860507** [microsoft/vscode#85643]
The same problem like this https://github.com/microsoft/vscode/issues/66031

Could you change "Trigger suggestion" shortcut because it conflicts with default Mac OS keyboard switch

**Comment by gjsjohnmurray** [comment]
Did you follow the advice given by @egamma at https://github.com/microsoft/vscode/issues/66031#issuecomment-451496772 ?

Also some guidance about customizing your keybindings [here](https://code.visualstudio.com/docs/getstarted/keybindings).

**Comment by vr19860507** [comment]
I don't found there any information about control+space. I use apple Magic Keyboard with russian and english languages.

**Comment by vr19860507** [comment]
Yes i know how to customize keyboard shortcuts, but why they conflict by default?

**Comment by gjsjohnmurray** [comment]
AFAIK the OSX keyboard switch sequence used to be Cmd+space, so there wouldn't have been a conflict with what VS Code uses control+space for. Then Apple changed things.

**Comment by vr19860507** [comment]
Yes, but if Apple changes the default behavior, I think you also should.

**Comment by jrieken** [comment]
Are you saying that Apple uses <kbd>CTRL+space</kbd> for something? Iff so what is it and what version of the macOS is that? I use Catalina with US layout and ctrl+space is working in VS Code as intended and cmd+space launches spotlight.

**Comment by vr19860507** [comment]
I also use Catalina but i have russian and US layout .

**Comment by vr19860507** [comment]
Try add another language to your system

**Comment by vr19860507** [comment]
This is default settings
[https://ibb.co/N9wRYdH](https://ibb.co/N9wRYdH)

**Comment by jrieken** [comment]
You can please answer my questions. Are you saying that in the Russian layout ctrl+space is taken for something?

**Comment by vr19860507** [comment]
it is used for switching languages, if there is another input language added

**Comment by jrieken** [comment]
Ok, thanks for clarifying. It seems that Xcode can use ctrl+space despite it being used by the language picker. We cannot, the keyevent never reaches us. The simplest recommendation is to disable/change the input source switcher

<img width="670" alt="Screenshot 2019-11-28 at 13 58 27" src="https://user-images.githubusercontent.com/1794099/69808253-69e5b200-11e7-11ea-98bc-d28ac009d814.png">

The Xcode alternative is <kbd>ESC</kbd> which I can experiment with (on Mac). However, <kbd>ESC</kbd> is quite popular and I don't know how well it will work other command, <kbd>ctrl+esc</kbd> would be an easy alternative.

**Comment by vr19860507** [comment]
No Xcode also can't. if i disable like you on screenshot then it works.

**Comment by jrieken** [comment]
Turns out Xcode also supports <kbd>alt+space</kbd> which I will also support.
