### ISSUE TITLE
Tabs: Coloring issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8564]
Summary of collected issues for coloring in tabs
* editor find widget blends too easy into tab background in dark theme (https://github.com/Microsoft/vscode/issues/7649, https://github.com/Microsoft/vscode/issues/8294)
* we use a lot of opacity to get the different shading to work with the different themes
* people find it hard to distinguish the active tab from the inactive
* in HC theme it is hard to distinguish tabs that are in an inactive group (https://github.com/Microsoft/vscode/issues/8550)
* in HC theme the active tab shifts down (https://github.com/Microsoft/vscode/issues/8551)

Proposed solution from @bgashler1 in https://github.com/Microsoft/vscode/pull/8587

**Comment by bpasero** [comment]
@bgashler1 I pushed a variant of your commit (https://github.com/Microsoft/vscode/commit/681e42f8061cdeb12823be626e0bd28b6aa86c6b) to master for June with the following changes:
* I also use mix-blend-mode for the ::before element so that the border blends nicely in other themes (not sure why you did not set it)?
* I avoid the trick/hack you do with changing the tab size between 34-36px by using z-index for the ::before element. in your solution I noticed the active tab jumping a bit when getting active

There is one thing which I don't like is the dropfeedback color over tabs and tabs container in light theme. It used to be the same blue you get when dragging over the tree or editor area but now with the mixed blend mode, I cannot get this colour to work. It seems this CSS property is inherited like opacity and you cannot disable it? If you have ideas how to solve that, we can still push for it.

**Comment by sandy081** [comment]
Leaving this verification to @bgashler1 based on above comment

**Comment by bgashler1** [comment]
Nice work @bpasero. Unfortunately, I can't think of a simple way around the inheritance problem.  But it really didn't bother me because I can't drag a tab to the "Open Editors" anyway.  Some of the more complex solutions I suggested earlier, such as CSS custom properties, and the CSS 4 pollyfill library would certainly enable us to avoid using the mix-blend mode.

**Comment by bpasero** [comment]
@bgashler1 well you can drag it over to any opened editor and there you would get the large area filled in blue. I will see if I can tweak the color at least a little bit in light theme.
