### ISSUE TITLE
node breakpoints misplaced in source code

### ISSUE THREAD

**Issue by dound** [microsoft/vscode#85644]
Issue Type: <b>Bug</b>

I'm trying to debug jest tests running inside a Docker container with VSCode. My setup is guided by https://github.com/microsoft/vscode-recipes/tree/master/Docker-TypeScript but without the typescript bit.

Whenever I launch my debug configuration, my breakpoints are shifted. This can be corrected by using the "Reapply All Breakpoints" menu in VSCode, but this is tedious.

My setup:
1) VSCode (on mac) launch configuration which uses node a launch target to use npm to run a package.json script.
2) The package.json script starts the containers with docker-compose.
3) The container command is ```nodemon --nolazy --no-lazy --legacy-watch --watch /app --inspect-brk=0.0.0.0:9229 `which jest` --runInBand```
4) I've set breakpoints in my source code.
5) When I launch this, the containers start and the VSCode debugger attaches. However, the breakpoints get shifted until I reapply them.

I'm using node12. This issue also occurs on the latest VSCode insiders version (with no extensions installed).

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (1.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.2.3
vscode-docker|ms-|0.8.2
python|ms-|2019.11.50794
emacs-mcx|tut|0.13.0

</details>

**Comment by roblourens** [comment]
Can you try setting `"disableOptimisticBPs": true`?

**Comment by timiscoding** [comment]
@roblourens Thanks! Adding that in my debug config solved my issue. I'm not using docker, just a simple jest + node project. 

vs code 1.40.2
node v11.10.1
jest 24.9.0
mac os 10.14.6

**Comment by dound** [comment]
Thank you so much @roblourens, this did the trick!
