### ISSUE TITLE
clear console

### ISSUE THREAD

**Issue by wuwenrufeng** [microsoft/vscode#85649]
Issue Type: <b>Feature Request</b>

There is no shortcut key to clear the console

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Go ahead and assign your own:

https://code.visualstudio.com/docs/getstarted/keybindings
