### ISSUE TITLE
Failure message from Variables request to debugger extension is not surfaced

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#85645]
Issue Type: <b>Bug</b>

Similar to #80464.

The code at https://github.com/microsoft/vscode/blob/615732feae7228502eab60919d67837f7a625e7c/src/vs/workbench/contrib/debug/common/debugModel.ts#L117-L127 caters for an exception thrown by a debugging extension. But they never do that. What they do is return ```response.success: false``` and a message in ```response.message```

VS Code version: Code - Insiders 1.41.0-insider (a8158aee897bea1c1ec6545b55c4f7d0de57ed38, 2019-11-26T21:13:19.311Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
@gjsjohnmurray Good catch!
Would you be willing to provide a PR that fixes this? The PR should check the response.success and if it is `false` also return the dummy `Variable` which would hold the error message.

**Comment by gjsjohnmurray** [comment]
My initial diagnosis was incorrect, and the fix (see PR) turned out to be trivial.

**Comment by weinand** [comment]
If the variable request returns an error response 'foo bar' it shows up in the UI as:

<img width="408" alt="2020-01-30_14-18-43" src="https://user-images.githubusercontent.com/1898161/73453165-b8d8d080-436b-11ea-873b-894c5f437897.png">

To emphasize that this is an error I suggest a small change to the error format: don't show the leading space and the colon ':'.

**Comment by isidorn** [comment]
@weinand yes, this makes perfect sense. So this does not get lost I have created issue for next milestone https://github.com/microsoft/vscode/issues/89709
