### ISSUE TITLE
contexts change tab not show tab name

### ISSUE THREAD

**Issue by zhiqiang21** [microsoft/vscode#85648]
版本: 1.40.2
提交: f359dd69833dd8800b54d458f6d37ab7c78df520
日期: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
Steps to Reproduce:

i use contexts app change my app on macos
1.  on 1.39 , i use context app can see tab names, for example change chrome 
![image.png](https://ws1.sinaimg.cn/large/698e22a9ly1g9ccjkzs0nj219m07un32.jpg)
2.but now it's not show , when i open more vscode can't show tab name

![image.png](https://ws1.sinaimg.cn/large/698e22a9ly1g9ccm4tu2tj219208810j.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by vdkuipb** [comment]
I would like to see this feature added as well!

**Comment by isidorn** [comment]
Assigning to @deepak1556 since Ben is on vacation
