### ISSUE TITLE
Custom view item alignment wrong

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85654]
Issue Type: <b>Bug</b>

In the image, you can see that the files pointed too look like they are inside `src`, but they are at the same level.

![image](https://user-images.githubusercontent.com/641685/69694236-191a7000-10a6-11ea-827b-5d839d4a6631.png)

VS Code version: Code - Insiders 1.41.0-insider (a8158aee897bea1c1ec6545b55c4f7d0de57ed38, 2019-11-26T21:13:19.311Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.52GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Eric/code/eamodio/vscode-gitlens|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
I'm not seeing that same issue:
![image](https://user-images.githubusercontent.com/38270282/69791342-9c31e800-11c4-11ea-9723-88f75934090a.png)
Does it happen with every view?

**Comment by eamodio** [comment]
@alexr00 The parent of the mis-aligned children needs to have an icon, and there needs to be another child of the same parent without an icon (and possibly be between the parent and the children with icons)

**Comment by alexr00** [comment]
I can see it now, thanks!

**Comment by alexr00** [comment]
After looking some more, I'd like to leave it as is. Aligning the icon under the twisty results in a child with an icon that is further left than the parent. In your screen shot, the icon is correctly aligned with the the test of the other elements at it's level.

**Comment by eamodio** [comment]
@alexr00 In this screenshot you can see how they are not nested correctly

![image](https://user-images.githubusercontent.com/641685/70086834-2b823580-15e1-11ea-8dfd-7e551cd2ef4f.png)

**Comment by alexr00** [comment]
This is also poorly aligned since the icons are now too far left: 
![image](https://user-images.githubusercontent.com/38270282/70128146-ae0c0300-167c-11ea-956c-7a3dee2f62fb.png)
They are both bad. We need to change how custom trees are aligned more thoroughly to fix this.

**Comment by eamodio** [comment]
I agree that they are too far left, but at least they are nested appropriately. Personally I would choose this over what we have now, but it would be great to get a more robust fix.
