### ISSUE TITLE
Link is not generating

### ISSUE THREAD

**Issue by bilalhashmi1** [microsoft/vscode#85659]
Issue Type: <b>Bug</b>

Goto link is not generating or not getting that file mostly.

Extension version: 0.0.3
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
![image](https://user-images.githubusercontent.com/49593487/69698660-c5d90980-1107-11ea-964d-8f1b1782f953.png)

|VM|0%|
</details>

**Comment by awsumbill** [comment]
Are you talking this extension: https://marketplace.visualstudio.com/items?itemName=hzwuxinhan.goTo ?

**Comment by sandy081** [comment]
Can you please elaborate about where are you trying to use this Goto link functionality and if this is being contributed by an extension?

**Comment by bilalhashmi1** [comment]
Thank you for your response, I am using "Laravel goto view" extension this extension provides me goto link functionality in Laravel blade. Sometimes this I am unable to use this functionality and when I restart visual studio code then it works well.

**Comment by sandy081** [comment]
Please file issue against the extension.
