### ISSUE TITLE
Appear folding button at the wrong place in python editing

### ISSUE THREAD

**Issue by 1298345095** [microsoft/vscode#85656]
appear folding button at the`<head>`and the`</html>` line

Issue` Type: <b>Bug</b>

```
for chapter_info in chapter_info_list:
		fb.write('''<html xmlns="http://www.w3.org/1999/xhtml" lang="zh">
	<head><meta charset="UTF-8"/>
		<title>%s</title>
	</head>
	<body>
	<h3>%s</h3>
<pre>\n    %s</pre>
</body>
</html>''' %(chapter_title,chapter_title,chapter_content))
		fb.close()
		print(chapter_url)
```

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (4.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.40.2
python|ms-|2019.11.50794
csharp|ms-|1.21.8

</details>

**Comment by 1298345095** [comment]
fb.write('''<html xmlns="http://www.w3.org/1999/xhtml" lang="zh">
	<head><meta charset="UTF-8"/>
		<title>%s</title>
	</head>
	<body>
	<h3>%s</h3>
<pre>\n    %s</pre>
</body>
</html>''' %(chapter_title,chapter_title,chapter_content))
		fb.close()
		print(chapter_url)

**Comment by octref** [comment]
You should open an issue for the Python extension you are using.
