### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by luofeng457** [microsoft/vscode#85658]
win10 system has a white gap on the top of the fullscreen window.

**Comment by awsumbill** [comment]
This doesn't happen to me, can you please provide a screenshot?

**Comment by gjsjohnmurray** [comment]
Also look at #85655 and close yours if it is a duplicate.

**Comment by IllusionMH** [comment]
@luofeng457 is it Full screen (<kbd>F1</kbd> or same result for Zen mode) or just maximized window where you see menu, window control buttons (Minimize, Restore, Close)?

Do you have scaling enabled in Windows Settings > System > Display ?

**Comment by awsumbill** [comment]
This is a duplicate #85655

**Comment by luofeng457** [comment]
> @luofeng457 This doesn't happen to me, can you please provide a screenshot?

Thanks! The problem didn't reproduce after I restart my computer.

**Comment by luofeng457** [comment]
> @luofeng457 is it Full screen (F1 or same result for Zen mode) or just maximized window where you see menu, window control buttons (Minimize, Restore, Close)?
> 
> Do you have scaling enabled in Windows Settings > System > Display ?

Thanks! Now It seems norma After l restart my computer.
