### ISSUE TITLE
Find newline with regex does not highlight all matches

### ISSUE THREAD

**Issue by zhangxiubo** [Microsoft/vscode#8565]
- VSCode Version: 1.3.0-insider
- OS Version: WIndows 7

Steps to Reproduce:

1. Create a new buffer;
2. Type three lines of text;
3. Open the find dialogue (Ctrl + +F) with regex enabled (Alt + R);
4. Search for \n.

Only the first matched newline character gets highlighted. Finding ordinary characters, in contrast, will highlight all the matches.

**Comment by bpasero** [comment]
I think this is caused by the editor find widget jumping into the "find in selection" as soon as you search for \n

**Comment by zhangxiubo** [comment]
I can see it works as intended now. Thanks!
