### ISSUE TITLE
Multiprocessing not working in VS code, computer hangs indefinitely. 

### ISSUE THREAD

**Issue by chrjakob** [microsoft/vscode#85665]
I know this issue has been raised before, however I cannot find a working solution. 

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

This code works:

```
def if_prime(x):
    if x <= 1:
        return 0
    elif x <= 3:
        return x
    elif x % 2 == 0 or x % 3 == 0:
        return 0
    i = 5
    while i**2 <= x:
        if x % i == 0 or x % (i + 2) == 0:
            return 0
        i += 6
    return x

answer = 0

for i in range(1000000):
    answer += if_prime(i)
    #print(answer)
```
When adding multiprocessing, the computer hangs:

```
from multiprocessing import Pool

if __name__ == '__main__':
    with Pool(2) as p:
        answer = sum(p.map(if_prime, list(range(1000000))))
        #print(answer)
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by sandy081** [comment]
What do you mean by `When adding multiprocessing, the computer hangs:` ? It hangs after running this code? If so how are you running this code?
