### ISSUE TITLE
Failed to Execute Git

### ISSUE THREAD

**Issue by bhatiasagar999** [microsoft/vscode#85666]
Issue Type: <b>Bug</b>

Cannot perform any Git operations , basically I receive an error saying Failed to Execute Git when I try using Git 

VS Code version: Code 1.40.2 
OS version: Windows_NT x64 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.1
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|10.2.0
prettier-vscode|esb|3.10.0
forcecode|Joh|3.19.2
salesforcedx-vscode|sal|47.6.0
salesforcedx-vscode-apex|sal|47.6.0
salesforcedx-vscode-apex-debugger|sal|47.6.0
salesforcedx-vscode-apex-replay-debugger|sal|47.6.0
salesforcedx-vscode-core|sal|47.6.0
salesforcedx-vscode-lightning|sal|47.6.0
salesforcedx-vscode-lwc|sal|47.6.0
salesforcedx-vscode-visualforce|sal|47.6.0
sfdx-package-xml-generator|Vig|1.2.1
vscode-open-in-github|ziy|1.3.6

</details>

![image](https://user-images.githubusercontent.com/58249241/69703413-5834d980-1117-11ea-8461-0624a795d260.png)

**Comment by bhatiasagar999** [comment]
I have already tried setting up the Global user name and email , also reinstalled Git and VS Code . nothing working for me

**Comment by joaomoreno** [comment]
If you click `Open Git Log`, what's in the log?

**Comment by bhatiasagar999** [comment]
git show HEAD:src/profiles/LEX G360 District Manager %2B GTW.profile
fatal: unable to access 'https://ecolabinstitutional.visualstudio.com/Mobile%20Sales%20and%20Service/_git/Salesforce_Institutional/': error setting certificate verify locations:
  CAfile: C:/GitHub/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none

**Comment by bhatiasagar999** [comment]
git show HEAD:src/profiles/LEX G360 District Manager %2B GTW.profile
fatal: unable to access 'https://eco/Mobile/_git/Salesforce_Institutional/': error setting certificate verify locations:
  CAfile: C:/GitHub/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none

**Comment by joaomoreno** [comment]
Please fix your git configuration. Based on the git output there's a certificate issue, unrelated to VS Code.

**Comment by bhatiasagar999** [comment]
I get both errors sometime I get the Failed to Execute sometime this certificate issue . Not sure whats really wrong in both cases and how to fix them
