### ISSUE TITLE
Intellisense: console.log() autosuggest a function or variable

### ISSUE THREAD

**Issue by KarmaBlackshaw** [microsoft/vscode#85669]
Say I have a long function name which returns something.

`
const long_function_name_in_javascript = () => {}
`

If I write `console.log()` and start typing inside the parenthesis, it should at least suggest functions or any variables present in the current file.

**Comment by rajatrt** [comment]
Hi @KarmaBlackshaw ,
the autosuggestion is working fine for me.
I am using the below version.
Version: 1.41.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

<img width="1057" alt="long_function" src="https://user-images.githubusercontent.com/11995080/69728499-8a136380-114a-11ea-82a5-6a6894f3be24.png">

Which version you are using?

**Comment by mjbvz** [comment]
Closing as more info needed to investigate. Most likely, just set `"editor.suggest.snippetsPreventQuickSuggestions": false`

**Comment by KarmaBlackshaw** [comment]
Thank you guys! I guess the snippets I made disabled the quick suggestions. @mjbvz, the setting `snippetsPreventQuickSuggestions` to `false` is indeed correct.
