### ISSUE TITLE
VSC performance and feature issues when multi langage usage (ReactJS/Golang)

### ISSUE THREAD

**Issue by ezwiebel** [Microsoft/vscode#8566]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 14.04 LTS

Hello,

I'm working on an project with ReactJS/Redux and Golang respectively as frontend and backend technologies.

I started to work on the frontend part and managed to install and use `jsx` extension for a while.
Then I started to work on the backend and successfully installed and use `Go` extension.

This is when I went back to frontend that problems started. None of the previously working feature (completion, navigation, error highlighting, etc..) of the `jsx` would work anymore (Go extension still working fine though).
Moreover, when I try to force a completion for example, I just have a `Loading...` message appearing above the code and a process is started that burns 1.3GB of memory and a whole CPU charge. I need to manually kill the process, it won't kill itself on VSC quit.

`settings.json`

```
{
    //GO
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.goroot": "/opt/go",
    "go.gopath": "/home/emile/dev/RMTool/go",
    "go.gocodeAutoBuild": false,

    //React / JS
    "javascript.validate.enable": false,
    "editor.tabSize": 2,
    "files.trimTrailingWhitespace": true,
    // Migrated from previous "File | Auto Save" setting:
    "files.autoSave": "onFocusChange"
}
```

`.eslintrc`
```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "browser": true,
    "mocha": true,
    "node": true
  },
  "rules": {
    "react/jsx-uses-react": 1,
    "react/prop-types": 0,
    "no-console": 0,
    "react/jsx-no-bind": 0,
    "react/prefer-stateless-function": 0,
    "comma-dangle": 0,
    "no-use-before-define": 0,
    "consistent-return": 0,
    "func-names": 0,
    "no-unused-expressions": 0,
    "id-length": 0,
    "no-multi-spaces": 0,
    "no-mixed-spaces-and-tabs": 2,
    "no-unused-vars": [1, {"vars": "all", "args": "none"}]
  },
  "plugins": [
    "react"
  ]
}
```

Steps to Reproduce:

1. Set a project with react and go in different folders
2. Install extensions and try out

Cheers

**Comment by bpasero** [comment]
@dbaeumer please advise if maybe this one needs multiple owners or someone else.

**Comment by dbaeumer** [comment]
@ezwiebel can you provide me with the full command line of the process that starts eating up the memory and CPU. This will help to track this down. And is your project public. Then I could clone it and have a look.

**Comment by ezwiebel** [comment]
Thanks @dbaeumer for your quick answer!
Unfortunately the project is not public but I set up [another project that reproduces the problem](https://github.com/ezwiebel/VSCode_issue)

All instructions to reproduce are in the [README.md](https://github.com/ezwiebel/VSCode_issue#README.md)

Here is the full command line of the problematic process: 

`/usr/share/code/code /usr/share/code/resources/app/extensions/typescript/out/utils/electronForkStart /usr/share/code/resources/app/extensions/typescript/server/typescript/lib/tsserver.js`

Looks like it comes from a typescript extension...

**Comment by dbaeumer** [comment]
Yes, it does come from the tsserver. Before you spent the time creating another project that reproduces the problem (which I highly appreciate) lets do the following:

In VS Code enable the tsserver trace setting by adding the following to the settings.json: `"typescript.tsserver.trace": "messages"`. Then start VS Code open a TS/JS/JSX file open the Output view and switch to the TypeScript channel. Could you provide the trace here. That might help to understand what is happening.

**Comment by ezwiebel** [comment]
Hello @dbaeumer , sorry for the late reply, I was off for the weekend.
The project to reproduce was already usable at the time of my last post, [here](https://github.com/ezwiebel/VSCode_issue)
Not to hard to build though.

Anyway, here is the trace you were asking for:
```
Sending request: open (0). Response expected: no. Current queue length: 0
Sending request: quickinfo (1). Response expected: yes. Current queue length: 0
TypeScript Service: tried to cancel request with sequence number 1. But request got already delivered.
TypeScript Service: canceled request with sequence number 2
TypeScript Service: canceled request with sequence number 4
TypeScript Service: canceled request with sequence number 5
TypeScript Service: canceled request with sequence number 8
TypeScript Service: canceled request with sequence number 9
....... AND GOING.......
```

**Comment by dbaeumer** [comment]
@ezwiebel thanks. Looks like the tsserver 'dies' already on the first quickInfo request.

**Comment by dbaeumer** [comment]
@ezwiebel cloned and was able to reproduce. The problem is the jsonfig.json setup. It currently doesn't support patterns which in your setup doesn't exclude the node_modules folder and as a result putting two much preasure on the tsserver. You can either move the jsconfig.json to the frontend folder (there is no JS in the backend) or change the jsonfig.json to:

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "target": "ES6",
    "module": "system"

  },
  "exclude": [
    "frontend/node_modules"
  ]
}
```

I will still move the issue to the TS team since the tsserver didn't warn me about problem with that setup.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9504
