### ISSUE TITLE
Starting client failed. Error: listen EACCES permission denied 

### ISSUE THREAD

**Issue by kenkangxgwe** [microsoft/vscode#85663]
Issue Type: <b>Bug</b>

1. Install [lsp-wl extension](https://marketplace.visualstudio.com/items?itemName=lsp-wl.lsp-wl-client). I am the author of the extension, I claim that I didn't upgrade it recently and it worked yesterday. You don't even need to install the server.
2. Open a file (`.wl`) that triggers lsp-wl extension.
3. In the __Output__ tab, select Wolfram Language Server. It reads

```
[Error - PM 10:53:31] Starting client failed
Error: listen EACCES: permission denied 127.0.0.1:6536
	at Server.setupListenHandle [as _listen2] (net.js:1209:19)
	at listenInCluster (net.js:1274:12)
	at doListen (net.js:1413:7)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.35.1
ccls|ccl|0.1.28
cquery|cqu|0.1.10
vscode-eslint|dba|1.9.1
tslint|eg2|1.0.44
wolfram-language|fli|0.1.0
base16-generator|gol|1.11.0
lsp-wl-client|lsp|0.1.5
vscode-elixir|mjm|1.1.0
python|ms-|2019.11.50794
cmake-tools|ms-|1.2.2
cpptools|ms-|0.26.1
vsliveshare|ms-|1.0.1293
lsp-inspector-webview|oct|0.0.2
vscode-elixir-formatter|sam|0.2.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-wl|shi|1.7.3
prettify-symbols-mode|sie|0.4.2
org-mode|too|0.5.0
cmake|twx|0.0.17
vscode-icons|vsc|9.6.0
vim|vsc|1.11.3
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Guessing if it is some how related to the recent fix you guys have done, hence assigning to you.

**Comment by dbaeumer** [comment]
@kenkangxgwe I looked at your code and you are reading the port from a config file. If the port is taken (which can happen easily by other processes) you get a permission denied. I think you need to probe for an open port and use that one. 

Does this also occur when you configure a different port which you know is not taken.

**Comment by kenkangxgwe** [comment]
In previous versions , the extension would simply throw “address in use”
error. This is the first time that I saw this massage. I have also tried
other ports. Can you reproduce it on your side?

**Comment by dbaeumer** [comment]
Actually I tried this but all I got is:

```
[Error - 2:11:32 PM] Starting client failed
Launching server using runtime wolfram failed.
```

Can you provide me with a docker container / file I can use that contains a fully functional setup?

**Comment by kenkangxgwe** [comment]
Thanks for the confirmation. I reinstalled VSCode and now it works.
