### ISSUE TITLE
Cannot import module that resides in "tests" folder of the project

### ISSUE THREAD

**Issue by xSupasx** [microsoft/vscode#85660]
Issue Type: <b>Bug</b>

when project has "tests" folder in the folder structure and there are modules that reside within it (python modules) then modules cannot be imported. If the name of the folder is changed everything works as expected. 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (2.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
cucumberautocomplete|ale|2.14.1
scratchpads|bue|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.9
json-tools|eri|1.0.2
code-runner|for|0.9.15
gc-excelviewer|Gra|2.1.32
path-autocomplete|ion|1.13.3
search-node-modules|jas|1.3.0
vscode-codemetrics|kis|1.23.0
node-module-intellisense|lei|1.5.0
codeacejumper|luc|2.1.7
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
vscode-azurefunctions|ms-|0.20.0
python|ms-|2019.11.50794
remote-wsl|ms-|0.40.3
azure-account|ms-|0.8.7
csharp|ms-|1.21.8
mono-debug|ms-|0.15.8
powershell|ms-|2019.11.0
vsliveshare|ms-|1.0.1293
vsliveshare-audio|ms-|0.1.80
debugger-for-chrome|msj|4.12.1
autodocstring|njp|0.4.0
vscode-for-node-js-development-pack|nod|2.0.1
vscode-jest|Ort|3.0.2
code-settings-sync|Sha|3.4.3
ayu|tea|0.18.0
snippet-creator|vin|1.1.0
vscodeintellicode|Vis|1.2.0
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by xSupasx** [comment]
I've discovered that it is a problem with this in particular:
C:\\Users\\aslupek\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\tests\\__init__.py - this is what gets assigned when I debug importing only "tests" module. My python version is: 3.7.4

**Comment by sandy081** [comment]
Please file issue against Python extension.

**Comment by xSupasx** [comment]
will do - thanks
