### ISSUE TITLE
Separate "Organize imports" into "Sort imports", "Merge imports" and "Remove unused imports".

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode#85661]
I think "Organize imports" should be separated into "Sort imports", "Merge imports" and "Remove unused imports", so that one can choose which one to enable.

**Comment by charrondev** [comment]
Very often I just want to remove things, not reformat the entire list! Re-ordered imports are just noise in pull requests!

**Comment by ravshansbox** [comment]
Thanks.

**Comment by charrondev** [comment]
@mjbvz Not sure if this is really an extension candidate, when the functionality is already built-in to VSCode!

Knowing which imports are unused is a relatively expensive operation that the Typescript language process already seems to know about! Why would an we want a separate plugin to do this?
