### ISSUE TITLE
Console does not load

### ISSUE THREAD

**Issue by jlgarridol** [microsoft/vscode#85670]
Issue Type: <b>Bug</b>

When you start the console the window appears but there is only one box with no prompt or way to type in it. It also happens with the debug console

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.3.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3229)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.69GB (4.94GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
auto-close-tag|for|0.5.6
python|ms-|2019.11.50794
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
markdown-all-in-one|yzh|2.5.1
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by jlgarridol** [comment]
![imagen](https://user-images.githubusercontent.com/14005926/69709283-68d85600-10fd-11ea-873d-abe5828bd28c.png)

**Comment by Tyriar** [comment]
Could you share your settings.json file and [enable trace logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging) and see what the logs say?

**Comment by jlgarridol** [comment]
My settings.json
```json
{
    "workbench.iconTheme": "material-icon-theme",
    "material-icon-theme.folders.color": "#26a69a",
    "workbench.colorTheme": "Solarized Dark High Contrast",
    "terminal.integrated.fontFamily": "Menlo for Powerline",
    "files.autoSave": "afterDelay",
    "terminal.integrated.inheritEnv": false,
    "terminal.integrated.shell.linux": "/bin/zsh",
    "window.zoomLevel": -1,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false
}
```

Log: when open terminal 

> [2019-11-28 10:28:58.131] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.toggleTerminal
[2019-11-28 10:28:58.132] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"workbench.action.terminal.toggleTerminal","from":"keybinding"}
[2019-11-28 10:28:58.132] [renderer1] [trace] terminalInstance#ctor (id: 5) {}
[2019-11-28 10:28:58.176] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/jlgarridol/.config/Code/logs/20191128T102328/renderer1.log
[2019-11-28 10:28:58.193] [renderer1] [error] A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'
[2019-11-28 10:28:58.235] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {workbench.panel.hidden => false}), delete(Set(0) {})
[2019-11-28 10:28:58.235] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2019-11-28 10:28:58.235] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('workbench.panel.hidden','false')
[2019-11-28 10:28:58.236] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION

**Comment by Tyriar** [comment]
> [2019-11-28 10:28:58.193] [renderer1] [error] A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'

You're seeing this issue: https://github.com/microsoft/vscode/issues/76542, remove the inheritEnv settings to fix for now.

/duplicate

**Comment by jlgarridol** [comment]
Thanks
