### ISSUE TITLE
Current open file relative path variable

### ISSUE THREAD

**Issue by mani47** [Microsoft/vscode#8567]
- VSCode Version: 1.2.1
- OS Version: Mac OS X 10.11.5 ( OS X El Capitan )

Steps to Reproduce:

I have this line in my launch json for testing just current open file:
````
{
            "name": "Test - active test file only",

            "type": "Ruby",

            "request": "launch",

            "cwd": "${workspaceRoot}",

            "program": "${workspaceRoot}/bin/rake",

            "args": [
                "test",
                "${fileBasename}" or "${file}"
            ]
        }


````

rake test needs relative path of the file. ${file} gives complete absolute path and ${fileBasename} just gives the name of the file. is there any variable to get relative path of the current open file? I want to run this script:

rake test test/integration/my_test.rb

**Comment by isidorn** [comment]
The idea with variable path substition is that they always substitue for an absolute path. 
If you need a relative path just do not use those variables, and istead put 'test/integration/my_test.rb' as args.

**Comment by mani47** [comment]
idea was being able to run open file tests just like all other IDEs, this way I have to constantly edit launch.json when working on tests.

**Comment by isidorn** [comment]
Currently we do not support this and it is a valid feature request -> reopening

**Comment by adstep** [comment]
I believe this is the same as my issue https://github.com/Microsoft/vscode/issues/7000.

**Comment by dbaeumer** [comment]
@adstep thanks. Indeed a dup of #7000
