### ISSUE TITLE
Remove ICommandAction#iconClassName

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#85673]
This got added via https://github.com/microsoft/vscode/commit/c9f9081e2fd9846c6f24d5ee782dfa7373ee32c2 and is a no, no because it a) weirdly competes with `iconLocation` give consumer headaches what to use and b) won't work for the Mac Touch Bar (which is the reason this originally has been added). In essence this must go again and we should use uri until it comes to rendering

**Comment by jrieken** [comment]
fyi - with https://github.com/microsoft/vscode/pull/85635 we are adding support to have uris like this `vscode-icon://codicon/XYZ` That means codicon can then be used everywhere as if it's uris

**Comment by jrieken** [comment]
Adding @eamodio since the removal could be a side effect of #85635

**Comment by jrieken** [comment]
I am preparing a change for https://github.com/microsoft/vscode/issues/84695 and I am cleaning this up along the way. A command icon is now defined like so: `icon?: { dark?: URI; light?: URI; } | ThemeIcon;`, a sample for codicons is `icon: { id: "codicon.go-to-file" }`

**Comment by misolori** [comment]
@jrieken thanks for cleaning this up (and sorry for introducing this the wrong way)!
