### ISSUE TITLE
Notification toast when there are no notifications

### ISSUE THREAD

**Issue by mfsbo** [microsoft/vscode#85679]
- VSCode Version: 1.40.2
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. View All notifications so that there are no notifications.
2. Click on the notifications icon and you will see a narrow toast for notifications and text is out.
![image](https://user-images.githubusercontent.com/50488401/69716720-865bee80-1102-11ea-86ea-d230706da5d3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by NizamLZ** [comment]
@mfsbo It works as expected:

![image](https://user-images.githubusercontent.com/9017268/69729169-e1660380-114b-11ea-9e49-7783f30b2331.png)

Some notification might have disturbed it.

**Comment by mfsbo** [comment]
Thanks, Closed it restarted and installed some extensions to see if notifications reproduces it but cannot reproduce it.
