### ISSUE TITLE
python extension broke in vscode 1.40.2

### ISSUE THREAD

**Issue by chaosreload** [microsoft/vscode#85678]
- VSCode Version: 1.40.2
- OS Version: macos 1.12.6

Steps to Reproduce:

1. install python extension and enable it
2. watch the View -> Output panel

The python language server restart for 5 times then report "it crashed 5 times in 3 minutes, it will not restart".

This is the output:

[Info  - 6:08:25 PM] Connection to server got closed. Server will restart.
[Info  - 6:08:26 PM] Analysis cache path: /Users/weichaoluo/Library/Caches/Microsoft/Python Language Server
[Info  - 6:08:26 PM] Microsoft Python Language Server version 0.4.114.0
[Info  - 6:08:26 PM] Workspace root: /Users/weichaoluo/work/gitlab_repo/mgcoop
[Info  - 6:08:26 PM] GetCurrentSearchPaths /usr/local/bin/python 
[Info  - 6:08:26 PM] Interpreter search paths:
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
[Info  - 6:08:26 PM]     /Users/weichaoluo/Library/Python/2.7/lib/python/site-packages
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/bandcamp_downloader-0.0.8.post12-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/chardet-3.0.4-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/mock-2.0.0-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/unicode_slugify-0.1.3-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/mutagen-1.40.0-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/demjson-2.2.4-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/pbr-4.0.1-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/lib/python2.7/site-packages/Unidecode-1.0.22-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bandcamp_downloader-0.0.8.post12-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chardet-3.0.4-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mock-2.0.0-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/unicode_slugify-0.1.3-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mutagen-1.40.0-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/demjson-2.2.4-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pbr-4.0.1-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg
[Info  - 6:08:26 PM]     /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Unidecode-1.0.22-py2.7.egg
[Info  - 6:08:26 PM] User search paths:
[Info  - 6:08:31 PM] Initializing for /usr/local/bin/python
[Info  - 6:08:33 PM] Analysis caching mode: None.
dyld: lazy symbol binding failed: Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Users/weichaoluo/.vscode/extensions/ms-python.python-2019.11.50794/languageServer.0.4.114/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Users/weichaoluo/.vscode/extensions/ms-python.python-2019.11.50794/languageServer.0.4.114/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

------
**UPDATE 20191127**: I tried to open a workbench including fewer files, and it did not crash. Is it a problem about performance?

Does this issue occur when all extensions are disabled?: No

**Comment by chaosreload** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Javascript/Typescript Language Service Crashes During Git Diff (#85234)](https://www.github.com/microsoft/vscode/issues/85234)

I confirmed it should be a new issue.

**Comment by sandy081** [comment]
Please file the issue against the python extension.
