### ISSUE TITLE
Greek characters

### ISSUE THREAD

**Issue by JarosT55** [microsoft/vscode#85672]
Issue Type: <b>Bug</b>

I use Greek characters in the Python code. Everything is OK, but
Explorer windows shows them like Chinese ones.

𝜃  += 𝜃i

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
What do you mean by Explorer Windows? Can you please provide a screenshot?

**Comment by JarosT55** [comment]
Explorer, it is panel available via <View><Explorer>
To check the problem copy :
𝜃 += 𝜃i
into basic python script and check <Outline> panel.

**Comment by JarosT55** [comment]
Hi Git,
The issue seems to be OK now,
Just keep consistent encoding between VSC editor and the shell of OS.
UTF-8 is the natural choice.
![testGreek](https://user-images.githubusercontent.com/23690439/69831985-f80d7700-127f-11ea-8f94-40bca549265a.png)
Regards
MichaelT
