### ISSUE TITLE
Automatic conversion of Windows to WSL paths on integrated terminal

### ISSUE THREAD

**Issue by fnery** [microsoft/vscode#85676]
Suppose one has the following path in the clipboard: `C:\Users\Name`

My suggestion is that upon pasting (ctrl+v on Windows) the above path in the VS Code integrated terminal (running WSL bash) it would be automatically converted to a WSL path, in this case `/mnt/c/Users/Name`. I found this implemented in [ConEmu](https://conemu.github.io/) and I find it quite useful, hence the suggestion. Note I am using VS Code installed on Windows 10 and the Remote-WSL extension (see below).

Any thoughts?

**VS Code version:**
```
$ code --version
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64
```

**Extensions:**
```
cmd> code --list-extensions --show-versions
CoenraadS.bracket-pair-colorizer-2@0.0.28
dracula-theme.theme-dracula@2.18.1
Gimly81.matlab@1.4.0
ms-vscode-remote.remote-ssh@0.47.2
ms-vscode-remote.remote-ssh-edit@0.47.2
ms-vscode-remote.remote-ssh-explorer@0.47.2
ms-vscode-remote.remote-wsl@0.40.3
nemesv.copy-file-name@1.2.0
oderwat.indent-rainbow@7.4.0
sdras.night-owl@1.1.3
Shan.code-settings-sync@3.4.3
shardulm94.trailing-spaces@0.3.1
slevesque.vscode-autohotkey@0.2.2
streetsidesoftware.code-spell-checker@1.7.20
tomoki1207.vscode-input-sequence@0.2.0
wmaurer.change-case@1.0.0
wmaurer.vscode-jumpy@0.3.1
```

Apologies if this has been suggested elsewhere (I searched for `is:issue is:open label:feature-request wsl path`). Possibly related are https://github.com/microsoft/vscode/issues/79881 and https://github.com/microsoft/vscode/issues/78751.

**Comment by JSousa-UoL** [comment]
This is a relevant issue for me too, because it's a hassle for me every time I set hardcoded paths in my scripts to test and develop them. The purpose is to check if the script works for both Windows and Linux systems.

**Comment by Tyriar** [comment]
I think messing with the clipboard contents would be unexpected generally, you should be able to just put `wslpath ` before pasting (wrapped in quotes if there are spaces) and it would do what you want.

<img width="230" alt="Screen Shot 2019-11-28 at 9 43 56 AM" src="https://user-images.githubusercontent.com/2193314/69825298-9d164a00-11c3-11ea-85f0-e488b540bc4f.png">
