### ISSUE TITLE
indent guide line with depth variation

### ISSUE THREAD

**Issue by kita32** [microsoft/vscode#85677]
Issue Type: <b>Feature Request</b>

use multi-color indent guide line to  represent  various  indent depth. 

```
| (black)
|
|    | (black)
|    |
|    |    | (grey)
|    |    |    | (grey)
|    |    |    |    |(grey)      //.. and so on
```

why?   current guide line looks bad on deep-indent,   with show no direct structure information.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by s-surineni** [comment]
I like the idea. I want to work on it. Can you please tell me where to find the related code
