### ISSUE TITLE
Typescript type definition not working with library in an Angular Workspace generated with `--create-application false`

### ISSUE THREAD

**Issue by Dremor** [microsoft/vscode#85681]
- VSCode Version: 1.40.2, 1.41.0-insider
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Create an Angular 8.2 app with `--create-application false` (`ng new XrmAngular --create-application false`)
2. Create a library project in this workspace (`cd XrmAngular  && ng g lib XrmAngularLib`)
3. Add a type declaration (ex: @types/xrm) package, and add "xrm" to the library `tsconfig.lib.json`  file type array. (`cd projects/xrm-angular-lib  && npm add @types/xrm`)
4. Try to use it in the library code, VS Code won't find the type.

Does this issue occur when all extensions are disabled?: Yes

Note : Code still build via command line, seems to be specific to VS Code.

**Comment by mjbvz** [comment]
Looks like `@types/xrm` declares globals (not a module), so I believe this is expected

In cases like this, you need to explicitly add a reference to `xrm` so that VS Code knows to use these globals. Adding a top level import such `import 'xrm';` is one approach.
