### ISSUE TITLE
launch: program ''does not exist

### ISSUE THREAD

**Issue by coucourou** [microsoft/vscode#85688]
- VSCode Version: 1.40.2
- OS Version: 18363.476

Steps to Reproduce:

1.do as the https://code.visualstudio.com/docs/cpp/config-mingw
2. launch: program 'C:\WINDOWS\systerm32\projects\helloworld.exe' does not exist.
launch.json:
`{

    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/helloworld.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/Mingw-w64/mingw64/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}`

tasks.json:
`{

    "version": "2.0.0",
    "tasks": [
      {
        "label": "build hello world",
        "type": "shell",
        "command": "g++",
        "args": ["-g", "-o", "helloworld", "helloworld.cpp"],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
  }`
c-cpp-properties.json:
`{

    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Mingw-w64/mingw64/bin/g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Please file against cpp extension. Thank you

**Comment by coucourou** [comment]
in fact, my Visual Studio also meets this problem. I reinstalled the vscode, vs, win10 and the situation did not change. But the C:\WINDOWS\systerm32\projects\helloworld.exe does exist.

**Comment by coucourou** [comment]
https://github.com/microsoft/vscode-cpptools
I only install C/C++ extension.
