### ISSUE TITLE
Buffer() deprecation warning when installing a vsix through the command line

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#85686]
I saw #67534 but I'm still getting the warning when installing a vsix from the terminal. I even tried the hello world extension sample from Microsoft and it also shows the same warning.

I'm on windows 10 and this is the vscode version:

Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by psclkhoury** [comment]
> /duplicate

@sandy081 duplicate for the one I referenced which says it is fixed and closed for comments. That’s why I made a new issue because it’s not fixed.

**Comment by sandy081** [comment]
There is another open hence marked duplicate.

**Comment by psclkhoury** [comment]
> There is another open hence marked duplicate.

@sandy081 well then at least link the duplicate issue!

**Comment by sandy081** [comment]
#82524
