### ISSUE TITLE
中文输入法拼音出现重叠&Chinese input method pinyin overlaps

### ISSUE THREAD

**Issue by phm622848** [microsoft/vscode#85680]
下载搜狗输入法,或者Mac原生中文输入法,输入中文时,拼音出现重叠
Download Sogou input method, or Mac native Chinese input method, pinyin overlaps when inputting Chinese
![image](https://user-images.githubusercontent.com/18509054/69717402-f68c6380-1146-11ea-8605-da53873d31ac.png)

**Comment by rebornix** [comment]
@phm622848 can you help confirm you can see the same issue with macOS native Chinese IME? I didn't see to reproduce it 

![image](https://user-images.githubusercontent.com/876920/72479669-010fc480-37aa-11ea-9fda-fcc89340a7be.png)
