### ISSUE TITLE
Ellipsis repository icon is spinning on refresh

### ISSUE THREAD

**Issue by Madsim** [microsoft/vscode#85685]
In the repository tab if a repository name is truncated with the ellipsis icon it will spin if clicked to refresh the repository :)

![ezgif-4-1123323ab4e9](https://user-images.githubusercontent.com/1423660/69720858-dc855d80-1113-11ea-9e2a-405f42ea6ef8.gif)

**Comment by s-surineni** [comment]
@Madsim Can you please tell which version are you using? I tried this on master build
ersion: 1.41.0
Commit: Unknown
Date: Unknown
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

and 

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

but could not reproduce the issue

**Comment by Madsim** [comment]
@s-surineni sure, sorry for not including this in the first place.
![about-vscode](https://user-images.githubusercontent.com/1423660/69746248-225a1a00-1144-11ea-8f1e-e1da4a3ce7ea.JPG)

**Comment by joaomoreno** [comment]
@misolori Already fixed this in `master`.

**Comment by svipas** [comment]
@joaomoreno Still happening in `1.41.0` on `Push` press in `Git` press.

**Comment by misolori** [comment]
Please see https://github.com/microsoft/vscode/issues/86423. There were some cases where the sync icon still got truncated, we now have set a min width on the icons so this doesn’t happen.
