### ISSUE TITLE
App crashes when trying to search the files or find function references

### ISSUE THREAD

**Issue by anteburazer** [microsoft/vscode#85687]
Issue Type: <b>Bug</b>

App crashes when right click on the folder, in order to search for some keyword, or right click on the function to find the references. When I reopen the app the opened tabs are not consistent with the previous session - tabs which were opened are not opened any more and ones which were previously closed are opened again.
Repro rate is not 100% but it happens quite often - almost every day, and today is the second time

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.44
prettier-vscode|esb|2.2.2
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.12.1
project-snippets|reb|0.5.0
java|red|0.34.0
vscode-lldb|vad|1.2.0
vscode-java-debug|vsc|0.18.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1

</details>

**Comment by gjsjohnmurray** [comment]
First suggestion is to update. The current release is 1.40.2.

**Comment by anteburazer** [comment]
New version works more reliably. Didn't notice that update is available because VS Code didn't prompt me to update. Also manual update didn't work.

So far v1.40.2 is more stable.
