### ISSUE TITLE
Fix notorious "the content of the file is newer" bug by adding an option to force overwrite by default

### ISSUE THREAD

**Issue by Bodup** [microsoft/vscode#85697]
- VSCode Version: 1.40.2
- OS Version: Windows 10 Pro Build 18363

This issue has been reported many times before. 

> Failed to save [filename]: The content of the file is newer. Please compare your version with the file contents.

See #7025 #48308 #46706 #77387 #48308 #84941. All of these issues were closed by vscodebot without being resolved.

Please, add an option to always force overwrite files without further notifications or popups. Having to go through this on each and every save is driving people nuts.

The issues listed above seem to indicate that the exact cause is still unknown, and consequently it still isn't fixed. But it would help if we could just make vscode remember to always overwrite dirty files so we can at least move on.

**Comment by MrEduar** [comment]
And they keep marking the topics as duplicates. They don't even give a solution. As @Bodup says you don't give solution in any of the issues opens. It's frustrating every time I'm doing the comparison and accepting results, I don't even use git in vs code.

**Comment by Bodup** [comment]
@MrEduar 46c696a adds an option to disable this check. See [this](https://github.com/microsoft/vscode/issues/66035#issuecomment-563156223) comment for more info.
