### ISSUE TITLE
Vertical Select with middle click is not working

### ISSUE THREAD

**Issue by yanniszark** [microsoft/vscode#85694]
Issue Type: <b>Bug</b>

In older versions of VSCode, I did vertical selection by clicking the middle button on the mouse and dragging.
It seems like this doesn't work anymore.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.0.0-36-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1960)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 1|
|Memory (System)|7.76GB (0.16GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.13.5
intellij-idea-keybindings|k--|0.2.37
python|ms-|2019.11.50794
vscode-yaml|red|0.6.1

</details>

**Comment by alexandrudima** [comment]
@yanniszark In some Linux distributions, middle clicking is reserved for moving windows. Did you perhaps change window compositors, or have upgraded your distribution since it last worked? Does middle clicking work for you in other applications?

**Comment by yanniszark** [comment]
@alexandrudima thanks for the response!
I'm working on Ubuntu 18.04.
This is the output of `lsb_release -a`:
```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

In Jetbrains Goland, vertical selection with middle click works as expected.

**Comment by alexandrudima** [comment]
Thanks for your quick reply.

VS Code is built with Electron, which is built with Chromium. Can you please try opening https://vscode-web-test-playground.azurewebsites.net (it might take a long time to load) in Chromium on the same machine? Does using the middle mouse button work there?

**Comment by yanniszark** [comment]
@alexandrudima I loaded the web page and the middle click vertical select still doesn't work.
When I try to select vertically, it just selects normally.
Also, middle click for paste works.

**Comment by alexandrudima** [comment]
> Also, middle click for paste works.

Aha! Thanks for the last extra detail to jog my memory. Indeed, the middle mouse button by default will paste the selection clipboard on Linux. You can disable that via `"editor.selectionClipboard": false`. Once the selection clipboard is disabled, the middle mouse button can be used for column selection.

**Comment by yanniszark** [comment]
@alexandrudima yes that was it! 
Thanks a lot for the help!
I can now go back to my favorite editor :smile:
