### ISSUE TITLE
Lock terminal input before startup commands are executed

### ISSUE THREAD

**Issue by keddad** [microsoft/vscode#85692]
When creating new integrated terminal, VS Code might insert come startup commands (starts python env, for example). Problem is, it is pretty slow, so you might start typing your command before VS Code is done, and it will just paste the command next to yours and execute it. Obviously, it fails. Here is an example, where "source" command was automatically pasted by VS Code:
![image](https://user-images.githubusercontent.com/34062895/69729334-080d4580-111e-11ea-9dc0-bcb418112978.png)
Not a critical issue, but still pretty nasty.

**Comment by Tyriar** [comment]
This is an extension issue, however we're discussing a way so that extensions don't need to do this in https://github.com/microsoft/vscode/issues/46696

/duplicate
