### ISSUE TITLE
Alt + Numpad keybindings insert characters into editor

### ISSUE THREAD

**Issue by doxxx** [microsoft/vscode#85699]
Issue Type: <b>Bug</b>

I have a keymap extension installed (IntelliJ IDEA Keybindings) that provides keybindings for Alt+Numpad1, etc. to toggle various sidebar views. However, using these keybindings is inserting various characters into the active editor, probably due to the Windows alt-code feature.

Is it possible to block these characters from being inserted when there is a matching keybinding?

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.70GB free)|
|Process Argv|C:/Users/gordon.tyler/dev/Synaptive/BuildTooling/PSModules|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.1.5
spellright|ban|3.0.48
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
systemd-unit-file|coo|1.0.5
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
vscode-pull-request-github|Git|0.13.0
gc-excelviewer|Gra|2.1.32
nsis|idl|3.20.4
vscode-react-typescript|inf|1.3.1
intellij-idea-keybindings|k--|0.2.37
rainbow-csv|mec|1.3.1
vscode-azureappservice|ms-|0.16.1
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
cpptools|ms-|0.26.1
csharp|ms-|1.21.8
Go|ms-|0.11.9
powershell-preview|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
typescript-hero|rbb|3.0.0
java|red|0.53.1
vscode-yaml|red|0.6.1
windbg-debug|rez|0.3.4
rust|rus|0.7.0
vscode-zipexplorer|sle|0.3.1
rewrap|stk|1.9.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-icons|vsc|9.6.0
jinja|who|0.0.8

</details>

**Comment by alexdima** [comment]
Minimal repro steps:

```
{
    "key": "alt+numpad4",
    "command": "actions.find",
    "when": "editorTextFocus"
}
```

Presing the key combination results in the find widget opening, but then the text `♦` is typed into the find widget.
