### ISSUE TITLE
Go code completion of functions/methods should include parameters

### ISSUE THREAD

**Issue by calmh** [Microsoft/vscode#857]
Hi & thanks for an awesome editor effort! There is one thing still bugging me when coming from Sublime that I think could be added, at least as an option. Currently Go code completion for methods and functions stops after the name is expanded:

```
strconv.AppendF<tab>  ->  strconv.AppendFloat
```

In sublime, the behaviour would have been:

```
strconv.AppendF<tab>  ->  strconv.AppendFloat(dst, f, fmt, prec, bitSize)
```

<img width="710" alt="screen shot 2015-12-01 at 12 44 56" src="https://cloud.githubusercontent.com/assets/125426/11499846/617e59be-9829-11e5-97dd-b8e0ddee6789.png">

with "dst" being selected for overwrite if I continued typing, and tab moving to the "f" parameter and so on. This is enormously helpful when you don't immediately remember the parameters or their order, as in this example that takes a lot of them... It's also great when you've just refactored out the method and are going to call it from the original site, as the parameters are probably already named correctly.

Currently the workarounds are to type the parens manually, then go back and hit Ctrl-Space for the completion result again. However, it cuts off long parameter lists:

<img width="1051" alt="screen shot 2015-12-01 at 12 40 05" src="https://cloud.githubusercontent.com/assets/125426/11499757/b27a5a08-9828-11e5-9882-ac17ef0d65e4.png">

The other option is Alt-F12 to preview the actual declaration, which works but is more work to parse than just getting the params immediately up front:

<img width="1053" alt="screen shot 2015-12-01 at 12 38 39" src="https://cloud.githubusercontent.com/assets/125426/11499720/7a120332-9828-11e5-9fc4-345e95ab38e8.png">

I could see that some prefer the current setup though, so this could be hidden behind a `go.completeWithParameters` option or something.

**Comment by lukehoban** [comment]
This issue was moved to Microsoft/vscode-go#135
