### ISSUE TITLE
After Changing Workspace Folders, Debug Settings Are Lost

### ISSUE THREAD

**Issue by AlencarGabriel** [microsoft/vscode#85709]
- VSCode Version: 1.40.2 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Tested using Workspace;
2. Click the launch creation gear icon: ![image](https://user-images.githubusercontent.com/10109480/69745354-d2b62700-1120-11ea-8442-f0cb6190ae0c.png)
3. A new tab will open for configuring Debug;
4. Change workspace folder by setting: 
```json
"folders": [
  {
    "name": "Example\\Folder",
    "path": "Example"
  }
]
```
5. Repeat step 2;
6. Will notice that the new tab will not open;
7. Same behavior occurs when debug setting is in workspace settings;
8. This directly impacts the debug extension I use, because every time I change folders and press F5 the list of debug enviroments appears again;
9. But if I reload VsCode, it works correctly. This issue has begun to occur in version 1.40

Obs.: I apologize for the writing because I'm from Brazil and I'm not fluent in English.

Follow gif demo:
![Evidence](https://user-images.githubusercontent.com/10109480/69746354-d9459e00-1122-11ea-9def-4ec2a6a844dc.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
This one functioned as desigen.
Launch configurations are stored in `${workspaceFolder}/.vscode/launch.json`.

If you change path of folder in workspace folder - you just change folder where VSCode will look for files (no moving files etc.). And VSCode won't have any configuration for debug if folder with new path don't have them.

**Comment by AlencarGabriel** [comment]
So I started using the release setting in Workspace settings after it
stopped working in the last monthly release.

All the folders I use in my workspace have the .vscode folder and the
configuration. So much so that if I reload VsCode it works, and the problem
only occurs with folder switching.

Em qua., 27 de nov. de 2019 às 14:53, Andrii Dieiev <
notifications@github.com> escreveu:

**Comment by IllusionMH** [comment]
@AlencarGabriel sorry. I posted comment and then checked recording with proper scaling to see that there were debug settings above paths (default scaling made them hard to read and recognize) and therefore removed it as incorrect.

**Comment by AlencarGabriel** [comment]
Ok, no problem lol.

Will this issue be considered as BUG then?

**Comment by isidorn** [comment]
Can you reproduce this issue with vscode insiders https://code.visualstudio.com/insiders/

**Comment by AlencarGabriel** [comment]
Good morning, 
I did the test using VsCode Insiders and reproduced the problem in the same way as already presented.

**Comment by isidorn** [comment]
Ok, I will look into this next milestone. Will provide more details then. Thanks

**Comment by isidorn** [comment]
This should be fixed with latest I believe.
Can you try with newest stable update that we will do in a couple of days and let us know if you still see the issue?

**Comment by AlencarGabriel** [comment]
Hey! I just installed the latest version and reading the release notes realized that there has been a change.

Tested as previously sent GIF, and the problem no longer occurs! Wonderful!

But I noticed that VsCode no longer considers debug (launch) configuration in Workspace settings :confused:
And in directories without write permission, it is not possible to debug as it will not be possible to create the launch.json file

How to proceed in this case?

**Comment by AlencarGabriel** [comment]
Doing more testing, I found a way to debug using directories without write permission.

I left the debugging settings in the workspace, but had to restart VsCode for it to recognize the setting.

**Comment by isidorn** [comment]
Ok, so the original issue is fixed great. Thus closoing this.
If there are more issue, can you please create a new one with short concise steps if possible. And feel free to ping me on it .Thanks

**Comment by AlencarGabriel** [comment]
I thank you for the problem solved. I was already suffering with him a few months ago kkk
