### ISSUE TITLE
Extensions are not npm_shrinkwrap'ed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8570]
We have extensions that have npm dependencies, like `css` or `json`. We don't shrink-wrap them which means each build from the *same* commit has a chance of being different.

@Microsoft/vscode

**Comment by bpasero** [comment]
The list of extensions with node_modules folder:
* typescript
* javascript
* php
* markdown
* json
* css
* configuration-editing

All of these need shrinkwrap and maybe a smoke test after that.

**Comment by bpasero** [comment]
Also, if you have recently moved code to a new extensions, please make sure you have removed the dependency of your extension from our package.json and shrinkwrap file.

**Comment by jrieken** [comment]
@bpasero Can you give pointers how to create the shrink_wrap file?

**Comment by bpasero** [comment]
What I typically do is:

* Make sure to have npm 3 installed
* Copy the package.json to a new, empty folder outside VSCode
* Delete all devDependencies from the package.json file
* Open a prompt in that new folder
* Run "npm install" and wait for it to finish without errors
* Run "npm shrinkwrap" and wait for it to finish without errors

**Comment by jrieken** [comment]
Since @aeschli is out, pls someone jump in. Also, we might need to run the OSS tool after this again 👻

**Comment by isidorn** [comment]
I can do it instead of @aeschli

**Comment by bpasero** [comment]
I updated the description with this important step:

* Copy the npm-shrinkwrap.json file into same location as the package.json file in the extension

**Comment by isidorn** [comment]
Seems to be done for all -> closing
