### ISSUE TITLE
folders with .d in name are being excluded

### ISSUE THREAD

**Issue by rrodrigues-ws** [microsoft/vscode#85701]
> Version: 1.40.2
> Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
> Date: 2019-11-25T14:54:40.719Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Linux x64 4.15.0-66-generic

Hi
If there is a folder with a name ending in .d, for instance, "test.d", the folder and its content are being excluded from the file explorer. In addition, all the files in this folder can not be accessed using the go-to file command.

steps to reproduce:
* mkdir test.d
* cd test.d/
* echo "test" > test.txt
* check if test.d and test.txt are not accessible

**Comment by sandy081** [comment]
Please check your settings and see if you have a rule configured in `files.exclude` setting that hides these files?

**Comment by rrodrigues-ws** [comment]
@sandy081 Thanks. That's the problem. In the default settings, it excludes *.d
I've removed that filter and now it works.
