### ISSUE TITLE
Escape key should not be shown if it does nothing.

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#85706]
The ESC key does nothing when you have just opened the search bar.

One thing ESC could do here is close the search bar. This will not be implemented, source: https://github.com/microsoft/vscode/issues/84724

Alternatively, the ESC key should not be shown. Because currently it is shown but it does nothing.

Motivation: buttons which are shown but do not do anything are an error and they cause physical stress when people press them harder because they think the computer is not physically responding.

---

Regarding the ESC key as shown on Touch Bar.

**Comment by roblourens** [comment]
Not sure what you mean "should not be shown", where is it?

Also, you are talking about the search viewlet in the side bar? I disagree that escape should close it. It's a large part of the UI, not a temporary dialog or overlay.

**Comment by fulldecent** [comment]
![IMG_5904](https://user-images.githubusercontent.com/382183/69767843-212ceb00-114c-11ea-8931-168afca067b1.jpg)

**Comment by roblourens** [comment]
Isn't it shown all the time? I don't think we have control over that, to be honest. But even if we do, I don't think we should show and hide it. It will almost always do something, and will often have some native behavior in the browser. So we can't really know when it will do something.
