### ISSUE TITLE
Snippet suggest skips perfect match

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode#85703]
When typing snippet names, the editor suggestions will often skip the top snippet even though it's a better match. I have `editor.snippetSuggestions` is set to `top`.

Here's me typing `ifer`, where it correctly suggests the `iferr` snippet as the top choice:

![Screen Shot 2019-11-27 at 11 20 04](https://user-images.githubusercontent.com/50314/69740869-181a2a80-1108-11ea-9066-81345b11af05.jpg)

Here's me typing `iferr`, where it correctly suggests the `iferr` snippet as the top choice (it's a perfect match, after all), but skips to another suggestion, so that hitting Enter will select the wrong one:

![Screen Shot 2019-11-27 at 11 19 58](https://user-images.githubusercontent.com/50314/69740870-181a2a80-1108-11ea-9755-68db8414c19b.jpg)

---

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|-psn_0_29498400|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
vscode-hie-server|ala|0.0.31
project-manager|ale|10.9.1
vscode-styled-jsx|bla|1.5.0
mermaid-markdown-syntax-highlighting|bpr|1.0.1
better-toml|bun|0.3.2
ndjson-colorizer|bus|1.0.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
scala|dal|0.0.5
whitespace-plus|dav|0.0.5
vscode-eslint|dba|1.9.1
devdocs|dei|0.1.4
vscode-new-file|dku|4.0.2
xml|Dot|2.5.0
scala-lsp|dra|0.2.3
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.10.0
sass-lint|gle|1.0.6
workspacesort|ici|1.5.8
Scala|itr|0.1.7
RelativePath|jak|1.4.0
reason-vscode|jar|1.7.2
language-haskell|jus|2.6.0
saltstack|kor|0.0.6
graphql-for-vscode|kum|1.15.3
chmod-command|lab|0.0.1
vscode-rufo|mbe|0.1.1
git-graph|mhu|1.18.0
gitignore|mic|1.0.1
ecdc|mit|1.3.0
vscode-docker|ms-|0.8.2
vscode-kubernetes-tools|ms-|1.0.7
cpptools|ms-|0.26.1
Go|ms-|0.11.9
omnisharp|ms-|0.3.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
vscode-sanddance|msr|1.2.12
rails-run-spec-vscode|nok|0.1.3
seti-icons|qin|0.1.3
ruby|reb|0.26.0
vscode-yaml|red|0.6.1
sass-indented|rob|1.5.1
rust|rus|0.7.0
vscode-workspace-switcher|sad|1.14.0
vscode-nginx|sha|0.6.0
shellcheck|tim|0.8.1
lorem-ipsum|Tyr|1.2.0
vscode-mermaid-preview|vst|1.2.0
jinja|who|0.0.8
vscode-ruby|win|0.26.0
change-case|wma|1.0.0
FilterText|yhi|0.0.15
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.3.0

(7 theme extensions excluded)

</details>

**Comment by atombender** [comment]
I just updated gopls (to `c1736c0f`), and it seems the problem has disappeared. Does this means gopls was interfering with snippets somehow?

**Comment by jrieken** [comment]
Yes - this is https://github.com/microsoft/vscode-go/issues/2739#issuecomment-557480991
