### ISSUE TITLE
visual problem

### ISSUE THREAD

**Issue by isesul** [microsoft/vscode#85704]
I don't know why it happens, but, this happens by leaving the vscode window in the background, and then I get the window in the foreground.

![bug_vscode](https://user-images.githubusercontent.com/3892768/69741411-c37fab00-1119-11ea-805e-32105c2d2dcc.jpg)

![bug_vscode_2](https://user-images.githubusercontent.com/3892768/69741448-d0040380-1119-11ea-8869-ad1b52113090.jpg)

**Comment by awsumbill** [comment]
There might be a problem with your hardware (monitor, GPU, etc.) does this happen with other programs? If it doesn't try reinstalling.

**Comment by isesul** [comment]
It may be a problem with my GPU, but it only happens in visual studio code, however, this has appeared since I updated the latest nvidia drivers.

**Comment by awsumbill** [comment]
Ok, here's my advice:

- Update VSCode
- Update drivers
- Update windows
- Reinstall Drivers
- Reinstall VSCode

If it still happens something freaky is happening.
Also, make sure you have the _right_ drivers, many have accidentally installed drivers for the wrong GPU and stuff like this happens.

**Comment by isesul** [comment]
I have reinstalled vscode and it is apparently fixed. But it is still strange. thanks and regards
