### ISSUE TITLE
Paste line moves cursor to start of current line rather than start of next line

### ISSUE THREAD

**Issue by Sharpiro** [microsoft/vscode#85712]
- VSCode Version: 1.40.2
- OS Version: Tested Windows 10 and Linux Fedora

Does this issue occur when all extensions are disabled?: Yes

Paste line moves cursor to start of current line rather than start of next line.  I setup both VS Code 1.40.2 and the current running version of stackblitz to illustrate that something has changed with line-pasting behavior that I couldn't find any mention of in the issues or release notes.

* I am using stackblitz as of 11/27/19 to show how an older version of vs code works.
* I also tested the vs code nightly, and this issue persists
* Tested with `code --disable-extensions`

Reproduction Steps:

* Start with a line of data
* Copy the entire line (not a selection)
* Press enter to move to the next line
* Paste the line
* See below for differences

Before:

![vscode_before](https://user-images.githubusercontent.com/9012043/69748733-012f0480-1117-11ea-872c-c47d38fd029f.png)

VS Code (1.40.2) after:
![vscode_after](https://user-images.githubusercontent.com/9012043/69748862-34719380-1117-11ea-9a01-265a66e7414e.png)

Stackblitz (old version of VS code) after
![stackblitz_after](https://user-images.githubusercontent.com/9012043/69748957-70a4f400-1117-11ea-9a38-62c81fad8b71.png)

I'm just trying to figure out if this is a bug or a feature, and what the reasons for the change were.

**Comment by alexdima** [comment]
This is a regression, caused by c7ec4738248ca355d0314b33192815a9015dee11
