### ISSUE TITLE
Smart Selection

### ISSUE THREAD

**Issue by shayneski99** [microsoft/vscode#85719]
Hey there!

I write a lot of copy in XML, and am trying to only select the text after "<textevent timeoffset="0" message=" and in between the quotation marks. Like this:

            <textevent timeoffset="320" message="We're going to be breaking that 20min up by doing 5, 4min efforts, separated by 2min of recovery."/>
            <textevent timeoffset="330" message="We'll also be changing up the cadence with each interval, and on-bike positions."/>

Is there an extension that allows me to do that? I am trying to copy and paste the content into Grammarly.

Thanks!

**Comment by whizsid** [comment]
Install my extension DOMQS https://marketplace.visualstudio.com/items?itemName=whizsid.domqs With this extension you can find your dom objects with a query selector

**Comment by shayneski99** [comment]
@whizsid thanks for your help! Would you mind running through what I'd need to do to only select the text between the quotations marks? What would the query be? Sorry, I have zero programming skills...

**Comment by whizsid** [comment]
Use regex instead.
1. Type Ctrl+F to find. Click `*` (regex) button on the find widget.
2. Paste this `<textevent\stimeoffset="(\d+)"\smessage="` into find box.
3. Click on your document.
4. Hit Ctrl+Shift+P
5. Type "Select all occurrences of Find Match" and click it.
6. Press the Right arrow key once.
7. Hold Shift key and press the "End" button.

**Comment by shayneski99** [comment]
@whizsid you're awesome thanks so much! I get this error though on Step 5: 
![image](https://user-images.githubusercontent.com/55494962/69754319-9e903580-1123-11ea-8f52-40b0bbc0d9be.png)

**Comment by whizsid** [comment]
Press right arrow key. ![Working Example](https://i.imgur.com/EkLujwV.gif)

**Comment by shayneski99** [comment]
Ah-ha! Got it! Sorry about that, I wasn't searching in the document itself *facepalm*

Thanks so much for all of your help! I really appreciate it.
