### ISSUE TITLE
CTRL + F and CTRL+ H mode switching issue

### ISSUE THREAD

**Issue by Antix-Development** [microsoft/vscode#85718]
- VSCode Version: 1.40.1
- OS Version: Windows 8.1 Professional 64-bit

When in find mode you can press CTRL + H to enter replace mode. When in replace mode you cannot press CTRL + F to exit replace mode and re-enter find mode. This one way behavior is mildly annoying and inconsistent.

Steps to Reproduce:

1. Press CTRL + F to enter find mode
2. Press CTRL + H to enter replace mode
3. Press CTRL + F which does not exit replace mode and re-enter find mode... instead it stays in replace mode but focuses the find input.

**Comment by Grommers00** [comment]
Would I be able to attempt this fix?

**Comment by rebornix** [comment]
Thanks for your feedback! This is as designed. Ctrl+F in Replace Mode moves focus into the Find Widget to allow you update the find query. It doesn't mean to quit replace mode.

**Comment by Antix-Development** [comment]
thanks, but it's behavior is not consistent as explained in my original statement.
