### ISSUE TITLE
launch.json schema says `cwd` is not allowed

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85713]
Issue Type: <b>Bug</b>

With an `extensionHost` type launch config, the schema says that `cwd` isn't allowed. But it is actually required to get good sourcemap support when debugging webpacked extensions.

![image](https://user-images.githubusercontent.com/641685/69749854-5ff57d80-1119-11ea-815f-ea662d018412.png)

/cc @isidorn 

VS Code version: Code - Insiders 1.41.0-insider (615732feae7228502eab60919d67837f7a625e7c, 2019-11-27T05:37:07.864Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.80GB free)|
|Process Argv|--enable-proposed-api eamodio.remotehub|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
The reason for that is that the node extension does not declare the `cwd` property as a configurationAttribute for the `extensionHost` type [here](https://github.com/Microsoft/vscode-node-debug2/blob/db4894e74eeca1b14a501b0a6eb085caadc9ec5a/package.json#L107)
Forwarding to @roblourens to add it if needed
fyi @connor4312

**Comment by roblourens** [comment]
I don't think it makes sense to set it for extensionHost debugging because it won't actually be the cwd of the EH process. This is just to get the default sourceMapPathOverrides to kick in, right? That should work without having to set this.

**Comment by eamodio** [comment]
I don't have any `sourceMapPathOverrides`, so setting `cwd` for me gets source maps to work.

**Comment by roblourens** [comment]
Yeah but the effect is just to get the default sourceMapPathOverrides to work. The debugger should handle this rather than require the user to, and it should actually be handling this correctly in vscode-pwa already.

**Comment by eamodio** [comment]
Ah, awesome 👍  -- will try that out soon.

**Comment by roblourens** [comment]
Going to close this because I don't plan to do anything with `cwd`. The new adapter takes a new strategy which should avoid some of the issues with this in the original adapter.
