### ISSUE TITLE
Extension api: process.env doesn't contain all of my .bash_profile environment variables

### ISSUE THREAD

**Issue by bmingles** [Microsoft/vscode#8572]
- VSCode Version: Code - Insiders 1.3.0-insider (a21c12346f388e51858c930875ca30968604c116, 2016-06-30T05:03:45.119Z)
- OS Version: Darwin x64 15.4.0

Steps to Reproduce:

My extension makes use of process.env to get values set in my .bash_profile. This has been working fine in VSCode 1.2 but appears to not be working in the 1.3 insider preview. My env variables set in .bash_profile are undefined on process.env in my extension.

**Comment by bmingles** [comment]
@joaomoreno I can get output from the [last command you posted](https://github.com/Microsoft/vscode/issues/7343#issuecomment-227876267) but am not sure what I am looking for. Latest insiders is still not loading env variables.

**Comment by joaomoreno** [comment]
@bmingles The output should be a raw JSON object. If you wrap `result.stdout` with `JSON.parse`, does it work?

**Comment by bmingles** [comment]
@joaomoreno I get an unexpected token error with JSON.parse

**Comment by joaomoreno** [comment]
What does the beginning of that string look like?

**Comment by bmingles** [comment]
My bash_profile echos a few lines of code with env values. Then the JSON string is presented. I'm assuming that the echo output is unexpected?

**Comment by bmingles** [comment]
Worth mentioning that I only echo if interactive shell:
`if [[ $- == *i* ]]
then
    echo 'foo'
    echo 'bar'
fi`

**Comment by bmingles** [comment]
Okay, looks like getting rid of all echo statements from my .bash_profile fixes this, but definitely would be preferred if this is not required.

**Comment by joaomoreno** [comment]
Thanks! Duplicate of #8434
