### ISSUE TITLE
Commit message should use to full editor

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode#85721]
Based on StackOverflow post about [editable commit message in vscode](https://stackoverflow.com/a/54139152/99834) the entire commit action should be changed in order to use a full editor. This will consolidate the user experience when using git from command line and configuring vscode as preferred editor.

There is no treason to have a different editing experiences for the two cases. In fact is a bit ironic that editing the commit message is much better when git calls vscode than using vscode directly. This enables spellchecking, linting, syntax checks like 50/72 rule and a ton of other features which are not available in the crippled input box of the default commit feature.

![vscode-git-commit-edit](https://user-images.githubusercontent.com/102495/69753322-39503a80-114b-11ea-8401-5242891ad8ec.png)

**Comment by joaomoreno** [comment]
> There is no treason to have a different editing experiences for the two cases.

Actually there is. Most people don't really want a full editor taking away workbench space. They just want to type a message and go with it.

Nevertheless, a full editor experience has its merits and can be tracked here: #30562
