### ISSUE TITLE
long search time for ridiculously huge workspaces

### ISSUE THREAD

**Issue by MRVDOG** [microsoft/vscode#85729]
At the company I work for, we have a single workspace for about 700+ websites, with 107k PHP files and 12m lines of code, when I do a search for something from the root directory it takes about 10-15 minutes to complete the search, thankfully most of the time what I'm after is found pretty early on, but still like 4-5 mins in. 

Version: 1.40.1
OS: Windows 10 (unsure on the build, as not reporting this from work)

**Comment by roblourens** [comment]
It might just be that slow, it might be Windows Defender getting in the way, or something else. See if the tips in https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory help
