### ISSUE TITLE
files.autoGuessEncoding is wrong with utf-8 chinese

### ISSUE THREAD

**Issue by MxDany** [microsoft/vscode#85738]
- VSCode Version:
版本: 1.40.2 (user setup)
提交: f359dd69833dd8800b54d458f6d37ab7c78df520
日期: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134
- OS Version:

Steps to Reproduce:

1. set "files.autoGuessEncoding": true, create a 'go' file, such as 'main.go'
2. open it in 'utf-8' encode
3. input the following code:
package main
import (
	"fmt"
)
func main() {
	fmt.Println("hello 世界")
}
![image](https://user-images.githubusercontent.com/20413031/69771554-2cbdf780-11c8-11ea-91dd-97a45bf503df.png)

4. close 'main.go' file
5. reopen it, it's encoding will be 'Windows 1252' Instead of 'utf-8'
![image](https://user-images.githubusercontent.com/20413031/69771579-47906c00-11c8-11ea-9da2-b842ffbb8747.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by MxDany** [comment]
oh, not all the 'utf-8' file with Chinese characters are garbled, you have to enter the same code as above,   and it will be occur.

**Comment by byyxx128** [comment]
#33720
#84503
#85480

**Comment by byyxx128** [comment]
https://github.com/microsoft/vscode/issues/33720#issuecomment-555975817
#84503
#85480

**Comment by byyxx128** [comment]
#33720
#84503
#85480
