### ISSUE TITLE
all the extentions are taking too much performace of the computer around 100% cpu

### ISSUE THREAD

**Issue by hello341** [microsoft/vscode#85737]
a week ago or so and the computer lags every time and I can not run any code on the browser or on the extensions, is it because I have too many Extensions? I have about 30-50 extensions, is that too many extensions downloaded? or is it a problem with one of my extensions. I know that the extensions are taking the most power BTW.

**Comment by whizsid** [comment]
Disable all extensions by `Disable all installed extensions` command and check the CPU load. If the issue resolved, disable extensions one by one and check the CPU load.

**Comment by hello341** [comment]
how to disable one by one?

**Comment by sandy081** [comment]
You can disable the extension from the extensions view.

**Comment by hello341** [comment]
I think I figured it out and it seems to be working well now
