### ISSUE TITLE
Enable tabs by default

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8573]
After talking to @egamma we both think that tabs should be enabled by default (currently they are not). Erich rationale is that tabs is a flag ship feature that resolves a serious adoption blocker and my reasoning is that the editor stacks model is harder to understand if tabs are disabled and more natural if tabs are enabled.

@Microsoft/vscode please speak up if someone has a valid reason why we should not do that.

**Comment by jrieken** [comment]
I don't like it, but I know how to configure the tool ;-). I just wonder what existing users that like no tabs (do those outside our team exist) thing of it?

**Comment by bgse** [comment]
Currently giving tabs a shot, but will probably stay with no-tabs, just works better for me.

I'd guess the majority is used to tabs from other editors, so probably sensible to enable it by default, fine with me as long as no-tabs doesn't disappear completely one day.
