### ISSUE TITLE
Git:  Need ability to see response from Remote on push/pull/sync

### ISSUE THREAD

**Issue by ggedde** [microsoft/vscode#85732]
Currently, when I run a push, pull, or sync I don't get any way to view the response from the remote.  Clicking on "Show Git Output" only seems to show the Git output from my machine, but not the response from the remote.  I am just looking for an option somewhere in settings, etc to change the focus of "Show Git Output" to the remote response.  Basically seeing the same results as if you ran git from a terminal.

There are many services out there that provide more details then just the normal git output.
For example, WPEngine provides much more information, like clearing caches, etc.  It also takes much longer than normal and it is a little unclear if everything ran accordingly without seeing the response.  Also there may be warnings or notices from the remote that will get missed without seeing the responses.

Here is an Example from a WPEngine push when running from the Terminal:
![image](https://user-images.githubusercontent.com/3236909/69766785-67735180-112e-11ea-8a23-cf92235b9741.png)

**Comment by joaomoreno** [comment]
We do output both stdout and stderr. It might actually be that git won't output the `remote:` lines if it detects it isn't in a TTY. Can you try seeing which output is stdout and which is stderr?

```
git push > stdout.log 2> stderr.log
```

Also, can you show me what `Git: Show Git Output` shows when you run `git push`?

**Comment by ggedde** [comment]
@joaomoreno My apologies, it does output the data from the remote.
However, it waits until the remote is completely done before it outputs any data than also adds some generic Git details.

The reason I thought that it didn't was because I have to scroll way back up to see the response from the server I didn't notice that before and because it does it at the end of the response and I usually only have about 4-5 lines showing normally so I didn't see any of the WPEngine output.
![image](https://user-images.githubusercontent.com/3236909/69996069-269c8380-1506-11ea-93b7-fca04b5ee72f.png)

So I will close this for now, but ideally I would like to see the response from the remote server come in as it does from a Terminal response.  Showing instantly and with the correct terminal colors instead of the raw output.  So I will make a separate Feature Request for that.

**Comment by ggedde** [comment]
FYI, when running `git push > stdout.log 2> stderr.log` WPEngine gets loaded into stderr

**Comment by joaomoreno** [comment]
Yeah, we don't really stream the output but just accumulate it until the command is over. The reason for this is that we sometimes run commands in parallel. If we did stream the output, they would appear all intermixed, making it hard to read.
