### ISSUE TITLE
my less file when folded, it does not unfold. if I restart vscode ,it is ok

### ISSUE THREAD

**Issue by haoqichongtian** [microsoft/vscode#85739]
![image](https://user-images.githubusercontent.com/26773939/69772398-c7b7d100-11ca-11ea-95bf-aa03f2958c7b.png)

**Comment by aeschli** [comment]
if you see this again, can you check whether the folding actions (from the command menu) still work?

Duplicate of https://github.com/microsoft/vscode/issues/75726
