### ISSUE TITLE
Keeping vscode/extensions up to date and working on Mac is difficult, would prefer app store

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#85731]
This came from a customer comment in an extension repo (https://github.com/microsoft/vscode-azurearmtools/issues/399):

> Almost every time I start Code (yes I don't use it that often) I am confronted with updates, also the extension I have installed. now I updated my OS an PwSH, TerraForm etc don't work anymore.
> Using the package manager Brew is not easy to install all that voodoo on the comandline, why don't you just include it in the AppStore.
> This will make live easy!
> I am willing to pay for it if it comes from the AppStore, as it takes to much time to make everything work again. I am tired of this!

**Comment by sandy081** [comment]
Not sure what is the request for? Please provide us what is the feature user is missing and expecting?

**Comment by StephenWeatherford** [comment]
@gherik You want to answer this?
