### ISSUE TITLE
Published Extension doesn't work

### ISSUE THREAD

**Issue by Prabhatyadav11** [microsoft/vscode#85747]
- VSCode Version: 1.40.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Make a simple Hello World extension
2. Bundle & Publish to market Place. 
3. Install extension. Doesn't work.

Does this issue occur when all extensions are disabled?: Yes

I'm trying to publish a simple extension to see how it works. Everything works fine in debug mode but when you publish the same code to the marketplace, the extension doesn't act all??

I did package & publish. Didn't work. I did bundling & then published, which doesn't work as well.

```
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	let disposable = vscode.commands.registerCommand('extension.testName', () => {
		vscode.window.showInformationMessage('Hello World!');
		vscode.window.showErrorMessage('Heyyyy heyy heyy');
	});
	context.subscriptions.push(disposable);
}
export function deactivate() {}
```

**Comment by Prabhatyadav11** [comment]
@gjsjohnmurray what data else should I include? 

 I just did [this](https://code.visualstudio.com/api/get-started/your-first-extension) tutorial and published it to the marketplace. The extension doesn't work??

**Comment by gjsjohnmurray** [comment]
What does your ```package.json``` file contain? In particular, what [Activation Events](https://code.visualstudio.com/api/references/activation-events) does it hook into?

What is the name of the extension on marketplace?

**Comment by Prabhatyadav11** [comment]
My Extension 'https://marketplace.visualstudio.com/items?itemName=prabhaat.publishtest'
My Package.json
'''{
	"name": "publishtest",
	"displayName": "publishtest",
	"description": "this is the test for publishing the extension",
	"version": "2.0.1",
	"engines": {
		"vscode": "^1.40.0"
	},
	"categories": [
		"Other"
	],
	"activationEvents": [
		"onCommand:extension.helloWorld"
	],
	"main": "./out/extension.js",
	"contributes": {
		"commands": [
			{
				"command": "extension.helloWorld",
				"title": "Hello World"
			}
		]
	},
	"scripts": {
		"vscode:prepublish": "npm run compile",
		"compile": "tsc -p ./",
		"watch": "tsc -watch -p ./",
		"pretest": "npm run compile",
		"test": "node ./out/test/runTest.js"
	},
	"devDependencies": {
		"@types/glob": "^7.1.1",
		"@types/mocha": "^5.2.7",
		"@types/node": "^12.11.7",
		"@types/vscode": "^1.40.0",
		"glob": "^7.1.5",
		"mocha": "^6.2.2",
		"typescript": "^3.6.4",
		"tslint": "^5.20.0",
		"vscode-test": "^1.2.2"
	},
	"publisher": "prabhaat",
	"Repository name": "Kuchbhi"
}
'''

**Comment by gjsjohnmurray** [comment]
Works for me. Here's what I get when I use Command Palette to run your 'Hello World' command

![image](https://user-images.githubusercontent.com/6726799/69791900-5aea0a00-11bd-11ea-8757-36af87bc6916.png)

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

I noticed you are still on 1.40.0, but I'll be surprised if that's why you're seeing a problem.

**Comment by Prabhatyadav11** [comment]
Thanks @gjsjohnmurray ,I am also able to run it from Command Palette but i thought it is going to run as the background process.

**Comment by gjsjohnmurray** [comment]
Your activate() function runs when your extension gets activated. You can use the * activation event to make that happen as soon as VSCode starts up with your extension enabled. But to be a good citizen your extension shouldn't take a long time to complete its activate()

**Comment by Prabhatyadav11** [comment]
@gjsjohnmurray  I just tried this out. The extension did execute but only once. I have no idea why the extension doesn't work on the next successive tries. I have restarted/exited vscode again & again but to no help.

**Comment by gjsjohnmurray** [comment]
From https://code.visualstudio.com/api/references/activation-events#Start-up

![image](https://user-images.githubusercontent.com/6726799/69803309-bde69b80-11d3-11ea-8f53-aed34acb5e60.png)

What do you mean by "the next successive tries"?

**Comment by Prabhatyadav11** [comment]
@gjsjohnmurray  By that I mean, i expect the extension to work every time i start/restart vscode.

**Comment by gjsjohnmurray** [comment]
Each time you restart VSCode your ```activate``` function should get run the first time one of the activation events it has registered for occurs.

Are you saying this doesn't happen, and that your ```activate``` only ever gets run once, right after you installed your extension?

**Comment by Prabhatyadav11** [comment]
That's exactly what I'm talking about. @gjsjohnmurray

**Comment by gjsjohnmurray** [comment]
There's no way this can be a general VSCode fault, since **every** extension relies on its activate code being run each time VSCode starts up and fires the first activation event for which the extension registered.
