### ISSUE TITLE
Terminal is not cleared with cls command

### ISSUE THREAD

**Issue by AnkitaSharma88** [microsoft/vscode#85744]
Issue Type: <b>Bug</b>

1. open terminal
2. Enter a few commands like node app.js or nodemon server.js etc etc.
3. type `cls` and hit enter
4. It should clear the terminal view but am still able to view the command by scrolling.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.24GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/AnkitaSharma/Documents/node%20samples/mysql/crud%20in%20node%20and%20mysql/node-sql|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
formatter-pug|ale|0.0.1
ng-template|Ang|0.900.0
npm-intellisense|chr|1.3.0
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|3.11.0
evolution-gaming--vscode-eslint|evo|1.9.2
docker-explorer|for|0.1.6
beautify|Hoo|1.5.0
docthis|joe|0.7.1
angular-essentials|joh|0.6.3
Angular2|joh|8.2.0
vscode-peacock|joh|3.2.0
node-module-intellisense|lei|1.5.0
rainbow-csv|mec|1.3.1
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-azureappservice|ms-|0.16.1
vscode-docker|ms-|0.8.2
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
angular2-inline|nat|0.0.17
angular-console|nrw|9.1.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.13.0
vscode-manifest-yaml|Piv|1.13.0
vscode-spring-boot|Piv|1.13.0
material-icon-theme|PKi|3.9.2
java|red|0.53.1
sonarlint-vscode|Son|1.12.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-icons|vsc|9.6.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by igorskyflyer** [comment]
And that's exactly how the ````cls```` command works. Try it out in the Command Prompt (outside of VS Code).

**Comment by dhairyanadapara** [comment]
> And that's exactly how the `cls` command works. Try it out in the Command Prompt (outside of VS Code).

On windows, it will clear the terminal in when using `cmd` or `PowerShell` directly.
