### ISSUE TITLE
git repo does not work in folders with special characters (like ū)

### ISSUE THREAD

**Issue by zaw-shinoto** [microsoft/vscode#85745]
Issue Type: <b>Bug</b>

Git works great out of the box, but today I had problems with a new git repository, when trying to stage a file I was told there is a fatal error and something is out of the scope of the repo. I tried a lot until I found that there are special characters in my top folder (above the git repo). In the meantime I checked git is working in Sourcetree without issues. 

I started from scratch with "normal" folder names, works great again. 

In 2019, full utf8 support should be expected?

(working on Mac OS X Mojave)

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

**Comment by joaomoreno** [comment]
This seems to work fine for me, both cases:

- Repo created in folder named `repū`
- Repo created in folder named `parentū/repo`

@zaw-shinoto Can you give me exact reproducible steps, including complete folder names?

**Comment by zaw-shinoto** [comment]
Thank you very much, I did all steps and wrote them down. 

The problem is not the encoding, but the location of the workspace file, and I think this is special to using git with VSCode?

Description:

I got the error message "Git:fatal: path to document: 'path to document' is outside repository". Without VSCode, mostly using Sourcecode, rarely the Terminal, all files in the same folder as the git repo file are recognized. With VSCode, I cannot have the repo and the workspace on the same level, but the workspace file needs to be one level on top of the folder with the git repo. Is that right?

When I create the same repo inside a folder below the workspace file, everything is OK. 
 
If that is true, the error message is misleading: not the file to be staged is out of the path to the repo, but the repo is out of reach of the workspace, or something like that. At least, the repo works in Sourcetree. 


Anyway, if that is the case, it is no problem to add another level for the workspace above the git and the working files. Much better than the encoding problems that I assumed because of some other circumstances when I created the repo recently. 


Thanks, 
Maria

**Comment by joaomoreno** [comment]
@zaw-shinoto 

What are the *exact* steps for me to reproduce?

**Comment by zaw-shinoto** [comment]
Hi, 

I wrote down every step this afternoon, did it twice, once with and once without umlauts. Since I deleted the repos, I now recreated a repo exactly the same way: 

1. I created a folder on my desktop.
2. I created a new workspace and added this folder to my workspace.
3. Then I saved the workspace inside that folder. 
4. I created a text file in the same folder on the same level as the workspace file.  
5. Then I hit F1 "git: init", where I had to pick a workspace.
6. I picked this workspace, the repo is created on that same level with the workspace file and the text file.. 
7. 2 files are marked as changed, the workspace file and the text file. 
8. I added the workspace file to .gitignore.
9. Now gitignore is the second changed file in my repo, it is on the same level as the other files.
9. Then I clicked the plus button which is nearby the text file in git mode in order to stage the file.

This afternoon, like yesterday, I got this message twice: 
 
10. Then I got the error message "Git: fatal: ...path to file ...:'...path to file...' is outside repository, but I could open the repo in sourcetree and work on it.

This evening, creating a third case, I got no error message. Everything works fine from within VSCode. My computer was not shut down inbetween, everything is the same. 

So I think that I messed something up without knowing -- I am new to VSCode, but quite used to several text editors including Emacs. There must be a subtle step that I did wrong. When I encounter the problem again, may I contact you again?

Thanks for taking care and asking again. 

Maria

**Comment by joaomoreno** [comment]
Yes, let us know if it comes back.

**Comment by cosmicbeamer** [comment]
I encountered the same problem. When I use folder names with german umlauts git is not working correctly.

System: macOS 10.14.6

1. created folder `über`
2. initialised a new repo inside that folder
3. added a file `test.txt` with some dummy text
4. in source control clicked on `+` to stage the changes
5. get error `…/über/test.txt' is outside repository`

What is really strange, when I chose to commit directly without staging, the commit works.

**Comment by joaomoreno** [comment]
@cosmicbeamer Can you show me the full output of `Git: Show Git Output`, after the error occurs?

**Comment by cosmicbeamer** [comment]
@joaomoreno Here we go:

1. init git

> git init

2. switch to source control
Looking for git in: /usr/local/bin/git
Using git 2.25.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

3. initialise repo

> git init

4. add test.txt

> git rev-parse --show-toplevel
> git rev-parse --git-dir
>Open repository: /Users/xxxx/Desktop/über
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git show :test.txt
> git check-ignore -v -z --stdin

5. add dummy text to test.txt & save

6. switch to source control, click on `test.txt` in changes list

> git show HEAD:test.txt

7. click on `+` to stage changes

> git.stage 1
> git.stage.scmResources 1
> git add -A -- /Users/xxxx/Desktop/über/test.txt
> fatal: /Users/xxxx/Desktop/über/test.txt: '/Users/xxxx/Desktop/über/test.txt' is outside repository

Commit directly without staging:

> git add -A -- .
> git commit --quiet --allow-empty-message --file -
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git show HEAD:test.txt
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
