### ISSUE TITLE
marketplace parsing problem.

### ISSUE THREAD

**Issue by TheRealSyler** [microsoft/vscode#85749]
i recently updated my badges,on my extension page in vscode the badges didn't get loaded, they work on github and npm (the same badges on github and very similar ones on npm),  this is probably not an isssue with vscode, but with the markdown parser that you use, i could't find what parser you use, in case this is not a bug could you please tell me what parser you use and with what options so that i can fix it.

[marketplace link ](https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented)
in vscode just search for `syler`, and chose the sass extension.

[npm ](https://www.npmjs.com/package/test-grammar) i know not the same badges but created with the same tool.

plain text:
```markdown
<span id="BADGE_GENERATION_MARKER_0"></span>
 [![circleci]( https://img.shields.io/circleci/build/github/TheRealSyler/vscode-sass-indented)](https://app.circleci.com/github/TheRealSyler/vscode-sass-indented/pipelines) [![vscV]( https://img.shields.io/visual-studio-marketplace/v/syler.sass-indented)](https://marketplace.visualstudio.com/items?itemName=syler.sass-indented) [![vscD]( https://img.shields.io/visual-studio-marketplace/d/syler.sass-indented)](https://marketplace.visualstudio.com/items?itemName=syler.sass-indented) [![vscI]( https://img.shields.io/visual-studio-marketplace/i/syler.sass-indented)](https://marketplace.visualstudio.com/items?itemName=syler.sass-indented) [![githubLastCommit]( https://img.shields.io/github/last-commit/TheRealSyler/vscode-sass-indented)](https://github.com/TheRealSyler/vscode-sass-indented) [![githubIssues]( https://img.shields.io/github/issues/TheRealSyler/vscode-sass-indented?color=lightgrey)](https://github.com/TheRealSyler/vscode-sass-indented)
<span id="BADGE_GENERATION_MARKER_1"></span>

[![Tested With](https://img.shields.io/badge/Syntax Tested With-test--grammar-red?style=for-the-badge)](https://www.npmjs.com/package/test-grammar)
[![Using](https://img.shields.io/badge/Using-sass--formatter-red?style=for-the-badge)](https://www.npmjs.com/package/sass-formatter)
``` 
github:
<span id="BADGE_GENERATION_MARKER_0"></span>
 [![circleci]( https://img.shields.io/circleci/build/github/TheRealSyler/vscode-sass-indented)](https://app.circleci.com/github/TheRealSyler/vscode-sass-indented/pipelines) [![vscV]( https://img.shields.io/visual-studio-marketplace/v/syler.sass-indented)](https://marketplace.visualstudio.com/items?itemName=syler.sass-indented) [![vscD]( https://img.shields.io/visual-studio-marketplace/d/syler.sass-indented)](https://marketplace.visualstudio.com/items?itemName=syler.sass-indented) [![vscI]( https://img.shields.io/visual-studio-marketplace/i/syler.sass-indented)](https://marketplace.visualstudio.com/items?itemName=syler.sass-indented) [![githubLastCommit]( https://img.shields.io/github/last-commit/TheRealSyler/vscode-sass-indented)](https://github.com/TheRealSyler/vscode-sass-indented) [![githubIssues]( https://img.shields.io/github/issues/TheRealSyler/vscode-sass-indented?color=lightgrey)](https://github.com/TheRealSyler/vscode-sass-indented)
<span id="BADGE_GENERATION_MARKER_1"></span>

[![Tested With](https://img.shields.io/badge/Syntax Tested With-test--grammar-red?style=for-the-badge)](https://www.npmjs.com/package/test-grammar)
[![Using](https://img.shields.io/badge/Using-sass--formatter-red?style=for-the-badge)](https://www.npmjs.com/package/sass-formatter)

screenshot of the vscode marketplace: 
![vscode_m](https://user-images.githubusercontent.com/46901787/69783613-29b90c00-11b4-11ea-9544-d564f3430c1e.png)

**Comment by sandy081** [comment]
Please file issue against the market place.

**Comment by TheRealSyler** [comment]
@sandy081 link?

**Comment by sandy081** [comment]
@kesane-msft FYI
