### ISSUE TITLE
Extension host terminated unexpectedly 3 times

### ISSUE THREAD

**Issue by KInGATiLLa** [microsoft/vscode#85742]
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

![errvs](https://user-images.githubusercontent.com/17881842/69777722-84665e00-11dc-11ea-9f7e-ddf705cec6ef.PNG)
![errvs1](https://user-images.githubusercontent.com/17881842/69777845-f179f380-11dc-11ea-83b2-1dff6d12ac3c.PNG)
(Local environment)--->

* Chrome: 78.0.3904.108
* Node.js: 12.13.0
* OS: Windows_NT x64 build10.0.18363 version1909

Issue: Extension host terminated unexpectedly 3 times
Working on: Angular7
Extensions: Tslint, Prettier, Angular 8 snippet, Bracket pair colorizer
 [](url)

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
Please file the issue against the extension that is causing this.
