### ISSUE TITLE
azurecli: pyhton process in vscode high cpu usage

### ISSUE THREAD

**Issue by fle108** [microsoft/vscode#85757]
- VSCode Version: 1.40.2
- OS Version: Windows10 v1909 Build 18363.476

Steps to Reproduce:

1. install or have installed azurecli on windows (typically : C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2
2. install or have installed azureclitools in vscode
2. create or edit file named *.azcli

**Result**: subprocess Visualstudiocode\python(32bit) located at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe take 25-50% cpu all time even if file *.azcli is closed
when vscode restarted and no *.azcli is opened cpu is allright

Does this issue occur when all extensions are disabled?: No
if i disable extension "azure Cli tools" cpu is ok and when i re-enable it, python(32bit) is back at 40%cpu : \

**Comment by sandy081** [comment]
Please file issue against the extension that is causing this.
