### ISSUE TITLE
HTML Table + Source Code Block = How?

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode#85754]
Please advise ...
![screen dump](https://snipboard.io/2vG1yH.jpg)

- VSCode Version: The latest 
- OS Version: WIN10 PRO -- the latest

Does this issue occur when all extensions are disabled?: Yes/No --> YES

**Comment by IllusionMH** [comment]
/question

you can try to add empty line between `<td>` and <code>```js</code>

AFAIK VSCode uses markdown-it implementation under the hood so you can try their [demo page](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ctable%3E%5Cn%3Ctr%3E%5Cn%20%20%20%20%3Cth%3EBlock%20code%20%5C%22fences%5C%22%3C%2Fth%3E%5Cn%20%20%20%20%3Cth%3ESyntax%20highlighting%3C%2Fth%3E%5Cn%3C%2Ftr%3E%5Cn%3Ctr%3E%5Cn%3Ctd%3E%5Cn%5Cn%60%60%60%5CnSample%20text%20here...%5Cn%60%60%60%5Cn%3C%2Ftd%3E%5Cn%20%20%20%20%3Ctd%3E%5Cn%5Cn%60%60%60js%5Cnvar%20foo%20%3D%20function%20%28bar%29%20%7B%5Cn%20%20return%20bar%2B%2B%3B%5Cn%7D%3B%5Cn%5Cnconsole.log%28foo%285%29%29%3B%5Cn%60%60%60%5Cn%3C%2Ftd%3E%5Cn%20%20%20%20%3C%2Ftr%3E%5Cn%3C%2Ftable%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

And report issues there if there is incorrect behavior
