### ISSUE TITLE
Language client is not ready yet: Error: Language client is not ready yet

### ISSUE THREAD

**Issue by fyeeme** [microsoft/vscode#85750]
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
Steps to Reproduce:

1. java plugin not work

Does this issue occur when all extensions are disabled?: No
![image](https://user-images.githubusercontent.com/6078758/69785167-6b68a780-11f2-11ea-83f4-319fdef03a89.png)

**Comment by sandy081** [comment]
Please file issue against the java extension
