### ISSUE TITLE
sqlite3  API open

### ISSUE THREAD

**Issue by snoopylovefiona** [microsoft/vscode#85755]
I'm a plugin developer,At first I wanted to find globalState store location and found it use sqlte3 when I looked at the source code.
i want to use sqlit3 store some information,However, due to different platforms, it can not be very compatible, so I want to use sqlite.note provided by vscode, because it has achieved platform compatibility

we hope you can open sqlite3 api in the feature,thx.

**Comment by sandy081** [comment]
sqlite3 is an internal detail to store our state and we provide an API to manage the extension state. So in our opinion it does not makes sense to expose such an API as it is not inline with our API.
