### ISSUE TITLE
[Insiders-Regression] zsh:1: command not found: tsc The terminal process terminated with exit code: 127

### ISSUE THREAD

**Issue by admmasters** [microsoft/vscode#85753]
I'm noting this behaviour as it has occurred in the insiders build for a few releases now.

- VSCode Version: 1.41.0-insider
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Try running a task (tsc watch in this instance) using the task menu
2. Observe issue

Does this issue occur when all extensions are disabled?: Yes

**Comment by admmasters** [comment]
Note this only occurs with a locally installed typescript - which is bad form seems whatever new behaviour has been introduced relies upon a globally installed typescript which is not great practice at all.

**Comment by RobertoMalatesta** [comment]
Confirm the issue on Linux as well (Kubuntu 18.04).
vsc does not finds tsc command if node is per-user nvm-installed.
Besides it lists an incorrect Typescript version (3.7.3 while I'm on 3.8):
![image](https://user-images.githubusercontent.com/11835025/69922704-02f22280-149f-11ea-8493-61f8ea22cb37.png)

R

**Comment by mjbvz** [comment]
Here's the logic we use to look up the tsc path: https://github.com/microsoft/vscode/blob/cf197953d7c65b4131147d93cf0dc7766a610b70/extensions/typescript-language-features/src/features/task.ts#L183
 
Note that is prefers using the local tsc installed under `node_modules`. How do you have tsc installed?

**Comment by RobertoMalatesta** [comment]
Hi @mjbvz 
> How do you have tsc installed?
I have tried with both.
`> Executing task: /home/robi/src2/industry40/node_modules/.bin/tsc -p /home/robi/src2/industry40/tsconfig.json --watch <
/usr/bin/env: ‘node’: No such file or directory
The terminal process terminated with exit code: 127
`
It seems that newer versions of VSC don't read _.bashrc_ before opening the internal terminal or it's read async.
If I open an integrated terminal and type the "tsc -p ... --watch" command line myself, the compiler executes.

Node Version: 13.2.0
TS Version: 3.8.0-dev.20191128

R

**Comment by alexr00** [comment]
VS Code tasks have never read the .bashrc. By default, tasks run <your shell> -c <your command>, and the -c flag means that the shell is non-interactive and non-login. Tasks usually _do_ inherit the environment that VS Code has though. Something similar happened over in #85714. Do you have `"terminal.integrated.inheritEnv": false` set? That would cause this behavior.

**Comment by RobertoMalatesta** [comment]
>Do you have "terminal.integrated.inheritEnv": false set? That would cause this behavior.

It is set to true.

**Comment by alexr00** [comment]
Can you share your tasks.json if you have one and all of your settings.json files?

**Comment by RobertoMalatesta** [comment]
> Can you share your tasks.json if you have one and all of your settings.json files?

@alexr00 Yes. I'll have to edit out some info for security and non-disclosure reasons.

The key point I think is the error line reported in the internal terminal when opened with ^B:
`/usr/bin/env: ‘node’: No such file or directory`
If I open a new internal terminal ("+")  and issue:
`tsc -p tsconfig.json`
or
`tsc -p tsconfig.json --watch`

tsc executes.

R

**Comment by RobertoMalatesta** [comment]
tasks.json:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ]
        }
    ]
}

```


tsconfig.json:

```

{
  "compilerOptions": {

    "incremental": true,
  
    "target": "es5",                       
    "module": "amd",                 
    "lib": [
      "es6",
      "dom",
      "es2015.iterable"
    ], 
    "allowJs": true, 
    "sourceMap": true,                  
    "outFile":  <cut>, 
    "outDir":  <cut>
    "strict": true,                   
    "esModuleInterop": true ,               
    "inlineSourceMap": false,              
    "inlineSources": false,                

  },
  "files": [
  <cut>
  ],
  "include": [
  <cut>
  ],
  "exclude": [
  <cut>
  ] 
}
```

**Comment by admmasters** [comment]
The other key thing to note here is that this is 100% working on the normal channel so whatever change in behaviour has been introduced is recent and unique to the insiders channel.

**Comment by alexr00** [comment]
Can you share your settings.json?

**Comment by admmasters** [comment]
``` project
{
    "cSpell.words": [
        "persistor"
    ],
    "typescript.tsdk": "node_modules/typescript/lib"
}
```

**Comment by admmasters** [comment]
```{
    "npm.packageManager": "yarn",
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.organizeImports": true
    },
    "editor.tabSize": 2,
    "editor.renderWhitespace": "all",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "workbench.iconTheme": "material-icon-theme",
    "editor.formatOnSave": true,
    "editor.fontFamily": "Source Code Pro for Powerline",
    "workbench.colorTheme": "Winter is Coming (Dark Blue - No Italics)",
    "editor.suggestSelection": "first",
    "sync.gist": "5f44767f3b5aaa317b0ea5151cae465d",
    "go.useLanguageServer": true,
    "typescript.preferences.quoteStyle": "single",
    "typescript.preferences.importModuleSpecifier": "relative",
    "eslint.alwaysShowStatus": true,
    "eslint.autoFixOnSave": true,
    "eslint.packageManager": "yarn",
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact"
    ],
    "window.zoomLevel": 0,
    "terminal.integrated.inheritEnv": true

}

**Comment by hilleer** [comment]
Had this same issue popping up after updating vscode to version `1.41.0`, while it has been working perfectly fine until then.

Running on macOS Catalina version `10.15.2`.

**Comment by RobertoMalatesta** [comment]
> he other key thing to note here is that this is 100% working on the normal channel 

On Linux the same issue is present in 1.40.02 stable.

**Comment by jimisaacs** [comment]
Same behavior Version: 1.41.0
was working fine yesterday.

**Comment by MJRasmussen** [comment]
> Same behavior Version: 1.41.0
> was working fine yesterday.

Had to downgrade it: https://code.visualstudio.com/updates/v1_40 to solve it.

**Comment by alexr00** [comment]
Can anyone who's seeing this share the output from the task?

**Comment by alexr00** [comment]
Found the issue: cf197953d7c65b4131147d93cf0dc7766a610b70
On linux (and maybe others, just not Windows). the `stat.type` of the `node_modules/.bin/tsc` is 65, which isn't `vscode.FileType.File` (that's actually `).

**Comment by jrieken** [comment]
The `FileStat#type` property is a bitmask, so 65 is a sym-link to a file (1 /*file*/ + 64 /*symlink*/)

**Comment by alexr00** [comment]
Yup, today's the first time I've ever looked at our `FileStat` API so I read the documentation :)

**Comment by hilleer** [comment]
> Can anyone who's seeing this share the full terminal output from the task?

@alexr00 what do you need exactly? The error I get is the same as  the one @RobertoMalatesta posted here: https://github.com/microsoft/vscode/issues/85753#issuecomment-560177248.

**Comment by sandy081** [comment]
Discussed in our standup and agreed to be included for November Recovery.

**Comment by hilleer** [comment]
Can confirm this is again working for me with vscode version `1.41.1`.

**Comment by RobertoMalatesta** [comment]
1.41.1 : same problem persists:
![image](https://user-images.githubusercontent.com/11835025/71426821-4e6bab00-26b0-11ea-9b3b-28486887d07e.png)

**Comment by RobertoMalatesta** [comment]
... same happens with latest insider.
![image](https://user-images.githubusercontent.com/11835025/71426957-35fc9000-26b2-11ea-9fe6-5d4ac6ed9a4b.png)

**Comment by RobertoMalatesta** [comment]
A temporary remedy is to create a link that env can see.
in my case:
_ln -s  /home/robi/.nvm/versions/node/v13.2.0/bin/node /usr/local/bin/node_
But it's an ugly patch and I hate ugliness.

Merry X-Mas,
--R

**Comment by humansthatmake** [comment]
Having a similar issue here.
Here I tried to run `make` as a task:
![Screenshot 2020-01-07 at 21 31 07](https://user-images.githubusercontent.com/10792249/71931466-b680bd80-3195-11ea-8869-ac0d46c75310.png)

Here I tried to run `make` in a different integrated terminal session:
![Screenshot 2020-01-07 at 21 37 49](https://user-images.githubusercontent.com/10792249/71931601-fa73c280-3195-11ea-85c6-7e2c76ccf3ca.png)

The outputs are quite different and they should not be.

It seems like when I run a task the new terminal session is stripped out of any user configurations and starts running a factory version of the terminal. 


VSCode: 1.41.1
macOS 10.14.6

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "includePath": [
                "${workspaceRoot}/main/**",
                "${workspaceRoot}/build/include/",
                "${env:IDF_PATH}/components/**"
            ],
            
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "~/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by alexr00** [comment]
Please open a new issue since this isn't a problem with typescript task detection.

**Comment by humansthatmake** [comment]
done.
https://github.com/microsoft/vscode/issues/88290

Thank you @alexr00
