### ISSUE TITLE
Git: working tree does not work 

### ISSUE THREAD

**Issue by emono** [microsoft/vscode#85751]
- VSCode Version:
Version: 1.40.2

- OS Version:
10.14.6

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/17827474/69787701-5dba1e80-1200-11ea-8bdd-5348ab3237c8.png)

1. opne my project managed git
2. can't display source diff

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
If you run `Developer: Toggle Developer Tools`, what do you see?

Which extensions do you have installed?
