### ISSUE TITLE
Commenting a selection with ctrl + K, C is not selection-aware

### ISSUE THREAD

**Issue by ralaul** [microsoft/vscode#85758]
Issue Type: <b>Bug</b>

If I have a line that looks like this:

`if (this.configProvider.config.permissions.adpRequestAVLast &&`

and I select 'this.configProvider.config.permissions.adpRequestAVLast', then hit ctrl + K, C, I would expect the result to look what it does in visual studio, which is this:

`if (/*this.configProvider.config.permissions.adpRequestAVLast*/ &&`

Instead, it comments the entire line like this:

`// if (this.configProvider.config.permissions.adpRequestAVLast &&`

If I place my cursor on the line without selecting anything, then this behavior is expected, if I select only a part of the line, it makes more sense, and is more consistent with visual studio to use an inline comment.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (9.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
<kbd>Ctrl+K</kbd><kbd>Ctrl+C</kbd> is the default shortcut for ```editor.action.addCommentLine``` (Add **Line** Comment), so what you're reporting isn't a bug.

Maybe you want to use ```editor.action.blockComment``` (Toggle Block Comment) when some text is selected, and ```editor.action.addCommentLine``` -- or alternatively ```editor.action.commentLine``` (**Toggle** Line Comment) -- when none is selected. You can do this by assigning the same keybinding to both commands but making one test ```editorHasSelection``` in its when-expression and the other test ```!editorHasSelection```.

**Comment by ralaul** [comment]
This has a side-effect of making a block comment when I select multiple lines at the same time. In this case, line comments are better, as you can do a block selection to partially clear them instead of uncommenting the entire thing, and re-commenting the desired lines one by one or with multiple actions.

**Comment by gjsjohnmurray** [comment]
https://stackoverflow.com/questions/58803218/vscode-key-binding-with-when-clause-for-partial-line-selections @ralaul is this you?

**Comment by ralaul** [comment]
It isn't

**Comment by gjsjohnmurray** [comment]
Pinging @alexandrudima who seems to be a team member specializing in keybinding issues. Maybe he has an opinion on the SO post's suggestion about adding a ```when``` clause context to make this possible.
