### ISSUE TITLE
Please provide a way to find the electron version of vscode from command prompt

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#85756]
Hi 
We have an extension that needs to find the electron version which will be used in installing some node packages.
Is there a way to find the electron version from the command prompt like how we find the vscode version using 'code --version' command.

I know from vscode we can find it using F1 -> developer tools -> in console (process.versions.electron)

But I want to find it from the command prompt.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
> * Enhance vscode to return electron version using command prompt (#79305)

This issue was labeled as out of scope.
Sorry, may I know why?

Thanks
Akhil

**Comment by sandy081** [comment]
/duplicate

Please add your comments to the original issue
