### ISSUE TITLE
Goto Definition Context Menu looks like strange behavior in *.tsx

### ISSUE THREAD

**Issue by thayamizu** [microsoft/vscode#85752]
- VSCode Version: 1.40.2
- OS Version: macOS 10.14.6 Mojave.

Steps to Reproduce:

1. open .tsx file
    1. `*.ts` file is ok.
2. select `goto definition` from context menu. 

Note:   
Maybe, this issue related #70032. But, `*.ts` is work.   

![1](https://user-images.githubusercontent.com/95033/69787652-4aa74e80-1200-11ea-823d-9996512356f9.png)
![2](https://user-images.githubusercontent.com/95033/69788066-0b2d3200-1201-11ea-85a8-2f8c29136d49.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please explain what the expected behavior is?

**Comment by thayamizu** [comment]
I expected that If I execute `goto definition` from the context menu,  jump to the implementation or type definition. But, this case peeks a definition in the active editor.  This behavior is not `goto definition` but `peek definition`.

**Comment by mjbvz** [comment]
Are there multiple definitions? Also have you tried configuring the `editor.gotoLocation.multipleDefinitions` setting?

**Comment by thayamizu** [comment]
> Are there multiple definitions?

Yes. So, I followed your advice and configured `editor.gotoLocation.multiple Definitions`. Then it jumped to Implementation. 

Thank you.
