### ISSUE TITLE
Provide a way to Show Command Search Palette on "empty" backdrop view

### ISSUE THREAD

**Issue by lucideer** [Microsoft/vscode#8576]
- VSCode Version: 1.2.1
- OS Version: various / many

Steps to Reproduce:
1. Open a file in VSCode
2. Click the filename at the top left of the file pane (this opens the command palette)
3. Close all files in VSCode (this shows a blank pane with the VSCode logo)
4. Click the same location (currently blank - nothing happens - command palette is no longer accessible via mouse)

_Quite a low-priority feature request as I'm primarily a keyboard user, but it would be nice if it were fully mouse-accessible in all editor states._

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
