### ISSUE TITLE
Emmet Extension CSS abbrevation expansion for vendor prefixes does not work as expected

### ISSUE THREAD

**Issue by PetaSoft** [microsoft/vscode#85764]
- VSCode Version: 1.40.2 (fresh installation with no external extensions or settings changed)
- OS Version: MS Windows 10 (19.03) Professional

Steps to Reproduce:

1. Add to "settings.json" the properties 
    "emmet.preferences": {
        "css.webkitProperties": "border-right,animation",
        "css.mozProperties": ""
    }
  and save the settings.
2. Open a new file and save it as "Test.css"
3. Enter 
    div {
        -bg2
    }
  and expand the "-bg2" Emmet abbrevation. Then I get: 
    div {
        -webkit-background: 2px;
        -moz-background: 2px;
        -ms-background: 2px;
        -o-background: 2px;
        background: 2px;
    }
  However, following the documentation at https://code.visualstudio.com/docs/editor/emmet#_include-vendor-prefixes I should get the following result:
    div {
        -ms-background: 2px;
        -o-background: 2px;
        background: 2px;
    }
  Furthermore, using the value null for one of the above mentioned "emmet.preferences" properties the editor shows me an error message: "Incorrect type. Expected "string", but in the above mentioned documentation a value null is allowed and shown there in an example.

Does this issue occur when all extensions are disabled?: No, Emmet is a build in extension of VS Code. Disabling extensions does not work, and I use a fresh installation of VS Code with no other external extensions loaded.

**Comment by rzhao271** [comment]
Out of scope because vendor prefixes are being deprecated in a newer version of Emmet.
