### ISSUE TITLE
Go to definition not working for any language

### ISSUE THREAD

**Issue by vijayjdk** [microsoft/vscode#85760]
Issue Type: <b>Bug</b>

Go to definition not working for any language also tried re-installing but didnt found anything helpful tried un-installing completely and deleting cache still not helpful

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
/confirmationPending Works for me.

![junk](https://user-images.githubusercontent.com/6726799/69800049-5e38c200-11cc-11ea-9e47-4bce9cfc8629.gif)
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

/needsMoreInfo

**Comment by art40100** [comment]
Same here with error Unable to open '': File is a directory.
![errrrrrrrrrrrrrr](https://user-images.githubusercontent.com/33236770/69816497-3021a500-1201-11ea-9d3b-0f9d5e093491.PNG)

**Comment by art40100** [comment]
Update: it seems to be working again for me, no changes to configuration, extensions were made...can not explain.

**Comment by jrieken** [comment]
ping @vijayjdk
