### ISSUE TITLE
Add 'none' option to editor.suggestSelection

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#85768]
Issue Type: <b>Feature Request</b>

Some users seem to dislike that the suggestion list always has an item selected when it appears. They're happy to see the list but want to make a conscious choice (down-arrow) to take a selection. That way, if they just keep typing they'll get exactly what they type even if their next character is one that would otherwise trigger acceptance of a suggestion.

How about extending ```editor.suggestSelection``` to accept a new value ```none``` ?

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

**Comment by rwilliams** [comment]
So if you hit enter (or whatever the keybind may be) with none selected it would just keep what you've already typed?

**Comment by gjsjohnmurray** [comment]
Yes, that is the idea.

**Comment by rwilliams** [comment]
Perfect!
