### ISSUE TITLE
Setting zoom level to 1 leads to jumpy scrolling

### ISSUE THREAD

**Issue by caillou** [microsoft/vscode#85767]
- VSCode Version: 1.40.2 and 1.41.0-insider
- OS Version: MacOS 10.15.1

Steps to Reproduce:

1. Set `Zoom Level` to 1
2. Slowly scroll in both the explorer and the editor.
3. You will see that the line jump in small increments, separated from each other, c.f. GIF

![Nov-28-2019 13-19-02](https://user-images.githubusercontent.com/46739/69807267-268a4400-11e5-11ea-9d08-46e249ccc6a9.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by caillou** [comment]
@joaomoreno I see that you added the ![help wanted](https://img.shields.io/badge/-help--wanted-fef2c0.svg) badge. Could you maybe give me a hint or two on where to get started on this, then I might give it a try.

I already figured out, that the bug comes from the fact, that the CSS ends up with fractional `px` values.

**Comment by joaomoreno** [comment]
Can you show me where you see those fractional values?

**Comment by caillou** [comment]
@joaomoreno If you set the zoom level to 1, e.g. with <kbd>command</kbd> + <kbd>=</kbd>, then you can see the following in the `developer tools`:

<img width="1476" alt="Screenshot 2019-12-09 at 13 12 51" src="https://user-images.githubusercontent.com/46739/70435090-39730300-1a86-11ea-882e-411a53f2cef2.png">

**Comment by nynexman4464** [comment]
I've experienced this in vs code on mac as well.  I tried to find a bug report and found this [from a while ago](https://github.com/Microsoft/vscode/issues/28439).  FWIW I can't replicate in chromium 81, at least using page zoom, the factors are different though (100%, 110%, 125%).

**Comment by robertrossmann** [comment]
This issue is even more visible in the git diff views - having zoom set to `1` and looking at a diff view, there are strange lines jumping all around the view on each scroll position change. Gif attached for demonstration purposes.

> Some background: I have a large 4k 32" panel at home and to effectively work in Code I have to zoom the contents in a bit, otherwise everything is extremely small and hard to read. So I have zoom activated some 50% of my coding time and have to look at these artifacts quite often. 😢

![vscode-zoom](https://user-images.githubusercontent.com/3058150/71884353-76d7b880-3138-11ea-9556-85ab3ac131a8.gif)

**Comment by joaomoreno** [comment]
@alexdima Seen this?

**Comment by alexdima** [comment]
I cannot speak about the tree, but about the editor. Here is the explanation -- https://github.com/microsoft/vscode/issues/28439#issuecomment-308407781

There are no changes I can do on my side to workaround the zoom. Please use zoom only for presenting something on a projector and never for real life work, unless you zoom in by 200%.

For the editor, if you want everything to be pixel perfect, simply use editor.fontSize. For the workbench, I can only recommend upvoting https://github.com/microsoft/vscode/issues/519
