### ISSUE TITLE
libdbus-1.so.3: no version information available

### ISSUE THREAD

**Issue by MarianoGodoy** [microsoft/vscode#85762]
- VSCode Version: 1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64

- OS Version: RHEL 7.4

Steps to Reproduce:

1. type "code" on command line
2. code would not launch and error shown:
/usr/share/code/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
How did you install code ? Can you provide the output of `code --verbose` ? Thanks!

the libdbus warning is harmless, thats not the cause of the issue here. You can find more information about why that is printed from https://github.com/electron/electron/issues/16364 and https://bugs.chromium.org/p/chromium/issues/detail?id=783468.

**Comment by MarianoGodoy** [comment]
Hello thanks lots! 

output with --verbose:


[root@devecpvm009602 ~]# code --verbose --user-data-dir /~
/usr/share/code/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)
/usr/share/code/code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/code)
/usr/share/code/code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/code)
(code:18967): Gtk-WARNING **: cannot open display:

I think the problem here is that I am trying to use vs code from a headless RHEL via Xming from a windows machine (corporate restrictions), and I;ve jut read that this configuration may not be supported?

if so, is there a way to run vs code remotely?

thanks!

**Comment by deepak1556** [comment]
@MarianoGodoy https://code.visualstudio.com/docs/remote/remote-overview suite should help you with remote development

**Comment by egamma** [comment]
@MarianoGodoy in addition to the docs that @deepak1556 mentioned there is also a blog post on remote development with some videos that provide a good overview https://code.visualstudio.com/blogs/2019/05/02/remote-development.

**Comment by MarianoGodoy** [comment]
Awesome guys! Thanks for the help!

**Comment by luokery** [comment]
VSCode Version: 1.46.1 x64
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z (1 wk ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 3.10.0-327.el7.x86_64

OS Version: RHEL 7.2 x64
Red Hat Enterprise Linux Server release 7.2 (Maipo)

Steps to Reproduce:

type "code" on command line
code would not launch and error shown:
/usr/share/code/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)

[root@localhost]#code  --user-data-dir
With root, you can run!
The error still exists, but it can run!

[sas@localhost local]$ code
/usr/share/code/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)
[sas@localhost local]$ code  --user-data-dir
/usr/share/code/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)
but:  Root works!
[root@localhost yum.repos.d]# code  --user-data-dir
/usr/share/code/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)
