### ISSUE TITLE
Typescript language service died 5 tims right after it got started

### ISSUE THREAD

**Issue by louisvangeldrop** [microsoft/vscode#85765]
Issue Type: <b>Bug</b>

<syntax> TypeScript Server Error (3.7.3-insiders.20191123)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:133315:23)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (tsserver.js:140230:42)
    at IOSession.Session.getFormattingEditsForRange (tsserver.js:140322:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139367:61)
    at tsserver.js:140917:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140908:28)
    at IOSession.Session.executeCommand (tsserver.js:140917:33)
    at IOSession.Session.onMessage (tsserver.js:140940:35)
    at Interface.<anonymous> (tsserver.js:142255:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

VS Code version: Code - Insiders 1.41.0-insider (615732feae7228502eab60919d67837f7a625e7c, 2019-11-27T05:37:07.864Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
string-converter|ada|0.1.2
vscode-javascript-snippet-pack|aka|0.1.5
vbscript|Dar|1.0.4
vscode-quick-select|dba|0.2.8
githistory|don|0.4.6
vscode-wasm|dts|1.2.1
rest-client|hum|0.23.0
vscode-text-pastry|jkj|1.2.0
Angular2|joh|8.2.0
pwa-tools|joh|0.1.0
vscode-peacock|joh|3.2.0
cortex-debug|mar|0.3.4
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.1
vscode-azurefunctions|ms-|0.20.0
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-edge-devtools|ms-|1.0.6
mssql|ms-|1.7.1
python|ms-|2019.11.50794
remote-containers|ms-|0.86.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.41.0
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
cmake-tools|ms-|1.2.2
cpptools|ms-|0.26.2-insiders2
node-debug2|ms-|1.41.0
powershell|ms-|2019.11.0
typescript-javascript-grammar|ms-|0.0.53
vscode-node-azure-pack|ms-|0.0.10
vsliveshare|ms-|1.0.1293
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.2
debugger-for-chrome|msj|4.12.1
debugger-for-edge|msj|1.0.12
vscode-react-native|msj|0.13.2
vscode-apl-language-client|Opt|0.0.9
qub-textedits|qub|1.0.0
text-marker|ryu|1.11.0
addDocComments|ste|0.0.8
nativescript|Tel|0.11.0
tizentv|tiz|1.0.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.0
azure-iot-edge|vsc|1.19.0
azure-iot-toolkit|vsc|2.13.0
azure-iot-tools|vsc|0.3.0
vscode-arduino|vsc|0.2.28
vscode-iot-device-cube|vsc|0.1.4
vscode-icons|vsc|9.6.0
WebTemplateStudio-dev-nightly|WAS|0.0.1929801
debug|web|0.23.1
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, open the `TypeScript` section of the output panel. 
1. At the very top of that log output, find the `<semantic> log file` line. It should look something like:

```
[Info  - 00:12:17.130] <semantic> Log file: /Users/matb/Library/Application Support/code-oss-dev/logs/20191122T190638/exthost37/vscode.typescript-language-features/tsserver-log-FuDPa0/tsserver.log
```

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by louisvangeldrop** [comment]
I can't reproduce the error anymore.
