### ISSUE TITLE
Test: initial debug / run experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#85774]
Refs: https://github.com/microsoft/vscode/issues/84677

- [x] anyOS @jrieken 
- [x] anyOS @sandy081 

Complexity: 3

We have improved the debug start experience for new users.
Open VSCode in the purple no folder mode and verify:
* Content of the debug viewlet makes sense and helps you to start debugging / running your program
* Content of the debug viewlet changes as the active file changes, buttons get disabled when you are on a file which can not be debugged

Open VSCode in a folder with no `launch.json` and verify:
* Content of the the debug viewlet makes sense and guides you to start debugging or to create a `launch.json` file. Buttons get disabled / enabled based on the active file. 
* Once you have created the `launch.json` the start view is no longer visible

The point of these changes is to simplify the start debug experience to new users. Any feedback on how to better do this are  welcome.

**Comment by FantasySoftwareDesigns** [comment]
Is this what is causing my issues since around 22 hours ago?

Launcher[1] disconnected unexpectedly

**Comment by isidorn** [comment]
No

**Comment by fredow68** [comment]
@FantasySoftwareDesigns 
> 
> 
> Is this what is causing my issues since around 22 hours ago?
> 
> Launcher[1] disconnected unexpectedly

Look at https://github.com/chrmarti/testissues/issues/52646

**Comment by FantasySoftwareDesigns** [comment]
Hi,

    I discovered the issue. The version of the Python library and Visual
Studio Code had auto-updated and the versions simply do not work.
