### ISSUE TITLE
开启自动补全括号，在jupyter notebook在出现异常

### ISSUE THREAD

**Issue by HuangQiang97** [microsoft/vscode#85776]
with    "python.autoComplete.addBrackets": true, in  setting.json ,
when i use  the autocomplete  in jupyternotebook , there appears $0 in function's parentheses，just like：print($0)
![image](https://user-images.githubusercontent.com/37450694/69819679-63ccf100-123a-11ea-997c-ea024525c779.png)

**Comment by sandy081** [comment]
Please file the issue against the extension.
