### ISSUE TITLE
Preserve language and encoding when dragging file (normal or untitled) to other window

### ISSUE THREAD

**Issue by andrhevictor** [microsoft/vscode#85770]
Issue Type: <b>Bug</b>

When change file from a window to another, VS Code change the encode of the file, setting the default encode that is configured. If none, the default is UTF-8.

**What is expected to see:**
The file keep the encoding that was saved.

**What actually happened:**
VS Code change the encoding to the default encode (`files.encoding` in `settings.json`).

**This issue occurs even with all extensions disabled.**

**Steps to reproduce:**
1. Create a file with a different encoding than the default (`files.encoding` in  `settings.json`)
2. Open a new VS Code window.
3. Drag and drop the file to the new window.
4. In the new window, the file will change his encode.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.06GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by bpasero** [comment]
This is currently simply not implemented. Code area is https://github.com/microsoft/vscode/blob/f3f658369f117d12b0ae6960555b4b2845178fd8/src/vs/workbench/browser/dnd.ts#L365 but we currently miss a way to open an editor with specific encoding.

**Comment by bpasero** [comment]
I just noticed that we also seem to miss the selected language mode when dropping an editor to another window, that should be easy to add as well.

**Comment by andrhevictor** [comment]
But the encode change even if the file was previously saved.
When the file is saved, the language is preserved when dragged to other window.

1. Create a file and change the encode and the language.
2. Save the file.
3. Drag to a new VS Code Window.
4. The file will keep the language, but will change the encode.

**Comment by bpasero** [comment]
@andrhevictor I don't think it preserves the language properly, it would just pick it up looking at the file extension. Try with a *.css file for example that you change the language to something else and move that around.

**Comment by andrhevictor** [comment]
Ops. You are right.

**Comment by bpasero** [comment]
**Verification:** configure encoding and language mode for a file or untitled file in a way that is not the default (e.g. a windows encoding and a HTML language mode for a CSS file). Drag and drop this file into another window of VSCode and check that encoding and language mode are restored.
