### ISSUE TITLE
Replace Preview in broken state after replacement is done

### ISSUE THREAD

**Issue by SpineEyE** [microsoft/vscode#85772]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Fill Search and Replace fields to replace in multiple files, don't replace yet.
2. Preview the change in any file by double-clicking a result line. The Replace Preview will open and stay open, even if a different result of a different file is selected.
3. Press "Replace All"
4. The Replace Preview stays open and is blank with scrollbar markers still active

If you then do another Search&Replace and want to open a result in the same file, nothing happens, the Replace Preview just stays blank and has to be closed manually.

I think, the Replace Preview should be closed after replacement even if it was opened permanently (i.e. by double-click).

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.3.0-23-generic snap

**Comment by sandy081** [comment]
I am no longer able to replace this, please try again with latest release and let us know if you still see the issue.

**Comment by SpineEyE** [comment]
Yup, it's fixed. Thanks.
