### ISSUE TITLE
Using typescript-language-features extension and plugins

### ISSUE THREAD

**Issue by agentcooper** [microsoft/vscode#85788]
(I'm not sure if this is bug or not)

I'm building an extension for a domain specific language that uses a subset of TypeScript. It uses a custom file extension, let's say it is `*.sts` (SmallTypeScript). I would like to reuse all IntelliSense features that VSCode supplies for TypeScript.

I've made some progress doing following:
1. VSCode extension manifest defines a [new language](https://code.visualstudio.com/api/references/contribution-points#contributes.languages).
2. Same VSCode extension manifest defines [TypeScript server plugin](https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins) with a [`languages` field](https://github.com/microsoft/vscode/commit/4f398bafda1fde8e17ec4646371272baad6d3914) that points to my language.

I'm able to override compilation settings (I provide my own built-in functions) and get hover support for them:
<img width="947" alt="wip" src="https://user-images.githubusercontent.com/794591/69835075-1f901f80-123f-11ea-9208-7a45e7b7d457.png">

The problems are following:
1. Although I specify `jsx` property in my [compiler options override](https://github.com/agentcooper/vscode-sts/blob/master/src/sts-language-service-plugin/index.ts#L28), TS server does not seem to pick it up (see Problems on screenshot above).
2. There are no suggestions/completions. If on line 6 I try typing `data.`, I get no completion items.

Both problems are solved in the `hello.tsx` file I have in the same directory, it has the same content.

I've created an example repository to reproduce the problem: https://github.com/agentcooper/vscode-sts.

**Comment by agentcooper** [comment]
@mattbierner maybe you will be able to help with this, since you've worked on 4f398bafda1fde8e17ec4646371272baad6d3914?

**Comment by agentcooper** [comment]
@RyanCavanaugh since this is related to `tsserver` as well, any suggestions?

**Comment by agentcooper** [comment]
**Update:** I solved JSX by overriding `getScriptKind` and solved completions by providing `typescript-plugins.suggest.enabled` since that is used by typescript-language-features.

**Comment by mjbvz** [comment]
The additional language support for js/ts (4f398ba) was originally added for angular. However the push behind this effort sort of died off and so it seems unlikely it will ever move past prototype stage.

I think you're better off proxying everything through VS Code apis. See the [built-in commands](https://code.visualstudio.com/api/references/commands) for example of this
