### ISSUE TITLE
VSCODE doesn't respect font settings for editor or terminal

### ISSUE THREAD

**Issue by cyberbeast** [microsoft/vscode#85782]
- VSCode Version: 1.40.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install Fira Code font from https://github.com/tonsky/FiraCode
2. Install VSCode, edit settings for editor's and terminal's fontFamily to reflect "Fira Code". Edit settings to enable `ligatures`. 

The settings will haphazardly work sometimes. After every computer restart though, the following screenshot is what the editor looks like.

https://imgur.com/a/0ztcWgF
 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dhairyanadapara** [comment]
As you have shown your setting for the font. I think you have to add a pair of `''(quotes)` on font name like this `"editor.fontFamily": "'Fira Code Retina', Consolas"`.
