### ISSUE TITLE
Restore target environments in common & browser

### ISSUE THREAD

**Issue by malekpour** [Microsoft/vscode#8578]
Some parts in workbench dragged in dependencies to upstream environments (common => browser, browser => electron-browser).

**Original:**

First of all thank you for making a standalone version of `monaco` available. It is the greatest online editor and most people don't need more than that. But I was using `monaco-workbench`, its services and UI infrastructure in a custom web project, similar to vs online.

Thanks to great source structure my implementation was working very good until a recent change to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/workbench.ts#L47 which references from `electron-browser` and prevents it to be used in web.

I know it has not been the intent to make everything reusable, but it would be greatly appreciated if the team maintain the code in a way to keep `browser` modules available in web for use cases like this.

**Comment by malekpour** [comment]
Also according to https://github.com/Microsoft/vscode/wiki/Code-Organization#target-environments `browser` may not use from `node`, `electron-browser` and `electron-main`.

**Comment by bpasero** [comment]
Good catch, this should not be the case. Have to look into it, but only for July.

**Comment by malekpour** [comment]
Thank you, also there is another reference to `vs/editor/node/model/modelBuilder` in `vs/workbench/parts/files/browser/textFileServices`.

**Comment by malekpour** [comment]
@bpasero I found more instances. Do you want me to add them here or you will review them all when you get time for working on it?

**Comment by bpasero** [comment]
@malekpour that would be great. It is too bad we do not have a linter to give us a warning for this. I am sure we have many more cases throughout our code.

May I ask where and how you use the workbench standalone?

**Comment by malekpour** [comment]
@bpasero I am using workbench and monaco for an online IDE to manage server side repositories, similar to Kudu and VS Online but for enterprise environment. I was using an angular app and ace editor but found monaco a great alternative. Currently waiting for release clearance before I can publish it open source.

I can report workbench issues in web environment here or wherever it is appropriate, please let me know.

I found the following references by regex searching for `(/electron-browser/|/node/)` in `src/**/browser/**` and excluding `src/**/electron-browser/**`.

![image](https://cloud.githubusercontent.com/assets/542968/16522549/8f5bafe0-3f6c-11e6-832c-0d875dcfb6ab.png)

**Comment by bpasero** [comment]
That is pretty cool, thanks 👍

**Comment by bpasero** [comment]
To be clear, I can not make a statement if workbench.ts stays in browser land. I will try, but eventually we might have to move it to electron-browser land. Using the workbench as such standalone was never intended nor planned with VS Code.

**Comment by malekpour** [comment]
Good to know. In my case moving `workbench.ts` is not important because I have re implemented it in my repo anyway but please try to keep the rest sanitized from being mixed with electron.

**Comment by bpasero** [comment]
I fixed some issues in workbench land and as expected workbench had to move into electron-browser.

Since the related issues are in @isidorn and @alexandrudima land, I am moving this issue to them.

**Comment by malekpour** [comment]
Are you moving `workbench.ts` file only or it may affect other files in the browser folder like `layout.ts`?

**Comment by bpasero** [comment]
@malekpour just workbench.ts

**Comment by isidorn** [comment]
I fixed all the issues in my land #8806 #8802 #8807 #8803

**Comment by bpasero** [comment]
@isidorn thanks dude!

**Comment by bpasero** [comment]
@malekpour should be good now, let us know otherwise 👍

**Comment by malekpour** [comment]
It works perfectly. Thank you :+1:
