### ISSUE TITLE
unknown error/

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#85784]
Version:Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. open a new untitled file.
2. type "pr" go on the "print" on suggestion window and press enter.
3. type something after press "enter"
4. use ctrl+a to clear all text.
5. type "pr" again. the suggestion not working.

the new code we are writing looks like selected but it different from selected words:
[image](https://user-images.githubusercontent.com/26390254/69831070-09815f80-123d-11ea-807f-0852a2e3f6eb.png)

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
> type "pr" again. the suggestion not working.

Which means what? Is it still shown or not? It doesn't work when inserting.

> Does this issue occur when all extensions are disabled?: No

If "No" then please name the extension which is responsible for this, e.g from what extension does the snippet suggestion come?

**Comment by byehack** [comment]
> Which means what? Is it still shown or not? It doesn't work when inserting.

not shown

> If "No" then please name the extension which is responsible for this, e.g from what extension does the snippet suggestion come?

ms-python

**Comment by jrieken** [comment]
can you reproduce this with another file, eg. a JS or TS file and a snippet/suggestion from them?

**Comment by byehack** [comment]
test on ts file and worked fine. i think the problem is from ms-python
