### ISSUE TITLE
Ctrl+Shift+O cannot show long function name

### ISSUE THREAD

**Issue by guolisen** [microsoft/vscode#85793]
Issue Type: <b>Bug</b>

Ctrl+Shift+O cannot show long function name

sometimes in C++, the function name has a long namespace, so the Ctrl+Shift+O cannot show the whole function name, because the dialog is too short and doesn't have scroll bar.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|1.7.7
lua-debug|act|1.21.1
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
shell|bbe|0.3.0
c-cpp-project-generator|dan|1.1.1
algorithm-mnemonics-vscode|dav|1.0.3
vscode-shell-snippets|Dee|0.2.0
githistory|don|0.4.6
vscode-babel-coloring|dza|0.0.4
vsc-material-theme|Equ|30.0.0
masontidy|eri|1.0.0
prettier-vscode|esb|3.11.0
git-project-manager|fel|1.7.1
shell-format|fox|6.1.3
sublime-search-vscode|gar|0.0.1
fuzzysearch|gay|0.2.1
vscode-lua|gcc|0.1.2
monkey-c|ghi|0.3.1
fish|gio|0.0.4
CppSnippets|har|0.0.14
vscode-perl|hen|1.17.0
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.14.14
sublime-babel-vscode|jos|0.2.10
Lua|key|0.0.9
ccpp-extension-pack|Leo|0.3.0
cmake-tools-helper|mad|0.2.1
bash-ide-vscode|mad|1.3.3
vscode-language-babel|mgm|0.0.25
git-graph|mhu|1.19.1
xml-format|mik|1.0.2
perl-debug|mor|0.6.3
python|ms-|2019.10.41019
cmake-tools|ms-|1.2.2
cpptools|ms-|0.26.2-insiders3
material-icon-theme|PKi|3.9.2
java|red|0.53.1
reloaded-cpp|rel|0.1.9
format-html-in-php|rif|1.6.1
bash-debug|rog|0.3.6
text-marker|ryu|1.11.0
vscode-javascript-booster|sbu|0.11.0
perl6-lsp|scr|0.3.0
vscode-extjs|Sen|1.0.2
bash-beautify|sha|0.1.1
incremental-search|sie|0.2.1
lua|sum|0.14.5
autocomplate-shell|tru|0.1.1
cmake|twx|0.0.17
html-mason|via|1.0.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.20.0
JavaScriptSnippets|xab|1.7.2
plsql-language|xyz|1.8.2
cpp-quick-start-snippet-for-beginners|yyx|1.0.1

(20 theme extensions excluded)

</details>

**Comment by guolisen** [comment]
![image](https://user-images.githubusercontent.com/1932457/69841109-eedcd400-1298-11ea-9b34-72cfe291e08f.png)

**Comment by jrieken** [comment]
It looks like the extension providing the outline uses the fully qualified name. It should use the containerName/detail property

**Comment by sean-mcmanus** [comment]
@jrieken Our C/C++ extension shows "base::sub" syntax when that is what is used in the code -- C++ allows class method definitions to be defined outside of the class itself. The "base::" part may not even be defined in the file at all, so there would be no symbol/type for it in the file, so clicking on it in the Outline view wouldn't really make sense unless we created some artificial placeholder symbol -- is that what you recommend we do? In the cases where the definition is lexically inside of the class definition, then it uses the containerName/detail property (except when a bug occurs, such as with template classes, which I think we have a fix for).

E.g. the code
```
namespace foo {
void bar::func(){}
}
```
Will shows a symbol like 
```
foo
> bar::func
```
And "bar" is not a "document symbol".

**Comment by jrieken** [comment]
Yeah, my recommendation is to use the details or containerName property (depending on what type you use). So the `bar::func` symbol could be shown as as `func  bar`.

**Comment by guolisen** [comment]
@jrieken

actually, I think add the scroll bar is better, because 'func base1 base2....' also has problem.

setValue ObjjjjjjjjjjjjjjjjjjjjjectNamespace::ObjjjjjjjjjjjjjjjjjjjjjectNamespace::type1
setValue ObjjjjjjjjjjjjjjjjjjjjjectNamespace::ObjjjjjjjjjjjjjjjjjjjjjectNamespace::type2
.....

the 'type1‘ will be covered by dialog......
