### ISSUE TITLE
Able to set hot key to trigger "Source Actions" directly

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode#85799]
As reqeusted in redhat-developer/vscode-java#1166, we need to be able to have a hot key to trigger "Srouce Actions" directly. Now it's in the context menu and users need to click it to show the source action options. But we couldn't find the entry in the hot key map and assign a key to it.

![image](https://user-images.githubusercontent.com/16755094/69846109-f5c21180-12ad-11ea-86a8-5e053c4f5e83.png)

To enable that, we probably need a command entry, e.g. `editor.action.sourceActions`, as we already have `editor.action.refactor`, `editor.action.quickFix`, etc.

**Comment by mjbvz** [comment]
There is already a command for this: `editor.action.sourceAction`.

@sandy081 I don't know why this doesn't show in the visual keybindings editor. Here's the definition: https://github.com/microsoft/vscode/blob/7d179d04aee96928fe2a41683943b416e942d169/src/vs/editor/contrib/codeAction/codeActionCommands.ts#L305

Assigning you

**Comment by sandy081** [comment]
/duplicate

Because it has args and currently commands with args are not shown.

**Comment by akaroml** [comment]
> /duplicate
> 
> Because it has args and currently commands with args are not shown.

Is there a number of the duplicated issue?

**Comment by fyeeme** [comment]
as @mjbvz  says add  code in keybindings.json, then works.

```json
 {
        "key": "cmd+.",
        "command": "editor.action.sourceAction",
        "when": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
    },
```
after then , also can search in  visual keybindings editor.
![image](https://user-images.githubusercontent.com/6078758/70044548-8aee3e80-15fd-11ea-9b1e-c3e51a0d1938.png)
![image](https://user-images.githubusercontent.com/6078758/70044569-95103d00-15fd-11ea-9e96-77f226d161af.png)

@akaroml  @mjbvz  many thanks.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/84072
