### ISSUE TITLE
Allow to have scoped instantiation service per editor slot

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8579]
For:
* scoped keybinding service
* scoped progress service

For the title area and the editor itself. This requires a common parent (or the editor-container itself) to be reparented instead of the editor moving around.

Enables more scenarios around menu and command contributions for contexts.

**Comment by bpasero** [comment]
@jrieken I merged this to master: title container, editor container, progress bar widget and the instantiation service are now within a new container that gets reparented when a) you move an editor around or b) you close editor group LEFT when LEFT | RIGHT exist and RIGHT becomes LEFT as well as for when you have 3 editors open and you close the left or center group.

Is there a way to verify this works for the scenario you disabled late before we finished June milestone? I remember you reverted a commit and I am not sure if this can be now reverted back again.

**Comment by jrieken** [comment]
I can verify

**Comment by jrieken** [comment]
LGTM - will push the revert revert commit

**Comment by Tyriar** [comment]
Verified via https://github.com/Microsoft/vscode/issues/9693
