### ISSUE TITLE
Display command name in the status bar after a keybinding

### ISSUE THREAD

**Issue by amgalan81mn** [microsoft/vscode#85790]
when pressed second key then display command name for short time
ctrl+k was pressed, waiting for second key of chord... "code folding -> collapsed to level 2"

**Comment by gjsjohnmurray** [comment]
Please clarify. Are you reporting a bug? Or requesting an enhancement?

**Comment by sandy081** [comment]
Why is it only for chord keys but also for all keys?

**Comment by amgalan81mn** [comment]
requesting an enhancement, just display what kind of combination pressed,
the name of it.

**Comment by alexdima** [comment]
I have tried out the changes in PR #86524, but I have to be honest and say that I personally don't find this a useful addition to VS Code, it does not feel natural to me for the status bar to constantly echo and repeat the action I executed.

Are there other editors that do what is proposed here?

**Comment by vincentfiestada** [comment]
I assume this is trying to achieve some vim-like features around keybindings? But I agree that this doesn't seem very useful. 

1. If I use a keybinding, I probably already knew what it was going to do.
2.  If not, it may have been by accident, in which case should the command stay in the status bar long enough for me to notice? What if I accidentally use 2 keybindings in a row, then this feature doesn't help me at all. And wouldn't most users simply notice the accidental change and undo?
3. This doesn't help with feature discovery, unlike the command palette.

At the very best, this seems out-of-scope and should be implemented by an extension instead.

**Comment by gjsjohnmurray** [comment]
I concur with @alexdima and @vincentfiestada

If the goal is to answer the question, "hey, what did I just do there?" perhaps add a new OutputChannel, logging each command that gets executed. Then the interested user can view this in the Output tab of the Panel.

**Comment by alexdima** [comment]
> If the goal is to answer the question, "hey, what did I just do there?" perhaps add a new OutputChannel, logging each command that gets executed. Then the interested user can view this in the Output tab of the Panel.

This already happens. When using the trace log level, each executed command is logged.

I have also presented this issue in today's standup and there was unanimous agreement that we don't want this feature, so I will close this issue for now as "out-of-scope".
