### ISSUE TITLE
Debugger sometimes not used config launch.json

### ISSUE THREAD

**Issue by luthfikw** [microsoft/vscode#85795]
Issue Type: <b>Bug</b>

i've 3 directory inside project
when first time open the project, debugger working properly
but after i've added some directory on the project, debugger not working with launch config

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|16.00GB (4.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|2.0.2
Bookmarks|ale|10.6.0
bracket-pair-colorizer|Coe|1.0.61
EditorConfig|Edi|0.14.2
vscode-projects-plus|fab|1.23.2
shell-format|fox|6.1.3
todo-tree|Gru|0.0.162
colored-regions|mih|0.0.3
dotenv|mik|1.0.1
Go|ms-|0.11.9
vsliveshare|ms-|1.0.1293
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
trailing-spaces|sha|0.3.1
vscode-ruby|win|0.26.0
material-theme|zhu|3.1.2
vscode-proto3|zxh|0.3.0

</details>

**Comment by sandy081** [comment]
Can you please let us know what debugger are you using?

**Comment by luthfikw** [comment]
i am using golang, go debugger @sandy081 

https://github.com/Microsoft/vscode-go

**Comment by sandy081** [comment]
ok please file the issue against the go extension.
