### ISSUE TITLE
Have Keyboard Shortcuts To Navigate to Previous View When Using Go to Definition, etc.

### ISSUE THREAD

**Issue by j-a-lewis** [microsoft/vscode#85791]
Right now, if I use GO TO DEFINITION, there is no way to jump back to my code starting point (I'm an ignorant newbie).  It would be nice to have a keyboard shortcut to do that, also to be able to open the  item definition location in a new window, retain the old location in the current window, as an option, too.  Apologies if one can already do this but I looked at Keyboard Shortcuts and did not see this option.  Would be good if the option worked across files in a workspace.

**Comment by aNickzz** [comment]
The command "Go Back" is bound to `Alt + LeftArrow` by default (on windows). You can also use mouse buttons 4 and 5, if you have them.

The command "Open Definition to the Side" is bound to `Ctrl + K F12` too, and I've just found that it appears to work with `Alt + Ctrl + LeftClick` (rather than just `Ctrl + LeftClick` for "Go to Definition").

**Comment by j-a-lewis** [comment]
Thanks!  Looks like I need to actually carefully study the Visual Study Keyboard Shortcuts PDF file.  Perhaps searching for items in the PDF rather than try to skim read for them would help old geezers like me!  https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by aNickzz** [comment]
There are a _lot_ of keyboard shortcuts and commands you can bind in VSCode. I don't think any one person could know more than half of them. My keybindings.json is over 500 lines long, and that only includes bindings I've changed. 😅

**Comment by j-a-lewis** [comment]
Thanks for the further hint.  Sounds great.  I've noticed the customizability of Code but haven't taken advantage of it the way I should.
