### ISSUE TITLE
I can't see code hint in dart document after vscode update

### ISSUE THREAD

**Issue by youchen12138** [microsoft/vscode#85796]
Issue Type: <b>Bug</b>

## my solution

I use BaiDu search when I catch this issue. I want to solve the issue in myself. [one of the solution](https://blog.csdn.net/u014239709/article/details/96909682). I can't solve the issue according to that solution. then I reset my computer. And add 
 document of dart to working area again. But I still can't solve the issue. I only search the solution because material of flutter.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.4.4
vscode-html-css|ecm|0.2.3
code-runner|for|0.9.15
vscode-atom-javascript-snippet|glu|0.2.1
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
HTMLHint|mka|0.6.0
vscode-filesize|mkx|2.1.3
vscode-language-pack-zh-hans|MS-|1.40.2
cpptools|ms-|0.26.1
js-atom-grammar|ms-|0.1.14
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.0
html5-boilerplate|sid|1.0.3
easysass|spo|0.0.6
es6-mocha-snippets|spo|0.2.2
guides|spy|0.9.3
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.6.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please explain the issue you are seeing? Is this caused by an extension? Can you repro this issue by disabling all extensions.
