### ISSUE TITLE
Head bug

### ISSUE THREAD

**Issue by lizhaono123** [microsoft/vscode#85794]
Full screen bug。
![image](https://user-images.githubusercontent.com/37563737/69841137-0f0c9300-1299-11ea-9cf0-c84cc49d4b25.png)
![image](https://user-images.githubusercontent.com/37563737/69841199-43804f00-1299-11ea-810b-40c0ec0675bb.png)

**Comment by gjsjohnmurray** [comment]
Please update to 1.40.2 and retest

**Comment by lizhaono123** [comment]
> Please update to 1.40.2 and retest

No such bug in version 1.40.2
