### ISSUE TITLE
VS code launch problem

### ISSUE THREAD

**Issue by MugeshBTech** [Microsoft/vscode#8580]
- VSCode Version:v1.2.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. I have closed all the chrome instance and then i have tried, still not working
2. Then i have tried directly from chrome using F5 button
3. I don't know how to open the port using command prompt 
4. Can anyone help me on this
![image1](https://cloud.githubusercontent.com/assets/16976667/16496242/a48f3dcc-3f0e-11e6-9ca2-7a5aee0560d3.png)
![image2](https://cloud.githubusercontent.com/assets/16976667/16496243/a4a1822a-3f0e-11e6-9761-b7744f860c4c.png)

**Comment by bpasero** [comment]
@MugeshBTech are you using an extension? Are you launching a server on F5? I am having issues understanding in what area of Code there is a bug.

**Comment by joaomoreno** [comment]
@bpasero Just assigning to get an owner on this, but fwd if necessary.

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
