### ISSUE TITLE
VSCodeInsider_Settings_AI4D : (Code - Insiders/text '') The Name property must not contain any characters in the private Unicode range.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/vscode#85807]
The following accessibility issue needs investigation.

**App:** Code - Insiders

**Steps to Reproduce**
1. Launch Visual Studio Code application.
2. Navigate to the "Settings" button in the left navigation bar and select "Settings" from the flyout that appears. 
3. Select the "Extensions" option under the "Commonly Used" setting and expand.
4. Select any of the extensions from the list then details would appear at the right. 
5. Launch the AI4D and inspect the right panel.

**Element path:** text ''

**Issue Details:** The Name property must not contain any characters in the private Unicode range. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Modify the Name property, removing all characters in the range U E000 to U F8FF and replace them with meaninful, standard text content.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Attachment:**
![VSCodeInsider_Settings_AI4D  (Code - Insiderstext '') The Name property must not contain any characters in the private Unicode range](https://user-images.githubusercontent.com/52036772/69850702-da530880-12a5-11ea-99ac-2199fd9748eb.png)

**Comment by roblourens** [comment]
This is a false positive. The content of that element is a character for a custom font that shows an image, so there is no text content. I see the same warning all over the app.
