### ISSUE TITLE
Debug Electron , But electron can not start up

### ISSUE THREAD

**Issue by leosx** [microsoft/vscode#85809]
- VSCode Version:1.40.2
- OS Version:win10 18362.267

Steps to Reproduce:

1.config launch.json
{
            "type": "node",
            "request": "launch",
            "name": "UI debug",
            "cwd": "${workspaceFolder}/Client",
            "runtimeExecutable": "${workspaceFolder}/Client/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceFolder}/Client/node_modules/.bin/electron.cmd"
            },
            "env": {
                "env_mode": "development"
            },
            "args": ["."],
            "program": "${workspaceFolder}/Client/main.js"
        }

2.press F5 to start debug

Question:
sometimes , Press F5 can start debug electron. sometimes  vs code show started debug, in fact  electron not start up, then need restart vs code, it can be debug electron success.After several times of continuous debugging, it failed to start again.Causing me to restart vscode again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Do you see any error message when that happens? Is there still an Electron process from a previous run open in the background?

**Comment by leosx** [comment]
ERR can not find file(s:\127.0.0.1): Error: can not find file (s:127.0.0.1)   log.ts:196 .....



399432882@qq.com
 
From: Rob Lourens
Date: 2019-12-06 07:15
To: microsoft/vscode
CC: leosx; Author
Subject: Re: [microsoft/vscode] Debug Electron , But electron can not start up (#85809)
Do you see any error message when that happens? Is there still an Electron process from a previous run open in the background?

**Comment by roblourens** [comment]
Where doy ou see that error? I don't understand it, it sounds like it might be coming from your app, not from vscode.

**Comment by leosx** [comment]
this error come from vs code developer  devtool.  my project has no this js file.



399432882@qq.com
 
From: Rob Lourens
Date: 2019-12-07 00:45
To: microsoft/vscode
CC: leosx; Author
Subject: Re: [microsoft/vscode] Debug Electron , But electron can not start up (#85809)
Where doy ou see that error? I don't understand it, it sounds like it might be coming from your app, not from vscode.

**Comment by weinand** [comment]
@roblourens I've investigated and found the "ERR can not find file(s:\127.0.0.1)" error and created 
https://github.com/microsoft/vscode/issues/86587.
