### ISSUE TITLE
The detached account doesn't auto disappear from the view 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode#85805]
- VSCode Version:1.41.0-insider (user setup)
- OS Version :Windows_NT x64 10.0.18363
- Commit: d20be77af2fd4bf460b7c993fa32011f6f8d9081

Steps to Reproduce:

1. Create a Cosmos DB account  --> Attach this account with connection string.
2. Detach this account --> Check whether the account auto disappears or not.

**Expect:**
The detached account auto disappears from the view.

**Actual:**
The detached account doesn't auto disappear from the view.
![image](https://user-images.githubusercontent.com/34729092/69848283-9fa49c80-12b4-11ea-90cf-74b4e0a17b37.png)

**More Info:**
1. The detached account doesn't list when executing "Cosmos DV: Detach" again.
2. The detached account still lists after refreshing the Attached Database Accounts panel.
3. The detached account disappears after re-opening VS Code. 
4. This issue doesn't reproduce before updating VS Code Insiders.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
This issue appears to be about the extension whose repo is at https://github.com/microsoft/vscode-cosmosdb

Please report it there, even though you are only seeing it in VS Code Insiders. The extension developers are best able to determine if it is a problem with Insiders or if the extension needs fixing.

**Comment by v-dantch** [comment]
Hi @gjsjohnmurray , it seems an issue of the **latest** VS Code Insiders. This issue doesn't reproduce **before** updating to the latest VS Code Insiders.

**Comment by v-dantch** [comment]
Meanwhile , this issue doesn't reproduce on VS Code(not Insiders).

**Comment by gjsjohnmurray** [comment]
> 
> 
> Hi @gjsjohnmurray , it seems an issue of the **latest** VS Code Insiders. This issue doesn't reproduce **before** updating to the latest VS Code Insiders.

I understand that. But I still think the extension devs are the ones to pinpoint what is going wrong.

**Comment by sandy081** [comment]
Please file this issue against the cosmos-db extension.
