### ISSUE TITLE
[json] Outline Failed to Display Complete Items of a Long/Big JSON File

### ISSUE THREAD

**Issue by noisnemid** [microsoft/vscode#85804]
Issue Type: <b>Bug</b>

As the json file size growing, the outline view does not behave normally.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763
[dump.zip](https://github.com/microsoft/vscode/files/3904006/dump.zip)

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|1.0.21
json-tree-view|Cha|2.6.0
vbscript|Dar|1.0.4
vscode-eslint|dba|1.9.1
vscode-highlight|fab|1.3.4
restructuredtext|lex|116.0.0
vscode-language-pack-zh-hans|MS-|1.40.2
python|ms-|2019.11.50794
vscode-table-formatter|shu|1.2.1
code-spell-checker|str|1.7.20
open-in-browser|tec|2.0.0
crs-al-language-extension|wal|1.1.21

</details>

**Comment by aeschli** [comment]
There's a limit of 500 symbols we show. It seems the JSON language server hits the limit but doesn't send any results for that example.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-json-languageservice/commit/7e006ef38993fb332f0916020cfc9c896e1f77bf

Also there's now a setting `json.maxItemsComputed` to configure the limit.
