### ISSUE TITLE
VSCodeInsider_Settings_Keyboard : The "More Actions" control is not keyboard actionable.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/vscode#85808]
**Evironment Destails**
- VSCode Version: 1.41.0-insider (user setup)
- OS Version: Win10

**Steps to Reproduce:**
1. Launch Visual Studio Code application.
2. Navigate to the "Settings" button in the left navigation bar and select "Settings" from the flyout that appears. 
3. Select the "Extensions" option under the "Commonly Used" setting and expand.
4. Select any of the extensions from the list then details would appear at the right. 
5. Navigate to the panel and try to access the "More Action" control using a keyboard.

**Actual:**
Issue 1:
When keyboard users navigate using the "Tab" through the panel which appears on activating any of the extension from the list the "More Action" control present for each section is not keyboard actionable.

Issue 2:
The tooltip that available on the "More Action" control is not accessible for keyboard users nor for the screen reader users.

**Expected:**
Issue 1:
The "More Action" control should be keyboard actionable when keyboard users navigate using the "Tab" key.

Issue 2:
For keyboard users, the tooltip should be available when the "More Action" control receives keyboard focus and for screen reader users the tooltip should be announced when they navigate to the "More Action" control.

**User Impact:**
Issue 1:
If any control that is available on the screen and on activating it some action takes place but it is not actionable using keyboard then the keyboard users will not be able to access the information that is available on that control.

Issue 2:
If the tooltip content is not available on keyboard focus then the information that is available for the mouse user will not be provided for the keyboard users.

**Attachment:**
[VSCodeInsider_Settings_Keyboard  The More Actions control is not keyboard actionable..pptx](https://github.com/microsoft/vscode/files/3904098/VSCodeInsider_Settings_Keyboard.The.More.Actions.control.is.not.keyboard.actionable.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
You can trigger this button with `shift+f9`. We can't make it a tabstop because that will make tabbing through the settings editor basically impossible.
