### ISSUE TITLE
VSCodeInsider_Settings_AI4D : Inappropriate toolbar structure provided for the "More Actions" control.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/vscode#85812]
**Evironment Destails**
- VSCode Version: 1.41.0-insider (user setup)
- OS Version: Win10

GitHubTags: #A11yMAS; #A11yTCS; #Win32; #DesktopApp; #A11y_VSCodeEditor; #MAS4.1.2; #A11ySev2; #Benchmark

**Steps to Reproduce:**

1. Launch Visual Studio Code application.
2. Navigate to the "Settings" button in the left navigation bar and select "Settings" from the flyout that appears.
3. Select the "Extensions" option under the "Commonly Used" setting and expand.
4. Select any of the extensions from the list then details would appear at the right.
5. Launch the AI4D and inspect the content with the panel.

**Actual:**
The "More Actions" control is structured in a toolbar which is not appropriate as this control is a menu item and the toolbar is structured for a set of buttons.

**This issue is observed in both the screen readers i.e. JAWS and NVDA.**

**Expected:**
The "More Actions" control should not be structured in a toolbar and it should not be announced for screen reader users.

**User Impact:**
If any content is not structured properly then the screen reader users will have difficulty in understanding the content present on the screen.

**Attachment:**
![VSCodeInsider_Settings_AI4D  Inappropriate toolbar structure provided for the More Actions control](https://user-images.githubusercontent.com/52036772/69857931-f4491700-12b6-11ea-875e-92655598507c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It's essentially a toolbar with one button in it. It's the same as all other "..." type toolbar overflow menus. I'll see if there's a way to simplify it though.

**Comment by sana-ajani** [comment]
@roblourens @isidorn is there something we want to do here? This issue is out of SLA so we need to report an update back to the accessibility team.

**Comment by isidorn** [comment]
Settings editor has been restructured. We did not get negative user feedback regarding this.
Closing as no longer applicable / will not fix
