### ISSUE TITLE
Error of syntax highliting when recognizing __invert__ operator in python

### ISSUE THREAD

**Issue by artemshadrunov** [microsoft/vscode#85810]
Hi! I'm using vscode for `python` and found a problem.

I wrote something like:
```
from elasticsearch_dsl import Q

def missing(field: str) -> Q:
    return ~Q('exists', **{'field': field})
```
vscode highlights the `~` symbol with error `bad operand type for unary ~: strpylint(invalid-unary-operand-type)`. But I can run this code and it works just fine.
![Screenshot_2](https://user-images.githubusercontent.com/18066169/69856254-4762a000-129e-11ea-887a-5827f36ca292.jpg)

**Comment by aNickzz** [comment]
The error message seems to think the return type of `Q()` is a string, can you confirm that is correct? Or perhaps you can cast return value into the type required before applying `~`.

**Comment by artemshadrunov** [comment]
`Q()` returns specific type for `elasticsearch_dsl` query, it is definitely not a string. And this type(s) contains overload for `__invert__`, so I don't need to cast it to something else.

**Comment by mjbvz** [comment]
Please file this issue against the python extension
