### ISSUE TITLE
Open preview action on a markdown file opens the preview again if it is already opened in a different editor group

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8581]
- VSCode Version: a21c12346f388e51858c930875ca30968604c116
- OS Version: OSX

Steps to Reproduce:
1. Tabs enabled
2. Open a markdown file
3. Right click on the tab and open Preview
4. Drag and drop the opened preview into a second editor group
5. Right click on the preview tab and open source
6. Note that it makes already opened markdown file as active
7. Now again right click on the markdown tab and open Preview

Expected: It makes already opened preview as active
Actual: It opens new Preview tab next to it

**Comment by mjbvz** [comment]
Currently blocked by #14483 on implementing this

**Comment by mjbvz** [comment]
Fixed by #44307

**Comment by ramya-rao-a** [comment]
Running the command `Markdown: Open Preview` still opens another preview if one exists in another editor group

**Comment by mjbvz** [comment]
Sorry, misread the repo instructions. This behavior is actually by-design. `Open Preview` always opens the preview in the current group. `Open preview to side` always opens it to the side of the current group. There should only ever be a single preview of a document in a given group at a time
