### ISSUE TITLE
Adopt extension kind for those extensions defined as ui extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#85819]
Adoption for #85036

## Background

- As of 1.40 the `extensionKind` attribute can be an array, pls see the [documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location).
- We will be deprecating the `string` type for `extensionKind` property in favour of `string array` type to cause less confusions and the new `extensionKind` must be adopted.

## Adoption

If you have an extension with the `extensionKind` set to `"ui"`, then you must change the extension kind to:
- **["ui"]** - when the extension only runs locally in the local extension host and does **not** run in a remote context. For example, extensions contributing a `resolver`can only run locally.
- **["ui", "workspace]** - when the extension can run both locally and remotely, but locally is preferred. For example, personalisation extensions like key bindings can run both locally and remotely, but if the extension is already installed locally it will be used.

##  Details about the New Format & Behaviour 

| Kind \ Runtime      | Desktop - Local | Desktop - Remote     | Web - Remote     |
| :---        |    :----:   |          :----:   |   :----:  |
|    ["ui"]  |  ✔️        | ❌    | ❌    |
| ["workspace"]   | ❌        | ✔️     | ✔️   |
| ["ui", "workspace"]   | ✔️       | ✔️     | ✔️   |
| ["workspace", "ui"]   | ✔️       | ✔️     | ✔️   |

**["ui"]**:  Runs only locally.
**["workspace"]**:  Runs only remotely.
**["ui", "workspace"]**:  Preferably runs locally if exists otherwise can run remotely.
**["workspace", "ui"]**:  Preferably runs remotely if exists otherwise can run locally.

## Adoption Tracking

Please go through the extensions listed below and adopt your extension to use the new array format correctly as per above table.

- [x] Git UI Extension `git-ui` - @chrmarti 
- [x] Image Preview Extension `image-preview` - @mjbvz  
- [x] Remote Containers Extension `ms-vscode-remote.remote-containers` **["ui"]**- @chrmarti
- [x] Remote SSH Edit Extension `ms-vscode-remote.remote-ssh-edit` **["ui"]**- @roblourens 
- [x] Remote SSH Extension `ms-vscode-remote.remote-ssh` **["ui"]**- @roblourens  
- [x] Remote WSL Extension `ms-vscode-remote.remote-wsl` **["ui"]**- @aeschli 
- [x] Remote Development Extension Pack `ms-vscode-remote.vscode-remote-extensionpack` **["ui"]** - @roblourens  @aeschli @chrmarti 
- [x] Notepad++ Keymap Extension `ms-vscode.notepadplusplus-keybindings` **["ui", "workspace"]** - @chrisdias   
- [x] Sublime Keymap Extension `ms-vscode.sublime-keybindings` **["ui", "workspace"]** - @chrisdias   
- [x] Debugger for Chrome Extension `msjsdiag.debugger-for-chrome` **["ui"]** - @roblourens 
- [x] Debugger for Edge Extension `msjsdiag.debugger-for-edge` **["ui"]** - @roblourens 
- [x] Test Resolver `vscode-test-resolver` **["ui"]** - @aeschli    

@alexandrudima FYI

**Comment by RMacfarlane** [comment]
@chrmarti Correct me if I'm wrong, but the Azure Account Extension is currently a workspace extension and various other workspace extensions depend on it (Docker, Azure functions). Since it doesn't set `extensionKind` to `ui`, I'm going to remove it from the list

**Comment by sandy081** [comment]
Ping @chrisdias and @mjbvz

**Comment by mjbvz** [comment]
I already adopted this in the image-preview with https://github.com/microsoft/vscode/commit/b0fb9f17da7b34ab122d9308c497b900fbe3cada

**Comment by chrisdias** [comment]
updated extensions and published to marketplace.

**Comment by chrisdias** [comment]
uh wait :) @sandy081 why would my keymap extensions be `workspace` as well as `ui`?

**Comment by chrisdias** [comment]
done

**Comment by sandy081** [comment]
Great. Thanks guys.
