### ISSUE TITLE
suggest.completeFunctionCalls without parameters signature

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#85816]
It would be cool to have `suggest.completeFunctionCalls` to complete without parameters signature. It could be the same setting or introduce a new one.

**without parameters signature** (existing setting)
`"javascript.suggest.completeFunctionCalls"`
`"typescript.suggest.completeFunctionCalls"`

**with parameters signature** (new setting)
`"javascript.suggest.completeFunctionCallsWithParameters"`
`"typescript.suggest.completeFunctionCallsWithParameters"`

/cc @mjbvz

**Comment by mjbvz** [comment]
Can you provide an example use case?

Maybe I'm misunderstanding, but if all this is is inserting `()`, you can press `(` to accept the current suggestion and—provided auto closing is enabled—it will add the closing `)` too.
