### ISSUE TITLE
Code block is not rendered properly in extension details

### ISSUE THREAD

**Issue by AkiraMiyakoda** [microsoft/vscode#85815]
**Description**:
A code block in README.md of an extension is not rendered properly in the Extension Details tab if it contains a blank line. 

README.md of [my extension](https://marketplace.visualstudio.com/items?itemName=akiramiyakoda.cppincludeguard) has a code block which contains a blank line. Here is the real example:
```C
/**
 * Copyright (c) 2019 Akira Miyakoda
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

#ifndef FOO_BAR_UTILS_H     // <- Inserted here.
#define FOO_BAR_UTILS_H
```
The code block is rendered like this in the extension details tab (the last two lines appear outside the block):
![codeblock](https://user-images.githubusercontent.com/30318985/69863421-17d48780-12e0-11ea-8259-e8ff02a6eade.PNG)

Oddly enough, it looks fine in the Markdown Preview of VSCode.

**Enviroment**:

- VSCode Version: 1.40.2
- OS Version: Windows10 1903  x64

**Steps to Reproduce**:

1. Search the marketplace for my extension named "C/C++ Include Guard" in VSCode.
2. Look at the bottom of its details.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is an upstream issue with marked: https://github.com/markedjs/marked/issues/849

[self contained example](https://marked.js.org/demo/?text=*%20list%0A%60%60%60%0Acode%0A%0Amore%0A%60%60%60%0Atext&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

To workaround, add a newline before the code block:

~~~md
* list

```
code

more
```

~~~
