### ISSUE TITLE
Minimap selection slows down scrolling considerably

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#85817]
1. Open https://github.com/microsoft/TypeScript/blob/master/src/compiler/checker.ts in vscode
2. Wait a bit for it to be tokenized. Select whole file -> start scrolling -> it is very slow
3. Now disable minimap and od the same -> it is fast

fyi @alexandrudima @jrieken 

Gif might not capture this the best, but here it is.

![minimap](https://user-images.githubusercontent.com/1926584/69865121-af19ea80-12a0-11ea-8450-8840a694cd9b.gif)

**Comment by connor4312** [comment]
Verifiers: ensure decorations in the minimap are rendered correctly, and test that scrolling is smooth in the file that Isi linked

**Comment by isidorn** [comment]
I will verify this. Thanks
