### ISSUE TITLE
VSCodeInsider_SettingsAI4D : Inappropriate treeview structure provided for the content in the panel.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/vscode#85811]
**Evironment Destails**
- VSCode Version: 1.41.0-insider (user setup)
- OS Version: Win10

**Steps to Reproduce:**

1. Launch Visual Studio Code application.
2. Navigate to the "Settings" button in the left navigation bar and select "Settings" from the flyout that appears.
3. Select the "Extensions" option under the "Commonly Used" setting and expand.
4. Select any of the extensions from the list then details would appear at the right.
5. Launch the AI4D and inspect the content with the panel.

**Actual:**
Issue 1:
The "CSS" text and sections such as "Completion: Complete Property With Semicolon", "Completion: Trigger Property Value Completion", etc. is structured in treeview which is not appropriate. 

Issue 2:
Since the sections in the panel are structured as treeview the screen reader users are unable to access the content within the panel properly as this has affected the normal keyboard navigation for the screen reader users.

**This issue is observed in both the screen readers i.e. JAWS and NVDA.**

**Expected:**
Issue 1:
The "CSS" text should be announced as header element and the sections such as "Completion: Complete Property With Semicolon", "Completion: Trigger Property Value Completion", etc.  should not be announced as treeview structure for screen reader users.

Issue 2:
Screen reader users should be able to access all the content in the panel using the normal keyboard navigation.

User Impact:
Issue 1:
If any content is not structured properly then the screen reader users will have difficulty in understanding the content present on the screen.

Issue 2:
If the screen reader users are unable to access the content on the screen then they might miss out some information that is available for other users.

**Attachement:**
![VSCodeInsider_SettingsAI4D  Inappropriate treeview structure provided for the content in the panel](https://user-images.githubusercontent.com/52036772/69856468-bb5b7300-12b3-11ea-83d1-819371ab0a53.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you explain what you mean by `the normal keyboard navigation.`? Tabbing, etc, should all work fine here.

This content is effectively a tree, although the sections are non-collapsible.
