### ISSUE TITLE
After each new release JS error occur

### ISSUE THREAD

**Issue by vmunisamy** [microsoft/vscode#85825]
Just launching vs code crashes each time their is a new release : 

![Screenshot_19](https://user-images.githubusercontent.com/27403337/69870132-5cecbf80-12c8-11ea-93bb-52f6ea4cc6e3.png)

**Comment by deepak1556** [comment]
Missing main package, very likely incomplete update download.

@vmunisamy does this happen with every update on your machine ?

/cc @joaomoreno thoughts on how to debug this further wrt updates ?

**Comment by joaomoreno** [comment]
It's hard to debug, the issue was indeed caused by a broken update. @vmunisamy did you get any errors while updating?
