### ISSUE TITLE
Stuck At Downloading Omnisharp and components

### ISSUE THREAD

**Issue by GhostLeader37** [microsoft/vscode#85827]
- VSCode Version:1.40.2
- OS Version: Windows 8.1 6.3 (Build 9600)

Steps to Reproduce:

1.uninstall reintstall (still stuck at downloading omnisharp and components)
2.switch to insider version (still stuck at downloading omnisharp and component)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
What is stuck at downloading? Is it downloading newer version of VS Code?

**Comment by GhostLeader37** [comment]
> What is stuck at downloading? Is it downloading newer version of VS Code?

It stuck at download omnisharp and some components which needed for C/C++ extension
(Sorry i forgot to mention omnisharp and component)

**Comment by sandy081** [comment]
Please file issue against the omnisharp extension
