### ISSUE TITLE
Suggestion is not highlighted

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#85826]
I'm not sure what would be special about that particular suggestion, but it doesn't receive the same blue highlight like the others.

This happened while working today, unfortunately I cannot point to a specific commit to reproduce on because I haven't saved the work yet...

![image](https://user-images.githubusercontent.com/5047891/69870823-63bc0800-12b1-11ea-9a5e-50651d6390f3.png)

**Comment by jrieken** [comment]
@alexandrudima  Please press `comand+space` for showing details, and then press `cmd+?` for the explainer

**Comment by alexandrudima** [comment]
Here is the information:

![image](https://user-images.githubusercontent.com/5047891/69876288-81906980-12bf-11ea-883d-bf32f5f9fd4b.png)

**Comment by jrieken** [comment]
I have a unit test and this 🤔 

<img width="904" alt="Screenshot 2019-11-29 at 16 06 11" src="https://user-images.githubusercontent.com/1794099/69877320-2b70f580-12c2-11ea-8c92-c1c2ef4c1f1c.png">

**Comment by alexandrudima** [comment]
I'm sorry I can no longer reproduce ... The problem is that I am in the middle of a large refactoring so I haven't saved my state.

I will reopen once I have good steps.

**Comment by jrieken** [comment]
Yeah, maybe a rendering glitch in how we reuse the highlight labels...
