### ISSUE TITLE
Adding space after bitwise operators option also adds spaces after increment/decrement operators in loops

### ISSUE THREAD

**Issue by baybal** [microsoft/vscode#85823]
- VSCode Version: 1.40.2
- OS Version: 5.3

Steps to Reproduce:

1. Enable javascript.format.insertSpaceBeforeAndAfterBinaryOperators
2. Try to format a js file with ++ operator in a for loop declaration. VSCode will try to inset space after ++, thinking of it as a bitwise operator.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share example code. This does not repo for me with (the formatting remains unchanged):

```js
for (let i = 0; ++i; i++) { }
```

**Comment by baybal** [comment]
```
for (var i = 6, ii = 2; i < s.length; ii++ , i++) {
}
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/35474 to track upstream
