### ISSUE TITLE
Can't add a specific second folder to a new workspace

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#85821]
Easy repro on Linux, both dev and Insiders, with very specific file paths. Create these two directories:

- `/home/joao/tmp/sample/a`
- `/home/joao/tmp/sample/b`

I failed to repro on macOS Insider or dev.

1. New Window
2. Add folder `a` to workspace

Already something is wrong since the explorer is empty:

![image](https://user-images.githubusercontent.com/22350/69874553-9a971b80-12bb-11ea-9b21-c774466a4c11.png)

3. Add folder `b` to workspace

![Screenshot from Fri 29 Nov 2019 12:50:31 PM CET](https://user-images.githubusercontent.com/22350/69867794-2ef78300-12a8-11ea-88c4-88799acb1671.png)

When I click `Open Workspace Configuration`, I get:

![Screenshot from Fri 29 Nov 2019 12:50:38 PM CET](https://user-images.githubusercontent.com/22350/69867799-3454cd80-12a8-11ea-88b8-4c05754f82cd.png)

When I run `Reopen with Encoding` and pick `UTF8`, I get:

![Screenshot from Fri 29 Nov 2019 12:50:53 PM CET](https://user-images.githubusercontent.com/22350/69867802-3880eb00-12a8-11ea-95a6-c94cc318ee53.png)

And then everything keeps running.

It seems the automatic encoding detection screwed up at some point. Strange that I can't repro in Insiders though.

---

Unrelated, and I haven't found a way to repro, so just FYI: once that notification was done I opened the notifications area and saw:

![Screenshot from Fri 29 Nov 2019 12:57:19 PM CET](https://user-images.githubusercontent.com/22350/69867920-90b7ed00-12a8-11ea-91f3-42a769e22041.png)

:man_shrugging:

**Comment by joaomoreno** [comment]
I can't repro in Stable.

I decided to run the `Show Workspace File` command after step 2, both stable and Insiders. This is what I got on Insiders:

![image](https://user-images.githubusercontent.com/22350/69874700-f366b400-12bb-11ea-8684-51e6554dccff.png)

**Comment by joaomoreno** [comment]
This seems to be very specific to the following workspace file which gets detected as UTF16:

```
{
	"folders": [
		{
			"path": "/home/joao/tmp/sample/a"
		}
	]
}
```

**Comment by joaomoreno** [comment]
This just seems like so many issues at once.

Debugging with @isidorn we nailed on one: tree compression seems to be causing the empty explorer.

**Comment by joaomoreno** [comment]
Empty explorer is https://github.com/microsoft/vscode/issues/85835, removing @isidorn.

**Comment by joaomoreno** [comment]
Can't repro with the exact same workspace file, when at home. :thinking: Only in the office machine...

**Comment by bpasero** [comment]
@joaomoreno I think this can be explained if you either have a non-UTF-8 encoding configured in settings or possibly auto guessing of encoding. I pushed 2 changes today:
* enforce encoding of UTF-8 for untitled workspace files (we never did that and it was luckily also reported just now as https://github.com/microsoft/vscode/issues/85870)
* do not automatically guess UTF-16/32 encodings

**Comment by mjbvz** [comment]
Verified untitled workspaces with are encoded properly for #85870 

I was not able to reproduce the original problem @joaomoreno reported. @joao Can you please handle verification

**Comment by jrieken** [comment]
@bpasero Can this be verified?

**Comment by bpasero** [comment]
@jrieken I never could

**Comment by joaomoreno** [comment]
I also couldn't verify this at home... really the only machine in which this happened was the office one. I'm pretty sure I had no encoding settings set. I'll verify once in the office.
