### ISSUE TITLE
Markdown Preview is not using complete editor space

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8583]
- VSCode Version: a21c12346f388e51858c930875ca30968604c116
- OS Version: OSX

Steps to Reproduce:

1. Make window zoom level configuration to 1. `"window.zoomLevel": 1`
2. Right click on a markdown file in Explorer view and open preview

Expected: Preview should take complete editor space
Actual: Not complete editor space is consumed

<img width="1393" alt="screen shot 2016-06-30 at 7 41 41 pm" src="https://cloud.githubusercontent.com/assets/10746682/16498201/de104bb8-3efa-11e6-939d-a8917580e9c0.png">

**Comment by jrieken** [comment]
Yeah - it's an issue with the web view that it doesn't inherit the `zoomLevel`. Closing this duplicate of #5745
