### ISSUE TITLE
Add the option to sort inside groups in explorer/context menu items.

### ISSUE THREAD

**Issue by caleteeter** [microsoft/vscode#85838]
Currently the ordering of groups is functional, however inside of groups, the ordering of context menu items falls back to the title property in the command contribution.

For instance:

In the command contributions:

**{
    "command": "contract.copyByteCode",
    "title": "Copy Constructor Bytecode",
    "category": "Azure Blockchain"
},
{
    "command": "contract.copyDeployedByteCode",
    "title": "Copy Transaction Bytecode",
    "category": "Azure Blockchain"
},
{
    "command": "contract.copyABI",
    "title": "Copy Contract ABI",
    "category": "Azure Blockchain"
},**

then in the "explorer/context" section:

**{
    "when": "resourceLangId == json",
    "command": "contract.copyByteCode",
    "group": "9_copyFromContractGroup"
},
{
    "when": "resourceLangId == json",
    "command": "contract.copyDeployedByteCode",
    "group": "9_copyFromContractGroup"
},
{
    "when": "resourceLangId == json",
    "command": "contract.copyABI",
    "group": "9_copyFromContractGroup"
},**

No matter what order the items are changed (contributes or explorer/context) the ordering inside this group will always be:

Copy Constructor Bytecode
Copy Contract ABI
Copy Transaction Bytecode.

Ideally the items inside a group could be ordered independently from the command title.  Possibly adding an additional property in the explorer/context section (e.g. order) that will be respected if added but not required (default to fall back to title name ordering inside the group).

**Comment by jrieken** [comment]
https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups
