### ISSUE TITLE
Save terminal commands history

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#85831]
Save gitbash terminal commands history on vscode exit for future sessions. 

(using windows 10 it's not available)

**Comment by Tyriar** [comment]
This is maybe happening because of how we're killing/cleaning up the process?

Not confirmed but I've seen plenty of reports for this on Windows.

**Comment by blueworrybear** [comment]
Hi, I have encountered this issue too. After studying, it seems to me that it's because how node-pty kill process.

At [windowsTerminal.ts:161](https://github.com/microsoft/node-pty/blob/f3099ad49177197203b27e9450aef7c03530c375/src/windowsTerminal.ts#L161)

```ts
public kill(signal?: string): void {
    this._defer(() => {
      if (signal) {
        throw new Error('Signals not supported on windows.');
      }
      this._close();
      this._agent.kill();
    });
  }
```
The process is force killed, therefore the shell terminates immediately and does not save history.

The possible solutions IMO may be:

1. Users set `PROMPT_COMMAND="history -a"` by themselves.
    
    This is what I do for short-term solution.

2. Send a `exit` command before pty killed.

    Maybe add below code:
    [terminalProcess.ts:190](https://github.com/microsoft/vscode/blob/718331d6f3ebd1b571530ab499edb266ddd493d5/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L190)
    ```ts
	try {
		if (this._ptyProcess) {
			this._logService.trace('IPty#kill');
			this._ptyProcess.write('exit\r\n');
			this._ptyProcess.kill();
		}
	} catch (ex) {
		// Swallow, the pty has already been killed
	}
    ````
    Not sure it's an acceptable way to solve this problem. 🤔 

Please let me know what you think. I would like to solve this issue.

**Comment by Tyriar** [comment]
@blueworrybear writing exit won't be good enough as there may not be enough time to exit gracefully before kill anyway (a race condition) and also `exit\r\n` might not do anything depending on the state of the terminal. What we really need is a way to signal the process to shutdown gracefully and kill it forcefully if it didn't happen several seconds later. Something like this but it would be better if there was a node.js API to do it (even if we need to go to C++): https://stackoverflow.com/a/6860723/1156119

**Comment by blueworrybear** [comment]
@Tyriar you are right. Sending `exit\r\n` is not a good idea. My first thought is to graceful kill the process. However, I found that I am unable to graceful kill `bash` with `taskkill`. I got an error message when I tried `taskkill /PID <pid>`. It said the process could be killed only with `/F` option. I am still looking for the solution. 😕

**Comment by SterlingButters** [comment]
@Tyriar @blueworrybear And does `PROMPT_COMMAND="history -a"` have any obvious disadvantages?

**Comment by JerryGreen** [comment]
I have this problem on windows, but I don't have it on macos

~It seems nobody's using VSCode on windows?~

**Comment by jerrygreen** [comment]
I guess mister @Tyriar doesn’t understand the problem, or can’t reproduce it, so [he thinks] he’s reasonably closing it.

As for myself, after when I’ve put `export PROMPT_COMMAND="history -a"` into one of my rc files, I kinda forgot about this problem, even though it was said it is a short term solution, - by @blueworrybear, this simple fix kinda works good long-term, negating this VSCode bug.

**Comment by Tyriar** [comment]
@Lemmingh thanks for the info, I'll add this to the terminal docs FAQ page
