### ISSUE TITLE
Sometimes Find stops working

### ISSUE THREAD

**Issue by justinhj** [microsoft/vscode#85836]
Issue Type: <b>Bug</b>

Occasionally the Find function stops working both with the keyboard shortcut key and the Edit/Find menu option. In both cases the find dialog does not appear. It can be fixed by closing and reopening the window.

This has always been in a Scala (Metals) window but I don't know if it occurs 

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 6, 5|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
activitusbar|Gru|0.0.21
python|ms-|2019.11.50794
scala|sca|0.3.8
metals|sca|1.6.3
sass-indented|syl|1.7.1
vscode-vtools|ven|1.0.6

</details>

**Comment by rebornix** [comment]
@justinhj could you please check if there is any error in Dev tools (F1 -> Toggle Dev Tools)? I've seen this a few times but now it seems it's not just me. It would be great if we can find some clues of how to reproduce.

**Comment by justinhj** [comment]
@rebornix Absolutely! Next time it happens I will check it out now I know where to look.

**Comment by justinhj** [comment]
Closing since have not reproduced for many weeks
