### ISSUE TITLE
      The terminal process terminated with exit code: 3305342920

### ISSUE THREAD

**Issue by srinvaspoduri** [microsoft/vscode#85848]
Issue Type: <b>Bug</b>

while opeing Terminal ,getting The terminal process terminated with exit code: 3305342920

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.90GB (1.98GB free)|
|Process Argv|C:\Users\srini\Desktop\Angular_Tutorial\First-app|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by srinvaspoduri** [comment]
Nothing worked out

**Comment by gjsjohnmurray** [comment]
Please follow the guidance in https://github.com/microsoft/terminal/issues/1838 and see if that helps.

**Comment by srinvaspoduri** [comment]
Yup ..its working now ..Thanks

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
