### ISSUE TITLE
Extension Ratings in New Experience

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#8584]
- VSCode Version: 1.3-insider
- OS Version: All

Steps to Reproduce:

1. View an extension in results list
2. See rating and compare how we render stars vs the gallary

For a 3.91 rating:
![image](https://cloud.githubusercontent.com/assets/1051190/16498275/e24d8736-3eaf-11e6-9267-f8d4b85ea4a5.png)

In the gallery:
![image](https://cloud.githubusercontent.com/assets/1051190/16498283/ed26a1ba-3eaf-11e6-9a3b-381b9e7d3989.png)

We should be consistent - in this case round up to 4.0 vs round down to 3.5

**Comment by isidorn** [comment]
I know Joao was trying to simulate their extension ranking algorithm, but seems like he missed some corner cases.

**Comment by joaomoreno** [comment]
@modigrv Can you give me the exact algorithm for mapping a rating number to the stars, used in the Marketplace? [This is what we're doing](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsWidgets.ts#L108).

**Comment by pkuma-msft** [comment]
@joaomoreno In marketplace we round off to the nearest multiple of 0.5. Here are some examples,
3.74 will round off to 3.5
3.80 => 4.0
2.60 => 2.5 
4.24 => 4.0
4.26 => 4.5
4.25 => 4.5

**Comment by joaomoreno** [comment]
@pkuma-msft Thanks for the directions. Does 284309d0383624f1c9393bad8e84d38652d690a8 make sense?

**Comment by jaime-olivares** [comment]
This is still happening. i.e. Microsoft's C# extension:
in VSCode: 3.5 stars
in Marketplace: 4 stars

**Comment by techtwaddle** [comment]
The extension has a rating of 3.9 (seen if you hover over the stars), this should be rounded off to 4.0 as per the logic above.. @joaomoreno ?

**Comment by joaomoreno** [comment]
@jaime-olivares Which version of Code are you using?

Here's the latest insiders:

![image](https://cloud.githubusercontent.com/assets/22350/17319988/7b544028-5891-11e6-91a6-0b68f42bb169.png)

**Comment by jaime-olivares** [comment]
@joaomoreno I am using 1.3.1 for macOS

<img width="895" alt="screen shot 2016-08-03 at 00 45 38" src="https://cloud.githubusercontent.com/assets/6194083/17355116/e0eea5a4-5913-11e6-8c25-e5c3d8cf51a9.png">

**Comment by joaomoreno** [comment]
@jaime-olivares The fix is still not in for the stable, it will only come for 1.4.
