### ISSUE TITLE
Prevents software-like hardware intervension with the keyboard.

### ISSUE THREAD

**Issue by GRGSIBERIA** [microsoft/vscode#85849]
- VSCode Version: 1.40.2
- OS Version: Windows 10 64bit

dvorak-kr 4 is background software in Japan.
(http://hp.vector.co.jp/authors/VA009883/)

dvorak-kr converts the keyboard layout from Qwerty to Dvorak in software.
dvorak-kr is familiar with the Japanese keyboard layout.
The latest release can't actions dvorak-kr 4.
I've been using dvorak-kr for more than 10 years, so I'm not familiar with the current Dvorak hardware layout.
Japanese Dvorak is different from English Dvorak.
The latest release has a bug that prevents software-like hardware intervention.
I think that Electron or VSCode changed in keyboard operation in Windows.
This is relevant for all keyboard operations, so please revert if possible.

Does this issue occur when all extensions are disabled?: Yes

**Comment by GRGSIBERIA** [comment]
Yet, this issue duplicated, And Windows is different from Linux.
I think that Electron or VSCode changed keyboard interrupt.
Does Electron depend on Chromium?
I hope the cause of the dependency can be identified.
I'll be patient for a while :D

**Comment by GRGSIBERIA** [comment]
Whoops, this problem does not reproduce on Windows 7 64bit.
VSCode does not have this problem.

* VSCode Version: 10.40.2
* OS Version: Windows 7 64bit SP1

**Comment by alexandrudima** [comment]
@GRGSIBERIA VS Code is built with Electron, which is built with Chromium. With version 1.40.x, we have moved to a newer version of Chromium (76.0.3809.146). Chrome stable is currently at 78.0.3904.108.

Does the special software work with Chrome?

**Comment by GRGSIBERIA** [comment]
@alexandrudima  No, does not work.
VSCode works the same as Chrome.
I don't remenber when the special software does not work on Chrome.
I know that Electron is very chromewell.
I think that VSCode does not be fixed unless Chrome is fixed.

**Comment by alexandrudima** [comment]
Thank you for your fast answer. Given our current architecture, we cannot support this input method on our side unless we receive input events from Chromium.

Can you please create a new issue at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

**Comment by GRGSIBERIA** [comment]
Thank you for a sharing issue link.
No mistake if it works the same as Chrome.
