### ISSUE TITLE
Automated Testing show errors

### ISSUE THREAD

**Issue by lamontu** [microsoft/vscode#85847]
- VSCode Version: 1.40.2
- OS Version: macOS Catalina

Steps to Reproduce:
1. Get the latest source code and build succeeded as [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#contributing-to-visual-studio-code).
2. [Run Automated Testing](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#automated-testing)
`$ ./scripts/test.sh > test_result`
There are 12 same errors output on the terminal

> [93167:1130/140149.646715:INFO:CONSOLE(736)] "_saveResultAndEncode: 1 --> 0-full(10), 10-full(10    ), 20-full(3)", source: file:///Users/lamont/vscode/out/vs/workbench/api/common/extHostLangua    geFeatures.js (736)

**Comment by alexandrudima** [comment]
I have removed the console logs
