### ISSUE TITLE
Polish: Settings GUI array of strings `maxItems` validation error message

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#85841]
```js
"maxItems": 4
```
Provides the message: `"Array must have less than 4 items"`. Should it be `less than 5 items` or something like that?

---

json version of warning is correct: `Array has too many items. Expected 4 or fewer.`

**Comment by octref** [comment]
Changed to `Array must have at most {0} items`

**Comment by octref** [comment]
Also `must` => `should`, since it's natural to say `should have at most...` than `must have at most...`.

**Comment by roblourens** [comment]
If it's _required_, then you should say "must", it's common in technical writing.

**Comment by octref** [comment]
Good point, changed it back to must then.
