### ISSUE TITLE
CTRL + HOVER NOT WORKING 

### ISSUE THREAD

**Issue by vmittal26** [microsoft/vscode#85846]
VS Code surprisingly not showing anything on CTRL and hover because of which I am not able to go to required file/method

**Comment by vmittal26** [comment]
![CTRL_HOVER_VS_CODE](https://user-images.githubusercontent.com/34622587/69896082-22833100-1361-11ea-9a42-e95eda0bcbde.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What version of VSCode? What extensions? What coding language?

What is the simplest repro you can create?

Any messages in the Output panel that might indicate a language server extension having problems?

**Comment by vmittal26** [comment]
Coding lanuage -> Javascript/Typescript
No message in output panel , its simply not showing option on hover , attaching screen shot of about vs vs code version
![VS_CODE_VERSION_SCREENSHOT](https://user-images.githubusercontent.com/34622587/69910074-46ab4480-142b-11ea-9622-aaca06eab214.png)

**Comment by alexandrudima** [comment]
@vmittal26  Can you please do the following:
- disable all extensions
- comment out all your `settings.json`

Open a simple file, like the following `simple.ts`, where the definition lies within the same file:
```ts
class MyClass {
  public sayHello() {
    console.log(`hello`);
  }
}

const x: MyClass;
x.sayHello();
```

Holding the control key and hovering over `MyClass` or over `sayHello` should render a preview of the definition, e.g.:
![image](https://user-images.githubusercontent.com/5047891/70049880-033d0b80-15ce-11ea-878e-7787f86b60ca.png)

Does this sample work for you?

**Comment by vmittal26** [comment]
Hello ,

I tried with one simple file named as sample.ts as mentioned above , there are no extensions and 
and I have commented my settings.json , still issue is present , attached are the screenshots

**Comment by vmittal26** [comment]
![samplets](https://user-images.githubusercontent.com/34622587/70083862-3960a680-1633-11ea-8471-b5d54c58cdea.png)
![image](https://user-images.githubusercontent.com/34622587/70083916-52695780-1633-11ea-9e89-b7c7cc27b632.png)

**Comment by alexandrudima** [comment]
@vmittal26 Your screenshot looks funny because normally TypeScript renders the typescript version in the status bar:

![image](https://user-images.githubusercontent.com/5047891/70145098-a14cd680-169f-11ea-883d-1cc72bb32360.png)

Also, for that code sample, it is expected to see squiggles on `x` because it is not initialized.

I think there is something not working with our built-in TS extension on your machine which is more than go to definition. Does IntelliSense (Ctrl+Space) show completions in TS files? Have you by any chance disabled the built-in TS extension?

**Comment by vmittal26** [comment]
I am glad that screen shot made u smile :) 

You are right ctrl + space is also not showing anything also no errors means red lines 
if some import or missing or any other error , how to enable TS Extension i don't know how to enable/disable it I am surprised what got changed few days back everything was ok

**Comment by alexandrudima** [comment]
Can you please check via the extensions viewlet on the left > ... > Show builtin extensions > scroll down in the first section:

![image](https://user-images.githubusercontent.com/5047891/70147124-f25ec980-16a3-11ea-9313-d541d78fa532.png)

**Comment by vmittal26** [comment]
Thanks a lot :) issue is fixed ,built in typescript extension was disabled somehow , all things resumed to normal

**Comment by alexandrudima** [comment]
@vmittal26 Well, did you disable it in the past (and possibly forgot about it) or did it become disabled by itself without you doing anything? The latter would be a bug and we would like to know how that could have happened.

**Comment by vmittal26** [comment]
I could have disabled this option if I knew about this option , first time i came to know about we can enable/disable built in extension by doing @builtin , however i don't know if there is some short cut of key combination that possibly would have disabled it , 
 
Do let me know if you need any other info
