### ISSUE TITLE
typing non-breaking chinese(may be non-english) will cause input method's candidate box getting farther and farther away

### ISSUE THREAD

**Issue by liesauer** [microsoft/vscode#85845]
![333](https://user-images.githubusercontent.com/8676741/69894392-1cd61d00-135a-11ea-9a7f-26093734294a.gif)

- VSCode Version: 1.40.1
- OS Version: Darwin x64 17.7.0

Steps to Reproduce:

1. install `sogou pinyin input method`
2. type some non-braking chinese words

Does this issue occur when all extensions are disabled?: Yes

**Comment by estepona** [comment]
I've encountered the same problem. The input method I used is MacOS's default Chinese character input method.

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by nerrons** [comment]
I can reproduce this.

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by wangbh0722** [comment]
The same problem here. [#91525](https://github.com/microsoft/vscode/issues/91525)

**Comment by wangbh0722** [comment]
I've just found that this issue won't appear when using Mojave. Only Macs using Catalina have this problem.

**Comment by linklelinklelin** [comment]
So how long will it be before you fix this bug... Now I'm using macOS Big Sur and the bug
still exsit. @rebornix

**Comment by folivora-ice** [comment]
> So how long will it be before you fix this bug... Now I'm using macOS Big Sur and the bug
> still exsit. @rebornix
This problem can be reproduced when editor.letterSpacing: 1 is set, Have you also set it?

**Comment by rebornix** [comment]
> I've just found that this issue won't appear when using Mojave. Only Macs using Catalina have this problem.

As you pointed out it's a behavior change of macOS Catalina, it's the system who decides where to position the IME box but somehow it doesn't put it next to the textarea.

**Comment by liesauer** [comment]
> > I've just found that this issue won't appear when using Mojave. Only Macs using Catalina have this problem.
> 
> As you pointed out it's a behavior change of macOS Catalina, it's the system who decides where to position the IME box but somehow it doesn't put it next to the textarea.

that is not right, i am sure that it works properly in previous versions, but i can't tell you which version it is. btw, i use High Sierra all the time and never update anything.

**Comment by duzhen1996** [comment]
I get the same bug.
