### ISSUE TITLE
Enable setting "breadcrumbs.symbolSortOrder" to be specific to languages

### ISSUE THREAD

**Issue by MarkRosemaker** [microsoft/vscode#85858]
### Problem

The setting "breadcrumbs.symbolSortOrder" cannot be enabled for a specific language, i.e.

`"[markdown]": {
  "breadcrumbs.symbolSortOrder": "position"
  }`

is not possible in the settings.

### Use case

- It makes sense to sort by position in markdown files to see headers and subheaders as they are.
- However, one might want to display symbols by type when writing code.

Thank you in advance!

**Comment by jrieken** [comment]
Actually not a duplicate but should be straight forward to implement as filter-options can already be defined per language

**Comment by jzyrobert** [comment]
Could you point me towards how to get the current resource from the editor model inside `breadcrumbsPicker.ts`?

**Comment by jrieken** [comment]
The [`OutlineModel`](https://github.com/microsoft/vscode/blob/0e3a2cc6da45e47b5e83d27f160a9528dd6925aa/src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts#L470) has a reference to the text model

**Comment by jrieken** [comment]
to verify, have this setting

```
  "[javascript]": {
        "breadcrumbs.symbolSortOrder": "position"
    },
```

and a file `foo.js` with this content (symbol should be sorted alphabetically)

```js
class Abc {
    zzzz;
    aaaa;
}
```

Now, paste the same content into `foo.ts` and make sure symbols are sorted by position
