### ISSUE TITLE
Debug Run extension hangs on building

### ISSUE THREAD

**Issue by kmkadze** [microsoft/vscode#85852]
- VSCode Version: 1.40.2 2019-11-25T14:54:45.096Z
- OS Version: Windows_NT x64 10.0.17763

Trying to debug vscode extension. After pressing F5 "Building" message appears in the status bar but debugging doesnt start. After reinstalling code bug disappeared until laptop was rebooted. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Can you repro this using any of the example extensions from https://github.com/microsoft/vscode-extension-samples? Or one of your own in a public repo?

**Comment by kmkadze** [comment]
> /needsMoreInfo
> 
> Can you repro this using any of the example extensions from https://github.com/microsoft/vscode-extension-samples? Or one of your own in a public repo?

It doesnt start debugging even with a 'hello-world' extension

**Comment by kmkadze** [comment]
Ok, I found the issue. I dont know if it's a correct solution but it worked for me. In a launch.json both "preLaunchTask" parameters should be set to "${defaultBuildTask}" insted of "npm watch"
launch.json:
`{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		}
	]
}`
