### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by redy2roll** [microsoft/vscode#85855]
Issue Type: <b>Bug</b>

I am trying to open html, css, and javascript files and vs code isn't allowing me to open the file, but sublime text does and It's really aggravating me.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9425 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 3094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
sublime-keybindings|ms-|4.0.3

</details>

**Comment by sandy081** [comment]
What do you mean by `not allowing me to open`. Do you see any error ?
