### ISSUE TITLE
Directory with a dot prefix will not be found

### ISSUE THREAD

**Issue by sl5net** [microsoft/vscode#85857]
Directory with a dot prefix will not be found

I want to open the following folder: "/home/me/.config/autokey/data/AutoHotKey4Linux" 
But presumably because it starts with a dot, the program does not allow opening this folder? 

If I use another IDE, I can open files from this folder or this folder.

Steps to reproduce:

    Open Menu , go to "Open Folder ... "
    Mark directory in Thunar (file manager) like this "/home/me/.config/autokey/data/AutoHotKey4Linux" 
    Select a directory like this "/home/me/.config/autokey/data/AutoHotKey4Linux" 
    VSCode says it is not exist.

Reproduces without extensions: Yes

Version: 1.40.0 Code - OSS
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-10T18:38:48.056Z
Electron: 6.1.1
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.12-1-MANJARO
![image](https://user-images.githubusercontent.com/5634759/69903915-1f5b6580-13a0-11ea-92ba-7b0319a2be7d.png)

**Comment by sl5net** [comment]
works if i choose file:///home/me/.config/autokey/data/AutoHotKey4Linux

**Comment by sl5net** [comment]
no problem if i use file:///home/me/.config/autokey/data/AutoHotKey4Linux

**Comment by dhairyanadapara** [comment]
I can't reproduce this issue on ubuntu. I think this is an OS-specific issue.

**Comment by bpasero** [comment]
Me too.
