### ISSUE TITLE
Autopep8 formatting doesn't work in 2.7.17 python but work in 3.8

### ISSUE THREAD

**Issue by Prynka1995** [microsoft/vscode#85868]
Issue Type: <b>Performance Issue</b>

Hi, autopep8 formatting doesn't work in python 2.7.17, but when I change intepreter to python 3.8 it works. What shoul I do to able to formatting code in 2.17 intepreter?

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    74	  9920	code main
    0	   118	  4932	   gpu-process
    0	   157	  9512	   window (pto.py - Новая папка - Visual Studio Code)
    0	     4	  1804	     winpty-process
    0	     6	  7632	       console-window-host (Windows internal process)
    0	     2	  9316	       C:\WINDOWS\system32\cmd.exe
    0	    31	  2684	     searchService
    0	    89	  3092	     extensionHost
    0	    86	  8616	       c:\Users\Husband\.vscode\extensions\ms-python.python-2019.11.50794\languageServer.0.4.114\Microsoft.Python.LanguageServer.exe
    0	     4	  1436	         console-window-host (Windows internal process)
    0	    39	 10912	       "C:\Users\Husband\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Husband\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=3092
    0	     9	 10972	     watcherService 
    0	     4	  9300	       console-window-host (Windows internal process)
    2	    64	  9584	   window (Issue Reporter)
    0	    73	 10764	   shared-process
    0	    11	 11244	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (pto.py - Новая папка - Visual Studio Code)
|    Folder (Новая папка): 4 files
|      File types: py(2) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.11.50794
indent-rainbow|ode|7.4.0
vscodeintellicode|Vis|1.2.0

</details>

**Comment by sandy081** [comment]
Please file the issue against the python extension.
