### ISSUE TITLE
Syntax highlighting for "not obviously defined" variables

### ISSUE THREAD

**Issue by claytongulick** [microsoft/vscode#85864]
It would be a huge time saver if variables inside of a scope that are not obviously defined, were highlighted in a color, yellow for example.

One of the more helpful features VS Code has with syntax highlighting is to grey a variable out when it detects that it's not being used. This helps find lots of typos. It would be equally, perhaps more, helpful if when using a variable, if there's no obvious place where it's been declared, to color it light yellow as a warning. This would also save tons of time with typos etc... in variable names.

Thanks for the great work!

Edit: *this applies to the javascript syntax highlighter

**Comment by sandy081** [comment]
Looks like related to syntax highlighting, hence assigning to you.

**Comment by aeschli** [comment]
This would have to come from the TypeScript language server or from a linter.

**Comment by mjbvz** [comment]
See [type checking for js](https://code.visualstudio.com/Docs/languages/javascript#_type-checking).

It will show errors for undefined variables
