### ISSUE TITLE
Debugging remote node process ignores breakpoints

### ISSUE THREAD

**Issue by chrisahardie** [microsoft/vscode#85867]
- VSCode Version: 1.40.2
- OS Version: Raspbian Buster / Windows 10

Steps to Reproduce:

1. Create Node project on remote Raspberry Pi running Raspbian Buster at `/home/pi/Documents/Repos/test`
2. Add `start-with-debug` script to `project.json`

```
"start-with-debug": "node --inspect=0.0.0.0:9229 index.js"
```

3. Expose `/home/pi/Documents/Repos` as a network share `PiShare`
4. Open VS Code on Windows 10 laptop pointing at network share: `Open directory -> //192.168.1.130/PiShare`
5. Add `launch.json` configuration:

```
{
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229,
      "address": "192.168.1.130",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/home/pi/Documents/Repos/test",
      "protocol": "inspector"
},
```
6. In VS Code debugging window, select the `Attach` option and click "Start Debugging"
7. On Raspberrry Pi, run `npm run start-with-debug`

When I do the above, VS Code will break on `debugger` statements in the code (totally awesome!). Unfortunately, any breakpoints I set within VS Code are not respected.

If I set a couple breakpoints in VS Code:
![image](https://user-images.githubusercontent.com/2429373/69908140-aebd4480-13b1-11ea-8a09-1324587223e0.png)

Breakpoints are greyed out once code is running and only the `debugger` statements are respected:
![image](https://user-images.githubusercontent.com/2429373/69908151-f0e68600-13b1-11ea-9160-9bb6983b7986.png)

The `Debug Console` errors out multiple times with:

```
Error processing "breakpointLocations": Error: Breakpoint ignored because generated code not found (source map problem?).
    at Object.errP (c:\Users\chris\.vscode\extensions\ms-vscode.node-debug2-1.39.0\node_modules\vscode-chrome-debug-core\out\src\utils.js:262:13)
    at c:\Users\chris\.vscode\extensions\ms-vscode.node-debug2-1.39.0\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:140:30
```

Other issues that have been raised due to this error seem to be web related, so I think/hope I'm not duplicating some other issue.

**Comment by eohlde** [comment]
I'm having an identical problem when attempting to debug a python application in a docker container. I'd be happy to share any useful information. Just let me know what to post.

**Comment by weinand** [comment]
@eohlde please file an issue against the Python extension. This issue is about node.js which is unrelated to your problem.

**Comment by eohlde** [comment]
For posterity, my issue is being tracked at https://github.com/microsoft/vscode/issues/90244#issue-561737806

**Comment by AndrewRayCode** [comment]
Possibly related, but unclear: https://github.com/Microsoft/vscode-recipes/issues/187

It looks something like if the path to the file on the host machine running vscode and the target (be it docker, rasberry pi, what have you) are different, vscode reads the localRoot and remoteRoot options and then discards them and falls over.

The solution from the other ticket, which helped me hit a breakpoint in a docker container (different file path) running typescript, was to use the `sourceMapPathOverrides` option, which seems to be some backup

      "sourceMapPathOverrides": {
        "/target/folder/*": "${workspaceRoot}/*"
      }

**Comment by AndroidHitchhiking** [comment]
I am facing same issue but not remote for my local code,
launch.js ---

```{
    "type": "node",
    "request": "attach",
    "name": "Node: Nodemon2",
    "port": 9229,
    "restart": true,
}```

When running the code debugger got attached and at initial load breakpoints are fine but as when I hit any api endpoint the breakpoints in code are ignored

**Comment by connor4312** [comment]
We since have a [new debugger](https://github.com/microsoft/vscode-js-debug/), please let us know if you're still running into problems, and if so open an issue on that repo; the issue template has instructions on how to collect a log file which should be sufficient to help you fix whatever problems you may still be having.
