### ISSUE TITLE
HTML inside PHP Print not syntax highlighted, simply treated as string.

### ISSUE THREAD

**Issue by djsall** [microsoft/vscode#85862]
Piece of code without highlighting:
![image](https://user-images.githubusercontent.com/4785203/69905159-605b7600-13b0-11ea-90cc-61dccd48a9c2.png)
Example in phpstorm:
![image](https://user-images.githubusercontent.com/4785203/69905186-97318c00-13b0-11ea-93e5-82dbffba6833.png)
Also tested with builtin color themes, all of them reproduce the same behavior.

**Comment by gjsjohnmurray** [comment]
Perhaps the fix for #84401 may have resolved this. Can you test with the current [insider build] (https://code.visualstudio.com/insiders) ?

**Comment by djsall** [comment]
Tested insiders, still not working.
![image](https://user-images.githubusercontent.com/4785203/69915360-58eaaa00-144e-11ea-9009-1bdab747a95e.png)

**Comment by setochris** [comment]
Is there any progress on this?  It's definitely an issue when working on .php files with large html strings.  The html not being highlighted is a real pain to work on.  I know you can change to HTML file formatting, but then you lose the PHP formatting, and the outline messes up as it does not list the PHP functions and variables.  Ideally there should be an option for "Multi Highlighting" similar to PHP storm or PSPad.

**Comment by djsall** [comment]
For me it is still the same. Also, SQL highlighting inside php files can be funky too:
![image](https://user-images.githubusercontent.com/4785203/79791189-33066900-834d-11ea-8d8f-e8237ef4e207.png)

**Comment by mmorgan86** [comment]
Any update on this?

This issue is the one thing keeping me from moving fully from phpstorm. 

I run across a lot of code where the html is echo'd out in a php file. 

echo "
    <div class='names'>
        <div class='names2'>
            Names are here:
        </div>
        <button class='btn btn-danger'>
            I am a button
        </button>
        <div>
             hello
        </div>
    </div>
";

I would love to be able to move to vscode if this issue is solved. As of now it looks like it is not. 

Thanks.

**Comment by roblourens** [comment]
This is actually supported if you use a heredoc string with `HTML`:

![image](https://user-images.githubusercontent.com/323878/88495781-d4661200-cf6f-11ea-9143-85940958fc95.png)

However I don't plan to support parsing HTML in all PHP strings by default. An extension might attempt that.

**Comment by MichaelOhn** [comment]
Hi, 

Is there any advancement of this ? 

Best regards

**Comment by iberosmen** [comment]
any idea that this?
