### ISSUE TITLE
Terminal windows icon cut out

### ISSUE THREAD

**Issue by narendra-sabhani** [microsoft/vscode#85874]
Issue Type: <b>Bug</b>

While installing rust (rls) package on terminal windows font icons were displayed fully.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
csharp|ms-|1.21.8
rust|rus|0.7.0
vscode-icons|vsc|9.6.0
material-theme|zhu|3.1.2

</details>

**Comment by narendra-sabhani** [comment]
See Attached Screenshot.
![image](https://user-images.githubusercontent.com/20256908/69912089-bb41ab80-144a-11ea-8d2f-07220cdb615d.png)

**Comment by Tyriar** [comment]
@sbatten weirdness with the top of the panel getting cut off?
