### ISSUE TITLE
Error message: Sorry, Java IntelliCode Support has problem, for more details, please view Output

### ISSUE THREAD

**Issue by cdytoby** [microsoft/vscode#85876]
Issue Type: <b>Bug</b>

Original Text:
很抱歉，激活面向 Java 的 IntelliCode 支持时遇到问题。有关详细信息，请查看“针对 Java 的语言支持”和 "VS IntelliCode" 输出窗口。

Translation:
Sorry, Java IntelliCode Support has issue. For more details, please check "Java Language Support" and "VS IntelliCode" Output.

I don't get it. Where are these Output? I don't have any outputs here.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.5
vscode-glsllint|CAD|0.0.5
npm-intellisense|chr|1.3.0
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
vscode-npm-script|eg2|0.3.9
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
beautify|Hoo|1.5.0
php-cs-fixer|jun|0.1.129
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|0.8.2
vscode-language-pack-zh-hans|MS-|1.37.3
python|ms-|2019.10.41019
csharp|ms-|1.21.8
powershell|ms-|2019.11.0
java|red|0.53.1
vscode-nginx|sha|0.6.0
shader|sle|1.1.4
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.18.1

</details>

Project Folder:

[JavaTest.zip](https://github.com/microsoft/vscode/files/3908078/JavaTest.zip)

**Comment by sandy081** [comment]
I suspect this is coming from an extension. So please file against the extension that is causing this.
