### ISSUE TITLE
crash without any error message

### ISSUE THREAD

**Issue by icq4ever** [microsoft/vscode#85873]
OS : windows 10 Home edition 64bit

I'm not sure what makes crash exactly but it's happen with korean IME (input method). with korean IME, as soon as typing '"' or "-" like special charecter, suddenly all VS code windows are disappear. already tried uninstall suspicious non official extensions. but no different.

**Comment by alexandrudima** [comment]
@icq4ever

I have installed the Korean input method and typing with that does not crash VS Code for me. Here is the one I have configured:

![image](https://user-images.githubusercontent.com/5047891/70051531-8ad84980-15d1-11ea-94b0-f6abb928d481.png)

Can you perhaps give more precise steps? Like what exactly are you typing?

**Comment by icq4ever** [comment]
hmm. I realized that it's not related with  "microsoft korean input method".
I used another korean IME called "날개셋", for custom shorcut of switching input language between english and korean, but vscode crashed with that IME. 

now no issue with "MS korean IME". I'll close this issue.
but thanks for support!!!
