### ISSUE TITLE
 Garbled characters when importing multiple folders into the workspace

### ISSUE THREAD

**Issue by rihalvnium76** [microsoft/vscode#85870]
Issue Type: <b>Bug</b>

Directly importing folders with Chinese names is normal. However, if I first import a folder with an English name (e.g. D: \ npMingw \ mingw), and then import a folder with a Chinese name (e.g. D: \ Data \测试), the import with a Chinese name will fail. The name of the folder in the workspace becomes garbled code, and prompts "Can not resolve workspace folder"

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.40.2
cpptools|ms-|0.26.1
vscode-code-runner|wan|0.9.6
material-theme|zhu|3.1.2

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please open the workspace configuration file and see the entry that is corresponding to the folder `测试`. You can use the command `Open Workspace Configuration File` to open it.

**Comment by rihalvnium76** [comment]
> Open Workspace Configuration File

The configuration file can be opened, but it displays garbled characters.
This garbled problem has existed from the previous version to the current version, and still has not been fixed.
![VSCBUG](https://user-images.githubusercontent.com/57667144/69914360-5ef87f00-147e-11ea-9288-0fb0c3b7c78b.png)

**Comment by sandy081** [comment]
If you fix this file by changing the encoding and updating the path then it works?

**Comment by rihalvnium76** [comment]
> 
> 
> If you fix this file by changing the encoding and updating the path then it works?

No.
I tried to modify the file encoding to UTF-8 and save it, but it didn't work. 
After that, I tried to remove the folder with Chinese name, opened the workspace configuration file, used "Reopen with Encoding" and selected UTF-8 (not saved), and then re-added the directory with Chinese name, VSCode was able to resolve . 
However, when I close the workspace configuration file opened in the editor, and then add another directory with Chinese name, or remove the directory with Chinese name added before, and then add the directory again, VSCode cannot resolve the directory again. The configuration file also became garbled, and its encoding changed back to Windows-1252.
It seems that VSCode fixedly uses Windows-1252 encoding instead of automatic recognition to read and write some configuration files.

**Comment by sandy081** [comment]
Will wait for @bpasero insights.

**Comment by bpasero** [comment]
This can happen if an encoding is configured that is not UTF-8. We have overrides in place that can enforce an encoding but we missed to specify it for untitled workspaces. I added that now here:

https://github.com/microsoft/vscode/blob/f3f658369f117d12b0ae6960555b4b2845178fd8/src/vs/workbench/services/textfile/electron-browser/nativeTextFileService.ts#L354
