### ISSUE TITLE
Add file to .gitignore from Explorer context menu

### ISSUE THREAD

**Issue by omer-g** [microsoft/vscode#85885]
It'd be nice to have an "Add to .gitignore" functionality in the Explorer context menu.
This was already mentioned briefly in #51525 and was closed (I'm sorry for the duplicate - I thought this could perhaps be further discussed, since the previous issue was one line).

The main reason why I think this would be helpful, is because folders do not appear in the Source Control toolbar. This means that if a newly added folder has many files (for example a tests folder), it becomes very tedious to ignore them all - and requires manual editing of `.gitignore`. A context menu button in Explorer would allow to ignore the entire folder. This becomes even more problematic when multiple folders have been copied to the working folder and there are suddenly hundreds of U marked files in Source Control.

In any case I think it would be nice to at least have the option to add this to the context menu, even if this would not be the default.

**Comment by gjsjohnmurray** [comment]
[This extension](https://marketplace.visualstudio.com/items?itemName=michelemelluso.gitignore) look like it does the job.

**Comment by omer-g** [comment]
It does, thanks so much.

**Comment by gjsjohnmurray** [comment]
@omer-g please close this issue.
