### ISSUE TITLE
Provide a way to make terminal commands issued programmatically not end up in the shell history

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode#85887]
I initially opened this issue over in the vscode-python repo (microsoft/vscode-python#7041) but it turned out to be something for the core.

When anything - for example the "run" command from the Python extension - executes a command in the terminal, it ends up in the user's shell history.

I'll explain below why this is incredibly annoying, but both [bash](https://unix.stackexchange.com/a/115922/2505) and [zsh](https://unix.stackexchange.com/a/6104/2505) (and probably most other shells as well) have a setting to not add commands to the history when they are prefixed with a space. When this feature is not enabled/supported, there are no disadvantages of prefixing the line that's sent to the shell with a space.

So my feature request is to either always add a space at the beginning of any command that's sent to the shell, or to add a setting that lets the user enable this if they want to use it.

---

Some details on why I find it so annoying to have vscode-executed commands end up in my shell history.

The first time (ie no terminal open yet) I run e.g. my Python script in the terminal, the output is a bit ugly but not terrible:

```
[adrian@claptrap:~/dev/misc]> source /home/adrian/.python3-env/bin/activate
[adrian@claptrap:~/dev/misc]> /home/adrian/.python3-env/bin/python /home/adrian/.vscode-server-insiders/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 38805 /home/adrian/dev/misc/imapwatch.py 
```

That long command is nothing I'd ever want to run manually form my shell, so it does not belong in the shell history. But if I run the command again (now that a terminal is already open) it gets much, much worse. To have pretty `ls` output I have a *very* verbose LS_COLORS env var. No problem usually, but look at what vscode does during the second run:

```
[adrian@claptrap:~/dev/misc]> cd /home/adrian/dev/misc ; env 'SSH_CONNECTION=xxx' OLDPWD=/home/adrian XDG_SESSION_ID=c5 USER=adrian PWD=/home/adrian HOME=/home/adrian 'SSH_CLIENT=xxx' XDG_SESSION_TYPE=tty MAIL=/var/mail/adrian SHELL=/bin/zsh XDG_SESSION_CLASS=user SHLVL=2 VSCODE_AGENT_FOLDER=/home/adrian/.vscode-server-insiders LOGNAME=adrian XDG_RUNTIME_DIR=/run/user/1000 _=/home/adrian/.vscode-server-insiders/bin/e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027/node VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH=/home/adrian/.vscode-server-insiders/bin/e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027/remote/node_modules VSCODE_LOGS=/home/adrian/.vscode-server-insiders/data/logs/20191201T150801 ANT_HOME=/usr/share/ant CONFIG_PROTECT=/usr/share/gnupg/qualified.txt 'CONFIG_PROTECT_MASK=/etc/sandbox.d /etc/fonts/fonts.conf /etc/gentoo-release /etc/terminfo /etc/ca-certificates.conf /etc/revdep-rebuild' EDITOR=/usr/bin/vi GCC_SPECS= INFOPATH=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.30/info:/usr/share/info LC_CTYPE=de_DE.UTF-8 'LESS=-R -M --shift 5' 'LESSOPEN=|lesspipe %s' MANPAGER=/usr/bin/vimmanpager MANPATH=/etc/java-config-2/current-system-vm/man:/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/man:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.30/man:/usr/lib/llvm/8/share/man:/etc/java-config-2/current-system-vm/man/:/usr/local/share/man:/usr/share/man:/usr/share/rust-bin-1.37.0/man MANWIDTH=100 OPENGL_PROFILE=xorg-x11 QUOTING_STYLE=literal PAGER=/usr/bin/less JAVA_HOME=/etc/java-config-2/current-system-vm JDK_HOME=/etc/java-config-2/current-system-vm JAVAC=/etc/java-config-2/current-system-vm/bin/javac 'LS_COLORS=bd=38;5;68:ca=48;5;22;38;5;253:cd=38;5;113;1:di=38;5;30:do=38;5;127:ex=38;5;166;1:pi=38;5;126:fi=38;5;253:ln=target:mh=38;5;220;1:or=48;5;196;38;5;232;1:ow=38;5;220;1:sg=48;5;3;38;5;0:su=48;5;1;38;5;253:so=38;5;197:st=38;5;86;48;5;234:tw=48;5;235;38;5;139;3:*LS_COLORS=48;5;89;38;5;197;1;3;4;7:*README=38;5;220;1:*LICENSE=38;5;220;1:*COPYRIGHT=38;5;220;1:*AUTHORS=38;5;220;1:*HISTORY=38;5;220;1:*.log=38;5;190:*.txt=38;5;192:*.etx=38;5;184:*.info=38;5;184:*.markdown=38;5;184:*.md=38;5;184:*.mkd=38;5;184:*.nfo=38;5;184:*.pod=38;5;184:*.tex=38;5;184:*.textile=38;5;184:*.msg=38;5;178:*.pgn=38;5;178:*.xml=38;5;178:*.json=38;5;178:*.yml=38;5;178:*.cbr=38;5;141:*.cbz=38;5;141:*.chm=38;5;141:*.djvu=38;5;141:*.pdf=38;5;141:*.PDF=38;5;141:*.docm=38;5;111;4:*.doc=38;5;111:*.docx=38;5;111:*.eps=38;5;111:*.odb=38;5;111:*.odt=38;5;111:*.odp=38;5;166:*.pps=38;5;166:*.ppt=38;5;166:*.csv=38;5;78:*.ods=38;5;112:*.xla=38;5;76:*.xls=38;5;112:*.xlsx=38;5;112:*.xlsxm=38;5;112;4:*.xltm=38;5;73;4:*.xltx=38;5;73:*cfg=1:*conf=1:*rc=1:*.ini=1:*.vim=1:*.viminfo=1:*.pcf=1:*.psf=1:*.git=38;5;197:*.gitignore=38;5;240:*.gitattributes=38;5;240:*.gitmodules=38;5;240:*.awk=38;5;172:*.bash=38;5;172:*.bat=38;5;172:*.BAT=38;5;172:*.sed=38;5;172:*.sh=38;5;113:*.zsh=38;5;113:*.ahk=38;5;29;1:*.py=38;5;41:*.msql=38;5;222:*.mysql=38;5;222:*.pgsql=38;5;222:*.sql=38;5;222:*.tcl=38;5;64;1:*.asm=38;5;81:*.cl=38;5;81:*.lisp=38;5;81:*.lua=38;5;81:*.c=38;5;81:*.C=38;5;81:*.h=38;5;110:*.H=38;5;110:*.tcc=38;5;110:*.c++=38;5;81:*.h++=38;5;110:*.hpp=38;5;110:*.hxx=38;5;110:*.ii=38;5;110:*.M=38;5;110:*.m=38;5;110:*.cc=38;5;81:*.cs=38;5;81:*.cp=38;5;81:*.cpp=38;5;81:*.cxx=38;5;81:*.f=38;5;81:*.for=38;5;81:*.ftn=38;5;81:*.s=38;5;110:*.S=38;5;110:*.sx=38;5;81:*.hi=38;5;110:*.hs=38;5;81:*.PL=38;5;160:*.pyc=38;5;240:*.css=38;5;125;1:*.less=38;5;125;1:*.sass=38;5;125;1:*.scss=38;5;125;1:*.htm=38;5;125;1:*.html=38;5;125;1:*.jhtm=38;5;125;1:*.mht=38;5;125;1:*.eml=38;5;125;1:*.mustache=38;5;125;1:*.coffee=38;5;074;1:*.java=38;5;074;1:*.js=38;5;074;1:*.jsm=38;5;074;1:*.jsm=38;5;074;1:*.jsp=38;5;074;1:*.php=38;5;81:*.ctp=38;5;81:*.twig=38;5;81:*.vb=38;5;81:*.vba=38;5;81:*.vbs=38;5;81:*Makefile=38;5;155:*MANIFEST=38;5;243:*pm_to_blib=38;5;240:*.am=38;5;242:*.in=38;5;242:*.old=38;5;242:*.out=38;5;242:*.SKIP=38;5;244:*.diff=48;5;197;38;5;232:*.patch=48;5;197;38;5;232;1:*.bmp=38;5;97:*.tiff=38;5;97:*.TIFF=38;5;97:*.cdr=38;5;97:*.gif=38;5;97:*.go=38;5;97:*.ico=38;5;97:*.jpeg=38;5;97:*.JPG=38;5;97:*.jpg=38;5;97:*.nth=38;5;97:*.png=38;5;97:*.svg=38;5;97:*.xpm=38;5;97:*.avi=38;5;114:*.divx=38;5;114:*.IFO=38;5;114:*.m2v=38;5;114:*.m4v=38;5;114:*.mkv=38;5;114:*.MOV=38;5;114:*.mov=38;5;114:*.mp4=38;5;114:*.mpeg=38;5;114:*.mpg=38;5;114:*.ogm=38;5;114:*.rmvb=38;5;114:*.sample=38;5;114:*.wmv=38;5;114:*.3g2=38;5;115:*.3gp=38;5;115:*.gp3=38;5;115:*.webm=38;5;115:*.gp4=38;5;115:*.asf=38;5;115:*.flv=38;5;115:*.ts=38;5;115:*.ogv=38;5;115:*.f4v=38;5;115:*.VOB=38;5;115;1:*.vob=38;5;115;1:*.3ga=38;5;137;1:*.S3M=38;5;137;1:*.aac=38;5;137;1:*.dat=38;5;137;1:*.dts=38;5;137;1:*.fcm=38;5;137;1:*.m4a=38;5;137;1:*.mid=38;5;137;1:*.midi=38;5;137;1:*.mod=38;5;137;1:*.mp3=38;5;137;1:*.oga=38;5;137;1:*.ogg=38;5;137;1:*.s3m=38;5;137;1:*.sid=38;5;137;1:*.ape=38;5;136;1:*.flac=38;5;136;1:*.alac=38;5;136;1:*.wav=38;5;136;1:*.wv=38;5;136;1:*.wvc=38;5;136;1:*.afm=38;5;66:*.pfb=38;5;66:*.pfm=38;5;66:*.ttf=38;5;66:*.otf=38;5;66:*.PFA=38;5;66:*.pfa=38;5;66:*.7z=38;5;40:*.a=38;5;40:*.arj=38;5;40:*.bz2=38;5;40:*.gz=38;5;40:*.rar=38;5;40:*.tar=38;5;40:*.tgz=38;5;40:*.xz=38;5;40:*.zip=38;5;40:*.apk=38;5;215:*.deb=38;5;215:*.jad=38;5;215:*.jar=38;5;215:*.cab=38;5;215:*.pak=38;5;215:*.vdf=38;5;215:*.vpk=38;5;215:*.bsp=38;5;215:*.dmg=38;5;215:*.r00=38;5;239:*.r01=38;5;239:*.r02=38;5;239:*.r03=38;5;239:*.r04=38;5;239:*.r05=38;5;239:*.r06=38;5;239:*.r07=38;5;239:*.r08=38;5;239:*.r09=38;5;239:*.r10=38;5;239:*.r100=38;5;239:*.r101=38;5;239:*.r102=38;5;239:*.r103=38;5;239:*.r104=38;5;239:*.r105=38;5;239:*.r106=38;5;239:*.r107=38;5;239:*.r108=38;5;239:*.r109=38;5;239:*.r11=38;5;239:*.r110=38;5;239:*.r111=38;5;239:*.r112=38;5;239:*.r113=38;5;239:*.r114=38;5;239:*.r115=38;5;239:*.r116=38;5;239:*.r12=38;5;239:*.r13=38;5;239:*.r14=38;5;239:*.r15=38;5;239:*.r16=38;5;239:*.r17=38;5;239:*.r18=38;5;239:*.r19=38;5;239:*.r20=38;5;239:*.r21=38;5;239:*.r22=38;5;239:*.r25=38;5;239:*.r26=38;5;239:*.r27=38;5;239:*.r28=38;5;239:*.r29=38;5;239:*.r30=38;5;239:*.r31=38;5;239:*.r32=38;5;239:*.r33=38;5;239:*.r34=38;5;239:*.r35=38;5;239:*.r36=38;5;239:*.r37=38;5;239:*.r38=38;5;239:*.r39=38;5;239:*.r40=38;5;239:*.r41=38;5;239:*.r42=38;5;239:*.r43=38;5;239:*.r44=38;5;239:*.r45=38;5;239:*.r46=38;5;239:*.r47=38;5;239:*.r48=38;5;239:*.r49=38;5;239:*.r50=38;5;239:*.r51=38;5;239:*.r52=38;5;239:*.r53=38;5;239:*.r54=38;5;239:*.r55=38;5;239:*.r56=38;5;239:*.r57=38;5;239:*.r58=38;5;239:*.r59=38;5;239:*.r60=38;5;239:*.r61=38;5;239:*.r62=38;5;239:*.r63=38;5;239:*.r64=38;5;239:*.r65=38;5;239:*.r66=38;5;239:*.r67=38;5;239:*.r68=38;5;239:*.r69=38;5;239:*.r69=38;5;239:*.r70=38;5;239:*.r71=38;5;239:*.r72=38;5;239:*.r73=38;5;239:*.r74=38;5;239:*.r75=38;5;239:*.r76=38;5;239:*.r77=38;5;239:*.r78=38;5;239:*.r79=38;5;239:*.r80=38;5;239:*.r81=38;5;239:*.r82=38;5;239:*.r83=38;5;239:*.r84=38;5;239:*.r85=38;5;239:*.r86=38;5;239:*.r87=38;5;239:*.r88=38;5;239:*.r89=38;5;239:*.r90=38;5;239:*.r91=38;5;239:*.r92=38;5;239:*.r93=38;5;239:*.r94=38;5;239:*.r95=38;5;239:*.r96=38;5;239:*.r97=38;5;239:*.r98=38;5;239:*.r99=38;5;239:*.part=38;5;239:*.iso=38;5;124:*.bin=38;5;124:*.nrg=38;5;124:*.qcow=38;5;124:*.sparseimage=38;5;124:*.accdb=38;5;60:*.accde=38;5;60:*.accdr=38;5;60:*.accdt=38;5;60:*.db=38;5;60:*.localstorage=38;5;60:*.sqlite=38;5;60:*.typelib=38;5;60:*.pacnew=38;5;33:*.un~=38;5;241:*.orig=38;5;241:*.BUP=38;5;241:*.bak=38;5;241:*.o=38;5;241:*.swp=38;5;244:*.swo=38;5;244:*.tmp=38;5;244:*.sassc=38;5;244:*.pid=38;5;248:*.state=38;5;248:*lockfile=38;5;248:*.err=38;5;160;1:*.error=38;5;160;1:*.stderr=38;5;160;1:*.dump=38;5;241:*.stackdump=38;5;241:*.zcompdump=38;5;241:*.zwc=38;5;241:*.pcap=38;5;29:*.cap=38;5;29:*.dmp=38;5;29:*.allow=38;5;112:*.deny=38;5;196:*.service=38;5;45:*@.service=38;5;45:*.socket=38;5;45:*.swap=38;5;45:*.device=38;5;45:*.mount=38;5;45:*.automount=38;5;45:*.target=38;5;45:*.path=38;5;45:*.timer=38;5;45:*.snapshot=38;5;45:*.application=38;5;116:*.cue=38;5;116:*.description=38;5;116:*.directory=38;5;116:*.m3u=38;5;116:*.m3u8=38;5;116:*.properties=38;5;116:*.sfv=38;5;116:*.srt=38;5;116:*.theme=38;5;116:*.torrent=38;5;116:*.urlview=38;5;116:*.gpg=38;5;192;3:*.signature=38;5;192;3:*.sig=38;5;192;3:*.pgp=38;5;192;3:*.asc=38;5;192;3:*.enc=38;5;192;3:*.32x=38;5;213:*.cdi=38;5;213:*.fm2=38;5;213:*.rom=38;5;213:*.sav=38;5;213:*.st=38;5;213:*.a00=38;5;213:*.a52=38;5;213:*.A64=38;5;213:*.a64=38;5;213:*.a78=38;5;213:*.adf=38;5;213:*.atr=38;5;213:*.gb=38;5;213:*.gba=38;5;213:*.gbc=38;5;213:*.gel=38;5;213:*.gg=38;5;213:*.ggl=38;5;213:*.ipk=38;5;213:*.j64=38;5;213:*.nds=38;5;213:*.nes=38;5;213:*.sms=38;5;213:*.pot=38;5;7:*.pcb=38;5;7:*.mm=38;5;7:*.pod=38;5;7:*.gbr=38;5;7:*.pl=38;5;7:*.spl=38;5;7:*.scm=38;5;7:*.sis=38;5;7:*.1p=38;5;7:*.3p=38;5;7:*.cnc=38;5;7:*.def=38;5;7:*.ex=38;5;7:*.example=38;5;7:*.feature=38;5;7:*.ger=38;5;7:*.map=38;5;7:*.mf=38;5;7:*.mfasl=38;5;7:*.mi=38;5;7:*.mtx=38;5;7:*.pc=38;5;7:*.pi=38;5;7:*.plt=38;5;7:*.pm=38;5;7:*.rb=38;5;7:*.rdf=38;5;7:*.rst=38;5;7:*.ru=38;5;7:*.sch=38;5;7:*.sty=38;5;7:*.sug=38;5;7:*.t=38;5;7:*.tdy=38;5;7:*.tfm=38;5;7:*.tfnt=38;5;7:*.tg=38;5;7:*.vcard=38;5;7:*.vcf=38;5;7:*.xln=38;5;7:' GOPATH=/home/adrian/dev/go RIPGREP_CONFIG_PATH=/home/adrian/.ripgreprc SSH_AUTH_SOCK=/tmp/ssh-xxx/agent.715 SSH_AGENT_PID=716 GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:742:1 AMD_ENTRYPOINT=vs/server/remoteExtensionHostProcess PIPE_LOGGING=true VERBOSE_LOGGING=true VSCODE_EXTHOST_WILL_SEND_SOCKET=true VSCODE_HANDLES_UNCAUGHT_ERRORS=true VSCODE_LOG_STACK=false 'VSCODE_NLS_CONFIG={"locale":"en","availableLanguages":{}}' VSCODE_IPC_HOOK_CLI=/tmp/vscode-ipc-xxx.sock APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL=true PATH=/home/adrian/.vscode-server-insiders/bin/e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027/bin:/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/home/adrian/scripts:/home/adrian/.local/bin:/home/adrian/dev/go/bin PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/adrian/.python3-env/bin/python /home/adrian/.vscode-server-insiders/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 38855 /home/adrian/dev/misc/imapwatch.py
```

Yes, that's 10 kB in a single shell command because for some reason vscode repeats the whole environment there.

I don't know why this is done and if it's the fault of vscode of the python extension that the whole env is explicitly specified in the terminal, but regardless of this annoyance: I don't want ANY of those commands in my shell history. They are useless.

---

Update: As a workaround I put this in my `~/.zshrc` on the remote system:

```zsh
if [[ -n "$VSCODE_IPC_HOOK_CLI" || -n "$VSCODE_AGENT_FOLDER" ]]; then
        # vscode does weird stuff
        # https://github.com/microsoft/vscode/issues/85887
        unset LS_COLORS
        function zshaddhistory() {
                return 1
        }
fi
```

Like this I don't get anything from the vscode terminal in my history, and the worst env var is gone as well. Executing a second command is still quite ugly (and slow-ish due to the big input, but much better with the 3kb I have now than with the 10kb one):

```
[adrian@claptrap:~/dev/misc]> cd /home/adrian/dev/misc ; env 'SSH_CONNECTION=xxx' OLDPWD=/home/adrian XDG_SESSION_ID=c11 USER=adrian PWD=/home/adrian HOME=/home/adrian 'SSH_CLIENT=xxx' XDG_SESSION_TYPE=tty MAIL=/var/mail/adrian SHELL=/bin/zsh XDG_SESSION_CLASS=user SHLVL=2 VSCODE_AGENT_FOLDER=/home/adrian/.vscode-server-insiders LOGNAME=adrian XDG_RUNTIME_DIR=/run/user/1000 _=/home/adrian/.vscode-server-insiders/bin/e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027/node VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH=/home/adrian/.vscode-server-insiders/bin/e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027/remote/node_modules VSCODE_LOGS=/home/adrian/.vscode-server-insiders/data/logs/20191201T162934 ANT_HOME=/usr/share/ant CONFIG_PROTECT=/usr/share/gnupg/qualified.txt 'CONFIG_PROTECT_MASK=/etc/sandbox.d /etc/fonts/fonts.conf /etc/gentoo-release /etc/terminfo /etc/ca-certificates.conf /etc/revdep-rebuild' EDITOR=/usr/bin/vi GCC_SPECS= INFOPATH=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.30/info:/usr/share/info LC_CTYPE=de_DE.UTF-8 'LESS=-R -M --shift 5' 'LESSOPEN=|lesspipe %s' MANPAGER=/usr/bin/vimmanpager MANPATH=/etc/java-config-2/current-system-vm/man:/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/man:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.30/man:/usr/lib/llvm/8/share/man:/etc/java-config-2/current-system-vm/man/:/usr/local/share/man:/usr/share/man:/usr/share/rust-bin-1.37.0/man MANWIDTH=100 OPENGL_PROFILE=xorg-x11 QUOTING_STYLE=literal PAGER=/usr/bin/less JAVA_HOME=/etc/java-config-2/current-system-vm JDK_HOME=/etc/java-config-2/current-system-vm JAVAC=/etc/java-config-2/current-system-vm/bin/javac GOPATH=/home/adrian/dev/go RIPGREP_CONFIG_PATH=/home/adrian/.ripgreprc SSH_AUTH_SOCK=/tmp/ssh-xxx/agent.715 SSH_AGENT_PID=716 GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:742:1 AMD_ENTRYPOINT=vs/server/remoteExtensionHostProcess PIPE_LOGGING=true VERBOSE_LOGGING=true VSCODE_EXTHOST_WILL_SEND_SOCKET=true VSCODE_HANDLES_UNCAUGHT_ERRORS=true VSCODE_LOG_STACK=false 'VSCODE_NLS_CONFIG={"locale":"en","availableLanguages":{}}' VSCODE_IPC_HOOK_CLI=/tmp/vscode-ipc-43c9a5b3-6518-4b05-9252-xxx.sock APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL=true PATH=/home/adrian/.vscode-server-insiders/bin/e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027/bin:/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/home/adrian/scripts:/home/adrian/.local/bin:/home/adrian/dev/go/bin PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/adrian/.python3-env/bin/python /home/adrian/.vscode-server-insiders/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 38195 /home/adrian/dev/misc/imapwatch.py 
```

**Comment by Tyriar** [comment]
> So my feature request is to either always add a space at the beginning of any command that's sent to the shell, or to add a setting that lets the user enable this if they want to use it.

If adding a space does this then it has to be done by the Python extension.

@luabud you closed (and locked) https://github.com/microsoft/vscode-python/issues/7041 but AFAICT it's about changing this line:

https://github.com/microsoft/vscode-python/blob/7ee819a3cef5072c98be4a3538bfa21546437ab9/src/client/common/terminal/service.ts#L46

to send `' ' + text`

> if [[ -n "$VSCODE_IPC_HOOK_CLI" || -n "$VSCODE_AGENT_FOLDER" ]]; then

FYI the right way to do this is to check if `$TERM_PROGRAM` is `vscode`.

**Comment by ThiefMaster** [comment]
Wouldn't it still make more sense to support this in the core? It doesn't really matter if it's the Python extension or anything else executing a command - I think nobody really expects commands not entered (or pasted) by themselves to end up in the history...

**Comment by Tyriar** [comment]
@ThiefMaster the Python extension uses an API which sends arbitrary text to the terminal, it's up to the extension to use it how they wish.

VS Code runs the env call when the first window is opened to initialize its environment (which all windows inherit). `TERM_PROGRAM` is set whenever a terminal is launched so if you only care about this inside VS Code's terminal then it should be sufficient. This is that code if you're interested:

https://github.com/microsoft/vscode/blob/a2dbfef1c1501f1915723af36e8daac1dbe296f0/src/vs/code/node/shellEnv.ts#L93-L111

**Comment by ThiefMaster** [comment]
Thanks, that looks helpful.

This `disable-user-env-probe` flag sounds like something that may avoid the problem I have altogether (my shell env is setup properly, so I don't need the `env` call the python extension adds at all, so if I can force it to be empty that'd be a good workaround).

What would be the best way of setting it in my environment (windows client, linux remote via ssh)? I tried launching vscode on Windows with `--disable-user-env-probe` (since it appears to be a command line argument) but the arg didn't get forwarded to any of the processes launched on the remote side. Googling for it doesn't really yield anything useful either.

**Comment by Tyriar** [comment]
@ThiefMaster something different happens for SSH, pretty sure there are issues discussing this sort of thing in https://github.com/microsoft/vscode-remote-ssh

**Comment by ThiefMaster** [comment]
I'd love to have a look at the issues (and code 😏) in there, but I have the feeling I'd have to become a Microsoft employee to do so, and that's something I'm currently not planning to do... ;)

(tl;dr: that repo is private)

**Comment by Tyriar** [comment]
Yeah remote release is the one. If nothing of interest in this query https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+getunixshellenvironment+is%3Aopen, you could create an issue

**Comment by pzmarzly** [comment]
Same problem with Microsoft's C++ extension: https://github.com/microsoft/vscode-cpptools/issues/2904. There's a bash workaround posted there.

**Comment by ThiefMaster** [comment]
The problem with those workarounds is that you still have vscode sending a potentially huge env command to the shell. That makes running even the simplest commands **much** slower than it'd be without the env garbage there.

**Comment by pzmarzly** [comment]
> The problem with those workarounds is that you still have vscode sending a potentially huge env command to the shell

I don't think the `env` command itself impacts the performance as much as the fact that an interactive shell is spawned (e.g. `bash` or `fish`) and it receives text over stdin, just to run a single command. That means that all your `.bashrc`/`.zshrc`/fish scripts are executed, and the syntax highlighting and autocompletion engines are triggered.

By the way, my shell of choice, `fish`, is not bash-compatible. Some VSCode extensions may break because of that (though I haven't met any so far).

I can understand @Tyriar stance ("it has to be done by the Python extension"). At least now that it's clear it's extension responsibility, I hope that at least the extensions made by MS will soon start doing it. So far that issue in `vscode-cpptools` has been ignored for over a year now, while the one in `vscode-python` has been closed over 2 weeks ago.

**Comment by ThiefMaster** [comment]
*Invoking* the env command is not the problem. But at least with zsh you can really see the performance impact of vs code *sending* a 10kb command to the terminal/shell.

**Comment by Tyriar** [comment]
@ThiefMaster the space prefix thing doesn't work on bash (macOS) for me? Pressing up after ` echo b` brings that back?

> At least now that it's clear it's extension responsibility, I hope that at least the extensions made by MS will soon start doing it. So far that issue in vscode-cpptools has been ignored for over a year now, while the one in vscode-python has been closed over 2 weeks ago.

If an extension is calling sendText to set the environment that is bad, it should use `TerminalOptions.env`. Setting it by sending text is ugly, unreliable and it can end up in shell history. Report these individually to extensions, as everything else these will get triaged by the team in relation to all the other incoming issues. Created https://github.com/microsoft/vscode-python/issues/9316

For debugging there is environment `sendText` code here:

https://github.com/microsoft/vscode/blob/502fe137129301c43cdc3da0b0516b42907d9544/src/vs/workbench/api/node/extHostDebugService.ts#L112

I think this is being done to reuse the terminals when the integrated terminals is set explicitly as the debug console and I don't think this can change.

**Comment by ThiefMaster** [comment]
> the space prefix thing doesn't work on bash (macOS) for me

Did you enable it using the `HISTCONTROL` env var? By default it's empty, so both duplicates and space-prefixed values go to the history.

**Comment by Tyriar** [comment]
@ThiefMaster oh no I didn't, but that would also be up to the extension to set that in the environment. I'll comment on that issue

**Comment by ThiefMaster** [comment]
Personally I think it should be up to the user to enable such a feature (since it depends on the shell - zsh has a different way to enable it for example). By always sending the prefix you give the user full control over whether to use this shell feature or not, without drawbacks.
