### ISSUE TITLE
Insiders intellisense will not load

### ISSUE THREAD

**Issue by Cellv2** [microsoft/vscode#85889]
### VSCode Version:
Version: 1.41.0-insider (user setup)
Commit: e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027
Date: 2019-11-29T09:09:48.304Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

### OS Version:
Windows 10 Version 1903 (OS Build 18362.476)

### Steps to Reproduce:
Currently unknown how to get it into the state that I have, but opening anything in VS Code (non-insiders, Version: 1.40.2 (user setup), Commit: f359dd69833dd8800b54d458f6d37ab7c78df520) does not have the problem

I did see several back to back warnings about the TS server not being able to load correctly, and I think the issue happened immediately after this but am not positive

### Does this issue occur when all extensions are disabled?: Yes/No
Yes

### Expected Behaviour:
Intellisense works

### Actual Behaviour:
An (infinite?) 'loading...' appears as below. I've left this at least 5 minutes to see if anything loads and it doesn't appear to

![image](https://user-images.githubusercontent.com/22135118/69917286-39f31480-145c-11ea-8623-251b2be74b31.png)

This seems to happen for anything involving intellisense at all, and seems to affect both the OOTB things (such as Emmet) and extension snippets

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.01GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
turbo-console-log|Cha|1.3.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.32.0
javascript-ejs-support|Dig|1.1.3
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|3.11.0
vscode-todo-plus|fab|4.14.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.15
discord-vscode|icr|3.13.0
sublime-babel-vscode|jos|0.2.10
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
cpptools|ms-|0.26.2-insiders3
csharp|ms-|1.21.8
powershell|ms-|2019.11.0
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.2
es6-css-minify|olb|3.3.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.0
ejs-snippets|Tao|0.1.0
highlight-matching-tag|vin|0.9.5
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.6.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please help us in providing steps to reproduce? Probably give us a sample repo on which we can reproduce this.

Also did you try repro this by disabling all installed extensions?

**Comment by Cellv2** [comment]
Yes, I'm able to replicate this by doing code-insiders --disable-extensions. With this said, I've tried a few other things here:

| Action | Result |
|--------|--------|
|Update to latest VS Code Insiders|Able to replicate|
|Cloning the repo into a new folder|Unable to replicate|
|Copy paste the project folder|Unable to replicate|
|Zipping then unzipping the project folder|Unable to replicate|

I've noticed that I get 'Initializing JS/TS languag...' (language service?) on the bottom panel, and that appears for as long as the intellisense loading is happening.

![image](https://user-images.githubusercontent.com/22135118/69983291-3a5be000-152e-11ea-8af5-651c748bf583.png)

From my point of view, I'm happy to close this as simply cloning the project again resolved it. I'm unsure if it's worth investigating further, but I'd guess it would be hard to diagnose.

**Comment by Cellv2** [comment]
Couldn't find the exact dependency, but seems to be a combination of react-router-dom, react-bootstrap and/or bootstrap. Steps to repro below:

Open terminal and **swap to any drive other than C:\\**. I was able to replicate this on my E/F/G/H drives, but not my C drive.

In terminal:
```
git clone https://github.com/Cellv2/vscode-insiders-bug-85889.git
cd vscode-insiders-bug-85889
npm i
code-insiders.cmd --disable-extensions .
```

In the editor:
```
Open src\App.js
On line 15, try bringing up any intellisense (example: imp for import)
```

**Comment by sandy081** [comment]
Not sure if it is VS Code related as you said your nom dependencies are broken. Probably you have to fix that.

**Comment by Cellv2** [comment]
@sandy081 Considering this is working completely fine on VS Code (non insiders) but is broken on insiders and has worked fine on insiders in the past, do you still suggest the same thing?

**Comment by sandy081** [comment]
I see, in such case let me reopen it.

**Comment by mjbvz** [comment]
Works fine for me on macos with latest insiders:

![Screen Shot 2019-12-04 at 3 59 00 PM](https://user-images.githubusercontent.com/12821956/70191869-03610800-16af-11ea-8c37-b405400c7738.png)

Will test on windows too

**Comment by mjbvz** [comment]
Thanks. Confirmed that this seems to happen when using a non c-drive on windows. Opened https://github.com/microsoft/TypeScript/issues/35512 to track this upstream
