### ISSUE TITLE
New folder navigation makes it impossible to delete empty file

### ISSUE THREAD

**Issue by tomasaschan** [microsoft/vscode#85880]
Issue Type: <b>Bug</b>

1. Inside the workspace, create a few folders inside each-other. For example, `mkdir -p foo/bar/baz`. `foo/bar/baz` shows up as a single entry in the File Explorer pane, which is pretty awesome.

2. Navigate to either folder in the File Explorer by focusing it and using the arrow keys.

3. Try to delete it by pressing the `Delete` key.

Expected result: The folder is deleted, possibly after a dialog asks me if I really want to.

Actual behavior: An error message is shown stating "Cannot read property `isDirectory` of undefined."

VS Code version: Code - Insiders 1.41.0-insider (e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027, 2019-11-29T09:09:48.304Z)
OS version: Windows_NT x64 10.0.19033
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|Memory (System)|5.96GB (3.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|Memory (System)|5.96GB (3.19GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
haskell-linter|hoo|0.0.6
hoogle-vscode|jca|0.0.7
language-haskell|jus|2.6.0
haskero|Van|1.3.1
stylish-haskell|vig|0.0.10
vscode-docker|ms-|0.8.2
remote-containers|ms-|0.86.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.41.1
vscode-remote-extensionpack|ms-|0.17.0
scala|sca|0.3.8

</details>

**Comment by roblourens** [comment]
I was about to file the same issue. Here's what my debugging showed

- ExplorerView#getContext returns an array with the same element twice
- In the deleteFiles handler, `resources.distinctParents` returns an empty array, I think it isn't expecting the same element multiple times and both are filtered out
- Then it fails here

![image](https://user-images.githubusercontent.com/323878/69918356-b6b6cc00-1425-11ea-9abb-749b350b406e.png)
