### ISSUE TITLE
Debugger Cannot launch program if the file has a dot on beginning of the name

### ISSUE THREAD

**Issue by Josema** [microsoft/vscode#85882]
![image](https://user-images.githubusercontent.com/1819888/69913845-98f56100-143d-11ea-8bfd-3cfd664b359d.png)

- VSCode Version: 1.40.2
- OS Version: Windows 10

This is my conf:
```
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/test/.quick.js"
        }
}
```

The path is correct and the file exists. If i remove the dot on the file it works. Is this a normal behavior.

**Comment by connor4312** [comment]
We since have a [new debugger](https://github.com/microsoft/vscode-js-debug/) where this seems to be fixed. Please let us know if you're still running into problems, and if so open an issue on that repo.
