### ISSUE TITLE
Code formatting by Shift + ALT + F stops working

### ISSUE THREAD

**Issue by grizlikoff-code** [microsoft/vscode#85888]
Issue Type: <b>Bug</b>

Code formatting by Shift + ALT + F stops working.
If I select "Format with document using ..."
Several identical formatting profiles appear:

"C / C ++ by default"
"C / C ++ by default"
"C / C ++ by default"
"C / C ++ by default"
and only one of them formats the code.
Setting this profile by default does nothing.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz (8 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-language-pack-ru|MS-|1.40.2
cpptools|ms-|0.26.1
platformio-ide|pla|1.10.0
code-spell-checker|str|1.7.20
code-spell-checker-russian|str|0.2.2

</details>

**Comment by gjsjohnmurray** [comment]
Does this reproduce if you disable all extensions except for cpptools?
