### ISSUE TITLE
deb post install script writes to /etc/apt/sources.list.d

### ISSUE THREAD

**Issue by vlijmenfileer** [microsoft/vscode#85881]
Issue Type: <b>Bug</b>

After adding a deb source for vscode:
deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
in /etc/apt/sources.list.d/microsoft-vscode.list
the deb post install script writes its own variant of that file under its own name.

See:
https://github.com/microsoft/vscode/blob/master/resources/linux/debian/postinst.template

I'm not sure if it is a bug in the sense that it goes against Debian packaging rules, but applications secretly dropping their own package sources in one of the most fundamental OS configuration places sure is a breach of trust at the very least.  Managing /etc/apt is the administrator's job, not that of a random package maintainer.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.2.0-0.bpo.3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|7.75GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
vscode-markdownlint|Dav|0.32.0
vscode-azurestorage|ms-|0.7.2
azure-account|ms-|0.8.7
powershell|ms-|2019.11.0
azurerm-vscode-tools|msa|0.8.2
vscode-yaml|red|0.6.1

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/22145

That was open for 2 years and no one seemed to care enough to contribute, I'd still accept a PR for it though.
