### ISSUE TITLE
Change All Occurrences messes up after positioning with mouse

### ISSUE THREAD

**Issue by ssomers** [microsoft/vscode#85891]
Issue Type: <b>Bug</b>

- In Rust or Go or probably any type of file:
- Right-click on an identifier that appears elsewhere too, perform Change All Occurences => other occurrences on screen get selected
- Left-click somewhere inside the identifier to position the cursor => other occurrences are still entirely selected
- Start typing => replaces the other occurrences instead of inserting there

VS Code version: Code - Insiders 1.41.0-insider (e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027, 2019-11-29T09:09:48.304Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (11.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
Yeah, change all occurrences is just a fast gesture fore search and replace (inside file). For a semantic operation you should Rename.

**Comment by ssomers** [comment]
Quick search and replace is exactly what I expect. I have no idea what you mean with semantic operation. When I have started Change All Occurrences, then I expect all occurrences to change in the same way until at some point (like pressing the Esc key) the mode ends. That is, as far as I know, what happens if you use cursor keys and text keys. If instead you mouse-click somewhere in the original text, then ideally the same thing would happen as if you pressed the cursor keys towards the same location, or (less ideally) the Change All Occurrences mode ends. What happens now is that the change of cursor is not relayed to the other occurrences, the mode does not end, and subsequent moves (with cursor keys) or edits are applied incorrectly to the other occurrences.
