### ISSUE TITLE
Debug console missing output when using new node DA

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85897]
- Debug some script like

```js
console.log(`1`);
console.log(`2`);
debugger
```

and

```json
{
	"type": "pwa-node",
	"request": "launch",
	"name": "Run",
	"program": "${file}",
	"trace": true,
},
```

- Close the debug console
- Press F5, hit debugger statement
- Open the debug console
- Sometimes, there is no output
- Press F8, you will see the output after this point

I only see this when using vscode-pwa, but it is sending the output events, and I only see it when the debug console is initially closed.

FYI @connor4312

**Comment by isidorn** [comment]
As far as I know we are not yet shipping PWA, this milestone I have a lot of issue, thus moving this to December and I plan to look into debt week. If you need this for the release please let me know
