### ISSUE TITLE
Delay with rendering description of extension

### ISSUE THREAD

**Issue by lass-0** [microsoft/vscode#85896]
Issue Type: <b>Performance Issue</b>

Ever since I started using VS code, there has been this 10-30 second delay when selecting extensions and seeing the description, and it's really starting to annoy me. The javascript profiler says that most of it is idling..? https://i.imgur.com/nhYcjmq.png. I have run with and without GPU, and with and without --force-renderer-accessibility. It is not an internet issue, as I can view the contributions tab fine, but not the details or changelog.

VS Code version: Code - Insiders 1.41.0-insider (e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027, 2019-11-29T09:09:48.304Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (11.51GB free)|
|Process Argv|--verbose --force-renderer-accessibility|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   102	  4252	code-insiders main
    0	    68	  3888	   shared-process
    0	    14	  5512	   electron-crash-reporter
    2	    57	  6552	   window (Issue Reporter)
    2	   119	  8096	   gpu-process
    0	   205	  8368	   window (Extension: C/C++ - Visual Studio Code - Insiders)
    0	    61	 10252	     extensionHost
    0	    30	  7140	       "C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=10252
    0	   198	  8620	   window (undefined)
    0	    65	  9320	   window (undefined)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by mjbvz** [comment]
@lass-0 Do you see a similar delay for the release notes? What about for a markdown preview?

**Comment by lass-0** [comment]
yes

**Comment by mjbvz** [comment]
Are you on a corporate network or using a firewall that could be blocking or delaying some network requests?

**Comment by lass-0** [comment]
no

**Comment by mjbvz** [comment]
How long to opening a page such as https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines from the online marketplace normally take? Any other apps effected?

**Comment by mjbvz** [comment]
Also, can you share the complete profile you captured? I want to see which part of the rendering it is stalling on
