### ISSUE TITLE
Several windows look blank

### ISSUE THREAD

**Issue by wedeluxe** [microsoft/vscode#85899]
Issue Type: <b>Bug</b>

My VS Code session has 10 windows open. 6 out of 10 look blank right after starting VS Code. Blank windows show appropriate tooltips when hovering things, so content still exists. Triggering a repaint of a blank window (e.g. restoring, then maximizing again) is a temporary help. And by the way, unblanking one window blanks another.

As I understand, the issue is supposed to be fixed in VS Code 1.40.2.
But actually, 1.40.2 introduced this issue on my Arch Linux PC.

After upgrading  these two packages

```
code 1.40.1-1 -> 1.40.2-1
electron6 6.1.4-2 -> 6.1.5-1
```

I noticed said behavior. Never saw that in 1.40.1 and before.

VS Code version: Code - OSS 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-26T23:44:27.629Z)
OS version: Linux x64 5.3.13-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz (8 x 3534)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.53GB (0.85GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
extended-cursormove|Bil|0.0.2
reflow-paragraph|Tro|1.3.0
lorem-ipsum|Tyr|1.2.0
overtype|ada|0.2.0
Bookmarks|ale|10.6.0
line-jumper|ale|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.2.0
vscode-great-icons|emm|2.1.47
vscode-projects-plus|fab|1.23.2
php-debug|fel|1.13.0
file-icons|fil|1.0.19
vscode-firefox-debug|fir|2.5.3
auto-close-tag|for|0.5.6
vscode-insertdatestring|jsy|2.2.4
restructuredtext|lex|116.0.0
vscode-docker|ms-|0.8.2
python|ms-|2019.11.50794
cpptools|ms-|0.26.1
debugger-for-chrome|msj|4.12.2
shunt|myc|1.0.1
java|red|0.53.1
yo|sam|0.9.3
bracket-jumper|sas|1.1.8
rewrap|stk|1.9.1
vscode-gulp|tan|0.0.4
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.20.0
vscode-icons|vsc|9.6.0
vscode-todo-highlight|way|1.0.4
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by deepak1556** [comment]
I am unable to repro it on ubuntu, I highly doubt this is distro specific, how did you install the package ?

Also can you test with the exploration build https://az764295.vo.msecnd.net/exploration/22c3db00ec057fecf0144c4c7f8c6bc6cb60e5d6/code-exploration-1575406103.tar.gz ? Thanks!

**Comment by wedeluxe** [comment]
The packages I'm using are in the official Arch binary repositories.

I'd love do do more testing, but prior to installing the exploration build, I need to know:
What is an exploration build (research on Bing and Google didn't reveal any useful insight)?
Will or can it mess up settings/configuration of the regular, stable VS Code?

**Comment by deepak1556** [comment]
> What is an exploration build (research on Bing and Google didn't reveal any useful insight)?

They are based on a newer version of electron, chromium and nodejs compared to stable and insiders. The current version is based on electron 7 https://github.com/microsoft/vscode/pull/83796

> Will or can it mess up settings/configuration of the regular, stable VS Code?

No it won't mess with your stable version settings. Stable, insiders and exploration maintain their own respective configurations, they don't interact with each other.

**Comment by ivan** [comment]
I also have this issue on 1.41.1 with several vscode windows being blank until I resize them. I am running NixOS master, xfce4, no compositor in Xorg, and see the same issue on a machine using NVIDIA and another using radeon. My Chromium instances work fine and never blank. Reverting to vscode 1.40.1 seems to fix it.

**Comment by rzhao271** [comment]
Does this issue still occur on the latest version of VS Code?

**Comment by wedeluxe** [comment]
Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91


Upgraded to the latest version today (see above).
The issue didn't show up.
Actually, I didn't notice this to happen in the last couple of years.
