### ISSUE TITLE
Doesn't reverse multiple files in git

### ISSUE THREAD

**Issue by dryganets** [Microsoft/vscode#8590]
- VSCode Version: Code - Insiders 1.3.0-insider (a21c12346f388e51858c930875ca30968604c116, 2016-06-30T05:03:45.119Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:
1. Create few files not added to git
2. in git panel select all files you created and press reverse button
3. In warning dialog select Clean Changes

Expected result - all files reverted
Actual result - nothing happens
The only way to revers is one by one

**Comment by dryganets** [comment]
It's kind of random, in some cases it works and in some it doesn't

but its really easy to reproduce it

**Comment by bpasero** [comment]
@dryganets what is your git version?

**Comment by dryganets** [comment]
git version 2.6.2

**Comment by dryganets** [comment]
I'm using insiders edition of Visual Studio Code btw

**Comment by joaomoreno** [comment]
@dryganets Can you create a screencast, movie, gif of your interaction?

**Comment by dryganets** [comment]
part one create files from command line:
http://www.screencast.com/t/ayE0ZpxiODT

part two: reverting changes from VSO
http://www.screencast.com/t/S83qE9rbHO

**Comment by joaomoreno** [comment]
First off, awesome videos, they really help.

Second, wow, very bad bug, thanks for catching it!

**Comment by joaomoreno** [comment]
Great catch!

**Verification:**

- Create two new files in a git repository, in separate directories: `A/a.js` and `B/b.js`.
- Multi-select them
- Undo them, like in the screencast above
- They should successfully get removed from the repository.
