### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by Sabarishtgi** [microsoft/vscode#85905]
Issue Type: <b>Bug</b>

In My Visual Studio  Code Terminal is not working it is Blank ,it is hard to run the program.So Please consider this issue For me
![image](https://user-images.githubusercontent.com/50689455/69933083-7aea3800-14f3-11ea-9f88-eb40855e6314.png)
![image](https://user-images.githubusercontent.com/50689455/69933116-9b19f700-14f3-11ea-8119-0a18c320ed02.png)

Thanks in Advance.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.0.6000

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics     (4 x 2195)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|6.96GB (3.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Sabarishtgi** [comment]
> /findDuplicates

Sorry Sir i can't get it

**Comment by gjsjohnmurray** [comment]
Your version info makes me think you are using Windows Vista. Is that correct?

**Comment by Sabarishtgi** [comment]
no sir windows 7 sir

**Comment by gjsjohnmurray** [comment]
> VS Code version: Code 1.40.2 (f359dd6, 2019-11-25T14:54:45.096Z)
> OS version: Windows_NT x64 6.0.6000

Strange then that the issue reporter put 6.0.6000 as your OS version. The Internet (e.g. [here](http://www.jrsoftware.org/ishelp/topic_winvernotes.htm)) seems convinced this is Vista.

From a Windows command shell, what does the `ver` command report?

The dropdown in the first of your two screenshots shows "1:powershell". On the second one it begins "2: " but I can't see the full path.

Does anything appear in your Terminal if you click into it and then press <kbd>Enter</kbd>?

In your settings.json what is `terminal.integrated.shell.windows` set to?

**Comment by gjsjohnmurray** [comment]
@Sabarishtgi are you starting code.exe from a shortcut that you have set to use Vista compatibility mode? If so, why?

**Comment by Sabarishtgi** [comment]
Okay sir i will check it thanks.
