### ISSUE TITLE
Test: Viewlet/ViewContainer Refactor

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#85908]
Refs #85566

- [x] anyOS @isidorn 
- [x] anyOS @sandy081  

Complexity: 3

Test the branch for the PR to ensure there are no regressions introduced so that we can be in a great starting state for next iteration.

**Comment by isidorn** [comment]
Sounds good. Imho this touches a lot of areas and will require a bit more time, thus increasing complexity to 3.

**Comment by isidorn** [comment]
Great work. I could find some issues, but they were mostly present before your refactoring.
