### ISSUE TITLE
keyboard language change is focus main menu

### ISSUE THREAD

**Issue by Nerossoul** [microsoft/vscode#85916]
Issue Type: <b>Bug</b>

Hello
I am from Russia
my keyboard contains to languages: English and Russian/
 I change keyboard language by alt+shift combination

after the update, alt+shift combination focuses me on the main menu and I need to click to the editor now to continue to type my code. each time when I change the language by alt+shift it unfocuses my editor

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2338)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.68GB (0.22GB free)|
|Process Argv|--no-sandbox --unity-launch /home/nerossoul/02 Проекты/PlayAvto/001_Catalogization|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
calva-fmt|cos|0.0.38
clojure4vscode|cos|1.3.71
paredit-revived|cos|0.1.22
vscode-eslint|dba|1.9.1
prettier-vscode|esb|3.11.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
vue-snippets|hol|0.1.11
vue|jcb|0.1.5
vscode-phpfmt|kok|1.0.30
vue|liu|0.1.5
MagicPython|mag|1.1.0
python|ms-|2019.11.50794
csharp|ms-|1.21.8
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.22.6
es6-css-minify|olb|3.3.1
format-html-in-php|rif|1.6.1
LiveServer|rit|5.6.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.8.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.0
jinja|who|0.0.8
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Thanks for the report, I merging this to https://github.com/microsoft/vscode/issues/85405, please follow that issue for updates.
