### ISSUE TITLE
Shitf insert into VSCode built-in terminal

### ISSUE THREAD

**Issue by spartan195** [microsoft/vscode#85918]
Linux version
I've noticed while working with docker in the built in terminal that i cannot properly copy and paste text in the terminal.

For example if I want to select text and copy it with Shift-insert like in my main terminal it does not work, it just print the default clipboard, not the text selected clipboard

**Comment by Tyriar** [comment]
You can also try this keybinding to get this behavior:

```
{ "key": "shift+insert",                 "command": "workbench.action.terminal.paste",
                                     "when": "terminalFocus" }
```
