### ISSUE TITLE
Renamed a folder with many files, then got an empty folder. I have disabled all extensions.

### ISSUE THREAD

**Issue by pinksky** [microsoft/vscode#85912]
- VSCode Version:1.40.2
- OS Version:Darwin x64 17.7.0
- V8: 7.6.303.31-electron.0
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0

Steps to Reproduce:

1. Renamed one folder from lspEditor to LspEditor.
2. Opened file initlsp.ts from file index.tsx by gotoDefinition, both of the two files were within the folder LspEditor.
3. The folder name of LspEditor on the nav is old lspEditor.
4. Try to open the file within the folder LspEditor.
5. Can't find any files. The folder changed to be an empty folder.
![image](https://user-images.githubusercontent.com/20432533/69937302-5bfc9d80-1515-11ea-9040-e2472e7eefba.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/72174
