### ISSUE TITLE
Settings Sync Concept

### ISSUE THREAD

**Issue by rickyzhangca** [microsoft/vscode#85911]
Some thoughts on approaches to settings sync: visualizing sync status

![visualization1@2x](https://user-images.githubusercontent.com/16908811/69936319-7008b680-14a5-11ea-9bb2-5f993b85b1a4.png)

![finished@2x](https://user-images.githubusercontent.com/16908811/69936296-5ebfaa00-14a5-11ea-949c-5a69d62a925c.png)

![demo1](https://user-images.githubusercontent.com/16908811/69936378-99c1dd80-14a5-11ea-8fbf-0793675ebe12.gif)

![temp@2x](https://user-images.githubusercontent.com/16908811/69936912-27ea9380-14a7-11ea-8bc6-2838a93a2634.png)

**Comment by misolori** [comment]
Thanks for the suggestions! As we're actively developing this feature we'll keep these ideas into consideration.
