### ISSUE TITLE
Explorer always show Windows System Folder "System Volume Infomation"

### ISSUE THREAD

**Issue by coolxxy** [microsoft/vscode#85910]
Issue Type: <b>Bug</b>

On my windows machine, my  golang working folder is a partion mounted on `C":\User\xxx\go`, and when I opened this foler in vscode, the explorer always show Windows System Folder "System Volume Infomation".

![image](https://user-images.githubusercontent.com/11879017/69937063-a7627c00-1514-11ea-86f1-0f08d9a732cc.png)

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
project-manager|ale|10.9.1
mdmath|goe|2.4.0
latex-workshop|Jam|8.4.2
markdown-formatter|mer|0.7.6
python|ms-|2019.11.50794
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.1
csharp|ms-|1.21.8
Go|ms-|0.11.9
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
markdown-preview-enhanced|shd|0.5.0
markdown-pdf|yza|1.4.1

(1 theme extensions excluded)

</details>
a into your clipboard because it was too large to send. Please paste.

**Comment by isidorn** [comment]
Well the file is there, vscode is not adding it.
Can you reproduce this with other programs? For example Visual Studio, Sublime, Atom etc...
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by coolxxy** [comment]
That folder is a windows system-protected folder, and I should add it to ignore folder. It is my problem.
