### ISSUE TITLE
Does it support blackbox?

### ISSUE THREAD

**Issue by 1316346949** [microsoft/vscode#85917]
Does it support blackbox when debugging ? just like chrome?

**Comment by IllusionMH** [comment]
/question

Depends on debug extension:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome
https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome#skip-files-blackboxing-ignore-files

**Comment by 1316346949** [comment]
> Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

thanks

**Comment by 1316346949** [comment]
> /question
> 
> Depends on debug extension:
> https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome
> https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome#skip-files-blackboxing-ignore-files

thanks
