### ISSUE TITLE
Rendering issues with VSCode on Ubuntu in VirtualBox

### ISSUE THREAD

**Issue by lecode-official** [Microsoft/vscode#8591]
Version 1.2.1
Commit fe7f407b95b7f78405846188259504b34ef72761
Datum 2016-06-14T12:54:38.105Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. I have a Ubuntu installed on VirtualBox with graphics acceleration enabled and 128MB of graphics memory
2. I freshly installed VSCode on the fresh Ubuntu installation
3. VSCode does not render properly
4. Also VSCode is always in the foreground (on top of all other windows)
5. I have a separate virtual machine with the latest version of Linux Mint installed and there I have no problem with the rendering, since both virtual machines have the same setting, I guess it has nothing to do with VirtualBox
6. Funny enough, when I take a screen shot I only get this, which is not the actual rendering problem I see, when not taking a screen shot. Normally I only see the dark gray background of VSCode, some lighter gray patches, and the cursor:
![Screenshot](https://cloud.githubusercontent.com/assets/10341491/16504176/e1eaabd6-3f16-11e6-9490-166118cddd27.png)

**Comment by lecode-official** [comment]
By the way, I have a Surface Pro 4 and have set the UI scaling of Ubuntu to 1.75 to accommodate the high DPI of the screen. I have checked, setting the UI scaling back 1.0 still produces the same rendering problem. So maybe it could have to do anything with that?

**Comment by bpasero** [comment]
@lecode-official does this help? https://code.visualstudio.com/Docs/supporting/faq#_vs-code-main-window-is-blank

**Comment by lecode-official** [comment]
Thank you so much, that solved my problem.

**Comment by cobir** [comment]
thank you!!!
