### ISSUE TITLE
Do not include git files in search results

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#85915]
This has started recently, and it is annoying for me:

* when having many tabs opened, including diff editors
* and I want to do a cross-cutting refactoring, like renaming something in multiple places which don't work via <kbd>F2</kbd> (like API), I use the search viewlet.
* the search viewlet has now multiple times misled me and I ended up in what appears to be the "old" version of the file via the git fs provider.
* this is highly annoying, in this case this is clearly separated in the viewlet, but I've run into situations where this was the only result and it was no longer clearly separated.

![image](https://user-images.githubusercontent.com/5047891/69940651-11fac400-14e3-11ea-9497-896f0bd452fd.png)

**Comment by joaomoreno** [comment]
Yup that's pretty ugly, I seen it too. This is a consequence of using a FileSystemProvider for git, instead of the TextDocumentContentProvider API. cc @eamodio 

I wonder if we can filter out search documents based on URI scheme?

**Comment by roblourens** [comment]
Should I specifically exclude the `gitfs` scheme or is there something else that distinguishes these from other documents?

I could ignore docs with a scheme that doesn't match that of a workspace folder (but including untitled docs)?

**Comment by roblourens** [comment]
I think excluding git docs specifically might be the best fix, I don't want to make FileSystemProviders less useful by excluding their docs from search all the time.

**Comment by alexandrudima** [comment]
:+1: IMHO the safest change so late is to exclude git specifically. The best would be for a FileSystemProvider to opt-in/opt-out of searching.

**Comment by joaomoreno** [comment]
Agreed, thanks @roblourens!

**Comment by jrieken** [comment]
I think this problem isn't exclusive to the FileSystemProvider API because there many sources for editor model. @roblourens How does this work for other resources, like any document from a TextDocumentContentProvider, things like inmemory resources, or RHS diff editor etc? Why aren't they searched?

**Comment by roblourens** [comment]
I think that everything else is handled by

```ts
if (!this.fileService.canHandleResource(resource)) {
	return;
}
```

**Comment by jrieken** [comment]
Yeah - that should catch most of it but I also see [special handling](https://github.com/microsoft/vscode/blob/293cabc6a15616ea0093360dacc6fd8cc3a2cfe0/src/vs/workbench/services/search/common/searchService.ts#L395) for untitled files and the `search-result` mode. It looks like the search service is missing a concept of "ignored schemes" or phrased different, while it only has a search for provider for the `file`-scheme it seems to text-model-search in almost all other files. So, question is if the text-model-search should only be attempted for schemes for which a provider is registered?

**Comment by roblourens** [comment]
> So, question is if the text-model-search should only be attempted for schemes for which a provider is registered?

You mean a search provider? Maybe. I don't know what all the different usecases of fs providers are and how many we want to search vs not search. I think we should probably search everything by default, exclude some things like this, and figure out what people complain about.
