### ISSUE TITLE
Test new workspace event API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#85929]
Refs: https://github.com/microsoft/vscode/issues/43768

- [x] any @deepak1556 
- [x] any @dbaeumer 

Complexity: 3

There are new event that fire *before* and *after* a file or folder is being created, renamed, and deleted. These events are `vscode.workspace.onWillRename`, `...onDidRename`, `..onWillCreate`, `...onDidCreate`, `...onWillDelete`, and `...onDidDelete`. Test

* these events are fired when performing file operations via the explorer or the `vscode.workspace.applyEdit` API
* these events are *not* fire when performing them "on disk", e.g using the cmd line, another application, or the `vscode.workspace.fs` API. 
* the will-events allow to register a promise that is awaited before performing the operation
* this works when deleting, moving many files/folders
* the jsdoc is easy to understand

**Comment by jrieken** [comment]
fyi - use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.d.ts` and/or `vscode.proposed.d.ts`

**Comment by jrieken** [comment]
fyi - this should be finalised API but the PR didn't make it in time. So, the API is still in proposed but won't change anymore. (In master it's moved to stable)

**Comment by dbaeumer** [comment]
Worked nicely for me. I tested under Windows.

**Comment by deepak1556** [comment]
Works pretty good on macOS 👍 , identified a couple of edge cases.
