### ISSUE TITLE
Search view buttons become insensitive when switching views and search is active.

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#85921]
Perform a search in the search window, switch to the terminal or anything else (while the search is still running) and switch back to the search view, then the menu buttons become insensitive.

![image](https://user-images.githubusercontent.com/9846892/69958239-a6c1e980-1504-11ea-99d8-732281dac093.png)

Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
I can repro this in 1.40, but not Insiders. I think it has been fixed.

**Comment by psclkhoury** [comment]
@roblourens In Insiders, one scenario is fixed but there is still one that isn't. If you make a search and then hide the search view, let the search complete then switch back to it. In that scenario the buttons are insensitive.

Version: 1.41.0-insider (system setup)
Commit: 97855786a014be2440751b038b373c3726e11fe8
Date: 2019-12-03T05:40:39.806Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
I definitely don't see that, how do you hide the search view?

**Comment by psclkhoury** [comment]
@roblourens I usually do ctrl + B to toggle the activity bar visibility, or switch to the EXPLORER view or any other view. We have a big code base so the search usually takes more than 5 seconds so it gives me enough time to hide the search view before the search is done.

**Comment by roblourens** [comment]
Oh, during  the search, now I see it thanks
