### ISSUE TITLE
Early testing of forwarded ports UI

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#85926]
ref: https://github.com/microsoft/vscode-remote-release/issues/1777

Complexity: 3

- [ ] Windows @JacksonKearl 
- [x] non-Windows @isidorn 

You can enable the "Tunnels"(name not final, it will probably be called Forwarded Ports) view with `"remote.forwardedPortsView.visible": true` and then connecting to a remote (not WSL). It will show in the Remote Explorer view. The setting is temporary and for testing. If you add the setting after connecting you'll need to reload.

- Verify that the "Tunnels" view shows somewhere under the targets view.
- Verify that it only shows when you have the remote you are connected to in the drop down.
- Verify that you can forward a port by using the "Add a Port..." tree item or the "+" in the view title.
- Verify that the flow for forwarding a port makes sense.
- Verify that the input box behaves in a way that you expect it to. See the "Rename" context menu command in the file Explorer for ideas.
- Verify that the port is actually forwarded.
- Verify that all of the context menu commands work in a way that you expect them to. Same for the inline commands.

**Comment by isidorn** [comment]
My Win VM is in a bad state. Swaping platforms with @JacksonKearl hope that is ok.

**Comment by JacksonKearl** [comment]
The above also apply to Windows. Also, not sure if this is a standard syntax, but in containers we use "2222:22" to say "forward remote port 22 to local port 2222. That could be nice to have as a way to specify what the local port should be.
