### ISSUE TITLE
Test Remote explorer drop-down UI

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#85927]
ref: https://github.com/microsoft/vscode-remote-release/issues/1778

- [x] Windows @dbaeumer 
- [x] MacOS @octref 
- [x] Linux @sbatten 

Complexity 3

- Verify that only the views for the remote type currently in the drop-down show.
- Verify that your view sizes and positions are preserved when you switch with the drop-down.
- Verify that when you connect to a remote that remote type is shown.
- Verify that your drop-down choice is saved per workspace.
- Verify that you can find the help info.
- Verify that the help info works, and that if you're connected to a remote only the help info for that remote type is shown.
- Play around with remote explorer and see if you can break it.

**Comment by dbaeumer** [comment]
Tested under Windows: WSL 2 and Docker on WSL 2 (lightweight VM)
