### ISSUE TITLE
Copying data from debug hover doesn't copy everything

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#85922]
I have a vector with 20 elements, I want to copy the values but I noticed that items that are no longer visible are deselected.

So I selected all the elements starting from 0
![image](https://user-images.githubusercontent.com/9846892/69958729-ba218480-1505-11ea-9b98-9f7d13db6600.png)

Now if I scroll back up, the items that were not visible are no longer selected and therefore not copied.
![image](https://user-images.githubusercontent.com/9846892/69958785-d2919f00-1505-11ea-8787-4f344592a69f.png)

Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
The issue here is that we use the tree as the imlementation detail of the hover.
The tree is virtualised thus the native selection does not work nicely.
The best workaround for this is to use Copy Value from the WATCH view or from the VARIABLES view.

Though leaving this open as a feature request

**Comment by psclkhoury** [comment]
@isidorn I cannot really use Copy Value from the WATCH view because it only copies 1 value at a time. It would be more useful if I can copy all the values in the vector at once.
