### ISSUE TITLE
Disable the initial telemetry notification

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#85920]
- VSCode Version: Any recent version (>= 1.37.0)
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Launch a fresh instance of VSCode
2. wait a few seconds
3. a popup with "Help improve VSCode ..." appears in the notification area, even when telemetry is disabled

Does this issue occur when all extensions are disabled?: Yes

I'd like to disable this notification for running automated test on an extension that I am developing, as the telemetry notification is interfering with those displayed from my extension. I assume that this notification is displayed only once, since I haven't seen it in my development instance of vscode. What is the appropriate setting/flag for that?

**Comment by dcermak** [comment]
Any updates on this? This notification is really annoying as it results in my automated tests being extremely flaky.

**Comment by isidorn** [comment]
This should no longer happen. Thus closing
