### ISSUE TITLE
Visual Studio code hangs when stopping and starting angular cli serve

### ISSUE THREAD

**Issue by noam-honig** [microsoft/vscode#85937]
We have written the needed data
Issue Type: <b>Bug</b>

Visual studio code hangs when I use it's tasks to run ng serve.

I'm using angular cli 8.3.20
Steps to reproduce:
1. ng new some-project
2. cd some-project
3. code .
4. Ctrl Shift P, run Task npm:start
5. Choose $tsc-watch as the problem matcher
6. wait for it to run.
7. Click on the garbage can to stop.
8. Ctrl Shift P to run again
It'll hang and eventually show the message box:
[Window Title]
Visual Studio Code

[Main Instruction]
The window is no longer responding

[Content]
You can reopen or close the window or keep waiting.

[Reopen] [Keep Waiting] [Close]

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (14.02GB free)|
|Process Argv|--folder-uri file:///c%3A/Repos/hug-moms|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
vscode-simpler-icons|dav|1.6.5
githistory|don|0.4.9
gitlens|eam|10.2.0
angular2-switcher|inf|0.2.0
TypeScriptImport|kev|1.17.0
csharp|ms-|1.21.8
debugger-for-chrome|msj|4.12.2
vscode-scss-formatter|sib|1.4.2
spellchecker|swy|1.2.13
sass-indented|syl|1.7.1
markdown-all-in-one|yzh|2.5.1

</details>
 into your clipboard because it was too large to send. Please paste.

**Comment by alexr00** [comment]
Does the issue reproduce if you disable all extensions?

**Comment by noam-honig** [comment]
Hi, Yes, I've disabled all my extensions and the problem still occurs

Here is the info from VS now without the extentions:

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (18.84GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by noam-honig** [comment]
This also happens to me when I use kill terminal to kill other npm tasks. for example git push

**Comment by alexr00** [comment]
Thanks for the additional details! You're seeing https://github.com/microsoft/vscode/issues/71966. Until it's fixed or until there's a better work around, you can try setting `terminal.integrated.windowsEnableConpty` to false. This will cause other problems, but it should stop the freezing.
