### ISSUE TITLE
Failed to install 'ms-python.python'

### ISSUE THREAD

**Issue by pelx** [microsoft/vscode#85936]
the extention failed to install. All I can see "Python extention loading". I swithed to trace level log. Where can I find the log to send it to you?

**Comment by sandy081** [comment]
Where are you seeing this `Python extension loading` message?

**Comment by pelx** [comment]
in the status bar:

    On Monday, 2 December 2019, 15:48:23 GMT, Sandeep Somavarapu <notifications@github.com> wrote:  
 
 
Where are you seeing this Python extension loading message?

**Comment by sandy081** [comment]
Installation of extension is successful. But this is coming from python extension.
So, Please file the issue against the python extension.

**Comment by pelx** [comment]
not very helpful!
    On Monday, 2 December 2019, 16:31:58 GMT, Sandeep Somavarapu <notifications@github.com> wrote:  
 
 
Installation of extension is successful. But this is coming from python extension.
So, Please file the issue against the python extension.

**Comment by pelx** [comment]
Python extension stopped working after last VSC update... 
    On Monday, 2 December 2019, 16:31:57 GMT, Sandeep Somavarapu <notifications@github.com> wrote:  
 
 
Closed #85936.

**Comment by sandy081** [comment]
Python extension is installed successfully and is activated.
This status message which you are seeing is coming from Python extension. 
So, please file the issue against the Python extension.
