### ISSUE TITLE
Test: Git FileSystemProvider

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#85932]
Tests #55110

- [x] Windows @fiveisprime
- [x] Linux @deepak1556
- [x] macOS @mjbvz

Complexity: 3

---

The entire Git virtual document infrastructure shifted from the TextDocumentContentProvider API to the FileSystemAPI. Please test:

- Diffing works as usual
- Gutter inline diffing works as usual
- File events work as usual (staging, unstaging should update the git models, visible on the left hand side of the diff editor)
- Text encoding is preserved across staging/unstaging ranges #36219

---

**Known issues:**

- [Do not include git files in search results](https://github.com/microsoft/vscode/issues/85915)

**Comment by sandy081** [comment]
@joaomoreno Is this TPI to be tested in this milestone? If so, please do not forget to add the milestone and label.

**Comment by mjbvz** [comment]
Also give a quick test to  the image preview as it now uses this:

- Create/change/and delete images and confirm you can view the diff from the changes view
- Try with large images as well

**Comment by deepak1556** [comment]
Works well on linux 👍 also verified image diff.

**Comment by fiveisprime** [comment]
Works well on Windows including image diffs 👍
