### ISSUE TITLE
Test: ESLint support for TypeScript

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#85933]
Tests https://github.com/microsoft/vscode-eslint/issues/802

- [x] anyOS @isidorn
- [x] anyOS @sana-ajani

Complexity: 3

The ESLint extension now has better support for TypeScript. Test that this is working as expected if a workspace is setup correctly for eslint usage.

### Prerequisite

Install the latest version of the ESLint extension from here: https://github.com/microsoft/vscode-eslint/releases/tag/2.0.1-next.1

### Setup

- create a new workspace folder
- add eslint to it
- add typescript to it.
- add the typescript parser to it: `"@typescript-eslint/parser`
- create a .eslintrc.json file and configure the typescript parse
```json
	"parser": "@typescript-eslint/parser",
	"parserOptions": {
		"ecmaVersion": 6,
		"sourceType": "module"
	}
```
- create a TypeScript file

A blueprint repository can be found here: https://github.com/microsoft/vscode-eslint/tree/2.0.1-next.1/playgrounds/ts

Ensure the following:

- the TypeScript file is validated correctly
- for workspace that don't have TypeScript support enabled for eslint no error messages are shown and no Output  panels pop to the front.

Please report issues here: https://github.com/microsoft/vscode-eslint/issues

**Comment by isidorn** [comment]
Works nicely. I also set it up for our VS Code repo. I tested on macOS.
