### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by sofu456** [microsoft/vscode#85934]
Issue Type: <b>Bug</b>

Extension host terminated unexpectedly.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.21.1
code-gnu-global|aus|0.2.2
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
cocos-debug|Chu|0.0.1
vscode-devtools-for-chrome|cod|0.0.5
vscode-svgviewer|css|2.0.0
dakara-foldplus|dak|1.4.0
vue-peek|dar|1.0.2
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
python-extension-pack|don|1.6.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|3.11.0
syntax-highlighter|evg|0.4.1
vscode-solution-explorer|fer|0.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-google-translate|fun|1.4.2
godot-tools|gee|0.3.7
cmake-integration-vscode|go2|0.6.5
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
dotnet-core-essentials|Kis|0.0.8
node-module-intellisense|lei|1.5.0
cmake-tools-helper|mad|0.2.1
MagicPython|mag|1.1.0
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
vscode-language-pack-zh-hans|MS-|1.40.2
python|ms-|2019.11.50794
cmake-tools|ms-|1.2.2
cpptools|ms-|0.26.1
csharp|ms-|1.21.8
Go|ms-|0.11.9
debugger-for-chrome|msj|4.12.2
vscode-react-native|msj|0.13.2
vuejs-extension-pack|mub|1.1.5
gulptasks|nic|1.3.1
vetur|oct|0.22.6
quicktype|qui|12.0.46
vscode-essentials-snippets|rob|2.0.0
watch-in-chrome|sne|0.0.2
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|2.0.0
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
unity-debug|Uni|2.7.2
quokka-vscode|Wal|1.0.261
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.5.1

</details>

**Comment by sandy081** [comment]
Are you able to reproduce it by disabling all extensions?

**Comment by sofu456** [comment]
@sandy081   i just reload the window to reproduce it. thank you for your mention, i will try to disable all extension to solve it.

**Comment by sandy081** [comment]
ok
