### ISSUE TITLE
Ctrl+k Ctrl+P not mapped to showAllEditors

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8593]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 10

The obsolete command workbench.files.action.workingFilesPicker had been mapped to ctrl+k ctrl+p.
The new equivalent command is workbench.action.showAllEditors.  

showAllEditors is mapped to alt+cmd+tab for OS X but not mapped for Windows and Linux.

**Comment by bpasero** [comment]
Thanks for finding this 👍
