### ISSUE TITLE
VSCode should have a table listing its versions against the corresponding Electron (or NODE_MODULE_VERSION) versions.

### ISSUE THREAD

**Issue by anurbol** [microsoft/vscode#85939]
[This table](https://nodejs.org/en/download/releases/) helps **a lot** when one builds a native Node.js addon and needs to know which Node.js versions have which `NODE_MODULE_VERSION`. Without such table for VSCode I simply don't know which VSCode versions should I test against. Installing every non-patch VSCode version to figure that out is not fun.

**Comment by anurbol** [comment]
Something like [this](https://github.com/Sneezry/vscode-version-watcher) but official and up-to-date. I am currently reading its source code and figuring out if I can do that myself.

**Comment by anurbol** [comment]
I think I've found an easier way to figure out Electron versions in different VSCode versions. I can browse repository tags and look at the `.yarnc` file. I just hope this is reliable enough, and someone can confirm that.

**Comment by anurbol** [comment]
```
		VSCODE ELECTRON
		master (insiders?) - 6.1.5
		1.40.2 - 6.1.5 // new
		1.40.1 - 6.1.2 
		1.40 - 6.1.2 // new
		1.39.2 - 4.2.10 
		1.39.1	 - 4.2.10		
		1.39.0 - 4.2.10		
		1.38.1 - 4.2.10		
		1.38.0 - 4.2.10	// new
		1.37.1 - 4.2.7	
		1.37.1 - 4.2.7	
		1.37.0 - 4.2.7 // new	
		1.36.1 - 4.2.5 	
		1.36.1 - 4.2.5 	
		1.36.0 - 4.2.5	// new	
		1.35.1 - 3.1.8 	
		1.35 - 3.1.8	// new	
the rest can be found here: https://github.com/Sneezry/vscode-version-watcher
```

**Comment by deepak1556** [comment]
@anurbol yes `.yarnrc` file contains the electron version that went in that branch. 

Any major electron version bump is always a change in `NODE_MODULE_VERSION` https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json , as long as your module is recompiled, matching the version shouldn't be something the author should be worried about.

Also I would suggest to have module written in N-API to avoid this scenario completely https://nodejs.org/api/n-api.html.
