### ISSUE TITLE
Allow configuration of integrated terminal's scroll sensitivity

### ISSUE THREAD

**Issue by mogzol** [microsoft/vscode#85947]
Currently, the integrated terminal's scrolling sensitivity seems to be tied to both the `editor.mouseWheelScrollSensitivity` setting and the operating system's global scroll settings. For me, this makes the terminal scroll far too fast when I use my mouse wheel. I can slow it down by decreasing either of those settings, but then scrolling in other places is too slow for my liking. It would be nice to be able to configure the scrolling sensitivity of just the terminal, rather than having one setting that affects both the terminal and the editor.

**Comment by Tyriar** [comment]
I'm concerned about adding yet another setting for this. The reason scrolling is different is because monaco has a bunch of logic to classify and tweak wheel events whereas xterm.js trusts the browser and doesn't try to align with the operating system's default scroll setting.

**Comment by mogzol** [comment]
I understand the concern for adding more settings, but the way it is currently makes scrolling in the terminal practically unusable if you either setting turned up. Even if the terminal only respected one of the two settings it would be much more manageable. VSCode's editor disregards the OS scroll sensitivity, only using what you have set in `editor.mouseWheelScrollSensitivity`, so in order to have the editor scroll at my liking, I have to turn this setting up. But I also want other apps to scroll faster, so I also turn my OS's scroll setting up. Since the terminal seems to multiply these two settings together, this results in the terminal scrolling far too quickly.

So perhaps make the terminal only use the  `editor.mouseWheelScrollSensitivity` setting, and ignore the OS one, like the editor seems to do?

**Comment by Tyriar** [comment]
I actually added a setting for it recently in https://github.com/microsoft/vscode/issues/87240

/duplicate
