### ISSUE TITLE
Hover overlapping with breadcrumbs

### ISSUE THREAD

**Issue by numanash** [microsoft/vscode#85940]
Issue Type: <b>Bug</b>

I found an issue while doing code that the suggestions are overlapping with the file name. Please review and fix it. I think its the order or visibilty issue.
Here is the screenshot: http://prntscr.com/q55tox
Thanks

Regards
Numanash

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.36GB free)|
|Process Argv|--folder-uri file:///d%3A/POS|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
simple-react-snippets|bur|1.2.2
jquerysnippets|don|0.0.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
sequelize-vscode-association-snippet|lou|0.0.2
code-beautifier|mic|2.3.3
material-icon-theme|PKi|3.9.2
format-html-in-php|rif|1.6.1
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by alexandrudima** [comment]
Let's track in #86239
