### ISSUE TITLE
Implement interface quick fix leaves out some 'any' typings

### ISSUE THREAD

**Issue by kizerkizer** [microsoft/vscode#85949]
Issue Type: <b>Bug</b>

Bug when I use the 'Implement interface' quick-fix; certain 'any' types are missing and not generated with the rest of the code, it seems. To reproduce, try to use the auto-implementer (don't know formal name) on the JSON2 class:
```
import IJSONObject from "./IJSONObject";

interface IJSON2 {

    /**
      * Converts a JavaScript Object Notation (JSON) string into an IJSONObject. This function is otherwise identical
      * to the standard JSON.parse, except for returning an IJSONObject instead of an object of type any.
      * @param text A valid JSON string.
      * @param reviver A function that transforms the results. This function is called for each member of the object.
      * If a member contains nested objects, the nested objects are transformed before the parent object is.
      */
    parse (text: string, reviver?: (this: any, key: string, value: any) => any ): IJSONObject;

    /**
      * Converts an IJSONObject to a JavaScript Object Notation (JSON) string.
      * @param value An IJSONObject.
      * @param replacer An array of strings and numbers that acts as a approved list for selecting the object properties that will be stringified.
      * @param space Adds indentation, white space, and line break characters to the return-value JSON text to make it easier to read.
      */
    stringifyStrict (value: IJSONObject, replacer?: ((this: any, key: string, value: any) => any) | ((number | string)[]) | null, space?: string | number): string
}

class JSON2 implements IJSON2 {

}
```

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
code-runner|for|0.9.15
beautify|Hoo|1.5.0
rest-client|hum|0.23.0
csharp|ms-|1.21.8
powershell|ms-|2019.11.0
hide-gitignored|npx|1.0.1
vim|vsc|1.11.3

</details>

**Comment by kizerkizer** [comment]
The contents of './IJSONObject' for reference:
```
type JSONValue = string | number | boolean;

interface IJSONObject {
    [key: string]: JSONValue | JSONValue[] | IJSONObject;
}

export default IJSONObject;

export {
    JSONValue,
    IJSONObject
};
```

**Comment by kizerkizer** [comment]
I'm not sure if this is a bug on a typescript plug-in, or whether this functionality is baked into code.

**Comment by kizerkizer** [comment]
This is what I get when I go to 'Quick fix...', then 'Implement interface IJSON2':
```
class JSON2 implements IJSON2 {
    parse(text: string, reviver?: (this: any, key: string, value: any) => ): IJSONObject {
        throw new Error("Method not implemented.");
    }    stringifyStrict(value: IJSONObject, replacer?: ((this: any, key: string, value: any) => ) | (string | number)[], space?: string | number): string {
        throw new Error("Method not implemented.");
    }

}
```
Note the missing `any` on the second line, in the type definition of `reviver`.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/35508 to track upstream
