### ISSUE TITLE
VSCode not finding import definitions

### ISSUE THREAD

**Issue by simkessy** [microsoft/vscode#85945]
- VSCode Version: 1.40.2
- OS Version: OSX 10.14.6

I trying to get VSCode to find the definitions for the files in my projects but it's not working.

For example: 

test.js

    export const getCats = cat => 'something something';

test2.js

    import { getCats } from './test';
    
    const iAmCat = () => getCats();

jsconfig.json

    {
      "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "jsx": "react",
        "checkJs": true
      },
      "include": ["src/**/*"],
      "exclude": ["node_modules"]
    }

When I'm in test2.js, I can't F12 into test 1. When I hover over `getCats` it doesn't show anything.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, if you run `JavaScript: Go to project configuration` in both `test.js` and `test2.js`, does it open the `jsconfig`?

**Comment by simkessy** [comment]
It works with the insider version and all the extensions disabled. I'm not sure why it doesn't work with the default version of VSCode but I'm happy using the insider edition anyways. Thanks.
