### ISSUE TITLE
Should be able to right-click and Copy Path from search results

### ISSUE THREAD

**Issue by curtw** [Microsoft/vscode#8594]
- VSCode Version: 1.2.1
- OS Version:  OS X 10.10.5

Steps to Reproduce:
1. click the search icon in the left column
2. run a search that returns results
3. right-click on a filename
4. observe that no context menu is displayed

Expected result: should get context menu that includes "Copy Path" like that available in the Explorer section ("Working Files" or "Main")

**Comment by dtgriscom** [comment]
I have two suggestions:

- The menu should include all relevant items from the menu shown when right-clicking on the title of a file being edited (e.g. "Reveal in Finder/Explorer" and "Reveal in Side Bar")

- This right-click menu should also be available on the files mentioned in the Debug/Call Stack list

**Comment by ryanburr** [comment]
Does this feature request include being able to copy/export the search results so they could be copied to another editor and compared with other search results? If not I'll open a different issue

**Comment by dtgriscom** [comment]
You mean, to export all items in the search results, rather than a single item? No; I'd only envisioned this as a popup menu on a single item, giving access to the path of that item.

**Comment by ryanburr** [comment]
Thanks. Not sure why #42120 was closed as a duplicate then. I'll try and get that reopened
