### ISSUE TITLE
"Go to File" and "Go to Symbol in Workspace" dialogs should not close when focus is lost

### ISSUE THREAD

**Issue by HighCommander4** [microsoft/vscode#85942]
**Steps to Reproduce:**

1. Invoke "Go to File" or "Go to Symbol in Workspace" command
2. Type a query into the search box
3. While waiting for the search results to come in (this can sometimes take a while if the workspace is large and the machine is under heavy load), switch focus to a different application

**Expected results**

VSCode continues performing the search while focus is on an another application.

**Actual results**

VSCode aborts the search and closes the dialog when focus is switched away.

**Comment by roblourens** [comment]
This is my favorite setting: `"workbench.quickOpen.closeOnFocusLost": false`

**Comment by HighCommander4** [comment]
Oh, awesome -- thanks!
