### ISSUE TITLE
Test: Search on Type

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#85953]
Refs: #46326

- [x] Windows @sana-ajani 
- [x] Linux @sbatten 
- [x] macOS @misolori 

Complexity: 2

Authors: @JacksonKearl 

---

The workspace search now has setting `"search.searchOnType"` enabled by default, causing results to update as you type, rather than on enter. Please ensure:

- Edits to any field trigger a search (query, include, exclude, toggling each button)
- Further typing doesn't feel sluggish after a search has been triggered
- `search.searchOnTypeDebouncePeriod` can be configured to:
  - Change the delay between a keystroke and a search being triggered
  - But `Enter` and toggling buttons still instantly trigger the search.
- Results shouldn't flicker as searches are re-triggered

**Comment by sana-ajani** [comment]
Besides a bit of flickering in the search results and in the "X results in Y files" line, this works well! Super neat

**Comment by JacksonKearl** [comment]
@sana-ajani @sbatten Increased the delay a bit in 27a00da to try to reduce flickering. We can see if its enough on the next build.
