### ISSUE TITLE
November 2019 Endgame

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#85959]
- *December 2nd* Code freeze for the endgame
- *December 6th* [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)
- *December 11th* Expected release date (this may change)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday
- [x] Run [OSS tool](https://github.com/microsoft/vscode-build-tools/tree/master/distro-tools) **endgame master**
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Tuesday
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
- [x] [🔖All closed feature-requests](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+archived%3Afalse+milestone%3A%22November+2019%22+user%3Amicrosoft+label%3Afeature-request+-label%3Averification-needed+-label%3Aon-testplan+-label%3Averified+sort%3Aupdated-desc+) either have a `verification-needed` or `on-testplan` label
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] [🔖Testing](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3Atestplan-item+user%3Amicrosoft)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+archived%3Afalse+milestone%3A%22November+2019%22+user%3Amicrosoft+label%3Averification-needed+-label%3Averified)

##### Wednesday
- [x] [🔖Testing](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3Atestplan-item+user%3Amicrosoft)
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+archived%3Afalse+milestone%3A%22November+2019%22+user%3Amicrosoft+label%3Averification-needed+-label%3Averified)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+archived%3Afalse+milestone%3A%22November+2019%22+user%3Amicrosoft+label%3Averification-needed+-label%3Averified)
- [x] [🔖Verification](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+is%3Aissue+user%3Amicrosoft+milestone%3A%22November+2019%22+label%3Abug+-label%3Averified+-label%3Aon-testplan+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+-repo%3Amicrosoft%2FAL+)

##### Friday
- [x] Pause scheduled `insider` builds **endgame master**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@sandy081**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
  - [x] debug adapter protocol **@weinand**
- [x] All issues [🔖verified](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A%2Aduplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+milestone%3A%22November+2019%22)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - **@dbaeumer**
  - [x] OS X - **@weinand**
  - [x] Linux - **@bpasero**
  - [x] Web (manual until https://github.com/microsoft/vscode/issues/80308 is done)
- [ ] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @aeschli
  - [x] @alexdima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [ ] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexdima**
  - [x] vscode-loader **@alexdima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes **@chrisdias**
  - [x] localization **@weeteckt**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [x] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **endgame master**
- [x] Acknowledge issue trackers from the community **@chrmarti**
- [x] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **endgame master**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **endgame master**
- [x] Bump up the version in package.json - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [x] [🔖milestone issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Amicrosoft+milestone%3A%22November+2019%22)
- [ ] [🔖candidate issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Amicrosoft+label%3Acandidate)
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **endgame master**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [x] Build stable for all platforms as new candidate issues come in **endgame master**
- [ ] Documentation updated
  - [x] @aeschli
  - [x] @alexdima
  - [ ] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [ ] @joaomoreno
  - [ ] @jrieken
  - [ ] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [x] Run `scripts/test-documentation.sh|bat` and add file or fix issues if there are new colors that are not documented.

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame. **endgame master**

##### Wednesday/Thursday
- [x] Build stable for all platforms **endgame master**
- [x] Sanity check of installable bits
  - [x] Windows 32 bit @mattbierner 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit @roblourens
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] OS X - @rebornix 
  - [x] Linux
    - [x] deb package 64-bit @JacksonKearl 
    - [x] rpm package 64-bit **owner** @RMacfarlane 
    - [x] archives **owner** @RMacfarlane 
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers)) **owner**
- [x] Publish website **@gregvanl**
- [ ] Publish Localization language pack **@weeteckt**
- [x] Publish to stable **endgame master**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **endgame master**
- [x] [Publish @types/vscode](https://github.com/microsoft/vscode/wiki/Publish-vscode-types) **endgame master**
- [x] Make sure rpm gets automatically published **@RMacfarlane**
- [ ] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@chrisdias**

**Comment by jeanluc243** [comment]
don't forget to compile also to build a stable version for **snap** ( in Linux )

it is not mentioned on the Endgame plans

**Comment by JacksonKearl** [comment]
@jeanluc243 we built snap and I sanity tested it, I'm not sure why it isn't in the checklist.

**Comment by geek1011** [comment]
Something's wrong with the Debian repository:

```
patrick@dpc01:~$ curl http://packages.microsoft.com/repos/vscode/dists/stable/InRelease
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: vscode stable
Label: vscode stable
Suite: stable
Codename: stable
Date: Thu, 12 Dec 2019 19:59:19 UTC
Architectures: amd64
Components: main
Description: Generated by aptly
MD5Sum:
 7bea19872e9b82085d3be6538fb9f5a8  5818137 Contents-amd64
 72aaf0c6a96497f5d312ebe6aa38fa25   286060 Contents-amd64.gz
 7bea19872e9b82085d3be6538fb9f5a8  5818137 main/Contents-amd64
 72aaf0c6a96497f5d312ebe6aa38fa25   286060 main/Contents-amd64.gz
 983c0db35856571cd4cd07c154098a0d  1065578 main/binary-amd64/Packages
 4153a12e4a5629bfb14ed98f4c8ac234   156065 main/binary-amd64/Packages.bz2
 54c730dd6a33c612b2ae3c23fe0cfcb7   165979 main/binary-amd64/Packages.gz
 4c9ca25b556f111a5536c78df885ad82       95 main/binary-amd64/Release
SHA1:
 530b0cd7db8fa73242275da9caaf5cacbb524123  5818137 Contents-amd64
 2e0ad5881362c82f54156e5d7b0934794dd0f332   286060 Contents-amd64.gz
 530b0cd7db8fa73242275da9caaf5cacbb524123  5818137 main/Contents-amd64
 2e0ad5881362c82f54156e5d7b0934794dd0f332   286060 main/Contents-amd64.gz
 c31f025e8b66250872d5a51fa6955bb69b84f962  1065578 main/binary-amd64/Packages
 1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e   156065 main/binary-amd64/Packages.bz2
 381a8321619083a4063fa8381bf3aa12a2dac5a3   165979 main/binary-amd64/Packages.gz
 58bf20987a91d35936f18efce75ea233d43dbf8b       95 main/binary-amd64/Release
SHA256:
 0e4df01bc226382fb8ff3377c2013660e7ff2214a5836dfbc291913ddb21b760  5818137 Contents-amd64
 fe9df392bb3b55000f0a367b1395bf0f1fba73f5155cbda55eb76bac813c1f61   286060 Contents-amd64.gz
 0e4df01bc226382fb8ff3377c2013660e7ff2214a5836dfbc291913ddb21b760  5818137 main/Contents-amd64
 fe9df392bb3b55000f0a367b1395bf0f1fba73f5155cbda55eb76bac813c1f61   286060 main/Contents-amd64.gz
 3799c721fce6022a424e516fd2e4a05b42300dbc0a2c9be367b4baaca7341e2f  1065578 main/binary-amd64/Packages
 c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0   156065 main/binary-amd64/Packages.bz2
 179eb71f2afb4a72bf5b11180b4d4c9ccf1644076dd75f5a7bbf880ecefafbba   165979 main/binary-amd64/Packages.gz
 0f509a0cb07e0ab433176fa47a21dccccc6b519f25f640cc58561104c11de6c2       95 main/binary-amd64/Release
SHA512:
 b7604de0adc4577b4602b367c64acb53d3e4f0df6bc6c0607ffc23c25a80effe5a68198c27ed10174f50b0bce8793f7a17e0371d6a45989cc0d2e9aa3abc31e9  5818137 Contents-amd64
 c97dfd42559374979acd16928c3e4e23d688662627b54cab47caa14915ad8cbe3ae15795b07e88add4f56f4f826fa6e614f4f61fbd4eb9c29bc718de7316568e   286060 Contents-amd64.gz
 b7604de0adc4577b4602b367c64acb53d3e4f0df6bc6c0607ffc23c25a80effe5a68198c27ed10174f50b0bce8793f7a17e0371d6a45989cc0d2e9aa3abc31e9  5818137 main/Contents-amd64
 c97dfd42559374979acd16928c3e4e23d688662627b54cab47caa14915ad8cbe3ae15795b07e88add4f56f4f826fa6e614f4f61fbd4eb9c29bc718de7316568e   286060 main/Contents-amd64.gz
 5eccea54bc989f1ac0c59c08a50ed272a257f4a431a672994e98739eb61db665169a65866621c4367c20337cbdc6a1705d11e96f7d6642ae4b1d1dc10b3aeb13  1065578 main/binary-amd64/Packages
 12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b   156065 main/binary-amd64/Packages.bz2
 ce0cd5497cdc9242a0e841113b3c280aa381555b20cde125fb1ded717ba89d936f004d0e64c83b3b6d5e2ef42756352975feb16ae5c7271cdcf631ffe6c3872a   165979 main/binary-amd64/Packages.gz
 e1a4378ad266c13c2edf8a0e590fa4d11973ab99ce79f15af005cb838f1600f66f3dc6da8976fa8b474da9073c118039c27623ab3360c6df115071497fe4f50c       95 main/binary-amd64/Release

-----BEGIN PGP SIGNATURE-----
Version: BSN Pgp v1.0.0.0

iQEcBAEBCAAGBQJd8pwjAAoJEOs+lK2+EinP/TcH/0uVbSn5nI9Vq7xal1PD3E2q
xKD2T8Q0mprsR1EEUnEdjoUguL8eqKB1Mnr36L/u6fqynngvPUm7gLEY0UsdnKGV
cPqEjVJvq1JD4tmnxv1FBfAQAbOtrUsBaeLFJaOWchNUEvnKgvc+HDnlCZEtmgQ8
fgIbBUgUEdWSIJzMd7yrl+E+uCGAZCmezA9TYl7Np5Kiv5u2ESwx625AlWLrFuKB
GCGnD7hdV/OTXdM8kndtJWfI36NwJo7SSfhS8WBZDtlLjEXf+jcMGgnsP/q9xeth
Q/QGm5OpAWx8IzJisygifIroNIhcoMy71CdzsluX7499DhWu1s8UXGEx9WY32/M=
-----END PGP SIGNATURE-----
```

```
patrick@dpc01:~$ curl http://packages.microsoft.com/repos/vscode/dists/stable/Release
Origin: vscode stable
Label: vscode stable
Suite: stable
Codename: stable
Date: Thu, 12 Dec 2019 21:57:52 UTC
Architectures: amd64
Components: main
Description: Generated by aptly
MD5Sum:
 7bea19872e9b82085d3be6538fb9f5a8  5818137 Contents-amd64
 72aaf0c6a96497f5d312ebe6aa38fa25   286060 Contents-amd64.gz
 7bea19872e9b82085d3be6538fb9f5a8  5818137 main/Contents-amd64
 72aaf0c6a96497f5d312ebe6aa38fa25   286060 main/Contents-amd64.gz
 b74c26fe433e1ae5cd51ba97a1a5add5  1065587 main/binary-amd64/Packages
 632de604a4708e3ea75bab7502bc3a10   156056 main/binary-amd64/Packages.bz2
 91a0716a94b6d538d6b0d61d4a103d37   165978 main/binary-amd64/Packages.gz
 4c9ca25b556f111a5536c78df885ad82       95 main/binary-amd64/Release
SHA1:
 530b0cd7db8fa73242275da9caaf5cacbb524123  5818137 Contents-amd64
 2e0ad5881362c82f54156e5d7b0934794dd0f332   286060 Contents-amd64.gz
 530b0cd7db8fa73242275da9caaf5cacbb524123  5818137 main/Contents-amd64
 2e0ad5881362c82f54156e5d7b0934794dd0f332   286060 main/Contents-amd64.gz
 fa2912d89b2c127f9d0742c57d39e28981c08713  1065587 main/binary-amd64/Packages
 e226193bb1c639fe5deb212ad1a34a509b257edb   156056 main/binary-amd64/Packages.bz2
 5ce736fa892c5622232eaf36085ea1686125d426   165978 main/binary-amd64/Packages.gz
 58bf20987a91d35936f18efce75ea233d43dbf8b       95 main/binary-amd64/Release
SHA256:
 0e4df01bc226382fb8ff3377c2013660e7ff2214a5836dfbc291913ddb21b760  5818137 Contents-amd64
 fe9df392bb3b55000f0a367b1395bf0f1fba73f5155cbda55eb76bac813c1f61   286060 Contents-amd64.gz
 0e4df01bc226382fb8ff3377c2013660e7ff2214a5836dfbc291913ddb21b760  5818137 main/Contents-amd64
 fe9df392bb3b55000f0a367b1395bf0f1fba73f5155cbda55eb76bac813c1f61   286060 main/Contents-amd64.gz
 1b1451ddbdcf4709a79af52ecd4cbb03a8b201ac8a0a98d6b6f65ed548b5a4e2  1065587 main/binary-amd64/Packages
 d579347e81cc933e947b201edff68cfd90b54524197bcee493d966dc2c496b17   156056 main/binary-amd64/Packages.bz2
 61d3902fba852c4869c0b5e92343aef1ac503e9b672b973996b8edfb96101ecb   165978 main/binary-amd64/Packages.gz
 0f509a0cb07e0ab433176fa47a21dccccc6b519f25f640cc58561104c11de6c2       95 main/binary-amd64/Release
SHA512:
 b7604de0adc4577b4602b367c64acb53d3e4f0df6bc6c0607ffc23c25a80effe5a68198c27ed10174f50b0bce8793f7a17e0371d6a45989cc0d2e9aa3abc31e9  5818137 Contents-amd64
 c97dfd42559374979acd16928c3e4e23d688662627b54cab47caa14915ad8cbe3ae15795b07e88add4f56f4f826fa6e614f4f61fbd4eb9c29bc718de7316568e   286060 Contents-amd64.gz
 b7604de0adc4577b4602b367c64acb53d3e4f0df6bc6c0607ffc23c25a80effe5a68198c27ed10174f50b0bce8793f7a17e0371d6a45989cc0d2e9aa3abc31e9  5818137 main/Contents-amd64
 c97dfd42559374979acd16928c3e4e23d688662627b54cab47caa14915ad8cbe3ae15795b07e88add4f56f4f826fa6e614f4f61fbd4eb9c29bc718de7316568e   286060 main/Contents-amd64.gz
 938bb9aa427ca9f1aa176a298d5f78abfb314b0ade477a1c5e6c744eb91edb77b0e7f1f2bc64202304b6b8effc4d478d2047b7e51540cd741ab1166f471cc697  1065587 main/binary-amd64/Packages
 120b1d269bd467cd62b1c4bb823b871fd54f85b0e24bbcb1f8daa86af34e286c4c7408c53592e288d709d7cd15f2d63fe2c7b496472f7ec0d21f0571ef9e869f   156056 main/binary-amd64/Packages.bz2
 791b26fa5435a26921fbfb56c489f66634ca53633d6bf038a0f46ea66bcb6ce5c8bdee728581f07ee969e7c54f24d5b82f5bcd28e8542d5842ddc93bf560e7c4   165978 main/binary-amd64/Packages.gz
 e1a4378ad266c13c2edf8a0e590fa4d11973ab99ce79f15af005cb838f1600f66f3dc6da8976fa8b474da9073c118039c27623ab3360c6df115071497fe4f50c       95 main/binary-amd64/Release
```

```
patrick@dpc01:~$ curl -s http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages | wc -c
1065587
```

```
patrick@dpc01:~$ curl -s http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2 | wc -c
156056
```

```
patrick@dpc01:~$ curl -s http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.gz | wc -c
165978
```

Note how the file size for `main/binary-amd64/Packages*` is correct in the unsigned `Release` file, but has the last two digits swapped in the signed `InRelease` file. I can't imagine how that would have happened, but it's preventing apt from accepting the repository.

**Comment by gjsjohnmurray** [comment]
> Something's wrong with the Debian repository:

See #86858
