### ISSUE TITLE
VS Code is very slow and there is a lag

### ISSUE THREAD

**Issue by kaustubhspande** [microsoft/vscode#85967]
We have written the needed data into your clipboard because it was too large to send. Please paste.
I am on Windows 10:
- ssh to linux machine using MobaXterm.
- From command line, launch VS code using, 'code . '.

Slowness and lag is experienced at all places. Disabling/ Uninstalling plugins also did not solve the problem.

CPUs | Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz (16 x 1342)
-- | --
GPU Status | 2d_canvas: unavailable_softwareflash_3d: unavailable_offflash_stage3d: unavailable_offflash_stage3d_baseline: unavailable_offgpu_compositing: unavailable_offmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: unavailable_offprotected_video_decode: unavailable_offrasterization: unavailable_offskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabled_readbackwebgl2: unavailable_off
Load (avg) | 0, 1, 1
Memory (System) | 62.65GB (47.63GB free)
Process Argv | . --no-sandbox
Screen Reader | no
VM | 0%

CPU %	Mem MB	   PID	Process
    0	    64	 30799	code main
    0	     0	 30830	   zygote
    0	    64	 30891	   gpu-process
    1	    64	 30991	   shared-process

|  Window (event_handler.py - kpande - Visual Studio Code)
|    Folder (kpande): more than 39389 files
|      File types: h(5261) c(2920) cc(1765) txt(755) py(586) png(420)
|                  code(413) svg(373) in(328) cmake(293)
|      Conf files: cmake(293) makefile(65) package.json(7) settings.json(3)
|                  tsconfig.json(2) tslint.json(1) launch.json(1)
|                  tasks.json(1)
			

Extension | Author (truncated) | Version
-- | -- | --
python | ms- | 2019.11.50794
cpptools | ms- | 0.26.1
yang-vscode | typ | 1.7.0
vscode-proto3 | zxh | 0.3.0

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
