### ISSUE TITLE
Test: Terminal minimum contrast ratio

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85966]
Refs: #84935

- [x] Windows @RMacfarlane
- [x] Linux @connor4312
- [x] macOS @bowdenk7

Complexity: 3

---

The new setting `terminal.integrated.minimumContrastRatio` makes foreground colors in the terminal more of less luminous to improve the contrast ratio. To test this, read over the setting description then testing using the dom, canvas and webgl renderers. Note that each different type of color is calculated a little differently so should be tested independently:

- Default foreground color
- 256 palette color (eg. https://github.com/gawin/bash-colors-256)
- True color (eg. https://unix.stackexchange.com/a/404415/115410)

For Windows use WSL or PowerShell to output colors.

**Comment by connor4312** [comment]
Using the DOM renderer on Lubuntu 19.10, the contrast ratio does not apply to the truecolor test:

![image](https://user-images.githubusercontent.com/2230985/70070851-23a69f00-15a9-11ea-97e5-0fa097ef4176.png)

Canvas and webgl work, and dom works with the default palette color

![image](https://user-images.githubusercontent.com/2230985/70070907-42a53100-15a9-11ea-9869-b2f89e3c90a0.png)

**Comment by Tyriar** [comment]
@connor4312 can you create an issue? Maybe I missed a case

**Comment by bowdenk7** [comment]
![image](https://user-images.githubusercontent.com/820883/70093532-739b5b00-15d5-11ea-8cd3-28a66b02ec94.png)

![image](https://user-images.githubusercontent.com/820883/70093544-7dbd5980-15d5-11ea-909f-2213c394cb11.png)

0, 16, 17, 233, 234, 235 seem to not be working for me.

**Comment by Tyriar** [comment]
@bowdenk7 that's expected behavior because your background is lighter than those colors, I don't try to invert the colors for this case as I felt that changed too much about the text. Can wait for more feedback from users on this but I'll keep as is for now.
