### ISSUE TITLE
Test: CSS property ranking by populartiy

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#85968]
Refs: #3145

- [x] macOS @misolori
- [x] anyOS @stevencl

Complexity: 1

---

Try a few CSS property completions. Verify that you get properties ordered by the order of https://www.chromestatus.com/metrics/css/popularity.

Previous Ranking:

![image](https://user-images.githubusercontent.com/4033249/69999726-2b653580-150e-11ea-916f-5caf9964697f.png)

Current ranking, based on https://www.chromestatus.com/metrics/css/popularity:

![image](https://user-images.githubusercontent.com/4033249/69999665-0b357680-150e-11ea-8c30-b95f24d8b62e.png)

**Comment by misolori** [comment]
@octref does this not apply to vendor prefixes? Looks like those are still alphabetical:

![image](https://user-images.githubusercontent.com/35271042/70086207-bdc91000-15c6-11ea-84c0-26af85b92a55.png)

**Comment by octref** [comment]
@misolori Chrome doesn't give that information. So even if we rank by their properties without `moz`, that wouldn't necessarily correspond with their actual popularity.
Alphabetical is fine for them I think.
