### ISSUE TITLE
VSCode should display information regarding languages' versions

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#8596]
**Problem:**

Currently, VSCode doesn't display version information about languages that are used by extensions, so you have no way to know **what** is the current language version that the extension is using and **whether** the extension was tested with version 1.0, 2.0 or whatever of the language, you have to assume that the extension just works, VSCode itself doesn't even report information about TypeScript.

For example, if I want to know what version of TypeScript ships with VSCode I have to read the release docs which I do but this isn't the point and if I upgrade or downgrade I have to assume VSCode is using whatever version of TypeScript I set it up with but I have no feedback about the version the editor consumes either because the information is not exposed to the UI or not available at all.

_In fact, it's odd that when you type `ext` to tasks in VSCode, VSCode tells you `no extensions found` but it actually uses many extensions under the hood, it's okay to prevent people from removing them but it should certainly allow you to list them but that's probably another issue._

_**Solution:**_

I didn't have the time or the chance to write an extension _yet_ so I don't know the infrastructure of VSCode so I really don't know whether something like this exists but it would be really great if VSCode had an API that authors could implement to get the version of the language they consume.

Something like this:

```
class SomeLanguageExtension {
    get currentLanguageVersion(): string {
        return SomeExternalService();
    }
}
```

Then VSCode would have the ability to take advantage of this to display the version in the UI next to where you pick the language.

What would be even better is something like this:

```
class SomeLanguageExtension {
    get currentLanguageVersion(): string {
        return SomeExternalService(); // Shouldn't be hardcoded.
    }

    get supportedLanguageVersions(): string {
        return ["2.x", "3.0", "6.x"]; // Hardcoded.
    }
}
```

As far as I know an extension manager is planned for VSCode so the `supportedLanguageVersions` API can be used to tell users what are the versions of a language that the extension supports or tested against.

Having no API for this or not exposing this to the UI means authors are left to write it as part of their extension page or somewhere else or not at all and users need to look for it or ask the author that may or may not answer you, in short all I'm saying is this information needs to be transparent and crystal clear. :)

**Comment by dbaeumer** [comment]
Adding @joaomoreno since such an information is best presented in the Extension UI. 

I am up for a more general solution. TS currently shows the TS version is uses in the status bar iff it is different than the preshipped one (the tsdk setting is used). If every extension does that we have a very populated status bar :-)

**Comment by eyalsk** [comment]
@dbaeumer yeah, sure, adding this to the Extension UI makes a lot of sense.

Displaying the version in the status bar is not _required_, it's nice for _decoration_ but here is an idea instead of statically display the version of TypeScript, you can change this behaviour to display the version of the language that currently handles the opened file.

So for example, say I have two files opened a TypeScript file and a C# file, when I switch between them the version indicator gets changed accordingly.

**Comment by joaomoreno** [comment]
I don't understand. What would a theme extension show? Or the Spotify status bar extension? Or an extension that contributes many languages?

**Comment by eyalsk** [comment]
@joaomoreno I wrote this specifically for languages, I'm not sure whether this can be extended farther for other types of extensions and whether it makes sense but I really think that when someone installs an extension that support some language the versions of the language that the extension supports needs to be transparent to the user.

Authors that write language extensions don't necessarily write details about the version of the language that they used to test the extension with, I think that having APIs for this will improve this scenario and prevent unnecessary confusion to the end-users when it comes down to questions like "What version of the language should I install?", "What version of the language this extension supports?", "Can I use this extension with the version of the language I already installed?" 

The API can probably iterated to fit more scenarios, i didn't take into account the fact that a single extension can support multiple languages.

**Comment by jrieken** [comment]
I wonder if it's that simple. Often extension don't really contain the language implementation but just make sure some version of a tool is installed - like `go` and it's tool chain

**Comment by eyalsk** [comment]
@jrieken Yeah, you're right, it's something that needs to be checked but nonetheless, say you installed language X and you tested it with version Y, it can be helpful to note the version even if it's just a hardcoded value in the API.

If there was a way to force authors to write the supported versions in the extension page then there wasn't much need for an API for this so maybe another idea is to let them write the supported versions for the language or multiple ones when they are uploading the extension to the gallery.

**Comment by jrieken** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
