### ISSUE TITLE
Webview select checked user agent stylesheet cannot be overridden

### ISSUE THREAD

**Issue by AnyaHunt** [microsoft/vscode#85963]
In a webview form
With a select box with multiple selection allowed
Selection colors cannot be overridden (because they are marked important?)
What happens is the highlighted items in the select box appear with a grey background and dark grey text, rather than being able to apply the current vscode theme color to them.
![image](https://user-images.githubusercontent.com/49539354/69998757-e3ddaa00-150b-11ea-9c46-9dad3bab9190.png)

Method of turning off default appearance attempted (appearance is not a recognized property, and -moz-appearance is crossed out):
```
select {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}
```
The rule that should override the default stylesheet is (and does not appear crossed-out):

```
select option:checked {
    color: var(--vscode-dropdown-foreground) !important;
    background-color: var(--vscode-editor-selectionHighlightBackground) !important;
}
```

But instead the user agent stylesheet remains in effect (not crossed out to show overridden):
```
select:-internal-list-box option:checked {
    background-color: -internal-inactive-list-box-selection !important;
    color: -internal-inactive-list-box-selection-text !important;
}
```

![image](https://user-images.githubusercontent.com/49539354/69998753-de805f80-150b-11ea-8400-bb7e22554387.png)

**Comment by mjbvz** [comment]
Does this work in chrome?
