### ISSUE TITLE
Cannot open files beginning with '.' and containing additional '.' from jump list

### ISSUE THREAD

**Issue by mbreaton** [microsoft/vscode#85960]
# Environment
Win32NT 10.0.19033.0 Microsoft Windows NT 10.0.19033.0

# Steps to reproduce

1. Open a file beginning with a '.' and containing another (e.g., .profile.json) in Windows Explorer by selecting "Open with Code" in file's context menu
2. Exit Visual Studio Code
3. Bring up Visual Studio Code's jump list
4. Select the file opened in step 1

# Expected behavior

Expected the file to open in VS Code

# Actual behavior

Error message stating:

> The item you selected is unavailable. It might have been moved, renamed, or removed. Do you want to remote it from the list?

**Comment by bpasero** [comment]
This could be an Electron issue as well. Up for grab if someone wants to invstigate.

**Comment by bpasero** [comment]
Sorry, but I cannot reproduce this it works fine for me.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mbreaton** [comment]
I tried it with the latest insider build and can confirm the problem is resolved.
