### ISSUE TITLE
Test: Semantic Tokens proposed API

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#85976]
Test item for semantic tokens API proposal

- [ ] anyOS @octref  
- [x] anyOS @Tyriar 

Complexity: 5

We are working towards semantic colorization as requested in #585. This work consists of two conceptual pieces:
1. Providing semantic tokens to the editor via the `vscode` API
2. Styling/Theming semantic tokens - #77133

---

Your test assignment is to write an extension that [uses the semantic tokens proposed API](https://github.com/microsoft/vscode/blob/e95b3adcf080bf47123362b31e93fe2d5fafbf9d/src/vs/vscode.proposed.d.ts#L71-L226). Part of the test plan item is to gather feedback on the API shape itself. I know the API is not as usable as other provider APIs, but there is a rather large doc comment in the proposed API which I will not duplicate here, but which I hope answers most of your questions. You can implement a semantic tokens provider that always returns all the tokens, you can even use a builder class that is part of the proposal, or you can go all in and implement a provider that returns edits... I am interested in all kinds of feedback. Thank you!

---

Here is an example TS semantic tokens provider -- https://github.com/microsoft/vscode/compare/alex/ts-semantic-coloring . This is not a standalone extension because it needs to modify the built-in TS extension to get access to the tsserver.

---

It is not possible to see the semantic tokens you are providing unless you style them via user settings via `"editor.tokenColorCustomizationsExperimental"`. For example, when I provide semantic tokens of the types "classes", "enums" and "namespaces", I am using the following setting in order to distinguish my semantic tokens from the rest of the tokens:
```
    "editor.tokenColorCustomizationsExperimental": {
        "classes": { "foreground": "#ff0000", "fontStyle": "bold" },
        "enums": { "foreground": "#ff0000", "fontStyle": "bold" },
        "namespaces": { "foreground": "#ff0000", "fontStyle": "bold" },
    },
```

**Comment by alexandrudima** [comment]
@sbatten @sandy081 I have explicitly assigned @octref to this item (he expressed interest) and it looks like the bot has lost that:

> ![image](https://user-images.githubusercontent.com/5047891/70032782-70d93f80-15ae-11ea-84e0-37607f31334b.png)

@octref maybe you can negotiate with @Tyriar and swap test plan items.

**Comment by sandy081** [comment]
It was assigned to @octref in the beginning see 👇 

![image](https://user-images.githubusercontent.com/10746682/70041908-41323380-15be-11ea-9510-7dfc22bf3514.png)

It got reassigned after manually for adjustments.

**Comment by octref** [comment]
I swapped with Isi for #85994.

**Comment by octref** [comment]
I prioritized testing shipping features today. I'll block off time tomorrow morning to do more testing.
