### ISSUE TITLE
Git repo on did change event not fired on first selection change in multiroot workspace

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#85975]
Issue Type: <b>Bug</b>

1. Create an extension with the following code, making sure to list `vscode.git` as an extension dependency in the `package.json` and copying the `git.d.ts` from vscode:
```
export async function activate(context: vscode.ExtensionContext) {
	const gitExtension = vscode.extensions.getExtension<GitExtension>('vscode.git')!.exports;
	const gitApi  = gitExtension.getAPI(1);

	gitApi.repositories.forEach(repo => {
		console.log(repo.rootUri.path, repo.ui.selected);
		repo.ui.onDidChange(() => {
			console.log(repo.rootUri.path, repo.ui.selected);
		});
	});

	gitApi.onDidOpenRepository(repo => {
		repo.ui.onDidChange(() => {
			console.log(repo.rootUri.path, repo.ui.selected);
		});
	});
}
```
2. Run the extension and open a multiroot workspace with two repos
3. In the SCM viewlet, select the second folder

Expected:
`onDidChange` is fired for the repo that is deselected and the repo that is now selected

Actual:
`onDidChange` gets fired for the first repo which now has selected `false`, but no `onDidChange` is fired for the second, now selected repo

VS Code version: Code - Insiders 1.41.0-insider (7cf4cca47aa025a590fc939af54932042302be63, 2019-12-02T05:26:29.458Z)
OS version: Darwin x64 18.7.0

**Comment by joaomoreno** [comment]
Pushing out due to not being regression or severe.
