### ISSUE TITLE
New Debug Viewlet do not work with multi workspace

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#85977]
Ref: #84677

Version: 1.41.0-insider
Commit: 7cf4cca47aa025a590fc939af54932042302be63
Date: 2019-12-02T05:26:29.458Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

- Open two folders, each with a `.vscode/launch.json`
- ![image](https://user-images.githubusercontent.com/4033249/70001736-eb548180-1512-11ea-9223-7b11f028120d.png)

I feel this has to be fixed, so putting in Nov milestone.

**Comment by isidorn** [comment]
Good catch. Yes, this has to be fixed. Thanks for filling the issue.
