### ISSUE TITLE
Test: Auto selecting matching tag position

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#85973]
Refs: #47069

- [x] Windows @gregvanl
- [x] Linux @aeschli 
- [x] macOS @rebornix 

Complexity: 3

---

For #47069, we added two features:
- F2 to rename HTML tags
- Auto selecting tags when `html.autoSelectingMatchingTags` is enabled

Test that:

- F2 to renaming opening/closing tags together works as expected
- Auto selecting tags works as you expect for different scenarios, for example:
    - Test both valid HTML and incomplete HTML (such as tags without closing `>`). Make sure the behavior works as expected in valid HTML and is **understandable** in invalid HTML.
    - Test that when inserting space on this case: `<div|></div|>`, only the first cursor inserts the space (the space inserted by second cursor is auto-removed)
    - Try self closing tags such as `<br>` and `<input>`. Try both the `<br>` form and `<br/>` and `<br />` form. Make sure they do not interfere with this feature working on adjacent tag pairs.
    - Try various shortcuts such as `alt + Delete`, `alt + Right`, `cmd + c`. Make sure this feature works with them.
    - (Mostly for @rebornix, but if you want to try a bit of Vim, go ahead) Try this feature with Vim extension. Make sure basic movements, such as `hjkl` for left/down/up/right and `dw` (delete word) and `cw` (change word) can work property when you position your cursor in the tags
    - Test this feature in large HTML files.
    - Test that tag auto-completion works. For example, try setting cursors in `<div|></div|>`, delete the `div` and enter `d` to complete `div`. (This will only work when primary cursor is in the beginning `<div>` and mirrored cursor in the ending one, not the other way around).

**Comment by ayyash** [comment]
guys in the previous insider version I was able to disable this feature with auto select configuration, now I can't find it, what was it replaced with?
Reason is very simple, when I want to move the opening tag by keyboard, but not the closing tag... that isn't possible while this feature is active. And there is a bug, if I "ctrl+Z" to undo, the cursors are stuck, any keyboard move, moves the two cursors together.

**Comment by octref** [comment]
@ayyash It's called `html.mirrorCursorOnMatchingTag` now.
