### ISSUE TITLE
WebGL renderer isn't hot swappable

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85970]

**Comment by JacksonKearl** [comment]
Not sure how to tell if the swap was made.
 
One issue is that the descriptions still says hot swap isn't supported.

**Comment by JacksonKearl** [comment]
Verified by timing `tree` against vscode... canvas is 7.5-8s webgl is 5.5-6. Opened https://github.com/microsoft/vscode/issues/107858 to track description mismatch
