### ISSUE TITLE
Test: VS Code Figma Toolkit

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#85978]
Refs https://github.com/microsoft/vscode/issues/83952

- [ ] any @octref 

Complexity: 3

**Overview**

We've created a [Figma toolkit for VS Code](https://aka.ms/vscode-figma-toolkit) extension authors to aid in the creation of extension UI. With this toolkit, extension authors are able to re-use existing design components and create custom views. Try to design a dummy extension that covers the following the contribution points:

- Custom activity bar icon
- Custom viewlet with section group
- Custom tree
- Custom web view
- Custom notification

Link: [Figma Toolkit](https://aka.ms/vscode-figma)

Follow the steps in the Figma file's readme, if you are already part of the VS Code team on Figma you can skip steps 1-3 and create a file in your drafts:

![image](https://user-images.githubusercontent.com/35271042/70001003-09b97d80-1511-11ea-8f63-d4dc9b3f5987.png)

**Comment by octref** [comment]
I had fun. Pretty good library. Thanks 👍 

![image](https://user-images.githubusercontent.com/4033249/70098799-f6c2ae00-15e1-11ea-87b2-9f563a6f411c.png)
