### ISSUE TITLE
Opening a 3 gig CSV to view causes Visual Code to crash. 

### ISSUE THREAD

**Issue by enmunger** [microsoft/vscode#85974]
Issue Type: <b>Bug</b>

working with a large data set within Visual Code  - when I try to load it to display, Visual Code crashes. 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.19528

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (20.99GB free)|
|Process Argv|--max-memory=4096|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
python-extension-pack|don|1.6.0
pip-packages|etm|0.4.3
r|Iku|1.1.8
MagicPython|mag|1.1.0
rainbow-csv|mec|1.3.1
vscode-nmake-tools|Mic|2.0.190718003
r|Mik|0.0.6
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
cpptools|ms-|0.26.1
python-coding-tools|nil|1.0.3
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
python-pack|Swe|0.1.9
python-extended-snippets|tus|0.0.1
vscode-icons|vsc|9.6.0
material-theme|zhu|3.2.0

(2 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Does it happen with extensions disabled? Especially `rainbow-csv`.
