### ISSUE TITLE
Only generate valid document links of `@use` and `@forward` imports

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#85980]
Ref #81943, #85979

```scss
@use "material";
@use "material/theme";
```

Both cases should provide no links since they don't point to actual paths.

EDIT: Seems link verification has been broken.
Verify that `@use "./foo.scss"` doesn't generate a link when `./foo.scss` doesn't exist on disk.

**Comment by mjbvz** [comment]
Still seeing this with 7f1975a4fb29d0a788c21f17eb2aad056fec22d8

![Screen Shot 2019-12-04 at 3 06 13 PM](https://user-images.githubusercontent.com/12821956/70189246-a6158880-16a7-11ea-83fe-b511f58a573e.png)

**Comment by octref** [comment]
Sorry, forgot to pull in CSS dependency...
