### ISSUE TITLE
Test: Custom dropdown picker in Desktop + Web

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#85988]
Refs: https://github.com/microsoft/vscode/issues/83756
- [x] macOS @isidorn
- [x] linux @jrieken
- [x] windows @weinand

Complexity: 1

Along with testing in the **latest desktop** release, make sure you have **latest browsers** installed:
- macOS: Chrome, Safari, Firefox
- Linux: Chrome, Firefox
- Windows: Chrome, Firefox

We've changed all of the dropdown chevrons to use our custom icons. Please test on **both Desktop and Web** that all dropdowns render correctly in the following areas:
- Settings UI
- Debug (launch, connections)
- Panel (terminal, output)
- Remote explorer - nightly (target switcher)

**Comment by isidorn** [comment]
We do not use the custom select box on the Mac vscode. Though I will test on Chrome Safari and Firefox.

**Comment by misolori** [comment]
@isidorn sorry I should've clarified, when I said "custom" I meant that all dropdowns now use the chevron as the "custom" icon:

![image](https://user-images.githubusercontent.com/35271042/70070446-7c296c80-15a8-11ea-8d8e-777bcac1949e.png)

As opposed to the native one:

![image](https://user-images.githubusercontent.com/35271042/70070515-96fbe100-15a8-11ea-96d1-dcee673b4124.png)

**Comment by isidorn** [comment]
Ok. It looks good on all platforms as I was unable to detect the difference :)
