### ISSUE TITLE
Test: Debug icons & color tokens

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#85989]
Refs: https://github.com/microsoft/vscode/pull/84771

- [x] macOS @gregvanl
- [x] linux @JacksonKearl
- [x] windows @sana-ajani

Authors: @misolori, @isidorn 

Complexity: 2

**Overview**

We've update the Debug breakpoint and toolbar icons to use our new icon font. Start a couple of different debug sessions, set the various breakpoints, step into/out, navigate the call stack, and ensure that all icons render correctly.

In addition, we've also introduced new color tokens for each of these items. Ensure that you can overwrite this in your user settings via `workbench.colorCustomizations`:

**Toolbar**
- `debugIcon.startForeground`
- `debugIcon.pauseForeground`
- `debugIcon.stopForeground`
- `debugIcon.disconnectForeground`
- `debugIcon.restartForeground`
- `debugIcon.stepOverForeground`
- `debugIcon.stepIntoForeground`
- `debugIcon.stepOutForeground`
- `debugIcon.continueForeground`
- `debugIcon.stepBackForeground`

**Breakpoints**
- `debugIcon.breakpointForeground`
- `debugIcon.breakpointDisabledForeground`
- `debugIcon.breakpointUnverifiedForeground`
- `debugIcon.breakpointStackframeForeground`
- `debugIcon.breakpointStackframeFocusedForeground`

**Comment by JacksonKearl** [comment]
It's not clear to me when `debugIcon.breakpointStackframeForeground` should be used. It seems like it's only used for the topmost frame when it's focused, every other focused frame gets `debugIcon.breakpointStackframeFocusedForeground`.

I think when the top frame is focused it should also get the focused color. Also, I don't see frames that aren't focused so I don't know why there are two colors.

**Comment by isidorn** [comment]
There are two colors becuse the top stack frame when focused gets the yellow color.
If you click on any other stack frame other than the top it is green. As shown in this gif.
The names are maybe not the best and they are there for historic reasons. I am open to suggestions on how to make this more clear. Thanks

![frame](https://user-images.githubusercontent.com/1926584/70080585-1f10d380-1607-11ea-9f58-3e0ba1db0ad6.gif)

**Comment by JacksonKearl** [comment]
I think "debugIcon.breakpointStackframeForeground" should be every stackframe icon besides the topmost one, and "debugIcon.breakpointCurrentStackframeForeground" should be the topmost one.

**Comment by sana-ajani** [comment]
Yeah, agreed with Jackson. We can edit the help text for those to be "Icon color for current stackframe" and "Icon color for other stackframes". 

Other feedback would be on the "debugIcon.startForeground" setting, since that one isn't a part of the actual debug toolbar, but is in Debug View. The help text says "debug toolbar icon for start debugging", maybe we can change it to "Icon color for start debugging". 
![image](https://user-images.githubusercontent.com/9721254/70093307-f40d8c00-15d4-11ea-877b-5918dd836cc3.png)

**Comment by isidorn** [comment]
@JacksonKearl Sure, those suggestions work for me. Can you please create an issue and assign it to @misolori and me. Thanks!
