### ISSUE TITLE
Test: Sanity check vscode-pwa

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#85984]
Smoke tests and getting 👀 on the PWA extension. (cc @roblourens )

- [x] macOS @sandy081 
- [x] linux @weinand 
- [x] windows @chrmarti 

Complexity: 4

### Prerequisite

 - Install the latest `js-debug-nightly` extension from the marketplace.
 - Be on Insiders, of course :)

### Node.js testing

 - Pick any Node.js project you have configured for debugging with VS Code
 - Prefix its launch config type with `pwa-`
 - Verify that you can *launch* the program and debug as usual:
    - The program launches
    - You can set breakpoints before and while the program is running, and they get hit
    - You can step into, out of functions.
    - Stack traces etc. display correctly.
    - Restarting the program works
    - Stopping the program works
 - Verify that you can *attach* to this Node.js process running in debug mode, and debug as usual.

### Chrome testing

 - Pick any browser/Chrome project you have configured for debugging with VS Code
 - Prefix its launch config type with `pwa-`
 - Verify that you can *launch* the project and debug as usual:
    - The browser launches and opens your project
    - You can set breakpoints before and while the program is running, and they get hit
    - You can step into, out of functions.
    - Stack traces etc. display correctly.
    - Restarting the program should refresh the page
    - Stopping the program should close the browser
 - Verify that you can *attach* to a running browser with your project open.
    - Note that you need to launch Chrome with special flags for this, on my machine: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=/tmp/chrome-debug`

### Extension Host testing

 - Pick any extension you have configured for debugging with VS Code
 - Prefix its launch config type with `pwa-`
 - Verify that you can launch the extension and debug as usual:
    - The extension host launches with your extension
    - You can set breakpoints before and while the program is running, and they get hit
    - You can step into, out of functions.
    - Stack traces etc. display correctly.
    - Restarting the extension reloads the extension host window
    - Stopping the program closes the extension host window

**Comment by roblourens** [comment]
Please file issues at https://github.com/microsoft/vscode-pwa/

You can get a log using `"trace": true` in the launch config if needed

**Comment by weinand** [comment]
After 5 hours of testing vscode-pwa with **node.js** and **extension debugging** I've decided to stop because I had reached the Complexity level of 4.
I suggest that the other testers start with **Chrome testing**.
