### ISSUE TITLE
editor.autoClosingBrackets: beforeWhitespace is incorrect for Python

### ISSUE THREAD

**Issue by kbd** [microsoft/vscode#85983]
Issue Type: <b>Bug</b>

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

**Description**:

When `editor.autoClosingBrackets` is set to `beforeWhitespace`, bracket closing is incorrect for the Python language. Quote characters (single and double) seem to be treated as whitespace.

**Expected behavior**:

Typing "foo(" before any text other than whitespace should not add a closing bracket.

**Actual behavior**:

For Python specifically, typing "foo(" before a string in quotes still auto-closes. Other languages (even plaintext) have the correct behavior.

Here's a screen captured video that shows the behavior. I follow the same three steps in three different "languages": plain text, Ruby, then Python. For all three, typing "foo(" before whitespace correctly closes the bracket. For Python only, typing "foo(" before a quoted string still auto-closes the bracket.

![autoClosingBrackets](https://user-images.githubusercontent.com/728060/70002928-c6660b80-151e-11ea-8935-48a08f676196.gif)

(Sorry the ffmpeg-converted gif came out slower than real time, but it was better to be able to post something inline on github than have to link you to the video uploaded to imgur.)

I do have the Python language extension installed, but it is disabled to ensure that's not the cause.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/1d93480508768e5789d7ac56ee2312af1bacd245
