### ISSUE TITLE
 IntelliSense shows blank

### ISSUE THREAD

**Issue by wrbing728** [microsoft/vscode#85996]
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.5.0

In a Typescript project the IntelliSense works like:
![image](https://user-images.githubusercontent.com/8429360/70018847-590bb680-15c2-11ea-8d04-36725fcddbbd.png)

have already set quickSuggestions to true. Seems the IntelliSense worked, but worked in a wrong way.

**Comment by mjbvz** [comment]
From the screenshot, it looks to me like all the text is just super tiny

**Comment by wrbing728** [comment]
@mjbvz  When you say that, it really looks like the text is tiny, so maybe something wrong with the text font size

**Comment by wrbing728** [comment]
But I couldn't find which config to set the IntelliSense suggestion's font size. Need help again~
