### ISSUE TITLE
Editable custom editor exploratory test pass

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#85991]
Test continuation for #77131 

- [x] Any @roblourens
- [x] Windows @eamodio

Complexity: 5

## Overview
This iteration, we added basic support for editable custom editors. This includes:

- undo/redo
- save and saveAs

You can find the current state of the api in [`vscode.proposed.d.ts`](https://github.com/microsoft/vscode/blob/7ddf497849919fae58911920bceaa12bfcffafb3/src/vs/vscode.proposed.d.ts#L1340)

## Testing
We'd like an exploratory test pass made over this new functionality. To help with this, I've created a set of very simple custom editors: https://github.com/mjbvz/vscode-experimental-webview-editor-extension/

Some areas to focus on:

- API
    - Can you make you understand how to use the new api?
    - Does it work as you would expect?
    - Are there ways it could be made easier to work with? Especially for binary editors.

- Integration with VS Code
    - Do undo/saves work intgrate with VS Code's UX (dirty indicator, edited file count, ...)
    - Do custom editors play nicely with VS Code's commands (save all, ...)
    - How do edit and save work if you have multiple custom editors for the the same file type?

## Known issues
- Hot exist doesn't work (it may look like it kinda works but it doesn't)
- Prompt on closing editor doesn't work: #86145

**Comment by mjbvz** [comment]
Also try opening multiple copies of the same custom editor in different groups for a single resource. Make sure that editor history is properly shared between the visible editors

**Comment by roblourens** [comment]
It seems like a possible issue that there are n instances of the editor for the same resource opened n times, and they all save independently. A real implementation would probably want to coordinate editors to only write a save to disk once rather than write n times simultaneously.

**Comment by eamodio** [comment]
@mjbvz one thing I noticed is that if you start with an untitled doc, save it, and name it `foo.abc` it won't invoke the custom editor. You need to close the file and re-open it. Also would there be an eventual tie in with the language mode, so you can go right from an untitled document to the custom editor immediately?

**Comment by eamodio** [comment]
As @roblourens mentioned, I feel like having a document model either in the API (or encouraged by the API) would be good. @mjbvz I changed up your sample [here](https://github.com/eamodio/vscode-experimental-webview-editor-extension) to create a backing document for all the editors (of the same Uri) and it seems to work decently -- no more undo/redo strangeness (other than having to hit `ctrl+z` or `ctrl+y` twice to make it happen -- not sure why that is).

My sample changes are quite naive and there are plenty of issues (not cleaning up docs from the cache, disposing events, etc, etc). But I feel like an API that encourages this style and removes the need for its own document cache, and helps with versioning, etc would make this easier to write.
