### ISSUE TITLE
Test CodeAction.disabled

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#85993]
Test for #85160

- [x] AnyOs @eamodio 
- [x] AnyOs @alexr00 

Complexity: 4

# Overview
The new `CodeAction.proposed` property lets extensions tell VS Code why a specific code action is not available. This is used in a few ways:

- Disabled actions **are not** shown in the normal lightbulb menu
- Disabled action **are** show in specialized code action menus, such as refactor (but they should never be applied
- If a user explicitly requests a disabled code action, we show the `.disabled` message 

# Testing
Using the [Code Action Sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/code-actions-sample), test the proposed `.disabled` property. 

- Confirm the expected behavior stated above
- Make sure you can never apply a disabled action
- Try creating cases where a provider returns all disabled actions
- Try creating cases where a provider returns a mix of enabled and disabled actions

**Comment by alexr00** [comment]
@mjbvz How do you do this?

> If a user explicitly requests a disabled code action, we show the .disabled message

**Comment by alexr00** [comment]
Tested on Windows.
