### ISSUE TITLE
Error: EACCES: permission denied, open '/home/vsonline/.vs-liveshare-keychain'

### ISSUE THREAD

**Issue by AdityaGovardhan** [microsoft/vscode#85995]
This error occurred in jupyter notebook when visual studio code **online** was reloaded.

**Comment by KernelDev** [comment]
Hello,

EACCES is an error code in nodejs, that indicates that process has not permission to open a file. May you provide the file permission of /home/vsonline/.vs-liveshare-keychain?

Kind regards,

a Dev

**Comment by whizsid** [comment]
You can set file permission by executing `sudo chown yourusername:yourusername /home/vsonline/.vs-liveshare-keychain` command.

**Comment by AdityaGovardhan** [comment]
Okay I can try that @KernelDev . Also thank you @whizsid  for mentioning the command. I raised the issue because I believe that the end user experience should be seamless and similar to using VSCode locally, since not everybody would be familiar with the above command and hence such permission issues should not occur.
