### ISSUE TITLE
macOS ctrl+v to go to the end of the document

### ISSUE THREAD

**Issue by jsyt** [microsoft/vscode#85997]
- VSCode Version: 1.40.2
- OS Version: macOS(Catalina)

Steps to Reproduce:

1. Ctrl + v is not working
2. Ctrl+V is bound to nothing in the keyboard shortcuts and there is no conflict

Does this issue occur when all extensions are disabled?: Yes!

**Comment by jrieken** [comment]
> Ctrl+V is bound to nothing in the keyboard shortcuts

If it is bound to nothing what do you expect it to do then? Except for doing nothing?

**Comment by jsyt** [comment]
> > Ctrl+V is bound to nothing in the keyboard shortcuts
> 
> If it is bound to nothing what do you expect it to do then? Except for doing nothing?

I expect it to move the cursor to the end of the text just like in the editor.
Thanks!

**Comment by alexandrudima** [comment]
I think we have covered the keybindings from https://support.apple.com/en-us/HT201236 , which doesn't have `Control-V`...

**Comment by jsyt** [comment]
OK! It working!
Thank you very much!
