### ISSUE TITLE
Test: Mobile Safari support

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#85990]
Refs: https://github.com/microsoft/vscode/issues/85254

- [x] anyOS @bpasero

Complexity: 3

We added pointer events support and improved touch gesture handling for Mobile Safari this month, to enable users to use basic functionalities with Web. There are still many blockers currently for Mobile Safari as listed in https://github.com/microsoft/vscode/issues/85254, but we can sanity test the core functionalities. Assigning to @bpasero for now as he has experience with Mobile Safari and has an iPad.

To test this item

* Open Web in Mobile Safari
* Save the page to Home, which turns the page to PWA mode
* It now has full keybindings support. Test basic components.

**Comment by dbaeumer** [comment]
@sbatten @rebornix 

Ben is out of office so this item needs to be assigned to someone else.

**Comment by bpasero** [comment]
I can try to still do this, possibly for December if time is running out. I think it would be good to have another person looking into this and this is also not too critical for our November release either.
