### ISSUE TITLE
PHP autocompletion: $_GET completes into $$_GET

### ISSUE THREAD

**Issue by marlass** [Microsoft/vscode#86]
When using autocompletion for variables it places 2 dollar signs instead of 1. For example typing $_GET will transform it into $$_GET. Fails with every completion starting with $.

**Comment by aeschli** [comment]
fixed

**Comment by anothergituser** [comment]
Hello, Can you also take a look why autocomplete stops working for php?
```
workbench.main.js:1550 WARNING: Promise with no error callback:undefined
workbench.main.js:1550 Error: Promise did not implement oncancel(…)
```
This is how to reproduce.
Say you start writing ```array_chunk```, it autocompletes fine, as you are writing.
Then you open and close the parentheses and now you have this ```array_chunk()```. Now begin to delete what you just wrote, when you delete the parentheses and you get back to having just ```array_chunk``` again that's where that error shows up in the dev tools and autocomplete stops working for everything until you restart the editor. Of course this happens with any other function also not just array_chunk.

I tested this behavior on Fedora 22 and Windows 10 both 64bit
