### ISSUE TITLE
Flag to skip starting VSCode after installation

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vscode#860]
Currently VSCode is automatically started after installing it with `/silent`. For scripted installations this is not an ideal situation. Also this prevents the possibility to set default settings after installation, since they'll be overwritten after VSCode is closed.

There should be an installer flag to avoid automatic startup of VSCode after installation.

**Comment by joaomoreno** [comment]
With our next release, you will be able to run the setup with the additional argument `/mergetasks=!runcode` which will skip the running of Code at the end of the setup.
