### ISSUE TITLE
Can't disable tooltip in shown on hovering html tags

### ISSUE THREAD

**Issue by Souravgoswami** [microsoft/vscode#86009]
Hi, I have been trying to disable the tooltip containing stupid documentations:
![image](https://user-images.githubusercontent.com/37468605/70032021-95dfa980-15d2-11ea-8d1f-3785073263be.png)

I have disabled all the suggestion, and hovering, followed stackoverflow, but that still doesn't disable the tutorial. I have been working on a small window, so that's very very frustrating.

How do I disable the tooltips?

**Comment by gjsjohnmurray** [comment]
Did you try adding this to your settings.json file?

```
    "[html]": {
        "editor.hover.enabled": false,
    },
```

**Comment by Souravgoswami** [comment]
That works, thank you very much!
