### ISSUE TITLE
Custom display name for proper nouns in Settings UI

### ISSUE THREAD

**Issue by eriolchan** [microsoft/vscode#86000]
In the Settings UI, the configuration key will be used to construct a title. Capital letters are used to indicate word breaks which is not suitable for proper nouns.

For example, if the configuration key is IoTWorkbench, UI will shows "Io TWorkbench" which is strange to user. However, I expect UI shows "IoT Workbench". Is there any way for VSCode to solve this problem? or provide a way to custom display name for configuration key in Settings UI?

**Comment by roblourens** [comment]
Sorry it's not optimal, tracking this request in https://github.com/microsoft/vscode/issues/51778
