### ISSUE TITLE
Sync: Keybindings conflict - Show two way diff

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#86019]
Issue Type: <b>Bug</b>

Testing #85941

I disabled keybindings sync, changed a keybinding on both machines (the other is Mac) and then reenabled keybindings sync.

The conflict is shown as a single large change over the entire file:
![image](https://user-images.githubusercontent.com/9205389/70039492-5efd9980-15ba-11ea-8278-f7af924427a2.png)

Comparing the changes shows that there is just a small diff:
![image](https://user-images.githubusercontent.com/9205389/70039635-8e140b00-15ba-11ea-9648-7aee9b5a0062.png)

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:40:39.806Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.97GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.1.0
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.13.0
rest-client|hum|0.23.0
solidity|Jua|0.0.64
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.87.0
remote-ssh-edit-nightly|ms-|2019.12.2400
remote-ssh-nightly|ms-|2019.12.2400
remote-wsl|ms-|0.41.1
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
github-issues-prs|ms-|0.9.2
debugger-for-chrome|msj|4.12.2
vetur|oct|0.22.6
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.6.1
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.13.0
ayu|tea|0.18.0
vscodeintellicode|Vis|1.2.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Yes, this is expected to show the complete changes as we do not 3-way diff to show  conflicts. Open for ideas here.

**Comment by chrmarti** [comment]
The 2-way diff that the diff editor does would be sufficient. Based on the diff shown in the second screenshot, you could create these finer grained merge conflict regions.

**Comment by sandy081** [comment]
Ok, I can show remote (incoming) on the left and current on the right and allow user to update the current and apply changes.

**Comment by sandy081** [comment]
A two way diff is shown now for all conflicts.
