### ISSUE TITLE
Dialogs are different with Electron 7

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#86012]
Testing https://github.com/microsoft/vscode/issues/85994
Not sure if this is intentional, but the same dialog looks different. (please ignore size difference, that's from screen resolution)
![image](https://user-images.githubusercontent.com/38270282/70034564-acc1d400-15b1-11ea-9309-201d0f68419e.png)

**Comment by deepak1556** [comment]
Good catch, thanks!

**Comment by deepak1556** [comment]
https://github.com/electron/electron/issues/20855

**Comment by bpasero** [comment]
LGTM:

![image](https://user-images.githubusercontent.com/900690/72133672-50a55900-3382-11ea-8c00-40bed95741dd.png)
