### ISSUE TITLE
Sync: Keybindings overwritten after enabling sync between platforms

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#86011]
Issue Type: <b>Bug</b>

Testing #85941

I had Windows and Mac with different keybindings. After enabling sync between platforms, the Windows keybindings simply overwrote the Mac keybindings.

I'd expect to be asked to merge the two.

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:35:54.992Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|17%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.1.0
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.13.0
rest-client|hum|0.23.0
solidity|Jua|0.0.64
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.15.3
vscode-azureappservice|ms-|0.16.1
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.87.0
remote-ssh-edit-nightly|ms-|2019.12.2400
remote-ssh-nightly|ms-|2019.12.2400
remote-wsl|ms-|0.41.1
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
github-issues-prs|ms-|0.9.2
debugger-for-chrome|msj|4.12.2
vetur|oct|0.22.6
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.6.1
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.13.0
ayu|tea|0.18.0
vscodeintellicode|Vis|1.2.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Does it overwrote completely or merged it? Because it should merge if possible otherwise it should show you the conflicts.

**Comment by chrmarti** [comment]
Looking closer, I think it merged. There was a keybinding on both platforms for the same command with different keys and that was overwritten (Mac won it seems).

This is from looking at the result now. Let me know if that doesn't make sense and I can try to reproduce.

**Comment by sandy081** [comment]
It merges when the incoming/outgoing changes do not conflict from their base. Please let me know if this is the case or not?

**Comment by chrmarti** [comment]
I enabled sync between platforms for the first time. What's the base in that case?

**Comment by sandy081** [comment]
When you enabled sync across platforms for the first time ever then its base and remote are null. So local wins and uploaded to remote. 
When you enabled sync across platform on another machine for the first time (but not first time ever) then base should be null and remote should be the latest on the server.

**Comment by chrmarti** [comment]
What if remote has a keybinding for the same command as local when base is null? Should the two keybindings stay or just one of them?

Is there a way to reset remote and base to null?

**Comment by sandy081** [comment]
it shall show conflict in this case.

**Comment by sandy081** [comment]
Assigning to May for investigation.

**Comment by sandy081** [comment]
I am back to it after long time.

I have following keybindings.json in Mac

```
[
    {
        "key": "shift+cmd+c",
        "command": "editor.action.insertCursorAbove",
        "when": "editorTextFocus"
    },
    {
        "key": "alt+cmd+up",
        "command": "-editor.action.insertCursorAbove",
        "when": "editorTextFocus"
    }
]
```

I have following keybindings.json on Windows

```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+shift+c",
        "command": "editor.action.insertCursorAbove",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+up",
        "command": "-editor.action.insertCursorAbove",
        "when": "editorTextFocus"
    }
]
```

- Turned on Sync on Mac, all good as it just pushes data
- Turned on Sync on Windows, got a dialog to merge/replace as expected
- I tried both merge and replace and none of them overwrote my keybindings in windows

@chrmarti Sorry that it is long time back, but May I know if I am missing anything here?

**Comment by chrmarti** [comment]
Not sure if there was anything I did in addition, but even then this has likely been fixed since. I suggest to close the issue.
