### ISSUE TITLE
Polish debug console input output grouping

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86016]
1. Do not use arrows, just > or <
2. Move the tree expadno a bit to the right
3. Check out why we removed the line separator in the past

fyi @weinand

**Comment by isidorn** [comment]
I moved the expando to the right.
I droped the arrows and went with the expando.
And I increased the opacity to not make them so load. I am happy with the current state of things
fyi @misolori 

Adding bug so we get this verified @weinand 

<img width="365" alt="Screenshot 2019-12-05 at 20 40 06" src="https://user-images.githubusercontent.com/1926584/70267804-777ad900-179f-11ea-8e88-31853f9457a5.png">

**Comment by eamodio** [comment]
IMO, the `<` next to the expando looks strange, but it might be more the alignment that is causing most of the issue for me:
![image](https://user-images.githubusercontent.com/641685/70277373-44751d00-1780-11ea-8293-923d441ac2e7.png)

**Comment by isidorn** [comment]
Thanks for the feedback. We can add more alignemnt, however not for Endgame. Though I do on my machine it looks much better.
It might be that codicons are not proeprly centered on Win

![Screenshot 2019-12-06 at 11 10 54](https://user-images.githubusercontent.com/1926584/70315103-2d363e00-1819-11ea-98d9-e545909a62a5.png)
