### ISSUE TITLE
Introduce an universal newline character like \R

### ISSUE THREAD

**Issue by zhangxiubo** [Microsoft/vscode#8601]
- VSCode Version: 1.3.0-Insider (2016-07-01 build)
- OS Version: Windows 7

Steps to Reproduce:
1. Open a new buffer;
2. Type three lines of text;
3. Open the find and replace dialogue and turn on regex;
4. In the Find field, input \n; in the Replace with field, input a whitespace;
5. Hit replace all.

The whitespace is supposed to replace the newline character entirely, but it seems the newline character is retained --- whatever is replacing \n got appended to each of the matching newline.

**Comment by alexandrudima** [comment]
@zhangxiubo Are you using `\r\n` as the EOL sequence in your file?

![image](https://cloud.githubusercontent.com/assets/5047891/16519694/223ed922-3f8b-11e6-9be7-4bfc0a8b6942.png)


In that case you'd need to search for `\r\n`:

![ggjnzdyc7m](https://cloud.githubusercontent.com/assets/5047891/16519729/64daaa4a-3f8b-11e6-9850-89ecdc36c878.gif)

**Comment by zhangxiubo** [comment]
@alexandrudima Thank you for your reply. Yes you are right, using `\r\n` works (I thought of it before but mistakenly tested `\n\r` perhaps). :+1: Wouldn't it be nice for VS Code to introduce an universal newline meta- like the `\R` in Sublime Text. :smile:

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
