### ISSUE TITLE
Freeze in C++ file with particular content

### ISSUE THREAD

**Issue by w-flame** [microsoft/vscode#86014]
Issue Type: <b>Bug</b>

VSCode is freezing after opening C++ file with this content:
```
json_safe_sprintf(msg3, "\":[", atol(row[8]) /*current car id*/, atoi(row[10]) /*ta driver version*/, atol(row[13]) /*exchange_member_id*/, tmp_line2, atol(row[16]) /*group_id*/, row[1] /*login*/, atof(row[17]));
```
I maximaly shrink code which still represents isuue. 
Freeze  happens only in C++ mode, if opening in C mode it's OK. 
Freeze happens with and witout C++ extensions installed/enabled.
Freeze happens on Mac and PC with current VSCode versions and some previous releases.

You  can save this string of code to test.cpp and open it in VSCode. VSCode will freeze immediately.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|2.1.3
python|ms-|2019.11.50794
remote-wsl|ms-|0.40.3
cpptools|ms-|0.26.2
csharp|ms-|1.21.8

</details>

**Comment by w-flame** [comment]
I did some research and found that bug wal introduced in version 1.39

**Comment by alexr00** [comment]
Upstream https://github.com/jeff-hykin/cpp-textmate-grammar/issues/426
