### ISSUE TITLE
Search: do not show preview when replace is empty?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8602]
Marking important for discussion: I find it weird at the moment that clicking a search result opens the preview of replace only because I have the replace input field expanded:

![image](https://cloud.githubusercontent.com/assets/900690/16515162/a9aa825a-3f70-11e6-8b50-b6e2568bdcc4.png)

It is especially bad because the results all show in the color of a normal search result.

I suggest that for this case when you click on a result, we just open it like a search result.

**Comment by sandy081** [comment]
@bpasero makes sense. It was result of clean up while fixing. 
In this case, replace preview should not open but we can still show replace specific actions on the entries.

**Comment by bpasero** [comment]
Ok setting for June then.
