### ISSUE TITLE
wrong parenthesis at autocomplete

### ISSUE THREAD

**Issue by 7be** [microsoft/vscode#86020]
Issue Type: <b>Bug</b>

Hi all,

while using the latex extension, which in my opinion includes Intellisense I have an autocomplete probleme:
typing \todo it autocompletes \todo{}{} which makes no sense.
correct would be \todo[]{}. I found no way to customize it.
My favority would be to have it autocomplete to \todo[inline]{}.
Is there a file, where I can change the suggestions?
Thanks

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment]
/causedByExtension

VSCode doesn't provide support for LaTeX out of the box and as you mentioned
> while using the latex extension

Please create issue for extension you are using
