### ISSUE TITLE
Folder updates when expanding

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86024]
re  #85928

* use the Java Dev container
* expand `test-project > src`
* expand `main`
* :bug: the "label" of the main project updates, I would expect it to be proper when expanding `src`

![Dec-03-2019 11-15-26](https://user-images.githubusercontent.com/1794099/70041939-50b17c80-15be-11ea-99f6-6df4c00c16dc.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/84703
