### ISSUE TITLE
View dragged title has a number at the end

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86029]
Refs: #85908

1. Drag a view inside a viewlet, for example the Enabled or Recommend view in the Extensions
2. The drag title has a strange label, for example "Enabled15" or "Recommended0". It should not have that number at the end

I can repro with stable insiders, so probably not introduced by you

**Comment by sbatten** [comment]
@sandy081, caused by your indexing changes from earlier this milestone?

**Comment by sandy081** [comment]
> I can repro with stable insiders, so probably not introduced by you

Also in stable, so I think not by changes done in this milestone.

**Comment by sbatten** [comment]
@sandy081 is that the right area label?

**Comment by sbatten** [comment]
This no longer repros as we use the entire header as the draggable item
