### ISSUE TITLE
Firefox: custom dropdown renders not needed inner focus box

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86026]
Refs: https://github.com/microsoft/vscode/issues/85988

1. OS X, Firefox, web

Focus on a custom dropdown in settings. Inner focus is rendered (the white dotted line). It should not be there since it brings no value and overlaps with the chevron

![Screenshot 2019-12-03 at 11 20 24](https://user-images.githubusercontent.com/1926584/70042401-11376000-15bf-11ea-8fe4-1c08f5863d58.png)

**Comment by misolori** [comment]
@rebornix do you have any idea how this dotted border is being added to all `select` inputs on FF? I've tried the various `select::-moz-focusring` and `select::-moz-focus-inner ` with on luck and am at a loss.

**Comment by misolori** [comment]
Tuns out the only way to fix this is to set the text color to transparent and use text shadow to show the text:

```
.select:-moz-focusring {
    color: transparent !important;
    text-shadow: 0 0 0 #000 !important;
}
```

So I'll need to somehow pass the dropdown foreground color to this style.

**Comment by bpasero** [comment]
Not seeing this anymore:

![image](https://user-images.githubusercontent.com/900690/128017451-62950061-7128-4c45-8d4d-0bc66c39d1a3.png)

**Comment by isidorn** [comment]
Yup also seems to work for me. Closing
