### ISSUE TITLE
Compact folder rendering looks weird

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86025]
re #85928

IMO we had a much better in-between solution using chevrons or no spacing. To me the slash and the spacing look like screen cheese. 

<img width="306" alt="Screenshot 2019-12-03 at 11 18 27" src="https://user-images.githubusercontent.com/1794099/70042173-b69e0400-15be-11ea-8f66-539db89b4d8b.png">

<img width="307" alt="Screenshot 2019-12-03 at 11 18 07" src="https://user-images.githubusercontent.com/1794099/70042183-ba318b00-15be-11ea-8a6b-52388519b4be.png">

**Comment by jrieken** [comment]
Proposal: Use normal character spacing and opacity

<img width="308" alt="Screenshot 2019-12-03 at 11 50 30" src="https://user-images.githubusercontent.com/1794099/70044706-2615f280-15c3-11ea-96e9-193e76ba1c0f.png">

**Comment by joaomoreno** [comment]
Closing this for now and waiting for more user feedback.

**Comment by gabeklein** [comment]
Personally I'd like to see an option to make nested folders less prominent (lighter, less opacity). Reason being that usually the root folder is the relevant, most "unique" folder and should be visually more prominent.

**Comment by gjsjohnmurray** [comment]
@gabeklein by "the root folder" do you mean the leftmost one on the sequence? In other words, you'd like the opposite of what @jrieken proposed in his screenshot [here](https://github.com/microsoft/vscode/issues/86025#issuecomment-561112797)?

**Comment by gabeklein** [comment]
@gjsjohnmurray

**Comment by joaomoreno** [comment]
> If I had a way to explicitly set the opacity of /src ect... I'd make it close to zero, resulting in the second image just without the extra line for subfolder. It'd make my development experience a lot more comfortable.

What if you had the possibility of letting the explorer know that `express` and `interface` and `webpack` should not be _folded up_?

**Comment by gabeklein** [comment]
@joaomoreno Sorry I don't really follow, could you explain?

**Comment by joaomoreno** [comment]
I mean: a workspace setting that you could mark certain folders never to be folded up. I believe your argument has something to do with the `lib/*` folders, and not just any folder, being folded up with a single child.

So we could offer a setting, e.g. `explorer.preventCompactFolder` which would have a glob pattern value, eg. `lib/*`, and the explorer wouldn't render those folders as compact, even if they only have a single child.
