### ISSUE TITLE
Need two left arrow presses to get to parent

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86032]
re https://github.com/microsoft/vscode/issues/85928

* use Java 12 dev container
* in the explorer reveal and select App.java
* press App.java, press arrow-right
* press Arrow-left
* :bug: app-folder isn't selected, it requires a 2nd arrow-left press

**Comment by rebornix** [comment]
It's weird that you also need to press Arrow Right more than once to expand the compressed node, however you only need one mouse click to expand.
