### ISSUE TITLE
Hide debug launches drop down in empty window

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86034]
Testing #85774

- Open empty vscode window
- Open a file that can be debuggable
- Put a breakpoint and start debugging:
- When breakpoint is hit, following view is shown

Hide debug launches drop down in empty window as they are not doing anything.

![image](https://user-images.githubusercontent.com/10746682/70044243-47c2aa00-15c2-11ea-8d82-2d2f65de8d5b.png)

**Comment by isidorn** [comment]
I can not reproduce.
How do you get into this state? Are you in a purple vscode?
Whenever I am in a no folder vscode I always get the debug start view and the drop down is not shown

**Comment by sandy081** [comment]
Sorry for providing full details. Updated the summary.
