### ISSUE TITLE
Remote: hidden view can not be brought back

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86039]
1. Vscode insiders, install remote SSH extension
2. Open the Remote view container
3. Hide all the views via context menu
4. Context menu on the title -> the views are not there and they can not be brought back 🐛 
5. Reload -> the views are back -> I would expect the hidden state to be preserved 🐛 

fyi @alexr00 

![remote](https://user-images.githubusercontent.com/1926584/70045024-ae949300-15c3-11ea-8462-b5af21b2cf87.gif)

**Comment by sandy081** [comment]
Assigning to @alexr00 as remote viewlet has special treatment.

**Comment by alexr00** [comment]
Original decision was that none of the views in the filter-view should be hide-able. Looks like I missed a spot!
