### ISSUE TITLE
Remote view select box out of style

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86031]
Refs: #85988

macOS, remote view, look at the select box at the top. Notice how it is out of the style with other select boxes in our product:
1. It has sharp corners
2. Chevron is not centered relatvie to the the inner blue focus
3. it is taller than our other select boxes

![Screenshot 2019-12-03 at 11 37 08](https://user-images.githubusercontent.com/1926584/70043831-78561400-15c1-11ea-84e1-774a45e74c29.png)

![Screenshot 2019-12-03 at 11 39 20](https://user-images.githubusercontent.com/1926584/70043875-915ec500-15c1-11ea-86e7-236f18ab0051.png)

**Comment by alexr00** [comment]
macOS specific, since on Windows none of them have rounded corners, the chevron is centered, and the height is the same. I'll need to borrow a Mac :).

**Comment by isidorn** [comment]
If you use our `SelectBox` you should be fine since in all other places it is aligned.
[Here](https://github.com/Microsoft/vscode/blob/8b449d1a0874b52b9a2d088ed1be6a7fd8d0051b/src/vs/workbench/contrib/debug/browser/debugActionViewItems.ts#L49) is how the Debug is using it
Not sure if you can do the same...

**Comment by alexr00** [comment]
I use the `SelectActionViewItem` which does use the `SelectBox` similarly to how Debug is using it. I will look into what could be missing.

**Comment by isidorn** [comment]
Maybe some .css rules are written to target only the vscode internal containers (just an idea, I would check css). I would search for `border-radius` css rule.

**Comment by misolori** [comment]
Added rounded corners on the Mac:

![image](https://user-images.githubusercontent.com/35271042/70099978-40f95e80-15e5-11ea-8718-e22f4622d043.png)
