### ISSUE TITLE
Remote Explorer: when there is only one view, split view should not be present

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86037]
Refs: #85908

1. Have a contributed view container like remote
2. Hide all views except one 
3. That view is still shown in a split view. Instead it should be merged with the container (same  as our vscode container behave, for example Explorer). It should no longer be inside a split view

This is also happening in Insiders
fyi @sandy081

**Comment by sandy081** [comment]
I think this is expected ad remote viewlet has special behaviour and is not merged. 

@alexr00 Please confirm?

**Comment by alexr00** [comment]
That is correct, remote viewlet has special behavior and is not merged since the merging conflicts with the drop down.

**Comment by isidorn** [comment]
I find that inconsistent - couldn't we merge the actions from the container with the actions of the view? Would there be too much? 
Feel free to close as designed.

**Comment by alexr00** [comment]
Since the drop-down functions as a filter I think keeping the things it filters (views, including actions) below it it is clearer than having the title change and having actions move to be next to the drop-down. If we merge, it could look like those are top level actions and a top level title, which it is not. I will bring up at the next UX sync to get more input.

**Comment by isidorn** [comment]
That's makes sense, however since it is for a UX sync, we will probably not tackle it this week. Thus maybe assign to next milestone not this one?

**Comment by alexr00** [comment]
After UX discussion, this is the goal:
![image](https://user-images.githubusercontent.com/38270282/71976665-297e4880-3217-11ea-8c60-06b7c5dfea6e.png)
Then when there is only one view, the title still makes sense and there is room for the buttons.

**Comment by alexr00** [comment]
Moving to February so that it will have more time in insiders for feedback.
