### ISSUE TITLE
Further configure message is confusing when no file is opened

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86038]
Testing #85774

![image](https://user-images.githubusercontent.com/10746682/70044538-d9321c00-15c2-11ea-9e6a-69b2e9be148c.png)

I see above view when there is no file opened or a file cannot be debuggable. Asking to open a file makes sense. But I do not understand the other message `To further configure...`. 

Is not that this message makes sense only when file is opened that can be debuggable and do not show this message otherwise.

So, When no file or folder is opened is not the following message enough?

`Open a file or folder which can be debugged or run`

**Comment by isidorn** [comment]
This was also under discussion between @weinand and me.

Same as with the disabled buttons we want to sell to the user that he should open a folder and that much more features will be available. And yes this also makes sense if the user has no file open, and wants to start debugging. Depends on what debugging he wants to do. If he just wants to debug/run a file than the first message is just fine, however if he wants to debug his complex project well he should open a folder.
The other part is optional, thus it is at the end and has "to further" wording.

I am perfectly fine with removing this line when no folder is open and no file is open. Above I am simply explaining the reasoning behind having it.

fyi @misolori @chrisdias @roblourens @connor4312 

Leaving this open and under discussion for now, let's see what we land on.
Thanks

**Comment by sandy081** [comment]
IMO for newbies or first time users, it is quiet confusing to do more configuration when I have not opened any thing that is debuggable.
