### ISSUE TITLE
Hide the debug / run buttons when not enabled

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86041]
Testing https://github.com/microsoft/vscode/issues/85774

Why not hiding the buttons instead of disabling them? This might make UI look lighter when no file is opened?

**Comment by isidorn** [comment]
This was an open discussion between @weinand and me.
@weinand wanted the buttons to be hidden, I prefered them disabled.
My reasoning was that having them disabled shows the user the possibility that will be available to him once he does what we ask him to do. So it sort of sells the possibilities of the debug viewlet.
Another reason is that without them the view would just have text and be boring.

I am leaving this open and under discussion for now and we can change how it behaves, I am flexible. 

fyi @misolori @chrisdias

**Comment by isidorn** [comment]
Closing as will not change. We will only show the one button though and it will bi disabled / enabled
