### ISSUE TITLE
Remember the debugger choice

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86042]
Testing #85774

- Have chrome debugger extension installed
- Open a simple js file in vs code
- Open debug viewlet
- Click on debug button
- Choose from the debugger dropdown and select for eg `node.js`.
- Stop debugging
- Click on debug button again

It asks to select debugger again. Why not remember the option I chose before?

**Comment by isidorn** [comment]
This makes sense. However where would you remember this choice? And what if the user made the wrong choice, how would he undo his choice?
Writing into settings is ugly imho, and writting into storage makes it hard for this to be undone.

I am open for suggestions
fyi @weinand @roblourens @connor4312

**Comment by sandy081** [comment]
Yeah good point that what if user makes wrong choice. I do not have suggestion for where to remember it unfortunately.

**Comment by roblourens** [comment]
I disagree, if they want the choice to be remembered, they can create a launch config.

**Comment by isidorn** [comment]
Ok. No action planned. Closing as out of scope.
