### ISSUE TITLE
Support Time Travel Debugging in Javascript

### ISSUE THREAD

**Issue by alyahmedaly** [microsoft/vscode#86040]
I know this feature is implemented but I wish to have it for typescript/javascript too if possible not sure this will be editor feature or runtime feature  (node,v8, whatever)

**Comment by IllusionMH** [comment]
/needsMoreInfo

What do you mean with "moving the debugger cursor to another line"?
Debuggers for Node, Chrome, and Edge have "Step into" and "Step Over".
Basically Step Over will continue execution to next statement which is usually next line.

**Comment by alyahmedaly** [comment]
@IllusionMH what I mean is moving the cursor to the previous executed line so you can execute it again like c# for example in visual studio you can move to debug cursor to any other line
here you can see that you can change code flow using debug cursor. [visual studio docs](https://docs.microsoft.com/en-us/visualstudio/debugger/navigating-through-code-with-the-debugger?view=vs-2019#BKMK_Set_the_next_statement_to_execute)

**Comment by gjsjohnmurray** [comment]
@alyahmedaly I assume you are referring to [Jump to Cursor](https://code.visualstudio.com/updates/v1_36#_jump-to-cursor) which arrived in 1.36 but only lights up if the debug extension you're using supports it.

**Comment by IllusionMH** [comment]
> moving the cursor to the previous executed line so you can execute it again

This sounds like Time Travel Debugging and unfortunately it needs support from JS runtime.
AFAIK only [node-chakracore supported TTD](https://www.linux.com/news/nodejs-chakracore/) and this unfortunately there is nothing similar in V8 (and therefore Node, Chromium etc.)

**Comment by weinand** [comment]
The feature known from C# is not called "Time Travel Debugging" but it is called  "Jump to Cursor" as @gjsjohnmurray correctly pointed out. This feature is automatically enabled in VS Code if the underlying runtime supports it.

"Time Travel Debugging" is supported by VS Code too, but only the Chakra-based runtimes and a few other debuggers support it. Again, this feature is automatically enabled in VS Code if the underlying runtime supports it.

Another feature similar to what you are asking for is "Restart Frame", which starts execution at the start of the current function. This is available for JavaScript.

**Comment by alyahmedaly** [comment]
Just for other people to know I found restart frame button vsCode call stack is useful for this case 
![image](https://user-images.githubusercontent.com/6495633/70623573-b89b3f00-1c1e-11ea-95a6-45f80468214f.png)
