### ISSUE TITLE
Debug/Run actions are not enabled when opening a node project

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86047]
Testing #85774

- Open a node project (eg: vscode-smoketest-express)
- Go to debug view

Debug and Run buttons are not enabled.
I expect them to be enabled as the debugger knows creating a program in `launch.json` automatically.

**Comment by isidorn** [comment]
You do not have a javascript file open. Thus VSCode UX does not know which debug adapter to pick.
This is a fair feature request, however nothing that is within reach with the current architecture.
