### ISSUE TITLE
Show debug view when opening a folder from debug view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86044]
Testing https://github.com/microsoft/vscode/issues/85774

- Open empty vs code
- Go to debug view
- Open folder from the link in the view
- Folder gets opened but user lands into explorer view. Instead user should be landed into debug view to start debugging.

**Comment by isidorn** [comment]
Yes, fully agree. The issue is that when opening a folder we always open the Explorer view.
This would have to be passed through from the debug to the dialog service to the window service.
Not for endgame, assinging to next milestone to look into this.

**Comment by isidorn** [comment]
@bpasero currently I use `dialogService.pickFolderAndOpen` to open the folder. However there does not seem to be a way to specify what viewlet should be opened?
An alternative which IMHO makes sense in all cases is that if I open another Folder in the same window the same viewlet would be shown. We should not switch viewlets.
Let me know what you think

**Comment by bpasero** [comment]
That logic sits here: https://github.com/microsoft/vscode/blob/cbeff45f80213db0ddda2183170281ed97ed3b12/src/vs/workbench/browser/layout.ts#L456-L461 and is currently a workspace setting, not a global setting. So it would be harder to define that property upfront.

**Comment by isidorn** [comment]
@bpasero and that is only read from local storage if I am reloading which i am not.
So the only ugly way to make this work is to introduce some new ugly storage state which would take priority and which I would set. Or somehow to change the `defaultViewletId`.

Nothing I would like to do right now. 
However keeping this feature request open and we see if users also hit this. This I do agree that it fully makes sense.
