### ISSUE TITLE
Open folder link is not opening the project folder

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86049]
Testing #85774

I used vscode-smoketest-express for testing
- From an empty vscode widnow, in debug view, open file `~bin/www` in `vscode-smoketest-express`
- Now click on open folder link that says to further configure..
🐛 I would expect the picker/dialog to show the root folder to open instead it shows the `bin` folder.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/85769
