### ISSUE TITLE
Uri class converts $ to %24

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#86043]
I don't know if this is related to #83645, but my comment on that issue was marked as off-topic.

The URI class seems to unexpectedly encode the `$` character:

```ts
vs.Uri.parse("http://localhost:1234/$debug").toString()
"http://localhost:1234/%24debug"
```

Similar code in JavaScript doesn't do this:

```js
new URL('http://localhost:1234/$debug').toString()
"http://localhost:1234/$debug"
```

**Comment by jrieken** [comment]
Yes - that a known bug that we cannot fix anymore as too many extension are relying on the "wrong" encoding.

**Comment by DanTup** [comment]
@jrieken are there any plans to address this in some other way? It feels weird to have to do manual replacements on URIs all over the place for expected behaviour (probably extensions will end up making their own class). Couldn't it be solved with a flag on the object, so we can opt-in to "correct" behaviour?

**Comment by jrieken** [comment]
@jrieken are there any plans to address this in some other way? 

The general answer is "no" (see https://github.com/microsoft/vscode/issues/83645) but it depends on your use-case

**Comment by DanTup** [comment]
> support URL in our API, namely `openExternal` and `DocumentLinkProvider`

The place I hit this was `asExternalUri`. If that will be updated to use a compliant URL (I presume it would if `openExternal` is), then I think that solve the place I've had to put custom replaces. However the issue that's linked to is closed and links back to that issue, so it's not clear whether that's still the plan?

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/85930
