### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by JostCrow** [Microsoft/vscode#8604]
- VSCode Version: 1.3.0-insider
- VSCode Commit: 716f76458e4dc93e865b6a999e437ed45774744e
- OS Version: Elementary OS 0.3

Now I am able to search for extensions. Only I am not able to install them. Nor do I get any feedback.

I really wish to give more information. But also the dev tools do not give any feedback. Even with Pause On Caught Exceptions.

**Comment by bpasero** [comment]
@JostCrow so what happens? can you share a video or screen shots?

**Comment by JostCrow** [comment]
![output](https://cloud.githubusercontent.com/assets/390575/16517719/449c9bc8-3f7f-11e6-8c37-6566d4f6e38a.gif)

Other than this I do not get any feedback. Could it be the same reason as #8605 ?

**Comment by isidorn** [comment]
It might be connected - let's wait for the other issue

**Comment by JostCrow** [comment]
Also this issue is resolved after uninstalling every extension.

**Comment by isidorn** [comment]
Great - I commented on the other issue which was the root cause (adding duplicate here)
