### ISSUE TITLE
GitHub Desktop has a much better user experience for accounts

### ISSUE THREAD

**Issue by georgestevens99** [microsoft/vscode#86045]
Issue Type: <b>Feature Request</b>

In GitHub Desktop the File>Options>Accounts dialog provides a really nice, intuitive, and easy way to switch between numerous Git accounts and authentication to the repos in them. 

I am very disappointed that VS Code offers NOTHING in this area.  Am I missing something?  

I am forced to drop out of VS Code and open up the Windows Credential Manager and delete the unusable credential that is causing my pushes to fail.  And after I do that then back to VS Code terminal window to push again, which kicks off a Git prompt for authentication.  

Why not go easy on us and put this capability in VS Code like it is in GitHub Desktop -- VS Code would look a lot more modern that it does now.  

Thanks, George

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
We currently have no specific Github features in Code itself. It might come in the future, but not for now.
