### ISSUE TITLE
Debug view is not merged into viewlet header if it only view in debug viewlet

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86056]
Testing #85908

Debug view is not merged into viewlet header if it only view in debug viewlet

![image](https://user-images.githubusercontent.com/10746682/70049406-e94ef900-15cc-11ea-9d68-c14d30e21110.png)

**Comment by sbatten** [comment]
this is actually in stable as well, is it intended to merge or not due the large dropdown box in the header?

**Comment by sandy081** [comment]
Yes you are right about stable but it seems this got changed in current release to merge into title area

@isidorn FYI

**Comment by isidorn** [comment]
We should merge the view in the debug viewlet if there is only one. Thanks

**Comment by sbatten** [comment]
fixed, thanks
