### ISSUE TITLE
bug in python

### ISSUE THREAD

**Issue by skshahriarahmedraka** [microsoft/vscode#86059]
Issue Type: <b>Bug</b>

in python "None" is working but  not comming in suggestion list

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:38.728Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|10.95GB (4.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.5
code-runner|for|0.9.15
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
LiveServer|rit|5.6.1
vscode-icons|vsc|9.6.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please provide detailed steps on how to reproduce this. Screenshots may be useful (e.g. from Snipping Tool on Windows). They can be pasted directly into GH from your clipboard.

**Comment by octref** [comment]
Please report to https://github.com/Microsoft/vscode-python
