### ISSUE TITLE
Dropdown in settings look different

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86050]
re https://github.com/microsoft/vscode/issues/85988

* ubuntu 16.04, FF70
* open setting editor
* 🐛 the drop downs look embossed (those in debug look normal)

<img width="1063" alt="Screenshot 2019-12-03 at 12 31 45" src="https://user-images.githubusercontent.com/1794099/70047777-04b80500-15c9-11ea-839a-694e085746db.png">

**Comment by misolori** [comment]
Firefox has 2px defaults for `border-block` and `border-inline` so I set those to `none`:

![image](https://user-images.githubusercontent.com/35271042/70160914-1d2f2a80-1670-11ea-9dc6-73cdcf65ebe4.png)
