### ISSUE TITLE
code runner

### ISSUE THREAD

**Issue by belokarvp** [microsoft/vscode#86054]
Issue Type: <b>Feature Request</b>

code runner is installed in Microsoft VS Code (System Installation) 

After running the the code previous output is not being cleared

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.3.9600

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by octref** [comment]
Please report to the code runner extension.
