### ISSUE TITLE
Can not view installed and outdated extensions

### ISSUE THREAD

**Issue by JostCrow** [Microsoft/vscode#8605]
- VSCode Version: 1.3.0-insider
- VSCode Commit: 716f76458e4dc93e865b6a999e437ed45774744e
- OS Version: Elementary OS 0.3

This happens on Installed and outdated extensions. I can search, view popular and recommended extensions. If more info is needed I am happy to provide it.

![screenshot from 2016-07-01 10 08 58](https://cloud.githubusercontent.com/assets/390575/16515713/e135eef0-3f73-11e6-8b41-1173b69f7104.png)

**Comment by bpasero** [comment]
@isidorn maybe you connect with @JostCrow to debug this?

**Comment by isidorn** [comment]
@JostCrow thanks for the awesome screenshot! It seems like you have a broken extension installed.
What happens if you delete all your extensions via the command line and install them again? You can do that using the following commands:
```
code-insiders --list-extensions
code-insiders --uninstall-extension ...
code-insiders --install-extension ...
```

I can put some null guards in the code - but I do not think that is the solution since the code is based that either `this.local` or `this.gallery` are not `null`. In your case somehow both of them are and since the original author is on vacation this week I am a bit puzzled.

**Comment by JostCrow** [comment]
Yes I will give it a try

**Comment by JostCrow** [comment]
I uninstalled all the extensions. It said that they where successfully installed.

Then I run --list-extensions again. This is what it returned.

HookyQR.beautify
bcmarinacci.theme-material
cssho.vscode-svgviewer
donjayamanne.python
robertohuertasm.vscode-icons

So these where not uninstalled.

**Comment by isidorn** [comment]
Ok - let's try to manually remove them, if you go to your user folder you should have a .vscode-insiders\extensions -> delete everything inside and restart vscode

**Comment by JostCrow** [comment]
Ok

**Comment by JostCrow** [comment]
After uninstalling all the extensions and restarting the computer it works. Thanks.

**Comment by isidorn** [comment]
Not sure how you ended up in that broken state, so I would leave this issue open so @joaomoreno can investigate next week once he is back.
Since you are the only one seeing this and since there is a workaround I am putting this for july

**Comment by joaomoreno** [comment]
@JostCrow Is there any way you have a backup of the `.vscode-insiders/extensions` folder from when you had this issue? We will find the answer to this problem by looking at the folder structure at the time you had the issue.

**Comment by JostCrow** [comment]
I did not make a backup of the folder. But I can recover the manually deleted items. But all the uninstalled are gone.

**Comment by joaomoreno** [comment]
Yeah I'm curious to see what the `extensions` folder had at the time you had this issue.

**Comment by JostCrow** [comment]
[extensions.zip](https://github.com/Microsoft/vscode/files/346313/extensions.zip)

**Comment by joaomoreno** [comment]
Argh, didn't help much, unfortunately. I'll close the issue and wait for more, in case other people run into it.

Also notice that you seem to have the `vscode-icons` extension installed which potentially damages Code's runtime behaviour.

**Comment by JostCrow** [comment]
Yes I had. But I have removed it since.

**Comment by robertohuertasm** [comment]
@JostCrow are you still experiencing same issues with latest versions? In case you are, please, could you open an issue in [vscode-icons repo](https://github.com/robertohuertasm/vscode-icons)?
