### ISSUE TITLE
[html] auto rename: auto-remove results in extra undo

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86055]
Testing #85973

```html
<html>
    <foo>

    </foo>
</html>
```

- set cursor at the end of `foo`
- insert space, space is only added to first element
- undo
- space is not removed (but added on the closing tag)

According to @jrieken this could be solved by adding a keybinding that takes over the space key when a certain context is set. It removes the multicursor and then inserts the space.

**Comment by octref** [comment]
I don't think we should do that. I use Vim and a keybinding wouldn't allow me to undo that stack with `u`.

When you are typing a space there I expect 99% of the users mean to actually write an id or attribute. If he doesn't and is planning to undo, an extra undo feels ok for me.

**Comment by octref** [comment]
Currently auto-rename-tag makes every edit two edits, and people don't even complain that to it, so I feel this is fine.
