### ISSUE TITLE
No activations event for file events

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#86063]
Testing https://github.com/microsoft/vscode/issues/85929

We should have activation events for the provided file events (e.g. `onWillRename`, ...)

**Comment by jrieken** [comment]
This needs to go into the textfileservice and(or?) the working copy service

**Comment by bpasero** [comment]
To clarify: is this about allowing an extension to get activated on the new text file events introduced? Similar to how we activate file system providers for example?

**Comment by dbaeumer** [comment]
Yes.

**Comment by bpasero** [comment]
@dbaeumer any thoughts on the naming for such an activation? I assume you would want just one activation for any file operation and not one per kind right?

@jrieken 

> This needs to go into the textfileservice and(or?) the working copy service

Isn't this the right place? Right before we call `$onWillRunFileOperation`:

https://github.com/microsoft/vscode/blob/8e66829775a449c00908fc82698781911c724f8f/src/vs/workbench/api/browser/mainThreadFileSystemEventService.ts#L59-L59

**Comment by dbaeumer** [comment]
To ensure that it is not mistaken with file events one idea would be `onFileOperation`

**Comment by bpasero** [comment]
@dbaeumer so `onFileOperation` would be the activation event when:
* `onWillCreateFiles`
* `onWillDeleteFiles`
* `onWillRenameFiles`

Fires?

**Comment by dbaeumer** [comment]
Yes, I think one is enough. We don't need to distinguish between create, rename and delete.

**Comment by jrieken** [comment]
Wouldn't the existing `onFileScheme:<scheme>` be enough? It fires whenever an file is read or written

**Comment by bpasero** [comment]
Looks like we don't need this.

![image](https://user-images.githubusercontent.com/900690/97998829-e1a26080-1dea-11eb-9857-b9008ac2577a.png)

**Comment by dbaeumer** [comment]
@bpasero just checking: wouldn't you need to trigger the activation. I assume a delete does neither read nor write the file.

**Comment by bpasero** [comment]
@jrieken with your undo logic, you now read files before delete to support undo right?

**Comment by bpasero** [comment]
I take it back, any IO operation whatsoever will activate the file system provider:

https://github.com/microsoft/vscode/blob/d81f0e499283838ab70eb681ec913df198c038e2/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L117-L119

Via

https://github.com/microsoft/vscode/blob/bb3aaa780099662751cf9b02be6fe02407af1b00/src/vs/platform/files/common/fileService.ts#L116-L117
