### ISSUE TITLE
Sensible settings of windows.zoomLevel result in jittery scrolling

### ISSUE THREAD

**Issue by gavofyork** [Microsoft/vscode#8606]
- VSCode Version: 1.2.1
- OS Version: Mac OS 10.11.2

Steps to Reproduce:
1. Use these user settings:

```
{
    "editor.fontSize": 13,
    "editor.lineHeight": 14,
    "window.zoomLevel": -2,
}
```
1. Vertically scroll a text window

Notice that the lines do not stay equidistant from each other, but rather jitter as though each has a non-unit vertical position which is rounded differently.

It's not easy to see from these images, but if you do a pixel-level comparison, you'll see the line beginning "Controls the number of decorations" moves relative to the others.

![image](https://cloud.githubusercontent.com/assets/138296/16517189/162fd0bc-3f74-11e6-9812-04d6c3ba3d17.png)
![image](https://cloud.githubusercontent.com/assets/138296/16517203/285d9742-3f74-11e6-8d99-27477017db77.png)

**Comment by alexandrudima** [comment]
@gavofyork If you are sensitive to get things pixel-perfect (like me), I can recommend not to use `window.zoomLevel`. We do everything correct on our side, paint the `<div>s` at integer coordinates, etc. But by setting `window.zoomLevel` to `-2` I think Chromium interprets that as `80%` and begins multiplying all our nice integers with `0.8`. This causes the nice integers to become floats and it is inevitable that they get rounding errors.

I recommend to stick with customizing `fontSize` and `lineHeight`. I wonder what makes you want to change `window.zoomLevel` to begin with?

**Comment by tompiarulli** [comment]
I'm not the OP but to speak to why someone would change the zoom level - the zoom level increments are really large. Doing one CMD+ for me results in the text being huge, whereas by default the text is a bit too small. 

Why does font size not solve it? Because the UI elements like the explorer etc aren't affected by it. Making the zoom level adjustments more incremental would solve it.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
