### ISSUE TITLE
Tunnels: Add a Port... feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86064]
#85926

I do not like how we have the Add a Port... action inline in the view. This goes against our pattern in other views and does not bring values once you have configured your ports and just takes up space.
Instead of having it always inline I suggest the following as in the WATCH view:
* Add the context menu action in the view "Add a Port..."
* Double click in empty area adds the port
* Have some consistency between the hover on the action in the view title area and the title of this action. They are doing the same thing, why are they called `Add a Port...` and `Forward Port`. I suggest to pick one name and stick with it
* If you decide to stick with the Add A Port inline action it should also trigger on `Space` as all our other actions

**Comment by alexr00** [comment]
Good feedback, thank you!

**Comment by alexr00** [comment]
I agree with all of them except the `Space` trigger. In custom trees will only trigger on enter. Space in used only for expand/collapse.
