### ISSUE TITLE
Tunnels view: ux polish needed on presented data

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86066]
Refs: #85926

All the data is currently presented using the same font and with no special decorations which makes the text hard to process.
Since you are not an extension I believe you have full control of the rendering and due to that I think we should polish up how we present this data. Here are some suggestions:
* Instead of the word "to" use an arrow or some icon that would represent forwarding
* The port and the place where it is forwarded to should be in a monospace font
* Consider doing the background circle around the port number (since I believe that is the most important part of data)

As an inspiration I am attaching a screenshot of the callstack view which uses different fonts, rendering styles to make the data more readable.
These are just suggestions, I am open for any improvement in the way we present the data as long as it makes it more readable.

fyi @misolori 

![Screenshot 2019-12-03 at 14 28 59](https://user-images.githubusercontent.com/1926584/70055181-55375e80-15d9-11ea-89d0-026b49605328.png)

![Screenshot 2019-12-03 at 14 32 48](https://user-images.githubusercontent.com/1926584/70055458-dabb0e80-15d9-11ea-98b3-a429155f1372.png)

**Comment by alexr00** [comment]
Now with arrows:
![image](https://user-images.githubusercontent.com/38270282/72074184-b8f82a00-32f1-11ea-98bf-ffb112f023d6.png)

**Comment by isidorn** [comment]
I like the arrow, ux looks cleaner and easier to understand.

**Comment by alexr00** [comment]
Since the host+port aren't code I would prefer to leave them in non-monospaced font. I also think it would look a little uneven to have the port label be non-monospace on one line, and then the next line have a port without a name that is monospace. 

I am a big fan of the arrow though.
