### ISSUE TITLE
JSON limited to 5000 items

### ISSUE THREAD

**Issue by RobAndrewHurst** [microsoft/vscode#86060]
Issue Type: <b>Bug</b>

Hello. I am looking to increase the symbols limit on the JSON Language Features (Extension).

I work with massive JSON files for configurations and need to better understand what layer I am in the JSON. 

Please advise about how to remove the limit, or increase it.,

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.0.0-27-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.49GB (0.28GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
vsc-material-theme|Equ|30.0.0
composer-support-client|Hyp|0.19.12
vscode-docker|ms-|0.9.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.2
markdown-preview-enhanced|shd|0.5.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
duplicated of https://github.com/microsoft/vscode/issues/84259
