### ISSUE TITLE
Support onDidExecuteCommand

### ISSUE THREAD

**Issue by usere12** [microsoft/vscode#86068]
Hello,

I am working on VS Code extension. I am using webview for my extension and I am looking into way how I can listen and implement additional logic to VSCode commands like 'undo'/'redo'.

I found that there was already feature request for "onDidExecuteCommand" support - #1431
And according to that GitHub issue it was implemented and also merged to master, but then it was removed from master - https://github.com/microsoft/vscode/commit/21de711cdfb32d5798abbd60fc4ef92e640d23dd

Do you have plans to support "onDidExecuteCommand"?

**Comment by jrieken** [comment]
> Do you have plans to support "onDidExecuteCommand"?

Sorry, no. See this more explanation: https://github.com/microsoft/vscode/issues/78091#issuecomment-518545491
