### ISSUE TITLE
sync settings: resolve conflict complete button is too hidden

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86069]
Testing #85941

- have two machines that have settings sync
- open `keybinding.json` in both make a conflicting change
- conflict editor shows. Solve the conflicts
-  the 'resolve' checkmark is hard to find. Maybe use the blue button..

**Comment by sandy081** [comment]
<img width="1278" alt="Screenshot 2020-01-21 at 14 34 39" src="https://user-images.githubusercontent.com/10746682/72813742-2d24bd00-3c64-11ea-990f-9ce6a4eda118.png">
