### ISSUE TITLE
Tunnels view: keyboard shortcuts missing

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86065]
Refs #85926

Tunnels view, keyboard focus on a forwarded port.
Cmd + backspace on Mac and Delete on Win / Linux should delete the forwarded port.

Similarly if the Open in Browser is the only "positive" primary actions space and enter should open the port in browser.
F2 could rename the port also. On mac this might be what should happen on Enter.

**Comment by alexr00** [comment]
Added the rename and the delete as suggested.
I added Copy address with keyboard shortcut ctrl/cmd +c.

**Comment by alexr00** [comment]
To verify, try the rename, delete, and copy keyboard shortcuss in the forwarded ports view.

**Comment by isidorn** [comment]
Adding verified with the exception of https://github.com/microsoft/vscode-remote-release/issues/2221
