### ISSUE TITLE
sync settings: initial settings are lost when enabling `sync.keybindingsPerPlatform`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86077]
Testing #85941

- have a windows and a linux machines that have settings sync
- put different keybindings on both
- on the one machine add `  "sync.keybindingsPerPlatform": false` to the settings, change focus
- on the other machine the existing `keybindings.json` file is overwritten
-> should be a conflict

**Comment by gjsjohnmurray** [comment]
See also #86011
