### ISSUE TITLE
Terminal: Characters escape their background color

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86079]
Testing #85971

Notice the following WebGL screenshot of the [truecolor-test](https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern/404415#404415):

WebGL:

![image](https://user-images.githubusercontent.com/22350/70057549-a0ec0700-15dd-11ea-849f-8161f05be494.png)

Canvas:

![image](https://user-images.githubusercontent.com/22350/70057572-ac3f3280-15dd-11ea-8669-9994b096e060.png)

---

The characters are drawn outside the background color boxes.

**Comment by Tyriar** [comment]
Same root cause as https://github.com/microsoft/vscode/issues/86081

/duplicate
