### ISSUE TITLE
Terminal: Switching terminal background color doesn't react appropriately

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86072]
Testing #85971

1. Open a terminal
2. Select some text
3. Open settings and change `terminal.selectionBackground` through `workbench.colorCustomizations`

- When using `canvas`, it appears the entire selection is gone
- When using `experimentalWebgl`, selected text gets cheesy and the selection background color doesn't change:

![image](https://user-images.githubusercontent.com/22350/70056198-55385e00-15db-11ea-8ad9-64df3c1803ef.png)

**Comment by Tyriar** [comment]
@joaomoreno I think the canvas case is fine as opaque selections don't work, I was thinking about forcing opacity when using canvas/dom to help with this https://github.com/xtermjs/xterm.js/issues/2594

Upstream for webgl: https://github.com/xtermjs/xterm.js/issues/2595

**Comment by Tyriar** [comment]
The canvas thing you mention is an inconsistency, but I want to remove the canvas renderer soonish so it's not worth the effort to fix such an obscure bug.

**Comment by joaomoreno** [comment]
There are still rendering glitches which go away once I reselect: 
![recording (6)](https://user-images.githubusercontent.com/22350/80720662-8622ad80-8afd-11ea-8b40-778f1f94f93f.gif)

**Comment by Tyriar** [comment]
Yeah that was the original bug, I might not have updated xterm properly.

**Comment by Tyriar** [comment]
This is fixed, the selection disappearing for canvas only is tracked in https://github.com/xtermjs/xterm.js/issues/4057
