### ISSUE TITLE
Terminal: First row gets clipped at the top

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86073]
Related to https://github.com/microsoft/vscode/pull/84440, tested on Linux

Using `experimentalWebgl`, the very first row of my terminal is clipped by one pixel at the top. Notice the `i` dot:

![image](https://user-images.githubusercontent.com/22350/70056360-a21c3480-15db-11ea-9784-4760ec752b99.png)

Does not repro when using `canvas`.

**Comment by Tyriar** [comment]
This might be https://github.com/microsoft/vscode/issues/84432

**Comment by Tyriar** [comment]
Can you share font and related settings you have?

**Comment by connor4312** [comment]
This happens to me with both Fira Code and the default osx monospace font. Settings: https://gist.github.com/connor4312/1a810145da474e32edd593b6d3bc4cbe
