### ISSUE TITLE
C grammar pushes states and does not pop them for sqlite3.c

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8607]
Spin off from #7912

In #7912 I have fixed the crash and reduced the memory usage significantly.

But the C grammar is still broken IMHO.

From my logging, by the end of the file it has more than 50 pushed states that are not popped.

We need to investigate which rule in the C grammar causes this.

[sqlite3.zip](https://github.com/Microsoft/vscode/files/343199/sqlite3.zip)

**Comment by aeschli** [comment]
I created https://github.com/atom/language-c/issues/155 with a smaller example.
