### ISSUE TITLE
Tab completion until next delimiter

### ISSUE THREAD

**Issue by kbernard-fiveco** [microsoft/vscode#86075]
Wouldn’t it be interesting to have a feature "tab completion until next delimiter" ?

Let's take an example : 
In "settings.json", if you type "edi" and you toggle intellisense, it will propose : editor.acceptSuggestionOnCommitCharacter / editor.acceptSuggestionOnEnter / etc.
Actually I want to access "editor.minimap", so I have to manually complete "editor" and start typing "minimap" to finally have the results I want. 

If a "tab completion until next delimiter" was available, if you type "edi" and toggle intellisense, you could press a shortcut (e.g. ctrl + tab) to complete "editor.", then start typing "m" and complete "minimap." with the same shortcut. 

I took the example of a JSON file but I mainly code in C, where it is common to have more than 5 level of structures before reaching what you are actually searching for. What do you think?

**Comment by IllusionMH** [comment]
Just in case - these completions support fuzzy matching so you can type any part of properties in case you mention you can just type `mini` or `edmin` and you should see `editor.minimap...` suggestions on top

**Comment by kbernard-fiveco** [comment]
Hi, 

That's true that fuzzy matching can be used when you know what your are looking for. 

But if Intellisense is used to "explore" what is inside a imbricated Structure (in C) or Class, and you do not know the name of what you are looking for, the fuzzy matching will not be very usefull.

Actually, if I am not mistaken, this what Eclips does, it only propose suggestion until the next structure/class member operator ".", then you can "Tab complete it" and explore the next level of struct/class member. 

I did my example with C/C++, but I think this can be applied to other languages as well.

What do you think ?
