### ISSUE TITLE
Tunnels view: rename feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86070]
Refs: https://github.com/microsoft/vscode/issues/85926

1. When a port has no name I find it a bit weird that the action is called Rename. Maybe it shuold be `Set Label` or something like that.
2. Once I give it a name, triggering Rename should select the whole old name (to make it easier for the user to delete the old name - we do this in Explorer).

Also Rename is a bit vague. Does Rename change the port or the label. Due to that I might be leaning more towards `Set Label` always.

Also why do we have it Port Name in the UX. Why not Port Label?

**Comment by alexr00** [comment]
"Port Name" is a holdover from SSH, where they call it a "name". Label makes sense to me. I've also gotten feedback though that it should be "Rename" to match how explorer works. I'm leaning more towards always having "Set Label" as it is the clearest to me.

**Comment by JacksonKearl** [comment]
I also thought the rename was going to change the port being forwarded. "Set Label" would make more sense to me.

**Comment by isidorn** [comment]
Works great now, nice work 👏
