### ISSUE TITLE
Sync: Have an option to copy the Sign In link

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86083]
Testing #85944

In my weird setup, Code can't really open links in the system browser. When I chose `Sync: Turn On`, a popup came up asking me to sign in. I clicked `Sign In`, the browser failed to open. The opener service should be used here, which will give the user the chance to copy the link instead.

**Comment by sandy081** [comment]
Auth related, assigning to @RMacfarlane

**Comment by TylerLeonhardt** [comment]
> The opener service should be used here, which will give the user the chance to copy the link instead.

@joaomoreno this is an oldie but we use vscode.env.openExternal so I would think that this "just woks"...

**Comment by joaomoreno** [comment]
Yeah just feel free to close this. It's not a real-world issue.
