### ISSUE TITLE
Sync: Turning Sync back on asks for what to sync again

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86089]
Testing #85944

Should we really ask the user again what they want to sync, once they re-enable sync?

![image](https://user-images.githubusercontent.com/22350/70060709-54a3c580-15e3-11ea-9771-58e1469faa27.png)

**Comment by Tyriar** [comment]
I think we should keep this, turning off should happen very infrequently and one of the valid reasons for this could be to reconfigure what is synced for users less familiar with settings.

**Comment by sandy081** [comment]
I know it is not frequent action, but is not annoying for the user if we show it always and user knows about it? 

Anyway moving this discussion to https://github.com/microsoft/vscode/issues/85216

**Comment by joaomoreno** [comment]
Why not a command `Sync: Configure`?
