### ISSUE TITLE
Unhappy "Run Java" experience

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86086]
re https://github.com/microsoft/vscode/issues/85774

* open java-12 dev container
* rename .vscode folder to .vscode-off
* open debug viewlet, select "Run with Java"
* 🐛 no run... there is a progress message about generating configuration and a launch.json file is shown but that is all...

**Comment by isidorn** [comment]
This is up to the Java extension, they can handle the No Workspace Run however the extension wants. Due to that I have moved this issue to the java repository https://github.com/microsoft/vscode-java-debug/issues/724
