### ISSUE TITLE
About vscode Integration

### ISSUE THREAD

**Issue by Luncher** [Microsoft/vscode#8608]
Ask a question, I want to integrate my vscode inside an application , how can I do it ?

**Comment by bpasero** [comment]
@Luncher can you be more specific?

**Comment by Luncher** [comment]
@bpasero 

Thank you for your reply!  
I have an application using the electron. I want to vscode integrated in, how do I do it? I want vscode as an editor of my application. You can give me some advice?

**Comment by bpasero** [comment]
I suggest you start here: https://github.com/Microsoft/monaco-editor
