### ISSUE TITLE
Sync: Review UX behind turning on/off

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86082]
Testing https://github.com/microsoft/vscode/issues/85944

I already raised this concern before, let's just have it in an issue:

I believe that allowing the user to turn Sync on/off is an anti-pattern. Just like Edge or my Android phone, sync just works, without me enabling/disabling it.

The current approach also has ambiguous command labels like `Sync: Turn On`... like what does this mean? If I didn't know what I was testing I would even think this came from an extension.

**Comment by joaomoreno** [comment]
Also minor: the sign out command is simply `Sign Out`, it should be `Sync: Sign Out`.

**Comment by joaomoreno** [comment]
Also: should it really be a global notification (in the gear icon) that you're not signed in? That's another reason to drop the whole user controlled toggle.

**Comment by sandy081** [comment]
There are also other tools like Chrome which provide this toggling option. I assume that context is shown from the global menu where it shows all user configuration data and we also show a dialog after turning on explaining user what is getting synced.

Sign out command is temporary but will add Sync prefix.

> Also: should it really be a global notification (in the gear icon) that you're not signed in?

I think so it is. Again same reasoning as above.

Again moving this to https://github.com/microsoft/vscode/issues/85216
