### ISSUE TITLE
Token theming: Last rule wins?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#86095]
Testing #85972

With the rules:
```
		"*.async": {
			"fontStyle": "bold italic"
		},
		"*.declaration": {
			"fontStyle": "-bold -italic"
		},
```

It appears the last one wins except when changing the order of the two rules.

![Dec-03-2019 16-10-07](https://user-images.githubusercontent.com/9205389/70063012-68512b00-15e7-11ea-810b-d225c2d0f724.gif)

**Comment by aeschli** [comment]
Yes, the last rule should win if two rules are equally strong.

The issue that you see has to do that we rely on the property order.
The configuration service does not send a change event if all that changes is the property order.
Using the property order is a bit of a gray area, so I suggest we leave things as they are and live with the issue.
