### ISSUE TITLE
Sync: Improve sync output

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86090]
Testing https://github.com/microsoft/vscode/issues/85944

I'd like to see the following data when looking into the sync log:

- Duration of each sync operation
- Amount of settings/keybindings/snippets synced each call

![image](https://user-images.githubusercontent.com/22350/70060794-7a30cf00-15e3-11ea-93eb-d9027957e973.png)

**Comment by joaomoreno** [comment]
Also typo:

```
Updating last synchronised sttings
```

**Comment by sandy081** [comment]
> Amount of settings/keybindings/snippets synced each call

Do you mean the size of file or number of entries?

**Comment by joaomoreno** [comment]
Number of entries :+1:

**Comment by sandy081** [comment]
Added logs for the time to sync. But cannot log number of entries as I am syncing file content.
