### ISSUE TITLE
Sync: Theme failed to apply

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86097]
Testing https://github.com/microsoft/vscode/issues/85944

Due to https://github.com/microsoft/vscode/issues/86096, my settings were synced first and only then my extensions. Once everything was synced, my theme still did not apply. I had to reload the window to have it applied.

**Comment by sandy081** [comment]
I do not think order matters here. Theme should be applied even if the extension gets installed after. Will investigate.

**Comment by sandy081** [comment]
/duplicate

#88364
