### ISSUE TITLE
Previously opened tabs are lost when opening code through the file explorer -> right click file -> open with code

### ISSUE THREAD

**Issue by DutchBlackOp** [microsoft/vscode#86092]
1. I close Visual studio code while there are saved tabs open in code.
2. I open the file explorer and select a file.
3. Right click the file and select "open with code"
4. The saved tabs that were open in visual studio code are not there. (only the new file is visible)
4(expected). The saved tabs are open and the new file is open in visual studio code.

**Comment by isidorn** [comment]
@DutchBlackOp Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by DutchBlackOp** [comment]
Hello Isidorn,

I am able to reproduce the same error in the Visual Studio Code Insiders application.
