### ISSUE TITLE
isWatching confusion

### ISSUE THREAD

**Issue by jbondc** [Microsoft/vscode#861]
Started to use vscode for a new project but confused about `isWatching` and what it does.

Here's the `tasks.json` config I'm currently using:
![capture](https://cloud.githubusercontent.com/assets/199519/11501300/0eb1bda2-9801-11e5-811b-a4e4a34c6f11.PNG)

Initially started with:

```
        {
            "taskName": "watch",
            "isWatching": true,
            "args": ["--watch", "compiler/types.ts", "compiler/scanner.ts'],
            "problemMatcher": "$tsc"
        },
```

But then I try to run `watch` then `build-test`, the IDE complains that a task is running. 

Can someone explain the magic with `"problemMatcher": "$tsc-watch"` ?
https://github.com/Microsoft/vscode/blob/f0dfc2374892759438a856dfb0bb748fa5f1ae0b/src/vs/workbench/parts/tasks/node/processRunnerSystem.ts#L267

And how file watching works? 
https://github.com/Microsoft/vscode-filewatcher-windows/tree/master/FileWatcher

Intuitively, would seem simpler if there were two modes of file watching `"external" | "managed"`

``` :
        {
            "taskName": "watch-external",
            "isWatching": "external",
            "args": ["--watch", "compiler/types.ts", "compiler/scanner.ts'],
            "problemMatcher": "$tsc"
        },
        {
            "taskName": "watch-managed",
            "isWatching": "managed", // uses IDE file watching
            "problemMatcher": "$tsc"
        },
```

**Comment by Ciantic** [comment]
This is still confusing, isn't there a way to watch and still run other tasks? Ideally one should be allowed to run multiple watches like css preprocessors less, ts, and still run tests manually.

Additionally instead of having watcher, it would be a better if one could trigger a task when certain filetype changes, e.g. I don't need to watch for less if I could just trigger less task when *.less changes. (There are plugins for this, but this should be part of tasks.json)

**Comment by dbaeumer** [comment]
Currently there is only support to run one task at a time. Being able to run multiple tasks in parallel is on the backlog.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/981

**Comment by dbaeumer** [comment]
[Addressed in new terminal runner]

The new runner support running multiple commands in parallel all of which can be background tasks.

**Comment by dbaeumer** [comment]
Closing. Task 2.0.0 can run multiple tasks in parallel.
