### ISSUE TITLE
ssh - only able to open one file at a time

### ISSUE THREAD

**Issue by noeltdolan** [microsoft/vscode#86104]
- VSCode Version: 1.40.1
- OS Version: Mac Mojave and Windows 10 

Steps to Reproduce:

1. Connect to remote server via ssh 
2. Navigate to first file
3. Open.
4. Navigate to second file
5. Open
6. Result first file closes.

Works correctly on version 1.38.1  using remote ssh extension.

**Comment by roblourens** [comment]
Sounds like you are seeing the files open in "preview" editors. If you don't like that behavior, you can disable `workbench.editor.enablePreview`

**Comment by noeltdolan** [comment]
Yes, that seems to have 'fixed' it though why would it default to that behaviour in the first place? :/

**Comment by roblourens** [comment]
Many people don't like having a cluttered tab bar with files that they opened once but aren't really working on. Depends on the project/workflow I think.
