### ISSUE TITLE
Compact folder: Shift + F12 changes the selection

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86106]
Testing #85928

Ubuntu and Windows with WSL

- clone https://github.com/eclipse/eclipse.jdt.ui.git
- set "explorer.compactFolders": true
- use the keyboard to navigate to `org.eclipse.jdt.junit/src` (underline shows)
- Shift + F12 to show the context menu. Note that the underline is now at `org.eclipse.jdt.junit/src/org/eclipse/jdt`

**Comment by isidorn** [comment]
I can reproduce this. Assigning to December to look into it then.
