### ISSUE TITLE
Command (and other callback) exceptions should be reported to the debug console

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#86109]
When exception happens during command execution, nothing is printed anywhere, and it's pretty hard to understand what's going on. 

What do you think about catching exceptions on the extension/vscode boundary, and reporting them into the console? If you are ok, then would you be open to accepting PRs adding such reporting?

**Comment by jrieken** [comment]
It depends ;-) The `extHostCommands` logic doesn't catch/handle error but relies on the caller to handle them correctly. I think that's a good approach because error handling often differs from caller to caller. So, it depends what are trying and where are seeing error going unnoticed?

**Comment by solomatov** [comment]
@jrieken Commands is likely a bad example. I want to make exceptions in callback code more visible, i.e. if some exception happens, I want to see it in the vscode debug console, and be able to navigate to the source files there.

**Comment by bpasero** [comment]
@solomatov does this work now given https://github.com/microsoft/vscode/pull/86617 is merged?

**Comment by solomatov** [comment]
@bpasero I just tried, it worked perfectly. Many thanks for your help!
