### ISSUE TITLE
Compact folders: Context menu actions not selection aware

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86103]
Testing #85928

- open a remote WSL window
- clone https://github.com/eclipse/eclipse.jdt.ui.git
- set `"explorer.compactFolders": true`
- in the explorer, move the mouse over `org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/` (underline appears) and pick `Copy Relative Path` from the context menu

The path copied is `org.eclipse.jdt.junit.runtime/src/org/eclipse/jdt/internal/junit/runner`

Same with other context menu command: Open in Terminal, Find in Folder..., New File...
Rename & Copy seem to work.

**Comment by aeschli** [comment]
Works when using keyboard and Shift + F10

**Comment by isidorn** [comment]
Good catch. Debt follow up work https://github.com/microsoft/vscode/issues/86268

Verifier have the compact folders in the explorer and verify all context menu actions work on the expected context (if you click on the middle item it will execute on it).

**Comment by aeschli** [comment]
`Open Terminal` still opens on the wrong folder. Created https://github.com/microsoft/vscode/issues/86408

**Comment by aeschli** [comment]
Oh, it's much more. It depends om where the selection is (not just the focus).

- open a remote WSL window
- clone https://github.com/eclipse/eclipse.jdt.ui.git
- set "explorer.compactFolders": true
- in the explorer, set the selection on  `org.eclipse.jdt.junit.runtime - src -org\eclipse\jdt\internal\junit\runner`
- Move the mouse over `jdt`, opemn context meny and `Copy Relative Path'
Paste:
org.eclipse.jdt.junit.runtime\src
org.eclipse.jdt.junit.runtime\src\org
org.eclipse.jdt.junit.runtime\src\org\eclipse
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt\internal
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt\internal\junit
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt\internal\junit\runner

**Comment by aeschli** [comment]
If the selection is somewhere else, things work. Marking as verified.
