### ISSUE TITLE
Electron 7: out of source debugging - source maps not discovered

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86108]
Refs: https://github.com/microsoft/vscode/issues/85994

macOS

1. `scripts/code.sh`
2. F1 > developer tools > set a breakpoint
3. There are no `.ts` files, only javascript files even though I have source maps enabled in the chrome dev tools configuration 

This works fine when I run with the previous Electron.

**Comment by deepak1556** [comment]
https://github.com/electron/electron/pull/21473

**Comment by bpasero** [comment]
Seems fine now.
