### ISSUE TITLE
Go to References with a single reference could cause confusion

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86116]
Testing https://github.com/microsoft/vscode/issues/85925

It's strange when there is only a single reference that nothing happens except for (maybe) moving the cursor to the start of the symbol:

<img width="108" alt="Screen Shot 2019-12-03 at 9 14 46 AM" src="https://user-images.githubusercontent.com/2193314/70073287-6b2f2a00-15ad-11ea-9290-8a9ec00e9bcf.png">

shift+f12

<img width="102" alt="Screen Shot 2019-12-03 at 9 15 12 AM" src="https://user-images.githubusercontent.com/2193314/70073297-6f5b4780-15ad-11ea-9919-a8ba4155a1ad.png">

Either showing the peek view always here or showing the little popup saying there's only a single reference like the below message would prevent confusion:

<img width="220" alt="Screen Shot 2019-12-03 at 9 17 46 AM" src="https://user-images.githubusercontent.com/2193314/70073448-c9f4a380-15ad-11ea-8af5-b5012f90f0e3.png">

**Comment by jrieken** [comment]
I'd say that's mostly https://github.com/microsoft/vscode/issues/84553#issuecomment-561438782 and the lack of a good reveal color. What happens (and that works with at the default light theme) is that the current position is highlighted for a (very) short while and that should you a better understanding of what's going on. Let's see how well that works once we have a better color.

**Comment by Tyriar** [comment]
👍 looks pretty good after setting `editor.symbolHighlightBorder`

**Comment by jrieken** [comment]
Ok - then closing in favour of the polish for #84553
