### ISSUE TITLE
[Bug]Terminal: garbage characters on scroll after running child_process

### ISSUE THREAD

**Issue by pranshuchittora** [microsoft/vscode#86117]
**Description**
Demo Video => [https://youtu.be/HXlDxt4kaMo](https://youtu.be/HXlDxt4kaMo)
I know this is a crazy scenario, but it must be resolved. I ran a node process which include a child_process in the code's terminal instance. After running I saw some weird characters on scrolling.

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-23-generic
```
Steps to Reproduce:
(Install [htop](https://hisham.hm/htop/) if you don't have)
1. Create a new `.js` file
2. Paster this code.
```
const { spawn } = require("child_process");
const child = spawn("htop", []);
child.on("exit", code => {
  console.log(`Child process exited with code ${code}`);
});
child.stdout.on("data", data => {
  console.log(`stdout: ${data}`);
});
child.stderr.on("data", data => {
  console.log(`stderr: ${data}`);
});

```
3. Run the file with `node`
4. Exit the htop instance
5. Try scrolling

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

**Comment by Tyriar** [comment]
How did you run that node file, a task? This state specifically?

![image](https://user-images.githubusercontent.com/2193314/70161578-22d94000-1671-11ea-86af-160fd32370e6.png)

**Comment by pranshuchittora** [comment]
> How did you run that node file, a task? This state specifically?
> 
> ![image](https://user-images.githubusercontent.com/2193314/70161578-22d94000-1671-11ea-86af-160fd32370e6.png)

Using [Code Runner ](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)

But that's not the cause of the error, because I tried the same by running vscode with node extension flag. And ran the code manually in the integrated terminal by running `node {path to file}`.
Output is same :(

**Comment by Tyriar** [comment]
There's a feature where if you're in the alt buffer (ie. there is no scroll bar, vim, htop, etc.) then scrolling the mouse wheel will translate to up/down arrow events such that the mouse wheel will scroll the cursor in vim. Does pressing up and down produce the same characters?

**Comment by pranshuchittora** [comment]
If I run `htop` in the integrated terminal directly then everything works perfectly. But when I ran the nodejs instance which includes `child_process` then scrolling doesn't work and even after exiting the process scrolling generates weird characters, hence I am not able to scroll up/down.
I think there's some sort of mem leak.

**Comment by Tyriar** [comment]
Oh this is because it's a child process not a pty, I don't think you're meant to be able to do this.

@jerch can you confirm?

**Comment by jerch** [comment]
@Tyriar Yes, most interactive programs will not work correctly without a tty/pty in between. Some even check for that and refuse to work, others might work but behave much different (e.g. bash knows a pipe through mode).
