### ISSUE TITLE
Viewlet flicker when launch fails

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86112]
re https://github.com/microsoft/vscode/issues/85774

* use node-12 dev container
* "forget" to run `npm i`
* press "Run with Node.js"
* the viewlet immediately changes to complex mode and then quickly changes back because launching failed
* I'd say it would be better to wait until launching was successful

![Dec-03-2019 17-29-58](https://user-images.githubusercontent.com/1794099/70069903-dc450080-15f2-11ea-86e2-88c429515f71.gif)

**Comment by isidorn** [comment]
Yeah, agree. We should still show the simple view while in initatialising phase.
