### ISSUE TITLE
Opening search results in editor should not create duplicate tabs if results are unchanged

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#86118]
Testing #85965

1. Create a search result
2. Click "open results in editor"
3. Click "open results in editor" again
4. 🐛 The same results keep opening in a new tab
![image](https://user-images.githubusercontent.com/35271042/70073469-d416a200-15ad-11ea-9c8f-7c347e6d6374.png)

Similar to the builtin Markdown preview extension, we should not duplicate the results in a new tab if they are the same results. If I am on a different tab, I would expect the focus to go to the last tab that has the results.

**Comment by RMacfarlane** [comment]
I'm still seeing this happen on the latest insiders on Windows

```
Version: 1.41.0-insider (user setup)
Commit: bbf00d8ea6aa7e825ca3393364d746fe401d3299
Date: 2019-12-05T05:38:12.288Z
OS: Windows_NT ia32 10.0.18363
