### ISSUE TITLE
Editor inherits Abyss theme in find widget

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8612]
![image](https://cloud.githubusercontent.com/assets/900690/16519185/6f26f28c-3f87-11e6-95a6-e59f113cfcd9.png)

**Comment by alexandrudima** [comment]
@aeschli - it is caused by this generated CSS style:
```
.monaco-editor.vs-dark.vscode-theme-abyss-themes-Abyss-tmTheme {
    color: rgba(102, 136, 204, 1);
}
```

Perhaps the intent is to use `.token` in there?

**Comment by alexandrudima** [comment]
Even better:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/themeService.ts#L365
```ts
	if (editorSettings.foreground) {
		let foreground = new Color(editorSettings.foreground);
		cssRules.push(`.monaco-editor.${themeSelector} { color: ${foreground}; }`);
		cssRules.push(`.monaco-editor.${themeSelector} .token { color: ${foreground}; }`);
	}
```
