### ISSUE TITLE
Call hierarchy duplicate entries 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#86123]
testing #85924 

- VSCode Version: 1.41.0-insider (9785578)
- OS Version: macOS Mojave

Steps to Reproduce:

1. https://github.com/jrieken/demo-callhierarchy
2. open sample/test.abc
3. show or peek call hierarchy

![image](https://user-images.githubusercontent.com/8586769/70074634-f27d9d00-15af-11ea-8c2f-939d805a6c88.png)

Not sure if this is from the extension or what but definitely unexpected.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
I'd say that's my dummy extension... I will take a look but you can double check with the other (better) sample that we have

**Comment by JacksonKearl** [comment]
Yes its fine in the other extension. Fine to close unless there's something odd there.

**Comment by jrieken** [comment]
yeah - closing. I already invested too much in my abc-lang
