### ISSUE TITLE
Search results does not persist on reload when search input has text

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#86129]
Testing #85953

1. Enter a search term
2. Enter a "files to include"
3. Reload editor, results persist
  <img width="50%" src="https://user-images.githubusercontent.com/35271042/70075882-7cc70080-15b2-11ea-814a-5df4be8d876c.png">

4. Remove "filest to include" param, reload editor
5. 🐛 Results do not persist
  <img width="50%" src="https://user-images.githubusercontent.com/35271042/70075766-47221780-15b2-11ea-9c44-614b5bc50f72.png">

Since we persist results on other param changes I'd expect the same to be true when any text is in the search input

**Comment by roblourens** [comment]
I assume this is due to triggering the search again after the window reloads. @JacksonKearl please don't trigger search automatically when the window reloads, it will lead to slower startup or complaints about CPU use on startup.
