### ISSUE TITLE
Web UI: application menu is empty

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86120]
While testing https://github.com/microsoft/vscode/issues/85988:

The application menu is empty in Chrome:

![2019-12-03_18-20-58](https://user-images.githubusercontent.com/1898161/70073716-b1aa7600-15f9-11ea-81a7-820c02281f81.png)

It works fine in Firefox

**Comment by sbatten** [comment]
please try tomorrow, it is likely being drawn underneath the activity bar and hopefully fixed with fix from today.

**Comment by weinand** [comment]
Works fine now in latest.
