### ISSUE TITLE
nonintuitive iconage in call heiarchy

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#86125]
testing #85924

![image](https://user-images.githubusercontent.com/8586769/70074864-759ef300-15b0-11ea-8872-6c4c966793bc.png)

The "refresh" icon on the tree items makes me think it will reload the results of that node, especially as we use the icon to do the same in the top acton bar. I think using the "Show incoming/outgoing calls" icon would make more sense.

**Comment by jrieken** [comment]
@misolori Do you have a suggestion? I was considering the "phone handle icon" that we use to toggle the call hierarchy direction.

**Comment by misolori** [comment]
@jrieken using the same icon makes sense here. Related: the current phone handle icon looks out of place with the old style, I can re-create it to match our new style.

**Comment by jrieken** [comment]
Yes, please a new icon. I took it from the VS set but something more modern is very much appreciated.

**Comment by jrieken** [comment]
Catch 22 - the icon atop always shows the other direction, e.g when in "caller of" mode the icons shows the "call from" mode to switch to that mode but the inline command should be always be the current mode. that means the icons are always different...

<img width="402" alt="Screenshot 2019-12-04 at 11 15 40" src="https://user-images.githubusercontent.com/1794099/70133986-735b9800-1687-11ea-82a6-7950a54e7f65.png">

**Comment by JacksonKearl** [comment]
I think the difference is subtle enough that it users will understand the connection and it wont be particularly jarring. @misolori?

**Comment by misolori** [comment]
I think our advanced users will pickup on the subtlety but the average might not. I still think it works better than the refresh icon.

**Comment by eamodio** [comment]
Related to this -- I expected to be able to right-click on an item in the hierarchy view and get to the _Show Call Hierarchy_ action

**Comment by misolori** [comment]
Icon design being handled by https://github.com/microsoft/vscode/issues/86305

**Comment by jrieken** [comment]
<img width="437" alt="Screenshot 2019-12-05 at 10 48 15" src="https://user-images.githubusercontent.com/1794099/70223992-c3506280-174c-11ea-9b50-b52be51c6b28.png">
