### ISSUE TITLE
Breakpoints show up as white in Firefox

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86126]
testing https://github.com/microsoft/vscode/issues/85988:

When debugging in the Web UI on Firefox breakpoints are white and misaligned:

![2019-12-03_18-41-06](https://user-images.githubusercontent.com/1898161/70075300-cb00f180-15fc-11ea-97e9-684d85f7a2f3.png)

In Chrome they look ok:

![2019-12-03_18-39-52](https://user-images.githubusercontent.com/1898161/70075321-d5bb8680-15fc-11ea-9fb9-bf93829a19e9.png)

**Comment by isidorn** [comment]
@misolori can you look into this? I can also help so just ping.

**Comment by misolori** [comment]
@isidorn yea I'll take a look at this

**Comment by weinand** [comment]
Looks good now:
![2019-12-05_11-09-21](https://user-images.githubusercontent.com/1898161/70225650-b97c2e80-174f-11ea-93bf-cc0500fd1874.png)
