### ISSUE TITLE
Extra quote is added when completing settings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86121]
Testing https://github.com/microsoft/vscode/issues/85925

I have this set:

```
"editor.autoClosingQuotes": "beforeWhitespace"
```

In settings with the following state:

<img width="62" alt="Screen Shot 2019-12-03 at 9 19 26 AM" src="https://user-images.githubusercontent.com/2193314/70073592-0de7a880-15ae-11ea-8d8e-7b659a445616.png">

Type "go" and trigger intellisense:

<img width="161" alt="Screen Shot 2019-12-03 at 9 19 36 AM" src="https://user-images.githubusercontent.com/2193314/70073594-104a0280-15ae-11ea-9219-4358dd870060.png">

Press tab will insert an extra `"` at the end:

<img width="115" alt="Screen Shot 2019-12-03 at 9 19 44 AM" src="https://user-images.githubusercontent.com/2193314/70073601-117b2f80-15ae-11ea-8095-84e353c48b40.png">

To make matters worse, pressing backspace it will remove both:

<img width="101" alt="Screen Shot 2019-12-03 at 9 21 07 AM" src="https://user-images.githubusercontent.com/2193314/70073726-45eeeb80-15ae-11ea-9708-e44b5b1229c0.png">

**Comment by Tyriar** [comment]
Consider fixing for November, think it's a regression

**Comment by gjsjohnmurray** [comment]
Maybe related to #86078?

**Comment by Tyriar** [comment]
Yep

/duplicate
