### ISSUE TITLE
Include link to clear filters in problems view empty message

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#86135]
Issue Type: <b>Bug</b>

From #85943

**Repo**
1. Create a few problems
1. In the problems view, filter them all out

**Feature request**
<img width="499" alt="Screen Shot 2019-12-03 at 10 32 21 AM" src="https://user-images.githubusercontent.com/12821956/70078813-47bdac80-15b8-11ea-9531-19c17b3d3d2d.png">

In the problems view, we show `no results found ...`

I suggest that we also show some additional information here, such as a clickable link that clears the filters or the total problem count.

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:35:54.992Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.05GB free)|
|Process Argv|-psn_0_7812979|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
`Clear Filters` link used to be there and removed it. So bringing it back.
