### ISSUE TITLE
Atom Java Script Grammar doesn't work  with the Oceanic - Next theme

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8613]
See https://github.com/Microsoft/vscode/issues/8204#issuecomment-229202771

The theme used is: 
![image](https://cloud.githubusercontent.com/assets/172399/16519297/2c196104-3f88-11e6-9527-ce3f14b7b4ec.png)

![image](https://cloud.githubusercontent.com/assets/172399/16519285/1782285c-3f88-11e6-8828-0c5704605316.png)

**Comment by aeschli** [comment]
The oceanic theme defines a rule for scope 'meta.function-call' which matches to everything in a function call due to https://github.com/Microsoft/vscode/issues/3008

Closing as dup of #3008
