### ISSUE TITLE
Menu system crashes when run on Linux Mint inside of VirtualBox

### ISSUE THREAD

**Issue by zelko-ring** [microsoft/vscode#86138]
Issue Type: <b>Bug</b>

Hello,

I like VSCode, but now I've got a problem with it.

I'm running VSCode on:
- Linux Mint 19.2 Cinnamon 64-bit
- ...which is running inside of VirtualBox 6.0.14 r133895
- ...which is running in Windows 10 (version 1809; build 17763.864)

Problem: From time to time entire VM crashes with an error that looks like so: 
"The instruction at 0x000(some addr) referenced memory at 0x00000000000000."

The second address is always all zeros.

This only happens when popup windows appear in VSCode. Whether code completion popup or the main menu bar (for example, the File menu). It has to happen a few times and then it crashes.

The popup windows usually looks weird, just a black box without any text or graphics inside. As if there's some problem with the popup window subsystem. But sometimes the windows look normal, and everything works fine. So this is not an easily predictable error (that would be way too simple, right?)

While I was running VSCode on native Ubuntu and without VirtualBox I've never seen this error. Maybe it's related to VBox being too sensitive to exceptions. Or maybe it's related to the graphics adapter. The one inside of VBox is the default VMSVGA with (non-default) 128 MB RAM. I gave it maximum RAM size hoping that would solve the problem, but it didn't.

That's all.

Cheers!
Zelko

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (1 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.79GB (5.13GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.11.50794

</details>

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/84745

Please use the following workaround

```
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
```

**Comment by zelko-ring** [comment]
That helped. Thank you very much!
