### ISSUE TITLE
[html] auto rename doesn't exit when deleting at the end of a tag

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86149]
Testing #85973

```
<html>
    <foo class=this>

    </foo>
</html>
```

* put cursor at the end of `/foo` of line 4
* press Delete (delete the right side character)
* keep deleting
* auto rename mode doesn't exit

**Comment by octref** [comment]
This is a really niche case...In this case there's no `onSelectionChange` event since your cursors didn't move. I think it's ok to leave it as it is.
