### ISSUE TITLE
Problems view filter input should prioritize showing problem count when the input becomes narrow

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#86143]
Issue Type: <b>Feature Request</b>

For #85943

**Repo**
1. Move the panel to the right.
1. Create a few problems in a file, for example:

```ts
const xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 1;

const xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 2 %;
```

3. In the problems view, type in some long seach text (`xxxxxxxxxxxxxxxxxxxxxx` for the example above). This should show the total problems filter in the problems filter box
4. Now make the problems panel very narrow

**Bug**
The problems count is collapsed as the panel gets narrow

![Dec-03-2019 11-06-34](https://user-images.githubusercontent.com/12821956/70081454-6ecaad00-15bd-11ea-939f-ec04c7adfa7a.gif)

I think we should prioritize showing this information over the long filter text itself, as the total issue count is important 

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:35:54.992Z)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
This is the case even now and I have not got any issues for this and its been there for long time. Hence closing as out of scope.
