### ISSUE TITLE
Not able to install extension with multiple kinds to other location

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#86153]
Issue Type: <b>Bug</b>
Testing  #85948

Related https://github.com/microsoft/vscode/issues/86152

1. Connect to a remote using WSL, containers, or SSH
2. Search for the test extension "sandy081.workspace-ui-extension" and install it on the remote
3. Reload window and go to extension viewlet again

Expected:
Button to install the extension locally to be available

Actual:
No option is given

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:35:54.992Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1025-azure

**Comment by sandy081** [comment]
It is primarily workspace extension and why is it expected to have an action given that install does not have any affect.
