### ISSUE TITLE
[html] no suggestion for closing tag

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86159]
Testing #85973

```
<html>
    <foo>

    </foo>
</html>
```

* put cursor in the middle of `foo` of line 2
* trigger suggest, get suggestions like `footer`
* press arrow down
* trigger suggest again, get nothing

**Comment by octref** [comment]
This is as-designed. From testing description:

> Test that tag auto-completion works. For example, try setting cursors in <div|></div|>, delete the div and enter d to complete div. (This will only work when primary cursor is in the beginning <div> and mirrored cursor in the ending one, not the other way around).

You do not have an open `<footer>`, so there's no auto-completion for closing `</footer>`.
