### ISSUE TITLE
[html] auto rename doesn't exit when move cursor the end of line

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86151]
Testing #85973

```
<html>
    <foo>

    </foo>
</html>
```

* put cursor at the beginning of `foo` of line 2
* press cmd+right
* auto rename mode doesn't exit, there is still a secondary cursor on line 4

**Comment by rebornix** [comment]
Another case

![cursorend](https://user-images.githubusercontent.com/876920/70085072-688bff00-15c4-11ea-8022-1d4dfa05e2d2.gif)

```
<html>
    <foo>
    </foo>
</html>
```

* Move cursor into `foo` of line 2
* Move cursor to the end, there are two cursors
* Move down, the cursors go into the tag

**Comment by octref** [comment]
Initially I thought this would be nice for line-wise selection, especially if you do cmd+left/right, so I intentionally allowed this case.

Should we remove it?

For your second one:
- When you move, two cursor became one
- The first cursor went to `</foo>`, producing another cursor

So I'd say its behavior is fine

**Comment by rebornix** [comment]
> Initially I thought this would be nice for line-wise selection, especially if you do cmd+left/right, so I intentionally allowed this case.

For line wise selection, I would expect it to work when I create multiple cursor myself.

**Comment by octref** [comment]
Verifier:

Have below HTML code (you can surround them with other HTML elements):

```html
  <div>
  </div>
```

Put cursor inside `div` so mirror cursor occurs, and then move your cursor before `<` or after `>`. Make sure the 2 cursor become 1 when cursor is not on `div` anymore. Free free to jump around using Option/Cmd + arrow keys.
