### ISSUE TITLE
[Contributing] How do I format code for PRs to this repo?  Tried running the Format Document command with tsfmt, hygiene still complains

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#86155]
My first problem was that I have the prettier extension installed and it was formatting by default.  But I also tried installing the `tsfmt` extension and doing Format Document With... tsfmt, and hygiene *still* isn't happy.  The error message isn't very helpful:

```
File not formatted. Run the 'Format Document' command to fix it: src/vs/base/test/common/decorators.test.ts
```

* For one this doesn't provide guidance on *which formatter* to use with `Format Document`.
* It also doesn't give me any hints about what's formatted wrong so I can just fix it manually

Only running `tsfmt -r src/vs/base/test/common/decorators.test.ts` on the commandline fixed this.  Can we document how to properly configure my VSCode workspace for this?

Most projects have a package script users can run to format everything, that would be more helpful than just saying to run the Format Document command.

**Comment by jedwards1211** [comment]
Not a duplicate

**Comment by jrieken** [comment]
F1 > Format Document

**Comment by jedwards1211** [comment]
@jrieken please read my OP.  Although the instructions in the error say to use the "Format Document" command, that only works if the right formatter is configured, and even after I installed tsfmt it didn't seem to be configured right.  Could we please reopen this until it's documented in more detail?
