### ISSUE TITLE
[Contributing] How do I whitelist sinon for a new test case for a PR?

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#86157]
I need `sinon.useFakeTimers` in a new test for a PR I'm making but the precommit hook doesn't allow it:

```
src/vs/base/test/common/decorators.test.ts:6:1:Imports violates 'assert or vs/nls or **/vs/base/common/** or **/vs/base/test/common/**' restrictions. See https://github.com/Microsoft/vscode/wiki/Code-Organization
```

I don't see where I would tell it that importing from `sinon` in the tests is okay, and I'm wondering if there's any reason you don't want me to use Sinon in these tests?

**Comment by sandy081** [comment]
Allowed sinon in all test packages

**Comment by jedwards1211** [comment]
Thanks!
