### ISSUE TITLE
[Contributing] repo probably shouldn't have both .prettierrc.json and tsfmt.json

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#86150]
Because it has `.prettierrc.json` and I had the prettier extension installed and active, when I save any files within this repo, it formats them with prettier.  The precommit hooks then complain that the file is formatted improperly.

**Comment by jedwards1211** [comment]
Nope this is not a duplicate of that issue

**Comment by octref** [comment]
@jedwards1211 What specific rules conflict?

If I remove it then I have to manually enable the formatting rules for my code...

**Comment by jedwards1211** [comment]
Or maybe I misunderstand, is prettier used for different file types than tsfmt or something?  I assume there would be no point to using both on ts files.  Also I had assumed that the prettier extension made itself the default formatter in VSCode because a config was found, but seems like it was just that I was already using the prettier extension

**Comment by jedwards1211** [comment]
In any case maybe for some people the guidance to just run the Format Document command on .ts in this repo just works, but for me everything is messed up because it formatted with prettier instead.

**Comment by octref** [comment]
Yeah, our idea was to leave it there, so team member with prettier (me) can use it, but we didn't enforce everyone onto prettier.

If you are contributing, you should use TS formatter. There should be a choice when 2 formatters are available.

**Comment by jedwards1211** [comment]
I'm confused though, you still have to use tsfmt to commit code right?

**Comment by jedwards1211** [comment]
And is there any configuration file in the repo that can make it use tsfmt on save by default/ask to install the tsfmt extension?  If nothing else we should make a package script to run the formatter

**Comment by octref** [comment]
For me, I run my files on prettier. We have precommit hook to check formatting:
- If it succeeds, I do nothing
- If it fails, I format with TS formatter again

> Is there any configuration file in the repo that can make VSCode use tsfmt on save by default/ask to install the tsfmt extension?

No. Some of us would be annoyed by that.
When you commit the file the hygiene will complain if it sees non-formatted code. If it doesn't complain, you are good.

**Comment by jedwards1211** [comment]
I see.  This confused me a lot when making my first PR 🙃
