### ISSUE TITLE
[html] auto rename broken state when deleting tags

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86156]
Testing #85973

```
<html>
    <foo>

    </foo>
</html>
```

* put cursor at the end of foo of line 2
* press backspace three times
* auto rename mode doesn't exit, and leave the document in a weird state

**Comment by octref** [comment]
When you don't have a complete pair, I think updating `<f` to `<bar` when you rename `f` to `bar` is fine. Or is your case different?

![Kapture 2019-12-04 at 16 12 47](https://user-images.githubusercontent.com/4033249/70192574-0826bb80-16b1-11ea-8964-ae96d3d0d43b.gif)

**Comment by rebornix** [comment]
This one seems caused actually by https://github.com/microsoft/vscode/issues/86151
