### ISSUE TITLE
[html] auto rename weird cursor state management

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86158]
Testing #85973

```
<html>
    <foo>
    </foo>
</html>
```

* put cursor in the middle of foo of line 2
* press arrow down then up
* it's weird as it behaves like I'm pressing arrow left and right

**Comment by octref** [comment]
Where exactly in `<foo>` are you putting it? Can't repro.

**Comment by rebornix** [comment]
I updated the snippet

```
<html>
    <foo>
    </foo>
</html>
```

![Kapture 2019-12-05 at 11 37 13](https://user-images.githubusercontent.com/876920/70267586-99e70500-1753-11ea-93b2-f5278782570c.gif)

**Comment by octref** [comment]
This is unfortunately expected behavior:

Initial:

```html
<html>
    <foo|>
    </foo|>
</html>
```

Down button
```html
<html>
    <foo>
    </fo|o>
</html>|
```

HTML kicks in to remove mirrored cursor
```html
<html>
    <foo>
    </fo|o>
</html>
```

HTML kicks in again to add mirrored cursor from the end tag to beginning tag
```html
<html>
    <fo|o>
    </fo|o>
</html>
```
