### ISSUE TITLE
Only one install option for extensions that list multiple extension kinds

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#86152]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/85948

1. Connect to a remote using WSL, containers, or SSH
2. Search for the test extensions "sandy081.ui-workspace-extension" and "
sandy081.workspace-ui-extension"

Expected:
Since both extension kinds are supported for these, I thought I would see buttons to install either locally or on the remote

Actual:
Only one option is shown, "Instally locally" for the "ui-workspace-extension" and "Install on <remote>" for the workspace-ui one

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:35:54.992Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1025-azure

**Comment by sandy081** [comment]
Yeah it is because their preferable location is either workspace or ui and they get installed in the preferable location.
