### ISSUE TITLE
VsCode starts into the same Workspace everytime

### ISSUE THREAD

**Issue by aateeque** [microsoft/vscode#86169]
Issue Type: <b>Bug</b>

Whenever my VsCode starts, it lands on the same unsaved worksapce which has three folders. This even happens on a fresh install on a different PC. It's as if I am carrying it around on the Roaming Profile on the network.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3491)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.91GB (10.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Perhaps you are. Do you want the workspace? If not, use Close Workspace from the File menu.

**Comment by bpasero** [comment]
@aateeque if you close the workspace via File menu it should go away.

**Comment by aateeque** [comment]
It's back - that workspace which isn't saved is back. I have tried close workspace & close vs code; and it still opens up to that unsaved worksapce

**Comment by bpasero** [comment]
@aateeque can you try to `File > Save Workspace As` and then open another folder? It should then be good for good. 

Any clues how you get into this state all the time? Are you opening more than 1 folder into the same workspace?
