### ISSUE TITLE
Custom editors in inconsistent state

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86162]
Testing #85991

I've managed to do this a couple times but I don't have repro steps yet. Just doing a combination of typing in different editors, undo/redo, save, reload window.

Once an editor opened after reloading the window with different content than the other editors.

In this case, an editor has different content after undoing all the way back:

![Dec-03-2019 12-00-41](https://user-images.githubusercontent.com/323878/70085165-9113f900-15c4-11ea-93a2-60cfe021cb8a.gif)

Will update if I can get a better repro

**Comment by roblourens** [comment]
One repro is just to have several editors open, make a change, then reload the window without saving. Then I get this:

![image](https://user-images.githubusercontent.com/323878/70093033-6631a100-15d4-11ea-8029-1d01c8b4c4cd.png)

the real content is without `abc`

**Comment by mjbvz** [comment]
Can you please test to see if you can get into this state without a window reload. The window reload cases are related to hot exit and I have not tested or tried to implement them yet

**Comment by roblourens** [comment]
No, I'm pretty sure the reload is necessary
