### ISSUE TITLE
Hovering over "module" in tsconfig.json gives incorrect suggestions

### ISSUE THREAD

**Issue by httpdigest** [Microsoft/vscode#8616]
- VSCode Version:1.3.0-insider (Commit 716f76458)
- OS Version: Windows 7 x64

Steps to Reproduce:
1. Create a tsconfig.json file with "compilerOptions" and the "module" property in it.
2. Mouse-hover over the "module" property
3. See that it suggests, among others, "CommonJS", "Amd", "System", etc. (notice case!)
4. Write any of the mentioned module values in the suggested case
5. Observe that neither of those values are accepted and Visual Studio Code tells that only their lower-case values are valid values

**Comment by dbaeumer** [comment]
We are using the tsconfig schema from here: http://json.schemastore.org/tsconfig which is backed by https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json.

Moving to TS team which seem to contribute to the tsconfig.json.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9505
