### ISSUE TITLE
Webview editor z-index

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86160]
Testing #85991

Can the webview be forced beneath the rest of the workbench?

![image](https://user-images.githubusercontent.com/323878/70085039-5a3de300-15c4-11ea-91a7-f81396df118e.png)

**Comment by mjbvz** [comment]
MacOS, correct? Any repo steps?

**Comment by mjbvz** [comment]
Looks like same root cause as #82653

Unfortunately we have to keep webview elements outside of the main dom layout to avoid reparenting them
