### ISSUE TITLE
CTRL+ALT+ARROW should not delete empty lines

### ISSUE THREAD

**Issue by MattEsquivel** [microsoft/vscode#86163]
Issue Type: <b>Bug</b>

In VS I used to use SHIFT+ALT to reduce or increase the indent of many lines at once. In VS Code when I use CTRL+ALT to do the same it is annoying because:
1) It deletes empty vertical space lines. That is not my intent, my intent is to delete extra spaces, not empty lines.
2) When you use the arrow key after making the large cursor it moves the entire cursor, which is not what I want. It just gets confusing.

Ideally you will fix (1). (2) is something I could get used to.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (14.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
gitlens|eam|10.2.0
cpptools|ms-|0.26.2

</details>

**Comment by alexandrudima** [comment]
@MattEsquivel 

- `Ctrl+Alt+Up`/`Ctrl+Alt+Down` are commands for introducing multiple cursors. Multiple cursors is a feature that is similar, but different to column selection.
- We have also implemented column selection. By default, those commands are available via `Ctrl+Shift+Alt+` arrow keys. But we lack virtual space. That is tracked in #13960 . You can also use the middle mouse button to do column selection.
- For indenting/unindenting multiple lines there are alternative built-in commands via `Tab`, `Shift+Tab`, `Ctrl+]` and `Ctrl+[`.
