### ISSUE TITLE
Sync: provide a command to forcefully sync

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#86177]
I know by reading issues that I can force a sync by opening the settings editor, but it may be useful to provide a more explicit "sync now" command.

**Comment by sandy081** [comment]
May I know the usecase why do you want to have that command given that sync happens every 5 mins and also on special events?

**Comment by connor4312** [comment]
Maybe it's just because I was testing it, but I found myself wanting to "save" a changed setting and then have the reflect immediately on my other machine/vm. Instead I either had to wait 5 minutes or hit one of the magic sync triggers.

Another good alternative would be to trigger a sync immediately after the settings are closed.

**Comment by sandy081** [comment]
We trigger sync when settings or keybindings or extensions got changed. Let me know if you did not see that happening?

**Comment by connor4312** [comment]
It doesn't seem like the settings eagerly sync after being changed. A few minutes later they do eventually sync, but it's not immediate.

**Comment by sandy081** [comment]
Hmm strange. Probably you are facing this issue - https://github.com/microsoft/vscode/issues/86067

**Comment by connor4312** [comment]
Sounds like it. Resolving that would make this unnecessary, I'll close it.
