### ISSUE TITLE
Run selected text in active terminal is not running the selected text

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8617]
Windows 8.1 with insiders latest build #716f764

Steps to Reproduce:

1. Open a file and select text "echo 123"
2. Open command pallette and select action Run selected text in active terminal

Expected: Selected text should be executed in the terminal
Actual: Text is just copied into terminal and focus remains in editor

**Comment by Tyriar** [comment]
@sandy081 what shell are you using? Also did you include a `\n` character in the text?
