### ISSUE TITLE
Cntrl + Shift + E should toggle explorer pane

### ISSUE THREAD

**Issue by kismet-cai** [microsoft/vscode#86171]
Issue Type: <b>Feature Request</b>

Cntrl + Shift + E should toggle explorer pane, clicking on Explorer in the View menu should also toggle explorer pane in and out of view.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/85785#issuecomment-560317290
