### ISSUE TITLE
Sync: Settings conflict file closes when opening the editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#86173]
https://github.com/microsoft/vscode/issues/85944

 1. Get into a conflicted state and start resolving conflicts
 2. Close and re-open VS code
 3. The conflicted settings file is open briefly and then closes, even if conflicts remain

I'd expect that we'd be able to continue using or reuse the same file.

**Comment by sandy081** [comment]
On reload, the editor is closed and notification is shown again to show conflicts. I think this is behaviour is reasonable given that conflicts are very rare.
