### ISSUE TITLE
Toggling regex mode in search sometimes flickers results

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#86179]
Testing #85953

Minor issue

Repro steps:
1. Do a search that will not change results when toggling regex mode
2. Toggle regex mode on and off

:bug: => sometimes the line `X results in Y files` flickers with less results before settling on the initial state.

**Comment by JacksonKearl** [comment]
Given that we need to run the search all over again, there will always be cases where the result count resets. We try to avoid this by delaying the rendering of new results by ~200ms, but depending on the size of the search that might not be enough to get all of the results, and at the cusp of being able to get all results in the allotted delay time, there will always be flickering.

**Comment by JacksonKearl** [comment]
@sana-ajani also noticed flickering, going to increase the delay. Seems like 100ms isn't enough for windows.
