### ISSUE TITLE
Better linting support for sass variable references via @use

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#86183]
Testing #85979

![image](https://user-images.githubusercontent.com/35271042/70094103-a42fc480-15d6-11ea-8ab7-a452c93a7048.png)

1. Create a `helper.scss` file with a `$red` variable
2. Create a `main.css` file with a `@use` ref for the helper file
3. Try and use the variable in an element
4. :bug: No linting errors but sass compile throws errors

I would expect better linting to avoid compile errors, it should tell me the same errors from the terminal as we do with other TS errors.

**Comment by octref** [comment]
Cross-file SCSS support is in https://github.com/mrmlnc/vscode-scss.
