### ISSUE TITLE
Compact Folders: Shift+F10 changes focused folder

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86189]
re #85928

Open a workspace with following folder structure

```

- .github
  - ISSUE_TEMPLATE
    - issue.md
```

* Move focus to `.github` with keyboard
* Shift+F10
* Focus moves to `ISSUE_TEMPLATE`

**Comment by isidorn** [comment]
DUp of https://github.com/microsoft/vscode/issues/86106
