### ISSUE TITLE
Search editor match highlight background is too dark

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86185]
Testing #85965

Very hard to see the highlight here:

![image](https://user-images.githubusercontent.com/323878/70094231-f244c800-15d6-11ea-885b-dcbc431c4a2b.png)

Compared to the highlight of search results in the actual editor:

![image](https://user-images.githubusercontent.com/323878/70094260-01c41100-15d7-11ea-9103-540aba1ab908.png)

I think it should just use the same color

**Comment by JacksonKearl** [comment]
We explicitly don't want it to be the same color, as that makes searching in the search results difficult (everything looks the same). Right now its a half-transparent version of the normal highlight, but we could adjust it to be 75% or something? It is configurable by extensions or end users.

**Comment by JacksonKearl** [comment]
@misolori what do you think of the highlighting color?

**Comment by misolori** [comment]
Don't we already do something similar when you click on a search result? I also expected it to be the same from the sidebar:

![image](https://user-images.githubusercontent.com/35271042/70188714-479bda80-16a6-11ea-9f78-ebdb1d452e3c.png)

And when using find:

![image](https://user-images.githubusercontent.com/35271042/70188736-54b8c980-16a6-11ea-96bf-6096c2786676.png)

**Comment by JacksonKearl** [comment]
The colors are the same, they look different there becauase you're overlaying two decorations on top of each other.
![image](https://user-images.githubusercontent.com/8586769/70188945-e58fa500-16a6-11ea-8531-6f5f736b3411.png)

**Comment by misolori** [comment]
If I set `searchEditor.findMatchBackground` to `#ea5c0054` then I get the same effect:

![image](https://user-images.githubusercontent.com/35271042/70189333-e37a1600-16a7-11ea-85fb-05eb7dd4d8ec.png)


I'd be in favor of using the same color.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/70190878-073f5b00-16ac-11ea-8449-a888eb184115.png)

![image](https://user-images.githubusercontent.com/8586769/70190914-17efd100-16ac-11ea-9fe5-eba2df6bdf02.png)

**Comment by misolori** [comment]
Well, this is the same result from a search and using find inside there as well 🤷‍♂️

![image](https://user-images.githubusercontent.com/35271042/70191864-fe9c5400-16ae-11ea-9141-faa85bd3d02e.png)
