### ISSUE TITLE
Search editor shouldn't ask to save on close

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86191]
Testing #85965

- Close search editor
- It asks whether to save

I thought you had a way to make the editor "saveable" but not ask whether to save? It is kind of annoying and makes the search editor feel "heavier"

**Comment by JacksonKearl** [comment]
We previously explicitly exempted the search editor from the Save on Close prompt but @kieferrm felt strongly about us not doing that.

**Comment by JacksonKearl** [comment]
Now only asks to save when you explicitly modify the results
