### ISSUE TITLE
When opening result from search editor, the cursor should go to the match

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86190]
Testing #85965

- Open search editor, put cursor on a result
- Press F12
- The file is opened and the cursor is at the beginning of the line, but the cursor should be on the match itself

**Comment by JacksonKearl** [comment]
Placing your cursor in the same area it was at when you hit f12 for now. We don't really have a concept of where the actual match is on the line, but that should be added eventually...

**Comment by JacksonKearl** [comment]
Currently working as per initial issue description: if you put your cursor on a result and press f12, you'll end up at the result.
