### ISSUE TITLE
code-search files should be excluded from all searches

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86195]
Testing #85965

This should be done differently -

https://github.com/microsoft/vscode/blob/a868166d9ece2af3be2579ce5c873117790db87b/src/vs/workbench/contrib/search/common/searchModel.ts#L986-L989

either it should be done in the QueryBuilder so it applies to searches that don't go through SearchModel (like through extension API) or it should be added to the `search.exclude` default.

**Comment by JacksonKearl** [comment]
One could verify by either looking at the code, or developing an extension that searches and noticing that `*.code-search` results are excluded.
