### ISSUE TITLE
WebGL Renderer: selection not rendered in background

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86194]
Re #85971

* macOS
* zsh with oh my zsh

* Run scripts described in https://github.com/microsoft/vscode/issues/85971#issuecomment-561273784 
* Open with Canvas rendering and select all 

![image](https://user-images.githubusercontent.com/876920/70096161-4782d880-15db-11ea-8ff8-6ee6cb135919.png)

* Open with WebGL rendering

![image](https://user-images.githubusercontent.com/876920/70095798-7b113300-15da-11ea-99c2-4ab7c1802f83.png)
![image](https://user-images.githubusercontent.com/876920/70096170-4fdb1380-15db-11ea-9396-4955702fb623.png)

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/2599

I think the problem with inverse is the only issue there? Let me know if I'm wrong.

**Comment by rebornix** [comment]
yup, that's the only issue I saw.
