### ISSUE TITLE
Search results editor - problems triggering hover on Linux

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#86199]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/85965

This is possibly just an issue with my VM, I'll test again on actual hardware tonight.

1. Have `editor.multiCursorModifier` set to alt
2. With `"search.enableSearchEditorPreview": true` set, run search and open it in an editor

Pressing ctrl and hovering over results doesn't show a hover with the line in context. Sometimes on key up the cursor changes from input to pointy hover hand.

I've tried on Mac as well and don't have any issues there

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:31:49.954Z)
OS version: Linux x64 4.11.12-100.fc24.x86_64

**Comment by JacksonKearl** [comment]
Can you get hovers from other definition providers on the VM? TS, for instance.

**Comment by RMacfarlane** [comment]
Ah, good question. Nope, that's also not working on this VM. So, this is unrelated to the feature
