### ISSUE TITLE
Remote SSH VSCode Command

### ISSUE THREAD

**Issue by jhamet93** [microsoft/vscode#86196]
I'm trying to write a custom extension which from a high level, will remotely SSH to a external machine (via `vscode.newWindow`) and then upon success, automatically open a certain folder location (via `vscode.openFolder`).

The issue I'm running into is I do not want to open a folder until the SSH connection is complete. However, it appears the execution of the vscode command completes before a success/failure.

```
const response = await vscode.commands.executeCommand("vscode.newWindow, { remoteAuthority: "ssh-remote+..."})"
```

Is there an alternative route to achieve my goal since it appears `vscode.newWindow` is returning right away in the case of a remote ssh connection ?

**Comment by roblourens** [comment]
The new window will open in, well, a new window, and so your extension needs to handle this in two steps. First open a new window, and if the extension detects that it's being activated in an empty remote window, open the folder.
