### ISSUE TITLE
Unable to start Code on Ubuntu

### ISSUE THREAD

**Issue by ace007** [Microsoft/vscode#862]
I am running Ubuntu 15.04, without a GUI. My home directory is an NFS share mounted via automount, my account is via NIS.
After installing Gnome I have been able to get the Code executable to run by double clicking on the program from a file explorer. But not from a shell, either on the console or a remote ssh.
If I run the Code program from my normal ssh login it runs waits a while and then exits, with no error message or anything.
If I run it with the sudo Code command it runs up and works fine, apart from the whole running as root issue :(.
I suspect it's a file permission thing but am unable to track down what it could be.

Regards

John

**Comment by bpasero** [comment]
Would be nice if you could track further ;)

**Comment by ace007** [comment]
The program exits without any information.
Is there a log file or any command line options that would make it easier to find out what is wrong ?

**Comment by bpasero** [comment]
Maybe "code --verbose" reveals more?

**Comment by ace007** [comment]
That gave me this error
Startup error: TypeError: Bad argument
Still not helpful
Seems to work fine when run via sudo Code

**Comment by bpasero** [comment]
Hmmm, I wonder if this has something to do with the window properties we set. Are you able to build and run VS Code out of source code here on GitHub?

**Comment by ace007** [comment]
This is heading down a rabbit hole I would rather not go down at the moment, I am really busy and was hoping this tool would speed things up.
I have the software running on my windows machine so I can use it there for now.
The Ubuntu machine I am using is a vm on my windows machine (using Hyper-V) and it is NOT a full desktop install, it's version 15.04. I have had to install gnome (apt-get install gnome) just to get the software to run. You install notes are vague on what the dependencies are, it's possible that there is something not quite right about my environment. It was built to run docker containers and not for more complex software building.
I will see what I can do if I get some free time.

**Comment by bpasero** [comment]
Yeah no worries, take your time. The instructions are here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

It could be that something is missing as requirement but it could also be that we do something wrong when setting the window dimensions for VS Code. I got suspicious when I saw the error message from the --verbose call.

**Comment by ace007** [comment]
It is being X displayed back from the Ubuntu vm to Cygwin running on my windows machine

**Comment by bpasero** [comment]
Got it, it could also well just be not supported by the Electron framework we use for rendering the UI. Does the Atom editor open?

**Comment by ace007** [comment]
don't forget it does work when run by "sudo Code" from the same shell as the one that doesn't work

**Comment by bpasero** [comment]
Hm good point... :cake:

**Comment by ace007** [comment]
Also it will run if I log onto the console of the vm (when it's running gnome) and double click on the program from the folder/explorer view. However it wouldn't run from an xterm shell in the same logon enviroment

**Comment by bpasero** [comment]
Does this still happen with latest?

**Comment by ace007** [comment]
Just downloaded an run the latest zip file
ls -la /usr2/VSCode-linux-x64/Code
-rwxr-xr-x 1  59217872 Dec 17 16:23 /usr2/VSCode-linux-x64/Code

I get the following error

/usr2/VSCode-linux-x64/Code
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at Object.exports.spawn (child_process.js:351:9)
    at /usr2/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:6:25084
    at new __dirname.undefined.t.Class.derive._oncancel (/usr2/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:5:2734)
    at Object.i [as getUserEnvironment] (/usr2/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:6:25047)
    at Object.<anonymous> (/usr2/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:9:3090)
    at e._invokeFactory (/usr2/VSCode-linux-x64/resources/app/out/vs/loader.js:4:13773)
    at e._complete (/usr2/VSCode-linux-x64/resources/app/out/vs/loader.js:4:14012)
    at e.resolveDependency (/usr2/VSCode-linux-x64/resources/app/out/vs/loader.js:4:15066)

**Comment by bpasero** [comment]
That sounds like an issue in getting the user environment. @joaomoreno fyi

**Comment by ace007** [comment]
Is there any extra debug information I can get/provide ?
It works fine when I use sudo to run it

**Comment by joaomoreno** [comment]
What do you get with `echo $SHELL`?

**Comment by ace007** [comment]
That's the problem
I am using ksh but SHELL=/bin/sh
If I set SHELL=/bin/ksh it all works fine.

I am trying to find out why xterm is setting SHELL to the wrong value

**Comment by ace007** [comment]
It turns out that the xterm on the machine (3.19.0-15-generic #15-Ubuntu) is not setting SHELL to my actual shell (/bin/ksh) but defaulting to /bin/sh.
I have fixed this in a script and I now get an xterm with the correct SHELL variable ($SHELL=/bin/ksh)
This now allows Code to run correctly :D

**Comment by joaomoreno** [comment]
What do you get with `/bin/sh --version`?

**Comment by ace007** [comment]
/bin/sh --version
/bin/sh: 0: Illegal option --
/bin/ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01

**Comment by joaomoreno** [comment]
Maybe `/bin/sh -v`?

**Comment by ace007** [comment]
No that gives the same error 
I tried this
strings /bin/sh | grep -i ver
preverrout
verbose
%s: not completely converted
.gnu.version
.gnu.version_r
and this
strings /bin/sh | grep -i [0-9].[0-9]
/lib64/ld-linux-x86-64.so.2
GLIBC_2.3
GLIBC_2.11
GLIBC_2.3.4
GLIBC_2.14
GLIBC_2.4
GLIBC_2.2.5
5_5!
t2D9
*0123456789

Best I can get is this
ls -la /bin/sh
lrwxrwxrwx 1 root root 4 Nov  6 15:21 /bin/sh -> dash
ls -la /bin/dash
-rwxr-xr-x 1 root root 121272 Feb 19  2014 /bin/dash

**Comment by joaomoreno** [comment]
OK that helps: you seem to be running [dash](https://en.wikipedia.org/wiki/Almquist_shell). Leaving it closed as I don't think many people will hit this.

**Comment by hashhar** [comment]
@ace007 Seems like I ran into the same issue. I had some troubleshooting ideas but couldn't find somebody who had faced this before.

Could you try running 
```
echo $SHELL
sudo chsh
# Set it to /bin/sh
sudo reboot
```
Try running Code again.
AND,
```
echo $SHELL
sudo chsh
# Set it to /bin/bash
sudo reboot
```
Try running Code again.

I want to isolate if the reason is /bin/sh or /bin/bash.

**Comment by ace007** [comment]
Hi,
I am running Code (version 0.10.5)  via a ssh spawned xterm with /bin/ksh.
My problem was that xterm (on my version of ubunto) was not setting SHELL to the correct value.
It was defaulting to /bin/sh, which was a sym link to /bin/dash.
I modified my profile script and forced SHELL to be my login shell and all was fine.
I suspect that the problem is with /bin/sh (which is actually /bin/dash)

**Comment by hashhar** [comment]
I have the exact opposite. My login shell is bash, but it works with SHELL set to any other shell but bash.
I also wrote a script that changed my SHELL when calling `code`.
