### ISSUE TITLE
Remote Explorer UI: UI consistency with Debug Viewlet

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86208]
Test #85927

![image](https://user-images.githubusercontent.com/4033249/70099807-c29cbc80-15e4-11ea-9535-0b3b52682590.png)

Notice that:

- Debug has round corners. Remote Explorer UI has angled ones.
- The description feel cramped to the left in the Explorer UI (`Containers`). Should give a few more pixels to the left, just like Debug Viewlet (`Unit Tests`)

**Comment by alexr00** [comment]
Fixed by @misolori in https://github.com/microsoft/vscode/issues/86031
