### ISSUE TITLE
Make remote timeout configurable

### ISSUE THREAD

**Issue by taiyosogawa** [microsoft/vscode#86202]
We'd like to make the remote development timeout configurable to handle longer connection times. I believe it is currently configured to 20 seconds.

**Comment by jkeech** [comment]
@alexdima, any update on this? Another VSO user hit a connection timeout when running in a browser on slower hardware (raspberry pi) in MicrosoftDocs/vsonline#414.

**Comment by alexdima** [comment]
The start-up timeouts have been removed via https://github.com/microsoft/vscode/commit/25dc50c18edae19089169a255802137ac5ebfef0
