### ISSUE TITLE
 TreeError [MarkersPanel] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#86201]
Issue Id: <b>990a4e3b-c48d-4deb-8a07-b908a2df554d</b><br /><br />*Versions* <br />- 1.41.0-insider (12/2/2019 5:20:41 AM)<br />*Stack* <br />Error: TreeError [MarkersPanel] Tree element not found: [object Object]<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#281:9 (getElementLocation)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/base/browser/ui/tree/objectTreeModel.ts#L281:9 (getElementLocation))<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#219:24 (isCollapsed)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/base/browser/ui/tree/objectTreeModel.ts#L219:24 (isCollapsed))<br />[/vs/base/browser/ui/tree/abstractTree.ts#1513:20 (isCollapsed)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/base/browser/ui/tree/abstractTree.ts#L1513:20 (isCollapsed))<br />[/vs/workbench/contrib/markers/browser/markersPanel.ts#560:19 (autoReveal)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L560:19 (autoReveal))<br />[/vs/workbench/contrib/markers/browser/markersPanel.ts#489:7 (onActiveEditorChanged)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L489:7 (onActiveEditorChanged))<br />[/vs/workbench/contrib/markers/browser/markersPanel.ts#437:9 (call)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L437:9 (call))<br />[/vs/base/common/event.ts#89:116 (call)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/base/common/event.ts#L89:116 (call))<br />[/vs/base/common/event.ts#581:15 (fire)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/base/common/event.ts#L581:15 (fire))<br />[/vs/workbench/services/editor/browser/editorService.ts#121:32 (doHandleActiveEditorChangeEvent)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/workbench/services/editor/browser/editorService.ts#L121:32 (doHandleActiveEditorChangeEvent))<br />[/vs/workbench/services/editor/browser/editorService.ts#110:7 (handleActiveEditorChange)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/workbench/services/editor/browser/editorService.ts#L110:7 (handleActiveEditorChange))<br />[/vs/workbench/services/editor/browser/editorService.ts#129:9 (call)](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/workbench/services/editor/browser/editorService.ts#L129:9 (call))<br />[/vs/base/common/event.ts#581:15](https://github.com/microsoft/vscode/blob/7cf4cca47aa025a590fc939af54932042302be63/src/vs/base/common/event.ts#L581:15)<br />    at out/vs/workbench/workbench.deskto<br />

**Comment by sandy081** [comment]
@joaomoreno This keeps coming and I do not know the steps to repro. Is it possible to get a method from tree to know if the model exists or not?

**Comment by joaomoreno** [comment]
@sandy081 Pushed `tree.hasElement()`.
