### ISSUE TITLE
SCM decoration colors in the overview ruler don't match minimap and gutter 

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#86207]
- VSCode Version: 1.41 Insiders
- OS Version: Windows

The SCM change decorations in the overview ruler are all the same color (blue is the default) while in the editor and minimap add/modify/delete are different colors.

The colors are themeable editorOverviewRuler.addedForeground, etc. but I wonder why we leave them all blue by default?

**Comment by misolori** [comment]
@aeschli any objections to making these same colors?

**Comment by misolori** [comment]
Here's what that would look like:

![image](https://user-images.githubusercontent.com/35271042/70193227-58068200-16b3-11ea-9617-afc81f5e265f.png)

**Comment by aeschli** [comment]
I'm not opposed but this has historical reasons that @joaomoreno knows about.

**Comment by gregvanl** [comment]
Perhaps to not confuse the user with error (red) and warning (yellow) decorations also in the overview ruler? The decorations would be on different columns.

**Comment by joaomoreno** [comment]
There's been multiple times this has been raised. The reason why it was implemented this way and we kept it for a long time is to prevent the already noisy scrollbar from becoming even more, as well as, like @gregvanl says, the fact that errors and warnings appear as green as red respectively in the scroll bar.

**Comment by alexandrudima** [comment]
I don't think green is a big problem anymore, it used to be that warnings were green.

But the problem remains with the errors. IMHO we should only use red in the overview ruler for errors. We have our eyes trained already that red in the overview ruler => errors. I would not dilute that...

Maybe we can find another color, but I wouldn't go with red... Another idea would be to let people customize the colors if they want to, but I would keep the defaults without using red.

**Comment by misolori** [comment]
We discussed this during today's UX sync and the consensus was making it consistent is the right direction however we should dim the colors so that they don't take too much focus away. I'll setup a PR that shows this.
