### ISSUE TITLE
Unresponsive & freezes

### ISSUE THREAD

**Issue by robopo** [microsoft/vscode#86218]
Issue Type: <b>Bug</b>

Freezes for a few seconds, is unresponsive to mouse and keyboard. Started with 1.40.2

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
