### ISSUE TITLE
Keep selected item when typing line numbers

### ISSUE THREAD

**Issue by regoje** [microsoft/vscode#86215]
- VSCode Version: 1.40.2

Steps to Reproduce:

1. In quick open search for a file
2. Using arrow keys select it 
3. Type :123 (colon followed by a line number to go to in that file)
4. The selection is reset to the first result

If, however, :123 is entered and the file then selected the correct line number is juumped to.

![Peek 2019-12-04 09-17](https://user-images.githubusercontent.com/1166932/70103781-004a2580-1677-11ea-91e5-9b9939491242.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Yeah, each letter you type is interpreted as new search and will result in new results to appear where we do not preserve the selection.

**Comment by Wowol** [comment]
I will look into this and create a PR soon, if you don't mind.

**Comment by bpasero** [comment]
I ended up doing this with the new quick open implementation. The results stay as they are for when a line/col is typed in the query for file results.

**Comment by bpasero** [comment]
**Verification:** https://github.com/microsoft/vscode/issues/86215#issue-532376564
