### ISSUE TITLE
Deleting/Renaming a folder in explorer doesn't return all the affected files in the event listener

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#86213]
When testing https://github.com/microsoft/vscode/issues/85929

Steps to reproduce:

1) Use the example code from https://github.com/microsoft/vscode/issues/86210

2) Delete a folder in the explorer and watch an event received that only contains the folder name being deleted. Same for renaming a folder as well.

Not sure if this is as designed or what is the right behavior here, wouldn't it be better to list the files in the folder affected because their path is now changed/deleted, considering this event is specific for files ?

**Comment by jrieken** [comment]
Yeah - that's the designed behaviour and I have also made an attempt to [document](https://github.com/microsoft/vscode/blob/8d2160686e73b3ea2fd5d44628f4b7348e6aeff4/src/vs/vscode.d.ts#L8632) that with the event. Think about deleting node_modules and the avalanche of event that would be required if listing all children, apart from the fact that we don't have this information when such operations are performed

**Comment by deepak1556** [comment]
Sounds good, but the result of the operation `FilesDeleteEvent` has a value that says `/**
		 * The files that got deleted.
		 */
		readonly files: ReadonlyArray<Uri>;` which seems misleading, can we better clarify that ?

Also any reason for this event listeners to care about changes to a folder value ? Maybe avoiding that would keep it simpler ?
