### ISSUE TITLE
Deleting multiple files through explorer invokes the event listeners per file

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#86210]
When testing https://github.com/microsoft/vscode/issues/85929

Steps to reproduce:

1) Register delete event listeners

```
vscode.workspace.onWillDeleteFiles((e : vscode.FileWillDeleteEvent) => {
	const p = new Promise((resolve) => {
		setTimeout(() => resolve(), 10000);
	});
	e.waitUntil(p);
	console.log(e.files.length);
});

vscode.workspace.onDidDeleteFiles((e : vscode.FileDeleteEvent) => {
	console.log('DELETING...');
	e.files.forEach(file => console.log(file));
});
```

2) Select multiple files from the explorer with `Cmd+Click` and delete using context menu.

3) Expect to receive single event fire for all the files but instead the listener is fired individually for each file being deleted.

Output: 

```
1
1
DELETING...
<Object>
DELETING...
<Object>
```

**Comment by isidorn** [comment]
The issue is that the file-explorer calls the textFileService per resource. To tackle this we should introduce a bulk call in the textFileService.

**Comment by isidorn** [comment]
This should actually be fixed now with the PR that introduces bulk operations
