### ISSUE TITLE
Make Activity Bar items toggleable by keyboard shortcut 

### ISSUE THREAD

**Issue by KonFr** [microsoft/vscode#86227]
At the moment it is possible to open Activity Bar item using keyboard shortcuts (Explorer Ctrl-Shift-E, Search Ctrl-Shift-F etc.) but you have to use mouse to hide it back. Would be nice to use same keyboard shortcuts to hide them, toggle visibility of those.

**Comment by eunjoohwang12** [comment]
🔑

**Comment by gjsjohnmurray** [comment]
Do you know that <kbd>Ctrl+B</kbd> already exists as that toggle?

**Comment by KonFr** [comment]
> Do you know that Ctrl+B already exists as that toggle?

No, I did not know this, thank you @gjsjohnmurray

**Comment by nickdepinet** [comment]
Additionally, if you want to use the same keybinds then you can add following overrides to your keybindings.json for either whenever the pane is visible or only if the context focus is on it:
```

[
    { "key": "ctrl+shift+e",          "command": "workbench.action.toggleSidebarVisibility",
                                        "when": "explorerViewletVisible" },
    { "key": "ctrl+shift+f",          "command": "workbench.action.toggleSidebarVisibility",
                                        "when": "searchViewletFocus" }
]   
```       

It doesn't appear that there is good context registering for the repository, debug, and extensions viewlets

**Comment by KonFr** [comment]
Thanks @nickdepinet for useful information
