### ISSUE TITLE
Hovers no longer show up above the current line

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#86228]
Issue Type: <b>Bug</b>

They now appear to overlap the current line
![image](https://user-images.githubusercontent.com/641685/70120296-34ebbc00-163a-11ea-8a64-0b8b2bf270bc.png)

VS Code version: Code - Insiders 1.41.0-insider (43e3581aa635406ada2d8138d7ee242ddabefc1c, 2019-12-04T05:29:38.104Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by octref** [comment]
Dup of #86239.
