### ISSUE TITLE
Give application wise theme enabling option.

### ISSUE THREAD

**Issue by zeromsi** [microsoft/vscode#86229]
If I open multiple workplace, I can hardly acknowledge which workplace to work on.

**Comment by roblourens** [comment]
Sorry, I don't know what you mean. Please give more details.

**Comment by zeromsi** [comment]
I'll try to give an example,
Suppose I'm working on 3 projects, opened on vscode from different workplaces. When I try to switch from one VS code instance to another, I get confused as the color are same. I'm not sure , if there's any option to give vscode instance different color or theme, provably application wise.

**Comment by zeromsi** [comment]
> Sorry, I don't know what you mean. Please give more details.

I'll try to give an example,
Suppose I'm working on 3 projects, opened on vscode from different workplaces. When I try to switch from one VS code instance to another, I get confused as the color are same. I'm not sure , if there's any option to give vscode instance different color or theme, provably application wise.

**Comment by roblourens** [comment]
It's possible, search around a bit or see this extension https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock

**Comment by zeromsi** [comment]
Thanks Rob :)
