### ISSUE TITLE
Move line up/down should keep the indentation

### ISSUE THREAD

**Issue by prabowomurti** [microsoft/vscode#86222]
Issue Type: <b>Feature Request</b>

When I move the `echo $row->id;` line up, and down it again, it goes from : 

```
        foreach ($expired_tiers as $key => $row) {
            echo $row->account_id;
        }
```

to 

```
            foreach ($expired_tiers as $key => $row) {
                echo $row->account_id;
        }
```
As you can see that the indentation is also changed.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 17.7.0

**Comment by whizsid** [comment]
Can you provide an animated GIF that containing what you did? I have tested it and worked.
