### ISSUE TITLE
pls provide direct download links for SSH remote extension (VS Code server Work space Extension) download

### ISSUE THREAD

**Issue by aKumaraGHB** [microsoft/vscode#86233]
referring to 
Remote Development using SSH https://code.visualstudio.com/docs/remote/ssh

our linux back end servers which contain source code (which I intend to open with VS code) has no Internet access. So the SSH extension cannot perform the required download in remote machine.

Therefore please provide direct download links (as zip files) for the VS Code server Work space Extension

**Comment by roblourens** [comment]
If it fails to download on the remote, it will try to download on the client. If the client doesn't have internet, there is another issue tracking that request.

**Comment by aKumaraGHB** [comment]
> "there is another issue tracking that request."

@roblourens , would you kindly be able to provide the issue ID of that issue

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1242
