### ISSUE TITLE
SHORTCUT NOT WORKING

### ISSUE THREAD

**Issue by Gunawanart** [microsoft/vscode#86230]
Issue Type: <b>Bug</b>

I CANT USE SOME SHORTCUT, I ALREADY BLOCK SOME CODE BUT I CANT COPY AND PASTE IT WITH SHORTCUT CTRL+C AND CTRL+V.   I ALSO CANNOT USE CTRL+A FOR SHORTCUT

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G  (4 x 2695)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.46GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-go-syntax|dun|0.0.18
vsc-material-theme|Equ|30.0.0
python|ms-|2019.11.50794
Go|ms-|0.11.9
vs-keybindings|ms-|0.2.0
material-icon-theme|PKi|3.9.2
python|tht|0.2.3
vim|vsc|1.11.3

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@Gunawanart uninstall or disable the vim extension. It appears you actually do not want vim mode, despite the fact that you installed the vim extension 🤷.
