### ISSUE TITLE
how to connect to remote os's docker

### ISSUE THREAD

**Issue by qcq** [microsoft/vscode#86236]
I have a requiremnt, which my code can only build under redhat, but I have debian,, and my work pc is  windows, if visual stdio support from my pc to connect the debian's redhat docker.

**Comment by chrmarti** [comment]
Take a look at the Remote-Containers extension. That allows you to develop inside a container.

Extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
There are a few samples: https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-dev-container

**Comment by qcq** [comment]
seems my question unclear,
A, my pc which is windows
B, my remote server which is debian
C, docker dev which is redhat hosted on debian.
so, the road map is how can I from A get the C online.
not connect with A's docker.

**Comment by qcq** [comment]
by the way, found a temp way, from A connect to B, C start with -v options, which can map the share folder with the B. then edit in A, compile in C.
Anyway, Thanks.

**Comment by chrmarti** [comment]
Connecting to a remote Docker host is documented here: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host

HTH
