### ISSUE TITLE
Hover information in package.json is mis-aligned

### ISSUE THREAD

**Issue by alexdevero** [microsoft/vscode#86239]
Issue Type: <b>Bug</b>

Hover over script or dependecy in package.json to show information bubble. The bubble should be above the dependency or script text. Now it is on the far right.

VS Code version: Code - Insiders 1.41.0-insider (43e3581aa635406ada2d8138d7ee242ddabefc1c, 2019-12-04T05:29:38.104Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.70GB free)|
|Process Argv|E:\devero-laboratories\my-experiments-and-projects\apps\trainerlog-web-app-landing-page|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.9.1
color-info|bie|0.5.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|1.9.1
javascript-ejs-support|Dig|1.1.3
es7-react-js-snippets|dsz|2.4.4
EditorConfig|Edi|0.14.2
prettier-vscode|esb|3.11.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
svg|joc|1.0.5
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.27
vscode-colorize|kam|0.8.15
wordcounter|kir|2.1.0
contextualduplicate|laf|0.2.0
vscode-language-babel|mgm|0.0.25
postcss-language|mhm|2.1.0
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.3.0
vscode-duplicate|mrm|1.2.1
language-gettext|mro|0.1.1
vscode-azureappservice|ms-|0.16.1
azure-account|ms-|0.8.7
vscode-react-native|msj|0.13.2
react-proptypes-intellisense|OfH|1.0.3
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
multi-command|ryu|1.3.0
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
code-spell-checker|str|1.7.20
code-spell-checker-czech|str|0.1.0
vscode-icons|vsc|9.6.0
WebTemplateStudio-dev-nightly|WAS|0.0.1929801
dictionary-completion|yzh|0.8.4
material-theme|zhu|3.2.0

</details>

Screen:
![vs code hover bug](https://user-images.githubusercontent.com/4237724/70127040-8ddb4480-167a-11ea-8d1e-446cac01a2e2.PNG)

**Comment by alexandrudima** [comment]
I have bisected this to 74ffa79

**Comment by alexandrudima** [comment]
I have reverted via https://github.com/microsoft/vscode/commit/7f1975a4fb29d0a788c21f17eb2aad056fec22d8 , new builds are running...

**Comment by alexandrudima** [comment]
A new insiders with the fix is now available.

**Comment by alexdevero** [comment]
Thank you @alexandrudima.
