### ISSUE TITLE
Search field autofocus issue

### ISSUE THREAD

**Issue by paulbennet** [microsoft/vscode#86234]
Issue Type: <b>Bug</b>

- Start a new global search ( Cmd + Shift + F )
- Focus 'files to include' input and type something
- Focus moves to 'Search' input automatically

Note: Seems only happens when 'Search' input is empty initially

VS Code version: Code - Insiders 1.41.0-insider (43e3581aa635406ada2d8138d7ee242ddabefc1c, 2019-12-04T05:26:19.040Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.83GB free)|
|Process Argv|-psn_0_249917|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-icalendar|af4|1.0.1
rtf|ale|2.1.0
vscode-sqlite|ale|0.8.0
vscode-json|and|1.5.0
markdown-preview-github-styles|bie|0.1.6
insert-unicode|bru|0.7.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
compulim-vscode-dictionary|Com|0.0.5
vscode-eslint|dba|1.9.1
binary-plist|dni|0.3.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.9
vsc-material-theme|Equ|30.0.0
flow-for-vscode|flo|1.5.0
macros|ged|1.2.1
sass-lint|gle|1.0.6
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
JSDocTagComplete|Hoo|0.0.2
path-autocomplete|ion|1.13.3
vscode-lebab|jer|1.0.5
bash-ide-vscode|mad|1.3.3
start-git-bash|McC|1.2.1
markdown-shortcuts|mdi|0.12.0
code-beautifier|mic|2.3.3
hg|mrc|1.3.0
vscode-lebab|mrm|2.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.2
resourcemonitor|mut|1.0.6
vscode-json-editor|nic|0.2.3
unicode-latex|oij|1.1.2
fix-json|oli|0.1.2
ant-tree-viewer|ped|0.3.2
material-icon-theme|PKi|3.9.2
remove-comments|pli|1.2.2
polacode|pnp|0.3.4
vscode-jsp|pth|0.0.3
java|red|0.53.1
datetime|rid|1.0.5
vscode-sass-format|sas|1.1.6
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.7.20
vscode-markdown-table-format|Tom|1.0.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-icons|vsc|9.6.0
vscode-todo-highlight|way|1.0.4
propertylist|zho|0.0.2

</details>

**Comment by paulbennet** [comment]
Though [issue 84768](https://www.github.com/microsoft/vscode/issues/84768) is almost the same, this occurred today for me, and I keep insiders version updated everyday.

**Comment by JacksonKearl** [comment]
Thanks for reporting! Will be fixed in the next release.
