### ISSUE TITLE
[scss] @use proposals: Don't use CompletionItemKind.Text

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86247]
Testing #85979

```
@use "";
```
- do code compete inside `""`.
- proposals `sass:color` and others use the textual icon.

->Should only be used for textual (non-context aware) proposals

**Comment by wongjn** [comment]
What would be a better alternative here? The definitions for the builtins are all in [scssCompletion.ts](https://github.com/microsoft/vscode-css-languageservice/blob/82c0079a3c4a8cd2045e767e41f81c80abb52f85/src/services/scssCompletion.ts#L216).

**Comment by octref** [comment]
@wongjn `Module` kind. I went ahead to change it.

Verifier: Verify you see module icon in completion

![image](https://user-images.githubusercontent.com/4033249/70191138-af552400-16ac-11ea-81dd-6f84790e09ca.png)
