### ISSUE TITLE
Make breakpoint candidates less noisy

### ISSUE THREAD

**Issue by Hagay-Reinman** [microsoft/vscode#86242]
- VS code : 1.40.2:
- Ubuntu 18.04.3 LTS :

Steps to Reproduce:

1. Create any break point
2. See that 2 or more icons of break point is shown in the editor, see attached picture.
![Selection_100](https://user-images.githubusercontent.com/45554685/70129770-0bf21800-1688-11ea-8398-f5738e697347.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Those are breakpoint candidates. On which you can click to add a breakpoint.
Renaming this issue to make breakpoint candidates less intrusive.
We should add opacity and decrease the size they take. They should be less noisy
