### ISSUE TITLE
Emmet abbreviation shown above list of CSS property completions 

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#86249]
Testing #85968
Issue Type: <b>Bug</b>

Invoke CSS property completion by typing 'a' inside a selector.

Expect to see the top item in the completion list - align-items. Instead see align-self at top of the list (this is an emmet abbreviation).

![image](https://user-images.githubusercontent.com/1704059/70133509-2a531600-167e-11ea-9902-061553ab2b4a.png)

Same discrepancy when typing b, f, o, and v instead of a (the emmet abbreviation at the top of the list doesnt match the item underneath).

For all other letters, the emmet abbreviation does match the item underneath.

VS Code version: Code - Insiders 1.41.0-insider (43e3581aa635406ada2d8138d7ee242ddabefc1c, 2019-12-04T05:29:38.104Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by octref** [comment]
@aeschli I also didn't like this, but I don't have confidence to get rid of it. This can be controlled by `"emmet.showAbbreviationSuggestions": false`.

Do you think we should default it to false?

**Comment by aeschli** [comment]
Can you find out why it is on top? Did emmet boost the sort order?
Ideally it comes after `align-self`

I'm not opposed to `"emmet.showAbbreviationSuggestions": false` but there will be users that complain.

**Comment by octref** [comment]
Here are the abbreviations:

```
as => align-self:;
as:a => align-self:auto;
as:b => align-self:baseline;
as:c => align-self:center;
as:fe => align-self:flex-end;
as:fs => align-self:flex-start;
as:s => align-self:stretch;
```

I think a good logic could be, if it's an exact abbreviation, put `emmet` on the top. Otherwise hide it.

When I did the Chrome ranking work, I put custom `sortText` on each item, and that emmet completion with `a` ranks higher than all of them.

**Comment by octref** [comment]
Let me see if I can find a clean solution for November...

**Comment by octref** [comment]
I don't think there's a perfect solution: what if the user is exactly looking for `align-self: auto`?

When you type `as`, Emmet's `align-self` is on top.
When you type `ali`, CSS `align-self` is on top.

I think that's ok. When you have typed only `a`, whichever one we put on top will frustrate the other half users.

**Comment by octref** [comment]
Fixed this way: https://github.com/microsoft/vscode/issues/86941#issuecomment-565639404
