### ISSUE TITLE
Search Editor Preview: Support syntax highlighting

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#86241]
#23931

|    Expected     |  Actual         |
| ------------- |-------------|
| ![Screenshot (105)](https://user-images.githubusercontent.com/9638156/70135342-f3d7c400-169a-11ea-8e28-b21fa49fa354.png)    | ![Screenshot (106)](https://user-images.githubusercontent.com/9638156/70135362-fcc89580-169a-11ea-8e09-828773bf0493.png)  |

**Comment by JacksonKearl** [comment]
To verify: run a search that has results in a variety of files (searching in `colorize-fixtures` in vscode works well). Test with and without context `Search Editor: Search Again (with Context)`. When in `with context` mode, each group of contiguous lines should be an independent semantic region (modifying a line in a block affects lines below it in the same block), when searching without context, a line's contents should not affect the lines around it.
