### ISSUE TITLE
Restart frame: make it less nervous

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86248]
As pointed out by @jrieken 

Verified tho I have noticed that this makes the call stack view quite nervous - I believe that's because the hide the filename and line/column information on hover
Would it be possible to not have either or but to have the restart button push the details to the left?

Plan to experiment with flex and overflow.

**Comment by isidorn** [comment]
I have changed the ux a bit that on hover only the line numbers get hidden, not the whole file name. IMHO this makes it much less nervous. Please try it out and let me know how it feels. Thanks!

![restart](https://user-images.githubusercontent.com/1926584/72743036-2ab25c80-3bab-11ea-8efa-603de9417121.gif)

**Comment by weinand** [comment]
Much better now.
