### ISSUE TITLE
Search Editor Preview: Highlight file in paths

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#86240]
Example is WebStorm's finder screenshot from https://github.com/microsoft/vscode/issues/23931#issuecomment-468454610

![53601335-d4df5b00-3b79-11e9-9374-d2f5b04c2f5c - Copy](https://user-images.githubusercontent.com/9638156/70129045-1c59c100-168f-11ea-84b2-f9f5ace0ac65.png)

Or Better Search extension

![search](https://user-images.githubusercontent.com/9638156/70129477-d9e4b400-168f-11ea-9830-84784046de74.png)

**Comment by JacksonKearl** [comment]
Going to bundle this with #86317 to generally add more scopes to the search result grammar.
