### ISSUE TITLE
Markdown Side Preview disappearing when *.md tab in focus/edited

### ISSUE THREAD

**Issue by lukas-runge** [microsoft/vscode#86245]
Note: This does not occur when using stable version, just insiders.

- VSCode Version: 1.41.0-insider
- OS Version: Linux x64 5.0.0-37-generic

Steps to Reproduce:

1. create test.md
2. open side preview
3. edit test.md
4. preview disappears

Does this issue occur when all extensions are disabled?: Yes

**Comment by lukas-runge** [comment]
New vs code insiders version just dropped - I installed it and it fixed the issue. Thanks you guys ;-)

**Comment by ddzy** [comment]
Same issue...

版本: 1.41.0-exploration (user setup)
提交: 22c3db00ec057fecf0144c4c7f8c6bc6cb60e5d6
日期: 2019-12-03T21:30:12.474Z
Electron: 7.1.3
Chrome: 78.0.3904.126
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
