### ISSUE TITLE
Python Interactive Window Disappears When Clicking Left Side after latest insider update

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/vscode#86246]
![gifhome_1920x1040_7s](https://user-images.githubusercontent.com/44701446/70132442-33180c00-16bf-11ea-9cb1-6f4eaff2a5d1.gif)

I think this is VsCode's Problem not the python team's. After I upgraded the latest version hours ago, it happened as shown above. Even when I press `shift+enter` to run cell, the Interactive Window doesn't show up unless I click the right side.

**Comment by mjbvz** [comment]
Please start by filing this against the python extension
