### ISSUE TITLE
VSCode force opening window on error

### ISSUE THREAD

**Issue by fortydegrees** [microsoft/vscode#86252]
I'm developing a react native app that uses typescript. Whenever I run the app and it encounters an error, VSCode forces focus and opens up a file in node_modules.

This is really annoying as I have to scroll all the way up the file list and collapse the node_modules folder, and then navigate back to the original window I was working on. I've looked around and haven't been able to find a page describing this issue or how to stop it. What's going on here and how do I stop it from happening?

**Comment by IllusionMH** [comment]
Are you sure you don't have checked "All Exceptions" and "Uncaught Exceptions" checked in Breakpoins section?

**Comment by fortydegrees** [comment]
Not that I know of. Not for VSCode (which doesn't show anything in Breakpoints section) or for Chrome Dev Tools

**Comment by isidorn** [comment]
Please use the following setting `"debug.focusWindowOnBreak": false`
