### ISSUE TITLE
Electron 7: going full screen makes the whole screen flickr

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86256]
Refs: https://github.com/microsoft/vscode/issues/85994

Catalina, Electron 7.1.3

1. Make sure to have "window.nativeFullScreen": true
2. Go to full screen -> the transition is not smooth, there is a flash of black screen for a moment

The full screen transition for my current chrome 78 is much more smoother

**Comment by bpasero** [comment]
@isidorn I cannot reproduce this with today's insider build (which comes with E7). Can you try again?

**Comment by isidorn** [comment]
I can reproduce on my machine.

**Comment by bpasero** [comment]
Oh yeah, I see it too. I was accidentally trying with the simple fullscreen. I see a brief flash of white.

**Comment by isidorn** [comment]
Exactly!

**Comment by Al-Ferguson** [comment]
Could this be Electron [#21750](https://github.com/electron/electron/pull/21750)? Which was fixed in Electron 7.1.9.

**Comment by bpasero** [comment]
Yeah, we still have not yet updated, but maybe @isidorn could try this running out of sources by changing our `.yarnrc` to 7.1.9.

**Comment by bpasero** [comment]
@isidorn does this still happen in latest insider for you?

**Comment by isidorn** [comment]
No. Now it behaves fine. Thus closing.
