### ISSUE TITLE
Maximize button doesn't work correctly

### ISSUE THREAD

**Issue by cankush625** [microsoft/vscode#86258]
- VSCode Version: 1.40.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. When the maximize button is clicked, it is expected that the application windows must be maximized and when clicked again it will toggle.

Does this issue occur when all extensions are disabled?: Yes

The Autohide taskbar is enabled.

**Comment by IllusionMH** [comment]
Most likely duplicate of #81102

@cankush625 please update to latest version 1.40.**2** it should contain the fix and close issue if it work correctly with latest version.

**Comment by cankush625** [comment]
Yes, the new version 1.40.2 fixed it.
Closing the issue.
