### ISSUE TITLE
Intellisense for trimStart() and trimEnd()

### ISSUE THREAD

**Issue by s-e1** [microsoft/vscode#86250]
Issue Type: <b>Feature Request</b>

Intellisense doesn't show trimStart() and trimEnd().

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
You need to set a higher `target` or `lib` version in the jsconfig or tsconfig: https://code.visualstudio.com/docs/languages/jsconfig
