### ISSUE TITLE
Electron 7: going simple full screen turns everything white

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86255]
Refs: https://github.com/microsoft/vscode/issues/85994

macOS, Catalina, electron exploration build

1. "window.nativeFullScreen": false
2. Go full screen -> whole screen is white and code is unusable

Due to the severity of the issue adding label important

![fullScreen](https://user-images.githubusercontent.com/1926584/70136311-0991bd00-168c-11ea-8b2d-db0dbee91dce.gif)

**Comment by bpasero** [comment]
@isidorn I cannot reproduce this with today's insider build (which comes with E7). Can you try again?

**Comment by isidorn** [comment]
@bpasero I also can not reproduce, so this seems to have been fixed.
