### ISSUE TITLE
Firefox on macOS: drag-n-drop to desktop doesn't work

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86257]
Testing https://github.com/microsoft/vscode/issues/85987 in Firefox on macOS:

Dragging a file from the VS Code explorer to the desktop results in some `vscode-remote-//localhost-80` link.

This works fine in Chrome.

**Comment by isidorn** [comment]
This feature is currently implemented that it uses the chrome transfer protocol.
We would have to see what is needed so that firefox supports this.
