### ISSUE TITLE
Javascript error main process

### ISSUE THREAD

**Issue by ThomasRoca** [microsoft/vscode#86266]
Issue Type: <b>Bug</b>

I cannot open VScode clicking on its icon or when opening a file associated to it. For some reason, i can open it when right clicking on the icon and selecting open a New Window

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.47GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
nbpreviewer|jit|1.2.2
vscode-azureappservice|ms-|0.16.1
mssql|ms-|1.7.1
python|ms-|2019.11.50794
azure-account|ms-|0.8.7
vscode-json-editor|nic|0.2.3
vscode-sql-beautify|sen|0.0.4
WebTemplateStudio-dev-nightly|WAS|0.0.1925201

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
