### ISSUE TITLE
Highlight still appers different colors

### ISSUE THREAD

**Issue by alexalannunes** [microsoft/vscode#86261]
Issue Type: <b>Bug</b>

Today I updated my VSCODE and, again, In my editor appered two highlight background color.
In the old days I had this problem before, and it was fixed changing some configs!
in /usr/share/applications/code.desktop

I had to put `--disable-gpu` nit the code.desktop file

Follow:
https://github.com/microsoft/vscode/issues/84690#issuecomment-554008427

In this release, I had to do again

I'd like to know the why this is happening

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2573)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (1.08GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.11.0
mithril-emmet|Fal|0.7.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
mongo-runner|Joe|0.5.8
vscode-phpfmt|kok|1.0.30
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
vscode-typescript-tslint-plugin|ms-|1.2.3
sqltools|mtx|0.21.3
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.2
phpdoc-comment-vscode-plugin|rex|1.1.0
RocketseatReactJS|roc|2.2.0
RocketseatReactNative|roc|2.2.0
vscode-sql-beautify|sen|0.0.4
markdown-preview-enhanced|shd|0.5.0
vscode-counter|uct|1.3.1
vscode-icons|vsc|9.6.0
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
The HW accelerated rendering support comes from chromium, and especially on certain linux distributions it doesn't work well often, might be due to graphic cards etc,

Please don't edit the .desktop file, it will be updated and your changes will be lost. Also vscode will never disable HW acceleration support by default.

However, you can do this in a less harmful way on your end by 

```
If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
```
