### ISSUE TITLE
can't reach hidden task bar with position top when vscode window maximized

### ISSUE THREAD

**Issue by Ahmed-Elswerky** [microsoft/vscode#86260]
- VSCode Version:1.40.2
- OS Version:windows_NT x64 10.0.18362

Steps to Reproduce:

1.open vscode
2.maximize it's window

Does this issue occur when all extensions are disabled?: Yes

I set my task bar to hidden and when mouse reaches the top, it displayes, this works fine with all programs, but only the latest two updates in vscode that this not happening

**Comment by sbatten** [comment]
This sounds like a duplicate, but @deepak1556 has the issue link

**Comment by deepak1556** [comment]
Yeah this is https://github.com/microsoft/vscode/issues/84342 , but it should have been fixed with `1.40.2` , @Ahmed-Elswerky what is your screen setup and resolution ? Can you also attach a video demo. Thanks!

**Comment by deepak1556** [comment]
Okay this seems to happen only for the case where the taskbar is autohidden on top, works fine for `left, right, bottom`.

@Ahmed-Elswerky can you confirm if you are setting your taskbar position to top of your screen ?

**Comment by Ahmed-Elswerky** [comment]
yes on the top

**Comment by deepak1556** [comment]
Thanks for confirming.

**Comment by codestothestars** [comment]
As with the linked/related issues, this one only occurs for me when using `"window.titleBarStyle": "custom"`. The issue disappears when using `native` instead.

**Comment by Ahmed-Elswerky** [comment]
@codestothestars  I think this is a workaround , but that solved it

**Comment by Nemric** [comment]
Same problem here.
Taskbar on top with auto hide and latest version 1.42.1 (for now) 

I haves to press F11 twice to make it working as expected (Taskbar appear on top when mouse reaches the top) with default `"window.titleBarStyle": "custom"`

**Comment by Prehistoricman** [comment]
Electron has closed this issue 3 times now. It seems they don't want to fix it or believe that it is fixed:
https://github.com/electron/electron/issues/5990
https://github.com/electron/electron/issues/8546
https://github.com/electron/electron/issues/9193

**Comment by deepak1556** [comment]
@Ahmed-Elswerky can you check if this still an issue with latest insiders https://code.visualstudio.com/insiders/. Thanks!

**Comment by deepak1556** [comment]
Should be fixed with latest insiders, please check.

**Comment by Prehistoricman** [comment]
Looks good! Thanks.

**Comment by 0x5c** [comment]
When will this be part of the main release channel?
