### ISSUE TITLE
Live update to log files in editor

### ISSUE THREAD

**Issue by tdmiller1** [microsoft/vscode#86279]
# Issue: Stale Log File View
### More Detail: 
It would be really nice to have the IDE automatically update file changes to .log files. For debugging live changes instead of after the file is completely written. There is a hacky way to do it now by clicking off window and clicking back on. But it would be really nice for basically a "live refresh" of files. Thank you.
VS Code Version: 1.40.1

**Comment by octref** [comment]
Please open issue for the extension you are using for debugging live changes.

**Comment by tdmiller1** [comment]
I just want to say that I am not using an extension. I just want the IDE to auto update its view when a file changes that wasn't caused by that IDE. @octref

**Comment by octref** [comment]
But this is limited by file system change events. There's no way for VS Code to get "live updates" from your file system. We can only poll for changes, and doing it too often causes slowness.
