### ISSUE TITLE
Chinese can't trigger suggestion in registerCompletionItemProvider 

### ISSUE THREAD

**Issue by garygao12580** [microsoft/vscode#86276]
- VSCode Version:
1.40.2
- OS Version:
Darwin x64 19.0.0

Steps to Reproduce:
I develop a IntelliSense VsCode extension which is triggered by some Chinese characters, but it not  work.
```tsx
const triggers = ['哈', '我'];
const provider = vscode.languages.registerCompletionItemProvider(['typescriptreact', 'typescript', 'javascript', 'javascriptreact'], {
		async	provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
 ...
		}
	}, ...triggers);
```

**Comment by garygao12580** [comment]
When will this feature be released?

**Comment by jrieken** [comment]
Should be in current insiders and will be in next stable (1.42). Can you give it a try with insiders https://code.visualstudio.com/insiders/, I have tested with with characters like ü, ê but not will all complex characters

**Comment by garygao12580** [comment]
Thank you very much. I will try it soon.

**Comment by rebornix** [comment]
I didn't get it to work with completion extension sample https://github.com/microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts#L68 , I used `哈`, `:`, `.` as trigger characters but `哈` doesn't work.

**Comment by jrieken** [comment]
@rebornix How is that character typed? Via composition? That's the only thing we current support and I could only test/verify that with `¨ + u -> ü`

**Comment by rebornix** [comment]
@jrieken that's through composition but the way it works might differ from inserting characters with accent:

* Switch to English IME on macOS
* Insert `console`
* Ctrl+Space to switch IME (which is the keybinding on my macOS) to Chinese 
* Press `ha` and then press space to choose the first character, which will finally insert `哈` into the editor

**Comment by jrieken** [comment]
This actually works all fine @rebornix The issue you have encountered is that your sample is triggered on 哈 but it doesn't return any suggestion that matches on 哈, e.g all completions are filtered out. Try with a provider like this

```
vscode.languages.registerCompletionItemProvider('plaintext', {
		provideCompletionItems(doc, pos) {
			const wordRange = doc.getWordRangeAtPosition(pos);
			if (wordRange) {
				const item3 = new vscode.CompletionItem(doc.getText(wordRange) + 'hallo_test');
				return [item3]
			}
		},

	}, 'ü', 'ß', 'ë', '哈')
```
