### ISSUE TITLE
[semantic tokens] Use singular for token type names

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#86281]
Testing #85972

I have written quite a number of parsers, and so far I never used terms like this is "comments", this is "classes", etc. 

I find the choice to use plurals in built-in token types a bit surprising.

**Comment by aeschli** [comment]
It's more related to styling

I chose plural as we already have the setting
```
	"editor.tokenColorCustomizations": {
		"comments": "#FF0000",
		"keywords": "#FF0000",
		"strings": "#FF0000",
		"types": "#FF0000",
		"functions": "#FF0000",
		"numbers": "#FF0000",
		"variables": "#FF0000"
	},
```
and my goal is to bring this together.

**Comment by alexandrudima** [comment]
I see how this was driven, and in the coloring context that makes sense: "I want to color comments in red". But I still think writing a parser and returning plurals is very different than what I have seen/done so far. Could we look at some language ASTs, is anyone using plurals?

**Comment by aeschli** [comment]
The token names are not user facing, while the settings are. So while I agree that plurals are unconventional and even a bit weird, are not a real problem.

That said, deprecating the current setting names is also possible.

**Comment by alexandrudima** [comment]
@aeschli Two final points.

1. IMHO the tokens that we are proposing impact more than VS Code since I think we want to add them to the LSP, so using plurals because of an existing VS Code configuration option is a bit forcing... 

2. Interesting, the same problem exists in CSS. Given the HTML:
```html
<div class="title">Title 1</div>
<div class="content">Content 1</div>
<div class="title">Title 2</div>
<div class="title">Content 2</div>
```

The CSS is `.title` and not the plural `.titles` even if multiple elements are targeted:
```css
.title { color: red }
```

**Comment by aeschli** [comment]
Making the change as we want to mention the new API in the release notes so that others can try it out.
