### ISSUE TITLE
Sync: Extension notification overload

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#86285]
<img width="75%" src="https://user-images.githubusercontent.com/35271042/70163394-3df97f00-1674-11ea-9bdc-a67564203f22.png" />

After setting up Sync I was bombarded with **6 notifications** from Extensions and is a jarring setup experience. It would be great if there was a way to suppress these when sync is setting up because in theory the user has already seen these from the previous machine.

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/83451

**Comment by misolori** [comment]
@sandy081 #83451 is talking about welcome experiences for specific extensions. This issue is about all fo the notifications popping up at the same time.

**Comment by sandy081** [comment]
I think both of them are talking about same. Currently there is no way that an extension knows when and when not to show their welcome pages or notifications. Description of the other issue says:

> Hi, it would be great if there was an "onExtensionInstalled" activation event that would trigger when a VS Code extension is first installed.

both of these are talking about similar issue except that here extension got installed automatically. At the end, we have to provide a better welcome experience and able to control it.

**Comment by misolori** [comment]
Ok that makes sense, I'll drop a note to make sure it also covers extensions installed automatically via Settings Sync.
