### ISSUE TITLE
Settings UI links to settings don't work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86289]
Clicking this:

![image](https://user-images.githubusercontent.com/2193314/70164490-19060b80-1676-11ea-9bfe-447a12d3f868.png)

Just removes the filter:

![image](https://user-images.githubusercontent.com/2193314/70164515-258a6400-1676-11ea-9acc-02af7814a868.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/67479
