### ISSUE TITLE
Sync: Unable to re-trigger sign in after closing browser tab

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#86284]
<img width="50%" src="https://user-images.githubusercontent.com/35271042/70162760-0e964280-1673-11ea-8df7-dab5cf0229a6.png">

1. Enable sync
2. Close browser tab that was opened by Sync
3. Go back to VS Code and attempt to turn on sync again
4. :bug: Unable to sign in again as sign in button is disabled

**Comment by sandy081** [comment]
@RMacfarlane Seems the auth stuck at signing in.

**Comment by RMacfarlane** [comment]
This is tricky, I don't think there's a way for us to know that the browser was closed. There's a timeout of 5 minutes after which auth will fail, which should reset the UI. Maybe we could keep the "Sync: Signing in..." option enabled to allow retriggering auth?

**Comment by Amares03** [comment]
#86284

**Comment by misolori** [comment]
@RMacfarlane having the `Sync: Signing in...` field enabled to re-trigger the auth would work for me.

**Comment by RMacfarlane** [comment]
The badge no longer changes to the clock icon when you start sign in, so it should always be possible to trigger sign in again
