### ISSUE TITLE
[semantic tokens] The concept of "-" minus feels weird

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#86282]
Testing #85972

The concept of removing a fontStyle is super weird.

For example:
```
"*.static": {
  "fontStyle": "italic"
},
"*.abstract": {
  "fontStyle": "underline-italic"
}
```

![image](https://user-images.githubusercontent.com/5047891/70161267-13cbaf80-16bc-11ea-804b-f61884b5cd3f.png)

That just reads as if I asked for underline and italic, but it means underline, remove italic if set. IMHO this is super complex and foreign coming from TM grammars / CSS styling...

**Comment by alexandrudima** [comment]
Also, the `none` appears to be broken: 
![image](https://user-images.githubusercontent.com/5047891/70161385-48d80200-16bc-11ea-84cc-9467b74932f9.png)

```
        "*.static": {
            "fontStyle": "italic"
        },
        "*.abstract": {
            "fontStyle": ""
        },
```

![image](https://user-images.githubusercontent.com/5047891/70161450-5e4d2c00-16bc-11ea-9ee2-1aa4388454eb.png)

**Comment by aeschli** [comment]
I see wht you say. I chose that as plural makes sense for the styling, in the settings.

we already have
```
	"editor.tokenColorCustomizations": {
		"comments": "#FF0000",
		"keywords": "#FF0000",
		"strings": "#FF0000",
		"types": "#FF0000",
		"functions": "#FF0000",
		"numbers": "#FF0000",
		"variables": "#FF0000"
	},
```
and my goal is to bring this together.
