### ISSUE TITLE
Firefox: Menu items move on click with trackpad

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#86296]
Testing #85987

<img width="75%" src="https://user-images.githubusercontent.com/35271042/70168432-ba449000-167d-11ea-9678-e055506609ce.gif">

😁This appears to affect all menu items, including context menus

**Comment by bpasero** [comment]
I cannot reproduce this anymore.

**Comment by misolori** [comment]
@bpasero did you test this on a trackpad? I am still seeing this:

![Kapture 2020-02-27 at 13 25 18](https://user-images.githubusercontent.com/35271042/75488150-a6e74f00-5964-11ea-9689-19eb06984721.gif)

**Comment by sbatten** [comment]
does not repro in latest FF for me https://github.com/microsoft/vscode/issues/86296

**Comment by misolori** [comment]
Confirmed that it also does not repro anymore.
