### ISSUE TITLE
Install language pack on remote?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86293]
Testing https://github.com/microsoft/vscode/issues/85948

![image](https://user-images.githubusercontent.com/2193314/70166418-90896a00-1679-11ea-9e06-704ca9633a7d.png)

I haven't been using a language pack for long but not sure if this is expected? Should language packs strictly be ui extensions?

**Comment by sandy081** [comment]
No, language packs are special extensions which have to be installed on both sides because they contain translations for both core and extensions.
