### ISSUE TITLE
Workbench Notification Improvements

### ISSUE THREAD

**Issue by gardner** [microsoft/vscode#86295]
Please allow batching of workbench notifications into their own page, much like the "Welcome page". These types of pop-up toast notifications are [not accessible](https://github.com/microsoft/vscode/issues/46676#issuecomment-428097380) and they steal attention away from developers and force them to focus on something that may or may not be more important than the work at hand.

Ideally, the bell icon in the bottom right would change colour/weight when there are notifications. When a user clicks the bell icon, then the notifications are shown in their own page, not as a list of pop-ups.

An existing issue where this is being tracked was not found. Issue https://github.com/Microsoft/vscode/issues/51240 was closed and @bpasero invites us to review a tag: https://github.com/Microsoft/vscode/labels/workbench-notifications
This list brings us to issue https://github.com/microsoft/vscode/issues/46676 which discusses disabling temporarily and permamently disabling these messages. That issue includes some hacks to forever hide the notification pop-ups. The information in these pop-up workbench notifications may be useful. The control of when and how this information is delivered should be configurable. At some times it is not worth stealing attention away from a developer. The attention cost is too high to have these notifications showing up and taking up so much real estate, not self-dismissing, and requiring user-interaction. Especially when it happens multiple new projects, many times per day.

Please add a mode where the notifications are stored and queued until the developer clicks the bell icon in the bottom and is ready to review them. To maximise accessibility and screen reader functionality, ideally this list would appear in its own window, not as a series of popup windows.

Thank you for accepting my feature request.

**Comment by bpasero** [comment]
@gardner can you please explain how notifications are not accessible when you open them from the notification center?

To summarise this request, you want:
* to hide all notification toasts and only see the status bell icon changing
* have an experience to manage notifications all at once from an experience such as the welcome editor

Is that accurate?

And if so, what is the exact advantage of managing notifications in the editor vs. the notifications center?
