### ISSUE TITLE
Request: Git features should be available when working on a project that's below the git repo root

### ISSUE THREAD

**Issue by photex** [Microsoft/vscode#863]
Howdy!

Due to some unfortunate circumstances I'm currently stuck working on a project that's a subdirectory in part of a larger git repo. To open the entire repo directory would be a bit of a pain as well. I can work on the project just fine otherwise but none of the git features are currently available which is a disappointment.

What's preventing Code from being able to use Git regardless of the opened project folder location (relative to the git root)?

The contrived example layout:

```
/projects/engine/ <--- root of the repo
/projects/engine/tools/my_application/ <--- here sits a package.json, gulpfile.js, etc etc
```

**Comment by joaomoreno** [comment]
This is actually already implemented, will come with the next update! Duplicate of #57

**Comment by photex** [comment]
That is awesome @joaomoreno! :open_mouth:

**Comment by joaomoreno** [comment]
:tada:

**Comment by Stanzilla** [comment]
Sneak in https://github.com/Microsoft/vscode/issues/507 while we are at it? :)
