### ISSUE TITLE
Toggling comment requires multiple undos in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8630]
- selfhost
- open tabstitle.css https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/media/tabstitle.css#L71
- invoke keybinding to toggle comment
- Undo

=> for me it does not undo directly, but I need more than one undo invocation

@alexandrudima fyi

**Comment by alexandrudima** [comment]
@bpasero I cannot reproduce:

To clarify, I press `ctrl+/` followed by `ctrl+z` on Windows:

![ctrl-slash](https://cloud.githubusercontent.com/assets/5047891/16769023/780798e0-484f-11e6-8df0-c56b1db70a7f.gif)

**Comment by bpasero** [comment]
@alexandrudima ok seems to work good now, I wonder if we fixed something in this area. Could it have been Emmet?

**Comment by alexandrudima** [comment]
AFAIK emmet only kicks in when pressing `Tab`, so it is unlikely. I didn't make any changes in the comment line commands either, so I don't really know...

**Comment by bpasero** [comment]
Ok, so feel free to close this. Though I can remember that I had another case where undo was not working at first, really no clue how to reproduce but will keep an eye open.
