### ISSUE TITLE
Call Hierarchy view should show both incoming & outgoing at the same time

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#86306]
Issue Type: <b>Bug</b>

I found it confusing that the peek and view remember the direction. While there is an aspect to that which is nice (and probably desirable). It felt strange to me, that when I opened the peek it had defaulted to `Calls from`, but on the same keyword using show it has defaulted to `Callers of` and I was confused for a minute about why I was seeing different data.

IMO, I think it would be nicer if the view instead of being a toggle, it just had 2 root nodes -- one for `Calls from 'foo'` and `Callers of 'foo'`. That way there would be no disconnect from the peek to the view and the view would be showing even more information at the same time.

Refs: #85924

VS Code version: Code - Insiders 1.41.0-insider (7f1975a4fb29d0a788c21f17eb2aad056fec22d8, 2019-12-04T10:20:42.228Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
See https://github.com/microsoft/vscode/issues/16110#issuecomment-471951544 more background on this. We have explored the double-direction approach in March but didn't continue on it because we figured it makes things complex without adding value. Actually, VS did the same and they simplified their call hierarchy UX a few year back which influenced this but it also felt bad because each node get more children
