### ISSUE TITLE
Custom dialogs use greyscale aa

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#86309]
![image](https://user-images.githubusercontent.com/6561887/70174900-9b98c600-168a-11ea-9729-9ffe1aa67106.png)
refs #85143

**Comment by bpasero** [comment]
Similar explanation as https://github.com/microsoft/vscode/issues/86338#issuecomment-562854975, there is a `box-shadow` in use and no background applied. I am not entirely sure how we could get LCD rendering to work with `box-shadow` boxes. Possibly putting the contents of the dialog on its own GPU layer would help + setting an opaque background.

**Comment by sbatten** [comment]
I fixed this as described. Still... having to manage GPU layers is disappointing. Also, on my monitors, I actually prefer the non-RGB rendering :(

**Comment by bpasero** [comment]
Hm, I tested this on Windows (through a VM to be honest) running the web version and get only partial results:

![image](https://user-images.githubusercontent.com/900690/73371022-663cdd00-42b5-11ea-90a0-bb8e6649ae1d.png)

Can you confirm maybe natively?

**Comment by sbatten** [comment]
@bpasero native windows 
![image](https://user-images.githubusercontent.com/6561887/73373873-27376900-426e-11ea-97f0-6652c70de984.png)

**Comment by alexr00** [comment]
Agree with @bpasero that the details message in the custom dialog is greyscale on Windows when running **web**.

Is workbench.dialogs.customEnabled supposed to be a hidden setting?

**Comment by sbatten** [comment]
there's an issue to productize it. will look at this in feb.
