### ISSUE TITLE
Provide a context key for the selected debug mode

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#86302]
For https://github.com/microsoft/vscode-pwa/issues/125, I'd like to show the "browser breakpoints" rollout when we're actively debugging `pwa-chrome` _or_ when that debug type is selected. We currently have a `debugType` context key, but this is only set when a debug session is active, which would prevent users from being able to use the panel before the session starts and e.g. break on the page `load` event.

**Comment by isidorn** [comment]
There is a context key called `debugConfigurationType`. You can check it out.
Code pointer https://github.com/Microsoft/vscode/blob/a56829c2258accf1767c9a1137fa2a5cd545fedf/src/vs/workbench/contrib/debug/common/debug.ts#L41

**Comment by connor4312** [comment]
Perfect, thanks! It'd be neat to document our context keys a bit better -- at least, I didn't find many docs on them in a cursory Google.

**Comment by isidorn** [comment]
Agree.
@gregvanl do we have a list of all context keys somewhere where I could add these?

**Comment by gregvanl** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings#_contexts

Our published when clause context list isn't exhaustive by design so consider whether this context is likely to be useful for end users or is for our internal use.
