### ISSUE TITLE
Call Hierarchy provider - Failed to show call hierarchy

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#86300]
Issue Type: <b>Bug</b>

Using the [sample](https://github.com/microsoft/vscode-extension-samples/tree/master/call-hierarchy-sample) and playing around (not sure on steps) the provider started showing `Failed to show call hierarchy` in the peek, but the sidebar just showed nothing (but an error notification). 

EDIT: Still not sure on the steps, but I've gotten it a few times when just playing around with the sample and maybe letting it sit for a bit in the background?

Here is what was in the console:

![image](https://user-images.githubusercontent.com/641685/70172633-14a21880-169f-11ea-85b4-d5150ef379cb.png)

It looks like the map couldn't be found in the cache here:
https://github.com/microsoft/vscode/blob/d6dae16f40614cacde62c70c7c465ac0f7b49cb0/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1220

Refs: #85924

VS Code version: Code - Insiders 1.41.0-insider (7f1975a4fb29d0a788c21f17eb2aad056fec22d8, 2019-12-04T10:20:42.228Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Hm... We do cache the last 10 models before disposing them and this error suggests that we somehow have a reference to a disposed "session"

**Comment by jrieken** [comment]
This does happen when you peek more than 10 times...
