### ISSUE TITLE
Semantic Tokens: Update TM scope inspector to include semantic coloring info

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86304]
Ref: #85976

Either a new command to add semantic coloring info here would be good.

This can be very useful for debugging my extension.

![image](https://user-images.githubusercontent.com/4033249/70173696-39d75c80-1688-11ea-908c-d65b93a0232e.png)

**Comment by alexdima** [comment]
This has been done by @aeschli

**Comment by octref** [comment]
LGTM, thanks!
