### ISSUE TITLE
Call Hierarchy phone icon doesn't fit the "vscode" style (imo)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#86305]
The phone feels too busy imo, and the incoming version has no hole in it
![image](https://user-images.githubusercontent.com/641685/70172992-e40eae80-169f-11ea-9973-87a678374d69.png)
![image](https://user-images.githubusercontent.com/641685/70173166-49fb3600-16a0-11ea-98ce-9dd02a5748d4.png)

Maybe something more like these but hollow: 
![image](https://user-images.githubusercontent.com/641685/70173664-503de200-16a1-11ea-90d4-24982daf7bb4.png)
![image](https://user-images.githubusercontent.com/641685/70173681-57fd8680-16a1-11ea-82ab-d4627999a1b5.png)

Also most of the icons in that row are over-bright (except for the collapse all -- maybe svg vs codicon?)

Refs: #85924

**Comment by eamodio** [comment]
I also find it hard (more so in the peek -- probably because of the colors) to tell the direction, because the phone is much more prominent than the arrow, while the arrow is the important part.

**Comment by misolori** [comment]
I think this is covered here: https://github.com/microsoft/vscode/issues/86125#issuecomment-561528551

**Comment by eamodio** [comment]
Ah OK, that issue seemed more about refresh vs phone icon, rather than the icon itself when I read it.

**Comment by eamodio** [comment]
@misolori also note in those screenshots the color difference between the first 3 icons and the collapse all. I think it might be svg vs codicons but it doesn't look good.

**Comment by misolori** [comment]
Thoughts on using these icons (it's part of the MDL icons):

![image](https://user-images.githubusercontent.com/35271042/70180475-f6371f80-1694-11ea-8773-31a021434e99.png)


![image](https://user-images.githubusercontent.com/35271042/70180456-ec152100-1694-11ea-90d0-e7ed694fe5c2.png)
