### ISSUE TITLE
References peek should have an action button to open in the view

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#86315]
I would love a button here to open the current peek in the view
![image](https://user-images.githubusercontent.com/641685/70176979-71093600-16a7-11ea-96f3-1698aac72835.png)

Related: #86313

**Comment by eamodio** [comment]
@jrieken what is this one a duplicate of?

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/73111

**Comment by eamodio** [comment]
Doh. It was even my own issue. Sorry! 😁

**Comment by SSJ9899TDylan** [comment]
LOL
