### ISSUE TITLE
Call Hierarchy peek should have an action button to open in the view

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#86313]
I would love a button here to open the current peek in the view
![image](https://user-images.githubusercontent.com/641685/70176793-17a10700-16a7-11ea-81d4-1367e85cb502.png)

Refs: #85924

**Comment by jrieken** [comment]
Handling as duplicate of the the two you have files - the main work packet is to make the menu bar of peek contributable.

**Comment by eamodio** [comment]
But the call hierarchy view already has a button for the to/from toggle how is this any different?

**Comment by jrieken** [comment]
peek is built into the product, the viewlet is an extensions so layering prohibits the 'easy fix' and it should be the extension contributing the commands to the peek toolbar
