### ISSUE TITLE
Semantic Tokens: Can't register new tokenTypes in `SemanticTokensLegend`

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86314]
Ref: #85976

Have this implementation:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const legend = new vscode.SemanticTokensLegend(['', 'functions', 'function'], ['']);
	const builder = new vscode.SemanticTokensBuilder();
	builder.push(0, 0, 3, 1, 0);
	builder.push(1, 0, 3, 2, 0);

	const result = new vscode.SemanticTokens(builder.build());

	vscode.languages.registerSemanticTokensProvider(
		'plaintext',
		{
			provideSemanticTokens() {
				return result;
			}
		},
		legend
	);
	
	vscode.languages.registerSemanticTokensProvider(
		{ language: 'css', scheme: 'file' },
		{
			provideSemanticTokens() {
				return result;
			}
		},
		legend
	);
}
```

And this setting:

```json
{
  "editor.tokenColorCustomizationsExperimental": {
    "functions": { "foreground": "#ff0000", "fontStyle": "bold" },
    "function": { "foreground": "#ff0000", "fontStyle": "bold" }
  }
}
```

`functions` work, but `function` doesn't.
It seems I can only register known `tokenTypes` in `SemanticTokensLegend`. Otherwise they have no colors.

![image](https://user-images.githubusercontent.com/4033249/70176978-4bbbfe00-168e-11ea-9239-4c591abdd520.png)

**Comment by Tyriar** [comment]
I was thinking maybe this was intentional to prevent extensions from inventing a bunch of inconsistent tokens and not turn into the mess that a lot of textmate grammars are now? A good example being functions and function.

**Comment by aeschli** [comment]
New tokens and modifiers can now be added through the `tokenType` and `tokenModifier` contribution points (along with descriptions and defaults)
