### ISSUE TITLE
Tasks inputs is not properly accepting commands

### ISSUE THREAD

**Issue by jemo07** [microsoft/vscode#86323]
Hello, I'm running into an issue after executing a task. The task is working correctly, but after adding the `${input:var}` and populating **inputs** as shown below. I tried several options, from executing other commands or a script in the root folder of the project, and it always provided an error that "command not found". Please see bellow.

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-24-generic snap
Steps to Reproduce:

1.Create a Task: builds tasks.json

2.Populate tasks.json as follows: 

```
{
            "label": "Flash Firmware",
            "group": "build",
            "type": "shell",
            "command": "idf.py",
            "args": ["-c","${input:setPort}","Flash"],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false
            }    
        }
    ],
    "inputs": [
        {
          "id": "setPort",
          "type" : "command",
          "command": "ls /dev/tty* | grep USB " }
        ]
}
``` 
Expected behavior is output from execution is `idef.py -c /dev/sttyUSB0 flash` 
Error received is ` command '/usr/bin/ls /dev/tty* | grep USB' not found`
I received this message even after adding the explicit path. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Commands are VS Code commands (for examples try running the Preference: Open Default Keyboard Shortcuts (JSON) command).

**Comment by jemo07** [comment]
Thank you, I see now this should be a shell type.
