### ISSUE TITLE
I do not load the interface

### ISSUE THREAD

**Issue by SergioFiloth** [microsoft/vscode#86324]
Issue Type: <b>Bug</b>

Download vs code for windows 7 32 bits and I did not load the vs code interface, I had to run the option to solve compatibility problems and I am running into Windows XP SP2, but I do not work several things of the text editor and neither the integrated console.

I ask for a quick solution, thank you very much.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:38.728Z)
OS version: Windows_NT ia32 5.1.2600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2388)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.73GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
beautify|Hoo|1.5.0
vscode-language-pack-es|MS-|1.40.2
material-icon-theme|PKi|3.9.2
LiveServer|rit|5.6.1
ayu|tea|0.18.0

</details>

**Comment by SergioFiloth** [comment]
It stays like that

![Captura](https://user-images.githubusercontent.com/58532720/70183546-fe528780-16b3-11ea-8612-8a3c8061e62f.PNG)

**Comment by gjsjohnmurray** [comment]
Per [this article](https://code.visualstudio.com/docs/setup/windows#_installation) have you confirmed your .NET Framework is 4.5.2 or later?

And per [this one](https://github.com/microsoft/vscode/issues/43169#issuecomment-539591825) the days of Windows 7 support seem to be numbered. After all, it goes EOL next month.

**Comment by SergioFiloth** [comment]
Yes, i have .NET Framework 4.5.2

![Captura 1](https://user-images.githubusercontent.com/58532720/70200595-0cb79800-16e2-11ea-9be8-a3eda0bb5d68.PNG)

**Comment by SergioFiloth** [comment]
> Según [este artículo, ¿](https://code.visualstudio.com/docs/setup/windows#_installation) ha confirmado que .NET Framework es 4.5.2 o posterior?
> 
> Y según [este,](https://github.com/microsoft/vscode/issues/43169#issuecomment-539591825) los días de soporte de Windows 7 parecen estar contados. Después de todo, termina el próximo mes.

**Comment by gjsjohnmurray** [comment]
Why are you running VS Code in Windows XP SP2 compatibility mode?

**Comment by SergioFiloth** [comment]
Because with the compatibility mode of Windows XP SP2 at least the graphic interface loads me, but without the compatibility mode it does not show me, although I know that the program opens because when doing a hover on some part there is content or a submenu show the title but you don't see anything.

**Comment by gjsjohnmurray** [comment]
Perhaps try launching with the `--disable-gpu` CLI argument

**Comment by SergioFiloth** [comment]
>Quizás intente iniciar con el --disable-gpuargumento CLI

Excuse me, how can I solve it? I don't know much about commands

**Comment by gjsjohnmurray** [comment]
Change the properties of the shortcut you launch VS Code from.

![image](https://user-images.githubusercontent.com/6726799/70235777-7fb12500-175b-11ea-8822-63ec7241c1b9.png)


Remember also to go to the Compatibility tab and turn off the compatibility mode you previously set.

**Comment by SergioFiloth** [comment]
Thanks friend, now everything works for me, including the integrated console, thank you very much.

Greetings from Colombia to @gjsjohnmurray and the entire VS Code team from Colombia.
