### ISSUE TITLE
"Conflict" message overlays resolution bar

### ISSUE THREAD

**Issue by snailbites** [Microsoft/vscode#8632]
- VSCode Version: 1.2.1
- OS Version: 10.10.5

Description: When a file is conflicted, the notification bar overlays needed information for the user to exit that state and potentially leads to a UX dead end. The reasons for this are two fold:

1) The notification bar will not close until you resolve the conflict; however...
2) In order to resolve the conflict, you have to use the resolution buttons on the right. But since the notification bar overlays relevant information, it is extremely difficult to see which file is which (ie. - which one is previous, which one is current) thus making it difficult to know which side to resolve to.

Steps to Reproduce:

1. Open any file in VS Code
2. Create a conflicted state on that file using git (ex. - edit the same line on a file that has recently changed on master, and rebase against master)
3. Observe the scenario similar to the attached screenshot.

<img width="1060" alt="screen shot 2016-06-29 at 11 38 27 am" src="https://cloud.githubusercontent.com/assets/6250972/16527706/5f204830-3f86-11e6-8538-57479009bfae.png">

**Comment by bpasero** [comment]
Fixed for 1.3 release.
