### ISSUE TITLE
Remote Explorer help links confusing

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#86328]
Testing https://github.com/microsoft/vscode/issues/85927

When testing, I connected to a container, then changed the dropdown of the remote explorer to SSH and clicked the help icon. After selecting one with a link, I noticed it was for Containers and not SSH.

I understand that if we aren't connected to a remote, asking can make sense. I also understand that not asking when we are using a specific type of remote can also make sense to remove that barrier.

However, I think that if the selected dropdown does not match the current session, this assumption is wrong. If I want help with SSH, I will select it in the dropdown and select the help icon. 

Either we always ask when the dropdown does not match the current session or we never ask and always show current dropdown's help.

**Comment by alexr00** [comment]
Always asking when the dropdown does not match the current session is a great idea.
