### ISSUE TITLE
Mouse cursor does not reset to "edit cursor" when discarding/closing context-menus

### ISSUE THREAD

**Issue by AndersenTobias** [microsoft/vscode#86320]
- VSCode Version: 1.40.2
- OS Version: macOS 10.15.1

Steps to Reproduce:

1. Right-click in an editor to bring up the context menu. Mouse cursor changes to pointer.
2. Click somewhere else to close the context menu. Mouse cursor is still a pointer and not the "edit cursor".

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
I think this might be specific to electron since we are talking native menus here.

**Comment by deepak1556** [comment]
I cannot repro this with latest stable, @AndersenTobias can you check if this still an issue ?

**Comment by AndersenTobias** [comment]
@deepak1556 Still an issue on macOS. I checked other apps to see if I get a similar behavior, and I don't. E.g. in the vanilla Terminal app, the cursor changes to the correct one on cursor movement, whereas VS Code has the same cursor regardless of movement.

Did you compare with other apps on your platform?
