### ISSUE TITLE
No tooltip when hovering link in terminal

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86325]
While testing https://github.com/microsoft/vscode/issues/84149, I noticed that the "cmd+click to follow link" tooltip is gone

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/70187006-16b9a680-16a2-11ea-8b23-1388c372cfa7.png)

**Comment by Tyriar** [comment]
<img width="159" alt="Screen Shot 2019-12-04 at 2 27 09 PM" src="https://user-images.githubusercontent.com/2193314/70187051-32bd4800-16a2-11ea-83c1-2ed92e828d85.png">

The location changed to the very left side to align with the editor, is that the problem?

**Comment by roblourens** [comment]
I am definitely seeing it now. Earlier it was not showing up at all...
