### ISSUE TITLE
Mac OS - Highlighting text in the editor requires two clicks when the integrated terminal is open

### ISSUE THREAD

**Issue by ckehoe** [Microsoft/vscode#8633]
- VSCode Version: 1.2.1
- OS Version: 10.11.5 (15F34) (El Capitan)

Steps to Reproduce:

1. Open a file in the editor
2. Open the integrated terminal
3. Type some commands on the terminal
4. Try to copy some text on the editor by highlighting and typing Mac + c
5. You will have to click on the section twice before the text successfully copies

**Comment by Tyriar** [comment]
Already fixed in v1.3.0.
