### ISSUE TITLE
Status bar doesn't use SPAA

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86339]
Testing #84715

![image](https://user-images.githubusercontent.com/2193314/70190817-d2cb9f00-16ab-11ea-97b8-23d30285f6ae.png)

**Comment by bpasero** [comment]
I cannot reproduce when disabling custom title bar so I suspect something in the title bar makes the status bar go greyscale...

**Comment by bpasero** [comment]
This is so random that I will not invest further, seems to work fine in some cases:

![image](https://user-images.githubusercontent.com/900690/70598034-31cc6f00-1bea-11ea-8b77-3f60716338a1.png)

**Comment by sbatten** [comment]
had the same experience, when testing with the custom menus enabled.
