### ISSUE TITLE
Notification center header does not use SPAA

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86338]
Testing https://github.com/microsoft/vscode/issues/84715

No text in notifications seem to be using SPAA

![image](https://user-images.githubusercontent.com/2193314/70190675-68b2fa00-16ab-11ea-9a17-2e8521044e37.png)

For the notifications list the message content works but not the NOTIFICATIONS header or the buttons

![image](https://user-images.githubusercontent.com/2193314/70190725-926c2100-16ab-11ea-8f50-eb022a6aa0d6.png)

**Comment by bpasero** [comment]
For toasts, not a lot I can do currently: https://github.com/microsoft/vscode/issues/85043#issuecomment-555376301

**Comment by Tyriar** [comment]
@bpasero is the problem that `opacity: 1` is set here?

https://github.com/microsoft/vscode/blob/4b394b938ec5f43fa3060746728df6ea460f49c2/src/vs/workbench/browser/parts/notifications/media/notificationsToasts.css#L40-L41

If so you could remove opacity from the base rule:

https://github.com/microsoft/vscode/blob/4b394b938ec5f43fa3060746728df6ea460f49c2/src/vs/workbench/browser/parts/notifications/media/notificationsToasts.css#L31

And create a `.hidden` rule with `opacity: 0` that it starts at?

**Comment by bpasero** [comment]
@Tyriar but we have an animation that fades the notification in that works with opacity. We could give that up, though there is still the animation that might break it. This is for notification toasts only.

**Comment by bpasero** [comment]
I have updated the summary. Fixing this for notification toasts means to disable the animation which I am not willing to. Still, the notifications center header not using SPAA is weird.

**Comment by bpasero** [comment]
The reason for this seems to be:
* a `box-shadow` on the container of the notifications center
* no background applied to the container

Since I am not easily giving up the box shadow, I am moving this to backlog. If someone has an idea for how to get the box-shadow to work while presering LCD rendering (and maybe without having to introduce another GPU layer), be my guest.
