### ISSUE TITLE
Semantic Tokens: Provide guidance for tokenType taxonomy

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86333]
Ref: #85976

Consider this case:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	new Bar();
}
```

- `import`, `as`, `from`, `export`, `new` are all `tokenType: "keyword"`
- Their scopes are:
    - `import`: `keyword.control.import.ts` -> purple
    - `as`: `keyword.control.as.ts` -> purple
    - `from`: `keyword.control.from.ts` -> purple
    - `export`: `keyword.control.export.ts` -> purple
    - `new`: `keyword.operator.new.ts` -> blue

Should I mark them all as `keyword` with different modifiers? Or should I mark, say, `new` as a new category `importantKeyword`, if I intend it to be marked with a different color, distinct from other keywords (but even if I do, theme authors need to mark them differently as well)?

The issue is:
- As tokenizer author, I don't know how much granularity should I provide for `tokenType`.
- As theme author, the new system seems to encourage more coarse taxonomy, making it impossible for a theme to give more accurate color. For example, if I think `new` is 100 times more important than other keywords, I can't highlight `new` differently now because I can't tell it away from other `keywords`.

Should we allow extensions to give `tokenType` such as `keyword.operator` or `['keyword', 'operator']` etc?

**Comment by aeschli** [comment]
The current default token dictionary is still just proposal and we will extend it based on the feedback of the first users. For you have a good name of that kind of keyword? Based on that we can see if it's a new type or rather a modifier.
In the future, extensions will be able to extend the token dictionary along with default color rules.

That said, keywords are not really a good example for a semantic highlight provider. The current story is that the semantic token provider adds semantic tokens while syntax tokens are coming from the textmate theme. Keywords are typically served by a the syntax theme. Yes it's possible that in some very context specific language a keywords can only be evaluated by a real parser.
So a semantic color provider would not report all keywords, just the one's that need a real parser.

**Comment by aeschli** [comment]
It's now possible for extension to define their own token types that extend an existing token type.
