### ISSUE TITLE
Loads empty screen with the last line of a file at the beginning

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode#8634]
- VSCode Version: 1.2.1
- OS Version: OS X El Capitan 10.11.5 (15F34)

Steps to Reproduce:

1. have a 2560*1440px screen
2. have a 57-line source code file
3. start VSCode with `code .` command from command-line
4. maximize VSCode window (not full screen mode)
5. click on that source file from the sidebar
6. get empty screen scrolled all the way down to line 57 with the rest of the coding area empty:

![image](https://cloud.githubusercontent.com/assets/159209/16528637/f3de64de-3f72-11e6-96ac-710b13c849ec.png)

scrolling up just shows the rest of the file, but why does it load the last line to the top of the screen? it is often an empty line...

**Comment by bpasero** [comment]
@ahmetalpbalkan did you open this file before? we keep and restore the view state of the file as it was so maybe you had been scrolling to the end before? or do you change monitor resolutions often maybe?

**Comment by ahmetalpbalkan** [comment]
I do both. It's easy to repro actually even without changing the resolution or anything as apparently vscode restores the view state. In this case, restoring a not-very-useful view state sounds a bit weird to me is all.

**Comment by bpasero** [comment]
@ahmetalpbalkan so you say this issue happens when you have the editor in one state, change to another monitor and open the file again?

**Comment by ahmetalpbalkan** [comment]
@bpasero I guess it was the state I left it at (scrolled all the way to the bottom). So maybe not a big deal, I'll close. Thanks.
