### ISSUE TITLE
Extension publishers and disabled extension titles don't use SPAA

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86343]
Testing #84715

![image](https://user-images.githubusercontent.com/2193314/70191606-2939dd00-16ae-11ea-84df-9ccbd61dc6e0.png)

**Comment by Tyriar** [comment]
This doesn't seem to happen in the normal view, just in `@builtin`?

**Comment by gjsjohnmurray** [comment]
See also #86192

**Comment by Tyriar** [comment]
Thanks, merged into that

/duplicate
