### ISSUE TITLE
Git decorations lasting far beyond their relevance

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#86346]
Not much in terms of repro steps, but to get this down on paper I've been seeing git change decorations lasting far beyond my actually commiting the change they're describing.

Here for instance is a change from like HEAD^5.

![image](https://user-images.githubusercontent.com/8586769/70192126-a285ff80-16af-11ea-9032-e2c1320036bb.png)

**Comment by joaomoreno** [comment]
@JacksonKearl Have you seen this since?

**Comment by JacksonKearl** [comment]
@joaomoreno I have not
