### ISSUE TITLE
problems.showCurrentInStatus showing incomplete messages

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#86348]
Issue Type: Bug
OS: Mac

#85943

When making the window small enough so the "line #, col #" in the status bar disappears, the resulting blank space cuts into the part of the status bar that shows the problem and it looks like the message is incorrect. 

![problems_statusbar_short](https://user-images.githubusercontent.com/9721254/70194646-f8f73c00-16b7-11ea-9cc9-cdd9b15d0a20.gif)

Version: 1.41.0-insider
Commit: 97855786a014be2440751b038b373c3726e11fe8
Date: 2019-12-03T05:35:54.992Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by sandy081** [comment]
This should be fixed by #85638
