### ISSUE TITLE
Settings Editor input suggestion displays incompletely

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86347]
- VSCode Version: Insiders
- OS Version: Windows 10

<img width="793" alt="image" src="https://user-images.githubusercontent.com/876920/70193036-92235400-16b2-11ea-97b1-be183f13dca1.png">

It's caused by the change we made to Suggest Input content widget positioning. cc @roblourens 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Reopening as this has been reverted
