### ISSUE TITLE
Layering: compact menubar underlays debug menu

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#86349]
The normal menubar does not.

![image](https://user-images.githubusercontent.com/2230985/70195659-272a4b00-16bb-11ea-8b5c-2f1fb9bce3cd.png)

**Comment by sbatten** [comment]
yea we couldn't get around this one. unfortunately the the activity bar should be below the debug toolbar and the menubar is forced to be on the same z-index due to the layering.

**Comment by connor4312** [comment]
Okay, I heard you talked to rob and was wondering if that was the same thing 😛
