### ISSUE TITLE
Incorrect keyboard shortcut shown in edit menu

### ISSUE THREAD

**Issue by cycledudecoder** [microsoft/vscode#86352]
Issue Type: <b>Bug</b>

1. Click "Edit" menu
2. Next to Toggle Line Comment the shortcut should be Ctrl +/ rather than Ctrl+shift+/

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
csharp|ms-|1.21.8
sublime-keybindings|ms-|4.0.3
vscode-yaml|red|0.6.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and `>Developer: Reload Window With Extensions Disabled`

Most likely this comes from `sublime-keybindings` extension
![image](https://user-images.githubusercontent.com/1312662/70228261-b9cef680-175c-11ea-9c0d-a1a0e409ef55.png)

**Comment by cycledudecoder** [comment]
@IllusionMH is correct. This was the issue. I'm new to VSCode and was not aware that the keybindings would change the menus.
