### ISSUE TITLE
need rename package name

### ISSUE THREAD

**Issue by Binaryify** [microsoft/vscode#86357]
hi
I have a extension which have 1,900000+ installs[One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme), the package name is wrong for historical reasons, have any feature that I can change it and keep the installs and downloads data?

**Comment by sandy081** [comment]
Yeah you can rename it. Please contact the marketplace team - @kesane-msft.

**Comment by Binaryify** [comment]
@kesane-msft 
hi, I need some help, how I can rename my extension, I will very appreciate it

**Comment by skofman1** [comment]
Hi @Binaryify , @kesane-msft changed teams so I can help out here. 
If you are interested in changing the display name of the extension (One Dark Pro), you can do this by publishing a new version with updated DisplayName in the manifest https://code.visualstudio.com/api/references/extension-manifest

If you are interested in changing the name/unique identifier (zhuangtongfa.Material-theme) this is not possible.

**Comment by Binaryify** [comment]
@skofman1 oh, I see, regret to see that can't change the name/unique identifier
