### ISSUE TITLE
problems.showCurrentInStatus disappears when toggling problems from multiple files

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#86353]
Issue Type: Bug

Testing #85943

When switching between problems in different files, the problems in the status bar only show for the first file that was opened and do not show when clicking on problems in other files.

![problem not showing](https://user-images.githubusercontent.com/9721254/70195986-1cbc8100-16bc-11ea-86b6-1165e3749f78.gif)

Version: 1.41.0-insider
Commit: 97855786a014be2440751b038b373c3726e11fe8
Date: 2019-12-03T05:35:54.992Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by sandy081** [comment]
Good catch
