### ISSUE TITLE
Replace in Files inserts replacement text in wrong location

### ISSUE THREAD

**Issue by drichardson** [microsoft/vscode#86355]
Issue Type: <b>Bug</b>

## Steps to Reproduce
You can also see a [screen recording](https://www.youtube.com/watch?v=_fqx87BB1PU) of the reproduction steps.

1. Download [problem.zip](https://github.com/microsoft/vscode/files/3924784/problem.zip) and extract to desktop.
2. Open problem folder in VS code
3. If HoudiniEngineEditor.Build.cs is displayed as a VS code tab, close the tab.
4. Edit > Replace in Files...
5. Enter 293 for the search string and AAA for the replacement string.
6. Press ENTER
7. Press the Replace All button.

### Result
The first replacment is correct, but the second replacement is incorrect. The 293 string is left intact and AAA is incorrectly inserted after the function name.

![image](https://user-images.githubusercontent.com/36176/70197442-b38b3c80-16c0-11ea-814b-eaf4006d8564.png)

## Notes
The file has mismatched line endings. If I open the file in Visual Studio 2019 16.4, I get an error about mismatched line endings.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.92GB (38.56GB free)|
|Process Argv|C:\Users\doug\Desktop\problem|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
Mismatched line endings alone shouldn't do it, but if there are CR-only line endings, that would do it, do you think that's the case? You can share the file if you want.

**Comment by drichardson** [comment]
I did share the file. It's in problem.zip.

**Comment by roblourens** [comment]
Yeah there are some bare CR characters there in the Unreal Engine Version line, this is https://github.com/microsoft/vscode/issues/48063
