### ISSUE TITLE
problems.showCurrentInStatus message not changing

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#86351]
Issue Type: Bug
Testing #85943

Sometimes the message doesn't change when switching between problems

![message not changing](https://user-images.githubusercontent.com/9721254/70195804-8f792c80-16bb-11ea-95a2-260a1ea0074d.gif)

Version: 1.41.0-insider
Commit: 97855786a014be2440751b038b373c3726e11fe8
Date: 2019-12-03T05:35:54.992Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by sandy081** [comment]
I cannot repro this, can you please provide the steps to repro and if possible also code snippets.

**Comment by sandy081** [comment]
After looking at the gif I understood why some marker messages are not shown. This is because, these markers on the same position of others and only the first one at that position is shown.
