### ISSUE TITLE
Problemmatcher not work over ssh

### ISSUE THREAD

**Issue by tooyangtoonaive** [microsoft/vscode#86356]
OS and Version:win7 x64
VS Code Version:1.40.2

task.json

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "zcsshbuild",
			"type": "shell",
			"command": "d:\\putty\\plink.exe -pw passwd user@server \"cd workspace/${workspaceFolderBasename} && ./zcmake.sh\"",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher" : {
				"fileLocation" : ["relative", "${workspaceFolder}"],
				"pattern" : {
					//"regexp": "^.*$",   // not work too
					"regexp" : "/home/workspace/testproject/([^:]*):(\\d+):(\\d+): (E|e)rror:(.*)"
					"file" : 1,
					"line" : 2,
				}
			}
		}
	]
}
```

Steps to Reproduce:

1.ctrl+shift+b to build
2. Terminal show message:
/home/workspace/testproject/src/test.c:423:26: error: 'a' undeclared (first use in this function)
3. It's nothing happen when double click message above. Terminal show message above not highlight

plink.exe is a tool that can connect to ssh server and do something in batch. It include in putty software

**Comment by alexr00** [comment]
I made a test task:
```
        {
			"label": "zcsshbuild",
			"type": "shell",
			"command": "echo",
			"args": ["/home/workspace/testproject/src/test.c:423:26: error: 'a' undeclared (first use in this function)"],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher" : {
				"fileLocation" : ["relative", "${workspaceFolder}"],
				"pattern" : {
					"regexp" : "/home/workspace/testproject/([^:]*):(\\d+):(\\d+): (E|e)rror:(.*)",
					"file" : 1,
					"line" : 2,
				}
			}
		}
```
It created a problem:
![image](https://user-images.githubusercontent.com/38270282/70218675-b8dd9b00-1743-11ea-8ec5-e20268b7db00.png)
Problem looks good:
![image](https://user-images.githubusercontent.com/38270282/70218738-dad71d80-1743-11ea-9653-2bc965d6494c.png)

**Comment by alexr00** [comment]
If plink does a bunch of re-writing of existing terminal content or some other unexpected operation with the terminal then Tasks might have trouble reading what's in the terminal and be unable to use problem matchers. You can see what lines tasks is reading by placing a breakpoint here https://github.com/microsoft/vscode/blob/79970801922dfabd5be3711ea7869e483655a0e8/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L721
