### ISSUE TITLE
Regex Lookbehind doesn't work

### ISSUE THREAD

**Issue by xenoken** [Microsoft/vscode#8635]
- VSCode Version: 1.2.1
- OS Version: Windows 7 Home Edition

Steps to Reproduce:

1. type "a b"
2. search text ( CTRL +F)
3. use regular expression (ALT+R)
4. type (?<=\w)\s(?=\w)
5. The Error Message Appears "Invalid Regular Expression: /(?<=\w)\s(?=\w)/: Invalid Group" and no results are found.
It should instead match the space character between 'a' and 'b'.

**Comment by bpasero** [comment]
I do not think we (or JS) supports this syntax.

**Comment by xenoken** [comment]
Odd, because Visual Studio supports Regular Expressions Look Behind.

**Comment by alexandrudima** [comment]
The find widget is simply using JavaScript's regular expressions as specified in ECMAScript 5 (the runtime of VS Code), and it unfortunately does not support look behinds.

**Comment by cyborgx37** [comment]
A work around when performing find/replace (which is the most common scenario for lookaround expressions):

Search Expression:

    (lookbehind_expression_)text_to_replace

Replace Expression:

    $1replacement_text

Given the input:

    lookbehind_expression_text_to_replace

The output will be:

    lookbehind_expression_replacement_text
