### ISSUE TITLE
issues opening html in browser

### ISSUE THREAD

**Issue by TimGangl** [microsoft/vscode#86367]
We h
Issue Type: <b>Bug</b>

Hi i am not able to open and html files to a browser. I have extensions installed.  Things were working fine last time I used VS code and i opened it tonight to work on some things  and i get an error. Open browser failed!! Please check if you have installed the browser chrome correctly! In fact I cannot open in any browser. same error. have tried unintalling extensions and VS code as well but nothing. please help

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|cod|0.1.21
debugger-for-chrome|msj|4.12.2
indent-rainbow|ode|7.4.0
open-html-in-browser|pea|2.1.0
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
open-in-browser|tec|2.0.0

</details>
ave written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Does advice at https://github.com/microsoft/vscode/issues/84265#issuecomment-552497552 produce any clues?

**Comment by RMacfarlane** [comment]
@TimGangl It sounds like this is being caused by the [open in browser extension](https://github.com/SudoKillMe/vscode-extensions-open-in-browser). The [debugger for chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) extension might be a good alternative

**Comment by TimGangl** [comment]
I figured it out. I was trying to create a path for mysql for command line
and that was what screwed it up.
