### ISSUE TITLE
Line Numbers Dissapear After Exiting Zen Mode

### ISSUE THREAD

**Issue by benpm** [microsoft/vscode#86365]
Issue Type: <b>Bug</b>

1. Open an existing file with content
2. Enter zen mode
3. Create a new file
4. Exit zen mode
5. Close file
6. Line numbers are not shown until reload

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.3.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (8 x 3580)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (1.44GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
love|bsc|0.3.6
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
latex-workshop|Jam|8.4.2
Lua|key|0.0.9
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
shader|sle|1.1.4
lua|sum|0.14.6
language-pde|Tob|1.4.0
cmake|twx|0.0.17
vscode-icons|vsc|9.6.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
I can not reproduce this.
