### ISSUE TITLE
grpc issues

### ISSUE THREAD

**Issue by seetharamanis** [microsoft/vscode#86366]
Issue Type: <b>Bug</b>

It doesn't run locally  due to grpc_tools module isn't found.  Not sure what it means and there are not enough help on this.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including whether the problem still occurs if you run with all extensions disabled
