### ISSUE TITLE
Not able to hit the breakpoints set on TS files which are present inside the node_modules folder

### ISSUE THREAD

**Issue by gauravmahto-at** [microsoft/vscode#86363]
- VSCode Version: Version: 1.40.2 (user setup)
- OS Version: Win10 Enterprise x64 1903

Steps to Reproduce:

1. Have node_modules JS sources with mapping to TS sources present inside node_modules folder.
2. Apply breakpoints in the TS file present inside node_modules folder
3. Breakpoints are properly applied and the 'red dot' glows (showing no sign of problem)
4. Try to execute the code path which should hit the breakpoints
5. None of the breakpoints are hit

Does this issue occur when all extensions are disabled?: Yes

Note: After enabling the 'trace' option, I can see that the files are properly mapped and so does the breakpoints. Also, if I use the Chrome Debugger the breakpoints gets properly hit.

**Comment by gauravmahto-at** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Allow for a Breakpoint to be Enabled when breakpoints are deactivated (#65394)](https://www.github.com/microsoft/vscode/issues/65394)
> * [Breakpoints (#85146)](https://www.github.com/microsoft/vscode/issues/85146)

Is not covered by the above ones.

**Comment by gjsjohnmurray** [comment]
Does your launch.json specify a skipFiles setting?

**Comment by gauravmahto-at** [comment]
> Does your launch.json specify a skipFiles setting?

No

Below is my launch.json:
`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to backend local",
            "type": "node",
            "request": "attach",
            "restart": true,
            "port": 9229
        }
    ]
}
`

**Comment by weinand** [comment]
Please try to add a "outFiles" attribute to the launch config. "Outfiles" helps the node-debugger to find mappings from TS -> JS (since sourcemaps only help with the reverse mapping JS -> TS).

```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to backend local",
            "type": "node",
            "request": "attach",
            "restart": true,
            "port": 9229,
            "outFiles": [
                "${workspaceFolder}/node_modules/**/*.js"
            ],
        }
    ]
}
```

**Comment by roblourens** [comment]
> Also, if I use the Chrome Debugger the breakpoints gets properly hit.

Are you debugging in Chrome or Node?

Can you set `"trace": true` in your launch config, try this again, and upload the log here?

**Comment by gauravmahto-at** [comment]
> Please try to add an "outFiles" attribute to the launch config. "Outfiles" helps the node-debugger to find mappings from TS -> JS (since sourcemaps only help with the reverse mapping JS -> TS).
> 
> ```js
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Attach to backend local",
>             "type": "node",
>             "request": "attach",
>             "restart": true,
>             "port": 9229,
>             "outFiles": [
>                 "${workspaceFolder}/node_modules/**/*.js"
>             ],
>         }
>     ]
> }
> ```

I tried the above but was still not able to hit the breakpoint.

**Comment by gauravmahto-at** [comment]
> > Also, if I use the Chrome Debugger the breakpoints gets properly hit.
> 
> Are you debugging in Chrome or Node?
> 
> Can you set `"trace": true` in your launch config, try this again, and upload the log here?

With Node the breakpoints are not getting hit. But when I tried connecting using the Chrome debugger and applied the same breakpoints inside the node_modules, I was able to hit those breakpoints without any config changes.

**Comment by gauravmahto-at** [comment]
@roblourens Please find the attached debug trace file.
In this file at the very bottom you can find that the debug adaptor was succeffully able to map my breakpoint:
`SourceMaps.setBP: Mapped c:\abc\xyz\node_modules\company\gdk\lib\aa\bb\calculator.js:435:54 to c:\abc\xyz\node_modules\company\gdk\src\aa\bb\calculator.ts:470'.
Also, I confirm the existence of both the file at the correct location and line number.
Please find the attached log file.
[debugadapter.zip](https://github.com/microsoft/vscode/files/3931619/debugadapter.zip)

**Comment by roblourens** [comment]
I see that Calculator.ts file is loaded in two places. The .js file you mention and also `c:\abc\xyz\dev-data\env-local-aristocrat-platforms\games\game_none_000000000000000000000\private\backend.js`. It's possible that the code you are actually interested in is in the second one. This is a case we don't currently handle well.

**Comment by gauravmahto-at** [comment]
@roblourens I see. Shall we keep this one open?

**Comment by weinand** [comment]
By using the `"outFiles"` attribute it is already possible to specify where the generated JavaScript lives.
Having the generated code in more than one place is not something we are planning to support.

**Comment by gauravmahto-at** [comment]
@weinand By using the `"outFiles"` attribute, I was not able to hit the applied breakpoints as the generated code is not in multiple places. I think we should understand the problem instead of closing this one?

**Comment by weinand** [comment]
What glob pattern did  you specify for `"outFiles"`?

**Comment by gauravmahto-at** [comment]
> What glob pattern did you specify for `"outFiles"`?

"${workspaceFolder}/node_modules/**/*.js"

**Comment by weinand** [comment]
And changing that to `"${workspaceFolder}/dev-data/**/*.js"`(for the other location) did not help?

**Comment by gauravmahto-at** [comment]
> And changing that to `"${workspaceFolder}/dev-data/**/*.js"`(for the other location) did not help?

No, it didn't.

**Comment by roblourens** [comment]
This is a case that we can and should support, although I am not going to debug it more in the current debug extensions because we are working on a new version of the debug extension. It might already work there, you can try it at https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

**Comment by gauravmahto-at** [comment]
@roblourens Hi there .. I tried the above extension on both the stable and insiders (VSCode) builds but I was still not able to hit the breakpoints. :(

**Comment by gauravmahto-at** [comment]
Shall we re-open this issue?

**Comment by roblourens** [comment]
Can you share your project? The basic scenario should work with that extension but I'd like to dig into your case. If not, could you please share the log from running with the new extension in a new issue on https://github.com/microsoft/vscode-js-debug/issues?

**Comment by gauravmahto-at** [comment]
@roblourens 

I apologize in advance but I won't be able to share the project due to my company policy. Anyways, I've opened the https://github.com/microsoft/vscode-js-debug/issues/170 issue with the log file attached.

If you need more info ... I would love to help out.
Thanks!
