### ISSUE TITLE
Markdown lists containing fenced code blocks with language hints breaks formatting 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8636]
- VSCode Version: Code - Insiders 1.3.0-insider (716f76458e4dc93e865b6a999e437ed45774744e, 2016-07-01T05:29:26.347Z)
- OS Version: Linux x64 4.4.0-28-generic

In this image, `* bar` should be the same style as `* foo` since the code block ended 2 lines ago.

![image](https://cloud.githubusercontent.com/assets/2193314/16529539/56f57134-3f78-11e6-9fc3-a8afd4a47062.png)

I first saw this happening in our release notes:

![image](https://cloud.githubusercontent.com/assets/2193314/16529592/9fcb1af8-3f78-11e6-9ed1-ae51685af243.png)

**Comment by mjbvz** [comment]
The specific problem seems to be the spaces before the end fence code blocks. 

![sep-20-2016 16-01-40](https://cloud.githubusercontent.com/assets/12821956/18691927/89e264b8-7f4b-11e6-9a72-4ae300d9ed53.gif)

Spaces are valid here as long as they do not turn the fenced code block into an indented code block.

**Comment by Tyriar** [comment]
By the way, in my example the spaces make it part of the preceeding list item. Non-empty lines after a - or * list item that have 2+ spaces are part of that list item.
