### ISSUE TITLE
Add search/filter in debug pane

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode#86369]
I think all panes which have hierarchical trees like the debug pane could have an option/search box to quickly search for an element by name. So by typing a part the name the tree will filter out and display only the matching elements.

**Comment by gjsjohnmurray** [comment]
Did you already try simply typing while focus is on the Variables pane?

**Comment by Zingam** [comment]
@gjsjohnmurray Thank you for pointing me to this feature. I didn't know about it and it isn't a very intuitive UI feature. I could be more explicit.
Also it doesn't really work in the way I suggest: It is only good for non-hierarchical lists. For example if there are a multiple items in a collapsed hierarchical view in the debug pane, typing the searched item name would neither expand and point to it nor will it hide the unwanted items. So it isn't really very useful at first try.

**Comment by gjsjohnmurray** [comment]
@Zingam I agree it's a feature that deserves better discoverability. You may want to upvote #70646

Did you notice that if you mouse over the little widget that appeared when you started typing, there are a couple of extra things you can do?

![image](https://user-images.githubusercontent.com/6726799/70312750-27862b80-180c-11ea-8882-6519e10d5f05.png)

One of them it to toggle to "filter" mode in place of "highlight" mode.

**Comment by isidorn** [comment]
Thanks @gjsjohnmurray 
Closing this as a question / duplicate then

**Comment by Zingam** [comment]
@gjsjohnmurray Thank you for letting me know about the widgets.

@isidorn The filtering still doesn't work quite as expected. I'd like that it would expand the hierarchy and show the searched item. Also it is buggy in the current state, please check the last screenshot: I have typed 'flat' and it also includes `defaultTargetName` in the results. Also on the previous screenshot: there is also an item that shouldn't be there

![Capture3](https://user-images.githubusercontent.com/3337419/70352031-e5440500-1872-11ea-844d-7ec58e47a448.PNG)
![Capture2](https://user-images.githubusercontent.com/3337419/70352032-e5440500-1872-11ea-935c-a5b8805a0acc.PNG)
![Capture1](https://user-images.githubusercontent.com/3337419/70352027-e4ab6e80-1872-11ea-9714-deefa161015d.PNG)
![Capture4](https://user-images.githubusercontent.com/3337419/70352030-e5440500-1872-11ea-9c80-5a16785e8880.PNG)
![Capture5](https://user-images.githubusercontent.com/3337419/70352029-e4ab6e80-1872-11ea-9ca2-53abbe92c3d5.PNG)

**Comment by Zingam** [comment]
Why is the `ctx` displayed in the search results?

![image](https://user-images.githubusercontent.com/3337419/70352437-ceea7900-1873-11ea-8704-09238fe4da0b.png)

**Comment by gjsjohnmurray** [comment]
@Zingam because it uses the same fuzzy matching as other parts of VSCode do. You may want to upvote #66913
