### ISSUE TITLE
How to get pylint to ignore some errors

### ISSUE THREAD

**Issue by msoultan** [microsoft/vscode#86373]
I have the following at the top of my Python file:

`import config`

And for every line where I type ```config.something``` I have a red mark underneath "config" indicating that it can't find the module.  I'm editing a file that resides on another host and I don't have that module's file residing locally, so I figure it makes sense that it's going to generate that error.

The problem is that I am referencing that module a ton in one file, so it's hitting it's max limit (I believe it's currently configured to 100) and then I don't see other legitimate errors.

Is there a more graceful way to handle this issue?  I really like the linting, but right now I'm not seeing any other errors because this error is maxing out the number of errors displayed.

Thanks!
Mike

**Comment by octref** [comment]
Please report to https://github.com/microsoft/vscode-python
