### ISSUE TITLE
golang-start without debugging does not working

### ISSUE THREAD

**Issue by gerrywp** [microsoft/vscode#86374]
- VSCode Version:1.40.2
- OS Version:win10 1909

Steps to Reproduce:

1. when I using go1.13, the go compiler use module feature to finding packages 
2. start with debugging(f5). I can run my project/module code, go can using the go.mod file
then find all packages from %GOPATH%/pkg/mod  directory.
3. but when I running my code throw Ctrl+F5(start without debugging), go can not found package using go-module feature.
![image](https://user-images.githubusercontent.com/16008976/70215360-4804a600-1778-11ea-831a-3859ab03bcef.png)
It seems like when using CTRL+F5 go can not recognize go.mod file which is in project root path
4. what can I do?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gerrywp** [comment]
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

What do you mean? and can u tell me which extension(tell me the name) raises the error?

**Comment by weinand** [comment]
Most likely this is the Go extension.
You should know better because VS Code does not have built-in Go support, so you have installed some Go extension.

If you are using Microsoft's Go extension you can file the issue here: https://github.com/Microsoft/vscode-go

**Comment by gerrywp** [comment]
> Most likely this is the Go extension.
> You should know better because VS Code does not have built-in Go support, so you have installed some Go extension(s).
> 
> If you are using Microsoft's Go extension you can file the issue here: https://github.com/Microsoft/vscode-go

Thanks a lot!
