### ISSUE TITLE
"Close All" in editor group should show combined dialog

### ISSUE THREAD

**Issue by oerpli** [microsoft/vscode#86375]
Not sure if this actually is a bug or just behavior I find suboptimal. 

- VSCode Version: 1.40.2
- OS Version: Win 10 Pro 1809

### Steps to Reproduce:

1. Have a a lot of open editors with unsaved changes (had dozens of open editors with open changes due to mishandling a merge-conflict)
2. Try to close them all with 2 methods:
    a.) With the thing in the top right corner:
    b.) With the button in the Explorer

Here are (bad) screen capturing of both methods: 
![vscode-closeall-1](https://user-images.githubusercontent.com/4408819/70216079-18857780-173f-11ea-9b37-f770364988ed.gif)

![vscode-closeall-2](https://user-images.githubusercontent.com/4408819/70216200-584c5f00-173f-11ea-89f6-0dcee011616c.gif)

### What's the problem?
The first method tries to close each file individually and a modal (save, discard, cancel) pops up for every single editor.
The second method determines all files that have unsaved changes and allows to save them all/ discard them all with a single click.

The two commands are:
1. Close all editors (Ctrl K, Ctrl W)
2. Close all editors in group (Ctrl K, W)

I think the second should have the behavior of the first, though only for the subset of editors in the group. At least I don't see why this shouldn't be the case.

**Comment by bpasero** [comment]
This works as designed, closing all editors across all groups shows a combined dialog and closing all of a group asks for each editor. I am leaving this up as a feature request to change, pending enough upvotes.
