### ISSUE TITLE
Using software, stuck after a period of time

### ISSUE THREAD

**Issue by XYYHHKFD** [microsoft/vscode#86377]
所需的数据太大，无法直接发送。我们已经将其写入
Issue Type: <b>Performance Issue</b>

 

使用vscode在进行web任务制作时，使用一段时间之后点击关闭按钮会让系统完全卡死！
我的系统：win10专业版1803
8g内存以及17cpu
When using vscode to make web tasks, clicking the close button after a period of time will completely block the system!

My system: win10 professional 1803

8g memory and 17cpu

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    88	  5152	code main
    0	   193	  3208	   window (表格.html - H5-CSS3-JS-JQ - Visual Studio Code [管理员])
    0	   133	  6180	     extensionHost
    0	   100	  3332	       electron_node server.js 
    0	    61	  7076	       "C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=6180
    0	    33	  7016	     searchService
    0	    11	 11140	     watcherService 
    0	    10	 11260	       console-window-host (Windows internal process)
    0	    67	  4356	   shared-process
    1	   114	  4516	   gpu-process
    1	    27	  6028	   gpu-process
    0	    13	  7804	   electron-crash-reporter
    0	    67	  8520	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (表格.html - H5-CSS3-JS-JQ - Visual Studio Code [管理员])
|    Folder (H5-CSS3-JS-JQ): 302 files
|      File types: png(149) html(42) jpg(36) xml(10) js(10) css(8) md(8)
|                  iml(3) txt(3) doc(2)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.4.4
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
docthis|joe|0.7.1
Angular2|joh|8.2.0
vscode-view-in-browser|kop|1.0.5
node-module-intellisense|lei|1.5.0
vscode-fileheader|mik|0.0.2
vscode-language-pack-zh-hans|MS-|1.40.2
debugger-for-chrome|msj|4.12.2
vetur|oct|0.22.6
vuehelper|oys|0.1.0
material-icon-theme|PKi|3.9.2
code-spell-checker|str|1.7.20
open-in-browser|tec|2.0.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.0

(1 theme extensions excluded)

</details>
剪贴板，请粘贴。

**Comment by octref** [comment]
Please try disabling all extensions. This is caused by one of your extensions. Probably auto-rename-tag.
