### ISSUE TITLE
Unable to open VS Code on Ubuntu VM instance on Google Cloud

### ISSUE THREAD

**Issue by TRD-1** [microsoft/vscode#86372]
I am facing a problem when trying to open the VS Code on my VM machine using VNC viewer for UI. It has Ubuntu 18.04 LTS OS(x64). The VS code version is 1.40.2 installed through "sudo snap install --classic code". 

I was able to install the application and see it listed with the other applications but was not able to open it either by clicking on the icon or through the terminal. When I tried to open it through a terminal it didn't give any errors but also did not open anything.

**Comment by Tyriar** [comment]
Does `code --verbose` tell you anything?

**Comment by TRD-1** [comment]
(process:21998): Gtk-WARNING **: 03:13:00.891: Locale not supported by C library.
	Using the fallback 'C' locale.
Xlib:  extension "XInputExtension" missing on display ":1".
Xlib:  extension "RANDR" missing on display ":1".
Xlib:  extension "XInputExtension" missing on display ":1".
[22022:1206/031301.830800:ERROR:gl_surface_glx.cc(425)] glxQueryVersion failed
[22022:1206/031301.830903:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[22022:1206/031301.838782:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[21998:1206/031301.914698:WARNING:gpu_process_host.cc(1193)] The GPU process has crashed 1 time(s)
Xlib:  extension "XInputExtension" missing on display ":1".
[main 2019-12-06T03:13:01.995Z] Starting VS Code
[main 2019-12-06T03:13:01.997Z] from: /snap/code/21/usr/share/code/resources/app
[main 2019-12-06T03:13:01.997Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false
}
[main 2019-12-06T03:13:01.999Z] Resolving machine identifier...
[main 2019-12-06T03:13:02.070Z] Resolved machine identifier: 6de8fb2581d18024f9e2e812a4e64f59e621e4e8f7abc258b4bd838bb9315189 (trueMachineId: undefined)
[main 2019-12-06T03:13:02.090Z] update#setState idle
[main 2019-12-06T03:13:02.093Z] [storage state.vscdb] open(/home/developer/.config/Code/User/globalStorage/state.vscdb, retryOnBusy: true)
[main 2019-12-06T03:13:02.094Z] lifecycle (main): phase changed (value: 2)
[main 2019-12-06T03:13:02.095Z] windowsManager#open
[21998:1206/031302.117571:WARNING:gpu_process_host.cc(967)] Reinitialized the GPU process after a crash. The reported initialization time was 167 ms
Xlib:  extension "XInputExtension" missing on display ":1".
Xlib:  extension "XInputExtension" missing on display ":1".
[21998:1206/031302.304728:ERROR:atom_browser_main_parts.cc(183)] X IO error received (X server probably went away)

This is the response  for code --verbose

**Comment by TRD-1** [comment]
Xlib:  extension "XInputExtension" missing on display ":1".
Xlib:  extension "RANDR" missing on display ":1".
Xlib:  extension "XInputExtension" missing on display ":1".
[13988:1206/040556.509538:ERROR:gl_surface_glx.cc(425)] glxQueryVersion failed
[13988:1206/040556.509600:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[13988:1206/040556.510808:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[13966:1206/040556.517587:WARNING:gpu_process_host.cc(1193)] The GPU process has crashed 1 time(s)
Xlib:  extension "XInputExtension" missing on display ":1".
[13966:1206/040556.554491:WARNING:gpu_process_host.cc(967)] Reinitialized the GPU process after a crash. The reported initialization time was 14 ms
[main 2019-12-06T04:05:56.578Z] Starting VS Code
[main 2019-12-06T04:05:56.579Z] from: /usr/share/code/resources/app
[main 2019-12-06T04:05:56.579Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false
}
[main 2019-12-06T04:05:56.580Z] Resolving machine identifier...
[main 2019-12-06T04:05:56.581Z] Resolved machine identifier: 8195d34eeeec20241a1db1a84b63b5309fc06715a4960b3481584f41d87c0955 (trueMachineId: undefined)
[main 2019-12-06T04:05:56.597Z] update#setState idle
[main 2019-12-06T04:05:56.600Z] [storage state.vscdb] open(/home/developer/.config/Code/User/globalStorage/state.vscdb, retryOnBusy: true)
[main 2019-12-06T04:05:56.600Z] lifecycle (main): phase changed (value: 2)
[main 2019-12-06T04:05:56.601Z] windowsManager#open
Xlib:  extension "XInputExtension" missing on display ":1".
Xlib:  extension "XInputExtension" missing on display ":1".
[13966:1206/040556.659702:ERROR:atom_browser_main_parts.cc(183)] X IO error received (X server probably went away)

**Comment by Tyriar** [comment]
Sounds like https://github.com/microsoft/vscode/issues/3451

/duplicate

**Comment by kk738** [comment]
I already tried using the fix from #3451, but it's still not working. Maybe I'm doing something wrong. I installed vs-code via snap install. @TRD-1 Did you get it to work?

**Comment by TRD-1** [comment]
No, I changed to nomachine and there everything works fine without any hacks (previously I was using VNC viewer).
