### ISSUE TITLE
Debug: protocol corruption

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#86387]
After editing a breakpoint condition I got the following in the console:

PROTOCOL CORRUPTION, LAST SAW MSG 1195 AND HAVE NOW RECEIVED MSG 1198

**Comment by isidorn** [comment]
This is coming from the ipc.net layer [here](https://github.com/Microsoft/vscode/blob/7cbfeb67921a1dd954a4b4f9b3e45479a63cb1cb/src/vs/base/parts/ipc/common/ipc.net.ts#L728) So also assigning @joaomoreno 
I can not repro this issue if I simply edit a breakpoint via a context menu.
@dbaeumer do you always see this, and if yes how do you edit the breakpoint?

**Comment by dbaeumer** [comment]
This happens to me when verifying a debugger issue with hit counts in lib and main were someone complained about the breakpoint always being hit if the count is set to 100. 

I can't find the issue anymore since I don't know in which repository it is :-( but I am sure you remember.

I was under WSL 2 when I saw this in case it matters.

**Comment by joaomoreno** [comment]
@isidorn This is @alexandrudima

**Comment by alexandrudima** [comment]
@dbaeumer This has to do with reconnection, and it indicates that some messages were lost... Do you happen to have some steps?

**Comment by dbaeumer** [comment]
Sorry no steps. I saw it yesterday again when loosing the debugger connection. I will have an eye on it and see if I can distill some steps.

**Comment by alexdima** [comment]
@dbaeumer I think this might have been caused by the WSL2 sleep bug, where their TCP/IP pipes got broken somehow. Please reopen if you notice this again.
