### ISSUE TITLE
Urls in markdown files do not get the "hyperlink" styles in preview and are not clickable as well

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#8638]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

Steps to Reproduce:
1. Open a markdown file type in a url
2. Open preview
3. The url is neither clickable nor does it have the styles of a hyperlink

In older versions (mine is 1.2.1 dated 6/14), the url would appear as a hyperlink and on clicking a browser instance would open up using the url.

Note: Links added using the right markdown syntax as below work just fine
![image](https://cloud.githubusercontent.com/assets/16890566/16531337/d63636ce-3f80-11e6-9d41-f31b1b264bb9.png)

**Comment by mjbvz** [comment]
I believe this is by design. Our markdown preview targets Common Mark, which does not automatically identify links like github does.

To create a proper link, you can either use a `[text](http://example.com)` style link or use an auto link: `<http://example.com>`
