### ISSUE TITLE
Web: cannot open images in selfhost anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86399]
Selfhosting web, I cannot see images anymore when opened (e.g. from vscode-docs):

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-1575547817862'". Either the 'unsafe-inline' keyword, a hash ('sha256-wYGzaCFwj3TvTS34soRrdUzuFXoP41wOXBmVV2zSHds='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by mjbvz** [comment]
I just tested this but could not repo:

![Screen Shot 2019-12-05 at 10 52 54 AM](https://user-images.githubusercontent.com/12821956/70264521-6dc88580-174d-11ea-8b7d-a46d55ed29cc.png)

What OS and browser was this for?

**Comment by bpasero** [comment]
@mjbvz make sure to try from our web selfhost setup, not out of sources.

**Comment by mjbvz** [comment]
I can repo on edge only. The error seems to be that edge is blocking something. Here is the content of the iframe:

![Screen Shot 2019-12-06 at 1 47 10 PM](https://user-images.githubusercontent.com/12821956/70358763-f66b2280-182e-11ea-8fbf-c182c65017d9.png)

I don't know why this is being blocked or why the blocking error isn't being displayed properly

**Comment by mjbvz** [comment]
Also now effecting VSO so I need to figure out what is going on

**Comment by mjbvz** [comment]
I finally figure out a change that fixes this: rewrite the content security policy of the webview content. Here's the fix applies to the markdown preview:

```diff
diff --git a/extensions/markdown-language-features/src/features/previewContentProvider.ts b/extensions/markdown-language-features/src/features/previewContentProvider.ts
index 0be66d1d63..30048dc58f 100644
--- a/extensions/markdown-language-features/src/features/previewContentProvider.ts
+++ b/extensions/markdown-language-features/src/features/previewContentProvider.ts
@@ -213,7 +213,7 @@ export class MarkdownContentProvider {
 
                        case MarkdownPreviewSecurityLevel.Strict:
                        default:
-                               return `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' ${rule} https: data:; media-src 'self' ${rule} https: data:; script-src 'nonce-${nonce}'; style-src 'self' ${rule} 'unsafe-inline' https: data:; font-src 'self' ${rule} https: data:;">`;
+                               return `<meta http-equiv="Content-Security-Policy" content="default-src *; img-src 'self' ${rule} https: data:; media-src 'self' ${rule} https: data:; script-src 'nonce-${nonce}'; style-src 'self' ${rule} 'unsafe-inline' https: data:; font-src 'self' ${rule} https: data:;">`;
                }
        }
 }
```

This makes no sense as there is nothing that the inner document (the html that comes from extensions) should be able to set or do that effects whether or not our webview iframes can be loaded. 

I've been trying all afternoon to put together a minimal repo to file this against Chromium but so far have not been able to. It also only effects chromium nightly at the moment. @bpasero and @kieferrm Can we please also loop in some folks from the edge team on this?

**Comment by mjbvz** [comment]
ping @jungkees Haven't been able to make much progress with this one. Any advice on who to reach out to on edge for help?

**Comment by jungkees** [comment]
Sorry about the delay. I'll find out who to talk to in our team.

**Comment by jungkees** [comment]
@mjbvz, is the Edge you experimented with here Chromium Edge not Spartan Edge, right? If so, can you please file an issue using the 'Send feedback' icon in the upper right corner of the Chromium Edge browser?

**Comment by ericlaw1979** [comment]
Is there a repro URL I can see? With a stable repro, I should be able to tell you exactly what the problem is.

**Comment by mjbvz** [comment]
Yes, Chromium based edge. But I just tested this again with the latest Edge dev build (and chrome canary) and don't see this anymore. I suspect it was fixed over the holidays, possibly by a security change like https://bugs.chromium.org/p/chromium/issues/detail?id=1001283

@bpasero I tested VSO and VS Code selfhost on Mac. Let me know if you still see this

**Comment by ericlaw1979** [comment]
FWIW, that fix landed in September, so it's unlikely to be related. 

Feel free to ping me directly if you find another repro.

**Comment by bpasero** [comment]
Confirmed, seems to be working again.
