### ISSUE TITLE
Add "Snippet: Surround With...."

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86397]
Snippets that use the $TM_SELECTION and/or $SELECTION variable should be grouped into a new "Surround With..."-command, e.g support selection with try-catch or if-else. We should also consider not showing such snippets in IntelliSense because the selection is always where users are typing.

**Comment by jrieken** [comment]
closing this in favour of https://github.com/microsoft/vscode/issues/62907

**Comment by jrieken** [comment]
After https://github.com/microsoft/vscode/issues/138564 and given that a dedicated command is more visible we should add this

**Comment by heartacker** [comment]
@jrieken hi, Thanks for your adding support for outside code
 
and could please add some identification for those snippet support `$TM_SELECTION` and/or `$SELECTION` when users are using `insert snippets` command

e.g.:
when using insert snippet, users never know which snippet is outside-code supported
- there is the ui:
![image](https://user-images.githubusercontent.com/1876302/151956385-32e4b65f-1e42-4223-bb9d-615a41c27889.png)
- and the snippet code from C# official extension
![image](https://user-images.githubusercontent.com/1876302/151956592-19b35b8b-7dff-4a41-ae43-804bb539ac85.png)

for that reason, I have to add some tip/text for the name of snippet when I develop the snippet extension.

https://github.com/heartacker/snippet-plus/blob/4472416d3ffa660f1f7733ea22be5a1ce8737608/snippets/cpp.json#L16-L35

after that, user could know that which is outside code supported.

![image](https://user-images.githubusercontent.com/1876302/151957294-9325e1ff-b2c8-4359-809e-f6347acb3769.png)


I could do it for myself and my extension, I there are many snippets that have no tip or identification

## propose
Please add some identification for those outside code supported in UI when users using insert snippet.

that will be useful and helpful for user to distinguish

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/151958325-6521edd1-d42e-47f5-9cef-1d7f96d424a7.png)

maybe some icon for text is good

**Comment by heartacker** [comment]
https://github.com/microsoft/vscode/issues/131308
BTW, there is another issues related to this. please

**Comment by heartacker** [comment]
@jrieken hi, should I file a new issue?

> @jrieken hi, Thanks for your adding support for outside code
> 
> and could please add some identification for those snippet support `$TM_SELECTION` and/or `$SELECTION` when users are using `insert snippets` command
> 
> e.g.: when using insert snippet, users never know which snippet is outside-code supported
> 
> * there is the ui:
>   ![image](https://user-images.githubusercontent.com/1876302/151956385-32e4b65f-1e42-4223-bb9d-615a41c27889.png)
> * and the snippet code from C# official extension
>   ![image](https://user-images.githubusercontent.com/1876302/151956592-19b35b8b-7dff-4a41-ae43-804bb539ac85.png)
> 
> for that reason, I have to add some tip/text for the name of snippet when I develop the snippet extension.
> 
> https://github.com/heartacker/snippet-plus/blob/4472416d3ffa660f1f7733ea22be5a1ce8737608/snippets/cpp.json#L16-L35
> 
> after that, user could know that which is outside code supported.
> 
> ![image](https://user-images.githubusercontent.com/1876302/151957294-9325e1ff-b2c8-4359-809e-f6347acb3769.png)
> 
> I could do it for myself and my extension, I there are many snippets that have no tip or identification
> 
> ## propose
> Please add some identification for those outside code supported in UI when users using insert snippet.
> 
> that will be useful and helpful for user to distinguish

**Comment by jrieken** [comment]
To verify

* open a typescript files
* select some code
* select F1 > Surround with Snippet > try-catch
* ensure the selected code is surrounded by the snippet

**Comment by IanMatthewHuff** [comment]
Verification looked good with both TS and CS files.
