### ISSUE TITLE
macOS Safari: cannot drag-n-drop files from Finder/Desktop into VS Code

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86398]
testing https://github.com/microsoft/vscode/issues/85986:

drag-n-dropping files from Finder/Desktop into VS Code has no effect.

**Comment by rebornix** [comment]
Can you provide more details? I didn't reproduce this issue with dragging a js file to the explorer view 

![Kapture 2019-12-05 at 11 14 45](https://user-images.githubusercontent.com/876920/70266011-7cfd0280-1750-11ea-890f-404b55c71f87.gif)

**Comment by weinand** [comment]
Strange, with the latest this is working fine now.
