### ISSUE TITLE
Debug popup collapses when mouse goes into the debug console

### ISSUE THREAD

**Issue by jmillwood** [Microsoft/vscode#8639]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:

1. While debugging with the debug console displaying, hover over an object so that the popup will partially be displayed in the debug console.
2. Move the mouse into the debug popup and start moving it down until is crosses into the debug console.
3. The debug popup will collapse.  As long as the mouse is in the code window section of the popup, you are OK.  But as soon as you drift into the debug console (you're still within the debug popup), the popup will collapse.
4. See the attachment

![debugwindowbug](https://cloud.githubusercontent.com/assets/6989056/16532408/614cab2e-3f97-11e6-82d6-27482b881184.png)

**Comment by isidorn** [comment]
Dup of #3528
