### ISSUE TITLE
выделение и копирование текста в Interactive Playground

### ISSUE THREAD

**Issue by Khvatov-Alexey** [microsoft/vscode#86393]
Issue Type: <b>Feature Request</b>

Доброго времени суток! Я столкнулся с такой особенностью, что в Interactive Playground невозможно выделить и скопировать текст. Мне это нужно было для того, чтобы было легче перевести некоторые участки текста на русский язык.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.3.9600

**Comment by IllusionMH** [comment]
Please provide English title and description so VS Code team can review your request.

If only purpose to copy text from Interactive playground is single time usage to provide translations -  you can use source file with all static content (with markdown markup) in [vs_code_editor_walkthrough.ts](https://github.com/microsoft/vscode/blob/e39717bd97d79289e4960d6df35a26111b4defac/src/vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough.ts)

Not sure if playground should support text selection and copying in general case.

**Comment by Khvatov-Alexey** [comment]
Oh, thank you. It's nice to quickly get an answer to such a small question. 
About copying in interactive Playground...OK, you can probably see the reasons why you need to prohibit copying. That answer is enough for me :)
