### ISSUE TITLE
macOS Safari: no custom context menus

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86391]
testing https://github.com/microsoft/vscode/issues/85986:

No custom context menus on macOS Safari.

**Comment by rebornix** [comment]
Can you check the Dev Tools and see if there are any errors there? It's weird to me that our custom code doesn't work.

**Comment by weinand** [comment]
Nothing in the console when trying to open the context menu:

![2019-12-06_12-10-56](https://user-images.githubusercontent.com/1898161/70319021-91f59680-1821-11ea-890b-e84fdb39f02e.png)
