### ISSUE TITLE
'Open File' missing from img diff

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86392]
* have a image in git
* make a modification to it
* the image-editor shows 'Open Changes'
* open the diff editor for that image
* 🐛 the editor still shows 'Open Changes' and not 'Open File'

<img width="702" alt="Screenshot 2019-12-05 at 12 03 00" src="https://user-images.githubusercontent.com/1794099/70229825-3ced4e00-1757-11ea-8cf0-cf3078810990.png">

**Comment by mjbvz** [comment]
Note that this also happens with binary files that don't use custom editors

**Comment by bpasero** [comment]
This can be explained easily: all commands in Git check for the `isInDiffEditor` context key which only exists for text diff editor. To fix this properly we need an new key such as `isSideBySideEditor` whenever the `SideBySideEditor` is active.
