### ISSUE TITLE
macOS Safari: "undo typing" doesn't work

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86394]
testing https://github.com/microsoft/vscode/issues/85986:

- edit some text in VS Code editor
- open Safari's "Edit" menu: there is a "Undo Typing" entry 
- execute the "Undo Typing"

Observe:
nothing happens

**Comment by rebornix** [comment]
Are you referring to `Edit -> Undo (Cmd+Z)` entry? I didn't reproduce this issue with latest code in Safari.

![undo](https://user-images.githubusercontent.com/876920/70266347-293ee900-1751-11ea-8ccb-61b70349393f.gif)

**Comment by weinand** [comment]
No, I'm referring to the native menubar ("Safari's Edit menu")
Using the VS Code Edit menu is not very intuitive for the basic edit operations...
