### ISSUE TITLE
Cosmetic - incorrect text 

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/vscode#86400]
We have written the needed data in
Issue Type: <b>Bug</b>

Open a large Json file.

You should see a warning about auto-formatting being disabled with a button that allows you to "forcefully enable features".

Whilst I like the mental image of commandingly smiting the mouse to conjure the formatting into existence, the correct usage is "forcibly" ;-) 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.48GB free)|
|Process Argv|C:\Users\neilm\AppData\Local\Temp\Rar$DIa18860.30456\2019_12_05___1209_38___637111445789559496.json|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
numbered-bookmarks|ale|6.2.1
code-gnu-global|aus|0.2.2
vscode-instant-markdown|dba|1.4.4
xml|Dot|2.5.0
gc-excelviewer|Gra|2.1.32
vscode-edit-csv|jan|0.2.5
python|ms-|2019.11.50794
remote-wsl|ms-|0.40.3
cpptools|ms-|0.26.2
csharp|ms-|1.21.8
powershell|ms-|2019.11.0
platformio-ide|pla|1.10.0
vscode-hexdump|sle|1.7.2
html-preview-vscode|tht|0.2.5

</details>

![forcefully](https://user-images.githubusercontent.com/9131337/70234872-863e9d00-1759-11ea-9ab6-2158d9d4c7ff.png)

**Comment by aeschli** [comment]
found this: https://english.stackexchange.com/questions/344858/what-is-the-difference-between-forcibly-and-forcefully

There are more usages of forcefully in comments for keybindings.

@Tyriar There are also some usages in terminal land (just in comments)

**Comment by Tyriar** [comment]
@aeschli I only see "force" and "forces" being used in `./src/vs/workbench/contrib/terminal`?

**Comment by aeschli** [comment]
@Tyriar This one I meant https://github.com/microsoft/vscode/blob/2bb6cfc16a88281b75cfdaced340308ff89a849e/src/vs/vscode.proposed.d.ts#L907
