### ISSUE TITLE
Compact folders: Context menu actions not focus aware when selection is set

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86408]
- open a remote WSL window
- clone https://github.com/eclipse/eclipse.jdt.ui.git
- set "explorer.compactFolders": true
- in the explorer, set the selection on  `org.eclipse.jdt.junit.runtime - src -org\eclipse\jdt\internal\junit\runner`
- Move the mouse over `jdt`, open the context menu and `Copy Relative Path'
Paste:
org.eclipse.jdt.junit.runtime\src
org.eclipse.jdt.junit.runtime\src\org
org.eclipse.jdt.junit.runtime\src\org\eclipse
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt\internal
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt\internal\junit
org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt\internal\junit\runner

-> expected `org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt`

- Open terminal: Opens on `org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt\internal\junit\runner`, expected `org.eclipse.jdt.junit.runtime\src\org\eclipse\jdt`
- Find in FIles: Contains full list, expected: just `jdt`

**Comment by isidorn** [comment]
Thanks for filling this. Getting this contexts properly is more tricky than I anticipated.
