### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by sarahjstacey15** [microsoft/vscode#86409]
Adding to string within a script using tags with spaces causes indentation of next line to go wrong. 

The issue seems to be having a space between div and class

`<script>
            var txt = "";
            txt += '<div class="row">'
                txt += '<p>paragraph example</p>'
                txt += '</div>'
            </script>`

<img width="440" alt="Screenshot 2019-12-05 at 14 40 10" src="https://user-images.githubusercontent.com/21659702/70244950-37026780-176d-11ea-9c31-0865750b4d5a.png">

<img width="454" alt="Screenshot 2019-12-05 at 14 41 18" src="https://user-images.githubusercontent.com/21659702/70245022-53060900-176d-11ea-987a-b6f74c556bc1.png">

**Comment by rebornix** [comment]
I'm not able to reproduce this issue in latest Insiders, if you are still seeing it you can try set `"editor.autoIndent": "advanced"` in your settings.
