### ISSUE TITLE
Php errors

### ISSUE THREAD

**Issue by zycog** [Microsoft/vscode#8640]
- VSCode Version:
- OS Version:
worked on this trying to validate php for 1 hour  used 
 Just for fun" 
  "php.validate.executablePath": "C:\inetpub\wwwroot",

and 
C:\Program Files (x86)\PHP\v5.3\
and 
C:\Program Files (x86)\PHP\v5.3
and 
C:\Program Files (x86)\PHP\
and 
C:\Program Files (x86)\PHP

" Invalid escape character in string Points to the php executable." 

this software can't Figure out were PHP is.? 
i can't imagine the hair-pulling for node js .........
.   
has anyone actually gotten this to work ?> 
whats the problem here.??? . 

Steps to Reproduce:

1. 
2.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
