### ISSUE TITLE
Can't connect to Jupyter notebook (only with VS Code)

### ISSUE THREAD

**Issue by davideps** [microsoft/vscode#86406]
I'm using the most recent VS Code on Windows 10 64bit with Anaconda 64bit 4.7.12 and Python 3.7.4. I can start jupyter notebook from the commandline and interact in a browser through port 8888. However, when I reboot and try to run a Jupyter cell in VS Code, I receive the error: 

**Error: Failed to connect to Jupyter notebook.  http://localhost:8888/ Error: Invalid response: 500 Internal Server Error**

I used VS Code's native support for Jupyter successfully for months. Security and Internet settings on my machine recently changed. I tried turning off the virus software and firewall, but that does not solve the issue. I'm not sure how else to troubleshoot. Please advise.

**Comment by octref** [comment]
Please report to https://github.com/microsoft/vscode-python
