### ISSUE TITLE
vscode.executeCodeActionProvider sometimes returns code actions with missing commands

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#86403]
Periodically in test runs, I see an issue where `vscode.executeCodeActionProvider` returns code actions that are missing their `command` (resulting in `Cannot read property 'command' of undefined` when I do `codeAction.command.command` - my code action never returns anything without a command). This came up before in #45124 but I think that was a different bug as this one is intermittent.

I had a similar issue about CodeLens doing the same #79805 which was a race condition. The fix looks like it was applied only on CodeLens code, so I wonder if this is the same issue and needs a similar fix applying here? @jrieken

**Comment by mjbvz** [comment]
@DanTup Do you have a small repo for the problem you can share?

**Comment by DanTup** [comment]
Not a reliable one - it's very intermittent on my CI builds. I hoped it might be a similar timing issue like #79805 that might be identifiable from the code. If that's not the case, I'll have a go at trying to make a repro (though it may take a while to get something reliable 😞)

**Comment by DanTup** [comment]
FWIW I don't think the CodeLens fix works in any case - I just saw a failure on GH Actions (Windows) that looks like the same issue again (`.command` on the `CodeLens` is undefined).

These race conditions make automated tests unreliable 😞

**Comment by mjbvz** [comment]
@jrieken I know we added a timeout to disposed of the code actions / code lenses. I thought that if the timeout is triggered, it would just result in an invalid command. Do you know why a command could potentially become `undefined`?

**Comment by DanTup** [comment]
> it would just result in an invalid command.

I've always seen `undefined` commands for these issues - I'm not sure what an invalid command would look like?

Out of interest, what's the drawback to setting the timeout to something much higher (for ex. 1 second)?

It doesn't seem like 1 second extra before cleaning something up is going to make much difference, but it'll make these sorts of races far less likely (esp. when running on slow machines with shared CPUs where there's no guarantee how quickly your code will resume).

**Comment by jrieken** [comment]
> Do you know why a command could potentially become undefined?

Only when the "real" command cannot be looked up. We patch a `$ident` property onto internal command objects and use that for lookup. Unsure if you copy commands somehow so that this information gets lost. 

I'd say this needs repro steps first. With LS we have a pretty popular customer of this API command we haven't heard of problems from them.  @DanTup please provide real repo steps and not a vague pointer to a sparingly failing test.

**Comment by DanTup** [comment]
Sorry, I thought because it'd come up with CodeLens it might just need a similar fix applying.

It's intermittent so hard to reliably reproduce - but it can easily be forced to occur by making the extension host busy (here I block it for for 100ms repeatedly - which is extreme but easily shows there is a race - and the extension host being busy for 100ms is not far-fetched):

https://github.com/DanTup/vscode-repro-86403

<img width="615" alt="Screenshot 2019-12-10 at 9 52 04 am" src="https://user-images.githubusercontent.com/1078012/70518711-be1b5b00-1b32-11ea-83d9-2d9b5c8cd9d5.png">

It's far worse on GitHub actions due to slow and shared CPU (burning 100ms is even easier), so almost every run failed very quickly there:

https://github.com/DanTup/vscode-repro-86403/runs/341632495#step:6:87

I don't think using wall-clock (at least in the measure of milliseconds) for things like this is a great idea. If your machine is slow, it's bad enough that things take a long time, but having them intermittently fail is super frustrating.

**Comment by DanTup** [comment]
@jrieken I don't understand why this was closed - my last comment gave a full repository that repros the issue with GitHub actions. Is there something more I should do?

**Comment by jrieken** [comment]
Sorry, wrong label but same outcome. We have not seen this happening in reality. If your emotions for this go beyond issue commenting you are welcome to provide a PR.

**Comment by DanTup** [comment]
It happens in my test runs quite a lot, that's why I raised it. Based on previous discussions I think this may be because of timeouts used to dispose these - would you accept a PR that increases the timeouts for these (assuming it fixes the issue)?

**Comment by DanTup** [comment]
These are the timeouts I'm suspecting based on the previous discussion:

https://github.com/hunghw/vscode/commit/3852e8c871ba47982ca23074e306de04c0fca6b5
https://github.com/hunghw/vscode/commit/e1f3f092f0aa7b4b70e70be10be56e527038479e
