### ISSUE TITLE
Download creates a folder 'root'

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86413]
- open a remote WSL window
- clone https://github.com/eclipse/eclipse.jdt.ui.git
- select `org.eclipse.jdt.junit.runtime/scripts` and choose Download from the context menu
- pick an empty folder as destination
- `root` is suggested as folder name. That's strange. Maybe it's related to the fact that the full path of `scripts` is `/root/eclipse.jdt.ui/org.eclipse.jdt.junit.runtime/scripts`. 

Instead of `root` I would expect `scripts`

**Comment by isidorn** [comment]
There are some other issues about the download command that cover this.
