### ISSUE TITLE
breadcrumb: functions are nested

### ISSUE THREAD

**Issue by frostius** [microsoft/vscode#86412]
- VSCode Version:1.40.2
- OS Version:Win 10

Breadcrumb shows function twice (nested) when cursor is inside of function

![bc](https://user-images.githubusercontent.com/3818866/70249162-9cd8fa00-1741-11ea-8481-b21952e1eeed.gif)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

/needsMoreInfo

**Comment by frostius** [comment]
I not sure what that means.  This seems like a pretty clear bug to me.


------ Original Message ------

**Comment by mjbvz** [comment]
Copy and paste the text from that screenshot into github

**Comment by frostius** [comment]
As requested:
```javascript
ruStupid.prototype.orLazy = function() {
}
```
![lazy](https://user-images.githubusercontent.com/3818866/70269498-20a5dd00-1768-11ea-97d0-926420d16c36.gif)

**Comment by mjbvz** [comment]
Stay classy... but next time just provide the minimal text from the start instead of wasting time

Also this doesn't seem to happen in VS Code insiders. Did you test on 1.41?

**Comment by frostius** [comment]
I have no desire to be part of your QA team.  Sorry for posting

**Comment by mjbvz** [comment]
@frostius Stop doing this. See #47198 for the same pattern of behavior

We cannot help you if you don't provide the information we ask for in a professional way

**Comment by frostius** [comment]
>>>We cannot help you if you don't provide the information we ask for in 
a professional way

I was not asking for help.  My intent was to help you by providing 
feedback about bugs in your product.  Since that seems to have been 
unhelpful, I closed the issue.  Not sure why that irritated you, but 
I'll stop posting bugs in the future as I am unable to spend the time to 
help you troubleshoot that you are demanding.

Your expectation that users provide you with "professional" bug reports 
seems unrealistic to me, but it will certainly help to keep the number 
of reported bugs down.

------ Original Message ------
