### ISSUE TITLE
When I enter the curly braces This line will be advanced by one space

### ISSUE THREAD

**Issue by jiangkuan2018** [microsoft/vscode#86410]
- VSCode Version: 1.40.2
- OS Version: MacOS Mojave 10.14.6 (18G103)

Steps to Reproduce:

1. When I enter the curly braces This line will be advanced by one space
2. JSX and TSX all get this problem

![h6nie-b0lh1](https://user-images.githubusercontent.com/19922382/70246933-76ec3d80-17b3-11ea-9fba-5c219a0e1a5c.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by LuigiDerson** [comment]
I have the same issue, I tested it in ubuntu and windows machines, and even with the insiders build.

**Comment by alexdima** [comment]
Copy-Paste friendly code:
```
import React from 'react';

function Test() {
    return (
        <div>
            <span>{</span>
        </div>
    )
}
```
