### ISSUE TITLE
Resolution adaption after switching from an external monitor

### ISSUE THREAD

**Issue by guanghaoch** [microsoft/vscode#86418]
Issue Type: <b>Bug</b>

After using the app on an external monitor with lower resolution, the UI is blurry.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|-psn_0_73746|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by deepak1556** [comment]
Seems to be https://github.com/electron/electron/issues/21393 , can you confirm if you are following similar steps outlined in that issue ?

**Comment by krupenja** [comment]
I am also having a similar issue with the steps similar to the ones in electron/electron#21393:
1. Connect MacBook to a non-retina display.
2. Open VSCode.
3. Unplug the display.

Interestingly, I only get the blurriness in the terminal:
![image](https://user-images.githubusercontent.com/26354715/76262631-90df6580-6265-11ea-8427-7fb21d7c3d9d.png)

**Comment by deepak1556** [comment]
Closing as upstream issue has been resolved.
