### ISSUE TITLE
Misalignment in icon

### ISSUE THREAD

**Issue by kichappa** [microsoft/vscode#86417]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/10088817/70254857-caf32400-17ab-11ea-97f4-3a38cc9c715b.png)

While git pushing, a small clock appears in the git logo on the activity bar. The outling (white) for the clock is not centred with it's blue bg. I'm not sure if it's an aliasing issue.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-jupyter-qtconsole|and|1.0.0
vscode-django|bat|0.19.0
my-nbpreviewer|col|1.2.2
jupyter|don|1.1.5
python-extension-pack|don|1.6.0
auto-close-tag|for|0.5.6
nbpreviewer|jit|1.2.2
MagicPython|mag|1.1.0
code-beautifier|mic|2.3.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
vscode-yaml|red|0.6.1
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.0
jinja|who|0.0.8
NbConverter|yig|1.4.0

</details>

**Comment by misolori** [comment]
@kichappa I'm not seeing this in the default setup:

![image](https://user-images.githubusercontent.com/35271042/70265853-1c6dc580-1750-11ea-9926-91a4738a8e48.png)


Do you have any zoom settings?

**Comment by kichappa** [comment]
@misolori Image in yours also has the problem: 2px on the right and 1 on the left of the white circle. Here's when I zoom the window.

![image](https://user-images.githubusercontent.com/10088817/70585196-773c6c80-1be9-11ea-9d1c-cbb5f3e9f3d4.png)

**Comment by misolori** [comment]
This is now centered:

![image](https://user-images.githubusercontent.com/35271042/71143658-3daec700-21d0-11ea-9d55-32e7e4033328.png)

![image](https://user-images.githubusercontent.com/35271042/71143678-4bfce300-21d0-11ea-938c-67511426bf6b.png)

**Comment by misolori** [comment]
Verification steps:
1. Use the [Notification Tester](https://marketplace.visualstudio.com/items?itemName=svipas.notification-tester) extension
2. Run the `Start Progress Badge` command
3. Inspect that the badge is centered like above

**Comment by kichappa** [comment]
Not yet!

![image](https://user-images.githubusercontent.com/10088817/71308716-e4d86c00-2425-11ea-9573-147656e16de6.png)

**Comment by misolori** [comment]
@kichappa this is fixed on Insiders
