### ISSUE TITLE
Error processing "restartFrame": Error: Internal error

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#86411]
I was testing https://github.com/microsoft/vscode/issues/85626, which works nicely, by debugging VS Code. The only inline action is restart frame, and when I click it I get this error in the debug console:
```
Error processing "restartFrame": Error: Internal error
    at Client.processMessage (c:\Users\alros\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:66:36)
    at LoggingSocket.<anonymous> (c:\Users\alros\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:42:48)
    at LoggingSocket.emit (events.js:205:15)
    at Receiver.receiverOnMessage (c:\Users\alros\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:200:13)
    at Receiver.dataMessage (c:\Users\alros\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\ws\lib\receiver.js:422:14)
    at c:\Users\alros\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\ws\lib\receiver.js:379:23
    at c:\Users\alros\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\ws\lib\permessage-deflate.js:298:9
    at c:\Users\alros\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\ws\lib\permessage-deflate.js:376:7
    at afterWrite (_stream_writable.js:483:3)
```
It happens on any of the frames and the ~~frame doesn't appear to restart.~~ frame does restart.

**Comment by isidorn** [comment]
This is coming from the node debug adapter.
The isse is that the node debug adapter can only restart the top frame. And currently we do not have a capaibiltiy for the node extnesino to notify vscode that this action should be disabled.

Assigning also to @roblourens 
fyi @weinand

**Comment by alexr00** [comment]
I see the error even on the top frame.

**Comment by isidorn** [comment]
I leave that up to @roblourens and @connor4312 since the error is coming from the extension

**Comment by roblourens** [comment]
Cool, this is not supported by Electron. Not only that but if you send restartFrame to the window then the window breaks. We don't really detect if we are debugging Chrome vs Electron but I guess I need to do that.

**Comment by roblourens** [comment]
Eh I take that back, I got into a bad state once but in other cases it seems fine to just ignore the error. Fixing in the DA.

**Comment by connor4312** [comment]
Fyi I had this happen on Node 10 putting together https://github.com/microsoft/vscode-pwa/pull/160. Switching my runtime version to 12 resolved the issue, and everything looked peachy in the traces, so I think it's some V8 issue.

**Comment by roblourens** [comment]
Yeah I filed an upstream issue then realized that it's fixed in Electron 7. I'm just going to leave this alone.

**Comment by roblourens** [comment]
Oh this affects extensionHost debugging too, I will work around it for this release

**Comment by isidorn** [comment]
Thanks for jumping on this Rob

**Comment by roblourens** [comment]
Can be verifid in chrome-debug starting now

**Comment by connor4312** [comment]
Verified works debugging VS Code
