### ISSUE TITLE
Option to keep React import at the the top when using Organize Imports

### ISSUE THREAD

**Issue by jaredpalmer** [microsoft/vscode#86416]
## Current Behavior

Organize Imports is great, but it _always_ sorts as it is designed to. This means that React imports within React files get pushed to the their proper sorted position. However, it is a widely accepted convention to keep React as the very first import in most codebases.

## Desired Behavior

Ability to specify/whitelist imports by position (perhaps using a priority). You could do it by glob or by language.

```json
{
  "importOrder": [
    {
      "package": "react",
      "order": 0,
      "language": "typescriptreact"
    }
  ]
}
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by jaredpalmer** [comment]
Thanks will do!
