### ISSUE TITLE
CustomExecution starts built-in extensions, displays error message if no workspace open

### ISSUE THREAD

**Issue by xorye** [microsoft/vscode#86419]
Running a `vscode.Task` with a `vscode.CustomExecution` automatically starts these 5 built-in extensions: 

* Grunt support for VS Code
* Gulp support for VSCode
* Jake support for VS Code
* NPM support for VS Code
* TypeScript and JavaScript Language Features

When one of these 5 built-in extensions are started when no workspace folder is open, this error message appears:
![image](https://user-images.githubusercontent.com/20326645/70257121-bc7b1d00-1757-11ea-9fca-a567de97a66a.png)

**Steps to Reproduce:**

1. Create a new VS Code extension that activates on startup and runs the folloing code:
```
	const presenterTask = new vscode.Task({ type: "test" }, vscode.TaskScope.Workspace, 'test', "test", new vscode.CustomExecution(async () => {
		return undefined as unknown as vscode.Pseudoterminal;
	}));
	
	await vscode.tasks.executeTask(presenterTask);
}
```

2. Run the extension in a new window and make sure that no workspace folder is open in that new window.

3. The error message appears 

**Does this issue occur when all extensions are disabled?:**
Yes, only if you don't disable all five built-in extensions listed above.
If those five built-in extensions are disabled, then no error message appears.

**Comment by alexr00** [comment]
I found that even with those extension disabled I still got the message. Thanks for the sample code!

**Comment by xorye** [comment]
No problem, thank you for looking into this.

This issue is closed so does this mean that this issue has been fixed? Or reopened somewhere?

**Comment by alexr00** [comment]
It is fixed on our master branch, but not yet available anywhere for you to try out yet. By the end of the week it should be available in our daily Insiders build: https://code.visualstudio.com/insiders/
