### ISSUE TITLE
typescrypt server crashes

### ISSUE THREAD

**Issue by gonza-lito** [microsoft/vscode#86422]
Issue Type: <b>Bug</b>

[Info  - 19:04:12.706] Using tsserver from: c:\Users\*****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 19:04:12.715] <syntax> Forking...
[Info  - 19:04:12.724] <syntax> Starting...
[Info  - 19:04:12.727] <semantic> Forking...
[Info  - 19:04:12.739] <semantic> Starting...
[Info  - 19:07:46.902] Killing TS Server
[Info  - 19:07:46.938] TSServer exited

VS Code version: Code - Insiders 1.41.0-insider (a63d88ec550107a66c08d813fb5d3c32c9e131a7, 2019-11-26T05:36:00.083Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.44GB (7.26GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
prettier-vscode|esb|3.11.0
remote-wsl|ms-|0.41.4
powershell-preview|ms-|2019.11.0
vscode-jest|Ort|3.0.2

</details>

**Comment by mjbvz** [comment]
Can you please check the TS Server log to see what the crash is:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. Back in VS Code, go to the `TypeScript` section of output panel
1. At the very top of this output, there should be a line that prints the path to the main server log. It should look like this (note the `<semantic>` part) :

```
[Info  - 4:06:59 PM] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20191111T144045/exthost1/vscode.typescript-language-features/tsserver-log-F2rDlk/tsserver.log
```

Please look through that log file for errors or stack traces (they should be near the end). If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by romanlex** [comment]
same issues
![image](https://user-images.githubusercontent.com/3369304/71182224-c12aef80-2286-11ea-9d41-de39604bc697.png)
Error from log
![image](https://user-images.githubusercontent.com/3369304/71182264-d6a01980-2286-11ea-8733-27b99e765345.png)

**Comment by romanlex** [comment]
I'm trying last insider build and have same error
![image](https://user-images.githubusercontent.com/3369304/71183138-7dd18080-2288-11ea-9fc8-1f2c3b76143c.png)
![image](https://user-images.githubusercontent.com/3369304/71183219-a5284d80-2288-11ea-97cc-8c6ee322b40c.png)
