### ISSUE TITLE
Tasks inputs accept shell types. 

### ISSUE THREAD

**Issue by jemo07** [microsoft/vscode#86429]
Hello 

While creating tasks for build process or other tasks, I find that the ${input:var} is limited to: 

Currently VS Code supports three types of input variables:

**promptString:** Shows an input box to get a string from the user.
pickString: Shows a Quick Pick dropdown to let the user select from several options.
command: Runs an arbitrary command.
Each type requires additional configuration attributes:

promptString:

description: Shown in the quick input provides context for the input.
default: Default value that will be used if the user doesn't enter something else.
pickString:

**description:** Shown in the quick pick provides context for the input.
options: An array of options for the user to pick from.
default: Default value that will be used if the user doesn't enter something else. It must be one of the option values.
Command:

**command:** Command being run on variable interpolation.
args: Optional option bag passed to the command's implementation

This is limiting as many development task require inputs from shell, be it declaration of system variables, shell scripts, etc. 

**Proposed Feature**

Support for inputs to accept shell types, for example

```{
            "label": "Flash Firmware",
            "group": "build",
            "type": "shell",
            "command": "idf.py",
            "args": ["-c","${input:setPort}","Flash"],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false
            }    
        }
    ],
    "inputs": [
        {
          "id": "setPort",
          "type" : "shell", 
          "command": "ls /dev/tty* | grep USB " }
        ]
}``` 

Expected behavior is output from execution in shell for the task is `idef.py -c /dev/sttyUSB0 flash` After assigning the output of `'/usr/bin/ls /dev/tty* | grep USB'` to the ${input:setPort} as defines in the task.json example provided. 

Thanks, 

JOSÉ

**Comment by devashish2203** [comment]
+1 for this.

I'm trying to set the CWD for a task to a folder defined by another input parameter, that requires me to read the output of `dirname ${input:testBinary}` and set that as the CWD.

On trying to use an extension from the market place to try to do this, the extension is limited by this issue.
https://github.com/augustocdias/vscode-shell-command/issues/10

VS Code providing this functionality directly would be great, if not having an API that allows other extensions to read input values provided for a task would help.

**Comment by augustocdias** [comment]
I have asked for that feature in the past but it was rejected. The reason that extension exists is because of [that issue](https://github.com/microsoft/vscode/issues/71296). 
Would be nice if the the extensions API could provide a way to resolve variables.
