### ISSUE TITLE
Double '...' after overflowing SCM provider row

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86423]
- Have a commit that isn't pushed
- Make the SCM viewlet narrower until the branch name and commit difference with the remote both overflow

![image](https://user-images.githubusercontent.com/323878/70267486-6ad09380-1753-11ea-83ab-92d309894b42.png)

Is it possible to make one of these disappear, and just have one show the `...`?

**Comment by misolori** [comment]
We can't make it all one as the branch and sync buttons are separate components. I'll try and adjust the min-width on the branch button.

**Comment by misolori** [comment]
I've improved how the text overflows in narrow views, the icons should never overflow (sometimes it might be cut off/hidden):

![image](https://user-images.githubusercontent.com/35271042/70577006-2aac4f00-1b5f-11ea-8bca-ce2870cec6f1.png)

![image](https://user-images.githubusercontent.com/35271042/70577014-326bf380-1b5f-11ea-8b20-45bd35e07126.png)
