### ISSUE TITLE
 Debug Failure. False expression: Script should not exist and not be open already

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#86433]
Now after a while without this crash it occured again today (latest insiders release). Here is what I did:
- Right click on a Folder in VSCodes explorer
- Select "New File"
- Type the name "HttpUtils.ts"
- Create a class body in the file
- Add an import using [Ctrl]+[Space]
- Rename "HttpUtils.ts" to "HTTPUtils.ts" (change part of the file name casing)
- Past a complex source code snipped into the file
- use intellisense [Ctrl]+[Space] to add an import
- use intellisense [Ctrl]+[Space] to add an import
  -> The message regarding the TS-Server that crashed multiple times appears

The resulting log looks similar to the one I posted in my last comment.

_Originally posted by @synth3 in https://github.com/microsoft/vscode/issues/83403#issuecomment-562246486_

**Comment by mjbvz** [comment]
[tsserver.log](https://github.com/microsoft/vscode/files/3929377/tsserver.log)

**Comment by mjbvz** [comment]
@sheetalkamat When renaming a file from `HttpUtils.ts` to `HTPPUtils.ts`, VS Code generates this sequences of calls

Close `HttpUtils.ts`

```
Info 669  [14:14:10.700] request:
    {"seq":120,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["c:/Users/matb/projects/san/83403/HttpUtils.ts"],"openFiles":[]}}
...
Info 673  [14:14:10.705] Project 'c:/Users/matb/projects/san/83403/tsconfig.json' (Configured) 0
Info 673  [14:14:10.705] 	Files (21)
	...
	c:/Users/matb/projects/san/83403/a.ts
	c:/Users/matb/projects/san/83403/HttpUtils.ts
	c:/Users/matb/projects/san/83403/b.ts
    {"seq":0,"type":"response","command":"updateOpen","request_seq":120,"success":true,"body":true}
```

Open `HTTPUtils.ts`:

```
Info 675  [14:14:10.706] request:
    {"seq":121,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"c:/Users/matb/projects/san/83403/HTTPUtils.ts","fileContent":"...","projectRootPath":"c:\\Users\\matb\\projects\\san\\83403","scriptKindName":"TS"}]}}
...
Info 692  [14:14:10.724] Project 'c:/Users/matb/projects/san/83403/tsconfig.json' (Configured) 0
Info 692  [14:14:10.724] 	Files (21)
	...
	c:/Users/matb/projects/san/83403/a.ts
	c:/Users/matb/projects/san/83403/HttpUtils.ts
	c:/Users/matb/projects/san/83403/b.ts
```

Note that the server is still taking about lowercase `HttpUtils.ts` here. Is it expected that TS Server always keeps using the old file name casing internally? How are clients supposed to handle this case?

**Comment by mjbvz** [comment]
@sheetalkamat I'm pushing a fix on the VS Code side for this. After the fix, even though TS server hands us back `HttpUtils.ts` in the edit for the quick fix, we will correctly apply the change to `HTTPUtils.ts`

**Comment by mjbvz** [comment]
I have decided to push this fix into the November milestone given that the bug is high impact when it happens.

To verify:

1. `git clone https://github.com/mjbvz/83403.git` into VS Code
1. Open `HttpUtils.ts`
1. Verify that intellisense is working
1. Now, with the file still open, rename `HttpUtils.ts` to `HTTPUtils.ts`
1. Wait a few seconds and make sure intellisense is working  in the file
1. Then trigger the quick fix on `b` to add the missing import

Make sure there is no crash

**Comment by mjbvz** [comment]
Note that the fix isn't in the most recent insiders build. You need to wait until the next one kicked off tonight

**Comment by sheetalkamat** [comment]
microsoft/TypeScript#34622 should fix the casing issues...
