### ISSUE TITLE
Persist and restore window when opening multiple

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#8643]
- VSCode Version:1.3.0 insider (July 1 2016)
- OS Version:Windows 10

Steps to Reproduce:
1.  Open vscode, change app size/position, exit
2. Re-open vscode - app should use last size/position
3. Open additional instance using CLI (vscode -n <some folder>) - app uses default window size/position

**Comment by bpasero** [comment]
@mfrost66 we do not store any view state when you open an empty instance, only when you open a folder. I am marking this as duplicate, there are issues filed for this already.

**Comment by mfrost66** [comment]
The second instance is to a folder - it restored correctly as the 1st
instance, just fails if opened as the 2nd instance.

**Comment by bpasero** [comment]
True, valid request then.

**Comment by Earl-Brown** [comment]
I have a similar situation.  I don't open folders, I just open VSCode, then use the File menu to open a folder.  But I have to resize VSCode every time.

I think the solution to both concerns would be to store the window metrics in the workspace file, then restore them when the "workspace is opened".

I looked for a plugin, didn't find one.  Looked for an API, didn't find one.  So maybe it might be useful to add  some API/Extension features to allow this kind of thing?

**Comment by bpasero** [comment]
This works if you configure `window.restoreWindows` accordingly.
