### ISSUE TITLE
Check update not work

### ISSUE THREAD

**Issue by zhaowy313** [microsoft/vscode#86438]
Issue Type: <b>Bug</b>

Help -> Check for updates -> Server return 404

VS Code version: VSCodium 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-27T10:22:53.349Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.7.0
flutter|Dar|3.7.0
vim|vsc|1.11.3

</details>

**Comment by kieferrm** [comment]
@zhaowy313 please file the issue against VSCodium.
