### ISSUE TITLE
Links in enum setting values can't be clicked

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86431]
From https://github.com/microsoft/vscode/issues/86182

- Find the referenced link in the setting GUI
- Try to click it 
- The select widget is hidden and the link is not opened

**Comment by Tyriar** [comment]
Not fixed, the widget stays open but this exception is hit:

![image](https://user-images.githubusercontent.com/2193314/73392426-a76dc680-428e-11ea-957f-e01806b8f0a7.png)

**Comment by roblourens** [comment]
Works for me. Can you show me or set a breakpoint to see what we call `open` with?

**Comment by roblourens** [comment]
- We call `openerService.open("https://github.com/xtermjs/xterm.js/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Faddon%2Fwebgl")`
- The URI is parsed correctly then eventually it fails inside uri.toString

Do you know what's going on @jrieken? Why would it think `_formatted` is a readonly property? I have no clue

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/89624, fixed in master
