### ISSUE TITLE
Find symbol stops highlighting updates

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86434]
In vscode.d.ts find symbol "register", notice that the highlighting in the list stops as "reg" because that's when the items in the list no longer move around.  I expect the entire word to be bold as it's matching:

<img width="398" alt="Screen Shot 2019-12-05 at 2 31 32 PM" src="https://user-images.githubusercontent.com/2193314/70279797-05d56780-176c-11ea-8931-e8905dcb57d1.png">

Pressing T will update all items except the focused one.

<img width="180" alt="Screen Shot 2019-12-05 at 2 33 22 PM" src="https://user-images.githubusercontent.com/2193314/70279914-40d79b00-176c-11ea-98d8-4b584b4e1397.png">

**Comment by jrieken** [comment]
Not sure what you are doing but for me this works - when typing or pasting that work.

<img width="950" alt="Screenshot 2019-12-06 at 08 56 16" src="https://user-images.githubusercontent.com/1794099/70306107-45e92880-1806-11ea-91ca-fd66122c3c38.png">

**Comment by Tyriar** [comment]
@jrieken happens on my home computer as well, both machines are Windows 10. It works fine on my macbook

**Comment by jrieken** [comment]
I could not reproduce on windows... I suspect that this is a rendering issue, not a matching issue. Either some dom-reuse issue with the tree or some debounce issue. The next this happens can you then inspect the element and see if highlight spans are there? 

> Pressing T will update all items except the focused one.

What happens when you delete the T again?

**Comment by Tyriar** [comment]
It's working now, weird. I suspect it was related to when the list viewport not updating when only items outside the viewport changed removed. Will keep an eye out if it happens again

**Comment by jrieken** [comment]
> Will keep an eye out if it happens again

Yes please! We have seen something similar with completion items and also suspected a painting/redraw issue and also didn't understand what was going all. Both use the highlight label...
