### ISSUE TITLE
Red breakpoint no longer show up

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86439]
Repro:

- Set `"debug.showInlineBreakpointCandidates": false`
- Set a breakpoint
- Hit the breakpoint
- Previously I would see the yellow arrow on top of red dot. Now red dot do not show at all 🐛 

Before hitting:

![image](https://user-images.githubusercontent.com/4033249/70284545-340d7400-1779-11ea-810d-72a5d314305d.png)

After hitting:

![image](https://user-images.githubusercontent.com/4033249/70284551-3b348200-1779-11ea-9159-3040dc7ae977.png)

I'm using https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-minimal-sample

**Comment by octref** [comment]
Stable:

![image](https://user-images.githubusercontent.com/4033249/70284609-72a32e80-1779-11ea-8378-d8da73171eb2.png)

**Comment by isidorn** [comment]
Thanks for filling. Dup of https://github.com/microsoft/vscode/issues/85148
