### ISSUE TITLE
Unable to delete multiple Watch debug variables simultaneously via hotkey

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#86445]
Issue Type: <b>Feature Request</b>

A user should be able to hit the delete key to delete all selected variables in the Watch drop-down tab when in debug mode. You can right click on the selected variables and click the relevant button to delete all selected but the delete key should definitely be able to do this obviously.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by ariffjeff** [comment]
Thank you!

**Comment by isidorn** [comment]
Welcome. You can try it out in vscode insiders from next week or the stable from January.

**Comment by ariffjeff** [comment]
Seems to work great, thanks. 

Also if you do the original method of deleting multiple Watch expressions via right click and "Remove All Expressions", this option appears to be missing the "Delete" hotkey label next to it, which in contrast appears next to the "Remove Expression" option immediately above it.

**Comment by isidorn** [comment]
Great, adding verified label.
Yeah that is expected, since remove all expression does not have the hotkey assigned.
