### ISSUE TITLE
Terminal Crash in VSC

### ISSUE THREAD

**Issue by HsunGong** [microsoft/vscode#86442]
Issue Type: <b>Bug</b>

I use WSL-remote extension in VSC.
When I open terminal in VSC, after 1/2 commands, the terminal can not accept anything. And when I open a new terminal, it just not show the interface.

However, the terminal works fine when i open cmd-wsl only. And `reload-window` can make terminal work again.

In Windows Task Manageer, I found `node` in wsl can not end, while terminal crash.

All happens after I update VSC.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 3.10.0-693.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|Memory (System)|15.85GB (7.91GB free)|
|VM|0%|

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
code-settings-sync|Sha|3.4.3
vim|vsc|1.11.3
Bookmarks|ale|10.6.0
xml|Dot|2.5.0
gitlens|eam|10.2.0
shell-format|fox|6.1.3
todo-tree|Gru|0.0.162
bash-ide-vscode|mad|1.3.3
python|ms-|2019.11.50794
indent-rainbow|ode|7.4.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you try enabling escape sequence logging and see what happens before and after the terminal stops working? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging
