### ISSUE TITLE
Array<number>.sort() is sorting using string comparison

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#86440]
This was the root cause for #84523
```ts
[1,2,3,4,5,6,7,8,9,10].sort()
// [1, 10, 2, 3, 4, 5, 6, 7, 8, 9]
```

We call `sort()` without a comparator on `number[]` in the following locations:
- https://github.com/microsoft/vscode/blob/196aeda027bd5fd10367d5bbd6d8faf8d45f0f40/src/vs/base/browser/ui/list/listView.ts#L847
- https://github.com/microsoft/vscode/blob/196aeda027bd5fd10367d5bbd6d8faf8d45f0f40/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L693

@joaomoreno @Tyriar Please review those two places

**Comment by Tyriar** [comment]
Not a big deal on terminal side but still a bug.

**Comment by joaomoreno** [comment]
That's crazy. Not a big deal on list side.

**Comment by mjbvz** [comment]
Marking this as debt. Let me know if there was anything to verify
