### ISSUE TITLE
Intellisense suggestions - jump to next types of completions

### ISSUE THREAD

**Issue by purplecandle** [microsoft/vscode#86447]
It would be fantastic to make shortcut for this action. Sometimes it's too slow to scrolldown to desired types of completions (Values and Enumerations, for example) , but I don't want to turn off other types too.

**Comment by jrieken** [comment]
How should that work? Suggestions aren't grouped by type, they are sorted by rank and different types are interleaved, e.g there could 10 targets for "jump to value"

**Comment by purplecandle** [comment]
In my [case ](https://i.gyazo.com/1ec768f14a62ea83a4734096d6196a35.mp4)(SCSS), they're grouped by type. Better make it available only for certain file types

**Comment by jrieken** [comment]
> In my case (SCSS), they're grouped by type. 

But only when having no prefix, e.g with your sample, type `g` and it's likely not grouped anymore.

**Comment by purplecandle** [comment]
> But only when having no prefix, e.g with your sample, type `g` and it's likely not grouped anymore.
hmm. Okay. Let's look from the other side. When I'm typing 'overflow" property, I'd like see available values for that property at the top of suggestions list. I can't order suggestions types, only disable. In case I don't know the exact property value name, I should  scroll to them. All over the suggestions right to the 'Values and Enumerations' suggestion group. How can I optimize it?
