### ISSUE TITLE
same file opened twice in different tabs

### ISSUE THREAD

**Issue by nvkokorin** [microsoft/vscode#86449]
Hi, when the opened workspace or folder contains symbolic link or directory junction (created with mklink) sometimes files does not opening properly - same file can be opened from differ location. As result we can see two tabs with same files but one from physical path and other - from linked path.

**Comment by birgersp** [comment]
You should write up some steps to reproduce the error

**Comment by nvkokorin** [comment]
I'm not sure that this reason but may be problem in the php xdebug extension
so, steps here
https://github.com/felixfbecker/vscode-php-debug/issues/382

**Comment by octref** [comment]
If it's not php extension's problem, feel free to report a new one or reopen this one.
