### ISSUE TITLE
intellisense suggestions based on cursor position / language type cursor is currently positioned in

### ISSUE THREAD

**Issue by CrankyWebDev** [microsoft/vscode#86446]
Issue Type: <b>Feature Request</b>

I apologize if this is a duplicate feature request. I searched around a bit but was unable to find this specific suggestion.

In PHPed (nusphere) the intellisense-like engine goes a step further and suggests based on cursor position. So if the cursor is in js, it only shows js suggestions, php...php suggestions, html... html suggestions, etc etc.

That doesn't appear to be the case with vscode intellisense which seems to only suggest based on defined document type shown in the bottom right corner.

As you can imagine, intellisense doesn't feel all that intelligent when transitioning from PHPed environment to vscode.

VScode has dozens more features that make using it more appealing but intellisense desperately needs an update to only suggest based on the type of code the cursor is currently in.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
It would be up to the language extensions to implement this.
