### ISSUE TITLE
Minimap size setting acces made available via F1

### ISSUE THREAD

**Issue by CuoreneroSangueblu** [microsoft/vscode#86458]
F1 and filtering on minimap to resize it instead of looking in settings and modify its value (1,2,3,...)

This could be interesting waiting for minimap resizable by drag with mouse, which is surely more resource consuming to be implemented (a request already exists for this  [https://www.github.com/microsoft/vscode/issues/84179](url) )

Resizable map is very useful as in open spaces often people changes desk from a day to another or during the same working day, so screens with different resolutions are used

**Comment by CuoreneroSangueblu** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Drag to resize minimap (#84179)](https://www.github.com/microsoft/vscode/issues/84179)

Not a duplicate, just an alternative and inexpensive improvement

**Comment by hediet** [comment]
I think an extension might help here.
