### ISSUE TITLE
iPadOS: cannot resize sidebar via touch

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86456]
Refs: https://github.com/microsoft/vscode/issues/85990

I can not resize the sidebar sash easily, works fine for editor sashes. Maybe we should increase the size of the sashes when touch is enabled.

**Comment by rebornix** [comment]
Agree, we can probably adding some affordance to the sash especially when the sash is being clicked.

**Comment by bpasero** [comment]
I am no longer seeing this, seems to work fine now.
