### ISSUE TITLE
File preview doesn't refresh when run command creates a file.

### ISSUE THREAD

**Issue by vietanh74** [microsoft/vscode#86454]
When I create a file via VS Code command line, the project file preview doesn't refresh with this file created.
eg: `php artisan make:model`

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-37-generic

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
What is the project file preview. Can you attach a screenshot?

**Comment by vietanh74** [comment]
Thank @isidorn.
When I create a file in the project via the terminal in `VS Code`, this file doesn't show in the preview area.

Screenshot: https://prnt.sc/q94tq4

**Comment by isidorn** [comment]
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by vietanh74** [comment]
It worked! Thanks for support @isidorn.

**Comment by isidorn** [comment]
Great, closing this then.
