### ISSUE TITLE
rg code helper, occupies 600+% CPU in Mac

### ISSUE THREAD

**Issue by yumikohey** [microsoft/vscode#86450]
<img width="348" alt="Screen Shot 2019-12-05 at 11 49 46 PM" src="https://user-images.githubusercontent.com/3360621/70305845-3a701000-17ba-11ea-9ab3-fafadaf6025f.png">

**Comment by JacksonKearl** [comment]
Were you performing a workspace text search at the time you observed this?

**Comment by yumikohey** [comment]
@JacksonKearl  It happens whenever I open VSCode now. I can kill this `rg`, but seems will cause some functionality loss .

**Comment by JacksonKearl** [comment]
You can kill `rg` without loss of functionality, a new instance will be spawned as needed. Are you on inisders?

**Comment by aiqingr** [comment]
I have the same issue. Even though sometimes I just leave VS code open, the CPU is able to be up to 600%. I ever tried to close VS code, but it didn't work. I have to terminate code helper renders to reduce my CPU rate.

**Comment by yumikohey** [comment]
@JacksonKearl  the version is Version 1.27.1 (1.27.1)

**Comment by JacksonKearl** [comment]
That version is over a year old (August 2018). We’re currently on 1.41. Is there something preventing you from updating? We may have fixed this over the past year.

**Comment by krinklesaurus** [comment]
Same problem running the latest version

![Screen Shot 2019-12-18 at 10 54 24 AM](https://user-images.githubusercontent.com/8155836/71075750-e5060c80-2184-11ea-9bc2-c76b60a97be0.png)
![Screen Shot 2019-12-18 at 10 55 06 AM](https://user-images.githubusercontent.com/8155836/71075756-e800fd00-2184-11ea-8866-8a0fa0e58bd1.png)

**Comment by medikoo** [comment]
Same problem with v1.41.1

I started to observe that after I've upgraded to Catalina. Maybe it's related to its fsaccess security features

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Reload the window to get the rg processes to start again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

This should tell us why teh search started

**Comment by medikoo** [comment]
@roblourens I observe it after I do search in a project. I close search and `rg` stays forever on 100% CPU.

It happens in projects where I have linked npm packages in `node_modules` (some links lead to `/usr/local/lib/node_modules`).

There was no such issue on Mojave. It might be that on Catalina there's some problem when search involves files that are outside of user folder

**Comment by roblourens** [comment]
What if you disable `search.followSymlinks` @medikoo?

**Comment by medikoo** [comment]
> What if you disable search.followSymlinks @medikoo?

It doesn't hang, but obviously search is not made in symlinked folders (which in some cases is desired)

**Comment by roblourens** [comment]
Sure but that's a useful hint, thanks for testing it

**Comment by JacksonKearl** [comment]
Are you still seeing runaway ripgrep processes on the latest vscode (1.50)? It's a known issue that ripgrep sometimes has perf problems when dealing with symlinks but it shouldn't cause high cpu use outside of running a search.
