### ISSUE TITLE
"Stage Changes" command should be called "Add"

### ISSUE THREAD

**Issue by arnolde** [microsoft/vscode#86453]
I want to suggest reopening issue  #47876, it was closed too fast and I don't agree that "we would just get issues pulling in the opposite direction". The whole world uses "add" instead of "stage" and calling it "stage" is wasting thousands of people's time searching for "add" and worsening the general vscode experience.

Maybe the git superusers don't mind, or even prefer "stage", but I'm willing to bet 90% of the vscode users just want the UI to feel like git commandline and most other tools.

**Comment by joaomoreno** [comment]
Reopened original
