### ISSUE TITLE
Doubled cursor in HTML files causes doubled content

### ISSUE THREAD

**Issue by varadero** [microsoft/vscode#86455]
Issue Type: <b>Bug</b>

When inside .html file and you enter the opening or closing tag you get second cursor at the same place inside the other tag. Now if you press arrow keys in order to exit the tag (or END key if the tag is the only content in the line) you are outside the tag but the cursors are still 2. Now if you start typing you get doubled content - after the opening and also after the closing tag.

Also, if you have tag on a single line and you enter the opening or closing tag and try to comment the line, the result is wrong.

Look at the attached animated GIF.

![vscode-double-cursor-bug](https://user-images.githubusercontent.com/7610713/70308981-23aad700-1815-11ea-9247-b2a04dde138f.gif)

VS Code version: Code - Insiders 1.41.0-insider (bbf00d8ea6aa7e825ca3393364d746fe401d3299, 2019-12-05T06:56:28.532Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.20GB free)|
|Process Argv|--folder-uri file:///c%3A/dev/azavista/azavista-servicelib|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-icons|vsc|9.6.0

</details>

**Comment by octref** [comment]
If you have latest insiders version, the mirrored cursor should be gone here:

```html
<div>|
</div>|
```

This is a new feature. You can read about it in https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_41.md. You can also turn it off by `html.mirrorCursorOnMatchingTag: false` if you don't like it.

My hope is it helps with majority of editing scenarios in HTML — changing opening/closing tags at the same time. When you have it enabled, indeed commenting out while you have 2 cursors on the same line could cause trouble. But it helps with this case:

```html
<|div>
</|div>
```
