### ISSUE TITLE
Powershell Core exiting with unexpected error on ctrl+c

### ISSUE THREAD

**Issue by techsaau** [microsoft/vscode#86459]
Install powershell terminal and debug\run any script or run azure function.
click ctrl+c to exit from console, you receive below error

The terminal failed to launch properly because your system has legacy console mode enabled, uncheck "Use legacy console" cmd.exe's properties to fix this.

Even this is already unchecked.

![image](https://user-images.githubusercontent.com/46290126/70312074-26a4c800-1813-11ea-90b7-b874d49a1ad4.png)

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}        
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by Tyriar** [comment]
Also what version of vscode?

**Comment by techsaau** [comment]
VScode was not allowing me to report directly via tool. It redirected me to this page.

VScode:

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362


Windows:
Microsoft Windows [Version 10.0.18362.476]

Extensions list:
christian-kohler.path-intellisense
DotJoshJohnson.xml
jasonnutter.search-node-modules
McCarter.start-git-bash
ms-azuretools.vscode-azurefunctions
ms-vscode.azure-account
ms-vscode.azurecli
ms-vscode.js-debug-nightly
ms-vscode.powershell
rebornix.ruby
Tyriar.shell-launcher
wingrunr21.vscode-ruby
xabikos.JavaScriptSnippets


[settings.zip](https://github.com/microsoft/vscode/files/3940259/settings.zip)

**Comment by rohith** [comment]
![terminal crash](https://j.gifs.com/1Wp2mq.gif)

Terminal crashes when pressing `Ctrl + C`
Terminal is set to `pwsh` (PowerShell Core installed as a dotnet global tool)

**Comment by Tyriar** [comment]
This message shows when the exit code is 3221225786:

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/common/terminal.ts#L68

https://github.com/microsoft/vscode/blob/d8d87f5c456e8d69e23dbac97fdb8c7aad8120c6/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1045

Looks like https://github.com/microsoft/terminal/issues/1894 is the underlying issue, good find @rohith

**Comment by rohith** [comment]
It's fixed (at least for me) after upgrading to PowerShell `v7` which comes with a fix to unexpected `Ctrl+C` behavior powershell/powershell#11959

**Comment by techsaau** [comment]
after upgrading it to latest version, issue has been resolved.
