### ISSUE TITLE
Debugging fails if Stopped event occurs before command Response.

### ISSUE THREAD

**Issue by richardstanton** [Microsoft/vscode#8646]
There appears to be an issue with the VS Code Debug Protocol. When a step or continue command is issued it is possible to get a stopped event before the command response. This occurs occasionally in the C# and C++ debugger extension. When this occurs you can no longer debug with VS Code. It no longer appears in break mode, but you cannot get out without stopping debugging.

**Comment by weinand** [comment]
@richardstanton this issue has been discussed in #7325:

An adapter should only send an event after sending back the response for the command that triggered the event.

The original problem that made us enforcing the correct order is #5966.

/cc @isidorn

**Comment by richardstanton** [comment]
Please help me understand this a bit better. When reading the original bug #5966, it appears the fix was to prevent issuing multiple step/continue commands until a stopped event was received. That should not influence this. After a command is issued, shouldn’t it wait until the response is received before processing events? In similar situations this can be handled by putting events in a queue until the command response is received. Based on #7325 this obviously effects other debug adapters in addition to C# and C++, it seems like this would also require more onus on debug adapter writers.

**Comment by richardstanton** [comment]
@weinand Hi, I had a question this morning, but forgot to include the @. Sorry.
