### ISSUE TITLE
Context menu actions are prefixed with "Debug:"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86465]
* pause on a breakpoint
* select some text
* open editor context menu
* 🐛 some commands are prefixed with 'Debug: ' which seems to be part of the label and not the explicit category

<img width="507" alt="Screenshot 2019-12-06 at 11 53 41" src="https://user-images.githubusercontent.com/1794099/70317929-11359b00-181f-11ea-9891-bb36d497161d.png">

**Comment by isidorn** [comment]
Makes sense, those prefixes should not be there.

**Comment by isidorn** [comment]
Went with the following. Decided on `Evaluate in Debug Console` to give more clarity and context

![Screenshot 2019-12-10 at 15 48 51](https://user-images.githubusercontent.com/1926584/70539903-9c3acc00-1b64-11ea-9b47-7bd2a4519cb8.png)
