### ISSUE TITLE
Breakpoint and stackframe class name cleanup

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86469]
Hi @misolori 
Sorry for not providing this feedback earlier since I was in vacation mode when we did the breakpoint css refactoring. Here are some issues I am seeing:

* There was a className which I did not fully understand and which I removed `codicon-debug-breakpoint-stackframe-dot`
* There is no class name that repesents just the top stack frame without the breakpoint. There is `codicon-debug-breakpoint-stackframe` but there shuold be just `codicon-debug-stackframe`

I plan to:
1) Rename `codicon-debug-breakpoint-stackframe` to `codicon-debug-stackframe`
2) So if there is just the class `codicon-debug-stackframe` we decorate just the stacframe, if there is also `codicon-debug-breakpoint` we decorate both combined
3) Bring back the inline breakpoitn and stackFrame decoration

There are 3 places where we decorate breakpoints: breakpoint view, glyph margin and inline in the editor. Due to those things might be overly complicated and I will try to clean this up.

Feedback very welcome on how to furhter simplify this.

**Comment by isidorn** [comment]
@misolori I have started a bit with the cleanup. You can see the attached commits for reference. I hope this simplifes the structure and if you have questions do let me know and I can explain more.

**Comment by isidorn** [comment]
@misolori  One of the missing things is that the call stack decoration is not rendered inline - there is just an empty area. I am not sure how you did the rendering in the glyph margin, and what is exactly missing when it is an inline decoration. To repro have the following sample:
```
debugger
for (var i = 0; i < 100; i++) {
    console.log('helllo theher')
}
```
Once you step over the for has multiple statmens so there should be an inline decoration in the editor.

I will continue on this tomorrow, but just in case you have ideas on how to fix let me know.

**Comment by misolori** [comment]
Inline stack decorations are now in:

![image](https://user-images.githubusercontent.com/35271042/70734679-8989d980-1cc1-11ea-8ab1-32664db3e5f2.png)

**Comment by isidorn** [comment]
Thanks a lot!
I have also pushed some cleanup.
There are stil quite some hacks, however I feel this is in a better spot than before, thus closing.
