### ISSUE TITLE
--new-window is broken when used with absolute --folder-uri

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode#86473]
- VSCode Version: 1.40.2
- OS Version: Pop!_OS 19.04

Steps to Reproduce:

1. Open a project. For example, let’s say a clone of the VSCode repository.
   ```sh
   code .
   ```
2. Open a file in this folder in a new window. This will work.
   ```sh
   code --folder-uri . --new-window --wait package.json
   ```
3. Now do the same, but specify an absolute path.
   ```sh
   code --folder-uri "$PWD" --new-window --wait package.json
   ```
   This doesn’t open a new window.

Does this issue occur when all extensions are disabled?: Yes

Real use case: My git [mergetool](https://github.com/remcohaszing/dotfiles/blob/master/.local/bin/mergetool) has been broken for a while now.

**Comment by aeschli** [comment]
`--folder-uri` requires a URI. Something like `--folder-uri file://home/jo/tests`
