### ISSUE TITLE
The window has crashed

### ISSUE THREAD

**Issue by TotzkePaul** [Microsoft/vscode#8647]
- VSCode Version: 1.3.0-insiders
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Install VS Code
2. Open Folder with 12 Mb html file.
3. "The window has crashed"

There isn't a noticeable increase in memory or CPU usage. Running as Admin or opening it as a single file makes no difference.

This seems similar to "Crashing/failing to open on new install #8400" except that it seems that I need to open a file first.

**Comment by bpasero** [comment]
@TotzkePaul can you attach the file please?

**Comment by TotzkePaul** [comment]
I was able to reproduce with non-useful data.

https://github.com/TotzkePaul/SpacesVsTabs/blob/master/Test.html#L1

**Comment by TotzkePaul** [comment]
also not fixed with the latest VS Code

**Comment by TotzkePaul** [comment]
It seems to be because there is a large amount of data in a value attribute. Removing that tag but leaving that data behind in a div doesn't cause an issue.

**Comment by alexandrudima** [comment]
The crash is due to OOM

**Comment by alexandrudima** [comment]
The problem is that the hand-written HTML tokenizer tries to build up the `attributeValue` in its `State` object and holds on to O(N^2) memory because each state is cloned at the beginning of a line.

**Comment by alexandrudima** [comment]
![image](https://cloud.githubusercontent.com/assets/5047891/16767965/a676ed98-484a-11e6-988b-b4cff714160c.png)

**Comment by TotzkePaul** [comment]
So I removed all the "\n\r" from the file and I got "The window is no longer responding. You can reopen or close the window or keep waiting. I'm not sure if I understood what you meant.

**Comment by jrieken** [comment]
@aeschli Correctly if I am wrong but we will change to textmate for html this milestone, right?

**Comment by aeschli** [comment]
@jrieken Not sure if already in this milestone.
As it's going to stay in the standalone editor anyway, I will start working on a fix.
From what I see it's not really necessary to have the attribute value as part of the tokenizer state.

**Comment by TotzkePaul** [comment]
I tested it out and works great! thanks!
