### ISSUE TITLE
VS Code Freezes When Rendering Markdown

### ISSUE THREAD

**Issue by tgrux** [microsoft/vscode#86477]
- VSCode Version: 1.40.2
- OS Version: Mac OS 10.14.6 (Mojave)

Steps to Reproduce:

1. Open VS Code
2. Open Markdown file
3. Preview Markdown file
4. VS Code freezes and I have to force quit

Does this issue occur when all extensions are disabled?: Yes
VS Code Insiders: Still occurs

**Other Notes:**

This also happens after installing a plug-in, when the plug-in informational page tries to come up.  Because of this I can’t ever install any plugins because they always render a page after first being installed.

Additionally, my company does block the ability for VS Code to perform an update.  Is there anyway for me to tell if this behavior is due to a security policy on my computer?

**Comment by tgrux** [comment]
Update on this.  I was right that some type of firewall rule was causing the issue.  I do think this needs addressed though, the error doesn’t seem handled and is crashing the IDE

**Comment by tgrux** [comment]
I was able to get someone else to reproduce this issue in my organization, so it seems like maybe my company is blocking some type of network request.  Is there anyway for me to find out what is being blocked?

**Comment by mjbvz** [comment]
Can you please try looking in the dev tools to see if there are any errors:

1. In VS Code, run the `Developer: Toggle developer tools` command
1. Then reproduce the issue
1. See if there are any logs in the developer console

**Comment by tgrux** [comment]
When starting up VSCode, I get the following error in the console (doesn't seem to be related):

`ERR No application in the Launch Services database matches the input criteria.   workbench.desktop.main.js`

When reproducing the error, I do not get any console errors (it is frozen).  The network requests tab shows the last request was to an image: "preview-dark.svg."  I can't see if my corporate proxy blocked anything since the tool is frozen.

**Comment by deepak1556** [comment]
@tgrux this is most likely a renderer crash, can you follow the steps outlined to get a stacktrace ?

```
// from terminal
$ export ELECTRON_ENABLE_LOGGING=1
// launch vscode with following
$ /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron path-to-your-test-folder --renderer-startup-dialog
```

The above will print logs like the following in the terminal once vscode is started and the code will be blank. This is expected, as we are now pausing the renderer process from starting so we can attach a debugger to it.

```
[68163:1208/215533.967533:ERROR:content_switches_internal.cc(110)] Renderer (68163) paused waiting for debugger to attach. Send SIGUSR1 to unpause.
```

The number within `()` is the process id, now attach lldb to it

```
// Again from a new terminal tab
$ lldb /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
// Once lldb attaches, run the following in its prompt
$ process attach --pid 68163 // Use the process id from previous terminal output
$ continue // will resume the process
```

Now repeat the lldb steps for all the processes that are launched for your session of vscode. Once the freeze happens, one of the lldb sessions will indicate a crash, use `bt` command and get the stacktrace and attach it here.

**Comment by tgrux** [comment]
Sorry for the delay.  I’ve tried this a few times and not been able to get any data from the lldb process attachments.  I was able to capture the following errors.  When I reproduce the actual bug where the renderer freezes, I didn’t see any errors logged (I had 4 processes attached).  There two process that started right before the freeze happened, that I couldn’t attach to quick enough, after attaching I couldn’t produce any more errors because the app was frozen.

Here is what I saw:


* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff757cc7de libsystem_kernel.dylib`__sigsuspend + 10
libsystem_kernel.dylib`__sigsuspend:
->  0x7fff757cc7de <+10>: jae    0x7fff757cc7e8            ; <+20>
    0x7fff757cc7e0 <+12>: movq   %rax, %rdi
    0x7fff757cc7e3 <+15>: jmp    0x7fff757ae421            ; cerror
    0x7fff757cc7e8 <+20>: retq   
Target 0: (Code Helper (Renderer)) stopped.

warning: Executable module changed from "/Applications/Visual Studio Code.app/Contents/MacOS/Electron" to "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)".


[17557:1211/091113.628890:INFO:CONSOLE(9)] "Uncaught (in promise) Canceled: Canceled", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (9)


[18157:1211/092430.371012:INFO:CONSOLE(250)] "%c[Extension Host] %c[redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (250)

**Comment by mjbvz** [comment]
Thanks @tgrux. Can you also try one more thing:

1. In your VS Code settings json file, add `"webview.experimental.useExternalEndpoint": true`
1. Then try reproducing the issue

This undocumented setting will switch VS Code from using webview to using iframes to render markdown content. It will help us track down what is triggering this
