### ISSUE TITLE
VSC too slow

### ISSUE THREAD

**Issue by GowthamGthm** [microsoft/vscode#86485]
Issue Type: <b>Performance Issue</b>

application hangs too often , not showing suggestions . cmd prompt hangs

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	 22000	code main
    2	   131	 11780	   gpu-process
    1	    70	 17224	   shared-process
    0	   198	 18920	   window (approve-inspection.component.ts - w_digitcare - Visual Studio Code)
    0	    36	  9144	     searchService
   38	     9	 10816	       "c:\Users\gowtham.p\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g **/*.{ts,tsx} -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/node_modules/** --no-ignore --follow --no-config --no-ignore-global
    0	    11	  1352	         console-window-host (Windows internal process)
   40	     9	 20292	       "c:\Users\gowtham.p\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g **/*.{ts,tsx} -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/node_modules/** --no-ignore --follow --no-config --no-ignore-global
    0	    11	 11748	         console-window-host (Windows internal process)
    0	    13	 18552	     watcherService 
    0	    11	 17632	       console-window-host (Windows internal process)
    0	    78	 19620	     extensionHost
    0	   300	 12676	       electron_node tsserver.js 
    0	    45	 20808	         electron_node typingsInstaller.js typesMap.js 
    0	    58	 21784	       electron_node tsserver.js 
    1	    36	 21876	       "C:\Users\gowtham.p\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\gowtham.p\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=19620
    0	    65	 19104	   window (Issue Reporter)
    0	    16	 23072	   electron-crash-reporter
    0	   123	 23180	   window (Welcome - Visual Studio Code)
    0	    58	 20412	     extensionHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (approve-inspection.component.ts - w_digitcare - Visual Studio Code)
|    Folder (w_digitcare): 331 files
|      File types: ts(158) html(43) css(32) json(11) js(6) log(2) svg(2)
|                  gitignore(1) 0(1) md(1)
|      Conf files: package.json(1) tslint.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
autoimport|ste|1.5.3

</details>

**Comment by roblourens** [comment]
Please give more details about exactly what you are doing and what you see happening
