### ISSUE TITLE
Web smoketest broken

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#86480]
I tried running it on Windows and Ubuntu. Ben tried running it on Mac. On all:
- I couldn't point it to a build with --build.
- The folder fails to load with "Can't resolve workspace folder"

**Comment by bpasero** [comment]
@Tyriar also, I cannot run these tests with node 12 installed. I get an error asking to use node <=10.

**Comment by Tyriar** [comment]
They've been broken since https://github.com/microsoft/vscode/issues/80308
