### ISSUE TITLE
Move cursor with Alt+Click in Terminal has issues with wrapped lines

### ISSUE THREAD

**Issue by depascalis** [microsoft/vscode#86482]
- VSCode Version: 1.40.2 
- OS Version: Windows_NT x64 10.0.17763
- PowerShell Version: 5.1.17763.771

Ref: https://github.com/microsoft/vscode/issues/44448#issue-300421788

Steps to Reproduce:

1. Open integrated PowerShell Terminal
2. Type some text that will wrap multiple lines
3. Alt+Click somewhere on the last line (works as expected)
4. Alt+Click somewhere on the other lines (not working) 

![vscode-altclick](https://user-images.githubusercontent.com/33980634/70334313-81efae00-1845-11ea-9a54-a2d288b459c5.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/2658

**Comment by Tyriar** [comment]
Oh, it's actually fixed as of a few days ago since the upstream PR got merged (https://github.com/xtermjs/xterm.js/pull/2670) 😃
