### ISSUE TITLE
rename symbol issue

### ISSUE THREAD

**Issue by aleksandrafanasyev** [microsoft/vscode#86487]
sometimes when you use Rename Symbols (F2 hotkey) as a result you lost 2 symbols before name and get 2 duplicate characters in the end of new name

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you specify language and example when that happened (example text before, cursor position, example text after?

**Comment by aleksandrafanasyev** [comment]
It happened when i refactored C++ classes and i had this issue:
I renamed func "ReadWriteStatus" in class Concurrent_ring_buffer to name "Read_write_status" but got this
"Concurrent_ring_bufferRead_write_statusus" instead this "Concurrent_ring_buffer::Read_write_status"
