### ISSUE TITLE
Find not usable when in native ipynb 

### ISSUE THREAD

**Issue by jrounds** [microsoft/vscode#86489]
- VSCode Version:  
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Open and Save native ipynb following instructions here https://devblogs.microsoft.com/python/announcing-support-for-native-editing-of-jupyter-notebooks-in-vs-code/
2. Go to menu Edit->Find...  Nothing happens.  No way to find any text appears.

Verify Edit->Find still works by going to any other document type.  Still works.  Go back to native ipynb.  Find... nothing happens previous find window is hidden.

**Comment by octref** [comment]
Open issue for https://github.com/Microsoft/vscode-python please.
