### ISSUE TITLE
Programatically scroll hovers

### ISSUE THREAD

**Issue by JarrettSpiker** [microsoft/vscode#86483]
**Request:**
Provide a way for extensions to scroll a revealed hover programatically.
Ideally, this would allow the hover to be scrolled to a particular tag in the markdown.
For example: `vscode.commands.executeCommand("editor.action.showHover", "#revealThisTag")`

**Details:**
Right now, it is possible to programatically reveal a hover for a particular line to a user by moving their cursor to the line in question using:
`commands.executeCommand("cursorMove")`
and then calling:
`vscode.commands.executeCommand("editor.action.showHover")`

This is very helpful if you would like to link an action/line in a custom tree view with a peice of code in the editor.

However, since multiple hover providers can contribute to the same line and the results are merged, there is no guarantee that the expected `MarkdownString` will be at the top of the revealed hover.

Off the top of my head, providing a separate API for this seems a bit wonky, but maybe adding a positional argument to the `editor.action.showHover` command would make sense

**Comment by octref** [comment]
@JarrettSpiker Why can't you wait to let users to scroll?
@jrieken What do you think? I don't feel it's a necessary addition.

**Comment by JarrettSpiker** [comment]
@octref If the user is interacting with my extension directly (through the command palette, or a custom view, or whatever), and I am going to force open a hover, I would like that hover to immediately be displaying the relevant information.
I don't want the user to need to scroll around, and try to determine which peice of information I am trying to show them
