### ISSUE TITLE
Problems view should be refreshed when files are moved

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8648]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:24:33.352Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

Steps to Reproduce:

1. Get a file with errors in the problems view
2. Move the file to another folder via drag and drop in explorer
3. Open problems
4. Click one of the problems

![image](https://cloud.githubusercontent.com/assets/2193314/16535216/8fd2e186-3f9a-11e6-89c6-d1c223438e12.png)

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscode-eslint#96
