### ISSUE TITLE
Go back in menu is missing shortcut key in Korean

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8649]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:24:33.352Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

It should say `뒤로 (B)`

![image](https://cloud.githubusercontent.com/assets/2193314/16535517/dab65cbc-3f9c-11e6-8c90-7c478bdee112.png)

**Comment by Tyriar** [comment]
This is what it looks like when accessing via <kbd>alt</kbd>, notice the misplaced underline.

![image](https://cloud.githubusercontent.com/assets/2193314/16535855/d9dd5c16-3f9f-11e6-91ce-b19cd1fa8430.png)

**Comment by dbaeumer** [comment]
@johnliu2016 can you please have a look. The keys in ( ) are down in the translation.

**Comment by johnliu2016** [comment]
HK assignment issue, "B" is missing in KOR translation.

[menus.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Fcode%2Felectron-main%2Fmenus.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";miBack" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[&amp;&amp;Back]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[뒤로(&amp;&amp;)]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Fixed.

File: src\vs\code\electron-main\menus.nls.resx
ID: ".resx", 0; "miBack"
SRC: &amp;&amp;Back
TGT: 뒤로(&amp;&amp;B)
