### ISSUE TITLE
My activity bar is blue!

### ISSUE THREAD

**Issue by hello341** [microsoft/vscode#86496]
Issue Type: <b>Feature Request</b>

I want it back to black that it always was but suddenly it changed its color to blue once I installed an Extention it turned blue, and I uninstalled it but the activity bar stayed blue and did not change back! I  have no idea how to undo it!

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7
<img width="136" alt="problem" src="https://user-images.githubusercontent.com/57366073/70364379-51663f00-185a-11ea-9139-3be542561e47.png">
c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by hello341** [comment]
and now I don't know why but there is also a weird space coming
<img width="195" alt="wierd" src="https://user-images.githubusercontent.com/57366073/70381480-02cbaa00-1919-11ea-9759-d5271bffcf27.png">
 up on the sides if I do not open the preview. It was not there before.

**Comment by sandy081** [comment]
Please file an issue against that extension that caused it. I suspect it is writing into your settings file.

Regarding the space have you enabled entered layout? 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/10746682/70463261-da7cb080-1abc-11ea-8281-e0928c638d0e.png">

**Comment by hello341** [comment]
I don't know what Extention it was that caused it.

**Comment by sandy081** [comment]
Can you please disable all extensions and let us know if you can still reproduce it.

**Comment by hello341** [comment]
I tried that already and it stayed the same. By the way, is blue the default color of the activity bar? because when I installed vs code, it was dark grey. I also tried using different themes but the blue top bar and activity bar stayed the same unlike before when it changed based on the theme. It was a extension that I found in themes, and I'm pretty sure it had no images that's all I know about it.

**Comment by sandy081** [comment]
Can you please let me know which extension is that? Also let me know the steps to reproduce this consistently.

**Comment by hello341** [comment]
I don't know which extension is causing the blue sidebars and the empty spaces

**Comment by hello341** [comment]
all I know is that it is an extension that is not installed in vs code because I did not see it in the installed section. it was like a theme bar extension or something like that. To fix this should I uninstall vs code and install again? will that work?

**Comment by sandy081** [comment]
Its not helpful if the extension is not provided. I think it is useful to know the extension so that you can file the issue against it. Anyway you can always reinstall to try but before that try following

- Restart VS Code?
- Restart VS Code with different user data dir and extensions dir. Launch from command line using args `--user-data-dir` and `--extensions-dir`.
