### ISSUE TITLE
Duplicate "Clear Search" and "No Settings Found"  in settings-editor

### ISSUE THREAD

**Issue by smilegodly** [microsoft/vscode#86490]
I noticed in the settings-editor that there are now duplicate clear buttons when the user searches but finds no result.

I propose getting rid of the "Clear Search" text in the bottom left corner as there is now a button in the search bar that achieves the same thing but with less clutter (in my opinion). This change would make the settings-editor more consistent with the keyboard shortcuts tab as well.

![Capture](https://user-images.githubusercontent.com/35276477/70350781-71373c00-1835-11ea-9c0b-31a332a8f542.PNG)

**Comment by roblourens** [comment]
Yeah we can probably just get rid of the text link

**Comment by jzyrobert** [comment]
What about the "Clear Filters" link? 
Should there be an extra Clear Filters button that appears in the search bar itself, or let the link stay?

**Comment by smilegodly** [comment]
@jzyrobert Would you mind sending me a picture of the "Clear Filters" link ?

**Comment by jzyrobert** [comment]
@smilegodly 
![Code_2019-12-06_21-02-38](https://user-images.githubusercontent.com/20613660/70356205-c8f09a00-186b-11ea-8754-07973a0b25e8.png)

When you use one of the @ filters it appears.

**Comment by smilegodly** [comment]
For now I think we can let the 'Clear Filters' link stay.  This issue was originally meant to get rid of the duplicate for  'Clear Search'.
In another PR I could add a button to the search bar that adds this , and then we could get rid of that link though, although other tabs don't have that sort of button . 
What do you think ? @roblourens

**Comment by roblourens** [comment]
Yeah the "Clear Filters" link is all about discoverability and I'd rather leave it
