### ISSUE TITLE
Viewlet gets narrower after zooming in and out

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86492]
![bug](https://user-images.githubusercontent.com/4033249/70356394-23b4d200-1829-11ea-989a-2ebebba24080.gif)

Version: 1.41.0-insider
Commit: d386b49dee6267238389c0a616af2be89726a4e3
Date: 2019-12-06T12:17:13.091Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

**Comment by sbatten** [comment]
/cc @joaomoreno 

I'm not sure if this constitutes a bug or just not what is expected sometimes. I believe this is caused because we always give the extra space to the editor which is normally best.

**Comment by joaomoreno** [comment]
Yeah this is just like resizing the window, wrt the grid.
