### ISSUE TITLE
References codelens for every plain object property since TypeScript 3.7

### ISSUE THREAD

**Issue by EtienneBourque** [microsoft/vscode#86495]
- VSCode Version: 1.40.2 and 1.41.0-insider
- OS Version: Windows 10 1909
- TypeScript 3.7
- This setting: "typescript.referencesCodeLens.enabled": true
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create a new .ts file.
2. Create an object such as
```javascript
class MyClass {
  private myMethod() {
    const myObject1 = {
      prop1: "prop1",
      prop2: {
        prop2_1: "prop2.1",
        prop2_2: "prop2.2"
      }
    };
  }
}
```

With TypeScript 3.6, we get codelens for the class and the method:
![image](https://user-images.githubusercontent.com/50217898/70362468-0dbc0700-1853-11ea-844f-c313e4b93e96.png)

With TypeScript 3.7, we also get codelens for each property in the object:
![image](https://user-images.githubusercontent.com/50217898/70362432-f5e48300-1852-11ea-9cc3-5d663bd0ba5f.png)

Is it normal behavior?

It becomes pretty intense in a React Native screen file when we define styles like so:
![image](https://user-images.githubusercontent.com/50217898/70362115-d7ca5300-1851-11ea-9bb3-f8c90b5822ed.png)

or when we pass a plain object as a parameter to a method:
![image](https://user-images.githubusercontent.com/50217898/70362736-021d1000-1854-11ea-94b1-261a0da4f77d.png)

Also, the references found for each React Native styles are styles with the same name in other files, but in reality, those are not related since they are local to each file.

**Comment by craxal** [comment]
@mjbvz Why was this issue closed? Has it been resolved?

**Comment by mjbvz** [comment]
@craxal Yes. Try the insiders builds (1.42)
