### ISSUE TITLE
Toggle between default and custom editors

### ISSUE THREAD

**Issue by sverg1** [microsoft/vscode#86504]
# Background
This is a subtask of #84520 involving a keybinding that toggles between the default editor of a file and its custom editor (if applicable). The goal is to add flexibility between different view modes without having to force views such as in the example below.

# Example
Pertaining to the aforementioned parent issue in particular, one can force the custom Markdown preview mode by adding the following **experimental** setup to *settings.json*:
```
"workbench.experimental.editorAssociations": [
    {
        "viewType": "vscode.markdown.preview.editor",
        "filenamePattern": "*.md"
    }
]
```

# Save-to-Preview
Using another keybinding, the user can save the file and switch to the custom editor all in one command. For example, saving in a Markdown file may automatically switch to its preview mode so that the user can see the final look of the file with each edit.

**Comment by mjbvz** [comment]
This ended up being implemented as a single: `editor.action.customEditor.toggle` command
