### ISSUE TITLE
Autocomplete 'string' to 'String' after input dot or comma

### ISSUE THREAD

**Issue by Rey-Wang** [microsoft/vscode#86502]
- VSCode Version: 1.40.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a js file and try to add type for a variable(cause I use flow)
2. auto changed 'string' to 'String' after I input a comma or dot
![vscodeIssue](https://user-images.githubusercontent.com/45580554/70367090-ca57ac00-18d7-11ea-9504-6c0917de5407.gif)

I'm not sure this is the correct behavior, but in my view,  if I don't select any code snippet in the list,  VScode shouldn't change my code instead of selecting the first one because I entered a comma or dot

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
We don't support types in JS files natively. Please file this against the flow extension

**Comment by Rey-Wang** [comment]
@mjbvz But this bug is not caused by flow extension, I think the deep reason is why it autocomplete the option I didn't choose?

**Comment by mjbvz** [comment]
We don't support writing `: types` in JS files. If you write types, we cannot say that IntelliSense will do the right thing or will work at all . Please use the flow extension if you are writing flow code
