### ISSUE TITLE
Activity bar debug icon left white border not shown when debug startView is active

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#86506]
Tested from sources.

Steps to Reproduce:

1. Start vscode with an empty workbench
2. Click debug activity bar icon. Notice that the left white border is not shown.

![debugstartviewfocus](https://user-images.githubusercontent.com/25115070/70368846-04945f80-187e-11ea-8397-bb82ac6e6088.gif)

**Comment by isidorn** [comment]
@jeanp413 thanks a lot for filling this!
