### ISSUE TITLE
Output panel channel dropdown in Chinese has incorrect line height for CJK characters

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8651]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:24:33.352Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

It should be centered:

![image](https://cloud.githubusercontent.com/assets/2193314/16535688/3f0f323c-3f9e-11e6-9a2c-cbb0f5ea5edc.png)

**Comment by Emeryao** [comment]
![image](https://cloud.githubusercontent.com/assets/3591899/16579530/ade33a8c-42d2-11e6-8ef8-ea40e7667efa.png)
BTW: @Tyriar do you think the English is vertically centered?
* VSCode Version: Code - Insiders 1.3.0-insider (Commit 0c5f6e8867fb117b6fa41cc647dc650bb9856dc4 Date 2016-07-04T09:47:29.290Z)
* OS Version: Windows10 10586.420

**Comment by Tyriar** [comment]
@Emeryao that's off too, this is what I see on Ubuntu 
![image](https://cloud.githubusercontent.com/assets/2193314/16587236/73536e4a-427e-11e6-86d9-676cf36f369e.png)

**Comment by isidorn** [comment]
We use a native drop down there.
I do not think there is anything we can do there. Suggestions on improving this are welcome, in the meantime closing

**Comment by Tyriar** [comment]
@isidorn maybe the height of the dropdown should be increased so the font fits and it's truly centered?
![image](https://cloud.githubusercontent.com/assets/2193314/25099510/68fe342e-2361-11e7-8254-c388a8322331.png)
