### ISSUE TITLE
Add "Interaction set" feature

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [microsoft/vscode#86517]
Don't know if it was already requested, but it will be awesome if VS Code could have some kind of file that contains set of extensions and settings to make it behave as another editor or IDE.
Some kine of set that you can download and apply to VS in one click that will configure instantly and I mean not visual style, but way it react.

For example I prefer the way VS19 behave when I code, but I notice that it doesnt auto format indentions, can't catch up pathes, doesn't have same key bindings and more. So I have to search what exactly I even need and then look for extension, then try multiple and fine tune them.
How nice it would be to download something like "VS19 Interaction set", install it and get vs code configuret accordingly.
To avoid extensions problems there may be a swith in panel to select like "default" set or one of preconfigured.

People prefer different editors would appreciate one click configuration, like sublime, Eclipse, IJ Idea and many others and ability to switch between them straight from VS code

**Comment by octref** [comment]
https://marketplace.visualstudio.com/search?term=keymap&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by CaCTuCaTu4ECKuu** [comment]
@octref I mean i know about all this stuff. The point is to have one pack of everything without necessity to search all of it, install and check compability with other extension. Sometimes it's a problem too.
Obviously you can make a list of extension, instuction to install and what not to, but there still is no ability to do it all in one click.
Such a thing already was discussed at #49826 and that's looks pretty what I mean. It's not so hard to implement as what I initially proposed and I believe this feature has to be supported natively.

**Comment by CaCTuCaTu4ECKuu** [comment]
And btw it's a point that periodically you have to switch to different kind of projects and you want a different set of extensions. Sometimes depending of file type (language) sometimes depending of workspace (set of project you working on)

**Comment by octref** [comment]
Please upvote https://github.com/microsoft/vscode/issues/57548
