### ISSUE TITLE
Settings editor do not retain filters when moved across editor groups

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#86513]
### Env
```
Version: 1.41.0-insider (user setup)
Commit: bbf00d8ea6aa7e825ca3393364d746fe401d3299
Date: 2019-12-05T06:56:28.532Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

### Steps to Reproduce:

similar to https://github.com/microsoft/vscode/issues/26490

- Open Settings editor in editor group 1 and provide a filter
- Open any file in editor group 2
- Move the Settings editor from group 1 to group 2
- filtration is gone

issue still persists.

**Comment by sandy081** [comment]
It works for me for keybindings editor. Moving it across groups (when tabs are enabled) retain the search filter. I see its not the case with Settings editor.

**Comment by ctf0** [comment]
u r right, its mostly related to settings now, ticket updated

**Comment by roblourens** [comment]
@sandy081 Does the keybindings editor have to persist this manually, because the editor will still have to be recreated in the new group right?

**Comment by sandy081** [comment]
Have options persisted in your editor input and update them.

https://github.com/microsoft/vscode/blob/91cf906e108d4544cb6cf99a4c4619604a60e06b/src/vs/workbench/services/preferences/common/preferencesEditorInput.ts#L63

**Comment by ctf0** [comment]
any news ?
