### ISSUE TITLE
unable to input chinese chars on ubuntu 19.10

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#86511]
Issue Type: <b>Bug</b>

unable to input chinese chars

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.3.0-24-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|7, 5, 5|
|Memory (System)|7.69GB (0.57GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.32.0
prettier-vscode|esb|3.11.0
marp-vscode|mar|0.11.2
vscode-language-pack-zh-hans|MS-|1.40.2
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
java|red|0.54.2
rust|rus|0.7.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.20.0
vscode-icons|vsc|9.6.0
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@calidion sorry for reaching out late, could you please share more about your set up and how to reproduce ?

**Comment by calidion** [comment]
it is very easy to reproduce.
I just entered ubutnu 19.10 for comfirmation.
and opened vscode, I even can't switch to my chinese input method fcitx.

**Comment by calidion** [comment]
but gedit gets chinese char with fcitx in ubuntu 19.10 or 20.04( as i have updated it to receive 20.04 daily build)

**Comment by rebornix** [comment]
@calidion what's the keyboard shortcut you use to switch IMEs? Do you mean it's hijacked by VS Code?

**Comment by calidion** [comment]
I don't know the exact reason either.
I wonder if you can reproduce it now?

**Comment by rebornix** [comment]
@calidion I can't reproduce. I'm not sure yet which part goes wrong, can you switch IME by UI/Mouse? If you can switch to Chinese somehow (say you close VS Code and switch the IME), can you type Chinese then in VS Code?

**Comment by ericlingit** [comment]
Hi @rebornix, I believe OP is referring to the snap version of vscode installed on Ubuntu.

I'm also not able to activate any input method (iBus or fcitx) to enter Chinese characters anywhere in vscode (snap version).

My keyboard shortcut to activate fcitx is Super+Space. I've tried switching to a different set of keys (and made sure it's collision-free) to no avail. I'm also not able to activate the input method manually by mouse when the vscode window has focus.
