### ISSUE TITLE
Editor title control is not using SPAA

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86514]
This was fixed by using the `translate3d` trick, but got removed in endgame. 

![image](https://user-images.githubusercontent.com/900690/70371098-279b2f80-18cf-11ea-89df-8860fb5861f4.png)

**Comment by bpasero** [comment]
This seems to depend on how the editor part is pushed to the side when the sidebar is visible. I cannot reproduce when the sidebar is hidden and sometimes cannot reproduce when sizing the sidebar to some value. 

My speculation is that some sidebar sizes cause the entire editor part to be rendered on a different layer. Though I cannot explain why LCD rendering drops.

**Comment by ShakeelHamiya** [comment]
I am new at git
