### ISSUE TITLE
Intendation based folding in Markdown Language Mode

### ISSUE THREAD

**Issue by Ilias48rus** [microsoft/vscode#86510]
Please add this, its a completely no-harm option .
Plain text support it, so why markdown that is an extension of such, wouldn't ?
And the markdown syntax ignore Tab Stops anyway, so their use even won't affect the rendering .

**Comment by mjbvz** [comment]
See `editor.foldingStrategy`

**Comment by Ilias48rus** [comment]
@mjbvz , its not the asked feature, changing this setting to indentation make the editor do not use the {language specific}/Heading folding, the Issue's point is that Markdown should have the default/{ plain text / no-}language } indentation based folding in addition to the Heading one .

**Comment by Ilias48rus** [comment]
( The indentation folding should count as sub levels of headings and the bullet lists )

**Comment by mjbvz** [comment]
Please provide an example

**Comment by Ilias48rus** [comment]
Of what ..?
```
# 1 (fold all)
2 (fold 3)
    3
1. 4 (fold 5-6)
    2. 5 (fold 6)
        6
```

**Comment by mjbvz** [comment]
That is a good fit for an extension.

The default markdown folding supports folding lists just fine but based on semantic elements. Because `2` to `3` is just part of the same paragraph in markdown, it generally would not make sense to fold that. The same with folding list element `2.`. if you open the markdown preview you'll see that we don't actually parse that as a list

**Comment by Ilias48rus** [comment]
Right as a said, the [2] to [3] 's `\br` and `\t` characters will be ignored (yes "2 3" will be rendered, or "`2<<\br>>3`" if you use 2 spaces ending), thats why the folding won't affect the result . But compared to the rendered document that is only for read, it can be usable to separate the paragraph to fold-able lines in editing . And if the most of users won't do so, it doesn't mean that anyone who will, wouldn't want the lines to be fold-able by indentation .

I didn't care about syntax much while was writing the example,
```
# 1 (fold all)
2 (fold 3)
	3

tree
1. 4 (fold 5-6)
	1. 5 (fold 6)
		6
```

**Comment by Ilias48rus** [comment]
And the statement about lists you've wrote are wrong, [6] is just the part of [5] 's paragraph .

**Comment by Ilias48rus** [comment]
1 of the main reasons why i ask for such folding, is that its more ergonomic to use Markdown for notes and info writing, than plain text files . Because you can check it's rendered version and send parts of it to someone less technical .

And so in such use, for example, you note down a C++ class tree or other code in the .md about some program . Obviously you do not want to render it, so you wouldn't be able fold it, or send it to someone for who its not comfortable to read the Markdown syntax .

The folding could be also good to add to the comments, but as you resist the improper merging of things, it would be enough for paragraphs which is equal to enhanced plain text .
