### ISSUE TITLE
Add `function name` predefined variable for snippets

### ISSUE THREAD

**Issue by akantsevoi** [microsoft/vscode#86519]
As I see there is no `TM_CURRENT_FUNCTION_NAME` or smth like this in the list of snippet variables.
Is it possible to add it?
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables

**Comment by jrieken** [comment]
This isn't possible with the static snippet system because it has no knowledge of its surroundings. You would need to implement an extension doing this.
