### ISSUE TITLE
Code Randomly Swaps Out

### ISSUE THREAD

**Issue by JoeCianflone** [microsoft/vscode#86528]
Issue Type: <b>Bug</b>

I have no idea how to exactly explain this bug, but I've had it happen several times now. You open a bunch of files, do some work and save...then all of a sudden one of those files will be totally swapped with the code from a different file that was also open at the same time. 

That sounds insane I know, but here's a screenshot of a diff of a file that it did this to me. The first time I saw this I thought I "must have" somehow overwritten the file, but this time I know there's NO WAY I overwrote anything. 

I've attached a screenshot so you can see that the file called `AccountSetupEmail` was changed to the code in `UserReceipt`. 

This is also not just a repaint issue because the file was saved and when I went to run my app I got an error because `AccountSetupEmail` didn't exist anymore. 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tidyhtml|anw|1.10.0
spellright|ban|3.0.48
vscode-intelephense-client|bme|1.3.2
npm-intellisense|chr|1.3.0
laravel-blade|cjh|1.1.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
php-debug|fel|1.13.0
vue-snippets|hol|0.1.11
mysql-syntax|jak|1.3.1
php-cs-fixer|jun|0.1.129
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.3.0
vscode-scss|mrm|0.8.1
php-docblocker|nei|2.1.0
vetur|oct|0.22.6
vue-beautify|pea|2.0.4
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.8.0
html5-boilerplate|sid|1.0.3
open-in-browser|tec|2.0.0
vscode-status-bar-format-toggle|tom|2.0.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.0

(9 theme extensions excluded)

</details>

<img width="1552" alt="Screen Shot 2019-12-07 at 11 44 01 AM" src="https://user-images.githubusercontent.com/989648/70377817-e6167e80-18e6-11ea-8b86-937e82cf89b0.png">

**Comment by whizsid** [comment]
Can you reproduce this issue even when all extensions disabled?

**Comment by rebornix** [comment]
Closing for now as lack of information asked above.
