### ISSUE TITLE
VSCode lags and freezes, when OBS and Firefox are open in the background, or when left open for a long time.

### ISSUE THREAD

**Issue by 1chriis1** [microsoft/vscode#86521]
VSCode gets so slow and laggy that a character that I type, appears on screen even after 5-6 seconds, and ultimately becomes unusable.

I notice this happening in two circumstances.
Mainly, when I've got Firefox open and OBS Studio recording a single tab (!), it slows down to the point that typing appears on screen often after 10 seconds.
It does so, not at the beginning of the recording, but well into it.

It stops slowing down when I close OBS and Firefox, and do a restart of VSCode.

The other circumstance when it freezes and lags is when I have it open with a single python file with 500 or so lines, and I leave VSCode open for too long. Even hitting enter to create a new line takes a second or two.

After a close,and re-open it works like new though.

**Comment by Someoneece** [comment]
Same over here

**Comment by octref** [comment]
Please follow https://github.com/microsoft/vscode/wiki/Performance-Issues for reporting perf issues.

**Comment by 1chriis1** [comment]
Will close current issue an re-report it correctly. Thanks @octref
