### ISSUE TITLE
Indentation of html attributes should be the same after indenting the element 

### ISSUE THREAD

**Issue by Haberkamp** [microsoft/vscode#86522]
When correcting the indentation of an html element with multiple attributes. The attributes don't align any more.

### Before
![Before](https://i.imgur.com/ln6wwhS.png)

### After

![After](https://i.imgur.com/vQV1CMq.png)

- VSCode Version: 1.40
- OS Version: Fedora 31 

Steps to Reproduce:

1. Create an html file
2. Create a html tag with three or more attributes. (Like in the images above)
3. Select the whole html tag and indent it with the tab key.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
If you are using formatting, this is the behavior of js-beautify so you should report issue to them:
https://github.com/beautify-web/js-beautify

There are other formatters such as prettier you can find on https://marketplace.visualstudio.com/vscode
