### ISSUE TITLE
Insiders - When using a UNC, unable to read file for working tree changes 

### ISSUE THREAD

**Issue by will-l-h** [microsoft/vscode#86534]
Issue Type: <b>Bug</b>

Steps:
* Start Insiders
* Open folder \\\\192.168.1.111\my_samba_share\
* Make file edits, save
* Attempt to view working changes in Source Control tab
* changes don't display and error toast appears

I'm using Insiders on Windows to edit files from a Samba share on a raspi running Raspbian GNU/Linux 9 (stretch).  I can edit and save the changes fine, but starting in the last few weeks, when I select the file on the Source Control tab (Git) I get this toast message:

Unable to open 'some_file.yaml (Working Tree)': Unable to read file (EntryNotFound (FileSystemError)).

There are no error messages in the Git output. I'm using git 2.18.0.windows.1. I discovered that if I have the folder mapped as a drive in Windows (e.g. Z:), the issue goes away. I don't see this issue with UNC paths on VS Code 1.40.2.

VS Code version: Code - Insiders 1.41.0-insider (87c2e0be5d7359ce110c4c9ec9f6df71be996f8a, 2019-12-06T21:36:11.793Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
//cc @joaomoreno maybe related to implementing a file system provider in Git

**Comment by joaomoreno** [comment]
Great catch, thanks!

**Comment by joaomoreno** [comment]
@bpasero The fix has been pushed to `master` and `release/1.41`.
