### ISSUE TITLE
 integrated terminal 

### ISSUE THREAD

**Issue by alexandre91alfa** [microsoft/vscode#86531]
VSCode Version: 1.4.2
OS Version: Ubuntu 19.10
Steps to Reproduce:

Open the terminal using ctrl+`
The cmd will open but I am unable to type in the integrated terminal within VS code. I have attempted to use the Insiders build of VS Code and I still can't type in the integrated terminal.
Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What version of VS Code are you on?
