### ISSUE TITLE
VSCode: long lines on terminal

### ISSUE THREAD

**Issue by luizo094** [microsoft/vscode#86540]
Hi, I wanted to learn how to program Java in VSCode. I did all the necessary steps to install Java, but when I run the classic Hello World code in the terminal I get long lines. How do I fix it?

- VSCode Version: 1.40.2
- OS Version: Windows 7

![codigo](https://user-images.githubusercontent.com/58644857/70383110-2279c700-1947-11ea-9e03-6a780dc18a26.png)

I tried almost every version of Java.
Thanks!.

**Comment by Tyriar** [comment]
Not sure what the problem is, what do you expect to happen?
