### ISSUE TITLE
Missing crossorigin="use-credentials" to manifest.json link for basic auth

### ISSUE THREAD

**Issue by jmbarbier** [microsoft/vscode#86541]
- VSCode Version: latest from https://github.com/cdr/code-server
- OS Version: browser (Chrome)

Steps to Reproduce:

1. Serve VSCode behind basic auth; everything is OK but manifest.json gets a 401

Does this issue occur when all extensions are disabled?: Yes

Everything works well using basic auth, except retrieving of manifest.json. It appears that at least for Chrome, we need to add <link rel="manifest" href="manifest.json" **crossorigin="use-credentials"**> in order for Chome to pass auth headers for manifest retrieval.

**Comment by octref** [comment]
Please report this to code-server.
