### ISSUE TITLE
Multiline highlighting disappears on some lines

### ISSUE THREAD

**Issue by Zx-EvM** [microsoft/vscode#86547]
- VSCode Version: 1.40.2
- OS Version: Windows 10 Pro x64 1903 18362.476

```
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

```

Gif demo with bug reproduce:

![vscode-github-issue](https://user-images.githubusercontent.com/20873402/70385415-c2336580-19d8-11ea-9b0d-80fc5716aa46.gif)

Steps to Reproduce:

1. Open file with code used in demo:

```
// https://codepen.io/wernight/details/YyvNoW
var listElm = document.querySelector('#infinite-list');

// Add 20 items.
var nextItem = 1;
var loadMore = function () {
    for (var i = 0; i < 20; i++) {
        var item = document.createElement('li');
        item.innerText = 'Item ' + nextItem++;
        listElm.appendChild(item);
    }
}

// Detect when scrolled to bottom.
listElm.addEventListener('scroll', function () {
    console.log(listElm.scrollTop)
    if (listElm.scrollTop + listElm.clientHeight >= listElm.scrollHeight) {
        loadMore();
    }
});

// Initially load some items.
loadMore();
```

2. Try to multiline select

I noticed that issue reproduced only at the beginning of the file (if try to reproduce with large file). Also this bug reproduced with any theme except default.

Extensions I use:

- [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)
- [Subtle Match Brackets](https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by usernamehw** [comment]
Duplicate of #84523 ?

**Comment by Zx-EvM** [comment]
> Duplicate of #84523 ?

No. It's not the same

**Comment by usernamehw** [comment]
How are they different?

**Comment by Zx-EvM** [comment]
@usernamehw I'm sorry. I again read #84523 and try to reproduce. Looks like it's the same. But why it's closed?

**Comment by usernamehw** [comment]
Because it's fixed in the master branch. You can see that it will be shipped in the next release 
( Milestone - November 2019).
