### ISSUE TITLE
Tasks don't work if powershell profile changes directory

### ISSUE THREAD

**Issue by MikeCook9994** [microsoft/vscode#86548]
- VSCode Version: 1.40.2
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Include in your powershell profile
`
Set-Variable -Name Home -Value <directory that isn't your wd> -Force;
cd $HOME
`
2. Open code in a directory containing defined vs code tasks that are dependent on some files in the working directory.
3. Execute a task 

It should fail because it is operating in the directory defined in your profile instead of in the current working directory that code was launched from

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
I can't reproduce this. Can you share your settings.json and tasks.json? 
My steps:
1. Do the change directory shown in the initial issue
2. Open a folder in VS Code.
3. Launch the terminal. See that it's cwd is the dir specified in (1) and not the folder that I have open in VS Code.
4. Add this tasks to tasks.json:
```
{
    "label": "dir",
    "command": "dir",
    "type": "shell"
}
```
5. Run the task. See that it correctly uses the current VS Code folder as the cwd, not the directory specified in (1).
