### ISSUE TITLE
Markdown preview shows flickering batches in smoke test's readme.md while updating

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8654]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:26:22.011Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Open smoke test's readme.md and its preview side-by-side
2. Type in readme.md
3. -> The batches at the top of the preview disappear after each change and the reappear

**Comment by bpasero** [comment]
Not a regression I think. We just reload the contents each time.

**Comment by jrieken** [comment]
Yes - the web view reloads the contents when it receives a document change event. Not really sure how to fix this on that level. It would require to diff the contents, check what to do in the scripts/no scripts changed case etc. 

An easier fix for this specific problem might be to make this change in MD - by running a server that provides updates as you type

**Comment by chrmarti** [comment]
What surprises me is how slow the images are added back, these are cached I assume?

**Comment by jrieken** [comment]
I actually don't know... I can image they aren't cos they are meant to represent some live state about the repo...?

**Comment by chrmarti** [comment]
Makes sense, that might be the reason then. Typing in the markdown source effectively refreshes these.

**Comment by jrieken** [comment]
no action planned
