### ISSUE TITLE
Debian package repository URL doesn't use HTTPS

### ISSUE THREAD

**Issue by noelleleigh** [microsoft/vscode#86545]
Issue Type: <b>Bug</b>

1. Install VSCode .deb package from <https://code.visualstudio.com/Download>
2. Inspect contents of `/etc/apt/sources.list.d/vscode.list`:

```
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
``` 
**Expected behavior**: The repo URL should use HTTPS.
**Actual behavior**: The repo URL uses HTTP.

The repository supports HTTPS, and other issues have reported the repo using an HTTPS URL, but the actual code that generates it uses HTTP:
https://github.com/microsoft/vscode/blob/2bb6cfc16a88281b75cfdaced340308ff89a849e/resources/linux/debian/postinst.template#L69-L71

**Proposed solution**: Change the URL in that file to use HTTPS ([link to commit from fork](https://github.com/noelleleigh/vscode/commit/54e888f1f4b28c6a0df97945dda4271e79c0937c)).

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.19.69-06666-g6c4f8cbba24e

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|4.84GB (2.36GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by Tyriar** [comment]
This has come up before, it's fine that it's not https as there are extra checks in place to make sure it's the right payload that comes back. Also a lot of distros need an additional package when you install via https.
