### ISSUE TITLE
Ask before overwriting when dragging a file from outside of VSCode to the Explorer view

### ISSUE THREAD

**Issue by CanisLupus** [microsoft/vscode#86555]
Imagine you are working on a workspace and have the Explorer view open with your files tree:

![image](https://user-images.githubusercontent.com/532708/70388130-8a5efa80-19a5-11ea-9497-b71cea8febc2.png)

Now you drag a file named "CsvParser.cs" from your Desktop to this workspace.

![image](https://user-images.githubusercontent.com/532708/70388138-b7131200-19a5-11ea-8ed8-285564b77dc7.png)

VSCode will just happily replace the existing file of the same name without confirmation. Even if you had the file open, Ctrl+Z can't save you. It's not in the trash either since it's a replace. You just lost your changes to an entire file.

It does this for me with no extensions installed and no settings, so unless something is broken, this seems like the default behaviour.

When using the Explorer view by itself VSCode will, however, ask for confirmation by default when deleting a file or moving a file to a folder, which are operations that are reversible (if you delete to trash). It will also create a copy if you just copy and paste.

So it seems safe by default except when replacing, and I couldn't find an option to require confirmation either.

I think I could essentially report this as a bug. I lost an entire file because I didn't notice that the file I was dragging had the exact same name, so... :) But I'm still unsure if it's something I have badly configured.

**Comment by gjsjohnmurray** [comment]
Possible duplicate of #83478. @CanisLupus you didn't say what version of VSCode you are running and on what platform. Are you willing to try the [Insiders version](https://code.visualstudio.com/insiders)?

**Comment by CanisLupus** [comment]
I didn't because I thought this was just the way it was right now and not a bug, but I'm using VSCode 1.40.2 and Windows 10.

I tried Insiders just now based on your suggestion and... yes! I can confirm that it now asks for confirmation, so that's great! :)

You can close this (I won't do it myself in case you want to keep it for tracking, but feel free to close).
