### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by AllenVork** [microsoft/vscode#86554]
I have the vscode installed on external storage on imac.  The terminal can't work when i  select view -> terminal.
It says:
The terminal shell CWD "/Volumes/Seagate Backup Plus Drive/development/git/blog/AllenVork.github.io" does not exist.

**Comment by Tyriar** [comment]
Does `/Volumes/Seagate Backup Plus Drive/development/git/blog/AllenVork.github.io` exist?

Can you check the devtools console for errors? (Help > Toggle Developer Tools)
