### ISSUE TITLE
Autosave delay leads to a cursor lagging behind typing

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#86557]
I set option of autosave to afterDelay, and set the autosave period to 100. Then, when I type, sometimes cursor lags behind the typing.

**Comment by gjsjohnmurray** [comment]
Do you really want/need autosave to be triggered whenever you stop typing for one tenth of a second?

**Comment by solomatov** [comment]
@gjsjohnmurray Yes. I got used to IntelliJ where saving is automatic and transparent.

**Comment by gjsjohnmurray** [comment]
@solomatov isn't the default 1000ms period adequate for you?

**Comment by solomatov** [comment]
@gjsjohnmurray For me 1000ms is too much. 200-300ms is a more reasonable limit.

**Comment by gjsjohnmurray** [comment]
> when I type, sometimes cursor lags behind the typing

Does that happen less often if you set, say, 300ms?

**Comment by solomatov** [comment]
@gjsjohnmurray I did not try it

**Comment by solomatov** [comment]
I tried it on the master version, and it doesn't reproduces there. So it's either fixed, or caused by one of the extension I use, though, I use nothing but the standard set + tslint + nightly typescript.

**Comment by alexdima** [comment]
@solomatov I cannot reproduce.
* I have configured `settings.json`:
```json
"files.autoSaveDelay": 100,
"files.autoSave": "afterDelay",
```
* I type in a `.txt` file and everything appears to be working normally for me:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/72426277-baaa6d80-3789-11ea-9598-a43fce745a9a.gif)

**Comment by solomatov** [comment]
I didn't see this problem for a long time, thus closing it. Thanks everyone for your help.
