### ISSUE TITLE
Add the global settings of extensions

### ISSUE THREAD

**Issue by keywet06** [microsoft/vscode#86552]
Issue Type: <b>Feature Request</b>

### I think vscode can add the global settings of extensions

- But I must add the settings to some folders over and over again now.

- example: the file `c_cpp_properties.json` of the extension `C/C++`

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
@keywet06 This request appears to be extension-specific. Please raise it at https://github.com/Microsoft/vscode-cpptools/issues and close this one.
