### ISSUE TITLE
Keybindings.json is opened in broken editor

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#86565]
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-70-generic

When I open the keybindings, it gives me an option to open the keybindings.json file.

When this file is opened in the editor, the editor is opened in read only mode, even for the user keybindings.json. 

When I try to edit the default keybindings.json, it shows a tooltip saying the file is in read-only mode. When I try to edit the user keybindings.json, it also acts as in read-only mode, but it gives no tool-tip.

In addition, in the user keybindings.json, even moving the caret does not move. Where as in the default keybindings.json, I can at least move the caret.

In the bottom right of the editor it permanently says "defining keybinding (ctrl+k, ctrl +k).

I assume the user keybindings.json is intended to be editable. I have checked that there are no odd permissions on the user keybindings.json

**Comment by gjsjohnmurray** [comment]
/confirmationPending I wasn't able to reproduce this (I only tested on Windows though).

@safield does it still happen for you if you run with all extensions disabled, e.g. by adding the [`--disable-extensions`](https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions) argument?
