### ISSUE TITLE
*.json and debugging

### ISSUE THREAD

**Issue by DharneshwarPartapSipla** [microsoft/vscode#86560]
Issue Type: <b>Bug</b>

I have a problem for launch.json, task.json and also debugging

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|-psn_0_3888053|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.15
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
sublime-keybindings|ms-|4.0.6
quicktype|qui|12.0.46

</details>

**Comment by octref** [comment]
Please describe your problem and then reopen or open a new issue.
