### ISSUE TITLE
addSelectionToNextFindMatch does no include quotes brackets or delimiting characters

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#86567]
When editing in json, when I put the caret at the start of a word, and then hit ctrl+d, I would like for the subsequent word selection to not extend to enclosing characters such as brackets, or extend to standard delimiting characters such as -,+,/...

This is the default multi caret behaviour in other languages in VSCode

For example, observe the following text...

> "editor.autoClosingBrackets"

If I put the caret at the first 'e' character, and then hit ctrl+d to addSelectionToNextFindMatch, the behaviour in json and xml.

in xml it will select just the word _editor_ where as in json will select everything.

Another example...

> "test"

In xml hitting ctrl+d will select everything, where as json will just the word _test_.

**Comment by alexdima** [comment]
This is because Ctrl+D uses the word defined by the language in the language configuration. There is already an issue to move Ctrl+D to use the word separators as defined in `editor.wordSeparators`, so let's track in https://github.com/microsoft/vscode/issues/15774
