### ISSUE TITLE
Alt text on tabs' close button

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8656]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:26:22.011Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Enable OS X Voice Over
2. 'Tab' to editor tabs
3. -> You can't distinguish between the tab and it's close button

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8659
