### ISSUE TITLE
Terminal unusable after closing laptop lid

### ISSUE THREAD

**Issue by eborghi10** [microsoft/vscode#86568]
Issue Type: <b>Bug</b>

1. Open integrated terminal
2. Close the laptop lid
3. Open it again

The integrated terminal will display unreadable characters.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.0.0-37-generic snap

**Comment by debopamgupta** [comment]
I am on <strong>Windows 10 version 1903</strong> OS Build <strong>18362.418</strong> and I am not facing this issue.  
Also I just updated to the latest version of VSCode version 1.40.2

**Comment by eborghi10** [comment]
> I am on **Windows 10 version 1903** OS Build **18362.418** and I am not facing this issue.
> Also I just updated to the latest version of VSCode version 1.40.2

I'm mostly sure this issue only happens with Linux-based OSs.

**Comment by debopamgupta** [comment]
> I'm mostly sure this issue only happens with Linux-based OSs.

Seems so. 

Do we need to wait for a bit or immediately close and open the lid? Does it happen after extended inactivity?

**Comment by eborghi10** [comment]
> > I'm mostly sure this issue only happens with Linux-based OSs.
> 
> Seems so.
> 
> Do we need to wait for a bit or immediately close and open the lid? Does it happen after extended inactivity?

It's possible to reproduce it suspending the computer too.
