### ISSUE TITLE
Selection disappears when context menu open

### ISSUE THREAD

**Issue by beckbria** [microsoft/vscode#86571]
Issue Type: <b>Bug</b>

1) Select some text
2) Right click on selection to access context menu

Expected behavior: Selection is still highlighted
Actual behavior: Selection is not visible.  

3) Dismiss context menu (click outside it)

Observed behavior: selection is once again visible

VS Code: 1.40.2
OS: Windows 10 1909 x64

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (24.81GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/git/advent-of-code/2019 --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|31.93GB (24.81GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.40.3
vscode-custom-css|be5|3.0.9
vscode-markdownlint|Dav|0.32.0
python|ms-|2019.11.50794
Go|ms-|0.11.9

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@beckbria may I ask what's the theme you are using?

**Comment by beckbria** [comment]
Cobalt2: https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2

**Comment by rebornix** [comment]
Good catch, thanks @beckbria 

When using native menu 

* Select text
* Right click on text
* Selection is gone, context menu shows up, selection is back again

When using context menu

* Select text
* Right click on text
* Selection is gone

It seems related to how context menu steals the focus @sbatten

**Comment by sbatten** [comment]
Yea it's because the editor isn't focused with custom context menus opened. We don't currently have a fix for this, but the theme you are using can get around this by setting a different theme color for `editor.inactiveSelectionBackground`. It looks like the theme you are using has updated this value but hasn't published a new version of the extension since. For now, you can adopt the new color by adding this to your `settings.json`.

```json
"workbench.colorCustomizations": {
	"[Cobalt2]": {
		"editor.inactiveSelectionBackground": "#003b8b",
	}
}
```
