### ISSUE TITLE
CompressedNavigationController ends with outdated state after startup

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#86573]
Tested from sources

Steps to Reproduce:

1. Open (or reload) a workspace with compressed folders containing file decorations.
2. :bug: Keyboard focus the explorer and observe it's not possible to navigate the compressed labels.
3. :bug: Right click on a compressed label to show the context menu. Observe the context menu appears at the top left corner of the window.

![compressedfolder](https://user-images.githubusercontent.com/25115070/70417872-29303900-1a30-11ea-979a-9e722d317a03.gif)

**Comment by gjsjohnmurray** [comment]
@joaomoreno maybe the PR from @jeanp413 can be a candidate for 1.41 ?

**Comment by isidorn** [comment]
@jeanp413 thanks a lot for filling this!
I can reproduce this issue.
Adding candidate label

**Comment by isidorn** [comment]
I have merged to master a great PR by @jeanp413 
However reopening this issue so we dicuss if the issue should be part of the release, if yes I will create a new PR which dulicates the @jeanp413 fix to our release branch.
