### ISSUE TITLE
cannot jump definition

### ISSUE THREAD

**Issue by roguexiaohuihui** [microsoft/vscode#86570]
- VSCode Version: 1.40.2
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/22930711/70405783-5d7c1780-1a79-11ea-857b-19aa961f3b93.png)

Before, vscode in ". ts "file can be defined by the normal jump function, I do not know why, recently suddenly can not use the jump function.

Now a simple example, I have two files：

1、child.ts
`export var version=1;`

2、main.ts
`import { version } from "./child";
console.log('version:',version);`

Now in main.ts file, you cannot click "./child" to jump to child.ts file

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by roguexiaohuihui** [comment]
I have uninstalled the original 1.40.2, but it is still not possible to reinstall the official 1.40.2. However, according to what you said, with the latest version 1.41.0, the problem has been solved

**Comment by mjbvz** [comment]
Thanks for testing. The current insiders build will be released as VS Code 1.41 sometime this week
