### ISSUE TITLE
Allow Profiles to manage enabled Extensions

### ISSUE THREAD

**Issue by makeway4pK** [microsoft/vscode#86575]
### Idea
Custom Extension Profiles would be extremely useful to manage the plethora of extensions we have gathered in our adventure. Enabled in a click*, disabled in a click*, assigned to workspace in a click*.

- A profile would be just a list of extensions to enable, and one list to disable. Other extensions are not touched.
- For the Disable list, a keyword denoting all extensions must be provided to allow making strict profiles.

**Actions:**
- Apply profile: First disables extensions from disable list, then enables the ones in the enable list.
- Assign profile to workspace: Profile will be applied each time the workspace is opened.
- (optional) Create profile from current workspace: Makes a profile from the currently enabled extensions in the workspace.

**Motivation**
Many freelancers often work on different types of workspaces requiring different assists. Most extensions don't interfere with incompatible files but some do, some register a ton of commands into the pallette, some have poorly thought keybindings and so on.

Besides, many (me included) have a minimalism/efficiency OCD  and just can't bear to put any extra non-productive burden on their processors🤷‍♀️.

\* (in a click): or a command, whichever.

**Comment by octref** [comment]
https://github.com/microsoft/vscode/issues/2743

When we say "setting sync" it involves syncing extensions.

**Comment by makeway4pK** [comment]
> #2743
> 
> When we say "setting sync" it involves syncing extensions.

Sorry, you missed an important point.
I suggested nothing related to syncing.
Extension profiles were meant to be used to quickly ENABLE a SET of extensions to quickly switch between Web dev, Embedded sys and other workspaces I have. You have saved a week on the next update.

**Comment by sandy081** [comment]
Looks related to this - https://github.com/microsoft/vscode/issues/57548. If it is related please provide your input there.
