### ISSUE TITLE
PROTEST! Why is the RedHat xml extension shown as the 1st place in the search result?

### ISSUE THREAD

**Issue by AlseinX** [microsoft/vscode#86585]
Although the Josh Johnson one is more popular, it is still shown as the second choice in the xml search result.
The redhat one requires Java runtime, why?
Why should we install a irrelative specific language runtime for generally used XML?
Not all programmers use java but most programmers have to deal with XML.
It is so rude and confusing that a new user who simply want an XML support and is surprisingly asked to manually install and configure a Java runtime! It makes no sense! It makes me feel insulted!
Why does it overtake the 1st place in the search result (which is regarded as the recommended one)?

**Comment by whizsid** [comment]
If you want a sort option to search results, Please use [this](https://github.com/microsoft/vscode/issues/82352) issue.

**Comment by AlseinX** [comment]
It is not about customization or personal configuration, but about the official recommendation, for everyone who simply want an XML language support in VSCode without knowing how they are.

**Comment by octref** [comment]
I'm guessing it's because "XML" is a direct match to your query, whereas "XML Tools" is not.

**Comment by AlseinX** [comment]
@octref I clicked "Contact Us" at the bottom side of that page and directed to "Support for business" page, where a support plan is required.
