### ISSUE TITLE
Revisit handling of deleted/moved files in custom editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86599]
I just came across the change in https://github.com/microsoft/vscode/commit/b52f1c7dae8a70d1d877e65b16b9496118690196#diff-bd0cac707b6707e6ef725a11d0702cea. I think the approach is a bit questionable as we now have some editors implementing this method (custom) but some not (files).

I find the `FileEditorTracker` should only be responsible for updating editors for files, not any other editor nor custom editors. At least that was the initial intent of it.

Can you do the tracking on your end for custom editors? I am not seeing a big win of doing this in a generic way?

**Comment by bpasero** [comment]
I pushed changes to revert back to how it was. I have a feeling that each editor should handle moves and deletes individually, specifically I think `CustomEditorService` should listen to file operations and update accordingly (via `this._register(this.fileService.onAfterOperation(e => this.onFileOperation(e)))`).

Let's put that on the agenda for our sync.

**Comment by bpasero** [comment]
I briefly looked into this but don't have a good understanding of how this should work. Specifically:

https://github.com/microsoft/vscode/blob/e8b79d9c42956fd79ae685164a83eadaa35ac4c0/src/vs/workbench/contrib/customEditor/browser/customEditorInput.ts#L161-L174

It looks like we used to pass in the new URI after the rename into `editorInfo?.matches(uri)` but that seems wrong to me. Shouldn't we find the custom editor that deals with the resource before it got renamed and then update the editor accordingly?

**Comment by bpasero** [comment]
@mjbvz I spend some time working on it via https://github.com/microsoft/vscode/commit/729397923d453d61dc95fd48f18aa17fef905105 and went back to a solution that would expose a `move` method from the editor input, sorry for the back and forth. 

It has the following signature:

```ts
move(group: GroupIdentifier, target: URI): IMoveResult | undefined

export interface IMoveResult {
	editor: IEditorInput | IResourceEditor;
	options?: IEditorOptions;
}
```

The idea is that you can return a new editor input that you would like to be replaced with and provide some additional options if e.g. you want to restore specific view state once the editor is being replaced.

I was not adopting this for custom editor input because I was not sure how to create the input from within the custom input, maybe you could have a look and then delete your custom logic for handling moves.

Btw deletes are also handled now, a file that is deleted that matches an editor that is opened will dispose that editor. But I think you have extra logic already somewhere to dispose webviews when files are deleted, maybe you could check.

**Comment by mjbvz** [comment]
Thanks @bpasero! Just got around to taking another look at this with 041a5907b1d3437344fda16da784aba7828af520

I'm going to continue looking into how VS Code and extensions handle moves in #86146
