### ISSUE TITLE
Support build-in inline-render inferred types in TypeScript

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/vscode#86592]
example: (https://github.com/sokra/vscode-inline-types)

![image](https://github.com/sokra/vscode-inline-types/raw/master/assets/demo.png)

This feature seems to be supported natively by many IDE. such as [Inlay Hints](https://blog.jetbrains.com/webstorm/2019/06/webstorm-2019-2-eap-5/#inlay-hints)

**Comment by alexandrudima** [comment]
I think this is implemented well by an extension, there is no clear reason at this time to reimplement this in the core of VS Code.
