### ISSUE TITLE
'Using .NET Core in Visual Studio Code' by default has 26 errors

### ISSUE THREAD

**Issue by edwin-hendriks** [microsoft/vscode#86597]
- VSCode Version: 1.40.2
- OS Version: Win NT x64 10.0.18362

**Steps to Reproduce:**

1. Fill in prerequisites on [Using .NET Core in Visual Studio Code](https://code.visualstudio.com/docs/languages/dotnet) with button **Download .NET Core SDK**.
2. Perform steps as described in **Create a "Hello World" app** of same [Using .NET Core in Visual Studio Code](https://code.visualstudio.com/docs/languages/dotnet)

Does this issue occur when all extensions are disabled?: No

**Result:** 

With the C# extension (which is part of the prerequisites) the errors appear. With this extension disabled it works as I would have expected. 

**What I would have expected:** 

I would have expected that there would not be any errors at all after performing the step 1 and 2 of **Create a "Hello World" app#**. Especially for a "Hello world" app.

**Comment by octref** [comment]
@gregvanl fyi, think we should make sure the doc is up-to-date. is what on that page still the recommended way for setting up?
