### ISSUE TITLE
GitFs: support proper e-tag handling

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86604]
I am not sure if this would be possible, but it would be good if the file system provider for git could return actual `mtime` and `size` values here:

https://github.com/microsoft/vscode/blob/6de6aa0278b35763d9063e079ab8eaa8f2031289/extensions/git/src/fileSystemProvider.ts#L127

With proper values, the file service is able to quickly return with a `NOT_MODIFIED_SINCE` error and avoid reading the same content again if already known. 

The etag is computed as this:

https://github.com/microsoft/vscode/blob/6de6aa0278b35763d9063e079ab8eaa8f2031289/src/vs/platform/files/common/files.ts#L821

**Comment by eamodio** [comment]
Getting the size should be straight forward (I do this in the GitLens git fs provider), but the `mtime` I guess would just need to be the timestamp of the commit which would be another lookup. But since this data should always be readonly would a static `mtime` be acceptable?

**Comment by bpasero** [comment]
> would a static mtime be acceptable

How would that look like? What is a static mtime?

**Comment by eamodio** [comment]
Something like a minimum date -- so that anytime you get the resource, the etag would always be not modified.

**Comment by bpasero** [comment]
But that is not the contract of how `mtime` should work. If the file changes, its `mtime` needs to advance. If you cannot compute a good `mtime`, you need to increment a counter everytime the resource is requested to make sure the file service is not wrongly assuming the file did not change.

**Comment by eamodio** [comment]
But for a given git uri the file contents is immutable. For the file contents to change the sha would need to change which is part of the uri.

Well except for the special uri for the index (staged), but for those we can probably use the mtime of the file on disk.

**Comment by bpasero** [comment]
Yeah makes sense.

**Comment by joaomoreno** [comment]
> But for a given git uri the file contents is immutable. For the file contents to change the sha would need to change which is part of the uri.

Not really, since we can use references like `master` or `HEAD` or `~` (index), and we often do.

**Comment by eamodio** [comment]
Won't a static mtime make the workbench think it is never changed?

**Comment by bpasero** [comment]
Yes, if `mtime` and `size` are static, workbench would think the file has not changed when reading it (again - after having it opened once). 

If you cannot compute a proper `mtime`, use a counter that increments on each `stat` call to disable this.

**Comment by joaomoreno** [comment]
I can just use `Date.now()` right?

**Comment by bpasero** [comment]
Yes that should work.
