### ISSUE TITLE
Python test discovery never finishes when git submodule present

### ISSUE THREAD

**Issue by JasonL4t1qbit** [microsoft/vscode#86606]
Issue Type: <b>Bug</b>

Add a submodule (in my case https://github.com/bitnami-labs/kube-libsonnet) in the subdir of the testing root. Test discovery that worked immediately beforehand no longers works. Removing the submodule causes the tests to be discoverable again. 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
render-crlf|med|1.4.4
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
vscodeintellicode|Vis|1.2.0

</details>

**Comment by RMacfarlane** [comment]
Please file this on the [python extension](https://github.com/Microsoft/vscode-python)
