### ISSUE TITLE
Smooth transition of explorer with the new "Highlight file on active editor change" feature

### ISSUE THREAD

**Issue by agostini01** [microsoft/vscode#86603]
This tries to address the problem here https://github.com/microsoft/vscode/issues/84365  from a different perspective

It seems that this feature was introduced on 1.40: "The Source Control view will now automatically highlight the active editor file in its tree/list view". It does that by jumping to the highlighted file.

I would like to propose a smother transition from the current file in the explorer to the clicked file in the explorer.

Why?

I have been working in a project with several files in different folders. The source tree does not fit the screen. When looking around for another file in the source tree, I get a little confused on where I am, having to scroll up and down to verify the the folders around the active file.

By smooth transitioning the source tree view to the right location would better help understanding where the highlighted file is actually located.

Thanks!

**Comment by agostini01** [comment]
[This gif highlights how hard is to follow the exploring jumping around](https://preview.redd.it/84k69vl392b41.gif?format=mp4&s=6f9ccc3c730fb7348f111b1f965b6fcebf14974f).

**Comment by kaustubhcs** [comment]
Been trying to get this feature for months! It would be great to have this!
