### ISSUE TITLE
Screenreader issues in global search/replace

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8660]
VSCode Version: insiders 7/1
OS Version: Windows
1. Open Search Pane
2. Search for a string with matches in your workspace
3. Tab to the first search result
4. Tab to the Replace or Remove button on the right end of  a search match

-> screenreader remains silent when those buttons have focus

**Comment by bpasero** [comment]
I think this is a general problem with actions inside trees. 

@kieferrm do you see this bug in all trees with actions? if so, we should only have one issue for it.
