### ISSUE TITLE
Feedback windows closes on right click

### ISSUE THREAD

**Issue by kevball2** [microsoft/vscode#86614]
when entering feedback and then right clicking your feedback window is closed removing your comments. comments are not saved when re-opening the window

**Comment by RMacfarlane** [comment]
@kevball2 Can you include your VSCode version and what OS you're using?

**Comment by kevball2** [comment]
OS build 19037.1 version 2004
VScode Version - 1.40.2
Python add-in - 2019.11.50794

**Comment by RMacfarlane** [comment]
Thanks! Is this the feedback window you're referring to?
![Screen Shot 2019-12-09 at 12 01 01 PM](https://user-images.githubusercontent.com/3672607/70471741-a71d3000-1a82-11ea-9e39-9b5eabaa0bee.png)

Or something from the Python extension?

**Comment by kevball2** [comment]
@RMacfarlane  that is correct yes.

**Comment by RMacfarlane** [comment]
Repro steps:
1. Have `"window.titleBarStyle": "custom"`
2. Right click on the activity bar (or any UI that would bring up a context menu)

Seems to only happen on Windows.

**Comment by sbatten** [comment]
The feedback widget uses the same context view that the menu widgets use. Currently, there can only be one at a time. We need to introduce some separation mechanism.

/cc @joaomoreno

**Comment by bpasero** [comment]
Obsolete: https://github.com/microsoft/vscode/issues/188960
