### ISSUE TITLE
Resize Pane Shortcut (Mac) Feature Request. 

### ISSUE THREAD

**Issue by jfacoustic** [microsoft/vscode#86618]
It's my understanding VSCode on Linux has shortcuts to resize editor panes according to the issue below.  Can this feature be enabled by default on Mac?  

https://github.com/microsoft/vscode/issues/46100

**Comment by RMacfarlane** [comment]
@jfacoustic These commands are also available on Mac, just with different default keybindings than linux:
![Screen Shot 2019-12-09 at 12 57 38 PM](https://user-images.githubusercontent.com/3672607/70472168-7f7a9780-1a83-11ea-81f5-ad65000ea0a1.png)

**Comment by jfacoustic** [comment]
@RMacfarlane Editor panes, not terminal panes.  control + command + arrows in the editor just switches which pane I'm working on.

**Comment by jfacoustic** [comment]
I guess the terminology is "group" not "pane".  Control-Alt-Arrow is set up to "move Editor into next Group," so I'd imagine this would be "Resize current group."

**Comment by jfacoustic** [comment]
It sounds like `View: Increase/Decrease current view size` does what I need, although not quite as refined as tmux.
