### ISSUE TITLE
Jupyter Notebook  not formatting code correctly 

### ISSUE THREAD

**Issue by kevball2** [microsoft/vscode#86615]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Launch GettingStartedKeras.ipynb from https://github.com/MicrosoftLearning/Deep-Learning-Explained/tree/master/Module2
2.Run all code blocks in section 2.1 
3. Code in following block does not format properly 

`for i in range(5, 20, 4):
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    plt.show()
    print('Label = ' + str(train_labels[i]))`

the first image is displayed then all 4 labels. the following 3 images are show last. 

Expected Results: 
each picture and label should be shown in order per the instructions in the for loop

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
Please reopen this issue on the python extension: https://github.com/Microsoft/vscode-python
