### ISSUE TITLE
css.lint.emptyRules has no effect

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#86613]
1.  Update the setting to 'error'

:bug: => warnings do not change to errors

**Comment by octref** [comment]
It does for me:

![image](https://user-images.githubusercontent.com/4033249/70463586-03c41f00-1a72-11ea-8336-5ea189d2b417.png)

Are you sure you are not editing a scss/less file? If so you need to configure scss/less.lint rules.

**Comment by octref** [comment]
Closing since @sbatten had files.association to set `*.css` as `scss` 🤷‍♂
