### ISSUE TITLE
Git: LFS support for image diffing

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#86611]
**Steps to Reproduce:**

1. In a repository with git LFS enabled (such as the VS Code docs repo)
2. Open a modified image diff 

**Bug**
Left hand side shows an image load error. Here's the content for a git lfs file we get:

```
version https://git-lfs.github.com/spec/v1
oid sha256:65ccfe99efef1afc4bbd0fade1397c620759d165d0af1f2394afce4f34570a5f
size 166430
```

This works properly when not using git LFS

Does this issue occur when all extensions are disabled?: Yes

**Comment by 5c077yP** [comment]
Wow just found this comment on another repos' issues page: https://github.com/git-lfs/git-lfs/issues/440#issuecomment-501007460. tl;dr: `git config diff.lfs.textconv cat `. Now both sides work for me

**Comment by lszomoru** [comment]
Closing based on this comment - https://github.com/microsoft/vscode/issues/86611#issuecomment-875894108.
