### ISSUE TITLE
GitHub is not connecting 

### ISSUE THREAD

**Issue by Beniyam-WD** [microsoft/vscode#86620]
Issue Type: <b>Bug</b>

i won't be able to connect to Git hub? 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
angular2-snippets|dan|1.0.21
Angular-BeastCode|Mik|8.1.2
bootstrap4-vscode|the|6.1.0

</details>

**Comment by Beniyam-WD** [comment]
basically I won' be able to connect from VS code using terminal ?

**Comment by RMacfarlane** [comment]
@Beniyam-WD I'm not sure what you're referring to, can you include exact steps of what you are doing? Or a screenshot?

**Comment by Beniyam-WD** [comment]
![image](https://user-images.githubusercontent.com/54153242/70475995-c37d9480-1aa3-11ea-9b26-c3c5df007708.png)

**Comment by Beniyam-WD** [comment]
Thanks for the prompted response, I was trying to pus my code from VS Code, but I wont be able to connect my git hub repository,

**Comment by Beniyam-WD** [comment]
I was trying to push my code from VS Code to Git hub, but I won’t be able to connect my git hub repository , I have tried by copying my repository url and on my VS Terminal, no luck

**Comment by RMacfarlane** [comment]
Thanks for the screenshot. The documentation [here](https://code.visualstudio.com/Docs/editor/versioncontrol#_git-support) may be helpful - do you have Git version 2.0.0 or greater installed?

**Comment by Beniyam-WD** [comment]
Thank you, but i am using online version,  and i will see the documentation.
