### ISSUE TITLE
Auto closing brackets not functioning for c# in 1.3.0-insider

### ISSUE THREAD

**Issue by jcloutz** [Microsoft/vscode#8662]
- VSCode Version:1.3.0-insider
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Create new c# file (.cs)
2. Type the following `void Foo() {` and the bracket fails to auto close.

I have test both the c#, and legacy c# extensions and both fail to close the brackets in the in insiders edition. Both plugins work properly in 1.2.1.

The auto closing bracket also works properly in 1.3.0-insider for other tested languages C, C++, JS, PHP.

**Comment by kaanoo2904** [comment]
Same here: Ubuntu 16.04 , VS 1.3.0-insider , C# extension 1.2.1

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by DustinCampbell** [comment]
@bpasero: Note that this works fine in VS Code 1.2.1 and is being reported as broken in VS Code 1.3.0 Insiders. That _seems_ to point at this being a VS Code issue.

**Comment by jrieken** [comment]
@aeschli, @alexandrudima did something change here? The [omnisharp config](https://github.com/OmniSharp/omnisharp-vscode/blob/master/csharp.configuration.json) didn't change

**Comment by alexandrudima** [comment]
I can reproduce at a8eadbd8d42034bf926d657d33e971892b1b5660 and not at db21446a84f7afb9f496462941e4e93591db330d (parent of a8eadbd8d42034bf926d657d33e971892b1b5660) so IMHO the bad change was introduced with a8eadbd8d42034bf926d657d33e971892b1b5660

**Comment by alexandrudima** [comment]
IMHO the bad change is:

![image](https://cloud.githubusercontent.com/assets/5047891/16614507/f1a4214c-4371-11e6-9642-31da2761db28.png)
