### ISSUE TITLE
Cannot type over closing parenthesis

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86623]
Version: 1.41.0-insider
Commit: bef029a9d21904c0085c4e8ef1335d9c33a28fa4
Date: 2019-12-09T15:40:24.842Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

1. Type `console.log(|)` in a TS file
2. Make completion show up
3. `tab` to select completion
4. `)` enters a new parenthesis 🐛 I expect it to overwrite the closing parenthesis.

I have all extensions disabled.
This seems to be a regression from stable.

![bug](https://user-images.githubusercontent.com/4033249/70480417-8067f500-1a94-11ea-9755-df7c4a74870c.gif)

**Comment by octref** [comment]
I didn't bisect but before pressing upgrade on my home laptop's Insider, I don't see this happening. So it's one of the commits in the last few days.

Version: 1.41.0-insider
Commit: e7c13723938e42ee5ac402289d7b59be9a727536
Date: 2019-12-05T23:15:44.450Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

**Comment by alexandrudima** [comment]
I cannot reproduce, could you try removing some of your settings? Maybe there's a setting that impacts the edit suggestions do?

**Comment by alexandrudima** [comment]
@octref The auto closing `)` is overtyped only if the editor inserted it and if your cursor has not left the range between `(` and `)`.

This is in stable since a couple of milestones I think. There is a setting to always overtype `"editor.autoClosingOvertype": "always"`.

**Comment by octref** [comment]
@alexdima This makes sense, but quite commonly I make a function to include an extra parameter and need to move into the function calls to add that parameter.

`"editor.autoClosingOvertype": "always"` works fine for me. Thanks!
