### ISSUE TITLE
Jupyter Notebook editor hover issue

### ISSUE THREAD

**Issue by Bill-Fujimoto** [microsoft/vscode#86629]
Issue Type: <b>Bug</b>

When hovering the mouse over a function in a jupyter notebook:
1.  the documentation does not consistently appear.  The file needs to be closed and reopened to appear.
2.  when documentation does appear, cannot move mouse pointer into the text block to scroll thru the contents, the text block immediately disappears.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
remote-wsl|ms-|0.40.3
vscode-yaml|red|0.6.1
material-theme|zhu|3.2.0

</details>

**Comment by RMacfarlane** [comment]
Please reopen this issue on the Python extension
