### ISSUE TITLE
Remote-SSH: "remote.SSH.path" is an 'Unknown configuration setting' in settings.json 

### ISSUE THREAD

**Issue by binhlt1310** [microsoft/vscode#86627]
When developing on a remote machine via the Remote-SSH extension vs code doesn't recognise "remote.SSH.path" is the settings.json: "remote.SSH.path" is an 'Unknown configuration setting" in settings.json

VSCode Version: 1.35.1
OS Version: Windows 7 host 
![image](https://user-images.githubusercontent.com/54388461/70488099-f45cd880-1b3a-11ea-822a-2aeed50580f8.png)

**Comment by RMacfarlane** [comment]
@binhlt1310 What version of the Remote-SSH extension are you using? Please try upgrading VSCode so that the extension will upgrade.
