### ISSUE TITLE
Copying when nothing is selected should not insert anything into the clipboard

### ISSUE THREAD

**Issue by chanan** [microsoft/vscode#86625]
Issue Type: <b>Bug</b>

1. Select something
2. Press Ctrl+C
3. un select everything and make sure nothing is selected
4. Press Ctrl+C
5. Press Ctrl+V

Result:
Nothing gets pasted

Expected Result:
Original text from the first Ctrl+C should be pasted as is true in any other editor

Note: 
Pressing Win+V shows the blank entry in the clipboard

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.19037

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (11.32GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/cbraunstein/source/repos/radigio-order|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
react-hooks-snippets|AlD|1.1.6
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.0
prettier-vscode|esb|3.11.0
vscode-pull-request-github|Git|0.13.0
todo-tree|Gru|0.0.162
rest-client|hum|0.23.0
docthis|joe|0.7.1
vscode-colorize|kam|0.8.15
vscode-postgresql|ms-|0.2.0
remote-wsl|ms-|0.40.3
vscode-jest|Ort|3.0.2
code-spell-checker|str|1.7.20
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Please add `"editor.emptySelectionClipboard": false` to your settings as described here: https://github.com/Microsoft/vscode/issues/11112
