### ISSUE TITLE
Latest update causes the window to stop responding at random

### ISSUE THREAD

**Issue by Merith-TK** [microsoft/vscode#86633]
VSCode says the window has stopped responding for little to no reason on startup and at  random
![image](https://user-images.githubusercontent.com/10422110/70493609-20d20f80-1abd-11ea-963b-34d32172cb73.png)
![image](https://user-images.githubusercontent.com/10422110/70493806-cbe2c900-1abd-11ea-8b41-d4932f2699f6.png)

- VSCode Version: 
```
code --version
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64
```
- OS Version:
![image](https://user-images.githubusercontent.com/10422110/70493634-347d7600-1abd-11ea-8df4-95f0df2533e3.png)

Steps to Reproduce:
Unknown, My specs are a Core i3 3rd gen, Intel integrated graphics 4k series, 
i even tried reinstalling and it didnt fix the issue, and no recent updates of any other component of my system have been upgraded. at all.

Does this issue occur when all extensions are disabled?: Yes,
![image](https://user-images.githubusercontent.com/10422110/70493752-9a69fd80-1abd-11ea-9851-81044329a536.png)

**Comment by Merith-TK** [comment]
Also noticed that when these issues occure, Memory usage drops from around 300-330mb, to <50mb

**Comment by RMacfarlane** [comment]
@Merith-TK Did this only start happening with the most recent VSCode update? Does this happen only for particular projects, or anything you have open?

**Comment by Merith-TK** [comment]
It started with the most recent update yes. It occurs at random. i use a few extensions and develop golang
my workspace is a mounted Samba share. i can give you logs in a few hours once im out of school.

**Comment by Merith-TK** [comment]
[2019-12-11_19-30-28.zip](https://github.com/microsoft/vscode/files/3953679/2019-12-11_19-30-28.zip)
Logs from me opening today
the things that happened in order
1. The new update readme tab opened, nothing rendered, (BLANK TAB)
2. I opened the file explorer and navigated to open `Z:\` which is my workspae
3. `Window is not responding` popup, clicked reload
4. Window reloaded. `Window is not responding` popup occured again, i clicked close

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Merith-TK** [comment]
Will try tomarrow.

I am guessing that insider builds are more verbose with their logs?

**Comment by Merith-TK** [comment]
[2019-12-12_07-36-09.zip](https://github.com/microsoft/vscode/files/3956548/2019-12-12_07-36-09.zip)
Insiders doesnt crash, stops responding at first but doesn't crash (logs are insiders first run.)

**Comment by bpasero** [comment]
@Merith-TK to clarify, "stops responding" means you cannot do anything in the UI? does eventually a dialog popup informing about that fact?

**Comment by Merith-TK** [comment]
This time around, it is just the standard windows "application has stopped
responding" bar at the top for a a few seconds, and then resumes.

**Comment by bpasero** [comment]
@Merith-TK does it reproduce with any folder you open or only specific?

**Comment by Merith-TK** [comment]
It does it on startup, 
Sorry for being unhelpful if i am, the weird thing is when im working over RDP it doesn't give issues, 


SPECULATION:
which is leading me to believe it may be a graphics issue and electron, as i noticed RDP connections use a different graphics driver mode.
 even though that makes no sense as chrome does not fail at all,

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by jmlivingston** [comment]
I'm seeing this also on a Mac with version 1.40.1, specifically anytime I try to search on anything. I have reverted to 1.39.2 and am not seeing any problems. It actually will crash my machine and I have had to do a hard reboot several times as the machine freezes up.

Environment
- macOs Mojave - 10.14.6
- Processor - 3.1Ghz i7
- Memory - 16GB
- Graphics - Radeon Pro 560

I also have two LED 27 monitors attached to my Mac running 2560x1440 resolution using USB-C to DisplayPort.

I need to get back to work, but will try reproducing with hardware-accelaration disabled later.

**Comment by bpasero** [comment]
Please do.

**Comment by Merith-TK** [comment]
Update for me, Hardcrashing (window not responding, windows saying that, not vscode) has stopped
But vscode's "not responding" still pops up occasionally, but i can just tell it to keep waiting

but the problem is that it feels like i am trying to program over vnc over cellular service, it is way too sluggish

**Comment by bpasero** [comment]
@Merith-TK can you check what I asked in https://github.com/microsoft/vscode/issues/86633#issuecomment-565322500

**Comment by Merith-TK** [comment]
Sure, testing now

**Comment by Merith-TK** [comment]
Yeah that helps. alot,

**Comment by bpasero** [comment]
Ok, closing given the workaround.
