### ISSUE TITLE
Vscode has been used for a period of time, which makes the system stuck. You can only use it by forcing shutdown and restart the computer

### ISSUE THREAD

**Issue by XYYHHKFD** [microsoft/vscode#86637]
所需的数据太大，无法直接发送。我
Issue Type: <b>Performance Issue</b>

Vscode has been used for a period of time, which makes the system stuck. You can only use it by forcing shutdown and restart the computer。
 don't know if it's a plug-in problem, but I feel like I can't do without a plug-in before learning and using vscode to develop and make.
My system is win10 1903, 8g memory.

I hope to get a really effective solution, such as which plug-in has problems.

Thank you.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (4.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    89	  3232	code main
    0	    68	   732	   window (问题报告程序)
    0	    70	  8592	   shared-process
    0	   177	  8628	   window (点击按钮修改多个p标签的内容.html - H5-CSS3-JS-JQ - Visual Studio Code [管理员])
    0	    12	  7636	     watcherService 
    0	    11	  9140	       console-window-host (Windows internal process)
    0	    34	  8944	     searchService
    0	   147	 12292	     extensionHost
    0	   102	  4568	       electron_node server.js 
    0	    87	 12584	       "C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=12292
    0	   157	 12556	   gpu-process
    0	    14	 13088	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (点击按钮修改多个p标签的内容.html - H5-CSS3-JS-JQ - Visual Studio Code [管理员])
|    Folder (H5-CSS3-JS-JQ): 59 files
|      File types: html(24) jpg(14) png(7) css(4) json(2) js(2) doc(1)
|      Conf files: settings.json(1) launch.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.4.4
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|30.0.0
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
XMLLanguageSupport|IBM|0.0.1
docthis|joe|0.7.1
Angular2|joh|8.2.0
vscode-view-in-browser|kop|1.0.5
node-module-intellisense|lei|1.5.0
vscode-fileheader|mik|0.0.2
vscode-language-pack-zh-hans|MS-|1.40.2
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
vuehelper|oys|0.1.0
material-icon-theme|PKi|3.9.2
vscode-xml|red|0.9.1
code-spell-checker|str|1.7.20
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.6.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>
们已经将其写入剪贴板，请粘贴。

**Comment by RMacfarlane** [comment]
@XYYHHKFD Can you please follow our [Performance Issues guide](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to help diagnose the problem?
