### ISSUE TITLE
Key bindings for the command palette.

### ISSUE THREAD

**Issue by Xdminsy** [microsoft/vscode#86635]
Can we add some functions like `selectPrevCommand` or `selectNextCommand` for command palette so that we can bind hotkeys like "ctrl+p" to select the previous command, avoiding the use of arrow keys. Thus we can have a more coherent experience if we are using emacs keymaps. 
And add a when rule like `inCommandPalette`,  then we can simulate most readline emacs mode hotkey like `ctrl+h` to backspace, `ctrl+j` to choose the command, `ctrl+d` to delete forward char and so on. This may be very helpful for some 60% keyboard users whose keyboard has no arrow keys.

I tried binding `ctrl+n` to "cursorDown" with no when clause, it still doesn't work in command palette. I searched in Keyboard Shortcuts and only found a "workbench.action.showCommands" function related to command palette. I have to use arrow keys or backspace to control. Well while I am using VSCodeVim and bind some emacs hotkey for my vscode, I need no arrow keys in most cases, it's a pity I can not bind keys for command palette. I also looked for AHK but it seems hard for it to have a same "when" condition.

**Comment by chrmarti** [comment]
Pressing `Cmd+P` on Mac works as you suggest if you keep `Cmd` pressed. `Ctrl+P` should do the same on Windows.

@bpasero There used to be a way to navigate to the previous entry by additionally holding `Shift`, but that doesn't work for me at the moment. Does that need configuration?

**Comment by bpasero** [comment]
I can press `Cmd+Shift+P` and quick select the previous entry on my macOS without special configuration.

**Comment by Xdminsy** [comment]
Sorry I have no mac device, I don't know how to do these on Windows now, when in command palette, `ctrl+n` is still new tab and `ctrl+shift+n` is new window while `ctrl+alt+n` has no effect. 

I wonder how macOS achieve these? Do mac maps such keys to arrow keys or need specific programs to support it by them self?

**Comment by chrmarti** [comment]
@bpasero You're right, it works now. 🤷‍♂ 

@Xdminsy Try:
- Press&hold `Ctrl`, press&release `p`.
- The file picker should now be open while you are still holding `Ctrl`.
- Press&release `p` multiple times.
- The selection should move down by one entry each time.
- Release `Ctrl`.
- The currently selected file should be opened.

Additionally holding `Shift` allows you to move the selection up.

Your other suggestions are not supported at the moment. I have labelled this issue as feature request for these.

**Comment by Xdminsy** [comment]
Oh I see, file picker don't need arrow key, it's great, works well.

Looking forward to custom hotkeys for command palette. Thanks!

**Comment by bpasero** [comment]
This can be achieved already via the `workbench.action.quickOpenSelectPrevious` and `workbench.action.quickOpenSelectNext` commands in combination with the `inCommandsPicker` context.
