### ISSUE TITLE
Issues with reliability and usability of  built in Extension command line commands, and Question about metrics and guidance.

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#8663]
I have been working on a PowerShell Module for working with VSCode Extensions and Metrics. This project got started by looking for a better way to get metrics on Publishers and Extensions. I have a large number of published extension, roughly 300 or so which are mostly themes, and found it was almost impossible to really get any sort of idea on numbers.

My module can be found here [VSCodeExtensions](https://github.com/gerane/VSCodeExtensions)

When implementing my `Install-VSCodeExtension` and `Uninstall-VSCodeExtension` I first tried to use wrappers around the `code --install-extension` and `code --uninstall-extension`. I found it incredibly difficult to work with the built in commands. 

- The first issue I encountered, is the cmd returns before the JS does, so there is no way to capture the output to error handle. This also might potentially be the reason why PowerShell ISE gets zero output from --list-extensions. If you run the command to get installed extension in the ISE it does not show any output. I felt this issue was related enough for this issue, but if it is not I can open up a separate issue.

- When I first started to write Pester tests for my wrappers, I had to stop because the internal wrapped commands weren't reliable enough to test. If you look in that repo will notice, I really don't have any Pester unit/integration tests for that project, and that is because I don't want to write them only to have to change my whole implementation because the internal commands are not reliable. So right now, I have everything written in PowerShell. Gtting installed extensions and versions is just parsing the package.jsons, finding packages I am using the cache url, uninstalling packages I am removing all versions of extension folders, and to install I am getting the asseturi, downloading vsix, unpacking vsix, moving to vscode folder and then renaming manifest and moving to vscode folder. Then I added an update command to find latest installed versions and then check to see if theres an update and updates if available. I like this one for my powershell profile.

- Since the output comes from a separate process, I cannot catch the output in a variable for use in powershell. 

My solution was to replicate the installation in pure powershell. I can actually control the errors and what causes them. I much prefer this method as I am not dependent on an external cmd file. One thing I did not replicate was the added metadata that is added into the package.json, and I could easily do this for 99% of the data, but there was one field I was uncertain about. The "X-Market-User-Id" I was seeing odd and different results. I look at some, and the value was a long randon string, and then others would be "someValue.machineID". The other issue was the amount of metadata has been inconsistent. 

Sometimes you might get a large amount of metadata like this

```json
{
"__metadata": {
		"galleryApiUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"id": "7a8e7281-d65b-4a07-b901-0cd5756fa98e",
		"publisherId": "a5c25faf-bf60-4941-81b9-9a852b96c5fb",
		"publisherDisplayName": "gerane",
		"installCount": 420,
		"versions": [
			{
				"version": "0.0.2",
				"date": "2016-04-27T21:22:48.88Z",
				"downloadHeaders": {
					"X-Market-Client-Id": "VSCode",
					"User-Agent": "VSCode",
					"X-Market-User-Id": "95e28e718b572a5c28f0d6acfd3c5c00ad85a8df6de64cebe9fbd63ff73d69f3"
				},
				"downloadUrl": "https://gerane.gallery.vsassets.io/_apis/public/gallery/publisher/gerane/extension/Theme-TomorrowNight/0.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true",
				"manifestUrl": "https://gerane.gallery.vsassets.io/_apis/public/gallery/publisher/gerane/extension/Theme-TomorrowNight/0.0.2/assetbyname/Microsoft.VisualStudio.Code.Manifest"
			},
			{
				"version": "0.0.1",
				"date": "2015-11-22T08:18:07.117Z",
				"downloadHeaders": {
					"X-Market-Client-Id": "VSCode",
					"User-Agent": "VSCode",
					"X-Market-User-Id": "95e28e718b572a5c28f0d6acfd3c5c00ad85a8df6de64cebe9fbd63ff73d69f3"
				},
				"downloadUrl": "https://gerane.gallery.vsassets.io/_apis/public/gallery/publisher/gerane/extension/Theme-TomorrowNight/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true",
				"manifestUrl": "https://gerane.gallery.vsassets.io/_apis/public/gallery/publisher/gerane/extension/Theme-TomorrowNight/0.0.1/assetbyname/Microsoft.VisualStudio.Code.Manifest"
			}
		]
	}
}
```

Then other times you might just get 3 small pairs at the bottom.

```json
	"__metadata": {
		"id": "14f7c4fd-fedf-4513-a31a-163a1b07a997",
		"publisherId": "a5c25faf-bf60-4941-81b9-9a852b96c5fb",
		"publisherDisplayName": "gerane"
	}
```

I am not sure what your recommended way of handling this would be. I know the metadata is not required, but I am not quite sure what that impacts. The other reason is the built in commands are about as basic as they can get. Writing this native in powershell lets me build in pipeline support and ability to query by any property. This allows me to do things like this

```powershell
Find-VSCodeExtension -ExtensionName * -category Snippets -Tag *type* -PublisherName 'gerane' | Install-VSCodeExtension
```

How does VSCode handle the metrics for extension installs? I am guessing having this external to the built in command lines is going to break the install metrics, but it just was not reliable enough to use for me. It would be nice if Code offered a native powershell module for Windows, but since I am not so sure that will happen, I was hoping I could get a little guidance on the direction I should go. If anything, maybe I can get some support or potentially work with the PowerShell extension in some way.

One thing I am worried about, is the apis or uris that are currently accessible, might be removed one day without warning.

There is another issue with --uninstall-extension that I will open a second ticket for. It is only uninstalling the latest version. So if you have 6 versions installed, you have to run the command 6 times to actually remove the extension.

cc @daviwil 

- VSCode Version: 1.3.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Run large number of Install/uninstall extensions
2. Occasional unexplained failures with no way of knowing cause.

**Comment by joaomoreno** [comment]
I feel your pain with the **wrappers** and I'm way out of my league as with trying to understand **cmd**, **call** and all their complicated ramifications... One idea you could do would be to mimic what [code.cmd](https://github.com/Microsoft/vscode/blob/master/resources/win32/bin/code.cmd) itself does: it launches `Code.exe resources\app\out\cli.js ARGS` with the `ATOM_SHELL_INTERNAL_RUN_AS_NODE` env variable set to `1`. This would surely let you capture its output and wait for its end.

Code recently started _cropping_ the **metadata**, so we only need the small 3 pairs you mentioned. The bigger snippet was needed in older versions only.

The **metrics** are fetched live with the [Marketplace API](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionGalleryService.ts). Yes, this API is not published and **will** change over time. Code doesn't own it, but the Visual Studio family, as it's a feature that runs across the whole family.

**Comment by joaomoreno** [comment]
Closing this since it is a discussion issue. We can keep talking here.

**Comment by gerane** [comment]
@joaomoreno did you remove the ability to open files with the command recently? This stopped working in insiders for the last few days.

**Comment by joaomoreno** [comment]
I don't understand what you mean by *the ability to open files with the command*, can you elaborate?

**Comment by gerane** [comment]
I opened this #8947

`code-insiders C:\path\to\project` or `code-insiders.cmd C:\path\to\project` would open the project in a new Code window.

**Comment by gerane** [comment]
or just `code-insiders` or `code-insiders.cmd` would open a new Code Window, but now it does now.

**Comment by gerane** [comment]
This only happens from inside of Code. Works properly from outside of code. This just started happening earlier this week.
