### ISSUE TITLE
Unable to Search in Marketplace, vscode experiments

### ISSUE THREAD

**Issue by 20chan** [microsoft/vscode#86631]
Actually it's dup of #81814 but with more informations.
- VSCode Version:
- OS Version: Windows 10 Pro 18362

Steps to Reproduce:

1. Search anything on marketplace
2. Got `Unable to Search in Marketplace` message.

Does this issue occur when all extensions are disabled?: Yes
Solution: Set `workbench.enableExperiments` to false

---

I opened developer tools and saw what's wrong.
There was error message:
```
ERR Unexpected token < in JSON at position 0: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.asJson (file:///C:/Users/2/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1714:949)
```

I followed it, it was `getExperiments`, 178 line at  `experimentService.ts`.

```js
return asJson(context).then(..)
```

Inside `asJson(context)`, `buffer.toString()` returns next weird text:

```
"<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">↵<path fill-rule="evenodd" clip-rule="evenodd" d="M9.88465 1.69445L8.57246 3H11.346C11.5656 3 11.783 3.04327 11.9858 3.12734C12.1886 3.2114 12.3729 3.33461 12.5281 3.48993C12.6833 3.64525 12.8063 3.82963 12.8902 4.03253C12.9741 4.23543 13.0172 4.45287 13.017 4.67243L12.517 4.672H13.017V4.67243V10.4539C13.8823 10.6794 14.521 11.4661 14.521 12.402C14.521 13.5138 13.6198 14.415 12.508 14.415C11.3963 14.415 10.495 13.5138 10.495 12.402C10.495 11.4596 11.1426 10.6685 12.017 10.4493V4.672V4.67158C12.0171 4.58341 11.9998 4.4961 11.9661 4.41462C11.9324 4.33314 11.883 4.25911 11.8207 4.19674C11.7584 4.13437 11.6844 4.08489 11.6029 4.05114C11.5215 4.01738 11.4342 4 11.346 4H8.53857L9.83833 5.34332L9.11967 6.03868L7.00067 3.84868L7.00735 3.14655L9.17935 0.98555L9.88465 1.69445ZM11.495 12.402C11.495 11.8425 11.9485 11.389 12.508 11.389C13.0675 11.389 13.521 11.8425 13.521 12.402C13.521 12.9615 13.0675 13.415 12.508 13.415C11.9485 13.415 11.495 12.9615 11.495 12.402ZM2.499 3.513C2.499 2.95354 2.95254 2.5 3.512 2.5C4.07147 2.5 4.525 2.95354 4.525 3.513C4.525 4.07247 4.07147 4.526 3.512 4.526C2.95254 4.526 2.499 4.07247 2.499 3.513ZM3.512 1.5C2.40025 1.5 1.499 2.40125 1.499 3.513C1.499 4.44783 2.13622 5.23382 3 5.46031V11.307C3 11.7502 3.17605 12.1752 3.48942 12.4886C3.8028 12.802 4.22782 12.978 4.671 12.978H7.44813L6.13543 14.2835L6.84057 14.9925L9.01257 12.8325L9.01941 12.1304L6.90041 9.93939L6.18159 10.6346L7.48086 11.978H4.671C4.49304 11.978 4.32237 11.9073 4.19653 11.7815C4.07069 11.6"
``` 

I double checked network tab and there was request to `https://az764295.vo.msecnd.net/experiments/vscode-experiments.json`, and response same as above.

![it's real](https://user-images.githubusercontent.com/16171816/70490434-aeefd980-1b41-11ea-82c1-dcdf63a1635f.png)
![seriously](https://user-images.githubusercontent.com/16171816/70490439-b1523380-1b41-11ea-92a3-54a9a77e7bb0.png)

But when I send request directly to same url, it's response is pretty normal:

![wsl curl](https://user-images.githubusercontent.com/16171816/70490446-b31bf700-1b41-11ea-9689-acc5cee1aa4e.png)

Even I `copy all as cURL` it looks very normal.

![copied curl](https://user-images.githubusercontent.com/16171816/70490843-e14e0680-1b42-11ea-941d-4b3c8b6795bf.png)

I checked other svg requests but none of them matched. Absolutely nonsense.

Response of request said about `WSL extension`, so I turned it off even deleted it but same error still occurres.

So I just changed `workbench.enableExperiments` to false, to just skip function, and it totally works very well.
After few `Error querying extensinos gallery canceled` messages, I'm finally able to search on Marketplace.

![wow it works](https://user-images.githubusercontent.com/16171816/70491247-16a72400-1b44-11ea-8d91-346302215cc7.png)

I have no idea about that request, and it seems like I was not only for me (#81814).

---

After disable experiments, I reinstalled extensions and searches are just working very fine, no problem at all.

**Comment by sandy081** [comment]
@20chan Thanks for figuring this out. I was completely clueless from where this is coming. Now I know because of your investigation.

@roblourens I remember you are chiming in for some experiments related issues. So assigning to you,

**Comment by 20chan** [comment]
I found what was that 'svg-like' texts are. It was `file:///..../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/git/resources/icons/dark/open-change.svg` and it was very weird because it's in my disk.

Look at captured image in my issue, network tab in developer tools.
Status code of request to `vscode-experiments.json` is `200 (from disk cache)`, and I think that **from disk cache** is the problem.

**Comment by roblourens** [comment]
Can you check whether this works in Insiders? I might have fixed the same issue there.

**Comment by 20chan** [comment]
@roblourens I'm sorry but as I mentioned, I can't reproduce this issue anymore.

**Comment by roblourens** [comment]
Are you using a proxy or vpn? I'm not sure why you getting that svg, but in any case, I looked at a similar issue earlier this month and fixed it so that if that request fails, it will not fail the whole marketplace search.
