### ISSUE TITLE
Why we don't have 1 button to expand & collapse all block code ?

### ISSUE THREAD

**Issue by DungVA1** [microsoft/vscode#86639]
I have some files and it's included a lot of functions. Total 5613 lines now, I won't use scroll by mouse to end of file, my hand has been fatigued. So I always collapse the functions I don't working on it, sometimes that functions auto expands, I have to re-collapse them.

I think we need a button to collapse all of blocks. It will very helpful

**Comment by IllusionMH** [comment]
There is <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and `>Fold all` or `>Fold Level 1` commands. They already have shortcuts and you can reassign them if needed.

Does this solve your problem?

**Comment by gjsjohnmurray** [comment]
Also this extension to add context menu items:

https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff

**Comment by RMacfarlane** [comment]
Closing since there are available solutions to this problem as described above.

**Comment by DungVA1** [comment]
> There is Ctrl+Shift+P and `>Fold all` or `>Fold Level 1` commands. They already have shortcuts and you can reassign them if needed.
> 
> Does this solve your problem?

What the shortcut on MacOS ?

**Comment by DungVA1** [comment]
> There is Ctrl+Shift+P and `>Fold all` or `>Fold Level 1` commands. They already have shortcuts and you can reassign them if needed.
> 
> Does this solve your problem?

Thanks. I don't know it since read your comment. It's very helpful for me.
