### ISSUE TITLE
Default formatter not used as default formatter in javascript file

### ISSUE THREAD

**Issue by Meeeeow** [microsoft/vscode#86643]
- VSCode Version: 1.40.2
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Install Extension "esbenp.prettier-vscode"
2. Set `"editor.defaultFormatter": "esbenp.prettier-vscode"` in settings.json
3. Open a new javascript file
4. Execute command "Format document with..." to see result

![image](https://user-images.githubusercontent.com/19658647/70515631-9fd45000-1b70-11ea-935c-2ddcecacc775.png)

Does this issue occur when most extensions are disabled?: Yes
> Only prettier and remote ssh extension was enabled.

Checklist:
- Is there another default formatter in user settings? No.
- Is there multiple default formatter in workspace settings?: No.
- Format on save? Yes.
- Is it work as expected on typescript file? Yes.

**Comment by jrieken** [comment]
Please profile the complete settings file or check if there is language specific override for JavaScript and this setting

**Comment by Meeeeow** [comment]
Not sure why defaultFormatter for javascript was specified in user settings, i don't think i can put this into settings because i never edit settings in plain JSON file mode, maybe related to #71755 ?

I tried "Format Document With..." -> "Configure Default Formatter" before report this issue, but it it says "Unable to write to Folder Settings because editor.defaultFormatter does not support the folder resource scope."

I am confused about why there are language specified defaultFormatter in my user settings...

Maybe setting location could be shown in "Format Document With..." screen? Such as "Foo Formater (Default - User Settings/Language Specified)". At least tell me there are language specified defaultFormatter will override defaultFormatter in settings editor.

![image](https://user-images.githubusercontent.com/19658647/70610056-dc21b200-1c3d-11ea-8d3a-cc6bad8e0fe1.png)
Here is a screenshot of my user settings, and it says this was override by workspace settings, this make me think there is no default formatter in my user settings.

**Comment by jrieken** [comment]
> I am confused about why there are language specified defaultFormatter in my user settings...

This happens when you use "Configure Default Formatter"

**Comment by Meeeeow** [comment]
@jrieken 
As a mention above, i can't use this feature because it report a error to me. I don't understand  why it says "does not support the folder resource scope".

As i understand, it will save a language specified defaultFormatter it i use "Configure Default Formatter" command with a file opened.

This command only appears when a file open, but why it not work at this time? I missed something?...

**Comment by jrieken** [comment]
>  I don't understand why it says "does not support the folder resource scope".

Hard to say? Are you using workspace folders? @sandy081 do you know where this error comes from?

**Comment by sandy081** [comment]
This error is thrown while writing a non-resource setting into workspace folder.
