### ISSUE TITLE
suggestion trigger

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#86644]
https://github.com/microsoft/vscode-python/issues/8790

**Comment by IllusionMH** [comment]
It's already supported by VS Code
see https://code.visualstudio.com/updates/v1_28#_semicolon-as-a-commit-character-for-jsts

LS extension should provide list of commit characters for each item. See `commitCharacters` in https://code.visualstudio.com/api/references/vscode-api#CompletionItem

**Comment by byehack** [comment]
> LS extension should provide list of commit characters for each item. See `commitCharacters` in https://code.visualstudio.com/api/references/vscode-api#CompletionItem


how can i use it in settings.json?
i want support ".", "(", "[", "=" on trigger suggestion for python

**Comment by IllusionMH** [comment]
Python extension should add these characters for appropriate completion items.
For example completions for `import`, `print` shouldn't be committed with `(`, but `raw_input` or `open` should be.

**Comment by byehack** [comment]
> Python extension should add these characters for appropriate completion items.

i said them but they said the vscode should do this.


> For example completions for `import`, `print` shouldn't be committed with `(`, but `raw_input` or `open` should be.

now i cant do these anymore

**Comment by RMacfarlane** [comment]
Closing since the Python extension has reopened the original issue.
