### ISSUE TITLE
Alt+"Right Arrow" doesn't switch me on right hand side tab

### ISSUE THREAD

**Issue by ikonovi** [microsoft/vscode#86648]
It switches me between window tabs on opposite direction.

**Comment by gjsjohnmurray** [comment]
I think the standard keybindings are these:

![image](https://user-images.githubusercontent.com/6726799/70525146-9205d700-1b3e-11ea-9d45-78b2fc4434f6.png)

So if you have 3 tabs open, then click on the rightmost, then the centre, then the leftmost, then type Alt+Left the focus will move rightwards by one tab. This is as designed; you are moving back and forward through your navigation history.
