### ISSUE TITLE
Python snippets not working with Jupyter Notebook (.ipynb) files

### ISSUE THREAD

**Issue by h0rd3** [microsoft/vscode#86646]
Greetings

A new user snippet is working correctly with the .py files and absolutely not working with .ipynb files.

The snippet is below:

`"Create a new figure":{
		"scope": "python",
		"prefix": "nf",
		"body": [
			"plt.figure(figsize=(9, 9))",
			"",
			"$1",
			"",
			"plt.show()"
		]
	}`

I've also tried editing `files.associations` setting so it now looks like this:

`"files.associations": {
      "*.ipynb": "python"
    }`

Moreover, it seems that custom extensions for python are not working with the .ipynb files too (I've got Bracket Pair Colorizer installed and it is not running too).

<img width="398" alt="Screenshot 2019-12-10 at 13 29 18" src="https://user-images.githubusercontent.com/48713543/70521890-17928280-1b51-11ea-845e-a0d6e17dfb51.png">

<img width="236" alt="Screenshot 2019-12-10 at 13 29 39" src="https://user-images.githubusercontent.com/48713543/70521905-21b48100-1b51-11ea-8ffd-b461486e5fe5.png">

**Comment by jrieken** [comment]
What does the language indicator in the lower right say? Can try F1 > Insert Snippet and check what snippets are offered then

**Comment by h0rd3** [comment]
It basically says nothing, there is none of it.

<img width="1440" alt="Screenshot 2019-12-10 at 14 08 18" src="https://user-images.githubusercontent.com/48713543/70524576-86260f00-1b56-11ea-9dba-02d80a095bd0.png">


It actually doesn't have any insert snippet there too.

<img width="745" alt="Screenshot 2019-12-10 at 14 08 43" src="https://user-images.githubusercontent.com/48713543/70524635-abb31880-1b56-11ea-981d-b1fc5fbcc409.png">

**Comment by jrieken** [comment]
oh, this is from within the notebook and not from a "normal" editor?

**Comment by h0rd3** [comment]
It actually happens like that: I am clicking the .ipynb file, it first (for a couple of second) opens as a python file with the cells (see the image) and that it closes for the notebook itself. The process is automatic and I believe I have not ever fixed the settings for it so I feel that is just VSC's feature?
<img width="1098" alt="Screenshot 2019-12-10 at 14 18 03" src="https://user-images.githubusercontent.com/48713543/70525288-0a2cc680-1b58-11ea-9369-0af520b63724.png">

**Comment by jrieken** [comment]
Understood - this is an issue with python extension and something cannot fix on our side
