### ISSUE TITLE
Python extension: Pandas Import csv fail in within a Jupyter notebook when file does not contain a full relative path

### ISSUE THREAD

**Issue by andreamoro** [microsoft/vscode#86649]
- VSCode Version: 1.40.2
- OS Version: 10.14.6 (18G1012

Steps to Reproduce:

1. Import the Pandas
2. Create a dummy csv file in the same folder where the project is
3. Use the read_csv fuction to import the file as pd.read_csv('./file.csv')

Does this issue occur when all extensions are disabled?: Yes

The above works fine in a Jupyter notebook and Lab.

**Comment by RMacfarlane** [comment]
Please reopen on the Python extension

**Comment by andreamoro** [comment]
The Python extension has been installed freshly this morning after I've seen a video which was mentioning the Jupyter notebook support as a new feature introduced in November.

I have of course opened the module with that extension. In saying all the extension disabled, I meant anything else other than this.

**Comment by RMacfarlane** [comment]
Since this is a problem with the Python extension, please open the issue there: https://github.com/Microsoft/vscode-python
