### ISSUE TITLE
Opening search box clobbers primary selection

### ISSUE THREAD

**Issue by LinAGKar** [microsoft/vscode#86645]
Issue Type: <b>Bug</b>

On Linux:
1. Highlight something with the mouse, to put it into primary selection
2. Put the cursor on a word in vscode
3. Press ctrl+f
This word the cursor is in will automatically be filled into the search box. However, when it does this, it also puts this word into primary selection, replacing whatever was there prevously.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.12.14-lp151.28.32-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.84GB (20.90GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
vscode-markdownlint|Dav|0.32.0
githistory|don|0.4.11
xml|Dot|2.5.0
gitlens|eam|10.2.0
language-cython|guy|0.0.6
tab-indent-space-align|j-z|0.0.3
bash-ide-vscode|mad|1.3.3
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
markdown-preview-enhanced|shd|0.5.0

</details>

**Comment by rebornix** [comment]
@LinAGKar do you have `editor.find.globalFindClipboard` turned on?

**Comment by LinAGKar** [comment]
I don't seem to have such a setting.

**Comment by rebornix** [comment]
Can you run command "Preferences: Open Settings (UI)" from command palette  and paste `editor.find.globalFindClipboard` in the search box and see if you can see the setting?

**Comment by LinAGKar** [comment]
I did, and it's not there. According to [this](https://github.com/microsoft/vscode/commit/b5ef98e6015d201104df4798d6859afdd02df958), it MacOS-specific.

**Comment by rebornix** [comment]
I think this is the system behavior, when we feed the query into the find input box, we select the search query to allow you easily update it if you want, however the system then puts into the primary selection.

**Comment by LinAGKar** [comment]
Are you just going to deliberately keep this broken? Clobbering the primary selection just by opening a box is definitely not "system behavior", it's a bug in VSCode (or Electron). Updating primary selection is normally only done when something is highlighted by the user, not when something is highlighted automatically.

**Comment by LinAGKar** [comment]
Furthermore, searching also clobbers primary selection, as the primary selection is filled with the search result.

**Comment by LinAGKar** [comment]
I opened an upstream issue for this at https://github.com/electron/electron/issues/26563, but they want a small test case for it.
