### ISSUE TITLE
Impossible to copy extension description

### ISSUE THREAD

**Issue by pavelloz** [microsoft/vscode#86658]
A lot of extensions have configuration code. It is extremely annoying that since some version ago we are unable to copy anything from that pane, mouse or keyboard.

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

Steps to reproduce:

* Go to extension description
* Try to copy something

Video: https://youtu.be/lhMmpawfTQY

**Comment by gjsjohnmurray** [comment]
See #65310

I'm surprised that you can't copy using the keyboard. What key sequence are you using? What command(s) does your Keyboard Shortcuts page show that bound to?

**Comment by pavelloz** [comment]
Im using the usual cmd+c which works in other apps.
And cmd+c also works in the editor mode, terminal mode - so i think its not my key bindings customization.
