### ISSUE TITLE
Error creating issue

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#86657]
Jira and Bitbucket (Official)

Issue Type: <b>Bug</b>

Important hints: data was not an array.
I have no idea what is meant with 'data'

Extension version: 2.2.0
VS Code version: Code - Insiders 1.41.0-insider (bef029a9d21904c0085c4e8ef1335d9c33a28fa4, 2019-12-09T15:40:24.842Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_28765037|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
@bm-stschneider an issue with VS Code's Issue Reporter (#73515) causes it to raise some extension-related issue reports here rather than in the extension's own project. This looks like one of those events. If so, please post your issue in the correct place (see extension's doc for a link) and close this one.
