### ISSUE TITLE
Option 'Switch to ... for Multi-Cursor' doesn't reflect the appropriate option in settings.json

### ISSUE THREAD

**Issue by Nutznieser** [microsoft/vscode#86654]
The option `Switch to ... for Multi-Cursor` in the `Selection` menu of the menubar doesn't reflect the appropriate option `editor.multiCursorModifier` in settings.json.

Version: 1.40.2 (user setup)
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:
1. Go to the menu `Selection` and switch the option `Switch to ... for Multi-Cursor` to have `Switch to Alt+Click for Multi-Cursor`
2. Now the option is stored in the settings.json as `"editor.multiCursorModifier": "ctrlCmd"`
3. Close vscode and open vscode again.
5. In the `Selection` menu now you have `Switch to Ctrl+Click for Multi-Cursor` again althoug it must be `Switch to Alt+Click for Multi-Cursor` now.

It seems at starting vscode the menu option doesn't initialize the proper current state of the settings.json for this option.

**Comment by sbatten** [comment]
fyi @alexdima

**Comment by alexdima** [comment]
Thank you @sbatten
