### ISSUE TITLE
Different Settings shortcut for different input source

### ISSUE THREAD

**Issue by hsinyinfu** [microsoft/vscode#86652]
### Version Information
- VSCode Version: 1.40.2
- OS Version: macOS Mojave 10.14.6

### Steps to Reproduce:
The following steps should be reproduced on macOS.
1. Go to [ System Preferences ] -> [ Keyboard ] -> [ Input Sources ] -> add [ Zhuyin ] in [ Chinese, Traditional ] -> set [ Zhuyin ] as default -> Toggle off the [ Use the 中/英 key to switch to and from ABC] below
2. Switch your input source to  [ Zhuyin ]
3. Press [ Caps Lock ] on your keyboard and make sure the light of the key is on ( now you can press any key and you will find that you are typing English in small case instead of traditional chinese)
4. Open the VS code
5. Click [ Code ] -> [ Preferences ]
Now the shortcut for [ Settings ] is [ ⌃⌥⌘ㄝ ] instead of [ ⌘, ].
However, when you switch your input source to English, the shortcut is [ ⌘, ].
I think it should always be [ ⌘, ] as shortcut for Settings no matter what input source now it is.

- Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Currently VS Code relies on reading active keyboard layout to work properly.
