### ISSUE TITLE
Cannot run vscode on Centos 7.

### ISSUE THREAD

**Issue by z00420691** [microsoft/vscode#86656]
- VSCode Version: 1.40.1
- OS Version:centos 7

Steps to Reproduce:

1. Install vscode via rpm
2. Run code & on terminal with common user & no log info shows.

**Comment by RMacfarlane** [comment]
@z00420691 What is the result of running `code`? Does the window still open? Can you try `code --verbose`? Have you been able to run other versions of VSCode?
