### ISSUE TITLE
Allow order to be specified in context view/item/context menu

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#86651]
When adding commands to a view context menu it appears to present them in alphabetical order.
It would be nice to be able to specify the order in a similar way to how it can be specified in the "group" argument.

At the moment, if I add "Move to Top" and "Move to Bottom",  they appear in an illogical order.

**Comment by gjsjohnmurray** [comment]
/duplicate

Already possible - https://github.com/microsoft/vscode/issues/85838#issuecomment-560293130

**Comment by Gruntfuggly** [comment]
Thanks! I didn't realise I could add my own groups - I was under the impression that adding the group attribute made the item an inline button, but I can see now that is just a special case when using "group":"inline".
