### ISSUE TITLE
Git : suggest stashing changes when switching branch

### ISSUE THREAD

**Issue by aymericbouzy** [microsoft/vscode#86668]
On GitHub Desktop, when you switch branch, if you have uncommited changes, a prompt will suggest to stash them. When you switch back to the branch, you can restore these uncommited changes in one click. That means that switching branch is never an effort anymore : 

* You need to quickly check something on the master branch? Just switch, your current state will be restored when you come back.
* You're interrupted by a colleague asking for a review? Just switch
* There is a critical bug? Just switch

For this reason, I'm still using GitHub Desktop alongside VS Code. But VS Code is so feature rich, it's become a pain not being able to do the same right inside my editor. I haven't found an extension that does that yet.
<img width="1072" alt="Screenshot 2019-12-10 at 15 44 25" src="https://user-images.githubusercontent.com/8168981/70539447-0bfc8700-1b64-11ea-88b7-ecaa78341af6.png">
<img width="1072" alt="Screenshot 2019-12-10 at 15 44 35" src="https://user-images.githubusercontent.com/8168981/70539449-0bfc8700-1b64-11ea-8929-5d55dc28638e.png">
<img width="1072" alt="Screenshot 2019-12-10 at 15 44 49" src="https://user-images.githubusercontent.com/8168981/70539450-0c951d80-1b64-11ea-9c2a-9f612d4deb7d.png">

**Comment by Thaina** [comment]
+1

Also I would like to suggest that `git.autoStash` setting should enable this feature, stashing all change and pop the last stash on switched back
