### ISSUE TITLE
very tired for make scroll on tab

### ISSUE THREAD

**Issue by lopez2041** [microsoft/vscode#86666]
Issue Type: <b>Feature Request</b>

when i have many tab open , some are hide, and it is dificult make scroll, also the scroll bar is very thin, please do every tab visible ever, please!

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
Did you try `"workbench.editor.tabSizing": "shrink"` ?
