### ISSUE TITLE
Tree Guide Indents not showing in latest Insiders (1.41)

### ISSUE THREAD

**Issue by DeltaRazero** [microsoft/vscode#86662]
Tree guide indents will not show up at all in the latest insider build, regardless of always enabled or show on hover.

```
Version: 1.41.0-insider
Commit: bef029a9d21904c0085c4e8ef1335d9c33a28fa4
Date: 2019-12-09T15:42:51.762Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Looks like elements are there, but have `border-left: 1px solid transparent;`

**Comment by gjsjohnmurray** [comment]
/confirm this is a regression in 1.41.

@sbatten should this be tagged as a candidate for fixing before release?

**Comment by isidorn** [comment]
I am investigating when this broke exactly..
@DeltaRazero if you know that it worked with some previous insiders do tell me.

**Comment by isidorn** [comment]
@IllusionMH You are correct that the `trasnparent` color is the issue [here](https://github.com/Microsoft/vscode/blob/63fd0dbc8b49bd5fd493e378615950d69665f31e/src/vs/base/browser/ui/tree/media/tree.css#L29). However we always had that code. I believe this indent guides can be styled, and that styling got broke. Investigating more

fyi @misolori

**Comment by isidorn** [comment]
I am suspecting this commit https://github.com/microsoft/vscode/commit/75a778d9217f0bb815e4418dd1da4c6bb84ef1c0

Investingating more...

**Comment by isidorn** [comment]
Ok found a fix, creating a PR.
