### ISSUE TITLE
API: allow case insensitive find files via vscode.workspace.findFiles()

### ISSUE THREAD

**Issue by zabel-xyz** [Microsoft/vscode#8666]
**Steps to Reproduce:**
a file with name "Unit.pas"

```
filename = 'unit';
vscode.workspace.findFiles('**/' + filename + '.*', '')
```

**Problem:** 
file *Unit.pas" will not be found, because the case doesn't match.
(Windows is a case-insensitive files system)

_VSCode Version: 1.2.1 / OS Version: Windows 10_

**Comment by jrieken** [comment]
It just delegates to the [search service](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadWorkspace.ts#L40)

**Comment by bpasero** [comment]
After investigation: searches from extensions never fill in `filePattern` but rather `includePattern` and since our glob is case sensitive, this is a valid request.

Refs: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadWorkspace.ts#L50

**Comment by akshita31** [comment]
Any update on this one ?

**Comment by roblourens** [comment]
Dupe of https://github.com/Microsoft/vscode/issues/10633
