### ISSUE TITLE
TypeScript fails to load w/ git diff view

### ISSUE THREAD

**Issue by tommck** [microsoft/vscode#86660]
Issue Type: <b>Bug</b>

Whenever I'm viewing a diff of TypeScript code, the TS extension fails and I get the "failed 5 times message" repeatedly.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (6.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.1
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
javascript-ejs-support|Dig|1.1.3
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
prettier-vscode|esb|3.11.0
vscode-peacock|joh|3.2.0
git-graph|mhu|1.19.1
vscode-azureappservice|ms-|0.16.2
azure-account|ms-|0.8.7
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
angular-console|nrw|9.1.1
sort-lines|Tyr|1.9.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by tommck** [comment]
I need to get my corporate overlords to white list the Insiders version of the app in order for it to be usable at all (otherwise there's a process constantly scanning every file access it makes, etc).  So it will take a bit to test this

**Comment by mjbvz** [comment]
Note that VS code 1.41 will also be out in the next few days. That has the potential fixes that are in the current insiders build

**Comment by tommck** [comment]
One way or another, I'll let you know soon :)

**Comment by mjbvz** [comment]
@tommck 1.41 is now out. Can you please test this once you have a chance

**Comment by tommck** [comment]
@mjbvz I believe it is fixed now. I have not experienced it.. Don't want to leave you hanging.  I'll comment again here if it comes back up
