### ISSUE TITLE
Find/Replace sometimes replace the whole file

### ISSUE THREAD

**Issue by hawezo** [microsoft/vscode#86664]
When using find/replace, sometimes a file get replaced with the content of another place, for no apparent reason. See details below.

**Version**
- VSCode Version: 1.40.2
- OS Version: W10.0.17763

![](https://i.imgur.com/FkcYGJu.png)

**Steps to Reproduce**

1. Use find to find all occurences of something, without option.
2. Replace it with anything.
3. Sometimes, the whole file is replaced by another file.

It seems to happen only with extensions enabled. I tried 10 times with extensions, it happened 6 out of 10 times. Without extension, it didn't happen at all out of 10 another times.

Note that the 6 times a file has been replaced, it has been replaced with the same file.

**Screenshots**

My find/replace, all options disabled:

![](https://i.imgur.com/QYqszaP.png)

The one file that gets replaced:

![](https://i.imgur.com/IXCXFR7.png)

Note that the first time it happened, it wasn't the same. It was another find/replace query. I tried the same find/replace query for debugging purposes, and this one file was replaced 6/10 times.

Here are my extensions:

<details>
<summary>Extensions</summary>

<pre>
$ code --list-extensions
amiralizadeh9480.laravel-extra-intellisense
austenc.tailwind-docs
bmewburn.vscode-intelephense-client
bradlc.vscode-tailwindcss
calebporzio.better-phpunit
cjhowe7.laravel-blade
cpylua.language-postcss
damianbal.vs-phpclassgen
daylerees.rainglow
dbaeumer.vscode-eslint
DotJoshJohnson.xml
dunstontc.dark-plus-syntax
eamodio.gitlens
ecmel.vscode-html-css
emilast.LogFileHighlighter
esbenp.prettier-vscode
geequlim.godot-tools
heybourn.headwind
icrawl.discord-vscode
joelday.docthis
junstyle.php-cs-fixer
Kasik96.latte
MehediDracula.php-constructor
MehediDracula.php-namespace-resolver
mikestead.dotenv
mrmlnc.vscode-apache
naumovs.color-highlight
neilbrayfield.php-docblocker
octref.vetur
prograhammer.tslint-vue
psioniq.psi-header
ritwickdey.LiveServer
ryannaddy.laravel-artisan
Shan.code-settings-sync
whatwedo.twig
</pre>
</details>

I'm going to do some more debugging by manually disabling them one by one and testing.

**Comment by KHMANJUNATH** [comment]
I think you have searched for a directory by typing app/support\. Hence the file present in one directory is getting replaced by the file present in another directory

**Comment by hawezo** [comment]
I'm sorry, I'm not sure to understand what you're saying. I'm not searching for a directory, I'm using the Search & Replace functionality. And the file replacement is random and doesn't really make sense.

**Comment by roblourens** [comment]
That's very weird. Was that file open when you did the replace? Thanks for anything you can do to narrow down the problem.
