### ISSUE TITLE
VS Code snippets do not work with Jupyter (.ipynb) files

### ISSUE THREAD

**Issue by hannibal90** [microsoft/vscode#86670]
I have started using VS Code with my Jupyter notebook files. However I have noticed that my existing Python snippets do not work within VS Code's implementation of Jupyter. Initially I thought it was because my snippets are specifically for .py files, but even after adding my snippet code to the global snippet settings JSON I still can't use them in any .ipynb files. They work with all other file types.

- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.17763

Here is the code I am adding to my global.code-snippets json file.

```
{
	"Python common imports": {
		"prefix": "imports",
		"body": [
			"import pandas as pd",
			"import numpy as np",
			"import matplotlib.pyplot as plt",
			"import statsmodels.api as sm"
		],
		"description": "Imports common python modules"
	}
}
```

**Comment by rebornix** [comment]
@hannibal90 we don't have native notebook support yet in VS Code, I suppose you are using Python extension which opens the notebook in a webview? If so, right now they are using a standalone monaco editor in the webview, which doesn't have access to the snippet service in VS Code.

**Comment by hannibal90** [comment]
Yes, I am using the Python extension. I believe it is using monaco:

![VSCode Jupyter Snippet #86670](https://user-images.githubusercontent.com/34248668/70551385-718d4b00-1b45-11ea-9059-a8fad6309825.PNG)

Do you know if there are any plans to add this in the future?
