### ISSUE TITLE
Cursor position is allowed to sit between character and combining marks

### ISSUE THREAD

**Issue by PandaSandStudio** [microsoft/vscode#86673]
monaco-editor version: Latest (one used on documentation)
Browser: Latest version of chrome
Device: Chromebook
Steps or JS usage snippet reproducing the issue:
If you go onto the documentation website and paste in "Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!͖̬̰̙̗̿̋ͥͥ̂ͣ̐́́͜͞'" then even though it looks like 6-ish characters when you select the end of the part you pasted and hold the left arrow (moving the cursor to the left) it stops every so often. There are also issues when you paste a unicode character / emoji into the editor and type -- it replaces some text and randomly changes other characters. Also with unicode characters word wrapping doesnt work properly.
(reference -> https://mathiasbynens.be/notes/javascript-unicode)

**Comment by alexdima** [comment]
This has been fixed with 3f1a2f690ae5b0dc192ef1a233a7c1c9cb8360ff
