### ISSUE TITLE
Syntax colouring

### ISSUE THREAD

**Issue by Spinofis** [microsoft/vscode#86677]
Issue Type: <b>Bug</b>

Syntax coloring for type script doesnt work.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.73GB free)|
|Process Argv|--folder-uri file:///c%3A/Praca/MMP/spa-gui|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular2|joh|8.2.0

</details>

**Comment by RMacfarlane** [comment]
@Spinofis Can you please provide some example code? I'm not able to reproduce this.

**Comment by Spinofis** [comment]
Syntax has only two colours, white and blue. There was more of them.

![image](https://user-images.githubusercontent.com/26433062/70557009-48d77680-1b82-11ea-9ce2-8e20577355a4.png)

**Comment by RMacfarlane** [comment]
@Spinofis Can you check what theme you're using? The `Dark (Visual Studio)` theme looks similar to this, whereas `Dark+ (default dark)` has more colors

**Comment by Spinofis** [comment]
its dark+

**Comment by RMacfarlane** [comment]
Hmm, I see the exact same syntax coloring as in your screenshot with `Dark (Visual Studio)`:
![syntax_highlighting](https://user-images.githubusercontent.com/3672607/70575816-1fa3ef80-1b5c-11ea-8c10-c61e473980ac.gif)
