### ISSUE TITLE
vscode.workspace.openTextDocument should open in the active editor

### ISSUE THREAD

**Issue by zabel-xyz** [Microsoft/vscode#8667]
If we have two editors open side by side, 
the method  _vscode.workspace.openTextDocument ()_ always open file in the left editor instead of the active editor.

It would also be nice to choose (optionnaly) to open in a new editor (like ctrl + click)

_VSCode Version: 1.2.1 / OS Version: Windows 10_

**Comment by jrieken** [comment]
The ['showTextDocument`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3175) allows you to set the `column` in which to open. The column of the [active](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3136) is exposed via [TextEditor#viewColumn](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L904)

**Comment by zabel-xyz** [comment]
It's work well, thank you.
