### ISSUE TITLE
Markdown headers are not rendered when more than one header is in a given cell 

### ISSUE THREAD

**Issue by andreamoro** [microsoft/vscode#86685]
- VSCode Version: 1.40.2
- OS Version:  10.14.6 (18G1012

Steps to Reproduce:

1. Add the following content in a cell

```
## Header 1

### Header 2
```

2. Change the content to Markdown
3. Render the cell

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please clarify what cell to you mean?
If it's cell in Jupyter notebook then this issue should be reported in Python extension repo.

**Comment by andreamoro** [comment]
@IllusionMH a Jupyter notebook is made by "cells", which kind of isolate codes. Cells can also host markdown content.
Please see here for the reference
https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#structure-of-a-notebook-document

**Comment by IllusionMH** [comment]
/causedByExtension

Please fill in this issue against Python extension: https://github.com/microsoft/vscode-python/issues
