### ISSUE TITLE
Indicator should show even before contributed treeview is loaded

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86686]
Version: 1.41.0-insider
Commit: bef029a9d21904c0085c4e8ef1335d9c33a28fa4
Date: 2019-12-09T15:40:24.842Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

---

- Install GH PR extension
- Reload window
- Click onto it
- I expect the indicator to focus on it before it even loads, but currently it doesn't even show the indicator after loading

![bug](https://user-images.githubusercontent.com/4033249/70553941-fb7ee900-1b30-11ea-8e97-8bc7a5abdd99.gif)

**Comment by IllusionMH** [comment]
Looks like wrong gif

**Comment by octref** [comment]
@IllusionMH You are absolutely right! Sorry 😅

**Comment by sandy081** [comment]
@misolori Assigning to you as you are aware of these indicators. Let me know if there is something I have to do here.

**Comment by misolori** [comment]
@sandy081 the indicator only shows up after the extension viewlet is in focus. It appears that the issue here is that the extensions loses focus when the custom viewlet is loaded, so we should place focus to the viewlet after it's loaded like the rest of our views. Can you look into adding this?

**Comment by sandy081** [comment]
Thanks @misolori for investigating. Assigning to @alexr00 for custom views.

**Comment by alexr00** [comment]
@sandy081 I think this needs to be solved at the viewlet level, not the view level.
In the most simple case, the contributed _viewlet_ is empty. The indicator will not show unless you click in the viewlet. The custom view  doesn't know that the viewlet it's in is empty, but the viewlet does.
Even the explorer still has an issue with this when there are no views. The proper white indicator doesn't show until I click in the empty viewlet:
![sidebar-indicator](https://user-images.githubusercontent.com/38270282/72059372-2c8a3f00-32d2-11ea-99b5-d7da74d20feb.gif)

**Comment by alexr00** [comment]
Fixed for custom tree views, but the problem still exists for empty viewlets.

**Comment by alexr00** [comment]
New bug for empty viewlets so I can close this for testing: https://github.com/microsoft/vscode/issues/88356
