### ISSUE TITLE
QA tester

### ISSUE THREAD

**Issue by joseramos1131** [microsoft/vscode#86688]
Issue Type: <b>Bug</b>

Unable to do a git pull command ....i get this error

awsprocesscreds.saml.SAMLError: Received a non-200 response (401) when  making a request

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0

</details>

**Comment by RMacfarlane** [comment]
@joseramos1131 This doesn't sound like a problem with VSCode itself. Can you check to see if you see the same error when you run the command in a terminal outside of VSCode? It sounds like you are not authenticated.
