### ISSUE TITLE
terminal.external.windowsExec Cannot be changed to powershell

### ISSUE THREAD

**Issue by OmriBromberg** [Microsoft/vscode#8668]
- VSCode Version: 1.2.1
- OS Version: windows 10

Steps to Reproduce:

1. change in settings terminal.external.windowsExec from default "cmd" to "powershell"
2. debug a node.js app with "externalConsole": true in the launch.json
result : it opens up the default cmd instead of powershell
although the integrated terminal works fine when I try to launch powershell.

EDIT: when I try to open a new command prompt through ctrl shift c it opens powershell.
Is this behavior intended?

**Comment by Tyriar** [comment]
@weinand isn't this to do with debug? Does the debug stuff rely on parts/execution?

**Comment by weinand** [comment]
@Tyriar no, the debug console is an implementation detail of debug adapters. It does not rely on anything VS Code related.

**Comment by Tyriar** [comment]
So this issue is related to 3 then, as it's talking about the `externalConsole` setting here? https://github.com/Microsoft/vscode/blob/c5429332d4ac326a94a6c5e87fffefcb14d10e84/src/vs/workbench/parts/debug/common/debug.ts#L214

**Comment by weinand** [comment]
This will be supported in the September release (and is already in the current Insiders).
