### ISSUE TITLE
Let user define custom "suggestions" for IntelliSense

### ISSUE THREAD

**Issue by duckimann** [microsoft/vscode#86683]
I've created a [suggestion file](https://github.com/duckimann/IntelliSense_Hints_Chrome/blob/master/index.d.ts) for who's writing Chrome Extension, but I couldn't add it into IntelliSense (See how I add it in file "install.bat").

So I just want to a feature that lets the user add custom suggestions into IntelliSense 'cause there are none of library/syntax suggestions for those API.

**Comment by IllusionMH** [comment]
If you mean custom suggestions into IntelliSense based on `.d.ts` files than users can add your file into their repo and it will be used automatically (if it won't be in `exclude`).
Probably it can be achieved with release as npm package and `typeRoots` (see [docs](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types_))

So it looks like it can be solved with proper `tsconfig.json`/`jsconfig.json` and don't require special handling from VS Code.

---
On the side note: looks like there already are [typings for Chrome extension API](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts) in DefinitelyTyped which can be installed as `@types/chrome`.
Would be great if you could contribute improvements there!
