### ISSUE TITLE
Font rendering issue persists on Windows (1.41.0-insider Build)

### ISSUE THREAD

**Issue by pavangayakwad** [microsoft/vscode#86691]
Issue Type: <b>Bug</b>

Tried insider build and the Font rendering issue still persist. Please check. 

![image](https://user-images.githubusercontent.com/1834890/70565303-cbc6f400-1bb7-11ea-95fb-ebcb9b0e705d.png)

Version: 1.41.0-insider (user setup)
Commit: 455d8f73cd7c73285fba70ab039a26279f19bb57
Date: 2019-12-10T12:59:54.138Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

VS Code version: Code - Insiders 1.41.0-insider (455d8f73cd7c73285fba70ab039a26279f19bb57, 2019-12-10T12:59:54.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (5.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
Can you try launching from commandline with `code-insiders.exe --disable-gpu` ?

The whole of editor area is affected along with the about panel, seems more of an hw acceleration issue.

/cc @bpasero

**Comment by pavangayakwad** [comment]
Yes, tried as you instructed. No luck.

![image](https://user-images.githubusercontent.com/1834890/70599516-4d983b00-1c13-11ea-9301-6fd87f6eff0a.png)

**Comment by pavangayakwad** [comment]
@deepak1556 regarding "About" panel comment of yours. It look blurred because of the image sizing done by the Github comment section. Request you to open my screen capture image in new tab (with "open image in new tab" option from browser context menu) and check, it then shows my actual screen capture resolution.

**Comment by deepak1556** [comment]
Can you try the exploration build https://az764295.vo.msecnd.net/exploration/22c3db00ec057fecf0144c4c7f8c6bc6cb60e5d6/VSCode-win32-x64-1.41.0-exploration.zip and report back how it looks ?


What is the value of `editor.disableLayerHinting` setting in your editor ?

**Comment by pavangayakwad** [comment]
Ok, Please find the exploration build run on my windows system

- _editor.disableLayerHinting_ is not present/configured.
- Font rending problem persists.

![image](https://user-images.githubusercontent.com/1834890/70607205-023a5880-1c24-11ea-9440-ed9c4b8334cb.png)

**Comment by deepak1556** [comment]
Thanks, one last thing can you remove the custom font `Cascadia Code` and see how it looks with the default ones ?

**Comment by pavangayakwad** [comment]
Sure, here it is

![Annotation 2019-12-11 160816](https://user-images.githubusercontent.com/1834890/70616490-914f6c80-1c34-11ea-83b8-63c35026b2f9.jpg)

**Comment by pavangayakwad** [comment]
This is from my Linux machine. Just to let you know this should be the expected output on Windows.

![image](https://user-images.githubusercontent.com/1834890/70616607-dbd0e900-1c34-11ea-8524-68814031751f.png)

**Comment by deepak1556** [comment]
Can you list the editor settings from this machine ?

**Comment by pavangayakwad** [comment]
I assumed your "this machine" referring to my Linux machine.

![image](https://user-images.githubusercontent.com/1834890/70617275-3d458780-1c36-11ea-9187-859a5a6e14b1.png)

**Comment by deepak1556** [comment]
Yes I meant the linux editor settings, thanks. Can you remove the `workbench.fontAliased` setting on windows ? although it will be surprising if `-webkit-font-smoothing` css rules made an effect on windows.

**Comment by pavangayakwad** [comment]
Ok here it is: 

without Cascadia font
![image](https://user-images.githubusercontent.com/1834890/70618285-71ba4300-1c38-11ea-8be2-83efa0061ec9.png)

with Cascadia Font (I prefer this to be fixed)
![image](https://user-images.githubusercontent.com/1834890/70618346-93b3c580-1c38-11ea-9657-66552eee00fc.png)

**Comment by csttsn** [comment]
Are you sure that ClearType is not turned off on your system?

**Comment by deepak1556** [comment]
Is this still an issue with latest stable ?
