### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by Rakesh-rules** [microsoft/vscode#86699]
Issue Type: <b>Bug</b>

The terminal is showing nothing except the cursor in ubuntu

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.15.0-72-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G630 @ 2.70GHz (2 x 2662)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 2|
|Memory (System)|3.79GB (0.32GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
kite|kit|0.101.0
python|ms-|2019.11.50794

</details>

**Comment by StoyanIvanovI** [comment]
I can reproduce the same terminal behaviour on Centos7 kernel 3.10.0-1062.9.1.el7.x86_64 and the same version of VS Code 1.40.2.

**Comment by StoyanIvanovI** [comment]
I managed to fix the issue with the issue mentioned in #76542. In short, set `"terminal.integrated.inheritEnv": false` to it's default value - true and it will work again.

**Comment by BlurryLight** [comment]
@StoyanIvanovI 
You saved my day

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.
