### ISSUE TITLE
VSC e PUSH

### ISSUE THREAD

**Issue by gmsetta** [microsoft/vscode#86694]
Issue Type: <b>Bug</b>

Não volto mais a utilizar. Msg de erro do PHP aparece toda hora como não instalado, mas não quero instalar o PHP. Extensão PUSH instala mas é impossível saber onde ir depois de instalada para funcionar. Ridículo.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pt-BR|MS-|1.40.2
push|njp|0.7.21

</details>

**Comment by RMacfarlane** [comment]
@gmsetta It sounds like this issue report is for multiple problems - can you please clarify what the bug is? Are there steps to reproduce your problem? What did you expect to happen and what actually happened?

If this is an issue with configuring the push extension, please open it on that extension: https://github.com/njpanderson/push/issues
