### ISSUE TITLE
Hint level diagnostics tagged as deprecated only show strikeout on first few characters

### ISSUE THREAD

**Issue by bmewburn** [microsoft/vscode#86692]
As shown in the screenshots. If a hint level diagnostic is tagged as deprecated only the first few characters are struck out. If the diagnostic is at information level then the full range is struck out.

As a comparison, hint level diagnostics tagged as unnecessary are shown too which fades the full range.

![Screenshot from 2019-12-11 07-29-30](https://user-images.githubusercontent.com/5885195/70567012-39d7df00-1be9-11ea-8402-bac7ec9aa055.png)

![Screenshot from 2019-12-11 07-30-54](https://user-images.githubusercontent.com/5885195/70567020-3e03fc80-1be9-11ea-8d81-5e51c7aa1f05.png)

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.0-6-amd64

Does this issue occur when all extensions are disabled?: 
Needs an extension enabled that provides deprecated diagnostics.

**Comment by jrieken** [comment]
Yes - that is somewhat how we have designed this. What is the use case for this?

**Comment by bmewburn** [comment]
@jrieken no particular use case other than consistency. I'd expect it to strikethrough the whole range like unnecessary fades the whole range.

**Comment by jrieken** [comment]
Fair feedback - I believe today we use a single editor decoration and for level-hint we crop that to just a few character. With this combination of tags and sev we would need to add at least two decorations...

**Comment by jrieken** [comment]
code pointer: https://github.com/microsoft/vscode/blob/573df438dbb97795ea6ce3c242c27f0dcd8b43dc/src/vs/editor/common/services/markerDecorationsServiceImpl.ts#L189
