### ISSUE TITLE
Keyboard layout is not detected correctly

### ISSUE THREAD

**Issue by turion** [microsoft/vscode#86695]
- VSCode Version: 1.40.0
- OS Version: NixOS unstable, KDE

I'm using a special German keyboard layout called Neo. I have two machines, both identical setup and configuration. On one of them, everything works just fine. On the other, all keyboard shortcuts are interpreted as QWERTZ, while normal typing and editing is correctly in Neo.

I tried workarounds from e.g. #23690, closed, restarted, deleted all config files, unfortunately to no avail.

Can I somehow manually change the keyboard layout that VSCode has incorrectly detected?

Does this issue occur when all extensions are disabled?: Yes

**Comment by turion** [comment]
If I do `Developer: Inspect Key Mappings (JSON)`, I get:
```
{
	"layout": {
		"model": "macbook78",
		"layout": "de,de",
		"variant": ",neo",
		"options": "terminate:ctrl_alt_bksp",
		"rules": "evdev"
	}
...
```
So it seems like it actually realised what my layout is...?

**Comment by turion** [comment]
This workaround helped me somewhat: https://github.com/microsoft/vscode/issues/24043#issuecomment-292334048

**Comment by turion** [comment]
Note that I have two keyboard layouts configured in KDE: Neo is the currently active one (and was active when starting vscode), but I have QWERTZ as a backup.

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/microsoft/vscode/issues/24043#issuecomment-292334048
