### ISSUE TITLE
VS Code Very Slow Startup

### ISSUE THREAD

**Issue by Harry09** [microsoft/vscode#86698]
Issue Type: <b>Performance Issue</b>

Hi,

Today I noticed that my VS Code was starting like 10 times slower, I turned off all extensions but nothing really change.

Here is Startup Performance https://gist.github.com/Harry09/74fdb99f681d0d673a4fa18bbcfcf3c3

I reinstalled VS Code by removing all files (cache also) but it also nothing changed.

Also windows like extension's info or process explorer takes like 5 second to load.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (5.06GB free)|
|Process Argv|--folder-uri file:///c%3A/dev/studia/PP1/Dante|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	 24480	code main
    0	    14	   452	   electron-crash-reporter
    0	   162	  7772	   gpu-process
    0	   192	 14360	   window (Startup Performance - Dante - Visual Studio Code)
    0	   115	 11632	     extensionHost
    0	    24	 14836	       c:\Users\piotr\.vscode\extensions\ms-vscode.cpptools-0.26.2\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    11	  5184	         console-window-host (Windows internal process)
    0	    12	  8932	         "c:\Users\piotr\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 14836 1
    0	     6	 13424	     console-window-host (Windows internal process)
    0	    34	 21760	     searchService
    0	    11	 22896	     watcherService 
    0	    11	 15416	       console-window-host (Windows internal process)
    0	    91	 23016	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    67	 18360	   window (Issue Reporter)
    0	    71	 23128	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Startup Performance - Dante - Visual Studio Code)
|    Folder (Dante): 97 files
|      File types: c(71) exe(14)
|      Conf files:;
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.32.0
auto-rename-tag|for|0.1.1
rest-client|hum|0.23.0
git-graph|mhu|1.19.1
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
csharp|ms-|1.21.8
vetur|oct|0.22.6
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.2
java|red|0.54.2
multi-command|ryu|1.3.0
code-settings-sync|Sha|3.4.3
ayu|tea|0.18.0
autocomplate-shell|tru|0.1.1
cmake|twx|0.0.17
errorlens|use|2.8.1
vscode-vtools|ven|1.0.6
vscodeintellicode|Vis|1.2.0
vscode-java-dependency|vsc|0.6.0
vscode-wakatime|Wak|2.2.1

(3 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by Harry09** [comment]
[prof-dc53.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/3950074/prof-dc53.renderer.cpuprofile.txt)
[prof-dc53.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/3950075/prof-dc53.extHost.cpuprofile.txt)
[prof-dc53.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/3950076/prof-dc53.main.cpuprofile.txt)

**Comment by jrieken** [comment]
wow - it takes more than 10 seconds to launch a new process... Do you use anti virus software and iff so can you rerun with that disabled

<img width="943" alt="Screenshot 2019-12-11 at 16 41 34" src="https://user-images.githubusercontent.com/1794099/70635990-1a66a380-1c35-11ea-8800-787700ffceb7.png">

**Comment by Harry09** [comment]
I only use Windows Defender.
Woah, it helped.
After turning on again, it still startup fast.
[prof-f454.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/3951585/prof-f454.main.cpuprofile.txt)
[prof-f454.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/3951586/prof-f454.renderer.cpuprofile.txt)
[prof-f454.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/3951587/prof-f454.extHost.cpuprofile.txt)

**Comment by jrieken** [comment]
Can you check if you have a (defender) update pending?

**Comment by Harry09** [comment]
I checked for updates and there was update to (KB2267602 (version: 1.307.279.0))

**Comment by jrieken** [comment]
Did that change anything?

**Comment by Harry09** [comment]
As I said before, when I am turning on Defender again, VS Code startup time is like when Defender is off..

**Comment by Harry09** [comment]
I also noticed that other Electron-based apps startup faster (like Spotify or Discord). This is weird. Something must have switched in Defender.
