### ISSUE TITLE
Can't close suggestions by pressing ESC anymore in TypeScript

### ISSUE THREAD

**Issue by patoezequiel** [microsoft/vscode#86693]
Issue Type: <b>Bug</b>

1. In a TypeScript file, code until the editor opens a tooltip with suggestions.
2. The keyboard focus is now inside the suggestions box, press ESC to close the box.

Expected behavior: The keyboard focus goes back the to the code editor where I left it.

Actual behavior: The keyboard focus stays trapped within the suggestions box and doesn't close until I manually click outside it.

![image](https://user-images.githubusercontent.com/5291103/70567588-fe033200-1b74-11ea-87e2-c50855d7fafe.png)

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (5.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
ng-template|Ang|0.900.1
npm-intellisense|chr|1.3.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
todo-tree|Gru|0.0.162
angular2-switcher|inf|0.2.0
vscode-scss|mrm|0.8.1
vscode-language-pack-es|MS-|1.40.2
vsliveshare|ms-|1.0.1293
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|9.6.0
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
I can't repo this. I suspect it is either caused by extensions or is a custom keybinding configuration issue
