### ISSUE TITLE
[shaderlab] Support Shaderlab Highlighting for .cginc (Include files)

### ISSUE THREAD

**Issue by TrofSivart** [Microsoft/vscode#867]
Unity Cg Include files are essentially Shaderlab files that are pasted in when the shader is compiled. Right now highlighting for them is not supported in VS Code, the fix is to simply add ".cginc" to the package.json file in the shaderlab folder.

**Comment by aeschli** [comment]
Fix delivered

**Comment by TrofSivart** [comment]
thanks! :D

**Comment by Coresi7** [comment]
@aeschli  how about .glslinc?

**Comment by aeschli** [comment]
@Coresi7 Please file an issue :-)
