### ISSUE TITLE
JSON no longer following tabsize setting when formatting document?

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#86709]
Issue Type: <b>Bug</b>

If I load my package.json file (https://raw.githubusercontent.com/microsoft/vscode-azurearmtools/6570e29d829ab3d14498e7c9d9a60ce949ecf2af/package.json) and format the file in vscode 1.40.2(user setup), it keeps the current 2-space settings.  If I format it in 1.41.0-insider, it reformats everything to four spaces, even though the edit claims it's using 2 spaces:
![image](https://user-images.githubusercontent.com/6913354/70580623-53d1dd00-1b69-11ea-82de-1eaedb217438.png)

My workspaces settings are:
{
    "editor.formatOnSave": true,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "search.exclude": {
        "out": true,
        "**/node_modules": true
    },
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.organizeImports": true
    },
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        ".vscode-test": true,
        "out": true
    },
    "files.associations": {
        "tslint.json": "jsonc"
    }
}

User settings are using default settings:
![image](https://user-images.githubusercontent.com/6913354/70580785-dbb7e700-1b69-11ea-819f-47ba9571a902.png)
I'm assuming since editor.detectIndentation is at its default true, that the 2-space indentations should be changed?

VS Code version: Code - Insiders 1.41.0-insider (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-10T21:44:16.632Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
gitlens|eam|10.2.0
json-escaper|jos|1.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
package-json-dependencies-navigation|mam|0.1.8
capturesyntaxtokens|Mic|0.0.1
vscode-antlr4|mik|2.2.3
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
extension-manifest-editor|ms-|0.1.5
remote-containers|ms-|0.92.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.41.5
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
csharp|ms-|1.21.8
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
83861|msa|0.0.1
azurerm-vscode-tools|msa|0.8.2
json-parse-stringify|nex|1.0.2
vscode-json-editor|nic|0.2.3
vscode-yaml|red|0.6.1
vscode-sort-json|ric|1.18.0
scope-info|sie|0.2.0
tmcolor|sle|0.0.1
tmlanguage|Tog|0.9.0
sort-lines|Tyr|1.9.0
win-ca|uko|3.1.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by aeschli** [comment]
To find out what indent was send to the JSON language server, can you 
- set `"json.trace.server": "verbose"`
- open the Output view, tab 'JSON Language Server`.
- open the JSON document, format
- in the JSON log, look for `textDocument/rangeFormatting`

![image](https://user-images.githubusercontent.com/6461412/99082694-c42c7e00-25c4-11eb-9d26-1152e3c70690.png)
