### ISSUE TITLE
Unicode rendering of typed indic script fails

### ISSUE THREAD

**Issue by crazyfoxkp** [microsoft/vscode#86706]
Indic script Kannada in editor
-------
When typing Indic script Kannada in editor (MacOS Kannada- QWERTY keyboard) use of 
U+0CCD  (kannada sign virama) causes entire word to be deleted to left. 
Characters are rendered properly when copy-pasted. 

Example word: ಪ್ರಕಾಶನ
1. Key sequence "pfrkaSn" on Kannada keyboard results in dropping 'p' character (or left delete of any number of characters in a different word)
2. Copy-pasting example word works as expected. 

![vscode](https://user-images.githubusercontent.com/29047364/70578273-0f8f0e80-1b62-11ea-9f20-7000895ad54c.gif)

----- other details -----
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.5.0

**Comment by rebornix** [comment]
I can no longer reproduce this issue on latest Insiders.
