### ISSUE TITLE
Intellisense Bug with Global Types

### ISSUE THREAD

**Issue by lameimpala** [microsoft/vscode#86702]
Issue Type: <b>Bug</b>

Create a javascript project.
Add a `globals.d.ts` file and declare a const with string type.
While the `globals.d.ts` file is open, intellisense works as expected.
Close the `globals.d.ts` file and observe that intellisense no longer works for values decalred in `globals.d.ts`.

VS Code version: Code - Insiders 1.41.0-insider (455d8f73cd7c73285fba70ab039a26279f19bb57, 2019-12-10T12:58:00.299Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_1982948|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Does your workspace contain a [jsconfig](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) or tsconfig?

**Comment by lameimpala** [comment]
Neither.  Maybe I'm confused as to how the intellisense is supposed to work.  Is it supposed to pick up the types defined in `globals.d.ts` automatically?

**Comment by mjbvz** [comment]
If you use globals instead of explicit imports, you need to tell VS Code that these files are part of the same project. That's what a jsconfig does. See [the documentation](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) for help creating one

**Comment by lameimpala** [comment]
Thanks!
