### ISSUE TITLE
syntax highlighting is off for TypeScript enums

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/vscode#86704]
**monaco-editor version:** 0.18.1
**Browser:** Google Chrome 77.0.3865.90
**OS:**  macOS 10.14.6 (18G103)

After updating to the September release of Visual Studio Code, I noticed the way enums are rendered in TypeScript changed. 

If you compare how they are rendered with `Light + (default light)` Visual Studio Code theme (Visual Studio in the Web version of Monaco Editor), you'll notice the difference:

**Before**

![image](https://user-images.githubusercontent.com/20233319/66549629-fa870680-eb43-11e9-9e20-5a6f0a4455ce.png)

**After**

![image](https://user-images.githubusercontent.com/20233319/66549655-0a9ee600-eb44-11e9-8094-b104c53b1669.png)

**Steps or JS usage snippet reproducing the issue:**

```ts
enum ComparisonResult {
  Smaller = -1,
  Equal = 0,
  Bigger = 1,
}
```

I'm not sure if that's intended or is it a regression. It doesn't seem to have changed for the  `Dark + (default dark)` Visual Studio Code theme. I'm opening an issue since I haven't seen anything about it in any changelog so far.

**Comment by mjbvz** [comment]
This color comes from the rules for `variable.other.enummember`.

**Comment by alexr00** [comment]
It did change for both dark and light themes. @aeschli do you want to keep the new color(`variable.other.enummember`), or the old color(`variable`)?

**Comment by karol-majewski** [comment]
It seems like there's another change, possibly accidental, in the latest Code Insiders. It strikes me as strange (why one identifier would be colored differently than the other):

![image](https://user-images.githubusercontent.com/20233319/72534368-fd963f00-3876-11ea-9275-be6e1617cdab.png)

```
Version: 1.42.0-insider
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T08:53:57.100Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0
```

**Comment by mjbvz** [comment]
@karol-majewski Unrelated, see #88696

**Comment by alexr00** [comment]
We will keep the new color.
