### ISSUE TITLE
the file explorer do not work after use "go to definition(F12)" several times

### ISSUE THREAD

**Issue by lfjbb** [microsoft/vscode#86712]
![121](https://user-images.githubusercontent.com/35714131/70588535-03f62300-1c08-11ea-9a58-ce50434ea48c.PNG)
![111](https://user-images.githubusercontent.com/35714131/70588539-09536d80-1c08-11ea-97af-1665710f5bfc.PNG)

- VSCode Version: 
- OS Version:

Steps to Reproduce:

1.  use VSCode with the github open source project "taurusai/kungfu"
2.  view the codes with the "go to definition(F12)" function

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
@lfjbb Can you check to see if there is anything in the dev console? (F1 > Developer: Toggle Developer Tools)

What extensions do you have installed?

**Comment by lfjbb** [comment]
![1111](https://user-images.githubusercontent.com/35714131/70690087-e3ee5e80-1cf0-11ea-8242-199d788788c0.PNG)

![121](https://user-images.githubusercontent.com/35714131/70690207-2748cd00-1cf1-11ea-973b-2caba23c8980.PNG)

acctually, I do not know much how this issue happen
