### ISSUE TITLE
shutting down suddently

### ISSUE THREAD

**Issue by imshivamchauhan** [microsoft/vscode#86719]
Issue Type: <b>Performance Issue</b>

from last 3-4 days, vs code is shutting down suddently while using and ask for reopen or cancel in dialog box.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.75GB (7.11GB free)|
|Process Argv|D:\personal\RnD\angularx-social-login\package-lock.json|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	    71	  1908	code main
    0	    16	    76	   electron-crash-reporter
    0	   176	  4988	   window (app.component.ts - angular-app - Visual Studio Code)
    0	    65	  6496	     extensionHost
    0	    55	  3068	       electron_node tsserver.js 
    0	    32	  3836	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=6496
    0	   153	  8248	       electron_node tsserver.js 
    0	    44	  9712	         electron_node typingsInstaller.js typesMap.js 
    0	    11	  6948	     watcherService 
    0	    11	 10116	       console-window-host (Windows internal process)
    0	     4	 18340	     C:\WINDOWS\System32\cmd.exe
    0	    34	  7016	       "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" start
    0	     4	 17836	         C:\WINDOWS\system32\cmd.exe /d /s /c ng serve --host 0.0.0.0 --port 2
    6	    71	  1864	           node   "D:\personal\RnD\angular-app\node_modules\.bin\\..\@angular\cli\bin\ng" serve --host 0.0.0.0 --port 2
    0	     6	 19360	     console-window-host (Windows internal process)
    1	   112	  5660	   gpu-process
    0	    45	 15372	   shared-process
    4	    64	 17860	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (app.component.ts - angular-app - Visual Studio Code)
|    Folder (angular-app): 40 files
|      File types: ts(11) json(9) js(2) html(2) scss(2) editorconfig(1)
|                  gitignore(1) md(1) ico(1) gitkeep(1)
|      Conf files: tslint.json(2) package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
code-beautifier|mic|2.3.3
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by RMacfarlane** [comment]
@imshivamchauhan Did this start happening with a recent update of VSCode? Does it happen for the same folders?
