### ISSUE TITLE
duplicates typed text to some other files

### ISSUE THREAD

**Issue by sanjaykhanssk** [microsoft/vscode#86715]
Issue Type: <b>Bug</b>

when i change something in main.py, it also adds the same line in different files, i thought I just copy-pasted but i was not, it itself doing many times every time i run a script it shows this error. Fix it :) 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.0.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2291)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|3.73GB (0.12GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
spellright|ban|3.0.48
django-html|bib|1.3.0
vscode-markdownlint|Dav|0.32.0
vscode-postman|eri|1.0.2
shortcuts|giz|0.0.1
python|ms-|2019.11.50794
vscode-xml|red|0.9.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
markdown-all-in-one|yzh|2.6.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible without extensions?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by sanjaykhanssk** [comment]
the filename is different. Actually, it happened 5-6 times with opened files in the closet tab, but not happening always, few times. I think it's just a bug.

**Comment by IllusionMH** [comment]
The question is if it's a bug with editor itself or some extension. Therefore confirmation that this might happen with all extensions disabled needed.

**Comment by sanjaykhanssk** [comment]
ok I will close the issue, it like a bug, but not happening all the time. Thanks :)
