### ISSUE TITLE
The child process Code.exe ignore parent process priority

### ISSUE THREAD

**Issue by Gargony** [microsoft/vscode#86716]
Then I run Code.exe with "low" process priority (CPU usage), Code.exe creates the child Code.exe with process priority "normal" (ignore the parent "low").

- VSCode Version: 1.40.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. Run START "" /low "Code.exe"
2. Look at the child Code.exe process priority (use [Sysinternals Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer))

Does this issue occur when all extensions are disabled?: Yes (don't think what extensions can do it)

**Comment by deepak1556** [comment]
Process priority is controlled by the chromium runtime, closing as not actionable.
