### ISSUE TITLE
chinese input method can't input when select content 

### ISSUE THREAD

**Issue by 502647092** [microsoft/vscode#86724]
**monaco-editor version:** 0.18.1
**Browser:** Chrome
**OS:** Windows

![temp](https://user-images.githubusercontent.com/10203793/69393440-1caf9f00-0d14-11ea-9502-f17727f52c13.gif)

select content and use input method will cause editor freeze

**Steps or JS usage snippet reproducing the issue:**

**Comment by 502647092** [comment]
@alexdima when can we resolve this problem

**Comment by rebornix** [comment]
I can reproduce this issue with third party IMEs but not the system built in one.

**Comment by 502647092** [comment]
@rebornix maybe is edge dev bug
I test at chrome it't ok

**Comment by rebornix** [comment]
As mentioned above, it's an upstream (browser specific), so fixes should go to Edge dev since it's a chromium fork.
