### ISSUE TITLE
Electron: leverage binary from electron dev dependency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86725]
For https://github.com/microsoft/vscode/issues/83421 I added a new dev dependency to Electron (https://github.com/microsoft/vscode/commit/93f58e063efcb86960ec1f2529186a63e655ee6c). This has the advantage of pulling in the correct `electron.d.ts` for us.

However, it also pulls in the Electron binary which is redundant to the one we pull into our `.build` folder. Ideally (maybe only when running out of sources), we would pick the binary from that folder. However, not clear to me what kind of modifications `gulp-atom-electron` do after downloading.

**Comment by bpasero** [comment]
Looks like this is relevant:

https://github.com/microsoft/vscode/blob/93f58e063efcb86960ec1f2529186a63e655ee6c/build/lib/electron.ts#L93-L108

**Comment by bpasero** [comment]
And all the places where we expect `.build/electron`:

![image](https://user-images.githubusercontent.com/900690/70605801-76143b00-1bfb-11ea-984b-c1b5a696020c.png)

**Comment by deepak1556** [comment]
> However, not clear to me what kind of modifications gulp-atom-electron do after downloading.

Check the per platform files under `gulp-atom-electron/src` ,  the renaming and removal default app sources are important.

> Ideally (maybe only when running out of sources), we would pick the binary from that folder.

If we work towards this, then working on https://github.com/microsoft/vscode/issues/81425 will become difficult.

**Comment by bpasero** [comment]
@deepak1556 yeah, maybe a better approach would simply be to consume Electron from the `node_module` folder if present instead of downloading it. I think we can keep everything else as it works today then?

**Comment by deepak1556** [comment]
Yeah we could do that, but the gulp version does all the transformation in memory with the downloaded stream through `vinyl-fs`, not sure if an extra machinery to reuse the binary is worth saving the additional download ?

**Comment by bpasero** [comment]
True, I think this should probably move to the gulp-atom-electron repository because changes need to happen there to support this.

**Comment by bpasero** [comment]
https://github.com/joaomoreno/gulp-atom-electron/issues/56
