### ISSUE TITLE
mix-blend-mode causes all kinds of issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8672]
Issues:
* lost cursor in the editor (https://github.com/Microsoft/vscode/issues/9029)
* lost LCD subpixel anti alias
* focus outline coloring turns gray
* DND feedback in light theme is gray when it should be blue

<img width="328" alt="screen shot 2016-07-03 at 11 19 09" src="https://cloud.githubusercontent.com/assets/900690/16544694/fcf38998-410f-11e6-90ac-8799935e1e50.png">

**Comment by bgashler1** [comment]
I don't think this can be solved simply.

We probably need to do one of the following:
- Use rgba colors
- Use a nasty and hacky z-index trick on duplicate versions of the tabs that act as the click/keyboard focus targets.  They would have transparent backgrounds and would be `opacity: 0` when not in focus or active.  This would basically just be trick to get a colored overlay.
- Use JavaScript internally to calculate the colors
- Use a library that enables `color-mod()` function usage from the CSS 4 spec during runtime (#8151).

The best solution is a CSS custom property in my opinion.  On the engineering side, how do you feel about the work to make this happen?

**Comment by bpasero** [comment]
Yeah, there is also the issue that once you set mix-blend-mode, all children seem to inherit this (similar to opacity) and you cannot unset this in a child. This is also the reason why I cannot have my nice blue drop feedback in light theme when dragging over tabs.

If we do something about it, it should not be a hack. Maybe we go back to rgba() in tabs land?

**Comment by bpasero** [comment]
There are more issues with mix-blend: we lost LCS subpixel anti aliasing in the tabs control which will cause it to look blurry for some users. 

Marking as important because I would not want to ship July without a fix for this (going back to opacity?).

**Comment by bgashler1** [comment]
We agreed in the UX meeting today to remove the `mix-blend-mode` and instead use rgba colors to avoid issues with anti-aliasing and other color side-effects that we cannot otherwise work around.

**Comment by alexandrudima** [comment]
:+1: combined with the use of `translate3d` in rendering the cursors, it causes #9029

**Comment by bpasero** [comment]
I pushed a change to remove mix-blend-mode from the tabs title. I did not introduce rgba() colors though and would like to wait for community feedback before reacting.

**Comment by jrieken** [comment]
@bpasero We still use [`mixed-blend-mode`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/widget/media/tokens.css#L10) in the high contrast theme. Unsure about the effects that has?

**Comment by bpasero** [comment]
@jrieken true, I saw that as well and it is probably very old. @bgashler1 do you have an idea why we have it?

**Comment by bgashler1** [comment]
@jrieken @bpasero the `mix-blend-mode: difference` in the high-contrast theme is to enable highlighting the text in white while inverting the text color.  Without it, it would look like this.
<img width="554" alt="screen shot 2016-08-25 at 12 02 04 pm" src="https://cloud.githubusercontent.com/assets/11839736/17982218/c4901596-6abb-11e6-8feb-db399a1c835e.png">

It hasn't caused any problems.  The alternative, which is currently not possible, is to instead enable styling the text color of the selection and use black or very dark colors for all tokens.
