### ISSUE TITLE
Bug visual

### ISSUE THREAD

**Issue by Mackenziefox** [microsoft/vscode#86720]
Hello, I have visual bugs... errors that are not fixed, that is, it is annoying that the underlined line of the error is not removed when I have already solved it, I have to close and open, also sometimes it does not recognize the commands in C++.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you use proper template and fill all necessary information about version, OS, extensions list and if reproducible with extensions disabled, screenshots of visual bugs.
