### ISSUE TITLE
Provide Editor Font Size with `px` unit to Webviews

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#86722]
Issue Type: <b>Feature Request</b>

As an extension developer I can style my Webview from the CSS `var`s, except for `--vscode-editor-font-size` which is provided as a number without units. So in my CSS I need to hard code the font size, like so:

```scss
  font-size: 15px; // var(--vscode-editor-font-size);
```

I need a `var` including the `px` unit, like with `--vscode-font-size`.

VS Code version: Code - Insiders 1.41.0-insider (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-10T21:42:59.146Z)
OS version: Darwin x64 19.0.0

**Comment by PEZ** [comment]
I found a workaround for now, maybe someone else has use for it.

I set the style attribute of the html element to the result of:

```js
getComputedStyle(document.body).getPropertyValue('--vscode-editor-font-size')
```

**Comment by eamodio** [comment]
FYI, You can also read that value and write your own version (or overwrite the same one) with px added.
