### ISSUE TITLE
Project tree and function reference

### ISSUE THREAD

**Issue by andreamoro** [microsoft/vscode#86726]
Back to the old VBA days, but even looking at the most recent IDE, I think that a real added value in actively using a fully fledged IDE for data science coding is the possibility to use all the advanced characteristics it may offer.

One of this, could be the project tree, which could list all the functions used in the code so to easily just back and forth as needed.

This could also mitigate the problems due to the lack of the [missing Search feature](https://github.com/microsoft/vscode-python/issues/7903).

- Project tree
- Active list of functions that allows jump directly to the cell where a feature is coded
- List of declared variables with object type

**Comment by IllusionMH** [comment]
> One of this, could be the project tree, which could list all the functions used in the code so to easily just back and forth as needed.

VS Code has [Outline view](https://code.visualstudio.com/updates/v1_25#_outline-view), [Go to Symbol in File...](https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-symbol) and [Go to Symbol in Workspace...](https://code.visualstudio.com/Docs/editor/editingevolved#_open-symbol-by-name)

But if you need this for Jupyter notebooksand Outline view doesn't show info about functions - it should be request to Python extension :(

**Comment by RMacfarlane** [comment]
Please open this feature request on the Python extension: https://github.com/Microsoft/vscode-python
