### ISSUE TITLE
Sticky action footer in hover

### ISSUE THREAD

**Issue by vasiltabakov** [microsoft/vscode#86729]
The Quick Fix / Peek problem "footer" in the hover is very useful, however it would be better if this "footer" is sticky (i.e. always visible) regardless of the length of the hover text.

Currently when the hover is scollable you see the "footer" after you scroll to the bottom.
Here's a demo of the current functionality:
![2019-06-07_11-03-27](https://user-images.githubusercontent.com/1178309/59090044-529ec980-8914-11e9-8d0b-54432ae4eb36.gif)

**Comment by sandy081** [comment]
Will be considered here - https://github.com/microsoft/vscode/issues/73120
