### ISSUE TITLE
search.exclude is being ignored

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#86727]
Issue Type: <b>Bug</b>

The setting `search.exclude` is being ignored. I think the (partly default) globs configured are correct, so searching for text in files will happily search through everything, including the excluded files, and report a lot of "noise" to me that is of no use to me.

It could be that I'm doing something wrong, but I can't imagine what that would be. The search feature is pretty basic - not a whole lot that can go wrong in terms of usage.

It seems I found some sort of bug, if I'm not mistaken.

Here is a screenshot to prove what I mean:
![Capture](https://user-images.githubusercontent.com/152227/70608400-592e3680-1c00-11ea-90f9-252864b028a0.PNG)

Please note that this problem also occurs with all extensions disabled.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (13.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
Bookmarks|ale|10.6.0
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
vscode-great-icons|emm|2.1.47
file-icons|fil|1.0.19
duplicate|gee|1.0.1
docthis|joe|0.7.1
rainbow-csv|mec|1.3.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|0.9.0
remote-wsl|ms-|0.40.3
vscode-versionlens|pfl|0.24.0
vscode-template-literal-editor|pli|0.9.0
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
mdx|sil|0.1.0
vscode-svg-previewer|vit|0.5.1

(1 theme extensions excluded)

</details>

**Comment by myfonj** [comment]
You have explicitly disabled the exclude:
![image](https://user-images.githubusercontent.com/1761395/70618700-ca2b1980-1c13-11ea-8df9-386965684600.png)
To enable it again, use the "⚙minus" button at the end of exclude input in extended search panel:
![image](https://user-images.githubusercontent.com/1761395/70618971-50476000-1c14-11ea-8fb7-0a73f9bbb28c.png)

**Comment by thany** [comment]
Well, that's awkward 😣

Take it like this: that little button controls a lot of noise being outputted, or not. It's also really hard to see the state of that button, and it's not possible to know what it's trying to tell without hovering the mouse cursor on it.

I honestly didn't notice that text either "ignored files are disabled". It's not there in my mind, I just immediately focus on the results.

**Comment by myfonj** [comment]
Sure, I don't blame you, it's easy to overlook such detail. At the same time it's hard to design such panel to be both non-distracting and verbose enough to clearly communicate everything it does.

<small>(See: I've messed up instructions to get to this button myself: I've thought it is under left ">" toggle, but in fact is under right "..." toggle.)</small>

I assume the default state of the "⚙➖ use Exclude Settings [...]" toggle button is "On" and user is expected to remember when and why he disables it and what it does. You are right that notice about it's effect above search results is really quite sunken…

**Comment by roblourens** [comment]
Sorry @thany, thanks @myfonj :)
