### ISSUE TITLE
Suggestion: Indicate closing bracket in folded area

### ISSUE THREAD

**Issue by vasiltabakov** [microsoft/vscode#86735]
![image](https://user-images.githubusercontent.com/1178309/58038603-fc224480-7b38-11e9-83c6-94df3f685f63.png)

When folding a function (or whatever brackety) the folded indicator is three dots as shown above. Also the opening bracket is shown.

It would be better if the closing bracket is shown so as to get something like:
![image](https://user-images.githubusercontent.com/1178309/58038660-3e4b8600-7b39-11e9-90b8-c9ff919a46ca.png)
Additionally it would be great if clicking the brackets would also expand the folded area.

**Comment by aeschli** [comment]
Dup of https://github.com/microsoft/vscode/issues/3352
