### ISSUE TITLE
Exact matches in symbols fuzzy search are not on top

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#8673]
I was a bit amazed by this, this is a screenshot from a file wide symbols listing (which should be quick to generate):

![image](https://cloud.githubusercontent.com/assets/64731/16539812/ca2360d8-4056-11e6-8195-6025136180b4.png)

Why does it suggest me a "LoggedIn" as default, rather than "Login" which is exact match? I think fuzzy search sorting should be predictably ordered. Exact matches should be at the top, especially on quick commands like file wide symbols search.

Ordering, on top of my head, should be:

Exact matches,
Matches that begins with the word,
Fuzzy matches

Version 1.3.0 insider

**Comment by bpasero** [comment]
@Ciantic is that file open source and can be attached here for me to repro?

**Comment by Ciantic** [comment]
@bpasero tried again, still happens. It's open source, here is the file https://github.com/Ciantic/AspNetApiMonolithSample/blob/master/src/Api/Controllers/OpenIdController.cs

**Comment by bpasero** [comment]
Thanks!

**Comment by Ciantic** [comment]
@bpasero I'm now using this: [a1293f5056e79c3f0e2cd3e24909f41ff4eef472](https://github.com/Microsoft/vscode/commit/a1293f5056e79c3f0e2cd3e24909f41ff4eef472), which should include your patch if I'm not mistaken. But it still functions incorrectly:

![image](https://cloud.githubusercontent.com/assets/64731/16591830/72bda4b0-42e6-11e6-8385-aa255accf311.png)

**Comment by bpasero** [comment]
@Ciantic no it is not in insider yet.
