### ISSUE TITLE
Behavior of Super + Delete

### ISSUE THREAD

**Issue by y-usuzumi** [microsoft/vscode#86731]
Hi. It's not exactly a bug. I haven't found it documented anywhere so I want to look for some help on explaining/clarifying this behavior.

- VSCode Version: 1.40.2
- OS Version: Arch Linux

Steps to Reproduce:
1. Open any text file or create a new file
2. Press `Super` + `Delete`
3. An invisible character is inserted at the cursor position.

By saving the file and opening it with a hex editor, I can see the character is actually a 0x7F (DEL) printing character.

I thought it was due to some shortcut settings system-wide. However I played with several editors and only found the issue on VSCode.

The reason I found it a bit annoying is that I am using a 60% keyboard, and Delete key is done by `Fn` + `Backspace`. I have also set the shortcut of opening a dropdown terminal to `Super` + `F12`, and `F12` is done by `Fn` + `=`. So sometimes I press `Super` + `Fn` + `Backspace` by accident, while I was actually thinking of `Super` + `Fn` + `=`.

It seems like a corner case, but after this I will very likely save the code file I was editing, leaving the invisible character inside.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
It's currently a limitation of the architecture (how we handle editing) and how an IME behaves. For this particular case, the IME inserts that into the textarea which we can't tell if it's intended or not. Sorry that we don't have a proper fix for it but you can turn on `"editor.renderControlCharacters": true` and then you can see the control character in the editor when that happens so you have a chance to delete it immediately.
