### ISSUE TITLE
Zone widget scrollbar height

### ISSUE THREAD

**Issue by vasiltabakov** [microsoft/vscode#86739]
When you click 'Peek Problem' the Zone widget is shown, but its vertical scrollbar height is just 3px and thus difficult to click. The scrollbar is actually 9px height but it's parent/wrapper div is 3px height.

![2019-03-29_20-45-19](https://user-images.githubusercontent.com/1178309/55255552-9cf43200-5263-11e9-8fc4-92380689bbf3.gif)

**Comment by sandy081** [comment]
It's easy to fix but we use similar scroll bar at other places too like tabs and breadcrumbs.  This feature has been there for so long and no complains till now. So will wait for a while to fix it.
