### ISSUE TITLE
Feature request: Closing folding range UI/UX

### ISSUE THREAD

**Issue by vasiltabakov** [microsoft/vscode#86736]
It would be great for the folding ranges to be indicated with a 'closing' interactable icon apart from 'starting' icon. This would allow to fold a long range from where it ends:

Here's an example:
![image](https://user-images.githubusercontent.com/1178309/57697590-4d739500-765c-11e9-98a5-05f09c814863.png)

There would be an icon at the `if` closing bracket line.
I imagine to implement this would also require changing the start/end icon of the range.

To the very least it would be great to have an indication of where the range ends (as in VS).

**Comment by aeschli** [comment]
Dup of https://github.com/microsoft/vscode/issues/60670
