### ISSUE TITLE
Getting error : rxjs-compat/operators/audit

### ISSUE THREAD

**Issue by sunil12345** [microsoft/vscode#86732]
HI Team,

I am getting the error while creating a 
[New Microsoft Word Document.docx](https://github.com/microsoft/vscode/files/3949626/New.Microsoft.Word.Document.docx)
project in Visual Studio code.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please use proper issue template and provide all necessary data from template (versions, if reproduced with extensions disabled), steps to reproduce and screenshot of the error.
