### ISSUE TITLE
VSC doesn't reopen the files I was working after restarting

### ISSUE THREAD

**Issue by dariocostanzo** [microsoft/vscode#86740]
Not sure if this is something I am doing wrong or a bug, but I think it is worth double check with you. I couldn't find a resolution on-line.

1) Open a folder and different files
2) Work on them and save
3) Close VSC
4) Reopening VSC will get a new window or an old project 

In my case, when I reopen VSC (after step 1,2 and 3), I always get a new window or files related to a project I was working on earlier (i.e 1 week ago) in a completely different branch, despite the fact I closed all the pages before changing branch, and opening the files of another project, sometimes from the same folder.

**Comment by RMacfarlane** [comment]
@dariocostanzo What's the value of your "window.restoreWindows" setting?

If you change branches outside of VSCode, it's expected that the branch would also change within VSCode. VSCode directly uses git for this information.

**Comment by dariocostanzo** [comment]
Hi @RMacfarlane,
the value of my "window.restoreWindows" setting is set to `one` (default). But I changed it to `all` so it will reopen everything, that's what I needed.
> The window.restoreWindows setting tells VS Code how to restore the opened windows of your previous session. By default, VS Code will reopen the last opened window you worked on (setting: one). Change this setting to none to never reopen any windows and always start with an empty VS Code instance. Change it to all to restore all windows you worked on during your previous session or folders to only restore windows that had folders opened.

RE branch changes, the issue wasn't occurring when  changing branch.

Thanks
