### ISSUE TITLE
[Feature request] Gethering necessary info when program crashed or has memory leak

### ISSUE THREAD

**Issue by 1011178l** [microsoft/vscode#86746]
Recently, a number of people suffering from the memory leak. VS code or some plugin will eat all memory in a short time, and there is no chance to collect debug data for vs team. In addition, such kind of issue usually difficult to reproduce. our user surly has such kind of problem, but we don't know why and how to reproduce it.

So it would be nice that the vs code has a feature that gathering all necessary technical data and generating a report. Later our user can report such bugs, and make the vs team easier to fix them.

**Comment by deepak1556** [comment]
Closing as steps to gather crash dumps are covered in https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports
