### ISSUE TITLE
Asynchronously verified breakpoints are not always marked as "verified" within the UI

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#86749]
Observed by @testforstephen in https://github.com/microsoft/vscode/issues/83743#issuecomment-563894120 and myself in https://github.com/microsoft/vscode-js-debug/issues/144 -- the latter has steps to reproduce the issue.

> What I'm seeing is that:
> 
>  1. The 'stubbed' parent debug session gets a setBreakpoints request. It returns unverified BP (and never verifies them).
>  2. The child debug session gets a setBreakpoints request. It also initially returns the BPs as unverified,
>  3. then a few milliseconds later (once we get confirmation from CDP) the child verifies them.
> 
> I think the correct behavior is for the BP to show as verified if any debug session verifies them, and this usually works. So I suspect there's some timing issue in vs code itself here.

**Comment by isidorn** [comment]
@connor4312 this should not happen. Our approach is to show the breakpoint as verified if at least one session verified it.
Can you please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/1c6e6b8030477e9a2d9b9005058322071744ec24/src/vs/workbench/contrib/debug/common/debugModel.ts#L561). And [here](https://github.com/Microsoft/vscode/blob/1c6e6b8030477e9a2d9b9005058322071744ec24/src/vs/workbench/contrib/debug/common/debugModel.ts#L622)
Point being the `data` should be the `data` of the sub session which verified it, not of the parent session.

How does the child session verify the breakpoint, does it send a breakpoint `changed` [event](https://github.com/Microsoft/vscode/blob/1c6e6b8030477e9a2d9b9005058322071744ec24/src/vs/workbench/contrib/debug/browser/debugSession.ts#L884)?
I am having issues running the dev container for the node sample, thus I am unable to repro this issue atm.

**Comment by connor4312** [comment]
@isidorn it looks like those source references don't exist any more, could you  update them?

The child session does send a changed event. If you try to reproduce it, note that in the most recent version of PWA we made a change to work around this issue--we try to resolve the BP in the initial setBreakpoints response--you'll want to check out cd910d020466b089f920ea50c8ba0f6168bab278 and run `gulp package` to get a vsix where the bug is present. (Once the bug is fixed we'll revert our workaround to cut down on complexity)

**Comment by isidorn** [comment]
Sorry this somehow slipped through my radar.
Here are new code pointers:
https://github.com/microsoft/vscode/blob/9bf0af3ea0715d73cfa6440a14f4487028412d74/src/vs/workbench/contrib/debug/common/debugModel.ts#L556

https://github.com/microsoft/vscode/blob/9bf0af3ea0715d73cfa6440a14f4487028412d74/src/vs/workbench/contrib/debug/common/debugModel.ts#L618

The data object is session specific data for a breakpoint. Point is we should figure out why the breakpoint thinks it is not verified and from what session does it read the data.

**Comment by isidorn** [comment]
@connor4312 do you have some nice steps to reproduce this without having a container? Is it possible to reproduce this locally? Did the code pointers I provided help?

**Comment by isidorn** [comment]
@connor4312 friendly ping for my previous question.

**Comment by connor4312** [comment]
Apologies, will check this out tomorrow morning!

**Comment by isidorn** [comment]
No problem and no hurries. Thanks

**Comment by connor4312** [comment]
I actually cannot reproduce this on the latest insiders, though I can on an old 1.41 install I had lying around on a VM. Maybe the ordering PR fixed this?

Closing unless we see it happening again.

**Comment by isidorn** [comment]
Ok, thanks for looking into this!
