### ISSUE TITLE
Escape key not working, in any ot the vim extensions

### ISSUE THREAD

**Issue by getreu** [microsoft/vscode#86745]
Issue Type: <b>Bug</b>

1. Install any of the vim extesions
2. go in insert mode with key [i]
3. press [escape]

Non of the extensions returns to "normal" mode. this is why I think it is an vs-code issue. I was using the vscode.vim extension for many months without problem.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.19.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2948)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.65GB (4.18GB free)|
|Process Argv|--no-sandbox --unity-launch /home/getreu/Desktop/Cyber_Security-PhD/020-about_Rust/Useful for Stringsext/encoding_rs_test1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-rustfmt|Con|0.1.0
vscode-markdownlint|Dav|0.32.0
code-runner|for|0.9.15
path-autocomplete|ion|1.13.3
vscode-print|pdc|0.7.13
toggle|reb|0.0.1
vscode-typograf|rus|0.2.0
rust|rus|0.7.0
code-spell-checker|str|1.7.20
code-spell-checker-french|str|0.1.4
code-spell-checker-german|str|0.1.2
vscode-ltex|val|4.7.7
vscode-ltex-de|val|4.7.7
vscode-ltex-en|val|4.7.7
vscode-ltex-fr|val|4.7.7
debug|web|0.23.1

(1 theme extensions excluded)

</details>

**Comment by getreu** [comment]
What could have messed up the editor configuration, was the test installation of the plugin: Vim Fcitx Remote. My VSCode with the Vim-plugin on another computer is still working. Strange.

**Comment by IllusionMH** [comment]
Could you try to reproduce this issue with Insiders build? https://code.visualstudio.com/insiders/

**Comment by getreu** [comment]
I tried with Insiders build, but still the same buggy behavior.
Workaround: I deleted `~/.config/Code` and `~/.vscode`. After opening _vscode_ again, I reinstalled all my plugins and everything worked fine so far.
As I can not reproduce the steps that lead to my problem, I close this issue. Thank you for having had a look into this.

**Comment by IllusionMH** [comment]
Glad that you found solution!
