### ISSUE TITLE
Ctrl + Click is not working when I am using es6 import function in node

### ISSUE THREAD

**Issue by christyram99** [microsoft/vscode#86747]
**file1.js:**
```
import moment from 'moment'

function getNumber() {
    return 2
}
exports.getNumber = getNumber
```

**file2.js:**
```
import { getNumber } from './file1.js'
```

My CTRL + CLICK is not working for **getNumber** function in file2.js.

**Note:** I observed click functionality is working fine in two cases.

 1. When I remove the import function in file1.js
 2. By replacing **import** function with ``` const moment = require('moment') ```

**Comment by mjbvz** [comment]
If you enable [semantic checks](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript) in your js files by adding `// @ts-check` at the top, do you see any errors?

**Comment by christyram99** [comment]
After adding semantic checks, it is showing error ```Module '"./file1"' has no exported member 'getNumber'.ts(2305)```

**Comment by mjbvz** [comment]
I don't believe we support mixing `import` statements with an `commonjs` style `export` object. Try using either one style or modules or the other: all commonjs or all `import` and `export` statements
