### ISSUE TITLE
asciidoc links are highlighted incorrectly

### ISSUE THREAD

**Issue by vvavrychuk** [microsoft/vscode#86741]
Issue Type: <b>Bug</b>

Per https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links asciidoc links have the following syntax:

    URL[caption goes here]

The problem is that VS Code highlights symbols "[caption" as part URL
![Screenshot from 2019-12-11 13-03-51](https://user-images.githubusercontent.com/152563/70618472-a23fb400-1c1b-11ea-8999-1e1d306b0682.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 9, 9|
|Memory (System)|31.30GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
@rebornix since this comes from editor/contrib/links

**Comment by rebornix** [comment]
Our internal link detector doesn't understand asciidoc links.
