### ISSUE TITLE
Search with "files to include" asks to "narrow down results"

### ISSUE THREAD

**Issue by IllNate** [microsoft/vscode#86753]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Work on a project with lots of files, like the linux kernel
2. Use find in files and fill in an include path like "/path-to-project/**/*bcm203*"
3. Search for a common keyword like "string"
4. You will get an error such as "The result set only contains a subset of all matches. Please be more specific in your search to narrow down the results."

When you explicitly narrow the search results like this, the search would ideally only search those files. Instead it seems like the search is searching all the files and then filtering the results based on the "files to include" field. It's very annoying when you are in a huge project and cannot use the search box for common terms. 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3491)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 3|
|Memory (System)|31.36GB (6.94GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllNate** [comment]
It seems like a temporary work around is to add "./" to _files to exclude_. This seems to have the desired behavior, but is not intuitive.

**Comment by roblourens** [comment]
You will get that message whenever the search returns 10,000+ results. You should see the first 10,000 results and that message. If this doesn't explain what you are seeing, please include more details.

**Comment by IllNate** [comment]
That does not explain what I am seeing. I did not say that I was seeing 10,000+ results. I am trying to include only a handful of files, using wildcards and the include field. I should see results for only 1 file using my example above, but instead I get the error. 

Again, as I explained above, it seems to me that the search is performed first on ALL OF THE FILES and then the filter is applied. Wheres, I think it would be much better and faster if it first applied the filter and then searched only those files. And again, as I explained above, if you use the exclude filter on all files, it seems to be a workaround. But only after this frustrated me for several hours.

**Comment by IllNate** [comment]
I have also installed the insiders edition, and the workaround does not work in that version. It seems to me, than in that version the exclude filter is applied after the include filter. I do not get the "The result set only contains a subset ..." error unless I remove the exclude filter.

**Comment by IllNate** [comment]
The workaround only works when you have file opened. So there is no practical workaround for this issue currently.

**Comment by roblourens** [comment]
So you are seeing results in files that don't match the glob pattern? Does it work if you use a glob pattern that isn't an absolute path like your example above? Assuming that you have the relevant folder open.

**Comment by IllNate** [comment]
I am seeing, 0 results returned. I assume this is because the file isn't in the first 10,000 results and therefore, the order of operations matters. Search then filter returns 0 results. Unless I have the file open in my editor, then it seems to get bumped up in the search priority and gets searched before the 10,000 limit is hit. 

I have tried both absolute paths and relative paths, with the same result. I have the folder open in my workspace. I have also loaded the insiders version and get the same results.

**Comment by IllNate** [comment]
If I limit the glob pattern further like ./linux/drivers/bluetooth/**/bcm203*, then it works. So it seems like the include filter is partially applied before the search is performed, but as soon as a wildcard is encountered, it stops and applies the rest of the filter post search.

**Comment by roblourens** [comment]
> I assume this is because the file isn't in the first 10,000 results and therefore, the order of operations matters.

That isn't how it works, only results that match the query will be considered. 

I cloned the linux sources, can you tell me which files you expect to match? Should I be on a certain branch?

![image](https://user-images.githubusercontent.com/323878/70741761-e0e37600-1cd0-11ea-8978-b186ec2ea656.png)

**Comment by IllNate** [comment]
If your workspace is at the linux source directory, then the include needs to be ./drivers/bluetooth/**/bcm203*

BUT, doing this myself, it seems to work fine. My specific example is that I have a yocto build open in my workspace. So my file count is actually closer to 8 million. I loaded a new vscode instance, limited to just the linux source folder and it seems to be ok. So I'm not sure at what point it breaks. But in my specific example the globs are:

Search term: "static"
./build/workspace/sources/linux/**/bcm203* -> Returns 0 results
./build/workspace/sources/linux/drivers/**/bcm203* -> Returns 0 results
./build/workspace/sources/linux/drivers/bluetooth/**/bcm203* -> Returns 1 result

But like I said, this might be a bit more of a corner case than I thought. If I point my workspace to ../build/workspace instead, then things seem to be ok.

**Comment by roblourens** [comment]
I am not sure how to produce that build so I can't run the same scenario. Can you give an example of a path that should be matched, but isn't?
