### ISSUE TITLE
Sync: Settings aren't synced when there is an update

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#86759]
I noticed that when I came back to my Windows laptop that hadn't been updated with Insiders in a few days that my settings were not synced. I reloaded the window and checked that I was signed in and Sync was on, but it wasn't until I updated Insiders that it actually updated my settings.

**Comment by sandy081** [comment]
Update has nothing to do with the sync. Is it possible to reproduce this and provide me with the sync logs to know what's happening?
