### ISSUE TITLE
Incorrect editor message positioning.

### ISSUE THREAD

**Issue by shoorlyne** [microsoft/vscode#86758]
monaco-editor version: 0.14.3
Browser: Chrome 67.0.3396.99
OS: macOS 10.12

When the Monaco editor is in read-only mode, if one tries to enter some text, a tip will show up saying "Cannot edit in readonly editor". However, if the position is close to the right boundary, the tip is not correctly positioned.

Please check the following images to get the idea. The first shows where the cursor is, and the second shows the tip when one tries to enter something, at the same cursor position.

<img width="638" alt="screen shot 2018-08-26 at 4 47 50 pm" src="https://user-images.githubusercontent.com/20250340/44626550-e9376680-a950-11e8-8eca-9bbbc28d2453.png">
<img width="639" alt="screen shot 2018-08-26 at 4 49 19 pm" src="https://user-images.githubusercontent.com/20250340/44626552-ee94b100-a950-11e8-89c5-1021c805e8bf.png">

**Comment by jrieken** [comment]
I see a z-index issue with diff editor and an issue with the arrow alignment but not the wrapping...

<img width="517" alt="Screenshot 2020-07-06 at 13 30 22" src="https://user-images.githubusercontent.com/1794099/86588929-f0881c00-bf8c-11ea-9b1e-8b5709488ddc.png">
