### ISSUE TITLE
TreeView.message only works with Insiders

### ISSUE THREAD

**Issue by JarrettSpiker** [microsoft/vscode#86752]
The `TreeView.message` API only seems to work when run through VSCode Insiders.
Using it in VSCode 1.40 seems to either produce no effect, or throw errors saying that a proposed API is being used.

I am open to the idea that I am missing something obvious here and this API is still only "proposed", but it is shown in the API documentation:
https://code.visualstudio.com/api/references/vscode-api#TreeView%3CT%3E
It is not in the proposed API .d.ts:
https://github.com/microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts
And this commit seems to be what changed that:
https://github.com/microsoft/vscode/commit/f8c9cc7d6a09f97bf4e270c2782de653f17aa5af

**Comment by JarrettSpiker** [comment]
For reference, this is the error produced:
```
Activating extension `vscode-samples.custom-view-samples` failed:  [vscode-samples.custom-view-samples]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode-samples.custom-view-sample
```
When setting a message on https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/ftpExplorer.ts#L163

**Comment by alexr00** [comment]
Looks like I forgot to remove the check for that in 1.40. Sorry about the confusion and annoyance this caused! The check is removed in 1.41, which just released this week.
