### ISSUE TITLE
Electron Helper in processes is very confusing for Electron projects

### ISSUE THREAD

**Issue by z-ax** [Microsoft/vscode#8675]
Hi. I'm very confused with processes in Activity Monitor while working on Electron projects.
The "Electron Helper" are usually processes of unbuilt projects, and while debugging performance or related stuff, too confused with this because have both processes of VSCode and currently launched app (launched with prebuilt Electron).

After build, all processes are usually renamed to something like "My App Helper", but VSCode still has dummy names there - please, fix this.

- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Launch VSCode
2. Check Activity Monitor

![image](https://cloud.githubusercontent.com/assets/1391015/16540727/36828f04-4077-11e6-91da-24692d3d1630.png)

**Comment by ykulinichenko** [comment]
There is no such problem on Windows:
![pasted_image_at_2016_07_02_05_10_pm](https://cloud.githubusercontent.com/assets/7082591/16540766/50ff9c7c-4078-11e6-98e9-0ff6de94b9ff.png)

**Comment by bpasero** [comment]
We could rename the process I guess.

**Comment by joaomoreno** [comment]
Apparently it's [possible](https://github.com/electron/electron/blob/78193a0608b5fa55161e95b7b3845b6bd85af377/docs/tutorial/application-distribution.md#macos).

**Comment by joaomoreno** [comment]
joaomoreno/gulp-atom-electron#36

**Comment by z-ax** [comment]
I'd suggest using up-to-date [electron-packager](https://github.com/electron-userland/electron-packager) for builds instead of `gulp-atom-electron` which I see in the `package.json`.

**Comment by joaomoreno** [comment]
00826ad

**Comment by weinand** [comment]
Cool:
![2016-07-28_18-01-33](https://cloud.githubusercontent.com/assets/1898161/17219881/5eb7304e-54ed-11e6-9a30-d95833b05c6e.png)
