### ISSUE TITLE
Custom icon lost after app is updated

### ISSUE THREAD

**Issue by sepw** [microsoft/vscode#86756]
Issue Type: <b>Bug</b>

OS: macOS 10.14.6.

On macOS it's possible to change the icon of an item (folder, file or app) by doing the following:

1. Find the item in the Finder

2. Right-click the item and select "Get Info"

3. In the displayed Get Info window, select click icon in the top-left corner of the window to select it and paste an icon image from the clipboard.

4. macOS stores this icon and uses it to display the item both in Finder and related UIs such as the standard file open and save panels.

This is something that macOS has supported at least since 10.3, which was the first version I used. I use this feature to associate an alternative app icon with Visual Studio Code.

I have done this with other apps in the past. Normally, this metadata is not lost when an app is updated. However, when updating Visual Studio Code this metadata is lost, meaning that I have to repeat the above steps every time the app is updated.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by misolori** [comment]
@deepak1556 do you know if this is electron related? I don't think this is something we natively support.

**Comment by deepak1556** [comment]
Yes this is not an issue with vscode but rather how update works for electron, when update happens, the `*.app/Contents/Resources` will be refreshed hence any modified icns will be lost. This is as designed and there is nothing we can do on vscode end to fix this, hence closing.
