### ISSUE TITLE
Add a "Suspend" feature (Like "great suspender")

### ISSUE THREAD

**Issue by MichelDiz** [microsoft/vscode#86757]
In general, in my daily work, I tend to open many applications. Too many browser tabs(must of it keeps suspended) and too many VS projects. However, some projects I open with VS are just "tests." I keep them open to study. But I wish I could "freeze" them to save RAM and sometimes CPU process.

Amazingly, it is the VS Code that consumes the most memory on my desktop today.

Please, analyze this with care.

PS. This is not duplicated of https://github.com/microsoft/vscode/issues/43115 as says in https://github.com/microsoft/vscode/issues/56180 Who read my issue was not careful to read what was written.

Cheers.

**Comment by deepak1556** [comment]
I am merging this to https://github.com/microsoft/vscode/issues/86224 which will contribute to memory savings.

**Comment by MichelDiz** [comment]
omg, what is wrong with Microsoft's engineers? Why don't they just take into account what was said in the issue? Why select a single concept and say "This will solve everything" or "Duplicate of something random I found here in the baklog"?

1 - Not just because a possible code refactoring or feature addition will be better than what I asked for in this issue. Who guarantees that e #86224 will be better than a "suspend"?

2 - The idea of suspending goes far beyond power management.

3 - #86224 looks more related to Windows. The same happens in Darwin?

This is the second ticket with the same topic that I open and you guys don't want to take the trouble to pay attention for what is written. If you don't want a "suspend", I will understand. But do not keep closing the issue with things that do not answer the question. Write "We won't do it" and I accept it, okay?

Cheer.
