### ISSUE TITLE
Fantastic software

### ISSUE THREAD

**Issue by spwebguy** [microsoft/vscode#86754]
Issue Type: <b>Performance Issue</b>

Hi team,

I've got no issues for you, I just want to let you know that this is the best f****** code editor I have ever worked with. I have tried a lot of them, during many years of coding (mostly PHP/JS) and Visual Studio Code is by far the fastest and easiest app to work with.

Huge thank you from France.

Gia-

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by RMacfarlane** [comment]
Thank you! ❤️
