### ISSUE TITLE
'Peek Error’ reference box doesn’t get closed automatically

### ISSUE THREAD

**Issue by mgimkal** [microsoft/vscode#86755]
monaco-editor npm version: 8.9.4
Browser: Chrome/Firefox/Internet explorer
OS: Windows 10

1. In the editor add some code which has syntax errors.
2. Highlight error -> click 'Peek Error' -> this shows red rows with error description.
3. Update code with correct syntax -> save -> redeploy.
4. We still see red rows though error is corrected.

 We have to close editor and open it again for red rows to vanish.

Regards,
Madhavi

**Comment by jrieken** [comment]
This is on purpose to prevent code jumping when typing. Having the error box and typing to fix an error below will likely change your viewport and that can disturbing. 

> We have to close editor and open it again for red rows to vanish.

Preesing ESC should close it, no need to close the editor
