### ISSUE TITLE
Local Typescript to be used by default (minor issue)

### ISSUE THREAD

**Issue by alexdrel** [Microsoft/vscode#8676]
- VSCode Version: 1.2.1
- OS Version: OSX 10.11

Although "typescript.tsdk" works fine it would be logical to make workspace local typescript to be used instead of VS code own copy.

Steps to Reproduce:
1. Remove all  typescript.tsdk overrides.
2. Open a workspace with typescript@next installed locally.
3. TS files has no TS version is present in the status line.
4. Add `"typescript.tsdk": "./node_modules/typescript/lib"` to the workspace settings.
5. Local TS is being used.

Thanks

**Comment by dbaeumer** [comment]
Makes sense to me.

**Comment by arciisine** [comment]
It would be really nice if it it could pick up the tsconfig options as well.  I specified the `typescript.tsdk` location but, with the new lib modules in 2.0, I would also need to be able to specify which features I'm targeting, e.g.: `lib.es2015.promise.d.ts, lib.es2016.d.ts` beyond the language level.

**Comment by dbaeumer** [comment]
VS Code now asks if you want to use a local install TS and persists it in the user settings. Pointing to a different tsconfig.json is not possible right now. A corresponding issue needs to be opened here: https://github.com/Microsoft/TypeScript/issues
