### ISSUE TITLE
"Generating Tags" process is noisy and disruptive.

### ISSUE THREAD

**Issue by gwk** [microsoft/vscode#86766]
Issue Type: <b>Bug</b>

I have a testing framework that creates symlinks in subdirectories of the `_build` directory. Recently, VSCode Insiders has started spontaneously opening the "OUTPUT" tab of the console tray, and spewing tons of warnings from "ctag". Here are the first few lines:

```
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> conda info --json
> conda info --json
> conda info --json
> conda info --json
> conda --version
> conda --version
> conda --version
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
Starting Jedi Python language engine.
----------Generating Tags----------
ctags --options=/Users/gwk/.vscode-insiders/extensions/ms-python.python-2019.12.53195-dev/resources/ctagOptions --languages=Python --exclude=**/site-packages/** -o /Users/gwk/work/muck/.vscode/tags .
> ctags --options=/Users/gwk/.vscode-insiders/extensions/ms-python.python-2019.12.53195-dev/resources/ctagOptions --languages=Python --exclude=**/site-packages/** -o ~/work/muck/.vscode/tags .
cwd: ~/work/muck
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/gloss/bin/python3 -c "import sys;print(sys.executable)"
ctags: Warning: cannot open source file "pithy/_build/test/svg/svg.py" : No such file or directory
...
```

Followed by many more warnings.

Additionally, I now see a `.vscode/tags` file getting generated in all of my projects, which I need to exclude in gitignore.

I am guessing this is a new feature being rolled out, and this is what I get for using Insiders. But, some honest feedback:
* The spontaneous switch to focus on the output pane is **very disruptive**.
* The new tags file is annoying (must be gitignored).
* When I search for text in my project, **I now get search results from the generated "tags" file**, which seems like something that nobody would ever want.
* Adding my `_build` directory to "files.exclude" setting does not fix the ctags warnings.
* It looks like the call to `ctags` takes an `--exclude` flag; should probably at least respect `files.exclude` setting, and at most be more aggressively populated.

Thank you, -George

VS Code version: Code - Insiders 1.41.0-insider (87c2e0be5d7359ce110c4c9ec9f6df71be996f8a, 2019-12-06T21:34:49.305Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (2.31GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
crafts|gwk|1.0.0
vscode-eslint|dba|1.9.1
vscode-dash|dee|2.3.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.9
macros|ged|1.2.1
gloss|gwk|1.0.0
vscode-settings-cycler|hoo|1.0.1
vsc-python-indent|Kev|1.8.1
legs|gwk|1.0.0
vscode-docker|ms-|0.9.0
python|ms-|2019.12.53195-dev
cpptools|ms-|0.26.2
debugger-for-chrome|msj|4.12.3
erlang|pgo|0.5.2
ploy|gwk|1.0.0
vscode-yaml|red|0.6.1
vscode-hexdump|sle|1.7.2
cython|tcw|0.1.0
pdf|tom|0.5.1
vscode-lldb|vad|1.4.3
change-case|wma|1.0.0
writeup|gwk|1.0.0

</details>

**Comment by gwk** [comment]
@vscodebot that is not a duplicate.

**Comment by gwk** [comment]
The output console pane continues to steal focus from the editor window every couple of minutes. This is making VSCode Insiders maddeningly unusable. I suggest you treat this as a high priority regression. In the meantime I will try switching to non-insiders.

**Comment by gwk** [comment]
I have managed to disable this with the setting `python.workspaceSymbols.enabled: false`.

**Comment by RMacfarlane** [comment]
@gwk Since this is caused by the Python extension, can you please reopen this issue here: https://github.com/Microsoft/vscode-python

**Comment by gwk** [comment]
@RMacfarlane thank you. filed at https://github.com/microsoft/vscode-python/issues/9046.

For what it's worth, I appreciate the personal note. In general I think the vscode team does not appreciate how off putting the bots are. Every time I encounter @vscodebot, it is after I have put at least an hour into filing a bug report, and it always feels like the humans on the other end don't care enough to read it. I understand the practical reason for using bots, but it has engendered some deep negative feelings about the vscode project for me. 

For one thing, if the bot can automatically close my issue, maybe it could automatically open it in the right place instead of just asking me to do more free work!

**Comment by RMacfarlane** [comment]
@gwk Thanks for the feedback! I agree that having the bot automatically transfer the issue would be a much better experience. I'll pass this on to the rest of the team.
