### ISSUE TITLE
Charmap or ASCII Map needed

### ISSUE THREAD

**Issue by ASopH** [microsoft/vscode#86760]
Issue Type: <b>Feature Request</b>

Unfortunately, there is no (extended) ASCII character table or the ability to use certain characters visually. Use in BAT / CMD / PS.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
If you're talking about the terminal you probably need to configure cmd/ps to use UTF-8 encoding.
