### ISSUE TITLE
API: Keep hover open until explicit focus out

### ISSUE THREAD

**Issue by JarrettSpiker** [microsoft/vscode#86767]
### Request:
Provide a way to open a hover which will keep the hover open until an explicit focus out.

### Motivation:
I am authoring an extension which force-opens hovers in the editor on certain user interactions (i.e. clicking on a TreeView element, or a command in a different hover).
This is accomplished easily enough moving the user's cursor to the appropriate range in the editor, and then executing:
`commands.executeCommand("editor.action.showHover")`

This works fine until the user moves their mouse: unless their cursor happens to be overtop of the newly-opened hover, the hover closes.
The user is unable to mouse over to the hover to interact with it, and unless they have very still hands the hover closes almost immediately.

It seems reasonable that if a hover has been programatically opened, it should be possible to keep it opened until the user focuses out (e.g. by clicking elsewhere, or hitting esc.)

Perhaps something like a `editor.action.showHover.focus` command, or adding an optional argument to `editor.action.showHover`?

**Comment by luispDesktop** [comment]
This would be beneficial for our extension. It makes it hard to try to read the content displayed in the hover while you have your hand on the mouse; especially when you need to scroll to reveal more of the content.
