### ISSUE TITLE
Clicking on List Widget triggers opening twice

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#86769]
- VSCode Version: Insiders
- OS Version: macOS

Run into this issue while registering another `editorOpenOverride`. The symptom is, when clicking an item in the file explorer, editor open event is emitted twice internally.

https://github.com/microsoft/vscode/blob/467a297f51fd11ba7a822b716dd20896912b50e6/src/vs/base/browser/ui/list/listWidget.ts#L616-L620

In above code, `list.setSelection` triggers `TreeResourceNavigator.onSelection`, which tries to open the resource the first time. And then `list.open` triggers another `TreeResourceNavigator.onSelection`. and leads to opening the resource the second time.

For list view users, if it tries to open source when a list item is being clicked, it needs to filter out the second opening event, which is kind of a hack.

**Comment by isidorn** [comment]
This is a list internal issue, not an explorer one. 
@rebornix please let me know if you are depending on this and if yes I can look into it while Joao is on vacation.

**Comment by rebornix** [comment]
@isidorn thanks! There is no hurry on it so we can't wait for Joao, I got ways to workaround it.

**Comment by joaomoreno** [comment]
@rebornix I deleted the deprecated `TreeResourceNavigator`, since no one was using it. I renamed `TreeResourceNavigator2` to `TreeResourceNavigator`. Can you use that and see if you still have an issue?

**Comment by rebornix** [comment]
@joaomoreno sorry for responding late, I'm still seeing the same duplication.

**Comment by joaomoreno** [comment]
Can you show me your code in a branch? :+1:

**Comment by joaomoreno** [comment]
@rebornix Let me know if this is still an issue.

**Comment by rebornix** [comment]
I didn't see any issue with it anymore. Closing it for now. Thanks!
