### ISSUE TITLE
Can't Download VS CODE for MAC

### ISSUE THREAD

**Issue by sujanrajs** [microsoft/vscode#86770]
Your connection is not private
Attackers might be trying to steal your information from go.microsoft.com (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by RMacfarlane** [comment]
@sujanrajs What download link are you clicking on?

**Comment by sujanrajs** [comment]
When I go to download page is https://code.visualstudio.com/download and when I click download for mac the new page is https://go.microsoft.com/fwlink/?LinkID=620882 but I can download using my my phone's personal hotspot but not from my home's wifi.

**Comment by sujanrajs** [comment]
The downloaded file is compressed file VSCode-darwin-stable.zip. I extract it and when I run it the alert says: “Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.This software needs to be updated. Contact the developer for more information."

**Comment by sujanrajs** [comment]
And I have allowed it from Security and Privacy, Preferences to open it that says, it is not from identified developers.
