### ISSUE TITLE
fs.stat on gitfs resources always returns size === 0

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#86776]
I'm trying to use `vscode.workspace.fs.stat` against a `gitfs` resource. However `stat` always returns a size of zero while `readFile` returns a non-zero buffer:

```ts
const stat = await vscode.workspace.fs.stat(resource);
const content = await vscode.workspace.fs.readFile(resource);
```

![Screen Shot 2019-12-11 at 3 14 16 PM](https://user-images.githubusercontent.com/12821956/70668722-2cdae000-1c29-11ea-92f0-c4553ff0a4d0.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
I was trying to use `fs.stat` in the image view to detect when a file is newly added vs when it is modified

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/86604

**Comment by eamodio** [comment]
I assume we are using `ls-tree` to get this data and we can include the flags to get the size as well.
