### ISSUE TITLE
Visual Studio Code opens off-screen with different scaling monitors

### ISSUE THREAD

**Issue by morl0048** [microsoft/vscode#86771]
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.I'm working on a laptop at home and have another screen to plug in via HDMI.
2.Place the visual studio code editor on my second screen.
3.Dock the editor on the left side of my second monitor to have my editor on the left and some web page on the right.
4.Save a file. (don't know if this is necessary)
5.Close the visual studio code editor.
6.Turn off my laptop while the second screen is still on.
7.Unplug the HDMI cable between my laptop and the second screen.
8.Launch my laptop.
9.Open the visual studio code editor.
10.The editor is shown completely off screen, showing the last file I edited/saved and I can't move it (since it's off screen).
11.I can manage to get a new window on my laptop screen by right clicking the pinned shortcut of visual studio code and selecting the "New Window" option.

I know this issue is the same as the #35148 issue, but I can't comment on there for some reason and it is still up to date but somehow closed.

See the point 11 of my steps to reproduce to see an easy quick fix.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by morl0048** [comment]
@bpasero I can confirm that it is still happening.

**Comment by bpasero** [comment]
@morl0048 I added some logging to our insiders build and will ask you to try it out once we have insiders running again tomorrow.

**Comment by morl0048** [comment]
@bpasero okay, just let me know when (:

**Comment by morl0048** [comment]
@bpasero  I don't know if this will be helpful, but here's a recording of my screen when the problem is happening. (I had to zip it to place it here)

You can see the visual studio code window "slide off" the screen.

[2019-12-12 06-13-01.zip](https://github.com/microsoft/vscode/files/3955418/2019-12-12.06-13-01.zip)

**Comment by bpasero** [comment]
@morl0048  Latest insider builds have a bit more logging around this (https://code.visualstudio.com/insiders/). When you run `code-insiders --verbose` from the command line, there are 3 things in the output that would help to diagnose this issue:
* `window#validateWindowState: 1 display { x: 0, y: 23, width: 2560, height: 1332 }` - this is the state to restore as we found it from the previous session
* `window#ctor: using window state { mode: 1, x: 0, y: 23, width: 2560, height: 1331 }` - this is the validated state from the previous session which will try to prevent putting the window outside the visible rectangle
* 
```
onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: {
      id: 'e3cdb405dff44ddaeb3d6c68dd167e33',
      configURIPath: 'file:///Users/bpasero/Development/Microsoft/vscode.code-workspace'
    },
    folder: undefined,
    backupPath: '/Users/bpasero/Library/Application Support/Code - ' +
      'Insiders/Backups/e3cdb405dff44ddaeb3d6c68dd167e33',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 0,
      y: 23,
      width: 2560,
      height: 1331
    }
  },
  lastPluginDevelopmentHostWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: undefined,
    remoteAuthority: undefined,
    uiState: { mode: 1, x: 384, y: 176, width: 1024, height: 768 }
  },
  openedWindows: []
}
``` 
- this is on shutdown the state we persist (which should match the state we get on the next startup)

Can you try when this happens to capture these values?

**Comment by bpasero** [comment]
Also: does it reproduce with our previous release (needs to be 1.40.1) from: https://az764295.vo.msecnd.net/stable/8795a9889db74563ddd43eb0a897a2384129a619/VSCode-win32-x64-1.40.1.zip

**Comment by morl0048** [comment]
```
[main 2019-12-13T20:10:16.110Z] window#validateWindowState: 1 display { x: 0, y: 0, width: 1920, height: 1040 }

[main 2019-12-13T20:10:16.110Z] window#ctor: using window state { mode: 1, x: 1920, y: 0, width: 960, height: 1040 }

[main 2019-12-13T20:12:47.169Z] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: 'c:\\Users\\morne\\AppData\\Roaming\\Code - Insiders\\Backups\\1576267600014',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 1920,
      y: 0,
      width: 960,
      height: 1040
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
```

**Comment by morl0048** [comment]
It is still happening with the previous release.

**Comment by bpasero** [comment]
@morl0048 how about version `1.39.2` before we updated to Electron 6: https://az764295.vo.msecnd.net/stable/6ab598523be7a800d7f3eb4d92d7ab9a66069390/VSCode-win32-x64-1.39.2.zip

**Comment by morl0048** [comment]
@bpasero still happening with

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
@morl0048 I added a bunch of more logging to this build [1] (which is also todays insider build so you can also just update) that you can see when running with the `--verbose` flag. 

Can you run it in a scenario where it appears off-screen and give me the output? Also would be helpful to learn what you did before-hand (I assume 2 monitors and then 1 unplugged).

[1] https://az764295.vo.msecnd.net/insider/2d2ac8f75b539d505443ac0733b196851c0b218d/VSCode-win32-x64-1.42.0-insider.zip

**Comment by morl0048** [comment]
@bpasero you can see the steps to reproduce in the first comment.

Just to be sure, here's the version:

Version: 1.42.0-insider (user setup)
Commit: 2d2ac8f75b539d505443ac0733b196851c0b218d
Date: 2019-12-16T12:09:59.453Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

and here are the log:

Here, when I have 2 monitors:

```
[main 2019-12-16T16:20:12.930Z] Starting VS Code
[main 2019-12-16T16:20:12.931Z] from: c:\Users\morne\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app
[main 2019-12-16T16:20:12.931Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false
}
[main 2019-12-16T16:20:12.933Z] Resolving machine identifier...
[main 2019-12-16T16:20:12.933Z] Resolved machine identifier: 0329a74f90c02a155aa8f8964a334e98cb5d3918ab5927ae0ab94685a48ba627 (trueMachineId: undefined)
[main 2019-12-16T16:20:12.947Z] update#setState idle
[main 2019-12-16T16:20:12.948Z] [storage state.vscdb] open(c:\Users\morne\AppData\Roaming\Code - Insiders\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2019-12-16T16:20:12.948Z] lifecycle (main): phase changed (value: 2)
[main 2019-12-16T16:20:12.949Z] windowsManager#open
[main 2019-12-16T16:20:12.950Z] window#validateWindowState: validating window state on 2 display(s) { mode: 1, x: 1920, y: 0, width: 960, height: 1040 }
[main 2019-12-16T16:20:12.951Z] window#validateWindowState: multi-monitor working area { x: 1920, y: 0, width: 1920, height: 1040 }
[main 2019-12-16T16:20:12.951Z] window#ctor: using window state { mode: 1, x: 1920, y: 0, width: 960, height: 1040 }
[main 2019-12-16T16:20:13.005Z] lifecycle (main): phase changed (value: 3)
[main 2019-12-16T16:20:13.007Z] telemetry/optInStatus { optIn: true }
[main 2019-12-16T16:20:13.022Z] telemetry/update:win32SetupTarget { target: 'user' }
[main 2019-12-16T16:20:13.023Z] telemetry/machineIdFallback { usingFallbackGuid: false }
[main 2019-12-16T16:20:13.104Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2019-12-16T16:20:13.104Z] [storage state.vscdb] getItems(): 30 rows
[main 2019-12-16T16:20:13.163Z] getShellEnvironment: running on Windows, skipping
[main 2019-12-16T16:20:13.206Z] [storage state.vscdb] updateItems(): insert(Map(2) {telemetry.lastSessionDate => Mon, 16 Dec 2019 16:19:40 GMT, telemetry.currentSessionDate => Mon, 16 Dec 2019 16:20:13 GMT}), delete(Set(0) {})
[main 2019-12-16T16:20:13.210Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2019-12-16T16:20:13.226Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('telemetry.lastSessionDate','Mon, 16 Dec 2019 16:19:40 GMT'),('telemetry.currentSessionDate','Mon, 16 Dec 2019 16:20:13 GMT')
[main 2019-12-16T16:20:13.231Z] [storage state.vscdb] Trace (event): END TRANSACTION
[main 2019-12-16T16:20:13.600Z] IPC#vscode-workbenchReady
[main 2019-12-16T16:20:16.356Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64-user/insider/2d2ac8f75b539d505443ac0733b196851c0b218d
```

And here when I unplug the second monitor:

```
[main 2019-12-16T16:15:43.791Z] Starting VS Code
[main 2019-12-16T16:15:43.792Z] from: c:\Users\morne\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app
[main 2019-12-16T16:15:43.794Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false
}
[main 2019-12-16T16:15:43.795Z] Resolving machine identifier...
[main 2019-12-16T16:15:43.795Z] Resolved machine identifier: 0329a74f90c02a155aa8f8964a334e98cb5d3918ab5927ae0ab94685a48ba627 (trueMachineId: undefined)
[main 2019-12-16T16:15:43.810Z] update#setState idle
[main 2019-12-16T16:15:43.810Z] [storage state.vscdb] open(c:\Users\morne\AppData\Roaming\Code - Insiders\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2019-12-16T16:15:43.811Z] lifecycle (main): phase changed (value: 2)
[main 2019-12-16T16:15:43.812Z] windowsManager#open
[main 2019-12-16T16:15:43.813Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 1920, y: 0, width: 960, height: 1040 }
[main 2019-12-16T16:15:43.813Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1920, height: 1040 }
[main 2019-12-16T16:15:43.814Z] window#ctor: using window state { mode: 1, x: 1920, y: 0, width: 960, height: 1040 }
[main 2019-12-16T16:15:43.854Z] lifecycle (main): phase changed (value: 3)
[main 2019-12-16T16:15:43.855Z] telemetry/optInStatus { optIn: true }
[main 2019-12-16T16:15:43.856Z] telemetry/update:win32SetupTarget { target: 'user' }
[main 2019-12-16T16:15:43.856Z] telemetry/machineIdFallback { usingFallbackGuid: false }
[main 2019-12-16T16:15:43.928Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2019-12-16T16:15:43.928Z] [storage state.vscdb] getItems(): 30 rows
[main 2019-12-16T16:15:43.985Z] getShellEnvironment: running on Windows, skipping
[main 2019-12-16T16:15:44.032Z] [storage state.vscdb] updateItems(): insert(Map(2) {telemetry.lastSessionDate => Mon, 16 Dec 2019 16:14:45 GMT, telemetry.currentSessionDate => Mon, 16 Dec 2019 16:15:43 GMT}), delete(Set(0) {})
[main 2019-12-16T16:15:44.034Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2019-12-16T16:15:44.035Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('telemetry.lastSessionDate','Mon, 16 Dec 2019 16:14:45 GMT'),('telemetry.currentSessionDate','Mon, 16 Dec 2019 16:15:43 GMT')
[main 2019-12-16T16:15:44.037Z] [storage state.vscdb] Trace (event): END TRANSACTION
[main 2019-12-16T16:15:44.370Z] IPC#vscode-workbenchReady
[main 2019-12-16T16:15:47.084Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64-user/insider/2d2ac8f75b539d505443ac0733b196851c0b218d
```

**Comment by bpasero** [comment]
Thanks I can tell the issue now: the window is positioned on `x: 1920px`. Our logic thinks that this is still within the bounds of the display and happily puts the window on that position. However, the entire monitor working area is just 1920px, so the window appears to be invisible.

This only seems to be an issue on Windows, as on macOS and Linux the OS seems to ensure that a window is always visible fully. 

I pushed a change to:
* allow a window to drop out of the monitor by 128px assuming that this is enough for the user to drag it back
* if the window is less than 128px visible either vertically or horizontally, it will be put to the far edge of that corner (i.e. becomes fully visible but close to the right or bottom edge where it was). 

Please give it a try in tomorrow's insider build and let me know how it goes.

**Comment by morl0048** [comment]
@bpasero It's working! Thank you guys for making the best editor there is even better! (:

**Comment by bpasero** [comment]
Great to hear and thanks for verifying.
