### ISSUE TITLE
Keyboard shortcuts not working with file opened

### ISSUE THREAD

**Issue by huyiqun** [microsoft/vscode#86787]
- VSCode Version: 1.41.0-insider
- OS Version: Windows 10

Many keyboard shortcut does not work when I have a file open:
![fileopen](https://user-images.githubusercontent.com/10877536/70674208-51e44880-1c53-11ea-817a-b65d22a35de3.gif)
which would work fine when there is no file open (or just peeking the file) or at the Welcome screen:
![nofileopen](https://user-images.githubusercontent.com/10877536/70674282-80faba00-1c53-11ea-9050-0ec9c4cc09c2.gif)

Steps to Reproduce:

1. Open any file by double click on it (does not happen when just peeking the file)
2. Use some keyboard shorcut: e.g. bring up the shortcut map by hitting Ctrl-k Ctrl-s

Does this issue occur when all extensions are disabled?: Yes

**Comment by tomaxsas** [comment]
for me only search in files does not open because same ctrl shift f is assigned to format document for some reason
