### ISSUE TITLE
Add ability to add a Panel through an extension

### ISSUE THREAD

**Issue by angerman** [microsoft/vscode#86789]
I'e been trying to figure out how to add a Panel to my extension. One that would sit next to the `PROBLEMS  OUTPUT   DEBUG CONSOLE   TERMINAL`. I'd like to provide a flamegraph like view for performance analysis. I seem to be unable to find any way to conribute either a custom view or hook into the Panel in any way?

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/41686
