### ISSUE TITLE
Visual Studio Code is displayed on another monitor

### ISSUE THREAD

**Issue by ch46** [microsoft/vscode#86784]
Hi!

I work in office with 2 monitors, and I guess I normally open VS Code in one monitor (identified as 1).  From home, I connect to my workstation at work (using Citrix), and I have only one monitor.  I can start VS Code, but I cannot see it.

Does VS Code not know there is only one monitor connected to my home computer?

**Comment by bpasero** [comment]
@ch46  Latest insider builds have a bit more logging around this (https://code.visualstudio.com/insiders/). When you run `code-insiders --verbose` from the command line, there are 3 things in the output that would help to diagnose this issue:
* `window#validateWindowState: 1 display { x: 0, y: 23, width: 2560, height: 1332 }` - this is the state to restore as we found it from the previous session
* `window#ctor: using window state { mode: 1, x: 0, y: 23, width: 2560, height: 1331 }` - this is the validated state from the previous session which will try to prevent putting the window outside the visible rectangle
* 
```
onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: {
      id: 'e3cdb405dff44ddaeb3d6c68dd167e33',
      configURIPath: 'file:///Users/bpasero/Development/Microsoft/vscode.code-workspace'
    },
    folder: undefined,
    backupPath: '/Users/bpasero/Library/Application Support/Code - ' +
      'Insiders/Backups/e3cdb405dff44ddaeb3d6c68dd167e33',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 0,
      y: 23,
      width: 2560,
      height: 1331
    }
  },
  lastPluginDevelopmentHostWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: undefined,
    remoteAuthority: undefined,
    uiState: { mode: 1, x: 384, y: 176, width: 1024, height: 768 }
  },
  openedWindows: []
}
``` 
- this is on shutdown the state we persist (which should match the state we get on the next startup)

Can you try when this happens to capture these values?

**Comment by bpasero** [comment]
Also: does it reproduce with our previous release (needs to be 1.40.1) from: https://az764295.vo.msecnd.net/stable/8795a9889db74563ddd43eb0a897a2384129a619/VSCode-win32-x64-1.40.1.zip

**Comment by ch46** [comment]
Benjamin :I will have to try it tomorrow in my office, as I cannot open VS Code now. Chang-Ping Hsiao 蕭長平On Dec 12, 2019 11:24 PM, Benjamin Pasero <notifications@github.com> wrote:Also: does it reproduce with our previous release (needs to be 1.40.1) from: https://az764295.vo.msecnd.net/stable/8795a9889db74563ddd43eb0a897a2384129a619/VSCode-win32-x64-1.40.1.zip

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


____________________________________________________________1 Cup of This Every Morning Melts Fattheflatbellyfix.comhttp://thirdpartyoffers.netzero.net/TGL3242/5df342a063ef442a020c5st01vuc

**Comment by ch46** [comment]
Benjamin :I will have to try it tomorrow in my office, as I cannot open VS Code now. Chang-Ping Hsiao 蕭長平On Dec 12, 2019 11:06 PM, Benjamin Pasero <notifications@github.com> wrote:@ch46  Latest insider builds have a bit more logging around this (https://code.visualstudio.com/insiders/). When you run code-insiders --verbose from the command line, there are 3 things in the output that would help to diagnose this issue:
window#validateWindowState: 1 display { x: 0, y: 23, width: 2560, height: 1332 } - this is the state to restore as we found it from the previous sessionwindow#ctor: using window state { mode: 1, x: 0, y: 23, width: 2560, height: 1331 } - this is the validated state from the previous session which will try to prevent putting the window outside the visible rectangle
onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: {
      id: 'e3cdb405dff44ddaeb3d6c68dd167e33',
      configURIPath: 'file:///Users/bpasero/Development/Microsoft/vscode.code-workspace'
    },
    folder: undefined,
    backupPath: '/Users/bpasero/Library/Application Support/Code - ' +
      'Insiders/Backups/e3cdb405dff44ddaeb3d6c68dd167e33',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 0,
      y: 23,
      width: 2560,
      height: 1331
    }
  },
  lastPluginDevelopmentHostWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: undefined,
    remoteAuthority: undefined,
    uiState: { mode: 1, x: 384, y: 176, width: 1024, height: 768 }
  },
  openedWindows: []
}

this is on shutdown the state we persist (which should match the state we get on the next startup)
Can you try when this happens to capture these values?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


____________________________________________________________Drink 1 Cup Before Bed, Watch Your Body Fat Melt Like Crazymedjournaltoday.comhttp://thirdpartyoffers.netzero.net/TGL3242/5df34289987e7428869b1st04vuc

**Comment by bpasero** [comment]
Ok thanks.

**Comment by ch46** [comment]
Benjamin: Attached are the output from VS Code 1.41.0 and 1.42.0-insider.I just installed VS Code Insiders 1.42.0 today, and I have not tested if it has the same monitor issue as VS Code 1.41.0 yet.  The attachments are for the versions on my office computer right now.  I will try it at home tonight if that will show differently. Chang-Ping

---------- Original Message ----------

**Comment by bpasero** [comment]
@ch46 how about version `1.39.2` before we updated to Electron 6: https://az764295.vo.msecnd.net/stable/6ab598523be7a800d7f3eb4d92d7ab9a66069390/VSCode-win32-x64-1.39.2.zip

**Comment by ch46** [comment]
Let me try that tomorrow. Thank you. Chang-Ping Hsiao 蕭長平On Dec 15, 2019 11:10 PM, Benjamin Pasero <notifications@github.com> wrote:@ch46 how about version 1.39.2 before we updated to Electron 6: https://az764295.vo.msecnd.net/stable/6ab598523be7a800d7f3eb4d92d7ab9a66069390/VSCode-win32-x64-1.39.2.zip

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


____________________________________________________________74 Year Old Grandma Shocks Doctors: Forget Botox, Do Thisremovethewrinkles.comhttp://thirdpartyoffers.netzero.net/TGL3242/5df72f792c2cb2f7823e1st01duc

**Comment by bpasero** [comment]
@ch46  I added a bunch of more logging to this build [1] (which is also todays insider build so you can also just update) that you can see when running with the `--verbose` flag. 

Can you run it in a scenario where it appears off-screen and give me the output? Also would be helpful to learn what you did before-hand (I assume 2 monitors and then 1 unplugged).

[1] https://az764295.vo.msecnd.net/insider/2d2ac8f75b539d505443ac0733b196851c0b218d/VSCode-win32-x64-1.42.0-insider.zip

**Comment by ch46** [comment]
Hi, Benjamin :I can surely try the new version, and no, the situation is, at work, I have dual monitors, but at home when I remote in using Citrix, I have only one monitor. Chang-Ping Hsiao 蕭長平On Dec 16, 2019 6:02 AM, Benjamin Pasero <notifications@github.com> wrote:@ch46  I added a bunch of more logging to this build [1] (which is also todays insider build so you can also just update) that you can see when running with the --verbose flag.
Can you run it in a scenario where it appears off-screen and give me the output? Also would be helpful to learn what you did before-hand (I assume 2 monitors and then 1 unplugged).
[1] https://az764295.vo.msecnd.net/insider/2d2ac8f75b539d505443ac0733b196851c0b218d/VSCode-win32-x64-1.42.0-insider.zip

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


____________________________________________________________1 Cup of This Every Morning Melts Fattheflatbellyfix.comhttp://thirdpartyoffers.netzero.net/TGL3242/5df7b38d7f6f1338c0da2st02duc

**Comment by bpasero** [comment]
@ch46 I am not sure what "Citrix" is. Is that a remote viewer that allows you to connect to the machine at work? And if that is the case, which monitor will be shown if you connect with 1 monitor? And is VSCode still running or do you start it fresh?

**Comment by ch46** [comment]
Citrix is a software allowing me to securely remote connect to my office computer. What I have been doing is opening VS Code fresh when I connect from home, because I always reboot my computer before I leave my office. I can also try to have VS Code open at work for me to check from home. Chang-Ping Hsiao 蕭長平On Dec 16, 2019 8:56 AM, Benjamin Pasero <notifications@github.com> wrote:@ch46 I am not sure what "Citrix" is. Is that a remote viewer that allows you to connect to the machine at work? And if that is the case, which monitor will be shown if you connect with 1 monitor? And is VSCode still running or do you start it fresh?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


____________________________________________________________Doctors Can't Believe She Used This To Erase Her Wrinklesremovethewrinkles.comhttp://thirdpartyoffers.netzero.net/TGL3242/5df7c052aade040510b44st04duc

**Comment by bpasero** [comment]
@ch46 got it. I have a feeling that possibly https://github.com/microsoft/vscode/issues/86771#issuecomment-566164705 could fix your issue as well. So when you try tomorrow please do it with the insiders build we release tomorrow.

**Comment by ch46** [comment]
Got you.  Thank you for the update., and I will try to convey all cases you posted to me and report back to you. Chang-Ping Hsiao 蕭長平On Dec 16, 2019 9:43 AM, Benjamin Pasero <notifications@github.com> wrote:@ch46 got it. I have a feeling that possibly #86771 (comment) could fix your issue as well. So when you try tomorrow please do it with the insiders build we release tomorrow.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


____________________________________________________________She's 46, But Looks 25. This Is What She Does Every Dayremovethewrinkles.comhttp://thirdpartyoffers.netzero.net/TGL3242/5df7c5deaf4ea45dd4cbast02duc

**Comment by ch46** [comment]
Benjamin :Thank you for the other ticket.  I think it behaves the same way for me. My office computer uses Intel® Iris® Graphics Control Panel to set the monitor VS Code opens in as the second screen. And because VS Code is opened in maximized mode, it must start its left border as the far left on the second screen and it of the first monitor's reach. I will simply try the new build tomorrow after its available. (When will that be, if you know?) Chang-Ping Hsiao 蕭長平On Dec 16, 2019 9:43 AM, Benjamin Pasero <notifications@github.com> wrote:@ch46 got it. I have a feeling that possibly #86771 (comment) could fix your issue as well. So when you try tomorrow please do it with the insiders build we release tomorrow.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


____________________________________________________________Do This Before Bed, Watch Your Belly Fat Melt Like Crazyfloraspring.comhttp://thirdpartyoffers.netzero.net/TGL3242/5df80d6d3f3e4d6b4370st01duc

**Comment by bpasero** [comment]
Sounds good.

**Comment by ch46** [comment]
Benjamin:

	Bad news.  I just tried VS Code 1.39, 1.40, 1.41 and 1.42-insiders, and all of them are working properly on both of my desktops at home.  I am not sure what happened to make them all work now.  The only things I did earlier today were to open each version on the 1st monitor at work in maximized windows, turned off the monitor and saw all versions opened in the 2nd monitor, and then turn on the first monitor and saw all versions open windows in the 1st monitor.  For some reason, this registered VS Code to open windows on my single monitor at home.

	I did get the daily build of 1.42-insiders, but for other versions I don’t think they get updated feature to check the last opened window’s location on the monitor(s).

	Do you need me to provide anything else?

Yours truly,

Chang-Ping Hsiao 蕭長平

**Comment by bpasero** [comment]
@ch46 I think this can be explained by the fact that you maximized the window. In that case we maximize the window on the display and I would assume the location does not matter. In other words this bug will only show itself for non-maximized windows.

I am going ahead and close this issue assuming my fixes for the other issue help.
