### ISSUE TITLE
PowerShell variables tab complete within double quotes

### ISSUE THREAD

**Issue by brentd09** [microsoft/vscode#86786]
**PowerShell Feature Request **

**Issue**
When using double quotes VSCode will not allow variables to be auto completed with the TAB key.

**Workaround**
Currently I am working around this issue by typing the code without the double quotes and then adding the double quotes after, this allows me to autocomplete the variable names. 

It would be great to have the ability to autocomplete the variable names without having to do this?

**Comment by brentd09** [comment]
The duplication bot has picked up an issue that is not related to mine!

**Comment by brentd09** [comment]
An example of this would be

`Write-Host "The data location is set to $DataLocation on the server $ServerHoldingData"`

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
