### ISSUE TITLE
CSS inside PHP breaks all highlights

### ISSUE THREAD

**Issue by Rah1x** [microsoft/vscode#86782]
- VSCode Version: 1.40.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. open a php file
2. write <style>bla bla bla </style>
3. everything after this looses its highlights

Image 1: Regular work without styles
Image 2: with <style> tag
Image 3: A trick I figured to bring back colour is adding comments at the end of styles.

![image](https://user-images.githubusercontent.com/841857/70671470-3e2af780-1cd0-11ea-9143-206ebaf1aaa4.png)

![image](https://user-images.githubusercontent.com/841857/70671486-4aaf5000-1cd0-11ea-8f8c-e0eb57897a3e.png)

![image](https://user-images.githubusercontent.com/841857/70671627-c4473e00-1cd0-11ea-9a71-850923c37464.png)

**Comment by roblourens** [comment]
Looks ok to me, can you try in 1.41 which we released today, and tell me which theme you're using? The `{{asset(...)}}` is a little messed up but I'm not sure about that css syntax?

![image](https://user-images.githubusercontent.com/323878/70763589-73077080-1d09-11ea-8e3e-92292c50817f.png)

**Comment by Rah1x** [comment]
hmm actually you are right its coming from the "asset()". this is from laravel blade. Also, the language used for the editor is Laravel Blade 

![image](https://user-images.githubusercontent.com/841857/70769794-0484ea00-1dbf-11ea-8972-80f784b220d9.png)

**Comment by Rah1x** [comment]
Actually its the same issue as this one:
https://github.com/microsoft/vscode/issues/86780

it looks like the issue is coming from Laravel Blade syntax highlighter extension 
https://marketplace.visualstudio.com/items?itemName=cjhowe7.laravel-blade

I will try to disable it but then will loose the highlighting of `blade`

**Comment by Rah1x** [comment]
Ok ive figured out the css issue. It was because of no quotes used in `background-url` (which is ok in general but I guess not ok for syntax highlighter of laravel). So if you do this instead it becomes fine again:

`
#bla {
background:url("{{asset('assets/images/del1.png')}}") center center;
}
`
