### ISSUE TITLE
Missing forward slashes in file path breadcrumb affecting behavior of breadcrumbs text and icon rendering

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#86791]
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-72-generic snap (Ubuntu 16.04.6 LTS)

Steps to Reproduce:

1. Open a Folder
2. Observe the breadcrumb at the top.

![](https://i.imgur.com/8p0De83.png)

3. Navigate to a very nested location.
4. Click on any of the folders in the breadcrumb to go up a few levels in the directory path.
5. Observe how it is broken.

![image](https://user-images.githubusercontent.com/6444116/70681104-33d51300-1c68-11ea-9657-2296bbeb795b.png))

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@tommai78101 The screenshots you've included are the file picker from Ubuntu, which we don't control
