### ISSUE TITLE
Windows keybindings on Linux

### ISSUE THREAD

**Issue by Matelasse** [microsoft/vscode#86797]
Hi. I wonder how this issue hasn't been opened up before, but to me it is a very important one that I haven't really figured out how to solve yet. I've been using vscode on windows for like past 2 years and now that I've grown fully accustomed to it the Linux keybindings are so different that I have become barely functional in Code. Can you please provide a way for us to force choose keys? I am not aware of any reason why the same Windows keybindings wouldn't work on Linux.

It seems that the following file is responsible for mappings, but that and windowsMapper.ts are different enough that I can't just replace the two.
https://github.com/microsoft/vscode/blob/98df43eb9020cef5bc7a480b51795998b14c3c0d/src/vs/workbench/services/keybinding/common/macLinuxKeyboardMapper.ts

You might not support Windows keybindings for Linux users by default or implement this feature request at all, but I really need some escape hatch here. What can I do?

**Comment by Matelasse** [comment]
@bpasero @alexdima @joaomoreno is there something that could be done about this? :cry:

**Comment by RMacfarlane** [comment]
@Matelasse Does using the command `Preferences: Open Default Keyboard Shortcuts (JSON)` on your Windows machine, coping the file, and then using `Preferences: Open Keyboard Shortcuts (JSON)` and pasting it on the Linux machine work?

**Comment by Matelasse** [comment]
@RMacfarlane Honestly I haven't tried that, but I'm sure it will not work, because some of the differences do not even show up in the json keyboard shortcuts, such as Mouse modifiers.

**Comment by Matelasse** [comment]
And also the JSON file only contains the shortcuts **you have set**. It does not contain the shortc uts that are set by default

**Comment by Matelasse** [comment]
Imho many developers jump around linux/windows **with the same keyboard**. I understand the differences for Mac and Windows because of different keys, but all my keycaps are exactly the same for Linux and Windows, so why does Code force this different behavior?

**Comment by RMacfarlane** [comment]
> And also the JSON file only contains the shortcuts you have set. It does not contain the shortcuts that are set by default (those are the ones that I'm reporting this issue for)

There are two separate commands. One will open the JSON of all of the default keybindings, and one opens the JSON of any custom keybindings you have on top of those

**Comment by Matelasse** [comment]
@RMacfarlane Thank you so much!!! That is actually what did it! Finally I can rest now, you don't realize how much you've helped me out.
