### ISSUE TITLE
Configuring the moduleIds property does not take effect

### ISSUE THREAD

**Issue by wlinglinux** [microsoft/vscode#86792]
- VSCode Version:
- OS Version:

Steps to Reproduce:

I looked at the configuration of webpack and said that you can set the optimization moduleIds property to compile, so that the packages configured in splitChunks will not change the hash value, but this property will not work after nuxt configuration, and the hash value will change every time you compile

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you specify how this is related to VS Code editor?
If it's related - provide exact steps to reproduce problem with the editor. If its question about your configs - please use StackOverflow
