### ISSUE TITLE
Insiders' Build: Tab scrolls page - does not insert a tab

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#86793]
See demo gif.  When I tab the page is scrolled, right off the screen.  I cannot actually insert a tab.

![tabs](https://user-images.githubusercontent.com/31813701/70681922-c5418680-1c62-11ea-945d-680a261bcd24.gif)

Version: 1.41.0-insider (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-10T21:44:16.632Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19037

(W10 -fast ring)

Steps to Reproduce:

1. Any file.
2. Press the tab key.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@ArtemGovorov I'm not able to reproduce this issue, does this happen when all extensions are disabled?

**Comment by ArturoDent** [comment]
Yes, I disabled all extensions prior to posting the issue.  Still happens - only in Insiders'.

**Comment by alexdima** [comment]
@ArturoDent I cannot reproduce. Have you tried commenting out your `settings.json` and your `keybindings.json`.

Pressing `Tab` works just fine for me:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/72449581-35d74800-37b9-11ea-9fdd-ba30d5710f15.gif)

**Comment by ArturoDent** [comment]
OMG, I had a keybinding only in Insider's for some reason messing with the `Tab` key - probably working on a SO question.  Sorry for the noise.
