### ISSUE TITLE
Emmet Wrap with Abreviation removes vertical bar character.

### ISSUE THREAD

**Issue by ivomachado** [Microsoft/vscode#8679]
- VSCode Version: 1.3.0-insider
- OS Version: Ubuntu 16.04
When I was developing a AngularJS 1.x application, the vertical bars used to represent a filter was missing after a wrap with abreviation.
Steps to Reproduce:

1. Open a HTML file and type something with a | character.
2. Select the code piece wich contains the character
3. Call the command Wrap With Abreviation

**Comment by mrmlnc** [comment]
I can reproduce on Windows with VS Code 1.3.0 (a2b9738a942237b59cb920940b93a0206f1b61d0).

**Comment by egamma** [comment]
TestCase

In this snippet:
```html
<span ng-bind-html='phone.connectivity.infrared | iconify'></span>
```

Place the cursor anywhere inside the span.

Run 'Wrap with Abbreviation' and enter a div.

Before the fix the `|` character inside the ng-bind-html attribute has been lost, i.e., turned into a snippet place holder.
