### ISSUE TITLE
Image embedding not working jupyter notebook

### ISSUE THREAD

**Issue by venkyyuvy** [microsoft/vscode#86795]
- VSCode Version:
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

- OS Version: Mojave

Steps to Reproduce:

 Not able to render the images in python Jupyter notebook
1. `![name](mrp1.png "Title")`
 
This works perfectly fine in browser, but renders as below in VS code. 

![image](https://user-images.githubusercontent.com/20812407/70683674-416eb500-1cc9-11ea-95c8-d63150dd0100.png)

**Comment by RMacfarlane** [comment]
Please open this issue on the Python extension: https://github.com/microsoft/vscode-python/issues
