### ISSUE TITLE
JavaScript intelligence isn't working

### ISSUE THREAD

**Issue by malipramod** [microsoft/vscode#86806]
JS intelligence isn't working for NodeJS, JS. Formatting not working asking to install formatter.

![intelligence](https://user-images.githubusercontent.com/13375870/70698257-15fdc180-1ced-11ea-94c3-b8f50fb56564.gif)

![format](https://user-images.githubusercontent.com/13375870/70698482-9a504480-1ced-11ea-9a3e-d93b6fe87864.gif)

Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by malipramod** [comment]
@mjbvz I tried on the latest VS Code insiders build and it works.
But doesn't work on 1.41.0 even all extensions disabled. Attaching files.

![all-plugin-disabled](https://user-images.githubusercontent.com/13375870/70743597-170f0d00-1d46-11ea-8ffe-bfca80d64438.gif)
 
![image](https://user-images.githubusercontent.com/13375870/70743615-24c49280-1d46-11ea-8e50-9f50602c88f5.png)

Thanks a lot! :)

**Comment by mjbvz** [comment]
The current insiders build is effectively the same as 1.41. If the problem only shows up in the stable release, the problem is likely caused by one of your extensions or a setting you have enabled

Can you manually trigger intellisense with `ctrl+space`?

**Comment by malipramod** [comment]
I tried `ctrl+space` but it gives all the things that I have typed before instead of intelligence. Attaching screen. All extensions are disabled. 

![Screen](https://user-images.githubusercontent.com/13375870/70744299-71f53400-1d47-11ea-9b5f-66b0efcbef86.gif)

I also tried reinstalling but the issue persists.

**Comment by malipramod** [comment]
> I tried `ctrl+space` but it gives all the things that I have typed before instead of intelligence. Attaching screen. All extensions are disabled.
> 
> ![Screen](https://user-images.githubusercontent.com/13375870/70744299-71f53400-1d47-11ea-9b5f-66b0efcbef86.gif)
> 
> I also tried reinstalling but the issue persists.

Also, reset all settings to its default.

**Comment by Ghojzilla** [comment]
There is probably a better solution to this, but I deleted this folder: **C:\Users\USER\AppData\Roaming\Code** 
and it started working again.

This is probably a sledge hammer to crack a nut approach but at least it worked :D

**Comment by malipramod** [comment]
> There is probably a better solution to this, but I deleted this folder: **C:\Users\USER\AppData\Roaming\Code**
> and it started working again.
> 
> This is probably a sledge hammer to crack a nut approach but at least it worked :D

Dirty approach but worked 😄 🔨 

@mjbvz closing this now!
