### ISSUE TITLE
Backtick is inserted when assigning shortcut to cmd+` (AZERTY)

### ISSUE THREAD

**Issue by ohemelaar** [microsoft/vscode#86809]
Issue Type: <b>Bug</b>

0. I opened two editor windows.
1. I mapped the following shortcut to have the same window switching shortcut as with the other apps I use:
```json
    {
        "key": "cmd+`",
        "command": "workbench.action.quickSwitchWindow",
        "when": "editorTextFocus"
    }
```
2. I used the previously defined shortcut to switch between two VSCode windows.
3. I observed that the shortcut worked (I switched windows), but the actual backtick character got inserted in the editor from which I switched (the first one I had focused). This litters my editors with backticks after every use.

I tested this on a QWERTY layout and it doesn't happen there, only with AZERTY.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.2.2
vsc-prolog|art|0.8.23
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.11.0
vscode-edit-csv|jan|0.2.5
expand-region|let|0.1.2
rainbow-csv|mec|1.3.1
python|ms-|2019.11.50794
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
vscode-jumpy|wma|0.3.1
material-theme|zhu|3.2.1

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Looks like a conflict between keybindings and IME.

**Comment by rebornix** [comment]
Thought about it again, this is as designed, currently IME always overrides keybindings.
