### ISSUE TITLE
I can see two terminal options in menubar

### ISSUE THREAD

**Issue by praveenkskochi** [microsoft/vscode#86803]
Issue Type: <b>Bug</b>

Don't have more details

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3328)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.62GB (4.53GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
go-coverage-viewer|def|1.0.3
githistory|don|0.4.11
gitlens|eam|10.2.0
git-graph|mhu|1.19.1
Go|ms-|0.11.9
material-icon-theme|PKi|3.9.2
gotestexplorer|pre|0.1.10
autoimport|ste|1.5.3
gitblame|wad|3.0.1

</details>

![image](https://user-images.githubusercontent.com/24299222/70696793-63c4fa80-1cea-11ea-8c0a-7d9351cf06c7.png)

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by praveenkskochi** [comment]
That i didn't check.

**Comment by sbatten** [comment]
@praveenkskochi can you try reproducing with extensions disabled?

**Comment by praveenkskochi** [comment]
I tried. Couldn't reproduce it.

**Comment by gjsjohnmurray** [comment]
Please enable your extensions one at a time to discover which one is causing the problem.

**Comment by praveenkskochi** [comment]
I think the issue is caused by the extension "Go Test Explorer" or "Go Coverage Viewer". Will update if i get more clarity.

**Comment by gjsjohnmurray** [comment]
Thanks for the update. Please open the issue with the developers of the troublesome extension and close this one. Ideally add a link to the other issue.

**Comment by praveenkskochi** [comment]
https://github.com/ppparihar/GoTestExplorer/issues/18
