### ISSUE TITLE
Panel-Problems could support much more flexible and intuitive filtering like IntelliJ...

### ISSUE THREAD

**Issue by dreaminplus** [microsoft/vscode#86818]
I am a linter enthusiast and a linter maker. So usually I am with panel-problems more. 

When using IntelliJ, I can filter the problems by severity/directory/rules(even combined query), what's more, it supports export/expand/etc. But when using vscode,  if the linter can detect a lot of problems and  we want to solve some types of problems firstly, I can't filter them easily. 

As far as I know, I can filter some by using the text match, but it cannot support combined-query friendly! Maybe I can create  a custom view to support this, but that's not a authentic way! Here do we have any plan to support this scenario?

**Comment by RMacfarlane** [comment]
@dreaminplus There's been some work on this this iteration, detailed here: https://github.com/microsoft/vscode/issues/47354

So filtering by severity will soon be available. You can currently filter by directory with the glob syntax, something like `src/vs/code/**` would filter to all problems under that folder. Can you describe in more detail if there is other filtering you'd like to see?

**Comment by dreaminplus** [comment]
moreInfo:
1. filter condition:
checker / severity / file / directory
2. others:
export/collapse/expand
previous/next (much more convenient: like intuitive arrow)

**Comment by sandy081** [comment]
Following filters are supported:

- By Severity
- Active file
- Considering files exclude
- Text and Glob based filtering

Moving this to backlog candidate for supporting other requests

**Comment by brbecker** [comment]
I'd like to be able to exclude problems based on matching text. Something like !text similar to the way that files can be excluded.
