### ISSUE TITLE
Opening url to browser passes incorrect URL

### ISSUE THREAD

**Issue by Hurtak** [microsoft/vscode#86815]
- VSCode Version: 1.40.2
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Have txt file with following url `https://example.com/jenkins/Test%20Deployments%2FHydra%20Environment`
2. Cmd click on it
3. 

The opened url in Chrome is
`https://example.com/jenkins/Test%20Deployments/Hydra%20Environment`
The clicked URL in txt is 
`https://example.com/jenkins/Test%20Deployments%2FHydra%20Environment`

**Comment by jrieken** [comment]
this has been fixed for 1.41
