### ISSUE TITLE
copyLinesDownAction works differently after the update

### ISSUE THREAD

**Issue by hyesung219** [microsoft/vscode#86816]
- VSCode Version: 1.40.2
- OS Version: windows10

Steps to Reproduce:

1. Before : weather the focus has focused or not it copies new line. 
![image](https://user-images.githubusercontent.com/43631109/70711442-e9659c00-1d24-11ea-8357-d166ef6d7122.png)

2. but it only copies where it focused.
![image](https://user-images.githubusercontent.com/43631109/70711393-cfc45480-1d24-11ea-97ac-e683474393b8.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
@hyesung219 I didn't reproduce this issue locally. Could you please provide more info about how to reproduce? A screen recording will be better.
