### ISSUE TITLE
VSCode window not responsive on startup, even with extensions disabled

### ISSUE THREAD

**Issue by looeee** [microsoft/vscode#86811]
On startup the window is non-reponsive. After 30 seconds or so a popup dialog comes up:

```
The window is no longer responding
You can reopen or close the window or keep waiting.
[Reopen] [Keep Waiting] [Close]
```

What I have tried:

1. starting with `code --verbose --disable-extensions`
2. deleting my workspace file so that there's no open docs or folders

No change from either of those. 

Here's the output from `code --verbose --disable-extensions`:

https://pastebin.com/mwzRjHbj

- VSCode Version: 1.40.2
- OS Version: Windows 10

**Comment by looeee** [comment]
I was able to get a responsive window by running `code --disable-restore-windows`

I've tested opening and closing a few times and it looks like this has fixed the issue.

**Comment by RMacfarlane** [comment]
Possibly related https://github.com/microsoft/vscode/issues/86633

**Comment by looeee** [comment]
I may have tracked down what causes this: 

I did a search/replace in around 1500 small files (all svg, <20kb). 
I then saw a spike in 'git for Windows' instances, and also 'console' instances nested under vscode in the windows task manager. These build over a couple is minutes until there was a combined total of >700 processes nested under vscode.

At this point the vscode window became unresponsive and I closed it from task manager. When I try to reopen I get the above error. 

I have done this two times with this result.

**Comment by bpasero** [comment]
@looeee so it does not reproduce anymore right? You once saw the git processes spike and then it was good?

**Comment by looeee** [comment]
> @looeee so it does not reproduce anymore right?

No, I can reproduce. I have figured out the steps:

1. Go here https://fontawesome.com/download
2. Download "free for web package"
3. Extract SVG folder and open in VSCode
4. Do a search and replace on all SVG files. There's 1556 files, all around 1-2kb

I used these values:

Search string: `<svg xmlns="`
Replace string: `<svg class="icon" role="img" aria-hidden="true" xmlns="`

5. Watch VSCode suffer a slow death over the next 5 minutes or so. 

I managed to snag this screenshot from the task manager. The processes here say 247, but it climbed slightly over 700. About half the processes are "console window host", the rest are "git for windows" (offscreen in this screenshot). Was kinda painful to capture this as my mouse was tracking at about 0.01 fps!

![tasks](https://user-images.githubusercontent.com/5307958/70784665-55471380-1dbc-11ea-887f-3fbae8961f56.jpg)

When I eventually managed to kill the VSCode process, about 200 of these windows popped up:

![process](https://user-images.githubusercontent.com/5307958/70785253-cf779800-1dbc-11ea-8c60-2605e3b9caf2.jpg)

**Comment by looeee** [comment]
Ha! I finally closed VSCode, and an "updating VSCode dialogue" popped up. I'm now on 1.41. 

Going through the whole sorry process again, the slow death of my system still happens. 

The only difference is that the console window hosts and git for window processes are no longer nested under VSCode:

![tasks_1 4 1](https://user-images.githubusercontent.com/5307958/70786480-56c60b00-1dbf-11ea-96ac-5b62306161c1.jpg)

However, the VSCode window is now responsive when I reopen 😁 

So, this has morphed into a report of a different bug. Apologies for that. Do you want me to close this and open a new issue? Or is it just a case of "don't search and replace 1500 files at once"?

**Comment by bpasero** [comment]
@looeee can you try to reproduce in a folder that is not under git control to see if these are all git processes?

**Comment by looeee** [comment]
Sure, I tested again by moving the svg folder to `D:/downloads` and running the same search/replace. 

My downloads folder is not under source control. However, behavior is exactly the same - hundreds of git for windows and console hosts processes spawn and my computer gradually crashes. 

Even after I kill VSCode stability doesn't really come back and I'm having to do a system restart nearly every time I test this.

**Comment by bpasero** [comment]
Weird. I just tried to reproduce on my Windows and cannot. Can you share your settings?

**Comment by looeee** [comment]
Sure, here you go:

https://pastebin.com/mXRcgi7u

git version 2.21.0.windows.1

Code version:

1.41.0
9579eda04fdb3a9bba2750f15193e5fafe16b959
x64

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by looeee** [comment]
> I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions

Hmm, that was the first thing I tested when I first had the original issue. 

But it seems like this "secondary" issue is caused by an extension. `code --disable-extensions` fixes it. 
I'll track down which extension tomorrow. 

Thanks for your support @bpasero .
