### ISSUE TITLE
When removing modfier, style is not updated

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86817]
From VScode master:

- Open `extensions/vscode-colorize-tests/test/semantic-test` as a folder in VSCode
- Note that `"class"` is not underlined'
- Change `"class"` to `"class.declaration": Now it is underlined
- Change back to `"class"`

BTW I added a output view for the Semantic test extension. There you can see that the tokens & modifiers are correctly reported.

You can set the Log Level to `Trace` and check the Log (window)
It turns out that after the last change, `"class"` is  requested but comes from the cache.

**Comment by alexdima** [comment]
@aeschli What do you mean that the style is not updated? Do you mean that you still see the underline? There is a known upstream bug in Chrome where they mess up underline rendering and do not repaint correctly. I've reported it at https://bugs.chromium.org/p/chromium/issues/detail?id=1012248

See https://github.com/microsoft/vscode/issues/48321 and https://github.com/microsoft/vscode/issues/76642
