### ISSUE TITLE
Add setting to make Git: Fetch (Prune) default behaviour for Git Fetch And Pull

### ISSUE THREAD

**Issue by tgoncuoglu** [microsoft/vscode#86813]
There have been some closed issues such as #78366 that are somewhat similar to this, but with a key difference: they assume local branch is not deleted. However, the problem is: when a remote branch is deleted and its local branch is deleted too, VSCode still does show **not-existing-anywhere** branches in branch checkout pull-down until Git: Fetch (Prune) is used. I have confirmed that those branches in checkout pulldown still persist after restarting vscode.

While this may indeed be about git itself, since `Git: Fetch (Prune)` has been implemented in vscode; my suggestion is that it is only natural to add an option in settings such as `git.pruneOnFetch: True` to append the `--prune` flag to git fetch and pull operations, making this default behaviour if user so chooses. This will avoid the need to run Git: Fetch (Prune) once in a while, and will have the benefit of keeping the checkout pulldown clean.

**Comment by joaomoreno** [comment]
Let's add a setting, but not have it enabled by default.

**Comment by tgoncuoglu** [comment]
Thank you very much !
