### ISSUE TITLE
copy doesn't work inside terminal when using tmux

### ISSUE THREAD

**Issue by ipstone** [microsoft/vscode#86829]
Hello,

In regular terminal applications (iTerm, or kitty, xterm), Alt(or shift) + mouse select, follow by C-c will copy the selected text to system clipboard. But I couldn't find a way to do the same in vscode terminal when running tmux.

Is there a way to enable this in vscode terminal? I searched and found one potential solution, but trying it, it doesn't work on my setup (mac os x 10.14.6 ) 10.14.6 https://github.com/microsoft/vscode/issues/24112

The terminal works with `screen`, but I still hope to get it to work with tmux.
Thanks for your suggestions/thoughts!

**Comment by Tyriar** [comment]
Not yet confirmed.

**Comment by iwittkau** [comment]
@ipstone have you tried the following setting?

```json
// Controls whether to force selection when using Option+click on macOS. 
// This will force a regular (line) selection and disallow the use of column selection mode. 
// This enables copying and pasting using the regular terminal selection, for example, 
// when mouse mode is enabled in tmux.
"terminal.integrated.macOptionClickForcesSelection": true,
``` 

This allows you to use option-click to select text in tumx' mouse-mode. The text stays selected after mouse-up and can be copied as usual.
