### ISSUE TITLE
The sidebar does not display icons that there are changes in the files

### ISSUE THREAD

**Issue by eboboshka** [microsoft/vscode#86821]
Issue Type: <b>Bug</b>

The sidebar does not display icons that there are changes in the files. The changes are no longer illuminated. However, in another window with another project everything works!

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.14.154-128.181.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (2 x 2299)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 2, 1|
|Memory (System)|7.79GB (0.82GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.11
gitlens|eam|10.2.0
json-tools|eri|1.0.2
jenkins-pipeline-linter-connector|jan|1.2.0
terraform|mau|1.4.0
vscode-docker|ms-|0.9.0
vscode-yaml|red|0.6.1
partial-diff|ryu|1.4.0
final-newline|sam|0.3.2
markdown-preview-enhanced|shd|0.5.0
jenkins-jack|tab|1.0.1
vscode-maven|vsc|0.20.0
vscode-icons|vsc|9.6.0

</details>

**Comment by RMacfarlane** [comment]
@eboboshka Can you provide some more details? What is displayed in the source control view when you click on it in the sidebar?

**Comment by eboboshka** [comment]
> @eboboshka Can you provide some more details? What is displayed in the source control view when you click on it in the sidebar?

![](https://i.imgur.com/2Gvs77D.png)

**Comment by joaomoreno** [comment]
Can you easily reproduce this? Can you give me exact steps?

**Comment by joaomoreno** [comment]
@jrieken I forget... I believe we fixed this right?

**Comment by eboboshka** [comment]
> Can you easily reproduce this? Can you give me exact steps?

I can still see that bug.

current version: 
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.14.158-129.185.amzn2.x86_64
```

**Comment by eboboshka** [comment]
The steps are difficult to describe as the bug only appears with one of the large repositories that includes Jenkinsfile, Dockerfile, Terraform, Java files, Maven and many more. You can see the list of installed plug-ins in the first message.

The project opens through a terminal:
`code -n projectdir/`

**Comment by joaomoreno** [comment]
> The steps are difficult to describe

Describe them any way, I can try to reproduce.
