### ISSUE TITLE
Launch.json is not working i.e., not able to debug c++

### ISSUE THREAD

**Issue by leopradeep** [microsoft/vscode#86820]
1. created hell world program in c++
2. created task.json as below
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "BuildHello",
            "type": "shell",
            "command": "clang++",
            "args": [
                "-std=c++17",
                "-stdlib=libc++",
                "helloworld.cpp",
                "-o",
                "helloworld.out",
                "--debug"
              ],
            "group":{
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher":"$gcc"
        }
    ]
}

3. created launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/helloworld.out",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
              }
        }
    ]
}

4. when i am clicking on "start debugging" it asking for me to create launch.json but after clicking on C++(GDB/LLDB), nothing happening.

**Comment by weinand** [comment]
Where did you create task.json and launch.json?

**Comment by leopradeep** [comment]
> Where did you create task.json and launch.json?

I created these file under .vscode present under my project WS

**Comment by weinand** [comment]
@leopradeep this is strange since VS Code only asks for creating a "launch.json" if it can't find one in the ".vscode" folder.

@isidorn any idea why this can happen?

**Comment by isidorn** [comment]
In theory this could happen if there are file events missing and the `configurationService` does not pick up the creation of `launch.json`. However this should go away after vs code gets restarted.
@leopradeep can you reproduce using vscode insiders https://code.visualstudio.com/insiders/

**Comment by leopradeep** [comment]
> In theory this could happen if there are file events missing and the `configurationService` does not pick up the creation of `launch.json`. However this should go away after vs code gets restarted.
> @leopradeep can you reproduce using vscode insiders https://code.visualstudio.com/insiders/

@isidorn is this insider is different from regular VS CODE?
How it Will help here?

**Comment by weinand** [comment]
@isidorn was this closed by accident?

**Comment by isidorn** [comment]
No. Should be filed against c++ https://github.com/microsoft/vscode-cpptools

**Comment by weinand** [comment]
I've removed the "need more info" and add a "caused-by-extension" label to make more clear why it was closed.
