### ISSUE TITLE
Jupyter server persists after VSCode is shut down

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode#86826]
- VSCode Version: 1.40.2
- OS Version: Debian Linux

Steps to Reproduce:

1. Open VSCode with Python extension, and open a ipynb file
2. Close VSCode
3. Check for Jupyter processes

After VSCode is shut down, any Jupyter server instances it has spun up while editing notebooks remains running. It must manually be killed from the command line.

**Comment by RMacfarlane** [comment]
@fonnesbeck Please reopen this issue on the Python extension: https://github.com/microsoft/vscode-python Thanks!
