### ISSUE TITLE
Ability to change the number of items stored in the recently used list

### ISSUE THREAD

**Issue by ishu3101** [Microsoft/vscode#8682]
Add a setting that would allow you to change the number of items stored in the `File -> Open Recent` recently used list in Visual Studio Code. By default it stores 10 folders and 10 files that you have recently used as seen in the source code [here](https://github.com/Microsoft/vscode/blob/f58289fdaf309c3ee2c45c41bf2486bfe5af25af/src/vs/code/electron-main/menus.ts#L47).

**Comment by reactivize** [comment]
I'd like this User Setting also.

My use case is this....
The recent files list is not of use to me so I would set it to 0
The recent folder list (thus projects) I would set to at least 20, because I work with a lot of smaller publishable projects.

Thanks!

**Comment by arendjr** [comment]
I'd like this too, but specifically for the amount of Recent projects shown on the Welcome screen. There it currently shows 5 recent projects, which is just too few for me.

**Comment by bpasero** [comment]
Note that there is a way to access a lot more recent files/folders via this command:

![image](https://user-images.githubusercontent.com/900690/30247885-76daeb76-961d-11e7-9e3b-c42cc79c816c.png)

**Comment by bpasero** [comment]
@ishu3101 did you try what I mentioned in https://github.com/Microsoft/vscode/issues/8682#issuecomment-328331565 ?

**Comment by bpasero** [comment]
Closing as per https://github.com/Microsoft/vscode/issues/8682#issuecomment-347092683
