### ISSUE TITLE
In an HTML document, HTML features disappear within <script> tags.   

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#86828]
In an HTML document HTML features† disappear within `<script>` tags.   
† features = intellisense, highlighting, emmet, auto matching tag editing

**simple use-case**
```
<script>
myElement.innerHTML = `<div class="Html-Features-Should-Still-Work-Here"> ${asJavascriptFeaturesDoHere} </div>` 
</script>
```

**possible solution**
Tag the backtick string, as follows: 
```
myElement.innerHTML = /* html */`<div class="commentTaggedTemplateLiteral"> ${ haveCakeAndEatToo } </div>` 
```
For example, see the extension "comment tagged templates," ([VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates)  / [Github](https://github.com/mjbvz/vscode-comment-tagged-templates) )
 which adds highlighting (no other features) based on the comment tags the backtick string, and supports multiple languages.  
Basically, instead of _switching_ to JS language features in <script> tags, it would be great to _add_ JS features without losing the HTML ones.  

Similarly, in a Javascript file, it would be nice to locally add HTML features where necessary.  

**current, clunky workaround**
For any complicated HTML, compose the HTML in a separate, "scratch.html" document in the editor, to get the features, then copy and paste into the template literal string, to get JS completion.  

I think anyone who does a lot of vanilla HTML/CSS/JS would benefit from this.  And, more generally, this would help for any time you're writing the code of one language as a string within another.  

- VSCode Version: Version: 1.41.0-insider
- OS Version: macOs 10.13.6
- Does this issue occur when all extensions are disabled?: Yes

**Comment by ultraGentle** [comment]
In response to the VSCode Bot, I don't believe this is a duplicate of #77977 (`<script type="text/html">`), because it's more generally about HTML features within template strings within regular <script> tags.

**Comment by octref** [comment]
@mjbvz @aeschli I'm not sure how we want to support this.

**Comment by octref** [comment]
This can be done by that extension. Please open a feature request there. Thanks!

**Comment by ultraGentle** [comment]
Okay, thanks for considering it!
