### ISSUE TITLE
Disabling hardware acceleration in argv.json does not work

### ISSUE THREAD

**Issue by vapoto** [microsoft/vscode#86827]
Issue Type: <b>Bug</b>

Setting the `disable-hardware-acceleration` flag to `true` in `argv.json` does not add the --disable-gpu flag to the process (see below). Manually running `code --disable-gpu` works fine. I noticed this issue because I have the "blank terminal" problem and setting the flag in argv.json did not help.

I am using the package from the Snap Store, but have tried the .deb package with the same result. This occurs on Ubuntu 18.04 in VirtualBox on a Windows 10 host.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Ubuntu 18.04 - Linux x64 5.0.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (10 x 2591)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 0|
|Memory (System)|10.74GB (4.72GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|100%|
</details>

**Comment by bpasero** [comment]
@vapoto I do not see an issue, you can see in your case `2d_canvas: unavailable_software` and in mine running with GPU enabled: `2d_canvas: enabled`

What else is missing?

**Comment by vapoto** [comment]
OK, I thought `--disable-gpu` should have appeared in `Process Argv`.

It seems that my problem of an empty terminal window might be caused by something else then. I just noticed that executing `code` from the terminal instead of the Gnome shortcut already solves the problem. So I assume it's related to something in the .desktop file.

**Comment by vapoto** [comment]
It seems #76542 was the actual problem, as setting `"terminal.integrated.inheritEnv": true` fixed it. You can close this issue.
