### ISSUE TITLE
Show the name of the file being deleted in the confirmation dialog

### ISSUE THREAD

**Issue by papb** [microsoft/vscode#86822]
![image](https://user-images.githubusercontent.com/20914054/70718815-b04f0c80-1ccf-11ea-9661-8c66386f80ec.png)

This confirmation dialog would be better if it included the name of the file being deleted.

**Comment by IllusionMH** [comment]
Looks like there is file name when file without changes is removed, but no filename when it has changes.
![image](https://user-images.githubusercontent.com/1312662/70731950-4c990380-1d10-11ea-927e-7c9eec9a8f75.png)

**Comment by papb** [comment]
Indeed, I just checked here as well.

**Comment by nbeentjes** [comment]
> Looks like there is file name when file without changes is removed, but no filename when it has changes.
To add to this, it is actually a bit more specific than that: it is doing this with _unsaved_ changes. Files where you have saved the changes but which are marked as "modified" or "changed" by the SCM are fine (you end up with the filename in the dialog).
That also means it narrows the possibilities of which file it is down to those that have unsaved changes (and thus will have the dirty marker in the tab if you have enabled it). I suppose you could consider this as a workaround.

I can also confirm this happens with the macOS version.
