### ISSUE TITLE
Settings sync sign in

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86836]
Possibly a couple issues here. 

I've been logged in to settings sync, but today there was a notification badge on the gear, and it says I'm not signed in.

* Should there be a notification prompting me to sign in? I might be signed out on purpose
* I am not sure why I'm not signed in today, I didn't sign out on purpose

Then I click "sign in" and it opens a browser. I closed the browser because I don't want to sign in right now. But now vscode is stuck in the "signing in" state: 

![image](https://user-images.githubusercontent.com/323878/70738590-e5f0f700-1cc9-11ea-8398-0b4df19b9d70.png)

even after reloading the window. I don't know how to sign in now, and there is no command for it in the command palette.

**Comment by roblourens** [comment]
Also I eventually got the notification "timeout waiting for code" with no explanation

**Comment by misolori** [comment]
The part about getting stuck in the sign in flow is the same as https://github.com/microsoft/vscode/issues/86284

**Comment by sandy081** [comment]
Yes this issue is similar to #86284. Hence marking duplicate.

> Should there be a notification prompting me to sign in? I might be signed out on purpose

Notification will be noisy. 

> I am not sure why I'm not signed in today, I didn't sign out on purpose

May be token got expired @RMacfarlane might know better.
