### ISSUE TITLE
Allow VSCode save files that need administrator permission.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#8683]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Allow VSCode save files that need administrator permission, similiar as with Notepad ++.
Currently VSCode show this message when trying to save the file.

![capturar5](https://cloud.githubusercontent.com/assets/19866231/16543131/e9ee25a6-409c-11e6-931f-9a59e7f1dd36.jpg)

This is the Notepad ++ message when you try to save the file.

![capturar3](https://cloud.githubusercontent.com/assets/19866231/16543133/1299492c-409d-11e6-903e-a17e2fcf0e91.jpg)

Suggested VSCode

![capturar7](https://cloud.githubusercontent.com/assets/19866231/16543134/21399284-409d-11e6-8581-c2d4d4ba0533.jpg)

Suggestion that the VSCode show when it is in Administrator mode as in Notepad ++.

![capturar4](https://cloud.githubusercontent.com/assets/19866231/16543135/2dae3204-409d-11e6-9725-785d76b72704.jpg)

![capturar6](https://cloud.githubusercontent.com/assets/19866231/16543144/5b19adb8-409d-11e6-8ac5-daf28c3ba935.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/1614
