### ISSUE TITLE
Search Result: Search Again (With Context) Doesn't Work

### ISSUE THREAD

**Issue by pltrant** [microsoft/vscode#86839]
Issue Type: <b>Bug</b>

The "Search Result: Search Again (With Context) Doesn't Work" command doesn't appear to work.  I perform a normal search (from the viewlet), then click to "Open in editor".  I then open the command palette to run the "Search Result: Search Again (With Context) Doesn't Work" command.  It prompts me for the number of lines, then I hit enter and nothing happens.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
vscode-markdownlint|Dav|0.32.0
gitlens|eam|10.2.0
code-eol|jef|1.0.11
gsl|pat|1.7.2
code-settings-sync|Sha|3.4.3

</details>

**Comment by JacksonKearl** [comment]
Duplicate of #86497?

**Comment by pltrant** [comment]
This would not be a duplicate of #86497.  I have no files open.

**Comment by JacksonKearl** [comment]
Is there anything logged to console? `Developer: Toggle Developer Tools`

**Comment by pltrant** [comment]
Nothing shows up in the console.  The only message is it connecting to the extension host.

**Comment by JacksonKearl** [comment]
Hm, do you get a `# ContextLines: ` entry in the header? 

![image](https://user-images.githubusercontent.com/8586769/70744276-3f5f2300-1cd6-11ea-81d9-f7a4c50d318a.png)


Also, can you jump to definition using F12/"go To Definition" from a search result line?

**Comment by pltrant** [comment]
There's no `# ContextLines` in the header.  It just shows the `Query` and `Flags`.  I can jump to/peek the definition of the matches.

**Comment by pltrant** [comment]
Actually, it's working now.  I may be that I wasn't waiting long enough before, since the second search doesn't show any progress (you just execute the command, wait, then it updates the window with the final results).  Thanks!

**Comment by JacksonKearl** [comment]
Ah okay, I was trying to get progress reporting to work for the preview but couldn't quite figure it out in time. We'll have it by the stable release (or stream results, a la. the viewlet)
