### ISSUE TITLE
cannot open authentication link in browser

### ISSUE THREAD

**Issue by githubfzq** [microsoft/vscode#86830]
- VSCode Version: 1.40.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. In command, I typed ">vs online: sign in", and enter.
![image](https://user-images.githubusercontent.com/19188149/70730433-e62bd980-1d3f-11ea-8812-9b37bd472598.png)

2. A notification indicated. 
![image](https://user-images.githubusercontent.com/19188149/70730601-415dcc00-1d40-11ea-8952-2cf96999189b.png)

3. After a while, vs code seems to try to open link in browser.
![image](https://user-images.githubusercontent.com/19188149/70730775-8eda3900-1d40-11ea-9375-bf532b7f744a.png)

4. But the page in browser is HTML code opened from local file, NOT a web page.
![image](https://user-images.githubusercontent.com/19188149/70730932-d4970180-1d40-11ea-9771-eb52271df4d5.png)

This issue occurs not only when signing into vscode online, but also whenever vscode try to open an external link. A cached page file with HTML source file is always opened.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
@githubfzq Can you please reopen this issue on the VSOnline extension here: https://github.com/MicrosoftDocs/vsonline Thank you!

**Comment by jkeech** [comment]
@RMacfarlane, this looks like an issue with VS Code rather than the VS Online extension. VS Online uses the `vscode.env.openExternal` API to open urls in the browser. From the original issue description, this is broader than just the VS Online extension (emphasis mine):

>This issue occurs not only when signing into vscode online, but also **whenever vscode try to open an external link**. A cached page file with HTML source file is always opened.
