### ISSUE TITLE
[rename on type] cursor should debounce

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86845]
Version: 1.41.0-insider
Commit: 455d8f73cd7c73285fba70ab039a26279f19bb57
Date: 2019-12-10T13:04:45.018Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-24-generic

- set '"html.trace.server": "verbose"
- open a HTML file with some content
- use keyboard to move cursor around
- observe that the HTML Language Server' gets a html/matchingTagPosition call per key press.

I think this needs to debounce, or previous calls need to be cancelled.

**Comment by octref** [comment]
Will consider this when doing #86845.
