### ISSUE TITLE
pull latest csharp.tmlanguage for fixes

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/vscode#86842]
A while ago I reported an issue regarding C# syntax highlighting breaking in certain conditions. This was determined to be an issue with the csharp-tmLanguage repo, and has now been fixed by this PR (https://github.com/dotnet/csharp-tmLanguage/pull/152) which was merged Nov. 6.

What needs to be done to get this updated in VSCode? I just updated to the latest 1.41 release and I'm still seeing this issue.

**Comment by alexr00** [comment]
I usually pull in grammar updates for the next release right after we release. If you download VS Code Insiders then you'll have the fix there.

**Comment by roa-nyx** [comment]
@alexr00 That's great to hear!

I wonder why it didn't get into 1.41, but if it's in insiders then I'm guessing it'll be out for the next release.
