### ISSUE TITLE
[jsx] Provide HTML tag matching

### ISSUE THREAD

**Issue by emzero** [Microsoft/vscode#8684]
HTML tag matching highlights all the tags of the same type in JSX instead of the corresponding one. 
Considering that code folding works fine, it seems that it's indeed properly recognizing the matching tag.

HTML syntax
![image](https://cloud.githubusercontent.com/assets/412489/16543186/68d865dc-409f-11e6-808c-9731fe2e6c08.png)

JavaScript/TypeScript React syntax
![image](https://cloud.githubusercontent.com/assets/412489/16543192/78abd4b2-409f-11e6-8b7e-1cfb025d3ea1.png)

**Comment by aeschli** [comment]
This would have to be added in symbol highlight support in the TypeScript language server.

**Comment by dbaeumer** [comment]
Moving to TS team since this is best implemented in the TS server / language server which has knowledge about jsx.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10138
