### ISSUE TITLE
Minimap is narrower and blurry

### ISSUE THREAD

**Issue by Eldaw** [microsoft/vscode#86841]
I've upgraded from v1.39.2 to v1.41.0 and I notice that the minimap has become narrower and the contents are blurry compared to previously.

Below is a comparison between between the two versions, where I've cropped the screenshots from each to exactly the same dimensions.

Version 1.39.2:
![image](https://user-images.githubusercontent.com/3789849/70743247-45292880-1d17-11ea-994d-2fad27c2c501.png)

Version 1.41.0:
![image](https://user-images.githubusercontent.com/3789849/70743265-4eb29080-1d17-11ea-9613-96bc88c57c84.png)

Running on Windows 10.

**Comment by connor4312** [comment]
The increased smoothness is intentional as a result of some improved sampling and rendering we're doing in the minimap as of v1.40--that's as designed. I'm thinking the slight decrease in width is due to the extra space for gutter decorations in 1.41 @RMacfarlane?

**Comment by RMacfarlane** [comment]
Yes, that's correct.
