### ISSUE TITLE
Mirror cursor makes calls for unrelated selection changes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86844]
Version: 1.41.0-insider
Commit: 455d8f73cd7c73285fba70ab039a26279f19bb57
Date: 2019-12-10T13:04:45.018Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-24-generic

- set '"html.trace.server": "verbose"
- open a HTML file with some content
- open the 'HTML Language Server' output, use mouse to set cursor to the end of the log
- use mouse to set cursor on a tag name in the HTML file
- observe that the HTML Language Server' output fills with html/matchingTagPosition calls

The problem is that the selection changes are also reported for the output view.
There needs to be a check here: https://github.com/microsoft/vscode/blob/19587ff1167011f6716ac384843874d3d6fb2754/extensions/html-language-features/client/src/mirrorCursor.ts#L53
That the event's textdocument is a HTML document

**Comment by octref** [comment]
Sorry, what exactly should I check for?

**Comment by aeschli** [comment]
Check whether `event.document` is a html document. Not only the active element can get selection events...

**Comment by octref** [comment]
I see. Clicking tags in editor triggers scrolling in the Output editor, which triggers the `onDidChangeTextEditorSelection` infinitely...
