### ISSUE TITLE
1.41 on Mojave washed out colors

### ISSUE THREAD

**Issue by MariuzM** [microsoft/vscode#86849]
Updated from 1.40.2 to 1.41 and noticed that colors are washed out. I remember that the same thing happened when i updated to 1.40 from the previous version but then it was fixed, don't remember if i edited something or not. But now this new version is causing same issues. 

Also in change log there was a mention about font rendering, i don't see any improvements. 
Edit: improved font rendering is for Windows and Linux only no Mac :( 

1.40.2
<img width="1440" alt="1 40 2" src="https://user-images.githubusercontent.com/36937039/70752495-a6a6c280-1d2a-11ea-93a1-a4e24a7c5811.png">

1.41
<img width="1440" alt="1 41" src="https://user-images.githubusercontent.com/36937039/70752513-b0302a80-1d2a-11ea-870d-fc4d3995bba8.png">

**Comment by MariuzM** [comment]
I've changed from false to true and it's fixed. But does it have to true? 

// argv.json
{
  "disable-color-correct-rendering": true
}

**Comment by dhowden** [comment]
@bpasero @deepak1556 I'm seeing this too.

1.40.2
<img width="1136" alt="Screen Shot 2019-12-13 at 11 48 36 am" src="https://user-images.githubusercontent.com/2822/70760716-a9db9600-1d9e-11ea-9071-4683b77933bf.png">

1.41
<img width="1136" alt="Screen Shot 2019-12-13 at 11 15 06 am" src="https://user-images.githubusercontent.com/2822/70760727-b102a400-1d9e-11ea-9d0f-2ba4cdf2c0a8.png">

**Comment by deepak1556** [comment]
@MariuzM yes `"disable-color-correct-rendering": true` is the correct configuration, @dhowden can you check if you have the right value for the `"disable-color-correct-rendering"`

**Comment by dhowden** [comment]
Yes, setting it to `true` fixed the problem.  It was set to `"active"` (which I believe was recommended for one of the previous issues).

**Comment by bpasero** [comment]
The only valid configuration is: `"disable-color-correct-rendering": true`

**Comment by MariuzM** [comment]
Just want to give some updates, today i have used i1Profiler to calibrate display, but today i have decided that in it's advance option instead using Matrix curve i will use Table. After calibration i have noticed that my screen has more contrast deeper blacks and I'm getting full black range wheres before with Matrix i was not. In other words lucks much nicer now. 

But with VSCode and `"disable-color-correct-rendering": true` the UI / Scrolling lags a lot. like 5fps or something. So ok then i changed this to False and walla smooth. Also colors look much better now with it being disabled. 

So this setting i feel looks into what ICC profile you have and either works with it great or not. So to utilise this setting properly you would need to have correct ICC profile (I'm assuming)
