### ISSUE TITLE
[html] Don't mark quoted strings as links

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#8685]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Problems with `src = "' '" and href = "' '"`

Can not find file.

Example: `<ng-include src = "'./view/template/header.html'"></ng-include>`

When using single quotes within double quotes.

Do not allow it to be considered link when something comes after the extension.

Example: `<script scr = "js/angular/angular.min.js?"></script>`
`<link rel = "stylesheet" href = "css/animate.css?"/>`

Similar as in Eclipse.

---Suggestion---

*I did not find these options in VSCode
- Open in a new tab when you click this link, as currently happens when we use with ".html"
- For when image, example: `<link rel = "shortcut icon" href = "img/ico.png">` or `<img src = "img/ico.png" />` have the option to choose whether you want to open with VSCode or my standard program.

In Eclipse, do not open a ".html" that is within the same folder (not considered link), when you put the full path. If possible do VSCode accept the way complete and short.

**Comment by bpasero** [comment]
@Tekbr is this about detecting links or what happens when you click a link?

**Comment by Tekbr** [comment]
@bpasero,  if I understand correctly, the situation mentioned can not consider link when I press Ctrl and move the mouse over the line.

> Do not allow it to be considered link when something comes after the extension.

> Example:

>  `<script scr = "js/angular/angular.min.js?"></script>`

> `<link rel = "stylesheet" href = "css/animate.css?"/>`

Now, about the rest, it is when I click on the link.

Example:

1- Take this situation: `<ng-include src = "'./view/template/header.html'"> </ng-include>`
2- Now click "Ctrl + Click left mouse button."
3- The VSCode not find the file.



On the suggestion to open pictures with the default program, you got any questions?

Any questions, just ask.

**Comment by bpasero** [comment]
Ok from the description I think we cannot open double quoted links from the editor. But I would also not assume to see a link in that case since that seems like a weird link to have.

**Comment by alexandrudima** [comment]
The link detection code for html now belongs to  @aeschli

**Comment by aeschli** [comment]
Technically, single quotes are valid characters in hrefs, see https://tools.ietf.org/html/rfc3986#section-2. We can't just ignore such links, but will optimistically unline them. It's the user's decision to open them (or not)

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@aeschli I think the translation was confusing ... besides that at the time I was a new user on Github. In addition to putting many suggestions in a single case. 😊 


Sure, since it's a link the same could point you to the correct path. Even if we are single quotation marks or not.

Which would lead to a new issue (I think 🤔 ), for VSCode to map, from where the folder opened by it is located.

1- It is possible?

2- And on the invalid link. Is it possible to block? (As in Eclipse)

**Comment by aeschli** [comment]
If a link is syntactically correct (and, surprisingly, `' '` is) we can't block it.
If it really exists we only know when we try to open the link. But at parse time we can't do that, it would be too expensive (and potentially make web requests).
