### ISSUE TITLE
Allow extra properties in .code-workspace files

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#86853]
I'm looking into using `.code-workspace` files for many projects in the same codebase. One thing that is blocking us right now is that we cannot add extra info or metadata to these JSONP files, because of this validation:

https://github.com/microsoft/vscode/blob/d832f86b04d6654f066c6489221b33d6c428ab62/src/vs/workbench/api/common/configurationExtensionPoint.ts#L318

The ability to add extra data in this file for our build system to use is crucial, as it will enable us to attach build/project settings to these workspaces, and make maintaining it much easier moving forward.

VSCode has been great in its extensibility model in other features, so here I propose adding another extension point `$metadata` to this file, where others can add whatever they want in that object:

```json
{
  "folders": [
  ],
  "settings: {
  },
  "$metadata": {
  }
}
```

* The name can be changed. `$metadata` is just a placeholder :) not sure about the convention in other places in VSCode.
* The new field is optional.
* Is a JSON `object`.
* Can contain arbitrary properties/fields.

I can submit a PR to change the validation in the file above, if the VSCode team approves.

**Comment by bpasero** [comment]
//cc @aeschli @sandy081 not sure why we would not relax this condition

**Comment by andekande** [comment]
Can't the same be achieved by moving custom properties into the _settings_ object ?
Something like "properties": { "build": { "propA": "value" } }

Then I would assume I can access them, for example in the _tasks_ section like ${settings:properties:build:propA}

Please clarify how your build scripts would access these properties. When you parse the file by yourself anyways, then why not put an additional config file next to the _.code-workspace_ which gives you full control over its syntax.

**Comment by sandy081** [comment]
settings object already accepts additional properties.
