### ISSUE TITLE
'Organize imports' should not change cursor position

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode#86851]
Issue Type: <b>Bug</b>

1. Enable 'Organize imports'
2. Import any module
3. Place cursor at the top
4. Save the file

Expected: Cursor position should not change
Result: Cursor position is changed to the line after the last import

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv|-psn_0_3945411|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
prettier-vscode|esb|3.11.0

</details>

**Comment by mjbvz** [comment]
@jrieken and @alexdima Assigning you for feedback. JS/TS implements organize imports with a workspace edit. However, that workspace edit always replaces the entire import block (even if they are already organized)

Isn't this case very similar to document format? Should JS/TS try to return a more minimal set of edits?

**Comment by jrieken** [comment]
> Should JS/TS try to return a more minimal set of edits?

Ideally, yes but for non trivial cases like equality this can be complex. I can try to hook this up with the `computeMoreMinimalEdits`-util that we already have. That would solve it for all code action providers and it runs on the worker, hence not block the extension host

**Comment by jrieken** [comment]
@mjbvz I have pushed 28a9dc95290846b774912ac86ea7775393bc7972 which makes sure that we call `computeMoreMinimalEdits` for textual changes that are performed with an editor (e.g we don't do this for textual changes for models that aren't open in an editor). Can you try with my changes? Generally, things should be better but there is no guarantee that the more minimal changes prevent this...

**Comment by jrieken** [comment]
@mjbvz Gave it a try and while edits are more minimal in general it doesn't work in this case so it's on TS now to create a better edit, e.g on replace edit instead of 10 with one being a replace and 9 being delete edits

**Comment by mjbvz** [comment]
Thanks @jrieken. TS always returns edits, even if the imports are fully sorted: https://github.com/microsoft/TypeScript/issues/22912. I'll let them know that returning more minimal edits is important in other cases too
