### ISSUE TITLE
Arrow up/down not switching python shell history

### ISSUE THREAD

**Issue by AntonGrekov** [microsoft/vscode#86859]
- VSCode Version: 
- OS Version: Windows 10
- Shell: Bash from WSL package

Steps to Reproduce:

1. Create .py file, select any interpeter you have(i tried 2.7, 3.6.6, 3.7.2)
2. Open terminal(bash or cmd) inside Visual Code Studio
3. Enter python interractive shell by typing `python`
4. Enter any random commands
5. Try to switch history with arrow up/down <- nothing scrolls in python shell

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by akaneoimo** [comment]
I have the same problem. A slight difference is that only when the integrated shell is bash will this happen, and I use anaconda.

OS: Windows 10
VS Code: 1.40.2
integrated shell: git-bash
python : Miniconda3

**Comment by AntonGrekov** [comment]
My shell is bash as well, sorry for forgetting to note it. I will change starting post

**Comment by Tyriar** [comment]
Works fine for me in both wsl and git bash. Can you run `ver` in cmd.exe and paste in the results?

**Comment by AntonGrekov** [comment]
ver gives me command not found, but running bash --version outputs:
****
GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
****

Checked same issue on another notebook with plain windows cmd - works fine.

**Comment by Tyriar** [comment]
@AntonGrekov open cmd.exe (conhost) and run ver, it will print version details for Windows.

**Comment by akaneoimo** [comment]
This is my Windows version:
> Microsoft Windows [Version 10.0.16299.15]

More details: 
1. git-bash version
> GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
2. open external git-bash with `Ctrl+Shift+C` from vscode, it works fine
3. both integrated and external cmd work fine

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by AntonGrekov** [comment]
````
C:\Users\XXX>ver
    Microsoft Windows [Version 10.0.16299.785]
````

I also noticed that this issue repeats not only with bash but with native windows cmd as well, steps to reproduce:
1. Open VSCode with no terminal.integrated.shell.windows set (leave it default to cmd)
2. Run python
3. Try to enter any commands and cycle them with Up/Down Arrows
4. Cycling Fails 

Cycling cmd commands works fine
