### ISSUE TITLE
save with formatting causes jump to end of document (again)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#86852]
Issue Type: <b>Bug</b>

Looks like #71707 has regressed.  Clicking CTRL+S in a JSON document causes the cursor to jump to the end.  Does not repro with F1 -> Save without formatting

Just started happening

VS Code version: Code - Insiders 1.41.0-insider (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-10T21:44:16.632Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.12GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
gitlens|eam|10.2.0
json-escaper|jos|1.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
package-json-dependencies-navigation|mam|0.1.8
capturesyntaxtokens|Mic|0.0.1
vscode-antlr4|mik|2.2.3
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
extension-manifest-editor|ms-|0.1.5
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.41.5
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
csharp|ms-|1.21.8
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
83861|msa|0.0.1
azurerm-vscode-tools|msa|0.8.2
json-parse-stringify|nex|1.0.2
vscode-json-editor|nic|0.2.3
vscode-yaml|red|0.6.1
vscode-sort-json|ric|1.18.0
scope-info|sie|0.2.0
tmcolor|sle|0.0.1
tmlanguage|Tog|0.9.0
sort-lines|Tyr|1.9.0
win-ca|uko|3.1.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by karsibali** [comment]
I am having same issue in an HTML file. All save operations jumps cursor to the end of file. Very annoying.

**Comment by alexdima** [comment]
@StephenWeatherford I cannot reproduce. Here is what I have tried:
* `settings.json`:
```json
 "editor.formatOnSave": true
```
* `test.json`:
```json
{ "this": ["is", "json"]}
```
* I click after `is` and type a character and save
* The cursor stays in the expected position:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/72447456-a8462900-37b5-11ea-980d-9bdac3ef7527.gif)

Does this reproduce for you when disabling all extensions?

**Comment by StephenWeatherford** [comment]
Can't repro anymore with Mac 1.41 stable or 1.42 insiders, will have to check work machine later.

**Comment by alexdima** [comment]
OK.

**Comment by StephenWeatherford** [comment]
Yeah, seems to be fixed again somehow.
