### ISSUE TITLE
The terminal shell "my folder" CWD does not exist

### ISSUE THREAD

**Issue by labnet7** [microsoft/vscode#86857]
Issue Type: <b>Bug</b>

New install of VS Code with Platform IO extension on Win10 with domain connected user account.
Create an ESP32 project from PIO

Try to build project.
> Executing task: C:\Users\me\\.platformio\penv\Scripts\platformio.exe run <
The terminal shell CWD "\\\DOMAINSERVER\RedirectedFolders\me\My Documents\PlatformIO\Projects\WAYO_CD" does not exist

launch.json had 
>"executable": "/DOMAINSERVER/RedirectedFolders/me/My Documents/PlatformIO/Projects/WAYO_CD/.pio/build/esp32dev/firmware.elf",
            "toolchainBinDir": "C:/Users/me/.platformio/packages/toolchain-xtensa32/bin",

I changed /DOMAINSERVER/RedirectedFolders to C:/me :no change
Tried setting terminal.integrated.cwd to c:\temp : no change
Disabled PIO :no change

I can't find where VSC is getting the  /DOMAINSERVER/RedirectedFolders/me from
* note DOMAINSERVER and me are redacted names.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.2
platformio-ide|pla|1.10.0

</details>

**Comment by SheepDomination** [comment]
I get the same error.

**Comment by Brolly0204** [comment]
I get the same error.

**Comment by SheepDomination** [comment]
Why is this, what is going wrong ?

**Comment by SheepDomination** [comment]
@Brolly0204 What extensions do you have installed ?
@weinand You wouldn't know what extension, since you closed the issue, it must be known what extension ?

**Comment by weinand** [comment]
The C++ extension "cpptools"

**Comment by labnet7** [comment]
Why do you say "cpptools" is the problem when the Executing task is C:\Users\me\.platformio\penv\Scripts\platformio.exe

**Comment by SheepDomination** [comment]
@weinand I don't even have that extension installed.

**Comment by weinand** [comment]
Then better explain what the error you are seeing is.

**Comment by SheepDomination** [comment]
As mentioned [here](https://github.com/microsoft/vscode/issues/87960).

**Comment by labnet7** [comment]
The PIO scripts are having problems with windows folder redirections for domain connected users.
A workaround for this problem is when using the PIO wizard to create a new project, untick 'Location' and specifiy a local non user file path such as "c:\pio\myapp"

**Comment by weinand** [comment]
@alexr00 is this a Task issue or an issue with the platformio-ide extension?

**Comment by SheepDomination** [comment]
@labnet7 Who are you directly replying to, anyone; or everyone ?

**Comment by labnet7** [comment]
I was replying to myself as the OP. The issue seems to be with platformio-ide not VS-code not being able to correctly parse domain based user folder redirects.
I've described a workaround since some others had said they had the same issue.

**Comment by alexr00** [comment]
@weinand based on @labnet7's response, this looks like an issue with the platformio-ide.
