### ISSUE TITLE
Cannot use ctrl+c to terminate execution in command prompt for many process

### ISSUE THREAD

**Issue by TQuy** [microsoft/vscode#86863]
Issue Type: <b>Bug</b>

I cannot use ctrl+c to terminate execution in many process, and ctrl+break fails, too.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.11
git-project-manager|fel|1.7.1
Python-autopep8|him|1.0.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
vscode-yaml|red|0.6.1

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by TQuy** [comment]
![image](https://user-images.githubusercontent.com/45731304/71608305-da02a180-2bb2-11ea-91ed-283139834bf0.png)

And below is the log file. 
[renderer1.log](https://github.com/microsoft/vscode/files/4011792/renderer1.log)

If I use window power shell, I can terminate the process by pressing Ctrl + Pause, but in the past I only needed to press Ctrl + c. In addition, Ctrl + C works fine in other computers

**Comment by Tyriar** [comment]
Can you check if this also happens in Windows Terminal? https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701

**Comment by TQuy** [comment]
I downloaded the window terminal from the link you provided and I can use Ctrl + c to terminate the running process

**Comment by TQuy** [comment]
I downloaded the window terminal from the link you gave me and it also doesn't work

**Comment by Tyriar** [comment]
@TQuy please report against https://github.com/microsoft/terminal then as we depend on a component from that project.
