### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by iwalkerr** [microsoft/vscode#86867]
Issue Type: <b>Feature Request</b>

笔记本：macos 15.2 ,用的zsh ,打开vscode,快捷键打开终端，顶部会出现"%"

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

**Comment by iwalkerr** [comment]
![Xnip2019-12-13_11-08-08](https://user-images.githubusercontent.com/43042929/70766511-e0aead80-1d98-11ea-8b42-984546aede9f.jpg)

**Comment by Tyriar** [comment]
See https://github.com/zeit/hyper/issues/3586, https://superuser.com/a/645612
