### ISSUE TITLE
Show tab index

### ISSUE THREAD

**Issue by longhaiqwe** [microsoft/vscode#86865]
We can navigate to a particular tab by using the keyboard shotcut `alt+number` (windows) or `number gt` with vscodevim plugin in Visual Studio Code. It's awesome!
But as I know, there is no way to show a tab's index in VS Code. Maybe I miss something?
I must count tabs first, then navigate to it.

Display a tab's index.

**Comment by Dimfred** [comment]
Is this still in plan?

**Comment by Dimfred** [comment]
Would it be possible to implement such behavior in form of an extension?
