### ISSUE TITLE
Add additional context to debug adapter `evaluateRequest` calls.

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#8686]
`DebugProtocol.EvaluateArguments` includes the `context` which can be `hover`, `watch`, or `repl`, but it would be helpful to (optionally) include additional context. In particular, for Clojure, the namespace in which the code is being evaluated is pertinent. A brute force way of passing on useful context would be to pass the text of the document in which the code is being executed if it is executed from a selection inside an editor. 

A more general approach would be to let an extension register a context generator function that gets passed the editor (to determine the selected text) and returns the `EvaluateArguments` object to be passed to the debug adapter. In this way the generator could limit the contextual information to only what is required (like the enclosing namespace in the case of Clojure). This would also allow the generator to expend the selection to an enclosing form, etc.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-debugadapter-node#137
