### ISSUE TITLE
Files Exclude desactivate/activate 

### ISSUE THREAD

**Issue by Pierre-Mike** [microsoft/vscode#86860]
I would love to have the possibility to deactivate/activate the File Exclude, 
 (node_module,__init__.py, __pycache)

it could be a Button or right-click
It will allow us to add more File exclude,
it will not be hard to see if the file is here or not and update it
interact with those file/directory 
thank you I hope is not a duplicate feature request

**Comment by RMacfarlane** [comment]
@Pierre-Mike In what context do you want this? When doing search? When opening files? For some cases, it's already possible to toggle whether or not to use file exclude
