### ISSUE TITLE
onDidChangeTextEditorSelection should fire on selection not on cursor movment

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#86871]
atm `onDidChangeTextEditorSelection` fires on each cursor movement not when u make a actual selection by either 
- mouse double click 
- mouse click & drag
- keyboard `shift+meta+direction` or `shift+direction`
> direction = up/down/right/left

### Env
```
Version: 1.41.0-insider
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-10T21:42:59.146Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

### Steps to Reproduce:

```js
vscode.window.onDidChangeTextEditorSelection((e) => console.log('selection', e))
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
This is as-designed, the primary cursor is part of selections. You can see this with 
```
	vscode.window.onDidChangeTextEditorSelection((e) => {
		console.log('selection', e);
		console.log(vscode.window.activeTextEditor?.selections);
	});
```

**Comment by ctf0** [comment]
i understand but this is far from ideal because in order for us to catch the user selection it means we need to check on each time the cursor move.

while it would be far more performant if we have an event that only fires when `editorHasSelection` has changed.

**Comment by RMacfarlane** [comment]
@alexdima @rebornix Can you comment on this? Do we have any recommendations about this?

**Comment by alexdima** [comment]
@ctf0 The current events works 100% as designed. 

It is designed to be a change event for the property `TextEditor.selections`.
```
/**
 * An [event](#Event) which fires when the selection in an editor has changed.
 */
export const onDidChangeTextEditorSelection: Event<TextEditorSelectionChangeEvent>;
```

This means it fires whenever that property changes, and that includes mouse double click, mouse click & drag and keyboard.

**Comment by ctf0** [comment]
@alexdima isnt `onDidChangeTextEditorSelection` is made specifically used for that ?

**Comment by alexdima** [comment]
@ctf0 I believe we have some communication barrier and I am afraid I don't understand what you mean. I am sorry I cannot help you further, but I can assure you the `onDidChangeTextEditorSelection` works correctly and as intended.
