### ISSUE TITLE
Color theme panel fails to open from setting button if a new color theme is installed

### ISSUE THREAD

**Issue by Eggiverse** [microsoft/vscode#86874]
- VSCode Version: 1.41
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Install a new color theme form Marketplace and enable it
2. Try opening color theme panel from setting button and it fails
3. Try opening color theme panel from menu it works

Bug is also reproduced in the latest insider version.

**Comment by gjsjohnmurray** [comment]
Are you viewing the release notes when this happens? If so, probably a duplicate of #75209

**Comment by Eggiverse** [comment]
@gjsjohnmurray I was not viewing release notes when I reproduced the issue. It seems the issue does not last for long. The panel can be opened after some time since I first tried.

**Comment by misolori** [comment]
Does this also happen when you have an extension preview open? If so then it is the same duplicate as John mentions.

**Comment by Eggiverse** [comment]
@misolori You are right. I will close this issue.
