### ISSUE TITLE
When opening a file containing Chinese, some text will become garbled.

### ISSUE THREAD

**Issue by cv0cv0** [microsoft/vscode#86875]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/18623780/70773161-a0a7f480-1db1-11ea-8737-3191a95de665.png">
重新打开后部分中文变成乱码。

**Comment by byyxx128** [comment]
1. Next time you need to describe in English.
2. Known issue.
#33720
#84503
#85480
Please vote the issues above.
***
中文版本
1. 下一次反馈问题必须讲英文，因为这个问题涉及到中文，我过来给你翻译一下。下次可没人管你……
2. 已知问题。给上面的问题点赞吧……因为点赞数达到一定程度VS Code的团队才会去处理……

**Comment by cv0cv0** [comment]
这都 2017 了，还没解决吗？我感觉是最近的 Bug，以前没遇到过。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "byyxx128"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 晚上6:06
收件人: "microsoft/vscode"<vscode@noreply.github.com&gt;; 
抄送: "Arete L"<linux2.0@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [microsoft/vscode] 包含中文的文件打开的时候部分文字会变成乱码。 (#86875)



 
Next time you need to describe in English.
 
Known issue.
 #33720
 #84503
 #85480
 Please vote the issues above.
  
 
中文版本
  
下一次反馈问题必须讲英文，因为这个问题涉及到中文，我过来给你翻译一下。下次可没人管你……
 
已知问题。给上面的问题点赞吧……因为点赞数达到一定程度VS Code的团队才会去处理……

**Comment by byyxx128** [comment]
Read this issue carefully #33720.
Everything you want to know has been interpreted in the comments.

**Comment by byyxx128** [comment]
1. Come to GitHub. Do not reply the email.
2. Please pay attention on these issue
#33720
#84503
#85480
especially the last one which would be the solution to this issue.
3. You can close you issue now. And focus on the issues above. Do not open more issues for this problem.

**Comment by rebornix** [comment]
@cv0cv0 sorry for reaching out late. Could you please share what's the encoding for this file ?

**Comment by byyxx128** [comment]
@rebornix #33720 #84503 #85480
I will reply to you there.

**Comment by rebornix** [comment]
Seems related to our encoding detection ;) Let's track it there.
