### ISSUE TITLE
Generate switch case for enum in typescript.

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#86879]
Maybe this is relate to typescript project.
see the `GenerateSwitchCases(EnumerationLiteral)` in https://docs.microsoft.com/en-us/visualstudio/ide/code-snippet-functions?view=vs-2019

I don't know this should be a codeaction, quickfix, refactoring or snippet.

**Comment by mjbvz** [comment]
Yes, please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) against the TypeScript project for this
