### ISSUE TITLE
Ubuntu repo broken

### ISSUE THREAD

**Issue by ginanjarn** [microsoft/vscode#86878]
Issue Type: <b>Bug</b>

Err:9 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages   
  File has unexpected size (156214 != 156065). Mirror sync in progress? [IP: 13.76.190.189 443]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics (4 x 1803)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 1, 1|
|Memory (System)|3.29GB (1.78GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.11.50794
Go|ms-|0.11.9

</details>

**Comment by CompassHXM** [comment]
Ubuntu 16.04, Linux 4.13.0-36-generic also comes across the similar problem, even after uninstall then reinstall using the downloaded deb:

"sudo apt update" shows:
> Err:15 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages                                                        
>   Writing more data than expected (1066720 > 1065578)
> Fetched 3,959 B in 6s (608 B/s)                                                                                                     
> Reading package lists... Done
> E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages  Writing more data than expected (1066720 > 1065578)
> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by peter279k** [comment]
I've same problem that @CompassHXM and @ginanjarn  mentions.

I think the key is mismatched and it should be fixed.
