### ISSUE TITLE
Two version of vs code  conflict

### ISSUE THREAD

**Issue by yang1626** [microsoft/vscode#86877]
1. Open a project with vs code,check the version of vs code is 1.41.0

vs code information:

Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

2.  Then I open another project with vs code,the version change to 1.40.1

vs code information:

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by yang1626** [comment]
I have Visual Studio Code - Insiders installed in my computer

Version: 1.42.0-insider (user setup)
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:57:35.999Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
Can you please uninstall all, make sure you remove all versions of Code, redownload and reinstall it?
