### ISSUE TITLE
Search: clicking on search view icon no longer puts focus into input box

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86883]
Steps to Reproduce:

1. click on "Search" icon in activity bar

=> 🐛 focus is not put into the input box anymore

**Comment by bpasero** [comment]
Hm, I think I can reproduce for any viewlet. @sbatten @isidorn maybe due to some recent refactorings?

**Comment by sandy081** [comment]
Looks like broken due to refactoring.

**Comment by isidorn** [comment]
@sbatten pushed a fix for this what seemed rational to me..

**Comment by sbatten** [comment]
thanks @isidorn LGTM, sorry about that
