### ISSUE TITLE
Remote SSH, CMake-Tools, Post-folder-open Error: connect ENOENT

### ISSUE THREAD

**Issue by vkryman** [microsoft/vscode#86888]
Many thanks for your efforts...

- VSCode Version: 1.40.2
- Remote-SSH 0.47.2
- CMake-Tools 1.2.3
- OS Version: Win7 -> SL 7.7

Steps to Reproduce:

1. Just open any project with CMakeLists.txt (root.cern.ch e.g.) remotely.
2. I do not see the issue on Centos 7.6 or 7.7

[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: connect ENOENT /tmp/cmake-server-0.3863942621475682 {"folder":{"uri":{"$mid":1,"fsPath":"/home/user/root","external":"file:///home/user/root","path":"/home/user/root","scheme":"file"},"name":"root","index":0}}

**Comment by RMacfarlane** [comment]
Hi @vkryman, I believe this is a problem with the CMake-Tools extension. Can you please open an issue there? https://github.com/microsoft/vscode-cmake-tools Thank you!
