### ISSUE TITLE
Peek Definition (ALT+F12) + ENTER - definitions stays open

### ISSUE THREAD

**Issue by 0ldF0x** [microsoft/vscode#86880]
When I go to definition, I use ALT+F12 to peek definition and then I used to simply hit ENTER to go to definition.
Things are changed in 1.41. Now after I hit ENTER, definition window stays open and I have to hit ESC to close it. It's very annoying. Is it possible to disable that?

**Comment by jrieken** [comment]
Yeah, that broke with reworking the code navigation - go to commands and peek commands are different here, eg enter in "go to" mode goes to a symbol, whereas in peek mode, peek stays for more peeking. 

I can add another command that's free for a user keybinding and/or I can make a rule that enter on a symbol that's already peek'ed ends peek whereas enter on anther symbol moves peek to that symbol.

**Comment by 0ldF0x** [comment]
That would be great, thanks.

**Comment by jrieken** [comment]
I have pushed a new `openReference` command that opens a reference and closes peek. Out of the box, there is no keybinding, this is how you add one; 

```
    {
        "key": "Enter",
        "command": "openReference",
        "when": "referenceSearchVisible && listFocus"
    }
```
