### ISSUE TITLE
Error update version 1.40 to 1.41 from apt

### ISSUE THREAD

**Issue by marcmorente** [microsoft/vscode#86887]
![imagen](https://user-images.githubusercontent.com/36136378/70784512-f2d51f80-1d89-11ea-987f-7cabb891b27b.png)

**Comment by ispirals** [comment]
Seems that the `InRelease` checksums do not correspond to the files in the repository. 

`InRelease` file content
![image](https://user-images.githubusercontent.com/51436060/70785795-88bd7a00-1d8b-11ea-8db2-be94ab2ddb74.png)

Repository files under `repos/vscode/dists/stable/main/binary-amd64/`
![image](https://user-images.githubusercontent.com/51436060/70785821-9246e200-1d8b-11ea-9175-a5495fa73d76.png)
