### ISSUE TITLE
the folders and files system not working as normal ! 

### ISSUE THREAD

**Issue by nalabdou** [microsoft/vscode#86897]
- VSCode Version: November 2019 (version 1.41)
- OS Version: Windows 10

Steps to Reproduce:

1. folders system 
2. files system
this is the issues 
![vscode](https://user-images.githubusercontent.com/46465503/70788976-5e22ef80-1d92-11ea-9493-9e22d6556622.png)

like normal this folders system must be in list like 

1. dist
     assets 
       css
         sass

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
Did you review this bit of the 1.41 release notes?

https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer
