### ISSUE TITLE
go back and go forward ignore continuous  movement

### ISSUE THREAD

**Issue by sworther** [microsoft/vscode#86890]
Is there an option to let `Go back` and `Go forward` ignore continuous movement, to work like the vim Ctrl-i,  Ctrl-o?
  
For example, 
    1. I jump to the definition of a function
    2. then move cursor to the next line several times, 
    
when I want to go back to the position where the function get called,  I have to `Go back` several times in the current implementation.
   
 Since using `Go back` to go to previous line or next line doesn't make much sence in most situation,  can we ignore continuous movement, so the `Go back` can be more convenient, or at least provide a disable option.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide details about your setup as specified by issue template?

Do you see every cursor position before or these are places where cursor was still for some time?

**Comment by sworther** [comment]
Sorry for the incomplete information,  After I follow the guideline,  I figure out It's the vim extension I installed change the go back and go forward behavior,  VSC just work as I expected,  Sorry for write an issue before I do a complete check again, I will close the issue
