### ISSUE TITLE
*.js files: Incorrect syntax highlight for returning local variables inside a function

### ISSUE THREAD

**Issue by IperStan** [microsoft/vscode#86899]
Version: 1.41.0 (system setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1.create a function in any place. Example
![image](https://user-images.githubusercontent.com/43338672/70791651-c6280480-1d97-11ea-975c-1802c3c37c71.png)

2. localVar is highlighted in white, as it should be.
3. now wrap localVar in parentheses and put the localVar in the following position:
![image](https://user-images.githubusercontent.com/43338672/70791688-d8a23e00-1d97-11ea-80f1-7b899a16a60e.png)

4. The localVar is now highlighted in orange and styled in italic.

It happens a lot when i need to return a boolean from a function with composed logic such as:
![image](https://user-images.githubusercontent.com/43338672/70791716-e657c380-1d97-11ea-9ad7-41c9e67bc63c.png)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/795 to track upstream
