### ISSUE TITLE
Allow projects to suggest extensions

### ISSUE THREAD

**Issue by vcsjones** [Microsoft/vscode#8689]
It would nice if a project had a way to advertise what extensions are required or helpful within the context of a project. Perhaps a new file in the `.vscode` directory that allowed listing extensions and versions. For example:

``` json
{
    "typescript": "~1.8.0",
    "tslint": "~0.5.32"
}
```

This will help people that are just getting started on a project understand what dependencies are required to use the project.

When opening the project, VS Code might say something like, "This project has recommended extensions. Would you like to review them?"

**Comment by Cram974** [comment]
I think that this is the same as if we had a thing like #347

**Comment by Telokis** [comment]
Isn't this issue closed by https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions?

**Comment by mjbvz** [comment]
Thanks @Telokis! Yes I think workspace recommended extensions covers this
