### ISSUE TITLE
MRU list contains some files but certainly not the last ones that I closed

### ISSUE THREAD

**Issue by par4dise** [microsoft/vscode#86892]
Issue Type: <b>Bug</b>

MRU list is never never up to date. I dont even know if and when I opened the files that it contains. If I close a file I'm sure it won't be listed, I have to find it back in my hard drive. Very annoying for such a simple feature.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
@par4dise which "MRU list" are you talking about
