### ISSUE TITLE
Download Update from inside editor itself

### ISSUE THREAD

**Issue by vk-sourcefuse** [microsoft/vscode#86894]
After clicking on 'Check for Update', it shows number (1) in the bottom-left icon of setting,, now if we again click on that icon, the last option in the submenu we see : "Download Update",

on clicking on that icon, it redirects to -
https://code.visualstudio.com/

I'm using UBUNTU (Linux), I think the same behavior is in all os versions.
Instead of redirecting to https://code.visualstudio.com/ , it should automatically start installing updated version, then a button/popup with option to 'restart vscode' will be helpful. 

![image](https://user-images.githubusercontent.com/30282624/70788690-6e00fa80-1db7-11ea-94bb-779cbc449f69.png)

**Comment by NotSqrt** [comment]
And if the number (1) could show up once the update is available on https://packages.microsoft.com/repos/vscode when installed through a package manager, that'd be nice !

**Comment by joaomoreno** [comment]
On Ubuntu, we recommend using Snap packages, which have auto update: https://twitter.com/joaomoreno/status/1112985658002468864
