### ISSUE TITLE
quickInput coloring not being respected for quickpick panel

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#86893]
ref: https://github.com/microsoft/vscode/issues/78989

### Env
```
Version: 1.42.0-insider
Commit: cbeff45f80213db0ddda2183170281ed97ed3b12
Date: 2019-12-13T07:05:12.353Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

### Steps to Reproduce:

1. set different colors for `sideBar` & `quickInput`
2. open `color theme picker` "uses sideBar coloring"
3. open `show all commands quick panel` "uses quickInput coloring"

- color theme picker
![Screen Shot 2019-12-13 at 11 02 23 AM](https://user-images.githubusercontent.com/7388088/70788139-e7d5bb80-1d98-11ea-9af1-3aaf3d3ad376.png)

- show all commands
![Screen Shot 2019-12-13 at 11 08 58 AM](https://user-images.githubusercontent.com/7388088/70788322-4f8c0680-1d99-11ea-8996-b86551b555df.png)

**Comment by ctf0** [comment]
@chrmarti is it possible to add different list styling for sidebar & quickinput instead of having the same for both ?

**Comment by chrmarti** [comment]
@ctf0 Not currently, please open a feature request if you would like to see this added.
