### ISSUE TITLE
html.mirrorCursorOnMatchingTag & html.autoClosingTags support for Vue.js SFC files

### ISSUE THREAD

**Issue by icleolion** [microsoft/vscode#86907]
If the `Auto Closing Tags` and `Mirror Cursor On Matching Tag` features supported the template block within a .vue file that would allow me to remove 2 extensions, `Auto Close Tag` and `Auto Rename Tag`.  The latter of which is currently suffering with performance issues for larger files.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/565
