### ISSUE TITLE
Aria alert not being read out on mac

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86905]
With latest insiders I see that aria.alert is sometimes not being read out by electron.
This is fixed with latest Eelctron 7. So just creating this for trasnparency.

How to easily repro an aria alert:
1. Create a new file in explroer, type something and then delete all content
2. You should get an aria alert how a name has to be provided

@bpasero also hit something like this for notifications

**Comment by deepak1556** [comment]
@isidorn can we close this ?

**Comment by isidorn** [comment]
Yes this works just fine now. Thanks a lot!
