### ISSUE TITLE
Extension details page content overflows when rendered side by side

### ISSUE THREAD

**Issue by HimekoEx** [microsoft/vscode#86909]
- VSCode Version: 1.41.0
- OS Version:Windows_NT x64 10.0.18363

Steps to Reproduce:

1. 打开Extensions页
2. 点击推荐插件
3. 将推荐插件的详细页向右拆分或者打开其他页面就会出bug

> Open Extensions page
Click on the recommended plugin
Splitting the detailed page of the recommended plugin to the right or opening other pages will cause a bug
![Snipaste_2019-12-13_20-30-45](https://user-images.githubusercontent.com/49508376/70800548-812bbe80-1de7-11ea-98c7-211ae532cb76.png)

**Comment by icleolion** [comment]
I’ve also seen it overflow when not in side by side view. I just had the terminal open below the extension pane and it overflowed just like in your image. This happened first time I opened the extensions pane after the update and have been  unable to reproduce since.
