### ISSUE TITLE
Unable to use intellisense because of 'Initializing js/ts language features'

### ISSUE THREAD

**Issue by HowardMed** [microsoft/vscode#86900]
- VSCode Version: 1.40.1
- OS Version: Windows 10

Steps to Reproduce:
1. Run VSCode with any angular project

Does this issue occur when all extensions are disabled?: Yes

I understand that the issue has been mentioned countless times but it has not been solved yet. I've waited and upgraded to the latest version of vsc every time just to see this bug fixed. For all I know this might not even be a bug and a feature which helps detect js/ts files and what not. But it runs every few minutes and runs for 30-60s every iteration, and I can't use intellisense or use F12(jump to method/class) because of it. I have to wait until the 'initializing js/ts...' message is gone. And honesty its too frustrating and infuriating at this point. Please get it fixed asap.
Thanks.

**Comment by gjsjohnmurray** [comment]
As of yesterday the latest version is 1.41 so please upgrade to that and see if the problem remains.

**Comment by mjbvz** [comment]
/needsMoreInfo

The reason this issue has been mentioned countless times is that it has countless possible root causes. We can only address new ones as they come in, never eliminate this warning entirely

**Comment by HowardMed** [comment]
> As of yesterday the latest version is 1.41 so please upgrade to that and see if the problem remains.

I upgraded to the latest version after your reply. And since then I haven't faced the issue anymore. Thanks, closing the issue.
