### ISSUE TITLE
代码不自动补全

### ISSUE THREAD

**Issue by shenjianbo** [microsoft/vscode#86908]
Issue Type: <b>Feature Request</b>

1. 在今天，2019年12月13日，好像vscode发生了一次更新，因为我发现当一个文件夹下只有一个文件夹的时候，它的显示方式和之前有所区别了，他会以[主文件/子文件]的形式来排列，当子文件夹大于1的时候，才会出现目录树，这有时候会让我很疑惑，甚至要在主文件创建一个新文件夹的时候，却不小心创建到了子文件夹里面，因为它是横排显示，的确不容易分辨它的高亮
2. 以前我的vscode会自动补全代码，现在，它任何提示都没有了，即使我已经输入过的东西也不会提示，我甚至尝试以重启我的电脑这种愚蠢的方式也无济于事，这让我的开发效率立刻降到低谷，我希望可以尽快得到解决，因为它以前真的很好用

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

**Comment by RMacfarlane** [comment]
@shenjianbo Please open issues in English, and please create one issue for each problem. For 1, you can change this behavior by turning off the "Explorer: Compact Folders" setting
