### ISSUE TITLE
Ability to ignore extensions to sync from UI

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86915]
Ability to ignore extensions to sync from UI

**Comment by misolori** [comment]
Here is the basic flow that I had in mind, we add a context menu item in the Settings UI and append the info to the title, like we do with workspace settings:

![gif](https://user-images.githubusercontent.com/35271042/71101437-8f713600-216b-11ea-9885-b8cbca17576c.gif)

cc @roblourens

**Comment by roblourens** [comment]
Yeah I like that but I think you want https://github.com/microsoft/vscode/issues/85208, I think this issue is for the same thing but for extensions.

**Comment by misolori** [comment]
@roblourens 🤦‍♂️ no wonder I already had this in my design file. Moving it over to there.

**Comment by misolori** [comment]
For ignoring extensions, my thought would be to also add this to the context menu in the viewlet + extension detail view:

![image](https://user-images.githubusercontent.com/35271042/71298536-70c29900-233d-11ea-9e72-9cfb8033a2f7.png)

And when ignore we append a badge, similar to when we disable an extension:

![image](https://user-images.githubusercontent.com/35271042/71298547-81730f00-233d-11ea-88a8-d00020a529b1.png)

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/74831394-70cb1f00-5315-11ea-95ef-ab09a4e728c8.png)

**Comment by sandy081** [comment]
Created a separate issue for tracking showing indication for ignored extensions and settings - https://github.com/microsoft/vscode/issues/90977
