### ISSUE TITLE
Sync extensions enablement

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86916]
Sync extensions enablement

**Comment by rickstaa** [comment]
It would be nice to incorporate settings/extension syncing directly into vscode. I am currently using the [code-settings-sync extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) to do this. Maybe you can incorperate this extension in the vscode framework or have it installed as a default extension.

**Comment by sandy081** [comment]
@rickstaa That's not the current strategy and also might not be correct because that extension is scoped to a backend. Our strategy is to provide settings sync feature with open ended backend.

**Comment by rickstaa** [comment]
@sandy That would be even better. Thanks a lot for the amazing product. Looking forward to test out this new feature.
