### ISSUE TITLE
Typscript & Javascript Language service couldn't started.

### ISSUE THREAD

**Issue by danjun-yor** [microsoft/vscode#86918]
Issue Type: <b>Bug</b>

I created project directory, and initialiezed npm. 
Next, installed typescript package `npm i typescript` and created tsconfig.json with no config.
And then when I entered "src/index.js", I got error popups.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 9|
|Memory (System)|16.00GB (3.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.2.0
prettier-vscode|esb|3.11.0
vscode-language-pack-ko|MS-|1.40.2
prisma|Pri|0.0.19
vscode-graphql|Pri|0.2.2
vscode-jsp|pth|0.0.3
spellchecker|swy|1.2.13
vscodeintellicode|Vis|1.2.0

</details>

**Comment by mjbvz** [comment]
What are the error popups? Can you share a screenshot

Also does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Noxillio** [comment]
I'm having this same exact issue, except I do not have TypeScript installed within my project.
![image](https://user-images.githubusercontent.com/40806092/72127518-f5ea0e00-333d-11ea-89f2-e9e267f2b109.png)
