### ISSUE TITLE
Files to Exlcude has stopped worked after last update

### ISSUE THREAD

**Issue by nicklepedde** [microsoft/vscode#86922]
Issue Type: <b>Bug</b>

Files to Exclude option in search is now completed ignored.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (12.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nicklepedde** [comment]
I discovered the issue. After upgrade the file path was using backslashes "\", and to get the exclude working I needed to use forward slashes "/". 

This should be either pointed out in release notes, or auto corrected upon updating.

**Comment by roblourens** [comment]
Can you give an example of a "files to exclude" pattern which worked in 1.40 but doesn't in 1.41? I think there was a preexisting issue there.

**Comment by nicklepedde** [comment]
here's my example of what used to work, and no longer does:
".\www\pub\js*"
after upgrade I had to chnage it to:
"./www/pub/js*"

Obviously not a big deal, but it stumped me for a bit after upgrade, what was wrong.

**Comment by roblourens** [comment]
Same as #87939 I think
