### ISSUE TITLE
YAML error markers off by one line

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#86928]
Issue Type: <b>Bug</b>

The backslashes need escaping, the error shows one line above:

```yaml
volumes:
  - "${PWD}/../..:${PWD}/../.."
command: "\([^ ]*\)"
```

![image](https://user-images.githubusercontent.com/9205389/70806998-dd2d1d80-1dbc-11ea-895f-b130802265f2.png)

VS Code version: Code - Insiders 1.41.0-insider (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-10T21:42:59.146Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (1.54GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.1.0
EditorConfig|Edi|0.14.3
tslint|eg2|1.0.44
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.13.0
rest-client|hum|0.23.0
solidity|Jua|0.0.64
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.94.0
remote-ssh-edit-nightly|ms-|2019.12.16800
remote-ssh-nightly|ms-|2019.12.16800
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
github-issues-prs|ms-|0.9.2
js-debug-nightly|ms-|2019.12.16803
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.6.1
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.13.0
ayu|tea|0.18.0
vscodeintellicode|Vis|1.2.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
@chrmarti You need to file this against the yaml extension that generates the diagnostic

**Comment by chrmarti** [comment]
Forgot I had a YAML extension installed. 😄 Filed: https://github.com/redhat-developer/vscode-yaml/issues/254
