### ISSUE TITLE
repository issues (Packages.bz2)

### ISSUE THREAD

**Issue by maravento** [microsoft/vscode#86925]
Ubuntu 18.04 x64
Repository: https://packages.microsoft.com/repos/vscode stable main
Problem: Failed to get https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2 The file has an unexpected size
![Captura de pantalla -2019-12-13 09-08-28](https://user-images.githubusercontent.com/14880802/70805998-4b0b2200-1d88-11ea-8035-e2d4d5e298bf.png)

**Comment by chrisgavin** [comment]
It looks like packages.microsoft.com is currently having issues. The same issue was reported for .NET Core at dotnet/core#3988.

**Comment by BrainStone** [comment]
Much rather: #86858

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/86858
