### ISSUE TITLE
GPG Signing keys fail to  validate

### ISSUE THREAD

**Issue by deelaka** [microsoft/vscode#86931]
On https://packages.microsoft.com/yumrepos/vscode/repodata/

The GPG keys have been failing to validate `repomd.xml.asc` with the `repomd.xml` file using Microsoft (Release signing) <gpgsecurity@microsoft.com> (EB3E 94AD BE12 29CF).

```
b9656aaa3b2141ca865c417b83075ff0  repomd.xml
2716a5c1d9db42b7b29affb04e045ec0  repomd.xml.asc
```

Thus I am unable to perform upgrades on my distro since the GPG check fails.

Quite recently also I filed a similar report:
https://github.com/microsoft/vscode/issues/82317

This issue happens on a regular occurrence thus could a solution be determined to ensure that a simple GPG check takes place before releases are made?

**Comment by RMacfarlane** [comment]
@deelaka I contacted our linux repo admin team about a different issue with our deb package and they have rolled back some changes that were impacting Microsoft repos. Can you confirm if that also resolved this?

**Comment by deelaka** [comment]
@RMacfarlane The issue is resolved, thanks!

Hope a solution could be determined to ensure basic GPG checks are automated on releasing, in order to catch such errors beforehand.
