### ISSUE TITLE
Debug Target drop-down too narrow

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/vscode#8693]
- VSCode Version: 1.2.1
- OS Version: Windows 10 14380

Steps to Reproduce:

1. Open .NET Core project
2. Hit View | Debug

Cannot see the full target name in the debug target drop-down:

![image](https://cloud.githubusercontent.com/assets/961950/16546788/dafffb32-410a-11e6-872b-c25e76b6d713.png)

Debug target field should be widened so the full debug target name can be displayed.

**Comment by isidorn** [comment]
This is a designed as the debug target drop down changes size corresponding to the viewlet

This was initiated by this user request #3027
Closing as designed

![launchdropdown](https://cloud.githubusercontent.com/assets/1926584/16553196/321706b0-41c7-11e6-8f9c-efdc395ac3a6.gif)

**Comment by bitcrazed** [comment]
@sisdorn - thanks for this info: However, to be fair, #3027 was referring to the fact that the play button got hidden - it was not asking to make the width of the debug target drop-down dependent on the width of the left-hand column. 

I do not think that I should have to sacrifice a significant amount of my available screen real-estate to the left hand column just to be able to read the name of the currently selected debug target.

**Comment by isidorn** [comment]
@bitcrazed fair enough, reopening

**Comment by bitcrazed** [comment]
@isidorn Many thanks. Obviously not a Pri0, but it'd be a nice fix next time someone revisits that area of code 😉
