### ISSUE TITLE
Show types in Intellisense during object initialization

### ISSUE THREAD

**Issue by fraser-lowndes** [microsoft/vscode#86938]
During object initialization, there is no hint for what type a property has which makes working with unfamilliar classes difficult. There should be an indication of the type of a property.

How it is now:
<img width="302" alt="Code_cBTUqCb3Lb" src="https://user-images.githubusercontent.com/12660705/70810949-9dfecc80-1dbc-11ea-8e19-41d4726227d8.png">

Proposed solution:
<img width="302" alt="Code_cBTUqCb3Lb_2" src="https://user-images.githubusercontent.com/12660705/70810962-a525da80-1dbc-11ea-8f52-3932a1b85458.png">

**Comment by mjbvz** [comment]
Please file this against the c# extension
