### ISSUE TITLE
\n plus optional space (0x20) matches \r\n in regex search

### ISSUE THREAD

**Issue by Simran-B** [microsoft/vscode#86935]
**Version**: 1.42.0-insider
**Commit**: cbeff45f80213db0ddda2183170281ed97ed3b12
**Date**: 2019-12-13T07:08:57.560Z
**Electron**: 6.1.5
**Chrome**: 76.0.3809.146
**Node.js**: 12.4.0
**V8**: 7.6.303.31-electron.0
**OS**: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create two files with the following content:
   ```
   text

       @foo
   ```
   That is, some text, two line breaks, four spaces, @ and some more text.
2. Make sure one of the files has CRLF line endings, and the other LF
   In a hex editor, it should look like this:
   - `74 65 78 74 0D 0A 0D 0A 20 20 20 20 40 66 6F 6F` (CRLF Windows line breaks)
   - `74 65 78 74 0A 0A 20 20 20 20 40 62 61 72` (LF Unix line breaks)
3. Open the folder the files are in as working folder
4. Open search (Ctrl+Shift+F), try below search phrases and observe which of the two files are matched:

   | # | Search | Matches |
   |:--|:--------|:----------|
   | 1 | `\r\n\r\n[ ]{4}@` | Windows ✔
   | 2 | `\n\n[ ]{4}@` | Unix ✔
   | 3 | `\n[ ]\n[ ]{4}@` | none ✔
   | 4 | `\n[ ]?\n[ ]{4}@` | both ⁉
   | 5 | `\n\n[ ]{4}@` | still both if match open in editor 😟

   Note: I use `[ ]{4}` here because GitHub would strip 3 of 4 literal spaces away. Both variants are functionally identical however.
5. While the search result of 1, 2 and 3 are as expected, 4 doesn't make any sense to me. Neither file has a space between the line breaks (confirmed by 3), but `[ ]?` which optionally allows a space makes it suddenly match the file with Windows line breaks despite a `\r` being in that position.
6. Bonus bug: Click on the Windows match to open it in the editor
7. Remove the `[ ]?` - both matches are still listed (I assume that this is because of the different behavior of find & replace in the editor, which does line break normalization?)
8. Click on the Unix match and close it in editor - both matches are still listed
9. The matches are only updated if the search phrase is changed once more, or if the refresh button is clicked

Does this issue occur when all extensions are disabled? Yes

![vscode line break bug](https://user-images.githubusercontent.com/7819991/70807443-d7840780-1dbd-11ea-8f27-96b4506716f0.gif)

**Comment by roblourens** [comment]
Thanks for the detailed report. So I actually try to normalize `\n` to match `\r?\n`, which is arguably unexpected but that is what people expect. Also the editor already normalizes newlines like this for search. But your example shows that this broke for two `\n\n` in a row.
