### ISSUE TITLE
File rename issues

### ISSUE THREAD

**Issue by jsknight1969** [microsoft/vscode#86934]
Issue Type: <b>Bug</b>

There is an issue with files staging to git after being renamed.

A.file renamed to B.file -> stages to git fine.

A.file rename to a.file -> does not stage to git.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.16299

**Comment by brunoventura** [comment]
Other rename issue

Issue Type: Bug

There is an issue with files when renaming, if you have unsaved updates on the file, the unsaved updates will be lost.

A.file is not saved
A.file renamed to B.file
B.file rolls back to the original A.file

Version: 1.37.1, (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: macOS mojave 10.14.5 (18F132)

**Comment by joaomoreno** [comment]
@jsknight1969 Can you reproduce using command line git as well?
