### ISSUE TITLE
Disable changing `this.` to `globalThis.` in VSCode Insiders

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#86930]
- VSCode Version: latest Insiders
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Just type `this.` on a new line anywhere inside Javascript file
2. Upon typing of `.`, the `this.` is auto-corrected to `globalThis.`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
As you start typing `thi` does the autosuggest list appear?

If yes, I assume `globalThis` is listed first, and `this` doesn't appear.

Where is `globalThis` coming from in your project?

Can you reproduce the issue if you launch a fresh VSCode with nothing open, then create a new .js file, then enter some code?

Also maybe worth knowing that when the autocomplete list is showing you can add an explanation panel to it by typing <kbd>Ctrl+/</kbd>

**Comment by mjbvz** [comment]
Also, did you perhaps disable keyword suggestions? Make sure `"editor.suggest.showKeywords": true` is set

**Comment by selfrefactor** [comment]
All good suggestions. I will be able to respond on Monday as this happens only on my job's machine.

**Comment by selfrefactor** [comment]
The issue was caused by this deprecated setting:

```
 "editor.suggest.filteredTypes": {
    "keyword": false
  },
```

removing it, fixed the problem and I will close the issue.
