### ISSUE TITLE
create Branch duplicate 'plus' icon

### ISSUE THREAD

**Issue by Lmzd** [microsoft/vscode#86932]
- VSCode Version: 1.41.0
- OS Version: Mac Os Catalina

Steps to Reproduce:

1. Click on your current branch name (bottom left action)
2. Dropdown open with all your git branches

<img width="671" alt="Capture d’écran 2019-12-13 à 15 34 36" src="https://user-images.githubusercontent.com/16925117/70807875-bf60b800-1dbe-11ea-9ca6-ab66e845b72c.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@Lmzd I'm having trouble reproducing this - did this only start happening with the update today?

**Comment by Lmzd** [comment]
Hi @RMacfarlane, this morning I could not reproduce this as well. I close this issue. Thanks
