### ISSUE TITLE
Peek definition missing

### ISSUE THREAD

**Issue by viveknangal** [microsoft/vscode#86945]
Issue Type: <b>Bug</b>

Hi team,
Peek definition not showing up in the right click while working on Golang language.

Please suggest whow to fix it.

Recently i have updated the "GOPATH" to my GO project and after that it stopped working

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|/private/var/folders/q5/0cpzy36s0tx5lqgyy3csq5f00000gp/T/AppTranslocation/73B1555F-6186-4C82-B0A6-2E8F49817F17/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform-autocomplete|erd|0.0.8
py-paste-indent|hye|0.1.2
terraform|mau|1.4.0
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
Go|ms-|0.11.9
material-icon-theme|PKi|3.9.2

</details>

**Comment by gjsjohnmurray** [comment]
You're on an 18 month old version (1.24.1). Any reason for not updating to the latest, which is 1.41 ?

**Comment by viveknangal** [comment]
oh is it,  didnt realise it because when I check for updates, following windows shows up saying "No updates available" . Do i need to uninstall & re-install the latest version. Pls suggest.

<img width="398" alt="Screen Shot 2019-12-13 at 10 32 15 PM" src="https://user-images.githubusercontent.com/5039071/70817983-c3113080-1df8-11ea-9303-156acf861eda.png">

**Comment by viveknangal** [comment]
@gjsjohnmurray thanks its working as expected after i updated the version
