### ISSUE TITLE
Layer breaker: should not reference monaco-workbench outside workbench

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86940]
![image](https://user-images.githubusercontent.com/900690/70811684-639a2d00-1dc6-11ea-8868-0f728dd8945b.png)

**Comment by sbatten** [comment]
updated all dialog references

**Comment by misolori** [comment]
✅ lightbulb
✅ find widget
✅ severity icons

@jrieken can you take a look at the [symbol icons](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/documentSymbols/media/symbol-icons.css), I wasn't able to find where the inline/block icons are used.

**Comment by jrieken** [comment]
Yeah, those symbol icons aren't needed anymore - they are from the pre-codicon-times. I'll nuke them.

**Comment by jrieken** [comment]
I think this is now done. Only references in the smoke tests are left ⬇️. Closing.

```
/Users/jrieken/Code/vscode/test/automation/src/application.ts
  142,35: 		await this.code.waitForElement('.monaco-workbench');
  145,40: 			await this.code.waitForTextContent('.monaco-workbench .statusbar-item[id="status.host"]', ' TestResolver');

/Users/jrieken/Code/vscode/test/automation/src/viewlet.ts
  13,39: 		await this.code.waitForTextContent('.monaco-workbench .part.sidebar > .title > .title-label > h2', undefined, fn);
```
