### ISSUE TITLE
Ranking of autocompleted CSS properties not working 

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [microsoft/vscode#86941]
- VSCode Version:
```
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

- VSCode Insiders Version:
```
Version: 1.42.0-insider
Commit: cbeff45f80213db0ddda2183170281ed97ed3b12
Date: 2019-12-13T07:05:12.353Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```
- OS Version: macOS 10.13.6 (17G7024)

Steps to Reproduce:

1. Open an empty css file
2. Type `wi`
3. `widows` suggestion from Emmet appears above all rest. 

I have also installed insiders version. Shouldn't emmet be ignored by default on a new installation? 

Does this issue occur when all extensions are disabled?: Yes. Is Emmet integration tighter that extensions?

**Comment by octref** [comment]
Yeah, our emmet is not so smart. I did close #86249, but I guess I should really find a solution...

**Comment by octref** [comment]
For now you can use "emmet.showExpandedAbbreviation": "never" or `"emmet.excludeLanguages: ["css"]`.

**Comment by octref** [comment]
Emmet expands `wi`, `wid`, `widt`, `width` all to `widows: ;` what the hell.

**Comment by octref** [comment]
I think it's better to just drop `widows` from the completion.

**Comment by octref** [comment]
The change: `widows: ;` will no longer be completed by emmet.

Emmet was designed when auto-completion-as-you-type experience doesn't exist, so it ended up with:

- `w` -> `width`
- `wid` -> `widows`

99.99% of the time, people type `wid` to look for `width`. If you are really looking for `widows`, CSS completion still has it. So I think it's fine to special-case it to remove it.

We might special-case other abbreviations in the future as well, depending on people's input.

Tab-to-expand with `"emmet.triggerExpansionOnTab": true` will continue to expand `wid`.
