### ISSUE TITLE
Distinguish mirror cursors in HTML files

### ISSUE THREAD

**Issue by abhnvkmr** [microsoft/vscode#86947]
Visual Studio Code 1.41 November update introduced mirror cursors in HTML files. I really love this feature which allows us to rename a tag without any command or third-party extensions. But when the cursor is at a tag, there is no distinction between the two cursors.

It's not an issue if I'm in an editing flow but coming back from a break or distraction, it's hard to know where the cursor will be when it gets out of the tag.

**Comment by octref** [comment]
Duplicate of #85630.
