### ISSUE TITLE
Extension Host terminated unexpectedly

### ISSUE THREAD

**Issue by Prasana1996** [microsoft/vscode#86943]
I installed VS code and tried to run java programs in it. Whenever i press F5 there is an pop up saying "EXTENSION HOST TERMINATED UNEXPECTEDLY". I am new to programming.

MY EXTENSIONS:
vscode-markdownlint | Dav | 0.32.0
-- | -- | --
javadebugger | don | 0.1.5
vscode-javac | geo | 0.2.31
python | ms- | 2019.11.50794
csharp | ms- | 1.21.8
java | red | 0.54.2
LiveServer | rit | 5.6.1
vscodeintellicode | Vis | 1.2.0
vscode-java-debug | vsc | 0.23.0
vscode-java-dependency | vsc | 0.6.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.22.0
vscode-maven | vsc | 0.20.0
commandlist | yam | 1.0.2

**Comment by RMacfarlane** [comment]
Hi @Prasana1996, it sounds like one of your extensions is causing the extension host to crash. Can you try disabling them one at a time to narrow down which one is causing the problem?
