### ISSUE TITLE
new default keybindings hijacked and not mentioned in release notes

### ISSUE THREAD

**Issue by ilovett** [microsoft/vscode#86949]
I believe I was using the defaults all along and didn't set these manually, but here are some examples:

`cmd d` used to `Add Selection To Next Find Match`, but now is overridden by `Duplicate Selection`  -- this one I understand as it's commonly used as "Duplicate" in other programs.

`cmd -` used to zoom out, but is now overridden by `Fold` code? -- this one doesnt seem right.

There doesn't seem to be any mention of these changes in the release notes.

This has been the most upsetting change by vscode as it's forcing me to go and re-learn keyboard shortcuts or manually set keybindings instead of using defaults.  I'm also just not sure if it's some extension or caused by the update due to the lack of mention.

**Comment by RMacfarlane** [comment]
@ilovett Can you run the command `Preferences: Open Keyboard Shortcuts` and search for those keybindings?
![Screen Shot 2019-12-13 at 11 43 51 AM](https://user-images.githubusercontent.com/3672607/70827324-dba02d00-1d9d-11ea-84eb-da12c848b3e1.png)

The update should not have added any conflicting keybindings, keybindings from extensions will also be listed here and have the extension name as the source

**Comment by IllusionMH** [comment]
AFAIK if [keymap](https://marketplace.visualstudio.com/search?target=VSCode&category=Keymaps&sortBy=Installs) extension is used then it will be shown as `Default` so only way to verify it for sure its editor - use `>Developer: Reload Window With Extensions Disabled` from Command palette.

I would guess that it might be [JetBrains IDE Keymap](https://marketplace.visualstudio.com/items?itemName=isudox.vscode-jetbrains-keybindings) extension that provides these actions for <kbd>Cmd</kbd>+<kbd>D</kbd> and <kbd>Cmd</kbd>+<kbd>-</kbd> shortcuts.

**Comment by ilovett** [comment]
Yeeearrrgh,  thank you @IllusionMH it ended up that I some how installed the IntelliJ IDEA Keybindings and I have no idea how.  Also this unfortunately coincided with the November update.

Apologies!  Closing this.

**Comment by IllusionMH** [comment]
Yay! Glad it solved the problem :)
