### ISSUE TITLE
Suggestions for Debug: Attach to Running Process

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#86946]
I frequently debug a (specific) running process using VS Code on Windows, remote debugging an already running C++ process on Linux.  I have a few related suggestions (and/or bugs) for launch.json, and the documentation of it:

1) In launch.json, I have "processId":"${command:pickProcess}", which works.  However, I also have the "program" setting specified (which the documentation says is "required" -- see #3), but the list of running processes that are displayed is never filtered to only show that "program".  So, this is my first suggestion: If a "program" is specified, filter the list to that program.  This could be done by starting the running program selection with the "program" text in the search box (related to #2).  Or, it could be done without the search box by simply limiting the list to those processes which match.

2) In the running program selection box, I am frequently typing the same thing (actually, different than my "program", because I am searching for a command-line parameter).  It would be nice if I could specify some default text search string in launch.json (that could override "program" if you also do #1).  I would still want to be able to edit the text, but this text could appear as the default/initial text in the search box.

3) The documentation on https://code.visualstudio.com/docs/cpp/launch-json-reference says that "program" is "required".  However, it does not appear to actually be required (at least in my scenario is actually ignored).

4) The documentation on https://code.visualstudio.com/docs/cpp/launch-json-reference lists "externalConsole" option.  However, A) The editor shows a yellow squiggly for it, and B) See https://github.com/microsoft/vscode-cpptools/issues/4592 where I found out that my debugger never actually attaches when that setting is present (after selecting the process to attach to).  Please update the documentation and also make the debugger still work if an invalid entry is present in launch.json (or at least report it in the notifications).

**Comment by weinand** [comment]
All C++ functionality is provides by the C/C++ extension. Please raise your issues there.
