### ISSUE TITLE
require admin privileges if the application is running from a regular user

### ISSUE THREAD

**Issue by harddownloader** [microsoft/vscode#86952]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by harddownloader** [comment]
https://prnt.sc/qahbtw

**Comment by harddownloader** [comment]
https://prnt.sc/qahbya
https://prnt.sc/qahc37
https://prnt.sc/qahc6l
https://prnt.sc/qahcac
etc...

**Comment by harddownloader** [comment]
ошибка 5: Отказано в доступе => error 5: Access denied

**Comment by harddownloader** [comment]
https://prnt.sc/qaha38
https://prnt.sc/qaha87
https://prnt.sc/qahabh
https://prnt.sc/qahaea
https://prnt.sc/qahahd
https://prnt.sc/qahajw
https://prnt.sc/qahanl
https://prnt.sc/qahar4
 etc...

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

**Comment by weinand** [comment]
Please provide reproducible steps and explanations in English.
