### ISSUE TITLE
Icons for submenu indicators are missing

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#86951]
Issue Type: <b>Bug</b>

With latest Insiders update arrow (chevrons) are missing for menu items that have submenu.
![image](https://user-images.githubusercontent.com/1312662/70819037-e11d6780-1ddd-11ea-8b34-a89573e54e7f.png)

I guess that this is regression introduced in https://github.com/microsoft/vscode/commit/5854f63f43c464dbf27c43a05c66948f6cd6f080

/cc @misolori 

VS Code version: Code - Insiders 1.42.0-insider (cbeff45f80213db0ddda2183170281ed97ed3b12, 2019-12-13T07:08:57.560Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Looks fine if I remove `font-size: 60%;`
```css
.monaco-workbench .monaco-menu .monaco-action-bar.vertical .submenu-indicator {
    /* font-size: 60%; */
    padding: 0 1.8em;
}
```

**Comment by misolori** [comment]
This must be a difference in the order of how our styles are bundles when building locally vs our builds (fyi @joaomoreno @bpasero). When I run this locally, the font size rules are above:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/70821928-2f584980-1d91-11ea-8693-4667f3bf186f.png" />

But when it's built the other styles have higher priority:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/70822001-5c0c6100-1d91-11ea-8d60-d94f36a7ee42.png"/>
