### ISSUE TITLE
Terminal TypeError on launch

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#86958]
![image](https://user-images.githubusercontent.com/6561887/70827831-ef985e80-1d9e-11ea-964f-bf48b1aa2665.png)

I believe to be caused by https://github.com/microsoft/vscode/commit/2cbd162c66150797066a88ba6283abf8827deb37 @sandy081

**Comment by sbatten** [comment]
fyi @Tyriar @sandy081

**Comment by sandy081** [comment]
Yes. Caused by my refactorings. Forgot to rename it here. Thanks for fixing.
