### ISSUE TITLE
"editor.action.insertSnippet" stopped working

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#86954]
was working perfectly pre v1.40

### Env
```
Version: 1.42.0-insider
Commit: cbeff45f80213db0ddda2183170281ed97ed3b12
Date: 2019-12-13T07:05:12.353Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. add to user shortcuts
```
{
    "key": "-",
    "command": "editor.action.insertSnippet",
    "when": "editorHasSelection && !inputFocus",
    "args": {
        "snippet": "-$TM_SELECTED_TEXT-"
    }
},
```

2. make a selection of something and press the shortcut key
3. the whole text will be replaced without maintaining the selection

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> the whole text will be replaced without maintaining the selection

That's expected given that the rule uses ` && !inputFocus`. Whenever you have blinking cursor then the `inputFocus` is set and for this rule it means disablement.

**Comment by jrieken** [comment]
btw - I see the same behaviour with 1.39

**Comment by ctf0** [comment]
isnt `inputFocus` means a **text input** or does it mean an input in general ?

**Comment by ctf0** [comment]
removing `&& !inputFocus` makes no difference 😢

**Comment by jrieken** [comment]
Good question... it seems yes, adding @bpasero how seems to manage that context key.

**Comment by bpasero** [comment]
This came in via https://github.com/microsoft/vscode/commit/234e2db9d7cb28bca2e07290b2b587bbea42b649#diff-44bbe916b3c1fe3cef283d2e70ff53e6 for https://github.com/microsoft/vscode/issues/39855. Leaving up to @joaomoreno to decide but I think this works still as it used to. 

I think if we want to exclude the editor from this check we would need to check for some well known properties of the editor. Though we are using editors in some cases also for input fields so this may be tricky to achieve.

**Comment by ctf0** [comment]
btw there are `inputFocus` & `textInputFocus` which are true whether there is an input field or not, not sure what each is for.

**Comment by bpasero** [comment]
We found out that this context key works as documented. Please check https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts for help with context keys.
