### ISSUE TITLE
Terminal "squashed"

### ISSUE THREAD

**Issue by byronferguson** [microsoft/vscode#86955]
Issue Type: <b>Bug</b>

I completed the update yesterday, and for some reason the zsh that I use for my default terminal is now "squashed" vertically.

What I mean by that is the line-height seems to be off, which causes the lines to overlap making them hard to read.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 2|
|Memory (System)|16.00GB (5.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|2.0.1
TabOut|alb|0.1.6
flutter-snippets|ale|2.0.0
expressjs|ama|2.0.0
jest-snippets|and|1.7.0
vscode-tailwindcss|bra|0.2.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
vscode-eslint|dba|1.9.1
vscode-coffeescript-preview|dre|1.0.1
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.3
docker-explorer|for|0.1.6
html-slim-scss-css-class-completion|gen|1.5.23
mysql-syntax|jak|1.3.1
vscode-gutter-preview|kis|0.24.2
vusion-peek|lin|0.1.2
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|0.9.0
vsliveshare|ms-|1.0.1377
debugger-for-chrome|msj|4.12.3
awesome-flutter-snippets|Nas|2.0.3
reload|nat|0.0.6
vetur|oct|0.22.6
vscode-jest|Ort|3.0.2
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.8.0
code-settings-sync|Sha|3.4.3
tech-debt-tracker|Ste|0.19.0
vscode-icons|vsc|9.6.0
vscode-todo-highlight|way|1.0.4
codedox|wig|1.3.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
markdown-pdf|yza|1.4.1

(4 theme extensions excluded)

</details>

**Comment by byronferguson** [comment]
[Screenshot](https://slack-files.com/T0D11T59P-FRNS786DT-aa79efa7fc)

**Comment by krupenja** [comment]
Interestingly, I did see this on the first launch of updated VSCode but cannot reproduce after restarting VSCode.

**Comment by krupenja** [comment]
OK, now able to repro this consistently:

1. Start VSCOde.
2. Enable `"terminal.integrated.rendererType": "experimentalWebgl"`
3. Restart VSCode.
4. Open VSCode terminal.
5. Type a command which prints something with a background colour, e.g. `'\e[48;2;0;0;0m Background color: black\n`

To work around this, disable `"terminal.integrated.rendererType": "experimentalWebgl"` and restart VSCode.

**Comment by byronferguson** [comment]
I did turn that feature on with this last update. However, I have now tried using the `dom` and the `canvas` options with the same results. The leading above the row is still off, which produces this is un-centered text on the background.

Thank you

**Comment by krupenja** [comment]
Hmm, interesting. You did restart VSCode after disabling `"terminal.integrated.rendererType": "experimentalWebgl"`?

**Comment by byronferguson** [comment]
Yes. I did. 

Byron Ferguson

**Comment by singularitti** [comment]
Same issue here. And I can see that the characters inside the cursor are a bit lower than normal characters.
![1](https://user-images.githubusercontent.com/25192197/71043412-8b59ff80-20fc-11ea-8991-18a37562e512.png)
![2](https://user-images.githubusercontent.com/25192197/71043275-27373b80-20fc-11ea-8407-57010f4ad7c9.png)

```
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

```json
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "terminal.integrated.rendererType": "experimentalWebgl",
  "editor.fontFamily": "FuraCode Nerd Font",
  "editor.fontLigatures": true,
  "editor.fontSize": 13,
```

```
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
