### ISSUE TITLE
Error message with Python execution code with Shift+Enter 

### ISSUE THREAD

**Issue by jdkorigan** [microsoft/vscode#86960]
Hello,
I get an error message when selecting python code and using Shsift+Enter. 
Everything works perfectly when running "Python file in Terminal" with the context menu.
Thanks for help

![error-pyhton-1](https://user-images.githubusercontent.com/19359410/70830144-dbc91880-1def-11ea-97cc-ff3d4fd9527d.gif)
![info-vs-1](https://user-images.githubusercontent.com/19359410/70830150-de2b7280-1def-11ea-9826-5f53fd4b7a55.jpg)

**Comment by RMacfarlane** [comment]
@jdkorigan Please reopen this issue on the Python extension: https://github.com/Microsoft/vscode-python Thank you!
