### ISSUE TITLE
[html] css.completion.completePropertyWithSemicolon don't work in html files

### ISSUE THREAD

**Issue by Kevint1998** [microsoft/vscode#86969]
Issue Type: <b>Bug</b>

if I close the [css|scss|less].completion.completePropertyWithSemicolon ,it works in css file , but when I edit css in html file ,the editor still help me add a semicolon .It troubles me especially when I edit inline style.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (4.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.15
vscode-language-pack-zh-hans|MS-|1.41.1
cpptools|ms-|0.26.2
LiveServer|rit|5.6.1
ayu|tea|0.18.0
vscode-icons|vsc|9.6.0

</details>

**Comment by octref** [comment]
@aeschli Is there a reason that settings are not propagated to each `languageMode` anymore? In Vue I do that and I copied that from HTML language server.

Changing `css.completion.triggerPropertyValueCompletion` doesn't work in HTML as well.
Should I add `settings` to `doComplete` in CSS Language Service, or should I just propagate settings to each mode with `configure`?

**Comment by aeschli** [comment]
I'm not sure if we ever propagated the css settings to html. But we can do this. The only problem I see is that it's hard to promise that all settings work. E.g. for the embedded JavaScript, I have my own JavaScript server implementation and it a lot of work / maybe impossible to support all the JavaScript settings.
