### ISSUE TITLE
Search Result Extension needs icon

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#86965]
Currently the search result extension uses the default programming language extension icon, which isn't quite right. 

![image](https://user-images.githubusercontent.com/8586769/70840247-d525ab80-1dc5-11ea-896b-934f4b80951f.png)

**Comment by misolori** [comment]
<img width="623" alt="CleanShot 2021-10-04 at 15 26 04@2x" src="https://user-images.githubusercontent.com/35271042/135933046-e24f03a3-15fc-4bb9-aa53-4d5e8d8da280.png">
