### ISSUE TITLE
vscode is hung

### ISSUE THREAD

**Issue by Ahassnat** [microsoft/vscode#86963]
After starting to write the code in 5 seconds. The system was completely suspended and had to be restarted

**Comment by RMacfarlane** [comment]
@Ahassnat Please include the following information when reporting bugs to help us diagnose the issue faster:
- What version of VSCode are you using?
- What operating system are you using?

For this particular problem, has this only recently started happening with a recent update of VSCode? Does this happen only for certain projects? Do you see even when all extensions are disabled?

**Comment by Ahassnat** [comment]
@RMacfarlane   I use Ubuntu 18.04.3 OS, 
 * version 1.41 VS Code

**Comment by RMacfarlane** [comment]
Can you please follow the [performance wiki guide](https://github.com/microsoft/vscode/wiki/Performance-Issues) to help diagnose the issue?
