### ISSUE TITLE
Vscode turns all the JavaScript files into HTML!!

### ISSUE THREAD

**Issue by hayanisaid** [microsoft/vscode#86973]
- VSCode Version: 1.41.0
- OS Version:Darwin x64 19.0.0

Steps to Reproduce:
 
1. Closed a project I was working on then I opened another project(React Native project) and I was surprised that all the JavaScript files turned into like `myjavaScriptFile.js.html `
![Screen Shot 2019-12-13 at 11 51 55 PM](https://user-images.githubusercontent.com/24610720/70843696-e4781980-1e04-11ea-83a8-d254b8470bdb.png)

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: No

Which extension is causing the problem?
