### ISSUE TITLE
vscode without autoprompt method bracket

### ISSUE THREAD

**Issue by lmmarise** [microsoft/vscode#86979]
When I coding JavaScript code the autoprompt method press enter without bracket , need to enter bracket manually. What can I do to complete the bracket  automatically?my friend❤

![GIF 12-14-2019 4-15-54 PM](https://user-images.githubusercontent.com/48174413/70846568-1765f000-1e8d-11ea-9da0-2232cf703c84.gif)

**Comment by RMacfarlane** [comment]
@lmmarise You can a predefined snippet for this.

Run the `Preferences: Configure User Snippets` command and search for javascript and select it, then paste
```
		"Console Log": {
			"prefix": "console.log",
			"body": [
				"console.log($0);",
			],
			"description": "Log output to console"
		}
```

into the file
