### ISSUE TITLE
Suddenly get this issue Code Behind VSCode

### ISSUE THREAD

**Issue by vikas-ukani** [microsoft/vscode#86976]
- VSCode Version:
- OS Version:
- VSCode Insider:

Steps to Reproduce:

1. Suddenly getting this bug,

 
![image](https://user-images.githubusercontent.com/57585690/70844531-5f265080-1e68-11ea-8523-b1ccb01a277c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

In particular, version and platform information, and whether it reproduces when all extensions are disabled
