### ISSUE TITLE
Mirror cursor breaks HTML tags

### ISSUE THREAD

**Issue by juristr** [microsoft/vscode#86978]
- VSCode Version: 1.42.0-insider
- OS Version: macOS 

Steps to Reproduce:

See the following gif:

![vscodeissue](https://user-images.githubusercontent.com/542458/70845560-8a9d4100-1e50-11ea-8a8f-24023af725f8.gif)

I first enter the `ng-template` tag which activates multicursor, then I use the key combi to select and jump to the end of the line, go one back and use "Backspace" to delete the attribute.

This is a common operation, but now with mirror cursors it might break the HTML as seen in the gif above. Moreover, if the opening & closing tag are further apart, one might not even notice the HTML is broken.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mrahhal** [comment]
Also faced this quite a lot as this is a very common operation. I'd like to work on this fix.

**Comment by yuc0n** [comment]
This also brings up an issue when you try to add an attribute to multiple tags that have none.

![Error](https://user-images.githubusercontent.com/22962322/70852960-17bfb480-1ea8-11ea-85bf-59cd30b7ee70.gif)
If you click the open tag, it'll select the opening and closing, and usually when you're at the end and you press _space_ to type in the attribute it doesn't add the attributes to the closing tag, but when you're adding more cursors to the tags in other lines, it doesn't act like that anymore and adds the attributes to both tags.

I went crazy trying to find this to disable it.

**Comment by mrahhal** [comment]
@yuc0n Yeah looking at the current implementation, there's no support at all for multiple cursors. That's gonna take some work for the behavior to work correctly.

**Comment by secf4ult** [comment]
This feature doesn't work well with extension vim too, have to shut it down.

**Comment by octref** [comment]
The fix will be available in https://code.visualstudio.com/insiders/ until next month's release.
