### ISSUE TITLE
list of todo's

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#8697]
the Visual Studio and tools like Resharper allow to define a set of special words in comments treated as tags for certain type of messages: `TODO` an item from a to-do list, `BUG` an item considered a bug, etc

would be great to have is VS Code too

**Comment by Tyriar** [comment]
There are some extensions that scan for TODO/BUG etc.

- https://marketplace.visualstudio.com/items?itemName=MattiasPernhult.vscode-todo
- https://marketplace.visualstudio.com/items?itemName=minhthai.vscode-todo-parser
