### ISSUE TITLE
[Feature Request] Allow "jsconfig.json" within ".vscode" directory

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#86985]
The `.vscode` directory contains config for the IDE.

The `jsconfig.json` file must be within the project root, which is already crowded and messy.

Please allow us to place the file within the `.vscode` directory so that all config is in the same place.

**Comment by ravshansbox** [comment]
Isn't it typescript feature that looks `jsconfig.json` in the root?

**Comment by lonix1** [comment]
For a particular project I'm working on, it's just plain JS (not TS) and it looks in the root. It's a mess in there. The config should be in `.vscode`, to keep it manageable.

**Comment by ravshansbox** [comment]
It's still typescript language server that parses `jsconfig.json`/`tsconfig.json`.

**Comment by mjbvz** [comment]
Closing this as out of scope.

These files are not VS Code specific. Other editors can also `jsconfig` and `tsconfig` to improve their intellisense, and `tsconfig.json` files in particular are used by command line tooling
