### ISSUE TITLE
Centered Layout editor width should remain fixed

### ISSUE THREAD

**Issue by ford04** [microsoft/vscode#86981]
- VSCode Version: 1.41.0
- OS Version: Win 10

### Steps to Reproduce:

![1111](https://user-images.githubusercontent.com/16099458/70846710-4617a280-1e5c-11ea-81a0-6ecb2763965f.gif)

The editor width in a centered layout should remain the same, given there is enough space around it. For example, if you have manually adjusted the editor width to be inline with editor rulers (in the example I had `"editor.rulers": [80]`), every time the side bar is opened, width gets mixed up. Instead it would be nice to keep the manually set editor size and just reposition the whole editor window to the new center position, when side bar has reduces the available space.

Is this possible with the layout system (not sure, if rather a bug of feature request)? Thanks in advance.

### Does this issue occur when all extensions are disabled?
Yes  (also with Insiders)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/54731
