### ISSUE TITLE
Allow extensions to send output to the debug console.

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#8698]
I am building an extension/debugger combination for Clojure that uses the debug console to display the output from a continuously running REPL. I need to be able to evaluate code selected in an editor outside of the normal `Debug: evaluate` path (primarily so the extension can identify the namespace in which to execute the code). I have this working, but I would like to display the the result in the debugger  #console.

**Comment by weinand** [comment]
@indiejames you can find the preliminary "API" [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L430).

**Comment by indiejames** [comment]
@weinand That looks good to me, thanks.

**Comment by weinand** [comment]
Proposed API is now available. Please see https://github.com/Microsoft/vscode/issues/36753
