### ISSUE TITLE
VSCode does not appear to resolve nested variables in launch.conf

### ISSUE THREAD

**Issue by hatmarch** [microsoft/vscode#86982]
Issue Type: <b>Bug</b>

When using the coreclr extension, Code does not appear to resolve variables like ${input:<input_name>} before passing this into the extension.  

**To reproduce**: create a launch.conf like attached 
[launch.json.zip](https://github.com/microsoft/vscode/files/3963677/launch.json.zip) and have the coreclr extension installed.

**Expected**: The user is prompted for a value for ${input:podName} at the time the launch configuration is chosen and this value is passed through to the pipeTransport program.

**Bug**: The extension gets ${input:podName} passed into it breaking the oc pipeProgram of the pipeTransport due to ${input:podName} not being a valid argument to the oc command.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|-psn_0_4666483|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: C++|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (4 x 2800)|
|Memory (System)|7.79GB (5.29GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.19.0
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
vscode-docker|ms-|0.9.0
cpptools|ms-|0.26.2
csharp|ms-|1.21.8
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3

</details>

**Comment by hatmarch** [comment]
I'm not sure this is the same issue as[ #85206](https://github.com/microsoft/vscode/issues/85206) as the user is **never** prompted for the input variables at all at any point before the command in question executes and the variables remain unresolved.

According to the documentation [here](https://code.visualstudio.com/docs/editor/variables-reference) there doesn't appear to be any limitation upon where input variables can be specified within the launch.conf.

**Comment by weinand** [comment]
My speculation is the following:
In your launch.json:
```js 
{
  // Use IntelliSense to find out which attributes exist for C# debugging
  // Use hover for the description of the existing attributes
  // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
  "version": "0.2.0",
  "configurations": [
    // Command for debugging a pod on openshift from vscode
    {
      "name": ".NET Core Attach in OpenShift",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:pickRemoteProcess}",
      "pipeTransport": {
        "pipeProgram": "oc",
        //"pipeArgs": [ "exec", "-i", "${input:podName}" ],
        "pipeArgs": [
          "exec",
          "-i",
          "${input:podName}",
          // container we're interested in should always be listed first, uncomment
          // the following lines (and add necessary input) if this is not the case in your scenario
          "--"
        ],

        // Path to the vsdbg file on the remote pod
        "debuggerPath": "/vsdbg/vsdbg",
        "pipeCwd": "${workspaceRoot}",
        "quoteArgs": false
      }
    }
  ],
  "inputs": [
    {
      "id": "podName",
      "type": "promptString",
      "description": "Enter the name of the pod you want to debug",
      "default": "<run oc get pods>"
    }
  ]
}
```
The "pipeTransport" section is processed (and removed) inside the "coreclr" extension and it is not passed onto the debug adapter.
Since variable substitution occurs only when the launch.json is passed from the extension to the debug adapter, the "pipeTransport" is gone and no input prompts remain.
If this is true, then this issue is basically a duplicate of #85206.
