### ISSUE TITLE
Regression - JavaScript false positive errors ("Expression expected.")

### ISSUE THREAD

**Issue by ghnp5** [microsoft/vscode#86983]
- VSCode Version: 1.41.0
- OS Version: Windows 10

Steps to Reproduce:

```
<script type="text/javascript">
intVar = <?php echo $someInt; ?>;
someFunction(someArray[<?php echo $someInt; ?>]);
</script>
```

The first JS line will show error "Expression expected.".
The second JS line will show "An element access expression should take an argument.".

I suppose the JavaScript lint is stripping out the PHP elements before parsing, but in fact, those PHP elements are putting contents where the lint expects them to be.

**Comment by aeschli** [comment]
Is this with the built-in HTML language support?
We don't support PHP in HTML documents. If it once happen to work, that was just a lucky coincidence. 
Instead you have to open the file in PHP mode and have a PHP extension that adds richer language support.
Or you can disable JavaScript validation in HTML, if you want to continue with it like that.

**Comment by ghnp5** [comment]
Why is this closed?

The file extension is .php and the parsing language in VSCode is PHP.

Why wouldn't you support PHP tags in the middle of HTML? That's very common in many projects... not everyone uses templates like Twig.

**Comment by aeschli** [comment]
Ah, ok, you are in PHP mode and you are using a PHP extension. You need to file this against the PHP extension you use. VSCode has no rich PHP language support out-of-the-box.

**Comment by ghnp5** [comment]
The PHP extensions I use are not giving any errors.

It is the built-in JS validator of VSCode that is complaining about invalid JS, in the lines similar to the above.

Do you still think this is something that the PHP extensions need to fix?

**Comment by aeschli** [comment]
The HTML and/or JS support are only enabled if the editor language mode is HTML or JS.

Can you run VSCode with all extensions disabled?

Here's what I see when I try your example:
![DeepinScreenshot_select-area_20191217151157](https://user-images.githubusercontent.com/6461412/71002483-a702dd00-20df-11ea-90c0-a95d1a5578ca.png)

**Comment by bmewburn** [comment]
This is probably https://github.com/bmewburn/vscode-intelephense/issues/836

**Comment by ghnp5** [comment]
Thank you very much.
I raised bmewburn/vscode-intelephense#903 after I saw this error went away when disabling PHP Intelephense.

Oh - I see now it's a duplicate. Thanks for pointing that out, @bmewburn
