### ISSUE TITLE
postfix completion reports incorrect position

### ISSUE THREAD

**Issue by AlexHaxe** [microsoft/vscode#86984]
- VSCode Version: since 1.41 (also tried insider build)
- OS Version: Ubuntu 18.04

Steps to Reproduce:
1. using `ipatalas.vscode-postfix-ts`  extension
2. inside a function type `foo.le` 
3. perform a postfix completion after `e` and select `let`
4. code gets expanded to `lelet name = foo`

position reported for completion is after `.` instead of `e`

same thing happens with `nadako.vshaxe` extension, it works fine in 1.40.x

**Comment by jrieken** [comment]
This happens when a completion item defines additional text edits that happen on the same line and before the current cursor position.

**Comment by AlexHaxe** [comment]
I just tried with latest insider build and your fix works for both extensions. Thanks a lot!

**Comment by sandy081** [comment]
Discussed in the standup and agreed to be included for November Recovery.
