### ISSUE TITLE
Add "Run Test Task" to global menu "Terminal"

### ISSUE THREAD

**Issue by andre2007** [microsoft/vscode#86999]
Could you add a menu item Run Test Task (With keyboard shortcut, maybe Shift + F10) side by side to Run Build Task in global menu Terminal?

Testing is a major functionality and the test task should have the same importance and visibility as the build task.

**Comment by alexr00** [comment]
You can always add your own keyboard shortcut too!
https://code.visualstudio.com/docs/getstarted/keybindings
