### ISSUE TITLE
Remove input border blinking when you click on internal input options

### ISSUE THREAD

**Issue by awerlogus** [microsoft/vscode#86995]
Issue Type: <b>Bug</b>

When you click on internal input options, the focus of input itself is being lost for the moment, and it produces a border blink visual effect. May be reproduced by opening the search window and clicking on search options like "Use regexp" or other.

VS Code version: Code - Insiders 1.42.0-insider (cbeff45f80213db0ddda2183170281ed97ed3b12, 2019-12-13T07:08:57.560Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
It is slightly annoying but I won't fix it. The focus shows when the input has focus, and when you are in the middle of clicking on the box, it indeed does not have focus.
