### ISSUE TITLE
[html] issues caused by HTML grammar associating '<' with JS

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#86998]
Select the opening `<style>` tag and notice how it highlights the `<html>` tag.

```html
<!DOCTYPE html>
<style>
  body {
    background-color: black;
  }
  .center {
    display: block;
    margin-left: auto;
    margin-right: auto;
  }
  img {
    width: 100%;
  }
</style>
<html>
  <body>
    <span>test</span>
  </body>
</html>
```

**Comment by octref** [comment]
I cannot reproduce this. When I select the opening `<style>` tag it selects the closing `</style>` tag.

![image](https://user-images.githubusercontent.com/4033249/71024959-ec60e380-20ba-11ea-9d76-27266cb85b8b.png)

**Comment by thernstig** [comment]
@octref Notice the "brick-brackets" (in lack of better terms) that highlights the <> for style but the <> for html? That is what I mean.

**Comment by octref** [comment]
@aeschli Actually I don't know what is that feature. Is it something built-in in editor?

**Comment by thernstig** [comment]
@octref Oh, I thought it was part of the new, awesome "mirror cursor" feature but I guess not. It seems built-in in editor somehow. I tried it with no extensions enabled and got the same result.

**Comment by aeschli** [comment]
This is the bracket matching feature that now also works when in the enclosed code: https://code.visualstudio.com/updates/v1_41#_new-bracket-matching-option

The bug is caused by https://github.com/textmate/html.tmbundle/issues/74. The `<` of `</script> is associated with JavaScript. We would have to patch the HTML grammar to fix this as TextMate relies on that behaviour.
For now we're going to accept this bug.

**Comment by aeschli** [comment]
@alexr00 FYI. See https://github.com/microsoft/vscode/commit/18bab626b9d54e836412b7a6aae620645da0422c

The patch turns the name into a scope that is never matched. We could also set it to empty. It would be ignored by vscode-textmate and would never show up. But it might make it harder to understand when debugging differences.
I'm fine either way. Do you have a preference?

**Comment by alexr00** [comment]
A scope that is never matched sounds reasonable. Thanks for the FYI!
