### ISSUE TITLE
Prefer external formatter

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode#86993]
Issue Type: <b>Feature Request</b>

When two (internal and external) formatters are installed, prefer external one instead of generating warning. User only installs external formatter when he/she is not satisfied with internal one.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

**Comment by jrieken** [comment]
Disagree because you sometimes get a formatter you didn't want, esp when a formatter targets multiple languages,  for instance you install prettier for CSS and it also starts to format TypeScript and JSON files

**Comment by ravshansbox** [comment]
How about having a config like `editor.preferExternalFormatters` and user set it `true` not to have to set up prettier for all types it supports. I can open a different issue if required.
