### ISSUE TITLE
Node error for Import saying no exports for files that use module.exports

### ISSUE THREAD

**Issue by mcpDESIGNS** [Microsoft/vscode#87]
Test Node project, saying error for these `Imports`, even though they are in fact `export`ing something.

![image](https://cloud.githubusercontent.com/assets/2574412/11250803/4e8adf4e-8dfc-11e5-8577-1c6b1c88cc4b.png)

![image](https://cloud.githubusercontent.com/assets/2574412/11250814/5d419dfc-8dfc-11e5-9642-6945e87c401f.png)

**Comment by jrieken** [comment]
when using the `import Thing from 'module'` pattern, export must be in this form `export default ThingScheme`

http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by mcpDESIGNS** [comment]
Interesting, I would of thought it could accept both. I'll try that out, thank you!!
