### ISSUE TITLE
Cursor jumps to random location when using the dollar symbol

### ISSUE THREAD

**Issue by ziofil** [microsoft/vscode#87002]
I use vscode (1.40.2) for writing LaTeX documents. In LaTeX, inline math formulas have to be enclosed in two dollar symbols `$ like so $`.

When I input a dollar symbol the cursor jumps somewhere else in the document (though, not always). This is pretty annoying on its own, but it's also making me waste the time to figure out where I am now in the document and to navigate back to where I was.

**Comment by RMacfarlane** [comment]
@ziofil Are you using any extensions, and if so, does this also happen when those are disabled?
