### ISSUE TITLE
In the integrated terminal CTRL + V prints ^V and do not paste.

### ISSUE THREAD

**Issue by bldesign** [Microsoft/vscode#8700]
In the integrated terminal CTRL + V prints ^V and do not paste.

- VSCode Version: 1.2.1
- OS Version: Windows 10
- Node 5.10.0

Steps to Reproduce:

1. Press CTRL + V in the integrated terminal
2. It prints ^V and do not paste

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/6451, see there for advice
