### ISSUE TITLE
Input not registered in second editor group

### ISSUE THREAD

**Issue by Srekel** [microsoft/vscode#87001]
Issue Type: <b>Bug</b>

So I've split the panel in two (dragged and dropped the main window to create the second one) and no input gets registered in the second one to the right.

If I type, nothing happens.

If I move something from the left pane to the right, I can't type in it. Move it back, I can. 

Not sure how I got here, don't think I've seen it before. 

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer-2|Coe|0.0.29
smoothscroll|cya|1.0.4
vscode-markdownlint|Dav|0.32.0
githistory|don|0.4.11
sort-lines-by-selection|ear|1.0.0
EditorConfig|Edi|0.14.3
vscode-diff|fab|1.4.0
asciidecorator|hel|0.2.0
wordcounter|kir|2.1.0
contextualduplicate|laf|0.2.0
python|ms-|2019.11.50794
vscode-remote-extensionpack|ms-|0.19.0
cpptools|ms-|0.26.2
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.2
vscode-fileutils|sle|3.0.0
shader|sle|1.1.4
vscode-3dviewer|sle|0.1.0
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.7.20
ninja|sur|0.0.1
zig|tie|0.2.3
sort-lines|Tyr|1.9.0
gitblame|wad|3.0.1
markdown-all-in-one|yzh|2.6.1

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@Srekel Can you check that this also happens when all extensions are disabled? (You can run the `Developer: Reload with Extensions Disabled` command)

**Comment by Srekel** [comment]
I have no idea how to reproduce it unfortunately, I just reported it as it happened. When I reloaded the window the problem disappeared.

**Comment by RMacfarlane** [comment]
@Srekel Have you been able to reproduce this problem in recent versions of VSCode?

**Comment by Srekel** [comment]
@RMacfarlane No, sorry, afaik it's just happened the one time.

I'll close it now. :)
