### ISSUE TITLE
'Show integrated terminal' shortcut doesn't work

### ISSUE THREAD

**Issue by ShoshinNikita** [microsoft/vscode#87004]
- **VSCode Version:** 1.41.0
- **OS Version:** Linux x64 5.3.6-050306-generic

`Show integrated terminal` shotcut (both default `` Ctrl+` `` and custom) doesn't work in extension windows.

**Steps to Reproduce:**

1. Open any extension window (for example, [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) Welcome page or [VSCode Git Graph](https://github.com/mhutchie/vscode-git-graph))
2. Use shortcut
3. If terminal is opened, it will hide. If terminal is closed, nothing will happen (no matter how many times you use the shortcut)

The shortcut works fine with files. I noticed this problem only for extension windows

**Comment by Tyriar** [comment]
Cannot repro on mac, but I can reproduce on Linux using Release Notes. It also happens with ctrl+j (toggle panel)

**Comment by ShoshinNikita** [comment]
I couldn't reproduce this issue on Windows 10. So, I guess it is related only to Linux

**Comment by mjbvz** [comment]
Fixed for me in  master

I've tweaked the code around how webviews handle keyboard shortcuts on linux (see dbc7b4d912d34da083c969e5ee921f74119c30b9 for example)

Let me know if you still see this in the VS Code next insiders build. If you do, any more specific steps to reproduce the issue?
