### ISSUE TITLE
auto load slowly

### ISSUE THREAD

**Issue by printfll** [microsoft/vscode#87017]
Issue Type: <b>Performance Issue</b>

sometimes  auto load import packages into my golang project  fail and always jump to some function definition fail : ( 
bad user experience!!

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    98	 12187	code main
    6	   360	 12196	   gpu-process
   13	    66	 12211	   shared-process
    0	     0	 16615	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   262	 15889	   window (service.go — customer_service)
    0	   115	 15890	     extensionHost
    0	    49	 15897	       electron_node languageserver.js 
    0	   901	 15903	       /Users/liulu/go/bin/gopls -mode=stdio
    0	    33	 15891	     watcherService
    0	    33	 15984	     searchService
    2	    66	 16612	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (service.go — customer_service)
|    Folder (customer_service): 3205 files
|      File types: go(2147) md(122) yml(65) gitignore(63) s(53) sh(46) mod(31)
|                  sum(21) png(15) conf(14)
|      Conf files: makefile(19);
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
thrift|cdu|0.0.1
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.32.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.13.0
gc-excelviewer|Gra|2.1.32
vscode-starling|liu|0.12.0
python|ms-|2019.11.50794
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
Go|ms-|0.11.9
go-doc|msy|0.1.1
sqltools|mtx|0.21.5
vscode-leetcode|she|0.15.8
vscode-icons|vsc|9.6.0

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@printfll Can you please open this issue on the Go extension?
