### ISSUE TITLE
Typescript validation for JS files should not run in Flow checked files by default

### ISSUE THREAD

**Issue by xixixao** [microsoft/vscode#87012]
This is a duplicate of https://github.com/Microsoft/vscode/issues/15171 - which is closed, and so I'm opening this one as I don't think the issue is resolved.

- VSCode Version: 1.41.0
- OS Version: 10.14.6
- Does this issue occur when all extensions are disabled?: Yes

# Steps to Reproduce:

1. Create a folder with .flowconfig file
2. Create a file with the following:

```
// @flow
import { type Node } from 'react'
```
3. Open VS Code in this folder

You see the following error on hover:
```
Node
~~~~
',' expected. ts(1005)
```
# Issue

This is a bad default experience. Can we disable typescript validation automatically, instead of forcing the user to disable JS validation in settings, which can negatively their experience when opening other projects?

**Comment by mjbvz** [comment]
From VS Code's point of view, flow files are just JS files. We don't want to get into the business of special casing `*.js` files that start with `// @flow`; that should be something that either users or extensions opt into

The correct workaround for flow project is disabling JavaScript validation
