### ISSUE TITLE
Lost short cut key for "integrated terminal"

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Microsoft/vscode#8701]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:24:33.352Z)
- OS Version: Linux x64 3.10.0-327.18.2.el7.x86_64

Steps to Reproduce:

1. Ctrl + ` short cut key for integrated terminal is lost in latest 1.3.0-insider

**Comment by Tyriar** [comment]
I can't reproduce, is there anything in your `keybindings.json` file?

**Comment by tanaka-takayoshi** [comment]
Thanks, I find ``Ctrl+` `` is working at the latest insider. However, shortcut key description is not shown. Is it the intended change?

![selection_029](https://cloud.githubusercontent.com/assets/846156/16571871/71021e88-429d-11e6-9ce6-b791acf4c856.png)

**Comment by Tyriar** [comment]
Does the keybinding show up in the command palette?

![image](https://cloud.githubusercontent.com/assets/2193314/16598967/25428d80-42b5-11e6-978b-a9886d386e7b.png)

**Comment by tanaka-takayoshi** [comment]
Yes, keybinding showed up the command palette. And the latest version today (Commit 798b41ab1cf3636a27042020a54ddfb4cfb8d23c) has fixed the issue commented on  https://github.com/Microsoft/vscode/issues/8701#issuecomment-230371828

**Comment by Tyriar** [comment]
Weird, so it works fine now?
