### ISSUE TITLE
Html problem

### ISSUE THREAD

**Issue by yogesh1234567890** [microsoft/vscode#87019]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

hello, i am having problem here with html files as it doesnt show html logo when using .html extension.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 5.0.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.76GB (0.39GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   189	  7140	code main
    0	    35	  7142	   zygote
    0	    92	  7167	   gpu-process
    0	   274	  7184	   window (Untitled (Workspace) - Visual Studio Code)
    0	   154	  7222	     extensionHost
    0	    58	  7313	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=7222
    0	    81	  7520	       /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=7222
    0	    58	  7229	     watcherService
    0	    62	  7282	     searchService
    0	   119	  7270	   shared-process
    0	     0	  8231	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  8232	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   104	  8210	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled (Workspace) - Visual Studio Code)
|    Folder (vms): 122 files
|      File types: py(32) pyc(31) css(5) html(4) map(4) js(4) eot(1) svg(1)
|                  ttf(1) woff(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.19.0
django|big|1.0.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.13.0
html-snippets|gey|0.2.3
python|ms-|2019.11.50794
html5-skelton|sha|1.0.0
django-intellisense|sha|0.0.2
html5-boilerplate|sid|1.0.3
ejs-snippets|Tao|0.1.0
python|tht|0.2.3
HTML5-extension-pack|wal|0.0.3
html-snippets|wge|0.1.5

</details>

**Comment by gjsjohnmurray** [comment]
Please relaunch with all extensions disabled and see if the problem remains. If it doesn't, bisect to discover which extension is causing the issue. Then report it to the extension author.
