### ISSUE TITLE
[Errno 2] No such file or directory due to signs in path name

### ISSUE THREAD

**Issue by dudiqo** [microsoft/vscode#87018]
Issue Type: <b>Bug</b>

My directory path contained Polish signs in the name of folders (eg. 'ł', 'ś' etc.) was cloned like this from github. The path/folder names are showed correctly in the sidebar. But in terminal there letters are removed from folder names which causes incorrect path name and [Errno 2] No such file or directory.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.11.50794

</details>

**Comment by Tyriar** [comment]
Works under conpty:

<img width="577" alt="Screen Shot 2019-12-30 at 10 07 14 AM" src="https://user-images.githubusercontent.com/2193314/71594280-2b942900-2aec-11ea-85e8-5d4c14ee2ee3.png">

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
