### ISSUE TITLE
Del character couldn't trigger completions

### ISSUE THREAD

**Issue by garygao12580** [microsoft/vscode#87029]
- VSCode Version: 1.41.0
- OS Version: Darwin x64 19.0.0

 I add the `del` character ( ASCII 127 ) in the completion trigger characters. But  it didn't trigger completions when 
I delete some character(s).

I know `new vscode.CompletionList(completionItemList, true);` could display completions even delete some characters . But it doesn't work when I input a space.

**Comment by jrieken** [comment]
Only characters that end up being shown in the editor can be used. It's also highly discouraged to use "all" characters to get some alternative quick suggest experience

**Comment by garygao12580** [comment]
I got it.  Thanks.
