### ISSUE TITLE
Died on 15k and more lines of code

### ISSUE THREAD

**Issue by Ihor93** [microsoft/vscode#87021]
Issue Type: <b>Performance Issue</b>

Jus run big file 

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3516)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (3.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   104	  6364	code main
    2	   375	  5764	   window (game.min.js - game - Visual Studio Code)
    0	    14	  4640	     watcherService 
    0	    11	 17272	       console-window-host (Windows internal process)
    0	   151	 13628	     extensionHost
    0	    45	  7540	       electron_node eslintServer.js 
    0	    96	 15124	       electron_node tsserver.js 
   14	   225	 16916	       electron_node tsserver.js 
    0	    49	 13220	         electron_node typingsInstaller.js typesMap.js 
    0	     5	  7444	           C:\WINDOWS\system32\cmd.exe /d /s /c "npm install --ignore-scripts types-registry@latest"
    0	    11	  4972	             console-window-host (Windows internal process)
   14	    24	  7944	             "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" install --ignore-scripts types-registry@latest
    0	    75	  7948	   shared-process
    0	    15	  9564	   electron-crash-reporter
    7	   174	 12164	   gpu-process
    1	    66	 14812	   window (Issue Reporter)
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1

</details>

**Comment by zachvalenta** [comment]
I've also noticed a significant lag on the newest release; I've had to open anything above 1k LOC in Vim.

**Comment by rebornix** [comment]
@Ihor93 @zachvalenta is it possible that we can share the large file or provide more detailed steps of how to reproduce it? It would be really bad if VS Code slows down for just opening a 1k LOC file.

**Comment by zachvalenta** [comment]
> @Ihor93 @zachvalenta is it possible that we can share the large file or provide more detailed steps of how to reproduce it? It would be really bad if VS Code slows down for just opening a 1k LOC file.

https://gist.github.com/zachvalenta/7bd1d774b41adb8596432790fdaaf33f

Agree that this is tough without hard perf numbers. Assuming if it's real more tickets like this will get opened to the effect of "idk what's going on but VS Code seems slower now".

**Comment by zachvalenta** [comment]
I went through all my extensions and realized the slowdown happens only when I have a particular extension enabled.
