### ISSUE TITLE
The [Enter] and [Backspace] keys are invalid!!!

### ISSUE THREAD

**Issue by CityBoyStar** [microsoft/vscode#87024]
During the development of Vue project with Visual Studio Code, the Enter key and Backspace key often fail when saving the Code, while all other keys can be used normally. What's the problem?
For example, the Enter key cannot break a line, and the Backspace key cannot delete characters. Other alphanumeric keys, including Ctrl+Enter, can be used normally

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform,  steps to reproduce, and whether it still occurs if you disable all extensions.

**Comment by CityBoyStar** [comment]
The version I used is 1.41.0.
------------------------------------------------------------------------------------------------
Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
------------------------------------------------------------------------------------------------

According to your prompt, I disabled all the extensions. After enabling them one by one, I found screenshots situation
. When I pressed enter, the vue-helper reported an error. 
Who knows how to solve it?
THANKS very much!
![TIM截图20191216084500](https://user-images.githubusercontent.com/39644629/70872193-383f5a00-1fe1-11ea-80f7-4b89ab755283.png)

**Comment by gjsjohnmurray** [comment]
Please report this to the extension author. The Report Issue option on the Help menu may help you to do that, but beware that before 1.42 it will silently direct the new issue to the microsoft/vscode repo (ie here) if the extension's repo isn't hosted by GH.

Once you have opened an issue on the extension or found an existing one there please link this to it, then close this.

**Comment by CityBoyStar** [comment]
> Please report this to the extension author. The Report Issue option on the Help menu may help you to do that, but beware that before 1.42 it will silently direct the new issue to the microsoft/vscode repo (ie here) if the extension's repo isn't hosted by GH.
> 
> Once you have opened an issue on the extension or found an existing one there please link this to it, then close this.

Thank you very much. I found it's really the problem with "vue-helper".
