### ISSUE TITLE
Scroll intertia starts zooming when Ctrl is pressed

### ISSUE THREAD

**Issue by flaghacker** [microsoft/vscode#87028]
Issue Type: <b>Bug</b>

When scrolling with the mouse wheel there is some inertia, so the text keeps scrolling a while after you stop physically moving the mouse wheel. This is pretty standard scrolling behavior. The problem is that when you start pressing the `Ctrl` key the existing scrolling inertia is instead applied to the zooming. This is not how other programs (like browsers) behave.

It also looks like it's not possible to turn off scrolling inertia entirely, so right now I don't even have a workaround for this behavior. I hit this pretty frequently as I'm scrolling and zooming around.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.69GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by alexdima** [comment]
I cannot reproduce on my machine. When I scroll with the physical mouse wheel, there is 0 inertia, a single mouse wheel "flick" arrives as a single `mousewheel` event, so I don't believe this is standard behavior.

Does this reproduce for you with any mouse? Is there a specific setting you have turned on in Windows to get this behavior?

**Comment by flaghacker** [comment]
That's weird, I don't have any scrolling inertia anymore either. I'll do some tests over the coming days with different peripheral setups to see what was causing this, but it's good to know there isn't supposed to be any inertia.

**Comment by flaghacker** [comment]
It was because of the trackpad adding scrolling inertia, turns out this affects other applications just as much. Sorry for the noise!
