### ISSUE TITLE
Cannot push/pull using gpg authentication key and gpg-agent. VSCode always try to start ssh-agent

### ISSUE THREAD

**Issue by giulianisanches** [microsoft/vscode#87027]
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:32:17.711Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.0-6-amd64 (Debian 10)

Steps to Reproduce (the steps below are all explained [here](https://opensource.com/article/19/4/gpg-subkeys-ssh)):

1. Create an authentication subkey 
2. Enable gpg ssh support (`echo "enable-ssh-support" >> ~/.gnupg/gpg-agent.conf`)
3. Add the keygrip to `~/.gnupg/sshcontrol`
4. Add the following lines in your .bashrc:

```
# check if th gpg-agent is running
gpg-connect-agent -q updatestartuptty /bye &> /dev/null
SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

export SSH_AUTH_SOCK
```

When I try to pull from VSCode command `(Ctrl+Shift+p) -> Git: Pull`, a `ssh-agent` process is started and i receive the error `permission denied (publickey)`.

Running `git pull` using gnome-terminal or even VSCode integrated terminal works as expected and `pinentry-gnome3` asks for my key password.

`echo $SSH_AUTH_SOCK` shows the correct value both in gnome-terminal and VSCode integrate terminal.

Does this issue occur when all extensions are disabled?: *Yes*

**EDIT: I found the problem!**

Debian 10 does not set GPG_AGENT_INFO automatically. There is a /etc/X11/Xsession.d/90gpg-agent to do this, but as Gnome is using wayland, this variable is not set. As soon as this variable is present, everything works fine..

I would love to comment and close this issue, but a yellow banner said that only collaborators can do it. :)

**EDIT 2:**

The discussion below states that it's not recommended to rely on the contents of this variable anymore.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855868

**Comment by swt30** [comment]
I had this problem too (on Mac). Setting 
`export GPG_AGENT_INFO="$(gpgconf --list-dirs agent-socket):0:1"` in a .bashrc or similar was enough to make it work. From a little reading, it looks like GPG_AGENT_INFO was used by older versions of gpg and that some programs – presumably also vscode – still use it.
