### ISSUE TITLE
Files deleted

### ISSUE THREAD

**Issue by yonicol** [microsoft/vscode#87023]
Issue Type: <b>Bug</b>

I have been working on a project and I saved the files, closed the computer and when I start the computer again to keep on working the entire code got deleted from the files

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (1.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
LiveServer|rit|5.6.1

</details>

**Comment by bpasero** [comment]
Sorry to hear that but unclear to me if VSCode is involved without having some steps how to reproduce if possible. Can you and log the steps?

**Comment by yonicol** [comment]
Never mind anymore, I have rewritten the project form 0, but now I had downloaded local history and that saves me for temp time the files on local history if it happend again.
