### ISSUE TITLE
Enabling Application insights writes JavaScript to function app host.json

### ISSUE THREAD

**Issue by franz-josef-kaiser** [microsoft/vscode#87030]
- VSCode Version: 1.41.1
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. Confirm the "Application Insights" notification question
2. Step through and enable it for your account

This added the following to the function apps `host.json` file:
```json
// Enable telemetry collection with Application Insights
var ai = require('applicationinsights');
ai.setup(process.env.APPLICATIONINSIGHTSKEY || 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX').start();{
  "version": "2.0"
}
```
_The `X` are placeholders._

This broke deployments.

**Comment by RMacfarlane** [comment]
@franz-josef-kaiser I'm not sure where you see the Application Insights notification question, is this shown after installing an extension?

**Comment by franz-josef-kaiser** [comment]
@RMacfarlane You are right. It's [this extension here](https://marketplace.visualstudio.com/items?itemName=VisualStudioOnlineApplicationInsights.application-insights) by Microsoft. Sorry, if I added this to the wrong repo. I am new to Visual Studio Code. Normally I work with IntelliJ products and only use VSC as I am forced into it, so I haven't wrapped my head around all the details.

**Comment by RMacfarlane** [comment]
@franz-josef-kaiser No worries, it's often difficult to tell what the source of an issue is. In this case, this extension does not ship with VSCode. Can you please open this issue at the repo [here](https://github.com/Microsoft/applicationinsights-vscode/issues) instead?
