### ISSUE TITLE
Bug in terminating batch job

### ISSUE THREAD

**Issue by shubhambhojane5** [microsoft/vscode#87033]
Issue Details: 
          There is bug while terminating a batch job, even after giving input as "n" OR "N", a batch is getting terminated.

Steps To Reproduce:
1) Open any project/solution.
2) Run/Start application.
3) Now for terminating a batch job press "Ctrl + C" shortcut.
4) Then it will prompt you a message "Terminate batch job (Y/N)".
5) Now press "n" OR "N".
6) A batch job will get terminate.

Please find the attached screenshot.
![VSCodeTerminateBatchIssue](https://user-images.githubusercontent.com/16082713/70866458-ecb09000-1f8f-11ea-8eca-a7bb0525acc5.png)

Regards

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
