### ISSUE TITLE
Can't edit a <video> tag in HTML

### ISSUE THREAD

**Issue by Souravgoswami** [microsoft/vscode#87031]
OS: ArchLinux x86_64

I am facing a problem where selecting on `<video>` tag in HTML select the closing `</video>` tag as well without pressing any other key.

For example:
![x](https://user-images.githubusercontent.com/37468605/70866371-e5d54d80-1f8e-11ea-81c0-754f89a6d296.gif)

**Comment by gjsjohnmurray** [comment]
Did you see this section of the 1.41 release notes?

https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor

**Comment by Souravgoswami** [comment]
Oops! I thought it's a weird bug!
