### ISSUE TITLE
“Visual Studio Code.app” can’t be opened 

### ISSUE THREAD

**Issue by priyaka-xo** [microsoft/vscode#87040]
I am trying to download Visual Studio Code version 1.41 on Mac. However, I get the following response:
"Visual Studio Code.app" can't be opened because Apple cannot check it for malicious software. 
This software needs to be updated. Contact the developer for more information.

Please advise.

**Comment by gjsjohnmurray** [comment]
/duplicate of #74782 for which the resolution didn't land in time for 1.41. That ticket suggests workarounds.
