### ISSUE TITLE
Black screen issue

### ISSUE THREAD

**Issue by webshoreindia** [microsoft/vscode#87049]
Issue Type: <b>Bug</b>

Just update from v1.39 to v1.40 or 1.41
Vs code opens and only a black screen is shown.
Tried using cmd command "code --disable -gpu"-> worked 1 day, next day back to black screen.
Downgraded to 1.39.2 and it works without any issue

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz (2 x 2799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.00GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
If --disable-gpu helped once it should help again. You have to specify that CLI argument every time you launch code.exe

**Comment by webshoreindia** [comment]
But sir why should always have to disable gpu.? why can't i just open vs code normal like from desktop shortcut

**Comment by gjsjohnmurray** [comment]
Maybe your Windows 7 driver for the GPU of your machine isn't fully compatible with the version of Electron that the newer VSCode uses.

Any reason you can't use that switch every time?

**Comment by gjsjohnmurray** [comment]
Or put a setting into `argv.json` to disable GPU every time? Search the [1.40 release notes](https://code.visualstudio.com/updates/v1_40) for the term 'GPU'

**Comment by webshoreindia** [comment]
ok.. i will refer it. thank you for your time
