### ISSUE TITLE
When I drag the program window, it freezes and there is a delay

### ISSUE THREAD

**Issue by PlutoCA** [microsoft/vscode#87047]
Issue Type: <b>Performance Issue</b>

When I drag the program window, it freezes and there is a delay
The computer's CPU and power consumption will go from low to very high, but when I stop dragging the window, there is a low state

This problem occurred when I updated from win10 system version 1808 (as if 1908 I forgot how much) to the latest 1909 version

![image](https://user-images.githubusercontent.com/31099607/70875637-8b210d80-1ff1-11ea-8310-a074afcbc40a.png)

 x64 的 Windows 10 Version 1909

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	 15280	code main
    0	    77	   548	   shared-process
    0	    69	  4044	   window (问题报告程序)
    0	   132	  4716	   window (欢迎使用 - Visual Studio Code [管理员])
    0	    93	 13152	     extensionHost
    0	    37	  7776	       electron_node server.js 
    0	   220	 10180	   window (wulian_cloud_wxMin - Visual Studio Code [管理员])
    0	    19	  5760	     watcherService 
    0	    11	 14356	       console-window-host (Windows internal process)
    0	    35	 11272	     searchService
    0	   123	 11348	     extensionHost
    0	    53	 10624	       electron_node tsserver.js 
    0	    58	 14040	       electron_node server.js 
    0	   157	 14576	       electron_node tsserver.js 
    0	    45	  8860	         electron_node typingsInstaller.js typesMap.js 
    0	    32	 14992	       "E:\soft\Microsoft VS Code\Code.exe" "e:\soft\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=11348
    0	     6	 14192	     console-window-host (Windows internal process)
    0	    73	 14376	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	 14360	       C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" run dev:weapp"
    0	    26	 12932	         "C:\Program Files\nodejs\\node.exe"  "C:\Users\elvis\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" run dev:weapp
    0	     4	   224	           C:\WINDOWS\system32\cmd.exe /d /s /c npm run build:weapp -- --watch
    0	    26	 13952	             "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run build:weapp -- --watch
    0	     4	 14812	               C:\WINDOWS\system32\cmd.exe /d /s /c taro build --type weapp "--watch"
    0	    27	  4968	                 "C:\Program Files\nodejs\\node.exe"   "C:\Program Files\nodejs\\node_modules\@tarojs\cli\bin\taro" build --type weapp "--watch"
    0	   113	 15272	                   "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\@tarojs\cli\bin\taro-build" --type weapp --watch
    0	   186	 14648	   gpu-process
    0	    15	 15224	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (wulian_cloud_wxMin - Visual Studio Code [管理员])
|    Folder (wulian_cloud_wxMin): 468 files
|      File types: js(120) json(44) wxml(38) png(32) ts(28) wxss(28) scss(26)
|                  tsx(24) md(2) wxs(2)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
cssrem|cip|0.1.0
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
vscode-eslint|dba|1.9.1
githistory|don|0.4.11
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.3
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
docthis|joe|0.7.1
acss|lit|0.0.2
vscode-csscomb|mrm|5.3.0
vscode-language-pack-zh-hans|MS-|1.41.1
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.5
sublime-keybindings|ms-|4.0.6
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
korofileheader|OBK|4.3.2
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
view-in-browser|qin|0.0.5
minapp-vscode|qiu|2.2.2
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
css-auto-prefix|spo|0.1.7
guides|spy|0.9.3
code-spell-checker|str|1.7.20
vscode-import-cost|wix|2.12.0
material-theme|zhu|3.2.1

(5 theme extensions excluded)

</details>

**Comment by PlutoCA** [comment]
image

https://i.loli.net/2019/12/16/oaOBxpZusWkmgy6.png

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled? If not, bisect your extensions to find out which one is causing the problem. Then report it to the extension author.

**Comment by PlutoCA** [comment]
> Does the problem also happen if you launch with all extensions disabled? If not, bisect your extensions to find out which one is causing the problem. Then report it to the extension author.

I also tried starting with all extensions disabled and this issue also happened

**Comment by deepak1556** [comment]
Is this still an issue with our latest insiders https://code.visualstudio.com/insiders ?
