### ISSUE TITLE
Go to definition does not work correctly while in a project that is in a network location (Samba share)

### ISSUE THREAD

**Issue by aed22** [microsoft/vscode#87055]
Go to Definition or F12 on a function gives "No Definition found for 'x' "

This may also occur when the symbol definition exists on the same file.(not as often as when symbol definition is on another file  though)

Version: 1.41.0
OS : Windows 10

**Comment by aed22** [comment]
I was on C project.

**Comment by mjbvz** [comment]
Please file this against your c/c++ extension
