### ISSUE TITLE
Typescript Language Support Broken

### ISSUE THREAD

**Issue by marsoln** [microsoft/vscode#87050]
Issue Type: <b>Bug</b>

Failed to load ts support 5 times.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (7.02GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.4
EditorConfig|Edi|0.14.3
prettier-vscode|esb|3.14.0
sublime-babel-vscode|jos|0.2.10
vscode-language-pack-zh-hans|MS-|1.41.1
cpptools|ms-|0.26.2
Go|ms-|0.11.9
vetur|oct|0.22.6
rust|rus|0.7.0
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by Scooviese** [comment]
I downloaded version 1.40.0 for now, that works. 
I disabled all my extensions in version 1.41.0 and restarted but that didn't help. Also downloading the latest version again won't fix it. So I guess it's the latest commit :(

**Comment by mjbvz** [comment]
@marsoln Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
