### ISSUE TITLE
tsconfig changes to baseUrl, paths, etc require restart.

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/vscode#8705]
- VSCode Version: 1.3.0-insider, 1.2.1
- OS: Windows 10 Professional x64

Steps to Reproduce:

1. Install a nightly build of typescript supporting `baseUrl` and `paths`, anything since march should do.
2. Set `"typescript.tsdk": "C:/Users/user/AppData/Roaming/npm/node_modules/typescript/lib"`
3. Changes to paths and baseUrl are not reflected without reloading VSCode.

This is very frustrating as I am trying to determine a package install strategy which supports multi-versioned, non ambient external module resolution for jspm and I need to test changes manually. Each time I tweak any _tsconfig_ i must reload VSCode.

I was going to raise this issue with the TypeScript team but I have not been able to reproduce it in other editors, such as the VS 15 preview 2, which I have configured to use the new language service and supports these settings. I could not find any exact duplicates.

PS: Thank you for all the hard work you have put into VSCode, it keeps getting better and better :heart:

**Comment by dbaeumer** [comment]
VS uses a different engine underneath. To my knowledge they implement their own language service whereas VS Code relies on the tsserver (also maintained by the TS team). So I will move the issue since the tsserver is the right place to react to these changes.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9522

**Comment by dbaeumer** [comment]
@aluanhaddad thanks for the nice P.S.
