### ISSUE TITLE
Debug console doesn't show text correctly

### ISSUE THREAD

**Issue by JuanMaRuiz** [microsoft/vscode#87058]
- VSCode Version: 1.41.0
- OS Version: Windows 10

Steps to Reproduce:

1. Configure test launcher
2. Launch tests (mocha in my case)

Does this issue occur when all extensions are disabled?: Yes

_With extensions_
![image](https://user-images.githubusercontent.com/1837650/70885482-3c677980-1fd9-11ea-83dc-bd4fd0f56832.png)

_Without extensions_
![image](https://user-images.githubusercontent.com/1837650/70885509-51440d00-1fd9-11ea-8225-ae44fae225c3.png)

**Update**

The problem seems to be related with the configuration `"debug.console.lineHeight"`. If user has setted this property to a number lower than 4 the debug console will show the output unreadable.

**Comment by gjsjohnmurray** [comment]
Seems unwise to set `debug.console.lineHeight` to a non-zero value smaller than the pixel height of your font.

**Comment by JuanMaRuiz** [comment]
Hi @gjsjohnmurray maybe you are right and we should not set the a different value for `debug.console.lineHeight` but the thing is that that configuration worked for me in previous versions of vscode.

Anyway, I will close this issue. 

Best regards.
