### ISSUE TITLE
Cannot type anything within the editor in vscode

### ISSUE THREAD

**Issue by prateekgurnani10** [microsoft/vscode#87053]
Apple cannot open it because of security issues.

- VSCode Version: 1.41
- OS Version: Mac OS catalina version 10.15.1

Does this issue occur when all extensions are disabled?: Yes

**Comment by prateekgurnani10** [comment]
I tried to install the builder version but it says “Visual Studio Code - Insiders” can’t be opened because Apple cannot check it for malicious software.

**Comment by gjsjohnmurray** [comment]
/duplicate of #74782 for which the resolution didn't land in time for 1.41. That ticket suggests workarounds.

**Comment by prateekgurnani10** [comment]
I am able to open the vscode on Mac os X Catalina but my main issue is that I cannot type anything inside the editor. I can delete though.  My keyboard just doesn't work for typing. I also tried to disable all the extensions and then enable it but still it doesn't work.

**Comment by gjsjohnmurray** [comment]
@weinand looks like I closed this too soon. Please reopen and assign to whoever you think is best placed to handle it.

**Comment by prateekgurnani10** [comment]
So I disabled the vim extension and now it works! But still not sure what thing was causing the problem?

**Comment by weinand** [comment]
You might want to file the issue against the VIM extension.
