### ISSUE TITLE
Cannot open folder in vscode with hot key i after updating VSCode to 1.41.0 

### ISSUE THREAD

**Issue by Sichen-Wang** [microsoft/vscode#87056]
- VSCode Version: 1.41.0
- OS Version: Win 10 pro 10.0.18362.535

Steps to Reproduce:

1. right click a folder to open the menu
2. press `i`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
To confirm, are you referring to this menu entry in File Explorer?
![image](https://user-images.githubusercontent.com/6561887/70926488-15fa0c00-1fe2-11ea-8a57-a310c691888d.png)

**Comment by waitingsong** [comment]
Same issue.
Win7 64bit chinese.
And the context menu changed from `Open with Code`  to  `通过 Code 打开` ，i think it should be `通过 Code 打开 ( I )`

**Comment by Sensirex** [comment]
Same issue.
Win10 64bit, there are no hotkey for files and folders
When I fixed this by editing registry I saw that text "Open with Code" without &, so after adding "&" hotkeys works great

But I should do that after each update :(

**Comment by Sichen-Wang** [comment]
> To confirm, are you referring to this menu entry in File Explorer?
> ![image](https://user-images.githubusercontent.com/6561887/70926488-15fa0c00-1fe2-11ea-8a57-a310c691888d.png)

Yes

**Comment by sbatten** [comment]
ah, looks like this PR just missed it when localizing https://github.com/microsoft/vscode/pull/84414

/cc @joaomoreno

**Comment by roblourens** [comment]
I see this after reinstalling vscode fresh: 

![image](https://user-images.githubusercontent.com/323878/73482351-6ccd6200-4352-11ea-986b-f266c5cb8af1.png)

Does the & need to be added to every language, or are we waiting for the localized versions to be updated by the translators?

**Comment by sbatten** [comment]
@roblourens I did not update the localized strings as I don't know the correct behaviour for each language. I rely on the translators to update each language.
