### ISSUE TITLE
wsl terminal takes a long time to open

### ISSUE THREAD

**Issue by Tender2233** [microsoft/vscode#87065]
Issue Type: <b>Performance Issue</b>

when you start wsl ubuntu terminal (root) it will immediently start after wsl open. but when you open a folder. It will make you become a default user and take a long time.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|15.93GB (8.95GB free)|
|VM|29%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   135	  4360	code main
    0	    72	  8416	   window (问题报告程序)
    0	    17	 16508	   electron-crash-reporter
    0	    94	 17896	   shared-process
    0	   112	 18516	   gpu-process
    0	   140	 18972	   window (tender [WSL] - Visual Studio Code)
    0	    76	 14320	     extensionHost
    0	    29	 17364	       electron_node wslDaemon.js 
    0	     7	  2432	         C:\WINDOWS\System32\wsl.exe sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" f359dd69833dd8800b54d458f6d37ab7c78df520 stable .vscode-server 0  '
    0	    11	  6732	           console-window-host (Windows internal process)
    0	     5	  9388	           C:\WINDOWS\System32\lxss\wslhost.exe {6b1cc7de-7763-4864-b319-fa1c53428f36} 480 500 504
    0	    14	 15648	             console-window-host (Windows internal process)

Remote: WSL
CPU %	Mem MB	   PID	Process
   64	     0	    12	remote agent
    0	     0	   174	   extensionHost
    0	     0	   187	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	   188	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL|    Folder (tender): more than 51305 files|      File types: cmt(1021) mar(962) cmti(794) cmi(702) cmx(680) mli(524)
|                  annot(406) ml(313) comp(258) descr(257)
|      Conf files: package.json(7) tslint.json(1) makefile(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
reasonml|fre|1.0.38
vscode-language-pack-zh-hans|MS-|1.40.2
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.61
lex-flex-yacc-bison|fau|0.0.3
vscode-language-pack-zh-hans|MS-|1.40.2
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.40.3
vscode-icons|vsc|9.6.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Can you explain more? How is this related to the `Remote - WSL` extension? How do you open a folder?
