### ISSUE TITLE
Position of Code Lens using Octicon looks strange

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#87062]
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

<img width="257" alt="Screen Shot 2019-12-16 at 3 39 10 PM" src="https://user-images.githubusercontent.com/6193897/70888079-7311b400-201a-11ea-8d25-471317468a3c.png">

As shown in the screenshot, the Octicon shows higher than the common texts.

**Comment by jrieken** [comment]
I have pushed a change that fixes the sizing, underline, and color issues

**Comment by jrieken** [comment]
**Normal**
<img width="158" alt="Screenshot 2019-12-16 at 11 54 49" src="https://user-images.githubusercontent.com/1794099/70901338-e0155180-1ffa-11ea-8340-5604e5cb86fe.png">

**Hovered**
<img width="201" alt="Screenshot 2019-12-16 at 11 54 47" src="https://user-images.githubusercontent.com/1794099/70901353-e60b3280-1ffa-11ea-82ad-da7c5753ce03.png">

**Comment by jdneo** [comment]
Thank you @jrieken, 

I tried it in the newest Insider, looks much better, but the position is still looks higher from my side:

Before
![image](https://user-images.githubusercontent.com/6193897/70960045-dc480480-20b8-11ea-8682-3b905d7fd3d3.png)


New:
![image](https://user-images.githubusercontent.com/6193897/70960060-ecf87a80-20b8-11ea-94ee-53f31488d9fa.png)

**Comment by jrieken** [comment]
Hmm, did you try this with 22a87bf3f259d3fcff66f636a9db611741c7e1c5?

**Comment by jdneo** [comment]
Hi @jrieken 

I updated to 22a87bf, still the later appearance

Version: 1.42.0-insider (user setup)
Commit: 22a87bf3f259d3fcff66f636a9db611741c7e1c5
Date: 2019-12-17T05:41:30.616Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
<img width="166" alt="Screenshot 2019-12-17 at 10 42 48" src="https://user-images.githubusercontent.com/1794099/70983998-fc2bf800-20b9-11ea-8393-d02e39d453ca.png">


Not so easy... When I change the vertical alignment then the link-underline looks bad... @misolori can you help? Is there a trick I am unaware of or should I stop showing the underline?

**Comment by jrieken** [comment]
Idea to (1) use no underline anymore or (2) try more css tricks (border, different v-align)

**Comment by jdneo** [comment]
By saying `no underline anymore`, what will be the rendering result if the Code Lens is `Hello ✓`

**Comment by jrieken** [comment]
Yes - on hover we will only change the color and pointer style but we won't underline anymore

**Comment by jrieken** [comment]
I have tweaked the alignment and now there is two options for the underline decoration. 

1) have no underline decorations
1) have underline decoration except for codicons


![Dec-20-2019 11-40-54](https://user-images.githubusercontent.com/1794099/71249528-a35c9980-231d-11ea-840f-ee9b1fcabb38.gif)
![Dec-20-2019 11-41-03](https://user-images.githubusercontent.com/1794099/71249529-a3f53000-231d-11ea-932f-e0a92f49f326.gif)

**Comment by jrieken** [comment]
Went for the variant without underline

**Comment by connor4312** [comment]
@jrieken testing the debug-start codicon in js-debug, I noticed that it appears to sit slightly lower than it looks like it should on the line

![image](https://user-images.githubusercontent.com/2230985/72940277-6c661300-3d23-11ea-93fc-42fe9311ec18.png)

**Comment by misolori** [comment]
@jrieken not sure if you've tried this already, but setting `.monaco-editor .codelens-decoration > a` to `display: flex` will help it get aligned vertically:

![image](https://user-images.githubusercontent.com/35271042/72944529-016e0980-3d2e-11ea-870d-cd305638b06d.png)

**Comment by jrieken** [comment]
Yeah, the display flex makes it move upwards and we want it to be align the bottom (the anchor line...) 🤷‍♂ I have now pushed a change that ensure the text and codicon use equal sizes, before codicon were rendered a little larger and that caused the misalignment. Let me know what his 👇 

<img width="331" alt="Screenshot 2020-01-23 at 10 07 21" src="https://user-images.githubusercontent.com/1794099/72970845-bc4ae580-3dc8-11ea-930b-9df0d986915d.png">
