### ISSUE TITLE
window namespace tests Terminal processId immediately after createTerminal should fetch the pid:

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#87066]
From build: https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=63728&view=results

```
1) window namespace tests Terminal processId immediately after createTerminal should fetch the pid:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

```

**Comment by bpasero** [comment]
Oh, looks like they only fail remote. I can reproduce locally and pushed https://github.com/microsoft/vscode/commit/2d2ac8f75b539d505443ac0733b196851c0b218d. Please review

**Comment by Tyriar** [comment]
This change is likely why shellArgs no longer work on remote: https://github.com/microsoft/vscode/issues/87088

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/87088
