### ISSUE TITLE
"HTML mirror cursor" and "F2 to rename tag" won't work with anything but HTML files

### ISSUE THREAD

**Issue by solid-pixel** [microsoft/vscode#87064]
Hello! :)

I'm working mainly with .tpl Smarty files, and I have the [Smarty extension](https://marketplace.visualstudio.com/items?itemName=imperez.smarty) installed for syntax highlighting and language support.

I was really eager to try the new features "HTML mirror cursor" and "F2 to rename tag" but none of these will work unless I go and change the Language Mode from Smarty to HTML.

I have tried to add these settings, but to no avail:
```
	"[smarty]": {
		"html.mirrorCursorOnMatchingTag": true,
		"editor.defaultFormatter": "vscode.html-language-features",
	}
```

Given that .tpl files are essentially HTML files that support Smarty `{tags}`, would it be possible to add support for these features? It would be a great game changer.

Thank you very much!

**Edit: just realised the same applies to PHP too :(**

**Comment by gjsjohnmurray** [comment]
@octref - is it possible for other languages that embed HTML to benefit somehow from this new feature that I think you added?

**Comment by JamesCoyle** [comment]
I feel like this should be extended to support all XML like syntaxes.

**Comment by octref** [comment]
> is it possible for other languages that embed HTML to benefit somehow from this new feature that I think you added?

@gjsjohnmurray  Nope. Each language extension needs to implement this feature themselves.

XML already has it. See https://github.com/redhat-developer/vscode-xml/issues/130
JSX -> https://github.com/microsoft/vscode/issues/85707#issuecomment-559187700

**Comment by octref** [comment]
@solid-pixel Currently they only way is to use `files.associations` to mark tpl as HTML languages.

In the future we might make this feature available to other languages.

**Comment by solid-pixel** [comment]
@octref thanks for coming back. 
If I do that, I'll lose Smarty's syntax highlighting and other stuff, so, unfortunately, it's not an option for me.

Perhaps I'll try and ask the Smarty extension devs if they can implement this the way XML did.

**Comment by ridwantanjung** [comment]
that's also what happens to me too, but what I experienced is on Laravel ``blade.php`` file, and if I add ``blade.php`` to ``file.associations`` that remove the syntax highlight
