### ISSUE TITLE
Unknown encoding: cp850

### ISSUE THREAD

**Issue by bernatrm** [microsoft/vscode#87069]
Issue Type: <b>Bug</b>

When I'm trying to Shearch some text on the "Search Form" appears this message "Unknown encoding: cp850" and the search function doesn't 
![Anotación 2019-12-16 110634](https://user-images.githubusercontent.com/6303965/70898035-274c1400-1ff4-11ea-988d-a742f27d6dec.png)
executed.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
xml|Dot|2.5.0
gitlens|eam|10.2.0
mssql|ms-|1.7.1
azurecli|ms-|0.4.6
powershell|ms-|2019.11.0
team|ms-|1.161.0

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/68237
