### ISSUE TITLE
It would be great if F5 would open the debug console automatically

### ISSUE THREAD

**Issue by Ritzlgrmft** [Microsoft/vscode#8706]
- VSCode Version:1.2.1
- OS Version: Windows 8.1

I am using vscode with the "Cordova Tools" extension for building an Ionic2 app. Currently my build/debug workflow is the following, when I need to debug it on the device (which I need since I am testing some hardware functionalities which cannot be simulated):

- run `ionic serve --nobrowser` in the background
- press F6 for the cordova build: this shows automatically the output window
- press F5 for starting the debugger

Here it would be nice to see the debug window automatically - without explicitely showing it with `Ctrl-Shift-Y`.

I opened an issue for this topic on [vscode-cordova repository](https://github.com/Microsoft/vscode-cordova/issues/161), but the guys there mentioned it seems to be more a vscode issue...

**Comment by isidorn** [comment]
Yes, it is a configuration on the vscode side. To get the behavior you would like you can add to your launch.json configuration: `'internalConsoleOptions': 'openOnSessionStart'`
More details can be found here: https://github.com/Microsoft/vscode/issues/6159
