### ISSUE TITLE
Default Javascript extension does not provide suggestion from the local modules.

### ISSUE THREAD

**Issue by Wathsara** [microsoft/vscode#87078]
![Screenshot from 2019-12-16 17-33-10](https://user-images.githubusercontent.com/31571237/70905654-701ebf80-202a-11ea-999f-2ab95a7f06ff.png)

Here I attached an image to make the explanation easier. what I did is created a folder called modules and add one of my modules name age to that. what I did here is i added the path of the module folder to require function like `require.main.paths.push('/home/wathsara/Videos/test/modules')` so it compiles fine. but still, the vscode does not give the suggestion for the auto completions (exported functions of the module).

**Comment by mjbvz** [comment]
We do not support IntelliSense for dynamic resolution like that (i.e. modifying `require.paths`)

For proper intellisense support, try using static module references
