### ISSUE TITLE
Error in creating subfolder.

### ISSUE THREAD

**Issue by shrutipant7** [microsoft/vscode#87079]
1. Create any folder.
2. Create a subfolder under that.

The subfolder will not be created. Instead, the parent folder will be renamed as <folder/subfolder>.

**Comment by gjsjohnmurray** [comment]
You didn't say what version you are running. If it is 1.41 perhaps what you are seeing is [this new feature](https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer). I don't see how the new folder on disk could actually end up being named folder/subfolder

**Comment by shrutipant7** [comment]
Closing the issue. This new feature is quite confusing though. Would suggest to remove it.

**Comment by gjsjohnmurray** [comment]
Remember you can use the `explorer.compactFolders` setting to turn it off if you don't like it.

**Comment by neiltnathan** [comment]
Thanks for the solution @gjsjohnmurray 
Perhaps the default  for compact folders should be OFF.  I have just wasted an hour trying to understand the issue.  The problem appears to have been introduced in the latest update 1.41
