### ISSUE TITLE
Panel tabs disappear on "Problems" click if there are no problems

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#87074]
Version: 1.41.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Click on "Problems" panel tab

![gif](https://user-images.githubusercontent.com/9438102/70901491-2e2a5500-1ffb-11ea-96bd-3a4405168d5e.gif)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by gjsjohnmurray** [comment]
/confirm also in 1.42.0-insider, 2019-12-13T07:08:57.560Z

Looks like the new 1.41 "Flexible filter box layout" mentioned in a subsection of the [release notes](https://code.visualstudio.com/updates/v1_41#_problems-panel) doesn't handle this sequence:

1. Switch to Problems tab.
2. Reduce width until filter field moves below tabs (this is the new feature).
3. Switch to another tab.
4. Switch back to Problems tab. Only the filter box displays. The tabs that should be above it are missing 🐛 

cc @sandy081

**Comment by sandy081** [comment]
Resizing the panel will bring the panel tabs back. 

Fixed it in master.

Reopening it for candidate discussion to include in recovery release.

**Comment by sandy081** [comment]
Discussed in our standup and agreed to be included for November Recovery.

**Comment by isidorn** [comment]
This issue only happens when:
* There are no errors in the problem panel and only the  problems panel and one more panel is visible
* If I reload, or resize the window the problem goes away

Due to that I personally do not think this is a canddiate. Also only 1 user hit it.
However I have verfiied that the PR fixes it in a proper way, thus adding approved label on the PR.

**Comment by sandy081** [comment]
Yes, this was mentioned yesterday during the stand up that not many users hit this issue. Reason why it was taken as candidate because the UI gets into broken state and looks ugly.
