### ISSUE TITLE
"Run Test | Debug Test" success/fail annotations do not update until scrolling

### ISSUE THREAD

**Issue by DanielFEvans** [microsoft/vscode#87077]
- VSCode Version: 1.41.0
- OS Version: Windows 10, running remotely on Scientific Linux 7.6

Steps to Reproduce:

1. Open a file containing code tests, at least one of which begins below the bottom of the screen
2. Run all tests in the file as a group (i.e. without clicking "Run Test" on each individually)
3. Tests visible on screen will have success/fail annotations (the tick/cross symbols) appear.
4. Collapse code until at least one test not previously visible can be seen. It will not have a tick/cross symbol.
5. Scroll the display, even if by only one line. The tick/cross symbol will appear for all visible tests.

4 and 5 can be repeated if more tests still exist off-screen.

Does this issue occur when all extensions are disabled?: Unknown, as this disables the remote development extension, and we don't develop locally.

Step 3: Tests run, annotations show for visible tests.
![Step 3: Tests run, annotations show for visible tests.](https://user-images.githubusercontent.com/41120183/70905694-6da57100-1ffc-11ea-9f9d-1b2ca1ab4f2f.PNG)

Step 4: Topmost test collapsed. Newly appeared test has no annotation, but was run at the same time as the topmost test.
![Step 4: Topmost test collapsed. Newly appeared test has no annotation, but was run at the same time as the topmost test.](https://user-images.githubusercontent.com/41120183/70905691-6d0cda80-1ffc-11ea-89cc-f0203b0ba160.PNG)

Step 5: Screen scrolled down one line, and annotation appears.
![Step 5: Screen scrolled down one line, and annotation appears.](https://user-images.githubusercontent.com/41120183/70905693-6d0cda80-1ffc-11ea-8f67-c06f743d3a30.PNG)

**Comment by gjsjohnmurray** [comment]
@jrieken will this be Code Lens specific, or a more general issue about things not redrawing adequately if they scroll into view as a consequence of code folding?

**Comment by DanielFEvans** [comment]
I've also just noticed that I can't use newly displayed Run Test or Debug Test buttons after folding some code above them - the text doesn't highlight on mouseover, nor does clicking do anything. Again, this is fixed by scrolling.

Other UI elements behave as expected - code highlights on being clicked, help displays on mouseover, etc..
