### ISSUE TITLE
Linux: Keybinding for "Replace in Files" conflicts

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8707]
On Linux we seem to bind Ctrl+Shift+H to toggle output (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/output.contribution.ts#L47)

**Comment by sandy081** [comment]
As discussed, we stick to Ctrl+Shift+H keybinding for replace and change it for Output console in Linux.

**Comment by isidorn** [comment]
@sandy081 ok tried it out and currently replace takes priority - which is good. So we decided to move this to july? Which is a good decision imho
