### ISSUE TITLE
Screen flickering and saving continously

### ISSUE THREAD

**Issue by sriteja-m** [microsoft/vscode#87075]
Issue Type: <b>Bug</b>

When we hit CTRL+S it is getting saved continously

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

[2019-12-16-17-32-44.zip](https://github.com/microsoft/vscode/files/3967902/2019-12-16-17-32-44.zip)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (10.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
missinglineendoffile|ric|0.3.1
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment]
Please re-test with all your extensions disabled. If this solves the problem, re-enable each extension one at a time until you find the culprit. Then report the issue to the extension developer and close this one here.
