### ISSUE TITLE
Enable Service Worker for extension webview API

### ISSUE THREAD

**Issue by ayqy** [microsoft/vscode#87076]
Now, `navigator.serviceWorker` at extension webview's runtime is `undefined`, so that we can not use Service Worker. Is it designed intentionally ?

Can we enable Service Worker for webviews ?

**Comment by mjbvz** [comment]
Yes currently by design. No plans in the short term to change this limitation

**Comment by ayqy** [comment]
@mjbvz Got that, thanks for your response.
