### ISSUE TITLE
css in markdown stopped working

### ISSUE THREAD

**Issue by MrBjorn** [microsoft/vscode#87073]
Hi,

After I upgraded the

    "markdown.styles": [
        "styles.css"
    ],

setting for css files in markdown stopped working.

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue

/needsMoreInfo

**Comment by MrBjorn** [comment]
Issue Type: <b>Bug</b>

1. Create MD file:

# This headline should be styled nice

    this should be in a nice box

2. Update: file|preferences|Settings|settings.json

{
    "markdown.styles": [
        "styles.css"
    ],
}
 
3. Add styles.css
:root {
  --background-color-alt: rgb(60, 60, 60);
  --background-color: rgb(40, 40, 40);
  --border-radius: 0;
  --call-to-action: rgb(200, 100, 0);
  --call-to-action-active: rgb(220, 120, 20);
  --checked-color: rgb(0, 130, 0);
  --divider-color: rgb(40, 40, 40);
  --font-size: 100%;
  --font-size-large: 150%;
  --font-size-huge: 200%;
  --gutter: 20px;
  --gutter-small: 5px;
  --gutter-medium: 10px;
  --gutter-wide: 60px;
  --gutter-wide-negative: -60px;
  --heading-color: rgb(220, 220, 220);
  --heading-color-alt: rgb(100, 100, 100);
  --icon-width: 15px;
  --main-color: rgb(0, 60, 100);
  --secondary-color: rgb(20, 80, 130);
  --shadow: 0 5px 5px rgba(0, 0, 0, 0.2);
  --table-width: 80%;
  --text-color: rgb(180, 180, 180);
  --text-color-alt: rgb(60, 120, 170);
}

* {
  box-sizing: border-box;
}

a {
  color: var(--call-to-action);
  text-decoration: underline;
}

a:hover {
    color: var(--call-to-action-active);
}

blockquote {
  border-color: var(--secondary-color);
  border-width: var(--gutter);
}

body {
  background-color: var(--background-color);
  background-attachment: fixed;
  color: var(--text-color);
  padding: 0 var(--gutter-wide) 100px var(--gutter-wide);
  margin: 0;
  letter-spacing: .5px;
}

code {
    color: var(--secondary-color);
    font-style: italic;
}


em, strong {
  color: var(--text-color-alt);
}

h1, h2, h3, h4 {
  text-decoration: none;
  font-weight: normal;
  text-transform: uppercase;
  color: var(--heading-color);
}

h1 {
  font-size: var(--font-size-huge);
  background-color: var(--main-color);
  border-width: 0;
  text-align: center;
  padding: var(--gutter);
  margin: 0 var(--gutter-wide-negative) var(--gutter-wide) var(--gutter-wide-negative);
  box-shadow: var(--shadow);
}

h1 + h2 {
  margin-top: var(--gutter-wide-negative);
}

h2 {
  font-size: var(--font-size-large);
  padding: var(--gutter-medium) var(--gutter-wide);
  margin: var(--gutter-wide) var(--gutter-wide-negative) var(--gutter) var(--gutter-wide-negative);
  line-height: 100%;
  background-color: var(--secondary-color);
  box-shadow: var(--shadow);
}

h3 {
  font-size: var(--font-size-large);
  margin: var(--gutter) 0 0 0;
}

h4 {
  font-size: var(--font-size);
  margin: 0;
  color: var(--heading-color-alt);
}

hr {
    width: var(--gutter-wide);
    margin: var(--gutter-wide) auto;
    border: 1px solid var(--secondary-color) !important;
    height: 0;
    border-width: 0 0 1px 0 !important;
}

html {
  padding: 0;
  margin: 0;
}

img {
  box-shadow: var(--shadow);
}

input.task-list-item-checkbox {
    background: transparent;
    border: 1px solid var(--background-color-alt);
    -webkit-appearance: none;
    width: var(--icon-width);
    height: var(--icon-width);
    margin-top: -1px;
}

input.task-list-item-checkbox[checked]:after {
    content: "✓";
    font-weight: bold;
    position: absolute;
    top: -4px;
    left: -19px;
    color: var(--checked-color);
    font-size: 17px;
}

p {
  padding: 0;
  margin: 0;
}

pre code {
  color: var(--text-color);
  tab-size: 4;
  background: none;
  padding: 0;
  margin: 0;
}

table, pre, blockquote {
  margin: var(--gutter-wide) auto;
  padding: var(--gutter);
  background-color: var(--background-color-alt) !important;
  width: var(--table-width);
  border-radius: var(--border-radius) !important;
  box-shadow: var(--shadow);
}

table {
  border: none;
}

table > tbody > tr > td + td {
  border-left: 1px solid var(--divider-color) !important;
}

table > tbody > tr > td {
    border-top: 1px solid var(--divider-color) !important;
    color: var(--text-color);
}

th {
    background-color: var(--secondary-color);
    border-bottom: none !important;
    font-weight: normal;
    text-align: center !important;
    color: var(--text-color) !important;
}

th:first-child {
  border-top-left-radius: var(--border-radius);
}

th:last-child {
  border-top-right-radius: var(--border-radius);
}

th + th {
  border-left: 1px solid var(--divider-color) !important;
}

th, td {
  padding: var(--gutter-small) var(--gutter) !important;
  color: var(--heading-color);
}

ul {
  list-style-type: disc;
  padding: 0;
  margin: var(--gutter-small) 0 var(--gutter-small) var(--gutter);
}

ul ul {
  padding-left: var(--gutter);
  margin: 0;
}

4. Have the MD file open, and open preview window to the right. in previous VS code it was styled nicely, blue boxes was one thing, but now it have lost most of the styling, some seems to still be there.


VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (9.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
excel-to-markdown-table|csh|1.1.0
vscode-markdownlint|Dav|0.33.0


</details>

**Comment by mjbvz** [comment]
I can't repo this on MacOS. @MrBjorn Is your project on a network drive or similar? See #87180 for example
