### ISSUE TITLE
Scroll doesn't work properly sometime (UBUNTU)

### ISSUE THREAD

**Issue by raysk4ever** [microsoft/vscode#87072]
my scroll from my touch pad doesn't work properly but it works fine in windows.

**Comment by deepak1556** [comment]
Do you still experience this issue with latest stable ?

**Comment by raysk4ever** [comment]
Yes

**Comment by raysk4ever** [comment]
Hey @deepak1556, i moved on to the codium and the scroll works normally there. But when i use vscode some times it scrolls more i expected.

**Comment by raysk4ever** [comment]
i switched to mac it doesn't happens on the mac version. but yeah i was facing that scroll issue on my windows and my ubuntu

**Comment by deepak1556** [comment]
Closing per above comment, if the issue happens with latest insiders https://code.visualstudio.com/insiders/ can reopen.
