### ISSUE TITLE
Markdown preview bug

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#87081]
Issue Type: <b>Bug</b>

n Markdown file preview, header 3 is not bold like any other level of headers.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.32.0
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6

</details>

**Comment by mjbvz** [comment]
Please provide an example

**Comment by mjbvz** [comment]
Actually never mind; I see what you are talking about

This is intentional. h1-h3 are all normal font weights

You can change the style of the preview: https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css
