### ISSUE TITLE
Run all tests fails (pytest)

### ISSUE THREAD

**Issue by hiddenslave** [microsoft/vscode#87080]
Hi Good people,

For some reasons run all tests fails in vscode with following error
```

platform linux -- Python 3.6.9, pytest-5.0.1, py-1.8.0, pluggy-0.13.1
rootdir: /workspace
plugins: cov-2.8.1
Fatal Python error: Aborted

Error: TypeError: Cannot read property 'testsuites' of null

```

Even discovery of tests fails with following error
```

Test Discovery failed: 
Error: free(): invalid pointer
Fatal Python error: Aborted
```
I have tried installing different versions of pytest but it doesnt seem to help.
do you know about this issue ?

**Comment by RMacfarlane** [comment]
@hiddenslave Please reopen this issue on the pytest extension

**Comment by hiddenslave** [comment]
@RMacfarlane i am not using any pytest extension .i use Microsoft python extension and pytest pip package . It could be a problem with pytest itself .. thanks
