### ISSUE TITLE
Keybindings Editor: Ability to multi select and perform an operation

### ISSUE THREAD

**Issue by jacobgqc** [microsoft/vscode#87086]
The ability to disable multiple (or all) default keystrokes. This might be done through the UI or via a pre-compiled list of disables in keybindings.json.

This functionality would be useful for blind users or anyone who relies heavily on keybindings in helping to avoid accidentally using the wrong key commands.

At this time, the best method I found was to manually delete (adding disable to keybindings.json) key bindings. However, this is an incredibly slow process for such a large list of existing keybindings.

**Comment by sandy081** [comment]
@jacobgqc If I understand correctly you are asking for multi-select support in keybindings editor?

**Comment by jacobgqc** [comment]
Yes, more specifically, multi-delete. It looks like multi-select already works, but the delete only removes one entry.

I noticed while going through the default keybindings, a lot of them are required for much of the editor as a whole. For example, key bindings to navigate with arrows, escape keys, delete key, etc.
Another solution that would fit my particular use case would be to provide multiple sets of defaults.

A base default that only has normal text editor functionality, i.e. arrow keys, shift + arrow keys, copy, cut, paste, etc.
A VS default that has the base default plus some VS specific commands, such as comment all code, open command palette, etc.

**Comment by sandy081** [comment]
I can accept this to support multi select and delete. For other of your suggestions please open a separate issue.
