### ISSUE TITLE
No longer using login shell

### ISSUE THREAD

**Issue by cpheps** [microsoft/vscode#87088]
Issue Type: <b>Bug</b>

I have the `"terminal.integrated.shellArgs.linux": [ "-l" ]` setting in my settings which use to source the `.bash_profile` . It no longer sources that file unpon opening the terminal.

VS Code version: Code - Insiders 1.42.0-insider (2d2ac8f75b539d505443ac0733b196851c0b218d, 2019-12-16T12:08:26.094Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: faas2|
|OS|Linux x64 4.15.0-39-generic|
|CPUs|Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz (8 x 1789)|
|Memory (System)|47.15GB (16.63GB free)|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
You're using a remote extension, I think you'll need to set that in your _remote_ settings for it to work.

**Comment by cpheps** [comment]
@Tyriar I do have that setting in my remote Machine config. It was working then as of the build I submitted this under it stopped working.

**Comment by Tyriar** [comment]
I haven't confirmed yet.

**Comment by Tyriar** [comment]
Probably caused by https://github.com/microsoft/vscode/issues/87066, https://github.com/microsoft/vscode/commit/2d2ac8f75b539d505443ac0733b196851c0b218d

**Comment by Tyriar** [comment]
Looks like it was caused by a bunch of changes in config land c71fa38dc98e22f147f5eccb4d46422dd943ade9, 4cdb067a8d9823f86f11f9b8b64e7cb19660742b, 0ecc745265d489e2a52abda5482c986e5737af48

**Comment by Tyriar** [comment]
@sandy081 why did you change it to `userValue` and `defaultValue` in c71fa38dc98e22f147f5eccb4d46422dd943ade9? `user` and `default` seem to only exist:

![image](https://user-images.githubusercontent.com/2193314/71603101-3365c480-2b10-11ea-853b-6f4d1d13cc31.png)

**Comment by sandy081** [comment]
@Tyriar How are you getting the above value?

**Comment by Tyriar** [comment]
@sandy081 printing `shellArgsConfigValue` here:

https://github.com/microsoft/vscode/commit/c71fa38dc98e22f147f5eccb4d46422dd943ade9#diff-85216c80e51fd42e2b7910df0bd3d26aR313

**Comment by sandy081** [comment]
I do not think `user` and `default` should hold the values. I have changed the inspect to return following

```ts
export interface IConfigurationValue<T> {

	readonly defaultValue?: T;
	readonly userValue?: T;
	readonly userLocalValue?: T;
	readonly userRemoteValue?: T;
	readonly workspaceValue?: T;
	readonly workspaceFolderValue?: T;
	readonly memoryValue?: T;
	readonly value?: T;

	readonly default?: { value?: T, override?: T };
	readonly user?: { value?: T, override?: T };
	readonly userLocal?: { value?: T, override?: T };
	readonly userRemote?: { value?: T, override?: T };
	readonly workspace?: { value?: T, override?: T };
	readonly workspaceFolder?: { value?: T, override?: T };
	readonly memory?: { value?: T, override?: T };
}
```

This is done to make it consistent on renderer and ext host and also to include override values.

Can you please provide me simple steps to reproduce this

**Comment by Tyriar** [comment]
@sandy081 log/debug here:

https://github.com/microsoft/vscode/blob/f548111c5c3435622c5f4fe42a121ed8ba28d543/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L312

1. Connect test resolver
2. (optional) Add `"terminal.integrated.shellArgs.windows": ["a", "b"]` to user settings
3. Add `"terminal.integrated.shellArgs.windows": ["c", "d"]` to remote settings
4. Open a terminal

![image](https://user-images.githubusercontent.com/2193314/71912318-248f9b00-312a-11ea-9f72-941e22d00470.png)

The fix to this seems to be changing `userValue` to `user` and `defaultValue` to `default`, however the interface says `IConfigurationService.inspect` will return `user`/`default` as a `{ value?: T, override?: T }`, but the log shows they are `T`?

https://github.com/microsoft/vscode/blob/f548111c5c3435622c5f4fe42a121ed8ba28d543/src/vs/platform/configuration/common/configuration.ts#L79

https://github.com/microsoft/vscode/blob/f548111c5c3435622c5f4fe42a121ed8ba28d543/src/vs/workbench/contrib/terminal/electron-browser/terminalInstanceService.ts#L103

**Comment by weinand** [comment]
Just to be clear: this bug does not only affect the setting's "shellArgs" property but "shell" and "automationShell" too. If a user has configured those, they are basically ignored!

**Comment by sandy081** [comment]
@Tyriar Missed updating `_apiInspectConfigToPlain` while refactoring. It did not complain because `fetchSetting` function does not have proper return type. 

https://github.com/microsoft/vscode/blob/7989db485eeec4a5ffcdff615ec57949b61ee01d/src/vs/workbench/api/node/extHostTerminalService.ts#L62-L67

Fixed `_apiInspectConfigToPlain` to return `defaultValue` and `userValue`.
