### ISSUE TITLE
[ini] Language Colorize working incorrectly for INI files

### ISSUE THREAD

**Issue by hcoona** [Microsoft/vscode#8709]
- VSCode Version: v1.2.1
- OS Version: Windows 10

Steps to Reproduce:
1. Change file type to INI
2. type "A=b;xxxx" in file content

Expected: "b;xxxx" colored as white
Actual: "b" in white but ";xxxx" in green

";xxxx" should only be regard as comments when there is no other contents in the line before ";"

**Comment by aeschli** [comment]
This issue was moved to demyte/language-cshtml#11
