### ISSUE TITLE
Top portion of the window is missing

### ISSUE THREAD

**Issue by vmetelkin-mdsol** [microsoft/vscode#87090]
Issue Type: <b>Bug</b>

In two monitor setup (extending main monitor) move the VS Code wondow to the secondary monitor and maximize. The top portion of the VS Code is missing. If the window is not maximized, everything looks normal.

![image](https://user-images.githubusercontent.com/16654963/70915506-f2d25b00-1fe7-11ea-81f6-709f136a2bb0.png)

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sbatten** [comment]
@vmetelkin-mdsol can you share information about your screen resolution, scaling settings, and positions for both the primary and secondary monitor?

**Comment by vmetelkin-mdsol** [comment]
@sbatten 
Would this screen shot give you necessary information:
![image](https://user-images.githubusercontent.com/16654963/70924452-83646780-1ff7-11ea-9890-18b724a654c3.png)

**Comment by maximdx** [comment]
It looks like I am not the only one suffering this issue:

Vs code version:
Version: 1.41.0 (system setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Vs code:
![image](https://user-images.githubusercontent.com/1274252/71151125-0d1d6a80-226e-11ea-834e-3a903dbd20e8.png)

My screen setting:
![image](https://user-images.githubusercontent.com/1274252/71151206-2de5c000-226e-11ea-98d5-c4aac0911b54.png)

The issue only happened on the secondary monitor. It works fine on the primary monitor.

**Comment by sbatten** [comment]
@maximdx I have not been able to reproduce this. Can you verify a few things:

1) Check that it does (not) reproduce with extensions disabled. `F1 > Reload with extensions disabled`

2) Check your setting for `window.titleBarStyle`.
