### ISSUE TITLE
Background color artifacts aligning with layers since v1.40.1

### ISSUE THREAD

**Issue by lgraziani2712** [microsoft/vscode#87097]
This is the bug:

![image](https://user-images.githubusercontent.com/15050200/70911230-30d37d00-1ff0-11ea-953e-cd47c247790c.png)

**VSCode version**: 1.41.0
OS: Ubuntu 18.04.3

**Comment by aeschli** [comment]
I don't see this. 

What theme is this? Is it only in the setting UI?

**Comment by lgraziani2712** [comment]
It happens with every theme. Not only for me but for my teammates too.
![image](https://user-images.githubusercontent.com/15050200/71000277-cab32c80-20b9-11ea-9834-b212efc88c33.png)
![image](https://user-images.githubusercontent.com/15050200/71000311-e1598380-20b9-11ea-87c3-2e3af6ad017b.png)
![image](https://user-images.githubusercontent.com/15050200/71000342-ef0f0900-20b9-11ea-8906-b82d04badbed.png)

The darker the theme, the harder is to notice it.

I did tried to reinstall it from zero but nothing happened

**Comment by aeschli** [comment]
Ok, with the blue theme can see it as well.

It's a Electorin/Chrome rendering issue as the regions are matching the rendering layers:
![image](https://user-images.githubusercontent.com/6461412/71004472-41fcb680-20e2-11ea-9544-0786a015d219.png)

You can workaround it by disabling the gpu acceleration:
`code --disable-gpu`

**Comment by lgraziani2712** [comment]
Nice! I can confirm is fixed with that flag

**Comment by MohamadKh75** [comment]
the `code --disable-gpu` flag doesn't fix it!

```
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.3.9600
```

**Comment by lgraziani2712** [comment]
This issue is still happing in linux in the latest version (v1.47.2)

**Comment by deepak1556** [comment]
Can you test the insiders version https://code.visualstudio.com/insiders/ that has a newer runtime, thanks!

**Comment by lgraziani2712** [comment]
Done! I can confirm that is fixed with the latest insiders version! Thank you! Feel free to close the issue

**Comment by deepak1556** [comment]
Thanks for the confirmation!

**Comment by deepak1556** [comment]
The fix will also be available in upcoming stable release.
