### ISSUE TITLE
System collapses while typing in ts angular

### ISSUE THREAD

**Issue by manugarcia101** [microsoft/vscode#87099]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by manugarcia101** [comment]
Issue Type: <b>Bug</b>

Normal angular project, reactive forms, it crash when applying custom validation, just while typing, it seems there is some incompatibility with js or ts especifications

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|15.56GB (8.79GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.9.1
tslint|eg2|1.0.44
prettier-vscode|esb|3.14.0
latex-workshop|Jam|8.4.2
vscode-clang|mit|0.2.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
vscode-typescript-tslint-plugin|ms-|1.2.3
prettier-standard-vscode|num|0.6.0
vscode-yaml|red|0.6.1
prettier-now|rem|1.4.9
pdf|tom|0.5.1
markdown-pdf|yza|1.4.1


</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
