### ISSUE TITLE
Adopt insert/replace range

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#87091]
This is for https://github.com/microsoft/vscode/issues/10266 and while TS doesn't have it in tsserver. To extra confidence we should make the Typescript extension use insert/replace ranges... The current logic is more complex than I expected, hence this issue. 

Also, I have noticed some usages of the document and its contents *after* [awaiting](https://github.com/microsoft/vscode/blob/16fffb122b1db1d48ea7fc462e8b66a5c121e074/extensions/typescript-language-features/src/features/completions.ts#L128) async-calls which is risky as it's likely that in-between the document has changed.

**Comment by mjbvz** [comment]
TypeScript issue: https://github.com/microsoft/TypeScript/issues/35602

**Comment by jrieken** [comment]
Would be nice if we have poor mans approach for simple cases while TS isn't ready yet

**Comment by mjbvz** [comment]
@jrieken This means that for most JS/TS completions, I will end up using `getWordRangeAtPosition`. Should I do this in the JS/TS extension, or will the default suggestion implementation handle it automatically this if I return a single range?

**Comment by jrieken** [comment]
> ...implementation handle it automatically this if I return a single range?

No, only when returning no range...

**Comment by mjbvz** [comment]
@jrieken I need to push this to next iteration. I'm not confident in making the change this close to endgame

**Comment by mjbvz** [comment]
@jrieken 9887559f17e25da37ab325ce653682bf85fd5b40 added basic support for this. There's a few cases where we need TS Server's help with this but I believe I've managed to handle most bases cases on the VS Code.

Let me know if you notice any issues with the new behavior

**Comment by mjbvz** [comment]
Closing this for verification. Will continue to track the TS api for this upstream

**Comment by connor4312** [comment]
Should snippets also replace in this mode?

```
w|indow
```

expands to

```
while (condition) {
	
}indow
``

**Comment by mjbvz** [comment]
Maybe? Ts doesn’t control snippet completions at all however; it’s all on the Vs Code side

**Comment by jrieken** [comment]
Snippets already support both modes when possible, see https://github.com/microsoft/vscode/issues/83834
