### ISSUE TITLE
My Mac won't let me open the VS code download in order for me to install it. 

### ISSUE THREAD

**Issue by eddystaff** [microsoft/vscode#87103]
I get this error message when trying to open the file:
"
“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
"

My Mac is all up to date this end too. Please help.

**Comment by Chris1904** [comment]
Have you tried opening it as an admin? And you're sure you downloaded it from the official vscode website?

**Comment by eddystaff** [comment]
yeah dude, all legit. And yeah, I'm the admin.

**Comment by Chris1904** [comment]
so `ctrl + right click -> open`  does not install it it properly?

**Comment by gjsjohnmurray** [comment]
See #74782
