### ISSUE TITLE
formatOnSave not working for specific files

### ISSUE THREAD

**Issue by drstonebraker** [microsoft/vscode#87109]
Issue Type: <b>Bug</b>

I have two typescript files, both in the same directory with the same .ts extension. For one file, the formatter seems to run and update the file every time I save the file. For the other file, the formatter does not run when I save the file, but it does work when I manually trigger the command pallette "Format Document" command. This behavior persists even after I restart the window.

I can't understand why it works for one file and doesn't work for the other, so I don't know how to give steps for someone else to reproduce the behavior, but it's an issue I've experienced many times and others have mentioned experiencing as well.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.2.17-1rodete3-amd64
Remote OS version: Linux x64 5.2.17-1rodete3-amd64
Remote OS version: Linux x64 5.2.17-1rodete3-amd64
Remote OS version: Linux x64 5.2.17-1rodete3-amd64
Remote OS version: Linux x64 5.2.17-1rodete3-amd64
Remote OS version: Linux x64 5.2.17-1rodete3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stonebraker.svl.corp.google.com|
|OS|Linux x64 5.2.17-1rodete3-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|187.61GB (88.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stonebraker.svl.corp.google.com|
|OS|Linux x64 5.2.17-1rodete3-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|187.61GB (88.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stonebraker.svl.corp.google.com|
|OS|Linux x64 5.2.17-1rodete3-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|187.61GB (88.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stonebraker.svl.corp.google.com|
|OS|Linux x64 5.2.17-1rodete3-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|187.61GB (88.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stonebraker.svl.corp.google.com|
|OS|Linux x64 5.2.17-1rodete3-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|187.61GB (88.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: stonebraker.svl.corp.google.com|
|OS|Linux x64 5.2.17-1rodete3-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|187.61GB (88.11GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
RelativePath|jak|1.4.0
atom-keybindings|ms-|3.0.6
clang-format|xav|1.9.0
vscode-proto3|zxh|0.3.0
Angular-BeastCode|Mik|8.1.2
remote-ssh|ms-|0.47.2
vscode-gn|npc|1.1.0
vscode-jsp|pth|0.0.3
code-settings-sync|Sha|3.4.3

</details>

**Comment by drstonebraker** [comment]
I just discovered the editor.formatOnSaveTimeout setting, and increasing the value solved my problem. Should there have been some kind of output in the "Problems" pane or something like that to make this problem more discoverable?

**Comment by jrieken** [comment]
The is the log and the log output channels that show these kinds of things.
