### ISSUE TITLE
Debugger Button Step Over Button Works Erroneously

### ISSUE THREAD

**Issue by HYUCM** [microsoft/vscode#87101]
Issue Type: <b>Bug</b>

I was trying to debug a small C++ project of mine, on Manjaro Linux, with gdb. I set my breakpoints and used ""stopAtEntry": true in launch.json config file. When I started debugging, the cursor was on the line of main, as expected. But then, after I clicked on the "step over" button, I expected the cursor to move on to the next line, which used to do in the past, but instead, it moved to one of the header files of my project, to the line that contains the definition of the constructor of the class I'm using. If I click "step over" again, the cursor moves on to another file, new_allocator.h, which I think is one of the standart libraries of C++.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 4.19.88-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 3214)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.71GB (3.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
code-gnu-global|aus|0.2.2
latex-workshop|Jam|8.4.2
cpptools|ms-|0.26.2

</details>

**Comment by isidorn** [comment]
This behavior is up to the C++ extension, thus please create an issue there https://github.com/microsoft/vscode-cpptools
