### ISSUE TITLE
SCM: Support `alt` commands for SCM title menu

### ISSUE THREAD

**Issue by DavidGoldman** [microsoft/vscode#87107]
The [documentation](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) for `contributes.menus` notes that `alt` commands can be used, which will show the alternative command if the user presses the `Alt` key while opening the menu.

Unfortunately this doesn't seem to work for the [SCM menus](https://code.visualstudio.com/api/extension-guides/scm-provider#menus), specifically `scm/title`. It would be convenient to use this functionality to change behavior of some commands while the `Alt` key is pressed.

e.g. for mercurial, push active revision vs. push all revisions in client

**Comment by jrieken** [comment]
In depends in what group you are trying this - it should work in the `navigation` group, the one that's rendered inline with icons. For native menu we unfortunately cannot offer this option because we lack the underlying APIs...

**Comment by DavidGoldman** [comment]
Ah, you're right - it does work for the `navigation` group but I was hoping it would work for the `inline` group. Which APIs are missing?

**Comment by jrieken** [comment]
The electron API doesn't allow us to update a (native) context menu while it shows...

**Comment by thomasvl** [comment]
If this isn't expected to work in all cases, they shouldn't the [contributes.menus](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) documentation mention where it does/doesn't work rather than implying it works in all cases?

**Comment by thomasvl** [comment]
ps - even if you can't update it while it is displayed, couldn't it still be support to show the alt if the key was down when the menu is first displayed?
