### ISSUE TITLE
Quickopen results does not stream results by folder

### ISSUE THREAD

**Issue by pelmers** [microsoft/vscode#87105]
Steps to Reproduce:

1. Ppen a workspace with one folder which is very large, and one folder which is much smaller
2. Use cmd-p file search and observe the spinner takes a long time to complete

I think this Promise.all() collects all the search results

https://github.com/microsoft/vscode/blob/84abfc2e32eb3a43f01febdf3cf244433f9a88de/src/vs/workbench/services/search/common/searchService.ts#L216

**Expected behavior**: Results from the smaller folder can come back immediately, and more results can stream in later from the slower search

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Quickopen sorts all results, mixed together in one list, so we need to wait for all searches to be done before displaying results.
