### ISSUE TITLE
gotoLocation multiple references option with "goto" value does not seem to work

### ISSUE THREAD

**Issue by coreylight** [microsoft/vscode#87106]
Issue Type: <b>Bug</b>

Previously I have used these settings successfully:

```json
  "editor.gotoLocation.multiple": "goto",
  "editor.gotoLocation.multipleReferences": "goto",
  "editor.gotoLocation.multipleImplementations": "goto"
```

But now with current version they do not seem to be respected.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
cucumberautocomplete|ale|2.14.1
vscode-apollo|apo|1.12.2
ascii-tree-generator|apr|1.2.1
compulim-vscode-closetag|Com|1.2.0
vscode-eslint|dba|2.0.4
prettier-vscode|esb|3.14.0
vscode-pull-request-github|Git|0.13.0
gc-excelviewer|Gra|2.1.32
vscode-peacock|joh|3.2.0
chat|kar|0.29.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|0.9.0
mssql|ms-|1.7.1
Go|ms-|0.11.9
sublime-keybindings|ms-|4.0.6
vsliveshare|ms-|1.0.1377
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.3
vscode-jest|Ort|3.0.2
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
code-spell-checker|str|1.7.20
highlight-matching-tag|vin|0.9.6
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
vscode-mdx-preview|xyc|0.2.2
markdown-all-in-one|yzh|2.6.1
sort-js-object-keys|zen|1.0.6

(3 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yes - we have deprecated `editor.gotoLocation.multiple` and all settings editor should show you are warning (please check). This setting is now different, more fine grained settings: `editor.gotoLocation.multipleDefinitions`, `editor.gotoLocation.multipleTypeDefinitions`, `editor.gotoLocation.multipleDeclarations`, `editor.gotoLocation.multipleImplementations`, `editor.gotoLocation.multipleReferences`

**Comment by coreylight** [comment]
Thanks @jrieken ! Seems to work now with those options.
