### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by bseigel** [microsoft/vscode#87104]
- VSCode Version: 1.41.0
- OS Version: Windows 10 64bit

Steps to Reproduce:
1. Choose any extension, click 'install'.
2. Process stalls. No network activity.

Does this issue occur when all extensions are disabled?: Yes/No
Could not get this command to run.
![extensionInstall](https://user-images.githubusercontent.com/26010821/70936309-a72fa980-2007-11ea-8db5-ae2a7a59410c.gif)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by bseigel** [comment]
Hi,

- No failed network requests.

- I can access the URL you provided.

Logs attached.

Please note - I am no longer even able to search extensions - no results appear.
![extensions](https://user-images.githubusercontent.com/26010821/71301471-10dfe880-2365-11ea-8bcc-b4282a5f29ec.png)

[exhost.log](https://github.com/microsoft/vscode/files/3990948/exhost.log)
[main.log](https://github.com/microsoft/vscode/files/3990949/main.log)

**Comment by sandy081** [comment]
Hey I would need shared and window logs and also console log of your current window. Please see above comment to know how to get them

**Comment by bseigel** [comment]
I attached the logs I could access in the previous message. For View Log, I only have the following options:

- Extension Host
- Main
- Window

See attached.
![viewLog](https://user-images.githubusercontent.com/26010821/71644536-99c52100-2c8f-11ea-8541-eaf89daf4caa.png)

**Comment by bseigel** [comment]
I'm also seeing software update fail repeatedly - I click 'update now', the program restarts, and the message comes back.

I'm happy to complete uninstall and reinstall VSCode in an effort to fix these issues - can you point me to instructions? Note - I want to completely remove it, including registry entries, so it doesn't pick up old data.

**Comment by sandy081** [comment]
Looks like there is an issue with your VS Code installation. Passing it on to @joaomoreno for more insights.

**Comment by bseigel** [comment]
@joaomoreno can you advise? Thanks.

**Comment by joaomoreno** [comment]
Just normally uninstall VS Code. Then, download it again and reinstall it. See whether that helps.

**Comment by bseigel** [comment]
@joaomoreno I tried an uninstall and reinstall previously, and problems persisted. I really need to remove it completely from the registry. Please advise.

**Comment by joaomoreno** [comment]
Does it work if you run with a different user data dir? `code --user-data-dir NEW_FOLDER`

**Comment by bseigel** [comment]
Can't even configure VS Code to run from command line, which I need to do in order to run it with different user data dir, I believe.
![shell](https://user-images.githubusercontent.com/26010821/72828106-9cd58080-3c41-11ea-9ae9-2cbe480bc2dc.png)

**Comment by joaomoreno** [comment]
In Windows, you should be able to just run from the command prompt, if you have chosen to add Code to the PATH during installation. The `shell command` command is only available for macOS.

**Comment by bseigel** [comment]
Thanks, that appears to work. It also appears that VS Code will use this new data directory by default when I open it normally. Is that correct?

Any idea why this happened, and how I can avoid the issue in the future?

**Comment by joaomoreno** [comment]
No, Code won't use that new data directory by default. I'm really not sure what is wrong with your default user data dir, but if you don't have any meaningful contents within, I suggest to simply remove it Code will create a new one.
