### ISSUE TITLE
Search results can differ between disk match and editor match

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8710]
@sandy081 not really something that you caused, but I thought I would file this because you seem to want to look into reducing debt in search land for disk match vs. editor buffer match.

Consider you have 1 match in a file and you edit the file to remove the match. The search results nicely update live and show that you no longer have results. However, once you close the file in the editor, its associated model gets disposed and search suddenly goes back to showing the disk result, which now is outdated and still shows the match. I think the disk result needs to be updated as well when the editor changes.

Here is a video showing the issue:

![jul-04-2016 09-06-56](https://cloud.githubusercontent.com/assets/900690/16553130/ad417114-41c6-11e6-811b-481ff77254e1.gif)

**Comment by sandy081** [comment]
@bpasero Yes, I am aware of this and I think there are few other such corner cases causing due to not proper sync between search models.

**Comment by sandy081** [comment]
Closing this as this will be fixed with #8515
