### ISSUE TITLE
Git is not found

### ISSUE THREAD

**Issue by PeterFromSweden** [microsoft/vscode#87102]
![VSCode-no-git](https://user-images.githubusercontent.com/5816270/70930835-69964500-2036-11ea-85c5-cfe37d106686.jpg)
Issue Type: <b>Bug</b>

Install VS Code
Open source control.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|
</details>Extensions: none

**Comment by dbaeumer** [comment]
Is the workspace you have opened under Git control ? The view is only populated if you open a folder which has a .git folder.

**Comment by divslinger** [comment]
Do you have the prettier extension installed? I have the same problem, disabling prettier solves it. Alternatively, waiting for 5 minutes helps too, it will eventually show up.

**Comment by joaomoreno** [comment]
Can you run `Git: Show Git Output`?

**Comment by eine** [comment]
@joaomoreno, this is the output I see:

```
Looking for git in: C:\msys64\usr\bin\git.exe
Using git 2.24.1 from C:\msys64\usr\bin\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
```

In a Terminal, `git` works as expected:

```sh
user@DESKTOP MINGW64 /t/vunit/vunit
# git version
git version 2.24.1
```

The relevant part of my settings:

```
    "git.path": "C:\\msys64\\usr\\bin\\git.exe",
    "terminal.integrated.shell.windows": "C:\\msys64\\usr\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["-li"],
    "terminal.integrated.env.windows":
    {
        "MSYSTEM": "MINGW64",
        "CHERE_INVOKING": "1",
    },
```

@divslinger, disabling/uninstalling prettier and/or waiting does not have any effect.

**Comment by rhires** [comment]
Is this related to #61491? For myself, I was also realizing that if I do a clone into a local folder, that {something} should git init the folder, too.

**Comment by eine** [comment]
I'm not sure about it. For me, exactly the same repos/folders that don't work on Windows, do work if I just run a container and attach VSCode to it. Note that it is the same filesystem and the same VSCode version. Hence, I don't think it has nothing to do with the content of the folders, but with VSCode's 'Source Control' feature being broken on Windows.

**Comment by joaomoreno** [comment]
You seem to be using MSYS Git. Can you install Git for Windows instead? https://git-scm.com/

**Comment by eine** [comment]
Unfortunately, I cannot. On some workstations I don't have admin permissions. Nevertheless, why would users install Git for Windows (which is a limited distribution) instead of using the one in MSYS2? I understand that MSYS2 can be a replacement for Git for Windows, but not the other way round.

**Comment by joaomoreno** [comment]
Sure, you can disable git with the `git.enabled` setting and hide the SCM view by right clicking it.

**Comment by eine** [comment]
> Sure, you can disable git with the `git.enabled` setting and hide the SCM view by right clicking it.

I tried to do so. Unfortunately, that seems to be a global setting. As a result, when I attach to a container (where a supported git exists) I need to remember to enable it again. Is it possible to set a different behaviour when it is native vs attached?

Ideally, VSCode would detect if it can show any relevant content in Source Control, and disable it otherwise.

**Comment by joaomoreno** [comment]
> Unfortunately, that seems to be a global setting.

You can have workspace settings as well, would that work?

**Comment by eine** [comment]
> > Unfortunately, that seems to be a global setting.
> 
> You can have workspace settings as well, would that work?

The workspace/folder is the same in both contexts. So, I'm working on Windows and whenever I need a tool that is only available/supported on GNU/Linux, I run a container by sharing the root of my workspace/folder and opening it in the attached window. Then, I can work on the same project/sources with two instances of VSCode: one on Windows with MSYS2 and another one in the container with the shell in it.

**Comment by joaomoreno** [comment]
Do you use the Remote Containers extension for that?

**Comment by eine** [comment]
> Do you use the Remote Containers extension for that?

Yes. By "attach" I mean using the "Remote - Containers" extension.

**Comment by joaomoreno** [comment]
Got it. I still suggest to install Git for Windows, as mentioned above.

**Comment by bowdenk7** [comment]
You can set container specific settings to enable only in a container where a supported version of git is installed.

https://code.visualstudio.com/docs/remote/containers#_container-specific-settings

**Comment by eine** [comment]
@bowdenk7, containers are not created/started from VSCode, but externally. Hence, there is no `devcontainer.json`. Is it possible to set those options in the "regular" settings?

@joaomoreno, I'm ok with using containers if MSYS2 is not supported by VSCode. It just seems to me that the UX could be improved slightly. It is misleading that git works perfectly when MSYS2 is used as a Terminal in VSCode, and yet the message is "No source control providers registered". Something along "No supported source control providers found" would be easier to understand.

**Comment by eine** [comment]
In case it was overlooked by others, the bat file in #4651 allows VSCode to partially support MSYS2's git. At least, changes are shown and "Source Control" tab is not empty.
