### ISSUE TITLE
[html] auto-complete on closing tags when pasting with space

### ISSUE THREAD

**Issue by helgemahrt** [microsoft/vscode#87118]
Issue Type: <b>Bug</b>

Same as: https://github.com/microsoft/vscode/issues/87067

In my opinion there is a bug here. Yes, the feature should create a mirror cursor on a matching tag, but when I'm pasting content with a leading space onto the opening tag, I'd expect the mirroring cursor to handle this like having typed the space manually.
I encounter this a lot because I want to copy some attribute to another tag. On new tags, like

, the closing ">" is right behind the tag name and therefore I include leading spaces when copying, so I can just put the cursor right at the end of the tag and paste. Having to manually press space is an additional step in my workflow and makes this feature rather cumbersome.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
jsonsort|hma|1.0.0
vscode-docker|ms-|0.9.0
vscode-asa|ms-|0.2.0
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
azure-account|ms-|0.8.7
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.8.2
cordova-tools|msj|1.9.0
debugger-for-chrome|msj|4.12.3
wow-bundle|Sep|1.3.0
code-spell-checker|str|1.7.20
azure-event-hub-explorer|Sum|0.1.2
azure-iot-toolkit|vsc|2.14.0

</details>

**Comment by octref** [comment]
Tracking in #87067.
