### ISSUE TITLE
No completion for "export default exports" modules

### ISSUE THREAD

**Issue by ithinkihaveacat** [Microsoft/vscode#8711]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. `git clone https://gist.github.com/ithinkihaveacat/ed5fc36db488b6e5ecb209fb2d31aa68`
2. `typings install`
3. open main.ts in VSCode
4. Note that there are no completions for `$.`. (`$.greet` should be a completion.)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9520

**Comment by dbaeumer** [comment]
Moving to TS team.
