### ISSUE TITLE
F12 go to definition is not searching

### ISSUE THREAD

**Issue by thkrishn** [microsoft/vscode#87112]
![image](https://user-images.githubusercontent.com/7133450/70943922-d2fe5f80-2006-11ea-887b-8ccbb2f758f3.png)

OS version - Win 10 1607 Enterprise 

Steps to Reproduce:
1. On the variables if I use F12 does not go to definition; I have tried the `Go > Go To Definition` from the menu as well; it does not start a search  I dont see a bar which indicates its searching)
2. I have re installed VS code twice; removed all extensions and tried it nothing seems to work 
But there is no issues on Code Insiders

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please give more details. What language are you using, does it work if you start with `--disable-extensions`?

**Comment by thkrishn** [comment]
I am using C++ ; I cannot really run with `--disable-extensions`  because I use remote SSH 
But I did try removing all extensions except remote SSH and experiment; but F12 still does not work 

I am seeing this issue since an update about 3-4 weeks ago
One more thing that I verified -- there is no double mapping on F12 key for it to complain

**Comment by dbaeumer** [comment]
@thkrishn are you using the C++ extension. If so please report the problem there. If not F12 is only available if you have installed an extension providing language smarts.

**Comment by thkrishn** [comment]
the only extension related to c++ is the one provided by msft (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)

I haven't made any changes in the extensions; and F12 was working until recently ;
The same extensions; F12 still works on my VS code insiders

**Comment by thkrishn** [comment]
The `Go to Definition` is not preset when I do a mouse right click on the variable 

![image](https://user-images.githubusercontent.com/7133450/71043200-b20b3c80-20e2-11ea-80be-0127bc9c61dc.png)



here is a screen shot from another machine where F12 is working
![image](https://user-images.githubusercontent.com/7133450/71043143-8ee08d00-20e2-11ea-8bbd-633d409b0a09.png)

**Comment by dbaeumer** [comment]
@jrieken could this be caused by the context menu Peek / Go to clean up?

**Comment by jrieken** [comment]
Highly unlikely - when the entry doesn't show then that means that there is no provider registered

**Comment by thkrishn** [comment]
> Highly unlikely - when the entry doesn't show then that means that there is no provider registered

is it something I have to do -- register a provider?

**Comment by thkrishn** [comment]
and one more thing
I keep getting this error, though I am connected to the internet 

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Framework Assemblies'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Runtime (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```

**Comment by dbaeumer** [comment]
This sounds like an extension problem. Please report the problem here: https://github.com/Microsoft/vscode-cpptools
