### ISSUE TITLE
API: allow an extension to get all keys it stored

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#87110]
We (python extension) have accidentally stored large contents in the global memento store.
This causes perf issues, as we have stored contents of user's files. If a user were to open a large notebook, we store the contents of the entire notebook in the global storage (as part of our custom persisting of unsaved notebook changes).

We'd like to clear these items (to resolve perf issues), however the keys are dynamically generated based on the file paths of files opened in the editor. Even though all of these dynamically generated keys are prefixed with a specific string, we are unable to clear them.

Please can we get a list of all of the keys? so we could clear them
Open to alternatives

**Comment by bpasero** [comment]
You can ask a user to run this action:

![image](https://user-images.githubusercontent.com/900690/70969973-81ed7a80-209d-11ea-9306-022949ef188e.png)

It will print all contents of workspace and global storage into the developer console.

However, when an extension uses storage, it will always get it's data stored under 1 key (the extension name + extension ID). We never allow to write directly into storage under a key that could conflict with other keys. In other words, all your data go under the same single key in storage and become a JSON object there.

Are you suggesting there needs to be API for you to retrieve the entire state object for the extension?

**Comment by DonJayamanne** [comment]
> Are you suggesting there needs to be API for you to retrieve the entire state object for the extension?

Yes, read write access.

The reason is we have inadvertently stored contents of files in the object. This is causing perf issues for users.
We have addressed the issue, however existing users will still have large objects due to the bug and we have no way of clearing the.
We're looking for a way to clear these old items from the object.

**Comment by bpasero** [comment]
I doubt we would do a one-off for this, but adding @jrieken to also comment.

The API I can think of is to get access to the full object that is persisted in global or workspace state for the extension.

**Comment by jrieken** [comment]
I think adding `Memento#keys():string[]` would be the best here - that's generic enough, not specific to this problem and allows to cleanup

**Comment by jrieken** [comment]
@DonJayamanne A simpler and much faster solution to your problem might be a look at our Memento implementation. Generally, this is *highly* discouraged but given the problem your are facing: The `Memento` implementation uses a private [`_value`](https://github.com/microsoft/vscode/blob/c842995673ffe4cc6b948b8d185e02b260eef1c9/src/vs/workbench/api/common/extHostMemento.ts#L17)-property which is a plain JavaScript object and using `Object.keys` on that should give you what you want..

**Comment by jrieken** [comment]
In the mid/short term we than not only add `keys` but also a way to remove a key, esp when there are many or when they are long. Maybe `globalState.update("key", undefined)` could do this implicit tho...

**Comment by DonJayamanne** [comment]
Thanks we'll be using `_value` to find the keys and clear the data.
FYI - The keys are also dynamically generated and mapped to file names (hence the difficulty, however searching the keys helps, as the items with faulty data have keys that start with a specific string).

**Comment by jrieken** [comment]
Great!

**Comment by bpasero** [comment]
@DonJayamanne assuming you are unblocked, moving this to backlog.

**Comment by bpasero** [comment]
I don't want to add API for nothing. Closing since this does not seem to be asked by others.

**Comment by eamodio** [comment]
I added the following api:

```ts
export interface Memento {

	/**
	 * The stored keys.
	 */
	readonly keys: readonly string[];
}
```

https://github.com/microsoft/vscode/blob/e657d42281487040b50374d482d34b3fb05eb377/src/vs/vscode.proposed.d.ts#L3325-L3335

**Comment by jrieken** [comment]
@eamodio To support older TS versions, the API is using `ReadonlyArray<foo>` over `readonly foo[]`

**Comment by eamodio** [comment]
Oh, I thought we had changed to the newer syntax, as I saw other instances in the `vscode.proposed.d.ts` file. I can switch it.
