### ISSUE TITLE
http://json-schema.org/schema# not recognized as valid $schema

### ISSUE THREAD

**Issue by projeffboy** [microsoft/vscode#87111]
Issue Type: <b>Bug</b>

1. Create JSON file
2. Paste -> {"$schema": "http://json-schema.org/schema#"}
3. Get yellow squiggly line saying -> Unable to parse content from 'http://json-schema.org/schema': Parse error at offset 0.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (19.47GB free)|
|Process Argv|C:\Users\etanjef\Downloads\manifest|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|2.0.4
vscode-lombok|Gab|0.9.9
vscode-azureappservice|ms-|0.16.2
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
azure-account|ms-|0.8.7
debugger-for-chrome|msj|4.12.3
java|red|0.54.2
vscode-xml|red|0.10.1
autoimport|ste|1.5.3
rf-intellisense|Tom|2.8.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.0

</details>

**Comment by aeschli** [comment]
@projeffboy  `https://json-schema.org/schema` is not resolvable. Why did you choose it?

**Comment by Hotell** [comment]
> @projeffboy `https://json-schema.org/schema` is not resolvable. Why did you choose it?

what do you mean by `not resolvable` ?

it is used for all angular tooling, I'm facing the same issue

**Comment by aeschli** [comment]
Ok I see in https://json-schema.org/understanding-json-schema/reference/schema.html how this is used.
I wasn't aware of it.
