### ISSUE TITLE
[rfe] list preference under edit menu on linux/gnome

### ISSUE THREAD

**Issue by ritzk** [microsoft/vscode#87116]
Preference should be listed under Edit menu option , when running under Linux. Currently, it is listed under File.

From https://wiki.gnome.org/Design/HIG/Planning/Configuration#Preferences_Windows
> Preferences windows should be accessible through the Preferences entry in the Edit menu, should one be provided.

**Comment by roblourens** [comment]
That might be right but to be honest, I don't think we should move it and confuse people after it's been there for a few years.
