### ISSUE TITLE
Debug Console: No auto closing of quotes

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#87124]
Version: 1.42.0-insider
Commit: 2d2ac8f75b539d505443ac0733b196851c0b218d
Date: 2019-12-16T12:08:26.094Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

Type `'` or `"` in debug console. There's no auto-closing.

**Comment by isidorn** [comment]
I agee. Since the debug console already closes the brackets I would expect that it also auto closes the quotes.

**Comment by isidorn** [comment]
Hmm even though I set `autoClosingQuotes` to `always` the Repl Input Editor never auto closes quotes.
However this nicely works for all brackets.
@alexdima might there be some option I am missing in the editor? Or do auto closing qutoes use a different controller for completions than the brackets (which might not be regsiterd for my simple code editor - just an idea)

**Comment by isidorn** [comment]
Now the debug console uses the mode of the current active editor. So we get coloring, indentation, auto closing of quotes.
@alexdima thanks for the gentle idea that we should be better than Chrome here

![Screenshot 2019-12-18 at 18 35 18](https://user-images.githubusercontent.com/1926584/71109300-359d5a00-21c5-11ea-8d2c-3c1a9622d03b.png)

**Comment by isidorn** [comment]
@octref can you please verify this works as expected when you find the time, so we add the verified label. Thanks!

**Comment by octref** [comment]
Nice!
