### ISSUE TITLE
Editor Font not sharp

### ISSUE THREAD

**Issue by OmarBoshra** [microsoft/vscode#87120]
Iam using windows 7 with vs code November 2019 (version 1.41) ,the editor font is not sharp and is kind of pexelated ,I've added a picture that compares it with Notpad3-mod an editor that uses sharp font text.

[![VS-code _vs_ NotPad3-mod][1]][1]

  [1]: https://i.stack.imgur.com/LATvD.png

**Comment by alexdima** [comment]
@OmarBoshra What font family and font size are you using?

**Comment by OmarBoshra** [comment]
I opened vs code today and it had sharp text ,don't know what happened but if you fixed it ,thank you.
