### ISSUE TITLE
Debug Console: Store as global variable

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#87125]
In Chrome, if you evaluate an object, you can store it as a global variable to use later:

![image](https://user-images.githubusercontent.com/4033249/70953458-2d56ea80-201e-11ea-9137-e434b0518f63.png)

In VS Code we can't do that.

One common case I run into is:

```js
let a = { b: 5 }

function f() {
  // breakpoint here
}
```

In the breakpoint, you **cannot** access `a`.

In Chrome I can store a as global and still evaluate it in the scope of the `f` function.

**Comment by isidorn** [comment]
I am not sure how language agnostic this feature would be.
What this feels like is that we should open the repl context menu to extensions and the the node / pwa would contribute this "Store as global variable" command. The next time the user does the evauluate the debug extension would be aware of the stored global variable.
However not for the next couple of milestones.

fyi @roblourens @connor4312

**Comment by connor4312** [comment]
Yep, I agree, an extension-contributed context menu item would be ideal here.
