### ISSUE TITLE
Follow link broken inside of Fedora toolbox container

### ISSUE THREAD

**Issue by mMerlin** [microsoft/vscode#87128]
Follow link does not work for standard urls when Visual Studio code is installed in a toolbox container.  In another case, for a different application, the fix was to provide the container access to `xdg-open` with a script.  That does not work here, so it appears that `code` does not use `xdg-open` to handle the urls.  The problem was encountered on a system with Fedora 31 Workstation installed.  To eliminate as many extraneous interactions as possible, I spun up a virtual machine from Fedora-Workstation-Live-x86_64-31-1.9.iso and tested there.  After `dnf upgrade` and reboot

```
5.3.15-300.fc31.x86_64
toolbox 0.0.17-1.fc31.noarch
code-1.41.0-1576089692.el7.x86_64
```

The full installation and test sequence used is shown below.  No extensions installed.  The install of libX11-xcb and libicu is needed because of [Missing dependencies in rpm package](https://github.com/microsoft/vscode/issues/17142).  The toolbox environment does not include a lot of packages that are installed by default in a fc31 workstation environment.

```sh
cd ~
mkdir bin
mkdir vscode
vi vscode/vscode.repo
<<<
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1\gpgkey=https://packages.microsoft.com/keys/microsoft.asc
>>>
vi vscode/test1.md
<<<
[go test2](test2.md)

[github](https://github.com)
>>>
vi vscode/test2.md
<<<
[go test1](test1.md)
>>>
vi vscode/code
<<<
#!/bin/sh
toolbox run --container test code "$@"
>>>
chmod +x vscode/code
vi vscode/xdg-open
<<<
#! /bin/sh
${TOOLBOX_PATH:+flatpak-spawn --host} /usr/bin/xdg-open "$@"
>>>
chmod +x vscode/xdg-open
xdg-open "https://github.com"
# result: github.com page opens in firefox
sudo dnf install toolbox
cp vscode/code bin
toolbox create --container test
toolbox enter --container test
xdg-open "https://github.com"
# result: `bash: xdg-open: command not found`
sudo cp vscode/vscode.repo /etc/yum.repos.d/
sudo dnf upgrade
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo dnf upgrade
sudo dnf install libX11-xcb libicu
sudo dnf install code
exit
# from toolbox container
code vscode
«test1.md»
«ctrl click test2.md»
«ctrl click test2.md»
«ctrl click github.com» ¦ Open «this does not do anything»
«close»
cp vscode/xdg-open bin
toolbox enter --container test
xdg-open "https://github.com"
# result: github.com page opens in firefox
exit
xdg-open "https://github.com"
# result: github.com page opens in firefox
code vscode
«test1.md»
«ctrl click test2.md»
«ctrl click test2.md»
«ctrl click github.com» ¦ Open «this does not do anything»
«close»
```

Restoring the virtual machine to a state before installing toobox, and using the same commands (except no install for libX11-xcb and libicu) to install visual studio code directly in the fc31 environment works fine.  Whatever technique is being used to attempt to open the link in a browser is not making it from the container to the host environment.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mMerlin** [comment]
vscodebot was rather far from the mark on that duplicate detection.  I just referenced the missing information to show why the extra packages needed to be installed.  Nothing at all to do with this issue … unless another missing package is what is causing follow link to fail.

**Comment by dbaeumer** [comment]
Starting with @bpasero as the owner of the URL service (according to Git :-))

**Comment by bpasero** [comment]
This may be an Electron issue because we rely on the protocol handler API of Electron to install handlers afaik.

**Comment by jmou** [comment]
I was having this issue (links not opening from VS Code inside toolbox), and creating an xdg-open script on my PATH works for me. The script is:

```
#!/bin/sh
exec flatpak-spawn --host xdg-open "$@"
```

**Comment by mMerlin** [comment]
As indicated in the original problem report, I (thought I) had implemented the fix jmou mentions.  With the information that it was working for him, I did some more digging.  

What happened was that I had my xdg-open script in a folder that was in PATH for the host environment, but not for the container **run** environment.  Using `toolbox enter` (apparently) runs the host environment shell command startup (profile), so from a shell inside the toolbox the script was available, and worked fine.  However, `toolbox run --container «» which xdg-open` reports

```log
which: no xdg-open in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

which does not include the extra folders in the host search path.  So vscode could not see it either.  The fix (that works) is to copy the script to one of those (shadow) folders inside of the toolbox.
