### ISSUE TITLE
Inivisible <200b> character not rendered as white space, hard to find source of bug

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#87127]
Issue Type: <b>Bug</b>

This code contains an invisible character that makes it very difficult to find, and thus difficult to find the source of bugs from this code:

```yaml
startup.camera_offset: [0, 2, 5]​ // <-- invisible character after the ]
manager.color_intensity: 100
```

I turned on "render whitespace" hoping I could find an issue in the text, but that didn't help.

It'd be great if rendering whitespace helped identify any invisible characters.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
lit-html|bie|1.11.1
toggle-format-on-save|cbr|0.2.0
gltf-vscode|ces|2.2.7
npm-intellisense|chr|1.3.0
javascript-ejs-support|Dig|1.1.3
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.14.0
terminal|for|0.0.10
kotlin|fwc|0.2.11
error-gutters|Igo|1.0.1
statusbarerror|Joe|0.4.0
vscode-styled-components|jpo|0.0.27
vscode-map-preview|jum|0.4.8
vue-beautify2|ker|0.0.3
git-graph|mhu|1.19.1
vscode-mesh-viewer|mic|0.0.10
vscode-docker|ms-|0.9.0
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.26.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1377
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
java|red|0.54.2
partial-diff|ryu|1.4.0
vscode-javascript-booster|sbu|0.11.0
vscode-3dviewer|sle|0.1.0
es6-string-html|Tob|1.8.8
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.20.0
vim|vsc|1.12.2
markdown-all-in-one|yzh|2.6.1
material-theme|zhu|3.2.1
vscode-proto3|zxh|0.3.0

(15 theme extensions excluded)

</details>

**Comment by trusktr** [comment]
If you paste those two lines in VS Code, you should be able to move the cursor after the `]` and it'll take an extra key stroke to move beyond the `]`.

**Comment by fz0000** [comment]
The reason why we can replace the space character with a visible dot is they have the same width.
But 200B is a **zero width space**. How could it be visible without breaking the code... 🤔 

If I were you, I will kick the guy's butt who inserted it in the code. 😠

**Comment by alexdima** [comment]
There are extensions in the marketplace that can help with this kind of issue, e.g. https://marketplace.visualstudio.com/items?itemName=nachocab.highlight-dodgy-characters
