### ISSUE TITLE
Fresh install of VSCode crash loops TS server

### ISSUE THREAD

**Issue by breeny** [microsoft/vscode#87137]
Issue Type: <b>Bug</b>

1. Fresh install VSCode
2. Open a JavaScript project
3. Typescript crash loops

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|-psn_0_24696716|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Please check the TS Server log to see what the first occurrence of the crash is:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. Back in VS Code, go to the `TypeScript` section of output panel
1. At the very top of this output, there should be a line that prints the path to the main server log. It should look like this (note the `<semantic>` part) :

```
[Info  - 4:06:59 PM] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20191111T144045/exthost1/vscode.typescript-language-features/tsserver-log-F2rDlk/tsserver.log
```

Please look through that log file for errors or stack traces (they should be near the end). If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
