### ISSUE TITLE
Debug Console: Cannot move cursor directly when having selection

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#87130]
Have this in your debug console:

![image](https://user-images.githubusercontent.com/4033249/70954768-604fad00-2023-11ea-9fa1-32c85bb7256e.png)

- Double click on `foo` to select it
- Press right arrow 🐛 This cancels selection instead of moving

**Comment by isidorn** [comment]
This behaves for me the same as it behaves in the editor. Can you please clarify what is the issue?
Are you having some setting in your editor which changes this behavior? Can you reproduce with fresh user data directory?

![pine](https://user-images.githubusercontent.com/1926584/70987565-72cbf400-20c0-11ea-97a2-6e784f033adc.gif)

**Comment by octref** [comment]
Ah, I'm sorry, in the editor I'm using Vim extension, so right arrow moves right in this case.

This is consistent with the editor so no fixing needed.
