### ISSUE TITLE
Debug Console: Preview evaluation result

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#87131]
When you have this expression in file:

```js
const obj = { a: 1, b: 2, c: 3 }
```

Typing it in Chrome console gives a preview of the evaluation result. VS Code doesn't do that.

![image](https://user-images.githubusercontent.com/4033249/70954985-1d420980-2024-11ea-94d5-5d434b80cc64.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/64949
