### ISSUE TITLE
Support to navigate up to out of workspace files from links inside the editor

### ISSUE THREAD

**Issue by hzmnet** [Microsoft/vscode#8713]
- VSCode Version:
- OS Version:

Steps to Reproduce:
文件路径提示错误<link rel="import" href="../../../../../../../../../../test.html">文件显示路径永远给限制在工作区 #HappyCoding 来自 @code
1. href Ctrl 打开的路径错误
2.

**Comment by joaomoreno** [comment]
Can you maybe find someone to translate the issue to English? I'm having a hard time understanding the problem.

@bpasero This might be that the user has an href link with `../../../..` and tries to double click and gets an error message.

**Comment by Emeryao** [comment]
@joaomoreno you are almost right man.
@hzmnet his problem is getting error if the href targetting out of the workspace folder.

PS: @hzmnet 个人认为：提issue还是用英文吧兄弟 而且你这个description也太草率了吧

**Comment by bpasero** [comment]
I do not think we allow to escape the workspace like that, at least when I try. Other relative links with "../" work for me though.

@Emeryao is the resulting path pointing outside of the workspace maybe?

**Comment by hzmnet** [comment]
Beloware the Paths of my html files

Polymer
     |-  component Dir.
     |             |- some.html
App
    |-  My Component Dir.
    |                 |-    test.html


I need to import  some Polymer component from component Dir.

But VSC. could always open the link like   "/app/component Dir./some.html" or not "/Polymer/component Dir./some.html"

even there enough quantity of "../../../../../../../../../../". the path VSC open still not over "App" this Dir.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
