### ISSUE TITLE
VSCode lost 2 hours worth of my changes. No way to recover it

### ISSUE THREAD

**Issue by nojvek** [microsoft/vscode#87134]
Not sure how to repro it.

I made a whole bunch of changes. I was going to git comit via the Source Control Panel. I even added a commit message. Git runs and suddenly shows me ({file} deleted) on my tab. I was totally taken aback, I closed the tab and tried to re-open in the hope that vscode probably has stale info. 

No way to recover the deleted file. Git commit did not commit, git reflog doesn't have the commit. Its gone. 

I really wish vscode had some other deleted file buffer. Losing changes is never fun.

**Comment by gjsjohnmurray** [comment]
Please tell us what version of VSCode you are running, and on what platform.

>Git runs

What did you see that told you Git had run at this point?

Does your settings.json file contain any entries beginning `git.` ? Are there any such settings at workspace level or folder level?

Any clues in the Git view of the Output tab?

**Comment by hoancmg** [comment]
I have the same problem.
I'm running VSCode 1.41.1, on Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
@nojvek As a Code veteran, you might already know that Code simply spanws `git commit`. So something in that process went wrong. Do you maybe have any commit hooks? Was there anything in the Git output? Have you seen this since?
