### ISSUE TITLE
Debug Console: Allow inline input

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#87133]
In Chrome I can evaluate expressions sequentially. My eyes can stay in the same place as I'm typing and evaluating:

![image](https://user-images.githubusercontent.com/4033249/70955139-a0fbf600-2024-11ea-834b-16a1133eb8ef.png)

In VS Code debuggers I have to always look up and down, each time I type and enter something:

![image](https://user-images.githubusercontent.com/4033249/70955295-2a132d00-2025-11ea-871b-9e297aa219b9.png)

Frequently, I have to refer to previous evaluation results for entering my current expressions. In Chrome console this is much easier than in VS Code.

**Comment by isidorn** [comment]
This is a fair feature request, and I see the benefits of the Chrome console (less eye movement).
However not something that I would tackle in the next couple of milestones > backlog.
