### ISSUE TITLE
marker list doesn't reuse editor

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8714]
- open settings (left and right editor)
- notice a warning showing in the marker list
- select the warning to open the file (which actually is the left editor)
- another editor open (in the right slot)

**Comment by sandy081** [comment]
@bpasero any idea why the workbench is opening Default settings resource in a different editor? 

Another observation
- Default settings file is named as settings.json instead of Default settings

**Comment by bpasero** [comment]
@sandy081 I guess this happens because the right editor has focus? we always open a new editor if it does not contain in the group.

**Comment by sandy081** [comment]
@bpasero Yes, right editor is in focus. Do you think is it a good idea to check if file to be opened is a settings file and delegate to Default settings file to open the file? So that opening this will always same behavior either from Command Pallette or from Problems view?

**Comment by jrieken** [comment]
I think that makes sense. I have a similar request for go to definition. Maybe we should think about a setting ala `reuseEditors`?

**Comment by bpasero** [comment]
I added a new option `revealIfOpened` to do this.

**Comment by sandy081** [comment]
@bpasero Thanks for adding this option. But this is not working in this case. Default settings are opened as a new editor even if I say revealIfOpened to true.

**Comment by bpasero** [comment]
@sandy081 how can I reproduce to get a warning from the settings?

**Comment by sandy081** [comment]
After discussing with @bpasero, it seems that Default settings file is a special file (readonly and not a real file) and workbench is not yet supporting them. Hence revealifOpened options is not helping in this case.

Making it related to #8918

**Comment by sandy081** [comment]
This is no longer applicable as Default settings are opened as secondary editor on LHS of main settings editor (just like diff).
