### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by Fosol** [microsoft/vscode#87148]
Intellisense isn't working.  Latest issues are with .netcore 3.1 and omnisharp.

I have .netcore 3.1 SDK installed.

C:\Program Files\dotnet\sdk\2.2.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): Error: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.

**Comment by theajack** [comment]
It's also happened to me, in version 1.41.0

![微信截图_20191217150704](https://user-images.githubusercontent.com/23377279/70972839-496e9080-20df-11ea-8152-0541799e57b0.png)

**Comment by theajack** [comment]
It disappeared after open vscode for a while.

Then I reinstalled the lower version(1.35.1) of vscode, it works ! 

![微信截图_20191217153155](https://user-images.githubusercontent.com/23377279/70974291-648ecf80-20e2-11ea-914d-732cef5fabb6.png)

I was so confused about this, and didn't expect it to be a bug！😂

**Comment by aplavsa** [comment]
Not working in React as well...
![image](https://user-images.githubusercontent.com/22588290/70977098-83bf3a00-20ad-11ea-95ad-a51e43e63405.png)
Nothing happens when you press CTRL+Space. Same happens for built-in javascript objects like Number and Arrays...

**Comment by dbaeumer** [comment]
Please file the issue against the OmniSharp extension here: https://github.com/OmniSharp/omnisharp-vscode

**Comment by Ronkiro** [comment]
@dbaeumer I don't think this is related to Omnisharp only.
There is some people talking about this problem in React Native too. (As #87151 and @aplavsa stated).

Isn't this passive to reopening?

**Comment by dbaeumer** [comment]
@Ronkiro thanks for pointing this out. Reopening...

**Comment by givionte** [comment]
Seems related to #87034

**Comment by jrieken** [comment]
This is both (guess work based on information fragments) - it seems that are issues with OmniSharp and/or TypeScript IntelliSense. Hence the dupe of #87034

**Comment by Fosol** [comment]
To fix I had to do the following;

omnisharp.json
```
{
  "MsBuild": {
    "UseLegacySdkResolver": true
  }
}
```
global.json
```
{
  "sdk": {
    "version": "3.1.100"
  }
}
```

**Comment by fanzkday** [comment]
@Fosol Where should I put the files?

**Comment by Fosol** [comment]
I put them in the root of my solution.

**Comment by zandiarash** [comment]
> 
> 
> @Fosol Where should I put the files?

I have the same problem, did the solution of dear @Fosol worked for you ?

**Comment by Tyrcheg** [comment]
@Fosol 's solution worked for me. Thanx!
@zandiarash
