### ISSUE TITLE
Word wrap bug

### ISSUE THREAD

**Issue by ShoichiAnda** [microsoft/vscode#87142]
Issue Type: <b>Bug</b>

Setting on is not reflected.
It is reflected immediately after setting, but a blank space suddenly appears on the right and a horizontal scroll occurs.

macOS Catalina 10.15.1
VSCode
バージョン: 1.41.0

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.2.0
githistory|don|0.4.11
gitlens|eam|10.2.0
php-debug|fel|1.13.0
smarty|imp|0.3.0
ftp-sync|luk|0.3.9
vscode-language-pack-ja|MS-|1.41.2
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|9.6.0

(2 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@ShoichiAnda Can you please post a screenshot or more detailed steps? Word wrap works correctly for me.

**Comment by ShoichiAnda** [comment]
Thank you for your reply.

I have a new understanding.
Code written in the editor wraps normally.
When a supplementary message such as a GIT log is displayed when the mouse
cursor is moved, if the display area is insufficient, horizontal scrolling
occurs without wrapping.

I closed this issue. Or remove this issue if possible in your operation.
it was different from the word wrap bug.

2019年12月17日(火) 22:57 Alexandru Dima <notifications@github.com>:
