### ISSUE TITLE
Notification leads to default website

### ISSUE THREAD

**Issue by thbkthf** [microsoft/vscode#87155]
We have written
Issue Type: <b>Bug</b>

Hello
Each time I get a notification like
"(team) Welcome to version 1.161.0 of the Azure Repos extension!"
and I click on the "Learn more..." button, I end up on the same default Microsoft website (https://www.microsoft.com/de-ch/?ref=aka) which has nothing to do with VSCode or the extension...
My fault? Something wrong in the config? I Just wanted to let you know...
Best regards
Andy

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (5.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
armview|ben|0.3.3
githistory|don|0.4.11
gitlens|eam|10.2.0
beautify|Hoo|1.5.0
rest-client|hum|0.23.0
compareit|in4|0.0.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
mssql|ms-|1.8.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
powershell|ms-|2019.11.0
vscode-node-azure-pack|ms-|0.0.10
vsliveshare|ms-|1.0.1377
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.2
arm-snippets|sam|1.4.19
azure-iot-toolkit|vsc|2.14.0
vscode-icons|vsc|9.6.0
gitblame|wad|3.0.1
json|Zai|1.0.2

(1 theme extensions excluded)

</details>
 the needed data into your clipboard because it was too large to send. Please paste.

**Comment by dbaeumer** [comment]
@thbkthf please file the bug against the corresponding Azure extension. Very likely here: https://github.com/Microsoft/azure-pipelines-vscode
