### ISSUE TITLE
Search ignores wildcards in .gitignore even for committed files

### ISSUE THREAD

**Issue by orgads** [microsoft/vscode#87150]
Issue Type: <b>Bug</b>

I have in .gitignore a wildcard rule for *.js.

I do have js files that are committed despite this ignore rule. These files are part of the project. The ignore rule is for generated files, which should not be committed.

I expect Search to include all the committed files when it automatically excludes files from .gitignore.

The list can be created by executing `git ls-files *.js` (or any other wildcard, of course).

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.3.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: my-vm|
|OS|Linux x64 5.3.0-24-generic|
|CPUs|Intel Core Processor (Skylake, IBRS) (4 x 2198)|
|Memory (System)|7.78GB (0.24GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
ripgrep does the search for us, and that's how that tool works. It's unlikely to be fixed upstream, sorry - https://github.com/BurntSushi/ripgrep/issues/1127
