### ISSUE TITLE
intellisense not working , ctrl + not goto function definition react native

### ISSUE THREAD

**Issue by jawadg** [microsoft/vscode#87151]
intellisense not working , ctrl + not goto function definition react native

**Comment by theajack** [comment]
@jawadg 

You could reinstall a [lower version](https://code.visualstudio.com/updates/v1_35)

[same issue](https://github.com/microsoft/vscode/issues/87148#issuecomment-566420131)

**Comment by fanzkday** [comment]
Me, too.
