### ISSUE TITLE
Losing content of unsaved files in workspace

### ISSUE THREAD

**Issue by puco** [microsoft/vscode#87156]
After upgrading to this Insider version a reopening my workspaces all the files which weren't saved yet are open as usual but the content in empty.

VS Code version:
Version: 1.42.0-insider (user setup)
Commit: 22a87bf3f259d3fcff66f636a9db611741c7e1c5
Date: 2019-12-17T05:41:30.616Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19037

Steps to Reproduce:

1. Have a previous Insiders version with `"files.hotExit": "onExitAndWindowClose"`
2. Open a workspace (in my case it was a WSL2 workspace)
3. Open a new file (Ctrl+N) and write something inside
4. Upgrade to new version
5. Reopen workspace

Expected results: File with content is there
Actual results: I see the the open tab (Untitled-1) but there is no content inside

Does this issue occur when all extensions are disabled?: Unfortunately no way to test

**Comment by bpasero** [comment]
...checking (and stopped insiders from distributing)

**Comment by bpasero** [comment]
Sorry for that, I pushed a fix and triggered new insider builds. Unfortunately there is currently no way to get this data back :-(. I will try to write a test for this case.

Broken with https://github.com/microsoft/vscode/commit/2b1bbfa63f2c5c65a074b5547ae92461082b9692 btw.

**Comment by puco** [comment]
If I have some workspaces which I haven't opened yet, will the files still be gone (if I upgrade before opening it). Meaning was it bug in upgrade process or opening the workspace?

**Comment by bpasero** [comment]
@puco that should be fine if you update VSCode before opening these workspaces. It is a bug that only occurs when you open that workspace with backups (which unfortunately is the default setting for most).

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/16125bcbe3ad883a7a3f0b3abbfae280e1018b54 adds a test for this.
