### ISSUE TITLE
Unexpected terminal right padding space

### ISSUE THREAD

**Issue by esonic** [microsoft/vscode#87153]
- VSCode Version: 1.41.0
- OS Version: Windows 10  1909

After I upgrade vscode from 1.40.2 to 1.41.0, this annoying right padding in terminal occurs.
I searched existing issues and found this one #22949 is related, which said Windows needs patch. But my Windows is already updated to latest version.

![WXWorkCapture_15765705609222](https://user-images.githubusercontent.com/5556689/70978213-4f1da380-20ea-11ea-9135-89da12dd2b48.png)

![WXWorkCapture_15765706403590](https://user-images.githubusercontent.com/5556689/70978216-52189400-20ea-11ea-8fcf-f5baeb7ca779.png)

**Comment by KoltonG** [comment]
Facing this issue as well! Here is the version that I am using.
```
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

**Comment by yedhink** [comment]
I'm also facing the same issue with the `insider` version.
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:58:23.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-72-generic
```

![Screenshot_20191221_165539](https://user-images.githubusercontent.com/31244999/71307372-5d81fd00-2413-11ea-9b3b-9f129d845ef4.png)

**Comment by Tyriar** [comment]
Note that this depends on the renderer being used, the char width differs between dom and the others and we use the dom sizing to determine the size as it's the widest. Since renderers aren't changed much I guess we should do a resize to fix this up.

This is blocked on an upstream API to pull char dimensions https://github.com/xtermjs/xterm.js/issues/702

**Comment by yedhink** [comment]
@Tyriar Yea.  As a temporary solution I think dom based rendering can be used since it renders maximum column width.
