### ISSUE TITLE
Keep a folder closed option

### ISSUE THREAD

**Issue by vianneyguesdon** [microsoft/vscode#87157]
It would be nice to be able to keep a folder always closed, for example the node modules folder that is very big and open itself for unknown reasons.

Another right click on the folder would give the opportunity to remove the "keep closed" option.

**Comment by mfearby** [comment]
I sometimes Ctrl+Click on something which opens the corresponding file in node_modules, and always have to go back and close that folder because it's so huge. Doesn't happen often, but when it does, it annoys me :-)

**Comment by vianneyguesdon** [comment]
This has been solved in another way with the "close all folder" button introduced in the 1.42.
Great work ! This 1.43 is really good !!
