### ISSUE TITLE
Introduce a context for opened editors and use for "Close Editor"

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#8715]
We have one action to close the active editor that closes the window if the last editor is closed. We could just introduce a new keybinding context for when editors are visible or not and reuse the existing "Close Editor" and "Close Window" actions.

Original:

<kbd>⌘W</kbd> closes documents. When no documents are open, it would then close the window. It doesn't do that any more.

**Comment by bpasero** [comment]
Kim-Possible 👎 . The command that runs does close the window: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/actions.ts#L53

So it must be something else, did you rebind Cmd+W maybe?

**Comment by joaomoreno** [comment]
Yeah, you're right, of course. 👍 

We should fix the keybindings, then. Currently it is:

```json
{ "key": "cmd+w",                 "command": "workbench.action.closeActiveEditor" }
```

Which implicitly closes the window when no editors are open.

Should we come up with a new `editorIsOpen` context, or similar? Thus we could do the following and I would still be able to overwrite cmd+w:

```json
{ "key": "cmd+w",                 "command": "workbench.action.closeActiveEditor",
                                  "when": "editorIsOpen" },
{ "key": "cmd+w",                 "command": "workbench.action.closeWindow" },
```

**Comment by bpasero** [comment]
That is a cool idea, however would break every user that has workbench.action.closeActiveEditor associated to a different keybinding and who is still expecting the window to close when the last editor closes...

**Comment by joaomoreno** [comment]
Yup... We can always release note it, I don't think there are many users in that camp.

**Comment by bpasero** [comment]
Please verify that Cmd+W still closes the window when no editor is open and there is a new keybinding context for when an editor is open.
