### ISSUE TITLE
Opening search viewlet does not detect potential new matches in new files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#87168]
Cataling, VS Code insiders

1. Search for something in our repository, for example "IsidorHatesWinter" -> no results
2. Close search viewlet, add "IsidorHatesWinter" to some file
3. Open search vielwet again -> no results 🐛 

Opening search viewlet should automatically update all results. Currently it only updates for the files that were already in the results. If some file appears as a new reuslt, it will not be detected

**Comment by JacksonKearl** [comment]
This amounts to rerunning the search on click to open the viewlet. We had this for a bit, but it caused issues when people dismissed results then clicked into the viewlet and those results got brought back (#90962).  #91901 discusses next steps for configuring this.
