### ISSUE TITLE
vscode doc just spell out where codicons are supported

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#87165]
Today the vscode.d.ts-doc does mention when a string ends up a message (human-readable....) but it doesn't spell out all places in which messages also support the themeicon-syntax, e.g `$(zap)`. These are all messages that use human-readable strings.I can make the doc changes but I need to know if a message support codicon or not. 

This is the process:

* add a ✅ for messages that support codicons
* do *not* add a check for messages that don't support codicons
* last un-assign yourself (I will make a uniform doc update)

This is the list:

- [x] QuickPickItem#label @chrmarti 
- [x] QuickPickItem#description @chrmarti 
- [x] QuickPickItem#detail @chrmarti 
- [ ] InputBoxOptions#validate @chrmarti 
- [ ] [Open|Save]DialogOptions#openLabel @jrieken 
- [ ] [Open|Save]DialogOptions#filters @jrieken 
- [ ] CodeAction#title @mjbvz ❌ 
- [x] MarkdownString @eamodio 
- [ ] DocumentSymbolProviderMetadata#label @jrieken 
- [ ] ParameterInformation#documentation @jrieken 
- [ ] SignatureInformation#documentation @jrieken 
- [ ] ComplationItem#detail @jrieken 
- [ ] ComplationItem#documentation @jrieken 
- [ ] Diagnostic#message @sandy081 
- [ ] Diagnostic#source @sandy081 
- [x] OutputChannel#name @isidorn 
- [x] Task#source @alexr00 
- [ ] createTerminal#name @Tyriar 
- [ ] TerminalOptions#name @Tyriar 
- [ ] ExtensionTerminalOptions#name @Tyriar 
- [ ] TreeView#message @alexr00 
- [ ] TreeItem#label @alexr00 
- [ ] TreeItem#description @alexr00 
- [ ] ProgressOptions#title @jrieken 
- [ ] SourceControl#label 
- [ ] CommentThread#label @RMacfarlane 
- [ ] CommentReaction#label @RMacfarlane 
- [ ] Comment#label @RMacfarlane 
- [ ] CommentController#label @RMacfarlane

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode

**Comment by isidorn** [comment]
`OutputChannel.name` does not currently support codicons since the name is shown in the select box dropdown. @sandy081 correct me if I am wrong here and if it was added recently.

**Comment by Tyriar** [comment]
Terminal names don't (and likely won't ever) support icons

**Comment by sandy081** [comment]
Yes, `OutputChannel.name` does not support codicons.

**Comment by alexr00** [comment]
Task source does support codicons.
TreeView message, TreeItem label, and TreeItem description do not support codicons.

**Comment by chrmarti** [comment]
QuickPickItem supports codicons, InputBox's validation message doesn't. (Thanks for filling in.)

**Comment by jrieken** [comment]
@RMacfarlane ping

**Comment by RMacfarlane** [comment]
@jrieken CommentThread#label, CommentReaction#label, Comment#label, and CommentController#label all do not currently support codicons

**Comment by jrieken** [comment]
Thanks everyone
