### ISSUE TITLE
Simplify initial debug experience even more

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#87162]
as discussed:
- rename "Debug" to "Run and Debug"
- remove "Run" button

**Comment by isidorn** [comment]
I have removed the Run action and now there is only one Run and Debug. If we know what is being debugged the title is "Run and Debug LABEL (SHORTCUT)". For example:

![Screenshot 2019-12-23 at 17 46 03](https://user-images.githubusercontent.com/1926584/71369817-3448a480-25ac-11ea-9414-4804fd69d5e2.png)


To align with this I have renamed the view to be Run and Debug (previously Debug and Run)

**Comment by isidorn** [comment]
As a follow up work I have created this issue in the Python repository so we start a discussion if it is useful for extension to contribute custom start view https://github.com/microsoft/vscode-python/issues/9268
If this ends up being a fruitful discussion with some outcome I plan to create similar issues for other debuggers.

fyi @connor4312 @roblourens
