### ISSUE TITLE
To long text in statusbar.currentProblem covers right side statusbar items 

### ISSUE THREAD

**Issue by pdziewa** [microsoft/vscode#87163]
Issue Type: <b>Bug</b>

1. Enable `problems.showCurrentInStatus`
2. Find problem/error with long message.
3. Select that problem.

![Screenshot from 2019-12-17 10-38-15](https://user-images.githubusercontent.com/2640714/70985469-7b223000-20bc-11ea-9d0e-438454f0737e.png)

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 2828)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|31.31GB (8.15GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
/duplicate 

#84258

**Comment by sandy081** [comment]
Reopening this to have a specific fix for this case.

**Comment by RMacfarlane** [comment]
I still see the right side items being pushed out of view:
![Screen Shot 2020-01-29 at 12 53 26 PM](https://user-images.githubusercontent.com/3672607/73396513-6a0d3700-4296-11ea-971a-42c7b31826a4.png)

**Comment by sandy081** [comment]
There is no fix here and it marked duplicate
