### ISSUE TITLE
Failed tsserver request should show some message in the UI

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#8716]
- VSCode Version: 1.3.0
- OS Version: all

If a tsserver request fails we currently show an empty result. We need to investigate to make the failure more prominent.

**Comment by MLefebvreICO** [comment]
When can we expect this to be done ? I'm getting tired of restarting vscode without knowing why it failed .. :/

**Comment by dbaeumer** [comment]
@MLefebvreICO if this happens frequently to you, you can enable tracing. That even helps reporting issues. Do the following: 

* add setting `"typescript.tsserver.trace": "messages"`
* open Output view and switch to TypeScript channel. (the channel is only visible fter you opened the first TS/JS file)

All requests send to the server a logged in the output channel with information about success and failure.

**Comment by MLefebvreICO** [comment]
@dbaeumer I changed my version of TypeScript (Had a custom one they did to test out the errors) to `1.9.0-dev.20160609-1.0` and it seems to be returning a message properly now.

Maybe the TS server was not returning the information properly to vscode before therefore resulting in no  message shown in vscode ?!

I'll keep an eye on it and come back if I don't have a message shown.

**Comment by dbaeumer** [comment]
This got addressed. Failing requests are now logged to the Output channel.
