### ISSUE TITLE
Add QUIC support?

### ISSUE THREAD

**Issue by mrconter1** [microsoft/vscode#87174]
I am currently developing a extension which relies on low latency. One nice addition to see would be to enable QUIC support for the editor. It provides much lower setup latency and around 7% of all traffic on the Internet today consists of QUIC traffic.

**Comment by IllusionMH** [comment]
I thought that VS Code doesn't provide any API to perform network requests from extension host.

Extension author can use any Node.js network client they want: default http/http2/https or something else. Am I missing something?

**Comment by dbaeumer** [comment]
@mrconter1 can you please be a little bit more specific were you think QUIC support should be used.

**Comment by mrconter1** [comment]
If would nice to be able to have an extension being compatible with a QUIC server. If I fetch an JSON from a URL on my website it should be able to do it with QUIC.

**Comment by dbaeumer** [comment]
It is still not clear to me what you are looking for. Our description sounds more like a npm node module that an extension author can use? Can you provide me with a concrete example.
