### ISSUE TITLE
Negative filtering in Problems panel (exclude items that match text)

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#87175]
I'd like to be able to do something like this:

![Screenshot 2019-12-17 at 14 38 07](https://user-images.githubusercontent.com/101152/71000028-dbc06580-20da-11ea-9895-990d32dc08cf.png)

to filter out spelling errors. For files, the `!` syntax is supported, e.g., `!not-this-file.txt`, but I can't make negative search work for text / strings.

**Comment by sandy081** [comment]
#83775
