### ISSUE TITLE
Zero Click Auto Update

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vscode#87179]
Browser-like updates which don't require clicks would be nice. 

1. Auto-download
2. Auto-install / prepare
3. Activate new version on restart.

https://www.leeholmes.com/blog/2017/02/03/setting-visual-studio-code-to-auto-update-in-the-background/

**Comment by joaomoreno** [comment]
We support this for both macOS and Windows (user install).

**Comment by OlafvdSpek** [comment]
How?

AFAIK one has to do multiple 'clicks' to update VSCode.
