### ISSUE TITLE
Save electron-main state periodically to prevent loss on shutdown or reboot

### ISSUE THREAD

**Issue by umdstu** [microsoft/vscode#87171]
Existing Issue (Locked): #207

- VSCode Versions: ~1.25 to 1.40
- OS Version: WIndows 10

Steps to Reproduce:

1. Open Vscode 
2. Open (and Select) a Folder
3. New Window
4. Open (and Select) another Folder
~~ You now have two Windows / Folders open ~~
5. Log out of Windows
6. Log back into Windows
7. Launch VSCode
~~ Only one of the two Windows from before will open.~~

My understanding  was that #207 was suppose to add/fix this. It's also a bit confusing as there have been multiple configuration settings discussed, to include:
```
{
  "window.reopenFolders": "all",
  "window.reopenWindows": "all",
  "window.restoreWindows": "all" ## Control how windows are being reopened after a restart
}
```
However, only the latter is identified as an known configuration setting. Does "window.restoreWindows" not apply to  Windows > Signout ? Is there a different setting that does?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by umdstu** [comment]
@bpasero At your convenience, please take a look as this one is (possibly) linked to a previous issue of yours, Thanks.

**Comment by bpasero** [comment]
@umdstu are you logging out of windows while VSCode is running? this will terminate the process and leave us no normal shutdown sequence. In order to restore window state, we currently require a clean shutdown.

**Comment by umdstu** [comment]
Ah yes, I absolutely am logging out while VSCode is running.

How does that work though if I have to close each of the windows manually, then there would be no 'state' to return to once logged back in, right? I will have to test but I think it would just open the last window you closed.

The problem with manually closing windows is that it forces you to save untitled/unsaved tabs/files (Scratch pads for me); maybe i'm missing a setting though. This works well when you don't manually close the windows.

Would #12058 make this any better?

**Comment by bpasero** [comment]
@umdstu you don't have to close windows one by one, simply pick File > Exit and you are all set. 

Yes #12058 is relevant, though this particular state is not persisted in the same way. It would need another fix. I will rename this issue to reflect that.

**Comment by umdstu** [comment]
Ok thanks for the info on Exiting all at once, and thanks for updating the issue to reflect the actual situation here!

**Comment by bpasero** [comment]
I pushed a change to save the window state also when any window looses focus (e.g. when reaching to the Windows signout button it should persist). I hope this strategy resolves the issue properly, maybe you could verify in tomorrows insider build.

**Comment by bpasero** [comment]
**Verification:** make a change to the window dimensions or window position and then alt+tab to another app and click the OS restart button. Verify that after restart when you open VSCode, the window opens in that position and size.
