### ISSUE TITLE
Bottom panels no longer remember previous height when reopening workspace

### ISSUE THREAD

**Issue by pdanpdan** [microsoft/vscode#87173]
Issue Type: <b>Bug</b>

After updating to 1.42 insiders the bottom panels (Problems, Output, ...) always start with a default height when I change workspace or open VSCode.

VS Code version: Code - Insiders 1.42.0-insider (241d4048aabc31db0baed66bb3d58cf3210d981d, 2019-12-17T10:43:45.626Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
project-manager|ale|10.9.1
i18n-ally|ant|1.6.0
gitkraken-glo|axo|1.1.0
color-info|bie|0.5.1
markdown-mermaid|bie|1.4.1
gitignore|cod|0.6.0
transformer|dak|1.6.0
vscode-eslint|dba|2.0.6
githistory|don|0.4.11
xml|Dot|2.5.0
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
auto-close-tag|for|0.5.6
vscode-pull-request-github|Git|0.13.0
sass-lint|gle|1.0.6
asciidoctor-vscode|joa|2.7.7
l13-diff|L13|0.21.0
rainbow-csv|mec|1.3.1
git-graph|mhu|1.19.1
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
sqltools|mtx|0.21.5
vscode-json-editor|nic|0.2.3
vetur|oct|0.22.6
vuehelper|oys|0.1.0
vscode-versionlens|pfl|0.24.0
vscode-sort-json|ric|1.18.0
vscode-gtm|s3r|0.2.0
todotasks|san|0.5.0
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.7.1
language-stylus|sys|1.11.0
gitflow|vec|1.2.1
markdown-all-in-one|yzh|2.6.1
cursorCharCode|zei|0.1.1
material-theme|zhu|3.2.1

</details>

**Comment by isidorn** [comment]
I can repro this with insiders: changing workspace does not preserve panel size.
This works fine with stable.
So it seems like previously we would store the panel height in user storage, and now this changed to workspace storage. 
Forwarding to @sbatten since this is caused by his refactoring. 

Code pointer in case it is needed https://github.com/Microsoft/vscode/blob/d79953fa273a80b118041eef93342d1ff088378c/src/vs/workbench/browser/layout.ts#L901

**Comment by sbatten** [comment]
reverted the change for another bug, going to fix another way. https://github.com/microsoft/vscode/commit/72dfc13b730a8398b9aef746664d5697a975ad50
