### ISSUE TITLE
No ANSI output from 'tsc --pretty' task

### ISSUE THREAD

**Issue by pierredewilde** [Microsoft/vscode#8717]
- VSCode Version: 1.2.1
- OS Version: Mac OS X El Capitan 10.11.5

Steps to Reproduce:
1.  tasks.json

```
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["--pretty"],
    "problemMatcher": "$tsc"
}
```
1. test.ts

```
dummy;
```
1. ctrl+p task tsc

```
[100;30m1 dummy;
[100;30m  ~~~~~
test.ts(1,1): error TS2304: Cannot find name 'dummy'.
```

Running 'tsc --pretty' manually from integrated terminal displays ANSI codes correctly.

**Comment by joaomoreno** [comment]
cc @isidorn @bpasero

**Comment by bpasero** [comment]
Looks like we fail to strip some ANSI codes?

**Comment by isidorn** [comment]
Dup of #571?

**Comment by bpasero** [comment]
Well as long as we do not support ANSI colors we need to ensure they are all removed from the output. In the screen shot it looks like they are still in.

**Comment by isidorn** [comment]
@pierredewilde what version of typescript do you have? I can not get the pretty command to print out ansi codes as you.

**Comment by pierredewilde** [comment]
```
$ tsc -v
Version 1.8.10
```

**Comment by isidorn** [comment]
We accept PRs that fix this
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L285

**Comment by dbaeumer** [comment]
@isidorn with the new task runner this will run in the terminal which will have proper ANSI control sequence handling.

**Comment by isidorn** [comment]
Then this should work -> closing
