### ISSUE TITLE
[html] mirror cursor: issues when pasting new content that is not a tag

### ISSUE THREAD

**Issue by Kirubelabr** [microsoft/vscode#87170]
Issue Type: <b>Bug</b>

Trying to paste additional info i.e. 'class' on existing div tag it adds extra cursor on the closing tag too and good to change to any other HTML tags. But while pasting some CSS class or anything that includes space at the beginning it also adds it on the closing tag and leads to HTML template parse errors.
To reproduce: paste info on HTML div tag with leading space.
i.e. paste ` class="page-wrapper"` in an existing div tag
<div></div> // first
<div class="page-wrapper"></div class="page-wrapper"> //

it should only paste content on oppening tag.
<div  class="page-wrapper"></div>

Please fix this.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.84GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
flutter-snippets|ale|2.0.0
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
vscode-eslint|dba|2.0.6
githistory|don|0.4.11
auto-close-tag|for|0.5.6
vscode-react-native|msj|0.13.2
awesome-flutter-snippets|Nas|2.0.3
material-icon-theme|PKi|3.9.2
vscode-scss-formatter|sib|1.4.2
code-spell-checker|str|1.7.20
vscode-icons|vsc|9.6.0
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.19.0

</details>

**Comment by jsgoupil** [comment]
https://github.com/microsoft/vscode/issues/87067
