### ISSUE TITLE
Keyboard shortcut for File > Exit

### ISSUE THREAD

**Issue by umdstu** [microsoft/vscode#87189]
Searched Open and Closed issues, no Titles to indicate this has been discussed yet.

There is no keyboard combination/shortcut associated with the File > Exit menu (at least on Windows 10). It would be great if this could be done, or at least configurable.

Thanks

**Comment by n00ne1mportant** [comment]
I'm not seeing it...
CTRL + Q on my machine by default.
CTRL + W to close a single file (same as chrome tab close)
if you try it with no files open it will close the program
ALT+F4 as universal program close works as well

I'm running Linux most of the time but it works the Windows pretty much the same....
:confused:

**Comment by umdstu** [comment]
Assuming maybe you mean the command key? Unless you’ve remapped something.

But yeah, command q is my go-to on my Mac. I’ll have to check how alt f4
behaves tomorrow at work. I’m wondering if it’s graceful or not, which
vscode has some issues with.

Thanks for the idea.

If it is graceful then perhaps it can be added to the File > Exit text.

**Comment by LordScree** [comment]
CTRL+F4 also works as a graceful "Close File" (tried on Windows).

You can also use ALT F X to call **F**ile E**x**it.

**Comment by bpasero** [comment]
```json
{
  "key": "<your key>",
  "command": "workbench.action.quit"
}
```

**Comment by umdstu** [comment]
CTRL + F4 does not work as it prompts to saved Untitled and Unsaved files (rather than caching).
ALT + F + X did work though

@bpasero's  solution is even better though, I should have thought of this. Now it's binded like on my Mac (or as close as I can get) with ALT + Q.

Thanks for the help all, and sorry to have wasted your time @bpasero !

**Comment by LordScree** [comment]
That is a good point about the caching!
