### ISSUE TITLE
Debug Takes Too Long to Start

### ISSUE THREAD

**Issue by arielspalter** [microsoft/vscode#87184]
Issue Type: <b>Bug</b>

When starting to debug, gdb takes about 3 minutes until execution. It appears like it's stuck on extensions activation stage. The issue seemed to start after an update on December 17th 2019.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.14.0
cpptools|ms-|0.26.2
html5-boilerplate|sid|1.0.3
ReactSnippets|xab|2.4.0

</details>

**Comment by dbaeumer** [comment]
Might be C++ related.

**Comment by isidorn** [comment]
Yes, please file this against the C++ extension here so they investigate first. Thank you
https://github.com/microsoft/vscode-cpptools
