### ISSUE TITLE
Search is broken when seeding search string from selection

### ISSUE THREAD

**Issue by jschank** [microsoft/vscode#87186]
Issue Type: <b>Bug</b>

Here is my experience with search.
I see a symbol I want to search for.
I select it.
I hit ctrl/cmd-f, and the search gets seeded with my symbol.
I hit cmf-g to go to the next occurence, but there aren't any.

There are no futher occurrences because seeding from selection, ALSO selects to only search within the selection. Which happens to still be my selected symbol.

Much gyrations then ensue to ensure that, no there is no selection, and yes, please search for the next occurrence of that thing I highlighted.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

**Comment by rebornix** [comment]
@jschank sorry for reaching out late, could you provide more details about how to reproduce this issue? Like text samples and keyword you are using?

**Comment by jschank** [comment]
I think the problem is really unexpected behavior and ingrained habits.

In this case I am used to selecting the string that I want to populate the search dialog with.
Whereas, in VS Code, you simply put your cursor in the string you want to search for. 

In my case, my habit conflicts with useful behavior, because when I select the string first. The search gets restricted to the selection (as you can see that would be pretty useless)

Perhaps, the restrict to selection should only be active when the selection is more than a single word. Dunno.

I just have to break a years old habit. Heh. not so easy.

Thanks,
John

**Comment by roblourens** [comment]
It sounds like maybe you have the `editor.emptySelectionClipboard` setting enabled?

**Comment by jschank** [comment]
Hmmm, Thanks for the suggestion, that does seem to help

**Comment by roblourens** [comment]
Hmm, I actually meant to mention the `editor.find.autoFindInSelection` setting...
