### ISSUE TITLE
Wrong Markdown preview format for files in UNC path

### ISSUE THREAD

**Issue by TManhente** [microsoft/vscode#87180]
- VSCode Version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a Markdown file on a network shared folder (ex.: `\\storage01\MyFiles\test.md`).
2. Map that network shared folder to a drive letter in Windows (ex.: `Y:`).
3. Open the Markdown file in VS Code using the mapped drive letter (ex.: `Y:\test.md`) and open its Side-by-Side Preview (`Ctrl + K, V`).
    - The preview should be correctly formatted.
4. Open the same Markdown file in VS Code, but using the file's UNC path (ex.: `\\storage01\MyFiles\test.md`) and open its Side-by-Side Preview.
    - The preview is incorrectly formatted.

Does this issue occur when all extensions are disabled?: Yes

Correct format (file opened through mapped drive letter):
![image](https://user-images.githubusercontent.com/4401054/71003298-9c385000-20bf-11ea-8c00-1183ef519670.png)

Wrong format (file opened through UNC path):
![image](https://user-images.githubusercontent.com/4401054/71003319-ac502f80-20bf-11ea-891a-1792439eaf21.png)

**Comment by BuraChuhadar** [comment]
I would like to work on this if possible.

**Comment by BuraChuhadar** [comment]
There was a typo in the code was causing this. I have tested on Windows 10 with a file on a UNC path with the fix above and it is working fine.
