### ISSUE TITLE
delete all my data twice

### ISSUE THREAD

**Issue by helloyan** [microsoft/vscode#87188]
Issue Type: <b>Bug</b>

the last two edtion, after auto update, all my user data and extensions was delete , what's the matter? 

VS Code version: Code - Exploration 1.42.0-exploration (15d77c6ee6bf204cb4dc8e199d3db852263ccfb0, 2019-12-17T09:53:04.711Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.31GB free)|
|Process Argv|--user-data-dir data --extensions-dir data\extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by dbaeumer** [comment]
@helloyan where did you store your user data and extensions ?

**Comment by joaomoreno** [comment]
@bpasero User seems to be using the exploration build.

**Comment by bpasero** [comment]
Yes, please use insiders or stable for production quality.
