### ISSUE TITLE
Show Explorer count and File editors in sync with save/do not save action

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8718]
- Create new files and edit them
- Use close all
- You get dialog per dirty editor for save confirmation
- Select do not save in first dialog

Observe that Explorer count and dirty editor on the background still does not reflect the state. They are updated only after all dialogs are confirmed. It would be nice if they can be in sync.

**Comment by bpasero** [comment]
I do not think we can do this because the dialog is blocking the UI thread and I doubt anything would update in the background (at least on Mac).

**Comment by bpasero** [comment]
Sorry, no plans to change this.
