### ISSUE TITLE
Run Selection/Line in Python Terminal - Long Text

### ISSUE THREAD

**Issue by DougPlumley** [microsoft/vscode#87183]
**- VSCode Version: 1.40.2**

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**- OS Version: macOS Catalina Version 10.15**

**- VS Code Extension - Python**

Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2020.1.54965-dev
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Steps to Reproduce:**

1. Launch Python3
2. Run Selection with more than ~1024 characters selected, example below.

```python
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
{
    "test": "test",
    "test2": "test2"
}
```

![image](https://user-images.githubusercontent.com/32851221/71010889-82483e80-20ba-11ea-9239-dc93fb40dea8.png)

Does this issue occur when all extensions are disabled?: Yes

This is a duplicate of https://github.com/microsoft/vscode-python/issues/6334 and https://github.com/microsoft/vscode/issues/38137 (and likely others).  This does not appear to be resolved and the old issues are closed so I cannot update them.

The result is that I cannot copy/paste or run/selection on large amounts of Python code in the embedded terminal.

**Comment by narmadanagar** [comment]
I am seeing the same issue

**Comment by dbaeumer** [comment]
Please file the issue against the Python extension you are using. Very likely here: https://github.com/Microsoft/vscode-python

**Comment by dbaeumer** [comment]
Sorry my fault. Dups https://github.com/microsoft/vscode/issues/38137

**Comment by DougPlumley** [comment]
@dbaeumer when I had opened this originally via the VS Code extension repository it was determined to be an upstream issue.  Do you think that's not that case anymore?  

Original extension issue: https://github.com/microsoft/vscode-python/issues/6334

**Comment by dbaeumer** [comment]
It is. The issue in VS Code to track this is #38137 which I marked this issue a duplicate of.

**Comment by DougPlumley** [comment]
@dbaeumer https://github.com/microsoft/vscode/issues/38137 is closed but I can still reproduce the issue and it appears others can as well.  I believe this is still an issue.  Can you please reopen this?

**Comment by gowerc** [comment]
Just to add this issue affects more than python.  My ticket was closed as a duplicate of this one (#96973) but shows that the issue also occours using send text to terminal  even on bash commands

**Comment by Tyriar** [comment]
@gowerc I think there might be another older duplicate of this as well, but it's a generic bug related to a maximum amount of text you can use with the sendText API and pasting.

**Comment by gowerc** [comment]
Thanks @Tyriar  for clarifying.  Does this mean there is unlikely to be a solution then ?

**Comment by Tyriar** [comment]
I'm sure there is a solution, it's just not something I'm focusing on at the moment. If anyone wants to investigate this, I suspect the problem lies inside the node-pty component which manages the connection between VS Code and the process inside the terminal, either in [how it's created](https://github.com/microsoft/node-pty/blob/bcdc826f365dd014403992d41b286e815798459a/src/unix/pty.cc#L134) and/or [socket limitations when writing](https://github.com/microsoft/node-pty/blob/bcdc826f365dd014403992d41b286e815798459a/src/unixTerminal.ts#L168-L170).

Related: https://github.com/microsoft/vscode/issues/59135
