### ISSUE TITLE
Single-byte characters are  entered twice in Japanese IME on Firefox

### ISSUE THREAD

**Issue by wumf-terra** [microsoft/vscode#87199]
**monaco-editor version:** 0.15.6
**Browser:** Firefox 65.0.1 (64-bit)
**OS:**  Windows 10

When I select a single-byte characters in IME on Firefox, the selected characters is entered twice.
It does not occur with double-byte characters.

![monaco_firefox_ime](https://user-images.githubusercontent.com/4832115/52673254-7c963f80-2f63-11e9-8ff1-1dfbb635c65f.gif)

**Comment by rebornix** [comment]
Fixed via 83f000df03411224969a37415cb4719ded6265ba

**Comment by roblourens** [comment]
@wumf-terra this is fixed, can you verify?

**Comment by wumf-terra** [comment]
Thank you for fixing it.

@roblourens 
Sorry.
This fix has not been released. I can't confirm because I don't know how to npm install monaco-editor that is applied this fix.

**Comment by rzhao271** [comment]
Verified on Firefox by testing on https://vscode-web-test-playground.azurewebsites.net/
