### ISSUE TITLE
Trailing tick on Ctrl-Click to open link in error output

### ISSUE THREAD

**Issue by RMKeene** [microsoft/vscode#87195]
Issue Type: <b>Bug</b>

In a output line from python test discovery like:

Error: ImportError while loading conftest 'C:\Users\my.name\Desktop\development\alpaca-solver\tests\conftest.py'.

The fort tick ' is not part of the lik, and the last tick IS part of the link so then if you Ctrl-Left-Click on the link to open the file you get

[Window Title]
Visual Studio Code

[Main Instruction]
Unable to open 'conftest.py''

[Content]
Unable to read file (Error: File not found (c:\Users\my.name\Desktop\development\alpaca-solver\tests\conftest.py'))

[Create File] [Cancel]

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
python-extension-pack|don|1.6.0
dotnet|for|0.0.4
elixir-ls|Jak|0.2.25
MagicPython|mag|1.1.0
vscode-elixir|mjm|1.1.0
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
vsliveshare|ms-|1.0.1377
erlang|pgo|0.5.2
vscode-erlang-workbench|pro|0.0.9
elixir-formatter|sar|1.3.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.0
jinja|who|0.0.8
erlang-otp|yuc|0.2.4

</details>

**Comment by dbaeumer** [comment]
@RMKeene the output is presented in the terminal. Right ?

**Comment by abcrahul-ai** [comment]
I am able to open the file. I have used the VS Code Version: Code 1.41.0.
Please find the attached screenshot

![Screenshot_1](https://user-images.githubusercontent.com/52042305/71098623-080ddc00-21d8-11ea-837f-3e3c8e833ca7.png)

**Comment by RMKeene** [comment]
That is javascript.  This bug is with python and in the output of the test discovery for python.
