### ISSUE TITLE
Add the concept of subsections.

### ISSUE THREAD

**Issue by tyohDeveloper** [microsoft/vscode#87192]
Some languages (and other files) require or encourage very long files. This makes it harder to maintain the files. It would be nice to have a way to explicitly mark a file as kind of a sub-file. A quick example.

  project/util.clj - a file that contains lots of generally useful functions. 

If it looked like

  project/util.clj/section-1
  project/util.clj/section-2
  ...

It would be easier to maintain the file. Presumably it would still be one file. Git and other utilities would still treat it like a single file.

Reason not to do it.
* Not all languages need the feature. It might be limited to a small audience.
* It would need to be language dependent. Some languages use ";" for comments. Some "//"

I'd rate it as a lower priority feature. Only implement it if it would require low maintainance.

**Comment by IllusionMH** [comment]
Not a subfiles feature, but can be helpful in meantime - [Folding regions](https://code.visualstudio.com/updates/v1_17#_folding-regions).

Type `#reg` or `#end` to get language specific code completion for regions.

In combinations with Outline view can be good enough replacement
