### ISSUE TITLE
Closing a file without saving is not cleaning markers

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8719]
Steps to reproduce:

- Auto save is disabled
-  Open a typescript file
-  Make a change to cause an error in that file
- Close the file **without** saving

Expected: Markers should be cleared
Actual: Markers remain

![jul-04-2016 12-55-32](https://cloud.githubusercontent.com/assets/10746682/16558553/c042124e-41e6-11e6-9ee5-ba47adf029bc.gif)

**Comment by dbaeumer** [comment]
I looked into fixing this and the only reasonable fix for this is to remove the markers on close. The tsserver has some limitation which I can't work around it. They are:

- you can't request errors for closed resources. Such a request is simply ignored. 
- if a last resource of a project closes the whole project closes which doesn't allow any request to the files in the project anymore.
