### ISSUE TITLE
vscode intellisense not working

### ISSUE THREAD

**Issue by xuwentao93** [microsoft/vscode#87209]
I do really trouble in vscode, I restarted it and reboot my computer again and again. The IntelliSense is not working and this just happened in javascript(.js).
![image](https://user-images.githubusercontent.com/40651803/71044375-7b7a0400-216c-11ea-93ee-761a2357f8d0.png)

and in .css or .vue lookes like that: 
![image](https://user-images.githubusercontent.com/40651803/71044430-99476900-216c-11ea-8dc6-a349a14420e3.png)
![image](https://user-images.githubusercontent.com/40651803/71044543-d57ac980-216c-11ea-80af-5d65f1cb632c.png)

But when I just opened vscode, IntelliSense will work in a second in javascript.
Did anyone else face this problem?

**Comment by mjbvz** [comment]
Please file out the issue template

/needsMoreInfo

**Comment by walidbagh** [comment]
This same issue occurred to me,  re-installed vscode, uninstalled all extensions, re-installed npm but nothing seems to fix it.
It was working just fine few days ago, i guess before the last update.
Also, i use eslint in my project if that helps.

**Comment by givionte** [comment]
Duplicate of #87034

**Comment by walidbagh** [comment]
@xuwentao93 Downgrading to 1.40.2 seems to resolve this issue.

**Comment by xuwentao93** [comment]
@walidbagh still not working...

**Comment by walidbagh** [comment]
> @walidbagh still not working...

For me , that fixed it. 
You need to make sure, you disabled updates, after installing 1.40.2 (or any earlier version) or else vscode will auto update on the first restart.

**Comment by mjbvz** [comment]
@xuwentao93 Again, please fill out the issue template and provide steps to reproduce. Otherwise we can't investigate this issue

**Comment by xuwentao93** [comment]
I don't know how to explain it, briefly, just a new system with new vscode, but intellisense is not working. Maybe after I use create-react-app to create a new project.

**Comment by xuwentao93** [comment]
I find it will work in typescript, but when I type in javascript, both are not work.

**Comment by xuwentao93** [comment]
oh, I think it must caused by create-react-app or vue-cli, I can use normally in any .js when I config the webpack myself.
