### ISSUE TITLE
Changing the color of variables in sidebar when using debugger

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode#87200]
This has been asked [on StackOverlow](https://stackoverflow.com/questions/57410784/how-to-change-color-of-debug-variable-names-in-vscode) already too, and I've Googled and tried many things in my settings.json file, but although I changed the color of _many things_, I did not manage to* change the color of variables in the sidebar while debugging.
Currently it's purple on a dark background. Here's a screenshot of the problem:
![vscodedebuggervarsbadcolor](https://user-images.githubusercontent.com/52244768/71032768-439e9c80-212b-11ea-8a0d-882bebb440e9.png)
I hope someone can help me fix this or if that's not possible I hope vscode makes it possible.
<hr>
* I tested words like "debug", "sidebar", "variable", etc... in the settings.son with the help of auto-completion but none of those options suggested seems to work.

**Comment by isidorn** [comment]
These colors are currently not customisable.
This is a fair feature request, and I do agree we should make this colors customisable. However this is not on our immediate plan, thus assigning to the backlog for now.
