### ISSUE TITLE
Private fields inside strings

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#87208]
From Twitter: https://twitter.com/jasnell/status/1207085555567087617

Looks like using private fields inside template strings breaks things.

![image](https://user-images.githubusercontent.com/9721254/71044089-8b023a00-20e5-11ea-8544-525007aa8436.png)

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/34898
