### ISSUE TITLE
Large file under git control encoding guess can freeze the editor

### ISSUE THREAD

**Issue by ziggi** [microsoft/vscode#87205]
- VSCode Version: 1.41 (same on 1.42 insiders build too)
- OS Version: Windows 10 Pro 1909, build 18363.535

Steps to Reproduce:

1. Open a large file (my file is 93k+ lines, 3.96 MiB) and a small one. The files should be in `Windows 1251` encoding and VS Code `settings.json` should contains `"files.autoGuessEncoding": true,`.
2. Switch tab from small to large.

Does this issue occur when all extensions are disabled?: Yes

It looks like the problem is in [jschardet](https://github.com/aadsm/jschardet), it was updated from 1.6.0 to 2.1.1.

[CPU-20191218T010956.cpuprofile.txt](https://github.com/microsoft/vscode/files/3975749/CPU-20191218T010956.cpuprofile.txt)
[Profile-20191218T010523.json.txt](https://github.com/microsoft/vscode/files/3975750/Profile-20191218T010523.json.txt)

![image](https://user-images.githubusercontent.com/1020099/71038250-726c4100-2132-11ea-917c-9c367d38aff0.png)
![image](https://user-images.githubusercontent.com/1020099/71038688-6fbe1b80-2133-11ea-9e8d-07ccb3ec004c.png)

**Comment by bpasero** [comment]
@ziggi great analysis, wanna report it to jschardet maybe?

**Comment by ziggi** [comment]
I'm not 100% sure what the problem is in jschardet. The problem may be in vscode only.

**Comment by bpasero** [comment]
@ziggi looks like jschardet to me. We are simply calling this method: 

https://github.com/microsoft/vscode/blob/b6ae21e6e2e7255978993df45c1317a869170d21/src/vs/base/node/encoding.ts#L215

**Comment by ziggi** [comment]
Ok, done: https://github.com/aadsm/jschardet/issues/53

**Comment by creative-acr** [comment]
I have the same issue while opening large JS file after updating to version 1.41.1

![vs code issue](https://user-images.githubusercontent.com/55732794/71575643-5772d700-2b0b-11ea-91ef-703c0fb8de8c.png)

**Comment by bpasero** [comment]
@creative-acr do you have `"files.autoGuessEncoding": true` configured which this issue is about?

**Comment by bpasero** [comment]
@ziggi to clarify, you only see this with large files that are under git control?

**Comment by ziggi** [comment]
@bpasero yes

**Comment by bpasero** [comment]
I can reproduce and it looks like the dirty diff decorator is triggering this. Though I cannot explain why this performance issue does not show up when just opening the editor where we also guess the encoding. Maybe the diff decorator is not as optimized as the code editor model that reads the file in chunks?

**Comment by bpasero** [comment]
I pushed a fix that will limit the buffer for encoding guessing to 65kb. The dirty diff decorator was passing the entire buffer. Filed https://github.com/microsoft/vscode/issues/88119 as follow up.
