### ISSUE TITLE
TreeView.message doesn't refresh correctly when cleared

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#87207]
vscode 1.41.0

In my extension, if the tree is unpopulated I set a message to encourage the user what to do. If I add an item to the tree and then clear the message it is removed correctly. 

The problem is when I then remove the item from the tree and reset the message, the message doesn't appear.

I have tried setting the message to "" and also undefined.

**Comment by alexr00** [comment]
@Gruntfuggly since you have an extension can you point me to the repository with steps so I can clone and reproduce the issue myself?

**Comment by Gruntfuggly** [comment]
Hi - I haven't published it in the store yet, but you can find it here:
https://github.com/Gruntfuggly/remembrall
The master branch should exhibit the behaviour.
Line 121 of extension.js is where the message is set. If I change it to a non-empty string when the tree has content it works as expected. With an empty string or undefined, it doesn't.

**Comment by alexr00** [comment]
Nice bug, thanks for filing and providing a repo! The issue was that if you remove the message and then put back _the same message from before you removed_ then we wouldn't correctly show the message.
