### ISSUE TITLE
Syntax highlighting gets confused if return type ends with a number

### ISSUE THREAD

**Issue by kayahr** [Microsoft/vscode#8720]
- VSCode Version: 1.2.1
- OS Version: Debian GNU/Linux 8.5

Steps to Reproduce:

1. Open new TypeScript file.
2. Copy/Paste the following code:

```javascript
class Vector2 {
    public foobar(): Vector2 {
        return this;
    }
}

class Vector2D {
    public foobar(): Vector2D {
        return this;
    }
}
```

The method in the class `Vector2D` is properly colored but in the class `Vector2` the syntax highlighting gets confused. Looks like this has something to do with the class name ending with a number. 

Here is a screenshot showing a wrong color of the `return` and `this`keywords:

![highlighting](https://cloud.githubusercontent.com/assets/580493/16558618/28846992-41e7-11e6-90c5-9a74362ed30d.png)

In larger source code this gets quite confusing because subsequent methods in the same class are also affected.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#207
