### ISSUE TITLE
Disable Trivial Path Collapse Feature in Workspace Navigator

### ISSUE THREAD

**Issue by oclyke** [microsoft/vscode#87201]
This is in-between a feature request and a question. I couldn't turn up any other issues with the same subject.

### Question
Is there an existing setting that I can use to turn off directory flattening in the workspace navigator? 

In a project I am working on the boilerplate directory structure has at least one case where there are 5+ organizational levels with only one subdirectory and no contained files. This creates an inconvenient situation for trying to examine that structure and add files to deep directories. 

Though intuitive I also find it inconvenient to need to worry about my horizontal placement when right clicking to add/remove directories/files.

Here's a look at what I'm talking about:
![targets_small](https://user-images.githubusercontent.com/13486034/71034188-18d62900-20d6-11ea-921d-5d7e84e28134.JPG)
![targets_large](https://user-images.githubusercontent.com/13486034/71034189-1a075600-20d6-11ea-99b1-81e1dac2cab8.JPG)

### Feature
If there is not a setting to disable this functionality then I would surely appreciate seeing one added. Thanks!

**Comment by IllusionMH** [comment]
/question

This settings already exists and you can do actions with any folder from nesting. See https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer for details
