### ISSUE TITLE
can vscode run in a browser window ?

### ISSUE THREAD

**Issue by jmls** [Microsoft/vscode#8721]
I was wanting to put vscode into a docker container, but would obviously need to be able to run vscode in a browser window - is this possible ?

**Comment by joaomoreno** [comment]
Very hard to achieve nowadays. There are many references to node modules by now.

**Comment by jmls** [comment]
Wait - what has node_modules got to do with this ? I was wanting to show the UI in a browser, not run the application in a browser ;) The application would be running in the docker container on the server, with all the access to node_modules that it needs.

**Comment by joaomoreno** [comment]
Most of the workbench code has dependencies not only on the DOM but also on native functionality, only available in node, which would make it impossible to run in a browser. Take [`shell.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L27) as an example.
