### ISSUE TITLE
Dont know if this is a C++ issue or VS-Code issue, but i need to fix this.

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#87218]
https://code.visualstudio.com/insiders/ -->

Version: 1.42.0-insider (system setup)
Commit: 241d4048aabc31db0baed66bb3d58cf3210d981d
Date: 2019-12-17T10:43:45.626Z
OS: Windows x64 10

Please read this issue located here.  Sorry if I sound frustrated, its because I am.
I dont know if this is happening because of Visual Studio Code or C++ extension.
So im posting here because I need this solved.
Also, dont know if I am doing something wrong without realizing it.
But I still need to fix this.

Thank you.
.--Full details at this link:
https://github.com/microsoft/vscode-cpptools/issues/4751
..
.
**

> Basically:

**
.
Code works when doing a debug,  but not when pressing the Play Button on top left of IDE or 
right clicking anywhere in the code and choosing 'Run Code'  ??
Grrr.
.
![Works in Debug 1](https://user-images.githubusercontent.com/18384135/71055801-f5869a80-2124-11ea-9dfe-2b963800df53.png)

.

![Works in Debug 2](https://user-images.githubusercontent.com/18384135/71055808-fa4b4e80-2124-11ea-9ec1-349f23cd7921.png)

.

And the picture immediately below is the result when trying to run the code the normal way,
by either pressing the play button in the IDE or right clicking and selecting 'Run Code'
I can not interact with the terminal and it shows the output only in the Output section of the terminal.
Very frustrating.
.
![Wont Run Code in Normal RUN](https://user-images.githubusercontent.com/18384135/71056042-d76d6a00-2125-11ea-9d52-0ce390e69036.png)

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-cpptools/issues/4751

Lets see what the C++ extension devs find out.

**Comment by RobFosterNYC** [comment]
10 days later still no solution to this.
for the time being any C++ I do will be done in Eclipse IDE, until I find a solution to this problem.
As I am not getting answers from either side, as you both closed my case.
