### ISSUE TITLE
Source Control no longer opening as Preview for image files

### ISSUE THREAD

**Issue by setek** [microsoft/vscode#87212]
**Update:** it only seems to be happening for images, not for `.js` files.

- VSCode Version: 1.41.0
- OS Version: macOS 10.14.3 (18D109)

This appears to be a regression of https://github.com/Microsoft/vscode/issues/26184

I have:
- Open Mode: single click
- Workbench > Editor: Preview ✔️

If I single click from Explorer it still opens as Preview.

Steps to Reproduce:

1. Edit/Add an image file in a source controlled directory
2. Go to Source Control and click on the file

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not repro also for image files.
However even if that is the case, since it repros only for image files it is not urgent, thus Joao can tackle this once he is back.

**Comment by joaomoreno** [comment]
@mattbierner This seems related to you recent changes. I see the preview editor briefly only to become pinned right after.

**Comment by mjbvz** [comment]
Not specific to custom editors. Here's the code that triggers the reopen that pins the editor:

https://github.com/microsoft/vscode/blob/9bf0af3ea0715d73cfa6440a14f4487028412d74/src/vs/workbench/browser/parts/editor/textDiffEditor.ts#L157

And here's where we enable pinning:

https://github.com/microsoft/vscode/blob/5e09466b85f2752e875e702d596d06a515ec49c8/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1500

@bpasero Adding you as the expert on workbench editor management

**Comment by mjbvz** [comment]
I've fixed the custom editor case with c4d53a19df8799f5d49a4f49a6900c499e6fa27c (just forcing the custom editor diff view to always be binary)

Normal binary editors still have this bug. Adding @joaomoreno

**Comment by bpasero** [comment]
I pushed a change, the reason was that we replace the text diff editor with a binary diff editor and the `replaceEditor()` method was always setting pinned: true by default. 

@mjbvz I think you could revert your change and it would be fine. Not sure yours made sense or was a workaround.
