### ISSUE TITLE
VSCode searching for exception information in the wrong path for pyzmq

### ISSUE THREAD

**Issue by kitattyor** [microsoft/vscode#87219]
**System Information**

Version: 1.41.0 (system setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Steps to Reproduce:**

1. Create new folder and create new python virtual environment `venv`. 
2. activate `venv`
3. `pip install pyzmq`  (Using version 18.1.1)
4. Copy paste the following code in a file and run

```
# echoClient.py
import sys
import time
import zmq

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.stderr.write("Add port as argument")
        sys.exit(1)

    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    socket.connect("tcp://localhost:%d" % int(sys.argv[1]))
    socket.setsockopt(zmq.LINGER, 0)

    print("Sending ...")
    times = 0
    while True:
        times += 1
        msg = "Message".encode('utf-8')
        send_OK = socket.poll(1, zmq.POLLOUT)
        socket.send(msg)   # <-- Will crash here if Server is not connected
        #  Get the reply.

        if socket.poll(10, zmq.POLLIN):
            message_recd = socket.recv()
            print("Received %s" % message_recd)

            if msg == message_recd:
                print("ECHO OK")
            
            else:
                print("ECHO NOT OK")

        else:
            print("Timeout")
        
        time.sleep(1)   

    # close socket and exit
    socket.close()
    context.term()
```

This code will crash if a listener is not connected because of the internal state machine mechanisms of a zmq REQ socket, that is you cannot send() twice without recv() after every send().

The issue is that VSCode seems to look for the exception information in `.\zmq\backend\cython\checkrc.pxd` when it should be looking in the site-packages folder. The correct path is `.\venv\Lib\site-packages\zmq\backend\cython\checkrc.pxd`

**Error message** - Unable to open 'checkrc.pxd': Unable to read file (Error: File not found (c:\pyprojects\echoclient\zmq\backend\cython\checkrc.pxd)).

Does this issue occur when all extensions are disabled?: Yes

**Comment by kitattyor** [comment]
> Does this issue occur when all extensions are disabled?: Yes

Only the python extension is enabled. Rest were disabled during test.

**Comment by weinand** [comment]
VS Code has no built-in Python functionality. Please file this issue against the Python extension.

**Comment by kitattyor** [comment]
I see. Thanks.
