### ISSUE TITLE
Fix Python file/syntax detection for virtual environment shebang lines

### ISSUE THREAD

**Issue by bulletmark** [microsoft/vscode#87214]
- VSCode Version: 1.41.0 (and all previous versions in the last 2 years that I have used)
- OS Version: Arch Linux, up to date.

I use virtual environments for most of my projects so the shebang line for my main Python app, say myprog is:

```python
#!venv/bin/python
print('This is my program. Has no .py extension.')
```

Vim correctly automatically identifies this as a Python file but vscode does not.

Of course, if I change nothing more than that first line to below, then vscode does correctly detect and syntax highlight the code as Python.

```python
#!/usr/bin/python
print('This is my program. Has no .py extension.')
```

Shebang lines like the first example are very common when people use virtual enviroments so vscode should detect that relative path shebang as well.

**Comment by alexr00** [comment]
If you use 
`#!/venv/bin/python` vs
`#!venv/bin/python` then it will work.
I _think_ that having the leading slash is more correct and it's what we do for make, php, powershell, python, and ruby.

**Comment by bulletmark** [comment]
@alexroo, `/venv/usr/bin` is not the same path as `venv/usr/bin`!

The whole point of this bug is that I need to use a relative path but relative paths are not currently correctly parsed by vscode to determine the file type. Yes, as I said in my original description, it I put in a path with a leading slash then vscode works. But I can't do that because the path is relative, not absolute.

How come vim can get this right, but vscode can't?

**Comment by bulletmark** [comment]
@alexr00 I should also add that please note that relative paths are valid as shebang lines and are correctly invoked by the linux shell. E.g. running the program above (i.e. having shebang `venv/bin/python`) as `./myprog` does invoke that program under that venv python. So given it is correct syntactically, shouldn't vscode support it?

**Comment by alexr00** [comment]
If a relative path is correct for consumers of the shebang line then yes, this should be supported. 
In general, providing links to documentation that supports the behavior you're asking for is the fastest/smoothest way to get a change made. We get a lot of issues, and the more actionable the issue is, the more likely we are to take action!

**Comment by bulletmark** [comment]
@alexr00 It's difficult to find a link to any specific documentation about that but it is trivial to try it against any shell. They all support relative paths in the shebang line as far as I know (at least bash and zsh do).

I installed a few different editors to see how many others detected python file type from a relative shebang (with no .py extension hint of course). E.g. Vim, emacs, pycharm, geany, notepad did, vscode, atom, gedit did not.

Note I am discussing python here in my examples but of course this is a general issue not specific to python.
