### ISSUE TITLE
Problem pane don't show problems

### ISSUE THREAD

**Issue by Kang-Jh** [microsoft/vscode#87210]
When I typed not existing variable name(typo) or omitted some expression vscode showed me problems. But since yesterday suddenly vscode doesn't show problem in problem pane.
And also when I typed variable name's first few letters it should suggest a list of auto completed variable names or some options like keyword or something, but I didn't see any of it.

I disabled all extensions but it didnt work.
I don't know what is the problem.

**Comment by Kang-Jh** [comment]
It looks like js file only
when writing json file, problem shows me problems about errors

**Comment by Kang-Jh** [comment]
Sorry for missing info. And I don't major CS and I'm not good at English. So please understand me.

Version: 1.41
OS: Windows 10 pro
Extensions: Without extensions(I disabled all extensions and still have the problems)

When I wrote JS code in .js file the issues came.
If I typed v, it should show me list of keywords that starts with v. But it doesn't show me nothing.
Or if I typo some variable name like userr (correct is user) it should show me a error on problem pane there are no userr variable. But problem pane  shows me nothing.

Below is the screenshot about errors

![js-error](https://user-images.githubusercontent.com/39303779/71144097-2a4b3c80-2260-11ea-8f4b-d590bcb7c8d5.png)
![others](https://user-images.githubusercontent.com/39303779/71144098-2a4b3c80-2260-11ea-9a5b-d2aa3ba7c1df.png)

**Comment by Kang-Jh** [comment]
Some js file (like index.js) shows me a list of auto completed keywords and errors. But my real project doesn't show me errors at all. I'm sorry for not clarifying issues.

**Comment by mjbvz** [comment]
@Kang-Jh Can you please share a small example project along with steps to reproduce the problem? This will help us understand if there is a bug in VS Code or if your project needs to be configured

**Comment by Kang-Jh** [comment]
@mjbvz Sorry for late reply. I'm trying to reproduce about this bugs. Now my version is 1.41.1 (previous version was 1.41.0 when I wrote this report.)
https://github.com/Kang-Jh/vscode-bug1.git
above url is github repo for this bugs

I did create new folder for this bugs. and just git init and create readme.txt file and disable all extensions and re-start vscode. So there are no packages or extensions at all.

I couldn't reproduce a list of auto completed keywords like var, let, const or objects like window, document or variables that I defined or etc.

Below picture shows keyword let stands alone with no problem. It doesn't make sense. and I think 1.40.x versions show me errors with this problem.
![test1](https://user-images.githubusercontent.com/39303779/71305535-02530900-2419-11ea-85e7-de993c75259c.png)

Below, constant without assigning value still has no problem.
![test2](https://user-images.githubusercontent.com/39303779/71305554-4c3bef00-2419-11ea-8e91-7f8514f208f1.png)

Below, 3rd line shows stand alone keywords. 4th line wrong messages I guess
![test3](https://user-images.githubusercontent.com/39303779/71305563-6d044480-2419-11ea-8da1-a4e097fa57aa.png)

I think error messages is diffrent from 1.40 versions(It is just my guts. I never saw problem pane thoughtfully and carefully.)

Sorry for not reproducing perfect sample of this bugs. Or is it just me that have this bugs?

**Comment by Kang-Jh** [comment]
@mjbvz Problem pane issues is my mistake. I found out that showing problem in the problems pane that unused variables (as info) and undefined variables but used them in code (as warning) is not built-in features. Is installed extension(ESLint) feature. When I enable ESLint, it solved a issue

But another issue (JS Intellisense issue) is posted #87658  by another user and I commented it too with some my info. Please check #87658
