### ISSUE TITLE
Add option to disable auto paste when enter search panel

### ISSUE THREAD

**Issue by githoniel** [microsoft/vscode#87217]
I found vscode will auto paste when I enter search panel after update to 1.41.0.
It maybe annoy sometimes. new setting `search.searchOnType` can not turn it off.

Case 1: 

1.copy keyword, and click search panel, auto paste will work

But sometimes I just do not what to search or I misclick on search panel, the search may waste a long time

Case 2

I want to copy/paste some code in several files

1. copy keyword to search, get files I want to alter
2. copy something I what to paste across files, click the first file in search result, left panel now is in Exporer, paste and edit something
3. after this, I want to go to the second file in search result, I click the search panel, but auto paste and search will trigger...

**Comment by AnuragAnalog** [comment]
I have tried case1; there was an option in the settings for disabling the search.searchOnType, and if I disable the option, there is no auto paste. It's working well in the master branch.

My vscode specifications are:
  Version: 1.42.0
  Commit: Unknown
  Date: Unknown
  Electron: 6.1.6
  Chrome: 76.0.3809.146
  Node.js: 12.4.0
  V8: 7.6.303.31-electron.0
  OS: Linux x64 5.0.0-37-generic

Preview:
![no-auto-copy](https://user-images.githubusercontent.com/32128318/71099099-bade3a00-21d8-11ea-8974-071a846a7132.gif)

**Comment by roblourens** [comment]
You can disable this with the setting `editor.find.seedSearchStringFromSelection`

**Comment by githoniel** [comment]
It works, but `editor.find.seedSearchStringFromSelection` maybe hard to find.
Why it is in `TextEditor-Find` rather than `Search` but it affect `Search`

**Comment by IllusionMH** [comment]
@roblourens is is possible to somehow differentiate cases when search panel is opened from the editor (with shortcut on active selection) and when user just have selection in inactive editor and clicks on Search panel?

Problem with `"editor.find.seedSearchStringFromSelection": false` is that in this case I'm unable to select text that I want to search and just press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> to trigger search by selection.

While problem is actually in switching between tabs in panel or action bar - I have no intention to trigger new search, I just navigate back from Problems or Terminal panel.

**Comment by roblourens** [comment]
We would need another setting to control that part of the behavior. We ended up like this because of users who requested this exact behavior. I guess people who are primarily mouse users don't really see the distinction.
