### ISSUE TITLE
js代码智能提示失效

### ISSUE THREAD

**Issue by INTMIN** [microsoft/vscode#87216]
Issue Type: <b>Bug</b>

项目代码进入后，初始有提示，过一会后，提示消失，一直提示为加载中，所有的变量以及类名都无法自动引入和提示

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.34GB free)|
|Process Argv|--folder-uri file:///f%3A/estee-lauder-kol|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
turbo-console-log|Cha|1.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
wxml-vscode|cny|0.1.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.6
githistory|don|0.4.11
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.3
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.16.1
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
beautify|Hoo|1.5.0
rest-client|hum|0.23.0
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.27
vscode-language-babel|mgm|0.0.25
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.41.2
remote-wsl|ms-|0.41.6
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
vscode-versionlens|pfl|0.24.0
java|red|0.54.2
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
js-jsx-snippets|sky|10.0.0
autoimport|ste|1.5.3
language-stylus|sys|1.11.0
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
vscode-icons|vsc|9.6.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.1

</details>

**Comment by wangshaojie98** [comment]
低版本的VScode可以，我昨天也是这种情况。

**Comment by Raleigh-xc** [comment]
me too

**Comment by TaoTao2deng** [comment]
我也是，我已经安装旧的版本了。

**Comment by INTMIN** [comment]
> This issue is being closed because its description is not in English, that makes it hard for us to work on it. Please open a new issue with an English description. You might find [Bing Translator](https://www.bing.com/translator) useful.

fix to English now
