### ISSUE TITLE
installing previous version of VS Code prevents usage of extensions

### ISSUE THREAD

**Issue by zachvalenta** [microsoft/vscode#87215]
A few Markdown extensions I use started misbehaving w/ the latest ([1.41](https://code.visualstudio.com/updates/v1_41)) release of VS Code, so I temporarily need to use the previous version of VS Code ([1.40](https://code.visualstudio.com/updates/v1_40)).

To avoid VS Code updating itself to the latest version, I added `"update.mode": "none"` in my `settings.json`.

I then downloaded and installed [1.40](https://code.visualstudio.com/updates/v1_40). When I opened VS Code, however, I got the following warning:

![Screen Shot 2019-12-17 at 9 07 42 PM](https://user-images.githubusercontent.com/11388735/71050070-3aed9c80-2112-11ea-8d26-028aa292d36e.png)

When I clicked the prompt, this [page on the docs site](https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported) seems to say "you're on your own running old versions of VS Code". 

Which is fine, but the second warning 'extension host cannot start' seems to contradict that and say "your extensions won't work, you **need** to upgrade to the latest VS Code version".

**Comment by alexdima** [comment]
@zachvalenta Well, the first warning: "Your Code installation appears to be corrupt. Please reinstall" is the most concerning one.

Simply uninstall VS Code completely from your machine and then install an older version and when you launch it make sure the first thing you do is to change `"update.mode": "none"` in your `settings.json`.

I believe you have ended up with a corrupt on disk installation. Perhaps mixing up some old files with some new ones.
