### ISSUE TITLE
The setting is deprecated. Use editor.codeActionsOnSave instead with a source.fixAll.eslint member.

### ISSUE THREAD

**Issue by prateekgurnani10** [microsoft/vscode#87227]
Whenever I type anything inside my editor, it automatically opens up the json settings. I have no clue why it is doing that

- VSCode Version: 1.41
- OS Version: Mac OS catalina 10.15.2

**Comment by SathiskumarD** [comment]
Hey Prateek,
can you please let me know how you fixed it?

**Comment by sauzy34** [comment]
> Hey Prateek,
> can you please let me know how you fixed it?
` "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }`

**Comment by kissu** [comment]
Not sure why/how but this update also broke my Eslint-Prettier autoformat in `.vue` files on save.

It's not auto-formatting it when I do save a file, even if `  "editor.formatOnSave": true,` and `"vetur.format.defaultFormatter.html": "prettier",` has not been changed.

**Comment by Aurelioolive** [comment]
Correct format:
` "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }`

**Comment by kissu** [comment]
I did ofc tried that before too. ^^

**Comment by Aurelioolive** [comment]
Worked for me o.o

**Comment by kissu** [comment]
I mean, it's working and it's really sluggish. When the lines to reformat are too long it just gives up too...
