### ISSUE TITLE
Multiple cursors appear in nested snippets after code completion is used several times

### ISSUE THREAD

**Issue by vadson71** [microsoft/vscode#87226]
- VSCode Version: 1.41.0
- OS Version: Windows 10, MacOS

Multiple cursors appear in nested snippets after code completion is used several times at tab stop position. This may be caused by miscalculation of tab stop indexes. When each new snippet is added inside the existing one, tab stop indexes of the outer snippet are recalculated so that all tab stops inside the outer snippet and after it are numbered sequentially.
At some point, the index numbers are miscalculated so that multiple tab stops with the same index number appear. When the cursor reaches these tab stops, several cursors appear, as several tab stops have the same index.

### Steps to Reproduce

1. Using VSCode's  'Configure user snippets' command (more info here https://code.visualstudio.com/docs/editor/userdefinedsnippets), create simple snippet definition:
```
"snippet": {
        "scope": "typescript",
        "prefix": "@2",
        "body": [
            "function($1) {$2}"
        ]
}
```
2. Create New Typescript file using New File menu option
3. Start typing @2... Code completion options should appear in a drop down menu. Select @2 option. This will insert function snippet and replace @2 symbols with snippet's text. You should get the following text fragment ( vertical bars | here indicate tab stop positions in the inserted snippet):
```
function( | ) { | } |
```
4. Using Tab button go to the second tab position (which is between curly brackets {} ).
5. Press Enter and then type @2. 
```
function () {
  @2|
}
```
Again code completion drop down menu should appear. Selecting option @2 insert second nested snippet. You should get following text:
```
function() {
    function() {}
}
```
6. Repeat actions from step 5 one more time. Result should be following:
```
function() {
    function() {
        function() { }
   }
}
```
6. Using Tab go to position between curly brackets and ask for code completion there, using arrows select some option, for example undefined, and press Enter. 
```
function() {
    function() {
        function() {undefined}
   }
}
```
7. Press Tab. Cursor should jump to next tab stop( vertical bar | indicates this position )
```
function() {
    function() {
        function() {undefined} |
   }
}
````
8. Press Enter to insert new line. Type @2, insert snippet as described above, press Tab, Ctrl+space, select 'undefined', press Enter, press Tab. Result should be following:
```
function() {
    function() {
        function() {undefined}
        function() {undefined} |
    }
}
```
9. Using Tab for navigation between tab stop positions and repeating steps described above create structure like this. Do NOT use arrows for navigation, only Tab or Shift+Tab!
```
function() {
    function() {
        function() { undefined }
        function() { undefined }
    }
    function() {
        function() { undefined }
        function() { undefined }
        function() { undefined }
        function() { undefined }
        function() { undefined }
        function() {}
    }
}
```
10. After 6-8 code completions next function snippet appears with multiple cursors.

### Expected results

Multiple cursors should not appear.

### Actual results

Multiple cursors appear in the newly inserted snippet.
![vscode-snippets](https://user-images.githubusercontent.com/6931493/71067409-24c8f600-217d-11ea-8c6d-ccc338d7a7a5.gif)

This issue occurs even when all extensions are disabled, (Launch with `code --disable-extensions` to check.)

**Comment by jrieken** [comment]
I wasn't able to to reproduce. For me snippet mode stays active and completion works as expected also after repeating this many time. Tho, your steps are very complex, please try to make them more minimal. If you are up for it, write a test that exercises what you are describing, find samples [here](https://github.com/microsoft/vscode/blob/87c0f5a5388fb82f55509f7dc25020dc66bc18a3/src/vs/editor/contrib/snippet/test/snippetController2.test.ts#L414)

**Comment by vadson71** [comment]
@jrieken 
Have you created 3-level nested snippet structure?
Code completion in tab stops should be done at least 7-times.
Please try to repeat steps captured on video. For me and my colleagues the issue stable reproducible in different file formats (XML, TypeScript), using different snippets (having 2-3 tabstops) and on different platforms (Windows, Mac).
So, crucial requirements to reproduce - code completion many times, at least 6-7 and deeply nested snippet structure ( try to make 3 levels and then return  to 2-nd level and continue. When navigate please use only Tab-button to keep snippet mode active. If still can't reproduce, let me know, I'll try to create test. Thanks!

**Comment by vadson71** [comment]
Hi, @jrieken !
I would like to know, if you tried to reproduce the issue once again following my recommendations?
As for me, the issue is stable reproducible.  But yes, the scenario is not that straight forward. It couldn't be somehow simplified. Please repeat steps how they demonstrated on the attached video. If you do it precisely as described, after code completion of 'undefined' value has done 7 times, the next snippet should appear with two cursors. Please try to reproduce it again.

**Comment by vadson71** [comment]
Hello, @jrieken !
I have not received a response from you. I would like to know what status this problem has. Are you expecting any action from me?

**Comment by jrieken** [comment]
Honestly I have not. It seems like it requires such a long sequence of commands that close to no user will hit this in real life. Since you seem to have strong emotions, how about doing PR that first adds a test reproducing this failure (add it here src/vs/editor/contrib/snippet/test/snippetController2.test.ts) and then try to fix it

**Comment by dmitrivMS** [comment]
I think this has been fixed in https://github.com/microsoft/vscode/pull/316824
