### ISSUE TITLE
Create new folder failed

### ISSUE THREAD

**Issue by SanJin-hx** [microsoft/vscode#87223]
- VSCode Version:
版本: 1.42.0-insider (user setup)
提交: 4636be2b71c87bfb0bfe3c94278b447a5efcc1f1
日期: 2019-12-18T05:41:55.003Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
- OS Version:

Steps to Reproduce:

1. Create new folder
2. Error: UNKNOW: unknow error, stat '\\d:\path'

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by SanJin-hx** [comment]
![image](https://user-images.githubusercontent.com/26178326/71068753-54462580-21b2-11ea-9aa2-f66e7de3fcaa.png)

**Comment by SanJin-hx** [comment]
![image](https://user-images.githubusercontent.com/26178326/71068793-6f189a00-21b2-11ea-8cc9-54986e79c56a.png)

**Comment by Enl0ve** [comment]
![image](https://user-images.githubusercontent.com/27036865/71071960-8490c280-21b8-11ea-8df6-149b70cfcbbb.png)

**Comment by Enl0ve** [comment]
cannot to create file & folder
