### ISSUE TITLE
VSCode didn't provide autoComplete prompt when python.autoComplete.addBrackets: true

### ISSUE THREAD

**Issue by kennieh2017** [microsoft/vscode#87221]
VSCode didn't provide autoComplete prompt when python.autoComplete.addBrackets: true

https://stackoverflow.com/questions/59319814/vscode-didnt-provide-autocomplete-prompt-when-entering-grey-backgroud-mode

**Comment by dbaeumer** [comment]
Please report the proble against the Python extension you are using. Very likely here: https://github.com/Microsoft/vscode-python
