### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by itamardavidyan** [microsoft/vscode#87224]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

ts engine crashed 5 times in 5 minutes

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|3.2.0
vscode-standardjs-snippets|cap|0.8.9
turbo-console-log|Cha|1.3.1
gitlens|eam|10.2.0
asm-code-lens|maz|1.3.1
git-graph|mhu|1.19.1
remote-wsl|ms-|0.41.5
cpptools|ms-|0.26.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-javascript-booster|sbu|0.11.0
tabnine-vscode|Tab|2.1.22
vscodeintellicode|Vis|1.2.0
vscode-convert-utils|vsc|1.0.2

</details>

**Comment by FinalButterfly** [comment]
I am having the same problem after updating to 1.41 today.

I have only Oceanic Next installed as an extension.

![image](https://user-images.githubusercontent.com/31434462/71079162-8785b600-21ac-11ea-9efb-0725b0020da0.png)

**Comment by mjbvz** [comment]
Please check the TS Server log to see what the first occurrence of the crash is:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. Back in VS Code, go to the `TypeScript` section of output panel
1. At the very top of this output, there should be a line that prints the path to the main server log. It should look like this (note the `<semantic>` part) :

```
[Info  - 4:06:59 PM] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20191111T144045/exthost1/vscode.typescript-language-features/tsserver-log-F2rDlk/tsserver.log
```

Please look through that log file for errors or stack traces (they should be near the end). If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by thanpolas** [comment]
@mjbvz this issue is repeating itself, please explain where to find the "TS Server log" so I can perform your troubleshooting checklist.

From my output console on VSC:

```
[Info  - 16:24:41.404] Killing TS Server
[Info  - 16:24:41.512] TSServer exited
[Info  - 16:24:41.512] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 16:24:41.514] <syntax> Forking...
[Info  - 16:24:41.528] <syntax> Starting...
[Info  - 16:24:41.530] <semantic> Forking...
[Info  - 16:24:41.541] <semantic> Starting...
[Info  - 16:24:55.69] Killing TS Server
[Info  - 16:24:55.96] TSServer exited
[Info  - 16:24:55.96] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 16:24:55.98] <syntax> Forking...
[Info  - 16:24:55.107] <syntax> Starting...
[Info  - 16:24:55.109] <semantic> Forking...
[Info  - 16:24:55.117] <semantic> Starting...
```
