### ISSUE TITLE
Program is not responding

### ISSUE THREAD

**Issue by nblog** [microsoft/vscode#87225]
版本: 1.41.0 (user setup)
提交: 9579eda04fdb3a9bba2750f15193e5fafe16b959
日期: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:
1. open [sample](https://github.com/microsoft/vscode/files/3977223/EventDatabaseMgr.zip) file (Please unzip before using)

Does this issue occur when all extensions are disabled?: Yes (but sometimes or 'No')

**Comment by nblog** [comment]
1. Without url
2.Only one version of vscode

**Comment by dbaeumer** [comment]
@alexr00 starting with you since it is a C# file and it might be a grammar issue.

**Comment by alexr00** [comment]
@nblog, this line is the culprit:
```csharp
CallEvent callEvent = new CallEvent(traceId, (ulong)((callNumber == 0UL) ? ((long)r["CallNumber"]) : ((long)callNumber)), (ulong)((long)r["Peer"]), (int)((long)r["Priority"]), (string)((obj2 == DBNull.Value) ? string.Empty : obj2), (EventFlags)((long)r["EventFlags"]), (ulong)((long)r["RetValue"]), (string)((obj3 == DBNull.Value) ? string.Empty : obj3), (string)((obj4 == DBNull.Value) ? string.Empty : obj4), (HookType)((long)r["HookType"]), (uint)((long)r["ChainDepth"]), (uint)((long)r["Cookie"]), (double)r["Time"], (double)r["GenerationTime"], (int)((long)r["ParamMainIndex"]), (uint)((long)r["Pid"]), (uint)((long)r["Tid"]), (string)((obj5 == DBNull.Value) ? string.Empty : obj5), (string)((obj6 == DBNull.Value) ? string.Empty : obj6), (string)((obj7 == DBNull.Value) ? string.Empty : obj7), (bool)r["Success"], ancestors);
```

**Comment by alexr00** [comment]
Issue opened in owning repo.
@nblog you can try restructuring that line for a more immediate fix.
