### ISSUE TITLE
[Feature request]File filter/filename search in explorer panel.

### ISSUE THREAD

**Issue by Jammer77** [microsoft/vscode#87222]
It will be very convenient to have search or filter functionality in explorer panel.  Like in VS:

![image](https://user-images.githubusercontent.com/26893798/71063280-12e35500-2175-11ea-8345-846e56a5d2dc.png)

**Comment by roblourens** [comment]
We actually have this, you can type in the explorer viewlet to search or filter. But it's not very obvious or discoverable, we are aware of that :)
