### ISSUE TITLE
can only find installed python from start menu

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode#87234]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.can only start vscode from start menu ,then be able to find installed python
2.
![image](https://user-images.githubusercontent.com/46309533/71072494-99218a80-21b9-11ea-926c-6fbc2df13556.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
Did you allow VS Code to be added to the PATH variable on installation? Otherwise you will be able to start it from the terminal.
