### ISSUE TITLE
Matching tag edit

### ISSUE THREAD

**Issue by ttepede** [microsoft/vscode#87238]
Issue Type: <b>Bug</b>

Not certain this would always happen but while editing an html tag (a div to be specific, which was nested within another div), there were three cursors instead of two.

The extra cursor was editing the parent tag's first node.
So while the expected div was being edited, the extra cursor was causing a problem by change a parent node, which then leads to an unmatching tag for the parent.

I didn't insert multiple cursors manually, I believe this is a new functionality that makes it easier to edit matching tags?

![image](https://user-images.githubusercontent.com/45486209/71078474-5f349200-2181-11ea-844d-8f01d7e2a526.png)

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
Bookmarks|ale|10.6.0
ng-template|Ang|0.900.2
htmltagwrap|bra|0.0.7
path-intellisense|chr|1.4.2
githistory|don|0.4.11
gitlens|eam|10.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
json2ts|Gre|0.0.6
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
vscode-peacock|joh|3.2.0
theme-karyfoundation-themes|kar|18.2.1
Angular-BeastCode|Mik|8.1.2
vscode-todo-parser|min|1.9.1
vscode-scss|mrm|0.8.1
vscode-edge-devtools|ms-|1.0.6
azure-account|ms-|0.8.7
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.1424
debugger-for-chrome|msj|4.12.3
debugger-for-edge|msj|1.0.13
vetur|oct|0.22.6
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.20
reopenclosedtab|uyi|1.1.0
vscodeintellicode|Vis|1.2.0
vscode-todo-highlight|way|1.0.4

(3 theme extensions excluded)

</details>

**Comment by yume-chan** [comment]
Yes it's a new feature called [HTML mirror cursor](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor) shipped in Code version 1.41.

In my test it's conflicting with the Auto Rename Tag (formulahendry.auto-rename-tag) extension you have installed. Disable or remove it should resolve the problem.

**Comment by ttepede** [comment]
> Yes it's a new feature called [HTML mirror cursor](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor) shipped in Code version 1.41.
> 
> In my test it's conflicting with the Auto Rename Tag (formulahendry.auto-rename-tag) extension you have installed. Disable or remove it should resolve the problem.

I have removed it and seems to be fine after restarted VSCode.
Cheers
