### ISSUE TITLE
No js / ts syntax hints

### ISSUE THREAD

**Issue by xkmy** [microsoft/vscode#87232]
In recent days, when I open vscode, it shows that the js / ts import statement is being checked for updates. This has caused my vscode editor to have no js / ts syntax prompts. I tried restarting but it still does not work.can you help me？

**Comment by wengdongyang** [comment]
me too。please tell me how to fix the bug。

**Comment by xkmy** [comment]
> In recent days, when I open vscode, it shows that the js / ts import statement is being checked for updates. This has caused my vscode editor to have no js / ts syntax prompts. I tried restarting but it still does not work.can you help me？

Um, add that my operating system is windows10, I really do n’t know why vscode has always had such a problem recently, I hope you guys can help me, thank you very much!
