### ISSUE TITLE
Copying from terminal using Ctrl+Shift+C does not work anymore

### ISSUE THREAD

**Issue by jangxx** [microsoft/vscode#87230]
- VSCode Version: 1.41.0
- OS Version: Linux Mint 19.1

Steps to Reproduce:

1. Highlight some text in the built-in terminal
2. Press Ctrl+Shift+C to copy it

The clipboard now contains the path of the currently open file instead of the highlighted value. Turning off extensions seems to fix it, but I can't pinpoint which extension might be causing this problem (since none of the extensions should be doing anything to the terminal), so I'm filing the report here.

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
Some extension is registering a keybinding that replaces ctrl+shift+c, look at the default keybindings.json file to find it as extension keybindings are at the bottom of that.

<img width="338" alt="Screen Shot 2019-12-30 at 9 53 24 AM" src="https://user-images.githubusercontent.com/2193314/71593798-46fe3480-2aea-11ea-8429-6a50b2370366.png">
