### ISSUE TITLE
Settings settings should be contributed from settings

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#87239]
Noticed that a few `workbench.settings` values are coming in from `workbench.contribution.ts`. They should be contributed from the settings contrib.

**Comment by bpasero** [comment]
Hm, some seem to be used by core workbench services so they should probably stay:

![image](https://user-images.githubusercontent.com/900690/71079335-5f398f80-218b-11ea-950e-4e2372dc7f13.png)

**Comment by roblourens** [comment]
I moved the two settings that aren't used by the PreferencesService
