### ISSUE TITLE
Can't create files or folders

### ISSUE THREAD

**Issue by Harfeur** [microsoft/vscode#87236]
Issue Type: <b>Bug</b>

> The problem is currently on all my workspaces, and tried to disable all my extensions

> VSCode Insiders

When I try to create a file, I get the following error:
```
Unable to write file '\\c:\Users\maxou\Documents\GitBitHub\Talent-Map\test.js'
(Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\c:\Users\maxou\Documents\GitBitHub\Talent-Map')
```
And when I create a folder:
```
Error: UNKNOWN: unknown error, stat '\\c:\Users\maxou\Documents\GitBitHub\Talent-Map\test'
```
Here is a screenshot:
![image](https://user-images.githubusercontent.com/22135449/71073844-6d82ae00-2181-11ea-9253-b060d9893553.png)

VS Code version: Code - Insiders 1.42.0-insider (4636be2b71c87bfb0bfe3c94278b447a5efcc1f1, 2019-12-18T05:41:55.003Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.10
vsc-material-theme|Equ|30.0.0
beautify|Hoo|1.5.0
discord-vscode|icr|3.13.0
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
json-template|sto|0.3.1
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|9.6.0

</details>

**Comment by bpasero** [comment]
@isidorn related to your recent changes?

**Comment by isidorn** [comment]
@bpasero looks like this one https://github.com/microsoft/vscode/commit/85f587ab646c2d7bcbe902aee0cb48ccfcfdb4fe
Let me try to repro on windows and if I can I will freeze the build

**Comment by dbaeumer** [comment]
I can repro on Windows:

![image](https://user-images.githubusercontent.com/1931590/71074721-0fef6100-2183-11ea-8bc4-768fb28f3c65.png)

**Comment by isidorn** [comment]
Ok freezing build. Will release a new insiders once I push a fix

**Comment by GraxFU** [comment]
same here:
`Error: UNKNOWN: unknown error, stat '\\c:\Users\gregory.erb\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\etc\ansible\playbooks\asdasdasd'`

**Comment by isidorn** [comment]
I have verified that my change `85f587a` broke this. I appologize for this. I have triggered a new build and will release a new insiders once it is out (in like an hour or so).

**Comment by isidorn** [comment]
We released insiders which contains the fix, thus closing this
