### ISSUE TITLE
New debug/run experience always writes launch.json into first workspace folder

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#87237]
The new "Create a launch.json file" link on the side bar (I think part of https://github.com/microsoft/vscode/issues/85774) always creates the launch.json in the first workspace folder for a multi-root workspace. This feels a bit weird since it replaces the other UI that lets you choose which workspace folder to create one for - so as far as I can tell, there's no simple way for me to now create a launch.json for a workspace folder that is not the first one.

Here, I wanted to create a launch.json for `flutter_tools` but was not given a choice, it just went into `flutter_test` and I had to drag it around. Since there's already a picker that lets me choose a workspace folder (for ex. when spawning a new terminal) I think it could be used here?

<img width="334" alt="Screenshot 2019-12-18 at 10 10 08" src="https://user-images.githubusercontent.com/1078012/71077041-96ee0a80-217e-11ea-8a03-75b62ce8192c.png">

<img width="585" alt="Screenshot 2019-12-18 at 10 10 28" src="https://user-images.githubusercontent.com/1078012/71077119-bd13aa80-217e-11ea-8302-79bb576df5b4.png">

**Comment by DanTup** [comment]
Actually, it's worse than that - if you drag the `.vscode` folder into the second workspace folder, it does *not* update the debug side bar - so I still see the "new experience" UI even though I now have a `.vscode` folder in the second workspace folder. I can't see a way to select the debug config.

**Comment by DanTup** [comment]
As a workaround, re-ordering the folders in the `.code-workspace` file so one with `.vscode/launch.json` comes first does result in the "normal" debug sidebar UI.

**Comment by isidorn** [comment]
@dantup I have changed the configure action to always ask if you have multple folders in your workspace. Please try it out in tomorrow's vscode insiders.
As for the debug start view being stale even if you move the launch.json around. I could not reproduce that, but that sounds like a file event missing on the configuration service. So if you still see that please file an issue with steps, thank you
![Screenshot 2019-12-18 at 16 44 15](https://user-images.githubusercontent.com/1926584/71100766-e3a10800-21b5-11ea-93a7-123567a5d26e.png)

**Comment by DanTup** [comment]
Thanks! I'll test it tomorrow and open another issue if I still see the other issue.

**Comment by DanTup** [comment]
Original fix looks good - I've opened https://github.com/microsoft/vscode/issues/87324 for the other issue with repro steps. Thanks!

**Comment by isidorn** [comment]
Thanks, adding verified label then.
