### ISSUE TITLE
Title appears different when menu is visible vs not

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#87233]
On Linux with custom title enabled I see different visual appearance when menu is hidden vs not.

**Hidden:**

![image](https://user-images.githubusercontent.com/900690/71072029-f7307c80-217d-11ea-9d97-72f7c162ae19.png)

**Visible:**
![image](https://user-images.githubusercontent.com/900690/71072039-fc8dc700-217d-11ea-8897-e643a10992f1.png)

E.g. the application logo becomes smaller?

**Comment by bpasero** [comment]
Just toggle back and forth to spot the differences.

**Comment by sbatten** [comment]
I am using Ubuntu 19.04 in a VM and cannot spot the differences :/

**Comment by bpasero** [comment]
Ok odd, I can try again today in office. I am using Ubuntu 18 btw. Oh, and I have always zoom level on (+1), can you try that?

**Comment by sbatten** [comment]
good idea, but still no luck, im not able to reproduce on 19.04 with zoom.
