### ISSUE TITLE
The terminal scrolls too much on a mouse wheel

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#87240]
Version: 1.42.0-insider (user setup)
Commit: 4636be2b71c87bfb0bfe3c94278b447a5efcc1f1
OS: Windows_NT ia32 10.0.18362

@Tyriar This is a top pain point for me.

When using the terminal, oftentimes I need to scroll up to see some older output. When working on my macbook and using the touchpad, this works great. But when using my Windows desktop with a physical mouse which has a physical mouse wheel, one flick of the mouse wheel scrolls more than one terminal page. It scrolls so much that 10 lines of the terminal are entirely skipped.

To reproduce, execute the following:

```js
for (let i = 0; i < 100; i++) {
    console.log(`LINE ${i + 1}`);
}
```

* plug a mouse with a mouse wheel on Windows
* do one mouse wheel flick: (note how lines 80-88 are not rendered at all)

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/71078697-2d73f900-218a-11ea-9b00-1128990d4ba8.gif)

**Comment by Tyriar** [comment]
@alexdima what do you have `editor.mouseWheelScrollSensitivity` set to?

**Comment by Tyriar** [comment]
@alexdima use `terminal.integrated.mouseWheelScrollSensitivity` and `terminal.integrated.fastScrollSensitivity` to configure the terminal specifically now.

**Comment by StormFalcon32** [comment]
@Tyriar I just got vscode insiders for this, but it says "Unknown configuration setting" when I add "terminal.integrated.mouseWheelScrollSensitivity": 0.5 to the settings.json. The scrolling behavior doesn't change. Am I doing something wrong?

**Comment by Tyriar** [comment]
@StormFalcon32 there likely won't be a new Insiders build until the 6th due to the holidays.

**Comment by StormFalcon32** [comment]
@Tyriar ah thank you

**Comment by alexdima** [comment]
Thank you @Tyriar , this works great !! :heart:
