### ISSUE TITLE
Support jump to file inside remote container

### ISSUE THREAD

**Issue by dionysiosarvanitis** [microsoft/vscode#87248]
Normally, by clicking at the pencil of the image below, you're redirecting to the exact line of code where the error initiated.

![UseCase](https://user-images.githubusercontent.com/1359269/71239069-49a0a300-230e-11ea-94d3-1eab976c297b.png)

The link generated by the app is at the format of `vscode://file/%path:%line`.

In the example below, the path generated is `vscode://file/%2Fvar%2Fwww%2Fhtml%2Fapp%2FHttp%2FControllers%2FWelcomeController.php:18`. But, when the file resides in a remote container you get the error below

![Error](https://user-images.githubusercontent.com/1359269/71239076-4dccc080-230e-11ea-9be7-cbe995d33e05.png)

**Comment by roblourens** [comment]
Please give more details

**Comment by dionysiosarvanitis** [comment]
ping @roblourens
