### ISSUE TITLE
Font rendering issue when plugging/inplugging external monitor

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#87249]
- VSCode Version: 1.41.0
- OS Version: macOS Catalina 10.15.2

Steps to Reproduce:

I think the problem appears when mixing HDPI (Retina) and HD displays.

1. Plug in an external (non-retina) monitor
2. Start VSCode, move the window onto the external monitor
3. Go to fullscreen and change virtual screen so that VSCode is not visible
4. Unplug the monitor
5. Change virtual screen so that VSCode is visible

Notice how some fonts are not correctly rendered (sometimes it only happens on a subset of VSCode: the Terminal view, or all views).

More informations on my configuration:
 - MacBook Pro 13" 2017, resolution: 2560 x 1600
 - External monitor HDMI through USB-C dongle, resolution: 1920 x 1200 (WUXGA)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/199648/71086784-fc4ff480-219a-11ea-98d8-f80b30b8ff0f.png)

![vcodeFonts](https://user-images.githubusercontent.com/199648/71086913-489b3480-219b-11ea-98c9-ed8f4f1156c2.jpg)

**Comment by warpdesign** [comment]
Note: as a workaround, exiting full screen mode appears to be enough to fix the problem.

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?
