### ISSUE TITLE
workspace.createFileSystemWatcher is sensitive to drive letter casing

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vscode#87257]
I am developing a language server around the feature `workspace/didChangeWatchedFile`.

With vscode language client, whenever registering a watcher using absolute path with the Windows drive letter to be upper-case (e.g., C:/...), the client will fail to report file events. It will work normally if lower-case drive is used (e.g., c:/...).

Since vscode client uses `workspace.createFileSystemWatcher` for watching files, it may be root-caused by glob matching issue. Add following tests to glob test:
```typescript
p = 'C:/DNXConsoleApp/**/*.cs';
assertGlobMatch(p, 'c:\\DNXConsoleApp\\Program.cs');
assertGlobMatch(p, 'c:\\DNXConsoleApp\\foo\\Program.cs');

p = 'c:/DNXConsoleApp/**/*.cs';
assertGlobMatch(p, 'C:\\DNXConsoleApp\\Program.cs');
assertGlobMatch(p, 'C:\\DNXConsoleApp\\foo\\Program.cs');
```
It can be seen that above tests will fail.

### Environment

- VSCode Version: 1.41.0
- OS Version: Windows 10

### Steps to Reproduce
1. Use `workspace.createFileSystemWatcher` to listen to an absolute path in Windows, with device being `c:` and `C:`.
2. Modify a file that matchs the glob, see that whether a file event is notified in these two watchers.

This issue may add another vote for https://github.com/microsoft/vscode/issues/10633. This behavior is confusing for the language server developer since they will not be able to use `new RelativePattern(workspaceFolder, pattern)`, but to construct the path on their own.

**Comment by Vigilans** [comment]
Example of confusion in [java language server](https://github.com/eclipse/eclipse.jdt.ls/blob/cf6358ba4c166fa7d4c45aba5b7b22ea08516524/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java#L257-L261):
```java
if (path.getDevice() != null) {
    //This seems pretty hack-ish: need to remove device as it seems to break
    // file detection, at least on vscode
    globPattern = globPattern.replace(path.getDevice(), "**");
}
```

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/10633

**Comment by bpasero** [comment]
Workaround:

```js
p = '[cC]:/DNXConsoleApp/**/*.cs';
assertGlobMatch(p, 'c:\\DNXConsoleApp\\Program.cs');
assertGlobMatch(p, 'c:\\DNXConsoleApp\\foo\\Program.cs');
```

**Comment by dmitrivMS** [comment]
This should now work without workarounds on Windows.
