### ISSUE TITLE
Import  not working

### ISSUE THREAD

**Issue by yogesh1234567890** [microsoft/vscode#87253]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

when i am trying to import class from another file with correct link the import doesnt work

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 5.0.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2441)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.76GB (0.38GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   123	  4729	code main
    0	    35	  4801	   zygote
    0	    92	  4835	   gpu-process
    0	   212	  4852	   window (cause_models.py - vms - Visual Studio Code)
    0	   243	  4906	     extensionHost
    0	    54	  4955	       electron_node server.js 
    0	    85	  5019	       /home/yogesh/.vscode/extensions/ms-python.python-2019.11.50794/languageServer.0.4.127/Microsoft.Python.LanguageServer
    0	     4	  4914	     /bin/bash
    0	    62	  4936	     watcherService
    0	    62	  4978	     searchService
    0	   104	  4888	   shared-process
    0	     0	  5412	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  5413	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   104	  5385	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (cause_models.py - vms - Visual Studio Code)
|    Folder (vms): 152 files
|      File types: py(46) pyc(45) html(6) css(5) map(4) js(4) eot(1) svg(1)
|                  ttf(1) woff(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.19.0
django|big|1.0.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.16.1
chat|kar|0.29.0
python|ms-|2019.11.50794
vsliveshare|ms-|1.0.1377
vsliveshare-audio|ms-|0.1.80
django-intellisense|sha|0.0.2
python|tht|0.2.3

</details>

**Comment by IllusionMH** [comment]
Most likely you need to report this issue in https://github.com/microsoft/vscode-python/issues/ and provide more details about your setup if it is in Python files.

**Comment by dbaeumer** [comment]
@yogesh1234567890 can you please provide the data that got copied into the clipboard in case you can reproduce. And if it happens in a Python file please report it against the owner of the extension.
