### ISSUE TITLE
first figure in Plots only left half can be seen

### ISSUE THREAD

**Issue by hanwsf** [microsoft/vscode#87255]
Issue Type: <b>Bug</b>

Then only adjusting the Python Interactive columne, then the first figure can be shown fully.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.68GB (1.39GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
kite|kit|0.102.0
python|ms-|2019.11.50794
python|tht|0.2.3

</details>

**Comment by IllusionMH** [comment]
Is it with Jupyter notebooks? Most likely you need to report this issue in https://github.com/microsoft/vscode-python repo

**Comment by dbaeumer** [comment]
Agree with @IllusionMH .
