### ISSUE TITLE
Intellisence is not working

### ISSUE THREAD

**Issue by ankconstruct** [microsoft/vscode#87251]
Suddenly Intellisence popup box is not at all appearing.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible without extensions?
You can try this with F1 and >Developer: Reload Window With Extensions Disabled

What is language? What is configuration?

**Comment by AstrisDev** [comment]
I'm agree with topic starter.
For me it is not work in JS (react). I'm disabled all of my extensions and it still not show me autocompleteion pop. It shows me only "Loading..." text.

**Comment by mjbvz** [comment]
Closing as not actionable without more information from the original poster about how the reproduce the problem
