### ISSUE TITLE
cant 

### ISSUE THREAD

**Issue by congtrieu112** [microsoft/vscode#87252]
Issue Type: <b>Feature Request</b>

i cant open go to function code

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.7.0

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible without extensions?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

What is language? What is configuration?
