### ISSUE TITLE
Collapse all test suites

### ISSUE THREAD

**Issue by stevevg** [microsoft/vscode#87260]
In the test panel, a command to collapse all test suites would be a nice to have feature. For big projects with lots of test classes, closing all the various sections becomes cumbersome.
Moreover, everytime you start VSCode, test suites are all open.

**Comment by stevevg** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [FileSystemProvider: have a reference test suite (#48664)](https://www.github.com/microsoft/vscode/issues/48664)

this is no duplicate of #48664

**Comment by IllusionMH** [comment]
/causedByExtension

You should report this issue in repo of the extension that provides test panel because VS Code  doesn't provide Test panel by itself.

Please let developers know if you are sure that this issue was closed by mistake and provide more details.
