### ISSUE TITLE
Santa Hat on vscode insiders and pushing of religion is very offensive to me

### ISSUE THREAD

**Issue by Christian-Schiffer** [microsoft/vscode#87268]
The Santa Hat on vscode insiders and pushing of religion is very offensive to me, additionally xmas has cost millions of Jews their lives over the centuries, yet even if that was not the case, pushing religious symbols as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

Version: 1.42.0-insider (user setup)
Commit: 26f5dfcd76c9a02f116a706844611aeb09ae8c0b
Date: 2019-12-18T10:34:34.277Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install latest build of insiders.

Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered. https://www.sefaria.org/sheets/51928?lang=bi

**Comment by Christian-Schiffer** [comment]
![Offensive](https://user-images.githubusercontent.com/4748045/71110025-c9bbf100-21c6-11ea-8531-666e20a812a1.jpg)

**Comment by kieferrm** [comment]
@Christian-Schiffer we're sorry we hurt your and other's feelings. We'll remote the Santa Hat.

**Comment by 99z** [comment]
lol

**Comment by friendlyanon** [comment]
This is why we can't have nice things.

**Comment by Christian-Schiffer** [comment]
Thank you, I am very pleased with that decision. I understand many find this strange, therefor I would like to add an article about how offensive xmas is to many so you understand why. https://www.sefaria.org/sheets/51928?lang=bi

**Comment by docbiz** [comment]
> still there where people who did not understand the offence
Some of us don't respect the fact that you are offended; that doesn't entail that we don't understand why you are offended.

**Comment by Christian-Schiffer** [comment]
> you

Well million of people have been tortured and murdered because of it and you still do not understand why it is offensive? Unbefreakinglieveble.

**Comment by Perustaja** [comment]
This is what Twitter-culture has done to people. You should be more concerned with your flag than a little hat on a settings button.

**Comment by zetanor** [comment]
![Untitled](https://user-images.githubusercontent.com/6922903/71124722-78eecd00-21b3-11ea-9812-ab18272a47db.gif)

**Comment by Christian-Schiffer** [comment]
> This is what Twitter-culture has done to people. You should be more concerned with your flag than a little hat on a settings button.

Here we go again, I am so disgusted with people who want to have "fun" dancing on the grave of others. I am not Jewish by the way, I am German, a Noahide. As a German I do have a responsibility to speak out against things like that. Yet, the level of dismay and disgust I feel when reading such comments, I am not able to try to help people who do not want to see the light. This will be my last comment, downvote it as much as you like. It speaks about nothing else then your character or rather, lack thereof.

**Comment by spuriklaus** [comment]
I certainly hope whoever added this hate speech to VSCode is FIRED.

**Comment by faissaloo** [comment]
If it bothers you fork it and remove it yourself, or use another editor (I suggest ed). You don't get to tell people not to have their celebrations.  
t. Someone who doesn't celebrate Christmas

**Comment by egamma** [comment]
Closing the issue as confirmed by @Christian-Schiffer the issue has been addressed.

**Comment by egamma** [comment]
I've also deleted the discussion that does not belong into our issue tracker.

**Comment by kieferrm** [comment]
See https://github.com/microsoft/vscode/issues/87440.
