### ISSUE TITLE
Regression: lost ability to drop a folder into Code to open it

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8726]
Now we try to open the folder as editor which fails. We should detect that a folder is dropped and give the right feedback.

**Comment by f111fei** [comment]
extension file like `.vsix` need also give the right feedback.

**Comment by bpasero** [comment]
I pushed a fix for it, @f111fei maybe you check it out when we push July insider builds (sometime after we released stable this week).

**Comment by f111fei** [comment]
@bpasero  Extension install failed. I push a PR for this. See https://github.com/Microsoft/vscode/pull/8786

**Comment by bpasero** [comment]
@f111fei thanks for reporting, looks like another issue. I have assigned @joaomoreno and @isidorn to look into that.

**Comment by f111fei** [comment]
Another problem. I am not sure why you add the code `DOM.EventHelper.stop(e);` when `dragover` and `drop`.

https://github.com/Microsoft/vscode/blob/5da820a3b5f0e510abca2aab8645b0d4c8f7726f/src/vs/workbench/electron-browser/window.ts#L91
https://github.com/Microsoft/vscode/blob/5da820a3b5f0e510abca2aab8645b0d4c8f7726f/src/vs/workbench/electron-browser/window.ts#L132

**Comment by bpasero** [comment]
@f111fei by default if you drop a link into an electron window it will try to navigate to that URL. so this is needed to prevent a link from opening.

**Comment by f111fei** [comment]
Yeah. I am writing an extension for vscode. I use `vscode.previewHtml` to show my html document in `webview`. In my html, I add some listeners like `dragover` and `drop`, but these listeners will also prevented.

**Comment by bpasero** [comment]
@f111fei that surprises me because the drag listeners on the editor area and tabs are also working even with that code. Also, this is not a new change, you can see how this was prevented before already: https://github.com/Microsoft/vscode/blob/1.2.1/src/vs/workbench/electron-browser/window.ts#L67

**Comment by f111fei** [comment]
Maybe this is a bug existed for a long time. I will push an issue for this.

**Comment by bpasero** [comment]
@f111fei please try if you can fix it by removing the drag over handler maybe? What is interesting is that a HTML preview in Code actually runs in a different process (more isolated even than an iframe), so I wonder how DND behaves in this case anyways.

**Comment by f111fei** [comment]
As I know, If `renderer process` prevent default handler like `keydown`,   some shortcut operations like `copy`, `cut` will not be executed in `webview`.  I think DND is just that.

**Comment by f111fei** [comment]
@bpasero  This is the issue https://github.com/Microsoft/vscode/issues/8794 about this
