### ISSUE TITLE
"Value is not accepted" warnings in the default keybindings.json

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#87265]
Issue Type: <b>Bug</b>

I'm getting many _"Value is not accepted"_ warnings in my default `keybindings.json`.

<img width="1297" alt="Screen Shot 2019-12-18 at 11 00 48 AM" src="https://user-images.githubusercontent.com/1993919/71102097-d8ce7f00-2185-11ea-95cb-c25279430ed7.png">

VS Code version: Code - Insiders 1.42.0-insider (26f5dfcd76c9a02f116a706844611aeb09ae8c0b, 2019-12-18T10:32:01.697Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (24.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.2.1
vscode-database|baj|2.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
gitlens|eam|10.2.0
LogFileHighlighter|emi|2.6.0
shell-format|fox|6.1.3
seito-openfile|Fr4|1.8.5
mdmath|goe|2.4.0
gc-excelviewer|Gra|2.1.32
open-file-from-path|jac|1.3.3
latex-workshop|Jam|8.5.0
vsc-space-block-jumper|jmf|1.2.2
center-editor-window|kai|2.3.0
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
sqltools|mtx|0.21.5
neuron-IPE|neu|1.0.4
vscode-ipython|pan|0.5.0
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.6.1
vscode-dired|rru|0.0.4
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.0
emacs-mcx|tut|0.13.0
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.6.0
org-mode|vsc|1.0.0
highlight-trailing-white-spaces|yba|0.0.2
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by alexdima** [comment]
@amelio-vazquez-reina My `keybindings.json` file has no errors. Can you please share your `keybindings.json` file ?
