### ISSUE TITLE
Bracket-only indent guides

### ISSUE THREAD

**Issue by alkaitagi** [microsoft/vscode#87267]
It would be nice to have an option to render indent guides only inside bracket-defined regions instead of on every tab.

![image](https://user-images.githubusercontent.com/32439229/71104703-43ef7400-21cd-11ea-9083-0dbbc7fea60a.png)

![image](https://user-images.githubusercontent.com/32439229/71104858-8b760000-21cd-11ea-8c9c-92a46b05f4c8.png)

**Comment by alkaitagi** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Indent Guides Have Breaks Where CodeLens UI is Rendered (#9604)](https://www.github.com/microsoft/vscode/issues/9604)
> * [Feature Request: Smarter indent guides (#48772)](https://www.github.com/microsoft/vscode/issues/48772)
> * [Indent guides are rendered for empty lines in gitlens's file blame panel (#51484)](https://www.github.com/microsoft/vscode/issues/51484)
> * [Tree Guide Indents not showing in latest Insiders (#86675)](https://www.github.com/microsoft/vscode/issues/86675)

Right, a duplicate of #48772. That issues is more than 1 year old, so far was there any update?

**Comment by gjsjohnmurray** [comment]
/duplicate @alkaitagi please continue your contribution there.
