### ISSUE TITLE
Terminal in Visual Studio Code (git-bash as default) isn't printing entire HTML code

### ISSUE THREAD

**Issue by jgarwin95** [microsoft/vscode#87269]
Issue Type: <b>Bug</b>

Using html-requests python package. When trying to print the html of a website to the terminal inside visual studio code it truncates it severly. 

`
from requests_html import HTML, HTMLSession

new_session = HTMLSession()

r = new_session.get('https://www.sample-website.com')

print(r.html.html)
`

This is not a problem with the code or the package extensions as it will print the entire HTML when running directly from the git-bash terminal. I know its simple step to just move over to the terminal to run but the thing that makes VScode stand apart is its ease of use. 

Thanks.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.15
html-preview-vscode|geo|0.2.5
python|ms-|2019.11.50794

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
