### ISSUE TITLE
Allow to override list styling for quick input and other places (notifications)

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#87278]
atm list styling is the same for both sidebar ex.`tree, extensions, etc...` and the quick input panel `ctrl+shift+p`.

however this assumes that both of them have the same background and foreground styling which is not true, so is it possible to add a separate list styling for both ?

**Comment by aeschli** [comment]
You basically ask for more quick input colors. Which colors in particular?

**Comment by ctf0** [comment]
sure , to make things easier to understand lets say we have styles for sidebar as
```
"sideBar.background": "#1a1a1a",
"sideBar.foreground": "#ffffff",
```

and for quick input as 
```
"quickInput.background": "#f4f6fc",
"quickInput.foreground": "#1a1a1a",
```

now something like
```
"list.focusBackground": "#0064ff26",
```

will work perfectly for the quick input but not for the sidebar, so for now "unless u have more scenarios u can think of" haveing a different `focusBackground` would be enough
