### ISSUE TITLE
Incorrectly using raw device colors on Mac OS X

### ISSUE THREAD

**Issue by geoelectric** [microsoft/vscode#87275]
- 1.41.0
- OS X 10.15.1

I realize this has been discussed in other threads in general, but the discussion has been dominated by Linux concerns. This issue is specific to Mac.

On Mac, you have the option of using tagged colors or untagged colors. Untagged colors are display-native and uncalibrated, whereas the norm is to pick in SRGB (or similar) color space with a *tagged* color that will be translated to the appropriate calibrated color.

Chrome started using untagged colors in an update last year, which makes it display things like Solarized differently than native apps do. Electron followed, so did VS Code.

While the colors remain *close*, they won't be the same as native apps so they look funky next to each other.

In other threads, it's been determined there's no need for a way to force profiles, but that's exactly what must be done in Chrome via chrome://flags to fix the discrepancy on Mac and we need the option here too. 

I've tried using the code launcher and editing main.js for the command-line option, and neither seem to work (code launcher won't pass the option through, main.js did nothing).

STEPS

1. Install Solarized in both MacVim/iTerm/Terminal/etc. and VS Code
2. Use Digital Color Meter built-in utility, choose SRGB color space + hex
3. Mouse over background of native app, observe ~00 2B 36 background

<img width="843" alt="Screen Shot 2019-12-18 at 12 04 35 PM" src="https://user-images.githubusercontent.com/314134/71119650-7ed2b700-218f-11ea-93a0-62918339be18.png">

4. Mouse over background of VS Code, observe different color (if monitor using default calibrated profile)

<img width="855" alt="Screen Shot 2019-12-18 at 12 04 42 PM" src="https://user-images.githubusercontent.com/314134/71119684-9873fe80-218f-11ea-9345-7f4843ffe619.png">

5. Switch Digital Color Meter to native colors
6. Mouse over background of VS Code, observe 00 2B 36

<img width="832" alt="Screen Shot 2019-12-18 at 12 04 52 PM" src="https://user-images.githubusercontent.com/314134/71119706-a7f34780-218f-11ea-9f21-838f448cbe58.png">

7. Mouse over background of native app, observe different color (if monitor using default calibrated profile)

<img width="829" alt="Screen Shot 2019-12-18 at 12 04 48 PM" src="https://user-images.githubusercontent.com/314134/71119745-bc374480-218f-11ea-805f-c603d4c7b462.png">

8. Change monitor profile to sRGB (this removes any translation due to calibration), try all steps again. and observe all values are on/close to 00 2B 36 and that native/VSS are aligned in color.

NOTES

* Sorry for no cursors in the shots, they don't take with screenshots.

* Likely due to similar translation issues, if you view the screenshots in Chrome, both VS Code and MacVim render the same native colors . View this issue in Safari and there's a visible difference and Digital Color Meter will show it as well. You can also save the screenshots and use Preview, which also shows the difference.

* While the 00 2C 37 "sRGB" color coming back from VS Code looks close numerically, the visible difference in saturation shows that it's an artifact of native and sRGB gamuts being different sizes. Translating in the right direction gives a noticeably different native color (0E 2A 35) vs. the other way (00 2B 36).

* You can do the same viewing https://ethanschoonover.com/solarized/ in Chrome vs. Safari and mousing over his screenshots to see the issue there as well and validate that it's a Chrome color space issue that the force-profile flag solves. Safari demonstrates reference behavior for OS X.

WORKAROUNDS 

The workaround of setting the monitor to SRGB color space will align colors between native and SRGB, but moves the display out of calibration. In particular, on high-gamut iMac and MacBook Pro displays, colors (reds especially) become quite bright.

Worth noting that some people like the brighter colors, based on threads where people selected sRGB exactly to get that effect in native apps. A flag is ideal vs. a "fix it in the launcher" approach.

REQUESTED SOLUTION

Expose the chrome://flags#force-color-profile flag so that it can be set on Mac to the user's preference.

**Comment by woody77** [comment]
Excellent explanation.  (I found this trying to open the same issue).  What I'm finding interesting is that Chrome itself (on MacOS Catalina) seems to be using colors correctly (converting "web colors" from sRGB to native via the calibration profile).  But VSCode is not.

**Comment by deepak1556** [comment]
You can now set this option via runtime arguments

* Open the Command Palette (⇧⌘P).
* Run the Preferences: Configure Runtime Arguments command.
* "force-color-profile": 'srgb'
