### ISSUE TITLE
Quick fix context menu in problems pane

### ISSUE THREAD

**Issue by icleolion** [microsoft/vscode#87277]
Apologies if this is a vscode issue and not an issue with the ESLint extension.  Might not be terribly clear from my poor attempt at screen capturing, but the wrong context menu appears when right clicking on problems.  

It's something I've noticed since back in the 1.9.x days. I'm running 2.0.6 at the moment and it's taken me till now to realise it happens if I right click on the line before the red X changes to a yellow lightbulb when hovering over the line.  

This requires a very fast right click for whichever line you click on first as the yellow lightbulb appears quite quickly.  But after right clicking the first one, it's easy to reproduce on the others as while the context menu is active it blocks the on hover event when you move the cursor over another problem.  Once the quick fix menu appears for a problem, it will always appear on subsequent right clicks on that same problem even if you right click before the red X changes to a yellow lightbulb again.

![peek](https://user-images.githubusercontent.com/47498402/71118627-65059400-21d0-11ea-98c4-a92bf6af9f82.gif)

Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
Yeah this is because of the delay for loading quick fixes. I am not sure if there is anything that can be done.
