### ISSUE TITLE
[feature] get cursor position for inputs

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#87272]
atm the only api available to get the cursor position is within an editor, but what about inputs ?

lets say u have an ext like https://github.com/edgardmessias/vscode.clipboard-manager which manages the clipboard globally, 
but because of the current api limitation we cant use it with inputs & we have to either 
- manually write the text 
- or open an editor > get the content from the ext > copy it > paste it into an input.

i've searched the docs for such option but couldn't find any, so it there any plans to support exposing the input fields to the api ?

**Comment by jrieken** [comment]
That's the design - not all UX elements have API representations. However, we are using the text editor in more places (and have plans to use it even more) and that allows to interact with such inputs just like with any other text editor
