### ISSUE TITLE
Maximized window is too large

### ISSUE THREAD

**Issue by tomburger** [microsoft/vscode#87279]
Issue Type: <b>Bug</b>

When VS Code window is on secondary monitor, it is bigger than it should be.
This is a screenshot from the corner of the window:
![image](https://user-images.githubusercontent.com/101147/71122295-879fa900-21e0-11ea-843f-89f72e24a1de.png)
- other three corners look similar.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (5.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
team|ms-|1.161.0
LiveServer|rit|5.6.1

</details>

**Comment by Silic0nS0ldier** [comment]
I've also experienced this issue, window content extends beyond its actual bounds. Issue also occurs when windowed (can tell as dragging to resize in the bottom right has the drag point too far in).

This is on a Surface Book 2 (high DPI screen) paired with 2 23" full HD screens (comparably lower pixel density).

This hasn't been an issue in the past, I first noticed the issue a few weeks ago, but hadn't the chance to report.
![Annotation 2019-12-19 094348](https://user-images.githubusercontent.com/17376090/71130111-47264680-2245-11ea-849e-3cb474b7c720.png)
