### ISSUE TITLE
Split-view: Highlight occurrences of text in other windows

### ISSUE THREAD

**Issue by herodionem** [microsoft/vscode#87274]
When I have multiple windows open for the same file I often find myself wishing that the auto-hint/highlight feature that's already present in the active window for all occurrences of the text that is either actively highlighted or simply has the cursor at rest in a given word would be applied to all open windows for that file (or even for all open windows.

![image](https://user-images.githubusercontent.com/24979523/71116019-7c249180-2190-11ea-9765-220eed10f800.png)

**Comment by atorr0** [comment]
Hi,

I think this feature is so useful as long as splitting-view is. Please, could you give it a boost?

TY!

**Comment by lonix1** [comment]
Until this is implemented, does someone know of a plugin that does this?

**Comment by RollingHog** [comment]
Same here. This should be a default-enabled feature, I must say - it is too useful.

**Comment by Ankit7991** [comment]
Yes please, that will save some time to go find same string in other screen.

**Comment by Kochise** [comment]
https://github.com/microsoft/vscode/issues/30014

**Comment by jrieken** [comment]
This has happened 🥳
