### ISSUE TITLE
Clicking in the scrollbar jumps to where I clicked

### ISSUE THREAD

**Issue by StasD** [microsoft/vscode#87273]
- VSCode Version: 1.41.0
- OS Version: macOS 10.15.2

Why, in the latest version, clicking in the scrollbar jumps to where I clicked? It should just scroll to the next "page", as I specified in "System Preferences" -> "General": "Click in the scroll bar to:" -> "Jump to the next page" vs. "Jump to the spot that's clicked".

Steps to Reproduce:

1. In VSCode version 1.41.0, click in the scroll bar of any long file opened.
2. Observe the behavior.

(It is, theoretically, possible, that this behavior started even before 1.41.0, but it's unlikely: I would have noticed :))

**Comment by alexdima** [comment]
@StasD This is the VS Code behaviour since day 1.

**Comment by martingbrown** [comment]
While we are at it would it be possible to have arrows at either end to move a single line per click or continious scroll if held down please?
