### ISSUE TITLE
Add Copy Extension Id action for an extension in extensions viewlet

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#87284]
Add Copy Extension Id action for an extension in extensions viewlet

**Comment by isidorn** [comment]
I have verified that the action is there. Thus adding verified label.
However I personally do not see the need for such an action in such a prominent place. Why would the user need this?

**Comment by sandy081** [comment]
You need extension Id at multiple places like in adding workspace recommendations in workspace recommendations file, or adding to package.json extension dependencies, also to share it just like setting id.
