### ISSUE TITLE
Tabs: hover improvements

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8728]
- the hover should appear over the full area of the tab

/cc @alexandrudima

**Comment by alexandrudima** [comment]
:heart: TY!

**Comment by bpasero** [comment]
@alexandrudima I looked into the custom hover and was not convinced yet. however, maybe we could combine a custom hover for the path with an area to get the editor actions back? I am suffering a lot from the fact that those are hidden. Will comment on https://github.com/Microsoft/vscode/issues/7666
