### ISSUE TITLE
SCM Panel is blank

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#87283]
- VSCode Version: 1.41.0 (prior version as well)
- OS Version: Windows 10 1909
- Git Version: 2.24.1.windows.2, been happening on prior versions as well)

I have a specific folder/git repository, where, when VS Code is opened to this folder, if the SCM view is not the starting view, the view fails to load when switched to.  If the SCM view was the starting view, then the view seems to work even after switching to another view and back later.

This particular repository is also showing file changes doubled (note in the image below).

I am noticing in the git output, that some commands are doubled.  This is a relatively new folder, repository, that was just simply started with `git init` and not much more, and its been acting this way since the beginning.

I also often use this same folder in a work-space along with another folder, also a fairly freshly init'd repository, and it works fine, but the folder that is a problem by itself is also a problem with the work-space file, and thus because the SCM view will not appear prevents easy access to the other folder's SCM.

git output for reference.  Note the doubling of some commands near the end.
```None
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.24.1.windows.2 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: \\rk-vs-fs1\Users Folders\cmorris\My Documents\Projects\RMA database
> git fetch
> git status -z -u
> git show :Query Samples.sql
> git symbolic-ref --short HEAD
> git check-ignore -v -z --stdin
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --local branch.master.github-pr-owner-number
> git config --get commit.template
> git status -z -u
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: \\RK-VS-FS1\Users Folders\cmorris\My Documents\Projects\RMA database
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git show :Items and Labels testing.sql
> git rev-parse master
> git symbolic-ref --short HEAD
> git rev-parse --symbolic-full-name master@{u}
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git rev-parse master
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git rev-parse --symbolic-full-name master@{u}
> git config --get commit.template
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git config --local branch.master.github-pr-owner-number
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git fetch
> git fetch
> git status -z -u
> git status -z -u
> git symbolic-ref --short HEAD
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git config --get commit.template

```

These show the view when in the work-space setup.
Here it is when it fails.
![image](https://user-images.githubusercontent.com/26179051/71117448-c19a8c00-219b-11ea-8a30-b09288139248.png)

Again after a `Reload Window`
![image](https://user-images.githubusercontent.com/26179051/71117737-58674880-219c-11ea-81bb-cf99af660f44.png)

Does this issue occur when all extensions are disabled?:  Disabled GitLens, no change, need to do more checking.

**Comment by joaomoreno** [comment]
If you open the Developer Tools, is there any error, when the view is empty?

**Comment by msftrncs** [comment]
I'll try looking there, but surprisingly just the last couple of days it hasn't been an issue suddenly.   I'm not aware of any changes I would have made, only automated updates such as extensions.

**Comment by joaomoreno** [comment]
Awesome, let me know if it comes back.
