### ISSUE TITLE
Bug on vscode stable release and pushing of slaughter is very offensive to me 

### ISSUE THREAD

**Issue by BLUEBOUNCE** [microsoft/vscode#87286]
The bug-icon on vscode stable and pushing of slaughter and killing is very offensive to me, additionally "bug hunting" has cost millions of bugs their lives over the centuries, yet even if that was not the case, pushing slaughter as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as killing another human.

I propose to remove at least the "x" from the back of the bug, or remove the bug completely.

Image of the poor creature:
![img](https://i.imgur.com/Taz2aRt.png)

Version: 1.40.1 (user setup)
Commit: unknown
Component: activity bar
Date: 2019-12-18T10:34:34.277Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

    Install latest build of stable.

Does this issue occur when all extensions are disabled?: Yes

**Additional reading on the issue that most certainly needs to be considered.** https://www.outdoorjournal.com/slider/human-lives-are-not-more-important-than-animal-lives/

I believe that this is very important as Microsoft values the lives of individuals, see [this issue](https://www.github.com/microsoft/vscode/issues/87268) for reference

**Comment by IllusionMH** [comment]
Fixed in Insiders https://github.com/microsoft/vscode/issues/85395#issuecomment-565404809 😆

**Comment by BLUEBOUNCE** [comment]
> 
> 
> Fixed in Insiders [#85395 (comment)](https://github.com/microsoft/vscode/issues/85395#issuecomment-565404809) 😆

Awesome! Hope I'll see it in the stable mainstream soon!
