### ISSUE TITLE
Restore existing multi-root workspaces when opening N folders from the command line

### ISSUE THREAD

**Issue by jankrassnigg** [microsoft/vscode#87290]
Issue Type: <b>Bug</b>

I am programmatically opening VSC with multiple roots like this:
code.exe "C:\...\Folder1" "C:\...\Folder2" "C:\...\Folder1\SomeFile.txt"

This will open VSC with a multi-root workspace. So far so good.

The annoying thing happens when
1) running the same cmd line again while VSC is open
2) closing VSC and running the same command line again

In scenario 1) I would expect VSC to just appear in the foreground and make sure "SomeFile.txt" is selected. Same if I used a slight variation of the command line to open a different file (but still using the same folders).
However, instead it just launches as a second instance of VSC with the exact same configuration, so typically the user now needs to close one of them.

In scenario 2) I would expect VSC to open once. What happens though, is that it actually opens TWICE ! As far as I can tell, what happens is that VSC launches and sees that last time it was open with this multi-root configuration, so it restores that configuration. It then additionally follows the command line instructions and thus opens a second instance with that multi-root setup, which happens to be the exact same.

The results of scenario 2) are particularly annoying. The only way to prevent this ONCE is to manually select "Close Workspace" before closing VSC. But the user would need to do that every single time and there is no way programmatically to prevent this behavior (afaik).

I tried adding "--new-window" and "--reuse-window", but both have unintended effects. "-n" just always opens a new window, which is not what I want, and "-r" just always reuses the existing window, which is also not what I want.

Generally, I want VSC to use the given folders to detect whether the exact same multi-root configuration is already open atm and then either reuse a window or launch a new one, if needed. Once that is decided, the files given via the command line should get opened.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
Yes, what is missing here is knowing that those folders are already opened inside a window and then using that window instead of opening another window. I am open for PRs in this area to improve this.

**Comment by epfeiffe** [comment]
I am able to work on both Scenario 1 and Scenario 2. @bpasero do you mind if I start and submit a pull request when I'm done?

**Comment by epfeiffe** [comment]
I am working on this bug fix now. I'll try to have a pull request up for it in about a week or so!

**Comment by epfeiffe** [comment]
I am a little stuck working on this task, can someone point me in the right direction as to where specifically in the project the terminal arguments are being converted to their respective workspaces? I have been looking through `src/main.js` and `src/vs/code/electron-main/main.ts` and am aware that the arguments are being retrieved from `process.argv` and stored as the `args` variable in `src/vs/code/electron-main/main.ts`, but am unsure how they are being set as a workspace. Any hints or pointers would be great, thanks!

**Comment by epfeiffe** [comment]
Just submitted a pull request that is ready for review: #111845
