### ISSUE TITLE
VS Code Doesn't Respect High Contrast Color Customizations (Windows)

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/vscode#87298]
Issue Type: <b>Bug</b>

In Windows, color customizations for high contrast mode at the OS level are possible. Many apps (including Teams) appear to respect these custom colors, but VS Code does not. Here's an example from the Ease of Access high contrast settings dialog:

![image](https://user-images.githubusercontent.com/40371649/71133804-c0278e80-21b0-11ea-97ec-c18c746f3c1c.png)

In this example, hyperlinks are set to show up in yellow.

When opening VS Code, the welcome page still shows links as blue:

![image](https://user-images.githubusercontent.com/40371649/71133885-0b41a180-21b1-11ea-82bf-b06e2a422901.png)

This appears to be the case throughout the app.

VS Code version: Code - Insiders 1.42.0-insider (26f5dfcd76c9a02f116a706844611aeb09ae8c0b, 2019-12-18T10:34:34.277Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (46.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by dbaeumer** [comment]
@isidorn assigning to you. Not sure if you are the right owner.

**Comment by isidorn** [comment]
Assigning for now to @misolori 
Also fyi @aeschli

**Comment by misolori** [comment]
@chlafreniere are you saying that setting custom colors is not respected or that the links don't match the HC colors? 

@isidorn @aeschli I don't believe we support setting custom OS colors for High Contrast, is this correct?

**Comment by aeschli** [comment]
No, we don't have any synchronization between the Windows colors and our own custom colors.
But all these colors (and many more) can be configured in our user settings. 

For accessibility we also provide a high contrast theme that is switched to automatically when Windows goes in high contrast mode.

**Comment by misolori** [comment]
Closing as @aeschli mentions that we don't support OS customizations.
