### ISSUE TITLE
[powershell] Line comment block not recognized in PowerShell when in attribute definition scope

### ISSUE THREAD

**Issue by dreadris** [Microsoft/vscode#8730]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:
1. Create a powershell script file (ie. test.ps1)
2. Open the script in vs code
3. Paste the following:
   `param(
   [ValidateScript(
       { if (Test-Path $_) { $True } else { Throw "Path:`"$_`" does not exist" } }
   )] 
   [string]$rootPath = "./"
   )`
4. Insert the # sign after ValidateScript( - the text style won't be changed to indicate the commented block.

**Comment by aeschli** [comment]
This issue was moved to PowerShell/EditorSyntax#64
