### ISSUE TITLE
There is no way to disable Compact Folders for source control

### ISSUE THREAD

**Issue by MansurAliKoroglu** [microsoft/vscode#87307]
I can disable it for explorer but not for source control.

![image](https://user-images.githubusercontent.com/43291306/71140129-63b08780-2221-11ea-9a04-5033a6edc9d8.png)

**Comment by IllusionMH** [comment]
To be fair this one is not related to that setting and existed in 1.40.2 - before introduction of Compact Folders feature to Explorer.

![image](https://user-images.githubusercontent.com/1312662/71168095-a9d80c00-225e-11ea-9a99-2f724d8f3f2f.png)

/cc @isidorn

**Comment by MansurAliKoroglu** [comment]
So, isn't it still a feature request?

**Comment by IllusionMH** [comment]
I've never said that this is not valid request.
Only that these 2 are not directly related and it's not new behavior.

**Comment by joaomoreno** [comment]
The compact feature has different purposes in SCM and the Explorer. There is no reason not to use compact folders in SCM, when showing the changes as a tree: there is no added value to having all those folders listed each in a separate row.
