### ISSUE TITLE
我的js的智能提示不能用

### ISSUE THREAD

**Issue by TaoTao2deng** [microsoft/vscode#87302]
Issue Type: <b>Bug</b>

就是js文件的智能提示不能用。重新安装也是不行。上次更新后出现的问题

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.6
vscode-language-pack-zh-hans|MS-|1.41.2
vetur|oct|0.22.6
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by 0x0ffff** [comment]
如果是在项目文件夹里，可以删除 `node_modules` 文件夹之后在重新安装依赖即可。

**Comment by sebleblanc** [comment]
@TaoTao2deng 
> Is the js file smart tips can not be used. Reinstall is also not possible. Problems after last update.

@0x0ffff 
If you are in the project folder, you can delete the node_modules folder and reinstall the dependency.

This automated translation brought to you by sleblanc-translate-bot!
