### ISSUE TITLE
Implement a splash screen

### ISSUE THREAD

**Issue by natrist** [microsoft/vscode#87309]
The application should display a splash screen like Visual Studio does on Windows 10.

**Comment by natrist** [comment]
https://imgur.com/a/4cyRKpX

**Comment by ajayyy** [comment]
No need for a splash screen when it loads fast.

**Comment by warpdesign** [comment]
I'm not sure a splash screen is needed but I think the about window should get some love and maybe this could be used for that?

**Comment by natrist** [comment]
> No need for a splash screen when it loads fast.

On my end it takes around 6 seconds to load _everything_ and I have a decent computer and SSD.
It's just a suggestion but I'd rather look at a pretty splash screen than have the VS Code window load up and have to wait for the code view, extensions and other things to fully load up before I can even start using the program.
