### ISSUE TITLE
Removal of Santa Hat

### ISSUE THREAD

**Issue by plasticuproject** [microsoft/vscode#87308]
Shame on you for removing the festive hat. It's a hat, it doesn't represent any of that garbage the requester said. I'd argue that the hat represents keeping your head warm in cold weather. The hat is equally as unoffensive as the cog that it was set upon. You all shouldn't just add or remove a feature just because one person, out of tens of thousands, claims to be unreasonably offended. You should have done due diligence and researched on your own to see if it was a valid criticism.

**Comment by egamma** [comment]
Duplicate #87291
