### ISSUE TITLE
Auto Importing stopped working with November's update

### ISSUE THREAD

**Issue by BenRacicot** [microsoft/vscode#87304]
- VSCode Version:
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
-----
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

- OS Version: MacOS Catalina 10.15.2 (19C57)

Steps to Reproduce:
1. Using TypeScript, enter the name of any type or class name you wish to import.
or 
2. backspace on a classname to remove the last letter
No options are shown as in previous VSC versions

Version: 1.42.0-insider
Commit: 26f5dfcd76c9a02f116a706844611aeb09ae8c0b
Date: 2019-12-18T10:32:01.697Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

The Insiders version above behaves as expected.

**Comment by AndreyWV** [comment]
I'm not shure, but I have both this and [this](https://github.com/microsoft/vscode/issues/87325) issues at same time, and guess they are related.

**Comment by mjbvz** [comment]
Closing this since it sounds like it is fixed in the insiders build.

Please also make sure to check your installed extensions to make sure one of them is not causing this
