### ISSUE TITLE
"Error" - resolving Prettier configuration

### ISSUE THREAD

**Issue by vorousjames** [microsoft/vscode#87312]
All of a sudden prettier formatting extension doesn't work. output is screens hotted below:
<img width="1010" alt="Screen Shot 2019-12-18 at 11 14 19 PM" src="https://user-images.githubusercontent.com/26244526/71144482-2978c300-21ec-11ea-8475-6284331950ae.png">

**Comment by dbaeumer** [comment]
@vorousjames please report the issue against the prettier extension.
