### ISSUE TITLE
Removal of the Santa Hat and kowtowing to SJWs

### ISSUE THREAD

**Issue by JohnMH** [microsoft/vscode#87314]
The removal of the santa hat, and kowtowing to a single SJW, is incredibly offensive to me. Please rectify this as soon as possible.

**Comment by tweakimp** [comment]
Without a hat the settings icon may get cold

**Comment by egamma** [comment]
duplicate of #87291

**Comment by egamma** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
