### ISSUE TITLE
IMHO Display Language is too thin to get its own page under Customization

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8732]
https://code.visualstudio.com/docs/customization/locales

Maybe it could be put under setup? (as it sounds like something I'd do once and never touch again)

**Comment by gregvanl** [comment]
The page gets very high sentiment (>90%) and visibility in the TOC is important for non-English speakers.  It is true that a user will likely only do this once, but discoverability in the docs is key for that one time.

**Comment by alexandrudima** [comment]
:+1:
