### ISSUE TITLE
New debug/run experience doesn't go away after creating launch.config

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#87324]
Related to #87237 (I'm testing in Insiders with the fix for that issue).

- Create two empty folders, `one` and `two`
- Open both folders as a multi-root workspace
- On the Debug side bar, click the "Create a launch.json file"
- Select the *second* workspace folder
- Select node.js (or any other) debug type

The launch.json is created in the second folder, however the debug side bar doesn't update, it remains with the "new experience" (and therefore doesn't allow you to run using the launch config you just created).

cc @isidorn

**Comment by isidorn** [comment]
@DanTup thanks for filling this and for providing steps. You can try it out in vscode insiders tomorrow and let me know if it is good now. Thanks a lot!

**Comment by DanTup** [comment]
Fix all works fine for me, thanks!

**Comment by isidorn** [comment]
Thanks a lot for letting us know, adding verified label.
