### ISSUE TITLE
Removal of the Santa hat and kowtowing to a single fake user is offensive to me

### ISSUE THREAD

**Issue by JohnMH** [microsoft/vscode#87328]
The removal of the santa hat, and kowtowing to a fake user, is incredibly offensive to me. Please reinstate the santa hat icon.

**Comment by MaurogDark** [comment]
...Dissenter detected
...Stifling discussion
...Summoning egamma
...Issue closed in 3... 2... 1...

**Comment by egamma** [comment]
Duplicate of #87291 pls see https://github.com/microsoft/vscode/issues/87291#issuecomment-567383802.

**Comment by egamma** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
