### ISSUE TITLE
Snow Flake on vscode insiders and pushing death is very offensive to me

### ISSUE THREAD

**Issue by Kaseaa** [microsoft/vscode#87327]
The Snow Flake on vscode insiders and pushing it as a "cozy"/"wintery" thing is very offensive to me. I come from Norway and people who glorify snow is equivalent to the people who glorified hitler during WW2. The amount of deaths caused by winter is massive, not to mention the depression the season brings and you want to bring that into my work space as well? This is unacceptable, everytime I leave my house I see snow and I want to escape into Visual Studio Code and get some work done and what do I see? More snow... To me this is equally offensive as a swastika.

This isn't just me either, think about the people who cannot even get snow, think about how you're making them feel, making them see what they cannot get, although personally I don't understand that. Snow is terrifying.

Version: 1.42.0-insider (user setup)
Commit: 26f5dfc
Date: 2019-12-19T05:31:04.916Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Install latest build of insiders.

Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered.
[https://thoughtcatalog.com/jim-goad/2015/12/death-by-snow-14-ways-that-winter-weather-can-kill-you/](https://thoughtcatalog.com/jim-goad/2015/12/death-by-snow-14-ways-that-winter-weather-can-kill-you/)
[https://www.nrdc.org/stories/global-warming-101](https://www.nrdc.org/stories/global-warming-101)
[https://www.recoveryranch.com/addiction-blog/snow-depression/](https://www.recoveryranch.com/addiction-blog/snow-depression/)

**Comment by bhack** [comment]
This is really offending for people that are suffering for global warming and desertfication areas. 
Also It Is that a natural snow icon or a fake snow icon.
Please think about how much water Is wasted to create artificial snow just for games:
https://news.bloombergenvironment.com/environment-and-energy/fake-snow-for-china-olympics-needs-49-million-gallons-of-water

**Comment by SamuelTilly** [comment]
This is also highly offensive to everyone who has ever been called a snowflake or identifies as a snowflake.

Please remove.

https://en.wikipedia.org/wiki/Snowflake_(slang)

**Comment by braindigitalis** [comment]
Perhaps this is not the correct platform for trolling?

**Comment by SaltyMonkey** [comment]
No? Perhaps it same level "trolling" as https://github.com/microsoft/vscode/issues/87268 ?
```Racism is the belief in the superiority of one race over another.[1][2][3] It may also mean prejudice, discrimination, or antagonism directed against other people because they are of a different race or ethnicity.[1][2] Modern variants of racism are often based in social perceptions of biological differences between peoples. These views can take the form of social actions, practices or beliefs, or political systems in which different races are ranked as inherently superior or inferior to each other, based on presumed shared inheritable traits, abilities, or qualities.```
So removed santa hat is racism. Just because its offended for one person, microsoft prejudice, discrimination, or antagonism directed against other peoples

**Comment by navartis** [comment]
ДБ?

**Comment by bhack** [comment]
@braindigitalis It Is not trolling Is that when MS apply too extreme "politically correct" reactions it Is healty if the community react with a little bit of satire.

**Comment by SaltyMonkey** [comment]
Also, seems, censoring everything just keep self "clean"

**Comment by bhack** [comment]
We could make the snowflake toggable https://github.com/microsoft/vscode/issues/87333 :smile:

**Comment by MaurogDark** [comment]
If it was possible to just turn the slowflakes off, this whole debacle wouldn't happen :thinking:

**Comment by shakeyourbunny** [comment]
It is really offending me because I am very snow sensitive and get hurt by snowflakes when it is snowing.

If I see that on the VS code I feel physically hurt.

So remove it immediately like you did the other thing.

**Comment by tomstolarczuk** [comment]
Not to say that many Jews died when it was snowing outside.

**Comment by ChronoTempus** [comment]
On the other hand snowflake is the best symbol for spineless corporations bowing down to any random activist complain.

**Comment by bhack** [comment]
Also there was some recent effort to associate snowflake and Santa with its red hat to drug consumption so please don't talk about Its red hat and snow simbolol in the same thread. 
https://www.vice.com/en_us/article/jgee9k/amazon-is-still-selling-festive-christmas-sweaters-showing-santa-doing-cocaine

**Comment by MaKiPL** [comment]
I am with you guys- the one troll that offended many, many people got his wish filled. Only ONE person wanted this ridiculous change and you are just ignoring so many requests to bring back what was deleted. Shame on you, shame.

**Comment by daniel1302** [comment]
If you do not like VSCode, do not use it. The simpliest solution!

**Comment by PierreRambaud** [comment]
@daniel1302 Please stop offended me! You're not my dad, I can use everything I like / dislike!

**Comment by daniel1302** [comment]
@PierreRambaud I am happy you are not my child. You are the worst child I have seen :)

**Comment by MaKiPL** [comment]
@daniel1302 Please stop offending other users. @Christian-Schiffer created enough havoc already.

**Comment by ludo237** [comment]
@daniel1302 ok boomer

**Comment by shakeyourbunny** [comment]
So, interesting to see that this issue is actively watched but the only thing what happens, is that two posts were deleted instead of instapromptu removing the hurtful snowflake from the application, like the other thing.

I'd be really  grateful if that the correct reaction will be delivered like the other one, snowflakes do hurt and sting in the eyes, I won't be able to sleep if I see all day this hurtful symbol of pain in my IDE.

**Comment by SimonGrn** [comment]
Some guy in Microsoft HQ is sweating right now.

Although this is 100% deserved.

**Comment by matthieu-rolland** [comment]
His name is **Christian**, that must be a troll account, too good to be true :D

**Comment by shakeyourbunny** [comment]
If you need further reference why snowflakes remind me of cold, pain and hurt see:
https://www.aao.org/eye-health/diseases/photokeratitis-snow-blindness
https://www.webmd.com/a-to-z-guides/news/20110120/snow-shoveling-injures-thousands-each-year#1

**Comment by ioquatix** [comment]
I'm from New Zealand, and in the Southern Hemisphere, it's not cold, but hot during the holiday season. I suggest you geo-locate the user's position and prompt them for the icon of their choice, e.g. snow, ice, fire, sun shine.

**Comment by pgawlowski** [comment]
BTW. To original author of this shitstorm - Christian-Schiffer. W wonder is his name not offending him? 
https://en.m.wikipedia.org/wiki/Christian_(given_name)
Maybe he should change it...

**Comment by cy6erGn0m** [comment]
Every Christian should be renamed immediately to eliminate possible offence. The name should be strictly prohibited for future use.

**Comment by cristaloleg** [comment]
https://en.wikipedia.org/wiki/Snowflake_(slang)

**Comment by Kaseaa** [comment]
Can you people stick on topic? This is a serious discussion about the terror that is snow flakes and how it terrorises a lot of people everyday, even more now with the new VS Code update.

**Comment by Yobilat** [comment]
I would also like to point out that snow(flake) is _white_ and is commonly used as a white supremacy symbol to oppress whole ethnicities which due to systemic geographic discrimination couldn't historically experience first-hand full range of weather phenomena.

**Comment by ivanpopelyshev** [comment]
Winter is one good buff against invaders in Russia. Praise the winter! Let it snow!

Also I think climate calculations are wrong and new ice age is nearby. There will be more snow. Thank you global warming fighters, for helping to make even more snow!

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
