### ISSUE TITLE
intellisense not work

### ISSUE THREAD

**Issue by GreedyWhale** [microsoft/vscode#87325]
### solved

Install JavaScript and TypeScript Nightly and restart vscode

[JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

- ### Intellisense fails when node_modules folder is included

![image](https://user-images.githubusercontent.com/22760464/71159489-afdee480-2280-11ea-9c24-aaf490ad590c.png)

- ### Intellisense works fine after deleting the node_modules folder

![image](https://user-images.githubusercontent.com/22760464/71159402-88881780-2280-11ea-81a3-dfd38f83dbd9.png)

- ### version

![image](https://user-images.githubusercontent.com/22760464/71159524-c08f5a80-2280-11ea-8456-1927e847b808.png)

> Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

- ###  Disable all extensions and include node_modules

![image](https://user-images.githubusercontent.com/22760464/71224679-0e53a380-2311-11ea-8d4f-a8a51d613632.png)

- ### Disable all extensions and no node_modules

![image](https://user-images.githubusercontent.com/22760464/71224739-3e9b4200-2311-11ea-963f-a78d6b64048b.png)

- ### Enable all extensions and no node_modules

![image](https://user-images.githubusercontent.com/22760464/71224798-67233c00-2311-11ea-993c-38ec71d44841.png)

- ### package.json file

```json
{
  "name": "demo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "cross-env NODE_ENV=production webpack --config ./build/webpack.prod.js --progress",
    "build:dev": "cross-env NODE_ENV=development webpack --config ./build/webpack.prod.js --progress",
    "dev": "cross-env NODE_ENV=development webpack-dev-server --config ./build/webpack.dev.js"
  },
  "sideEffects": [
    "*.scss",
    "./src/**/*.js"
  ],
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "core-js": "3"
  },
  "devDependencies": {
    "@babel/cli": "^7.7.5",
    "@babel/core": "^7.7.5",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/preset-env": "^7.7.6",
    "autoprefixer": "^9.7.3",
    "babel-loader": "^8.0.6",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^5.1.0",
    "cross-env": "^6.0.3",
    "css-loader": "^3.2.1",
    "eslint": "^6.7.2",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "file-loader": "^5.0.2",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.8.0",
    "postcss-loader": "^3.0.0",
    "pug": "^2.0.4",
    "pug-loader": "^2.4.0",
    "sass": "^1.23.7",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.0.1",
    "url-loader": "^3.0.0",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.9.0",
    "webpack-merge": "^4.2.2"
  }
}

```

**Comment by AndreyWV** [comment]
I'm not shure, but I have both this and [this](https://github.com/microsoft/vscode/issues/87304) issues at same time, and guess they are related.

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by GreedyWhale** [comment]
solved
Install JavaScript and TypeScript Nightly and restart vscode

JavaScript and TypeScript Nightly
