### ISSUE TITLE
Holiday Festivities

### ISSUE THREAD

**Issue by Jackarunda** [microsoft/vscode#87339]
Issue Type: <b>Bug</b>

I saw a red clothing item earlier in the bottom left corner of the window. It reminded me of when my parents were still alive, and brought me such indescribeable joy to see it while coding. When I updated my VSCode, it was gone. I have to assume this was a bug. Where did it go? The last thread I made on this topic was locked by accident. I posted it on my tumblr and sent it to several news outlets but it was locked, and so unusable, so I made a new one to hopefully get some resolution to this issue. This time I'll be taking screenshots to ensure that the Github Issue record doesn't become unuseable.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 1300X Quad-Core Processor           (4 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.9

</details>

**Comment by Danielx64** [comment]
It was removed all because of this one guy: https://github.com/microsoft/vscode/issues/87268 and he prob think that what he did is funny.

**Comment by PierreRambaud** [comment]
Same, I lost all my family in a car accident. Santa hat reminds me old good memories :sob: :sob: :sob:

**Comment by Piorys** [comment]
I was able to reproduce the issue on my side as well

**Comment by galimba** [comment]
I was attempting to reproduce the issue. Got as far as to feel the joy of my parents being alive, but then a snowflake got in the way and I got offended.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
