### ISSUE TITLE
option for disable autopening of output panel

### ISSUE THREAD

**Issue by alex-left** [microsoft/vscode#87331]
I have an extension that throws errors, but works fine. The errors open automatically the output panel and this is very annoying and useless. I don't uninstall the extension and I would like an option to disable this behaviour, but seems that don't exist. I did not find it and anyone answer to me in stackoverflow:
https://stackoverflow.com/questions/59395981/disable-output-panel-with-errors

By other side I will apreciate a lot some kind of workaround.

**Comment by isidorn** [comment]
Please file this issue against the extension, the extension should not open the output panel aggressivly
