### ISSUE TITLE
Santa Claus hat as an option in VS Code settings

### ISSUE THREAD

**Issue by PrzemyslawPolrolniczak** [microsoft/vscode#87333]
Hey,

maybe instead of removing Santa Claus hat because 1 SJW, can you make an option to turn it on and off in options? Really, why you have to remove it?

**Comment by MaurogDark** [comment]
That's way too rational, a guy was extremely offended, please have some consideration!

We must remove the hat, all mentions of the hat, all mentions of removing the mentions of the hat and so on, just to be sure. Oh no, I just mentioned way too many forbidden things, so this is getting removed too. Along with this thread. And me. And you.

**Comment by Vallek** [comment]
The removing of the Santa hat and catering to vocal minority of sjw idiots is very offensive to me. Please stop.

**Comment by Tyldar** [comment]
Who is going to submit the PR?

**Comment by doyle-mark** [comment]
Why was that guy even pandered to in the first place? The story of Santa Claus is not directly tied to any religion in particular. While yes, it's stems from Christianity, nowadays it's completely secular.. If Santa is a religious figure, then so is the Grinch,

It's so sad that people are so sensitive in the world we live in today that this sort of thing is even worth discussion..

**Comment by laurentb** [comment]
> While yes, it's stems from Christianity, nowadays it's completely secular.. 

My understanding is that he was actually upset of the pagan origins :man_shrugging:

**Comment by nkkollaw** [comment]
🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
