### ISSUE TITLE
关于HTML mirror cursor功能

### ISSUE THREAD

**Issue by orange-tree** [microsoft/vscode#87336]
这个功能对我来说就是个灾难，有f2的标签命名功能就足够了，这个增加了我配置首选项的成本，不知道有多少人喜欢这个功能。

**Comment by IllusionMH** [comment]
Please report issues in English.

Guessing from only English part in title - you can disable this with `"html.mirrorCursorOnMatchingTag": false`
More details in update post: [HTML mirror cursor](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor)

**Comment by octref** [comment]
As mentioned by @IllusionMH's, you can disable it with the setting. If we disable it, others are going to complain they have to set a config to enable it.
