### ISSUE TITLE
'Set-Clipboard' PowerShell command doesn't work in VS Code terminal

### ISSUE THREAD

**Issue by ArturGudiev** [microsoft/vscode#87338]
Issue Type: <b>Bug</b>

I can't use 'Set-Clipboard'  command in VS Code Powershell terminal. 
Although it works fine in a standard powershell console. 

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|31%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.3
vsc-prolog|art|0.8.23
toggle-semicolon|awe|0.0.1
scratchpads|bue|0.0.7
swap-word|dav|0.1.2
vscode-eslint|dba|2.0.6
javascript-ejs-support|Dig|1.1.3
vscode-nm|dpa|0.2.0
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
vscode-firefox-debug|fir|2.6.1
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.32
latex-workshop|Jam|8.5.0
plantuml|jeb|2.13.5
angular-essentials|joh|0.6.3
Angular2|joh|8.3.0
vscode-peacock|joh|3.2.0
language-haskell|jus|2.6.0
intellij-idea-keybindings|k--|0.2.37
cql|Law|0.8.7
csharpfixformat|Leo|0.0.84
Kotlin|mat|1.7.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
angular2-inline|nat|0.0.17
angular-console|nrw|10.0.0
material-icon-theme|PKi|3.9.2
java|red|0.54.2
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.3
vscode-autohotkey|sle|0.2.2
vscode-mindmap|Sou|0.0.5
rewrap|stk|1.9.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
t4-support|zbe|0.4.3

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
FYI @TylerLeonhardt, closing since I don't think we can influence anything about this in VS Code.
