### ISSUE TITLE
Please don't remove the dark theme, because it will make it harder to read large block of code.

### ISSUE THREAD

**Issue by Danielx64** [microsoft/vscode#87344]
The title pretty much says what needed to be said. Having a white background with different coloured text can make thing extremely hard to read and can do more harm to your eyes than having a black (or dark grey) background with different coloured text makes it far easier to read.

**Comment by dbaeumer** [comment]
@Danielx64 can you please explain what exactly you are concerned about. We don't have any plans to remove the dark theme.

**Comment by Danielx64** [comment]
> 
> 
> @Danielx64 can you please explain what exactly you are concerned about. We don't have any plans to remove the dark theme.

There's this issue (https://github.com/microsoft/vscode/issues/87341 ) asking for dark theme to be removed.

**Comment by Glamhoth** [comment]
Is this even one more layer of trolling?

**Comment by Danielx64** [comment]
> 
> 
> Is this even one more layer of trolling?

This issue, no, it was a big concern till @dbaeumer stated that they have no plans to remove the dark theme.

**Comment by jedenastka** [comment]
r/woooosh

**Comment by chrisdias** [comment]
We are not removing the dark theme, sorry for the confusion.
