### ISSUE TITLE
Stop the censorship

### ISSUE THREAD

**Issue by Mikotochan** [microsoft/vscode#87348]
Please restore the comments in https://github.com/microsoft/vscode/issues/87268 and unlock https://github.com/microsoft/vscode/issues/87291.

I enjoy reading drama, please don't take my only pleasure in life away.

**Comment by Hamdullah-gif** [comment]
This censorship is literally a new holocaust!

**Comment by jablpiotrek** [comment]
I'm extremely offended by the fact that because of religious beliefs @Mikotochan 's only life pleasure has been taken away.

**Comment by matks** [comment]
> This censorship is literally a new holocaust!

You deserve an award for skyrocketting the level of drama of this topic 👏 🍾 🎖 !

**Comment by PierreRambaud** [comment]
Could we remove the bug logo
![image](https://user-images.githubusercontent.com/1462701/71169433-2c5dcd00-2259-11ea-9a1d-64b90ce7930a.png)
, it's against the insects life :thinking:

**Comment by ttoine** [comment]
```
 /  __) (____) (____) (____) (____) (____) (__  \ 
 |_|                                          |_| 
  _      _                    _       _        _ 
 | |    / |       _ __   ___ (_)_ __ | |_     | | 
 | |    | |      | '_ \ / _ \| | '_ \| __|    | | 
 |_|    | |      | |_) | (_) | | | | | |_     |_| 
  _     |_|      | .__/ \___/|_|_| |_|\__|     _ 
 | |             |_|                          | | 
 | |                                          | | 
 |_|     ____           _          _          |_| 
  _     / ___| ___   __| |_      _(_)_ __      _ 
 | |   | |  _ / _ \ / _` \ \ /\ / / | '_ \    | | 
 | |   | |_| | (_) | (_| |\ V  V /| | | | |   | | 
 |_|    \____|\___/ \__,_| \_/\_/ |_|_| |_|   |_| 
  _                                            _ 
 | |__   ____   ____   ____   ____   ____   __| | 
 \____) (____) (____) (____) (____) (____) (____/
```

**Comment by Phillipus** [comment]
Good grief. Poor old Santa! BTW - solstice is a pagan festival and Santa was a shaman.

**Comment by s9w** [comment]
How to ruin your stellar reputation in one easy step.

**Comment by Tyldar** [comment]
So who is going to push a Pull-Request reintroducing the Santa Hat (maybe with an option to turn it on/off for SJW)?

**Comment by Phillipus** [comment]
No pressies for @Christian-Schiffer this year,. He's been a very naughty boy!

**Comment by normano** [comment]
@egamma Could stop this discussions if a more balanced approach was taken such as including configuration to enable disable these decorations. Can't imagine any controversy from that therefore these outbursts that take time away from other issues.

**Comment by TheRishabhB** [comment]
We should stop using git as version control for vscode too.  One time a random person told me to “git good” and since then, “git” is extremely offensive to me.

**Comment by TimWelter** [comment]
Please remove Python compatibility I'm scared of snakes.

**Comment by Roguezilla** [comment]
> @egamma Could stop this discussions if a more balanced approach was taken such as including configuration to enable disable these decorations. Can't imagine any controversy from that therefore these outbursts that take time away from other issues.

Won't happen, the the people who code vscode are too scared to go against someone's beliefs. They removed a god damn hat for fucks sake, a hat that's related to a holiday that isn't celebrated for its religious symbolism anymore, the latter was issue for the amazing mastermind who made #87268. This is why we can't have nice things.

**Comment by pmosko** [comment]
It's funny and sad at the same time that one selfish issue can cause loss of hundrets of man-days (people-days?) across globe.

**Comment by Phillipus** [comment]
> It's funny and sad at the same time that one selfish issue can cause loss of hundrets of man-days (people-days?) across globe.

Sadder still is the amount of lives lost in the name of "religion".

**Comment by Sunscratch** [comment]
Merry Christmas and Happy New Year! 🎅 
You can ban me now, `for pushing of religion`

**Comment by pmosko** [comment]
> Sadder still is the amount of lives lost in the name of "religion".

I am not sure why you used quotes, but yes, lives lost or opressed at any occasion are depressing thing.

**Comment by kpucynski** [comment]
:popcorn:

**Comment by nitnelave** [comment]
`git push --religion`

**Comment by bhack** [comment]
https://www.theregister.co.uk/2007/12/04/microsoft_kills_santa/

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
