### ISSUE TITLE
Default settings.json don't match schema

### ISSUE THREAD

**Issue by Samonia** [microsoft/vscode#87343]
- VSCode Version: version 1.41
- OS Version:  Microsoft Windows 10 Enterprise 10.0.17763 Build 17763

Steps to Reproduce:
1. Copy default settings.json from  https://code.visualstudio.com/docs/getstarted/settings#_default-settings
2. Remove comments. Filter: /^\s+(//.*)$/

Does this issue occur when all extensions are disabled?: Yes

Following settings don’t correspond to the settings schema inside of vscode.

![image](https://user-images.githubusercontent.com/35612451/71166100-4e078600-2252-11ea-9f48-715041bc844e.png)

![image](https://user-images.githubusercontent.com/35612451/71166148-611a5600-2252-11ea-8491-774256c2543b.png)

![image](https://user-images.githubusercontent.com/35612451/71166181-73948f80-2252-11ea-97f7-430dde303d4e.png)

**Comment by dbaeumer** [comment]
@alexdima do you know how we generate the default settings file?

**Comment by Samonia** [comment]
Background:
Our issue were that personal user-settings in vscode were overwriting default workspace settings. This cause problems in the build pipeline.

@alexdima have tried to Google how to generate default settings. Found nothing.

**Comment by dbaeumer** [comment]
Not sure who owns this. Starting with @roblourens as the settings person.

**Comment by roblourens** [comment]
The problem here is with the default settings blob on the docs page. I suspect that this is manually copied onto the webpage by @gregvanl or @octref and probably just needs to be updated, is that the case?

**Comment by gregvanl** [comment]
editor.matchBrackets did change from a Boolean to an enum late in the 1.41 release and settings.md was out of date. Updated with https://github.com/microsoft/vscode-docs/commit/f72caff30fb1ab2f8fc29e282200b9ecd1a04b0b.
The two path properties put default values (null) which conflict with the defined schema of string. The Emmet and Git extension package.json should be updated to use an array with types string and null similar to git.path:

```json
        "git.path": {
          "type": [
            "string",
            "null"
          ],
          "default": null,
        },
 ```

**Comment by roblourens** [comment]
Those are old settings, funny nobody has noticed that the defaults are not valid types. I'll fix them.
