### ISSUE TITLE
shift + alt + left mouse button

### ISSUE THREAD

**Issue by Ccback** [microsoft/vscode#87340]
Issue Type: <b>Bug</b>

It does not work when you select the end of a multiline

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
rainbow-csv|mec|1.3.1
vscode-docker|ms-|0.9.0
vscode-language-pack-zh-hans|MS-|1.41.2
mssql|ms-|1.8.0
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.22.6
java|red|0.54.2
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1

</details>

**Comment by alexdima** [comment]
@Ccback Can you please explain in greater detail what you mean. I am trying to reproduce here and everything looks ok:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/72503990-3e716200-383d-11ea-82f4-baabe76090c0.gif)
