### ISSUE TITLE
Please remove the black theme, because it's offensive to me

### ISSUE THREAD

**Issue by Humberd** [microsoft/vscode#87341]
When I was young our village was invaded and robbed at night and since then I am afraid of going out anywhere when it's getting darker. VS Code dark theme reminds me of this situation, so please remove it immediately, because for me dark theme = death.

**Comment by shakeyourbunny** [comment]
In addition, it reminds me of black people lurking around.

Microsoft scares me by forcing people to use this theme.

**Comment by Humberd** [comment]
Please don't laugh. This is a serious issue for me. I want to force removal of the feature, because it hurts my feelings. And no, don't make a toggle for it. It would remind me that a death is still there, but not visible.

**Comment by Danielx64** [comment]
WTF are you thinking? Having a dark theme makes it ready to read code. No joke bro. If you don't like it, go and use something else troll

**Comment by Humberd** [comment]
Don't you understand? It makes me feel anxious all the time. If you don't do it I'll feel sad and disappointed.

**Comment by Humberd** [comment]
I don't know if it makes any difference, but I'm a black Jew living in Uganda.

**Comment by Danielx64** [comment]
> 
> 
> I don't know if it makes any difference, but I'm a black Jew living in Uganda.

To me? No, it doesn't.

**Comment by Shusek** [comment]
I'm sorry they hurt your and other's feelings. I hope they'll remote the dark theme soon.

**Comment by ludo237** [comment]
It's okay to use white theme

**Comment by Kegelcizer** [comment]
To avoid being offended, please use the transparent theme.

**Comment by hckr** [comment]
@Kegelcizer Did you just say trans-parent? But it's ok, my conservative belifs can and even should be offended.

**Comment by Kegelcizer** [comment]
> @Kegelcizer Did you just say trans-parent? But it's ok, my conservative belifs can and even should be offended.

I'm deeply sorry for my insensitivity. I hope the edit of my original comment will make it more PC.

**Comment by wattengard** [comment]
PC?! What if I'm a mac-user?!

**Comment by anterokarttunen** [comment]
LOL ( troll )

**Comment by pokonski** [comment]
Dark theme is basically a blackface of white editors.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
