### ISSUE TITLE
Find a way to fit panel headers into the smaller minimum width

### ISSUE THREAD

**Issue by Kroc** [microsoft/vscode#87347]
Now that the integrated terminal panel cannot be sized smaller than its toolbar (a good thing because the kill button was being shoved off screen), it is however uncomfortably wide on a screen-resolution of 1366x768. With a document of 80-chars wide, the side-bar is far too narrow :(

![image](https://user-images.githubusercontent.com/142650/71168072-dd5e6a80-224d-11ea-9d03-70d7f448f4d0.png)

Please allow the integrated terminal's toolbar to compact more at its smallest size.

**Comment by Kroc** [comment]
I should add that I fully agree with having a non-negotiable minimum width of the terminal, I would just like some kind of minification strategy for the toolbar beyond a certain size; overflow buttons, reduced button padding, removing the "terminal" title -- I leave that choice up to the VSCode designers.

**Comment by Tyriar** [comment]
This is the minimum size for the panel, not just the terminal. Moving to @isidorn

**Comment by isidorn** [comment]
This is a fair feature request.
However forwarding to @sbatten since he is looking into the view layouting currently.
Not sure if we would just decrease the default minimum or we would make it configurable (which I would personally try to avoid)

**Comment by sbatten** [comment]
Like @Kroc stated, this minimum width prevents it panel header bar from rendering improperly so I believe the right fix is to figure out a way for the header to become smaller.

/cc @misolori for ideas

**Comment by misolori** [comment]
One thing we can experiment with is to make the toolbars overflow to a `...` when resizing to smaller sizes, just like the panel titles. So the overflow menu would show all of the actions that are hidden:

![image](https://user-images.githubusercontent.com/35271042/72829012-bcb17800-3c32-11ea-84da-0cafffd68a9d.png)

This would allow us to decrease the min-width for the panel.

**Comment by misolori** [comment]
After discussing this during our UX Sync we thought this was worth pursuing but we'd need to cautious of a state where the panel titles has an ellipsis and the actions on the right also have one. One idea was to swap the ellipsis in the terminal panel. We'll ideate on this a bit.

**Comment by flyerH** [comment]
I have a same issue

![20200207-155406-HD 2020-02-07 16_03_14](https://user-images.githubusercontent.com/17452527/74011697-6e86cd80-49c3-11ea-9abb-5b26423f9896.gif)

**Comment by P1X3L0V4** [comment]
Can you please make the terminal panel minimum width configurable? I work on widescreen (2560) - two documents side by side + terminal panel and before the update I was able to save much more space on the right when terminal was open. Now it snaps around 420px, before it was ~250px

**Comment by tw-space** [comment]
I have to imagine this must be a bug .. right? The new min width for the terminal panel, especially on laptops, is crazy annoying.

I already hide all the panel buttons (thank goodness there's a way with css customization). Which worked & felt great before. But now? I mean, sure, all the panel headings are visible without overflow now, with room to spare. But only the terminal matters (for me). So .. thanks but no thanks?

I haven't calculated, but @P1X3L0V4's assertion on then & now widths (250px vs 420px) sounds about right:
<img width="1362" alt="Screen Shot 2020-02-08 at 1 10 29 PM" src="https://user-images.githubusercontent.com/56986410/74092087-6a66b880-4a74-11ea-812c-936442a05eea.png">

Please revert the min width to ~250px, as before.

**Comment by Tyriar** [comment]
@misolori 👍 to collapsing the buttons into an ellipsis but I think the dropdown should also be included in the overflow button. Otherwise the terminal is forced to be larger than the other panels, for example what happens when you open the debug console, size it as small as possible and then open the terminal? Does the panel expand from opening a different one?

**Comment by sbatten** [comment]
@Tyriar I think we should not have it resize by changing panels. I want to find a way to get every in the old minimum width and keep that restriction for all panels. Since we are tracking this item closely to find a resolution, I am going to revert the minimum width change now in favor of a fix that gets the terminal within the bounds.

**Comment by sbatten** [comment]
btw, problems panel is looking like this in a small width.

![image](https://user-images.githubusercontent.com/6561887/74546339-4d603880-4eff-11ea-99fa-e354c0e069e6.png)

**Comment by sbatten** [comment]
old width restored: b51e12159525ded4b690e34338014ab37efe0b3d

**Comment by inwardmovement** [comment]
> I already hide all the panel buttons (thank goodness there's a way with css customization)

@tw-space can you share your CSS rules to hide panel buttons and prevent panel headers from collapsing please?

**Comment by FrizzleFur** [comment]
on the opposite, I want to set the panel wider😂, the default is not enough for me, but I cannot find the settings, anyone who knows?

**Comment by calebplum** [comment]
Can you please make the minimum panel width configurable? Some people want it larger, some smaller. Why not give the option to choose the value that works best for your particular screen size and preferences?

Personally I want to make the minimum width smaller. On a laptop screen I sometimes like to collapse a side panel until I need it, and the current width wastes precious space with two windows side-by-side on a 1080p screen.

**Comment by SIMJO77ZZ** [comment]
ffmpeg -hwaccel auto -y -i "/storage/emulated/0/Android/data/com.silentlexx.ffmpeggui/files/sample.mp4" -s 1920x1080 -c:v wmv2 -q:v 5 -c:a wavpack -ab 128k -ar 44100 "/storage/emulated/0/Download/sample.wmv"

ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 4.9.x (GCC) 20150123 (prerelease)
  configuration: --enable-version3 --enable-gpl --enable-nonfree --disable-indev=v4l2 --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libvorbis --enable-libtheora --enable-libopus --enable-libfdk-aac --enable-libfreetype --enable-libass --enable-libfribidi --enable-fontconfig --enable-pthreads --enable-libxvid --enable-filters --enable-openssl --enable-librtmp --disable-protocol='udp,udplite' --enable-libopencore-amrwb --enable-libopencore-amrnb --enable-libvo-amrwbenc --enable-libspeex --enable-libsoxr --enable-libwebp --enable-libxml2 --enable-libopenh264 --enable-jni --prefix=/home/silentlexx/AndroidstudioProjects/ffmpeg/ffmpeg/build/arm-api18-r13b --sysroot=/home/silentlexx/Android/android-ndk-r13b/platforms/android-18/arch-arm --arch=arm --disable-shared --enable-static --enable-pic --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffnvcodec --disable-avdevice --disable-debug --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-symver --cross-prefix=/home/silentlexx/Android/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=android --enable-cross-compile --pkg-config-flags=--static --extra-libs='-lgnustl_static -lm -lpng -l:libz.so -lpthread' --enable-asm --enable-neon --enable-small
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Android/data/com.silentlexx.ffmpeggui/files/sample.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2010-03-20T21:29:11.000000Z
    encoder         : HandBrake 0.9.4 2009112300
  Duration: 00:00:05.57, start: 0.000000, bitrate: 551 kb/s
  Stream #0:0[0x1](und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 560x320, 465 kb/s, 30 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2010-03-20T21:29:11.000000Z
      vendor_id       : [0][0][0][0]
      encoder         : JVT/AVC Coding
  Stream #0:1[0x2](eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 83 kb/s (default)
    Metadata:
      creation_time   : 2010-03-20T21:29:11.000000Z
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> wmv2 (native))
  Stream #0:1 -> #0:1 (aac (native) -> wavpack (native))
Press [q] to stop, [?] for help
[out#0/asf @ 0xb0e6f3c0] Could not write header (incorrect codec parameters ?): Operation not permitted
[vost#0:0/wmv2 @ 0xb0e38000] Error initializing output stream: 
Conversion failed!



https://m.youtube.com/@YOSHIMIXXUGRAFFIT47


https://m.youtube.com/@YOSHIMIXXUGRAFFIT47


https://m.youtube.com/@YOSHIMIXXUGRAFFIT47

**Comment by benibenj** [comment]
Setting `workbench.panel.showLabels` to `false` will give you much more space in the title area
