### ISSUE TITLE
vscode.executeCompletionItemProvider results are missing additionalTextEdits

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#87346]
If you return `additionalTextEdits` in a completion item, the property is `undefined` when calling through `vscode.executeCompletionItemProvider`.

Setup:

```ts
const pos = new vscode.Position(0, 0);
const range = new vscode.Range(pos, pos);

context.subscriptions.push(vscode.languages.registerCompletionItemProvider({ language: "markdown" }, {
	provideCompletionItems: (document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) => {
		// Build a string like `test(onPressed: [null])` where [null] is
		// a placeholder containing "null".

		const item = new vscode.CompletionItem("dantup");
		item.insertText = "dantup";
		item.additionalTextEdits = [
			new vscode.TextEdit(range, "additional-dantup"),
		];
		return [item];
	}
}));
```

Test code:

```ts
const doc = await vscode.workspace.openTextDocument({ language: "markdown" });
const results = await (vscode.commands.executeCommand("vscode.executeCompletionItemProvider", doc.uri, pos, undefined, 100000) as Thenable<vscode.CompletionList>);
const result = results.items.find((c) => c.label === "dantup")!;
console.warn(result.label);
console.warn(result.additionalTextEdits);
```

Output is:

```
dantup
undefined
```

Full repro project is here:

https://github.com/DanTup/vscode-repro-completion-additional-edits

**Comment by jzyrobert** [comment]
@jrieken It looks like the conversion [here](https://github.com/microsoft/vscode/blob/656fff3b1efdc4fa35f29a6f0665091b021ff042/src/vs/workbench/api/common/extHostTypeConverters.ts#L854) is missing.

The doc states that additionalTextEdits should not overlap with the main edit range or each other, should that be checked or is that done when the edits are carried out?

**Comment by jrieken** [comment]
No checks required - this is already the way back from the UX and check should have been carried out already
