### ISSUE TITLE
When &middot; is wider than &nbsp; rendered whitespace goes outside the reserved area

### ISSUE THREAD

**Issue by mvoidex** [microsoft/vscode#87359]
Issue Type: <b>Bug</b>

I prefer using non-monospace font.
VSCode draws spaces incorrectly and draws caret incorrectly when it stands within indent part

![vscode-incorrect-spaces](https://user-images.githubusercontent.com/1637937/71173741-8b7d0b00-2274-11ea-8d07-253a6685bbe8.gif)

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.171-70.1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (7.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alkorops|
|OS|Linux x64 4.4.171-70.1|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (42 x 1999)|
|Memory (System)|235.18GB (7.87GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.6
vscode-remote-extensionpack|ms-|0.19.0
generic-input-method|mr-|0.0.11
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
vscode-yandex-arc|per|0.4.3
python|tht|0.2.3
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by gaotongsh** [comment]
I have the same issue, but with font set to [Source Han Mono](https://github.com/adobe-fonts/source-han-mono), which is a monospace font for Latin alphabet _and_ CJK characters.

**Comment by alexdima** [comment]
@mvoidex What font family do you use?

@gaotongsh Can you please create a separate issue with your OS info, etc. There might be different issues, since you say you have a monospace font, while this issue talks about a non-monospace font.

**Comment by mvoidex** [comment]
> @mvoidex What font family do you use?

Lucida Sans Unicode
