### ISSUE TITLE
Remove text as it is offensive to illiterates

### ISSUE THREAD

**Issue by yamashi** [microsoft/vscode#87358]
I find that any form of written text is offensive as it excludes people who are illiterate, 14% of the world's population is illiterate so we must do something for this minority. Also we can clearly see that illiteracy is more prevalent in struggling economies areas such as countries in Africa. They have suffered enough and I find offensive that we pretend to be better than everybody else just because we can read. 
Please remove the use of any kind of written language from your product.

Version: 1.42.0-insider (user setup)
Commit: 26f5dfc
Date: 2019-12-19T05:31:04.916Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

    Install latest build of insiders.

Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered.
https://ourworldindata.org/literacy

**Comment by Phillipus** [comment]
word

**Comment by Arteneko** [comment]
you excel at puns

**Comment by DrLynix** [comment]
as an illietrate myself, I strangely suporrt tihs.

**Comment by Hamdullah-gif** [comment]
👏🏽

**Comment by monterinio** [comment]
I'm writing here since the original post is blocked.
It''s interesting... a jew named Christian, don't ya think so?

**Comment by lordjbs** [comment]
+1 from me

**Comment by loicbersier** [comment]
I would suggest to use wingdings as an easy fix.
Hope this will get accepted!

**Comment by binn** [comment]
Great suggestion! Implement a change to allow illiterate people who can't even access a computer access to vsc! I have no objections whatsoever.
