### ISSUE TITLE
Please add Do not show again button to php error message

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#8735]
![image](https://cloud.githubusercontent.com/assets/5047891/16566068/f358767a-4211-11e6-8966-d5e0d1110a60.png)

**Comment by dbaeumer** [comment]
There is a setting to turn that off. It is: 'php.validate.enable'. I would love to add a button to not show this again but it would require to have access to the settings in the extension host. @aeschli I know you worked on this. Any status?

**Comment by aeschli** [comment]
@dbaeumer That's not ready to use yet. For now you can offer a button that brings the user to the settings page (similar to what Ben does with the 'Configure File Associations')

**Comment by dbaeumer** [comment]
@aeschli Thanks. Makes sense.
