### ISSUE TITLE
It shows a blank screen

### ISSUE THREAD

**Issue by AxiomJalaj** [microsoft/vscode#87353]
Issue Type: Bug

When I upgraded my windows to windows 10(November 2019) from windows 10(August 2018) my code started to show a blank screen. I searched on the net and found that it would work if I ran it in compatibility mode. So I ran it in compatibility mode for windows 8. It did ran but then I discovered that its terminal wasn't working and it just showed a blank screen. I tried re-installing several times but it simply didn't work.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 6.2.9200 (generated by issue reporter in compatibility mode. Actual is 10.0.18363.476)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-3305M APU with Radeon(tm) HD Graphics (2 x 1897)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.48GB (4.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.6
vsc-material-theme|Equ|30.0.0
python|ms-|2019.11.50794
material-icon-theme|PKi|3.9.2

</details>

When I run it without compatibility mode:
![Capture](https://user-images.githubusercontent.com/58107107/71171487-e833f200-2283-11ea-979c-85940bec558e.PNG)
When I run it in compatibility mode for windows 8:
![Capture](https://user-images.githubusercontent.com/58107107/71171129-0f3df400-2283-11ea-864b-3ceefc87b260.png)

**Comment by Tyriar** [comment]
The terminal doesn't work with compatibility mode on: https://code.visualstudio.com/docs/editor/integrated-terminal#_integrated-terminal-exited-with-code-1-on-windows-10

Moving to @deepak1556 to look into why it's a blank white window when not using compat mode.

**Comment by AxiomJalaj** [comment]
It is fixed now. It was just a bug with the OS and got fixed with a nice OS update
