### ISSUE TITLE
Updates no longer installable from within VS Code

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/vscode#87356]
Issue Type: <b>Bug</b>

I no longer get the option to install an update. Instead, VS Code notifies me about the update and tells me to go and download it. Similarly, the option in the settings cog menu is now "Download update" instead of "Install update."

To make matters worse, the downloaded file does not contain an installer, but just a bunch of files that I'm supposed to copy to my installation folder.

This is a dramatically worse experience and I don't understand why it was changed.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.26GB free)|
|Process Argv|--folder-uri file:///c%3A/dev/src/CitadelFramework/citadel-framework-ui|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
ng-template|Ang|0.900.3
vscode-combine-scripts|Bat|2.0.5
xml|Dot|2.5.0
gitlens|eam|10.2.0
php-debug|fel|1.13.0
todo-tree|Gru|0.0.162
vscode-jasmine-test-adapter|hbe|1.6.2
vscode-test-explorer|hbe|2.15.0
randomeverything|hel|0.0.3
typelens|kis|1.9.3
json-to-ts|Mar|1.5.5
code-coverage|mar|1.1.0
git-graph|mhu|1.19.1
vscode-azureappservice|ms-|0.16.2
azure-account|ms-|0.8.7
powershell|ms-|2019.12.0
debugger-for-chrome|msj|4.12.3
vscode-jest|Ort|3.0.2
vscode-versionlens|pfl|0.24.0
angular-karma-test-explorer|raa|1.2.4
LiveServer|rit|5.6.1
vscode-coverage-gutters|rya|2.4.2
code-settings-sync|Sha|3.4.3
vscode-taskexplorer|spm|1.21.0
vscode-wakatime|Wak|2.2.1
vscode-import-cost|wix|2.12.0

</details>

**Comment by joaomoreno** [comment]
This is strange. Please completely remove Code and reinstall it.
