### ISSUE TITLE
Suggestion: Add Santa Hat in vscode insiders

### ISSUE THREAD

**Issue by Darkov3** [microsoft/vscode#87354]
A Santa Hat is the symbol of Christmas: the holiday of giving and getting together with family and friends. It is celebrated over the world, from USA to Japan. It is an atmosphere of joy and holiday spirit. It inspires people to give gifts and donate to charities. The one time of the year to let go of grudges and hate and forgive. To relax and forget your problems at least for a day with your friends and family.

I suggest Microsoft shows their love for the holiday spirit and that they are not a Grinch (an enemy of forgiveness, happiness: aka bitterness and hate) and create a quick update to add this symbol. That way you will not only brighten the holidays of many but also remind them of what is truly important in life: family and friends. Please make it your top priority.

**Comment by sudoxd** [comment]
Make VSCode Great Again.
Bring back the hat.

**Comment by Phillipus** [comment]
+1 for the hat. And a reindeer.

**Comment by navx2810** [comment]
Could at least make it a setting we can toggle.

**Comment by chojrak11** [comment]
The fact that some people demand tolerance for their beliefs and priorities by not tolerating others' beliefs and priorities is a hypocrisy. Very well known phoenomenon these days.

I expect the Santa Hat to return.

**Comment by Razzile** [comment]
🎅Santa approves this request

**Comment by vini2003** [comment]
I entirely support this decision. Bring back Santa Hat - one's disliking for it doesn't warrant a complete removal. Nowadays, Santa and Christmas are barely about religion anymore either way.

Make Insiders Christmas-y Again.

**Comment by bhack** [comment]
Octodex https://octodex.github.com/saint_nictocat/

**Comment by iaxx** [comment]
Surely the overwhelming support for the Santa hat as opposed to that one grinch is enough to overturn that decision.

**Comment by Hakier** [comment]
I would also like Santa's Hat to return. You can add flag to not show it. But please not remove this pretty nice feature because of one Grinch (an enemy of forgiveness, happiness: aka bitterness and hate).

Like people above said this is a symbol of spending time with friends and family.

**Comment by wolfensg** [comment]
UpVote for Santa !

**Comment by nkkollaw** [comment]
🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅

**Comment by bhack** [comment]
https://www.theregister.co.uk/2007/12/04/microsoft_kills_santa/
