### ISSUE TITLE
:santa:

### ISSUE THREAD

**Issue by Phillipus** [microsoft/vscode#87357]
:santa:

**Comment by Phillipus** [comment]
:santa: :santa:

**Comment by Phillipus** [comment]
:santa: :santa: :santa:

**Comment by Phillipus** [comment]
:santa: :santa: :santa: :santa:

**Comment by Phillipus** [comment]
:santa: :santa: :santa: :santa: :santa:

**Comment by Phillipus** [comment]
:santa: :santa: :santa: :santa: :santa: :santa:

**Comment by pgawlowski** [comment]
BTW. To original author of this storm - Christian-Schiffer. I wonder is his name not offending him?
https://en.m.wikipedia.org/wiki/Christian_(given_name)
Maybe he should change it...

**Comment by Phillipus** [comment]
:santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa:

**Comment by Phillipus** [comment]
:santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa:

**Comment by Phillipus** [comment]
@Christian-Schiffer don't suppose you know a workaround?

**Comment by pgawlowski** [comment]
🎅 🎅 🎅 🎅 🎅 🎅🎅
@Christian-Schiffer 
https://en.m.wikipedia.org/wiki/Christian_(given_name)
Maybe you should change it...

**Comment by ArtHell** [comment]
🎅

**Comment by sarjann** [comment]
🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅

**Comment by wopoczynski** [comment]
santasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasantasanta

And all of these dislikes from 1 user lmao
