### ISSUE TITLE
"Save All" is greyed out

### ISSUE THREAD

**Issue by AndyLuckert** [microsoft/vscode#87352]
- VSCode Version: 1.41.0 (x64)
- OS Version: Linux Lubuntu 18.04

**Problem:**
Since the day before yesterday more or less, the button under the tab "File" > "Save All" is greyed out.

**Tried solution with no avail:**
Due to having installed some extensions recently, I've disabled all of them via the following
command, which starts a new window of VSCode with all extensions disabled:
`code --disable-extensions`

As an aside, the shortcut for "Save All" (in my case "Ctrl+Shift+S") doesn't seem to work either. When I close a file without saving it, it saves upon closing automatically, it seems.

Thanks in advance for your comments and suggestions.

**EDIT:**
@bpasero : Thanks for your answer.
I'm going to write here, since I can't seem to answer below the answer of @bpasero :
- I don't know what you mean by "dirty files". Before, I had python-scripts, text-files etc. opened all at once in different tabs, and all of the sudden "Save All" stopped being available.
- As for "do you have steps", I don't have any more details, unless you ask me for something specific.

**Comment by bpasero** [comment]
@AndyLuckert "Save All" will only be enabled when there are dirty files. Do you have steps?

**Comment by k40L1n** [comment]
Same issue here as well.
I'm using basic HTML, CSS and JS files.
It worked fine before even with my Shopify liquid files etc, but won't work now.

**Comment by bpasero** [comment]
@AndyLuckert @k40L1n  "Save All" will only be enabled when there are dirty files. Do you have steps?

**Comment by AndyLuckert** [comment]
> @AndyLuckert @k40L1n "Save All" will only be enabled when there are dirty files. Do you have steps?

I'm sorry, there were no steps to state.
It just seems to have changed from one day to the other, and that's it.
Could it have been an update of VSCode?

**- VSCode Version:**
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64

**- OS Version:**
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"

**Comment by samkern108** [comment]
This is affecting me as well. One day "save all" was enabled, the next day it was disabled for all of my workspaces, regardless of whether there are dirty files.
(I have checked; even with a dirty file that it not focused in the editor window, save all is greyed out.)

**Comment by k40L1n** [comment]
Literally the same thing.
Sometimes its fine, sometimes it's not.

At my office it generally doesn't have that option enabled, but at home it
keeps switching, either it's activated or its not.
