### ISSUE TITLE
Your icon is offensive

### ISSUE THREAD

**Issue by nkkollaw** [microsoft/vscode#87368]
I've been meaning to say this for a while, and now that someone found the courage to stand up against the Santa hat, I found the will to post this.

Your icon is obviously a representation of Jesus (see https://www.iconfinder.com/icons/1374273/christian_fish_jesus_religion_icon for comparison), and that's just unacceptable.

I do NOT understand why a code editor tool must push religion onto its users.

Why do you push the idea that Christianity should be the most important religion? I don't see any icons celebrating other religions anywhere in your app.

Please fix this ASAP, not everyone is Christian!!!

**Comment by x1024** [comment]
Forget the VSCode icon, the MICROSOFT icon literally has a cross in it, and the company has "cross" in its name! (kind of)

**Comment by Rodrigo54** [comment]
visual studio code icon is directly related to ide visual studio

This icon only represents that vscode is not a complete ide and is limited to a text editor.
![Sem título](https://user-images.githubusercontent.com/8932920/71177250-5a87e080-224a-11ea-95c3-75c48425eb5d.png)

Believing that a fish icon represents Christianity only demonstrates its lack of knowledge of that religion.

It is clear here that this is a big coincidence and not a conspiracy plan of a religion.

I suggest closing this issue and stop listening to the crazy conspiracy theories.

**Comment by Rodrigo54** [comment]
I was taken by surprise and did not notice the irony
it seems like it all started because of santa's hat kkkkkkk
https://github.com/microsoft/vscode/issues/87268

🎅

**Comment by Sajgoniarz** [comment]
@Rodrigo54 "Believing that a fish icon represents Christianity only demonstrates its lack of knowledge of that religion." - Fish was the first symbol used to mark churches during roman oppression, back in those times it was treated as most sacred symbol.  Moreover it was used by Christians to recognize themselves on the roads. So, who have the lack of knowledge problem now?

**Comment by Rodrigo54** [comment]
@Sajgoniarz Before we assume that fish symbolizes Christianity, we must understand that Christianity is not just made up of evangelical and Protestant churches. Catholicism is also a Christian religion and the oldest symbol representing Christianity and the cross.

Merry Christmas
🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅

**Comment by ostronom** [comment]
Does it matter if fish represents something or not? IF SOMEONE IS OFFENDED BY IT -- THEY SHALT REMOVETH IT!

**Comment by sunriseiscool** [comment]
I cannot believe they would try to sneak their religion into their logo... Absolutely unacceptable. Please change the logo.

**Comment by egamma** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
