### ISSUE TITLE
Suggestion: Add Cthulhu tentacles to the settings icon

### ISSUE THREAD

**Issue by adiospl** [microsoft/vscode#87360]
Please add Cthulhu tentacles to the settings icon on the 31st of October/1st of November. 

Lack of tentacles is very offensive to the whole community of Great Old Ones believers. 

Ph’nglui mglw’nafh Cthulhu R’lyeh wgah’nagl fhtagn.

**Comment by Phillipus** [comment]
Sounds too much like "testicles." #offensive

**Comment by virgiliu** [comment]
ph͟'͝nģlu̡i m͝gl̵w'̶n̛a̸fh ̴Cthul̢h͞u͞ R͢'̴l̵y̢eh ̧w̸g͜ah'n̡agl fh́tagn̶
