### ISSUE TITLE
The removel of Santa Hat is very offensive to ME

### ISSUE THREAD

**Issue by brlebtag** [microsoft/vscode#87363]
ONE guy complained (https://github.com/microsoft/vscode/issues/87268) that Santa Hat is offensive because it pushes religious. (Santa Hat is a religious symbol? Coca-Cola invented Santa Claus, not Christianity).

It was immediately accepted.

But I think that is offensive to ME as well. So I want to put it back.

How about now?

Are you guys immediately accepting mine too?

**Comment by AUTOMATIC1111** [comment]
are you jewish

**Comment by brlebtag** [comment]
No. damnit!!!

I guess I am not minority enough to be heard. I'm just a White, privilege, Christian, German descendent.

I should just accept what my minority overlords demand!

**Comment by chriva** [comment]
Bring back the hat!

**Comment by sh7d** [comment]
>Are you guys immediately accepting mine too?
They will not accept your offensives cause you are not a jew or any other so called "oppressed" group.

If you change your line of argumentation to something like: "removal of santa claus confirms patriarchate" then it might work :)

You have to be MINORITY

>I guess I am not minority enough to be heard. I'm just a White, privilege, Christian, German descendent.

EXACTLY

**Comment by Proximyst** [comment]
> Coca-Cola invented Santa Claus, not Christianity).

I'd just like to quote this to redirect you to information about Nikólaos, the man we today know as St. Nicholas or the Santa Claus: [https://en.wikipedia.org/wiki/Saint_Nicholas](https://en.wikipedia.org/wiki/Saint_Nicholas).

It was indeed neither Coca-Cola nor Christianity which invented him, but rather his parents, whoever these people lost in time were. Therefore, someone of any religion should not have much of a problem with the man, unless they oppose the ancient Romans, so I suppose anyone from around Magna Germania, or the Germanic areas north of the Roman Empire. I support having the hat, as it's got nothing to do with Christianity, but rather to do with one man being stubborn.

**Comment by brandonvdongen** [comment]
Christmas and Santa as we Know it has various celebrations depending on where you come from. here in the netherlands we even celebrate the equivelant of 'christmas eve' twice in 2 months time. because of things getting lost in translation when coca-cola started pushing it worldwide. 

25 y/o non religious programmer and even i agree the hat should be brought back. christmas is one of the few things that gives me hope around these times of the year. 

To me it wouldn't even be considered a religious symbol if it was to begin with, It's a symbol that represents caring for others and spreading of happiness among friends and family. why is that such a bad thing?

**Comment by rustamgaifullin** [comment]
I'm not Christian but I was offended by removing Christmas Hat.

**Comment by chriva** [comment]
They really took a dump in the blue cupboard by accepting that nonsense.
The hat has nothing to do with religion. It's a folklore that has since been blown out of proportions, a beloved tradition if you will.

#bringbackthehat

**Comment by Kagetsuki** [comment]
I'm Jewish and the Russian part of my family have winter decorations and celebrations surrounding a character called Ded Moroz, which is likely where the image of Santa/Father Christmas was actually derived from ( https://en.wikipedia.org/wiki/Ded_Moroz ). Furthermore, the so-called "Santa hat" is just a stocking cap which appears in a wide variety of cultures without any specific religious associations.

It's a shame that some choose to be offended on the behalf of others without even consulting with those they are trying to be offended for. I, as a Jew, am offended that someone would portray me and other Jews as being so weak and mentally delicate that a hat loosely associated with a specific "religious" holiday would cause great offence and mental distress. And shame on Microsoft for folding to such a silly demand.
