### ISSUE TITLE
Oh my zsh symbols are not rendered correctly on Catalina

### ISSUE THREAD

**Issue by hologerry** [microsoft/vscode#87366]
- VSCode Version:
```
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```
- OS Version: macOS 10.15.2

Steps to Reproduce:

1. Use a font support powerline glyphs
2. Open integrated terminal
3. Look

On iTerm 2:
<img width="1042" alt="Screen Shot 2019-12-19 at 20 37 30" src="https://user-images.githubusercontent.com/11660168/71174130-65209500-229f-11ea-836a-077279059abe.png">
It produces:
<img width="682" alt="Screen Shot 2019-12-19 at 20 35 23" src="https://user-images.githubusercontent.com/11660168/71174145-6c47a300-229f-11ea-9a28-f0e83227a4f2.png">

On VS Code:
```
"editor.fontFamily": "FuraCodeNerdFontComplete-Retina",
"editor.fontLigatures": true,
"editor.fontSize": 12,
"terminal.external.osxExec": "iTerm.app",
"terminal.integrated.fontFamily": "FuraCodeNerdFontComplete-Retina",
```
however it produces:
<img width="413" alt="Screen Shot 2019-12-19 at 20 35 32" src="https://user-images.githubusercontent.com/11660168/71174208-9bf6ab00-229f-11ea-80d1-bb325e418541.png">

It maybe an OS related issue, but it can be fix on iTerm https://github.com/ohmyzsh/ohmyzsh/issues/8235, so I think it also could be fix on VS Code.

More examples:
<img width="682" alt="Screen Shot 2019-12-19 at 20 47 48" src="https://user-images.githubusercontent.com/11660168/71174761-e9274c80-22a0-11ea-9a68-9f5b9d4eb0a8.png">
<img width="245" alt="Screen Shot 2019-12-19 at 20 47 56" src="https://user-images.githubusercontent.com/11660168/71174764-eaf11000-22a0-11ea-8aa8-c7b8e4205e39.png">
<img width="980" alt="Screen Shot 2019-12-19 at 20 54 16" src="https://user-images.githubusercontent.com/11660168/71175170-d3feed80-22a1-11ea-8e4d-780a79b7b285.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
The symbols aren't right because the same font isn't configured, see how the `r` character looks very different for example.
