### ISSUE TITLE
Regarding c++ stl use of vector

### ISSUE THREAD

**Issue by ashishugi** [microsoft/vscode#87367]
We have written the needed data into your clipboard because it was too large to send.

vector<int>* edgeT = new vector<int> [n];
    vector<int>* edge = new vector<int>[n];
 writing above line below one another generates an error , i.e the 2nd line does not get detected( vector<int>* edge = new vector<int>[n];).

**Comment by x1024** [comment]
The santa hat, though! 🎅

**Comment by dbaeumer** [comment]
@ashishugi can you please provide the data?

**Comment by ashishugi** [comment]
ok , see the below lines of code


`
#include<bits/stdc++.h>
#include<vector>
#include<unordered_set>
#include<stack>
using namespace std;
void dfs(bool* visited,int start,vector<int>* edge ,stack<int>& st){
    visited[start] = true;
    for(int i=0;i<edge[start].size();i++){
        int adj = edge[start][i];
        if(!visited[adj]){
            dfs(visited,adj,edge,st);
           
        }
    }
    st.push(start);
}
void dfs2(bool* visited,vector<int>* edgeT,int start,unordered_set<int>* com){
     visited[start] = true;
     com->insert(start);
    for(int i=0;i<edgeT[start].size();i++){
        int adj = edgeT[start][i];
        if(!visited[adj]){
            dfs2(visited,edgeT,adj,com);
            
        }
    }
}
void scc(vector<int>* edge,vector<int>* edgeT,int n){
    bool* visited = new bool[n];
    for(int i=0;i<n;i++){
        visited[i] = false;
    }
    stack<int> st;
    for(int i=0;i<n;i++){
        if(!visited[i]){
            dfs(visited,i,edge,st);
           
        }
    }
    for(int i=0;i<n;i++){
        visited[i] = false;
    }
    unordered_set<unordered_set<int> *>* collection = new unordered_set<unordered_set<int> *>(); 
    while(!st.empty()){
       int top = st.top();
        st.pop();
           
                unordered_set<int>* component = new unordered_set<int>();
                if(!visited[top]){
                    dfs2(visited , edgeT,top,component);
                    
                }
               (collection)->insert(component); 
        
        
     }
    unordered_set< unordered_set<int>* >::iterator itr = collection->begin();
    for(;itr!=collection->end();itr++){
        unordered_set<int>* temp = *itr;
        unordered_set<int>::iterator it = temp->begin();
        for(;it!=temp->end();it++){
            cout<<*it+1<<" ";
        }
        cout<<endl;
    }
}
int main(){
    // making of adjacency list
    int n;
    cin>>n;
     vector<int>* edgeT = new vector<int> [n];
    vector<int>* edge = new vector<int>[n];  **// this line is not getting detected**
   int e;
    cin>>e;
    for(int i=0;i<e;i++){
        int s,f;
        cin>>s>>f;
        edge[s-1].push_back(f-1);
        edgeT[f-1].push_back(s-1);
    }
    scc(edge,edgeT,n);
    return 0;
}
`

**Comment by ashishugi** [comment]
above at line number 72 , after writing 
`vector* edgeT = new vector [n];
vector* edge = new vector[n];`
above line one after another the 2nd line do not gets detected in visual stdio .

**Comment by dbaeumer** [comment]
@ashishugi what do you mean it doesn't get detected. Not colored not code assist available?

**Comment by ashishugi** [comment]
Yes the syntax is not getting colored , also on compilation that line is showing error

**Comment by alexr00** [comment]
@ashishugi this is what I'm seeing:
![image](https://user-images.githubusercontent.com/38270282/71809367-43315b80-3070-11ea-8200-f9cb6ced6fe0.png)

Can you please provide a screen shot?

**Comment by ashishugi** [comment]
@alexr00  see the screen shot .
![vs](https://user-images.githubusercontent.com/46626591/72242759-34b6e700-3610-11ea-88b9-dc833ee22287.png)

**Comment by ashishugi** [comment]
see the line number 72 in the screen short .

**Comment by alexr00** [comment]
It's still getting colored correctly for me. Can you try disabling all installed extensions?
![image](https://user-images.githubusercontent.com/38270282/72243803-1db2cd80-35ed-11ea-9702-f51963a2d31e.png)

**Comment by ashishugi** [comment]
done but nothing happened .

**Comment by alexr00** [comment]
What version of VS Code are you using? I can't reproduce the issue on 1.41.1 or insiders (1.42.0).

**Comment by ashishugi** [comment]
i am using Version: 1.35.1

**Comment by alexr00** [comment]
The issue no longer occurs on 1.41.1, please update to get the latest!
