### ISSUE TITLE
actual clean file is marked as dirty

### ISSUE THREAD

**Issue by liangjiancang** [microsoft/vscode#87372]
Open a file, insert something, and delete.
The file is the same as before, but it is marked as dirty.

**Comment by sunriseiscool** [comment]
It's because they removed the santa hat.

**Comment by bpasero** [comment]
This is intentional. The dirty indicator makes sure the user is aware that there is an undo-stack that can restore data in the session. I would not easily want to change it. The file shows as non-dirty if you undo enough until the file is back empty.
