### ISSUE TITLE
Issues tracker being spammed with SantaGate silliness: proposed fix

### ISSUE THREAD

**Issue by Phillipus** [microsoft/vscode#87371]
Bring back the hat.

:santa:

**Comment by shika-blyat** [comment]
I strongly support that fix !

**Comment by chriva** [comment]
Proposed fix should solve the issues 🎅🎅🎅

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
