### ISSUE TITLE
Gender problem

### ISSUE THREAD

**Issue by p-lee-grimm** [microsoft/vscode#87370]
Please remove MS SQL extension and any compatibility with it because it's only SQL's business which gender they are.

**Comment by toniejestgorlik1337** [comment]
![PepeTheFrog](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fih1.redbubble.net%2Fimage.286268989.0224%2Fap%2C550x550%2C12x12%2C1%2Ctransparent%2Ct.u2.png&f=1&nofb=1)

**Comment by egamma** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
