### ISSUE TITLE
To all you stupid spammers

### ISSUE THREAD

**Issue by chojrak11** [microsoft/vscode#87377]
What are you trying to achieve? You want Microsoft to kill this project? Go ahead.

**Comment by Phillipus** [comment]
:santa:

**Comment by nkkollaw** [comment]
Better dead, than anti-Santa hat.

**Comment by wooglie** [comment]
Quick, pull the repo

**Comment by prikhodkoalexey** [comment]
🎅

**Comment by AveryanovS** [comment]
You offense me by 'stupid', you, abuser!

**Comment by exasky** [comment]
You offense me by 'spammers', you, abuser !

**Comment by acedened** [comment]
Please refrain from insults, it violates the code of conduct

**Comment by chojrak11** [comment]
Are you a stupid spammer? Then yes, it's meant to insult. If not, ignore it.

**Comment by Phillipus** [comment]
He ("they"?) have a point though. SantaGate could actually bring about the complete downfall of Microsoft. Like the walls of Jericho. :santa:

**Comment by hckr** [comment]
Please stop posting S*nta icon in comments. It's a hat(e) speech symbol now

**Comment by x1024** [comment]
https://i.kym-cdn.com/entries/icons/facebook/000/031/015/EA42mJJXYAEzxWF_(2).jpg

**Comment by chriva** [comment]
🎅 Merry Christmas, everyone

**Comment by laurentb** [comment]
> You want Microsoft to kill this project?

Actually, yes.

I find Electron offensive. JavaScript was a mistake.

**Comment by ArtHell** [comment]
xmas tree is disappointed
![image](https://user-images.githubusercontent.com/10870902/71177765-fe828380-226c-11ea-9356-2b55791c08c2.png)

**Comment by sh7d** [comment]
>What are you trying to achieve? You want Microsoft to kill this project?
All i want from microsoft is that they will sell this project to white male jews

**Comment by ca1ek** [comment]
>You want Microsoft to kill this project?

I would very much love that

**Comment by eppak** [comment]
🎅

**Comment by deitry** [comment]
> I find Electron offensive.

Electron actually holds negative charge. VS Code shoud use Positron instead.

**Comment by yamashi** [comment]
To the journalist who will be reading all of this for his click-bait article of the day, I hope you have a good day !

**Comment by brlebtag** [comment]
@deitry No man, we should be using Neutron instead. No charge at all. Everyone will be satisfied! If you can't have it and I can't have it so no one can have it then Neutron should be!

**Comment by dreais** [comment]
this is what github was made for

**Comment by chojrak11** [comment]
@microsoft please delete this issue.

**Comment by brlebtag** [comment]
@chojrak11, you're a naughty boy, you won't receive your present this year :santa:. Don't close it, you're being offensive!

**Comment by WhiteYaksha** [comment]
Streisand effect at its best
