### ISSUE TITLE
Please rename your project

### ISSUE THREAD

**Issue by prikhodkoalexey** [microsoft/vscode#87375]
VSCode implies that you are versus the code as a concept.
I like the code and many people like the code too.
I suggest ASCode as a new name.
AS is an acronym for "alongside".

**Comment by Phillipus** [comment]
Better still `SAnta Code`.

**Comment by ivanpopelyshev** [comment]
It will remind everyone about ActionScript: it had ints and uints, while JavaScript does not.

**Comment by egamma** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
