### ISSUE TITLE
We started to expose token types in the API

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8737]
With https://github.com/Microsoft/vscode/commit/a8eadbd8d42034bf926d657d33e971892b1b5660 we now apparently settled on exposing token types as `string[]`. I am unsure if this is well thought through and why we didn't continue to use the old way of doing it

**Comment by jrieken** [comment]
@aeschli Pls comment

**Comment by jrieken** [comment]
Some ideas

* We change `notIn: string[]` to `notIn: ('string' | 'comment')[]` to be more *strict* and to not allow stuff like `string.php`
* We acknowledge that we only use this for preventing auto close in `string` and `comment` tokens and just hardcode that in the editor

**Comment by aeschli** [comment]
@jrieken `notIn: ('string' | 'comment')[]` makes sense to me.

**Comment by jrieken** [comment]
alternatively two explicit fields like `notInStrings: boolean` and `notInComments: boolean`

**Comment by alexandrudima** [comment]
:+1: to hard-code that string, comments and regexes do not get this feature and there is no way to enable it inside of those (i.e. hard-code `notIn` to be `['string', 'comment', 'regex']` and remove it from the API

**Comment by jrieken** [comment]
The change also caused #8662
