### ISSUE TITLE
Please bring back the Santa hat, stop persecuting Christians!

### ISSUE THREAD

**Issue by virgiliu** [microsoft/vscode#87386]
The removal of the Santa hat is a slap in the face of all true Christians. Christians were persecuted since the first century of our current era, and in modern times such blatant oppression is unacceptable. To me this is almost equally offensive as the persecution in Lugdunum!

Please bring back the Santa hat and unrustle my true Christian jimmies!

Does this issue occur when all extensions are disabled?: Probably

**Comment by mcosti** [comment]
I am offended and I feel Christian

**Comment by petrukhnov** [comment]
Here another point of view:
https://www.wsj.com/articles/im-jewish-please-wish-me-a-merry-christmas-11575564639

**Comment by CoachGodzup** [comment]
Santa belongs to religion pretty much like pineapple belongs to pizza.

**Comment by Hamdullah-gif** [comment]
> Santa belongs to religion pretty much like pineapple belongs to pizza.

So is 100%?

**Comment by vini2003** [comment]
> 
> 
> Santa belongs to religion pretty much like pineapple belongs to pizza.

Weird way to say Santa is intrinsically a religious symbol.

**Comment by rzurawski1337** [comment]
Wasn't Santa invented by Coca-Cola?
