### ISSUE TITLE
Stop discriminiating against new users

### ISSUE THREAD

**Issue by J0s3f** [microsoft/vscode#87387]
In this repository, it is not possible for "new users" to comment.
![New users are discriminated by Microsoft employees, probably white males](https://user-images.githubusercontent.com/604089/71180111-d0537280-2271-11ea-88e6-a3ce9e2ff638.png)

Why do "new users" have less rights than other users? Are "new users" somehow worth less than "old users"?

**Comment by Mothrakk** [comment]
Microsoft supports zoomercide.

**Comment by Sebastian506563** [comment]
Ok Boomer

**Comment by virgiliu** [comment]
This is censorship and infringes freedom of speech! Is Microsoft turning into a dictatorship?

**Comment by toniejestgorlik1337** [comment]
![PepeTheFrog](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fih1.redbubble.net%2Fimage.286268989.0224%2Fap%2C550x550%2C12x12%2C1%2Ctransparent%2Ct.u2.png&f=1&nofb=1)

**Comment by dreais** [comment]
how to exit new user mode?

**Comment by virgiliu** [comment]
They need to do way instain user

**Comment by vini2003** [comment]
> 
> 
> how to exit new user mode?

`:q`

**Comment by kakolisgay** [comment]
HOW WILL MICROSHAFT EVER RECOVER
