### ISSUE TITLE
urllib.request.urlopen cannot open url

### ISSUE THREAD

**Issue by pjuangph** [microsoft/vscode#87384]
Issue Type: <b>Bug</b>

I used anaconda and followed this tutorial. https://www.youtube.com/watch?v=vKFc3-5Y17U 

I tried running and debugging my code with pycharm and vs code. pycharm allows the debugging and grabs the url request, code does not. I get this error everytime. 

  File "C:\Users\pahtj\Anaconda3\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\Users\pahtj\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\pahtj\Anaconda3\lib\urllib\request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.79GB (22.33GB free)|
|Process Argv|C:\Users\pahtj\OneDrive\Documents\GitHub\Projects\Research\turbine_opt\DesignTool\3D\rev10_python|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.23.0
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
mssql|ms-|1.8.0
python|ms-|2019.11.50794
vscode-ai|ms-|0.6.8
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
vscode-node-azure-pack|ms-|0.0.10
azurerm-vscode-tools|msa|0.8.3
azure-iot-toolkit|vsc|2.14.0

</details>

**Comment by nkkollaw** [comment]
Is this about the Santa hat removal..?

**Comment by ca1ek** [comment]
This doesn't seem to be an issue with VS Code.

:santa: :santa: :santa: :santa: :santa: :santa: :santa:

**Comment by prikhodkoalexey** [comment]
![image](https://user-images.githubusercontent.com/36811399/71179042-6bebdf80-2280-11ea-9c60-74fa83dd3f0a.png)

**Comment by dbaeumer** [comment]
@pjuangph does this also happen if you start VS Code with all extensions disabled?

**Comment by brlebtag** [comment]
:santa: is coming for you!

**Comment by pjuangph** [comment]
> @pjuangph does this also happen if you start VS Code with all extensions disabled?

I need the python extension. I’ll share my files over github

**Comment by pjuangph** [comment]
https://github.com/pjuangph/web-scraper 
Now you can try it. I’m using it with anaconda python 3.74 for both vs code and pycharm

**Comment by dbaeumer** [comment]
@pjuangph this looks like a problem wtih the Python extension. Please file the issue here: https://github.com/Microsoft/vscode-python

**Comment by dbaeumer** [comment]
Here is what I deleted since we decided to preserve it:

<img width="562" alt="capture" src="https://user-images.githubusercontent.com/1931590/71241429-deee6800-230b-11ea-98cc-a4a51434e049.png">

<img width="569" alt="capture" src="https://user-images.githubusercontent.com/1931590/71241454-ed3c8400-230b-11ea-880c-c3a76a94b08f.png">
