### ISSUE TITLE
[javascript] No intellisense for javascript objects created with new?

### ISSUE THREAD

**Issue by raghur** [Microsoft/vscode#8738]
- VSCode Version:1.2.1
- OS Version:Windows 8.1 x64

Steps to Reproduce:

1. I have a nodejs library generated with AutoRest which also generates `d.ts` files.
2. It's `package.json` has `"typings": "path to d.ts file"` generated by autorest.
3. In a project where I have the npm package above referenced, there is intellisense only for the main class constructor. Once an instance is created, intellisense doesn't work on the created object to suggest completions.

gif below to explain

![animation](https://cloud.githubusercontent.com/assets/516267/16566468/5e7c3f8e-4232-11e6-9de8-7368b237bd4c.gif)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9519

**Comment by dbaeumer** [comment]
Moving to TS team.
