### ISSUE TITLE
@microsoft microsoft locked as too heated and limited conversation to collaborators

### ISSUE THREAD

**Issue by x1024** [microsoft/vscode#87393]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kavalanche** [comment]
That's just censorship.

**Comment by virgiliu** [comment]
inb4 thread locked for being too hot

**Comment by Enitoni** [comment]
I'm offended by temperatures above 30 degrees celsius

**Comment by brlebtag** [comment]
Stop censoring us!!! They are showing their true colors!

**Comment by EthanRutherford** [comment]
:fire:
