### ISSUE TITLE
Answer to such idiot issues like @torvalds would do

### ISSUE THREAD

**Issue by tapionx** [microsoft/vscode#87398]
Such an idiot request as #87268 must not generate any kind of change in the codebase.
@Microsoft in this situation you should ask yourself:
"What would my teacher @torvalds answer?"

![Screen-shot-2012-06-18-at-10 32 45-AM](https://user-images.githubusercontent.com/1826929/71182202-f3802100-2275-11ea-81b5-a8311ad02b2e.png)

**Comment by Alko89** [comment]
Sempai!

**Comment by trefr** [comment]
quaglio!

**Comment by chriva** [comment]
I love that guy!
Even given me a few kicks. He knows how to handle stuff lol

**Comment by sh7d** [comment]
>Such an idiot request as #87268 must not generate any kind of change in the codebase.

He is not an idiot, he is just poor, offended by white privileged christianity Jew
Have some MODERN diverse empathy

**Comment by kavalanche** [comment]
He should write his own code editor. But it's easier to destroy other peoples' work.

**Comment by Enitoni** [comment]
> 
> 
> > Such an idiot request as #87268 must not generate any kind of change in the codebase.
> 
> He is not an idiot, he is just poor, offended by white privileged christianity Jew
> Have some MODERN diverse empathy

This has nothing to do with empathy. People are mad at Microsoft bending down to a single person being offended by something the majority of people wouldn't mind at all. They could have handled this better, like adding a toggle.

**Comment by trefr** [comment]
That fucker.. ruined my code editor

**Comment by sh7d** [comment]
> > > Such an idiot request as #87268 must not generate any kind of change in the codebase.
> > 
> > 
> > He is not an idiot, he is just poor, offended by white privileged christianity Jew
> > Have some MODERN diverse empathy
> 
> This has nothing to do with empathy. People are mad at Microsoft bending down to a single person being offended by something the majority of people wouldn't mind at all. They could have handled this better, like adding a toggle.

That was an irony, of course I don't give a fuck about political correctness bullshit :)

**Comment by brlebtag** [comment]
senpai!

**Comment by Reynergodoy** [comment]
> > > Such an idiot request as #87268 must not generate any kind of change in the codebase.
> > 
> > 
> > He is not an idiot, he is just poor, offended by white privileged christianity Jew
> > Have some MODERN diverse empathy
> 
> This has nothing to do with empathy. People are mad at Microsoft bending down to a single person being offended by something the majority of people wouldn't mind at all. They could have handled this better, like adding a toggle.

Let me link you [this](https://examples.yourdictionary.com/examples-of-irony.html).
