### ISSUE TITLE
We demand apologies from Microsoft for the Santa Hat

### ISSUE THREAD

**Issue by brlebtag** [microsoft/vscode#87392]
This Santa Hat situation is unacceptable. This is outrageous and humiliating. We demand apologies from @microsoft and that the Hat be back!

Merry Christmas!!!

**Comment by mike-code** [comment]
XDDDDD careful. microsoft now owns github too and they also take direct orders from jerusalem. your account will be vanished in no time. their petty feelings are way above yours so hush now

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
