### ISSUE TITLE
Stop censoring discussion

### ISSUE THREAD

**Issue by kavalanche** [microsoft/vscode#87395]
You dun goofed, deal with the consequences.

**Comment by virgiliu** [comment]
It's easier for them to just lock down posts and purge comments than it is to properly handle this shitstorm they triggered.

**Comment by jaironalves** [comment]
I live in a country that doesn't snow. I am offended to see a snow icon.

**Comment by trefr** [comment]
Did you remove santa because of the blowjobs he does ?
