### ISSUE TITLE
Removal of Santa icon is hate speech.

### ISSUE THREAD

**Issue by digitallysane** [microsoft/vscode#87391]
Issue Type: <b>Bug</b>

Get back the Santa icon you morons.  How much of a brain do you have to delete that icon as a result of hate speech of a single idiot?

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
