### ISSUE TITLE
Santa hat removal #2

### ISSUE THREAD

**Issue by Asgoret** [microsoft/vscode#87396]
Are you happy @Christian-Schiffer? Your behaviour offence a lot of people around the world.
I think you must apologize to these people and @egamma must do it too.

**UPD#1:** Christmas, like Hanukkah, is a great time of the year. When people give each other a little love, warmth and kindness. Trying to be better than they were during the year. So why spoil this wonderful moment of world peace with unfounded accusations, old insults and other unpleasant things? I don’t understand, and you?

**UPD#2:** And the position when moderators without apologies simply close the comments, thus censoring, in a free society should not be acceptable. I ask @microsoft to intervene in this situation, apologize, and I also want to hear an apology from @dbaeumer who insulted me with his behaviour.

Assign:
#87268
#87386
https://github.com/microsoft/vscode/issues/87389

**Comment by virgiliu** [comment]
@dbaeumer has offended me by locking down issue conversations in which I was an active participant. I feel censored, offended and persecuted. I want an official apology and 5 cookies! 
Also bring Santa back :mrs_claus:

**Comment by daydiff** [comment]
Fully agreed with @Asgoret. Being an atheist doesn't prevent me from celebrating Christmas. And Santa has nothing to do with religion nowadays.

**Comment by mv92** [comment]
Bring the hat back! Why the heck some offended fanatics that see religion every-bloody-where can ruin our holidays! and we, non-religious developers, are being silenced!
Hear us out! Bring the hat back!

**Comment by julianlam** [comment]
> Santa has nothing to do with religion nowadays.

This is the key point here. A santa hat has very little (if anything) to do with the religious holiday. Microsoft, there is accommodating, and there is _too accommodating_. I understand the wish to avoid conflict means you must take a neutral approach to all aspects, and in many ways, I do agree that a text editor should be as neutral as possible, but @Christian-Schiffer went about it completely the wrong way, and he should not be rewarded for this kind of behaviour.

**Comment by Xarkam** [comment]
I think that person (@Christian-Schiffer ) does not know what tolerance towards others is.

I think microsoft shouldn't have given in to this. Already by what it is possible to force the project if something does not please us (and perhaps at this moment that @Christian-Schiffer  should make a special Jewish fork), but also then because it opens the door full of requests on d 'themes other than religion.

**Comment by starvingForThings** [comment]
If I have had everything that bothers me removed, there would not be much left but hey the world isn't all about me. 

Maybe some people should learn to look away and accept that "hey, maybe a santa hat isn't much and maybe it's a small easter egg that made a few developers smile for a second". 

Geezus how selfish do you have to be to ask for its removal non-ironicaly ? 

Bring the hat back, let people enjoy the little thing and, if you want to fight for tolerance, chose your damn fights and chose those who matter.

**Comment by mv92** [comment]
Atheists do have feelings that are constantly being oppressed by religious fanatics.
But we don't stick our "feelings" into the tools that are used by millions of developers from all over the world!
Microsoft is a developer of the FREE tool! Why bring religion to the topic of the development of the said free tool and displease hundreds of thousands.
Stop using religion to push your agenda. 
Stop being offended over the most basic and trivial things...
Please grow up and consider the opinions of others around you

P.S. I have Jewish relatives. I had spoken with families of the victims of the Holocaust.
Not even one of them ever complained about "Santa-hat" when encountered. 
Never.

**Comment by MarcinSzyszka** [comment]
Shame on You Microsoft!
Now you have thousands of offended users and not offended one. 
Someone should get paid rise for Xmas!

**Comment by Asgoret** [comment]
@starvingForThings little things lead to big things. FYI: https://en.wikipedia.org/wiki/Overton_window

I think it will be great in Hanukkah there will be the menorah or, maybe, there is no any symbols any more.

**Comment by julianlam** [comment]
Remember the human. Step back and think about the intent to add the santa hat.

**Was it to signify the birth of Christ**? I doubt it.

**Was it a (possibly) misguided attempt to show appreciation for a time of year where many people put aside their differences and come together as family and friends**? More likely.

**Comment by 0jdxt** [comment]
The guy was literally trying to push his "xmas is anti semitic" article multiple times, trying to say if you like xmas you hate jews. Any sensible person doesnt give a fuck about a tiny santa hat in the corner. I dont even use vscode anymore but this is bs.

**Comment by Asgoret** [comment]
@0jdxt have you some confirmation that he is trying to do this is not the first time?

**Comment by 0jdxt** [comment]
> @0jdxt have you some confirmation that he is trying to do this is not the first time?

I was referring to the fact he took opportunity in each of his comments to post a link to the article when the first one in the issue would have sufficed. The article doesnt even explain why Santa is bad nor why it has anything to do with xmas today. Ironically hes making a religious point complaining about something being religious when it isnt even?

**Comment by virgiliu** [comment]
If you reverse image search his image you'll find a bunch of his posts on other websites and under a different name. He's either a prolific troll or has some warped views. Regardless, he shouldn't have been taken so seriously.

**Comment by asc11cat** [comment]
Why do you even care about Santa hat icon in IDE...

**Comment by EEVV** [comment]
when ur name is literally Christian and ur against santa hat LMAO

**Comment by digitallysane** [comment]
Why does everybody bother getting angry at that idiot who raised the "Santa issue"?
He's just an imbecile that should have been ignored or banned for wasting developer's time.
It's people from the VS Code team like @kieferrm (replying instantly with oh we are so sorry we hurt your feelings and we're gonna delete that immediately) and @egamma that are the real problem.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by asfdfsaf** [comment]
The culture war is everywhere now. SJW-ism against non-fragility. Who will win? 

The corporations will. The governments will. Wokeness is the new little red book for the masses.
