### ISSUE TITLE
Where is 🎅 ?

### ISSUE THREAD

**Issue by Radeox** [microsoft/vscode#87394]
🎅🎅🎅🎅🎅

**Comment by digitallysane** [comment]
https://youtu.be/kntQNeSge5s

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
