### ISSUE TITLE
Replace quotes instead of wrapping them

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#874]
When I have some code wrapped in double quotes like this:

```
"I am a string"
```

I then select the whole string (including the quotes) and press <kbd>'</kbd> it then gives this:

```
'"I am a string"'
```

It would be nice if it replaced the old quotes instead so it looks like this:

```
'I am a string'
```

The same goes for when converting single quotes to double quotes.

**Comment by wildeyes** [comment]
Why not use a plugin for that?

**Comment by ramya-rao-a** [comment]
If you are using the `tslint` extension then you can set the rule [quotemark](https://palantir.github.io/tslint/rules/quotemark/) to get fixes from the linter's auto-fixes.

**Comment by Grawl** [comment]
@ramya-rao-a it's not handy to run a command just to replace a few quotes :(

**Comment by ramya-rao-a** [comment]
Doing so without a command would change existing behavior which all current users are used to.

The existing feature here is _add_ enclosing selected text with whatever is defined as `surroundingPairs` for each language. For eg: See https://github.com/Microsoft/vscode/blob/master/extensions/css/language-configuration.json#L17

What is being asked here is to _change_ existing surrounding chars which is a whole new feature and is a good extension candidate.

cc @alexandrudima @rebornix for more thoughts

**Comment by egamma** [comment]
Agree with @ramamurthynagaraj this can be provided through an extension.

**Comment by praveenraj1987** [comment]
@egamma I think you meant, @ramya-rao-a
