### ISSUE TITLE
[Feature request] UI changes

### ISSUE THREAD

**Issue by ranonn** [microsoft/vscode#87404]
It would be nice to have a Christmas related theme, bringing the Christmas spirit into our souls.
I suggest some Christmas hats on the icons, also a few Christmas trees won't hurt

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
