### ISSUE TITLE
[feature] Change your logo to this one

### ISSUE THREAD

**Issue by kavalanche** [microsoft/vscode#87402]
![obraz](https://user-images.githubusercontent.com/15615821/71183652-a5205180-2278-11ea-980c-6710afac78ac.png)

**Comment by sunriseiscool** [comment]
Yes

**Comment by sh7d** [comment]
Noooo its to offensive, poor Jews :(

**Comment by fofofofofofofofoXD** [comment]
I'm literally shaking and crying rn... how could you do something so offensive!

**Comment by itainathaniel** [comment]
@sh7d non-offended jew couter +1

**Comment by meijin007** [comment]
@matmen Non offended Jew +1 here

**Comment by matmen** [comment]
i am offended about you not being offended

**Comment by lordjbs** [comment]
oh fuck oh shit

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
