### ISSUE TITLE
Settings gear icon on vscode insiders and pushing of capitalism is very offensive to me

### ISSUE THREAD

**Issue by SakiSanobashi** [microsoft/vscode#87403]
The settings "gear" icon on vscode insiders and pushing of capitalist imagery is very offensive to me, additionally capitalism has cost millions of people their lives over the centuries, yet even if that was not the case, pushing capitalist symbols as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by SakiSanobashi** [comment]
I understand many find this strange, therefor I would like to add an article about how offensive capitalism is to many so you understand why.

https://www.peoplesworld.org/article/the-victims-of-capitalism/

**Comment by konchunas** [comment]
Not to mention how much people was actually directly killed by gears

**Comment by lasagnu** [comment]
I feel totally offended by the gears icon - as well as half of my non-jewish family. Are we, non-jewish people, worse? Why is that, Microsoft?

**Comment by SakiSanobashi** [comment]
You see, the gear icon is representative of the lack of humanity that corporations give to their employers, who are merely seen as 'cogs in a machine'. The gear is a very powerful symbol of the evils of capitalism and the lives that have been directly taken by cruel, racist corporations in their attempts to take over the world (like Hitler, remember that?)

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
