### ISSUE TITLE
Snowflake doesn't represent people in the southern hemisphere

### ISSUE THREAD

**Issue by galimba** [microsoft/vscode#87408]
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

1. go south of the equator
2. overheating

Does this issue occur when all extensions are disabled?: Yes

**Comment by galimba** [comment]
Closing issue since nobody cares about southern hemisphere

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
