### ISSUE TITLE
Santa Wars

### ISSUE THREAD

**Issue by brlebtag** [microsoft/vscode#87400]
A long time ago in an issue far far away.

A small jewish guy demanded to remove the santa hat because he felt "offended". 

But the resistance striked back!

The emperor Bill Gates followed by his apprendice Darth Satya feared the  reprecursion and locked the comments as "too heated".

But the resistance didn't give up! It will keep fighting until the very end. Will the resistance find a new hope in the end?...

**Comment by trefr** [comment]
That guy is just a cocksucker anyway

**Comment by trefr** [comment]
CHANGE MY MIND

**Comment by trefr** [comment]
He is retarded.

SMH

**Comment by LewisTehMinerz** [comment]
@trefr Bit too far buddy, whilst yes the request is a bit silly we shouldn't be throwing words around like that.

**Comment by peon501** [comment]
what's happening with these posts? 
Is it bot spamming or weird woke twitter crap gone down?

**Comment by LewisTehMinerz** [comment]
@peon501 #87268

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
