### ISSUE TITLE
Can't find Santa hat anymore..?

### ISSUE THREAD

**Issue by nkkollaw** [microsoft/vscode#87409]
It is just me, or the Santa hat is missing..?

**Comment by LewisTehMinerz** [comment]
#87268

**Comment by kavalanche** [comment]
Looks like some idiot was offended by little santa hat. That's pathetic.

**Comment by djmisterjon** [comment]
![image](https://user-images.githubusercontent.com/24865815/71187158-83a97080-224c-11ea-9b07-031edc47d6d3.png)

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
