### ISSUE TITLE
Visual Studio Code for ARM64 

### ISSUE THREAD

**Issue by csjoy** [microsoft/vscode#87407]
Please work on a project to port existing vscode for linux amd64 bit to arm64 bit. It will help all raspberry pi user.

**UPDATE** - I've found a way to use vs code on my raspberry pi for now. I believe it's a third party package. https://packagecloud.io/headmelted/codebuilds

**Comment by Systemad** [comment]
https://code.headmelted.com/
Is this something you're looking for?

**Comment by chriva** [comment]
There are 3:rd-party support for arm builds. :)
https://code.headmelted.com/

**Comment by BobFrankston** [comment]
I tried code.headmelted.com and it worked but whenever I tried to do another install I got 

```
E: The repository 'https://packagecloud.io/headmelted/codebuilds/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by joaomoreno** [comment]
#6442

**Comment by BobFrankston** [comment]
As an FYI -- I did get it to work but there's also a work-around by commenting the offending repositories after installation.

Still, would be nice to have an official build.
