### ISSUE TITLE
Don't add "santa hat" as it's really a coca-cola's santa and I like pepsi more

### ISSUE THREAD

**Issue by pulka103** [microsoft/vscode#87406]
Knowing that my favourite editor is going with Coca-Cola's symbol would get me sick. It offends me that anyone dare to even mention Coca-Cola while we all know Pepsi is better. Merry Xmas.

**Comment by virgiliu** [comment]
Blue Santa all the way!

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
