### ISSUE TITLE
How can I references too many projects (folders) in Visual Studio Code?

### ISSUE THREAD

**Issue by HamedFathi** [Microsoft/vscode#8741]
- VSCode Version: 1.2.1
- OS Version: Windows,Mac

When I used Visual Studio, I had two files format solution (.sln) and project (.csproj).

I want to know in Visual Code

How can I have solution (Root folder) and many projects (sub folders) with dependencies to itself ?

How can I set folders dependencies ? (I want to reference folders together)

please guide me or introduce a source that How can I add many related project with their dependencies in Visual Code.

**Comment by joaomoreno** [comment]
@jrieken Can you provide some guidance here?

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#527
