### ISSUE TITLE
is it christmas already?

### ISSUE THREAD

**Issue by an0o0bis** [microsoft/vscode#87412]
![image](https://user-images.githubusercontent.com/16511906/71185797-6ab8b380-227c-11ea-81bc-a46936804c27.png)

don't bow down to fuarking sjw's.

**Comment by asc11cat** [comment]
![651402326829039637](https://user-images.githubusercontent.com/47783525/71186682-4c57b580-2286-11ea-8996-62577ca26860.png)

**Comment by charlesamacon** [comment]
How do you delete someone else's issues?

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
