### ISSUE TITLE
The existence of vscode is very offensive to me

### ISSUE THREAD

**Issue by SakiSanobashi** [microsoft/vscode#87415]
As we all know, the alt-right uses programming as hate speech to cyberbully innocent journalists. Remember when they told journalists who were laid off to 'learn to code'? Clearly, if actual Nazis want you to "learn to code", then coding is an inherently offensive concept, and any and all programs and the companies that produce these programs need to be shut down as soon as possible.

Additional reading on the issue that most certainly needs to be considered.
https://knowyourmeme.com/memes/learn-to-code

**Comment by ayylmaoooooo** [comment]
coding is cancelled

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
