### ISSUE TITLE
Color themes are offensive to blind (and colorblind) users

### ISSUE THREAD

**Issue by SakiSanobashi** [microsoft/vscode#87411]
While I am sighted myself, it is extremely unfair and demeaning to those that are not. Why should it be acceptable in 2019 to give exclusive features to people who are abled, and bar disabled people from having the same experience?

I propose that either the option to select different color themes be removed (especially the dark theme, as cultural appropriation of people of color is just not cool), or, alternatively, provide a native text-to-speech interpreter with multiple voices to choose from (so that the blind and colorblind have the same number of QoL options as the sighted, as should be fair.)

**Comment by prawnsalad** [comment]
Just to tack onto this, please remove the blue colour as I find it offensive to harm millions of peoples eyes all year round. Please remove it immediately and make it your top priority.

Additional reading on the issue that most certainly needs to be considered, https://www.allaboutvision.com/en-gb/digital-eye-strain/blue-light/

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
