### ISSUE TITLE
VS Code display issue when using custom title bar, multiple monitors, different text size scaling

### ISSUE THREAD

**Issue by delie** [microsoft/vscode#87416]
Issue Type: <b>Bug</b>

When using VS Code with a custom title bar, and using a primary monitor with a vastly different text/app size scaling setting to a second monitor, VS Code does not display the title bar/status bar correctly and the content within them is cropped.  

To reproduce - open VS code on a 4k primary monitor with 350% text scaling (monitor display settings), now maximize the window and it fits correctly.  However, drag the window to a 1080p monitor with 125% scaling and again maximize the window, and note how the title bar/status bar are now being cropped.  

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.1
ng-template|Ang|0.900.3
bracket-pair-colorizer-2|Coe|0.0.29
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.17.0
angular2-switcher|inf|0.2.0
angular-essentials|joh|0.6.3
Angular2|joh|8.3.0
theme-monokai-pro-vscode|mon|1.1.14
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
angular2-inline|nat|0.0.17
angular-console|nrw|10.0.0
vscode-jest|Ort|3.0.2
material-icon-theme|PKi|3.9.2
vscodeintellicode|Vis|1.2.0
change-case|wma|1.0.0

</details>

**Comment by deepak1556** [comment]
Should be fixed in our latest insiders https://code.visualstudio.com/insiders

/duplicate https://github.com/microsoft/vscode/issues/85592
