### ISSUE TITLE
Santa hat removal was the wrong thing to do.

### ISSUE THREAD

**Issue by lnx64** [microsoft/vscode#87417]
First of all, I understand these days everyone is as sensitive as a staph infection.  Unfortunately, you will not be able to cater to everyone, but I feel that removing a Santa hat because someone was _offended_ is just wrong.  We've hit an all time low here in terms of "catering to the snowflakes", and I don't mean that as a derogatory term, but more so because it's **WINTER TIME**.

Seeing the responses is quite clear, such quick hasty decision to actually remove the hat was very much the wrong decision, and it reminds me of a funny scene from Monty Python and the Holy Grail: https://www.youtube.com/watch?v=ZtYU87QNjPw

I get it, some things are indeed offensive, others are not.  But VLC never had such complaints about the Santa hat on the traffic cone icon during the season.  Clearly it's a non issue, and indeed Christian Shiffer (ironic name?) is just a troll, you need not react to his post, nor make such rash decisions like removing a silly Santa hat.

I don't follow specific religions, but I wouldn't stop someone from celebrating what they love.  I do indeed love Christmas, I have Jewish friends whom aren't offended by this at all, and even celebrate it as well because.....it's just fun.  Clearly Christian got too much coal under his nonexistent tree.  Once again, not being derogatory, but I am indeed fairly upset at your rash decisions.

With that said, 🎅.

**Comment by nkkollaw** [comment]
I find this issue pretty offensive, to be honest.

**Comment by J0s3f** [comment]
> I find this issue pretty offensive, to be honest.

I find you being offended pretty offensive, to be honest.

**Comment by nfp16113** [comment]
Bring back Santa! If it's offensive for someone he doesn't have to use VSC. Simple!

**Comment by trefr** [comment]
Bros when you're gonna lick pussy ?

**Comment by ranonn** [comment]
The only reason I kept using VSC was because of that hat. Guess I don't have to anymore

**Comment by trefr** [comment]
Use Atom you jewish bruhs

**Comment by virgiliu** [comment]
Microsoft needs to do some training on how to spot trolls. Clearly MS is new to the internet and they're easily baited.

**Comment by trefr** [comment]
Imagine if a muslim opened the same issue...

**Comment by trefr** [comment]
reference to #87420

**Comment by lnx64** [comment]
> 
> 
> reference to #87420

Oh my lord.  Wait, I mean oh my **goodness**.

**Comment by Inquis1t0r** [comment]
That was Bill's hat tho. 
![billgates](https://user-images.githubusercontent.com/3273347/71189630-6cd24080-2283-11ea-8702-504474327591.jpg)

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by shymi** [comment]
> Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

If this issue is "unactionable or unrelated to the goals of this project", how was the original one from Christian-Schiffer(who deleted/renamed his original account) actionable or related? Looks like Micro$oft is comfortable being racist against more widespread views.
