### ISSUE TITLE
VSCode not working with Path variable set by installer

### ISSUE THREAD

**Issue by luitzenhietkamp** [microsoft/vscode#87413]
- VSCode Version: 1.41.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Download the installer and install VSCode for the first time
2. Choose the option to let the installer add VSCode to the path
3. Open a folder with Windows Explorer
4. Type `code .` in the address bar.
5. Windows will launch the default browser and search the web for ` code .`  (exact behaviour depending on installed browser).

The installer adds `C:\Program Files\Microsoft VS Code\bin` to the Path variable. Taking of `\bin` and changing the Path variable entry to `C:\Program Files\Microsoft VS Code` fixes the issue.

See also discussion [here](https://www.reddit.com/r/vscode/comments/eca1c7/path_variable_from_vscode_not_working_on_windows/)

Does this issue occur when all extensions are disabled?: Have not checked.

**Comment by nkkollaw** [comment]
Is this caused by Santa hat missing..?

**Comment by joaomoreno** [comment]
We add `bin` to the PATH since that's where Code's CLI script is. If you take `\bin` out you lose support to run `code --version` and other CLI flags from the command line.

We simply choose not to support typing `code .` in the address bar of the Windows Explorer.
