### ISSUE TITLE
Visual studio code logo is offensive to me

### ISSUE THREAD

**Issue by madis** [microsoft/vscode#87419]
The current logo of vscode reminds me of a fish which is a religious symbol and is very offensive to me, additionally christianity has cost millions of lives over the centuries, yet even if that was not the case, pushing religious symbols as part of a product design is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

Related: https://github.com/microsoft/vscode/issues/87268

![Screen Shot 2019-12-19 at 16 52 17](https://user-images.githubusercontent.com/674621/71187770-026bd100-2280-11ea-9eb7-a23a219e645e.jpg)
![1200px-Visual_Studio_Code_1 35_icon svg](https://user-images.githubusercontent.com/674621/71187801-14e60a80-2280-11ea-94c9-e56576f76baf.png)

Additional reading on the issue that most certainly needs to be considered. https://en.wikipedia.org/wiki/Ichthys https://en.wikipedia.org/wiki/Christianity_and_violence

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by IRCraziestTaxi** [comment]
But #87268 was actionable and related to the goals of the project? lmao

**Comment by SRGOM** [comment]
I am beginning to think that Microsoft discriminated against minorities

**Comment by parth181195** [comment]
Guys this is not discrimination. If you link any animal with a logo and make it religious thing then everything will seem religious to you.please be open minded.and please think twice before submitting issue like this.vs code is open source project and is supported by Microsoft there are many contributors who dose not work for Microsoft and working on this project and it is a Wonderfull software that we are getting free of cost and I really appreciate work of all the contributors and thank them for making vs code awesome.

**Comment by kingserpent** [comment]
> The current logo of vscode reminds me of a fish which is a religious symbol and is very offensive to me, additionally christianity has cost millions of lives over the centuries, yet even if that was not the case, pushing religious symbols as part of a product design is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.
> 
> Related: #87268
> 
> ![Screen Shot 2019-12-19 at 16 52 17](https://user-images.githubusercontent.com/674621/71187770-026bd100-2280-11ea-9eb7-a23a219e645e.jpg)
> ![1200px-Visual_Studio_Code_1 35_icon svg](https://user-images.githubusercontent.com/674621/71187801-14e60a80-2280-11ea-94c9-e56576f76baf.png)
> 
> Additional reading on the issue that most certainly needs to be considered. https://en.wikipedia.org/wiki/Ichthys https://en.wikipedia.org/wiki/Christianity_and_violence

What a joke.

**Comment by kenneth-rebello** [comment]
> > The current logo of vscode reminds me of a fish which is a religious symbol and is very offensive to me, additionally christianity has cost millions of lives over the centuries, yet even if that was not the case, pushing religious symbols as part of a product design is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.
> > Related: #87268
> > ![Screen Shot 2019-12-19 at 16 52 17](https://user-images.githubusercontent.com/674621/71187770-026bd100-2280-11ea-9eb7-a23a219e645e.jpg)
> > ![1200px-Visual_Studio_Code_1 35_icon svg](https://user-images.githubusercontent.com/674621/71187801-14e60a80-2280-11ea-94c9-e56576f76baf.png)
> > Additional reading on the issue that most certainly needs to be considered. https://en.wikipedia.org/wiki/Ichthys https://en.wikipedia.org/wiki/Christianity_and_violence
> 
> What a joke.

It indeed is. Check out #87268

**Comment by parth181195** [comment]
#87268 is totally different Then this one.this issue is trying to make something out of nothing

**Comment by M1rceaDogaru** [comment]
Please feel free to replace the current logo with a snowflake.

**Comment by Shadowleo85** [comment]
Honestly I'm just here to say. Stop trying to find any excuse to be offended... Sheesh all these whiney baby grownups that feel entitled and easily offended by anything they seem as offensive. World has gotten way to soft with all this wahhhhh, I feel offended, you should appease me by changing it. Stop that and grow up

**Comment by EthanRutherford** [comment]
Noting for future readers: this issue is satirical.

**Comment by Shadowleo85** [comment]
Noted. Thank you I hoped it wasn't legit

**Comment by seraph-fawkes** [comment]
> Noting for future readers: this issue is satirical.

However this issue takes on serious topic of symbolism. Can we also ban the dollar sign, as many millions died because of money and greed?

**Comment by parth181195** [comment]
> Honestly I'm just here to say. Stop trying to find any excuse to be offended... Sheesh all these whiney baby grownups that feel entitled and easily offended by anything they seem as offensive. World has gotten way to soft with all this wahhhhh, I feel offended, you should appease me by changing it. Stop that and grow up

Well said

**Comment by Weblure** [comment]
I am offended by you being offended by fish, how dare you.

**Comment by asfdfsaf** [comment]
This is white supremacy, pure and simple! Please change this offensive logo.

**Comment by SRGOM** [comment]
> I am offended by you being offended by fish, how dare you.

Womp womp

**Comment by khionu** [comment]
I'd like to suggest to the VS Code team to lock threads like this.

**Comment by NatsumiHB** [comment]
I think if they change it they should change it to the swastika. I, as a Buddhist, am offended by the absence of the VS Code developers showing support for my religion.

**Comment by M1rceaDogaru** [comment]
Why would they show support for any religion? The logo looks nothing like a fish and even if it did by some exagerrated extrapolation it would have nothing to do with the christian symbol.

I'm offended that i'm in the same species as people who get offended over everything.

@devs please lock this issue up, it has gone off rails a long time ago.

**Comment by NatsumiHB** [comment]
> 
> 
> Why would they show support for any religion? The logo looks nothing like a fish and even if it did by some exagerrated extrapolation it would have nothing to do with the christian symbol.
> 
> I'm offended that i'm in the same species as people who get offended over everything.
> 
> @devs please lock this issue up, it has gone off rails a long time ago.

I'm offended that people take this shit seriously instead of seeing it as what it is. It's a troll. A protest against MS for obeying to ONE SINGULAR PERSON who allegedly got offended.

**Comment by hickscorp** [comment]
I'm highly tempted to point out that the blue colour is too much of a "aristocracy" oppression reminder of all the pain my folks went through, but if I did I guess we'd have to close the internet, shops, radio, malls, gaming consoles, decaf packages, female hygiene products, blue jeans and Euronet ATM. Don't even get me started on the Ryanair logo... In the end, because VSCode is opensource, we decided to change it ourself. We used white font on white background with gorgeous white buttons - our productivity went down and someone pointed out that it probably was because it reminded people of some white supremacy - we decided to change everything to red and people called us communists... We're right now AB testing rainbow - I'll let you know how it goes.

**Comment by gabrieltaets** [comment]
I see this as a lesson to be learned by the dev community. If someone might be offended by a temporary change (e.g. Santa Hat), simply allow it to be disabled (i.e. "Opt-out of events" on Appearance settings or something like that). No one gets pissed because of a special snowflake who ruins a nice thing for everyone else.

**Comment by rodrigofbm** [comment]
Please remove this repository from GitHub. "Hub" reminds me of "PornHub" and is very offensive to me. I'm a virgin.

**Comment by rodrigofbm** [comment]
Please remove this repository from GitHub. "Hub" reminds me of "PornHub" and is very offensive to me. I'm a virgin. Additionally PornHub has cost millions of lives over the years.

**Comment by lucaspontoexe** [comment]
see https://vscodium.com

the same VSCode, but without the official branding. 

_ends discussion_

**Comment by SRGOM** [comment]
lol vscodium users are the biggest losers on earth. If you really hate microsoft so much why use their product?

**Comment by john-cj** [comment]
Why do we have BLACK theme as the default one? The user must have a choice!!!111111

Seriously, stop listening to "offended" people. If you are offended - don't use the software. The "offended" people are just the ones who have too many times and too little real problems.

**Comment by RafaelTuber** [comment]
![image](https://user-images.githubusercontent.com/35770666/71325728-a8f9e100-24cf-11ea-9809-e0b5cd3d7dc3.png)

o mais top foi a resposta do bot kkkk ele queria dizer isso >> 

Obrigado por enviar esta reclamação. Verifique também que esse comentario e inutil como essas a baixo e por esse motivo estamos vinculando elas nos topicos de assuntos sem conteudo que não contribui para nossa cominidade:

Chapéu de Papai Noel para iniciantes vscode e promoção da religião é muito ofensivo para mim (# 87268)
O ícone de engrenagem nas configurações de insiders do vscode e a pressão do capitalismo são muito ofensivos para mim (# 87403)

**Comment by iiagodias** [comment]
> Please feel free to replace the current logo with a snowflake.


But snow flakes reminds me of a Christmas, Christmas reminds me of Santa, Santa reminds me of a Coke, Coke has a pact, this is against my religion.

**Comment by davitabosa12** [comment]
It's clearly a Möbius Strip

**Comment by konrad-bak** [comment]
I find writing offensive. The invention of writing is EXACTLY what made millions of people illiterate. I will not stop writing about this until it's banned.

**Comment by konrad-bak** [comment]
> I'm highly tempted to point out that the blue colour is too much of a "aristocracy" oppression reminder of all the pain my folks went through, but if I did I guess we'd have to close the internet, shops, radio, malls, gaming consoles, decaf packages, female hygiene products, blue jeans and Euronet ATM. Don't even get me started on the Ryanair logo... In the end, because VSCode is opensource, we decided to change it ourself. We used white font on white background with gorgeous white buttons - our productivity went down and someone pointed out that it probably was because it reminded people of some white supremacy - we decided to change everything to red and people called us communists... We're right now AB testing rainbow - I'll let you know how it goes.

10/10 make it randomly play drag queen shows in the corner to boost productivity

**Comment by madis** [comment]
> But #87268 was actionable and related to the goals of the project? lmao

Exactly. Satirical? 100%, at least as relevant than the original santa hat issue 100%

**Comment by madis** [comment]
> Honestly I'm just here to say. Stop trying to find any excuse to be offended... Sheesh all these whiney baby grownups that feel entitled and easily offended by anything they seem as offensive. World has gotten way to soft with all this wahhhhh, I feel offended, you should appease me by changing it. Stop that and grow up

Read https://github.com/microsoft/vscode/issues/87419#issuecomment-569064216
