### ISSUE TITLE
Snow icon on vscode insiders and pushing of weather is very offensive to me 

### ISSUE THREAD

**Issue by 810** [microsoft/vscode#87410]
The Snow icon on vscode insiders and pushing of weather is very offensive to me, additionally xmas snow has cost billons of snowflakes their lives over the centuries, yet even if that was not the case, pushing weather symbols as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a tsunami.

Version: 1.42.0-insider (user setup)
issue: #87268
OS: Windows 10 x64 10.0.19536.1000

Steps to Reproduce:

Install latest build of insiders.
Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered. https://www.knmi.nl/nederland-nu/klimatologie/lijsten/wittekerst

**Comment by galimba** [comment]
snowflake suggests Microsoft does not believe in global warming. Shun the nonbelievers!

**Comment by Reynergodoy** [comment]
You forgot to count the Inuktituts that had their lives taken in the snow, or even people from up North Europe that die from fever and the snow itself. Not counting Napoleon's men in their campaign to Russia.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
