### ISSUE TITLE
I'm Buddhist and I'm offended

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [microsoft/vscode#87428]
The gear icon in VScode resembles the religious symbol of Buddhism, the Dharmachakra and I find it very offensive.

![rsz_aps840x830smalltransparent-pad1000x1000f8f8f8u2](https://user-images.githubusercontent.com/2551877/71188771-97ce8b80-22a7-11ea-9989-6ac38f67695c.jpg)

Please remove it. Or at least cover it with a hat or something.

**Comment by madis** [comment]
I agree. 
Related: 
  - https://github.com/microsoft/vscode/issues/87268
  - https://github.com/microsoft/vscode/issues/87419

**Comment by hanseul1795** [comment]
perfect solution is to cover it with a `SANTA` hat

**Comment by lnx64** [comment]
Boatymcboatface might be offended too, looks like a boat steering wheel.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by scottwalstead** [comment]
I find the word happy offensive. Not everyone is happy during the holiday season. Could we change that from `Happy Coding!` to `Coding!` please. Thanks in advance!

**Comment by MichaelX99** [comment]
I am offended that everyone is offended.  I feel like I am being personally attacked and would like for people to stop being offended since it goes against my personal beliefs.

**Comment by onix** [comment]
All this shit is killing creativity in 2k19... So sad 🙁

**Comment by EzitoKo** [comment]
Ok boomer

**Comment by mdelong42** [comment]
The symbol also represents an old ship steelering wheel..... it's okay. The symbol also known as a t in English also represents a cross in Christianity, where can I submit a request to remove

**Comment by SRGOM** [comment]
Jude observe do nothing

**Comment by gleeny** [comment]
how is this in my feed what
![Screenshot_20191221-111732~2](https://user-images.githubusercontent.com/10573728/71306663-9bffc380-23e3-11ea-85a7-402177c2d18e.png)

**Comment by rameshxghimire** [comment]
No worries, nothing lasts forever!

**Comment by remenyo** [comment]
Make everything flagged as offensive optional, but also default.
This should make everyone happy.

**Comment by jpescada** [comment]
> how is this in my feed what
> ![Screenshot_20191221-111732~2](https://user-images.githubusercontent.com/10573728/71306663-9bffc380-23e3-11ea-85a7-402177c2d18e.png)

Same reason I ended up here. Wat? (Sorry in advance as "wat" might be offensive to someone, somewhere)

**Comment by himanshu010** [comment]
I will work on this issue

**Comment by meSubhoKarma** [comment]
@Isuru-Nanayakkara 😂😂😂

**Comment by camstuart** [comment]
Replace it with nothing, and our Zen brothers and sisters will become offended

**Comment by bostrowski13** [comment]
Is therea bounty on this?  Will work for non-denominational christwanzakaule presents.

**Comment by CrEaTiiOn187** [comment]
> how is this in my feed what
> ![Screenshot_20191221-111732~2](https://user-images.githubusercontent.com/10573728/71306663-9bffc380-23e3-11ea-85a7-402177c2d18e.png)

Just means Google agrees that what they've done to our precious Santa hat is bullshit.

**Comment by AlexFlipnote** [comment]
Google feed brought me here, I'm not disappointed.

**Comment by AlexandrosD** [comment]
Dear vscode team, I hope it is quite apparent now how ridiculous the claim of @Christian-Schiffer, about the santa hat was. But even more ridiculous was the fact that you complied to his arbitrary request. In fact, your actions are as offensive to me as the swastika.

**Comment by danger89** [comment]
Atleast I'm not the only one that get this item in the Google News timeline..

**Comment by UddeshJain** [comment]
I got here because it appeared in my Google Feed. Why is this issue closed? And what's this icon for?

**Comment by PepperTeasdale** [comment]
The icon kinda looks like a ❄️ to me...

**Comment by CQH-2020** [comment]
Im offended by this issue

**Comment by UtkarshBhatthere** [comment]
Guys, I am here just for the comments! (Keep em Coming.) 😂

**Comment by mdelong42** [comment]
Does this expose Google's algorithm as promoting liberal propaganda.

**Comment by asfdfsaf** [comment]
I am offended that people are offended by things.

**Comment by AndrewChacon** [comment]
yall are buggin.

**Comment by mtasir** [comment]
> The gear icon in VScode resembles the religious symbol of Buddhism, the Dharmachakra and I find it very offensive.
> 
> ![rsz_aps840x830smalltransparent-pad1000x1000f8f8f8u2](https://user-images.githubusercontent.com/2551877/71188771-97ce8b80-22a7-11ea-9989-6ac38f67695c.jpg)
> 
> Please remove it. Or at least cover it with a hat or something.

Basically it's the captain's wheel ..

**Comment by catalintomescu** [comment]
For God's sake get over it, it's a captain's wheel! Do you have anything else of value to contribute to open source community?

**Comment by himanshu010** [comment]
dalai lama to bhai he apna, bol to sahi symbol badalwa doun.

**Comment by kevinmu17** [comment]
You kidding me right? These discussions do not belong here on GitHub, contribute with code but don't start these kinds of bull here, if you chose to be offended go make a complaint email.

**Comment by konrad-bak** [comment]
I find writing offensive. The invention of writing is EXACTLY what made millions of people illiterate. I will not stop writing about this until it's banned.

**Comment by higherkinded** [comment]
@konrad-bak same here. Write until it's against the law to write.

**Comment by gleeny** [comment]
uh oh... #87537 too
![Screenshot_20191223-132450~2](https://user-images.githubusercontent.com/10573728/71357994-b83c6580-2587-11ea-92e4-4dae07f64ce7.png)

**Comment by RenFontes** [comment]
Isn't buddhism all in for forgiveness and letting go?

🙄

**Comment by AzureWolf** [comment]
I'm so happy to be a part of this community. I love you all.

Merry Christmas everyone!

**Comment by TeddyAlbina** [comment]
Oo wokesoft close the thread 😱😱😅😅

**Comment by jycr753** [comment]
Is a free software, if you are offended is your problem and don't use, is about software not your feelings.

**Comment by douglasg14b** [comment]
> Is a free software, if you are offended is your problem and don't use, is about software not your feelings.

@jycr753 This is a joke making fun of MS for pandering to every Tom, Dick, and Harry that gets offended by the most inconceivable things. Such as someone being upset about the Santa hat, so they removed it.

**Comment by jycr753** [comment]
> > Is a free software, if you are offended is your problem and don't use, is about software not your feelings.
> 
> @jycr753 This is a joke making fun of MS for pandering to every Tom, Dick, and Harry that gets offended by the most inconceivable things. Such as some snowflake being upset about the Santa hat, so they removed it to pander to them.
> 
> It's riding on the growing level of unrest over blind pandering to "offended" people, actively making things worse or less enjoyable for many just to serve the unconformed feelings of a single individual.

What! Amazing the Microsoft remove it just for some "feelings"

**Comment by windson** [comment]
Meanwhile in another world, this was observed. 
![Kubernetes_Logo](https://user-images.githubusercontent.com/1826682/71424523-5c252e80-26b8-11ea-8505-deb1662d737a.png)

**Comment by tadanderson** [comment]
I would recommend watching this https://youtu.be/ceS_jkKjIgo
