### ISSUE TITLE
The gear symbol on vscode insiders and pushing of religion is very offensive to me

### ISSUE THREAD

**Issue by PashaMasalkin** [microsoft/vscode#87423]
The vscode insider gear symbol are very offensive to me, you don’t honor the machine of God, Omnissia, and the Emperor.
Do not obey the Universal Laws, but use it.
With this symbol, billions of techno priests and adherents went to death. The promotion of this religious symbol as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. For me it is almost as insulting as using the sun sign with Hitler.

Version: 1.42.0-insider (user setup)
Commit: 26f5dfc
Date: 2019-12-18T10:34:34.277Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

    Install latest build of insiders.

Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered. https://pikabu.ru/story/microsoft_ubrala_shapochku_santyi_iz_vscode_tk_ona_oskorblyaet_chuvstva_evreev_7114488#comments

**Comment by jimbali** [comment]
This is offensive to survivors of the gear wars

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by asfdfsaf** [comment]
The gear is an oppressive symbol of the industrial revolution that represents a pre-cursor to capitalism, all of which are imperialist systems of white supremacy. I think the gear should be removed. You can do better, Microsoft!
