### ISSUE TITLE
Tool is not in accordance with my beliefs

### ISSUE THREAD

**Issue by jaironalves** [microsoft/vscode#87425]
- VSCode Version: all
- OS Version: al

Hello, I live on planet earth with billions of people, but I can't accept that there are projects or people with different cultures or religions than mine. I would like the company to modify the tool to put a reminder of my birthday and my wedding anniversary. Increment the photo of my dogs on the icon.

It's still unacceptable to have companies that I don't control.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by Roen00** [comment]
Why is it closed? @chrisdias why did you offend him? Do YOU think he has no feelings?
Look how many people agree with this idea.
How dare you!
