### ISSUE TITLE
What gives you the right to "fix" a bug? What about the feelings of the bug?

### ISSUE THREAD

**Issue by SakiSanobashi** [microsoft/vscode#87421]
If a bug wishes to be a bug, that is its own prerogative and you nor anybody else has any right or reason to force it to not be a bug. This is literally oppression.

**Comment by MACIEKBAKI** [comment]
Microsoft has been fixing bugs for years never even bothering to ask the bug about its feelings. This is offensive.

**Comment by Isuru-Nanayakkara** [comment]
+1 Bug lives matter!

**Comment by ranonn** [comment]
They should change the label "bug" to "surprise feature"
The term bug is clearly offensive

**Comment by MACIEKBAKI** [comment]
@ranonn I fully agree with you. We should make a separate issue for this.

**Comment by MACIEKBAKI** [comment]
In fact, I'll make one

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
