### ISSUE TITLE
Santa Wars

### ISSUE THREAD

**Issue by vgarleanu** [microsoft/vscode#87426]
And this ladies and gentlemen, is how the Grinch stole Christmas.

**Comment by SakiSanobashi** [comment]
a long time ago
in a repo far far away....

**Comment by trefr** [comment]
... a jew got insulted by goddamn hat

**Comment by ThanosPapathanasiou** [comment]
Guys, let's just split the difference and add a Santana hat. :)

**Comment by SakiSanobashi** [comment]
A Satania hat, you say?

![image](https://user-images.githubusercontent.com/59058841/71188883-cd478a80-224f-11ea-8271-9259d5b6b431.png)

**Comment by pancirno** [comment]
![EnergeticAcidicBushsqueaker-size_restricted](https://user-images.githubusercontent.com/6917316/71189042-73ac8380-2282-11ea-8785-8539b492b15c.gif)

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by asfdfsaf** [comment]
Thank god for political correctness. Imagine all those people who could have been offended by the Santa hat! It's too bad that the ones who actually liked it will be disappointed, but their disappointment is a small price to pay to prevent the offense of those who find Santa hats offensive - who I assume to be the majority.
