### ISSUE TITLE
Increase defense spending of the german military to 4% or 5% of gdp

### ISSUE THREAD

**Issue by nkyokoo** [microsoft/vscode#87427]
The current state of germany's army is really offensive to us danes. It feels like even the bundespolizei could defeat bundeswehr. 

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by trefr** [comment]
Don't be racist my man

**Comment by SakiSanobashi** [comment]
do you want a fourth reich, because this is how you get a fourth reich

**Comment by trefr** [comment]
I want a jew reich
