### ISSUE TITLE
Term "Bug" is offensive to bugs.

### ISSUE THREAD

**Issue by MACIEKBAKI** [microsoft/vscode#87424]
I, and many others, find the use of the term "bug" to be offensive. You have no idea if the "bug" you are reffering to would like to be called a "bug", which is comparing them to an insect - unwanted, unneeded, and maybe worse, wants to be called a "bug". You should instead use the term _"surprise feature"_ as a less offensive term for describing such things.

**Comment by trefr** [comment]
Is bug another way of insulting jews ?

**Comment by ranonn** [comment]
As Bob Ross said, they are happy little accidents. Putting such a strong and derogatory label is just wrong.

**Comment by pulka103** [comment]
SURPRISE FEATURE XDDDDDDD I AM DYING XDDDDDD

**Comment by MACIEKBAKI** [comment]
@ranonn Very wise words of a very wise man. It is sad he is no longer with us.

**Comment by MACIEKBAKI** [comment]
@trefr I believe it is

**Comment by BurakDev** [comment]
It's not a bug, it's a feature.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
