### ISSUE TITLE
I'm from Siberia, it's cold over here. Where my hat?

### ISSUE THREAD

**Issue by RianAshes** [microsoft/vscode#87437]
Since I'm from Siberia I really, really need this warm red hat. Or I can lost my ears, ill by pneumonia or even die. Why you so hate me, Microsoft?

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
