### ISSUE TITLE
surprise feature - a headpiece of Kriss Kringle is missing from the program that controlls display in VScode

### ISSUE THREAD

**Issue by lasagnu** [microsoft/vscode#87431]
Recently I have noticed that surprise feature has made its way to the production - a headpiece of Kriss Kringle is missing!

- VSCode Version: newest
- OS Version: Win10 1909

Steps to Reproduce:

1. Open VSCode
2. See missing headpiece

Does this issue occur when all extensions are disabled?: Yes

**Comment by MACIEKBAKI** [comment]
I am very happy you do not discriminate against surprise features and use the correct terms for them

**Comment by pulka103** [comment]
I wish surprise feature will stay forever within this repo. It's actually awesome

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
