### ISSUE TITLE
output  'show enabled extensions' as plain text

### ISSUE THREAD

**Issue by zachvalenta** [microsoft/vscode#87433]
IMO this would be helfpful for version control. At present I use the following:

```sh
alias vscfr="ls ~/.vscode/extensions/ > $DOTFILES_DIR/vsc-pkg.txt"
```

as basic version control for extensions, but it'd be useful to know which extensions are enabled as well. 

Thinking VS Code could perhaps write that in a `.json` file somewhere in the `extensions` directory.

**Comment by trefr** [comment]
Is this santa playing games ?

**Comment by sandy081** [comment]
There is a command line option to list all extensions `--list-extensions`. This will show you all installed extensions.
