### ISSUE TITLE
cannot delte some folder/files in work place after VS code opened.

### ISSUE THREAD

**Issue by ywmail** [Microsoft/vscode#8743]
- VSCode Version:1.2.1
- OS Version:Windows 7 Professional 64bit
- Git Version:2.9.0.windows.1

Steps to Reproduce:

1. open my work space, i see the process info like this:
![1](https://cloud.githubusercontent.com/assets/15505291/16571312/692507b8-428c-11e6-830f-55c1f8b000f5.png)
as you can see, no process opens the folder.

2. Click the Git Icon on the left navigator, and open a changed file to see the changes on index or stage a file or other git operations, then i see another two code process actived, and they're handling the angular folder result that the folder can't deleted or renamed.
![2](https://cloud.githubusercontent.com/assets/15505291/16571448/fc4a2170-428e-11e6-8905-eaf15710d1b3.png)

**Comment by bpasero** [comment]
@ywmail is this using typescript?

**Comment by ywmail** [comment]
@bpasero Yes, this is a typescript project, forked from angular2-webpack-starter, here is the `settings.json`
`// Place your settings in this file to overwrite default and user settings.
{
    "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        "build/": true,
        "dist/": true,
        "bin/": true,
        "karma/": true,
        "r/": true,
        "reports/": true,
        "scripts/": true,
        "runtimeWindows/": true,
        "runtimeLinux64/": true,
        "**/node_modules": true,
        "documentation/":true
    },
    "editor.folding": true,
    "html.format.wrapLineLength": 0,
    "html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, script, select, small, span, strong, sub, sup, textarea, tt, var",
    "htmlhint.enable": false,
    "editor.insertSpaces": false,
    "files.eol": "\n",
    "files.trimTrailingWhitespace": true,
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        ".build/**": true,
        "out*/**": true,
        "i18n/**": true,
        "extensions/**/out/**": true
    }
}`

here is the `tsconfig.json`:

`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true
  },
  "exclude": [
    "node_modules",
    "server"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
`

**Comment by ywmail** [comment]
The file structure is like this:
```
- .git
- .github
- .vscode
- config
- node_modules
- server
	-- data
	-- models
	-- node_modules
	-- routes
	-- typings
	-- views
	-- app.js
	-- jsconfig.json
	-- package.json
- src
- typings
- package.json
- tsconfig.json
- ...
```
Pls note that I have a `server` in the root folder which contains another node_modules foler.

**Comment by dbaeumer** [comment]
This is a problem of the tsserver can gets addressed with the next TS update. For details pls see https://github.com/Microsoft/TypeScript/issues/7762
