### ISSUE TITLE
Please remove white theme since IT could be offensive to non causasian people

### ISSUE THREAD

**Issue by tomaszgrabowski** [microsoft/vscode#87432]
Please remove white theme from visual theme since IT could be offense for non causasian people.

**Comment by ranonn** [comment]
It's okay to use white themes

**Comment by lnx64** [comment]
Where does that leave red themes?  Wait, that's too Christmas-y.

**Comment by krazyito65** [comment]
white themes will burn your eyes and cause pain to your descendants for thousands of years, better to remove it now before it causes too much trouble.

**Comment by Isuru-Nanayakkara** [comment]
Oh my god, @tomaszgrabowski! You can't just call them white themes!

**Comment by Nekiono** [comment]
I'm offended by the caucasian themes; monokai pro should be the only available one.

**Comment by ranonn** [comment]
@krazyito65 Then they should keep the actual white theme and rename it to Supreme White and add another one but more grayish to protect the eyes

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by asfdfsaf** [comment]
White themes are inherently white supremacist and racist. It's not okay to use light theme. However, you should also not use dark themes as a white person, because that is cultural appropriation. Do better, Microsoft!
