### ISSUE TITLE
I'm a non-programmer and I find "code"offensive

### ISSUE THREAD

**Issue by Mateiadrielrafael** [microsoft/vscode#87435]
The fact this program contains the word "code" in it's name is very offending. Why not remove the word "code" from it's name? I'm sure no other program did this before us!

- VSCode Version: all of em
- OS Version: all of em

Steps to Reproduce:

1. Download vscode
2. Read the title
3. Realise you could've read the title without installing vscode
4. ???
5. Profit!!!

Does this issue occur when all extensions are disabled?: This occurs without even installing vscode

**Comment by trefr** [comment]
reference to #87430

**Comment by trefr** [comment]
IMO the name in the issue is fucking better

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by asfdfsaf** [comment]
I am a trans-disabled person of color and I find it racist that, what seems to me to be, a white, cis, straight male gets to decide what is an issue or a non-issue for people who are not so privileged as to be able to code. I think this issue should be re-opened, addressed, and an apology should be issued. I will try and reach out to your manager at Microsoft and be sure that this is mentioned on your next performance review.
