### ISSUE TITLE
Improve code action on save behavior when timeout is exceeded

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#87449]
The file is save so it would be cool to allow running without a timeout. This ensures that users can get there problems fixed even if it takes longer without learning another command / short cut.

**Comment by mjbvz** [comment]
We have the `"editor.codeActionsOnSaveTimeout"` setting to control this. You can set it very high if you want to give it more time to finish, but we generally do want to make sure that these actions are either run relatively quickly or canceled (and not applied a minute after the save for example)

**Comment by dbaeumer** [comment]
@mjbvz I am aware of the timeout and it does make sense if the file is dirty. I am only asking for ignoring this if the file is saved. Otherwise users need to use a different command with a different short cut to fix all problems if the file is saved (e.g. `Fix All`). I just want to make the user experience better in this case: short timeout when saving longer timeout if the file is saved. 

Is the `Fix All` command running with or without the timeout?

**Comment by dbaeumer** [comment]
Discussed that with @jrieken and we concluded that we need to improve this. Major reason is that the current behavior is unpredictable for the user (e.g. some file are fixed on save, some aren't). We came up with the following items to improve the current behavior:

- inform the user that as save participant failed (exceed the budget). Best is a message in the status bar that disappears after a timeout and when clicked on show show help to increase the budget.
- make the budget file size dependent.
- make the budget machine dependent (e.g. proportional to the startup time)
- run without a budget when Ctrl+S is hit on a saved file 

I changed the title to indicate this new direction.

**Comment by jrieken** [comment]
I have (bravely) removed timeouts in favour of a more user-friendly progress notification. It will show what's currently happening and allows the user to cancel or to wait. We optionally, add a command to said notification that allows to disable format/code action on save but I'll leave that for another issue ;-)
