### ISSUE TITLE
Coverage: December 20, 2019 - January 6, 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#87455]
After months of continuous shipping, most of us will take off the next couple of weeks. As in the last few years:
- We will pause Insider builds. We will resume around January 6th, 2020
- Issue triaging and responses will be slow and for some topic areas not happen at all.

Happy Coding!

**Comment by catgirlsec** [comment]
Happy Holidays 🎄🎅 | Thank you for making the best code editor possible 💙

**Comment by widersky** [comment]
Happy Holidays VSCode team! Thanks for hard work! 🎄

**Comment by ChaseKnowlden** [comment]
Kamino cloned this issue to [ChaseKnowlden/vscode](https://github.com/ChaseKnowlden/vscode/issues/3)
