### ISSUE TITLE
Configuration to increase the terminal cursor width

### ISSUE THREAD

**Issue by varmanishant** [microsoft/vscode#87456]
There is an option called `editor.cursorWidth` which can be used to increase the cursor width; however, this doesn't change the terminal emulator's cursor width. This is slightly annoying. For example, please see my screenshot:

![code](https://user-images.githubusercontent.com/4084912/71278335-57d9d800-237d-11ea-9333-b7d6c8111c74.png)

**Comment by Tyriar** [comment]
This option was added upstream in https://github.com/xtermjs/xterm.js/pull/2590 as `cursorWidth`, we should carry it over to vscode (xterm in vscode will get updated to have this option very soon).

**Comment by BuraChuhadar** [comment]
Sending an MR for this: https://github.com/microsoft/vscode/pull/87911. While adding this feature in I couldn't find the changes under 4.3.0 xterm release: https://github.com/xtermjs/xterm.js/blob/4.3.0/typings/xterm.d.ts. If you can upgrade the package.json of VSCode then this MR will start working. I tested with the latest beta release of xterm as 4.3.0 is missing this feature.
