### ISSUE TITLE
Please add back the Santa hat

### ISSUE THREAD

**Issue by chrismjohnston** [microsoft/vscode#87454]
I'm sad to see that one person being upset causes a feature to be removed. I'm upset that it was removed and I would like to see it added back.

**Comment by TheAifam5** [comment]
Please look at this thread to see what we think:
https://www.reddit.com/r/vscode/comments/ed87t1/we_want_santa_hat_back/

Could you maybe provide an option to enable/disable the hat?

**Comment by aokozlov** [comment]
I'm totally agree that you should bring that santa hat back. Christmas is one of the most celebrated holidays over the world and Santa related things are accepted by everyone from children to seniors. That's weird that you removed a hat based on just one person claim. 
If you really can't decide what is better let community to vote.

**Comment by chrisdias** [comment]
Please see https://github.com/microsoft/vscode/issues/87440 for more information.

In a nutshell you can update your copy of Insiders and there is a new option that will let you change the gear to a number of different icons.  

![image](https://user-images.githubusercontent.com/1487073/71270300-19550680-2306-11ea-8fc7-61ae89e893c3.png)

**Comment by TheJaredWilcurt** [comment]
It's cool that it is a setting, but would be nicer if the icon options weren't so rushed. It's like one custom one (the santa hat), and then a bunch of just generic emojis.

In comparison, Twitch's holiday icons were really well done and included Kwanzaa and Hanukkah references.

![Twitch 2019 HaHaHalidays emotes](https://creatorhype.com/wp-content/uploads/2019/12/Twitch-Happy-HAHAHAlidays-Event.jpg)

**Comment by NotTsunami** [comment]
> It's cool that it is a setting, but would be nicer if the icon options weren't so rushed. It's like one custom one (the santa hat), and then a bunch of just generic emojis.
> 
> In comparison, Twitch's holiday icons were really well done and included Kwanzaa and Hanukkah references.
> 
> ![Twitch 2019 HaHaHalidays emotes](https://camo.githubusercontent.com/27794f82ae78f1f9eb310261257a8c9b26b0460a/68747470733a2f2f63726561746f72687970652e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f31322f5477697463682d48617070792d4841484148416c69646179732d4576656e742e6a7067)

Twitch probably had months to prepare these emotes while these were likely made on a whim due to unexpected feedback. Some of those look like they were also drawn by separate artists.
