### ISSUE TITLE
Preference to disable Recently Opened Files not working

### ISSUE THREAD

**Issue by etiennejcharles** [microsoft/vscode#87458]
Thank you for the hard work guys! 

Shouldn't recently opened files not be shown with this option ? 
Maybe I misunderstand how this works: https://github.com/microsoft/vscode/issues/30770

```
search.quickOpen.includeHistory
```

- VSCode Version:  Version: 1.42.0-insider
- OS Version: Mac OS high Sierra 10.13.6

Steps to Reproduce:

![recent-history](https://user-images.githubusercontent.com/2872476/71278369-65fc0a00-2325-11ea-8391-8cc8a359138b.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
This setting will remove "recently opened" once you start typing for search, but not initially.
