### ISSUE TITLE
Saved Work Gone

### ISSUE THREAD

**Issue by ceceliacshelley** [microsoft/vscode#87451]
Issue Type: <b>Bug</b>

Hello,

I repeatedly saved my work yesterday , but just opened up my 

VS to see that all of my code was gone. The folders and everything. Please help!

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx   (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.95GB (3.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3

</details>

**Comment by dbaeumer** [comment]
@ceceliacshelley where did you store the folder on disk?

**Comment by ceceliacshelley** [comment]
Hello! I’m at work right now, may I address this when I get home around 5?
I’ll have to address it when I’m in front of my computer! I truly apologize!

**Comment by dbaeumer** [comment]
That's fine. Provide the information when you have it.
