### ISSUE TITLE
Please add santa hat back to VS Code, it was one of the few things that gave me joy during this depressing season

### ISSUE THREAD

**Issue by nallg00d** [microsoft/vscode#87457]
Please add the santa hat back to VS Code, this truly gave me a spark of joy and inspiration during these depressing times. I really, really enjoyed it and started working on my projects, and then to find out it's been removed really, really depresses me.. and affects my mental conditions including PTSD, depression, anxiety, along with a wealth of others. The joy this gave me was something words truly can't express.

**Comment by christian-0s** [comment]
Maybe add an option to deactivate santa hat like in VLC, so we can enjoy it but who doesn't want to see it can remove it.

**Comment by kieferrm** [comment]
Try the lates insiders. For details see https://github.com/microsoft/vscode/issues/87440 for details.

**Comment by nallg00d** [comment]
Thanks friends
