### ISSUE TITLE
Turban

### ISSUE THREAD

**Issue by nikandlv** [microsoft/vscode#87463]
Hello there vscode team,

Im muslim and we feel left out so please add turban as nooroz is coming soon

**Comment by kieferrm** [comment]
Please see https://github.com/microsoft/vscode/issues/87455 and https://github.com/microsoft/vscode/issues/87440 for timeline. No opportunity for us for another Insiders build.

**Comment by SRGOM** [comment]
Please consider adding a b**b for the upcoming Ramadan b**bathon for the "austere religious scholars " among us.

**Comment by SRGOM** [comment]
@kieferrm You know you've done something awfully stupid when even the intolerants-in-chief from orange website make fun of you for being too quick to action.
