### ISSUE TITLE
Insiders Settings custom icon hover/focus state

### ISSUE THREAD

**Issue by Studio384** [microsoft/vscode#87467]
Version: 1.42.0-insider (user setup)
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:57:35.999Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Hover/focus on the Settings icon in the Insider builds
2. There is no indication of hover or focus

A way to solve this is to restore the focus state and to make hover alter its opacity as it does with any other icon.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
Please see https://github.com/microsoft/vscode/issues/87440 and https://github.com/microsoft/vscode/issues/87455 for timeline details. Given the build constraints we'll not fix the issue before we remove the feature.

**Comment by Studio384** [comment]
First off: is it still set to be removed given that it is now season-agnostic as well as optional. And second: next year it will be back and will probably have the same issues again.
