### ISSUE TITLE
JavaScript colors in editor have changed

### ISSUE THREAD

**Issue by Harfeur** [microsoft/vscode#87469]
Issue Type: <b>Bug</b>

Since a few days, the colors of the js scripts in html files have changed. I tried with a different theme, but the problem is still there.
PS : When I load VS Code, I can see during one second the old colors
![image](https://user-images.githubusercontent.com/22135449/71285992-c95a5c00-2366-11ea-854e-81cc1a49a8f6.png)
_Before_
![image](https://user-images.githubusercontent.com/22135449/71285997-ceb7a680-2366-11ea-8812-38917de43d5c.png)
_Now_

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.10
vsc-material-theme|Equ|30.0.0
beautify|Hoo|1.5.0
discord-vscode|icr|3.13.0
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
json-template|sto|0.3.1
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|9.6.0

</details>

**Comment by Harfeur** [comment]
No, vscodebot! It's still not `integrated-terminal`

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

Also, what is the theme?

**Comment by Harfeur** [comment]
After more searches, I found that the old colors were in my theme that I had installed.
So, the actual colors are the ones of a VS Code theme.
My theme was Material Theme High Contrast.
I will report the bug to the theme dev.
Thanks
