### ISSUE TITLE
Color blind 

### ISSUE THREAD

**Issue by nikandlv** [microsoft/vscode#87462]
Hello, 
Recently i lost ability to recognize colors from reading too much javascript
and i find colors really offensive and hateful
Please consider removing colored themes from vscode and only use shades of gray

Thanks vscode team

**Comment by Nick78111** [comment]
I couldn't agree more! If you can't see colors, no one else should as that is very offensive.

**Comment by Harfeur** [comment]
Hi,
Since 3 (approximately) days, it seems like that the JS colors in HTML files have changed. The functions were blue, but now they're yellow
![image](https://user-images.githubusercontent.com/22135449/71280413-6911ed00-235b-11ea-8a5b-9f3f01e374ed.png)
_Screen taken without extensions_

**Comment by kieferrm** [comment]
@Harfeur please file a separate issue.

Otherwise: Custom theme opportunity.

**Comment by SRGOM** [comment]
@kieferrm  I want to thank you for responding but you sound a bit insensitive which is very hurtful because I have a similar issue. Just because we are a minority doesn't mean we should be discriminated against. Come on, microsoft of all?
