### ISSUE TITLE
Hanukkah symbols on vscode insiders and pushing of religion is "very offensive" to me

### ISSUE THREAD

**Issue by lwinch2006** [microsoft/vscode#87478]
Democracy and righteousness should be preserved.
As complaints from @Christian-Schiffer was satisfied Microsoft should follow the same principles towards other users.
Hanukkah symbols on vscode insiders and pushing of religion is "very offensive" to me.

Version: any future version
Commit: any future commit
Date: any date in the future
Electron: any future version
Chrome: any future version
Node.js: any future version
V8: any future version
OS: any future version

Steps to Reproduce:
1. Install latest build of insiders.

Does this issue occur when all extensions are disabled?: Yes

**Comment by darkiron** [comment]
Santa hate is not religious symbol  the issue of  @Christian-Schiffer  is ridiculus and is a beautiful Godwin's point
