### ISSUE TITLE
Better JavaScript completion thru JSDOC

### ISSUE THREAD

**Issue by slowmove** [Microsoft/vscode#8747]
It would be very interesting to make the intellisense, completion and documentation popup (for a method for instace) better thru the ability of VSCode to better understand standard jsdoc like ```@description``` and such to give some text description to how to use a function, not only ```@param``` and parameter typing.

**Comment by joaomoreno** [comment]
@dbaeumer Is there already a feature request for this?

**Comment by dbaeumer** [comment]
If so then in the TS land. I will move the issue since the feature request needs to be implemented there.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9518
