### ISSUE TITLE
Formatter don't works since last update

### ISSUE THREAD

**Issue by grosfaignan** [microsoft/vscode#87472]
Issue Type: <b>Bug</b>

Shift + Alt +F don't works anymore since last update.

error message = "no such formatter installed"

thanks

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.85GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.3-insiders2

</details>

**Comment by grosfaignan** [comment]
sorry i give you all, i don't saw what you can need anymore,

**Comment by dbaeumer** [comment]
@grosfaignan this sounds more like an issue with your PHP extension. Can you please report the issue with the extension that provides you with the PHP formatting. Thanks!

**Comment by grosfaignan** [comment]
sorry, format document don't works since last update, i tried to add extension after ...

**Comment by dbaeumer** [comment]
@grosfaignan which language do you try to format?

**Comment by grosfaignan** [comment]
php,
format document worked before update, and i didnt have extension except cpptools

**Comment by dbaeumer** [comment]
@grosfaignan that sound very strange since VS Code doesn't ship with a PHP formatter out of the box. To get PHP formatting you need to install an extension from the market place.

**Comment by grosfaignan** [comment]
yes that's what i say ^^ but i havent installed formatter before, and furthermore, since alt + shift + F dont works anymore, i tried to install formatter extension and wasn't able to find working one.

**Comment by dbaeumer** [comment]
@grosfaignan but VS Code never shipped a php formatter. So I don't see how an upgrade can result in a broken php formatter. Have you tried installing https://marketplace.visualstudio.com/items?itemName=kokororin.vscode-phpfmt ort something comparable?

**Comment by grosfaignan** [comment]
yes i finally did it works. but it's a little most annoying
