### ISSUE TITLE
Scrollbar is being reset after toggling the Intergrated Terminal

### ISSUE THREAD

**Issue by limonte** [microsoft/vscode#87477]
Version: 1.41.0
OS: Linux x64 4.15.0-54-generic

### Steps to Reproduce:

1. Open the integrated terminal
2. Type something so the document height is big enough and vertical scrollbar is visible
3. Scroll down to the bottom
4. Hide the terminal (toggle)
5. Show the terminal (toggle again)

### Expected behavior 
The position of scrollbar is the same

### Actual behavior
The position of scrollbar is reset to top, but the actual document is scrolled to bottom:

![1](https://user-images.githubusercontent.com/6059356/71293029-da15cc80-237c-11ea-968b-648f129105a1.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by limonte** [comment]
Just checked on the Windows machine, the same issue is happening there as well

Version: 1.41.1 (user setup)
OS: Windows_NT x64 10.0.18363

**Comment by liamplm** [comment]
I have the same issue on a Windows machine and it`s so annoying
