### ISSUE TITLE
PR description page looks weird with maximized panel?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#87480]
- Open a PR description
- Maximize the panel
- See strange overflow

![image](https://user-images.githubusercontent.com/323878/71296681-508edc00-2335-11ea-8db8-773de89682d5.png)

**Comment by roblourens** [comment]
Or @mjbvz for webview

**Comment by sbatten** [comment]
probable dupe of https://github.com/microsoft/vscode/issues/83209
