### ISSUE TITLE
Add two-step "collapse all" behavior to explorer

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#87487]
Originally added to search in https://github.com/microsoft/vscode/issues/34685. I swear there is an issue for having this in the explorer somewhere but I can't find it.

Possible that it was closed as out of scope at some point, but I've always wanted this and I am trying to implement it.

I will also add a setting to disable this. I don't know whether we would want it on by default or not.

**Comment by roblourens** [comment]
We can't really do a common implementation for this because the tree doesn't give a way to examine the tree structure of the data. The Navigator is not sufficient because we don't know the depth of nodes as we visit them.

We could have a common helper utility that would take some delegate to give info about the model's tree structure with an API like the old IDataSource, or the depth of nodes + navigator,  but it seems like overkill given that the utility of this is limited. I think search+explorer are the only places where this is useful. If there is a third, maybe we try for a common implementation...

**Comment by isidorn** [comment]
Adding verified label since this works great :)
