### ISSUE TITLE
Confusing keyboard behavior in Text Search input box

### ISSUE THREAD

**Issue by dalongi** [microsoft/vscode#87482]
- VSCode Version: 1.41
- OS Version: OSX Catalina

Steps to Reproduce:

1. Enter long content into the Text Search box, such that it visually word-wraps (but does not have any new lines in the string)

Expected:
- This text behaves like one long line. E.g. "Home" key returns to the beginning of the entire input box

Actual:
- This text behaves as 2 separate lines. E.g. "Home" key returns to the beginning of the current line
- The text has horizontal scroll, does not wrap to multiple lines

Before pressing "cmd + left"
![Screen Shot 2019-12-20 at 3 20 38 PM](https://user-images.githubusercontent.com/1166263/71298307-5936e080-233c-11ea-94f0-d874927da76a.png)

After pressing "cmd + left"
![Screen Shot 2019-12-20 at 3 21 01 PM](https://user-images.githubusercontent.com/1166263/71298308-5b00a400-233c-11ea-9865-82ac5f8ef34d.png)

**Comment by roblourens** [comment]
I think this is actually expected. In any case this is implemented by the behavior of the native textarea and I don't want to override that.
