### ISSUE TITLE
TypeScript, JavaScript, Homophobia and Brendan Eich

### ISSUE THREAD

**Issue by RandomErrorMessage** [microsoft/vscode#87486]
As we all know, VS Code is written primarily in TypeScript, which transpiles to JavaScript, which was created by Brendan Eich. Brendan's deplatforming from Mozilla is well documented, involving a personal donation to a political organization which advocated against gay marriage.

While we don't really know Brendan's personal views, this alone has sufficiently made him and all of his derived work inherently offensive. I cannot imagine anyone in good faith writing something in JavaScript and/or TypeScript without simultaneously endorsing a homophobic agenda.

Additionally no desktop application should be written in such a language as it promotes a culture of mediocrity and bloat that is increasingly damaging to society. When software fails, people die. We can't ethically be programming in these _scripting languages_.

- VSCode Version: All
- OS Version: All

Steps to Reproduce:

1. Install Visual Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by SRGOM** [comment]
It's okay to profit off purported bigots and thought criminals ,‌‌‌ please watch CNN to get some tips on it. What's not okay is to let the purported bigots profit.

**Comment by RandomErrorMessage** [comment]
> It's okay to profit off purported bigots and thought criminals ,‌‌‌ please watch CNN to get some tips on it. What's not okay is to let the purported bigots profit.

Using JavaScript and JavaScript derived work absolutely directly enriches Brendan Eich. He is arguably most notable for JavaScript and it's current popularity. This gives him many opportunities to profit and garner attention.

**Comment by RandomErrorMessage** [comment]
I'm concerned that this issue was closed. I thought a Microsoft, a company that supposedly values diversity and inclusiveness would base significant portions of their business on technology drenched in homophobia without a second glance.

**Comment by Amanse** [comment]
I am concerned about this too, i stopped using brave browser because of this and i recently got to know that he is behind javascript too, i think it's time of python for me.
