### ISSUE TITLE
Bug when dragging folder or extension file into vscode

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#8748]
- VSCode Version: 1.3.0-insider
- OS Version: windows7

Steps to Reproduce:

1.  Drag a `folder` from outside into vscode.
2.  `folder` would not open as an new workspace.

3. Drag a `vsix` file from outside into vscode.
4. vscode would open the file instead of install the extension

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/8726
