### ISSUE TITLE
disable explorer.compactFolders by default

### ISSUE THREAD

**Issue by eedwards-sk** [microsoft/vscode#87484]
Horrible new feature. Absolutely horrible.

The UX is terrible. Dragging files between empty subfolders used to be easy, now it's extremely difficult and error prone.

Took over 30 minutes of frustration and searching to discover how to disable this feature.

Wasn't until I installed the update officially that the release notes appeared describing the feature.

Somehow I was opted into it before even updating explicitly.

Please don't force new behavior that reduces functionality.

**Comment by 0xAndrewBlack** [comment]
I agree with you its a horrible feature i just see this randomly my folder is full of '/' and i figured out it updated before it even was updated to the latest version and even showing me the changelog of this HORRIBLE "feature"

**Comment by Divlo** [comment]
Agreed, worst feature of VS Code actually.

**Comment by ee0pdt** [comment]
Wow, this is so annoying! I'm hoping we get the upvotes in time!

**Comment by zephinzer** [comment]
+1
