### ISSUE TITLE
[Bug] "Updating Visual Studio" Dialog should be at central position of the screen

### ISSUE THREAD

**Issue by MaledongGit** [microsoft/vscode#87495]
1. Open a Visual Studio of an old version.
2. Click the icon at left corner to update it.
3. The "Update Visual Studio" appears, but it's at most top left of the screen, it should be at the center of the screen.

----

CPUs | Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 3.15GB (1.40GB free)
Process Argv |  
Screen Reader | no
VM | 0%
---

Extension | Author (truncated) | Version
-- | -- | --
gitlens | eam | 10.2.0
vscode-language-pack-zh-hans | MS- | 1.41.2
vscode-icons | vsc | 9.6.0

**Comment by joaomoreno** [comment]
We already do this: https://github.com/microsoft/inno-updater/blob/master/src/gui.rs#L48

But if for any reason that dialog data isn't available, we simply show the window: https://github.com/microsoft/inno-updater/blob/master/src/gui.rs#L58 and I guess that places it in any available screen space.

Not really sure why that's the case for you. But I also don't think it's worthwhile spending time on. Sorry about that!

**Comment by MaledongGit** [comment]
> Not really sure why that's the case for you. But I also don't think it's worthwhile spending time on. Sorry about that!

Because sometimes when the dialog isn't in the center, I cannot click "OK" button until I drag the dialog. But I still want to say a BIG THANK YOU to you to solve it.
