### ISSUE TITLE
"The typescript task provider is slow" very often

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#87494]
I have been seeing this somewhat often, especially on remote. It started maybe a few weeks ago. It shows up after I press cmd+shift+B

![image](https://user-images.githubusercontent.com/323878/71300306-30b4e380-2348-11ea-9a86-bd0767d5c153.png)

**Comment by kieferrm** [comment]
Same here.

**Comment by alexr00** [comment]
@mjbvz made a change that should have improved this. If you're still seeing the this after this week let me know and I'll increase the timeout again (currently 4 seconds). 

I don't want to increase the timeout too much though, as this this waiting is directly surfaced to users when they run "Run Task" and have to wait for the quick pick.

**Comment by Beatsleigher** [comment]
I'm definitely having the same issue with the latest Insiders Build.
Waiting for the tasks to pop up takes several seconds. I would certainly be faster typing everything in to the console.

**Comment by alexr00** [comment]
@Beatsleigher, this  issue is about the above notification poping up often. Are you seeing that, or are you just seeing the task quick pick be slow?

**Comment by Beatsleigher** [comment]
Both, actually. They coincide. Hitting CTRL+SHIFT+B opens up the Tasks popup, which takes several seconds, which in turn causes the notification to pop out.

**Comment by alexr00** [comment]
@Beatsleigher are you using the insiders build?

**Comment by Beatsleigher** [comment]
Yes, I'm using the Insiders build. I'm aware these may get a bit buggy, but that's the exact reason I'm here. So that this issue doesn't get in to the next stable release ;)

Here's some more debug info.
```
Version: 1.42.0-insider
Commit: 22e4d75bd07b1ec7362c69da9dda7667eae95374
Date: 2020-01-13T05:28:42.464Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-26-generic
```

**Comment by alexr00** [comment]
@mjbvz even with your fix we are still seeing many instances of the typescript task provider being slow. I can increase the timeout, but that won't help with the slowness.

**Comment by mjbvz** [comment]
@roblourens Repo steps? I don't see this in the VS Code repo in my testing

**Comment by roblourens** [comment]
I see it in my https://github.com/microsoft/vscode-js-debug repo, only on remote, when I press cmd+shift+B.

**Comment by mjbvz** [comment]
Thanks @roblourens. We find tsconfigs too ways:

- From TypeScript. I already time boxed that since the tsserver can take a little while to init
- A file search to find tsconfig files in the workspace. I wonder is that is what is slow here...

**Comment by mjbvz** [comment]
I've added timeboxes  to our calls to `findFiles` and also rewritten the code to run more things in parallel instead of sequentially. I think the rewritten task UI also makes less likely to be hit 

Let me know if you still see this and I can try reducing some of the timeouts or looking into other fixes
