### ISSUE TITLE
 Repeat input in Terminal when toggle Input

### ISSUE THREAD

**Issue by xiaoxintang** [microsoft/vscode#87499]
- VSCode Version: 1.14.1
- OS Version: macos 10.15.2

Steps to Reproduce:

1. Chinese input method type something i want E.g `ls`
![image](https://user-images.githubusercontent.com/24927686/71301127-8932c200-23d6-11ea-88a5-9067ec12e779.png)

2. press `Chinese-English Switch`
![image](https://user-images.githubusercontent.com/24927686/71301132-98197480-23d6-11ea-91c0-d17b4c3c14c4.png)

3. it's the same as any i want to input

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Is this "Pinyin - Simplified"? I can't reproduce on that.

Could you also clarify what "press Chinese-English switch" means?

**Comment by xiaoxintang** [comment]
> Is this "Pinyin - Simplified"? I can't reproduce on that.
> 
> Could you also clarify what "press Chinese-English switch" means?

![image](https://user-images.githubusercontent.com/24927686/71555998-99e5d680-2a6d-11ea-8946-d80a92956b6a.png)
sorry,I mean this button

**Comment by Tyriar** [comment]
Well I don't have a hardware button but ctrl+shift+space switches the IME and just prints the single `ls`. @rebornix any ideas on this?

**Comment by xiaoxintang** [comment]
well done

**Comment by rebornix** [comment]
I'm not seeing it happening in both Stable and Insiders. @xiaoxintang it would be great if you can provide more info about how to reproduce this issue.
