### ISSUE TITLE
I can't contribute to VS Code?

### ISSUE THREAD

**Issue by Entomy** [microsoft/vscode#87492]
This will probably get flagged and removed given the recent controvery, but at least hear me out. I'm not at all trying to troll. I genuinly do not understand how this is supposed to work.

I'm the author of numerous extensions, one being the most popular for the language it supports. I have several .NET projects dealing with text/programming related things, from parsing, to code analysis, and more. One of those projects actually caught the attention of another team at Microsoft.

I have not ever worked as a programmer. For various reasons I was unable to finish college beyond an A.A. I very much would like to, ideally at Microsoft. So more recently I have been looking for a project to begin contributing to, to help further prove I know what I am doing, but also to demonstrate an understanding and ability to work within the typical MS workflow.

So now we get into my concern and why I'm filing this as a bug report. I beleive there is a fundamental bug in how these things are handled. Let me explain.

I am autistic. My very existence is a matter of offense to some people. One only needs to do a cursory search to find that's the case. If I contribute to this project, and someone files an issue claiming offense to this, the action is what exactly? To remove any and all of my contributions? After all "even a single person being offended is one too many".

Again, I'm not trying to troll. I'm genuinely trying to understand the situation and if it's even okay for me to contribute to this project. I fail to see how anything could exist which isn't offensive to someone, so I have to ask where that line is drawn, because I'm not able to see it on my own.

**Comment by Xaekai** [comment]
I'm not aware of any political subgroup that campaigns to oppress ASD individuals in the same fashion as LGBT and racial minorities. I believe most would recognize that ASD children have a profound struggle with bullying in school, and many have issues maintaining employment in adulthood. But that's generally out of the inability of others to cope with atypical behavior, not being offended by the very existence of autism.

Anyone who would raise issue exclusively with your status as an ASD individual would be out of line, out of scope, and _**without question would be quickly vilified by the larger open source community.**_

**Comment by Entomy** [comment]
I've been fired from at least two positions explicitly because of my condition. As in that was the actual reason given. This was despite excellent performance evals, and even despite being head cook for one. Yes I know this is illegal, but the law merely punishes offenders after the fact. And I happen to live in a very small area where you can't reasonably sue because word gets around. After both times I would receive random messages from locals on Facebook about things like "retards like you should be put down" or "you shouldn't even be allowed to go outside".

The secondary school I had attended went as far as to try to court order ECT. Not on any medical nor psychiatric basis. In fact the judge summarily dismissed the entire thing and even overheard the counter suite, which was won.

With all due respect, I have to disagree with you. Sure it's not exactly a "political subgroup", but it is a subgroup. The "political" qualifier is unnecessary and I don't understand it's inclusion. There's been several cases of people going as extreme as forced consumption or forced enema of bleach in an attempt to "cure" child autism. Just because it's not happening on a strict political line doesn't mean it's not happening, nor is any less so than others. I can personally attest that it's a lot more than just bullying and rubbing people the wrong way. I've encountered numerous people, and institutions who absolutely were offended by what I am.

**Comment by Xaekai** [comment]
I'm sorry to hear about your awful experiences. I included the word political because usually any sort of widespread or organized oppression is under some ideological banner; people tend to need the justification that provides to suppress their conscience. The optimistic part of me would hope those you describe would be the outliers of our society.

Software development has historically been a vocational refuge for ASD. [Microsoft especially](https://www.youtube.com/watch?v=XUAsU_zQVMo). You can do all your work from the safety of your home, presenting yourself to the world through code and text at a safe distance, if that is what's comfortable for you. For someone express that they are offended by you, for example in a VCS issue tracker, they would have to put themselves on public display as inequitable. That violates one of the most sacred tenants of coding, one that predates the concept of CoCs, the _meritocracy_. If you can code, you belong, everything else is irrelevant.

**Comment by Entomy** [comment]
Oh okay, thank you for your explanation.

**Comment by kieferrm** [comment]
@Entomy this repository is governed by the [Microsoft OSS Code of Conduct](https://opensource.microsoft.com/codeofconduct).  I quote:
> **Be welcoming:** Our communities welcome and support people of all backgrounds and identities. This includes, but is not limited to members of any race, ethnicity, culture, national origin, color, immigration status, social and economic class, educational level, sex, sexual orientation, gender identity and expression, age, size, family status, political belief, religion, and mental and physical ability.

Recently, people have quoted us incompletely. Here is our full quote from https://github.com/microsoft/vscode/issues/87440, emphasis added by me.
> Earlier this week, we were notified through an issue (and on twitter) that **the design** of the gear with the Santa hat **was divisive and offensive to some of our users (even a single person being offended is one too many)**, meaning it represented the opposite of what we wanted to convey to our users.

What this says is that we don't want to distribute a **product** that is offensive to anyone. There is no reason for us why we ever would want to do that. 

As a community we are human beings with different temperaments and styles of interaction, and we do interact in English which for many if not most of us is a second language. We do not always agree on how features should work or what is a bug and what isn't. Also, misunderstandings will happen. All our interactions are conducted in the spirit of the  [Microsoft OSS Code of Conduct](https://opensource.microsoft.com/codeofconduct) and as such we'll be friendly, patient, and respectful. In large, this is an outstanding community, and you are more than welcome to be part of it. 

I hope this answers your question. If so, please close the issue.

**Comment by SRGOM** [comment]
I assure you that the recent closure was just one guy trying to quietly and quickly go about their business by doing what they thought was a harmless (thought unfruitful) submission to a troll.

Microsoft is a very accomodating employer and would never do such a thing. Nor would any genuine contributions be ever removed.
