### ISSUE TITLE
VSCode on Linux opens on wrong display(system)

### ISSUE THREAD

**Issue by d3x0r** [microsoft/vscode#87498]
- VSCode Version:

1.41.0
9579eda04fdb3a9bba2750f15193e5fafe16b959
x64

- OS Version:
Arch linux (updated sometime last week)

Steps to Reproduce:

1.Connect to a linux system, which supports forwarding X connections, and with a SSH client that can host forwarded X connections.  (I use Mobaterm, from a windows system... that is, the system connecting to the linux system should also be a separate system.)  Start Code in some directory.

2.Login as the same user directly on the computer.  I am using wayland with weston for the gui; and in a terminal, I can start code in some other directory, but it did not appear.  (It does, but on the wrong system, when I did it the first time I would say '... did not appear but, I later got back to the other system, and noticed two new VS code editors open.

So, not only open on the wrong display, but the display on the wrong physical computer.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@d3x0r does that happen with any other electron app?

**Comment by d3x0r** [comment]
@kieferrm  It is possible it's any electron app; I have Atom installed... but I won't be able to test for a few days (while I'm on the road).

to codebot; I left the template in, and attempted to complete as much of it as I could; I don't know which sentence of that reporting guideline I'm failing.

**Comment by deepak1556** [comment]
Sorry missed this, thanks @d3x0r for opening the electron issue, will continue the discussion there.

**Comment by deepak1556** [comment]
Closing as the issue hasn't seen movement in upstream for a while, you can use our [remote development suite](https://code.visualstudio.com/docs/remote/remote-overview) as a workaround.
