### ISSUE TITLE
bug with find and replace all folder feature

### ISSUE THREAD

**Issue by ngocthangh** [microsoft/vscode#87497]
Issue Type: <b>Bug</b>

When i press Ctrl + Shift + H to find something and select replace all, it sometime fail to replace all found text, sometime it replace wrong position, maybe because the position changed since the previous replace of the same file.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kieferrm** [comment]
Can you please add concrete steps that help us to reproduce the issue? Thank you!
