### ISSUE TITLE
User configurable maximum *.d.ts file-size

### ISSUE THREAD

**Issue by HackbrettXXX** [Microsoft/vscode#875]
I stumbled over an issue where really large TypeScript .d.ts-files were not parsed correctly in JavaScript mode.

After some debugging I found out that the reason is a hard-coded file-size limit, where all characters in file-strings that are longer than 1,500,000 characters are getting replaced by space-characters and therefore getting ignored. This happens in **languages/typescript/common/project/snapshots.ts**:

    export function fromValue(value: string): ts.IScriptSnapshot {

        var len = value.length;
        if (len > 1500000) {
            // everything except newline characters will be replaced
            // with whitespace. this ensures a small syntax tree and
            // no symbol information overkill. keeping the newline
            // characters makes further processing (based on line and
            // column) easy for us
            value = value.replace(/[^\r\n]/g, ' ');
        }

        return {
            getLength: () => len,
            getText: value.substring.bind(value),
            getChangeRange: () => null
        };
    }

My idea was to make this maximum file size user-configurable using the `workbench/node/UserSettings` class. However, this is not possible as `typeScriptWorker2` runs in the `common` environment and has therefore no access to the `fs` and `path` module.

So another suggestion is to just increase the maximum file size (or omit the check completely). I removed the length check and tested the editor with a *.d.ts-file with ~8,000,000 characters. I could not perceive any lags or unresponsiveness. The code completion still worked smoothly. Neither did the memory usage significantly increase.

In addition, the languages/typescript/common/lib/lib.es6.d.ts-file, which defines the standard language, itself is 1,470,724 characters long. So there are only ~30,000 characters left for future changes, which could lead to a bug that will probably be hard to track down.

Is there a quick and easy method to make the maximum file-size user configurable?
If not, my suggestion is to increase the hard-coded maximum file-size to at least 10,000,000 characters.
In the future, when the JavaScript mode will also be moved to an extension, it would be sensible to make the maximum file size user configurable.

**Comment by jrieken** [comment]
We have this check because the editor (without VS Code) ships in other products with different memory/perf constraints. Making it configurable is an option (you should have access to a config service somewhere) but once we adopt project salsa VS Code will not hit by this anymore.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
