### ISSUE TITLE
窗口虚化

### ISSUE THREAD

**Issue by bubupuanother** [microsoft/vscode#87500]
和别的窗口重叠的时候，vscode的窗口会变成虚化（毛玻璃状态），非常影响代码的查看和编写，希望尽快修复。

**Comment by djmisterjon** [comment]
hi, here the solution for you .
https://github.com/microsoft/vscode/issues/51789#issuecomment-416868789

**Comment by bubupuanother** [comment]
> hi, here the solution for you .
> [#51789 (comment)](https://github.com/microsoft/vscode/issues/51789#issuecomment-416868789)

That's amazing！thanks my friend
