### ISSUE TITLE
The ability to type anything with a keyboard is offensive to lots of people who suffered limbs diseases

### ISSUE THREAD

**Issue by MaksimMedvedev** [microsoft/vscode#87513]
I find myself very lucky not to have such a terryfying disease but I feel it's offensive and humiliating for the talented people who want to program.
I do want to be sure that such horrible situation is well handled by MS since the problem is challenging our honest and tolerant world.

- VSCode Version: latest Production build
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Launch VS Code
2. Try to type anything in the edit window

Does this issue occur when all extensions are disabled?: Yes

**Comment by nzalog** [comment]
Agreed, it's so damn offensive I'm also offended on their behalf. 

Also it's very ablest too, there are people out there who don't know how to code. How is writing code fair to them?

**Comment by remenyo** [comment]
I think you should open an issue on keyboard's repo.

(I think you opened this issue because you read about the santa hat removal. The holiday logo is configurable on insider edition settings.json -> holiday.gearIconStyle)
See #87440

**Comment by sitepodmatt** [comment]
Keyboard support is planned for removal in December release by default (due out mid jan) - you can re-enable in settings though by carefully dragging characters from https://en.wikipedia.org/wiki/English_alphabet you need to change keyboardDisabled to false

**Comment by MaksimMedvedev** [comment]
> Keyboard support is planned for removal in December release by default (due out mid jan) - you can re-enable in settings though by carefully dragging characters from https://en.wikipedia.org/wiki/English_alphabet you need to change keyboardDisabled to false

Thank you very much, I hope MS would bring its sincerest apologies to people who were abused by this incident!

**Comment by kieferrm** [comment]
We have many users who successfully use VS Code with assistive technologies. If there is a concrete issue, please file an issue with reproducible steps. Thanks.
