### ISSUE TITLE
Python Intellisense autocomplete extremely slow

### ISSUE THREAD

**Issue by kevin-hv** [microsoft/vscode#87510]
OS: MacOS
- VSCode Version: 1.41.1
- OS Version: 10.15.2

Problem:
Intelisense autocomplete takes forever to complete downloaded Python modules such as pandas (but other as well, numpy, scikit-learn...) under MacOS. 

Steps to Reproduce:

1. Install python3 via Brew (brew install python3)
2. Install VSCode (either via Download from Official site or via Brew Cask)
3. Install pandas with pip3 (pip3 install pandas)
4. Create a new .py file and observe the behaviour attached below

![Screen Recording 2019-12-21 at 08 40 28](https://user-images.githubusercontent.com/44970281/71305059-c3986100-23ce-11ea-9e7c-737cfb7eca14.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
Please file this issue against the Python extension here: https://github.com/Microsoft/vscode-python/issues. Thank you!
