### ISSUE TITLE
vscode not support gradle and springboot together very well 

### ISSUE THREAD

**Issue by ablozhou** [microsoft/vscode#87516]
- Version: 1.41.1
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T14:57:51.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Darwin x64 19.0.0
- 
 Steps to Reproduce:
I've install all extentions.
1.  generate a gradle spring boot project

2.  report many errors like:
{
	"resource": "/Users/zhh/java/crediter/src/main/java/com/abloz/xxxApplication.java",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "compiler.err.doesnt.exist",
	"severity": 8,
	"message": " package org.springframework.boot  does not exist",
	"startLineNumber": 4,
	"startColumn": 8,
	"endLineNumber": 4,
	"endColumn": 50
}

3. but I can run it in the IDE or run it by comand.
![Uploading WX20191221-191708@2x.png…]()

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ablozhou** [comment]
the attached image：
<img width="553" alt="WX20191221-1917082x" src="https://user-images.githubusercontent.com/1628718/71307601-6f6f9a00-242b-11ea-9052-375f74715d08.png">

**Comment by kieferrm** [comment]
Please file the issue against the Java extension here: https://github.com/redhat-developer/vscode-java/issues. Thank you!
