### ISSUE TITLE
Configured debug type 'chrome' is not supported.

### ISSUE THREAD

**Issue by Luncher** [Microsoft/vscode#8751]
- VSCode Version: 1.4.0
- OS Version: fedora21

Steps to Reproduce:

1.  clone vscode repository & `./scripts/npm.sh install --arch=x64` 
2.  ./scripts/code.sh --remote-debugging-port=9222 &  `DEBUG from Attach to VSCode`

![screenshot from 2016-07-05 16 57 56](https://cloud.githubusercontent.com/assets/5138977/16579313/c328cce0-4264-11e6-843f-3a040ddde908.png)

**Comment by weinand** [comment]
@Luncher you have to install the chrome debug extension:  https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome if you want to reuse that launch config.
