### ISSUE TITLE
Change the logo because it hurts Non-Christian programmers

### ISSUE THREAD

**Issue by dzejqub** [microsoft/vscode#87518]
Hello, please remove the logo or change it if it harms other religions than Christianity, the logo resembles a Christian fish, change the logo within tolerance for other followers
Regards

**Comment by VlasinCalin** [comment]
This is just insane, first this guy: Christian Schiffer with removal of santa hat and now you. 
You guys are imagining things or you are just stupid.

Are you crazy? You are part of a generation of already offended people. 

And Microsoft, this is happening when you accept compromise. You accepted the compromise with @Christian-Schiffer and now all morons are requiring things from you.

This is just stupid.

**Comment by nielslange** [comment]
If you see a fish in that logo, you should stay away from drugs, mate! ;)

**Comment by fonix232** [comment]
@nielslange the logo actually does look like the Christian fish, stylized a bit: 

![image](https://user-images.githubusercontent.com/371847/71308162-446c5280-23f9-11ea-8921-f291fb14a3b0.png)

**Comment by sitepodmatt** [comment]
On a more serious note, MS have made their position clear (and that's fine its their project to govern) but I wonder if its a company wide attitude.

Does anyone know what the Microsoft company canteens at Redmond and Zurich (where VSCode is developed) serve? VSCode PM said "if one person is offended that's one person too much" which is an interesting take, but I ponder the implications.  What if a muslim is offended by the serving of pork? What if a hindu is offended by the serving of beef? What if a vegetarian is offended by the serving of chicken? What if a vegan is offended by milk and dairy products? Can you get anything other than water or organic non-lactose skinny lattes at Redmond or Zurich without offending "one person"?

**Comment by dzejqub** [comment]
This is nice issue, everyone we did it! Remove too how santa cap who delete because only one guy triggered about this!

~~this issue is bait guys, don’t takie this seriously.~~

**Comment by bertramdryan** [comment]
Realistically, Any logo could be offensive to anyone.  A lot of non-Christians celebrate Christmas and go to see Santa.  If you are personally offended by a red cap with a white fuzzy saddle, then use Atom or Eclipse or download an older version. This is open source, make fork and remove the offending item.

**Comment by nielslange** [comment]
> @nielslange the logo actually does look like the Christian fish, stylized a bit:
> 
> ![image](https://user-images.githubusercontent.com/371847/71308162-446c5280-23f9-11ea-8921-f291fb14a3b0.png)

Everything looks like a Christmas fish if you just stare at it long enough. Opening an issue like this is nuts in my opinion. My thoughts are similar to @bertramdryan. Don't like the logo, don't use the software. Simple as that.
