### ISSUE TITLE
Allow changing all the icons in VSCode

### ISSUE THREAD

**Issue by varadero** [microsoft/vscode#87522]
Recently a lot of people were shocked by how Microsoft (employees) reacted to https://github.com/microsoft/vscode/issues/87268 , not without a reason.

In order to avoid a single person LOL-ing at us and you in the future, allow changing all the icons in VSCode.

I personally find the "Source Control" icon looking exactly as a thin penis attached to two loosely-coupled testicles heading down (I expect to take this seriously):

![image](https://user-images.githubusercontent.com/7610713/71308984-4fc87980-240b-11ea-8b07-f1a5c53bcf69.png)

This promotes porn-related images to me and I am offended and insulted at the same time. According to what Microsoft says in https://github.com/microsoft/vscode/issues/87440 - "even a single person being offended is one too many", I demand you to "remove it immediately and make it your top priority" (see exactly the same demand at https://github.com/microsoft/vscode/issues/87268 and how you obeyed).

I don't (and hopefully nobody) expect you to treat me (or anyone else) differently on the above matter. Otherwise, it would be an willful discrimination.

**Comment by ex1tium** [comment]
Couldn't agree more. Small penis icon is deeply offensive for me as a white man. Also the debugger icon looks like a bug is being tortured by poking it with a arrow head. Now I respect all animals equally so I find it horrible that Microsoft is promoting animal torture to such extent.

**Comment by remenyo** [comment]
I do like the general idea, allow more advanced theming.
There are enough examples to encourage this.

Misinterpreting the vscode icons one by one is pointless from now on.

**Comment by MaksimMedvedev** [comment]
Agreed. There are way too many opinions and way too many ways to offend some single person with some icon 

The only right way to solve this is just to make everything customizable and that's how it should've been asked by that guy. Not by "removing it immediately and making it the top priority"

**Comment by Joshua-Ashton** [comment]
Yes, I would like to change every icon to a frog.

🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸

**Comment by anshulxyz** [comment]
I am pretty sure you can change those icons with editing themes,

if not that, then you have entire project open sourced, change the icons and you can build it up yourself

**Comment by coding4truth** [comment]
Typical white developers waving their undersized penises at us.

**Comment by MartinX3** [comment]
We in our company won't introduce a software which contains NSFW icons.
Please remove it.

**Comment by SRGOM** [comment]
> Yes, I would like to change every icon to a frog.



> Yes, I would like to change every icon to a frog.

Is that the same frog that hially went berserk about in a video and still blames for his defeat to the bad orange man?

**Comment by MartinX3** [comment]
@SRGOM I would use pepe the frog.
┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴

**Comment by Joshua-Ashton** [comment]
@SRGOM No.

**Comment by lviggiano** [comment]
Please add a customizeable-size penis icon. 
Size matters.
