### ISSUE TITLE
focusSideBar opens file

### ISSUE THREAD

**Issue by mchels** [microsoft/vscode#87524]
Issue Type: <b>Bug</b>

1. Open a workspace.
2. Close all open files.
3. Open any file from the sidebar explorer.
4. Close that file (now you should have no open files and the file you opened in the Explorer should be highlighted, and the editor, not the sidebar explorer, should have focus).
5. Invoke workbench.action.focusSideBar (I use shift+alt+e).

Actual behavior:
The Explorer window is in focus AND the highlighted file is opened.

Expected behavior:
The Explorer window is in focus. No file should be opened.

This only happens if there are no open files when focusSideBar is invoked. It has been an issue in a couple of vscode versions, so it's not a 1.41 thing.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-1051-aws

edited for clarity: "focused file" -> "highlighted file"

**Comment by isidorn** [comment]
Somewhat dup of https://github.com/microsoft/vscode/issues/83028 and oposite of https://github.com/microsoft/vscode/issues/67708

Bottom line: we behave like this from day one and changing it might break some muscle memory of users.
I will leave this open as a feature request and I might change this in the future (potentially adding a setting so this can be controlled by the users)

**Comment by isidorn** [comment]
After more feedback from users we decided to no longer automatically open editors from the explorer if no editor opened. I personally found this behavior overly smart and counter intuitive sometimes. Let's see the user feedback on this change.

fyi @webczat so now your issue should be fixed as well

**Comment by webczat** [comment]
I am currently not fully certain if this is the same issue. I have experienced this one too and didn't quite know how to reproduce it, but at first glance the issue with opening a focused file when pressing enter after typing filename for new file may be something different. When I have a version of vscode with the fix for this I can likely test.
