### ISSUE TITLE
TypeScript language service died 

### ISSUE THREAD

**Issue by KhalilAwada** [microsoft/vscode#87526]
Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.11
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
vscode-docker|ms-|0.9.0
mssql|ms-|1.8.0
python|ms-|2019.11.50794
vscode-typescript-tslint-plugin|ms-|1.2.3
subtitles-editor|pep|1.0.4

</details>

**Comment by Nek-** [comment]
Related to https://github.com/microsoft/vscode/issues/87521

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by OmgImAlexis** [comment]
Having the same issue here. Using the latest public VS Code on macOS.
