### ISSUE TITLE
Breakpoints disabled when debugging extensions

### ISSUE THREAD

**Issue by vivainio** [Microsoft/vscode#8752]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:

1. git clone https://github.com/vivainio/robotframework-vscode.git
2. open the project in vscode
3. set some breakpoints in extension.ts
4. press f5 and open some file with .robot extension
5. observe that breakpoints are disabled with the tooltip: "Breakpoint ignored because generated code not found (source map problem?)."

**Comment by weinand** [comment]
@vivainio thanks for making your project available.
The launch config is missing the source map attributes `sourceMaps` and `outDir`. With this launch config setting and hitting breakpoints works for me:

```json
		{
			"name": "Launch Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": ["--extensionDevelopmentPath=${workspaceRoot}" ],
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/out/src"
		}
```

It is recommended to use the VS Code yeoman generator `generator-code` for scaffolding an extension project (see https://code.visualstudio.com/docs/extensions/example-hello-world )

**Comment by vivainio** [comment]
@weinand thanks for looking into this. I generated the project with yeoman generator, but it was an earlier version of the generator.
