### ISSUE TITLE
Basic File Explorer Feature: Nested Files

### ISSUE THREAD

**Issue by tmarkovski** [microsoft/vscode#87523]
Issue Type: <b>Feature Request</b>

Nested Files is a basic feature that all editors include today, including Visual Stuido for Windows and Mac. Based on the numerous PR's that the community submitted, it seems the implementation is roughy couple dozen lines of code. This feature is actively requested since 2016, and is almost mandatory when working with web projects. What are the reasons the dev team is not looking into adding this and ignoring community contributions?

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/6328
