### ISSUE TITLE
Compact or concat all editors groups spacing [Request]

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#87527]
In a big project I really like working with **editor grouping** for all my files, I find it more productive.
But i lost a lot of space work.
Is it possible plz to add a native setting to concat all editor group not focused ?

I take time to made little photoshop sketch if am not clear, tell me if you need more info.

### Current behavior
![image](https://user-images.githubusercontent.com/24865815/71309160-acf40900-23d2-11ea-9a97-facec204be43.png)
### Target behavior
![image](https://user-images.githubusercontent.com/24865815/71309186-fd6b6680-23d2-11ea-9d69-85257de66923.png)

---
Here a animated gif of target behavior
![concatVscode](https://user-images.githubusercontent.com/24865815/71309262-f85ae700-23d3-11ea-9b8d-0bbf015b30a4.gif)

Thanks a lot for your awesome work guys.

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by djmisterjon** [comment]
I try many hack but i cant succeed to get compact space (:
Did you have any tips for this ?
I try disable breadcrumb , but editor keep a min vertical space!
![breadcrumb space editor vscode](https://user-images.githubusercontent.com/24865815/74396936-7ee2e200-4de1-11ea-8355-7137833bed3a.gif)

**Comment by djmisterjon** [comment]
i don't know this IDE, but it show what i mean by compact.
![image](https://user-images.githubusercontent.com/24865815/74398121-97083080-4de4-11ea-90d6-8d138b073aa1.png)
