### ISSUE TITLE
Notification UI distortion

### ISSUE THREAD

**Issue by burlarajesh** [microsoft/vscode#87520]
Issue Type: <b>Bug</b>

Notification pop up is disorted when no notifications are availble

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.5.0
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|3.17.0
python|ms-|2019.6.24221
csharp|ms-|1.21.9
vscode-jest|Ort|3.1.0
material-icon-theme|PKi|3.9.2
csharp2ts|raf|0.0.22
project-snippets|reb|0.5.0
LiveServer|rit|5.6.1
sonarlint-vscode|Son|1.10.0
python|tht|0.2.3
vscode-icons|vsc|9.6.0

</details>

**Comment by burlarajesh** [comment]
![image](https://user-images.githubusercontent.com/10438863/71308046-2284c700-241d-11ea-96f4-97e1370b82ff.png)

**Comment by bpasero** [comment]
@burlarajesh yeah we are getting this issue from time to time but never had the chance to reproduce. You are using quite an old version of VSCode. Can you update to latest and let me know how to reproduce if it happens again?

**Comment by burlarajesh** [comment]
@bpasero I am not able reproduce this anymore after updating to latest. You can close this thread. :)

**Comment by renanlq** [comment]
I'm on version: 

> Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

and facing the same problem:
![image](https://user-images.githubusercontent.com/15347353/73774795-603a7680-4763-11ea-873c-1fb6271f2d41.png)

**Comment by bpasero** [comment]
Given https://github.com/microsoft/vscode/issues/85617 I would like to verify this again when 1.42 ships this week.
