### ISSUE TITLE
custom-built font refuses to load, pre-built counterpart works fine

### ISSUE THREAD

**Issue by arknjl** [microsoft/vscode#87530]
the iosevka font works great on vscode. though, for iosevka, there are a bunch of neat customization options you get to switch on/off when you build it manually. so i did!
the font works as intended in other editors like sublime text and notepad, but when i enter the name of the font into vscode settings, it doesn't seem to recognize it exists (exhibits same behavior as if i typed in gibberish or a font i haven't installed)
i've built a version of the font with no additions whatsoever, and that one doesn't seem load either.

it looks like vscode doesn't seem to acknowledge manually built fonts. any ideas?

- VSCode Version: 1.41.1
- OS Version: Windows 10 Education (64-bit)

Steps to Reproduce:

1. install [this font](https://github.com/microsoft/vscode/files/3991582/iosevka-custom-regular.zip) (iosevka-custom-regular.zip)

2. change font to `Iosevka Custom`

Does this issue occur when all extensions are disabled?: Yes

**Comment by arknjl** [comment]
note: just fired up vscode insider and it works there. this is no longer a problem to me but it may still be worth looking into

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by arknjl** [comment]
> Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

what?

**Comment by alexdima** [comment]
@arknjl VS Code is built with Electron, which is built with Chromium. Sometimes, Chromium is real picky about the font family name and finding it installed. Sometimes, it is necessary to close all running VS Code instances before the font is found. 

I don't think there is anything more we should do on our side.
