### ISSUE TITLE
June Issue Review

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8753]
We have accumulated a lot of issues in our inboxes it is time to review them. Therefore please go through your issues and check:
- can the issue be closed (obsolete, dupe)
- did you ask for more information, but the author of the issue didn't come back for a month
- should the bug be labelled as `important`, that is, we do not want to ship a `stable` build with the issue.
- is the issue properly labeled: `feature request` vs. `bug`, labelled with a functional area.
- check the milestone and assign it to July if you plan to close the issue during this iteration.

As you do so, please collect questions you have regarding issue management that is not covered in our [issue tracking](https://github.com/Microsoft/vscode/wiki/Issue-Tracking) page and add them as comments to this issue.

### Zurich

- [x] @joaomoreno
- [x] @bpasero 
- [x] @weinand 
- [x] @isidorn 
- [ ] @alexandrudima 
- [x] @jrieken 
- [x] @sandy081 
- [ ] @dbaeumer 
- [ ] @egamma

### Redmond

- [ ] @kieferrm 
- [x] @Tyriar 
- [x] @chrmarti 
- @rebornix

**Comment by sandy081** [comment]
Done reviewing my issues. Most of the issues I have, I could process it as per points mentioned in tracking.

**Comment by Tyriar** [comment]
Are we going to go through the 300-odd unassigned issues as part of this? https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee

**Comment by bpasero** [comment]
Imho every issue should have an owner. So +1

**Comment by Tyriar** [comment]
@bpasero same, it's difficult to find an owner for some of the random feature requests is the only problem. We should change the inbox tracking query to include unassigned issues if this is desirable.

**Comment by bpasero** [comment]
I think this got easier with being able to assign multiple owners. So, if in doubt, just pick a couple. And yes, inbox tracking is just looking at issues without owner 👍

**Comment by Tyriar** [comment]
Created https://github.com/Microsoft/vscode/issues/9862 to follow up assigning unassigned issues.
