### ISSUE TITLE
Search symbol on vscode and pushing of religion is very offensive to me

### ISSUE THREAD

**Issue by vitorbarbosagoncalves** [microsoft/vscode#87537]
The logo used to search on vscode highly resembles the Ankh hieroglyph used on the ancient Egypt. As you all know, slavery was a big thing on the ancient Egypt and that offends me, A LOT.

Although I'm no slave (only to the daily grind of life) or I have no history, that I know of, of relatives being treated as such, just thinking on the fact that such a horrible and vile act was done throughout the years and that a lot of people were hurt because of that really, really offends me... I just shed a tear of pain, yet even if that was not the case, pushing religious symbols as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika. 

Also, I'm a Christian and I celebrate Christmas, why not add a christmas hat since in 4 days it's the big day and I'm getting presents :)). That would help ease the pain that you made me go through by reminding me that slavery is a thing.

Related: #87268

![Capture](https://user-images.githubusercontent.com/58522298/71311944-42b48600-241d-11ea-96bf-fc127f09925f.PNG)
![583px-Ankh svg](https://user-images.githubusercontent.com/58522298/71311951-5c55cd80-241d-11ea-8a55-8ea6f25cf988.png)

**Comment by filip-minx** [comment]
It also very much resembles a magnifying glass. I am offended because a magnifying glass once fell on my foot.

**Comment by PaoloTCS** [comment]
The Ankh symbol comes from De Nile!

**Comment by jlillyreed** [comment]
Butthurt christians, get over yourselves

**Comment by ethsmith** [comment]
Christians don’t act like this. This is just some person that is either trolling the devs or actually needs to rethink his/her priorities on what should offend him.

**Comment by iosvanyd1** [comment]
@jlillyreed this is clearly a troll. He starts by saying no religion and then jumps to Christianity. I have to admit it's pretty good sport 😂

**Comment by gabrieltaets** [comment]
I find it funny that the bot was probably adjusted to close these issues automatically

**Comment by DRD161** [comment]
100% troll 🤣 just joined Github December 4. Thanks I needed a good laugh.

**Comment by fakhrimf** [comment]
I had a good laugh there 🤣

**Comment by xpinero** [comment]
Every symbol has offended everyone at one point or another. We are all slaves to one thing or multiple. A supposed Christian wouldn't care about getting gifts as much if they actually were Christians and knew the meaning behind Christmas. Everyday is a gift... Don't waste it being offended.

**Comment by Blackbear710** [comment]
what ah pussyy

**Comment by jeffschwartz** [comment]
I'm an anarchist and that means I'm against all codes and it offends me that your editor's name has the word "code" in it. Please remove the word "code" from your editor's name immediately and I mean make that your numero uno priority. Us anarchists shouldn't be subject to persecution just because we are anti everything that you hold sacred and dear!

Other than that, us anarchists ♥ your editor ;)

**Comment by halr9000** [comment]
Those who mistakenly believe this is serious--you need to click on the related issue to understand the joke.

**Comment by mxxcon** [comment]
I'd like to point out that @vitorbarbosagoncalves post is a blatant violation of github community's anti-harassment polity.
https://help.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed
They created a brand new github account specifically to mock another user's personal views.
Is this the kind of behavior this project and github at large wants to tolerate?

**Comment by FireDog31262** [comment]
It's a magnifying glass symbol...get over yourselves you little snow flakes!!!

**Comment by GaryLBaird** [comment]
> Butthurt Christians, get over yourselves

Who's butthurt? I mean you're are talking about a graphic that just happens to look like something Christian symbol. Seems you need to get over the pareidolia and stop worrying about controlling others.

**Comment by JayBeavers** [comment]
> I'd like to point out that @vitorbarbosagoncalves post is a blatant violation of github community's anti-harassment polity.
> https://help.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed
> They created a brand new github account specifically to mock another user's personal views.
> Is this the kind of behavior this project and github at large wants to tolerate?

And yet, saying that a Santa hat is related to the death of millions of Jews and comparing Christianity to Nazi symbology is not harassment, eh?  Your definition of harassment is very limited.

**Comment by mxxcon** [comment]
> 
> 
> > I'd like to point out that @vitorbarbosagoncalves post is a blatant violation of github community's anti-harassment polity.
> > https://help.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed
> > They created a brand new github account specifically to mock another user's personal views.
> > Is this the kind of behavior this project and github at large wants to tolerate?
> 
> And yet, saying that a Santa hat is related to the death of millions of Jews and comparing Christianity to Nazi symbology is not harassment, eh? Your definition of harassment is very limited.

If you have a problem with that issue, post there and raise it up with the project's team or github. My post is about this issue.

**Comment by gabrieltaets** [comment]
> > > I'd like to point out that @vitorbarbosagoncalves post is a blatant violation of github community's anti-harassment polity.
> > > https://help.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed
> > > They created a brand new github account specifically to mock another user's personal views.
> > > Is this the kind of behavior this project and github at large wants to tolerate?
> > 
> > 
> > And yet, saying that a Santa hat is related to the death of millions of Jews and comparing Christianity to Nazi symbology is not harassment, eh? Your definition of harassment is very limited.
> 
> If you have a problem with that issue, post there and raise it up with the project's team or github. My post is about this issue.

Except that that issue is closed for discussion.

**Comment by KyzaGitHub** [comment]
This appeared on my mobile Chrome browser's news feed, and I have to say that I'm highly amused by this entire conversation. Google knows me well.

**Comment by bmfkai** [comment]
The Christians seem to be fine using Roman letters when it was the Romans who crucified Jesus... just sayin :P

**Comment by kevinrodriguez-io** [comment]
To all the people talking s**t about christians. This is a parody issue. This is sarcasm; the Christian stuff only serves the narrative. See the related link, Which truly happened.

**Comment by Bigtimbers** [comment]
The real issue is religious intolerance. That's just plain wrong and also against the constitution. Let's all have a cheer for religious freedom in our country(or wherever you're from).

**Comment by colindekker** [comment]
I am offended by the complete off the charts level of political correctness I have to deal with day in day out.

**Comment by Nexowned** [comment]
I am offended people are using the previous instance of this "meme" to continue this, if you don't have anything valid to report, please keep your memes to yourself.
This makes everyone of you look like little 5 year old girls twirling around in tutu's..
Im ashamed to call myself a human being sometimes....

**Comment by Bryanaug1** [comment]
I hope this is a joke because its ridiculous on so many levels.  Christians also enslaved loads of ppl, can confirm am black and american for many many generations so I have ancestors that were enslaved and forfully converted by the wizard lovers. Also every bronze age civilization had slaves, they sucked in that way, just a fact of history. And finally why is it you always hear Christians bitching about being offended? I'm a pegan and I constantly see Christians talk about how I worship demons and am going to hell(as if that doesnt sound awesome to me). If this isnt a joke post then honestly fuck you OP

**Comment by GeorgeWillaman** [comment]
Can we please stop with filing fake issues that pertain to no importance, and wasting everyone's time in the process?

**Comment by samomar** [comment]
Some of you guys need to apt-get install memes

**Comment by prajaybasu** [comment]
grateful for vscodium

**Comment by sonicpp** [comment]
Is it fixed yet?
