### ISSUE TITLE
The snowflake icon ❄ is, sadly, gone

### ISSUE THREAD

**Issue by Erableto** [microsoft/vscode#87536]
Issue Type: <b>Bug</b>

Recently, the Santa icon 🎅 was changed with a snowflake icon ❄ (read #87440 for more info). But, somehow, the snowflake is now gone. What happened?

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2397)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (3.39GB free)|
|Process Argv|D:\UNIVERSIDAD\4o_CARRERA\1er_CUATRIMESTRE\IMD\P3+4+5\P4.py|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (84)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
racket-repl|And|1.5.8
language-mcfunction|arc|0.16.0
webbrowse|aur|0.0.1
code-gnu-global|aus|0.2.2
speech|bie|0.0.3
LinkCheckMD|bla|0.1.5
pdf-view|bri|0.3.6
yacc|car|1.3.1
vscode-chez|ch|0.1.2
vscode-markdownlint|Dav|0.33.0
scheme|der|0.0.1
marshal-command-code|din|1.1.2
racket|Dmy|1.2.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.4
docs-images|doc|0.0.1
docs-markdown|doc|0.2.29
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.36
docs-yaml|doc|0.2.4
xml|Dot|2.5.0
magic-racket|evz|0.4.5
lex-flex-yacc-bison|fau|0.0.3
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.162
url-preview|Her|0.0.2
mcide|int|0.0.4
latex-workshop|Jam|8.5.0
vscode-edit-csv|jan|0.2.5
svg|joc|1.0.6
chat|kar|0.31.0
racket|kar|0.0.3
vscode-format-context-menu|lac|1.0.4
mcjson|Lev|0.4.1
bison|lun|0.1.0
lex|lun|0.1.0
web-browser|mas|0.0.1
vscode-html-format|moh|0.0.3
vscode-language-pack-es|MS-|1.41.2
extension-manifest-editor|ms-|0.1.5
vscode-edge-devtools|ms-|1.0.6
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
azure-account|ms-|0.8.7
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2
github-issues-prs|ms-|0.9.2
powershell|ms-|2019.12.0
powershell-preview|ms-|2019.12.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.1404
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
vsonline|ms-|1.0.1424
debugger-for-edge|msj|1.0.13
vscode-sanddance|msr|1.2.12
clips-lang|ner|1.0.2
datapack-helper|pca|0.6.1
clips|pho|0.0.1
qub-textedits|qub|1.0.0
clips|rcr|0.0.1
prolog|reb|0.0.4
scheme|reb|0.0.2
java|red|0.54.2
vscode-yaml|red|0.6.1
vscode-scheme|sjh|0.4.0
shader|sle|1.1.4
syntax-racket|spo|0.0.4
mcscript|Ste|0.0.3
rewrap|stk|1.9.1
code-spell-checker|str|1.7.20
vscode-mc-shader|Str|0.8.5
pdf|tom|0.5.1
vscode-websearch|Two|1.5.0
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
vscode-icons|vsc|9.6.0
openTheWebPage|zhh|0.0.1
minecraft-lang-colorizer|zz5|1.0.0

(9 theme extensions excluded)

</details>

**Comment by Toby-Larone** [comment]
@Erableto It's now a configurable setting as stated in the [pinned issue](https://github.com/microsoft/vscode/issues/87440)

**Comment by Erableto** [comment]
> @Erableto It's now a configurable setting as stated in the pinned issue

Nice! Thanks ^^.
