### ISSUE TITLE
Build system overwhelmingly complicated and demanding, with very bad errors

### ISSUE THREAD

**Issue by Entomy** [microsoft/vscode#87534]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce (per [wiki](https://github.com/microsoft/vscode/wiki/How-to-Contribute)):

1. Git 
![image](https://user-images.githubusercontent.com/25399505/71310978-a2dd0500-23e8-11ea-8fa3-2b47c352df16.png)
2. Node.JS, x64, version >= 10.x, <= 12.x 
![image](https://user-images.githubusercontent.com/25399505/71310987-bc7e4c80-23e8-11ea-9436-e2e2ccc72b1f.png)
3. Yarn 
![image](https://user-images.githubusercontent.com/25399505/71310995-d3bd3a00-23e8-11ea-866b-ef4f95479aea.png)
4. A C/C++ compiler tool chain for your platform: 
   * Select VC++ 2015.3 v14.00 (v140) toolset for desktop on the right hand side 
![image](https://user-images.githubusercontent.com/25399505/71311149-f81a1600-23ea-11ea-9f00-58e4874bfc50.png)
5. Restart your computer (I can't screenshot this, just take my word that I did)
6. Warning: Make sure your profile path only contains ASCII letters, e.g. John, otherwise it can lead to node-gyp 
![image](https://user-images.githubusercontent.com/25399505/71311158-1aac2f00-23eb-11ea-8439-4d72a95d6325.png)
7. Install and build all of the dependencies using Yarn 
![image](https://user-images.githubusercontent.com/25399505/71311167-44fdec80-23eb-11ea-9a83-dc5595bd6988.png) ![image](https://user-images.githubusercontent.com/25399505/71311190-a2923900-23eb-11ea-811a-01af1a4bb21e.png)

Now, I beleive this may be related to #1747, so I follow the solution there. 
![image](https://user-images.githubusercontent.com/25399505/71311241-ef760f80-23eb-11ea-9d48-50d0e12c4400.png)

But that still fails with 
![image](https://user-images.githubusercontent.com/25399505/71311274-1c2a2700-23ec-11ea-8676-fe370188a157.png)

So I go to the page cited in the error message which largely directs me to do what I have already done. It is finding the correct python binary.
![image](https://user-images.githubusercontent.com/25399505/71311412-d6ba2980-23ec-11ea-86fe-21cca704f455.png)

I have VS2019 installed as well, so I try directing things to use that. 
![image](https://user-images.githubusercontent.com/25399505/71311484-3f090b00-23ed-11ea-89c2-d98b9ea5093f.png)

One would assume from various documentation here and on related tools that this should not work, and yet actually did work. However at this point about 6.7 additional GB of storage has been used up, which is absolutely unreasonable, as we're getting into video game territory, for just dev tools.

Continuing on with the instructions. 
![image](https://user-images.githubusercontent.com/25399505/71311621-44b32080-23ee-11ea-8bd4-5ee805c5aa87.png) 
![image](https://user-images.githubusercontent.com/25399505/71311636-96f44180-23ee-11ea-91a9-0eab8664119d.png)

So my understanding is, everything finally worked. Check filesystem usage and... it's over 15GB at this point. I actually had to find stuff to remove because I've nearly maxed out the drive all of this is happening on. Which brings up a good point, boot drives aren't always massive and all of this being dumped on a single drive with no control can be highly problematic.

![image](https://user-images.githubusercontent.com/25399505/71311674-1aae2e00-23ef-11ea-8710-a68d856de6b8.png)

At this point my system starts to get highly unstable. The developer instance of vs code is finally running, but an additional 1.1GB of storage has been used up, now putting it over 16GB.

Does this issue occur when all extensions are disabled?:
N/A, as this isn't about the editor program, but rather the editor sources/build-system.

The barrier to contributing is extremely high, as there is a remarkable amount of things to install. Most of the requirements are poorly documented or even have out of date documentation, which includes this repo's wiki. Furthermore, the amount of storage required for doing development is rediculous, being the equivalent of 3-4 1080p videos, or many non-AAA games. In fact, the amount of storage space the various required tooling used up exceeds the installation size of the VisualStudio instance that I use regularly. I had to spend over three hours trying to figure things out, because several failures I've encountered within the required tooling had unintelligible errors.

This needs to be simplified, better documented, and trimmed down.

**Comment by mohsinhijazee** [comment]
Tried to do the same on Mac and the setup process is brittle, mainly it is all about luck it seems but I am not sure if it can be simplified given the amount of functionality and features this piece of software offers. What can be done however is a startup check list program to check all the required tools, their versions, libraries (something like flutter doctor) which could be the first step.

**Comment by kieferrm** [comment]
@chrmarti This could be addressed with`.devContainer.json`?

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by Entomy** [comment]
@brlebtag While I understand your concern and partially agree with your frustration, please do not bring this into unrelated issues. There's plenty of issues already related to that. Do not get technical issues locked down or closed for going off topic.

**Comment by chrmarti** [comment]
Using a DevContainer would compile the native modules for Linux and not Windows / Mac, so the result would need to be run in the container (unless you're on Linux). I'm using such a setup with a VNC server running inside the container, but I wouldn't expect that to help here (assuming this is for developing the desktop client, for the web client a DevContainer would make sense).
