### ISSUE TITLE
When renaming destructured arguments, solution is verbose

### ISSUE THREAD

**Issue by afeinman** [microsoft/vscode#87535]
Currently VSCode does an amazing job of renaming variables. However, when renaming, destructuring assignments often end up overly wordy / misleading.

For example:
```
function contrivedExample(props: PropType) {
    const { prop1, prop2, prop4 } = props;
    return { prop3: prop4 };
}
```

When renaming `prop4` to `prop3`, this correctly becomes:

```
function contrivedExample(props: PropType) {
    const { prop1, prop2, prop3 } = props;
    return { prop3: prop3 };
}
```

but it would be even nicer if it could simply become:
```
function contrivedExample(props: PropType) {
    const { prop1, prop2, prop3 } = props;
    return { prop3 };
}
```

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by afeinman** [comment]
I think you meant to troll people over in another issue?

**Comment by mjbvz** [comment]
Actually, this is not related to `"javascript.preferences.renameShorthandProperties"` as I first thought

However this this feature is powered by the TypeScript project, so please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) for this

**Comment by afeinman** [comment]
https://github.com/microsoft/TypeScript/issues/35923
