### ISSUE TITLE
Ho-Ho-Hold up a second, Racist terms in code??

### ISSUE THREAD

**Issue by LWSS** [microsoft/vscode#87532]
I kept a hearin a whole lotta hub-bub bout' this here vs code. So I thought, shieeet, maybe i'll give it a go, I could always use me one of them 6 figure microsoft jobs. 

However as I was browsin the code in my Jetbrains WebStorm(Take 25% off with promo code: SANTA - expires Jan 1st, 2020), I noticed some very racist terms being used freely by the development team.

Did they really think that a black man would never look at their code?

```
./src/bootstrap.js:283: * Prevents appinsights from monkey patching modules.
./src/bootstrap.js:288:	process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = true; // Skip monkey patching of 3rd party modules by appinsights
./src/vs/base/test/common/lifecycle.test.ts:76:		const ref4 = collection.acquire('monkey');
./extensions/python/test/colorize-results/test_py.json:124:		"c": " Bananas the monkey can eat.",
./extensions/python/test/colorize-results/test_py.json:322:		"c": "Make the monkey eat N bananas!",
./extensions/python/test/colorize-fixtures/test.py:4:	# Bananas the monkey can eat.
./extensions/python/test/colorize-fixtures/test.py:7:		'''Make the monkey eat N bananas!'''
```
I have been called a monkey many times in my life, but I never thought that microsoft would do it themselves, shame on them.

Here is a link to a random article (that neither you or I will read) that easily helps boost my credibility( http://theconversation.com/comparing-black-people-to-monkeys-has-a-long-dark-simian-history-55102 )

Until issue is fixed, I am instructing all of my black brothers and sympathizers at microsoft to halt work on this project.

And for the racists in question, we got our eyes on you, and don't expect anything but coal from santa this year.

![monkey-according-to-ms](https://media.npr.org/assets/img/2016/12/09/santa-larry-128215_wide-e82af2415a460efbc95d15b1b8f5cae42adfddb4.jpg?s=1400)

**Comment by BlackYuzia** [comment]
lol. Where is my Vederko of OR?

**Comment by vladnex8** [comment]
WOW. I can't believe Microsoft would do something like this! If they are this open about being racist, they're probably sexist AND transphobic too! I am litearlly shitting and pissing and cumming right now!!!

**Comment by nzalog** [comment]
A python killed my first born. That's offensive...

**Comment by coding4truth** [comment]
Wow, that IS incredibly racist. These developers are disgusting.

Have you noticed the developers who moderate this Github are always white too? Constantly locking down discussion threads and preventing minority voices from being heard sure sounds like they are exerting their white privilege over us.

**Comment by BRA1L0R** [comment]
the fuck

**Comment by LWSS** [comment]
> lol. Where is my Vederko of OR?

bucket of what?

**Comment by SRGOM** [comment]
Well written
