### ISSUE TITLE
use of measured RAM

### ISSUE THREAD

**Issue by AlexisRojasF** [microsoft/vscode#87539]
the visual studio is using the ram in an exaggerated way noc because it was because the problem was not before, and proceeded to de-list and delete all the plugin data etc but the error remains

**Comment by AlexisRojasF** [comment]
![Sin título](https://user-images.githubusercontent.com/45072631/71312622-e7719c00-23fa-11ea-9f7e-4a348c8cc0d4.png)

**Comment by AlexisRojasF** [comment]
I am not sure where the problem is coming from, it only happens when dot ctrl + space to auto contain the argorithms, I think it must be an error of some plugin installed or a problem with some process in node I am already doing some work with ionic

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by dbaeumer** [comment]
@AlexisRojasF can you please provide the information requested here: https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu

Otherwise it is hard for us to understand what is causing this. Thanks.

**Comment by AlexisRojasF** [comment]
Open Process Explorer 
![Sin 2png](https://user-images.githubusercontent.com/45072631/71384968-7a086b80-25b2-11ea-94db-f8bfa641b27c.png)

**Comment by AlexisRojasF** [comment]
Open Process Explorer with the externalities disabled 
![sin](https://user-images.githubusercontent.com/45072631/71385093-5a257780-25b3-11ea-91a0-4f915f6aa9bd.jpg)

**Comment by AlexisRojasF** [comment]
using the code - status command

C:\Windows\system32>code --status

Version:          Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G (4 x 2695)
Memory (System):  15.39GB (0.28GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    2       84   13408  code main
    0      100     348     gpu-process
    0       37     832     shared-process
    8      167    3816     window (ÔùÅ noticia.component.ts - noticias - Visual Studio Code)
    0        4    5564       C:\Windows\System32\cmd.exe
    0        6    6560       console-window-host (Windows internal process)
    0        7    9164       watcherService
    0        0   10368         console-window-host (Windows internal process)
    5       65   12604       extensionHost
   17     1859     976         electron_node tsserver.js
    0       43   14780           electron_node typingsInstaller.js typesMap.js
    0       53    5344         electron_node tsserver.js
    0       11    5940         "C:\Users\AlexisRojas\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\AlexisRojas\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=12604
    8      127   11984         "C:\Users\AlexisRojas\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\AlexisRojas\.vscode\extensions\angular.ng-template-0.900.3\server --logFile c:\Users\AlexisRojas\AppData\Roaming\Code\logs\20191223T175508\exthost1\Angular.ng-template\nglangsvc.log --logVerbosity terse --ngProbeLocations c:\Users\AlexisRojas\.vscode\extensions\angular.ng-template-0.900.3\server --tsProbeLocations c:\Users\AlexisRojas\.vscode\extensions\angular.ng-template-0.900.3 --node-ipc --clientProcessId=12604
    0        7   13240       searchService
    0        1   11472     electron-crash-reporter
    0       63   11964     window (Process Explorer)

Workspace Stats:
|  Window (ÔùÅ noticia.component.ts - noticias - Visual Studio Code)
|    Folder (noticias): 343 files
|      File types: png(79) js(37) ts(34) json(14) h(14) md(12) html(12) m(11)
|                  xml(9) scss(9)
|      Conf files: package.json(5) tsconfig.json(2) tslint.json(1) sln(1)

**Comment by dbaeumer** [comment]
@AlexisRojasF thanks for the additional information.

**Comment by mjbvz** [comment]
@AlexisRojasF Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
