### ISSUE TITLE
clicking back to Search pane repopulates previously dismissed search results

### ISSUE THREAD

**Issue by hansifer** [microsoft/vscode#87540]
Issue Type: <b>Bug</b>

1. Confirm that the setting `search.searchOnType` is set to `true`
2. Select the Search pane
3. Search on some text that produces results
4. Dismiss the first result by clicking the line item's x icon
5. Select the Explorer pane
6. Select the Search pane again
7. Observe that the previously-dismissed search result reappears, despite no change in search text

I contend that clicking away from and then back to search results should not reset the set of results that have been dismissed, since the search text itself has not changed.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (16.36GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by JacksonKearl** [comment]
I can't seem to reproduce this. Does it happen every time for you or only occasionally?

**Comment by hansifer** [comment]
Strangely, I'm no longer able to repro either. If it happens again I can
open a new ticket with more detail.

Thanks.
