### ISSUE TITLE
Bug report closed as "duplicate" without saying what it's a duplicate of

### ISSUE THREAD

**Issue by theres-waldo** [microsoft/vscode#87545]
A couple of weeks ago I filed https://github.com/microsoft/vscode/issues/86435.

It was close as a "duplicate" by **vscodebot**, but there is no indication of which issue it's a duplicate of.

Was this a mistake on the part of the bot?

I'd like to know what the duplicate issue is (if there is one), so that I can follow discussion / progress there.

**Comment by gjsjohnmurray** [comment]
My guess is #67268 which was the 4th match when I searched issues for 'find references breadcrumb'

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by jrieken** [comment]
Yeah, I do that to save time (GH search is for me as bad as it is for you) However,  I am also adding labels, e.g `breadcrumbs`, which will help you to narrow down the set of potential issues drastically.

<img width="335" alt="Screenshot 2019-12-23 at 10 00 06" src="https://user-images.githubusercontent.com/1794099/71347652-02631e00-256b-11ea-8502-970ffb606da9.png">
