### ISSUE TITLE
File -> Exit should only close current window

### ISSUE THREAD

**Issue by henrygab** [microsoft/vscode#87546]
Issue Type: <b>Bug</b>

### Steps to Repro

1. Open a first instance from cmd.exe, e.g., `code c:\Dir1`
2. Open a second instance from cmd.exe, e.g., `code c:\Dir2`
3. While the second instance of VS Code has focus, press `Alt-F, X` (or use menu for `File -> Exit`

### Expected Results:

The second instance of VS Code exits,
while the first instance of VS Code remains open.

### Actual Results:

All instances of VS Code exit.

### NOTE:

This occurs even with ALL extensions disabled.

### Additional Scenario:

1. Set VS Code as the editor for git commits (made from command line, not from with VS Code)
2. Edit something in VS Code, leaving multiple files open
3. From cmd line, git commit (which launches VS Code)
4. To allow git to finish, need to exit that instance of VS Code
5. use `File -> Exit` or press `Alt-F, X`

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19013

Extensions: none

**Comment by kieferrm** [comment]
There is always only one instance of VS Code running.  What happens in step 2 is that the first instance opens a second window.

**Comment by gjsjohnmurray** [comment]
Any difference if in step 2 you add the -n argument?

`code -n c:\Dir2`

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by henrygab** [comment]
> There is always only one instance of VS Code running.  What happens in step 2 is that the first instance opens a second window.

OK, updated title to indicate this should only close the first _**window**_.

> Any difference if in step 2 you add the -n argument?
> code -n c:\Dir2

Unfortunately, no.

**Comment by henrygab** [comment]
@brlebtag -- What do you mean by the following comment?

> Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by bpasero** [comment]
This will not be possible with our current design. If you truly want to run 2 instances of VSCode (where File > Exit only closes the one instance), you can run "`code --user-data-dir <some dir>`" from the command line.

**Comment by henrygab** [comment]
@bpasero -- Thank you for the possible workaround using `--user-data-dir`.  This **almost** works.

I have modified my `.gitconfig` so that the editor is `code --wait --new-window --user-data-dir C:/Users/Name/AppData/Local/Temp/git_19118`.

If I already have an existing VS code window open, then `git commit` will correctly open the new window, and exiting that process has zero effect on my "real" VS code editors.

However, if I don't yet has VS code window open, and start a commit (using the alt. user-data-dir), then start code for another directory (e.g., `code .`), exiting any window will exit them all.  I think this is because the new windows "latch onto" (open as new windows of) the instance that's handling the commit.

I think I'll have to simply change my git commit editor to something other than code.  VS Code appears unable to simply and easily support this simple user experience (isolated VS Code instance), and it **really** sucks to keep losing my place in all my code editors, just because I prefer to commit from the command line and have muscle-memory for closing an editor.

**Comment by henrygab** [comment]
OK, I found an workaround, that allows this to work substantially as expected.  I put this here for anyone who searches through closed issues, in case it is helpful to them:

I'm running on Windows, but the instructions appear easily translated to Linux/MacOS  … just edit `code` instead of `code.cmd`....

<details>
  <summary>Expand for instructions for setting up VS Code as git commit editor on Windows</summary>

  <p>

1. Discover where code lives:  `where code`
    [ ] e.g., output could include `C:\Users\Contoso\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd`)
2. Verify that code is using the following path (Windows specific) for the user data directory:
    [ ] e.g., `echo.%APPDATA%` --> should be `C:\Users\Contoso\AppData\Roaming` or similar
    [ ] e.g., `dir %APPDATA%\Code` --> should have storage.json, which includes recently-used files at the end
3. Change to that directory where code lives.
    [ ] e.g., `cd /d "C:\Users\Contoso\AppData\Local\Programs\Microsoft VS Code\bin\"`
4. Backup the script and create a copy for git to use for commits:
    [ ] e.g., `copy code.cmd code.cmd.original`
    [ ] e.g., `copy code.cmd git-commit-code.cmd`
5. Explicitly indicate the user data directory in `code.cmd`, by adding the following parameter:
    [ ] `--user-data-dir %APPDATA%\Code\`
6. Explicitly indicate an alternate data directory for use by git commit, by adding a different parameter:
    [ ] `--user-data-dir %TEMP%\git_code_93820` -- the number can be anything …
    [ ] `--wait` -- add this parameter also, so git will wait for the window to be closed when done editing the commit message.
7. Modify git config to use the new command script:
    [ ] e.g., `git config --global --unset core.editor`
    [ ] e.g., `git config --global --set core.editor git-commit-code.cmd`

</details>

### What this does, and does not, do...

This basically forces git to use a distinct instance of code compared to that launched via `code`.  In other words, all git commits are funneled to one instance of code, while all other launches via `code` are funneled to a second instance of code.

Closing (Alt-F4 or Alt-F, X) the git commit window will therefore **_not_** cause the "normal" instance of code to exit / close existing windows.  However, doing so **_will_** close all instances of commits that are currently open.  Similarly, closing the "normal" instance of code will not accidentally close the git commit instance.

It's worth noting that this doesn't prevent accidentally closing multiple simultaneously open git commits.  To do that would require a distinct user data directory per git depot.  Doing so (and analysis of pros/cons) is an exercise left for the reader.

**Comment by henrygab** [comment]
**_WARNING:_** Updates of VSCode will overwrite the `code.cmd` file, and **_silently delete_** the `git-commit-code.cmd` file, if it is placed in the same directory.

In addition, VSCode does not allow overriding of existing command-line parameters by adding them a second time with a different value (e.g., `--user-data-dir` cannot be given twice).  Time to open some issues....
