### ISSUE TITLE
Powershell Terminal Display Issues

### ISSUE THREAD

**Issue by seltzer1717** [microsoft/vscode#87544]
Clarification: this has nothing to do with the keystroke config, it can be reproduced by just calling workbench.action.terminal.clear command directly.

- VSCode Version: 1.41.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Start Terminal (Powershell or CMD Prompt doesn't matter)
2. Start typing and all of the sudden the text shifts down
3. Terminal loses track where where the cursor is

Does this issue occur when all extensions are disabled?: Yes

Now this might sound like an issue that was already closed - "Terminal: broken text layout #19665". But that issue was closed claiming that Windows 10 update - KB4020102 fixes the problem. However, that was a patch for 1703. I'm on 1903, so I should have that patch.

I've been able to reproduce the problem with consistency in the latest Insiders build by configuring the following key binding and using it:

{
  "key": "ctrl+k",
  "command": "workbench.action.terminal.clear",
  "when": "terminalFocus"
}

If this is not configured, the issue never arises, if you configure this it starts happening.

I suspect that the "workbench.action.terminal.clear" command is doing something not intended to the PowerShell terminal.

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.
