### ISSUE TITLE
pandas definitions not found

### ISSUE THREAD

**Issue by zbinkz** [microsoft/vscode#87547]
- VSCode Version: 1.41.1
- OS Version: Debian buster 10.2

Steps to Reproduce:
`
import pandas
import quandl
df = quandl.get("WIKI/GOOGL")
df.fillna(value=-99999, inplace=True)
`

1. Definition of pandas function fillna() not available whether using system pandas or from pip (pip3), regardless of python version. The same applies to all other pandas functions.

![Screenshot_20191221_175253](https://user-images.githubusercontent.com/46252795/71314680-ce78e300-241a-11ea-913e-f98acd851903.png)

**Comment by kieferrm** [comment]
Please file the issue against the Python extension here: https://github.com/Microsoft/vscode-python/issues. Thank you!
