### ISSUE TITLE
High consumption of CPU

### ISSUE THREAD

**Issue by pegasus1982** [microsoft/vscode#87542]
I have a weird problem.
I am developing react project.
Before installing [ i18n-iso-country](https://www.npmjs.com/package/i18n-iso-countries), I could not feel any complaint.
But after installing this package, VScode consumes much CPU.
![image](https://user-images.githubusercontent.com/38883905/71313621-e022b080-2443-11ea-9687-9f4d0ebeeecd.png)

And all of hints not working properly.
I want to resolve this doomed situation.

This is my package.json file
``` json
{
  "name": "...-client",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "autoprefixer": "^9.7.3",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "concurrently": "4.0.1",
    "css-loader": "^3.3.0",
    "eslint": "^6.7.2",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-compat": "^3.3.0",
    "eslint-plugin-flowtype": "^4.5.2",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.17.0",
    "file-loader": "^5.0.2",
    "flow-bin": "^0.113.0",
    "html-webpack-plugin": "^3.2.0",
    "postcss-loader": "^3.0.0",
    "style-loader": "^1.0.1",
    "url-loader": "^3.0.0",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.9.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "@livechat/livechat-visitor-sdk": "0.35.2",
    "@livechat/saga-utils": "0.1.1",
    "@livechat/ui-kit": "0.2.13",
    "@material-ui/core": "3.0.3",
    "@material-ui/icons": "3.0.1",
    "@material-ui/lab": "3.0.0-alpha.15",
    "autosuggest-highlight": "3.1.1",
    "axios": "^0.18.0",
    "babel-runtime": "^6.26.0",
    "chart.js": "2.7.2",
    "date-fns": "1.29.0",
    "downshift": "2.2.2",
    "i18n-iso-countries": "^4.3.1",
    "jss-rtl": "0.2.3",
    "leaflet": "1.3.4",
    "moment": "2.22.2",
    "react": "16.5.1",
    "react-autosuggest": "9.4.1",
    "react-beautiful-dnd": "^9.0.2",
    "react-big-calendar": "0.19.2",
    "react-chartjs-2": "2.7.4",
    "react-dom": "16.5.1",
    "react-emotion": "^9.2.8",
    "react-google-maps": "9.4.5",
    "react-hot-loader": "^4.12.18",
    "react-leaflet": "2.0.1",
    "react-number-format": "3.5.2",
    "react-quill": "1.3.1",
    "react-redux": "^5.0.2",
    "react-router-dom": "4.3.1",
    "react-scripts": "1.1.5",
    "react-select": "2.0.0",
    "react-swipeable-views": "0.12.17",
    "react-text-mask": "5.4.3",
    "redux": "^3.6.0",
    "redux-create-reducer": "^1.1.0",
    "redux-devtools-extension": "^2.13.8",
    "redux-persist": "^5.4.0",
    "redux-saga": "^0.15.6",
    "redux-saga-requests": "^0.20.0",
    "redux-saga-requests-axios": "^0.7.4",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.2.0",
    "webpack": "^4.41.2",
    "webpack-merge": "^4.2.2"
  },
  "scripts": {
    "start": "webpack-dev-server --config webpack/config.dev.js --progress --content-base ./public --output-public-path /build/ --host 0.0.0.0 --port 3000 --watch-poll",
    "build": "webpack --config webpack/config.prod.js",
    "flow": "flow --include-warnings",
    "lint": "eslint webpack/* src/** --ext .js,.jsx,.flow"
  }
}
```

**Comment by kieferrm** [comment]
@pegasus1982  pls see https://github.com/microsoft/vscode/wiki/Performance-Issues for how to help us identifying performance issues.

**Comment by pegasus1982** [comment]
Issue Type: <b>Performance Issue</b>

While working on other workspace, I couldn't feel any complaints.

But once I switch to this workspace, VScode consumes much CPU.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	  7988	code main
    0	    14	  4512	   electron-crash-reporter
   38	    70	 11552	   shared-process
    0	   194	 14440	   gpu-process
    0	    64	 14916	   window (Issue Reporter)
    0	   253	 15136	   window (actionInstructions.js - spa-workspace (Workspace) - Visual Studio Code)
    0	    38	 11556	     watcherService
    0	    69	 13012	     extensionHost
    0	    66	  2452	       electron_node tsserver.js 
   18	   395	 14288	       electron_node tsserver.js 
    0	    45	 14228	         electron_node typingsInstaller.js typesMap.js 
    0	     6	 15544	     winpty-process
    0	    69	  1000	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    11	 12464	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (actionInstructions.js - spa-workspace (Workspace) - Visual Studio Code)
|    Folder (spa.com-web): more than 22367 files
|      File types: php(18448) js(185) md(143) json(81) meta(55) gitignore(52)
|                  dist(50) yaml(24) yml(21) jpg(8)
|      Conf files: package.json(2) makefile(1)
|    Folder (spa): 5719 files
|      File types: png(1638) php(1481) js(416) gif(261) yml(237) html(208)
|                  css(122) jpg(83) xml(46) htm(44)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.9.2

(1 theme extensions excluded)

</details>

**Comment by pegasus1982** [comment]
In my opinion the suspicious problem is `i18n-iso-country` npm module.
Because, before installing this module, I couldn't feel any problem.

Before installing this module, VScode worked properly and hints worked well.

But after installing this module, my environment were doomed.

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by dbaeumer** [comment]
@pegasus1982 can you please provide the additional information requested here: https://github.com/microsoft/vscode/wiki/Performance-Issues Without that information it is very hard for us to understand what is causing the performance problems.

**Comment by pegasus1982** [comment]
Hi @dbaeumer.
I have already posted information above.

I removed `i18n-iso-country` from package.json file.
So I can't high CPU usage of VScode after that.

When I remove it, I thought that that module wouldn't work.
But it did work without registration in package.json.

Anyway, my issue was solved.
