### ISSUE TITLE
VS code typescript errors

### ISSUE THREAD

**Issue by alland67** [microsoft/vscode#87543]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by kieferrm** [comment]
@alland67  You missed to copy the actual data into this issue report.

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
