### ISSUE TITLE
Autoformat multiple exports

### ISSUE THREAD

**Issue by ayoubdev** [Microsoft/vscode#8755]
- VSCode Version: 1.3.0-insider (2016-07-04)
- OS Version: Windows 10

Hello everyone,

I wonder if it's possible to change indentation behavior for javascript multiple exports (like multiple imports one). Indeed, autoformat feature currently outputs following:
```jsx
import {
	InjectEventEmitter,
	ProvideEventEmitter
} from "./decorator.js";

export {
Helper,
CustomPropTypes
};
```

Desired output:
```jsx
import {
	InjectEventEmitter,
	ProvideEventEmitter
} from "./decorator.js";

export {
	Helper,
	CustomPropTypes
};
```

**Comment by dbaeumer** [comment]
Moving to TS.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9540

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#53

**Comment by ayoubdev** [comment]
Not working in insider preview (2016 - 07 - 22)

**Comment by dbaeumer** [comment]
TS 2.0 is not out yet which contains the fix for this.
