### ISSUE TITLE
VSCode freezes after several 'menubarUpdate' on Ubuntu 16.04

### ISSUE THREAD

**Issue by JiamingJiao** [microsoft/vscode#87558]
- I installed vscode 1.41 on a workstation with Ubuntu 16.04 using the .tar.gz package.
- I used `./code --disable-gpu --verbose` to run it. After a few minutes it became totally not responsive. This happened every time. The last output on my terminal was `menubarUpdate` (Maybe not exact, I cannot access to the workstation when I am writing this), there were several same outputs before it.
- Other applications worked well after VSCode froze.
- Disabling git and all the updates checking did not solve this problem.
- Python extension was the only installed and used extension.
- I saw there are 5 processes (Sometimes less than 5 but at least 2) after I run VSCode using `top` command, they occupied about 4g RAM in total and their CPU usages were always below 5%. And it seemed those processes became idle frequently.
- I used the workstation through a remote desktop application.

- The workstation specs:
- E5 20 cores 40 threads CPU
- 512GB RAM (more than 300GB available when I was using VSCode)
- 8 Tesla V100 GPUs
- 7.5TB HDD RAID0

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by mrconter1** [comment]
He think it's funny to imitate [this](https://www.reddit.com/r/KotakuInAction/comments/ecnnuy/microsoft_removes_a_santa_hat_from_a_piece_of/).

**Comment by JiamingJiao** [comment]
There was a folder that contains lists of files that created by eclipse. After removing those files, VSCode could live a little longer time, but still crashed every 30 minutes. It seemed more likely to freeze when it’s idling.

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders
