### ISSUE TITLE
Incorrect link syntax in file vscode.d.ts

### ISSUE THREAD

**Issue by rwnkl** [microsoft/vscode#87559]
- VSCode Version: 1.41.1
- OS Version: irrelevant 

Steps to Reproduce:
1. file: vscode.d.ts
2. JSDoc type Declaration: line 2316
3. [location links][#LocationLink] -> (#LocationLink)

Does this issue occur when all extensions are disabled?: Yes

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by mrconter1** [comment]
He think it's funny to imitate [this](https://www.reddit.com/r/KotakuInAction/comments/ecnnuy/microsoft_removes_a_santa_hat_from_a_piece_of/).
