### ISSUE TITLE
"code" command-line utility isn't restoring the previous session

### ISSUE THREAD

**Issue by BrendanMartin** [microsoft/vscode#87555]
- VSCode Version: 1.41.1
- OS Version: Windows 10

When I'm done for the day I just shutdown without closing code and let Windows shutdown close everything for me. The next day I'll run `start /B "" code path/to/my/project` as part of a batch file and vscode will open my directory, but won't have any of my previous tabs open.

Steps to Reproduce:

1. Open folder in VSCode using `start /B "" code path/to/my/project`. Open tabs and use normally.
2. Shutdown computer without manually closing VSCode. Let Windows shutdown process close VSCode.
3. Restart computer
4. Reopen folder in VSCode using `start /B "" code path/to/my/project`. Previous session tabs are not restored.

I've checked similar issues to this and have set Hot Exit to onExitAndWindowClose, but the problem still occurs.

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by mrconter1** [comment]
He think it's funny to imitate [this](https://www.reddit.com/r/KotakuInAction/comments/ecnnuy/microsoft_removes_a_santa_hat_from_a_piece_of/).
