### ISSUE TITLE
Logging Feature request

### ISSUE THREAD

**Issue by Arman69** [microsoft/vscode#87552]
many time i'm change my machine. i was thinking my all setting saved with my account. just because that's usefull. if in case some one change its machine. and he want work urgently and he did not have his own machine. he's working with another machine. if he had there account with vscode. then he simply login and work.

logging feautre save our time. we don't need install any extansion. if we priously installed

**Comment by Serega124** [comment]
If "Logging" word means "log in and sync settings/extensions" then that feature is already in development. See #87479
