### ISSUE TITLE
Adding items to Autocomplete list does not seem to work after saving file.

### ISSUE THREAD

**Issue by mrconter1** [microsoft/vscode#87550]
### Hello!

I am using the code on this [repository](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample). Having "Untitled-1" works fine where as after saving it to "test.py" the item does not seem to have been added to the autocomplete list. I have run "npm install" in the folder multiple times but that does not seem to help. Here are the file extensions that does not work:

- .ts
- .c
- .cpp
- .js
- .py
- .sh

**Extensions that does work:**

- No extension (unsaved9
- .txt

**I have tested this on:**

- Machine A
- Ubuntu 18.04.2 LTS
- vscode 1.41.0
----------------------------------------------
- Machine A
- Ubuntu 18.04.2 LTS
- vscode 1.40.2
----------------------------------------------
- Machine B
- Windows 10
- Fresh install of vscode 1.41.1

**Steps for reproduction:**

1. Clone [this](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample) Git.
2. Run "npm install" in completions-sample folder
3. Open completions-sample folder in vscode
4. Choose "Start Debugging" under "Debug" to run the extension
5. Create new file and do not save.
5. Press ctrl+shift+p and choose "Trigger Suggest". A menu should pop up with items from the extension code such as "Hello World!".
6. Give the file an extension by saving such as ".py". Repeat step 5 and the menu will not contain any custom autocomplete items.

Running my extension with the --disable-extension flag results in the same behavior.

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by dbaeumer** [comment]
@mrconter1 thanks for your issue. In VS Code completion item providers are registered for a certain language. In the example for `plaintext`. This is why you don't see any code completion contributed by the extension in other languages. The list of language id can be found here: https://code.visualstudio.com/docs/languages/identifiers

I am closing the issue. If you have additional questions, please ping

**Comment by mrconter1** [comment]
Thanks!
