### ISSUE TITLE
scss User snippets not working with $ prefix 

### ISSUE THREAD

**Issue by danju4rizzl** [microsoft/vscode#87551]
Issue Type: <b>Bug</b>

When I try to use my user-snippet i.e : $color-white: #FFF scss variable name.

The issue:  ' $ ' is removed when I call it in my scss file as follow:  color-white: #FFF

My solution: I must add '$-' when naming my  scss snippet like this : $-color-white: #FFF

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.97GB free)|
|Process Argv|C:\Users\Riana\OneDrive\Desktop\Snippets|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by mrconter1** [comment]
He think it's funny to imitate [this](https://www.reddit.com/r/KotakuInAction/comments/ecnnuy/microsoft_removes_a_santa_hat_from_a_piece_of/).

**Comment by aeschli** [comment]
Yes, `$` is special in the snippet syntax as it is used for placeholders and other features. You need to escape it with a `\`
See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar for all the details.
