### ISSUE TITLE
 Italic not reflected in preview when entering markdown notation

### ISSUE THREAD

**Issue by aky100200** [microsoft/vscode#87564]
Issue Type: <b>Bug</b>

Create an empty md file called test.md.
write the following information.
```
### タイトル
- *見出し*
- _見出し_
- **見出し**
```

Open markdown preview.
The title, list, and bold are reflected in the preview, but the italics in the second and third lines are not reflected in the preview, but are reflected in the input editor in italics.

<img width="1066" alt="vscode_italic_disable" src="https://user-images.githubusercontent.com/43887641/71325904-c57d3400-2536-11ea-8fa6-a6455d8f8876.png">

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.04GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by mjbvz** [comment]
This works properly for me in VS Code insiders:

![Screen Shot 2020-01-22 at 6 11 28 PM](https://user-images.githubusercontent.com/12821956/72951257-a397ec80-3d42-11ea-9577-01eec797424b.png)

Are you still seeing this?

**Comment by mjbvz** [comment]
Closing as not reproducible for me in the current insiders builds
