### ISSUE TITLE
TypeScript and JavaScript Language Features (Extension)

### ISSUE THREAD

**Issue by aytacg26** [microsoft/vscode#87560]
We have written the needed data into yo
Issue Type: <b>Bug</b>

Error Message : The TypeScript Language Service died 5 times right after it got started. The Service will not be restarted. I started to write JavaScript code for my website and VSCode started to give this message every 30 minutes after starting VSCode. When it shows this message I close the VSCode and open it again and again after 30 minutes, it gave the same message. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.98GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
c-cpp-compile-run|dan|1.0.5
vscode-eslint|dba|2.0.11
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.17.0
CppSnippets|har|0.0.14
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
nodejs-repl|los|0.5.13
cpptools|ms-|0.26.2
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
ayu|tea|0.18.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.1

</details>
ur clipboard because it was too large to send. Please paste.

**Comment by David-Else** [comment]
Very likely related to: https://github.com/microsoft/vscode/issues/87521 ,https://github.com/microsoft/vscode/issues/87526 ,https://github.com/microsoft/vscode/issues/87470

So please look here how to give a full report and help solve this massively annoying bug! https://github.com/microsoft/vscode/issues/87224#issuecomment-567751919

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by aytacg26** [comment]
I did not understand what you mean with "_**To me this is almost equally offensive as a swastika**_"

**Comment by mrconter1** [comment]
He think it's funny to imitate [this](https://www.reddit.com/r/KotakuInAction/comments/ecnnuy/microsoft_removes_a_santa_hat_from_a_piece_of/).

**Comment by David-Else** [comment]
@brlebtag I agree Santagate was an outrage and things need to change, but please don't obstruct the issue tracker as bugs still need fixing!

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next).

Does that fix the issue?
