### ISSUE TITLE
cannot re-install or un-install vscode

### ISSUE THREAD

**Issue by dmsaw60** [microsoft/vscode#87562]
Issue Type
![Annotation 2019-12-22 102036](https://user-images.githubusercontent.com/59144489/71324848-b7350680-24a9-11ea-9818-efb20daaf4db.png)
: <b>Bug</b>

i installed vscode on windows10
after opening vscode - vscode opens correctly - after about 10 seconds i get an error box from from vscode saying "error5: access is denied" and setup is saying unable to create directory "c:\users\dtlsa\appdata\local\programs" (see attached pic).

after getting this error i tried to uninstall vscode however it stopped during the uninstall process giving the same error (see attached pic)

after trying and failing to uninstall i tried to reinstall vscode using fresh download from vscode website however that stopped during the install process failing with the same error (see attached pic)

the directory c:\users\dtlsa\appdata\local is on my hard drive however that is not my current user name and is not my current user directory and also it was never my current user name plus my windows10 system is on a desktop system only used by me and only used with my correct user name and never used by this "dtlsa" user name.

please suggest a way to proceed for correcting this error.

thanks

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.41019
vscode-yaml|red|0.6.1
python|tht|0.2.3

</details>

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by mrconter1** [comment]
He think it's funny to imitate [this](https://www.reddit.com/r/KotakuInAction/comments/ecnnuy/microsoft_removes_a_santa_hat_from_a_piece_of/).

**Comment by joaomoreno** [comment]
This is strange and it seems your system is wrongly configured since your AppData folder is indeed in dtlsa's home.

I suggest to use the system install: https://code.visualstudio.com/docs/?dv=win64
