### ISSUE TITLE
Snippets & Languages Overview & HTML documentation issues

### ISSUE THREAD

**Issue by PetaSoft** [microsoft/vscode#87563]
There are some documentation issues in the "Snippets" User Guide (https://code.visualstudio.com/docs/editor/userdefinedsnippets):
- The snippets EBNF grammar has an error and is incomplete (https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar):
  - The definition of "any" is wrong. It should be<br>
    `any ::= [tabstop | placeholder | choice | variable | text]+` <br>
    because e.g. the snippet `"for (const ${2:element} of ${1:array}) {"`is correct but is not part of the language definied by the grammar in the documentation. The snippet starts with a "text" part of the grammar, followed by a placeholder part, a text part, and finally another placeholder part. So, there must be the possibility of >=1 repetititions of any part of the right sight of the "any" definition.
  - The non-terminals "if" and "else" are part of the grammar but are not defined anywhere. I cannot use these parts as I do not know their definitions. Please add these definitions!
  - Maybe it is a good idea to give the reader of the documentation the hint that "any" is the entry point of the grammar and that every element of the language is derived from "any" such that newcomers to the topic have a better overall understanding.
  - The command **Preferences: Open Keyboard Shortcuts File** mentioned in section "Assign keybindings to snippets" (https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets) does not exist. The correct command is **Preferences: Open Keyboard Shortcuts (JSON)**.

- The list of known language identifiers (https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers) is not consistent with the list of language modes shown after pressing `Ctrl+K M`. You write at https://code.visualstudio.com/docs/languages/overview#_language-id that one can see the list of currently installed languages and their identifiers  in the **Change Language Mode** (`Ctrl+K M`) drop-down list, but the two list have the following issues:
  - There are known language identifiers (`abap`, `bibtex`, `latex`, `sass`, `tex`) which are not in the list of of language modes. If one needs to install an extension to get language support for these language ids, it would be very helpful when You mark these known language ids as only accessable by an extension in the list of known language ids. Maybe You can add links to concrete extensions for these language ids, too.
  - The list of language modes includes the language ids `hlsl`, `ignore`, `jinja`, `jupyter`, `log`, `perl6`, `pip-requirements`, `properties`, `search-result`, and `toml` which are not mentioned in the list of known languages. Please add these ids to that list and keep both lists identical.
  - Setting the property `"files.defaultLanguage"` in `settings.json` offers Intellisense but there are no suggestions for the language ids `html`, `css`, `git-commit`, `go`, `handlebars`, `json`, `jsonc`, `less`, `makefile`, `markdown`, `scss`, `search-result`, `shellscript`, `yaml`. However, there is a suggestion for `jsx-tags`. Using the latter suggestion, after opening a new file the section for the language mode in the status bar is empty. Probably `jsx-tags` is not a valid language id and should be removed from the intellisense list for that property. Once again, please keep the suggestion list identical to the list of language ids!

- The settings.json properties `"html.suggest.angular1"` and `"html.suggest.ionic"` are not valid and should be removed from the documentation at https://code.visualstudio.com/docs/languages/html#_intellisense

**Comment by jrieken** [comment]
Please file one issue per topic, not a collection of topics in one issue.

**Comment by PetaSoft** [comment]
@jrieken Should I close this issue, or will You close the issue, and what do You mean with *one issue per topic*? Is it okay to spit the issue in "Snippets documentation issues", "Language Overview documentation issues", and "HTML documentation issues", or will I have to spit the issue further into issues such that each represents a subsection of the current issue?

**Comment by jrieken** [comment]
Yeah, please close and file separate issue. Roughly an issue per bullet point or per small logic unit, like snippet grammar

**Comment by jrieken** [comment]
not actionable, too broad. closing
