### ISSUE TITLE
Menu items aren't sorted properly

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8756]
If you have menu items with and without a `group` we have problems sorting them properly and they show mixed. That's because we first sort them by group and the `compare` logic is flawed.

![screen shot 2016-07-05 at 12 50 00](https://cloud.githubusercontent.com/assets/1794099/16582396/043c6cec-42af-11e6-9c0a-7be1683e2e42.png)

**Comment by jrieken** [comment]
The flaw is that we compare the groups only when both items have one and else compare the titles, it should be that an item without a group is sorted after an item with a group.

**Comment by alexandrudima** [comment]
:+1: looked at the commit

**Comment by jrieken** [comment]
To **verify**

* have an extension that adds three items to the editor context menu where two have a group and one has not. Use titles `a`, `b`, and `c` where the menu item without group is called `b`
* Make sure that the item with a group are rendered together and that the item without shows below

**Comment by weinand** [comment]
starting to verify...
