### ISSUE TITLE
The default branch of this repo should not be called Master but Main since "master" is linked to slavery

### ISSUE THREAD

**Issue by LPN64** [microsoft/vscode#87561]
Hello,

I'm happy to find I didn't find anything related to master/slave in the code itself of VSCode, but the name of the branch itself is "master", which make sense since it's the default name git gives.

But as 2020 approaches, it would be nice to be able to move on to a brighter future and stop using this kind of vocabulary.

Have a nice Christmas.

-LPN64

**Comment by Roguezilla** [comment]
Is this a troll or something? Please tell me it is.

**Comment by Roguezilla** [comment]
Is this a troll? Please tell me this is a troll.

**Comment by hugmouse** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by brlebtag** [comment]
Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by mrconter1** [comment]
He think it's funny to imitate [this](https://www.reddit.com/r/KotakuInAction/comments/ecnnuy/microsoft_removes_a_santa_hat_from_a_piece_of/).

**Comment by jcmfernandes** [comment]
> Is this a troll/bait issue? Please tell me it is.

https://github.com/antirez/redis/issues/5335

**Comment by alexandernst** [comment]
I agree, "master" sounds quite offensive to me.
