### ISSUE TITLE
rg.exe used high CPU when I launch VScode

### ISSUE THREAD

**Issue by anrananran** [microsoft/vscode#87577]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.18363
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T14:58:56.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0

Steps to Reproduce:

1. just launch vscode
2. open windows task manager
3. watch

Does this issue occur when all extensions are disabled?: No

screenshots:
<img src="https://s2.ax1x.com/2019/12/23/lSwYw9.jpg" >

**set config "search.followSymlinks": false, now everything is OK when I launch VScode again**.

for reference only

**Comment by roblourens** [comment]
Something is triggering a search when you launch vscode, either an extension or a user action. Sounds like the followSymlinks setting fixed it for you, that can be expensive for rg.exe, glad you figured it out!
