### ISSUE TITLE
Color Picker is not showing up in CSS

### ISSUE THREAD

**Issue by vbbalaji** [microsoft/vscode#87574]
Issue Type: <b>Bug</b>

When I hover over the hex color code, it used to display the inbuilt color picker. This was working till last week. Now its not showing the picker.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.86GB (12.56GB free)|
|Process Argv|--folder-uri file:///c%3A/Balaji/Personal/AHAR/aharkds|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
I can't reproduce. Can you attach a small code sample and maybe a screenshot ?

**Comment by vbbalaji** [comment]
![image](https://user-images.githubusercontent.com/26417800/71427154-fd918d80-2682-11ea-9127-25e7752a5888.png)

Im hovering on line 162 and dont see the color picker.

**Comment by vbbalaji** [comment]
Is there a way I can attach a video grab? I can show you I hover over that Hex code and nothing comes up...

**Comment by aeschli** [comment]
I tried to reproduce with
```css
.itemName {
    font-size: 3em;
    color: #fa45a2;
}
```
but I see the color picker when moving the mouse over `#fa45a2`.

Can you paste a reproducible example? Maybe add the full sample code?

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/71724546-ec8a0e80-2e30-11ea-80f7-b7e3220576ef.png)

**Comment by vbbalaji** [comment]
I have tried with ALL types of hex code, same result. Is there something else I can try to enable/disable to make this work? Also can you please compare your version and mine from the meta info above?

**Comment by aeschli** [comment]
I tested with 
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z

Can you reproduce with the example above?
Do you see other hovers? (Hovers can be enabled/disabled in the settings).
Did you try running code without any extensions enabled (Command: `Developer: Reload with Extensions Disabled`)

**Comment by vbbalaji** [comment]
Your second question did the trick. Editor: Hover was disabled!! Its working now. 

FYI: Few weeks ago VS Code crashed and restarted itself. Either that or the recent update disabled this option!
