### ISSUE TITLE
VSCode Terminal should allow navigation and selection of previous output using keyboard commands

### ISSUE THREAD

**Issue by jagdishrajan** [microsoft/vscode#87579]
In PowerShell ISE we can break out of the single line terminal command with Ctrl+Up and move the cursor across the terminal output for selection and copy.  Obviously the output remains read-only and can't be modified.  Can we have similar keyboard command in the VSCode terminal?

Thank you!

**Comment by IllusionMH** [comment]
VS Code already support commands for navigation and selection of next/previous terminal commands. You just need shortcuts you prefer to them.

For example add next lines to your `keybindings.json`
```json
    { "key": "ctrl+up",         "command": "workbench.action.terminal.scrollToPreviousCommand", "when": "terminalFocus" },
    { "key": "ctrl+down",       "command": "workbench.action.terminal.scrollToNextCommand", "when": "terminalFocus" },
    { "key": "ctrl+shift+up",   "command": "workbench.action.terminal.selectToPreviousCommand", "when": "terminalFocus" },
    { "key": "ctrl+shift+down", "command": "workbench.action.terminal.selectToNextCommand", "when": "terminalFocus" },
```

Does this solve your request?

**Comment by jagdishrajan** [comment]
These commands only scroll the output screen.  I then have to use the mouse to select and copy certain output.  What I'm looking for is to scroll up and down (by page and single line) with a cursor that can be moved to select and copy certain text.  Ctrl+F currently allows us to find and select text but we can't extend the selection with the Shift and arrow keys - this would also help in quickly locating and selecting text.

**Comment by IllusionMH** [comment]
Last two commands I mentioned select full output of command (checked in git bash and powershell) and you can copy it
```
    { "key": "ctrl+shift+up",   "command": "workbench.action.terminal.selectToPreviousCommand", "when": "terminalFocus" },
    { "key": "ctrl+shift+down", "command": "workbench.action.terminal.selectToNextCommand", "when": "terminalFocus" },
```

**Comment by jagdishrajan** [comment]
I honestly think these would work better as selectToPrevious/NextPage where a page size is given or predefined.  This would make it more predictable since  outputs from commands can be of varying lengths.

I often use PowerShell to list items (say blobs in Azure) where the list also generates other PS commands on that blob (say GetContents).  This really requires precise selection of a specific line - otherwise it's easier to just use the mouse and select.   In cases where I want to copy and paste output (to an email say)  broad selections simply means I have to further cut down the selection in the next editor.

Finally, you can get lost scrolling up and down between commands without a cursor to confirm your current location.  Once again PSISE's terminal pane does the job nicely.

**Comment by IllusionMH** [comment]
I think that free movement cursor was requested earlier, but I won't be able to find it on mobile.

Anyway, **Tyriar** is assigned to this issue and will weigh in (I guess after the holidays).

**Comment by Tyriar** [comment]
I guess this sort of thing could be bundled in with https://github.com/microsoft/vscode/issues/69795 to allow not just cell navigation but selection as well (holding shift). Merging into that
