### ISSUE TITLE
PHP embedded in JS highlighting incorrectly

### ISSUE THREAD

**Issue by ProtocolLive** [microsoft/vscode#87573]
Issue Type: <b>Bug</b>

The following line take a wrong color starting at lista"];?>
```
<input type="submit" value="Salvar" onclick="Ajax('lista.php?a=npok&lista=<?php echo $_GET["lista"];?>','AjaxWindow1Page','produto');return false;">
```
The file is PHP

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.49GB free)|
|Process Argv|C:\php\www|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipexplorer|sle|0.3.1

</details>

**Comment by alexr00** [comment]
Looks like embedded languages where tokens don't have a theme get the theme of the surrounding language...

**Comment by alexr00** [comment]
@aeschli is this bug yours?

**Comment by aeschli** [comment]
This is about PHP syntax highlighting

**Comment by roblourens** [comment]
We don't handle PHP embedded in JS well

**Comment by ProtocolLive** [comment]
I desagree with the new topic title.
The bug is that Code thinks the second quite closes the first, but have a php tag between them

**Comment by roblourens** [comment]
That's correct, but the reason for the issue is that this nesting of embedded languages is not handled correctly.

**Comment by ProtocolLive** [comment]
found another one...
`<a<?php if(isset($Options["item"])){?>`

**Comment by ProtocolLive** [comment]
The error persist
Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
Merging our PHP grammar issues into this issue https://github.com/microsoft/vscode/issues/162707
