### ISSUE TITLE
Python extension: Find All References/Go to Definition issue with __init__.py

### ISSUE THREAD

**Issue by meimchu** [microsoft/vscode#87576]
- VSCode Version: 1.41.1
- OS Version: macOS Catalina 10.15.2
- Python extension Version: 2019.11.50794

Steps to Reproduce:

1. Download python extension. (2019.11.50794)
2. Download the colour-science package from pip.
3. Open ``/plotting/diagrams.py`` from the python package in site-packages.
4. You will see at the very top are a few imports. An example would be
```python
from colour.utilities import (domain_range_scale, first_item, is_string,
                              normalise_maximum, tstack, suppress_warnings)
```
5. What that is doing is it's importing from the utilities module's ``__init__.py`` which if you follow, will see has the following import.
```python
from .common import (
    handle_numpy_errors, ignore_numpy_errors, raise_numpy_errors,
    print_numpy_errors, warn_numpy_errors, ignore_python_warnings, batch,
    disable_multiprocessing, multiprocessing_pool, is_networkx_installed,
    is_openimageio_installed, is_pandas_installed, is_iterable, is_string,
    is_numeric, is_integer, is_sibling, filter_kwargs, filter_mapping,
    first_item, get_domain_range_scale, set_domain_range_scale,
    domain_range_scale, to_domain_1, to_domain_10, to_domain_100,
    to_domain_degrees, to_domain_int, from_range_1, from_range_10,
    from_range_100, from_range_degrees, from_range_int)
```
6. If you follow the ``first_item`` import for example, you will see that it is ultimately declared in ``utilities/common.py``.
7. The problem is if you are back at ``plotting/diagrams.py`` and use **Go to Definition** on ``first_item``, it will not find the declaration of that function in ``utilities/common.py``.
8. Conversely, if you try to use **Find All References** on that ``first_item`` function in ``utilities/common.py``, it will also not find all usages of that function in ``plotting/diagrams.py``, for example.
9. My conclusion is that this is due to importing through ``__init__.py`` which caused the python extension to lose track. So I am sure one could also create a much more simplified way to reproduce this issue. I have tried both ``python.jediEnabled`` set to ``true`` or ``false`` by switching to Microsoft Python Language Server. Neither of which worked.
10. I am using ``first_item`` variable from ``plotting/diagram.py`` as an example. You will find similar issue with other kind of imports within that same file as well. It would be lovely to see the python extension improve its **Go to Definition** and **Find All References** linkage because that is essential for bigger size projects.

Thank you for taking a look into this.

Does this issue occur when all extensions are disabled?: No

**Comment by dbaeumer** [comment]
Please report the issue against the Python extension you are using very likely here: https://github.com/Microsoft/vscode-python
