### ISSUE TITLE
#87440 should be open for discussion

### ISSUE THREAD

**Issue by interferereviver** [microsoft/vscode#87571]
#87440 should be open for discussion because that issue says something about "want to be transparent" and "not censoring".

It is unclear how you decide if any "single person being offended" is a real offended person or just troll or smth else? Would you believe me if I say that I'm offended by letter V?

New acc for obvious reasons

Does this issue occur when all extensions are disabled?: Yes

**Comment by brlebtag** [comment]
![3k891b](https://user-images.githubusercontent.com/7052344/71329139-03ab3100-2500-11ea-8bce-6a18b89a779e.jpg)

It's just laughable...

They're as "transparent" and "not censoring" as North Korea.

**Comment by h0wXD** [comment]
The person who raised the issue #87268, @Christian-Schiffer (From the medieval Latin name Christianus meaning "a Christian"), deleted his github account. There's a high possibility of this being trolling that got out of hand.

**Comment by egamma** [comment]
Issue #87440 has been updated an unlocked, opened for discussion.
