### ISSUE TITLE
Use jsconfig.json in root floder, js code no tips

### ISSUE THREAD

**Issue by linlinyang** [microsoft/vscode#87582]
Issue Type: <b>Feature Request</b>

when i use  jsconfig.json in my project workspace, and then all my project file has no tips, especial js file. I just  write such config in  jsconfig.json:
```
{
    "compilerOptions": {
        "baseUrl": "./",
        "target": "es6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true,
        "paths": {
            "@/*": ["src/*"]
        }
    },
    "exclude": ["node_modules", "dist"],
    "include": ["src"]
}
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

**Comment by anyclub** [comment]
the same

**Comment by mjbvz** [comment]
How large is your project? Are there a lot of files under `src`?

**Comment by linlinyang** [comment]
@mjbvz About 7 floder ( 40 files ) in src.It just a new project or i try create 1 file in src and use this config, then all my project in workspace has not code hints.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by linlinyang** [comment]
I used vscode stable not insiders

**Comment by mjbvz** [comment]
Try insiders
