### ISSUE TITLE
taskbar not display project name

### ISSUE THREAD

**Issue by 5dao** [microsoft/vscode#87588]
Issue Type: <b>Feature Request</b>

taskbar and dockbar only display  "Code" ,how to config to show project or fordle name on taskbar icon title

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

**Comment by dbaeumer** [comment]
@5dao the project name is usually presented in the title bar. Can you please be more preceise what you expect to see?

**Comment by 5dao** [comment]
yes，mac dock hover tips

**Comment by gjsjohnmurray** [comment]
Perhaps a duplicate of #84195

**Comment by dbaeumer** [comment]
@5dao can you provide a screen shot showing what you are missing where.

**Comment by 5dao** [comment]
> @5dao can you provide a screen shot showing what you are missing where.

thinks.
 
![1577154289271](https://user-images.githubusercontent.com/5286750/71390261-96e88180-263a-11ea-83ab-de1e77ea248b.jpg)

**Comment by dbaeumer** [comment]
Thanks.

**Comment by bpasero** [comment]
@5dao 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by 5dao** [comment]
> @5dao
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Thanks,Thanks all vscode !developers , @dbaeumer @bpasero @gjsjohnmurray 



<img width="137" alt="截屏2019-12-27下午4 28 07" src="https://user-images.githubusercontent.com/5286750/71509467-5e5cd800-28c6-11ea-864b-424f4af68524.png">
