### ISSUE TITLE
Please change the 'insiders' build label as it instillates privilege of one group over another, suggests corruption and offends homeless people

### ISSUE THREAD

**Issue by higherkinded** [microsoft/vscode#87589]
Greetings, Microsoft! I'd like you to please change the "insiders" build label to something else. I'm not sure what fits the best since there are lots of triggers in the wild, though I'd consider something like "preview" neutral enough. In short, yes, this label just reeks of supremacy: "Oh, you aren't an insider, are you? Seems like you're an outsider then!", and that doesn't appear appropriate or even acceptable to me. It basically suggests some kind of privilege even if I'm not sure which specific one it is, not to mention that the "insider" circles usually involve some sort of corruption and bribery, though I hope that VSCode insiders, still being the glorious OSS people, don't do that. Lastly, it's a major insult for homeless people. Like, look, insiders are inside while the homeless people are outside. Does that mean that homeless people are outsiders, too? I don't know for sure, but it sounds pretty offensive.

And to make the matters worse, there's no binary build for `musl`, and that's probably the most insulting part of it.

*Specs:*

- VSCode Version: every single up to this date
- OS Version: Linux 5.3.8_2
- LibC: [musl](https://github.com/ifduyue/musl)

*Steps to Reproduce:*

1. Try to write a concise issue report to suggest the support for `musl-libc`;
2. Stumble upon a suggestion to use an insider build;
3. Go ballistic.

*Does this issue occur when all extensions are disabled?:* Extensions must be loved and cherished equally even if they're disabled.

**Comment by merkens** [comment]
As someone who's sometimes inside and sometimes outside I see the problem. A fix for the outside build could be something like a hat to keep warm. Maybe a red hat with a fluffy on it.

**Comment by alexandernst** [comment]
This must be fixed! @vscode_team top priority, please.

**Comment by higherkinded** [comment]
I would also like to inform you that the recurring recommendation of "using the latest insiders" will sound very rude. Sure, insiders may be corrupt and overly privileged but they still don't deserve to get abused as they are living and feeling beings.

**Comment by higherkinded** [comment]
The best part of it is that it's actually actionable for the `musl` part.
