### ISSUE TITLE
Lost driver letter when double click to copy path in vscode terminal on Windows after vscode version about 1.38

### ISSUE THREAD

**Issue by lqm678** [microsoft/vscode#87583]
Lost driver letter when double click and copy paths in `vscode` terminal on **Windows** after `vscode` version about `1.38`.

This bug makes it inconvenient to copy paths for use.

- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 **10.0.18363**

Steps to Reproduce: 
1. Run a simple command in vscode terminal: `echo %tmp%`
2. Double click the result/path (expanded `%tmp%`) to copy.
3. You'll see that the selected path and copy result will lost the driver letter (`C:` most likely)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
: is considered a word separator, you'll need to double click to the right of the C: and drag the mouse over the C to select the whole thing

**Comment by lqm678** [comment]
Thanks a lot for your reply! 
Why not make special processing for the **Windows** platform to give the users a better experience?
(it's an incomplete path if lost the driver letter).

**Comment by Tyriar** [comment]
Thinking about it again I think it was probably a mistake to remove ; and :

**Comment by lqm678** [comment]
@Tyriar Thanks a lot! Your support will help me to save a lot of times and make users happy to use vscode on Windows! 
Enjoy your Christmas days! 
-- Oh, you're such a dedicated developer! Thanks a lot and best wishes to your family members!
