### ISSUE TITLE
Pleast, remove skyblue colors everywhere, it's offensive to non-homosexuals

### ISSUE THREAD

**Issue by luntik2012** [microsoft/vscode#87586]
And pink too, it's color of lesbians

**Comment by dalisoft** [comment]
Be good, please don't troll. If you don't like these colors, change theme.

You using maintained Free and good editor, just support developers by file real issues and try solve others issue

**Comment by luntik2012** [comment]
Thanks, but I'll never use software from microsoft

**Comment by dalisoft** [comment]
Okay, if not using, why creating troll issue?
