### ISSUE TITLE
HTML tag creation not works properly

### ISSUE THREAD

**Issue by trendsttler** [microsoft/vscode#87585]
Issue Type: <b>Bug</b>

here i facing issue when i create a new tag then wirte a class in it, It just write that in closeing tag also i can't do this again and again to remove from bottom and start working on satrting tag.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
r|Iku|1.2.0
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|1.4.2

</details>

**Comment by gjsjohnmurray** [comment]
This new 1.41 feature is described in the release notes including information on how to turn it off. Several issues have been raised about it, and some are already resolved in the 1.42 Insiders build. Please search for 'mirror cursor' to see if any describe what you are seeing. If yes, close this as a duplicate. If not, give more information on how exactly to reproduce yours.

**Comment by octref** [comment]
@trendsttler This bug should be fixed. Please open a new issue with reproducible steps.
