### ISSUE TITLE
Cannot show references

### ISSUE THREAD

**Issue by tuannv1804** [microsoft/vscode#87587]
Dear team,
I was updated visual studio code to 1.41.1. Now, it don't show references my functions. It's so bad. I had checked setting and everything is so good. Please check my issue! 
Sorry for bad english
Thanks and best regards

**Comment by dbaeumer** [comment]
This is very likely a problem with the extension you are using. Which programming language are you using. Can you please add steps how to reproduce the problem, best is a GitHub repository to clone.
