### ISSUE TITLE
Extensions using form in webview cannot work in VSCode Online Web.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#87581]
- VSCode Version: Version: 1.41.0
- OS Version: Mac OS X 10_15_2

Steps to Reproduce:

1. Install `mtxr.sqltools`
2. Create a configuration and save, according to https://github.com/mtxr/vscode-sqltools/issues/469

Screenshots
![image](https://user-images.githubusercontent.com/7701575/71160696-03523200-2283-11ea-81a7-00a64218b17f.png)

Does this issue occur when all extensions are disabled?: Yes

I create a pull request for fix this: https://github.com/microsoft/vscode/pull/87334

**Comment by mjbvz** [comment]
Fixed by #87334
