### ISSUE TITLE
Ctrl + click on file does not behave intuitively

### ISSUE THREAD

**Issue by cydouzo** [microsoft/vscode#87598]
- VSCode Version: 1.41.0
- OS Version: Linux Mint 19.2

Steps to Reproduce:

1. On the VScode file explorer, I press Ctrl+LClick on several files to select them simultaneously.
2. Then I Ctrl+LClick on a couple of ones that I had previously selected (thus "un-selecting" them)
3. Finally I press Delete
What happens is that instead of deleting the currently selected files, it will only delete the last file that I had un-selected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/85437
