### ISSUE TITLE
Tune presentation of input/output in the debug console

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#87599]
Follow up work from last milestone to make the input / output more distinguishable.

**Comment by isidorn** [comment]
I have improved the alignment so it now looks like this.
As @joaomoreno points out the issue is that we use the same icon as for the tree expando which can resonate badly with the user.
We should use a different icon. However if I use a arrow right / left codicon I personally do not like the effect since due to an illusion they do not look centereted

Thus I think we should introduce a new icon. Something that looks like a chevron but is a bit different. So some stylised version of > <
@misolori is it possible to design something like this?

![Screenshot 2020-01-21 at 15 11 00](https://user-images.githubusercontent.com/1926584/72812528-f5b51100-3c61-11ea-83e7-8aaf39685891.png)

![Screenshot 2020-01-21 at 15 25 37](https://user-images.githubusercontent.com/1926584/72812738-5a706b80-3c62-11ea-999f-bea51ec1bdf0.png)

**Comment by joaomoreno** [comment]
I remember discussing this back in December. Alternatives are:

- Only use an icon for input
- Only use an icon for output
- Separate input/output pairs with a horizontal separator

Let's explore those as well.

**Comment by isidorn** [comment]
Good ideas.
Horizontal separator: the repl no longer would look like an editor and I personally dislike this.

Only use an icon for input:

![Screenshot 2020-01-21 at 15 36 44](https://user-images.githubusercontent.com/1926584/72813564-d8814200-3c63-11ea-876b-bad037f913b3.png)


Only use an icon for output:

![Screenshot 2020-01-21 at 15 37 40](https://user-images.githubusercontent.com/1926584/72813638-fb135b00-3c63-11ea-92e0-38a5d7ba0113.png)

I personally like how it looks when we only use an icon for input.
I would push this to insiders to get feedback.
Let me know what you think! And thanks a lot

**Comment by joaomoreno** [comment]
>  Horizontal separator: the repl no longer would look like an editor and I personally dislike this.

But the repl isn't an editor. The Chrome repl uses horizontal separators.

**Comment by isidorn** [comment]
Yeah, I am aware of both those things. IMHO it just feels like too much for me with all the horisontal lines. Chrome uses nice transparent color for lines and I could be convinced to also try that, but I would first like to try the one arrow approach.

Our users are always swtiching between the editor and repl, while the chrome does not have a regular editor. Since VSCode is an editor, and our users mostly look at the editor imho it makes sense to make the repl resemble the editor as much as it can.

**Comment by joaomoreno** [comment]
> Since VSCode is an editor, and our users mostly look at the editor imho it makes sense to make the repl resemble the editor as much as it can.

It's especially because our users constantly switch between both that it is important to differentiate between them such that they don't get annoyed when they try to edit the repl or run commands in the editor.

But, you're right, let's roll with the current approach since it already addresses some pain points. 👍
