### ISSUE TITLE
PATH not loading

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#87591]
- VSCode Version: 1.41.1
- OS Version: macOS Catalina 10.15.2
- Shell: Fish shell + Starship prompt

Steps to Reproduce:

1. Load VSCode from Launchpad or Code.app
2. Open Dev Tools
3. Execute `process.env.PATH` in console
4. I get `"/usr/bin:/bin:/usr/sbin:/sbin"` - wrong PATH

Steps to Workaround:

1. Run Terminal
2. Execute `code`
3. Open Dev Tools
4. Execute `process.env.PATH` in console
5. I get `"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"` - expected correct PATH

What i want:

Get expected result without workaround

Steps i tried:
1. Add `export PATH="/usr/local/bin:$PATH"` to `.profile`
2. Add `export PATH="/usr/local/bin:$PATH"` to `.bash_profile`
3. Add `export PATH="/usr/local/bin:$PATH"` to `.bashrc`
4. Add `export PATH="/usr/local/bin:$PATH"` to `.zshrc`
4. Add `export PATH="/usr/local/bin:$PATH"` to EVERYWHERE possible

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@joaomoreno think this is related to the way we source the environment on startup.

**Comment by weinand** [comment]
@dalisoft On macOS all apps started from Finder, Dock, or Launchpad do **not** read the users ".profile", ".bash_profile" etc. files. So they don't inherit the same environment as apps launched from a terminal.

This is standard OS behavior. See https://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications

VS Code tries to work around this issue by reading the users ".profile", ".bash_profile" etc. files before an external command is executed (or the integrated shell is launched). 

But VS Code does not read the users ".profile", ".bash_profile" etc. files before opening the Chrome Dev Tools.

As a consequence you will not see the expected value of PATH in the DevTools but you should see it in VS Code's integrated terminal.

**Comment by dalisoft** [comment]
Thanks for response and describe, specially i not looking for DevTools, just `PATH` in DevTool is VSCode env `PATH`. Because of this bug i can't start the debugger, with Terminal starting can do

**Comment by weinand** [comment]
What debugger are you starting from DevTools?

Since we do not consider "DevTools" an end-user visible part of VS Code, we saw no need to make DevTools read ".profile", ".bash_profile" etc. files on startup.

**Comment by dalisoft** [comment]
@weinand Your link helped me and works, i think would be nice to add this to docs.

If anyone looks for fix, Steps:
1. `bash` (especially for Fish shell)
2. `launchctl setenv PATH $PATH`
3. `killall Dock`
4. Enjoy coding with amazing VSCode :)

**Comment by dalisoft** [comment]
I mean VSCode built-in debugger, if in DevTools `PATH` not shows `/usr/local/bin` (Homebrew Node.js path), built-in Debuggers fails (like this `Cannot find runtime node`)
