### ISSUE TITLE
Git Graph does not show for local repo.

### ISSUE THREAD

**Issue by ArbitCode** [microsoft/vscode#87592]
I have created a folder.
open by code  folder name
as I want to integrate with GitHub, on the terminal ->
>>cd < folder Name>
>> git init
edited some file and added into the folder.
>> git add .
>> git commit -m "message"
>> git branch

while clicking on git-graph tab not showing git graph

![github error](https://user-images.githubusercontent.com/35590355/71348036-a6f85680-2591-11ea-87e0-2eecae96fcf4.png)

**Comment by dbaeumer** [comment]
This looks like a problem with the GitGraph extension. Please report the issue here: https://github.com/mhutchie/vscode-git-graph
