### ISSUE TITLE
command 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by SiterZzz** [microsoft/vscode#87594]
Issue Type: <b>Feature Request</b>

command 'vscode.previewHtml' not found

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

**Comment by aeschli** [comment]
This command is not part of VSCode. I guess you had an extension installed that provided it. Maybe the  extension has been uninstalled or disabled?
