### ISSUE TITLE
HTML - Starting and closing tag cursor

### ISSUE THREAD

**Issue by ashwyn222** [microsoft/vscode#87590]
Issue Type: <b>Bug</b>

When I try to add any attribute to an html tag then the closing tag also gets the cursor (i.e. two cursors are there, one for the starting tag and another for the closing tag). So what happens is that when that attribute is added to the starting tag then closing tag also gets the same attribute. However this is a not a way a html code should look like. This was not there earlier. I think this feature is added in the latest release. Overall, I like vscode a lot. But this feature (bug) is king of annoying. Please check.

Example snippet:

<div></div>

If trying to add a class name to above div.

then this happens.

<div class="pt10"></div class="pt10">

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_86553222|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.9.1
scratchpad|awe|0.1.0
nebula-theme|Chi|1.3.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.17.0
vscode-diff|fab|1.4.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vs-color-picker|lih|1.0.0
prettify-json|moh|0.0.3
python|ms-|2019.11.50794
azure-account|ms-|0.8.7
vsliveshare|ms-|1.0.1404
vscode-json-editor|nic|0.2.3
angular-console|nrw|10.0.0
vetur|oct|0.22.6
polacode|pnp|0.3.4
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
vscode-smoothtype|spi|1.2.0
ayu|tea|0.18.0
vscode-wakatime|Wak|2.2.1
quokka-vscode|Wal|1.0.267
better-align|wwm|1.1.6
material-theme|zhu|3.2.1

(17 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
This new 1.41 feature is described in the release notes including information on how to turn it off. Several issues have been raised about it, and some are already resolved in the 1.42 Insiders build. Please search for 'mirror cursor' to see if any describe what you are seeing. If yes, close this as a duplicate. If not, give more information on how exactly to reproduce yours.
