### ISSUE TITLE
Intellisense is extremely slow

### ISSUE THREAD

**Issue by AbdulAhad125** [microsoft/vscode#87595]
I am using latest VsCode user version 1.4.1 and i had a simple react project in it and i have only one extension installed in it .Intellisense almost stoped working when i use gitBash with it ...Please help me in solving  this problem...

**Comment by dalisoft** [comment]
@AbdulAhad125 if you can, please add info about OS/Env infos for faster response

**Comment by 0x0ffff** [comment]
if not like this link: https://github.com/microsoft/TypeScript/issues/35792#issuecomment-567076852

I delete `node_modules/@types` folder at workspace folders, and reopen vscode, Intellisense will working.

**Comment by AbdulAhad125** [comment]
@dalisoft  Windows 10 x64
VSCode: v1.41.1 user
Hard :180Gb ssd
Ram:8Gb
![Screenshot (11)](https://user-images.githubusercontent.com/58077182/71399882-f187da80-2646-11ea-8aba-6adf2d306632.png)
![Screenshot (12)](https://user-images.githubusercontent.com/58077182/71399884-f187da80-2646-11ea-8cda-8bce6db77100.png)

(url)

**Comment by AbdulAhad125** [comment]
@0x0ffff  its working thanks for help

**Comment by dalisoft** [comment]
@AbdulAhad125 from process explorer seems everything OK, for me cleaning cache did help. i think @0x0ffff solution worked

**Comment by mjbvz** [comment]
@AbdulAhad125 So this is no longer a problem?

/needsMoreInfo

**Comment by AbdulAhad125** [comment]
@mjbvz  yes the issue resolved by @0x0ffff  solution
