### ISSUE TITLE
Open files in different tab

### ISSUE THREAD

**Issue by vermaman** [microsoft/vscode#87597]
When we open files one after the other, it replaces the current class window/tab and opens new file in the same window/tab.

We want to open new files in different tab.

-Currently using ForceCode extension for Salesforce Development.

**Comment by IllusionMH** [comment]
If you open editors with a single click you trigger preview mode: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
You can disable it with `"workbench.editor.enablePreview": false`. 
Or use double click to open persistent tabs and use single click if you only want preview - view content and replace with next opened editor to avoid pile of tabs that you needed only for few seconds

**Comment by vermaman** [comment]
Thanks
