### ISSUE TITLE
Disable "snippets prevent quick suggestions" when user enters last section of snippet

### ISSUE THREAD

**Issue by decodejacques** [microsoft/vscode#87607]
The "Snippets prevent quick suggestions" was added because the tab key is used to switch to the next section of the snippet. I would like quick suggestions to be re enabled when the user enters the last section of the snippet.

Right now, I have to escape out of the snippet every time to re enable quick suggestions.

**Comment by jrieken** [comment]
It does - once we you reach the final placeholder/tabstop (e.g. `$0`) snippet mode ends and quick suggest is enabled against. Are you suggesting to use the second to last tabstop?

**Comment by decodejacques** [comment]
My mistake, I didn't know about $0. Thanks for responding so quickly!
