### ISSUE TITLE
Icon theme dropdown area gets extra space on selecting "null" item

### ISSUE THREAD

**Issue by ZuBB** [microsoft/vscode#87600]
I just noticed that I am having issue (also see attached gif) described in title

- VSCode Version: latest available of today
- OS Version: latest patch version of macos 10.14

Steps to Reproduce:

1. open settings
2. search for icon
3. find "Icon theme" dropdown
4. click on dropdown to expand it
5. do hover-over between null any neighbour item

Does this issue occur when all extensions are disabled?: Yes

----

![2019-12-23 12 50 53](https://user-images.githubusercontent.com/597016/71354282-1f581b00-2584-11ea-944e-f21796ac19a5.gif)

**Comment by IllusionMH** [comment]
/question

It's just a description of a particular option. For example
![image](https://user-images.githubusercontent.com/1312662/71356705-b4124700-258b-11ea-9693-d0e1341129f0.png)

in case of **Files: Auto Save** every option has a description, in case of **Workbench: Icon Theme
** only predefined value `null` has one.

In your theme it's a bit hard to notice separator between options and description of highlighted option.

---
Please let maintainers know if it was closed by mistake with more details and suggestions of actionable items.

**Comment by ZuBB** [comment]
hi @IllusionMH! thanks for you reply.

OK, I git what happens. I have two comments on that:
* why I do not see description on currently selected items when dropdown is expanded but nothing is hovered?
* After you wrote about separator I notice a black line there. I am wonder if we have some tool that allows to check used colors if they playing nice together. Because currently black separator inside of light black background is hardly noticeable.

Any thought on that?

**Comment by IllusionMH** [comment]
What I see (Insiders builds, Windows)

1) When you open drop down with options list (with mouse click or with keyboard) and before hovering over any options - currently selected option is highlighted by default and if it has a description it is shown too.
    So It works as expected (at least from my side). Do you have described behavior or your is different?

2) This one depends on UI theme and particularly `"dropdown.border"` value (controls outer border as well as separator between options and description). Theme author should specify contrast enough value so I think it will be reasonable request in theme repo.

3) `null` - no icons for files/folders will be shown in Explorer or editor tabs. This one has description for this case.
    I agree that `null` doesn't look like best option and other fields have `none`, but in this case actual value that's written in `settings.json` will be literal `null` instead of string `"none"` as in other dropdown.

/cc @roblourens for visibility and maybe some input on third item.

**Comment by ZuBB** [comment]
Hi @IllusionMH! 

1. Yes, I have that behaviour. I understand that any piece of UI may require some additional explanation/description. For me next two things looks weird
* why some items in dropdown need explanation and some does not. Is everything good with design (more common sense of this word here)?
* my experience its a rare case when size of expanded area (where items are listed) can change its size while I am doing hover-over through items in it. Do we know examples in other software where that pattern is also used?

2. I understand that simple solution is to make author of that theme aware of it. Although I my question what not about that. Theme inside is a json. we know names of two props that are participating in this case. we can get theirs values and do calculation (some kind of diff) to check if there is enough contrast?(my color skills are not so good) between them. this kind of check (or some of it deviation) can be applied to all group of colors that dealing together. in that way author of any extension can check that neighbour elements have visually different colors. 

3. Data in JSON is case, presentation is another. I know VSCode is for SW engineers. But they can range from kickass to absolutely newbie. and tool should be user-friendly to all of them. I think `(none)` or `[none]` should be used here.

As a summary I would leave next:
* we do not need explanation here (inside of drowdown area). If we really need it for this option, it should be somewhere outside of dropdown.
* `null` should be replaces with `([none)`

Also I have noticed that one more place where this setting can be changed and there UX (and content) differs..

![2019-12-24 18 55 41](https://user-images.githubusercontent.com/597016/71420659-097b5080-267f-11ea-88c8-889497df1abb.gif)

/ cc @roblourens
