### ISSUE TITLE
FileSearch output needs to be more intuitive

### ISSUE THREAD

**Issue by muthursyamburi** [microsoft/vscode#87603]
Issue Type: <b>Feature Request</b>

The file search output should list the files in directory wise, instead of files. Or atleast it should be configurable

As of now, if I search for a word in my project folder, it lists all the files and the search text it matched. However, what I am looking for is to see the list of files already sorted under their appropriate dirs or sub-dirs (ex: refer how Eclipse does it so neatly)

Also, I should be able to select and save the search results like in Textpad.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/20224
