### ISSUE TITLE
Emmet balanceOut doesn't work in TSX with generics

### ISSUE THREAD

**Issue by andreyvital** [microsoft/vscode#87608]
```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

Working fine:
![Kapture 2019-12-23 at 14 28 38](https://user-images.githubusercontent.com/967317/71369436-8deba780-2589-11ea-85fa-2f2e1cbe4eeb.gif)

Doesn't work:
![Kapture 2019-12-23 at 14 29 59](https://user-images.githubusercontent.com/967317/71369444-917f2e80-2589-11ea-9f5c-b00a23def8cb.gif)

Code:

```TSX
import { NextPage } from "next";

interface IIndexProps {
  timeStamp: number;
}

const Index: NextPage<IIndexProps> = () => (
  <div>
    <div>
      <div>
        <p>
          Balance out doesn't work
        </p>
      </div>

      <span>Lorem ipsum dolor sit amet.</span>
    </div>
  </div>
);
```

**Comment by octref** [comment]
Note that you can use Expand Selection command, which is supported by TypeScript language server. Emmet doesn't handle this yet.

**Comment by andreyvital** [comment]
Yes, but it doesn't select in between tags :(

**Comment by rzhao271** [comment]
Closing in favour of #99896
Another related issue is #77279
