### ISSUE TITLE
Can not execute multi tasks

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#87601]
![image](https://user-images.githubusercontent.com/27731323/71356690-f48ab880-25bd-11ea-992a-5498804cce48.png)
![image](https://user-images.githubusercontent.com/27731323/71356700-f94f6c80-25bd-11ea-86c8-d6fad545f200.png)
![image](https://user-images.githubusercontent.com/27731323/71356712-00767a80-25be-11ea-8ed8-176480a6f4fb.png)
![image](https://user-images.githubusercontent.com/27731323/71356734-09674c00-25be-11ea-8ee5-0dfa3b9bc6cb.png)

the task only do the first one "package"

**Comment by alexr00** [comment]
Checkout the documentation on hover: 
![image](https://user-images.githubusercontent.com/38270282/71817140-3bc87d00-3085-11ea-97db-f40a7f87329d.png)
