### ISSUE TITLE
Save Icon in vscode is very offensive to me

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/vscode#87602]
Please remove the Save Icon. 

I know a _friend_ that has an erectile dysfunction and if offended. #floppyDisk

Thanks

https://github.com/microsoft/vscode/issues/87327

**Comment by mikeblakeuk** [comment]
(Sorry, was joining the trolling band wagon. Feel bad now. 
Hope everyone has a festive, fun Christmas. Even those who are _hard up_ )

**Comment by mikeblakeuk** [comment]
https://www.bbc.co.uk/news/education-50760683

**Comment by knilecrack** [comment]
rofl
