### ISSUE TITLE
Visual Code crashes Window 10 with Blue Screen

### ISSUE THREAD

**Issue by tweekes** [microsoft/vscode#87616]
Issue Type: <b>Bug</b>

When Visual Studio Code is running it crashes Windows 10 and give a blue screen.
The problem is random but today when I launched VSC it crashed straight away.
The problem has occurred a number of times previous but is relatively recent - say in last 6 weeks. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:59:13.638Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3310)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (12.17GB free)|
|Process Argv|--folder-uri file:///d%3A/home/mydev/Javascripts/chordplay|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
vscode-todo-plus|fab|4.14.1
devServer|ihu|0.0.4
Angular2|joh|8.3.0
prettify-json|moh|0.0.3
python|ms-|2019.11.50794

</details>

**Comment by kieferrm** [comment]
@tweekes does the same happen when you have disabled all extensions? E.g. `code --disable-extensions`?

**Comment by tweekes** [comment]
I can try that but the problem is very random. I have just restarted VSC and its running fine again.
Is there directory / folders that I could inspect? 
@kieferrm Thanks!

**Comment by kieferrm** [comment]
Since this is a system crash, none of our logs will really help. I'm guessing the issue is caused by an extension that has components that are native code such as the Python extension. I don't know devServer or vscode-color but they also look like installing native dependencies.

**Comment by tweekes** [comment]
Python might be my prime suspect as it is the last one I installed and on reflection there might be a coincidence in the timing. Thanks for the help. I will close for now and monitor over the next month.
