### ISSUE TITLE
Javascript intellisense is not working

### ISSUE THREAD

**Issue by aashishchainyard** [microsoft/vscode#87617]
Issue Type: <b>Bug</b>

mkdir test-project
cd test-project
npm init -y
npm install express
touch app.js
code app.js
enter code 
const router = require('express').Router
router.

Expected: Intellisense shows the express router functions
Observed: Nothing is shown.  Tried Ctrl+Space 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2965)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.42GB (8.83GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-yaml|red|0.6.1
graphviz-interactive-preview|tin|0.0.4

</details>

**Comment by 0x0ffff** [comment]
delete `node_modules/@types` folder, and reopen vscode, it working

**Comment by aashishchainyard** [comment]
Did not work for me.

**Comment by aashishchainyard** [comment]
I deleted the settings.json and now it works

**Comment by XuZhaoTong** [comment]
> delete `node_modules/@types` folder, and reopen vscode, it working

It worked yesterday and it not work again today.

**Comment by 0x0ffff** [comment]
> > delete `node_modules/@types` folder, and reopen vscode, it working
> 
> It worked yesterday and it not work again today.

Oh sorry
I found that problem too, then I checkout `node_modules/@types` folder came back, so **delete it again!**

**Comment by XuZhaoTong** [comment]
> > > delete `node_modules/@types` folder, and reopen vscode, it working
> > 
> > 
> > It worked yesterday and it not work again today.
> 
> Oh sorry
> I found that problem too, then I checkout `node_modules/@types` folder came back, so **delete it again!**

It didn't come back，but I find node_modules/@typescript-eslint folder,should I delete it?

**Comment by 0x0ffff** [comment]
> > > > delete `node_modules/@types` folder, and reopen vscode, it working
> > > 
> > > 
> > > It worked yesterday and it not work again today.
> > 
> > 
> > Oh sorry
> > I found that problem too, then I checkout `node_modules/@types` folder came back, so **delete it again!**
> 
> It didn't come back，but I find node_modules/@typescript-eslint folder,should I delete it?

emmm, I thnik it relate to `typescript`, because if you open single js file, intellisense will work, but open workspace, intellisense it not working, so you can try, **delete it**

**Comment by XuZhaoTong** [comment]
> > > > > delete `node_modules/@types` folder, and reopen vscode, it working
> > > > 
> > > > 
> > > > It worked yesterday and it not work again today.
> > > 
> > > 
> > > Oh sorry
> > > I found that problem too, then I checkout `node_modules/@types` folder came back, so **delete it again!**
> > 
> > 
> > It didn't come back，but I find node_modules/@typescript-eslint folder,should I delete it?
> 
> emmm, I thnik it relate to `typescript`, because if you open single js file, intellisense will work, but open workspace, intellisense it not working, so you can try, **delete it**

I try to delete it and restart vscode,but it still not work😞

**Comment by 0x0ffff** [comment]
> > > > > > delete `node_modules/@types` folder, and reopen vscode, it working
> > > > > 
> > > > > 
> > > > > It worked yesterday and it not work again today.
> > > > 
> > > > 
> > > > Oh sorry
> > > > I found that problem too, then I checkout `node_modules/@types` folder came back, so **delete it again!**
> > > 
> > > 
> > > It didn't come back，but I find node_modules/@typescript-eslint folder,should I delete it?
> > 
> > 
> > emmm, I thnik it relate to `typescript`, because if you open single js file, intellisense will work, but open workspace, intellisense it not working, so you can try, **delete it**
> 
> I try to delete it and restart vscode,but it still not work😞

New Issues!
