### ISSUE TITLE
Why The Politics Microsoft?

### ISSUE THREAD

**Issue by scifi6546** [microsoft/vscode#87611]
Watching the Santa Saga unfold has got me questioning why the Open Source community has allowed politics to seep into a fairly technical world. I thought that having a Santa icon was fairly benign but the developers swayed to the beliefs of a single troll and ignored what pretty much everybody else wanted. The beliefs of the troll were very strange and does not match what anybody else feels. Therefore I find it quite strange that the request for the removal of Santa to be given any thought. That should have been treated the same way that any other troll is treated (by showing them the door, I suspect that the same will be done to me with this post btw). I think that the reason that the user was given any attention was that he said the word 'racist' which is sadly treated as something that has to be believed without any question.

The 'feature' that I am requesting is for the developers to have a backbone and stand up to lone trolls. It should not be that easy for the outrage culture to infect the Open Source community. Furthermore I request that the Santa hat be put back and the original issue to be deleted. Thanks for reading this issue.

**Comment by alexandernst** [comment]
Furthermore, Microsoft decided to hide behind their bot and close 6 or 7 other issues that arose from the "Santa Saga". I can't decide whether they are afraid of even more public backlash or they realised they got trolled and now they can't keep up with their own statement of honouring every single ofended person.

**Comment by shogerr** [comment]
The open source community itself could not withstand the onslaught of varying social values into computing space without flinching wildly. I don't think a corporation will be do anything but add weight to the existing political contentions: there are far too many interests for a corp to manage that extend beyond the technology and project itself.

Microsoft calling the shots via Github for the larger open source community is a terrifying reality, to be honest.

**Comment by soulshined** [comment]
to be fair and objective, it feels like the community brought politics into this. I didn't even know what was going on until I submitted an actual bug report yesterday only to be slammed with comments about unrelated things, unprovoked by me or Microsoft. Github isn't a forum like Reddit, but it's being treated as such. Microsoft already established what they learned from it and posted remarks here, it feels like from my perspective, someone who didn't know what was going on until yesterday, it appears its provoked by the community. Although, based on your OP I think you agree to some extent, your title is slightly misleading

**Comment by kieferrm** [comment]
@scifi6546 Thanks for sharing. We wanted to try to address the concerns/feature-request you raised by providing more information on what happened last week. This turned out to address questions raised across other issues, so we put the response in https://github.com/microsoft/vscode/issues/87440#issue-540437717. 

Please take a look there, we hope this answers your concerns. If it does, please close this issue.

**Comment by RUSshy** [comment]
it is not politic, it is sanity, keep your religion at home, don't enforce it in our society

ban all religions.

tech should be ahead of the retarded religious people, time to clean this retarded world

**Comment by scifi6546** [comment]
thanks for responding to my comment. I'd still argue that the entry in the COC "That “even a single person being offended is one too many” means any concern must be answered with a code change" as the concern was not very valid or reflective of reality
