### ISSUE TITLE
The cursor jumps to the left after replacing double quotes with backticks in a Javascript file (over the screen width)

### ISSUE THREAD

**Issue by ndsvw** [microsoft/vscode#87614]
**Information**
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
This bug does still exist in the latest insider build.
I was not able to reproduce it on Windows.
This bug stays after running VSCode with disabled extensions.

**Steps to Reproduce:**
1. Create a new file somewhere, name it bug.js and save it.
2. file content: a string in double quotes (`".."`) that is longer than the screen width
```
test("longstring.............................................................................................................................................................................");
```
It could look like this:
<img width="1613" alt="Bildschirmfoto 2019-12-23 um 22 27 39" src="https://user-images.githubusercontent.com/21332313/71381400-b26c7180-25d3-11ea-9fbe-f5cd11875130.png">

3. replacing the first double quotes (") with a backtick (`).
4. scroll to the right to the second double quotes and click on them.

**Effect:**
The cursor jumps to the left. I clicked the second double quotes but the cursor is left from it.

After step 3:
<img width="1613" alt="Bildschirmfoto 2019-12-23 um 22 27 56" src="https://user-images.githubusercontent.com/21332313/71381423-ce701300-25d3-11ea-9d58-713c38064f72.png">

After step 4 (remember: I clicked on the 2nd double quotes):
<img width="1613" alt="Bildschirmfoto 2019-12-23 um 22 28 03" src="https://user-images.githubusercontent.com/21332313/71381456-e9428780-25d3-11ea-9929-d6b1af581d74.png">

Still after step 4 after scrolling as far as possible to the right:
<img width="1613" alt="Bildschirmfoto 2019-12-23 um 22 28 59" src="https://user-images.githubusercontent.com/21332313/71381533-2444bb00-25d4-11ea-8abb-e60f8ce46983.png">

**Comment by alexdima** [comment]
@ndsvw I could not reproduce. Does this reproduce only with a certain keyboard layout? I have tried with a US keyboard layout:

![Kapture 2020-01-21 at 11 42 15](https://user-images.githubusercontent.com/5047891/72798319-1cb01a80-3c43-11ea-9192-f36998685d6e.gif)

**Comment by ndsvw** [comment]
Interesting: It's not reproducible when using the scroll bars..
I scroll to the right with the MacOS trackpad (swiping to the left with 2 fingers).

Using the scroll bar method works fine (exactly what happens in your gif), but using the swipe method to scroll to the right results in this:
![mc](https://user-images.githubusercontent.com/21332313/72870909-b9c58e80-3ce9-11ea-8cc8-d8d5bfb97e1b.gif)

**Comment by alexdima** [comment]
@ndsvw  I could reproduce, but only when using US Intl where `` ` `` enters the accent composition mode.

So what is happening is that an accent composition is starting, it is not confirmed (usually this should be confirmed by pressing space or by pressing it again), then the very first click ends in the input composition being revealed again, and then immediately gets confirmed...
