### ISSUE TITLE
VS Code Freeze

### ISSUE THREAD

**Issue by Blockost** [microsoft/vscode#87612]
Issue Type: <b>Performance Issue</b>

Hi, 

VS Code is freezing at random moments... well, not so random, it seems it happens when I have compilation errors (code underlined with red). 

It happens more and more often recently. At first, I thought it was Angular compilation/hot reloading that made my laptop freeze but even when I don't use Angular CLI at all (no `ng serve`) it still freezing.

Can you look into it? Thanks for this amazing editor by the way. Never had any problems  until a week ago...

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|25, 38, 20|
|Memory (System)|7.70GB (4.91GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    79	  2721	code main
    0	     0	  2724	   zygote
    0	    47	  2752	   gpu-process
    0	    32	  2763	   window (equipmentTypeService.ts (Working Tree) - gim-ws - Visual Studio Code)
    0	     8	  3195	     extensionHost
    0	     0	  3492	       electron_node tsserver.js 
    0	     8	  3493	       electron_node tsserver.js 
    0	     0	  3526	         electron_node typingsInstaller.js typesMap.js 
    0	     0	  3511	       electron_node tslintServer.js 
    0	     0	  3823	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3195
    0	     0	  3196	     /usr/bin/zsh
    0	     0	  3455	     watcherService
    0	     0	 15762	     /usr/bin/zsh
    0	    63	  3469	   shared-process
    0	     0	 10629	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 10630	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   323	  9998	   window (● table-factory.service.ts - gim-ui - Visual Studio Code)
    0	   173	 10019	     extensionHost
    0	    79	 10314	       electron_node tsserver.js 
    0	   236	 10315	       electron_node tsserver.js 
    0	    71	 10356	         electron_node typingsInstaller.js typesMap.js 
    0	    87	 10332	       /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=10019
    0	   102	 10333	       electron_node tslintServer.js 
    0	    55	 10448	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=10019
    0	     0	 10020	     /usr/bin/zsh
    0	   102	 10193	     watcherService
    0	    63	 10424	     searchService
    1	   102	 10606	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● table-factory.service.ts - gim-ui - Visual Studio Code)
|  Window (equipmentTypeService.ts (Working Tree) - gim-ws - Visual Studio Code)
|    Folder (gim-ws): 169 files
|      File types: js(64) ts(64) json(6) log(3) gitignore(1) prettierrc(1)
|                  md(1) jpg(1) gitkeep(1) env(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|    Folder (gim-ui): 3458 files
|      File types: svg(2708) scss(259) ts(116) js(37) jpg(34) html(30) png(22)
|                  css(19) eot(10) ttf(10)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
gitlens|eam|10.2.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.18.0
Angular2|joh|8.3.0
dotenv|mik|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.8.1
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
peep|nwa|0.0.5
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
code-settings-sync|Sha|3.4.3
gitflow|vec|1.2.1
vscode-icons|vsc|9.6.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by Blockost** [comment]
Hi @mjbvz,

So it seems that the freeze was related to the TSLint plug-in I used. I disabled it and so far so good.

Thanks!

**Comment by calidion** [comment]
@Blockost 

Thanks.  

Confirmed TSLint plug-in problem.
