### ISSUE TITLE
Please revert latest change regarding tree folders on VS CODE 

### ISSUE THREAD

**Issue by BruneXX** [microsoft/vscode#87619]
Since latest version 1.41.1 I've noticed that there was a change regarding tree folders making this:

```
myParentFolder / firstChildFolder
  - file1
  - file2
  - fileN
```

The annoying thing with this is that creating a new child folder is not created at firstChild level, instead of that is created inside the firstChildFolder..

**Comment by KamranMackey** [comment]
You can just click the folder where you want to create a file in. The tree structure changed was made to reduce folder clutter more than likely in the file view.

**Comment by soulshined** [comment]
I would argue against reverting. For me, I work heavily with Java and it's finally easier to navigate the tree as a 99% mouse-free user. I barely use my mouse, except for peeks, but I was surprised how well it works mouse-free to select the folder you want. 

At minimum, I feel this is a great candidate for a user/workspace setting to accommodate all the different coding preferences.

**Comment by BruneXX** [comment]
Ok, I see, Maybe this is a Linux thing, so for me, after that change, I had to move the new created folder outside because after creation of the first one, the others were created inside of it. For me was annoying, but maybe it’s because I’m using mouse to create  the new folders ínstead of shortcuts?

**Comment by BruneXX** [comment]
Also, I’ve only seen this behaviour with the first folder, then (if you add more) the tree view comes back to normal.

**Comment by soulshined** [comment]
@BruneXX so when you hover over the top level item, there isn't an underline decorator indicating you would be adding to that folder?

Say for example I am hovering on the 'vars' subfolder shown below:
![ss1](https://user-images.githubusercontent.com/11242654/71390430-f5bfe380-25c5-11ea-954f-9f654153336c.png)

If I were to hover the 'pragmas' folder it would become underlined. Using keyboard  is no different, should work the same, just with arrow keys

**Comment by BruneXX** [comment]
Hi @soulshined yes, it is. But I don’t know why, when I’ve created the new child folder clicking on the parent (pragmas in this case) the folder was created insiste of vars (first child) instead of pragmas.

**Comment by soulshined** [comment]
ah ok. It very well may be a linux thing 😕 just tested on my mac and windows, both behave appropriately. Sorry about that. If anything, maybe others want a user setting for it as well.

**Comment by BruneXX** [comment]
Maybe it's just a matter of habit. I will double check tomorrow. Thanks for the replys 😃👍🏻

**Comment by misolori** [comment]
@BruneXX you can disable this by setting `explorer.compactFolders` to `false` in your [user settings](https://code.visualstudio.com/docs/getstarted/settings).

**Comment by weinand** [comment]
Since there is a way to turn this off, there is nothing we need to do on our side.
