### ISSUE TITLE
Generic type in interface breaks TSX syntax highlighting

### ISSUE THREAD

**Issue by tomduncalf** [Microsoft/vscode#8761]
- VSCode Version: 1.3.0-insider a1293f5056e79c3f0e2cd3e24909f41ff4eef472 (does not affect 1.2.1)
- OS Version: OS X 10.11.3

Steps to Reproduce:

1. Create an interface which has a property of a type which uses a generic in its signature
2. Subsequent code is incorrectly highlighted, presumably due to angle brackets being interpreted as JSX

Example code:

```
interface Test<T> {
    test: T;
}

interface Props {
    prop: Test<T>;
}

class Whatever {
}
```

Actual result:

![image](https://cloud.githubusercontent.com/assets/5458070/16587544/0a56eea4-42c3-11e6-8feb-43f804f2e441.png)

Expected result: `class` should be highlighted properly e.g.

![image](https://cloud.githubusercontent.com/assets/5458070/16587548/1938bede-42c3-11e6-86b3-790dd7cef8c1.png)

**Comment by lediur** [comment]
I can reproduce this too. Other Intellisense features (e.g. type inference, info on hover) works, so it seems like just a syntax highlighting bug.

Version: 1.3.0-insider a1293f5
OS: Windows 10 Pro Insider 14379

Here's a gif:

![syntax-highlighting-typescript-generics](https://cloud.githubusercontent.com/assets/1077648/16600793/cf0ce416-42bd-11e6-8d9f-1efdf62ef3bb.gif)

**Comment by PascalSenn** [comment]
**Workaround:** If you put a whitespace between the generic and the angle brackets the syntax should highlight correctly

**Comment by tomduncalf** [comment]
Ah thanks @PascalSenn, looks a bit ugly but better than no syntax highlighting!

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#202

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/8045
