### ISSUE TITLE
[Feature request] How to change "Peek" submenu to main menu

### ISSUE THREAD

**Issue by vinxue** [microsoft/vscode#87628]
- OS and Version: Win10 1909
- VS Code Version: 1.41.0
-  C/C++ Extension Version: 0.26.2

Since Code 1.41.0 release, “Peek” menu moved to a submenu.
I am wonder if there is method change it back to main menu? Because it's very not convenience for coding. Most of time, we just do "Peek..." rather than "Go to...".
Or is there a way to configure the UI?
I searched by google but I didn't find a solution. Please help.
![image](https://user-images.githubusercontent.com/48240436/71397848-ab884200-2659-11ea-8b93-95acf4bbbb22.png)

**Comment by LAK132** [comment]
Which issue is this a duplicate of?

**Comment by scottshambaugh** [comment]
@jrieken is this the duplicate issue you are referring to? #9285

Also throwing in my vote that this was an unwelcome change, since I use peek far more than go to and there aren't shortcuts for all those actions.
