### ISSUE TITLE
Selected lines count are wrong

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#87626]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/13949704/71395149-c345d300-2625-11ea-914c-ba751216de72.png)

i earlier had [peterfh.linesinfostatusbar](https://marketplace.visualstudio.com/items?itemName=peterfh.linesinfostatusbar) extension enabled, but not now .

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
adiZcont|ili|0.8.0
l2mdtable|aki|0.1.0
Bookmarks|ale|10.6.0
read-only-indicator|ale|3.0.3
code-gnu-global|aus|0.2.2
spellright|ban|3.0.48
vscode-custom-css|be5|3.0.9
autofoldyeah|bob|1.0.6
language-status|Eya|1.0.3
shortcuts|giz|0.0.1
toss-file|gre|1.0.5
activitusbar|Gru|0.0.21
align-mode|Gru|0.0.18
tablegenerator|Jay|1.0.4
favorites|kdc|2.4.5
vs-color-picker|lih|1.0.0
select-highlight-minimap|mde|0.0.8
vscode-language-pack-ru|MS-|1.39.3
mssql|ms-|1.8.0
python|ms-|2019.11.50794
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
vsliveshare|ms-|1.0.1404
vsliveshare-audio|ms-|0.1.80
color-manager|roy|0.5.4
partial-diff|ryu|1.4.0
html-preview-vscode|tht|0.2.5
zoombar-vscode|wra|1.2.1
markdown-all-in-one|yzh|2.6.1
cursorCharCode|zei|0.1.1
file-size|zh9|0.1.3

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
"40" is the number of selected characters, not lines.

**Comment by irvnriir** [comment]
@weinand , thanks

It would be good to add a 2nd number for lines .

**Comment by weinand** [comment]
Please file a feature request.

**Comment by irvnriir** [comment]
https://github.com/microsoft/vscode/pull/87311
