### ISSUE TITLE
Unable to select the debug environment

### ISSUE THREAD

**Issue by tonynaveen** [microsoft/vscode#87627]
Issue Type: <b>Bug</b>

Cannot add Configurations to launch.json file

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.6.1
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
python|tht|0.2.3
unity-debug|Uni|2.7.2
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.23.0

</details>

**Comment by weinand** [comment]
Please provide steps for how to reproduce this.
