### ISSUE TITLE
开启多个工程,每个工程的编辑器颜色不同

### ISSUE THREAD

**Issue by xiongyechang** [microsoft/vscode#87621]
Issue Type: <b>Feature Request</b>

每次用vscode打开多个工程时,对应的每个编辑器的背景色都是一样的,希望能在开启多个工程时,每个工程的背景色都能不同,便于区分

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by AliasT** [comment]
use workbench.colorCustomizations
