### ISSUE TITLE
"references-view.prev" and "references-view.next" commands don't exist any more

### ISSUE THREAD

**Issue by fiddleyuan** [microsoft/vscode#87625]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.17763

I do reference search very frequently, so I keybind these two commands.
But recently, I found these two commands are not supported.
And Problem panel also hints me that "Value is not supported..." (but it used to work)

If I changed these two commands to "goToNextReference" and "goToPreviousReference", it didn't work in the same way. It will change focus in references-view, but it won't auto select the content so I can traverse through all the reference search result. Now all I can do is call "goToNextReference" first, then press enter.

Please, if possible, bring these two commands back.

**Comment by jrieken** [comment]
They [still exist](https://github.com/microsoft/vscode-references-view/blob/9761d06af9e78c1e80bb90b03eead850f558ab1e/package.json#L317. ) but I also see that they have stopped working...

**Comment by fiddleyuan** [comment]
> They [still exist](https://github.com/microsoft/vscode-references-view/blob/9761d06af9e78c1e80bb90b03eead850f558ab1e/package.json#L317.) but I also see that they have stopped working...

Thanks, Johannes, looking forward to the fix.
