### ISSUE TITLE
prompt for confirmation before closing app

### ISSUE THREAD

**Issue by zachvalenta** [microsoft/vscode#87620]
Looking for something like how Chrome 79 (on macOS, anyhow) flashes a message 'hold cmd Q to quit' in response to any single `cmd q` sequence i.e. "not sure you really wanted to quit, please confirm". Especially since `cmd q` is proximate to `cmd w` for closing tabs.

**Comment by nikoladev** [comment]
For those from the future looking for the original issue that makes this one a duplicate: https://github.com/microsoft/vscode/issues/14710
