### ISSUE TITLE
Git Fetch / Rebase

### ISSUE THREAD

**Issue by SK83RJOSH** [Microsoft/vscode#8763]
- VSCode Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Select Git tab
2. Open pulldown
3. Notice the lack of Fetch / Rebase

Alternatively being able to configure Pull to execute `git pull --rebase ` would be quite nice and reduce the need for fetch and rebase.

This is also a feature request but I'm not aware if there's a template, so excuse the format 👍

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/16615591/0f38b83e-4378-11e6-9774-255565faba92.png)

`Pull (Rebase)` exists already. No need to call fetch, since it is automatically done for you.
