### ISSUE TITLE
PrimeNG error: ',' expected.

### ISSUE THREAD

**Issue by lymimt** [microsoft/vscode#87631]
- VSCode Version: 1.41.1 or 1.42.0-insider
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create an Angular project and install PrimeNG
2. add `<p-toggleButton>` in component
3. set value of property `onLabel` and `onIcon`

or download code from: https://stackblitz.com/edit/angular-izgb41?file=app%2Fapp.component.html

```html
<p-toggleButton [(ngModel)]="checked" onLabel="I confirm" offLabel="I reject" onIcon="fa fa-check" offIcon="fa fa-times"
	[style]="{'width':'150px'}"></p-toggleButton>
```

problems:

![image](https://user-images.githubusercontent.com/37477603/71403344-63255000-266a-11ea-9892-ac63b600b418.png)

![image](https://user-images.githubusercontent.com/37477603/71403226-0de93e80-266a-11ea-955e-99f1f5cb705a.png)

the code works fine, but the error is annoying, is there any way to fix that?

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
The built-in html language server thinks that `onLabel` and `onIcon` are script attributes.

**Comment by octref** [comment]
You can turn it off by `"html.validate.scripts": false`.

HTML attribute is, by its standard, case insensitive. `onLabel` should contain JavaScript code just as `onlabel`.
