### ISSUE TITLE
Goto line doesn't work properly in Mac OS X.

### ISSUE THREAD

**Issue by LZong-tw** [microsoft/vscode#87632]
- VSCode Version: 1.41.1
- OS Version: Mac OS X 10.15.1

Steps to Reproduce:

1. Open any file
2. Press ^ + G
3. Enter an arbitrary number that doesn't exceed the total lines of the file

(Screenshot: https://drive.google.com/open?id=1XMBvR1fUYGMph4VY_haJ-jAxFEKxPN09 )

Does this issue occur when all extensions are disabled?: No
(Actually, the bug seems not to appear every time even when the extensions are enabled.)

**Comment by weinand** [comment]
I cannot watch/download the screencast. Please add it as a comment.

**Comment by LZong-tw** [comment]
Since it's a video file, I uploaded it to Youtube as a replacement: [https://youtu.be/HgoXW7-HyHk](https://youtu.be/HgoXW7-HyHk)

**Comment by weinand** [comment]
(you can just drag-and-drop video files into github. There is no need to upload them to anywhere)

But I still don't understand the problem.
Could you please describe what you are seeing and what you are expecting.

**Comment by LZong-tw** [comment]
(Since the format is .mov, it is not supported by Github for direct uploading, so I uploaded it to Youtube.)

I pressed ^ + G at 0:08, entered a line number as I wanted to go to(I wanted to go to line 520, at 0:10 ~ 0:11). Normally, the editor should start jumping to the line that I'd already typed in during the typing period(in this situation, it should jump to the line 5 at first, then the line 52) and finally go to line 520 when the typing is done. However, it didn't act at all, even I typed all the 5, 2 and 0, it just did nothing at all(0:11 ~ 0:15). When there was another coding character entered (、, a Mandarin comma) and deleted, the behavior I expected above was back again(0:15 ~ 0:22).

**Comment by kieferrm** [comment]
This works for me as expected on an English locale. My suspicion is that this is related to the CJK input method.

**Comment by LZong-tw** [comment]
> This works for me as expected on an English locale. My suspicion is that this is related to the CJK input method.

Oh, it really could be reproduced when I was using CJK input method. And I found the point is that when pressing ^ + G by using CJK input method, it would add a white space after the colon, this caused the function didn't work as it would be, whereas by using English input method, entered another coding character then deleted it or just manually deleted the white space could let the function works properly.

The two screenshots show the difference when using CJK input method and others.
![image](https://user-images.githubusercontent.com/5158408/71520183-c4ad1f00-28f5-11ea-8c7a-a890dd05d7f1.png)
![image](https://user-images.githubusercontent.com/5158408/71520226-e60e0b00-28f5-11ea-92f2-b16725f93519.png)

**Comment by rebornix** [comment]
@LZong-tw can you share what's the CJK input method you are using? I didn't reproduce this issue with macOS Pinyin.

**Comment by LZong-tw** [comment]
@rebornix I use Cangjie.

**Comment by LZong-tw** [comment]
This problem is solved with Zhuyin on Mac OS X 10.15.5 and VSCode 1.45.1. But with Cangjie, the problem becomes another way. When I press Ctrl + G with Cangjie, the input method shows a candidate window with one character that looks like space for me to choose for the "input", which is a candidate for typing "Ctrl + G" in Cangjie. I inspected the Unicode of the space-like character and it turned out to be U+0007. So...should I consider it an OS-wide problem?

This picture shows the candidate window I mentioned, and this is the space-like character in the window: "".
![image](https://user-images.githubusercontent.com/5158408/83153197-43221d00-a131-11ea-8614-e89d7c9b50fe.png)

**Comment by rebornix** [comment]
From the info above, it's more or less an issue of the native IME on the system.
