### ISSUE TITLE
Task service api feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#87638]
Here's some feedback for things which I do not find friendly to use looking at the API:

* Looking at the `taskService` API I could not find calls to `cancel` task runs. 
* `runTask` does not take a `taskId` to run. Due to that I have to do the whole `getTask` dance [here](https://github.com/Microsoft/vscode/blob/7531960f4e420e4e0ded48996b6ee5633b1e1266/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L116)
* `runTask` does not always finish which leads us to do the whole dance [here](https://github.com/Microsoft/vscode/blob/7531960f4e420e4e0ded48996b6ee5633b1e1266/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L140)

Due to the API being a bid cumbersome to use we had to introduce the DebugTaskRunner as a sort of wrapper. I wonder if this code should be moved to the task land that other potential clients do not have to do this.
It is of course fine leaving this code in the `DebugTaskRunner` if this is something debug specific - which I do not feel like it is.

**Comment by alexr00** [comment]
I think that debug is the only one using ITaskService besides tasks :D If there were any other uses then I'm sure this would be useful.

**Comment by alexr00** [comment]
Since debug is the only user, I will close as out of scope. However, if we gain another user then we should reconsider adopting.
