### ISSUE TITLE
open folder not work

### ISSUE THREAD

**Issue by xinyi1989** [microsoft/vscode#87630]
Issue Type: <b>Bug</b>

open folder button not work

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 6|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.22.6

</details>

**Comment by kieferrm** [comment]
@xinyi1989  can you please provide more information? Best would be recording that shows the behavior. Thank you!

**Comment by xinyi1989** [comment]
I return the version to 1.40, And it worked.
When the version is 1.41, It cannot open the project folder. The button [open folder] click not work.

**Comment by kieferrm** [comment]
If I understand your scenario correctly, it works for me as expected: 

![kWUsLnZfMq](https://user-images.githubusercontent.com/4674940/71492341-5845f900-27eb-11ea-969a-55b85d3ec416.gif)

Does <kbd>Cmd+o</kbd>, i.e. `Open Folder` work for you?

**Comment by xTibor** [comment]
Same issue here on Linux (KDE neon 5.17). These are the logs it spits out for me on the console:

<details><summary>Logs</summary>
<p>


```
bootstrap-window.js:213 [uncaught exception]: Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/usr/share/code/resources/app/node_modules.asar/graceful-fs/polyfills.js:11:19)
    at Q.resolveSingleFolderWorkspaceInitializationPayload (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6325:710)
    at Q.resolveWorkspaceInitializationPayload (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6325:68)
    at Q.initServices (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6324:392)
    at Q.open (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6322:20)
    at Object.t.main (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6327:444)
    at file:///usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.js:8:763
onUnexpectedError @ bootstrap-window.js:213
(anonymous) @ bootstrap-window.js:54
emit @ events.js:200
window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:151
error (async)
(anonymous) @ /usr/share/code/resources/electron.asar/renderer/init.js:146
Module._compile @ internal/modules/cjs/loader.js:786
Module._extensions..js @ internal/modules/cjs/loader.js:798
Module.load @ internal/modules/cjs/loader.js:645
Module._load @ internal/modules/cjs/loader.js:560
Module.runMain @ internal/modules/cjs/loader.js:850
(anonymous) @ internal/main/run_main_module.js:17
bootstrap-window.js:216 Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42)
    at process.cwd (/usr/share/code/resources/app/node_modules.asar/graceful-fs/polyfills.js:11)
    at Q.resolveSingleFolderWorkspaceInitializationPayload (desktop.main.ts:308)
    at Q.resolveWorkspaceInitializationPayload (desktop.main.ts:260)
    at Q.initServices (desktop.main.ts:224)
    at Q.open (desktop.main.ts:116)
    at Object.t.main (desktop.main.ts:380)
    at workbench.js:33
    at errors.ts:26
onUnexpectedError @ bootstrap-window.js:216
(anonymous) @ bootstrap-window.js:54
emit @ events.js:200
window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:151
error (async)
(anonymous) @ /usr/share/code/resources/electron.asar/renderer/init.js:146
Module._compile @ internal/modules/cjs/loader.js:786
Module._extensions..js @ internal/modules/cjs/loader.js:798
Module.load @ internal/modules/cjs/loader.js:645
Module._load @ internal/modules/cjs/loader.js:560
Module.runMain @ internal/modules/cjs/loader.js:850
(anonymous) @ internal/main/run_main_module.js:17
```

</p>
</details>

**Comment by plivesey** [comment]
I had the same problem. Maybe this happens when you've previously opened a folder and then you delete that folder from disk? Just guessing from @xTibor's comment and this was something that happened to me (I actually renamed one of the folders).

Uninstalling and reinstalling fixed it for me.

**Comment by isidorn** [comment]
Should be fixed now. If you can still reproduce with vscode insiders let me know and we can reopen
