### ISSUE TITLE
Intellisense is not working

### ISSUE THREAD

**Issue by emakina-efeuruk** [microsoft/vscode#87635]
Issue Type: <b>Bug</b>

Hi, code editor does not recommend me any function or variable names. Also, it doesn't let me to ctrl+click on paths to see files inside of these paths.

Kind regards

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.5.0
vscode-html-css|ecm|0.2.3
auto-rename-tag|for|0.1.1
debugger-for-chrome|msj|4.12.3
prettierthis|nir|0.0.6
material-icon-theme|PKi|3.9.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by anyclub** [comment]
the same

**Comment by kieferrm** [comment]
@emakina-efeuruk what programming language are you using? Please provide us with a small example that shows the problem for you. Thank you.

**Comment by emakina-efeuruk** [comment]
I am using jsx @kieferrm 

Here is the gif
![ezgif-6-24d1078c0320](https://user-images.githubusercontent.com/59011907/71440994-83a7e580-2710-11ea-912b-efcad1eb7c67.gif)

**Comment by sonivipul89** [comment]
same here

**Comment by klmurty2019** [comment]
I am using : Visual Source Code Version :  1.41.1
IntelliSense is not working.
I search som many blogs and tried to fix it but no use.
I am working with ReactJs snippets, Please help me to fix this.

For me it should be like this 👍 
When i open the file and try import, it is working. This is reproducible when when i come to second line of code.

**Comment by Cellv2** [comment]
Are you on Windows? If yes, is your project on a different drive to the one you installed VS Code on? If yes, try one of the three:
1) Move your project to the same drive and try again
2) Install the 'JavaScript and TypeScript Nightly' extension and use typescript@next
3) For your project, run ```npm i -D typescript@3.6.*``` then opening VS Code, bringing up the command palette (F1) > select typescript version and using workspace version

**Comment by sonivipul89** [comment]
i followed all steps but i can't resolve problem
its still loading.....

**Comment by klmurty2019** [comment]
Me also same. If I try previous version, it works well (VS code : )

**Comment by mjbvz** [comment]
@emakina-efeuruk What driver letter is your code stored on?
