### ISSUE TITLE
Typescript definition files sometimes not picked correctly

### ISSUE THREAD

**Issue by csvn** [Microsoft/vscode#8764]
- VSCode Version: 1.2.1 (and 1.3.0-insider)
- OS Version: Windows 8.1 Pro

![typescript-library-errors](https://cloud.githubusercontent.com/assets/8770194/16593212/9cf4bf22-42e4-11e6-9acd-1b185cc2980c.gif)

Seemingly at random when I open a typescript file, `d.ts` files will not work correctly. `Reload typescript project`, `Reload window` or navigating to `tsconfig.json` and back may remove red squiggly lines. But when one file works, another usually do not. This means I almost always have red errors in vscode for imported files or even `lib.es6.d.ts` objects/methods.

The only easy place where I can reproduce it is in my repo (see .gif above).

**Steps to Reproduce:**

1. Clone https://github.com/csvn/ng-esm.git and run `npm install`
2. Open folder with vscode
3. Navigate between different `.ts` files under `src` folder
4. vscode should complain about: unknown namespaces, Symbol, Reflect etc
5. Reload window/typescript
6. The current file should be fine, but navigating to other `.ts` files produce similar errors

I have the same issue on two computers with both insider and regular vscode. I believe this to be an issue with vscode due to typescript building without issues, and due to the randomness of the errors.

**Comment by dbaeumer** [comment]
Moving to TS team since TS smartness is powered by tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9539
