### ISSUE TITLE
Re-activate view containers if they have automatically been removed

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode#87645]
Imagine this scenario: an extension created a view container with some views for its supported file type. The user opens such a file and activates the extension view container. Now the user switches to a file not supported by that extension (and view container). The extension hides all views and as a consequence the view container is removed by vscode.

Now the user switches back to the supported file, only to have some other (usually unrelated) view container activated. It would be nice if that automatically hidden view container in the first switch is restored, once the user switches back to a file which is supported (and which shows at least one view of that container).

That would require that each editor tab stores the last active view container that was open when the editor was active. While thinking about this it seems like it is a generally interesting idea to have an option to restore the last active view container when switching editor tabs.

Here's a screen cast of what happens when you switch tabs of supported and unsupported files:

![vscode-extension](https://user-images.githubusercontent.com/2398704/71443636-6bce6280-270c-11ea-938b-6b1c75213b13.gif)

**Comment by kieferrm** [comment]
@mike-lischke to make sure we talk about the same thing, can you please attach a screencast or annotated screenshot. Thanks!

**Comment by mike-lischke** [comment]
@kieferrm screen cast uploaded, just let me know if you need more info.

**Comment by sandy081** [comment]
I see your request, in short, you would like VS Code to reopen the view container that was hidden automatically (because of all views getting hidden) when it is shown again, unless user switches to other view containers explicitly in between.

Instead, how about not switching or hiding your view container when any of the views are not shown?

**Comment by mike-lischke** [comment]
Your first sentence summarizes it pretty well. I would not use the other approach to not hide the view container if a file (tab) is selected that doesn't belong to the specific view container.

It's good that such views are only visible when a file tab is selected for which they apply. It's only that little annoyance that I have to reselect the view container when I switch away from a supported file and back to it. In other words: vscode should strive to reselect that view container, which was active when the user switched away from the file tab and comes back. That can also be useful for general view containers as this gives a more consistent experience to the user.

**Comment by sandy081** [comment]
I don't think the requested behaviour is trivial because, VS Code has to keep track of the gestures causing viewlet change. For eg., in this case VS Code has to open the restored viewlet only if there is no explicit switch of viewlets from users. I would also foresee unexpected results.

**Comment by mike-lischke** [comment]
I believe it would already be enough to track the last active view container for each tab and restore that when the user switches to it. If that view container is hidden use a default one, but keep the original reference. This wil automatically overwritten when the user switches to a different view container.

**Comment by mike-lischke** [comment]
That's what I expected. With the current inflow of requests in this repo it's rather unlikly that someone finds a specific request by accident. You have to search for a similar feature directly (which is difficult as often people have a slightly different need or formulate things a bit different) or the author has to advertise his request somehow.

Instead I speculated on you finding this idea appealing enough to implement it. If you conclude that the implementation effort outweighs the benefit then it is noth worth to keep it open any longer. I wouldn't be surprised if a similar issue comes up sooner or later again. Thanks.
