### ISSUE TITLE
Takes up all RAM, only reset helps

### ISSUE THREAD

**Issue by taluks** [microsoft/vscode#87643]
Issue Type: <b>Bug</b>

I open IDE, started edit file component angular with use ctrl+space, after a random time everything freezes, but cursor movement is available. It always repeats

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3391)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-database|baj|2.2.0
pgformatter|bra|1.10.0
bracket-pair-colorizer|Coe|1.0.61
FreeMarker|dco|0.0.9
tslint|eg2|1.0.44
freemarker-magnolia-snippets|fen|1.4.0
vscode-language-pack-ru|MS-|1.41.2
debugger-for-chrome|msj|4.12.3
foundecms|Tri|0.1.34
</details>

![photo_2019-12-24_14-49-24](https://user-images.githubusercontent.com/20488327/71412112-420a3280-265d-11ea-9ab8-fe6317907501.png)

**Comment by kieferrm** [comment]
When this happens can you pls run `code --status` in a terminal and append the output here? You can also run with the the process explorer visible (F1>Developer: Open Process Explorer). This will show us which process is consuming most of the memory. Thanks!

**Comment by taluks** [comment]
My OS freezes when I get error with red line in my code, I open Process Explorer before starting work. Here's what I managed to get, maybe the problem is in the tslint module
![photo_2019-12-26_13-34-30](https://user-images.githubusercontent.com/20488327/71473174-0d29e700-27e7-11ea-999a-7166cba6c675.png)

**Comment by mjbvz** [comment]
This is caused by the old tslint extension that has been deprecated. Please try using the new TSlint extension instead
