### ISSUE TITLE
macOS completly freezes when performing Find in Files

### ISSUE THREAD

**Issue by andreibratuleanu21** [microsoft/vscode#87647]
- VSCode:
    Version: 1.41.1
    Commit: 26076a4de974ead31f97692a0d32f90d735645c0
    Date: 2019-12-18T14:57:51.166Z
    Electron: 6.1.5
    Chrome: 76.0.3809.146
    Node.js: 12.4.0
    V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
- OS Version:
    macOS Mojave, 10.14.6 (18G2022), MacBook Pro (15-inch, 2017, 16gb ram)

Steps to Reproduce:

1. Open any project that has at least 100 files
2. Perform search in the whole project.
3. In my case macOS completely freezes, not even able to move the cursor. I need to force shutdown.

- This bug seemed intermittent at first (older versions), but now I've noticed that for some keywords that I'm searching the bug replicates consistently.
- Usually there are words that I'm pasting directly on the search input. For example if I search for `RecommendationsAction.SET_VOLUMES_FILTERS`.
- If I search this term in another project, the bug is gone.
- Also, in other projects, I've come across other terms that can cause the crash, so I can confirm it's not related to my project only.
- Tried to launch with `--disable-extensions` option, same behaviour.
- Tried to exclude as much folders and files as possible from search options (yes, I'm always excluding `node_modules` :), and even `.test` files) but I doesn't make a difference if I do it or not.
- Tried vscodium v1.41.1, same behaviour.
- Tried to keep htop open to inspect resources, but because the OS freezes completely, wasn't able to find anything.

Does this issue occur when all extensions are disabled?: **Yes**

Edit: There are other colleagues of mine in our company, working with go or/and JavaScript that have the same issue. (we have the same laptops, but some have different macOS versions) This issue started ~3 months ago, but now replicates more often.

**Comment by tillkolter** [comment]
I experience the same issues

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by roblourens** [comment]
This sounds similar to https://github.com/microsoft/vscode/issues/87254.

Can you try disabling `search.searchOnType` and see whether that helps in 1.41?

**Comment by andreibratuleanu21** [comment]
@roblourens disabling `search.searchOnType` works for me.

Thank you!

**Comment by roblourens** [comment]
Interesting, so you paste the query with that setting enabled and get the freeze, but if you disable that setting and paste the query the same way, there is no freeze?

In theory the setting shouldn't have any affect because pasting the query should only result in a single search...

FYI @JacksonKearl

**Comment by JacksonKearl** [comment]
I've confirmed that pasting a string with `searchOnType` enabled does indeed only trigger a single search. I haven't been able to reproduce the freeze.

**Comment by andreibratuleanu21** [comment]
> Interesting, so you paste the query with that setting enabled and get the freeze, but if you disable that setting and paste the query the same way, there is no freeze?
> 
> In theory the setting shouldn't have any affect because pasting the query should only result in a single search...
> 
> FYI @JacksonKearl

Yes, that's correct.

There was one isolated case when `searchOnType` was disabled and I had a lot of processes open (debugger, VMs, and other stuff opened) and after pasting something into the search input it froze but that was only once, not every time as it was happening before. 
Today I've updated to latest VSCode - *Insiders* (v. 1.42.0-insider) and switching `searchOnType` on and searching for `RecommendationsAction.SET_VOLUMES_FILTERS` in the whole project still freezes my laptop (unless I specify a narrow path like /folder/*.jsx).

**Comment by cheeseprocedure** [comment]
I'm experiencing the same behaviour (macOS Mojave 10.14.6, VS Code 1.14.1, all extensions disabled). My reproduction case is pretty simple: if I perform a search in a reasonably large repo (in my case, a Golang project with a fair number of files under ``/vendor``), **then trigger another search before the first has completed,** my machine reliably locks up to the point the cursor is stuttering, I cannot switch applications, etc.

``searchOnType`` seems to help, as it forces me to hit Enter before an in-progress search is interrupted, but it does not prevent the issue from occurring altogether.

**Comment by cephalization** [comment]
Wow pretty sure this is my issue. I even took my mbp to the apple store in an attempt to exchange it. I've been getting huge system hangs until I eventually crash and reboot, everytime it has happened has been while using vscode.

Learning a new codebase at a new job and have been searching constantly... That would explain my issues... Will turn off `searchOnType` for now

**Comment by roblourens** [comment]
I'm going to merge this into #87254.
