### ISSUE TITLE
Cannot recognize txt text properly

### ISSUE THREAD

**Issue by Kumiri** [microsoft/vscode#87646]
**English：**

<s>Use Windows Notepad to save simplified Chinese characters, assuming "1.txt" has been saved</s>
<s>Then use "Visual Studio Code" to open "1.txt", all Chinese characters become garbled.</s>

Strikethrough content has been excluded, at least not in Windows10.

Is it a compatibility issue?
Or is it a problem after compression?
Half a month ago, I downloaded the file (.rar) from the Internet and the problem also appeared in the attached txt.
However, I tested the compressed file with txt, and then decompressing it could not reproduce the problem.

<img src="https://i.vgy.me/C47iaB.png" />
<img src="https://i.vgy.me/etQ4oY.png" />

Picture 1: Text modified: March 21, 2009 (copy the text to save) ※WindowsXP SP3-Notepad.exe
Picture 2: It is the official WinRAR update text (rarlab.com—Chinese Simplified 64 bit download)
※WinRAR 5.8 has just been updated, the text is modified on December 12, 2019

**中文：**

<s>使用Winodws记事本来保存简体汉字，假设已保存“1.txt”</s>
<s>然后使用“Visual Studio Code”打开“1.txt”，中文全变成乱码。</s>

删除线内容已被排除，最起码Windows10中没有出现过。

到底是兼容性问题？
还是，压缩过后的问题？
半个月前，在网络上下载文件（.rar），附件txt里也出现这问题。
可是我测试压缩包附带txt，再解压缩没法重现问题。

**Comment by rebornix** [comment]
@Kumiri can you check what's the file encoding when you are using Notepad? I'm wondering it's because that Notepad and VS Code are using different encoding for opening/saving the file.
