### ISSUE TITLE
Want to optimize CPU usage

### ISSUE THREAD

**Issue by sbfkcel** [microsoft/vscode#87649]
- VSCode Version:1.41.1
- OS Version:macOS v10.14.6

When there are many file trees or file contents, the CPU usage will be too high.

**Comment by kieferrm** [comment]
@sbfkcel can you please provide a concrete example that shows the issue? What does your workspace look like? What steps do you take? 

Please see https://github.com/microsoft/vscode/wiki/Performance-Issues for which information we need. Thank you!

**Comment by sbfkcel** [comment]
I disabled all plugins and the problem doesn't seem to recur.
