### ISSUE TITLE
Mac Book Pro 2019 Cannot Download

### ISSUE THREAD

**Issue by christyzliang** [microsoft/vscode#87641]
Is there a way to download vscode onto the 2019 mac book pro. It always says that apple cannot verify it, which doesnt allow it to be opened

**Comment by weinand** [comment]
This is not an issue with the Mac Book Pro 2019, but with the Catalina OS installed on it.

/duplicate #74782

**Comment by weinand** [comment]
see https://github.com/microsoft/vscode/issues/74782 for details.
