### ISSUE TITLE
TSServer keeps crashing

### ISSUE THREAD

**Issue by qevni** [microsoft/vscode#87650]
Issue Type: <b>Bug</b>

Happens since previous VSCode release, and this latest.
Seems to parse the active file, then crashes. Somewhat largish project, shared JS and TS.
Used typescript 3.3.333 and now 3.7

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|32.00GB (1.54GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|3.2.0
vscode-browser-preview|auc|0.5.9
glsl-canvas|cir|0.2.7
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.11
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
nasc-touchbar|fel|1.12.0
vscode-redux-devtools|jin|1.0.2
nbpreviewer|jit|1.2.2
vscode-styled-components|jpo|0.0.27
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
azure-account|ms-|0.8.7
cpptools|ms-|0.26.2
debugger-for-chrome|msj|4.12.3
java|red|0.55.0
code-settings-sync|Sha|3.4.3
shader|sle|1.1.4
language-stylus|sys|1.11.0
react-redux-es6-snippets|tim|2.1.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
sync-rsync|vsc|0.36.0
gitblame|wad|3.0.1
propertylist|zho|0.0.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Which TS version are you currently using? TS 3.7.3? Can you share the file?

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by qevni** [comment]
> Which TS version are you currently using? TS 3.7.3? Can you share the file?
> 
> Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> /needsMoreInfo

Will have a look. Thanks

**Comment by mjbvz** [comment]
Closing as more info needed to investigate
