### ISSUE TITLE
Python input problem

### ISSUE THREAD

**Issue by wnsrl56** [Microsoft/vscode#8765]
- VSCode Version: 1.2.1
- OS Version: window 10 64bit 

Steps to Reproduce: 

when i used python extension.
1. using input function  . there is no response in program
2. this is my code

```python
print('input your number')

limit = int(input())

while limit < input: 
        limit = limit +1
        print(limit)
```

**Comment by joaomoreno** [comment]
This issue was moved to DonJayamanne/pythonVSCode#196
