### ISSUE TITLE
File New > From Template

### ISSUE THREAD

**Issue by jeffpatton1971** [microsoft/vscode#87653]
I write a lot of more or less repetitive things in VSCode, and it would be nice if I could have a Template for the various JSON documents I work with, that are already stubbed in with the basics. I've not seen a request for something like this, but kind of thinking something akin to how Word might handle it? Perhaps a templates folder with various starter files, so you could just drop like whatever files you want in there, and it just creates a new one based on the file extension, so a sample .ps1 would create a new powershell script, or a sample .json would create a new json document.

**Comment by kieferrm** [comment]
@jeffpatton1971 have you tried to snippets? Information [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets).
