### ISSUE TITLE
TypeScript and JavaScript Language Features 

### ISSUE THREAD

**Issue by ckoparir** [microsoft/vscode#87658]
Issue Type: <b>Bug</b>

JS/TS language feature initializing message on status bar cannot finish and typescript intellisense feature does not respond when this message has been showing. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz (8 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (2.44GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|2.3.2
angular-productivity-pack|dev|2.1.2
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
vscode-firefox-debug|fir|2.6.1
auto-rename-tag|for|0.1.1
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.2.0
vscode-angular2-emmet|jak|2.0.3
search-node-modules|jas|1.3.0
vscode-commitizen|Kni|0.8.4
Angular-BeastCode|Mik|8.1.2
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.14
vscode-scss|mrm|0.8.1
vscode-typescript-tslint-plugin|ms-|1.2.3
angular2-inline|nat|0.0.17
vscode-html-scss|P-d|0.0.42
vscode-css-peek|pra|3.0.2
quicktype|qui|12.0.46
project-snippets|reb|0.5.0
stylelint|shi|0.51.0
vscode-smoothtype|spi|1.2.0

(6 theme extensions excluded)

</details>

**Comment by hazem94** [comment]
The same issue happened to me! @mjbvz Disabling this extension temporarily would allow JS Intelligence to work again until this bug is fixed!

**Comment by wengdongyang** [comment]
The same issue happened to me.
Here, I have two solutions.
1.Install an older version.
2.Uninstall all plug-ins.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by Kang-Jh** [comment]
The same issues happened to me

Below is my info about this issues
- VSCode Version: 1.41.1
- OS Version: Windows 10 pro

Steps to Reproduce:
1. Disable all installed extensions
2. Disable TypeScript and JavaScript Language Features(Built-in)
3. Enable TypeScript and JavaScript Language Features(Built-in)

Does this issue occur when all extensions are disabled?: Yes

When I enable TS and JS Language Features(built-in extensions), I can't use JS Intellisense and HTML Intellisense at all in javascript files(.js). This is annoying when using react that need both JS and HTML Intellisense

**Comment by mjbvz** [comment]
Closing as we need more information from the original poster

@Kang-Jh Your issue is possibly https://github.com/microsoft/TypeScript/issues/35512 which should be fixed in VS Code insiders
