### ISSUE TITLE
Inside the JS file, code hints, user snippets, etc. don't work

### ISSUE THREAD

**Issue by anyclub** [microsoft/vscode#87652]
- VSCode Version: 1.41.1
- OS Version: win10

Inside the JS file, all hints are invalid
And inside the script tag of the .VUE file, it works fine

Including user code snippets, [JavaScript (ES6) code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets)/ [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) Etc. plugins

It seems to be related to these ISSUS  #87635    #87617    #87582 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Is your code stored on a non `c` drive? 

Also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that fix the issue?
