### ISSUE TITLE
Analysing non-stop when writing dart/flutter code

### ISSUE THREAD

**Issue by JJzhu2020** [microsoft/vscode#87655]
Issue Type: <b>Bug</b>

Dart/Fluter code.

Editing this one particular file leads to permanent analysis and basically all the features for VS code are broken.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 14, 15|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.7.0
flutter|Dar|3.7.0
vscode-eslint|dba|2.0.11
vscode-npm-script|eg2|0.3.10
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|3.17.0
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
syntax-project-pbxproj|mar|0.1.3
vscode-docker|ms-|0.9.0
Go|ms-|0.11.9
vscode-data-preview|Ran|1.49.0
js-jsx-snippets|sky|10.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by kieferrm** [comment]
I'm suspecting this is an issue with one of your extensions. To verify, please disable all extensions. You can do so by starting from the command line with `code -disable-extensions`. If the problem does not occur, then enable one extension after another and see which ones are causing the problem. Test Dart or Flutter first. Please reopen if this also happens without any extension enabled. Thank you!
