### ISSUE TITLE
Jupyter python input method - frontend does not support input requests.

### ISSUE THREAD

**Issue by gokulyc** [microsoft/vscode#87659]
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open ipynb (Jupyter file) 
2. Use input() method in a cell.
3. StdinNotImplementedError  occurs. Please find attached screenshot.

**Error:** StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

Does this issue occur when all extensions are disabled?: Yes/No -->NA (Python needed)

![image](https://user-images.githubusercontent.com/13468848/71422665-e3b77100-26a9-11ea-9335-1789ca6fdadc.png)

**Comment by kieferrm** [comment]
@gokulyc please file the issue against the Python extension here: https://github.com/Microsoft/vscode-python/issues. Thank you!
