### ISSUE TITLE
PowerShell Console exception when line input wraps beyond end-of-window

### ISSUE THREAD

**Issue by Crossbow78** [microsoft/vscode#87662]
Issue Type: <b>Bug</b>

1. Open a PowerShell terminal docked at the bottom
2. Make sure the prompt has reached the bottom line of the window (eg. by pressing Enter several times)
3. Type (or copy/paste) text until you reach beyond the end of the line (eg. by repeating '1234567890' several times).

**Expected behavior:**
* Window scrolls to make room for the wrapped line, input continues

**Actual behavior:**
* Exception (below) appears inside console, input is truncated to only the wrapped portion

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 15.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__103.MoveNext()
```

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.20GB free)|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
xml|Dot|2.5.0
vsc-material-theme|Equ|30.0.0
gc-excelviewer|Gra|2.1.32
rest-client|hum|0.23.0
ftp-simple|hum|0.7.5
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
mssql|ms-|1.8.0
python|ms-|2019.11.50794
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
vscode-node-azure-pack|ms-|0.0.10
azurerm-vscode-tools|msa|0.8.3
vetur|oct|0.22.6
vscode-hexdump|sle|1.7.2
sort-lines|Tyr|1.9.0
azure-iot-edge|vsc|1.19.0
azure-iot-toolkit|vsc|2.14.0
azure-iot-tools|vsc|0.3.0
vscode-arduino|vsc|0.2.28
vscode-iot-device-cube|vsc|0.1.4
vscode-iot-workbench|vsc|0.10.18
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by yume-chan** [comment]
Looks similar to #78967 and PowerShell/vscode-powershell#702, possible resolution in second link.
