### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by GolfMan2000** [microsoft/vscode#87667]
Issue Type: <b>Bug</b>

Follow a first time tutorial that just create a simple project and start typing with no Intellisense.  How to activate Intellisense??

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.92GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kieferrm** [comment]
@GolfMan2000 can you please add a link to the tutorial? Thank you.

**Comment by GolfMan2000** [comment]
I start vscode
Create a new folder then new file and start typing and no intellisense guiding me!!!!

**Comment by kieferrm** [comment]
@GolfMan2000 can you please add a link to the tutorial? Thank you.

**Comment by GolfMan2000** [comment]
https://m.youtube.com/watch?v=<https://m.youtube.com/watch?v=xDhsz5AdLZ8>xDhsz5AdLZ8<https://m.youtube.com/watch?v=xDhsz5AdLZ8>

My failure is that I don't see suggestions as I type...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kieferrm** [comment]
@GolfMan2000 the video shows editing java code. You either need to install the Java extension  from the [marketplace](https://marketplace.visualstudio.com/items?itemName=redhat.java), or if you already have the extension, please file the issue against the Java extension [here](https://github.com/redhat-developer/vscode-java/issues).
