### ISSUE TITLE
Santa hat being removed goes against many religion and there beliefs, we have to celebrate there said festivities etc so readd it.  

### ISSUE THREAD

**Issue by Taco360noscope** [microsoft/vscode#87663]
Hi I find it disrespectful to the many religions that celebrate Christmas that the santa hat was removed when we have to celebrate and put up with many other festivities and events by other groups. please add it back. The other religious groups have a choice to take part or not, and this issue wasent handled very well when there could of been a simple toggle therefore many users are offended over the remover of such a loved symbol.
Much Love mwah
 *<:-)

**Comment by gjsjohnmurray** [comment]
#87440 tells you how it is now configurable.

/duplicate

**Comment by lviggiano** [comment]
Removing Santa Hat is a hate crime against everyone who believes in Santa. Please re-add it enabled by default.
