### ISSUE TITLE
jupyter notebook wont execute correct env

### ISSUE THREAD

**Issue by BillmanH** [microsoft/vscode#87669]
Issue Type: <b>Bug</b>

Jupyter notebook (.ipynb) only executes in base. Doesn't execute other envs. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
azure-account|ms-|0.8.7
team|ms-|1.161.0
vscode-yaml|red|0.6.1

</details>

**Comment by BillmanH** [comment]
Steps to reproduce: 
Have base conda env with no azureml tools. 
Have a conda env with azureml tools. 

In VSC, open a notebook and enter:
`from azureml.core import Workspace`

error: 
`ModuleNotFoundError: No module named 'azureml'`

There is no way to switch the jupyter notebook away from base, making it useless for projects that use an environment.

**Comment by kieferrm** [comment]
@BillmanH please file the issue against the Python extension [here](https://github.com/Microsoft/vscode-python/issues). Thank you!

**Comment by BillmanH** [comment]
Interesting that this is a python issue as it only happens in vs code. You can do this in literally any other IDE, even vs2019.
