### ISSUE TITLE
Bug with quick search field on settings tab

### ISSUE THREAD

**Issue by Sendoo** [microsoft/vscode#87670]
- VSCode Version: 1.41.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Go to settings
2. Type something in the search field
3. Go to another editor tab
4. Return to settings tab
5. Try to edit the previously entered text in the search field
6. Not editable 🤨

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

**Comment by roblourens** [comment]
I can't reproduce this. Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by Sendoo** [comment]
At the moment I have at hand another laptop with the same version of software.
And here I can’t reproduce it, it works correctly 😮
