### ISSUE TITLE
html.format.endWithNewline not working

### ISSUE THREAD

**Issue by cmegown** [Microsoft/vscode#8767]
- VSCode Version: 1.2.1
- OS Version: Windows 8.1 Pro

Steps to Reproduce:

1. Open user settings `File > Preferences > User Settings`
2. Add `"html.format.endWithNewline": true`

I assume this should make sure that there is a new line at the end of every file (or only `.html` files?) on create or save.

**Comment by aeschli** [comment]
This is only for the html formatter (Note the 'html.' prefix)
From what I tried, the setting works.
Setting false:
![image](https://cloud.githubusercontent.com/assets/6461412/16630923/aa5768e4-43bc-11e6-92f7-db870a5ff453.png)
Setting true:
![image](https://cloud.githubusercontent.com/assets/6461412/16630945/c10e6010-43bc-11e6-96cb-feceeb69aa03.png)

**Comment by cmegown** [comment]
I do not get the same result. Here's my `settings.json`:

```
// Place your settings in this file to overwrite the default settings
{
    "html.format.endWithNewline": true
}
```

I tried saving an existing `.html` file, as well as creating a new `.html` file, and did not see the correct result either time. Side note: why not allow for inserting a new line at the end of any file type?
