### ISSUE TITLE
Use wsl to connect to linux remotely, vi command Chinese garbled

### ISSUE THREAD

**Issue by pikadun** [microsoft/vscode#87678]
- VSCode Version:lasted
- OS Version:lasted

Steps to Reproduce:
1.open **wsl** in vscode and open the terminal
2.ssh to server
3.use vi to edit file contains Chinese
4.Chinese cannot be displayed correctly

Right steps:
1.open the terminal and use cmd.exe
2.ssh to server
3.use vi to edit file contains Chinese
4.all is work well

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@pikadun can you please provide concrete instructions about step 1)? How do you open `wsl` in VS Code? Do you talk about the Remote-WSL extension?

**Comment by Tyriar** [comment]
This issue is very likely related to your ssh server not working in UTF-8 encoding. Try running `echo $LANG` in a terminal where the characters display correctly and in the terminal where it doesn't.

**Comment by pikadun** [comment]
> @pikadun can you please provide concrete instructions about step 1)? How do you open `wsl` in VS Code? Do you talk about the Remote-WSL extension?

@kieferrm 
I installed wsl and run command in cmd
```Bash
code ./
```
it's would open a new vscode window,
and I pressed ctrl + ` to open terminal,
vscode would oepn a terminal with wsl bash.
this is all operation of step 1).
thank you!

**Comment by pikadun** [comment]
thank all very much!
it a vi encoding problem!
