### ISSUE TITLE
Trying to run C# applications crashes the window

### ISSUE THREAD

**Issue by PhilipHassialis** [microsoft/vscode#87671]
Issue Type: <b>Bug</b>

Go into an empty folder and run dotnet new console. 
Open the folder in VS Code (C# extension is already installed)
Press F5 or Ctrl+F5
The mini popup window with pause/stop/other debug icons appears for a second or so and then I get a message "Window has crashed".

FYI I am using dotnetcore 3.1, I don't know if this has to do anything.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4014)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
vscode-javascript-snippet-pack|aka|0.1.5
svelte-intellisense|ard|0.7.1
simple-react-snippets|bur|1.2.2
bracket-pair-colorizer|Coe|1.0.61
riot-tag|cri|0.1.7
vscode-eslint|dba|2.0.11
java-decompiler|dgi|0.0.2
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.18.0
vscode-firefox-debug|fir|2.6.1
auto-rename-tag|for|0.1.1
vscode-javac|geo|0.2.31
path-autocomplete|ion|1.13.3
java-properties|ith|0.0.2
svelte-vscode|Jam|0.9.3
Angular2|joh|8.3.0
remote-wsl|ms-|0.41.6
csharp|ms-|1.21.9
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
vscode-spring-boot|Piv|1.14.0
material-icon-theme|PKi|3.9.2
vscode-jsp|pth|0.0.3
java-ide-pack|pve|1.2.1
java|red|0.55.1
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|1.8.0
markdown-preview-enhanced|shd|0.5.0
java-generate-setters-getters|soh|4.2.2
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
vscode-spring-boot-dashboard|vsc|0.1.7
vscode-spring-initializr|vsc|0.4.6
vscode-icons|vsc|9.6.0
JavaScriptSnippets|xab|1.7.2
vscode-java-saber|You|0.1.1

(8 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Please file the issue against the C# extension [here](https://github.com/OmniSharp/omnisharp-vscode/issues). Thank you!
