### ISSUE TITLE
react 不在提示问题

### ISSUE THREAD

**Issue by github-yuminhui** [microsoft/vscode#87676]
Issue Type: <b>Feature Request</b>

配置了react提示，只有在vscold刚启动的几分钟有提示功能。紧接着就不再提示了，必须重启vscold才能恢复一会儿。

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by yx201103707** [comment]
相同的问题

**Comment by byyxx128** [comment]
English Please!
