### ISSUE TITLE
extension code not open settingPage and Details 

### ISSUE THREAD

**Issue by fyeeme** [microsoft/vscode#87674]
**Version: 1.42.0-exploration**
Commit: 25d09f2ef5a379e8a3aedd1c821bd866a5efe58c
Date: 2019-12-19T09:27:39.593Z
Electron: 7.1.5
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

Steps to Reproduce:
 extensions could not open detail tab and that which has setting page stand alone also could not open, 
but before upgrade to 1.42.0 ,1.31.0  is normal.
![image](https://user-images.githubusercontent.com/6078758/71428145-ec379800-26f9-11ea-9216-078c86eae68a.png)

Does this issue occur when all extensions are disabled?: Yes. it  both happens on installing extensions and installed extensions

**Comment by kieferrm** [comment]
Issue in exploration build.

**Comment by fyeeme** [comment]
when will this be fixed?@kieferrm

**Comment by deepak1556** [comment]
Should be fixed in recent versions, can reopen if not.
