### ISSUE TITLE
File opened in editor is not highlighted in explorer

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#87686]
Issue Type: <b>Bug</b>

description:
If a file is opened in editor or active in the editor, the explorer should show the file and its location in the explorer tree.
this used to be the case earlier. it's not working this way now.

steps to reproduce:
1. open a folder in VSCode with lots of files and sub-folders 
2. open few files from different folders.
3. focus on files and check if an active file is highlighted in explorer.

current behavior: file is not highlighted in explorer
expected behavior: The file should be highlighted.

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-64-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (2.59GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.6.1
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.96.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.42.0
vscode-remote-extensionpack|ms-|0.19.0
debugger-for-chrome|msj|4.12.3
aws-toolkit-vscode|ama|1.4.0
ng-template|Ang|0.900.3
atlascode|atl|2.2.1
jshint|dba|0.10.21
vscode-eslint|dba|2.0.11
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
vscode-docker|ms-|0.9.0
vscode-kubernetes-tools|ms-|1.0.9
vscode-postgresql|ms-|0.2.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1404
vsliveshare-audio|ms-|0.1.80
cordova-tools|msj|1.9.1
vscode-react-native|msj|0.13.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.14.0
vscode-manifest-yaml|Piv|1.14.0
vscode-spring-boot|Piv|1.14.0
fabric8-analytics|red|0.0.13
java|red|0.55.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.6.1
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
vscode-spring-boot-dashboard|vsc|0.1.7
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by isidorn** [comment]
I can not reproduce this.
I see that you have 44 extensions. Can you please disable all extension and try to reproduce?
Do you have `explorer.autoReveal: true` set in your settings (which is the default btw)

Do you do something different than me in this gif?

![reveal](https://user-images.githubusercontent.com/1926584/71512931-8cc3be80-2898-11ea-8c07-13ec748e43ca.gif)

**Comment by sanket-bhalerao** [comment]
@isidorn, 
can you try to collapse all folders with th "-" icon in the explorer, and then check?

**Comment by isidorn** [comment]
Yes, it still works.
Can you now try to answer my questions? :)

**Comment by sanket-bhalerao** [comment]
@isidorn, I have not set the `explorer.autoReveal` to an explicit value. and its default value is set to true.

**Comment by sanket-bhalerao** [comment]
I have 2 different machines, both have the same settings and the same set of extensions. the issue is appearing on one setup only. I have already tried to disable all extensions, uninstalling them, and removing all the settings as well. the only thing remaining to uninstall vscode insiders :). which I am not able to do due to lack of download/install permission (as this is office setup)

**Comment by isidorn** [comment]
If you F1 > develoepr tools > do you see some errors in the debug console?

**Comment by sanket-bhalerao** [comment]
I haven't seen any, but I will be able to confirm this on Monday.

**Comment by isidorn** [comment]
Ok, do let me know. Any minimal steps to repro would aslo be useful.

**Comment by sanket-bhalerao** [comment]
@isidorn after a couple of vscode restarts I am not able to reproduce the issue. 
If this happens again i will reopen/recreate similar ticket.
closing this issue as i am not able to reproduce or provide any concrete steps to reproduce the issue. 😞
