### ISSUE TITLE
An error occurred while signing in: tunneling socket could not be established, statusCode=400

### ISSUE THREAD

**Issue by logeshpalani98** [microsoft/vscode#87688]
- VSCode Version: 1.41.1
- OS Version: Windows 10 Insider Build 19018

Steps to Reproduce:
1. Uninstall and reinstalled extensions 
2. Tried in VS Code & VS Code insiders.

**Error**
Error: tunneling socket could not be established, statusCode=400	at ClientRequest.a (c:\Users\loges\.vscode\extensions\ms-vscode.azure-account-0.8.4\dist\extension.js:221:234974)	at Object.onceWrapper (events.js:273:13)	at ClientRequest.emit (events.js:182:13)	at Socket.socketOnData (_http_client.js:474:11)	at Socket.emit (events.js:182:13)	at addChunk (_stream_readable.js:283:12)	at readableAddChunk (_stream_readable.js:264:11)	at Socket.Readable.push (_stream_readable.js:219:10)	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

Does this issue occur when all extensions are disabled?: Yes

![Screenshot (59)](https://user-images.githubusercontent.com/24875197/71446148-2464c800-2746-11ea-9ae7-59917a6b9114.png)

**Comment by mjbvz** [comment]
This error comes from the azure account extension (see the stack trace)

Please file this issue against that extension
