### ISSUE TITLE
截图有bug

### ISSUE THREAD

**Issue by 342033340** [microsoft/vscode#87687]
vscode使用了background拓展后，QQ的长截图无法在VScode运行，只能截取当前页面图

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
1. Please report in English.
2. Please report as extension issue.
***
扩展的问题你报告给扩展啊……看图——
![image](https://user-images.githubusercontent.com/20079289/71449348-5fe89d80-2718-11ea-8ebe-82b7e179e7cf.png)
直接在程序里报告。
