### ISSUE TITLE
Snippets in JSON Schema documentation issue

### ISSUE THREAD

**Issue by PetaSoft** [microsoft/vscode#87684]
The documentation of the definition of snippets in JSON schemas at https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas lacks some important information: <br>
The last sentence says:
> Note that defaultSnippets is not part of the JSON schema specification but a VS Code-specific schema extension.

As it is not part of the JSON schema specification You must provide the information how to use such *defaultSnippets* but I cannot find that information anywhere in the JSON language documentation. Normally, a snippet defition in VS Code has a `prefix`part, e.g. (https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets)
```json
{
  "For Loop": {
    "prefix": ["for", "for-const"],
    "body": ["for (const ${2:element} of ${1:array}) {", "\t$0", "}"],
    "description": "A for loop."
  }
}
``` 
It that case, when I want to use that snippet, I type one of the strings which are part of the `prefix` section of the snippet, and I get a suggestion with the `description` part of the snippet. When I now press `Enter`, the body of the snippet is inserted into the document. <br>
However, how do I use one of the `defaultSnippets` defined in a JSON schema file? There is no `prefix` part, and the `label`part does not work, too. That information should be part of the documentation. Otherwise, I cannot use `defaultSnipperts`.

**Comment by aeschli** [comment]
But isn't that already explained just above, in the same paragraph?
https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas

There's also an example how you define such a default snippet.


```
{
    "type": "array",
    "title": "Keybindings configuration",
    "items": {
        "type": "object",
        "required": ["key"],
        "defaultSnippets": [
            {
                "label": "New keybinding",
                "description": "Binds a key to a command for a given state",
                "body": { "key": "$1", "command": "$2", "when": "$3" }
            }
        ],
        "properties": {
            "key": {
                "type": "string"
            }
            ...
        }
    }
}
```

Note that you would only use that if you are a JSON schema author. Or if you implement you own extension with settings.

**Comment by aeschli** [comment]
I added the image to the docs.
