### ISSUE TITLE
Focus at dialogbox

### ISSUE THREAD

**Issue by der-andrew** [microsoft/vscode#87689]
Issue Type: <b>Feature Request</b>

When I save protected file (f.e. hosts), its popup dialogbox about  insufficient permission. OK. And cursor still in editor window. But it would better if cursor at dialogbox to just press enter) Otherwize I have to annoy mouse/touchpad... and waste expensive time.
![image](https://user-images.githubusercontent.com/40394363/71446340-430d9380-2733-11ea-8e8b-6e33fe50fdb7.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by kieferrm** [comment]
We use a notification in this case rather than a modal dialog. @bpasero for consideration of using a model dialog.

**Comment by bpasero** [comment]
This is configurable to have a keyboard shortcut, see this list:

![image](https://user-images.githubusercontent.com/900690/71507662-8a0b9e00-2885-11ea-90eb-cca522f5800b.png)

**Comment by der-andrew** [comment]
Thanks! Advise was usefull.
But don't you agree its logically that after ctrl+s the next action is press smth on dialog box. So why don't coded that out of box?
