### ISSUE TITLE
I DEMAND the bring back of the Santa Hat

### ISSUE THREAD

**Issue by rroethof** [microsoft/vscode#87683]
The world is going insane with the racism thing.
Bring back the santa hat NOW..

**Comment by virgiliu** [comment]
as per their announcement, "even a single person being offended is one too many", but only if it's related to religion or something. censorship is fine.

**Comment by gjsjohnmurray** [comment]
See #87440 for how to turn it on

/duplicate

**Comment by schwarcu** [comment]
Removing Santa Hat on vscode insiders is very offensive to me. Because it means product  supports anti-christian movements that happen across the globe.
Removing Santa Hat to me this is almost equally offensive as a swastika.

Please bring it back immediately and make it your top priority.
