### ISSUE TITLE
Can't start js pugin server

### ISSUE THREAD

**Issue by fengdachao** [microsoft/vscode#87681]
Issue Type: <b>Bug</b>

Add jsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  },
  "include": ["src/**/*.js"],
  // "exclude": ["node_modules", "**/node_modules/*"]
}

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (2.97GB free)|
|Process Argv|-psn_0_1978851|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.11
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
vscode-jest|Ort|3.1.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.20
vscode-icons|vsc|9.6.0
json|Zai|1.0.2

</details>

**Comment by kieferrm** [comment]
@fengdachao can you please provide step-by-step instructions that allow us to reproduce your problem? Thank you!
