### ISSUE TITLE
[Explorer bar], show updates is not timely

### ISSUE THREAD

**Issue by xoeaza** [microsoft/vscode#87699]
Issue Type: <b>Bug</b>

[Explorer bar], show updates is not timely, after npm install nodemodule, you must close and restart vscode to display nodeModule

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (17.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

</details>

**Comment by kieferrm** [comment]
@xoeaza to avoid too many file changes, VS Code excludes `node_modules` by default from file watching.

![Screen Shot 2019-12-26 at 1 19 38 PM](https://user-images.githubusercontent.com/4674940/71490934-883cce80-27e2-11ea-8d8d-713336061c37.png)
