### ISSUE TITLE
Modified lines doesn't get annotated if you pull while in annotation mode

### ISSUE THREAD

**Issue by yonifra** [microsoft/vscode#87692]
VS Code Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open a file with Annotations turned on (from the top menu button)
2. Go to a section of the code where you know the code was changed in `master`
3. Do a `git pull` to get latest code from `master` branch
4. Notice that the new modified line isn't annotated
5. After un-annotating and re-annotating it works as expected

Result:
![image](https://user-images.githubusercontent.com/726718/71447365-0db67500-2736-11ea-8fa7-46b0e4220f9c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What are Annotations? Is this an extension? A screen recording would help.

**Comment by yonifra** [comment]
@joaomoreno so sorry for the confusion, I was using GitLens and this button is coming from that extension. I've been using GitLens for so long that I already thought that this button is part of vscode. But now thinking about it, vscode should really have a blame feature for git built in.
