### ISSUE TITLE
do not highlight white spaces

### ISSUE THREAD

**Issue by zhyiyu** [microsoft/vscode#87697]
There is a feature in VS code which would highlight the word you selected. It is nice and convenient but it also highlights white spaces, like below

![space](https://user-images.githubusercontent.com/26550166/71449200-61b16180-2716-11ea-950c-29a0e76b4b8f.png)

This does not seem necessary, at least to some people. It would be nice if we can have the feature "do not highlight white spaces".

Thanks!

**Comment by yume-chan** [comment]
Code doesn't do this by default. Please check your "editor.renderWhitespace" setting and try to disable all extensions (by running the "Developer: Run With Extensions Disabled" command).

**Comment by kieferrm** [comment]
@zhyiyu  see comment above. This is not default behavior. Please check your extensions. Thank you!

**Comment by zhyiyu** [comment]
Yes, you are right, it is [highlight icemode](https://marketplace.visualstudio.com/items?itemName=iceliu.highlight-icemode) that does, thanks!
