### ISSUE TITLE
长行问题

### ISSUE THREAD

**Issue by wujiekd** [microsoft/vscode#87691]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by byyxx128** [comment]
1. Please report in English.
2. What's your problem?
***
上面这句话意思是，你的数据太大，不能直接发送，所以自动打开浏览器之后，请Ctrl+V过来粘贴一下，你倒好，直接把这句话发出去……另外请务必讲英文。这个issue你关闭吧，重新报告一个，数据太大的话过来再粘贴一下。

**Comment by wujiekd** [comment]
Ok，thanks。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"byyxx128"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 凌晨2:11
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"~笨ぁ小孩☆"<2684488096@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] 长行问题 (#87691)



 
Please report in English.
 
What's your problem?
  
 
上面这句话意思是，你的数据太大，不能直接发送，所以自动打开浏览器之后，请Ctrl+V过来粘贴一下，你倒好，直接把这句话发出去……另外请务必讲英文。这个issue你关闭吧，重新报告一个，数据太大的话过来再粘贴一下。
