### ISSUE TITLE
Eliminate all schema based attributes from IEnvConfig

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8769]
`IEnvConfig` still has attributes that are debug type specific and are defined as a contributed schema. It makes no sense to have them in an interface and to use them.

Here are the bogus attributes:
```ts	
	program?: string;
	stopOnEntry?: boolean;
	args?: string[];
	cwd?: string;
	runtimeExecutable?: string;
	runtimeArgs?: string[];
	env?: { [key: string]: string; };
	sourceMaps?: boolean;
	outDir?: string;
	address?: string;
	port?: number;
	externalConsole?: boolean;
```

**Comment by isidorn** [comment]
Elimintaed all except the following which we use internally for extension host debugging:
```ts
sourceMaps?: boolean;
outDir?: string;
port?: number;
```

**Comment by weinand** [comment]
@isidorn for now, please create an explicit interface for them. e.g. IExtHostConfig. And add a comment that this has to match the extensionHost scheme.

I will look into this to figure out why they are really needed.

**Comment by isidorn** [comment]
@weinand makes sense, I introduced IExtHostConfig

**Comment by aeschli** [comment]
verified in code
