### ISSUE TITLE
Initializing JS/TS language features doesn't work

### ISSUE THREAD

**Issue by mmiszy** [microsoft/vscode#87695]
Issue Type: <b>Bug</b>

> The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 5, 4|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|1.5.0
pgformatter|bra|1.10.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.11
vscode-generate-getter-setter|DSK|0.5.0
dbml-language|duy|0.0.1
gitlens|eam|10.2.0
tslint|eg2|1.0.44
prettier-vscode|esb|3.18.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
reason-vscode|jar|1.7.4
vscode-docker|ms-|0.9.0
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
vs-sequential-number|nep|1.0.0
indent-rainbow|ode|7.4.0
tsimporter|pmn|2.0.1
prisma|Pri|0.0.20
vscode-graphql|Pri|0.2.2
quicktype|qui|12.0.46
testcafe-test-runner|rom|2.0.0
cucumber|ste|0.12.0
vscode-icons|vsc|9.6.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/neesMoreInfo
