### ISSUE TITLE
通过内容猜测编码错误

### ISSUE THREAD

**Issue by sunyum** [microsoft/vscode#87690]
Issue Type: <b>Bug</b>

files.autoGuessEncoding = true
Automatically identify errors
My file is [utf8] encoded, but it is always recognized as [Windows 1252] after closing and reopening
[index.txt](https://github.com/microsoft/vscode/files/4000494/index.txt)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.33.0
githistory|don|0.4.12
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|3.18.0
auto-rename-tag|for|0.1.1
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.41.2
vetur|oct|0.22.6
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.2

</details>

**Comment by byyxx128** [comment]
#33720
