### ISSUE TITLE
[html] tag auto close on intellisense

### ISSUE THREAD

**Issue by PhenomanSolutions** [Microsoft/vscode#877]
HTML tags are not closing automatically and when i edit one tag the ending part is not being modified too.

**Comment by TheColorRed** [comment]
+1

**Comment by aeschli** [comment]
Can you please provide more details? Please give an example on what you type and what you expect to be automatically added.
For html we have two ways of creating closing tags:
- type `</` and do intellisense
- type the tag name (e.g. `div`) and press `tab`. This completes to `<div></div>`

**Comment by TheColorRed** [comment]
I didn't know you could just type the name of the tag it auto creates both opening and closing tags. It would be nice to also type `<div` and press <kbd>tab</kbd> and have the same effect.

**Comment by PhenomanSolutions** [comment]
In general, the intuitive way of typing is when you type `<` then intellisense suggests some examples and when I select it hitting <kbd>enter</kbd> it must auto-complete to full tag: example
I typed `<` and from the intellisense hints selected `div` currently when i hit  <kbd>enter</kbd> it looks like `<div` but must look like `<div></div>` and when I edit the opening tag to `p` would be nice if it will automatically change the closing tag to `p` so it will look like `<p></p>` and not `<p></div>`
and one more case of auto-complete is when i have `<div` and when i close the tag: `<div>` it MUST automatically add the closing tag: `<div></div>` 
for special cases like `input` or `link` it can do nothing or if it is possible it can replace the closing tag to `/>`

**Comment by aeschli** [comment]
Thanks for the clarification and the suggestions.

BTW, to update start and end tag, you can currently use 'Change all occurrences' from the context menu

**Comment by TheColorRed** [comment]
So, it looks like VS Code uses Element style html: http://docs.emmet.io/

where this:

    ul#nav>li.item$*4>a{Item $}

becomes this once you tab:

    <ul id="nav">
        <li class="item1"><a href="">Item 1</a></li>
        <li class="item2"><a href="">Item 2</a></li>
        <li class="item3"><a href="">Item 3</a></li>
        <li class="item4"><a href="">Item 4</a></li>
    </ul>

**Comment by GarethOates** [comment]
+1

**Comment by formulahendry** [comment]
@PhenomanSolutions This [Extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) would meet with your requirement. It will automatically add closing tag when you type in the closing bracket of the opening tag.

![GIF](https://raw.githubusercontent.com/formulahendry/vscode-auto-close-tag/master/images/usage.gif)

**Comment by dcworldwide** [comment]
Auto-updating the closing tag when changing the type of the opening tag would be a big productivity win for me. It's something that I'm really used to with Webstorm. 'Change all occurrences' won't work for me becuase I only want to change the type of a single tag at a time.

**Comment by formulahendry** [comment]
@dcworldwide , do you mean to automatically rename paired HTML/XML tag like below?

![auto-rename-tag](https://raw.githubusercontent.com/formulahendry/vscode-auto-rename-tag/master/images/usage.gif)

You may try [Auto Rename Tag ](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)

**Comment by PhenomanSolutions** [comment]
Seems ok, 👍, the only annoying part is for every small single thing you need to install an extension, these are kind of a basic staff that every (now days) IDE should have by default.

**Comment by dcworldwide** [comment]
Auto tag is neat thanks

**Comment by KokoDoko** [comment]
After the latest VS Code updates, html autocomplete is not working at all anymore:

- type the tag name (e.g. div) and press tab. This does **not** complete to `<div></div>`
- start a tag by typing `<` and then choose the tag from the list by pressing enter. This does **not** even complete the tag and also does **not** add a closing tag

**Comment by aeschli** [comment]
@KokoDoko You'd have to file new issues. 
> type the tag name (e.g. div) and press tab. This does not complete to <div></div>'

This is Emmet completion and has been a recent change with emmet: Read [here](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

> start a tag by typing < and then choose the tag from the list by pressing enter. This does not even complete the tag and also does not add a closing tag

I just tested this and pressing enter on the suggestion list does select and insert the proposal. It does not add the '>' but that as designed (you might want to add attributes). Entering `>` with the keyboard will then auto close the tag (since the 1.17 release)

So please file a new issue and please add more details such as a code snippet to reproduce., Don't forget to try without any extensions enabled
