### ISSUE TITLE
[Debug] "Run In Terminal" is broken in the 1.42.0-insider

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#87700]
```
Version: 1.42.0-insider (system setup)
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:57:35.999Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

### **Issue 1:**
I already set my integrated terminal to cmd via `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"`. But when i choose to run my Java program in the integrated terminal, it always opens powershell to run my program. This issue only appears in the insider version.

### **Issue 2:**
The powershell in the insider doesn't escape the runInTerminal command line arguments well.

Here is the DAP request.
```json
{
    "command": "runInTerminal",
    "arguments": {
        "kind": "integrated",
        "title": "Java Debug Console",
        "cwd": "c:\\spring-petclinic",
        "args": [
            "C:\\Users\\jinbwan\\.vscode-insiders\\extensions\\vscjava.vscode-java-debug-0.24.0\\scripts\\launcher.bat",
            "C:\\Program Files\\Java\\jdk1.8.0_231\\bin\\java",
            "-agentlib:jdwp\u003dtransport\u003ddt_socket,server\u003dn,suspend\u003dy,address\u003dlocalhost:51804",
            "-Dfile.encoding\u003dUTF-8",
            "-cp",
            "C:\\Users\\jinbwan\\AppData\\Local\\Temp\\cp_ahnlxjst7ispcqdhfngxir0if.jar",
            "org.springframework.samples.petclinic.PetClinicApplication"
        ]
    },
    "seq": 2,
    "type": "request"
}
``` 

Below is the powershell screenshot in the stable **vscode 1.41.1**, it works well.
![image](https://user-images.githubusercontent.com/14052197/71453506-79482300-27c6-11ea-86fd-b36c28abc6f7.png)

Below is the powershell screenshot in the **1.42-insider**, it doesn't work.
![image](https://user-images.githubusercontent.com/14052197/71453563-c3c99f80-27c6-11ea-8d63-5206912ab42b.png)

**Comment by testforstephen** [comment]
Have a try to set my integrated terminal to powershell directly, it works. Looks like VS Code sent the cmd-style arguments to powershell by mistake.

**Comment by astrelsky** [comment]
I would just like to note that I have faced issue 2 for several weeks now. Possibly since the beginning of December.

**Comment by kieferrm** [comment]
@testforstephen I'm guessing you are using extensions for Java. Can you list the extension versions that run in insiders and the versions that run in stable? If it's the same version, the code change is in the VS Code core.

**Comment by testforstephen** [comment]
In the insider, i just enable three Java extensions, and they are the same version as those running in the stable.
![image](https://user-images.githubusercontent.com/14052197/71495999-aca0b580-288b-11ea-9867-e1c96c010113.png)

Anyway, i'm the committer of these Java extensions, i believe this issue is not caused by the Java extensions.

**Comment by weinand** [comment]
In VS Code 1.38 (August) we've introduced the notion of an "automationShell" setting which is used when VS Code runs tasks or debug targets in the integrated terminal (see https://code.visualstudio.com/updates/v1_38#_new-shell-setting-for-launching-a-debug-target and https://code.visualstudio.com/updates/v1_38#_automation-shell-setting).

So if you want to configure VS Code to use the command prompt ("cmd.exe") when launching the debug target from the integrated terminal, you must change 
```js
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
```
to
```js
    "terminal.integrated.automationShell.windows": "C:\\Windows\\System32\\cmd.exe",
```

@Tyriar do you know why this problem surfaces only in the latest Insiders (1.42.0) and not in the August release (1.38.0), where this new concept was introduced?

**Comment by Tyriar** [comment]
@weinand there was a regression around terminal settings recently that I'm trying to work through with @sandy081 in https://github.com/microsoft/vscode/issues/87088, I would guess this is due to that.

**Comment by Tyriar** [comment]
@weinand you should probably revert your fix as `getDefaultShell` is meant to handle `automationShell`

**Comment by weinand** [comment]
@Tyriar thanks!
Another question:
I'm using this code to find value of the `automationShell` in the extension host:
```ts
const configProvider = await this._configurationService.getConfigProvider();
const terminalConfig = configProvider.getConfiguration('terminal');

let shell;
const automationShellConfig = terminalConfig.integrated.automationShell;
if (automationShellConfig) {
	if (env.isWindows) {
		shell = automationShellConfig.windows;
	} else if (env.isLinux) {
		shell = automationShellConfig.linux;
	} else if (env.isMacintosh) {
		shell = automationShellConfig.osx;
	}
}
if (!shell) {
	shell = this._terminalService.getDefaultShell(true, configProvider);
}
```

Is there a simpler way?
something like:
```ts
shell = this._terminalService.getShell(true, configProvider);
```

**Comment by Tyriar** [comment]
@weinand maybe it's badly named but `getDefaultShell` gets the "default" after considering all settings/environment factors. automationShell is meant to be considered here:

https://github.com/microsoft/vscode/blob/eaf427d740f7d3aea7c385d113c320956c8a85dc/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L248-L264

**Comment by weinand** [comment]
@Tyriar `getDefaultShell` does not work for me.

If I have this setting on macOS:
```js
	"terminal.integrated.automationShell.osx": "/usr/local/bin/powershell",
```
then this code:
```ts
	const configProvider = await this._configurationService.getConfigProvider();
	let shell = this._terminalService.getDefaultShell(true, configProvider);
```
results in shell set to `/usr/local/bin/bash`.

**Comment by Tyriar** [comment]
@weinand yes I think it's broken because of #87088

**Comment by weinand** [comment]
Ok, then I will keep my current code as a workaround until #87088 is fixed.

**Comment by weinand** [comment]
I've removed my workaround for #87088 since #87088 is fixed now.
