### ISSUE TITLE
Find in Folder issue

### ISSUE THREAD

**Issue by arjun-707** [microsoft/vscode#87707]
Issue Type: <b>Bug</b>

Visual code automatically closing after few minutes finding in `Find in Folder` tab. Due to this issue all tabs are closing (file not saved or project loaded removed)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.9.1
prettier-vscode|esb|2.2.2
vscode-docker|ms-|0.7.0
python|ms-|2019.3.6558
code-spell-checker|str|1.6.10

</details>

**Comment by kieferrm** [comment]
@arjun-707 thank you for reporting the issue. Can you please provide step by step instructions that help us recreating the problem, or please attach a screen recording. Thank you!

**Comment by arjun-707** [comment]
Sure, will share the video
