### ISSUE TITLE
Encountering a BUG when developing Java with vscode

### ISSUE THREAD

**Issue by thomas1984** [microsoft/vscode#87703]
- VSCode Version:1.40.1
- OS Version:Linux x64 5.0.0-37-generic

Steps to Reproduce:

1.
![Screenshot from 2019-12-26 11-27-03](https://user-images.githubusercontent.com/6303182/71456574-03978380-27d5-11ea-942e-b6a6f469ee4f.png)

2.As shown above, the department ID on line 61 of the code prompts an error, but there is actually no error here. The error is that the parenthesis is missing from line 64.I think this is a hint to locate the bug.
3.When I remove the parentheses on line 64, the error is no longer prompted

4.
![Screenshot from 2019-12-26 11-48-55](https://user-images.githubusercontent.com/6303182/71456715-b9fb6880-27d5-11ea-9eb4-e63366c2b809.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
@thomas1984 please file this issue against the Java extension [here](https://github.com/redhat-developer/vscode-java/issues). Thank you!
