### ISSUE TITLE
[folding] Allow folding controls to be themeable

### ISSUE THREAD

**Issue by iamfraggle** [microsoft/vscode#87702]
I do not see a way to set the theme colour of the folding controls in the gutter.  The same is also true of the 'edit' control used for certain settings.json options.

**Comment by iamfraggle** [comment]
Thanks!  As the edit control wasn't included the the merge, should I raise a new issue for that?

**Comment by aeschli** [comment]
@iamfraggle Sorry for that. yes, please file a separate issue.
