### ISSUE TITLE
I think the word follow typedef should be pasred to a type in c++ file,but vsc didn't do this

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vscode#87708]
I think the word follow typedef should be pasred to a type,but vsc didn't do this
![image](https://user-images.githubusercontent.com/5162926/71466738-73206980-27fb-11ea-8b2c-cf747f20f4cf.png)

**Comment by alexr00** [comment]
We get our C++ grammar from https://github.com/jeff-hykin/cpp-textmate-grammar/ 
The folks over there know a lot about how C++ tokens should be categorized so I recommend posting in issue in that repo and seeing if they agree with you. If they do, then the change will make it into VS Code eventually.
