### ISSUE TITLE
Cannot fullscreen when opening with `code .` from terminal

### ISSUE THREAD

**Issue by CodeCorrupt** [Microsoft/vscode#8771]
- VSCode Version: 1.2.1 (1.2.1)
- OS Version: OSX 10.11.5 (15F34)

Steps to Reproduce:

1. Navigate to the desired folder of your project.
2. execute `code .`
3. Press the green "fullscreen" button, OR `cmd+ctrl+F`
4. Application does not resize.

**Comment by joaomoreno** [comment]
Can you provide a recording of this behavior? I can't reproduce it.

**Comment by CodeCorrupt** [comment]
![error](https://cloud.githubusercontent.com/assets/8364947/16642713/89096664-43db-11e6-9c35-b4eddb7e1e14.gif)

In testing I've realized that the issue only arises when code is called from within tmux.

**Comment by joaomoreno** [comment]
Can you reproduce it with [plain Electron](https://github.com/electron/electron/releases/download/v1.2.6/electron-v1.2.6-darwin-x64.zip)?

**Comment by ahmetalpbalkan** [comment]
I can repro this very easily on OS X. as @CodeCorrupt said, type `tmux` then `code .` and full-screen does not work as in the screen recording above.

**Comment by ahmetalpbalkan** [comment]
here's the diff of env variables (`ps eww <pid>`) of the vscode main process got when launched directly (`<`) and from tmux (`>`):

```
3c3
< ELECTRON_NO_ATTACH_CONSOLE
---
> ELECTRON_NO_ATTACH_CONSOLE=1
18c18
< SHLVL=2
---
> SHLVL=3
21c21
< TERM=xterm-256color
---
> TERM=screen-256color
25a26,27
> TMUX=/private/tmp/tmux-501/default,31436,0
> TMUX_PANE=%0
```

TERM might be causing this issue but when I exported it manually, it still didn't work...

**Comment by joaomoreno** [comment]
@ahmetalpbalkan I did not understand if you could reproduce this with **Electron**.

**Comment by jchannon** [comment]
Could we not have a `code -f .` option to open the application from terminal that opens it fullscreen straight away?

**Comment by joaomoreno** [comment]
@jchannon That's another feature. Feel free to file a new issue for it.

@ahmetalpbalkan Can you reproduce this with [plain Electron](https://github.com/electron/electron/releases/download/v1.2.6/electron-v1.2.6-darwin-x64.zip)?

**Comment by CodeCorrupt** [comment]
This appears to have been fixed. I'm no longer experiencing the issue. (Not sure which update fixed it though)

**Comment by joaomoreno** [comment]
Thanks.
