### ISSUE TITLE
Code consuming too much CPU, draining battery on Surface Book

### ISSUE THREAD

**Issue by fpintos** [microsoft/vscode#87715]
Issue Type: <b>Performance Issue</b>

VS Code seems to be consuming a significant amount of CPU in my system even when it is supposedly idle, when I have a large typescript project open.

This is consistently draining my Surface Book battery and it is reported as a culprit in
[energy-report.zip](https://github.com/microsoft/vscode/files/4002260/energy-report.zip)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19536

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.76GB free)|
|Process Argv|--folder-uri file:///d%3A/projectName|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    55	 17024	code main
    1	   192	 10176	   gpu-process
    1	    78	 10384	   window (Issue Reporter)
    0	     8	 11488	   electron-crash-reporter
   39	    50	 12532	   shared-process
    0	   221	 13424	   window (TimeStreamAssetView.tsx - client-web - Visual Studio Code)
    0	    15	 11944	     watcherService 
    0	     6	 16564	       console-window-host (Windows internal process)
    0	   161	 17728	     extensionHost
    0	    18	  7436	       electron_node eslintServer.js 
    0	    69	  9708	       electron_node server.js 
    0	    18	 16164	       "C:\Users\fpintos\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\fpintos\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=17728
    0	    27	 18240	       electron_node tslintServer.js 
    0	    24	 21956	       electron_node tsserver.js 
    8	  1659	 22692	       electron_node tsserver.js 
    0	    13	 23468	         electron_node typingsInstaller.js typesMap.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (fileName.tsx - client-web - Visual Studio Code)
|    Folder (client-web): more than 34419 files
|      File types: json(7964) ts(2341) map(1948) js(1637) png(441) svg(210)
|                  tsbuildinfo(199) bcmap(168) tsx(148) jpg(108)
|      Conf files: tsconfig.json(551) package.json(130) gulp.js(2)
|                  tslint.json(1) launch.json(1) tasks.json(1)
|                  settings.json(1)
|      Launch Configs: chrome(8) node(5);
```

</details>
<details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-icalendar|af4|1.0.1
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer|Coe|1.0.61
jison-syntax-highlight|cru|0.1.1
vscode-eslint|dba|2.0.11
vscode-instant-markdown|dba|1.4.4
xml|Dot|2.5.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
json-tools|eri|1.0.2
prettier-vscode|esb|3.18.0
url-encode|fle|1.1.0
code-sync|gol|2.6.1
gc-excelviewer|Gra|2.1.32
vstsservicestatus|jep|1.3.0
svg|joc|1.0.6
docomment|k--|0.1.8
favorites|kdc|2.4.5
eml|lei|0.3.2
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.6
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.7
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.1424
debugger-for-chrome|msj|4.12.3
ejs-language-support|Qas|0.0.1
project-snippets|reb|0.5.0
code-spell-checker|str|1.7.20
vscode-icons|vsc|9.6.0
markdown-all-in-one|yzh|2.6.1
t4-support|zbe|0.4.3

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
