### ISSUE TITLE
supportsVariablePaging returning true, yet variables are not paged

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#87718]
- VSCode Version: 1.40.2
- OS Version: Windows 10

I'm currently implementing support for paged requests on the Python debugger for VSCode, but it doesn't seem like VSCode is trying to use paged requests.

What I'm doing is:

1. Check that the client is passing `supportsVariablePaging=true` (which VSCode is doing).

 2. Provide a scope response saying that there are 5000 named variables and that's expensive to compute.

i.e.:

```
{
  "request_seq": 16, 
  "body": {"scopes": [{
    "variablesReference": 63623728, 
    "namedVariables": 5000, 
    "name": "Locals", 
    "expensive": true, "source": {}}
  ]}, 
  "success": true, "seq": -1, "command": "scopes", "type": "response"
}
```

3. At this point I expected that the variables requests come with start and count, but this doesn't seem to be the case... the command that I'm receiving is still asking for all the variables in the scope (as can be seen below).

```
{
    "command": "variables",
    "arguments": {
        "variablesReference": 63623728,
        "format": {}
    },
    "seq": 20,
    "type": "request"
}
```

From the spec I expected that to be everything needed, but it's possible that I'm missing something... Does something else need to be done for VSCode to use a filter with `filter="named"`, `start` and `count` parameters in the variables request or is this a bug (or feature request)?

**Comment by weinand** [comment]
It could be possible that VSCode only pages "indexed" variables but not "named" variables. Reason being: indexed variables (e.g. large arrays) occur more frequently than large dictionairies.

**Comment by fabioz** [comment]
I guess this depends on the language -- I think that on Python large dictionaries seem to be pretty common ;)

**Comment by isidorn** [comment]
@weinand is correct, this is currently only implemented for "indexed" variables but not for "named" variables.
We are open for a PR that changes this, here's the code pointer 
https://github.com/Microsoft/vscode/blob/06bb703b9eb6209aa6e42a6a5b5896ff6c70dc2d/src/vs/workbench/contrib/debug/common/debugModel.ts#L76
I believe the change shuold not be that complex, we should just do for named variables what we are already doing for indexed variables.
