### ISSUE TITLE
visual code crashes again again. i found vs code ash file in %temp% every time 

### ISSUE THREAD

**Issue by dkroy8790** [microsoft/vscode#87713]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by kieferrm** [comment]
@dkroy8790 you forgot to paste the info from the bug report.

**Comment by dkroy8790** [comment]
Sir please tell me how to paste information from bug report . I don't know
about coding and computer much but i want to learn all this things
Please  help me sir

**Comment by kieferrm** [comment]
You successfully created an issue in the Issue Reporter. You pressed `Preview Issue`. All you missed is: <kbd>Cmd+V</kbd> (if on macOS) or <kbd>Ctrl+V</kbd> (if on Windows/Linux).

**Comment by dkroy8790** [comment]
Thanks sir i got it

**Comment by kieferrm** [comment]
@dkroy8790 we still need more information from you about this issue.

**Comment by dkroy8790** [comment]
Sir now IDE work smoothly  their is no issue now
