### ISSUE TITLE
The react file has no smart code prompt

### ISSUE THREAD

**Issue by VitaminCtea** [microsoft/vscode#87712]
- VSCode Version: 1.41.1
- OS Version: win10 1903

Steps to Reproduce:

1. The react file has no smart code prompt
2. Normal js files have smart prompts

Does this issue occur when all extensions are disabled?: Yes/No
Not sure

**Comment by kieferrm** [comment]
@asas55858995 can you please provide more information? Best would be a small example with step by step instructions. Thank you!

**Comment by asas55858995** [comment]
@kieferrm 
- VSCode Version: 1.41.1
- OS Version: win10 1903

In the react file, [For example:](https://github.com/asas55858995/react-practice/blob/master/public/animate2.gif)
1. if I type in a field called func, the function panel should be prompted.
2. The same is true for other keywords! Such as input con field, The prompt panel should show the console!

Normal JS file normal.
No tips now, I don't know what happened.
Long time ago used to install all these vscode plugins, But that didn't happen problem.
It's a pain to write code these days. It's like writing code in a journal, I wish I could get help.
Thank you!

Here is a list of plug-ins installed by vscode:
  1. auto-close-tag v0.5.6
  2. auto-rename-tag v0.1.1
  3. better-comments v2.0.5
  4.  bracket-pair-colorizer v1.0.61
  5. change-case v1.0.0
  6. code-beautifier v2.3.3
  7. code-runner v0.9.15
  8. code-settings-sync v3.4.3
  9. code-spell-checker v1.7.20
  10. color-highlight v2.3.0
  11. color-info v0.5.1
  12. debugger-for-chrome v4.12.3
  13. docthis v0.7.1
  14. EditorConfig v0.14.4
  15. es7-react-js-snippets v2.5.0
  16. guides v0.9.3
  17. highlight-matching-tag v0.9.6
  18. html-css-class-completion v1.19.0
  19. html-snippets v0.2.1
  20. htmltagwrap v0.0.7
  21. indent-rainbow v7.4.0
  22. JavaScriptSnippets v1.7.2
  23. markdown-all-in-one v2.6.1
  24. markdown-preview-enhanced v0.5.0
  25. npm-intellisense v1.3.0
  26. open-in-browser v2.0.0
  27. output-colorizer v0.1.2
  28. path-intellisense v1.4.2
  29. polacode v0.3.4
  30. prettier-vscode v3.18.0
  31. project-manager v10.9.1
  32. react-redux-react-router-snippets v0.4.29
  33. regex v0.2.0
  34. sass-indented v1.7.1
  35. sass-lint v1.0.6
  36. simple-react-snippets v1.2.2
  37. sublime-babel-vscode v0.2.10
  38. todo-tree v0.0.162
  39. typescript-hero v3.0.0
  40. vetur v0.22.6
  41. vsc-material-theme v30.0.0
  42. vscode-css-peek v3.0.2
  43. vscode-eslint v2.0.11
  44. vscode-fileheader v0.0.2
  45. vscode-filesize v2.1.3
  46. vscode-gutter-preview v0.24.2
  47. vscode-html-css v0.2.3
  48. vscode-icons v9.6.0
  49. vscode-import-cost v2.12.0
  50. vscode-language-pack-zh-hans v1.41.2
  51. vscode-markdownlint v0.33.0
  52. vscode-npm-script v0.3.10
  53. vscode-todo-highlight v1.0.4
  54. vscode-typescript-tslint-plugin v1.2.3
  55. vscodeintellicode v1.2.2
  56. vue-snippets v0.1.11

**Comment by jabczyk** [comment]
Do You have `jsconfig.json` or `tsconfig.json` in the root directory?

**Comment by asas55858995** [comment]
@jabczyk None! The project was generated by create-reaction-app scaffolding.

**Comment by asas55858995** [comment]
@jabczyk  None! The project was generated by create-react-app scaffolding.

**Comment by jabczyk** [comment]
@asas55858995 Looks like IntelliSense needs one. Create `jsconfig.json` (or `tsconfig.json` for TypeScript) and fill it with something like:
```js
{
  "compilerOptions": {
    "target": "es6"
  }
}
```

**Comment by asas55858995** [comment]
@jabczyk A jsconfig.js file was added to the root directory in your way, But the react file still doesn't have a smart prompt. 
In the react file, the language pattern is Javascript react (Babel).
Is there any missing configuration? Previously, react files had prompts.

**Comment by asas55858995** [comment]
I need help, Thank you!

**Comment by husseyexplores** [comment]
There are multiple issues like this. [Like this](https://github.com/microsoft/vscode/issues/87787), and [this](https://github.com/microsoft/vscode/issues/87728).
I've downgraded my vscode to version 1.40 and intellisense is working again. You can try to do the same until this is fixed.
(I was also working with React, vscode version 1.41.1, Windows 10 64-bit)

**Comment by asas55858995** [comment]
@husseyexplores I don't know how to go back to the version, How do you do that? there was a problem with the synchronous extension before, it was reinstalled later! Hope the officially can fix it soon!
In addition, Can the authorities see my question?

**Comment by husseyexplores** [comment]
Go to [this link](https://code.visualstudio.com/updates/v1_40)
And click here (For windows)
![](https://i.postimg.cc/g095t18P/Capture.png)

There are options for Mac and Linux too.

**Comment by asas55858995** [comment]
@husseyexplores Ok, Thank you very much!

**Comment by asas55858995** [comment]
@husseyexplores I went back to version 1.40 and intellisense is working again! Thank you for your help! 
We hope to fix this problem in the latest update plan, Otherwise I dare not update the new version!

**Comment by mjbvz** [comment]
@asas55858995 Is your code stored on a different drive letter drive (not the `c:` drive?)

Also, using VS code 1.41 please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that fix the problem?

**Comment by asas55858995** [comment]
@mjbvz I have two disks, C and D. The code is in the D disk, while vscode is in the default installation path. 
I am currently using react and only found this problem in writing react files. For others, like vue or angular, I don't know. Normally in js or ts files, there is no such problem.
Yesterday, I went back to version 1.40. Version 1.40 makes intellisense work without installing additional help plug-ins. 
The latest version takes up most of my time and I don't want to do it anymore. 
Wait until the official fix is complete, then update.
Thank you for your kind help!

**Comment by asas55858995** [comment]
@mjbvz I have two disks, C and D. The code is in the D disk, while vscode is in the default installation path. 
At presen, I used version 1.40. Dare not update!

**Comment by asas55858995** [comment]
In the issues section, many people have encountered this problem

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

As a workaround, upgrad your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
