### ISSUE TITLE
Auto Scroll java file.

### ISSUE THREAD

**Issue by shashank1vy** [microsoft/vscode#87719]
Issue Type: <b>Bug</b>

as I keep on typing the JAVA file, it auto scroll up on every line typed or on press of return key. Then I have to close the file and again open it, to bring it to normal.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-standardjs|che|1.2.3
vscode-postgres|cko|1.1.11
bracket-pair-colorizer-2|Coe|0.0.29
vscode-just-start-server|dea|0.2.0
vscode-html-css|ecm|0.2.3
code-runner|for|0.9.15
intellij-idea-keybindings|k--|0.2.37
mssql|ms-|1.8.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
debugger-for-chrome|msj|4.12.3
elmmet|nec|1.0.1
java|red|0.55.1
LiveServer|rit|5.6.1
vscode-checkstyle|she|1.3.2
open-in-browser|tec|2.0.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by kieferrm** [comment]
@shashank1vy do you see the same behavior with all extensions disabled? You can start from the command line with `code --disable-extensions`. Also, do you see this behavior with any other file type or only `.java` files?
