### ISSUE TITLE
node js intellisense dosn't work 

### ISSUE THREAD

**Issue by fiqnh29** [microsoft/vscode#87723]
Issue Type: <b>Bug</b>

after updating to new version of vs code, november update, version 1.41.
my intellisense doesn't work correctly.  I tried to uninstall and install the older version, its work fine, but after update my intellisense dosn't work again.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (2.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kieferrm** [comment]
@fiqnh29 is that limited to any particular code? Do you use JS or TS?

**Comment by chen-kosile** [comment]
> @fiqnh29 is that limited to any particular code? Do you use JS or TS?

just js

**Comment by mjbvz** [comment]
Please share steps to reproduce the issue (such as example code)

Also, is your code stored on a non-c-letter drive?
