### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by itzbidyut** [microsoft/vscode#87728]
I'm using vscode editor from the last past two years. now I am getting a problem with vscode Intellisense. I'm working on javascript language. few minutes of working on vscode after that Intellisense suddenly stops working .after that i restart vscode. it will work again . but again after few minutes vscode Intellisense not working .,.///

**Comment by MrCreeper1008** [comment]
Same problem here with latest macOS and VSCode version `1.41.1`.

**Comment by Barretemer** [comment]
This problem also puzzles me. Even worse, vscode editor can't figure out whst javascript file is!

**Comment by vuongggggg** [comment]
Same.

**Comment by husseyexplores** [comment]
I was also having the same problem (windows 10).
Reverting to [version 1.40.0](https://code.visualstudio.com/updates/v1_40) fixed it for now.
I've also disabled auto-updates from the settings until this is fixed.
