### ISSUE TITLE
Ability to press up to navigate IntelliSense context menu

### ISSUE THREAD

**Issue by chrispaynter** [microsoft/vscode#87722]
One small thing I come across again and again.

When pressing `CMD` + `.`, I can't press the up key to navigate through the list bottom up. Can be a small annoyance in long lists.

For context, I use "Create and initialise field" plenty of times a day (always at bottom of the list), and would be great if I could save my self some down key strokes, or having to grab the mouse.

Again, small annoyance, but frequent enough to be worthwhile asking for.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/1684083/71475544-57ac6300-27e9-11ea-89dd-fd2f2fc3ab2b.png">

**Comment by chrispaynter** [comment]
@kieferrm I've just discoed that a `CMD` + `Down` will actually take me to directly to the bottom of the list. I can live with that.

I'll leave it to you to close or not. To be fair, the up button behaviour I requested is common on MacOS (try right click in chrome for example), so may be worth implementing if it's not a hassle.

Thanks.

**Comment by mjbvz** [comment]
Closing this as by-design.

We automatically select the first item in the list. For MacOS native menus, this means that pressing up has no effect (apps such as chrome do not auto select any element which is why you see a difference in behavior)
