### ISSUE TITLE
Go to Definition (F12) in Typescript fails ("Cannot read property 'toString()' of undefined)

### ISSUE THREAD

**Issue by samdoeswork** [microsoft/vscode#87727]
VSCode: 14.1.1
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
OS: Windows 10

Hi,
When I control+click / F12 / click "Go to Definition" from the context menu, I see a notification error saying "Cannot read property toString() of undefined".

In package.json I specifically set typescript to 3.7.3 to match VSCode's version and compiled - this did not resolve the issue.

It would be great to get this working again.

**Comment by samdoeswork** [comment]
Update: I've been trying to troubleshoot this myself for a few hours with no luck.
I have tried disabling as many extensions as I was able to. Here is the stacktrace in the VSCode developer tools:


  | onDidNotificationChange | @ | notificationsAlerts.ts:38
-- | -- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | fire | @ | event.ts:581
  | addNotification | @ | notifications.ts:171
  | error | @ | notificationService.ts:57
  | (anonymous) | @ | goToCommands.ts:112
  | processTicksAndRejections | @ | internal/process/task_queues.js:89
  | Promise.then (async) |   |  
  | run | @ | goToCommands.ts:77
  | (anonymous) | @ | goToDefinitionAtPosition.ts:338
  | invokeFunction | @ | instantiationService.ts:67
  | invokeWithinContext | @ | codeEditorWidget.ts:362
  | gotoDefinition | @ | goToDefinitionAtPosition.ts:338
  | (anonymous) | @ | goToDefinitionAtPosition.ts:59
  | fire | @ | event.ts:581
  | onEditorMouseUp | @ | clickLinkGesture.ts:175
  | (anonymous) | @ | clickLinkGesture.ts:138
  | fire | @ | event.ts:581
  | n.onMouseUp | @ | codeEditorWidget.ts:1475
  | emitMouseUp | @ | viewOutgoingEvents.ts:94
  | emitMouseUp | @ | viewController.ts:306
  | _onMouseUp | @ | mouseHandler.ts:204
  | (anonymous) | @ | mouseHandler.ts:104
  | (anonymous) | @ | editorDom.ts:110

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
