### ISSUE TITLE
Feature request: Classify User and Workspace settings

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8772]
Copied from https://github.com/Microsoft/vscode-docs/issues/455

 "window.restoreFullscreen": true  works great in User Settings, but doesn't have any affect in Workspace Settings.

Repro steps:
1.Make sure  "window.restoreFullscreen": true  is set in Workspace Settings and not in User Settings.
2.Run "Reload Window" to make sure the new setting is active.
3.Go full screen.
4.Close and reopen the app.

Actual: Window opens not in full screen.
Expected: Window opens in full screen.

I'm on:
•Windows 10
•VSCode 1.3.0-insiders

**Comment by bpasero** [comment]
We should really work on differentiating between user and workspace settings. Imho this does not make sense as a workspace setting.

**Comment by sandy081** [comment]
This is fixed.
