### ISSUE TITLE
no  info shown for certain events in IntelliSense 

### ISSUE THREAD

**Issue by s-e1** [microsoft/vscode#87720]
Issue Type: <b>Bug</b>

IntelliSense doesn't show any details about the events onformchange, onforminput and onmousewheel, it just shows a blank line that's half the height of a normal line. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem

/needsMoreInfo

**Comment by s-e1** [comment]
Usually when typing events, intellisense recognizes them as such and shows a popup box with the info for the event. When writing these events a popup box appears that doesn't contain any info, and the box height is half a line.
![Screenshot (3)](https://user-images.githubusercontent.com/49290335/71841937-3ab93f00-30c9-11ea-99d9-70fc6b1973e0.png)

**Comment by octref** [comment]
I cannot reproduce this on macOS. @s-e1 if you try `onchange` (which has a rather long description) does it reproduce?

![image](https://user-images.githubusercontent.com/4033249/71965626-55420400-3200-11ea-8c96-2517842456fd.png)

**Comment by s-e1** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/49290335/72001877-feafe680-324e-11ea-854d-a72ba178bb9d.png)

**Comment by octref** [comment]
@jrieken Have you ever seen this happening, and how may I find a repro?

**Comment by jrieken** [comment]
Unsure... Could this be timing dependent? E.g that we somehow resolve details, assume they are there but then it failed?
