### ISSUE TITLE
Typescript: Intellisense fails on class heritage with generic type

### ISSUE THREAD

**Issue by Chnapy** [microsoft/vscode#87729]
- VSCode Version: 1.41.1
- OS Version: Debian 9

Does this issue occur when all extensions are disabled?: Yes

---

I create a class, which extends another class with generic type. This generic type, Intellisense does not propose me any value whereas this type is a union of specific strings.

![image](https://user-images.githubusercontent.com/7474483/71479060-2afd4900-27f3-11ea-8674-36e0668e78c1.png)

![image](https://user-images.githubusercontent.com/7474483/71479107-6b5cc700-27f3-11ea-9a35-fb815e1c54fc.png)

You can reproduce the issue with this code:

```typescript
type S = 'a' | 'b' | 'c';

abstract class C<T extends S> {}

class ImplC extends C<''> {} // try autocomplete in the ''
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
