### ISSUE TITLE
Cannot exclude whole folders from being validated by "php.validate"

### ISSUE THREAD

**Issue by paulalbertdev** [microsoft/vscode#87725]
- VSCode Version: 1.41.1
- OS Version: ubuntu 19.10

Steps to Reproduce:

1. Be sure that `php.validate.enable` is set to "true"
2. If you make syntaxical errors in a PHP file and you save it, you'll see that, even if you close VS code and re-open it, files will stiil be parsed @ startup, and I've got a lot of those files.

Since I use the "local history" extension, that creates a copy of a files each time it's modified, it takes a lot of CPU/time and I cannot ignore the .history folder. (tried unsuccessfully with "files.exclude")

**Comment by roblourens** [comment]
> files will stiil be parsed @ startup

Can you explain the exact problem a little more? And are you sure that the problem is not caused by an extension? You can try starting with the `--disable-extensions` flag

**Comment by paulalbertdev** [comment]
My bad you were right, seems to be a problem of the php-intellisense extension, unsing php-language-server : https://github.com/felixfbecker/php-language-server/issues/159
There seems to be no solution yet...
Sorry for the disturbance, and thanks for your advice !
