### ISSUE TITLE
Call hierarchy 'no result' c#

### ISSUE THREAD

**Issue by dps999** [microsoft/vscode#87733]
Steps to Reproduce:

1. Select a method on c#
2. Use 'Show Call Hierarchy' command
3. You will get No result window 

Maybe I should use an extension? Is there any?

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@dps999, I'm guessing you already use the C# extension. Please file this issue as a feature-request against the C# [here](https://github.com/OmniSharp/omnisharp-vscode/issues). Thank you.
