### ISSUE TITLE
Toggle line comment: comments twice when used with two cursors at same line 

### ISSUE THREAD

**Issue by VeselovAlex** [microsoft/vscode#87730]
Issue Type: <b>Bug</b>

1. Place 2 cursors at the same line of code
2. Execute `Toggle Line Comment` command .(Cmd+/ for me)
3. Now line is commented twice.

```js
let x = 12;
```
Expected: 
```js
// let x = 12;
```
Actual: 
```js
// // let x = 12;
```

Also, when toggling line comment off, cursors at same line are removed, except one. Is it an expected behavior?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.2.0

Extensions: none

**Comment by Vlad-Shcherbina** [comment]
This is not as uncommon as it may appear, because the cursor is automatically doubled inside HTML tag names.

### Steps to reproduce
1. Create an HTML file with the following contet:
    ```html
    <body></body>
    ```
2. Place the cursor right after the first `b`:
    ```html
    <b|ody></body>
    ```
3. Press `Ctrl-/`.

### Expected result
```html
<!-- <body></body> -->
```

### Actual result
```html
<!-- <!-- <body></body> --> -->
```
