### ISSUE TITLE
[html] Mirror cursor devolves into multi-cursor when undoing (ctrl-z)

### ISSUE THREAD

**Issue by rlyczynski** [microsoft/vscode#87732]
Issue Type: <b>Bug</b>

1. Open html document and add a tag
```<div></div>```
2. Place cursor at the end of the open tag and add a space
```<div ></div>```
3. Undo (ctrl-z) once adds a space to close tag (unexpected, but probably an implementation detail of the space special case 🤷‍♂)
```<div ></div >```
4. Undo (ctrl-z) twice removes the space from the end of both tags
```<div></div>```
5. Add a space and start typing
```<div class="aClass"></div class="aClass">```

Expected: 
```<div class="aClass"></div>```

Basically, after the second undo, you're left with a normal multi-cursor. Even if you move the cursor around the document and keep typing the multi-cursor follows.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.3
xml|Dot|2.5.0
json-tools|eri|1.0.2
terraform|mau|1.4.0
vscode-json5|mrm|1.0.0
remote-wsl|ms-|0.41.6
csharp|ms-|1.21.9
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.12.3
vscode-icons|vsc|9.6.0
better-align|wwm|1.1.6

</details>

**Comment by octref** [comment]
Good catch, although I'm wondering why you would use Cmd-Z instead of backspace in this case.

**Comment by rlyczynski** [comment]
That's a fair question. I guess its just a habit I've built over time. I like to think that I undo my typos instead of deleting so that unwanted changes aren't left on the "undo stack", but honestly it's probably just a weird quirk that I do.

In fairness this is probably pretty small edge case but something I noticed and the resulting functionality seemed weird so I reported it.

**Comment by octref** [comment]
This will be fixable if we do #88424.

**Comment by octref** [comment]
In tomorrow's insiders `html.mirrorCursorOnMatchingTag` is replaced with `editor.renameOnType`. The new implementation fixes this issue. You can find more details here: https://github.com/microsoft/vscode/issues/88424#issuecomment-600840619
