### ISSUE TITLE
Unable to get any task to work

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#87739]
I need some help, I'm struggling trying to get any task to work within VSCode.  One task which I'm trying to create is a task which runs `mlink.exe` and pass it some arguments; this is what that task looks like within the `tasks.json` file;
```
"tasks": [
        {
            "label": "SymbolicLink",
            "type": "shell",
            "command":"echo Hello",
            "args": [], 
            "group":"test",
        },
```
As you see, it is not setup to run `mklink.exe` as I'm simply trying to get anything to work; but it this simply thing as echoing `Hello` does not work ? 

Formally I had for the *command* property; `${env:Path}` which was to load the `mklink.exe` from the system environment variable where windows is located as I can within any windows shell, that didn't work either; I also tried the absolute path to the executable file, that didn't work either. 

For the `args[]` property, I passed in some of `mklinks.exe` flags, well those didn't work because I couldn't even get mklink to execute ?

**Comment by g-konst** [comment]
Here is a default task template with args:
```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo",
            "args": ["$USER"],
            "group": "test"
        }
    ]
}
```
Output:
```
> Executing task in folder test_project: echo $USER <

konstantin
```
In your case, you should replace `echo` with path to your `exe` file or use env variable, for details read the [documentation](https://go.microsoft.com/fwlink/?LinkId=733558):
```js
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "mklink",
            "type": "shell",
            "command": "$mklinkENV", // or /path/to/mklink.exe
            "args": ["/?"],
            "group": "test"
        }
    ]
}
```

**Comment by SheepDomination** [comment]
@g-konst 
This is the result I get from the first task, nothing like the result you got ?

```
Executing task in folder CodeProjects: echo $USER 

The terminal shell CWD "<Path of workspace>" does not exist

Terminal will be reused by tasks, press any key to close it.
```

**Comment by SheepDomination** [comment]
What is `$mklinkENV` ?

**Comment by g-konst** [comment]
@SheepDomination 
`mklinkEnv` it's just a name of path to `mklink`.
For windows this should be `${env:VAR_NAME}` or `%VAR_NAME%`, you can also set it manually
```bash
# Unix
export VAR_NAME=value
```
```cmd
# Windows
SET VAR_NAME=value
```
