### ISSUE TITLE
editor save error

### ISSUE THREAD

**Issue by fxk2006** [microsoft/vscode#87742]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.17134

I use it for go-lang devlep

Steps to Reproduce:

1. open the same file in different vscode editors 
2. edit it in one vscode editor and save it
3. then it will automatically delete some letters at some lines.

Does this issue occur when all extensions are disabled?: No

**Comment by kieferrm** [comment]
@fxk2006 please file this issue against the Go extension [here](https://github.com/Microsoft/vscode-go/issues). Thank you!
