### ISSUE TITLE
Discard submodule changes does not work

### ISSUE THREAD

**Issue by mkitby** [microsoft/vscode#87744]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. in the submodule update the commit of current branch
2. change is list in main repo in vscode
3. click "Discard Changes" button on the changed item, not work

![image](https://user-images.githubusercontent.com/15389150/71495422-9ba27500-2888-11ea-8bc2-4a8ff9e2aae0.png)

**Comment by joaomoreno** [comment]
Can you reproduce in other repositories?

> in the submodule update the commit of current branch

How do you do this?
