### ISSUE TITLE
Cannot replace text in Search text

### ISSUE THREAD

**Issue by thanhpham288** [microsoft/vscode#87748]
Issue Type: <b>Bug</b>

Cannot replace text in Search text

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
vscode-eslint|dba|2.0.11
csharp|ms-|1.21.9
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
vscode-icons|vsc|9.6.0

</details>

**Comment by kieferrm** [comment]
@thanhpham288 can you please provide more details. Where do you expect replace to work? Thanks!

**Comment by jabczyk** [comment]
Maybe You forgot to click 'Toggle Replace Mode'?
![image](https://user-images.githubusercontent.com/13063089/71534367-ae579100-28fe-11ea-9866-4da77540c015.png)

**Comment by thanhpham288** [comment]
I clicked this toggle and show input box for replace . But replace button
is disabled, i want it enable.

**Comment by thanhpham288** [comment]
I want to highlight button that show in image of attach file to enable.

**Comment by kieferrm** [comment]
@thanhpham288 still need more information. Can you please add an image showing what inputs you have and which button you think should be enabled but is not. Thank you!

**Comment by thanhpham288** [comment]
Are you see button that I highlighted? I want it enable after type string
to replace
