### ISSUE TITLE
react项目自动提示失效

### ISSUE THREAD

**Issue by zhuxianguo** [microsoft/vscode#87743]
Issue Type: <b>Bug</b>

第一次打开有效，修改属性后，自动提示失效

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by zhuxianguo** [comment]
![image](https://user-images.githubusercontent.com/9689585/71495166-6e08fc00-2887-11ea-96ee-95b7c035aecf.png)
会一直卡在loading状态

**Comment by byyxx128** [comment]
English Please!
Somebody already reported before but his issue was closed due to non-English description.
#87676
So... English! MUST ENGLISH!

**Comment by byyxx128** [comment]
English Please!
Somebody already reported before but his issue was closed due to non-English description.
#87676
So... English! MUST IN ENGLISH!
@yx201103707 @github-yuminhui

**Comment by chen-kosile** [comment]
我也有这个问题，应该是1.4.1版本有问题，改成1.4.0就好了
