### ISSUE TITLE
Horazontal Scroll on mx master mouse not working

### ISSUE THREAD

**Issue by python151** [microsoft/vscode#87740]
Issue Type: <b>Bug</b>

it seams to be ignoring the horazontal scroll wheel? I am not quite sure

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.61GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/python151/pc/pc --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|Memory (System)|31.95GB (18.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|Memory (System)|31.95GB (18.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|Memory (System)|31.95GB (18.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|Memory (System)|31.95GB (18.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|Memory (System)|31.95GB (18.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|Memory (System)|31.95GB (18.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3850)|
|Memory (System)|31.95GB (18.61GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
qiksit-snippets|Aka|0.0.8
flask-snippets|cst|0.1.1
CppSnippets|har|0.0.14
remote-wsl|ms-|0.41.6
jinja2-snippet-kit|Wya|1.2.0

</details>

**Comment by kamenminkov** [comment]
I believe it's a Chromium bug as it's also seen in Chromium-based browsers (Chrome, Vivaldi, Opera).

**Comment by alexdima** [comment]
@python151 Does this reproduce for you when opening http://vscode-web-test-playground.azurewebsites.net/ in Chrome?

**Comment by alexdima** [comment]
Possibly related -- https://github.com/microsoft/vscode/issues/84136
