### ISSUE TITLE
Debugger: error text from configurationDone is not shown to the user

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode#87745]
Issue Type: <b>Bug</b>

### Issue
If a debug adapter fails `configurationDone`, then debugging stops. But VS Code will no longer show the user the error message that the debug adapter sent. So unless the debug adapter prints this error in some other way, users will not understand why debugging failed.

Partial protocol trace (full trace is at the end of this report):
```
-> (C) {"command":"configurationDone","type":"request","seq":4}
<- (R) {"seq":8,"type":"response","request_seq":4,"success":false,"command":"configurationDone","message":"Only 64-bit processes can be debugged."}
```

### Steps to reproduce
Here is a way to reproduce this problem with the C# extension. One could also reproduce this problem with a different debugger by having it fail `configurationDone`.

**Setup**
* This method of reproducing the problem will only work on Windows, so get a Windows machine.
* Follow steps in https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install to install the .NET Core SDK
* Install the C# extension

**Steps**
1. Create a new .NET Core console app: `dotnet new console -o dncTest32`
2. Load this folder in VS Code
3. Wait for the C# extension to ask if you want to generate assets to build and debug, when prompted, have the C# extension do this.
4. Edit tasks.json, to add the following to `arg` to the build task: `"/property:Platform=x86",` after `"/property:GenerateFullPaths=true",`
5. Edit launch.json, to update `program` to: `"program": "${workspaceFolder}/bin/x86/Debug/netcoreapp3.1/dncTest32.exe",`
6. F5

#### Result:
Debugging stops with no error shown

#### Expected:
Debugging stops and an error is shown to the user

#### Full trace of DAP mesages
```
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"C:\\proj\\clinew/bin/x86/Debug/netcoreapp3.1/clinew.exe","args":[],"cwd":"C:\\proj\\clinew","console":"internalConsole","stopAtEntry":false,"logging":{"engineLogging":false},"internalConsoleOptions":"openOnSessionStart","__sessionId":"4e13db4e-37ea-4da9-a190-11ad25055fc8"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":3}
<- (R) {"seq":6,"type":"response","request_seq":3,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":4}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/LaunchFailed","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.2.10703.1 commit:d18411016e7da314dd58c44a4828778b19665cc3","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-2147220965}}}
<- (R) {"seq":8,"type":"response","request_seq":4,"success":false,"command":"configurationDone","message":"Only 64-bit processes can be debugged."}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":5}
-> (C) {"command":"threads","type":"request","seq":6}
<- (E) {"seq":9,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.2.10703.1 commit:d18411016e7da314dd58c44a4828778b19665cc3","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}
<- (R) {"seq":10,"type":"response","request_seq":5,"success":true,"command":"disconnect"}
```

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.41.2
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
debugger-for-chrome|msj|4.12.3

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. 
The configurationDone error response was not being properly handled, I have changed that with this commit and this issue should now be fixed. You can try out the vscode insiders after the vaction break to verify this issue got fixed. Thansk

**Comment by gregg-miskelly** [comment]
Thanks for fixing this so quickly! Will do.

**Comment by weinand** [comment]
If an error response 'foo bar' is returned from the configurationDoneRequest, VS Code shows the following error notification:

<img width="567" alt="2020-01-30_15-16-32" src="https://user-images.githubusercontent.com/1898161/73457242-a793c200-4373-11ea-9435-600988ecc422.png">

I suggest to improve the error message to something like "Debug session terminated because of error 'foo bar'".
