### ISSUE TITLE
syntax highlight for python equality operator and others

### ISSUE THREAD

**Issue by zhyiyu** [microsoft/vscode#87746]
I searched the all the related open and recent closed issues, I did not see similar ones so I decided to open a new issue.

I would like to request the feature of highlighting operators like

```python
==
!=
>=
+=
-=
*=
**
...
```

Currently those are not highlighted

<img width="400" alt="highlight" src="https://user-images.githubusercontent.com/26550166/71495861-09658700-281e-11ea-932e-ba0aa56f2438.png">

Thanks!

**Comment by g-konst** [comment]
Maybe you should try a different theme? [Monokai Pro](https://marketplace.visualstudio.com/items?itemName=monokai.theme-monokai-pro-vscode)

![image](https://user-images.githubusercontent.com/27275720/71516706-1c766680-28b3-11ea-8bb3-6a50c5081ad8.png)

**Comment by kieferrm** [comment]
Themes can color operators. The grammars tokenize them correctly:

![image](https://user-images.githubusercontent.com/4674940/71528731-305f9f80-2896-11ea-88dc-d0fc886f82b8.png)

**Comment by zhyiyu** [comment]
@kieferrm 

Thanks for your comment, but how did you turn this highlighting on? I can not find such options in my [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension settings.
