### ISSUE TITLE
Code prompt problem

### ISSUE THREAD

**Issue by DBCdouble** [microsoft/vscode#87749]
Issue Type: <b>Bug</b>

Some projects have code prompts, some don't, the Settings are the same.Version 13.1 is starting to have problems

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
React-JS-Snippet|Gaj|3.0.54
ReactCodeSnippets|haz|1.2.1
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
vscode-language-pack-zh-hans|MS-|1.41.2
vetur|oct|0.22.6
js-jsx-snippets|sky|10.0.0
addDocComments|ste|0.0.8
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.6.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@DBCdouble can you please provide step by step instructions that allow us to reproduce the problem. Thank you!

**Comment by Sinclair8023** [comment]
I have the same problem
