### ISSUE TITLE
Jupyter cannot be started from 'Python 3.7.3 64-bit'

### ISSUE THREAD

**Issue by lowercase00** [microsoft/vscode#87751]
- VSCode Version:1.14.1
- OS Version: 10.14.6

While working within the `venv` of a Flask app, I'm getting "_Jupyter kernel cannot be started from 'Python 3.7.3 64-bit ('venv': venv)'. Using closest match Python 3.7.3 64-bit instead. Error starting original kernel: Error: Module 'notebook' not installed._" It's as if VSCode can't find the notebook installed in my `venv`.

However, when I'm with the `vent` activated and type `python -m jupyter notebook --version` in the terminal, I get 6.0.2. Same when I type `python3 -m jupyter notebook --version`. I tried installing `ipykernel` using pip3 and get `requirement already satisfied`, same with pip.

I'm unsure wether this is a VSCode issue or a Jupyter issue, please let me know if I'm in the right place. Thanks.

**Comment by IllusionMH** [comment]
Most likely you should report this issue on https://github.com/microsoft/vscode-python/issues/ because it's related to Jupyter or check StackOverflow if you want to ask questions about configuration.

**Comment by kieferrm** [comment]
@lowercase00 please see previous comment.
