### ISSUE TITLE
Respect the OS setting to always show accelerators on menu bar.

### ISSUE THREAD

**Issue by brjsp** [microsoft/vscode#87756]
Issue Type: <b>Bug</b>

1. Enable the OS setting to always show underlined shortcuts without the ned to press Alt
2. Open VScode
3. Look at menu bar

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3512)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prolog|reb|0.0.4

</details>

**Comment by Zhuinden** [comment]
Makes me wonder why they ever closed https://github.com/microsoft/vscode/issues/74232 as a duplicate if this is actually still an issue.

**Comment by sbatten** [comment]
@brjsp did you close and re-open code after modifying the OS setting. this behavior is implemented but we don't dynamically update after launch.

**Comment by brjsp** [comment]
I have that setting constantly turned on. Had it turned on before installing Code.

**Comment by sbatten** [comment]
with this setting enabled,
![image](https://user-images.githubusercontent.com/6561887/72539564-5690b380-3834-11ea-867d-52517a55a063.png)

 the menubar in VS Code should look like this: 
![image](https://user-images.githubusercontent.com/6561887/72539631-745e1880-3834-11ea-9c98-0079710bc58c.png)

It seems you are saying this is not the case for you?

**Comment by brjsp** [comment]
I am using the native titlebar, not the custom one. This setting indeed works correct with the custom titlebar.

**Comment by sbatten** [comment]
@brjsp thanks for the clarification. I needed to remind myself why this is not working. The native menu is powered by electron and does not support always displaying mnemonics. There is no flag I can send to their api to allow me to show it all the time and it doesn't acknowledge the OS level setting either.

@deepak1556 couldn't find an electron issue for this one, but maybe you know?
