### ISSUE TITLE
High GPU spikes when editing C++ files

### ISSUE THREAD

**Issue by Atom2004** [microsoft/vscode#87750]
Issue Type: <b>Performance Issue</b>

Editing a STM32 project (C language). After some actions(I don't know what action occur it).
![image](https://user-images.githubusercontent.com/22042246/71499357-107eaa80-289b-11ea-9c48-7da080182999.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (14.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   131	 39284	code main
    0	    43	  8512	   window (undefined)
    0	     7	 20872	   utility
    3	   304	 22284	   gpu-process
    0	    94	 25108	   window (stm32f7xx_hal_conf.h - E_Series_TouchApp - Visual Studio Code)
    0	     5	   640	     console-window-host (Windows internal process)
    0	    37	 25508	     extensionHost
    0	    11	 22416	       c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2\bin\Microsoft.VSCode.CPP.Extension.exe
    0	     6	 22608	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 22416 8
    0	    10	 27100	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 22416 7
    0	     5	 42660	         console-window-host (Windows internal process)
    0	     4	 41020	     "C:\Program Files\Git\bin\bash.exe"
    0	     6	  1756	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    10	 42104	     watcherService 
    0	     5	 26192	       console-window-host (Windows internal process)
    0	    88	 27652	   window (● Untitled-1 - Visual Studio Code)
    0	    29	 34020	     extensionHost
    7	    49	 29452	   shared-process
    0	     2	 30448	   electron-crash-reporter
    0	   142	 39568	   window (LineIntersectPolygon.cpp - ComputationalGeometry - Visual Studio Code)
    0	    38	 15236	     extensionHost
    0	     8	  7932	       c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2\bin\Microsoft.VSCode.CPP.Extension.exe
    0	     5	 33184	         console-window-host (Windows internal process)
    0	     9	 43756	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 7932 2
    0	     4	 16368	     "C:\Program Files\Git\bin\bash.exe"
    0	     6	 26396	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	     9	 20732	     watcherService 
    0	     5	 41740	       console-window-host (Windows internal process)
    0	     5	 38188	     console-window-host (Windows internal process)
   10	   414	 42408	   window (touch_mixer.c - G_Series_TouchApp - Visual Studio Code)
    0	    13	 40792	     watcherService 
    0	     5	  4540	       console-window-host (Windows internal process)
    0	   100	 41996	     extensionHost
    0	    96	 13136	       c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2\bin\Microsoft.VSCode.CPP.Extension.exe
    0	     9	 15136	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 13136 11
    0	     9	 23524	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 13136 13
    0	     9	 29756	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 13136 9
    0	    42	 34932	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 13136 3
    0	     5	 38728	         console-window-host (Windows internal process)
    0	    23	 41672	         "c:\Users\atom2\.vscode\extensions\ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 13136 2
    1	    59	 43408	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (touch_mixer.c - G_Series_TouchApp - Visual Studio Code)
|  Window (LineIntersectPolygon.cpp - ComputationalGeometry - Visual Studio Code)
|  Window (stm32f7xx_hal_conf.h - E_Series_TouchApp - Visual Studio Code)
|    Folder (ComputationalGeometry): 300 files
|      File types: h(75) cpp(46) vcproj(34) vcxproj(33) filters(33) sln(2)
|                  htm(1) hpp(1) suo(1) db(1)
|      Conf files: sln(2)
|    Folder (G_Series_TouchApp): 2216 files
|      File types: c(665) h(564) d(185) o(183) crf(170) s(148) icf(110)
|                  txt(17) lib(10) a(5)
|      Conf files: settings.json(1)
|    Folder (E_Series_TouchApp): 2144 files
|      File types: c(653) h(522) d(258) o(258) s(148) icf(110) txt(21) lib(10)
|                  a(5) lst(3)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.33.0
gitlens|eam|10.2.0
matlab|Gim|1.5.2
git-graph|mhu|1.20.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.2

</details>

**Comment by kieferrm** [comment]
@Atom2004 please follow the steps in https://github.com/microsoft/vscode/wiki/Performance-Issues to file a performance issue. Thank you!

**Comment by Atom2004** [comment]
> @Atom2004 please follow the steps in https://github.com/microsoft/vscode/wiki/Performance-Issues to file a performance issue. Thank you!

Thank you. I will try to cache more performance infomation I meet that next time. (I don't know when it happen)

**Comment by connor4312** [comment]
Please follow up on this issue if you are able to get more info 🙂

**Comment by Atom2004** [comment]
> Please follow up on this issue if you are able to get more info 🙂

Hi there, I just recognize that following info:
My CPU and GPU stay low just after I open or reload VSC. And they would be running high after I editing my code for a long time.
Otherwise, CPU and GPU always stay low if the C/C++ extension disabled.

PS: They always stay low if I never edit my code (VSC keep running).

![after reload](https://user-images.githubusercontent.com/22042246/72028922-42423900-32bf-11ea-894e-cba52dfda1c8.png)
VSC just reload, CPU and GPU running low.

![long time running](https://user-images.githubusercontent.com/22042246/72029120-e4fab780-32bf-11ea-85b4-b4088e664351.png)
Editing code for while only with C/C++ extension.

![extensions](https://user-images.githubusercontent.com/22042246/72029166-065ba380-32c0-11ea-8b00-0acf00b48947.png)
about the C/C++ extension

**Comment by bpasero** [comment]
@Atom2004 so to confirm, you see the GPU column in the process viewer increase when you edit C++ files?

**Comment by Atom2004** [comment]
> @Atom2004 so to confirm, you see the GPU column in the process viewer increase when you edit C++ files?

Yes. The GPU always increase when I edit C++ file. And the GPU stay high instead of become low when this issue occur.

**Comment by bpasero** [comment]
@Atom2004 does this really only happen with C/C++ files?

**Comment by Atom2004** [comment]
> @Atom2004 does this really only happen with C/C++ files?

I'm only use C/C++ or matlab file in VSC. And only happen this issue with C/C++ files.

**Comment by bpasero** [comment]
@Atom2004 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Atom2004** [comment]
![image](https://user-images.githubusercontent.com/22042246/72233951-3c24c300-3605-11ea-950a-8990fd4c30da.png)
I tried to disable all extensions by vsc gui command and this issue reproduced.

I would try that run vsc in command line `code --disable-extensions`

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Atom2004** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Yes, I trying that but I can not reproduce the issue so far, even all extension enabled.

**Comment by bpasero** [comment]
@Atom2004 so with all extensions disabled and in stable you cannot reproduce this? Can you find out which extension is causing it by enabling one by one?

**Comment by Atom2004** [comment]
> @Atom2004 so with all extensions disabled and in stable you cannot reproduce this? Can you find out which extension is causing it by enabling one by one?

I can reproduce this issue whether the extensions enabled or not in the stable version. But I can not reproduce this in insider version.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by Atom2004** [comment]
> Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

I'm trying for a long time but I never met this issue so far.
