### ISSUE TITLE
Expected "array" green squiggles when passing array JSON ARM

### ISSUE THREAD

**Issue by lwsrbrts** [Microsoft/vscode#8776]
- VSCode Version: 1.2.1
- OS Version: Windows 10 Build 14372

Steps to Reproduce:

1. Define a parameter of type array in the appropriate parameters section of the template.
2. In a section that requires an array, pass only the parameter instead of starting and ending with square brackets.

This specifically relates to an issue I see when using the dnsServers setting to define the DNS servers to use when creating a NIC.

In the following piece of code, the dnsServers value doesn't validate, despite it being passed as an array - I appreciate this may not even be possible to fix given the types declared may simply not be validated at this level.

```
"parameters": {
    "onPremDNSServers": { 
      "type": "array"
    }
},
"resources": {

    {
      "apiVersion": "2015-06-15",
      "type": "Microsoft.Network/networkInterfaces",
      "name": "[concat(parameters('BEvirtualMachineNames')[copyIndex()],'-nic')]",
      "location": "[resourceGroup().location]",
      "copy": {
        "name": "BEnicLoop",
        "count": "[length(parameters('BEvirtualMachineNames'))]"
      },
      "dependsOn": [
      ],
      "properties": {
        "ipConfigurations": [
          {
            "name": "ipconfig1",
            "properties": {
              "privateIPAllocationMethod": "Static",
              "privateIPAddress": "[concat(parameters('BEsubnetIPPrefix'),copyIndex(parameters('BEnicStartingAddress')))]",
              "subnet": {
                "id": "[variables('BEsubnetRef')]"
              }
            }
          }
        ],
        "dnsSettings": {
          "dnsServers": "[parameters('onPremDNSServers')]"
        }
      }
    }
}
```
Despite the green squiggles, the ARM template will deploy successfully, it seems that just because there are no square brackets immediately after `"dnsServers":` - the green squiggles appear with `Incorrect type. Expected "array"`

The full ARM template (which works when deployed) is attached. Line 153 gives the green squiggles.

[azuredeploy.zip](https://github.com/Microsoft/vscode/files/348739/azuredeploy.zip)

**Comment by aeschli** [comment]
This issue was moved to Azure/azure-resource-manager-schemas#193

**Comment by aeschli** [comment]
The schema at http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/networkInterfaces specifies that dnsServers is an array of type string.

Moving to https://github.com/Azure/azure-resource-manager-schemas
