### ISSUE TITLE
I can not input the letter "l".

### ISSUE THREAD

**Issue by Nuaaphd** [microsoft/vscode#87760]
Issue Type: <b>Bug</b>

L became a command?
![image](https://user-images.githubusercontent.com/43512491/71512102-c106a180-28cf-11ea-9abc-4c91812ff8a0.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.41.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
cpptools|ms-|0.26.3-insiders2
csharp|ms-|1.21.9
notepadplusplus-keybindings|ms-|1.0.5
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
tensorflow-snippets|vah|0.3.3

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

It is hard to see what's on screenshot because it's too small (looks like thumbnail instead of link to actual screenshot)
