### ISSUE TITLE
HTML file multiple cursor

### ISSUE THREAD

**Issue by ranajyotic** [microsoft/vscode#87769]
Issue Type: <b>Bug</b>

When I put the blinking curson in a tag, the opening and closing tags are highlighted and there would be now two blinking cursors and any edit will be reflected to both cursor positions. I have found this specific to HTML files.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.17GB free)|
|Process Argv|D:\Projects\clearifi-web-lambda|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
sass-lint|gle|1.0.6
cpptools|ms-|0.26.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-hexdump|sle|1.7.2
html-preview-vscode|tht|0.2.5
serverless-snippets|Tim|0.1.0
debug|web|0.24.0

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate Please read the 1.41 release notes for details of this new feature and how to turn it off if you don't want it.
