### ISSUE TITLE
When developing an extension, exthost prints many warnings

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#87768]
When developing an extension with vscode-insiders, the extension host prints many warnings like:

`[warning] [vscode.markdown-language-features] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for...`

The warnings are printed for the following extensions:
- The built-in `vscode.git` extension
- The built-in `vscode.markdown-language-features` extension (when opening a markdown file)
- The built-in `vscode.html-language-features` extension (when opening a html file)
- The built-in `vscode.typescript-language-features` extension (when opening a ts file and typing something)

![warnings](https://user-images.githubusercontent.com/23744935/71514073-589ecc80-289d-11ea-87ce-d958c5e4557e.png)

When developing an extension with vscode, no warnings are printed.

![no-warnings](https://user-images.githubusercontent.com/23744935/71514491-12e30380-289f-11ea-80af-1ace5844177d.png)

- VSCode Version: 1.42.0-insider
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Develop an extension
2. Many warnings are printed inside `Log (Extension Host)`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I believe these should be fixed now. Let me know if you notice any additional ones
