### ISSUE TITLE
Settings json to be sorted in an alphabatical order

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#87764]
Issue Type: <b>Feature Request</b>

can we have an option to get the settings.json re-arranged in an alphabatical order.
may be its already a part of the settings-sync api.
if not i think it will be good to see all related settings at one place.

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.17134

**Comment by B0sh** [comment]
Why can't you just use the sort command to sort the settings? If you select all the text and hit `F1` and then type `Sort` there should be a command to sort the text.

**Comment by roblourens** [comment]
There is likely an extension to handle sorting settings, but vscode should not be opinionated abou tthis because many people have many different ideas about how to organize their settings.

**Comment by lonix1** [comment]
Maybe he means the json editor's left pane - the built-in settings (not the custom settings themselves). Those are not sorted in alpha order and is very hard to use.

Many of us still use the json editor.

Does anyone know of a plugin to do that?
