### ISSUE TITLE
Enabling all extensions doesn't update enabled list

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#87761]
- VSCode Version: 1.41.1
- OS Version: OSX 10.15.2

Steps to Reproduce:

1. Disable all extensions
2. Reload the window
3. Enable all extensions by choosing "Enable all extensions" command with cmd+shift+p

All extensions are enabled but enabled list stays empty.

![vscode-extensions](https://user-images.githubusercontent.com/199648/71512445-80d6fd00-2896-11ea-9e95-f5dfeb5fc631.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by warpdesign** [comment]
I wanted to have a look at it myself but when running in dev mode, there are no extensions at all, I'm not sure where to start.

**Comment by sandy081** [comment]
Steps say `Reload the window` but I do not see it in screenshot. 

FYI, Extensions list view does not get updated immediately. There is a feature request already for this.

Closing this as duplicate.
