### ISSUE TITLE
显示 BUG

### ISSUE THREAD

**Issue by Anstehen** [microsoft/vscode#87762]
Issue Type: <b>Feature Request</b>

在使用vue的时候会在界面上报红报错，但还可以正常运行

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment]
Please report issues in English using propert template and detailed steps.
