### ISSUE TITLE
Error pushing new branch with first letter Capital

### ISSUE THREAD

**Issue by azurekid** [microsoft/vscode#87766]
Issue Type: <b>Bug</b>

When creating a new branch through VS Code an error is shown when the the branch name starts with a capital.

In this case I tried to create a branch with the name Rogier/PolicyGuidance
![image](https://user-images.githubusercontent.com/40334679/71514238-090cd080-289e-11ea-8d54-d50a109959ef.png)
![image](https://user-images.githubusercontent.com/40334679/71514250-188c1980-289e-11ea-8a21-dbda8bbd5708.png)

When pushing the new branch it will give an error. 
![image](https://user-images.githubusercontent.com/40334679/71514253-1de96400-289e-11ea-9a2c-a5e0b2ebfa32.png)

If I than click on the branch, it is shown without a capital first letter. 

![image](https://user-images.githubusercontent.com/40334679/71514262-280b6280-289e-11ea-9b88-96372456249e.png)

After selecting it, push is successful

![image](https://user-images.githubusercontent.com/40334679/71514290-3fe2e680-289e-11ea-8a12-e761c429aab1.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
azurepolicyextension|Azu|0.0.22
armview|ben|0.3.3
gitlens|eam|10.2.0
azure-account|ms-|0.8.7
powershell|ms-|2019.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.8.3
code-spell-checker|str|1.7.20
vscode-icons|vsc|9.6.0
arm-params-generator|wil|0.8.1

</details>

**Comment by joaomoreno** [comment]
The problem is that you already have `rogier` and you're trying to create `Rogier`. Git actually splits branch names by `/` and creates folders in disk for each part. So Git can't create a `Rogier` folder since a `rogier` folder already exists.

This isn't a Code issue, but a git limitation.
