### ISSUE TITLE
Intellisense support for gcc __attribute__((libcall))

### ISSUE THREAD

**Issue by AlphaKilimanjaro** [microsoft/vscode#87777]
Certain c libraries use the ((libcall)) attribute in gcc to create interface structs for functions. What it does is it passes the interface base as first argument transparently when calling the function. Like this:

IInterface->SomeFunciton (arg1, arg2, etc);

becomes

IInterface->SomeFunction(IInterface, arg1, arg2, etc);

when constructing the call.

This is not supported in IntelliSense c/c++. It would be a nice-to-have feature when working with these libraries.

**Comment by IllusionMH** [comment]
/causedByExtension

C/C++ support for Visual Studio Code is provided by a Microsoft C/C++ extension (from docs)

Please file this issue in https://github.com/Microsoft/vscode-cpptools repo
