### ISSUE TITLE
Dynamically adjust `Open Editors` pane height to _always_ show ALL open files

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#87774]
Suppose I have 10 open files, and `Open Editors` shows them all.
Suppose I open an 11th file.
I would like the `Open Editors` pane to increase its height so that all 11 are visible.
The current behaviour means I am constantly having to resize/scroll this pane.

**Comment by IllusionMH** [comment]
Just set high enough (but reasonable†) value to `explorer.openEditors.visible`.

† Looks like it will be resized with each editor added (before visible limit is reached ) and will eventually push sections below "reachable" screen.

**Comment by kieferrm** [comment]
@p-i- Please previous comment.
