### ISSUE TITLE
Highlight error for function named 'delete'

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#8777]
- VSCode Version: 1.2.1

Steps to Reproduce:
Just write a function named "delete":

![image](https://cloud.githubusercontent.com/assets/3254987/16602164/d0bc8c4a-42c6-11e6-8433-2984eb3c7a75.png)

Another highlight issue for TS. :)

Error: Identifier Expected

**Comment by joaomoreno** [comment]
[`delete` is a reserved word in TypeScript (and JavaScript)](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#221-reserved-words)

**Comment by unional** [comment]
This comes from module (e.g. `soundcloud`) https://github.com/shawnlauzon/typed-soundcloud/blob/master/index.d.ts
As I change it to named export:
https://github.com/unional/typed-soundcloud/blob/c926158f8492b2cdd518aa93f612fc6a9a3f2cf4/index.d.ts#L9

it fails.  Do you have a recommendation on how to do it?

**Comment by joaomoreno** [comment]
I see, so `delete` is a valid object property, just not a valid function name.

Yeah... sounds like another TypeScript type constraint problem. 😉 

Maybe @jrieken has an idea how to solve it?

**Comment by jrieken** [comment]
I believe the difference is to have `delete` as a global symbol vs a member symbol. The `soundcloud` sample does the (correct) former and you do the latter.

**Comment by unional** [comment]
Since it's named export, shouldn't it consider as local? Or maybe I'm not understanding what you mean by "global symbol vs a member symbol"

btw the original issue on that repo is that structure does not expose the interfaces. I fixed it using namespace:
https://github.com/unional/typed-soundcloud/blob/b9506673dba719e76b4440eae6c5984558f6a61a/index.d.ts

But this issue would occurs if we try to change the typings from commonJS to ES module syntax.
