### ISSUE TITLE
missing remove folder from workspace 

### ISSUE THREAD

**Issue by quangthanh010290** [microsoft/vscode#87772]
Issue Type: <b>Bug</b>

1. select add folder to workspace
2. select folder that have multiple level

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.19.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.55GB (8.48GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
meld-diff|dan|1.0.5
gitlens|eam|10.2.0
pip-packages|etm|0.4.3
asciidoctor-vscode|joa|2.7.7
python|ms-|2019.11.50794
cpptools|ms-|0.26.3-insiders2
trailing-spaces|sha|0.3.1

</details>

**Comment by kieferrm** [comment]
See pictures below. 

![image](https://user-images.githubusercontent.com/4674940/71529116-f5f70200-2897-11ea-8fcd-66036755c8dd.png)


![image](https://user-images.githubusercontent.com/4674940/71529131-04451e00-2898-11ea-949d-2dbf934e95d0.png)
