### ISSUE TITLE
Restore Santa Claus hat. I'm offended on intellectual level

### ISSUE THREAD

**Issue by suicane** [microsoft/vscode#87778]
I like spirit of Christmas. I was pleasantly surprised by santa hat. Then I saw a complaint, unfounded because Santa Claus is invented by Coca-Cola company and has nothing to do with religion.

I'm offended on intellectual level where a company that did awesome things (Microsoft: VSCode, TypeScript, Azure, Chromium-based Edge) quickly caved in without fact checking to an obvious troll.

Since being offended is a grave crime these days, I'm offended for all the people with IQ > 100 and ability to google so please - return the Santa hat. 

If you give in to evil people just like that, does that mean I and all the others who think like I do need to find a new editor? I expect more backbone from people capable of doing amazing software.

Thank you.

P.S. - the person who thought of santa hat and added it - you're the MVP, we love you.

**Comment by g-konst** [comment]
They just need to add a checkbox in the settings to enable the `Christmas spirit`, and that’s all.  Anyone who wants to, will enable this setting, the rest will remain as they are.

**Comment by kieferrm** [comment]
See https://github.com/microsoft/vscode/issues/87440.

**Comment by lviggiano** [comment]
@g-konst  maybe Microsoft could wrap different version of vscode: one for general people, and one specifically tailored for SJWs with no feature that can be offensive to anyone.
This would be inclusive.
