### ISSUE TITLE
Update feedback icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#87775]
I noticed Edge has a new feedback icon, maybe we should change our tweet feedback icon too?

<img width="40" alt="Screen Shot 2019-12-27 at 8 44 40 AM" src="https://user-images.githubusercontent.com/2193314/71525766-13bc6b00-2888-11ea-900d-466a545dadac.png">

**Comment by misolori** [comment]
Let's try it out on Insiders next week and see how it goes. Preview:

![image](https://user-images.githubusercontent.com/35271042/71683414-5af2a200-2d47-11ea-81aa-9d796422c483.png)
