### ISSUE TITLE
The TypeScript language service died 5 times right after it got started

### ISSUE THREAD

**Issue by fibric** [microsoft/vscode#87783]
Issue Type: <b>Bug</b>

I see this message now every day since VSC v1.41

I can't tell exactly what triggers crashing TypeScript language service but the last thing changed in my environment is VSC v1.41 and VSC 1.41.1

VS Code version: VSCodium 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-21T00:38:34.410Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (36.34GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
LinkCheckMD|bla|0.1.5
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.0.29
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.11
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.4
docs-images|doc|0.0.1
docs-markdown|doc|0.2.29
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.36
docs-yaml|doc|0.2.4
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
svelte-vscode|Jam|0.9.3
vscode-healthier|Kid|3.0.0
graphql-for-vscode|kum|1.15.3
fish-ide|lun|0.4.0
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.16.2
vscode-devskim|MS-|0.2.2
azure-account|ms-|0.8.7
cpptools|ms-|0.26.2
debugger-for-chrome|msj|4.12.3
color-highlight|nau|2.3.0
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
fabulous|raa|0.12.0
vscode-yaml|red|0.6.1
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3
fish-vscode|sky|0.2.1
tech-debt-tracker|Ste|0.21.0
code-spell-checker|str|1.7.20
tabnine-vscode|Tab|2.1.22
nativescript|Tel|0.11.0
vscode-sort-package-json|uni|1.2.0
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.2
quokka-vscode|Wal|1.0.267
wallaby-vscode|Wal|1.0.162
WebTemplateStudio-dev-nightly|WAS|0.1.1934601
vscode-webhint|web|1.5.2
glean|wix|4.19.0
stylable-intelligence|wix|0.4.1
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
background-phi-colors|wra|2.1.0

(4 theme extensions excluded)

</details>

Maybe related issues: #87650 #87560 #87658 #87521 #87635 #87680 #87695 #87473 #87470 #87251 #87034

**Comment by fibric** [comment]
I downgraded from 1.41.1 to 1.41.0, and the issues are gone. For the time being, I also set the Update Mode to None.

Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-12T20:38:10.027Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

**Comment by hazem94** [comment]
I downgraded it to `1.39` worked fine for me. Thanks for the information.

**Comment by AstrisDev** [comment]
You're saved my psycho )) Thank you.
Downgraded to 1.41.0 and it works perfect.

> I downgraded from 1.41.1 to 1.41.0, and the issues are gone. For the time being, I also set the Update Mode to None.

**Comment by mjbvz** [comment]
@fibric Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by RamiroPinol** [comment]
Bug solved for me with latest insiders build and extensions disabled.

**Comment by fibric** [comment]
I tried the newest insider build and without extensions. It works.
