### ISSUE TITLE
Ryzen 5 3600 -> git.exe instances

### ISSUE THREAD

**Issue by Auxority** [microsoft/vscode#87784]
- VSCode Version: 1.41.1
- OS Version: Windows 10 - 1903 - Build 18362.535

Steps to Reproduce:
1. Use a Ryzen 5 3600 CPU instead of a Ryzen 3 1200
2. Open Visual Studio Code
3. Wait for your visual studio to crash after opening thousands of git.exe instances.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Preview of the bug:
https://auxority.000webhostapp.com/NGHY73q9.mp4

**Comment by Jaakkonen** [comment]
This issue doesn't seem to be CPU dependent. Have you verified you have Git for Windows installed? It should be automatically installed by VS Code but it may be that it has registered git being installed (i.e. check install folder exists) but the git.exe isn't there or it isn't in the search path.
