### ISSUE TITLE
No intellisense

### ISSUE THREAD

**Issue by SumTingWentWong** [microsoft/vscode#87787]
Issue Type: <b>Bug</b>

There is no intellisense when writing in any languege. No luck after searching the web for hours. Now i reach to nerds of wisdom! i seek your guidance.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.6.1
python|ms-|2019.11.50794
csharp|ms-|1.21.9
unity-tools|Tob|1.1.1
unity-debug|Uni|2.7.2

</details>

**Comment by dlxu** [comment]
I am having same issue, the intellisense might work at very beginning upon open vsCode and then it will  stop working. 

Same version/build as depicted in the issue. 

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by husseyexplores** [comment]
I was also having the same problem (windows 10).
Reverting to [version 1.40.0](https://code.visualstudio.com/updates/v1_40) fixed it for now.
I've also disabled auto-updates from the settings until this is fixed.

**Comment by SumTingWentWong** [comment]
> 
> 
> I was also having the same problem with version 1.40.1 - windows 10.
> Reverting to [version 1.40.0](https://code.visualstudio.com/updates/v1_40) fixed it for now.
> I've also disabled auto-updates from the settings until this is fixed.

The issue happens to be the new update so go to hell new update. The solution is to install the october version 1.14.0
