### ISSUE TITLE
Emmet work slowly with longer SASS files

### ISSUE THREAD

**Issue by vellkan** [microsoft/vscode#87785]
Hello!
I've looking for the solution, but some of them are old and won't work.
I've try to change from Sublime Text to VS Code.

When I'm working with my project, for example Wordpress theme and I'm editing CSS file - no matter how long it is - Emmet abbrevation show and work in lightspeed.
When I'm typing m0 and hit TAB - I've got margin:0; in blink eye.

But when I'm working with SCSS file longer that 150-200 lines it's gonna be really slow.
When I type m0 or p10 I need to wait 2-3 seconds before TAB hit to work it.
Popur with suggestions show really slow. I've try to disable it - not showing of them, but it's not help with working speed.
In long HTML/PHP/JS files it's work perfectly - only problem is with SASS/LESS files.

Version: 1.41.1 (user setup)
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

I've try to disable all extensions, I've try disable emmet new version - nothing can help.
I know I'm new in this, but SM3 work so much better, especially in this matter, but I really would like to work with VS.

**Comment by octref** [comment]
Please try to profile emmet and attach it here, so we can analyze the issue, thanks.

https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions.

**Comment by vellkan** [comment]
> Please try to profile emmet and attach it here, so we can analyze the issue, thanks.
> 
> https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions.

Don't worry, I found solution - I just back to Sublime Text 3 and it's works great.
