### ISSUE TITLE
Better implementation of interfaces in TypeScript

### ISSUE THREAD

**Issue by netdjw** [microsoft/vscode#87782]
I'm woring with VSCode and TypeScript and using many interfaces that refer to eachother. So the VSCode's Implement interface hotfix function is very useful, but the end result is not perfect.

Here is what I get now:
```
import { CertificationOutgoingInvoiceUIFieldsInterface } from './certification-outgoing-invoice.interface';

export class CertificationOutgoingInvoice implements CertificationOutgoingInvoiceUIFieldsInterface {
  deviza_id: import("../../../base-model/base-data-type.model").ID;
  files: import("../../../file/file-model.interface").FileModelInterface[];
}
```

Actually two problems are here.

I set it up earlier in tslint to use apostrophe instead of double quotes. It's working fine if I use the Ctrl + space combination to include an import line.

This end result would be much more handy:
```
import { CertificationOutgoingInvoiceUIFieldsInterface } from './certification-outgoing-invoice.interface';
import { ID } from 'src/app/models/base-model/base-data-type.model';
import { FileModelInterface } from 'src/app/models/file/file-model.interface';

export class CertificationOutgoingInvoice implements CertificationOutgoingInvoiceUIFieldsInterface {
  deviza_id: ID;
  files: FileModelInterface[];
}
```

This is much more cleaner. Now I need to spend time to fix the auto-implement's result to this.

Is there any option to get this end result in VSCode?

**Comment by mjbvz** [comment]
Partially covered by https://github.com/microsoft/TypeScript/issues/35078

Please reduce the remaining issue to a small, self contained example

/needsMoreInfo

**Comment by netdjw** [comment]
> Please reduce the remaining issue to a small, self contained example

Ok, I reduced it. Thanks.

**Comment by mjbvz** [comment]
Can you please create a self contained example?

**Comment by netdjw** [comment]
> Can you please create a self contained example?

Maybe this will be good:

here is the interface:
```
// tslint:disable-next-line: max-line-length
import { AmountOfMoney, Description } from 'src/app/models/base-model/base-data-type.model';

export interface MyInterface {
  desciption: Description;
  amount: AmountOfMoney;
}
```
After I write this:
```
export class MyClass implements MyInterface {
}
```
VSCode get an error `Class 'MyClass' incorrectly implements interface 'MyInterface'.` and it's correct. It offer an autoimplement hotfix and I get this code:
```
import { MyInterface } from './my.interface';

export class MyClass implements MyInterface {
  desciption: import("../../../../base-model/base-data-type.model").Description;
  amount: import("../../../../base-model/base-data-type.model").AmountOfMoney;
}
```
instead of this (what I expect):
```
import { MyInterface } from './my.interface';
import { AmountOfMoney, Description } from 'src/app/models/base-model/base-data-type.model';

export class MyClass implements MyInterface {
  description: Description;
  amount: AmountOfMoney;
}
```

**Comment by mjbvz** [comment]
Quote style tracked by https://github.com/microsoft/TypeScript/issues/36140

Import usage tracked by microsoft/TypeScript#35078
