### ISSUE TITLE
Feature request: add ability to compare folders

### ISSUE THREAD

**Issue by fbaligand** [microsoft/vscode#87781]
Currently, we can compare two files, but not two folders.
This would be great to be able to compare two folders also (as Eclipse IDE does for instance).

**Comment by IllusionMH** [comment]
Looks similar to #85060 

In meantime you can check https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders

**Comment by fbaligand** [comment]
Hi @IllusionMH,

Well, yes, it looks like similar.
So I close this issue.
