### ISSUE TITLE
multicursor edit/undo doesnt autoscroll 

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#87789]
the expected behavior works well with the single cursor, but not with multiple ones

### Env
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

### Steps to Reproduce:

1.make multi cursors anywhere in doc
2.scroll away until non of the cursors is visible 
3.start typing something
4.scrollbar doesnt autoscroll to the cursors range

### Expected
- scroll bar should center at the intersected range of the cursors

Does this issue occur when all extensions are disabled?: Yes

**Comment by ctf0** [comment]
update:

this also extend to the arrow keys "up/down/left/right"

**Comment by alexdima** [comment]
Let's track in #6995
