### ISSUE TITLE
can you add a one-click cancel syntax highlighting and auto-completion feature?

### ISSUE THREAD

**Issue by yanjinbin** [microsoft/vscode#87796]
Can vscode add a one-click cancel syntax highlighting and auto-completion feature?
It's right for code interview mode

**Comment by wizzard0** [comment]
can't say it's one-click, more like a couple keystrokes, but maybe it's enough just to switch language mode to plain text (and back, if needed)

**Comment by IllusionMH** [comment]
As @wizzard0 correctly suggested - you can quickly run `>Change Language Mode` from command palette (or clicking on language name in status bar) and pick Plain text.

Also you can add extension mappings in advance
```json
    "files.associations": {
        "*.*": "plaintext"
    }
````

Both cases will disable all language features for concrete or every file.
I don't think that something else should be added to editor only for this strange case.

---

On the side note: IMHO this is wrong kind of code interview where you can use editor, but not its features.

**Comment by yanjinbin** [comment]
thanks, but maybe it's not the best solution, I also need language level color theme
what I expect is like this pic as follows.
 It  is an icon of man is grey as you see in Intellij IDEA
![image](https://user-images.githubusercontent.com/6295386/71556384-fb5c7400-2a72-11ea-80d3-15afdcb7cf8a.png)
It can make me in whiteboard mode only with java color theme. 
However, in VSCODE, I need to disable all Java-related plugins, which can make VSCODE  in whiteboard mode
