### ISSUE TITLE
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser. The file does not match your project config:

### ISSUE THREAD

**Issue by Gumichocopengin8** [microsoft/vscode#87791]
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config:
```
When I created a file, this error came out. 
Once I closed and opened VS code, the error went away. 

I think this is a bug of VS code.

Thank you for VS code. 
I love using it! :)

**Comment by IllusionMH** [comment]
/causedByExtension
This error comes from [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) ([exact lines](https://github.com/typescript-eslint/typescript-eslint/blob/8bf6879e530fb539a1777ffffbfc7b166c3f4a2f/packages/typescript-estree/src/create-program/createProjectProgram.ts#L32-L38)) 

Please see https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0, https://github.com/typescript-eslint/typescript-eslint/issues/890 and https://github.com/typescript-eslint/typescript-eslint/issues/864.
These links have descriptions/discussions of the problems, steps how to resolve them (pay attention to parts about `createDefaultProgram` and `tsconfig.eslint.json`), and instruction on how to analyze and report problem if it's not solved.

**Comment by demisx** [comment]
Please note that creating  the suggested `tsconfig.eslint.json` and linking it in `.eslintrc`  (as `"project": "./tsconfig.eslint.json"`) only fixes the issue at CLI. The VS Code extension will still show this error until it is restarted.  But this appears to be the problem in the [VS Code ESLint extension](https://github.com/Microsoft/vscode-eslint), not the VS Code core. What makes it go away in VS Code, though, without  the`createDefaultProgram` performance penalty is adding this to `settings.json`:

```json
// In VS Code settings.json
"eslint.options": {
    "parserOptions": {
      "project": [
        "${workspaceFolder}/tsconfig.json"
      ],
    }
  }
```
