### ISSUE TITLE
Can not return to the previous state with "--disable-extensions".

### ISSUE THREAD

**Issue by zwuis** [microsoft/vscode#87795]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Download a theme extension and use it.
2. Close VSCode.
3. Open VSCode with command `code --disable-extensions`.
4. Click `Reload` in the lower right corner.
5. VSCode doesn't display the theme you use.

Sorry for my bad English.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:59:13.638Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.41GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
latex-workshop|Jam|8.5.0
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.41.2
cpptools|ms-|0.26.2
debugger-for-edge|msj|1.0.13
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
polacode|pnp|0.3.4
trailing-spaces|sha|0.3.1
vscode-icons|vsc|9.6.0

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Themes are extensions. In step 3, you disable all extension, thereby also disabling the theme extension you installed.

**Comment by zwuis** [comment]
Oh, I mistook "the previous state" as the state before step 2.

Thanks. :)
