### ISSUE TITLE
DocumentFilter does not work for dockerfiles

### ISSUE THREAD

**Issue by PeterJausovec** [Microsoft/vscode#878]
We want our docker extension to support yml and docker files when they are named like ‘docker-compose-dev.yml’ or ‘dockerfile-dev’ etc. Using the DocumentFilter pattern `**/docker-compose*.yml` I was able to get this to work, however DocumentFilter `**/dockerfile*` does not work – I don’t even get syntax coloring.

**Comment by jrieken** [comment]
@PeterJausovec Just to clarify, you have a filter like this `{ pattern: '**/docker-compose*.yml' }`?

**Comment by PeterJausovec** [comment]
Yes, filter like the one below works fine:
`vscode.DocumentFilter = { language: 'yaml', scheme: 'file', pattern: '**/docker-compose*.yml' };`

However, if I try to use a filter for Dockerfile - e.g. `**/dockerfile*`, it does not work.

**Comment by jrieken** [comment]
I'd say that's because `somepath/dockerfile` doesn't match the pattern `**/docker-compose*.yml` or am I missing something?

The properties of the document filter must all match so that the filter matches (logical AND). You can either change the pattern (maybe `**/docker*.yml`) or use make up the selector from an array of two filers like `[{pattern: '**docker-compose*.yml'}, { pattern: '**/dockerfile*}]` because then just one must match (logical OR)

**Comment by PeterJausovec** [comment]
Yes, I know it doesn't - I have a separate document filter that's for dockerfile only and its pattern is `'**/dockerfile*` and files like dockerfile, blah/dockerfile-dev, etc. are *not* recognized by the pattern.

**Comment by PeterJausovec** [comment]
Check the file here: https://github.com/Microsoft/vscode-docker/blob/master/dockerExtension.ts. If I add the pattern to `const DOCKERFILE_MODE_ID: vscode.DocumentFilter = { language: 'dockerfile', scheme: 'file' };`, dockerfiles are not recognized.

**Comment by jrieken** [comment]
This seems to be a problem with our glob matcher

**Comment by bpasero** [comment]
@jrieken I don't see how a pattern of `**/dockerfile*` can match a file `docker-compose-dev.yml`?

**Comment by PeterJausovec** [comment]
I am not trying to match docker file to the docker compose pattern. Check the source file I referenced above.

**Comment by jrieken** [comment]
Sorry, I am not getting it. Can you point to the exact line in that file?

**Comment by PeterJausovec** [comment]
For docker-compose files I am using the pattern below. This works fine. 
Line 20:   `const YAML_MODE_ID: vscode.DocumentFilter = { language: 'yaml', scheme: 'file', pattern: '**/docker-compose*.yml' };`

I was trying to use the pattern `**/dockerfile*` and put it in line 15:
`const DOCKERFILE_MODE_ID: vscode.DocumentFilter = { language: 'dockerfile', scheme: 'file' };`

However, it using the pattern `**/dockerfile*` in line 15 for the dockerfile does not work.

**Comment by jrieken** [comment]
@PeterJausovec please confirm these steps and will in the uri of your document

* have a document selector like this `{ language: 'dockerfile', scheme: 'file', pattern: '**/dockerfile*'}`
* have a `TextDocument` with a `uri` **????**
* -> selector doesn't match?

**Comment by PeterJausovec** [comment]
I added this: `vscode.DocumentFilter = { language: 'dockerfile', scheme: 'file', pattern: '**/dockerfile*' };`, I open a file named `Dockerfile` - I get syntax coloring and all works good. 

If I open a file named `DockerfileBlah` or `Dockerfile.test` I do not get any syntax coloring.

**Comment by jrieken** [comment]
so it does seems to be glob related. please try using just this `vscode.DocumentFilter = { pattern: '**/dockerfile*' }`

**Comment by PeterJausovec** [comment]
I tried `const DOCKERFILE_MODE_ID: vscode.DocumentFilter = { pattern: '**/dockerfile*' };` and I get the exact same behavior: file named `Dockerfile` works, but `DockerfileTest` doesn't.

**Comment by jrieken** [comment]
ok. thanks for the heads-up

**Comment by bpasero** [comment]
Ok I get it, our glob matcher is case sensitive. There is currently no option to test ignoring case. I think the easiest would be to lowercase the file name when passing into the glob call @jrieken

**Comment by jrieken** [comment]
I am unsure if making stuff lower-case is desirable...

**Comment by bpasero** [comment]
If a user can provide multiple document filters for the same kind, the solution is to just provide as many glob patterns as needed to catch the casing too.

**Comment by jrieken** [comment]
yeah. you can do `[{pattern: '**/lowercase'}, {pattern: '**/Uppercase'}]` tho it would be pita to provide all possible permutations. @PeterJausovec is your scenario actually such that case matter and is it common that the file must match on name (like a package.json, tsconfig.json) but is given varying cases?

**Comment by bpasero** [comment]
I can add a flag to glob to ignore casing, since its just a RegEx in the end it should be easy.

**Comment by bpasero** [comment]
(that is, it would be an option, I dont want to enable this for any glob)

**Comment by jrieken** [comment]
unless the flag is in the glob expression itself, it will be the same as me lower-casing the string first I guess

**Comment by bpasero** [comment]
Right, since glob patterns are not RegExp syntax, there is no syntax from what I remember to form a case-insensitive glob. Would it make sense to allow to set this flag from the side of the extension?

{pattern: '**/lowercase', ignoreCase: true}

**Comment by PeterJausovec** [comment]
I would say case doesn't matter; since Docker users will probably have more than 1 dockerfile, our idea was to provide the syntax coloring and all that magic for files that are named `dockerfile*`.

**Comment by jrieken** [comment]
Needs more thinking. Tend towards not doing this.

**Comment by SteveLasker** [comment]
We've updated our yo docker tools to use docker.debug /docker.release to enable developers to compose up multiple environments. This means our scaffolding is generating assets that hide the docker editor features. Is it possible to get this in the January 2016 milestone?

**Comment by egamma** [comment]
CC @chrisdias

**Comment by jrieken** [comment]
@SteveLasker, @PeterJausovec Is it that you guys want to contribute a language service for docker files or do you want to add specific features for certain docker files - those that match a name pattern? Can you provide some samples, like `filename` -> [feature set] etc?

**Comment by PeterJausovec** [comment]
We own the docker extension for VS Code (https://github.com/microsoft/vscode-docker) and as I mentioned earlier, we would like to provide support for files that match the pattern `dockerfile*` (e.g. Dockerfile.dev, Dockerfile-blah, etc.). We want all files that match the pattern above to have the same features as the current Dockerfile pattern has. For example, if I open a `dockerfile` in VS Code today, I get syntax highlighting and all that magic. However, if I open a file named `dockerfile.debug` I don't get any of that.

**Comment by jrieken** [comment]
So what you guys actually want is to be able to map more filenames to the language `dockerfile` such that (this)[https://github.com/Microsoft/vscode-docker/blob/master/dockerExtension.ts#L15]  selector works for more filenames and such that the grammar works for more filenames.

**Comment by jrieken** [comment]
That is then not the document filter, but the language mapping as defined in `package.json` (https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages)

**Comment by jrieken** [comment]
@alexandrudima, @bpasero Do we already support some sort of globbing in the filename-to-language mapping?

**Comment by SteveLasker** [comment]
Just wanted to check on the status of this. We'd really like to close this item out and promote the extension.

**Comment by jrieken** [comment]
@SteveLasker I am still waiting for answers regarding adding a `language` vs a language feature (https://github.com/Microsoft/vscode/issues/878#issuecomment-168615826)

**Comment by SteveLasker** [comment]
Are you looking for input from us or the underlying implementation?

**Comment by jrieken** [comment]
1. You want to contribute a file pattern to language mapping similar to `*.js -> JavaScript` (https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages) but need some more powerful like glob-patterns

2. You want to contribute a language feature like IntelliSense using a DocumentFilter **independent** of the language of a document but purely based on a glob-pattern, like `{ pattern: "*.js"}` instead of `{language: "JavaScript"}`. 


@SteveLasker, @PeterJausovec Please answer (1) or (2).

**Comment by bpasero** [comment]
@jrieken we do not support glob patterns for registering file names to languages currently. The code that decides which mode to load given a file name is https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/languageExtensionPoint.ts#L451

**Comment by jrieken** [comment]
closing in favour of #1851
