### ISSUE TITLE
F5 does not work for Theme editing

### ISSUE THREAD

**Issue by tomByrer** [microsoft/vscode#87806]
Issue Type: <b>Bug</b>

1. Press `F5`
2. Dialog opens to choose between "NodeJS" & other

Expected:
2. Another browser window would automatically open. using the theme I was editing in the first browser.

3 months ago when I edited & published my theme, all I had to do was pres F5 to open a new editor to test my theme.  Now I can't do that.  Here is the docs I used:
https://github.com/tomByrer/Nord-City-Theme/blob/master/vsc-extension-quickstart.md

Official website seems to be outdated also:
https://code.visualstudio.com/api/extension-guides/color-theme#test-a-new-color-theme

I'd like to bypass the debugger stage, & just open the theme I am currently editing in another window as I could before.
cheers

----

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.27GB free)|
|Process Argv|C:\Users\tomby\.vscode\extensions\tombyrer.nord-city-theme-1.2.3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vscode-peacock|joh|3.2.0
vscode-versionlens|pfl|0.24.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
I cannot reproduce this issue.
- I've created a "theme extension" following these steps: https://code.visualstudio.com/api/get-started/your-first-extension
- opened the generated extension with VS Code 1.41.1
- pressed "f5"

An new window opened and I was able to select my new theme from the theme picker.
