### ISSUE TITLE
Vscode Problems doesn't update & line references are frozen (GOLANG)

### ISSUE THREAD

**Issue by piperun** [microsoft/vscode#87802]
Issue Type: <b>Bug</b>

Might be a duplicate of: #50395 but it's closed & locked so 🤷🏿‍♀️.

1. Install all the recommended extensions (Go) and Analytic tools:
```
gocode
gopkgs
go-outline
gocode-gomod
godef
goimports
golint
```

2.  Use vscode on an existing project.

3. Problems don't update if you fix/create new problems.

Extra:
It worked before vscode recommended to install `golint`, `gopls` and `gocode-gomod` I believe it was, I've tried removing both or 1 by 1 and it hasn't helped.

Double Extra:
I believe also the `gopls`  is not very stable with vscode since at times it would remove certain characters like: `t` and `)` and just behaves weird.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (17.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
git-project-manager|fel|1.7.1
Go|ms-|0.11.9
vscode-fileutils|sle|3.0.0

</details>

**Comment by kieferrm** [comment]
@piperun please file this issue against the go extension [here](https://github.com/Microsoft/vscode-go/issues). Thank you!
