### ISSUE TITLE
Execute `revealFileInOS` on TreeItem will use current focused file's URI

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vscode#87804]
Issue Type: <b>Bug</b>

This is a regression bug after https://github.com/microsoft/vscode/commit/0dbe568b59c9fd213bddc5ddc730a4892f3b011c which fixes #86103:

```ts
export function getMultiSelectedResources(resource: URI | object | undefined, listService: IListService, editorService: IEditorService, explorerService: IExplorerService): Array<URI> {
    const list = listService.lastFocusedList;
    if (list?.getHTMLElement() === document.activeElement) {
        // Explorer
        if (list instanceof AsyncDataTree) {  // <-- TreeView List will also fall into this block!
            // Explorer
            const context = explorerService.getContext(true);
            if (context.length) {
                return context.map(c => c.resource);
            }
        }
```

When executing [`getMultiSelectedResources`](https://github.com/microsoft/vscode/blob/502fe137129301c43cdc3da0b0516b42907d9544/src/vs/workbench/contrib/files/browser/files.ts#L56-L66) with `listService` derived from `TreeView`, if will fall into the logic which only handles `FileExplorer`, causing the returned resource to be the currently focused file's uri. 

Steps to Reproduce:
1. Consider a java-dependency-viewer treeview:
![image](https://user-images.githubusercontent.com/20227484/71543789-3d71b100-29b2-11ea-960d-7d7198b10bba.png)

2. Execute `Reveal In Explorer` on a jar file, which will forward jar file's uri to `revealFileInOS` command.

3. On older versions, it will work as expected, but in insider version and the newly released version, it will open the folder containing the currently focused file.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:32:17.711Z)
OS version: Linux x64 4.15.0

**Comment by isidorn** [comment]
@Vigilans vscode insiders from next week will contain your fix. Just let us know if the issue gets resolved for you so we can verify this issue. Thank you

**Comment by Vigilans** [comment]
Hi @isidorn, I confirmed that this issue has been resolved in new insider version, thank you!

**Comment by isidorn** [comment]
Thank you, adding verified label.
