### ISSUE TITLE
把速览定义放在右键的二级目录下真是个变态的设计

### ISSUE THREAD

**Issue by lgl608** [microsoft/vscode#87800]
Issue Type: <b>Bug</b>

把速览定义放在右键的二级目录下真是个变态的设计

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.59GB (3.22GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
msg|ajs|0.1.1
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
prototxt|dmi|0.0.6
githistory|don|0.4.12
translation|dus|0.0.4
gitlens|eam|10.2.0
comment-translate|int|1.4.2
advpl-vscode|Kil|0.13.0
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.41.2
vscode-ros|ms-|0.6.2
python|ms-|2019.11.50794
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.3-insiders2
cmake|twx|0.0.17
vscode-zh-hans-custom|wan|1.1.0
clang-format|xav|1.9.0
vscode-proto3|zxh|0.4.0

</details>

**Comment by Lemmingh** [comment]
## Translation

I hate the design that putting **Peek Definition** under a cascading context menu.

**Comment by Lemmingh** [comment]
@lgl608 might be experiencing the situation same as #87628 and #86316, or even worse.

According to #85218, the Peek submenu is by design. However, IMO, the **Peek** commands are **frequently used**, and it's **much more convenient to access them by context menu** than by keyboard.

@jrieken , please reconsider it. What about **putting Peek commands into the main menu** and **folding Goto commands**? Thanks.
