### ISSUE TITLE
Quick suggestions still appearing in snippets even when explicitly prevented

### ISSUE THREAD

**Issue by decodejacques** [microsoft/vscode#87814]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 19.04

Here is an image of what I'm seeing: https://drive.google.com/file/d/1p8-2TgrhIcRPHqfnKTRwhMfxbK6Qbb_B/view?usp=sharing

Steps to Reproduce:

1. set "snippetsPreventQuickSuggestions" to true in settings
2. Add this snippet to javascript.json
```
"test snippet": {
		"prefix": "eq",
		"body": [
			"$1 = $2"
		],
		"description": "equality"
	}
```
3. Create a new javascript file. Here is the contents of the file
```
let obj = {prop: 5}
eq
```
4. Press tab beside eq to start the snippet. The code should look like this now
```
let obj = {prop: 5}
 =
```
5. Type obj.prop, you should see a quick suggestion for prop. In other words, the quick suggestion is not prevented. Pressing tab selects the suggestion instead of moving to the next section of the  snippet.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
trigger characters, like `.`, aren't part of what we call "quick suggestions". They appear as soon as you start typing, where trigger characters are more specific, like the dot. Those aren't muted when typing snippets.
