### ISSUE TITLE
multiple cursors HTML bug

### ISSUE THREAD

**Issue by Xa4vier** [microsoft/vscode#87818]
If i want to use multiple cursors in a HTML tag, the first one will also place a new cursos in the closing tag. And if I select a new place to add a second cursors this cursos will not have a cursos in the closing tag. I think this is a bug, because why would you want to include some attribute in the closing tag? And why else whould VS code not select the closing tag if I add a new cursos. 

**EXAMPLE** ("|" = cursor place)
```
<li "|" ><a routerLink="/recipes">Recipes</a><"|" /li> /// 2 places open and end tag
<li "|" ><a routerLink="/shopping-list">Shopping List</a></li> /// 1 place open tag
```

RESULT: "routerLinkActive="active"" is now also places in the closing tag of the first tag I started my multiple cursor chain.
```
<li routerLinkActive="active"><a routerLink="/recipes">Recipes</a><routerLinkActive="active" /li>
<li routerLinkActive="active"><a routerLink="/shopping-list">Shopping List</a></li>
```

**Comment by CNote1** [comment]
https://www.reddit.com/r/vscode/comments/ech6kk/vscode_multile_issue/
