### ISSUE TITLE
Use CLS can not clear the prompt screen.

### ISSUE THREAD

**Issue by litaotju** [Microsoft/vscode#8781]
- VSCode Version: 1.2.1 commit:fe7f4....2761
- OS Version: Windows 8.1 x64

Use CLS in the terminal shell inside vscode can not clear the prompt screen.

Steps to Reproduce:

1. Ctrl + `
2. CLS

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by leedonhyun** [comment]
Version 1.3.0-insider
Commit e724f269ded347b49fcf1657fc576399354e6703
Date 2016-07-06T13:46:20.448Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

windows 10

Terminal window  don't work 'cls' command. not clear.

**Comment by Tyriar** [comment]
@leedonhyun that's this upstream issue https://github.com/sourcelair/xterm.js/issues/106
