### ISSUE TITLE
[loc][issue] Wrong German translation in pop-up for openening an external URL 

### ISSUE THREAD

**Issue by Jakob-vdH** [microsoft/vscode#87811]
- VSCode Version: 1.41.1
- OS Version: Windows 10 1903, 18362

Steps to Reproduce:

1. Use German as language.
2. Click on any external link in VS Code (CRTL + left mouse button).
3. An pop-up opens, asking if the user wants VS Code to open the external website. Here the highlighted option would say 'Open' / in German 'Öffnen', but instead is says 'Eröffnungskurs' in German, which would translate to something like 'Opening price' for stocks (Screenshots attached below).

_Screenshot of wrong translation in German_
![image](https://user-images.githubusercontent.com/19874459/71545559-d1c91d00-298c-11ea-84ae-bbf3fd9a008d.png)

_Screenshot of the pop-up in English_
![image](https://user-images.githubusercontent.com/19874459/71545738-dee70b80-298e-11ea-88ac-c4b9fe9f9a5e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by danyeh** [comment]
Thank you for your feedback! 
This was fixed long time ago.
https://github.com/microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-de/translations/main.i18n.json#L6826
