### ISSUE TITLE
When can remote server docker debugging be supported

### ISSUE THREAD

**Issue by koln2017** [microsoft/vscode#87812]
When can remote server docker debugging be supported

**Comment by IllusionMH** [comment]
/causedByExtension

Please use StackOverflow for questions.

[Remote - Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) is supposed to be used for debug in docker containers and if you have issues with this extension you should report them in extension repo https://github.com/Microsoft/vscode-remote-release/issues (with more details that this one has)
