### ISSUE TITLE
Why is VSCODE heavy, and consumes memory resources?

### ISSUE THREAD

**Issue by jeanluc243** [microsoft/vscode#87815]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Just in case - VSCode is build on top of Electron which brings Chromium and Node with their runtimes and memory consumption pattern.

If you have concrete concerns see https://github.com/microsoft/vscode/wiki/Performance-Issues
