### ISSUE TITLE
[html] [rename on type] problem with particular formatting

### ISSUE THREAD

**Issue by Dassderdie** [microsoft/vscode#87819]
- VSCode Version: 1.41
- OS Version: Windows 10

![reproduction-mirror-cursor-bug-vscode](https://user-images.githubusercontent.com/18506183/71548583-f8994a80-29b0-11ea-8462-6fc597b593d3.gif)

Steps to Reproduce:

1. Write the following in a html file (formatted with prettier):
```html
<span
  class="Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor"
  >*</span
>
```
2. Try to write an additional `<span>`-element directly before the other element
3. The expected result would have been 
```html
<span></span>
<span
  class="Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor"
  >*</span
>
```
instead of 
```html
<span></span>
<span
  class="Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor"
  >*</span></span>
>
```

**Comment by jnsatterfield** [comment]
I can confirm this behavior. It appears to extend to HTML-like languages, such as EJS, as well.

**Comment by octref** [comment]
This does not reproduce for me. Do you have other extension (especially auto-rename-tag extension) installed?

![m](https://user-images.githubusercontent.com/4033249/72149688-fc12d580-33a3-11ea-95b4-27a8c0f9b909.gif)

**Comment by Dassderdie** [comment]
I tried it out again (inclusive "disable all installed extensions" -> reload) and was able to reproduce this issue on two different devices :confused:

**Comment by robclancy** [comment]
This has been the worst feature I've seen in vscode. I don't even know how it has gotten to production. It bugs out far more than it works properly in new and exciting ways every day.
I especially love pasting a new attribute and having it added to the closing tag.

**Comment by idlelimey** [comment]
Just to confirm I can replicate this issue too.

- Version: 1.41.1 (user setup)
- Commit: `26076a4de974ead31f97692a0d32f90d735645c0`
- Date: 2019-12-18T14:58:56.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.17763

The simple _fix_, sadly, is to turn it off in settings (`html.mirrorCursorOnMatchingTag`).  I had been looking forward to this feature for the odd element change but I can't live with the constant cleaning up of closing tags _with attributes_.  Unless I'm 'holding it wrong'.

**Comment by aeschli** [comment]
Fixed in latest
