### ISSUE TITLE
PyQt5 Lib Not Found

### ISSUE THREAD

**Issue by udoyen** [microsoft/vscode#87829]
Issue Type: <b>Bug</b>

1. Install PyQt5 lib via pip3 install pyqt5 and sudo apt install python3-pyqt5
2. Create a simple pyqt5 application that displays 'Hello World'
3. Launch the application

### Actual Results:

```[Running] python -u "/home/george/Documents/python-projects/hello.py"
Traceback (most recent call last):
  File "/home/george/Documents/python-projects/hello.py", line 7, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named PyQt5.QtWidget
```

### Expected Results:

PyQt5 Application Window

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2707)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|11.62GB (0.67GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
Handlebars|and|0.4.1
handlebars-preview-with-function-support|ano|2.1.0
vscode-django|bat|0.19.0
vscode-intelephense-client|bme|1.3.6
simple-react-snippets|bur|1.2.2
handlebars-preview|cha|1.1.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
vscode-eslint|dba|2.0.11
githistory|don|0.4.12
python-extension-pack|don|1.6.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
apacheconf-snippets|eim|1.3.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
git-project-manager|fel|1.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
file-icons|fil|1.0.20
code-runner|for|0.9.15
docker-explorer|for|0.1.6
kotlin|fwc|0.2.11
cloudcode|goo|1.0.1
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
composer|ika|0.7.1
easy-icons|jam|0.3.1
vscode-edit-csv|jan|0.2.5
php-cs-fixer|jun|0.1.129
intellij-idea-keybindings|k--|0.2.37
edge|luo|0.3.2
MagicPython|mag|1.1.0
Angular-BeastCode|Mik|8.1.2
theme-monokai-pro-vscode|mon|1.1.14
vscode-apache|mrm|1.2.0
vscode-docker|ms-|0.9.0
mssql|ms-|1.8.0
python|ms-|2019.11.50794
azure-account|ms-|0.8.7
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
awesome-flutter-snippets|Nas|2.0.3
laravel-blade|one|1.20.0
csv-to-table|php|1.2.1
material-icon-theme|PKi|3.9.2
vscode-data-preview|Ran|1.49.0
java|red|0.55.1
jinjahtml|sam|0.11.0
code-settings-sync|Sha|3.4.3
ejs-snippets|Tao|0.1.0
ayu|tea|0.18.0
vscode-docker-ws|tii|0.4.1
pdf|tom|0.5.1
vscodeintellicode|Vis|1.2.2
vscode-icons|vsc|9.6.0
vim|vsc|1.12.4
jinja|who|0.0.8
html-css-class-completion|Zig|1.19.0

(7 theme extensions excluded)

</details>
.

**Comment by kieferrm** [comment]
@udoyen please file this issue against the Python extension [here](https://github.com/Microsoft/vscode-python/issues). Thank you!
