### ISSUE TITLE
JS/TS language features are not working

### ISSUE THREAD

**Issue by gurbaj5124871** [microsoft/vscode#87821]
Issue Type: <b>Bug</b>

Just by opening the project the default extention crashes

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:55:38.353Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 4|
|Memory (System)|8.00GB (2.11GB free)|
|Process Argv|-psn_0_692393|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.0.11
prettier-vscode|esb|3.18.0
vscode-pull-request-github|Git|0.13.0
graphql-for-vscode|kum|1.15.3

</details>

**Comment by kieferrm** [comment]
Please provide a small JS sample project that reproduces the problem for you. Thank you!
