### ISSUE TITLE
Terminal cannot display zh_CN properly.

### ISSUE THREAD

**Issue by litaotju** [Microsoft/vscode#8782]
VSCode Version: 1.2.1 commit:fe7f4....2761
OS Version: Windows 8.1 x64

The terminal inside vsocde can not display zh_CN（中文） properly in windows.

Steps to Reproduce:

1. Ctrl + `

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by litaotju** [comment]
Thanks. The insider build is fine.
