### ISSUE TITLE
Scroll in explorer

### ISSUE THREAD

**Issue by ganholete** [microsoft/vscode#87820]
Issue Type: <b>Bug</b>

I am using an asus notebook that has software called smart gesture. It simulates the scrolling of a mouse by moving with two fingers on the touchpad. Works everywhere except in the vscode folder list ...

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.70GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.3
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
angular-essentials|joh|0.6.3
Angular2|joh|8.3.0
vscode-peacock|joh|3.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
angular2-inline|nat|0.0.17
angular-console|nrw|10.0.0
material-icon-theme|PKi|3.9.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by byehack** [comment]
i use lenevo and it works well in with touchpad in explorer tab

**Comment by isidorn** [comment]
@ganholete can you reproduce this in other lists in vscode. For example in the extensions view list? Or the SCM or Search view? Can you repredocue with vscode insiders https://code.visualstudio.com/insiders/
@deepak1556 did we already have complaints like this sounds electron related?

**Comment by ganholete** [comment]
> i use lenevo laptop and it works well in with touchpad in explorer tab
Is a problem with asus smart gesture.

> @ganholete can you reproduce this in other lists in vscode. For example in the extensions view list? Or the SCM or Search view? Can you repredocue with vscode insiders https://code.visualstudio.com/insiders/
> @deepak1556 did we already have complaints like this sounds electron related?

This issue happens in all scrollable listings and only in vscode (extensions, options, code). The whole system works.

**Comment by byehack** [comment]
> This issue happens in all scrollable listings and only in vscode (extensions, options, code). The whole system works.

try to reinstall vscode in admin mode and test without any extensions.

**Comment by ganholete** [comment]
> > This issue happens in all scrollable listings and only in vscode (extensions, options, code). The whole system works.
> 
> try to reinstall vscode in admin mode and test without any extensions.

I reinstalled vscode and extensions and now everything works! Thanks!

**Comment by byehack** [comment]
> I reinstalled vscode and extensions and now everything works! Thanks!

Perfect! you can close this issue now
