### ISSUE TITLE
VScode keeps hanging on Linux Mint

### ISSUE THREAD

**Issue by Stancobridge** [microsoft/vscode#87826]
I have removed almost all the extensions I have but it keeps on  hanging
vsoce version: 1.41.1 (it started from the initial version)

**My system configuration**
Memory: 16gb
Processor: Intel® Core™ i5-8300H CPU @ 2.30GHz × 8 
Release Linux Mint 19 Tara 64-bit
Kernel Linux 4.15.0-20-generic x86_64
Available Disk space: 169.5 GiB

**Comment by kieferrm** [comment]
@Stancobridge please start VS Code from the command line with `code --disable-extensions`. Does the problem still persist? Can you please provide step-by-step instructions that reproduce the problem for you when you run with all extensions disabled. Thank you!
