### ISSUE TITLE
kconfig-frontends rendered badly, barely usable in integrated-terminal.

### ISSUE THREAD

**Issue by Devenda** [microsoft/vscode#87838]
When running ESP-IDF menuconfig command from the integrated terminal, the rendering is bad and the arrow keys are not working. 

**Steps to reproduce**
Follow esp-idf getting started guide: 
https://docs.espressif.com/projects/esp-idf/en/latest/get-started/

Execute commands in integrated-terminal

Check output.

**Expected results**
When running in the installed ESP-IDF command Prompt (note arrow keys are working):
![afbeelding](https://user-images.githubusercontent.com/2527506/71556031-5ec6b180-2a33-11ea-8600-f9172fbdddca.png)

When running in Powershell:
![afbeelding](https://user-images.githubusercontent.com/2527506/71556072-40ad8100-2a34-11ea-98b9-2d5aa97c47d3.png)

**Actual results**
Same for cmd and powershell terminal (arrow keys also not working)
![afbeelding](https://user-images.githubusercontent.com/2527506/71556047-bc5afe00-2a33-11ea-8591-de265953824a.png)

Bonus: in the new windows-terminal (note arrow keys are NOT working, but rendering is good):
![afbeelding](https://user-images.githubusercontent.com/2527506/71556038-89b10580-2a33-11ea-98eb-c769322aa175.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
idf-vcode-plugin|Dev|0.1.0
live-p5|fil|1.3.0
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.6
vscode-remote-extensionpack|ms-|0.19.0
cpptools|ms-|0.26.2
powershell|ms-|2019.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.6.1
vscode-icons|vsc|9.7.0
material-theme|zhu|3.2.1

</details>

**Comment by Tyriar** [comment]
Moving upstream https://github.com/xtermjs/xterm.js/issues/2657
