### ISSUE TITLE
Support Type Acquisition From Npx Shebang

### ISSUE THREAD

**Issue by arciisine** [microsoft/vscode#87834]
I'm currently building a library, where primary use case is to be consumed via executable scripts, with `npx` as the shebang command (this allows for global execution without the need for prior installation).   

For example:
```javascript
#!/usr/bin/npx @arcsine/nodesh
stdin
  .sort()
  .unique()
  .stdout
```
When authoring these scripts, the desire is to leverage the typings provided by the library invoked by `npx`.  The assumption here is that the editor would detect `npx` invocation, and load the appropriate typings (local if library is previously installed, or downloaded if not).  

I'm hoping to see if there is any interest in the feature, and if so I would be happy to put together a PR.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by arciisine** [comment]
I don't think this feature would belong in typescript proper which is why I filed it here.  Technically this feature could work within Typescript, but seems like it may be too focused on the editing process.  I'll open a feature request in Typescript and see how that goes.
