### ISSUE TITLE
extension changelog page markdown display incorrectly

### ISSUE THREAD

**Issue by changnet** [microsoft/vscode#87833]
extension changelog page markdown display incorrectly in vs code after installed, but it display correctly in [marketplace](https://marketplace.visualstudio.com/items/changnet.lua-tags/changelog) or [github](https://github.com/changnet/lua-tags/blob/master/CHANGELOG.md)

- VSCode Version:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 3.13.0-157-generic

- OS Version:
1. ubuntu 14.04 x64
2.  win7 x64

Steps to Reproduce:

1. install extension lua-tags
2. switch to changelog page

![2019-12-29 14:10:32屏幕截图](https://user-images.githubusercontent.com/9293777/71553155-2a5bf100-2a45-11ea-99c0-a05c39644ce6.png)

the lua code block is display incorrectly
```lua
-- v is show as
local V -> X.Y = true
```

**Comment by mjbvz** [comment]
Oped https://github.com/markedjs/marked/issues/1592 to track root cause issue

If you are interested in fixing this, please look into contributing upstream
