### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by NixFull** [microsoft/vscode#87837]
Issue Type: <b>Feature Request</b>

Hello,
Impossible to navigate to file when i make import by use package.json
Exemple:
import {myFile} from '@sources/myFile'

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

**Comment by EfstathiadisD** [comment]
I am pretty sure, there is something wrong with your SETUP. I mean how you set up your project. Typically when you use `@`, you should also, appropriately name it in your `package.json`.

```
"name": "@packages/package1"
```

**I use it like that in 3 Separate Project, and it works perfectly. I have tested it in the Version that you are mention and VSCode Insiders.**

> BTW, It is working with that setting, for Months now. So, Previous Versions of Code, should work as well.
