### ISSUE TITLE
 Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by venkateswarluaduru** [microsoft/vscode#87839]
Issue Type: <b>Bug</b>

attempting to GET "https://functionscdn.azureedge.net/public/3.0.2009/Azure.Functions.Cli.win-x64.3.0.2009.zip"
Error: self signed certificate in certificate chain

please suggest to fix the above problem 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (2 x 2397)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (118)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|10.9.1
git-tools|ank|1.0.0
azds|azu|2.0.220191204
azurenodeessentials|azu|0.2.6
armview|ben|0.3.3
node-json-autocomplete|bhs|0.1.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.20.5
vscode-devtools-for-chrome|cod|0.0.5
gitignore|cod|0.6.0
vscode-azure-storage-utility|Com|0.0.2
python-snippets|cst|0.0.8
git-diff-and-merge-tool|dav|1.0.1
vscode-eslint|dba|2.0.11
vscode-gist|dba|1.0.0
python-preview|don|0.0.4
git-extension-pack|don|0.1.3
githistory|don|0.4.12
jupyter|don|1.1.5
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
pull-request-monitor|eri|1.7.1
vscode-git-history|fab|2.0.5
vscode-npm|fkn|3.3.0
git-extensions-for-vs-code|for|1.1.2
azure-storage-explorer|for|0.1.2
github-actions|for|0.0.1
terminal|for|0.0.10
pythonsnippets|frh|1.0.2
gitflow4code|Gre|1.2.3
nodejs-module-snippet|gun|0.0.2
npm-dependency-links|her|1.0.1
AzureFunctionsSnippets|hha|0.1.0
python-coding-conventions|igr|0.0.4
kubernetes-snippets|ipe|0.1.9
powershellprotools|iro|5.5.1
Sbt|itr|0.1.7
vscode-tfs|iva|0.7.2
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
vstsbuildstatus|jep|0.7.1
vstsservicestatus|jep|1.3.0
node-module-intellisense|jhe|1.6.0
diff-tool|jin|0.0.1
core-extension-pack|jro|0.0.2
vscode-cassandra|kdc|0.3.6
vsc-python-indent|Kev|1.8.1
json2csv|kha|0.0.1
vscode-codemetrics|kis|1.23.1
vscode-github|Kni|0.30.3
cql|Law|0.8.7
node-module-intellisense|lei|1.5.0
vscode-sbt-scala|lig|0.2.4
python-path|mge|0.0.11
vscode-exec-node|mir|0.5.1
vs-deploy|mkl|14.0.0
azure-pipelines|ms-|1.157.4
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
vscode-logicapps|ms-|0.2.25
vscode-asa|ms-|0.2.0
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.0.9
mssql|ms-|1.8.0
sqlops-debug|ms-|1.3.0
python|ms-|2019.11.50794
vscode-ai|ms-|0.6.8
azure-deploy|ms-|1.0.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2019.12.0
vscode-node-azure-pack|ms-|0.0.10
vsliveshare|ms-|1.0.1404
vsliveshare-audio|ms-|0.1.80
vsonline|ms-|1.0.1424
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.3
azure-hdinsight|msh|1.1.7
debugger-for-chrome|msj|4.12.3
nodejs-docs|Muk|0.2.2
gitdownloadazurerepos|nei|1.0.9
python-coding-tools|nil|1.0.3
vscode-for-node-js-development-pack|nod|2.0.1
indent-rainbow|ode|7.4.0
vscode-ipython|pan|0.5.0
npm|pik|0.0.12
vscode-gitextensions|pmi|1.0.0
text-power-tools|qcz|1.11.1
vscode-yaml|red|0.6.1
vscode-format|rya|0.0.6
git-add-remote|sam|0.0.2
git-pull-upstream|sam|0.0.7
yo|sam|0.9.3
scala|sca|0.3.8
scala-snippets|sca|0.1.0
code-settings-sync|Sha|3.4.3
azure-event-hub-explorer|Sum|0.1.2
python|tht|0.2.3
corona-tools|Tob|0.2.1
python-extended-snippets|tus|0.0.1
usql-vscode-ext|usq|0.2.15
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.2
application-insights|Vis|0.4.2
vim|vsc|1.12.4
nodejs-extension-pack|wad|0.1.9
NodeJS-extension-pack|wal|0.0.2
wilderminds-aspnetcore-snippets|wil|0.2.1
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
NbConverter|yig|1.4.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@venkateswarluaduru please provide the steps that allow us to reproduce the problem. Thank you!
