### ISSUE TITLE
Regex does not support `\K`

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#87842]
In a regex search, `\K`  will prevent the previously matched text from being in the overall match. See

> To overcome the limitations of lookbehind, Perl 5.10, PCRE 7.2, Ruby 2.0, and Boost 1.42 introduce a new feature that can be used instead of lookbehind for its most common purpose. \K keeps the text matched so far out of the overall regex match.

from https://www.regular-expressions.info/keep.html

It appears that `\K` is supported in pcre2, so shouldn't this work in vscode?  For example, if I wish to find every 9th line in a file, this regex should work:

`(?:.*\n){8}\K(.*\n)`  See [https://regex101.com/r/IjbZTP/1](url) with pcre option selected.  Then I could select all find matches or set cursors at all without the full match text being included in the find match - as it is if you use `(?:.*\n){8}(.*\n)` .  So I want to keep all that matched text out of the find match except line 9 for example.  But `\K` does not appear to be supported in vscode.

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19536

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
We didn't support `\k` in Find as it's JS based.
