### ISSUE TITLE
Allow extending Search by replacing ripgrep with a stand in replacement search tool

### ISSUE THREAD

**Issue by dutzi** [microsoft/vscode#87841]
The idea is to allow extending the Search panel by providing an alternative for Ripgrep, one that outputs a similar format.

The use-case I'm addressing is one where a user wants to find-in-files by running *some query* that's applied to every file. The extension provides a "find callback" (the one that's getting called per-each file).

A concrete example: Running a [TSQuery](https://github.com/phenomnomnominal/tsquery) on all files, finding all function declarations, for instance.

This Search Extension I'm suggesting should do 2 things:

- The extension should provide an alternative to Ripgrep (**the replacement**), one that implements a similar API (or at least a necessary subset which is required by VSCode).
- The extension should provide an icon for a button (**the button**) that will be displayed within the search input box, next to the Match Case, Match Whole Word and Use Regular Expression buttons. 

**The button** will be a toggle button that once toggled on will cause every search to go through the **the replacement**, so eventually the search results will be comprised of all the files that fall underneath the search criteria.

And here are some screenshots, to clarify the process of using such extension:

![image](https://user-images.githubusercontent.com/927310/71557145-d0f6c080-2a4a-11ea-9557-ea9f6558169d.png)

![image](https://user-images.githubusercontent.com/927310/71557146-d48a4780-2a4a-11ea-8960-729ccaf1eff0.png)

![image](https://user-images.githubusercontent.com/927310/71557151-d6eca180-2a4a-11ea-833d-99f8b7231887.png)

**Comment by roblourens** [comment]
This would be a potential application of the proposed text search provider API: https://github.com/microsoft/vscode/issues/59921

However, I don't know if taking over the search viewlet is really the best approach for this kind of functionality. Maybe just showing an input box and putting results in an editor or custom view, which extensions can already do.

**Comment by dutzi** [comment]
Got it, makes sense. 

Is there anywhere I can read about implementing custom views within an extension? I've searched for docs/examples but couldn't find anything.

**Comment by roblourens** [comment]
Here is a good place to start, see the view containers and tree views topics: https://code.visualstudio.com/api/extension-capabilities/extending-workbench
