### ISSUE TITLE
Navigating between windows command shell and terminal 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#87848]
When running the same program in both a vanilla command shell in windows and within vscode terminal. The results are not identical when navigating between files ?

**Windows Command Shell**
![commandShell](https://user-images.githubusercontent.com/6827459/71561392-dd2b4f80-2a43-11ea-97fd-6dfa81686510.gif)

**Terminal in Code**
![vscodeterminal](https://user-images.githubusercontent.com/6827459/71561400-f3d1a680-2a43-11ea-92a4-a23dd3860ca0.gif)

**Comment by shogerr** [comment]
I'll concur that the integrated terminal is extremely broken in VSCode. I'm a powershell user, and it's not even worth having the integrated terminal open. A good solution is to hit the '+' button, and open a new terminal. This seems to fix a lot of the navigation issues (think `set-psreadline -editmode emacs`), but it's still far from useable.

**Comment by SheepDomination** [comment]
@shogerr Opening a new terminal doesn't fix the problem, and I shouldn't have to open a new terminal,  terminal should operate the same way it does within windows itself.

**Comment by shogerr** [comment]
@SheepDomination, hey, I totally agree. I've just noticed that for myself, tab navigation etc seems to work in a terminal session that has not been opened as the integrated terminal. It's more of a lead to whomever takes up this ticket, that something about the behavior of the integrated terminal breaks the expected functionality of the terminal itself.

**Comment by SheepDomination** [comment]
@shogerr In your second reply I got that I should try the *tab* key, whether I was right or wrong, I tried it; although unsuccessful.  
I didn't notice a change at all, it is exactly the same.

**Comment by shogerr** [comment]
It looks like this issue has been assigned to someone. I've honestly not tried to troubleshoot this issue, and I'd also like to see some attention paid to this issue. That's pretty much why I replied: the more replies an issue gets, the bots will respond and up the priority. Microsoft painfully applies automation to their issues, so you have to wade through that nonsense. Let's hope Github doesn't turn into the Visual Studio developer forum. That would be a nightmare.

**Comment by SheepDomination** [comment]
@shogerr That explains why responses take so long, as you mentioned; it's automated. Otherwise you wait days for a response, if any response at all.

**Comment by Tyriar** [comment]
Does the same thing happen with Windows Terminal?  https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701

**Comment by shogerr** [comment]
Isn't that kind of extreme to put Windows Terminal on? That's a UWP application, and after test driving it, I already know that it will never be permanent part of my system, ever. Other users may not have the same feeling, but... they just might. Could the user not install pwsh 7, rc1 instead? Would that not be a little more reasonable?

**Comment by Tyriar** [comment]
@shogerr Windows Terminal provides and maintains the backend used for launching the processes and emulating pseudoterminals, I'm suggesting installing it so we can see if the bug is part of that component of VS Code's frontend.

**Comment by shogerr** [comment]
@SheepDomination Consider that when you create an issue here, you are getting involved with the development process for the application. Your issues helps improve the product because now you are participating in the development process: you are now a developer on the project in part. So, don't think of these issues like tickets that demand resolution from the team, but rather think of them like your contribution to the project as a developer: that's the nature of open source. An issue may or may not be addressed as part of the development process, depending on the discussion that happens here.

@Tyriar Understood.

**Comment by SheepDomination** [comment]
@Tyriar It doesn't work well in Windows Terminal either. 
![windowsterminal](https://user-images.githubusercontent.com/6827459/71605297-c6fdbc00-2b35-11ea-95fb-105e7b738d27.gif)

**Comment by Tyriar** [comment]
While the issues look a little different, I suggest following this up with the terminal team first so they can fix the component that we depend on (conpty), then refile here if it's still a problem. https://github.com/microsoft/terminal

Please link the terminal issue here when you create/find it.
