### ISSUE TITLE
Collapse wont work correctly

### ISSUE THREAD

**Issue by LindolfoJunior** [microsoft/vscode#87856]
Issue Type: <b>Bug</b>

When i try to collapse the functions with coment line the function won't colapse and i need to exclude the comment to work.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
laravel-model-snippets|ahi|1.3.2
vscode-intelephense-client|bme|1.3.6
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.2
vscode-mysql-manager|cwe|1.5.2
EditorConfig|Edi|0.14.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.6.1
dotenv|mik|1.0.1
notepadplusplus-keybindings|ms-|1.0.5
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1404
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
laravel-helpers|raf|0.2.2
laravel-artisan|rya|0.0.27
vscode-laravel-assist|tia|0.1.7
json|Zai|1.0.2

</details>

**Comment by kieferrm** [comment]
Can you please give a source code example?

**Comment by LindolfoJunior** [comment]
Here the code:
function SomenteNumeros($string){
//   dd($string)    
    return preg_replace("/[^0-9]/", "", $string);
}

Pics is better to explain.

Here is a code
![image](https://user-images.githubusercontent.com/38046370/71582568-93954000-2ae9-11ea-93ad-3cd29f36862f.png)

here is collapsed
![image](https://user-images.githubusercontent.com/38046370/71582588-a740a680-2ae9-11ea-9690-41ebfc995673.png)

as you can see the code dont collapse when have a coment.

**Comment by egamma** [comment]
The indentation is by default based on indentation. Adding the comment with an indent will result in the correct folding regions.

```php
function SomenteNumeros($string){
    // dd($string)
return preg_replace("/[^0-9]/", "", $string);
}
```

![image](https://user-images.githubusercontent.com/172399/71644121-ce52d000-2cc3-11ea-8bae-fc59801a1879.png)

VS Code provides API for extensions to implement semantic folding regions. Suggest to file a feature request for the PHP extension you are using to implement the folding regions API.

**Comment by LindolfoJunior** [comment]
Actually, when I comment I always use the shortcut ctrl + / and the error always occurs.
Wouldn't it be more efficient for the editor to always execute collapse considering only what is within the consolidation point for example {}? Note that when we run this collapse process we want to consolidate the lines to visually lighten the code while we are working on other parts of the code.
Wouldn't it be possible to get the editor to work this way?

**Comment by egamma** [comment]
@LindolfoJunior 

>Wouldn't it be more efficient for the editor to always execute collapse considering only what is within the consolidation point for example {}? 

The default folding region computation is fully language agnostic and does not understand scopes like `{}`. In addition to this VS Code provides API for an extension which understands scopes to implement precise folding. For example, the extension https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client uses this API to implement semantic folding ranges.
