### ISSUE TITLE
Visual Studio Online - access web server running in the hosted terminal

### ISSUE THREAD

**Issue by kevinrood** [microsoft/vscode#87858]
When using the hosted Visual Studio Online service, I cannot figure out how to access a server process (web server) running in the "terminal" tab using the browser.

Seems like this would be a pretty common scenario - developing a server app, saving files in the workspace, running a server in the terminal, accessing the changes in the same browser being used for development.

Maybe I overlooked something? 😄

**Comment by kieferrm** [comment]
You can either manually forward the port (search for `port` in the command palette or use the Remote Explorer) or <kbd>Cmd/Ctrl+Click</kbd> the link when printed in the terminal.

**Comment by kevinrood** [comment]
@kieferrm amazing! Thanks! 😄 

I found my way to this repo for support through the feedback dialog in VS Code. It might be useful to include a link to StackOverflow (along with any other support options not mentioned already) in the feedback dialog:

![image](https://user-images.githubusercontent.com/157205/71591277-c0515380-2af9-11ea-8996-559cadc32a4d.png)
