### ISSUE TITLE
WSL Integration with SSH and GPG

### ISSUE THREAD

**Issue by eskse** [microsoft/vscode#87850]
**Please read our Rules of Conduct: https://opensource.microsoft.com/codeofconduct**
Read.

**Please search existing issues to avoid creating duplicates.**
None, after a quick glance.

**Describe the feature you'd like.**
Integrated terminal to popup when using WSL and git to allow passphrase entry for SSH and GPG.
Currently GPG gives and error and SSH just loops.

This would allow for people using SSH and git in WSL to use the VSCode native git integration without having to use the terminal.

**Comment by kieferrm** [comment]
@eskse do you use the Remote-WSL extension? Can you provide more information about your setup?

**Comment by eskse** [comment]
Hi @kieferrm, yes I'm using the Remote-WSL extension with Ubuntu as the Linux distro.
Both my GPG and SSH keys are configured on WSL only (potentially this is where I am going wrong) as VS Code doesn't display a passphrase from when being requested to sign commits or push changes.

**Comment by joeparislbcc** [comment]
I believe I am running into the same issue. I am using the Remote-WSL extension version 0.41.7 in VS Code 1.41.1 on Windows 10 1903 18362.535. When working with a remote repo configured with an SSH key that requires a passphrase I can perform all git actions from the terminal but if I attempt to push/pull from within VS Code I am never prompted for my passphrase and the program just spins.

Further, If I close and re-open VS Code its git plugin no longer functions properly; it seems that VS Code will no longer track changes made to files in the repo. If I save changes to an open file the source control icon in the activity bar does not show any status. Even in this state, I can still interact with git and GitHub from the terminal but VS Code refuses to tract changes to local files.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1022
