### ISSUE TITLE
Command rename

### ISSUE THREAD

**Issue by softlandia** [microsoft/vscode#87853]
Issue Type: <b>Feature Request</b>

After renaming (command F2), the cursor changes position.
When you rename several constants, you have to return the cursor to the block of renamed constants

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
It shouldn't and it doesn't in my testing. So, I need reproducible steps that allow me to see what you see

**Comment by softlandia** [comment]
video
https://drive.google.com/open?id=13Om0aRugPzL12Nakn0W-7XZr8DYi9n8A
on start rename cursor have position at line 53
after rename cursor at line 61
and if i need rename other constant i need use mouse.
I believe that the cursor should return to the position it was when I clicked

**Comment by jrieken** [comment]
Please paste the code here

**Comment by softlandia** [comment]
package cpd

//unit for windows1251

var consonans1251 = [256]byte{

/*      0     1     2     3     4     5     6     7     8     9     A
   B     C     D     E     F*/
    /* 0 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 1 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 2 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 3 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 4 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 5 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 6 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 7 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 8 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 9 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* A */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* B */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* C */ 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 0x00, 0x01, 0x01
, 0x01, 0x01, 0x01, 0x00, 0x01,
    /* D */ 0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01
, 0x00, 0x01, 0x00, 0x00, 0x00,
    /* E */ 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 0x00, 0x01, 0x01
, 0x01, 0x01, 0x01, 0x00, 0x01,
    /* F */ 0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01
, 0x00, 0x01, 0x00, 0x00, 0x00,
}

var vowels1251 = [256]byte{

/*      0     1     2     3     4     5     6     7     8     9     A
   B     C     D     E     F*/
    /* 0 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 1 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 2 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 3 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 4 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 5 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 6 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 7 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 8 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 9 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* A */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* B */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* C */ 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x01, 0x00,
    /* D */ 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x01, 0x00, 0x01, 0x01, 0x01,
    /* E */ 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00
, 0x00, 0x00, 0x00, 0x01, 0x00,
    /* F */ 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x01, 0x00, 0x01, 0x01, 0x01,
}

// cvPairs1251 - counts the number of pairs consonans+vowels
func cvPairs1251(d []byte) (cvPairsCount int) {
    for i := 0; i < len(d)-1; i++ {
        if consonans1251[d[i]] > 0 {
            i++
            if vowels1251[d[i]] > 0 {
                cvPairsCount++
            }
        }
    }
    return cvPairsCount
}

// matchRunes1251 - counts the number of characters that are the most
popular letters of the Russian alphabet
func matchRune1251(d []byte, tbl *codePageTable) int {
    for i := 0; i < len(d); i++ {
        if is1251(d[i]) {
            upper := lu1251(d[i])
            j := tbl.index(rune(d[i]))
            (*tbl)[j].count++
            for i++; (i < len(d)) && is1251(d[i]); i++ {
                if upper >= lu1251(d[i]) {
                    j = tbl.index(rune(d[i]))
                    (*tbl)[j].count++
                }
            }
        }
    }
    return tbl.founded()
}

func match1251(d []byte, tbl *codePageTable) MatchRes {
    return MatchRes{matchRune1251(d, tbl), cvPairs1251(d)}
}

func runesMatch1251_1(d []byte, tbl *codePageTable) (counts int) {
    for i := range d {
        if i < 1 {
            continue
        }
        //case "ab" - counts only if symbols are arranged in pairs
        if is1251(d[i-1]) {
            j := tbl.index(rune(d[i]))
            if j > 0 {
                (*tbl)[j].count++
                counts++
            }
            continue
        }
        if i < 2 {
            continue
        }
        //case " Us" separator_UPPER_lower
        if IsSeparator(rune(d[i-2])) && isUpper1251(d[i-1]) {
            j := tbl.index(rune(d[i]))
            if (j > 0) && (isLower1251(d[i])) {
                (*tbl)[j].count++
                counts++
                continue
            }
        }
    }
    return
}

const (
    cp1251BeginUpperChar = 0xC0
    cp1251StopUpperChar  = 0xDF
    cp1251BeginLowerChar = 0xE0
    cp1251StopLowerChar  = 0xFF
)

func isUpper1251(r byte) bool {
    return (r >= cp1251BeginUpperChar) && (r <= cp1251StopUpperChar)
}

// lu1251 - return 1 if r is upper, return 0 if r is lower
func lu1251(r byte) (res int) {
    if isUpper1251(r) {
        res = 1
    }
    return
}

func isLower1251(r byte) bool {
    return (r >= cp1251BeginLowerChar) && (r <= cp1251StopLowerChar)
}

func is1251(r byte) bool {
    return isUpper1251(r) || isLower1251(r)
}


чт, 2 янв. 2020 г. в 22:57, Johannes Rieken <notifications@github.com>:

**Comment by softlandia** [comment]
You can download full package from https://github.com/softlandia/cpd
file win1251.go
cursor do not keep position at F2 command on all files

чт, 2 янв. 2020 г. в 22:57, Johannes Rieken <notifications@github.com>:

**Comment by jrieken** [comment]
Hm, I get these messages.. Is there any special setup that's not part of the [go-dev-container](https://github.com/microsoft/vscode-dev-containers/blob/75ce586e1e7a934b6b1e0456bdc473f222d1749c/containers/go)?

```
Rename failed: gorename: can't find package containing /workspaces/vscode-dev-containers/containers/go/cpd/win1251.go 
Rename failed: gorename: can't find package containing /workspaces/vscode-dev-containers/containers/go/cpd/win1251.go 
```

**Comment by softlandia** [comment]
Yes, I receive such messages very often... I tried to understand in what cases this message occurs, and in which not. I do not understand yet.

Extentions installed in VSC : 
Go 0.12.0
markdownlint 0.33.0
Numbered bookmarks 6.2.1
Todo Tree 0.0.162
All other installed auto. 
How can i look other  special parts?

**Comment by softlandia** [comment]
I understand.
If package in GO path then F2 work, else not work
