### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by algunacosa** [microsoft/vscode#87855]
I built VSCode using this repository. It runs with no errors (except the console messages), but i can't install extensions. In the Extensions menu, there are no search results, and the built dir has no a "ext" script (or i can't find it). When trying to install the sugested extensions (that appears in the Welcome screen, no in results), it prints an error "No extension gallery service configured"

- VSCode Version: 1.42.0
- OS Version: Manjaro 18.3

Steps to Reproduce:

1. Build VSCode (git clone, yarn watch)
2. Run it (yarn run electron, yarn web)
3. Go to "Extensions". You'll see that there's no results.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
This is correct. You cannot use the marketplace from the OSS version. This requires a VS Code product version.
