### ISSUE TITLE
Autoformat stops working

### ISSUE THREAD

**Issue by T1KK3S** [Microsoft/vscode#8785]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

I am not yet quite sure how to reproduce this issue but every now and again - when working for several hours - some of my JS and JSX files no longer format correctly or at all when I hit the shortcut alt+shift+F.

**Comment by dbaeumer** [comment]
@T1KK3S can you please enable TS tracing using the following setting: `"typescript.tsserver.trace": "messages"` and open the Output view and switch to the TypeScript channel (JS, JSX is powered by TypeScript). When formatting stops can you please attach the output. This will help tracking this down.

**Comment by T1KK3S** [comment]
@dbaeumer I receive following response:

> Sending request: projectInfo (4050). Response expected: yes. Current queue length: 0
Response received: projectInfo (4050). Request took 1 ms. Success: false . Message: Error processing request. Cannot read property 'projectFilename' of undefined
Sending request: format (4051). Response expected: yes. Current queue length: 0
Response received: format (4051). Request took 1 ms. Success: false . Message: Error processing request. No Project.

**Comment by emzero** [comment]
I'm experiencing the same issue. After some time of usage (might be hours, might be minutes) reformat stops working and I have to run the Reload Window command to bring it back.

**Comment by dbaeumer** [comment]
@T1KK3S thanks for the additional info.

Moving to the TS team since this is an issue in the tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9598
