### ISSUE TITLE
Highlight refactoring options

### ISSUE THREAD

**Issue by SSL0** [microsoft/vscode#87869]
I have been using VSCode for a long time and want to ask. Why the editor does not emphasize the possibility of refactoring. Despite the fact that he finds them. I noticed that if you click on the yellow light whenever possible, then there really are useful tips. I compared them to the tips from the JetBrains IDE in the same code, and they matched most of the time. Please add this feature to your editor. This is a very useful thing.

**Comment by mjbvz** [comment]
Making refactoring more discoverable is being investigated with #86788 and #85160
