### ISSUE TITLE
Visual Studio Code not opening 

### ISSUE THREAD

**Issue by BopItFreak** [microsoft/vscode#87861]
Hi.  I'm having a problem where Visual Studio Code will not open at all. Doing `code --verbose` resulted in: `

#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 000000CC4CEFF210 `

- VSCode Version: latest version
- OS Version: Windows 10

Steps to Reproduce:

1. open vs code
2.

Does this issue occur when all extensions are disabled?: Yes

I have a hunch this has something to do with the electron app as I've been having trouble with electron lately in other apps. 

**Edit:** I reinstalled vscode and this resolved the issue. I have a hunch this issue was possibly due to cypress, as this error has come up in their repository.

**Comment by kieferrm** [comment]
Thanks for sharing. I'll close the issue then.

@deepak1556 FYI
