### ISSUE TITLE
Rename in WSL silently fails: Should show error.

### ISSUE THREAD

**Issue by raphtlw** [microsoft/vscode#87873]
Issue Type: <b>Bug</b>

1. Right click on a file in WSL mode, and then click rename
2. After typing in the specific name, press enter.

You should now see that the file does not get renamed at all.

I tested this on folders and files.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.93GB (2.90GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.18.0
python|ms-|2019.11.50794
LiveServer|rit|5.6.1
google-search|skz|0.0.2
relative-line-height|use|1.0.2
macos-modern-theme|dav|1.6.6
vsc-material-theme|Equ|30.0.0
remote-wsl|ms-|0.41.6

(16 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Bow the rename handler catches the error and uses the notification service to show it to the user
