### ISSUE TITLE
allow delay between edits via vscode extension api

### ISSUE THREAD

**Issue by tansaku** [microsoft/vscode#87871]
I'd like to be able to add a series of edits via a vscode extension to simulate the process of someone typing in real time.  I was wondering if I could [use an existing library](https://stackoverflow.com/questions/59526405/is-it-possible-to-get-terminal-text-typing-effects-in-a-vscode-extension) but they all seem to rely on access to the DOM which I don't think is exposd.

I tried to create a custom approach, but can't get anything to work at the moment.  Putting together a series of edits like so:

```ts
const textEdits: vscode.TextEdit[] = []
string.forEach( (character: string, index: number) => {
	console.log(`character[${index}]: ${character}`)
	textEdits.push(vscode.TextEdit.insert(new vscode.Position(0, index), character))
})
const workEdits = new vscode.WorkspaceEdit();
workEdits.set(document.uri, textEdits); // give the edits
vscode.workspace.applyEdit(workEdits); // apply the edits
```
applies them all immediately, and when I try to loop through and introduce a delay like so:

```ts
string.split('').forEach(async (character: string, index: number) => {
	wait(500).then(_ => { 
		editBuilder.insert(new vscode.Position(0,index), character) 
	})
})	

function wait(milliseconds: number) {
	return new Promise(resolve => setTimeout(resolve, milliseconds))
}
```

then I get errors like so:

```
rejected promise not handled within 1 second: Error: Edit is only valid while callback runs
```

I'd really like to simulate typing in a vscode extension for educational purposes, and I wonder if there is some existing way to achieve this, or something that could be changed to allow it?  

Many thanks in advance

**Comment by jrieken** [comment]
The `editBuilder` "expires" once you return from the callback passed to [`TextEditor.edit`](https://github.com/microsoft/vscode/blob/64fd341760fdeb688bb13a9d1b5805291d4ff3a4/src/vs/vscode.d.ts#L1125). If you want to partition your work into multiple chunks, the you must call `edit` multiple times, tho subsequent edits must then be based on the modified states.

**Comment by tansaku** [comment]
thanks @jrieken - I tried that a la:

```ts
string.forEach( (character: string, index: number) => {
     console.log(`character[${index}]: ${character}`)
     editor.edit(editBuilder => {
          editBuilder.insert(new vscode.Position(0, index), character)
     })
})
```
but this only seems to insert the first letter.  As you can maybe see I'm trying to make each subsequent edit make sense in terms of the previous edit by using the index ...

The console log outputs all the characters, so I know the loop is working, but is there something else I'm missing?

**Comment by jrieken** [comment]
Try to `await` the promise that's returned from calling `edit`. Only when that resolves have the edits been applied

**Comment by RandomFractals** [comment]
btw, I don't think @vscodebot closing it with the link to the 3rd party vscode extensions dev community is a good resolution for this ticket :) ...

**Comment by tansaku** [comment]
thanks @jrieken - I seem to have it working now using the following code:

```ts
let line = 0
let typing = array.reduce((promise: Promise<any>, character: string, index: number) =>
	promise.then((_: any) => 
		editor.edit(editBuilder => { return editBuilder.insert(new vscode.Position(line, index), character) })
			.then(_ => { return wait(100) })
				.then(_ => { if(character === '\n') { line++ }})		
	)
, Promise.resolve())
typing().catch((err: any) => console.log(err))
```

however I get a pop up saying the extension failed that seem to prevent me from running other subsequent code 

<img width="565" alt="Screenshot 2019-12-31 09 33 18" src="https://user-images.githubusercontent.com/30216/71605995-bf2f2d80-2bb0-11ea-93dc-094ae6df0caa.png">

but there is no more detail than that and nothing in the debug console where I'm building the extension.  So I guess that's maybe related to the time it takes to type things out triggering some timeout with vscode, the extension etc. ... not ideal ... would like to fix that ...

**Comment by tansaku** [comment]
btw, here's an animated gif of the typewriter effect in action

![vscodeextension-typewriter](https://user-images.githubusercontent.com/30216/71606147-dde1f400-2bb1-11ea-9633-e96773a8ad2e.gif)

**Comment by RandomFractals** [comment]
@tansaku this is really cool! Are you publishing this as an extension in marketplace soon? I think some devs would use it for code bits presentations.

**Comment by tansaku** [comment]
@RandomFractals would be great to publish it :-) At the moment it's part of a larger extension that's relying on some insider proposed API ... I'd need to break out the typewriter bit as a separate extension - not quite sure how that all works yet, but would be nice to provide a little module or something that others could use ...
