### ISSUE TITLE
Suggestion: Add ability to Find/Replace in selection

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#8787]
- VSCode Version: Code - Insiders 1.3.0-insider (a1293f5056e79c3f0e2cd3e24909f41ff4eef472, 2016-07-05T13:09:46.271Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Select some text
2. Use Ctrl+F or Ctrl+H
3. Observe that there is no way to find matches and replace all occurrences within the selection.

Side note: would also be nice if there was some way to indicate to "Change All Occurrences (Ctrl+F2)" a range in which to create the cursors.

**Comment by isidorn** [comment]
We actually already support this - try out the 'Find in selection' button in the find widget

![selectionfind](https://cloud.githubusercontent.com/assets/1926584/16618237/9c9fac2c-4388-11e6-858c-b9b0e35aacf3.gif)

**Comment by dilijev** [comment]
Ah thanks. I didn't even notice that button. Maybe it would make sense to make that selected by default when a text selection is made at the time the find widget is opened?

**Comment by isidorn** [comment]
I believe that might have been the previous behavior but we have reverted that due to some reason - I can not remember why.

**Comment by tbfleming** [comment]
Is there a way to do this without using the mouse?

**Comment by isidorn** [comment]
@tbfleming yes my pressing ctrl + f and the tab key and lot of times and then a space. I know this is not the best so please file a feature request to create a global workbench command to enable find in selection
