### ISSUE TITLE
Moving Folder in another folder

### ISSUE THREAD

**Issue by bayramucuncu** [microsoft/vscode#87879]
Issue Type: <b>Bug</b>

I am working on angular 8 prject. When I try to move one folder into another folder, the move operation cannot be performed.

![image](https://user-images.githubusercontent.com/2901269/71628746-a9e6ed00-2c0a-11ea-9a23-379db8995501.png)

When I want to mode `user `folder into `components `folder, Visual Studio Code does nothing. And some times shows a permission popup. But when I restart the visual studio, moving successfully.

- Angular version is 8
- Visual studio code version is 1.41.1
- OS is windows 10 pro.
- My OS user is domain user, not local administrator.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bayramucuncu** [comment]
> /needsMoreInfo

I updated mode.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
