### ISSUE TITLE
Repo grouping (folders) in Workspace

### ISSUE THREAD

**Issue by markfinlabs** [microsoft/vscode#87887]
When dealing with many repos in a workspace, the flat listing of them in the explorer becomes difficult to work with. An ability to group them into folders would be great.

**Comment by isidorn** [comment]
This is a fari feature request however we do not have it on our immediate plan.
There might be similar issue already open which might help with your scenario. You can search for them and upvote them. For example working sets might help.

**Comment by markfinlabs** [comment]
Okay, thanks, will search for such requests although didn't see much when searching before. Ideally what I would like is that my VS Code workspace can mirror my folder structure which groups repos by site (e.g. GitHub, BitBucket, other site) and account (company provider,  personal account etc). This is in fact a two-level grouping but I wanted to start with a simple request!

(And, to reduce maintenance, it would be great if the folder structure and repos in a workspace could be auto-detected. 😀 See https://github.com/microsoft/vscode/issues/87888.)

Just giving some context and hoping this can be taken account of in future planning.

I appreciate your reply. Happy 2020!

**Comment by joshbmarshall** [comment]
This looks similar to #76904 maybe you can combine the two and get more upvotes

**Comment by eine** [comment]
@joshbmarshall, thanks for bringing the ref! @markfinlabs, as you see, I opened #76904 to hopefully cover use cases as yours. Since both issues are candidates for the backlog, and  #76904 has about a dozen positive reactions already, I'd be glad if you could upvote it and, ideally, redirect potential users interested on this feature.

**Comment by markfinlabs** [comment]
> @joshbmarshall, thanks for bringing the ref! @markfinlabs, as you see, I opened #76904 to hopefully cover use cases as yours. Since both issues are candidates for the backlog, and #76904 has about a dozen positive reactions already, I'd be glad if you could upvote it and, ideally, redirect potential users interested on this feature.

Sure, have upvoted.
