### ISSUE TITLE
Cursor looks strange when it is in certain area under the title bar

### ISSUE THREAD

**Issue by Northurland** [microsoft/vscode#87883]
- VSCode Version:1.41.1 (language: Chinese simplified)
- OS Version: Windows 10, Enterprise LTSC, 1809, 17763.914

Steps to Reproduce:

1. Open VSC
2. Open at least one file with VSC
3. Move your cursor to the area under the title bar and behind the files' labels
4. You see _this_, which is different from the usual hand-like icon (significantly rougher):
![ac863580284e1038139258f623fa81a](https://user-images.githubusercontent.com/40388212/71586817-6df25000-2b56-11ea-8812-fa87518aa411.jpg)
(sorry for photographing the screen. It seems that I can't catch this one using the screenshot tool... I have no other way but to photograph.)

Does this issue occur when all extensions are disabled?: **Yes**

(Probably the image is not loaded properly? ...If this is a _feature_ instead of a bug please ignore me... )

**Comment by bpasero** [comment]
The cursor indicates that you can pick the entire group and move it around in the editor grid.
