### ISSUE TITLE
Weird tabs auto scrolling behaviour?

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#8788]
- VSCode Version: 1.3.0 Insider
- OS Version: OSX

Steps to Reproduce:

1. I have opened multiple tabs in one single group editor
2. Scroll to the last tab in this group
3. Move the cursor into the editor part
4. The tab headers will scroll to left most automatically, which makes it difficult to right click the tab header to open context menu.

![tab-header](https://cloud.githubusercontent.com/assets/876920/16611456/f1cbb744-4393-11e6-9a62-960dcaed9b6f.gif)

It takes me minutes to record above gif as I can't right click the tab header successfully every time.

**Comment by bpasero** [comment]
@rebornix I am puzzled by this bug, having a hard time to understand it. you say the tabs start to scroll (slowly even?) when you do some action? like what?

**Comment by rebornix** [comment]
It's difficult for me to describe this issue as well. Please take a look at below gif, at first I opened more than 10 files in a single Group Editor. Then I double click `subparser.ts` from left side explorer, after that, I did nothing. Now if you look at the tabs header, you can see they are scrolling. I'm not sure if this a new feature or not, but to me, it's weird.

![tab-header-2](https://cloud.githubusercontent.com/assets/876920/16619766/23e21736-43c2-11e6-8ab4-60a38f34e68c.gif)

**Comment by rebornix** [comment]
It's difficult for me to describe this issue as well. Please take a look at below gif, at first I opened more than 10 files in a single Group Editor. Then I double click `subparser.ts` from left side explorer, after that, I did nothing. Now if you look at the tabs header, you can see they are scrolling. I'm not sure if this is a new feature or not, but to me, it's weird.

![tab-header-2](https://cloud.githubusercontent.com/assets/876920/16619766/23e21736-43c2-11e6-8ab4-60a38f34e68c.gif)

**Comment by rebornix** [comment]
Oh, it's a feature, you want to always reveal the active one and this feature is brought in by https://github.com/Microsoft/vscode/commit/3d469f88107cdde449af8c6a0f5907ea7871c493 . Now my problem is really easy to describe, I can not see the active tab title on the tab scrollbar.

**Comment by bpasero** [comment]
@rebornix whenever an editor opens or gets active, we scroll the active tab into view in the tabs container. however, we are not doing this in the way you see it. it should move quickly. see my video:

![untitled](https://cloud.githubusercontent.com/assets/900690/16620705/c2bb1404-4393-11e6-8c5f-da5cd4e8d4d7.gif)

**Comment by rebornix** [comment]
This doesn't happen with master build and latest Insider (updated this morning), this issue is already obsolete.

**Comment by bpasero** [comment]
@rebornix great, in fact I have seen it on a build that was not latest and cannot really explain it.

**Comment by chrmarti** [comment]
Not reproducible for me, marking verified.

**Comment by rebornix** [comment]
@chrmarti yes it's no longer there from 1.3.1.

**Comment by cdodge89** [comment]
Looks like this has regressed. I am on version 1.7.2 and am experiencing the same bug. If I navigate to a tab outside of the visible tabs, the tabs immediately begin scrolling back to the first open tab in the group.

**Comment by bpasero** [comment]
@cdodge89 do you have exact reproducible steps so that I can try to reproduce? Also do you still see this in our insider build where we updated Chrome from 52 to 53?  You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by cdodge89** [comment]
@bpasero unfortunately no, I don't have reproducible steps. Once I got it into that state it would do it regularly, but I restarted vscode and can't get it back to that state again. I've several things, but no luck. It is now working as expected though.
