### ISSUE TITLE
Copy paste does NOT paste on new line

### ISSUE THREAD

**Issue by programmerneo** [microsoft/vscode#87885]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

When I copy a line of code, with the carriage return, I would expect it to paste under the line, yet it pastes right after my cursor. I believe this issue is related to the previously reported issue, (now closed) ... [Command-C & Command-V does not duplicate the whole line #83003](https://github.com/microsoft/vscode/issues/83003) Although I am using Python and not Java as in the previously reported issue.

Thought I might help others with the work-around until this is fixed. Go into your settings and turn OFF .... "editor.formatOnPaste": false,

... this seems to fix the problem

**Comment by egamma** [comment]
The python extension implements the `formatOnPaste` behaviour, please report the issue with detailed steps against the python extension.
