### ISSUE TITLE
Go To Symbol does not display types

### ISSUE THREAD

**Issue by jeffijoe** [Microsoft/vscode#8789]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a `type`
2. Go To Symbol - the type does not appear

![image](https://cloud.githubusercontent.com/assets/2505474/16611714/51f80eb4-4363-11e6-897a-73b8d1d08bf1.png)

**Comment by dbaeumer** [comment]
Got addressed for 1.3.1.

![capture](https://cloud.githubusercontent.com/assets/1931590/16617880/7fc04b86-4386-11e6-8803-e7e207affdb2.png)

**Comment by jeffijoe** [comment]
Sweet, when will this be released?

**Comment by dbaeumer** [comment]
@jeffijoe next couple of days.
