### ISSUE TITLE
imports are auto sorting

### ISSUE THREAD

**Issue by ecabrera1** [microsoft/vscode#87898]
Issue Type: <b>Bug</b>

When I save my react *.js file the imports at the top auto sort and remove blank lines taking out any  formatting I've placed.

import React from 'react';
import { Button } from '@material-ui/core';

import styles from './main.scss';

TURNS INTO 

import styles from './main.scss';
import { Button } from '@material-ui/core';
import React from 'react'; 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have configuration for `editor.codeActionsOnSave` in User or Workspace settings?
See details [Run Code Actions on save](https://code.visualstudio.com/updates/v1_23#_run-code-actions-on-save)

Is it reproducible without extensions?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by mjbvz** [comment]
This is either caused by an extension or has been configured as @IllusionMH notes

**Comment by ecabrera1** [comment]
I uninstalled all plugins, ran it with extensions disabled and it still sorts my imports. I also uninstalled VSCode and reinstalled it and same issue. Not sure what else you need to know but it's pretty frustrating that I've used it for years. I have switched to Atom so that I can keep my structure correct.
