### ISSUE TITLE
Don't assume holidays == winter :)

### ISSUE THREAD

**Issue by davux** [microsoft/vscode#87890]
Hello,

It's very nice to get the Happy Holidays greeting. Thanks for that, happy holidays to you too!

I think it would be very nice for the half of the people who are in south hemisphere to get summer greetings. :)

Thanks and best regards.

- VSCode Version: 1.42.0-insider
- OS Version: macOS Catalina 10.15.2

Steps to Reproduce:

1. Clic bottom-left Cog icon
2. Select "Happy Holidays!"
3. Watch the snow over the window
4. Watch the sun through the window
5. Remember you're in south hemisphere

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by egamma** [comment]
@davux this is a great observation. However, since there will be no more builds during the holidays (pls see https://github.com/microsoft/vscode/issues/87455) there is no opportunity to address it.
