### ISSUE TITLE
Code not Being highlighted

### ISSUE THREAD

**Issue by AVCADO** [microsoft/vscode#87896]
I am writing a C# file, but on one specific function, nothing is being highlited. (No syntax highlighting) The only thing that is highlited is "new".

Expected result: Syntax highlighting
Actual result: Nothing highlighted
Image:
![image](https://user-images.githubusercontent.com/56693327/71595928-268ea400-2b03-11ea-96b6-952e2195cde2.png)

**Comment by alexr00** [comment]
Please provide a copy-pastable example I can test with.
