### ISSUE TITLE
Show full path on tab hover and window title in git diff 

### ISSUE THREAD

**Issue by iamdevlinph** [microsoft/vscode#87893]
With the introduction of `window.title` we can configure the title of VSCode. But when viewing a diff of a file, the full path is not shown

**Tab Hover**
![image](https://user-images.githubusercontent.com/19337229/71594173-dbf84080-2b71-11ea-8a87-75fd91aa7399.png)
**Window Title**
![image](https://user-images.githubusercontent.com/19337229/71594180-e1558b00-2b71-11ea-8f81-b1f75b1a13b0.png)

Can we make it behave just like when we open a file normally?

**Tab Hover**
![image](https://user-images.githubusercontent.com/19337229/71594259-31cce880-2b72-11ea-9370-d02059386c2c.png)
**Window Title**
![image](https://user-images.githubusercontent.com/19337229/71594264-36919c80-2b72-11ea-84a5-3b1d27f53689.png)

**Comment by joaomoreno** [comment]
This is currently not supported by the workbench, right @bpasero ?

**Comment by bpasero** [comment]
@isidorn @joaomoreno maybe talk, I think the label provider can do this that you can register for your custom file scheme for git.

**Comment by isidorn** [comment]
Yes, this should be supported by the labelProvider.
@joaomoreno just register rules for your git schema. Api pointer https://github.com/Microsoft/vscode/blob/f43c3601e5feb57cc4dfe9c033881f1886d1d7ff/src/vs/vscode.proposed.d.ts#L114

**Comment by joaomoreno** [comment]
@isidorn We looked into this back in December together and saw there is no support. I don't want to lose the `(Index)` suffix, and if I append it in a custom label, the Label won't render anything nicely.

**Comment by joaomoreno** [comment]
Oh this is already fixed. Sorry about that, been too long out.
