### ISSUE TITLE
c:\ws\src\node_file.cc:1485: Assertion `(argc) == (5)' failed.

### ISSUE THREAD

**Issue by Chatpard** [microsoft/vscode#87902]
Issue Type: <b>Bug</b>

Recently I installed a package: https://www.npmjs.com/package/readline-sync
when I run my app via node using debug, I get the error:
node.EXE[1900]: c:\ws\src\node_file.cc:1485: Assertion `(argc) == (5)' failed.
 1: 00007FF648D3124F napi_wrap+124431
 2: 00007FF648CD2A06 v8::base::CPU::has_sse+34502
 3: 00007FF648CD2D23 v8::base::CPU::has_sse+35299
etc.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.11
json2ts|Gre|0.0.6
csharp|ms-|1.21.9
debugger-for-chrome|msj|4.12.3
debugger-for-edge|msj|1.0.13

</details>

**Comment by egamma** [comment]
/needsMoreInfo

What version of node are you using, what version of readline-sync? Do you also get the error when you run the program from the command line?
