### ISSUE TITLE
Javascript no IntelliSense - V1.41.1

### ISSUE THREAD

**Issue by 1nfility** [microsoft/vscode#87900]
- VSCode Version: 1.41.1
- OS Version: Darwin x64 19.0.0 (Catalina 10.15.1)

I recently noticed that i no longer have IntelliSense on my Javascript using Visual Studio Code.
Funny enough, it works on Typescript files, just not on Javascript.

I have restarted my TS Server multiple times, checked the TS server logs and didn't find any errors, and made sure i had IntelliSense enabled.

Looks like others have the same issue, but where TypeScript doesn't have IntelliSense.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by hahuma** [comment]
I'm just having the same problem, it's just work when I'm inside of a HTML script tag...

**Comment by mjbvz** [comment]
Closing as needs more info from original poster
