### ISSUE TITLE
WebExtension api is not working in VSCode

### ISSUE THREAD

**Issue by agileselenium** [microsoft/vscode#87909]
Hi,

I'm new to VSCode tool. I'm trying to develop a extension with WebExtension api. When I type browser.runtime then it's not showing any functions. Can you please let me know why VSCode is not showing the functions for WebExtension api.

**Comment by jrieken** [comment]
vscode extension don't run inside a browser context but inside a Node.js context. To access [vscode-apis](https://code.visualstudio.com/api/references/vscode-api) you can call `require('vscode')`
