### ISSUE TITLE
The solution to the problem of intellisense not working

### ISSUE THREAD

**Issue by VitaminCtea** [microsoft/vscode#87905]
If you have intellisense failure in React files or (js, ts) files, there are two solutions to the problem of intellisense not working:

1. Back to version 1.40, and then disable automatic updates in the settings.json file.

2. If you're friends with version 1.41, you can fix the problem by installing the [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) plugin

> **Self test, both are effective.** I hope I can help others who have the same problem as me

**Comment by KushagraPan** [comment]
Installed the plugin still not working, even the autocomplete isn't working now. The tags are auto-closing either.
https://github.com/microsoft/vscode/issues/87955

**Comment by VitaminCtea** [comment]
@KushagraPan These are the only two options I know of.

**Comment by KushagraPan** [comment]
@VitaminCtea can you tell me how to completely uninstall vs code. Then it may work. Have tried total uninstaller, still, old config files remained. So whenever I reinstall, it opens up with the old set up

**Comment by VitaminCtea** [comment]
@KushagraPan 

> **After making sure to uninstall the vscode program, try the following steps:**

1. Delete the. vscode folder. The default path is in the user directory.(All extensions in vscode)

2. Find the path:  C:User/AppData/Roaming/Code/User, delete all files under this path. (Remove the vscode global configuration file and user customization file)

3. Find the path: C: Users/AppData/Local/Programs, delete the Microsoft VS Code folder.

The demo paths  in steps 1 and 2 are in the user directory, even though the install vscode path is not the default.

The third step is variable, because everyone's installation path is different, so just find the installation path and delete the Microsoft VS Code folder.

Complete all the above steps, and then install vscode again, it will be a brand new vscode!

> **Note: Before you complete all the steps above, back up any extensions you install! Otherwise, once all the above steps have been completed, the operation will not be reversible!!**

**Comment by VitaminCtea** [comment]
@KushagraPan 
If you installed version 1.41 and installed the recommended extensions, intellisense doesn't work,
try backtracking to version 1.40.

**Comment by KytoSai** [comment]
Thank you, i have same issue. I can fix it the way you have instructed

**Comment by baozi510** [comment]
就用这个扩展可以解决这个问题，不懂为什么这么严重的问题，不是修复。每天都看有没有新版本发布。
