### ISSUE TITLE
Conditional BreakPoint Debug

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#87907]
Issue Type: <b>Bug</b>
![image](https://user-images.githubusercontent.com/27731323/71608252-cbb88380-2bba-11ea-8fc7-92dce7bddeed.png)

I can't use it either==

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
toolkit-vscode|ali|2019.11.1
vscode-bazel|Baz|0.3.0
emojisense|bie|0.5.3
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.33.0
java-decompiler|dgi|0.0.2
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.15
shell-format|fox|7.0.0
vscode-lombok|Gab|0.9.9
beautify|Hoo|1.5.0
java-properties|ith|0.0.2
asciidoctor-vscode|joa|2.7.7
docthis|joe|0.7.1
intellij-idea-keybindings|k--|0.2.37
vscode-osgi|lgd|1.0.2
vscode-json5|mrm|1.0.0
vscode-docker|ms-|0.9.0
vscode-language-pack-zh-hans|MS-|1.41.2
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
vscode-remote-extensionpack|ms-|0.19.0
vscode-react-native|msj|0.13.2
sqltools|mtx|0.21.5
vscode-versionlens|pfl|0.24.0
vscode-spring-boot|Piv|1.14.0
material-icon-theme|PKi|3.9.2
java|red|0.55.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.6.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscode-checkstyle|she|1.3.2
vscode-leetcode|she|0.15.8
perforce|sle|3.2.0
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
vscode-spring-boot-dashboard|vsc|0.1.7
vscode-spring-initializr|vsc|0.4.6
vscode-icons|vsc|9.7.0
vscode-wakatime|Wak|2.2.1
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.6.1
material-theme|zhu|3.2.1

</details>

**Comment by egamma** [comment]
It looks like you are using the Java extension. Please report the issue against the Java extension.
