### ISSUE TITLE
wsl  Explorer does not update the list of files in a timely manner

### ISSUE THREAD

**Issue by PlutoCA** [microsoft/vscode#87908]
Issue Type: <b>Bug</b>

wsl 在命令窗口用mkdir等命令创建文件夹或者文件 资源管理器并不会对文件列表及时更新

wsl Create a folder or file with a command such as mkdir in the command window. Explorer does not update the file list in time.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.90GB (7.87GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.14.4
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
path-autocomplete|ion|1.13.3
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.41.2
vscode-typescript-tslint-plugin|ms-|1.2.3
minapp-vscode|qiu|2.2.2
vscode-scss-formatter|sib|1.4.3
vscode-import-cost|wix|2.12.0
better-comments|aar|2.0.5
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
vscode-react-typescript|inf|1.3.1
vscode-language-pack-zh-hans|MS-|1.41.2
remote-wsl|ms-|0.41.6
sublime-keybindings|ms-|4.0.6
debugger-for-chrome|msj|4.12.3
material-icon-theme|PKi|3.9.2
js-jsx-snippets|sky|10.0.0
material-theme|zhu|3.2.1

(5 theme extensions excluded)

</details>

**Comment by egamma** [comment]
@PlutoCA I assume you are using WSL1? This issue has been addressed in WSL2.
For WSL please see this blog https://devblogs.microsoft.com/commandline/tips-and-tricks-for-linux-development-with-wsl-and-visual-studio-code/ and the section 'Work Around For Renaming Folders' for how you can tune the polling behaviour in WSL1.
