### ISSUE TITLE
Source Control Providers view: support for more than 10 providers without vertical scrolling

### ISSUE THREAD

**Issue by markfinlabs** [microsoft/vscode#87906]
Please allow the Source Control Providers view to expand (when space is available) to show all providers without vertical scrolling. In my case only 10 repos are shown; scrolling is required to see the remainder. I have about 20 repos in my workspace and it's annoying to need to scroll the source providers view to see many repos (despite plenty of empty vertical space below).

**Comment by gjsjohnmurray** [comment]
Have you investigated the `scm.providers.visible` setting? If so, what value are you using?

**Comment by markfinlabs** [comment]
Great call! I set the value to "50" and problem solved. Sorry to not be aware of this setting, I did not expect a UI component to have a fixed max size controlled by settings. Thanks again.
