### ISSUE TITLE
[razor] Property indexer mess up code highlighting

### ISSUE THREAD

**Issue by tfsjohan** [Microsoft/vscode#8790]
- VSCode Version:
  1.2.1
- OS Version:
  OSX El Capitan

When using indexers to access properties, the syntax highlighting stops working for the rest of the document. I use @inject IViewLocalizer Localizer and then in the code @Localizer["SomeKey"]. This causes the styling to be wrong. It seems to work better with @Localizer.SomeMethod("SomeKey")

Have a look at the attributes on the form tag below.

![skarmavbild 2016-07-06 kl 10 40 35](https://cloud.githubusercontent.com/assets/860380/16612223/21626602-4366-11e6-9968-a20917f955e8.png)

**Comment by aeschli** [comment]
@tfsjohan Can you paste the code snippet? Thanks!

**Comment by tfsjohan** [comment]
As you can see on the screenshot in the original thread coloring of attributes in the form tag are wrong.

```
@model CloudQR.ViewModels.LoginViewModel
@inject IViewLocalizer Localizer;
@{
    ViewData["Title"] = "Cloud QR";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">

            <h1>@Localizer["PageTitle"]</h1>

            <form asp-controller="Account" asp-action="LoginWebForm" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <input type="hidden" name="redirectUrl" value="/"/>
                
                @Html.EditorFor(x => x.Email)
                @Html.EditorFor(x => x.Password)
                @Html.EditorFor(x => x.RememberMe)

                <button type="submit" class="btn btn-lg btn-primary">@Localizer["LoginButton"]</button>
            </form>
            
            <hr>

            <a asp-controller="Account" asp-action="Signup">@Localizer["SignupButton"]</a><br>
            <a asp-controller="Account" asp-action="ResetPassword">@Localizer["ResetPasswordButton"]</a>
        </div>
    </div>
</div>
```

**Comment by aeschli** [comment]
This seems to work now (Tried in VSCode 1.10 insiders build)
