### ISSUE TITLE
Typescript knows generic paramater's type but Intellisense doesn't display it's properties

### ISSUE THREAD

**Issue by Ed-zo** [microsoft/vscode#87903]
Issue Type: <b>Bug</b>

When I'm tring to use a function with generic parameter Intellisense does not show the properties of a specific type. VS Code and also typescript transcription do throw an error that the parameter is missing some properties but Intellisense is not aware of those properties. It works only when I use `as` keyword casting.

VS Code is aware of parameter's type:

![image](https://user-images.githubusercontent.com/15330300/71605392-d5190000-2b68-11ea-8bfb-5259c0319f24.png)

![image](https://user-images.githubusercontent.com/15330300/71605306-1f4db180-2b68-11ea-87d4-db119010d80d.png)

But Intellisense does not shows it's properties:

![image](https://user-images.githubusercontent.com/15330300/71605329-4b693280-2b68-11ea-9e67-6f2aa8a9878b.png)

Properties are suggested only when `as` is used:

![image](https://user-images.githubusercontent.com/15330300/71605344-6b005b00-2b68-11ea-8455-976f3d9953b9.png)

This is the code that I have tested it on:

```Typescript
type RequestResponsePair<IN, OUT> = [IN, OUT];

interface RequestType {
    id: number,
    content: boolean
}

type GetRequest = RequestResponsePair<RequestType, number>;

function request<T extends RequestResponsePair<any, any>>(data: T[0]) {
    return new Promise<T[1]>((resolve, reject) => { });
}

request<GetRequest>({id: 1, content: true})
```
I have tested this with all extensions disabled. I suppose that is a bug and Intellisense should know about those properties.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
This works when using TypeScript@next (TS 3.8):

<img width="885" alt="Screen Shot 2020-01-06 at 3 40 12 PM" src="https://user-images.githubusercontent.com/12821956/71857039-e008ee80-309a-11ea-823b-72b541f33f07.png">

You can switch to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
