### ISSUE TITLE
More precise actions on save

### ISSUE THREAD

**Issue by MDHD-Yee** [microsoft/vscode#87917]
For example, `editor.formatOnSave` works only when I save the file manually, but `files.insertFinalNewline` works also on auto save. It's a bit confusing and we cannot find this difference from their description. I hope there is a way to control those actions in each situation.

BTW, the code below doesn't work. Actually I didn't figure out what is the correct usage of `editor.codeActionsOnSave` from the document. 

```json
"editor.codeActionsOnSave": {
    "files.insertFinalNewline": true,
},
```

**Comment by mjbvz** [comment]
Falls under #67147
