### ISSUE TITLE
Errors/warnings only shown for open files

### ISSUE THREAD

**Issue by jeffijoe** [Microsoft/vscode#8791]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a typescript project with a tsconfig
2. Open a file with no errors, see there are no errors in the project
    ![image](https://cloud.githubusercontent.com/assets/2505474/16612218/1bdf8c82-4366-11e6-9aad-2caa23a9f5af.png)
3. Open a file with errors, and the errors start popping up
    ![image](https://cloud.githubusercontent.com/assets/2505474/16612245/37ff3a98-4366-11e6-98b7-f82939f31ed7.png)

My tsconfig:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "outDir": "dist/",
    "rootDir": "src/",
    "allowJs": true,
    "sourceMap": true,
    "listFiles": true,
    "target": "es6",
    "jsx": "react",
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules",
    "dist",
    ".vscode",
    "test"
  ]
}
```

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/8201

**Comment by AltekkeE** [comment]
This was working for me in previous versions but isn't any more

**Comment by dbaeumer** [comment]
@AltekkeE not really. With the introduction of a 'reusable tab' UI in 1.3 we are more aggressive close buffers hence Errors disappear sooner. If in > 1.3 you close a file by clicking x in the working list or using Ctrl+Shift+W the errors disappeared as well. This is why we started the work on the TS project builder. If you want to have the 1.2 behaviour you can use the following setting:

```json
	"workbench.editor.enablePreview": false,
	"workbench.editor.enablePreviewFromQuickOpen": false
```
