### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by yuanzhenbd** [microsoft/vscode#87913]
Issue Type: <b>Bug</b>

为什么我 打开一个文件夹，就会导致codhelper进程CPU利用率达到100%，并且代码跳转失效

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.3
flatbuffers|gab|0.1.0
mssql|ms-|1.7.0
python|ms-|2019.6.24221

</details>

**Comment by y122972** [comment]
我这切换分支，提交代码也是

**Comment by egamma** [comment]
@yuanzhenbd please see this page for how to narrow down performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues
