### ISSUE TITLE
cant open viewColumn with anything above 2 via api

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#87910]
am trying to make an ext that save the currently opened tabs along with the column of each, so far all is good except that any viewColumn with number above `2` doesnt create any new columns and we end up with max 2 columns

### env
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

### Steps to Reproduce:
> am not sure if this is doable without an ext but here is what i have

1. using `vscode.window.showTextDocument`, try to open multiple docs with different `viewColumn` ex.'1,2,3,etc...`
2. either have a one document open or non, the behavior is the same
3. run the command in **step.#1** and watch the columns being created
4. only 2 columns at max are being created.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
The API function simply forwards the column. Unsure if there is some limit or if the extension needs to wait before an editor is showing (and the column existing...)

**Comment by ctf0** [comment]
> (and the column existing...)
after more testing, i found the issue.

- columns with numbers above 2 cant be created unless we have 1 & 2 groups already in place

sorry for that, i thought the editor will create the groups even if it will be an empty group.

aside from that, is there a way to know the position of the column ex.`top,bottom,right,left` ?

**Comment by bpasero** [comment]
Yes, groups have to be created to refer to them. There is a special group `ViewColumn.Beside` that can be used to open a group to the side of the currently active one. There are various commands you can run to create groups upfront, e.g. look for the commands from the keybindings editor:

![image](https://user-images.githubusercontent.com/900690/71767575-cab28980-2f0d-11ea-868a-4fd7b5884859.png)

**Comment by bpasero** [comment]
I also suggest you subscribe to https://github.com/microsoft/vscode/issues/15178
