### ISSUE TITLE
Why should I use English to report my question?

### ISSUE THREAD

**Issue by Ricky1986** [microsoft/vscode#87919]
Issue Type: <b>Bug</b>

My question is Why should I use English to report my question?
Why cant I use Chinese to report my question?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.6
vscode-language-pack-zh-hans|MS-|1.41.2
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.6
vscode-remote-extensionpack|ms-|0.19.0

</details>

**Comment by egamma** [comment]
@Ricky1986 your issue report is very valuable to us. Since only a few members of the development team understand Chinese such are report cannot get the attention it deserves. Therefore, please use English then everybody in the development team can jump in and participate in the resolution of the issue.
