### ISSUE TITLE
I want use vscode at Arch

### ISSUE THREAD

**Issue by WkBqVN** [microsoft/vscode#87915]
Issue Type: <b>Feature Request</b>

Dear Dev team
First thing im from vietnam so im not good at English, please mercy if i mistake on something.
The main thing i love vscode is it very useful in code. But i love arch linux too but my style is nothing just only command line. I log in in Arch and working with command line only. I use arch for coding with typing and no mouse nothing just command line. I suggest build vscode for somekind like "nano" in linux. Nano bad at code when have block ({ }) but if vscode can do it , it will help dev like me who like simple and clear high contrast very much.
At last thank you for listening. Goodday to work.
Regards

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by egamma** [comment]
please see https://snapcraft.io/install/code/arch
