### ISSUE TITLE
Extensions search is returning a surprising result

### ISSUE THREAD

**Issue by pitosalas** [microsoft/vscode#87929]
When I go to the "extensions" tab and ask for extensions matching "ruby" the number one hit is Prettier. However Prettier doesn't support ruby and more important, if I look at all the README of the Prettier extension, the word 'ruby' does not appear anywhere!

**Comment by egamma** [comment]
Cannot reproduce, these are the results I'm getting with the most popular Ruby extension appearing first.

![image](https://user-images.githubusercontent.com/172399/71625421-0f75b200-2be8-11ea-9c95-75614c165963.png)

**Comment by pitosalas** [comment]
I guess I wasn't clear. I meant inside vscode itself, in the extensions 'tab' there's a search box at the top.

It is easy to imagine that it's something about the state of my vscode install but it's a totally up to date install etc. I am just trying to understand.



Pito Salas
Brandeis Computer Science
Volen 134

**Comment by egamma** [comment]
This is the result when executing the query inside VS Code
![image](https://user-images.githubusercontent.com/172399/71626506-e0623f00-2bed-11ea-8c55-ed14eafade96.png)

I haven't seen any similar issue report.
Can you include a screenshot of what you are seeing.
