### ISSUE TITLE
Font ligatures setting not working in suggested text

### ISSUE THREAD

**Issue by joulev** [microsoft/vscode#87924]
- VSCode Version: 1.41
- OS Version: Windows 10 version 2004 build 19035.1000

I am using font Monaco, which is quite good, but the font ligatures is IMO not very good. So I turned off font ligatures using

```json
"editor.fontLigatures": false
```

However, the suggested text seems to be confused by this setting. Please see the screenshot below

![vscode](https://user-images.githubusercontent.com/44609036/71618898-5f5a7600-2bf4-11ea-8807-3f29fc3170e3.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@octref In the editor, when configuring `editor.fontLigatures: false`, we set `"liga" off, "calt" off`

**Comment by octref** [comment]
I can't reproduce this.

Ligature off:
![image](https://user-images.githubusercontent.com/4033249/76028278-20dc8280-5ee7-11ea-9e8b-456105c8c756.png)

Ligature on:
![image](https://user-images.githubusercontent.com/4033249/76028355-4cf80380-5ee7-11ea-8cdc-0b3c0f511e1b.png)

**Comment by joulev** [comment]
@octref Thanks, somehow it is already fixed. It works well now.

**Comment by roblourens** [comment]
Nothing to verify right?

**Comment by octref** [comment]
@roblourens Yeah nothing to verify.
