### ISSUE TITLE
ctrl+(left|right) arrow should jump to previous/next word boundry in a camel cased variable name/ method name.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#87923]
Issue Type: <b>Feature Request</b>

ctrl+(left|right) arrow should jump to previous/next word boundry in a camel cased variable name/ method name.
The current implementation jumps to the end of the entire variable name skipping all the camel cased word boundries in a given variable.
i tried to change the `Ediror: Word Separators` setting with which i faced 2 issues.
1. it does not accept the regex styled [A-Z], instead i have to give entire capitalized alphabate (not a big deal)
2. with this capical alphabate ctrl + right arrow seems to work fine, however, ctrl + left arrow has issues
Ex: for variable `thisIsATestVariable` 
ctrl + right arrow will traverse as -> this, Is, A, Test, Variable
ctrl + left arrow will traverse as -> ariable, V, est, T, A, s, I, this (i.e. each capitalized letter is considered as a separate word)

is there some setting i am missing?
can someone suggest a workaround/solution to this feature?
else vscode team please consider this feature request if its worth.

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-64-generic

**Comment by egamma** [comment]
This is supported pls see https://code.visualstudio.com/updates/v1_25#_subword-support
