### ISSUE TITLE
hover information window will be invisible occasionally when fast switch hovering between variables  

### ISSUE THREAD

**Issue by cloveris2012** [microsoft/vscode#87922]
- VSCode Version: 1.14.1
- OS Version: Windows 10

Steps to Reproduce:

1.  start debugging on a ts project
2.  hover over one variable
3.  hover over another variable
2-->3-->2

sometimes the hover information window will show like 0.1 second then disappeared
![hoverVscode](https://user-images.githubusercontent.com/19221777/71617969-83b85180-2bf8-11ea-8881-8e98feead67a.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Great catch, thanks for filling this issue!
I pushed a fix and this should be picked up by vscode insiders next week
