### ISSUE TITLE
Backslashes not recognized in Project Search "Files to Include" especially when pasted from "Copy Relative Path"

### ISSUE THREAD

**Issue by hughanderson4** [microsoft/vscode#87939]
Issue Type: <b>Bug</b>

1. Windows 10, open your favorite project with deep filestructure
2. Go to subfolder of project, right click it, choose "copy relative path"
3. move to Search tab (Shift + Ctrl + F)
4. paste relative path from step 2 into "files to include"
5. notice the path has "backslashes" `\`
6. search for something
7. notice there are zero results
8. change all the backslashes in "files to include" to forward slashes `/`
9. notice the search results populated

*Observed:* The path pasted from "copy relative path" command has backslashes, but the Project Search function didn't recognize backslashes

*Expected:* Can we please standardize on the right kind of slashes for my OS, or just recognize any kind of slashes?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.14.4
docthis|joe|0.7.1

</details>

**Comment by shogerr** [comment]
This is probably the desired behavior. On Windows, you have to remember they are the odd duck out with back slashes for paths. The search probably, and correctly, uses the backslash as an escape character. Try using '\\' to search for a back slash, and see if that works. Again, if this is the behavior, this is going to be intentional, and desirable.
