### ISSUE TITLE
Intellisense not working with Remote-WSL

### ISSUE THREAD

**Issue by Auersberg** [microsoft/vscode#87933]
- VSCode Version: 1.41.1
- OS Version: Windows 10.0.19041

Steps to Reproduce:

1. When editing a dockerfile in WSL 2 (Ubuntu distro) intellisense is not working ("No suggestions")
2. Doing the same in a local folder there is no problem

![grafik](https://user-images.githubusercontent.com/4933918/71626796-51562680-2bef-11ea-80e3-82db8a9ba181.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
/needsMoreInfo

@Auersberg have you installed the Docker extension inside the WSL container? To see where an extension is installed open the extension viewlet. Can you add screenshot of the extension viewlet that shows the Docker extension.

**Comment by Auersberg** [comment]
![grafik](https://user-images.githubusercontent.com/4933918/71644729-80db6080-2ccd-11ea-80bd-afa7a73cc8dd.png)

**Comment by Auersberg** [comment]
Thanks @egamma since you pointed me to the right direction. Intellisense is working now like expected.

**Comment by egamma** [comment]
@Auersberg great that it is working for you now, what did you change to make it work?
