### ISSUE TITLE
extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by mateenkhan007** [microsoft/vscode#87931]
Issue Type: <b>Bug</b>

Serveral time restarted, VS Code shows this error.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mateenkhan007** [comment]
When I open VS Code, there is message prompt extension host terminated unexpectedly. Since I get this error, In VS files my code not able to show any validation error, no import file prompt. no HTML or TypeScript error while coding.

![VS Error](https://user-images.githubusercontent.com/57237630/71626480-3b585e00-2c0f-11ea-9e54-0225d2ce3f61.jpg)

**Comment by egamma** [comment]
@mateenkhan007 thanks for the update. An extension host termination is most of the time caused by an extension. Can you narrow down which extension is causing the termination? You can selectively deactivation extensions in the Extensions Viewlet.

**Comment by ankitshah009** [comment]
Why is this issue closed? I am facing the exact same issue since the past few days and cannot figure out the extension causing the problem.

**Comment by connor4312** [comment]
We automatically close issues that have the `needs more info` label after several days if there's been no followup. If you're running into this issue, please follow Erich's suggestion and let us know.

**Comment by mateenkhan007** [comment]
Thanks Guys for the response, I followed the egamma's suggestions and removed extensions which were not required and made few disabled after this issue was resolved. Did'nt have idea which extension was exactly causing this.
