### ISSUE TITLE
Add setting bem.shortElementPrefix

### ISSUE THREAD

**Issue by nicothin** [microsoft/vscode#87936]
Please add support for Emmet setting `bem.shortElementPrefix`

```
    "emmet.preferences": {
        // some settings
        "bem.shortElementPrefix": "_", // ← this
        // some settings
    },
```

**Comment by octref** [comment]
https://github.com/microsoft/vscode/issues/54339#issuecomment-405318596

**Comment by nicothin** [comment]
?

BEM has more than one dialect.
I use a dialect in which `--` characters are used for the modifier. I'm not alone :)
Emmett has a setting, in the VS code it is not. This is strange.

**Comment by octref** [comment]
Can you point me to the BEM dialect you are using?

**Comment by nicothin** [comment]
https://en.bem.info/methodology/naming-convention/#two-dashes-style

The authors of this dialect are Harry Roberts and Nicolas Gallagher, as far as I remember.

**Comment by nicothin** [comment]
needs more info?

**Comment by rzhao271** [comment]
@nicothin I'm not sure if Emmet has that setting anymore (look through the `Options` interface)
https://github.com/emmetio/emmet/blob/master/src/config.ts

I believe this is therefore an upstream issue or feature request.
CC @sergeche

**Comment by sergeche** [comment]
In new version it's `bem.element` and `bem.modifier`

**Comment by rzhao271** [comment]
Actually, `bem.shortElementPrefix` used to be a third bem-related preference here https://docs.emmet.io/customization/preferences/

**Comment by sergeche** [comment]
Not sure what’s the use case of the problem you’re describing. In previous version, `bem.shortElementPrefix` was some sort of design flaw: it affected parser and was unclear for users. It’s like an option to redefine `.` for something else to set a class name for element.

When you enable BEM, you tell Emmet that leading `_` and `-` in class names has a special meaning so Emmet apply additional processing to produce another class names. The way how these class names should look like is described via `bem.element` and `bem.modifier` options.

**Comment by rzhao271** [comment]
Thanks! Marking the issue as out of scope.
