### ISSUE TITLE
API request to enable/disable extensions

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vscode#87935]
I work with several different web technologies, sometimes react sometimes flutter... If I install new extensions for flutter they are enabled when I switch to a workspace from a react project. My list of extensions is growing so I thought about making an extension that enables/disables extensions based on the technology used but I'm not sure this is possible with the current api. Is there a way to do this? If not can you add it?

**Comment by egamma** [comment]
@sketchbuch 

>I thought about making an extension that enables/disables extensions based on the technology

Can you elaborate or give an example one how you would leverage this API and enable/disable an extension based on the 'technology'?

**Comment by sketchbuch** [comment]
Hi, 

My plan would be to allow users to associate technologies used in a workspace (React, Flutter, Flowtype, Typescript, etc.) and specify which plugins should be enabled/disabled for that type of worksapce using those technolgies.

I have 30+ react workspaces, some using Typescript some using Flowtype, PHP workspaces, many Flutter workspaces and I want an extension that enables/disables the extensions that I have installed already so that for example all Flutter relevent extensions are disabled in the workspace if the workspace is associated with React. All typescript related extensions are disabled if the workspace is not Flowtype based. I would also have a group of extensions that should be enabled in every workspace - like line sorting plugins, syntax highlighters and so on.

My plan wouldn't be to install new extensions, just enable/disable existing intalled extensions on a workspace basis so that as many useless (for that workspace) extensions are switched off as possible. I think I have the user specify for each installed extension what type of worksapce it is for rather automating this by relying on tags in the extension as

- 1: Not everyone tags their extesions
- 2: Some people use the wrong tags

**Comment by sandy081** [comment]
/duplicate

#57548
