### ISSUE TITLE
The text wrap display issues in Visual Studio Code

### ISSUE THREAD

**Issue by GaussSpace** [microsoft/vscode#87932]
Issue Type: <b>Bug</b>
Reproduction steps：
1. Open the web page and copy a paragraph that contains multiple lines of text.
2. Create an HTML file in the Visual Studio Code, add a p tag, and paste the contents of the pasteboard into the p tag.
3. The Visual Studio Code displays the copied multi-line text as one line.

Question: I want Visual Studio Code to display the text I copied like the line break format that appears on the Web page, but Visual Studio Code merges them into one line. Is there any way to solve this problem?
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
vscode-caniuse|aga|0.5.0
vscode-javascript-snippet-pack|aka|0.1.5
TabOut|alb|0.1.6
project-manager|ale|10.9.1
color-info|bie|0.5.1
lit-html|bie|1.11.1
path-intellisense|chr|1.4.2
EnglishChineseDictionary|Cod|0.0.11
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.33.0
vscode-faker|dee|1.3.0
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
vsc-material-theme-icons|equ|1.0.6
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|3.18.0
file-icons|fil|1.0.20
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.15
beautify|Hoo|1.5.0
icon-fonts|idl|2.2.3
vscode-pigments|jas|2.0.0
docthis|joe|0.7.1
vscode-clangd|llv|0.0.19
vscode-language-babel|mgm|0.0.25
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.6.0
vscode-filesize|mkx|2.1.3
vscode-language-pack-zh-hans|MS-|1.41.2
cpptools|ms-|0.26.2
debugger-for-chrome|msj|4.12.3
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
emoji|Per|0.0.3
material-icon-theme|PKi|3.9.2
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|0.11.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.0
html5-boilerplate|sid|1.0.3
swdc-vscode|sof|1.3.9
code-spell-checker|str|1.7.20
sass-indented|syl|1.7.1
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.2
vscode-icons|vsc|9.7.0
gitblame|wad|3.0.1
quokka-vscode|Wal|1.0.267
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
markdown-pdf|yza|1.4.1
markdown-all-in-one|yzh|2.6.1
material-theme|zhu|3.2.1
html-css-class-completion|Zig|1.19.0

(6 theme extensions excluded)

</details>

**Comment by octref** [comment]
@GaussSpace When you selected the multiple lines, it's wrapped by browser but its content is single line, so pasting would result in one line.
