### ISSUE TITLE
BOLD style of colored theme bahaved unexpectedly on Windows

### ISSUE THREAD

**Issue by noisnemid** [microsoft/vscode#87930]
Issue Type: <b>Bug</b>

fonts got wider than normal on windows when the color theme make a bold sytle to the source files, such as:

colored theme DARK / DARK +,

in dark_vs.json, line:119, there is a config:
"fontstyle":"bold"

eg, in a rst file, I got codes like this:
```
aaaaaaaaaaaaaaaaaaaaaaaa
========================
```

on linux(Ubuntu 19.10, same versioned VSCode, extension, fonts...),
 with the same colored theme, they align correctly.

but on windows, they are wider!

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_10 x64 10.0.17763

|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tree-view|Cha|2.6.0
vscode-eslint|dba|2.0.11
githistory|don|0.4.12
vscode-highlight|fab|1.3.4
restructuredtext|lex|116.0.0
vscode-language-pack-zh-hans|MS-|1.41.2
python|ms-|2019.11.50794
vscode-table-formatter|shu|1.2.1
code-spell-checker|str|1.7.20
open-in-browser|tec|2.0.0
local-history|xyz|1.7.0

</details>

**Comment by noisnemid** [comment]
![linux-bad](https://user-images.githubusercontent.com/16525011/71625433-c8f17900-2c22-11ea-8e54-04d5c9f3e415.png)
![linux-good](https://user-images.githubusercontent.com/16525011/71625434-c98a0f80-2c22-11ea-8115-d57c4417e6f6.png)
![windows-bad-1](https://user-images.githubusercontent.com/16525011/71625435-ca22a600-2c22-11ea-81cc-94e9dd48a346.png)
![windows-bad-2](https://user-images.githubusercontent.com/16525011/71625437-ca22a600-2c22-11ea-804d-96c5a6029261.png)
![linux-good-1](https://user-images.githubusercontent.com/16525011/71625439-cabb3c80-2c22-11ea-9954-716ed258b3ea.png)

**Comment by noisnemid** [comment]
is this a machine-ralated problem or operating system ralated problem, or only some thing about VS CODE?

**Comment by alexdima** [comment]
This is defined by the font. I cannot offer any explanation as to why different Operating Systems render the same font in different ways. I have found that sometimes these fonts ship bold and italic variants and unless I install them, the OS will try to guess how bold or italics should render.

In any case, the width of a character is driven by the font. So my recommendation is to use another font or customize token types via user settings and remove boldness from the affected tokens.

**Comment by noisnemid** [comment]
> 
> 
> This is defined by the font. I cannot offer any explanation as to why different Operating Systems render the same font in different ways. I have found that sometimes these fonts ship bold and italic variants and unless I install them, the OS will try to guess how bold or italics should render.
> 
> In any case, the width of a character is driven by the font. So my recommendation is to use another font or customize token types via user settings and remove boldness from the affected tokens.

Thanks for replying.
At this moment  I guess that's might because the fonts I tested had not different font-weight versions and this made Windows confused about how to render bolded glyphs and used some default solutions, while Linux's solutions were different from Windows'...
