### ISSUE TITLE
Snippet Variables within a Choice Block

### ISSUE THREAD

**Issue by minig0d** [microsoft/vscode#87949]
Unless I'm just messing up the syntax, it seems like within the snippet choice syntax, only string literals are supported.  I'm basically trying to accomplish this:

`"${1| ${TM_SELECTED_TEXT}, ${TM_CURRENT_LINE}, ${CLIPBOARD} |}"`

When the snippet is inserted, have the choice between using the selected text, the entire line, or the contents of the clipboard.

I'm sure that with regex I could come up with some kind of logic for most common scenarios but I can envison other use cases where being able to use variables as choices would be extremely beneficial (ex. maybe choice between construction of date formats ).

**Comment by ArturoDent** [comment]
It seems like a good request.  I would say it is not currently supported by looking at the snippet grammar though:

[placeholder ::= '${' int ':' any '}'
choice      ::= '${' int '|' text (',' text)* '|}](url)

So a `choice` element can only take text and not a `placeholder`.

**Comment by jrieken** [comment]
That's not part of the Textmate snippet syntax and we try to be compatible with that, e.g not add features that won't be supported elsewhere.
