### ISSUE TITLE
Charchter 'k' not typed in editor

### ISSUE THREAD

**Issue by Devahmed93** [microsoft/vscode#87940]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Devahmed93** [comment]
the editor accept all charterer to type except character 'k' on editor

**Comment by IllusionMH** [comment]
Works on my computer just fine.

Please provide more info about your setup (VSCode and OS versions), extensions list. Everything that was in report that was not pasted in initial post.

Moreover is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

And do if you have any Shortcuts bound to this key?
