### ISSUE TITLE
Issues following extension getting-started documentaiton.

### ISSUE THREAD

**Issue by baileyn** [microsoft/vscode#87941]
**EDIT**  There is a video illustrating the issue in this comment https://github.com/microsoft/vscode/issues/87941#issuecomment-570832469

I'm following the Getting Started documentation for creating extensions located here: https://code.visualstudio.com/api/get-started/your-first-extension

1. Run `yo code` command.
```text
PS D:\Nicholas\git> yo code                                                                                             
     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Visual  │
    |--(o)--|    │   Studio Code Extension  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What type of extension do you want to create? New Extension (TypeScript)
? What's the name of your extension? HelloWorld
? What's the identifier of your extension? helloworld
? What's the description of your extension?
? Initialize a git repository? Yes
? Which package manager to use? npm
   create helloworld\.vscode\extensions.json
   create helloworld\.vscode\launch.json
   create helloworld\.vscode\settings.json
   create helloworld\.vscode\tasks.json
   create helloworld\src\test\runTest.ts
   create helloworld\src\test\suite\extension.test.ts
   create helloworld\src\test\suite\index.ts
   create helloworld\.vscodeignore
   create helloworld\.gitignore
   create helloworld\README.md
   create helloworld\CHANGELOG.md
   create helloworld\vsc-extension-quickstart.md
   create helloworld\tsconfig.json
   create helloworld\src\extension.ts
   create helloworld\package.json
   create helloworld\tslint.json


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN helloworld@0.0.1 No repository field.
npm WARN helloworld@0.0.1 No license field.

added 121 packages from 582 contributors and audited 288 packages in 9.512s
found 0 vulnerabilities


Your extension helloworld has been created!

To start editing with Visual Studio Code, use the following commands:

     cd helloworld
     code .

Open vsc-extension-quickstart.md inside the new extension for further instructions
on how to modify, test and publish your extension.

For more information, also visit http://code.visualstudio.com and follow us @code.
```
2. Open the project in Code
```text
PS D:\Nicholas\git> code .\helloworld\ 
```
3. Run the extension by pressing `F5`. I get the following error:
![A terminal process terminated with exit code 1](https://njbailey-files.s3.amazonaws.com/errormessage.png)
4. In the Extension Host Development Code process, try to execute the extension with `Ctrl-Shift-P` "Hello World". I get the following error:
![Files cannot be found](https://njbailey-files.s3.amazonaws.com/extensionerror.png)

I haven't modified any of the files from what was generated via `yo code`. It seems like the `out` directory isn't being created when I execute the extension which is causing the issue. I manually ran `npm run watch` and the out directory gets created and the extension successfully shows a "Hello World!" popup.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.17GB free)|
|Process Argv|.\helloworld\|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|10.2.0
vscode-lombok|Gab|0.9.9
vscode-cfn-lint|kdd|0.10.2
ra-lsp|mat|0.0.1
vscode-typescript-tslint-plugin|ms-|1.2.3
indent-rainbow|ode|7.4.0
java|red|0.55.1
vscode-yaml|red|0.6.1
indenticator|Sir|0.6.0
vscode-lldb|vad|1.4.5
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1

</details>

**Comment by baileyn** [comment]
Also, after manually executing the `npm run watch` command, I still receive the "The terminal process terminated with exit code: 1" error whenever I debug the extension via `F5`.

**Comment by egamma** [comment]
/needsMoreInfo

I cannot reproduce this issue following the steps above. So I suspect this is related to your current setup and settings and how you have configured your default shell.

Can you open the internal terminal and use it when you do not do extension development?

To try this out in fresh setup you could install vscode-insiders https://code.visualstudio.com/insiders/ and try the steps again (using `code-insiders` instead of `code`).

**Comment by baileyn** [comment]
I still get the same issue using Insiders: https://njbailey-files.s3.amazonaws.com/issue.mp4

There's no issues opening the internal terminal using Ctrl-` in either Insiders or release versions.

**Comment by baileyn** [comment]
This seems to only happen if the extension is set for TypeScript. If I use JavaScript, then I am able to execute the extension without issue.

**Comment by egamma** [comment]
@baileyn thanks for providing the video (I've tried to repro on OS X and it works for TS).

What happens is that the build of the extension fails and therefore the .js files of the extension are not available and the extension cannot load. 

It looks like the `preLaunchTask` fails for some reason.

**Comment by alexr00** [comment]
@baileyn did you do an `npm install` in your folder yet?
For this https://github.com/microsoft/vscode/issues/87941#issuecomment-569976628 does that mean you opened the terminal in VS Code then ran `npm run watch`?

**Comment by baileyn** [comment]
@alexr00 yes it works fine from the VS Code terminal. I do have to cd into the working directory after opening the terminal before executing `npm run watch`. Could it be using the wrong working directory? It seems to default to `$HOME`.

**Comment by alexr00** [comment]
@baileyn it could certainly be the wrong working directory. When you open your helloworld folder in VS Code, then open the terminal it is defaulting to `$HOME`? It should be defaulting to the helloworld folder you have open in VS Code. Can you confirm this with the insiders build, since you shouldn't have any settings set there?

**Comment by baileyn** [comment]
@alexr00 yes I can confirm on Insiders it's also defaulting to `$HOME` when I open the terminal from the helloworld folder.

**Comment by alexr00** [comment]
@baileyn can you share your settings.json file for your new Insiders install? I assume its basically empty, but maybe something is getting set there.

**Comment by baileyn** [comment]
@alexr00 the workspace `settings.json` is
```
// Place your settings in this file to overwrite default and user settings.
{
    "files.exclude": {
        "out": false // set this to true to hide the "out" folder with the compiled JS files
    },
    "search.exclude": {
        "out": true // set this to false to include "out" folder in search results
    },
    // Turn off tsc task auto detection since we have the necessary tasks as npm scripts
    "typescript.tsc.autoDetect": "off"
}
```

The user `settings.json` is
```
{
}
```

**Comment by alexr00** [comment]
@Tyriar the terminal (not just tasks) is starting with the `$HOME` cwd even though VS Code has a folder open. Most relevant info copied:
- There are basically zero settings set since @baileyn doesn't normally use insiders: https://github.com/microsoft/vscode/issues/87941#issuecomment-571670697
- Video of setup (just uses yo generator): https://youtu.be/AflAg1T5Ylo
- Definitely happens with just the terminal, and is probably the thing causing a problem with tasks: https://github.com/microsoft/vscode/issues/87941#issuecomment-571263604

**Comment by baileyn** [comment]
I apologize. I've resolved the issue. The issue was actually some configuration in my `profile.ps1` configuration for PowerShell.
