### ISSUE TITLE
"editor.autoSurround": "both"

### ISSUE THREAD

**Issue by shelbykauth** [microsoft/vscode#87950]
The Setting "editor.autoSurround" has the following options:
- "languageDefined"
- "never"
- "brackets"
- "quotes"

There should be a fifth option: "both" or "always"

bxt requested the same here... https://github.com/microsoft/vscode/issues/32616#issuecomment-481184485 in April 2019
Issue #32616 was marked as verified and closed in October 2019, but it is not working now.

Plain Text appears to support both, but when enabling any Vue Extension for instance, trying to surround the selection with quotes fails.  Instead, it replaces the text with only half of the pair.  Meanwhile brackets still works.

I'd like to be able to do both, separately from the language definition.  It seems odd that I can do one or the other but not both.

<img width="423" alt="Screen Shot 2019-12-31 at 9 38 49 PM" src="https://user-images.githubusercontent.com/10117276/71637642-fbe14000-2c15-11ea-8ec8-d10722a5aae4.png">
<img width="673" alt="Screen Shot 2019-12-31 at 9 38 10 PM" src="https://user-images.githubusercontent.com/10117276/71637643-fbe14000-2c15-11ea-95e4-48bd582e6a85.png">

**Comment by ZYinMD** [comment]
I agree with adding a "both" option. What I experienced is that auto-surround doesn't work in Makefiles (*.mk).

**Comment by ZYinMD** [comment]
Hi @alexdima , thanks for the explanation! Just want to clarify: if a language doesn't define any auto surround pairs, but does define brackets (for instance [makefile](https://github.com/microsoft/vscode/blob/1018bfac9c969c9caa4586b09314fbf7c3fcf158/extensions/make/language-configuration.json) , then in that language we'll have auto-surrounding behavior on those brackets, but not on quote marks. Is that correct?

**Comment by alexdima** [comment]
@ZYinMD Yes, here is the fallback logic:
* if `surroundingPairs` are missing, the `autoClosingPairs` are used -- [here](https://github.com/microsoft/vscode/blob/7c069dff35b9165b441b9bd705ffb343f1ff7164/src/vs/editor/common/modes/supports/characterPair.ts#L35)
* But `autoClosingPairs` themselves fall back to `brakcets` if they are missing -- [here](https://github.com/microsoft/vscode/blob/7c069dff35b9165b441b9bd705ffb343f1ff7164/src/vs/editor/common/modes/supports/characterPair.ts#L22)

All in all, for makefile, those brackets end up defining both `autoClosingPairs` and `surroundingPairs`. It would be great if you could create an issue or a PR and define those with something that is sensible for makefile.
