### ISSUE TITLE
Allow to set explorer.autoReveal per specific folder

### ISSUE THREAD

**Issue by elucidsoft** [microsoft/vscode#87956]
Issue Type: <b>Feature Request</b>

node_modules will constantly expand itself in the Explorer, especially if your defining definitions.  I typically never want this, I think an exception should be made for showing what file is open if its in node_modules to keep the folder collapsed unless I explicitly expand it.  

The reason it's a problem is because there are so many files in node_modules you have to collapse it to keep developing, as it's completely useless in most cases to have it expanded and it pushes your work files off screen.

Proposition:
- Never expand node_modules implicitly
- If goto definition is used into a node_module, go there but do not older current folder state (if its collapsed keep it collapsed, if it was explicitly expanded by user keep it).
- This behavior applies very specifically to node_modules only.

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:58:23.119Z)
OS version: Linux x64 5.3.0-24-generic

**Comment by isidorn** [comment]
This is a fair feature request, renaming to make it more general and not javascript specific.
We do not have it on our immedaite plan, thus assigning to backlog candidates.
As a workaround you can use `explorer.autoReveal: false` however that will disable this for all folders.

Alternative way to achieve this in the future is if we allow to define settings per subfolder.

**Comment by joelday** [comment]
@isidorn Would you accept a PR for this?

**Comment by joelday** [comment]
@elucidsoft Do you mind pulling this down, building it and testing it out?

**Comment by elucidsoft** [comment]
Yes I'll pull it down and check it out.

**Comment by isidorn** [comment]
@joelday no I would not accept a PR for this yet. I am still not sure we want this feature to be a part of the vscode core expereince.
If you would like to provide PRs please search for issues tagged with "Help Wanted".

**Comment by joelday** [comment]
@isidorn no problem!

**Comment by patarapolw** [comment]
My thought on alternative implementation, would be to focus on larger folders.

**Do ellipsis** beyond 20 entries or something, rather than totally expand it.

It should be implemented by default, especially for

- `node_modules/`
- `.venv/`
- <https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types>

**Comment by opudalo** [comment]
@isidorn What's the status here? 
You mentioned that no external help is accepted on this issue, but many people experience problems with current behavior. 
And as per bot response here, in March it was moved to team backlog. That's almost a year ago.

**Comment by isidorn** [comment]
Status: no progress.

**Comment by ShlomiRex** [comment]
oof
this really frustrates me... it opens node_modules and dist directories with tons of files and I can't do anything but to scroll up for 3 years and closing it

**Comment by vhesener** [comment]
Although I too want to see this feature, a small workaround for those interested.. If you find yourself in scrolly hell, click on one of the items in `node_modules` and hit your left arrow key a bunch of times. This collapses everything until `node_modules` is completely collapsed.

**Comment by benji011** [comment]
@vhesener 

Two workarounds I found was either:

1. _preferences_ → _settings_ then filter by keyword `autoreveal` and set from `true` to `false` (screenshot below(

![image](https://user-images.githubusercontent.com/6195689/109242961-66443f00-781f-11eb-809a-3d00061b24eb.png)

2. Open your `settings.json` and add `explorer.autoReveal": false`

```json
  "explorer.autoReveal": false
```

**Comment by GitKokoszka** [comment]
Why is this still not added to the VSC? The auto revealing node_modules is a dev nightmare and switching it off completely isn't a solution!

**Comment by elucidsoft** [comment]
My other suggested feature to add a right hand pane so you can have windows docked to the right hand side of VSCode.  Really convenient for people with Ultra Wide monitors, yeah that got enough votes to make it into product and here we are 2 years later with that one as well still in back and forth drama.  Pretty disappointed in Microsoft at how they treat such simple feature requests that the community wants to see but it gets caught up in politics and egos.

**Comment by ShlomiRex** [comment]
Behavioral suggestion:
Right click on folder -> Lock folding
This locks the folding / collapsing of a folder
(It's just a suggestion how a user will do it)

**Comment by superole** [comment]
@elucidsoft , were you able to test @joelday 's PR? did it work? And - while we're waiting for such useful features to not fall victim of procrastination in favor of useless glam like 'Product Icon Themes' - Would it be possible to make an extension with this functionality?

**Comment by adamburgess** [comment]
Another workaround in the meantime: https://marketplace.visualstudio.com/items?itemName=phobal.vscode-collapse-node-modules
It works by adding node_modules to the ignore list and then removing it, which makes vscode hide and restore it, effectively collapsing. (it does edit your .vscode/settings.json though, but I've made a PR to fix that)
that + statusbar-commands makes for a handy button:
![image](https://user-images.githubusercontent.com/7473960/113810036-bc0bef80-97ac-11eb-8503-ceaef2f3d138.png)

**Comment by peacechen** [comment]
Here's a proposal that should be simple to implement: Don't auto-expand any folders in `.gitignore`

That gives developers flexibility in choosing its behavior.

**Comment by vintprox** [comment]
> Here's a proposal that should be simple to implement: Don't auto-expand any folders in `.gitignore`
> 
> That gives developers flexibility in choosing its behavior.

@peacechen Nice! Can't believe it's still hanging there. So, where is the proposal? (Search fails me.)

**Comment by SimonDever** [comment]
@isidorn yet again personally deciding that this is not what the community wants. Don't expect a reason or explanation or movement on this @opudalo and @ShlomiRex, so many other issues [like this one](https://github.com/microsoft/vscode/issues/27286) that they've been assigned to haven't moved in years despite the demand and interest.

**Comment by FlashThePlayer** [comment]
Why is this still an open request? 
There are several really good behavior proposals and non of them gets a reaction or answer what so ever!
PR are also not accepted which really baffles me while a feature like this should be marginal to implement from my point of view.

**Comment by runia1** [comment]
I recently decided to try vscode after years of using intellij ides.  I like it but this single issue is probably a deal breaker for me.  After reading this thread and realizing there still isn't a setting to turn this off I'm a little shocked.  It's kinda crazy that it's the default behavior to begin with.

**Comment by MrEmanuel** [comment]
Excluding folders by using the same matching feature as in vscode search function would be good. So we could just define `node_modules` in `.vscode` or the settings UI. Comma separated for multiple values. 

![image](https://user-images.githubusercontent.com/7394415/127343989-32217acb-c2a9-41bc-ada2-abf1a41a0c00.png)

**Comment by kodeine** [comment]
I'm surprised this is still open and not updated.

**Comment by martincalvert** [comment]
Is this really not something that could be a plugin? Like if they are going to keep punting this idea can we achieve this functionality through a plugin?

**Comment by elucidsoft** [comment]
This right is the perfect example of Microsoft "open source".

**Comment by JacksonKearl** [comment]
I propose a new `explorer.autoReveal.exclude` setting with semantics similar to the existing exclude configurations: 
![image](https://user-images.githubusercontent.com/8586769/129296359-cace2040-a184-48a4-853a-885cca3b950a.png)

The default would perhaps be the `search.exclude` configuration, or something similar to what that one uses as a default (`"**/node_modules", "**/bower_components"`).

**Comment by craigcosmo** [comment]
can the dev get this shiet done? It's been bugging me so bad.

**Comment by xxczaki** [comment]
I'm actually surprised this has not been implemented yet. Seriously, why would I want to expand the whole node_modules folder just to see a single type definition?

**Comment by AlexReff** [comment]
Could we get some feedback as to what the status or current planning is for this? There are multiple good proposals here and clear interest from the community to offer a PR, if we could get confirmation it would be considered and accepted.

+1 on the 'do not auto-expand folders/files in .gitignore' as an easy QoL setting.

**Comment by JacksonKearl** [comment]
I will accept a PR which adds an `explorer.autoReveal.exclude` setting. This should work like the `files.exclude` and `search.exclude` settings, and be especially similar to the `search.exclude` setting, for instance by inheriting from `files.exclude` and excluding `"**/node_modules"` and `"**/bower_components"` by default. A good starting point would be to look around https://github.com/microsoft/vscode/blob/469640333f0cab03988e1c1aa2c196da348520ed/src/vs/workbench/contrib/files/browser/explorerService.ts#L265-L277

**Comment by webark** [comment]
@JacksonKearl what would the process be of changing the `explorer.autoReveal` setting from a boolean to a nested one? Is there a settings migration process? Would it be just the presence of the object be seen as truthy? Should a `explorer.autoReveal.enabled` setting be added?

**Comment by JacksonKearl** [comment]
The `explorer.autoReveal` setting should continue to accept `true|false|focusNoScroll`. 

Our configuration provider may reject introducing a new `explorer.autoReveal.exclude` key if theres an existing `explorer.autoReveal` key, not sure but I could see that happening. If so, the new setting should just be `explorer.autoRevealExclude`. 

If a given path matches the exclude setting no revealing code should run, regardless of the overall `explorer.autoReveal` (i.e. treat it as `false` temporarily).

**Comment by gomezvillegasdaniel** [comment]
> @vhesener
> 
> Two workarounds I found was either:
> 
> 1. _preferences_ → _settings_ (⌘ + ,) then filter by keyword `autoreveal` and set from `true` to `false`
> 
> ![image](https://user-images.githubusercontent.com/6195689/109242961-66443f00-781f-11eb-809a-3d00061b24eb.png)
> 
> 1. Open your `settings.json` and add `explorer.autoReveal": false`
> 
> ```json
>   "explorer.autoReveal": false
> ```

you have saved my time so much, thanks!

**Comment by kreftk** [comment]
Hiding `node_modules` from the sidebar can be a good workaround until this is added:

```json
"files.exclude": {
  "**/node_modules/": true
},
```

**Comment by adamdry** [comment]
> Here's a proposal that should be simple to implement: Don't auto-expand any folders in `.gitignore`
> 
> That gives developers flexibility in choosing its behavior.

Personally I'm not sure I'd want this. gitignoring folders and not wanting them to expand are 2 separate things IMO. You do have 64 positive emojis from the community though so I guess it'll work for most! :smiley: 

As another use case for this feature in general, I use [CDK for Terraform](https://github.com/hashicorp/terraform-cdk) which creates a `.gen/providers/aws` folder which I'm constantly `Ctrl + Clicking` into to see the definition of the configurations I can apply to AWS resources. This folder has 3,288 files in it!

The left arrow trick will save my mouse wheel for now. Thanks to the community for all the workarounds! :+1:

**Comment by rickvian** [comment]
once i dragged wrong folder inside the `node_module` because it auto expanded, and i have to go trough delete and rerun yarn install..

**Comment by SimonDever** [comment]
Okay, but you could have used ctrl+z there too.

**Comment by jzyrobert** [comment]
I've also hit the issue of not wanting to reveal `node_modules` plenty of times, so I've given this PR a go.
Have a look and leave any suggestions if you'd like

**Comment by benjaminblack** [comment]
Nothing to contribute here, just wanted to share my personal journey over the past hour:

1. finally getting frustrated enough at a persistently annoying issue to see if there is a solution
2. my initial resignation upon discovering the issue has been open for two years on GitHub
3. my growing excitement as I read through the comments
4. finally, elation upon discovering that a solution has been implemented and is due to be released in the next version.

It's the little things. So thank you.

**Comment by ireznik** [comment]
> Hiding `node_modules` from the sidebar can be a good workaround until this is added:
> 
> ```json
> "files.exclude": {
>   "**/node_modules/": true
> },
> ```

Thanks! Appreciate it! Now it behaves like I want it: it only shows the one file I want to see instead of the whole folder.

**Comment by septatrix** [comment]
@jzyrobert I would also greatly appreciate if there was an option like `true`/`false`/`ignore-preview` wherein the latter would ignore files which are opened in preview mode like explained in #140057

**Comment by DerGoogler** [comment]
> I propose a new `explorer.autoReveal.exclude` setting with semantics similar to the existing exclude configurations: ![image](https://user-images.githubusercontent.com/8586769/129296359-cace2040-a184-48a4-853a-885cca3b950a.png)
> 
> The default would perhaps be the `search.exclude` configuration, or something similar to what that one uses as a default (`"**/node_modules", "**/bower_components"`).

This was really helpful

**Comment by DerGoogler** [comment]
> I propose a new `explorer.autoReveal.exclude` setting with semantics similar to the existing exclude configurations: ![image](https://user-images.githubusercontent.com/8586769/129296359-cace2040-a184-48a4-853a-885cca3b950a.png)
> 
> The default would perhaps be the `search.exclude` configuration, or something similar to what that one uses as a default (`"**/node_modules", "**/bower_components"`).

This was really helpful

**Comment by benoitrongeard** [comment]
> Hiding `node_modules` from the sidebar can be a good workaround until this is added:
> 
> ```json
> "files.exclude": {
>   "**/node_modules/": true
> },
> ```

Exclude node_modules isn't the solution. Some extension, like intellisense for bootstrap needs to have node_modules inside vscode to scan it :/ If you exclude node_modules, you break this extensions :(

**Comment by elucidsoft** [comment]
Two years later....

**Comment by digimbyte** [comment]
build/repo folders need to consider condensing for VS code

like.. I'm not a VS code wizard, it's not communicated how I could set a 'files.exclude' property

> It gets tiring trying to follow all these cryptic commands and settings between IDE's
> I assume its some vscode folder or a file with a vscode/glob extention - but that's just me making assumptions from the conversation.

For user experience, I should be able to right click on a folder and set it to  'collapsed mode' to effectively lock that folder from expanding. maybe this can be done with a plugin? because I would love this to be a global feature.

I do enjoy the features of the auto-expand when finding files, and I don't mind if a file is visible if open/viewing so I know the path/structure. This additional behaviour is seen with some react apps where the folders are condensed into a path string above the file, no idea what magic settings does this, but it is a dream.

regardless, I stand by the point that folders like `node_modules` and `dist` should be permanently collapsed since they are not inherit to the development of the app, at most only needed for build scripts and the occasional debugging on types.

disappointed this wasn't taken seriously by the dev team, but then again, I guess Microsoft don't really develop large scale js/node apps or just go with the 'its good enough as is' approach.

for clarification, the 60 emotes mentioned earlier on this thread were from random people dealing with this very issue. This topic is not advertised or highlighted to the general public (neither is the backlog voting known), and I guarantee that if this was more public, it would be an overwhelmingly supported feature from the community.

**Comment by Livan-pro** [comment]
@digimbyte, FYI, there is already a PR for this issue, it just needs to be updated/improved: https://github.com/microsoft/vscode/pull/136905.

**Comment by djmisterjon** [comment]
> Two years later....

they probably need visual for help understand ? is hard concept. 
Plz allow omit reveal in node_module !
![lock node_module](https://user-images.githubusercontent.com/24865815/167284285-e7cdf19a-f0ee-4909-8680-cac0e173091f.gif)

**Comment by mindplay-dk** [comment]
💡 How about not auto-expanding things that are in your `.gitignore`?

That would work for `node_modules` and probably for other similar scanarios - without any manual intervention.

It's great to have options - but it would be even nicer if (most) users didn't need to solve this problem in the first place.

Those items are already grayed-out in the tree-view, so the IDE already "knows" - most likely, folders you wish to ignore in terms of source-control are just artifacts that the user wants to ignore most of the time in practice as well.

**Comment by well-balanced** [comment]
plz..

**Comment by salv0** [comment]
Is there any news about this one?

**Comment by sephentos** [comment]
> 💡 How about not auto-expanding things that are in your .gitignore?
>
> That would work for node_modules and probably for other similar scanarios - without any manual intervention.
> 
> It's great to have options - but it would be even nicer if (most) users didn't need to solve this problem in the first place.
> 
> Those items are already grayed-out in the tree-view, so the IDE already "knows" - most likely, folders you wish to ignore in terms of source-control are just artifacts that the user wants to ignore most of the time in practice as well.

Hell, yeah, i even would pay some bucks to have such a feature. Or at least having the possibility to define `node_modules` in the user settings to not be expanded when opening files in it e.g. via checking defination files in typescript projects.

**Comment by gulshan** [comment]
I think LSP should be able to provide sorting/nesting/hiding/revealing settings for a opened folder.

**Comment by PaRaD1SE98** [comment]
How about just collapsing the folder vscode auto-expanded when closing the file?

**Comment by owens-ben** [comment]
+1

Please add autoreveal per folder and/or regex!!!

**Comment by hjhjdev** [comment]
+1

**Comment by vincentbab** [comment]
+1

**Comment by lramos15** [comment]
Huge thanks to @jzyrobert his PR has been merged and you should be able to try this in tomorrow's [insiders ](https://code.visualstudio.com/insiders/)

**Comment by Masterxilo** [comment]
Thanks, so I assume this is how it would work: in your settings.json, add
```json
    "explorer.autoRevealExclude": {
      "**/node_modules": true
    }
```
I am not using the insiders build and 1.73.1 doesn't seem to understand that yet but looking forward to it...

**Comment by elucidsoft** [comment]
Thanks everyone!
