### ISSUE TITLE
Update notification still appears

### ISSUE THREAD

**Issue by arhakim** [microsoft/vscode#87957]
Issue Type: <b>Bug</b>

Hi,
I noticed the application update notification always appears several days after I update the application. As I remember, I update to the latest version three times already.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
vscode-json|and|1.5.0
laravel-goto-view|cod|1.3.2
jquerysnippets|don|0.0.1
gitlens|eam|10.1.1
php-intellisense|fel|2.3.13
rest-client|hum|0.21.3
vue|jcb|0.1.5
vetur|oct|0.22.3
laravel-blade|one|1.20.0
laravel5-snippets|one|1.7.0
vuehelper|oys|0.1.0
laravel-artisan|rya|0.0.25
bootstrap4-vscode|the|6.1.0
vscode-workspace-explorer|tom|1.2.1
wordpress-toolbox|wor|1.3.5
html-css-class-completion|Zig|1.19.0

</details>

**Comment by joaomoreno** [comment]
Do you still see this? Can you show me what's in the `About Code` window?

**Comment by arhakim** [comment]
Nope, I didn't get the notification again.

Does this issue has already fix?

Btw, this is the `About Code` content that you are asking:
```
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601
```

**Comment by joaomoreno** [comment]
> Nope, I didn't get the notification again.

Cool, glad to know it's good now. Thanks.
