### ISSUE TITLE
Intellisense/Autocomplete not working

### ISSUE THREAD

**Issue by KushagraPan** [microsoft/vscode#87955]
Building my first React project from https://frontendmasters.com/courses/complete-react-v5/ on VS Code for Windows 10.

Have installed prettier, eslint. Using Parcel to transpile the code. The intellisense is only working on index.html file. Nothing on js files. Have looked through old answers and none of them proved to be helpful. A bit of a noob here, a step by step solution will be helpful

![vscode](https://user-images.githubusercontent.com/44598917/71640938-bb3b0280-2cb9-11ea-99b6-6a450f1fb921.png)

Attaching project files
http://www.filedropper.com/adapt-me

**Comment by FangDingli** [comment]
I have the same problem and don't know how to solve it. The intellisense is working in HTML and CSS files and if you insert  script tag in HTML files, the intellisense is also working. But it's nothing happend in jsx and js files. I have already reinstalled vscode but no use.

**Comment by hasenov** [comment]
i had same problem, adding those settings into settings.json helped me:
"emmet.triggerExpansionOnTab": true,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },

**Comment by FangDingli** [comment]
> 
> 
> i had same problem, adding those settings into settings.json helped me:
> "emmet.triggerExpansionOnTab": true,
> "emmet.includeLanguages": {
> "javascript": "javascriptreact"
> },

Back to version 1.40

**Comment by mjbvz** [comment]
/needsMoreInfo

Please fill out our issue template
