### ISSUE TITLE
intellisense only shows once or twice then disappears

### ISSUE THREAD

**Issue by Dalesttn** [microsoft/vscode#87954]
Issue Type: <b>Bug</b>

Im busy editing a file with extension .jsx and have installed the simple react snippets, now the intellisense only shows up a couple of times before not working at all, even the standard snippets, is this a bug or a configuration on my program?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
bracket-pair-colorizer|Coe|1.0.61
vscode-faker|dee|1.3.0
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.18.0
auto-rename-tag|for|0.1.1
LiveServer|rit|5.6.1
php-formatter|Sop|0.2.4
ayu|tea|0.18.0
highlight-matching-tag|vin|0.9.6
vscode-icons|vsc|9.7.0

</details>

**Comment by egamma** [comment]
/needsMoreInfo

Please provide detailed steps for how to reproduce the problem.

Is there anything in the TypeScript log when Intellisense stops working? The TypeScript log is shown when running the command `TypeScript: Open TS Server log`

**Comment by Dalesttn** [comment]
[ts-server-details.txt](https://github.com/microsoft/vscode/files/4014771/ts-server-details.txt)
attached the server details as requested.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Dalesttn** [comment]
so it seems to only reproduce in large projects , but when I reinstalled the project using npm i , then it seemed to work again, very strange
