### ISSUE TITLE
Extension UI allows duplicate updates

### ISSUE THREAD

**Issue by rbirkby** [Microsoft/vscode#8795]
- VSCode Version: 1.3.0-insider (a1293f5)
- OS Version: Windows 10 TH2

Steps to Reproduce:

1. Click Update
2. Click on Explorer sidebar view
3. Click on Extensions sidebar view
3. Click Update a second time

![image](https://cloud.githubusercontent.com/assets/203034/16615179/b09f4fd2-436c-11e6-8a64-c06ac8947c55.png)

**Comment by joaomoreno** [comment]
@shanselman Saw this in 1.4.0, insiders.

cc @kieferrm

**Comment by joaomoreno** [comment]
Given that we received no more reports, I failed to reproduce and @shanselman reported back in August 3

> I’ll see if I can make it happen again.

I'll close this and keep an eye out for issues that come.

**Comment by rebornix** [comment]
Mark it as verified as no reports yet.
