### ISSUE TITLE
Title Menu Bar Navigation

### ISSUE THREAD

**Issue by jndbergfeld** [microsoft/vscode#87962]
Issue Type: <b>Feature Request</b>

when using the title menu only with keyboard, it is impossible to navigate between the main tabs ("File", "Edit", "Selection", "View", etc.) using the left and right arrow keys while in a submenu("Edit>Undo", "Edit>Redo", etc.).

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.15.0-72-generic snap

**Comment by sbatten** [comment]
@jndbergfeld this is an upstream issue. we solved this in our custom implementation of the menus but they are not enabled by default on linux due to the wide array of styling needs on linux. to see if you personally like them, try updating the setting `window.titleBarStyle` to `custom`
