### ISSUE TITLE
Allow to quickly remove entries from quick open recently opened

### ISSUE THREAD

**Issue by abaljeu** [microsoft/vscode#87963]
The solution implemented to the [closed item #15340](https://github.com/Microsoft/vscode/issues/15340) is illustrated in this GIF

https://user-images.githubusercontent.com/900690/28452585-a1acd4d8-6df3-11e7-9b37-a22591a11d69.gif

The current version of VS code seems to have removed this feature, adding an Okay but less important (because there are other ways)  "Open to Side" button in its place.  

![image](https://user-images.githubusercontent.com/5861116/71648352-26440380-2cd1-11ea-9090-b8c3738c9e39.png)

(The big problem of not being able to remove individual files is vscode has a tendency to remember and prioritize files of the same name from other folders that were opened a long time ago.)

**Comment by bpasero** [comment]
Those are 2 different lists of recently opened. You can remove from "File > Open Recent > More..." but the same is not as easily possible from the quick open solution (which tracks files within the project as opposed to the other). Converting to a feature request.

**Comment by bpasero** [comment]
Actually as a workaround you can do this from command palette:

![image](https://user-images.githubusercontent.com/900690/71767105-bae47680-2f08-11ea-9d31-58290ac59c85.png)
