### ISSUE TITLE
Executing Task Error

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#87960]
Why when creating a task, and running the task do I get this error; 
```
> Executing task in folder CodeProjects: \Custom Program Settings\Projects.Code\'C:\Custom Program Settings'\EXRTools\exrdisplay.exe  <

The terminal shell path "\Custom Program Settings\Projects.Code\'C:\Custom Program Settings'\EXRTools\exrdisplay.exe" does not exist
```

**Comment by alexr00** [comment]
Please provide the full task.

**Comment by SheepDomination** [comment]
@alexr00 This is the first example which I could not get to execute;
```
"version": "2.0.0",
    "tasks": [
        {
            "label": "EXRTool",
            "type": "shell", // run a task as an administrator without running vscode as an administrator ?
            "command": "C:\\Custom Program Settings'\\EXRTools\\exrdisplay.exe"
        },
```

And this is the error;
```
Executing task in folder CodeProjects: \Custom Program Settings\Projects.Code  <
The terminal shell path "\Custom Program Settings\Projects.Code" is a directory
Terminal will be reused by tasks, press any key to close it.
```

**Comment by alexr00** [comment]
@SheepDomination unfortunately I can't reproduce the issue you're seeing with only that information. If you can provide a minimal example that requires simple setup that anyone can reproduce (such as a repository I can clone with a task that runs a silly script that only echos hello) then I'm happy to take another look.

**Comment by SheepDomination** [comment]
@alexr00 The question is, is it not possible to run commands outside of the workspace, as you see in the task which I posted. The path to the executable is outside of the workspace, but when trying to run the task, it appears as though the executable must be inside the workspace ?

**Comment by alexr00** [comment]
You can set the task's cwd. Documentation is here: https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks

**Comment by SheepDomination** [comment]
@alexr00 I've read that documentation, although it still is not working; I cannot get any task to work as I mentioned in my original post.  This is what is frustrating me for months already, and this must not continue, I must solve why I cannot get tasks to work.

**Comment by SheepDomination** [comment]
If a script must be located within your workspace folder when running tasks. How can one run an executable which is outside of the workspace, whether located in another folder or in the path environment variable ?

**Comment by SheepDomination** [comment]
If a command must be run from the workspace, then why when running this task does it not work ?
```
 "tasks": [
        {
            "label": "runEcho",
            "type": "shell", // 
            "command": "C://Custom Program Settings//Projects.Code//batch//runEcho.bat",
        },
```

**Comment by SheepDomination** [comment]
I'm unable to join stack over flow; therefore can someone please help ?
