### ISSUE TITLE
customise enableSearchEditorPreview behaviour

### ISSUE THREAD

**Issue by andrasnyarai** [microsoft/vscode#87961]
With the enableSearchEditorPreview is on the search results are displayed in a new open editor,
it is bothersome that when closing this editor vscode prompts, that if you want to save this file or not.

a boolean setting would be nice with a false default like so:
`canSaveSearchEditorPreviewToDisk`

**Comment by JacksonKearl** [comment]
\duplicate #86191

**Comment by JacksonKearl** [comment]
See #86191
