### ISSUE TITLE
The token '&&' is not a valid statement separator in this version.

### ISSUE THREAD

**Issue by eascott** [microsoft/vscode#87967]
Issue Type: <b>Bug</b>

Attempt to debug a python module containing "print("hello, world")" in with python 3.6 throws this error ( although it happens on anything and everything):

PS K:\new\-\video\VideoRedo\vprj rename tool\vrprename> cd "k:\new\-\video\VideoRedo\vprj rename tool\vrprename" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && "k:\new\-\video\VideoRedo\vprj rename tool\vrprename\venv\Scripts\python.exe" c:\Users\evana\.vscode-insiders\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 31327 "k:\new\-\video\VideoRedo\vprj rename tool\vrprename\helloworld.py" "
At line:1 char:58
+ cd "k:\new\-\video\VideoRedo\vprj rename tool\vrprename" && cmd /C "s ...
+                                                          ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

Neither VSC 1.41.1 nor  VSCodium 1.41.1 do this, I have removed the path fragments for all three from the system path. Only VSC Inisder is running. There are no other relevant envars set,  It is probably worth mentioning that VSC Insider worked just fine  until it was updated. This happened several weeks ago and I failed to capture the relevant data. But having said that it occurrs to me that another approach would be to reinstall earlier versions until the problem goes away... or doesn't. I will try that tomorrow and let you know how it goes.
evan.alan.scott@gmail.com

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.19536

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8120 Eight-Core Processor            (8 x 3110)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (12.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by egamma** [comment]
Please report this issue against the python extension.

**Comment by eascott** [comment]
According to the VSC-Python crew:
@microsoft/pvsc-team this is an upstream bug in VS Code. We do not control the &&. The command is build by VS Code and sent to the terminal. We merely provide parts of the command such as cwd, env variables, and the like. Issue #84793 

This is consistent with my evaluation and is the reason I didn't submit it as an extension bug, The fact that the same extension version works in both VSC 1.42.1 and VSCodium 1.41 would seem to argue against it being an extension bug... unless, of course, some documented change in VSC Insider could be employed to show that the extension has not been properly adjusted to work in VSC Insider.
evan.alan.scott@gmail.com

**Comment by weinand** [comment]
It seems you are using PowerShell but VS Code doesn't detect this and builds the command line for a regular command prompt ("cmd.exe").

Does it help if you set the terminal setting `terminal.integrated.shell.windows` to `C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`?

**Comment by eascott** [comment]
Yup. I have both Powershell and Powershell 6 installed and things run normally when they are selected as the default shell. The problem only occurs with cmd. I don't normally select Powershell as the default but I probably should have thought to try that.

**Comment by weinand** [comment]
Thanks, I'm currently investigating why VS Code doesn't see you default terminal.

But the workaround should work for you: just configure the `terminal.integrated.shell.windows` to reflect the default.

**Comment by weinand** [comment]
@eascott since #87088 is fixed now it would be great if you could verify that your issue is now resolved.
