### ISSUE TITLE
Resizing sidebars using mouse wheel

### ISSUE THREAD

**Issue by rostamiani** [microsoft/vscode#87969]
Issue Type: <b>Feature Request</b>

Sometimes it's useful to make sidebars such as search results smaller to make more space for main area and still read the search results.
Maybe using Ctrl + mouse wheel

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
You can click and drag to resize the sidebar if you didn't realize that, but I don't think we will try to resize workbench parts with the mousewheel.
