### ISSUE TITLE
JS code intelligent prompt failure

### ISSUE THREAD

**Issue by INTMIN** [microsoft/vscode#87979]
Issue Type: <b>Bug</b>

After the project code enters, there is an initial prompt. After a while, the prompt disappears. The prompt is loading all the time. All variables and class names cannot be imported and prompted automatically

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
turbo-console-log|Cha|1.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
wxml-vscode|cny|0.1.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.11
githistory|don|0.4.12
es7-react-js-snippets|dsz|2.5.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
beautify|Hoo|1.5.0
rest-client|hum|0.23.0
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
vscode-language-babel|mgm|0.0.25
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.41.2
remote-wsl|ms-|0.41.6
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
vscode-versionlens|pfl|0.24.0
java|red|0.55.1
prettier-now|rem|1.4.9
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
js-jsx-snippets|sky|10.0.0
autoimport|ste|1.5.3
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-maven|vsc|0.20.1
vscode-icons|vsc|9.7.0
vim|vsc|1.12.4
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.1

</details>

**Comment by INTMIN** [comment]
!(https://raw.githubusercontent.com/INTMIN/photo/master/JSintelligent.png)

**Comment by egamma** [comment]
/needsMoreInfo

Please provide detailed steps for how to reproduce the problem.

**Comment by INTMIN** [comment]
Only one project would  recurrent ,This is a react project，other member would not recurrent. Even reinstallation after uninstallation is useless.

**Comment by INTMIN** [comment]
@egamma
