### ISSUE TITLE
Unable to open web links in running browser instance (Firefox on Fedora 30/31, Ubuntu 19.10)

### ISSUE THREAD

**Issue by shreepads** [microsoft/vscode#87971]
- VSCode Version: 1.41.1
- OS Version: Fedora 31 64 bit workstation (also occurs on 30)

Installed using the Snap store as described here: https://snapcraft.io/install/code/fedora

Steps to Reproduce:

1. Start VS Code
2. Click on a link in the help text e.g. Help -> Documentation or a web link in a file
3. An error message pops up stating: "Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system."

Expected Result: The selected link opens in a new tab/ window in the running Firefox instance

Workarounds: Copy the link and open separately in a new tab in Firefox. Doesn't work for Help -> Documentation where the link text is not available, in this case the only way out is to close Firefox and then click on Help -> Documentation. It then opens fine but this is not a workable workaround!

Does this issue occur when all extensions are disabled?: Yes

**Comment by DAlperin** [comment]
+1 same on ubuntu 19.10

**Comment by egamma** [comment]
>Click on a link in the help text e.g. Help -> Documentation or a web link in a file

What do you mean by 'web link in a file', can you please provide an example?

**Comment by egamma** [comment]
@deepak1556 the openerService calls `window.open()` which is part of the standard DOM API.

**Comment by alirezamaleky** [comment]
![Screenshot from 2020-01-12 23-25-24](https://user-images.githubusercontent.com/37160903/72224758-224a9800-3593-11ea-8075-7179902c145b.png)

Report contents:
BuildID: 20200107212822
CrashTime: 1578858890
FramePoisonBase: 9223372036600930304
FramePoisonSize: 4096
InstallTime: 1578689039
Notes: Ubuntu 19.10
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 1788
StartupCrash: 1
StartupTime: 1578858890
ThreadIdNameMapping: 14961:"Gecko_IOThread",14973:"Timer",14974:"Netlink Monitor",14975:"Socket Thread",14978:"JS Helper",14981:"JS Helper",14979:"JS Helper",14977:"JS Watchdog",14980:"JS Helper",14984:"Cache2 I/O",14985:"Cookie",14986:"StreamTrans #1",14987:"DOM Worker",14988:"IPDL Background",14989:"StreamTrans #2",14990:"StreamTrans #3",14991:"StreamTrans #4",14992:"StreamTrans #5",
Throttleable: 1
UptimeTS: .46901348
Vendor: Mozilla
Version: 72.0.1

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/85344
