### ISSUE TITLE
Allow debugging TS code out of the box

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#87972]
We're the best editor for TS, but you wouldn't know it from trying to start a new project.

1. Create a new `.ts` file in an empty folder:
```ts
console.log('hello')
```
1. F5 to run.
![image](https://user-images.githubusercontent.com/8586769/71656962-78e1e780-2cf2-11ea-91ff-abe6705be598.png)
1. Accept the provided launch.json, then try again. 
1. Same error. Maybe I need to compile it? (however a newcomer might not know that)
1. Search command pallette for "TypeScript" in hopes of finding a way to compile the current file or initialize a new project.
![image](https://user-images.githubusercontent.com/8586769/71657053-f6a5f300-2cf2-11ea-8774-78615e12598a.png)
Secretly, "Go to Project Configuration" is what I want, but again a newcomer wouldn't know that
![image](https://user-images.githubusercontent.com/8586769/71657081-1d642980-2cf3-11ea-971b-c890a2cae6d1.png)
We should have a "Typescript: Configure tsconfig.json" or "Typescript: Initialize Project" or similar to go straight to making the tsconfig.
1. Accept the provided tsconfig.json (also note the default file is reported as having an error):
![image](https://user-images.githubusercontent.com/8586769/71657156-8350b100-2cf3-11ea-9407-a59e3f5a98d8.png)
1. Try running the file again. Same error!
1. Add `"sourceMap": true` to the tsconfig.json. The file now runs.

At the very least we should make the default tsconfig.json output source maps, as VS Code is crippled without them. It should also not come with the error about `checkJs` by default, either by removing it or adding `allowJs`.

We should also make the error message give some hints about how to fix the problem (Do you have source maps enabled for this project? Have you built the project? Are the files in the location specified in the launch.json, etc.), as suggesting a launch.json identical to the existing one is never the right solution. 

Going beyond that, it would be nice to have a thought out flow for going from a .ts file to a proper VS Code experience.

**Comment by mjbvz** [comment]
I'll add `"sourceMap": true` to the default tsconfig we generate

We did also discuss bundling `tsc` with VS Code in the past. However this would add ~6mb to our bundle size and we also weren't sure we wanted people relying for VS code for their compiles (for example, when we ship a VS Code update, we want to avoid breaking compilation of someone's project)

/cc @DanielRosenwasser and @gcrev93 for other thoughts on the TS first run experience

**Comment by mjbvz** [comment]
`checkjs` now also implies `allowjs`: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#checkjs-implies-allowjs

**Comment by mjbvz** [comment]
@connor4312 Any ideas about making it simpler to debug TS files for beginners? If the user has `tsc` installed globally or under `node_modules`, could we automatically compile on `f5`?

**Comment by connor4312** [comment]
@mjbvz we actually include typescript internally already in js-debug that we use for a lot of syntax tree stuff already. So we could do it without even requiring an `npm install`... basically do something like ts-node's transpileOnly mode.

I like that idea as a way to get beginners using TS without a whole bunch of setup. I don't want that scenario for the intermediate to advanced users that have a proper build setup; maybe we have a `transpileTypeScript` flag that's on for default F5 debugging but requires manual opt-in inside launch.json.

**Comment by mjbvz** [comment]
Renaming this to focus on f5. Please split any other concerns to their own issues

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/124280
