### ISSUE TITLE
Rename custom tags (React tags) change all these tags in code

### ISSUE THREAD

**Issue by Whitefox98** [microsoft/vscode#87978]
- VSCode Version: 1.41.1 (user_setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:
This bug happens when you use the new feature of rename tag (F2) with React tags, in this case Link from react-router-dom. 
1. Create a multiple tag Link for example, and try to change it with F2. This will change all Tags Link in your code.

You can see it with gif: https://gyazo.com/c227626d3aae20bd6092f35fc0c47a3b

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
I can't use F2 to rename JSX/TSX tags. Can you try disabling all extensions you have?

**Comment by mjbvz** [comment]
Also, please share a minimal, self-contained example of this (as text or as a GitHub repo)
