### ISSUE TITLE
total lag in the program

### ISSUE THREAD

**Issue by nadenagi** [microsoft/vscode#87974]
the program lagges in every function it should do things like 
1- auto complete 
2- correction 
3- find result
4- expand and collapse sections of code

Steps to Reproduce:

1. open a big project 
2. open many tapes from that file (in my case 30 taps)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please follow the instructions at https://github.com/microsoft/vscode/wiki/Performance-Issues
