### ISSUE TITLE
markdown causes vscode reopen

### ISSUE THREAD

**Issue by PacificBase** [microsoft/vscode#87973]
After updating the new version, I have reopened vscode for 3 times during writing the mardown files. I have no ideas about it, the reason might be that the files are put on the network location. 

自从更新完这个版本的vscode后，我在写markdow文件时已经重启了三次了。我是一点脾气都没有了。。。可能是我把文件放在了网盘上了。

**Comment by mjbvz** [comment]
/needsMoreInfo

Please follow our issue reporting guidelines
