### ISSUE TITLE
collapse all function

### ISSUE THREAD

**Issue by RafaelANNO** [microsoft/vscode#87970]
Issue Type: <b>Feature Request</b>

hey guys, can you add the feature to collapse all function in the code

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Please review https://code.visualstudio.com/docs/editor/codebasics#_folding and if these features don't meet your needs then post more details.
