### ISSUE TITLE
Declared variables and Functions do not register within an if loop in angular

### ISSUE THREAD

**Issue by kapow00** [microsoft/vscode#87983]
I have declared variables and functions in a component  .These were called inside an if loop, initially the variables and the functions were registering inside the loop..in fact I got infinite loops...subsequently they have stopped registering , even the visual code prompt does not show the variables/functions.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide all info required by issue template as well as reduced code example that causes a problem.
