### ISSUE TITLE
Add 'always peek definition' setting

### ISSUE THREAD

**Issue by guidsdo** [microsoft/vscode#87987]
After the last update `1.41.1`, you now always go to the definition/reference if there is only one occurence. This is understandable, but I really love the peek view.

Old situation:
How is this method used and where? Ah, okay good to know. Now continue reading.

New situation:
How is this method used and where? Oh darn, I jumped to the file. Where am I? Ah alright. Wait; where was I? Back mousebuttons don't work in vscode on the Mac and Linux, so I have to go to my keyboard again and use my custom shortcut.

Proposal:
Please allow me to always see the 'peek' window when clicking on `1 reference` in codelens. This now only works when there are multiple references.

**Comment by jrieken** [comment]
So, what describe is more or less the difference between "Go To"-commands and "Peek"-commands. The former tries to go to some place whereas the latter always peeks. The issue here is that code lens commands default to the "Go To" behaviour, not the "Peek" behaviour.

**Comment by guidsdo** [comment]
Yes that's correct. So I would like to be able to `Peek references` when I click on  the `1 reference` link, instead of going directly to the reference.

<img width="324" alt="Screenshot 2020-01-04 at 13 35 18" src="https://user-images.githubusercontent.com/7917821/71765604-3b9a7700-2ef7-11ea-91ba-b38e8943dd64.png">

**Comment by jrieken** [comment]
I have pushed a change so that code-lens always uses "peek" and not "go to".

**Comment by jrieken** [comment]
Verifier: 

1. enable ts reference code lense
2. have a symbol with one reference
3. select the "1 reference" commnd
4. make sure peek shows
