### ISSUE TITLE
Document/clarify how "keyboard.touchbar.ignored" affects extensions

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#87980]
I had [a request](https://github.com/Dart-Code/Dart-Code/issues/2195) in my extension to honour the `keyboard.touchbar.ignored` setting to hide items from the touchbar. There's nothing in the docs about the expectations here - if the array is just populated with command IDs, it would be better for VS Code to handle this (to avoid every extension that contributes touchbar buttons having to do it).

Otherwise, if it's the extensions responsibility to do this, it should be made clear somewhere in the docs (for example on https://code.visualstudio.com/api/references/contribution-points).

**Comment by bpasero** [comment]
Yes, this setting literally contains the IDs of actions/commands to not show in the touchbar. It should just work for your touchbar actions if the user configures the identifier. Does it not?

**Comment by DanTup** [comment]
Oh, I see the issue... The problem is that in order to have different text on the TouchBar from the Command Palette (the touchbar has much less space so has to have the names shortened) we have to have extra commands. In this case the touchbar has a hidden command ("_flutter.screenshot.touchBar") and the user was using the command it delegates too.

I guess it's working-as-intended, but it doesn't feel ideal to have to have the user exclude using private command names, or having to compromise the command palette text to match that for the touchbar.

**Comment by bpasero** [comment]
This came in via https://github.com/microsoft/vscode/pull/70174. Maybe you ping the author about the issues you see with this feature.

**Comment by DanTup** [comment]
@bpasero I'm not sure there's a great fix besides being able to have a single command with different text labels for touchBar vs commandPalette so it'd probably need a decision from the Code team whether they'd want to support something like that. Another option would be to use icons, though for some things it's hard to come up with icons that wouldn't be vague.

**Comment by bpasero** [comment]
I am not sure what you are asking for. `keyboard.touchbar.ignored` is well defined. The user can add the identifier of a command to exclude it from the [macOS touchbar](https://support.apple.com/de-ch/guide/mac-help/mchlbfd5b039/mac). That is pretty much the entirety of what this setting does.

If you think something is missing in this area (e.g. allowing the user to hide commands from the command palette), I would suggest to open a separate feature request.
