### ISSUE TITLE
Shortcut doesn't work

### ISSUE THREAD

**Issue by dhagej** [Microsoft/vscode#8798]
- VSCode Version: Code - Insiders 1.3.0-insider (a1293f5056e79c3f0e2cd3e24909f41ff4eef472, 2016-07-05T13:09:46.271Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Try to open integrated terminal by clicking Ctlr+'
2. Nothing happens

**Comment by Tyriar** [comment]
The shortcut is <kbd>ctrl</kbd>+<kbd>`</kbd> (backtick), not <kbd>ctrl</kbd>+<kbd>'</kbd> (apostrophe)

**Comment by dhagej** [comment]
I discovered that few days later, my mistake.. sorry :(
