### ISSUE TITLE
 intellisense is not working

### ISSUE THREAD

**Issue by kamanak** [microsoft/vscode#87981]
Issue Type: <b>Feature Request</b>

 intellisense is not wrking in js file

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
/needsMoreInfo

Is your code on somewhere besides the `c:` drive?
