### ISSUE TITLE
Display full-size diff when window is split

### ISSUE THREAD

**Issue by hesting15** [microsoft/vscode#87988]
If I split window to work with 2 editors and go to _Source Control_ to see the diff, diff is displayed inside the active editor. It splits editor once again. Columns are very narrow. I would like to see full-size diff

![SplitWindow](https://user-images.githubusercontent.com/22618607/71668835-1f6dcd00-2d73-11ea-834e-caa9012c760a.png)

**Comment by egamma** [comment]
Please see the command `View: Maximize Editor Group`.
