### ISSUE TITLE
Edit/remove specific emmet abbreviation (dot expands to empty div)

### ISSUE THREAD

**Issue by Vallek** [microsoft/vscode#87985]
I have a problem with emmet abbreviation for dot (full stop) in HTML. It creates div with empty class. If I use enter to expand abbreviation than emmet creates div instead of just a dot (if I need to jump to next line after). I know that I can disable enter and use Tab but that is inconvenient. 
That being said I think this is just a small example of bigger problem. We can't edit or disable specific default abbreviations (correct me if I'm wrong). 

What I tried:
1. Custom abbreviations in snippets.json but it doesn't work with a "."
2. Custom abbreviations in html.json but it just adds another one and the div one stays.

If anyone knows a way around it please do tell.

I'm using latest stable version (1.41.1), Windows 10 64bit

**Comment by octref** [comment]
Can you provide the source of the custom abbreviations?

**Comment by Vallek** [comment]
Something like this for html.json (based on example): 
```
"dot": {
	"prefix": ".",
		"body": [
			"."
	 	],
	 	"description": "dot"
	 }
```
And this for snippets.json:
```
{
	"html": {
	  "snippets": {
		".": "{.}"
	  }
	}
  }
```
I think i tried different versions, none worked.

**Comment by octref** [comment]
So you are saying you want to remove this suggestion?

![image](https://user-images.githubusercontent.com/4033249/74881980-25b80880-5323-11ea-8791-81bd96033bd3.png)

I'm afraid there's no customization now that can only allow you to remove one expansion.

**Comment by Vallek** [comment]
Yep, that's what i want. But it's not only working with "div.". The problem is that it's working for just a single dot.

**Comment by octref** [comment]
In https://docs.emmet.io/, typing `.` does expand to `<div class=""></div>`, so I can't just remove it.

**Comment by Vallek** [comment]
> please explain what is expected and what is not in more detail.

When I press enter after full stop (especially inside some element's text content) I do not expect creating a div there. I expect cursor to jump to next line (create new one). 

The "div." one is fine. But just a dot in any context is not.

But then again this is just a consequence of bigger problem: we can't edit or disable default abbreviations.
