### ISSUE TITLE
With Source Code Pro font, italic cyrillic characters renders wrong

### ISSUE THREAD

**Issue by freetz13** [microsoft/vscode#87996]
- VSCode Version: 1.41.1
- OS Version: 5.4.6-2-MANJARO

Steps to Reproduce:

1. In `settings.json` set the `editor.fontFamily` to `'Source Code Pro'`
2. Use any color theme that uses italic type (for example, for comments)
3. Write any comment with cyrillic characters in any code

Does this issue occur when all extensions are disabled?: Yes

***
I want to use Source Code Pro font and Base16 Dark theme (from Base 16 Theme Generator) together. Sometimes I need to write Russian text in comments. That text looks like Source Code Pro font is not found.

![Screenshot_2020-01-03_01-46-04](https://user-images.githubusercontent.com/7419347/71676028-db0e1b80-2dca-11ea-9d4e-38ddcf4736ea.png)

Problem appears only for italic cyrillic text.

Problem appears in a fresh-installed Manjaro linux (in Virtualbox) and Solus Linux (slightly different, but still).

Italic cyrillic characters with "Source Code Pro" font looks as it should in Firefox:

![Screenshot_2020-01-03_01-34-32](https://user-images.githubusercontent.com/7419347/71675911-a4d09c00-2dca-11ea-809f-b46663ec8c19.png)

**Comment by alexdima** [comment]
@freetz13 Does the issue reproduce in Chromium? How does the page at https://jsfiddle.net/L32xv408/ render in Chromium vs Firefox?

**Comment by freetz13** [comment]
Well, yeah.

Firefox:

![Screenshot_2020-01-21_19-27-26](https://user-images.githubusercontent.com/7419347/72792082-1beba880-3c84-11ea-812a-bef92c4c1731.png)

(as it should)

Chromium:

![Screenshot_2020-01-21_19-27-15](https://user-images.githubusercontent.com/7419347/72792148-3c1b6780-3c84-11ea-8095-6e837750253c.png)

So, it's Chromium problem, right?

**Comment by alexdima** [comment]
@freetz13 Yes. VS Code is built with Electron, which is built with Chromium, and this reproduces in Chromium. Since this reproduces in Chromium, please create an issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list
