### ISSUE TITLE
Right click and topbar dropdowns render as a blackbox

### ISSUE THREAD

**Issue by mbistacchi** [microsoft/vscode#87997]
- VSCode Version:  1.41.1
- OS Version: Ubuntu 18.04 (Virtual Machine)

Steps to Reproduce:

1. On opening, all code from current file/blank page renders as normal. However, clicking on any of the top bar dropdowns (File, Edit etc), or right clicking on any point, just gives a black box with the same dimensions as expected from the dropdown prompt.

Does this issue occur when all extensions are disabled?: YES

**Comment by egamma** [comment]
/needsMoreInfo

Please illustrate the problem with a screenshot.
