### ISSUE TITLE
C++ asm statement not recognised

### ISSUE THREAD

**Issue by RSDuck** [microsoft/vscode#87991]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open any C++ file
2. Enter the following code:
```C++
void test()
{
  asm
  (
    : : :
  );
}
```
If the opening paranthesis is on the same line as the asm statement, it is properly recognised.

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.41.2
cpptools|ms-|0.26.3-insiders2

(1 theme extensions excluded)

</details>

**Comment by RSDuck** [comment]
There are also several other issues with asm statements. When putting the opening paranthesis on the following line, discolorations appears all through the rest of the file.

Take for example this code:
```c++
void test()
{
    __asm__
    (
        // load palettes
        "ld2 {v4.16b, v5.16b}, [%[curpal0]]\n"
        "ld2 {v6.16b, v7.16b}, [%[curpal1]]\n"
        :
            [prevTileLo] "+w" (prevTile.val[0]), [prevTileHi] "+w" (prevTile.val[1])
        :
            [curpal0] "r" (curpal0), [curpal1] "r" (curpal1)
        :
            "memory", "q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7"
    );

    int test = 0;
    printf("test %d\n", 0);
}

int main(int argc char* argv[])
{

}
```
As you can see the entire rest of the function is completely discoloured.
![grafik](https://user-images.githubusercontent.com/9352526/71673207-690ce680-2d78-11ea-842c-4a78ba935c45.png)

This is independent from the semantic colouring of the C++ extension included in the auto generated list extensions I have installed, as I've been eable to reproduce both issues detailed in this and the first post without it.

**Comment by alexr00** [comment]
Moved to the owning repository.
