### ISSUE TITLE
Duplicate, ever-increasing, non-resetting error count

### ISSUE THREAD

**Issue by kierenj** [Microsoft/vscode#8799]
- VSCode Version: 1.2.1 (fe7f407b)
- OS Version: Windows 10 Enterprise (10586.420)

Steps to Reproduce:
1. Open folder with many dotnet core projects
2. Invoke gulp-based build command as below

tasks.json:

```
        {
            "taskName": "build",
            "args": [ "build" ],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        },
```

gulpfile.js (relevant bit):

```
gulp.task('build', 
    shell.task([
        'dotnet build **/project.json'
    ])
);
```
1. See correct build output as below (if output window open)

```
[12:57:41] Using gulpfile c:\git\kierenj\saffron-0.2\gulpfile.js
[12:57:41] Starting 'build'...
Project app (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project Xyz.Something1 (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Xyz.Something2 (.NETStandard,Version=v1.6) will be compiled because inputs were modified
Compiling Xyz.Something2 for .NETStandard,Version=v1.6
C:\Program Files\dotnet\dotnet.exe compile-csc @c:\git\kierenj\xyz-0.2\src\Xyz.Something2\obj\Debug\netstandard1.6\dotnet-compile.rsp returned Exit Code 1
Compilation failed.
    0 Warning(s)
    1 Error(s)
Time elapsed 00:00:01.1862173
c:\git\kierenj\saffron-0.2\src\Xyz.Something2\AppBuilderExtensions.cs(7,35): error CS0161: 'AppBuilderExtensions.UseAutofac(IAppBuilder)': not all code paths return a value
Project Xyz.Something3 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
[12:57:42] 'build' errored after 1.93 s
[12:57:42] Error: Command `dotnet build **/project.json` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
:
```
1. Immediately notice 3 errors in the bottom bar, not 1.  Once I had 4 errors, no changes!
2. Change a line, rebuild the app
3. Number immediately decreases to 2 (or sometimes 1), before coming back up to 3 upon build completion

I got up to a point of having 99 errors in the status bar, with only one build error, which was not flagged.  I don't know the exact steps for _that_, that was after a 1-hour session.

If I can provide more diag info, let me know.

**Comment by dbaeumer** [comment]
@kierenj do you have a project you can share. This would ease reproducing this.

**Comment by kierenj** [comment]
I can't share the project as-is, but I'll try to find time to duplicate the issue then rename/remove things until the problem disappears as a repro.

**Comment by dbaeumer** [comment]
Thanks a lot.

**Comment by dbaeumer** [comment]
Closing the issue. We change quite some code in the marker service and without a reproducible case there is nothing we can fix.
