### ISSUE TITLE
Allow suppression of auto-open behaviour for bottom panel

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/vscode#87993]
I'd love to see a setting to suppress any and all auto-open behaviour of this panel:

![image](https://user-images.githubusercontent.com/115199/71671246-2b886900-2d38-11ea-9d8a-df61466f9646.png)

---

#### Rationale

This comes from years of using code as it has been evolving. My "clue" for needing this is that I find myself closing or going after every possible way to close this part of the UI. Especially after using keyboard shortcuts that won't necessarily require me to digest any of the information presented.

The two most common scenarios for me are when code is automatically started as my git commit message editor (from WSL2) and when I do a build (ctrl-shift-b).  Especially in the WSL2 scenario where the panel actually steals focus, requiring me to click in the editor window before authoring my commit message!

While in the case of failed builds, I will want to see information, after a successful build, having nominal "this will stay open" information presented to me takes away my attention and forces me to take an action to close the panel to get back to my regular "focused/unobstructed" layout.
As for focus-stealing, I think these need to be chased down.  Unless the open of the panel was as a direct result of user intention (ctrl-`, etc), this panel should never steal focus.

To make all of this conceptually easier, I do not believe code should care about whether tasks or other events that pop this panel up are successful or not.  Just give me a way to say "never pop this open, I will open it myself when I need it".

**Comment by isidorn** [comment]
It is a fair feature request to have this setting, thus leaving this open.
However apart from that we should still find all places that un-necesserily open the bottom panel and file issues against tham. @atrauzzi can you please file independet issue for when panel is opened and it should not be in your opinion so that owners can tackle those independently?
Thanks

**Comment by Screenfeed** [comment]
Hi.
I totally agree. A "Don't automatically open the bottom panel" setting is needed imho. I personally see this behavior exactly like an unwanted popup thrown to my face. If we can't fine tune it, at least I'd love to be able to nuke it.

**Comment by atrauzzi** [comment]
That is such a terrible way to prioritize work.
