### ISSUE TITLE
sortable intellisense, automatic conda environments switching when changing python interpreter, add settings.json button to preferences

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode#87992]
Here are some things I would suggest:

1- When using autocomplete/intellisense suggestions, please allow getting specified types of suggestions, e.g variables or functions and methods. Better if a hotkey could be used after the suggestions are popped up. So for example I write "re." in python and I can press F then to get a list of functions and methods first in the suggestions list.
2- When Python interpreter is changed to another conda environment, this doesn't affect the conda environment activated in the WSL integrated terminal, so when running the code, it'll still run in the previous conda environment! although using the interpreter of the other! (Might have something to do with the fact that I'm using the WSL remote but I don't think that's the case)
3- Add a button for "settings.json" file in the preferences too! I know it can be accessed from CTRL+SHIFT+P -> Open Settings JSON but sometimes you go into preferences automatically and you search for it scratching your head! Maybe it's there and I'm unaware but I have not found it there unless I open the settings for font! and then enter settings.json file.
Thank you.

**Comment by mjbvz** [comment]
Please file these as separate issues. Let's just track the first point in this issue

Can you provide a complete example of the first point and what specifically you are requesting
