### ISSUE TITLE
Console is difficult to work with on a small screen

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#88]
While working on my laptop, I found it difficult to use the debug console. For example, consider this screen:

![image](https://cloud.githubusercontent.com/assets/393660/11250992/0683cb24-8de4-11e5-9580-0e6e96628e1c.png)

I was able to adjust the side of the code on the right, and hide files:

![image](https://cloud.githubusercontent.com/assets/393660/11251007/1b957f58-8de4-11e5-9b39-707239321f7e.png)

But note there is *still* text I can't see that bleeds off the right hand side. 

Is there any way to wordwrap?

**Comment by bpasero** [comment]
Improving the debug console (including word wrap) is a top item on our backlog.

**Comment by isidorn** [comment]
Dup of #226 
+1 for Ben's comment
