### ISSUE TITLE
[Terminal] VSCode Freeze when typing 'a' into terminal and closing it

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#88003]
Issue Type: <b>Bug</b>

![](https://user-images.githubusercontent.com/15258962/71267430-5b2e7e80-22ff-11ea-8d36-c1b0bcfba51d.gif)

The ConPTY team has provided suggestion on how the VSCode team can fix this.
https://github.com/microsoft/terminal/issues/1810#issuecomment-570284546

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bracket-pair-colorizer-2|Coe|0.0.29
gitlens|eam|10.2.0
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.162
vscode-peacock|joh|3.2.0
better-powershell-syntax-highlighting|jus|0.0.2
git-graph|mhu|1.20.0
azure-pipelines|ms-|1.157.4
remote-containers|ms-|0.96.0
remote-ssh-edit-nightly|ms-|2019.12.44160
remote-ssh-nightly|ms-|2019.12.44160
remote-wsl|ms-|0.42.0
azure-account|ms-|0.8.7
powershell-preview|ms-|2019.12.1-CI.41180
team|ms-|1.161.0
indent-rainbow|ode|7.4.0
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3
vscode-zipexplorer|sle|0.3.1
vscode-icons|vsc|9.7.0
gistfs|vsl|0.0.41
better-align|wwm|1.1.6
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by JustinGrote** [comment]
@Tyriar are you sure it's a dupe? That referenced issue shows that it should work on 1903 and later, and I'm well past that and still have the issue.

As mentioned terminal team has mentioned the vscode team can fix this, but its still currently an upstream issue: https://github.com/microsoft/terminal/issues/1810#issuecomment-570284546

**Comment by Tyriar** [comment]
@JustinGrote #76548 points to https://github.com/microsoft/terminal/issues/1810 which points to the new https://github.com/microsoft/node-pty/issues/375 😉
