### ISSUE TITLE
Syntax Highlighting Broken

### ISSUE THREAD

**Issue by welljsjs** [microsoft/vscode#88001]
Issue Type: <b>Bug</b>

This piece of JS code does not get properly highlighted. 

The selected theme does not matter; when choosing another theme, the issue persists.

I assume it gets confused by the nested arrow functions and JSDoc.
```js
/**
   * @param {any} uid 
   */
  static findOne = uid =>
    /**
     * @param {any} connection
     */
    connection => {
      return true;
    };
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (4.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
arm|dan|0.7.0
vscode-markdownlint|Dav|0.33.0
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
vscode-sql-template-literal|for|0.1.0
vscode-docker|ms-|0.9.0
vscode-language-pack-de|MS-|1.41.2
cpptools|ms-|0.26.2
vsliveshare|ms-|1.0.1404
vsliveshare-audio|ms-|0.1.80
material-icon-theme|PKi|3.9.2
vscode-icons|vsc|9.7.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.2.1
linkerscript|Zix|1.0.0

(3 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Please try disabling all user installed extensions and provide a screen shot showing the problem.
