### ISSUE TITLE
OmniSharp server running icon color problem

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#88002]
The OmniSharp server running icon(the fire icon) at bottom bar always stays on white color. 
It's not readable on light theme.
![image](https://user-images.githubusercontent.com/24863266/71681847-c761b580-2dc8-11ea-8465-466a47df992b.png)
![image](https://user-images.githubusercontent.com/24863266/71681889-e9f3ce80-2dc8-11ea-8c86-0f6dafd6bdb8.png)
![image](https://user-images.githubusercontent.com/24863266/71681910-fbd57180-2dc8-11ea-8196-c6b2a088f3c4.png)
![image](https://user-images.githubusercontent.com/24863266/71681924-05f77000-2dc9-11ea-8ac9-27ed50cb6cc8.png)

**Comment by egamma** [comment]
This status bar item is contributed by the C# extension. The VS Code recommendation is to use codicons for status bar icons https://microsoft.github.io/vscode-codicons/dist/codicon.html.

Please report the issue against the C# extension.
