### ISSUE TITLE
Intellisense based on variable contents in debug session

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#88009]
Mainly TypeScript, but other languages could also benefit. I would be nice if, when in a debug session, intellisense could provide completions based on an `any` variable's actual contents:

```ts
function getDataFromApi(): any {
   return {
     some: "data",
     which: { has: "fixed structure, but no typedefs yet" }
   }
}

const data = getDataFromApi();
const formatted = data.|
```

If I break after the `data` assignment and my cursor is at the pipe, it would be cool if TS could give me completions based on the actual value of the variable, rather than its usual `any` type, similar to how the debug console works.

Use case is that I'm working with a complicated structure returned by a graphQL endpoint, and I don't have types for it, but the structure is constant, so it would be cool to be able to write data manipulation code I need using the actual data as a guide for intelisense suggestions. 

Or maybe a way to pull a type out from the runtime value of a variable? @mjbvz

**Comment by mjbvz** [comment]
This is out of scope of the TS Server that powers our existing JS/TS intellisense but could come in through a separate completionItemProvider. An extension may even be able to implement the provider (although I'm not sure if our debuggers expose enough hooks for it to do so)

**Comment by weinand** [comment]
This feature makes perfect sense and is (revert) related to our Roadmap item "Leverage language services to improve debug experience."

I'll investigate what it needs to support this.

**Comment by weinand** [comment]
If a debug session is active, a debug extension could contribute a `completionItemProvider` that uses a DAP `evaluateRequest` to retrieve the actual value of the symbol/expression on the left side of the caret.

**Comment by roblourens** [comment]
It seems that it is possible for extensions to implement this if they want to, and I don't think there's anything for vscode to do right now.
