### ISSUE TITLE
Powershell PSScriptAnalyser not working in Insiders builds

### ISSUE THREAD

**Issue by simon-michaud** [Microsoft/vscode#8801]
- VSCode Version:1.3.0-Insiders / Commit a1293f50
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. VSCode + Powershell Extension + Install-Module PSScriptAnalyser
2. No automatic analysys of ps1 / psm1 when  **"powershell.scriptAnalysis.enable": true** in _Default Settings_

Works from command line **Invoke-ScriptAnalyser**

**Comment by joaomoreno** [comment]
This issue was moved to PowerShell/vscode-powershell#218
