### ISSUE TITLE
Can I get rid of auto horizontal scrolling?

### ISSUE THREAD

**Issue by keepgoingdev** [microsoft/vscode#88018]
Issue Type: <b>Bug</b>

Hi,
I am a fan of VS Code, but I just realized that there is something annoying function which scrolls automatically when lines are long.
This blocks me coding?
Is there any way for me to get rid of this?
Thanks

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

**Comment by egamma** [comment]
/needsMoreInfo can you illustrate in which cases the horizontal scrolling is annoying and blocks your from coding?

One way to disable horizontal scrolling is to enable `Toggle Wordwrap` (`View>Toggle Wordwrap`)
