### ISSUE TITLE
Typescript and JS dying

### ISSUE THREAD

**Issue by rohitkumar377024** [microsoft/vscode#88011]
Issue Type: <b>Bug</b>

Just cloned a JS project from PayTM and it is showing such issue.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
auto-rename-tag|for|0.1.1
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.2
LiveServer|rit|5.6.1

</details>

**Comment by ChaseKnowlden** [comment]
Kamino cloned this issue to [ChaseKnowlden/vscode](https://github.com/ChaseKnowlden/vscode/issues/1)

**Comment by rohitkumar377024** [comment]
Worked.
