### ISSUE TITLE
Find "files to include" is case sensitive on case insensitive file system

### ISSUE THREAD

**Issue by danmosemsft** [microsoft/vscode#88014]
Issue Type: <b>Bug</b>

On Windows, have a bunch of files in your workspace with the extension ".cs". Search for some string in them, using ".CS" in the "files to include". It doesn't find anything -- you have to match the case, ie, ".cs".
![image](https://user-images.githubusercontent.com/6385855/71700862-1a148080-2d7b-11ea-8842-221d23f0a3f9.png)

![image](https://user-images.githubusercontent.com/6385855/71700869-213b8e80-2d7b-11ea-8b29-239bef4c7b8a.png)

Is this intentional on Windows? On Windows, file system queries generally ignore case. Counter argument here is a Windows developer collaborating with a Unix developer via Git, but it's still likely to be surprising to them.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.79GB (49.57GB free)|
|Process Argv|\git\runtime|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
LinkCheckMD|bla|0.3.1
gitlens|eam|10.2.0
remote-wsl|ms-|0.41.6
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by roblourens** [comment]
Yeah, originally the tool we use for search didn't support case-insensitive glob patterns. Now it does and we tried to adopt it but got stuck on some issues. I still plan to fix it - https://github.com/microsoft/vscode/issues/10633

**Comment by danmosemsft** [comment]
thanks @roblourens not sure why I didn't find those dupes.
