### ISSUE TITLE
auto refactor import when split code into multiple files

### ISSUE THREAD

**Issue by moun3iim** [microsoft/vscode#88010]
let's suppose that we have two files named `file1.js` and `file2.js`, the first contains two functions :
```
export const foo1 = () => { ... } 
export const foo2 = () => { ... } 
```

and the secode import them : 

`import { foo1, foo2 } from './file1.js'`

now we've got in our minds that we want to split `file1.js` into two different files like this :
```
// file1_1.js
export const foo1 = () => { ... } 
```
```
// file1_2.js
export const foo2 = () => { ... } 
```
is it possible to automate the process of updating `file2.js` to automatically update import as bellow?
```
import { foo1 } from './file1_1.js'
import { foo2 } from './file1_2.js'
```
I mean it's a time saver because I've always found myself in a situation where I want to refactor my code, and I face the problem where I have to update it manually

**Comment by mjbvz** [comment]
This sound be a good candidate for an extension

Then if that proves popular, we could look at integrating it into VS Code itself
