### ISSUE TITLE
Multipe cursors 

### ISSUE THREAD

**Issue by Naveen562117** [microsoft/vscode#88028]
Issue Type: <b>Bug</b>

i was deleting part of HTML code 

And i just saw Multiple cursors appear,

i dont remember the steps to exactly reproduce the bug 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2365M CPU @ 1.40GHz (4 x 1397)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0

</details>

**Comment by Naveen562117** [comment]
I am not sure this is a bug or feature , I got 3 cousor and when I type something it reflected in all 3 line

**Comment by gjsjohnmurray** [comment]
This new 1.41 feature is described in the release notes including information on how to turn it off. Several issues have been raised about it, and some are already resolved in the 1.42 Insiders build. Please search for 'mirror cursor' to see if any describe what you are seeing. If yes, close this as a duplicate. If not, give more information on how exactly to reproduce yours.

**Comment by Naveen562117** [comment]
Hope it is duplicate issue 

I just wanted to inform about the issue i faced and I am happy if it is already been rectified 
Thank you
