### ISSUE TITLE
 Mouse back and forward buttons do not work on Mac OS anymore 

### ISSUE THREAD

**Issue by TooXu** [microsoft/vscode#88029]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

Does this issue occur when all extensions are disabled?: Yes

I know it's duplicate of #71318, but that issue is closed and the problem is still existing.

**Comment by TooXu** [comment]
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

 The problem still exists.

**Comment by TooXu** [comment]
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z (2 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

The problem still exists.

**Comment by firzok** [comment]
Can someone please have a look at this I really need the mouse buttons to work? They were working fine on my Ubuntu machine but on Mac, it does not work.

**Comment by bpasero** [comment]
I cannot reproduce, clicking mouse buttons 4 and 5 on my mouse navigate back and forward. Make sure `workbench.editor.mouseBackForwardToNavigate` is set to `true`.

**Comment by TooXu** [comment]
![image](https://user-images.githubusercontent.com/11987019/98207863-48548500-1f77-11eb-9ed9-7e9f027dbade.png)

**Comment by bpasero** [comment]
@TooXu can you do this:
* open https://jsfiddle.net/dmq8xt9b/
*  click with the mouse button 4 or 5 into the red area
* see if you see a dialog opening telling you which button was pressed

**Comment by andreialecu** [comment]
@bpasero I'm experiencing the same issue and can reply to your question above:

* On Mac: 
  If I open the fiddle in Safari clicking button 4 and 5 in the red area doesn't do anything. 
  In Chrome clicking button 4 and 5 results in the page navigating back/forward - no alerts.

* Just a note: On Windows I can see the alerts.

I'm using a Logitech MX Master 3 and have the "Logi Options" software from Logitech installed.

**Comment by bpasero** [comment]
@andrecasal yeah the browser navigation makes this hard to test, can you only test pressing the button that would normally "Forward" so that you dont leave the page and can still test this.

**Comment by andreialecu** [comment]
From what I have found out, MacOS doesn't support more than 3 buttons for the mouse. So button 4 and 5 might not be able to be detected as such.

The "Logi Options" software is set to map button 4 and 5 as Forward/Back. I'm not sure exactly what those mappings mean, but Chrome can use them properly.

**Comment by andreialecu** [comment]
@bpasero as mentioned, there are no alerts on MacOS for mouse 4 and 5. I have only mentioned that it navigates back/forward to validate that Chrome does catch it, the page itself never reacts to those buttons.

Some references: 
https://apple.stackexchange.com/questions/110177/logitech-mouse-how-can-i-use-additional-buttons/303961#303961
https://superuser.com/questions/1216047/universal-back-forward-mouse-buttons-in-osx-instead-of-m4-m5

**Comment by bpasero** [comment]
I am using a Logitech mouse btw and it works just fine in Chrome. Clicking mouse buttons 4 and 5 shows the dialog. 

Since this seems to be hardware / upstream dependent, I do not see how VSCode can fix this. I suggest to open a bug against Chrome: https://bugs.chromium.org/p/chromium/issues/list

**Comment by andreialecu** [comment]
@bpasero do you have Logi Options installed? This link provides further information: https://superuser.com/questions/1216047/universal-back-forward-mouse-buttons-in-osx-instead-of-m4-m5

It seems that it simulates a swipe event, which VSCode probably doesn't detect.

**Comment by bpasero** [comment]
No I do not have any specific software installed from Logitech.

**Comment by andreialecu** [comment]
@bpasero I have uninstalled "Logi Options" and it started working. I can see the alerts now. It seems that Logi Options makes the buttons turn into swipe events. I haven't found a way to disable this.

I kind of need "Logi Options" for other things, I'm using Logitech Flow for cross-computer usage between Windows and MacOS.

Since it works in Chrome, and lots of other apps via the simulated swipe event, perhaps #79078 should be reconsidered.

**Comment by TooXu** [comment]
> @bpasero I have uninstalled "Logi Options" and it started working. I can see the alerts now. It seems that Logi Options makes the buttons turn into swipe events. I haven't found a way to disable this.
> 
> I kind of need "Logi Options" for other things, I'm using Logitech Flow for cross-computer usage between Windows and MacOS.
> 
> Since it works in Chrome, and lots of other apps via the simulated swipe event, perhaps #79078 should be reconsidered.

Is indeed caused by this reason

**Comment by firzok** [comment]
I can confirm all the things @andreialecu posted. I am using Logitech MX Master 1 on macOS. 
The same reason I need the software for other apps. So maybe if there is a way to have it work please do let us know.

**Comment by andreialecu** [comment]
I was able to find a workaround.

In`Logi Options` (top-right) you can create a new profile just for Visual Studio Code and map:

Forward to `CTRL+SHIFT+-`
Back to `CTRL+-`

![image](https://user-images.githubusercontent.com/697707/98832717-d207c500-2445-11eb-88d9-ef1eaffc57fb.png)

**Comment by TooXu** [comment]
![image](https://user-images.githubusercontent.com/11987019/99023611-e3fd7b00-259f-11eb-83c8-848716f3a3da.png)
I'm using a cheap series of mouse. It doesn't have the features you show.

> I was able to find a workaround.
> 
> In`Logi Options` (top-right) you can create a new profile just for Visual Studio Code and map:
> 
> Forward to `CTRL+SHIFT+-`
> Back to `CTRL+-`
> 
> ![image](https://user-images.githubusercontent.com/697707/98832717-d207c500-2445-11eb-88d9-ef1eaffc57fb.png)

**Comment by simuhunluo** [comment]
果然卸载 罗技的那个软件就可以用了

**Comment by meganrogge** [comment]
@bpasero I can confirm this isn't working for me on Mac OS using a Logitech mouse. Using edge, on JS fiddle I don't see the alerts and forward/back don't work. On chrome, forward/back works. this is a feature I'll greatly miss in VS code, as it's so helpful to navigate the history with just button clicks. lmk if I can help to investigate a solution to this.

**Comment by meganrogge** [comment]
I debugged and our event listener doesn't pick up the mouse down when I use buttons 4/5 here https://github.com/microsoft/vscode/blob/6c89a38cfcc8d6ae4b4804302b709f5256e4a02b/src/vs/workbench/services/history/browser/history.ts#L162

**Comment by bpasero** [comment]
@meganrogge can you try a HTML fiddle outside of VS Code in Chrome to see if you can get mouse buttons 4/5 to fire any of the mouse events? There is also `auxclick` now, maybe that event is fired instead?

Refs: https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event

**Comment by meganrogge** [comment]
Auxclick fires on middle click. On chrome, I can't get it to fire any event when buttons 4/5 are clicked 😢

**Comment by meganrogge** [comment]
Could we consider exposing the command so that a keyboard shortcut can be assigned in cases like this, when those buttons don't work?

**Comment by bpasero** [comment]
`workbench.action.navigateBack` & `workbench.action.navigateForward`

**Comment by meganrogge** [comment]
thanks 👍🏼
