### ISSUE TITLE
Release the window manager from VSCode in separate OSS project

### ISSUE THREAD

**Issue by alexkreidler** [microsoft/vscode#88027]
VSCode has innovated both in editors and web and developer tooling because it has distributed [Monaco](https://microsoft.github.io/monaco-editor/), the core editor that powers VSCode, in its own package with its own branding and documentation.

This has spawned a [new](https://github.com/cdr/code-server) [array](https://codesandbox.io/s/competent-minsky-qo2lx) [of](https://stackblitz.com/edit/react-vhz6z2) [projects](https://www.eclipse.org/che/) that use Monaco to build better web code editors.

I think that VSCode could do the same thing for desktop + web based window managers by releasing its own window manager as a separate project. 

It would provide similar functionality to [GoldenLayout](http://golden-layout.com/) and [PhosphorJS](https://phosphorjs.github.io/examples/dockpanel/), along with the many other React libraries that attempt a subset of their features.

This might also encourage more developers to contribute as they customize it for their own applications, so it could help with many of the [issues tagged "layout"](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Alayout+sort%3Areactions-%2B1-desc).

Providing good integration with electron might allow in the future, if we solve #10121, a whole new set of Electron apps with capabilities rivaling the most powerful native IDEs, photo editors, browsers and other multi-window tools.

Additionally, it would provide a great opportunity for web-based apps to take advantage of the library as well, resulting in new more powerful UIs. Personally, I would love to use the window/layout manager from VSCode in a web React app I'm building as there are no maintained libraries that provide all the features VSCode has.

I'd appreciate any feedback everyone has and would love to hear of any other use cases for a separate library and release system for the window manager.

Thanks for all your hard work!

**Comment by egamma** [comment]
@alexkreidler the idea is great, but we currently have no cycles to do so. This could also be done outside of the core development team.

**Comment by alexkreidler** [comment]
Ok sure, I understand.

Would you be able to point to sections of the code or relevant docs for the window manager API so someone else could?


________________________________

**Comment by egamma** [comment]
Here are some starting points:
- https://github.com/microsoft/vscode/blob/642fb9465e8cf47c9e7fdc1c952675a1f497ffc4/src/vs/base/browser/ui/splitview/splitview.ts
- https://github.com/microsoft/vscode/blob/c2997da2ac72121a46e8e6ce504d5f47495b9ff5/src/vs/base/browser/ui/sash/sash.ts
