### ISSUE TITLE
Recent files not being updated

### ISSUE THREAD

**Issue by leetsin** [microsoft/vscode#88025]
Issue Type: <b>Bug</b>

Open a file from Nautilus using Visual Studio Code.
After making changes close the file.
The File does not appear in Recent(Files).
Same if you create a new file and save in Visual Studio Code.
The File does not appear in Recent(Files).

thanks

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.18.0-147.3.1.el8_1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.72GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch /tmp/hello.txt|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.48
code-spell-checker|str|1.7.20

</details>

**Comment by bpasero** [comment]
@leetsin how exactly do you open the file? And which "Recent Files" list do you refer to, how do you access it?

**Comment by leetsin** [comment]
@bpasero 

I double-click the text file in Nautilus to open it.
code is my default editor so it opens in code, but after i close the file it does not appear in the Recent folder on top of Nautilus.
If I right click the file and click on Open With Other Application and choose Text Editor, the file appears as expected in Recent on closing.
Attaching a screenshot.

![vs code nautilus recent](https://user-images.githubusercontent.com/25386850/71806734-949d1300-308f-11ea-86ea-92473ecd8b8d.png)

**Comment by bpasero** [comment]
This sounds like an issue you should report to Nautilus. I do not know what VSCode can do to add entries there.

**Comment by leetsin** [comment]
Most Linux Applications adds entries in Recent:- Image viewers, Document Viewers, Media players, Office Applications, etc.

**Comment by bpasero** [comment]
//cc @Tyriar @deepak1556 @joaomoreno  if you have any clues. I am not entirely sure how we associate text files with Code on Linux.

**Comment by Tyriar** [comment]
File types are associated here: https://github.com/microsoft/vscode/blob/18bbf28f2c35ab147bd1ec5a43dd32f5f52003a1/resources/linux/code.desktop#L11

Not sure how things end up in Nautilus' recent tab.

**Comment by leetsin** [comment]
Hi,

found this.

https://developer.gnome.org/gtk3/stable/GtkRecentManager.html

and an old one.

https://stackoverflow.com/questions/39836725/how-does-one-add-an-item-to-gtks-recently-used-file-list-from-python

**Comment by leetsin** [comment]
@bpasero 

I had installed code-insiders before uninstalling it and installing the stable version.
could that be the cause of an issue ?
