### ISSUE TITLE
Can't show/run task when disable extension TypeScript and JavaScript Language Features

### ISSUE THREAD

**Issue by dbchord** [microsoft/vscode#88026]
- VSCode Version: Version: 1.41.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open workspace
2. Add simple task in .vscode/tasks.json
3. Try to run task, and show up
4. Disable extension @builtin `vscode.typescript-language-features`
5. Try to run task again, and then not show list

Does this issue occur when all extensions are disabled?: No

![screencast](https://user-images.githubusercontent.com/51242829/71705397-1bdd5300-2e12-11ea-8a3f-eb026f2be680.gif)

**Comment by alexr00** [comment]
I think this is fixed by 90ca98af024903ad6d95887a4aa4587221f9c008
Can you try again with Insiders? https://code.visualstudio.com/insiders/
