### ISSUE TITLE
The word error in sidebar debug

### ISSUE THREAD

**Issue by Remote-version-git** [microsoft/vscode#88020]
https://github.com/microsoft/vscode/issues/88020#issue-544824338
![image](https://user-images.githubusercontent.com/43395809/71704131-6dd2a880-2e13-11ea-9601-3d4da99ff90b.png)

**Comment by Remote-version-git** [comment]
![image](https://user-images.githubusercontent.com/43395809/71704147-8478ff80-2e13-11ea-9f7d-25a3764248dc.png)

**Comment by isidorn** [comment]
Thanks for filling this, however we have changed this wording in vscode insiders, thus this is already fixed. Now we say
"To customize Run and Debug"
