### ISSUE TITLE
Fluent design theme

### ISSUE THREAD

**Issue by Chandrawk27** [microsoft/vscode#88021]
Issue Type: <b>Feature Request</b>

I am tired of trying various types of themes available in the extension. At the moment I have not found another interesting theme. Looks like if VS Code makes the theme "fluent design" will look attractive, cool and elegant.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by misolori** [comment]
Duplicate of #26572
