### ISSUE TITLE
Selection > Add Next Occurrence goes backwards

### ISSUE THREAD

**Issue by morganwdavis** [microsoft/vscode#88022]
Issue Type: <b>Bug</b>

In HTML mode while editing CSS rules in a <style> tag, selecting some text and choosing Selection > Add Next Occurrence (typing Control-D on Windows) causes previous (not next) occurrences to be selected.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.95GB (7.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
sqlformatter|bre|0.0.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.11
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.18.0
unicode-substitutions|Gle|2.2.5
vscode-phpfmt|kok|1.0.30
vscode-apache|mrm|1.2.0
python|ms-|2019.11.50794
vscode-typescript-tslint-plugin|ms-|1.2.3
php-docblocker|nei|2.1.0
material-icon-theme|PKi|3.9.2
partial-diff|ryu|1.4.0
rewrap|stk|1.9.1
change-case|wma|1.0.0
markdown-pdf|yza|1.4.1
markdown-all-in-one|yzh|2.6.1

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
This does not reproduce for me. Can you try disabling all extensions? Or am I doing something differently?

![b](https://user-images.githubusercontent.com/4033249/72150711-76445980-33a6-11ea-9ca4-8333e3e43e77.gif)

**Comment by morganwdavis** [comment]
It happened again since I posted this, but now I can't repro on any of my systems. Thanks for verifying. Closing.
