### ISSUE TITLE
Do not pollute shell history with automatically executed debugger commands

### ISSUE THREAD

**Issue by neonsea** [microsoft/vscode#88038]
Currently, when a debugger is executed (ie by hitting F5), a terminal is opened and the debugger is executed as a command. 

This command can get pretty long as it also changes to the working directory and sets some environment variables. Running the Python debugger in a simple project with only one file runs a command which is 243 characters long.

This, however, means that these commands which are not meant to be run by the user but are instead run automatically are still included in the user's shell history file by default.

I propose changing the command generation function `prepareCommand()` to include a space at the very beginning - on many shells across various distros, `$HISTCONTROL` is set to not add commands to history if they start with a space character. This also gives some control to the user whether they'd like for the debugger commands to be stored in history or not.

**Comment by B0sh** [comment]
If you were wondering why someone might want this, I like that the history is there. All the time I go to my command line and use up arrow enter to rerun the last auto generated command. I've also gone through the history a bunch to rerun previous auto generated commands too.

**Comment by neonsea** [comment]
Aye, this is why I opted for simply adding a space instead of something more aggressive such as `unset $HISTFILE` - the shell is still in control whether to preserve history or not with `$HISTCONTROL`.

**Comment by connor4312** [comment]
This works for the integrated terminal, but I noticed the external terminal doesn't get the space  on OSX

![image](https://user-images.githubusercontent.com/2230985/75372869-06b6fa80-587e-11ea-8e7c-26836c5f2762.png)

**Comment by weinand** [comment]
On MacOS the leading space character seems to get dropped in the Applescript that talks to the Terminal application. So the feature at hand only works for the integrated terminal for now.

I've created a [new feature request](https://github.com/microsoft/vscode/issues/91689) for the external terminal.

Since @connor4312 has verified that the fix works for the integrated terminal, I'm adding the "verified" label.
