### ISSUE TITLE
after set `terminal.integrated.inheritEnv` to false, vscode could not start an integrated terminal

### ISSUE THREAD

**Issue by dum3ng** [microsoft/vscode#88036]
- VSCode Version: 1.42.0-insider
- OS Version:	elementary OS 5.1 Hera

Steps to Reproduce:

1.in the `settings.json`, set  "terminal.integrated.inheritEnv": false,  then save
2. in another terminal, open a new vscode window
```bash
code .
```
and in the new opened vscode window, integrated terminal can not be opened.
The console show the error message:
```plain
 ERR A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.
