### ISSUE TITLE
Font issue?

### ISSUE THREAD

**Issue by goxr3plus** [microsoft/vscode#88031]
With a space it appears like this :
![Code_2020-01-03_10-28-36](https://user-images.githubusercontent.com/20374208/71713790-df125b80-2e13-11ea-97d2-a653f2b898c0.png)

Without it appears like this:
![Code_2020-01-03_10-28-28](https://user-images.githubusercontent.com/20374208/71713811-eafe1d80-2e13-11ea-9b5a-c0c906e236fd.png)

I mean after `h` the `-` , what might cause this ? I mean it's minor but i am curious .

**Comment by egamma** [comment]
/needsMoreInfo what font are you using and on which platform do you observe this behaviour.

**Comment by goxr3plus** [comment]
@egamma I am on Windows 10 November Edition , i am using Font :

![image](https://user-images.githubusercontent.com/20374208/71716366-23eec000-2e1d-11ea-8d5e-6d32344a569f.png)

**Comment by egamma** [comment]
@goxr3plus do you have the setting `editor.fontLigatures` enabled and can you reproduce the behaviour when you have fontLigatures disabled?

**Comment by goxr3plus** [comment]
@egamma  There use to be a button in settings for enable/disable fontligatures but i can't find it anymore.

**Comment by goxr3plus** [comment]
Okay i found out modifying settings , that happens only when `editor.fontLigatures=true`

**Comment by egamma** [comment]
Then this is the expected behaviour pls see https://code.visualstudio.com/blogs/2017/06/20/great-looking-editor-roundup#_font-ligatures
