### ISSUE TITLE
iPython - Plotly VBox widget not rendering

### ISSUE THREAD

**Issue by thierryd25** [microsoft/vscode#88035]
- VSCode Version: 1.41.1
- OS Version: WIN 10

Steps to Reproduce:
My purpose is to display a plotly graph with a small table and buttons just below. I am using a FigureWidget declaration for each object, then I group them in a Box widget for final display

1. In Jupyter Notebook environment, I get the expected graphical display
2. In VSCode with Python 3.8.1 interpreter, I only get the text display of the VBox structure 
3. When displaying each object separately with xxx.show() command, the graphical output works correctly (applicable to graph and table only)

It looks like a plotly VBox/HBox widget cannot be displayed in VSCode or I am doing something wrong.

Thanks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by BenedictWilkinsAI** [comment]
This issue is not caused by an extension...
