### ISSUE TITLE
Multiprojects as single project 

### ISSUE THREAD

**Issue by bespilotnayakartoshka** [microsoft/vscode#88030]
Hello ! :) 

I think it would be nice to have ability to open single project as multiprojects in windows(or something like that). 

I mean, like currently i have N projects and every time during run vscode i have to open every time N windows to prepare my editor for work. It require sometime and sometime doesnt comfortable. (Workspace doesnt solve it, coz i wish to separate)

For example, i open MySuperMicroserviceProject -> then i have N windows which relates to this :) 
Or not windows, may be think about how to manage it. 

May be i am wrong and this feature already exists or solved, but i didnt found :< 
I will be very thankful for any suggestions :) 

Thanks.

**Comment by egamma** [comment]
Pls see https://code.visualstudio.com/docs/editor/multi-root-workspaces
