### ISSUE TITLE
Missing debugger column indicator arrow

### ISSUE THREAD

**Issue by Unc3nZureD** [microsoft/vscode#88037]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Personally I tried this only with Typescript, and a custom language server, but I suppose it's a generic issue. When the language supports breakpoints bps on columns as well (eg. TS) the little yellow indicator arrow is not appearing when the code is stopped at a specific column.

For example:
![image](https://user-images.githubusercontent.com/8837736/71724366-5a820600-2e30-11ea-8692-4ac749f62a35.png)
Currently the debugger is stopped at the cursor and this is the only thing showing me where the debugger is standing at. If I move the cursor it will be impossible to tell if the debugger it stopping at a breakpoint or I've just stepped on the line, but not yet reached the bp.

It was working before the version 1.4x.x (not sure if 1.40.x is affected as well)

- Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/86469#issuecomment-565104652

Might already be fixed in Insiders. Can you try that?

**Comment by isidorn** [comment]
@Unc3nZureD thanks for filling this, however this is fixed in insiders https://code.visualstudio.com/insiders/
If you can reproduce with vscode insiders let us know and I will reopen this issue

**Comment by Unc3nZureD** [comment]
Insider version:
`Version: 1.42.0-insider (user setup)
Commit: 9349e9a2fdbd1d92824ce99af4a50b6785351b11
Date: 2020-01-06T10:40:10.218Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363`

Sorry for the delay, but for some reason the insider release produces no column breakpoints at all for me (at least for typescript, not sure about others)

Screenshot from insider:
![image](https://user-images.githubusercontent.com/8837736/71831296-e2724500-30a8-11ea-8088-1c9ba92f7c7f.png)

Screenshot from normal user:
![image](https://user-images.githubusercontent.com/8837736/71831402-1cdbe200-30a9-11ea-86c2-af9ac3c841be.png)

Is it some weird issue or really the fix was to remove column breakpoints? :D I don't think :)

**Comment by isidorn** [comment]
Insiders produces column breakpoint candidates for me. 
Can you post exact reproducable steps? Are you debugging in both cases?
Make sure you do not have candidate breakpoints turned off via a setting

**Comment by Unc3nZureD** [comment]
Exact versions:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
```

```
Version: 1.42.0-insider (user setup)
Commit: 9349e9a2fdbd1d92824ce99af4a50b6785351b11
Date: 2020-01-06T10:40:10.218Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

Allright. I was developing my extension, so I'll try with a similar project.
Current VSCode Insider has NO EXTENSIONS installed at all for me.

- Download this as sample:
https://github.com/microsoft/vscode-extension-samples/tree/master/decorator-sample
- Use Vscode version mentioned above.
- Open decorator-sample
- Run `npm install`
- Open extension.ts
- Place breakpoint on line 47 (this contains a new <something> which should have a column bp)
- F5 and try to trigger the extension by opening any file which has number in it :)
- Try to re-add breakpoint or do something, nothing seems to make the column bp appear

The line does not seem to have any column bp:
![image](https://user-images.githubusercontent.com/8837736/71837142-fff9db80-30b5-11ea-9ff6-4fcaa2c4b2fe.png)

I tried to search in settings for `candidate breakpoint` but it was enabled, so it should be all right.

Can you reproduce the issue?

**Comment by Unc3nZureD** [comment]
@isidorn bump?

**Comment by isidorn** [comment]
Reopening, will investigate in the future.

**Comment by Unc3nZureD** [comment]
Just a quick note that it still persists in the new stable 1.42.0 version.

**Comment by Unc3nZureD** [comment]
I can confirm that it's perfectly working in 1.39.2

**Comment by Unc3nZureD** [comment]
Just a small picture how it should be looking normally. This was shooted on vscode v1.39.2
On any further versions it's not appearing.

![image](https://user-images.githubusercontent.com/8837736/75145650-a8f9a580-56f9-11ea-80b7-3a02592b4a1c.png)
