### ISSUE TITLE
No commit possible from GUI after resolving all merge conflicts

### ISSUE THREAD

**Issue by giliambreems** [microsoft/vscode#88034]
When having resolved all the merge conflicts from within VS Code, the resolved issues/file is not visible under "Staged Changes" and doing a "Commit All" in the action-menu, will return the error that there is nothing to commit.

Workaround: a manual "git commit" from the terminal will do the commit properly.

I am using v1.41.1

**Comment by joaomoreno** [comment]
@giliambreems Can you provide specific and exact steps so other people can reproduce your issue?

**Comment by CherryDT** [comment]
Maybe your change resolution ended up in keeping everything as is, i.e. no changes? In this case it's a duplicate of #7989 and already fixed by now (there is now an option to click "Create Empty Commit" when this message appears).

**Comment by lszomoru** [comment]
@giliambreems, since the issue has been last updated we have made quite some improvements to this flow. 
I will go ahead and optimistically close this issue but in case you are still able to reproduce the issue please feel free to reopen the issue. Thanks!
