### ISSUE TITLE
The TypeScript language 

### ISSUE THREAD

**Issue by katrinekolleskov** [microsoft/vscode#88043]
Issue Type: <b>Bug</b>

Got the error: The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|16.00GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.18.0
vscode-peacock|joh|3.2.0
chat|kar|0.31.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
vsliveshare|ms-|1.0.1404
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
sass-indented|rob|1.5.1

</details>

**Comment by egamma** [comment]
/needsMoreInfo please provide more info when this happens. Can you reproduce this behaviour? Can you share the code that triggers this behaviour?
