### ISSUE TITLE
IntelliSense is loading

### ISSUE THREAD

**Issue by amirsh1639** [microsoft/vscode#88042]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by hasenov** [comment]
I also have problems with IntelliSense loading last time! When i open vsc, intellisense works fine for like 1 min, but then it's stops working, i've deleted all extensions, but nothing chages.

**Comment by hasenov** [comment]
Reinstalled vsc 3 times, same :/

**Comment by znoOb** [comment]
I have the same bug

**Comment by egamma** [comment]
@znoOb @hasenov not clear that this is the same issue, please provide separate issues with detailed information about your setup.

**Comment by nicolopezuruguayo** [comment]
Same here, no way to make it work, it used to be fine in past versions with same conf
