### ISSUE TITLE
default values missing for workspace.getConfiguration().get in resolver

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#88044]
On master:

- the test-resolver extension is a UI extension defining a resolver and some configuration options
- In https://github.com/microsoft/vscode/blob/6f1ee4b66cc47b08e523ed8a78291258aa38ad9e/extensions/vscode-test-resolver/src/extension.ts#L29
add 

```ts
outputChannel.appendLine(JSON.stringify(vscode.workspace.getConfiguration('testresolver').inspect('startupDelay')));
outputChannel.appendLine(JSON.stringify(vscode.workspace.getConfiguration('testresolver').inspect('startupError')));
```
- run vscode from sources, invoke `Remote-TestResolver: New Window`
- in the remote window that opens, check the `TestResolver` output view
```
{"key":"testresolver.startupDelay"}
{"key":"testresolver.startupError"}
```
The default values are missing.

Same when accessing `workspace.getConfiguration('testresolver).get('startupDelay')`

I have the same problem in the Remote WSL extension.

**Comment by sandy081** [comment]
This is because resolver extensions are activated even before their contributions are scanned.

@alexdima FYI

**Comment by sevillal** [comment]
@alexdima is there any plan to fix this?

**Comment by legomushroom** [comment]
Hit this in the GH Codespaces extension recently, since it is a resolver extension, the setting default is not present before the connection is fully established 😊 Worked around this by adding the default in the JS code, not ideal since could diverge with the package.json value at some point, but works for now 👍

**Comment by vanowm** [comment]
Perhaps if there was some kind of event or promise which we can use to wait for it to finish loading?
