### ISSUE TITLE
Terminals in editor tabs

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#88056]
I am thinking about creating an extension to display terminals in editor tabs. In the roadmap I saw that you want to add a lot of flexibility to move workbench parts around. Do you have plan to implement something like this yourself? Or does such an extension makes sense even with your plans?

So the question, is whether you have plan to make it possible to have terminals in editor tabs?

**Comment by egamma** [comment]
As part of the work for more flexible workbench layout we will also consider this option. In addition, trying to implement this from an extension might need API that is currently not provided.

**Comment by solomatov** [comment]
@egamma I implemented it in the vscode code base: https://github.com/microsoft/vscode/pull/88796
What do you think?
