### ISSUE TITLE
HTML completion doesn't work with .php files

### ISSUE THREAD

**Issue by RM6SS62** [microsoft/vscode#88053]
As title

- VSCode Version: 1.41.1
- OS Version: Windows 10 pro 1909

Steps to Reproduce:

1. Create a .php file
2. Start writing any HTML tag.

**Comment by freeman133** [comment]
just switched from different code editor and i noticed this issue

**Comment by kanlukasz** [comment]
Are you sure it still doesn't work? I've done the test now and it looks like it's working well

An example with a fresh installation without any custom settings:
![php1](https://user-images.githubusercontent.com/30685349/80917874-f6316d80-8d61-11ea-990a-f5f3669dbd3e.gif)


My env:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by freeman133** [comment]
Yeah works fine now. Thank you for checking
