### ISSUE TITLE
Tab key deletes selection if line wraps over two lines

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#8805]
- VSCode Version: Code - Insiders 1.3.0-insider (a1293f5056e79c3f0e2cd3e24909f41ff4eef472, 2016-07-05T13:09:46.271Z)
- OS Version: Windows_NT ia32 10.0.14379

Steps to Reproduce:

1. write a long line so that text wraps onto the next line (text should wrap on a single line, the problem doesn't seem to appear otherwise)
2. select the whole line by going to the begining of the line, press shift + end, then keep shift down, and press the arrow key to select the part that wraps onto the next line
3. press `tab`: the text is removed instead of beeing shifted to the right

![vscodetabproblem](https://cloud.githubusercontent.com/assets/199648/16618967/54f31a5e-438c-11e6-9c20-b32d29b1e342.gif)

**Comment by alexandrudima** [comment]
This is expected given the change in 0f38435250b9ce748a04676b26d2db7b08943d4a for #4312, which makes it that if a full line is not selected the selected text is replaced with a tab character.

@warpdesign Your selection in this case starts at (1,2) - notice the one space that is not selected from the line. So, this being not a full line selection, the tab character replaces the content. This is unrelated to the text wrapping.

Would you expect a different behaviour?

**Comment by warpdesign** [comment]
@alexandrudima I would exepect a single behavior, not two different depending on what is selected.

As you said, selecting a line, not starting at the begining of the line, and pressing tab will delete the select text.

But, if I keep this selection, and select the full line below, tab will indent the code, and not delete the selected text, although the first line isn't completely selected:

![vscodeselection](https://cloud.githubusercontent.com/assets/199648/16649041/32b34260-4437-11e6-9877-061f359b2b96.gif)

I find it quite inconsistent: I think tab should always indent, or delete, and should not act differently depending on the type of selection (ie: full line, or not, single line or several lines, etc).

**Comment by alexandrudima** [comment]
@warpdesign Is there any other editor that does what you suggest? (i.e. indent line when selecting a portion of text within a line?)

@weinand Care to jump in and motivate #4312 further ?

**Comment by warpdesign** [comment]
@alexandrudima Atom indents the code, no matter if the whole line is selected or not:

![atomtab](https://cloud.githubusercontent.com/assets/199648/16649346/d2cafddc-4438-11e6-8a5a-2ae5739f18c3.gif)

**Comment by alexandrudima** [comment]
That was our behaviour too prior to the fix for #4312.

#4312 asked the exact opposite (that selecting inside a line should not indent, but replace the selection with the tab character). I'm starting to believe this needs to be a configuration option as neither behaviour makes everyone happy.

**Comment by warpdesign** [comment]
@alexandrudima an option would be a good idea.

**Comment by alexandrudima** [comment]
Apologies for me taking so long to figure this out. This does not require any code change and this customization can be easily made via `keybindings.json`. It is preferable to use existing customization methods than to create a new setting.

To get that `tab` **always indents** if there is a selection, please use the following in your `keybindings.json`:

```
   {
        "key": "tab",
        "command": "editor.action.indentLines",
        "when": "editorTextFocus && !editorReadonly && editorHasSelection"
    }
```

**Comment by ekfuhrmann** [comment]
@alexandrudima Thank you so much for a fix to this issue. That said, while this can be resolved in `keybindings.json` using your provided snippet, it took quite awhile to come across this solution. I imagine as more people migrate from Atom.io this will become a more common issue as it is part of the core functionality there. 

Please consider coming up with a better way of documenting this feature or possibly setting it as a toggable setting.

**Comment by alexandrudima** [comment]
Thank you @ekfuhrmann . Your suggestion makes sense. I suppose the best place to do that is in the Atom Keybindings Extension at https://github.com/Microsoft/vscode-atom-keybindings

@chrisdias Could we please add the following rule to the contributed keybindings:
```
    {
        "key": "tab",
        "command": "editor.action.indentLines",
        "when": "editorTextFocus && !editorReadonly && editorHasSelection"
    }
```

This adds a rule that aligns pressing Tab with Atom's behaviour.
