### ISSUE TITLE
Command 'markdown.extension.togglePreview' not found

### ISSUE THREAD

**Issue by tscpp** [microsoft/vscode#88050]
Issue Type: <b>Bug</b>

sometimes when I write fast this error shows up: `Command 'markdown.extension.togglePreview' not found`

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad  CPU   Q9450  @ 2.66GHz (4 x 2670)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey-plus|cwe|2.0.2
vscode-eslint|dba|2.0.11
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
vscode-firefox-debug|fir|2.6.1
code-beautifier|mic|2.3.3
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1404
debugger-for-chrome|msj|4.12.3
platformio-ide|pla|1.10.0
typescript-hero|rbb|3.0.0
vscode-autohotkey|sle|0.2.2
sass-indented|syl|1.7.2
unity-tools|Tob|1.2.3
sort-lines|Tyr|1.9.0
unity-debug|Uni|2.7.2
vscode-icons|vsc|9.7.0
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by mjbvz** [comment]
This is caused by the markdown-all-in-one extension
