### ISSUE TITLE
Candidate port row shows overflow indicator when not overflowing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88059]
![image](https://user-images.githubusercontent.com/323878/71745060-f3f3ec80-2e1d-11ea-89a0-b4a76abca5f9.png)

- The `...` is in the second row unless I make the sidebar much wider

**Comment by alexr00** [comment]
I made a change to truncate the detail earlier (at the first null character) since it shouldn't be the crazy long thing it was. Let me know if that fixes it for you!

**Comment by alexr00** [comment]
Still happening. Looks like there is a lot of white space in there.
