### ISSUE TITLE
my VS code editor blank since I updated it

### ISSUE THREAD

**Issue by Favourval** [microsoft/vscode#88054]
I can't use my VS code editor since I updated it because it has been blank, I tried deleting it and downloaded a new version, after installation, it was still blank, can't use it at all.

**Comment by Favourval** [comment]
Still no answer, am I alone in this?

**Comment by deepak1556** [comment]
@Favourval which OS are you facing this issue with ? Can you disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if the issue still persists.

**Comment by Favourval** [comment]
I'm using windows 7
