### ISSUE TITLE
intellisense problem

### ISSUE THREAD

**Issue by smadixd** [microsoft/vscode#88062]
Issue Type: <b>Bug</b>

something is wrong with my VSCode .. the intellisense is acting normal (for JS) for the first 10 seconds then it stops working 
no autocomplete suggestions
no mouse-hover information
nothing.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.96GB (7.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
dart-code|Dar|3.7.1
beautify|Hoo|1.5.0
discord-vscode|icr|3.13.0
remote-wsl|ms-|0.41.6
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
easyzoom|Nab|0.1.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by 1nfility** [comment]
Same issue, but on mac!

**Comment by Gwokhov** [comment]
Same too, but after removing `node_modules/`, it work again.

**Comment by KytoSai** [comment]
I have same issue, only work in 10s start vscode
But only occur when open a large project. And error with .js file. Vetur work normal with .vue file

I try turn off all extension. But still not autocomplete

**Comment by KytoSai** [comment]
> Issue Type: Bug
> 
> something is wrong with my VSCode .. the intellisense is acting normal (for JS) for the first 10 seconds then it stops working
> no autocomplete suggestions
> no mouse-hover information
> nothing.
> 
> VS Code version: Code 1.41.1 ([26076a4](https://github.com/microsoft/vscode/commit/26076a4de974ead31f97692a0d32f90d735645c0), 2019-12-18T14:58:56.166Z)
> OS version: Windows_NT x64 10.0.18362
> 
> System Info
> Extensions (9)

Fix it here - https://github.com/microsoft/vscode/issues/87905

**Comment by mjbvz** [comment]
@smadixd Where is your code stored? Somewhere other than the `c:` drive?

Also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that fix the issue?

**Comment by zzx0106** [comment]
I think there may be some problems between the node modules's @type file and vscode1.4.1

**Comment by smadixd** [comment]
Problem got solved ... sorry for late update, i just had two conflicting extensions on my vs code i had to remove one.

**Comment by tiagomsmagalhaes** [comment]
@smadixd which extension you had got conflicts with ts code?

**Comment by smadixd** [comment]
it was js code not ts, and i dont remember exactly but they both had to do with the intellisense behavior of my js files... probably cause i was using babel and i had its extension downloaded with some kind of es6 js extension.
