### ISSUE TITLE
Debug Top Strip

### ISSUE THREAD

**Issue by Rjrunner44** [microsoft/vscode#88067]
Issue Type: <b>Bug</b>

when debugging, the top "little debug status strip" is on top of the tab names, so you can't select the tab under the debug status strip. And since the (other bug) windows menu doesn't list other open documents, you can't even switch to some of the files you are editing while debugging.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

**Comment by Rjrunner44** [comment]
![Screen Shot 2020-01-03 at 2 22 30 PM](https://user-images.githubusercontent.com/46289259/71752600-81dad200-2e34-11ea-9435-64a489ca2749.jpg)
You can see there's now other documents in the windows menu (separate bug) and the document under the little "debug gizmo" on top of the tab obscures some files you can't even get to now.

**Comment by gjsjohnmurray** [comment]
The `debug.toolBarLocation` setting allows you to have it docked rather than floating. And even when floating you can drag it downward to move it out of the way of the tabs.

**Comment by gjsjohnmurray** [comment]
> ![Screen Shot 2020-01-03 at 2 22 30 PM](https://user-images.githubusercontent.com/46289259/71752600-81dad200-2e34-11ea-9435-64a489ca2749.jpg)
> You can see there's no other documents listed in the windows menu even though they are open (separate bug) 

#88066 - closed, as designed

**Comment by isidorn** [comment]
Closing as @gjsjohnmurray provided the answer.
For more flexible layout of the debug toolbar please file that issue and you can upvote it
