### ISSUE TITLE
(TS) (Bug) When moving class to directory with same name, the imports are incorrectly auto-refactored

### ISSUE THREAD

**Issue by kizerkizer** [microsoft/vscode#88063]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. In a new folder create a few classes, and call one Foo.ts
2. Have one of the classes import Foo.ts
3. Create a new directory called `foo`.
4. Move all the classes into the new directory.
5. The import of Foo.ts will be re-written to simply `.`, because the rewriter - I presume - has confused the class Foo with the directory foo.

Is this TS plugin specific?

Thanks!

Does this issue occur when all extensions are disabled?: Yes/[Maybe]/No

**Comment by mjbvz** [comment]
Please provide a small, complete sample project that demonstrates this issue
