### ISSUE TITLE
Window Menu

### ISSUE THREAD

**Issue by Rjrunner44** [microsoft/vscode#88066]
Issue Type: <b>Bug</b>

doesn't list or even show all open documents which are in tabs. It only lists the one document of the active tab.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

**Comment by Rjrunner44** [comment]
![Screen Shot 2020-01-03 at 2 22 30 PM](https://user-images.githubusercontent.com/46289259/71752645-acc52600-2e34-11ea-89d6-d3f07074773a.jpg)

multiple files open, but not listed in window menu.

**Comment by egamma** [comment]
The windows menu shows the open windows not the open editors (or documents). Please see https://code.visualstudio.com/docs/getstarted/userinterface#_open-editors  https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_quick-open
https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_navigate-between-recently-opened-files
