### ISSUE TITLE
make folded code not use editor.selectionBackground 

### ISSUE THREAD

**Issue by bobmagicii** [microsoft/vscode#88070]
folded code makes these highlighted bars all the way across the editor, and i hate it. turns out folded lines are using `editor.selectionBackground` as their background color. so then i made it transparent and now of course i cant see text i select. having folded lines use something like `editor.foldedBackground` would make more sense.

**Comment by usernamehw** [comment]
Aren't there already a separate color for them `editor.foldBackground`?

**Comment by aeschli** [comment]
Correct, there's already a separate color: `editor.foldBackground`. It uses a transparent `editor.selectionBackground` as default.

I improved the default, please have a look at it in tomorrows intergration build.
Also I added a settings `editor.foldingHighlight` so you can disable that feature if you don't like it.
