### ISSUE TITLE
[html] mirror cursor: pasting a full line will copy the full line twice

### ISSUE THREAD

**Issue by jsgoupil** [microsoft/vscode#88072]
Issue Type: <b>Bug</b>

If I copy a full line with CTRL+C (my cursor range is empty.)
Then position my cursor on top of a starting tag, it will paste the line above the opening tag and the closing tag.

```
<div>
   <span>Something</span></div>
```

Copy a line like 
```
HELLO
```
Position your cursor on the opening `<div>`

Press CTRL+V.

**Actual Results**
```
HELLO
<div>
HELLO
    <span>Something</span></div>
```

**Expected Results**
```
HELLO
<div>
    <span>Something</span></div>
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-input-sequence|tom|0.2.0

</details>

**Comment by octref** [comment]
This is the default behavior of multiple-cursor. The extra cursor is added because of `html.mirrorCursorOnMatchingTag` setting. You can disable it for now if you don't like it.

**Comment by octref** [comment]
In tomorrow's insiders `html.mirrorCursorOnMatchingTag` is replaced with `editor.renameOnType`. The new implementation fixes this issue. You can find more details here: https://github.com/microsoft/vscode/issues/88424#issuecomment-600840619
