### ISSUE TITLE
quickfix shorcut key

### ISSUE THREAD

**Issue by windwp** [microsoft/vscode#88076]
I need a navigation shorcut key on quickfix .
I use vscode with vim on Window and when i open quickfix menu I need to use arrow key for select options. 

![quickfix](https://i.ibb.co/RpKkCDJ/Annotation-2020-01-04-092832.png)

**Comment by egamma** [comment]
/needsMoreInfo

Have you looked into https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions? Does this cover your needs?

**Comment by windwp** [comment]
@egamma 
Hi i use vscode with vim and when i open a quickfix menu I need to use arrow key for navigation.
The context menu on vscode don't allow to custom navigation.

` {
        "key": "ctrl+j",
        "command": "list.focusDown",
        "when": "listFocus && !inputFocus"
    },
 {
        "key": "ctrl+j",
        "command": "selectNextSuggestion",
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
  `
This shorcut key is only work in some case but it don't work in context menu and quickfix menu.

**Comment by windwp** [comment]
@egamma 
I already try to create an extension for open quickfix menu by this API function 
 vscode.window.showQuickPick
but I can't find anyway to get all code action in vscode API

**Comment by mjbvz** [comment]
Adding @rebornix for Vim and @sbatten since quick fixes uses our standard context menus

**Comment by sbatten** [comment]
I don't see how we could make this work with native context menus. I recommend using AHK or similar to get this behavior. I do this for VS Code because VIM navigation is not too compatible with my keyboard layout.
