### ISSUE TITLE
TypeScript brace matching is incorrect in `${}` strings

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#88075]
- VSCode Version: 1.41.1
- OS Version: Windows

Steps to Reproduce:

1. Move the cursor in the middle of the `)}` in TypeScript code
```
            if (!this.debugChannel) {
                this.debugChannel = vscode.window.createOutputChannel(`${localize("c.cpp.debug.protocol", "C/C++ Debug Protocol")}`);
                this.disposables.push(this.debugChannel);
            }
```

Bug: The paren matching incorrect matches the 1st `{` instead of the `${` one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
Issue confirmed

![image](https://user-images.githubusercontent.com/172399/71768206-5a5b3680-2f14-11ea-94bd-eaecd710e9f9.png)

**Comment by alexdima** [comment]
Reduced repro:
```ts
function hello() {
    console.log(`${100}`);
}
```
