### ISSUE TITLE
When I move file to directory, vscode don't update import route.(Angular9 with Ivy compiler)

### ISSUE THREAD

**Issue by silphir** [microsoft/vscode#88077]
- VSCode Version: 1.41
- OS Version: windows 10 1903
- Angular 9.0.0-rc.7( with Ivy compiler)
in tsconfig.json
```
{
    "angularCompilerOptions": {
        "enableIvy": true,
    }
}
```

vscode don't update import route like...
```import { environment } from './environments/environment';```

Steps to Reproduce:

when I started,
1. install Angular and npm module(with npm i)
2. _when I move file to directory, vscode update import route_
3. npm start(compile and serve)
4. **when I move file to other directory, vscode don't update import route.** 

when don't use Ivy compiler,
1. after I remove node_modules directory
2. install module(with npm i)
3. not using Ivy compiler and npm start("enableIvy": false)
4. _when I move file other directory, then vscode update import route._

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Same root cause as https://github.com/microsoft/TypeScript/issues/35014 I believe

**Comment by silphir** [comment]
ok. unfortunately, I use WebStorm until it fixed.
