### ISSUE TITLE
Make StackView scroll to the top when a breakpoint is hit

### ISSUE THREAD

**Issue by mnovakovic** [microsoft/vscode#88073]
Right now when a breakpoint is hit, the function `updateTreeSelection()` in callStackView.ts is called, and it in turn calls `this.tree.reveal(element)`.

The logic of `reveal()` is that it shows the wanted element at the very bottom of the scroll view. What this means is that in the Call Stack view, we'll only see the thread that hit the breakpoint and the first frame at the very bottom -- Ideally I think we want to show this at the top, so that we can see the whole stack trace, not just the first frame.

**Comment by isidorn** [comment]
@mnovakovic try it out in VS Code insiders from Friday and let us know if it behaves good for you so we add a verified label here. Thanks

**Comment by isidorn** [comment]
@mnovakovic did you get a chance to give this a spin?

**Comment by mnovakovic** [comment]
@isidorn sorry for the late reply. I tested it on the latest Insiders Build and it works as expected -- on breakpoint, the stack view shows the current thread in the middle if there are multiple threads in the program and the behavior is not changed compared to previous version if there are fewer threads.

**Comment by mnovakovic** [comment]
Also another question for you @isidorn. 

I can see that you guys (i.e. the VSCode team at Microsoft) are working heavily on Debugging UX improvements and our teams at Facebook could also suggest a few improvements we could benefit from. What is the process on picking the improvements to work on? Is it only done via feature requests? If so, how do you pick and prioritize the requests?

**Comment by isidorn** [comment]
Thanks for coming back, adding verified label.
For suggestions on improvments please create new feature requests. Feel free to ping me @isidorn on them. Thanks
