### ISSUE TITLE
Extension page overlaps top of terminal window

### ISSUE THREAD

**Issue by lukaasm** [microsoft/vscode#88082]
Issue Type: <b>Bug</b>

1. Have open terminal
2. Click 'Manage extensions' in notification popup
3. Extension page will overlap Terminal tab

![ezgif com-optimize](https://user-images.githubusercontent.com/48881/71765865-c54b4400-2ef9-11ea-9b83-0576996cf687.gif)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (2.88GB free)|
|Process Argv|F:\Praca\Sunwell\sunwell_wotlk|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cmake-format|che|0.6.0
LogFileHighlighter|emi|2.7.0
vscode-pull-request-github|Git|0.13.0
theme-karyfoundation-themes|kar|20.0.3
mssql|ms-|1.8.0
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.6
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.3-insiders2
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
debugger-for-chrome|msj|4.12.3
language-ogre-script|par|0.8.4
rust|rus|0.7.0
shader|sle|1.1.4
cmake|twx|0.0.17
vscode-icons|vsc|9.7.0
clang-format|xav|1.9.0

(12 theme extensions excluded)

</details>

**Comment by egamma** [comment]
/needsMoreInfo the problem is not obvious in the animated give. can you please indicate in a screenshot where exactly this overlap happens?

**Comment by lukaasm** [comment]
> 
> 
> /needsMoreInfo the problem is not obvious in the animated give. can you please indicate in a screenshot where exactly this overlap happens?

Here it goes:
![obraz](https://user-images.githubusercontent.com/48881/71770497-5a1b6500-2f2d-11ea-89a7-90695ebda1a9.png)

Part of the header + top border of terminal pane seems to be under the page
