### ISSUE TITLE
C Code block syntax highlighting in markdown is broken

### ISSUE THREAD

**Issue by maple3142** [microsoft/vscode#88087]
Issue Type: <b>Bug</b>

Create a markdown, and add a code block with language "c" and paste the code below. They you will see that the syntax highlighting is broken for "c".
Example C code:
```c
#include "./src/duktape.h"

const char* eval(const char* js_code) {
	duk_context* ctx = duk_create_heap_default();
	duk_push_string(ctx, js_code);
	duk_int_t rc = duk_peval(ctx);
	if (rc != 0) {
		duk_safe_to_stacktrace(ctx, -1);
		const char* stacktrace = duk_get_string(ctx, -1);
		duk_destroy_heap(ctx);
		return stacktrace;
	}
	const char* json = duk_json_encode(ctx, -1);
	duk_destroy_heap(ctx);
	return json;
}
```
Screenshot: ![](https://i.imgur.com/GGWBQww.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-css-formatter|aes|1.0.1
vscode-sqlite|ale|0.8.1
markdown-checkbox|bie|0.1.3
vscode-intelephense-client|bme|1.3.6
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
smali|cra|1.0.1
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
code-runner|for|0.9.15
terminal|for|0.0.10
vscode-yarn|gam|1.7.0
webpack-snippets|gog|0.0.4
vue-snippets|hol|0.1.11
minify|Hoo|0.4.3
rest-client|hum|0.23.0
vscode-cheerio|jas|1.1.0
webpack|jer|2.2.0
nearley|kar|1.0.3
vscode-fix-checksums|leh|1.1.0
g-translate|map|0.0.2
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.14
vscode-attrs-sorter|mrm|2.1.0
vscode-jade-snippets|mrm|1.0.1
vscode-language-pack-zh-hant|MS-|1.41.2
python|ms-|2019.11.50794
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.6
cpptools|ms-|0.26.2
vsonline|ms-|1.0.1424
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
laravel-blade|one|1.20.0
material-icon-theme|PKi|3.9.2
polacode|pnp|0.3.4
vscode-graphql|Pri|0.2.2
ejs-language-support|Qas|0.0.1
quicktype|qui|12.0.46
vscode-yaml|red|0.6.1
LiveServer|rit|5.6.1
background|sha|1.1.23
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
script|sto|0.1.31
language-stylus|sys|1.11.0
nativescript-xml-snippets|tsv|1.0.7
ws-rainmeter|wil|0.2.7
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|2.6.1
swig|zhu|0.0.5
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by mjbvz** [comment]
Same root cause as #34525

Upstream issue with how the c/c++ grammar is written. It makes embedding like this impossible
