### ISSUE TITLE
VSCode once lunched has no visible UI

### ISSUE THREAD

**Issue by drp2136** [microsoft/vscode#88084]
I am using windows-7 64 bits. Once I installed, and lunched the application, its lunched, but nothing showing up. Just a black UI, although while hovering over it, sometimes, the cursor type changes to hand then arrow. I have tried with System Installer, User Installer and the archive file too, but no response. No idea if the issue is with win-7 OS or any other issue, as I have tried same with win-10 and is working fine.

https://prnt.sc/qja9sm

**Comment by cyanidee** [comment]
Try using the `--disable-gpu` command line flag. Looks like your system lacks hardware acceleration support.

**Comment by deepak1556** [comment]
Can you try what @cyanidee mentioned, if it still doesn't work can you launch with `code --verbose` from command line and provide the output. Thanks!
