### ISSUE TITLE
Sync configurations

### ISSUE THREAD

**Issue by rafaelptr** [microsoft/vscode#88086]
Issue Type: <b>Feature Request</b>

Por favor adicionem suporte a importar facilmente configurações com base em uma conta Microsoft, restaurar extensões e configurações feitas.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by egamma** [comment]
If you ask for settings sync, then this is a duplicate and we are already working on it.
