### ISSUE TITLE
Visual Studio Code .Net Core SDK issue.

### ISSUE THREAD

**Issue by anantv10** [microsoft/vscode#88091]
I am using Windows 7. I need to run C# code in visual studio code.
I already installed **.net core 3.1** from microsoft site. Although when I installed the **c# plug in by Microsoft , Powered by OmniSharp.** it gives me below **error**.
**"The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path."**

And after that my terminal stops working. can anyone helps me. also I tried typing dotnet on cmd and then i got another error **"ucrtbase._configure_wide_argv could not be located in the dynamic link library api-ms-win-crt-runtime-L1-1-0.dll"**

**Comment by weinand** [comment]
Please file issue against C# extension.
