### ISSUE TITLE
Can't create file relative to project root

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#88096]
Issue Type: <b>Bug</b>

1. Right click in tree and select `New file relative to project root`
2. Press `enter` to confirm the root `/`
3. Enter any file name

Result: File not found error
Expected: For the file to be created

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:55:38.353Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
vscode-eslint|dba|2.0.11
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
file-icons|fil|1.0.20
gc-excelviewer|Gra|2.1.32
json2csv|kha|0.0.1
l13-diff|L13|0.21.0
git-tree-compare|let|1.7.1
vetur|oct|0.22.6
multi-command|ryu|1.3.0
vscode-fileutils|sle|3.0.0
control-snippets|svi|1.7.1
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.9.6
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo is that context menu command provided by one of your extensions? Can you reproduce the issue when running with all extensions disabled?

**Comment by adamreisnz** [comment]
No, it's not provided by an extension... it's stock VSCode, in the sidebar.

**Comment by gjsjohnmurray** [comment]
> 
> 
> No, it's not provided by an extension... it's stock VSCode, in the sidebar.

Not seeing it in my 1.42 (all extensions disabled):

![image](https://user-images.githubusercontent.com/6726799/71808256-39562b00-3065-11ea-85dd-dc93ec0083e0.png)

Am I looking in the wrong place?

**Comment by egamma** [comment]
The action is contributed by this extension: https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils

@adamreisnz pls report the issue against this extension.

**Comment by adamreisnz** [comment]
Done, filed as https://github.com/sleistner/vscode-fileutils/issues/153
