### ISSUE TITLE
Typescript Language Died

### ISSUE THREAD

**Issue by edsonsenna** [microsoft/vscode#88094]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When I was renaming and moving some folders inside my Angular project the Typescript extension just died.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 7, 5|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv|-psn_0_6923930|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-snippets|hol|0.1.11
Angular2|joh|8.3.0
vscode-docker|ms-|0.9.0
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
RocketseatReactJS|roc|2.2.0
RocketseatReactNative|roc|2.2.0
vue-vscode-snippets|sdr|1.8.0
nativescript|Tel|0.11.0

(2 theme extensions excluded)

</details>

**Comment by edsonsenna** [comment]
A popup opened with this message:

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

Source: TypeScript and JavaScript Language Features (Exten...

**Comment by nick318** [comment]
any updates? I still have this issue
