### ISSUE TITLE
Layer breakers from code/electron-main to vs/workbench

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8809]
Some issues:
- there are dependencies into `vs/workbench` from `vs/code`
- `vs/code/main` has knowledge about git for the askpass and reaches into `vs/workbench/part/git` (this probably asks for some kind of registry to contribute)

**Comment by bpasero** [comment]
We got rid of `userSettings`, so only git remains.

**Comment by bpasero** [comment]
@joaomoreno is the new SCM provider still using `AskpassChannel` and `GitAskpassService`?

**Comment by joaomoreno** [comment]
@bpasero I still haven't removed Git. People can still go back to it. Let's remove it this week. #24014
