### ISSUE TITLE
Offer actions for AppleScript Editor

### ISSUE THREAD

**Issue by googol7** [microsoft/vscode#88093]
I'd like to create a script with the [AppleScript Editor](https://en.wikipedia.org/wiki/AppleScript_Editor) to "remote control" Visual Studio Code.

This doesn’t work at the moment:

`tell application "Visual Studio Code" to set the bounds of the front window to {345, 23, 2560, 1390}`

**Comment by googol7** [comment]
This would be very handy to organize the screen according to the current work situation (2 large screens at home, 1 small LCD on the go, etc.) like described [here](https://gist.github.com/seansu4you87/9595069).

**Comment by nicooprat** [comment]
Also looking forward to this. It would be pretty useful, making it easy to create some shortcuts with Mac touchbar and BetterTouchTool for instance:
![image](https://user-images.githubusercontent.com/645641/83145459-1d772280-a0f5-11ea-9d77-453cce7b65d6.png)

**Comment by deepak1556** [comment]
Support should be provided by runtime Electron, closing as part of issue grooming https://github.com/microsoft/vscode/wiki/Issue-Grooming
