### ISSUE TITLE
https://www.google.com/webhp?hl=ar&sa=X&ved=0ahUKEwjcpdudl-rmAhXpsIsKHVWND6kQPAgH

### ISSUE THREAD

**Issue by mohmmedmeshi** [microsoft/vscode#88090]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by thavlik** [comment]
Yeah, this is sketchy. I would advise against visiting the link in the title.

**Comment by egamma** [comment]
@mohmmedmeshi thank you for the issue. Please open a new issue with detailed steps to reproduce the problem and with an explanation, why someone should follow a particular link.
