### ISSUE TITLE
experimental decorators warning 'ts(1219)' is reported even when 'experimentalDecorators' are enabled

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#88099]
Issue Type: <b>Bug</b>

in tsconfig.json 
```
    "experimentalDecorators": true,

```
is configurated.
But the warning endured.
```
对修饰器的实验支持是一项将在将来版本中更改的功能。设置 "experimentalDecorators" 选项以删除此警告。ts(1219)
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-36-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2253)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|3.73GB (0.10GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
code-gnu-global|aus|0.2.2
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.33.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
file-icons|fil|1.0.20
marp-vscode|mar|0.11.2
binary-viewer|mom|0.0.1
vscode-scss|mrm|0.8.1
vscode-docker|ms-|0.9.0
vscode-language-pack-zh-hans|MS-|1.41.2
cpptools|ms-|0.26.2
typescript-javascript-grammar|ms-|0.0.53
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
vscode-nunjucks-formatter|oki|0.1.3
emoji|Per|0.0.3
material-icon-theme|PKi|3.9.2
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
nunjucks|ron|0.2.3
rust|rus|0.7.0
vscode-scss-formatter|sib|1.4.3
vscode-icons|vsc|9.7.0
react-playground-vscode|wmi|0.0.11

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Are you sure the file is in the correct tsconfig project? Run the `Go to project configuration` command to check this. It should open the jsconfig/tsconfig with experimentalDecorators: true
