### ISSUE TITLE
Ability to set default tasks based on file extension (or glob)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#88106]
## Motivation
our codebase has a mix of different languages. Some .php files some .js files for example.

I need to keep switching the default task depending on which file I’m working on, it can become quite frustrating.

Is it possible to have a default task for that file extension? So when I’m working in JS I can just run the default task, and when I’m in .php I can run the default task for that? 

## launch.json example from a typical project

```json
[
    {
      "label": "Test JS File",
      "type": "shell",
      "command": "yarn jest ${file}",
      "extension": "js",
      "group": {
        "kind": "test",
      },
    },
    {
      "label": "Test PHP File",
      "type": "shell",
      "command": "phpunit ${file}",
      "extension": "php",
      "group": {
        "kind": "test",
      },
    }
]
```

## Backwards Compatibility 
* Option 1: Default tasks can work as they are now, if a task based on file extension is added this can override the default task. So extension based tasks have higher priority.
* Option 2: If no default task is set then fallback to checking if an `extension` has been set. This way `defaultTask` is still guaranteed to work as it does today
* Option 3: Another option is to use globs instead, and run the task by default if it matches the particular glob pattern (see below). This can override `defaultTask`

## Example table (if globs are used)

| Current Open File Extension        | File           | Task  |
| -------------- |:---------:| -----:|
| `.js`      | javascript | Run JS file |
| `.php`      | PHP      |   Run PHP File, or run PHP tests |
| `.test.js` | Javascript test file      |    Run Tests |
| `.html`| HTML File | Open browser with this file

**Comment by RandomFractals** [comment]
this is a great idea. I really like how @lostintangent handled some of those requirements, especially on the preview side with gists and playgrounds in https://github.com/vsls-contrib/gistpad

Perhaps some of that can be ported to this feature implementation too.

**Comment by jasonwilliams** [comment]
A nice to have would be if we can use globs to detect directory and set tasks on that also.
So . `*end_to_end/*.js` would trigger a different test task to the typical unit tests one which has already been set for this project.

**Comment by RandomFractals** [comment]
@jasonwilliams also a great idea, however I am afraid vscode team will mark this request as can be provided by another extension :) ...

**Comment by jasonwilliams** [comment]
Hey @alexr00 its received 20 votes

**Comment by bishayyo** [comment]
Any news on this additional "ability"?

**Comment by KSH-code** [comment]
I need this feature too.

**Comment by trojan-01** [comment]
is there any update regarding this feature?

**Comment by avi-01** [comment]
Is there any update regarding this feature?

**Comment by andybbruno** [comment]
Any news about this feature?

**Comment by greenzebraelephant** [comment]
You could have a task run a shell script, which would determine what to do based on the extension.

This is the task, we pass the file extension and the file path to the shell script:

```
        {
          "label": "Run according to extension",
          "type": "shell",
          "command": "/path/to/your/shell/script",
          "args": ["${fileExtname}", "${file}"]
      }
```

Then the shell script determines what to do according to the extension:

```
#!/bin/bash
case $1 in
	.html)
	chrome "$2"
	;;
	.js)
	node "$2"
	;;
	.py)
	python3 "$2"
	;;
esac
```

**Comment by jasonwilliams** [comment]
Thanks @greenzebraelephant its a nice workaround but the purpose of this issue is so I don't have to maintain a script. We work across different OS's so a bash script wouldn't always work.

**Comment by greenzebraelephant** [comment]
@jasonwilliams Actually I found an even simpler solution: use 'when' and 'editorLangId':
https://stackoverflow.com/a/64248855/9702500

**Comment by jasonwilliams** [comment]
I had a go at this and pretty much have it working. I've done a PR but will need some guidance on having it suitable to merge. 

Here is the functionality.
- if the glob matches it will run that task automatically (globs have a higher priority than defaults).
- Then I remove the glob and it falls back to asking which task to run because there's 2 build tasks set.
- Then I remove "build" from the top task and it runs "blah" because its the only build task there
- 
![glob](https://user-images.githubusercontent.com/936006/150661187-0878761d-e379-4fb7-a7f3-4f244f2dd822.gif)
