### ISSUE TITLE
Vs code delete ; for my js file and setup 2spaces as a tab for one file

### ISSUE THREAD

**Issue by FrozzyBoy** [Microsoft/vscode#8810]
- VSCode Version: Code - Insiders 1.3.0-insider (a1293f5056e79c3f0e2cd3e24909f41ff4eef472, 2016-07-05T13:09:46.271Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.ctrl+shift+f

for other files work perfect. Config setup to 4 spaces as a tab.

**Comment by joaomoreno** [comment]
@dbaeumer: feels like JS formatting, not sure if you are the right person.

**Comment by dbaeumer** [comment]
@FrozzyBoy do you have any additional extension installed. The built in JS formatter doesn't remove ;

**Comment by mjbvz** [comment]
@FrozzyBoy Please try running vscode with `--disable-extensions` and let us know if this still repos. If it does, please add some information about how we can reproduce this issue, along with an example file the demonstrates this.

Thanks.
