### ISSUE TITLE
Slow extensions setup and slow render

### ISSUE THREAD

**Issue by TRCMKR** [microsoft/vscode#88100]
We have written the needed data into you
Issue Type: <b>Performance Issue</b>

It all started from slow project rendering then all ended in vscode lagging

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   219	  3156	code main
    0	    24	  2476	   utility
    0	   178	  3008	   window (haha-classic.html - A$$ AND N0T G4Y - Visual Studio Code)
    0	    76	  1616	     extensionHost
    0	    87	  3664	       "C:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=1616
    0	    11	  1724	     watcherService 
    0	     3	  3968	       console-window-host (Windows internal process)
    0	    32	  2484	     searchService
    0	    65	  3624	   shared-process
    0	   484	  3820	   window (undefined)
    0	    11	  3824	   electron-crash-reporter
    2	    87	  4820	   gpu-process
    1	    63	  7160	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (haha-classic.html - A$$ AND N0T G4Y - Visual Studio Code)
|    Folder (A$$ AND N0T G4Y): 12 files
|      File types: js(4) html(2) json(1) css(1) mp3(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.3
vscode-firefox-debug|fir|2.6.1
google-fonts|lio|0.0.1
debugger-for-chrome|msj|4.12.3
html-preview-vscode|tht|0.2.5
html-css-class-completion|Zig|1.19.0

</details>

**Comment by egamma** [comment]
/needsMoreInfo  please use this guide to narrow down the performance issue https://github.com/microsoft/vscode/wiki/Performance-Issues
