### ISSUE TITLE
Quick suggestions for snippet prefixes that aren't word characters

### ISSUE THREAD

**Issue by andyjeffries** [microsoft/vscode#88104]
- VSCode Version: 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0)
- OS Version: Darwin x64 19.0.0

Steps to Reproduce:

1. Create a snippet containing the following:

```json
"ERB Block": {
	"scope": "erb,html,html.erb",
	"prefix": "%",
	"body": [
		"<% $1 %>"
	],
	"description": "Insert ERB <% %> block"
},
```

2. Open an file with a type of HTML ERB (

Does this issue occur when all extensions are disabled?: Yes (if you remove the scope)

A similar issue about being able to use symbols such as `%` was raised at https://github.com/microsoft/vscode/issues/6358 and it was apparently resolved in 2017. However, as of today I can't get it to work. Nor if I use `=` as another trigger.

These work in Atom and in Sublime Text 3, so it's really slowing down my working with Ruby on Rails sites.

**Comment by jrieken** [comment]
This issue misses info about expected/actual behaviour

**Comment by andyjeffries** [comment]
Expected: the snippet to insert
Actual: I just end up with the prefix and a space

**Comment by jrieken** [comment]
> Open an file with a type of HTML ERB 

We don't insert snippets automatically after opening files. I don't think that would be a good feature (and I also don't think that's what you want) There are multi ways to trigger snippets:

1. F1 > Insert Snippet
2.1 Manually started IntelliSense (aka Ctrl+Space) > Select from IntelliSense
2.2 IntelliSense as you type (aka quick suggestions) > Select from IntelliSense

So, what of those are you trying? Remember that I don't sit next to you and that you have to give me precise and complete steps.

**Comment by andyjeffries** [comment]
Sorry, you're absolutely right, I missed the third step:

3. Type a `%` and hit Tab (assuming Editor's Tab completion is set to `on`)

If I insert the snippet from the command palette, it's listed and works fine. If I do your second option it works fine. If I just type the character and wait (for your third option) it doesn't popup any suggestions.

**Comment by jrieken** [comment]
This actually works for me. With IntelliSense-As-You-Type and also via Tab completions. Any chance your settings are off? What is `editor.tabCompletion` and `editor.quickSuggestions` configured to?

![Jan-06-2020 11-02-08](https://user-images.githubusercontent.com/1794099/71811058-13845280-3074-11ea-9e1d-a45ac92f6a3a.gif)

**Comment by andyjeffries** [comment]
Having just seen you do this in a plain HTML file, I tested that too and you're right, that works for me. Just ot in an `test.html.erb` file.

**Comment by andyjeffries** [comment]
I guess this must be an extension doing something broken then. I'll try disabling them all and re-enabling them one at a time until I find the one causing it.

**Comment by jrieken** [comment]
Maybe different set of trigger characters... Each language defines what characters make up a word and likely erb doesn't include `%`...

**Comment by jrieken** [comment]
Yeah, that's likely it. The [language configuration](https://github.com/microsoft/vscode/blob/c898cc34899bb3b3d5e2bcae881ae9a3f5fa3162/extensions/ruby/package.json#L12) for ruby doesn't spell out a special word definition. That means % isn't part of a word and we only use word starts to know if IntelliSense-as-you-type should start or not.

**Comment by andyjeffries** [comment]
Blank slate and the "Rails" extension installed seems to not work. So I guess it's the html.erb language definition in there?

**Comment by andyjeffries** [comment]
And that package is looking for maintainers (https://github.com/bung87/vscode-rails/issues/15) so I guess it's unlikely that this will get fixed. I'll have to just use another trigger and rewire my brain to use the new trigger. Thanks for your help.
