### ISSUE TITLE
Breakpoints are doubled for javascript (visual broken)

### ISSUE THREAD

**Issue by ShiroYacha** [microsoft/vscode#88109]
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Place a breakpoint in a Javascript file in debug mode (Chrome debugging tools)
2. Breakpoint is displayed twice

Does this issue occur when all extensions are disabled?: Unable to test without chrome debugger

![image](https://user-images.githubusercontent.com/4082699/71786617-84dcea80-300d-11ea-832e-e420bec0c78e.png)

**Comment by isidorn** [comment]
Thanks for filling this issue. This should be fixed in latest, can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
If you can reproduce can you provide exact minimal steps for this? Thanks
