### ISSUE TITLE
[suggestion] phpDoc Parser? Understanding PHP?

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#8811]
- VSCode Version: 1.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a PHP Class with phpDoc Comments
2. Try to mention that class ... You'll see no suggestions. 

It would be great if "Code" will parse my PHP Classes(out-of-the-box). Autocomplete Classnames for use Statements would be also useful!

**Comment by joaomoreno** [comment]
Have you given [any PHP extension](https://marketplace.visualstudio.com/search?term=php&target=VSCode&sortBy=Relevance) a try? Out of the box PHP support will likely not come in the near future.
