### ISSUE TITLE
No symbols found in document for  'video_player.dart' when in a parent level folder.

### ISSUE THREAD

**Issue by jerryzhoujw** [microsoft/vscode#88113]
- VSCode Version:
- OS Version:

## Steps to Reproduce:

1. `git clone https://github.com/flutter/plugins`
2. `cd plugins/packages/video_player`
3. type `code .`
4. click file `video_player/lib/video_player.dart` in vscode's file navigator. 
> Loading document symbols for 'video_player.dart'...

<img width="732" alt="Loading document symbols" src="https://user-images.githubusercontent.com/6405390/71792558-1b43f700-3074-11ea-8494-26bc2853e175.png">

5. and see bellow result:
> No symbols found in document 'video_player.dart'...

<img width="704" alt="No symbols found in document" src="https://user-images.githubusercontent.com/6405390/71792562-20a14180-3074-11ea-93ee-1b3aba903d1f.png">

## PS:
it show outline fine when I open from folder `cd plugins/packages/video_player/video_player`

<img width="613" alt="find symbols 1" src="https://user-images.githubusercontent.com/6405390/71792582-31ea4e00-3074-11ea-8a5c-03f9b9d6851a.png">

or open from folder `cd plugins/packages/video_player/video_player/example`

<img width="1150" alt="find symbols 2" src="https://user-images.githubusercontent.com/6405390/71792593-37479880-3074-11ea-80c6-f79212b730d9.png">

##  Launch with `code --disable-extensions`
Does this issue occur when all extensions are disabled?: Yes

> The active editor cannot provide outline information

<img width="691" alt="The active editor cannot provide outline information" src="https://user-images.githubusercontent.com/6405390/71795582-d45cfe00-3081-11ea-9ad3-8d3f12772ebf.png">

**Comment by egamma** [comment]
Please report the issue against the Dart extension.

**Comment by jerryzhoujw** [comment]
ok

**Comment by jerryzhoujw** [comment]
Do you mean after `code --disable-extensions`, it shows `The active editor cannot provide outline information ` means it's caused by dart extension ?

**Comment by egamma** [comment]
@jerryzhoujw 

>Hi @egamma, do you mean after code --disable-extensions, it shows The active editor cannot provide outline information , which means it caused by dart extension ?

Correct, VS Code does not know how to compute the outline of a `.dart` file. It will never show an outline for a dart file. The outline of a `.dart` file is computed by an extension so this must be an issue with an extension (or your setup), but not with VS Code.

**Comment by jerryzhoujw** [comment]
@egamma  Thank you.
