### ISSUE TITLE
Git: dirty diff decorator reads file into a single buffer

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88119]
Follow up from https://github.com/microsoft/vscode/issues/87205

It looks like the dirty diff decorator is reading an entire file into memory for computing diff. This has a chance of causing out of memory exceptions if the file is very large. The editor is better here because it reads the file into chunks of 65kb. Maybe we should add a specific limit for the dirty decorator or make it chunked too?

**Comment by joaomoreno** [comment]
Dirty diff doesn't read the file at all. It creates a [model reference](https://github.com/microsoft/vscode/blob/1420967188b1a2ef98326cbb30b0fa5fc219b1c4/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1114) so it can [compute the diff](https://github.com/microsoft/vscode/blob/1420967188b1a2ef98326cbb30b0fa5fc219b1c4/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1091).

**Comment by bpasero** [comment]
True, I am not sure what I saw, seems fine to me.
