### ISSUE TITLE
Support follow-mode editor layout

### ISSUE THREAD

**Issue by lissitz** [microsoft/vscode#88118]
> Follow mode is a minor mode that makes two windows, both showing the same buffer, scroll as a single tall virtual window.

https://www.gnu.org/software/emacs/manual/html_node/emacs/Follow-Mode.html

This would be great for files that tend to have a very low number of characters per line, such as jsx.

**Comment by egamma** [comment]
/needsMoreInfo

Thank you for the feature request, can you please elaborate on this and illustrate this with screenshots.

>This would be great for files that tend to have a very low number of characters per line, such as jsx.

**Comment by lissitz** [comment]
It would be similar to the current option View > Editor Layout > Split to the Up/Down/Left/Right, but the new editor would always show the first line that overflows the "parent" editor, their scroll position would be synced. 

- gif, first scrolling and then going up and down with the arrow keys at the borders.

![demo](https://user-images.githubusercontent.com/53315888/71817527-68c95f80-3086-11ea-9213-27309f2c4582.gif)

- 2 columns
![2pane](https://user-images.githubusercontent.com/53315888/71817234-80ecaf00-3085-11ea-8f61-e6da437d47b5.png)

- 4 columns
![4hpanes](https://user-images.githubusercontent.com/53315888/71817298-aed1f380-3085-11ea-90aa-d046d9c41f3c.png)
mixed columns and rows
![mixedpanes](https://user-images.githubusercontent.com/53315888/71817319-bee9d300-3085-11ea-83a2-64f4bae1c407.png)

*jsx example*: In React components, it is commonn (e.g. default in Prettier) to format parameters and attributes each in a new line. The resulting code is often very vertical, and it is common that a function will be longer than the screen height, thus having to scroll back and forth to check the whole function body

- Comparison:
1 column, lots of empty space.
![1](https://user-images.githubusercontent.com/53315888/71818930-a334fb80-308a-11ea-9b00-1f6e50a39ee9.png)
2 columns, can see more, don't need to manually keep both views in sync as we scroll.
![2](https://user-images.githubusercontent.com/53315888/71819134-4dad1e80-308b-11ea-91e0-00f9aba51ced.png)
