### ISSUE TITLE
Cannot see the present working directory when the Terminal opens for the first time.

### ISSUE THREAD

**Issue by phaniallamsetty** [microsoft/vscode#88139]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code
2. Press Ctrl+`

Expected Result: Terminal should display the present working directory as the command prompt
Actual Result: Nothing is displayed. When we start typing, it starts printing after the length of the present working directory.

Does this issue occur when all extensions are disabled?: Yes
![Screenshot_VS](https://user-images.githubusercontent.com/11642091/71824832-6f48de80-3068-11ea-84ac-65f03179b128.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
