### ISSUE TITLE
Insiders doesn't update on first shutdown after running overnight.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8813]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 7

Steps to Reproduce:
1. Come in to work and go to an open Insiders instance (it's been running all night).
2. See banner saying "Insiders will be updated after it restarts."
3. Click "Update Now"

Insiders instance closes but nothing happens. No installation prompt.
If I look in Windows Task Manager, I can see a running Code - Insiders.exe.
If I minimize all open windows, I don't see an installation prompt hidden anywhere.

This has been happening often but not sure when it started.

If I restart code-insiders.exe, next time I get the "Insiders will be updated after it restarts" and click "Update Now", I do get the installation prompt and it succeeds.

**Comment by gregvanl** [comment]
A little more information:
I don't see this issue if the prompt is brought up during my active session, meaning I don't initially see the prompt while working and then I do see the prompt. 
I saw this when I log into my machine, switch to Insiders and the prompt is already visible.

**Comment by gregvanl** [comment]
I think this may be due to the running Code - Insiders.exe mentioned above.  I just saw another case where I shut down Insiders, uninstalled it with Windows Control Panel then tried to install again.  Manual installation failed due to a running Code - Insiders.exe process even though there was no visible instance and I had uninstall the product.

**Comment by gregvanl** [comment]
Happened twice this morning when I had code-insiders open but not using.  Didn't see a stray Code Insider.exe process these times.

**Comment by gregvanl** [comment]
Saw the issue again today.  Same repro, left code-insiders.exe running all night.

**Comment by joaomoreno** [comment]
Sorry for the silence @gregvanl. It's both interesting and strange that you alone seem to hit this very consistently.

**Comment by joaomoreno** [comment]
Do something next morning that you get the update notification:

- Take a screenshot of the contents of `%TEMP%\vscode-update`.
- Try to update. If it fails as mentioned above, post the screenshot here.

**Comment by gregvanl** [comment]
@joaomoreno Failed to update again this morning (actually everyday for the last few weeks). %TEMP%\vscode-update is empty.
![empy vscode-update](https://cloud.githubusercontent.com/assets/12818376/19732852/07515c34-9b57-11e6-8562-fedafeb43eb9.png)
If I relaunch code-insiders and get prompted to update, vscode-update has an exe.
![exe vscode-update](https://cloud.githubusercontent.com/assets/12818376/19733222/3214ff9c-9b58-11e6-8d25-68df2b213282.png)

**Comment by gregvanl** [comment]
For some reason, when the update detection occurs when I'm away from my machine (logged off), the exe is not pulled down.

**Comment by joaomoreno** [comment]
Sorry for delaying this for so long @gregvanl. I'll take a look at it in November. 👍

**Comment by gregvanl** [comment]
I'm seeing this consistently on Windows 7 machines. My Windows 10 machine seems to work correctly. Perhaps Windows 7's sleep is deeper than Windows 10.

**Comment by joaomoreno** [comment]
This seems to be related to [this issue](https://blogs.msdn.microsoft.com/oldnewthing/20110125-00/?p=11673). Also [this](http://stackoverflow.com/questions/6521277/why-does-temp-resolve-to-a-non-deterministic-path-of-the-form-temp-digit).

> The problem lay in the Administrative Templates\Windows Components\Terminal Services\Temporary folders group policy. **If you don't select Do not use temporary folders per session, then these TEMP subdirectories are created.** There is also a knowledge base article describing the registry keys behind these group policies.

I'll close it as it is a Windows 7 issue and it can be fixed by you changing that policy in your system.
