### ISSUE TITLE
Feedback: beak is off now with new icon it seems

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88138]
![image](https://user-images.githubusercontent.com/900690/71824338-98359780-3099-11ea-8090-d6c8f26bf69c.png)

I think it used to be centered with the smiley.

**Comment by egamma** [comment]
Regarding polish, there also is no hover for the feedback item (the smiley didn't have a hover neither)

**Comment by bpasero** [comment]
I added a tooltip and positioned the beak so that it works for both notifications and feedback.
