### ISSUE TITLE
bug: file is exist,but can't search it out 

### ISSUE THREAD

**Issue by jianglinyang8** [microsoft/vscode#88137]
Issue Type: <b>Bug</b>

bug: file is exist,but can't search it out 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (24.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|10.6.0
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
EnglishChineseDictionary|Cod|0.0.11
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.11
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.18.0
code-runner|for|0.9.15
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
docthis|joe|0.7.1
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.41.2
cpptools|ms-|0.26.3-insiders2
java|red|0.55.1
code-spell-checker|str|1.7.20
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
vscode-icons|vsc|9.7.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by connor4312** [comment]
Could you provide reproduction steps for us? Thanks!

/needsMoreInfo
