### ISSUE TITLE
Removal of Santa Hat from vscode insiders and pushing of antitheism is very offensive to me

### ISSUE THREAD

**Issue by cope** [microsoft/vscode#88130]
The removal of Santa Hat on vscode insiders and pushing of atheism is very offensive to me, additionally xmas has brought millions of normal people happiness into their lives over the centuries, yet even if that was not the case, pushing antitheistic agenda as part of a product update is completely unacceptable. Please bring it back immediately and make it your top priority. To me this is almost equally offensive as it is to compare a Santa Hat with a swastika.

Version: 1.42.0-insider (user setup)
Commit: 26f5dfc
Date: 2019-12-18T10:34:34.277Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

Install latest build of insiders.
Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered.
https://en.wikipedia.org/wiki/Santa_Claus

**Comment by egamma** [comment]
Pls see https://github.com/microsoft/vscode/issues/87455. The holiday season is over and we have started the integration builds again.

**Comment by cope** [comment]
So, it's a first come first serve on offense responses at microsoft?

Good to know.
