### ISSUE TITLE
Shortcut keys Go to next problem(Alt+F8) and Go to previous problem(Shift+Alt+F8) are not working when focus is on the close button

### ISSUE THREAD

**Issue by InduPriya1805** [microsoft/vscode#88133]
* have a file with at least two errors
* press F8
* move focus via Ctrl+M and tabbing to the close button
* try to use Alt+F8 and Shift+Alt+F8
* the shortcuts do not work because `editorTextFocus` does not hold. IMHO they should use `editorFocus` like the rest of the commands.

---

<details><summary>OLD DESCRIPTION from @InduPriya1805:</summary>

**Environment Details:​**
www.typescriptlang.org/​​
​​
**Browser Details: ​​​**
Microsoft Edge 44.18362.1.0, Google Chrome 75.0.3770.142​
​OS: Windows (Version 1903, Build: 18362.113)​​
​
**Repro Steps: ​​​**
1) Hit the URL "www.typescriptlang.org"​​
2) Navigate till "Playground" link and press enter​​
3) Tab till editor field and type any wrong code. ​
4) Press F8 or Shift+F8 to open the errors​
5) Press Shift+Tab to go to Go to next problem(Alt+F8) and  Go to previous problem(Shift+Alt+F8) controls and verify shortcut key given in the tooltip is working or not​

**Actual Result: ​​​**
Shortcut keys given in the Tooltips for Go to next problem(Alt+F8) and  Go to previous problem(Shift+Alt+F8) is not working​
​​
**Expected Result: ​​​**
Shortcut keys given in the Tooltips for Go to next problem(Alt+F8) and  Go to previous problem(Shift+Alt+F8) should work​
​
**User Impact: ​​​**
Generally users will try to navigate through the shortcut keys given in the tooltip. If short cut keys does not work then disabled users will find difficult to work with the editor field​

**Video Reference:**
[Bug_1748_shortcut keys not working.pptx](https://github.com/microsoft/monaco-editor/files/4019129/Bug_1748_shortcut.keys.not.working.pptx)

</details>

**Comment by connor4312** [comment]
I found a kind of weird issue verifying this. After I focus in the problem peek, F8 goes to the next problem, no issues. But shift+F8 only works once, it's like the focus is lost when going to the previous problem if the user has focus in the peek.

[Video](https://memes.peet.io/img/b484a2ea-7c20-4e29-8128-4de5883fcaa6.mp4)
