### ISSUE TITLE
Extensions cannot view updates to PATH until full relaunch

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#88148]
See OmniSharp/omnisharp-vscode/issues/3461

Basically, the C# extension depends on some binaries it expects to find in the user's PATH. It handles the installation of the binaries, but can't see the updated PATH, so requires a full relaunch of Code to get started. It would be nice if we could somehow help out here.

**Comment by deepak1556** [comment]
Unassigning myself as this isn't related to the runtime

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/15452

**Comment by joaomoreno** [comment]
Closing as designed, that's just how it is unfortunately.
