### ISSUE TITLE
CTRL+A and Enter key don't work in search fields anymore

### ISSUE THREAD

**Issue by OrganicCat** [microsoft/vscode#88141]
Issue Type: <b>Bug</b>

- Open a search field (CTRL+F or CTRL+SHIFT+F both areas)
- Use CTRL + A (select all does nothing)
- Use enter key to cycle through next value (does nothing)

The arrow keys, if clicked, still work

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.12
gitlens|eam|10.2.0
tslint|eg2|1.0.44
prettier-vscode|esb|3.18.0
svelte-vscode|Jam|0.9.3
webpack|jer|2.2.0
vsliveshare|ms-|1.0.1404
debugger-for-chrome|msj|4.12.3
nativescript|Tel|0.11.0
gitblame|wad|3.0.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Did you add a keybinding for ctrl+a or enter? This works for me. Or something else at the OS level that might be intercepting keys?

When did it stop working?

**Comment by OrganicCat** [comment]
This has started working again for me:

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.2.0

Not sure what changed, but this wasn't working for about 4 to 5 days
