### ISSUE TITLE
Support hyperlink in the integrated terminal emulator

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode#88144]
Please implement hyperlink rendering in the integrated terminal emulator, by recognizing the escape sequence specified in [this spec](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda):
- the hyperlink is underlined
- the hyperlink is clickable

**Comment by IllusionMH** [comment]
Most likely depends on https://github.com/xtermjs/xterm.js/issues/1134
