### ISSUE TITLE
Go to References opens in Peek rather than view

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#88147]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.42.0-insider (9349e9a2fdbd1d92824ce99af4a50b6785351b11, 2020-01-06T10:40:10.218Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
@eamodio would a setting to configure whether "go to references" to open a peek rather than view solve the issue, or did you have some other behavior in mind?

/needsMoreInfo

**Comment by eamodio** [comment]
@connor4312 I think this is just a bug -- as _Peek References_ opens in the Peek, and _Go to References_ also opens in the Peek.

**Comment by eamodio** [comment]
_Go to Type Definition_ also seems to have this behavior as well.

**Comment by connor4312** [comment]
"Go to" is ambiguous, best I can recall it's always opened in peek for me if there's more than one candidate location.

**Comment by eamodio** [comment]
Yeah... and it made sense before we had the _Peek *_ versions, but now it feels strange to me

**Comment by jrieken** [comment]
That's the design - when invoking "Go to..." on something that has multiple targets, then we cannot drop one. There are settings like `editor.gotoLocation.multipleDefinitions` to redefine this (peek, gotoAndPeek, goto) but the default peek - how it has been since a long while
