### ISSUE TITLE
View page in browser option for static files

### ISSUE THREAD

**Issue by jnegron357** [microsoft/vscode#88140]
I use VSCode for developing email templates for use in Pardot, an email marketing platform. During development I usually right-click on the tab and "Copy path" and then paste and navigate to view the local file in Chrome. I would like to see a "View in browser" context menu option that would just open the file in my default browser. Better yet, have a sub-menu open to choose which of my installed browsers I want to view it in. That would be great!

**Comment by connor4312** [comment]
Thanks for the suggestion! This is something that would be a good candidate for an extension.
