### ISSUE TITLE
Explorer: folders no longer collapse

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88146]
Steps to Reproduce:

1. have 2 root folders
2. from the first expand a couple of folders
3. collapse from the explorer
4. expand the first folder again

=> 🐛 the folders are not collapsed recursively

This looks like a regression to me.

**Comment by bpasero** [comment]
![video](https://user-images.githubusercontent.com/900690/71830682-8955e180-30a7-11ea-9570-018cc367e844.gif)

**Comment by isidorn** [comment]
@bpasero nice catch, thanks for filling this!
