### ISSUE TITLE
Unsaved editors lost/blank in Insiders build

### ISSUE THREAD

**Issue by asampal** [microsoft/vscode#88145]
Issue Type: <b>Bug</b>

My workspace had several unsaved editors which became blank when I updated my Insiders instance to the previous to this build.

VS Code version: Code - Insiders 1.42.0-insider (9349e9a2fdbd1d92824ce99af4a50b6785351b11, 2020-01-06T10:40:10.218Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (9.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-vlang|0x9|0.0.9
html-snippets|abu|0.2.1
project-manager|ale|10.9.1
svelte-intellisense|ard|0.7.1
azds|azu|2.0.220191204
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.11
FreeMarker|dco|0.0.9
githistory|don|0.4.13
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
vscode-firefox-debug|fir|2.6.1
vscode-svelte-snippets|fiv|0.3.0
code-runner|for|0.9.15
gc-excelviewer|Gra|2.1.32
vscode-nginx-conf-hint|han|0.1.0
rest-client|hum|0.23.0
Ionide-fsharp|Ion|4.4.2
svelte-vscode|Jam|0.9.3
vscode-line-endings|jha|0.2.0
language-julia|jul|0.13.1
vscode-mocha-sidebar|mat|0.22.2
rainbow-csv|mec|1.4.0
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.0.9
remote-containers|ms-|0.96.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.7
cpptools|ms-|0.26.3-insiders2
csharp|ms-|1.21.9
Go|ms-|0.12.0
powershell-preview|ms-|2019.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.3
vscode-react-native|msj|0.13.2
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
red|red|0.3.6
java|red|0.55.1
vscode-yaml|red|0.6.1
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
vscode-icons|vsc|9.7.0
quokka-vscode|Wal|1.0.268
ReactSnippets|xab|2.4.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by bpasero** [comment]
@asampal sorry to hear that, however I cannot reproduce when updating from the last insiders of 20th December to todays on both macOS and Windows with having dirty files open (both untitled and normal files). Any clues what could be different in your setup?

**Comment by asampal** [comment]
Not sure I can say what's different for me. Are there any logs which might help identify the issue?

**Comment by bpasero** [comment]
We have a command that will open the folder with all logs from previous sessions:

![image](https://user-images.githubusercontent.com/900690/71911313-c7b8d280-3173-11ea-88aa-394b46a6efb7.png)

That one might contain a bit more info of what went wrong. 

Would you be able to conduct a test and see if you can possibly reproduce this? I am thinking of this setup where you first run Code stable and then Insiders over the same data directory:
* run `code --user-data-dir <some dir>` and make some files dirty
* run `code-insiders --user-data-dir <some dir>` and verify the files are still there in your setup

**Comment by asampal** [comment]
Looks like the timestamps on the logs are all recent, i.e. newer than when the problem happened, so I don't think these would help. Not sure why older output isn't there since I haven't messed around with the logs.

I do have another detail that might help. I had 7 unsaved editors and all but the last one (rightmost) were lost. Why the last one was not, I can't say. 

WRT trying to reproduce as you indicated, I want to mention that I hadn't switched between stable and Insiders - I pretty much use Insiders exclusively for the last few months (with the odd starting up stable to update it). So, I'm not sure that the exercise you mentioned would be representative of something that could have triggered the content loss.

**Comment by bpasero** [comment]
@asampal yeah no worries, we can do the same with insiders:
* Build from your report: [Download](https://az764295.vo.msecnd.net/insider/9349e9a2fdbd1d92824ce99af4a50b6785351b11/VSCode-win32-x64-1.42.0-insider.zip)
* Build from 20th of December:  [Download](https://az764295.vo.msecnd.net/insider/7c0095ee2d064033fc13184127a9adc603454729/VSCode-win32-x64-1.42.0-insider.zip)

I just tried to reproduce by starting the old build (with --user-data-dir), opening some files and making them dirty and starting the new build afterwards (on the same user data dir). I do not see any data loss. Can you try?

**Comment by asampal** [comment]
It just occurred to me that I missed some possibly important details in reporting the issue. I'm pretty obabout updating my Insiders build daily. I left on vacation Dec. 19th and was back at work on Dec. 27th. So, the test for reproducing the loss, should be between the build that was current on the 18th and the first build available on or after the 27th.

**Comment by bpasero** [comment]
@asampal hm ok. It could very likely be https://github.com/microsoft/vscode/issues/87156 which has the exact same symptoms. It got fixed around 17th/18th. There are no other reports from other users so maybe you got unlucky by getting that exact version with that problem.

**Comment by asampal** [comment]
I'll assume that was the issue, @bpasero. Go ahead and close this one.
