### ISSUE TITLE
ctrl+tab + ctrl+shift+tab doesn't cycle tabs in different directions

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vscode#8815]
I attempted to add this:
// Place your key bindings in this file to overwrite the defaults
[
{ "key": "ctrl+shift+tab",        "command": "workbench.action.openPreviousEditor" },
{ "key": "ctrl+tab",              "command": "workbench.action.openNextEditor" }
]

But it seems openNextEditor is not a command

**Comment by bpasero** [comment]
@rchiodo is this on stable or insiders build? if stable, mind trying insiders?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
