### ISSUE TITLE
Add folder to workspace not working

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#88152]
Issue Type: <b>Bug</b>

Add folder to workspace from File menu not working currently on macOS with latest Insiders. The command handler was hit but dialog service doesn't work, without any errors

```
const folders = await dialogsService.showOpenDialog({
			openLabel: mnemonicButtonLabel(nls.localize({ key: 'add', comment: ['&& denotes a mnemonic'] }, "&&Add")),
			title: nls.localize('addFolderToWorkspaceTitle', "Add Folder to Workspace"),
			canSelectFolders: true,
			canSelectMany: true,
			defaultUri: dialogsService.defaultFolderPath()
		});
```

VS Code version: Code - Insiders 1.42.0-insider (9349e9a2fdbd1d92824ce99af4a50b6785351b11, 2020-01-06T10:36:54.329Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by bpasero** [comment]
I cannot reproduce, works fine for me. Anything in the logs?

**Comment by bpasero** [comment]
![video](https://user-images.githubusercontent.com/900690/71873995-f9ed1480-3120-11ea-9dac-4a66b5c2792a.gif)

**Comment by rebornix** [comment]
I can't reproduce this either, it' really weird because when that happens, no error at all, breakpoint hit but nothing happens. Also even if I download the latest bits from the website again, nothing changes.

*Update*

It must be something wrong with my machine (MacBook Pro 16" with Catalina) as today even if I download previous Insiders, I can't reproduce it anymore. Previously when I was using the Insiders before holiday on this machine, Insiders can never be focused but the Stable version is fine, now I can't reproduce that either. cc @deepak1556 .

I'll close this issue for now.
