### ISSUE TITLE
Recent change to searching makes it way too aggressive

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#88159]
Issue Type: <b>Bug</b>

A recent update changed the behavior of `workbench.action.findInFiles` in an extremely undesirable way for me. Like, constant source of frustration throughout my day kind of way.

Previously, triggering search would open the panel and seed the search box with any text I had selected, but it _wouldn't actually run the search_. Since I think 1.40 or 1.41 invoking `workbench.action.findInFiles` both seeds the search text and _begins an actual search_.  This happens despite setting `"search.searchOnType": false`. The only way I've found to stop this auto-search behavior is to set `"editor.find.seedSearchStringFromSelection": false`, but that's an undesirable workaround.

The reason this is such a big issue for me is that it ends up constantly re-running the search. In the large codebase I work in most often this takes about 2 seconds and ends up happening after every search result I look at.

My workflow looks like this:
* Invoke `workbench.action.findInFiles` to begin a search
* Type some text and hit enter
* Select a result and press enter
* Look at the opened editor
* Invoke `workbench.action.findInFiles` to _return focus to search_
* Select a different result and press enter
* repeat

The problem is with _return focus to search_. Since selecting a search result opens an editor with the matching text selected then if I don't clear the selection before invoking `workbench.action.findInFiles` is starts a brand new search. This means I have to wait for the search to complete, and worse, it blows up the tree view where I had collapsed some files that I'd finished inspecting.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
@JacksonKearl, disabling searchOnType should also prevent the search from running in this case

**Comment by roblourens** [comment]
Remember to assign to the milestone for verification :)

**Comment by fakhamatia** [comment]
How can I fix this?
I want: select string and hit ctrl+F and find it on the current page.
I don't want: select string and click the search icon and VSCode automatic search string.

I use `"editor.find.seedSearchStringFromSelection": false` but i must copy string and hit ctrl+F and 
paste string to search in current page.

**Comment by JacksonKearl** [comment]
@fakhamatia see #90962.
