### ISSUE TITLE
[folding] [markdown] No setting for ignoring all empty lines

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#88151]
please { add a setting for / make so } markdown folding would ignore trailing {empty lines}/whitespace .

![](https://user-images.githubusercontent.com/13949704/57344136-a0c28080-714e-11e9-8452-8e0c8d3bfc7b.gif)

**Comment by aeschli** [comment]
Each language defines whether whether folding blocks end with a new line ('off-side folding') or not.
For plain text #73444 requested that it does end with a empty line (`off-side == true`).

That's what got implemented for October 2019 and that's why #73444 got closed.

You screenshot is from an old version of VSCode. If you try with the latest build, you will see that plain text no longer includes empty lines.

**Comment by irvnriir** [comment]
@aeschli , thanks for response, but does it mean only the '1 empty line' folding ?
(so if you have 2 trailing lines, they still will be folded, including plain text?)

**Comment by aeschli** [comment]
No, any number of empty lines.
Actually how it works is::
For offside folding, a folding range ends with the last line that has content and has a larger indent than the next non-empty line.

**Comment by irvnriir** [comment]
@aeschli ,
so where can it be defined then?

and i also tried to modify language configs, but some-why they do nothing
![](https://lh3.googleusercontent.com/WhNJHSGr9o-0NdDP8fh3jRSizd8dznmeHpQS31nde9CutWuoMjG2MPkPj4jXCJHER0HzJ7Ls3S1rRSOVLUmoEbNA_PauMRUhtd_4K3h9klwnO1I6Hxad33XEAsMwtHquWHGtCcb6FbtEogqxx9dGyc4kfzGeafBpEjqyAmiVH1RVqvn68roNtSNSU-a8qHQ330BWg0EiCmvPorIK5IKBpS6mylAZqCruRCcQoOAj9x1wZpVaezKAsFwXlRAEzSrQ3vjcsV-06OpYKUxF6yX0C4wVP6i44RkHioPPNq96Uzl3AzKL46f_ijYbsHfMEQN5EYjWLokHZiMNZHoxMZjspliTf9ntUKVgEZ7zAV03lWCMBJBe19DlMszZo9V6pY-_dDGb3lQS5N3hcorTgN5fKdsbo2DJsmeNtqrubQt87qcJGAzuxtn9oaNCJhIbsbr6gmefd4H-wynATb-BP_HY5vtRSVVUaSTmdO8Fh3oWRaIl8r0eL66qroZ-X-54TwXONUR6AavlTKvfXLA-CslVO3lGqtfPPPUeM7V8S-9n4xTLRjQUfM_kStM9HT_1rtWCuaU20-8EAOl03SFz_vt0yIdUwWkPu6HRwy57spWtnAp5HTQlbk3oUWG1-FAF185L1B-1ZaTripVLtqCGx53Krn2fQZDjGwlRBYn28ShwuKLTpL_MK8o7mA=w346-h220-no)

**Comment by aeschli** [comment]
Here's how it's done for Python: https://github.com/microsoft/vscode/blob/f548111c5c3435622c5f4fe42a121ed8ba28d543/extensions/python/language-configuration.json#L44

**Comment by aeschli** [comment]
Plain text is special but it's the same setting. And when I try it it works as expected:
![off-side-folding](https://user-images.githubusercontent.com/6461412/71912026-15820a80-3175-11ea-8503-37e4b838ffcd.gif)

Please create a sample that shows what's not working.

**Comment by irvnriir** [comment]
Python and Batch configs and Plain Text work fine . but with markdown, Offside Folding and surroundingPairs config doesn't work .

![](https://lh3.googleusercontent.com/b-zAWqRQ8DE400kRiT_smuZH96CKa3_Q4-lqFI8W-uNbNTEQ27IJgvR_IjEBlzBHn7hPBV76-U6ebu8lHmiAgsfR8lp7npMTJqu19EXbpG3yEPOpAApqd9aVWt4Z8JT3L1NAMhJWVOXmOBc70Xr2HUYW3JcWMmhXKlgbiRjJsCd8iHwAU1TAJeDzgzK7YPyWQbWIVUgwjMvhwECG2qCqGViR5jQnFRBqUey6Z4y266DR-UioPKjqUGAt54OH7Av4NgAPwrHOA4EXgrfdQpZtlIpL2KHfs-Y11c6t3TgZCHEDMaLJDfO10FC-AjPH74lXISHr37yizKqkB6bTZXQqK9k2NlW1ZwnuTqdA1p_sKUOMBfrGrVJuOcQ1Vper_GT4LEfXuEBEIi5rXiVhdwdZittEc8HlPG5AEoKsL3ZYNaRB32hL14jUxuwfLJexGRUXIIfXb0CrB72UGQMDQiUwrQcbCK6BhZRoD0yh1d7HWBsUoTdMdZOgSxbi1Hgkyd-EPBHkshk_XZd55ge2w8ZtrsXHb6MvBcaoiPusbMLxelUtgxFYabcbBxPlw6P8UwvN-JOK6nUrUPtiY-8mhWMyKZ3Hd-6_0tiERhKi2bHASi6nMrqfSC-kMcC3LJfY1ClWTnqIjknftd28FfJ1YN3ANSjuzC4-Q0KZ0xujhyVypfb-aWui4ETH8w=w364-h264-no)

![gif](https://lh3.googleusercontent.com/c6MzocSUcNf3PDXABfhS5W9vsLLg4q1J5DzFq2hf8uNEO7lLKk2R17M6Vy8JA8o_PG2xwUTYMFMTS4XnhUrEB-WBMdgedrcJP4TRDJVm9sAT5Om2_kWU1omJSYQ8JNEuvlZpQNZXoK2w2tW1Sijt_ElCg-WWT90lQ14BwjYTKMiZs8DFTnz2fTNtyLljXD5aLVbyGm51V4KI9cSN_PQt0qhWy8qlLNmde9WjBpu7nk4pn7zcvT8NeFdmXBRnDy9GlKvnUOSvUuRD6cRyrx2sjgVrujTHZtflwX9esdbhF8LBsMcwo9AG2_0e0fH8VOdy9OX3pS0WBZQh8LOLTY5HIxQkTl5A2v9XcwOulEvs38hfgg3zSoKg-JflpXeObZlm_DJ6N49vefC2JOXnxb_zXNtU6yCUOEap564cjsd7tpJXwxkpTBdSpcijj41dH_o3fDMjiumSirsc5q-4fUySeMWZ744x_zdi5DeJrdKbhinnpkycWZ6t2pMhq2_Xl74X30-AqWuP6oQoq1_4KYAYB7wWYCHxp4OpvVH4rRM2Ny3AIFLMPeUDAImU3vupR__dqgG6RsNnJd6UQ4y7RlCCEXbfHCYK-0hKotbX_eQECPwzFQX2nRBC9KaalTgUIVVNCpFyvsReYwpH4a4iBKLztU_Udd-uC80YBRmkhsf_ZPuuNMcToOOj3A=w1064-h588-no)

**Comment by aeschli** [comment]
@irvnriir Can you paste a small markdown sample code that show the problem? The images that you included don't seem to work.

**Comment by irvnriir** [comment]
@aeschli , sorry, they got unshared for no reason, now should work

**Comment by aeschli** [comment]
This is the sample from your screenshot:
```md
1.
   1.

   2.



2.
```

What you see is not the indentation based folding, but the folding contributed from the markdown language server. That means it's not related to 'off-side'

Moving the issue to @mjbvz

**Comment by irvnriir** [comment]
i just want to set the Offside behavior for any folding, so where can the corresponding Markdown Language Server setting be found?

**Comment by aeschli** [comment]
That's up to Markdown Language Server to decide whether the generation of ranges is configurable.
I would guess the Markdown Language Server uses it's internal Markdown parser and Markdown knowledge to decide how the folding ranges look like. @mjbvz is the owner of that code and can explain more.

If you don't want to use the folding ranges from language aware providers, you can switch back to indentation based folding regions by this setting:
```json
"[markdown]": {
    ""editor.foldingStrategy": "indentation"
}
```

**Comment by mjbvz** [comment]
Markdown ignores the single last blank line when folding list items. There is no setting to make it ignore additional blank lines

**Comment by irvnriir** [comment]
@mjbvz , by "setting" i mean any way to make it work so (code editing)

**Comment by atanasj** [comment]
Would not being able to fold all comments be related to this issue, or am I mistaken that this is even possible in `markdown`, and each comment needs to be folded manually via clicking on the fold symbol?

**Comment by mjbvz** [comment]
@atanasj Sounds unrelated. Do you mean html comments in markdown files?

**Comment by atanasj** [comment]
Yes, `html` multi line comments. They are able to be toggle manually one at a time but not via the command palette.

**Comment by mjbvz** [comment]
@atanasj  That's unrelated to this issue. Please open a new issue so we can track that feature request

**Comment by atanasj** [comment]
@mjbvz done: https://github.com/microsoft/vscode/issues/91271. Thanks.

**Comment by mjbvz** [comment]
Closing this as it has not gotten enough upvotes on our backlog (not sure why the bot did not kick in to do this automatically)
