### ISSUE TITLE
Pasting formatted JSON into a JSON array wraps with extra parenthesis

### ISSUE THREAD

**Issue by ChristopherGLewis** [microsoft/vscode#88150]
Issue Type: <b>Bug</b>

If I have a JSON file with an Array and paste a full item into it, VSCode or an extention adds extra parenthesis.

```` JSON
{
  "Company": [
    {
      "CompanyAbbr": "AAA",
      "CompanyName": "AAA Co"
    },
    {
      "CompanyAbbr": "BBB",
      "CompanyName": "BBB Co"
    }
  ]
}
````

If I highlight from the comma after company AAA's closing bracket until the end of company BBB and click copy, and then paste after company BBB, extra parenthesis are added:

```` JSON
{
  "Company": [
    {
      "CompanyAbbr": "AAA",
      "CompanyName": "AAA Co"
    },
    ({
      "CompanyAbbr": "BBB",
      "CompanyName": "BBB Co"
    },
    {
      "CompanyAbbr": "BBB",
      "CompanyName": "BBB Co"
    })
  ]
}
```` 

Not sure if this is the built in VSCode JSON formatter or "Prettify JSON 0.0.3"

I've tried turning off all "Format on Paste" options that I can find.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
azureautomation|Awe|1.0.2
LinkCheckMD|bla|0.3.1
bracket-pair-colorizer|Coe|1.0.61
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.33.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.5
docs-images|doc|0.0.3
docs-markdown|doc|0.2.29
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.36
docs-yaml|doc|0.2.4
githistory|don|0.4.13
xml|Dot|2.5.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.18.0
beautify|Hoo|1.5.0
chat|kar|0.31.0
terraform|mau|1.4.0
prettify-json|moh|0.0.3
vscode-docker|ms-|0.9.0
mssql|ms-|1.8.0
remote-wsl|ms-|0.41.6
azure-account|ms-|0.8.7
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
vsliveshare|ms-|1.0.1404
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
azurerm-vscode-tools|msa|0.8.3
vscode-yaml|red|0.6.1
code-spell-checker|str|1.7.20
vscode-ansible|vsc|0.5.2
gitblame|wad|3.0.1
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by ChristopherGLewis** [comment]
Actually - its just VSCode - I disabled Prettify JSON and it still happens.

**Comment by connor4312** [comment]
Please try to repro this with all extensions disabled (ctrl+shift+p -> disable all installed extensions)

**Comment by ChristopherGLewis** [comment]
When I disable all extensions using  (ctrl+shift+p -> disable all installed extensions) I see the same results.  The error is not resolved.

**Comment by ChristopherGLewis** [comment]
OK - the extension with the error is 'Prettier - Code formatter' v 3.18.0.

Off to report the bug there...
