### ISSUE TITLE
"cmd + `" to switch windows does not work when using non-US layout

### ISSUE THREAD

**Issue by Porkepix** [microsoft/vscode#88153]
- VSCode Version: 1.41.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Switch to a non-US layout (e.g. default French one, usually called azerty)
2. Try to use the default system shortcut to switch between windows of the same application, ie. ``cmd + ` ``.
3. You'll see that the application switch isn't performed and that it's going to write a `` ` `` instead. There's no issue when using US layout on the same setup.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@Porkepix 
What kind of keyboard do you have? ANSI or ISO?

![image](https://user-images.githubusercontent.com/5047891/72785302-36456800-3c2b-11ea-86b8-2973df16063f.png)

**Comment by Porkepix** [comment]
This is on an ISO keyboard. I might get a hand on a Typematrix keyboard with a switch between ISO & ANSI mode, and maybe try it on, but I''m not sure yet.
In any cases, the bug report was done from an ISO keyboard.

**Comment by alexdima** [comment]
VS Code is built with Electron. I could reproduce this in vanilla Electron and have created an issue at https://github.com/electron/electron/issues/21847
