### ISSUE TITLE
Search tab no longer shows at the bottom of the screen when updated to v1.42.0

### ISSUE THREAD

**Issue by AravindGopala** [microsoft/vscode#88165]
- VSCode Version:1.42.0 insider
- OS Version:ubuntu 18.10

Steps to Reproduce:

1. Search tab no longer shows up for ctrl+shift+F when at the bottom of the editor, only shows when the position is toggled to the left of the file editor

Does this issue occur when all extensions are disabled?: Yes

**Comment by AravindGopala** [comment]
1. Type in "toggle search view position" in the command palette (ctrl+shift+p), 
then the search tab shows up only in the position left to the editor but the tab disappears when toggled to the bottom of the editor.

**Comment by vgrafe** [comment]
I confirm, bug observed on my setup on macos 10.15.2 (19C57).

When pressing cmd+shift+f, the terminal appears if the search is set to appear on bottom. If I toggle search all in the left pane, it works as expected. 
```
Version: 1.42.0-insider
Commit: 9349e9a2fdbd1d92824ce99af4a50b6785351b11
Date: 2020-01-06T10:36:54.329Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```
