### ISSUE TITLE
Can't find module with extension .es6

### ISSUE THREAD

**Issue by aikeru** [Microsoft/vscode#8816]
- VSCode Version: 1.2.1
- OS Version: Windows 8.1

Some projects I work on use ```.es6``` extension for JavaScript files that import/export using ES6 module syntax.

While webstorm and webpack seem to have no issues with this setup, VSCode gives a red squiggly saying ```[js] Cannot find module './filename.es6'.```

Is there some way to get VS Code to find modules imported that do not have a ```.js``` extension? We would like to use ```.jsx``` in a similar fashion.

I have this for a .jsconfig:

```
    {
        "compilerOptions": {
            "target": "ES6",
            "module": "commonjs"
        },
        "files": [
            "**/*.jsx",
            "**/*.es6",
            "**/*.js"
        ]
    }
```

...and tried adding ```.es6``` under user settings for VSCode, but suspect I did it wrong or that doesn't solve the issue.

Also opened StackOverflow here:
https://stackoverflow.com/questions/38046039/vs-code-es6-extensions-cant-find-module

**Comment by dbaeumer** [comment]
@aikeru jsx is support but es6 to my knowledge not. Moving to TS team for further clarification.

**Comment by dbaeumer** [comment]
TS team: for 2.0 I saw that you support arbitrary file extensions by use setting the kind on open. Would there be more we need to do to make this work.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9551

**Comment by aikeru** [comment]
@dbaeumer   I appreciate the quick response and clarification. If I just rename the files to ".js" extension, everything works in VS Code. It's only the difference of extension that seems to matter. I'd like to switch, but you know how it is... :)

Does this further confirm that it is, indeed, a TypeScript issue?

**Comment by dbaeumer** [comment]
It is a TS issue. Especially when it comes to resolving file. Consider the case weher eyou have a JS file A which import a JS file B. The import statement usually doesn't include the file extension. So the TS/JS server (yes the JS support is power by the TS language server :-)) needs to know the list of valid file extensions that could contain JS code.

**Comment by aikeru** [comment]
@dbaeumer well, the issue has been closed on the TS side as "works as intended".

This seems to be saying that for all the Microsoft tooling that depends on TS for module intellisense, you must either use one of the 4 supported extensions or it wont work. If true, it also means VS Code isn't viable for codebase(s) that I work on day-to-day (even if the syntax highlighter has no problem with it). :(

I really hope this isn't the case, since plenty of the community supports configurable extensions (especially ".es6", even if it's not the best extension to use).

Other competing tools (like Webstorm) work just fine with this setup.

I really hope this is reconsidered!

**Comment by aikeru** [comment]
Sadly, this still seems to be an issue in VS Code (January 2017 v1.9) and the issue on the TypeScript repo seems to have been closed without taking this use case into account https://github.com/Microsoft/TypeScript/issues/10939
This is one of the things driving teams I work with away from VS Code. Regardless of whether it's a good idea, the reality is asking teams to move away from .ES6 extension (and virtually every editor/IDE has the ability to configure a custom extension for a given file type) is a non-starter just for the sake of supporting a specific editor/tool.

**Comment by dbaeumer** [comment]
@mjbvz @waderyan can you follow up.

**Comment by leeight** [comment]
+1
