### ISSUE TITLE
Selecting first element in a debug group selects the -------

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#88162]
In VSCode repo, select the "Launch VS Code (Main Process)" debug configuration. Bug: the "------" divider gets selected instead. Select "Launch VS Code (Main Process)" again, it works this time. 
![Jan-06-2020 11-10-14](https://user-images.githubusercontent.com/8586769/71841844-28adb100-3075-11ea-9593-1c9b1d136bb7.gif)

**Comment by JacksonKearl** [comment]
Also, with the proper element selected, navigating to a different viewlet then back to debug will re-select the "-------".

**Comment by isidorn** [comment]
@JacksonKearl thanks for filling! Pushed a fix, just let me know if you no longer see it with new Insiders from Friday.
