### ISSUE TITLE
Theme setting ignored / reset when launching extension development host...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode#88169]
hi there :wave:

i've noticed that as of `v1.41.x` my theme setting is no longer respected in the extension development host. here's a screencap of what i'm experiencing:

![theme reset demo](https://user-images.githubusercontent.com/367674/71852490-ac739780-308d-11ea-8b08-f5dcfea83ef6.gif)

in some cases, the selected theme is reset immediately after selecting otherwise it'll revert to some random theme upon re-launching.

**Steps to Reproduce:**

1. launch the extension development host (press F5)
2. wait for extension development host to launch, note the theme setting is reset
3. change the theme setting: `cmd/ctrl` + `shift` + `p` then select the `Preferences: Color Theme` command
4. pick "Dark (visual studio)" or "Dark+ (default dark)"
5. stop / close the extension development host
6. re-launch the extension development host (press F5)

**Expected:**
theme setting is retained

**Actual:**
theme setting is lost / reset to some random theme

**Does this issue occur when all extensions are disabled?:**
Yes

**Environment:**
- VSCode Version: `1.41.1`
- OS Version: macOS `v10.13.6` and `v10.15.2`

_edit: also happens on my laptop running macOS `v10.15.2`_

**Comment by sandy081** [comment]
Can you please open settings editor and please check what is the value for theme there and let us know if it is retained or not.

**Comment by busticated** [comment]
@sandy081 when i select "Dark+ (default dark)", my user settings look like:

```json
{
    "editor.minimap.enabled": false,
    "workbench.startupEditor": "newUntitledFile",
    "terminal.integrated.scrollback": 100000,
    "window.zoomLevel": 0,
    "extensions.autoUpdate": true
}
```

...when i select "Dark (visual studio)", they're:

```json
{
    "editor.minimap.enabled": false,
    "workbench.startupEditor": "newUntitledFile",
    "terminal.integrated.scrollback": 100000,
    "window.zoomLevel": 0,
    "extensions.autoUpdate": true,
    "workbench.colorTheme": "Visual Studio Dark"
}
```

neither setting is respected upon launching the extension development host.

**Comment by sandy081** [comment]
Moving to @aeschli as per above comment.

**Comment by aeschli** [comment]
Does the extension that you are developing contain a theme contribution? 
We have this feature that the extension development host automatically switches to the theme.

**Comment by busticated** [comment]
@aeschli 

> Does the extension that you are developing contain a theme contribution?

i have _another_ extension which contributes multiple themes but it's not the one i'm working on in this case. though i guess since my `extensionDevelopmentPath` points to a shared parent directory, it's being picked up?

> We have this feature that the extension development host automatically switches to the theme

guessing this was added somewhat recently (`v1.4x.x`)? is there a way to disable it? even if i were working on my themes, i wouldn't want my current theme selection to reset upon launch as i could be working on one of many included in my theme extension ([info](https://marketplace.visualstudio.com/items?itemName=particle.particle-vscode-theme))

**Comment by aeschli** [comment]
>  my extensionDevelopmentPath points to a shared parent directory
Yes, that explains it. That's not the standard way. Maybe better pass the folder of the extension (you can have multiple `extensionDevelopmentPath` arguments)

There feature has been there for quite a while (over a year). I'd rather not add any setting...

**Comment by busticated** [comment]
> There feature has been there for quite a while (over a year).

i've been working on my extension using the same local development setup for nearly the same amount of time. any idea why i'm seeing this behavior now?

**Comment by busticated** [comment]
> Maybe better pass the folder of the extension (you can have multiple extensionDevelopmentPath arguments)

my extension uses `extensionDependencies` so pointing `extensionDevelopmentPath` at one of my extension's root directory causes its dependencies to be installed in the global / default location (`~/.vscode/extensions`) which i do not want.

> Do you run it from the command line?

no, i'm using a `.vscode/launch.json` file within my extension's root directory.

more importantly, changing my `launch.json` from:

```json
"args": [
    "--extensionDevelopmentPath=${workspaceRoot}/../"
],
```

...to:

```json
"args": [
    "--extensionDevelopmentPath=${workspaceRoot}"
],
```

doesn't actually fix the issue. upon launching the extension development host using this new `extensionDevelopmentPath`, my theme is still reset and updates to that setting are not retained.

**Comment by aeschli** [comment]
Auto switching the theme now only happens if there's a single extension under development (and provides a theme)

**Comment by aeschli** [comment]
To verify:
- use yo code to create two extensions in the same folder: foo/themeExtension and foo/tsExtension. themeExtension is a color theme extension
- create a ext dev launch configuration with 
"args": [
    "--extensionDevelopmentPath=pathtofoo"
],
-On launch there should not be a change of theme
