### ISSUE TITLE
Explorer search file - enhancements

### ISSUE THREAD

**Issue by bernardoadc** [microsoft/vscode#88164]
I have some requests for the Explorer search file feature:

- input not easily editable. For instance, if you want to change the begging of the text, you would have to delete it all and start over (you can't navigate chars)
- seems to do only a basic text comparison. No gloob patterns, no regex. No exclude patterns (e.g.: show everything but these files; search everywhere except in some folder).
- that last example actualy works via folders that are currently expanded (not so intuitive, though). But there's currently only a command for "File: collapse folders in explorer", both visually and by keyboard. A "File: expand folders in explorer" command is needed, at least via keyboard

**Comment by melMass** [comment]
1. It should be, I can navigate chars
2. It does you have to enable Regex (third icon):
![image](https://user-images.githubusercontent.com/7041726/71888303-206e7800-3140-11ea-98c9-e18591cc6e06.png)
Also If you click on the dots down the search you can filter where it searches
![Screenshot 2020-01-07 at 11 25 06](https://user-images.githubusercontent.com/7041726/71888542-ad193600-3140-11ea-94c0-d6d9fbcb9f68.png)
![Screenshot 2020-01-07 at 11 25 54](https://user-images.githubusercontent.com/7041726/71888555-b5717100-3140-11ea-9be2-fb9ce108256d.png)
3. I use Ctrl+P to navigate to where I need, I know this is not what you are asking but just in case you don't know.

**Comment by usernamehw** [comment]
@melMass I think he is talking about `Type to filter` feature in Explorer Tree.

**Comment by bernardoadc** [comment]
Yes @usernamehw !
Altough I think it could also be only visible while typing. Or, plan simple, a button to unhide that +row.

**Comment by isidorn** [comment]
This is related to the tree.
There are already feature requests that are very similar to this and it might be a dupilcate.
However forwarding to @joaomoreno who owns the tree so he considers it. Thanks

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/70646
