### ISSUE TITLE
Forwarding a port with an invalid remote address - no error or feedback

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88179]
- Use today's ssh nightly extension
- Try to forward a port with a remote address which is probably unreachable
- Nothing seems to happen, it should either try to set up the forward anyway, or show me an error that it couldn't do it

![Jan-06-2020 17-03-51](https://user-images.githubusercontent.com/323878/71860154-9f16d700-30a6-11ea-9b34-16fb64ea4822.gif)

**Comment by alexr00** [comment]
New error: 
![image](https://user-images.githubusercontent.com/38270282/71904448-68a09100-3166-11ea-801a-3d8881a1bbdc.png)

**Comment by connor4312** [comment]
I'm not totally sure how to trigger this. At least on my azure dev VM/test setup, I can set up forwarding for lots of ports that I can't ping. (Also, it seems they treat everything under 127.x.x.x as loopback). Maybe someone else has a better environment they can test on.

![image](https://user-images.githubusercontent.com/2230985/73475604-8c11c280-4345-11ea-98ae-4e94bbff54a3.png)

**Comment by roblourens** [comment]
What I see now is that I can set up a forward for a port that isn't open, then start a server using the forwarded port, and I can access it over the forwarded port. That is actually what I expect, although the commit makes it sound like setting up the forward should have failed. I'll say it's verified unless @alexr00 says it should be different.

**Comment by alexr00** [comment]
@roblourens that is what it should be doing.
