### ISSUE TITLE
Outline and breadcrumbs are not initially available for files with code lenses

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#88171]
### THIS IS NOT A PYTHON EXTENSION ISSUE

_**The issue is with codelenses**_

@pewscorner commented on [Sun Nov 24 2019](https://github.com/microsoft/vscode-python/issues/8762)

## Environment data

- VS Code version: 1.40.1
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.0 32-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Jedi

## Expected behaviour

Outline symbols and breadcrumbs should be available for all python files regardless of whether file has code lenses or not.

## Steps to reproduce:

_**This is one way to get codelenses on a file, you can try other ways**_

**Setup:**
1. Install python extension.
2. Run `Python: Configure tests` command, configure using unittest framework, then follow the steps below.

1. Set "python.testing.unittestEnabled" to true, and change the last item of the default "python.testing.unittestArgs" setting from "\*test\*.py" to "*test.py" (this change is not always necessary to provoke the problem).
2. Create a file named atest.py with the following content:
```
#!/usr/bin/env python3
import unittest

class Test1(unittest.TestCase):
    def test1(self):
        self.assertEqual(5, 5)

if __name__ == '__main__':
    unittest.main()
```
3. Restart VS Code. At this point there are no breadcrumbs for the file, and the outline view says "No symbols found in document 'atest.py'".
4. Type a space into the editor. Now the breadcrumbs and outline symbols appear correctly.

Because the test file had codelenses ( `Run test | Debug test`) like 
![image](https://user-images.githubusercontent.com/13199757/69589712-da9b8d00-0fa1-11ea-88e9-17c4fcf31c76.png)

the outline symbols don't load. Disabling code lenses using the setting `"editor.codeLens": false` solves the issue.

**Comment by jrieken** [comment]
> THIS IS NOT A PYTHON EXTENSION ISSUE

What makes you think so? I happily selfhost with codelens and breadcrumbs in typescript. Are you sure that the code lens provider doesn't interact/block the resolution of document symbols?

What does the (verbose) extension host log read?

**Comment by pewscorner** [comment]
@karrtikr, can you help out here? I don't have the knowledge to argue that this is a VS Code issue and not a Python extension issue. Since we agree that the issue exists, we should be able to keep either this one or the [vscode-python issue #8762](https://github.com/microsoft/vscode-python/issues/8762) open.

**Comment by karrtikr** [comment]
Sorry the notification got missed. I am looking at the code lens provider, it's pretty complicated so it may interact with outline symbol provider. Reopening original issue to investigate.
