### ISSUE TITLE
Launch config picker shows ----------

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88176]
- Remove "hidden" from the "Attach to VS Code" launch config
- Use it to attach to a vscode instance
- Stop debugging
- Now the picker has that separator selected:

![image](https://user-images.githubusercontent.com/323878/71858370-cb7b2500-309f-11ea-8bff-8276acfb87d6.png)
![image](https://user-images.githubusercontent.com/323878/71858374-cfa74280-309f-11ea-83e4-7f89481aa1b6.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/88162#event-2926932988
Fixed via 1ced4ebbc7
