### ISSUE TITLE
Takes more that 2 minutes to open a file

### ISSUE THREAD

**Issue by 9072997** [microsoft/vscode#88170]
Issue Type: <b>Performance Issue</b>

This workspace is a git repo on an SMB share (unconventional I know). It seems like the behavior is the same for anything that needs to read from or write to the workspace: saving a file, opening a file, viewing a diff, or expanding a directory. Any one of those actions can trigger the lock up. It happens frequently (3-10 times a day). I usually work in this workspace, but it happens in others too (all SMB shares, all git repos, different servers). This workspace is the only one where I have gone to the trouble of testing it with all extensions disabled. I usually just kill VScode via Task Manager and open it again, but when I have something I really need to save I will wait it out. It sometimes will take more than 10 minutes to save a file. When this happens I cannot do anything else from my earlier list of actions. I can close files as long as I don't save changes. I can interact with the UI.  VSCode is only using ~2% of my CPU and I'm good on RAM. I do not believe I am bandwidth constrained either. I can open the same file in another editor and it will open instantly. 

If there is any additional information I can provide please let me know. Unfortunately I cannot share the workspace. A big chunk of the contents is data rather than code (SSNs, student data, the kind of stuff you get super-fired for publishing on the internet)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (9.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    81	  6684	code main
    6	    72	  4628	   shared-process
    1	   176	  9644	   window (Bentonville.psm1 - scripts - Visual Studio Code)
    0	    15	  7544	     watcherService 
    0	    11	 13616	       console-window-host (Windows internal process)
    0	    58	  8088	     extensionHost
    0	    69	 13156	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 14100	     console-window-host (Windows internal process)
    0	    14	 11544	   electron-crash-reporter
    0	    65	 13532	   window (Issue Reporter)
    0	   179	 13720	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Bentonville.psm1 - scripts - Visual Studio Code)
|    Folder (scripts): 4051 files
|      File types: jpg(1229) txt(859) csv(298) zip(116) yaml(63) log(56)
|                  ps1(52) sql(50) url(38) xml(36)
|      Conf files:;
```

</details>
Extensions: none

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by 9072997** [comment]
Happens on the insider build as well
<details><summary>Code - Insiders.exe --status</summary>
<pre>
Version:          Code - Insiders 1.42.0-insider (629a08ed6231d7af269ae61a5cc610490d1f7f5d, 2020-01-07T05:28:24.258Z)
OS Version:       Windows_NT x64 10.0.18363
CPUs:             Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)
Memory (System):  15.83GB (8.33GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        enabled
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       86   10276  code-insiders main
    0      114    7960     window (Student Account Creator.ps1 - wwwroot - Visual Studio Code - Insiders)
    0       34   11956       extensionHost
    0       14   13840       watcherService
    0        5     124         console-window-host (Windows internal process)
    0      188   11576     window (MissedTasks.ps1 - scripts - Visual Studio Code - Insiders)
    0       52    3504       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0        5    9176       console-window-host (Windows internal process)
    0       13   10272       watcherService
    0        5    3720         console-window-host (Windows internal process)
    0       45   12588       extensionHost
    0       22    7400         "L:\Work\scratch\vscode-insiders\Code - Insiders.exe" l:\Work\scratch\vscode-insiders\resources\app\extensions\json-language-features\server\dist\jsonServerMain --node-ipc --clientProcessId=12588
    0       53   11748     shared-process
    0      138   11756     gpu-process
    0        5   12128     "C:\Program Files\Google\Drive File Stream\35.0.13.0\crashpad_handler.exe" --database=C:\Users\jpenn\AppData\Local\Google\DriveFS\Crashpad --url=https://clients2.google.com/cr/report "--annotation=application=Code - Insiders.exe" --annotation=prod=DriveFS --annotation=ver=35.0.13.0 --initial-client-data=0x143c,0x1440,0x1444,0x1438,0x1454,0x7fff61f51348,0x7fff61f51358,0x7fff61f51368
    0       11   12796     electron-crash-reporter

Workspace Stats:
|  Window (MissedTasks.ps1 - scripts - Visual Studio Code - Insiders)
|  Window (Student Account Creator.ps1 - wwwroot - Visual Studio Code - Insiders)
|    Folder (scripts): 4183 files
|      File types: jpg(1230) txt(776) csv(321) zip(117) yaml(63) log(56)
|                  ps1(54) sql(50) url(38) xml(36)
|      Conf files:
|    Folder (wwwroot): more than 26887 files
|      File types: odt(5780) sqlite3(5624) php(2670) html(1533) txt(835)
|                  js(636) gif(378) asp(294) css(247) png(206)
|      Conf files: csproj(1) makefile(1)
</pre>
</details>

**Comment by bpasero** [comment]
@9072997 would you say that the connection to the SMB share is a fast or slow one? We rely on node.js for all file handling and are on the mercy of the operating system for how fast file operations go through SMB. I am not sure there is much VSCode can do to improve this if the underlying sources are slow.

**Comment by 9072997** [comment]
The limiting factor is the 100 megabit connection on my desktop. The rest of network all the way to the server is gigabit and there is not much else competing with me for bandwidth to that server. I can reliably push or pull about 9.5 mega**bytes** per second to that file share, which seems about right for a 100 mega**bit** connection. Latency is under 1ms.

Of course SMB (like most network file protocols) gets slow when you start dealing with a ton of small files, which is basically what git is. I can tell the difference when running git from powershell. `git status` takes ~2 seconds on the network copy of this repo vs being practically instant on my local copy. The other thing that comes to mind would be file watching. I know very little about how that works in VS Code or over SMB.

**Comment by bpasero** [comment]
Still not clear to me how this surfaces: randomly when you save a file VSCode will freeze? Can you share a screencast or some more visual information when and how this happens?

**Comment by 9072997** [comment]
In this case it was when I opened a file, though it happens on save sometimes too. Sorry for the potato quality. I had to leave this running while I was working, so I'm only recording at 2 FPS. The UI looks choppy because of this. It is actually very smooth.

https://send.firefox.com/download/811849a978a58dea/#vcJQAWywD9e1X3ReoIhVxQ

**Comment by bpasero** [comment]
@9072997 ok, so to clarify: you see blue spinning bars in the editor and explorer once this happens but nothing freezes and the UI is fully functional? 

Unfortunately I do not think this issue is something VSCode can fix because we simply rely on node.js for all file system matters (https://github.com/nodejs/node) and they in turn probably call some OS APIs for this purpose. So how can we rule out that this is not something that happens outside of VSCode?

**Comment by 9072997** [comment]
Yes, that is correct.

As demonstrated in the video, I can interact with the git repo using git and I can open the file in notepad. Both are fast. That seems to rule out OS API stuff as presumably git and notepad have to make the same OS API calls. I'm not sure how to rule out bugs in node.js . Any recommendations?

**Comment by 9072997** [comment]
If the primary issue is reproducibility, I can try to lab this up with a less sensitive repo on a couple of VMs this weekend, and send you the VMs if I am successful in reproducing the issue.

**Comment by bpasero** [comment]
Yeah I think what we need to get at is a reproducible case for node.js though to report this upstream. If a VM is not too much work for you, feel free to send it to me and I can try to reproduce + see if it is VSCode or node.js specific.

**Comment by 9072997** [comment]
I cannot make this happen with my test setup. I fired up wireshark to try to see what was happening while vscode was stuck trying to open a file, and saw a lot of SMB traffic referring to the share `\\server\c` where my share is `\\server\c$`. This gave me the idea to try mapping the share as a network drive so the path would no longer have the $ in it. This seemed to fix the issue and is a suitable workaround for me. Feel free to close this. Sorry for wasting your time.
