### ISSUE TITLE
Activity bar items without associated views appear in the latest insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#88174]
See https://github.com/microsoft/vscode-js-debug/issues/205. PWA has had a contribution to the activity for several months with no associated views, but in the latest insiders it started appearing there. @eamodio indicated this may be a bug in VS Code.

(Note that the "blank icon" part of the linked issue is not a problem; pwa uses [the square [JS] logo](https://github.com/microsoft/vscode-js-debug/blob/master/resources/logo.svg), that part was displaying fine)

**Comment by eamodio** [comment]
Yeah this is a regression. You can see the same behavior if you set all GitLens views to something other than the GitLens sidebar. Then you'll be left with a GitLens icon in the activity bar that will go away if you click on it.

**Comment by sandy081** [comment]
Yeah, it was broken due to the refactorings I did to merge viewlet descriptor into view container.
