### ISSUE TITLE
Add conditional ctrl+c/v to copy on integrated terminal similar to cmd

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8818]
From @bldesign in https://github.com/Microsoft/vscode/issues/6451#issuecomment-230595940

> Maybe integrated terminal can present same feature as native Windows terminal, on Windows.
> 
> In the property options there are edition options with the ability to active <kbd>ctrl</kbd> shortcuts. It's just what we are talking about. It kills the process only if there is no selection. Cool no? _VS Code_ can do it.
> 
> Sorry my preview is in french, but yours certainly looks the same.
> ![terminalpropertiesoptions](https://cloud.githubusercontent.com/assets/2221676/16598938/75102700-4300-11e6-8063-0c357febefcb.png)
> 
> With all options enabled. You can:
> 1. Copy paste <kbd>ctrl</kbd> + <kbd>c</kbd> / <kbd>v</kbd> even when a process is running (kills only if no selection)
> 2. Always paste <kbd>ctrl</kbd> + <kbd>v</kbd> (after process ended)
> 3. Select text with mouse
> 4. Select text with keyboard <kbd>shift</kbd> + <kbd>←</kbd> / <kbd>→</kbd>
> 
> You can copy, paste and select text only with keyboard on Windows. 
> (Both terminal, integrated and not are Microsoft **Windows [version 10.0.10586]**)
> 
> Can you expose these options to user preferences?

**Comment by warpdesign** [comment]
+1 that would be nice!

**Comment by vstoykov** [comment]
Terminal shortcuts on Windows, Linux and Mac are different and probably need to be the same for the OS you are using.

 - Mac - Cmd+C/Cmd+V
 - Linux - Ctrl+Shift+C/Ctrl+Shift+V
 - Windows - Ctrl+C/Ctrl+V (I never new that you can use this in windows terminal)

Actually currently I'm unable to copy/paste anything to/from VS Code terminal. Right click menu with Copy/Paste options will be helpful.

**Comment by Tyriar** [comment]
@vstoykov Insiders currently allows ctrl+shift+c/v on Windows and Linux, this is coming to Stable in a week or so. It also contains a context menu :smiley: 

For Linux you can also use middle click to paste selection into the terminal, use this if you're sticking to stable for the time being.

**Comment by vstoykov** [comment]
@Tyriar thanks for the info. I will wait for now until new stable version is ready.

**Comment by Tyriar** [comment]
A change was just made that allows rebinding the terminal commands to anything and they should skip the terminal and work. This means that ctrl+c/v can be bound to copy and paste now, a `terminalTextSelected` state or similar needs to be implemented before conditional keybindings can work though.

**Comment by whitecolor** [comment]
Yes this is needed if `terminalTextSelected` ctr+C should copy the text.

**Comment by Tyriar** [comment]
@whitecolor the work in this issue is essentially to add `terminalTextSelected`.

**Comment by Tyriar** [comment]
Hey @alexandrudima, from what I can see all information around a command's context keys are currently private. Is it possible to expose this so that I can use `IContextKeyService.contextMatchesRules` to ensure I'm only allow keybindings that have valid `when` clauses to skip the terminal?

So given a set of command IDs (`string[]`), I need to get their keybindings (I'm currently using `IKeybindingService.lookupKeybindings`) in addition to their associated `ContextKeyExpr` (all hidden from what I can see).

See https://github.com/Microsoft/vscode/commit/cf28f6d081ef7f4ccac90b35512d92723499969b#diff-8c4484557359fefa25fe7396aa970c56R119

**Comment by alexandrudima** [comment]
@Tyriar I've read through this issue, but I'm not fully understanding what you mean. 

* By default xterm interprets **and** eats up (stop propagation?) all keydown events
* You have a hook from xterm in the form of `attachCustomKeydownHandler`.
* If you return false for a keydown event, then xterm will not interpret and not eat up the event.
* In consequence, if you return false, we get to interpret and dispatch the event possibly to a command in our world.
* So you would like to "find out" ahead of time what the keydown event would do and if it would end up executing a command in a certain set, but without actually executing it now, then you'd return false, and the command would end up being executed by the keybindingsService eventually.

Is this what you mean?

**Comment by Tyriar** [comment]
@alexandrudima basically yeah, currently if the keybinding pressed matches one of the commands in some list it will pass it through. The problem is when implementing this is that I only want to have ctrl+c skip xterm only if the `when` property of the command is fulfilled. It's very important this only happens when the `when` property (`terminalTextSelected`) because ctrl+c is the keybinding the terminal uses to send `SIGINT` to the terminal.

**Comment by alexandrudima** [comment]
I've extracted #14603 so we don't forget about it.

**Comment by whitecolor** [comment]
Didn't forget?

**Comment by Tyriar** [comment]
I actually forgot about the branch I was working on for this, just merged into master!
