### ISSUE TITLE
Breakpoint maps to a wrong outFile

### ISSUE THREAD

**Issue by kamechb** [microsoft/vscode#88187]
- VSCode Version: 1.36.1 
- OS Version: macOS Catalina 10.15.2 

I use webpack bundles two output files with source map enabled, for example main.js and server.js. 
When I set a breakpoint in a TS file which is included in both files source map, it maps to main.js file, but actually I want it to be mapped to server.js. 
![image](https://user-images.githubusercontent.com/208991/71872011-10619300-3156-11ea-99ff-6f060dae86ff.png)

Is there a way to fix it?

**Comment by weinand** [comment]
You will have to configure your webpack-based build process to produce sourcemaps with the desired contents. This is not a problem with VS Code.

**Comment by kamechb** [comment]
But if a TS file shared by client side code and server side code in a universal app, it will be imported in both bundled files. So in this case, how could we set breakpoints correctly in that shared file? vscode debugger could not know which file should map to, right?

**Comment by weinand** [comment]
Sourcemaps map from (webpacked) JS files to TS file, not the other way around. So a shared TS files means that more than one (webpacked) JS file references the same TS file.

Setting a breakpoint in a shared TS file means that VS Code's JavaScript debugger has to find all JS files that "map" to the TS file and set breakpoints there.

Assuming that the two webpacks are not loaded into a single runtime, you can specify which (webpacked) JS file is considered by specifying it in the outfiles attribute of a node.js debug config, e.g. `"outfiles": [ "${workingFolder}/server.js" ]`.

/cc @roblourens @connor4312

**Comment by kamechb** [comment]
yeah, if two webpacks are not loaded into a single runtime, it works fine. But in my case as a universal app, I have a server.js(an express server) and main.js(app code), and server.js needs to use main.js to render the app in server side, so they will be loaded in the same runtime. So in this case, the breakpoints set in shared files will not work.

This seems not a bug, but good to have it as a feature request.

**Comment by connor4312** [comment]
You can try using our [new debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly) which is in preview and does not have this limitation.

**Comment by kamechb** [comment]
cool, thanks! will have a try.
