### ISSUE TITLE
Select multiple files for deletion, the file being edited will also be selected by default

### ISSUE THREAD

**Issue by liushichuan** [microsoft/vscode#88188]
Issue Type: <b>Bug</b>

When pressing ctrl to select multiple files for deletion, even if the file currently being edited is not manually selected, it will be deleted together. In fact, I have a list that needs to be deleted. I look at the contents of the list and decide which files to delete next. Then I press ctrl to select the files to be deleted, and delete them. Then the list files are gone. This problem has a particularly high probability of occurrence. Every time, I need to go to the recycle bin to search hard, which is not in line with the use logic. I hope that engineers can solve it.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.15.0-30deepin-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (4 x 2182)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|3.77GB (0.86GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
comments|Ale|1.0.4
c-cpp-compile-run|dan|1.0.5
c-cpp-flylint|jbe|1.2.4
git-graph|mhu|1.20.0
vscode-language-pack-zh-hans|MS-|1.41.2
python|ms-|2019.11.50794
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2
notepadplusplus-keybindings|ms-|1.0.5
cmake|twx|0.0.17
markdown-pdf|yza|1.4.1

</details>

**Comment by isidorn** [comment]
I can not reproduce this issue. Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
Also try setting `explorer.autoReveal: false` as a workaround
