### ISSUE TITLE
TS: compile error only discovered from command line, not editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88189]
Steps to Reproduce:

1. revert https://github.com/microsoft/vscode/commit/d3147a5ac69431308f50acfc3f1de7bf13d1130b 
2. open searchEditor.ts
3. notice no compile error
4. run `tsc -p src/tsconfig.json --noEmit`

=> 🐛 notice compile errror

```
src/vs/workbench/contrib/search/browser/searchEditor.ts:241:21 - error TS2352: Conversion of type 'IDiffEditorModel' to type 'ITextModel' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'IDiffEditorModel' is missing the following properties from type 'ITextModel': uri, id, isForSimpleWidget, mightContainRTL, and 96 more.

241     const textModel = model as ITextModel;
```

**Comment by bpasero** [comment]
Same with TS 3.8 btw.

**Comment by mjbvz** [comment]
The code has changed significantly since this was opened. Let me know if you see this again in the current codebase with TS 3.9
