### ISSUE TITLE
Moving lines of code down inreases their indentation for no reason

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#88180]
![ezgif com-optimize](https://user-images.githubusercontent.com/490562/71860228-f5dbe980-3156-11ea-831e-ce05b4d3fb60.gif)

Issue Type: <b>Bug</b>

See screen recording. Select lines of code, move them up and all works fine. Move them down, and every movement down increases their indendation.

The setting Format On Type is disabled.

Reproduces with all extensions disabled.

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:55:38.353Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
vscode-eslint|dba|2.0.11
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
file-icons|fil|1.0.20
gc-excelviewer|Gra|2.1.32
json2csv|kha|0.0.1
l13-diff|L13|0.21.0
git-tree-compare|let|1.7.1
vetur|oct|0.22.6
multi-command|ryu|1.3.0
vscode-fileutils|sle|3.0.0
control-snippets|svi|1.7.1
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.9.6
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
What language is this? JS

**Comment by mjbvz** [comment]
Also please share small code sample (as text!)

**Comment by adamreisnz** [comment]
Yes javascript.

```js
const foo = [
{
  foo: 'Foo',
  bar: [
    'bar',
    'baz'
  ],
];
```

**Comment by adamreisnz** [comment]
What is the duplicate issue please? So I can follow it there..
