### ISSUE TITLE
How to fix 'unresolved import 'tensorflow.keras'?

### ISSUE THREAD

**Issue by wangyexiang** [microsoft/vscode#88184]
- VSCode Version: latest version
- OS Version:win7-64bit
- tensorflow Version:  tensorflow2.0-cpu

![图片](https://user-images.githubusercontent.com/23202109/71864027-9e7b5080-3139-11ea-8954-28a28e5ee447.png)

How to fix 'unresolved import 'tensorflow.keras'?

**Comment by melMass** [comment]
Please name the issue properly like `How to fix 'unresolved import 'tensorflow.keras'?`
