### ISSUE TITLE
Terminal display problems under Windows 10, version 1.41

### ISSUE THREAD

**Issue by hexiaobing5880** [microsoft/vscode#88186]
- VSCode Version: Windows 10
- OS Version: version 1.41

Steps to Reproduce:
1.git clone XXXX
2.halfway，ctrl + c

display :
remote: Compressing objects: 100% (358/358), done.
PS C:\Users\hexiaobing\Desktop\github>  19.57 MiB | 21.00 KiB/s

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
