### ISSUE TITLE
Allow to Ctrl+click in File > Open Recent to open in new window

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8819]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 7

Steps to Reproduce:

1. Press Ctrl
2. Using the File menu, File > Open Recent and select a folder

The folder opens in the current VS Code instance. Using Ctrl along with Open Recent should open a new VS Code instance according to the June_2016.md release notes ("Open Recent in a new Window").

Note: that Command Palette File: Open Recent does create a new VS Code instance.

**Comment by bpasero** [comment]
Works for me, though I only press the Ctrl key after the list is opened. Works for both mouse click and Enter with pressed Ctrl key.

**Comment by gregvanl** [comment]
Hmm, weird. I can't get it to work on Windows, Linux or OS X.  Pressing Ctrl (Cmd on OS X) before or after the list is open doesn't matter. I guess we'll see if anyone else has trouble.

**Comment by gregvanl** [comment]
Oh, File > Open Recent from the menu doesn't behave the same way as File: Open Recent from the Command Palette.  That seems confusing.  I'll update the issue.

**Comment by bpasero** [comment]
Good point and actually with the Electron update we could implement this 👍
