### ISSUE TITLE
alert confirm when open recent workspace

### ISSUE THREAD

**Issue by zhangddjs** [microsoft/vscode#88195]
🚀 Feature Proposal
As title, can you alert confirm when I click open recent workspace?
just like what IntelliJ IDEA does.
![image](https://user-images.githubusercontent.com/30108045/71879524-3d6b7100-3169-11ea-8a70-00166efc8be5.png)
so that we don't need to open new windows before open recent workspaces.
Thank you.

**Comment by gjsjohnmurray** [comment]
Hold Ctrl / Cmd down when clicking the Recent entry and it will open in a new window.

**Comment by connor4312** [comment]
You can also configure this behavior using the `window.openFoldersInNewWindow` setting.

**Comment by zhangddjs** [comment]
Thank you all. It really helps me.
