### ISSUE TITLE
TS server crashing repeatedly 

### ISSUE THREAD

**Issue by askdesigners** [microsoft/vscode#88196]
Issue Type: <b>Bug</b>

Just browsing files and the TS server crashes. Also the laptop fan is pegged out, indicating some runaway process.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 4, 6|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
awilix-vscode-container-definitions|iki|0.0.4
docthis|joe|0.7.1
rainbow-csv|mec|1.4.0
Angular-BeastCode|Mik|8.1.2
music-time|sof|1.3.7
swdc-vscode|sof|1.3.9
change-case|wma|1.0.0
join-lines|wma|0.2.2

</details>

**Comment by connor4312** [comment]
Can you share what version of the TS language server you're running? It should be shown in the lower right hand corner of the screen when a TS file is open.

/needsMoreInfo
