### ISSUE TITLE
Search Tab does not appear on the panel.

### ISSUE THREAD

**Issue by Elastino** [microsoft/vscode#88198]
- VSCode Version: 1.42.0-insider
- OS Version: Darwin x64 19.2.0

Steps to Reproduce:

1. Updated vscode to 1.42.0. 
2. Search Pane does not appear when Search Location is set to Panel.
Search Pane appears when Search Location is set to sidebar.

Does this issue occur when all extensions are disabled?: Yes

**Comment by melMass** [comment]
Same here, it actually opens a terminal when I run the command "Find in Files" or Ctrl + Shift + F
It worked well last night, I've disabled every extension, tested on different projects... But it's still an issue :/

**Comment by melMass** [comment]
The issue is only in insiders btw

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/88132

**Comment by melMass** [comment]
@sandy081 Thanks, so it should be fixed ?
