### ISSUE TITLE
perf: git diff view scrolling has poor framerate

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#88199]
When looking at a git diff view, scrolling feels laggy, frames are dropped. I believe the more changes (multiple green and red sections) the worse it gets.

**VS Code:**

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0 (Catalina 10.15.2)
```

**System specs:**

```
Model: MacBook Pro (15-inch, 2017)
CPU: 2,8 GHz Quad-Core Intel Core i7
Graphics: 
  - Radeon Pro 555 2 GB
  - Intel HD Graphics 630 1536 MB
```

**Steps to Reproduce:**

1. Open a git diff view with multiple separate change sections (the more the merrier)
1. Scroll up and down
1. Notice visible "framedrops" while scrolling (it drops to some 25-30fps on my machine)

**Expected behaviour:**

Ideally the scroll frame rate would not drop below 50fps, ideally staying at buttery-smooth 60fps.

Does this issue occur when all extensions are disabled?: **Yes**

Below you can also find a Chrome performance report with screenshots, stack traces, framerate and other goodness that may help you in troubleshooting. I am also including a performance report of a normal editor scrolling, just for comparison so you have a reference frame in case this turns out to be heavily device/GPU-dependent.

As I do not fully understand the architecture of VS Code or Electron, sadly, I cannot deduce what is wrong, but looking at the perf data I see that the `GPU` bar is a lot more greener than the `GPU` bar in the regular editor scroll perf report, suggesting a much heavier GPU usage while scrolling in the git diff view than in a regular editor.

Thanks for looking into this! Let me know if I can provide any further troubleshooting information.

**Performance profiles:**

[Scrolling in a git diff view](https://github.com/microsoft/vscode/files/4030046/diff-view-scroll.json.zip)
[Scrolling in a regular editor view (working as intended, just for reference)](https://github.com/microsoft/vscode/files/4030049/editor-view-scroll.json.zip)

**Comment by rebornix** [comment]
Screenshot for the perf data for diff view scrolling, 30+ms in total

![image](https://user-images.githubusercontent.com/876920/71919520-bb178880-3139-11ea-8df4-8106b9119228.png)

Screenshot of regular one, 18ms in total

![image](https://user-images.githubusercontent.com/876920/71919665-0f226d00-313a-11ea-863f-500f23f4020f.png)

**Comment by alexdima** [comment]
@robertrossmann Thank you for the issue, but I have to be honest and say that this is not really actionable.

To sum up, the issue is more or less that "rendering is slow". And since the diff editor renders two editors, rendering the diff editor is twice as slow.

This is good to know, and we should improve, but it is not really clear what should be changed... All I can say is that everything costs. Minimap on? That costs time. Indent guides on? Same. Render whitespace on? Same. At one point, depending on the file shape, the diff shape, the number of decorations, and the settings, the 16ms frame budget will be busted.

Unfortunately, it is not clear what change we should do given the provided steps.

**Comment by robertrossmann** [comment]
Hi @alexdima! Thank you for the feedback. I understand that there is not much to go on. My goal was to provide

1. UX feedback (my 2017 Core i7 MacBook Pro cannot render fast enough to keep the scrolling smooth, even when a dedicated Radeon Pro 555 is being used)
1. A performance snapshot in case there is an obvious performance killer somewhere on the loose so that perhaps someone who knows how the diff view works would be able to eliminate that perf killer

If you say that the diff view is currently beyond any kind of optimisation and that there are no obvious bottlenecks which could potentially be eliminated (based on the performance report) I think you can safely close the issue.

Sorry that I do not have more to go with. I'm just trying to help the VS Code team find areas which could benefit from improvements. ❤️
