### ISSUE TITLE
Variable font and size depending on DPI

### ISSUE THREAD

**Issue by waclaw66** [microsoft/vscode#88194]
Hello!

I switch different monitor setups very often (work FHD 24" 100% text size / home 4k 27" 175%). Because of this I need to use different fonts and sizes for each of monitor. The default Consolas font  (vector fonts in general) is too blurry at 24", therefore I need to use bitmap font with sharp edges. On the other hand there is no such problem with 4k 27" monitor at all, the antialiased font looks sharp enough.

Would it be possible to make a customazible font setups depending on DPI value (or percentage of text size)? It would be very helpfull for me.

Thanks a lot!

**Comment by erhhung** [comment]
Want to upvote this request as I like to use the "FiraCode-Retina" font, and that works great on my MBP screen, but when I plug into my old desktop TB display w/o Retina at the office, it appears too bold, so I want to use "FiraCode-Light" instead.

**Comment by AlexAegis** [comment]
I think this will be increasingly important with the upcoming settings sync update
