### ISSUE TITLE
Update icon to match Visual Studio 2015 Update 1

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#882]
![screenshot 24](https://cloud.githubusercontent.com/assets/10532611/11511474/95c60e3e-9869-11e5-9724-6285851fd712.png)

**Comment by bgashler1** [comment]
Thanks for catching this.  I just checked with our icon designers; this change was intentionally just for Visual Studio 2015 (since many VS 2015 users also have legacy versions of VS installed, and it was confusing which one was the latest version since the icons were the same).  Since Visual Studio Code is continuously updated and there are no legacy versions, they left the logo the same.

**Comment by felixfbecker** [comment]
I can remember though how you updated the icon back then to match the white outline of the VS icon. You tweeted "sometimes it's the little things" and I agree with that... VS Code icon should match the VS icon in a blue color. I don't see continuous updates as a counter argument - you want people to associate the icon with the newest version of VS, not VS 2013, right? Imo If this association is not wanted then this editor should not have VS in its name and a totally different icon...

**Comment by felixfbecker** [comment]
I can remember though how you updated the icon back then to match the white outline of the VS icon. You tweeted "sometimes it's the little things" and I agree with that... VS Code icon should match the VS icon in a blue color. I don't see continuous updates as a counter argument - you want people to associate the icon with the newest version of VS, not VS 2013, right? Imo If this association is not wanted then this editor should not have VS in its name and a totally different icon...

**Comment by bgashler1** [comment]
I definitely understand where you're coming from.  However, tthe team for Visual Studio 2015 made this decision on their own just to differentiate it from multiple legacy versions (which was causing challenges to users).  This was not a brand update or refresh; it was just to solve a problem.  We don't have that same problem, and carrying it over to VS Code isn't something our team wants to do at this time.  We hope you understand.

**Comment by felixfbecker** [comment]
@bgashler1 thanks for the explanation.

**Comment by Den-dp** [comment]
Actually it is quite sad that now the VSCode icon drawn as something in between Edge' icon (no outline) and old VS2015 (with filled background). Both approaches separately look cool (especially on dark background), but not this one (without a white outline but with a white background/fill).
![syvcrld](https://cloud.githubusercontent.com/assets/1770529/13442937/483b1a66-e007-11e5-9a83-c1bf0c08930b.png)

**Comment by bgashler1** [comment]
@Den-dp: thanks for sharing the feedback.  We are addressing the comments we've received from our icon in the next release.
