### ISSUE TITLE
VS code with WSL doesn't work if closed and opened again

### ISSUE THREAD

**Issue by georgetour** [microsoft/vscode#88205]
Issue Type: <b>Bug</b>

If I start windows and enter a wsl distro and then type code . in the folder I want, visual studio code opens normally. If I clode visual studio code and do the same things, visual studio code pops many errors like couldn't fetch remote environment and failed to connect to remote extension. The distro is Ubuntu 18.04, downloaded from store. I tried powershell and cmd but same result.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19536
Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: connect ECONNREFUSED ::1:40261

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.95GB (6.64GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/c/Users/tourt/Documents/working_now --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: connect ECONNREFUSED ::1:40261
</details>Extensions: none

<img width="766" alt="visual-studio-code-wsl-bug" src="https://user-images.githubusercontent.com/12733888/71897423-36d7fc00-315f-11ea-8ed1-33142d4c1d64.png">

**Comment by aeschli** [comment]
I think that's a dup of https://github.com/microsoft/vscode-remote-release/issues/2060 caused by WSL issue in 19536.
I just pushed a new version of the Remote - WSL extension (0.41.7). Please try if this fixed your issue!
