### ISSUE TITLE
TypeScript shows stale errors

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#88209]
I lately see a lot of stale errors with TypeScript which can only be cleared if I restart the TS Server using the corresponding command. An example looks like this:

![capture](https://user-images.githubusercontent.com/1931590/71900119-71409980-315d-11ea-9015-429dca64d047.png)

I have no concrete steps to reproduce since entering the same code doesn't always result in the same behavior. What I did notice is that it happens more frequently under WSL than under native Windows. 

All other TS functionality is still working correctly (e.g. code complete) so I think it is not a ts server problem rather a timing problem in the TS extension (but it is speculation on my end).

**Comment by dbaeumer** [comment]
Another case:

![capture](https://user-images.githubusercontent.com/1931590/71901274-ead98700-315f-11ea-9630-b598eb2d6cce.png)

**Comment by dbaeumer** [comment]
Closing and opening the file removes the errors as well.

**Comment by dbaeumer** [comment]
In the example above I miss typed `new` using `mew`. Although I corrected the error the problem stayed.

**Comment by dbaeumer** [comment]
After quite some trying I was able to reproduce in self host:

![capture](https://user-images.githubusercontent.com/1931590/71908219-e0be8500-316d-11ea-9d24-2b67846ae986.png)

**Comment by dbaeumer** [comment]
I was setting a breakpoint in the marker service and actually TypeScript for some reasons reports stale markers:

![capture](https://user-images.githubusercontent.com/1931590/71909002-56772080-316f-11ea-9bb3-fad752745821.png)

![capture](https://user-images.githubusercontent.com/1931590/71909040-6bec4a80-316f-11ea-917d-0914cee96bbc.png)

As you can see the error about the `x is declared` is actually stale.

**Comment by mjbvz** [comment]
Any errors in the dev console? Does this repro if you disable all extensions? Also, when did this start happening?

**Comment by dbaeumer** [comment]
No errors in the dev console. It also happens when running out of source in which case I only have the remote extensions installed (see https://github.com/microsoft/vscode/issues/88209#issuecomment-571650499) . I saw this first shortly before Christmas but did not dig deeper. Happens quite frequently now to me but I have no exact steps to reproduce. @alexdima said he sees this in self host as well.

**Comment by dbaeumer** [comment]
And I think this deserves an important label since it makes VS Code with TypeScript hard to use for me since I need to restart the TS server or open and close all files every ~10 Minutes.

**Comment by dbaeumer** [comment]
The following screen shot is out of source with all extension disabled.

![capture](https://user-images.githubusercontent.com/1931590/71931014-1cbd0e80-319d-11ea-8d9e-fffcbfc3cd33.png)

**Comment by dbaeumer** [comment]
Nothing in the console.

**Comment by dbaeumer** [comment]
More findings: when typing on the same line with the stale error no additional marker updates are triggers on the renderer side. When adding another error on another line below the marker update is triggered but contains the stale error as well:

![capture](https://user-images.githubusercontent.com/1931590/71931431-05325580-319e-11ea-8b85-dc30d5658c83.png)

![capture](https://user-images.githubusercontent.com/1931590/71931462-18452580-319e-11ea-84f3-f8164cd1dea7.png)

**Comment by dbaeumer** [comment]
![capture](https://user-images.githubusercontent.com/1931590/71931652-7d008000-319e-11ea-9260-1b2a42e2b475.png)

**Comment by dbaeumer** [comment]
Debugged the extension host and the stale error is in the internal TS extension's diagnostic manager
![capture](https://user-images.githubusercontent.com/1931590/71932604-6d823680-31a0-11ea-8952-2088a3315e0b.png)

**Comment by mjbvz** [comment]
Can you also please try setting `"typescript.tsserver.trace": "verbose"` and then looking for the semantic/syntactic errors TS sends back. I want to understand if we are caching these errors on the VS Code side, or if TS server itself is sending them back to us

**Comment by dbaeumer** [comment]
Interestingly all further updates of diagnostics come with kind 0

![capture](https://user-images.githubusercontent.com/1931590/71932914-2fd1dd80-31a1-11ea-911c-0bb1f9887ee5.png)

**Comment by dbaeumer** [comment]
What makes the stale error go away is adding the following line to the source file

`console.log(mapping);`

The triggers a diagnostic update with kind 1 which clears the stale errors.

![capture](https://user-images.githubusercontent.com/1931590/71933243-f483de80-31a1-11ea-988b-1386ac8ec8ad.png)

@mjbvz for the the problem looks like that the error `Expected 2 arguments, but got 1` at some point got reported under a kind 1 but when fixed only diagnostics with a kind !== 1 got updated, hence the stale error.

**Comment by dbaeumer** [comment]
@mjbvz regarding your question. The TS Server is not sending them again  (see additional screen shots above). It is because we are caching them and the TS Server never sends an empty update for the right diagnostic kind. I don't know if this is a problem of the TS Server or whether we can't make the assumption of correct kind clearance.

**Comment by dbaeumer** [comment]
Could it be that something in the TS Server gets canceled when I continue typing. As said this is not easy to reproduce and requires quite some typing in the same area before it happens.

**Comment by mjbvz** [comment]
Yes that is possible. We cancel the `geterr` call to TS server when user requests come in (such as a hover). We should then re-queue those but there may be a problem.

Could you please send me a TS trace from when this happens? I also asked around Redmond but others have not noticed this problem

**Comment by mjbvz** [comment]
Also, what TS version are you using in your workspace?

**Comment by dbaeumer** [comment]
The TypeScript version I use is `3.7.4`.  Regarding tracing: I will spent some time to reproduce it with tracing enabled. When it happens enabling tracing is IMO to late since the clearing call with the right kind is already missing.

**Comment by dbaeumer** [comment]
Here is another case:

![capture](https://user-images.githubusercontent.com/1931590/71966329-a30b3c00-3201-11ea-92db-1322c77d09d1.png)

[88209-trace.txt](https://github.com/microsoft/vscode/files/4034523/88209-trace.txt)

**Comment by mjbvz** [comment]
From the logs, seems like we aren't getting back semanticDiagnostics responses from TS after a certain point. That would explain why you see the stale semantic errors

Opened https://github.com/microsoft/TypeScript/issues/36081 to continue investigation upstream

**Comment by epranka** [comment]
Same issue. Also, stale errors appears than I format the document.

Before:

![image](https://user-images.githubusercontent.com/21198957/72008946-8dc3fb00-325d-11ea-9bf2-32cc23d39d74.png)

After:

![image](https://user-images.githubusercontent.com/21198957/72008982-9e747100-325d-11ea-8fda-7ac48db3f78a.png)

Helps file reopening or restarting TS server.

Typescript: 3.7.4
VSCode: 1.41.1
OS: Linux 18.04

**Comment by dbaeumer** [comment]
@mjbvz actually while I was debugging it yesterday the semantic response do come if I introduce certain errors. See my comment here: https://github.com/microsoft/vscode/issues/88209#issuecomment-571794929

So I don't think it gets completely stale.

**Comment by dbaeumer** [comment]
@mjbvz is there anything that we can do on our side to work around this. This makes VS Code really hard to use for me on my LSP and ESlint projects.

**Comment by epranka** [comment]
> @mjbvz is there anything that we can do on our side to work around this. This makes VS Code really hard to use for me on my LSP and ESlint projects.

I disabled TypeScript validation now. It's not the best solution, because the lost TypeScript Idea, but I can work with it, because the errors are reported by compiler and linter.

"typescript.validate.enable" = false
"javascript.validate.enable" = false
