### ISSUE TITLE
regarding loop and terminal

### ISSUE THREAD

**Issue by sandeeppatel7** [microsoft/vscode#88206]
![Uploading Screenshot ### ### ### ### 

> 

> [**(54).png…]()**]([url](url
![Screenshot (55)](https://user-images.githubusercontent.com/56965055/71897901-eae87f80-317d-11ea-86f7-1ed9e15a2a7c.png)
))

Issue Type: <b>Bug</b>

when loop runing countinous infinite time then  after i kill terminal then vsc hanged and notification shows reopen or wait ..
![Screenshot (18)](https://user-images.githubusercontent.com/56965055/71897583-043cfc00-317d-11ea-96a9-446b975fe167.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.9.15
cpptools|ms-|0.26.3-insiders2

</details>

**Comment by connor4312** [comment]
Can you upload some code or a repro that reproduces the issue?
