### ISSUE TITLE
Searching in dirs with specific file types doesn't work any more

### ISSUE THREAD

**Issue by dzungtran89** [microsoft/vscode#88201]
- VSCode Version: 1.41.1
- OS Version: macos 10.14

Steps to Reproduce:

1. Open project source code
2. Cmd+shift+F to search
3. In the box `files to include`, type directory and file types, ie: module,*.py - it means that I would like to search all python files in dir `module` and its subdirs

Expected search result:
- Only show the result in `module` dir and its subdirs, its parent dirs should not be shown

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I think you mean `module/**/*.py`. Your query means "all files in module and also all .py files"

**Comment by dzungtran89** [comment]
Hi,

Thanks for quick reply

Please have a look at the below image

![image](https://user-images.githubusercontent.com/46039081/71943329-e1e5c580-31f2-11ea-93e4-6520c122cbb3.png)

The expected result should show **ONLY** the file `server.py` because it's in the dir `service` as predefined; the file `config.py` is not supposed to be in the search result

**Comment by roblourens** [comment]
No, like I said, you need to use `service/*.py`, a comma will essentially be "OR" not "AND"
