### ISSUE TITLE
My vscode can't open my code file which path in workspace

### ISSUE THREAD

**Issue by xuzequn** [microsoft/vscode#88203]
I want open my file in workspace, but this fail occur.
Unable to open 'api_model.py': Unable to read file (Unknown (FileSystemError): Error: ENOTDIR: not a directory, stat '/workspacepath/file/workspcepath/file').
I reinstall vscode,but can't fix this problem.
I don't know how to fix it .

**Comment by connor4312** [comment]
Can you provide reproduction steps for this?

/needsMoreInfo

**Comment by zhuhonglinX** [comment]
I have the same problem with Mac Catalina and vscode newest version.
It seems the problem of Microsoft Python Language Server. I use jedi and everything is ok.
But maybe jedi is not good enough, you could try kite for auto-completion.
