### ISSUE TITLE
Python programs execution is very slow

### ISSUE THREAD

**Issue by Avik-nag** [microsoft/vscode#88202]
We have written the need
Issue Type: <b>Performance Issue</b>

writing a long program on python , after clicking on 'run' the execution is very slow.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    83	  7404	code main
    0	    15	  4900	   electron-crash-reporter
    2	    59	  6308	   window (Issue Reporter)
    3	   155	 10060	   gpu-process
    0	    71	 12740	   shared-process
    0	   186	 13084	   window (Welcome - p1 - Visual Studio Code)
    0	    11	  1900	     watcherService 
    0	    11	  1152	       console-window-host (Windows internal process)
    0	   109	  2776	     extensionHost
    0	    64	  8956	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     8	 10756	     console-window-host (Windows internal process)
    0	    34	 12668	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - p1 - Visual Studio Code)
|    Folder (p1): 36 files
|      File types: py(10) mp3(9) txt(3) wav(3) json(2) google-cookie(1)
|                  pickle(1) class(1) java(1) rb(1)
|      Conf files: launch.json(1)
|      Launch Configs: java(2);
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
lit-html|bie|1.11.1
python-extension-pack|don|1.6.0
java-debug|DSn|0.0.2
vscode-html-css|ecm|0.2.3
code-runner|for|0.9.15
rails-snippets|Hri|1.0.8
python-coding-conventions|igr|0.0.4
vsc-python-indent|Kev|1.8.1
MagicPython|mag|1.1.0
python|ms-|2020.1.56281-dev
js-patterns-snippets|nik|0.0.5
vscode-html-scss|P-d|0.0.42
vscode-css-peek|pra|3.0.2
ruby|reb|0.26.0
java|red|0.55.1
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-icons|vsc|9.7.0
vscode-ruby|win|0.26.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>
ed data into your clipboard because it was too large to send. Please paste.

**Comment by Avik-nag** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [code execution is slow (#87020)](https://www.github.com/microsoft/vscode/issues/87020)

sorry , it wasn't covered by any exeisting links.

**Comment by oneslash** [comment]
@Avik-nag, would be great if you can provide a minimal application which you are trying to launch?

**Comment by connor4312** [comment]
This is likely related to the program you're running, the machine you're on, or the Python extension; VS Code is not involved in execution
