### ISSUE TITLE
Refactor actions fail on code blocks using optional chaining (TS/JS)

### ISSUE THREAD

**Issue by Jayphen** [microsoft/vscode#88204]
Issue Type: <b>Bug</b>

To reproduce this, open a Typescript file and enter the following:

```ts
const test = { key: 'val' };
const broken = test?.key;
```

Highlight these two lines and try to "Extract to function in module scope".

VSCode throws an error:

```
TypeScript Server Error (3.7.3) Debug Failure. False expression. Error: Debug Failure. False expression. at getPos (tsserver.js:119224:22)
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
jest-snippets|and|1.7.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-react-proptypes-intellisense|cun|0.0.3
vscode-eslint|dba|2.0.11
vscode-dash|dee|2.3.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
gitlab-workflow|fat|2.1.1
docthis|joe|0.7.1
vscode-peacock|joh|3.2.0
vscode-styled-components|jpo|0.0.27
yarn-lock-syntax|mar|0.1.3
vscode-docker|ms-|0.9.0
python|ms-|2019.11.50794
Go|ms-|0.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1404
debugger-for-chrome|msj|4.12.3
snippet-creator|nik|0.0.5
advanced-new-file|pat|1.2.0
git-file-history|pom|1.0.1
vscode-graphql|Pri|0.2.2
remote-vscode|raf|1.1.0
ruby|reb|0.26.0
postcss|ric|2.0.0
rust|rus|0.7.0
mdx|sil|0.1.0
vscode-fileutils|sle|3.0.0
vsc-favorites|Sli|1.0.0
rewrap|stk|1.9.1
vscode-lua|tri|0.12.4
vscodeintellicode|Vis|1.2.2
vim|vsc|1.12.4
quokka-vscode|Wal|1.0.268
vscode-ruby|win|0.26.0
codesandbox|yes|0.0.8
material-theme|zhu|3.2.1

(10 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
What version of the TypeScript are you using? It should be shown in the lower left hand corner of your screen when a TS file is open.

/needsMoreInfo

**Comment by Jayphen** [comment]
3.7.3. It's shown there in the error.

**Comment by mjbvz** [comment]
Duplicate of microsoft/TypeScript#35372  (#88088)
