### ISSUE TITLE
Ability to hide/show VSCode Exception area

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#88217]
In Visual Studio when an exception happens the IDE shows a popup with the exception details that the user can dismiss and take action. In VSCode the exception also appears but there is no way to dismiss the message/notification to take further action the error being intrusive.

**The request: a way to have the exception notification dismissed after inspection**

Below is an example on the situation, an "X" to close the red area and a red exclamation icon/marker on the left side gutter near to the line numbers to review the notification  would be one solution suggestion. 

![image](https://user-images.githubusercontent.com/37976898/71910755-2fbee700-317b-11ea-8979-66e6a2545bc4.png)

**Comment by weinand** [comment]
@isidorn this request makes a lot of sense to me.

**Comment by isidorn** [comment]
I have added a X button to the top right corner. Also clicking `ESC` will close the exception widget.
To get the exception widget back again -> a user needs to click on the call stack to again. Or to close the editor and open the same file again. Which I think is not a bad experience.
Anyways try it out and let me know what you think

fyi @connor4312 

![Screenshot 2020-11-10 at 19 12 42](https://user-images.githubusercontent.com/1926584/98714254-f6ea3280-2388-11eb-9fba-1c304223c665.png)

**Comment by connor4312** [comment]
Seems intuitive 🙂
