### ISSUE TITLE
git refresh is not working, either auto or manual

### ISSUE THREAD

**Issue by WaveF** [microsoft/vscode#88214]
Issue Type: <b>Bug</b>

In source control, git refresh is not working, either auto or manual. I have to enter 'git pull' in terminal to update my local files, but it can commit and push my changes, only PULL not working.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (5.93GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
LiveServer|rit|5.6.1
material-theme|zhu|3.2.1

</details>

**Comment by connor4312** [comment]
Git refresh only reads the remote so that you can see if there are any changes made upstream, it doesn't affect your current file. Does running the `Git: Pull` command, from the command palette or source control view, work for you?
