### ISSUE TITLE
Menu bar rendering not correct with ipython feature.

### ISSUE THREAD

**Issue by cangyin** [microsoft/vscode#88216]
Issue Type: <b>Bug</b>

(This issue is forwarded here by suggestion, from [issue 9379 of ms-python extension](https://github.com/microsoft/vscode-python/issues/9379))
1. open an empty folder, create an 'python jupyter note book' and open it.
2. (as shown in GIF below)
![demo](https://user-images.githubusercontent.com/50256182/71726005-b7051580-2e70-11ea-865e-94478e90e492.gif)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (6.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
python|ms-|2019.11.50794
cpptools|ms-|0.26.2
java|red|0.55.1
vscode-hexdump|sle|1.7.2
cmake|twx|0.0.17
vscode-lldb|vad|1.4.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
