### ISSUE TITLE
Keyboard layout change causes missrecognition of shortcuts command in macOS

### ISSUE THREAD

**Issue by Paalon** [microsoft/vscode#88218]
Shortcuts for [indent / outdent lines (⌘\] / ⌘\[)](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf) don't work on my macOS.
I encountered similar bug behavior in Atom 1.36.0 but it works in Atom 1.35.0 and I reported in https://github.com/atom/atom/issues/19968.
I don't know how related this to Atom's issue, but at least the behavior exists in VSCode.
I haven't checked but I think the detailed behavior is same in https://github.com/atom/atom/issues/19968. 

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. On physical JIS keyboarded mac, change keyboard type from SystemPreference > Keyboard to US layout.
2. Use VSCode.
3. Shortcuts for Indent / outdent lines (⌘] / ⌘[) (and perhaps other keyboard layout related shortcuts) don't function correctly.

Does this issue occur when all extensions are disabled?: haven't cheked

**Comment by connor4312** [comment]
Can you follow these troubleshooting steps? https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-mac-keybindings

/needsMoreInfo
