### ISSUE TITLE
Typo in Node.js debugger

### ISSUE THREAD

**Issue by mathare** [microsoft/vscode#88221]
Issue Type: <b>Bug</b>

When running a Node.js file under debug there is a typo in the help text that appears:
"To futher configure Debug and Run create a launch.json file"
should be:
"To further configure..."

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Fixed in latest vscode insiders. Thanks for reporting though!
