### ISSUE TITLE
Consider using a different grammar for shell script (messed syntax highlight with shell script)

### ISSUE THREAD

**Issue by efolch** [microsoft/vscode#88226]
Issue Type: <b>Bug</b>

Syntax highlight gets messed when using the word "function" followed by a space in command substitution (ex: capturing stdout from an external program into a var)

Example of messed syntax hightlight:
```
#!/usr/bin/env bash
var_highlighting_works="string"
also_works_if_value_is_a_command=$(ls)
this_works_too="$(ls function)"
but_this_fails="$(ls function | oops | syntax hilight is broken)"
# everything looks like a qoted string here, though this is a proper comment
this_is_an_uncolorized_var="$(ls)"
echo commands look like quoted strings too but vars are colorized $but_this_fails
# and a line with a single double-quote (though wrong in terms of script)
# will make syntax highlighting even weirder 
echo wtf"
# now comments and commands are highlighted, but not vars
echo 1 2>/dev/null
# comment
another_var_uncolorized="something"
```

Workaround: trucate the command substitution into many lines:
```
#!/usr/bin/env bash
var_highlighting_works="string"
also_works_if_value_is_a_command=$(ls)
this_works_too="$(ls function)"
quoting_function_works="$(ls function \
							| true
							| works_fine)"
# now comment, commands and vars are properly colorized
echo commands
var="something $var"
```

Also as a hint for the bug, quoting the work function also works as a workaround.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.57204
shell-launcher|Tyr|0.4.0

</details>

**Comment by alexr00** [comment]
Moved to owning repo

**Comment by efolch** [comment]
Can we reopen this? The upstream bug was closed because this problem does not appear in Atom, hence it's VSCode only

**Comment by alexr00** [comment]
VS Code doesn't maintain the grammar's it uses, instead getting them from the community. If there is a better maintained shell script textmate grammar I'm happy to look into switching away from https://github.com/atom/language-shellscript/

**Comment by efolch** [comment]
Honest question because I'm a bit lost here. Atom said they don't maintain the grammar because they don't use that textmate version anymore, but tree-sitter. Instead of looking for a textmate grammar replacement, couldn't VSCode switch to the tree-sitter instead?

**Comment by alexr00** [comment]
Switching to tree-sitter is a non-trivial change (https://github.com/microsoft/vscode/issues/50140), and we do have many good community supported textmate grammars. You can see our roadmap of what we want to do to see what we're using our time for : https://github.com/microsoft/vscode/wiki/Roadmap

**Comment by efolch** [comment]
Ok, I see. No prob, the bug has an easy workaround and I can live with it.
Thank you.
