### ISSUE TITLE
VSCode keeps on removing / overwriting activeBorder in settings.json

### ISSUE THREAD

**Issue by antoinecfmws** [microsoft/vscode#88224]
Hello,

I check-in the settings.json file into git for dev reasons. VSCode keeps on modifying / overwriting the activeBorder setting in settings.json. It's minor, but thought I'd mention it. 
![image](https://user-images.githubusercontent.com/41809103/71916631-5f0a2f80-314c-11ea-8581-3d5f1f6830d6.png)

Thank you!

**Comment by connor4312** [comment]
Can you provide reproduction steps?

/needsMoreInfo

**Comment by antoinecfmws** [comment]
I am not sure as to what causes this to happen, i.e. I can't provide reproduction steps as I can't tell when vscode decides to overwrite that particular property.
