### ISSUE TITLE
VSCode icon has black background in Windows 10 timeline

### ISSUE THREAD

**Issue by msekmfb** [microsoft/vscode#88228]
Visual Studio Code icon has black background in Windows 10 timeline

- VSCode Version: 1.41.1 (user setup), also present in VSCode Insider 1.42.0 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Check if timeline is enabled
2. Edit a file using VSCode
3. Open Windows 10 timeline

![timeline](https://user-images.githubusercontent.com/59621052/71920155-365b5780-3197-11ea-934a-3ff2a827f14f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Unable to confirm this for Insiders

![image](https://user-images.githubusercontent.com/1312662/71929697-e2567000-31a2-11ea-8b50-7096ff998fee.png)

VS Code version: Code - Insiders 1.42.0-insider (629a08ed6231d7af269ae61a5cc610490d1f7f5d, 2020-01-07T05:28:24.258Z)
OS version: Windows_NT x64 10.0.**19536**

**Comment by msekmfb** [comment]
> Unable to confirm this for Insiders
> 
> ![image](https://user-images.githubusercontent.com/1312662/71929697-e2567000-31a2-11ea-8b50-7096ff998fee.png)
> 
> VS Code version: Code - Insiders 1.42.0-insider ([629a08e](https://github.com/microsoft/vscode/commit/629a08ed6231d7af269ae61a5cc610490d1f7f5d), 2020-01-07T05:28:24.258Z)
> OS version: Windows_NT x64 10.0.**19536**

This is Task View, not Timeline
![taskview-timeline](https://user-images.githubusercontent.com/59621052/71970241-57648c80-3219-11ea-9aaf-e53afd2c4b5c.png)


> /duplicate #49096

It isn't, this issue is about icon, not timeline support generally

**Comment by IllusionMH** [comment]
Yes, you are correct.
Looks like Timeline uses Start tile background and VSCode has fixes dark background to avoid problem described in #58893

Similar behavior for PowerPoint
![image](https://user-images.githubusercontent.com/1312662/71973805-96461280-3218-11ea-9908-5fc5ae2e27aa.png)
