### ISSUE TITLE
VSCode File\Open dialog needs an "address bar" to open file by absolute filename

### ISSUE THREAD

**Issue by mipnw** [microsoft/vscode#88220]
On MacOS with VSCode 1.41.1 there does not seem to be a way to open a file by full filename. 

File\Open ```(⌘O)``` opens a dialog. That dialog allows us to manually browse a filesystem to a specific file and open it in the current window. That dialog does not seem to be of help when one already has the full filename in the clipboard, ready to paste in an address bar. When the path is long it is labor intensive to paste the full filename somewhere, read it by chunks, only to take the corresponding navigation steps in the dialog, iterate to another chunk of the file path, until one reaches the desired file.

The file that needs to be opened may not be part of the project currently loaded in VSCode. A common scenario is to open a file outside that project to read something quickly, perhaps copy an endpoint URL, a certificate value, some workspace settings we liked in another project, or even a snippet of code, to be pasted shortly thereafter in the current project. As such this is really a File Open issue, rather than a code browsing by symbol or reference issue.

Also opening a terminal ```(CTRL-`)``` only to type ```code [filename]``` isn't an option when one isn't interested in opening a second window of VSCode with that file loaded into it, one just wants to open that file in the current window, just like if they had navigated to that file in the File\Open (⌘O) dialog.

**Comment by connor4312** [comment]
The open dialog is provided by the OS, we don't have control over it. Opening a file by absolute path is a good extension candidate.
