### ISSUE TITLE
Settings file saves trigger sync on macOS but not Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88235]
Repro:

Windows machine:

1. Open settings json file
2. Add a setting
3. Save

Mac machine:

1. Open settings json file, notice the new setting does not show up

Windows machine:

1. ctrl+tab twice to force a sync

Mac machine:

1. ctrl+tab twice to force a sync, notice the setting shows up now

Swapping windows and mac above works fine, mac seems to sync just fine on save where windows does not.

Version: 1.42.0-insider (user setup)
Commit: 629a08ed6231d7af269ae61a5cc610490d1f7f5d
Date: 2020-01-07T05:28:24.258Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

Same commit on mac.

**Comment by sandy081** [comment]
I suspect `fileService` is not triggering change event. Will investigate when I am back on my windows VM.

@Tyriar Meanwhile can you please check if the event is getting triggered here on shared process?
https://github.com/microsoft/vscode/blob/master/src/vs/platform/userDataSync/common/settingsSync.ts#L58

**Comment by Tyriar** [comment]
I'm not seeing any settings.json file events fire when I save it in the renderer trace log. I do see it fire for `globalStorage` and `.lastSyncSettings.json` though.

**Comment by sandy081** [comment]
I think you should look in shared process log.

**Comment by Tyriar** [comment]
Oh yes, that's the log I was looking at. I saw settings sync logs when I focused the file

**Comment by sandy081** [comment]
Closing this as no one has seen this during testing.

@Tyriar Please verify if you are still seeing this.

**Comment by Tyriar** [comment]
Haven't seen it since I created the issue.
