### ISSUE TITLE
Hex color values involving capital letters are changed to RGB when using the Color Picker.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [microsoft/vscode#88231]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new tab and paste in this:

```css
div {
    background-color: #1F1F1F;
}
```

2. Open the command palette and run `Change Language Mode`. Select `CSS` as the language.

3. Hover over the color picker and note that the value is interpreted as RGB.

4. Use the color picker to change the color. Note that the original hex has now been replaced with RGB.

This isn't really a big deal—it's more of an annoyance whenever an external color picker gives me a hex value with all caps. Demo:

![demo](https://user-images.githubusercontent.com/19352442/71923395-f1b1cb00-315a-11ea-99dd-79d1d8456469.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
**Verification:**
- Create a new CSS file and add the following class
  ```
  div {
      background-color: #1F1F1F;
  }
  ```
- Hover over the color and open the color picker
- Confirm that the title of the color picker shows "#1f1f1f"
