### ISSUE TITLE
Feature Request: Command-Semicolon

### ISSUE THREAD

**Issue by danieldespainTLS** [microsoft/vscode#88239]
I love that you can press Command-Enter anywhere on the line to add a new line and go to it.  Saves me from getting the cursor to the end of the line just to hit enter.

I think it would be great if you could do the same thing for adding a semicolon to the end of the line no matter where the cursor is.  You could press Command-Semicolon, and it would place a ";" at the end of the line, add a new line under the current one, and place the cursor at the beginning of the new line.

Same thing as Command-Enter, but with adding a ";" to the end of the line you're on.

**Comment by connor4312** [comment]
This is a good suggestion for an extension!
