### ISSUE TITLE
ConfigurationResolverService should support cancelationTokens

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#88248]
Hello there 👋 

In the [Python extension for VS Code](https://github.com/microsoft/vscode-python/) we are implementing an attach-to-local process debugging scenario using a `QuickPick` item (https://github.com/microsoft/vscode-python/issues/8701), however clicking the stop button before selecting a process doesn't dismiss the picker (despite `ignoreFocusOut` being at its default `false` value):

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51720070/71935878-cd56ee00-315c-11ea-8bd9-ad92a539376d.gif)

The session is being dismissed after the `resolveDebugConfiguration` call but before the `createDebugAdapterDescriptor` one, so the `debugService.onDidStartDebugSession` and `debugService.onDidTerminateDebugSession` events are not being fired.

Is there an event the extension can listen to or API it could register to in order to dismiss the picker when debugging is cancelled early?

Thank you 😊

Note: The picker is dismissed correctly when pressing the escape key or clicking anywhere else in the editor.

**Comment by weinand** [comment]
Is your QuickPick triggered from the `resolveDebugConfiguration` hook or is it triggered as part of a (command) variable substitution?

**Comment by kimadeline** [comment]
Yup, the QuickPick is triggered as part of the command variable substitution.

**Comment by weinand** [comment]
@isidorn is there a way to cancel the Quickpick (or any other UI command) either 
- automatically (behind the scenes) or
- manually, by passing a CancellationToken into the UI command?

**Comment by isidorn** [comment]
Extensions can also close the quick picks which they created, so in this particular case Python can not hide the quick pick.
Idealy the configurationResovlerService would introduce support for cancelationTokens.
And the debugService would simply pass an already existing cancelationToken.

I am open and can review a PR which fixes this.
Code pointer for configuration resovler service https://github.com/microsoft/vscode/blob/3ddf7a874a11993e2fb74f9f35dd7dae2d8984c8/src/vs/workbench/services/configurationResolver/browser/configurationResolverService.ts#L26

Code pointer for debug service calling into configuratoin resovler service
https://github.com/microsoft/vscode/blob/3ddf7a874a11993e2fb74f9f35dd7dae2d8984c8/src/vs/workbench/contrib/debug/browser/debugService.ts#L671

**Comment by isidorn** [comment]
I do not think this will happen in June, pushing out to On-Deck.
If there are enthusiasts feel free to assign back.

**Comment by weinand** [comment]
After investigating this, I found that it does not help if the `ConfigurationResolverService` propagates a `CancellationToken`. The reason is that commands implemented in an extension have no access to a `CancellationToken` and are not cancellable. 

As an alternative I've tried @isidorn's suggestion to hide the QuickPick myself. This doesn't work either because the extension API doesn't provide an event for "Debugging stopped" and the `vscode.debug.onDidTerminateDebugSession` does not help because there is no debug session yet...

@isidorn any other ideas how to tackle this?

**Comment by isidorn** [comment]
@weinand thanks for trying it out. Yes, I see the issue that the commands in general are not cancelable and there is no way for vscode to tell the extension "Stop executing the command".

I also see the other issue, that we are in a state where the debug session is not yet fully started and stopping it does not send out an event.

To take another approach: I suggest we solve this by solving this https://github.com/microsoft/vscode/issues/84228
Thus we would not show the debug toolbar, and the user would not be able to do this so prominently.

If you like that approach let me know and I can assign that issue to August so I investigate more.

**Comment by weinand** [comment]
@isidorn great suggestion,
I like that and will close this issue as a duplicate.

/duplicate #84228

**Comment by isidorn** [comment]
Great, let ma assign #84228 to August then..

**Comment by weinand** [comment]
@kimadeline your issue has been fixed now: stopping the debug session will dismiss QuickPicks.

**Comment by kimadeline** [comment]
Thank you for the fix and heads up!
