### ISSUE TITLE
Intellisense does not work on newly created JS files until VSCode is restarted.

### ISSUE THREAD

**Issue by SGuduru96** [Microsoft/vscode#8824]
- VSCode Version: 1.2.1
- OS Version: OS X El Capitan 10.11.5

Steps to Reproduce:

1. Open VSCode
2. open new window
3. Create a new JS file
4. Create a few variables in that file ex: var name = "bob"; 
5. Use CMD-SHIFT-O (no symbols show up for me)
6. Try typing some commands such as console.log, notice that the regular autocomplete window does  
     not come up.
7. Quit VSCode
8. Reopen VSCode
9. Reopen previous file
10. Autocomplete now works, and symbols show up (intellisense works)

**This does not happen when creating a new file through the command line interface**

**Comment by dbaeumer** [comment]
@SGuduru96: in step 3.) do you save the file or is it a temporary file.

**Comment by SGuduru96** [comment]
@dbaeumer Yes, in step 3 I save the file as a .js file.

**Comment by SGuduru96** [comment]
I've updated to version 1.3.0 and the issue has disappeared for me since!

**Comment by dbaeumer** [comment]
Great. I will close the issue. Please ping if you see it again.
