### ISSUE TITLE
Name "TunnelInformation.environmentTunnels" type

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88244]
It would be useful to have a name for the type of this property:

```
environmentTunnels?: { remoteAddress: { port: number, host: string }, localAddress: string }[];
```

so that I can refer to it without copy/pasting or having to say `TunnelInformation['environmentTunnels'][number]`

I don't have a suggestion for a name :)

It is mostly the same as the `Tunnel` type so maybe they could share a base type with an extending interface that adds dispose()

**Comment by alexr00** [comment]
It is now a `TunnelDescription`. Name might change after next API discussion, but I think it's solid enough.
