### ISSUE TITLE
Search box should upper layer of crash dialog

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#88246]
As the title, look at top right, the search box disappear.
![vscodeSearchboxlayer](https://user-images.githubusercontent.com/24865815/71936761-61827e80-3178-11ea-87b6-9e145d0826e1.gif)

Version : 1.41.1 (user setup)
Validation : 26076a4de974ead31f97692a0d32f90d735645c0
Date : 2019-12-18T14:58:56.166Z
Électron : 6.1.5
Chrome : 76.0.3809.146
Node.js : 12.4.0
V8 : 7.6.303.31-electron.0
OS : Windows_NT x64 10.0.18363

**Comment by rebornix** [comment]
I didn't reproduce this issue on Stable, Insiders and master. @djmisterjon could you provide more info about how to reproduce or confirm if you can see the same issue with Insiders?

**Comment by djmisterjon** [comment]
@rebornix  sure, here for you a fast 1min video to replicate the bug behavior.
I also make you a demo here step in video 
https://youtu.be/_ko_GpGFn9A
---
- Create new folder where you want
- Open with vscode
- instal demo with terminal `git clone https://github.com/djmisterjon/pixi-nwjs-starter.git .`
- npm i with terminal
- than look video

**Comment by rebornix** [comment]
@djmisterjon thanks! It helps a lot.

**Comment by arijun** [comment]
I can confirm is happens, and it can be pretty confusing the first time. I hit forward on my search and it disappeared behind the error dialogue, and ctrl-f couldn't bring it up again.

This also happens with preview definition popups.

**Comment by rebornix** [comment]
No longer reproducible anymore.
