### ISSUE TITLE
Suggestion: Sync: Sync Now command

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#88249]
Right now (per # https://github.com/microsoft/vscode/issues/85210#issuecomment-560428825) a sync happens when a new windows is opened, a windows is focused, or the settings/keybindings/extensions views are opened.  These are goodness, but sometimes I want to just force it to happen instead of clicking around or waiting.

Suggest to have a command `Sync: Sync Now` to force the sync.  

Here's the scenario, let's say that i've made changes to my settings/extensions and then I want to get them onto a second machine.  In this case, its a laptop and i'm on my way to the airport, so I am in a rush. I have to click around until a sync happens, and in some cases it won't be obvious that the sync happened (e.g. one setting of 100 changed), so i have to click around to ensure the changes were made.    

With a `Sync Now` command I could force it and be sure it happened before I close the laptop.

**Comment by bpasero** [comment]
Why are we not syncing when settings change? I would not expect anything else than that to keep the state in sync.

**Comment by weinand** [comment]
But for the receiving side a "Sync Now" would still make sense since there is no setting change on that side, right?

**Comment by bpasero** [comment]
I think the receiving side is fine with a combination of:
* pull in on startup
* pull in once window gains focus
* pull in every N minutes

**Comment by sandy081** [comment]
I agree with @bpasero that Sync should just happen. 

IMO the moment this action is required is not very often. So, I would wait to receive more feedback.

**Comment by Tyriar** [comment]
To give users piece of mind, let's add a Sync Now command that shows up here:

![image](https://user-images.githubusercontent.com/2193314/80545196-9dc82d80-8967-11ea-8601-b6e96e1e5cd0.png)

Maybe just below Show Log and move the last synced message to it?

**Comment by sandy081** [comment]
Ok 👍
