### ISSUE TITLE
VSCode does not preserve original virtual desktop placement when restoring windows (Windows, macOS)

### ISSUE THREAD

**Issue by cdmihai** [microsoft/vscode#88257]
Issue Type: <b>Bug</b>

Repro:
1. Create multiple virtual desktops
2. Open a vscode instance in each virtual desktop
3. Update vscode such that it restarts

Expected: All reloaded instances after the restart are placed in their original virtual desktop
Actual: All reloaded instances are placed in the current virtual desktop

This is quite annoying as I have multiple repos opened in multiple virtual desktops. After each vscode restart I have to waste a minute or two figuring out which virtual desktop to move each vscode instance to

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (9.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.48
dscript|Bui|0.1.38015
githistory|don|0.4.13
xml|Dot|2.5.0
vscode-archiver|ecm|0.0.27
EditorConfig|Edi|0.14.4
graphviz-preview|EFa|1.3.3
gc-excelviewer|Gra|2.1.32
buildxlscript|Mic|0.1.0-devBuild
remote-wsl|ms-|0.41.7
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
dot|Ste|0.0.1
spellchecker|swy|1.2.13
zip-file-system|Tom|1.0.0
markdown-all-in-one|yzh|2.6.1
vscode-proto3|zxh|0.4.0

</details>

**Comment by bpasero** [comment]
A couple of related issues here: https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aworkbench-os-integration+virtual+is%3Aclosed

We need Electron API to support this. I encourage you to ask for this API in https://github.com/electron/electron/issues so that we can link back the issue here. 

Bottom line: as far as I know when opening a window in Electron I can only give it a size and position but I cannot restore virtual desktops, nor find out about them. If someone has ideas, please speak up.

**Comment by cdmihai** [comment]
It seems such an issue already exists: https://github.com/electron/electron/issues/5362
