### ISSUE TITLE
Problems with the @ alias when developing vue.js projects

### ISSUE THREAD

**Issue by heiyehk** [microsoft/vscode#88258]
- VSCode Version: 1.41.1(user setup)
- OS Version: Windows 10

Steps to Reproduce:

1.When I use the alias @ in the vue.js project, it points by default to the first project in the vs code work bar, so it is reported incorrectly.
2. Items are not affected unless they are in the first column.

Does this issue occur when all extensions are disabled?: Yes/No
![image](https://user-images.githubusercontent.com/33891067/71948359-ba9af280-320a-11ea-8b92-ca1630cf1ae3.png)

**Comment by connor4312** [comment]
Can you share your tsconfig?

/needsMoreInfo

**Comment by heiyehk** [comment]
> Can you share your tsconfig?
> 
> /needsMoreInfo

``` json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

```
