### ISSUE TITLE
Support relative file only links in terminal (no folder)

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode#88259]
I am using a dotnet web project in vscode. I have some build error so when I run dotnet build, it's showing me some error. 

I click on file and it doesn't open the file that is relative to the directory I have opened in my vs code.

**Comment by anirugu** [comment]
@connor4312  Here is the scenario 


You installed VS code and installed the dotnet core and get started to program dotnet core app in VS code.

Now you create a project and open it in vs code. Normally how a developer does normally.
Now for testing change something in C# to make a broken code.

Now try to compile using powershell (integrated) in vs code. Now it will show you HomeController.cs have blah blah error.

Now when you click on the file name like HomeController in this case, sadly it doesn't open the file. I does this on windows machine.

So what someone opened is root of the project, In this case Controller/Homecontroller.cs
VS Code the relative path to the file. it must open the file when someone click on HomeController in Powershell integrated panel.

Note :- I am doing dotnet build from inside the terminal provided in VS Code.

**Comment by connor4312** [comment]
This is the build output on my case on an Ubuntu VM. You're referring to `Program.cs` not being linkified?

```
connor@connor-lubuntu-vm:~/Github/HelloCS$ dotnet run
Program.cs(9,46): error CS1002: ; expected [/home/connor/Github/HelloCS/HelloCS.csproj]

The build failed. Fix the build errors and run again.
```

I can repro but I don't think this is something we'd likely recognize in VS Code with false positives elsewhere.

**Comment by anirugu** [comment]
Few days ago when I tried this it's showing the (Powershell integrated) in terminal inside my vscode. I tried to click on that and it's not working.  that's the issue.

I tried again and in all 3 and it's look working. Not sure what is breaking that time. Is there a way to check that powershell integrated thing in VS code. in those case it's not working.

**Comment by Tyriar** [comment]
@anirugu please share OS/version and VS Code version

**Comment by anirugu** [comment]
I reset my windows last weekend. I have the stable version latest. When I was using it's showing some "Powershell Integrated"  in terminal.

Can it happen because of some plugin.  my user directory in C is intact as it is. I can see all my plugin get reinstalled after I installed the VS code in refresh window.

**Comment by Tyriar** [comment]
@anirugu open cmd.exe and run `ver` to get the exact Windows build number please.

**Comment by anirugu** [comment]
Microsoft Windows [Version 10.0.18363.535]

**Comment by Tyriar** [comment]
What I suspect is happening is the file in question is getting output without any path separators which until https://github.com/microsoft/vscode/issues/21125 won't work.

For example these type of paths should work:

```
src\Program.cs(1,2)
.\Program.cs(1,2)
..\Program.cs(1,2)
```

But this should not:

```
Program.cs(1,2)
```

Note also that the working directory that the terminal starts in is what all link are relative to on Windows as it's impossible to extract the cwd of a particular shell.

To verify this, could you show a screenshot of the terminal in the problem state to see the exact file?

**Comment by anirugu** [comment]
I have reset my windows machine last week. I will reproduce this and let you know

**Comment by Konradox** [comment]
Microsoft Windows [Version 10.0.19041.153]
Powershell: 5.1.19041.1
VS Code: 1.43.2 (system setup)
VS Code Insider: 1.44.0-insider (system setup)
I can't click on links in the terminal: 
- relative,
- absolute,
I can click web URL

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/21125
