### ISSUE TITLE
Wrong keyboard layout when starting VSCode on startup

### ISSUE THREAD

**Issue by lodi-g** [microsoft/vscode#88269]
- VSCode Version: 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, x64)
- OS Version: Linux laptop 5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64 GNU/Linux

Steps to Reproduce:

1. Start VSCode at the startup of the computer (in the startup file of the WM),
2. Wrong keyboard layout!

Does this issue occur when all extensions are disabled?: Yes

---

This is related to #31899, I also have an AZERTY keyboard. If I close and re-open VSCode it works fine.

**Comment by alexdima** [comment]
I believe that we read the keyboard layout and then the keyboard layout is changed during startup. I suggest we continue tracking in #23690
