### ISSUE TITLE
Left pane spills outside VSCode window

### ISSUE THREAD

**Issue by amanmittal25** [microsoft/vscode#88267]
When you open VS Code, observe that left pane which shows explorer, search, source control etc spills outside the VSCode window, there is an extra 1-2px white line which shows up. The issue is more prominent in multi-screen monitors. where you can see white line an the left monitor

**Comment by IllusionMH** [comment]
Hard to tell without screenshots and other details required by issue template.

Looks related to #85592 and #85655
