### ISSUE TITLE
downloading on Mac

### ISSUE THREAD

**Issue by maltit14** [microsoft/vscode#88260]
I can't download VScode on Mac because apple can't check for "malicious software". Can that be fixed do I can download?
![VSCode error while downloading](https://user-images.githubusercontent.com/59634972/71948960-ac0af780-3186-11ea-88d2-4998b2bbdf06.png)

**Comment by l2dy** [comment]
See https://github.com/microsoft/vscode/issues/74782#issuecomment-567353275.
