### ISSUE TITLE
do not autoclose quotes when in strings 

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#88265]
VSC 1.41.1 .

it doesn't detect the open/close state

![](https://lh3.googleusercontent.com/Vakm7V5k8QeHxh4CVszGOMlP4EdKqNIaK4SQ9-B5X9skAhLvv3ku6ZhHSI3-Gl60ZThxD3mMKI8i1Bl5utZNshk_JYdTSDEttNlroL6fKQBy3pRfBYqe6aOAZUYQGrXBa6yBhP2Z2GrUPsVK9-N9KTRAIyNv0SkaOLjA7d6aupNeXVJoDCp0o6GCJsOXugJuZXfsUPqcxeWYW4Uu4z2q8uTL1Y7JpgjvtwDSqOCP9wEIHGr41DFw1uFxGmkPOB__Q1_nM_bNxEG8rEWAJW8c0PUeNSGfFxoAhEJuDb8fA0RG_7l-7FxkdNcPJ6yU9TKL9mPFQ31BhyZKuWJOsCjMLQ0dtf92rJOOSZwCVdBziKhTuDy96I67hUr_yX1NHfzFZ14IYdBYjPnOyKayQmNuAifI1bv1I6QbJ9DMDDwIT_RrT9kZYsiEITsEd_rPzFec7jOzAZvmNWCWUvoaA2UnooaJQhRowRSNExbEDzHrZWOgPeu-ihTXvNRJLExxzC1hIrOvDV_sw39xx0meVGpUXmSnBNfWQymCgWrHqlNmQMz4yZXr63i4TvIxYv8-NDElGyt-g4ep8XZrkPPvfSnINDoeUsEevuRUkYz8iTu1bV_oRzj_ydZApee4VxotLYHkNw1JNndefNa8a9DFWWw3oiurCmbx9FlDKv9PY0OJQCMkCrrkBWaLG_Y6Zf4icD6MmcsfPBS7zT9x1-y4hu9ePONqEflavCLPkPAPt-ulQQlui_o=w530-h246-no)

( even if the function work with {syntax code ranges}/Regions, this is still the part of Autoclosing, so it seems that should create own Regions, which won't affect the code ones( Syntax Highlighting) )

**Comment by connor4312** [comment]
It looks like you have an unclosed quote on the first line. If you fix that, does it work?

/needsMoreInfo

**Comment by irvnriir** [comment]
@connor4312 , its same when i try to place 3 ` " ` by one, at open space (all 3 times they get doubled)

**Comment by connor4312** [comment]
What's the language mode for the opened file? It doesn't look like there's any syntax highlighting, is it getting set correctly?

**Comment by irvnriir** [comment]
@irvnriir , Batch, working (plain theme)

**Comment by connor4312** [comment]
Okay, can you share the contents of the source file from your screenshot so we can try to reproduce it?

**Comment by irvnriir** [comment]
@connor4312 .
![](https://lh3.googleusercontent.com/f3woG_fSxckST8a-V52KrqZ7msh7LcvAq2nwz32wyIXehIOqPtsnZkpt-NUzIa5nfDjaepBGNIPaMO_vZqdRvfMsH-4GpwE9fhKm0TOHP8AXbT61YBI2RUI9tuJv03JsVRcDwIUDAhXE9PvilhfdsY0DzTLPcRByzjfLg9wOM5QsiwDniQcc1PjFg9rpyoFmV7g0PI4oaGbbLLvtyFTwTLZSa0Nv8KzY9Qe_uNBo2rWEkxclM9D96xgHoyZulItOonQZBc7RADU9smL-CKxyVAojKmJRyejLUdwB3QQbJj5fbRpZ-GtMc6JSpN9SyU9sfnrgCD_2rmQIguoO9ioxwlU2BNqFIo6ex0hfDAEKRn16kydJABlR4ivKRG26k_7ZURRv4wmt6ipf-dCnguk6Mk0-FJTtKwSwc__st6Jub7q4yZRhV6IR7p2dIfMMOvOjYDH6HG614y4xnwM63q2zlb7I87nJFX5jWd3Sr-I-YkRDjc3kHH1ZBZjq5wZnF0hF5A4L06yVUAcPYAco8VQlfLs4IM7qBjIxUBut-ezn8uWCpoJCCgt-JUA4z9o-MNdrU11dhyvy6-MwjBr_x0xPTNgiDIwMa3W4PrZnjpao-25xhRZZuNqjBuDYLjYp2jeg2gS1GTJWKkLQ5MPYLkqfqPMetXTYKJdk38_yLmhz5o-WRc33prB8JwCIoi-gWBpMLxX221E65qHB2kjOgt9dPFiIxOzx_rGpE0lIxuviuA1qXYo=w260-h44-no)

**Comment by connor4312** [comment]
Thanks, that's useful!

**Comment by irvnriir** [comment]
bat\\surroundingPairs also doesn't work

**Comment by aeschli** [comment]
Good catch!
Can you file a separate issue for the `surroundingPairs` issue? Please add a code sample (pasted as text, if possible)

**Comment by irvnriir** [comment]
@aeschli , is there a command, other than "notIn" (blacklist), to specify the whitelist of Scopes?
