### ISSUE TITLE
Settings Sync: provide a description about UI State

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#88274]
Not every user will understand what synching 'UI state' means. I suggest to add a description that explains it using an example.

![image](https://user-images.githubusercontent.com/172399/71970023-1c0d9200-3208-11ea-9a85-a2390489d3ec.png)

**Comment by sandy081** [comment]
I would add only display language as it is only synched now.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/10746682/72063630-6b23f780-32da-11ea-8de4-2ed9d20f0559.png">

**Comment by Tyriar** [comment]
@sandy081 now it feels awkward that it says a description, will this eventually be something like "Display language, something else, ..."?

**Comment by sandy081** [comment]
I do not know what it is going to be eventually and what other state we will include.
