### ISSUE TITLE
heightlight error

### ISSUE THREAD

**Issue by poycc** [microsoft/vscode#88279]
<img width="671" alt="WX20200108-194240@2x" src="https://user-images.githubusercontent.com/24654957/71975590-50587100-324f-11ea-8b51-d05fe2cf573d.png">

A number of such incorrect highlighting problems occurred

**Comment by connor4312** [comment]
Does this issue reproduce with all extensions disabled?

/needsMoreInfo

**Comment by poycc** [comment]
> <img alt="WX20200108-194240@2x" width="671" src="https://user-images.githubusercontent.com/24654957/71975590-50587100-324f-11ea-8b51-d05fe2cf573d.png">
> 
> A number of such incorrect highlighting problems occurred
