### ISSUE TITLE
Include process.arch in about dialog

### ISSUE THREAD

**Issue by StefanMoore** [microsoft/vscode#88277]
Issue Type: <b>Feature Request</b>

In the About VS Code section, include a way to tell what version you are using. Either 32-bit or 64-bit. I can't remember what version I installed. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:59:13.638Z)
OS version: Windows_NT ia32 10.0.18363

**Comment by IllusionMH** [comment]
In the meantime you can try `process.arch` in DevTools.

**Comment by gjsjohnmurray** [comment]
Doesn't that "ia32" indicate you're on 32-bit Windows? In that case you'll have to be running 32-bit VSCode, right?

**Comment by Unc3nZureD** [comment]
@gjsjohnmurray Doesn't that just indicate the OS version?

**Comment by bpasero** [comment]
@StefanMoore running "code --version" from the command line will give you this information.

**Comment by StefanMoore** [comment]
Also, this is my first posting on Github  since I've joined. So, take it easy on me until I can become as good as you guys. I thank all for comments and suggestions.

@gjsjohnmurray - I'm running Win 10 Pro. So I'm not to sure what the ia32 means

@bpasero - I'll try that when I get in tonightand post and update to see what version of VS Code I'm running.

**Comment by gjsjohnmurray** [comment]
@StefanMoore AFAIK if your Windows 10 Pro was 64-bit that string would be "x64".

**Comment by StefanMoore** [comment]
@gjsjohnmurray if that where the case, I wouldn't be able to install 64-bit Python or a 64-bit version of Office 2019. This is why I am inquiring to see what version of VS Code I have

**Comment by StefanMoore** [comment]
The version I have running on my laptop is 32-bit. When I compared that to the version that's on my desktop it's 64-bit. I thank all for their help on this.

**Comment by gjsjohnmurray** [comment]
@StefanMoore thanks for the update. This seems to align with what @bpasero reported about the part played by the NodeJS version. I conclude that 'ia34' in the Windows version part of About means the 32-bit VSCode is what's running.
