### ISSUE TITLE
Keyboard shortcuts not working on macOS catalina

### ISSUE THREAD

**Issue by kunal-batra** [microsoft/vscode#88278]
Issue Type: <b>Performance Issue</b>

"Shift+Option+F" shortcut not working for macOS catalina.
"Option+Z" shortcut working but its also typing a special character simultaneously.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.63GB free)|
|Process Argv|-psn_0_61455|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   21	    98	   495	code main
    0	   115	   624	   gpu-process
    0	   311	   667	   window (OperatorSearchLanding.js — fc-mobile)
    0	    66	   722	     extensionHost
    0	    49	   734	       electron_node tsserver.js 
    0	   262	   736	       electron_node tsserver.js 
    0	    49	   749	         electron_node typingsInstaller.js typesMap.js 
    0	    33	   839	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=722
    0	    33	   750	     watcherService
    0	     0	  1639	     /bin/bash -l
    0	    33	  1662	       npm
    0	    16	  1663	         node /Users/kunal.batra/Desktop/fc-mobile/node_modules/.bin/cross-env NODE_ENV=development PORT=3001 API_TARGET=prod node server.js
    0	   393	  1664	           node server.js
    0	    49	 26437	     searchService
    0	    82	   746	   shared-process
    0	     0	 29439	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	 29144	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (OperatorSearchLanding.js — fc-mobile)
|    Folder (fc-mobile): 915 files
|      File types: js(303) png(122) json(72) jsx(49) scss(44) snap(35) map(33)
|                  svg(10) eot(4) ttf(4)
|      Conf files: jsconfig.json(1) package.json(1) webpack.config.js(1);
```

</details>
Extensions: none
(3 theme extensions excluded)

**Comment by connor4312** [comment]
What keyboard layout are you using? Can you follow these troubleshooting steps? https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-mac-keybindings

/needsMoreInfo
