### ISSUE TITLE
provide API vscode.env.openItem

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#88273]
openExternal doesn't work when file path contains non-ascii chars.
reference issues: https://github.com/electron/electron/issues/6302

I'm working with my extension [open-in-external-app](https://github.com/tjx666/open-in-external-app), but I found that the following code doesn't work when the filePath contains non-ascii chars.

```javascript
vscode.env.openExternal(vscode.Uri.file(filePath));
```
for example: `vscode.env.openExternal(vscode.Uri.file('C:/测试.md'));`
It works well when filePath only includes ascii chars. Is there any methods to fix it, or provide the API vscode.env.openItem as electron?

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/85930
