### ISSUE TITLE
[Regression of #9448] Lowercase drive letter in Windows integrated terminal

### ISSUE THREAD

**Issue by olee** [microsoft/vscode#88272]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open folder in vscode in Windows (eg. C:\dev\test)
2. Open any subfolder in integrated terminal by right-clicking in the tree view (eg. C:\dev\test\subfolder)
Result: The terminal will open with the lowercase drive letter in `c:\dev\test\subfolder`

Does this issue occur when all extensions are disabled?: Yes

This seems to be a regression of #9448

**Comment by Mistermasque** [comment]
I have exactly the same problem with git client on :
-     VSCode Version: 1.46.1
-     OS Version: Windows 10

Steps to Reproduce:
1. clone a git repository on a specific folder (ex : C:\Users\E10770\Documents\Programmation\gic\dep_GIC-CENTRE) using gitBash
2. Open git repository using vscode
3. add a file using vscode version control
4. 

I have this error message in OUTPUT Git : 
```
git add -A -- c:\Users\E10770\Documents\Programmation\gic\dep_GIC-CENTRE\src\Import\AbstractGlobaAdlImportProcess.php
fatal: c:\Users\E10770\Documents\Programmation\gic\dep_GIC-CENTRE\src\Import\AbstractGlobaAdlImportProcess.php: 'c:\Users\E10770\Documents\Programmation\gic\dep_GIC-CENTRE\src\Import\AbstractGlobaAdlImportProcess.php' is outside repository

```
The "C" drive letter is in lowercase.

**Comment by rzhao271** [comment]
@Mistermasque your issue seems to be fixed in the related issue.

@olee I can't reproduce the issue on the latest Insiders (1.51).
My prompt looks like this after following the steps:

```Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\raymondzhao\notebook-extension-samples\notebook-provider> 
```

Are you using a different shell?

**Comment by olee** [comment]
I was using cmd, but I think it does not happen for me anymore as well.
Therefore I will close this issue, thank you.
