### ISSUE TITLE
Jump to last selection (during multiselect)

### ISSUE THREAD

**Issue by richie3366** [microsoft/vscode#88275]
It might be handy to have a shortcut allowing to go back to single-cursor mode on the last selection positions.

Like what the [Escape] button does, but instead of going to the first selection, it would go to the last one. The default key combination would be something like [Ctrl]+[Escape].

**Comment by jakub-g** [comment]
+1, I virtually always want to keep the cursor in the last position, not the first position when pressing `Esc`.
A toggle in settings would be another option (instead of different keybinding)

**Comment by rioj7** [comment]
With extension [Select By](https://marketplace.visualstudio.com/items?itemName=rioj7.select-by) v1.3.1 and the command `moveby.calculation` you can calculate the new location of the cursor. By using the collapse feature of VSC you are left with 1 cursor.

Define this keybinding

```
  {
    "key": "ctrl+i escape",
    "when": "editorTextFocus",
    "command": "moveby.calculation",
    "args": {
      "lineNrEx": "selections[selections.length-1].start.line",
      "charNrEx": "selections[selections.length-1].start.character"
    }
  }
```

**Comment by jakub-g** [comment]
Awesome, thx @rioj7!
