### ISSUE TITLE
Surface IExtHostTerminalService.getDefaultShellArgs()

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#88280]
The IExtHostTerminalService has a method `getDefaultShell(...)` but it lacks the corresponding method `getDefaultShellArgs(...)`.

This makes it rather difficult to use `createTerminalFromOptions(...)`. See:
https://github.com/microsoft/vscode/blob/de3922b5b4507690e72fd47f1db147b18dc3a0d5/src/vs/workbench/api/node/extHostDebugService.ts#L89-L104

**Comment by Tyriar** [comment]
@weinand I'll make this change, after it's done please mark as verified if it's all good.
