### ISSUE TITLE
Parse error when using interpolation in an at-rule (scss)

### ISSUE THREAD

**Issue by lucpotage** [microsoft/vscode#88283]
- VSCode Version: 1.41.1
- OS Version: macOS 10.15.1

Related: https://github.com/microsoft/vscode-css-languageservice/issues/157

Steps to Reproduce:

1. I write an at-rule in a Sass file with an interpolation as a value.

```
$val: '(display: grid)';
div {
  @supports #{$val} {
    display: grid;
  }
}
```

2. I get the error: `( expectedscss(css-lparentexpected)`.

![Capture d’écran 2020-01-08 à 13 05 50](https://user-images.githubusercontent.com/7230764/71977457-208e7680-3219-11ea-9f6e-9a4ee883fe83.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The given snippet is no valid scss. There's a rule missing. Is that the example?
```
.foo {
  @supports (display: grid) {
    @media screen and (max-width: 400px) {
        column-gap: 0.5rem;
    }
  }
}
```
That's a dup of https://github.com/microsoft/vscode-css-languageservice/issues/152.
I just pushed a fix...

**Comment by aeschli** [comment]
Sorry, commented on the wrong issue.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-css-languageservice/commit/91e26f14404b1ef75405abc907c6e4245787aa85
