### ISSUE TITLE
when saving a file, windows process continuous increase

### ISSUE THREAD

**Issue by wangxiaoyuwangdayu** [microsoft/vscode#88286]
when saving a file (ctrl + s), a python.exe process and a conhost.exe process will be added to windows process, they dont occupy cpu, bu occupy memory.
although i close the vocode , the process dont end.

**Comment by connor4312** [comment]
Does this problem reproduce when all extensions are disabled?

/needsMoreInfo

**Comment by wangxiaoyuwangdayu** [comment]
> Does this problem reproduce when all extensions are disabled?
> 
> /needsMoreInfo

thank you, i disable the python extensions and it works,
