### ISSUE TITLE
Add toggle to show only breakpoints for current file

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#88289]
Issue Type: <b>Feature Request</b>

Often I find I will only be interested in the breakpoints in the current file I am working in, and therefore only said breakpoints shown in the Breakpoints dropdown. Currently breakpoints in other files are also listed in the Breakpoints dropdown, therefore are just creating clutter. It also appears that breakpoints are even listed that are in non-open files of the same work folder. Essentially you get every breakpoint.

A simple toggle in the Breakpoints dropdown next to the other 3 current buttons (add/deactivate/remove breakpoints) would make this dropdown a whole lot more usable: "Show only active file breakpoints" or something similar. If you have multiple files open and switch between them then the Breakpoints list should update accordingly with this toggle enabled.

Also maybe have again another toggle for only showing breakpoints of all open files. More functionality :)

You'd also need to account for people who have multiple files open where the files are displayed side by side. In this case I'm not sure if the other files that aren't window-focused would be considered "active" or just open and how that would affect the only active/open breakpoint toggled list.

I hope this helps!

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog candidates nad we might add this in the future. Thanks

**Comment by ariffjeff** [comment]
Fair enough :)
