### ISSUE TITLE
Sidebar search steals keyboard focus

### ISSUE THREAD

**Issue by ergl** [microsoft/vscode#88282]
Sometimes, the sidebar search input, the extension marketplace search input, and the editor steal focus from each other, in ways I can't always reproduce.

- VS Code version: Code - Insiders 1.42.0-insider (cba31b819ea99836daf51cee56299348e9c6d20b, 2020-01-08T05:35:29.477Z)
- OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>

Steps to Reproduce:

I wasn't able to reproduce this 100% of the time: sometimes, it's the editor window stealing focus from the sidebar inputs. Other times, it's the sidebar search input stealing focus from the editor. The extension marketplace search also steals focus from the editor from time to time.

I was able to reproduce the text editor stealing focus from the extension marketplace search:

1. Start VSCode with the sidebar open.
2. Create new file.
3. Collapse the sidebar.
4. Type something in the file.
5. Toggle the sidebar, and switch to the extension marketplace.
6. Hide the sidebar and immediately toggle it again.
7. Now the focus should be in the text editor, instead of in the extension marketplace search. Even clicking the search input won't work.
8. If you now click on the Search section of the sidebar, you will see all the text you typed in the search bar.

I've also attached a gif of the issue below.

Does this issue occur when all extensions are disabled?: Yes

<details><summary>Gif</summary>

![](https://www.dropbox.com/s/mul3764tejsipho/vscode-focus-steal.gif?raw=1)

</details>

**Comment by roblourens** [comment]
Weird! You are using the keyboard shortcut to show the sidebar right?

**Comment by ergl** [comment]
Yes, I'm using ⌘-B to open and close the sidebar. I haven't tried reproducing this with the Extension Marketplace shortcut or by opening and closing the sidebar using the mouse.

**Comment by maslade** [comment]
I experience this often when interacting with git (no git-related extensions installed). For example - if I use the sidebar to perform a commit, and quickly tab over to my terminal (using a keyboard shortcut for `workbench.action.terminal.focus`), the sidebar regains focus and my keystrokes become sidebar searches. It seems like it might be (in my case) that after the git commit succeeds, the sidebar is getting focused automatically.

**Comment by roblourens** [comment]
Wrong issue... that was https://github.com/microsoft/vscode/issues/95497

**Comment by roblourens** [comment]
Sorry, I have no idea what might be going on. Unless @rebornix has some idea. Can only hope that it has been fixed by some other change in the past 8 months.
