### ISSUE TITLE
Regex Replace does not allow to use expression

### ISSUE THREAD

**Issue by Kivayan** [microsoft/vscode#88285]
While using search an replace in regex mode I am no able to use expressions like convert to Lowercase (\L). '\L' is inserted literally
![xB7MCS3VxT](https://user-images.githubusercontent.com/26223593/71981532-df9b5f80-3222-11ea-826f-95abe3dbdf5a.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/12185
