### ISSUE TITLE
ability to delete terminal command line content (e.g. ctrl-U) from extension

### ISSUE THREAD

**Issue by tansaku** [microsoft/vscode#88288]
Is there any way to send ctrl-sequence commands to the terminal from vscode extensions?

I'd like to send ctrl-U to remove anything that might be hanging around before sending other commands.

I guess I could just send a newline char, but that would run anything the user had left on the command prompt ... in the ideal world one could use the `sendText` command to execute something on the terminal command line after saving any partially typed text there, and then replacing it after the desired command had been run ... (ctrl=K, `sendText('blah')`, ctrl-Y maybe)

**Comment by connor4312** [comment]
You should be able to use `Terminal.sendText` to send a control sequence, including ctrl+u.

**Comment by tansaku** [comment]
thanks @connor4312 I guess I'm stuck on what sequence of characters would do this, e.g.

sendText('crtl-U') // surely not
sendText('\u0003') // maybe?

**Comment by tansaku** [comment]
yes can be done with sendText('\u0003')
