### ISSUE TITLE
Git Extension: Commit interface should provide date and author name

### ISSUE THREAD

**Issue by ole1986** [microsoft/vscode#88294]
It would be very useful to have commit date, author name, ... in the `Commit` interface when calling `getCommit([...])`

Something similar to this:

```ts
export interface Commit {
    readonly hash: string;
    readonly message: string;
    readonly parents: string[];
    readonly commitDate?: Date;
    readonly authorEmail?: string | undefined;
    readonly authorName?: string | undefined;

}
```

**Comment by joaomoreno** [comment]
@ole1986 What exactly more do you require?

**Comment by ole1986** [comment]
Commit date and author name as already mentioned in the interface definition

**Comment by joaomoreno** [comment]
Cool, wanna contribute a PR?

**Comment by ole1986** [comment]
@joaomoreno I really would want to but do not know when I can arrange a PR due to less time unfortunately..

**Comment by almoghaimo** [comment]
I'd be interested in grabbing this issue.

**Comment by Prithviraj001** [comment]
I'm interested in this issue too, Did u start working on that @almoghaimo  ?

**Comment by ANEgorova** [comment]
Hey, @almoghaimo, @Prithviraj001! Sorry, I already started to work on it too and almost ready (will prepare PR tmr I think)

**Comment by almoghaimo** [comment]
OK I did worked on it too but I wasn't sure how to test it, how did you test it? only by the test commands?
