### ISSUE TITLE
Git Branch options dropdown does not close

### ISSUE THREAD

**Issue by Prateek93a** [microsoft/vscode#88297]
- VSCode Version:1.35.1
- OS Version:Linux x64 5.0.0-37-generic

Steps to Reproduce:

1.Click on option showing current branch at the bottom left corner of the screen.
2.Dropdown modal open up showing different branches to checkout to.
3.Try to close the dropdown by clicking somewhere else. Nothing happens.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
First please update to the current release, 1.41.1

**Comment by connor4312** [comment]
Yep, that version is about 6 months behind, let us know if it repos on recent versions.

/needsMoreInfo

**Comment by Prateek93a** [comment]
I updated to 1.41.1 version and the issue is fixed in that. Thanks @gjsjohnmurray  and @connor4312 .
