### ISSUE TITLE
launch.json prompt Add configuration button anywhere

### ISSUE THREAD

**Issue by rudywaltz** [microsoft/vscode#88292]
Issue Type: <b>Bug</b>

If I create a file (anywhere in my codebase) what is named launch.json they add special `Add Configuration...` button to the bottom.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7287U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 17, 33|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|-psn_0_237626|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.3
clipboard-history|Anj|1.0.7
svelte-intellisense|ard|0.7.1
lit-html|bie|1.11.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.12
gitlens|eam|10.2.0
vsc-material-theme|Equ|31.9.0
prettier-vscode|esb|3.18.0
vscode-svelte-snippets|fiv|0.3.0
vscode-pull-request-github|Git|0.14.0
beautify|Hoo|1.5.0
svelte-vscode|Jam|0.9.3
asciidoctor-vscode|joa|2.7.7
dotenv|mik|1.0.1
vscode-docker|ms-|0.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1404
printcode|nob|3.0.0
material-icon-theme|PKi|3.9.2
language-stylus|sys|1.11.0
quokka-vscode|Wal|1.0.271
literally-html|web|0.1.2
local-history|xyz|1.7.0

(1 theme extensions excluded)

</details>

<img width="552" alt="Screenshot 2020-01-08 16 31 50" src="https://user-images.githubusercontent.com/395555/71990858-6f95d500-3234-11ea-9219-d33fa767c435.png">

**Comment by connor4312** [comment]
Would it be appropriate to only tread launch.json's as "special" if we see they're inside a `.vscode` folder?

**Comment by isidorn** [comment]
@connor4312 thanks for the suggestion, I took that approach.
@rudywaltz you can try it out from tomorrow's vscode insiders and let me know how it goes. Thanks

**Comment by rudywaltz** [comment]
Dear @isidorn ,
sorry for the delay, I tested in `Insiders` and work perfectly. Thank you for the quick fix.

Happy Coding,
David

**Comment by isidorn** [comment]
Thanks for letting us know, adding verified label :)
