### ISSUE TITLE
Run task integrated terminal does not recognize PATH environmental variables (mac)

### ISSUE THREAD

**Issue by humansthatmake** [microsoft/vscode#88290]
Here I tried to run `make` as a task:
![Screenshot 2020-01-07 at 21 31 07](https://user-images.githubusercontent.com/10792249/71931466-b680bd80-3195-11ea-8869-ac0d46c75310.png)

Here I tried to run `make` in a different integrated terminal session:
![Screenshot 2020-01-07 at 21 37 49](https://user-images.githubusercontent.com/10792249/71931601-fa73c280-3195-11ea-85c6-7e2c76ccf3ca.png)

And the operation was successful. It was able to find the path and run.

It seems like when I run a task the new terminal session is stripped out of any user configurations and starts running a factory version of the terminal. 

VSCode: 1.41.1
macOS 10.14.6

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "includePath": [
                "${workspaceRoot}/main/**",
                "${workspaceRoot}/build/include/",
                "${env:IDF_PATH}/components/**"
            ],
            
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "~/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
settings.json
```
{
    "C_Cpp.updateChannel": "Insiders",
    "workbench.editor.highlightModifiedTabs": true,
    "editor.acceptSuggestionOnEnter": "off",
    "files.trimFinalNewlines": true,
    "terminal.integrated.env.osx": 
    {
        "PATH": "$HOME/esp/xtensa-esp32-elf/bin:$PATH"
    }
}
```

**Comment by alexr00** [comment]
Tasks run with `<shell> -c` which runs the command in your task in a non-login, non-interactive shell (so no profile or rc). However, we do try to get your environment from the environment the VS Code has. 
Can you check what your `PATH` is for VS Code by opening the Developer Tools and running `console.log(process.env)` in the console?

**Comment by humansthatmake** [comment]
PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin"

**Comment by alexr00** [comment]
That looks ok. Can you try running this task and share the output:
```
        {
            "label": "Path task",
            "type": "shell",
            "command": "echo $PATH"
        }
```

**Comment by humansthatmake** [comment]
This was the output:
<pre>
> Executing task: echo $PATH <

$HOME/esp/xtensa-esp32-elf/bin:$PATH
</pre>

**Comment by alexr00** [comment]
That's your problem. At that point the path should be expanded; however, because you're using `$HOME` and `$PATH` and  in `terminal.integrated.env.osx` they aren't expanding. This is in intentional, as VS Code's way of referencing variables is `${env:path}`, so your setting should be
```
    "terminal.integrated.env.osx": 
    {
        "PATH": "${env:HOME}/esp/xtensa-esp32-elf/bin:${env:PATH}"
    }
```

**Comment by humansthatmake** [comment]
thank you @alexr00. works like a charm!

**Comment by larsoleruben** [comment]
I suddenly have the exact same problem on macOS version 10.15.3 (19D76).
Until now it has been working perfectly. Suddenly it can't build .net core before debugging?
Paths as you showed it:/bin:/usr/bin:/usr/ucb:/usr/local/bin
Abd by path in the shell (zsh):/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/lars/.dotnet/tools
How can this be intentional? Suddenly I need a settings.json, which I did not need before?
