### ISSUE TITLE
Code lens overlapping text

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#88299]
Issue Type: <b>Bug</b>

I'm starting to see this again in today's insiders
![image](https://user-images.githubusercontent.com/641685/72006950-ab25a480-321e-11ea-9fa5-4d7f4e7d486b.png)

I will note, that I had this file open in 2 editors -- and 1 had the overlapping and the other didn't.

/cc @jrieken 

VS Code version: Code - Insiders 1.42.0-insider (cba31b819ea99836daf51cee56299348e9c6d20b, 2020-01-08T05:39:25.874Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (14.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Weird - no recent changes in that area... @eamodio When this happens, can do an inspect element, find the lens and try to find its content widget

**Comment by jrieken** [comment]
@eamodio Could this be related to folding? Are you using that by any chance?

**Comment by eamodio** [comment]
@jrieken I don't think it is folding related -- folding is on (I don't have it disabled or anything) but I wasn't folding anything. I've seen it again now in a peek view, but I accidentally closed it before I could inspect.

**Comment by eamodio** [comment]
@jrieken happened again -- no peek or duplicated editor this time:
![image](https://user-images.githubusercontent.com/641685/72849259-4cc3e180-3c74-11ea-8071-c37a5a5afc09.png)

**Comment by jrieken** [comment]
Let's see if this reproduces after the fix for https://github.com/microsoft/vscode/issues/89028 is deloyed
