### ISSUE TITLE
ansible snippets not working.

### ISSUE THREAD

**Issue by astha243** [microsoft/vscode#88300]
Issue Type: <b>Bug</b>

i use a mac and have the latest sotware downloaded but my visual studio code isnt working as per, the snippets doesn't work neither does the ansible local terminal. please help

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|53, 25, 10|
|Memory (System)|8.00GB (3.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ansible|haa|0.2.8
vscode-yaml|red|0.6.1
ansible-autocomplete|tim|0.0.2
vscode-ansible|vsc|0.5.2

</details>

**Comment by connor4312** [comment]
Can you provide reproduction steps and details around the issues you're facing?

/needsMoreInfo
