### ISSUE TITLE
Cannot close extension editor if extension is not in the marketplace

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8830]
Presumably the same if I don't have internet connection?

![hddiiofd4l](https://cloud.githubusercontent.com/assets/5047891/16649591/45759f46-4442-11e6-9300-8ed23f3c8c47.gif)

**Comment by joaomoreno** [comment]
Nasty, but I'd suggest to not fix it for June since:

- low impact: need an custom extension that is not in the workbench. should happen only to extension side loading
- no data loss
- workaround: restart the workbench

What do you think @alexandrudima @egamma @jrieken (endgame master)?

**Comment by jrieken** [comment]
adding `candidate` label for discussion

**Comment by jrieken** [comment]
Removing candidate tag after discussion

**Comment by joaomoreno** [comment]
Repro:

- Have an extension that lacks a `README` file.
