### ISSUE TITLE
Opening custom FileSystemProvider Uri loses Remote context

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode#88301]
Steps to Reproduce:

1. Open up a VS Code remote environment (I tested on SSH, should repro on WSL too)
1. Install the [MemFS sample extension](https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample) in that remote environment
1. Run "Setup Workspace"
![Screen Shot 2020-01-08 at 10 40 11 AM](https://user-images.githubusercontent.com/11282622/72007362-5b3ae380-3206-11ea-8e20-4ef1e022105b.png)

Expected:
It opens the MemFS workspace, still in the context of the SSH Remote. Obviously the files themselves will be coming from MemFS, but other pieces (settings, extensions installed, default terminal, etc.) should still be in the context of the SSH remote.

Actual:
It throws this error:
![Screen Shot 2020-01-08 at 10 40 01 AM](https://user-images.githubusercontent.com/11282622/72007442-858ca100-3206-11ea-9963-27786bbf46b0.png)

NOTE: If I use `vscode.commands.executeCommand('vscode.openFolder', uri)` instead of `vscode.workspace.updateWorkspaceFolders`, it won't throw an error, but the context is back to my local VS Code.

Version: 1.42.0-insider
Commit: cba31b819ea99836daf51cee56299348e9c6d20b
Date: 2020-01-08T05:35:29.477Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by jrieken** [comment]
to my knowledge that's designed like this. only folders of the same (remote) scheme are allowed

**Comment by EricJizbaMSFT** [comment]
I'm guessing the original design focused on entire remote extensions as opposed to _just_ a `FileSystemProvider`. Also I want to emphasize we care more about opening up a single folder workspace as opposed to a multi-root workspace with different schemes.

I think the biggest problem is the extensions installed in the remote environment. @fiveisprime originally discovered this problem for us because he primarily uses VS Code in a WSL environment. He only had our extension (Azure Storage) installed in WSL. When he tried to open up our custom FS provider link, it opened a window in the non-WSL environment which didn't even have the Azure Storage extension installed (as mentioned in the NOTE above, this is the behavior when we use the `vscode.openFolder` command as opposed to `updateWorkspaceFolders` which throws an error).

**Comment by alexdima** [comment]
This check was introduced via https://github.com/microsoft/vscode/commit/0e6822b2cf52d06a6abb80adf3aefc22563731e9 by @isidorn . I don't know the exact rationale behind it.

**Comment by isidorn** [comment]
Correct, I have introduced that check to enforce that only folders of the same scheme are allowed.
I believe we have this restriction because explorer and other parts of our UI are not fit to handle operations for files with different schemas. For example drag and drop from a folder with one scheme to another.

**Comment by EricJizbaMSFT** [comment]
I feel like I should've been more clear here. We don't care that much about the multi-root scenario. There are two ways to open a folder that I'm aware of:
```
vscode.workspace.updateWorkspaceFolders
```

```
vscode.commands.executeCommand('vscode.openFolder', uri)
```

The second method is always a single root workspace and also doesn't work (As described in the NOTE in the original issue). If we can get that working - I think we'd be okay with the error for a multi-root workspace.

**Comment by alexdima** [comment]
fyi @bpasero @aeschli

**Comment by bpasero** [comment]
@isidorn 

> I believe we have this restriction because explorer and other parts of our UI are not fit to handle operations for files with different schemas. For example drag and drop from a folder with one scheme to another.

I am not sure I follow: the file service is able to perform all of its operations from any scheme to any other scheme. So it should work fine for DND.

I think however that we do not want to allow for mixing local folders and `vscode-remote` folders because you can only ever be in remote context or local context. So we probably need to relax this strict rule to only cover that?

**Comment by isidorn** [comment]
I believe we have remove that check and this should hopefully work now
