### ISSUE TITLE
Blank part webview

### ISSUE THREAD

**Issue by yedane** [microsoft/vscode#88316]
- VSCode Version:1.41.1
- OS Version: Win 10 1803

Steps to Reproduce:

1.
![2020-01-09_00-17-14](https://user-images.githubusercontent.com/8882331/72024762-70e7f180-3276-11ea-9a58-3fcfe0917282.png)

2. When using bulma css in my webview, it look like that there is blank part in the webview that can't be selected by the developers tool. 

Does this issue occur when all extensions are disabled?: No

**Comment by connor4312** [comment]
This is default behavior of web pages, "html" isn't full height unless styled as such or the content is larger than the window.
