### ISSUE TITLE
Report updateGraph performance Telemetry from the TypeScript server

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#88313]
We suspect that updateGraph in the typescript server may be causing perceived slowdowns. However we don't have any data to prove or disprove this hypothesis. We also don't know what the currently baseline of `updateGraph` is.

To fix this, https://github.com/microsoft/TypeScript/pull/35675 introduces a new metadata property to TypeScript that tracks how long `updateGraph` takes. This change tracks having VS Code upload this performance telemetry

/cc @amcasey

**Comment by mjbvz** [comment]
@amcasey With the fix, we create a telemetry event for every TS response that includes `updateGraphDurationMs`. We upload both `updateGraphDurationMs` and the command name. Does that sound good?

**Comment by amcasey** [comment]
@mjbvz VS is just adding a property to the existing event for the operation (e.g. completion).  If that's a bad fit for your model, please make sure there's at least a way to correlate it with the operation telemetry event.

p.s.  I've added a couple notes to the commit.  I'm not sure if you were notified.

**Comment by mjbvz** [comment]
Yeah we can do that instead. Whatever would be easiest to work with when we are trying to analyze the data

**Comment by mjbvz** [comment]
Thanks for the feedback. Pushed fc65a7c41b844b194ba25403ec1d07025bb1ada6 with fixes

**Comment by mjbvz** [comment]
Marking this as verified based debugging though the code with typescript@next. It is difficult to verify extension telemetry externally until we update the telemetry registry
