### ISSUE TITLE
Extension icon not showing in side bar after installation

### ISSUE THREAD

**Issue by luisjotapepe** [microsoft/vscode#88312]
Side bar missing icon after installting from vsix file. This extension is one not available in the marketplace. Currently being developed in-house.

It worked for VSCode version 1.39, 1.40

- VSCode Version: 1.41
- OS Version: MAcOS 10.15

Steps to Reproduce:

1. Install extension from vsix file
2. Upon installation the icon wont be showing on the side bar
3. Re-starting VSCode will display it

![Screen Shot 2020-01-08 at 3 50 39 PM](https://user-images.githubusercontent.com/1677063/72022903-cd272300-322e-11ea-9c70-fbc17538dcd8.png)

**Comment by connor4312** [comment]
Which extension are you trying to install?

/needsMoreInfo

**Comment by luisjotapepe** [comment]
@connor4312 I’ve updated the description. This is an in-house extension currently in development.

**Comment by connor4312** [comment]
Can you share its `contributes` section from the package.json--or better yet a repo containing the extension, if possible?

**Comment by luisjotapepe** [comment]
Here is the `contributes` section from package.json
[contributes.txt](https://github.com/microsoft/vscode/files/4037913/contributes.txt)

Unfortunately, we do not have a public repo to share. Let me know if there is anything else I can help with.

**Comment by lcampos** [comment]
@connor4312 we were seeing this behavior for the Salesforce extensions on yesterday's insiders version. It is now working as expected with the latest insiders release (1.42.0-insider
Commit: cba31b819ea99836daf51cee56299348e9c6d20b).

**Comment by connor4312** [comment]
@luisjotapepe can you verify whether the latest insiders also fixes your issue?

**Comment by luisjotapepe** [comment]
@connor4312 I’ve just tested with today’s Insiders version and works well. 

Will this be fixed for 1.41 still though?

**Comment by connor4312** [comment]
@sandy081 is this a recovery candidate?

**Comment by sandy081** [comment]
I do not think this will be considered as recovery.

Closing this as it works.

**Comment by luisjotapepe** [comment]
@sandy081 may I ask what’s recovery?

**Comment by sandy081** [comment]
I do not see it is affected while installing normally otherwise we would have seen too many issues.
