### ISSUE TITLE
Settings UI doesn't update textboxes when settings change via sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88320]
@rebornix saw this

Repro:

Box 1:

1. Open settings UI, find font family

Box 2: 

1. Change font family

Box 1:

1. Trigger a sync (ctrl+tab, ctrl+tab)
2. Notice the font family doesn't change

**Comment by roblourens** [comment]
I can also repro this just by editing the json and UI side by side, editing the json, and seeing that the UI doesn't update. But this works in stable, so some event is not being fired from the configuration service, @sandy081

**Comment by sandy081** [comment]
@roblourens It is working for me on Mac. On which platform are you on?

**Comment by rebornix** [comment]
@sandy81 I saw this on macOS.

**Comment by roblourens** [comment]
I'll look into it and give you more specific details

**Comment by sandy081** [comment]
Its working for me. See the attached gif. I have Web insiders on left and Insiders on right and the settings editor is getting updated after sync

![Kapture 2020-01-09 at 12 08 29](https://user-images.githubusercontent.com/10746682/72062801-ca810800-32d8-11ea-9f89-7887bd47f8eb.gif)

**Comment by Tyriar** [comment]
That's what I saw on @rebornix's machine, maybe it didn't sync yet or something? 🤔

**Comment by roblourens** [comment]
Today I can't repro the issue I was seeing.

**Comment by rebornix** [comment]
I can confirm that this is no longer reproducible on my machine.
