### ISSUE TITLE
Make it easier to define platform-specific keybindings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88323]
@rebornix had this idea when recording:

![image](https://user-images.githubusercontent.com/2193314/72028124-49713480-3236-11ea-962a-468253166ba3.png)

As I've mentioned in the past, I think instead of having `"sync.keybindingsPerPlatform": true` be the default, I think we should improve the UI around making platform-specific keybindings instead and flip the default to be `false`. Otherwise it's very cumbersome to sync keybindings across different platforms.

**Comment by eamodio** [comment]
While I don't know about the UI shown above, I definitely agree that there should be a better UI/UX for managing platform-specific keybindings. Especially if there was some default/built-in way to automatically translate common changes (Ctrl<->Cmd) which you can then edit further.

Currently having `"sync.keybindingsPerPlatform": true` be the default with no UI indication of that being the case is really undiscoverable for users.
