### ISSUE TITLE
Revisit the icon for Java files

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode#88329]
We have some users reporting that the icon for Java files needs to be revisited. microsoft/vscode-java-pack#279 microsoft/vscode-java-pack#283

The current icon is like this:
![image](https://user-images.githubusercontent.com/16755094/72033490-70c71080-32cd-11ea-8b8b-1ffe917014b1.png)

Here are some comments regarding the current design:
1.  The current design does not incorporate the common understanding of Java element, e.g. a cup of coffee, which makes it less identifiable
2.  Some user recognizes this icon as a clock, which is misleading
3.  The red color and the dot shape is also misleading because some users consider it an error indicator

So here to request a new design for this file type in the default theme.

**Comment by misolori** [comment]
We use the [Seti UI theme](https://github.com/jesseweed/seti-ui) for our file ions, please file an issue with that repo.
