### ISSUE TITLE
Choosing "Restart Task" on build command causes vscode window to hang

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#88325]
Issue Type: <b>Bug</b>

1) git clone https://github.com/microsoft/vscode-azurearmtools.git
2) cd vscode-azurearmtools
3) npm i
4) code .
5) SHIFT+CTRL+B
6) When build finished, do SHIFT+CTRL+B again and select "restart task"
!) vscode hangs (you'll get the no longer responding message)

Might take a couple of tries

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.78GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
tsco|alj|1.0.15
vscode-browser-preview|auc|0.5.9
azure-arm-template-helper|ed-|0.0.17
rest-client|hum|0.23.0
vscode-antlr4|mik|2.2.3
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
extension-manifest-editor|ms-|0.1.5
mssql|ms-|1.8.0
python|ms-|2020.1.57204
azure-account|ms-|0.8.8
azurecli|ms-|0.4.6
powershell|ms-|2019.12.0
vscode-node-azure-pack|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3
83861|msa|0.0.1
azurerm-vscode-tools|msa|0.8.3
scope-info|sie|0.2.0
tmcolor|sle|0.0.1
html-preview-vscode|tht|0.2.5
arm-params-generator|wil|0.8.1

</details>

**Comment by alexr00** [comment]
This is https://github.com/microsoft/vscode/issues/71966.
