### ISSUE TITLE
Initially synced extensions sync all disabled extensions as enabled: true

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88321]
@rebornix saw this when syncing about 100 extensions for first time, about half of which were disabled. I verified in the DB that all of them are coming through as enabled: true.

Box 1:

- Install and disable some extensions
- Enable sync

Box 2:

- Enable sync, notice all extensions that were meant to be disabled are enabled.

**Comment by sandy081** [comment]
/duplicate

Extension enablement is not considered for syncing yet - #86916
