### ISSUE TITLE
Task providers lists potential tasks from the .vscode-test directory

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#88328]
Issue Type: <b>Bug</b>

**Repo**
1. Create a new VS Code extension that uses `vscode-test`.
1. Run the tests once so that the `.vscode-test` folder is created
1. In VScode, run the `Run Task` command

**Bug**
A bunch of build tasks for code under `.vscode-test` are listed:

![Screen Shot 2020-01-08 at 6 28 23 PM](https://user-images.githubusercontent.com/12821956/72032738-29953d00-3245-11ea-8da1-8047e809e809.png)

VS Code version: Code - Insiders 1.42.0-insider (cba31b819ea99836daf51cee56299348e9c6d20b, 2020-01-08T05:35:29.477Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (1.37GB free)|
|Process Argv|-psn_0_10746431|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
@alexr00 This also effects the `npm` task provider. I think excluding `.vscode-test` is a reasonable default

I'll look into the tsc task provider

**Comment by alexr00** [comment]
Agreed. Nice find.
