### ISSUE TITLE
Missing Node task in Configure Task Runner

### ISSUE THREAD

**Issue by matej-zajacik** [Microsoft/vscode#8832]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create new folder.
1. `code .`.
1. Press build button (`Ctrl + Shift + B` by default).
1. Press Configure Task Runner button.

Result:

- No Node task available.
- It used to be there as a great convenience.

Thank you!

**Comment by dbaeumer** [comment]
@matej-zajacik we never had a special node task. What would you expect as a template?

**Comment by matej-zajacik** [comment]
@dbaeumer I've mistaken it for the 'debug' command (`F5` by default). Must have just spent too much time at work. I am sorry. There is no issue.

**Comment by dbaeumer** [comment]
@matej-zajacik thanks. Closing then.
