### ISSUE TITLE
ProgressLocation.Notification progress incrementing is incorrect

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#88333]
### Env
```
Version: 1.42.0-insider
Commit: cba31b819ea99836daf51cee56299348e9c6d20b
Date: 2020-01-08T05:35:29.477Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

### Steps to Reproduce:

1. check https://github.com/microsoft/vscode-extension-samples/tree/master/progress-sample
> the progress is completed on 50%

2. check [withProgress docs](https://code.visualstudio.com/api/references/vscode-api#window)
> value will be summed up and reflected as overall progress until 100% is reached (a value of e.g. 10 accounts for 10% of work done). 

a correct example of `10% * 10 steps` iteration
```js
return vscode.window.withProgress({
        location: vscode.ProgressLocation.Notification,
        title: msg,
        cancellable: true
    }, async (progress, token) => {
        for (let i = 1; i <= 10; i++) {
            await new Promise((resolve) => {
                setTimeout(() => {
                    progress.report({ increment: (10 * i) / 5 })
                    resolve()
                }, 1000)
            })
        }

        return new Promise((resolve) => {
            resolve()
        })
    })
```

without the `/ 5` 
 - progress will complete in 5 steps
 - notification will remain visible for 10 seconds

**Comment by bpasero** [comment]
@ctf0 I do not follow, this works fine for me:

```ts
export function activate(context: ExtensionContext) {
	context.subscriptions.push(commands.registerCommand('extension.startTask', () => {
		return window.withProgress({
			location: ProgressLocation.Notification,
			title: 'Hello World',
			cancellable: true
		}, async (progress, token) => {
			for (let i = 1; i <= 10; i++) {
				await new Promise((resolve) => {
					setTimeout(() => {
						progress.report({ increment: 10 });
						resolve();
					}, 1000);
				});
			}

			return new Promise((resolve) => {
				resolve();
			});
		});
	}));
}
```

Each iteration, 10% of work is done. What is different?

**Comment by ctf0** [comment]
:scream:  wow, that worked, i dont know why using `10 * i` gave the same result as the sample gif :sob:

i apologize for the inconvenience but it took me about 2hrs or so to get it work correctly, thats why i  opened the ticket.

thanx again for ur help.
