### ISSUE TITLE
how to know VSCODE setup folder in launch.json file?

### ISSUE THREAD

**Issue by 283958849** [microsoft/vscode#88339]
I want to know the folder of vscode setup in launch.json, how? Can we get it ? Thank you so much!

**Comment by 283958849** [comment]
not ${workspaceFolder} or ${workspaceRoot}

**Comment by weinand** [comment]
What do you mean by "vscode setup"?

**Comment by 283958849** [comment]
sorry! I beg your pardon for my poor english.
In fact, I want to know the directory of VSCODE install. For example, I install VSCODE in F:/ide/, and other people install it in E:/ide_path/，I need to get the installation directory in launch.json dynamically，Can we make it? 
thank you so much again weinand!

**Comment by weinand** [comment]
No, this information is not available as a builtin variable. But you can introduce an environment variable for that (outside of VS Code). The environment variable can be accessed in a launch config with the `${env: FOOBAR }` syntax.

**Comment by 283958849** [comment]
Thank you very much for your solution. I will try later and I think it is usful!
Eh, I am working on an IDE development based on VSCODE for my company MCU chip compiling and debugging. I need to put some config files or gdb script files in IDE installation directory, and use these files in launch.json. So I need to know the VSCODE installation directory.

**Comment by weinand** [comment]
Putting config files or gdb script files into the VSCODE installation directory sounds wrong to me.
I suggest to put these files into your extension.

**Comment by 283958849** [comment]
yeah, good idea! Thanks!

**Comment by 283958849** [comment]
Sorry man! One more question, how to get vscode plugin installation directory with source code? Thand you again!
such as: ts.sys.getCurrentDirectory ?

**Comment by 283958849** [comment]
> 
> 
> Putting config files or gdb script files into the VSCODE installation directory sounds wrong to me.
> I suggest to put these files into your extension.

Now, I have put the script file in extensions directory.
For example, the directory after My IDE installed is like this:
D:/MyIDE/
                MinGW/
                PyOCD_Server/
                arm-none-eabi/
                Microsft-vscode/                             (based on vscode 1.40.0)
                extensions/
                                 cortex-debug/                (based on open source extension)
                                 scripts/sdram_init.script

also possible like this:
F:/MyIDE/
                MinGW/
                PyOCD_Server/
                arm-none-eabi/
                Microsft-vscode/                             (based on vscode 1.40.0)
                extensions/
                                 cortex-debug/                (based on open source extension)
                                 scripts/sdram_init.script
I need to get the directory path of cortex-debug extension, and then use the sdram_init.script file.
How can I do that in my extension(cortex-debug) source code with typescript ?

Thank you so much again!!!

**Comment by weinand** [comment]
You can easily find all extension API in `vscode.d.ts`. E.g. searching for "directory" quickly finds this: https://github.com/microsoft/vscode/blob/bc0f81bd0545af1eb0282870a95b0f156811b48e/src/vs/vscode.d.ts#L4986-L4989

The Extension context is passed into your extension's activate function.

**Comment by 283958849** [comment]
"extensionPath" works!! Thank you very much!
