### ISSUE TITLE
Is there anyway to show debug/problems/etc on another monitor?

### ISSUE THREAD

**Issue by rtanzifi** [microsoft/vscode#88347]
Hello.
there are some limitation on coding with this editor on hd/below_hs monitors spacely. So i really like to share the programming environment between multiple displays. So is there anyway to show for instance debug output on another display?
i really look forward into it.
Thanks.

**Comment by gjsjohnmurray** [comment]
Not that I know of. We need #10121 and it is on the road map - https://github.com/microsoft/vscode/wiki/Roadmap#workbench

/duplicate
