### ISSUE TITLE
Slows down my laptop

### ISSUE THREAD

**Issue by milinmestry** [microsoft/vscode#88348]
Issue Type: <b>Performance Issue</b>

From past few days when I open VS code editor for working on my PHP projects, the editor takes too much time to load and hangs my laptop.

Few other application running on the same time is Firefox(71.0) and Docker container

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:30:33.955Z)
OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B940 @ 2.00GHz (2 x 1625)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.80GB (0.13GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    86	 10552	code main
    0	    16	 10556	   zygote
    0	   183	 10596	     window (CheckDatabaseConnectionTest.php - Dinero-Projects (Workspace) - Visual Studio Code)
    0	   105	 10983	       extensionHost
    0	    31	 11107	         electron_node server.js 
    0	   522	 11117	         PHP Language Server
    0	    39	 11030	       watcherService
    0	    31	 11091	       searchService
    2	    62	 11066	     shared-process
    0	     0	 13262	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 13263	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    90	 13241	     window (Issue Reporter)
    0	    74	 10585	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (CheckDatabaseConnectionTest.php - Dinero-Projects (Workspace) - Visual Studio Code)
|    Folder (adplatforms): 11944 files
|      File types: php(8415) json(289) phpt(267) md(228) test(190) xml(175)
|                  txt(120) yml(101) stub(63) gitignore(62)
|      Conf files: makefile(5) package.json(1);
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
theme-karyfoundation-themes|kar|20.0.3
vscode-gutter-preview|kis|0.23.0
gitignore|mic|1.0.1
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.2
laravel-blade|one|1.20.0
vscode-icons|vsc|9.7.0
quokka-vscode|Wal|1.0.271
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by yarivShamash** [comment]
I'm experiencing a similar problem, VSCode gets stuck when I'm working on my React.js project.
When moving around through files copying and pasting and so on the program stops responding and I need to quit it and open it again for it to work propperly.

### system Info:
Ubuntu 18.04.3 LTS,
memory: 7.5 GiB
Processor: intelCore i7-8565 CPU @ 1.80GHz x 8
Graphics: Inter UHD Graphics (Whiskey Lake 3x8 GT2)
GNOME: 3.28.2
OS-type: 64-bit
Disk: 251.0 GB

### VSCode:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-37-generic snap

I don't know how to retrieve the info for the extensions used and all the rest. Would be happy to send if you explain to me how.

This behavior is very disturbing to my work flow and sets back my progress.
Your help is needed!

**Comment by connor4312** [comment]
@yarivShamash that sounds like a different issue, please open one.

@milinmestry please try running with extensions disabled. If you still have issues there, these steps can help you get more info for us to look at: https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by yarivShamash** [comment]
> @yarivShamash that sounds like a different issue, please open one.
Will do :)
