### ISSUE TITLE
Font size in markdown preview

### ISSUE THREAD

**Issue by gagoreli** [microsoft/vscode#88344]
Font size used in the markdown preview is uncontrolable. It is fixed at approximately 10 pixels and can't be changed. This bug appeared only in the last version. Steps to reproduce.

1. Create Markdown file.
1. Open Preview.
1. Open Settings.
1. Enter *font size*.
1. Click **Extensions > Markdown**.
1. Go to the **Workspace** tab.
1. Try to change the value in the **Font Size** box.

**Comment by mjbvz** [comment]
Are you using the `"markdown.preview.fontSize"`setting?

Also /needsMoreInfo

**Comment by gagoreli** [comment]
Hi, Matt!
Yes, I am using "markdown.preview.fontSize"setting.
Yesterday I installed 1.40.2 version back to be able to have markdown preview font size 17 pixels as I like.

Best regards,
German Gorelik.

**Comment by mjbvz** [comment]
The setting works fine for me

Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Do you have custom css you are using the in the preview?

**Comment by gagoreli** [comment]
Hi, Matt!
Thank you for your reply.

Now  I have 1.40.2 version installed. It works fine and I do not want to waste time to find out the reason of the bug in 1.41.1.
When is 1.41.2 ready I will try what you recommend.

Regards,
German Gorelik.

**Comment by mjbvz** [comment]
I'm closing this as not-reproducible then. Works fine for me in insiders with all extensions disabled

**Comment by gagoreli** [comment]
Hi, Matt,

Now it works fine for me too. I’ve just installed the latest version: 1.42.0.
Please note that I had to change nothing in my settings.

Regards,
German Gorelik
