### ISSUE TITLE
npm_modules/vscode/bin/install silently uses github_token causing 404 to be injected to vscode.d.ts

### ISSUE THREAD

**Issue by maxandersen** [Microsoft/vscode#8834]
when you as user have GITHUB_TOKEN with no push access to vscode defined it gets added in request header to fetch vscode.d.ts it will fail fetching.

the file will end up with something like:

```
404: Not Found

export = vscode;
```

as consequence github extensions don't build.

**Comment by chrmarti** [comment]
It would be better to not set the Authorization header at all. That would make it work independently of the GITHUB_TOKEN.

Also: The same code is used for another server that should not learn about the token.

**Comment by egamma** [comment]
@chrmarti if you do not set the GITHUB_TOKEN in the header then you get throttled to 60 API requests per hour by Github. This throtteling is primarily an issue during development and it should not affect users. 

Let's revisit this, but move this out to August.

**Comment by chrmarti** [comment]
Makes sense, I didn't know about the request throttling. Maybe then just make sure the GITHUB_TOKEN is only used for the GitHub URL. I'll open a new issue for that.
