### ISSUE TITLE
Extensions pages cannot show readme files

### ISSUE THREAD

**Issue by narfanar** [microsoft/vscode#88343]
- VSCode Version: 1.42.0
- OS Version: Windows 10 (1909) 64bit

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/5769148/72049984-c1883a80-32c8-11ea-9ef8-9bc3afb17864.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
No able to repro--maybe a temporary outage or glitch in the marketplace?

**Comment by sandy081** [comment]
Me neither

@narfanar Are there any steps to repro?

**Comment by narfanar** [comment]
My ISP's DNS suddenly started not answering for some domains? It's weird. `nslookup` was timing out on `vsassets.io`. Switched to `1.0.0.1` and the extension module works again (finds readme files and can download again), but while I can resolve `vsassets.io` address, pinging it still times out.
