### ISSUE TITLE
Add prompt when saving a file with problem (error, warning)

### ISSUE THREAD

**Issue by rbtreec** [microsoft/vscode#88349]
Currently there is nothing preventing you to save a file with an error in the case you missed it. It would be great to have the option to get a prompt when trying to save a file that contains an error, a warning or even info. In my case I don't want to accidentally save a file with an error before fixing it.

Ideally, the user should decide which level of problem wants to prompt on saving:
- None
- Errors
- Errors and warnings
- Errors, warnings and info ¿? 

(Maybe) This option also disables auto-save for files that contain a problem.
The prompt would show "Cancel" or "Save anyway" buttons.

**Comment by connor4312** [comment]
This is a good extension candidate; you can hook into the `TextDocumentWillSaveEvent` event and provide prompts there 🙂
