### ISSUE TITLE
Auto completion is not working in VS Code.

### ISSUE THREAD

**Issue by mohiyuddinshaikh** [microsoft/vscode#88341]
1. Suggestion works fine when started.
2. When I switch to another tab/window (Alt+tab), and return back to code,Auto suggestion stops working.
3. On force reloading VS code, suggestion works until switched to another window.
4. This is not the case with my smaller projects, only on bigger projects.
5. I am currently working with HTML, CSS, JS, ReactJs
6. i have tried uninstalling and reinstalling vs code that doesn't work either.

**Comment by RoyChina** [comment]
I meet the same problem when I coding for a typescript project. typescript lang server crash much faster than ever before after the latest update.

after I reinstall the old version, it works fine.

**Comment by hanqizheng** [comment]
I met the same problem when I build an brand new project by `ceater-react-app`, and the js code suggestion dosen't work. But the css & html file are totally fine :(

**Comment by hanqizheng** [comment]
> I met the same problem when I build an brand new project by `ceater-react-app`, and the js code suggestion dosen't work. But the css & html file are totally fine :(

And if I wrap this project in a folder(this folder doesn't have any other file), the code suggestion is fine again.

**Comment by LazyDuke** [comment]
I met the same problem justi in some project

**Comment by mohiyuddinshaikh** [comment]
I installed version 1.40.2 and it has solved the issue. Thankyou @RoyChina
