### ISSUE TITLE
Grammatical error in file deletion dialogue.

### ISSUE THREAD

**Issue by diligamer** [microsoft/vscode#88342]
- VSCode Version: 1.41.1
- OS Version: win10 x64 1909

Steps to Reproduce:

1. Create A File Through VS Code
2.  Delete Said File
MAKE SURE TO ADD TEXT AND SAVE BEFORE DELETION

Expected result:
The dialogue box description Should say "You Can Restore This File (these files) from the recycle bin."

Actual Result:
The dialogue box description says "You can restore from the recycle bin."

Does this issue occur when all extensions are disabled?: yes

**Comment by connor4312** [comment]
Can you follow the steps here to get crash logs for us? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows

/needsMoreInfo
