### ISSUE TITLE
I cannot open the terminal in vscode from snap

### ISSUE THREAD

**Issue by lartpang** [microsoft/vscode#88340]
- VSCode Version:
```
版本: 1.41.1
提交: 26076a4de974ead31f97692a0d32f90d735645c0
日期: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-23-generic snap
```
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/26847524/72045783-e93fc880-32f1-11ea-87e6-73a3f535568c.png)

1. From Ubuntu's "Show Applications", I click the icon of VSCode.
2. After VSCode starts: `Terminal` tab -> `New Terminal`.
3. My VSCode becomes like this:

![image](https://user-images.githubusercontent.com/26847524/72046034-7e42c180-32f2-11ea-819a-3eddc5426373.png)

---

**However, when I start vscode from the terminal, everything works fine.**

```
$ code
```

![image](https://user-images.githubusercontent.com/26847524/72046145-c19d3000-32f2-11ea-8602-7a0ca5a3deb0.png)

Does this issue occur when all extensions are disabled?: No

There is no problem using this command.

```
$ code --disable-extensions
```

![image](https://user-images.githubusercontent.com/26847524/72046203-dc6fa480-32f2-11ea-8958-125085e9d3bd.png)

**Comment by connor4312** [comment]
Can you try enabling trace logging for the terminal and uploading those logs? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

/needsMoreInfo

**Comment by lartpang** [comment]
> Can you try enabling trace logging for the terminal and uploading those logs? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
> 
> /needsMoreInfo

Thanks for your reply. But my problem will not reproduce when I open the code from terminal... Only it will occur, when I click it from icon...

**Comment by connor4312** [comment]
@lartpang try this instead:

 1. Open the command palette (ctrl+shift+p by default)
 2. Select `Developer: Set Log Level` > `Trace`
 3. At this point you should reproduce the terminal issue you're having
 4. Run the command "Developer: Open Log File..." (F1 opened command palette) and select Window to get an editor containing the logs

**Comment by lartpang** [comment]
I think these log is about my problem:

```
[2020-01-10 17:10:48.528] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.new
[2020-01-10 17:10:48.532] [renderer1] [trace] terminalInstance#ctor (id: 1) {}
[2020-01-10 17:10:48.680] [renderer1] [error] 发生了系统错误 (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'
[2020-01-10 17:10:52.931] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
```

It is a permission problem... I find this issue: #88036, it fixes my problem: `"terminal.integrated.inheritEnv": false,`, I change it to `"terminal.integrated.inheritEnv": true,`... And then, everything back to normal.

---

Thank you for teaching me to find out what the problem is by looking at the logs inside vscode.

**Comment by lartpang** [comment]
My problem has already been encountered by others, but unfortunately, I haven't found it before: https://github.com/microsoft/vscode/issues/76542#issuecomment-540738847
