### ISSUE TITLE
vscode default github extension changes eol to crlf 

### ISSUE THREAD

**Issue by RishiNiranjan** [microsoft/vscode#88358]
I have an environment where I use centos as a virtual machine in my windows PC.
I use vscode under windows to edit code and centos to do 'make and git'.

So when I discard any file changes using 'discard file changes' option , default git extension changes each EOL to CRLF under file.
Which is why I started getting long file diff when I 'git diff file' under centos.

**Comment by connor4312** [comment]
Do you have an [autocrlf](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code) setting for your git? If so, what's it set to?

/needsMoreInfo
