### ISSUE TITLE
Receiving multiple codeLens requests on startup

### ISSUE THREAD

**Issue by kenkangxgwe** [microsoft/vscode#88353]
Issue Type: <b>Bug</b>

I am developing a language extension but it receives multiple codeLens requests when the server starts up. Whenever the documentText changes, two (or maybe more) requests are sent. Not sure if this is an intended behavior.

If I return `Null` for the first request, and no matter what codeLens I returned for the second one, no codeLens will not be shown.

```
[Trace - 1:13:20 AM] Sending request 'textDocument/codeLens - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/Projects/lsp-wl/repo/src/WolframLanguageServer/Server.wl"
    }
}


[Trace - 1:13:20 AM] Sending request 'textDocument/codeLens - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/Projects/lsp-wl/repo/src/WolframLanguageServer/Server.wl"
    }
}


[Trace - 1:13:20 AM] Sending request 'textDocument/codeLens - (5)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/Projects/lsp-wl/repo/src/WolframLanguageServer/Server.wl"
    }
}
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.83GB free)|
|Process Argv|--folder-uri file:///d%3A/Projects/lsp-wl/repo|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.35.1
ccls|ccl|0.1.28
cquery|cqu|0.1.10
vscode-eslint|dba|2.0.13
tslint|eg2|1.0.44
wolfram-language|fli|0.1.0
base16-generator|gol|1.11.0
lsp-wl-client|lsp|0.1.5
vscode-elixir|mjm|1.1.0
python|ms-|2020.1.57204
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2
vsliveshare|ms-|1.0.1456
lsp-inspector-webview|oct|0.0.2
vscode-elixir-formatter|sam|0.2.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-wl|shi|1.7.3
org-mode|too|0.5.0
cmake|twx|0.0.17
vscode-icons|vsc|9.7.0
vim|vsc|1.12.4
markdown-all-in-one|yzh|2.6.1

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please provide a full repo sample

**Comment by kenkangxgwe** [comment]
client: https://github.com/kenkangxgwe/vscode-lsp-wl
server: https://github.com/kenkangxgwe/lsp-wl/tree/feature/dap-wl
You also need to install wolfram engine: https://www.wolfram.com/engine/

Actually, after I disabled [__Live Share__](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) extension the codeLens went back to normal. Once a time.
So I guess the Live Share duplicates the request, and doesn't show the codeLens if two responses do not match, which is a wired behavior.

Not sure if you have any idea about how Live Share affects the vscode lsp client. Should it change the number of requests and behavior after responces are received?

I am also gonna file an issue for the LiveShare team and close this one after they confirm the problem.

**Comment by jrieken** [comment]
Yeah, that afaik the expected behaviour of live share. In order to show the guest data from the host requests are re-run, e.g they have no access to our UX but to the data providers

**Comment by kenkangxgwe** [comment]
Sounds reasonable, I will keep in mind for further implementation. Thanks

**Comment by jrieken** [comment]
Yeah, from the vscode pov this is definitely as-designed. We expose a bunch of "api commands" (https://code.visualstudio.com/api/references/commands) which other extensions can use, e.g an extension might run the document symbol command to know where to place code lenses
