### ISSUE TITLE
blur issue on editor and IDE texts

### ISSUE THREAD

**Issue by rtanzifi** [microsoft/vscode#88355]
Hello. 
There are some blur issues on my vscode editor recently. i did not have it on windows 8.1 but on my newly windows 10 and latest vscode i have this problem. The texts are convert to blur and then switch to normal when debugging or installing extension or when the notification windows appear on right bottom of the screen:
[IDE screenshot when it was blur](https://imgur.com/a/oYU75TZ)
any help would be appreciate
Thanks.

**Comment by connor4312** [comment]
Does this problem occur if you [disable GPU acceleration](https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration)?

/needsMoreInfo

**Comment by rtanzifi** [comment]
@connor4312 Thanks man. It solved my problem. Disabling GPU acceleration works. Now every fonts and texts are smooth.

**Comment by connor4312** [comment]
Ok, thanks. Deepak fyi, not sure whether you want to keep the issue open.

**Comment by deepak1556** [comment]
Thanks @connor4312 , we can close the issue as there is nothing actionable for code.
