### ISSUE TITLE
surroundingPairs configuration doesn't work

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#88357]
![](https://lh3.googleusercontent.com/oLLLSK0Mn84JRr00T2ibzKY23S2eyDVtzEiND2uDSgEuZrPFWW4mmudl7MKBUjLvJHiNCX6q2Nedke8EMwaZq40mkbeU1seTLeI5uycYv4KZh5tFSNuGFEVeaJB3H7Kz8tWXaHbFDF8lC7Sujuv2WId0hgfdYnyrmokxhp_itOU9KKGJEchk-vRSYSKsl06xU3sbrH3zfFHE7UVjTEjgxCbIHgb2JiVkYRqh4OQKcBWFEgCsewV4Z_Wp-JTyN9VqqiKkR1zgAHKcy1Hvc0V7as5suZvPEihjUi_wUUmh3aY2JwKSdueBQ-Fwpx_rnBxI72g6mASBBX-vQF5xhS38M2RIE-QY-xBuXKjAX5R_ZRxSQDKIc6uVIZoelSlFqpBRvJcHCkvQtUU9nE7PKaMjq-WOGnwai_IUKvMzcFZscu3OhySSBupdHTJVUBEiPiFMENICab4IFBrJcClUTPhmqGBQ3asdHLIvrr_cPKNW144tm4RX6fd3sCxVbVkXJyOOP4X4bEsa7UTi5PwIlMS5QjJAYK8mur7O2GWa5EGYRQLsEFBKVZqcb5NHwfhQ0wwp4TRzLYDriW2Pbim3iVqmviNXHlhzu8WzZwhqPdOoY2Ys2zbwYP-gRWPdowQyES6a0uyCH79E20bZJBxK-lB1jpPhKAxbXgBGt6SooqUAPZMYf1gaW99-mE48EUNTTsIpivrspt1Dtj-HU67nE3-OpaJ89U1Lmwb-hSOkgzKbdl1bCR8=w678-h212-no)
(code independent)

mentioned in https://github.com/microsoft/vscode/issues/88151#issuecomment-571699095

**Comment by aeschli** [comment]
I'm not able to reproduce. `bat` does not have `'` as surrounding character [out of the box](https://github.com/microsoft/vscode/blob/master/extensions/bat/language-configuration.json). How did your run with the updated `language-configuration.json`?
I guess there's an issue in your development setup.

Here are the steps I performed to make sure the surround feature works:
- check out the VSCopde repo and setup according https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run
- in `extensions/bat/language-configuration.json`, add  `["'", "'"]` to the surrounding pairs
- run `yarn && yarn compile` as well as `./scrips/code.bat/sh` to start VSCode out of source (using the updated language-configuration.json)
- in the dev instance of VSCode, open a 'bat' file, select a character and press `'`.
Character is correctly surrounded with `'` 

An alternate way would be to create an extension that re-contributes the `bat` language, but with an extended `language-configuration.json` file.

**Comment by irvnriir** [comment]
@aeschli , thanks for the info, but the "`bat`" has \``"`\` Autosurround by [default](https://github.com/microsoft/vscode/blob/2ee7ddb01fd27c27f12d7c7a19f0ffdb7b105c57/extensions/bat/language-configuration.json#L20), and as seen in the .gif it doesn't work

**Comment by aeschli** [comment]
But `"` works for me:

![surround--bat](https://user-images.githubusercontent.com/6461412/72164707-7d7b5f80-33c6-11ea-8795-fdbd05ade64e.gif)

**Comment by irvnriir** [comment]
@aeschli . strange, i'll try reinstall .
