### ISSUE TITLE
Keymap using incorrect keyboard distribution

### ISSUE THREAD

**Issue by chponte** [microsoft/vscode#88359]
Issue Type: <b>Bug</b>

Instead of using the active keyboard distribution for the keybind shortcuts, vscode is picking the default keyboard distribution from my OS. I am changing keyboard distributions through KDE's keyboard layout manager. I don't know if this issue is specific to my DE or common to all.
Steps to reproduce:
1. Set the default keyboard distribution to es_ES.
2. Switch the active keyboard distribution to en_US.
3. Try to, for example, comment a line by pressing Ctrl + /. Instead of commenting the line, VScode changes the zoom (since the '/' key, in the spanish distribution, is a '-'). To toggle the comment, you have to press Ctrl + Shift + 7, since the '/' is above the '7' on this keyboard distribution.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.4.8-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3471)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|15.49GB (10.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.2.0
git-graph|mhu|1.18.0
python|ms-|2019.10.44104
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.0
cmake|twx|0.0.17

</details>

**Comment by connor4312** [comment]
The third bullet here should help you, let us know if it doesn't https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

/needsMoreInfo

**Comment by chponte** [comment]
You are right, following these instructions fixes the problem. Thanks!
