### ISSUE TITLE
High CPU usage issues with latest January update in Python with flake8

### ISSUE THREAD

**Issue by delyanr** [microsoft/vscode#88351]
- VSCode Version: January 2020 Update
- OS Version: Windows 10
- Environment: Python 3.7.4 incl. flake8 3.7.9

Steps to Reproduce:

1. Enable `python.linting.flake8Enabled`
2. Watch your CPU burn

Every time I open a .py file in my environment, VSCode starts the `python -m flake8` background process that goes into infinite loop and spikes the CPU. If I close the .py file, its flake8 process continues indefinitely. What is even worse, when I close VSCode, the flake8 process persists. The more files I open, the more flake8 processes are created. This started happening with the latest January update, making VSCode with flake8 basically unusable. (Note, I have not updated any packages or environments in the meantime, and running the flake8 process manually does NOT result in this issue.) Thanks

Does this issue occur when all extensions are disabled?: No

**Comment by pscosta5** [comment]
I have opened up an issue on the vscode-python repository.

https://github.com/microsoft/vscode-python/issues/9852
