### ISSUE TITLE
Weird auto suggestions from IntelliSense

### ISSUE THREAD

**Issue by vince1995** [microsoft/vscode#88361]
The autosuggest gives me sometimes really crazy suggestions like this one: 
![image](https://user-images.githubusercontent.com/15120985/72068644-d4f5ce80-32e5-11ea-8c66-eefa1622b728.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

VSCode uses fuzzy match (characters in same order but not required to be exact sub-string) in a lot of places (IntelliSense, Command Palette, Open File, etc).
In this case it's combination of auto import functionality (you have `googleapis` in your `package.json` and it has provided types) and this fuzzy math.

If it just a question why it's there - mentioned above.

Or do you have another probled? If yes - you need to provide more details required by issue template, used TS version (if not built-in) etc.

**Comment by vince1995** [comment]
Ok, I understand this, but the characters are not in the same order at this example.

**Comment by IllusionMH** [comment]
Yeah, you are correct.

/cc @mjbvz @jrieken for visibility

**Comment by jrieken** [comment]
That's because of `editor.suggest.filterGraceful` - with that enabled (default) the current word is permutated  a little to find a better match. Eg, jest, jset, and jets
