### ISSUE TITLE
 I CANNOT UNISTALL OR DISABLE EXTENSIONS ANYMORE.

### ISSUE THREAD

**Issue by Rivelino27** [microsoft/vscode#88365]
Please help me or uptade the visual studio code because there is a error that now i just can't unistall or disable no one extension, this maybe is an extension virus?
I have these extensios that i believe where should are causing this problem:
Quokka.js, pola code, autoclose tag and etc...

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide all details reuired by template (OS, versions etc)
Do you see any error notifications? Are there any errors in DevTools console (Help > Toggle Developer Tools)?

Can you remove extensions if you launch VS Code with all extensions disabled `code --disable-extensions` from terminal?
