### ISSUE TITLE
VSCode won't start properly, but just the outline of the window and the title bar

### ISSUE THREAD

**Issue by LaPeste** [microsoft/vscode#88363]
On Ubuntu 19.10, with

$code --version
1.41.1
-- a string --
x64

 when I open VSCode I get just the following

![image](https://user-images.githubusercontent.com/4258222/72069927-8dbd0d00-32e8-11ea-8290-8d2a0ecf4a52.png)

When opening In verbose from terminal, I get a bunch of text of which the only suspicious one is the following:

`[17700:0109/142315.305154:INFO:CONSOLE(1572)] "%cTRACE", source: file:///snap/code/23/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)

[17700:0109/142315.305154:INFO:CONSOLE(1572)] "%cTRACE", source: file:///snap/code/23/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)`

and when closing the window (only through Ctrl+Q) the following appear:

`[18022:0109/142530.024638:WARNING:x11_util.cc(1430)] X error received: serial 683, error_code 3 (BadWindow (invalid Window parameter)), request_code 3, minor_code 0 (X_GetWindowAttributes)

[18046:0109/142530.035725:WARNING:x11_util.cc(1430)] X error received: serial 99, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)`

Beside that just some Gtk-WARNING and some modules that fail to load (which I assume have always been there).

Any advice?

**Comment by LaPeste** [comment]
I'm still suffering from this issue.
I'll report here one more strange line that I see from the verbose logs

[19346:0116/114216.626199:INFO:CONSOLE(9)] "Uncaught (in promise) Canceled: Canceled", source: file:///snap/code/23/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (9)

Can you, please, take a look at this and at least advice a workaround?
So far the only workaround that I found is logging out and in again from Ubuntu. Not the most pleasant and fast thing to do.

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders

**Comment by LaPeste** [comment]
To be honest I don't even remember much. The issue was raised in mid January. It's now November....
Anyway, I don't work on Ubuntu anymore, so I can't give any more info about the issue.

**Comment by deepak1556** [comment]
Closing as per above comment. Thanks!
