### ISSUE TITLE
Git: checkout causes error

### ISSUE THREAD

**Issue by zRelux** [microsoft/vscode#88360]
Using the git checkout in the palette (cmnd + P) doesn't allow to change branch because it says that there is a error test_repo@1.0.0: The engine "node" is incompatible with this module. Expected version "^10.16.0". Got "12.7.0" This issue appeared yesterday. I'm using `nvm` to manage my node versions and the even if I do `nvm use` (selects 10.16.0) the issue still persists.

- VSCode Version: 1.41.1
- OS Version: MacOS Mojave 10.14.5

Steps to Reproduce:

1. (cmnd + P) type > git: Checkout to
2. Select a different branch
3. error shows up

Output from git in the terminal:
```
git checkout -q master
error test_repo@1.0.0: The engine "node" is incompatible with this module. Expected version "^10.16.0". Got "12.7.0"
error Commands cannot run with an incompatible environment.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
1. Do you have any git hooks installed in your repository?
2. Does that issue reproduce if you manually run git checkout in the terminal, outside of vscode?

/needsMoreInfo
