### ISSUE TITLE
Color theme per window or project

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#88376]
Issue Type: <b>Feature Request</b>

When I work on two projects at once, I happen to confuse which VS Code window I am reading from or writing to. For this it would be super helpful if one VS Code instance would be a color and the other one to be a different color. I tried to set the color theme in one window but then as soon as I focused in the other window it picked up the same theme. 
Would be great to have color themes per folder/project.

If this makes sense for more people.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by connor4312** [comment]
You should be able to do this by adding the desired theme to `.vscode/settings.json` in your projects. For instance, adding

```json
{
    "workbench.colorTheme": "Default Dark+"
}
```

Let us know if that works for you.

/needsMoreInfo

**Comment by csicky** [comment]
@connor4312 Thank you very much for the info! I didn't know I can do it like this. There are many things I don't know about what VS Code can do.
