### ISSUE TITLE
TS: Suggest options inconsistent in object literals

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#88379]
```ts
const a = (opts: { foo: number, bar: number }) => {}
a({|})
a({ bar: 0, |})
```

Place cursor at first pipe, trigger suggest. Provides options `foo` and `bar`, as expected. 

Place cursor at second pipe, trigger suggest. Provides options `foo` and `bar`, followed by every snippet available. Then, for me, selects the most recently used snippet. So I always need to scroll up to get the object properties. 

I'd prefer if it only suggested object property names for every suggest, not only suggests triggered from empty object literals.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/58112

**Comment by jrieken** [comment]
You can mitigate the situation by using editor.suggestSelection: first.
