### ISSUE TITLE
Uninstalling extensions has no effect when reloading VS Code

### ISSUE THREAD

**Issue by AndyLuckert** [microsoft/vscode#88378]
I tried to uninstall several extensions via the procedure as usual:
opening extensions (Ctrl+Shift+X), show only installed extensions, click on an undesired extension, then the button "uninstall".

Most of them don't show "reload required", some do.
Independently of the latter, whether I reload the entire window, or close and restart the application itself, the very same extensions remain installed.
Why is that and how can I definitely uninstall an extension with success then?

**- VSCode Version:**
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64

**- OS Version:**
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"

**Comment by sandy081** [comment]
Please try disabling all installed extensions except the one you are trying to uninstall and reproduce this?

**Comment by AndyLuckert** [comment]
It started working normally again, it was not functioning during approx. 2 days.
I cannot relate the beginning and ending to any particular event, wherefore I can just state: now, it works again.
