### ISSUE TITLE
IntelliSense not suggesting lodash functions with import _ from 'lodash-es' format.

### ISSUE THREAD

**Issue by xAt0mZ** [microsoft/vscode#88375]
Issue Type: <b>Bug</b>

I'm working on a project (Portainer) and we are using lodash-es as a dependency.
On previous build of VSCode, suggestions were working when importing lodash as 
```
import _ from 'lodash-es';
```
![2020-01-09-164809_1920x1080_scrot](https://user-images.githubusercontent.com/7642331/72084423-bbfc1600-3303-11ea-985c-5a01cf00a87c.png)

IntelliSense (suggestions) are not showed anymore with this kind of import, and we didn't changed anything.
However, suggestions are showed whith no import at all (lot of suggestion duplicates) 
![2020-01-09-164838_1920x1080_scrot](https://user-images.githubusercontent.com/7642331/72084487-ddf59880-3303-11ea-9601-eea31f7e5257.png)
or when importing lodash with
```
import * as _ from 'lodash-es';
```
![2020-01-09-164825_1920x1080_scrot](https://user-images.githubusercontent.com/7642331/72084518-ef3ea500-3303-11ea-854e-706fbc12d197.png)

It's not related to an extension as VSCode has the same behaviour when started with `--disable-extensions` flag.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.4.8-arch1-1
<details><summary>VSCode config</summary>

```
{
    "[go]": {
        "editor.formatOnSave": false
    },
    "auto-close-tag.activationOnLanguage": [
        "xml",
        "php",
        "blade",
        "ejs",
        "jinja",
        "javascript",
        "javascriptreact",
        "plaintext",
        "markdown",
        "vue",
        "liquid",
        "erb",
        "lang-cfml",
        "cfml",
        "HTML (Eex)"
    ],
    "editor.tabSize": 2,
    "eslint.alwaysShowStatus": true,
    "files.autoSave": "onFocusChange",
    "gitlens.views.compare.location": "gitlens",
    "gitlens.views.fileHistory.location": "gitlens",
    "gitlens.views.lineHistory.location": "gitlens",
    "gitlens.views.repositories.location": "gitlens",
    "gitlens.views.search.location": "gitlens",
    "go.useLanguageServer": true,
    "javascript.updateImportsOnFileMove.enabled": "never",
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "terminal.external.linuxExec": "gnome-terminal",
    "window.zoomLevel": 0
}
```

</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3469)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|15.53GB (5.28GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
systemd-unit-file|coo|1.0.6
vscode-eslint|dba|2.0.13
gitlens|eam|10.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
gc-excelviewer|Gra|2.1.32
VS-code-vagrantfile|mar|0.0.7
vscode-language-pack-fr|MS-|1.41.2
cpptools|ms-|0.26.2
Go|ms-|0.12.0
vscode-sort-json|ric|1.18.0

</details>

**Comment by mjbvz** [comment]
I'm not able to repo this issue:

![Screen Shot 2020-01-10 at 5 52 22 PM](https://user-images.githubusercontent.com/12821956/72197061-fe8c2400-33d1-11ea-905c-f5dbf7f2afdb.png)

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, what does the rest of your project look like?
