### ISSUE TITLE
Provide a way for a different language to receive html language features

### ISSUE THREAD

**Issue by xorye** [microsoft/vscode#88377]
Hi, it would be great if there was a way for different HTML-like languages to receive HTML language features. Templating language extensions in the VS Code Marketplace could benefit from this.

Our use case:
We are working with a new HTML templating language with its own language config and TextMate grammar and would like to have the built-in HTML language features for the language. Features like auto indent, auto close tags, auto rename tags.

In our package.json we've created a new language called "Qute", for the [Qute Templating Engine](https://quarkus.io/guides/qute-reference), with its own language config and grammar.

I don't think doing `"files.associations": {"*.(our-extension)": "html"}` in settings.json would help here because changing the file association would override the Qute grammar and language config.

Maybe there could be a way to register new HTML-like languages to the HTML language server?

Or is there a better way to handle this?

Thanks!

**Comment by xorye** [comment]
https://github.com/microsoft/vscode/issues/55088 seems like a solution.

Please feel free to close this issue

**Comment by xorye** [comment]
Hi @aeschli, it looks like the comment in https://github.com/microsoft/vscode/issues/55088#issuecomment-408031810 suggests forwarding requests by executing VS Code commands like `vscode.executeCompletionItemProvider` to get completion support, for example.

But what about html features like auto close tags and auto rename tags? The HTML LS accepts `html.autoClosingTags` and `html.mirrorCursorOnMatchingTag` to facilitate those features but I don't think it's possible to call specific requests to a specific LS using VS Code commands.

Would the solution here be to create our own LS that accepts `autoClosingTags` and `mirrorCursorOnMatchingTag` requests? To avoid redundancy, I think it would be ideal if I could communicate with the HTML LS instead.

Another solution would just be to add our language in this array: https://github.com/microsoft/vscode/blob/76d0b308ededd3a706d26fb1ccc564428248cd29/extensions/html-language-features/client/src/htmlMain.ts#L73

but because the Qute language is new, I understand if that's not favorable in general, to have random languages in the VS Code source code.

**Comment by aeschli** [comment]
Yes, we want to make the full-html language (html + css + javascript) server more reusable
a. as a service like the current html-language-service, to be used as library by other language servers
b. as a new contrib point so html-like languages (e.g. html template languages) can provide a custom scanner and ask to be served by the html server  (and get added to the array that you were pointing to). The issue for that is https://github.com/microsoft/vscode/issues/49210

autoClosingTags and mirrorCursorOnMatchingTag would be made available in both approaches.

It is also planed to make  autoClosingTags and mirrorCursorOnMatchingTag language features for all (using regular provider). So they would be reusable like code completions. 

If you have your own language server, I'd recommend for adding html as a service (a.) so you are self contained, avoid versioning issues and are able to give context to the HTML language service (e.g.) globals) gets as well as have more control over the user experience.

Approach (b) to enable a fast adoption of a template language where there is no language server. The capabilities added will be limited to inheriting HTML support.
