### ISSUE TITLE
Python print() statements do to appare in terminal

### ISSUE THREAD

**Issue by iswyatt** [microsoft/vscode#88382]
I have been using vs-code for a few months writing Python code. In my development process, I use print() statements to debug and monitor code execution; this all worked fine until a couple of days ago when the output of print() statements did not appear in the terminal until I quit the Python script. This problem is consistent for all of my scrips that worked before and on two computers running vs code. I have remove and re-install vs code with no remedy. Also, I do not have this issue when using other editors like Spyter or PyCharm.

**Comment by connor4312** [comment]
Please open this issue on the Python extension
