### ISSUE TITLE
tsserver won't start - WSL?

### ISSUE THREAD

**Issue by alexpaluzzi** [microsoft/vscode#88388]
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open any .js or .ts file in my project

After opening and watching "Initializing js/ts server...". I verbose logging shows a whole mess of stuff, happy to put it all here if needed.
Some that stick out:

[Trace  - 19:30:30.496] <semantic> Response received: updateOpen (2). Request took 137986 ms. Success: true 

This took over 2 minutes.

[Trace  - 19:30:31.120] <semantic> Response received: getSupportedCodeFixes (3). Request took 138609 ms. Success: true 

This took another 2 minutes.

[Trace  - 19:30:37.291] <semantic> Response received: configure (4). Request took 144779 ms. Success: true 

Again.

Then it just kind of hangs. I noticed when I try to force some intellisense (with ctrl+space) I see these errors:

```
[Error  - 19:35:46.867] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:210613)
	at t.Reader.onLengthData (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:211680)
	at Socket.<anonymous> (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:211607)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

I tried reinstalling VS Code. I tried Insiders. All my extensions (except for WSL Remote) are disabled. Happy to help or get more information if needed.

**Comment by mjbvz** [comment]
Where is your code stored? Somewhere besides the `c:` drive?

**Comment by alexpaluzzi** [comment]
> Where is your code stored? Somewhere besides the `c:` drive?

Yes sir. It's on a separate drive entirely `d:`. I didn't think of that one. I've always had my code there but could move it if needed.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by alexpaluzzi** [comment]
Thank you kindly! Apologies for missing the dupe. Cheers.

**Comment by alexpaluzzi** [comment]
@mjbvz it turns out I actually don't have these on the `d:` drive like I thought. They are in the home directory inside WSL2. It also seems like installing the extension didn't help. Apologies, I forgot I moved over to WSL2 a couple months ago.

**Comment by mjbvz** [comment]
Are you using the vscode wsl-remote extension? If not, can you please explain how you are opening the folder

**Comment by alexpaluzzi** [comment]
Yes, using `ms-vscode-remote.remote-wsl`. I either open VS Code directly from Windows (and the project shows up since it was last opened), or I simply `code .` from the Ubuntu shell.

**Comment by alexpaluzzi** [comment]
I also just started getting this pop-up too:
![image](https://user-images.githubusercontent.com/1376892/72108948-b3efa680-3302-11ea-940f-c561ad2dccd5.png)

No idea if it's related but it's new all of the sudden. My max user watches are already `524288` but I'm not ruling out some serious WSL2 weirdness here.

**Comment by alexpaluzzi** [comment]
Opening new issue to avoid confusion.
