### ISSUE TITLE
Python terminal shows no visual output until script finishes

### ISSUE THREAD

**Issue by rsekelsky** [microsoft/vscode#88389]
Issue Type: <b>Bug</b>

I don't know exactly how to reproduce this, as it was working fine until today.

Running a python script using the green arrow for "Run Python File in Terminal" shows the shell commands used to start running the script (such as sourcing virtualenv), but doesn't show any printing commands until the script has finished running. Running tensorflow code, so typically there are a bunch of training status messages - I made sure the verbosity is correct.

The terminal output behaves as expected when the same script is run in the debug console.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor (8 x 2934)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|11.75GB (1.42GB free)|
|Process Argv|model.py --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.57204

</details>

**Comment by connor4312** [comment]
Please open this on the Python extension
