### ISSUE TITLE
Creating a worker thread in the extension host crashes VS Code

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#88386]
The worker_thread API is available, but attempting to use it in an extension crashes VS Code.

1. Create a "hello world" extension from a template
2. Create a blank worker.js file
3. Add this to your extension's activate:

```js
const { Worker } = require('worker_threads');
new Worker(join(__dirname, 'worker.js'));
```

4. Run the extension. VS Code crashes upon activation.

**Comment by DonJayamanne** [comment]
Agreed, fails. Trying to use this in the `Python` extension as well, and `kaboom`.
Couldn't find any reason for this.

**Comment by anonimitoraf** [comment]
Any updates on this?

**Comment by bpasero** [comment]
I have a feeling this does not reproduce with our exploration builds. Can you try?

We are building exploration builds that use a much newer version of our UI framework (Electron version 7.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/code-exploration_1.45.0-1588316142_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/code-exploration-1.45.0-1588316312.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/code-exploration-1588316492.tar.gz)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/VSCodeUserSetup-x64-1.45.0-exploration.exe)

**Comment by DonJayamanne** [comment]
@bpasero Tried and works (am to start a worker thread and things work as expected).
Thanks.

**Comment by bpasero** [comment]
This seems to be more of a debugging problem than actually being able to use worker threads. E.g. I created an extension that uses this and it seems to work fine unless I debug.

**Comment by DonJayamanne** [comment]
> I created an extension that uses this and it seems to work fine unless I debug.

FYI - It worked for me while debugging.

**Comment by bpasero** [comment]
What I mean to say is: it works for me even in Electron 7. But not when debugging.

**Comment by deepak1556** [comment]
Does this still crash with latest insiders ?

**Comment by connor4312** [comment]
Yep it seems to work in electron 9.

(note that debugging the threads doesn't work either in Electron or in Node https://github.com/nodejs/node/issues/26609)
