### ISSUE TITLE
Path must be string recieved null

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8838]
- VSCode Version: insider
- OS Version: os x

Steps to Reproduce:

1. Start debugging some node code
2. Click on an internal module, notice error in console

![screen shot 2016-07-07 at 16 40 50](https://cloud.githubusercontent.com/assets/1926584/16657146/ad14b50a-4461-11e6-90a4-e2590ca68df0.png)

**Comment by dbaeumer** [comment]
@jrieken dup of the one from yesterday.
