### ISSUE TITLE
Python, simple print command does not show any output in integrated terminal

### ISSUE THREAD

**Issue by oliviercwa** [microsoft/vscode#88380]
**Repro Steps**:
1- Create a simple python script:
```python
a = 0
b = 1
```
2- add a break point to second line, and execute the script
3- Once the breakpoint is hit, type in the Debug Console window:
```
print(2)
```
**Result**:
```
> print(2)
< None
```
Every time you try to print anything, it displays None instead of executing the print command

**Expected**:
Print the output of the print command

**Notes**:
1- This is the launch settings that are used. I have tried to remove "console":"integratedTerminal" with no success. 
{
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
    },
2- Output goes to Terminal but not to the Debug Console like it used to

**Env**:
Windows 10
Python 3.7.4 64 bits
VS: 1.41.1

**Comment by FarukEroglu2048** [comment]
Having the exact same issue, and there are lots of reports on StackOverflow.

Seemingly it does not print the output in terminal unless program is terminated.
