### ISSUE TITLE
Odd Issue with Tabbing Code + Formatted super oddly when saving

### ISSUE THREAD

**Issue by bobber205** [microsoft/vscode#88387]
Issue Type: <b>Bug</b>

I'm going to attach a video but wow this is weird. Started happening this morning (1/9/20) after the latest update on the insiders branch.

I was going through lots of code and adding a <></> and tabbing it so that it's properly formatted. Almost every time when I pressed save after tabbing in insider formatted the code in the oddest way. An undo put it back where it should be (tabbed in)

VS Code version: Code - Insiders 1.42.0-insider (7e64866a703c83dcdd3b84a8b48dd1673895fb7d, 2020-01-09T06:43:40.314Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 8, 8|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|-psn_0_659617|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
vscode-mjml|att|1.6.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.0.13
gitlens|eam|10.2.0
beautify|Hoo|1.5.0
RelativePath|jak|1.4.0
haml|kar|1.3.0
vscode-github|Kni|0.30.3
atom-keybindings|ms-|3.0.6
uuid-generator|net|0.0.4
ruby|reb|0.26.0
vscode-fileutils|sle|3.0.0
vscode-ruby|win|0.26.0
propertylist|zho|0.0.2

</details>

Crappy gif but it's the best I can do atm.

https://imgur.com/a/lUyOrfZ

**Comment by connor4312** [comment]
Do you have [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) set to run on save? (`editor.formatOnSave`)

**Comment by bobber205** [comment]
> Do you have [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) set to run on save? (`editor.formatOnSave`)

I believe so -- though I am using eslint in additon to beautify.

I have this
```
{
    "window.zoomLevel": 0,
    "typescript.format.enable": true,
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "eslint.autoFixOnSave": true,
    "eslint.packageManager": "yarn",
    "eslint.run": "onSave",
    "editor.minimap.enabled": false,
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "extensions.autoUpdate": true,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "files.associations": {
        "*.jst": "html"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[json]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    }
}
```

**Comment by connor4312** [comment]
Does this issue still happen if the eslint and beautify extensions are disabled?

**Comment by bobber205** [comment]
I'll check but for now I wanna say it's also putting semicolons in odd spots like this

![weird semis](https://user-images.githubusercontent.com/5841107/72108763-22276f80-32e9-11ea-8e9b-0bfa78a2bb42.png)

**Comment by bobber205** [comment]
![CollectionReviewScreen js — legit 2020-01-09 14-07-00](https://user-images.githubusercontent.com/5841107/72108849-500cb400-32e9-11ea-96f1-9bf85a8e1371.png)
I turned off eslint and did some light formatting manually and this happened.

**Comment by bobber205** [comment]
This seems to be the culprit. I gave it a little while and it hasn't happened since I turned this off.

```
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": false
    }
```

**Comment by connor4312** [comment]
Okay, thanks. I'd recommend opening an issue on their repo.
