### ISSUE TITLE
Can't run Selenium python file

### ISSUE THREAD

**Issue by djalan** [microsoft/vscode#88390]
Issue Type: <b>Bug</b>

Hello

Please kindly take a look at this issue: https://stackoverflow.com/questions/58455234/running-selenium-from-visual-studio-code-terminal-with-virtualenv

Basically, the code works when I execute it outside of VSCode in my terminal, but the same code cannot be executed from VSCode. It only works in VSCode in headless mode (Firefox window doesn't show up).

Please kindly read Mike's question in the above link. I have the very same issue.

VS Code version: Code - Insiders 1.42.0-insider (cba31b819ea99836daf51cee56299348e9c6d20b, 2020-01-08T05:33:44.740Z)
OS version: Linux x64 5.4.6-2-MANJARO snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor (12 x 2686)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.65GB (9.71GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vsc-material-theme|Equ|31.12.0
vscode-firefox-debug|fir|2.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-test-explorer|hbe|2.15.0
vscode-peacock|joh|3.2.0
chat|kar|0.31.0
vscode-python-test-adapter|lit|0.3.15
vscode-docker|ms-|0.9.0
python|ms-|2020.1.57595-dev
vsliveshare|ms-|1.0.1456
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.4
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.2
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscode-maven|vsc|0.20.1
vim|vsc|1.12.4

</details>

**Comment by Tyriar** [comment]
venv queries should be directed to the Python extension https://github.com/microsoft/vscode-python

**Comment by djalan** [comment]
I am able to execute Python code with my venv / installed librairies in VSCode. Did you think I couldn't do this?

**Comment by Tyriar** [comment]
@djalan you're reporting a bug from what I can tell is about the Python extension, not VS Code core.
