### ISSUE TITLE
Add API to support custom width of document/webview columns

### ISSUE THREAD

**Issue by agrawal-d** [microsoft/vscode#88398]
As of now, it is possible to assign view-columns to API created documents/webviews. But, it is not possible to set their width ( in pixels or otherwise ) . This is needed in some extensions that use webviews, and  only need a small amount of space beside the main editor.

Currently, the user manually needs to resize them. Ability to do this programmatically ( set pixel widths of documents ) would be a nice addition to the API.

![image](https://user-images.githubusercontent.com/7714968/72125759-c7951e80-338f-11ea-9c35-1a6ce6e2cc03.png)

For example, in this image, the webview on the side is taking up very little space, but this had to be done manually.

**Comment by bpasero** [comment]
Actually this is possible with the `vscode.setEditorLayout` command: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_25.md#grid-editor-layout-new-commands
