### ISSUE TITLE
Auth flow creates a local server 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88392]
Right now the sync auth flow creates a local server to redirect to. Some users won't have permissions to do this so it would redirect to a 404.

**Comment by RMacfarlane** [comment]
I still attempt to create a local server, but if isn't able to establish a connection on an open port, I fall back to directly hitting the login endpoint

**Comment by Tyriar** [comment]
Not sure how to verify, might be best to trust your testing where you hardcoded the port?

**Comment by RMacfarlane** [comment]
Yeah, I don't have steps to cause a failure for listening on the server. So either that, or a quick code review?

**Comment by Tyriar** [comment]
@RMacfarlane consider refactoring to improve code sharing between `login` and `loginWithoutLocalServer`, feels dangerous to duplicate code across the rarely used `loginWithoutLocalServer`
