### ISSUE TITLE
Can't enter Vim visual block mode in integrated terminal

### ISSUE THREAD

**Issue by renzbagaporo** [microsoft/vscode#88395]
I can't enter visual block mode in Vim. Seems to paste stuff from the clipboard instead.

- VSCode Version: 1.41.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Select Git Bash as default shell.
2. Start vim.
3. Send `ctrl-v` to enter visual block mode. Pastes stuff instead.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/question

<kbd>Ctrl</kbd>+<kbd>V</kbd> is binded to `workbench.action.terminal.paste` and this is one of default actions whose keybinding will be intercepted and handled by VS Code.
Use next setting to exclute it from the list (will effectively disabled paste with <kbd>Ctrl</kbd>+<kbd>V</kbd> to the terminal)
```json
"terminal.integrated.commandsToSkipShell": [
    "-workbench.action.terminal.paste"
]
```
See details: https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

**Comment by renzbagaporo** [comment]
Thanks @IllusionMH!
