### ISSUE TITLE
[HTML Grammar] HTML Tags may start with colon

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/vscode#88396]
- VSCode Version:  1.42.0-insider
- OS Version: MacOS Catalina

As the title says, a leading colon is allowed in HTML tags but it breaks syntax highlighting in VSCode:

<img width="435" alt="Screen Shot 2020-01-10 at 1 41 46 pm" src="https://user-images.githubusercontent.com/8518303/72121525-654c1600-33af-11ea-8ab5-c8c37d17e778.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Where did you see `:` is a valid tag name?

Here's what I see for `<:foo></:foo>`:

https://validator.w3.org/nu/#textarea
![image](https://user-images.githubusercontent.com/4033249/72248559-c5cd9400-35f7-11ea-8a7b-bcc8fdfaf8ce.png)

**Comment by Jamesernator** [comment]
Step 1 of [createElement](https://dom.spec.whatwg.org/#dom-document-createelement) only requires an element name match the [Name](https://www.w3.org/TR/xml/#NT-Name) production which can start with `:`.

Although they might be `HTMLUnknownElement` they're still grammatically conforming.

For me I mostly want to use them as part of a preprocessor using the fact that `:` is noticably different from normal element names when reading the file while still maintaining the ability to use regular DOM methods to pre-process them into HTML files.

**Comment by octref** [comment]
You should open an upstream issue here: https://github.com/textmate/html.tmbundle

**Comment by alexr00** [comment]
We get our html grammar from https://github.com/textmate/html.tmbundle. Please open an issue in that repository and if it's fixed then we'll bring the change to VS code in a month or two (usually).
