### ISSUE TITLE
Editor captures scrolling event in interactive playground

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#88394]
Issue Type: <b>Bug</b>

* Open Interactive Playground
* Put focus in a monaco editor, which has no overflow/scrollbar
* Scroll

Previously scroll event will be emit if there is no scrolling happening in monaco editor, which will finally scroll the whole interactive playground. Now the editor always captures the events.

VS Code version: Code - Insiders 1.42.0-insider (7e64866a703c83dcdd3b84a8b48dd1673895fb7d, 2020-01-09T06:43:40.314Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|32.00GB (0.63GB free)|
|Process Argv|-psn_0_3761046|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.0
vscode-pull-request-github-insiders|Git|2020.1.11042
debugger-for-chrome|msj|4.12.4

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
It was introduced by `alwaysConsumeMouseWheel`. cc @alexdima

**Comment by alexdima** [comment]
Thanks for the fix :heart:
