### ISSUE TITLE
Feature [Ctrl+H] find and replace.  checkbox "in selection only" and replacements count

### ISSUE THREAD

**Issue by nmurzin1981** [microsoft/vscode#88408]
I want to complain about a feature [Ctrl+H] find and replace 
Please look how wonderful this feature realized in Notepad++.
It has checkbox "in selection only" for working with selected text only.
It has checkbox "Whole words only".
It has checkbox "Case sensitive".
And it has reporting, how many replacements have been completed.
I don't see all of this in WSCode.
I really miss about checkbox "in selection only" and about reporting of replacements count.

**Comment by IllusionMH** [comment]
>I don't see all of this in WSCode.

![image](https://user-images.githubusercontent.com/1312662/72143212-f666c100-339e-11ea-8029-7fdbe66944c4.png)

Highlighted switches from left to right are Match case (case sensitive), Match Whole Word, Find in selection.

You can check what other means by tooltips.

1 of 3 - number of matches (in selection) all will be replaced if you pick Replace all.

**Comment by nmurzin1981** [comment]
Thank you very much for your answer
Until you poked my nose, I did not see these options.

**Comment by IllusionMH** [comment]
/question

If you are sure that there are bugs with provided functionality - add detailed steps to reproduce.
