### ISSUE TITLE
Add the cell toolbar to Jupyter notebooks

### ISSUE THREAD

**Issue by epetrovski** [microsoft/vscode#88409]
When a jupyter notebook runs in the browser, it's possible to enable a cell toolbar for each code/markdown cell by clicking the menu item View > Cell Toolbar. The cell toolbar lets the user edit cell metadata which, for example, can be useful if creating a slideshow from the notebook.

The cell toolbar looks like this:
![cell_menu](https://user-images.githubusercontent.com/24638276/72136620-7da93a00-3389-11ea-837d-98f6b6ebf955.png)

Could this be added to the native Jupyter notebook editor in vscode?

**Comment by IllusionMH** [comment]
/causedByExtension

Please report this feature request in https://github.com/Microsoft/vscode-python/issues repo if it wasn't filed before.
