### ISSUE TITLE
Workspace shell permissions are not remembered with remote host.

### ISSUE THREAD

**Issue by schattenmann80** [microsoft/vscode#88406]
I'am working with vsode on Windows but the source is on a debian remote host. I connect to via ssh.
On the remote host I a have a scipt to set up the envirement and I use it with the setting "terminal.integrated.shellArgs.linux". But every time I restart vscode I need to set "Allow Workspace Shell Configuration" so that the "terminal.integrated.shellArgs.linux" can work.
![Allow](https://user-images.githubusercontent.com/22788790/72135482-e642e780-3386-11ea-94b3-8bc26a015437.png)

**Comment by kumaran-14** [comment]
@Tyriar I'd like to take this up. What should be the things I need to look for?

**Comment by Tyriar** [comment]
@kumaran-14 this one might be a little tricky for a contributor to get the right fix so I recommend again this one.

**Comment by dfarley1** [comment]
I'm encountering the same issue with a remote container. Running `Allow Workspace Shell Configuration` and opening a new terminal works until the remote is closed.

**Comment by krokyk** [comment]
Experiencing the same issue. Is this going to be addressed in a near future? It is annoying to always hit F1, start typing "shell perm..." and clicking on the allow option. Can this be made configurable on the workspace level somehow (i.e. we could enable/disable it via the workspace settings file)?

**Comment by schattenmann80** [comment]
I really hope that this gets fixed soon. Because I have a unstable internet connection and need to restart vs code 3 to 4 times a day.
And every time I restart I also need to set the shell permisson again.

**Comment by davidwin** [comment]
Yup, this is very distracting. I'm trying to set up a Workspace where a development environment must be sourced in first, and I'd like to have to give my permission only once and then be done with it.

**Comment by Aetherbase** [comment]
Any update on the fix ? It really is annoying to change everytime to allow with ctrl+shift+p. Saving the settings on allow will save us a big time.

**Comment by schattenmann80** [comment]
The new features for the Remote Development extensions is a workaround for this bug:

>  Work continues on the Remote Development extensions, which allow you to use a container, remote machine, or the Windows Subsystem for Linux (WSL) as a full-featured development environment.
> 
> Feature highlights in 1.51 include:
> 
> Ability to persist/reconnect to terminal sessions.
> Improved port forwarding experience.

**Comment by Tyriar** [comment]
This is no longer an issue since we've moved to the centralized workspace trust system
