### ISSUE TITLE
页面标签拖拽没反应

### ISSUE THREAD

**Issue by southyou** [microsoft/vscode#88407]
Issue Type: <b>Feature Request</b>

有时候会出现：页面标签拖拽没反应

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by IllusionMH** [comment]
Please report issues in English whit detailed steps to peproduce
