### ISSUE TITLE
When selected text is replaced by tab, option editor.insertSpaces is not respected

### ISSUE THREAD

**Issue by HubertJFarnsworth** [Microsoft/vscode#8840]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open any text file
2. Have option editor.insertSpaces set to true
3. Select a portion of text (size selected doesn't matter)
4. Hit Tab to replace selected text with a tab

Expected: selected text is replaced with spaces equivalent to a tab
Actual: selected text is replaced with actual tab character

**Comment by alexandrudima** [comment]
@HubertJFarnsworth When the selection is a single line selection the text will be replaced with a `\t`. Otherwise there would be absolutely no way to insert a Tab character anymore.

**Comment by alexandrudima** [comment]
Related #7682

**Comment by alexandrudima** [comment]
Related #4312

**Comment by HubertJFarnsworth** [comment]
So I guess you are saying this is working as intended.  It certainly doesn't seem like the correct behavior to me.  It seems if the setting to convert tabs to spaces is set it should be used consistently and not depending on whether you are replacing text or not.  If you want a hacky way to insert \t then you can copy and paste one in.  This is the behavior of the other coding text editors on my system (Visual Studio and Notepad++ and according to @blakeembrey sublime).  The current behavior seems inconsistent and non-intuitive.  If I hadn't had editor.renderWhitespace=true I would have introduced a bunch of \t characters in my code base.  

That said, this issue should be closed as a duplicate of #7682.  There is no need to keep them both open.

**Comment by alexandrudima** [comment]
I agree, I will make the change in July that if the indentation settings are to insert spaces, pressing Tab should insert spaces
