### ISSUE TITLE
Extension host terminated unexpectedly in vs code 1.41.1

### ISSUE THREAD

**Issue by Garincha3014** [microsoft/vscode#88401]
Hi there, I'm using vs code 1.41.1. Recently i'm facing this problem "Extension host terminated unexpectedly". After googling this problem, most suggestions was to uninstall Live Server. So i tried to uninstall & disable the extension, but the message was "Cannot uninstall/disable extension live server". Please give hints to solve this problem.

**Comment by Garincha3014** [comment]
Sorry, this two links are not helpful to solve my problem. They are suggesting to uninstall extensions, which is not working in my vs code.

**Comment by connor4312** [comment]
This may help you: https://github.com/ritwickdey/vscode-live-server/issues/285

/causedByExtension
