### ISSUE TITLE
"Find All References" unnecessarily requires a word position

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#88413]
If I invoke "find refrences" when the cursor is on a puncuation character, the editor seems to bypass the server and says "no results" without making any requests:

![image](https://user-images.githubusercontent.com/1711539/71984664-913d8f00-3229-11ea-9770-c4261672dc71.png)

However, there are valid cases to invoke "find usages" on a punctuation character:

* in languages with operator overloading, searching for usages of `+` is a pretty natural thing to do
* In Kotlin, searching for `(` in `data class Point(val x, val y)` will search for constructor calls (this is the feature we are trying to mimic in rust-analyzer)

I've tested and in Emacs I can ref-search punctuation. It's interesting that goto definition does not try to check if thing at point is an identifier.

**Comment by jrieken** [comment]
Yeah, for peek this works for the viewlet is more strict because it wants to show add a history entry like "foo - some/file.ts - references" and without a word this gets tricky... Tho, in that case we should just use the character at the position

**Comment by matklad** [comment]
Confirmed that peek references indeed work with rust-analyzer's implementation!

**Comment by jzyrobert** [comment]
It looks like you'd have to implement a custom check or think of a regex to pass to `getWordRangeAtPosition`, about [here](https://github.com/microsoft/vscode-references-view/blob/a505658f152c04407e94515dbdb6ab0eb452937e/src/extension.ts#L138)

Should it allow any non whitespace character if its not a valid word?
