### ISSUE TITLE
Breadcrumbs or outline can't show properly a symbol which contains a macro

### ISSUE THREAD

**Issue by eypsume** [microsoft/vscode#88410]
- VSCode Version: Code Insiders 
Version: 1.42.0-insider
Commit: 7e64866a703c83dcdd3b84a8b48dd1673895fb7d
Date: 2020-01-09T06:44:40.132Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

OS: Linux x64 4.15.0-66-generic

Steps to Reproduce:
case 1) Breadcrumbs or outline can't show properly a symbol which contains a macro.
for me, the code is c++ . below is  simple example.
![vscode_cpp_breadcrumbs_error_using_macro_02](https://user-images.githubusercontent.com/38209036/72137066-7c99fc00-33cd-11ea-8bbf-329a7a2edf6a.png)

![vscode_cpp_breadcrumbs_error_using_macro_01](https://user-images.githubusercontent.com/38209036/72137042-73a92a80-33cd-11ea-9de5-733edcfe5f1f.png)

I push other case.
case 2) they has same issue in c++ 11 'foreach' statement .

```
 //example.cpp
#define MACRO_1( s ) \
    if ( s == "" )

class Query
{
	Query( int d=0);
	virtual ~Query();
	void query(const char* sql);
	void find(int id);
	void exec();
	void next();
	int  error() const;
	int  lastErr;
};

Query::Query(int d)
{
}

Query::~Query()
{
}

void Query::query(const char* sql)
{

}
void Query::find(int id)
{

}
void Query::exec()
{
	if ( true ) {
        MACRO_1( t1 ) {
			for (;;) {
			}
		}
	}
	else {
        MACRO_1( t2 ) {
		}
	}
}

bool Query::next()
{
	return true;
}

int Query::error() const
{
	return lastErr;
}
```
	

	

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
This is provided by the C++ extension, please open an issue there

/causedByExtension
