### ISSUE TITLE
In markdown hover, hr overlaps following codeblock

### ISSUE THREAD

**Issue by sam-mccall** [microsoft/vscode#88416]
Issue Type: <b>Bug</b>

If our LSP server returns the following hover content:

`````markdown
function `x`

---

```cpp
void x();
```
`````

It renders poorly:

![image](https://user-images.githubusercontent.com/548993/72149340-33cd4d80-33a3-11ea-8d18-5e130b984c18.png)

No spacing between HR and the code block, and in fact they overlap.
This is due to the negative margin of -6px added by @dbaeumer in 6d837706307e0f6747909d5f59b99f4bab68300f to fix other problems in rendering.

Removing that -6px makes it render much better, but presumably breaks other things:

![image](https://user-images.githubusercontent.com/548993/72149570-c5d55600-33a3-11ea-96ac-8064602068eb.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.2.17-1rodete3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (48 x 1197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.88GB (19.36GB free)|
|Process Argv|/usr/local/google/home/sammccall/test.cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clangd|llv|0.0.19
vim|vsc|1.0.3

</details>

**Comment by dbaeumer** [comment]
I fixed that a while back ago. Please ping if you are still experiencing this.

**Comment by sam-mccall** [comment]
No, looks fixed to me. Thanks!
