### ISSUE TITLE
Images: unable to "Save As..."

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88414]
Steps to Reproduce:

1. open an image
2. pick File > Save As

=> :bug: the image reopens in the editor but does not seem to be saved on disk properly

**Comment by mjbvz** [comment]
This is a good point: images are not editable but still should support saveAs. For this case, we could either:

- Require that extensions implement `saveAs`
- Implement it in core (since there are no edits, it would just be a file copy operation)

**Comment by mjbvz** [comment]
Checking in a change to implement a default in the core for readonly editors

If there is any use case for letting readonly editors hook into save as, we can always revisit this

 #77131
