### ISSUE TITLE
Inline location indicator breaks line layout

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#88412]
while debugging the extension host with VS Code Insiders and stepping through some code, I noticed this issue:

<img width="1239" alt="2020-01-07_23-58-57" src="https://user-images.githubusercontent.com/1898161/72140718-a6cdc880-3391-11ea-9222-0189d9ed168e.png">

**Comment by isidorn** [comment]
This seems to be a rendering glith. I can not reproduce this.
If you can still repro this, please let me know if you have steps and we can reopen this.
