### ISSUE TITLE
Compressed tree: "autoExpandSingleChildren" options does not work for top-level nodes 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#88420]
For the LoadedScriptsView I use the `WorkbenchCompressibleAsyncDataTree` with the  `autoExpandSingleChildren` option. This works fine for all but the top-level nodes which results in a strange UI: top level nodes first appear with the name of the top level node ('~' and '' in the screencast below). Expanding the node does not show any children below the node but instead shows the full path:

![2020-01-10_13-02-06 (1)](https://user-images.githubusercontent.com/1898161/72151808-83167c80-33a9-11ea-96e9-081cf68e2f0a.gif)

IMO there are two ways to address this issue:
- setting `autoExpandSingleChildren` to true should include the top-level nodes too,
- adding another option `autoExpandingTopLevelNodesWithSingleChildren`.

Here is my own compressed tree implementation for comparison:

![2020-01-10_17-47-35 (1)](https://user-images.githubusercontent.com/1898161/72170753-b8cf5b80-33d1-11ea-9680-37fa7c9c1db9.gif)

**Comment by weinand** [comment]
So switching to a SyncDataTree would make the problem go away because there we know without resolving that a node has only a single child?

**Comment by joaomoreno** [comment]
Exactly! :+1: I'm currently still exploring what the best option would be here... I'll come back to you.

**Comment by joaomoreno** [comment]
Loaded scripts now uses `CompressibleObjectTree`! 🎆
