### ISSUE TITLE
Add scrolling to  Source Control "details" pane

### ISSUE THREAD

**Issue by barata0** [microsoft/vscode#88423]
When selecting multiple Source Controls the lower pane shows them in details but you can't scroll on them.

Having many source controls selected will lead to have some of the details hidden depending on the screen size

**Comment by barata0** [comment]
Add a Resizable Split Pane too between Source Control Providers panel and The Source Control "Selected Details" Pane.

**Comment by joaomoreno** [comment]
#64188
