### ISSUE TITLE
Horizontal scrolling jump with long sentences

### ISSUE THREAD

**Issue by Zamtakk** [microsoft/vscode#88429]
Issue Type: <b>Bug</b>

# Bug explanation
When typing a comment that is longer than what can be made visible, the screen starts scrolling to the right to follow the cursor. Then, when clicking on the sentence a few words back to insert an extra word the horizontal scrolling jumps all the way back to the beginning, leaving the cursor somewhere off screen to the right.

### Edit 1
I just noticed that it only really happens in my main file and not in my test file. Sometimes it jumps back a bit but not all the times. I attached a video that shows what I mean with the bug. Not sure if you can do something about it since it can not easily reproduced.
![VSCode insiders horizontal scroll bug](https://user-images.githubusercontent.com/28710885/72167495-7f93ed00-33cb-11ea-8234-d418995031e4.gif)

### Edit 2
Added a snipped of code in a comment that can be used to reproduce the problem.

## Expected outcome:
The cursor is placed at the point where the mouse clicks and the horizontal scrollbar stays on the same spot.

## Current outcome:
The cursor is placed at the point where the mouse clicks and the horizontal scrollbar scrolls all the way to the left automatically.

## Generated information
VS Code version: Code - Insiders 1.42.0-insider (960cddb992cc96d47f56b633b361909f1b5b3353, 2020-01-10T05:39:23.171Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 1995)|
|Memory (System)|15.89GB (9.04GB free)|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 1995)|
|Memory (System)|15.89GB (9.04GB free)|
|VM|40%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
githistory|don|0.4.13
cpptools|ms-|0.26.2
vscode-vtools|ven|1.0.6
debug|web|0.24.0
remote-containers|ms-|0.96.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0

</details>

**Comment by connor4312** [comment]
@Zamtakk could you upload a gif or screen recording of what you're running into? I'm trying to follow your reproduction steps but I think I must be missing something.

/needsMoreInfo

**Comment by Zamtakk** [comment]
I added more information to my original post including a gif where I demonstrate the problem. I was not able to reproduce it properly in a test file so I do not know if this is fixable. I can not share the file that contains the problem due to an NDA.

**Comment by Zamtakk** [comment]
Okay I found that if you load just the fist bit of code, the problem also occurs. Paste this in a new .c file and scroll to the right like in the gif. Then click somewhere in the long comment and it will jump back with the scrollbar. The cursor will stay where you clicked and if you hold your mouse it will actually select from where you clicked to where you end up after scrolling.

`//
//
//
//++++++++++++++++++++++++++++++++++++++++++++++++++++ INCLUDES +++++++++++++++++++++++++++++++++++++++++++++++++++++++
//
//
//

// C standard includes
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Default hello world
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

// Added for GPIO
#include "driver/gpio.h"
#include "freertos/queue.h"

// Added for timer
#include "driver/periph_ctrl.h"
#include "driver/timer.h"

// Added for flash
#include "nvs.h"
#include "nvs_flash.h"

// Added for BLE
#include "esp_bt.h"
#include "esp_bt_defs.h"
#include "esp_bt_main.h"
#include "esp_gap_ble_api.h"
#include "esp_gatt_common_api.h"
#include "esp_gatt_defs.h"
#include "esp_gattc_api.h"
#include "esp_log.h"

// Config file
#include "sdkconfig.h"

//
//
//
//++++++++++++++++++++++++++++++++++++++++++++++++ DEFINE SETTINGS ++++++++++++++++++++++++++++++++++++++++++++++++++++
//
//
//


/*
 * Characteristics handles for each saved BLE address. This is to skip characteristics scanning on each transmission. Currently (v4.1-dev-816) this doesn't work because characteristics scanning is automatically done after opening a connection. I still used this method of saving information so that when an update comes that does not do this automatically this software
 * scanning is automatically done after opening a connection. I still used this method of saving information so that when an update comes that does not do this automatically this software
 * runs much quicker straight away.
 */

// IO =====================================================
#define BUTTON_PIN_MASK                                                                                                                                                  \
    ((1ULL << BUTTON_PIN_ON) | (1ULL << BUTTON_PIN_OFF) | (1ULL << BUTTON_PIN_G1) | (1ULL << BUTTON_PIN_G2) | (1ULL << BUTTON_PIN_SELECT) | (1ULL << BUTTON_PIN_COLOR) | \
     (1ULL << BUTTON_PIN_SATURATION) | (1ULL << BUTTON_PIN_BRIGHTESS) | (1ULL << BUTTON_PIN_SET_G1) | (1ULL << BUTTON_PIN_SET_G2) | (1ULL << BUTTON_PIN_DEBUG) | (1ULL << BUTTON_PIN_SHIFT))
#define BUTTON_PIN_ON 25
#define BUTTON_PIN_OFF 26
#define BUTTON_PIN_G1 27
#define BUTTON_PIN_G2 14
#define BUTTON_PIN_SELECT 18
#define BUTTON_PIN_COLOR 5
#define BUTTON_PIN_SATURATION 4
#define BUTTON_PIN_BRIGHTESS 19
#define BUTTON_PIN_SET_G1 15
#define BUTTON_PIN_SET_G2 2
#define BUTTON_PIN_DEBUG 13
#define BUTTON_PIN_SHIFT 12

// BLE / RGB ==============================================
#define NR_OF_CHARACTERISTICS 11

#define MAX_BLE_PEERS 15
#define BLE_PEER_INVALID 255`

**Comment by Zamtakk** [comment]
It only seems to happen when I am connected to WSL (Ubuntu) and make a test file on that system. When doing it locally on windows the bug does not occur.

**Comment by connor4312** [comment]
Huh, I wonder if it's maybe an extension you have running in WSL but not your host machine. Does the bug still occur if you disable all extensions, excluding remote-wsl?

**Comment by Zamtakk** [comment]
Found out that the bug only occurs when the extention "VTools by venryx" is enabled. Should have checked this before submitting this as a bug. Thanks for you time.
