### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by trivett** [microsoft/vscode#88427]
Issue Type: <b>Bug</b>

I've gotten this error and an endless loop of "Initializing JS/TS langauge features" pretty consistently for like a month now. Ive deleted all extensions, reinstalled VS Code even, and this keeps happening, making it really hard to use the one true text editor. Is there something I am doing wrong? 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 17, 16|
|Memory (System)|8.00GB (0.73GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-opennewinstance|chr|0.0.6
path-intellisense|chr|1.4.2
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
relative-import|sai|1.3.1
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.6.0
highlight-matching-tag|vin|0.9.6

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Which version of the TS language server are you using? It should be shown in the lower right corner of the screen.

/needsMoreInfo
