### ISSUE TITLE
Terminal popping out separate console

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#88425]
Issue Type: <b>Bug</b>

Under Win10, opening VS Code terminal popping out a separate console since VS Code 1.40

Terminal shell: Cygwin bash
Using "old console".

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.84GB free)|
|Process Argv|--folder-uri file:///d%3A/Profiles/anrdaemon/Documents/project/project|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.7
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
php-debug|fel|1.13.0
todo-tree|Gru|0.0.162
sqltools|mtx|0.21.6

</details>

**Comment by connor4312** [comment]
Can you share your terminal settings?

/needsMoreInfo

**Comment by AnrDaemon** [comment]
Any specific settings you have in mind?
To the best of my memory, I only changed the shell.

**Comment by connor4312** [comment]
The settings starting with `terminal.*` would be good!

**Comment by AnrDaemon** [comment]
```
    "terminal.integrated.env.windows": {"PROMPT": "$P$_$G$S"},
    "terminal.integrated.shell.windows": "C:\\Cygwin64\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["-i"],
```

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.

**Comment by AnrDaemon** [comment]
> you need to disable legacy console mode

I do? Since when?
It's unusable.

**Comment by Tyriar** [comment]
@AnrDaemon that is the cause of this issue, you need turn the option off to fix it:

![image](https://user-images.githubusercontent.com/2193314/72276414-b002a380-35e4-11ea-87e1-2bd1806c86e7.png)

**Comment by AnrDaemon** [comment]
Not going to happen. The "better" console does not support raster fonts. And there's no true type font that looks even relatively usable. They are all a huge eyestrain.

**Comment by Tyriar** [comment]
@AnrDaemon I don't know what you're referring to when you say the better console. Unchecking that box is the fix to your problem inside VS Code, rendering inside VS Code is the same regardless, rendering inside conhost is the same regardless as well.
