### ISSUE TITLE
Open a file with any file extension as text

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/vscode#88426]
It looks like vscode can't open images as text.

When I try to open a file, I get this message: "An error occurred while loading the image".

That was, because the file had corrupted data (repairing the file was the point of opening it in a text editor) and I had to open notepad++ for this simple task.

Can you ensure that any file with any file extension could be opened? 
Like with the binary files, it could ask if you "want to open it anyway"

If this is an existing feature, can you improve the discoverability of this setting?

**Comment by connor4312** [comment]
@mhanuszh you can do this by selecting `Reopen With` in the command palette (F1) and choosing the text editor. Let us know if that solves your problem.

/needsMoreInfo

**Comment by mhanuszh** [comment]
@connor4312 Yes, thank you!
But I feel like it's a little hidden. Can you please improve the discoverability of this feature?

**Comment by connor4312** [comment]
Maybe the image preview should have a button to `reopen with` if it sees the image is invalid.
