### ISSUE TITLE
Multiple Debuggers attaching at once

### ISSUE THREAD

**Issue by chasingSublimity** [microsoft/vscode#88434]
Issue Type: <b>Bug</b>

I'm working on an express app. The source code is mostly es6, with the tests mostly coffeescript. (We're mid conversion to es6)

When i run the below command, multiple debuggers attach

`NODE_ENV=test TZ=GMT mocha --source-maps --inspect-brk=9233 --require coffee-script/register --reporter spec --colors --timeout 20000 --exit`

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.82GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.9
better-toml|bun|0.3.2
gotemplate|cas|0.3.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.13
vscode-quick-select|dba|0.2.8
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
npm-dependency-links|her|1.0.1
vscode-titlebar-less-macos|leh|1.10.2
restructuredtext|lex|116.0.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|0.9.0
python|ms-|2020.1.57204
cpptools|ms-|0.26.2
Go|ms-|0.12.0
vsliveshare|ms-|1.0.1456
vsliveshare-audio|ms-|0.1.80
debugger-for-chrome|msj|4.12.4
rust|rus|0.7.0
code-settings-sync|Sha|3.4.3
addDocComments|ste|0.0.8
code-spell-checker|str|1.7.20
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
city-lights-icon-vsc|Yum|1.1.3

(9 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
> multiple debuggers attach

Can you explain the issue a little more? What do you see?

I assume that you have "auto attach" enabled?

**Comment by chasingSublimity** [comment]
Sure!

`auto attach` is enabled.

After i run the script mentioned above, i see the following:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/21029639/72172321-7fc7c480-339a-11ea-8ff3-e2402cbc9807.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/21029639/72172335-85250f00-339a-11ea-9f17-98bb439cbe12.png">


Note that two debuggers are running.

**Comment by roblourens** [comment]
I think that's because two processes have been spawned. Those numbers are the process IDs. I think that mocha spawns a child process to run tests. You could verify by checking what those PIDs are. But I don't think there is an issue here.

**Comment by chasingSublimity** [comment]
If i restart my machine, only one debugger attaches. The behavior is indeterminate, unfortunately. :/ 

What info would i need to provide in order for this to be considered an issue?

Thanks!

**Comment by roblourens** [comment]
Try just figuring out what the processes with those PIDs are, like `ps -ax | grep <pid>` for example. Or evaluate code in them through the debug console, like seeing `process.argv` might help.
