### ISSUE TITLE
JS / TS features constantly failing

### ISSUE THREAD

**Issue by roderickfung** [microsoft/vscode#88435]
Issue Type: <b>Bug</b>

• create a new unsaved file,
• paste typescript block of code
• edit/write javascript/typescript code

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 4|
|Memory (System)|16.00GB (3.16GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.0.12
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
vscode-language-babel|mgm|0.0.25
mssql|ms-|1.8.0
atom-keybindings|ms-|3.0.6
debugger-for-chrome|msj|4.12.4
ruby|reb|0.26.0
haml|vay|1.0.1
vscode-icons|vsc|9.7.0
vscode-ruby|win|0.26.0

</details>

**Comment by connor4312** [comment]
Can you provide information about the error you see and [server logs](https://github.com/microsoft/TypeScript/wiki/Getting-logs-from-TS-Server-in-VS-Code)?
