### ISSUE TITLE
Optional chaining in plain JS ignores jsconfig.json

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#88439]
Version: 1.42.0-insider (user setup)
Commit: 7e64866a703c83dcdd3b84a8b48dd1673895fb7d
Date: 2020-01-09T05:41:05.676Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a plain JS project with no Babel
2. Set the target in jsconfig.json to "es6"
3. Create a "maybe undefined" JSDOC typedef for an object variable
4. Vscode will always use `?.` when trying to access properties

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Set `"javascript.suggest.includeAutomaticOptionalChainCompletions": false` in VS Code to disable this

We don't base this on `target` as you can use `tsc` on that jsconfig to compile optional chaining down to es6 compatible code

**Comment by pocesar** [comment]
but for plain JS, would be interesting as a feature then. TS is my primary language, but sometimes you'll be dealing with those plain JS files with proper typedefs
