### ISSUE TITLE
Package.json confused with different file in git

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88437]
- In https://github.com/microsoft/vscode-chrome-debug
- Open changelog.md and package.json, make changes
- Click both files in the SCM viewlet
- Now there is an error in the problems panel for package.json, but when I click it, it shows changelog.md

![image](https://user-images.githubusercontent.com/323878/72172559-543cde00-338a-11ea-9663-ab440eebf3a0.png)

- And the language mode for that file is "JSON" when it is definitely not a json file

Also reproes in 1.41

**Comment by usernamehw** [comment]
Duplicate of #88250. Or #88250 is a duplicate of this.

**Comment by mkoflerAT** [comment]
I'm glad to see someone else has the same problem like I do. It is driving me nuts. I assume, but I'm not entirely sure, that it has to do something with hyperlinks in combination with anchors or special chars in the headlines - like you have "4.12.5" within your h2-headline. Initially the issue appeared first time when I had a repository with a markdown h1-headline named "razorpages-3.1.100-template".
Can someone look into this?

**Comment by roblourens** [comment]
Oh interesting, I will close in favor of that issue.
