### ISSUE TITLE
Way to exclude TextEdits from undo history or reset undo history

### ISSUE THREAD

**Issue by Friday32** [microsoft/vscode#88438]
In my extension,  I modify the document using vscode.TextEdits.  These edits wind up in the undo history. The internal action should not be undone or redone when the user presses Ctrl-Z or Ctrl-R.

I can foresee issues with trying to implement a exclude feature, so I'd at least like the ability to clear the undo history?

**Comment by connor4312** [comment]
Does setting the `undoStopBefore` and `undoStopAfter` in the `edit` call do what you need?

/needsMoreInfo

**Comment by Friday32** [comment]
The extension is using workspace.applyedit().    The options undoStopBefore and undoStopAfter are available for TextEditor.edit().  I don't recall if that function was available when the extensions was created. But, it would be nice to have the same capability for all functions.
