### ISSUE TITLE
VS code forcing itself open with cli.js file

### ISSUE THREAD

**Issue by NerdPractitioner** [microsoft/vscode#88432]
Same issue as here https://github.com/Microsoft/vscode/issues/69373 but was closed before answered. VS Code keeps automatically opening a file called "cli.js"

**Comment by connor4312** [comment]
Can you follow the steps from https://github.com/microsoft/vscode/issues/69373#issuecomment-467589865 to get more info for us? Thanks!

/needsMoreInfo

**Comment by NerdPractitioner** [comment]
Yes I can, I downloaded the software you referred to. I'm not sure what information you want though, it just showed that vs code was open

**Comment by connor4312** [comment]
Can you show the command line arguments of all Code.exe processes?
