### ISSUE TITLE
Create command for find in selection and add default keybinding

### ISSUE THREAD

**Issue by tbfleming** [Microsoft/vscode#8843]
- VSCode Version: Insiders
- OS Version: Windows 10

actions.find and editor.action.startFindReplaceAction no longer find in selection without having to click an extra button (#8787). The Find in Selection button doesn't have a keyboard shortcut.

I frequently replace in selections. Ideally:
- Select text
- Hit a keyboard shortcut bound to a new command
- The Find in Selection button is already enabled

Also, it would be nice if all buttons and fields in the find dialog could be bound to keyboard shortcuts.

**Comment by tbfleming** [comment]
After looking closer, the Find in Selection button is the only thing in the dialog without a shortcut

**Comment by dilijev** [comment]
@tbfleming thanks for opening this :)

**Comment by bgashler1** [comment]
@tbfleming what if we instead had a setting that, if enabled, would always find within a selection by default?  That way you can still use the same keyboard shortcut you use today for Find/Replace.

**Comment by bgashler1** [comment]
See https://github.com/Microsoft/vscode/issues/12109#issuecomment-259003638 for background on why we changed the default behavior of Find/Replace to not be scoped by default to a selection.

**Comment by tbfleming** [comment]
As long as there's an easy way for me to switch between find selected and find in selected (e.g. whether it's multiline or not), then a setting will be nice.

**Comment by mylowillem** [comment]
The change to the default behavior is extremely annoying. Find in selection by default is what users from a Visual Studio / Windows background expect. I suspect users with an OSX background prefer it to be off by default.  Please add a setting for this, and I recommend turning find in selection on by default on Windows and off by default for OSX.

**Comment by tbfleming** [comment]
@mylowillem may be right. It's been odd seeing people complain about behavior that I expect.

**Comment by jasonterando** [comment]
By far, this is the biggest frustration I have with VS Code (which is a great product).  If I have text selected, it is setting a context of scope, and that scope should be respected on any command executed (including search or search/replace).

> @Bill-Stewart we needed to remove the default find in selection behavior due to it being easy to misunderstand what was going on when no results were showing up for some users.

I see this more as a problem with "flat" or minimalist UI than a behavioral issue.  The behavior needs to be reverted to work just like the vast majority of code editors out there.  To mitigate the risk of confusion, perhaps use something other than a "left justify" icon to indicate whole word search.  More contrast in the "down" mode for buttons that behave like checkboxes may help as well.

**Comment by rebornix** [comment]
Let's track the setting persistence in #6158

**Comment by tbfleming** [comment]
How is this related to persistence? I sometimes need to replace in selection and sometimes not. Switching between them right now is painful.

**Comment by rebornix** [comment]
@tbfleming First of all, speaking of your pain, I already added a command to toggle *Find in selection*. #6158 is about setting persistence as some users may want to have their default value for these settings. I commented here to help others know where to find that if they happen to jump into this issue. Sorry for the misleading and let me know if the newly added command helps you out.

**Comment by tbfleming** [comment]
Thanks. What is the command? I just tried searching for in Keyboard Shortcuts but don't see it (Insiders build)

**Comment by rebornix** [comment]
@tbfleming we don't release Insider on weekends, with today's insider, you can toggle it by cmd+alt+l

**Comment by tbfleming** [comment]
@rebornix I just updated and checked again. I tried searching for "selection" in Keyboard Shortcuts, but it's not there. I use Windows, which doesn't have a cmd key.

**Comment by rebornix** [comment]
@tbfleming can you try search `toggleSearchScope` in Keybinding?

**Comment by tbfleming** [comment]
Found it. Alt+L. These made it hard to find:

* The name toggleSearchScope has no resemblance to the button's hover text ("Find in selection")
* The button's hover text doesn't show the shortcut like the other buttons do

**Comment by rebornix** [comment]
@tbfleming you are right, I'll fix these you issues you mentioned. Thanks!

**Comment by tbfleming** [comment]
Thanks for adding the shortcut!

**Comment by rebornix** [comment]
@tbfleming from tomorrow's insider, you should be the shortcut in the hover text and the command will be called `toggleFindInSelection`

**Comment by toxic-johann** [comment]
I am using mac OS.
And i want to find in selection.
I follow the issue and find that i have to use mouse to finish this job.
@tbfleming found the key on windows.
But in mac OS, it seems it do not work.
Are there any global setting about this.
Because in sublime, i can set this easily.
