### ISSUE TITLE
Show indicator that setting is not synced

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88448]
https://github.com/microsoft/vscode/issues/84431

I added an action to the setting dropdown to let a user exclude that setting from settings sync. It is checked when it is excluded. But it might be useful to also have some indicator next to the setting name, that it is not synced? I am not sure whether people need this or not but it could be a nice reassurance when someone is editing a setting, that it will stay local.

What do you think? Is there an icon that describes something not being synced? @sandy081 @misolori

**Comment by sandy081** [comment]
I think it is also useful to have a search query to show ignored settings.

**Comment by misolori** [comment]
We could do have `eye-closed` that we could use:

![image](https://user-images.githubusercontent.com/35271042/72832590-05b8fa80-3c3a-11ea-8cb7-5e47c98f610d.png)

![image](https://user-images.githubusercontent.com/35271042/72832755-5d576600-3c3a-11ea-8d50-660b865fa12c.png)

And extensions can use it as well:

![image](https://user-images.githubusercontent.com/35271042/72832770-634d4700-3c3a-11ea-9c7c-2f5cf4b84487.png)

**Comment by roblourens** [comment]
I like that!

**Comment by roblourens** [comment]
We did this...
