### ISSUE TITLE
Cannot enter Assignee when Creating Issue

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#88442]
Issue Type: <b>Bug</b>

1. Create issue and fill in
2. Assignee is required. (On our install it is defaulted)
3. Cannot type
![image](https://user-images.githubusercontent.com/20051/72179068-1b583580-3399-11ea-933e-038be375b1d5.png)

Extension version: 2.2.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

**Comment by connor4312** [comment]
Please open this isse on the Jira extension repo.

/causedByExtension

**Comment by gjsjohnmurray** [comment]
I think you reported this issue against an extension (version 2.2.1) whose repo isn't on GitHub. See #73515 for an explanation of the consequence, which is that your issue gets opened here. Please raise it with the extension developers and close this one.
