### ISSUE TITLE
Add multi command support in key binding. 

### ISSUE THREAD

**Issue by nurmohammed840** [microsoft/vscode#88444]
Like...
` "command" : [ "editor.action.insertSnippet" , "deleteWordLeft" ]`
or...
` "command" :  " editor.action.insertSnippet && deleteWordLeft " `

**Comment by ArturoDent** [comment]
It seems unlikely that macro support would be added anytime soon - there are extensions that will do it already.  Like multi-command (perhaps you are aware of it?) and others.
