### ISSUE TITLE
PHP Syntax Highlighting of instanceof keyword and class name

### ISSUE THREAD

**Issue by KaduAmaral** [microsoft/vscode#88441]
- VSCode Version: 1.42.0-insider
- OS Version: Ubuntu 18

```
Version: 1.42.0-insider
Commit: 960cddb992cc96d47f56b633b361909f1b5b3353
Date: 2020-01-10T06:48:04.971Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.0.0-37-generic
```

Steps to Reproduce:

1. Create a new php file
2. Write the folowing code:

```php
<?php

class Foo {};

$a = new Foo;

if ($a instanceof Foo) {
    print 'Is foo';
} else {
    print 'Is not foo';
}
```

The keyword instanceof and the class name is not colored:

![image](https://user-images.githubusercontent.com/4316607/72178621-093ebd00-33c2-11ea-9ff1-bd21944309d2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by oneslash** [comment]
Looks like it is related to the theme, if I change to Monokai, it is highlithed


![image](https://user-images.githubusercontent.com/15870134/72279100-b1a88780-3635-11ea-8749-8d34eaeae217.png)

**Comment by roblourens** [comment]
Yeah, it's missing from the Dark theme. I assume it's a regression, because this is very obvious and I think I would have noticed it earlier...

**Comment by connor4312** [comment]
This appears to still be present--on dark the foreground color is the default `meta.embedded`:

![](https://memes.peet.io/img/20-04-6fa3294c-cac0-4f69-bafb-fdd94479895a.png)

**Comment by roblourens** [comment]
I think that's the expected behavior in "Dark", not "Dark+", which are you using?

**Comment by connor4312** [comment]
that's Dark, Dark+ is

![](https://memes.peet.io/img/20-04-86803856-97f2-4075-9623-cf4172f729b7.png)

**Comment by roblourens** [comment]
Yeah that's expected, that type just doesn't have a color in Dark. Why do we even still ship Dark? I don't really know.
