### ISSUE TITLE
Typing in Find field disables Find In Selection button

### ISSUE THREAD

**Issue by tbfleming** [Microsoft/vscode#8844]
- VSCode Version: Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Select text
2. ctrl+f
3. Type in text to find
4. Try to click Find In Selection button

![animation](https://cloud.githubusercontent.com/assets/418464/16661372/9f9707aa-4440-11e6-853f-16b91f6d9e8e.gif)

**Comment by isidorn** [comment]
Works for me in latest insiders. Let me know if you still see it and I will re-open
