### ISSUE TITLE
Difficulties during directory, file creation

### ISSUE THREAD

**Issue by AmalPrakash** [microsoft/vscode#88445]
Issue Type: <b>Bug</b>

<b>Issue</b> : Maybe it is developer friendly, but not really as user friendly as the other features. Selection of directories to create a new file is a tedious task in vscode. Please look into the issue and discuss with concerning testers.. 

<b>Solution</b> : new file/ new folder option on the top of each folder.. 

yours sincerely, 
<i>Amal Prakash<i>

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
kotlin|fwc|0.2.11
python|ms-|2020.1.57204
cpptools|ms-|0.26.2
java|red|0.54.2
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.7.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.2

</details>

**Comment by connor4312** [comment]
Hi, if this is a bug, please provide reproduction steps. Otherwise, please describe in greater detail the difficulty you're facing and solutions you'd like to see.

/needsMoreInfo
