### ISSUE TITLE
TMPDIR setting and and trimming trailing whitespace

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#88447]
Happened to find if the environment variable "TMPDIR" is not set correctly or not accessible, the whitespace will not be trimmed when saving a file.

It's OK but I wonder if this kind of requirement is documented somewhere?

I am using the latest insider version and CentOS 7.4.

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Can you provide more details reproduction steps and see if it happens without extensions set? I'm unable to repro on my machine.

**Comment by sweettyler** [comment]
@connor4312 
To reproduce:
1) create a shell script containing the following 3 lines (my default shell is C Shell):
#!bin/csh -f
#I assume here the following path doesn't exist or is not accessible
setenv TMPDIR /local1/data/tmp
2) source the script you just created in step 1);
3) launch vscode and open an existing file;
4) add a whilespace at the end of a line and then press "ctrl+s" to save it.
5) check if the whitespace you added in step 4) is removed or not;

**Comment by connor4312** [comment]
Interesting, looks like we fail somewhat silently trying to create an ipc socket.

[Verbose log](https://gist.github.com/connor4312/ee0204e8310f319d5fc98a9238dda6a2)

**Comment by joaomoreno** [comment]
Please do not provide a non existent TMPDIR. This is user error.
