### ISSUE TITLE
Rename window of vscode instances

### ISSUE THREAD

**Issue by cpagravel** [microsoft/vscode#88446]
I often work on multiple projects at the same time and it's very easy to lose track of which instance is for what. For example, see photo below.

![image](https://user-images.githubusercontent.com/9516565/72181919-37f76c00-339f-11ea-9aa7-058ef1f8b753.png)

It would be nice if I could rename the windows instead of the windows being named whatever file is opened.

**Comment by IllusionMH** [comment]
/question

You can use `window.title` setting on Workspace level. Add it to `.vscode/settings.json`
