### ISSUE TITLE
Indentation Disappears on New Lines

### ISSUE THREAD

**Issue by eddcgarcia** [microsoft/vscode#88450]
![vscode-tab-disappears](https://user-images.githubusercontent.com/58670498/72187213-e6091300-33ab-11ea-9e87-65f42a311038.gif)

[Indentation Disappears On Tab](https://imgur.com/a/buqotb3)

- VSCode Version: 1.41.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Put text on a new line. We'll call this line X.
2. On a new line before line X, use the tab key to indent.
3. On a new line after line X, use the tab key to indent. The indent on line X-1 disappears. 

Example:
```
\n
This is line X.
\n
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by eddcgarcia** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [VS Code changes indention of current line (#61510)](https://www.github.com/microsoft/vscode/issues/61510)

This issue is different from the linked issue.

**Comment by ArturoDent** [comment]
The setting "Editor: Trim Auto Whitespace" default setting is `true` so check to see if setting it to `false` is your preference.

**Comment by connor4312** [comment]
Check on what Arturo mentioned and let us know if that solves your issue 🙂 

/needsMoreInfo

**Comment by eddcgarcia** [comment]
Thank you, disabling Trim Auto Whitespace in the settings fixed the issue.
