### ISSUE TITLE
Selected text is not always used for search in files

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#88452]
Issue Type: <b>Bug</b>

I recently found myself having to replace a lot of SASS variable names in a project. As such, I extensively had to use to search/replace in files tool.

I noticed that it would often *not* use the text selected in the editor as source for the "find" field.

I think it can be reproduced as follows:

1. Select a text to replace, e.g. `foo`
2. Activate shortcut to find & replace in files (e.g. CMD-SHIFT-H)
3. Observe that the selected text `foo` appears in the find field as expected
4. Make a replacement based on this selection
5. Directly afterwards, select another text in the editor, e.g. `bar` (select directly with mouse, without first clicking in the editor and selecting with keyboard)
6. Activate shortcut again (CMD-SHIFT-H)
7. The find field in the search *momenterily* blinks to `bar` before reverting to `foo` again for reasons unknown.

Expected: for it to switch to `bar` and remain on `bar`

Note: I can't reproduce it 100% of the time, but it's frequent enough to be noticable if you try it a few times. I've generated a gif to illustrate the problem. Sorry for the low framerate. I tried to re-record it with another tool but then of course the bug didn't happen.

![find issue](https://user-images.githubusercontent.com/490562/72187437-874fa200-345c-11ea-9a54-12ade08c4487.gif)

VS Code version: Code - Insiders 1.42.0-insider (629a08ed6231d7af269ae61a5cc610490d1f7f5d, 2020-01-07T05:27:40.075Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|-psn_0_6604364|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.9.1
vscode-eslint|dba|2.0.13
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
file-icons|fil|1.0.20
gc-excelviewer|Gra|2.1.32
name-that-color|gui|0.1.2
json2csv|kha|0.0.1
l13-diff|L13|0.21.0
git-tree-compare|let|1.7.1
vetur|oct|0.22.6
multi-command|ryu|1.3.0
vscode-fileutils|sle|3.0.0
control-snippets|svi|1.7.1
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.9.6
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by adamreisnz** [comment]
I suspect it may only be happening with global clipboard enabled.

**Comment by roblourens** [comment]
I can't repro this, even with global clipboard enabled. Is this still happening?

**Comment by adamreisnz** [comment]
Did you enable global clipboard for both find and search in files?
They both need to be enabled.

My desire is for the find in files & search clipboards to just be shared. I don't care if they are global or not, I just don't want to search for something in files, and then have to re-type it to find all the occurrences of that same text in a specific file.

I don't know if it's still happening because I disabled it as it was driving me nuts, and I since went back to "regular" VS Code because Insiders was shipping with too many issues.

**Comment by roblourens** [comment]
I can't repro exactly that, but I see something which is probably related

- Focus the editor
- Do a search for "abc" in Sublime
- Highlight text "foo" in the vscode editor, and press cmd+shift+h
- Instead of using "foo" from the editor, it takes the text "abc" from the global find clipboard

This came with the "search on type" feature but really this is because the implementation of the whole "global clipboard" feature is questionable to me.

I pushed a fix, but since we are stabilizing the Insiders build for release, it won't be in Insiders builds for a few days.

**Comment by adamreisnz** [comment]
Yes as I wrote above, I would ditch the global clipboard and instead have an option to simply have a shared clipboard between the find and search in file fields.

**Comment by roblourens** [comment]
Unfortunately we can't do it that way, we don't even share the find text between two instances of the find widget.

**Comment by adamreisnz** [comment]
Yes, that's a pity though. Is that a conscious design decision, or just a technical limitation of the current approach?

The thing is you will often want to find a certain text/query globally, and then go over the instances in a specific file where it's used, maybe make modifications as needed. When viewing search results from the find in files output, all you see is the one line of code and not the surrounding context, so that alone doesn't cut it.

Without a shared clipboard, and as you say not even between two instances of the find widget, you have to re-enter the text you're searching for in every single file edit window you open. When you're making by-hand replacements for multiple files that quickly gets old.

I will try enabling global clipboard again once those fixes are out.

**Comment by roblourens** [comment]
You might also be interested in the "search editor" preview that we currently have in Insiders.

This is a new search UX that can show you surrounding context of matches.
