### ISSUE TITLE
Editor layout not preserved on restart

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#8846]
- VSCode Version: 1.3.0 Stable
- OS Version: Windows 10

Steps to Reproduce:

1. open a markdown file
2. right click on the tab, open preview
3. drag preview to the right to create a second editor well
4. restart VS Code

Result: the markdown preview is not opened and i only have one editor well

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/7780
