### ISSUE TITLE
DAP runInTerminalRequest does not have a process ID the first time a terminal is launched

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#88460]
I didn't see this happening before, but I was running into an issue this week. It seems like the first runInTerminal request we send over DAP only gives us the shell rather than the process ID of the one we launched. I made a speculative commit on a branch to make this better, but it'd be really nice if we could get the true process ID. Commit with more details: https://github.com/microsoft/vscode-js-debug/commit/8e077889c6271a1b5fa23aab17f8dc13dfb400c8

Debug behavior without this change, notice the first launch getting terminated prematurely:

![Kapture 2020-01-10 at 16 04 41](https://user-images.githubusercontent.com/2230985/72194576-f8db1200-33c2-11ea-9bfa-7f0ce7fa900f.gif)

**Comment by Tyriar** [comment]
@connor4312 it might be good for us to sit together to debug this, likely the problem line:

https://github.com/microsoft/vscode/blob/76c72ffc947fa8dfe9180409f3b204541e05b10b/src/vs/workbench/api/node/extHostDebugService.ts#L110
