### ISSUE TITLE
user settings workbanch.colorCustomizations statusBar.background color

### ISSUE THREAD

**Issue by shepelevstas** [microsoft/vscode#88476]
Issue Type: <b>Bug</b>

statusBar.background color setting is ignored

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3516)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (2.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
numbered-bookmarks|ale|6.2.1
vscode-npm-script|eg2|0.3.10
sftp|lix|1.12.9
python|ms-|2020.1.57204
ide-purescript|nwo|0.20.8
language-purescript|nwo|0.2.2
vetur|oct|0.22.6
dumb-copy-paste|she|1.0.1
sass-indented|syl|1.7.3
ayu|tea|0.18.0
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

![Untitled](https://user-images.githubusercontent.com/14919836/72200380-60ed2f00-347b-11ea-960d-d75d9d5acced.png)

**Comment by connor4312** [comment]
Does this reproduce with all extensions disabled? It may be related to the material theme, in which case I'd recommend opening an issue on their repo.

/needsMoreInfo

**Comment by shepelevstas** [comment]
Somehow it's back to normal after opening a folder from command line with "code .", while "File -> New Window" didn't help. Now I can not reproduce it.

**Comment by connor4312** [comment]
Okay, let us know if it occurs again or you're able to find repro steps

/cannotReproduce
