### ISSUE TITLE
Checkout git branch does not reload open file contents

### ISSUE THREAD

**Issue by famichiki** [microsoft/vscode#88472]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open file in a local git repository
2. Checkout another branch
3. Wait for progress clock to disappear from Source Control icon 
4. Observe that file contents are not updated/reloaded/refreshed
5. Make VS Code window inactive, click on desktop etc
6. Click back onto VS Code window to activate it
7. All opened file(s) contents will now be reloaded from the branch

If you have multiple tabs open clicking between them will reload all tabs the same as deactivating/activating the window.

However, if you have different tabs open in a split view clicking between those visible tabs will not trigger a reload.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
