### ISSUE TITLE
Hanging a lot with PowerShell Core debugging

### ISSUE THREAD

**Issue by sanket-t-shah** [microsoft/vscode#88477]
Issue Type: <b>Bug</b>

Whenever I work with PowerShell Core script, VS Code hangs a lot and asks for restart.

This is reproducible on Windows 10 Version 1909 - 64 bit with PowerShell Core 6.2 installed.

Am using PowerShell integrated console for debugging purpose.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.0.0
vsc-material-theme-icons|equ|1.1.2
terraform|mau|1.4.0
vscode-azurefunctions|ms-|0.20.1
vscode-azureterraform|ms-|0.3.0
vscode-docker|ms-|0.9.0
python|ms-|2020.1.57204
remote-wsl|ms-|0.41.7
azure-account|ms-|0.8.8
azurecli|ms-|0.4.6
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
azurerm-vscode-tools|msa|0.8.3
docker-compose|p1c|0.3.5
azure-event-hub-explorer|Sum|0.1.2

(2 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Can you please go through the terminal issue guide to provide us more info? Thanks! https://github.com/microsoft/vscode/wiki/Terminal-Issues

/needsMoreInfo

**Comment by sanket-t-shah** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

Added information and updated description.
