### ISSUE TITLE
Go back and forward jumps crossing different views if i open the same file in the second view

### ISSUE THREAD

**Issue by liesauer** [microsoft/vscode#88470]
- VSCode Version:
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

Steps to Reproduce:

1. see the gif
![333](https://user-images.githubusercontent.com/8676741/72197789-5e311080-3460-11ea-9c6a-d31d675e24de.gif)

each view should be independent/isolated, jumping to another view is not right, should be jump back to `a.ts` which is in my current active view, not my second view.

Does this issue occur when all extensions are disabled?: Yes

**Comment by liesauer** [comment]
little test case uploaded
[test.zip](https://github.com/microsoft/vscode/files/4048900/test.zip)

**Comment by connor4312** [comment]
Perhaps a setting here would be appropriate

**Comment by jrieken** [comment]
The setting is called  `workbench.editor.revealIfOpen` :-)

**Comment by liesauer** [comment]
@jrieken it is disabled, but this doesn't work.
![image](https://user-images.githubusercontent.com/8676741/72241137-05f53c80-3621-11ea-84b0-6614d083dd03.png)

**Comment by liesauer** [comment]
and i have never set "force open in a group" or something like that, so it this a bug?

**Comment by jrieken** [comment]
Oh, now I understand. Your issue isn't about going to a symbol but about going back from it. For the future, please write better steps

**Comment by liesauer** [comment]
> Oh, now I understand. Your issue isn't about going to a symbol but about going back from it. For the future, please write better steps

right, sorry about the unclear description
