### ISSUE TITLE
Extensions Last Updated Status

### ISSUE THREAD

**Issue by hl2guide** [microsoft/vscode#88474]
Please consider adding the ability to tell when an extension was last updated.

e.g. (added text in green)

![example](https://user-images.githubusercontent.com/17044982/72199072-abc27300-348a-11ea-8b3a-0df857f147cd.PNG)

It would also be useful if the extension sidebar list could be sorted by "Last Updated" and that the command palette had an "Extensions: Recently Updated" command that shows a list of the most recently updated.

Cheers,
- Dean

**Comment by sandy081** [comment]
/duplicate

#70736
