### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by sethmichel** [microsoft/vscode#88478]
Issue Type: Performance Issue

I've been doing a project in python and the latest version of kivy. No issues for about 2 weeks then randomly, on I think 1/8/20 or 1/9/20, when I opened vs code my cpu shot to 100% usage and stays there. Two days later it's still doing it while the computer is idle, no code is running, no other apps are open on my computer. Longest I've left it idle is around 15 minutes, no changes, still 100% usage. 

Also, when I close vs code: vs code and 2 python processes partly stay active and, combined, use 50%-70% of my cpu. In order to stop those 3 things, I have to "end task" on each of them in task manager

I saw on vs code's website a note to try and enter "**/largefolder" under files.exclude, but that also did nothing. I switched to pycharm and that works just fine, but I much prefer vs code

Link to a screenshot of my task manager (flickr.com, I don't know where to put a screenshot on github) https://www.flickr.com/photos/186413466@N03/49366419057/in/dateposted-public/

VS Code version: Code 1.41.1
OS version: Windows_NT x64 10.0.17763
CPU Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)
Ram: 12GB

GPU Status 2d_canvas: enabled 
flash_3d: enabledflash_stage3d: enabled 
flash_stage3d_baseline: enabled 
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_renderer: disabled_off
surface_control: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off
webgl: enabled<br>webgl2: enabled

Extensions (5)

kivy-vscode|Bat|0.5.3
sml|fre|0.0.18
teste|ign|2.1.2
python|ms-|2020.1.57204
powershell|ms-|2019.12.0
(1 theme extensions excluded)

**Comment by connor4312** [comment]
Does this reproduce with all extensions disabled? If not, it's likely related to the Python extension, so we'd recommend you open an issue on their repo.

/needsMoreInfo

**Comment by sethmichel** [comment]
Update, I uninstalled the powershell extension which lowered cpu usage to usually around 60 - 70%. However, task manager still says 2 python processes are running after I close vs code so my cpu stays at 70% until I end those processes. That's fine for me for now
