### ISSUE TITLE
Keyboard shortcut chords can be quietly overridden

### ISSUE THREAD

**Issue by derekyle** [microsoft/vscode#88488]
Issue Type: <b>Bug</b>

I had an issue where none of my keyboard shortcut chords that started with Ctrl + K worked correctly. I finally discovered that it was because I had an extension that was triggered with Ctrl + K alone. The extension action was context dependent so it would never trigger and tip me off to the problem. 

Allowing the first part of a chord to be set to an action negates all other chords that start with that combo. So it seems that vs code should warn or not allow this. I finally solved it by manually searching through all the shortcuts with ctrl + k in them and found the one that was just ctrl + k by itself and removed.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>

</details>

**Comment by alexdima** [comment]
I can see how this is highly annoying. But please create an issue against the extension. It is bad practice for an extension to ship with a keybinding which overrides tens of chords.

As far as VS Code goes, this is as designed. All the default VS Code keybindings can be overwritten from extensions. In fact, that is how the VS Code keymap extensions work, they change tens and hundreds of default keybindings, including chords, etc.

In this specific case, you did the perfect thing, you searched for "Ctrl+K" in the keybindings UI and found the culprit. Please create an issue against the extension.

**Comment by derekyle** [comment]
The extension didn't create the keybinding. I created it myself, not
knowing at the time that Ctrl K was commonly used in chords.

I opened the issue on vs code because it seems that the vs code UI should
warn when a bunch of chords are going to be rendered inaccessible.

**Comment by alexdima** [comment]
@sandy081 In this case, when using `cmd+k` I see that we show "1 existing command..." but it should show a lot larger number, to include all the chords at cmd+k as well:

![Kapture 2020-01-20 at 21 32 30](https://user-images.githubusercontent.com/5047891/72756155-acff4880-3bcc-11ea-8a7d-281076d3378b.gif)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/88122
