### ISSUE TITLE
All files get deleted after file rename

### ISSUE THREAD

**Issue by agrawal-d** [microsoft/vscode#88482]
All source code gets deleted ( except .git folder )  on renaming a file in a workspace

- VSCode Version:1.41.1
- OS Version:Ubuntu 19.10

Steps to Reproduce:

1. Open any folder in workspace
2. Rename any file ( I changed a file extension ) 

Does this issue occur when all extensions are disabled?: Cant say

I am unable to reproduce this error, with or without extensions disabled. This is the first time it has happened.

This is exactly what happened : https://github.com/Microsoft/vscode/issues/69828#issuecomment-469732219

> It  happens when you rename the file back to the same name that had been used before you recently renamed ...

I lost all my uncommited changes :-(

**Comment by agrawal-d** [comment]
Issue #46371 was closed, so I have created a new issue

**Comment by agrawal-d** [comment]
Not an extension issue

**Comment by bpasero** [comment]
@agrawal-d sorry to hear that. To clarify, you said:

> I am unable to reproduce this error, with or without extensions disabled. This is the first time it has happened.

Does this mean you are not able to come up with steps how to reproduce yourself?

**Comment by agrawal-d** [comment]
I have not had much time to investigate on how to reproduce the issue, but I will try it today and update here.

Here is what originally caused the deletion:
1. Rename `file.js` to `file.js.old`
2. Do something else for a few minutes in VS Code.
3. Rename it again to `file.js`
4. Suddenly, everything gets deleted ( except .git folder).

All renames were made from the side bar (explorer) in VS Code.

**Comment by bpasero** [comment]
Yeah please try to reproduce and be exact about the steps. E.g. is the file dirty? And when you say everything gets deleted except .git folder, what does that mean exactly?

**Comment by agrawal-d** [comment]
It means that in the folder that was open VS Code, after renaming, all files and folders except the `.git` folder got deleted.

I was able to do `git checkout master` to restore commited changes.

Also, I was able to recover the files using a data recovery tool. So I think only file system entries were deleted, and it was not a complete "wipe".

**Comment by bpasero** [comment]
@agrawal-d to clarify, you renamed a single file from the VSCode explorer and all files and folders were removed? Or did you rename a folder?

**Comment by agrawal-d** [comment]
I renamed a single file from VS Code explorer.

**Comment by bpasero** [comment]
Ok, then I would need exact steps how to reproduce, possibly with a sample workspace. I cannot see how renaming a file would result in this from VSCode itself.

**Comment by agrawal-d** [comment]
I am unable to reproduce the bug. Probably the deletion was caused by something else.
