### ISSUE TITLE
Unable to install extensions due to certificates

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode#88489]
Issue Type: <b>Bug</b>

1. Install either mssql or intellisense extensions
2. Receive an error "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"

e.g.   (happens with both mssql and intellicode installs)

> 
> Platform: win32, x86_64 (Windows)
> 
> Installing SQL tools service to c:\Users\BRITTG2.vscode\extensions\ms-mssql.mssql-1.8.0\sqltoolsservice\1.8.0\Windows. Downloading https://download.microsoft.com/download/e/7/8/e781cf8f-9c3f-4ad5-bd0c-f3c62b8bc6bd/microsoft.sqltools.servicelayer-win-x64-netcoreapp2.2.zip [ERROR] Error: Request error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
> 

Note: I am behind a corp fw.  FWIW I tried the suggestion here:  [Network Connections in Visual Studio Code](https://code.visualstudio.com/docs/setup/network)

where it says, in part: 

> If all else fails, you can tell VS Code to ignore all certificate errors using the --ignore-certificate-errors command-line flag. Warning: This is dangerous and not recommended, since it opens the door to security issues.

However, that is an _invalid flag_ :

```
> code --ignore-certificate-errors
Option 'ignore-certificate-errors' is unknown. Ignoring.
```

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.13
gitlens|eam|10.2.0
code-runner|for|0.9.15
gc-excelviewer|Gra|2.1.32
mssql|ms-|1.8.0
python|ms-|2020.1.57204
powershell|ms-|2019.12.0
partial-diff|ryu|1.4.0
vscode-hexdump|sle|1.7.2

</details>

**Comment by connor4312** [comment]
This is a feature specific to the mssql tools, please open an issue on [their repo](https://github.com/microsoft/vscode-mssql)

/causedByExtension
