### ISSUE TITLE
i want to get all my cods from any place

### ISSUE THREAD

**Issue by ahmedibrahimhassan654** [microsoft/vscode#88486]
in post man i register for account and from any place i can access to all projects that i created before 
i want the same for vs code register account and sign  in and then get all my projects i worked before
i hope to make this feature it will add fantastic feature  to vs code  
thanks

**Comment by connor4312** [comment]
It sounds like [Visual Studio Online](https://visualstudio.microsoft.com/services/visual-studio-online/) is what you're after.
