### ISSUE TITLE
Empty Lines Not Getting Commented-Out

### ISSUE THREAD

**Issue by FloatingSunfish** [microsoft/vscode#88480]
- VSCode Version: 1.41.1
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Sample code to be commented-out:

```
package com.mycompany.app;

public class MyApp {
    public static void main(String[] args) {
        SayHello();
    }

    static void SayHello() {
        System.out.println("Hello!");
    }
}
```

2. Expected result:

```
// package com.mycompany.app;
// 
// public class MyApp {
//     public static void main(String[] args) {
//         SayHello();
//     }
// 
//     static void SayHello() {
//         System.out.println("Hello!");
//     }
// }
```

3. Actual result:

```
// package com.mycompany.app;

// public class MyApp {
//     public static void main(String[] args) {
//         SayHello();
//     }

//     static void SayHello() {
//         System.out.println("Hello!");
//     }
// }
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
This is working as we intended it--empty lines don't get commented out.

**Comment by FloatingSunfish** [comment]
@connor4312 I'm not going to request that this issue be reopened, but I would like to ask what benefits this gives developers.

When commenting-out lines of code, it helps that empty lines within your selections are commented-out to group commented sections together.

This makes it clear which lines need to be uncommented together when developers want to put them back.

Compare:

```
    // line 1
    // line 2
    // 
    // line 3
    // 
    // line 4

    // line 5
    // line 6
    // line 7
    // 
    // line 8
    // line 9
    // 
    // line 10
```

With:

```
    // line 1
    // line 2
    
    // line 3
     
    // line 4

    // line 5
    // line 6
    // line 7
     
    // line 8
    // line 9
     
    // line 10
```

**Comment by FloatingSunfish** [comment]
In case this feature does get implemented, a setting can be added like `"commenting.includeEmptyLines": true` (with a default value of `false`).

This way, those who prefer to exclude empty lines from commenting will be unaffected.

**Comment by sunsp1der** [comment]
This is causing major problems for me. Is there any way I can help make this happen?

**Comment by FloatingSunfish** [comment]
@sunsp1der I think the code's been ready to merge for a while now, but I'm not sure why it hasn't yet.

**Comment by FloatingSunfish** [comment]
@alvintangz, any updates on this issue? 🙂

**Comment by alvintangz** [comment]
@FloatingSunfish you're right, it has been ready to merge for a while. All the CI tests passed and the assignee to the pull request from Microsoft hasn't looked at it.

Unfortunately, since the PR has been open for a while now, the new CI tests just failed. I'll need to fix this as soon as possible (hopefully this weekend) and then I'll mention the assignee in the pull request :shipit:

#93160 

Cheers,
Team DATA - @dharm1k987, @RhymeAccel, @privatejfx141, @jzp128

**Comment by FloatingSunfish** [comment]
@alvintangz Many thanks for the quick reply! We're all thankful for all your hard work!
We look forward to using your feature soon! 😄
