### ISSUE TITLE
File search - include overrides exclude settings

### ISSUE THREAD

**Issue by yoctozepto** [microsoft/vscode#88487]
- VSCode Version: 1.41.1
- OS Version: platform-irrelevant

Steps to Reproduce:

0. Use the search feature from the side pane.
1. Use 'exclude' settings with e.g. .gitignore (for example ignoring doc/build).
2. Add an 'include' of an overlapping pattern (for example include doc/).
3. 'Exclude' is now ignored and all 'include' matching are included despite 'exclude' "in effect".

^ The above does not happen when 'exclude' is added there explicitly - then the evaluation order is correct and files are excluded from 'include' as they should be.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/26574
