### ISSUE TITLE
Find in Files state is not preserved between reloads when in panel

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#88494]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Set `"search.location": "panel"`
2. Open Find in Files and do few searches changing Query, Flags, Include/Exclude
3. Reload window or close/open VS Code
4. Observe that state is reset to one before searches (however <kbd>Alt</kbd>+<kbd>Down</kbd> will bring last query value, but other looks lost)

Works as expected if `"search.location"` is `"sidebar"`.

It might be related to https://github.com/microsoft/vscode/commit/19c07c0c0e8ba16804b6834df3029305f91c100c or be side effect of exception in https://github.com/microsoft/vscode/issues/88461

/cc @JacksonKearl @sbatten

VS Code version: Code - Insiders 1.42.0-insider (960cddb992cc96d47f56b633b361909f1b5b3353, 2020-01-10T05:39:23.171Z)
OS version: Windows_NT x64 10.0.19541

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by JacksonKearl** [comment]
No longer seeing the exception, but still getting the old input. Interesting that Alt+Down works to bring back the input.

**Comment by IllusionMH** [comment]
Is it possible that state is restored from incorrect state after difference in `PANEL_ID` and `VIEW_ID` was introduced?
E.g. State is correctly stored for view and restored for view (because `VIEW_ID === VIEWLET_ID`, and [code like this](https://github.com/microsoft/vscode/blob/a78d0d7b862ca8a8e662df2fe3aa95b6146a112b/src/vs/workbench/contrib/search/browser/searchViewlet.ts#L33)), but will be saved into other place from panel.
