### ISSUE TITLE
Cannot rename folders

### ISSUE THREAD

**Issue by Legends** [microsoft/vscode#88493]
![image](https://user-images.githubusercontent.com/966368/72211391-e51ad300-34ca-11ea-8e89-e4964525b1d2.png)

Steps to Reproduce:

1.Click folder and press F2
2.rename and enter

**The weird thing is, this happens only in the currently opened project and
only with one folder, I can rename others.**

Does this issue occur when all extensions are disabled?: Yes/No
Yes
tried with: `C:\Program Files\Microsoft VS Code>Code.exe --disable-extensions`

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is initial name and new name? Windows have few restrictions for files/folders names.

Can you rename folder in Explorer without problems?

**Comment by Legends** [comment]
name is pages and I rename it to dsfaafs

**Comment by connor4312** [comment]
Can you run vscode with `code --disable-extensions --verbose` to give us additional log information? Thanks!

**Comment by Legends** [comment]
Now it works again..strange. If it appears again, I will try:

`code --disable-extensions --verbose`

closing for now.
