### ISSUE TITLE
Apple requesting update from manufacturer. Can't be opened because Apple can not check it for malicious software

### ISSUE THREAD

**Issue by VickieNelson** [microsoft/vscode#88496]
![Screen Shot 2020-01-11 at 5 38 18 PM](https://user-images.githubusercontent.com/53483150/72211964-d1a34400-3499-11ea-9d82-68ab066e47dc.png)

**Comment by IllusionMH** [comment]
/duplicate of #74782

Please see steps in #74782 (comment) for current workaround.
