### ISSUE TITLE
ES6 class member not showing in Intellisense

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#8849]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new `test.js` file

```js
'use strict';

class TestClass {
  constructor(prop) {
    this.property = prop;
  }

  GetLowerCase() {
    return this.property.toLowerCase();
  }
}

let a = new TestClass('ABC');
```

2. Type `a.` and check the Intellisense - it picks up class methods but not the property, even though a `console.log(a.property)` prints `"ABC"`

![js-intelli](https://cloud.githubusercontent.com/assets/286972/16664215/2182b852-444d-11e6-919e-fdc35034ebe6.PNG)

Contrast this with the same Typescript class.

```ts
class TestClass {
  property: string;

  constructor(prop: string) {
    this.property = prop;
  }

  GetLowerCase() {
    return this.property.toLowerCase();
  }
}

let a = new TestClass('ABC');
```

In TypeScript the Intellisense shows both the class method and the property.

![ts-intelli](https://cloud.githubusercontent.com/assets/286972/16664223/27603862-444d-11e6-87aa-440f3092acff.PNG)

Also, it works properly with the prototypical declaration.

```js
function TestClass(prop) {
  this.property = prop;
}

TestClass.prototype.GetLowerCase = function() {
  return this.property.toLowerCase();
};

let a = new TestClass('ABC');
```

![js-proto-intelli](https://cloud.githubusercontent.com/assets/286972/16664411/e701c8de-444d-11e6-9a62-686e5dc2929e.PNG)

**Comment by dbaeumer** [comment]
Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9599
