### ISSUE TITLE
IntelliSense does not work in react-native project! 

### ISSUE THREAD

**Issue by mironline-net** [microsoft/vscode#88498]
I am working on a very simple expo-react native project.
The IntelliSense works like a charm up to this line : 
`import { createStore } from "redux";`
When I am trying to add `, combineReducer` after `createStore` IntelliSense stops in `loading... mode` and does not work anymore! 

Does this issue occur when all extensions are disabled?: **Yes**

![Capture](https://user-images.githubusercontent.com/54317731/72213434-d4fbf700-34bc-11ea-89b0-75921a857b6a.JPG)

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Once you install that extension and restart VS Code, do you still see the issue?

**Comment by jakobsen9** [comment]
@mjbvz I was experiencing the same problem, and have spent hours to debug this issue. Happy to confirm that your suggestion works! So I guess it's an issue with the built-in TS version.

Thanks!

**Comment by mjbvz** [comment]
Closing as we need more info from the original poster
