### ISSUE TITLE
Emmet: «plus» modifier

### ISSUE THREAD

**Issue by nicothin** [microsoft/vscode#88509]
In other editor (and in Emmet's documentation): `ul+` expand

```
<ul>
  <li></li>
</ul>
```

In VSCode is expand 

```
<ul></ul>
```

I want it to work as described in the emmet documentation.

**Comment by rzhao271** [comment]
The current Emmet doesn't support the snippets ending in `+` anymore, and the Cheat Sheet is out of date. I'll label this as an upstream issue.

**Comment by rzhao271** [comment]
Actually @nicothin the current workaround is to use custom snippets.
https://code.visualstudio.com/docs/editor/emmet#_common-questions
Labelling this as a wontfix since newest Emmet doesn't support these snippets.
