### ISSUE TITLE
Let me configure whether to autocomplete single quotes in comments

### ISSUE THREAD

**Issue by leafje** [Microsoft/vscode#8850]
- VSCode Version: 1.2.1
- OS Version: Windows 8.1

Steps to Reproduce:
1. Create a Python file (really, any language will do, I just happened to be using Python today). Add a commented-out line.
2. Type the word don't. Two apostrophes are inserted instead of one. 

When I'm writing a comment, I'm more often using a single quote as an apostrophe in a word,
rather than writing a string or character literal. If I really want a pair of them in a comment, I'm OK typing two of them. I should be able to configure whether to auto-complete single quotes in comments.

**Comment by rmunn** [comment]
Some other places where single quote doubling should be configurable, as the user's intent is probably to have just one single quote / apostrophe character:

- Inside strings, where contractions like "don't" are far more likely than strings like "Unknown identifier '%s' on line %d". If I need two single quotes in a string, I'm quite happy to type them both.
- Generic type parameters in F#, where `Array<'T>` is an array containing items of type `'T`. The leading single quote means "This is a generic type parameter" in F#. So in F#, if I've typed an angle bracket, I would prefer for single quotes not to be doubled.

The latter example is specific to the language: when writing F#, I'd like to be able to turn off single-quote-doubling inside angle brackets, but when writing other languages I'll want to *keep* single-quote-doubling inside angle brackets.

So I suggest making this behavior configurable by context: the configuration can list a series of contexts where the doubling should be turned off. Maybe the contexts can be names of syntax-highlighting regions, like `"comment"`, or `"fsharp generic-type-parameter"`. (The `generic-type-parameter` syntax-highlighting region doesn't exist right now in the F# syntax highlighter, but it probably will if this feature request gets implemented). Also, the latter suggestion is an "and", not an "or": it should be converted to a CSS selector like `.fsharp.generic-type-parameter`.

**Comment by matthew-a-thomas** [comment]
I can confirm that this behavior is still occurring in 1.4.0 on Windows 7 Enterprise SP1 x64. In my case it's noticeable within JavaScript comments

**Comment by gillez** [comment]
I also see this behaviour and agree that it's annoying.  I am using v1.4.0 with OSX 10.11.5.
It's particularly annoying inside comments.  If I type a comment such as
// this comment shouldn't add an extra apostrophe.
in a JS file, I get an extra single quote at the end of the line that appeared when I typed "shouldn't". 

However, even outside of comments, I agree with rmunn's suggestion that the extra single quote should never be automatically added inside strings.

**Comment by jbsulli** [comment]
Same here for JavaScript. Doesn't make sense to have it automatically insert a second one.

**Comment by senocular** [comment]
+ 1. Version 1.6.1 (primarily JS).  I'm finding all kinds of comments that end in a single quote

```
// TODO: this doesn't clear'
```

**Comment by youneskhouli** [comment]
PLEASE FIX THIS, I have the same problem in python, and it'ts really annoying!!!!! 
I'm using v1.7.1 on windows 10

**Comment by rawling** [comment]
For consistency, it would be nice to be able to configure this for `(`, `{`, `[` too. I note it doesn't happen for `<`.

**Comment by joshkehn** [comment]
Currently—in Python—typing comments or inside a string doesn't cause a second `'` to be inserted. 

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.2|
|django-html|bibhasdn|1.2.0|
|python|donjayamanne|0.5.5|
|gitlens|eamodio|1.4.1|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.9.3|
|preview-vscode|searKing|1.1.1|
|vscode-react-native|vsmobile|0.2.5|

**Comment by leftdevel** [comment]
I'm using VS Code with latest updates as for today 31st May 2017. I'm using PHP, and whenever I type ', I get '' instead.

**Comment by rebornix** [comment]
This is configurable by language extension. I don't see this issue in Python and JavaScript anymore and fixed it for PHP. Let me know if you still see any problem.
