### ISSUE TITLE
md preview width bug

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#88506]
### Env
```
Version: 1.42.0-insider
Commit: 960cddb992cc96d47f56b633b361909f1b5b3353
Date: 2020-01-10T05:35:27.119Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

### Steps to Reproduce:

1. open markdown file
2. open preview
3. open bottom panel

![Screen Shot 2020-01-12 at 10 40 36 AM](https://user-images.githubusercontent.com/7388088/72216360-808e6100-3528-11ea-84af-e2753d2eac78.png)

> PS:
for some reason the image preview is broken too

**Comment by mjbvz** [comment]
I can't repo in 5e758c10c969d668730f036abfc557d9cfb62b87 (the 2020-01-13 build). Are you still seeing this?

**Comment by ctf0** [comment]
```
Version: 1.42.0-insider
Commit: 5e758c10c969d668730f036abfc557d9cfb62b87
Date: 2020-01-13T09:41:37.825Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

reinstalled insider and now the bottom panel is correctly rendering above the md preview, if this is the expected then all good.

**Comment by ctf0** [comment]
btw, giving the bottom panel a `z-index: 1` also fix the issue especially as the webview is at the end of the dom
