### ISSUE TITLE
shift+enter creates new terminal that does not activate base (or other environments)

### ISSUE THREAD

**Issue by smsalaken** [microsoft/vscode#88518]
Type: <b>Bug</b>

Open a python file. Type "import numpy", press shift+enter. This would create a new terminal and will try to activate base environment. This used to work but now hangs and does not finish even after a couple of minutes. However, it stopped working after today (didn't change anything other than restarting VS Code). 

If I create a new terminal from terminal menu and it successfully loads base env. I can import modules by typing but when when I shift+enter a line, it creates a new terminal and hangs.

Anaconda command line shell works as expected.

This is making VS code unusable.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.57204

</details>

**Comment by connor4312** [comment]
Please open an issue on the Python extension repo
