### ISSUE TITLE
I cannot use shift + enter to execute the selected line of code.

### ISSUE THREAD

**Issue by PiPiNam** [microsoft/vscode#88512]
Issue Type: <b>Bug</b>

I cannot use shift + enter to execute the selected line of code. I can only move the cursor to the first line and execute it line by line, very slowly.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (12.03GB free)|
|Process Argv|D:\OneDrive - City University of Hong Kong\CityU学习\机器学习实现\Perceptron.py|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.1.6
vscode-language-pack-zh-hans|MS-|1.41.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.57204
vscode-yaml|red|0.6.1

</details>

**Comment by connor4312** [comment]
Please open an issue on the Python extension for this.

/causedByExtension
