### ISSUE TITLE
Html default snippet not supported.

### ISSUE THREAD

**Issue by roshancom** [microsoft/vscode#88510]
We have(**.html**) fileType where html snippet is not support but other hand (**.htm**) file support all snippet. also no emmet task run.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
