### ISSUE TITLE
VSCode creates a gpu process after it is started with the --disable-gpu option if there is an opening editor.

### ISSUE THREAD

**Issue by JiamingJiao** [microsoft/vscode#88513]
- VSCode Version: 1.40, 1.41, insiders
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Start VSCode with the option `--disable-gpu`. Run command `top -c` in terminal, there is no gpu-process of VSCode.
2. Open a file in VSCode, a process `code --type=gpu-process ...` can be seen in the output of `top -c`

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Related: https://github.com/electron/electron/issues/14273

**Comment by deepak1556** [comment]
Thanks for the report, this is as designed, you can find more information in the issue @connor4312  linked above.
