### ISSUE TITLE
Hard to read overlapping diagnostics

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#88514]
I have 3 errors in this code:

![image](https://user-images.githubusercontent.com/4033249/72221886-03caa980-355f-11ea-996b-e8f324169537.png)

1. `inc`
2. `coun`
3. The whole `<button></button>` line

The problems:

1. I cannot tell how many errors I have on this line
2. If there are overlapping errors, I cannot tell the inner errors' ranges

**Comment by alexdima** [comment]
@octref What do other editors do? Do they render multiple underlines with displaced offsets such that the zig-zag pattern does not overimpose?

**Comment by octref** [comment]
They don't seem to do better. I don't see a clear solution either. One idea is to show something on hover.
