### ISSUE TITLE
Confusing Intellisense

### ISSUE THREAD

**Issue by hua03** [microsoft/vscode#88519]
Issue Type: <b>Bug</b>

The CSS class in the project will be displayed when the Intellisense is displayed

![](https://raw.githubusercontent.com/hua03/image-gallery/master/img/20200113100800.png)

![](https://raw.githubusercontent.com/hua03/image-gallery/master/img/20200113101111.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.46GB (15.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.6.0
project-manager|ale|10.9.1
copy-relative-path|ale|0.0.2
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.0.13
githistory|don|0.4.13
xml|Dot|2.5.0
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
code-runner|for|0.9.15
shell-format|fox|7.0.0
rest-client|hum|0.23.0
path-autocomplete|ion|1.13.3
vscode-autoprefixer|mrm|2.2.0
vscode-scss|mrm|0.8.1
vscode-docker|ms-|0.9.0
vscode-language-pack-zh-hans|MS-|1.41.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.57204
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.7
vscode-remote-extensionpack|ms-|0.19.0
Go|ms-|0.12.0
vsliveshare|ms-|1.0.1456
debugger-for-chrome|msj|4.12.5
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
minapp-vscode|qiu|2.2.2
quicktype|qui|12.0.46
vscode-yaml|red|0.6.1
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.3
vscode-leetcode|she|0.16.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.3
eno|Wsc|2.1.4
material-theme|zhu|3.2.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

What is language mode for this file (should be in on the right side of status bar)? Do you have any specific configs for languages?

**Comment by hua03** [comment]
I  disabled  extensions one by one then found This problem is caused by [HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css)

**Comment by connor4312** [comment]
Please open an issue on their repo, then!
