### ISSUE TITLE
File: Compare active file with ... does not work in latest insiders

### ISSUE THREAD

**Issue by pdanpdan** [microsoft/vscode#88528]
I also tested with all extensions disabled.

Issue Type: <b>Bug</b>

File: Compare active file with ... does not work in latest insiders

VS Code version: Code - Insiders 1.42.0-insider (22e4d75bd07b1ec7362c69da9dda7667eae95374, 2020-01-13T05:27:48.591Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (18.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
project-manager|ale|10.9.1
i18n-ally|ant|1.11.0
gitkraken-glo|axo|1.1.0
color-info|bie|0.5.1
markdown-mermaid|bie|1.4.1
gitignore|cod|0.6.0
transformer|dak|1.6.0
vscode-eslint|dba|2.0.13
githistory|don|0.4.13
xml|Dot|2.5.0
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.0.0
vsc-material-theme-icons|equ|1.1.2
auto-close-tag|for|0.5.6
vscode-pull-request-github|Git|0.14.0
sass-lint|gle|1.0.6
asciidoctor-vscode|joa|2.7.8
l13-diff|L13|0.21.0
rainbow-csv|mec|1.4.0
git-graph|mhu|1.21.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.5
sqltools|mtx|0.21.6
vscode-json-editor|nic|0.2.3
vetur|oct|0.22.6
vuehelper|oys|0.1.0
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
vscode-sort-json|ric|1.18.0
vscode-gtm|s3r|0.2.0
todotasks|san|0.5.0
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.7.3
language-stylus|sys|1.11.0
gitflow|vec|1.2.1
markdown-all-in-one|yzh|2.7.0
cursorCharCode|zei|0.1.1
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/confirmationPending I was able to compare with existing file without any problems.
Please note if you have removed file in Recent files section it will be an error.

Do you see any error notifications?

Also looks like there is another Insiders build, can you try using latest build?
Version: 1.42.0-insider (user setup)
Commit: 5e758c10c969d668730f036abfc557d9cfb62b87
Date: 2020-01-13T09:52:21.788Z

**Comment by pdanpdan** [comment]
Updated to the latest insiders.

It looks like compare works between an open file and a not opened file, but it fails when both files are already open (it just switches to the other file).

**Comment by bpasero** [comment]
@mjbvz this is coming from https://github.com/microsoft/vscode/blob/bc0f81bd0545af1eb0282870a95b0f156811b48e/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L357

**Comment by mjbvz** [comment]
Fixed by 2bbe9c533005e97f163ed38e1cfe85ea23787aeb (and possibly b84d08be70d1efe55d6097d3badcc03297a27635 too)
