### ISSUE TITLE
Icon did not displayed on MacOs Dock board.

### ISSUE THREAD

**Issue by JaredTan95** [microsoft/vscode#88520]
- VSCode Version:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0

- OS Version:
MacOs Mojave 10.14.6 (18G2022)

Steps to Reproduce:

1. click vocode to open a new window

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Sounds like #63068

**Comment by connor4312** [comment]
Let me know if so.

/needsMoreInfo
