### ISSUE TITLE
[folding] add setting to allow clicking in empty space to unfold

### ISSUE THREAD

**Issue by vuongvu1** [microsoft/vscode#88522]
When I click on a collapsed block of code, it won't open with my first click, I have to make another click to open it, this is not natural.

**Visual Studio Code - Insiders**

Version: 1.42.0-insider
Commit: 960cddb992cc96d47f56b633b361909f1b5b3353
Date: 2020-01-10T05:35:27.119Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

Please fix it. Thank you

**Comment by gjsjohnmurray** [comment]
/confirmationPending first click on the collapsed-block indicator (>) expands code for me.

Version: 1.42.0-insider (user setup)
Commit: 960cddb992cc96d47f56b633b361909f1b5b3353
Date: 2020-01-10T05:39:23.171Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

If you are using any extensions please first retest with all extensions disabled. If it still happens, give detailed steps. A screen recording may help.

**Comment by vuongvu1** [comment]
Hi @gjsjohnmurray first click on the collapsed-block indicator (>) works fine for me too, but I normally click on the '...' symbol at the end of a collapsed row to expand it. It doesn't work for me, please check this gif.

1. I use **_Cmd + K + 0_** to collapse all blocks
2. Try to click on the '...' to expand, not work

![bug-open-collapsed-content](https://user-images.githubusercontent.com/18032751/72249949-157a8280-362d-11ea-968e-72e9d51b5210.gif)

**Comment by gjsjohnmurray** [comment]
Clicking on the ... works OK for me. Please test with all extensions disabled, e.g. after running the command `Developer: Reload With Extensions Disabled`

**Comment by vuongvu1** [comment]
Hi @gjsjohnmurray, I did try as you suggested but still got the same result.
Now I realize I cannot expand it anymore with the '...'  

![bug-open-collapsed-content](https://user-images.githubusercontent.com/18032751/72251296-3395b200-3630-11ea-8ce9-7132ff6335a4.gif)

**Comment by usernamehw** [comment]
It's a recent change: #53886

**Comment by vuongvu1** [comment]
Wow I see, ppl want it that way, can't make everyone happy I guess.

Thank you for your support.

**Comment by aeschli** [comment]
@vuongvu1 Can you confirem that clicking on `...` still works. Clicking on the empty space behind now has changed and no longer expands.

**Comment by vuongvu1** [comment]
Hi @aeschli, I confirm that clicking on '...' still works and clicking on the empty space behind now has changed and no longer expands.

Even though I really want it back as before :(
Can I close this ticket now?

**Comment by aeschli** [comment]
I changes it to a feature request. Let's see how many other users would like a setting.

**Comment by Joey79100** [comment]
I just updated to 1.42 and noticed you can't click in the empty space to unfold anymore. By reading #53886 I saw that it was intentionally removed as people complained about it.
But there are people who got used to it (yes I'm talking of me) and are missing it (having to find a precise spot to click is annoying when you know you could just click anywhere). Where do we need to vote to have this as an optional setting?

**Comment by aeschli** [comment]
To vote, add a :+1: on the description of this issue.

**Comment by ShadeBlack** [comment]
Following up on this, I would prefer a double click on empty space to unfold, thus keeping the ability to single click to add a cursor to end of the folded line.

**Comment by cookch10** [comment]
Yes, please allow a configuration to restore the previous behavior of expanding when clicking on empty space.

**Comment by Irmitya** [comment]
I'm just going to rollback and maybe check in several months to see if I should never let it update again:
https://code.visualstudio.com/updates/v1_41
I don't even use new features ‾\\\_(ツ)\_/‾

**Comment by cookch10** [comment]
@aeschli , it seems there are folks interested in the previous behavior (myself included).  Can the previous behavior of clicking on a line and having it expand be put behind some configuration flag?

It's quite tedious to click on the ellipsis, especially when working in a large file with many folding regions (which have variable indentation).  The variable indentation is the main pain point for me (when I could just scroll down and click a line, and have it expand at any indentation level, it was great, but now having to find that hit target of the ellipsis is quite daunting when it moves to different areas depending on the indent level).

**Comment by Tyriar** [comment]
@aeschli please add a test plan or verification needed

**Comment by aeschli** [comment]
To verify:
- fold a region
- click in the empty space after the folded line (after the `...`) Verify that the line does not unfold
- set `"editor. unfoldOnClickInEmptyContent": true`
- - click in the empty space after the folded line (after the `...`) Verify that the line unfolds

Suggestions for a better setting name are welcome (@alexdima ?)

**Comment by gjsjohnmurray** [comment]
How about `editor.unfoldOnClickAfterEndOfLine` ?

**Comment by alexdima** [comment]
@aeschli :+1: For the setting, I don't really have a better name, except perhaps at one point the folding options should be grouped in a `.folding.` richer object, with backwards support.

**Comment by jrieken** [comment]
Does work with this file

```js
const test = async () => {
	const a = import('./foo');
	const a = import('./bar');
};
```

**Comment by aeschli** [comment]
I renamed the setting to `editor.unfoldOnClickAfterEndOfLine` as suggested by @gjsjohnmurray (Thanks!)
and fixed the issue found by @jrieken (changing the setting while the editor is open didn't work)

**Comment by alexdima** [comment]
@aeschli This just occurred to me, sorry for the late timing: `editor.unfoldOnClickAfterText`, `editor.unfoldOnDotsClick`. You could also ask in tomorrow's stand-up.
