### ISSUE TITLE
Debugging async/await Typescript with @babel/register doesn't work

### ISSUE THREAD

**Issue by yishn** [microsoft/vscode#88532]
Issue Type: <b>Bug</b>

In the latest version, it seems the VS Code debugger doesn't play nice with `@babel/register` along with `@babel/plugin-transform-typescript`. I believe this bug wasn't present in v1.41.0.

~~~js
// main.js

require("@babel/register")({
  presets: [
    ["@babel/preset-env", {
      targets: { node: "current" }
    }]
  ],
  plugins: [
    "@babel/plugin-transform-typescript",
  ],
  extensions: [".ts", ".js"],
  cache: true
})

const {main} = require("./test.ts")
main()
~~~

~~~ts
// test.ts

export async function main() {
  await new Promise(r => setTimeout(r, 1000))
  console.log('hello!')

  let a = await new Promise(r => r('a'))
  console.log(a)
}
~~~

The above `main` function is basically undebuggable using VS Code. I've created a [test repository](https://github.com/yishn/test-vscode-babel-register) and included more detailed reproduction steps to demonstrate the issue. When doing all the steps using the Chrome debugger, everything works fine.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by roblourens** [comment]
This is a scenario that we can't really support, and I confirmed that it also doesn't work at least in 1.39. But, it does work in our new experimental debug adapter which you can try out with this extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly
