### ISSUE TITLE
Search: do not trigger search automatically for regex and "|"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88539]
Steps to Reproduce:

1. vscode workspace
2. enable regex search
3. type a word followed by "|"

=> entire editor freezes for seconds because a search was triggered to find everything

**Comment by bpasero** [comment]
Probably similar: typing a single "." while regex search is on.

**Comment by roblourens** [comment]
We have gone back and forth on this before: https://github.com/microsoft/vscode/issues/66467 and there are other valid cases for searching with a regex that can match the empty string, for example if you combine it with a negative lookbehind.

@JacksonKearl do have any thoughts on how to make this less annoying, for example if the regex query will match the empty string, use a longer debounce after that keystroke.

**Comment by roblourens** [comment]
And I only saw the second comment after adding my comment, but yeah, maybe a different longer debounce in general while in regex mode would help?

**Comment by JacksonKearl** [comment]
Having rapid feedback in RegEx mode is one of my favorite parts of the search on type... maybe we could heuristically check if its likely to match very many things and debounce based on that?

**Comment by roblourens** [comment]
Yeah we could also just look at the exact cases that @bpasero brings up, `.endsWith('|')` or `=== '.'` which are likely to be common.

**Comment by bpasero** [comment]
I would not trigger a search automatically that is likely to produce tons of results, such as the examples I gave.

**Comment by bpasero** [comment]
How about using a function such as:

https://github.com/microsoft/vscode/blob/bf350ef870f229b334d3f54a7cc81a7e73841c3b/src/vs/base/common/strings.ts#L222

Which checks on matching the empty string?

**Comment by roblourens** [comment]
We removed that in the issue I linked, also it won't help with your second example. I think we should still trigger them automatically because they are valid queries, just a longer debounce. And we can identify some cases that are likely to come up while typing and match those.

**Comment by JacksonKearl** [comment]
Experimenting with a heuristic that delays the a regex search a multiple of how many matches it creates on some dummy input. So with default debounce a search for `.` or `\w` now delays by 1500 ms, and a search for something like `text|` delays by 3000 ms. Let me know what you think

**Comment by roblourens** [comment]
That's... interesting, lol let's try it

**Comment by JacksonKearl** [comment]
Yeah idk something simpler is probably just fine. But it's fun, and is a bit more robust than just checking if the last char is `|` or if it is only `.`, `\w`, `\s`, etc.

**Comment by bpasero** [comment]
@JacksonKearl shouldn't we simply not start the search automatically if we detect that the pattern matches each and every character from your test-bed?

**Comment by JacksonKearl** [comment]
@bpasero We could. I figured people might eventually be accustomed enough to the search on type that it sometimes being disabled would be more confusing. If they're just sitting there for 3 seconds anyways I think the potential hang of running a search with many results wont impact them too much?

**Comment by bpasero** [comment]
Yeah ok let's try it.
