### ISSUE TITLE
In "Replace in files", hitting Tab before files searched fails to move focus to Replace

### ISSUE THREAD

**Issue by ekliptik** [microsoft/vscode#88533]
Issue Type: <b>Bug</b>

1. Load a reasonably large code base
2. Go to Replace in files
3. Type search term and immediately hit Tab
Focus moves to Replace, and if the found lines are updated after the focus has moved to Replace, focus moves back to Search.
Video here: https://youtu.be/m6iupw4kk_M

VS Code version: VSCodium 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-21T00:21:25.699Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ekliptik** [comment]
Related but not duplicate to https://github.com/microsoft/vscode/issues/34676

**Comment by roblourens** [comment]
I can't repro this. Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by ekliptik** [comment]
Can't repro on new versions either! It seems it has been fixed. 
Apologies for the delay
