### ISSUE TITLE
Shortcut not working

### ISSUE THREAD

**Issue by haward79** [microsoft/vscode#88537]
Issue Type: <b>Bug</b>

I cannot switch to Explorer by shortcut, Ctrl+Shift+E.
I cannot switch to Git by shortcut, Ctrl+Shift+G.

VS Code version: Code - Insiders 1.42.0-insider (960cddb992cc96d47f56b633b361909f1b5b3353, 2020-01-10T06:48:04.971Z)
OS version: Linux x64 4.15.0-20-generic
Remote OS version: Linux arm 4.19.75-v7l+
Remote OS version: Linux x64 3.13.0-170-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.54GB (0.48GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: haward79-dev|
|OS|Linux arm 4.19.75-v7l+|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 600)|
|Memory (System)|3.76GB (0.25GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: csie-oldserver|
|OS|Linux x64 3.13.0-170-generic|
|CPUs|Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz (16 x 1600)|
|Memory (System)|31.41GB (29.87GB free)|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Most likely <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>G</kbd> is used as first chord for GitLens

**Comment by haward79** [comment]
> /needsMoreInfo
> 
> Is it reproducible with all extensions disabled?
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`
> 
> Most likely Ctrl+Shift+G is used as first chord for GitLens

After I updated vs-code to the following version, all issue gone.

Version: 1.42.0-insider
Commit: 22e4d75bd07b1ec7362c69da9dda7667eae95374
Date: 2020-01-13T05:28:42.464Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-20-generic

Thanks.
