### ISSUE TITLE
TreeView: Support search/filtering in the whole data model

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#88530]
For #88527 I need a TreeView feature that allows to search in a non-lazy Tree (i.e. a tree where the whole data model exists upfront).

For #88526 I switched the implementation of the LoadedScriptsView to use the `WorkbenchCompressibleAsyncDataTree` where the search/filtering functionality only works on the already seen parts of the tree model.

**Comment by joaomoreno** [comment]
In order to get this to work we need to move away from the async data tree.

**Comment by weinand** [comment]
After moving to the sync data tree, this is no longer an issue for me (and can be closed).
