### ISSUE TITLE
Global search dont search in files in symbolic linked folders in project

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode#88535]
Issue Type: <b>Bug</b>

Having a project (c++) with symbolic linked folder having many files inside, search for some text in all files, dont search the files in the linked folder. Only open files from the linked folder are correctly searched.

I'm sure that wasn't a problem previously !!

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
Have you maybe disabled the setting `"search.followSymlinks"`?

**Comment by iqapps** [comment]
I made the directory link into my project with this command in Win10.

mklink /D /J Libraries "../Libraries"

It makes a directory junction symbolic link. Could this be the issue.

I cannot use the link without the /J attached since the Arduino compiler need this to be able to read the directory.

**Comment by roblourens** [comment]
Maybe more issues with recognizing these as folders/symlinks, similar to https://github.com/rust-lang/rust/issues/46484

**Comment by iqapps** [comment]
I have news here: I found that opening the "files to include and files to exclude" dropdown in the global search panel, and entering a star in "files to include" field, the search finds what I need in all files, including the linked folders files.

**Comment by roblourens** [comment]
In that case you might want to double check that those linked folders are not actually just excluded due to exclude patterns/gitignore in your workspace https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by iqapps** [comment]
These folders and files are in fact in the gitignore.

**Comment by roblourens** [comment]
Ok, that would explain the issue then
