### ISSUE TITLE
Do not auto expand node_modules folder in file browser when files inside it change (e.g. yarn add)

### ISSUE THREAD

**Issue by ianidi** [microsoft/vscode#88542]
Usually when you run npm install or yarn add the node_modules folder is auto expanded and you have a large list of folders that you actually don't want to see.

<img width="206" alt="Снимок экрана 2020-01-13 в 14 44 02" src="https://user-images.githubusercontent.com/51965970/72253721-3e8e1980-3613-11ea-8027-0f4ba861cbfb.png">

**Comment by connor4312** [comment]
I cannot reproduce this on my machine. Does this happen if you run with `code --disable-extensions`?

/needsMoreInfo
