### ISSUE TITLE
Toggle breakpoints with double-click

### ISSUE THREAD

**Issue by hagemann** [microsoft/vscode#88540]
How about toggling breakpoints in the editor with a double-click? I never use BPs and find the feature excruciatingly annoying during full-line selections or when accidentally clicking the area to switch windows. I think a double-click wouldn't be so much pain for someone who uses BPs while it's an incredible relief for someone who doesn't. An option to completely disable them is another solution.

**Comment by gjsjohnmurray** [comment]
How about `"editor.glyphMargin": false` ?

**Comment by connor4312** [comment]
Let us know if that resolves it for you.


/needsMoreInfo

**Comment by hagemann** [comment]
Thanks @gjsjohnmurray! `editor.glyphMargin` is the option I was looking for.
