### ISSUE TITLE
HTML Autocompletion for details & summary

### ISSUE THREAD

**Issue by mateuspv** [microsoft/vscode#88548]
HTML Autocompletion should complete details and summary:
![Screen Shot 2020-01-13 at 10 22 15](https://user-images.githubusercontent.com/4995440/72259247-bd249000-35ee-11ea-8ad6-9d4b9bcd921c.png)

Expected:
details should autocomplete to `<details></details>`
summary should autocomplete to `<summary><summary/>`

**Comment by gjsjohnmurray** [comment]
I think you are referring to [Emmet](https://docs.emmet.io/cheat-sheet/) autocompleting because you're not typing an opening `<` character.

Emmet has `det` which expands to `<details></details>`

There is apparently no abbreviation that expands to `<summary></summary>`

**Comment by IllusionMH** [comment]
yep, Emmet shippets config only has `det` defined (as mentioned above)
https://github.com/emmetio/emmet/blob/0bd4100be0282ab329d1a7c8842128cee2f3c822/snippets/html.json
So this one should be request in Emmet repo.

If you type `<deta` or `<sum` you'll see proper suggestions for HTML tags.

**Comment by mateuspv** [comment]
Merged into emmet, thanks everyone.
https://github.com/emmetio/emmet/blob/0bd4100be0282ab329d1a7c8842128cee2f3c822/snippets/html.json#L137
