### ISSUE TITLE
Refactor preview: Apply changes on Enter

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#88557]
Apply changes should also be triggered on Enter.

Reasoning: enter is already a confirm for the regular rename, and without Enter I have to get ahold of my mouse or to press tab too many times.

**Comment by jrieken** [comment]
`Enter` is already to open a tree element, e.g to preview it. The default keybinding is Shift+Enter, the same gesture that brought you there so I think that makes sense. F2, Shift+Enter, Shift+Enter, and done

**Comment by isidorn** [comment]
Makes sense, however I would expect that on hover I get the keybinding. E.g on "Apply Change" I get "Apply Changes(Shift + Enter)"

**Comment by jrieken** [comment]
Yeah... Makes sense, now clue why this isn't automatic why I still have to write code this...
