### ISSUE TITLE
Random desktop.ini file

### ISSUE THREAD

**Issue by diligamer** [microsoft/vscode#88555]
- VSCode Version: Version: 1.41.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Random Desktop.ini file appearing in the directory root though it does not exist in that location

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
The file is sure to exist but probably has its Hidden attribute set, causing Windows Explorer not to show it unless you ask to see hidden files.
