### ISSUE TITLE
Same editor appears twice in tabs

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#88551]
1. Add a large-ish image to a repo (1080p)
2. Open SCM view
3. Click twice in untracked image

Two tabs will appears for that same file:

![image](https://user-images.githubusercontent.com/22350/72264403-0094f380-361b-11ea-86f4-b7a8e9ed3f69.png)

**Comment by bpasero** [comment]
Git bisect shows me that the cause was this: https://github.com/microsoft/vscode/pull/88183

**Comment by bpasero** [comment]
This was actually a bug in the text diff editor and the behaviour was right. I pushed a fix.
