### ISSUE TITLE
Preview rename message polish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#88552]
I like how you use the space below the rename box to make the Preview discoverable.
Some potential improvments:
1) Omit the word "Press", feels like currently there is too much text. Especialy since on Win the alternative shortcut might take more space
2) Consider using opacity or some other way to make sure the message is percieved as a help (like our placeholders texts in our places)

![Screenshot 2020-01-13 at 16 10 38](https://user-images.githubusercontent.com/1926584/72266753-49e74200-361f-11ea-9fb4-de6ffa754393.png)

fyi @misolori for potential ideas

**Comment by jrieken** [comment]
It already is a little opaque but I can make it even more so...
