### ISSUE TITLE
Tooltips have a black background

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#88565]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/641685/72273459-60c66e00-35f8-11ea-97cf-3c9afe429b40.png)

This is related to the Electron 7 upgrade

VS Code version: Code - Insiders 1.42.0-insider (5e758c10c969d668730f036abfc557d9cfb62b87, 2020-01-13T09:52:21.788Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?

**Comment by eamodio** [comment]
Yeah, it is a chrome change -- its the same in chrome and edge now (well for a while now)
