### ISSUE TITLE
Moving directory contents fails if full path contains the same folder name more than once

### ISSUE THREAD

**Issue by nixxquality** [microsoft/vscode#88569]
Issue Type: <b>Bug</b>

1. Clone the repo https://gitgud.io/nixx/vscodebug-dummy.git
2. Drag and drop the contents of the root folder into the vscodebug-dummy folder
3. Note that the src folder ends up as /src, but it should be /apps/root/src

![bug](https://user-images.githubusercontent.com/2478713/72277664-99833900-3632-11ea-855a-8272193bef44.gif)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (25.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.14
svg|joc|1.0.6
remote-wsl|ms-|0.41.7
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2
erlang|pgo|0.5.2

</details>

**Comment by nixxquality** [comment]
Actually, it's because of the directory contraction thing. When you click the top item, it automatically expands to src (even if you didn't know it had subfolders) and wants to drag that out.

**Comment by isidorn** [comment]
If you want to drag the other part of the compacted node you should hover over a different part of the name (you get underline feedback).
What the gif is showing is expected behavior I believe.

Not sure what we can change here

**Comment by nixxquality** [comment]
I realise that it looks a bit dumb in the recording I made after the fact, but it's a bit more ambiguous  when you haven't expanded the folder before.
![bug2](https://user-images.githubusercontent.com/2478713/72452484-e6dfe180-37bd-11ea-8b08-d36caa4cf921.gif)
When you left click the apps folder, it automatically selects the src folder, even though you may not realise it.

This is what I tried to explain with my follow-up message but I understand if that wasn't clear enough.
