### ISSUE TITLE
Suggestion: Change command to Show Recommended Extensions

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8856]
- VSCode Version:1.3.0-insiders
- OS Version:Windows

The rest of the Extension: commands in the Command Palette and Extensions View dropdown say "Show blah Extensions".  Saying "Show Extension Recommendations" doesn't fit with the others.

I get it wrong all the time in the docs.:-) 
The filter is "@recommended" as well.

**Comment by gregvanl** [comment]
I think the commit didn't use plural Extensions.  Should be "Show Recommended Extensions" since there will usually be multiple recommendations.

**Comment by joaomoreno** [comment]
Oh man, great catch! Thanks!
