### ISSUE TITLE
Refactor preview: element should expand on click anywhere

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#88561]
Refactor preview tree: element should expand wherever I click on it, not only on the expando. 
This only makes sense for special tree that have additional actions for click on file. And the refactor tree does not do anything.

I would guess this is just a copy / paste from the previous tree :)

**Comment by jrieken** [comment]
> And the refactor tree does not do anything.

Sure, it shows a diff editor when you select a file or text change...

**Comment by jrieken** [comment]
Oh, wait it actually doesn't but should open the file in question...
