### ISSUE TITLE
VSCode lag when web browser is loading

### ISSUE THREAD

**Issue by majezanu** [microsoft/vscode#88566]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

1. Open VSCode
2. Open web browser (Brave)
3. Scroll on VSCode window and see the lag on reder

Note: VSCode has lag with or without extensions.
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3157)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|7.63GB (0.67GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   117	  4319	code main
    0	    31	  4321	   zygote
    0	   156	  4356	   gpu-process
    0	   281	  4364	   window (notifications.component.ts - Interlingua - Visual Studio Code)
    0	   203	  4622	     extensionHost
    0	    78	  4674	       electron_node tsserver.js 
    0	   234	  4675	       electron_node tsserver.js 
    0	    62	  4744	         electron_node typingsInstaller.js typesMap.js 
    0	    55	  4806	       /snap/code/23/usr/share/code/code /snap/code/23/usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=4622
    0	   117	  4648	     watcherService
    0	    94	  4595	   shared-process
    0	     0	  9923	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  9924	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   117	  9897	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (notifications.component.ts - Interlingua - Visual Studio Code)
|    Folder (Interlingua): 12745 files
|      File types: py(2153) pyc(2143) mo(1179) po(1129) svg(576) scss(270)
|                  html(228) css(219) js(162) less(128)
|      Conf files: tslint.json(2) package.json(1) tsconfig.json(1) makefile(1);
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
laravel-blade-vscode|ami|1.0.3
vscode-intelephense-client|bme|1.2.3
laravel-blade|cjh|1.1.2
doxdocgen|csc|0.5.2
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.0.0
vsc-material-theme-icons|equ|1.1.2
php-intellisense|fel|2.3.14
ftp-simple|hum|0.7.5
vscode-browser-sync|jas|1.3.1
vuetify-pug-snippet|luc|0.6.0
php-namespace-resolver|Meh|1.1.8
python|ms-|2020.1.57204
remote-wsl|ms-|0.41.7
cpptools|ms-|0.26.2
php-docblocker|nei|2.1.0
vetur|oct|0.23.0
laravel-blade|one|1.20.0
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.0.3
python|tht|0.2.3
vscodeintellicode|Vis|1.2.3
vscode-arduino|vsc|0.2.29
vuetify-vscode|vue|0.2.0
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
