### ISSUE TITLE
Show/Hide commands in context menu when selecting multiple treeitems

### ISSUE THREAD

**Issue by lstocchi** [microsoft/vscode#88568]
Hi, current implementation allows to select multiple treeitems but i couldn't find a way to show commands in context menu based on it. It would be helpful if i could show or hide a command based on the number of treeitems selected. (i.e i have two actions `start` and `bulk delete` in my context menu. I want to hide `start` command if multiple items are selected and show `bulk delete`)

**Comment by IllusionMH** [comment]
Have you tried to add `when` condition to menu contribution using next contexts (screenshot from keybindings)?
![image](https://user-images.githubusercontent.com/1312662/72277311-5fb63080-363a-11ea-9f8b-18d5dee3a281.png)
