### ISSUE TITLE
TreeView reveals wrong item if multiple TreeItems with the same label exist.

### ISSUE THREAD

**Issue by tintinweb** [microsoft/vscode#88578]
- VSCode Version: 1.41.1
- OS Version: macos 10.15.2

<img width="200" src="https://user-images.githubusercontent.com/2865694/72289630-d14aaa80-364b-11ea-882b-5b229fb235f7.png">

I am maintaining a [bookmark extension for inline bookmarks](https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-inline-bookmarks). One feature users are using is the inline bookmarks view, a treeview in the side panel that allows you to get a quick overview on bookmarks per file. Recently I have added that the treeview item selection follows the users selection in the active editor. In the bookmarks treeview the bookmark text is the treeItem.label. Bookmarks are unique by location and text. There can be duplicate bookmarks with the same label on different lines.

`treeview.reveal()` works fine until I try to reveal an item that has a non unique `label`. `treeview.reveal(treeviewDataProvider.treeItem)` appears to reveal the first item that matches the `treeItem.label` if there are multiple similar `treeItems` sharing the same name even though other properties (`contextValue`, custom props, ..) are different. 

Steps to Reproduce:

1. create a custom treeview, populate it with items. add multiple objects with the same name on the same tree level but with different contextValue or other properties.
2. reveal one of the duplicate items (same label). e.g. reveal the last one of the duplicates.

**expected:** last item is selected (i.e. exact that unique object that I pass to `reveal` is revealed and not another object with the same `label`)

**actual result**: first item in the list having that label is reveald (even though other properties doent match).

In case this is expected behavior (not allowing multiple items with the same label on the same level), how can I specify an `id` (or something) for an item for `treeview.reveal` to exactly match the item I am requesting instead of the first one matching `label`? Note that I cannot really hide an `id` in the `label` as this is presented to the user.

here's some live action:

* when I click the `audit-ok` item in the treeview, the correct line is selected in the editor.
* when I click one of the `audit-ok` strings in the editor (except the first one), causing a `treeview.reveal(myTreeviewDataItem)`, the first item matching `label` is selected.

Note: If I add e.g. the line number to the label it works. But that messes up the UX as I dont want the line number to be part of the text shown in the treeview.

![bookmarks-treeview](https://user-images.githubusercontent.com/2865694/72289637-d7408b80-364b-11ea-8510-ba56c938ed38.gif)

* `treeViewDataProvider.treeItem`: https://github.com/tintinweb/vscode-inline-bookmarks/blob/master/src/features/inlineBookmarks.js#L323-L332
* `treeview.treeItem`: https://github.com/tintinweb/vscode-inline-bookmarks/blob/master/src/features/inlineBookmarks.js#L366-L377

ref: https://github.com/tintinweb/vscode-inline-bookmarks/pull/6/

**Comment by alexr00** [comment]
You need to set a unique id on you tree items.

**Comment by tintinweb** [comment]
Thank you @alexr00, adding an `id` fixed the issue! 

cheers 🙌
