### ISSUE TITLE
SCM diff does not respect global textconv gitconfig

### ISSUE THREAD

**Issue by senhalil** [microsoft/vscode#88573]
- VSCode Version: 1.41.1
- OS Version: Linux x64 4.15.0-74-generic

Steps to Reproduce:

1. add the following section to the git config (e.g., ~/.gitconfig )
```
[diff "json"]
  textconv = "cat \"$1\" | json_pp --json_opt=canonical,pretty" 
```
2. add the following to the git attributes file (e.g., ~/.gitattributes )
```
*.json diff=json
```
3. `git diff`, `git show` and other `git log` family of commands perform text conversion and they show diff and changes over prettified json but vscode continues to use the original document.

Opening a file via File explorer or source control puts `> git show :test/fixtures/results_regularity.json` message to the log output (Git) but doesn't apply the textconv. 
  
![vscode_output](https://user-images.githubusercontent.com/20163961/72280469-b1f65200-3638-11ea-9ae1-3d70994ce836.png)

The same command in terminal show the prettified output
![git_output](https://user-images.githubusercontent.com/20163961/72280470-b1f65200-3638-11ea-9378-c8f8ff940dfc.png)

The same applies to diff screen

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What if you right click and choose `Open File (HEAD)`

**Comment by senhalil** [comment]
The `git show` command stopped prettifying in the terminal.  

I guess I made a mistake earlier (that file is already overwritten but I guess the original file was already prettified and I assumed it was `git show` making the transformation). I assume this is the expected functionality. Sorry for your trouble!

If you don't mind answering, is there a way to enable `--textconv` option inside vscode by default for `git show` and `git diff` purposes OR is there a vscode diff setting for this purpose -- i.e., textconv?

**Comment by joaomoreno** [comment]
I don't think we currently have that option!
