### ISSUE TITLE
Provide a way for debug adapters to register UI-hidden debug types

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#88574]
In order for a debug adapter to receive events for a debug type, that debug type needs to be registered as a contribution in its package.json in addition to the usual adapter descriptor factory.

In js-debug we have a rather [esoteric use case](https://github.com/microsoft/vscode-js-debug/pull/221) where we want to have a debug type that's used internally (to inject a debug configuration from command code into the adapter) and not exposed to the user.

We _could_ technically shim overload this into one of our existing debug types, this is a rather ugly solution which I'd rather avoid.

**Comment by roblourens** [comment]
We could get the same effect by using an existing type + some hidden property flag, right? Is that the ugly workaround you're referring to?

**Comment by connor4312** [comment]
It is. It'd work, but it somewhat reduces the soundness of our internal types. Instead of saying "this type of object is a request to launch a Node.js process", we'd say "this type of an object is a request to launch a Node.js process, unless __delegateId is set in which case it's not related to Node and instead injects an existing session".

Maybe this use case is weird enough that that would be better than adding more vscode API surface, though.

**Comment by weinand** [comment]
@connor4312 I've read the [esoteric use case](https://github.com/microsoft/vscode-js-debug/pull/221) and I got the impression that we have already something very similar (that does not rely on a hidden debug type).

For the "Auto attach" feature VS Code has a built-in "companion" extension "debug-auto-launch" that implements the UI and detection logic. With this extension VS Code can be put into an "auto attach" mode where it watches for processes in debug mode running in the integrated terminal and starts new node-debug sessions if it detects any.

Since this functionality is implemented as a separate extension, we can have a UI (in the status bar) that is always on, but does not activate node-debug too early (e.g. on startup).

Could we try to generalise this functionality so that it covers the js-debug cases as well?

**Comment by connor4312** [comment]
The mechanism of action for auto-attach and JS debug's debugger terminal is different. Auto-attach polls for child processes and connects Node processes that run with the `--inspect` flag. In debugger terminal, any Node.js process launched by the user or other terminal processes will cause a debug session to start without additional flags. This is powerful, for instance a user can simply run `npm start` without touching their existing files or configuration and get a full debugging experience.

The way this works is by setting `NODE_OPTIONS` to `--require` a bootloader script that forces the process into debug mode. When this bootloader script is required, it creates a companion process that proxies the CDP connection to a pipe server set up by the debug adapter. This is also how we can automatically connect to all child processes; by default they will inherit the current environment, get the bootloader, and through that call back to the debug adapter.

The existing auto-attach polling lets us easily create a 'normal' launch configuration containing a request to attach to a debug process on a specific port. However, js-debug does not know that a debuggable process exists until it's knocking on the door with a CDP connection. Because of this, it needs some way to inject the CDP connection it just received into a debug session--something the basic launch and attach configurations don't do, and something that will not be able to done except through this entrypoint. That's why I added the new 'delegate' launch config type to js-debug, and why I want to hide it from appearing to users.

I hope that makes a little more sense 🙂

**Comment by weinand** [comment]
No, I did not mean to directly use anything in "debug-auto-launch" for the auto-debug feature of js-debug.

But couldn't the "debug-auto-launch" extension (or another new extension created only for this purpose) not be used to "set the NODE_OPTIONS to --require a bootloader script" and "start the pipe server", and listen for the "knocking on the door with a CDP connection"?

I try to understand why we have to shoehorn this functionality into a fake debug session with a fake debug type?

**Comment by connor4312** [comment]
I think that's a question from what I'm looking for here. Whether the debug terminal is launched from js-debug or a helper extension, someone needs to call `vscode.debug.startDebugging` to create a debug session.

For auto attach, [can create](https://github.com/microsoft/vscode-node-debug/blob/142ec9e75eb782e8dd93d05a28befe577dec5030/src/node/extension/autoAttach.ts#L84) an attach configuration very similar to what a user could normally write in their launch.json. There's an __autoAttach flag, but it's generally the same. For the delegate debug type, it does not fit into any of our existing launch or attach configurations; we don't need a port to connect to, program to run, or browser to boot, we just need a delegate ID. The code paths for providing configuration and handling the launch within the adapter are different than the existing Node.js  and Chrome handling.

I mentioned above, while it would be possible to overload an existing config and have some special-case logic to reroute the launch request, I would rather be able to register a distinct launch configuration type for delegate sessions.

**Comment by weinand** [comment]
Instead of introducing a new debug type we have the option to introduce a new value for the "request" attribute.
In addition to "launch" and "attach" we could introduce something like "delegateTo".

**Comment by weinand** [comment]
Another question about the UI-hidden debug type:
Other than being used in the launch config passed into the `vscode.debug.startDebugging()` call, what would be done with this type?

**Comment by connor4312** [comment]
> Other than being used in the launch config passed into the vscode.debug.startDebugging() call, what would be done with this type?

That's the only use here.

--- 

Thinking about it some more, for this issue I ended up co-opting `node-terminal`'s unused `attach` request. Omitting the request inside the package.json contributions makes it 'invisible' to the user, and it's close enough to what I'm after to make sense. I'm satisfied with this solution for the moment, and probably better than creating a new debug type for this specific scenario.
