### ISSUE TITLE
Cannot respond to the keyboard (Sometimes)

### ISSUE THREAD

**Issue by robotVisionHang** [microsoft/vscode#88579]
Issue Type: <b>Bug</b>

Sometimes, Visual Studio Code can not respond in time while I am typing codes. In the last version, this casue the stuck of all the Ubuntu System; In this version, Visual Studio Code is stuck for 2-3 seconds.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.4.0-171-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (1.43GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2

</details>

**Comment by Rohit-ChauhanRC** [comment]
settings.json --> check "files.autoGuessEncoding": true,
