### ISSUE TITLE
Feature Request: A native solution to sync user settings

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#88572]
Rather than using an extension, I'd like a way to be able to login to vscode so that I can sync my user settings, extensions, code snippets, etc from machine to machine. Kind of like logging into Google Chrome

**Comment by IllusionMH** [comment]
/duplicate of #2743 and it's already in the works.

In the meantime you can use https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
