### ISSUE TITLE
Visual Studio Patch silent install corrupts the application

### ISSUE THREAD

**Issue by 0ut1awStar** [microsoft/vscode#88575]
If the Visual Studio Code 1.41.0 x64 update is pushed out to a machine while a user is logged on and currently has the VSCode application open, the application will get corrupted and be unusable.

If you manually attempt to apply the update without switches while the application is running, you get a message indicating that the application is in use and to close it before continuing.

- VSCode Version: 1.41.1
- OS Version: Any

Steps to Reproduce:

1. Install Visual Studio Code 1.40.0 x64 on a machine.
2. Ensure a user us logged onto the machine and that they have the Visual Studio Code application open.
3. Run update as system with silent switch /VERYSILENT /SUPPRESSMSGBOXES
4. Attempt to start the VSCode application.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is why we distribute a user setup as well, so each user can have their own installation: https://code.visualstudio.com/docs/?dv=win64user

**Comment by ALvanti** [comment]
I don't find this answer to be particularly satisfactory.
@joaomoreno  Are you saying as an IT Admin at a company we need to only rely on the user based installation instead of a system based installation?

**Comment by joaomoreno** [comment]
We currently have no good solution for IT Admins, unfortunately.
