### ISSUE TITLE
Suggestion: add @installed filter to Extensions View

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8857]
To keep parity with @outdated, @popular and @recommended, we could add @installed.  We can still have the cleared search box show installed but I think users might expect that @installed would work.

It actually would help explain the installed extension list which is currently displayed without any clarification, just the "Search Extensions in Marketplace" prompt.

See also https://github.com/Microsoft/vscode/issues/8856

**Comment by joaomoreno** [comment]
We can add it but we should not drive users to it.

**Comment by gregvanl** [comment]
Looks like this was done as some point.
