### ISSUE TITLE
my extension has something wrong  what can i do

### ISSUE THREAD

**Issue by dddddu** [microsoft/vscode#88583]
Issue Type: <b>Bug</b>

i can't use my extension store  what can i do

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.41.2
python|ms-|2019.11.50794
cpptools|ms-|0.26.3-insiders2
java|red|0.55.1
vscode-java-dependency|vsc|0.6.0

</details>

**Comment by gjsjohnmurray** [comment]
Maybe similar to #84657 ? Please read the advice given there by @sandy081 and update here with your results.

**Comment by sandy081** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
