### ISSUE TITLE
Show breakpoints and logpoints in minimap

### ISSUE THREAD

**Issue by rben01** [microsoft/vscode#88581]
Currently, the minimap shows certain decorations in addition to the file's text, such as the current line (blue) and lines with errors (red). It would also be nice to dedicate a few pixels on the left of the minimap to indicate breakpoints, with different colors and/or shapes to distinguish between unconditional breakpoints, conditional breakpoints, and log points.

**Comment by gjsjohnmurray** [comment]
@rben01 in case you haven't already discovered this, it is already possible to show them in the Overview Ruler

`"debug.showBreakpointsInOverviewRuler": true`
