### ISSUE TITLE
TypeScript and JavaScript Language Features

### ISSUE THREAD

**Issue by JonathanRangelB** [microsoft/vscode#88584]
Issue Type: <b>Bug</b>

Just opened a js file from create-react-app boilerplate code and then a message appeared saying that this vscode feature failed to load 5 times in a row and will not be restarted.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.07GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.18.0
LiveServer|rit|5.6.1

</details>

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

Do you still see the issue after installing that extension and restarting VS Code?

**Comment by David-Else** [comment]
This error is not fixed for me using 1.41.1 and `JavaScript and TypeScript Nightly` extension TS 3.8.0-dev.20200114. Just do `ctrl-n`to start a new file, start typing and bam... crash every time!

**Comment by JonathanRangelB** [comment]
I just reinstalled vscode on my computer and seems to be working fine now
