### ISSUE TITLE
Clicking between test and EOL annotation sends the cursor to the beginning of the line

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88580]
![Jan-13-2020 15-46-53](https://user-images.githubusercontent.com/323878/72301580-135bf800-361c-11ea-8725-ba2f26c4225a.gif)

**Comment by napei** [comment]
+1 happening to me also

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/88873 I believe.
