### ISSUE TITLE
Expand selection improvements in Python

### ISSUE THREAD

**Issue by ngharrison** [microsoft/vscode#88589]
Issue Type: <b>Feature Request</b>

Currently the expand selection feature when used in Python files ignores quotes and indented blocks. Expanding to text inside quotes works in other languages and I would expect both to work. This issue was raised in #433 two years ago, but I don't see a resolution.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
/causedByExtension Please log this at https://github.com/microsoft/vscode-python
