### ISSUE TITLE
在mac系统下，编辑器里编写@file，按住CTRL打开文件不能正常工作

### ISSUE THREAD

**Issue by qq89987112** [microsoft/vscode#88593]
比如我输入了 @file://Users/xxxxx/Desktop/project/notes/githooks.js
按住CTRL点击链接，却提示

_**无法打开“githooks.js”: 无法读取文件(Error: 找不到文件(//Users/Users/xxxxx/Desktop/project/notes/githooks.js))。**_

这里是因为这个路径 //Users/Users 出问题了吗？

一些其他例子，比如输入  @file://xxxxx/Desktop/project/notes/githooks.js
点击提示 

**_无法打开“githooks.js”: 无法读取文件(Error: 找不到文件(//xxxxx/xxxxx/Desktop/project/notes/githooks.js))。_**

**Comment by byyxx128** [comment]
1. Always English please!!!
2. Do NOT ask questions in GitHub. Ask [here](https://stackoverflow.com/questions/tagged/visual-studio-code).
3. Your  mother tongue is poor as well...
