### ISSUE TITLE
没有代码提示

### ISSUE THREAD

**Issue by wangybm** [microsoft/vscode#88590]
Issue Type: <b>Feature Request</b>

react 项目没有代码提示，体验很差， 装了插件也不管用

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by byyxx128** [comment]
This user is reporting an issue of a specific extension.
Please report extension issues in their repositories or via VS Code wizard.

**Comment by LazyDuke** [comment]
> Issue Type: Feature Request
> 
> react 项目没有代码提示，体验很差， 装了插件也不管用
> 
> VS Code version: Code 1.41.1 ([26076a4](https://github.com/microsoft/vscode/commit/26076a4de974ead31f97692a0d32f90d735645c0), 2019-12-18T14:58:56.166Z)
> OS version: Windows_NT x64 10.0.18362

装回1.40.2试试

**Comment by wangybm** [comment]
> > Issue Type: Feature Request
> > react 项目没有代码提示，体验很差， 装了插件也不管用
> > VS Code version: Code 1.41.1 ([26076a4](https://github.com/microsoft/vscode/commit/26076a4de974ead31f97692a0d32f90d735645c0), 2019-12-18T14:58:56.166Z)
> > OS version: Windows_NT x64 10.0.18362
> 
> 装回1.40.2试试

我现在装回1.37版本了，好了

**Comment by LazyDuke** [comment]
> > > Issue Type: Feature Request
> > > react 项目没有代码提示，体验很差， 装了插件也不管用
> > > VS Code version: Code 1.41.1 ([26076a4](https://github.com/microsoft/vscode/commit/26076a4de974ead31f97692a0d32f90d735645c0), 2019-12-18T14:58:56.166Z)
> > > OS version: Windows_NT x64 10.0.18362
> > 
> > 
> > 装回1.40.2试试
> 
> 我现在装回1.37版本了，好了

我上周也碰到了  关键是没人去解决。。也是蛋疼
