### ISSUE TITLE
Unable to install extensions [Linux]

### ISSUE THREAD

**Issue by WhiskeyBeard** [Microsoft/vscode#8859]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-28-generic

Steps to Reproduce:

1. Navigate to Extensions
2. Click Install on any extension, no call-outs to user, nothing happens.

**Comment by artem-sidorenko** [comment]
I also have difficulties to see the installed or outdated extensions

**Comment by Tyriar** [comment]
@WhiskeyBeard what distro are you on?

Also is anyone who :+1:'d  experiencing this not on Linux?

**Comment by hyperlobic** [comment]
I am having these issues on Ubuntu 14.04.

**Comment by adam-mrachek** [comment]
Able to search extensions, but not able to install anything.  Ubuntu 16.04

**Comment by mksarge** [comment]
Linux Mint 17.3
Like previous commenters - able to search extensions, but install button does nothing.
Dev console spawning periodic errors exactly like posted by @WasabiFan

**Comment by afluth** [comment]
Same issues. Ubuntu Gnome 16.04

**Comment by natsukagami** [comment]
Same issues on Arch Linux x64.

**Comment by ryanbowden** [comment]
Same issue ubuntu 14.04.

**Comment by joaomoreno** [comment]
Here are the 1.2.1 as a temporary workaround:

- [32bit archive](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/VSCode-linux-ia32-stable.zip)
- [32bit deb](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-i386.deb)
- [32bit rpm](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-i386.rpm)
- [64bit archive](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/VSCode-linux-x64-stable.zip)
- [64bit deb](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-amd64.deb)
- [64bit rpm](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-x86_64.rpm)

**Comment by DarkNekros** [comment]
I'm on **Frugalware Linux x64** using the 64bit archive file and I've :+1: the ones that applies to me.

**Comment by joaomoreno** [comment]
Everyone, can you still reproduce with the downloadable archive?

[32bit](https://az764295.vo.msecnd.net/stable/e724f269ded347b49fcf1657fc576399354e6703/VSCode-linux-ia32-stable.zip)
[64bit](https://az764295.vo.msecnd.net/stable/e724f269ded347b49fcf1657fc576399354e6703/VSCode-linux-x64-stable.zip)

**Comment by artem-sidorenko** [comment]
@joaomoreno it looks good for me

**Comment by ayanamist** [comment]
@joaomoreno No, it still has the issue on Ubuntu 14.04 with your provided archive.

**Comment by joaomoreno** [comment]
@ayanamist Do you have any extensions installed? Which? Could you zip up your `extensions` folder and send it to me?

**Comment by DarkNekros** [comment]
@joaomoreno not better for me :-1:

**Comment by joaomoreno** [comment]
@DarkNekros Do you have any extensions installed? Which? Could you zip up your extensions folder and send it to me?

**Comment by ayanamist** [comment]
@joaomoreno I have removed my extension from `$HOME/.vscode/extensions`, no better luck.

**Comment by jrobeson** [comment]
@joaomoreno : I'm using Fedora 24, and I'm still having the problem even when trying the versions you posted. I had extensions, but deleted them to reinstall them (but couldn't), so I can't provide them for you :(

**Comment by joaomoreno** [comment]
@ayanamist @jrobeson Both you guys still see this issue after wiping `~/.vscode/extensions`?

**Comment by ayanamist** [comment]
@joaomoreno Yes, still have issue after wiping extensions dir.

**Comment by DarkNekros** [comment]
@joaomoreno sure :smile_cat: !

https://frama.link/vscode-extensions

**Comment by jrobeson** [comment]
@joaomoreno : yes I'd `rm -rf ~/.vscode/extensions` shortly after installing 1.3 the first time.

**Comment by devmetal** [comment]
@jrobeson Same problem here. I also deleted the folder, but it still not working on ubuntu 16

**Comment by joaomoreno** [comment]
@ayanamist & all:

Can someone set a breakpoint in `extensionsWorkbenchService.ts:163` and trigger the bug? You can achieve this in the Developer tools, clicking `Ctrl-O` and typing `extensionsWorkbenchService` to find the file. I'm interested in the the contents of the `t` array, specifically if there are any extensions in there with an `undefined` `manifest` property:

![image](https://cloud.githubusercontent.com/assets/22350/16684470/850fc2da-4505-11e6-82ba-9dec9634600c.png)

**Comment by joaomoreno** [comment]
@ayanamist Would you be willing to do a live Skype debugging call with me?

**Comment by ayanamist** [comment]
i have got off my work and can not touch my laptop for several hours, sorry

**Comment by mquandalle** [comment]
I also encounter this bug. I set the breakpoint as indicated in https://github.com/Microsoft/vscode/issues/8859#issuecomment-231325130 but this code wasn't called when clicking on the “Install” button of the new extension panel.

Also, I don’t know if this is directly related but the console is full of the following error:

```
shell.ts:416 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,
    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),
    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),
    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,
    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),
    at emitOne (events.js:90:13),
    at Socket.emit (events.js:182:7),
    at readableAddChunk (_stream_readable.js:153:18),
    at Socket.Readable.push (_stream_readable.js:111:10),
    at Pipe.onread (net.js:531:20)

e.onUnexpectedError @ shell.ts:416
(anonymous function) @ shell.ts:318
e.onUnexpectedError @ errors.ts:73u @ errors.ts:88
(anonymous function) @ winjs.base.js:43
(anonymous function) @ winjs.base.js:38
winjs.base.js:45
```

**Comment by belstgut** [comment]
https://ptpb.pw/SYtL.png

**Comment by RobertoMalatesta** [comment]
>  I have removed my extension from $HOME/.vscode/extensions, no better luck.

**remove ~/.vscode as well**

**Comment by ayanamist** [comment]
@RobertoMalatesta when i comment it, i have no other directories in `.vscode`

**Comment by RobertoMalatesta** [comment]
@ayanamist it's a weird bug.
I did the same reasoning at first, then, seeing that .vscode was expendable since it was empty I nuked it.
Hth,

--R

**Comment by joaomoreno** [comment]
To whoever still sees this issue:

- Shutdown Code
- Run `ps ax | grep code` in a terminal, do you see any Code process still running?

**Comment by artem-sidorenko** [comment]
@joaomoreno yes, it was the case for myself. I killed all code processes before I tried the provided zips

**Comment by mquandalle** [comment]
It’s also the case for me:

```
$ ps ax | grep code
  716 ?        Ssl    0:44 /usr/share/code/code
  718 ?        S      0:00 /usr/share/code/code --type=zygote --no-sandbox
  979 ?        Sl     0:10 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=SharedProcess
 6417 ?        Sl     0:07 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap git /home/mquandalle/github/push-notifications utf8 /usr/share/code/code 
26116 pts/6    S+     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn code
```

**Comment by joaomoreno** [comment]
Yeah great to know. I'm now investigating why it is that on Linux these processes stay alive for longer than expected.

**Comment by devmetal** [comment]
@DarkNekros Its worked me also. Thank you!

**Comment by WhiskeyBeard** [comment]
@joaomoreno Thanks for all the suggestions! I will try the kill process one when I get to the office. Hopefully that works, I will also try the debug session if needed. Let you know in a few.

**Comment by joaomoreno** [comment]
**Workaround confirmed:** kill all running `code` processes. Or simply restart your machine.

**Comment by weput** [comment]
my 2 cents..
on KDE-neon (based on ubuntu 16.04)... removing visual-studio code (sudo dpkg -r visual-studio-code) did the trick.

**Comment by karser** [comment]
I killed VSCode, and the extensions tab seems to be working on Ubuntu 14.04.
```bash
killall -9 code
```

**Comment by joaomoreno** [comment]
After a full day of debugging, here's the outcome. Thanks to all the people that reported the issue and helped reproduce it! Special thanks to @svarogg who did a Hangout session with me and helped me get some more clues on this mystery.

**The bug:** The shared process stays alive, after Code is shutdown.

It **reproduces** in Linux, 1.2.1 only with telemetry enabled. Does **not reproduce** in 1.1.1 nor 1.3.0.

The listening of [`SIGTERM`](https://github.com/Microsoft/vscode/blob/1.2.1/src/vs/base/parts/ai/node/ai.app.ts#L44) within the shared process prevented it from shutting down whenever the main process sent that signal. It would then trust all the telemetry adapters to properly dispose which for some reason never happened.

This listener has been removed since, explaining why it can't be reproduced in 1.3.0.

### Workaround

Kill all code processes OR restart machine.
