### ISSUE TITLE
References: Results - only seeing one line of history

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#88591]
Issue Type: <b>Bug</b>

[This comment](https://github.com/microsoft/vscode/issues/64531#issuecomment-487943139) by @jrieken has a screenshot showing multiple entries of history.

But if I invoke Find All References on several different symbols in turn, then click Clear, the "No results" list only has one entry, which is my most recent search:

![image](https://user-images.githubusercontent.com/6726799/72322408-329b6980-369e-11ea-8ef2-38fa18a040d3.png)

VS Code version: Code - Insiders 1.42.0-insider (c3c54744ab61fa2a44569d00cf686601aad873bf, 2020-01-14T05:29:53.324Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
True story.
