### ISSUE TITLE
Vscode black screen/frozen on Manjaro

### ISSUE THREAD

**Issue by dlqs** [microsoft/vscode#88598]
- VSCode Version: 1.41.1
- OS Version: 5.4.6-2-MANJARO 

Steps to Reproduce:

1. Fresh install of vscode
2. Run `code`
3. App opens with black screen, but if I wait long enough it eventually shows the correct start screen but in a frozen state. 

Running with logging gives this:
```
  ~  code --verbose --log critical
[main 2020-01-14T09:29:52.694Z] Sending env to running instance...
[11143:0114/172952.719002:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2020-01-14T09:29:52.783Z] Sent env to running instance. Terminating...
[main 2020-01-14T09:29:52.784Z] Lifecycle#kill()
```
 - Weirdly enough, running with `--verbose` returns immediately but the window remains black and will show the correct start screen (in a frozen state) if I wait long enough.
 - Another weird point: I am unable to take screenshots with `xfce-screenshooter` (the defaut screenshot tool on XFCE Manjaro), it just shows whatever is behind the vscode window. Which leads me to think that this could be a problem with my window manager or DE.

More info:
```
~ echo $XDG_CURRENT_DESKTOP
XFCE
~ echo $GDMSESSION
xfce
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dlqs** [comment]
I magaged to resolve the issue by running vscode with `--disable-hardware-acceleration` flag. [Steps](https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration)

The same issue happens with the nightly insider build, as well as Chromium. From what I can gather online ([link 1](https://forum.manjaro.org/t/chromium-and-brave-do-not-work-in-sandbox/107112/10), [link 2](https://forum.manjaro.org/t/manjaro-is-good-on-intel-comet-lake-yet/108197)) , disabling GPU acceleration is required to make Electron/Chromium apps work correctly with Manjaro and Comet Lake. 

More info for others:
Processor: Intel Core i5-10210u
Kernel: 5.4.6.2-MANJARO
OpenGL: Mesa DRI Intel UHD Graphics (Comet Lake 3x8 GT2)

**Comment by kjs3** [comment]
Had the same issue on a new Thinkpad X1 7th gen (i7-10710U Comet Lake).

Switching my driver from `intel` to `modesetting` seems to have fixed it. 

Also seems to have fixed issues with all Chromium/Electron apps (Chrome, Brave, etc).
