### ISSUE TITLE
I want to know the detailed  information about my extension.

### ISSUE THREAD

**Issue by garygao12580** [microsoft/vscode#88595]
I want to know the detailed  information about my extension. But there is no way except I report it by myself.  So could VsCode can provide a report page to show these information? Or just can provide an OpenAPI that I can get these information by myself.  My concerns include installs, uninstalls, installs today, uninstalls today, active users, stars, etc.

Thanks very much.

**Comment by sandy081** [comment]
Please file the feature request against Marketplace.

@fiveisprime FYI
