### ISSUE TITLE
Typescript and Javascript Language features

### ISSUE THREAD

**Issue by pravindot17** [microsoft/vscode#88592]
Issue Type: <b>Bug</b>

Getting errors every time I am trying to save, 
`The TypeScript language service died 5 times right after it got started. The service will not be restarted.`

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|40, 29, 18|
|Memory (System)|16.00GB (4.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
file-icons|fil|1.0.21
macros|ged|1.2.1
duplicate|gee|1.0.1
vscode-commitizen|Kni|0.8.4
vscode-typescript-tslint-plugin|ms-|1.2.3
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.0
vscode-import-cost|wix|2.12.0
material-theme|zhu|3.2.1

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate - see [this comment](https://github.com/microsoft/vscode/issues/88497#issuecomment-573945505) from @mjbvz advising installing an extension that will allow you to try typescript@next and see if this resolves your issue.
