### ISSUE TITLE
autoGuessEncoding takes precedence over filetype encoding

### ISSUE THREAD

**Issue by gabriellima** [microsoft/vscode#88601]
When both `autoGuessEncoding` and `encoding` are set, the guessed encoding type is selected even though there are specific settings for some filetypes.

```
    "[txt]": {
        "files.encoding": "windows1252"
    },
    "[django-txt]": {
        "editor.tabSize": 2,
        "files.encoding": "windows1252",
    },
    "files.autoGuessEncoding": true,
```

Opening a pt-br .txt file with this example, VS Code will choose the guessed `ISO 8859-5` incorrectly. It's incorrect both because the "guess" is wrong and because it didn't take the specific setting over. 

Disabling the `autoGuessEncoding` will make it open as `windows1252`. 

Without any of those settings, file will open as `utf-8`, the default encoding.

**Comment by bpasero** [comment]
I fear this could break existing use cases. To fix this, simply put the `"files.autoGuessEncoding": false` into the language specific overrides. That should work.
