### ISSUE TITLE
Azure ARM JSON standard export should not give warnings by default. 

### ISSUE THREAD

**Issue by cartbramer** [microsoft/vscode#88602]
Issue Type: <b>Bug</b>

I exported a resource group from Azure to to ARM JSON file. When opening this file in Visual Studio Code, I see a lot of warnings, indicating that the JSON contains invalid values. It seems that the definitions of what values are (not) allowed need a bit of an update. 

See screenshot for some warnings. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/13511904/72338586-1b23a700-36c5-11ea-8397-3f3b3caa2e5c.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo
It should have schema `"$schema` at top level and VSCode uses this schema to validate JSON.
Most likely you need to report this issue for project that provides values and/or schema.

Or provide exact cases when values are validated not according to the schema. The fact that it is default export doesn't guarantee that validation errors are wrong.
