### ISSUE TITLE
VSCode running inside Docker on Ubuntu crashes very frequently

### ISSUE THREAD

**Issue by BobPitha** [microsoft/vscode#88608]
Issue Type: <b>Bug</b>

There is no apparent pattern here, sometimes it happens before code has fully started up, sometimes it runs for quite a while before hanging and then crashing. Sometimes it happens when I'm building, sometimes when I'm editing, sometimes just out of the blue when I'm not doing anything.

--disable-extensions doesn't seem to change the frequency of the crashes.

Sometimes when code crashes, it will then hang immediately upon restart, always. Intellisense doesn't seem to work then, the code stays all gray instead of being colored. The only way to get past that state is to delete everything underneath ~/.config/Code/User/workspaceStorage. Then it goes back to the same crash frequency.

The frequency of crashes has gone up significantly rather recently, which is strange because nothing obvious has changed in our environment. The Dockerfile we use to create the docker image hasn't been modified, nor have the options given to docker to start the container.

Please help. It's almost totally unuseable.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.10-050310-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 3090)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (2.75GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ros|ms-|0.6.2
python|ms-|2020.1.58038
cpptools|ms-|0.26.2
cmake|twx|0.0.17
debug|web|0.24.0

</details>

**Comment by bpasero** [comment]
@BobPitha are you using the remote extension to run VSCode onto a workspace inside a docker container?

**Comment by BobPitha** [comment]
I am not. I am runnig VSCode directly inside the container.

**Comment by bpasero** [comment]
@BobPitha that seems unsupported if you check https://code.visualstudio.com/docs/supporting/requirements

**Comment by BobPitha** [comment]
So you're saying that VSCode is only supported on those systems it was explicitly tested on? I'm running Ubuntu 16.04, so I guess I'm SOL even if I move out of the Docker. That's a shame.

Well, sorry to have bothered you all, I guess I'll have to find a different IDE.

**Comment by bpasero** [comment]
@BobPitha I possibly did not understand your setup then. Are you able to explain this setup in a way to us that we can run it to reproduce?
