### ISSUE TITLE
Issues with error splash bar.

### ISSUE THREAD

**Issue by virtyaluk** [Microsoft/vscode#8860]
- VSCode Version: 1.3.0
- OS Version: Win 10 Ent Version 1511

Steps to Reproduce:

1. Open some js file in VS Code
2. Make sure you have ESLint package installed and no .eslint in project folder.
3. Start typing something in the editor and getting an error splash with no way to close it.
4. See attached gifs for more info.

![81cc716aa315476b1d714ae3b2ac6486](https://cloud.githubusercontent.com/assets/795984/16672488/19f5fd30-44af-11e6-9f03-44fc9a840373.gif)

![b39497d34fcc7286a8ae82841073bb4a](https://cloud.githubusercontent.com/assets/795984/16672499/285da01c-44af-11e6-9c53-b43ddd47fd28.gif)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#98

**Comment by dbaeumer** [comment]
This is an issue with the eslint extension. Moving
