### ISSUE TITLE
Namespace 'google.maps.places' has no exported member 'AutocompleteService'

### ISSUE THREAD

**Issue by luckylooke** [microsoft/vscode#88600]
- VSCode Version: 1.41.1
- OS Version: Mac OS 10.14.6 Mojave

Steps to Reproduce:

1. include google lib into project
```html
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=MY_KEY&libraries=places"></script>
```
2. install typings
```
npm install --save @types/googlemaps
```
3. create ts file where you reference AutocompleteService
```
type AutocompletePrediction = google.maps.places.AutocompleteService.AutocompletePrediction;
```
4. VScode hilight AutocompleteService with error
```
Namespace 'google.maps.places' has no exported member 'AutocompleteService'.
```
5. When I click through places VScode navigates to places namespace in .../node_modules/@types/googlemaps/index.d.ts and I can clearly see AutocompleteService class there

Does this issue occur when all extensions are disabled?: Yes

Additional screenshots posted on stackoverflow here: https://stackoverflow.com/questions/59723371/namespace-google-maps-places-has-no-exported-member-autocompleteservice

Thank you 🙏

**Comment by mjbvz** [comment]
Will answer on SO

**Comment by luckylooke** [comment]
@mjbvz many thanks 🙏
