### ISSUE TITLE
Search panel > files to include/exclude: filename autocomplete

### ISSUE THREAD

**Issue by panoschal** [microsoft/vscode#88609]
It seems to me that issue #61487 is not completed, or that they did not refer to the same thing.
I would want dropdown autocomplete here, in order to easily select the files you want to include/exclude.
![image](https://user-images.githubusercontent.com/27917356/72349959-2d620d00-36e6-11ea-8655-72e37986cc5c.png)

**Comment by roblourens** [comment]
We have considered this in the past, but closed it as out of scope: https://github.com/microsoft/vscode/issues/54260
