### ISSUE TITLE
При выделении блока вертикальная линия подсвечивается у родителького блока

### ISSUE THREAD

**Issue by ToxaLarin** [microsoft/vscode#88603]
Issue Type: <b>Bug</b>

При установке курсора на "{" или "}", происходит выделение начала и конца этого блока. Кроме того подсвечивается вертикальная линия слева, но она подсвечивается не у выделенного блока, а у родительского. 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.95GB (1.75GB free)|
|Process Argv|--user-data-dir=E:\Soft\VSCodePortable-x64\Data\code --extensions-dir=E:\Soft\VSCodePortable-x64\Data\code\extensions|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.39.3
Bookmarks|ale|10.6.0
better-comments|aar|2.0.5
githistory|don|0.4.13
Go|ms-|0.12.0

</details>

**Comment by IllusionMH** [comment]
Баги следует заводить на английском. Bugs should be reported in English.

Works as intended. This is active indent level guideline (`editor.highlightActiveIndentGuide`) and block is placed on indent level created by its parent, not one which it creates itself.

You can use https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2 with `"bracket-pair-colorizer-2.showVerticalScopeLine": true` to highlight current scope.
