### ISSUE TITLE
Startup: encoding configured for language from extension

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode#88605]
Issue Type: <b>Bug</b>

I've set an specific file encoding for .pas (pascal) files, like this:

 "[pascal]": {
        "files.encoding": "windows1252"
        },

In this scenario, with VSCode open in advance, if I go to file explorer, right-click the file and select OPEN IN VSCODE, it opens the file using the file encode I've set. 

However, if I do this with VSCode closed, it doesn't change the file encoding and open the file using the default encoding (UTF-8).

![VSCode Encoding](https://user-images.githubusercontent.com/15204313/72343759-654d5e00-36ae-11ea-98a0-4088c28444e0.gif)

VS Code version: Code - Insiders 1.42.0-insider (980d8ef1371b14e80162d88e88f45e15f8632070, 2020-01-14T09:07:36.433Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
pascal|ale|8.0.3
pascal-formatter|ale|2.2.0
project-manager|ale|10.9.1
read-only-indicator|ale|3.0.3
vscode-django|bat|0.19.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
python-preview|don|0.0.4
git-extension-pack|don|0.1.3
githistory|don|0.4.13
jupyter|don|1.1.5
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
gitlens|eam|10.2.0
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.162
MagicPython|mag|1.1.0
vscode-docker|ms-|0.9.0
vscode-postgresql|ms-|0.2.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.58038
remote-containers|ms-|0.96.0
remote-ssh-edit-nightly|ms-|2020.1.11041
remote-ssh-nightly|ms-|2020.1.11041
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0
vsliveshare|ms-|1.0.1456
resourcemonitor|mut|1.0.6
embrace|myc|1.0.0
autodocstring|njp|0.4.0
remove-comments|pli|1.2.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.1
clockify-tracker|tob|3.0.11
remove-empty-lines|use|0.0.6
vscode-icons|vsc|9.7.0
vscode-wakatime|Wak|2.2.1
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Yeah, this is very likely an issue with us not supporting Pascal out of the box. You have an extension installed and here is what happens:
* VSCode opens
* the file opens
* the editor does not know any handler for the file extension and at first the file will be "plain text"
* as such the encoding will be UTF-8
* extension host starts
* now the Pascal extension is there
* the language mode changes to Pascal
* 🐛 however the encoding does not change since the file already loaded

I am not sure how to fix this. Blocking the file from loading until the extension host is there also seems wrong to me.

**Comment by RicaBenhossi** [comment]
Yes... I supposed that VSCode followed the steps you described... Sorry for my mistake. I should have done the tests with all extensions disabled to make sure that the problems aren't caused by them. My bad 🤭

> Blocking the file from loading until the extension host is there also seems wrong to me.
Agreed... 
Maybe the best is to implement something in the extension, for example: after the extension loads, the extension itself reload the .pas file with the right encode (if there is a .pas file already opened in VSCode).

Don't know if it is the best solution (or if it is a solution at all). Either way, I think that any adjustments should be done on the extension.

I'll close the issue here...

@bpasero thank you for the analysis and, sorry again for didn't have tested it with the extensions disabled. 👍
