### ISSUE TITLE
VS Code doesn't recognize project files

### ISSUE THREAD

**Issue by halcwb** [Microsoft/vscode#8861]
- VSCode Version: 1.3.0
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. clone http://github.com/halcwb/GenUnitApp.git 
2. cd GenUnitApp 
3. code .

Expect in the statusbar detection of 2 projects. 
No projects are detected.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#611
