### ISSUE TITLE
API: add row support to document layout info

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#88612]
atm we only have `column` support for opened document, which is insufficient because the editor is using it for both vertical and horizontal, ex. lets say you have 2 editors
- above each other
- next to each other

in both cases you will get `column: 1` for first editor and `column: 2` for second editor.

with the introduction of rows, we can now know how the grid is laid out, so for the `above each other` example we should get

- `column: 1, row: 1`
- `column: 1, row: 2`

**Comment by gjsjohnmurray** [comment]
I don't think it's a simple as `column` and `row`. For instance, the layout in the screenshot [here](https://code.visualstudio.com/updates/v1_25#_grid-editor-layout-viewcolumn).

See also #51001

> atm we only have column support for opened document

Note that the ViewColumn is for an editor, not a document. See #49741

**Comment by ctf0** [comment]
> I don't think it's a simple as column and row. For instance, the layout in the screenshot

exactly, but if i want to save the current editors/documents layout, its not possible, u can check https://github.com/ctf0/vscode-save-editor-layout which try to save the layout using the currently available api but sadly its not enough

> Note that the ViewColumn is for an editor, not a document

i meant the `activeEditor.document` as find the column info under the document props and use it with `showDocument`

**Comment by gjsjohnmurray** [comment]
Maybe you need an API to return a _layout_ in the format that the `vscode.setEditorLayout` command takes. @bpasero might know how feasible this would be to add.

**Comment by bpasero** [comment]
Related to https://github.com/microsoft/vscode/issues/15178. Possibly a duplicate depending on how far the API goes. But I do think that for an extension to operate on editors, it needs this layout info too.

//cc @jrieken

**Comment by ctf0** [comment]
> Maybe you need an API to return a layout in the format that the vscode.setEditorLayout command takes

that would be a good starting point, or maybe expose how the editor could remember the layout setup between sessions to an Api & this way we dont need any extra work unless there are other use cases where this info would be relevant
