### ISSUE TITLE
When removing a specific panel and hiding the panel, don't show+hide another panel

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88613]
Context: https://github.com/microsoft/vscode/issues/88529

This is creating a terminal process without the user initiating it.

**Comment by sandy081** [comment]
@Tyriar I don't think there is any control with the panel here. This is working as expected.
When a panel is removed, a default panel is shown if panel is open.

**Comment by Tyriar** [comment]
@sandy081 so for the refactor one where the panel is hidden when removing, hide the panel before removal?

**Comment by Tyriar** [comment]
@sandy081 looks like the panel doesn't hide anymore so it's no longer a problem.
