### ISSUE TITLE
Commiting pending changes before change accessor leaves due to read access?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88610]
I often see `Commiting pending changes before change accessor leaves due to read access`. in the dev tools running out of sources and I have no clue what this means or what I should do to prevent it.

This warning needs some explanation or be removed if useless.

![image](https://user-images.githubusercontent.com/900690/72352450-95165900-36e2-11ea-950c-38df3331fc41.png)

**Comment by alexdima** [comment]
@bpasero I can remove this, but do you remember doing anything that caused it?

**Comment by aeschli** [comment]
Verified in code

**Comment by bpasero** [comment]
I cannot reproduce now anymore but I think I often saw it when saving an untitled file (where we quickly replace the editor with its saved version).
