### ISSUE TITLE
Strange folding strategy

### ISSUE THREAD

**Issue by scriptingstudio** [microsoft/vscode#88611]
I expect that the function level is the upper folding level, but any line inside with the same indentation wins. It is not logical.

**Comment by gjsjohnmurray** [comment]
What language? The [documentation](https://code.visualstudio.com/docs/editor/codebasics#_folding) explains:

> Folding ranges are by default evaluated based on the indentation of lines. A folding range starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

Some languages provide syntax aware folding, unless you have opted to revert to indentation-based folding. More in the the docs.

**Comment by scriptingstudio** [comment]
@gjsjohnmurray, powershell

**Comment by gjsjohnmurray** [comment]
/causedByExtension - please check existing issues in the extension's repo, and open a new one there if necessary. Here's one way to get to the repo of an extension:

![image](https://user-images.githubusercontent.com/6726799/72353728-6f865100-36dc-11ea-9c9a-90c506f13fca.png)
