### ISSUE TITLE
UI becomes laggy when using git stage selected ranges

### ISSUE THREAD

**Issue by sslupsky** [microsoft/vscode#88615]
Issue Type: <b>Bug</b>

I have noticed for quite a while now (months going on a year) that the UI becomes very sluggish and laggy.  I have not identified a method that triggers the lag immediately but it appears to me to be related to git.   In particular, when using git stage selected ranges, after several selected ranges are staged and committed, inevitably the lag occurs.

I have disabled extensions and the problem still arises.

This problem appears to get worse with each update.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (8.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
doxdocgen|csc|0.5.2
arm|dan|0.7.0
gitlens|eam|10.2.0
hex-fmt|ker|1.0.0
cortex-debug|mar|0.3.4
git-graph|mhu|1.21.0
python|ms-|2020.1.58038
cpptools|ms-|0.26.3-insiders3
devicetree|plo|0.1.1

</details>

**Comment by joaomoreno** [comment]
Can you reproduce the issue again, but first:

- Open `Developer: Show Running Extensions`
- Click the `Start Extension Host Profile` button at the top right, it's the circle
- Reproduce the issue
- Stop profile

You can show me a screenshot of the profile result. You can also send me the profiling results.

**Comment by sslupsky** [comment]
I'll work on this.  I need to create a few commits first :-)

**Comment by jahangirahmad** [comment]
I have lag problem with my vscode. but after while i guess problem caused by chrome. when i developing vue app i use vue devtools and after while i have lag in chrome page too. and i have lag in vs code when typing too. i uninstalled so many extensions. and do profiling too. but i had no problem in extensions.

**Comment by jahangirahmad** [comment]
Today i changed these vs code settings:
`"editor.quickSuggestions": false,
  "editor.quickSuggestionsDelay": 90,
  "editor.parameterHints": false,
  "editor.autoClosingBrackets": "always",
  "editor.formatOnType": false,
  "editor.suggestOnTriggerCharacters": false,
  "editor.acceptSuggestionOnEnter": "off",
  "html.autoClosingTags": false,
  "html.format.enable": false,
  "html.validate.scripts": false,
  "html.suggest.html5": false,
  "html.format.extraLiners": ""`

and my problem solved. but i suggestions is too good.

**Comment by sslupsky** [comment]
Here is a screen shot of the process explorer at the time I experience the lag:

![Screen Shot 2020-02-24 at 10 38 38 AM](https://user-images.githubusercontent.com/16888734/75176808-173a6a00-56f2-11ea-928a-c1b4baa69ac4.png)

**Comment by joaomoreno** [comment]
@sslupsky 

Can you reproduce the issue again, but first:

- Open `Developer: Show Running Extensions`
- Click the `Start Extension Host Profile` button at the top right, it's the circle
- Reproduce the issue
- Stop profile

You can show me a screenshot of the profile result. You can also send me the profiling results.
