### ISSUE TITLE
Settings Sync: ignoredSettings still sunk first time

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#88623]
Even though I have this configuration:

``` json
    "sync.ignoredSettings": [
        "editor.fontFamily"
    ],
```

On the first sync operation, the `editor.fontFamily` setting is brought down, and since it is set to a font that is not on my machine (e.g. `Fira Code`), I get the weird default times new roman (?) font.

Here is my `settings.json`:

``` json
{
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "files.autoSave": "afterDelay",
    "workbench.settings.editor": "json",
    "workbench.colorTheme": "Cobalt2",
    "files.autoSaveDelay": 1000,
    "sync.ignoredSettings": [
        "editor.fontFamily"
    ],
    "sync.ignoredExtensions": [
        "ms-vscode-remote.remote-wsl"
    ]
}
```

- Sync this from "Machine A"
- On clean "Machine B", install VS Code and then turn on synchronization

**Result:** On "Machine B", the `editor.fontFamily` setting is brought down, so if you don't have `Fira Code` installed you'll see the font change pretty easily.

From then on if I make changes to the `fontFamily`, those changes are not synchronized, which is what I expect. This is the first sync scenario where I don't want the `fontFamily` to come down at all.

**Comment by sandy081** [comment]
This is fixed now.
