### ISSUE TITLE
Settings Sync: No way to specify a platform specific extension

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#88625]
I am synchronizing settings across Windows and Mac.  

On my Windows machine, I have the `Remote - WSL` extension, which does not make sense to install on my Mac.  

There doesn't seem to be a way to specify by platform which extensions to sync (or not sync). `ignoredExtensions` makes sense if I don't want to synchronize across any machine, but if I add a second Windows machine into the mix (or rebuild a Windows machine), then the WSL extension is not installed.

**Comment by sandy081** [comment]
We do not have platform specific extensions support from Marketplace. We can implement this once we have such support.

**Comment by sandy081** [comment]
This gets supported automatically when platform specific extensions is supported.
