### ISSUE TITLE
Adding Folder To Workspace

### ISSUE THREAD

**Issue by 1sdc0d3r** [microsoft/vscode#88629]
- VSCode Version: 1.41.1
- OS Version: Mac Mojave 10.14.6 

It doesn't allow me to navigate to a deeper folder to add a folder to a workspace, It just adds that folder that I am currently in. I am able to go up in the file structure but not down.

Steps to Reproduce:

1. open a workspace folder
2. right-click, add folder to workspace
3. try to navigate to a deeper folder.... (via clicking on a folder, or CMD + up/down)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
This works just fine for me. What are you doing differently and can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

![addFolder](https://user-images.githubusercontent.com/1926584/72446254-7f249900-37b3-11ea-8c32-cdd98cc3d612.gif)

**Comment by 1sdc0d3r** [comment]
When I try to navigate to a deeper folder I am not able to…
