### ISSUE TITLE
quickfix context menu cant be toggled off from extension

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#88628]
### Env
```
Version: 1.42.0-insider
Commit: 980d8ef1371b14e80162d88e88f45e15f8632070
Date: 2020-01-14T09:03:12.949Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. run `editor.action.quickFix` from extension
2. re-run it again, it wont go away
3. using `hideSuggestWidget` wont work either

an example of usage could be found at https://github.com/ctf0/vscode-problems-fix-runner/blob/master/extension.js#L111

the funny thing is the cursor can change its position and the context menu still persist.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Yeah, quickFix opens a native menus (if quick fixes are available) and there is no command to hide that. It's a user menu and only the user should close this. Why is this a problem? What are you trying to achieve?

**Comment by ctf0** [comment]
am building an extension that loop over the quick fixable problems in the document and give the user the chance to simply run the command and chose the fix, so he/she doesn't need to do the manual labor.

the issue is i can toggle the menu on/off with the same keybinding or with `escape` but i cant do that from the extension.
like running `editor.action.quickFix` multiple times in a row wont do anything, its like the menu has hijacked the focus from the editor and u cant control it in anyway.

**Comment by jrieken** [comment]
> am building an extension that loop over the quick fixable problems in the document and give the user the chance to chose the fix per each, so he/she doesn't need to do the manual labor.

Not sure that I understand. Is this like the `editor.codeActionsOnSave`-setting (which applies fixes on save)? Generally, you cannot interact with the UX. While most things work with commands, some don't esp. those that are native and outside our control.

**Comment by ctf0** [comment]
i apologies if i wasn't clear, heres what i do
- we get all the document diagnostics https://github.com/ctf0/vscode-problems-fix-runner/blob/93c4441efe87c47aae94c241c0c099c4619388f0/extension.js#L63

- then one by one, we run the quick fix command 
https://github.com/ctf0/vscode-problems-fix-runner/blob/93c4441efe87c47aae94c241c0c099c4619388f0/extension.js#L111

- then we wait for the user to make a choice b4 going to the next problem
 https://github.com/ctf0/vscode-problems-fix-runner/blob/93c4441efe87c47aae94c241c0c099c4619388f0/extension.js#L127

- however if the user didnt make a choice or wanted to escape the active problem and go to next, then we should hide the menu first b4 moving on otherwise the cursor will move but the menu will remain where it was first toggled

---

to test the example for ur self, plz follow
- install https://github.com/streetsidesoftware/vscode-spell-checker
- clone https://github.com/ctf0/vscode-problems-fix-runner
- run debugger
- open a new doc and write a couple of any misspelled words on different lines ex
```
tset

cosnt
```
- now run `Problems Fix Runner` from the command panel as shown in https://user-images.githubusercontent.com/7388088/72210739-cf0c1300-34c8-11ea-8239-1650ebdc1ec8.gif

**Comment by jrieken** [comment]
Ok, I understand but I also have to disappoint you to say that this isn't something extensions are for.  You can programmatically get code actions via the [`vscode.executeCodeActionProvider`](https://code.visualstudio.com/api/references/commands)-command but cannot drive the UI like that.

**Comment by ctf0** [comment]
ok np, at least is there a way to simulate a key press ? 
also could u tell me what `quickFixWidgetVisible` is for or how to use it ?

**Comment by ctf0** [comment]
update: got around the limitation using `registerCompletionItemProvider`
