### ISSUE TITLE
Panel name changes after showing the panel

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#88637]
When using view container and views for panel, and if view container and view has different names, panel name is getting changed after the panel is shown.

![Kapture 2020-01-14 at 22 26 03](https://user-images.githubusercontent.com/10746682/72383980-de839a00-371c-11ea-92e8-d394fa36f36f.gif)

**Comment by sandy081** [comment]
This is tricky to fix. We are merging the view with view container only after the panel is opened. Until then it is hard to know if a view can be merged or not.

Until we find a proper solution I am renaming the debug container to use the same name as repl view.

@isidorn FYI

**Comment by isidorn** [comment]
Thanks for letting me know. The workaround works for me.

**Comment by sbatten** [comment]
I'm thinking that the names in panel should be stable (always using the container name) and we should have some other UI element that displays the name of the containing view if merged with the header. e.g. this terrible mock up but using the style of call stack line numbers:
![image](https://user-images.githubusercontent.com/6561887/74972463-9704c380-53d6-11ea-95b9-faba48972213.png)


![image](https://user-images.githubusercontent.com/6561887/74972296-4d1bdd80-53d6-11ea-992e-631bb66618bb.png)

**Comment by isidorn** [comment]
Not sure if I understand your idea 100%. But if we show the name of the view in the place where the name of the container is expected then we should render them the same.
For the user they are the same, it is just an implementation detail that one is a container, another is a view. A user is not aware of this, thus rendering them differently does not bring a clear benefit imho

**Comment by sbatten** [comment]
Once we have multiple views, the distinction is more clear. Just as in the activity bar the icons refer to a container and the headers refer to views. The user is aware of the difference between the scm container and the gitlens views.

**Comment by sbatten** [comment]
I think this is as addressed as we'd like by 56b8c192051b277ed775332ae24a0ab3425e2947. This issue only surfaces if the view is different from the container which we should strive for not being the case in a default layout. In a non-default layout, we have a cache to prevent this in most cases.
