### ISSUE TITLE
VS code does not close after git push

### ISSUE THREAD

**Issue by asmalik** [microsoft/vscode#88632]
Sometimes after synchronizing changes with my personal gitHub, I was not abble to close the editor. I have to kill the process on task manager in order to close it

**Comment by joaomoreno** [comment]
What happens when you try to close it? Can you send a screen recording of the issue?

**Comment by asmalik** [comment]
Hi,
I recorded the issue (please find it in the zip file).
After executing git push command, visual studio code refuse to close.

Regards,

Malik
[footage_vsc_cant_close.zip](https://github.com/microsoft/vscode/files/4106413/footage_vsc_cant_close.zip)
