### ISSUE TITLE
Can't drag the vscode window after switching from laptop display to monitor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88635]
I don't have good repro steps, but this happens sometimes

- Have vscode window open on macbook display
- Close lid, plug in external display
- Click and drag on the vscode title bar, it doesn't respond

Reloading the window fixes it, and maximizing the window (alt+click on green + button) also fixes it.

I noticed this happening with Slack weeks ago, and vscode more recently, if that helps narrow it down to an Electron update.

macOS 10.14.6

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?

**Comment by roblourens** [comment]
I don't even remember this issue. I don't think I have seen it lately.
