### ISSUE TITLE
VS code not providing intellisense unless I focus the terminal or the sidebar

### ISSUE THREAD

**Issue by thorizer** [microsoft/vscode#88631]
VSCode Version:
    1.41.1
    x64
    OS Version:
    Windows 10
    Steps to Reproduce:

1 open any file type, 
2 focus the file: IntelliSense won't work, 
3 focus the terminal or sidebar: IntelliSense will work 
4 refocus the file: IntelliSense won't work

https://i.imgur.com/EEb4Xy6.mp4

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@thorizer do you see this issue with other languages or just this one? I didn't reproduce this issue so I'm wondering if it's language/framework specific.

**Comment by thorizer** [comment]
@rebornix  every language.  it's not framework dependent. even a json file does not work unless i lose focus of the current file.

**Comment by alexdima** [comment]
@thorizer Given it only sometimes reproduces for you, and it doesn't reproduce for us, please let us know what precise steps you're doing when it reproduces.
