### ISSUE TITLE
Recent Tasks Are Sorted Least-Recently-Used First

### ISSUE THREAD

**Issue by d-bahr-dci** [microsoft/vscode#88634]
Issue Type: <b>Regression</b>

In a recent update (not sure of the version) the recent tasks list changed from most-recently-used to least-recently-used:

![Tasks](https://user-images.githubusercontent.com/44477887/72378048-7d7ca780-36c5-11ea-8843-9908b0767e93.png)

This severly inhibits usability of the recent tasks lists, especially when navigating with keyboard, because it requires skipping through tasks.

I am aware of the Rerun Last Task command, but sometimes that command is not applicable. For example, when compiling a bunch of libraries with dependencies on each other, it can be useful to compile them back-to-back, and when the recent tasks are listed most-recently-used first, it becomes much easier and faster to navigate.

Please bring back the most-recently-used sorting of the recent tasks list, or provide a settings option so we can select the ordering!

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:59:52.065Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (7.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
doxdocgen|csc|0.5.2
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
Go|ms-|0.12.0
perforce|sle|3.2.0

</details>

**Comment by alexr00** [comment]
I tried to reproduce the issue with version 1.41.1 and with Insiders (1.42) and the recently used tasks are still sorted with the most recently used at the top. Please try disabling all installed extensions!

**Comment by d-bahr-dci** [comment]
This occurs with a multi-root workspace.

If I execute "Run Task..." directly, then the issue doesn't occur. If I instead do Ctrl+P and then type "task", then the issue occurs as previously mentioned.
