### ISSUE TITLE
Add shortcuts to select different tabs

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#8863]
- VSCode Version: 1.3.0
- OS Version: OS X 10.11.5

This is a feature request to default `CMD + 1` to go to the first tab, `CMD + 2` to go to the second tab and so on...

The current behaviour seems unusual as it splits the editor into 2 or 3 sections. Also, similar shortcuts from `CMD + 4` to `CMD + 9` are not utilised.

**Comment by bpasero** [comment]
We decided to not change this (popular) keybinding. You can modify your keybindings to get this behaviour though, e.g. 

`{ "key": "cmd+1",                "command": "workbench.action.openEditorAtIndex1" }`
