### ISSUE TITLE
[Winpty] The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2)

### ISSUE THREAD

**Issue by lbrown1591** [microsoft/vscode#88639]
VSCode Version:
Version: 1.41.1

OS Name: Microsfot Windows 10 Enterprise
Version: 10.0.17763 Build 17763

Steps to Reproduce:

Open VSCode
Open a folder
Ctrl + J
Error Message:The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2}) failed to launch (exit code: 2)

I get a similar error when I try bash and cmd. 

Extensions: none

![image](https://user-images.githubusercontent.com/35009873/72387684-b0389700-36e9-11ea-8118-33e819c7b9c9.png)

**Comment by Tyriar** [comment]
Do you have anti-virus software installed and if so can you whitelist this folder from its scans?

```
C:\Users\<you>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\node-pty\build\Release
```

**Comment by lbrown1591** [comment]
Ugh since I opened this issue yesterday I upgraded from build 17763 to 18362 and now it work :confused: anyways. Thank you for your help.

**Comment by Tyriar** [comment]
@lbrown1591 oh ok, great! I'll close this then as you're on the new system which is now working.
