### ISSUE TITLE
Existing Keybindings Preview

### ISSUE THREAD

**Issue by Chiramisu** [microsoft/vscode#88630]
Show a sneak peak / preview of the existing bindings that conflict with the keyboard shortcut you are attempting to assign when mousing over the "existing commands" link in the window below:

![keybinding-conflict](https://user-images.githubusercontent.com/944951/72374051-5ec6e280-36be-11ea-892a-cf81e80743e6.png)

This would prevent navigating away from the command you're trying to set and having to navigate back to it after you identify the command which is already using that keybinding. If we could mouse over that link and see a list of commands and contexts (i.e. the "When" column), it would be very helpful.

**Bonus**: The option to navigate to the conflicting command **after** we overwrite the keybinding to resolve any conflicts of further define scope would be an added bonus.

**Comment by sandy081** [comment]
/duplicate

#77696

**Comment by Chiramisu** [comment]
Oh, fantastic! Thanks, I couldn't find one. I guess my search terms didn't catch it. 😉
