### ISSUE TITLE
Breakpoint position becomes larger than the file size

### ISSUE THREAD

**Issue by Sen-real** [microsoft/vscode#88645]
This is a common issue, not a problem of a special kind of language. Let's just take typescript for example: 

Repro steps:
1. Launch VS Code (I'm using v1.41.1), and open a folder which contains test.ts
2. Open this test.ts, make sure it has exactly 3 lines of code:
import * as vscode1 from 'vscode';
import * as vscode2 from 'vscode';
import * as vscode3 from 'vscode';
**### NOTE: there's no empty line after line 3
3. Remove all breakpoints. Then add a break point on line 3
Check the "Breakpoints" panel of VS Code - the result is correct
4. Go to the end of line 2, and press ENTER to add a new line
Check the "Breakpoints" panel of VS Code - the result is still correct; the line number of break point becomes "4"
5. Press BACKSPACE to delete the new added line
Check the "Breakpoints" panel of VS Code - the result is wrong; the line number of break point is still "4", and my file now has only 3 lines of code.

**Comment by isidorn** [comment]
Great catch with nice steps. Thanks a lot.
You can try out the fix with new insiders from tomorrow.
