### ISSUE TITLE
vue相关的扩展都失效了

### ISSUE THREAD

**Issue by 1243112190** [microsoft/vscode#88644]
Issue Type: <b>Bug</b>

vue相关的扩展都失效了，比如格式化vue扩展和代码提示的扩展，只有刚进去是正常的，过一会就失效了，已经卸载重装扩展，甚至卸载重装vscode都没用，希望帮忙看看是什么问题，谢谢

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.67GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.41.2
debugger-for-chrome|msj|4.12.5
vetur|oct|0.23.0
open-in-browser|tec|2.0.0

</details>

**Comment by WWongs** [comment]
有没有是vuter的问题，我重新安装了旧版本的vuter (0.22.6)就好了。
