### ISSUE TITLE
Toggle Control Characters doesn't work in 1.3.0

### ISSUE THREAD

**Issue by artem-sidorenko** [Microsoft/vscode#8864]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 3.19.0-32-generic

Steps to Reproduce:

1. Menu View -> Toggle Control Characters
2. You get `No handler found for the command: 'editor.action.toggleRenderControlCharacters'. An extension might be missing an activation event.`

**Comment by mrmlnc** [comment]
Duplicate #8823

**Comment by Tyriar** [comment]
Cheers @mrmlnc :smiley:

**Comment by jd-carroll** [comment]
Was this supposed to be fixed in 1.3.1?
