### ISSUE TITLE
Breakpoints work only when added prior to starting debug session

### ISSUE THREAD

**Issue by krworks** [microsoft/vscode#88648]
I am having an issue getting breakpoints to work when added after starting a debug session.  This is a Chrome Debug session, and the application type is a React application.  If it was a source mapping issue, breakpoints would not work at all but they definitely work perfectly when added prior to starting the debug session.  It's a bit debilitating since I have to constantly restart the session when tracking a bug.

**Comment by roblourens** [comment]
Could you try our new experimental debug adapter and tell me whether it happens there? https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

**Comment by krworks** [comment]
Prior to installing the extension (and following instructions to get the inspector to work; i.e. setting debug.chrome.useV3=true in settings.json) any breakpoints I would add or remove after the fact would have no effect.

Now, I'm happy to report that I can.  This is great, and thank you for your efforts.

**Comment by roblourens** [comment]
Great! Thanks for trying it.
