### ISSUE TITLE
IntelliSense errors appear on advanced SASS syntax

### ISSUE THREAD

**Issue by Hydra9268** [microsoft/vscode#88643]
Let's say I have a file named mixins.scss that contains a simple mixin

```
@mixin colors($p1, $p2, $p3) {
    background-color: $p1;
    border-color: $p2;
    color: $p3;
}
```

I load this mixins file into a main scss file and use it:

```
@use 'mixins';

@include mixins.colors( "#FFFFFF", "#FFFFFF", "#FF0000" );
```

According to SASS's website this is the correct syntax. However, in VSC, both the @use and dot notation in mixins.colors appears to throw IntelliSense errors. Further, hex colors that use to appear in the mixin expression inside the main SCSS file no longer work with imported mixins.colors syntax.

Here's an example of what I'm referring to
https://i.imgur.com/NBv3Vs2.png

And an example of the hex color issue
https://i.imgur.com/7tyfuqp.png

**Comment by octref** [comment]
I don't think this error comes from VS Code — I don't see any error here. If after disabling all extension and this still reproduces let us know.

**Comment by Hydra9268** [comment]
I have no extensions installed
https://i.imgur.com/E4OQX8B.png

**Comment by octref** [comment]
Where is the source of that error? You can find out by hovering over it or opening Problems View.

![image](https://user-images.githubusercontent.com/4033249/75694768-eca26100-5c5d-11ea-8746-d16ac6ff7b10.png)

**Comment by Hydra9268** [comment]
https://i.imgur.com/WjPK9va.png - Expects a semi-colon at mixins
https://i.imgur.com/okx0I5y.png - Expects an at-rule or selector

**Comment by octref** [comment]
This is already fixed in latest insiders version, https://code.visualstudio.com/insiders/, which we'll release either this week or next week.

**Comment by Hydra9268** [comment]
Thank you, friend. :)
