### ISSUE TITLE
Empty Arrat instead All Symbols Array - vscode.executeWorkspaceSymbolProvider command

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#88649]
- VSCode Version:1.41.0
- OS Version:Linux x64 5.3.13-arch1-1

Steps to Reproduce:
1. Use: `await vscode.commands.executeCommand('vscode.executeWorkspaceSymbolProvider', "");`
result: empty array
expected: array of all symbols

I know that it should work, because I read it in another issue.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
