### ISSUE TITLE
[powershell] Incorrect Powershell Parsing

### ISSUE THREAD

**Issue by MichaelMcBreen** [Microsoft/vscode#8865]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Create new file
2. Name it TEST.ps1
3. Add this text
 $c.'#text'
 SHOULD NOT BE MARKED AS STRING
 'SHOULD BE MARKED AS STRING

4. VSCode incorrectly parses the text.
The second line should not be shown as a string.
The third line should be shown as a string
5. Paste same text in the ISE to compare

**Comment by Aculeo** [comment]
Same problem with spaces. Here's an image:
![highlighting-error](https://cloud.githubusercontent.com/assets/3977620/16682641/d31c54de-44fb-11e6-9b78-ad5ac7b18a6d.jpg)

**Comment by Amedama96** [comment]
Same with hyphens.
![hyphes](https://cloud.githubusercontent.com/assets/18225518/16691224/c23eb772-4566-11e6-8a3c-48d243c5d4c6.png)
