### ISSUE TITLE
Allow to force open in same window from the recently opened picker

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#88665]
Currently, "Open Recent..." defaults to opening folders in the same window. If you hold <kbd>Ctrl</kbd>, they will be opened in a new window instead as indicated in the UI:

![](https://i.imgur.com/fAtBvlS.png)

With `"window.openFoldersInNewWindow": "on"`, the behavior changes to _always_ opening the folder in a new window, regardless of whether <kbd>Ctrl</kbd> is held or not, effectively taking away some flexibility.

I think it would be convenient if `"window.openFoldersInNewWindow": "on"` **flipped** the default behavior of "Open Recent..." instead, so that holding <kbd>Ctrl</kbd> could still be used to open the folder in the same window. This would be useful for people like me who want to open folders in a new window _most of the time_, so the more common action would have a simpler shortcut (<kbd>Enter</kbd> vs <kbd>Ctrl</kbd>+<kbd>Enter</kbd>).

**Comment by bpasero** [comment]
This is a very good idea and I would accept a reasonably small PR to solve this. The picker is being created from: https://github.com/microsoft/vscode/blob/af037fb9edf90c59ddc101e846e169003d33c8f5/src/vs/workbench/browser/actions/windowActions.ts#L67

I would think the label also needs to change to reflect this flip.

**Comment by dvrylc** [comment]
I'd like to work on this!

**Comment by dvrylc** [comment]
I'm trying to read `window.openFoldersInNewWindow` by adding the configuration service as an argument to the class, but I can't seem to find the call site where services are provided to the `OpenRecentAction` and `QuickOpenRecentAction` constructors. 

https://github.com/microsoft/vscode/blob/af037fb9edf90c59ddc101e846e169003d33c8f5/src/vs/workbench/browser/actions/windowActions.ts#L148-L159

**Comment by bpasero** [comment]
If this is about accessing the configuration service, you can just add it to the constructor to have it injected. Maybe check how we use it in other places.

**Comment by joe-nm** [comment]
I have this working, but I'll give dvrylc a chance to submit since he was first.  My branch is https://github.com/joe-nm/vscode/tree/recentFileWithSettings.
A couple questions:
Are new tests expected with a change like this?
This change requires comparing settings values, should that value be inline or imported from somewhere (I looked around a little and only saw inline values)?

**Comment by bpasero** [comment]
No I think this would not require tests as it is probably hard to test this UI only change. 

If the setting has no constant somewhere already, using the inline value is fine.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/72a381699f549b3f1c7c38b2b9a6d9a1de06f603 pushed support to force open in same window when `Alt` key is pressed, I think that is a good compromise to allow full control independent of the setting.

**Verification**
* make sure you can force open a recent entry in the recently opened folders quick pick (File > Open Recent > More...) by holding Alt key when clicking even if `"window.openFoldersInNewWindow": "on"` is configured

**Comment by JacksonKearl** [comment]
With this on macOS, `Cmd+Enter` opens the folder in a new window when `"window.openFoldersInNewWindow": "default" | "off"` is set, but `Opt+Enter` opens the folder in the same window when  `"window.openFoldersInNewWindow": "on"` is set. These should be the same in my opinion.

**Comment by bpasero** [comment]
@JacksonKearl that was the intent of my change to allow to override your setting. It seems it is working exactly as advertised. Please comment back if you disagree.

**Comment by JacksonKearl** [comment]
I think the key commands should be the same between the two. i.e. it should be `Cmd+Enter` to make the folder open in the same window when `"window.openFoldersInNewWindow": "on"`, as it is `Cmd+Enter` to make the folder open in a different window then `"window.openFoldersInNewWindow": "off"`.

**Comment by bpasero** [comment]
@JacksonKearl understood, but that is not what is implemented :). It is non trivial to get all the things right based on settings because you can have different settings for folders vs files, so you would almost have to update the placeholder when the folder is active vs. a file. That is why I did not want to go down that path.
