### ISSUE TITLE
Autocomplete / Intellisense stops working for JS with JSX

### ISSUE THREAD

**Issue by lynxtaa** [microsoft/vscode#88662]
- VSCode Version: 1.41.1, 1.42.0-insider (Commit: b40e5ce729ce49b7311e92f65f1f21c514aa9c2c)
- OS Version: Windows 10 Pro 1909

Steps to Reproduce:

1. `npx create-react-app react-app`
2. Open created folder
3. Open `App.js`. Intellisense stops working, CPU usage is constantly around 10% .

Does this issue occur when all extensions are disabled?: Yes, I'm using fresh install

Have this issue after 1.41.0 release, no problem in 1.40.2

<img width="748" alt="Screenshot 2020-01-15 11 32 00" src="https://user-images.githubusercontent.com/22496946/72418319-a49dac80-378b-11ea-8918-4b5dcf8c3ce6.png">

**Comment by lynxtaa** [comment]
Also, constant "Loading..." when I hover over the function:

<img width="462" alt="Screenshot 2020-01-16 13 45 48" src="https://user-images.githubusercontent.com/22496946/72518669-e3546500-3866-11ea-952b-6867a7342e81.png">

How can I debug this issue? I'm using clean installation

**Comment by doksara** [comment]
I have the same issue.

**Comment by mjbvz** [comment]
Where is your code stored? Somewhere besides the `c:` drive?

**Comment by lynxtaa** [comment]
I've moved my code to `c:` drive and now it works. Thank you @mjbvz !

**Comment by doksara** [comment]
My code is on c:drive all the time. I tried completely uninstalling it (including extensions), moving it to d: drive, etc. Same happens with Insiders version. Funny thing is that it works fine for a few minutes and then it completely gets stops working.

**Comment by lynxtaa** [comment]
@doksara , I've downloaded Insiders version in zip archive, created `data` folder inside (it makes it portable). Then I've created react app: `npx create-react-app react-app` and opened App.js. It magically works when I do it in c: drive.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/35512
