### ISSUE TITLE
Base64 data URI as script not working in WebView

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#88667]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Extract the HTML file in [reprex_reprex.zip](https://github.com/microsoft/vscode/files/4064201/reprex_reprex.zip)
2. Open the `reprex_reprex.html` in a web browser, the code highlighting works as supposed.
3. Open a WebView to show the file with the following example code in a VSCode extension:

```typescript
const file = "/path/to/reprex_reprex.html"
const panel = window.createWebviewPanel("webview", "WebView",
        {
        },
        {
            enableScripts: true,
        });
const html = fs.readFileSync(file);
panel.webview.html = html;
```

Then the highlight.js embedded as base64 data URI in script does not work.

I don't find any documentation that says whether such base64 data URI is supported or not.

Related: https://github.com/Ikuyadeu/vscode-R/issues/187

**Comment by IllusionMH** [comment]
I'm not sure about defaults for CSP for web views.
Have you tried to configure `<meta http-equiv="Content-Security-Policy">` and add `data:` to `script-src`?

**Comment by renkun-ken** [comment]
Base64 data URI is perfectly supported. My mistake in replacing WebView resource Uri in my code. Should be fixed by https://github.com/Ikuyadeu/vscode-R/pull/188.
