### ISSUE TITLE
Weird semantic coloring in TS

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#88666]
Issue Type: <b>Bug</b>

* use the following settings:
```json
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{ "scope": "entity.name.type", "settings": { "fontStyle": "underline" } },
			{ "scope": "storage, keyword, constant, variable.language.this, variable.language.super.ts", "settings": { "fontStyle": "bold" } },
			{ "scope": "variable", "settings": { "foreground": "#333" } },
			{ "scope": "keyword.operator", "settings": { "foreground": "#001080ff" } },
			{ "scope": "comment", "settings": { "foreground": "#008000", "fontStyle": "" } }
		]
	},
```

* open `src\vs\editor\test\browser\controller\cursor.test.ts`

| BEFORE | AFTER |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/72422418-b62e8680-3782-11ea-9654-8e3c3930f344.png) | ![image](https://user-images.githubusercontent.com/5047891/72422396-a9119780-3782-11ea-86eb-da58a3787cb4.png) |

VS Code version: Code - Insiders 1.42.0-insider (b40e5ce729ce49b7311e92f65f1f21c514aa9c2c, 2020-01-15T05:40:01.024Z)
OS version: Windows_NT ia32 10.0.18362

**Comment by aeschli** [comment]
fixed by https://github.com/microsoft/vscode/commit/a2d46d4b68013eb0a2ccee5991acb864ad501a01
