### ISSUE TITLE
Freezing linux

### ISSUE THREAD

**Issue by cyberhorse** [Microsoft/vscode#8866]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.2.0-040200-generic

Steps to Reproduce:

1. Start VScode
2. Open a PHP file
3. Within a minute of looking around in the file, the whole machine freezes - need to restart to fix it.

I think it was an issue in 1.2.1 as well, but only happened maybe once a week. Now it happens within minutes.

Further information, running linux from encrypted USB drive.

**Comment by Tyriar** [comment]
@cyberhorse what distro are you on?

**Comment by cyberhorse** [comment]
Linux Mint 17.3 Rosa 64-bit with Xfce

**Comment by cyberhorse** [comment]
Latest version seems to have fixed the issue.
