### ISSUE TITLE
Electron process keeps checking /proc/<pid>/cmdline when shell is launched

### ISSUE THREAD

**Issue by tjarlama** [microsoft/vscode#88663]
Issue Type: <b>Bug</b>

If I launch shell (zsh) inside VS code, its parent process keeps checking /proc/<shell_pid>/cmdline (every 200ms) until the shell is closed. Is this how vscode wait for the child process or there is something wrong?

Steps to reproduce: 

1. Open terminal 
2. Use [this](https://github.com/iovisor/bcc) tool to trace open syscalls.

**Sample output**
```
TIME(s)       PID    COMM               FD ERR PATH
0.000000000   2294   electron           38   0 /proc/4480/cmdline
0.200104000   2294   electron           38   0 /proc/4480/cmdline
0.400092000   2294   electron           38   0 /proc/4480/cmdline
0.600100000   2294   electron           38   0 /proc/4480/cmdline
0.800120000   2294   electron           38   0 /proc/4480/cmdline
1.000100000   2294   electron           38   0 /proc/4480/cmdline
1.200103000   2294   electron           38   0 /proc/4480/cmdline
1.400097000   2294   electron           38   0 /proc/4480/cmdline
1.600103000   2294   electron           38   0 /proc/4480/cmdline
1.800107000   2294   electron           38   0 /proc/4480/cmdline
2.000106000   2294   electron           38   0 /proc/4480/cmdline
2.200001000   2294   electron           38   0 /proc/4480/cmdline
2.400105000   2294   electron           38   0 /proc/4480/cmdline
2.600103000   2294   electron           38   0 /proc/4480/cmdline
2.799968000   2294   electron           38   0 /proc/4480/cmdline
3.000107000   2294   electron           38   0 /proc/4480/cmdline
3.200101000   2294   electron           38   0 /proc/4480/cmdline
3.400114000   2294   electron           38   0 /proc/4480/cmdline
3.600036000   2294   electron           38   0 /proc/4480/cmdline
3.800169000   2294   electron           38   0 /proc/4480/cmdline
```
VS Code version: Code - OSS 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-20T11:11:01.597Z)
OS version: Linux x64 5.5.0-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.64GB (5.19GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@RMacfarlane afaict the only place we're using cmdline is in https://github.com/microsoft/vscode/blob/master/src/vs/base/node/ps.sh when `ps` isn't present for process manager/issue reporter. Is this needed every 200ms?

**Comment by Tyriar** [comment]
@tjarlama did you have the process explorer (Help > Open Process Explorer) open at the time?

**Comment by tjarlama** [comment]
@Tyriar No, process explorer was not open at the time. I don't think ps.sh is responsible for this. If it was ps.sh then i should see it's pid instead of the electron pid, right?
Also full cmdline of the electron process looks like this
`
/usr/lib/electron6/electron --type=renderer --disable-color-correct-rendering --no-sandbox --field-trial-handle=<big_number>,<another_big_number>,<small_number> --disable-features=LayoutNG,SpareRendererForSitePerProcess --lang=en-US --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-path=/usr/lib/code --node-integration --webview-tag --no-sandbox --no-zygote --background-color=#2e3440 --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=<some_different_number> --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
`

**Comment by Tyriar** [comment]
The only other place I see in the codebase it is `ExtHostTunnelService.$findCandidatePorts`, but I wouldn't expect that to get called when not in a remote workspace @alexr00

**Comment by tjarlama** [comment]
@Tyriar I haven't enabled any extensions other than cpptools. Any way to check if `findCandidatePorts` is causing this problem, from my side ?
Also, can you confirm if `hookupOnLoadHandlers` [link](https://github.com/microsoft/vscode/blob/6aab56dd6255f0e5512d01ac520007bc14ef7f45/src/vs/workbench/contrib/webview/browser/pre/main.js#L485) has nothing to do with this issue. Because i see a 200 timeout and this happens every 200ms. Don't know how to debug further.


Adding a sample strace output:
```
[pid  1373] futex(0x7fff43a23238, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  1373] ioctl(113, TIOCGPGRP, [1428]) = 0
[pid  1373] openat(AT_FDCWD, "/proc/1428/cmdline", O_RDONLY) = 38
[pid  1373] fstat(38, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
[pid  1373] read(38, "/bin/zsh\0", 1024) = 9
[pid  1373] close(38)                   = 0
[pid  1373] futex(0x7fff43a23288, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=3515, tv_nsec=738267647}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
```

**Comment by RMacfarlane** [comment]
@tjarlama Does `which ps` return a path? The `ps.sh` script shouldn't be called repeatedly, but it would be called both when the process explorer is open, or the issue reporter window has been opened and "Performance Issue" is selected. Did you have the issue reporter window open?

**Comment by alexr00** [comment]
The "every 200ms" means that this wouldn't be coming from `findCandidatePorts` since there's nothing that would call that with that kind of frequency.

**Comment by tjarlama** [comment]
@RMacfarlane 
> Does which ps return a path? 
Yes /usr/bin/ps, provided by procps-ng package
> Did you have the issue reporter window open?
No i don't have issue reporter open. This happens only if I open terminal and goes away when I close it.

**Comment by Tyriar** [comment]
Ah, this is what's doing it: https://github.com/microsoft/node-pty/blob/f3099ad49177197203b27e9450aef7c03530c375/src/unix/pty.cc#L542

There was this issue in the past which was closed out of scope as it's not worth the effort to try and fix https://github.com/microsoft/vscode/issues/63723
