### ISSUE TITLE
Don't zoom titlebar with ctrl plus and ctrl minus

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/vscode#88676]
Issue Type: <b>Bug</b>

When I use `ctrl +` and `ctrl -` to set the entire window font size, the zoom also impacts the app-native (rather than system-native) titlebar.

It would be nice if the titlebar behaved more like something from the system and didn't zoom along with the rest of the UI.  Otherwise if I zoom the UI too much, I end up with gigantic window chrome.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

**Comment by atrauzzi** [comment]
Not quite.

**Comment by sbatten** [comment]
@atrauzzi we currently zoom the titlebar when using the custom titlebar because the menubar is present and it needs to zoom for accessibility reason. If you hide the menubar with `"window.menuBarVisibility": "hidden"` in your `settings.json`, it will stop zooming with the rest of the application.

**Comment by atrauzzi** [comment]
@sbatten - I don't want to remove the menu+title bar though.  Shouldn't it obey system-set accessibility settings?  Not in-application zoom?
