### ISSUE TITLE
[FIXED] Terminal fonts bug

### ISSUE THREAD

**Issue by TriMoon** [microsoft/vscode#88673]
In regard to issues like #81160, #22797, #7116, #30289 and maybe more that are about the Powerline fonts not displaying correctly:
- One seems to need to add `PowerlineSymbols` to the **fontFamily** of the editor or terminal settings inside VSC. eg:
   - `"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback', PowerlineSymbols"`

After that they are displayed correctly in my case, the same goes for other fonts :wink: 

This info should somehow be made available in some documentation or wiki of this project IMHO...
It took me rather some time to find the needed info via search engines...

**Comment by Tyriar** [comment]
Normally to set up powerline you use a special font that includes the powerline symbols in it, this seems like a fallback that might work but may end up with slightly off symbols?

**Comment by TriMoon** [comment]
@Tyriar 
You ofcourse need the Powerline symbol fonts, or anyother that you use, installed for them to display correctly.
This is just a FYI for users of Visual Studio Code (VSC) to aid them into having proper fonts displayed inside their editor and terminal inside VSC...
It's obvious how to do it once one knows about it, but for new users of VSC it isn't that natural to check that setting (see the many issues and replies posted) :wink: 

Besides IMHO if you add `PowerlineSymbols` at the **end** of the current value without having the font installed won't change anything because the glyps can't be found then, same as it is when you do have them installed without having it mentioned inside the setting :smiley: 

PS: the line i used as example is only correct for my system, other users might have other defaults...

**Comment by Tyriar** [comment]
Thanks for the info, closing it out though as there's already a FAQ on the topic at https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-powerline-fonts-in-the-integrated-terminal
