### ISSUE TITLE
console.warn in unit tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88672]
Steps to Reproduce:

1. run our unit tests
2. notice the following output:

`[1040:0115/125822.998550:INFO:CONSOLE(174)] "Cannot register 'a'. This property is already registered.", source: file:///home/bpasero/development/monaco/out/vs/platform/configuration/common/configurationRegistry.js (174)
`

I am not sure if we should simply remove the `console.warn` usage here.

**Comment by sandy081** [comment]
Removed `console.warn` as the extension contributions are validated already.
