### ISSUE TITLE
Reveal in Explorer / Explorer Terminology Change Request

### ISSUE THREAD

**Issue by ashclarke** [microsoft/vscode#88675]
This is a request to change the terminology used in the Windows version of VS Code for the `Reveal in Explorer` option.

I often find myself clicking `Reveal in Explorer` when I mean to click `Reveal in Sidebar`. 

I believe this is because I associate the term "Explorer" with the workspace/folder treeview in VS Code and the solution explorer treeview from Visual Studio, not the Windows "File Explorer".

![image](https://user-images.githubusercontent.com/963023/72436370-27c4ff80-3798-11ea-8138-1c43bbbf12fc.png)

- Yellow box highlights: Use of the term `Explorer` meaning different things
- Grey arrow: What `Reveal in Explorer` does
- Blue arrow: What `Reveal in Sidebar` does

My request is to change the option text to something like `Reveal in File Explorer` for Windows or discuss some other way to differentiate it from the VS Code "Explorer".

**Comment by gjsjohnmurray** [comment]
I think this is a good suggestion. The proper name for what "Reveal in Explorer" launches on Windows seems to be "File Explorer".

**Comment by isidorn** [comment]
Makes sense. Thank you for the suggestion.
