### ISSUE TITLE
Can’t watch `Return Value`

### ISSUE THREAD

**Issue by zgrgrcn** [microsoft/vscode#88678]
- VSCode Version: 1.41.1
- OS Version: Mojave 10.14.5

Steps to Reproduce:

1. In debug mode breakpoint after return bracket
2. I can check value of `return value` from `VARIABLES` tab
3. Right-click and Add To Watch and press enter
3. In `WATCH` section getting error `Return value: SyntaxError: Unexpected identifier`

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
What debugger is this?
How can you check the value of return value from VARIABLES tab?

**Comment by zgrgrcn** [comment]
@weinand 
Visual Studio Code default Debugger (small bug in the left corner), there is a breakpoint on the return line and then I am pressing step over(f10).
A screenshot will be more descriptive.
![Screen Shot 2020-01-17 at 09 28 25](https://user-images.githubusercontent.com/22799339/72589443-4d731580-390c-11ea-9a26-c5e27aa000d7.png)

As you can see the Return value is the `newPrice` array. But in Watch section, there is an error.

**Comment by weinand** [comment]
Since "Return value" is not a legal JS expression, I don't think that you can use it as a watch expression.

A debug extension could support this special case, but I don't see the benefit of this.

@connor4312 @roblourens what's your opinion?

**Comment by connor4312** [comment]
Yea, I'm kind of dubious on it as well, since the return value shows at the top of the call stack whenever possible, and when it's not in the call stack it's not valid to watch.
