### ISSUE TITLE
vscode.typescript-language-features

### ISSUE THREAD

**Issue by jeffbum** [microsoft/vscode#88677]
Issue Type: <b>Bug</b>

Crashing on every save. Not sure bug.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (7.18GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-postgres|cko|1.1.11
vscode-eslint|dba|2.0.14
gitlens|eam|10.2.0
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
vscode-peacock|joh|3.2.0
chat|kar|0.31.0
json2csv|kha|0.0.1
mssql|ms-|1.8.0
vsliveshare|ms-|1.0.1456
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
bash-beautify|sha|0.1.1
vscodeintellicode|Vis|1.2.3

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
