### ISSUE TITLE
"/etc/zshrc:7: command not found: locale" After Shell command install 'code' from PATH 

### ISSUE THREAD

**Issue by meditant** [microsoft/vscode#88684]
Hello,

After execute"Shell command install 'code'..." i have "/etc/zshrc:7: command not found: locale" error in VSCode and in terminal. i'am unable to use std commande like ls...

I try to uninstall but nothing change.

The path : $PATH /Applications/Visual Studio Code.app/Contents/Resources/app/bin

VSCode 1.41.1
Mac Os Catalina 10.15.2

I unable to find where VSCode change the default path, thats block before .zprofile loading !

Best

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by janosh** [comment]
Getting the same error. Here's a screenshot of what I see when trying to debug the currently active Python file.

![debug-error](https://user-images.githubusercontent.com/30958850/72530009-5f9a7880-3866-11ea-8682-f9fd536a3c65.png)

**Comment by janosh** [comment]
This error is really inhibiting.

@joaomoreno Any ideas what might be the cause? Would welcome even a temporary workaround.

**Comment by janosh** [comment]
Temporary fix seems to be adding

```sh
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```
to the top of `.zshrc`.
