### ISSUE TITLE
Can't inspect git diff for Jupyter Notebooks in the Git pane

### ISSUE THREAD

**Issue by allanleal** [microsoft/vscode#88685]
Issue Type: <b>Bug</b>

Jupyter Notebooks with changes when inspected through the Git pane loads the file as Jupyter Notebook, instead of showing it as plain text so that one can inspect the changes. 

The Git diff view should show the plain text file.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-36-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (20 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|62.83GB (24.34GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rerun-last-command|Cam|0.0.1
vscode-quick-select|dba|0.2.8
gitlens|eam|10.2.0
code-runner|for|0.9.15
latex-workshop|Jam|8.6.0
python|ms-|2020.1.58038
cpptools|ms-|0.26.3-insiders3
supersub|qui|0.5.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.9.1
ayu|tea|0.18.0
cmake|twx|0.0.17
vscode-icons|vsc|9.7.0
change-case|wma|1.0.0
better-align|wwm|1.1.6
material-theme|zhu|3.2.1

</details>

**Comment by joaomoreno** [comment]
@allanleal Not knowing much about Jupyter Notebooks... can you provide me a small sample repo and steps so that I can reproduce this? Thanks.

**Comment by hkennyv** [comment]
Hi there, I'm having this same issue.

**VSCode**
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**OS**
Mac OS Mojave 10.14.6 (18G95)

It may be an issue with vscode python? https://github.com/microsoft/vscode-python/issues/7905

**Comment by allanleal** [comment]
@joaomoreno 

**notebook.ipynb**
~~~json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hi\n"
     ]
    }
   ],
   "source": [
    "print(\"Hi\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
~~~

~~~
mkdir tmp && cd tmp
# copy notebook.ipynb here
git init
git add --all
git commit -a -m "First commit"
# make a change in notebook.ipynb
# now go to Git view in vscode - instead of showing the diff, as json file, it opens the notebook with Jupyter support
~~~

**Comment by joaomoreno** [comment]
This is an issue with the Python extension, which seems to automatically open the Jupyter notebook and close the text editor as soon as the user opens it, even though it might be the diff editor. You quickly see the diff editor and then it gets closed automatically and gets replaced by a Jupyter notebook:

![Peek 2020-01-21 10-00](https://user-images.githubusercontent.com/22350/72789949-e9668f00-3c34-11ea-9c6b-11efda08dbc9.gif)

I've found you can disable this behavior using the `python.dataScience.useNotebookEditor` setting:

![image](https://user-images.githubusercontent.com/22350/72789872-c89e3980-3c34-11ea-9dee-ee6541b6d330.png)

I still think this is bad behavior from the Python extension, so I'd recommend filing an issue on that extension. cc @isidorn

**Comment by isidorn** [comment]
fyi @luabud

**Comment by luabud** [comment]
This is now being tracked here: https://github.com/microsoft/vscode-python/issues/9395.
