### ISSUE TITLE
odd behavior when switching files after performing a text search

### ISSUE THREAD

**Issue by mehgcap** [microsoft/vscode#88680]
Issue Type: <b>Bug</b>

1. Install and run the NVDA screen reader (tested with 2019.2)
2. Open at least two files in VS Code.
3. Perform a search (ctrl-f) in one of them.
4. Press escape to close the search.
5. Switch to the other file.

Problems:
1. Pressing escape often exits the mode in which NVDA is able to interact with VS Code. I have to press escape a second time to get back to this mode.
2. When switching files, NVDA often reports the result of a search in the new file, even though I have only searched in the previous file, not the new one to which I just switched. It's as though the search were still open, but I have no way to verify that and don't know if there's a command to close it. I thought pressing escape in the search would do the job.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.16.0-4-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.73GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: git.domain.com|
|OS|Linux x64 3.16.0-4-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (2 x 2294)|
|Memory (System)|15.71GB (0.29GB free)|
|VM|100%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.7
vscode-remote-extensionpack|ms-|0.19.0
php-debug|fel|1.13.0

</details>

**Comment by isidorn** [comment]
@mehgcap do you still see this issue? 
If yes, I can try to repro and we try to find the gist of it.
