### ISSUE TITLE
Add "Click to find in files"

### ISSUE THREAD

**Issue by tensiondriven** [microsoft/vscode#88686]
I use Elixir with VSCode.

Often I want to find references to a given symbol/string to find out where it is being called or referenced.  ElixirLS supports finding definitions, but there's no way to find all occurrences of a given string (where a string is being references).  So, I resort to the following workflow:

1) Double click a term
2) Cmd-C to copy
3) Shift-Cmd-F to open Find In Files
4) Cmv-V to paste
5) Enter to search

This shows me all the occurrences of a given string in the Find In Files dialog.

What I'd like is to be able to metakey-click on a string to find all occurrences of a given string.  Another good option would be to have "Find in Files" available as an option in the context menu, similar to "Find References".

**Comment by gjsjohnmurray** [comment]
Did you try omitting your steps 2, 4 and 5? For me it's sufficient to doubleclick to select the term, then when the shortcut invokes Find In Files the term is immediately searched for.

![junk](https://user-images.githubusercontent.com/6726799/72456915-7b960f80-37bd-11ea-8393-37643324f41b.gif)

**Comment by tensiondriven** [comment]
Derp.  Thank you, this is wonderful.
