### ISSUE TITLE
Overwriting binary file is not allowed

### ISSUE THREAD

**Issue by ibuki2003** [microsoft/vscode#88687]
- VSCode Version: 1.41.1 (Occurs also at the latest insider build)
- OS Version: Manjaro Linux 18.1.5 Kernel 5.4.6

Steps to Reproduce:

1. Make a binary file
2. Try to overwrite the binary file
3. VSCode shows me an error message
   > Failed to save 'Untitled-1': File seems to be binary and cannot be opened as text

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Good catch.
