### ISSUE TITLE
Make workbench.action.files.revert action label clearer

### ISSUE THREAD

**Issue by anddam** [microsoft/vscode#88681]
I suggest to rename `workbench.action.files.revert` action from "Revert file" to something more explicative like "Reload file" or "Load file content from disk".

I was looking for this action and I was not able to find it but by searching the web for "manually reload file in vscode" I landed on #17643.

The "revert" part does not make clear that the content will be read from disk, I for one, would expect an action named "revert" to walk back all the undo stack to the state the file tab was initially opened rather than reading content again.

 

edit: clarify period

**Comment by anddam** [comment]
See [#49075](https://github.com/Microsoft/vscode/issues/49075#issuecomment-386886662) for the same kind confusion.

**Comment by bpasero** [comment]
I think `File > Revert File` is a quite established thing to have in an editor. I am not sure changing it would help people that are so used to it.

**Comment by anddam** [comment]
> I think `File > Revert File` is a quite established thing to have in an editor. I am not sure changing it would help people that are so used to it.

I now agree with this, considering even emacs has `revert-buffer`, therefore I am closing the ticket.
