### ISSUE TITLE
Ctrl+D should match whole words instead of substrings

### ISSUE THREAD

**Issue by xiaochuanyu** [Microsoft/vscode#8869]
Is there a way to highlight matching whole words of the word under cursor instead of all substrings?
In VScode, the current behaviour:
![image](https://cloud.githubusercontent.com/assets/1718745/16674113/084a0e54-4483-11e6-8688-d69751d427aa.png)
What I want (as seen in Sublime):
![image](https://cloud.githubusercontent.com/assets/1718745/16674149/4b82ab18-4483-11e6-8c60-537b28b32d7c.png)
This is actually the default behaviour in Sublime Text and IntelliJ based IDEs.

**Comment by joaomoreno** [comment]
Simply toggle that option in the find widget.

![image](https://cloud.githubusercontent.com/assets/22350/16681227/b375631c-44f3-11e6-97be-be161a41f98f.png)

**Comment by xiaochuanyu** [comment]
Wow I didn't expect Find box to be related to the cursor highlighting words. Shouldn't these be two separate settings?
I guess I can live with toggling that on and off for now.

**Comment by joaomoreno** [comment]
cc @alexandrudima

**Comment by alexandrudima** [comment]
I agree that it is possible to wish to search for a substring and then wish to highlight only a full-word selection **both at the same time**, but I think this is quite uncommon and inventing separate UI affordances for "whole word" find and "whole word" selection highlight and "whole word" `Ctrl+D` would not offset their cognitive cost. 

I personally use `alt+w` in this case. It works even if the find widget is not revealed.

@xiaochuanyu Do you have other ideas around this that would make for a better user experience?

**Comment by xiaochuanyu** [comment]
@alexandrudima , what do you think about the following scheme?
1. Find box settings are independent of the highlighting string under cursor (HSUC for short) settings. 
2. Highlight whole word under cursor if there are no text selected, otherwise highlight substrings matching selected text.

This is similar to scheme in Sublime Text except that Sublime Text doesn't actually highlight substrings when you select some text but will allow you to select them via multi-cursor (ctrl-D). Sublime Text only highlights whole words.

**Comment by alexandrudima** [comment]
cc @joaomoreno as the initial author of HSUC.

@xiaochuanyu I am open to disconnecting the HSUC feature from `ctrl-D` and making it not be configurable (i.e. it always matches case sensitive, it never matches whole words, it auto-expands to the current word if the selection is collapsed).

HSUC is not impacting anything actually, it just adds visual decorators to the text. I made the leap of thinking those visual decorators would work great with `Ctrl-D`. i.e. I've made HSUC have the exact same search criteria as `Ctrl-D`, such that HSUC can be used as a preview of what `Ctrl-D` would select next or as a preview of what `Ctrl-F2` will select entirely. Here I am playing with different test cases (whole words, case sensitivity). I sort of like how HSUC tells me what `Ctrl-D` will do ambientally, but again, I am willing to drop this connection, given @joaomoreno agrees too:

I am sorry the screen capture tool does not capture keypresses. But I'm using:
* `alt+c` to toggle case sensitivity
* HSUC tells me immediately where `ctrl-d` will go
* `alt+w` to toggle whole words
* HSUC tells me immediately what matches there are
* at one point near the end I use `ctrl-f2` too, to quickly select all matches.
* I do all of this without any other visual indicators except HSUC

![ctrl-d](https://cloud.githubusercontent.com/assets/5047891/16762104/bc774594-482b-11e6-9b5e-77ff54788ee0.gif)

Maybe it's just me using HSUC as a preview of `ctrl-d` and maybe that does not feel natural. Long story short, now that you've understood my rationale, do you still think they should be separated?

**Comment by joaomoreno** [comment]
Having disliked it once introduced, I grew fonder of the currently implemented behaviour.

**Comment by xiaochuanyu** [comment]
@alexandrudima , I understand your reasoning here to use HSUC as a preview for `ctrl+d` and in fact that is what I use HSUC for much of the time. 

The main point for the scheme I described above is that it saves me from manually toggling the setting to use (whole word or substring) when I do `ctrl+d`. It's determined from whether I highlighted a whole word or some substring (point 2).
Consequently, Find settings must then be separated from HSUC (point 1).

Another point I'd like to make is that I use whole word in Find very rarely relative to using whole word in `ctrl+d` so I have to toggle off whole word for Find after I use it for `ctrl+d` very often. This is because I'm usually using Find to search for something that I don't know the spelling exactly so I don't use whole word so that I don't miss any results.  On the other hand, I know exactly what pattern to search for when using `ctrl+d` because I can see it and I would like to highlight it and search.

The bad thing about this scheme is that you can't do case sensitive `ctrl+d` now.

Would be interesting if some statistics can be collected about what settings Find and `ctrl+d` are used with. Perhaps my habits are exceptional rather than common.

I quote my comment above for reference:

> 1. Find box settings are independent of the highlighting string under cursor (HSUC for short) settings. 
> 2. Highlight whole word under cursor if there are no text selected, otherwise highlight substrings matching selected text.

**Comment by Kongsea** [comment]
I am also anxiously hoping the selection highlight and find settings are separated.

**Comment by craPkit** [comment]
I'd like to join the chorus with @xiaochuanyu: I'm using Ctrl+D and HSUC _exclusively_ case sensitive and whole word, as opposed to Find, which is _mostly_ case insensitive and partial word. I came here by googling for that exact feature.

**Comment by azlan** [comment]
I came from Sublime and these are the default behaviors, case sensitive and whole word.

**Comment by RoyTinker** [comment]
I came from Visual Studio (and a couple of great extensions) and would love to see all instances of the currently selected word highlighted in the scrollbar without having to use `Ctrl+f`.

**Comment by third774** [comment]
Definitely want to see the sublime behavior implemented. It is indispensable when working in HTML.

**Comment by sreeram-boyapati** [comment]
The same is also being used by atom I hope it gets resolved quickly

**Comment by thearegee** [comment]
👍

**Comment by brendanzab** [comment]
I'm just going to voice up and say that I love having substring matching (that is what I use in Atom and ST - can't remember if I configured it or not).

**Comment by atombender** [comment]
I have to agree with all of the above that cmd-D/ctrl-D is not "Find". Atom and Sublime's behaviour is inuitive and requires fewer keystrokes — and VSCode doesn't offer a good story to justify deviating from that behaviour.

**Comment by fandy** [comment]
Any updates on this?

**Comment by vferko** [comment]
Can we close this and create a new issue to disconnect editor selections and HSUC from find selections? I believe this will solve all problems.

In other words ALT+C/+W in editor won't affect find's setting. This way everyone will be able to set selections and HSUC vs find to their preferences and be happy once again.

**Comment by StephenKingg** [comment]
`ctrl + f` and use regular expression:
![Image 3.png](https://ooo.0o0.ooo/2017/06/19/59477a10c0a5a.png)

and then, `ctrl + d` will match whole words instead of substrings:
![Image 6.png](https://ooo.0o0.ooo/2017/06/19/59477a91b39b4.png)

**Comment by StephenKingg** [comment]
`ctrl + f` and use regular expression:
![Image 3.png](https://ooo.0o0.ooo/2017/06/19/59477a10c0a5a.png)
then `ctrl + d` will match whole words instead of substrings:
![Image 7.png](https://ooo.0o0.ooo/2017/06/19/59477b3e74846.png)

**Comment by tino2kp** [comment]
Still one "issue": When anyone ctrl + D in VS CODE at any variable: USD sign ($) followed by some characters, the whole variable gets selected, thus, including the USD sign ($). In Sublime, the behavior is different by only selecting the characters, forgetting about selecting the $. How is this behavior achieved?
![captura](https://user-images.githubusercontent.com/32155919/31786694-edd0b6d2-b4ce-11e7-9c07-91215287e1b9.JPG)

**Comment by atombender** [comment]
@tino2kp: That's related to some *very* idiosyncratic choices in various VSCode grammars. For example, [in Ruby](https://github.com/Microsoft/vscode/issues/18241), `:foo` is considered a whole word (i.e., it includes the colon, which is _not_ appropriate), and [in JSON](https://github.com/Microsoft/vscode/issues/10080), quoted strings are considered a whole word (i.e. it includes the quotes). The latter is particularly egregious. Looks like PHP is equally weird.

**Comment by alexandrudima** [comment]
I will look into making the following changes to Ctrl+D and the selection highlights. The selection highlights will continue to match 100% what Ctrl+D will do; they will remain a reliable preview of what Ctrl+D will select next. Here is the mechanism:

---

#### Ctrl+D temporary disassociation from the find widget toggles
* only when starting with a collapsed selection on a word, Ctrl+D will set an internal flag such that it becomes disassociated from the find widget toggles. 
* it will not flash the find widget toggles when it runs, and it will use whole words and case sensitivity for searching. 
* for as long as Ctrl+D is pressed again, continuously, it will remain disassociated from the find widget toggles and will use whole words and case sensitivity.
* if a find widget toggle is explicitly changed (e.g. pressing alt+w or alt+c or clicking on a toggle), the flag will be reset and Ctrl+D will once again become associated with the find widget toggles.
* if the user changes the selection explicitly (e.g. via mouse), the flag will be reset and Ctrl+D will once again become associated with the find widget toggles.
* any typing or editing will also cause the flag to be reset.

---

This IMHO will make it possible for Ctrl+D to be used more as a poor-man's rename in languages where we don't currently have a rename refactoring: click or navigate via keyboard to the identifier you'd want to rename, press Ctrl+D, the selection will expand to the current word and then will find the next word that matches also case sensitive. I think using both whole words and case sensitive is a sensitive thing to do, as most programming languages are case sensitive AFAIK. While running Ctrl+D, if not all matches are found, toggling the find widget toggles will make it that they can be found via Ctrl+D.

If the user starts with a non-collapsed selection, Ctrl+D will follow the find widget toggles as it does today. 

---

Finally, @tino2kp , Ctrl+D today honors the word definition that comes in via language configuration (as @atombender). May I kindly suggest you open a separate issue such that we can discuss if Ctrl+D should better use `editor.wordSeparators` instead of the language word definition.

**Comment by alexandrudima** [comment]
Some flows:
* in all cases the selection highlighter shows what Ctrl+D will do next

#### Find widget closed - starting with a collapsed selection
 * Ctrl+D uses `wholeWords: true and caseSensitive: true`
 * the find options are briefly shown to reflect the temporary overriden settings
![0-0](https://user-images.githubusercontent.com/5047891/31889797-51156a64-b801-11e7-9933-444fbbe61515.gif)

#### Find widget closed - starting with a non-collapsed selection
 * Ctrl+D uses the find options
 * the find options are briefly shown
![0-1](https://user-images.githubusercontent.com/5047891/31889854-82181e9a-b801-11e7-87de-94bc0425bf8e.gif)

#### Find widget opened - starting with a collapsed selection
 * Ctrl+D uses `wholeWords: true and caseSensitive: true`
 * the find options reflect the temporary overriden settings
 * as soon as the editor loses focus, the find options rollback to their pre-Ctr+D values.
![1-0](https://user-images.githubusercontent.com/5047891/31889962-d61e6a76-b801-11e7-9bf7-0dd5d1954bfc.gif)

#### Find widget opened - starting with a collapsed selection
 * Ctrl+D uses the find options
![1-1](https://user-images.githubusercontent.com/5047891/31890128-601d33c4-b802-11e7-94fa-f3a55efe0e59.gif)

**Comment by atombender** [comment]
@alexandrudima This is fantastic, and exactly what I was wishing for. Thank you for your efforts!

**Comment by ffxsam** [comment]
@alexandrudima Pardon my ignorance.. but what do you mean by "collapsed selection"? I can't see any visual difference in the first two animated GIFs above. How does one make Cmd+D override the 'Find' settings?

**Comment by atombender** [comment]
@ffxsam A collapsed selection is just a technical way of saying "no selection". Technically, it's a selection where the start and end are the same position.

**Comment by ffxsam** [comment]
Got it! Thanks, and thanks to the VS Code team for this awesome update!

**Comment by aybabtme** [comment]
Wow I've been annoyed by this for so long, really glad to see it fixed!
