### ISSUE TITLE
Changed file names in bash/zsh do not update in explorer sidebar, are not always respected

### ISSUE THREAD

**Issue by methodbox** [microsoft/vscode#88699]
Issue Type: <b>Bug</b>

This all seems to have started in the last few months. This behavior does not change with all extensions disabled.

This seems to be related to what appears to be a regression ( due to previous issues opened for the same problem which have then been "fixed" in preview builds) exa. https://github.com/microsoft/vscode/issues/72637.

Currently, if you rename a file in terminal, for example, it isn't reflected inside VS Code. It should be watching for these changes, instead it looks like (as per this issue) it's caching the file names. File name changes are actual file changes and should be reflected in Git; not sure how that is working correctly if the file name is cached.

The end result is that changing the name of a file doesn't reflect in the sidebar correctly, even if you *don't have the file open*, then open it, it *still* shows the old name in the tab.

Using "Reveal in Finder" will take you to the *correctly named* file, i.e. obviously VS Code is referencing the correct file, but it doesn't update itself to show that.

If I make a change to this file, its name still is not updated in explorer, though I can do `ls -alh` in `zsh` and confirm the name is changed. If I look in Git Lens, it *also* shows the correct file name with the changes.

Screen caps showing this behavior:

File has been renamed with zsh using `mv fileName newFilename`:
![Screen Shot 2020-01-15 at 11 32 33 AM](https://user-images.githubusercontent.com/12660440/72457053-6607f200-378b-11ea-9742-0d4027ada828.png)

Same file, now opened after renaming for editing, name is still wrong, even on the tab (notice what name shows when using `ls` in the console window):
![Screen Shot 2020-01-15 at 11 32 51 AM](https://user-images.githubusercontent.com/12660440/72457054-6607f200-378b-11ea-938f-95b7e56a72bb.png)

Same as the last screenshot, but now the file has been edited and saved and still doesn't update. `ls` has been run again, file name is still `Test.js` not `test.js`:
![Screen Shot 2020-01-15 at 11 33 41 AM](https://user-images.githubusercontent.com/12660440/72457056-6607f200-378b-11ea-855d-35dc3bb87afd.png)

Opening the same file in split view, still opens the tab with the wrong name:
![Screen Shot 2020-01-15 at 11 34 00 AM](https://user-images.githubusercontent.com/12660440/72457057-6607f200-378b-11ea-9f9c-12ede05f66a3.png)

Git Lens seems to know the correct file name:
![Screen Shot 2020-01-15 at 11 42 39 AM](https://user-images.githubusercontent.com/12660440/72457469-47562b00-378c-11ea-834a-08d34de2802c.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (6.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
error-gutters|Igo|1.0.1
vscode-peacock|joh|3.2.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
material-icon-theme|PKi|3.9.2
errorlens|use|2.9.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
If you rename the file from test.js -> test2.js does it work correctly?
Does the issue happen only if you change the casing of the file?

**Comment by methodbox** [comment]
> If you rename the file from test.js -> test2.js does it work correctly?
> Does the issue happen only if you change the casing of the file?

Good question. I’ve completely renamed the file and the same thing happens.

I noticed this issue originally because I often rename React component files as my project becomes more complex, so usually I might have a bunch of buttons and move them to a menu component, so one component might go from “NavButton” to “NavMenu” or something.

VS Code appears to not read the directory unless you reload, in which case it shows the correct file name.

**Comment by isidorn** [comment]
So it seems like you are missing file events.
Forwarding to @bpasero so he can instruct you to run vscode in verbose mode and investigate more into missing file events. Thanks

**Comment by methodbox** [comment]
Just a side note that this is happening on my work machine which is a 3-day-old MBP 16" and my home machine which is a 2016 MBP.

i.e. it's not the fact of an issue that started happening over time; probably not an extension causing this and I've tried w/extensions disabled.

**Comment by bpasero** [comment]
Can you run `code --verbose` and see if you are getting the correct file events from dev tools?

**Comment by methodbox** [comment]
I’ll do this and report back probably tomorrow. I missed your last comment in email for some reason.
