### ISSUE TITLE
Cannot drag Window when Full screen height - MacOS

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#88691]
Issue Type: <b>Bug</b>

If you resize a window to be the full height of the screen (between the menubar and the bottom of the screen, assuming the Dock is on the left or right), you cannot drag the window to reposition it. You need to ensure the window is not the full width of the screen.

Double clicking the drag area to maximize the window does NOT exhibit this behavior - only if you drag to resize the window to fit the height of the screen. The only way to restore dragging is to resize the window smaller. Even by a little bit.

VS Code version: Code - Insiders 1.42.0-insider (33c79d5ad447956814a2a3658029dffb9e28bae6, 2020-01-15T08:53:57.100Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|32.00GB (7.24GB free)|
|Process Argv|-psn_0_22299971|
|Screen Reader|no|
|VM|20%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.4
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.0.14
githistory|don|0.4.13
auto-close-tag|for|0.5.6
output-colorizer|IBM|0.1.2
Angular2|joh|8.3.0
mads|mir|0.0.5
vscode-azurefunctions|ms-|0.20.1
azure-account|ms-|0.8.8
csharp|ms-|1.21.9
js-debug-nightly|ms-|2020.1.20223
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.5
abracadabra|nic|3.1.0
vetur|oct|0.23.0
material-icon-theme|PKi|3.9.2
vue-vscode-snippets|sdr|1.8.0
open-in-browser|tec|2.0.0
msbuild-project-tools|tin|0.3.3
vscodeintellicode|Vis|1.2.3

(1 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
@vscodebot - Not even close to the same issue - not related to integrated terminal either.

**Comment by bpasero** [comment]
@jtsom is this an issue you only see in insiders or in stable as well?

**Comment by jtsom** [comment]
I'm only seeing it in insiders (at the moment I only have insiders installed). I also just noticed that I don't have to resize the window to the full screen height. I just resized the height of a window to make it a little shorter, and experienced the same behavior - I couldn't drag the window around.

**Comment by jtsom** [comment]
I also have the latest Exploration version installed and I noticed it happens there too:

Version: 1.42.0-exploration
Commit: 779ba5939a3866cbc3e31dc1290eb8fa700f7104
Date: 2020-01-06T11:49:14.939Z
Electron: 7.1.5
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

**Comment by bpasero** [comment]
I can reproduce with Electron Fiddle.

**Comment by bpasero** [comment]
This seems to be fixed for me with 7.1.11. Would be interesting to point it to the commit that fixed it.

**Comment by bpasero** [comment]
@jtsom can you please see if this is fixed for you with latest VSCode insiders? in. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jtsom** [comment]
Using:
Version: 1.43.0-insider
Commit: f4c95d5b9cfb2265f1730d564df1709533eff55e
Date: 2020-02-12T05:45:29.569Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

It seems to be fixed. I can move the window after sizing it just fine.

Thanks!
