### ISSUE TITLE
Typescript validation ignore "esModuleInterop" setting in tsconfig

### ISSUE THREAD

**Issue by lastingman** [microsoft/vscode#88698]
- VSCode Version: 1.41.1
- OS Version:  Darwin x64 19.2.0
Steps to Reproduce:

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "ES2018",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "esModuleInterop": true
  },
  "exclude": ["node_modules", "dist"]
}

```
![image](https://user-images.githubusercontent.com/10057502/72457331-50cdaa80-3801-11ea-9c65-f81a392d2e9c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

And what is import ode that causes error?

Are you sure you are using `import express from 'express';` as suggested in error?

**Comment by lastingman** [comment]
I did import express like `import express from 'express';`. It's back to normal right now, after I reboot my Mac. I tried reboot vscode yesterday, not working. It's weird.

**Comment by mjbvz** [comment]
Closing as it sounds like it is working again
