### ISSUE TITLE
Java project: Import all jar in folder

### ISSUE THREAD

**Issue by carlitador** [microsoft/vscode#88697]
I would like to import all jar files into my vscode project classpath.
If I do this it works, but only for one library of course:

In my case I have almost 100 .jar files to import. If I put them in lib and put try this:
 `<classpathentry kind="lib" path="lib"/>`

Or this:

` <classpathentry kind="lib" path="lib/*.jar"/>`

Or this

`<classpathentry kind="lib" path="lib/*"/>`

Do not work

Any idea?

**Comment by mjbvz** [comment]
Please file this against the Java extension
