### ISSUE TITLE
Add extension point for auto-detecting tasks. 

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [microsoft/vscode#887]
According to [documentation](https://code.visualstudio.com/docs/editor/tasks#_autodetecting-gulp-grunt-and-jake-tasks) VS Code can autodetect tasks from within Gulp, Grunt and Jake files.

It would be nice if there was extension point to add support also for other type of build files - while I have created FAKE (F# Make) plugin I think it would be better to have more general solution allowing us just to extend existing functionality instead of duplicating it.

**Comment by dbaeumer** [comment]
There is now a task provider API.
