### ISSUE TITLE
Value for python.formatting.provider not exposed

### ISSUE THREAD

**Issue by pcko1** [microsoft/vscode#88701]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Go to `File > Preferences > Settings > Extensions > Python > Formatting`
2. Value for `python.formatting.provider` is not exposed in the IDE. Had to manually change the `settings.json` to set `"python.formatting.provider": "black"`

**Comment by roblourens** [comment]
I see it, are you sure the extension is installed?

![image](https://user-images.githubusercontent.com/323878/72550907-9c577700-3848-11ea-9dba-d5f62a265e8d.png)
