### ISSUE TITLE
Coffeescript syntax grammar

### ISSUE THREAD

**Issue by MayBeOut** [Microsoft/vscode#8870]
- VSCode Version: 1.3
- OS Version: Windows 10

Hello, you're adding new syntax grammar for javascript from atom grammar, maybe you're converting atom coffeescript grammar? He is awesome, and many people used coffeescript in projects.

**Comment by joaomoreno** [comment]
We already have Coffeescript syntax. I don't understand the request.

![image](https://cloud.githubusercontent.com/assets/22350/16681279/f37235c6-44f3-11e6-8e22-d9c5517dd777.png)

**Comment by MayBeOut** [comment]
![coffeescript highlight](https://cloud.githubusercontent.com/assets/20347464/16693010/8c9910f0-4533-11e6-9c74-3962ae9d8884.png)
