### ISSUE TITLE
File Explorer popups do not use current display's scaling setting

### ISSUE THREAD

**Issue by corwinburdick** [microsoft/vscode#88708]
Issue Type: <b>Bug</b>

Preconditions:
Have multiple connected monitors/displays on Windows 10 with different scaling settings (set under Settings > Display > Scale and layout)

Expected results:
The File Explorer popups (for Open File, Save As, etc.) should use the scaling setting of the current monitor.
Notepad.exe's popups are an example of this functioning correctly, where dragging the popup across screens will resize the popup based on that monitor's scaling.

Actual results:
The File Explorer popups use the scaling setting of the default monitor, regardless of which monitor the popup is on.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by runxel** [comment]
Hey, just a little reminder: this is still a problem on 1.48.
