### ISSUE TITLE
Failed to Save Participants

### ISSUE THREAD

**Issue by shaunm-msft** [microsoft/vscode#88702]
Issue Type: <b>Bug</b>

Save a python file
"Save Participants Failed: Aborted onWillSaveTextDocument-event after 1750ms"

I'm using code-insiders on WSL. The only extensions installed are:
Local: Remote - WSL
WSL: Python

VS Code version: Code - Insiders 1.42.0-insider (33c79d5ad447956814a2a3658029dffb9e28bae6, 2020-01-15T09:36:35.018Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|Memory (System)|15.85GB (8.11GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.42.1
python|ms-|2020.1.58216-dev

</details>

**Comment by shaunm-msft** [comment]
Which extension?

**Comment by jrieken** [comment]
It will be in the extension host log, F1 > Log > Extension

**Comment by shaunm-msft** [comment]
I don't see that error in any of the logs on any days.
I also now don't have the error. I'm glad it's gone now, but it was sure a problem for my dev loop while it was there.

**Comment by Sandstedt** [comment]
I have the same problem, also running Remote - WSL (but also other plugins in my WSL installation like ESLint that affects Format on Save).

Solves by restarting VS Code.
