### ISSUE TITLE
Focusing inline action in quickpick breaks the alignment

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#88717]
Issue Type: <b>Bug</b>

If you open the recent workspace/files quickpick and then tab to the remove action on an item, the outline on the icon causes the whole quickpick item to shift.

![outline](https://user-images.githubusercontent.com/641685/72478153-4be80700-37bf-11ea-922c-1d3a1575476d.gif)

VS Code version: Code - Insiders 1.42.0-insider (33c79d5ad447956814a2a3658029dffb9e28bae6, 2020-01-15T09:36:35.018Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|

|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Which theme is this?

**Comment by eamodio** [comment]
[Amethyst](https://marketplace.visualstudio.com/items?itemName=eamodio.amethyst-theme)

**Comment by chrmarti** [comment]
This appears to be fixed in Insiders. Can you confirm @eamodio?

**Comment by eamodio** [comment]
Yup looks fixed. Although the focus rect seem off: 
![image](https://user-images.githubusercontent.com/641685/76882184-aa2d7680-6850-11ea-9b26-67b1cfef1c78.png)

Though probably not worth the effort 😄

**Comment by chrmarti** [comment]
Closing, thanks.

Looks like we pixel-pushed the focus rectangle out of shape...
