### ISSUE TITLE
setting process.env from extensions doesn't propagate

### ISSUE THREAD

**Issue by jacobisaliveandwell** [microsoft/vscode#88718]
Issue Type: <b>Bug</b>

From an extension, setting `process.env[key] = value;` does not have any effect on the parent process. My guess is that this has to do with the Extension Host subprocess. Is there an api for communicating with the parent process?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

**Comment by jrieken** [comment]
>  setting process.env[key] = value; does not have any effect on the parent process.

Do I get that right? You set `process.env.foo` in the extension host process and expect it be observed in the renderer or terminal that launched the extension host process?

**Comment by jacobisaliveandwell** [comment]
@jrieken correct. When I open the developer tools and inspect `process.env` the environment is unchanged. My original reason for looking into this was to attempt better support for tools like rbenv, goenv, tfenv, etc.

**Comment by jrieken** [comment]
Thanks for clarifying, however a child process cannot pass/change env variables to a parent process. afaik this limitation is universal and not just vscode

**Comment by jacobisaliveandwell** [comment]
@jrieken Understood, I'm fully aware of how processes are handled, and everything that is happening makes sense. That is why the initial post finishes with the question of if the parent process exposes an API or something. And I explained the environment example in the hopes that if there wasn't an API, maybe it'd inspire thought of another solution/approach I'm not considering (maybe electron exposes some rpc? i don't really mess with electron much). My apologies if my straight to the point approach came off as naive.

**Comment by jrieken** [comment]
There is API to talk back to parent because the renderer kinda protects itself. Changing env is generally tricky because how would downlevel consumer know that they have changed, e.g a child process of another child process?

> My original reason for looking into this was to attempt better support for tools like rbenv, goenv, tfenv, etc.

To get back to original need. You might be better off with the [task](https://github.com/microsoft/vscode/blob/caf838e1cd1a01aad17137ed8d50379f7febabb3/src/vs/vscode.d.ts#L5594)-API - it allows you to define task run as process or via the shell and that allows to define args and env. Adding @alexr00 for more background if needed

**Comment by alexr00** [comment]
Tasks can be used to run build scripts (and other scripts and processes) and you can set up an environment for those tasks. The [documentation](https://code.visualstudio.com/Docs/editor/tasks), the [api](https://github.com/microsoft/vscode/blob/caf838e1cd1a01aad17137ed8d50379f7febabb3/src/vs/vscode.d.ts#L5594), and the [example extension](https://code.visualstudio.com/api/extension-guides/task-provider) are all good places to start.

**Comment by jacobisaliveandwell** [comment]
@jrieken @alexr00 Thanks for the info and links. I definitely trolled the documentation and tried a few approaches before creating this ticket, but unfortunately none of this scratches what I'm trying to solve. If you're familiar with the various env tools (direnv, rbenv, nodenv, goenv, tfenv, etc), they modify your environment and PATH relative to files in the directory. This in turn should have an effect on plugins like Terraform, Ruby, etc, so they find the intended binary/tool. This would require updating the running parent process, or restarting it after sourcing said environment changes.

So far my work around has been to navigate to the project directory, which automatically modifies the environment, and then launching with `code .` to inherit it. This means that if I need to change versions or do anything that would effect this environment, I have to quit and restart the editor, and makes the `File -> Open Recent` navigation useless.

I was hoping to write a plugin that monitors such files for changes and then updates the parent environment accordingly.

**Comment by jacobisaliveandwell** [comment]
> There is API to talk back to parent because the renderer kinda protects itself.

@jrieken Could you link me to documentation of this API that you're thinking of so I could look around?

**Comment by jacobisaliveandwell** [comment]
@jrieken [Here](https://github.com/microsoft/vscode/issues/57481#issuecomment-515830882) is another example of users impacted by this workflow. He is suggesting the ability to set load order? But my understanding is that doesn't matter because each extension runs in it's own process, or am I wrong?

**Comment by jacobisaliveandwell** [comment]
@bpasero is there a way this could be revisited? I feel like it was closed really quickly, and I can search github issues finding examples of others having these problems.
