### ISSUE TITLE
Show Detailed Application and Extensions CPU/Memory Usage

### ISSUE THREAD

**Issue by reyou** [microsoft/vscode#88712]
VS Code used for multipurpose development such as TypeScript, Angular, Vue, React, C#, Golang and many more.

Potentially every platform requires 1-5 extensions to be used in VS code efficently. Some extensions are poorly written, and consumes huge amount of memory, and causing the VS Code to be frozen and very slow.

My Feature Request to add an itemized list of Memory/CPU Consumption history of each component. Including main app thread, built-in extensions and language features, and especially for third party plugins.

Currently it is very hard to tell which extension is causing slowness, and I keep turning on/off to identify the issue. This will help also developers to report the issues to Extensions Owners, so they can fix them.

**Comment by RMacfarlane** [comment]
There is a process explorer for VS Code which can be opened with `F1` -> `Developer: Open Process Explorer`. This shows some of what you want - CPU and memory are given for every process within VSCode, so you're able to see the main process, the window, the extension host, and language servers launched from the extension host. Unfortunately, it's not possible to distinguish between extensions running within the extension host from this.

There's also another page from `F1` -> `Developer: Show Running Extensions` that I think is more suited to finding out which extension is causing a problem. This allows for profiling specific extensions, but doesn't display memory/CPU stats.

**Comment by reyou** [comment]
@RMacfarlane Process explorer helps a lot. Thanks! I also like the list of running extensions.
It would be great to have CPU/Memory usage of the extensions as a feature request. Because I keep seeing people are complaining about VS Code slowness, in fact that could be cause of a poorly written extension.

**Comment by DanAlexson90** [comment]
Why was this request closed without implementation?

**Comment by RMacfarlane** [comment]
https://github.com/microsoft/vscode/wiki/Issues-Triaging#managing-feature-requests
> Feature requests like all issues are a means of communication between us and our community as well as among the members of the community. Thus, in principle, we could keep all feature requests open no matter what will happen to the feature they describe. Unfortunately, this makes it hard for you to understand what has realistic chances to ever make it into the repository. We therefore close feature requests we cannot address with out-of-scope while we assign feature requests we don't plan to address but want to give you time to weigh in to the Backlog Candidates milestone.

> If you are the author of a feature request you might not like that we close or don't plan to address your request. It might even feel like a slap in your face. We understand that. All of us have been there - in this project or others we have contributed to. So, be assured, we love all of your input. Don't take personal offense when we close or assign the Backlog Candidates milestone to your issue :peace_symbol:. If you feel your feature request deserves to stay open, improve your use case and ping us or gather more up-votes.
