### ISSUE TITLE
Hard to place caret before first character of line by mouse

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8871]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:
1. Using default dark+ theme (but others are affected likewise)
2. Open any file and place caret before first character of any line with spaces as indentation
3. -> It is hard to hit the right spot right of the folding ruler and left of the first character

We seem to be missing a visual indicator where the line begins. A simple workaround is to add a editor.ruler at column 0 in the settings.

**Comment by alexandrudima** [comment]
@chrmarti That was one of the main reasons we added `editor.renderIndentGuides`. We can decide if we want to turn `editor.renderIndentGuides` on by default.

**Comment by alexandrudima** [comment]
@bgashler1 fyi

**Comment by chrmarti** [comment]
The indent guides work great (and solve the more general problem of placing the caret at the start of an indent). I didn't know we had this feature and 👍 on enabling it by default.

**Comment by bgashler1** [comment]
I'm noticing that if there are no folding buttons in the folding column that a click does not place a caret in the editor, which I agree can be annoying when there are no indent guides enabled.

I'm wondering if making it so clicking anywhere in the folding column will pass clicks to the editor on the left-most edge of it (thus placing a caret more easily).  We could make only the folding buttons steal the click to fold.  Just an idea.  @alexandrudima thoughts?  We can also discuss in UX sync this next Wednesday.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
