### ISSUE TITLE
Default to current branch name when renaming git branch

### ISSUE THREAD

**Issue by scottastrophic** [microsoft/vscode#88710]
My most frequent use case for renaming a branch is to correct a typo. It would be super helpful to prepopulate the Branch name field with the current branch name.
![image](https://user-images.githubusercontent.com/1441466/72468730-d4f54300-37ab-11ea-9e90-a97570423301.png)

**Comment by joaomoreno** [comment]
This was fixed via PR yesterday.

**Comment by scottastrophic** [comment]
Amazing! Thanks.
