### ISSUE TITLE
handle node-gyp include paths

### ISSUE THREAD

**Issue by bmacnaughton** [microsoft/vscode#88726]
When writing node-gyp-based C/C++ extensions to nodejs the currently active node include directory is automatically added to the include path. the binding.gyp file can specify additional paths. These are not configured in system environment variables (and when using nvm the location of the node include directory is dynamic which is the real issue). When using node-addon-api, the `"<!@(node -p \"require('node-addon-api').include\")"` is used in binding.gyp to add node-addon-api's include directory to the include path.

It would be useful to have an option to automatically include the node include directory and those defined in binding.gyp so that vscode can find those files. Currently it squiggles them and isn't able to find declarations and definitions.

I fiddled with an extension that implements a command to return the node include directory like:

```
let disposable = vscode.commands.registerCommand('extension.nodeIncludeNvm', function () {
  // just return a best guess as to the include directory for this version
  // of node. presume NVM_BIN var points to bin if it exists. if not, presume
  // /usr/local/include/node. no, it's not sophisticated.
  let path;
  if (process.env.NVM_BIN) {
    path = process.env.NVM_BIN.replace(/\/bin$/, '/include');
  } else {
    path = '/usr/local/include/node';
  }
  return Promise.resolve(path);
});
```

It works within the "echo nodeIncludeNvm path" task:
```
    "tasks": [
        {
            "label": "echo nodeIncludeNvm path",
            "type": "shell",
            "command": "echo ${command:extension.nodeIncludeNvm}",
            "problemMatcher": []
        },
        {
          "label": "echo C_Cpp.default.includePath",
          "type": "shell",
          "command": "echo ${config:C_Cpp.default.includePath}",
          "problemMatcher": []
        }
    ]
```

but I am unable to get it to "stick" in `C_Cpp.default.includePath`. My project settings.json:
```
  "C_Cpp.default.includePath": [
    "${workspaceFolder}",
    "${command:extension.nodeIncludeNvm}",
    "${workspaceFolder}/node_modules/node-addon-api"
  ],
```

and executing "echo C_Cpp.default.includePath" task output is:
```
> Executing task: echo ${workspaceFolder},${command:extension.nodeIncludeNvm},${workspaceFolder}/node_modules/node-addon-api <

/home/bruce/github.com/bmacnaughton/nvm-node-include,,/home/bruce/github.com/bmacnaughton/nvm-node-include/node_modules/node-addon-api
```

If I'm just doing something wrong trying to get `${command:extension.nodeIncludeNvm}` to work let me know.

Overall it seems like it would be a nice addition to have an option of something like `C_Cpp.addNodeGypIncludePaths` or something similar. The `nvm` setting seems most important, because hardcoding a possibly non-existent node-addon-api location is not a big deal. So maybe it's more limited and something like `C_Cpp.addNvmNodeIncludePath`.

Thanks for your consideration.

**Comment by bmacnaughton** [comment]
@bpasero which issue is caused by which extension?

you are saying vscode does support node-gyp paths?

**Comment by bmacnaughton** [comment]
this is really a feature request. the "extension" mentioned is one i created to get around the problem. please consider re-opening as a feature request. i'm sorry i didn't make that clear.

**Comment by bpasero** [comment]
@bmacnaughton that's right, out of the box VSCode does not support C++ authorting/development. I was assuming you are a user of https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools and meant to report the issue to them.

**Comment by bmacnaughton** [comment]
@bpasero - ok, thank you. that's a microsoft extension and it does make sense that i submit this request there. (i presumed that because it was microsoft that you were involved - my bad.)
