### ISSUE TITLE
F11 (step into) when debugging sometimes triggers the Full Screen command

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#88721]
Issue Type: <b>Bug</b>

It looks like #78251 is back. Sometimes when I step quickly, instead of stepping vscode goes full screen.

This might be related to the new js debugger. 

/cc @connor4312 

VS Code version: Code - Insiders 1.42.0-insider (33c79d5ad447956814a2a3658029dffb9e28bae6, 2020-01-15T09:36:35.018Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
js-debug doesn't contribute any keybindings or listen to those events, probably not related to us.

**Comment by eamodio** [comment]
The keybinding is based on the debugger state -- so maybe the state transitions are different (or the timing of them).

**Comment by isidorn** [comment]
I pushed a potential fix for this.
Downside: users will not be able to F11 to full screen while debugging. In honesty I do not think anyone will hit this, though let's keep our eyes open for users complains.
Thanks
