### ISSUE TITLE
Edit window scroll bar not detecting mouse release

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#88725]
Issue Type: <b>Bug</b>

I'm not sure if this is a core vscode issue but it's occuring for every workflow which involves an editor window and some form of seperate output window next to it - i.e. using python interactive with a py file open in the editor and the python interactive window beside it.

If I scroll the code window, and move the mouse left (still on the code window) the viewport continues to scroll (I assume by design and I don't have an issue with this) until I release the mouse. But if I move the cursor onto the python interactive window and then release the mouse, the editor viewport continues to scroll as I move the mouse and I have to click back on the scroll bar to release it.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.15.0-74-generic

**Comment by alexdima** [comment]
Reduced steps:
* open a markdown file
* click to see its preview on the side
* mouse down in editor
* drag mouse to preview
* mouse up in preview
* move mouse back over the editor, it still believes the mouse is down
