### ISSUE TITLE
Syntax highlight bug in .tsx files around < >

### ISSUE THREAD

**Issue by navjotts** [Microsoft/vscode#8872]
- VSCode Version: Version 1.3.0 (1.3.0)
- OS Version: OS X Version 10.11.5

**Steps to Reproduce:**

create a new file test.tsx with a class having an Array:  for example: 

`export default class Foo {
    poof:Array<string>
    renderHtml() {        
    }
}`

Find the syntax highlighting busted once < > is encountered:
<img width="380" alt="tsx_test png" src="https://cloud.githubusercontent.com/assets/8072161/16674664/4ea2047e-446f-11e6-98f4-bfb1c9011bf2.png">

**Comment by navjotts** [comment]
Note : this just happened as I updated to the latest update which came like 2 hours back.

**Comment by boxstart** [comment]
Duplicat with issue #8045

**Comment by joaomoreno** [comment]
Thanks @boxstart
