### ISSUE TITLE
Automatic updates fail on Terminal Server even though user installation

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/vscode#88737]
- VSCode Version: Not bound to a specific version, but across the board.
- OS Version: Windows Server 2016, but also occurs with 2019.

Steps to Reproduce:

The following case is given:

We use Visual Studio code on our Terminal Server (Windows Server 2016). Here it is installed, but not under "Programs". Each user has his own installation in his user directory.

Now we have problems with automatic updates when several people work with their installations in parallel. The problem here is that when Visual Studio code is closed no automatic installation can take place. There is always the hint that Visual Studio code is already opened. But this is a misconception, because everyone has his own installation. So this leads to the fact that we cannot use the automatic installation.

What does work is that if we manually download the new installer and use it to perform the installation. Here the case described above does not occur.

It looks like something is going wrong with the automatic update process here.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/76641
