### ISSUE TITLE
VSCode freezes every time when I perform a search.

### ISSUE THREAD

**Issue by yifanchen** [microsoft/vscode#88732]
Problem persists on VSCode Insider.

- VSCode Version: 1.41.1
- OS Version: Catalina 10.15.2 
- Machine: 2018 15 " MBP 16GB I7

Steps to Reproduce:

Both my machine and my co-worker's machine are same, when we perform the exactly same task as follow, everything works fine on his machine, but not my machine. 

1. Open a 1.7 GB project
2. Search something in general, let's say "toggle". The search result shows there are more than 10,000 results on my co-worker's machine, however it freezes on my machine every single time. I have tried the following to fix the problems, unfortunately no luck.

* Uninstall completely and reinstall without any extensions
* Close everything else while performing the searching task

Does this issue occur when all extensions are disabled?: Yes

**Comment by bklee2** [comment]
Hi

**Comment by deitry** [comment]
Also here: https://github.com/microsoft/vscode/issues/88385

**Comment by roblourens** [comment]
We can talk about it in https://github.com/microsoft/vscode/issues/88385
