### ISSUE TITLE
Allow disabling of plugin update notifications

### ISSUE THREAD

**Issue by corysimmons** [microsoft/vscode#88733]
This has been plaguing me lately. I keep getting update notifications from Material Theme.

I want to get the automatic updates, I just don't want to have to see the popup every other day, so simply disabling auto updates won't work.

This was mentioned here in this StackOverflow (there are lots of duplicates of this question btw):

- https://stackoverflow.com/questions/42496935/disabling-visual-studio-code-update-notification

Similar requests:
- https://github.com/microsoft/vscode/issues/61730
- https://stackoverflow.com/questions/43998534/can-i-disable-the-update-notification-of-vscode

An option like `"update.mode": "silent"` where auto updates were enabled, but the growl notifications on updates never showed up, would be perfect.

Thank you.

**Comment by bpasero** [comment]
@corysimmons first of all, please report this to material theme. Ideally they would not show these kind of notifications. Once you do, let me know the link and I will upvote it too.

As for this feature, there are duplicates: https://github.com/microsoft/vscode/labels/workbench-notifications

**Comment by corysimmons** [comment]
@bpasero Already did but they keep updating every day or two 😓 
 https://github.com/material-theme/vsc-material-theme/issues/433
