### ISSUE TITLE
Suggest details pane often shows up below the suggest widget when loading

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88731]
- Trigger suggest
- The details pane is already set to be shown
- Often, it first shows up below the suggest widget like in the position it wraps to when there is not enough room, then is re-layed-out to be on the right side

This has been around for maybe a couple months, it just sort of produces an annoying blink.

I've been trying to capture a gif for awhile but haven't succeeded.

**Comment by roblourens** [comment]
I dunno if I am using the right words, but I mean the thing on the right first shows up on the bottom for a couple seconds, then moves to the right.

![image](https://user-images.githubusercontent.com/323878/72483863-4981af00-37b7-11ea-939f-0a35858cbcab.png)

**Comment by octref** [comment]
@roblourens Do you mind doing this?

- Set `"typescript.tsserver.trace": "verbose"`
- Clear Output -> TypeScript
- Repro this
- Send me all logs

My guess is TS is not providing `details` upfront and later resolving the `details`.

**Comment by roblourens** [comment]
It's not that the details don't appear, it's that they appear in the wrong place on the screen.

**Comment by roblourens** [comment]
[ti-78783.log](https://github.com/microsoft/vscode/files/4073024/ti-78783.log)
[tsserver.log](https://github.com/microsoft/vscode/files/4073025/tsserver.log)

**Comment by jrieken** [comment]
I think this is due to size constraints and some dynamic layout. Surely @ramya-rao-a knows ;-) @roblourens is this with an editor as the "edge" of the window or monitor?

**Comment by roblourens** [comment]
There is plenty of room. It's a maximized window and this is happening closer to the left side

**Comment by roblourens** [comment]
This started happening in like November or October but it took me awhile to get around to filing the issue...

**Comment by octref** [comment]
- `expandSideOrBelow` re-layout docs box depending on Item
- #27868 makes it so when there's no details/doc, go to single-column layout
- https://github.com/microsoft/vscode/commit/15b7c86d86319b187a5ef255c170184a8519c5af does not change details, but set content of details UI to be `Loading...`. So during loading, docs box become single column. When item is resolved and details/docs provided, they flash to the right.

**Comment by eamodio** [comment]
Not exactly sure how I got this to happen, but:
![image](https://user-images.githubusercontent.com/641685/73568308-26513380-4436-11ea-94fd-ac9af73ed539.png)

**Comment by octref** [comment]
@eamodio Do you have enough space to the right? After "Loading...", does the docs box go to the right?

**Comment by eamodio** [comment]
It never stopped saying loading -- and there was lots of room on the right.

**Comment by octref** [comment]
Chatted with @eamodio, seems to be something else.

A consistent repro for me was to quickly type a few characters after dot, for an object with complex shape. This used to trigger the "Loading..." in the bottom then move to the right, but after my fix this no longer happens.

![Kapture 2020-01-31 at 11 47 36](https://user-images.githubusercontent.com/4033249/73569638-b0da6880-441f-11ea-82ed-5229430f5ac7.gif)
