### ISSUE TITLE
Prevent menu bar from showing up on Windows after Alt+mouse.

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#8874]
- VSCode Version: 1.3
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Toggle menu bar to hidden.
2. Hold the <kbd>Alt</kbd> key and click the editor to perform a multi-select.
3. Release the <kbd>Alt</kbd> key.
4. The menu bar show up.

The key problem is that when multi-selecting, users DO NOT WANT TO BRING OUT the menu bar. If they want, they will press <kbd>Alt</kbd> solely, without mouse interaction.

Related: #5851

**Comment by alexandrudima** [comment]
@bpasero thoughts? I'm pretty sure I call `e.preventDefault()` and Electron still pops up the menu

**Comment by alexandrudima** [comment]
Related: #3130

**Comment by bpasero** [comment]
As far as I know we cannot prevent the menu from showing when Alt is pressed because this is for accessibility. However afaik other native applications give a delay before showing the menu, not sure we can do the same.

**Comment by be5invis** [comment]
Just prevent it from showing up if the mouse is clicked in the period that the alt key is holding. In the situation that the user pressed and released alt only, show the menu as usual.

发自我的 iPhone

**Comment by bpasero** [comment]
I am not aware of any API to "prevent the menu from showing up". This discussion should probably move to Electron.

**Comment by be5invis** [comment]
@bpasero 
I am not sure whether the "e.preventDefault" on keyboard release event works. If it doesnt, use the mechanism like “delete menu when it is hidden” instead of hiding it?

**Comment by bpasero** [comment]
If we do that, how are you getting the menu back then?

**Comment by be5invis** [comment]
@bpasero You misunderstood my proposal.

We will monitor whether the mouse is clicked when the <kbd>alt</kbd> key is down. If the mouse is clicked during this period, it means that the user used <kbd>alt</kbd> to perform multi-selection, and then after <kbd>alt</kbd> is released, prevent the menu bar from showing up once. If not, show the menu.

**Comment by be5invis** [comment]
@bpasero 
Event sequence example

- **Multi-selecting**: <kbd>alt</kbd> key down — mouse down — mouse up — <kbd>alt</kbd> key up
- **Single <kbd>alt</kbd> press**: <kbd>alt</kbd> key down — <kbd>alt</kbd> key up

**Comment by bpasero** [comment]
Right that could work but would require us to explicitly null-ify the menu when we hide it instead of using the API of https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetautohidemenubarhide and always bring it back when we detect the Alt key press.

This is such a major hack and mess that I would rather ask Electron for better API or handling on Windows.

**Comment by be5invis** [comment]
Does onkeyup's preventDefault work?

发自我的 iPhone

**Comment by be5invis** [comment]
@bpasero I’ve tried to use this script
```html
<script>
  document.body.onkeyup = function(e){
    e.preventDefault()
  }
</script>
```
within Electron’s demo and it do prevents showing up menu after <kbd>alt</kbd> is releases.
So, no hacking is needed now.

**Comment by bpasero** [comment]
@be5invis maybe do a PR? I am not sure where to add this global handler though and also needs to detect the fact that you still want it if Alt is pressed alone.

**Comment by be5invis** [comment]
@bpasero The mechanism is simple
```javascript

var listening = false;
var mouseTriggered = true;
function onkeydown(e){
    ...
    if(e.key === AltKey){ listening = true; mouseTriggered = false }
}
function onkeyup(e){
    ...
    if(e.key === AltKey){
        listening = false;
        if(mouseTriggered) e.preventDefault();
        mouseTriggered = false;
    }
}
function onmousedown(){
    ...
    if(listening){ mouseTriggered = true }
}
```
I think the key is in viewImpl.ts...

**Comment by be5invis** [comment]
@bpasero OK, PR made #9154.

**Comment by be5invis** [comment]
@alexandrudima @bpasero What's the progress?

**Comment by be5invis** [comment]
@alexandrudima @bpasero What's the progress?

**Comment by bpasero** [comment]
@be5invis we will update this issue when we looked at the PR, please understand what we have a lot of issues to look through and need to prioritize 👍

**Comment by bpasero** [comment]
Works ok now, thanks @alexandrudima
