### ISSUE TITLE
Searching in quick pick is not reliable

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#88742]
Filtering items in a quick pick is not working correctly.

Examples:
I have a list of about 2000 items that I show in a quick pick. I noticed that sometimes on missing letter in a letter causes the results to be wrong.

Example:
This is what I want to search for.
![image](https://user-images.githubusercontent.com/9846892/72505181-b476c880-383f-11ea-9580-710ea97b427a.png)

If I remove ` 'p' then I get no results:
![image](https://user-images.githubusercontent.com/9846892/72505305-f3a51980-383f-11ea-87eb-597d8917a425.png)

If I remove the first 'a' I do get a result:
![image](https://user-images.githubusercontent.com/9846892/72505334-0586bc80-3840-11ea-9d05-b3395ddbbddd.png)

I think removing letters from the beginning and end will work, but any letter in the middle will not work for some reason.

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by psclkhoury** [comment]
Actually you can easily test it with the command palette.

![image](https://user-images.githubusercontent.com/9846892/72532324-7b584b80-3873-11ea-999e-0c8482b5aadf.png)


![image](https://user-images.githubusercontent.com/9846892/72532290-6e3b5c80-3873-11ea-8b41-d7815f17d68b.png)

**Comment by roblourens** [comment]
This is by design. We will match a complete substring inside a word (missing first letter) but won't match inside a word with a missing character (the other case) because we think that would just give us too many irrelevant fuzzy results. It has always worked that way.
