### ISSUE TITLE
VSCodeInsider_DefaultSetting_AI4D:Name property does not exist for the edit filed.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88746]
**Environment Details:​**

VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Steps to Reproduce:**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control and click on it .
5.Select any existing environment and then again click on the "+" button and navigate till "Default setting" ,click on it.
6. Open AI4D.
7. Check the name property for the  edit field.

**Actual:**
Name property does not exist for the edit filed.

**Expected:​**
Name property should be  provide for the edit filed ans screen reader should announces the same.

**Same issue Observed for the below scenario:**
**1.Customer Setting**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control and click on it .
5.Select any existing environment and then again click on the "+" button and navigate till "Custom setting" ,click on it.
Image

**​User Impact:​**
Screen reader user does not understand control if it does not announces information/name  about the control.

![image](https://user-images.githubusercontent.com/55909580/72518560-a2b31680-387b-11ea-90be-9701323dea8d.png)

**Comment by isidorn** [comment]
Please file this against the VSO Extension. They can create nice reproducable steps if this is the vscode input box and how they use it. Thanks

**Comment by vinodbk197** [comment]
@isidorn 
As per the above comment i have file the bug in the VSO Extension area path (Bug id:[88839](https://github.com/microsoft/vscode/issues/88839).But again this bug pushed back to  VSCode area path. Could you please provide us correct area path to log the external  issue.

**Comment by isidorn** [comment]
I do not know where visual studio online is tracking their issues. Please check with the Visual Studio Online team. Thank you
