### ISSUE TITLE
Inserting video vscode crash using html code in markdown.

### ISSUE THREAD

**Issue by Evilrabbit520** [microsoft/vscode#88744]
Dear development team, open source team, hello! 
&emsp;&emsp;I have always had a habit of writing a journal using markdown in vscode. Today, I inserted a video using html and found that vscode actually crashed. I thought the system was still a problem after restarting the computer, so I tried to insert a smaller file The video is also the html code. I found that the parsing can be completed. After inserting a video with a larger file again, the problem occurs again. I hope that it can be resolved in the next release. Thank you.

**Comment by mjbvz** [comment]
Can you please share the snippet of html that causes this

Also, please fill out the issue template. /needsMoreInfo

**Comment by Evilrabbit520** [comment]
```html
<div style="text-align:center;">
<video src="./video/20200116/1.mp4" controls="controls" width="400" height="200"></video>
</div>
```

**Comment by mjbvz** [comment]
This doesn't repo for me. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
