### ISSUE TITLE
Debug Console can not input

### ISSUE THREAD

**Issue by skyterra** [microsoft/vscode#88748]
Issue Type: <b>Feature Request</b>

Sometimes, i need to input params to debug my golang program, but the Debug Console can not inpput anything.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
If possible with the Go extension, try to configure your program to run in the integrated terminal. If the Go extension doesn't support this, file an issue against the Go extension.
