### ISSUE TITLE
golang debug attach

### ISSUE THREAD

**Issue by skyterra** [microsoft/vscode#88747]
Issue Type: <b>Bug</b>

when debuging attach to a golang process, the golang process may be killed.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (19.26GB free)|
|Process Argv|--folder-uri file:///d%3A/game_projects/b2/002|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.58038
Go|ms-|0.12.0

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

Please Go extension provides debug for Go language. Please report this issue with more details in https://github.com/microsoft/vscode-go/issues repo
