### ISSUE TITLE
VSCodeInsider_DefaultSetting_Keyboard:Keyboard focus is not in logical order.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88759]
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Steps to Reproduce:**
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3. Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4. Navigate till "+" button beside the  "VS ONLINE" control and click on it .
5. Select any existing environment and then again click on the "+" button and navigate till "Default setting" ,click on it.
6. after Default setting screen is opened by pressing the next tab keyboard focus is not in logical order.

**Actual:**
As soon as  Default setting pop up screen is opened by pressing the next tab keyboard focus is not in logical order.Here the keyboard focus is present outside the pop up.

**Expected:​**
As soon as Default setting pop up screen is opened by pressing the next tab keyboard focus must be present on the first actionable control in the pop up.

**Same issue observed for the below scenario:**
**1.Customer Setting**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control and click on it .
5.Select any existing environment and then again click on the "+" button and navigate till "Custom setting" ,click on it.
6.Verify that all the elements of "Customer setting" for new environment" pop up are accessible and MAS Compliant

**​User Impact:​**
User does not understand the proper navigation order.

**Comment by isidorn** [comment]
This makes sense, however I will create a super set of these issues so there are no duplicates
Closing in favor of https://github.com/microsoft/vscode/issues/88792
