### ISSUE TITLE
vscode consume toda la memoria y el area de intercambio y congela el sistema

### ISSUE THREAD

**Issue by osocure** [microsoft/vscode#88755]
vscode trabaja desde unos minutos a una hora y luego se queda congelado y congela el sistema operativo. Consume toda la memoria ram y el area de intercambio comienza a llenarse hasta que el ordenador no responde más. 
El s.o. es Linux mint 19 y la version de vscode es del repositorio.

**Comment by JandroMejia97** [comment]
VSCode works well for a few minutes, then all VSCode processes start to saturate the RAM, the system freezes and VSCode terminates cerranod. My OS is Windows 10 Home Edition 64-bit, my RAM is 4GB.
![image](https://user-images.githubusercontent.com/32623757/72761158-d82c6c80-3bb9-11ea-9547-a67f605a15e1.png)
