### ISSUE TITLE
Adopt CompletionItemLabel

### ISSUE THREAD

**Issue by dominic-simplan** [microsoft/vscode#88757]
IntelliSense shows a list of available methods and fields. It is possible to show the quick info for such an item by clicking on the info icon of the **currently selected** item.

I would like to be able to see the quick info for items which are currently not selected using the mouse only, and **without using the keyboard first to navigate** to the according item.

Currently, I cannot see the quick info for items other than the selected one by using the mouse only:
![intellisense](https://user-images.githubusercontent.com/22240239/72522393-e26b0580-385d-11ea-90c9-354dcdcd9cae.gif)

There is no info icon displayed for the other items and any mouse button click on the other item will insert the item into the code and close intellisense.

**Comment by gjsjohnmurray** [comment]
Work being done at the moment on #39441 by @jrieken may be relevant to this request.

**Comment by jrieken** [comment]
Yes - we are working on this. Issue #39441 is the ground work for this. Once that's done each language extension needs to follow up with our changes. Keeping for as tracking item for TypeScirpt

**Comment by mjbvz** [comment]
Upstream TS exploration/feedback issue https://github.com/microsoft/TypeScript/issues/36265

**Comment by mjbvz** [comment]
Closing as upstream. We're also already using some parts of this API
