### ISSUE TITLE
VSCodeInsider_DefaultSettingforNewEnvironment_AI4D: (Code - Insiders/combo box 'Type to narrow down results.') An element of the given ControlType must support the ExpandCollapse pattern.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88753]
**Application**: Code - Insiders has the following accessibility issue that needs investigation.

**Issue Details**
1.?Make sure the element has the appropriate ControlType property for its function. 2.?If the current ControlType is correct, modify the element to s...open attached A11y test file for full details.

**Element path**: combo box 'Type to narrow down results.'

To Reproduce and How to Fix guidance: Please open the attached Accessibility Insights for Windows Test File (*.a11ytest) to reproduce the error in Accessibility Insights for Windows.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. 

![image](https://user-images.githubusercontent.com/55909580/72524161-52da4c80-3887-11ea-8c22-038069886ddd.png)

**Same issue observed for the below scenario:**
**1.Select Plan**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "Select Plan" button beside the  "VS ONLINE" control and click on it.

**2.Create New Environment**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control  and click on it.

**Comment by isidorn** [comment]
Please file this against the VSO Extension. They can create nice reproducable steps if this is the vscode input box and how they use it. Thanks

**Comment by vinodbk197** [comment]
@isidorn 
As per the above comment i have file the bug in the VSO Extension area path (Bug id:[88840](https://github.com/microsoft/vscode/issues/88840)).But again this bug pushed back to VSCode area path. Could you please provide us correct area path to log the external issue.

**Comment by isidorn** [comment]
I do not know where visual studio online is tracking their issues. Please check with the Visual Studio Online team. Thank you
