### ISSUE TITLE
Find in folder search and replace dead slow

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#88764]
Issue Type: <b>Bug</b>

I searched in a coverage report, mainly html files, to fix a path.
4k appearances in 2k files.
After hitting replace all VSCode is pretty much unresonsive throwing out a 'Running Save Participants ...' message for each file.
I cannot do anything by waiting because also vscode is eating up all resources.

VS Code version: Code - Insiders 1.42.0-insider (33c79d5ad447956814a2a3658029dffb9e28bae6, 2020-01-15T08:53:57.100Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|50, 42, 35|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cucumberautocomplete|ale|2.14.1
cypress-snippets|and|1.2.0
atlascode|atl|2.3.1
vscode-custom-css|be5|3.0.9
color-info|bie|0.5.1
markdown-mermaid|bie|1.4.1
vscode-tldr|bmu|1.0.0
mermaid-markdown-syntax-highlighting|bpr|1.0.2
phpstan|bre|1.1.3
better-toml|bun|0.3.2
twigcs|cer|1.1.0
vscode-opennewinstance|chr|0.0.6
scss-grammar-extended|dan|1.0.0
vscode-eslint|dba|2.0.14
make-hidden|dev|3.0.3
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.18.0
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
file-icons|fil|1.0.21
vscode-firefox-debug|fir|2.6.1
nightswitch|gha|1.1.0
vscode-architect|gil|0.1.0
comby-vscode|gil|0.0.1
vscode-pull-request-github|Git|0.14.0
todo-tree|Gru|0.0.162
rest-client|hum|0.23.0
output-colorizer|IBM|0.1.2
composer|ika|0.7.1
smarty|imp|0.3.0
path-autocomplete|ion|1.13.3
svelte-vscode|Jam|0.9.3
plantuml|jeb|2.13.6
polacode-2019|jef|0.5.1
browsersync|jer|2.1.1
vscode-peacock|joh|3.2.0
php-cs-fixer|jun|0.1.129
vscode-commitizen|Kni|0.8.4
php-symbols|lin|2.1.0
phpmd|lin|1.2.1
web-accessibility|Max|0.2.8
twig-language-2|mbl|0.9.0
plantumlpreviewer|Meb|0.6.0
git-graph|mhu|1.21.0
vscode-scss|mrm|0.8.1
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.97.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
vscode-remote-extensionpack|ms-|0.19.0
js-debug-nightly|ms-|2020.1.21663
references-view|ms-|0.0.44
debugger-for-chrome|msj|4.12.5
ts-prop-dag|nat|1.0.6
vscode-jest|Ort|3.1.1
vscode-versionlens|pfl|0.24.0
rpa-eslint-snippets|rav|0.0.2
vscode-yaml|red|0.6.1
elastic|ria|0.13.3
vscode-javascript-booster|sbu|0.11.0
code-settings-sync|Sha|3.4.3
phpcs|she|1.0.7
svg-preview|Sim|2.8.1
sourcegraph|sou|1.1.0
tech-debt-tracker|Ste|0.23.0
cucumber|ste|0.12.0
vscode-stylelint|sty|0.80.0
gif-code-snippet|sub|1.0.2
language-stylus|sys|1.11.0
stylus-supremacy|thi|2.13.0
vscode-mermaid-editor|tom|0.4.4
php-phan|Tys|1.2.1
vscodeintellicode|Vis|1.2.3
vscode-icons|vsc|9.7.0
vim|vsc|1.12.4
vscode-mermaid-preview|vst|1.5.0
quokka-vscode|Wal|1.0.274
highlight-bad-chars|wen|0.0.3

(2 theme extensions excluded)

</details>

**Comment by bm-stschneider** [comment]
![image](https://user-images.githubusercontent.com/30625381/72529980-adb37a00-386e-11ea-8715-e6af8606226f.png)

**Comment by bm-stschneider** [comment]
first colum is cpu%

**Comment by bm-stschneider** [comment]
After force quit and reload I see that vscode was also trying to open all files.

**Comment by gjsjohnmurray** [comment]
Any chance the slowdown was being caused by one of your 82 extensions? Are you able to repeat the test after reloading with all extensions disabled?

**Comment by bm-stschneider** [comment]
Since I want to complete some work I will not be able to do that and try again.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have `editor.formatOnSave` enabled? In this case it's most likely that Prettier have to reformat each of that 2k files. Or any other extension can perform their tasks on changes in files they handle.

Please try later with all extensions disabled and/or  `"editor.formatOnSave": false` if it was enabled to see if there are any differences.

You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Just performed replace `Replaced 10000 occurrences across 1322 files with` no huge CPU spikes, however looks like some extensions doesn't handle background files changes well (e.g `bracket-pair-colorizer-2` or `markdown-toc` had warnings and errors in DevTools). If extensions perform formatting or costly computation on file change - they will cause this message and huge lag.
