### ISSUE TITLE
Reference panel disappeared

### ISSUE THREAD

**Issue by alexander-zolotykh** [microsoft/vscode#88767]
Reference panel does not exist in Sidebar.
Also triggering "Find all references" opens first tab in sidebar - Navigation panel.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
