### ISSUE TITLE
VSCodeInsider_VSONLINE_AI4D:Name property does not exist for the expand/collapase button.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88765]
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Steps to Reproduce:**
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3. Click on "Visual Studio Online" and navigate till "Remote Explorer"
4. Navigate till "VS ONLINE" control .
5. Open AI4D.
6. Check the name property for the expand/collapse button.

**Actual:**
**Issue1:**
For the "expand/collapse" button name property does not exit .

**Issue2:**
For the "expand/collapse" button,Incorrect control type is provided.

**Expected:​**
**Issue1:**
For the "expand/collapse" button name property should provide and screen reader should announces the same.

**Issue2:**
For the "expand/collapse" button,Correct control type should be  button.

**​User Impact**:​
Screen reader user does not understand name of the regarding the control.
![image](https://user-images.githubusercontent.com/55909580/72530410-54ab0c80-3895-11ea-8ac4-b056d515f4c7.png)

**Comment by isidorn** [comment]
Please file this against the visual studio online extension. They can destill this issue and file in vscode language.
