### ISSUE TITLE
need keyword search history

### ISSUE THREAD

**Issue by quangthanh010290** [microsoft/vscode#88766]
Issue Type: <b>Feature Request</b>

after add new keyword to search, I forget the previous keywork. So I would like to have the history for them, so I just pick one from history list.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.19.0-6-amd64

**Comment by gjsjohnmurray** [comment]
Did you try the <kbd>UpArrow</kbd> key when focus is on the input field?

**Comment by quangthanh010290** [comment]
I did not know this feature. thank you
