### ISSUE TITLE
Multiple method definations and references like SublimeText

### ISSUE THREAD

**Issue by tajveez-73** [microsoft/vscode#88760]
Hi,

I think vscode lacks the capability of getting list of all the definitions and references of method when you hover, I have a Php project and when I have installed a third party extension called Php Intelephense for that (Which sometimes doesn't works) but Sublime Text's built in definitions and references is way better than that, it would be great if get something like that builtin vscode.

**Comment by roblourens** [comment]
This exists, you can use shortcuts like F12 and Shift+F12 to run "go to definition" and "find all references", and that will be driven by the language extension.
