### ISSUE TITLE
VS Code freezes/crashes when closing powershell console

### ISSUE THREAD

**Issue by mclark5300** [microsoft/vscode#88777]
Issue Type: <b>Bug</b>

VS Code 1.41.1

Run application through dotnet cli command: watch run
The app stops running due to an application code error
Close the console (delete the instance)
VS Code freezes requiring force close of the app through task manager

Happens everytime. I downloaded DebugDiag 2, but it's not capturing the crash 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
Looks like #88271 and #88271, which are duplicates of #76548

**Comment by mclark5300** [comment]
Agreed. I did search but didn't find the dupes--sorry
