### ISSUE TITLE
Make symbol searching use "entity.name" TM scopes by default

### ISSUE THREAD

**Issue by Tetralux** [microsoft/vscode#88771]
As it stands, AFAIK, you have to do special plumbing in order to make symbol searching work with programming languages in VS Code.

Sublime Text handles this kind of problem by using the TM scopes in order to provide you a list of functions, etc - namely, the `entity.name.*` scopes.

To make this easier for people to make extensions for languages, it would seem to make sense to use these scopes in a similar way, since that's what you'd want anyway. At least if the extension doesn't provide a source for them, itself.

I'm not too clear on how the symbol system works at present, but I would imagine it would be a welcome improvement, especially if it can be disabled via the VS Code extension API, for when an extension wants to do something special to provide the symbols.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/82024
