### ISSUE TITLE
Go back to git: scheme (from gitfs:) and prior git url (json) format

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#88775]
Recently we changed from `git:` to `gitfs:` and also changed the git uri querystring format from a JSON object to individual querystring values. Can we change them back? These changes have broken certain GitLens features and could negatively affect other extensions as well.

**Comment by alexdima** [comment]
Yes, this affected https://github.com/alexdima/vscode-git-branch as well ... But actually I adopted `gitfs` and now I have to unadopt it

**Comment by joaomoreno** [comment]
Sorry @alexdima.

> For anyone else following along, the new git URIs are not backwards compatible. The path component must now be an absolute path.

What do you mean? It was always required to be an absolute path, that hasn't really changed. :thinking:
