### ISSUE TITLE
Line endings marking change.

### ISSUE THREAD

**Issue by xearonet** [microsoft/vscode#88786]
I would like to propose a change of marking the end of the line in VSCode to unambiguous and more convenient. Now, always you must wonder a second or two, is "LF" is UNIX or Windows line endings.

Literally I mean change:  

this:  
![image](https://user-images.githubusercontent.com/22504894/72541678-3d632380-3883-11ea-948a-3a0b5921b324.png)
to this:
![image](https://user-images.githubusercontent.com/22504894/72541752-5ff53c80-3883-11ea-96e5-877508eae3f0.png)  

and  

this:
![image](https://user-images.githubusercontent.com/22504894/72541818-77342a00-3883-11ea-8e26-04a2f3c5dbce.png)
to this:
![image](https://user-images.githubusercontent.com/22504894/72541879-8adf9080-3883-11ea-9aa6-3b17409d6624.png)
  
<br><br>
Great editor at all.
Thanks!

**Comment by IllusionMH** [comment]
So then everybody will have to do other way around and remember what Win uses and what Unix uses? Current display is literally what will be there - single LF or 2 characters CRLF - less cognitive load.

What are your cases when you need to convert it mentally to system instead of relying on characters?

**Comment by xearonet** [comment]
Hi. Maybe it's more personal. For me it's more clear if I see WIN or UNIX but your point of view is relevant so as I mentioned, it looks more like a personal preference than a rule.

**Comment by xearonet** [comment]
I have a question. I want to create an extension that will do this work, is it possible?
@IllusionMH @alexdima

**Comment by IllusionMH** [comment]
These labels can be overridden with localization.
https://github.com/microsoft/vscode/blob/3f5edc3d45dcbb79fa1711b2b363a69d14303931/src/vs/workbench/browser/parts/editor/editorStatus.ts#L277-L278
So probably you can create you own language pack similar to
https://github.com/microsoft/vscode-loc/blob/b4ae1bae12e1a14c24323e8bac4e950a4a17fe44/i18n/vscode-language-pack-ja/translations/main.i18n.json#L2731-L2732
