### ISSUE TITLE
Winsows 7 + VSCode: The terminal process terminated with exit code: {0}

### ISSUE THREAD

**Issue by payalord** [microsoft/vscode#88780]
I found only issues related Windows 10 with same problem. But since I'm on Windows 7 this can be different.

Downloaded next insiders version and issue still occured on it too:
Version: 1.42.0-insider (user setup)
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T09:36:35.018Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

VSCode version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601 (Windows 7 Ultimate SP 1 64-bit)

Steps to Reproduce:

1. Open VS Code
2. Open Terminal

Does this issue occur when all extensions are disabled?: Yes

Description: It is started probably 1-2 weeks ago or maybe 1 month, not sure. On the first times when issue occured, system restart helped. But now even restart doesn't help. Cmd works fine outside of vscode without any problems.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by payalord** [comment]
Ok, so will it be possible to fix it under Windows 7? Should I install some update on Windows 7? Because all I found for now is only discussions about Windows 10.

**Comment by dehilsterlexis** [comment]
I'm getting the same thing but with Windows 10. Here is my info. I have tried to reinstall but not help.

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
@dehilsterlexis it might be related to anti-virus software on Windows 10 https://github.com/microsoft/vscode/issues/86432

@payalord we don't support Windows 7 anymore, it's _extended_ end of life last month.
