### ISSUE TITLE
Debug Shortcut Keys Reversed

### ISSUE THREAD

**Issue by jefferyp1138A** [microsoft/vscode#88789]
Issue Type: <b>Bug</b>

The Debug keyboard shortcuts for Start Debugging and Toggle Breakpoint are reversed. The Debug menu shows F9 to start debugging and F5 to toggle breakpoint. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
delphi-keybindings|ale|8.1.0
delphi-pack|ale|2.0.0
numbered-bookmarks|ale|6.2.1
pascal|ale|8.0.3
pascal-formatter|ale|2.2.0
ng-template|Ang|0.900.4
vscode-eslint|dba|2.0.14
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
angular-essentials|joh|0.6.3
Angular2|joh|8.3.0
vscode-peacock|joh|3.2.0
vscode-kubernetes-tools|ms-|1.0.9
powershell|ms-|2020.1.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.5
angular2-inline|nat|0.0.17
angular-console|nrw|10.0.0
vscode-jest|Ort|3.1.1
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1

(2 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Most likely they are overriden by `delphi-keybindings` extension.
![image](https://user-images.githubusercontent.com/1312662/72544159-81f4bc00-388f-11ea-818f-111b8d566c3f.png)

**Comment by jefferyp1138A** [comment]
Yes, disabling the Delphi Keymap corrected the problem. Thanks for the quick response.
