### ISSUE TITLE
[FR] $LINE_COMMENT snippet applies an Ending tag automatically to the end on Languages which don't support Single line comments

### ISSUE THREAD

**Issue by A-Matt** [microsoft/vscode#88783]
# Suggestion
When using languages like VB, PHP, Python ETC, They all have access to Line comments allowing for use of the `$LINE_COMMENT` variable in snippets.
While in HTML using this will just return a Space, and do nothing which is a little annoying.

My suggestion for a feature is that for these languages that don't support line commenting with only a prefix to place the starting Comment at the point of the Variable, and then finish the line with the Language's correct Line End comment.

I think in code that using a inline code where possible is far cleaner and easier to manage for people to know where the comment starts (And not have to find the ending) but for languages where it is not supported, it will revert into this instead. Otherwise I'd prefer not have to use a separate snippet just as a replacement to use the comment start and stop snippet variables. 

------- 
### Example 1
```
"example1": {
    "prefix": "exmp1",
    "body": [
        "$LINE_COMMENT ----------------------------------------------------------"
    ],
    "description": "Example 1"
},
```
In languages like PHP, this will return back (Original and existing behaviour)
`// ----------------------------------------------------------`
In languages like HTML, this will return back:
`<!-- ---------------------------------------------------------- -->`

### Example 2
```
"Example 2": {
    "prefix": "exmp2",
    "body": [
        "Some content goes here $LINE_COMMENT and the rest of this line is a comment."
    ],
    "description": "Example 2"
},
```
In languages like PHP, this will return back (Original and existing behaviour)
`Some content goes here // and the rest of this line is a comment.`
In languages like HTML, this will return back:
`Some content goes here <!-- and the rest of this line is a comment -->`

**Comment by jrieken** [comment]
I don't understand. Snippets target a language and if line comments aren't supported there then the `$BLOCK_COMMENT_START` and `$BLOCK_COMMENT_END` variables should be used
