### ISSUE TITLE
Extension API:  expose Intellisense SuggestionItems for a given position

### ISSUE THREAD

**Issue by micomuko** [microsoft/vscode#88782]
Given a position in a document, I would like to have the ability to access the list of suggested items that Intellisense would provide. I believe internally this function is used:
https://github.com/microsoft/vscode/blob/5e6d6f71053c1121f6590b51e55af9c18f5e1f58/src/vs/editor/contrib/suggest/suggest.ts#L139-L145
Some way of reading this list or a list like it would be very useful. 
I'm exploring ways of making coding more accessible for people who are physically impaired one way or another and I would like to leverage Intellisense suggestions to dramatically reduce/ eliminate manual typing load. **Clarification:** I'm not looking to register new suggestions or change the way that items are suggested I just want to be able to **read** suggested items and display/filter them in the UI of my extension or use them to clearly identify voice commands. Thank you! :)

If this functionality already exists, I apologize, I couldn't find it.

**Comment by jrieken** [comment]
There are API commands for that, e.g. `vscode.executeCompletionItemProvider` from https://code.visualstudio.com/api/references/commands

**Comment by micomuko** [comment]
Thank you very much for the quick response, it's exactly what I needed!

**Comment by jrieken** [comment]
Great it works for you. Also adding @isidorn who has been leading an accessibility effort for IntelliSense during the last days.
