### ISSUE TITLE
ASP.NET Debugging No Longer Working

### ISSUE THREAD

**Issue by robbpriestley** [Microsoft/vscode#8879]
- VSCode Version: 1.3.0
- OS Version: OSX El Cap 10.11.5
- .NET Core Version: 1.0.0-preview2-003121

Steps to Reproduce:

1. As normal, use debugger for ASP.NET debugging
2. Upgrade VS Code from 1.2.1 to 1.3.0
2. Debugging no longer works. Error message given in VS Code debug console window:

> ERROR: CLRDBG exited unexpectedly with exit code 133 (0x85). Debugging will now abort.
The program '/Users/Me/MyPath/MyProgram.dll' has exited with code -1 (0xffffffff).

I re-installed .NET Core just to be on the safe side--no difference. I was already running the latest version. I also noticed after I installed the new version of VS Code that a background process re-installed the debug module (? details hazy--I just saw it on the status bar on the bottom of the screen).

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#541
