### ISSUE TITLE
vscode consumes all memory and swap area and freezes the system 

### ISSUE THREAD

**Issue by osocure** [microsoft/vscode#88791]
vscode works from a few minutes to an hour and then freezes and freezes the operating system. It consumes all ram memory and the swap area begins to fill up until the computer no longer responds.
The s.o. is Linux mint 19 and the vscode version is from the repository.

 VSCode Version: 1.41.1
 OS Version: Linux Mint 19

 VSCode
========================
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-66-generic

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by rajinder-yadav** [comment]
This is also happening to me now, it has happened 3 times is the past two days.

The trigger seem to be predictive lookup as you're trying. I have been keeping my system monitor up to view memory usage and I continue to see large spikes of memory getting allocated by vscode.

This needs to be fixed.

The memory spike happens within one second, at which time the entire system is frozen and you can't do anything. So asking us to provide further info is not possible.

**Comment by rajinder-yadav** [comment]
Some addition info on code-insiders

VS Code version: Code - Insiders 1.42.0-insider (9e8c4c247a779cdd1f4f53db963bc6124a28ac2f, 2020-01-30T08:43:06.481Z)
OS version: Linux x64 5.4.14-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3720)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|31.30GB (28.03GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.1.8
vscode-base64|ada|0.1.0
Bookmarks|ale|10.7.0
ng-template|Ang|0.900.8
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
shell-format|fox|7.0.1
markdown-preview-bitbucket|hbr|1.0.0
vscode-peacock|joh|3.3.1
solidity|Jua|0.0.68
terraform|mau|1.4.0
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
Go|ms-|0.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
angular2-inline|nat|0.0.17
vscode-yaml|red|0.6.1
markdown-preview-enhanced|shd|0.5.1
language-stylus|sys|1.11.0
sort-lines|Tyr|1.9.0
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.1

(5 theme extensions excluded)

</details>

**Comment by rajinder-yadav** [comment]
OK this seems to be just happening randomly, don't know what's causing this! I was just moving the edit cursor this time and this bug froze my system.

![vscode-memory-bug](https://user-images.githubusercontent.com/439226/73518109-6deea580-43cb-11ea-9ac0-52382d47d8dd.png)
