### ISSUE TITLE
Intellisense help text is truncated

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#888]
<img width="555" alt="screen shot 2015-12-01 at 3 08 08 pm" src="https://cloud.githubusercontent.com/assets/466713/11517308/65011810-983d-11e5-9218-64ddc2d406a8.png">

The help text for the JSON property is truncated, so it ends with "Can be omitted if ......."

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by joaomoreno** [comment]
Duplicate of #369
