### ISSUE TITLE
'pip' is not recognized.  '$' prompt missing in Terminal.

### ISSUE THREAD

**Issue by maiormarso** [microsoft/vscode#88805]
Issue Type: <b>Bug</b>

1. $ missing  in Terminal 
2.  Using Python 3,7.4 64-bit
PS C:\VSC> pip
pip : The term 'pip' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the   
name, or if  a path was included, verify that the path is correct and    
try again.
+ pip
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], Command  
   NotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (23.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.58038

</details>

**Comment by Tyriar** [comment]
You're using powershell so there isn't meant to be a $, if pip is missing it's likely a problem with your environment setup.
