### ISSUE TITLE
`searchViewletFocus` gets set `true` on launch if the viewlet is open, even if it is not focused

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#88803]
To rest to false, you must focus then blur the viewlet. In particular, this means that if you reload the window with the viewlet open, triggering the keybinding for toggle regex will toggle the global search regex instead of the find in files regex (assuming they're the same bind), until you explicitly focus and de-focus the viewlet.

**Comment by JacksonKearl** [comment]
@roblourens any ideas on why this would happen? 
added 
![image](https://user-images.githubusercontent.com/8586769/72556850-602a1380-3854-11ea-91ac-4c8598bc8bfc.png)
and see that the focus callback gets called immediately on launch, even if its not focused.

**Comment by roblourens** [comment]
@sbatten ?

**Comment by JacksonKearl** [comment]
Element gets focused on creation here https://github.com/microsoft/vscode/blob/ceec95bb1623522c13d550c9ca53232692194922/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L358

But it seems that it doesn't then get blured

**Comment by sbatten** [comment]
@sandy081 i don't think this was introduced in the refactor, is there a reason this should focus on create?

**Comment by sandy081** [comment]
I do not see a reason, I also think it is not correct to focus on create.

**Comment by alexdima** [comment]
I also hit this and it blocked me from committing in the Git Viewlet because `cmd+enter` was eaten by:
```
{ "key": "cmd+enter",             "command": "search.action.openInEditor",
                                     "when": "hasSearchResult && previewSearchEditor && previewSearchEditor && searchViewletFocus" },

```
