### ISSUE TITLE
Searching for symbols requires exact match

### ISSUE THREAD

**Issue by thaindq** [microsoft/vscode#88806]
- Version: 1.41.1 (user setup)
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T14:58:56.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open symbols searching palette
2. Type in symbol name: for example to search for function `getAccountList`
- Works: `getaccountl`
- Doesn't work: `getacli` (this works when searching for files)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Which language?

**Comment by thaindq** [comment]
Typescript & Javascript
I haven't tried others

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/13909
