### ISSUE TITLE
Improve UI view for arguments in settings 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#88802]
Sometimes arguments are pairs of flags and values, and while in the  settings.json file you have this...

```json
"python.sortImports.args": [
        "-w", "120",
        "-lai", "2"
    ],
```
... this is what appears on the UI:

![image](https://user-images.githubusercontent.com/45497113/72555442-6bc80b00-3851-11ea-8212-9e5dab590b97.png)

Maybe the arguments could be displayed side by side, instead of line by line?

**Comment by roblourens** [comment]
I'm not sure, it would require a level of customization that I don't really want to deal with but on the other hand I think this is a common case.

**Comment by pohmelie** [comment]
I don't like a "side by side" solution. I think it is better to improve parsing of arguments, so `["-w 120", "--foo 123"]` will be splitted to `["-w", "120", "--foo", "123"]`.

**Comment by roblourens** [comment]
One benefit of using an array vs string is that the user doesn't have to figure out how to escape a space

**Comment by pohmelie** [comment]
Yes, you are right, but, in this case, why `"-w 120"` works fine, but `"--foo 123"` do not? I think it is better to bring behvaior into consistent state.

**Comment by luabud** [comment]
@pohmelie That I'm not sure. When it comes to the Python extension, all it does is to concatenate the command we will send to the tool with the arguments specified on the setting.
