### ISSUE TITLE
Allow users to change color of taskbar icon

### ISSUE THREAD

**Issue by mfearby** [microsoft/vscode#88819]
It would be nice if we could change the colour of the taskbar icon through settings so that I can more easily differentiate all my open applications. So many of them have blue icons that I keep clicking on the wrong one all the time. Ever since I switched to Microsoft Edge (chromium version) with its blue/green icon, I keep accidentally clicking on it and VSCode because they're both very blue.

If we could customise the icon or even just toggle between the old orange one and the current blue one, that'd be enough. The only other alternative I have is to go back to Google Chrome because there's no way I can mix up a red/green/yellow icon and a blue one.

This request probably sounds pedantic, but when so many icons are mostly the same colour, it quickly becomes very annoying to find the right one. I checked to see if there's an extension to do it but there isn't. Even if it was permissible to change the icon through an extension, that would be enough.

Thanks.

**Comment by Siccity** [comment]
![image](https://user-images.githubusercontent.com/6402525/72596362-2f0d1a00-390c-11ea-84fa-50a8050484d8.png)

You can already do this through windows

![image](https://user-images.githubusercontent.com/6402525/72596415-42b88080-390c-11ea-9366-d48adbc5f970.png)

You can set any icon you want

**Comment by mfearby** [comment]
Changing the pinned shortcut has no affect to the running VSCode application. As soon as you start the app, it reverts to its internal icon.
