### ISSUE TITLE
project-level syntax colorizer for integrated terminal

### ISSUE THREAD

**Issue by ponyatov** [microsoft/vscode#88812]
https://stackoverflow.com/questions/49405353/how-to-get-colourful-integrated-terminal-cmd-in-vs-code

It would be great to have a project-level syntax colorizer for terminal implemented as .dll built by flex/bison/g++ compiler in project/.vscode. As a variant, it can be some colorizing filter generated by ANTLR into .js file (if it is possible) or PEG.js

The problem this issue should solve is highlighting logs of large continuous builds, and making standard shell console more user-friendly.

**Comment by Tyriar** [comment]
The colors in the terminal are driven by the shell and applications that run within it,
