### ISSUE TITLE
Add sticky/fixed indent/dir-levels to doc explorer tree when expanded and scrolling

### ISSUE THREAD

**Issue by thelazydogsback** [microsoft/vscode#88810]
This is a request to make each level of the current tree sticky, so that each element up to the current level of expansion is not scrolled off the top of the list but remain, so that they become level breadcrumbs.
As it is, if node_modules is ever expanded, for example, it's difficult to find you're way back up.

**Comment by Adondriel** [comment]
Should this be combined with: https://github.com/microsoft/vscode/issues/89849?

**Comment by AlexWayfer** [comment]
@isidorn, this issue is duplicate of what issue? #89849 mentioned above? 89849 is greater than 88810, so that is duplicate, not this.

**Comment by thelazydogsback** [comment]
We are also proposing different solutions, so they should be linked or combined rather than having only one open.

**Comment by AlexWayfer** [comment]
So, will there be an explanation of closing or re-opening?

**Comment by AlexWayfer** [comment]
One month have passed, @isidorn, we're waiting your response, please.
