### ISSUE TITLE
All the extension icons in the activity bar are gone after last update

### ISSUE THREAD

**Issue by stephenmirving** [microsoft/vscode#88814]
Issue Type: <b>Bug</b>

Since the last update, all the extra extension icons that are in the activity bar are no longer there.

VS Code version: Code - Insiders 1.42.0-insider (235695393db763af632fab376b890d63d8a48576, 2020-01-16T18:51:39.093Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (128)</summary>

Extension|Author (truncated)|Version
---|---|---
vsctoix|a-b|1.8.0
vscode-color-pick|ada|0.6.2
vscode-monokai-seti|adi|0.0.5
aessoft-class-autocomplete|AES|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
quotify|ala|0.0.4
increment-selection|alb|0.2.0
xbasic|Alp|0.0.5
incr|ara|1.0.0
atlascode|atl|2.3.1
openmatchingfiles|bca|0.4.1
vscode-icontheme-nomo-dark|be5|1.3.6
copyswapper|ber|1.0.7
color-info|bie|0.5.1
lit-html|bie|1.11.1
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
bemhelper|Box|0.8.0
split-line|che|1.0.1
quills|chr|1.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-devtools-for-chrome|cod|0.0.5
gitignore|cod|0.6.0
transformer|dak|1.6.0
hex-to-rgba|dak|1.0.0
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.14
vscode-deepscan|Dee|1.9.3
githistory|don|0.4.13
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
css-flexbox-cheatsheet|dzh|1.2.1
css-initial-value|dzh|0.2.3
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
replacequotes|eda|0.0.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
moxer-icons|Equ|5.4.0
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.14.1
file-icons|fil|1.0.21
vscode-firefox-debug|fir|2.6.1
gc-excelviewer|Gra|2.1.32
name-that-color|gui|0.1.2
imagesprites|gur|1.0.0
output-colorizer|IBM|0.1.2
javascript-snippets|jab|1.0.6
vscode-cdnjs|Jak|0.18.0
RelativePath|jak|1.4.0
search-node-modules|jas|1.3.0
diff-tool|jin|0.0.1
vscode-text-pastry|jkj|1.2.0
svg|joc|1.0.6
vscode-peacock|joh|3.2.0
scss-bem-support|jol|0.0.6
vscode-insertdatestring|jsy|2.2.4
better-line-select|kai|1.1.1
vscode-cfml|Kam|0.5.3
chat|kar|0.31.0
vscode-go-to-mdn|kby|1.1.1
vscode-gutter-preview|kis|0.24.2
cssSuggestions|kun|1.0.11
vsls-whiteboard|los|0.0.9
vscode-checkpoints|mic|1.2.0
HTMLHint|mka|0.6.0
selected-character-count|mou|0.0.1
vscode-apache|mrm|1.2.0
vscode-attrs-sorter|mrm|2.1.0
vscode-scss|mrm|0.8.1
vscode-edge-devtools|ms-|1.0.6
remote-wsl|ms-|0.42.1
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|3.8.20200116
vsliveshare|ms-|1.0.1482
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.5
color-highlight|nau|2.3.0
nojquery-snippets|Nkz|0.1.3
syncing|non|3.0.13
indent-rainbow|ode|7.4.0
convert-css-in-js|pau|1.1.3
emoji|Per|0.0.3
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
vscode-css-navigation|puc|1.9.0
text-power-tools|qcz|1.11.1
quicktype|qui|12.0.46
subtle-brackets|raf|3.0.0
vscode-sassdoc|raf|1.0.0
vscode-yaml|red|0.6.1
vscode-sort-json|ric|1.18.0
LiveServer|rit|5.6.1
px2vworvh|Riu|1.0.2
color-manager|roy|0.5.4
gi|rub|0.2.11
partial-diff|ryu|1.4.0
color-stamp|s3a|1.0.0
px-to-rem|sai|1.2.7
vscode-javascript-booster|sbu|0.11.0
git-merger|sha|0.4.1
vscode-leetcode|she|0.16.0
stylelint|shi|0.51.0
gitconfig|sid|2.0.1
vscode-fileutils|sle|3.0.1
swdc-vscode|sof|1.3.9
rewrap|stk|1.9.1
prettier-plus|svi|3.6.2
vscode-workspace-explorer|tom|1.5.0
sort-lines|Tyr|1.9.0
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.3
spaces|vsl|0.1.2
vscode-wakatime|Wak|2.2.1
quokka-vscode|Wal|1.0.274
vscode-todo-highlight|way|1.0.4
save-and-run|wk-|0.0.21
change-case|wma|1.0.0
scss-modules|won|1.0.1
vscode-surround|yat|1.0.2
emmet-live|yse|1.0.0
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|2.7.0
file-size|zh9|0.1.3

(31 theme extensions excluded)

</details>

**Comment by tomaxsas** [comment]
same here. Platform win 10

**Comment by madwebskills** [comment]
Also happening here (Windows 10). Problem persists in today's build (2020-01-17T05:42:30.764Z)

**Comment by dlucazeau** [comment]
Activity Bar : same here on Windows 10
Explorer: 
- 'VSCode simpler Icons' or 'Seti' are shown
- but not 'Material Icon Theme' or 'Minimal'
These problems doesn't exist on Ubuntu

Version: 1.42.0-insider (user setup)
Commit: b600d39061b60ed50f6df14dd405227c7618b7b7
Date: 2020-01-17T05:42:30.764Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by ctf0** [comment]
same
```
Version: 1.42.0-insider
Commit: b600d39061b60ed50f6df14dd405227c7618b7b7
Date: 2020-01-17T05:35:40.078Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by gtim108** [comment]
Same
Version: 1.42.0-insider
Commit: 2c7656f097d1150dbc5432253b2cd75b24a0229e
Date: 2020-01-17T08:00:18.698Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.12-xanmod7

**Comment by alexander-zolotykh** [comment]
Same
```
Version: 1.42.0-insider
Commit: b600d39061b60ed50f6df14dd405227c7618b7b7
Date: 2020-01-17T05:35:40.078Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0
```

**Comment by pookdeveloper** [comment]
The same in MacBook PRO:

Version: 1.42.0-insider
Commit: b600d39061b60ed50f6df14dd405227c7618b7b7
Date: 2020-01-17T05:35:40.078Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

**Comment by stephenmirving** [comment]
Today's update that just got pushed fixed it for me in Windows 10. Everything back to normal. Thanks for the hard work, **really** appreciate the swift resolution!

**Comment by dlucazeau** [comment]
For a few days this bug is present again.

Activity Bar : extensions icon are not visible, they have only their placeholder.
Explorer: "VSCode simpler Icons" or "Seti" are shown but not 'Material Icon Theme' or 'Minimal'

These problems doesn't exist on Ubuntu

Version: 1.43.0-insider (user setup)
Commit: 4c9161a3f125f5a788aafa73a4ecfcb27dcfc319
Date: 2020-02-14T05:34:36.456Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

![2020-02-17_08-08-57](https://user-images.githubusercontent.com/4538922/74631331-fe174380-515c-11ea-9fea-bd939e385e6a.png)
![2020-02-17_08-09-16](https://user-images.githubusercontent.com/4538922/74631332-feafda00-515c-11ea-8ee0-25050ac05a22.png)
