### ISSUE TITLE
Git file status badges doesn't appear

### ISSUE THREAD

**Issue by armanbayona** [microsoft/vscode#88818]
Issue Type: <b>Bug</b>

open a git repo, then edit a file, a 'modified' badge beside the file should appear.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.15.0-74-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics (8 x 1744)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.80GB (0.47GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-cmd-shift-d|and|1.2.2
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.5.0
prettier-vscode|esb|3.18.0
python|ms-|2020.1.58038
sqltools|mtx|0.21.6
material-icon-theme|PKi|3.9.2
swdc-vscode|sof|1.3.9

</details>

**Comment by joaomoreno** [comment]
Can you share a screen recording of the issue occurring?

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://getkap.co/)?
