### ISSUE TITLE
The BUG about files

### ISSUE THREAD

**Issue by zhongyf** [Microsoft/vscode#8881]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.When I draged the file into VS code, nothing was happended.
2.

**Comment by bpasero** [comment]
@zhongyf did you drag a folder maybe?

**Comment by trailofdad** [comment]
@bpasero I didn't want to open a new issue because I think this is the same issue I am having. It looks like when you drag a folder into the editor it does not load the folder like the previous version. 

Using Version 1.3.0 (1.3.0)
OSX Version 10.11.2

**Comment by bpasero** [comment]
@trailofdad yes, we fixed this for insiders already.

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by trailofdad** [comment]
@bpasero Awesome, looks like it's working as expected :) Thanks! Lots of great features in the newest release.
