### ISSUE TITLE
Ctrl+P should use folder name for search

### ISSUE THREAD

**Issue by tomaszkiewicz** [microsoft/vscode#88828]
Let's assume the scenario:

I'm working in multi-root environment and I attach multiple folders for each environments to my workspace.
Let's say I attached folders like terraform-dev, terraform-uat, terraform-prod. In each folder there's a file like let's say database.tf. 

Current behavior of VSCode with Ctrl+P + database is that it'll show the results for both folders with the label of folder name on the right.

I'd like to be able to search using also a folder name: I type Ctrl+P + devdatab and VSCode should find only database.tf file inside terraform-dev folder.

**Comment by IllusionMH** [comment]
It already uses fuzzy matching so you can type folders and files names. you can type `devdata` and if terraform-uat, terraform-prod doesn't have `d`, `e`, `v` in this order and in path to `database` file you'll have one match.

**Comment by tomaszkiewicz** [comment]
It does that for folders inside my "roots", but not for the "root folder" name.

Steps to reproduce:

1. Start with blank workspace

![image](https://user-images.githubusercontent.com/8005425/72612525-558f7d00-392d-11ea-8890-adfa00cd465a.png)

2. Create folders and files

```
~/projects> mkdir terraform-dev
~/projects> mkdir terraform-stage
~/projects> mkdir terraform-prod
~/projects> touch terraform-dev/database.tf
~/projects> touch terraform-stage/database.tf
~/projects> touch terraform-prod/database.tf
```

3. Add above folders to workspace

4. Now we have multi-root environment:

![image](https://user-images.githubusercontent.com/8005425/72612750-f0885700-392d-11ea-811e-e546e7e92633.png)

5. Now I can Ctrl+P and type "database" to get:

![image](https://user-images.githubusercontent.com/8005425/72612834-26c5d680-392e-11ea-82eb-0278376bda1f.png)

As you can see the labels are there, however if I want to search for specific file in specific folder....

6. When I Ctrl+P and type "devdata":

![image](https://user-images.githubusercontent.com/8005425/72612874-4ceb7680-392e-11ea-871f-eed8969783ad.png)

I got no results, as "root folder name" is not considered in search.

So this feature request is about adding that "root folder name" as a part of fuzzy search in Ctrl+P.

**Comment by IllusionMH** [comment]
Thanks for clarification!

**Comment by roblourens** [comment]
Got https://github.com/microsoft/vscode/issues/32444 for this
