### ISSUE TITLE
Trim auto whitespace even after it was trimmed once, but the trimming was undone

### ISSUE THREAD

**Issue by zhyiyu** [microsoft/vscode#88821]
I know VS code is doing auto indention, which means when new line is created with enter, it is auto indented to the previous lines indention.

I also know that if later codes were written in some other line while the new line just created has nothing, its indention will be deleted.

But, if I create a new line with enter, then search for many occurrences of that string, select them, then edit them. The auto created indention will remain!

So I am providing this feedback to ask if the auto deletion of auto indention could detect more cases.

Thanks!

**Comment by alexdima** [comment]
@zhyiyu I don't think I fully understand the steps you are doing. Are you using `"editor.trimAutoWhitespace": true`? What exact steps do you take?

**Comment by zhyiyu** [comment]
@alexdima 

I am glad to provide more information!

Also, I found out my description was not quite accurate, to clarify, a screen record in `zip` is attached.

In the screen record, I made a new line after `for i in range(10):`, the indention is made automatically. The instead of writing anything on that new line, I wrote something on the last line, which leads to the auto deletion of the auto indention. This is all good. However, at fifth second, after I press `command` plus `z`, the auto deletion of auto indention seems to be disabled! It overlooks the editions on others lines and never deletes the auto indentions.

[trim.zip](https://github.com/microsoft/vscode/files/4079897/trim.zip)

**Comment by alexdima** [comment]
Thank you, I now understand what the desire is: Auto whitespace is not trimmed after it is trimmed once and the trimming is undone by cmd+z. 

For completeness, here are the steps:
* Use `"editor.trimAutoWhitespace": true`
* Have a file like:
```
for (let i = 0; i < 100; i++) {
    console.log(i);
}
```
* Press Enter after `{`
* (auto whitespace is inserted)
* Move cursor at the end of the `console.log` line and type
* The auto whitespace is auto removed
* Press Cmd+Z to undo
* Both typing and the auto whitespace removal are undone
* When typing again, the auto whitespace is no longer removed
