### ISSUE TITLE
markdown not enabling

### ISSUE THREAD

**Issue by jandrieu** [microsoft/vscode#88820]
Issue Type: <b>Bug</b>

I open a folder with a markdown file in it. Extension .md.

No markdown commands are available. The preview option doesn't seem to exist.

If I try a markdown extension, such as instant markdown, it DOES at least get added to the command palette, but the commands fail: "command 'instantmarkdown.openBrowser' not found"

I'm trying to find other places to get an error from VS Code that would explain what's wrong with the markdown stuff, but I'm at a loss.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (3.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.33.0
vscode-instant-markdown|dba|1.4.4
scad|efb|1.0.1
sublime-babel-vscode|jos|0.2.10
remote-wsl|ms-|0.41.7
debugger-for-chrome|msj|4.12.5
html-mason|via|1.0.0

</details>

**Comment by jandrieu** [comment]
As near as I can tell, this is a unique issue. I don't think I'm using the custom editor preview and I don't need auto preview--any preview would be great. It's like the markdown subsystem just isn't getting loaded (no commands in the command palette). Not sure how to further debug.

**Comment by gjsjohnmurray** [comment]
Does the problem reproduce after you use command palette to run the command that reloads with all extensions disabled?

After opening your markdown file does the language indicator on the status bar show the correct value?

**Comment by jandrieu** [comment]
Perfect. That fixed it.

Turns out that another extension was blocking the markdown. HTML (Mason) was the culprit.

Thank you.

**Comment by jandrieu** [comment]
FWIW, I didn't know it was an extension. I would happily report the problem with HTML (Mason) but I'm stuck in a login loop I can't break through at the marketplace.
