### ISSUE TITLE
VSCode window is not focused when creating a new file/folder

### ISSUE THREAD

**Issue by wahidrahim** [microsoft/vscode#88822]
- VSCode Version: 1.41.1
  Commit: 26076a4de974ead31f97692a0d32f90d735645c0
  Date: 2019-12-18T14:57:51.166Z
  Electron: 6.1.5
  Chrome: 76.0.3809.146
  Node.js: 12.4.0
  V8: 7.6.303.31-electron.0
  OS: Darwin x64 19.2.0

- OS Version: macOS 10.15.2

Steps to Reproduce:

1. click outside of the vscode window
2. inside the vscode window right click and in the options click new folder
3. 🐞the new folder is ready to be created but typing has no effect since the window is not focused

Demonstration:
![ezgif-1-1ff039bff208](https://user-images.githubusercontent.com/7417976/72584783-64d4e300-38b9-11ea-9a10-95b3d435a656.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/70966
