### ISSUE TITLE
[html] Mirror cursor doesn't work inside a script tag where type is set to text/html

### ISSUE THREAD

**Issue by Steve-Mcl** [microsoft/vscode#88838]
- VSCode Version: 1.42-insiders
- OS Version: Win 10

![image](https://user-images.githubusercontent.com/44235289/72610548-97192b80-391f-11ea-9483-03bdb9c5da90.png)

Steps to Reproduce:

1. Create html file
2. Write some `div` pairs inside a `script` tag with type set to `text/html`
3. Moving the cursor over the script tag - ok (mirror cursor present)
4. Moving cursor over tags inside the `script` tag **does not produce a mirror cursor**

See gif below...

![mirror-cursor-in-script-tag](https://user-images.githubusercontent.com/44235289/72610557-a0a29380-391f-11ea-8383-18fff4a4136c.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Steve-Mcl** [comment]
@aeschli Really? Feature request? I'd agree with "Bug" or something similar. 

The example I provided is valid HTML and the mirror cursor clearly doesn't work  - i'd call that a bug.

Either way, just glad its on the road map.

**Comment by aeschli** [comment]
The feature request is to generally support `<script type="text/html">` and content which we don't as it's not the most common usage of a script tag.
That involves many more thing than just the mirror cursors (code complete, hovers, .... )

**Comment by aeschli** [comment]
Marking as dup of https://github.com/microsoft/vscode/issues/77977.
Once we support `<script type="text/html">` also the mirror cursor will work (along with many other features)
