### ISSUE TITLE
webviews not working at all on code-exploration

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#88831]
Issue Type: <b>Bug</b>

Webviews do not work with the latest exploration build.

Steps to Reproduce:

1. Get this folder:
https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample

2. npm install

3. Run the extension

4. Run "Cat coding" command

5. Observe webview opens with nothing inside

VS Code version: Code - Exploration 1.42.0-exploration (779ba5939a3866cbc3e31dc1290eb8fa700f7104, 2020-01-06T11:45:06.603Z)
OS version: Linux x64 4.15.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (0.63GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sguillia** [comment]
The extensions readme do not appear either. Simply go in the integrated marketplace and click any extension. The details wont appear.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sguillia** [comment]
Webviews work for the version below

```
Version: 1.42.0-insider
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T08:55:46.564Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-74-generic
```

**Comment by bpasero** [comment]
Ok, please stick to that version. The exploration build is currently unsupported until we switch to E8.
