### ISSUE TITLE
Terminal error

### ISSUE THREAD

**Issue by yaras6** [microsoft/vscode#88833]
Issue Type: <b>Bug</b>

I can not open intrnal terminal:

I get notification:
The terminal process terminated with exit code: {0}

In log file I see bellow errors:
2020-01-17 10:45:35.308] [renderer1] [debug] Terminal process exit (id: 1) with code Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
[2020-01-17 10:45:35.308] [renderer1] [debug] Terminal process exit (id: 1) state 5 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (24.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by yaras6** [comment]
This is strange, because today it is working without issues.
I changed nothing, but it is fine now.

**Comment by Usman046** [comment]
i added "\winpty-agent.exe" and "winpty.dll" in my AVG Exceptions but still VS code is not allowing to open terminal and shows notification as:

**The terminal process terminated with exit code: {0}**

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0 Date: 2019-12-18T14:58:56.166Z 
Electron: 6.1.5 
Chrome: 76.0.3809.146 
Node.js: 12.4.0 
V8: 7.6.303.31-electron.0 
OS: Windows_NT x64 10.0.17134

Kindly help. Thanks.

**Comment by yaras6** [comment]
Today it stopped working again. This is really strange. 3 of my teammates have similar issue.

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-error-connectnamedpipe-failed-windows-error-232
