### ISSUE TITLE
Permission dialog is shown more often

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#88842]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/10746682/72614543-d2712580-3932-11ea-83b4-09bce7aa20f8.png">

**Comment by bpasero** [comment]
Yes, seeing this also starting from today.

**Comment by jrieken** [comment]
Locally, I have disabled the account extension but tests that won't work...

**Comment by RMacfarlane** [comment]
Should be fixed with https://github.com/microsoft/vscode/commit/2eb1c837d73d1dfa80aec59208c76a0d2829e936. The prompt will still be shown the first time OSS/Insiders is opened, but now after hitting "Always Allow" it should stop prompting on subsequent opens.
