### ISSUE TITLE
Opt+Shift+back-arrow highlights more than just tag element

### ISSUE THREAD

**Issue by josh-unwin** [microsoft/vscode#88848]
Issue Type: <b>Bug</b>

Not necessarily a bug as such, but a frustrating thing that other editors I've used don't do.
Here is a link to a gif showing the issue: http://g.recordit.co/u736n1s4Qg.gif
![u736n1s4Qg](https://user-images.githubusercontent.com/49525488/72618524-8d9dbc80-393b-11ea-865f-553cb1b35d92.gif)

When you try to highlight a tag using Opt+Shift+back-arrow, depending on the characters used VSCode often automatically highlights unwanted extra characters.

Examples:
1. `<div><h1>Some text</h1></div>`
2. `<div>{myVariable}</div>`

In first example, if I wanted to highlight the closing div tag at the end using Opt+Shift+back-arrow on the keyboard, it will highlight: `></div>`
Obviously ideally we just want to highlight: `</div>`

Same for the second example, it will highlight: `}</div> `
Not: `</div>`

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv|-psn_0_340051|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|1.5.0
vscode-eslint|dba|2.0.14
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
beautify|Hoo|1.5.0
material-icon-theme|PKi|3.9.2
code-settings-sync|Sha|3.4.3
ayu|tea|0.18.0
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
@alexdima is the expert on word selection. I assume the feature isn't language aware and doesn't know about html tags.
We have a feature called `Expand Section` that is. When invoked repeatedly, it will select the id at the cursor, then inside the tag, the whole tag, the whole element and so on.

**Comment by alexdima** [comment]
This feature request is incredibly similar to #88872

**Comment by ultraGentle** [comment]
Hi, I opened #88872, so just want to chime in: yes, it's the same issue.  I've updated the title and examples to make that clearer.  

 Since `><` are both word separators, when they're adjacent, word nav skips to the end of the group, just like `)}` or `"]'` or all of `>>>>}""}))]]))`.  In this case, the skipping causes highlighting, too, but same root cause.
