### ISSUE TITLE
Make all debugger extension use the DebugAdapterDescriptorFactory

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#88849]
How debug extensions start their debug adapters:

**Dart:**
Lets VS Code start debug adapter in the old-fashioned way: DA's entry point is [contributed in package.json](https://github.com/Dart-Code/Dart-Code/blob/1436bdb49b54a650a63446afb8b71f874ef1e7bc/package.json#L1528-L1529) and VS Code starts it when needed. Behind the scenes this static approach results in a `DebugAdapterDescriptorFactory` that returns a `vscode.DebugAdapterExecutable` that contains the `program` attribute from the package.json.

**C++:**
Uses `DebugAdapterDescriptorFactory` that executes the real DA by returning a `vscode.DebugAdapterExecutable`.
See https://github.com/microsoft/vscode-cpptools/blob/223f63036c70849870595c9ff17799b83a8f8c82/Extension/src/Debugger/debugAdapterDescriptorFactory.ts#L36-L52.

**C#:**
Uses the deprecated precursor of the `DebugAdapterDescriptorFactory`. An "adapterExecutableCommand" was a command that VS Code would use like the `DebugAdapterDescriptorFactory` of today (but it is less flexible).
See https://github.com/OmniSharp/omnisharp-vscode/blob/5c4d5c73361b1d023d89c4fe6c796bcc67c113f9/src/coreclr-debug/activate.ts#L113-L152
I've [asked the team](https://github.com/OmniSharp/omnisharp-vscode/issues/3512) to convert their use of deprecated API to the `DebugAdapterDescriptorFactory`.

**Java:**
Uses another deprecated precursor of the `DebugAdapterDescriptorFactory`:
In the `resolveDebugConfiguration` hook they make VS Code connect to the Java Language and Debug Server process by [setting the `serverPort` attribute in the launch config](https://github.com/microsoft/vscode-java-debug/blob/5f15f9ab721b5be455d33d23952031a57df1744c/src/configurationProvider.ts#L223-L232 ). This is equivalent to the use of a `DebugAdapterDescriptorFactory` and returning a `vscode.DebugAdapterServer` object.
I've [asked the team](https://github.com/microsoft/vscode-java-debug/issues/751) to convert their use of deprecated API to the `DebugAdapterDescriptorFactory`.

**Python:**
implements an Node.js DA that delegates communication to the Python debugger.

---

The following extensions are still using the deprecated "adapterExecutableCommand":

<img width="858" alt="2020-07-22_10-58-14" src="https://user-images.githubusercontent.com/1898161/88157649-53271c00-cc0b-11ea-8538-981de6ef3ad4.png">

**Comment by JoeRobich** [comment]
Updating the C# extension in https://github.com/OmniSharp/omnisharp-vscode/pull/3912

**Comment by DanTup** [comment]
> **Dart**:
> Lets VS Code start debug adapter in the old-fashioned way: DA's entry point is contributed in package.json and VS Code starts it when needed. Behind the scenes this static approach results in a DebugAdapterDescriptorFactory that returns a vscode.DebugAdapterExecutable that contains the program attribute from the package.json.

This isn't quite right - looks like I forgot to delete that from `package.json`. We actually spawn in-process:

https://github.com/Dart-Code/Dart-Code/blob/98f568e3a0bb9237a5699f660b0b1ba00d6e1a35/src/extension/providers/debug_config_provider.ts#L467-L478

However, by coincidence yesterday I started moving them back out of process (https://github.com/Dart-Code/Dart-Code/issues/1876) using a `DartDebugAdapterDescriptorFactory` :-)

**Comment by weinand** [comment]
Support for the obsolete APIs has been removed from VS Code.
