### ISSUE TITLE
Disable editor.acceptSuggestionOnCommitCharacter by default

### ISSUE THREAD

**Issue by aalexgabi** [microsoft/vscode#88844]
In JavaScript when typing:
```js
run(
```
I end up with:
```js
return()
```
Because return is the first suggestion and `(` is considered a commit character. This happens any time I call a function that is not imported yet (it will grab the first suggestion which is never good).

This happens very very often. Over the last two months I came across this pattern a lot (which becomes very annoying) because I'm calling a function before actually importing it (I want to stay in the flow of what I want to write and I fix the imports afterwards).

The alternative would be to remove `(` from the list of commit characters.

**Comment by gjsjohnmurray** [comment]
Another idea is the one I propose in #85768. Please consider upvoting it.

**Comment by rwilliams** [comment]
I've got a very similar backlog candidate too. https://github.com/microsoft/vscode/issues/85079

**Comment by aesyondu** [comment]
Is there any use case at all where it would be better for the text editor to automatically guess and automatically type the coder's intention, rather than the coder manually pressing one TAB key?
