### ISSUE TITLE
Suggestion for React not working {cntrl+space}

### ISSUE THREAD

**Issue by umarzirgham** [microsoft/vscode#88845]
Hello dear

I hope you are doing great. As your tool is superb but unfortunately after your last update cannot able to suggest when use {cntrl+space} and when open taskbar your tool is using so much CPU. This issue is serious because it is making disturbance. If my explanation not clear please let me know I will elaborate it more. Thanks

Regards
Umar Ilyas

**Comment by mjbvz** [comment]
Please fill out our issue template. Include information about which VS Code version and operating system you are using

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as not actionable without more information
