### ISSUE TITLE
Only show suggest details close button on hover

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#88852]
Doesn't look good:

![image](https://user-images.githubusercontent.com/4033249/72621722-1a4b7900-3942-11ea-98a5-5ed9ad9cb5fe.png)

**Comment by misolori** [comment]
I'm not sure we should hide this on hover, otherwise how else does the user know that they can close it? Other items that show actions on hover also show them on focus, but I don't believe there is a focus state for this, which would make it not accessible.

**Comment by octref** [comment]
@misolori I agree. I'll think a bit about this.

**Comment by AlexStrNik** [comment]
@msicolor how about making close button more transparent by default (opacity: 0.7 for e.g) and non-opaque on hover. Also, I think that `details view` should have the right margin or padding, to make text not overlapping by close button

**Comment by misolori** [comment]
I'm not sure that changing the opacity will do much to the close button or what it's trying to achieve. I do agree that we should fix the margin/padding so text doesn't overlap with it though.

**Comment by jrieken** [comment]
As discussed, tweaked the positioning but not hiding the button
