### ISSUE TITLE
Initial text in integrated terminal disappears when starting to type

### ISSUE THREAD

**Issue by Cristy94** [microsoft/vscode#88858]
- VSCode Version: 1.41.1 (but it has always happened on this PC)
- OS Version: Windows 10 - 1809
- I have a 4k screen, I tried with --disable-gpu still same issue.

Steps to Reproduce:

**This happens only the first time after a new terminal is opened**

1. Open VSCode
![image](https://user-images.githubusercontent.com/1384885/72626936-e83f1480-394b-11ea-83f4-8045d14417ce.png)

2. Start typing something in the terminal (previous text is cleared, curret path invisible)
![image](https://user-images.githubusercontent.com/1384885/72626966-f4c36d00-394b-11ea-9783-899a664f44b6.png)

3. After pressing Enter (everything back to normal?):
![image](https://user-images.githubusercontent.com/1384885/72626996-0442b600-394c-11ea-91a3-061423cb1b57.png)

Now I can use the console without any further problems.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
