### ISSUE TITLE
quickly toggle auto format on save

### ISSUE THREAD

**Issue by Swazimodo** [microsoft/vscode#88856]
Issue Type: <b>Feature Request</b>

Normally I love auto format on save. However, there is one repo that I work on with crazy linter rules. It is a little annoying to go to settings and toggle this on and off as I jump between projects on a daily basis. 

Is there a way to make a custom action hotkey for something like this? Then people could make there own settings toggles. Or could a UI toggle be added to the bottom bar beside the indent spaces which would allow auto format to be configured faster?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

**Comment by IllusionMH** [comment]
You can disable it using`.vscode/settings.json` only for that project.

**Comment by jrieken** [comment]
There is "Save with Formatting" and those settings files, but yeah what you ideally want is private-project setting that disables this. Assigning to @sandy081

**Comment by Swazimodo** [comment]
This is exactly what I needed in my life thank you!

**Comment by sandy081** [comment]
#40233  for local workspace settings.
