### ISSUE TITLE
html attribute format only works when saving file.

### ISSUE THREAD

**Issue by Spleeding1** [microsoft/vscode#88850]
- VSCode Version: 
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

- OS Version: macOS 10.15.2

Steps to Reproduce:

I was trying to get the HTML attribute wrapper to force-aligned, and it wasn't working. Then I turned on "Format on Save", and when I save the file it formats it, but not as I type. Don't know if this is normal.

I did all of the recommendations in [this post](https://github.com/Microsoft/vscode/issues/25554) before finding that it formats after saving the files. If there are other things you would like me try, let me know.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Save on format just invokes HTML on whole document. So what you see is strange.
Can you paste a html code snippet and you settings that let me reproduce the issue?

**Comment by Spleeding1** [comment]
Here is a snippet. I know I used bogus attributes, but it doesn't matter if they are real or not, it only wraps them on save, not paste or type (even though I'm pretty sure those settings are both on).

```html
<!DOCTYPE html>
<html>

    <head>
        <title>Test Page</title>
    </head>

    <body>
        <!-- this is formatted because I saved it before I pasted it -->
        <p class="myClass"
           data-parent="no-parent"
           data-attribute="for-snippet"
           >This is my test paragraph. <br>
            HTML › Format: Wrap Attributes<br>
            is currently set to force-aligned.<br>
            <a href="#"
               class="href"
               title="My link">Test Link</a>
        </p>
    </body>

</html>
```

**Comment by aeschli** [comment]
To reproduce, I set
```
	"html.format.wrapAttributes": "force-aligned",
	"editor.formatOnSave": true
```
When I use `Format` from the context menu it formats the file.
Undo and save formats the file the same way.

So this seems to work.

Do you expect format as you type, on enter?
The HTML formatter doesn't support that (it can only format a whole file)

**Comment by Spleeding1** [comment]
I thought it might format on enter, so that was my mistake. Thanks for checking it out and getting back to me. It is a nice extension.
