### ISSUE TITLE
debug requirements for TypeScript

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#88857]
from https://github.com/microsoft/vscode/issues/84044:

- finding an "evaluatable" expression for a given source location.
E.g. for any character position in the string "doc.foo[a+b].x > foo" return the "evaluatable" expression that should be shown in the hover.
- exact source maps for mapping source code ranges for frames and scopes. The JS debugger receives JS source ranges and they have to map correctly to TS ranges (and vice versa).
- bidirectional variable mapping.
The JS debugger only sees JS variable names and the debug extension needs to have a way of mapping JS names to TS names (and vice versa). Source maps provide a mechanism for that but the maps were not complete and aren't used in our debuggers I think.

**Comment by mjbvz** [comment]
Lower priority:

- Evaluate TS code in debug console (I hit this a lot for enums and imports)

**Comment by mjbvz** [comment]
Here's what VS uses for point 1: http://index/?rightProject=Microsoft.VisualStudio.LanguageServices.TypeScript&file=Debugging%5CTypeScriptLanguageDebugInfo.cs&line=205

**Comment by weinand** [comment]
@mjbvz Thanks a lot! I'm very interested in that information, but the link does not work for me.

**Comment by mjbvz** [comment]
You need to be on coronet for this. The specific call to the TS Server is:

```
   var result = await this.taskHandler.InvokeTSServerAsync(CommandNames.NameOrDottedNameSpan, document, TaskPriority.High, cancellationToken,
                         (proxy, endpoint, operationToken) => proxy.GetNameOrDottedNameSpan(endpoint, document, endPoint.Value.Position, operationToken));
```

We don't use this command currently

**Comment by connor4312** [comment]
Request for an InlineValueProvider: https://github.com/microsoft/vscode/issues/119489#issuecomment-807113895

**Comment by connor4312** [comment]
@hediet brought up the state of const enums. This can _partially_ be solved by sourcemap renames (which we will support some day, https://github.com/microsoft/vscode/issues/12066) but not very well. There's also been the request to transpile typescript in the REPL, which @eamodio asked for. Both of these would be solved if I could ask the TS server to transpile this bit of code as if it was written at a certain position/scope in a file, though that may be easier said than done.

**Comment by connor4312** [comment]
> bidirectional variable mapping.

THis is now done with the sourcemap "names", which are now pretty good following https://github.com/microsoft/vscode-js-debug/pull/1827

> exact source maps for mapping source code ranges for frames and scopes

Work is happening in that in https://github.com/tc39/source-map-rfc

> finding an "evaluatable" expression for a given source location

Covered by https://github.com/microsoft/vscode/issues/18058, merging
