### ISSUE TITLE
VS Code 1.41.1.0 crash by nvidia nview application after windows upgraded to 18363.592

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/vscode#88869]
My VS Code worked just fine yesterday, but after my windows upgraded to  1909 (OS Build 18363.592) today.
My VS Code can't be started, and it crash every time when open it.
In Windows logs, I saw error event like below, and after I uninstall nview, VS Code can be started. It must be related with windows upgrade because nview works fine with VS Code prior the windows upgrade.

Faulting application name: Code.exe, version: 1.41.1.0, time stamp: 0x5d709650
Faulting module name: nViewH64.dll, version: 6.14.10.14847, time stamp: 0x58524e98
Exception code: 0xc0000094
Fault offset: 0x0000000000098c31
Faulting process id: 0x1270
Faulting application start time: 0x01d5cd5d6b0454cf
Faulting application path: C:\Users\<>\AppData\Local\Programs\Microsoft VS Code\Code.exe
Faulting module path: C:\Program Files\NVIDIA Corporation\nview\nViewH64.dll
Report Id: 891ee741-5294-4c95-b493-c5372b80946d
Faulting package full name: 
Faulting package-relative application ID: 

EventData:
Code.exe 
   1.41.1.0 
   5d709650 
   nViewH64.dll 
   6.14.10.14847 
   58524e98 
   c0000094 
   0000000000098c31 
   1270 
   01d5cd5d6b0454cf 
   C:\Users\<>\AppData\Local\Programs\Microsoft VS Code\Code.exe 
   C:\Program Files\NVIDIA Corporation\nview\nViewH64.dll 
   891ee741-5294-4c95-b493-c5372b80946d

**Comment by gjsjohnmurray** [comment]
Maybe disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if the issue still persists.

**Comment by gjsjohnmurray** [comment]
Can you try the Insiders version?

Another resource is https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
