### ISSUE TITLE
Missing activity bar extensions

### ISSUE THREAD

**Issue by sleblang** [microsoft/vscode#88864]
Updated VSCode Insiders today to version 1.42 and noticed that all of my activity bar extension icons are missing. I had about 6-8 additional icons in the activity bar. Now I only have the default icons showing. Uninstalling and reinstalling the extensions doesn't fix the issue. Nor does closing the program and restarting it.

<img width="26" alt="Screen Shot 2020-01-17 at 9 43 42 AM" src="https://user-images.githubusercontent.com/2072042/72629621-ea827e00-390d-11ea-99ec-e28df3b508ce.png">

**Comment by el-zoltan** [comment]
Yeah, I'm also seeing this.

**Comment by mil1i** [comment]
Also on Windows Insider 1.42.0-insider, and extensions are no longer showing on the Activity Bar or via right-click.

However, if you open them via the Command Palette (eg; Kuberenetes: Focus on Cluster View) they will appear for that specific window and session only in the Activity Bar.

![image](https://user-images.githubusercontent.com/8459426/72631831-37685380-3912-11ea-982d-c4ea4302114b.png)

![image](https://user-images.githubusercontent.com/8459426/72631783-1c95df00-3912-11ea-8026-9d40504d27ea.png)
