### ISSUE TITLE
Remote badge in extension viewlet only respects remoteForeground when its focused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88863]
For these settings:

```json
"workbench.colorCustomizations": {
    "extensionBadge.remoteForeground": "#ff0000",
    "extensionBadge.remoteBackground": "#0000ff"
},
```

![image](https://user-images.githubusercontent.com/2193314/72629540-62987600-3905-11ea-9b66-c284f82a91b9.png)

It looks especially bad when you invert the color

![image](https://user-images.githubusercontent.com/2193314/72629635-8eb3f700-3905-11ea-8834-436bdd77a528.png)

**Comment by Tyriar** [comment]
It also doesn't apply in the webview

![image](https://user-images.githubusercontent.com/2193314/72629688-aab79880-3905-11ea-8008-80c2d6855f0d.png)

**Comment by sandy081** [comment]
Its an icon in the badge and hence the foreground is not applied.

@misolori Is it possible to theme its colour?

**Comment by rediffusion** [comment]
@Tyriar 

When do these icons appear? When you installed some extensions on the remote server? Or maybe in «VS Code» when you click on the extension icon "Remote Explorer":

![image](https://user-images.githubusercontent.com/30071027/74001988-a0297580-497e-11ea-81df-9a049251f7ed.png)

**Comment by Tyriar** [comment]
@rediffusion in the extension viewlet when you install remote extensions.

**Comment by Tyriar** [comment]
Not fixed yet

**Comment by misolori** [comment]
Verification steps:

1. Use the same steps in the original issue
2. Verify that the overrides work in both narrow and large sidebar views, and in the extension detail page
