### ISSUE TITLE
Left clicking an extension in the extension viewlet a section time changes the focus color

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88860]
Left click once:

![image](https://user-images.githubusercontent.com/2193314/72629139-91fab300-3904-11ea-81e1-fdbb96b38094.png)

Left click 2+ times:

![image](https://user-images.githubusercontent.com/2193314/72629156-99ba5780-3904-11ea-9aaa-7ea4b96cd14a.png)

**Comment by sandy081** [comment]
Not sure what is the broken behaviour here.

**Comment by Tyriar** [comment]
Left clicking an item on the extension viewlet appears to "unselect" it as the color changes. left clicking the item twice should have it remain blue.

**Comment by Tyriar** [comment]
@isidorn @sandy081 this isn't a feature, it's a bug. It seems like the keyboard action of selecting is getting mixed up with what the mouse is meant to do as clicking it a second time focuses the extension editor. The explorer, search and scm all have lists like this and do not do this.

**Comment by sandy081** [comment]
This will gets fixed along with #91603
