### ISSUE TITLE
[AzureFunctions]Replace dashes in app settings with underscores

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/vscode#88875]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add any trigger that needs a connection string
2. Pick a app setting with dashes in the name
3. Publish to Azure
4. Go deployed Azure function and try to create an AppSetting.

 AppSettings do not allow dashes. Dashes need to be replaced with underscore

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/causedByExtension

You should report this issue in extension repo https://github.com/Microsoft/vscode-azurefunctions
