### ISSUE TITLE
Typescript not showing red underlines

### ISSUE THREAD

**Issue by taylorosbourne** [microsoft/vscode#88871]
Issue Type: <b>Bug</b>

Typescript files are not producing the red underline that they should when something is incorrect.  There doesn't appear to be a way to reproduce because it seems to only affect my  work machine (MacBook Pro (15-inch, 2018)).  My tsconfig is set up in the exact same way as I would  use it on my personal machine (that does not show this issue).  My settings.json is identical  and vscode is up to date on both of these machines.  Is there a reason why vscode would not show its helpful underlines?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.12.9
vscode-typescript-next|ms-|3.8.20200116
material-icon-theme|PKi|3.9.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does other functionality, such as suggestions, work in those files?

**Comment by taylorosbourne** [comment]
It does not.  No intellisense.  Not only in ts files, but in any file.

**Comment by mjbvz** [comment]
Have you disabled the builtin Javascript/TypeScript extension? Search `@builtin typescript` in the extensions view to check this. Make sure the `TypeScript and JavaScript Language Features` extension is enabled

**Comment by taylorosbourne** [comment]
By George you've done it!  It was disabled, but I don't remember doing so...  however, everything is good now!  Thank you very much for fixing this simple problem.

**Comment by mjbvz** [comment]
Glad that worked!

@sandy081 I see a one or two issue a month like this one where the built-in JS/TS extension is disabled but users do not remember explicitly disabling it. Are you tracking any issues related to this?
