### ISSUE TITLE
Expose monaco-editor instance on vscode.TextEditor

### ISSUE THREAD

**Issue by shaman-apprentice** [microsoft/vscode#88879]
I would like to access the monaco-editor instance on a `vscode.TextEditor` directly. For example to insert [ViewZones](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.iviewzone.html) (see #88483 for detailed motivation).

This would make #85682 obsolete. In general I assume a better experience for developing extensions with direct monaco-editor access, as it removes an abstraction layer, which must be learnt, maintained (and waited for to be created in the first place if it doesn't already exist).

**Comment by jrieken** [comment]
There is the renderer and the extension host process. The first is for the UX, the second is a dedicated process in which extensions run. There is no way to expose the Monaco-editor API in the latter because of this
