### ISSUE TITLE
Contanstly freezing

### ISSUE THREAD

**Issue by tehtertot** [microsoft/vscode#88870]
I am using the Azure extension and am running locally (F5) over and over (quitting in between with Shift+F5). After a couple of runs, it will freeze--sometimes while typing, sometimes right after quitting a run. My functions are pretty simple--just working with ServiceBusTrigger and CosmosDB as trigger/input binding.

**Comment by weinand** [comment]
What Azure extension are you using?

**Comment by tehtertot** [comment]
I am using Azure Functions (ms-azuretools.vscode-azurefunctions)

**Comment by weinand** [comment]
What debugger/language are you using? Node.js?
