### ISSUE TITLE
Installing Extensions not working

### ISSUE THREAD

**Issue by snraets** [Microsoft/vscode#8887]
- VSCode Version: 1.3
- OS Version: Ubuntu 16.4

Steps to Reproduce:

1. Open Extensions from the left
2. On any extension click "Install"

The install does not work.  In the debugger, I noticed there is an error.

shell.ts:416Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)

**Comment by aliukevicius** [comment]
Same here.  Also if you try to install extension the old way 'ext install js-atom-grammar' what you get is extension sidebar opened and search for 'js-atom-grammar' initiated

- OS Version: Ubuntu 14.04 

VS Code Info

- Version 1.3.0
- Commit e724f269ded347b49fcf1657fc576399354e6703
- Date 2016-07-07T16:50:12.291Z
- Shell 0.37.6
- Renderer 49.0.2623.75
- Node 5.10.0

**Comment by KnisterPeter** [comment]
Also for Debian Testing.

**Comment by joaomoreno** [comment]
#8859

**Comment by snraets** [comment]
Thanks for the really fast update.

**Comment by snraets** [comment]
By the way.  VS Code is awesome.

**Comment by javierquevedo** [comment]
Same issue here in version 1.4.0 on Windows 7.
TypeError: Cannot read property 'firstPage' of undefined ....
