### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY 

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode#88887]
re: https://github.com/microsoft/vscode-mssql/issues/1563

According to the closing note: 

> That's an issue you can open against vscode. The extension installation belongs to them, but if you see any issues with the extension itself, feel free to open an issue.

 [ERROR] Error: Request error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

Note: I am behind a corp fw. FWIW I tried the suggestion here: [Network Connections in Visual Studio Code](https://code.visualstudio.com/docs/setup/network)

where it says, in part:

> If all else fails, you can tell VS Code to ignore all certificate errors using the --ignore-certificate-errors command-line flag. Warning: This is dangerous and not recommended, since it opens the door to security issues.

However, that is an invalid flag :

```
code --ignore-certificate-errors
Option 'ignore-certificate-errors' is unknown. Ignoring.
Version: 1.41.1 (system setup)
Commit: 26076a4
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

VS Code version: Code 1.41.1 (26076a4, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

System Info
Item Value
CPUs Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)
GPU Status 2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: enabled
rasterization: enabled
skia_renderer: disabled_off
surface_control: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off
webgl: enabled
webgl2: enabled
Load (avg) undefined
Memory (System) 15.88GB (2.82GB free)
Process Argv
Screen Reader no
VM 0%
Extensions (9)
Extension Author (truncated) Version
githistory don 0.4.13
gitlens eam 10.2.0
code-runner for 0.9.15
gc-excelviewer Gra 2.1.32
mssql ms- 1.8.0
python ms- 2020.1.57204
powershell ms- 2019.12.0
partial-diff ryu 1.4.0
vscode-hexdump sle 1.7.2

**Comment by gbritton1** [comment]
Yes, it is related to that issue. But that issue was specific to a
particular extension. This new issue is in general to extension
installation across the board and to errors in the documentation for
suggested remedies.

**Comment by chrmarti** [comment]
Just to check your setup: Can you download the extension using Chrome? (From: https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)

@aeschli Should we allow-list `--ignore-certificate-errors`?

**Comment by gbritton1** [comment]
Sure I can do that.  I can download anything from there. However this post
is not about that extension in particular. It's about all extensions.
There's seems to be something quirky in the extension installer. I know of
at least two extensions that caused this error upon installation. I suppose
there probably are more.

Note that the question about the flag is not whether the flag should be
allowed or not, because the flag itself is invalid. It's not accepted by
the executable. to me that means that, at least, the documentation needs to
be updated.

**Comment by aeschli** [comment]
Added ignore-certificate-error & allow-insecure-localhost to the list of known options and improved the error message. Unknown settings are actually not ignored but still passed to Electron/Chromium.
https://github.com/microsoft/vscode/commit/bc8aaad1787e8c7160225de85bd8661f7445e71e

@gbritton1 Can you verify if using `--ignore-certificate-errors` makes a difference in your case (as said, just ignore the unknown option warning)

**Comment by gbritton1** [comment]
I have the same problem when I use that option.

**Comment by chrmarti** [comment]
@gbritton1 Do you have system certificates enabled?
![image](https://user-images.githubusercontent.com/9205389/73062050-c4c02080-3e9b-11ea-94de-b797c76e50de.png)

**Comment by gbritton1** [comment]
I believe that system certificates are enabled, however my laptop is locked
down by your system administrator so I don't have access to change it
either way.

**Comment by gbritton1** [comment]
Just confirmed system certificates are enabled

**Comment by chrmarti** [comment]
@gbritton1  Can you download https://download.microsoft.com/download/e/7/8/e781cf8f-9c3f-4ad5-bd0c-f3c62b8bc6bd/microsoft.sqltools.servicelayer-win-x64-netcoreapp2.2.zip using Chrome? (Just now saw that in your original report.)

**Comment by gbritton1** [comment]
Yup I can download it.

**Comment by chrmarti** [comment]
@abist Is this from a download you run in a separate Node process? We add system certificates to VS Code's extension host process, but we cannot pass these to any subprocesses.
