### ISSUE TITLE
'Split Editor' should move the active tab rather than duplicate it

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#8888]
- VSCode Version: 1.3.0
- OS Version: Xenial

Steps to Reproduce:

1. Open 2 code windows, there should be 2 tabs
2. Click the 'split editor' button.
3. Notice the new editor pane has a second instance of the active tab.

I find this annoying. I would prefer behaviour that _moved_ the active tab into the new split, revealing the next-most-recently-used tab in its place.

Preferred workflow goes:
- Editing a file
- Open another file to edit, desire to edit the 2 'top' files side-by-side
- Click 'split'; now the top 2 files are both visible, can edit side-by-side with just one click.

I can't think of a time when I have ever wanted the existing behaviour of duplicating the top tab. It just forces me to follow up the split action with another action to closing the tab in the original split.

**Comment by danvk** [comment]
There are times when I want to duplicate the open tab. Two examples that come to mind:

- I'm editing a Markdown file and want the new split to show a preview.
- I'm editing a large file and want to refer to one method while editing another.

**Comment by TurkeyMan** [comment]
> I'm editing a Markdown file and want the new split to show a preview.

I'd imagine preview to be a slightly different action no?

> I'm editing a large file and want to refer to one method while editing another.

I think that's a job for a different kind of split, VS implements a within-one-tab splitter thing, and I always find that more convenient to use when wanting to do what you say.

**Comment by bpasero** [comment]
I am closing this because I find it very unintuitive that the split action changes its behaviour like that. Also, the icon clearly indicates that you got from one editor to two. As for being able to move a tab left or right, I suggest to continue in https://github.com/Microsoft/vscode/issues/8234

**Comment by bpasero** [comment]
Pushed https://github.com/Microsoft/vscode/issues/8185 for July.

**Comment by jrenton** [comment]
I have also found this to be annoying. I have been using vs code for over a year and have never found myself in a situation where I want to duplicate the currently opened document. It would be nice if there were 2 commands: "Duplicate current document in new editor window" and "Open current document in new editor window."

**Comment by undless** [comment]
Totally agree with @TurkeyMan 
Also, when you close the last tab the column disapear so you have to open a new file and split the editor again and delete the first file. small things yes but i dont feel it as intuitive.
This is a "split editor action" not a "duplicate action" for me....

And if the columns could stay even if there is nothing, it could be great. This is the way Sublim Text is managing spliting and i really love it.

Nice work btw for all the rest
Cheers

**Comment by ProLoser** [comment]
Don't agree with closing this, at least make a setting to make this behavior controllable.

**Comment by mrchief** [comment]
> I find it very unintuitive that the split (get the name?) 

Well, Split Editor is supposed th split the _editor_, not the _file_, right? :smile: 

This is why its unintuitive right now. Its splitting/duplicating the file, not the editor.

At least #8185 provides a way out. So thanks for that! Although its gonna take while to get used to it (and remember not to click 'Split Editer'). Its not end of world, we'll live! :smile: VSCode continues to rock!
