### ISSUE TITLE
Cannot add any extension

### ISSUE THREAD

**Issue by djskim27** [microsoft/vscode#88883]
Issue Type: <b>Bug</b>

I am not able to add any extensions via Visual Studio Code. I tried changing my DNS settings as advised in similar issue tickets but it still not working for me.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|-psn_0_1024250|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
I suggest you follow the steps @sandy081 posted at https://github.com/microsoft/vscode/issues/88754#issuecomment-575642566

**Comment by djskim27** [comment]
It actually ended up being a permission issue! Thanks for the help :)
