### ISSUE TITLE
Text is blurry

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#88898]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.18363

Linking #88876, #61940, #15211, #61940, #13527 here.

The text suddenly became extremly blurry. VSCode worked nicely for some time now, but today it started acting weird.
Can be forced by going into Zen Mode.
If you klick somewhere, it gets better again – like in #13527. (but not as good as with gpu acc. disabled).

Note that the icons are blurried as well, so this might be an Electron thing (?).

What weirds me out, is the fact it just started today out of nothing. Last days everything was crisp.

![blurry](https://user-images.githubusercontent.com/2277182/72663902-ecc10700-39f7-11ea-8d14-061cc84677a3.png)

**Comment by gjsjohnmurray** [comment]
Did you recently get a Windows update? Your update history might reveal that.

**Comment by runxel** [comment]
Thanks for your answer, @gjsjohnmurray.

Yes, I got [kb4532938](https://support.microsoft.com/en-us/help/4532938/kb4532938-cumulative-update-for-net-framework), and [kb4528760](https://support.microsoft.com/en-us/help/4528760/windows-10-update-kb4528760) both on Jan. 14.

**Comment by alexdima** [comment]
@runxel Does this reproduce with every font family? Did you try a good old OS restart? Does this reproduce on VS Code Insiders (uses Electron 7)?

**Comment by runxel** [comment]
Okay, so a small update here:
Interestingly the Windows start menu had all the same problems, it was smudgy and unreadable. So it seems this is not related to Electron at all.
Sadly (or gladly?!) the error was gone after a few days and I can't reproduce this any longer...
Really weird – let's just hope that was the single appearance of this.
Otherwise I will reopen this issue.
