### ISSUE TITLE
my project is dead

### ISSUE THREAD

**Issue by ivanred** [microsoft/vscode#88899]
Hello,team of VS Code.I love your app,it is great.However,i`m shocked.Yesterday i was on a final stage of my project,and VS Code programme warned me that my vs code needs update.I confirmed it.On the next day(today),i am opening VS to finish my project and...my folder where was my project is deleted.So,i must rewrite it and waste my time :( :/ .I am really sad and shocked.Please,fix this.
My e-mail address if you will need my help-ivanredchyts69@gmail.com

**Comment by gjsjohnmurray** [comment]
What platform? What version were you running before the update? Is this the first time you have updated VS Code since you started your project? Did you put your project into source control?

What folder was your project stored in? Maybe #76567 is relevant.
