### ISSUE TITLE
Save Code for future use (ClipBoard)

### ISSUE THREAD

**Issue by praveenyen** [microsoft/vscode#88892]
Whenever I copy a code snippet, that should store in a separate memory. So, I can use it whenever I want to use it.
This saves the problem of saving in a new file for simple codes.

I hope, you will implement this feature.

**Comment by IllusionMH** [comment]
You can use system Clipboard history for short lived content or https://marketplace.visualstudio.com/items?itemName=markvincze.code-fragments to permanent storage
