### ISSUE TITLE
add file bonus in editor.suggest

### ISSUE THREAD

**Issue by zhyiyu** [microsoft/vscode#88891]
Setting `"editor.suggest.localityBonus": true` will rank the suggestions closer to cursor point higher, according to the [intellisense documentation](https://code.visualstudio.com/docs/editor/intellisense).

In addition to this, I suggest there could be a file bonus which ranks all the suggestions from this current file higher.

Issue [64489](https://github.com/microsoft/vscode/issues/64489) might be related.

**Comment by jrieken** [comment]
Locality bonus kind of does that as symbols that cannot be found in the current file don't get a bonus. However,
