### ISSUE TITLE
The editor have breakdown

### ISSUE THREAD

**Issue by TWOWhite** [Microsoft/vscode#8889]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.open a html file in the editor ,and the extension html css class completion is loading,then there is no
response and i can not edit the file and can not click anything

**Comment by Spown** [comment]
so maybe you should file a bugreport to ![HTML-CSS-Class-Completion](https://github.com/Zignd/HTML-CSS-Class-Completion/issues)?

**Comment by joaomoreno** [comment]
Zignd/HTML-CSS-Class-Completion#18
