### ISSUE TITLE
`enableForWorkspaceTypeScriptVersions` not working as the description.

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#88894]
- VSCode Version: [master](https://github.com/microsoft/vscode/blob/8d0777697e03a05bef85d22a8a6d0e021d5e6690/extensions/typescript-language-features/src/utils/plugins.ts)
- OS Version: all

https://github.com/microsoft/vscode/issues/88642

I don't find any document of it.
But the description in json [scheme](https://github.com/microsoft/vscode/blob/eeee6244d9b2277126b8c758df9f9fe4eb30e1bc/extensions/typescript-language-features/schemas/package.schema.json) is ""Should the plugin be loaded when using workspace versions of TypeScript?""
Actually, the plugin will always be trying to load. But when it is false, the `pluginProbeLocations` will not be set, this make the plugin to be loaded failed.

https://github.com/microsoft/vscode/blob/e7b44e70e94170e2b893458891d041dde36217fa/extensions/typescript-language-features/src/tsServer/spawner.ts#L142-L151

I guess in above code, the line 143 should be adjusted and placed in the `if`.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
This is how the feature was designed: 

- If you are using VS Code's TS, always try using the plugin
- If you are using a workspace version of TS, then try loading the plugins from the workspace automatically. However do not load it from the global plugin location. This was done as the safest default behavior (we assume that the plugin version installed in the workspace will work with the TS version installed there)
- Unless the plugin sets `enableForWorkspaceTypeScriptVersions`
