### ISSUE TITLE
vscode.Uri constructor takes no arguments

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#889]
I'm trying to create a new file programmatically using [openTextDocument](https://code.visualstudio.com/docs/extensionAPI/vscode-api#openTextDocument), but I'm having trouble providing it the proper URI. The documentation states that 2 schemes are supported (file and untitled). I'm trying to create a URI with `untitled` as its `scheme`, but the `Uri` constructor doesn't take any parameters and creating an empty URI and then assigning values to its properties individually doesn't do anything. 

Do you have any examples of this? It may be a personal problem, but I think it's a bug with `Uri`.

**Comment by jrieken** [comment]
@martellaj Yes and no. Today we ask people to use `Uri.parse` or `Uri.file`. The latter is for the file-scheme only, the former for the rest.

**Comment by jrieken** [comment]
Closing and assuming having the two static methods are OK

**Comment by martellaj** [comment]
Yes, thanks for the quick response!

**Comment by jrieken** [comment]
np
