### ISSUE TITLE
Unable to 'Go to definition' for javascript file with '.es6' file extension

### ISSUE THREAD

**Issue by mkloouo** [microsoft/vscode#88905]
- VSCode Version: 1.41.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Create new folder
2. Create file index.js with
```javascript
import first from './first';
import second from './second';
```
3. Create file first.js with
```javascript
export default 1;
```
4. Create file second.es6 with
```javascript
export default 2;
```
5. In file index.js hover over './first'; part with Ctrl button pressed -> you should see intellisence or whatever proposing you to click and follow the path
6. In file index.js hover over './second'; part with Ctrl button pressed -> nothing happens.
7. Selected ./second and press F12 -> nothing happens.

Does this issue occur when all extensions are disabled?: Yes

How do I make vscode index this type of file?

I have already added '.es6' extension to be parsed as javascript.
What else?

**Comment by mjbvz** [comment]
This IntelliSense feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) for es6 file support
