### ISSUE TITLE
IPv6 links are not clickable

### ISSUE THREAD

**Issue by oberbeck** [microsoft/vscode#88901]
- VSCode Version:
```
Version: 1.42.0-insider
Commit: fd13e449f5f2fe300f187129d6065ed1cfad74d3
Date: 2020-01-17T16:30:38.851Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```
and
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```
- OS Version:
```
macOS Mojave 10.14.6 (18G103)
```

Steps to Reproduce:

1. Open New External Terminal
2. type and execute 
`echo http://localhost:4200 && echo http://\[::ffff:7f00:1\]:4200`
3. While `http://localhost:4200` is clickable, `http://[::ffff:7f00:1]:4200` is not.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/20164654/72664787-63630200-3a02-11ea-82d7-0407e1e0920a.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by oberbeck** [comment]
#21125

**Comment by oberbeck** [comment]
https://github.com/microsoft/vscode/blob/a234f13c45b40a0929777cb440ee011b7549eed2/src/vs/editor/common/modes/linkComputer.ts#L284

**Comment by alexdima** [comment]
The editor link detector can find and open `http://[::ffff:7f00:1]:4200`.

**Comment by oberbeck** [comment]
> The editor link detector can find and open `http://[::ffff:7f00:1]:4200`.

True, it works in the editor for me as well but not in the terminal.

**Comment by Tyriar** [comment]
Additionally you say "Open New External Terminal", this is an external application and has nothing to do with VS Code.
