### ISSUE TITLE
NPM Scripts: wrong drive letter casing on Windows

### ISSUE THREAD

**Issue by danbaechtold** [microsoft/vscode#88906]
Issue Type: <b>Bug</b>

On Windows, in a Vue.js project:
Start "npm run serve" from the built in "NPM Scripts" view. Output:

> Executing task: npm run serve <
> my-app@1.0.0 serve c:\Users\dan\...
> vue-cli-service serve
> INFO  Starting development server...

The problem is the lowercase "c:\", which in my project will lead to these warnings:
> There are multiple modules with names that only differ in casing.."

Typing "npm run serve" in the built in terminal works fine, so it must be a bug within the "NPM Scripts" view.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment]
I haven't been able to get the lowercase drive letter to happen. My steps to try to repro:
- Create a vue project using `vue create hello-vue`
- Open in VS Code
- From npm scripts explorer, run `serve`

I always see an uppercase `C` as my drive letter. If you try with the same steps as me, what happens with the drive letter?

> my-app@1.0.0 serve c:\Users\dan...
I don't get this line and I am unfamiliar with vue. How can I make it show?

Can you share:
- Your tasks.json
- Your settings.json

**Comment by danbaechtold** [comment]
Thanks for looking into it. I still had the issue, but then I checked with
my colleague, and on his PC it works just fine.

As you asked me about settings.json, I played around with them and found
out that it is indeed one of my settings causing this issue! It's this one:
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",

As soon as I remove that entry, it works.

I prefer the CMD over Powershell, however, so it would be great if it works
with this shell, too..



Am Mo., 3. Feb. 2020 um 11:56 Uhr schrieb Alex Ross <
notifications@github.com>:

**Comment by alexr00** [comment]
@Tyriar this might be something in terminal that can be changed.
I can reproduce this issue on Windows by setting `"terminal.integrated.shell.windows": "cmd.exe"`
and running this trivial task:
```jsonc
        {
            "type": "shell",
            "command":"echo C%cd%", // extra 'C' is to make it easy to see that the next 'c' is lowercase
            "label": "echo cwd"
        }
```
In the task system, we use the a string path with the correct uppercase 'C' to create a URI. That URI has uppercase C in the path, but lowercase c in the fsPath. Powershell seems to handle fixing the casing, but cmd does not.

**Comment by alexr00** [comment]
Discussed and it turns out that if you're going to be handing an fsPath to an external tool you probably want the _original_ fs path. PR for the terminal incoming.
