### ISSUE TITLE
tsx style error

### ISSUE THREAD

**Issue by AMMing** [Microsoft/vscode#8890]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. tsx file
2. class or interface add property
3. `list: Array<string>;`
4. code style error

**Comment by joaomoreno** [comment]
#8045
