### ISSUE TITLE
Windows Installation: Improper Filepath Assignment

### ISSUE THREAD

**Issue by Armagon3650** [microsoft/vscode#88900]
We have writte
Issue Type: <b>Bug</b>

I d/l Visual Studio 1.41 a couple of days ago for Windows 10. I told the install Wizard to install Visual Studio to a specific folder I created for it, instead of its default filepath. After spending several hours trying to install my 1st Ext, and unable to find it. I discovered the files and folders of Visual Studio were scattered about and not all where I told them to go during installation. The program does work, but from the tutorials, I think some things are failing (not working how they should), because the program files are scattered. I've discovered at least 3 different filepath locations containing Visual Studio's data and added it up to 304.4 MB of data(actual size not size on disk). The uninstaller won't remove the program in its entirety (same reason I'm guesing), So I'd like feedback to know how large Visual Studio 1.41 is supposed to be, so I can remove it safely. Great Project! Thx for all the work put into it.
Note: from the photo, you can see the 3 separate filepaths I found the data in.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.72GB free)|
![Screenshot (17)](https://user-images.githubusercontent.com/46560814/72664238-3be34980-39b0-11ea-899c-978103d79a3c.png)

|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
n the needed data into your clipboard because it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
You might've missed the attached screenshot, do you mind sending it?

**Comment by Armagon3650** [comment]
Its in the lower half. But I certainly don't mind resending it. Thx for responding.
![Screenshot (17)](https://user-images.githubusercontent.com/46560814/72795218-15acec00-3bf2-11ea-89d5-ebaa4057f760.png)

**Comment by joaomoreno** [comment]
OK. The two windows on the right are coming from us. Not sure where the location of the window on the left comes from. Can you delete them all and reinstall VS Code?

**Comment by Armagon3650** [comment]
Yea but I was hoping for confirmation as to VS Code 1.41's size to be sure I remove it all, to guarantee a clean install. Does 304.4 MB sound about right? 
 Also, the window on the left is the folder I made to install VS Code into. Will it be ok to move it to that location after installing? I don't wanna have issues with extensions not able to find where to d/l.

**Comment by Armagon3650** [comment]
I d/l it as a .zip another computer and got 334 MB. But I ran searches and can't find anything so I'll just delete it and try a new d/l later. Worked fine when I did it from the zip.

**Comment by Armagon3650** [comment]
Ok so I downloaded it on 2 computers. Apparently it creates folders in C:\Users\[Username] ( i guess this is where extensions go), and C:\Users\[Username]\AppData\Roaming\[Code]. It automatically creates these folders every time you open VSCode if they don't already exist.. This could pose problems as the uninstaller doesn't include these locations (I don't think). 
     Anyway, it doesn't have anything to do with the installation.
     For all I know this is natural behavior Idk why it creates this .vscode folder randomly off by itself though: see photo.
![Screenshot (1)](https://user-images.githubusercontent.com/46560814/72890382-9806e000-3cc6-11ea-8ef6-0c92b6bb505b.png)

**Comment by joaomoreno** [comment]
> Does 304.4 MB sound about right?

Yes that's roughly the size!

>  Will it be ok to move it to that location after installing?

No, make sure you install it on the location you desire right from the start.

> It automatically creates these folders every time you open VSCode if they don't already exist.. This could pose problems as the uninstaller doesn't include these locations (I don't think).

The uninstaller won't remove the user data dir and extensions dir since users might want to reinstall and keep their settings.

Closing this issue.
