### ISSUE TITLE
snippets语法新增获取当前当前文档的目录名，但是不要获取任何路径

### ISSUE THREAD

**Issue by Candane** [microsoft/vscode#88908]
TM_DIRECTORY：获取当前文档所在目录，但是包含了路径，有时候我只想要目录名字而不要包含路径，希望能有

**Comment by roblourens** [comment]
Google translate is not quite helping here, please file issues in English.

**Comment by Candane** [comment]
Sometimes I want to get the directory name of the current working directory, but I find that there is no such snippets syntax

**Comment by roblourens** [comment]
Maybe `WORKSPACE_NAME` is what you want?

**Comment by Candane** [comment]
No, he includes all the paths, but I only need the last one.

**Comment by Candane** [comment]
I want to get the last name of TM_DIRECTORY

**Comment by roblourens** [comment]
Sorry I don't understand what you mean. Please give an example.

**Comment by Candane** [comment]
My problemPath : D://vueProblem/mall/detail/DetailGoods.vue
WORKSPACE_NAME is vueproblem，TM_DIRECTORY is D://vueProblem/mall/detail，but I only want to get "detail"

**Comment by roblourens** [comment]
Ok, so you want the directory name of the current file (not the folder open in vscode)

**Comment by Candane** [comment]
yes,Thank you for your understanding，Sometimes I want to use it in my code snippets
