### ISSUE TITLE
Unknown Configuration Setting

### ISSUE THREAD

**Issue by AlsoScratch** [microsoft/vscode#88914]
- VSCode Version: 1.41.1
- OS Version: macOS 10.15.2

When I hover over `css.colorDecorators.enable`, `scss.colorDecorators.enable` or `less.colorDecorators.enable` in the `settings.json` file, I get this:
<img width="296" alt="Screenshot 2020-01-19 at 10 14 11 AM" src="https://user-images.githubusercontent.com/48752273/72673400-e9d02000-3aa4-11ea-885b-1c2d968a6a90.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
They were merged into one editor setting.

```js
"editor.colorDecorators": false,
```

Scope by language:

```js
"[css]": {
	"editor.colorDecorators": false,
},
```
