### ISSUE TITLE
[Request] Keep 'Save All' and 'Close All Editors' buttons available when 'OPEN EDITORS' view is collapsed

### ISSUE THREAD

**Issue by yortus** [Microsoft/vscode#8891]
I've just updated to v1.3 (thanks! it's fantastic). Now with tabs, I've been collapsing the 'OPEN EDITORS' view on the left sidebar to make more room for the folder tree, since the tabs list the open files anyway.

But when the 'OPEN EDITORS' panel is collapsed, the 'Save All' or 'Close All Editors' buttons become unavailable, which is inconvenient as I use those a lot.

Is it possible to keep these two buttons available on the 'OPEN EDITORS' view's header, even when it is collapsed? The space is still there, and the commands are still useful even without the view expanded.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
