### ISSUE TITLE
Peek Problem text goes out of bounts / doesn't wrap

### ISSUE THREAD

**Issue by StevieJayCee** [microsoft/vscode#88919]
Peek Problem messages don't seem to be wrapping for me or displaying a scroll bar. I don't know what the expected behaviour is meant to be.

It looks like it's the same issue in:
https://github.com/microsoft/vscode/issues/77941

Except, the error message doesn't resize whenever I resize VSCode; it just keeps cutting off more of the message:
![image](https://user-images.githubusercontent.com/4976889/72674259-7f869380-3a42-11ea-8864-ca7c39817b44.png)

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.10-arch1-1

Steps to Reproduce:

1. Open Peek problem dialog that extends across the screen.
2. Open a left side bar widget (CTRL + B)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
I suggest you first update to the current release, 1.41.1. Do you still have the problem?

**Comment by StevieJayCee** [comment]
This occurs on the latest as well.

**Comment by jrieken** [comment]
@StevieJayCee When you hover over the message then a scrollbar should appear. Don't you see that?

**Comment by sandy081** [comment]
>  it gets cut off when you click on Peek Problem

What gets cut off?
