### ISSUE TITLE
SSH 

### ISSUE THREAD

**Issue by leemojiang** [microsoft/vscode#88928]
- VSCode Version: 1.41.1
- OS Version: local (Darwin x64 18.7.0 and WIN10) remote(ubuntu)
- Extensions  : Remote-ssh
Steps to Reproduce:

1.  Connect to the remote using ssh .ter
2. Then delete the .vscode and .vscode-server folder in the remote computer.
3. The ssh will never work again in vscode while ssh is still ok.

Does this issue occur when all extensions are disabled?: Yes/No

No because without remote-ssh there aren't ssh to use.

**Comment by roblourens** [comment]
I believe this was already fixed in https://github.com/microsoft/vscode-remote-release/issues/649. You can try it out with the Nightly version of the Remote-SSH extension and let me know.
