### ISSUE TITLE
Help popup font size: title ok but content too big

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#88929]
@octref I'm deliberately "reopening" issue https://github.com/microsoft/vscode/issues/80724 here because I've new input that seems relevant to our disagreement there, but sadly the other issue was locked.

The new input is related to https://github.com/microsoft/vscode/issues/88916 and https://github.com/microsoft/vscode-python/issues/9667. It seems relevant to me because it's pointing to the fact that the size of the content of the help popup (but not its title) is coupled to the size of a font of a very different nature (a monospace font belonging to a different family) which *a fortiori* supports:

>  yet you can see that everything in the GUI (without taking into account the editor and terminal fonts, which are independently controlled) is smaller than the contents of the help popup

If things are how this evidence suggest, I really don't get the rationale behind the decision to fetch the size of a non monospaced font, which is the same one used for the rest of the GUI, from the size of a font of another family, knowing how unreliable this could be. Wouldn't it be better to use some scale of the base font size since this font is of the same family and the user has already accepted it for the rest of the GUI? Or to measure the actual bounding box of some reference text rendered using one font and make the other one occupy the same area?

You answer there:

> This is already very small font size. Currently we don't allow you to customize that font yet. You can track #519.

doesn't seem to be pertinent at the light of my comments above: the size is indeed not taken to be the size of the non-configurable workbench font and I don't see why you will revise that decision once #519 was hopefully implemented, since you already decided to relate the doc font size to another setting (probably to make it consistent with the popup title, I don't know, but, at any rate, that's not happening in this case).  

Platform:

* VSCode Version: 1.41.1
* OS Version: Ubuntu 19.04
* Screen: 3000x2000 hidpi 2x scaling factor.

Steps to Reproduce:

1. Set Ubuntu Font as the editor font (but other fonts will do it, for example Inconsolata).
2. At the default size of 14px this font is a bit small, so set it to a more reasonable size, say 16px or 17 px.
3.Now type some code, say `import argparse`, and open the doc popup window for `argparse`.

**Comment by octref** [comment]
I tried it, setting one to 14px and the other to 17px. If a user chooses 17px font, maybe he/she cannot read smaller text comfortably. Also then the widget is not consistent.
