### ISSUE TITLE
provider UI for launch.json and task.json

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#88925]
The current configuration of launch.json and tasks.json are too complicated

It is difficult for ordinary people to configure a usable task.

And others does n't understand these complicated configuration files

Hope that vscode can also provide UI

Convenient for developers to configure and read more easily

**Comment by idoprz** [comment]
To provide good UI, the UI will need to provide callbacks to the task provider extension to provide the configuration options. For example, in the npm task type, I will want to see the available scripts in the package.json
