### ISSUE TITLE
Integrated Terminal  can not display and input Chinese word

### ISSUE THREAD

**Issue by wzyplus** [Microsoft/vscode#8892]
- VSCode Version: 1.3.0
- OS Version: OS X EI Capitan 10.11.5
### Can not display

Steps to Reproduce:
1. Create a directory or file with Chinese word.
2. Open terminal in vscode and execute `ls` command.

ITerm2

![4bb9ab49-afe3-4049-8b62-d1b71dc5e1d7](https://cloud.githubusercontent.com/assets/3762193/16677721/281d1aae-450b-11e6-8e31-709a1f159f51.png)

VSCode Terminal

![a1c91861-360e-44b6-8025-11b9ed184ae9](https://cloud.githubusercontent.com/assets/3762193/16677694/ecd915ba-450a-11e6-98da-6b8c4d19ebe7.png)
### Can not input

Steps to Reproduce:
1. Open ternimal in vscode.
2. Input some Chinese word with system default Chinese IME.

![1d1777d1-e0c9-4b5d-acd3-463dc1fdad8f](https://cloud.githubusercontent.com/assets/3762193/16677789/d5192518-450b-11e6-8d04-c8961d451fce.png)

**Comment by ZCShou** [comment]
Can Display but can not input on Windows 10!

**Comment by Tyriar** [comment]
@wzyplus this is related to the font, do you have a custom font set for the terminal? The editor's font should be the fallback which is expected to work.

@ZCShou see #7045

**Comment by ZCShou** [comment]
@Tyriar font set for the terminal is default,but IME is not

**Comment by wzyplus** [comment]
@Tyriar No, I didn't change the font of the terminal. But changed the editor's font to `Consolas`.

**Comment by Tyriar** [comment]
@wzyplus Does the problem go away if you use the default `editor.fontFamily` fallbacks?

```json
"editor.fontFamily": "Consolas, 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'"
```

**Comment by wzyplus** [comment]
@Tyriar No, it doesn't work.

![image](https://cloud.githubusercontent.com/assets/3762193/16756138/ac22c7cc-4835-11e6-86bf-371790de8292.png)

**Comment by Tyriar** [comment]
@wzyplus can you setup [xterm.js](https://github.com/sourcelair/xterm.js) and see if you can reproduce it in the demo?

```bash
git clone https://github.com/sourcelair/xterm.js.git
cd xterm.js
npm install
npm start
# navigate to http://0.0.0.0:3000
```

**Comment by wzyplus** [comment]
@Tyriar Can display but can't input.

![image](https://cloud.githubusercontent.com/assets/3762193/16762741/72a981b6-4858-11e6-911e-2224bb7c05df.png)

**Comment by Tyriar** [comment]
@wzyplus can you try toggling dev tools on vscode (Help > Toggle Developer Tools), inspecting the span/div containing the `??????` (using cursor button in top-left corner of dev tools) and get the paste in both the contents of the element and the computed font-family style?

Inspect button:

![image](https://cloud.githubusercontent.com/assets/2193314/16778876/da7a298c-4824-11e6-9ade-233a92ba1a13.png)

Computed styles tab:

![image](https://cloud.githubusercontent.com/assets/2193314/16778903/ef420682-4824-11e6-8181-55bc6c2a88d5.png)

**Comment by wzyplus** [comment]
@Tyriar 

![image](https://cloud.githubusercontent.com/assets/3762193/16793296/78fc6b50-4902-11e6-8194-2c45c5bb1422.png)

![image](https://cloud.githubusercontent.com/assets/3762193/16793303/835f0c9c-4902-11e6-9aaa-4db34276af32.png)

**Comment by ZCShou** [comment]
@Tyriar So does on Win10!  But The lastest version  can copy & paste！I have a .gif file, but upload failed！

**Comment by Tyriar** [comment]
FYI on the input side of things I've put out a PR which is mostly done, I still need to verify it on multiple-character IME compositions though, such as in Japanese. I'm not familiar with the Chinese IME systems but I think it's likely covered by the Korean/Japanese cases. https://github.com/sourcelair/xterm.js/pull/175

**Comment by alexandrudima** [comment]
@Tyriar Here is a wiki page I put together from various sources with examples and detailed steps on how different input methods should work, considering Word as the golden standard: https://github.com/Microsoft/vscode/wiki/IME-Test

**Comment by Tyriar** [comment]
@alexandrudima I think this issue is related to text encoding rather than the IME.

I'm familiar with Japanese and Korean IMEs from language learning so I used that experience when implementing support (which is in stable now). @rebornix did tests for Chinese, I don't think Vietnamese was tested though. You can check out https://github.com/sourcelair/xterm.js/pull/175 for the testing I did before endgame.

Thanks for the resource :+1:

**Comment by yangg** [comment]
vs code: 1.6.0
Can not display Chinese character in git log on windows 7,  
but it displays folder with Chinese character correctly.
I tried both cmd.exe & git bash.exe
```json
"terminal.integrated.shell.windows": "bash.exe", // git bash
```

**Comment by Tyriar** [comment]
The situation for this should be better now as `$LANG` is being set.
