### ISSUE TITLE
Use 'JetBrains Mono' as standard font.

### ISSUE THREAD

**Issue by MarvinJWendt** [microsoft/vscode#88920]
How about using the font from JetBrains [(JetBrains Mono)](https://www.jetbrains.com/lp/mono/) as the standard font?

The font was specially made for coding and will be used in every JetBrains IDE from now on (IntelliJ IDEA, etc.) The font has a full set of features, which are meant to improve the coding experience.
![image](https://user-images.githubusercontent.com/31022056/72674568-b24b7e80-3a78-11ea-9d6c-55074b635d21.png)
![image](https://user-images.githubusercontent.com/31022056/72674621-1c642380-3a79-11ea-9bbf-f8330a393efe.png)

I think it's way better to read, and the [`ligatures`](https://www.jetbrains.com/lp/mono/#ligatures) are very useful to me (ligatures are disabled in VSCode by default tho).

For example:
![image](https://user-images.githubusercontent.com/31022056/72674556-7ca69580-3a78-11ea-9042-1ae21fee5c47.png)

I could explain all the features of the font, but that would take too long.
I would suggest checking out: https://www.jetbrains.com/lp/mono/#key-features

It's also free to use:

> JetBrains Mono typeface is available under the Apache 2.0 license and can be used free of charge, for both commercial and non-commercial purposes. You do not need to give credit to JetBrains, although we will appreciate it very much if you do.

## Obviously this is just my opinion, but I feel like this font fit's very well into VSCode as it provides a better coding experience (to me).

Feel free to drop your thoughts about this :)

**Comment by alexdima** [comment]
There are a lot of very good monospace fonts, some of which are open source. At this time, VS Code does not ship any font for text rendering and simply uses what is installed on the machine. We do so for multiple reasons: to respect the platform defaults, to not over inflate the download size, the avoid licensing issues, etc.

You can write a VS Code extension which ships this specific font with its resources and which uses OS commands to install it, and then change the default of VS Code.

**Comment by mathmul** [comment]
Is anyone writing this extension? It'd be awesome to have.

**Comment by mw76** [comment]
No need for a extension. The font is open source and free to use everywhere. Just install it on your system and change the settings in VSCode to use the new font.

**Comment by webdevotion** [comment]
And **enable ligatures** to use a lot of the font's features:
Instructions ( for another font but process is the same ):
https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions#manually-editing-settingsjson

**Comment by MuhammadimYusoff** [comment]
Can I know how to write the font name properly?
in my settings.json file written as follows:-

    "editor.fontFamily": "'JetBrains Mono Regular' , 'Fira Code'",

is it right? how can i change the font properly?

**Comment by MarvinJWendt** [comment]
This is my solution

### Settings -> Search for `font`
![image](https://user-images.githubusercontent.com/31022056/73685912-4d726400-46c7-11ea-83d9-529c2c264ef4.png)
![image](https://user-images.githubusercontent.com/31022056/73685929-56633580-46c7-11ea-88c7-1ba6bff0482b.png)
![image](https://user-images.githubusercontent.com/31022056/73685975-6e3ab980-46c7-11ea-8d50-afefca108f0d.png)

**Comment by Gama11** [comment]
@MuhammadimYusoff  This works for me:

```json
"editor.fontFamily": "'JetBrains Mono'"
```

**Comment by MikiSkyxer** [comment]
> This is my solution
> 
> ### Settings -> Search for `font`
> ![image](https://user-images.githubusercontent.com/31022056/73685912-4d726400-46c7-11ea-83d9-529c2c264ef4.png)
> ![image](https://user-images.githubusercontent.com/31022056/73685929-56633580-46c7-11ea-88c7-1ba6bff0482b.png)
> ![image](https://user-images.githubusercontent.com/31022056/73685975-6e3ab980-46c7-11ea-8d50-afefca108f0d.png)

Okay Thank you very much. ✌️

I suppose to use ‘FiraCode’ on my editor and ‘Consolas’ for my terminal (because same font made me confuse between codes and errors).
