### ISSUE TITLE
Cycle Parameter Hints from keyboard

### ISSUE THREAD

**Issue by NikiforovAll** [microsoft/vscode#88922]
The goal is to have seamless developer flow without mouse. It is really useful to be able to not only trigger `editor.action.triggerParamterHints` but also be able to traverse them via keyboard. ⌨ 🤔

**Comment by octref** [comment]
What would be a natural shortcut? We can't use up/down since that's taken by editor.

**Comment by NikiforovAll** [comment]
`showNextParameterHint` as `Alt+(Down/Up)Arrow` is just perfect. Although, it doesn't work in consistent way - sometimes you need to guess which arrow triggers parameter cycling. Let me know if you need a demo or something

**Comment by octref** [comment]
Option up/down are taken by moving line up/down.

**Comment by NikiforovAll** [comment]
What we could do is to add user setting/preference that signifies the priority `triggerParamterHints` over text editor. So when you press up/down you actually cycle through params

This option is disabled by default and could be adjusted on user/workspace level

Another way to do it is to define command available from command palette which is not assigned to any keyboard shortcuts and then folks will figure this out.
* `editor.action.triggerParamterHints.Next`
* `editor.action.triggerParamterHints.Previous`

Don't vscode has this option already? I will need to check. 🤔
