### ISSUE TITLE
Introduce a HoverContext for HoverProvider with maxLineLength

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#88926]
There is a longstanding issue of very poor wrapping in hovers, see https://github.com/microsoft/vscode/issues/86805, https://github.com/microsoft/vscode/issues/35223, https://github.com/microsoft/vscode/issues/47873 and possibly others. But even if that is improved with better word wrapping, it's never going to work great in code blocks like the example from #47873. It's not enough to just not break in the middle of words there, ideally the second line would also be indentend.

I think the best solution would be to let extensions handle this - only they know how the code is best wrapped. If they implement a formatter, it might even just be a matter of running that over the code snippets in the hover with a specific max line length.

This is where the API limitation comes in: afaik, extensions currently have no way of finding out what the max line length in a hover is going to be. This info could be provided to a `HoverProvider` via a new `HoverContext`. Many providers are already provided with a "context", so this would follow that existing pattern.

**Comment by octref** [comment]
I'm not sure giving API to let extension do text wrapping is a good idea. @joaomoreno What do you think?

**Comment by joaomoreno** [comment]
@octref Yup, bad idea. We should instead address the issues for all usages.

**Comment by Gama11** [comment]
The only other solution I can think of to address the issue I described is running language-specific formatters. So the alternative might be to have VSCode invoke a formatting provider on each code block of the hover, with a certain max line length specified. I think the max line length is not currently part of the [formatter options](https://github.com/microsoft/vscode/blob/70d7091d75d3156578362292962bb81fc1293767/src/vs/vscode.d.ts#L3143) though (and some formatters choose to ignore these).

**Comment by octref** [comment]
I'll merge the discussion into #86805. Not necessarily we'll do it this way, but formatters like prettier do have an option to wrap at specific length. I can see our provider giving this information so extensions can format code cells to specific length.
