### ISSUE TITLE
Small save dialog on 4K

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#88931]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Have a second monitor with 4k res. Windows scaling is set to 150%
2. Open VSCode there.
3. Save a file.
--> The dialog will be tiny (as if it doesn't adhere to the 150% setting but sticks to 100%)

Does this issue occur when all extensions are disabled?: Yes

**Comment by EpicWolverine** [comment]
I came here to file a separate bug, but I think we may have the same problem but opposite situations. My main display is scaled to 125% but my secondary is at 100% and the dialogs (it happens for both save and open) are comically large. The scaling does not change when dragged between monitors like it does for the main vscode window.

After some experimenting, I think the scaling of the dialog boxes is dependent on **the scaling the main display is set to when vscode is opened**. Changing the scaling after it is opened does nothing, but setting my main display to 100%, opening vscode (which opens on the other monitor btw), and setting my main display back to 125% keeps the dialogs scaled to 100%.

**Comment by runxel** [comment]
Yes, this sounds like the same bug.
My main/primary monitor is indeed set to 100% scaling.

**Comment by dzsquared** [comment]
Duplicate to #88708, but also an issue for me.
