### ISSUE TITLE
color issue

### ISSUE THREAD

**Issue by cyberh0me** [microsoft/vscode#88934]
- VSCode Version: 1.42.0-insider (user setup)
- OS Version: 19546.rs_prerelease.200110-1443

Steps to Reproduce:

1. install it
2. start it

Does this issue occur when all extensions are disabled?: Yes

as you should see vs code is much "darker" as it should be
this started to happen with one of the latest insider releases
unfortunately i cant show it with Windows "Screen snip" because the colors are than ok so i needed to use a cam

![20200119_141537](https://user-images.githubusercontent.com/39925052/72681706-77703780-3ac6-11ea-89e9-17e478893108.jpg)

**Comment by cyberh0me** [comment]
issue does not occur with:
Version: 1.42.0-insider (user setup)
Commit: c4b6a6b537de49a734d0eedea06152ea37dfdb6a
Date: 2020-01-28T05:38:41.922Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19551

**Comment by cyberh0me** [comment]
and again issues, do you see the difference between 1.42 and 1.43 ?
what are you doing that i always have this problems @bpasero @deepak1556 ?
![Annotation 2020-02-17 003853](https://user-images.githubusercontent.com/39925052/74615104-e40a4080-511d-11ea-9554-a245cb2062e2.jpg)

**Comment by bpasero** [comment]
@cyberh0me can you try the steps outlined here to see if that helps: https://github.com/microsoft/vscode/issues/88491#issuecomment-585273752

**Comment by cyberh0me** [comment]
@bpasero 1.) your last link https://az764295.vo.msecnd.net/insider/a1f569c66f67287c525ee50b5f46ced8a50b4551/VSCode-darwin-insider.zip does not include an exe file we could execute

so i used https://az764295.vo.msecnd.net/insider/7428f161b0def9c82f5582b977f837fb0ad63453/VSCode-win32-x64-1.42.0-insider.zip and the colors are better

**Comment by bpasero** [comment]
@cyberh0me thanks for trying this out and finding the correct build. To clarify: once you set `srgb` as forced color profile you see the issue fixed on that build right?

Other versions will not support this flag yet.

**Comment by deepak1556** [comment]
> This is probably a duplicate of #88491

Just to reconfirm this, @cyberh0me are you using a HDR display ?

**Comment by cyberh0me** [comment]
"@cyberh0me thanks for trying this out and finding the correct build. To clarify: once you set srgb as forced color profile you see the issue fixed on that build right?"

@bpasero if you mean with that bild https://az764295.vo.msecnd.net/insider/7428f161b0def9c82f5582b977f837fb0ad63453/VSCode-win32-x64-1.42.0-insider.zip yes

@deepak1556 yes i am using a HDR display

**Comment by deepak1556** [comment]
Thanks for confirming and testing so far, this is an upstream issue with chromium. I am merging this to #88491
