### ISSUE TITLE
Debug console output to file on disk have different format.

### ISSUE THREAD

**Issue by Rvadrabade** [microsoft/vscode#88938]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 18.04

Steps to Reproduce and results:

https://github.com/Rvadrabade/gdb

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
Thanks for the nice steps however can you please first file this issue against the C++ extension and if they find out that the issue is on the vscode side they can move the issue back to us with more vscode specific details. Thank you very much
https://github.com/microsoft/vscode-cpptools
