### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by regdev18** [microsoft/vscode#88937]
Issue Type: <b>Feature Request</b>

The light theme is too bright and annoying to look at. I would like this theme to be improved to be visually pleasing.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by misolori** [comment]
Please see our [marketplace](https://marketplace.visualstudio.com/search?term=light&target=VSCode&category=Themes&sortBy=Installs) to find a suitable light theme or you can [create your own](https://code.visualstudio.com/docs/getstarted/themes#_creating-your-own-color-theme).
