### ISSUE TITLE
Allow graphical elements like arrows as decorations

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#88932]
I'm writing a debug adapter and I would like to offer a visualization of the last executed steps before the current.

Therefore I would like to use decorations (but if there are other means I could also use something different).

And I would like to use a graphical visualization with arrows. The arrows point from the previous instruction to the next instruction.
It should look very much like the arrows used in the clang visualization for Xcode, e.g. here:
<img width="688" alt="TV9Xd" src="https://user-images.githubusercontent.com/3081973/72680945-82739980-3abf-11ea-82e2-cf21100aa186.png">

I.e. the program execution is currently at line 207 but the user could see exactly which branches have been taken to get there.

Therefore I would like to ask to extend the capabilities of the vscode decorations so that one can also add graphical elements that span over several lines and are drawn on top of the text.

**Comment by connor4312** [comment]
Check out the text editor decoration API. That allows you (a limited) set of ways to apply styling to lines, including the ability to add icons which you could use cleverly to do what you're after.

**Comment by maziac** [comment]
Really. Could you point me to the documentation. I haven't found anything like this.
As shown in the picture I'm looking after e.g. a line that is drawn from a column position in line x to another column in another line y.
