### ISSUE TITLE
Allow single TypeScript files to be compiled with compiler options

### ISSUE THREAD

**Issue by sfsccn** [microsoft/vscode#88947]
If **tsconfig.json** exists then Intellisense seems to be based on `tsc` being run on all the ***.ts** files in the workspace that satisfy the conditions in **tsconfig.json**. But I just want it to run the currently open file. My workspace is about learning TypeScript, so I often have multiple files sharing the same variable. This causes errors concerning duplicates when multiple files are compiled. Please let me know if I'm missing something, otherwise:

**Feature Request 1**: please provide an option to compile only the currently open file (for Intellisense purposes).

I suspect **Feature Request 1** is not possible because on the command line when when `tsc` is given a source file [it ignores](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) **tsconfig.json**. So the only way to use **tsconfig.json** is without a source file.

Removing **tsconfig.json** appears to allow me to do single-file compiling. But it would be nice to be able to specify compiler options. If we could pass command-line options to `tsc`, that might solve the problem. For example:

`tsc --alwaysStrict myFile.ts`

bypasses **tsconfig.json** and compiles only **myFile.ts** while using the given compiler option. So if **Feature Request 1** is not possible then:

**Fetaure request 2**: please provide a setting that allows command line options to be passed to `tsc` when **tsconfig.json** is not present so that just the currently open file is compiled with those options (for Intellisense purposes).

**Comment by sfsccn** [comment]
It looks like **tsconfig.json** is pretty much mandatory. Because tsc ignores  **tsconfig.json** when a source file is given on the command line, I suspect the feature requests above are not possible or aren't worth it. As a workaround, if I want to write TypeScript files for practice that have variable names in common I'll just enclose them in IFFEs or something.

**Comment by mjbvz** [comment]
Documentation of compiler options: https://www.typescriptlang.org/docs/handbook/compiler-options.html

I recommend creating a `tsconifg` for anything more than just a quick, single-file experiment. We don't have plans to add VS Code settings to control all of compiler options since they are already supported in tsconfig (tsconfigs also work across different editors)
