### ISSUE TITLE
new port forwarding UI: how to specify local port?

### ISSUE THREAD

**Issue by OneCyrus** [microsoft/vscode#88941]
with the old port forwarding UI we always had the same local port like the remote port. with the new UI it takes a random local port. this doesn't play nice when using CORS in our development. with CORS we have to use always the same port. it doesn't look like we can control the local port.

support for e.g. the container notation like 3000:5000 to map remote port 5000 to local port 3000 would be great.

**Comment by alexr00** [comment]
This is actually a Windows + the way we're looking for an available port problem. The fix I'm merging will use the same port as the remote if it's available.

**Comment by OneCyrus** [comment]
allowing to specify the local port as well would still give a lot of benefits too.

**Comment by alexr00** [comment]
It would. I'm thinking of adding a right-click -> Change local port. How does that flow sound to you? Then, if you have the setting `    "remote.restoreForwardedPorts": true,`, you'd get that forward restored in your workspace.

**Comment by OneCyrus** [comment]
sounds great!

**Comment by alexr00** [comment]
To verify (Windows required):
- Connect to a remote using SSH nightly or Containers
- Forward a port using the Forwarded Ports view in the remote explorer (eg. 2000)
- Verify that you get the same local port as remote port (eg. 2000) if that port is available locally.

**Comment by dbaeumer** [comment]
Verified

![capture](https://user-images.githubusercontent.com/1931590/73454963-70231680-436f-11ea-9362-9892cc36ade5.png)
