### ISSUE TITLE
Enable user to open remote container on remote server

### ISSUE THREAD

**Issue by twolodzko** [microsoft/vscode#88957]
As a user, I want to be able to connect to remote server (`Remote-SSH: Connect to host...`) and then, on the server, to log into a docker container (`Remote-Containers: Open Folder in Container...`)[ as described in documentation](https://code.visualstudio.com/docs/remote/containers), so that I can apply & test the changes on the remote server.

Currently, when I work on remote server, I don't see the `Remote-Containers: Open Folder in Container...` menu, neither in Status Bar, nor in Command Palette, nonetheless that "Remote Development" extension is installed.

**Comment by twolodzko** [comment]
It doesn't seem to be duplicate.

**Comment by IllusionMH** [comment]
/causedByExtension

Please fill this request in Remote extensions repo https://github.com/microsoft/vscode-remote-release/issues
