### ISSUE TITLE
"Reload Required" is always shown, even after reload

### ISSUE THREAD

**Issue by windless0530** [microsoft/vscode#88958]
- VS Code Version: 1.39.2 (Mac)
- Log file (set `"trace": true` in launch config):
- Extension Version: 2.0.14

My current workspace is a C++ project so this extension is not applicable, gray and disabled. There had been nothing wrong for long time. But these days, maybe after some upgrade, the RELOAD REQUIRED button is always shown, no matter how many times I click it to reload Code, or even restart Code.

P.S. Another extension vscode-chrome-debugger has the same [issue](https://github.com/microsoft/vscode-chrome-debug/issues/971).

![image](https://user-images.githubusercontent.com/4645959/72673151-5517f300-3aa1-11ea-9e76-d83a32736807.png)

**Comment by sandy081** [comment]
Can you please check if these extensions are running. You can check this using the command `Developer: Show Running Extensions`
