### ISSUE TITLE
VSCodeInsider_VSOnline_VSONLINE_Keyboard:Unnecessarily taking extra tab focus on the window control.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88953]
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Repro Steps:​**
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3 .Click on "Visual Studio Online" and navigate till "Remote Explorer"
4. Navigate till "VS ONLINE" control.
5. Observe that taking extra tab focus on the screen.

**Actual:**
Unnecessarily extra tab focus present on the window control which is non actionable.

**Expected:​**
Keyboard focus should not present/move on  non actionable window control.

**User Impact:​**
Keyboard only user try to perform the action/activate the control unnecessarily for non actionable control.User understand the control is actionable if keyboard focus is present.

[88953_VSCodeInsider_VSOnline_VSONLINE_Keyboard.pptx](https://github.com/microsoft/vscode/files/4085015/88953_VSCodeInsider_VSOnline_VSONLINE_Keyboard.pptx)

**Comment by isidorn** [comment]
Dup of https://github.com/electron/electron
