### ISSUE TITLE
Extensions Web View does not follow zoom

### ISSUE THREAD

**Issue by ecmel** [Microsoft/vscode#8895]
<img width="762" alt="capture" src="https://cloud.githubusercontent.com/assets/1858678/16678711/547cf86a-44ea-11e6-8d6b-25af6cc27447.PNG">
- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce:

1. code --enable-use-zoom-for-dsf (Due to bug #1896)
2. Open an extension tab

**Comment by jrieken** [comment]
this is #5745
