### ISSUE TITLE
Deleted files and folder

### ISSUE THREAD

**Issue by maxl1997** [microsoft/vscode#88955]
Issue Type: <b>Bug</b>

VSCode deleted the untracked .vscode folder and one more untracked file in the toplevel folder.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1833)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.71GB (0.13GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
githistory|don|0.4.13
vscode-todo-plus|fab|4.14.1
output-colorizer|IBM|0.1.2
theme-monokai-pro-vscode|mon|1.1.14
vscode-language-pack-de|MS-|1.41.2
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.2
material-icon-theme|PKi|3.9.2
omnetpp-ned|sch|0.0.4
code-settings-sync|Sha|3.4.3
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@maxl1997 How do you know VS Code itself deleted it? It could've been any tool in your system, including any extension you might've installed. Can you reproduce the issue?

**Comment by maxl1997** [comment]
@joaomoreno I don't know for sure, but VS Code is the only tool I use in this folder, so my first thought was that it may be VS Code.

I could not reproduce the issue.

**Comment by joaomoreno** [comment]
OK, let me know if it happens again.

**Comment by dislick** [comment]
For anyone experiencing the same: The issue is probably in lint-staged@10.0.2 https://github.com/okonet/lint-staged/issues/780
