### ISSUE TITLE
VSCodeInsider_VSOnline_VS-SuspendEnvironment_AI4D:Incorrect name provided for the "warning" image.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88952]
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Repro Steps**:​
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3. Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4. Navigate till any environment and the "Suspend " button and click on it.
5. Open AI4D.
6. Check name property for the "waning" image.

**Actual:**
For the "Waning image", Incorrect name property provided.

**Expected:​**
For the "Waning image", Name property should provided correctly.

**Same issue Observed for the below scenario:**
**1.VS-Delete Environment**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till any environment and press right click.
5.Navigate till "Delete Environment " button and click on it  .
6.Verify that all the elements of "VS- Delete Environment" pop up are accessible and MAS Compliant.

**​User Impact:​**
Screen reader user does not understand related name or information regarding the control.
![image](https://user-images.githubusercontent.com/55909580/72707415-5cfd9300-3b86-11ea-83c8-d31236612706.png)

**Comment by isidorn** [comment]
Please file against electron https://github.com/electron/electron
