### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by mshabab1296** [microsoft/vscode#88964]
Issue Type: <b>Performance Issue</b>

When I restart my vscode intellisense works properly. It stops After doing some code.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    62	  5760	code main
    0	   123	  3268	   gpu-process
    1	    67	  4104	   window (Issue Reporter)
    0	    44	  7824	   shared-process
    0	     0	  7864	   
    0	     0	  8700	   
    0	    13	  9832	   electron-crash-reporter
    0	   130	 15100	   window (● StreamList.js - react - Visual Studio Code)
    0	     4	  7788	     console-window-host (Windows internal process)
    0	     5	  9460	     console-window-host (Windows internal process)
    0	    34	 10940	     searchService
    0	    10	 12512	     watcherService 
    0	     4	 15328	       console-window-host (Windows internal process)
    0	    14	 13536	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     2	  6328	       C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	     9	 12824	         "C:\Program Files\nodejs\\node.exe"  "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" start
    0	     2	 10472	           electron_node db.js 
    0	    11	  3428	             electron_node bin.js db.js 
    0	    38	 13656	     extensionHost
    0	    31	  5424	       electron_node tsserver.js 
   25	    22	  8096	       electron_node tsserver.js 
    0	    15	  2692	         electron_node typingsInstaller.js typesMap.js 
    0	    30	 11304	       electron_node eslintServer.js 
    0	    15	 14512	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     2	 14244	       C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    10	  9828	         "C:\Program Files\nodejs\\node.exe"  "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" start
    0	     2	  5372	           C:\WINDOWS\system32\cmd.exe /d /s /c react-scripts start
    0	     8	  8320	             electron_node react-scripts.js 
    0	    37	 11608	               node E:\xampp\htdocs\react\streams\client\node_modules\react-scripts\scripts\start.js
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● StreamList.js - react - Visual Studio Code)
|    Folder (react): 162 files
|      File types: js(51) json(22) png(12) gitignore(6) md(6) ico(6) html(6)
|                  txt(6) css(3)
|      Conf files: package.json(7);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.14
es7-react-js-snippets|dsz|2.5.0

</details>

**Comment by lomeat** [comment]
oh
i thought that only me have this problem
I write some code, alt+tab to browser, return back and see "Loading..." instead of list of functions
Let install older version

**Comment by mjbvz** [comment]
@mshabab1296 What language?

**Comment by 3abdawy** [comment]
@mshabab1296  This happened to me, i tried everything , but i think that the latest version has some issues with the intellisense , so try to use an older version , **v1.31** or **v1.38**  are working well and stable.
It's important to install it while your internet is disconnected to prevent automatic updates , Although u shall go to settings and search for update and select **none**

**Comment by mshabab1296** [comment]
> @mshabab1296 What language?

Javascript

**Comment by 3abdawy** [comment]
@mshabab1296  yes

**Comment by mshabab1296** [comment]
> @mshabab1296 This happened to me, i tried everything , but i think that the latest version has some issues with the intellisense , so try to use an older version , **v1.31** or **v1.38** are working well and stable.
> It's important to install it while your internet is disconnected to prevent automatic updates , Although u shall go to settings and search for update and select **none**

Thanks, @3abdawy I installed v1.38 and the problem has gone
