### ISSUE TITLE
incorrect window title when has unsaved files in Chinese

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#8896]
- VSCode Version: vscode-1.3.0-insider
- OS Version: windows7

Steps to Reproduce:

1.  Change Language to Chinese.
2.  Open a file and modify it.

![3](https://cloud.githubusercontent.com/assets/7069719/16676651/2ed9f30a-44ff-11e6-93f2-71f2c68cdf0f.png)

**Comment by bpasero** [comment]
@johnliu2016 fyi

**Comment by johnliu2016** [comment]
Fixed in latest loc change commits to loc repo.

**Comment by f111fei** [comment]
I will close PR https://github.com/Microsoft/vscode/pull/8885
