### ISSUE TITLE
Can extensions have control for hiding context menus like Add Logpoint

### ISSUE THREAD

**Issue by gvrpraneeth** [microsoft/vscode#88962]
We are writing a vscode extension for debugging purpose
We would like to show 'Add Conditional Breakpoint' and 'Add Logpoint...' only on specific conditions
Can we achieve this
Please help

**Comment by weinand** [comment]
No, adding breakpoints and Logpoints is generic VS Code functionality that is independent from any installed debugger extension. If your debugger extension would be able to turn breakpoints and Logpoints off and you have another debugger extension installed that would have them turned on, how should VS Code resolve this?

**Comment by gvrpraneeth** [comment]
Thanks for your immediate response
