### ISSUE TITLE
Untitled editor tab name and search entry differs

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#88969]
Issue Type: <b>Bug</b>

In latest Insiders builds Untitled files start to show first line as tab title (related to #37414).
This tab name is reflected in Open editors, however search still has Untitled-1, Untitled-2 in results which is hard to map to content.
![image](https://user-images.githubusercontent.com/1312662/72723906-891b1300-3b8a-11ea-8fb5-caa6fd73c30f.png)

/cc @bpasero

VS Code version: Code - Insiders 1.42.0-insider (d72b2d372f5024a9193b37a3830bbbc459c0ef1b, 2020-01-20T05:33:26.563Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
Good catch 👍
