### ISSUE TITLE
VSCodeInsider_VSOnline_Extension_VisualStudioOnline_AI4D:localized control type name is not provided."Micosoft,16854, *****, repository & license" control.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88961]
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Repro Steps:​**
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3. Navigate  right panel till "Extension: Visual Studio Online" 
4. Open AI4D.
5. Check "localized control type" is provided or not for the below control.
![image](https://user-images.githubusercontent.com/55909580/72716962-27ae7080-3b99-11ea-8b4d-b3269e540241.png)

**Actual:**
For the  above mentioned localized control type name is not provided 

**Expected:​**
For the above mentioned localized control type name should  provide  and screen reader should announces the same.

**​User Impact:​**
Screen reader user does not understand name of the regarding the control type if screen reader does not announces the control type..
![image](https://user-images.githubusercontent.com/55909580/72717113-765c0a80-3b99-11ea-9375-f4a755966fc6.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/88792
