### ISSUE TITLE
Expand selection in double quotes jumps to select whole line in Go files

### ISSUE THREAD

**Issue by ayubmalik** [microsoft/vscode#88968]
Issue Type: <b>Bug</b>

1. Edit  .go files and place cursor inside a double quoted string in the editor. E.g.
`content := "some string here"`
2.  Expand the selection repeatedly using using smart select shortcut (Shift + Alt + Right Arrow).

The selection does not stop when all the content inside the quotes is selected, rather it _jumps_ to select the whole line. 

I would only expect the text inside the quotes to be selected first. This problem is specific to golang (.go) files as I don't have this problem with JavaScript files, the selection expands correctly.

Does this issue occur when all extensions disabled? Yes (I have reloaded vscode with all extensions disabled).

Originally raised [here.](https://github.com/microsoft/vscode-go/issues/2984)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 3268)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.51GB (11.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
plantuml|jeb|2.13.6
python|ms-|2020.1.58038
cpptools|ms-|0.26.2
Go|ms-|0.12.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.14.0
vscode-manifest-yaml|Piv|1.14.0
vscode-spring-boot|Piv|1.14.0
java|red|0.55.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.20.2
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by jrieken** [comment]
> Originally raised here.

It is an extension issue as it doesn't help vscode in expanding ranges properly. However, our default could be better, but without a file and more steps I can't make statement...

**Comment by ayubmalik** [comment]
@jrieken Do you need more info from me?

**Comment by jrieken** [comment]
> ...better, but without a file and more steps I can't make statement...

Yeah, I need a sample file code snippet in which you are trying this and the position at which you are trying this

**Comment by ayubmalik** [comment]
Here is a sample program below.

If you insert the cursor on the "H" inside  "Hello, World\n" (Line 6 Col 14) and press the expand selection shortcut (Shift+Alt+Right Arrow on Linux) first the word Hello is selected and then the whole line.

The same behaviour occurs with other strings in quotes.

```
package main

import "fmt"

func main() {
	msg1 := "Hello, World!\n"
	fmt.Println(msg1)

	msg2 := "This is some other text"
	fmt.Println(msg2)
}
```

**Comment by jrieken** [comment]
Yeah, that's the default implementation which works off words, line, line with whitespace, and blocks of bracket pairs. VS Code doesn't have deeper knowledge of the language and relies on the help of extensions for further smarts, e.g knowing what an expression or statement is. For golang, that's tracked here https://github.com/microsoft/vscode-go/issues/2984
