### ISSUE TITLE
VSCodeInsider_DefaultSettingforNewEnvironment_AI4D: (Code - Insiders/tree '') The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#88963]
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Application:** Code - Insiders has the following accessibility issue that needs investigation.

**Issue Details**
Provide a UI Automation Name property that concisely identifies the element.

**Element path:** tree ''

**To Reproduce and How to Fix guidance**: Please open the attached Accessibility Insights for Windows Test File (*.a11ytest) to reproduce the error in Accessibility Insights for Windows.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. 

![image](https://user-images.githubusercontent.com/55909580/72717625-685ab980-3b9a-11ea-8db3-a6d1cd531b48.png)

**Same issue observed for the below scenario:**
**1.Select Plan**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "Select Plan" button beside the  "VS ONLINE" control and click on it.

**2.Create New Environment**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control  and click on it.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/88746
