### ISSUE TITLE
cant open terminal getting error

### ISSUE THREAD

**Issue by xitos2019** [microsoft/vscode#88978]
Issue Type: <b>Bug</b>

Hi,

i am getting error when i am trying to open terminal in in VS Code. "C:\Program Files\Git\bin\bash.exe does not exist"
could you please help 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.1.8
vscode-terraform0-12|dhd|0.0.1
terminal|for|0.0.10
terraform-azure-autocomplete|las|0.0.1
terraform|mau|1.4.0
dotenv|mik|1.0.1
terraform-snippets|min|2.1.0
vscode-azureterraform|ms-|0.3.0
vscode-docker|ms-|0.9.0
remote-wsl|ms-|0.41.7
azure-account|ms-|0.8.8
docker-compose|p1c|0.3.5
terraform-advanced-syntax-highlighting|pjm|0.0.3
terminalis|Spe|0.4.0
terminal-tabs|Tyr|0.2.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What do you have in Settings for `terminal.integrated.shell.windows`?
Most likely you need to either fix that path or remove it to use default (PowerShell).

**Comment by xitos2019** [comment]
> /needsMoreInfo
> 
> What do you have in Settings for `terminal.integrated.shell.windows`?
> Most likely you need to either fix that path or remove it to use default (PowerShell).

i have  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe" in my settings i have just re-installed VS code now i ma able to open shell terminal.
 thanks for your help.
