### ISSUE TITLE
Support unlisted or helper extensions

### ISSUE THREAD

**Issue by pkrukp** [microsoft/vscode#88975]
Hello, 

# Summary

would be nice if extensions could provide their own recommendations/suggestions. For example after installing extension X, the extension could suggest also installing extension Y or Z based on the workspace content.

# Context

My use case:

We're considering creating 3 extensions: Tool_C#, Tool_C++, Helper. Tool_C# and Tool_C++ would provide functionality to work with external tool for given language. The Helper extension would provide common functionality. This allows code sharing and prevents command duplication.

If user installs Tool_C# extension, it can automatically install Helper extension (with extensionDependencies).

But if user installs Helper extension only, the extension can't say "hey, I noticed you have C# files, and since you already installed this Helper extenions, you'll most likely want the Tool_C# extension too".

**Comment by sandy081** [comment]
After reading the use case, I guess user should never be seeing this helper extension and install it. So this is a request to hide an extension.

@fiveisprime FYI

**Comment by pkruk2** [comment]
That would work too. In other words, a feature which would allow to "share" commands between extensions.

**Comment by sandy081** [comment]
Ok, considering this as a request to have helper or unlisted extension.
