### ISSUE TITLE
Add separate setting to force Untitled-x file names

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#88971]
Issue Type: <b>Feature Request</b>

In latest Insiders builds Untitled files start to show first line as tab title (related to #37414).

As mentioned in https://github.com/microsoft/vscode/issues/37414#issuecomment-575904365 only way to restore `Untitled-x` file names is to have firs line empty and no settings planed.

I would like to have option to disable this behavior:
1. It will be confusing if first line of code will be used as title in search result entry (related #88969)
1. Each time I paste content - cursor is in the end of file and I need to stroll to top and add empty line. Otherwise I have 3-4 editors with `{` or `import React from 'react';` titles.
1. Some formatters remove leading empty line e.g. built-in JSON formatter.
1. Leading empty line adds unnecessary diffs when compared with saved files.

/cc @bpasero

**Comment by rafaelalmeida** [comment]
As this feature was heavily inspired by Sublime Text, another approach is to use the `Untitled-x` naming scheme if the file is not a plaintext file - i.e. has syntax highlighting enabled for a language, or is copied from another pane which does.

**Comment by bpasero** [comment]
@IllusionMH an alternative to not needing a first empty line is to simply put the name you want (e.g. "Untitled 1"). 

Currently, you will also get a fixed title if you open code on a file path that does not exist (where the untitled has an associated file path that will be used when saving). 

> As this feature was heavily inspired by Sublime Text, another approach is to use the Untitled-x naming scheme if the file is not a plaintext file - i.e. has syntax highlighting enabled for a language, or is copied from another pane which does

Wow, I was not aware ST works like that. Indeed, picking a language mode puts the name back to "untitled". I am not sure how helpful that is though because e.g. if I type markdown, it could be very helpful to use the first line as title of the editor because it could be a paragraph that describes the contents well.

Leaving this open for a bit more discussion to happen.

**Comment by IllusionMH** [comment]
@bpasero I rarely use them with text content so just putting desired file name here will require even more work than putting empty line: need to enter text, need to convert it to comment.
For JSON it will require to switch to JSON with comments and switch back and forth in cases when there is chance to copy JS/JSON with comments to see errors (rare case, but encountered few times).

So this is still bad solution for my use cases.

**Comment by bpasero** [comment]
@IllusionMH can you check with latest insiders if the situation improved for you?

**Comment by IllusionMH** [comment]
@bpasero works awesome with JSON (if 50 characters long title before formatting is not counted)

Other files: a bit better but still annoying - need to navigate to top, add empty line or comment (Prettier removes empty line, but now `//` enough to have different files)

**Comment by bpasero** [comment]
We changed the UX a bit and now we still show the previous way, just as description:

![Screenshot 2020-01-29 at 11 21 08](https://user-images.githubusercontent.com/900690/73348422-aab28380-4289-11ea-8865-d653cefe0e92.png)

@IllusionMH would you think that now a setting is not needed anymore?

**Comment by IllusionMH** [comment]
@bpasero I only got this change today and it looks good 👍 
Distinct enough in search results, and fits default sidebar size with title length adjustment.

So I think I don't need separate setting after recent changes.

The only thing that seems off - titles for editor show full path for regular files and for Untitled files it only displays first line content without mention of Untitled-x. Might be a bit hard to find difference in Open editors section without resizing. Should I create separate issue for title?

---
With this addition it looks like only first 39 characters are used for `Unititled-1` (to compensate for this text) however it's still 39 for `Untitled-10` and `Untitled-134`😄

**Comment by bpasero** [comment]
> With this addition it looks like only first 39 characters are used for Unititled-1

That should be 40, I will push a fix. Yeah, it is independent from the length of the untitled path.
