### ISSUE TITLE
vscode seems faulty connected to parent (console) process

### ISSUE THREAD

**Issue by shekh** [microsoft/vscode#88970]
Issue Type: <b>Bug</b>

After I launch vscode.exe from console-based program (far.exe) I noticed these effects:
Parent program (far) screen is frequently distorted by some log messages (which I now believe belong to vscode).
If I quit parent program (far) the vscode is also terminated.

I can live with it (just run vscode from explorer) but it took some to realize what is going on.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by deepak1556** [comment]
Can you provide minimal repro steps ? How are you launching vscode from the console program, please include the arguments used.

**Comment by shekh** [comment]
I just run far.exe, navigate to code.exe and press enter (execute) without any parameters.
To be honest I just realized I still use old far which has some issues with modern windows:
The FAR manager, version 1.70 beta 5 build 1634)
Will check the behaviour with the latest version.

**Comment by shekh** [comment]
Same with latest FAR version (version 3.0.5665.0 x64)
Here what happens after vscode starts: looks like some debug output from vscode is directed to FAR screen.
![image](https://user-images.githubusercontent.com/2552636/98238311-e132d280-1f6e-11eb-85b9-12aef8ab63dc.png)

**Comment by deepak1556** [comment]
You can try launching with `ELECTRON_NO_ATTACH_CONSOLE` environment variable set.

Fixing the issue with FAR is outside the scope of vscode, hence closing.
