### ISSUE TITLE
[rename on type] The match tag's highlighting doesn't work properly

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#88974]
#### Env:
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

#### Steps to Reproduce:

When you click on the tag like `div`, the match is not highlighted. You must move the left / right key to make the tag highlight

#### Does this issue occur when all extensions are disabled?:
Yes (I tested on a new, clean installation)

#### GIF video showing the problem and example:
![stream](https://user-images.githubusercontent.com/30685349/72728339-69391e80-3b8d-11ea-9f77-2736b62a582b.gif)

**Comment by aeschli** [comment]
This got caused by the 'auto-pair' feature which is now turned off by default and being reimplemented with a different approach that hopefull doesn't have that issue.

**Comment by aeschli** [comment]
This seems to work again in the latest.
