### ISSUE TITLE
Unable to install Protocol Buffer extension

### ISSUE THREAD

**Issue by gagangupt16** [Microsoft/vscode#8898]
- VSCode Version: 1.3
- OS Version: Ubuntu 14.04.4 LTS

Steps to Reproduce:

1. Click Extension symbol on left side
2. Search for Protocol Buffer
3. One of the results come (https://marketplace.visualstudio.com/items?itemName=peterj.proto)
4. Clicking on green install does nothing.

**Comment by joaomoreno** [comment]
Do you see any errors in the Developer Tools?

**Comment by gudvinr** [comment]
#8859

**Comment by joaomoreno** [comment]
Closing as duplicate.
