### ISSUE TITLE
TextDocumentContentChangeEvent range returns type Array[] not Range

### ISSUE THREAD

**Issue by Borks** [microsoft/vscode#88980]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Code:
```
let documentChangeEventWatcher = workspace.onDidChangeTextDocument((event: TextDocumentChangeEvent) => {
		// Check that the change applies to the active text editor
		if (event.document.uri !== window.activeTextEditor?.document.uri) { return; }

		// Loop over the changes and detect row additions.
		for (let change of event.contentChanges) {
			console.log(change.range);
		}
	});
context.subscriptions.push(documentChangeEventWatcher);
```

Steps to Reproduce:
1.  During extension development, listen for workspace.onDidChangeTextDocument
2. Loop over changes in event.contentChanges
3. Log change.range 
4. Console shows Array[2] not type Range.
4.1. Seems like same range is twice. 
![image](https://user-images.githubusercontent.com/5571023/72740331-263b7300-3bae-11ea-9db9-6a791dde0a7f.png)

Both interface and official api show as type Range

Does this issue occur when all extensions are disabled?: Yes

**Comment by Borks** [comment]
Seems this is just a logging issue. 
Still behaves like a Range.

**Comment by jrieken** [comment]
Yes - that the [toJSON](https://github.com/microsoft/vscode/blob/63142fc2cbb200c8ca8690ba680e4c4d054d749b/src/vs/workbench/api/common/extHostTypes.ts#L364)-implementation which is doing this.
