### ISSUE TITLE
Extension: TypeScript and JavaScript Language Features

### ISSUE THREAD

**Issue by ustolarinnomius** [microsoft/vscode#88989]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I have this dirty unsaved file with js content, I applied the JS syntax highlight (still dirty unsaved file) and I got another file open (js file, saved), whenever I paste content on the (now dirty) js saved file, the extension crashes and my dirty js file is automatically saved, even when autoSave setting is "off".

This happens at least once per minute and when this is <= 5 a notification for reporting the issue pops up

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|30, 27, 16|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.14
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.18.0
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.9.6
vscode-icons|vsc|9.7.0
markdown-pdf|yza|1.4.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
