### ISSUE TITLE
Keep all my extensions

### ISSUE THREAD

**Issue by kalber** [microsoft/vscode#88982]
As an user, I want to login to keep all my extensions when I change my computer.
Thanks, Greetings.

**Comment by Borks** [comment]
Could use settings sync extension. 
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by IllusionMH** [comment]
/duplicate of #2743 which is in progress for January release.

In the meantime you can use extension recommended by **Borks** above
