### ISSUE TITLE
VS Code does not use anaconda environments

### ISSUE THREAD

**Issue by Nathan-Furnal** [microsoft/vscode#88996]
- VSCode Version: Version: 1.42.0-insider (user setup)
Commit: d72b2d372f5024a9193b37a3830bbbc459c0ef1b
Date: 2020-01-20T05:33:26.563Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19546

- WSL : Ubuntu 19.10

Steps to Reproduce:

1. Have a working conda environment in WSL 2, ``conda activate`` the environment and type 
``code-insiders .``. Select the proper interpreter, in my case the one from the environment I launched VS Code from. 

![annot vscode](https://user-images.githubusercontent.com/45597572/72759892-53504b80-3bd7-11ea-91b6-1b772a236e8e.jpg)

So it seems to default to the basic (Ubuntu) WSL and won't budge. Even though typing 
``which python`` when the environment is activated, brings up the proper python interpreter, as such : 

![image](https://user-images.githubusercontent.com/45597572/72759989-bb9f2d00-3bd7-11ea-831f-b0a2bd953a4b.png)

Does this issue occur when all extensions are disabled?: I'm using the Python and Code Runner extensions

**Comment by sbatten** [comment]
Please start by filing this issue with the Python extension. https://github.com/microsoft/vscode-python
