### ISSUE TITLE
Language Grammar Highlighting Messed Up? (Latest Insiders)

### ISSUE THREAD

**Issue by bradennapier** [microsoft/vscode#88997]
Version: 1.42.0-insider
Commit: d72b2d372f5024a9193b37a3830bbbc459c0ef1b
Date: 2020-01-20T05:27:44.927Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

## Steps to Reproduce:

1. Open Javascript File
2. Use code shown

I believe this has broken languages for me.  I am using "Babel Javascript" and noticed with the most recent update that my color themes are screwed up.  

* It happens with the built in "Javascript" grammar as well as the "Babel Javascript" plugin
* This happens with extensions disabled.  
* Interestingly the highlighting is actually correct until about 3-4 seconds after a window loads. 
* This happens when using default color themes as well
* There does not appear to be any difference when I inspect the tokens - they refer to the same types.
* Not sure if this is in latest insiders build, but it is main thing i see that could cause potentially that is recent? https://github.com/microsoft/vscode/commit/852f493e27e2e6813f131c730543d58ab4ba1202 
* Another potential culprit? https://github.com/microsoft/vscode/commit/fd13e449f5f2fe300f187129d6065ed1cfad74d3
* Also noticed #88075 

### Recent Insiders Build:

![image](https://user-images.githubusercontent.com/15365418/72762672-803c3880-3bae-11ea-8e15-e1035e962f9d.png)

![image](https://user-images.githubusercontent.com/15365418/72763084-1329a280-3bb0-11ea-9479-a4ec2b9eb48f.png)

![image](https://user-images.githubusercontent.com/15365418/72764534-98b05100-3bb6-11ea-9a0a-3b80b3a5a0f9.png)

### Regular VSCode & Previous Insiders Builds:

![image](https://user-images.githubusercontent.com/15365418/72762691-8f22eb00-3bae-11ea-8237-04d0b8bbac2d.png)

![image](https://user-images.githubusercontent.com/15365418/72763100-20469180-3bb0-11ea-87b2-d43d44091f36.png)

![image](https://user-images.githubusercontent.com/15365418/72764544-9ea63200-3bb6-11ea-82d9-fab14a5332a7.png)

```js
const day = require('dayjs');
const SequelizeMysqlConnectionManager = require('sequelize/lib/dialects/mysql/connection-manager');
const abi = require('./abi');

const { env } = process;
```

## Happen without Extensions?

Yes

**Comment by IllusionMH** [comment]
Probably same root cause as #88911

**Comment by mjbvz** [comment]
Likely caused by semantic highlighting. Try setting `"editor.semanticHighlighting.enabled": false` to disable it

**Comment by aeschli** [comment]
Not a bug but semantic highlighting that shows the actual type of the import based on the theme
yellow for functions, blue for variables.
If you don't like that information you can turn semantic highlighting off by
` "editor.semanticHighlighting.enabled": false`

**Comment by mjbvz** [comment]
@aeschli This is a major visual change that is going to cause a lot of issue reports against JS/TS. Are we shipping 1.42 with the semantic highlighting enabled by default? Anything we can do to reduce the impact?

**Comment by IllusionMH** [comment]
@aeschli it's understandable how it works, but it brings few problems to JSX:
1) It creates pale pale tree without almost no highlights if you use `const Comp = () =>(<div>Hi</div>)` because there is no color diff between `<div>`, `<Comp />` and attribute name
![image](https://user-images.githubusercontent.com/1312662/72914574-916c7d00-3d47-11ea-8472-c7acfc50fc3e.png)
2) It creates visual difference in tree between different implementation, but inside JSX thee all are used in the same way and difference should be between components and regular HTML tags
```js
class CompCls extends React.Component{}

function CompFun() {}

const CompArr = () => {}
```

So there is need to have extra info about cases when function/class/variable/property are used in `tagName` of JSX element.
And easy way to restore previous highlighs: green(-ish) for (custom) components, dark blue for tags, light blue for attributes that make sense in that place.

**Comment by aeschli** [comment]
We can turn it off by default for stable, but we should work through the various issues.
- imports (see example above): For me there's a value-add with semantic coloring. Of course there are still issues, such as what to do if a identifier is both a class and a variable.
- JSX tags: I'll look at that. Obviously we don't want everything to become blue.

**Comment by bradennapier** [comment]
There is more than just imports affected here. @aeschli maybe i dont understand specifically but for example a `while` statement is now yellow.  sometimes my highlgithing is half words gray and half blue, will try to get screenshot when i can.

Other times imports have 3 different colorings - gray, yellow, blue based on my theme.  How many colors are there now?  Is there info on what this is doing exactly?

This seems to make the code really hard to read.  I know i can turn it off, but i assume it is an ideal feature for other reasons and want to understand it before i just turn it off.

A bit confused why `for` statement is purple

![image](https://user-images.githubusercontent.com/15365418/72939065-26687980-3d3a-11ea-8029-a613901fde02.png)

and a `while` is yellow

![image](https://user-images.githubusercontent.com/15365418/72939086-2f594b00-3d3a-11ea-9938-f0982a0b7103.png)

I am guessing that it is trying to make functions one color and variables another, etc which is cool - I like that a lot.  But seems inconsistent?  

Like this chain `state.db.updatedUsers` changes the color after the first property is accessed

![image](https://user-images.githubusercontent.com/15365418/72939166-5adc3580-3d3a-11ea-953e-4b08dbcc65ec.png)

It very well could just be that my color theme isn't really setup well for the semantic highlighting ofc.

![image](https://user-images.githubusercontent.com/15365418/72939218-78a99a80-3d3a-11ea-95c1-d8fc1fc80909.png)

![image](https://user-images.githubusercontent.com/15365418/72939009-0769e780-3d3a-11ea-98f6-9c5c47a5647c.png)

and confusing when `config` here is gray.

**Comment by aeschli** [comment]
@bradennapier Thanks for the help to find all the issues.
- Changing JSX tags was not intended. Fixed. #88911

Semantic highlighting only looks at identifiers and resolves them to find out to what symbol they resolve. 
You can use the `Developer: Inspect Editor Tokens and Scopes` hover to see what semantic type/modifier was given to an identifier.
We have a map that assigns each semantic token types to one or more textmate scopes. We query the theme for these scopes to evaluate the color to use.

Keywords are not touched. I don't see any change for `while`. Also I'd I'd like to understand why `CONFIG.updateInterval` gets different coloring. I would expect that all identifiers are variables.

- Please make sure you are on the latest i-build
- What theme are you using?
- Can you attach a small code sample (not just the screenshot)?
- What does the ` Inspect Editor Tokens and Scopes` hover show as semantic type and modifier.
