### ISSUE TITLE
Keybinding context for navigating up/down results from the findInFile (search across files) command while in the "search view"

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#88995]
Issue Type: <b>Bug</b>

I want to be able to navigate up and down `findInFile` results using a keybinding **only** when the search widget on the side bar is "active" (in **focus**). 

To do so I tried:
```
// Navigating search findInFile results
    {
        "key": "ctrl+n",
        "command": "search.action.focusNextSearchResult",
        "when": "hasSearchResult & sideBarFocus && activeViewlet == 'workbench.view.search"
    },
    {
        "key": "ctrl+p",
        "command": "search.action.focusPreviousSearchResult",
        "when": "hasSearchResult & sideBarFocus && activeViewlet == 'workbench.view.search"
    },
```

However, I notice that the above keybindings are **still active** when I try to **switch focus** to the editor (e.g. either in the editor where I am "previewing" the search results or any other one editor). 

As a result, setting the above prevents me from then using the same keybindings for going up and down in the editor:

```
{ "key": "ctrl+p",                "command": "emacs-mcx.previousLine",
                                     "when": "editorTextFocus && !suggestWidgetVisible" },

{ "key": "ctrl+n",                "command": "emacs-mcx.nextLine",
                                     "when": "editorTextFocus && !suggestWidgetVisible" },
```

To my knowledge, this `when` context `activeViewlet == 'workbench.view.search` should prevent the above from happening (i.e. ctrl+n and ctrl+p should actually trigger different commands depending on whether or not the active viewlet is `workbench.view.search`).

---

VS Code version: Code - Insiders 1.42.0-insider (d72b2d372f5024a9193b37a3830bbbc459c0ef1b, 2020-01-20T05:27:44.927Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (31.29GB free)|
|Process Argv|-psn_0_3642233|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.3.1
vscode-database|baj|2.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
gitlens|eam|10.2.0
LogFileHighlighter|emi|2.7.1
shell-format|fox|7.0.0
seito-openfile|Fr4|1.8.5
mdmath|goe|2.4.0
gc-excelviewer|Gra|2.1.32
open-file-from-path|jac|1.3.3
latex-workshop|Jam|8.6.0
vsc-space-block-jumper|jmf|1.2.2
center-editor-window|kai|2.3.0
vscode-docker|ms-|0.9.0
python|ms-|2020.1.58038
sqltools|mtx|0.21.6
neuron-IPE|neu|1.0.4
vscode-ipython|pan|0.5.0
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.6.1
vscode-dired|rru|0.0.4
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.1
emacs-mcx|tut|0.13.0
vscodeintellicode|Vis|1.2.4
vscode-icons|vsc|9.7.0
org-mode|vsc|1.0.0
highlight-trailing-white-spaces|yba|0.0.2
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by roblourens** [comment]
I can't repro this, the `sideBarFocus` context key seems to work correctly at least. Could you try in the Insiders build? It may have already been fixed.
