### ISSUE TITLE
editor.action.inspectTMScopes command removed?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88992]
Was this removed on purpose?

![image](https://user-images.githubusercontent.com/323878/72751456-89a8af00-3b74-11ea-8623-f4fb2485a01d.png)

**Comment by IllusionMH** [comment]
It was renamed to `>Developer: Inspect Editor Tokens and Scopes`

**Comment by roblourens** [comment]
Thanks!

**Comment by roblourens** [comment]
@aeschli I am probably not the only one with a keyboard shortcut for this, I suggest you keep the same command ID for back compat.
