### ISSUE TITLE
VSCode is collapsing RAM and freezing the computer.

### ISSUE THREAD

**Issue by JandroMejia97** [microsoft/vscode#88998]
- VSCode Version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64
- OS Version: Windows 10 Home Edition x64
- RAM: 4GB

**Description:** VSCode at the beginning this works fine, but when executing the `ionic serve` command after a few minutes its processes begin to saturate the RAM, to the point that it collapses, closing VSCode and freezing my computer.

**Detail:**

![image](https://user-images.githubusercontent.com/32623757/72761801-e9767880-3bbb-11ea-8c27-e47bb4f8b411.png)

Does this issue occur when all extensions are disabled?: I do not know

**Comment by sbatten** [comment]
are you using an extension to work with ionic or just running `iconic serve` from the built-in terminal?

**Comment by JandroMejia97** [comment]
I'm running it directly in the VSCode terminal

**Comment by Tyriar** [comment]
@JandroMejia97 can you do the same thing with the process explorer open and take a screenshot when the RAM is filling up? Curious what process is causing the problem.

**Comment by JandroMejia97** [comment]
Again I executed the command 'ionic serve' and from what I see the processes were re-executed as normal. Sorry for the inconveniences.
