### ISSUE TITLE
C mingw, After closing debugger and restarting normal build Permission denied error

### ISSUE THREAD

**Issue by martdu** [microsoft/vscode#88994]
Issue Type: <b>Bug</b>

I use C language and mingw und debugging functionality. After using debugger and closing it and then restarting normal build process with g++ I get an error saying: C:/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file Papprox.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
The terminal process terminated with exit code: 1

Papprox is my Program

After restaring VSCode issue seems to be resolved, building is possible again.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.3-insiders4

</details>

**Comment by sbatten** [comment]
please start by filing an issue with the cpp tools extension as this is part of the cpp debugging/running experience. https://github.com/Microsoft/vscode-cpptools
