### ISSUE TITLE
自动打开cli.js文件

### ISSUE THREAD

**Issue by sunflower-zwf** [microsoft/vscode#88999]
Issue Type: <b>Bug</b>

当vscode没有启动时，会突然启动并打开cli.js文件，当我正在使用vscode时，会从我正在编辑的窗口跳到新打开cli.js文件。
![image.png](https://upload-images.jianshu.io/upload_images/20517443-c43ef5840aa77af1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (9.58GB free)|
|Process Argv|D:\Microsoft VS Code\bin\..\resources\app\out\cli.js --list-extensions|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
code-gnu-global|aus|0.2.2
luatcode|che|0.22.0
path-intellisense|chr|1.4.2
code-runner|for|0.9.15
kite|kit|0.102.0
vscode-language-pack-zh-hans|MS-|1.41.2
python|ms-|2020.1.58038
cpptools|ms-|0.26.3-insiders3
korofileheader|OBK|4.5.2
vetur|oct|0.23.0
indent-rainbow|ode|7.4.0
java|red|0.55.1
markdown-preview-enhanced|shd|0.5.1
lua|sum|0.15.4
pdf|tom|0.5.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.20.2
vscode-icons|vsc|9.7.0

</details>

**Comment by acmaker** [comment]
"When vscode did not start, will suddenly start and open the cli. The js file, when I'm using vscode I was editor window to jump from the new open the cli. Js file. "

I also meet this problem.How should I do?
Thanks!
