### ISSUE TITLE
Add C/C++ support

### ISSUE THREAD

**Issue by huytd** [Microsoft/vscode#89]
I was surprised that VSCode didn't supported C/C++ :(

Need to add this language and CMake/Make as well...

**Comment by bjorn** [comment]
Vote for it here: http://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752459-c-code-completion-and-debugging

**Comment by Tyriar** [comment]
There are now several extensions that enable this, including one from Microsoft. https://marketplace.visualstudio.com/search?term=c%2B%2B&target=VSCode&sortBy=Relevance
