### ISSUE TITLE
Not possible to implement WorkspaceSymbolProvider with only offset information?

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#890]
It appears that it's not really possible to implement WorkspaceSymbolProvider if all you have available from the underlying language analysis engine is offset information (vs. line/col).  

The vscode API requires that you provide line/col for every reference up front, which would require opening every file and mapping position information.  

Questions:

1. Could the vscode API allow passing offset information instead of line/col in this case?
2. Could the vscode API allow a callback that computes line/col (after providing a TextDocument) instead of providing it up-front, since the UX doesn't need this info until after the user chooses to navigate to a reference?
3. Is there any way to work around this?

**Comment by jrieken** [comment]
Fair request, no workaround as of today. Needs some thinking as this might be an issue in several places...

**Comment by jrieken** [comment]
@aeschli Is this urgent?

**Comment by aeschli** [comment]
@jrieken No rush, we don't have any deadlines yet, but it would be great to have it in one of the next milestones.

**Comment by jrieken** [comment]
@lukehoban Not sure if this is still relevant for vcode-go but you can do option #2
