### ISSUE TITLE
Save 

### ISSUE THREAD

**Issue by JeyaRaniga** [microsoft/vscode#89002]
Issue Type: <b>Bug</b>

JSX code is impacted on save which was notan issue previously

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|15.90GB (4.79GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.14
beautify|Hoo|1.5.0
html-tag-wrapper|hwe|0.2.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|2.3.3
LiveServer|rit|5.6.1
ReactSnippets|xab|2.4.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you sure you don't have `editor.formatOnSave` enabled in your settings?
