### ISSUE TITLE
QuickInputList: many Emitter without dispose

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89008]
Noticed quite a few of `Emitter` in quickInputList with no associated `dispose` call.

**Comment by bpasero** [comment]
@chrmarti what about these?

https://github.com/microsoft/vscode/blob/11ac098428c29ffb4f6b661ee079e87d0d78c215/src/vs/base/parts/quickinput/browser/quickInput.ts#L1092-L1096

**Comment by chrmarti** [comment]
Thanks @bpasero !
