### ISSUE TITLE
Web: settings sync often shows progress indicator

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89006]
For some reason the syncing seems to take longer in web. I think it would be good to:
- understand why that is
- overall increase the timeout before showing progress

**Comment by Tyriar** [comment]
Also happens on desktop when the server is acting up: https://github.com/microsoft/vscode/issues/91026

**Comment by sandy081** [comment]
Progress on activity is removed in favour of showing the status as follows

<img width="287" alt="Screenshot 2020-02-20 at 17 46 55" src="https://user-images.githubusercontent.com/10746682/74963135-7f96fc00-5411-11ea-9f7d-577fcfb0f84b.png">

<img width="291" alt="Screenshot 2020-02-20 at 17 47 20" src="https://user-images.githubusercontent.com/10746682/74963149-858cdd00-5411-11ea-9cc2-a38d1ba8172b.png">

<img width="343" alt="Screenshot 2020-02-20 at 17 56 18" src="https://user-images.githubusercontent.com/10746682/74963161-8c1b5480-5411-11ea-84a7-8c9bcc0de234.png">
