### ISSUE TITLE
phpcs: Unable to locate phpcs, Please add phpcs to global path

### ISSUE THREAD

**Issue by ritayzy** [Microsoft/vscode#8900]
- VSCode Version: 1.3.0 (1.3.0)
- OS Version: 10.11.3 (15D21)
- vs plugin: [phpcs](https://github.com/ikappas/vscode-phpcs)

Steps to Reproduce:

when i open a `.php` file, the tips show that: 

![image](https://cloud.githubusercontent.com/assets/18484770/16679514/b913bb44-451a-11e6-81ec-829d036bbfce.png)

in my termianl, i input this `which phpcs`, show that:

![image](https://cloud.githubusercontent.com/assets/18484770/16679544/f51f616a-451a-11e6-85cc-afe2af2a169b.png)

Someone can help me. Thanks!

**Comment by joaomoreno** [comment]
This issue was moved to ikappas/vscode-phpcs#14
