### ISSUE TITLE
my terminal command line is showing 2 paths simultaneously?

### ISSUE THREAD

**Issue by jon117oneill** [microsoft/vscode#89003]
Issue Type: <b>Bug Report</b>

My terminal path shows 2 different paths. One written normally in a white text in the terminal, separated by a "&" and then followed by a very long path written in blue.

`PS C:\PythonProjects\Ex_Files_Learning_Python>` & `"C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe" "c:/PythonProjects/Ex_Files_Learning_Python/Ex_Files_Learning_Python/Exercise Files/Ch2/helloworld_start.py"
`
what is causing the 2nd path to show up, it has never happened before.
link to my screenshot: https://i.stack.imgur.com/QYzvV.png

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jon117oneill** [comment]
so my python executable path is showing along with my files path. why? and how can i remove the python executable path from showing

**Comment by sbatten** [comment]
@jon117oneill is this happening every time you open a terminal or just when you run your python code with the play button/shortcut/command?

**Comment by jon117oneill** [comment]
Hey Steven. 
I tried it in different terminals and spent a few hours trying to fix it. It’s changed my terminal path (unfortunately got slightly longer)
Changing terminals doesn’t fix thisAnd also stays every time I run my code. 
I updated the first local file path to be shorter. But the pythons interpreter executable location (in blue) is still unchanged and I’m not sure why it’s showing to begin with 


Thank you,JonSent from Yahoo Mail for iPhone


On Tuesday, January 21, 2020, 11:04 AM, SteVen Batten <notifications@github.com> wrote:


@jon117oneill is this happening every time you open a terminal or just when you run your python code with the play button/shortcut/command?

**Comment by sbatten** [comment]
@jon117oneill are you saying that this issue is occurring in your external terminals (not the terminals in VS Code)?

**Comment by jon117oneill** [comment]
Oh. I’m sorry. I’m still kinda new to this. I haven’t tried it in an external terminal. I thought you meant something else. However last time I ran code earlier that day through my windows terminal (not in case code) it wasn’t showing both paths. I haven’t since tried it when this issue occurred 


Thank you,JonSent from Yahoo Mail for iPhone


On Tuesday, January 21, 2020, 11:41 AM, SteVen Batten <notifications@github.com> wrote:


@jon117oneill are you saying that this issue is occurring in your external terminals (not the terminals in VS Code)?

**Comment by sbatten** [comment]
@jon117oneill okay thanks, can you try opening a terminal in VS Code with extensions disabled? `F1 > Reload with Extensions Disabled`. Does this terminal have the issue?

**Comment by jon117oneill** [comment]
I can try this in about 3 hours when I get home. Is that ok?


Thank you,JonSent from Yahoo Mail for iPhone


On Tuesday, January 21, 2020, 11:46 AM, SteVen Batten <notifications@github.com> wrote:


@jon117oneill okay thanks, can you try opening a terminal in VS Code with extensions disabled? F1 > Reload with Extensions Disabled. Does this terminal have the issue?

**Comment by jon117oneill** [comment]
I don’t know what this did. But I can’t run my code. It’s just the power shell terminal now. So no python obviously. Can’t tell if it’s any different. 


Thank you,JonSent from Yahoo Mail for iPhone


On Tuesday, January 21, 2020, 11:46 AM, SteVen Batten <notifications@github.com> wrote:


@jon117oneill okay thanks, can you try opening a terminal in VS Code with extensions disabled? F1 > Reload with Extensions Disabled. Does this terminal have the issue?

**Comment by sbatten** [comment]
@jon117oneill thanks for running the command. this looks like the intended behavior of the python extension. the behavior you are seeing is contributed by the the python extension. if you have questions about the behavior, feel free to file an issue at https://github.com/microsoft/vscode-python
