### ISSUE TITLE
Menu issues in Linux (menu items hide)

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#8901]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-28-generic

Steps to Reproduce:
1. Open VSCode
2. Click on a menu
   - see how the window icons (close, minimize, maximize/restore) flicker and are exchanged to app name (usually they stay if you open the menu), just as if the focus goes to an other window.
   - sometimes the "View" menu closes right after opening, but works normal if changing from another menu point to it.

I also had it, that I opened a "New Window" where then the "File" Menu was completely missing.

In the previous version there was the "View" Menu missing after running VSCode for a while. Restart fixed that.

There seems to be a problem with the Unity Menu (global menu) in general.

**Comment by joaomoreno** [comment]
Are you maybe using Linux inside a VM?

**Comment by DasJott** [comment]
Nope. Natively running on a Tuxedo Laptop.

**Comment by DasJott** [comment]
Still the same in 1.3.1 Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae

**Comment by Tyriar** [comment]
I haven't seen anything like this on Ubuntu 16.04 using arc-theme. Do you have any non-standard packages/customizations that affect the UI? Have you played with `unity-tweak-tool` for example?

**Comment by DasJott** [comment]
Didn't happen for a long time now. No double menu entries or missing ones.
What still happens is the window buttons (close, minimize, maximize) disapper on menu click, which differs to all other applications on ubunty with unity (when maximized).

**Comment by bpasero** [comment]
@DasJott  could you give our insider release a try to see if this issue is fixed? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by DasJott** [comment]
Will do tomorrow, thanks!

**Comment by westy92** [comment]
I have also seen the "File" or other menus missing as well as duplicate "Go" menus appearing after opening a new window on Ubuntu.  I haven't created an issue because it can't seem to nail down specific steps to reproduce it.

I did, however, just achieve multiple "Go" menus and a missing "Go" menu with vscode version 1.5.2 on Ubuntu Unity 15.10.

**Comment by bpasero** [comment]
Yes I also see this from time to time and basically since day 1.

**Comment by DasJott** [comment]
Sorry, I will try the preview release today. There were some difficulties I could not do that by now.

**Comment by DasJott** [comment]
Actually I could not seem to find preview releases. But for the update from today:

Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27

I can tell, that the window buttons still disappear on menu click, but on the first following mouse move they come back. No stopper at all, but I was simply wondering why this behaviour differs to all other software on Ubuntu 16.04 with Unity.

The double or missing menu entry thing didn't appear for a long time now.

**Comment by bpasero** [comment]
@DasJott 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by DasJott** [comment]
Correct URL was http://code.visualstudio.com/insiders

Installed and tested.

Sadly exactly the same. I even made videos to show, what I mean.
[Videos.zip](https://github.com/Microsoft/vscode/files/489446/Videos.zip)

The insider was initially german for me (system language), the normal one I switched back to english.

**Comment by DasJott** [comment]
I just got the "view" menu entry missing here again!

Usually I have connected two monitors to my laptop. I disconnected them and reconnected an other one in another office.
Then I noticed the "View" menu was missing.

So, something happens when switching displays in Ubuntu.

**Comment by bpasero** [comment]
Thanks for trying this issue seems to be still valid in Electron 1.3.x.

**Comment by DasJott** [comment]
Hey, today it is the help menu missing!

I currently have 3 instances of vscode running. One of them isses the help menu. I opened the window, the menu was there. I opened a project folder, the menu disappeared.

I just opened another one and loading another project in there, and that window got TWO help menus!
Closed it and did the same thing again, resulting in just one help entry again.

Something weird is going on here.

**Comment by Tyriar** [comment]
I had this happen to me with the help menu today for the first time (I've noticed at least).

![image](https://cloud.githubusercontent.com/assets/2193314/21542635/09c4fcb0-cd74-11e6-97d5-c9b0a36ee6f5.png)

I dropped window focus, brought it back and the Help menu was still missing. Then I closed the window and focused my other VS Code Insiders window and it had all the menus present.

**Comment by eghojansu** [comment]
I am using Ubuntu 16.04 LTS and visual code installed below.

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

This issue affect on me too. It happen after I do following action.

- Run "Show Desktop" or "Cmd + D".
- Maximize visual code and I got this issue. 

It is really annoying. I have to restart visual code when this issue comes to me. :(

May be this is because Compize issue?

**Comment by bpasero** [comment]
Please reopen if you still see this with VSCode 1.26+.

**Comment by rtosman** [comment]
Could this be re-opened? I have never seen it before, but as soon as I upgraded to 1.27.2 the "Tasks" menu disappeared.
