### ISSUE TITLE
No extension working, No IntelliSense or autofill working...

### ISSUE THREAD

**Issue by mehmc** [microsoft/vscode#89017]
Issue Type: <b>Bug</b>

I was having this problem that none of my extension was working, no IntelliSense or autofill suggestion, like I'm typing in a dead text editor.
So I reinstalled my vscode and all the extensions again. Without closing the vscode once everything was working fine. But when I close and relaunched vscode everything stop working again. It's like I'm coding on a simple notepad which shows no IntelliSense or autofill (Note:- this happens when I once closed the vscode, before closing it everything was working fine).
I'm working on react, JS... My extension of react-snippets is also not working as when i type 'imr' vscode is supposed to show me dropdown autofill menu to import react, but it does not show anything.
Any solution will be appreciated...

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.08GB free)|
|Process Argv|D:\Projects\crwn-clothing|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.0.14
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.10
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|3.18.0
vscode-react-native|msj|0.14.0
html5-boilerplate|sid|1.0.3
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.2.4
vscode-icons|vsc|9.7.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mehmc** [comment]
I figure out that by disabling and then re-enabling my extensions solve the issue... But again when I relaunched vscode after closing I have to do this trick again...

But this is not a solution, I provide this information to let you know more about the issue. Hope you can help me out

**Comment by hasenov** [comment]
i've exact same problem!

**Comment by jrieken** [comment]
This is likely one extension that going mad, e.g block the whole extension host process and thereby preventing any other work from happening. When this happens try : F1 > Running Extensions > Start Extension Host Profile (the dot-inside-circle button in the upper right). Let the profiler run for a few seconds and share the results here.

**Comment by mehmc** [comment]
Can you clarify, which results?
Extension Host Profiler keeps on running... Doesn't show any log or error

**Comment by mehmc** [comment]
> I figure out that by disabling and then re-enabling my extensions solve the issue... But again when I relaunched vscode after closing I have to do this trick again...
> 
> But this is not a solution, I provide this information to let you know more about the issue. Hope you can help me out

The above trick is also not working now, I don't know why it worked previously...
In addition some extensions like Prettier-code formatter,  GitLense are working fine... Just the IntelliSense and auto-fill while typing is not working (vscode don't show any dropdown suggestion while coding - like you are typing on a simple notepad).

**Comment by jrieken** [comment]
> Extension Host Profiler keeps on running... Doesn't show any log or error

You press the button again the bottom (which is the a filled circles again) and then you press the Save-button in the same toolbar

**Comment by mehmc** [comment]
Do I have to share the .cpuprofile file?

**Comment by jrieken** [comment]
Two options: 1) share it here 2) open in chrome dev tools and analyse it yourself. 

And needless to say that the .cpuprofile-file only has value when it was captured while extensions weren't working.

**Comment by ArchI3Chris** [comment]
I want to add something to the extensions problem.

First of all, another problem with extensions not working has been around in April last years.

Secondly, I have problems with extensions too, but another kind.

I was in the middle of writing Lisp code, when suddenly indent-rainbow started acting up and highlighting some lines in white and not stopping to do it, even when completely removing the lines and inserting a new one in the same place. The whole line was highlighted in white.

After restarting VSC at least TWO extensions stopped working entirely. These are not only indent-rainbow but also Bracket Pair Colorizer. I've made no upgrades, no changes, nothing. I was just in the middle of writing code.

Since I've tried a few things like disabling and enabling, reinstalling, upgrading the whole system and rebooting... nothing helped. They are just gone and don't work anymore. Furthermore, upon restarting VSC also syntax highlighting changed and highlights that have been there before is now white text. Like called functions for example.

So, there is something fishy going on with extensions again.

**Comment by ArchI3Chris** [comment]
Interesting. while writing the comment I noticed that there is a new version of Bracket Pair Colorizer. After installing Bracket Pair Colorizer 2 (and disabling the former), it seems I'm back to normal and also indent-rainbow seems to be back working for now.

**Comment by mehmc** [comment]
I still don't know what was the issue. But what matters is that vs code is back again and working perfectly 🙂...
