### ISSUE TITLE
Change default shortcut of "Go to File"?

### ISSUE THREAD

**Issue by mntolia** [microsoft/vscode#89016]
Currently the default shortcut key for "Go to File" is CTRL + E which is also the default shortcut key to go to the end of the line in a terminal. If I don't reassign the key it opens the "Go to File" menu when I press CTRL + E. Maybe this could be changed?

**Comment by Tyriar** [comment]
Yes this is the only workaround for this, unfortunately ctrl+e was an established shortcut well before the terminal existed.
