### ISSUE TITLE
ImportError: No module named site when starting code in terminal after Python 3.8 was installed on MacOS

### ISSUE THREAD

**Issue by nikolaj-lisberg-hansen** [microsoft/vscode#89013]
Issue Type: <b>Bug</b>

## FIxed issue with having both Python 3.8 and 2.7 by adding these lines in 
~/.zshrc and ~/.bash_profile

alias python=python3
alias pip=pip3
unset PYTHONPATH 
unset PYTHONHOME 

## Root cause is Visual Studio code bash script, that is used to start the app from a Terminal. The dependency on Python in bash script, could be avoided in 
Applications/Visual Studio Code.app/Contents/Resources/app/bin/code

#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# Workaround for "ImportError: No module named site" with both python 2.7 and 3.8 and zsh in MacOS Catalina instead of bash
# Fix is not to use Python but just standard bash to resolve symbolic links
# --- Remove lines related to python: 
## CONTENTS="$(dirname $(dirname $(dirname $(realpath "$0" ))))"

# --- Start fix: Add standard bash logic for resolving symbolic links
# Get code symbolic link /usr/local/bin/code symbolic link
CODE="${BASH_SOURCE[0]}"
# Find Contents path in /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
CONTENTS=`ls -dal $CODE | awk '{ print substr($11 " " $12 " " $13,0,length($11 " " $12 " " $13)-length("/Resources/app/bin/code"))}'`
# --- End fix

ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|-psn_0_225335|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.9.0
python|ms-|2020.1.58038

</details>

**Comment by sbatten** [comment]
please start by filing this issue in the python repo https://github.com/microsoft/vscode-python

**Comment by joaomoreno** [comment]
The Python code we have there is compatible with both 2 and 3. If you see an error it might be because you have a broken Python installation. Can you confirm?
