### ISSUE TITLE
Leading whitespaces are reformatted when using block indention

### ISSUE THREAD

**Issue by Huseriato** [microsoft/vscode#89011]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a code block, where the beginning is not aligned to the tab space size (ex. 4), example:
```
            $data_query = $database->query("
              select id, name
                from exampletable
               order by c_name, i_id
               limit 100
            ");
```
The SQL-Query is key-aligned.

2. Select the block and press TAB
3. The block is now aligned to match the tab space size

Does this issue occur when all extensions are disabled?: Yes

In my opinion block indention should add/substract the set tab space size to alle selected lines but should not reformat the code. There should be at least a setting for this.

**Comment by alexdima** [comment]
I think you would want to use `"editor.useTabStops": false`

**Comment by Huseriato** [comment]
Hello,

no, that's not what I want. This setting is currently false. So the tabstop setting defines how many white spaces are added when pressing tab. As I described, the whole lines are reformatted, when pressing tab on a selected block. The issue is real.

**Comment by alexdima** [comment]
Hmm, is this happening for a specific language or happening in all language? 

I believe there is some auto-indent code running on paste. Could you try to configure `"editor.autoIndent": "advanced"` instead of the default `"editor.autoIndent": "full"` ?

**Comment by Huseriato** [comment]
It's happening in any language (also NO language). Make a new file, no need to save. Type:

```
Hello
 World
  This
   Is
    A
     Test
```

Now select the whole text and press TAB.

**Comment by alexdima** [comment]
@Huseriato 

Just use `"editor.useTabStops": false` like I said in my initial comment:

### `"editor.useTabStops": true`
![Kapture 2020-01-24 at 15 28 12](https://user-images.githubusercontent.com/5047891/73076328-2c876300-3ebe-11ea-875c-821fbaa1c432.gif)


### `"editor.useTabStops": false`
![Kapture 2020-01-24 at 15 29 43](https://user-images.githubusercontent.com/5047891/73076426-60628880-3ebe-11ea-83f3-273e33d1bbd6.gif)

What exactly is not working for you, can you please provide clear steps and clear expected vs actual results.

**Comment by Huseriato** [comment]
I've cleared my settings.json - I think there was something that prevented the useTabStops setting from working correcly. My fault, cannot reproduce anymore.
