### ISSUE TITLE
Test: launch configuration sorting and grouping

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#89018]
Refs: https://github.com/microsoft/vscode/issues/82332

- [x] anyOS @joaomoreno 
- [x] anyOS @bpasero

Complexity: 3

Launch configurations and compounds now support the field `presentation`.
Make sure that:
* Using the `presentation` field you can sort, group and hide configurations and compounds as expected
* Description and naming of presentation fields makes sense
* All the debug ux resepect the presentation field as it changes: dropdown in debug viewlet and quick pick after typing `debug `

**Comment by joaomoreno** [comment]
:clap:
