### ISSUE TITLE
search.useIgnoreFiles is defaulted to true

### ISSUE THREAD

**Issue by Tatsujinichi** [microsoft/vscode#89019]
- VSCode Version: 1.41.1
- OS Version:

Steps to Reproduce:

1. Fill in .gitignore
2. Find in files
3. Files not found
4. Broken assumption about said searched term not existing in files.

Does this issue occur when all extensions are disabled?: Yes/No

Find in files should be **Find in files**  Not some abstract concept like "Find in project", or "Find in workspace" or find In "things git cares about".  That may be the only use case you understand, but  is not the case for everyone.  Find in files should do exactly what it says, FIND IN FILES.  That's how it has always worked (if you have programmed for more than just a few years), and that's how it should continue to work.  Fancy IDEs usually supply their own special search functionality where this functionality would be expected.  But not in FIND IN FILES*. (*May not find in files)

Please do not default this to on when your only file search is Find in files, which is EXPECTED to be a raw directory search.  It should be opt in, other wise anyone who didn't use your other favorite free editor will not know that this is now the **new** and **unexpected** behavior.

**Comment by roblourens** [comment]
This has been the case in vscode for quite a while, and I think it is actually what most people are expecting. I'm not planning on changing it.
