### ISSUE TITLE
jsx markup bug with empty tag

### ISSUE THREAD

**Issue by scarych** [microsoft/vscode#89020]
Issue Type: <b>Bug</b>

Hi, VSCode developers!
I've found some bug with visualization of markup of JSX using empty tags to decorate structures
When I use tag `</>` everything after it begin to look as regexp syntax 
screen with proof https://yadi.sk/i/g1fy_4Eiy12CCQ
Changing of color theme hadn't helped.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|8.00GB (2.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-stylesheet-formatter|dba|0.2.0
nunjucks-vscode-extensionpack|dou|0.0.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.18.0
nunjucks-template|ese|0.2.1
duplicate|gee|1.0.1
beautify|Hoo|1.5.0
vue|jcb|0.1.5
svn-scm|joh|2.4.2
solidity|Jua|0.0.64
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-html-format|moh|0.0.3
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
nunjucks|ron|0.2.3
markdown-preview-enhanced|shd|0.5.1
vscode-icons|vsc|9.7.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by scarych** [comment]
for example something like this

```jsx
                    {userPhoto.cropped_file_id &&
                        <>
                        <div className="col-4">
                            <button type="button" className="btn btn-primary form-button"
                                onClick={editPhotoHandler}
                            >
                                <IntlMessages id="settings.photo.edit" />
                            </button>
                        </div>

                        <div className="col-2">

                            <button type="button" className="btn btn-secondary form-button"
                                onClick={removePhotoHandler}
                            >
                                <Fa.FaTimes />
                            </button>
                        </div>
                        </>
                    }
```

the problem may be solved if use single line comment after closing tag `</> ///`

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically `vscode-babel-coloring`

**Comment by scarych** [comment]
Nope, thans doesn't reproduce with all disabled extensions. And the bug perhaps in extension `vscode-babel-coloring`.
Issue closed. Thank you
