### ISSUE TITLE
Horizontally resizing the integrated terminal messes up the viewport on Windows

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#8902]
- VSCode Version: Code - Insiders 1.3.0-insider (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-06T13:46:20.448Z)
- OS Version: Windows 10

Steps to Reproduce:

1.
![gif](https://cloud.githubusercontent.com/assets/8591065/16679662/dec61f70-451b-11e6-8196-ae3bc45e8f2e.gif)

2.

**Comment by Tyriar** [comment]
Duplicate #8336
