### ISSUE TITLE
Add multiple cursors from "find"

### ISSUE THREAD

**Issue by SUMUKHA-PK** [microsoft/vscode#89027]
I found myself needing this a lot, probably many have.

When I need to add multiple cursors to a certain type of code, I should be able to search for it using `Ctrl + F` and then be able to deploy cursors in all the places I found my required string.

PS: Interested in solving this if possible. Noob to the repo, would need a lot of help for the same.

**Comment by IllusionMH** [comment]
<kbd>Alt</kbd>+<kbd>L</kbd> if you are on Windows
