### ISSUE TITLE
A way to skip punctuation when moving cursor by word

### ISSUE THREAD

**Issue by suhr** [microsoft/vscode#89025]
Suppose you have an expression: `self.as_type(&ty).map(|ty| TypeRow { path, ty })`.

In EMACS, you can effectively navigate this expression by words, because it considers punctuation as separator characters, just like spaces.

In VS Code though, navigation by words is less effective, because it treats a sequence of punctuation characters as words.

It would be great to have an option to allowing more EMACS-like behavior.

**Comment by alexdima** [comment]
Let's track in #88872
