### ISSUE TITLE
Formatting javascript document puts the brackets on new line indented

### ISSUE THREAD

**Issue by mattti-post** [microsoft/vscode#89021]
- VSCode Version: 1.41.1
- OS Version: Kubuntu 16.04

Steps to Reproduce:

Actual formatting:

```
let abc = new Abc(
    {
        x: 1
    });
```

Desired formatting:

```
let abc = new Abc(
{
     x: 1
});
```

I was able to achieve the desired formatting by setting `editor.autoIndent` to `keep`. But it is working only when typing. When I try to format the document or selection, the brackets always end up indented.

Any online javascript beautifier I tried, which has an option to put the brackets on new line, makes it done well.

Am I missing some javascript or editor setting?

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Try using one of the formatting extension for more advanced formatting options like that

**Comment by mattti-post** [comment]
Thanks I will. 

Can you at least tell me where does this default formatting come from? In my first comment I wrote that

> Any online javascript beautifier I tried, which has an option to put the brackets on new line, makes it done well

From this perspective it really seems awkward to format the curly braces indented by default.

Thanks anyway.
