### ISSUE TITLE
[feature] mirror cursor: add support for other languages

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#89032]
atm it works only in html https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor

but there are other languages that also use html in their markup ex.`blade, php, twig`.

so is it possible to have like a config where you add the language id that you want the feature to be supported ? 

this way its global and users don't need to wait for language extension authors to update their packages.

**Comment by octref** [comment]
> so is it possible to have like a config where you add the language id that you want the feature to be supported ?

Not really. This also depends on #88424.
