### ISSUE TITLE
JavaScript with @ts-check and jsdoc shows different errors than using tsc directly

### ISSUE THREAD

**Issue by jdart** [microsoft/vscode#89039]
- VSCode Version: 1.41.1
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Clone demo repo https://github.com/jdart/ts-js-jsdoc-vscode and open in vscode
2. Open Foo.js
3. Set language to Typescript
4. Observe errors
5. Run `npx tsc --noEmit --p jsconfig.json` and notice no errors

![Screen Shot 2020-01-21 at 10 50 09 AM](https://user-images.githubusercontent.com/118674/72825950-9218ec80-3c3d-11ea-8294-0b68c8978230.png)

This might be a configuration issue but I can't figure it out. If I switch to the javascript language I don't get errors but I don't type hinting either.

I tried setting the ts version to use the version in node_modules but got the same result.

**Comment by mjbvz** [comment]
To check JS code, don't change the language to `typescript`. Leave it as JavaScript and just [enable type checking](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript) in the file or the project

**Comment by jdart** [comment]
Thanks @mjbvz, In my example project if I switch to javascript, and put `"checkJs": true` in my compilerOptions, vscode doesn't show errors that tsc reports.

![Screen Shot 2020-01-21 at 1 03 36 PM](https://user-images.githubusercontent.com/118674/72834435-75d17b80-3c4e-11ea-8a81-32c33975bf26.png)

**Comment by mjbvz** [comment]
Hmm, not able to repo using that example repo in VS Code insiders:

![Screen Shot 2020-01-21 at 2 35 18 PM](https://user-images.githubusercontent.com/12821956/72849307-45440e80-3c5b-11ea-92a8-53ef4eba84db.png)

Any extra steps?

**Comment by jdart** [comment]
I had set javascript.validate.enable to false for a flow project.... removing that and restarting vscode got things working. Thanks for the help!
