### ISSUE TITLE
Cannot launch `code` from terminal

### ISSUE THREAD

**Issue by rcho** [microsoft/vscode#89037]
- VSCode Version: 1.41.1
- OS Version: Mojave 10.14.6

Steps to Reproduce:

1. launch `code` from terminal

```code .                                                              
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code: line 10: ./MacOS/Electron: No such file or directory 
```

Does this issue occur when all extensions are disabled?: Yes

Found (closed) related issues:
https://github.com/microsoft/vscode/issues/5168
https://github.com/microsoft/vscode/issues/3790

I looked at the above related issues but this issue doesn't seem to be resolved from me. I've tried blowing away my $PATH and resetting as well as reinstalling VS Code and using the Command Palette to re-add it to my $PATH

FWIW my system python is 2.7 

```
/usr/bin/python -V                                            
Python 2.7.16
```

**Comment by joaomoreno** [comment]
What does `which code` return?

What are the contents of `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code`?

**Comment by rcho** [comment]
```
which code
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
```

```
cat "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

**Comment by joaomoreno** [comment]
Strange, the `CONTENTS` seems to be empty for you. :thinking: 

Can you add the following to the script? After `function realpath()...`:


```
echo $0
echo "$(realpath "$0)"
```

**Comment by rcho** [comment]
everything magically started working today, I suspect the cause may have been some endpoint security background process on my (work issued) machine since I literally have not changed anything in my env nor has my version of VS Code installed changed in the meantime.  

sorry about that thanks for the quick response.
