### ISSUE TITLE
showing wrong result in ipynb files 

### ISSUE THREAD

**Issue by Aerma7309** [microsoft/vscode#89033]
def pat(n):
    for i in range(n):
        for j in range(n+i):
            print(" ",end='') if j<n-1-i else print('*',end='')
        print()

the above code is showing wrong results in vscode but it is getting correct result in jupyter-notebook
![Screenshot from 2020-01-21 21-07-04](https://user-images.githubusercontent.com/47671638/72819787-e18a0780-3c93-11ea-8728-cf8d527aa004.png)
![Screenshot from 2020-01-21 21-07-57](https://user-images.githubusercontent.com/47671638/72819795-e3ec6180-3c93-11ea-8d51-6d7b40968455.png)

**Comment by sbatten** [comment]
@Aerma7309 please file this with the python extension
