### ISSUE TITLE
minimap is incorrect when using 3-digit colors in settings

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#89043]
Issue Type: <b>Bug</b>

1. Open TS file in code repo
2. Wait for the TS language features to start.

:bug: -> all white text in my theme is invisible in minimap

![image](https://user-images.githubusercontent.com/6561887/72832123-1a48c300-3c39-11ea-8bfa-b889ef86319e.png)

VS Code version: Code - Insiders 1.42.0-insider (2832fc3c234daeda025f205a862703ba7eee6a10, 2020-01-21T11:35:55.424Z)
OS version: Windows_NT x64 10.0.19041

**Comment by alexdima** [comment]
I can reproduce with the following settings:
```
{
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{ "scope": "variable", "settings": { "foreground": "#333" } },
		]
	},
	"workbench.colorTheme": "Default Light+"
}
```

![image](https://user-images.githubusercontent.com/5047891/72844284-7b55b280-3c9c-11ea-9ef2-aab33fcca5c1.png)

@aeschli if I comment out `textMateRules`, the minimap renders OK. I believe there might be some kind of problem with the color map (the minimap uses the color map array).

**Comment by alexdima** [comment]
It looks like the color `#333` is somehow left in this shorthand form, which is not understood by the `<canvas>` fill context.

@aeschli What do you believe, would it make sense for the theme service to normalize/validate the colors?

@sbatten a workaround could be to use 6 hex characters for your color customizations.

**Comment by sbatten** [comment]
@aeschli I would expect this to be fixed in today's insiders based on timestamp but am still seeing it 
![image](https://user-images.githubusercontent.com/6561887/73086079-c16d6a80-3e84-11ea-8e0d-4850698e29c8.png)

as i said before, it seems to be white text that is missing, so i used inspect scopes command on one token in case it helps.

![image](https://user-images.githubusercontent.com/6561887/73086197-0c877d80-3e85-11ea-88a0-65dc85858614.png)

**Comment by alexdima** [comment]
@sbatten What settings do you have around theming / token customizations ?

**Comment by sbatten** [comment]
```
	"editor.tokenColorCustomizations": {},
	"workbench.colorCustomizations": {
		"[LaserWave]": {
			"editor.lineHighlightBorder": "#74dfc455"
		}
	},
	"workbench.colorTheme": "LaserWave"
```

**Comment by alexdima** [comment]
@aeschli I can reproduce. The steps are to use the theme LaserWave without any customizations.

**Comment by aeschli** [comment]
The problem is https://github.com/microsoft/vscode/issues/89600.
