### ISSUE TITLE
Theme underline blinking in Insiders

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89042]
- Use a theme with underlines like Monaco
- Edit, move cursor around, notice the underline decorations blinking a lot

![Jan-21-2020 10-25-07](https://user-images.githubusercontent.com/323878/72831761-5a5b7600-3c38-11ea-96ae-0a7aaed58d1b.gif)

I've been noticing this lately, and this doesn't happen as much in Stable. Would anything in this area have changed lately?

**Comment by roblourens** [comment]
Related to this, when I type there are lots of syntax highlighting glitches, for example it often feels like the page is blinking orange at me:

![Jan-23-2020 11-34-14](https://user-images.githubusercontent.com/323878/73017280-5d8b6900-3dd4-11ea-9fad-0bd89b1b3d48.gif)

**Comment by rebornix** [comment]
thanks for reporting!

/duplicate https://github.com/microsoft/vscode/issues/76642
