### ISSUE TITLE
html css class completion  plugin bug, vs code not work, only close

### ISSUE THREAD

**Issue by blusoul** [Microsoft/vscode#8904]
- VSCode Version: 1.3 
- OS Version: windows 10

Steps to Reproduce:

1. vs Code 
2. tips  html css class completion; Fetching css rules from css files please wait 
![image](https://cloud.githubusercontent.com/assets/8167270/16680554/f10d7f92-4521-11e6-96e7-5b5e44875569.png)

**Comment by joaomoreno** [comment]
This issue was moved to Zignd/HTML-CSS-Class-Completion#19
