### ISSUE TITLE
Missing debug console icon

### ISSUE THREAD

**Issue by jmbockhorst** [microsoft/vscode#89041]
There seems to be a debug console icon missing to the right of the gear icon. When you hover over the space the tooltip says "Debug console" and you can click to open the debug console, but there is no icon.

![MissingIcon](https://user-images.githubusercontent.com/44308390/72828092-95ae7280-3c41-11ea-8351-4737f2b01e1a.png)

Version: 1.42.0-insider (user setup)
Commit: d72b2d372f5024a9193b37a3830bbbc459c0ef1b
Date: 2020-01-20T05:33:26.563Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19536

**Comment by isidorn** [comment]
Thanks for filling this issue. Pushed a fix and you can pick it up in tomorrow's (Thursday) vscode insiders.
