### ISSUE TITLE
Seeding Search view from Find Widget

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89048]
Issue Type: <b>Bug</b>

I sometimes want to seed the Search view with what I am searching for in the editor's find widget. I feel like at some point this used to work, but now it seems to only seed based on the selection in the editor even if the find widget has focus.

VS Code version: Code - Insiders 1.42.0-insider (c1793c0fc77b570baa079f8198112ff355e75249, 2020-01-21T16:53:39.890Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.34GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Eric/code/microsoft/vscode|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JacksonKearl** [comment]
What commands/buttons are you using exactly?

**Comment by eamodio** [comment]
1. Open the editor find (`actions.find` - `ctrl+f`)
1. Type a query (regex or something to make it easy to see it is seeding with the editor selection, not the find widget)
1. Run `workbench.action.findInFiles` - `ctrl+shift+f` and see that it will (well might be, depending on its state) be seeded with the editor selection (typically the first match) rather than the query

**Comment by JacksonKearl** [comment]
this is for the Search viewlet, rather than the Search Editor?

**Comment by eamodio** [comment]
Yeah, viewlet

**Comment by JacksonKearl** [comment]
I can't reproduce your expected behaviour on Stable on Mac or Windows... @roblourens do you know anything about this? I don't recall seeing in the code anything to seed from the editor's find widget. I know there's `editor.find.globalFindClipboard` and `search.globalFindClipboard` so if those are both enabled this should happen, but those are MacOS specific.

**Comment by roblourens** [comment]
No, we haven't ever had that functionality as far as I know

**Comment by eamodio** [comment]
Hrm, I swear it used to work... but maybe I was just getting lucky in that the cases where I wanted it the query matched the first result.
