### ISSUE TITLE
Highlighting text should also highlight its counterpart in Watch dropdown

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#89044]
Issue Type: <b>Feature Request</b>

Highlighting text already highlights other instances of said text across an entire file in the main text editor window. It would also be beneficial to extend this logic to the Watch dropdown. Text highlighted in the main editor window would highlight equal text in the Watch dropdown and vice versa.

VS Code version: Code - Insiders 1.42.0-insider (2832fc3c234daeda025f205a862703ba7eee6a10, 2020-01-21T11:35:55.424Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog candidates and we might add this in the future. Thanks
