### ISSUE TITLE
Alignment issues with quick pick

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89049]
![image](https://user-images.githubusercontent.com/2193314/72836436-7c0d2b00-3c41-11ea-9ca4-8d6d98d9313b.png)

I see the following problems:

- "4 selected" is not vertically aligned and the "Turn on"
- The the S in selected should probably be lower case?
- The "Turn on" button is taller than the text input

**Comment by chrmarti** [comment]
On Windows ('4 Selected' needs to move down 1px):
![image](https://user-images.githubusercontent.com/9205389/72881567-47f93f00-3d01-11ea-8632-d799aeca2d03.png)

**Comment by devanshj** [comment]
I guess this is already [fixed](https://github.com/microsoft/vscode/pull/96772#issuecomment-625653947)
