### ISSUE TITLE
Alt + B not working

### ISSUE THREAD

**Issue by myfyrefly** [microsoft/vscode#89053]
Issue Type: <b>Performance Issue</b>

It started sometime this morning. Any time I try to run my code in my broswer using Alt+B or even right clicking and asking it to open in default browser, nothing happens. The tool bar at the top gets highlighted with I use alt+b, but that's it. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.02GB free)|
|Process Argv|C:\Users\feart\Desktop\Activity Practice\floats\floats.html|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    83	 18936	code main
    0	   183	  9956	   window (Keyboard Shortcuts - Visual Studio Code)
    0	    69	 13984	     extensionHost
    0	    30	  3976	       "C:\Users\feart\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\feart\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=13984
    0	    31	  8536	       "C:\Users\feart\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\feart\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=13984
    0	    53	 17672	       "C:\Users\feart\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\feart\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=13984
    3	   252	 12716	   gpu-process
    0	    72	 13284	   shared-process
    0	    13	 14828	   electron-crash-reporter
    3	    66	 17096	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension it seems likely this relates to the open-in-browser extension you have installed.
