### ISSUE TITLE
EROFS Error

### ISSUE THREAD

**Issue by kcmodev** [microsoft/vscode#89056]
- VSCode Version: 1.41.1
- OS Version: MacOS 10.15.2 (19C57)

Steps to Reproduce:

1. Attempt to save any file

Does this issue occur when all extensions are disabled?: Yes

I get the following error whenever trying to save any file. I have tried everything. 

> Failed to save 'Untitled-1': Unable to write file (Unknown (FileSystemError): Error: EROFS: read-only file system, open '/Untitled-1.py')

I changed the permissions on the destination folder. I gave it all the permissions it requested. I tried running it on an administrator account. Downloaded and tried the Insider version. Tried a java and c++ file. It won't save anything. Searched everywhere for an answer before asking here and nothing I have tried has helped. Including uninstalling and removing all traces of the program I could find then reinstalling.

Any help or guidance would be greatly appreciated. Thank you.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kcmodev** [comment]
Yes I did it on an updated insiders version just last night. Also again this morning. Still same error. I also tried opening from a different directory with full read write execute permissions and still getting the same error.

**Comment by kcmodev** [comment]
My apologies, it appears I have been just trying to save this in the incorrect place. I got it to work by doing a "Save As" to a different location. I apologize for the inconvenience.
