### ISSUE TITLE
Let read-only editors show problems

### ISSUE THREAD

**Issue by buremba** [microsoft/vscode#89057]
I'm working on [an extension](https://marketplace.visualstudio.com/items?itemName=rakam.rakam-data-modeling) that lets users compile [Jsonnet](https://jsonnet.org) files and view them as read-only JSON files.

I would like to add support for JSON Schema to the JSON outputs so that if the output is not valid, VSCode highlights the errors in the output created as a virtual document by the custom content provider.

However; VSCode doesn't seem to validate read-only files so JSON schema validator doesn't work on virtual documents. When I convert the scheme to `untitled`, the validation does work but since the JSON outputs are idempotent (generated from Jsonnet files), I don't want to give the users the ability to edit/save the JSON output as the output is irrelevant.

I believe that the validation is useful for the read-only files as well. It would be great if we can disable the code actions and make the validation at least optional depending on how the extension creates the virtual documents.

**Comment by aeschli** [comment]
The JSON language server validates all documents of language id `json` and `jsonc`.
The problem view shows the errors, but not the editor.

**Comment by buremba** [comment]
I see, thanks for the info @aeschli. That explains why I started seeing the errors when I installed the extension `usernamehw.errorlens`.

**Comment by bpasero** [comment]
I wouldn't even know where to start looking to do this, I have no clue how the editor decides to show errors or not. Back to other folks.

**Comment by alexdima** [comment]
Currently, read only editors do not render validation decorations. The rationale back when we added this was that users would get frustrated because they see errors that they cannot fix.

**Comment by alexdima** [comment]
I have pushed an internal editor option `renderValidationDecorations` that can be `'editable' | 'on' | 'off'`. The default is `editable`.

`editable` means that validation decorations are rendered only in editable editors. `on` and `off` should be clear.

The option is not user facing, we can make it so or the workbench can decide that in VS Code we want to render validation decorations in read only editor. 

@bpasero ?

**Comment by bpasero** [comment]
@alexdima nice, I am trying to adopt that but could it be that your change broke any decorations showing up now? Can you check out of master?

**Comment by alexdima** [comment]
@bpasero Sorry about that, I had my boolean logic wrong :D

**Comment by bpasero** [comment]
Nice. This is now enabled for all text editors, but not for these which always had custom editor config overrides:
* log viewer
* output panel
* preferences editor

![image](https://user-images.githubusercontent.com/900690/73052115-9edb5180-3e84-11ea-9712-b84d232c938d.png)

**Comment by buremba** [comment]
Wow! I didn't expect you to fix the issue that fast. Thanks, folks. :)

**Comment by bpasero** [comment]
@buremba would be great if you could verify this fix on next week Monday when we have an insiders build out with this included.

**Comment by buremba** [comment]
Sure @bpasero !

**Comment by bpasero** [comment]
@buremba   You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by buremba** [comment]
@bpasero thanks for checking in, it works just fine!
