### ISSUE TITLE
DAP errors when setting breakpoints are not respected

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89059]
I wanted to validate logpoint breakpoint syntax in js-debug when setting the breakpoint. Plenty of times I have tried setting a breakpoint and only later realized it didn't get hit because I was missing a quotation mark. However it appears that errors in `setBreakpoints` aren't handled. I send back this error:

```
{id: 9231, format: 'Unexpected token 'const'', showUser: true}
```

It doesn't get shown to the user, and I see this in the window log:

```
[2020-01-21 15:35:26.072] [renderer6] [error] Error processing setBreakpoints: undefined: Error: Error processing setBreakpoints: undefined
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2875:728)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2875:159
    at async R.sendBreakpoints (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5486:707)
    at async Promise.all (index 1)
    at async j.sendToOneOrAllSessions (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5517:343)
    at async j.enableOrDisableBreakpoints (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5514:374)
```

**Comment by connor4312** [comment]
you can verify this by pulling down the branch in the linked PR, and then setting a logpoint like `{return const a = b + c}`

**Comment by roblourens** [comment]
I think this is the case for some other DAP requests too? You might just have to handle it yourself by sending an OutputEvent.

**Comment by isidorn** [comment]
@connor4312 Thanks for filling this issue.
The problem was that we were nowhere respecting the `showUser` flag in the error response and thus those errors were not being shown to the user.
Now we respect that flag and as soon as we get the response with that flag we show it to the user.

Please try it out and let me know how it behaves. Thank you!

**Comment by connor4312** [comment]
Hm, I see the error now shown property in the console log of the workbench...

![image](https://user-images.githubusercontent.com/2230985/74053451-b04a5080-4990-11ea-96e3-a08f4ad7b3a9.png)

But I don't see any message displayed to me. This is the full request/response:

```json
{
  "command": "setBreakpoints",
  "arguments": {
    "source": {
      "name": "main.js",
      "path": "/Users/copeet/Github/vscode-pwa/demos/node/main.js",
      "sourceReference": 0
    },
    "lines": [
      23
    ],
    "breakpoints": [
      {
        "line": 23,
        "logMessage": "hello {'world}"
      }
    ],
    "sourceModified": false
  },
  "type": "request",
  "seq": 12
}

{
  "seq": 117,
  "type": "response",
  "request_seq": 12,
  "command": "setBreakpoints",
  "success": false,
  "body": {
    "error": {
      "id": 9231,
      "format": "Invalid or unexpected token",
      "showUser": true
    }
  }
}
```

**Comment by connor4312** [comment]
Nevermind, I was behind on insiders, I had to restart twice to get the very latest version. It works here :)

**Comment by isidorn** [comment]
Thanks for verifying and leting me know!
