### ISSUE TITLE
TSX syntax is broken after as statement

### ISSUE THREAD

**Issue by lijunle** [Microsoft/vscode#8905]
- VSCode Version: 1.3.0
- OS Version: Windows Server 2012

Steps to Reproduce:

1. See the `propertyPane` syntax is gray out.

  ![image](https://cloud.githubusercontent.com/assets/1296500/16679864/8a390696-451d-11e6-90ff-f6b6a9c4f1c9.png)

2. Remove the `as ReactElement` statement, the `propertyPane` syntax is OK.

  ![image](https://cloud.githubusercontent.com/assets/1296500/16679870/94e4e858-451d-11e6-8f87-363909ea1b6f.png)

**Comment by KalleOtt** [comment]
Duplicate with issue #8045

**Comment by lijunle** [comment]
@KalleOtt Thank you! I am closing this one.
