### ISSUE TITLE
My VSCode auto indenting after save

### ISSUE THREAD

**Issue by igekaratas** [microsoft/vscode#89050]
![fullsizegif](https://user-images.githubusercontent.com/28317005/72838637-47579e80-3c56-11ea-9d8a-563dce0eb83a.gif)

Hello everyone. 
What is the solution for this?
Thanks.

If the gif not showing Link: https://imgur.com/JHSCIWY

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you sure you don't have editor.formatOnSave or editor.codeActionsOnSave enabled in your Settings?

**Comment by igekaratas** [comment]
> /needsMoreInfo
> 
> Are you sure you don't have editor.formatOnSave or editor.codeActionsOnSave enabled in your Settings?

Yes, that was my problem. I solved it with uncheck the editor.formatOnSave. Thank you.
