### ISSUE TITLE
Integrated PowerShell Terminal -ShowWindow switch for Get-Help Cmdlet not working

### ISSUE THREAD

**Issue by jbourgoin** [microsoft/vscode#89052]
Issue Type: <b>Bug</b>

In VSCode's integrated PowerShell try the following commands:

PS> man get-command -ShowWindow
PS> get-help get-command -ShowWindow
PS> get-help get-command

The first two command should present a pop up window for whatever Cmdlet you're wanting help with, and no window is presented.

The third command does output Cmdlet help to the terminal window.

Expected: -ShowWindow switch should present the Cmdlet's help documentation in a separate window. 

Actual: The command is executed and nothing happens.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.28GB free)|
|Process Argv|C:\scripts\Measure_Parallelism-SVR-SQL6Deploy.ps1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
mssql|ms-|1.8.0
remote-wsl|ms-|0.41.7
powershell|ms-|2020.1.0
material-icon-theme|PKi|3.9.2

</details>

**Comment by sbatten** [comment]
Please start by filing an issue with the powershell extension https://github.com/powershell/vscode-powershell
