### ISSUE TITLE
[comments API] unnecessary markdown autocomplete when writing a comment

### ISSUE THREAD

**Issue by evangrayk** [microsoft/vscode#89051]
We have our own extension using the Comments API for code review. When typing a reply to a comment thread, it seems to show autocomplete for markdown. This is not always useful, and is actually inaccurate for our comment rendering (we use a different format which we convert into markdown to render in the comments API).

It would be nice to have a config setting or API setting to disable the markdown autocomplete inside comments.

<img width="554" alt="Screen Shot 2020-01-21 at 12 00 15 PM" src="https://user-images.githubusercontent.com/1762690/72838685-a1039d00-3c45-11ea-8735-eaa0e3728b8e.png">

**Comment by ian-h-chamberlain** [comment]
Just wanted to add to this, there are already existing configuration options for completion of specific filetypes. I think it would make sense for the markdown comment editor to respect the configuration that already exists, e.g. in `settings.json`:

```json
{
    "[markdown]": {
        "editor.quickSuggestions": false,
        "editor.snippetSuggestions": "none",
        "editor.tabCompletion": "off"
    },
}
```

Alternatively, perhaps a new filetype like `[markdown-commenteditor]` could be added to support different settings in the comment box vs a normal Markdown document..
