### ISSUE TITLE
Menu uses unkown command warning

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8906]
1. Build vscode-darwin out of latest (commit b410792) 
2. Notice warnings in console

![screen shot 2016-07-08 at 09 26 31](https://cloud.githubusercontent.com/assets/1926584/16680355/27ca700a-44ee-11e6-99c9-ae224c7488c5.png)

**Comment by bpasero** [comment]
@alexandrudima fixed this I think.

**Comment by bpasero** [comment]
No, I am still seeing it.

**Comment by alexandrudima** [comment]
I have reverted my commit
