### ISSUE TITLE
Option to split sidebar subwindows

### ISSUE THREAD

**Issue by dbechrd** [microsoft/vscode#89064]
This feature is a drastically simplified subset of the infamous: https://github.com/microsoft/vscode/issues/10121 which I believe would be much more realistic to implement while still providing a measurable increase in productivity:

I would like the ability to show two sidebars at the same time, one on the left, one on the right, which allow me to independently select different subwindows. If synchronization is an issue with having two sidebars, instead, allow me to take a subset of subwindows from the left sidebar and display them in the right sidebar instead (e.g. left sidebar has Explorer, Search, Extensions, right sidebar has Debug).

This is the layout I would like to be able to achieve:
![image](https://user-images.githubusercontent.com/707367/72864376-a2a28480-3c88-11ea-9d74-30d1de1c4ae0.png)

**Comment by dbechrd** [comment]
The vscodebot duplicate is not a duplicate, but after digging a few issues deep I did find two other similar requests:
https://github.com/Microsoft/vscode/issues/45866
https://github.com/Microsoft/vscode/issues/26777

These seem like sufficient duplicates to close to issue if you like, but the screenshot may provide some value as a mock-up.

**Comment by sbatten** [comment]
@dbechrd thanks for finding the duplicates. this is definitely something we are considering when working towards a more flexible layout. keep an eye out for the next update for some progress in this space.
