### ISSUE TITLE
Cumulative change log across all extensions

### ISSUE THREAD

**Issue by jnesspro** [microsoft/vscode#89070]
The most of vsCode skills provided by extensions. So, that would be awesome to have an opportunity to collect change logs across all (or some selected) extensions filtered by some "seen" flag or "since last review" time

**Comment by gjsjohnmurray** [comment]
I wonder if it'd be possible to write an extension to do this?

**Comment by IllusionMH** [comment]
Should be possible - but hard to find stable source of info.
Some have CHANGELOG.md (should be linked in extension store) however some use GitHub Releases page ([example](https://marketplace.visualstudio.com/items/mrmlnc.vscode-scss/changelog) linked, but useless). This leads to a lot of questions where to pull info from (GitHub releases, other hosting, other file etc.) and looks like a lot won't have any info info :(

**Comment by jnesspro** [comment]
That's why I wrote an issue. Maybe it will be possible to make an Extension Change Log, or chengelog.md convention, or new separated release notice. 
I don't know how much value will this feature bring to vsCode community. If this is only my problem - yes, maybe I should write some sort of telegram bot, or make new rss feed
