### ISSUE TITLE
Not detecting the html file 

### ISSUE THREAD

**Issue by SwastiDahiya** [microsoft/vscode#89077]
Hi
Actually visual studio code is not detecting the html file. Its detecting other file perfectly let it be .css or c file but html file is not getting detected and its not even getting suggestions or auto completion.
Please tell me how to fix it . It will be really helpful
Thanks
![1](https://user-images.githubusercontent.com/53172313/72887824-6fb4cb00-3d32-11ea-8566-53ab3c3035be.jpg)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have any file association for HTML files? 
Example
```json
"files.associations": {
    "*.html": "plaintext"
}
```

**Comment by SwastiDahiya** [comment]
Hi
Thanks for the help i got it solved successfully. Now its working
absolutely fine.
Thankyou
