### ISSUE TITLE
Search for file with/by path

### ISSUE THREAD

**Issue by AndreyChursin** [microsoft/vscode#89076]
Issue Type: <b>Feature Request</b>

I pressed Ctrl+P and inserted the path (ex \modules\sale\lib\basketbase.php), but I did not get the result( http://joxi.ru/Q2KXNGkiwyQJjA )! 
If I insert "basketbase.php" - the same situation no result( http://joxi.ru/Rmz64NjTRjDNZm )! 

I think the search functionality should be more understandable. You probably need to implement a strict path or file name with quotation marks ("search" or 'search')

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.10240

**Comment by roblourens** [comment]
Please check whether any of the tips here are helpful: https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results
