### ISSUE TITLE
VS Code as syntax highlighter on a website like PrismJS but with VS Code themes and plugins

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#89078]
I'm using PrismJS for a long time now and have never thought about using something else (besides from that there isn't a better lib than PrismJS) but for my portfolio I thought it would be time to use something newer/more optimized and then, while editing my portfolio in VS Code, I had that idea:

> "Why can I not use VS Code as my code highlighter on my website, with my preferred theme and plugins to copy the code to the clipboard or something like that? This would be soo cool and people could have a button >Open in VS Code< and the code will open a new file with the correct syntax etc. :o"

So that is the idea but I guess the implementation will be much harder than I think 😄. Besides that, I guess a PrismJS plugin to allow VS Code themes in PrismJS or "open in VS Code" would be awesome as well.

Wonder what you are thinking about that.

**Comment by rebornix** [comment]
I think this is what you ask for https://github.com/octref/shiki
