### ISSUE TITLE
vscode automatically open the file cli.js

### ISSUE THREAD

**Issue by sunflower-zwf** [microsoft/vscode#89088]
Issue Type: <b>Bug</b>

This problem will occur in two cases. I recorded the problem in these two cases and made two gifs.
The first case is when vscode is not started, vscode will automatically start and open the cli.js file, as shown in the gif below.
![image1](https://raw.githubusercontent.com/sunflower-zwf/Image-Hosting-Service/master/1579696652908.gif)
The second is that when I use vscode normally, a new window will automatically open with the content of the cli.js file, as shown in the gif below.
![image2](https://raw.githubusercontent.com/sunflower-zwf/Image-Hosting-Service/master/1579696772000%20(1).gif)
I don't know why this problem occurs, I hope you guys can help me, thank you.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
code-gnu-global|aus|0.2.2
luatcode|che|0.22.0
path-intellisense|chr|1.4.2
code-runner|for|0.9.15
kite|kit|0.102.0
vscode-language-pack-zh-hans|MS-|1.41.2
python|ms-|2020.1.58038
cpptools|ms-|0.26.3-insiders3
korofileheader|OBK|4.5.2
vetur|oct|0.23.0
indent-rainbow|ode|7.4.0
java|red|0.55.1
markdown-preview-enhanced|shd|0.5.1
lua|sum|0.15.4
pdf|tom|0.5.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.20.2
vscode-icons|vsc|9.7.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please review the advice in #69373 and #88432. Both of those issues were closed without resolution because the OPs apparently didn't follow up with the requested information.
