### ISSUE TITLE
Integrated terminal can not be opened, flash back

### ISSUE THREAD

**Issue by zwq00000** [Microsoft/vscode#8908]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide detailed steps of how to reproduce the issue.
