### ISSUE TITLE
Propagate font feature settings to terminal

### ISSUE THREAD

**Issue by AlsoScratch** [microsoft/vscode#89085]
- VSCode Version: 1.41.1
- OS Version: macOS 10.15.2

Like #87994 but now involves the terminal.
<img width="693" alt="Screenshot 2020-01-22 at 8 43 47 PM" src="https://user-images.githubusercontent.com/48752273/72895424-3ee78c80-3d58-11ea-917a-b0a532e7a726.png">

**Comment by Tyriar** [comment]
The terminal has a separate set of font settings, it inherits some of the editor's values if they're not set though.

**Comment by AlsoScratch** [comment]
What is the `settings.json` code for the terminal then?

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/73010680-adaffe80-3dc7-11ea-8025-6122b1ba85b9.png)

**Comment by octref** [comment]
@Tyriar I think he's asking for `editor.fontLigatures` to be propagated as well.

**Comment by Tyriar** [comment]
Ligatures -> https://github.com/microsoft/vscode/issues/34103
