### ISSUE TITLE
MacOS: Multiple monitors

### ISSUE THREAD

**Issue by ljyanesm** [microsoft/vscode#89081]
Issue Type: <b>Bug</b>

Open more than one window, place each window on a different monitor, unplug second monitor, plug second monitor again.

Behaviour: Only one window appears visible, the second one can only be reached by "Mission Control".

Expected behaviour: Both windows are visible in their last location on each monitor.

Monitor configuration: Secondary above primary

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ljyanesm** [comment]
Maybe related to #86771

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders
