### ISSUE TITLE
Code color doesn't change accordingly to its type

### ISSUE THREAD

**Issue by GeorgeFlorian** [microsoft/vscode#89083]
- VSCode Version: 1.41.1
- OS Version: Linux Mint 19.1

Steps to Reproduce:

1. Copy code or comment code
2. See if it changes color or not

[![scxz.png](https://i.postimg.cc/0N1bzbLy/scxz.png)](https://postimg.cc/87w13Pp2)

**Comment by alexr00** [comment]
Does the issue still happen if you disable all installed extensions?
Please provide a copy/pastable example.

**Comment by GeorgeFlorian** [comment]
> Does the issue still happen if you disable all installed extensions?
> Please provide a copy/pastable example.

It started working as it should after a PC restart.
