### ISSUE TITLE
Powershell Integrated Console throws error on long lines

### ISSUE THREAD

**Issue by CatalinSoare** [microsoft/vscode#89082]
- VSCode Version: 1.41
- OS Version: 10.0.18363

Steps to Reproduce:

1. In Visual Studio Code, open up the Terminal, and make sure you are running Powershell Integrated Console.
2. Start typing, or paste a line in the terminal so that your current line goes over 138 characters
3. You will get an error similar to this:
    An error occurred while reading input:

> System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
> Parameter name: top
> Actual value was 17.
>    at System.Console.SetCursorPosition(Int32 left, Int32 top)
>    at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
>    at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__103.MoveNext()

**Comment by sbatten** [comment]
Please start by filing this issue with the PowerShell extension https://github.com/powershell/vscode-powershell
