### ISSUE TITLE
Linux publisher is broken since ~15/01

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89086]
It seems to be break when fetching credentials from the key store.

**Comment by chrmarti** [comment]
Reading the identity using `curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net' -H Metadata:true` failed with `"AADSTS700027: Client assertion contains an invalid signature`.

Removing the user assigned identity from the ACI and adding it back (using the Azure Portal) seems to have fixed it.
