### ISSUE TITLE
code folding breaks on large (ish) files

### ISSUE THREAD

**Issue by genghis-bunny** [microsoft/vscode#89094]
- VSCode Version: insiders 1.42.0
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

We are writing a vscode extension that makes heavy use of fluent interfaces/method chaining and often in large files.
Code folding is highly desirable for our use case but the out-of-the-box code folding in vscode can omit expected folds towards the end of the bigger files. 

To illustrate the following code snippet has been repeated ad nauseam in a file with our custom file extension.

![unfolded](https://user-images.githubusercontent.com/26346956/72898547-3a9d7e00-3d1c-11ea-917f-48002631d508.jpg)

When folded , all the lines up to 14983 and 14987 fold as expected but the lines 14995 and 14999 and after do not fold as expected.

![folded](https://user-images.githubusercontent.com/26346956/72898664-6fa9d080-3d1c-11ea-8996-6db927f709e7.jpg)

We have tried setting "editor.largeFileOptimizations": false (as per https://github.com/Microsoft/vscode/issues/34240) but this does not seem to improve the situation on our test using vscode (insiders 1.42.0) on a windows 10 machine. We have tried a "Folding Strategy" setting of "auto" and "indentation". We have not yet written a custom code folder for our extension because we do not know if the same effect will be seen after we implement it ("auto" for our language/file extension).

 To reproduce a test file is available following and it is a *.txt file of approximately 15,000 lines and is 410.5 kb in size. The same effect is seen in files with *.txt extension as is in our custom file extension. The tested file size does not seem to be too excessive at 410.5 kb and the code folding is very responsive it just does not seem to precipitate the desired result towards the end of the file.

Steps to Reproduce:

1. Cut and paste following into a text file

https://elasticbeanstalk-eu-west-1-828833189199.s3-eu-west-1.amazonaws.com/test.txt

2. Execute command "Fold All" and compare lines 14983 and 14987 with lines 14995 and 14999

Many thanks in advance.

**Comment by aeschli** [comment]
You are hitting the max limit of folding regions (added for performance reasons). Unfortunately it is hardcoded and not configurable. We have issue https://github.com/microsoft/vscode/issues/72994 for that.
