### ISSUE TITLE
VSCodeInsider_DefaultSettingforNewEnvironment_AI4D: (Code - Insiders/ 'Type to narrow down results. 3 Results') The LocalizedControlType property must not be null.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#89096]
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
OS Version: Win10

**Application:** Code - Insiders has the following accessibility issue that needs investigation.

**Issue Details**
Provide a string for the LocalizedControlType property that concisely describes the control's type.

**Element path:** 'Type to narrow down results. 3 Results'

**To Reproduce and How to Fix guidance:** Please open the attached Accessibility Insights for Windows Test File (*.a11ytest) to reproduce the error in Accessibility Insights for Windows.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. 

screenshot
![image](https://user-images.githubusercontent.com/55909580/72899674-7fd9a400-3d4c-11ea-9a23-9f0db1b128ff.png)

**Same issue observed for the below scenario:**
**1.Default Setting**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control and click on it .
5.Select any existing environment and then again click on the "+" button and navigate till "Default setting" ,click on it.

**2.Customer Setting**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control and click on it .
5.Select any existing environment and then again click on the "+" button and navigate till "Custom setting" ,click on it.

**3.Select Plan**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "Select Plan" button beside the  "VS ONLINE" control and click on it.

**4.Create New Environment**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Click on "Visual Studio Online" and navigate till "Remote Explorer" ,click on it.
4.Navigate till "+" button beside the  "VS ONLINE" control  and click on it.

**Comment by isidorn** [comment]
Will not fix
