### ISSUE TITLE
Terminal cd command

### ISSUE THREAD

**Issue by ChiscaAlex** [Microsoft/vscode#8909]
- VSCode Version: latest
- OS Version: win 10

Steps to Reproduce:

1. Open terminal
2. Type cd
3. Press TAB to get folder suggestions
4. Get a folder and add /
5. Press TAB again to get folder suggestions ( from inside the selected folder )

This will list the folders from the folder that you are currently in, and not the folders from /FOLDER SELECTED/

**Comment by f111fei** [comment]
I use windows7. `cmd.exe` also have this problem. I think it's an issue of windows os.

**Comment by f111fei** [comment]
Oh. I see. you should add `\` rather than `/`

**Comment by Tyriar** [comment]
Yes this is how cmd.exe behaves.
