### ISSUE TITLE
Extension API: vscode.workspace.findFiles() documentation needs to be updated

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#891]
The findFiles documentation has backslashes (\) instead of forward-slashes (/) in its example. I've found that using backslashes doesn't work as expected, but forward-slashes does. Forward-slashes would make sense (since only Windows uses backslashes in filepaths), but not sure if the documentation is wrong or the API is wrong.

**Comment by jrieken** [comment]
We use `/` in the doc because glob-pattern with slash don't work well with JS block comments. Despite, search should handle slash and back-slash unless I am mistaken

**Comment by bpasero** [comment]
@jrieken actually we support both slash and backslash when matching the path, but the glob expression requires forward slashes. I don't think backslashes in glob patterns are common, I took the same approach as https://github.com/isaacs/node-glob#windows

**Comment by jrieken** [comment]
ok. I will fix the doc
