### ISSUE TITLE
还我代码

### ISSUE THREAD

**Issue by buger404** [microsoft/vscode#89101]
你可爱的IDE觉得我的代码太美味然后把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了把它吞了！！！！！！！把它吞了！！！！！把它吞了！！！！！吞了！！！！！吞了！！！！！吞了吞了吞了吞了吞了吞了吞了吞了吞了吞了吞了吞了吞了

**Comment by rebornix** [comment]
Could you please provide more information like how your code was "eaten" by the editor and reproduce steps?

**Comment by buger404** [comment]
oh **sorry** , I was inflamed with passion yesterday . 
in fact I don't know what happended , just .......
yesterday I was using Visual Studio Code, when I finished my program ,
I opened Unity and launched my game . But suddenly Unity told me there was 10 errors because one of my code file was missing .

**I was so angry !**

I opened the folder and check the missing code file , the size of it was 0kb , yes , it's empty .
The last modification date of it was **10 min before I opened Unity** , at that time I was coding .
Maybe the **add-in** caused it ? or **Git** ? or .... **the editor itself** ?
It's my first time to face this problem , I was rather baffling .

**Comment by buger404** [comment]
Oh ..... heavens ... just now my code was missing again when I switch back to the editor from another window , but I found that Ctrl+Z worked .

**Comment by rebornix** [comment]
@buger404 do you run into this issue with all extensions disabled?
