### ISSUE TITLE
I can't install extensions

### ISSUE THREAD

**Issue by matheuscardoso** [Microsoft/vscode#8910]
- VSCode Version: 1.3.0
- OS Version: Ubuntu 14.04 - 64bits

**Comment by alpox** [comment]
Same here
VSCode Version: 1.3.0
OS Version: Windows 7 - 64 bit

**Comment by mdob2k** [comment]
Same here, after updating to the current June release (1.3.0) I am unable to install extensions.
Seems as if previously installed extensions don't show up, too.

OS: Ubuntu 16.04 x64

**Comment by joaomoreno** [comment]
#8877 #8859

**Comment by joaomoreno** [comment]
Everyone, can you still reproduce with the downloadable archive?

[32bit](https://az764295.vo.msecnd.net/stable/e724f269ded347b49fcf1657fc576399354e6703/VSCode-linux-ia32-stable.zip)
[64bit](https://az764295.vo.msecnd.net/stable/e724f269ded347b49fcf1657fc576399354e6703/VSCode-linux-x64-stable.zip)

**Comment by alpox** [comment]
I had this problem with Windows, this seems to be a Linux build.

**Comment by joaomoreno** [comment]
@alpox Do you have any extensions installed? Which?

**Comment by alpox** [comment]
@joaomoreno I have installed (And they are shown):

- TypeScript (0.3.1)
- PHP Debug (1.9.3)
- Crane - PHP Intellisense
- C# (1.2.1)

**Comment by joaomoreno** [comment]
@alpox 

Can you set a breakpoint in `extensionsWorkbenchService.ts:163` and trigger the bug? You can achieve this in the Developer tools, clicking `Ctrl-O` and typing `extensionsWorkbenchService` to find the file. I'm interested in the the contents of the `t` array, specifically if there are any extensions in there with an `undefined` `manifest` property:

![image](https://cloud.githubusercontent.com/assets/22350/16684470/850fc2da-4505-11e6-82ba-9dec9634600c.png)

**Comment by alpox** [comment]
The manifests are defined for me:
![printscreen](https://cloud.githubusercontent.com/assets/12485194/16685748/77e2067e-450d-11e6-999b-d125189b1e09.png)

But i have an error in my Console:
![printscreen_console](https://cloud.githubusercontent.com/assets/12485194/16685762/93d31008-450d-11e6-9627-1c8d49a20d19.png)
I hope it helps!

**Comment by alpox** [comment]
Alright, i tracked the issue down and it works now. It was my mistake :smiley: I defined HTTP_proxy and HTTPS_proxy environment variables in the system and VSCode made use of them.

Have a nice day!

**Comment by joaomoreno** [comment]
OK that's good to know, thanks!
