### ISSUE TITLE
Multicursor option "Match whole word" should default to the type of initial select. 

### ISSUE THREAD

**Issue by renthraysk** [microsoft/vscode#89103]
If the initial selected text is a whole word then the match whole word open should be enabled. If not a single whole word is selected then next whole word option should be disabled.

**Comment by alexdima** [comment]
The behaviour you desire is there, you just need to start without a selection. Simply move the cursor on a word and press Ctrl+D / Cmd+D ... The selection expands to the word under the cursor and "word match" is now on for Ctrl+D / Cmd+D.

I think the behavior you suggest might break use-cases where the word is manually selected exactly to get "word match" off. I know I use it in e.g.

```
const selections = this.getSelections()!;
const first = selections[0];
const firstPosition = first.getPosition();
```

Oftentimes it happens that I copy/paste a pattern like the above, where there are two related variables. Then I wish to rename:

```
const selections = this.getSelections()!;
const first = selections[0];
const firstPosition = first.getPosition();
const first = selections[0];
const firstPosition = first.getPosition();
```

I then select `first` and press Ctrl+D two times and type `last` and I get:
```
const selections = this.getSelections()!;
const first = selections[0];
const firstPosition = first.getPosition();
const last = selections[0];
const lastPosition = last.getPosition();
```

I then go ahead and fix the index and I got everything done quickly. I believe the suggestion you make would break this use-case.
