### ISSUE TITLE
During inertial scrolling on precision touchpad if Ctrl button is pressed, the font-size is increased of the editor

### ISSUE THREAD

**Issue by vipiny35** [microsoft/vscode#89102]
When I scroll though editor with precision touchpad and the editor window is still scrolling and then if I press the Ctrl button while it is still scrolling the font size increase or decreases depending on the scroll direction.

**Comment by rebornix** [comment]
Ctrl+Scroll is handled as zooming the workbench by default so when the editor is scrolling and you press ctrl, the zooming will happen automatically. You can turn it off by setting `editor.mouseWheelZoom` to false.

**Comment by vipiny35** [comment]
I think it will be better to scroll the workbench when scrolled with ctrl button pressed and not while in the scrolling motion.
