### ISSUE TITLE
Changing terminal not possible when current terminal not available

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#89107]
Issue Type: <b>Bug</b>

If, for whatever reason, the configured terminal programm is not available the terminal pane closes immidiately. It is therefor not possible to select another working terminal programm.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19541

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.3.1
typo3-typoscript|ben|0.2.0
vscode-intelephense-client|bme|1.3.7
vscode-eslint|dba|2.0.15
githistory|don|0.4.13
vscode-gitignore-syntax|dun|0.1.2
vscode-firefox-debug|fir|2.6.1
vscode-mysql|for|0.4.0
vscode-pull-request-github|Git|0.14.0
vscode-github|Kni|0.30.3
gitignore|mic|1.0.1
vscode-scss|mrm|0.9.0
remote-wsl|ms-|0.41.7
debugger-for-chrome|msj|4.12.5
vscode-yaml|red|0.6.1
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
You can press ctrl+p, type "term " and select any terminal, there's also the focus next/previous terminals commands.

This state you're describing isn't meant to happen though, are you using ctrl+` to open the terminal as that should just toggle the pane and only try to create a terminal if there aren't any available?

**Comment by theking2** [comment]
I show my predicement in a video https://youtu.be/-oZptjePuWY

**Comment by Tyriar** [comment]
You only have a single terminal, no good one to switch to. The message is telling you to install WSL so you can do that to fix it:

![image](https://user-images.githubusercontent.com/2193314/73010776-e64fd800-3dc7-11ea-99cf-a4c2c054f171.png)

Run switch default shell command to switch to something that's installed:

![image](https://user-images.githubusercontent.com/2193314/73010813-f962a800-3dc7-11ea-914d-fa1a0b03a57b.png)
