### ISSUE TITLE
Better refactor preview icon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89105]
With https://github.com/microsoft/vscode/commit/18c69d801317970b60c6e4a19aa03615f118e480 and for https://github.com/microsoft/vscode/issues/77728 I have added new icons to group/ungroup changes by type. I took those icons form the cpp-extensions but there are two things left

* add them to the codicon font
* make them look more like our icons (they seem stronger)

<img width="1027" alt="Screenshot 2020-01-22 at 15 57 44" src="https://user-images.githubusercontent.com/1794099/72904930-f9af6480-3d2f-11ea-8170-417ce8034bb9.png">

**Comment by misolori** [comment]
@jrieken it appears that our icon team worked on these icons, so they do match our style, this is the set of them by the C++ team:

![image](https://user-images.githubusercontent.com/35271042/72918006-c18d2f00-3cf9-11ea-953e-9ef8efb9e585.png)

I can add these two icons to our Codicon library.

**Comment by misolori** [comment]
🙅‍♂️ bad bot

**Comment by jrieken** [comment]
Thanks @misolori 

> @jrieken it appears that our icon team worked on these icons, so they do match our style, this is the set of them by the C++ team:

What I meant is the stroke thickness which looks better when all icons are codicons 👇 

<img width="215" alt="Screenshot 2020-01-23 at 09 05 46" src="https://user-images.githubusercontent.com/1794099/72966572-93722280-3dbf-11ea-97c5-33464bcdc5db.png">

**Comment by misolori** [comment]
@jrieken can you post verification steps for this? thanks!

**Comment by jrieken** [comment]
This testplan-item has an extension attached: https://github.com/microsoft/vscode/issues/89335. When being run, the icon will show, then verify that the stroke lines match those of other icons

**Comment by bpasero** [comment]
Seeing this:

![image](https://user-images.githubusercontent.com/900690/73278323-b7809a00-41eb-11ea-83c3-3738d7c9de0f.png)


Seems legit.
