### ISSUE TITLE
hangs on search.action.focusNextSearchResult if no search result avaiable

### ISSUE THREAD

**Issue by APerricone** [microsoft/vscode#89106]
- VSCode Version:1.41.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. clear the result results (no result or no search done)
2. execute the search.action.focusNextSearchResult action

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Wow, thanks!
