### ISSUE TITLE
Add an option to have '\n' not to be escaped on debug console 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#89114]
Full context here: https://github.com/microsoft/vscode/issues/73845

Basically the Python extension would love have the ability to have '\n' characters to be interpreted as actual new lines on the debug console, instead of printing '\n'. Would it be possible to have a setting for this? 😊

Thanks!

**Comment by isidorn** [comment]
Yes, we can introduce a setting. Assigning to next milestone February so we tackle then.
Thanks!

**Comment by isidorn** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/73845
Which we will tackle in February.
