### ISSUE TITLE
Code coloring and live preview don't work for HTML with multiple line breaks in Markdown files

### ISSUE THREAD

**Issue by jaredbcook** [microsoft/vscode#89116]
- VSCode Version: 1.42.0-insider
- OS Version: macOS 10.14.6 (Darwin x64 18.7.0)

Steps to Reproduce:

1. Open any markdown (.md) file
2. Set VS Code to use tabs or 4 (or more) spaces for indentation
3. Add inline HTML with any number of nested tags (e.g.: `<ul><li>content</li></ul>`)
4. Add at least 2 line breaks before the opening tag of one of the inner tag sets (e.g.: before the `<li>` in the code from step 2
5. Open the markdown preview pane
6. Notice that code coloring and live preview are not working correctly

Does this issue occur when all extensions are disabled?: **Yes**

<img width="966" alt="markdown-html-line-break-issue-bad" src="https://user-images.githubusercontent.com/1649519/72924617-de842b00-3d16-11ea-9485-023e542b2133.png">

**Comment by jaredbcook** [comment]
It seems that this issue only happens when using tabs or more than 3 spaces for indentation. Editing issue description to clarify.

**Comment by mjbvz** [comment]
This is standard markdown behavior: indents blocks of text are used for code block. Try it on GitHub:

```md
Start example

<div>

    <p>bla</p>

</div>
```

--- renders as---

Start example

<div>

    <p>bla</p>

</div>
