### ISSUE TITLE
intelli sence not working in javascript

### ISSUE THREAD

**Issue by Naggertooth** [microsoft/vscode#89115]
Issue Type: <b>Bug</b>

Hi guys
I typed some things in js
And didnt see buble with suggestions
I pressed CTRL + SPACE
And didnt see anything exept LOADING

In Atom all works good

I tryed reinstall vscode and reinstall all components of vscode includes extentions
Still intellisence not working at all (For sys and user versions)

![image](https://user-images.githubusercontent.com/24671211/72924204-9807ee00-3d61-11ea-980a-7a7a7a182937.png)
here must be `props`
and that is after click CTRL + SPACE

---

Also after installing extention vscode-language-babel i see objects like this in atom one dark theme
But may be that is not your problem
![image](https://user-images.githubusercontent.com/24671211/72924377-e1f0d400-3d61-11ea-8083-126be18240a2.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.54GB free)|
|Process Argv|D:\projects\swap.react|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|1.5.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.15
es7-react-js-snippets|dsz|2.5.0
vscode-styled-components|jpo|0.0.28
vscode-language-babel|mgm|0.0.25
vscode-language-pack-ru|MS-|1.41.2
atom-keybindings|ms-|3.0.6
color-highlight|nau|2.3.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Naggertooth** [comment]
In latest stable build without any extensions 100% yes

**Comment by mjbvz** [comment]
Please try the insiders build

**Comment by bsizzle74** [comment]
I'm seeing the same issue on the latest insiders build (with or without all extensions disabled).
@Naggertooth - do you see "Initializing JS/TS language features" in the status bar of vs code when you get this issue? On my insiders build that status never goes away.

Version: 1.42.0-insider (user setup)
Commit: ee803826ad8f16534bbf72fa463306ebcb1e7ee6
Date: 2020-01-22T15:27:51.183Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19546

It does not happen on the latest stable build for me. It works as expected.

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19546

**Comment by Naggertooth** [comment]
Actually no
![image](https://user-images.githubusercontent.com/24671211/72960042-7b010880-3dbd-11ea-843f-6f348e6d7ffe.png)
But i saw infinite "Initializing JS/TS language features" before i start reinstalling it all yesterday
<details><summary>Version</summary>
Insiders build<br>
Version: 1.42.0-insider (user setup)<br>
Commit: ee803826ad8f16534bbf72fa463306ebcb1e7ee6<br>
Date: 2020-01-22T15:27:51.183Z<br>
Electron: 7.1.7<br>
Chrome: 78.0.3904.130<br>
Node.js: 12.8.1<br>
V8: 7.8.279.23-electron.0<br>
OS: Windows_NT x64 10.0.17763<br>
</details>

Also i found that exactly after start and initializing JS/TS in stable build i see bubble with suggestions
But if i wiped that expression and wrote it again - i see nothing and with CTRL+SPACE i see loading

![LOL VSCODE DEAD](https://user-images.githubusercontent.com/24671211/72960596-69b8fb80-3dbf-11ea-8430-b9a9fc5a3706.gif)


<details><summary>Version</summary>
Версия: 1.41.1 (system setup)<br>
Фиксация: 26076a4de974ead31f97692a0d32f90d735645c0<br>
Дата: 2019-12-18T14:58:56.166Z<br>
Electron: 6.1.5<br>
Chrome: 76.0.3809.146<br>
Node.js: 12.4.0<br>
V8: 7.6.303.31-electron.0<br>
ОС: Windows_NT x64 10.0.17763<br>
</details>

**Comment by tthorntone** [comment]
I am seeing the same issue, where "Initializing JS/TS language features" stays spinning forever. I am using:
Version: 1.42.0-insider (user setup)
Commit: c4d53a19df8799f5d49a4f49a6900c499e6fa27c
Date: 2020-01-23T05:39:57.148Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

Typescript version: 3.2.4 (**NOT VS Code's Version**)

Here's the "TypeScript" output:
[Info  - 16:19:20.154] Using tsserver from: c:\Users\tthornton\Documents\MIB\webClient\node_modules\typescript\lib
[Info  - 16:19:20.198] <main> Forking...
[Info  - 16:19:22.791] <main> Starting...
[Error  - 16:20:35.877] ReaderError
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at t.Reader.onLengthData (c:\Users\tthornton\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218987)
	at Socket.<anonymous> (c:\Users\tthornton\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 16:20:35.881] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (c:\Users\tthornton\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:217663)
	at t.Reader.onLengthData (c:\Users\tthornton\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218730)
	at Socket.<anonymous> (c:\Users\tthornton\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

This has just started happening within the past 3 or so days. 

**Note**: If I use VS Code's built in version, things work. This is not ideal though, because my project is targeting 3.2.

**Comment by mjbvz** [comment]
@Naggertooth So this issue is fixed when you use VS Code insiders?

@tthorntone Older TS versions have known bugs that could cause issues like that. The fix is to use a newer TS version but let me know if you still see this issue when using TS 3.8+

**Comment by Naggertooth** [comment]
@mjbvz yes, but I didn't check another pc or os

**Comment by mjbvz** [comment]
@Naggertooth Thanks for checking. let me know if you see this in the VS Code insiders builds or in VS Code 1.42 once it is released
