### ISSUE TITLE
comment codes within JSON 

### ISSUE THREAD

**Issue by coreyfeder** [microsoft/vscode#89118]
Issue Type: <b>Bug</b>

In the below JSON, everything following the `/*` is interpreted as a multi-line comment.

{
    'user-agent': 'python-requests/2.18.4', 
    'accept-encoding': 'gzip, deflate', 
    'accept': '\*/*', 
    'content-type': 'application/json'
}

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

**Comment by reconix23** [comment]
```
{
'user-agent': 'python-requests/2.18.4',
'accept-encoding': 'gzip, deflate',
'accept': '*/*',
'content-type': 'application/json'
}
```

this looks weird in vscode. 

I don't know much json. took a quick look.
examples on https://json-schema.org/ & https://json-schema.org/understanding-json-schema/basics.html#hello-world, https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.3 show only double-quotes being used.

I hope its not a hard requirement, didn't find anything to suggest it.

**Comment by alexr00** [comment]
This is not valid json because json requires double quotes, not single quotes:
```json
{
"user-agent": "python-requests/2.18.4",
"accept-encoding": "gzip, deflate",
"accept": "*/*",
"content-type": "application/json"
}
```
![image](https://user-images.githubusercontent.com/38270282/72968294-7f302480-3dc3-11ea-9716-1c95c2ef9352.png)
