### ISSUE TITLE
Git UI loses focus on message field once staging a file has been completed

### ISSUE THREAD

**Issue by mikkotikkanen** [Microsoft/vscode#8911]
- VSCode Version: 1.3.0
- OS Version: W7

Steps to Reproduce:
1. In Git UI, click file for staging
2. Start entering commit message before the staging has finished. Once the staging is complete, the message field loses focus interrupting the message writing.

**Comment by joaomoreno** [comment]
Not happening any more.

**Comment by mikkotikkanen** [comment]
What? Literally just happened today...

**Comment by joaomoreno** [comment]
Sure, you have 1.3.0 installed. Please update to a more recent version. We can't really fix old versions, can we?

**Comment by mikkotikkanen** [comment]
1.10.2 but sure, there seems to be newer version available so I guess that was fixed in the latest release?

**Comment by joaomoreno** [comment]
Can you still reproduce it in 1.10.2?

**Comment by mikkotikkanen** [comment]
Yep. Literally was writing commit message yesterday and had to click back to the box because it got unselected. Installing the new version now though.

**Comment by joaomoreno** [comment]
This is very strange, because I can't reproduce it.

**Comment by mikkotikkanen** [comment]
Cloud be that it was something else. Haven't really been following the issue that closely cos I developed a habit to wait for everything to be staged before writing a comment, but can't seem to reproduce it myself now neither.
