### ISSUE TITLE
Styled components with diferent colors of React Native components

### ISSUE THREAD

**Issue by walteribeiro** [microsoft/vscode#89124]
Issue Type: <b>Bug</b>

When I use components created with styled components the colors in file doesn't work equal React Native components.

VS Code version: Code - Insiders 1.42.0-insider (ee803826ad8f16534bbf72fa463306ebcb1e7ee6, 2020-01-22T15:27:51.183Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.15
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.18.0
vscode-styled-components|jpo|0.0.28
dotenv|mik|1.0.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.2
vscode-graphql|Pri|0.2.2
sass-indented|syl|1.7.3
full-react-snippets|wal|1.4.1
markdown-pdf|yza|1.4.1

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/10420735/72945954-34c78d00-3d5c-11ea-8d6c-ca87ada00f8e.png)

**Comment by aeschli** [comment]
I fixed the JSX colors (that was unintended) (https://github.com/microsoft/vscode/issues/88911)
