### ISSUE TITLE
Same place open other file 

### ISSUE THREAD

**Issue by Nallasivamk** [microsoft/vscode#89129]
Issue Type: <b>Bug</b>

Same place open other file  if i open first file next time open send file the same place open  but, first open file is misssing.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.99GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-keybindings|ms-|4.0.6

</details>

**Comment by reconix23** [comment]
screenshots please. also, can't understand you clearly, please re-phrase.

all I know is its something related to files. and
>first open file is missing.

**Comment by gjsjohnmurray** [comment]
Sounds like Preview Mode is confusing you. 

https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by sbatten** [comment]
agree with @gjsjohnmurray, thanks for the link there

@Nallasivamk if the documentation helps you understand, please close this issue. If not, please describe your issue further.
