### ISSUE TITLE
CSS lint says that a "float" property should have no effect with display: inline, yet it does?

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#8912]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

Create a div with the two CSS properties "display:inline" and "float:right". This will display an error in the CSS linter saying that the float property will have no effect however if you view this on a webpage you will see that the float is clearly working.

Example:
https://jsfiddle.net/d9utag4f/

**Comment by joaomoreno** [comment]
This issue was moved to CSSLint/csslint#664
