### ISSUE TITLE
Bug with int after Tab

### ISSUE THREAD

**Issue by hochan222** [microsoft/vscode#89128]
- VSCode Version: Version 1.41 
- OS Version: mac

Steps to Reproduce:

1. Setting Tab 4 space
2. Press int

Does this issue occur when all extensions are disabled?: Yes

I was setting Tab value 4 space.
However, I press Tab after int, vscode convert 1 space length instead of 4space length

**Comment by hochan222** [comment]
I have checked the above issues but the error is not resolved.

**Comment by reconix23** [comment]
hi! ignore the @vscodebot.

can repeat.

type `int`. pressed tab twice, then hit backspace to get desired outcome. the first tab press doesn't work.

----

if you press Enter then hit Tab, it will indent by 4 spaces.

**Comment by rmunn** [comment]
This behavior is as designed. When you have the tab set to insert spaces, it still behaves as if there were "tab stops". E.g., if I type `i` and then Tab, it inserts 3 spaces. If I type `in` and then Tab, it inserts 2 spaces. If I type `int` and then Tab, it inserts 1 space. Here's what I get (with an `x` after each tab to show you where it got to):

```
    x
i   x
in  x
int x
```

That's how the tab key is supposed to work, to let you more easily line up multiple columns of text.

**Comment by reconix23** [comment]
my bad, I didn't know about that. Today I learned.

---

for me, it doesn't make much sense at all. until you use (back)spaces and tabs in one file, that helps align text properly(aesthetics matter!), in a manner unlike using Tabs alone, that does feel a long winded way and downright weird way to do it.

I guess it comes down to the trite fact - **different people have different preferences**.

**Comment by sbatten** [comment]
I do not know the history, but notepad is not a code editor and doesn't care too much about this behavior. When writing code however, aligned indentation is important so the behavior @rmunn is as designed.
