### ISSUE TITLE
Workspace editirng service throws 'unknown folder'

### ISSUE THREAD

**Issue by justaskarvovskis** [microsoft/vscode#89138]
- VSCode Version: 1.41.1
- OS Version: Darwin x64 19.2.0 (macOS Catalina | 10.15.2)

Steps to Reproduce:
1. When you have vscode show "add folder", quit and the relaunch the app.
2. Click "add folder" (the bug doesn't appear when it says "open folder") and then click the new file icon.
This doesn't happen every time, but when it does the file should disappear after a second or two.

Does this issue occur when all extensions are disabled?: Yes

Explanation:
Okay so, when you just launch vscode (it mostly only happens when the app is just opened) and it shows "add folder" (it doesn't happen when it says "open folder") and when you add a folder, and then click the new file icon, the new file appears for a second and then disappears, and it becomes very annoying as then you have files that have weird names because it closes the name editing before you finish or even start typing. After a lot of testing, I've concluded that this bug only appears on MacOS Catalina, I did a clean install of both vscode and macos (Catalina 10.15.2 & Mojave 10.14.6) and the bug only appears on Catalina.

I've tried testing it on vscode insider, but I've encountered a bug (like not being able to remove folders) that didn't exactly let me reproduce the original bug.

I've also attached a full video demonstrating the bug.
https://youtu.be/P-fYd4_8h2Y

**Comment by isidorn** [comment]
This should be fixed in vscode insider. If you see a different issue in vscode insiders please report that one. Thanks

**Comment by justaskarvovskis** [comment]
@isidorn Alright, thank you, I will open a new issue for the bug on the vscode insiders. As well may I know what more information is needed?

**Comment by isidorn** [comment]
Actually no need for a new issue. Just comment here. Exact repro steps of insiders issues and waht is the issue. Thank you

**Comment by justaskarvovskis** [comment]
- VSCode Version: 1.42.0-insider
- OS Version: Darwin x64 19.2.0 (macOS Catalina | 10.15.2)

Steps to Reproduce:
1. Add folder with "add folder". (doesn't happen with "open folder")
2. Try to remove the folder with "Remove folder from workspace".
3. The folder should stay there and you should get an error saying "Unknown folder".

Does this issue occur when all extensions are disabled?: Yes

Video: https://youtu.be/4AWoSM5r4-I

**Comment by isidorn** [comment]
Yes I can reproduce that issue. Nice steps in the video.
Here's the stack trace. It seems like the configurationModel does not handle the case when the last workspace folder is removed if it is empty. Forwarding to @sandy081 for now
This is coming from the WorkspaceEditingService which API I use.

```
compareAndDeleteFolderConfiguration (configurationModels.ts:527)
compareAndDeleteFolderConfiguration (configurationModels.ts:123)
onFoldersChanged (configurationService.ts:577)
onWorkspaceConfigurationChanged (configurationService.ts:542)
(anonymous) (configurationService.ts:227)
Promise.then (async)
(anonymous) (configurationService.ts:227)
Promise.then (async)
setFolders (configurationService.ts:225)
doUpdateFolders (configurationService.ts:218)
(anonymous) (configurationService.ts:141)
consume (async.ts:448)
(anonymous) (async.ts:439)
queue (async.ts:437)
(anonymous) (configurationService.ts:141)
Promise.then (async)
updateFolders (configurationService.ts:140)
removeFolders (configurationService.ts:136)
removeFolders (abstractWorkspaceEditingService.ts:175)
handler (fileCommands.ts:498)
invokeFunction (instantiationService.ts:67)
_tryExecuteCommand (commandService.ts:84)
(anonymous) (commandService.ts:73)
Promise.then (async)
executeCommand (commandService.ts:73)
run (actions.ts:237)
run (actions.ts:293)
runAction (actions.ts:198)
run (actions.ts:190)
runAction (contextmenuService.ts:196)
click (contextmenuService.ts:170)
onClickChannelHandler (contextmenu.ts:19)
onceWrapper (events.js:291)
emit (events.js:203)
onMessage (init.ts:50)
```
