### ISSUE TITLE
can't use Backspace in console during Debugging 

### ISSUE THREAD

**Issue by gogoIsComing** [microsoft/vscode#89139]
- VSCode Version: 1.41.1
- OS Version: Windows 10 Pro 64-bit (10.0, Build 18362)

Steps to Reproduce:

1. create launch.json
2. write `"console": "terminal"` in your `configurations`
3. write the following code that take an input from user : 
```
import 'dart:io';

main() {
  stdout.writeln('what is Your Name ?');
  String name = stdin.readLineSync();
  print('Welcome $name');
}
```
4. start debugging

then i can input value , but i can't use `backspace` key to undo the text while i write in console.

![Untitled](https://user-images.githubusercontent.com/33967218/72965434-f914dd80-3dc4-11ea-8df6-58883b34f354.png)

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
please file this against dart extension

**Comment by DanTup** [comment]
As far as I can tell, this is not an extension issue - the same issue occurs using the sample Psuedoterminal code. I've opened https://github.com/microsoft/vscode/issues/90618 anyway, not realising there was already an issue here.
