### ISSUE TITLE
Pylint misunderstands an error code

### ISSUE THREAD

**Issue by jamesisin** [microsoft/vscode#89136]
Pylint in VSCode is misinterpreting something in a try/except statement.  

```
def func_getFileData():  
	# count lines in file 
	global fileToRead 
	global totalLines 
	global fullFileByLine 
	try:  
		with open( fileToRead, 'r' ) as readFile: 
			fullFileByLine = readFile.readlines() 
			totalLines = int( len( fullFileByLine ) ) 
	except FileNotFoundError:  
		print( "The file you offered does not exist:  {}".format ( fileToRead ) ) 
		fileToRead = ( input( "Please offer a different file:  " ) ) 
```

In the above function, the FileNotFoundError (in the line "except FileNotFoundError:") is interpreted as an undefined variable.  

Of course it's not a variable at all but the error which except handles correct when run.

**Comment by weinand** [comment]
"pylint" is not a part of VS Code.
