### ISSUE TITLE
Not support decorator after export default.

### ISSUE THREAD

**Issue by Emiya0306** [microsoft/vscode#89137]
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.2.0

Steps to Reproduce:
Just like #88902 describe, vscode is not support decorator after `export default`. I'm very strange that there is not any response that I commit, if the issue is closed? 😕

I'm sure it doesn't have any solution to resolve this error. I ask this issue in stackoverflow. No one can give the resolution.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The Intellisense/error reporting is powered by the TypeScript project. Please [file an issue/question](https://github.com/microsoft/TypeScript/issues/new)
