### ISSUE TITLE
settings: simplify flow to set path for an executable

### ISSUE THREAD

**Issue by reconix23** [microsoft/vscode#89134]
# Please search existing issues to avoid creating duplicates.
searched lots of random issues. 
example: https://github.com/microsoft/vscode/issues/251 https://github.com/microsoft/vscode/issues/22391 https://github.com/microsoft/vscode/pull/25576

----

I encountered this for php, but should be general.

1. copy-pasted from my path to appease 'PHP Language features (Extension)'
```json
    "php.validate.executablePath":"C:\Users\username\Downloads\php-7.4.2"
```

expected it to work.

# Describe the feature you'd like

It can't understand it.

if it can parse the string correctly

two better ways to improve the situation would be
- search for php file in the given folder, since the value(string) is given.
Or
- name the key to be more intuitive. one example: - "php.validate.pathToExecutable"

there's more than two issues here. My end-goal is to make it straightforward to remove such vscode pop-ups without having to dabble in different things for not much benefit. Starting with php as its not the main focus of vscode, so issues should be minimal.

Don't have a statistic or anything to point to as indication that its going to benefit vscode users. Just one more thing I personally wanted to do in vscode and hit a speed-bump.

**Comment by reconix23** [comment]
way to ignore issue and accomplish what vscode's 'PHP Language features (Extension)' wants:
`"php.validate.executablePath":"C:\\Users\\username\\Downloads\\php-7.4.2"`

this will allow it to interpret it. now it will display a false warning.

using 
`C:\\Users\\username\\Downloads\\php-7.4.2\\php.exe`
should silence it. now you can go back to doing what you want.

----

necessary but offtopic, non-technical:

now for the defence spells:
I certify that I don't mean this issue as a demand, its more like a feature request or a very weak suggestion.
I feel very intensely grateful for vscode.
Json is human-readable and intuitive and awesome. textmate grammars are wicked fast and efficient.

**Comment by roblourens** [comment]
Yeah the backslashes need to be escaped, that's just JSON's rules. You can also use forward slashes.
