### ISSUE TITLE
GH: Linux unit tests core dump

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89147]
Lately almost every Linux CI build fails on GH in our unit tests. 

Using your build with debug symbols (from https://github.com/microsoft/vscode/runs/404544549#step:12:10): 
```
 Run Unit Tests3s
#22 0x55d8d7ff674c content::BrowserMainLoop::EarlyInitialization()
Run DISPLAY=:10 ./scripts/test.sh --tfs "Unit Tests"
yarn run v1.21.1
$ node build/lib/electron
Done in 0.52s.
Received signal 11 SEGV_MAPERR ffffef6f439f5194
#0 0x55d8d8746329 base::debug::CollectStackTrace()
#1 0x55d8d86a82e3 base::debug::StackTrace::StackTrace()
#2 0x55d8d8745ea1 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f95bf780890 <unknown>
#4 0x7f95adfaa2dd <unknown>
#5 0x7f95adfac145 <unknown>
#6 0x7f95adf9ef68 <unknown>
#7 0x7f95adf9a5d4 <unknown>
#8 0x7f95adf9aa41 <unknown>
#9 0x7f95b7938af9 epoxy_glx_version
#10 0x7f95bbd1eb3f <unknown>
#11 0x7f95bbd1efaa <unknown>
#12 0x7f95bbd27b30 <unknown>
#13 0x7f95bbd24ca6 <unknown>
#14 0x7f95bbd14e3d <unknown>
#15 0x7f95bbce9d5d gdk_display_manager_open_display
#16 0x7f95bc1d969a gtk_init_check
#17 0x7f95bc1d96c9 gtk_init
#18 0x55d8dbcf93a7 libgtkui::GtkInitFromCommandLine()
#19 0x55d8dbcf922e libgtkui::GtkUi::GtkUi()
#20 0x55d8dbcfeb6b BuildGtkUi()
#21 0x55d8d67ed8aa electron::AtomBrowserMainParts::PreEarlyInitialization()
#22 0x55d8d7ff674c content::BrowserMainLoop::EarlyInitialization()
```

**Comment by joelgriffith** [comment]
👋 I've been tracking this in browserless, and have narrowed it down to libglapi-mesa or one of their sibling libs.

I don't have a solution, but thought I'd help point you in some direction as I'm struggling with this one as well

**Comment by bpasero** [comment]
@joelgriffith oh thanks for chiming in, this seems to have started for us since a couple of days ago (https://github.com/microsoft/vscode/commit/d6fba3151413544265bc68cba92ab1f8585c556e). Is this a GH CI issue that should be reported?

**Comment by joelgriffith** [comment]
I don’t think so, it’s prevalent in any Debian system I’ve encountered unfortunately

**Comment by joelgriffith** [comment]
I believe I have this fixed by pinning these libs manually: https://github.com/browserless/chrome/pull/531/commits/7f89e8f01b6ae6d6b1be8ab75c3b3b48ba989fb7#diff-de2dfe904ac98a74495473e67a0d0e2cR68. I'll likely discuss this with the headless-dev mail group and see if they have better workarounds as this isn't viable longer term

**Comment by bpasero** [comment]
This is unrelated to Electron 7, it even fails after our revert back to Electron 6 ([link](https://github.com/microsoft/vscode/runs/409098297#step:12:10)):

```
 Run Unit Tests4s
##[error]Process completed with exit code 139.
Run DISPLAY=:10 ./scripts/test.sh --tfs "Unit Tests"
yarn run v1.21.1
$ node build/lib/electron
Done in 0.43s.
./scripts/test.sh: line 38: 11601 Segmentation fault      (core dumped) ELECTRON_ENABLE_LOGGING=1 "$CODE" test/electron/index.js --no-sandbox "$@"
##[error]Process completed with exit code 139.
```

**Comment by bpasero** [comment]
Fixed by passing `-screen 0 1024x768x24` to `xfvb`

**Comment by joaomoreno** [comment]
Epic!
