### ISSUE TITLE
TS language service ignores tsconfig.json exclude settings

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/vscode#89146]
- VSCode Version: 1.41.1
- OS Version: Darwin x64 19.2.0 (Mac Catalina)

Steps to Reproduce:

1. Create a new project.
2. Add the following tsconfig.json
```jsonc
{
  "compilerOptions": {
    "target": "esnext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */,
    "module": "esnext" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
    "allowJs": true /* Allow javascript files to be compiled. */,
    "checkJs": true /* Report errors in .js files. */,
    "noEmit": true /* Do not emit outputs. */,
    "strict": false /* Enable all strict type-checking options. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "baseUrl": "."
  },
  "include": [
    "./*.js",
    "./*.ts",
    "./src/**/*",
  ],
  "exclude": [
    "./node_modules/",
    "./src/**/*.test.js"
  ]
}
```
3. Create a `src` directory in the project root
4. Add a sample test file, e.g. `sample.test.js` and add something that conflicts with typescript, e.g.:
```js
global.__VERSION__ = '{VERSION}'
```

See that it does not check the file while running `tsc --project tsconfig.json`, but it still checks in vscode. Also settings `"typescript.tsdk": "./node_modules/typescript/lib",` does not help (i have verified it is used by checking the typescript console).

Does this issue occur when all extensions are disabled?: Yes/No
Yes it does

**Comment by mjbvz** [comment]
Have you set `"javascript.implicitProjectConfig.checkJs": true`

Tsconfigs only defines projects. If you open a JS/TS file not in the project, we still provide Intellisense and error reporting for it

**Comment by alesmenzel** [comment]
Yes, I do, here is the revevant settings:

```js
"javascript.validate.enable": true,
"javascript.implicitProjectConfig.checkJs": true,
"typescript.validate.enable": true,
"typescript.tsdk": "./node_modules/typescript/lib",
```

**Comment by mjbvz** [comment]
This is working as designed then. The excluded js file you open will be treated as just a loose file that is not part of any project (so `javascript.implicitProjectConfig.checkJs` applies to it)
