### ISSUE TITLE
frozen after opened sourcecode file

### ISSUE THREAD

**Issue by berndcolve** [microsoft/vscode#89144]
Hello,
steps to reproduce the crash / endless loop:
1. start visual studio code, 
2. open a source code file (file size: 67514 Byte), 
3. vs code does not respond to mouse clicks on menu item!

?-Version/Environment-Info:
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Datum: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
Betriebssystem: Windows_NT x64 10.0.17763

plus 37 active extensions:
1. Name: Anaconda Extension Pack, ID: ms-python.anaconda-extension-pack, Version: 1.0.1
2. Name: Android, ID: adelphes.android-dev-ext, Version: 0.8.0
3. Name: autoDocstring, ID: njpwerner.autodocstring,Version: 0.4.0
4. Name: Bash Debug, ID: rogalmic.bash-debug,Version: 0.3.6
5. Name: bat-snippets, ID: bat-snippets.bat-snippets, Version: 0.2.0
6. Name: C/C++,ID: ms-vscode.cpptools,Version: 0.26.3
7. Name: C#, ID: ms-vscode.csharp, Version: 1.21.9
8. Name: C++ IntelliSense, ID: austin.code-gnu-global, Version: 0.2.2
9. Name: Debugger for Chrome, ID: msjsdiag.debugger-for-chrome, Version: 4.12.5
10. Name: Debugger for Firefox, ID: firefox-devtools.vscode-firefox-debug, Version: 2.6.1
11. Name: Django, ID: batisteo.vscode-django, Version: 0.19.0
12. Name: Django Snippets, ID: bibhasdn.django-snippets, Version: 1.1.1
13. Name: Django Template, ID: bibhasdn.django-html, Version: 1.3.0
14. Name: Docker, ID: ms-azuretools.vscode-docker, Version: 0.9.0
15. Name: ESLint, ID: dbaeumer.vscode-eslint, Version: 2.0.15
16. Name: Generic Remote Debugger, ID: mkloubert.vs-remote-Debugger, Version: 3.0.0
17. Name: German Language Pack for Visual Studio Code, ID: ms-ceintl.vscode-language-pack-de, Version: 1.41.2
18. Name: Git Graph,ID: mhutchie.git-graph,Version: 1.21.0
19. Name: GitLens — Git supercharged,ID: eamodio.gitlens,Version: 10.2.0
20. Name: Java Debugger,ID: donjayamanne.javadebugger,Version: 0.1.5
21. Name: Jinja,ID: wholroyd.jinja,Version: 0.0.8
22. Name: Jupyter,ID: donjayamanne.jupyter,Version: 1.1.5
23. Name: Live Share,ID: ms-vsliveshare.vsliveshare,Version: 1.0.1510
24. Name: MagicPython,ID: magicstack.magicpython,Version: 1.1.0
25. Name: Perl Debug,ID: mortenhenriksen.perl-debug,Version: 0.6.3
26. Name: PowerShell,ID: ms-vscode.powershell,Version: 2020.1.0
27. Name: Python,ID: ms-python.python,Version: 2020.1.58038
28. Name: Python Extension Pack,ID: donjayamanne.python-extension-pack,Version: 1.6.0
29. Name: Python for VSCode,ID: tht13.python,Version: 0.2.3
30.Name: SQL Server (mssql),ID: ms-mssql.mssql,Version: 1.8.0
31. Name: SVN,ID: johnstoncode.svn-scm,Version: 2.4.2
32. Name: TSLint,ID: ms-vscode.vscode-typescript-tslint-plugin,Version: 1.2.3
33. Name: TSLint (deprecated),ID: eg2.tslint,Version: 1.0.44
34. Name: Visual Studio IntelliCode,ID: visualstudioexptteam.vscodeintellicode,Version: 1.2.4
35. Name: WinDbg Debugger extension,ID: reznikdi.windbg-debug,Version: 0.3.4
36. Name: XML Tools,ID: dotjoshjohnson.xml,Version: 2.5.0
37.Name: YAML,ID: redhat.vscode-yaml,Version: 0.6.1

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please reload with extensions disabled (search 'disabled' in Command Palette) and see if you still get the problem. If you don't bisect your extensions until you find the faulty one, then report the issue on its repo.

**Comment by berndcolve** [comment]
Hello,
after de-activing all visual Studio Code extensions (german language pack uninstalled due to no disabling feature) my local Visual Studio Code still crashes/endless loop - issue still occurs…
What more Information could help?

**Comment by gjsjohnmurray** [comment]
Some guidance at https://github.com/Microsoft/vscode/wiki/Performance-Issues

Are you able to share a source file that triggers the problem? What language is it coded in?

**Comment by berndcolve** [comment]
It is a *.cs C# source code file. And it seems like it depends on the file - a bigger *.cs file could be loaded, an also a smaller one.

**Comment by berndcolve** [comment]
Just for a comparison: windows 10 notepad.exe loads that file as the other *.cs files.

**Comment by gjsjohnmurray** [comment]
Please use the ... menu on Extensions to show the built-in ones. Disable the one called C# Language Basics. Then open your file. Does the problem still occur?

**Comment by berndcolve** [comment]
Thanks, this helps to avoid this issue, of course now without the helpfully color syntax highlighting. 
I am sure that I could not send you the Company C# source code. 
It is a C# test, and the C# Project compiles with no warnings and no errors.

**Comment by gjsjohnmurray** [comment]
/causedByExtension I think the issue needs to be raised at https://github.com/dotnet/csharp-tmLanguage but without access to the source file that's causing the problem for you it's going to be hard for that project to investigate the issue.

I am ccing @alexr00 as a member of the VSCode team who seems to have logged similar C# issues there previously.

**Comment by alexr00** [comment]
@berndcolve without some C# to show the problem the folks over at dotnet/csharp-tmLanguage won't be able to figure out what needs to be fixed. Usually when this sort of issue occurs it can be tracked down to a few lines in the source file. They may be perfectly valid C#, but the grammar used to colorize them doesn't account for whatever pattern you are using. 

Since you can't give us the whole file, can you give us a small part of the file? You should be able to delete half the file, see if it crashes, then delete half of that and repeat until you have it narrowed down to just a few lines that it's ok for you to share.

Thanks for looping me in @gjsjohnmurray !
