### ISSUE TITLE
Running SFDX: Deploy Source to Org

### ISSUE THREAD

**Issue by vipulissar** [microsoft/vscode#89141]
Issue Type: <b>Bug</b>

When I'm deploying the code to vs,Its not deployed.Deployment Process is continuously running without any success or failure message.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (4.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.15
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
python|ms-|2020.1.58038
vsliveshare|ms-|1.0.1510
vscode-xml|red|0.10.1
salesforcedx-vscode|sal|47.15.0
salesforcedx-vscode-apex|sal|47.15.0
salesforcedx-vscode-core|sal|47.15.0
salesforcedx-vscode-visualforce|sal|47.15.0
watch-in-chrome|sne|0.0.2

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension this question relates to one of your Salesforce extensions
