### ISSUE TITLE
Wrong Status When Clicking on "Check For Updates..."

### ISSUE THREAD

**Issue by oliverdrummond** [microsoft/vscode#89150]
Issue Type: <b>Bug</b>

1- Click on the settings cog (bottom left corner)
2- Click on "Check for Updates..."
3- While the updates are being checked, hover the mouse over the cog;
4- The message "Manage - New Code update available" will appear while it's still checking for the update, and even when no update is later found. 

Screenshot
![New Code Available](https://user-images.githubusercontent.com/3949943/72972172-ecfd4000-3e05-11ea-942c-84f2ddf6ded5.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
vscode-sql-formatter|adp|1.4.4
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
prettier-vscode|esb|3.18.0
vscode-projects-plus|fab|1.23.2
vscode-projects-plus-todo-plus|fab|1.6.10
vscode-todo-plus|fab|4.14.1
beautify|Hoo|1.5.0
textile|idl|0.1.5
python-coding-conventions|igr|0.0.4
vscode-edit-csv|jan|0.2.5
camelcasenavigation|map|1.0.1
textile-preview|mic|1.0.2
mssql|ms-|1.8.0
python|ms-|2020.1.58038
oracle-plsql|myc|1.0.3
partial-diff|ryu|1.4.0
vba|spe|1.2.0
vba-snippets|spe|1.0.1
spotfire-expressions|szi|0.0.1
html-preview-vscode|tht|0.2.5
tsqllint|tsq|1.2.0
vscodeintellicode|Vis|1.2.4
vscode-icons|vsc|9.7.0
change-case|wma|1.0.0
better-align|wwm|1.1.6
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|2.7.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by joaomoreno** [comment]
@bpasero can you verify by code review?
