### ISSUE TITLE
Git file is outside of repository on virtual drive

### ISSUE THREAD

**Issue by KevinGuancheDarias** [microsoft/vscode#89153]
- VSCode Version: 1.41.1
- OS Version: Windows 7 SP1 64bits

Steps to Reproduce:

1. Create a virtual drive with `subst G: C:\Users\myuser\EmulatedDevice`
2. git clone a git project in **C:\Users\myuser\EmulatedDevice\project**
3. Open the project from the virtual drive path **G:\project**
3. Change a file, go to the changes tab in VSCode, and press to add file to your environment
4. Bump!, capture of the error, and a key capture of the file browser of VSCode properly using the virtual drive as path to open files
![image](https://user-images.githubusercontent.com/6832422/72976582-c53cb680-3dca-11ea-8fcf-f9239e2db920.png)
![image](https://user-images.githubusercontent.com/6832422/72976691-f61ceb80-3dca-11ea-8ad0-46bbb1fd678c.png)  

Does this issue occur when all extensions are disabled?: **Yes**

Sidenote: I have been using this virtual disk for a long time without problems, I think it's something with version 1.41.1

**Comment by pcvdbroek** [comment]
I have this problem on my local drive with all files I try to stage through VSCode. Every time the same error. I also use sql developer and there it work perfectly. I think it started occuring after one of the last updates of vscode, since I was able to do it before... If I do it through the terminal I can add the file if I use the path without the c:\...\, but when using the full path (like the + button does) it won't work.

**Comment by KevinGuancheDarias** [comment]
Same drive @pcvdbroek ?

What do you mean when you say ** but when using the full path (like the + button does)**, do you mean launching vscode relatively with `$ code .` ?

**Comment by pcvdbroek** [comment]
My repository is on my C: drive, not a network drive (no strange characters in the path). When I change a file and want to stage it and click on the big + next to the filename I always get the error. If i look in the output i can see it uses the full path to stage the file, so "c:\projects\project1\src\filename.ext". When I stage through the teminal using "git add project1/src/filename.ext" it stages without a problem. So basically the big + button (or the menu option "Stage Changes" for that matter) does not work in VSC.

**Comment by KevinGuancheDarias** [comment]
:wine_glass:  No longer happends after updating to **1.42.0** :wine_glass: 

@pcvdbroek Can you confirm it's fixed too on your side?

**Comment by pcvdbroek** [comment]
I can confirm this no longer happens after updating! :)

**Comment by KevinGuancheDarias** [comment]
Then I will close this issue :smile: 

Keep up the great job guys! :wine_glass: :beers:
