### ISSUE TITLE
Ability to specify set of required plugins in .workspace and .vscode files for a project

### ISSUE THREAD

**Issue by SiarheiKuchukBelitsoft** [microsoft/vscode#89157]
As a developer in a team, I would like some common settings of VS Code that are in common for entire team - to be stored in a project folder in .workspace/.vscode file,

Teams has usually set of obligatory plugins, such as beautifiers and other commonly used ones that all developers have to install upon starting working on a project.

I would like to have a possibility to specify them in mentioned files, so VS Code would install them by itself (or with user consent (out of a warning 'This project demands those plugin to be installed: A, B, C. Press Install to install them.'))

**Comment by gjsjohnmurray** [comment]
[This technique](https://github.com/microsoft/vscode/issues/61723#issuecomment-486621532) looks interesting, but I haven't tried it myself.

**Comment by SiarheiKuchukBelitsoft** [comment]
@gjsjohnmurray Thanks for the interest. It seems like an easy feature to implement. Benefits will be to not install for other team members plugins by list in docs. And if a list will be changed in a future, to have less communication about that with a team.

**Comment by sbatten** [comment]
Under the .vscode folder for a folder, you can specify common settings in the `settings.json` file and recommended extensions in the `extensions.json` file. Take a look at our repository for an example https://github.com/microsoft/vscode/tree/master/.vscode

If you are using multi-root workspaces with `.code-workspace` file, the same can be done there following the guidance at: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings and https://code.visualstudio.com/docs/editor/multi-root-workspaces#_extensions.

**Comment by SiarheiKuchukBelitsoft** [comment]
Guys, you are awesome! I thought I've been adding unique value to your masterpiece project and this feature is already here! Fabulous
