### ISSUE TITLE
window.activeborder works inconsistently

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#89163]
Issue Type: <b>Bug</b>

Set this inside of *.vscode/settings.json*, then go between two different instances of Code. The color shows up in one but not the other.

```json
  "workbench.colorCustomizations": {
    "window.activeBorder": "#f0f000",
    "window.inactiveBorder": "#f00000",
}
```

VS Code version: Code - Insiders 1.42.0-insider (c4d53a19df8799f5d49a4f49a6900c499e6fa27c, 2020-01-23T05:38:55.065Z)
OS version: Darwin x64 19.2.0

![2020-01-23_08-36-43 (1)](https://user-images.githubusercontent.com/1202528/72989402-3032c100-3dbc-11ea-967a-9723f0de31a8.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|64.00GB (24.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
ng-template|Ang|0.900.5
vscode-browser-preview|auc|0.5.9
spellright|ban|3.0.50
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
vscode-pull-request-github|Git|0.14.0
angular-essentials|joh|0.6.3
Angular1|joh|0.2.1
Angular2|joh|8.3.0
read-time|joh|0.2.0
vscode-cloak|joh|0.2.0
vscode-peacock|joh|3.3.1
dotenv|mik|1.0.1
azure-pipelines|ms-|1.165.1
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.8.0
vscode-cosmosdb|ms-|0.12.1
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.98.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
azurecli|ms-|0.4.6
vsliveshare|ms-|1.0.1510
debugger-for-chrome|msj|4.12.5
angular-console|nrw|10.0.0
vetur|oct|0.23.0
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
vue-vscode-snippets|sdr|1.8.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.4

(1 theme extensions excluded)

</details>

**Comment by eamodio** [comment]
@johnpapa Do you still see this behavior? I can't reproduce it on macOS (or Windows) with 1.50
