### ISSUE TITLE
Untitled - apply language mode from copied text upon paste

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89162]
When pasting text from a VSCode editor into an untitled editor, it would be great if we inherit the mode we copied from.

Probably only unless a language mode is already set.

**Comment by axefrog** [comment]
@bpasero You forgot to verify the second part. Try setting "plaintext" manually and then paste from an existing editor. The pasted language is still adopted.

> Probably only unless a language mode is already set.
