### ISSUE TITLE
Terminate program button

### ISSUE THREAD

**Issue by Makkkkus** [microsoft/vscode#89168]
Issue Type: <b>Feature Request</b>

It would be very nice to have a terminate program button in the terminal when running a program.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

**Comment by GoEagles999** [comment]
Why closed?

**Comment by Makkkkus** [comment]
> 
> 
> Why closed? I’d appreciate such feature
Already exists

**Comment by GoEagles999** [comment]
> > Why closed? I’d appreciate such feature
> 
> Already exists

Where?

**Comment by Makkkkus** [comment]
> 
> 
> > > Why closed? I’d appreciate such feature
> > 
> > 
> > Already exists
> 
> Where?

Just click the trash icon while running the program
