### ISSUE TITLE
(Python) Go to definition unreliable - Renaming unreliable

### ISSUE THREAD

**Issue by lumyx2** [microsoft/vscode#89164]
Issue Type: <b>Bug</b>

Click F12 on function and sometimes it doesn't work or takes forever. 
I've tried the jedi flag, still no change. The problem seems to dissappear if VS Code is restarted. After some hours it comes back. Some times it recovers after taking forever and others it just shows some message along the lines of Not Found. 

The same happens with rename. The added effect is that sometimes it renames "some" of the matches. But, not all! So then you need to debug the code to find out in what files and in what parts of a file the variables/functions have been renamed!

I know that some of this functionality has been reported to depend on Rope. Either way, the sheer amount of bug reports shows that it either needs to be fixed through native support or an alternative dependency is needed. It is pathetic that after years, an IDE that is supposed to be fairly mass market is massively buggy. 

Also, I don't know what other information I can provide. However, I will try if asked. Don't CLOSE it like ALL the other instances. Pretending that the bugs are not there does NOT make them go away!

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (5.81GB free)|
|Process Argv|--folder-uri file:///f%3A/Eng_Cambridge/PhD/Project_WorkSpace_Python/ws_opm_wprior|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.6.0
project-manager|ale|10.9.1
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
githistory|don|0.4.13
vscode-gitignore-syntax|dun|0.1.2
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
todo-tree|Gru|0.0.165
asciidecorator|hel|0.2.0
beautify|Hoo|1.5.0
theme-by-language|jsa|1.1.1
vscode-map-preview|jum|0.4.8
vscode-github|Kni|0.30.3
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.58038
remote-wsl|ms-|0.41.7
vscode-json-editor|nic|0.2.3
indent-rainbow|ode|7.4.0
fix-json|oli|0.1.2
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
highlight-words|rsb|0.1.4
indenticator|Sir|0.6.0
selectline-statusbar|tom|0.0.2
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@lumyx2 I am not closing this issue because I do not think it is a bug, but rather this issue belongs in the python repository. Please file an issue at https://github.com/microsoft/vscode-python
