### ISSUE TITLE
API: provide a way to configure notifications to cancel when user closes the notification

### ISSUE THREAD

**Issue by ArchDev** [microsoft/vscode#89169]
Hi everyone! In my plugin I use progress bar in notifications area to display build progress. While I can cancel build process by using cancel button, in case if notification with progress will be closed it will be hidden in notification toast and while user will think that process was cancelled, in fact, it will be still going in background.

I believe there is a reason for not providing onClose callback for notifications and I wanna discuss how possibly we can extend vscode API to handle such a cases. Some ideas aside of onClose callback for notifications:
- add `cancelOnClose` property for progress bar;
- move progress bar from notifications to window on close (if its configured like this in properties for sure).

Would love to help you with this feature by making a PR if we will find out how it should be done.

**Comment by bpasero** [comment]
I personally think this is not the right UX direction. Rather, when a notification with progress is closed by the user, it should not cancel the progress but possibly indicate it somewhere else.
