### ISSUE TITLE
The F20-F24 key's are "unknown"

### ISSUE THREAD

**Issue by Wouterr0** [microsoft/vscode#89166]
- VSCode Version: Tested on VSCode Insiders 1.42.0-insider
- OS Version: Windows 10 Version 1909 (OS Build 18363.592)
 - Keyboard: Corsair K95 platinum RGB cherry mx brown

Steps to Reproduce:

1. Map one of your keyboard keys to the f20 key.
2. Go to the keybindings.json.
3. Click on the buttun "Define Keybinding (Ctrl+K Ctrl+K)".
4. Press the button you assigned the f20 key to.
5. It says unknown
![2020-01-23 15-10-41 mp4_snapshot_00 04 750](https://user-images.githubusercontent.com/41055533/72992245-c1715a00-3df3-11ea-97ed-c39948add1a3.jpg)

When I do the same thing but for any key f1-f19 it shows the correct key and works just fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ThePlasmaRailgun** [comment]
I would like to point out, just in case people think this is some vendor-specific function that's not really supported, the function keys up to F24 are defined as valid scan codes in the USB HID protocol spec. This threw me for a loop the first time I saw it. 

Also, tonight I can attempt to replicate this issue with the same keyboard on Ubuntu.

**Comment by Wouterr0** [comment]
What's the current status? Are there any updates? I am sorry for my impatience.

**Comment by rebornix** [comment]
Currently we only handle F1 to F12 in our keymap resolver.

**Comment by Wouterr0** [comment]
@rebornix but the f12 to f19 keys do work.
