### ISSUE TITLE
VSCode title should not contain editor label when screen reader is detected

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#89175]
Turn on a Screen Reader.
Every time the VSCode window is focused the Title is read out with the editor aria.
This leads to duplication and annoyance.

Another issue is if the focus was for example in the search input box, the Screen reader will still announce the editor name which is part of the title. Which is confusing for the screen reader, since the focus is actually in the search.

Due to that I suggest that the title area is simply vscode when a screen reader is detected.
@bpasero if you do not have time let me know what you think and provide a code pointer and I can implement this.
Here's the event and service which we should use
https://github.com/microsoft/vscode/blob/3efd575c64786100f67d80a29783715ccb3a9f18/src/vs/platform/accessibility/common/accessibility.ts#L15

Related https://github.com/microsoft/vscode/issues/89098

**Comment by bpasero** [comment]
@isidorn this is probably just window.title being read out by the screen reader. Does it change anything when you disable this line or hardcode it:

https://github.com/microsoft/vscode/blob/f3dbcea32a6b52ce819dc863e778fb8517357f61/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L212

**Comment by isidorn** [comment]
@bpasero Yeah it change things. I have created this PR, can you please review https://github.com/microsoft/vscode/pull/89216

**Comment by isidorn** [comment]
After discussions in the PR decided to not merge in. Users can configure this for example
`"window.title": "\u200B"`

**Comment by bpasero** [comment]
Yeah I was actually about to suggest that.
