### ISSUE TITLE
Wrong token colors display in editor

### ISSUE THREAD

**Issue by awerlogus** [microsoft/vscode#89174]
Issue Type: <b>Bug</b>

description:
---

While "Initializing JS/TS language features" message is shown, everything works right.
![screenshot1](https://user-images.githubusercontent.com/24425566/72998205-86c8eb00-3e0e-11ea-990e-ac96c83a732e.png)
But, after initialization, some tokens (type and function names) somehow become colored as plain text. 
![screenshot2](https://user-images.githubusercontent.com/24425566/72998238-921c1680-3e0e-11ea-8064-7f60c7743da5.png)
Meanwhile token colors are still inferred right.
![screenshot3](https://user-images.githubusercontent.com/24425566/72997751-c93df800-3e0d-11ea-8ae3-0d39493e534f.png)

Steps to reproduce:
---
1) Install Onyx theme
2) Open any .js/.ts file
3) Write any function
4) Reload window

VS Code version: Code - Insiders 1.42.0-insider (c4d53a19df8799f5d49a4f49a6900c499e6fa27c, 2020-01-23T05:39:57.148Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.35GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by NovaLogicDev** [comment]
Been having the same issue, doesn't seemed to be tied to anything but the initialization of JS/TS language features. Probably related to #77140 as I'm not seeing the issue in non insider builds. This also has nothing to do with the integrated terminal.

**Comment by NovaLogicDev** [comment]
I spent a moment and realized that this issue is not just effecting colors within the document but also the appearance of those tokens in the code minimap. notice the missing pieces of code on in the screenshots below.

![Annotation 2020-01-23 150344](https://user-images.githubusercontent.com/39929570/73027941-af8eb780-3df1-11ea-9710-95951c38e41a.png)
![Annotation 2020-01-23 150345](https://user-images.githubusercontent.com/39929570/73027943-b0274e00-3df1-11ea-8a22-e74e818250fb.png)

**Comment by awerlogus** [comment]
Version: 1.42.0-insider (system setup)
Commit: f3dbcea32a6b52ce819dc863e778fb8517357f61
Date: 2020-01-24T05:38:14.538Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

In the latest release function and type names are colored right, but this time constants became blue (because of wrong color inference only?)

While "Initializing JS/TS language features" message is shown, everything works right.
![изображение](https://user-images.githubusercontent.com/24425566/73126634-575cde80-3fc6-11ea-94fa-4c6f51e5af86.png)

After initialization constants become colored blue
![изображение](https://user-images.githubusercontent.com/24425566/73126643-79eef780-3fc6-11ea-8137-33265d1ea414.png)

Color of constants is inferred wrong
![изображение](https://user-images.githubusercontent.com/24425566/73126660-a6a30f00-3fc6-11ea-9399-304d53ed50ad.png)

Even if we force the color of token, it doesn't help
![изображение](https://user-images.githubusercontent.com/24425566/73126694-df42e880-3fc6-11ea-93fb-b4ad4a49c94f.png)

**Comment by aeschli** [comment]
Thus is caused bugs in by semantic highlighting that was just added. Some fixes have already gone in:
- I improved the Inspect Hover to show the rule that was matched in the theme. Because the token got a semantic token of type `variable`, we look for a theming rule matching scope `variable`.
- There's a bug with colors that have alpha components. that's fixed in tomorrows build.

Sorry for the trouble and I hope we get all the issue fixed soon. Please let me know if you still see issues with tomorrows I-Build.

If you want to turn off semantic highlighting, you can use `"editor.semanticHighlighting.enabled": false`

**Comment by awerlogus** [comment]
Sorry for semi-offtop, but can you make a feature with semantic detection of functions assigned to constants? I want all functions to be colored the same, but in some cases (when I return lambda expression from another function, for example) function selector is not being added to the token. (screenshots made without of semantic highlight)
![изображение](https://user-images.githubusercontent.com/24425566/73218543-38e41800-416b-11ea-89f5-d9c4ba7b770c.png)
![изображение](https://user-images.githubusercontent.com/24425566/73218565-44cfda00-416b-11ea-93e8-38214d08c4c9.png)
![изображение](https://user-images.githubusercontent.com/24425566/73218588-50bb9c00-416b-11ea-83da-3c00b7888ad4.png)

**Comment by awerlogus** [comment]
Also I realized just now that information about colors of tokens doesn't depend on <code>"editor.semanticHighlighting.enabled"</code> setting

---
![изображение](https://user-images.githubusercontent.com/24425566/73224647-338ec980-417b-11ea-8a8e-7ecfb6395e00.png)
![изображение](https://user-images.githubusercontent.com/24425566/73224805-b57ef280-417b-11ea-99fa-44b1066eec48.png)
![изображение](https://user-images.githubusercontent.com/24425566/73224850-d8a9a200-417b-11ea-859b-03ccc59c3ab0.png)

**Comment by aeschli** [comment]
Oh, yes, that's a bug that I wanted to fix

**Comment by NovaLogicDev** [comment]
Looking at todays build with semantic highlighting enabled and I'm seeing the same issue, no apparent improvement.

![image](https://user-images.githubusercontent.com/39929570/73313019-58208b00-41e7-11ea-8e81-2961b49720c8.png)

**Comment by NovaLogicDev** [comment]
Bug seems to be resolved in todays build

![image](https://user-images.githubusercontent.com/39929570/73468011-6387c980-4341-11ea-8838-7c37088534b3.png)

**Comment by SPGoding** [comment]
<details><summary>VSCode Info</summary>
Version: 1.42.0-insider (user setup)<br>
Commit: be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b<br>
Date: 2020-01-31T13:53:58.701Z<br>
Electron: 6.1.6<br>
Chrome: 76.0.3809.146<br>
Node.js: 12.4.0<br>
V8: 7.6.303.31-electron.0<br>
OS: Windows_NT x64 10.0.18363</details>

Though I don't have this problem with TS/JS, I encountered this with my own language server:

![bug](https://user-images.githubusercontent.com/15277496/73602278-d312da00-4536-11ea-8c76-8ca176ce03e7.gif)

The Inspect Hover told me that these tokens in the second line were applied correctly, but they did not have the specific colr. This happened after I deleted some tokens in the end of the last line.

I was using the SemanticTokensBuilder provided by `vscode-languageserver` package to build edits.

**Comment by aeschli** [comment]
I think all the mentioned issues got fixed.
- issue with colors and alpha
- don't render semantic tokens white if there's no color rule for it
- inspect hover improvents

Please file a new issue if you still see problems with semantic colors in TypeScript.

@SPGoding Please file a separate issue with the info of what tokens are created.
