### ISSUE TITLE
clarify error messages relation to settings/rules

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#89178]
Currently, when Typescript reports an error in the "problems" pane, it's not clear which option/rule to turn on/off if you want to ignore that warning.  

**Example error**: `initializer provides no value for this binding element ... TS(2525)`

There seems to be **no documentation mapping the error to the associated compiler option** in `tsconfig.json` (I have an open [Stackoverflow](https://stackoverflow.com/questions/59848559/connecting-typescript-errors-to-their-associated-compiler-options-tsconfig-json) question about that, if anyone knows.)

**Any easy fix** would be for the warning text to contain the setting related to this problem, like ` "strictPropertyInitialization": true`, or whatever.  

Thanks for considering!

**Comment by mjbvz** [comment]
These error messages come from TypeScript. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) with this suggestion
