### ISSUE TITLE
Focus vanishes after refactoring

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#8917]
- VSCode Version: 1.3.0 Commit e724f269ded347b49fcf1657fc576399354e6703
- OS Version: Linux Ubuntu 16.04

Steps to Reproduce:

1. Open a project (I use Go)
2. Mark a symbol
3. Press F2 to rename
4. Symbol is renamed and focus is not in the editor anymore :(

This Bug was previously marked as a duplicate but I could not see what the two bugs had in common.
This is still existing.

**Comment by jrieken** [comment]
There are calls to [`focus'](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/rename/browser/rename.ts#L99) at the end of the rename operation. Not sure why it doesn't work for you...

**Comment by DasJott** [comment]
I don't know, where the focus is though.
If I make Ctrl+TAB two times, the focus is where it should be right after refactoring.

**Comment by jrieken** [comment]
If this `go` specific or does this also happen for other languages like `js` or `ts` files?

**Comment by DasJott** [comment]
Trying to rename in JS files ended up in a "No results" error message at the top :-/
In PHP renaming is not working at all.

**Comment by jrieken** [comment]
save this as JS file to disk

```js
function ffff() {

}

ffff();
```

and try to rename `ffff`

**Comment by DasJott** [comment]
![vscode-js-rename](https://cloud.githubusercontent.com/assets/6298761/16799621/0b4146f4-48f2-11e6-8a6c-6e3cb79cc10e.png)

**Comment by jrieken** [comment]
That's bizarre... Sorry, for the hassle. Can you try with a TS files and when not having a file but a folder open?

**Comment by jrieken** [comment]
Also, can you check the console (F1 > Toggle Dev Tools)?

**Comment by DasJott** [comment]
I don't know, what to say - today it works. I took the time and made a new folder to put a ts and a js file into it. Renaming within the files works perfectly. Also the file from the screenshot above works now.

Whatever, within a very huge project with many php files and many js files, renaming symbols in js still fails with "No result". Can't seem to reduce this problem to certain steps by now...

Updated to 1.3.1 meanwhile, maybe that did at least some fixing on this error.

But anyway, this seems to be a different bug than some vanishing focus - which still exist as well.

**Comment by DasJott** [comment]
I found out, that I can get the focus back into the editors window by pressing TAB 18 times.
Meanwhile focus goes through the icons on the left and all the interface stuf, until it finally reaches back to the editor.

**Comment by jrieken** [comment]
> Whatever, within a very huge project with many php files and many js files, renaming symbols in js still fails with "No result". 

That's a known issue which will be fixed with TypeScript 2.0. Often JavaScript projects suck in tons of dependent code (node_modules et al) that make the compiler crawl/fail...

So, when the rename operation completes successfully and timely do you loose focus or only when only the rename operation is funky (no result, takes too long etc)?

**Comment by DasJott** [comment]
> Often JavaScript projects suck in tons of dependent code
It was a renaming of a parameter whithin a small function, so no search in other code needed.

If renaming works, focus comes back to where it was, yes! So that seems to be a problem affecting not ts and js but still go.

I found something interesting: I had the huge project opened in a vscode window, then opened another vscode window with the small test projecet (including the ts and js). Now the renaming within the ts and js files of the small project did not work as well!
If I then close the window with the huge project, it still doesn't work. If I close all windows and then restart vscode (it starts with the last project for me, and here it is the small one), it works again, renaming and focus just fine.

Strange, huh? ;)

**Comment by DasJott** [comment]
...if I then open another vscode instance with the huge project again, it still works in the small one, but doesn't in the huge one. I can close and reopen the small one, it stays that way.

order is: 
1. open a vscode with a huge project (where renaming does not work)
2. open a small project (where it usually works)
3. See, that the error seems to have expanded to the smaller project.

**Comment by DasJott** [comment]
... when the "No result" Info cxomes, the dev tools console says nothing.

**Comment by DasJott** [comment]
This is, when a vscode openes, where no renaming is possible. Right after startup.

![errors_focus](https://cloud.githubusercontent.com/assets/6298761/16835455/16686a22-49b9-11e6-9d3e-c0b41f5422b4.png)

**Comment by jrieken** [comment]
```
    languages.registerRenameProvider('abc', {
        provideRenameEdits(): any {
            throw new Error('testtest');
            // return new Promise(resolve => setTimeout(resolve, 3000));
        }
    });
```

Both cases aren't handled very graceful. The error case is easy, the 'takes long case' is a little harder cos we don't want to make the editor readonly.

**Comment by joaomoreno** [comment]
@jrieken Any hints on verification steps?

**Comment by jrieken** [comment]
Yes - have a rename provider like this: https://github.com/Microsoft/vscode/issues/8917#issuecomment-232712057
