### ISSUE TITLE
Allow "files.associations" as a resource setting

### ISSUE THREAD

**Issue by skipperTux** [microsoft/vscode#89179]
- VSCode Version: 1.41.1
- OS Version: Fedora 31

References: #12805 #29458 #47298

Steps to Reproduce:

1. Put the following code into `.vscode/settings.json` of a workspace project:
```json
    "files.associations": {
        "inventory": "yaml"
    }
```
The setting is darkened with the following message: `This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.`

2. Put the following code into the workspace file (`project.code-workspace`) of a project:
```json
    "files.associations": {
        "inventory": "yaml"
    }
```
The setting is underlined in yellow with the following message: `Unknown workspace configuration property`.

In both cases the `inventory` file is not recognized as a YAML-file. This setting only works when put into `~/.config/Code/User/settings.json`; however as a user setting it affects all projects.

Does this issue occur when all extensions are disabled?: Yes (not applicable)

Use case: Files in specific formats without extension, but file naming is unique only within project, not globally in user scope; it might lead to "files.associations" clashes.
Example: In one project `customers` is a YAML-file, in another project `customers` is a JSON-file.

Edit: 
1. Add new reference.

**Comment by sbatten** [comment]
@bpasero looks like that setting has a scope of WINDOW and we get this error due to code here https://github.com/microsoft/vscode/blob/caf838e1cd1a01aad17137ed8d50379f7febabb3/src/vs/workbench/contrib/preferences/browser/preferencesRenderers.ts#L1057

Is this a limitation we can address?

**Comment by bpasero** [comment]
It works with (either globally or as workspace setting):

```json
"files.associations": {
   "*.inventory": "yaml"
 }
```

**Comment by sbatten** [comment]
@bpasero that's right, but for example, if I have the vscode repo folder in a multiroot workspace, I get this 
![image](https://user-images.githubusercontent.com/6561887/73086749-11006600-3e86-11ea-8402-74bf03f22f7a.png)

different folders may have different clashing associations which is @skipperTux's remark

**Comment by bpasero** [comment]
Makes sense, I have updated the issue.

**Comment by skipperTux** [comment]
> It works with (either globally or as workspace setting):
> 
> ```json
> "files.associations": {
>    "*.inventory": "yaml"
>  }
> ```

To clarify, your setting _may_ work with the `inventory` **extension**, but I was talking about the `inventory` **file**. _Extensions_ are not a common concept among [Unix-derived systems like Linux or MacOS](https://en.wikipedia.org/wiki/Filename_extension#Command_name_issues). I was expecting a cross platform tool handles all platforms equally, and "files.associations" works also with files without extension.

Also the setting from my initial post is included **by VS Code into the user settings** `~/.config/Code/User/settings.json` when you click on `Select Language Mode`,
![image](https://user-images.githubusercontent.com/3322442/73089327-49c82b80-3ed6-11ea-978a-68867340a452.png)

click `Configure File Association...`,
![image](https://user-images.githubusercontent.com/3322442/73089633-f6a2a880-3ed6-11ea-895e-52e1999b3042.png)

and type in the file type, in this case `YAML`:
![image](https://user-images.githubusercontent.com/3322442/73089692-120db380-3ed7-11ea-940c-4ab59be2cc3e.png)

```json
  "files.associations": {
    "inventory": "yaml",
    "customer": "yaml"
  }
```
No extension, just the file name inserted by VS Code. **My point is**, this setting works when it is in the `~/.config/Code/User/settings.json` file, it does not work when it is put in either `.vscode/settings.json` or `project.code-workspace`, and gives error messages, see my initial post.
