### ISSUE TITLE
View Container Model does not fire events to update UI when views are moved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#89170]
Currently it is only possible to re-arrange the views inside the split view using drag and drop.
We should introduce commands so this feature is available to keyboard users.
Ideally this would work the following way: there is a command "Move View" , user executes that command and than can use up / down keybdingin to move the view inside the split view. Or left / right if the split view is horisontal.

fyi @sandy081 @alexdima @joaomoreno

**Comment by isidorn** [comment]
I hate the bot.

**Comment by sbatten** [comment]
@sandy081 pushed commands for this. as discussed, the model does not fire events to update UI with changes meaning reload is required

**Comment by isidorn** [comment]
Great for pushing commands for this, but if a reload is required then the experience is not that good. What would be needed that we update the views as soon as the commands are executed? Can I help somehow here?

**Comment by sandy081** [comment]
This is same as https://github.com/microsoft/vscode/issues/93909

This has to be fixed in the model which need some deep knowledge.

I will take care of this in this milestone.

**Comment by isidorn** [comment]
Great, thanks @sandy081
