### ISSUE TITLE
(node:26626) [DEP0005] DeprecationWarning: Buffer() 

### ISSUE THREAD

**Issue by kerolloz** [microsoft/vscode#89176]
When I try to install an extension from the command line I get the following warning. However, The extension is installed successfully.

```
(node:26626) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

- VSCode Version: 
```
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64
```
- OS Version: Kali-rolling

Steps to Reproduce:
for example
 `code --install-extension ms-python.python`

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
/duplicate

#82524
