### ISSUE TITLE
Enable to open settings via vscode:// URI in IEditorService.openEditor()

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8918]
Needs some kind of mapping from URI => EditorInput in the backend. This allows to e.g. open the default settings from the problems view.

Related: https://github.com/Microsoft/vscode/issues/8826

**Comment by bpasero** [comment]
@sandy081 can this be closed now that settings are using resource inputs?

**Comment by sandy081** [comment]
Yeah we can close this
