### ISSUE TITLE
JYUPITER NOTEBOOK 

### ISSUE THREAD

**Issue by himanshuaskd** [microsoft/vscode#89183]
NOTEBOOK IN VSCODE IS TAD BIT SLOW COMPARE TO ANACONDA VERSION 
IT DOES NOT MATCH UP TO MY SPEED OF TYPING 
IT NEEDS TO BE FASTER IN RESPONSE

**Comment by rebornix** [comment]
@himanshuaskd please file issue against the extension which contributes the notebook feature, I suppose it's Python extension.
