### ISSUE TITLE
SCM input wrong color

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89189]
![image](https://user-images.githubusercontent.com/323878/73015967-e1902180-3dd1-11ea-9d83-1ed1c9459444.png)

Stable: 
![image](https://user-images.githubusercontent.com/323878/73015996-ed7be380-3dd1-11ea-9951-729508071c6c.png)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/89149
