### ISSUE TITLE
Order of sync.enable setting is not retained

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89188]
I set up a new client and replaced local, sync.enable did not retain the same position though.

**Comment by sandy081** [comment]
`sync.enable` is always added at the end and is expected because `sync.enable` is ignored by default and cannot be retained on another machines.

**Comment by Tyriar** [comment]
Wouldn't it be better as global state/local storage then and change it exclusively through the gear menu and commands so it doesn't pollute the settings file?

**Comment by sandy081** [comment]
Global storage cannot be accessed in shared process yet and a setting is always helpful to pause/disable sync momentarily.
