### ISSUE TITLE
VSCode doesn't show poetry virtualenvs in select interpreter option

### ISSUE THREAD

**Issue by jaepil-choi** [microsoft/vscode#89182]
- VSCode Version: 1.14.1
- OS Version: 
Windows 10 pro, - 64bit (the latest)
```
PS C:\Users\Jaepil> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0
```

Steps to Reproduce:

1. Install & set up a `poetry` environment as explained in the official documentation. 
2. Try to look for available Python interpreters in the command palette. You won't see any. 

I've left [a detailed explanation](https://stackoverflow.com/questions/59882884/vscode-doesnt-show-poetry-virtualenvs-in-select-interpreter-option) on Stackoverflow. 

However, the main point is that even though [VSCode's official settings reference](https://code.visualstudio.com/docs/python/settings-reference) states that it has default `python.poetryPath` set for `poetry`, poetry-created environments' interpreters are not shown in 'Python: Select Interpreter'. 

I've also tried adding `python.venvPath": "~/.cache/pypoetry/virtualenvs"`, to my `settings.json` as suggested in https://github.com/microsoft/vscode-python/issues/8372#issuecomment-556984062 but to no avail. (I have to ask though. It seems that poetry's virtualenvs are located at `~\\AppData\\Local\\pypoetry\\Cache\\virtualenvs`, not `~/.cache/pypoetry/virtualenvs`. So why did the original issue suggested adding `~/.cache/pypoetry/virtualenvs` in the first place?) 

I also tried an absolute path, by adding `"python.venvPath": "C:\\Users\\Jaepil\\AppData\\Local\\pypoetry\\Cache\\virtualenvs"`, to the same settings, but it also doesn't work. 

At this point, I think it's VSCode's bug that doesn't properly recognize venv's path. 

Does this issue occur when all extensions are disabled?: Yes/No

99% Yes. Since Python is also an extension, this won't even run without Python extension enabled. However, any other extensions won't likely affect selecting Python interpreters.

**Comment by sbatten** [comment]
Based on your description, it seems this issue should be filed with the python extension directly. The setting you have modified to workaround this as suggested in the linked issue belongs to the python extension.
