### ISSUE TITLE
Log reason for request failure on Sync output channel

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89187]
Using local server on insiders fails due to no https but it doesn't say in the logs

```
[2020-01-23 09:58:27.765] [userDataSync] [error] Error
    at XMLHttpRequest.o.onerror (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:176:892)
```

**Comment by sandy081** [comment]
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/10746682/73102979-50b16700-3ef3-11ea-8a4d-408f91a2f622.png">


Fixed by a27c9fc6b18f5235aa0a457f5deae69e77499e47

**Comment by Tyriar** [comment]
Please also log the http code that comes back to make things clearer:

> Error: Request '.../resource/settings/latest' is not authorized.

This would be better as:

> Error: Request '.../resource/settings/latest' 401 Unauthorized

**Comment by Tyriar** [comment]
@sandy081 thanks, shouldn't you handle exceptions here as well? ie: if the code is not one of the successful options (200, 204, 304) it should also throw and print the code? It doesn't look like 404 is handled properly for example?

**Comment by sandy081** [comment]
Yes it is being handled by the respective callers of this internal method.

**Comment by Tyriar** [comment]
@sandy081 and other 4xx or 5xx errors get handled properly as well?

**Comment by sandy081** [comment]
Yes, for other unhandled errors we return a message saying `Server returned {code}`. Since these are unknown this code should be enough.
