### ISSUE TITLE
Code snippet with similar name takes precedence over variable name with parenthesis

### ISSUE THREAD

**Issue by rlrossiter** [microsoft/vscode#89197]
Issue Type: <b>Bug</b>

(Python, though likely happens in other languages as well)

I have a variable name `mod`, that when typing it as the last argument of a function is predicted by intellisense properly.

![noparen](https://user-images.githubusercontent.com/4017112/73026393-2cb42f80-3de6-11ea-91d5-4dfd7fc33a3a.PNG)

After typing the variable (without taking intellisense's suggestion) followed by the parenthesis changes intellisense's suggestion to a code snippet that has a common `od)`, taking the top spot.

![withparen](https://user-images.githubusercontent.com/4017112/73026432-3fc6ff80-3de6-11ea-8d37-ce57f68e0ce0.PNG)

When I then press enter, it injects the snippet rather than a newline.

![afterenter](https://user-images.githubusercontent.com/4017112/73026450-46557700-3de6-11ea-9b29-863d01f791ae.PNG)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-remote-workspace|mkl|0.43.1
python|ms-|2020.1.58038
remote-wsl|ms-|0.41.7
csharp|ms-|1.21.9
powershell|ms-|2020.1.0
vim|vsc|1.12.4

</details>

**Comment by jrieken** [comment]
Yes, whatever is used `prefix` for snippets is used for matching etc. If this is your own snippet, then move the parts in brackets to the snippet description, if this is an extension snippet then file an issue there
