### ISSUE TITLE
Horizontal scroll in editor doesn't work anymore

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#8919]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-28-generic (Ubuntu 16.04)

Steps to Reproduce:

1. Have a mouse with possibility to scroll horizontal and be sure it works in other apps like Nautilus (Filemanager) or Chrome.
2. Type so much text so that a horizontal scrollbar appears
3. Try to scroll horizontal

That worked once. I have a Logitech T620.

**Comment by alexandrudima** [comment]
@DasJott I wonder if this is a Chromium issue, a few months ago we updated from Chromium 45 to Chromium 49, did you experience the same issue in Chrome?

**Comment by alexandrudima** [comment]
Do you also see the issue at https://microsoft.github.io/monaco-editor/ when visiting that page in Chrome?

**Comment by DasJott** [comment]
It works in Chrome and it also works on that page https://microsoft.github.io/monaco-editor/ within the editor.

The touchpad does work on horizontal scrolling though. Hm... it is just the mouse. Strange.

**Comment by jflheureux** [comment]
I have this issue too.

Version: 1.3.1
OS: Windows 8.1
Laptop: Lenovo T440p
Pointing device: Trackpad

On  https://microsoft.github.io/monaco-editor/ the editor scrolls as expected when I'm horizontally scrolling with the trackpad.
In VSCode, the caret is moving left/right when I'm horizontally scrolling. I expect the editor to scroll instead.

**Comment by alexandrudima** [comment]
I can only believe it is a matter of time. We have the exact same code in dealing with mouse ops in both the monaco editor and in vscode. The only difference I can think of is that in vscode we're sitting on Chromium 49 and the stable Chrome version is already at 51

**Comment by DasJott** [comment]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:30:01.819Z)
- OS Version: Linux x64 4.4.0-38-generic

Works for me now! Brilliant!
