### ISSUE TITLE
Type inference issue with global variable definition

### ISSUE THREAD

**Issue by mazyvan** [microsoft/vscode#89195]
- VSCode Version: 1.41.1
- OS Version: Mac Catalina 10.15.2 

Steps to Reproduce:

Type inference only works if the `global.d.ts` file is open

![2020-01-23 2 46 18 PM](https://user-images.githubusercontent.com/10915753/73022476-48700380-3def-11ea-86b0-d2d4fb086bb8.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Do you have a jsconfig or tsconfig file?

**Comment by mazyvan** [comment]
Sorry, totally my fault. Still believe this behavior is very weird.
Maybe a suggestion message to add a `jsconfig/jsconfig` file when a `global.d.ts` is created would be nice.
