### ISSUE TITLE
Can't break on debugger extension callbacks

### ISSUE THREAD

**Issue by JayBazuzi** [microsoft/vscode#89192]
Issue Type: <b>Bug</b>

I'm trying to debug a VSCode debugger extension. A breakpoint in the main part of the file will get hit, but breakpoints in the callbacks (e.g. `setBreakPointsRequest()`) don't get hit.

I am able to repro while debugging both my extension and the vscode-mock-debug extension. 

Possibly related? The vscode-mock-debug extension doesn't stop on a breakpoint, either.

VS Code version: Code - Insiders 1.42.0-insider (c4d53a19df8799f5d49a4f49a6900c499e6fa27c, 2020-01-23T05:39:57.148Z)
OS version: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/1259628/73020099-caedc880-3dd9-11ea-99c9-ba8f3e90eddb.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (32 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by connor4312** [comment]
We since have a [new debugger](https://github.com/microsoft/vscode-js-debug/), please let us know if you're still running into problems, and if so open an issue on that repo.
