### ISSUE TITLE
Auto closing quotes in makefiles (*.mk)

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#89191]
I found a tiny issue: quotes don't auto-close in makefiles (*.mk), but brackets do. It's because makefile didn't define any `surroundingPairs` or `autoClosingPairs` in [its language-configuration.json](https://github.com/microsoft/vscode/blob/1018bfac9c969c9caa4586b09314fbf7c3fcf158/extensions/make/language-configuration.json), but did define `brackets`, and the fallback logic is [here](https://github.com/microsoft/vscode/issues/87950#issuecomment-577594415). 

I'm not an expert, but I think makefile does use double and single quotes for strings.

**Comment by rzhao271** [comment]
Brackets don't autocomplete for me now in makefiles, but I'm not sure if part of the original feature request was to keep that behaviour, hence author-verification-requested.

**Comment by jrieken** [comment]
I have a `test.mk` file, it shows Makefile at the bottom but when typing any of `(,[,{` no auto closing happens

**Comment by alexr00** [comment]
Thanks for catching!
