### ISSUE TITLE
blackbox/ignore modules for debugging in node

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#892]
Hello:

Often when I debug a node.js app, I want to toggle break on "All Exceptions".  In node, that means on **every require statement** it breaks during a `stat` check.

In most of my apps, that's quite a few require statements, and thus quite a few breaks!  The below should look familiar to other nodejs debugging devs!  Even if a _first pass_ as the feature was "Blackbox node internals", that would be a huge help!
<img width="437" alt="screen shot 2015-12-01 at 5 34 10 pm" src="https://cloud.githubusercontent.com/assets/1003261/11518809/cf0e266c-9851-11e5-9db9-d43f2d643063.png">

If you'd like to pass some pointers my way, I'd consider working a PR for the basic ignore?

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#16

**Comment by cdaringe** [comment]
thx!
