### ISSUE TITLE
Unable to start integrated terminal

### ISSUE THREAD

**Issue by Vibhav-Deo** [microsoft/vscode#89203]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open vs code
2. Open terminal(integrated)

Does this issue occur when all extensions are disabled?: Yes
![vs code](https://user-images.githubusercontent.com/45755558/73044606-60fb1f00-3ebe-11ea-92d3-72d1d891d832.PNG)

When I am trying to start integrated terminal, terminal pops up and dies saying terminal terminated with exit code 0

**Comment by Vibhav-Deo** [comment]
What might be causing this? I don't think extension is causing this because until recently it used to work it was after a recent windows update it started crashing

**Comment by Tyriar** [comment]
This issue is typically caused by anti-virus software blocking terminal processes from being launched.

**Comment by Vibhav-Deo** [comment]
Thanks a lot for responding, I'll have a look and let you know

**Comment by Vibhav-Deo** [comment]
I tried with virus protection disabled it still fails, the thing is the company that I am working with it runs for every one else except my machine

**Comment by Tyriar** [comment]
Are you sure you disabled everything? See https://github.com/microsoft/vscode/issues/86432

**Comment by Vibhav-Deo** [comment]
Hey thanks a lot you were right, I tried today again by suspending and terminating malwarebytes and my terminal started working again
