### ISSUE TITLE
I am facing this issue The terminal process command exit code{2}

### ISSUE THREAD

**Issue by gaurangjindal** [microsoft/vscode#89206]
The terminal process command 'C:\Windows\Sysnative\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})

I tried all eailer solution you posted on GitHub but none of them are working for me
system config-Lenovo,64-bit(i5-3320

**Comment by gaurangjindal** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Terminal will not open (#89198)](https://www.github.com/microsoft/vscode/issues/89198)
> * [[Winpty] The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2) (#88639)](https://www.github.com/microsoft/vscode/issues/88639)
> * [the terminal process terminated with exit  code #259 (#88262)](https://www.github.com/microsoft/vscode/issues/88262)
> * [[Conpty] Vscode, integrated terminal failed to launch (exit code: {2}) (#88008)](https://www.github.com/microsoft/vscode/issues/88008)
> * [Terminal exited with code 1 (#85561)](https://www.github.com/microsoft/vscode/issues/85561)

none is working for me let me know some other solution

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What exact Windows version? 

cc @Tyriar

**Comment by gaurangjindal** [comment]
> /needsMoreInfo
> 
> What exact Windows version?
> 
> cc @Tyriar

Lenovo,64-bit(i5-3320) cpu@2.60GHZ (intel)
RAM -4 GB
is this enough?

**Comment by gjsjohnmurray** [comment]
No, that is only about the hardware you are using. Tell us about your Windows version. One way is to open a Windows command window. The initial text that it display should include the full version string.

**Comment by EECSB** [comment]
I had this error too. The problem was my antivirus. So what solved it for me was just whitelisting the vs code installation folder in the antivirus. Hopefully, this helps someone.
