### ISSUE TITLE
Vscode 1.3 can't find system commands anymore

### ISSUE THREAD

**Issue by G3z** [Microsoft/vscode#8920]
- VSCode Version: 1.3
- OS Version: MacOS 10.11.5

Steps to Reproduce:

1. tray anything that uses external command

All extentions that use external commands can't find it (eslint, npm, ...) i see an error message which asks to install the command but it is installed and it was working in 1.2

other perhaps useful info:
i'm using zsh and i've installed node trough brew so the commands are located in `/usr/local/bin` (it's in my `$PATH`)

**Comment by wallverb** [comment]
https://github.com/Microsoft/vscode/issues/8434 - we will need to wait for insiders build - for time being start from terminal - although Project Manager extension won't work to switch between projects. Too bad it worked in 1.2 but stopped in 1.3
