### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by narottamsingh-jft** [microsoft/vscode#89208]
Issue Type: <b>Bug</b>

I work on both front-end and back-end technologies which are React, React-native and Node.js I have observed that many times intellisense stops working and sometimes i restart my vs code then suggestions again starts coming while coding but that too only happens only sometimes other than node.js for html and css intellisense works great. Please look into it. Other than that you have built a great software guys. I am amazed by the things vs code can do. For any language and every language.

Thanks
Narottam Singh
Software Engineer from India

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 3216)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.63GB (2.93GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.15

</details>

**Comment by George-BC** [comment]
Same issue using Node.js on Mac OS Catalina. Very frustrating issue, have to restart VS Code frequently.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by 3abdawy** [comment]
@mjbvz  i had the same error , it still occurs even if you disable all extensions !

**Comment by narottamsingh-jft** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

I have to test it but I don't know if this issue replicates in the insiders build version of VS Code, but mate I cannot disable the extensions some are quite crucial for the work I do. So If you are from microsoft team, you have to find a work around for that.

**Comment by mjbvz** [comment]
We cannot do really anything if an extension you have installed is causing the problem.. so make sure it's not one of them and test using the insiders build

**Comment by crinitic** [comment]
I have the same issue with all extensions disabled and VS Code 1.41.1

Will check with insider build in a couple of days

**Comment by mjbvz** [comment]
Closing as not actionable without more info from @narottamsingh-jft
