### ISSUE TITLE
Feature Request: Extension setting to prevent theme selection UI on install

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#89201]
We would like to bundle a theme with our extension.  Is there a way we can opt out of the theme selection UI that appears on install of the extension?  If not, could an option for this be added?

Using a separate extension for the theme and making our primary extension dependent on that extension appeared to circumvent the selection UI.  Is this behavior we can rely on?

**Comment by sandy081** [comment]
There is not such an option. Recommendation in such cases is to have theme as a separate extension and create a pack.
