### ISSUE TITLE
File picker: reaching C:\ should not offer to go up more

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89209]
Steps to Reproduce:

1. enter C:\ into picker
2. still see a ".." to go with

![image](https://user-images.githubusercontent.com/900690/73050084-f4146480-3e7e-11ea-8bf3-5beffae1ea28.png)

Not sure if related, but this was on Windows with a remote connection to windows itself (via the test remote scenario running out of sources).

**Comment by alexr00** [comment]
Windows -> Windows remote specific.
