### ISSUE TITLE
Improve handling of token refresh while offline

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#89200]
Issue Type: <b>Bug</b>

Currently, the built in account extension will attempt to refresh the access token before it expires. If it fails, it deletes the stored refresh token and sends a change event to core that no sessions are available.

If the user goes offline after signing in, then refresh will fail due to the lack of connection. (Or in @sbatten's case, changing networks also seems to cause refresh to fail). When this happens, it's confusing to show a badge on the gear to sign in again. One way we could handle this is for the extension to still remove the session that now has an expired token, but keep the refresh token if the error may be temporary, and retry again a bit later. In the sessions change event, the core could test to see if the user is online before updating the UI, and would need to tell the sync service to stop.

@sandy081 Thoughts?

VS Code version: Code - Insiders 1.42.0-insider (c4d53a19df8799f5d49a4f49a6900c499e6fa27c, 2020-01-23T05:38:55.065Z)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
> in the sessions change event, the core could test to see if the user is online before updating the UI, and would need to tell the sync service to stop.

Not sure if I understand this. How can core could test this? It might be that this could be different for different auth providers.

IMO all this logic should be in the extension and extension should signal core with proper events.

Looks related to https://github.com/microsoft/vscode/issues/88577#issuecomment-578755119

**Comment by RMacfarlane** [comment]
OK, I've just made a change to add an "Unavailable" status for auth in the `userDataSync` workbench contribution. Now, when refresh fails due to a network error, it will retain the refresh token, but remove the access token from the session and send a change event. This sets the "Unavailable" status while the extension continues retrying up to 3 times to refresh.

Still pending:
- What do we show in the gear menu when auth status is "Unavailable"?
- Need to add another long timeout to the extension to check for reconnection

**Comment by RMacfarlane** [comment]
Added a 30 minute poll when refreshing fails to check if the network is available again. https://github.com/microsoft/vscode/commit/b98f647ec997bd8b86157f6dce6443571c933fb1

Since https://github.com/microsoft/vscode/issues/89538 tracks the offline UX, this is complete
