### ISSUE TITLE
Install Extension does not work

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#8921]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-28-generic (Ubuntu 16.04)

Steps to Reproduce:

1. Open VSCode
2. Open Extension view
3. Type PHP in search field
4. Click on "Install" Button
    - neither the Button(s) in the left panel nor those in the detail view on the right are working.

No chance for Extensions anymore? Bummer...

**Comment by jltrv** [comment]
I had the same bug, but I fixed it by killing the old vscode processes from the previous version that where still running somehow.

**Comment by DasJott** [comment]
Yeah, after closing all (visible) instances of vscode, there were still plenty of vscode processes running!
Killed them all and now it works.

Thanks!
