### ISSUE TITLE
There is a problem with the smart completion function

### ISSUE THREAD

**Issue by endingly** [microsoft/vscode#89211]
Issue Type: <b>Bug</b>

After using the first completion, the next completion will fail in some areas. It look like 
![image](https://user-images.githubusercontent.com/38353844/73054251-e84b9100-3ec4-11ea-9f64-87ee6d44c9c8.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.28GB free)|
|Process Argv|C:\Users\47155\Desktop\go.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.5.0
prettier-vscode|esb|3.18.0
code-runner|for|0.9.15
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.41.2
Go|ms-|0.12.0
material-icon-theme|PKi|3.9.2
code-settings-sync|Sha|3.4.3
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Does this happen after you reload with all extensions disabled? If yes, please provide details of simple repro steps. An animated GIF screen recording may also be useful.
