### ISSUE TITLE
QUICK FIX TOOL COMMAND NOT WORKING

### ISSUE THREAD

**Issue by JulioTheCode** [microsoft/vscode#89223]
Issue Type: <b>Bug</b>

Command "CTRL + ." not working Latest VSCode on windows 10 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.15GB free)|
|Process Argv|E:\CREDIX\FlutterDemoApps\product_scoped_model_app|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
delphi-keybindings|ale|8.1.0
flutter-snippets|ale|2.0.0
vscode-eclipse-keybindings|alp|0.10.0
dart-data-class-generator|Ben|0.3.6
puzzle-vscode|big|0.0.2
vscode-standardjs-snippets|cap|0.8.9
ccs-flutter-color|cir|0.0.3
jsontotype|dan|0.0.3
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
vscode-eslint|dba|2.0.15
vscode-html-css|ecm|0.2.3
vscode-flutter-i18n-json|ess|0.28.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
php-file-types|fet|1.2.1
sepaswitch|Fut|1.0.2
flutter-stylizer|gml|0.0.14
vscode-flutter-files|gor|1.7.0
gc-excelviewer|Gra|2.1.32
vscode-emacs|hir|0.1.1
smarty|imp|0.3.0
vuetypes-snippets|inc|0.0.3
TypeScriptImport|kev|1.17.0
dart-import|lua|0.1.6
flutter-mvvm-architecture-generator|mad|1.6.0
dartsass|mal|0.2.5
f-orm-m8-generator|mat|0.1.8
rainbow-csv|mec|1.5.0
vscode-language-pack-fr|MS-|1.41.2
python|ms-|2020.1.58038
js-atom-grammar|ms-|0.1.14
notepadplusplus-keybindings|ms-|1.0.5
sublime-keybindings|ms-|4.0.6
vs-keybindings|ms-|0.2.0
awesome-flutter-snippets|Nas|2.0.3
dart-syntax-highlighting-only|osc|1.0.0
dartgettersetter|Pet|0.0.4
typescript-hero|rbb|3.0.0
govscode-flutter-dart|Tap|0.0.4
snippets-view|use|0.2.7
vim|vsc|1.12.4
JavaScriptSnippets|xab|1.7.2
dart-built-value-snippets|yon|1.1.1
dart-extensions-snippets|Zar|1.0.0

</details>

**Comment by sbatten** [comment]
@JulioTheCode  can you provide more details about the behavior you are experiencing?
