### ISSUE TITLE
Selecting a solution file shows the source instead of loading all the projects

### ISSUE THREAD

**Issue by netbitshift** [microsoft/vscode#89225]
Choose File > Open file, choose a recently created solution file created with VS 2019.  You get the source of the solution file instead of VS Code loading the projects within in it

The docs say otherwise - that the projects are supposed to be loaded

> Selecting a *.sln file opens a MSBuild-project. It will load the referenced *.csproj projects and sibling or descendant project.json files but no other project files that are referenced from the solution file.

https://code.visualstudio.com/docs/languages/csharp

**Comment by gjsjohnmurray** [comment]
Which extensions have you installed?

**Comment by netbitshift** [comment]
code --install-extension clintonrost.theme-firefox-devtools
code --install-extension codemooseus.vscode-devtools-for-chrome
code --install-extension firefox-devtools.vscode-firefox-debug 
code --install-extension formulahendry.dotnet-test-explorer    
code --install-extension jmrog.vscode-nuget-package-manager    
code --install-extension ms-mssql.mssql
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.powershell
code --install-extension ms-vsts.team
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension vincaslt.highlight-matching-tag

**Comment by gjsjohnmurray** [comment]
I'm guessing it's the job of the ms-vscode.csharp extension to handle solution files. In which case your issue probably needs to be raised at https://github.com/OmniSharp/omnisharp-vscode/issues

**Comment by netbitshift** [comment]
Ahh, good point.  Thanks
