### ISSUE TITLE
[semantic][typescript] `Object` in `Object.create` is classified as an interface

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#89221]
Have a piece of code like:
```
this._modelCreationOptionsByLanguageAndResource = Object.create(null);
```

Go and inspect `Object`:
![image](https://user-images.githubusercontent.com/5047891/73065936-0bfedf00-3ea5-11ea-9830-a08126807a41.png)

Currently, this is messing with my underline rules and is being underlined even though it should not ...

**Comment by aeschli** [comment]
I pushed a fix for that: https://github.com/microsoft/vscode/commit/13dd07b8a811d61b9b1f068a0093be915dff4d0e
