### ISSUE TITLE
Extensions side bar width

### ISSUE THREAD

**Issue by Fania** [Microsoft/vscode#8922]
- VSCode Version: 1.3.0
- OS Version: Win 10 - 1511

**Extensions view needs custom width for side bar.**

I keep my side bar neat and narrow which works fine for the normal explorer view.
But when browsing the new extensions view the narrow size of the side bar is clearly too small to read anything useful. Either make the width for the extensions view automatically wider or change what is shown in the side bar to the names of extensions only and keep any buttons to uninstall or install etc to the detail view on the right.

![vscodeext](https://cloud.githubusercontent.com/assets/361077/16683502/24405094-44f8-11e6-8c66-35d0d517c0eb.PNG)

**Comment by bpasero** [comment]
One idea is that the viewlet could implement the `getOptimalWidth()` function and then a double click on the sash would make it large enough to show everything.

**Comment by joaomoreno** [comment]
I think what I'll do is just hide the icons when the width is that small.

**Comment by Fania** [comment]
It works great now. Thanks for fixing it!
