### ISSUE TITLE
"Screencast mode" shows letters incorrectly when typing using Accessibility tools (like robotjs)

### ISSUE THREAD

**Issue by momakes3** [microsoft/vscode#89228]
Version: 1.42.0-insider
Commit: c4d53a19df8799f5d49a4f49a6900c499e6fa27c
Date: 2020-01-23T05:38:55.065Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

Steps to Reproduce:

1. Turn on "Screencast Mode"
1. Use a remote keyboard controller app or https://github.com/octalmage/robotjs 
2. Type CMD + A, then unselect or type A a couple of times
3. Now writing any letter with robotjs, **will be typed correctly in editor** but shown **incorrectly as letter A** in screencast mode.

Using `KeyCastr` you can see the bug demonstrated:

![photo_2020-01-24_17-33-08](https://user-images.githubusercontent.com/56743114/73075001-1b475200-3ed0-11ea-95ac-7179c2b56797.jpg)

Does this issue occur when all extensions are disabled?: Yes

Tested on another machine and the same as well.

**Comment by isidorn** [comment]
@lszomoru I am fine with closing this as out of scope (from the accessibility point of view)
