### ISSUE TITLE
Debugger restart not working anymore

### ISSUE THREAD

**Issue by JaderCM** [microsoft/vscode#89238]
Issue Type: <b>Bug</b>

When click menu Debug - Restart debugging is the same as Stop debugging.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.1
git-graph|mhu|1.21.0
powershell|ms-|2020.1.0
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.5
vetur|oct|0.23.0
html-preview-vscode|tht|0.2.5
es-quotes|vil|0.2.6

</details>

**Comment by JaderCM** [comment]
Back to work.

**Comment by JaderCM** [comment]
Happening again.

**Comment by connor4312** [comment]
If this is still happening, please let us know what debugger you're using.
