### ISSUE TITLE
Test: "files.defaultLanguage": "${activeEditorLanguage}"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89233]
Refs: https://github.com/microsoft/vscode/issues/78903

- [x] macOS @misolori
- [x] anyOS @bowdenk7

Complexity: 2

**Steps:**
* configure `"files.defaultLanguage": "${activeEditorLanguage}"` in settings
* verify that each untitled file you open will take the language mode from the currently active file if any
* verify this setting is suggested in settings help and its description makes sense

**Comment by misolori** [comment]
This works really well 👏. Any thoughts on making `${activeEditorLanguage}` the default? I really like that it defaults to plain text when there aren't any active editors.

**Comment by bowdenk7** [comment]
👍 not sure about making it the default because I know a lot of people use it as a notepad substitute, and depending on what kind of language service you get it's really distracting:

![image](https://user-images.githubusercontent.com/820883/73291141-7a4ce580-41b4-11ea-8513-f14d5a7fbdcb.png)

**Comment by bpasero** [comment]
> This works really well 👏. Any thoughts on making ${activeEditorLanguage} the default? I really like that it defaults to plain text when there aren't any active editors.

I am also not 100% sure this is good to do. Given we also now automatically flip the mode as soon as you copy/paste text, I think it gets less likely that you end up in text mode and not in a specific mode.
