### ISSUE TITLE
Test: backup and hot-exit

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89236]
Refs: https://github.com/Microsoft/vscode/issues/84672

- [x] windows@RMacfarlane
- [x] macOS @JacksonKearl

Complexity: 3

This milestone, backup / hot-exit was rewritten to work with custom editors. This test plan item is to verify there are no regressions for existing text based editors.

**Steps:**
* work with dirty files and dirty untitled editors
* with default settings you should be able to quit VSCode (File > Exit) without getting asked to save and all dirty content is restored after next startup
* turn hot exit off in settings and verify that quitting now will ask you to save/revert/cancel for each file or untitled editor
* verify each of save/revert/cancel works as expected and you can close VSCode (unless you picked "Cancel")
* verify that you can kill VSCode (literally the process) with dirty files and upon restart your content is still preserved (we backup after 1s delay after making content changes)

**Comment by RMacfarlane** [comment]
Works great!
