### ISSUE TITLE
"Group" is read when editor is focused

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#89230]
Turn on VoiceOver, focus an editor
The following is read
"x editor, Editor Group 1 group". 

1. group should not be read
2. Editor Group 1 should only be read if there is more than one group

fyi @ivanfetch

**Comment by isidorn** [comment]
Could not fix 1), since "group" is automatically read by VoiceOver. Suggestions on how to fix this are welcome.
2) I fixed, fyi @bpasero on my approach

**Comment by bpasero** [comment]
@isidorn can we have a debt item for Feb to fix it properly? I think we are happily setting this:

`this.editorContainer.setAttribute('aria-label', this.computeAriaLabel());`

But we actually do not update the editor options `ariaLabel` property at all. Neither from group changes nor from label changes. In fact I think we are computing the aria label twice: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/textEditor.ts#L97

**Comment by bpasero** [comment]
PS: I even wonder if we should go back and not update the aria label on each label change in untitled editors. After all that might be very confusing for users that need screen readers. We could simply just set the `Untitled-<N>` thing and it would probably be fine.

**Comment by isidorn** [comment]
@bpasero Yeah, I was just copying what you were doing on the label change. I will create a debt item

As for untitled editors, having the aria label `Untitled <N>` makes perfect sense for me. Feel free to change that.

**Comment by sandy081** [comment]
@isidorn Group 1 is not read when there are more than one group

![Uploading image.png…]()

**Comment by isidorn** [comment]
We properly update the `aria-label` on the vscode side, however VoiceOver does not properly read the updated one. 
However since we already have a debt item for this here https://github.com/microsoft/vscode/issues/89621
I would prefer to keep this closed and as part of that debt work check if we can do something better

**Comment by isidorn** [comment]
Since @bpasero fixed this in the end, I have just verified it works fine, Thus adding verified label.
