### ISSUE TITLE
Data Science library ipykernel is not installed. Install? 

### ISSUE THREAD

**Issue by BillmanH** [microsoft/vscode#89242]
Newly created conda env can't open in Python interactive window. Other envs are loading fine.  Even after multiple restarts. 

![image](https://user-images.githubusercontent.com/10108711/73088026-5160e380-3e88-11ea-8e25-e7d6ab07828d.png)

Then you click yes and the error: 
```
PS C:\Users\william.harding\Documents\repos\textanalytics> conda activate env-pjx
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ conda activate env-pjx
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

FYI, my path in settings is specified correctly as: 
`"python.pythonPath": "C:\\Users\\william.harding\\AppData\\Local\\Continuum\\anaconda3\\python.exe",`

The interpreter won't open the environment and will just crash. 

However I can just open the command line and confirm that ipykernel is installed in that environment.  I can also 
```
(env-pjx) C:\Users\william.harding>conda install --name env-pjx ipykernel
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

```

![image](https://user-images.githubusercontent.com/10108711/73088878-faf4a480-3e89-11ea-9b92-729b4031185c.png)

Steps to Reproduce:

1.  Create a new env, without installing ipykernel
2. Go into visual studio and try to activate that env.

**Comment by BillmanH** [comment]
Found it out. It came from having py 3.8 installed in the env, which Jupyter notebooks doesn't support. However the error suggests that it's the Ipykernel and then tries to install it which is not the issue.  A solution to the problem would be to check the compatability of the python version before spitting out the error message.

**Comment by sbatten** [comment]
I think the first image is missing something that helps here. However it seems you have fixed your issue. In the future, please file python related issues with the Python extensions directly. Thanks
