### ISSUE TITLE
HTML tag is displayed in documentation popup

### ISSUE THREAD

**Issue by thephp1over** [microsoft/vscode#89241]
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce (**This works only some times**):

1. Hovering over a function

Enabled extensions:
php-intellisense | fel | 2.3.14

Screenshot:

![image](https://user-images.githubusercontent.com/59211472/73087041-0de99200-3ee7-11ea-81b8-6f281b8f1ed6.png)

**Comment by thephp1over** [comment]
@octref 
@sbatten 

Hi, After a while I could figure out how to reproduce issue in a way that always works:

1. Inside a valid .php file with proper opening tag (<?php), Try typing a name of a PHP function like print_r
2. Type opening parentheses '(' 
3. VS's autocomplete will close the parentheses and display documentation popup which is un-formatted

![image](https://user-images.githubusercontent.com/59211472/74744664-e1bbf980-5277-11ea-8979-1e954795109c.png)

The bug does **not** occur if you try hovering **previously typed** function name!

---
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by octref** [comment]
Please open issue for the PHP extension you are using.

**Comment by felixfbecker** [comment]
This is a VS Code issue. The PHP language server returns proper markdown - HTML is valid inside markdown. https://github.com/microsoft/vscode/issues/40607

**Comment by octref** [comment]
From LSP website:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#markupContent

> *Please Note* that clients might sanitize the return markdown. A client could decide to remove HTML from the markdown to avoid script execution.

@jrieken What's your thoughts?

**Comment by mjbvz** [comment]
As covered in #40607: we support a subset of markdown (without inline html) and then sanitize the html generated from that markdown. This is by design and is how our rendering has worked for a long time
