### ISSUE TITLE
F3 with manual edits combines all changes into a single undo/redo

### ISSUE THREAD

**Issue by dgarner-boost** [microsoft/vscode#89250]
Issue Type: <b>Bug</b>

Open a blank file in the text editor
Add these lines:
```
test 1
test 2
test 3
test 4
```
Press Ctrl+F & search for "test"
Modify the word "test" on 1st line to any random text
Press F3 to go to the next occurence
Modify the word "test" on 2nd line to any random text
Press Ctrl+Z, notice that it performs an undo across all changes.
Press Ctrl+Y, notice that it performs a redo across all changes.

Bug Explanation:
This is contrary to every other text editor I've ever used. This is not a global find/replace, the lines are being edited by hand. The F3 is just being used to search the code to find instances that you may want to manually change, but the change is different across each line.

Correct Behavior:
Undo/Redo should allow you to cycle through each edit 1 at a time, rather than grouping them as a single edit.

Reasoning:
If you searching across a large file & make hundreds of little edits, after making 1 mistake you can't hit CTRL+Z to fix the 1 mistake, or else you'll have to start all over from the beginning.

Troubleshooting:
I've disabled all extensions & the issue persist. I've also tried on other machines & got the same result.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (21.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sbatten** [comment]
I cannot reproduce this following the repro steps. Can you possibly share a video with your experience with screencast mode enabled?

**Comment by dgarner-boost** [comment]
https://www.youtube.com/watch?v=m_kdSgcvZ0Y

**Comment by sbatten** [comment]
@dgarner-boost thanks, not sure what was different between my first attempt and this one but the video helped me repro the issue.
