### ISSUE TITLE
[snippets] Need way for extension settings to affect snippet content

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#89258]
I'm working on some better snippets for Material-UI.  Unfortunately, users will have such different needs that there's no one-size-fits-all extension.  For instance, they might want a controlled Input:

```
<Input name={$1} value={$2} onChange={$3} $0 />
```
Or an uncontrolled Input:
```
<Input name={$1} defaultValue={2} $0 />
```
But having long snippet names to distinguish the two like `mui-input-controlled` and `mui-input-uncontrolled` would kind of suck.  I think most users are only going to ever use one kind.  It would be a lot better to have a single `mui-input` snippet that outputs one or the other based upon an option users select in the extension settings.

In general, snippets and the DSL for variable transformations are really half-baked and limiting.  It would be the best thing ever if there were a JS API for more advanced snippets, where arbitrary JS could be used to determine snippet content and variable transformations.

**Comment by jrieken** [comment]
>  It would be the best thing ever if there were a JS API for more advanced snippets, where arbitrary JS could be used to determine snippet content and variable transformations.

Yes, that's the completion item provider API: https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample (at least that will gives you most of what you need). Simply return a snippet-type completion from there
