### ISSUE TITLE
Code colorization gets reset/lost

### ISSUE THREAD

**Issue by gevorggalstyan** [microsoft/vscode#89254]
Issue Type: <b>Bug</b>

After opening a file (typescript/javascript) the colorization gets weird/lost after a second or two. This is happening with or without any extensions. This is happening with any color theme selected.

![ezgif-2-d498fe1b29db](https://user-images.githubusercontent.com/2598355/73102484-5dda5000-3f0b-11ea-873e-b19971376b4d.gif)

VS Code version: Code - Insiders 1.42.0-insider (f3dbcea32a6b52ce819dc863e778fb8517357f61, 2020-01-24T05:33:35.045Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.13.0
quitcontrol-vscode|art|3.1.3
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.18.0
auto-rename-tag|for|0.1.1
vscode-pull-request-github|Git|0.14.0
todo-tree|Gru|0.0.166
rest-client|hum|0.23.1
dotenv|mik|1.0.1
HTMLHint|mka|0.6.0
python|ms-|2020.1.58038
js-debug-nightly|ms-|2020.1.33183
vscode-typescript-next|ms-|3.8.20200123
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.23.0
vscode-versionlens|pfl|0.24.0
tslint-vue|pro|1.5.6
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.6.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
sonarlint-vscode|Son|1.13.0
code-spell-checker|str|1.7.21
language-stylus|sys|1.11.0
nativescript|Tel|0.11.0
stylus-supremacy|thi|2.13.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.4
quokka-vscode|Wal|1.0.274

</details>

**Comment by markovicdenis** [comment]
Maybe this is related to the new "semantic highlighting feature"? You could try disabling it in the settings.

<img width="543" alt="Screenshot 2020-01-24 at 21 49 18" src="https://user-images.githubusercontent.com/6482823/73103073-81919c00-3ef3-11ea-8524-476aa05cf2a9.png">

**Comment by gevorggalstyan** [comment]
That was it. When I disabled it the colors came back.

**Comment by aeschli** [comment]
We had a bug that made that all semantic colors where white. That's fixed now.
A color change after a few second is intended, but it should improve the coloring. 

Please reopen if you still see a problem.
