### ISSUE TITLE
Fira Code 'onum' stylistic setting turns off font ligatures

### ISSUE THREAD

**Issue by efc** [microsoft/vscode#89253]
Issue Type: <b>Bug</b>

With the following settings all is good and ligatures work:
```
    "editor.fontFamily": "FiraCode-Retina, monospace",
    "editor.fontLigatures": "'ss01', 'zero'",
```
However, if I add the `onum` stylistic set, then the ligatures stop working (although the `ss01` and `zero` still are effective):
```
    "editor.fontLigatures": "'ss01', 'zero', 'onum'",
```
Note that adding `calt` (as suggested in other issues) does _not_ help:
```
    "editor.fontLigatures": "'ss01', 'zero', 'onum', 'calt'",
```
Why does using oldstyle numerals `onum` break the regular ligatures in VS Code when I'm using Fira Code Retina on macOS?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|40.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
atlascode|atl|2.3.2
codestream|Cod|6.0.0
vscode-simpler-icons|dav|1.6.5
githistory|don|0.4.13
gitlens|eam|10.2.0
vscode-statusbar-debugger|fab|2.0.6
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.1
applescript|idl|0.18.1
sublime-babel-vscode|jos|0.2.10
favorites|kdc|2.4.5
vscode-phpfmt|kok|1.0.30
fish-ide|lun|0.4.0
rainbow-csv|mec|1.5.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.9.0
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.41.7
vscode-remote-extensionpack|ms-|0.19.0
debugger-for-chrome|msj|4.12.6
php-docblocker|nei|2.1.0
language-liquid|nei|0.1.1
vscode-yaml|red|0.6.1
fish-vscode|sky|0.2.1
sass-indented|syl|1.7.3
wordpress-snippet|tun|1.1.5
code-navigation|vik|0.2.0
quokka-vscode|Wal|1.0.274
wordpress-toolbox|wor|1.3.6
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

**Comment by efc** [comment]
I have reviewed the other Fira Code and stylistic set issues and do not think this one is a duplicate. At least, none of those fixes resolves this issue.

**Comment by ArturoDent** [comment]
You could try `ss20` instead of `onum` - they appear to add the same set.  Otherwise, uninstall all Fira code fonts and reinstall v2.

**Comment by efc** [comment]
Thanks, @ArturoDent, deleting the v2 fonts I had and reinstalling them on my Mac seemed to resolve the `onum` issue.
