### ISSUE TITLE
editor.snippetSuggestions Setting -  Set order based on file type

### ISSUE THREAD

**Issue by kknopper** [microsoft/vscode#89259]
It would be cool to be able to set the editor.snippetSuggestions order based off the current file type.

For example, in HTML files, I want the setting to be "top" to populate the included emmet snippets at the top. But for a CSS file, I want the snippets to show up on the bottom so that the IntelliSense shows up on top.

Possible format below:
```
"editor.snippetSuggesions": {
  "*.html": "top",
  "*.css": "bottom"
}
```

**Comment by gjsjohnmurray** [comment]
Can you do this using language specific settings?

https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

**Comment by kknopper** [comment]
@gjsjohnmurray I had no idea you could do this! Thank you.

Closing.
