### ISSUE TITLE
[1.42] The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#89252]
Issue Type: <b>Bug</b>

Steps to reproduce are extremely simple

1. Open code-insiders --disable-extensions

2. Create a new Untitled file

3. Set the file language to `Javascript` by clicking on the bottom right of the status bar

4. Observe as it crashes shamefully

Here is the console trace: [console.log](https://github.com/microsoft/vscode/files/4110590/console.log)

Duplicates exist but are closed and are about previous vscode versions.

VS Code version: Code - Insiders 1.42.0-insider (f3dbcea32a6b52ce819dc863e778fb8517357f61, 2020-01-24T05:29:44.794Z)
OS version: Linux x64 4.15.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3534)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|15.51GB (1.92GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After you install that extension and restart VS Code, do you still see this issue?

**Comment by sguillia** [comment]
Does not reproduce anymore with the following version

```
Version: 1.42.0-insider
Commit: be9c72410acc677070685a616773b122f4c5e141
Date: 2020-01-29T05:36:49.901Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-74-generic
```
