### ISSUE TITLE
issue with terminal accessibility and having to much output

### ISSUE THREAD

**Issue by tayarndt** [microsoft/vscode#89264]
Issue Type: <b>Bug</b>
re
1. Please type a large python file.
2. Then use the built-in terminal to run it.
3. You will notice the screen reader will say too much output navigate to rows manually. The ode is syntactically correct and runs fine on external terminals.
Here is speech output from integrated terminal.
This is for my programming assignment. I haven't had this issue before though.
how many days does your class meet? 
3
how many weeks are in the semester? 
1
5
what is the price of gas for one gallon? 
1
1
what is the price of gas for one gallon? 
2
.
8
0
what is your cars MPG? 
2
what is your cars MPG?2 
0
how far do you have to travel one way? 
1
0
Too much output to announce, navigate to rows manually to read ********** RIDE SHARING APP ********** DATA YOU PROVIDED Gas costs 2.8 per gallon Car averages 20 mpg Class meets 3 days/week 15 weeks/semester Distance to Parkview 10 miles 1-way FIXED GENERIC COST 0.25 per mile FYI RESULTS 45 round trips/semester 900 total miles/semester 
it doesn't read the whole program
Now here is the cmd output. You notice it reads the entire program.
1_ride_share.py                                   
how many days does your class meet?                                                                                     
2
2
3
how many weeks are in the semester?                                                                                     
1
5
what is the price of gas for one gallon?                                                                                 
3
3
2
.
8
0
what is your cars MPG?                                                                                                  
2
0
how far do you have to travel one way?                                                                                  
1
0
 
********** RIDE SHARING APP **********                                                                                  
DATA YOU PROVIDED                                                                                                       
Gas costs 2.8 per gallon                                                                                                
Car averages 20 mpg                                                                                                     
Class meets 3 days/week 15 weeks/semester                                                                               
Distance to Parkview 10 miles 1-way                                                                                     
FIXED GENERIC COST                                                                                                      
0.25 per mile                                                                                                           
FYI RESULTS                                                                                                             
45 round trips/semester                                                                                                 
900 total miles/semester                                                                                                
7.80                                                                                                                    
COST FOR THE SEMESTER                                                                                                   
1 person alone: 351.00                                                                                                  
2 people sharing: 175.50                                                                                                
per person                                                                                                              
3 people sharing: 117.00                                                                                                
per person                                                                                                              
C:\Users\'\Dropbox\college\current 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (11.48GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.6.0
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
csharp|ms-|1.21.9
vsliveshare|ms-|1.0.1510
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by tayarndt** [comment]
I tried the latest insiders version of vs code and still getting the same issue. I did a much more simple test to tes this and here is the code. You will notice it stops reading fully after 19-20 numbers in the for loop. I read on another issue that this issue has to deal with the dom and have a 20 line buffer for terminal for screen readers. I would like to see this issue fixed as i do lots of collaboration in vs code and it is nice to read my entire output.
Here is the code.
I can provide recordings if you want me to.
for i in range(0,21):
    print(i)
Thanks
 Taylor

**Comment by Tyriar** [comment]
When there is too much data to read the intent was to navigate the rows manually if you need to read the full output (ctrl+up/down in terminal when accessibility mode is on). Another problem you might be seeing is that the terminal backend "conpty" reprints the screen sometimes which could result in duplicate text being read out?
