### ISSUE TITLE
Search editor: should initially report as dirty if loaded from backup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89267]
Steps to Reproduce (macOS):

1. open a search editor
2. mark it dirty (notice how the window reports dirty state via the black dot on the close button)
3. close vscode
4. start vscode
5. => 🐛 no dirty indication in the black dot of the close button

I believe this is caused by this: when you restore the search editor and find a backup, even though you put the contents of the backup into the editor, you do not set the input as dirty. So there is no dirty change event on the input.

**Comment by bpasero** [comment]
I think this issue is obsolete if https://github.com/microsoft/vscode/issues/89268 is resolved.

**Comment by JacksonKearl** [comment]
I cant reproduce this... I restore dirty state in the InputFactory, here: https://github.com/microsoft/vscode/blob/8e77e9f555392b072fc316e69173441793f3356c/src/vs/workbench/contrib/search/browser/searchEditorInput.ts#L285

**Comment by bpasero** [comment]
@JacksonKearl for this to reproduce you need to close VSCode and start it and not reload the window. I can still reproduce. 

![image](https://user-images.githubusercontent.com/900690/73240147-5e3e4980-419e-11ea-9e3c-a140dddc8ef0.png)

**Comment by bpasero** [comment]
Again, I think the correct model here is to NOT register as working copy so this should be fixed once we do something like https://github.com/microsoft/vscode/issues/89268

**Comment by JacksonKearl** [comment]
@bpasero #89406 would fix this. Let me know if its a reasonable change.

**Comment by bpasero** [comment]
Yeah, commented. Will need more changes I think. And since it does not reproduce for files nor untitled, I think they are sending out more events.

**Comment by bpasero** [comment]
Moving to Feb to verify in endgame via https://github.com/microsoft/vscode/commit/29a15dd045a9d6d7e633944ea30dad0f8366bdc0
