### ISSUE TITLE
Organize imports removes unused imports errors even when validate is false

### ISSUE THREAD

**Issue by BarakBD-Globality** [microsoft/vscode#89263]
- VSCode Version:
Version: 1.42.0-insider
Commit: f3dbcea32a6b52ce819dc863e778fb8517357f61
Date: 2020-01-24T05:33:35.045Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

- OS Version:
OS: Darwin x64 18.7.0

Steps to Reproduce:
settings.json:
```
    "javascript.format.enable": false,
    "typescript.format.enable": false,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
```
vscode will remove lines with ts errors, even though I am using eslint (no TSlint package or vs code extension installed):
`import loc from './locale.yml'; // eslint-disable-line no-unused-vars`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/36085
