### ISSUE TITLE
Add extension disable feature

### ISSUE THREAD

**Issue by Aukstkalnis** [Microsoft/vscode#8926]
There is no extension disable feature. If we want to temporally to disable one extension we have to uninstall it and when to enable it we have to download it and install. What if there is no internet around? In my opinion, this is not right.

**Comment by RobertoMalatesta** [comment]
This would be a nifty thing.

**Comment by joaomoreno** [comment]
#2882

**Comment by joaomoreno** [comment]
@Aukstkalnis as a workaround, you can always move the extension's folder out of `.vscode/extensions` and then place it back in.
