### ISSUE TITLE
Asterix causing HTML tags in red

### ISSUE THREAD

**Issue by Pieter-1337** [microsoft/vscode#89276]
When using an asterix (*) in html tags the html layout marks some tags or attributes as red or green.
This has no effect on the workings of an app.

When removing the * from matCellDef as seen in the photos below the issue resolves itself.
Would be nice if this would work as before and just accepted these kind of tags/attributes

![withAsterix](https://user-images.githubusercontent.com/24230642/73123995-41372a00-3f96-11ea-9dee-7fbbcde559c5.png)
![withoutAsterix](https://user-images.githubusercontent.com/24230642/73123996-41cfc080-3f96-11ea-9539-b8d4f7adfc06.png)

**Comment by vedpmehta** [comment]
I am also facing an issue.
after "Let" it consider it as Js file and layout color got change.
In my case if i remove * it gives me error. (See screenshots)

![Screen Shot 2020-01-28 at 12 48 15 PM](https://user-images.githubusercontent.com/53899376/73243100-c3109880-41cc-11ea-91ef-f66431e52976.png)
![Screen Shot 2020-01-28 at 12 49 59 PM](https://user-images.githubusercontent.com/53899376/73243106-c6a41f80-41cc-11ea-84b9-ffa46d84e7e8.png)

**Comment by alexr00** [comment]
My test text:
```html
<ng-container matColumnDef="Selector">
    <td mat-cell *matCellDev="let person">
        <mat-checkobx></mat-checkobx>
    </td>
</ng-container>
```
Looks fine:
![image](https://user-images.githubusercontent.com/38270282/73650127-b33bfd00-4681-11ea-97e5-6c2629fc1ebf.png)

Please try again with all installed extensions disabled.

**Comment by rosostolato** [comment]
I tested it here too and disabling `Angular Language Service` extension fixed the issue

**Comment by vedpmehta** [comment]
Yes , Angular Language Service extension is the problem.
Thanks
