### ISSUE TITLE
$tsc-watch pattern is too strict

### ISSUE THREAD

**Issue by Wutcake** [microsoft/vscode#89273]
Hello,

I spent the last couple of hours trying to work out why I wasn't able to follow the starter guide for writing you own VSCode Extension (https://code.visualstudio.com/api/get-started/your-first-extension). The issue I was encountering was being unable to debug the application, as it would just hang in the PreLaunch step, never getting around to actually performing the launch task.

I have now discovered, that the reason is because of the fairly narrow date format defined in the /extensions/typescript-language-features/package.json file, specifically the `tsc-watch` problem matcher.

My `npm run watch` would output messages like this:
```[16.21.03] Found 0 errors. Watching for file changes.```

To get it working I had to change the `beginsPattern` and the `endsPattern` to be more permissive, as the predefined date/time format did not match what was on my PC (Windows 10, da-dk, with English as the OS language).

The changes resulted in the following regexes:
```
"beginsPattern": {
    "regexp": "^\\s*(?:message TS6032:|\\[?\\D*\\d{1,2}[:./]\\d{1,2}[:./]\\d{1,2}\\D*(?:\\]| -)) File change detected\\. Starting incremental compilation\\.\\.\\."
},
"endsPattern": {
    "regexp": "^\\s*(?:message TS6042:|\\[?\\D*\\d{1,2}[:./]\\d{1,2}[:./]\\d{1,2}\\D*(?:\\]| -)) (?:Compilation complete\\.|Found \\d+ errors?\\.) Watching for file changes\\."
}
```
Note, that the changes are only in the number separator (I required `.`, but I figured some date/formats might use `/`). (From `:` to `[:./]`)
Below, I have included the version numbers from VSCode as well.

```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```
Adding this change may save the time of someone else in the future, so I figured I would post it. Hopefully you will have the time to make the change in the coming versions.

**Comment by alexr00** [comment]
Based on the very helpful comment here: https://github.com/microsoft/vscode/issues/46373#issuecomment-376114977
`/` isn't actually used. Will add the `.` though.

**Comment by alexr00** [comment]
This is tough to verify without changing your system language to something that uses alternate time separators. Instead, verify that nothing broke by running a tsc watch task and confirming that the problems generated are still correct. Many of the extension samples use a task that would work nicely for this.
