### ISSUE TITLE
Test: editor navigation by most recently use

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89277]
Refs: https://github.com/microsoft/vscode/issues/37366

- [x] anyOS @connor4312
- [x] anyOS @deepak1556

Complexity: 4

There is now a new utility in VSCode that will track each opened editor across all editor groups by their most recent use. An editor is considered as most recently used if it:
* was just opened as the active editor
* became the active editor if already opened

An editor is being removed from this list when it is being closed.

**Steps:**
* verify you can see this list in a picker from the new quick open picker "`edt mru`" and editors can be navigated to and searched from there
  * changing the MRU list with the examples from above is reflected in the list when you open it again
* verify you can open this list via the new `workbench.action.showAllEditorsByMostRecentlyUsed` command
* verify this list is stored and restored after restart across multiple editor groups (e.g. any kind of editor layout)
* there are new commands added that allow to navigate the history per editor group and across all editors without a picker
  * verify that the commands `workbench.action.openNextRecentlyUsedEditor` and `workbench.action.openPreviousRecentlyUsedEditor` can be used to navigate this MRU list without a picker across all editor groups
  * verify that the commands `workbench.action.openNextRecentlyUsedEditorInGroup` and `workbench.action.openPreviousRecentlyUsedEditorInGroup` can be used to navigate the per-editor-group MRU list without a picker
* verify you can still use `Ctrl+Tab` and `Ctrl+Shift+Tab` to quick navigate back and forth in editors of the active editor group through the picker

**Comment by deepak1556** [comment]
Works well, tested on windows and container environment 👍
