### ISSUE TITLE
EXTENSIONS: Install buttons not triggering installation

### ISSUE THREAD

**Issue by gsusI** [Microsoft/vscode#8927]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 3.13.0-88-generic

Steps to Reproduce:

1.Install latest version
2.Try to install extension

**Comment by matej-marcisovsky** [comment]
Same as #8923

**Comment by gudvinr** [comment]
Don't create same issues, it's already been here yesterday #8859
