### ISSUE TITLE
[html] CSS autocomplete not working inside style in html file

### ISSUE THREAD

**Issue by motss** [Microsoft/vscode#8928]
- VSCode Version: 1.3.0
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Create a `.html` file and create `style` tag.
2. CSS autocompletion only works on `.css` file but not working inside `style` tag of a `.html` file.
3. Within a `.html` file only HTML related auto completion will work.

**Comment by shhdgit** [comment]
Same situation.

**Comment by Oostwegel** [comment]
Same here!

**Comment by Tekbr** [comment]
Same situation.

**Comment by Reedo0910** [comment]
Version: 1.3.1
Same situation.

**Comment by ecmel** [comment]
Hi,

I have a new extension which works for style tags and attributes. Also completes class attributes:

https://github.com/ecmel/vscode-html-css

I used https://github.com/Microsoft/vscode-css-languageservice for language intelligence.

From the experience gathered while writing the extension, in my opinion, vscode html support should be refactored and give html intelligence from the vscode.extension api to allow further extensions leverage the underlying html document.

**Comment by Reedo0910** [comment]
Thank you!!! Your extension really helps me a lot. It works great! And I have a few questions to ask：
1. I find that the CSS color decorators attached to color values inside style tags in html files seem not working in vscode 1.3. May your extension help fix this problem in future updates?
2. If there is any possibility to fix the JS autocomplete problem inside script tags in html?
Thanks again.

**Comment by motss** [comment]
Any progress in fixing this?

**Comment by egamma** [comment]
Sorry for the delay but there is some major rework behind this:
- the CSS completion support was lost when we extract the CSS support into a language server. The plan is to also extract the HTML support into a language server as well that then leverages the CSS language server. This will likely take more than one iteration.
- we will work with the typescript team on support Intellisense inside JS script tags. We will start on this during August.

**Comment by motss** [comment]
@egamma Thanks for the update.

**Comment by zhenzhenkeai** [comment]
Not see the prompt in Html file write the javascript

**Comment by zhenzhenkeai** [comment]
I want to vscode add the javascript prompt in the html file

**Comment by xbears** [comment]
Version: 1.5.1
Same situation, waiting...

**Comment by fordou** [comment]
JS doesnt work in HTML document~~

**Comment by vitid** [comment]
No reason for me to switch from the old version(0.10.6) until this is fixed...

**Comment by doplumi** [comment]
Also, keyboard shortcuts don't seem to work. 
For example, if I use the shortcut to add a line comment, `<!-- -->` is stamped on the page instead of `//`.

**Comment by motss** [comment]
@doplumi The new release `1.6.0` just broke the vscode commenting. Try revert back to `1.5.3` and turn off the auto update.

**Comment by doplumi** [comment]
@motss Still an issue on `1.6.1`. What's the easiest way to downgrade, keeping all of the settings & snippets?

**Comment by motss** [comment]
What OS you using?

**Comment by aeschli** [comment]
CSS (styles) in HTML is now implemented, JS still needs to be done.
We will use https://github.com/Microsoft/vscode/issues/3465 for that.
Note that smart editing functionalty (comments, smart indent) is https://github.com/Microsoft/vscode/issues/11081

**Comment by perfecto25** [comment]
ecmel's terrific plugin works for HTML css support, but not in PHP files, 
anyone know of a way to add CSS intellisense to PHP?
