### ISSUE TITLE
cursor jumps

### ISSUE THREAD

**Issue by AniKaPu** [microsoft/vscode#89282]
every time I try to write someting the cursor jumps to the end of the file, it makes vcs impossible to use. The solutions on GitHub doesn't work for me

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
phpserver|bra|2.4.6
jsrefactor|cms|2.20.5
prettier-vscode|esb|3.18.0
auto-close-tag|for|0.5.6
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.8.0
inline-html|pus|0.2.5
format-html-in-php|rif|1.6.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
ftp-kr|rua|1.3.16
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.9.6
php-snippets-for-vscode|Yis|1.1.1

</details>

**Comment by sbatten** [comment]
does the issue reproduce with extensions disabled?

**Comment by AniKaPu** [comment]
yes it happened also with extensions disabled and output closed, but I do a reinstallation of VSC and it looks like it helped:) thanks anyway
