### ISSUE TITLE
Need scrollTop, scrollBottom, and scrollToCursor commands for Home, End and Control-L key bindings on macOS

### ISSUE THREAD

**Issue by markfinlabs** [microsoft/vscode#89284]
Hi there,

If we follow Apple apps like xcode or Pages as an example for macOS text input key mappings, some things are fine in VS Code. ```cmd+up``` is mapped to ```cursorTop``` and ```cmd+down``` is mapped to ```cursorBottom``` by default which is great. We can map ```pageup``` to ```scrollPageUp``` and ```pagedown``` to ```scrollPageDown``` to follow macOS behaviour of not moving the cursor when these are pressed (PS should these be macOS defaults?).

But we cannot map ```home``` to ```scrollTop``` and ```end``` to ```scrollBottom``` because the commands ```scrollTop``` and ```scrollBottom``` do not exist! Therefore on my keyboard ```home``` and ```end``` do nothing in a text file.

Could these missing two commands please be added to allow standard macOS key mappings for ```home``` and ```end```?

BR,
Mark

PS: After scrolling one often uses ```Ctrl-L``` ([reference](https://support.apple.com/en-in/HT201236)) to return to the cursor position - would be great if suitable command for this standard macOS shortcut was also added, e.g. ```scrollToCursor```

**Comment by ArturoDent** [comment]
You could effectively get that behaviour using the `editorScroll` command and setting a very high `value`.  See https://code.visualstudio.com/api/references/commands

**Comment by markfinlabs** [comment]
Thanks for this. I tried it and although the ```home``` mapping is fine, the ```end``` mapping overshoots and shows the blank page following document end. I also still can't find a way to make ```ctrl-l``` undo scrolling such that the cursor sits in the vertical centre.

**Comment by ArturoDent** [comment]
Disable:

> Editor: Scroll Beyond Last Line
Controls whether the editor will scroll beyond the last line.

and the `end` keybinding will not scroll beyond your last line.

**Comment by rebornix** [comment]
thanks @ArturoDent for answering the question.
