### ISSUE TITLE
Go syntax highlighting missing for structs

### ISSUE THREAD

**Issue by Jacalz** [microsoft/vscode#89288]
## Description
The syntax highlighting for Go code is missing a lot of highlighting for structs, struct fields and other places of code related to Go structs. This makes the code very hard to read and is pretty much the only thing that Atom do a better job with than Visual Studio Code. I had hoped that this would be fixed by including https://github.com/microsoft/vscode/issues/82549 in the source code, but it changed absolutely nothing for me. This is kind of a deal breaker for writing go code in Visual Studio Code...

- **VSCode Version:** 1.42.0-insiders and 1.41.1 both have this issue.
- **OS Version:** Solus 4.1 Fortitude (Linux kernel 5.4.12)

## Steps to Reproduce:
1. Open up a Go source file that has a lot of structs. ([this one](https://github.com/Jacalz/go-projects/blob/master/projects/kn%C3%A4ckning/main.go) for example)
2. Open the same project in Atom and compare syntax highlighting. You will see that a lot of syntax highlighting is missing and it makes it a lot hard to read in vscode.

### Atom struct syntax:
![image](https://user-images.githubusercontent.com/25466657/73133110-915ccd80-4024-11ea-96d7-615495dde0c7.png)
![image](https://user-images.githubusercontent.com/25466657/73133114-9588eb00-4024-11ea-9fa0-0478d8e9d46f.png)

### Visual Studio Code struct syntax:
![image](https://user-images.githubusercontent.com/25466657/73133119-a6396100-4024-11ea-910f-aff3d7e81864.png)
![image](https://user-images.githubusercontent.com/25466657/73133121-aa657e80-4024-11ea-96ef-dd9998e04717.png)

Does this issue occur when all extensions are disabled?:
Yes both with Go extension active and not active.

Linking to https://github.com/microsoft/vscode-go/issues/2892 for the original report.

**Comment by jeff-hykin** [comment]
I've moved this to the go syntax repo which is the upstream source for VS Code (which is where we can get this fixed)

I'll comment on the details there

**Comment by Jacalz** [comment]
Thanks :+1:

**Comment by ramya-rao-a** [comment]
@sbatten The issue here is regarding the grammar used for Go by VS Code which is controlled in VS Code and not the Go extension. Therefore, the `caused-by-extension` shouldn't be applied.

Can you provide the link to the issue that this one is the duplicate of?

**Comment by ramya-rao-a** [comment]
Ah, never mind, I jumped the gun :)
https://github.com/jeff-hykin/better-go-syntax has the tracking issue for this.
