### ISSUE TITLE
cmd terminal blank and can't type

### ISSUE THREAD

**Issue by samboustani** [microsoft/vscode#89285]
Issue Type: <b>Bug</b>

The terminal window is blank and there's no prompt.  You can start typing and it shows up in the center of the terminal.  The shell type is set to cmd.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (25.43GB free)|
|Process Argv|C:\Users\Sam\Source\Repos\WebChat\BotFramework-WebChat-master|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
tslint|eg2|1.0.44
prettier-vscode|esb|3.18.0
rest-client|hum|0.23.1
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|8.3.0
mssql|ms-|1.8.0
csharp|ms-|1.21.9
debugger-for-chrome|msj|4.12.6
aspnet-helper|sch|0.6.4
autoimport|ste|1.5.3
html-css-class-completion|Zig|1.19.0

</details>

![terminal](https://user-images.githubusercontent.com/898232/73130039-aac73080-3fb6-11ea-9f61-d2802b22ed5f.PNG)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
