### ISSUE TITLE
VSCode Version:

### ISSUE THREAD

**Issue by Minakt** [microsoft/vscode#89281]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Minakt** [comment]
Hi,

I am trying to operate latest version of Visual studio code but I don't know where to write code and where I can get output. Please send me any video if you have....

**Comment by sbatten** [comment]
Please see our documentation: https://code.visualstudio.com/docs/introvideos/basics
