### ISSUE TITLE
Test: save UI state automatically before OS reboot

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89291]
Refs: https://github.com/microsoft/vscode/issues/12058, https://github.com/microsoft/vscode/issues/87171

- [ ] macOS @btholt
- [x] linux @mjbvz
- [x] windows @fiveisprime

Complexity: 2

There is 2 sources of state that we so far only saved on a normal shutdown:
* UI state (e.g. use the list of opened editors and the editor layout to test this)
* Window state (use the size and location of the window to test this).

On most OS, if you simply restart the OS, VSCode will be terminated leaving no time to persist the UI state. To mitigate this, VSCode will now
* save state every minute automatically
* save state as soon as the VSCode window looses focus (for example if the user clicks on Start > Reboot, we would have a chance to persist state before this happens)

**Verify**
* open a couple of editors and/or set a specific editor layout and then alt+tab to another app and click the OS restart button. Verify that after restart of the OS when you open VSCode, that editor state is restored exactly how you left it
* make a change to the window dimensions or window position and then alt+tab to another app and click the OS restart button. Verify that after restart of the OS when you open VSCode, the window opens in that position and size

**Comment by bpasero** [comment]
I pushed a small but significant change today around finding out if a window has focus or not. I have a new insiders build running with that change and ask to please use that build once its out. Will post it here...

**Comment by bpasero** [comment]
Here are the builds:
* Windows: https://az764295.vo.msecnd.net/insider/2f5acf960db667602c58d8e950bb38f945de27df/VSCode-win32-x64-1.42.0-insider.zip
* macOS: https://az764295.vo.msecnd.net/insider/2f5acf960db667602c58d8e950bb38f945de27df/VSCode-darwin-insider.zip
* Linux: https://az764295.vo.msecnd.net/insider/2f5acf960db667602c58d8e950bb38f945de27df/code-insider-1580223729.tar.gz

**Comment by fiveisprime** [comment]
Looks good ✔️ 

Tested on internal and external monitor since Windows scaling can get interesting with varying resolutions. Works well even when disconnecting from external monitor while restarting.

**Comment by btholt** [comment]
LGTM, worked on macOS
