### ISSUE TITLE
Show breakpoint window without creating a launch.json in the workplace folder

### ISSUE THREAD

**Issue by xubury** [microsoft/vscode#89290]
After recent update, the debug tab no longer shows the breakpoint window until you create a launch.json. Personally I find that annoying cause I use the cmake-tool extension which allows me to debug without launch.json. Now, I have to create a launch.json to check the breakpoints before debug which seems so unnecessary. So I think maybe we should be able to check breakpoints even if we don't have launch.json.
![QQ截图20200126172833](https://user-images.githubusercontent.com/46261364/73133280-562cbf80-4061-11ea-84e8-1f116f6b7f30.png)

**Comment by isidorn** [comment]
Yes, this makes sense.
I agree we shuol show the breakpoints view in the start experience if there is at least one breakpoint set.

**Comment by isidorn** [comment]
To verify:
Make sure that Breakpoints view is visible in the start experience if and only if you have some breakpoints set.

**Comment by connor4312** [comment]
It seems like breakpoints should remain on the bottom where it is during the debug session, looks kind of weird on top. Good otherwise.

![image](https://user-images.githubusercontent.com/2230985/73310316-eb05f900-41d8-11ea-8205-2e133c91027f.png)

**Comment by isidorn** [comment]
@connor4312 how did you end up in that situation? I can not reproduce it.
This should never happen since the breakpoints view has order 40 and start view has order 10. fyi @sandy081

**Comment by connor4312** [comment]
I set a breakpoint and then commented out my launch config... but I'm also unable to reproduce it now/on today's insiders.

**Comment by isidorn** [comment]
@connor4312 ok. Let me know if you find repro steps and we can investigate further then. Thanks
