### ISSUE TITLE
Syntax highlighting bug in .TSX when using generic type annotation

### ISSUE THREAD

**Issue by Liero** [Microsoft/vscode#8929]
- VSCode Version:1.3.0
Commit   `e724f269ded347b49fcf1657fc576399354e6703`
Date 2016-07-07T16:56:12.476Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version: CPWin10 April 2016

Steps to Reproduce:

1. Open or create .tsx file in VSCode
2. type `interface IFoo {  bar: Array<any>; }`
3. Syntax highlighter will treat `<any>` as unclosed tag. 

![capture](https://cloud.githubusercontent.com/assets/3494407/16685168/91b47c3e-4509-11e6-9b57-b750cd64c6f3.PNG)

**Comment by mbilling** [comment]
Same as issue https://github.com/Microsoft/vscode/issues/8045
Which has been closed on 2016-07-08
