### ISSUE TITLE
Missing intellisense for 'requestIdleCallback'

### ISSUE THREAD

**Issue by carljohnesan** [microsoft/vscode#89293]
There are missing intellisense for `requestIdleCallback` method. It's weird considering there's intellisense even for `setImmediate` which is edge-only feature.
![requestidlecallbackmissing](https://user-images.githubusercontent.com/47556468/73135648-21af0880-404d-11ea-8c35-354285e61fc9.png)

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/21309
