### ISSUE TITLE
MacOS Catalina - delete file message says "move to trash" but its called "bin" on the UK edition

### ISSUE THREAD

**Issue by rtpHarry** [microsoft/vscode#89298]
- VSCode Version: Version: 1.41.1
- OS Version: MacOS Catalina 10.15.2

## Description 

In the UK the MacOS Catalina update [renames the Trash to Bin](https://www.imore.com/apple-ditches-trash-can-name-uk-macos-catalina-update).

![image](https://user-images.githubusercontent.com/1038062/73137517-e9112e00-4050-11ea-8c01-5ecae7ab6f7e.png)

But when you delete a file it says "Move to Trash":

![image](https://user-images.githubusercontent.com/1038062/73137557-6b99ed80-4051-11ea-861b-7a348a8f2c23.png)

## Steps to Reproduce
1. Select a file
2. Choose delete

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This makes sense, however it shuold be solved by having a UK language extension. Than that language would change the translation of the Move to Trash.
Thus closing this as extension candidate since we can not fix it in the core.
