### ISSUE TITLE
Create-react-app typescript debugging partially broken with V1.41, V1.40 still works fine

### ISSUE THREAD

**Issue by Ziriax** [microsoft/vscode#89294]
VSCode Version: `1.41`
OS Version: `Windows 10 Pro x64 1903`

Steps to Reproduce: 
_- Can't provide code that reproduces this, a trivially small 'hello world' app seems to work, but in our closed source code, it happens all the time._ 

Does this issue occur when all extensions are disabled?: `Yes`

**Description**

We have a large SPA that uses the latest version of react-scripts (3.3.0) and typescript (3.7.4)

Debugging with vscode 1.41 became very difficult, as if the source maps are not recognized correctly, the debugging cursor jumps to the strangest locations. With V1.40, this works fine.

I tried reverting to older versions of react-scripts and typescript, but that didn't seem to help

So currently we disabled vscode updates and continue working with 1.40, but since I can't find any other issue related to this, I felt the need to report this.

**Comment by Ziriax** [comment]
We still have the same issue with 1.42, going to try out 1.43

**Comment by connor4312** [comment]
We since have a [new debugger](https://github.com/microsoft/vscode-js-debug/), please let us know if you're still running into problems, and if so open an issue on that repo.
