### ISSUE TITLE
Import added via yellow bubble added to wrong part of ts file...

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/vscode#89307]
- VSCode Version: 1.42.0 insider
- OS Version: Windows 10

Steps to Reproduce:

1. I've the following code in a huger file:

                        if (moduleConfig.Loader) {
                            let el = document.createElement('script');
                            el.type = "module";
                            el.innerHTML = `
        import {${ moduleConfig.Loader.Class}} from '${folder + moduleConfig.Loader.File}'
        import { commonClient } from "/dist/commonClient/commonClient.js";
        commonClient.viewCreators.unshift(new ${ moduleConfig.Loader.Class})`;
                            window.document.head.appendChild(el);
                        }

2. When I now add a import in the file below this code via the yellow bubble, it's added to the imports in the template-string

**Comment by jogibear9988** [comment]
typescript

**Comment by mjbvz** [comment]
I can't repo this. Can you please provide a complete, step-by-step guide to reproduce this

Also, does this happen when you disable all extensions?
