### ISSUE TITLE
Cannot open Visual Studio Code on Mac running Catalina

### ISSUE THREAD

**Issue by kelseydavis19** [microsoft/vscode#89304]
- VSCode Version: 1.41
- OS Version: Catalina

Steps to Reproduce:

1. Download Visual Studio Code
2. Attempt to open
3. Verify that you get error message "Visual Studio cannot be opened because Apple cannot check it for malicious software." 
<img width="747" alt="Screen Shot 2020-01-26 at 2 12 44 PM" src="https://user-images.githubusercontent.com/60120136/73140430-d265d980-4046-11ea-9334-6ed73ec2bd89.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JacksonKearl** [comment]
/duplicate see #74782 for steps on how to fix this (you can right-click and open)
