### ISSUE TITLE
On Mac changing "select+all" and other key bindings doesn't work inside "Find" Widget 

### ISSUE THREAD

**Issue by Ivanca** [microsoft/vscode#89309]
- VSCode Version: 1.41.1
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. On Mac on keybindings change the "select all" command to `"ctrl+a"` by adding this in the array:
```json
        {
                "key": "ctrl+a",
                "command": "editor.action.selectAll",
                "when": "textInputFocus"
        },
        {
                "key": "ctrl+a",
                "command": "editor.action.webvieweditor.selectAll",
                "when": "!editorFocus && !inputFocus && activeEditor == 'WebviewEditor'"
        },
        {
                "key": "ctrl+a",
                "command": "list.selectAll",
                "when": "listFocus && listSupportsMultiselect && !inputFocus"
        },
        {
                "key": "ctrl+a",
                "command": "workbench.action.terminal.selectAll",
                "when": "terminalFocus"
        }
```
2. Open a document, click `Edit > Find`, write something, try to select it all by pressing ctrl+a, doesn't work.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rebornix** [comment]
We don't support keybinding customization for native inputs, including Find input, Search, SCM.

**Comment by Ivanca** [comment]
> We don't support keybinding customization for native inputs, including Find input, Search, SCM.

@rebornix  That doesn't seem completely true, the native command Cmd+a no longer works either, so it is definitely doing something on those inputs.

**Comment by rebornix** [comment]
@Ivanca good catch, I can reproduce this ;)

**Comment by dataf3l** [comment]
cmd+a > ctrl+a

**Comment by Ivanca** [comment]
@dataf3l reported for spam

**Comment by dataf3l** [comment]
Thanks, I didn't know having my opinions on things were considered SPAM, I'll keep this in mind.

I hope you are able to resolve your editor issue, since VSCode is open-source, have you considered fixing the issue yourself ?, do you have time to contribute to this project?.

**Comment by Ivanca** [comment]
> Thanks, I didn't know having my opinions on things were considered SPAM, I'll keep this in mind.
> 
> I hope you are able to resolve your editor issue, since VSCode is open-source, have you considered fixing the issue yourself ?, do you have time to contribute to this project?.

Github issues marked as bug are not the places to express your opinion on key bindings; my time is extremely limited so the only way I could place some time to use it is if someone pays me to do it? Perhaps as I have a public Paypal account (ivanca@gmail.com) you want to pay me yourself=

**Comment by rebornix** [comment]
Dig into this and found it's actually because how Electron menu works:

```
	{
		"key": "ctrl+a",
		"command": "editor.action.selectAll",
		"when": "textInputFocus"
	}
```

when we have about keybindings, `ctrl+a` will be the keybinding for `editor.action.selectAll` and it will not respect the `when` clause. The blocking issue is tracked in https://github.com/microsoft/vscode/issues/40389 .
