### ISSUE TITLE
Remove vertical line/cursor after using auto-completion in html file

### ISSUE THREAD

**Issue by mdsaifurrahmann** [microsoft/vscode#89303]
I've attached a screenshot below, and I'm trying to remove that vertical line/extra cursor after the double quotation mark. It appears when I'm using `auto-completion` by pressing `tab` or `enter`. It also prevents the `class/attributes` suggestions. After clicking or move the cursor by pressing the right and left button, that cursor turns away automatically and showing the suggestions fine as well.

[Screenshot](https://i.stack.imgur.com/pDGuC.png)

```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by myfonj** [comment]
These vertical lines indicate insertion points ("tabstops") of currently inserted snippet; you are supposed to either <kbd>Tab</kbd> through them (and eventually fill them), or cancel snippet-filling procedure with <kbd>Esc</kbd>. It is integral part of this feature.

You can define your own snippets with fewer or even zero tabstops if you want, but due #10565 you currently cannot get rid of the native ones completely (If I understand that issue correctly).

https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by mdsaifurrahmann** [comment]
@myfonj I know, It needs to cancel snippet-filling procedure with `ESC`.
But It'll be great if this vertical line disabled by default. I've tried with disabling `Tab Stops`. But there is no result.

**Comment by octref** [comment]
I don't know if it's worth it to add a setting, so HTML attribute completion does not add a tabstop there. That line tells people "you can tab to there". If we remove it, that fact becomes undiscoverable.

**Comment by aeschli** [comment]
@mdsaifurrahmann  Can you paste a small html snippet and detailed steps that show the problem. I'd like to understand if we unnecessarily go into snippet mode. And I'd like to understand what you mean by 'It also prevents the class/attributes suggestions.'.

Just removing the end line is IMO not the solution. Either we need to make it more obvious to the user that we are currently in snippet mode (and that escape brings you out of it), or we need to use the snippet mode less often.

**Comment by mdsaifurrahmann** [comment]
@octref Yes, HTML attribute completion doesn't add Tabstop there, and I also don't know it is worth it or not. But if it added to settings, then front-end developers will feel more comfortable to use VSCode IMO.
I'm not telling you to remove that vertical line altogether. Just consider adding an option there to add Tabstop for HTML attribute completion.

**Comment by mdsaifurrahmann** [comment]
Hi, @aeschli 
Yes, I know removing the end line is not a solution. I'm just telling you guys that add an option there to remove and add that line at the end of completion. Take a look at the gif. I hope you'll understand.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34965777/73862610-fd330780-4868-11ea-8794-676e4a3f68e7.gif)

**Comment by aeschli** [comment]
You mean there are no the quick suggestions (suggestion that pop up as you type) while in snippet/template mode.
There's a setting `snippetsPreventQuickSuggestions` that is true by default.

Moving to @jrieken to maybe reconsider the default of snippetsPreventQuickSuggestions

**Comment by myfonj** [comment]
Btw @mdsaifurrahmann that HTML snippet and className suggestions in your illustrative video are presumably both provided by some extensions.  Could you tell which exactly those are?

**Comment by mdsaifurrahmann** [comment]
@myfonj The extension name is `HTML CSS Support`.

**Comment by mdsaifurrahmann** [comment]
@aeschli Thanks, man. My problem is now solved. It will be great if VSCode makes this feature disabled by default in the next update.

**Comment by jrieken** [comment]
Closing, there are no plans to change the default as this will be too confusing. However, I will create another issue of relaxing this a little. Today, any snippet will prevent quick suggest but we could relax that so that only snippets with real tabstops prevent quick suggest
