### ISSUE TITLE
Can't get debug adapter to start

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#89305]
I'm trying to add a simple debug adapter to the [Julia extension](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia), but I can't even get anything to start :)

Here is what I'm doing. I added the following to `package.json`:
```JSON
"debuggers": [
            {
                "type": "julia",
                "label": "Julia Debug",
                "languages": ["julia"],
                "adapterExecutableCommand": "language-julia.adapterExecutableCommand",
                "initialConfigurations": [
                    {
                        "name": "julia",
                        "type": "julia",
                        "request": "launch"
                    }
                ]
            }
        ]
```
and then I have this line in the main `activate` function:
```typescript
 vscode.commands.registerCommand('language-julia.adapterExecutableCommand', () => {
        console.log('foo');
        return {
             
            command: "C:/Users/david/AppData/Local/Julia-1.3.1/bin/julia.exe",  // paths initially hardcoded for simplicity
            args: ["c:/Users/david/source/julia-vscode/scripts/debugger/foo.jl"]
        }
    });
```
When I now open a Julia file, I do get the UI that offers me the button `Debug with Julia Debug` and `Run with Julia Debug`, and I can click them. I then briefly see the debugger UI, and then it disappears again. No error message, no nothing, beyond that.

BUT, as far as I can tell, the `language-julia.adapterExecutableCommand` command never runs (i.e. if I set a breakpoint on the line with `console.log('foo')` it never breaks, and I also never see `foo`), and the julia process also never starts.

I'm obviously missing something basic, but I can't figure out what :) Any help would be appreciated.

Also, is there some way to get some diagnostic output what is happening?

**Comment by weinand** [comment]
@davidanthoff how is your extension activated?
Make sure to have at least this in your package.json:
```
	"activationEvents": [
		"onDebug"
	],
```

**Comment by davidanthoff** [comment]
Ah, I forgot to mention: I had also added the `onDebug` activation event, so that is not the problem.

I now changed this to use the `DebugAdapterDescriptorFactory` approach, but still no success...

This PR https://github.com/julia-vscode/julia-vscode/pull/946 has all the changes I made, it is short, so maybe you could take a quick look? If I set a breakpoint at https://github.com/julia-vscode/julia-vscode/pull/946/files#diff-45327f86d4438556066de133327f4ca2R35, that line never even runs, so I don't think it ever even gets to the point where it would be trying to start our debug adapter... Ignore the discussion in that PR, that is all internal stuff for later :)

Thanks so much for the help, much appreciated!

**Comment by weinand** [comment]
How do you actually start debugging?
How does your launch config look like?

**Comment by davidanthoff** [comment]
I figured it out! I didn't create a launch config, but also didn't have the mechanism in place to create one on the fly dynamically. At this point I can start the debug adapter, so all good. Now we just need to implement it ;) Thanks for the help!

**Comment by weinand** [comment]
Yes, for starting debugging **without** a launch config you will have to implement the `resolveDebugConfiguration` hook in your extension. If you have that, "F5" would start debugging even without a launch config.
