### ISSUE TITLE
Ipynb not accepting input()

### ISSUE THREAD

**Issue by surpavan** [microsoft/vscode#89302]
the input() function is not working for input, it is not asking for user input.

But as per the below stack channel, the bug is that - it is working fine if input() function is given some test like input('some text')

https://stackoverflow.com/questions/59907260/vscode-ipynb-how-to-accept-user-input

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode-python

**Comment by surpavan** [comment]
Thank you, filed the ticket there.
https://github.com/microsoft/vscode-python/issues/9776
