### ISSUE TITLE
Ctrl + Tab no longer works in editor. Keybinding is missing.

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/vscode#89318]
The keybinding for Ctrl + Tab is missing has gone missing in Keyboard Shortcuts.
Latest version:
![image](https://user-images.githubusercontent.com/5993909/73158546-6cc82a80-40e4-11ea-8261-98b906ece215.png)

VSCode 1.41:
![image](https://user-images.githubusercontent.com/5993909/73158571-810c2780-40e4-11ea-9f24-80a9b3019e9f.png)
 

Version: 1.42.0-insider (user setup)
Commit: 3c6f6af7347d38e87bc6406024e8dcf9e9bce229
Date: 2020-01-27T05:27:06.595Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open at least two files in the editor
2. Press Ctrl+Tab to navigate to next file
3. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by crewone** [comment]
Same here.

**Comment by EddyVinck** [comment]
I am having this issue as well. Really frustrating as I do it all the time :slightly_frowning_face:

**Comment by crewone** [comment]
> I am having this issue as well. Really frustrating as I do it all the time 🙁

I think most of us do ;)

**Comment by bpasero** [comment]
Fix is coming. Workaround: configure this in keybindings:

```json
{
    "key": "ctrl+tab",
    "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
    "when": "!inEditorsPicker"
}
```

**Comment by bpasero** [comment]
Workaround: configure this in keybindings

```json
{
    "key": "ctrl+tab",
    "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
    "when": "!inEditorsPicker"
},
{
    "key": "ctrl+tab",
    "command": "workbench.action.quickOpenNavigateNextInEditorPicker",
    "when": "inEditorsPicker"
}
```
