### ISSUE TITLE
Live Share results in `Unable to write files.hotExit to Workspace Settings. This setting can be written only into User settings.` warning

### ISSUE THREAD

**Issue by mavaddat** [microsoft/vscode#89310]
| Version  	| 1.42.0-insider (user setup)              	|
|----------	|------------------------------------------	|
| Commit   	| f3dbcea32a6b52ce819dc863e778fb8517357f61 	|
| Date     	| 2020-01-24T05 38 14.538Z                 	|
| Electron 	| 7.1.7                                    	|
| Chrome   	| 78.0.3904.130                            	|
| Node.js  	| 12.8.1                                   	|
| V8       	| 7.8.279.23-electron.0                    	|
| OS       	| Windows_NT x64 10.0.18363                	|
![image](https://user-images.githubusercontent.com/5055400/73144217-452b8080-4058-11ea-8ec8-f49fd685e72b.png)
I am getting the error message 

Steps to Reproduce:

1. Start [LiveShare ](https://github.com/MicrosoftDocs/live-share) session
2. See notice in Developer Console reading `Unable to write files.hotExit to Workspace Settings. This setting can be written only into User settings.`
![image](https://user-images.githubusercontent.com/5055400/73144319-95efa900-4059-11ea-8ef8-81ebe3c80b54.png)

Does this issue occur when all extensions are disabled?: No, because I cannot use [LiveShare](https://github.com/MicrosoftDocs/live-share) in that case

My active extensions:

| Extension                           	| Author (truncated) 	| Version      	|
|-------------------------------------	|--------------------	|--------------	|
| npm-intellisense                    	| chr                	| 1.3.0        	|
| vscode-crowdin                      	| Cro                	| 0.0.3        	|
| vscode-markdownlint                 	| Dav                	| 0.33.0       	|
| vscode-eslint                       	| dba                	| 2.0.15       	|
| githistory                          	| don                	| 0.4.13       	|
| xml                                 	| Dot                	| 2.5.0        	|
| prettier-vscode                     	| esb                	| 3.18.0       	|
| code-runner                         	| for                	| 0.9.15       	|
| beautify                            	| Hoo                	| 1.5.0        	|
| textile                             	| idl                	| 0.1.5        	|
| auto-comment-blocks                 	| kev                	| 1.0.1        	|
| vscode-codemetrics                  	| kis                	| 1.23.1       	|
| vscode-github                       	| Kni                	| 0.30.3       	|
| git-tree-compare                    	| let                	| 1.7.1        	|
| vscode-osgi                         	| lgd                	| 1.0.2        	|
| javadoc-tools                       	| mad                	| 1.3.1        	|
| vscode-azurefunctions               	| ms-                	| 0.20.2       	|
| python                              	| ms-                	| 2020.1.58038 	|
| azure-account                       	| ms-                	| 0.8.8        	|
| powershell                          	| ms-                	| 2020.1.0     	|
| vsliveshare                         	| ms-                	| 1.0.1510     	|
| vsliveshare-audio                   	| ms-                	| 0.1.80       	|
| debugger-for-chrome                 	| msj                	| 4.12.6       	|
| vscode-for-node-js-development-pack 	| nod                	| 2.0.1        	|
| java                                	| red                	| 0.55.1       	|
| partial-diff                        	| ryu                	| 1.4.1        	|
| code-settings-sync                  	| Sha                	| 3.4.3        	|
| vscode-checkstyle                   	| she                	| 1.3.2        	|
| vscode-table-formatter              	| shu                	| 1.2.1        	|
| open-in-browser                     	| tec                	| 2.0.0        	|
| vscodeintellicode                   	| Vis                	| 1.2.4        	|
| vscode-java-debug                   	| vsc                	| 0.24.0       	|
| vscode-java-dependency              	| vsc                	| 0.8.0        	|
| vscode-java-pack                    	| vsc                	| 0.8.1        	|
| vscode-java-test                    	| vsc                	| 0.22.1       	|
| vscode-maven                        	| vsc                	| 0.20.2       	|
| vscode-import-cost                  	| wix                	| 2.12.0       	|
| vscode-preview-server               	| yui                	| 1.3.0        	|

**Comment by sbatten** [comment]
Please start by filing this issue with live share https://github.com/MicrosoftDocs/live-share
