### ISSUE TITLE
Mac: Hiding Activity Bar via context menu vs main menu is not in sync

### ISSUE THREAD

**Issue by tchkreddy** [microsoft/vscode#89317]
**Actual Behavior**
Activity Bar to the left of VS Code can be hidden with its context menu. But if this option is used, the menu item View > Appearance > Show Activity Bar still remains checked. From now on it will behave in reverse. Checking it off shows Activity Bar and vice versa. Workaround is obviously to re-hide it using context menu.

**Expected Behavior**
The tick mark on View > Appearance > Show Activity Bar should be ticked off when Activity Bar is hidden with context menu on Activity Bar.

**Comment by tchkreddy** [comment]
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by tchkreddy** [comment]
Issue is same with Status Bar also

**Comment by sbatten** [comment]
It took some experimentation and I think I know what is causing this but I don't know why exactly.

Exact Repro Steps:

1) Cold Launch VS Code
2) Without clicking anything else, right-click the activity bar and hide.
3) Without clicking anything else, check the menu entry under the View menu.

:bug: => Activity bar shows visible

Exact Repro Steps to get the correct state:

1) Cold Launch VS Code
2) Click another window to blur the VS Code window
3) Click back into VS Code refocusing the window
4) Repeat 2 and 3 from first repro.

What this tells me is that the menubar is trying to update but is being blocked by the check here https://github.com/microsoft/vscode/blob/5d498736f42841b46b53cda82f23178a3f05070c/src/vs/workbench/electron-browser/window.ts#L728-L733

It seems the focus state in the host service is wrong on cold launch. Further evidence of this is that when you cold launch again with the menubar toggle out of sync, it remains out of sync until you blur and focus the window. This tells me that it is using the cached menu until refocusing.

I could not reproduce this in OSS on macOS which made it difficult to debug, but I can on the latest insiders.

@bpasero

**Comment by bpasero** [comment]
I cannot really explain this but we seem to be getting a `browser-window-blur` event from the main side. I changed the logic to simply use `document.hasFocus` instead and not rely on weird Electron behaviour. This also means we are aligned with web which uses this already.
