### ISSUE TITLE
Crash after opening and closing dev tools twice

### ISSUE THREAD

**Issue by the-ress** [Microsoft/vscode#8931]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Open Developer Tools
2. Close Developer Tools
3. Open Developer Tools
4. Close Developer Tools
5. VS shuts down

(Happens with --disable-extensions too.)

[operation_log.txt](https://github.com/Microsoft/vscode/files/354115/operation_log.txt)
[crash_checkpoint.txt](https://github.com/Microsoft/vscode/files/354114/crash_checkpoint.txt)
[1ab17383-925f-48f0-9369-2d6f6fa80746.txt](https://github.com/Microsoft/vscode/files/354116/1ab17383-925f-48f0-9369-2d6f6fa80746.txt)
[f3254ad4-4229-4c49-a5a9-d2cfb59b3a46.txt](https://github.com/Microsoft/vscode/files/354117/f3254ad4-4229-4c49-a5a9-d2cfb59b3a46.txt)

**Comment by MarkWaldron** [comment]
VSCode Version: 1.4.0-Insider
OS Version: OS X El Capitan 10.11.5 

Same issue after toggling dev tools twice

**Comment by bpasero** [comment]
#5628
