### ISSUE TITLE
Output window not showing utf-8

### ISSUE THREAD

**Issue by robopo** [microsoft/vscode#89312]
Issue Type: <b>Bug</b>

Using Python3.8.1 the string will not output correctly. Try:

ooo="äöåÄÖÅ"

print(ooo) 

works with cmd.exe and Qt Python. 

Have tried several settings for locale and internal Terminal in settings none of which helped. I suspect the fault is somewhere in VS code terminal settings.
 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X6 1090T Processor (6 x 3211)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (5.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
code-gnu-global|aus|0.2.2
vscode-eslint|dba|2.0.15
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
code-runner|for|0.9.15
vscode-phpfmt|kok|1.0.30
ftp-sync|luk|0.3.9
HTMLHint|mka|0.6.0
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
php-docblocker|nei|2.1.0
vscode-php-getters-setters|php|1.2.3
view-in-browser|qin|0.0.5
remote-vscode|raf|1.1.0
java|red|0.55.1
format-html-in-php|rif|1.6.2
html5-boilerplate|sid|1.0.3
vscode-arduino|vsc|0.2.29
html-snippets|wge|0.1.5
html-css-class-completion|Zig|1.19.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
