### ISSUE TITLE
Colors are looking a bit fadded when used light color theme compared to MS Edge Chromium (codesandbox) or Chrome

### ISSUE THREAD

**Issue by sagarrabadiya** [microsoft/vscode#89316]
- VSCode Version: 1.41.1 (System Version)
- OS Version: Windows 10 Pro (1909, build 18363.592)

Steps to Reproduce:

1. When applied light color theme (Night Owl) colors are looking a bit different than it shows in MS Edge (Chromium) or Chrome

Note: I am using codesandbox.io for comparison in browser codesandbox.io renders colors correctly, I also have tested other themes and this problem is there with all light themes.

For ex. check the screenshots of comparison with MS Edge (Chromium) and vscode they both have same hex code in developer tool but the both look different colors, in vscode the color is a bit fadded.
![color-problem](https://user-images.githubusercontent.com/5405403/73154144-63e35300-40fc-11ea-94ba-3e5f7fa1f3dd.png)
![same-hex-color](https://user-images.githubusercontent.com/5405403/73154150-680f7080-40fc-11ea-9720-95a10f1bc345.png)

 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sagarrabadiya** [comment]
Hi, let me know if anything or any other info is required from me here, 

Thanks for the awesome work you guys are doing for the community. 👍

**Comment by sagarrabadiya** [comment]
Is there any work around or something for this color problem? Or will there be any fixes to this problem? i really need to use light color themes but die to this issue I am not able to use it correctly and for long time.

**Comment by deepak1556** [comment]
Is this still an issue with latest stable `1.49` ?

**Comment by sagarrabadiya** [comment]
yes @deepak1556 for me it's still an issue, colors are rendering different from browser in vscode, not sure if its related to color profile or some other settings

**Comment by sagarrabadiya** [comment]
how can I help you to figure out the issue?

**Comment by rzhao271** [comment]
I look a closer look at your screenshot in Paint and noticed that codesandbox is using greyscale subpixel rendering, whereas we are using RGB subpixel rendering.

**Comment by rzhao271** [comment]
Closing as out of scope since we intentionally use subpixel rendering to make the font look sharper.

Relevant issues:
https://github.com/microsoft/vscode/issues/84154
https://github.com/microsoft/vscode/issues/84214
https://github.com/microsoft/vscode/issues/84698
