### ISSUE TITLE
Don't close suggestion popup when out of bounds occurs

### ISSUE THREAD

**Issue by Paril** [microsoft/vscode#89311]
This is a tiny suggestion but I run into it constantly. Often, I instinctively hit the up arrow to scroll through suggestions only for the little dialog/popup to disappear entirely rather than wrapping around to the other side of the list. For instance, if a function has 8+ overloads, I have to hit down arrow 7 times exactly. If I hit more than that, the whole thing closes and I have to start over.

Talking about this popup specifically: https://streamable.com/mx94q

Would be nice if it wrapped around, so I can access the last suggestion just by hitting up arrow, or don't accidentally lose my place by going too far.

**Comment by Tyriar** [comment]
Repro after pressing down a few times:

![Image](https://user-images.githubusercontent.com/2193314/207200108-ca457da1-e0bb-4e77-b3d4-98b4e38eb9f8.gif)

**Comment by Paril** [comment]
Huh. Why is it default to off? That seems counter-intuitive, since it is by default cycle in VS.

**Comment by Tyriar** [comment]
I prefer true as well and just set it. @alexdima thoughts on whether this should be off by default?

**Comment by alexdima** [comment]
@Tyriar I think parameter hints is owned by @mjbvz

**Comment by Tyriar** [comment]
@alexdima it actually moved to me when Pine left, I haven't done much on it though.

**Comment by alexdima** [comment]
Aha! I wasn't sure anymore and just looked at who has the most items assigned with that label :).

Yes, I think changing `editor.parameterHints.cycle` to be `true` by default would be an improvement. Other places like suggestions (arrow down) or find matches (F3) cycle by default.

**Comment by Tyriar** [comment]
To verify:

- The `editor.parameterHints.cycle` default should be true
- Switch it and ensure both values work
