### ISSUE TITLE
Test extended codicon/themeicon support

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89328]
Refs: #84695
- [x] anyOS @connor4312
- [x] anyOS @bpasero

Complexity: 4

Authors: @eamodio, @jrieken

---

For extensions we have extended support for codicons aka ThemeIcon. First, use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to get the latest version of `vscode.d.ts`, make yourself familiar with [our codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html), and then test that:

* You can use the `vscode.ThemeIcon` constructor with a codicon, in those places that support theme icons (TreeItem and QuickInputButton), e.g `new vscode.ThemeIcon('zap')`
* you can refer to a codicon in command definition (inside package.json), e.g `"icon": "$(zap)"`
* you can create `vscode.MarkdownString`s that enable theme icons and that then also support the `$(<name>)` syntax.
  * If you use `appendText` any codicons should not be rendered as codicons and instead be output 
as the input text
  * If you use `appendMarkdown` any codicons should be rendered as codicons
  * You can also escape a codicon using `\\`, e.g. `\\$(zap)` should be output as `$(zap)` in the text
  * Also note that if you set `supportThemeIcons` to `false` the text should be output exactly
* also make sure that there documentation and/or IntelliSense to help you around

**Comment by bpasero** [comment]
This is cool 👍 . I wasn't sure if an invalid icon such as new `vscode.ThemeIcon('zassp')` should render a placeholder or not. Currently it looks like an empty space is added.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/commit/786718fccdf5b146941fc629c5c3e0918d56508d 🎉
