### ISSUE TITLE
VSCode is breaking my Vim...

### ISSUE THREAD

**Issue by chief10** [Microsoft/vscode#8932]
...addiction.

Just wanted to say that I take issue with how well you guys are doing with putting this editor together. You broke my Vim addiction -- especially when it comes to typescript/angular development -- and I don't know how I feel about that.

Any ways, thank you for giving the community this really freaking awesome tool.

Keep up the good work!

- VSCode Version: 1.3
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install VSCode
2. Let Vim collect dust.

**Comment by flagbug** [comment]
Just saying: https://github.com/VSCodeVim/Vim :wink:

**Comment by joaomoreno** [comment]
Aha.
