### ISSUE TITLE
SCM input box has "fake-focus"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89324]
See attached screen recording (and sorry not having inspected the dom...). No clue why but I had two blinking cursors; one in the editor and on in the SCM input box. Clicking into the latter would allow me to type in it, it always types in the editor, only after clicking the tree and then into the input box things recovered

[Screen Recording 2020-01-27 at 10.44.52.mov.zip](https://github.com/microsoft/vscode/files/4116465/Screen.Recording.2020-01-27.at.10.44.52.mov.zip)

**Comment by joaomoreno** [comment]
Damn. This might happen with every _simple_ code editor. Ain't nothing simple about them though.

Keep an eye out for repro.

**Comment by alexdima** [comment]
I think this can happen if someone calls `focus()` on the editor when the editor is off-DOM.
