### ISSUE TITLE
January 2020 Endgame

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89326]
- *January 27* Code freeze for the endgame
- *January 31* [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)
- *February 5* Expected release date (this may change)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday
- [x] Run [OSS tool](https://github.com/microsoft/vscode-build-tools/tree/master/distro-tools) **endgame master**
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] Create test plan items following the template [here](https://github.com/microsoft/vscode/wiki/Writing-Test-Plan-Items) by 6pm PT
- [x] Add verification-needed label to features needed testing and are not tested by TPIs.
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Tuesday
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
  - [Assigned to you](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3A%40me++label%3Atestplan-item+)
- [x] [🔖All closed feature-requests](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22January+2020%22+label%3Afeature-request+-label%3Averification-needed+-label%3Aon-testplan+-label%3Averified+-label%3A*duplicate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release) either have a `verification-needed` or `on-testplan` label
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] [🔖Testing](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Atestplan-item+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22January+2020%22+label%3Averification-needed+-label%3Averified+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)

##### Wednesday
- [x] [🔖Testing](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Atestplan-item+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+)
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22January+2020%22+label%3Averification-needed+-label%3Averified+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22January+2020%22+label%3Averification-needed+-label%3Averified+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] [🔖Verification](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+is%3Aissue+milestone%3A%22January+2020%22+label%3Abug+-label%3Averified+-label%3Aon-testplan+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)

##### Friday
- [x] Pause scheduled `insider` builds **endgame master**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] debug adapter protocol **@weinand**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
- [x] All issues [🔖verified](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+is%3Aissue+milestone%3A%22January+2020%22+label%3Abug+-label%3Averified+-label%3Aon-testplan+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) (⚠️ MUST run with `--stable-build` argument ⚠️ ) - Run manually
  - [x] Windows @rebornix 
  - [x] OS X @connor4312 
  - [x] Linux @JacksonKearl 
  - [x] Web (manual until https://github.com/microsoft/vscode/issues/80308 is done) - **@sandy081**
- [x] All release notes updated
  - release notes are collected in a file named *`vMajor_Minor.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @aeschli
  - [x] @alexdima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [x] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-js-debug **@connor4312**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexdima**
  - [x] vscode-loader **@alexdima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes **@chrisdias**
  - [x] localization **@weeteckt**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [x] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **endgame master**
- [x] Acknowledge issue trackers from the community **@chrmarti**
- [x] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **endgame master**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **endgame master**
- [x] Bump up the version in package.json - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [x] [🔖milestone issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A%22January+2020%22+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] [🔖candidate issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **endgame master**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [x] Build stable for all platforms as new candidate issues come in **endgame master**
- [ ] Documentation updated
  - [x] @aeschli
  - [x] @alexdima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @mjbvz
  - [ ] @octref
  - [ ] @rebornix
  - [ ] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [ ] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [x] Run `scripts/test-documentation.sh|bat` and add file or fix issues if there are new colors that are not documented - @aeschli 

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame. **endgame master**

##### Wednesday/Thursday
- [x] Build stable for all platforms **endgame master**
- [x] Sanity check of installable bits
  - [x] Windows 32 bit **@bpasero**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit **@dbaeumer**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] OS X - **@weinand**
  - [x] Linux
    - [x] deb package 64-bit **@jooamoreno**
    - [x] rpm package 64-bit **@chrmarti**
    - [x] archives **@jooamoreno**
    - [x] snap **@jooamoreno**
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers)) **@sandy081**
- [x] Publish website **@gregvanl**
- [ ] Publish Localization language pack **@weeteckt**
- [x] Publish to stable **endgame master**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **endgame master**
- [x] [Publish @types/vscode](https://github.com/microsoft/vscode/wiki/Publish-vscode-types) **endgame master**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@chrisdias**

**Comment by gudvinr** [comment]
> release notes are collected in a file named `Month_Year.md`

I think you kind of need to update your templates. It's named like `vNext_Version.md` for a while.

**Comment by Calebyang93** [comment]
Hi @sandy081, please add me in. I am interested to contribute.

**Comment by Tyriar** [comment]
@Calebyang93 unfortunately our endgame process isn't really set up for those outside the core team to contribute.

**Comment by Calebyang93** [comment]
> @Calebyang93 unfortunately our endgame process isn't really set up for those outside the core team to contribute.

Thats fine! Thanks for clarifying! @Tyriar

**Comment by Techman** [comment]
The OSS tool link appears to be not found. Is this intentional?

**Comment by dhuber666** [comment]
Hi,

I can't wait for the settings sync in new version. Since 2 hours the checkbox "Manually Release Insider" is checked. Does that mean a new update arrives soon in my VSC Insider with settings sync? 

Can't wait. You guys are the best, keep on with this awesome work you do!
Greets from Austria

**Comment by sandy081** [comment]
I can see your excitement but sad to say that Settings Sync is not yet available in insiders. We are working towards providing it soon - https://github.com/microsoft/vscode/issues/90129

**Comment by GustavoASC** [comment]
Congrats for making this great editor!!!
