### ISSUE TITLE
re-use an LSP from a separate extension

### ISSUE THREAD

**Issue by amircodota** [microsoft/vscode#89329]
Hi

I'm writing a vscode extension that support multiple programming languages, and that requires all sorts of code analysis, normally provided by an LSP.

I can start my own LSP for each supported language, but that has several disadvantages:

1. It will use a lot more machine resources.
2. It requires that I install those lsps and any dependency they may require (python, node, java)

What I would ideally like is to re-use whatever LSP vscode already started. A node developer most likely already has a JS LSP running, and a python developer will most likely have a python LSP running.

Searched both the docs and the code, but it seems each plugin starts its own LSP, and it is hidden deep in the plugin, and not exposed to the outside.

Thanks
Amir

**Comment by dbaeumer** [comment]
From an vscocde extension you can use API commands (https://code.visualstudio.com/api/references/commands) to call into language features provided by another plugin.

**Comment by amircodota** [comment]
@dbaeumer That helps a lot. Thanks!
