### ISSUE TITLE
Emmet settings bug (filter)

### ISSUE THREAD

**Issue by nicothin** [microsoft/vscode#89321]
- VSCode Version: 1.41.1
- OS Version: windows 10

Steps to Reproduce:

1. add to preferences:
```
  "emmet.syntaxProfiles": {
        "html": {
            "filters": "bem"
        }
    },
```
2. type in html-file: `.foo__bar` (element class)
3. press TAB
4. see `<div class="foo foo--bar"></div>` (modifier class)

**Comment by octref** [comment]
What should it expand to? Also for me it expands to `<div class="foo foo_bar"></div>`>
