### ISSUE TITLE
Test peek focus enhancements

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89327]
Refs: #23001

- [x] anyOS @sandy081
- [x] anyOS @stevencl

Complexity: 1

---

There is a new setting and command to change (default) focus of the peek view, either the tree (default) or the editor. Test that

* the `togglePeekWidgetFocus` command (default to Cmd+K | F2) toggles focus
* the `peekWidgetDefaultFocus` allows to set the default focus
* focus stays stable when peek moves between different editors

**Comment by stevencl** [comment]
No issues found on Windows
