### ISSUE TITLE
Test code action preview API proposal

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89335]
Refs: #77728

- [x] anyOS @bpasero
- [x] anyOS @rebornix

Complexity: 4

---

This test-item is the extension of https://github.com/microsoft/vscode/issues/89331. The latter is only about the rename flow (which we are shipping for the Jan release) and this item is about an api proposal that allows extension to express that a preview is needed in order to continue, e.g because suggested edits are of low confidence. 

The current API proposal can be seen here: https://github.com/microsoft/vscode/blob/8c2a25968f24ac772e202d4a88ee7ef801205f6c/src/vs/vscode.proposed.d.ts#L1429-L1448 and the attached zip implements an extension that uses the rename flow to trigger some more advanced workspace edits, e.g those that create, rename, and delete files as well as classifying them. For testing use the extension below or fancy your own (but note that you currently need to use the rename flow) 

➡️ [refacto.zip](https://github.com/microsoft/vscode/files/4116918/refacto.zip)

Download the extension above, run `npm i` and press F5. Create a `test.refacto` file with some text with some repeating words. Test that

* preview always shows when the extension marks any edit with `needsConfirmation: true`
* renaming a word will show a preview with some changes unchecked and with them being assigned in various categories
* there is a toggle action to groups items by type/category or by file (panel menu and context menu)
* categories with unchecked changes are sorted atop
* checked states are preserved when toggling the grouping
* Add the lines below to the file and execute rename on them, play with the edits and make sure things make sense, e.g when unchecking file creation then text edits in that file should be disabled etc. 

```
createNewFile
createNewFileWithContent
deleteThisFile
editAndRenameThisFile
renameAndEditThisFile
```

**Comment by rebornix** [comment]
The API works as advertised, I only ran into a couple of issues while applying changes / diff.
