### ISSUE TITLE
Terminal Processes Terminated Exit Code 5

### ISSUE THREAD

**Issue by reneeskinner** [microsoft/vscode#89338]
We have written the needed daAll folders I have, if I open any of them and click Terminal and then new, it starts a new terminal for me but then as soon as it appears it disappears stating "The terminal process terminated with exit code: 5". I have been working in it fine for weeks.ta into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
This means that your shell exited with a code of 5. You have likely configured something wrong in your system or VS Code.

**Comment by reneeskinner** [comment]
Thank you all, I did discover my company blocked my access to Powershell...issue resolved.
