### ISSUE TITLE
Test preview of rename changes

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89331]
Refs: https://github.com/microsoft/vscode/issues/77728

- [x] anyOS @roblourens
- [x] anyOS @joaomoreno 

Complexity: 4

---

We are adding ways to preview change a code action is going to make. For this milestone, we have added it to the rename flow (more to come for other refactoring). For rename, test that

* the rename input box hints how to accept and preview changes (e.g enter and shift+enter)
* the `"editor.rename.enablePreview"`-setting allows to enable/disable rename preview *per* language
* the preview shows each change the extension wants to make (grouped by file)
* selecting a change a diff editor opens
* checking/unchecking a change updates the diff editor
* checking/unchecking a change applies/drops a change when applying the rename (this could be used when renames in string or comments are also suggested)
* checking/unchecking of parents/children behaves "natural"
* the refactoring can be accepted or dismisses from the panel toolbar 
* accepting or dismissing changes restores the initial workbench view state, e.g the preview panel goes and diff editors close

**Comment by joaomoreno** [comment]
Good job, this is pretty cool!
