### ISSUE TITLE
[semantic][typescript] Constants with function type should be rendered as functions

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#89337]
Issue Type: <b>Bug</b>

If function is declared as `const` + arrow function it will be hightlighted as variable in editor, but as function in hover.

![image](https://user-images.githubusercontent.com/1312662/73173358-da3c8100-410d-11ea-8a2b-782d67fc0b61.png)

Is it expected behavior?

/cc @aeschli 

VS Code version: Code - Insiders 1.42.0-insider (3c6f6af7347d38e87bc6406024e8dcf9e9bce229, 2020-01-27T05:27:06.595Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
In general, with semantic highlighting there will be difference between code in the editor and code snippets in hovers the's no semantic resultion possible in hovers (lack of context).

The sample that you show is interesting, and not really related to semantic information. The TypeScript TextMate grammar classified `fn` as a function, but semantic highlighting calls is a `variable`. So basically the type of the variable is used to figure out that it is a function.
I will fix this in the semantic highlighting code.

**Comment by IllusionMH** [comment]
> So basically the type of the variable is used to figure out that it is a function.

Looks like this is only working with variables, and interesting that TS doesn't highlight properties with arrow functions.
![image](https://user-images.githubusercontent.com/1312662/73183313-45448280-4123-11ea-9a44-7562302703b4.png)

>I will fix this in the semantic highlighting code.

So constants with function type will be highlighted as functions (yellow)? That would be awesome!

BTW, TS doesn't highlight unions as function even if all union members are function types 😢 
![image](https://user-images.githubusercontent.com/1312662/73184481-2b0ba400-4125-11ea-81a0-e424b8f6fe6d.png)

**Comment by aeschli** [comment]
fixed by https://github.com/aeschli/typescript-vscode-sh-plugin/commit/10f9e7f40b055b43d29fc515d2ab34f01c1879ac
