### ISSUE TITLE
Debugger variable inspection splits variables through $

### ISSUE THREAD

**Issue by alexandercerutti** [microsoft/vscode#89332]
- VSCode Version + OS Version:

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

But this happens also on previous releases (I was experiencing this on vscode <= 1.30.x )

Steps to Reproduce:

1. Write Javascript/Typescript code with an object that has a property with a dollar sign somewhere in the middle of its name.
2. Enter in debug mode and put the mouse on that variable. First part will result as `undefined`, the second part will match all the variable. Look at the gif.
It is not a great problem, but it may be error prone, as one might put the mouse above, assuming that it is read as one variable.

![report2](https://user-images.githubusercontent.com/5442545/73170662-4368c800-40ff-11ea-9044-e9b7ff3fb4b0.gif)

Debug sidebar only shows one variable (the complete one) as the hover window.

If this is done with a code like this:

```
const myvar$x = 5;
console.log(myvar$x);
```

Debugging `myvar$x` only shows the value `5` if the mouse is on `x`, but does not show anything on `myvar$`

Does this issue occur when all extensions are disabled?: I don't know. To debug this I'm using Google Chrome Extension. I had not the possibility to test it on a node application yet.

**Comment by gjsjohnmurray** [comment]
See #89084. Once this API lands and is adopted by debug providers it will be possible to fix this.

**Comment by weinand** [comment]
Even without the new API proposed in #89084 we could fix this by using a language-specific word definition in the current hover implementation.
