### ISSUE TITLE
Themes crashes and resets to default

### ISSUE THREAD

**Issue by jcvidiri** [microsoft/vscode#89349]
Issue Type: <b>Bug</b>

If i try to use a theme extension like the Atom One Dark Theme / One Dark Pro, it seems to work but after aprox 2 seconds something breaks and goes back to another theme which my best guess is the default theme

1 - install & enable extension Atom One Dark.
2 - open a .js or .ts file
3 - wait aprox 2 seconds

I tried updating & restarting VS Code
Here you have a gif showing the change in theme http://g.recordit.co/ItTFzYQgrD.gif

VS Code version: Code - Insiders 1.42.0-insider (5dcf2c96b6562b3aa879dbb455de4b58e17cb804, 2020-01-27T11:19:19.244Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|64.00GB (36.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
jenkins-status|ale|3.1.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
cloudcode|goo|1.0.1
graphql-for-vscode|kum|1.15.3
dotenv|mik|1.0.1
vscode-docker|ms-|0.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
postcss|ric|2.0.0
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.4.3
vscode-spotify|shy|3.1.0
vscode-icons|vsc|9.7.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.7.0
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you reproduce if you disable `code-settings-sync`?
