### ISSUE TITLE
Don't use (editor) command outside of editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89348]
The following files use an abstract [command](https://github.com/microsoft/vscode/blob/783970456be0c7634348e01ee61b2abb9a6ef3b1/src/vs/editor/browser/editorExtensions.ts#L59) from the editor world... That is bit awkward as it makes thing depend on the editor which actually don't depend on it, e.g the terminal needs the editor...

- [x] src/vs/workbench/contrib/webview/electron-browser/webview.contribution.ts @mjbvz 
- [x] src/vs/workbench/contrib/webview/browser/webview.contribution.ts @mjbvz 
- [x] src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts  @Tyriar 
- [x] src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts @roblourens 
- [x] src/vs/workbench/contrib/extensions/browser/extensionEditor.ts @sandy081 

Since this milestone there is [`registerAction2`](https://github.com/microsoft/vscode/blob/2175d4c0dd2921004566bc63156372ae173f7a8d/src/vs/platform/actions/common/actions.ts#L364) which is a workbench utility, is modelled after the editor world, and uses only "modern" concepts like menu registry, keybindings registry, and command registry.

**Comment by mjbvz** [comment]
@jrieken Can we update `registerAction2` to take a `Action2` instead of a constructor? Feels like I'm having to create boilerplate classes for it

**Comment by jrieken** [comment]
@mjbvz not sure that I understand that. Do you just want to provide an object literal instead of the class instance? That could work but the current thinking for having a constructor is that it will allow to delay instantiation, e.g make it happen only during some lifecycle phase and not when loading code.

**Comment by mjbvz** [comment]
I prefer defining the commands separately from their registration. Right now, that means creating extra classes like so:

https://github.com/microsoft/vscode/blob/3635373065cbc44e2f744d39c9b79f0ffebdeb4b/src/vs/workbench/contrib/webview/electron-browser/webview.contribution.ts#L33

It'd be nicer if I could just pass the actual instance of the command to `registerAction2(new webviewCommands.CopyWebviewEditorCommand(contextKeyExpr))`, but I see that most callers of `registerAction2` are using inline classes

**Comment by roblourens** [comment]
I have to add 'title' to a bunch of actions that didn't previously have them, but it doesn't actually appear anywhere unless the command is in a menu or command palette right?

**Comment by jrieken** [comment]
> but it doesn't actually appear anywhere unless the command is in a menu or command palette right?

Yeah, when there is no menuId (or no `f1`-shorthand) then the title won't be shown except for the keybindings editor. That's actually why I thought it's a good idea to enforce them.

**Comment by jrieken** [comment]
> It'd be nicer if I could just pass the actual instance of the command to registerAction2(new webviewCommands.CopyWebviewEditorCommand(contextKeyExpr)), but I see that most callers of registerAction2 are using inline classes

Yeah, we can certainly do that. The editor world as something similar which helps when you need to dynamically generate actions, like "Folder Level 0,1,2...N". But then you are responsible for the construction and won't benefit form future, potential lazy instantiation tricks
