### ISSUE TITLE
Search in folder (absolute include path search) should override excluded search settings

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#8934]
- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce:
1. Set "search.exclude" to:

``` js
"search.exclude": {
  "**/node_modules": true,
  "**/bower_components": true
},
```
1. Right-click on a `bower_components` folder and choose "Find in Folder"

Since the folder is excluded through settings, no results will show in your searches. 

What I would expect is that if an absolute path "files to include" (not glob) would be completely excluded by the exclude settings, it would prefer the includes. I don't want to right-click on my "public" folder and get "bower_components" results, but if I search specifically on the "bower_components" folder I would want to see the results.

**Comment by jaichandra** [comment]
I see that this bug is long pending. Is there a workaround to search in ignored directories (like bower_components) for now?

**Comment by roblourens** [comment]
Implemented in https://github.com/Microsoft/vscode/commit/ed91b067e075457791e5e523d25e110c57650a4b for 1.12.

Caveat - if your glob is like `**/node_modules`, then you can use `./node_modules` in 'files to include' and search inside node_modules. But, if it's like `**/node_modules/**`, then those files will still be excluded. Just as a result of how the glob patterns are implemented.

So then another workaround is the new button in the search viewlet which disables the search/files.exclude settings entirely.

**Comment by roblourens** [comment]
#18334
