### ISSUE TITLE
Review Semantic token LSP specification

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#89347]
Refs: https://github.com/microsoft/vscode-languageserver-node/issues/368

- [x] anyOS @aeschli
A proposed implementation of semantic tokes in LSP can be found here: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.sematicTokens.proposed.ts#L1 

Please review the proposed API around the following areas:

- client capabilities (announcement of token types and modifiers)
- server capabilities (there is only one registration with one legend)
- the provided Semantic tokens builder here: https://github.com/microsoft/vscode-languageserver-node/blob/master/server/src/sematicTokens.proposed.ts#L45

There is also an example in case you want to look at a server implementation here: https://github.com/microsoft/vscode-languageserver-node/blob/master/testbed/server/src/server.ts#L476

To run the example do: 
- clone the repository
- run `npm install`
- run `npm run symlink`
- run `npm compile`
- run `npm run symlink:testbed`
- run `npm compile:testbed`
- open VS Code
- run the launch config `Launch TestBed`
- open a bat file (there is a test workspace inside the testbed folder)

**Comment by sandy081** [comment]
@dbaeumer `- [ ] anyOS (not Windows) @aeschli` does not adhere to the template. Fixed it.

**Comment by dbaeumer** [comment]
@sandy081 sorry thanks for fixing.
