### ISSUE TITLE
file names not vibile (white on white

### ISSUE THREAD

**Issue by noam1023** [microsoft/vscode#89345]
Issue Type: <b>Bug</b>

open a directory, the file icons are visible, but the names are invisible.
OS: ubuntu 18.04

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2473)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.88GB (15.11GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.3

</details>

**Comment by joaomoreno** [comment]
Can you share a screenshot of what you mean?

**Comment by noam1023** [comment]
![image](https://user-images.githubusercontent.com/1450057/73435130-be74ed00-4350-11ea-9b4c-5f4414b7df45.png)

**Comment by noam1023** [comment]
note: dragging  a rectangle area with the mouse show the  file name in "almost white" color

**Comment by joaomoreno** [comment]
This is an issue with your GTK theme, not with VS Code.
