### ISSUE TITLE
"Create new integrated terminal" (+) is not aligned

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode#89346]
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
Steps to Reproduce:
```
1. Click on <kbd>control</kbd> + <kbd>~</kbd>
2. Look on the quick menu that just opened

<img width="298" alt="Screen Shot" src="https://user-images.githubusercontent.com/3723951/73180819-c4838780-411e-11ea-8d74-37d974d5e858.png">

**Comment by moshfeu** [comment]
That you gentlebot but it's not a duplicate

**Comment by Tyriar** [comment]
@chrmarti some changes happened to alignment in quick picks recently?

<img width="238" alt="Screen Shot 2020-01-27 at 8 53 51 AM" src="https://user-images.githubusercontent.com/2193314/73195362-96805200-40e2-11ea-9553-6438a8e798a3.png">

**Comment by AlexStrNik** [comment]
@Tyriar the icon aligned wrong coz it added through `IconLabel` and generated markup has no styles for alignment in `quick-open-entry`. So in my PR, I added icon by overriding the `getIcon()` method in the `CreateTerminal` class. And now it aligns right way

**Comment by chrmarti** [comment]
@misolori This is QuickOpen that might need a similar fix to #84124.

**Comment by misolori** [comment]
I actually just fixes this earlier via https://github.com/microsoft/vscode/commit/d6e0e7156ef3ea6089abda7fb3e4f6646dc9ed7d

**Comment by moshfeu** [comment]
Confirmed. Thanks!
