### ISSUE TITLE
[semantic][typescript] Highlight Global Variables 

### ISSUE THREAD

**Issue by ButchMonkey** [microsoft/vscode#89350]
Ability to be able to have different syntax highlighting for global variables. (Specifically JavaScript, but this would be useful in other language)

For example, here is a screenshot from NetBeans
![image](https://user-images.githubusercontent.com/9367266/73190542-1081fc80-411e-11ea-987d-824465c957f9.png)

Current behaviour in VSCode
![image](https://user-images.githubusercontent.com/9367266/73190620-298aad80-411e-11ea-8b97-c7a5c415946d.png)

Current Global TM Scope
![image](https://user-images.githubusercontent.com/9367266/73977440-498e4e00-4922-11ea-865b-269d48a54666.png)

**Comment by ButchMonkey** [comment]
To further add - 
Essentially ["Enhanced colorization for C++"](https://code.visualstudio.com/docs/cpp/colorization-cpp) but for Node.js / Javascript (and other popular languages) 
So that theme designers can access  `variable.other.global` and `variable.other.local`

**Comment by aeschli** [comment]
The typescript server now marks all local variables.

**Comment by ButchMonkey** [comment]
👍 

Local variable styling is looking good -
![image](https://user-images.githubusercontent.com/9367266/75171873-3fdb5780-5724-11ea-9d4d-0b610e475eb5.png)

I tried to also style the inverse (i.e global) by setting the `variable` `fontStyle` and unsetting the `fontStyle` for local types. However, the style seems to get ignored. Is there a way to override this and force the priority?


![image](https://user-images.githubusercontent.com/9367266/75172252-df004f00-5724-11ea-8614-38d86e581270.png)

**Comment by ButchMonkey** [comment]
I'm able to get the desired effect using the following rules - 
```
    "editor.tokenColorCustomizationsExperimental": {
        "variable": {
            "fontStyle": "underline",
            "foreground": "#CC6666",
        },
        "variable.local": {
            "fontStyle": "",
            "foreground": "#CC6666",
        },
        "variable.readonly": {
            "fontStyle": "",
            "foreground": "#CC6666",
        }
    }
```
However, it looks like `support.class` is being overwritten by the semantic token type.
As far as I'm aware, semantic takes priority over the textmate scopes. Is there a workaround for this?

![image](https://user-images.githubusercontent.com/9367266/75175476-4ec50880-572a-11ea-9010-fe40acb5fa77.png)

**Comment by aeschli** [comment]
The request for adding support for library symbol is : https://github.com/microsoft/vscode/issues/91090
