### ISSUE TITLE
Search Editor: Add settings for search option default values

### ISSUE THREAD

**Issue by adamlogic** [microsoft/vscode#89353]
Since the new Search Editor treats each search as a *new* search, it doesn't remember the options for "Match Case", "Match Whole Word", and "Use Regular Expression" (as the sidebar search does). This makes logical sense, but it's inconvenient if you need to toggle those options manually for every search.

It'd be very helpful to specify default search options, so that for example, "Use Regular Expression" was always enabled for each new search.

Ref https://github.com/microsoft/vscode/issues/88154#issuecomment-578559837

**Comment by karlhorky** [comment]
@JacksonKearl This is still an upcoming feature, right? Can we expect it in the March or April releases?

**Comment by JacksonKearl** [comment]
@karlhorky We'll probably add either default or persistent options, but I don't have a specific timeline for it.

**Comment by JacksonKearl** [comment]
You can try out `"search.searchEditor.experimental.reusePriorSearchConfiguration": true` in tomorrow's insiders (not the next Insiders to be released but the one after it) and let me know what you think.

**Comment by JacksonKearl** [comment]
Going to let this cook as an experimental setting for a bit. If others come across this issue and this works, please upvote so I know it's desired, or comment if this doesn't work as you'd expect.

**Comment by karlhorky** [comment]
@JacksonKearl thanks!

Which issue should we give a thumbs-up to? Your comment with the configuration setting (https://github.com/microsoft/vscode/issues/89353#issuecomment-611537268)?

I would suggest against using adamlogic's original description at the top: I think this would be misleading, since a lot of users upvote issues that they **want implemented** (not even knowing that it is already done), instead of meaning to upvote your implementation thereof.

**Comment by carlocardella** [comment]
> You can try out `"search.searchEditor.experimental.reusePriorSearchConfiguration": true` in tomorrow's insiders (not the next Insiders to be released but the one after it) and let me know what you think.

Is this available yet (in Insiders)? I can't find that setting

**Comment by JacksonKearl** [comment]
@carlocardella its hidden - you’ll have to paste the json manually.

**Comment by JacksonKearl** [comment]
Took the setting out of `experimental`, now you'll be able to find it in the UI settings editor. Also related #95582, which allows you to pass args in the keybinding configuration:
```
    {
        "key": "ctrl+shift+g",
        "command": "search.action.openNewEditor",
        "args": {
            "query": "${selectedText}",
            "filesToInclude": "${relativeFileDirname}"
        },
        "when": "editorTextFocus"
    }
```

Explicitly passed args override prior config.

**Comment by karlhorky** [comment]
Nice! This will appear for users in the stable May 2020 update?

**Comment by JacksonKearl** [comment]
Yes. And it will be out in the next Insiders release.

**Comment by dufferzafar** [comment]
@JacksonKearl When using this, and running it with no text selected, I get `'${selectedText}' can not be resolved. Make sure to have some text selected in the active editor.` 

Is there a way to define a single keybinding that can default to empty string if there is no text selected? Perhaps a `${selectedTextOrEmpty}` variable?

```json
    {
        "key": "ctrl+shift+g",
        "command": "search.action.openNewEditor",
        "args": {
            "query": "${selectedTextOrEmpty}",
            "filesToInclude": "${relativeFileDirname}"
        },
        "when": "editorTextFocus"
    }
```

**Comment by JacksonKearl** [comment]
By default it will use your selectedText or the empty string, you don’t need to include anything for `query`

**Comment by karlhorky** [comment]
Just received the VS Code May 2020 (1.46) update and the configuration below works well, thanks @JacksonKearl !

```json
"search.searchEditor.reusePriorSearchConfiguration": true
```
