### ISSUE TITLE
Minimap shows only half of select all selection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89354]
After cmd+a on latest insiders (mac)

<img width="147" alt="Screen Shot 2020-01-27 at 8 39 23 AM" src="https://user-images.githubusercontent.com/2193314/73194156-95e6bc00-40e0-11ea-9b95-91138eb10eec.png">

**Comment by connor4312** [comment]
Are you on a high DPI monitor?

**Comment by Tyriar** [comment]
@connor4312 yep, macbook monitor.

**Comment by connor4312** [comment]
Cool, thanks. I know where the bug is.

**Comment by connor4312** [comment]
To verify:

 1. With the minimap enabled on a high DPI (e.g. macbook) display, open a large file that takes the whole minimap height.
 2. Select all
 3. Verify all lines in the minimap are shown as selected
