### ISSUE TITLE
Test TypeScript/JavaScript semantic highlighting

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#89351]
Testing https://github.com/microsoft/vscode/issues/77140

- [x] anyOS @JacksonKearl
- [x] anyOS @RMacfarlane

Complexity: 4

---

Semantic highlighting has been added for JavaScript and TypeScript.
All identifiers are classified on the type of the underlying symbol:
 - class, enum, interface, namespace, typeParameter, type, parameter, variable, property, function, member

Additionally, the following modifiers are added:
-  declaration (when the symbol is declared at that location), static, async, readonly

There hasn't been any changes to our built-in themes to show information that hasn't been shown before. But highlighting has changed for the cases where symbols were variables but are now classified as a type or a namespace. E.g. mports now highlight according to the type of the identifier
- test various files with and without semantic highlighting, look at the differences and verify that the user experience is better, not worse.
- use the `Developer: Inspect Editor Token and Scopes` tool to see what style has been given to a token. The hover also shows the textmate scopes at the location and what the old style would have been.
- use `"editor.semanticHighlighting.enabled": false` to turn off semantic highlighting

Test classification:
  - Poke around and check whether some identifiers are missed or maybe are even wrong. This get interesting when an identifier represents both a type and a namespace.
  - Verify that JSX element get no semantic highlighting

**Comment by JacksonKearl** [comment]
Looks good to me
