### ISSUE TITLE
Show close (all) tab keybindings

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#8935]
- VSCode Version: 1.3.0
- OS Version: OS X 10.11.5

Steps to Reproduce:
1. Open a couple of tabs
2. Hover over the close button of the tab until a popup appears `Close`

I think it would be nice of the keybinding (default <kbd>Cmd</kbd>+<kbd>w</kbd>) was shown in the hover popup label. Same goes for the `Close all` action when pressing the 3 dots on the side of the panel.

If I find some time I will do a PR for this if you guys agree on it.

// @bpasero

**Comment by bpasero** [comment]
@SamVerschueren I am seeing the keybinding as soon as I assign to `workbench.action.closeEditorsInGroup`.

+1 for a PR, the same tooltip should also show up in the "opened editors" view section.

**Comment by SamVerschueren** [comment]
Odd, I don't see it. Are you on Windows or Mac?

![screen shot 2016-07-08 at 16 49 01](https://cloud.githubusercontent.com/assets/1913805/16691196/f50e067a-452b-11e6-9566-c1c195f8bcf3.png)
![screen shot 2016-07-08 at 16 49 11](https://cloud.githubusercontent.com/assets/1913805/16691199/f725d5f0-452b-11e6-834d-8a7e41721ce6.png)

**Comment by bpasero** [comment]
@SamVerschueren needs a restart, and yes cannot display choords in there.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14622
