### ISSUE TITLE
Jupyter notebook - zeros out file

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode#89368]
These steps resulted in a corrupted Jupyter notebook, of zero bytes (contents lost):
1) Open .ipynb file in VS code
2) VS Code fails to start kernel
3) Start notebook server manually in powershell terminal
4) Open notebook in browser (e.g. not in vs code) - file fails to load. 
5) close .ipynb file in VS code
6) File shows 0 bytes in file explorer. 

System:

Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3691)
--
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.93GB (2.64GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by rebornix** [comment]
@jmagosta Jupyter notebook feature is provided by extensions but not VS Code core so please file issues against the extension which provides this feature. Thanks!
