### ISSUE TITLE
Manual .vsix installation can duplicate installed marketplace extensions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89366]
@eamodio noticed that installing an extension from a `.vsix` doesn't replace the marketplace extension. If a marketplace extension was already installed, both the marketplace and vsix version will be installed and persist after refresh. We should probably automatically uninstall the vsix or marketplace version when the other is installed.

![image](https://user-images.githubusercontent.com/2230985/73204604-19f66f00-40f4-11ea-9fb5-e75c76544410.png)

**Comment by eamodio** [comment]
After this happened, I uninstalled one of those entries which vscode showed as removing both. Then I restarted vscode and there were none. Then I re-installed the `vsix` and now there are 2 again.

**Comment by sandy081** [comment]
I cannot repro this with the vsix I downloaded from Marketplace. Can you please share the vsix you used?

**Comment by eamodio** [comment]
Here's the vsix
[js-debug-nightly.vsix.zip](https://github.com/microsoft/vscode/files/4123170/js-debug-nightly.vsix.zip)

**Comment by sandy081** [comment]
@connor4312 @eamodio Can't repro. Are you able to repro it still?

**Comment by eamodio** [comment]
Yes, it still happens on today's insiders for me with that vsix.

**Comment by eamodio** [comment]
And now that I've installed that vsix again as a test, uninstalled it,closed vscode multiple times, and removed the extension from the user profile (since it was left behind) -- something is still left behind. VS Code doesn't show the extension anywhere in the UI (installed/disabled/etc), but if I search for the extension to install the marketplace version, VS Code thinks its kind of installed:

![image](https://user-images.githubusercontent.com/641685/73477326-00f2f580-4362-11ea-82d2-a1ed6152234c.png)

Oddly _Uninstall_ is disabled too.

**Comment by eamodio** [comment]
I've tried installing another version -- and that seems fine. But if I uninstall that one, it goes away, but the same thing happens when I go to search to install it from the marketplace... there is something left behind somewhere.

**Comment by sandy081** [comment]
I suspect these inconsistencies are coming because this extension is made built in and now you have this at two places (built in and installed location).

**Comment by eamodio** [comment]
I didn't think the js-debug was built-in yet

**Comment by connor4312** [comment]
If you were on the latest insiders on the 27th it would have been built-in

**Comment by sandy081** [comment]
To verify:

- Download and install the VSIX from https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug
- Make sure only user installed extension is shown in the extensions view.
