### ISSUE TITLE
Docker extension cannot be installed remotely (Remote-SSH) when it is installed locally

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode#89363]
- VSCode Version: 1.41.
- OS Version: Windows 10 Enterprise 1909 build 18363.592

Steps to Reproduce:

1. Install Microsoft VS Code Docker extension version 0.9.0 (current as of 1/27/2020) or newer
2. Use `Remote SSH: Connect to Host...` to connect to a remote machine with Docker installed (used Ubuntu 18.04 LTS).
3.  Open Extensions view in the remote VS instance

Expected:
VS Code should offer to install the Docker extension on the remote machine

Actual:
It does not (VS Code only offers to disable or uninstall the extension)

Remarks:
I am part of the team that owns Docker extension and we cannot think of anything changing on our side that would make the above stop working.
It used to work around last year's October timeframe (we have screenshots to prove https://github.com/microsoft/vscode-docker/wiki/SSH#using-visual-studio-code-remoting)
Interestingly, the extension does work if it is **installed remotely first** : https://github.com/microsoft/vscode-docker/issues/1582#issuecomment-578882428

Please help us troubleshoot this. The Remote-SSH is a popular use case for the Docker extension.

**Comment by chrmarti** [comment]
@sandy081 The Docker extension is marked as `"ms-azuretools.vscode-docker": [ "workspace", "ui" ]` in stable and insiders. Shouldn't that allow the extension to be installed remotely?

**Comment by sandy081** [comment]
/duplicate

#83675 Yes, we show install in remote/local button only if extension is on wrong side and disabled.

**Comment by karolz-ms** [comment]
@sandy081 @chrmarti Thanks for confirming the issue.I just want to make sure that it is understood that this issue is a **regression from previous state**, and one that is already significantly affecting the adoption of our extension (we are hearing directly from customers that "Docker extension does not work with SSH" and this issue is big part of the problem).

I am bringing this up because the duplicate bug https://github.com/microsoft/vscode/issues/83675 (that I cannot comment on) is marked as "feature request", and this is definitively not a new feature request for us.

**Comment by sandy081** [comment]
There is no regression here. It seems the docker extension is defined as `workspace + ui` kind. It means it can run on both remote and local (preferably remote). This is a new feature.

**Comment by karolz-ms** [comment]
@sandy081  it is true that we only recently started to advertise as being able to work remotely and locally. We did it only because previously there was no capability in VS Code to indicate that. 

The original implementation seems to assume that when an extension is advertising that it can run both locally and remotely, installing it locally delivers complete user experience. This is clearly not the case with Docker extension--it both makes perfect sense, and is a mainline scenario to install it in both places, because one typically runs different Docker daemons locally vs remotely.

So my point is the current behavior (inability to install an extension remotely if it is installed locally) is a bug and not some extra functionality.

CC @chrmarti

**Comment by karolz-ms** [comment]
@Chuxel what is your take on this? It (installing and using Docker extension remotely via SSH) used to work back in November last year. We did as instructed by EGamma and changed the Docker extension to be "workspace + ui" and now the SSH scenario is broken...

**Comment by Chuxel** [comment]
@sandy081  @chrmarti @karolz-ms @egamma Regardless of classification, I would expect in this case to at least have the option to install in the container.  This is particularly true when something prefers workspace - this indicates that it is secondary that it would run in the UI environment rather than primary. I could see not providing this option in the case the extension is already installed in the preferred host, but this is the reverse of that.

@sandy081 To be specific, there is a valid scenario for the extension to run in either location. Depending on the scenario, you may want the Docker extension remotely or locally. There's no single "right" answer for this extension.  The fallback would be likely to default to "workspace" which would prevent users from being able to actually connect to the local Docker demon when connected to a container or WSL.

**Comment by sandy081** [comment]
Please note that I accepted this request here - #83675. I would not go deep in discussing whether it is a feature request or bug. It seems necessary to provide this functionality so I assigned #83675 to next milestone as we are currently in the end game for current milestone.

**Comment by karolz-ms** [comment]
@sandy081 thank you, glad this is on track to be fixed in the next milestone!
