### ISSUE TITLE
Notifications should always stay in view even if window is outside screen

### ISSUE THREAD

**Issue by btholt** [microsoft/vscode#89369]
We saw this happen in a UX study we ran. A user was deploying to Azure Functions and had the VSCode window pulled slightly off screen so the bottom right of the window was off the display. The Azure Functions extension notified the user that Azure Function was finished deploying but the user didn't see it because of how the VSCode window was sitting slightly off screen. This caused some confusion in the user as they waited for a notification to tell them that their app had finished deploying.

**Comment by thinkjrs** [comment]
Firstly, great work. Team + community has rocked Vscode. 

However, please consider this a downvote from me. I am strongly against this _feature_. Amongst those with whom I work, those notifications tend to be an extraordinary nuisance. 

I found this issue actually looking for simple ways to disable the workbench notifications altogether, ironically.

https://github.com/microsoft/vscode/issues/46676
