### ISSUE TITLE
Improve integrated terminal

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8936]
- [x] Test Plan Item created
- [x] I18n support
- [x] Key board accessible
- [ ] Screen reader accessible
- [x] Works with the different themes, including the high contrast theme
- [ ] ~~Telemetry events in place~~ (not needed)

**Comment by jfd** [comment]
@egamma Any plans to to support terminals in panes? I would like the terminal to work in the same way as the editor pane, so I can drag it around, placing it to the right or to the left of my code window. I have a wide monitor, but limited vertical space :-)

**Comment by Tyriar** [comment]
@jfd it's been discussed. For now at least we don't want to meld the lines between editors (middle), panels (bottom), viewlets (sidebar), etc. The main concerns with doing so are that it could be quite confusing/unorganized (what does <kbd>ctrl</kbd>+<kbd>tab</kbd> do if a terminal is a tab? What does the toggle terminal action do?) and it may make the editor feel more "heavy".

There are a bunch of issues open to explore a more flexible panel system, that's probably the direction it will go if it does:

- Add maximize panel command #7314
- Make panel position configurable #2806
- Allow multiple panels to be displayed at once #7161

And related for *within* the terminal:

- Provide commands to split the terminal #7504

**Comment by Tyriar** [comment]
Closing off in favor of https://github.com/Microsoft/vscode/issues/8339
