### ISSUE TITLE
Enable selecting multiple text paragraphs

### ISSUE THREAD

**Issue by Ahmed-Hussein-Karam** [microsoft/vscode#89362]
- Version: 1.41.1
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T15:04:31.999Z
- OS: Linux x64 4.4.0-127-generic

# Description:
In order to copy multiple code snippets (or paragraphs) from a single file, one needs to select, copy then paste just one snippet at a time.

## Example:
To copy the first and the fifth lines from a file to some other file:

- **Step 1:** select first line.
- **Step 2:** `ctrl + c`.
- **Step 3:** `ctrl + v` in the target file.
- **Step 4:** select fifth line.
- **Step 5:** `ctrl + c`.
- **Step 6:** `ctrl + v` in the target file.

# Suggestion:
Enable user to select multiple snippets while pressing the `ctrl` key. So, the  above scenario will change like this:
- **Step 1:** select first line.
- **Step 2:** press _and hold_ the `ctrl` key.
- **Step 3:** select fifth line.
- **Step 4:** release the `ctrl` key.
- **Step 5:** `ctrl + c`.
- **Step 6:** `ctrl + v` in the target file.

# Sample use-case:
If one wants to move all `<p>` elements to the bottom of the `<body>` element in a large `html` document. 
- **Without** this suggested feature, one will **_repeatedly_** select a `<p>` element, cut it, scroll deep down to paste it, then scroll up again to copy the next `<p>` element.. and so on.
- **With** the suggested feature, it will be much easier to select all `<p>` elements along the way down until the end of the `<body>` element is reached. After that, a single `cut-paste` will do the task.

# Other Benefits:
- Avoid switching multiple times between 2 files through the `alt + tab` keys before and after each `copy-paste` operation. Instead, it is easier to select all snippets then copy and paste only once.
- Saves some time, especially for routine tasks like copying all function signatures from a `cpp` file and pasting them in an `hpp` file.

**Comment by joaomoreno** [comment]
> In order to copy multiple code snippets (or paragraphs) from a single file, one needs to select, copy then paste just one snippet at a time.

I'm not sure I understand this. Can you share a screen recording of what you mean?

**Comment by Ahmed-Hussein-Karam** [comment]
I added an example with steps. Is it clear enough now?

**Comment by alexdima** [comment]
@Ahmed-Hussein-Karam Out of the box, multi cursor is bound to alt+click. This can be changed to ctrl+click via `"editor.multiCursorModifier": "ctrlCmd"`
