### ISSUE TITLE
Test contributing actions to extension context menu

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89361]
Testing https://github.com/microsoft/vscode/issues/87285

- [x] anyOS @misolori
- [x] anyOS @dbaeumer

Complexity: 3

---

## Testing

Extensions can now contribute actions to an extension's context menu in extension viewlet using the new menu location `extension/context`. You can use the when condition `"when": "extensionStatus==installed"` if you want to have the action only on installed extensions.

Develop an extension that can contribute an action to extension's context menu 

- Make sure the action is shown based on the context you defined.

- Make sure your command is called with the extension id as argument

**Comment by misolori** [comment]
@sandy081 I can't get this to work, can you provide a sample extension that does this? Here's my basic extension:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	console.log('### activated');

	vscode.commands.registerCommand('extension. helloWorld', (extensionId) => {
		console.log('### command registered');
		vscode.window.showInformationMessage(extensionId);
		console.log(extensionId);
	});
}
```
and my `package.json`:

```json
	"contributes": {
		"commands": [
			{
				"command": "extension.helloWorld",
				"title": "👋 Hello World"
			}
		]
	},
	"menus": {
		"extension/context": [
			{
				"command": "extension.helloWorld",
				"group": "2_configure"
			}
		]
	},
```

And I'm assuming "extension context menu" means the gear icon in the extension viewlet on the specific extension? Or is this a different context menu?

**Comment by misolori** [comment]
Forgot that the `menus` needs to be part of `contributes`. It's working now:

![image](https://user-images.githubusercontent.com/35271042/73313805-14c31e00-41e1-11ea-818b-7aad26e7d46b.png)
