### ISSUE TITLE
Panel somehow ended up with no selection (and is blank)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89364]
VS Code version: Code - Insiders 1.42.0-insider (5dcf2c96b6562b3aa879dbb455de4b58e17cb804, 2020-01-27T11:23:59.719Z)
OS version: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/641685/73203812-ca23a200-410b-11ea-8072-2ca3c29c6abc.png)

**Comment by sbatten** [comment]
any dev console output or consistent repro?

**Comment by eamodio** [comment]
Not so far sadly. Though I feel like it was/is related to the debug console sometimes dying (which so far seems to have been resolved in the latest js-debug.

**Comment by sbatten** [comment]
closing with the assumption the above is true. can re-open if it comes back.
