### ISSUE TITLE
HTML code completion recommends invalid "en_US" lang attribute value

### ISSUE THREAD

**Issue by matthew-rister** [microsoft/vscode#89365]
Issue Type: <b>Bug</b>

1. Create an HTML document
2. Type <html lang="e
3. Observe attribute value suggestion

Expected: "en" or "en-US"
Actual: "en_US"

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (32 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.43GB free)|
|Process Argv|F:\git\export-crosstab-options-dialog|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
cpptools|ms-|0.26.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vscodeintellicode|Vis|1.2.4
vscode-icons|vsc|9.7.0

</details>

**Comment by octref** [comment]
I don't see such suggestion. Does this reproduce with all extensions disabled?
