### ISSUE TITLE
VS react project not getting snippets

### ISSUE THREAD

**Issue by ZeroLeg** [microsoft/vscode#89376]
I have 2 projects and in one the snippets of a pluggin works perfect and in the other  project no, if i press cntr+space keeps on "loading"

Someone know why this happen?

**Comment by ZeroLeg** [comment]
Hello again, okay sorry i'll explain a bit better. 

Basically, i got a project, in React, I build it with "yarn create react-app customers-app". Till here, nothing extrange. 
But when I open the project with VS code, the snippets with this project, doesn't work, even the common snippets of JS, doesn't work. For example: 

When you write "log" in a JS file, the snippet prints "console.log();"
So, the problem is, when i create a new project, the snippets of JS doesn't work, and I don't know if is VS code problem, or the problem is when I build the project, because on another project that I have, the snippets works perfecly.

I'll hope that helps you to understand my problem. 
Thnks for you help!!!

**Comment by mjbvz** [comment]
Can you please fill out the issue template and include information such as VS Code version and OS version

**Comment by ZeroLeg** [comment]
SO: Windows 10 Pro N
Code: 
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Extensions:; ES7 React/Redux/GraphQL/React-Native snippets

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Gu-Miao** [comment]
@ZeroLeg 
Recently, i met that problem too. And i slove it by disabling that extensions: ES7 React/Redux/GraphQL/React-Native snippets. Maybe you could try.

**Comment by ZeroLeg** [comment]
WoW!

Here works perfectly with extension inclusive!!!
What difference could be with Insiders vs Code? In VS Code steal not working. 
I tried to reinstall VS Code but the problem is even there. 

Thanks!!!!
