### ISSUE TITLE
Git 2.25.0 breaks functionality due to lower-cased driver letter

### ISSUE THREAD

**Issue by sparebytes** [microsoft/vscode#89373]
Git version `2.24.1.windows.2` does not have this issue but version: `2.25.0.windows.1` does.

- VSCode Version: 1.41.1 (user setup) and 1.42.0-insider (user setup)
- OS Version: Windows 10 build 18363.592
- Git Version: 2.25.0.windows.1

Steps to Reproduce:

1. Install  Git Version: 2.25.0.windows.1
2. Setup new folder with Git and `core.ignorecase=false`:
```shell
mkdir test
cd test
git init .
git config --add --local core.ignorecase false
echo "Hello" > README.md
code --disable-extensions .
```

3. Open Source Control panel and click `Stage Changes` on `README.md`

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/16328067/73211698-5cc73f80-4112-11ea-83f5-03a1a1501c73.png)

**Comment by joaomoreno** [comment]
> core.ignorecase=false

So... is the change between Git 2.14 and 2.15 that this value's default switched?

**Comment by sparebytes** [comment]
I manually set `ignorecase` to false. In my case git defaulted it to true.
I believe the change is that Git is stricter about the paths given to it. I reverted back to 2.14 and VSCode works as expected but if I look at the Output panel in VSCode for Git, I'll see lower case drive letters like so:
```
> git rm --cached -r -- c:\test\README.md
```
The bug appears to be that VSCode has always used lower-cased drive letters when executing git commands.

**Comment by joaomoreno** [comment]
Oh wow, @eamodio was there much earlier: https://github.com/git-for-windows/git/issues/2478

**Comment by joaomoreno** [comment]
@sparebytes Can you show me the full output of `Git: Show Git Output` after trying to add a file?

**Comment by joaomoreno** [comment]
*Repro:*

Make sure you're using Git 2.25, on Windows.

1. Set `core.ignorecase=false`
2. Try to stage/unstage files using VS Code
