### ISSUE TITLE
onDidOpenTextDocument event is missing event information

### ISSUE THREAD

**Issue by peni4142** [microsoft/vscode#89374]
Hi, I have the problem I want to react to onDidOpenTextDocument, when the user is opening a TextDocument. But the event is also triggered if the TextDocument is viewed by SourceControl. This is fatal for my extension. To know the event emitter would be great :-)

**Comment by jrieken** [comment]
There is no way to know why or by whom a document has been opened and your extensions need to be handling this else how, e.g by looking at visible editors or the document's uri-scheme

**Comment by peni4142** [comment]
Do you have more information?

yeah, the problem with the scheme is, vscode is opening the file with the scheme "file" before it is reopening it with the scheme "gitfs".

And checking  `if (window.visibleTextEditors.length > 0) `does not work because the editor could be splitted...

Even if I am able to look at how many times the editor is split, `(splits - window.visibleTextEditors.length > 0)` would not work, because something else could be opened.

**Comment by jrieken** [comment]
> vscode is opening the file with the scheme "file" before it is reopening it with the scheme "gitfs".

It's not reopening the document, it's just opening another (new, second) document with a different scheme. I don't know what you are trying to achieve so I can't give more information 🤷‍♂

**Comment by peni4142** [comment]
I am reacting at onDidOpenTextDocument. But I have not to react if it's opened for source control.

The problem is if TextDocument is opened for source control the event: onDidOpenTextDocument is triggered two times.

First time with the scheme: "file"
Second time with the scheme: "gitfs"

I could wait before I react at onDidOpenTextDocument and look if it triggers a second time, but I think that would the user make think vscode is slow

**Comment by peni4142** [comment]
In case someone is looking for something similar to me
My workaround:
```typescript
import { workspace, TextDocument, window, Uri } from "vscode";

export class API {

    private static lastOpenedComplementary: string = "";
    private static gitMode: boolean = false; // git mode is more precise, but it has to be in a git repository


    private static windowCounter: number[] = [
        window.visibleTextEditors.length,
        window.visibleTextEditors.length
    ];

    public static onDidShowTextDocument() {
        setInterval(() => {
            this.windowCounter.push(window.visibleTextEditors.length);
            this.windowCounter.shift();
            this.lastOpenedComplementary = "";
        }, 300);

        workspace.onDidOpenTextDocument((document: TextDocument) => {
            if (document.uri.scheme === "gitfs") { // fires after every show up of a TextDocument
                if (!this.gitMode) {
                    this.gitMode = true;
                } else { // the file mode will handle the first time
                    let newWindowCounter: number = window.visibleTextEditors.length;
                    if (newWindowCounter - this.windowCounter[0] === 1) { // prevent to act by source control
                        workspace.openTextDocument(Uri.file(document.fileName.substr(0, document.fileName.length - 4))) // cut out ".git"
                            .then((innerDocument: TextDocument) => {
                                this.businessLogik(innerDocument);
                            });
                    }
                }
            }
            if (!this.gitMode) {
                if (document.uri.scheme === "file") { // fires every time when TextDocument is opened, but TextDocuments can stay open while you kill the VisibleTextEditor

                    let windowCounter: number = window.visibleTextEditors.length;
                    setTimeout(() => {
                        if (window.visibleTextEditors.length - windowCounter === 1) {// prevent to act by source control
                            this.businessLogik(document);
                        }
                    }, 100);
                }
            }
        });
    }
}
```

This will mostly call `this.businessLogik` when a new `TextEditor` shows up.

**Comment by jrieken** [comment]
> This will mostly call this.businessLogik when a new TextEditor shows up.

This will not work for any remote case as such documents use `vscode-remote` and neither will it work for any custom file system, like ftp-backends etc.

**Comment by peni4142** [comment]
Yeah recognized when I use an interval I can build my own EventListener.
I think that would be the better solution: 

```typescript
    private static prevState: TextEditor[] = window.visibleTextEditors;

    public static onDidShowTextDocument() {
        setInterval(() => {
            let actualState: TextEditor[] = window.visibleTextEditors;
            try{                
                if (actualState.length - this.prevState.length === 1) {
                    for (let i: number = 0; i < actualState.length; i++) {
                        if (!this.documentIsOpened(actualState[i].document, this.prevState)) {
                            this.businessLogik(actualState[i].document);
                            return;
                        }
                    }
                }
            }
            finally{
                this.prevState = actualState;
            }
            
            
        }, 300);
    }

    private static documentIsOpened(document: TextDocument, textEditors: TextEditor[]): boolean {
        for (let i: number = 0; 0 < textEditors.length; i++) {
            if (document.fileName === textEditors[i].document.fileName) {
                return true;
            }
        }
        return false;
    }
```

What was/is a little bit confusing is I am not really looking for on didOpenTextDocument. Instead, I am looking for something like `onDocumentDidShow` an event for `showTextDocument`.

**Comment by jrieken** [comment]
> What was/is a little bit confusing is I am not really looking for on didOpenTextDocument. Instead, I am looking for something like onDocumentDidShow an event for showTextDocument.


Yeah, that called `onDidChangeVisibleTextEditors` -> https://github.com/microsoft/vscode/blob/8486d683444d324eaaa53ec41e5be7b47fd47a6a/src/vs/vscode.d.ts#L6736

**Comment by peni4142** [comment]
ok I think that is much prettier :)
```typescript
 private static prevState: TextEditor[] = window.visibleTextEditors;

    public static onDidShowTextDocument() {
        window.onDidChangeVisibleTextEditors((actualState:TextEditor[])=>{
            try{                
                if (actualState.length - this.prevState.length === 1) {
                    for (let i: number = 0; i < actualState.length; i++) {
                        if (!this.documentIsOpened(actualState[i].document, this.prevState)) {
                            this.businessLogik(actualState[i].document);
                            return;
                        }
                    }
                }
            }
            finally{
                this.prevState = actualState;
            }
        });
    }
```
