### ISSUE TITLE
Simplify the configuration service, enable programmatic modification

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8937]
* [x] simplify the configuration service
* [x] enable programmatic modification (user, workspace)
* [x] investigate if programmatic modification (tasks, debug) is needed

**Comment by bpasero** [comment]
Related: 
* https://github.com/Microsoft/vscode/issues/6095
* https://github.com/Microsoft/vscode/issues/6093

**Comment by bpasero** [comment]
Done. Continue in https://github.com/Microsoft/vscode/issues/1396

**Comment by bpasero** [comment]
Reopening for supporting tasks and debug as well.
