### ISSUE TITLE
Test `resolveDebugConfigurationWithSubstitutedVariables` hook

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89375]
Refs: #87450

- [ ] anyOS: @connor4312 

Complexity: 3

---

We've introduced a new `DebugConfigurationProvider` hook `resolveDebugConfigurationWithSubstitutedVariables` that receives the debug configurations with all variables resolved.

For verification either create a new extension or modify an existing extension and implement the `resolveDebugConfigurationWithSubstitutedVariables` hook of a registered `DebugConfigurationProvider`.
 
Verify that:
- all variable types (simple, 'env', 'command', 'input', 'settings') are resolved properly.
- new variables introduced in the `resolveDebugConfiguration` hook are resolved in the `resolveDebugConfigurationWithSubstitutedVariables` hook.
- returning `undefined` or `null` results in the specified behavior.

**Comment by connor4312** [comment]
lgtm, didn't run into any issues
