### ISSUE TITLE
Test inline implementations of debug adapter

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89377]
Refs: #85544

- [x] anyOS: @isidorn 

Complexity: 4

---

In this release we've added support for an "inline implementation" of a debug adapter in an extension. For details see #85544. 

Since it would too much work to implement a full debugger in this test item, do the following:

- get the latest version of the "mock debug" repo
- first, verify that the (existing) inline implementation of Mock Debug works correctly. For this set the "runMode" global to "inline" and play with Mock debug. Set a breakpoint in any DAP method of the `MockDebugSession` and verify that a stack shows methods from the extension host (to prove that there is no longer a communication stack between the DA and the extension host).
- second: create a "delegating debug adapter" that can intercept DAP traffic by implementing the new `DebugAdapter` [interface](https://github.com/microsoft/vscode/blob/6c619202b8975765168d436ff21ebc761c276bba/src/vs/vscode.d.ts#L9667). With the resulting `DelegatingAdapter` it should be possible to write this:
  ```ts
  class InlineDebugAdapterFactory implements vscode.DebugAdapterDescriptorFactory {

	createDebugAdapterDescriptor(_session: vscode.DebugSession): ProviderResult<vscode.DebugAdapterDescriptor> {
		return new vscode.DebugAdapterInlineImplementation(new DelegatingAdapter(new MockDebugSession()));
	}
  }
  ```
  Intercept the "step" command and log some message to the debug console.

**Comment by isidorn** [comment]
Works as expected! Looks good.
