### ISSUE TITLE
Unicode support in terminal

### ISSUE THREAD

**Issue by MrRiVoS** [microsoft/vscode#89372]
Issue Type: <b>Feature Request</b>

Hey guys, do you have any plans on adding unicode (UTF-X) support in VSCode terminal? It would facilitate the displaying of some words with graphic signs. Thanks!

VS Code version: Code - Insiders 1.42.0-insider (35116fa958d6622df1c31b4d84810b999a858170, 2020-01-27T18:00:58.077Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-957.27.2.el7.x86_64

**Comment by Tyriar** [comment]
UTF-8 is supported and encourages, is your $LANG variable set correctly? What makes you say it doesn't work?

**Comment by MrRiVoS** [comment]
Hi Tyriar.
I'm from Brazil. The $LANG variable is set correctly (pt_BR.UTF-8).
I've checked and UTF-8 is actually supported. I'm sorry for the mistake.
Let me explain better: I use the "screen" command to avoid having many windows opened. So when I use "special" Portuguese characters, like ã and ç, inside the "screen" command, they appear wrongly. But when I use them outside the "screen", they appear correctly.
This doesn't happen when I use the terminal from Bitvise ssh client.
So now I'm not sure if the problem is with VSCode, or my "screen".

**Comment by Tyriar** [comment]
It sounds like the problem is with screen if they appear normally in your regular shell. Maybe it's not picking up or supporting the encoding correctly?
