### ISSUE TITLE
Outline default behavior and config

### ISSUE THREAD

**Issue by noraj** [microsoft/vscode#89378]
When working with **markdown** documents the outline is basically a ToC (Table of Content).

![image](https://user-images.githubusercontent.com/16578570/73216114-a71de000-4155-11ea-8501-f451086671f2.png)

By default:

- it is sorted by category (with programming in mind)
- it is all expended

For a ToC specifically you  want to:

- sort by position by default, so maybe a way to configure the outline by default differently depending of he file extension, eg. different default behavior is the source file is a java file or markdown file
- Be able to filter the outline depth, eg. expend from h1 to h3 and collapse h4 to h6

For programming languages:

- collapsed view by default: https://github.com/microsoft/vscode/issues/53262 (yeah there is the button and a keyboard shortcut but this is manual)

All of that is possible manually but here we are talking about modifying default behavior or/and adding config possibilities.

**Comment by jrieken** [comment]
Assigning to @mjbvz to consider MD specific defaults

**Comment by mjbvz** [comment]
@jrieken Is there a user facing setting to control the default sort order for the outline view? I see one for the breadcrumbs but not the outline view

**Comment by mjbvz** [comment]
@jrieken Adding you back to this issue because I don't think the outline view gives an extension enough control to implement these

**Comment by jrieken** [comment]
True, only breadcrumbs has this. For outline this is already tracked in https://github.com/microsoft/vscode/issues/52202
