### ISSUE TITLE
Ctrl + Home/End in Explorer Panel

### ISSUE THREAD

**Issue by SirIntruder** [microsoft/vscode#89379]
In particularly large projects, I often find myself wanting to quickly scroll to the top of the folder hierarchy, and I expect `Ctrl+Home/End` to scroll to the begging/end, as they do in editor tabs / terminal.

Makes a lot of sense to propagate this behaviour to other side-panel tree views (git file changes, outlines, etc.)

**Comment by joaomoreno** [comment]
Simply `End` does the trick.
