### ISSUE TITLE
Test: wrapping using the DOM

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#89389]
Test for #2654

- [x] Any @kieferrm
- [x] Any @sana-ajani

Complexity: 3

There is a new setting, `editor.wrappingAlgorithm` that can be configured to `dom` (as opposed to the default `monospace`), in which case the editor will delegate wrapping points computation to the DOM. This will be slow/laggy for large files. 

Please check that using `"editor.wrappingAlgorithm": "dom"`:
* characters outside Latin / emojis wrap better now when using a monospace font
* using non-monospace fonts leads to correct wrapping
* changing the wrapping algorithm will rerun the wrapping points computation
* please also try some RTL text as well
* please also leave any feedback about the setting name / setting value / setting description if you have ideas.

Thank you!

**Comment by qaqz111** [comment]
The word wrapping just totally stop working under `"editor.wrappingAlgorithm": "dom"`:

> The font family **Simsun**'s space chararacter is recogonized as fullwidth which should be halfwidth, this leads to the wrong wrapping point at `Couri[e]r`. Vscode stable 1.41.1 also got this issue.
![1](https://user-images.githubusercontent.com/3367034/73303252-0dd3f400-4251-11ea-98d7-6ace419dfb67.png)

> After turn on `dom` option, line7 and line8 just stop wrapping while line3 is still wrapping with above issue.
![2](https://user-images.githubusercontent.com/3367034/73303647-cd28aa80-4251-11ea-915c-ba31981a507f.png)

> As a contrast, the above issues are all gone while font family set to **Consolas**:
![3](https://user-images.githubusercontent.com/3367034/73303985-6061e000-4252-11ea-8fe0-f5568153c800.png)

> But wrapping still not work for line7 and line8:
![4](https://user-images.githubusercontent.com/3367034/73304062-7ec7db80-4252-11ea-9850-924de79a909a.png)

settings.json
`{
    //"editor.wrappingAlgorithm": "dom",
    "editor.fontFamily": "Simsun, Consolas, 'Courier New', monospace",
//12345678
    "editor.fontSize": 20
}
//12345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678123456781234567812345678
//“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’“”‘’123456781234567812345678`

**Comment by alexdima** [comment]
@qaqz111 This now works correctly for me after the changes for https://github.com/microsoft/vscode/issues/89571

![image](https://user-images.githubusercontent.com/5047891/73533012-27766680-441e-11ea-8b09-19d58d014605.png)

Please open a new issue if you observe something is off. Thank you!
