### ISSUE TITLE
Test: refactoring documentation contribution point proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#89388]
Test for #86788

- [x] Any @jrieken
- [x] Any @joaomoreno

Complexity: 4

**background**
The proposed  `documentation.refactoring` contribution point allows extensions to contribute a command that lets users learn more about refactoring

```json
  "contributes": {
    "documentation": {
      "refactoring": [
        {
          "title": "%documentation.refactoring.title%",
          "when": "typescript.isManagedFile",
          "command": "_typescript.learnMoreAboutRefactorings"
        }
      ]
    }
```

This is rendered at the bottom of the completion list

![](https://user-images.githubusercontent.com/12821956/71938029-04300280-3163-11ea-8305-8691b3cb9d52.png)

**Testing**
Using the [code action sample extension](https://github.com/microsoft/vscode-extension-samples/tree/master/code-actions-sample), try using creating some `documentation.refactoring` contributions:

- Can you get the contribution to show up as expected?
- Does the when clause work?
- Make sure that the documentation only shows up when you would expect:
    - It should only show in the lightbulb menu if a refactoring is returned
    - It should always show up in the refactor menu
    - But it should never block [keybindings for code actions](https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions)

**Comment by joaomoreno** [comment]
I feel it's rather weird that a `when` clause is necessary. Usually `when` clauses are optional. Wouldn't a language selector be more appropriate?

**Comment by joaomoreno** [comment]
I'm not really sure what _But it should never block keybindings for code actions_ means.
