### ISSUE TITLE
Test: Moving views between the sidebar and panel

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#89384]
Refs: #85164

- [x] macOS @JacksonKearl
- [x] linux @aeschli
- [x] windows @Tyriar

Complexity: 4

Authors: @sbatten, @sandy081, @isidorn

---

## What's new

This milestone, we have made progress on the ability to move individual views between the sidebar and the panel. Currently, you can access this functionality by right clicking the header of the view you want to move and selecting `Move to (Panel|Sidebar)`. This is enabled for the following views: `Outline`, `Search`, and `Custom Views`. As a refresher, custom views are those contributed by extensions.

## Current Limitations

Today, this only works with the above mentioned views. Further, unlike the sidebar, the panel can only house one view at a time. Therefore, when you move a view to the panel, it will get its own panel even if another view that it was grouped with in the sidebar is also now present in the panel. Additionally, when you move the view back to the sidebar, it will return to its original position. It cannot be moved to its own new viewlet in the sidebar if it didn't start that way.

## What about the search location setting?

The old `search.location` setting is now deprecated with the new functionality. What happens now is that we read if you have the old setting on startup, adopt the new infrastructure and delete your setting. You should verify this by adding the setting back manually with `"search.location": "panel"` and reloading the window.

## How to Verify

There is no flag to disable this ability, it is simply opt-in via the context menu for individual views. Here are some things to test:

1) Verify that `Outline`, `Search` and your installed extensions have the context menu entry to move.
2) Try moving views around into different configurations.
3) Ensure views persist their positions across reload and restarts.
4) Try working in multiple windows and verify that the views move in all windows.
5) Try moving an extension view and uninstalling that extension. Do not expect the position to be remembered after re-install, just test that we don't break on reload or restart.
6) Test search setting migration.
7) Use `Search`, `Outline`, and some extension views in the panel for some time. Note if anything breaks.

The complexity of this test item comes through long term usage. Please selfhost with some views in the panel for a day or so, perhaps, while testing other items.

**Comment by ArturoDent** [comment]
I noticed that moving a collapsed Outline view to either the panel or sidebar will expand all items within it upon the move.  So "Collapse All" then "Move to Panel/Sidebar" automatically expands all.

**Comment by Tyriar** [comment]
@ArturoDent please create an issue, it might be as designed as the view gets destroyed but it's worth a discussion about.
