### ISSUE TITLE
Test: Call hierarchy support for JavaScript and TypeScript

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#89386]
Test for #88311

- [x] Any @jrieken 
- [x] Windows @gregvanl

Complexity: 3

**Background**
TS 3.8 adds call hierarchy support for JavaScript and TypeScript

**Testing**
Using typescript 3.8+ in your workspace, test using the call hierarchy UX to explore a JavaScript and TypeScript code base. Some things to check:

* Are any calls missed?
* Are any of the linked to locations incorrect?
* Is the displayed information correct?
* Test edge cases such as recursive functions.

**Comment by jrieken** [comment]
I have encountered some severe flaws that really confused me when using call hierarchy...

**Comment by gregvanl** [comment]
Removing @btholt as got coverage from @jrieken
