### ISSUE TITLE
js-debug smoke test

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89393]
Another iteration, another js-debug sanity check! If you were on last month's https://github.com/microsoft/vscode/issues/85984 and the tool assigns you, feel free to swap with someone else for fresh 👀  Please file issues on the js-debug repo: [click to file](https://github.com/microsoft/vscode-js-debug/issues/new)

- [x] anyOS @chrmarti 
- [x] anyOS @alexr00

Complexity: 4

---

### Prerequisite

 - Install the latest `js-debug-nightly` extension from the marketplace.
 - Be on Insiders, of course :)

### Node.js testing

 - Pick any Node.js project you have configured for debugging with VS Code
 - Prefix its launch config type with `pwa-`
 - Verify that you can *launch* the program and debug as usual:
    - The program launches
    - You can set breakpoints before and while the program is running, and they get hit
    - You can step into, out of functions.
    - Stack traces etc. display correctly.
    - Restarting the program works
    - Stopping the program works
 - Verify that you can *attach* to this Node.js process running in debug mode, and debug as usual.

### Chrome testing

 - Pick any browser/Chrome project you have configured for debugging with VS Code
 - Prefix its launch config type with `pwa-`
 - Verify that you can *launch* the project and debug as usual:
    - The browser launches and opens your project
    - You can set breakpoints before and while the program is running, and they get hit
    - You can step into, out of functions.
    - Stack traces etc. display correctly.
    - Restarting the program should refresh the page
    - Stopping the program should close the browser
 - Verify that you can *attach* to a running browser with your project open.
    - Note that you need to launch Chrome with special flags for this, on my machine: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=/tmp/chrome-debug`

### Extension Host testing

 - Pick any extension you have configured for debugging with VS Code
 - Prefix its launch config type with `pwa-`
 - Verify that you can launch the extension and debug as usual:
    - The extension host launches with your extension
    - You can set breakpoints before and while the program is running, and they get hit
    - You can step into, out of functions.
    - Stack traces etc. display correctly.
    - Restarting the extension reloads the extension host window
    - Stopping the program closes the extension host window

**Comment by sandy081** [comment]
@connor4312 You need to assign to the milestone to include it in testing. I assume you want this to be tested and hence assigning to current milestone.

**Comment by alexr00** [comment]
I couldn't test `chrome` launch configurations because of https://github.com/microsoft/vscode/issues/89439

**Comment by chrmarti** [comment]
Testing extension host debugging was limited by https://github.com/microsoft/vscode-js-debug/issues/273.

**Comment by connor4312** [comment]
Thank you for the issues! 😄
