### ISSUE TITLE
Better highlight of the workspace TypeScript vs the builtin one

### ISSUE THREAD

**Issue by arcanis** [microsoft/vscode#89391]
Many of our engineers are accidentally using the builtin TypeScript engine instead of our local one (we cannot update due to an assertion fail bug in TypeScript our code happens to trigger). We have the workspace TypeScript explicitly setup (using `typescript.tsdk`), but it's very easy to miss and as a result they don't get the proper type errors compared to the CI (they also don't get the proper file resolution but that's another story).

Could it be possible to highlight when users aren't using the local TypeScript engine if explicitly set inside the workspace configuration? For example by adding a warning / error badge at the bottom of the screen or better yet on the first line of the file?

**Comment by mjbvz** [comment]
In most cases using a different TS version for tooling does not cause problems  so I'm not in favor of making this an error (especially as the default behavior)

I believe that #65546 would cover what you are after
