### ISSUE TITLE
Test: Search Editor

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89396]
- [x] anyOS @bpasero 
- [x] anyOS @stevencl

Complexity: 3

**Background**
This iteration we are shipping an upgraded Search Editor experience. It is a preview feature, guarded by the `search.enableSearchEditorPreview` flag, which is enabled by default in Insiders, and disabled by default in Stable.

The goal of the search editor is to allow for both:
a) Viewing search results as you would view the actual code: full width, syntax highlighted, with surrounding lines of context.
b) Persisting a query and its set of search results to disk to be tracked over time and/or shared with a team.

**Testing**
- There are two paths to enter the Search Editor experience:
  - Seeded from an existing viewlet/panel search:
    - There should be an "Open in editor" link in the viewlet/panel of any search that has results. (Also command `Search: Open Results in Editor`/`(ctrl/cmd + enter)`)
    - Clicking this should open up a new search editor with all the query properties carried over (regex, includes, etc.). 
    - All results should also be carried over, and any results you have dismissed in the viewlet/panel shouldn't appear in the editor. From that point onward the search editor behaves as if you had entered the query manually, in the `starting fresh` flow:
  - Starting fresh:
    - A new Search Editor can be created from either the `Open new Search Editor` action in the search viewlet/panel, or the `Search: Open new Search Editor` command. This is initalized to be an empty search editor.

- In the Search Editor, test:
  - General searching/query editing
  - Keybindings: focus next input, toggle regex/whole word/case sensitive, toggle context lines
  - Going to definition, either via keybindings for `Go to Definition`/`Open definition to Side`, or clicking with `search.searchEditorPreview.doubleClickBehaviour` set to `openLocationToSide`, `goToLocation`, or `selectWord`. 
  - Editing:
    - The result buffer should be editable, so as to allow item removal. Edits aren't expected to modify source locations. 
    - Editing the buffer will cause dirty indicators to show as expected
    - Reloading a window with dirty Search Editors will keep the contents (hot exit)
  - Saving:
    - The results should be able to be saved and opened back in the Search Editor. 
    - The save prompt should give a decent file name and location, with `.code-search` extension.

Tangentially:
In settings, the syntax:
```json
"[search-result]": {
    "editor.lineNumbers": "off"
}
```
should be initially populated as above, and further allow customizing the search result editor. (minimap, rulers, etc.)

**Comment by sandy081** [comment]
@JacksonKearl It does not adhere to the template. Fixing it.

**Comment by bpasero** [comment]
Great experience overall 👍
