### ISSUE TITLE
Test: Settings sync authentication

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#89394]
Testing [https://github.com/microsoft/vscode/issues/84332)

- [x] windows @fiveisprime
- [x] mac @bowdenk7
- [x] linux @joaomoreno

Complexity: 3

---

## Set Up

- Follow instructions [here](https://github.com/microsoft/vscode-settings-sync-server#self-hosting)

## Testing

- Ensure you can sign in with both a microsoft and a personal account, such as outlook.com
- When you reload, you are not prompted to sign in again
- The command `Sync: Sign out` works as expected
- The "Account" output channel logs info about the sign in process

**Comment by joaomoreno** [comment]
All good!

**Comment by fiveisprime** [comment]
- [x] Ensure you can sign in with both a microsoft and a personal account, such as outlook.com
- [x] When you reload, you are not prompted to sign in again
- [x] The command Sync: Sign out works as expected
- [x] The "Account" output channel logs info about the sign in process

✔️

**Comment by bowdenk7** [comment]
buttery smooth!
