### ISSUE TITLE
Fix/improve the existing explorer.sortOrder options

### ISSUE THREAD

**Issue by jeff-hykin** [microsoft/vscode#89399]
## Why is this a problem (pseudo-bug)
Sorting files by both `filesFirst` and `modified` (timeModified) is certainly possible, but VS Code treats them as mutually exclusive. It seems very strange to me to include a `mixed` option,  and `modified` and option, but not a `mixed--modified` option.

For example, here's what the current VS Code options could more aptly be named:
`filesFirst--alphabetically`
`mixed--alphabetically`
`foldersFirst--alphabetically`
`foldersFirst--timeModified`
`foldersFirst--type`
But for obvious reasons switching to a naming scheme like that would quite a bit less than ideal.

## A Backwards Compatible, Future-Proofed, ~20-line API Proposal

I'd like to propose that `explorer.sortOrder` optionally accept an array of sort methods.
`explorer.sortOrder: SortMethod | SortMethod[]`
```
enum SortMethod {
    filesFirst   = "filesFirst",
    mixed        = "mixed",
    default      = "default",
    modified     = "modified",
    type         = "type",

    // additional options (see below for justification)
    foldersFirst = "foldersFirst",
    alphabetical = "alphabetical", 
}
```

## Behavior and Examples
```jsonc
{
    "explorer.sortOrder": [ "type" ]   // no different than "explorer.sortOrder": "type"
}
```
```jsonc
{
    "explorer.sortOrder": [ "type", "alphabetical"  ]
     // files primarily sorted by type
     // files with the same type are then sorted alphabetically
}
```
```jsonc
{
    "explorer.sortOrder": [  "filesFirst", "type", "modified"  ]
     // files primarily sorted with files at top
     // files and folders are sorted by extension name
     // files with the same extension name are then sorted by timeModified
}
```
## Example Implementation

Thanks to a handy sorting trick, applying the sort methods in reverse order creates the desired hierarchy. Ex: `sortBy("alphabetical"); sortBy("type")` will sort everything primarily by type, with files of the same type already being sorted in alphabetical order. Since code is more explicit than words, here is a javascript implementation.

```js
// import explorer.sortOrder
// import sortMethods // ex: sortMethods.alphabetical, sortMethods.modified, sortMethods.filesFirst

function sort(filesAndFolders) {
    let filesAndFoldersCopy = [...filesAndFolders]
    
    if (typeof explorer.sortOrder === "string") {
        // [ current behavior]
    } else if (explorer.sortOrder instanceof Array) {
        // perform each sortMethod, but in last-method-first order
        // (which produces the intended/expected behavior)
        const sortOrder = ([ ... explorer.sortOrder ]).reverse()
        for (const eachSortMethod of sortOrder) {
            filesAndFoldersCopy.sort(sortMethods[eachSortMethod])
        }
    } else {
        // error invalid type 
    }
    
    return filesAndFoldersCopy
}


```
Any change to the file hierarchy (new, renamed, copied, modified) would perform a re-sort.

## Why this is ideal
- The API change is about as minimal as an API change can possibly be
- The naming will still make sense (arguably will make more sense after the change)
- The additional codebase complexity is minimal and modular
- Makes space for future functionality such as `timeCreated` or descending/ascending sorts
- It allows the user to make the choice for a desirable customization at the cost of some performance (many of us have plenty of performance to spare)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/27286

**Comment by jeff-hykin** [comment]
Thank you! Sorry I didn't see that issue
