### ISSUE TITLE
Support to search for non file editors in quick open

### ISSUE THREAD

**Issue by benjaminRomano** [Microsoft/vscode#894]
**Here are the suggestions given when you press ctrl+p**
![image](https://cloud.githubusercontent.com/assets/9221137/11519488/4ab3d15a-9860-11e5-9d05-96583934c4f3.png)

**Here are the suggestions once you start typing Debug**
![image](https://cloud.githubusercontent.com/assets/9221137/11519502/756d6258-9860-11e5-9d30-5e15f1785403.png)

As you can the suggestion for the Debug Console goes away once you start typing for it.

**Comment by bpasero** [comment]
Right, I think in the editor history once you type we ignore anything that does not seem to be a file.

**Comment by bpasero** [comment]
Closing, you can search for these editors in the new "Show All Editors" picker.
