### ISSUE TITLE
VS Code's Internal use of CSS variables

### ISSUE THREAD

**Issue by jeff-hykin** [microsoft/vscode#89400]
Just to be clear (since the bot tagged this as `themes`): This issue is **not** about accessing/changing/exposing CSS from/to a theme. 

This issue is related/inspired by the much older 2016 issue: https://github.com/microsoft/vscode/issues/8151

## TLDR: can VS Code start using CSS variables in their codebase?
It appears the possibility was partially discussed in 2016 https://github.com/microsoft/vscode/issues/8151. It seems like the change would improve the quality of the codebase and make the system more generally obvious to outsider how pieces of VS Code fit together.

## Why this would be helpful
When creating a theme, sometimes it is unclear why a particular element is a particular color. I personally had a bug with an off-gray color and, with no good way to discover the source, had to spend hours changing every gray-looking color to purple, recompiling, and visually checking to see if I had finally found the source of the undesirable problem. I even tried creative solutions such as screenshots using the color-picker drop and then reverse searching the color's hex value to try to get to it faster. Intuitive naming conventions can only go so far. 

`Inspect TM scopes` solves this kind of issue for code colors by explaining exactly why something is a particular color, but there doesn't appear to be a similar tool for regular theme colors. Being able to use inspect element, see the name of the CSS variable that is being used, and then know what to change/add to a theme file would be incredibly helpful.

**Comment by aeschli** [comment]
The request for a color inspect tool is #62637 

Using css variables is a good idea.
We'd still need a solution for the cases where colors are directly set to the DOM nodes.

Marking this as dup of #62637.

**Comment by jeff-hykin** [comment]
What would make colors being set directly set to the DOM nodes different?

Maybe I don't understand the codebase well enough, but it seems colors are static outside of major events like a theme being loaded. In theory every color would have it's own css variable generated on pageload and the elements would receive an enum-ed CSS variable name instead of a color. 

Instead of `<div style="color: ${this.color}">`,  `<div style="color: var(${this.cssColorVar})">`

**Comment by aeschli** [comment]
Oh, I see, didn't think of that!
