### ISSUE TITLE
Web: download from explorer via blobs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89407]
Workaround for: https://github.com/MicrosoftDocs/vsonline/issues/new

**Comment by bpasero** [comment]
**Verification:** 
* run vscode for web (out of sources is fine)
* right-click on files in the explorer (1 or many)
* pick download
* verify the files download properly

**Comment by gjsjohnmurray** [comment]
> Workaround for: https://github.com/MicrosoftDocs/vsonline/issues/new

Bad link?
