### ISSUE TITLE
file save error on sdcard

### ISSUE THREAD

**Issue by mywisdomfly** [microsoft/vscode#89409]
Issue Type: <b>Bug</b>

I am craying.
I save my code. But when I reopen the code it is empty.
I save it on my sdcard. It happened twice.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.39GB free)|
|Process Argv|D:\NEU-ROBOT-Courses\微机原理\README.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
include-autocomplete|ajs|0.0.4
msg|ajs|0.1.1
ros|ajs|0.3.1
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
latex-workshop|Jam|8.6.0
vscode-cudacpp|kri|0.1.1
vscode-language-pack-zh-hans|MS-|1.41.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.58038
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.7
vscode-remote-extensionpack|ms-|0.19.0
cpptools|ms-|0.26.3
vscode-yaml|red|0.6.1
vscode-leetcode|she|0.16.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.4
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
SD Cards are not meant for storage, it's well known that you shouldn't use them for high file activity, I suggest to stay away from them. You'll hit issues with any tool, this isn't a VS Code issue.
