### ISSUE TITLE
Integrated terminal does not gets cleared when using bash

### ISSUE THREAD

**Issue by renanoliver** [Microsoft/vscode#8940]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.Set bash as integrated terminal
2.Try to clear the terminal using 'clear' command

**Comment by Tyriar** [comment]
What happens when `clear` is run? Command not found? Command accepted but nothing happens?

**Comment by renanoliver** [comment]
@Tyriar The command is accepted and the cursor moves to the top of the terminal, but it doesn't gets cleared, and every character typed overdraws the next character that wasn't cleared. Did you understand?

**Comment by Tyriar** [comment]
@renanoliver are you seeing this? https://github.com/sourcelair/xterm.js/issues/106

**Comment by renanoliver** [comment]
@Tyriar No... the `clear` command just moves the cursor to the top, but it doesn't clear the terminal.

**Comment by Tyriar** [comment]
Marking this as upstream as I'm guessing it's either Ubuntu Bash or winpty's fault.

**Comment by renanoliver** [comment]
@Tyriar With the new update(v1.3.1) this issue seems to be resolved. So, I'm closing this.
