### ISSUE TITLE
Long running extensions seem to be canceled with no result

### ISSUE THREAD

**Issue by robby** [microsoft/vscode#89401]
Issue Type: <b>Bug</b>

While executing an extension command on a large file, no progress is displayed and at times the operation is canceled.

• Load file with many lines, in my case over 500k, total file size 18mb
• Attempt to run extension to remove duplicates, Permute: Unique or Unique lines
• Notice nothing seems to happen

Alternatively, the same process works in Sublime within 2-5 seconds and shows a spinner while processing.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
uniquelines|cor|0.0.3
permute-lines|ear|1.1.0
vscode-solution-explorer|fer|0.3.7
vscode-exec-node|mir|0.5.1
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.0.9
mssql|ms-|1.8.0
csharp|ms-|1.21.9
java|red|0.55.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.6.1
append-comma|vco|0.0.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.20.2

</details>

**Comment by alexdima** [comment]
@robby Please create an issue directly against the `permute-lines` extension at https://github.com/earshinov/vscode-permute-lines .
