### ISSUE TITLE
LiveShare: error on guest about files.hotExit not applicable as workspace setting

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89404]
Steps to Reproduce:

1. use insiders
2. install LiveShare
3. host a session
4. join from another insiders run (via user-data-dir trick)

=> 🐛 notice this error right on startup

![Screenshot 2020-01-28 at 09 18 28](https://user-images.githubusercontent.com/900690/73246738-a5810600-41af-11ea-8628-c95f93d6ed9b.png)

I cannot reproduce in Code stable, so I suspect a regression with our configuration API.

**Comment by sandy081** [comment]
`files.hotExit` is an application setting and we never supported writing an application setting into workspace. Please check if something has changed with the live share extension.

**Comment by bpasero** [comment]
@sandy081 

> Please check if something has changed with the live share extension

Since I tried to reproduce with stable where it does not reproduce, I do not think it is their code to blame (unless they install a different version to insiders compared to stable?).

Maybe @IlyaBiryukov can chime in

**Comment by sandy081** [comment]
Let me also check from the extension's code perspective if there is any change.

**Comment by sandy081** [comment]
It looks like error is always thrown but not surfaced in UI. Change is that the error is not surfaced in UI which should not be.

**Comment by IlyaBiryukov** [comment]
Live Share sets 'files.hotExit' as a workspace setting. It has been doing this for quite some time. I guess we need to remove it because, as you said, it doesn't work on a workspace level.

**Comment by bpasero** [comment]
@IlyaBiryukov I guess this was done partially due to issues outlined in https://github.com/microsoft/vscode/issues/53257. At least for readonly sessions, this should no longer be an issue anymore given readonly files no longer mark as dirty in the guest.
