### ISSUE TITLE
Cannot edit markdown in jupyter notebook

### ISSUE THREAD

**Issue by Ikru488** [microsoft/vscode#89403]
Issue Type: <b>Bug</b>

Open/make a jupyter notebook. Put code in the first cell. Then try to add markdown in the cell above this one. It will not get saved.
Also try editing markdown after moving on to the next cell. Changes made to the text don't appear.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz (24 x 3458)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|47.98GB (27.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gc-excelviewer|Gra|2.1.32
python|ms-|2020.1.58038

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rebornix** [comment]
Please file issues against the extension which provides the notebook features. Currently we don't have notebook support in the core.
