### ISSUE TITLE
Missing decoration on alternative completion acception

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#89413]
Testing #89344

When having a completion item provider that gives a very simple result, e.g.:
```
        provideCompletionItems: (doc, pos) => {
            const result = new vscode.CompletionItem('hello');
            return [result];
        }
```

I would expect that pressing and holding Shift (in preparation for Shift+Enter) would highlight something differently to indicate that the completion will be inserted with replace semantics.

**Comment by jrieken** [comment]
Oh, wait... That's actually controlled by the `editor.suggest.insertHighlight` setting and that's off by default. Unsure if we should flip the default? thoughts?

**Comment by alexdima** [comment]
I think it's risky to flip the default in the endgame... Maybe we can try to flip it in debt week?
