### ISSUE TITLE
Renaming folder doesnt work

### ISSUE THREAD

**Issue by arthurspa** [microsoft/vscode#89411]
Issue Type: <b>Bug</b>

1. From VS Code explorer, copy and paste an existing folder with children contents
2. try to rename the folder

Expected: folder should be renamed
Result: folder doesn't get renamed

Note 1: after re-opening VS Code and trying to rename  it works.
Note 2: I have a large repository

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
ng-template|Ang|0.900.7
code-gnu-global|aus|0.2.2
gitlens|eam|10.2.0
todo-tree|Gru|0.0.166
vscode-jasmine-test-adapter|hbe|1.6.2
vscode-test-explorer|hbe|2.15.0
docthis|joe|0.7.1
Angular2|joh|8.3.0
code-beautifier|mic|2.3.3
python|ms-|2020.1.58038
cmake-tools|ms-|1.2.3
cpptools|ms-|0.26.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
angular-karma-test-explorer|raa|1.2.4
java|red|0.55.1
vscode-xml|red|0.10.1
code-spell-checker|str|1.7.22
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.20.2
JasmineSnippets|xab|1.0.1
markdown-pdf|yza|1.4.1

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by goleary** [comment]
I'm unable to rename folders that only have 1 child (pages folder below).
![image](https://user-images.githubusercontent.com/16123225/73964952-161ed580-48c8-11ea-9b5d-ef344dfae904.png)

When I click on `pages` it behaves like I can rename, and I even type a new name in, but it doesn't stick.

**Comment by isidorn** [comment]
This works just fine for me. What are you doing differently and are you using VS Code insiders as I asked in my previous comment

![hello](https://user-images.githubusercontent.com/1926584/74019692-551c5c00-4998-11ea-98f5-08b11c60b3bc.gif)

**Comment by goleary** [comment]
seems to have been a transient error, I can no longer repro.

**Comment by isidorn** [comment]
Then closing until we find nice reproducable steps. Thanks
