### ISSUE TITLE
Render whitespace character for untitled file names

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89417]
re https://github.com/microsoft/vscode/issues/89274

<img width="1192" alt="Screenshot 2020-01-28 at 11 02 59" src="https://user-images.githubusercontent.com/1794099/73253980-d5cfa100-41bd-11ea-9233-bf0a8e99bc2f.png">

* create a new file
* paste `the                                           quick brown fox`
* 🧀 the filename looks a little weird, esp in the open editors view and inside quick pick. it might be better to render whitespace characters in that case

**Comment by bpasero** [comment]
Yeah maybe, not sure. Alternatively, why not simply collapse all whitespace into one, like HTML?
