### ISSUE TITLE
Windows: Window crashes when trying to forward two ports to the same local port

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89419]
#89336

On Windows:
- Try to forward two ports to the same local port.
- Window immediately crashes.

**Comment by chrmarti** [comment]
This is when changing the port of the second forwarded port to the port of the first.

Adding two forwarded ports with the + action results in:
![image](https://user-images.githubusercontent.com/9205389/73255865-39a79900-41c1-11ea-8807-37eeb7eb323e.png)

**Comment by alexr00** [comment]
Fixed the crash, added a message for why you don't get the port you asked for, and changed the error to a warn so that it doesn't show in the console.
