### ISSUE TITLE
Updated to  1.30 now I get the error - Cannot launch debug target (spawn node ENOENT).

### ISSUE THREAD

**Issue by mmaio** [Microsoft/vscode#8941]
- VSCode Version: 1.30
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Open a node.js project - by starting VSCode from the Dock vs the Terminal
2. Configure launch.json
3. Start the debugger
4. You will receive Updated to  1.30 now I get the error - Cannot launch debug target (spawn node ENOENT).

The prior version worked fine and this started right after Visual Studio Code updated.  If I rollback to the 1.2.1 version everything operates correctly

**Comment by JonathanMEdwards** [comment]
After upgrading to 1.3 all my tasks fail with:
env: node: No such file or directory

Some sort of PATH problem?

**Comment by wallverb** [comment]
See if it's similar to: https://github.com/Microsoft/vscode/issues/8434 - I wish they fixed it before shipping 1.3.0

**Comment by mmaio** [comment]
Node is in my path so I don't think it is path issue.  If it was a path issue rolling back to the prior version should yield the same result.

**Comment by wallverb** [comment]
Yea, but if your shell outputs something more than usual then it will not work in 1.3.0 (worked in 1.2.0 though).

Try to run `$SHELL -ilc whoami` in your terminal and see if you just get your username or something more. If just username - then it's different issue

**Comment by mmaio** [comment]
@wallverb - I just get my username

**Comment by wallverb** [comment]
Ok - then it's different issue then - try to start vscode from terminal with `code` command - then it should pick up your PATH properly

**Comment by mmaio** [comment]
@wallverb - starting from terminal worked!

**Comment by mmaio** [comment]
@wallverb - I altered my .bash_profile  and removed my comment, In DEV mode. Using location cntlm. http proxy env variables set to http://localhost:3128, and it works from the dock.  Thanks... this really should be fixed

**Comment by joaomoreno** [comment]
Should be #8434
