### ISSUE TITLE
Forwarded Ports: Indication on which ports are currently being listened on

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89424]
#89336

It would also help if there was an indication on which ports are currently being listened on and which aren't. That could help with not forwarded and forwarded ports. Will open a new issue for this.

_Originally posted by @chrmarti in https://github.com/microsoft/vscode/issues/89421#issuecomment-579177560_

**Comment by alexr00** [comment]
What it looks like now:
![keepProcInfo](https://user-images.githubusercontent.com/38270282/73663746-6fa3bc00-469e-11ea-91f3-0e190ab1c098.gif)

**Comment by alexr00** [comment]
To verify, connect to a remote and start a process that listens on a port (ex. npx http-server -p 5006).
Refresh the forwarded ports view
Forward the port that your process is listening on.
Forward some other ports.
Verify that you can tell which forwarded port is the one that your process was listening on.
