### ISSUE TITLE
Shift+Enter in editor after previewing refactoring applies refactoring

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89422]
Testing https://github.com/microsoft/vscode/issues/89331

1. Run rename preview
2. Focus back into any regular editor
3. Press `Shift+Enter` to insert a new line

Refactoring gets applied! :see_no_evil:

**Comment by jrieken** [comment]
😇

**Comment by jrieken** [comment]
Wait, there is this: https://github.com/microsoft/vscode/blob/b57bae4a85ae569a82c6d79744c74c7f72f437f7/src/vs/workbench/contrib/bulkEdit/browser/bulkEdit.contribution.ts#L171

@sandy081 It that only active and not focused? Does a key exist for focused panel/view?

**Comment by sandy081** [comment]
There is panel focus context key bit not view specific

https://github.com/microsoft/vscode/blob/e641d316761f0f7446bd45d4f5b96a0f6b85e7ea/src/vs/workbench/common/panel.ts#L10

**Comment by jrieken** [comment]
Thanks @sandy081 👏
