### ISSUE TITLE
Broken Linux application launcher

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#8942]
Installing 1.3.0 on a brand new machine:

![image](https://cloud.githubusercontent.com/assets/22350/16689103/a2059696-4521-11e6-943c-ecfde198ae5b.png)

**Comment by Tyriar** [comment]
@joaomoreno did you wait a minute before trying? Sometimes it doesn't happen immediately.

**Comment by joaomoreno** [comment]
After 3 hours:

![image](https://cloud.githubusercontent.com/assets/22350/16693830/5a4ccd68-4537-11e6-9e45-88b9ac880c13.png)

**Comment by Tyriar** [comment]
Hmm, shows up fine for me about 3 seconds after installation after uninstall and reinstall.

![image](https://cloud.githubusercontent.com/assets/2193314/16694629/3077d754-44f0-11e6-9730-0656a5b7cf5a.png)

Can you paste the output of `cat /usr/share/applications/code.desktop` here?

**Comment by Tyriar** [comment]
Removing from candidate due to no customer complaints and I haven't been able to repro throughout all of June.

**Comment by Tyriar** [comment]
Just tested again, still fine. Going to close off.
