### ISSUE TITLE
Untitled: show original resource name as description

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89423]
re https://github.com/microsoft/vscode/issues/89274

* create a new untitled editor without content, it's name is 'Untitled-1'
* create a another untitled editor and type 'Untitled-1'
* ❓ editors can be told apart (albeit this being a artificial case) but I wonder if this also has an effect on the URI they are being assigned?

<img width="987" alt="Screenshot 2020-01-28 at 11 22 08" src="https://user-images.githubusercontent.com/1794099/73255444-6dce8a00-41c0-11ea-8643-6748a45979cf.png">

**Comment by bpasero** [comment]
@jrieken the URI has not changed with this, just the `name` of the untitled file. URIs are still unique and in the form of `untitled://untitled-1` etc.

**Comment by jrieken** [comment]
check. I think we are OK then and don't need a way to differentiate them further. feel free to nuke this issue 💣

**Comment by bpasero** [comment]
Yeah, the only alternative would be to show the actual resource path as description. I think that would make sense in a way but I would only do that if the untitled editor is opened in the same editor group, similar to what we do here:

![image](https://user-images.githubusercontent.com/900690/73258260-9c9b2f00-41c5-11ea-80dc-59468dcbe411.png)

Moving to backlog candidate to see if more users would want this.

**Comment by bpasero** [comment]
**Verification (NOTE: requires build from Thursday):** verify that untitled editors now always show "`Untitled-<N>`" as description label:
* in editor and other places (such as open editors view, search results, problems, pickers)
* NOT if the name label already is `Untitled-<N>` (e.g. when first line is empty)
* NOT if the untitled file has an associated file path (e.g. by starting code from the command line pointing to a file that does not exist)
