### ISSUE TITLE
Forwarded Ports remembers random ports

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89421]
#89336

Some ports are randomly chosen, e.g., when the user's code uses 0 as the port to listen to or when Node.js picks a random port (as is the default with the Node.js debugger extension for VS Code).

Maybe there should be a delete action for these remembered ports?

**Comment by chrmarti** [comment]
It would also help if there was an indication on which ports are currently being listened on and which aren't. That could help with not forwarded and forwarded ports. Will open a new issue for this.

**Comment by alexr00** [comment]
> Maybe there should be a delete action for these remembered ports?

Is the x action not working?

**Comment by chrmarti** [comment]
I don't get the 'x' on remembered ports that are not forwarded yet. 🤔

**Comment by alexr00** [comment]
Those aren't remembered! They are discovered by seeing what's running on your system.

**Comment by chrmarti** [comment]
These were not being listened on at that time I think. Cannot reproduce though in todays Insiders... 🤔
