### ISSUE TITLE
Refactor preview should have `Open Editor` actions 

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89427]
Testing https://github.com/microsoft/vscode/issues/89331

Should we have a `Open Editor` action at the top of the diff editor of a refactor preview?

Also maybe a context menu action `Open Editor` on each file row?

**Comment by jrieken** [comment]
Looking at other parts of VS Code, it seems that we don't do such thing. Neither search, problems, or the explorer have this...

**Comment by joaomoreno** [comment]
Let's close it! :+1:
