### ISSUE TITLE
Low numbered ports cannot be used

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89433]
#89336

On Windows:
- Forward a port to local port 123.
- Open in browser:
![image](https://user-images.githubusercontent.com/9205389/73257839-c7d14e80-41c4-11ea-861f-93563b636b8d.png)

On Mac I noticed that instead a random port will be used, which is unexpected in those cases where the user picked a port manually. Maybe there should be an info dialog telling the user that a different port was chosen in that case?

**Comment by alexr00** [comment]
123 is a valid port to forward to. That error comes from chrome:
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc
We could use the same restriction list though.

**Comment by alexr00** [comment]
\closedWith cd823d88f4b39d5f7f9a232628ad13caa70a9519

**Comment by joyceerhl** [comment]
On mac when I try to forward 123 in a Codespace, I get port 123 running with local address 127.0.0.1:51324--is that expected behavior?

**Comment by alexr00** [comment]
@joyceerhl I can't repro that on Ubuntu. I properly get prompted for sudo then see 127.0.0.1:123 as my local address. Do you have something else running locally on 123 already?
