### ISSUE TITLE
Debian: 1.3.0 is not a successor of 1.2.x

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#8943]
I have 1.2.1 installed. When I download the 1.3.0 package and open it in the ubuntu package manager, it shows me an install button instead of an update button, unlike before:

![screen shot 2016-07-08 at 15 20 22](https://cloud.githubusercontent.com/assets/22350/16688732/ae8d6486-451f-11e6-8667-de37be6e840e.png)

**Comment by joaomoreno** [comment]
Maybe related to #8859

**Comment by Tyriar** [comment]
As designed, the package was renamed `code` which now replaces `visual-studio-code` when installed. This was done as part of the package clean up to align the package name with the command name.

**Comment by joaomoreno** [comment]
Yeah but my system was left behind having two installed packages:

- `code`
- `visual-studio-code`

Any way to inform users of this?

**Comment by Tyriar** [comment]
It's meant to be replaced as per https://github.com/Microsoft/vscode/blob/master/resources/linux/debian/control.template#L10 which worked in all my testing previously. I'll look into it.

**Comment by Tyriar** [comment]
The old packages have been hanging around "installed" on my machine without me realising it. I think some package managers just don't know how to replace properly. I added `Breaks` for good measure as advised in https://wiki.debian.org/Renaming_a_Package, it doesn't make a difference from my testing though.

**Comment by Tyriar** [comment]
Continued discussion in https://github.com/Microsoft/vscode/issues/8876
