### ISSUE TITLE
Search editor: empty editor starts with line 2?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89436]
Refs: #89396

Is that intentional?

![image](https://user-images.githubusercontent.com/900690/73258706-92c5fb80-41c6-11ea-8630-e7b69afdf518.png)

**Comment by bpasero** [comment]
Now it seems to be 3:

![image](https://user-images.githubusercontent.com/900690/73258907-f3553880-41c6-11ea-8cb5-0763636406a1.png)

**Comment by bpasero** [comment]
6!

![image](https://user-images.githubusercontent.com/900690/73268807-e5f67900-41db-11ea-866c-dbe6eea2c322.png)

**Comment by JacksonKearl** [comment]
There's a hidden range at top the editor.. maybe line numbers could be configured to skip hidden ranges? Or discard the header info at disk read and add it back at disk write. But another issue I see here is that line numbers are showing up at all, they shouldn't without explicit configuration. Seems like they reappear on reload: #89584.

**Comment by JacksonKearl** [comment]
Fixed in 708877d8257a27107b841b5411a7add663ddc65c
