### ISSUE TITLE
Visual treatment of label for pickstring option is hard to determine which is the label and which is the value

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#89434]
Issue Type: <b>Bug</b>
Found while testing: https://github.com/microsoft/vscode/issues/89342

Create a pickstring task and add a few labels to some of the values.

Run the task.

Try to tell which are labels and which are values:

![image](https://user-images.githubusercontent.com/1704059/73258093-e29fc500-41bc-11ea-9351-51dbe4674366.png)

Note in the image above that env3 and env4 are values but they are given a different visual treatment to the other values in the list. Note also that the visual treatment of env3 and env4 is very similar (perhaps identical) to the visual treatment for the default label.

VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:38:41.922Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
vscode-github-releases-updater|joa|0.18.0
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
remote-containers|ms-|0.99.2
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
cloudenv-extensions|ms-|1.0.1369
vsonline|ms-|1.0.1507
test-search-rg|rob|0.0.3

</details>

**Comment by alexr00** [comment]
@misolori do you have any ideas on how this could be done within the confines of the quick pick? Maybe we do lable: value?

**Comment by misolori** [comment]
I think it's expected for users to keep the list consistent like:

![image](https://user-images.githubusercontent.com/35271042/73314927-8d2ade80-41e3-11ea-9c23-bf77c445ec62.png)

But I do see that it feels inconsistent that if you don't provide a label that it looks exactly like a label. We can try out `label: value` and I would make the default wrapped in parentheses as that's how we do it for color & file themes:

![image](https://user-images.githubusercontent.com/35271042/73315358-b861fd80-41e4-11ea-9f07-0ab83ff52388.png)

**Comment by alexr00** [comment]
I could also make all entries required to have a label if one does

**Comment by alexr00** [comment]
Actually, I'm now inclined to only show the label and not show the value at all if there is a label. If there's no label, we still show the value.

**Comment by alexr00** [comment]
What it looks like now: 
![image](https://user-images.githubusercontent.com/38270282/73367606-0abc2080-42b0-11ea-9a9d-adcb7660c9d0.png)
