### ISSUE TITLE
Refactor preview ain't behaving "natural"

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89430]
Testing https://github.com/microsoft/vscode/issues/89331

Really not sure why the GIF is in slow motion, just be patient. :laughing: 

![Peek 2020-01-28 11-39](https://user-images.githubusercontent.com/22350/73256711-b6874280-41c2-11ea-99b3-05891c2c2e1e.gif)

**Steps:**

1. Create both files listed below
1. Rename preview `Animal` to `Beast` in file `a.ts`
2. Uncheck both files in the rename preview view
3. Check the single change in `a.ts`
4. Check the entire `b.ts` file

:bug: The single change in `a.ts` gets unchecked

---

**`a.ts`**

```a.ts
export interface Animal {}
```

**`b.ts`**

```b.ts
import { Animal } from "./a";
export class Dog implements Animal {}
```

**Comment by jrieken** [comment]
@joaomoreno That was a simple rename, right?

**Comment by joaomoreno** [comment]
Yeah simple rename, let me get you some steps...

**Comment by joaomoreno** [comment]
Steps are in first post :point_up:

**Comment by jrieken** [comment]
Thanks for clarifying. I can repro in insiders but not in scripts/code.sh. This has been fixed with https://github.com/microsoft/vscode/issues/89500
