### ISSUE TITLE
apply editor mode on paste doesn't work if clipboard contents is confined to plain text

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89444]
Refs: #89274

on macOS I'm using a clipboard utility ["FormatMatch"](https://apps.apple.com/us/app/formatmatch/id445211988?mt=12) that removes any character style formatting from the clipboard contents so that pasting text always results in "plain text".

If this tool is enabled, the new VS Code feature to apply the mode of the source on paste does not work at all.

I don't think that the new feature "has a bug", but
- it would cool if the new feature would work anyway,
- or we should be aware of this limitation otherwise.

**Comment by bpasero** [comment]
@weinand I don't think this tool is doing the right thing, or maybe behaves different than expected. We put all the data for the copy operation into a [`vscode-editor-data`](https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/controller/textAreaInput.ts#L634) data transfer. It seems to me that this tools is probably removing this data and only allows for a standard one?

**Comment by weinand** [comment]
@bpasero yes, the tool might do something dumb but I'm using the tool since 10 years and I can not live without it. But again, I'm not saying that this is a bug on our side and that we can do anything against this. This is just a FYI in case you see issues that the feature is not working. Many macOS users are using this or similar tools...


BTW, copying text between VS Code on macOS and VS Code running in a Parallels VM doesn't apply the mode either even if I turn on the "Preserve text formatting" option:

![2020-01-28_17-18-49](https://user-images.githubusercontent.com/1898161/73282750-6031f800-41f2-11ea-970b-56c0eb1ebfa9.png)

**Comment by bpasero** [comment]
Good point, yeah we should document this. I think these tools:
* remove any data transfer that is not text
* possibly remove any formatting hints inside that text (like HTML)

This means our data transfer that we need for transfering the mode is also lost.
