### ISSUE TITLE
Ordering and naming tasks 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89448]
Testing https://github.com/microsoft/vscode/issues/89343

Currently tasks are shown as below when running command `Tasks: Configure Task` in alphabetical order

![image](https://user-images.githubusercontent.com/10746682/73259775-c86be400-41c8-11ea-9649-6252960587c0.png)

I think following order is better and consistent
- User Tasks
- Workspace Tasks
- Tasks for each Workspace Folder

Also user tasks have `User Settings` as description. It is nothing to do with Settings. So probably calling it just `User` is good enough

**Comment by alexr00** [comment]
The task list is filterable, and your recent tasks always show at the top anyway which means that the grouping by source could be confusing. Sticking with the alphabetical ordering, but changing "User settings" to "User".
