### ISSUE TITLE
Can't navigate to rename terminal button using keyboard in "Switch Active Terminal"

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode#89443]
Steps:

1. Call to command `workbench.action.quickOpenTerm`.
2. Create a terminal
3. Call to command `workbench.action.quickOpenTerm` again
4. Press down arrow
5. Try to go to the `gear` icon using only keyboard.

<img width="722" alt="Screen Shot 2020-01-28 at 13 05 31" src="https://user-images.githubusercontent.com/3723951/73259281-1e905580-41d0-11ea-89f3-830c52250f31.png">

If I remember correctly, it's regression.
 
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```
Also in insider
```
Version: 1.42.0-insider
Commit: c4b6a6b537de49a734d0eedea06152ea37dfdb6a
Date: 2020-01-28T05:34:51.242Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

--------------------
If I may, I liked the option to kill a terminal from this quick menu (next to the gear icon) I'm not sure if it's regression or a feature.

**Comment by moshfeu** [comment]
Thanks you nice bot. It's not..

**Comment by Tyriar** [comment]
This feature in the quick pick appears to have broken recently, you used to be able to tab to it.

**Comment by moshfeu** [comment]
Thanks @Tyriar

**Comment by chrmarti** [comment]
This is QuickOpen, @bpasero are you aware of any changes there? I can't get it to work even with 1.40.2.

**Comment by bpasero** [comment]
@chrmarti since it does not reproduce with quick input, let me take this as part of the adoption.

**Comment by bpasero** [comment]
this works now via https://github.com/microsoft/vscode/commit/33a47d52de5cccb475723fb59b9a806b7c873597

**Comment by moshfeu** [comment]
Thanks! When I could check it (Regular / Insider)?

**Comment by bpasero** [comment]
It will probably need until our March release before quick access will replace quick open. 

In insiders tomorrow you can test via:
* F1
* type quick access and pick it
* type `term `
* see the list of terminals

**Comment by moshfeu** [comment]
Thanks!

**Comment by Tyriar** [comment]
@JacksonKearl the bot should work even if it doesn't find a commit.

**Comment by JacksonKearl** [comment]
@Tyriar https://github.com/microsoft/vscode/issues/93323#issuecomment-606061545

**Comment by moshfeu** [comment]
Does `author-verification-requested` means that I should check if it's working?
It's working as expected in 1.44.0 insider.
There are small issues:

1. There is no indication when the terminal's name gets / looses focus 
2. The icon is not aligned inside the outline

<img width="52" alt="Screen Shot 2020-03-30 at 19 39 59" src="https://user-images.githubusercontent.com/3723951/77938342-437f7280-72be-11ea-963b-e5af57d2569c.png">

**Comment by JacksonKearl** [comment]
@moshfeu 
> Does author-verification-requested means that I should check if it's working?

Yes, normally the bot would leave a comment with further instructions, but this is a new label and we're still working some things out.

Thanks for the follow up! I'll hand off to @bpasero for the other things you mentioned.

**Comment by bpasero** [comment]
@moshfeu if you think you found issues while verifying this one, please open them as new issues. Thanks!
