### ISSUE TITLE
Search editor controls are placed too far away from search text

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#89445]
Issue Type: <b>Bug</b>
Found while testing: https://github.com/microsoft/vscode/issues/89396
Open a search editor
Note that search text is on left but controls are far to the right (at least when the editor takes up full width of editor area):

![image](https://user-images.githubusercontent.com/1704059/73259548-f0a31500-41bf-11ea-8a98-b968ed57ac43.png)

It might be worth considering placing these controls underneath the search text or somewhere else closer to the text. @misolori - what do you think?

VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:38:41.922Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
vscode-github-releases-updater|joa|0.18.0
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
remote-containers|ms-|0.99.2
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
cloudenv-extensions|ms-|1.0.1369
vsonline|ms-|1.0.1507
test-search-rg|rob|0.0.3

</details>

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/73338836-4f9e7380-422c-11ea-9fd0-7b05d9894f64.png)
![image](https://user-images.githubusercontent.com/8586769/73338899-6fce3280-422c-11ea-859d-f2be4681bf39.png)
@misolori thoughts on how this should look? Neither of the above really sell me.

**Comment by misolori** [comment]
I think that this also applies to Search in the panel (cc @roblourens) but I don't think we found a solution that works. 

![image](https://user-images.githubusercontent.com/35271042/73384687-9453fa00-4280-11ea-8d62-16416ba12008.png)

Since we don't have a pattern yet on what that would look like and we want them both to be consistent, I'd wait to bring it up in the UX sync.

**Comment by roblourens** [comment]
We could experiment with putting those buttons on the left sublime-style too. I think we explored that briefly when looking at search UI in the panel, but didn't want it to be **too** different from the UI in the sidebar. But we probably have more room to do things differently in the search editor.

I also think that putting a max width on the controls and centering them is an improvement too.

**Comment by misolori** [comment]
Also, when discussing a max-width we should be consistent with the Settings UI (1000px). Also applies to Keybindings which doesn't have a max-width.

**Comment by misolori** [comment]
This is a quick mockup, here's what it would look like if we left-aligned the search controls after it exceeded a certain width:

![image](https://user-images.githubusercontent.com/35271042/73387055-c8311e80-4284-11ea-9867-3d0bc5250409.png)

**Comment by JacksonKearl** [comment]
Deferring as we don't have a substitute UI and users haven't raised similar concerns.

**Comment by JacksonKearl** [comment]
Sweeping under the rug for housekeeping.

Or maybe it was already swept under the rug and now I'm taking it out to the trash?

Idk.
