### ISSUE TITLE
Bad default color in dark themes if semantic token type is not defined

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#89440]
![capture](https://user-images.githubusercontent.com/1931590/73259285-bd648400-41c7-11ea-863c-9f9e0ae4171c.png)

**Comment by aeschli** [comment]
caused by https://github.com/microsoft/vscode/issues/89600

**Comment by dbaeumer** [comment]
Thanks for fixing. Works nice now.

**Comment by dbaeumer** [comment]
Except one little thing.


![capture](https://user-images.githubusercontent.com/1931590/73437826-583a9b00-434d-11ea-93b2-d6365f576be3.png)

Observe: `provideCompletionItems` is colored in white whereas `resolveCompletionItem` is colored correctly (or better)

**Comment by dbaeumer** [comment]
![capture](https://user-images.githubusercontent.com/1931590/73437964-920ba180-434d-11ea-9839-ceaebe6db49a.png)

**Comment by aeschli** [comment]
No semantic highlighting is involved here. It's a TextMate grammar issue.

**Comment by dbaeumer** [comment]
Created https://github.com/microsoft/vscode/issues/89716 and assigned to you (since more likely to get a fix :-))
