### ISSUE TITLE
User tasks cannot be configured in empty window

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89456]
Testing https://github.com/microsoft/vscode/issues/89343

User tasks cannot be configured in empty window also in empty workspace

**Comment by alexr00** [comment]
This will be impacted by #90087. I'll fix it after the task quick pick improvements are done.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/2720a8022e5f2f22a50ba036eeafd3cc9e7b6a3f
