### ISSUE TITLE
Line highlighting differs

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#8945]
Don't know when this changed, but with the new *Find and replace* line highlighting (https://github.com/Microsoft/vscode/issues/2792) I realize that the normal line highlighting is very different. And somewhat invisible.

Normal line highlighting with **thin, thin** line. (IMO too subtle)
![image](https://cloud.githubusercontent.com/assets/1297882/16689453/544b06dc-4523-11e6-923c-6306accb3319.png)

New *Find and replace* line highlighting. This was the default several versions back.
![image](https://cloud.githubusercontent.com/assets/1297882/16689459/641639e2-4523-11e6-96c3-c85d56c75155.png)

1.4.0-insider
Win10

**Comment by joaomoreno** [comment]
cc @sandy081

**Comment by alexandrudima** [comment]
@csholmq I've added recently that the current find match also adds a full line decoration to help in spotting the current match easier (100% the same decoration as the go to line decoration, for example).

Here is how things work:
* the current line highlight (the one with thin borders) is the default one in the VSDark or VSDark+ theme. You can pick a different theme to get a different rendering. *This current line highlight is shown when there is no selection -- irrespective of the find widget*
* the current match highlight + the current match line highlight -- *this one is shown when doing F3 or find next match, etc to help in spotting the match*.

How would you expect them to interact?

![find-match](https://cloud.githubusercontent.com/assets/5047891/16728230/df8c6adc-476d-11e6-97d2-a7ec10ddba9f.gif)

**Comment by csholmq** [comment]
@alexandrudima My complaint was with the default themes, indeed. Now that I have switched to Monokai theme I don't have this issue.

I believe the current line highlight is too subtle in the default theme, but that's just me.
