### ISSUE TITLE
editor tabs shows hebrew text in different order than editor contents

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89452]
Refs: #89274

- create a new untitled file and enter some hebrew text into the first line (e.g. "ובמצפון, לפיכך חובה עליהם לנהו")

Observe that the editor tab shows the words in reverse order:

![2020-01-28_12-42-14](https://user-images.githubusercontent.com/1898161/73283171-fc5bff00-41f2-11ea-9266-9a48159ac215.png)

I don't know whether this is correct or not, but I just want to bring this to your attention.

**Comment by bpasero** [comment]
Isn't this the same order as in the editor?

![image](https://user-images.githubusercontent.com/900690/73280228-86559900-41ee-11ea-9353-09929f666f93.png)

**Comment by weinand** [comment]
Ups, I forgot to add a screenshot to the initial comment. I've added a screenshot that shows that the word order is flipped.

**Comment by bpasero** [comment]
No, on macOS. But I copied and pasted, did you type?

**Comment by weinand** [comment]
no, I copied from a web site.

**Comment by bpasero** [comment]
I am literally getting the contents from the model and then put then into our label. I would assume this probably looks like this in all places where we use labels. I am not sure how to fix that...
