### ISSUE TITLE
Double clicking text in the search editor opens the editor that contains the corresponding search result

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#89451]
Found while testing: https://github.com/microsoft/vscode/issues/89396

Issue Type: <b>Bug</b>

Open a search editor
Run a search
Go to any result
Double click on some text in a result
Expected: text to be highlighted
Actual: another editor is opened containing that search result

I realise that this is the behaviour of the search viewlet but the fact that this is the default for search editors seems inconsistent. I think the default should be selectWord for search editors.

VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:38:41.922Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
vscode-github-releases-updater|joa|0.18.0
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
remote-containers|ms-|0.99.2
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
cloudenv-extensions|ms-|1.0.1369
vsonline|ms-|1.0.1507
test-search-rg|rob|0.0.3

</details>

**Comment by JacksonKearl** [comment]
cc @sbatten 

On one hand, I think in the search editor, going to results will be more common than selecting words, so we should make that as easy as possible, which means allowing access with the mouse only in addition to keyboard only. 

I think people would also be more likely to search for a setting for select word if they wanted that to exist than the opposite.

Not sure...

**Comment by sbatten** [comment]
I agree with the sentiment of @stevencl. What is the difference between ctrl click and double click in the search editor by default?

**Comment by JacksonKearl** [comment]
@sbatten no difference, besides one can double click using only a mouse or trackpad. In the first release I got a good number of complaints about Ctrl+click being too high-energy for the most-common operation in the search editor.

**Comment by JacksonKearl** [comment]
Closing this out as I haven't received any other similar requests and we do provide the option.
