### ISSUE TITLE
Editor inputs have contributed commands in the context menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89459]
re https://github.com/microsoft/vscode/issues/89333

* focus SCM input
* show context menu
* the is a entry "Command Palette..." which is awkward 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/1794099/73266790-e4c34d00-41d7-11ea-9bc0-8fea17017eba.png">

**Comment by gjsjohnmurray** [comment]
Related to this, on my system that context menu also gives me entries that have been contributed by a couple of my extensions.

**Comment by joaomoreno** [comment]
This happens across all our inputs which use the Editor. IMO we should not include all those contributions and should just have `Cut`, `Copy` & `Paste` in that menu.

What's the simplest way towards this @alexdima?

**Comment by alexdima** [comment]
@joaomoreno The "Command Palette..." should potentially have a better context key for `precondition`, not `undefined`: https://github.com/microsoft/vscode/blob/4e27cff4ccfc5774a15d55e09e0e9143f1c575e0/src/vs/workbench/contrib/quickopen/browser/commandsHandler.ts#L216

**Comment by joaomoreno** [comment]
@alexdima This is actually only half of the story. As @gjsjohnmurray mentions, contributed commands show up:

![image](https://user-images.githubusercontent.com/22350/73369716-591eee80-42b3-11ea-8d91-06df26f4837a.png)

Should we file issues to these extensions, suggesting to change their `when` clauses?

**Comment by jrieken** [comment]
It might be better/simpler to have another menu id, something like `embeddedEditorContext` or even something SCM specific

**Comment by alexdima** [comment]
To reproduce, you can use:

```
"menus": [
    "editor/context/copy": [{
        "command": "workbench.action.toggleDevTools"
    }]
]
```
