### ISSUE TITLE
Search editor: first line could show a bit of information

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89463]
Refs: #89396

I think the first line could indicate how many search results there are, similar to what the search viewlet does:

![image](https://user-images.githubusercontent.com/900690/73268962-3241b900-41dc-11ea-8f43-c8d1c022b3c7.png)

Compared to ST:

![image](https://user-images.githubusercontent.com/900690/73268978-37066d00-41dc-11ea-95fc-b65e684fc8e7.png)

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/73991556-59e20100-4901-11ea-856a-d4283e491a0d.png)

**Comment by Tyriar** [comment]
@JacksonKearl please add a test plan or verification needed

**Comment by bpasero** [comment]
Would add a condition for single values:

![image](https://user-images.githubusercontent.com/900690/75260120-657e6480-57e9-11ea-88fa-6fbaafe4b7a9.png)
