### ISSUE TITLE
Terminal: Cannot launch code-insiders.cmd from inside Code on Windows

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#8947]
This is broken when using the integrated terminal and the PowerShell Extensions RunSelectedText (f8), but it works when using the PowerShell Extensions Debugger (f5)

- VSCode Version: 1.3.0-insiders and 1.4.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Using either integrated terminal run code-insiders.cmd filepath or code-insiders.cmd
2. Nothing will be output. The command runs but nothing actually happens

This stopped working for me a few days ago after one of the nightly insiders builds.

**Comment by gerane** [comment]
This appears to still work in the Stable version of Code using the `code` or `code.cmd` commands.

**Comment by gerane** [comment]
I am wondering if this might be related to the linux code.sh issues here #8141 and #7451

**Comment by bpasero** [comment]
@Tyriar the only change I made that maybe has an impact is https://github.com/Microsoft/vscode/commit/25eb33df1e948ae73343909ce86209b492c5de16

@gerane are you able to reproduce this running "out of sources"? Could you see if that commit has an impact?

**Comment by gerane** [comment]
hmm, i'm not that familiar, do you have any docs on how I could do that?

**Comment by bpasero** [comment]
It is outlined in: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

But you also will need to install the extensions into the thing, which you can do by downloading the VSIX and dropping it into the instance.

**Comment by gerane** [comment]
Just looked at [build and run from source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) and it might be a little while before I can get some of those dependencies set up.

**Comment by bpasero** [comment]
@gerane no worries, we can also wait for @Tyriar to comment.

**Comment by gerane** [comment]
hmm, so when I launched the dev build and try to open a terminal it just errors for me.

```
Error: Cannot find module '..\bin\win32\ia32.m47.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (c:\Github\vscode\node_modules\pty.js\lib\pty.js:18:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
[88656:0708/110115:INFO:CONSOLE(80)] "The terminal process terminated with exit code: 1", source: file:///C:/Github/vscode/out/vs/workbench/services/message/browser/messageService.js (80)
```

**Comment by gerane** [comment]
I was on node v5.1.0, so I upgraded but now it won't build. No time to mess with it right now.

**Comment by Tyriar** [comment]
The fix for #8141 was to remove `ATOM_SHELL_INTERNAL_RUN_AS_NODE` from the environment https://github.com/Microsoft/vscode/commit/9a7ec35a6adc97b7b611a9bdc6228eaea7c6be0d. As far as I can see this was changed to the new name when you upleveled Electron and switched back fine afterwards.

Removing this env variable should only make it act more like a regular terminal, and it's included in stable.

**Comment by bpasero** [comment]
Btw I just pushed a new insiders build where we are back to `ATOM_SHELL_INTERNAL_RUN_AS_NODE`

**Comment by gerane** [comment]
I installed the version that was just pushed out and having the same
problem.

**Comment by gerane** [comment]
After upgrading to new build and closing and reopening several different projects, it looks like this started to work again.

**Comment by Tyriar** [comment]
@gerane is it fine on both stable and insiders?

**Comment by gerane** [comment]
I never had the issue on stable, though I rarely use stable, but every time
I tested it worked on stable.

**Comment by Tyriar** [comment]
Cool, let us know if it comes back on Insiders :smiley:

**Comment by kdheepak** [comment]
I'm having this issue in code-insiders. I'm unable to launch code-insiders from the terminal within "Code - Insiders". 

```
ImportError: No module named site
/usr/local/bin/code-insiders: line 10: ./MacOS/Electron: No such file or directory
```
