### ISSUE TITLE
Search editor: highlights should not hide when search viewlet is hidden

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89470]
Refs: #89396

I think we have logic that removes all search highlights once the search viewlet is hidden. But if a search editor is still opened, the highlights should be preserved, especially when I use side by side editing where on the right hand side I now miss the highlights:

![image](https://user-images.githubusercontent.com/900690/73269667-8a2cef80-41dd-11ea-8c47-5623eb5318ae.png)

**Comment by JacksonKearl** [comment]
The are you talking about highlights in the document opposite the search editor? The search editor doesn't contribute any highlights to documents besides itself -- are you saying you want the search viewlet's highlights to persist?

**Comment by bpasero** [comment]
@JacksonKearl 

> are you saying you want the search viewlet's highlights to persist?

Yes. If and only if the search editor is visible. Consider this scenario: I may only be using the search editor and not the search view at all. When I work side by side, the right hand editor - even though opened from the search editor - does not show the search highlights, making it hard to work with it.
