### ISSUE TITLE
Sync ordering when there are conflicts

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89479]
Testing https://github.com/microsoft/vscode/issues/89358

This scenario might be too contrived, but just in case it isn't, here are the steps:

- Turn on sync across two machines (A and B)
- Set a theme color
- Turn off sync on A
- Change theme color on A and on B to different colors
- Turn on sync on A
- View the conflicts that arise
- Don't resolve the conflicts yet.
- On B, change the theme again to yet another color
- On A, resolve the conflict. 
Expected: The conflict doesn't resolve, or there is a new conflict since B changed color again.
Actual: Whatever I just resolved the color to on A wins and now B has A's color.

**Comment by sandy081** [comment]
Thanks for the bug and I am waiting for it.

I intentionally decided to overwrite in this case because its single user data and  in this case what ever user is trying to resolve should be given the preference.
