### ISSUE TITLE
Restart Frame shown on async part of stacktrace

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89471]
#89393 testing on Windows.

Restart Frame is shown on past parts of the stacktrace. It doesn't work:
![image](https://user-images.githubusercontent.com/9205389/73269681-8ef1a380-41dd-11ea-8f28-ab4a36e4c0ae.png)

**Comment by connor4312** [comment]
Previous discussion: https://github.com/microsoft/vscode/issues/84045#issuecomment-557157527

cc @isidorn @weinand. Mentioned there, I think the most reliably way would be to have an annotation from the debug adapter indicating whether or not each stack frame can be restarted.

**Comment by isidorn** [comment]
If we do not introduce a new annotation for this the best I could do from the UX side is to not show Restart Frame action on `deemphasize` stack frames.
What do you think about that approach?

**Comment by connor4312** [comment]
I think an annotation would be better. I'm not sure using deemphasis alone as the boundary is totally correct for js-debug, and may not work for other debuggers.

**Comment by weinand** [comment]
@connor4312 this can be closed, right?

**Comment by isidorn** [comment]
I tried this out and was working fine for me. Thus closing this and @connor4312 can reopen if needed
