### ISSUE TITLE
Found no way to create a language specific setting programmatically if it doesn't exist before

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#89486]
Testing https://github.com/microsoft/vscode/issues/89360

The code I tried is:

```ts
const jsConfig = vscode.workspace.getConfiguration('89360', { uri: editor.document.uri, languageId: 'javascript' });
jsConfig.update('enable', value * 2, vscode.ConfigurationTarget.WorkspaceFolder);
```

Note that the settings file has no `javascript` section

**Comment by sandy081** [comment]
@dbaeumer you can pass additional flag to `update` to create language specific setting.

**Comment by dbaeumer** [comment]
Suggest to rename that parameter to `force` or `create`. I couldn't understand `scopeToLanguage` without reading the doc :-)

**Comment by sandy081** [comment]
Is not calling `update` with `scopeToLanguage` flag means scope the update to language?

**Comment by dbaeumer** [comment]
All I can say that I was quite surprise since I already passed in a language scope wit `{ uri: editor.document.uri, languageId: 'javascript' }`. So having another parameter named `scopeToLanguage` was confusing to me and did not tell me that it forces creating the language specific group in the settings file if it doesn't exist.

**Comment by dbaeumer** [comment]
May be `createIfNotExisting` might be a good alternative.

**Comment by sandy081** [comment]
`createIfNotExisting` is too generic and does not explain what to create. How about `overrideInLanguage` ?

**Comment by dbaeumer** [comment]
I like `overrideInLanguage`
