### ISSUE TITLE
Search editor: .code-search should have an icon by default

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89480]
Refs: #89396

It looks like we are introducing a new file type *.code-search. It should also have a icon in the build in icon themes we ship:

![image](https://user-images.githubusercontent.com/900690/73270340-c14fd080-41de-11ea-8e01-6f7cea243965.png)

**Comment by JacksonKearl** [comment]
PR up on Seti at jesseweed/seti-ui/pull/547

**Comment by JacksonKearl** [comment]
Added an icon to the default (seti) icon pack.
