### ISSUE TITLE
Search editor: status bar is silent even though text is displayed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89482]
Refs: #89396

![image](https://user-images.githubusercontent.com/900690/73270476-05db6c00-41df-11ea-8522-03c50a4c24c2.png)

vs

![image](https://user-images.githubusercontent.com/900690/73270484-0c69e380-41df-11ea-9a77-808a49940bdc.png)

We probably need some generic way (via `TextEditorInput`?) to have the `editorStatus.ts` classes detect the editor that is opened. Currently that one is probably probing for file editor and untitled editor inputs.

**Comment by JacksonKearl** [comment]
What all should be present? Position makes sense, possibly tab size. I'm not sure if encoding or line ending make sense, and mode probably doesn't make sense (one wouldn't change the mode).

**Comment by bpasero** [comment]
Yeah, likely only a subset - those that make sense.

**Comment by JacksonKearl** [comment]
Added the status bar entries, but no clean way to configure which entries show for a given editor. Currently the "Search Result" mode will show and be clickable, but choosing results doesn't actually do anything. (aborts out at https://github.com/microsoft/vscode/blob/ec6feef1bd77313181feba1289785f87a782d95b/src/vs/workbench/browser/parts/editor/editorStatus.ts#L1097)

put up #90183 to fix that.
