### ISSUE TITLE
Incorrect workspace and workspace folder value

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#89481]
Testing https://github.com/microsoft/vscode/issues/89360

Following settings

```
{
	"89360.enable": 1,
	"[plaintext]": {
		"89360.enable": 4,
	}
}
```

Inspecting the value for a configuration scoped to `plaintext` gives:

![capture](https://user-images.githubusercontent.com/1931590/73270332-bc8b1c80-41de-11ea-9d49-6c8b2fe73c79.png)

I would have expected workspace and workspace folder value to be 1.

**Comment by sandy081** [comment]
Good catch!!!
