### ISSUE TITLE
'Restart' button when attached to process

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89483]
#89393 on Windows.

Node.js testing:

The 'Restart' button sometimes (after stepping?) just disconnects and does not reconnect. It reconnects as expected right after attaching (or maybe that was luck?).

Also, the 'Restart' button should maybe be called 'Reconnect'.

**Comment by connor4312** [comment]
Merging this into https://github.com/microsoft/vscode-js-debug/issues/270
