### ISSUE TITLE
Expect some error message when sync fails and for sync to turn off

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89485]
Testing https://github.com/microsoft/vscode/issues/89358

I made my setting file too big by adding lots of comments. Now it doesn't sync, but the only way for me to know that is to look in the sync log. Instead, could there be an error?

I also expect sync to turn off after 5 failures. It does not. Instead it keeps trying to sync the large file and failing.

**Comment by Tyriar** [comment]
This testing also caused _a lot_ of traffic on the server, more aggressive disabling requests on large files like this is probably a good idea.

**Comment by sandy081** [comment]
I stop sync when I get this error. Let me check again.

**Comment by Tyriar** [comment]
I think the client should refuse to request a sync on a file too large, with the server's limit just being fallback validation that shouldn't get hit during normal usage.

**Comment by sandy081** [comment]
I would first investigate why sync is not getting stopped with this error. 

Re validating on the client, I will think about it.

**Comment by sandy081** [comment]
Validation in the client will be tracked here - https://github.com/microsoft/vscode/issues/89597
