### ISSUE TITLE
Should task label support a hover?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#89498]
Found while testing: #89342

Create a very long label for task pickstring such that the text overflows the quick pick dropdown box and is displayed clipped with an ellipsis (...). 

![image](https://user-images.githubusercontent.com/12818376/73275701-64332b00-419c-11ea-8de0-74f679115a75.png)

There is no way to see all the text as no scroll bar or hover.

This might be a limitation of the quick pick control.

**Comment by alexr00** [comment]
The quick pick currently doesn't offer a way to add a hover. I'm actually ok with this since this is the first time anyone has noticed and mentioned that there is no over for it.
