### ISSUE TITLE
Debug: show presentation group name in picker

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89492]
Refs: https://github.com/microsoft/vscode/issues/89018

In the picker we have support to show group names on the right hand side, similar to this:

![image](https://user-images.githubusercontent.com/900690/73273765-c9127380-41e4-11ea-8b82-8e09c100b48b.png)

**Comment by isidorn** [comment]
Dislike. Since we use the group for alphabetical sorting, we would need to introduce a new field `groupLabel`.
Thus I decided to simply not show it.
