### ISSUE TITLE
Multi cursor do not work for me in the SCM input box

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89490]
Refs: #89333

On linux:

Multiple cursors do not work for me in the SCM input box.
I don't know whether they are supposed to work, so I just let you know...

**Comment by joaomoreno** [comment]
@weinand It should work with `Alt` clicking. What are you doing to get them working?

**Comment by weinand** [comment]
Since linux uses the ´Alt´ modifier for something else I had to use the "Toggle Multi-Cursor Modifier" action to switch to "Control click". With this multi-cursor worl fine in the editor but not in the SCM test box.

**Comment by deepak1556** [comment]
Just wanted to update that on macOS it works fine.

**Comment by joaomoreno** [comment]
Oh I see. That's because this editor, just like other simple input editors across the workbench, doesn't respect user settings. Closing for now until the issue surfaces in the real world, I hope that's alright with you @weinand.

**Comment by weinand** [comment]
Sure, fine by me. I only test "multi cursor support" because you mentioned it in the test plan item.
