### ISSUE TITLE
Codicon: offer intellisense for possible entries

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89494]
Refs: https://github.com/microsoft/vscode/issues/89328

For example in package.json:

![image](https://user-images.githubusercontent.com/900690/73274298-a3399e80-41e5-11ea-9413-e3691ec4b1e2.png)

Would even be awesome if intellisense could preview the icon as it looks like!

**Comment by jrieken** [comment]
Agreed, but no clue how to get that working, esp with the list of codicon changing and our plans to enable 3rd parties to contribute different icon sets

**Comment by connor4312** [comment]
At least the TS side of things you could have a string enum for the built-in codicons to make referencing them easier, like

```ts
enum BuiltInIcons {
  Add = 'add',
  // ...
}

new ThemeIcon(BuiltInIcons.Add);
new ThemeIcon('myCustomIcon');
```

**Comment by djmisterjon** [comment]
btw something similar
![image](https://user-images.githubusercontent.com/24865815/73303724-f19a6d80-41e4-11ea-8292-8f93db61482f.png)
i very love this plugin
https://github.com/kisstkondoros/gutter-preview

**Comment by aeschli** [comment]
Eventually we will have an icon contribution registry that we also use for the built-in icons (like the color registry).
That will allow us to create a schema for the package.json
