### ISSUE TITLE
A visible Timeline results in a lot of visual noise

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89509]
#89385

Version: 1.42.0-insider (user setup)
Commit: c4b6a6b
Date: 2020-01-28T05:38:41.922Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

When working with the timeline view opened I find it quite distracting as every time the file changes the view has all text removed and then fills in for the new file. One idea to prevent this is to disable the items in the view but leave them there until the new items are ready (or until some short timeout has elapsed), that way it would change from a full view to another full view.

**Comment by eamodio** [comment]
@Tyriar I think I have improved things a bit in `master`. Can you check it out in tomorrow's insiders? To me it feels the same as the Outline view.

**Comment by Tyriar** [comment]
@eamodio it still flashes empty and then full though?

When flipping between 2 files multiple times, one appears to be cached and the other not?

![Kapture 2020-02-07 at 7 55 44](https://user-images.githubusercontent.com/2193314/74044051-4d9c8900-497f-11ea-8172-fadef44d0765.gif)

**Comment by Tyriar** [comment]
@eamodio what was the fix that happened here?

**Comment by eamodio** [comment]
After discussion in Friday's standup, we will now not update the view until we've loaded the fastest provider for the new file, and if the user interacts (clicks on, etc) any of the items in the view while we are still loading, then the view will switch to the "loading" state.
