### ISSUE TITLE
Refactor preview: show creates and deletes still in diff editor?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89501]
Refs: #89335

I wonder if refactor preview should always open a diff editor and for:
* create: left side is empty
* delete: right side is empty

Not sure how git does it, we may want to align the experience.

**Comment by jrieken** [comment]
They should only show a diff editor when also having textual changes, otherwise a "normal" editor should be used. Can you confirm?

**Comment by bpasero** [comment]
Yeah they do. 

I think it is probably fine the way it is. In GIT:
* a deleted file when clicked on in the changes view shows in a normal editor
* an added file on the index will show a diff editor

Not sure if we would want to align, that would mean showing a diff editor for added files even when there is no other refactoring within.

![image](https://user-images.githubusercontent.com/900690/73337028-c4e16700-4273-11ea-8ac6-ce4a3dfed2ce.png)

**Comment by jrieken** [comment]
I have pushed a change to align this with the SCM/git behaviour
