### ISSUE TITLE
Come up with caching strategy for the git timeline view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89505]
#89385

Version: 1.42.0-insider (user setup)
Commit: c4b6a6b
Date: 2020-01-28T05:38:41.922Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

It seems wasteful to throw away events when the active editor changes. Perhaps we should cache the loaded events for all opened editors and discard them when the editor closed?

**Comment by eamodio** [comment]
Right now, my plan is to leave this up to the individual providers to handle any caching, if it is expensive to re-compute.

**Comment by Tyriar** [comment]
Ok, consider this issue about git timeline provider caching then 😄

**Comment by pltrant** [comment]
I agree that this would be very useful for the new timeline feature.  I work in a git repository that has very slow git log performance (which I can't control), so when I switch between files, it literally takes a few minutes before the timeline view is populated and it has to repeat this process every time I switch to a new file and back again.

**Comment by Tyriar** [comment]
@eamodio I've also worked in a very slow git repo in the past. We were talking about waiting for and merging multiple providers the other day, maybe it should wait 1-2 seconds before displaying and then slowly fill in the other provider for a slow one?

**Comment by Tyriar** [comment]
@eamodio is this not feasible or? Any reduction to the amount of shelling out we do is a win.

**Comment by eamodio** [comment]
Until we expose more information about exactly what changed (wrt the repository, working tree, etc), any caching would be mostly pointless, because we'd constantly be flushing all the caches. Once https://github.com/microsoft/vscode/issues/94826 is fixed, then we can look into caching.
