### ISSUE TITLE
Snippet descriptions are clipped

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#89507]
- VSCode Version: 1.42 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Bring up an image snippet for Markdown.

Description is clipped with ellipsis (...) but no way to see full text.

![image](https://user-images.githubusercontent.com/12818376/73277747-7367a800-419f-11ea-9bb2-68aa76015465.png)

If you Ctrl+Space to see more information and the snippet preview, the description is still clipped.

![image](https://user-images.githubusercontent.com/12818376/73277884-a14cec80-419f-11ea-89e4-4c3cf0f05ca4.png)

**Comment by gregvanl** [comment]
1.41.1 Stable:

![image](https://user-images.githubusercontent.com/12818376/73278338-4cf63c80-41a0-11ea-85a9-4d7e5e26d71c.png)

**Comment by jrieken** [comment]
@octref I have now fixed this by also setting the detail-field on snippet completions. That works nicely but we might wanna consider something more generic here...
