### ISSUE TITLE
F2 createNewFileWithContent does not check file?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89500]
Refs: https://github.com/microsoft/vscode/issues/89335

Is there a reason the file itself is not checked here? I picked the `createNewFileWithContent`

![image](https://user-images.githubusercontent.com/900690/73276643-4cce5f00-41e9-11ea-82bf-5730ea8c9f1a.png)

**Comment by jrieken** [comment]
Yeah, the file is being associated to a different category and that has "needsConfirmation" set. That should be more obvious when grouping by type. In the group-by-file view there is no indication of types (except for the hover) but then this is also a pretty artificial sample

**Comment by bpasero** [comment]
Ok that was not clear to me, probably something that would only happen with very specific refactoring providers.

However, maybe we should simply check this by default if the refactorings inside are applied. I mean, how could they be checked if the file is not being created?

**Comment by jrieken** [comment]
Yeah, I have now pushed a change that checks parents when children are being checked. Tho, I don't do a check/fix before rendering them and I'd say that is then an extension/provider issue.

**Comment by jrieken** [comment]
to verify: make sure that checking a child checks its parent and that unchecking a parent unchecks its children

**Comment by jrieken** [comment]
>  Tho, I don't do a check/fix before rendering them and I'd say that is then an extension/provider issue.

Actually, I will push a change that fixes "bad" metadata since testing has shown that such metadata is very confusing
