### ISSUE TITLE
TS gives docs on a constants type, rather than docs on the constant itself

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89508]
Notice that the docs are talking about `vscode.Event`

![image](https://user-images.githubusercontent.com/2193314/73277797-811d2d80-419f-11ea-81fe-f4ecdb1fcda3.png)

Instead of the thing I actually want:

![image](https://user-images.githubusercontent.com/2193314/73277854-95612a80-419f-11ea-88e5-f9ecb64d2be6.png)

Version: 1.42.0-insider (user setup)
Commit: c4b6a6b537de49a734d0eedea06152ea37dfdb6a
Date: 2020-01-28T05:38:41.922Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

TS 3.7.5

**Comment by mjbvz** [comment]
Upstream issue: https://github.com/microsoft/TypeScript/issues/36486
