### ISSUE TITLE
Refactor preview: indicate create/delete/renames better?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89504]
Refs: #89335

I am finding this a bit hard to read, why not do something like "<original file name> => <new file name>". There is possibly a good unicode arrow to use. E.g. diff editor does this:

![image](https://user-images.githubusercontent.com/900690/73277124-fca3cc80-41e9-11ea-9870-915c9ee68595.png)

![image](https://user-images.githubusercontent.com/900690/73277030-e1d15800-41e9-11ea-8625-4645eedec817.png)

**Comment by bpasero** [comment]
//cc @misolori for UX. I wonder if all of the create/delete/rename operations should visually indicate better what they are doing:

![image](https://user-images.githubusercontent.com/900690/73277214-1d6c2200-41ea-11ea-9e76-6279b547aa16.png)

![image](https://user-images.githubusercontent.com/900690/73277228-23fa9980-41ea-11ea-97ec-91598a6e19f5.png)

**Comment by jrieken** [comment]
Yeah, I am very open for ideas here

**Comment by misolori** [comment]
I had a hard time visually understanding the change. Would it help if we repeated the same text in the before/after so it's easier to understand?

![image](https://user-images.githubusercontent.com/35271042/73407024-c9764180-42ac-11ea-9951-1759862166ba.png)

I also wonder if there's a way to use some type of decorators like Git does to indicate the type of change:
![image](https://user-images.githubusercontent.com/35271042/73407076-e3b01f80-42ac-11ea-9c0d-7c5343550f9b.png)

**Comment by jrieken** [comment]
I have pushed a change that uses `\u2192` (→) for renames


<img width="566" alt="Screenshot 2020-02-07 at 13 06 21" src="https://user-images.githubusercontent.com/1794099/74028456-a6354b80-49aa-11ea-9549-9033fa8e2624.png">

**Comment by jrieken** [comment]
For deleting it now shows a strike out 👇 

<img width="418" alt="Screenshot 2020-02-07 at 15 42 44" src="https://user-images.githubusercontent.com/1794099/74038441-7e50e280-49c0-11ea-90df-c023f9a4d705.png">
