### ISSUE TITLE
Refactor preview: rename failed to apply edits

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89506]
Refs: #89335

Setup as instructed in test plan. My file content was:

```
createNewFile
createNewFileWithContent
deleteThisFile
editAndRenameThisFile
renameAndEditThisFile
```

I clicked into `renameAndEditThisFile`, hit F2 and added a `2` at the end. Opened preview and accepted the change, got this:

![image](https://user-images.githubusercontent.com/900690/73277417-6e7c1600-41ea-11ea-8515-bc6b6a0fb0e6.png)

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2717 Rename failed to apply edits
onDidNotificationChange @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2717
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1595   ERR Error: Unable to read file '/Users/bpasero/Desktop/test-ts/test-RENAME-EDIT-2ca.refacto' (Error: Unable to resolve non-existing file '/Users/bpasero/Desktop/test-ts/test-RENAME-EDIT-2ca.refacto')
    at _.doReadAsFileStream (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1615)
```

**Comment by jrieken** [comment]
Needs checking... Maybe just an issue with my hacked up extension

**Comment by jrieken** [comment]
I can reproduce - that's because the text change is applied on the renamed file and in this scenario that files has been created/faked yet

**Comment by rebornix** [comment]
I'm still seeing this issue in standalone editor while testing https://github.com/microsoft/vscode/issues/89392 . Running OSS from master (commit: 8e0cfc1ab2bf9524c2e9e25f4c4bbfc46be4d974) works fine.

**Comment by jrieken** [comment]
@rebornix Please file a separate issue, in the standalone editor there is no preview and non the code that was involved for this issue. While there surely is some kind of failure, it's not the preview logic

**Comment by alexr00** [comment]
It worked the first time I tested, but not I get this ever time, even after reloading.
![image](https://user-images.githubusercontent.com/38270282/73532866-dd8d8080-441d-11ea-8a14-2038689c3466.png)

**Comment by jrieken** [comment]
Good find, but a different issue. Please file a separate issue.
