### ISSUE TITLE
Not clear what the purpose of source in TimelineItem is

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89516]
#89385

Version: 1.42.0-insider (user setup)
Commit: c4b6a6b
Date: 2020-01-28T05:38:41.922Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/2193314/73280202-0fdf7980-41a3-11ea-97b8-02c9fd93d595.png)

Before actually running it seems like it's related to `TimelineProvider.source`, however that one seems to be an id where as `TimelineItem.source` explicitly says human readable? If they are related, why does `TimelineItem` need a source at all if it already has a source id (`TimelineProvider.source`) and a human readable (`TimelineProvider.sourceDescription`) one?

**Comment by eamodio** [comment]
Doh -- that is a bug. I accidentally left that in, as I used to have the source on the items themselves, but I moved it to the provider.
