### ISSUE TITLE
misleading wording of "files.preventSaveConflicts" setting

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89510]
Refs: #89272

IMO the name of the setting "files.preventSaveConflicts" is misleading (and the description of the setting doesn't help clarifying this either).

If I understand the setting correctly it controls whether in case of a conflict VS Code just overwrites the conflicting file on disk without asking or whether it asks and shows a diff editor.

So the setting does not control "save conflicts" but it controls the conflict resolution.
A value "true" lets the user resolve the conflict manually (which helps to prevent data loss).
A value "false" automatically resolves the conflict by overwriting the file on disk (which always results in data loss in the file on disk).

I suggest to rename the setting to better reflect this semantics, e.g. as an enum "saveConflictResolution" with the two values "askUser" or "overwriteFileOnDisk".

**Comment by bpasero** [comment]
Yeah, valid points.

**Comment by bpasero** [comment]
**Verification:** basically verify that the proposal from https://github.com/microsoft/vscode/issues/89510#issue-556288044 is implemented and works as advertised. 

@weinand maybe you want to check, can run out of sources to see it in settings editor.
