### ISSUE TITLE
TypeScript service died

### ISSUE THREAD

**Issue by tommck** [microsoft/vscode#89511]
Issue Type: <b>Bug</b>

I opened an enormous (3.2MB) bundled JS file

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.37GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.7
previewseqdiag-vscode|ari|0.2.3
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
javascript-ejs-support|Dig|1.2.1
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.18.0
vscode-peacock|joh|3.3.1
git-graph|mhu|1.21.0
vscode-azureappservice|ms-|0.16.2
azure-account|ms-|0.8.8
powershell|ms-|2020.1.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1510
team|ms-|1.161.0
vscode-mscgen|msc|1.2.0
angular-console|nrw|10.0.0
sort-lines|Tyr|1.9.0

</details>

**Comment by tommck** [comment]
what's even more awesome is... it doesn't even show me the file contents.

Also, **more context**: I had a large project open and ran "code filename.js" from the command line to open it in the existing code instance

**Comment by mjbvz** [comment]
Can you share the bundled file?

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Closing as not actionable without more information. If you are still running into this, please share the the file that causes this so we can investigate
