### ISSUE TITLE
Sync: pressing Back on auth page results in unfriendly message

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89518]
Refs: #89358

If you press the _Back_ button on the auth screen you get this unfriendly message:
![image](https://user-images.githubusercontent.com/641685/73281684-55f60680-41be-11ea-8ce2-2e53959fe836.png)

In VS Code it is fine though:
![image](https://user-images.githubusercontent.com/641685/73281752-6ad29a00-41be-11ea-8e6e-848ecc802c83.png)

**Comment by sandy081** [comment]
@RMacfarlane This happens when sync is enabled with no token which should never happen. Can you please check if you are setting auth status properly in this case?

**Comment by RMacfarlane** [comment]
The error message is still ugly (Not sure what would be clearer to show there? Pressing "Back" isn't expected to work, I have no control over what's shown on that page.), but now an error is thrown before settings sync is enabled

**Comment by roblourens** [comment]
I don't understand which page to press back on. I can't press back on this page: 
![image](https://user-images.githubusercontent.com/323878/75500507-01db6f00-5982-11ea-8602-efa481a21c33.png)

and on the next one, by the time it has loaded we have logged in successfully and pressing back just goes back to the page above with no bad effects.

**Comment by RMacfarlane** [comment]
@roblourens Hmm, when making this fix, I was able to press "Back" on the page you've screenshotted. The steps should be:

1. Start sign in and see browser page as above
2. Click the back button on that page
3. Error is displayed in browser
4. Going back to VSCode, you have not been signed in

**Comment by roblourens** [comment]
Is it different for me because I have two accounts? No back button

![image](https://user-images.githubusercontent.com/323878/75501906-20436980-5986-11ea-9e76-33193ab064ee.png)

**Comment by roblourens** [comment]
I realized that we are talking about the button that says Back, not the browser navigate button 😆 

The notification in vscode is not clear but it's ok, the user knows what they did... it sounds like everything is working as expected.
