### ISSUE TITLE
Folders not showing in Git explorer View for workspace

### ISSUE THREAD

**Issue by albu77** [microsoft/vscode#89514]
Issue Type: <b>Bug</b>

The  Git explorer is not showing the folders structure when I open a folder where I declare a workspace.
Folders structure is normally shown when I open it as a folder.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:59:13.638Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|5.98GB (2.64GB free)|
|Process Argv|--folder-uri file:///d%3A/electron/GestionSiteRestau|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
project-manager|ale|10.10.0
vscode-custom-css|be5|3.0.9
css-compressor|bes|0.0.2
copy-without-formatting|bma|0.1.0
open-html-in-browser|cod|0.1.21
docs-markdown|doc|0.2.37
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.14.1
php-debug|fel|1.13.0
vscode-mysql|for|0.4.0
todo-tree|Gru|0.0.166
beautify|Hoo|1.5.0
typings-autoinstaller|jvi|1.2.0
gitignore|mic|1.0.1
vscode-language-pack-fr|MS-|1.41.2
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.0
live-server-preview|neg|0.1.4
qub-xml-vscode|qub|1.2.8
explorer-exclude-vscode-extension|Red|1.2.0
markdown-preview-enhanced|shd|0.5.1
flowmaker|spe|1.2.0
addDocComments|ste|0.0.8
markdown-all-in-one|yzh|2.7.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by albu77** [comment]
Here the screen capture sof the two cases because this didn't work when I post the bug

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo your screenshots didn't post. When I add screenshots into GH issues I simply copy them to my clipboard first, then paste them into the input field, e.g.
![image](https://user-images.githubusercontent.com/6726799/73292348-d128de00-41f9-11ea-8c58-7c8ddf76fec4.png)

 I'm using FF on Windows.

**Comment by albu77** [comment]
Ok  had to switch to Chrome because I need to update my Firefox which is too old. Find enclosed the screen capture

![BugWorkSpace](https://user-images.githubusercontent.com/624802/73302464-f840d900-4214-11ea-9e2a-6e49e25148f2.png)
![OkForFolder](https://user-images.githubusercontent.com/624802/73302479-fe36ba00-4214-11ea-8d74-53692d15fe63.png)

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/updates/v1_39#_updated-source-control-view documents the way this can be switched between list style and tree style. Also the setting, which I guess may be set differently for your workspace.
