### ISSUE TITLE
[php] Brackets not recognized in PHP from HTML

### ISSUE THREAD

**Issue by sorinpopescu** [Microsoft/vscode#8951]
- VSCode Version:1.3.0
- OS Version: W8.1

Steps to Reproduce: http://prntscr.com/bqe1c6

1. Open a PHP file that has HTML along with PHP echo
2. The brackets from PHP that's inside HTML are not matched or highlighted.

**Comment by sorinpopescu** [comment]
Hi
Any ETA for this? It's really annoying not to see the php along html.
Thanks

**Comment by aeschli** [comment]
We currently have no plans working on this. Help is wanted.

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/2915
