### ISSUE TITLE
Editor navigation scrolled to top when opening the LRU item

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89519]
#89277

When swapping to the least recently used file with ctrl+shift+tab, the last item in the picker is selected, but the scrollbar is at the top so I can't see what's selected. I would expect it would be scrolled to the bottom.

![image](https://user-images.githubusercontent.com/2230985/73282055-c6dcf480-41a5-11ea-921d-641a35b6ae74.png)

**Comment by bpasero** [comment]
Wow, old bug.
