### ISSUE TITLE
workbench.action.openNextRecentlyUsedEditordoes not seem to work

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89522]
https://github.com/microsoft/vscode/issues/89277

This command appears to have no effect. 

```
Commit: c4b6a6b537de49a734d0eedea06152ea37dfdb6a
Date: 2020-01-28T05:34:51.242Z
```

Video: https://memes.peet.io/img/dd9069b8-d330-459c-a275-c6a6db5204ee.mp4

**Comment by connor4312** [comment]
openPreviousRecentlyUsedEditor does work

**Comment by deepak1556** [comment]
I was confused about this as well, but became clear that the operation works like a stack if the editor is the last one then its basically noop, in your example does going back to `controls.tsx` and executing the command bring the editor back to `model.tsx` ?

anyways will let @bpasero decide if this is a bug.

**Comment by bpasero** [comment]
Yes, this is as designed. Think about it like "Go Forward" and "Go Backward". You can only trigger "Go Forward" if you had previously navigated back in stack.

**Comment by connor4312** [comment]
Okay, thanks! Verified that works.
