### ISSUE TITLE
Commands/decorations too far away

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89521]
* move references viewlet to panel
* :bug: the command (X) and the decorations are too far away

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1794099/73283747-ddaa3800-41f3-11ea-9498-312de1f86b1d.png">

The search viewlet does this better as it stops floating those things to the right after some point and instead renders them with that label. 

<img width="510" alt="image" src="https://user-images.githubusercontent.com/1794099/73283864-029eab00-41f4-11ea-8698-723132d60180.png">

**Comment by sbatten** [comment]
we are awaiting feedback as there are some considerations around keeping actions in vertical alignment

**Comment by sbatten** [comment]
Search does not do this any more that I can tell. We are aligned.
