### ISSUE TITLE
Should refactor help come from provider?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89526]
re https://github.com/microsoft/vscode/issues/89388

I have a test extension that now contributes refactor "help" without actually contributing any code action... Given that the current help UX is embedded in the normal code actions flow (e.g. activation of extensions, calling providers etc) would it make sense to let code actions provider contribute the help as part of their metadata? That would bring doc and code actions (which are targeted by that doc) closer together

**Comment by mjbvz** [comment]
Will continue discussion in #86788
