### ISSUE TITLE
references viewlet has bogus title when in panel

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89523]
The references view sits inside a container called "References", that's why the view is called ["Results (N)"](https://github.com/microsoft/vscode-references-view/blob/db5c0a900e4ada62bca81d93bd9de19fbc2e3e3b/src/extension.ts#L88) when showing references, ["Implementation (N)"](https://github.com/microsoft/vscode-references-view/blob/db5c0a900e4ada62bca81d93bd9de19fbc2e3e3b/src/extension.ts#L90) when showing implementations, and for call hierarchy it shows "callers of" or "calls from".

<img width="806" alt="image" src="https://user-images.githubusercontent.com/1794099/73284011-3e397500-41f4-11ea-97c5-7e7a3ecf0196.png">

**Comment by jrieken** [comment]
There might be some changes required inside the extension (and in how many others?) but the weird thing is that the panel prefixes the title with the "old/static" title, e.g "Results: Results (9)"

<img width="414" alt="Screenshot 2020-01-28 at 17 38 21" src="https://user-images.githubusercontent.com/1794099/73284587-1a2a6380-41f5-11ea-8d58-6a234a99d873.png">

<img width="324" alt="Screenshot 2020-01-28 at 17 38 15" src="https://user-images.githubusercontent.com/1794099/73284603-1dbdea80-41f5-11ea-9dfa-78dce87c9a69.png">

**Comment by sbatten** [comment]
somehow, we should make the view titles descriptive enough. maybe we always add the original container title when moving to a non-default container and fix the logic to not duplicate the title as seen above.

**Comment by alexr00** [comment]
I think for the example above that would be good, but I expect that some extensions won't want that. By default, we can add the original container title, but we could also have allow an override title for when it's not in the default container for custom views.

**Comment by sandy081** [comment]
Are there any changes done here and what is the latest state of it?

**Comment by sbatten** [comment]
No changes, there have been many discussions around allowing users to set the icon and title of every container. I think this is a needed feature and the fix for this should align with that.

**Comment by sbatten** [comment]
With the ability to move the entire container at once, there is some relief here in that you will get a container with the name `References`. However, we still do not address the view being titled on its own.

**Comment by sbatten** [comment]
fixed by 56b8c192051b277ed775332ae24a0ab3425e2947
