### ISSUE TITLE
Indentation guide lines going through text on .yml file

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#8952]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:
1. Turn on indentation guide
2. Open yaml file

After that, I'm not really sure how to fully replicate this, I just noticed it in one of my yml files. I can send the contents of the file I'm using if necessary. I've attached a screenshot showing the issue, as you can see from it, the text that says "getters:" has the indentation lines passing through it, instead of stopping like the rest of the text
![screen shot 2016-07-08 at 15 15 09](https://cloud.githubusercontent.com/assets/11057501/16690296/17bcff6c-451f-11e6-80c3-906f6dc4aff5.png)

**Comment by alexandrudima** [comment]
Thank you for filing! :hear_no_evil:
