### ISSUE TITLE
JSON validation debounced too much

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89524]
Since a while a "feel" that JSON validation does take a long time to catch up, e.g I am typing in the presence of a squiggle and it takes a very, very noticeable time for the squiggle to disappear. Often I am looking at my code, trying to spot the issue but it's often a stale squiggle. I don't think this is CPU-bound but a debounce value which is too high.

**Comment by aeschli** [comment]
The `setTimeout(.., 100)` at the end of the diagnostics computation caused the diagnostics to be delayed by 1-2 secomds as other LS calls got processed first. Switched to `setImmediate` which is also what the other calls use to permit cancellation.
