### ISSUE TITLE
Images are not showing on markdown preview on v1.3.0

### ISSUE THREAD

**Issue by tugberkugurlu** [Microsoft/vscode#8953]
- VSCode Version:

```
Version 1.3.0
Commit e724f269ded347b49fcf1657fc576399354e6703
Date 2016-07-07T16:50:12.291Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

- OS Version:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

Steps to Reproduce:

1. put an image under your project directory (e.g. `.docs/media/Screenshot from 2016-03-04 15:47:50.png`)
2. create a makrdown file, reference the image inside it:

```
![](.docs/media/Screenshot from 2016-03-04 15:47:50.png)
```

3. hit `CTRL+SHIFT+V` and you will see that image is not being rendered.

**Comment by satokaz** [comment]
@tugberkugurlu , it contains a space in the file name.
If it is a cause, please replace the space to `&#32;`.

please refer to:
https://github.com/Microsoft/vscode/issues/7871#issuecomment-227056447

**Comment by joaomoreno** [comment]
#7871
