### ISSUE TITLE
Codicon color tokens should be area scoped

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89533]
https://github.com/microsoft/vscode/issues/89328 and related to https://github.com/microsoft/vscode/pull/89121

This looks kind of odd in the command palette imo. We may want to revisit codicon coloring, I think generally we should default to uncolored.

![image](https://user-images.githubusercontent.com/2230985/73288769-715a1500-41b0-11ea-9626-f579d06bc53e.png)

**Comment by jrieken** [comment]
@misolori Can you clarify where codicons should have color? Never when being rendered inside text, e.g never when used in the [CodiconLabel](https://github.com/microsoft/vscode/blob/82ed3d45ee481b547812f02d766398a71f005a92/src/vs/base/browser/ui/codiconLabel/codiconLabel.ts#L11)

**Comment by misolori** [comment]
Hmm...we only recently started removing color from the icons when out of context (like #89121). However in this context it doesn't bother me because you can also use emojis and those will always have color:

![image](https://user-images.githubusercontent.com/35271042/73385623-53f57b80-4282-11ea-8de6-39e7ff155acb.png)

We can bring it up the next UX sync or post it in the ux channel.

**Comment by connor4312** [comment]
Personally I also think emojis in the command palette are quite ugly 😛

**Comment by eamodio** [comment]
I think this is even more important for usages outside the command palette: 
![image](https://user-images.githubusercontent.com/641685/76888217-eca78100-6859-11ea-9d60-a8df5f423226.png)

Here I was thinking about using the step icons for push/pull in the GitLens view -- but with the color they look bad.

**Comment by eamodio** [comment]
Here's another example:
![image](https://user-images.githubusercontent.com/641685/76889760-8ec86880-685c-11ea-8500-805dd5c27d6e.png)

**Comment by misolori** [comment]
Updated the issue to make it so that all color tokens be scoped to their areas. Also happening for symbol icons used in the activity bar:

![image](https://user-images.githubusercontent.com/35271042/78693198-c51f6380-78af-11ea-9614-4ea61c42fbed.png)

cc @sbatten

**Comment by vainamov** [comment]
In response to https://github.com/microsoft/vscode/commit/d78f3419cca25c2c15b126365b0e836b9ef4b76b. I think e.g. the Go To Symbol (ctrl+shift+o) quick pick for example should keep the symbol icons colored like it does in the outline view. It makes distinguishing between symbols way harder when everything is the same color.

**Comment by misolori** [comment]
@vainamov thanks for bringing that up. This makes it really challenging to scope icon colors in the quick pick because of the various uses where some quick picks use it and others don't. I'll revert that commit and will need to revisit the strategy for this.

**Comment by misolori** [comment]
I think the guidance is for icons with color to adjust to their respective areas. For example, icons in the activity bar and status bar always should be a single color, while icons in the tree view + quick pick would persist their color. The primary icons that have color are Debug + Symbol icons, so it's a very limited scope already. These icons are intended to be used with color and in the cases that an extension does not want color should be recommended to use an alternate color via

```ts
this.iconPath = new vscode.ThemeIcon('rocket', new vscode.ThemeColor('foreground'));
```
