### ISSUE TITLE
Codicon alignment in the command palette

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89534]
In a world where extensions label commands with icons frequently, we might want to look at normalising their position in the command palette. Right now they will come after the category prefix, which may look messy if you have many different prefixes + icon + command name. Maybe they should align on the left or right hand side.

![image](https://user-images.githubusercontent.com/2230985/73289153-0d841c00-41b1-11ea-8aaa-ce673eae2d9d.png)

https://github.com/microsoft/vscode/issues/89328

**Comment by chrmarti** [comment]
The icon is embedded in the label's text, the extension could place it in the middle of the label. I'm leaning towards calling this 'as-designed'.

**Comment by misolori** [comment]
I would also say that this is `as-designed` as you can have varying icons be part of the same category and that would look really odd. It's easier to scan the category and then to the item.
