### ISSUE TITLE
toggleQueryDetails does not work in the new Search Editor

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#89536]
I am trying to add a keybinding to show the search advanced options, like this:

```json
{
    "key": "ctrl+shift+j",
    "command": "workbench.action.search.toggleQueryDetails",
    "when": "searchViewletVisible || inSearchEditor"
},
{
    "key": "ctrl+shift+j",
    "command": "-workbench.action.search.toggleQueryDetails",
    "when": "searchViewletVisible"
}
```

This is the same behavior as in the search viewlet: the key binding continues to work but it does not have any effect in the new Service Editor

@JacksonKearl 
Reference [#88154](https://github.com/microsoft/vscode/issues/88154#issuecomment-579323179)

**Comment by JacksonKearl** [comment]
`workbench.action.search.toggleQueryDetails` will now work in search editor with no change to keybindings needed.
