### ISSUE TITLE
Panel and viewlet position is reset after closing and opening workspace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89532]
https://github.com/microsoft/vscode/issues/89384

Version: 1.42.0-insider (user setup)
Commit: c4b6a6b537de49a734d0eedea06152ea37dfdb6a
Date: 2020-01-28T05:38:41.922Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

Before:

![image](https://user-images.githubusercontent.com/2193314/73288569-16c0b900-41b0-11ea-933a-12551992c229.png)

Close window, open recent workspace:

![image](https://user-images.githubusercontent.com/2193314/73288590-1fb18a80-41b0-11ea-9111-2dd6f6a6e7c8.png)

After reload:

![image](https://user-images.githubusercontent.com/2193314/73288598-24763e80-41b0-11ea-8e34-b4f2edce1790.png)

**Comment by sbatten** [comment]
no luck reproing this, maybe i am misunderstanding the steps?

**Comment by Tyriar** [comment]
Was happening 100% for me in the office, not on my home Windows desktop though 🤷‍♂ 

Can see if it's still happening when I'm in next if you want?

**Comment by sbatten** [comment]
yea, i'm not sure what's happening so if your desktop can repro that'd be great
