### ISSUE TITLE
LLDB debug adapter needs to know when the user triggered explicitly a completion in the Debug Console

### ISSUE THREAD

**Issue by a20012251** [microsoft/vscode#89531]
**Context**

Performing a completion request in the Debug Console for LLDB is very expensive because it very often needs to invoke the compiler to figure out the correct symbols to show. 
For context, in the normal LLDB CLI, it only autocompletes when the user presses TAB, which is fine and the user knows this can take a while. This establishes a well-defined contract with the user. 
On the other hand, on VSCode, the IDE sends a completion request to the debugger whenever the user types a character (except for some few exceptions). This is very heavy for LLDB and might make it hung up for many seconds and lock the entire debugger, blocking the user from debugging.

**Solution**

The solution is to perform a completion only when the user explicitly requests it with a CTRL-SPACE, providing the same experience as the LLDB CLI. 

The existing completion request structure, defined in CompletionsArguments https://microsoft.github.io/debug-adapter-protocol/specification doesn't have a field providing this information. 
The actual solution would be to have VSCode append a field to this structure indicating if the request was manually triggered by the user.

I'm happy to do the entire implementation, btw.

**Wrong ideas**

An idea I had to discard was comparing successive requests, and assuming that a request was manually triggered by the user if it's the same as the previous one. However, this doesn't work if the user performs the following action:

 - [assume there's a variable 'var1' in the scope]
-  user types 'var'
- a request is sent with 'var' as text
- user deletes r
- no request is sent. This is how VSCode works
- user types r
- a request is set with 'var' as text, which is the same as the previous request but was not manually triggered by the user.

Another idea I discarded was having VSCode send a completion request whenever the text field in the Debug Console changes, instead of the current behavior, which is most of the times the user types something. The downside is that this might brake existing debug adapter, which is a no go.

This feature is fundamental to providing a great experience to our LLDB users.

Any thoughts? :)

cc: @diazhector98 @kusmour

**Comment by kusmour** [comment]
I think it would be a good idea to keep the same behavior as LLDB CLI, since the frequent auto completion is expensive and could harm the actual debugging experience. Also, considering current behavior doesn't cover the case where users delete the input, it could be confusing to users.

**Comment by jrieken** [comment]
In the API (not LSP) there is the  [CompletionContext](https://github.com/microsoft/vscode/blob/35148678abd445851bcc07768b8d6c0f61826d51/src/vs/vscode.d.ts#L3537) which tho might not help you further. Suggestions-as-you-type (aka quick suggestions) is a user preference so it would be awkward to allow providers to play against that. The simplest I can think of is a language-specific default setting that your extension sets for your language which disables quick suggestions. 

This is completions inside the debug console, not "normal" editor, right? @isidorn what language is used there? Is that under control of the extension?

**Comment by a20012251** [comment]
That link is interesting and it's good to see that LSPs have already such feature :)

> This is completions inside the debug console, not "normal" editor, right?
Yes, it's inside the debug console. 

I think that as long as the debug adapter gets the completion context, it can make its own decision on when to suggest completions. Besides, debug adapter could programmatically change their behavior based on a flag in their launch.json configs, which will leave the completion logic entirely inside the debug adapter code.

**Comment by isidorn** [comment]
@jrieken no the language inside the debug console is not in control of the extensions. We just use the language of the active editor. [Code pointer](https://github.com/microsoft/vscode/blob/fecf73f7bd2a61d8717443026f993f9f42824562/src/vs/workbench/contrib/debug/browser/repl.ts#L245)

**Comment by jrieken** [comment]
> @jrieken no the language inside the debug console is not in control of the extensions. 

That's then required to get this to work, otherwise quick suggestions cannot be tuned for a certain language


@a20012251 re https://github.com/microsoft/vscode/issues/89531#issuecomment-579659265

> That link is interesting and it's good to see that LSPs have already such feature :)

What I tried to say is that we don't have this because we want users of IntelliSense to have the same experience no matter how IntelliSense has been triggered.

**Comment by a20012251** [comment]
If I understood correctly, this means that a new language should be created for the console, right?
That would give a good amount of flexibility to the debug adapter and the user

**Comment by a20012251** [comment]
Btw, I was inspecting VSCode itself and noticed that the CompletionKind is always 0, unless it's triggered by pressing ".". It seems currently VSCode doesn't differentiate ctrl-space cases vs normal on-type completion, which should be fixed as well.

**Comment by jrieken** [comment]
>It seems currently VSCode doesn't differentiate ctrl-space cases vs normal on-type completion, which should be fixed as well.

Next attempt in saying what I wanted to say [here](https://github.com/microsoft/vscode/issues/89531#issuecomment-579651916) and [here](https://github.com/microsoft/vscode/issues/89531#issuecomment-580736491): We do not want this, we have no plans in change that because users should always get the same IntelliSense, no matter how it has been triggered
