### ISSUE TITLE
Token inspector hover doesn't reflect disabling semantic highlighting

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89548]
Testing #89351

Notice the foreground is given as #0094f0, which is the blue shade it would be with semantic highlighting enabled. but semantic highlighting is disabled, so it should be the actual color. 
![image](https://user-images.githubusercontent.com/8586769/73296990-96a24f80-41bf-11ea-8034-d37a0dba9d91.png)

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/commit/5384095ee9283dd58ec14bff54e3a9715980d731

**Comment by aeschli** [comment]
To verify:
- set `"editor.semanticHighlighting.enabled": false`
- open a TypeScript file, select a type identifier, open `Inspect Editot Tokens and Scopes...`
- verify that these's no section about semantic tokens
