### ISSUE TITLE
Double title bar after opening VS Code

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89543]
![image](https://user-images.githubusercontent.com/2193314/73295406-78872000-41bc-11ea-8e35-823b6048567f.png)

This is what I was doing:

1. Installed Docker for Windows and restarted Windows
2. Opened Insiders

That's the window that greeted me. This only seemed to affect the foreground window not the others, which happened to be the only WSL remote window.

**Comment by sbatten** [comment]
@Tyriar  does you wsl workspace have any special configuration with the titlebar?

**Comment by Tyriar** [comment]
@sbatten as in remote settings? That's empty.

**Comment by sbatten** [comment]
looking at the code path for this, the one thing I could think this could be is if the configuration service gives us the wrong value at startup (the default value i would guess) and later gives the right one. this shouldn't happen, but its the only way to actually show the titlebar part that I can see. is it possible that settings sync changed the values during start up?

**Comment by Tyriar** [comment]
@sbatten I doubt settings sync would be the culprit as I changed that setting a long time ago and have only added new machines (and overwritten local).

**Comment by sbatten** [comment]
I don't think it would be because you changed the setting, I'm curious if there is some new loading logic that could give intermediate incorrect results for configurations.
