### ISSUE TITLE
The terminal process terminated with exit code: 4294901760

### ISSUE THREAD

**Issue by PaauloGuilheerme** [microsoft/vscode#89547]
Issue Type: <b>Bug</b>

Problem has been detected yesterday without a specific reason

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
android-emulator-launcher|343|0.9.0
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
emulate|Die|1.3.0
python|ms-|2020.1.58038
vscode-icons|vsc|9.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Some questions:

- Does this happen every time you open a terminal? When does it happen if not?
- Do you have anti-virus/malware software installed?
- Please also share your settings.json file.
