### ISSUE TITLE
Refactor with preview doesn't support live preview

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#89545]
Issue Type: <b>Bug</b>

Re #89335

* Put cursor on the first line
* F2
* Modify the content and press shift+enter
* Focus goes into the panel, rename dialog dismisses and I can no longer make updates any more.

![Kapture 2020-01-28 at 10 57 24](https://user-images.githubusercontent.com/876920/73295764-298dba80-41bd-11ea-9e85-2c15e459fa53.gif)

VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:34:51.242Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.18GB free)|
|Process Argv|-psn_0_7632711|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.0
vscode-pull-request-github-insiders|Git|2020.1.32642
vscode-language-pack-zh-hans|MS-|1.42.0
remote-ssh-edit-nightly|ms-|2020.1.38400
remote-ssh-nightly|ms-|2020.1.38400
debugger-for-chrome|msj|4.12.6

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yes - that's how it is designed to work. It says "Shift+Enter to preview" and that's what it does. Is the label unclear or what is the issue here? Did you forget to add expected/actual outcome?

**Comment by rebornix** [comment]
I was expecting the same experience as Xcode, which supports live preview when doing refactoring.

**Comment by jrieken** [comment]
Ah, understood. Yeah, that's something we have been talking about here, but more like its with html-tag rewriting today. Haven't seen this in Xcode but I believe live preview should only work inside a single file, right?

**Comment by rebornix** [comment]
It works across files too in Xcode and the way it presents multiple files is pretty close to the Refactor Preview panel, that's why I expect the live preview to work 

![Kapture 2020-01-30 at 9 59 00](https://user-images.githubusercontent.com/876920/73476496-33dbc000-4347-11ea-9d24-1d21c5867865.gif)

To some extent, the UI looks closer to the Search Editor @JacksonKearl works on. cc @octref

**Comment by octref** [comment]
The issue here is our API is:
```ts
provideRenameEdits(document: TextDocument, position: Position, newName: string, token: CancellationToken): ProviderResult<WorkspaceEdit>;
```
Not:

```ts
provideRenameRanges(document: TextDocument, position: Position, token: CancellationToken): ProviderResult<{ uri: Uri, range: Range }[]>;
```

If the widget stays open after Shift+Enter, and sends rename requests for each value change, we can achieve the XCode effect, but the requests/responses could be slow.

Or we can add a new API for rename providers that do not care about a new name, and only calculate the uri+ranges that should be renamed.

**Comment by jrieken** [comment]
Yeah - that's pretty cool. The main motivator for working on this is language services that are too slow to compute a correct result and that can result un-verified, text-based results.
