### ISSUE TITLE
Can't rename TS 3.8 private fields

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#89542]
- VSCode Version: 1.42 Insiders
- OS Version: Windows 10

Found will testing #89387

Steps to Reproduce:

1. Create a private field (`#name: string`).
2. Try to rename (F2) the symbol.

Get a message "You cannot rename this element".

![image](https://user-images.githubusercontent.com/12818376/73295150-08789a00-41bc-11ea-986f-0dfa2a84aa02.png)

You can rename 'name' -> '#name' but can't rename after changed to '#name'.

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/36481 to track upstream
