### ISSUE TITLE
[Shadow DOM] can not focus editor with mouse in Edge (chromium)

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#89540]
Issue Type: <b>Bug</b>

re #89392

Browser: Microsoft Edge 
OS: macOS

* Open http://127.0.0.1:8080/monaco-editor/test/shadow-dom.html?editor=src
* Focus the editor
* Switch to another application and then switch back
* You can now see the blinking cursor
* Move the cursor with mouse, now the cursor is hidden
* The editor is now in a weird state where you can type, but keybindings like delete, cmd+a don't work.

![Kapture 2020-01-28 at 10 26 22](https://user-images.githubusercontent.com/876920/73293396-abc7b000-41b8-11ea-927a-baa43763f9d3.gif)

**Comment by alexdima** [comment]
I'm sorry about that, I think this was totally broken by https://github.com/microsoft/vscode/commit/6172a30ba563d8043e14f4c8713c97a0272f5c6e that I pushed yesterday as a fix for another issue.
