### ISSUE TITLE
Slightly strange that one timeline provider can remove the entire view for others

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#89558]
Testing https://github.com/microsoft/vscode/issues/89385

When one provider is taking a while to provide results, the entire view becomes empty with the loading message. I could imagine this leads to flicker and is also annoying if the one you want is already loaded.

**Comment by eamodio** [comment]
Yeah, I'm planning to add a cache for at least the current Uri, so that way one provider won't really affect the others -- but right now it is very naive.
