### ISSUE TITLE
Private Fields: Avoid strict prefix match

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#89556]
Testing https://github.com/microsoft/vscode/issues/89387.

```ts
class Square {
    #sideLength: number;

    method1() {
        side<CARET>
    }
}
```
When invoking completions at <CARET> I'd expect to get  `#sideLength` as the first match, but it's not listed at all.

**Comment by mjbvz** [comment]
Fixed by 58fe34bb77aae5b596559d6dfe3cb81772e1dfca

Note that all of the following  should not insert `this.#xyz`

```js
class A {
  #xyz = 1;

  foo() {
    xy|
    #xy|
    this.xy|
    this.#xy|
  }
}
```
