### ISSUE TITLE
Suggestion detail close button can overlap with content

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#89554]
Issue Type: <b>Bug</b>

**Repo**
1. In an extension  `package.json`
    ```json
	"contributes": {
		"configuration": [
			{
				"title": "hello",
				"properties": {
					"hello.test": {
						"type": "string",
						"description": "hello Test lang config",
						"scope": ""

					}
				}
			}
		]
	},
    ```

1. Trigger suggestions in `scope`

**Bug**
The little suggestion details close icon (the `X` in the top right corner) overlaps slightly with the text content

![Screen Shot 2020-01-28 at 11 43 34 AM](https://user-images.githubusercontent.com/12821956/73299299-c81d1a00-41c3-11ea-9171-e925ad7ac9c0.png)

VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:34:51.242Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.19GB free)|
|Process Argv|-psn_0_1913299|
|Screen Reader|no|
|VM|15%|
</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest
