### ISSUE TITLE
Certain log output channel only show up in the first vscode window

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89559]
Issue Type: <b>Bug</b>

First window:
![image](https://user-images.githubusercontent.com/641685/73305964-3b855280-41e9-11ea-9bc2-08d82ca31dcd.png)

Any window after the first:
![image](https://user-images.githubusercontent.com/641685/73305982-44762400-41e9-11ea-9a8c-a7c94f0e506d.png)

VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:38:41.922Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.55GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
@eamodio Cant reproduce this. Any specific steps?

**Comment by eamodio** [comment]
Hrm, seems to work fine if you open a new window from inside vscode, but if you do it from outside (via taskbar button) then it always reproduces for me.

**Comment by sandy081** [comment]
Does the command `Toggle Shared Process` works for you on the second window?

**Comment by eamodio** [comment]
Yeah, both open:
![image](https://user-images.githubusercontent.com/641685/73429424-a9c13680-4309-11ea-8e31-844ae79e5d79.png)

**Comment by sandy081** [comment]
@bpasero Is there anything special if opening a window from taskbar that the environment is not set correctly?

**Comment by bpasero** [comment]
@sandy081 I think we try to fetch the shell environment later on:

https://github.com/microsoft/vscode/blob/2548906f4c2d4f5c5a1e59af79aa7ba5cbe74244/src/vs/code/electron-main/app.ts#L262

**Comment by joaomoreno** [comment]
The env only runs when Code starts. If another instance of Code comes along, it just talks to the first one. No further env resolution happens.

**Comment by sandy081** [comment]
@eamodio Can you please help in debugging this and find the root cause? 

Here is the code pointer where we register the output channels for the log files - 

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/logs/common/logs.contribution.ts#L48

Please check if the channels are getting created?

**Comment by sandy081** [comment]
Right, we create the channel only after file is created. But in this case the logs which were missing shall have files exist as they shall be same for all windows.

> But I'm not sure why the file Uri is different (or at least I'm assuming it is, since it doesn't exist)

Can you please let me know what the URIs are ?

**Comment by eamodio** [comment]
@sandy081 It looks like the timestamps are different.

First window:
```
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T165027/userDataSync.log
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T165027/renderer1.log
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T165027/main.log
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T165027/sharedprocess.log

2nd window:
```
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T194923/userDataSync.log
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T194923/renderer3.log
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T194923/main.log
file:///c%3A/Users/Eric/AppData/Roaming/code-oss-dev/logs/20200612T194923/sharedprocess.log
```

**Comment by sandy081** [comment]
Thanks @eamodio. This `logPath` is read from `IEnvironmentService` and on window this is read from process env. It seems this process env variable is not set for second window.

https://github.com/microsoft/vscode/blob/99a07407c8ffc992cfabe475fef5d72471529de5/src/vs/platform/environment/node/environmentService.ts#L268-L276

@bpasero Your help is appreciated.

**Comment by bpasero** [comment]
@sandy081 very unlikely that a value you put into `process` in one window ends up on the `process` object of another window. I am not sure I follow what you are trying to achieve here, I suggest you call me once available to talk it through and you can show me the code.

**Comment by sandy081** [comment]
This value is put into process in electron main and I assume that all windows shall get this value?

**Comment by bpasero** [comment]
Yes it should.

**Comment by sandy081** [comment]
@eamodio Can you please keep break point in the following code and let me know if the `process.env['VSCODE_LOGS']` value is set or not?

https://github.com/microsoft/vscode/blob/99a07407c8ffc992cfabe475fef5d72471529de5/src/vs/platform/environment/node/environmentService.ts#L268-L276

**Comment by sandy081** [comment]
It seems `VSCODE_LOGS` env is not being set in other windows environment and these windows are trying to set different logPath as of main and hence these windows are missing application level logs (shared process, main, sync).

After discussing @bpasero suggested to pass `logsPath` to other windows including shared process as window configuration instead through environment.

@joaomoreno any opinions as you came up with this pattern and not sure if there is any other reason.

**Comment by joaomoreno** [comment]
> It seems `VSCODE_LOGS` env is not being set in other windows environment and these windows are trying to set different logPath as of main and hence these windows are missing application level logs (shared process, main, sync).

Do we know why it's not being set?

**Comment by sandy081** [comment]
Sorry I did not know why, @bpasero do you have any clue?

**Comment by bpasero** [comment]
@sandy081 again, please move away from using process environment for this purpose, it asks for trouble. 

The issue is this:
* you open a first window and it sets `VSCODE_LOGS` path accordingly as environment
* you open a second window from the command line
  * we explicitly want all of `process.env` of this second window to reach that window because a user might have configured some environments that need to travel to other processes such as extensions
  * the second window is a fresh process and thus will set a `VSCODE_LOGS` again that is different from the main one
  * the fresh process communicates to the first process and sends over the environment to use
  * that second window opens with the logs folder that is different from the first

**Comment by bpasero** [comment]
To further debug, check this line which sends the process environment over:

https://github.com/microsoft/vscode/blob/8d699df76bc54aedda370574acd2ccfe945bad96/src/vs/code/electron-main/main.ts#L313

Deleting `VSCODE_LOGS` from the environment is a hacky workaround, but a proper fix should be made.

**Comment by sandy081** [comment]
@bpasero 

> @sandy081 again, please move away from using process environment for this purpose, it asks for trouble.

Yes, I am in that process. Since @joaomoreno added this, checking with him to know any special reasons for doing this.

**Comment by joaomoreno** [comment]
Process environment is _usually_ the least friction route: it requires no code to have environment variables propagate across spawned processes.

**Comment by rzhao271** [comment]
Still happens for me on both stable and insiders on Windows

0. Not sure if this step is necessary: close open folders and editors
1. Open VS Code Insiders from taskbar/start menu
2. Toggle panel, go to Output panel, check channels
3. Repeat steps 1 and 2 again

When running those steps with Insiders, the second window for me has 3 log options, whereas the first window has 6.
