### ISSUE TITLE
Insiders binaries are inside 1.2.1 stable release

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#8956]
Both 32 and 64 bit **stable** packages for 1.2.1 are suspiciously big:

![image](https://cloud.githubusercontent.com/assets/22350/16691827/86a22d6c-452e-11e6-8a49-770325337d85.png)

Looking inside one, I found an **insiders** binary:

![image](https://cloud.githubusercontent.com/assets/22350/16691829/8b5789c4-452e-11e6-8061-16e4fd3e8b04.png)

**Comment by joaomoreno** [comment]
Does not seem to have happened to 1.3.0

**Comment by Tyriar** [comment]
No issue then because 1.3.0 is fine? I ran `gulp vscode-linux-x64` and doesn't produce 2 binaries also.
