### ISSUE TITLE
Save and restore current view when VS Code restarts

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#89569]
Testing #89291

Version: 1.42.0-insider
Commit: 2f5acf960db667602c58d8e950bb38f945de27df
Date: 2020-01-28T14:52:14.496Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-76-generic

**Repo**
1. Open VS Code
1. Switch to debug view
1. Exit VS Code 
1.Reopen VS Code

**Bug**
We switch back to the explorer instead of restoring to the debug view

(note that the view restores properly for me when the side bar is collapsed )

**Comment by bpasero** [comment]
This is as designed ever since the @chrisdias lobby got active years ago. We only restore views on reload.
