### ISSUE TITLE
LSP list of semantic token modifiers differs from vscode

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#89564]
Testing https://github.com/microsoft/vscode/issues/89347

https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.sematicTokens.proposed.ts#L48

should be consistent with 

https://github.com/microsoft/vscode/blob/master/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L401

- No `definition`, `reference` and `volatile` (but can be discussed)
- `deprecated` has a typo in the enum value
- `final` should be `readonly`

**Comment by dbaeumer** [comment]
Thanks @aeschli . When I created the list I noticed that some of them are not defined. I think we should make a pass in Feb to ensure that we have a consistent set of tokens in VS Code and LSP.

**Comment by dbaeumer** [comment]
Fixed `deprecated` and `final`

**Comment by dbaeumer** [comment]
@aeschli how do we want to continue on this? I would suggest to add `definition` and `reference` since we have `declaration`. I am open with volatile. I thought about folding it with `async` but it carries a different semantic.

**Comment by aeschli** [comment]
Everything is a reference, so I wouldn't want to add that as a modifier to everything.
We can add `definition`, but there hadn;t been a demand yet from TS or C++. I would also wait with `volatile` until there's more that one user for it.
Language servers can always define their own types and modifiers.

**Comment by dbaeumer** [comment]
OK. I will remove `references` then. I will keep definition because it looks very unbalanced in LSP now that I added all that definition / declaration support. VS Code will simply not announce it. I will also keep `volatile` since we have `async` and I know that Eclipse had support for `volatile` (LSP is not VS Code only). Objections?

**Comment by aeschli** [comment]
I personally think `volatile` is too special. Let's add it when it is really used, by more than one language.
We can remove `async` to keep things simple.

**Comment by dbaeumer** [comment]
OK. Then I remove volatile and async.

**Comment by dbaeumer** [comment]
Done. Will close the issue for now.
