### ISSUE TITLE
Dom-based wrapping: long words don't wrap

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#89571]
Testing https://github.com/microsoft/vscode/issues/89389.

1) Enable line wrapping by setting it to `bounded`
2) Type a single number that is longer than the viewport/wrap column
-> when using `dom` for wrapping than there is no wrapping while in `monospace` the line is wrapped; this is not only true for numbers but also for strings of ascii characters. When using Chinese however, wrapping is working fine.

This screenshot shows three lines

![image](https://user-images.githubusercontent.com/4674940/73313232-7d110000-41df-11ea-9cdc-685a7c3bac7f.png)

What I also realize is that for most font families (such as Source Code Pro or Courier or AppleGothic), the last 2-4 characters of such long numbers (when no line is longer) are not revealed in the viewport neither by scrolling nor while moving the cursor with the arrow keys. 

The line below end on `0` and the viewport is scrolled all the way to the right:

![image](https://user-images.githubusercontent.com/4674940/73313292-b34e7f80-41df-11ea-9a0c-6e05cb465318.png)

**Comment by sana-ajani** [comment]
Trying on Windows machine, I set line wrapping to "wordWrapColumn", wordWrapColumn to "100", and the algorithm setting to "dom" and using characters, numbers, or in Arabic (RTL), there is no wrapping. 

![image](https://user-images.githubusercontent.com/9721254/73319388-1c8abe80-41f1-11ea-9046-e49486c87ead.png)
