### ISSUE TITLE
Custom views don't move in all windows

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89579]
Testing #89384

have two windows open. In one of them, attempt to move a full page view (i.e. github pull requests) to panel. It works. In the other window however it stays in sidebar, and clicking on it opens an empty view. Seen in dev tools:

![image](https://user-images.githubusercontent.com/8586769/73319374-0ed53900-41f1-11ea-9431-3890657d5ca8.png)

Update: this also applies with custom views non-full page. they appear blank in the secondary window and dont appear in panel

**Comment by rebornix** [comment]
@sbatten did we disallow moving view containers? I can't move GHPR if it's in its own container.

**Comment by sbatten** [comment]
@rebornix you should be able to move it as long as you have the setting `workbench.view.experimental.allowMovingToNewContainer` set
