### ISSUE TITLE
Better fallback on extension command contributions that use icons

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#89574]
Testing #89361

If you have a command that uses Codicons via `$(icon)` like:

![image](https://user-images.githubusercontent.com/35271042/73314058-ab8fda80-41e1-11ea-9b13-158e6da7733b.png)

The context menu shows the text:

![image](https://user-images.githubusercontent.com/35271042/73314076-bb0f2380-41e1-11ea-8f3b-253e45352e23.png)

IMO, we should strip out the codicon reference in the context menu since it's not supported there. Otherwise authors have to duplicate commands.

**Comment by sandy081** [comment]
Instead is it possible to support codicons in context menu?

**Comment by sbatten** [comment]
@misolori codicons are just part of our font, yes? meaning we'd have to fallback to some emoji in the native menus which would probably look out of place.

**Comment by misolori** [comment]
Correct that native menus would not be able to support it (we could hide it) but in the custom menu we could show it since it's part of our font. But I worry that it might cause inconsistencies across menus.

**Comment by sandy081** [comment]
We will also have inconsistency if we do not show complete label. I think this issue is same for all context menu actions that can be contributable. Leaving it to @sbatten

**Comment by sbatten** [comment]
I think it should be stripped to be consistent.

**Comment by sbatten** [comment]
@misolori Since you created the issue, can you try your test extension to verify?

**Comment by misolori** [comment]
Verified this works 👍

![image](https://user-images.githubusercontent.com/35271042/76018642-4365a000-5ed5-11ea-97f2-a98768fbd8b9.png)

![image](https://user-images.githubusercontent.com/35271042/76018632-3e085580-5ed5-11ea-8f3e-c607796cf1b4.png)
