### ISSUE TITLE
Configured debug type 'pwa-chrome' is not supported. 

### ISSUE THREAD

**Issue by Fab2295** [microsoft/vscode#89578]
- VSCode Version: 1.41.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Debugger fro Chrome installed
![image](https://user-images.githubusercontent.com/19378313/73318062-04c63100-4217-11ea-8d91-0fbf469c90f2.png)

3. launch.json 
![image](https://user-images.githubusercontent.com/19378313/73318039-ed874380-4216-11ea-8b83-a8fdf56912e9.png)

4. Error debugging 
![image](https://user-images.githubusercontent.com/19378313/73318005-d9dbdd00-4216-11ea-8bb6-a29e0a84ebb4.png)

**Comment by connor4312** [comment]
@Fab2295 do you have debug.chrome.useV3 or debug.javascript.usePreview on on your settings? If these are, then we will try to redirect to our new preview debugger, which you don't have installed.

/needsMoreInfo

**Comment by connor4312** [comment]
Okay, please be sure you have `js-debug-nightly` as well as `debugger-for-chrome` installed.

**Comment by Fab2295** [comment]
Thanks, it’s working

**Comment by connor4312** [comment]
Ok, thanks for the confirmation.
