### ISSUE TITLE
Search Editor: Line numbers show on recovered editors after restart

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89584]
![image](https://user-images.githubusercontent.com/8586769/73329668-5a004380-4213-11ea-9be6-c62535a54738.png)

this should be reflecting the "[search-editor]" configuration.

**Comment by JacksonKearl** [comment]
Built Insiders off of 8d497960d7 and does not reproduce.

**Comment by joaomoreno** [comment]
Actually I do see the line numbers for a few milliseconds before they hide. I wonder if we can improve that?
