### ISSUE TITLE
Custom views moved to panel don't appear anywhere after extension disabled then enabled

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89580]
Testing #89384

Take GHPR, move to panel. Disable extension. Reload. Enable. No "reload required" displayed, but the view is nowhere to be seen until reload.

Similar for moving a single non-full page view to panel, the others will reappear in sidebar, but the view moved to panel requires a reload to appear

**Comment by sbatten** [comment]
fyi @sandy081 
sadly, just running the `onDidRegisterExtensions` callback when `onDidChangeExtensions` fires doesn't work because it happens before the views are registered. the commit makes view registration smarter where it can generate containers if needed, but it does so carefully.

**Comment by sandy081** [comment]
Ok. will take a look. 

I would recommend to write tests for `ViewsDescriptorService` given it's logic is growing - https://github.com/microsoft/vscode/issues/89686

**Comment by sandy081** [comment]
@sbatten Please tag the views specific issues with `workbench-views` so that they can be easily tracked.
