### ISSUE TITLE
Settings are automatically changed on startup

### ISSUE THREAD

**Issue by BartTK** [microsoft/vscode#89586]
To easily distinguish multiple open windows of VSCode, I give them a distinct title bar color. In order to do that, I use project specific settings.json files. Such a file only sets the title bar background:

```
{
    "workbench.colorCustomizations": {
        "titleBar.activeBackground": "#970000",
    }
}
```

When I close and re-open VSCode, it automatically updates the complete color scheme. The settings.json file now looks like this:

```
{
    "workbench.colorCustomizations": {
        "activityBar.background": "#ca0000",
        "activityBar.activeBorder": "#004000",
        "activityBar.foreground": "#e7e7e7",
        "activityBar.inactiveForeground": "#e7e7e799",
        "activityBarBadge.background": "#004000",
        "activityBarBadge.foreground": "#e7e7e7",
        "titleBar.activeBackground": "#970000",
        "titleBar.inactiveBackground": "#97000099",
        "titleBar.activeForeground": "#e7e7e7",
        "titleBar.inactiveForeground": "#e7e7e799",
        "statusBar.background": "#970000",
        "statusBarItem.hoverBackground": "#ca0000",
        "statusBar.foreground": "#e7e7e7"
    },
    "peacock.color": "#970000"
}
```

### Expected behaviour
When I change a single color, I expect only that color to change. When I open VSCode, I do not expect it to automatically change a valid project settings file.

### Actual behaviour
On startup, VSCode automatically makes undesired changes to a valid settings.json file.

### Steps to reproduce
Create a project using the first settings.json file. Close and re-open VSCode. Several colors and the settings.json file have changed.

### Version info
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
What extensions do you have installed?

**Comment by BartTK** [comment]
Apparently the 'Angular Essentials' extension instals 'Peacock' as a dependency. That 'Peacock' extension was messing with the color settings. Disabling that plugin fixed the issue.
