### ISSUE TITLE
Cannot debug node v6.3.0 when files resides on a subst drive

### ISSUE THREAD

**Issue by Loghorn** [Microsoft/vscode#8958]
- VSCode Version: Code - Insiders 1.4.0-insider (4b84f6d791203e71fee10537f27fc8add9357160, 2016-07-08T07:45:28.445Z)
- OS Version: Windows_NT ia32 10.0.14383

Steps to Reproduce:
1. create a new folder (e.g. `C:\test`)
2. run `subst X: C:\test`
3. open the root of drive `X:` in VSCode
4. create a new javascript file with some code (a simple `console.log(__dirname)` will do)
5. configure VSCode to start the file you just created
6. set a breakpoint in the file
7. start debugging
8. PROBLEM: the breakpoint is never hit.

This is related to nodejs issue [#7294](https://github.com/nodejs/node/issues/7294)

**Comment by joshgav** [comment]
See https://github.com/nodejs/node/pull/7559 for work on fixes.

/cc @bzoz
