### ISSUE TITLE
VS Code Login Feature

### ISSUE THREAD

**Issue by AbiMahmood** [microsoft/vscode#89589]
The login feature is so much needed in VS Code so that if I install the VS Code in my other PC, it will automatically install all my settings, preferences and especially all my extensions. 
Please add this feature in VSCODE

**Comment by joaomoreno** [comment]
This is actively being worked on: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asettings-sync+milestone%3A%22January+2020%22
