### ISSUE TITLE
"The terminal process terminated with exit code: 64" on calling for a new terminal with pwsh due to `invalid argument "-l"` on OSX

### ISSUE THREAD

**Issue by kazurayam** [microsoft/vscode#89582]
**My environment**

- macOS Catalina 10.15.2
- Visual Studio Code 1.41.1
- PowerShell 6.2.4

**Incident**

I had `/Users/myname/Library/Application Support/Code/User/settings.json` as
```
{
    "terminal.integrated.shell.osx": "/usr/local/bin/pwsh"
}
```

When I did Code Toolbar Terminal>New Terminal, it failed to open a new terminal with error message "The terminal process terminated with exit code: 64" as shown in the following screenshot:
<img width="821" alt="スクリーンショット 2020-01-29 13 32 18" src="https://user-images.githubusercontent.com/4467417/73328079-d0e11f00-429b-11ea-9d7a-c85e632bd69e.png">

I could see the following output:
```
Invalid argument '-l', did you mean:

  -nologo
  -noprofile
  -windowstyle
  -file
  -executionpolicy
  -settingsfile
  -help
  -removeworkingdirectorytrailingcharacter
```

**My workaround**
I changed the settings.json as follows:
```
{
    "terminal.integrated.shell.osx": "/usr/local/bin/pwsh",
    "terminal.integrated.shellArgs.osx": []
}
```

Then I could open a new Terminal with pwsh.

**Discussion**
- Having `-l` as a commandline option for bash is OK, but not for pwsh.  
- In settings.json adding a line of `"terminal.integrated.shellArgs.osx": []` is tricky, should not be required.

**Comment by Tyriar** [comment]
We can't really fix this until we get something like this: https://github.com/microsoft/vscode/issues/45444, a shell selector with various profiles will eventually link both args and executable as we could automatically detect pwsh and handle it like that.

/duplicate
