### ISSUE TITLE
Too long path of an extension side effects in Windows flipping to TEMP user profile

### ISSUE THREAD

**Issue by stic** [Microsoft/vscode#8959]
- VSCode Version: 1.2.* and 1.3
- OS Version: Win7
- User: User with a roaming profile

Steps to Reproduce:
0. Have an Windows user with a roaming profile
1. Install VS Code
2. Make sure that your .vscode got created within profile
3. Install extension with a bit too long path, i.e. lukehoban.Go-0.6.39 will do
4. From now on 
   * in your profile might be already corrupted (logout might take longer or on login you will get TEMP profile)
   * upon login, in Event Viewer, you should see something along the lines of
Windows cannot copy file \\?\UNC\SOMESERVER$\profile$\SOMEPROFILE\.vscode\extensions\lukehoban.Go-0.6.39\node_modules\console-stamp\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-expression-parse\node_modules\spdx-license-ids to location \\?\C:\Users\SOMEPROFILE\.vscode\extensions\lukehoban.Go-0.6.39\node_modules\console-stamp\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-expression-parse\node_modules\spdx-license-ids. This error may be caused by network problems or insufficient security rights. 

 DETAIL - The filename or extension is too long.

I suppose it's related to #3884 as having extensions outside profile or even in AppData wouldn't cause such issue?

**Comment by joaomoreno** [comment]
Interesting. Yeah #3884 might end up fixing, but each extension can also improve by installing their dependencies with npm 3 which flattens the directory structure much more than 2. Can you file an issue on https://github.com/Microsoft/vscode-go as well?

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.
