### ISSUE TITLE
Installing extensions using the CLI is not working

### ISSUE THREAD

**Issue by MarcJefferson5** [microsoft/vscode#89590]
- VSCode Version: 1.41.1
- OS Version: Windows 10 Build 17134

Steps to Reproduce:

1. Open command prompt
2. code --install-extension ms-vscode-remote.remote-containers
3. Extension 'ms-vscode-remote.remote-containers' not found.

**Comment by sandy081** [comment]
It works for me. Are you able to see this extension with this id when you open Code?
