### ISSUE TITLE
Do not make requests if sync files are too large

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89597]
Settings Sync Server rejects if the resource is too large. This is to discuss if we have to prevent them already from the client side

@Tyriar FYI

**Comment by Tyriar** [comment]
Seems obvious that we should do this now imo as it was a cause for concern when I saw the data in shoot up to > 300x more than normal; why request and waste server time when we know it will be rejected by simply measuring the length of content on the client?

**Comment by sandy081** [comment]
Remember it was testing and there is a bug on the client to stop sync. So not sure if that is a good heuristics.

**Comment by Tyriar** [comment]
@sandy081 sure, but this will get hit when millions of people are using it. Moving the validation to the client means less traffic on the server, more stable servers, less compute and a faster response to the user. What's the downside when it's a simple conditional with a throw in VS Code?

**Comment by sandy081** [comment]
How do I know what is the max limit that a server can support?
