### ISSUE TITLE
Sync Settings UI: Quickpick UI comes at its limits...

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89595]
Refs: #89358

When turning on Settings Sync, I get this QuickPick UI:

![2020-01-29_11-40-48](https://user-images.githubusercontent.com/1898161/73350181-da16bf80-428c-11ea-84bb-5526c446d2eb.png)

The dominance of the filter text box is a bit confusing since there is no need for it in this 4-option case.

**Comment by sandy081** [comment]
Fixed:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/10746682/93517070-38cb9f00-f92b-11ea-8e57-33ade5d8bcb6.png">

**Comment by sandy081** [comment]
Check and verify the simplified above quick pick UI while turning on Settings Sync

**Comment by isidorn** [comment]
I have verified that you now use the quick pick with no input -> adding verified label.
But is it just me that the `Sing in & Turn On` button uses a weird font? @chmarti
