### ISSUE TITLE
Have shortkey Ctrl + D for duplicating line

### ISSUE THREAD

**Issue by Gregory-GIT** [microsoft/vscode#89592]
Issue Type: <b>Feature Request</b>

Hello,
It will be great to have the shortkey Ctrl + D for duplicating line as common other apps for coding.
regards
Greg

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kanlukasz** [comment]
VS Code has its own shortcut concept. 
`Ctrl + D` is used for something different

You can just change it using https://code.visualstudio.com/docs/getstarted/keybindings

PS. That what you looking for is used by:
![obraz](https://user-images.githubusercontent.com/30685349/73349664-e64e4d00-428b-11ea-9c0f-99ab52b34a77.png)

**Comment by Gregory-GIT** [comment]
Wonderful !
