### ISSUE TITLE
'Move to Panel' missing from Outline

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#89594]
Issue Type: <b>Bug</b>

Testing #89384

Based on the instructions I expected to see a context menu option for moving it to the Panel:

![image](https://user-images.githubusercontent.com/6726799/73349926-f9f5b580-4283-11ea-84c3-af523282ec64.png)

That option **does** appear for Search:

![image](https://user-images.githubusercontent.com/6726799/73349989-1bef3800-4284-11ea-9a71-3d78f28942a5.png)

Happens even after I reload with all extensions disabled.

VS Code version: Code - Insiders 1.42.0-insider (be9c72410acc677070685a616773b122f4c5e141, 2020-01-29T05:39:07.145Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sbatten** [comment]
@gjsjohnmurray you have the latest build with the new setting to gate this feature for stable. `"workbench.view.experimental.allowMovingToNewContainer": false`. Please set to true and thanks for testing.

**Comment by gjsjohnmurray** [comment]
Thanks @sbatten, that fixed it for me.
