### ISSUE TITLE
Search should respect .gitignore in subdirectories

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#89591]
When using Search with the option `Use Exclude Settings and Ignore Files` enabled, it does not respect .gitignore files in subdirectories. I would expect this is how it should work.

**Comment by roblourens** [comment]
This works for me, can you give some more details about your setup?

**Comment by thernstig** [comment]
@roblourens I am certain this did occur, as I have seen it before, but I cannot recreate. Your immediate reaction might be that I did something incorrectly thinking I .gitignored something, but that is not the case.

I think this might be some race condition/intermittent fault that can happen. Basically I was building some assets with WebPack to a directory we .gitignore, where the .gitignore file itself is in a subdirectory (think like <root>/client/ where client is a webapp). At some point when doing search, I found results in the output directory that was ignored.

I am still going to close this, but at least someone might stumble upon this in the future and can provide more input if they experience the same.
