### ISSUE TITLE
Improve wording in sync settings UI

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89598]
Refs: #89358

The last checkbox item "UI State Display Language (only)" is a bit confusing:

![2020-01-29_12-00-27](https://user-images.githubusercontent.com/1898161/73351381-295def80-428f-11ea-95ba-9f7468a63195.png)

If I understand correctly the message to convey here is "At the moment only the Display Language setting is synced".  

I suggest to change the wording to something like this:

`UI State ('Display Language' only)` or
`UI State (only 'Display Language' for now)`

**Comment by sandy081** [comment]
Thanks @weinand  for suggestion. Changed:

![image](https://user-images.githubusercontent.com/10746682/73351687-db95b700-428f-11ea-805e-4a85530abe45.png)
