### ISSUE TITLE
InputBox with auto suggest

### ISSUE THREAD

**Issue by edsu** [microsoft/vscode#89601]
In my VSCode extension I would like to be able to create an [InputBox](https://code.visualstudio.com/api/references/vscode-api#InputBox) with auto suggest functionality. So as a user types in the InputBox, a list of possible values appears below which the user can select from. It seems like this must be done elsewhere in VSCode but I can't seem to find an example. Or does the functionality not exist in the API?

**Comment by edsu** [comment]
@vscodebot I was wondering if QuickPick and InputBox could somehow be used together, but I couldn't seem to find an example of that.

**Comment by edsu** [comment]
@vscodebot thanks for the info ... I didn't realize this was a missing feature. I thought for sure there had to be an example of an auto suggest input somewhere in VSCode.

**Comment by edsu** [comment]
Hmm, here's an example from the Python extension that allows you to select the interpreter and to filter the list with an input box. I wonder if that's a good example of how to do this?

https://github.com/microsoft/vscode-python/blob/master/src/client/interpreter/configuration/interpreterSelector.ts

**Comment by edsu** [comment]
Well, I feel silly. It looks like showQuickPick already allows input with an autosuggest. Sorry for the noise.

**Comment by edsu** [comment]
Never mind, I see that I cannot enter a new value in the box. I have to select one of the supplied suggestions. So the feature request stands.

**Comment by chrmarti** [comment]
You could use `createQuickPick` and then update the first entry to be what the user already typed. Pressing Enter would accept that first entry.

**Comment by edsu** [comment]
@chrisbenti thanks, that's a great idea! If you have a snippet example of the best way to do that it would be super helpful to me. But if not I'll give it a try and update this ticket for others who are looking to do something similar.

**Comment by edsu** [comment]
@chrisbenti that actually worked nicely, thanks for the idea! If anyone else is interested you can find my use of `createQuickPick` in a plugin [here](https://github.com/edsu/anselm/blob/master/extension.js#L45-L62).
