### ISSUE TITLE
Issue on hover inspect variables

### ISSUE THREAD

**Issue by AlencarGabriel** [microsoft/vscode#89603]
- VSCode Version: 1.41.1 (system setup)
- OS Version: Windows_NT x64 10.0.17763

Hello, I would like to know how to resolve this situation that occurs in inspect variables hover.

My language has a particular construction, where some types of variables have parentheses. Ex .: `(cAlias)`.

However, the hover inspect doesn't seem to understand this construction, so it follows the demonstration of the problem.

It's possible send to VsCode a regular expression for example that would make it recognize this syntax so that hover inspect works as expected?

Steps to Reproduce:

- Inspection that works. Hovering the mouse over `TMP_MODEL`:
![image](https://user-images.githubusercontent.com/10109480/73353939-3a990300-4273-11ea-94e4-eb7a02927ab5.png)

- Inspection that doesn't work. Hovering the mouse over `ZCN_MODEL`:
![image](https://user-images.githubusercontent.com/10109480/73353965-4d133c80-4273-11ea-861e-d12189fa91e0.png)

- Inspecting the expression:
![image](https://user-images.githubusercontent.com/10109480/73353976-57353b00-4273-11ea-8cdc-f973f4832abe.png)

It is possible to notice that he does not interpret the `(cAlias)->ZCN_MODEL` syntax in Hover Inspect by highlighting the expression.

Does this issue occur when all extensions are disabled?: not applicable.

**Comment by gjsjohnmurray** [comment]
When #89084 arrives a debug provider will be able to solve this.

**Comment by AlencarGabriel** [comment]
Grateful for the attention. I will be following the next releases then to implement as soon as the feature is released.
