### ISSUE TITLE
Settings Sync: apply merge failed because of "sync.enable" setting

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89602]
Refs: #89358

- on linux I enabled settings sync for the first time (and there were no questions asked)
- on macOS I enabled settings sync for the first time (and I was asked whether to replace or merge local settings with cloud)
- I reviewed the changes in the diff editor and made some changes
- I pressed "Apply" which resulted in this notification:
  ![2020-01-29_12-15-54](https://user-images.githubusercontent.com/1898161/73352558-a8542780-4291-11ea-92aa-3f057d7ef5b6.png)
- I dismissed the notification and pressed "Apply" again
- diff editor closed and everything was ok.
- I reviewed the user settings and It seems that the `"sync.enable": true` setting was the new setting that made the merge operation fail (I did not see that setting in the original diff editor).

I wonder whether we can hide failed merge operations for the "sync.enable" setting because they are expected and it doesn't make sense to have the user merge them manually.

BTW, the wording in the error notification "... a new local version is available" sounds a bit strange. With that wording I would expect that you ask me next whether I want to use that new version. But there is no such question and the diff editor doesn't show or highlight the new version either. So I do not really know what to do and pressed "Apply" which made the error disappear. If this is the only thing I can do, VS Code could hide the problem completely and do the "Apply" automatically.

**Comment by sandy081** [comment]
> But there is no such question and the diff editor doesn't show or highlight the new version either.

I think the diff editor should show the new version. Can you please check if this is not the case?
