### ISSUE TITLE
onDidOpenTextDocument triggers two times if opened

### ISSUE THREAD

**Issue by peni4142** [microsoft/vscode#89605]
- VSCode Version: 1.41.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. clone repo: https://github.com/peni4142/br-onDidOpenTextDocumentTriggersTwoTimes
2. debug 'Run Extension'
3. do the seven steps of todo.txt
- change me
- save me
- close me
- have a look on debug console
- open me via source control
- have a second look on debug console
- recognize the event triggered two times, one time uri.scheme: "file" and the second time with the 
- uri.scheme: "gitfs"

My problem is I can't figure out if the event `onDidOpenTextDocument`  is triggered by source control or not. Because if it is triggered by source control the first time the params are the same as it is opened by the explorer.

**Comment by jrieken** [comment]
Yes - that's because two documents get opened when one gets displayed. That's because git keeps the original version around to be able to do inline diff'ing etc

**Comment by zacanbrcom** [comment]
Hello @jrieken , I'm facing the same issue and I am not agree with your reply.
Reading the LSP specification from the official documentation is written that: 

> ... An open notification must not be sent more than once without a corresponding close notification send before. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didOpen

Moreover in other IDE that support the protocol (Theia as example) I am not facing this issue, the didOpen is invoked just once.
For me make sense that the client should send only one URI to the server, so I think this behavior should be clarified and the issue reopened.

**Comment by jrieken** [comment]
This has nothing to do with LSP, this is VS Code specific
