### ISSUE TITLE
View > Reopen With feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#89604]
Refs: https://github.com/microsoft/vscode/issues/88426

![image](https://user-images.githubusercontent.com/900690/73354863-046d7a80-4297-11ea-8227-1d5c398460be.png)

**Two things:**
* the command should have a "..." at the end
* the command should probably be discoverable from the editor too, not just the command palette. Why not put it into the editor title "..." menu?

**Comment by mjbvz** [comment]
Thanks for the feedback! I'll look into these in February

**Comment by bpasero** [comment]
I would probably put it to the end:

![image](https://user-images.githubusercontent.com/900690/75259805-e426d200-57e8-11ea-8911-00bbe7402443.png)
