### ISSUE TITLE
Allow semantic token styles with undefined foreground and styles 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#89600]
When we style semantic tokens, some style properties (foreground, bold, italic, underline) can be undefined.

- when ColorTheme.getTokenStyleMetadata uses `ColorId.None` as foreground, we want the foreground of the underlying TextMate tokens to be used.
- we need to extend the API to express that bold, italic, underline are set, not set or undefined.

**Comment by alexdima** [comment]
Here is a good sample:

* `sample.ts`:
```ts
class A {
    
}
```

* `settings.json`
```json
	"editor.tokenColorCustomizationsExperimental": {
		"class": { "fontStyle": "underline" }
	},
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "entity.name.type.class.ts",
				"settings": { "foreground": "#FF0000" }
			}
		]
	}
```

* when having `"editor.semanticHighlighting.enabled": false`:
![image](https://user-images.githubusercontent.com/5047891/73361131-9b8cff00-42a4-11ea-9348-555167e7ef06.png)

* when having `"editor.semanticHighlighting.enabled": true`:
![image](https://user-images.githubusercontent.com/5047891/73361083-857f3e80-42a4-11ea-9c20-6f929cd5470a.png)

Ideally, the color would be taken from the TM token (red) and the underline should be taken from the semantic token.
