### ISSUE TITLE
Working icon stuck on gear menu

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89607]
When I got in this morning the gear menu is stuck on the working icon on all 6 windows I had opened.

![image](https://user-images.githubusercontent.com/2193314/73360059-fc8de600-4256-11ea-9af1-2d7e97aa0bb5.png)

Version: 1.42.0-insider (user setup)
Commit: c4b6a6b537de49a734d0eedea06152ea37dfdb6a
Date: 2020-01-28T05:38:41.922Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by sandy081** [comment]
@Tyriar Is this the time where server is taking too much time to respond?

**Comment by Tyriar** [comment]
@sandy081 nope, I think everything was fine

**Comment by sandy081** [comment]
Unfortunately I cannot repro this.

If you can repro, can you please provide following info

- Tooltip message
- If it is related to sync, provide me the sync logs.

**Comment by Tyriar** [comment]
👍 I have doubts I'll see this again but will give better diagnostics if I see it again.
