### ISSUE TITLE
rg.exe is downloading from OneDrive

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#89615]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Enable "Files on Demand" and see the files in ![image](https://user-images.githubusercontent.com/7588612/73363634-1c1f2000-42e4-11ea-8728-b6791ad046fd.png) status

   ![image](https://user-images.githubusercontent.com/7588612/73363241-563bf200-42e3-11ea-8f7e-dbfbaf16b09d.png)

2. Open a OneDrive folder with VSCode (I opened a subfolder in File Explorer with the right-click menu and "Open with Code")
3. See notification "rg.exe is downloading from OneDrive" at the right bottom corner of the screen

   And files are ![image](https://user-images.githubusercontent.com/7588612/73363738-44a71a00-42e4-11ea-955e-f3cbc8842ccf.png) now.

Does this issue occur when all extensions are disabled?: I think so

**Comment by roblourens** [comment]
If you start a search in vscode, then rg.exe will touch all files in your workspace and onedrive will download them. If you aren't searching manually, then some extension is probably triggering a search. Does this explain it?

**Comment by yzhang-gh** [comment]
> If you aren't searching manually, then some extension is probably triggering a search.

You are so right! It is [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) that downloads all the files.

Many thanks.

**Comment by roblourens** [comment]
FYI, this might be fixed in tomorrow's Insiders, via BurntSushi/ripgrep#1657
