### ISSUE TITLE
Sync or Ignored settings should be hidden completely in the sync settings UI

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89610]
Refs: #89358

My setup:
- on macOS I've disabled "syncing extensions"
- on linux I'm syncing everything

After changing some other setting on macOS I got a conflict on linux and was asked whether I want to resolve the problem in the diff editor.

In the diff editor I was seeing not only the expected setting "editor.multiCursorModifier" but I saw the "sync.enableExtension" too:

![2020-01-29_14-33-15](https://user-images.githubusercontent.com/1898161/73361395-2b32ad80-42a5-11ea-97ab-c4101e376c8e.png)

After talking to @sandy081 I learned that "sync.enableExtension" is actually a machine-specific setting that should not be synced at all.
And what I saw was actually confirming this: on the left hand side (server) I saw "sync.enableExtension" from macOS and on the right hand side (linux) I did not see "sync.enableExtension" because I did not change this setting in any way.

However since I'm seeing a difference for this value, I'm assuming a conflict (which is actually not there).
 
I suggest that all machine-specific settings should be completely hidden from the sync UI because they just result in unnecessary noise in the diff editor.

This should probably apply for the "sync.enable" setting as well (because it is machine specific and its value can only be true if the sync setting diff editor is active).

**Comment by sandy081** [comment]
Ignored settings are now not shown in the conflicts preview to avoid confusion and  make it simple to understand the diff. Also changed the action button labels to `Accept Remote` and `Accept Local` 

![image](https://user-images.githubusercontent.com/10746682/73875086-f39fa480-4854-11ea-9858-b224c0132117.png)


@bpasero FYI
