### ISSUE TITLE
The “left” “right” “center” label in Open Editors take too much space

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#8961]
If you split your editor (which is common when using a wide screen), two rows are used.
Maybe you can replace text labels with a horizontal line.

**Comment by bgashler1** [comment]
**UX meeting notes**
We will address this issue in a future overhaul of how we handle global commands throughout the product, as well as some refinements to our debugging experience.
Please see UX meeting notes in #9506 for more info.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
