### ISSUE TITLE
Call hierarchy lacks detail

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89616]
re https://github.com/microsoft/vscode/issues/89386

* use ts3.8-beta
* show callers of [mergeSort](https://github.com/microsoft/vscode/blob/a47886c5daa748b413fefbf45acb82c0700b2c7d/src/vs/base/common/arrays.ts#L94)
* the callers are shown without any detail making it hard to understand/process the information

<img width="1270" alt="Screenshot 2020-01-29 at 15 14 00" src="https://user-images.githubusercontent.com/1794099/73364070-2de3d180-42aa-11ea-93cc-fb4c4bd4e171.png">

**Comment by jrieken** [comment]
@mjbvz This is typescript that needs to provide this information

**Comment by mjbvz** [comment]
@jrieken just to clarify, you mean showing the file path for all entries?

**Comment by jrieken** [comment]
I would expect to see the "container", e.g the class that contains a function, or the module, or the file path

**Comment by mjbvz** [comment]
Thanks for the clarification. I've opened https://github.com/microsoft/TypeScript/issues/37061 to track this request upstream
