### ISSUE TITLE
IPC: IPCServer should be able to provide channels which communicate to any client

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89614]
Let's make the `router` parameter optional:

```
getChannel<T extends IChannel>(channelName: string, router?: IClientRouter<TContext>): T {
```

This means what:

- `routeCall` goes to *any* client
- `routeEvent` goes to *every* client which is connected at any given point in time, this is a dynamic collection of clients

---

Use case: Shared process would like to listen to storage change events.

**Comment by joaomoreno** [comment]
Another idea: let's do it on top of the channel server.

**Comment by joaomoreno** [comment]
@sandy081 can you verify?
