### ISSUE TITLE
[semantic][typescript] Add private/protected to TS semantic tokens

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89619]
* have a TS file with private fields
* there is no semantic information about that, e.g I cannot style private fields different

**Comment by alexdima** [comment]
@aeschli I would really like to have this, as I want to move away from using `_` for private properties. But I guess we don't own this anymore?

cc @hediet

**Comment by jrieken** [comment]
>  as I want to move away from using _ for private properties.

👀

**Comment by jrieken** [comment]
I would guess that eventually we migrate onto the native `#` syntax

**Comment by alexdima** [comment]
> I would guess that eventually we migrate onto the native `#` syntax

I really dislike that syntax :) . My brain always takes a pause when reading that.

**Comment by jrieken** [comment]
Me neither but I guess we need to get used to it. TypeScript doesn't emit the native syntax for `private foo` even when the target supports that. There is also supple differences between `private foo` and `#foo` where the former cannot be re-used in a subclass while the latter can

**Comment by hediet** [comment]
@jrieken off-topic, but can private fields be easily debugged? I love to use the Debug Console to read private fields. This does not seem to be possible for #-fields:

![image](https://user-images.githubusercontent.com/2931520/121002917-2e895380-c78d-11eb-89f4-b0fc3bacf779.png)

**Comment by jrieken** [comment]
Looks like the debugger can do this: `class Foo { #foo = 1233; constructor() { this.#foo = 333; debugger; } }`

<img width="180" alt="Screen Shot 2021-06-07 at 13 08 49" src="https://user-images.githubusercontent.com/1794099/121006745-8cb83580-c791-11eb-91a0-6410a871d694.png">

**Comment by aeschli** [comment]
Yes, TypeScript own semantic highlighting now.
I created https://github.com/microsoft/TypeScript/issues/44483 to avoid moving the off-topic comments. 

Please subscribe there.
