### ISSUE TITLE
No callers of/call from for certain elements

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89611]
re https://github.com/microsoft/vscode/issues/89386

* TS 3.8.0.dev-20200128
* trigger call hierarchy on `createModelReference` here https://github.com/microsoft/vscode/blob/0955af14012180993aeffa1bb8fb8b40ef3faf12/src/vs/workbench/contrib/bulkEdit/browser/bulkEditPane.ts#L326
* 🐛 nothing in either direction...

**Comment by mjbvz** [comment]
Seems like another case of https://github.com/microsoft/TypeScript/issues/36509
