### ISSUE TITLE
Properly apply aria-label to editors

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#89621]
As @bpasero points out
We use
`this.editorContainer.setAttribute('aria-label', this.computeAriaLabel());`

But we actually do not update the editor options ariaLabel property at all. Neither from group changes nor from label changes. In fact I think we are computing the aria label twice: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/textEditor.ts#L97

**Comment by bpasero** [comment]
I can look into this and also remove the change I did for updating the aria label on each change.

**Comment by bpasero** [comment]
The ARIA label for untitled is back to the form of "Untitled-<N>". In addition, changing groups will now properly update the ARIA label for the editor container as well as the editor widget itself.

**Comment by bpasero** [comment]
**Verification:** 
* untitled editors should read as "Untitled-N" to screen readers independent of their content
* editors should read out their group name only if more than one group is opened

**Comment by isidorn** [comment]
Thanks Ben. I will verify this once we have the insiders build out.

**Comment by bpasero** [comment]
@isidorn can you verify and set the label? Thanks!

**Comment by isidorn** [comment]
Works great, adding verified label. Thanks!
