### ISSUE TITLE
"Remove Folder from Workspace" option not present if parent folder only contains a single subfolder

### ISSUE THREAD

**Issue by RM-Eric** [microsoft/vscode#89625]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add a folder to workspace that only contains a subfolder
2. Right clicking either the parent folder or child subfolder
3. "Remove folder from workspace" option is not present

![image](https://user-images.githubusercontent.com/59585041/73372429-d11df200-427c-11ea-9657-f1ca459cf916.png)

![image](https://user-images.githubusercontent.com/59585041/73372315-9e73f980-427c-11ea-83e5-b6669bc125ed.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/87772
