### ISSUE TITLE
Settings data is requested twice in a row during a sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89626]
Related: https://github.com/microsoft/vscode/issues/89623

First request:

![image](https://user-images.githubusercontent.com/2193314/73372603-5c42bc00-426c-11ea-94dc-49c3b10d759f.png)

Second request:

![image](https://user-images.githubusercontent.com/2193314/73372631-64026080-426c-11ea-8f63-606709035bf9.png)

**Comment by sandy081** [comment]
This should be fixed by https://github.com/microsoft/vscode/issues/89628
