### ISSUE TITLE
Use current keyboard layout at startup time to determine key bindings

### ISSUE THREAD

**Issue by ppanhoto78** [microsoft/vscode#89620]
Issue Type: <b>Bug</b>

I have two different keyboards configured in my system (Kubuntu 19.10) -- and I am using either one keyboard or another. I am happy with default keybindings for each of those layouts.

Then the problems begin: if I am using VS Code when it's preconfigured for one layout, the key bindings do not work properly for the keyboard I am using. Tried to restart VS Code and with the after changing the current layout and it had no effect. The only way to get VS Code properly configured for the desired layout was to making it the default layout in the system (move it up until it's the top).

It would be good enough if VS Code configured its default keybindings based on what is selected at startup time.

Thanks

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-24-generic

**Comment by alexdima** [comment]
Have you seen https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings ?

![image](https://user-images.githubusercontent.com/5047891/73395010-f6434c80-42de-11ea-829a-ff37d4acd728.png)

**Comment by ppanhoto78** [comment]
Yes, this is KDE on Ubuntu. Thanks.
