### ISSUE TITLE
When PC sleeps settings sync seems to require sign-in again

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89629]
Refs: #89358

This has happened a few times so far both on Windows and Mac, where after the pc sleeps for a bit sometimes settings sync is turned off and requires signing in again.

**Comment by RMacfarlane** [comment]
Related to https://github.com/microsoft/vscode/issues/89200

**Comment by eamodio** [comment]
This happens to me at least once a day (sometimes multiple times). Pretty much anytime my PC sleeps for more than an hour or so (something around there, but I've never timed it) I have to re-sign in to sync.

**Comment by roblourens** [comment]
Fixed for you right @eamodio?

**Comment by eamodio** [comment]
Yup, haven't seen it since the fix.
