### ISSUE TITLE
Enable timeline view to move between sidebar and panel

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#89633]
Issue Type: <b>Feature Request</b>

I think the new timeline view (#84297) would benefit greatly from being able to move to the panel (#85164), particularly because the Git commit messages it's already displaying stand a good chance of being wider than the typical sidebar.

/cc @eamodio, @sbatten 

VS Code version: Code - Insiders 1.42.0-insider (be9c72410acc677070685a616773b122f4c5e141, 2020-01-29T05:39:07.145Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sbatten** [comment]
@gjsjohnmurray thanks for the feedback. this aligns with our current mindset of enabling all views to be movable. since you have already referenced the larger item above, I will close this as a duplicate to be tracked there.

**Comment by gjsjohnmurray** [comment]
Good to see https://github.com/microsoft/vscode/commit/d05b78490f04d66d05a856f57169f724d7679049 and I look forward to try moving Timeline to the panel with next Insiders.
