### ISSUE TITLE
When multi-line editing the window won't scroll with the cursor position if it goes off the page.

### ISSUE THREAD

**Issue by CrocodileDunDooDoo** [microsoft/vscode#89634]
- VSCode Version: 1.41.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open up some code in a window with word-wrap DISABLED.  In this example I have a basic HTML fragment open - some Tables with links and images inside of them to be specific.
2. Make sure the code is long enough on several different lines that it runs off the page / viewport.
3. Hold ALT and click on several of those lines in the exact same spot (over 90% of each of the lines I'm editing at once are identical code-wise).
4. Use your keyboard to move the cursor to the right side until it is off the page.

Viola!  The cursor has officially escaped the matrix and is now plotting with some random code chunks to overthrow our power!

Does this issue occur when all extensions are disabled?: YES.  HURRY THE MACHINES ARE TAKING OVER!

**Comment by alexdima** [comment]
Let's track in #6995
