### ISSUE TITLE
Extensions are merged instead of replaced when user chose to overwrite

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89630]
After discussion, this tracks the issue that extensions are getting merged instead of replaced when user chooses to overwrite.

<details>
<summary>Old Description</summary>

Refs: #89358 

Originally from: https://github.com/microsoft/vscode/issues/89358#issuecomment-579574853

On my PC I turn off sync and had it delete all of the cloud data and turn off sync for all my machines. I then went over to my mac, and there were sync errors in the logs (not authorized), and sync thought it was still on.

I then restarted vscode to see if it would change, but nothing changed and there were still sync errors (not authorized). So I turned sync off, and then uninstalled all of the disabled extensions (I believe there were 4 of them). Then I went back to my PC, and turned sync back on and then turn it back on on the mac as well.

But instead of it syncing the disabled extensions from my PC to the mac, it uninstalled those same extensions from my PC!

I assume this was some timing issue because of the network errors, but it was not good. Especially since I had chose the option to turn off sync everywhere and deleted the cloud data... but somehow it still either left data or sync'd after that.

</details>

**Comment by sandy081** [comment]
@eamodio When you turned on sync on your PC (on which you turned off completely) did you see a first time sync prompt?

**Comment by eamodio** [comment]
On the PC no (since it was the 1st computer), but I don't remember seeing it on the Mac (2nd computer) that time.

**Comment by sandy081** [comment]
If it was the first computer, I am wondering how did the extensions got uninstalled on the PC?

**Comment by eamodio** [comment]
My guess is something like this happened:

PC: Sync's data to the cloud at time X (all is good)
Mac: Try turn off sync (even though it should have been off - as I chose to turn off sync everywhere) at X+1
Mac: Uninstall a few extensions at X+2
Because of the sync errors and it not truly getting turned off (again because of the errors) we wrote some local information that now includes deleting extensions at X+2 time
Mac: Turn on sync and re-auth -- now it attempts to sync X+2 to the cloud because it is later than X?

I could be way off (as I'm unsure of the sync details) but maybe? 😄

**Comment by sandy081** [comment]
> Mac: Turn on sync and re-auth -- now it attempts to sync X+2 to the cloud because it is later than X?

Yes. There is no data in the cloud and it will just push local data to cloud. (This is similar to first time sync from anywhere)

After this, if you turn sync on from Desktop you should be asked to overwrite or merge. Extensions gets uninstalled only when you select to overwrite.

Let me know if this is what happened?

**Comment by eamodio** [comment]
So we won't uninstall extensions when you just remove one from one machine while sync is on?

**Comment by eamodio** [comment]
OK, I just ran into more issues. Here's what happened:

- Sync DB was cleared last night so everything should have been wiped
- On my PC, I upgraded to today's insiders build and then I sync said I need to sign in again (since it was on prior to the DB wipe)
- I signed back in successfully (which I _thought_ meant sync was now on -- it apparently was not)
- The on my Mac, I upgraded it to today's insiders, and Turn sync on (it was off) -- and I was surprised that it didn't prompt me with the overwrite/merge prompt (but now I know that it was because my PC sync was not actually on)
- Went back to my PC and uninstalled the TSLint extension
- And expected that to be sync'd to my Mac (it never did, because my PC sync was not on but I didn't know that yet)
- Then I noticed that sync was NOT enabled on my PC, so I went back to my Mac and turn sync off everywhere deleting all the data

OK, now we are in theory back to a clean slate

- On my PC, I turned sync on
- On my Mac, I turned sync on -- and I was prompted with overwrite/merge -- I chose overwrite
- I expected TSLint to get uninstalled from my Mac at this point (since it was previously uninstalled from my PC), but this never happened
- I went back to my PC to look at the sync logs and saw that it has re-installed TSLint on my PC!

Here's the logs from my PC:
```
[2020-01-30 11:58:13.352] [userDataSync] [info] Auto sync started
[2020-01-30 11:58:13.539] [userDataSync] [info] Settings: Updating remote settings
[2020-01-30 11:58:13.798] [userDataSync] [info] Settings: Updating last synchronised settings
[2020-01-30 11:58:13.953] [userDataSync] [info] Keybindings: Updating remote keybindings
[2020-01-30 11:58:14.139] [userDataSync] [info] Keybindings: Updating last synchronised keybindings
[2020-01-30 11:58:14.284] [userDataSync] [info] UI State: Updating remote ui state...
[2020-01-30 11:58:14.447] [userDataSync] [info] UI State: Updating last synchronised ui state...
[2020-01-30 11:58:14.617] [userDataSync] [info] Extensions: Updating remote extensions...
[2020-01-30 11:58:14.788] [userDataSync] [info] Extensions: Updating last synchronised extensions...
[2020-01-30 11:59:58.615] [userDataSync] [info] Extensions: Updating local extensions...
[2020-01-30 11:59:58.829] [userDataSync] [info] Extensions: Enabling extension. ms-vscode.vscode-typescript-tslint-plugin 1.2.3
[2020-01-30 11:59:58.833] [userDataSync] [info] Extensions: Installing extension. ms-vscode.vscode-typescript-tslint-plugin 1.2.3
[2020-01-30 11:59:59.072] [userDataSync] [info] Extensions: Updating last synchronised extensions...
```

And for some reason there are no logs on my Mac (the output channel is empty)

**Comment by eamodio** [comment]
Also while I saw that TSLint was re-installed on my PC, there was nothing in the UI that indicated that -- it didn't show up anywhere in the Extensions view. But once I reloaded vscode then it showed up.

**Comment by Tyriar** [comment]
Does the overwrite/merge dialog for first time syncs only apply to settings and keybindings? It should apply to everything and uninstall extensions locally if needed.

**Comment by sandy081** [comment]
> Also while I saw that TSLint was re-installed on my PC, there was nothing in the UI that indicated that -- it didn't show up anywhere in the Extensions view. But once I reloaded vscode then it showed up.

This is an UI bug that it does not get updated. You need to switch views to get it updated.

> Does the overwrite/merge dialog for first time syncs only apply to settings and keybindings? It should apply to everything and uninstall extensions locally if needed.

I do not uninstall extensions in overwrite case, not sure if this expected.

@eamodio Sorry that it is difficult to follow up with the issue. If you don't mind can you please summarise issue(s)? Sorry for asking that.

**Comment by Tyriar** [comment]
@sandy081 I think this is a manifestation of https://github.com/microsoft/vscode/issues/89750

**Comment by eamodio** [comment]
Part of this was definitely #89750, but the other part, is that we don't seem to honor the _overwrite_ choice on sync for extensions. They are instead merged.

**Comment by sandy081** [comment]
Since part of it is being discussed in #89750 I would use this issue for extensions merging when overwriting is chosen. Probably create separate issues if you have more cases.
