### ISSUE TITLE
When opening an ipynb file without an appropriate ipynb extension, link to the Python extension in the marketplace

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode#89632]
Currently, when you open an ipynb file in VS Code without an appropriate extension, it prompts the generic marketplace suggestion.

![image](https://user-images.githubusercontent.com/15910920/73377774-72ed1100-4274-11ea-8942-1af467aaab1b.png)

The Python VS Code Extension team is looking to change the prompt to ask users to install the Python extension, like what occurs when a user opens a .py file without an appropriate extension as to promote the Notebook Editor functionality in the Python Extension for VS Code.

**Comment by chrisdias** [comment]
fixed in next insiders build
