### ISSUE TITLE
On first sync of a new machine with some disabled extensions doesn't disable them on the target right away

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89631]
Refs: #89358

During the first sync of my 2nd machine, all of my extensions from my 1st machine where brought over, but the disabled ones appeared enabled until I restarted vscode.

**Comment by eamodio** [comment]
The next time I tried this, the sync logs show it installed the disabled extension, but it didn't show up at all in the extensions view (disabled or otherwise), until I restarted vscode and then it showed up disabled as expected.

**Comment by sandy081** [comment]
Fixed here - https://github.com/microsoft/vscode/issues/89462
