### ISSUE TITLE
Add key binding condition - terminalFocus

### ISSUE THREAD

**Issue by shaneparsons** [Microsoft/vscode#8964]
Correct me if I'm wrong, but there doesn't seem to be a key binding condition for when the terminal is focused.

This makes commands like `workbench.action.terminal.focusNext` useless as you have to use the mouse to focus the editor.. defeating the purpose of the key binding in the first place.

Something along the lines of `terminalFocus` would be awesome.

- VSCode Version: 1.3.0
- OS Version: OSX

**Comment by Tyriar** [comment]
Closing in favor of #7240
