### ISSUE TITLE
Should Diagnostic Links have display text?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#89649]
Testing #89320

With the new diagnostics links, it might be worth having some other display text for the link besides the code. If the code is just `1` or some small text, the link looks strange and isn't obviously a link.

Related: we don't cap the length at all which can also look bad.

**Comment by octref** [comment]
I think having a straightforward mapping between API and rendering matters, so it's always `<a href="code.link">code.value</a>`. The underline should still make it clear it's a link. If extension authors choose short error code, we render short error code. There's no way around that.

If during adoption this does become an issue we can reconsider.
