### ISSUE TITLE
When a warning is displayed, the editor's cursor moves back

### ISSUE THREAD

**Issue by thanpolas** [microsoft/vscode#89646]
Issue Type: <b>Bug</b>

While I suffer from the known "TypeScript language service died 5 times" problem, and multiple errors and warnings pop up, one of them, is affecting my editor cursor.

When the "5 times" error, appears as a Warning, with the orange/yello colored Danger Icon, my editor's cursor moves back and makes me mistype things.

Captured animated gif sample of the issue: https://d.pr/i/Us30WG

Relative Issue with the warnings: #89638

Warnings I am refering to:

![warnings](https://cdn-std.droplr.net/files/acc_551565/zTUrmS)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 90, 95|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.15
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
cpptools|ms-|0.26.3
platformio-ide|pla|1.10.0
code-spell-checker|str|1.7.22
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by mjbvz** [comment]
Are you sure it's the notification that triggers the cursor move? Can you record a video of it happening?

**Comment by thanpolas** [comment]
Video is captured on my initial post, here it is again: https://d.pr/i/Us30WG

**Comment by mjbvz** [comment]
#96338 is the possible root cause of this

**Comment by mjbvz** [comment]
@thanpolas  Let me know if you still see this and if there are any additional repro steps
