### ISSUE TITLE
Reset local sync state when turned off

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89648]
Reset local sync state when turned off

@misolori FYI

**Comment by misolori** [comment]
Do you still need me to log an issue or does this cover it?

**Comment by sandy081** [comment]
This covers it. 

Please verify it in tomorrow's insiders

**Comment by misolori** [comment]
Verified it works!

[image](https://user-images.githubusercontent.com/35271042/73471033-9d56d100-433d-11ea-9227-f3563bcb840b.png)
