### ISSUE TITLE
Call Hierarchy view overview ruler overlaps SCM and caller decorators

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#89644]
- VSCode Version: 1.42 Insiders
- OS Version: Windows 10

Found while testing #89386

1. Make a change such as add some new callers.

The green SCM addition region overlaps with the caller decoration.

![image](https://user-images.githubusercontent.com/12818376/73387300-383fa480-4285-11ea-8469-7a0d3d04471f.png)

**Comment by jrieken** [comment]
Closing this without any change. Looking at our related usages like word highlights or find matches shows that all "discovery" highlights are rendered in the center-lane. With all of them there is potential for overlap and the other alternative is to not have any ruler highlights at all
