### ISSUE TITLE
Why I have it so slow?

### ISSUE THREAD

**Issue by jack-fdrv** [microsoft/vscode#89659]
Here the video
https://src.fdrv.guru/slowvscode.mp4

I have this list of extantions, and I need all of them.
![image](https://user-images.githubusercontent.com/4230282/73396869-f5181c80-42ea-11ea-9fd3-891c26c99ada.png)

Any suggestion how I can sped up it?

**Comment by joaomoreno** [comment]
To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue
