### ISSUE TITLE
Bad acting save participant can still block save

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89654]
Refs: #89330

Given the example code in #89330, where you have a save participant that doesn't properly cancel (e.g. resolve/reject) its promise. That save participant still blocks the file save even when the user hits the cancel button. I only see the dirty indicator change on the file, when the `10000` is up. And if I change the code to resolve the promise if the token is cancelled then the save happens immediately after hitting the cancel button.

**Comment by jrieken** [comment]
We cannot control what happens on the extension host but the file should be saved...

**Comment by jrieken** [comment]
This is a great catch 👏

**Comment by IbrahimCanKALYA** [comment]
this error occures also without any extensions  in  vsCode version 1.42.0 but we downgrade version to 1.41.1 then everythinks fine there no format on save error

**Comment by tashbenbetov** [comment]
Also have this problem
