### ISSUE TITLE
No debug adapter found

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89658]
Issue Type: <b>Bug</b>

While debugging VS Code (using the `Debug VS Code Main, Renderer & Extension Host` config), I sometimes see this error:

![image](https://user-images.githubusercontent.com/641685/73395343-4f928800-42ad-11ea-9bf1-f50fd1bc3561.png)

![image](https://user-images.githubusercontent.com/641685/73395328-49041080-42ad-11ea-99b6-1774b883a85a.png)

I think it is related to the extension host dying (or restarting and the debugger loses connection to it).

Here is the debug adapter log: [vscode-debugadapter.zip](https://github.com/microsoft/vscode/files/4130623/vscode-debugadapter.zip)

VS Code version: Code - Insiders 1.42.0-insider (be9c72410acc677070685a616773b122f4c5e141, 2020-01-29T05:39:07.145Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.15GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Eric/code/microsoft/vscode|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
@connor4312 @roblourens can you guys first look into this, it seems like the debug adapter goes down. Thanks

**Comment by ws93** [comment]
Can someone look into this? We have an internal VS Code extension that also has this issue. It first happened in VS Code 1.39(or 1.38 I don't remember) and now it happens to 1.42.0 again.

My case is every time when I hit the Stop button then this error pops up. This is not really blocking something but just annoying.

If you have changed your api or something we would like to change our extension to make sure this works in latest version. But the error message doesn't really show any useful information.

**Comment by roblourens** [comment]
It ends with several `Lost connection to debugee, reconnecting in 10000ms` so I think we were trying to reattach to the EH process and not finding it. I tried different ways of running that config and killing the EH but don't see any issues.

@isidorn can you give us a hint about what would trigger that error? It seems like basically when vscode tries to send a DAP message but the debug adapter has stopped?

**Comment by isidorn** [comment]
@roblourens this error is coming from [here](https://github.com/microsoft/vscode/blob/b62b2280ea0ea828b898df94c43a455194639218/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L604).
It seems that it can happen if we try to send something to the `debugAdapter` and the `debugAdapter` was already stopped. I have improved this error message that we also log what command we are trying to send.
What I suspect is happening: is that the debug adapter goes down, but not 100% correctly thus VS Code does not properly clear out all DebugSession state. Because if the debugAdapter went down the DebugSession object should be inactive.

**Comment by isidorn** [comment]
From @parovbroadcom
"The problem appears when we are trying to terminate the debug session. We first use the "exited" method with the expected ExitedEventArguments and directly after that, the "terminated" method with the expected TerminatedEventArguments. The error comes from the terminated method. I repeat that the problem appeared directly when the version of VSCode was updated to 1.42. By the way this problem doesn't appear on Theia."

**Comment by isidorn** [comment]
Does somebody have exact reproducable steps? @eamodio @parovbroadcom @roblourens 
I tried reproducing this with latest vscode insdiers with starting debug and quickly stopping it but was unsuccessful in reproducing...

**Comment by ivankravets** [comment]
This bug arises a few times per year. @weinand could we have a regression test for this? We have the same problem with PlatformIO extension. Every time users stop debugging session, VSCode complains about "no adapter". See screenshot below:

![Screen Shot 2020-03-05 at 12 34 04](https://user-images.githubusercontent.com/1760209/75973364-b2df8d80-5edd-11ea-910a-92ec5026cacf.png)

**Comment by weinand** [comment]
We have decided to not throw the error if we are in "shutdown" mode (where we expect that the debug adapters goes away).

**Comment by isidorn** [comment]
Also in case you see the error again let us know it should have more detail (like the command that is about to be sent).

**Comment by ivankravets** [comment]
Thank you so much for the quick fix!!!

**Comment by connor4312** [comment]
I used to see this sometimes (never had a solid repro on it) but haven't seen it in the last month. @eamodio please unmark as verified if you think this isn't fixed.

**Comment by eamodio** [comment]
I haven't seen it in a while. :thumbsup:
