### ISSUE TITLE
Visual studio adding extra spaces on function shorthands

### ISSUE THREAD

**Issue by aymone** [Microsoft/vscode#8965]
- VSCode Version: 1.3
- OS Version: Ubuntu 16.04
- Language: JS

Steps to Reproduce:

1.Create a simple object with functions shorthand like:
```js
const x = {
    a(){}
};
```

2.Use VSCode auto format (ctrl+shift+i):
```js
const x = {
    a(){ } // why vscode add this extra space between braces?
};
```

Any way to disable this?

**Comment by dbaeumer** [comment]
Moving to TS team since the formatter comes from the tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9613
