### ISSUE TITLE
vscode-docker extension should not be special-cased in product.json

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode#89657]
- VSCode Version: 1.41.1
- OS Version: (all)

product.json has an entry for vscode-docker extension that declares it to be "workspace + ui" type. This is unnecessary--the extension manifest, starting with ver. 0.10.0, already declares the extension as such. It also prevents the extension to change its declared type if it ever becomes necessary.

Please remove this override.

See https://github.com/microsoft/vscode/issues/89363 for context

**Comment by egamma** [comment]
@karolz-ms done, thanks for the heads-up.
