### ISSUE TITLE
error symbol

### ISSUE THREAD

**Issue by Rhed001** [microsoft/vscode#89656]
Issue Type: <b>Bug</b>

There is an error symbol that looks like this " ~ " that i cannot get rid of.   The code will not run because it thinks there is a syntax error when there isn't.  I have tried closing and reopenning the program and is just simply re appears.  

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz (6 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.58038
python|tht|0.2.3

</details>

**Comment by sportshead** [comment]
Try removing your extensions

**Comment by joaomoreno** [comment]
Can you show me a screenshot?

**Comment by joaomoreno** [comment]
Please come to github and attach a screenshot, otherwise we can't see it.

**Comment by Rhed001** [comment]
![2020-01-30 12_11_07-Greenshot](https://user-images.githubusercontent.com/60448378/73560003-2c3e1900-4424-11ea-8c01-176aff07882a.png)

**Comment by Rhed001** [comment]
do i close this or leave it opened?

**Comment by sportshead** [comment]
@Rhed001 This is probably because of invalid indentation. Try deleting the spaces in front of `def method` and replace them with a tab. When indenting in python, use tabs and not spaces. For more information, see [this documentation page](https://docs.python.org/2.0/ref/indentation.html).

**Comment by pandene** [comment]
@Rhed001 Can this call be closed?
