### ISSUE TITLE
Indent guide overlay text in debug console

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#89665]
Version: 1.42.0-insider
Commit: be9c72410acc677070685a616773b122f4c5e141
Date: 2020-01-29T05:35:51.712Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

---

- Have an object in debug console
- Expand and then hover over it

![image](https://user-images.githubusercontent.com/4033249/73403332-143f8b80-42a4-11ea-888e-878ef554c9b0.png)

**Comment by isidorn** [comment]
I can reproduce this, and I agree it does not make a lot of sense in the debug console.
@joaomoreno I tried  passing `renderIndentGuides: RenderIndentGuides.None` [here](https://github.com/microsoft/vscode/blob/178239097ca2ab3fbdd35db872b532ad7e32e0aa/src/vs/workbench/contrib/debug/browser/repl.ts#L466) but it seems like that option has no effect.
Seems like the tree is not respecting that option?

**Comment by sandy081** [comment]
Candidate accepted because it is a regression.

**Comment by isidorn** [comment]
Thank you. Yes it is a regression since the whole tree indent gets broken. ONly @joaomoreno noticed now, thanks a lot for that!

**Comment by isidorn** [comment]
Fixe
