### ISSUE TITLE
Emmet abbreviations do not work in “Emmet: Update tag”

### ISSUE THREAD

**Issue by kokoshneta** [microsoft/vscode#89668]
- VSCode Version: 1.41.1
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Select an HTML tag in an HTML (or PHP, ASP or any other file your Emmet settings treat as HTML) file, say a `<div>` tag
2. Choose _Emmet: Update tag_ and input something like `span.myclass`

Expected result:

The `<div>...</div>` tag changes to `<span class="myclass">...</span>`.

Actual result:

The `<div>...</div>` tag changes to the invalid `<span.myclass>...</span.myclass>`

Does this issue occur when all extensions are disabled?
Yes

(This seems like rather an obvious bug, so I was surprised I couldn’t find any previous mention of it – is my search-fu simply inadequate? Also, half the time I try to update a tag in a plain HTML file, I get the error “Overlapping ranges are not allowed” – this doesn’t seem to happen in PHP files.)

**Comment by octref** [comment]
Emmet itself doesn't seem to have this action. You can only input tag name over there.
