### ISSUE TITLE
Can't configure user task to be default build task

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89663]
Testing https://github.com/microsoft/vscode/issues/89343

- Add user task
- "Configure default build task", pick the user task
- Nothing happens

I think it makes sense that it can't be a default build task, so maybe it should be filtered out of that list.

**Comment by alexr00** [comment]
Great find, thank you!

**Comment by alexr00** [comment]
I enabled configuration of default test and build tasks for user tasks and workspace file tasks.

**Comment by joaomoreno** [comment]
@alexr00  Seems to work now, but setting it as default removes all the comments in the task's properties.

**Comment by alexr00** [comment]
That's not great. It also happens in stable, so no urgency to fix now. https://github.com/microsoft/vscode/issues/89774
