### ISSUE TITLE
User tasks are mixed with workspace tasks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89662]
Testing https://github.com/microsoft/vscode/issues/89343

It says

> Verify that you can tell that it's a user level task in the task quick pick

But I can't tell that

![image](https://user-images.githubusercontent.com/323878/73400263-a3957080-429d-11ea-9666-629d9a2e10ce.png)

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/89441
