### ISSUE TITLE
The terminal gets scrambled up

### ISSUE THREAD

**Issue by Emyboy** [microsoft/vscode#89661]
![Screenshot_5](https://user-images.githubusercontent.com/34845973/73400302-28f24280-42e9-11ea-8719-33e3fe277036.png)
The terminal gets scrambled up after few hours of coding. especially when I have to vs code open.

**Comment by Tyriar** [comment]
Looks like a problem with canvas, you can try updating your graphics driver and if that doesn't work disable the canvas renderer with this setting:

```
"terminal.integrated.rendererType": "dom"
```
