### ISSUE TITLE
Integratel Terminal doesn't find commands from PATH

### ISSUE THREAD

**Issue by emzero** [Microsoft/vscode#8966]
- VSCode Version:
Version 1.3.0
Commit e724f269ded347b49fcf1657fc576399354e6703
Date 2016-07-07T16:56:12.476Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version:
Windows 7 x64 SP1

I have installed Git for Windows with both the git and Unix commands in the PATH.

VSCode doesn't seem to find the Unix commands.

![image](https://cloud.githubusercontent.com/assets/412489/16697663/2d31a8a0-4521-11e6-8d32-7b09cc3ffca3.png)

**Comment by Tyriar** [comment]
If `ls` is on `PATH`, can you print out path both the native and integrated terminal?

One of these should work:

```
echo $PATH
echo %PATH%
```

**Comment by emzero** [comment]
```
C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client
\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management
Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Co
mponents\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Pro
gram Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Wind
ows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\TortoiseGit\bin;C:\Pro
gram Files\Microsoft\Web Platform Installer\;C:\Users\Emiliano\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Fi
les\dotnet\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\Emiliano\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin;C:\Users\Emiliano\.dnx\bin
;C:\Program Files\Git\bin;C:\Users\Emiliano\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\dotnet;C:\Progra
m Files (x86)\Android\android-sdk\platform-tools;C:\Users\Emiliano\AppData\Roaming\nvm;C:\Program Files\nodejs
```

Both cmd and integrated terminal shows this. It doesn't seem accurate though since I've removed the old DNX runtines for example and they are still showing up. Will try restarting.

**Comment by Tyriar** [comment]
The integrated terminal literally runs cmd.exe and pipes data back and forth. If `ls` is not working I suspect some other trickery is going on with your cmd window like it's running inside another program or something. If your native window is git bash you need to set that up as the shell in settings, see #7286

**Comment by emzero** [comment]
Restarting the pc did the trick. Sorry!

**Comment by Tyriar** [comment]
Good to hear :+1:
