### ISSUE TITLE
Unable to download/export files from VS online explorer

### ISSUE THREAD

**Issue by EliasDallis** [microsoft/vscode#89671]
I am unable to download any files or folders that I have created in VS online. When I right click and select download it errors saying 'no file'. I tried dragging the files into VS Code offline and that didn't work either. I am using the free version, and am not sure if that's the reason this feature doesn't seem to work. I'm trying to set up some kind of way to export my files out of my environments but copying and pasting is the only way i've found so far...

**Comment by bpasero** [comment]
/duplicate https://github.com/MicrosoftDocs/vsonline/issues/292
