### ISSUE TITLE
Opening remote files in editor from the terminal

### ISSUE THREAD

**Issue by harsh-ka** [microsoft/vscode#89677]
When we connect to remote server the directory structure opens in the left section.
But if we have to open a file in the editor then we have to open the directory structure one by one which is time consuming.
There should be a way where we can just specify the file location and that file will automatically open in the editor without traversing the directory structure.
Example:
some command /path/to/remote/file/temp.txt 
will open temp.txt automatically in the editor.

**Comment by joaomoreno** [comment]
You can use Quick Open: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_quick-open
