### ISSUE TITLE
extension installing is not working in vs 

### ISSUE THREAD

**Issue by r105m** [Microsoft/vscode#8967]
- VSCode Version:
e724f269ded347b49fcf1657fc576399354e6703
- OS Version:
fedora 24

Steps to Reproduce:

1. open c# extension in new extension tab
2. press install

actual result: nothing happens
expected result: successfully installed c# extension

Steps to Reproduce 2:

1. ctrl-p
2. ext install csharp
3. enter

actual result: nothing happens
expected result: successfully installed c# extension

**Comment by gvn182** [comment]
+1

CentOS 7

**Comment by sapropel** [comment]
+1 Ubuntu 16.04

**Comment by r105m** [comment]
it works if you kill all vscode processes and remove all  vscode directories

**Comment by sapropel** [comment]
@r105m you're right it worked, but ill add that you don't need to remove all vscode directories, only the one in .cache (at least it was enough for me).

thanks.

**Comment by gvn182** [comment]
@r105m can you tell me where can i find this folder?

**Comment by sebadoom** [comment]
@gvn182 It's $HOME/.cache/Code

I can confirm this fixes the problem for me to. 

Duplicate: #8984

**Comment by r105m** [comment]
~/.vscode
~/.cache/Code
~/.config/Code

but you will loss yours  prefences

**Comment by sebadoom** [comment]
Please note that it appears that only removing the .cache/Code directory is required, so losing the user settings might not be necessary.

**Comment by iamchenxin** [comment]
@sebadoom  +1 Ubuntu 16.04 
only need to delete `~/.cache/Code`.

**Comment by TheColorRed** [comment]
Removing this folder did not work for me...

**Comment by DrakeLeung** [comment]
What about OSX ? There isn't a `~/.cache/Code`.@iamchenxin

**Comment by iamchenxin** [comment]
@DrakeLeung I haven't used osx yet.
But seems its cache directory is '~/Library/Caches' ?( [from discussions.apple.com](https://discussions.apple.com/thread/2756051?start=0&tstart=0) ).
I am not sure. get those information from `https://www.google.com/?q=osx+.cache+directory`

**Comment by iamchenxin** [comment]
@DrakeLeung In linux, vscode have some background process,which must be explicitly killed before delete the cache. Maybe OSX have some background process too.

**Comment by joaomoreno** [comment]
#8859
