### ISSUE TITLE
Rename preview list is populated from bottom to top

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89674]
Testing https://github.com/microsoft/vscode/issues/89331

- Trigger a preview for an item with lots of references, such as `IAction#run`
- The list of files shows up immediately, then it looks each files results are added top to bottom, slow enough to watch it happen
- It might look better if it's done top to bottom

![Jan-29-2020 16-21-32](https://user-images.githubusercontent.com/323878/73409277-a9964c00-42b3-11ea-923d-b78e171c810a.gif)

**Comment by jrieken** [comment]
Wow - that looks 💩 I am trying to expand all nodes of this async tree. I didn't test it for such a large refactoring.... The order is actually arbitrary.

**Comment by jrieken** [comment]
> The order is actually arbitrary.

Actually, not... 🤦‍♂ It's not first-to-last files and stops after 10 files
