### ISSUE TITLE
Can't resize with macosx app "rectangle" anymore

### ISSUE THREAD

**Issue by airtonix** [microsoft/vscode#89676]
![image](https://user-images.githubusercontent.com/61225/73417780-3c44f280-4369-11ea-88b5-13c42a7a1cd8.png)
![image](https://user-images.githubusercontent.com/61225/73417791-4b2ba500-4369-11ea-8b72-20a2bf468e07.png)

I have been using this amazing piece of free software to quickly resize and move windows around
- https://rectangleapp.com/
![image](https://user-images.githubusercontent.com/61225/73417985-df960780-4369-11ea-868f-e23ca100b709.png)

Restarted vscode and it now reports that vscode is not resizable due to all the options being greyed out:

<img width="131" alt="Screen Shot 2020-01-30 at 2 05 12 pm" src="https://user-images.githubusercontent.com/61225/73417951-cb520a80-4369-11ea-9397-40fdd08e7dc2.png">

**Comment by sportshead** [comment]
This is not a problem with VS Code. If you want troubleshooting, go [here](https://github.com/rxhanson/Rectangle/issues/new?assignees=&labels=&template=bug_report.md&title=) to contact Rectangle support directly.
