### ISSUE TITLE
Renaming can break semantic highlighting

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89673]
- Open extensionsActions.ts
- Rename the `alert` import
- Immediately press undo
- Semantic highlight colors go away and never come back for that document

![Jan-29-2020 16-13-51](https://user-images.githubusercontent.com/323878/73408840-5a035080-42b2-11ea-8150-27693f9ca14f.gif)

**Comment by alexdima** [comment]
I could reproduce on yesterday's Insiders, but I think this is also fixed by acf29319557d700472acdb2307f7eb66aec08a0e
