### ISSUE TITLE
Taskbar Icon not showing after Windows Update

### ISSUE THREAD

**Issue by aayushbisen** [microsoft/vscode#89680]
After updating to the latest windows feature update 1909 vscode taskbar icon turned into a white file icon. The insiders build has no issues.

- VSCode Version: 1.41.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363
 
Things I have tried:

1. Reinstalling vscode
2. Clearing icon cache

Does this issue occur when all extensions are disabled?: Yes

Screenshot:

![image](https://user-images.githubusercontent.com/41341387/73424907-1a8e4000-4356-11ea-992d-032c3dd1f569.png)

**Comment by joaomoreno** [comment]
Is the icon fixed if you uninstall and reinstall Code?

**Comment by aayushbisen** [comment]
After uninstalling and reinstalling code and opening any folder the vscode icon is still not showing.

**Comment by joaomoreno** [comment]
How do you clear the icon cache?

**Comment by aayushbisen** [comment]
I executed the following commands in CMD.

- cd %homepath%\AppData\Local\Microsoft\Windows\Explorer

- taskkill /f /im explorer.exe

- del iconcache*

- explorer.exe

Then I did System Restart.

**Comment by aayushbisen** [comment]
The bug was fixed after some vscode launches. We can close this issue 😄
