### ISSUE TITLE
字符显示问题

### ISSUE THREAD

**Issue by Wing-summer** [microsoft/vscode#89684]
Issue Type: <b>Bug</b>

变量窗口和监视窗口如有中文会出现乱码，望修正

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:59:13.638Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
bracket-pair-colorizer|Coe|1.0.61
code-runner|for|0.9.15
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.41.2
cpptools|ms-|0.26.3
vscode-icons|vsc|9.7.0

</details>

**Comment by joaomoreno** [comment]
Can you share a screenshot?

**Comment by Wing-summer** [comment]
OK.Here it is.

![123](https://user-images.githubusercontent.com/59953528/73434871-86869d80-4382-11ea-817e-0dc6e2d15c8e.jpg)

**Comment by Wing-summer** [comment]
When I debug  ,I define a class ,which includes myintname(int) and myname(string).When myname contains Chinese characters("小明"in this picture),in the variable window it shows unreadable characters.

**Comment by isidorn** [comment]
Please file against the cpp extension, it seems like their debug adapter is not handling chineese characters well.
https://github.com/microsoft/vscode-cpptools
