### ISSUE TITLE
Minimize functions in Python files

### ISSUE THREAD

**Issue by billmind** [microsoft/vscode#89681]
Vs code has a feature to minimise and expand all the methods in html , js and other file format but it does not support minimise and expand with a arrow in the left bar where code line numbers are shown

**Comment by sportshead** [comment]
@billmind Check again.
![https://media.giphy.com/media/QTh46bwZZOR92XrkfM/giphy.gif](https://media.giphy.com/media/QTh46bwZZOR92XrkfM/giphy.gif)

**Comment by billmind** [comment]
Sorry @sportshead  but i have never seen this 
check this please
![image](https://user-images.githubusercontent.com/58659424/73431966-abb9e280-4367-11ea-9d3f-25dbb029bd81.png)

**Comment by aeschli** [comment]
Make sure you have folding enabled: `editor.folding = true`. Also check that you are not running in Accessibility Mode. You can see this on the status bar.
Accessibility Mode is enabled when a screenreader is detected. Folding is turned off then.

**Comment by sportshead** [comment]
@billmind Follow what @aeschli suggested, then hover next to the line numbers like in my gif. You should see the arrows then

**Comment by billmind** [comment]
Sorry can't find anything specific can you please explain in more detail . I am bit new to vs code settings 
but the day i installed it , minimise doesn't work out for me

**Comment by aeschli** [comment]
Also check that you are not running in Accessibility Mode / Screen reader. You can see this on the status bar.

![image](https://user-images.githubusercontent.com/6461412/73728213-35d0c500-4733-11ea-9930-0b2610197243.png)

If you don't have a Screen Reader, click on it to disable it.

**Comment by billmind** [comment]
My bad actually my indentation was not working Due to a plugin [Anchors](https://github.com/ExodiusStudios/vscode-comment-anchors)

**Comment by billmind** [comment]
@aeschli  Can we have a inbuilt way to add those anchor or comment , atom also have this
