### ISSUE TITLE
Mismatched colors on retina display vs thunderbolt display

### ISSUE THREAD

**Issue by aflat** [Microsoft/vscode#8968]
- VSCode Version: 1.2
- OS Version: OSX 10.11.4

Steps to Reproduce: Have a document open, move it from a retina display to a thunderbolt display

The colors don't match when I move the editor from my laptops retina display to a thunderbolt display. I'm guessing it's due to electron, since the same issue is seen here

https://discuss.atom.io/t/text-color-different-on-retina-vs-thunderbolt-display/9451/12

What I can't seem to do is make the same webkit changes. So this is either a bug in electron, or a bug in VScode so I can't add those options.

**Comment by bpasero** [comment]
We should allow users to make modifications to the core CSS.

**Comment by bpasero** [comment]
@aflat  could you give our insider release a try to see if this issue is fixed? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by aflat** [comment]
It better. 
1. Dragging app from retina screen to external monitor, works
2. Editing a comment section in a file doesn't change colors anymore.
3. Opening the editor on the external monitor shows the correct colors

Only issue left is when I have the editor on the external monitor, and I switch files from the explorer view on the left. The newly selected file still has the wrong colors. Moving it to the retina screen and back to external monitor corrects the colors though.

This is without any changes in the settings.json, which I assume you didn't want me to add.

**Comment by bpasero** [comment]
@aflat how about our current 1.12 release?

**Comment by aflat** [comment]
Looks much better now, new electron seems to have fixed it, thanks
