### ISSUE TITLE
CDATA not considered appropriately in XML folding

### ISSUE THREAD

**Issue by michelecos** [microsoft/vscode#89692]
Issue Type: <b>Bug</b>

Open the sample xml included.
Note that is is a report on sections of code made by the PMD code analyser.
In particular, note that it contains a code fragment in a CDATA section that has unbalanced brackets.
Fold the code on the first <codefragment> element and note that the fold ends at the closing brackets.
Two suggested solutions:

1) condider a CDATA section as a plain text section, no matter what and disable folding inside it
2) avoid condidering a fold section end at a bracket if it started on XML markup. In an XML file, markup should prevail on minor folding sections.

Following is a sample XML file

```
<?xml version="1.0" encoding="Cp1252"?>
<pmd-cpd>
   <duplication lines="198" tokens="1096">
      <file column="35" endcolumn="62" endline="317" line="120"
            path="Packet.java"/>
      <file column="160" endcolumn="62" endline="317" line="120"
            path="Packet.java"/>
      <codefragment><![CDATA[        notify.setSendTimestamp("");
        thisAndThat();
        if ((Boolean) conditionOn(incoming)) {
            this.setConsideration(notify);
        }

        return notify;
    }
        ]]></codefragment>
   </duplication>
</pmd-cpd>
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4112 CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|47.66GB (37.77GB free)|
|Process Argv|C:\femsxs\documentation\xs_config_sql|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
rainbow-csv|mec|1.5.0
java|red|0.55.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.20.2

</details>

**Comment by michelecos** [comment]
This is the file before folding

![Folding before](https://user-images.githubusercontent.com/355198/73441493-5d024d80-4353-11ea-9219-92daa56ffc65.PNG)

This is the incorrect fold on element <codefragment>

![Folding after](https://user-images.githubusercontent.com/355198/73441508-655a8880-4353-11ea-9dd5-8d355424150b.PNG)

**Comment by aeschli** [comment]
You needs a XML extension that provides language-aware folding. Without extensions VSCode only has indentation-based folding.
Dup of https://github.com/microsoft/vscode/issues/46200
