### ISSUE TITLE
Support vs code in rhel 6

### ISSUE THREAD

**Issue by SiteshSahoo** [microsoft/vscode#89690]
It's in fact a question first then feature request.. sorry for that.
https://stackoverflow.com/questions/59982920/visual-studio-code-ide-support-in-rhel6

Can somebody help here ? Thanks in advance!

**Comment by joaomoreno** [comment]
Since we distribute snap packages, that addresses running VS Code in RHEL 6.

**Comment by SiteshSahoo** [comment]
Could you please elaborate what is a snap package ?

I have downloaded the VSCode tar for linux from official website and facing  the below dependency issue while trying to execute.

`VSCode-linux-x64/bin/../code: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`

Thanks in advance!

**Comment by joaomoreno** [comment]
Here's a bit more info:

- https://ubuntu.com/blog/visual-studio-code-launches-as-a-snap
- https://snapcraft.io/code

**Comment by SiteshSahoo** [comment]
> Here's a bit more info:
> 
> * https://ubuntu.com/blog/visual-studio-code-launches-as-a-snap
> * https://snapcraft.io/code

Thanks for the links. 
From : https://snapcraft.io/install/code/rhel I can see that snapd is supported from RHEL7.6. 
Enable snapd

> Snap is available for Red Hat Enterprise Linux (RHEL) 7, from the 7.6 release onward, from the Extra Packages for Enterprise Linux (EPEL) repository.
> 
> It is not yet available in the EPEL 8 repository, and consequently, not yet available for RHEL 8 unless you build the RPM yourself.

Would you be able to help here confirming if VSCode will work on RHEL6 versions ?
