### ISSUE TITLE
Blank terminal

### ISSUE THREAD

**Issue by cezny** [microsoft/vscode#89693]
My terminal has been very useless because it is blank, it can not show the path when I want to run and configure my project.  Very disappointing.

![bug](https://user-images.githubusercontent.com/46327532/73440910-d0f42400-435a-11ea-8a74-9b33f3ec5769.png)

How do we solve this?

**Comment by schattenmann80** [comment]
I have the same problem.
vscode is blinking one or two times like it is reloading something and than the terminals are blank.

If you scroll up there are some symbols:
![grafik](https://user-images.githubusercontent.com/22788790/73526158-e0ce3f80-4410-11ea-89f5-9098b09a5573.png)

The ctrl + click to follow link is still there:
![grafik](https://user-images.githubusercontent.com/22788790/73526263-212dbd80-4411-11ea-8509-961eee98a8a0.png)

If I open a new terminal with the plus symbol the new terminal is working fine.

I'm working via ssh one a debian remote host.

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by schattenmann80** [comment]
When I zoom out with ctrl + "+" then the text is back.

**Comment by belolap** [comment]
Same for me. Problem appear not every time. If it exists I must restart vscode, "reload window" command not resolve issue. When I restart vscode sometime problem fixes (only one time after restart where was no terminal). Zoom changing, render engine changing not fixes it.

When terminal absent where is error message in google dev tools console:

```
Error: EACCES: permission denied, open '/proc/1/environ'
```

Code runs as user w/o root rights. Permissions:
```
> ls -laFh /proc/1/environ 
-r-------- 1 root root 0 фев  5 18:17 /proc/1/environ
```

Where is no this error message, if terminal exists after restart. OS Debian Buster (10.2).

**Comment by Tyriar** [comment]
@belolap different problem: https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.

---

Still waiting on more info for this https://github.com/microsoft/vscode/issues/89693#issuecomment-580772621
