### ISSUE TITLE
IntelliSense for JS doesn't see Buffer in the global scope

### ISSUE THREAD

**Issue by lem0nify** [microsoft/vscode#89696]
- VSCode Version: 1.41.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

1. [Node.js documentation](https://nodejs.org/api/buffer.html#buffer_buffer) says that `Buffer` class is available in the global scope but VS Code's IntelliSense doesn't know about it.
![image](https://user-images.githubusercontent.com/17163615/73442799-8678a480-4366-11ea-97f2-8f25d968ba0f.png)

2. At least until I import it directly (but this import is excessive)
![image](https://user-images.githubusercontent.com/17163615/73442958-d48da800-4366-11ea-9996-b79e569ce457.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you sure you have `@types/node` installed in your project? TS doesn't provide built-in type for Node specific items.

**Comment by lem0nify** [comment]
@IllusionMH Who said anything about TS? Topic starts with words "IntelliSense for JS". Or you want to say it needs `@types/node` anyway?
By the way, after creating this issue I found out that IntelliSense doesn't also suggest `require` function (if I type e.g. `const fs = req` and press Ctrl+Space in empty .js file).
But right after I type it by hand (any `require`, it turns out, not only `require('buffer')`) then global scope, including `require` function and `Buffer` class, becomes available for IntelliSense. Magic!

**Comment by IllusionMH** [comment]
VS Code uses built-in version of TS to provide all language features for both TS and JS.

Both `Buffer` and `require` are not part of JS standard or browser API, therefore there are no built-in typings for Node.

You can add `@types/node` as dev dependency to your repo (using version for your node env) or above you project in directory tree. TS will be able to find and use these typings and both `Buffer` and `require` will be available for completion.

You can find more info in docs: [Working with JavaScript
](https://code.visualstudio.com/docs/nodejs/working-with-javascript)

/cc @mjbvz for visibility

**Comment by lem0nify** [comment]
@IllusionMH Then explain why it's enough to add any `require` call into js file to make node's global scope available **without instalation of `@types/node` package**?

**Comment by IllusionMH** [comment]
> UPD. Without @types/node installed you rely on Automatic Types Acquisition which won't be triggered until there is explicit import in code . After ATA it will be visible.

More details https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition

You can also force ATA for Node using `jsconfig.json`
```json
{
    "typeAcquisition": {
        "include": ["node"]
    }
}
```

**Comment by lem0nify** [comment]
Thanks. I close this.
