### ISSUE TITLE
vscode.postMessage bug?

### ISSUE THREAD

**Issue by SetoKaiba** [microsoft/vscode#89694]
- VSCode Version: 1.14.1
- OS Version: Win 10

Steps to Reproduce:

1.
```
		const url = "http://seto.gicp.net/test.html";
		const webview = vscode.window.createWebviewPanel("danmaku", "Danmaku",
			vscode.ViewColumn.One, { enableScripts: true });
```
2.
```
webview.webview.html = `
		<html>
		<head>
			<script>
			const vscode = acquireVsCodeApi();
			function test(){
				vscode.postMessage({
					command: 'token',
					token: '🐛  hahaha'
				});
			}
			</script>
		</head>
		<body>
		<button onclick="test();">haha</button>
		</body>
		</html>`;

```
3. This is working for local html.
4. 
```
		webview.webview.html = `<script>window.location.href="${url}"</script>`;
```
5. This is not working for remote html. The remote html is the same with the local one.

**Comment by SetoKaiba** [comment]
After deeper digging, I found that the postMessage is not working after the window.location.href="xxx". It will work before it. Any solution for it? I use the local html but scripts and css from the http is working.

**Comment by mjbvz** [comment]
Please link to an example extension repo

But it sounds like you should just not set the window.location inside of web views

**Comment by SetoKaiba** [comment]
@mjbvz Just copy the html to test.html and serve it on a http server. Use both `window.location` or `iframe` to load the page. The acquireVsCodeApi function is undefined. But it's ok with html string directly.

**Comment by SetoKaiba** [comment]
I take a deeper look at the vscode source. The acquireVsCodeApi is injected by src/vs/workbench/contrib/browser/pre/main.js. I want to load the html from the http server instead of a local html sting. Any other way method?

**Comment by mjbvz** [comment]
No. If you want to load external content, try loading your html using an iframe in the webview

**Comment by SetoKaiba** [comment]
But the iframe webpage can't call acquireVsCodeApi as well. It doesn't actually solve my problem.

**Comment by SetoKaiba** [comment]
@mjbvz

**Comment by SetoKaiba** [comment]
I don't know why does vscode come with an actual webview while the other IDEs does. For example, the JetBrains IDEs. This lead to problem when I migrate my plugin from JetBrains IDEs. Currently, I have to write an HTTP server in the extension to get message from normal browsers.
