### ISSUE TITLE
Extra sync happens after disabling sync everywhere using the checkbox

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89708]
- Have sync enabled on two machines
- Turn sync off on all machines from one of them using the checkbox in the turn off dialog.
- At this point, the second machine will get the message from the server to stop syncing, but sometimes it comes too late.
It looks like the second machine can quickly sync something before gets the message to stop. So instead of the data being cleared from the server, it has some sync data from the second machine. Or at least that's what it looks like.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/89750
