### ISSUE TITLE
Syntax highlighting disabled for parts of some keywords in C

### ISSUE THREAD

**Issue by sdaitzman** [microsoft/vscode#89706]
- VSCode Version: 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0)
- OS Version: macOS 10.15.3

Steps to Reproduce:

1. Write some simple C code
2. Add some more lines, and edit some lines above it

Does this issue occur when all extensions are disabled?: No

<img width="598" alt="Screen Shot 2020-01-30 at 8 08 34 AM" src="https://user-images.githubusercontent.com/1499476/73452346-b78db080-4337-11ea-92fa-8a7843f10046.png">

**Comment by alexr00** [comment]
`Does this issue occur when all extensions are disabled?: No`
It looks like an extension is causing this.
