### ISSUE TITLE
Setting sync error messages language

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89705]
To make the sentences more correct and descriptive I would make two changes:

"Turned off sync because size of the {0} file to sync is larger than {1}. Please open the file and reduce the size and turn on sync"
This could indicate that the user needs to manually turn sync back on after taking the other action(it doesn't turn itself back on.)
"Turned off sync because size of the {0} file to sync is larger than {1}. Please open the file and reduce the size before turning sync back on."

"Turned off sync because of too many failure attempts. Please open Sync log to check the failures and turn on sync."
"failed attempts" is just a little clearer than "failure attempts"
"Turned off sync because of too many failed attempts. Please open the Sync log to check the failures and then turn on sync."

**Comment by sandy081** [comment]
/duplicate 

#90218
