### ISSUE TITLE
Incorrect number of extensions that need updating reported

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#89702]
Issue Type: <b>Bug</b>

When checking for extension updates, by the menu command in the Extensions panel, the popup notification indicates an incorrect number that need updates. Currently, I have one extension that has an update available, but the popup message shows that I have two. But there is only one listed with a button to "Install update"

![image](https://user-images.githubusercontent.com/13488/73446440-c1f57d80-432a-11ea-84ac-e0d7084b258f.png)

<img width="330" alt="image" src="https://user-images.githubusercontent.com/13488/73446471-d33e8a00-432a-11ea-867b-85c0e2877e64.png">

VS Code version: Code - Insiders 1.42.0-insider (be9c72410acc677070685a616773b122f4c5e141, 2020-01-29T05:35:51.712Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 10, 8|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
ng-template|Ang|0.900.7
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.0.15
githistory|don|0.4.13
auto-rename-tag|for|0.1.1
Angular2|joh|8.3.0
mads|mir|0.0.5
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
csharp|ms-|1.21.9
js-debug-nightly|ms-|2020.1.41823
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|3.9.2
autoimport|ste|1.5.3
open-in-browser|tec|2.0.0
msbuild-project-tools|tin|0.3.3
vscodeintellicode|Vis|1.2.4

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
Not a duplicate of any of those.

**Comment by sandy081** [comment]
@jtsom I do not think I am able to repro it. Can you please let me know if you are still able to repro it and if so can you please provide me the steps, if possible what extensions are available for update during then?

**Comment by sandy081** [comment]
@jtsom So it happens only with this extension?

**Comment by jtsom** [comment]
Yes, it seems like it was just that extension. I checked when the extensions needed updating today, and it looks like it is not happening now. But I will keep watching, I feel it has happened recently.

**Comment by sandy081** [comment]
Ok, I suspect this weirdness from this extension because it was changed to built in extension and we had a bug inside VS Code in handling such extensions and I fixed it recently. So I am assuming this will be good now.

Hence closing this. Please reopen it if you see again.
