### ISSUE TITLE
[semantic][typescript] Semantic highlighting on literal properties missing

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#89716]
![capture](https://user-images.githubusercontent.com/1931590/73437826-583a9b00-434d-11ea-93b2-d6365f576be3.png)

![capture](https://user-images.githubusercontent.com/1931590/73437964-920ba180-434d-11ea-9839-ceaebe6db49a.png)

Observe: `provideCompletionItems` is colored in white whereas `resolveCompletionItem` is colored correctly (or better)

**Comment by aeschli** [comment]
fixed by https://github.com/aeschli/typescript-vscode-sh-plugin/commit/1100c3f1d18a96748509fae01a4c8f9138131a0f
