### ISSUE TITLE
Disable color boxes

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#89719]
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

I'm highlighting colors on my own and I'd therefore like to remove the built-in color boxes, there doesn't seem to be an option for it though, can it be added?

<img width="610" alt="Screen Shot 2020-01-30 at 15 13 53" src="https://user-images.githubusercontent.com/1812093/73463492-3fde7680-4375-11ea-8ac9-d17fb0081257.png">

**Comment by gjsjohnmurray** [comment]
`"editor.colorDecorators": false` should do it. Works on the 1.42.0-insider build

**Comment by usernamehw** [comment]
That would also disable the color picker. The issue about separating the two is #34341

**Comment by fabiospampinato** [comment]
> "editor.colorDecorators": false should do it. Works on the 1.42.0-insider build

@gjsjohnmurray Thanks! I'm still on v1.40.1. 

I'm closing this as it would seem the issue is resolved already.
