### ISSUE TITLE
Code doesn't release all file handles on Windows

### ISSUE THREAD

**Issue by macxcool** [microsoft/vscode#89714]
Issue Type: <b>Bug</b>

- using Windows 10
- Add folder to workspace. There may have to be images in a subfolder??
- Do some editing. Save. Remove folder from workspace
- Try to move the folder to another location using Windows Explorer
Explorer will complain that some files are still in use and will refuse to move the folder until Code is exited.

This doesn't happen with every folder, but it happens most times. The folders I'm working with always have an image in them and it's the image file that Explorer refuses to move while Code is open.

VS Code version: Code - Insiders 1.42.0-insider (9e8c4c247a779cdd1f4f53db963bc6124a28ac2f, 2020-01-30T05:29:34.196Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (6.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
json-tools|eri|1.0.2
path-autocomplete|ion|1.13.3
reg|ion|1.0.1
rainbow-csv|mec|1.5.0
powershell-preview|ms-|2020.1.0
code-settings-sync|Sha|3.4.3

</details>

**Comment by macxcool** [comment]
Nope. This looks like a different issue entirely.

**Comment by roblourens** [comment]
Do any of your extensions do anything with that image file?

Is the image open in vscode when this happens?

**Comment by macxcool** [comment]
I'll try --disable-extensions some time, but none of my extensions have anything to do with images and I never open this image. It's just a graphic that gets used when the script I'm writing gets run.

**Comment by roblourens** [comment]
Is there a build task or script or something running in a terminal? vscode doesn't just lock random files in your workspace, and the fact that it only happens with an image seems to point to something external.

**Comment by macxcool** [comment]
No. Nothing like that. I'm writing PowerShell scripts for software installations using the PowerShell App Deployment Toolkit. Whenever this happens, the solution is to close Code and then allow the move to finish. I've taken to closing Code before I move the folder so this doesn't happen. A thumb.db file is always left in the folder with the image whenever this happens, so I suppose it could be Windows doing something stupid ;-)

**Comment by roblourens** [comment]
Sorry for the slow response. But I think I have to leave it at

> vscode doesn't just lock random files in your workspace, and the fact that it only happens with an image seems to point to something external.

Please try with `--disable-extensions` when you get a chance, if you still see this issue.
