### ISSUE TITLE
Code won't remove folder from workspace list

### ISSUE THREAD

**Issue by macxcool** [microsoft/vscode#89715]
Issue Type: <b>Bug</b>

- Add folder to workspace
- Do some work, etc.
- Right-click on folder and select 'Remove folder from workspace'
Sometimes Code will pop up a message saying 'Unknown folder' and I have to exit Code in order for the folder to be removed. Sometimes removing another folder later will cause the other folder to disappear.

VS Code version: Code - Insiders 1.42.0-insider (9e8c4c247a779cdd1f4f53db963bc6124a28ac2f, 2020-01-30T05:29:34.196Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (6.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
json-tools|eri|1.0.2
path-autocomplete|ion|1.13.3
reg|ion|1.0.1
rainbow-csv|mec|1.5.0
powershell-preview|ms-|2020.1.0
code-settings-sync|Sha|3.4.3

</details>

**Comment by macxcool** [comment]
None of the issues listed match what's happening here. I did look first ;-)

**Comment by isidorn** [comment]
Same as https://github.com/microsoft/vscode/issues/89138
Looks like @sandy081 fixed it but he can comment more if it should be fixed in your insiders version

**Comment by sandy081** [comment]
Yes it is same as #89138 and is fixed. Please try latest insiders and let us know if you still see this issue.
