### ISSUE TITLE
Suggestion is not working

### ISSUE THREAD

**Issue by Taniya1** [microsoft/vscode#89712]
Issue Type: <b>Bug</b>

What ever i typed no suggestion coming.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
simple-react-snippets|bur|1.2.2
react-redux-react-router-snippets|dis|0.4.29
vscode-language-babel|mgm|0.0.25
react-proptypes-intellisense|OfH|1.0.3

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo such as what language mode your file is using, and whether the problem exists if you retest after running the command to reload with all extensions disabled.

Pasting screenshots into the GitHub editor is a good way of communicating what your problem is.
