### ISSUE TITLE
Electron Helper runs 99% of CPU after last update. 

### ISSUE THREAD

**Issue by gerhardcit** [Microsoft/vscode#8971]
- VSCode Version: Code - Insiders 1.4.0-insider (4c0676ab472a92f5269ac4995cdc81db8bc94896, 2016-07-08T15:15:41.390Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Install latest Insider on MacBook Pro (Retina, 15-inch, Late 2013) OSX 10.11.5 (15F34)
2. Seems that open second project make it go like this. Node Express apps mostly. 

It started on prev version.. but after a longer time. No it happens quickly.
Killing electron helper process in Activity Monitor seems to help.. for a while.

**Comment by bpasero** [comment]
@gerhardcit you need to find out which of the processes we spawn is under high CPU load, then we can investigate more!

**Comment by hartbit** [comment]
I'm experiencing this on a C# Unity project.

**Comment by gerhardcit** [comment]
[ElectronSample.txt](https://github.com/Microsoft/vscode/files/355607/ElectronSample.txt)

@bpasero 
Also seems that when I open the Extension manager, this happens.
Does this help?

**Comment by gerhardcit** [comment]
Not sure if it helps, but here is another sample. Started happening again after re-open the last time. Did nothing special.

[ElectronSample2.txt](https://github.com/Microsoft/vscode/files/355627/ElectronSample2.txt)

**Comment by bpasero** [comment]
@hartbit @gerhardcit use activity monitor to find the high CPU task and then from the command line run "`ps aux | grep <pid>`" to find the full command line arguments.

![image](https://cloud.githubusercontent.com/assets/900690/16709033/5a76c9aa-4605-11e6-9415-0477b9740822.png)

**Comment by hartbit** [comment]
Two processes regularly take 100% CPU when VSCode is becoming unusable:

```
$ ps aux | grep 69654
david           69683   0.0  0.0  2444056    816 s000  S+    7:04PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 69654
david           69654   0.0  0.6   972732 214848   ??  S     7:01PM   1:11.65 mono /Users/david/.vscode/extensions/ms-vscode.omnisharp-0.3.3/bin/packages/dnx-mono.1.0.0-beta4/bin/dnx.mono.managed.dll /Users/david/.vscode/extensions/ms-vscode.omnisharp-0.3.3/bin/packages/OmniSharp/1.0.0/root run -s /Users/david/Projects/leon/trunk/Project/Project.sln --hostPID 69643 dnx:enablePackageRestore=false --stdio
$ ps aux | grep 69642
david           69642  99.6  1.4  4474380 465284   ??  R     7:01PM   2:24.18 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --background-color=#131313 --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=34037 --channel=69361.2.457362895
david           69756   0.0  0.0  2434840    792 s000  S+    7:04PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 69642
```

**Comment by bpasero** [comment]
@hartbit is this happening for a large folder?

**Comment by hartbit** [comment]
Fair large yes:

```
$ find . -type f | wc -l
29575
```

I'd like to note that the severe performance degradation (to the point of making it unusable) only started happening since version 1.4.0 (final - I don't download insiders).

**Comment by bpasero** [comment]
@hartbit it might be the file watcher then which is known to consume lots of CPU on large folders. You can try setting the `files.watcherExclude` to exclude large folders from your workspace to see if that improves things.

See also https://github.com/Microsoft/vscode/issues/3998

**Comment by gerhardcit** [comment]
Extending the fileWatcher seems to help with this.
files.watcherExclude": {
".hg": true,
"bower_compoments": true,
.... add any build folders that will change a lot
}
I would close this now.
