### ISSUE TITLE
Expand large type signatures

### ISSUE THREAD

**Issue by TylorS** [microsoft/vscode#89713]
When you're working with a typed language, such as TypeScript, and you create a large enough type when you hover over an implementation you will see truncated types marked by `...`. I think it'd be a welcome addition to be able to expand these truncated types to allow viewing the full type signature.

**Comment by briancavalier** [comment]
I agree.  The ability to click to expand/contract each individual ellipsis seems ideal.

**Comment by mjbvz** [comment]
Being investigate upstream with https://github.com/microsoft/TypeScript/pull/31384 (which is about errors but would also apply to hovers)
