### ISSUE TITLE
Decrease minimum window size

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#89721]
I see recently the minimum allowed dimensions of the window have been increased, unfortunately this breaks a bit my workflow as I usually have windows on the left side of my screen that occupy 40% of it, and windows on the right side of my screen that occupy the remaining 60%. Now VSCode doesn't think 40% of my screen is enough for it anymore and it overflows:

![image](https://user-images.githubusercontent.com/1812093/73464591-1292c800-4377-11ea-9f87-87bacd98f654.png)

This is especially annoying for me since I've removed a bunch of icons from the interface so the acceptable minimum width should be even lower than what it was before, which worked fine for me.

Perhaps a setting for this could be added?

Perhaps the minimum size could be adjusted dynamically depending if the sidebar/side panel/side editors exist/are visible?

**Comment by sbatten** [comment]
there is no behavior that I am aware of that let's me dynamically update the minimum size. so i cannot shrink it because parts of the app are not visible. further, i think it would be weird for the app to get larger if you open the sidebar and the window is too small.

**Comment by fabiospampinato** [comment]
> there is no behavior that I am aware of that let's me dynamically update the minimum size.

What's a behavior? Electron's `BrowserWindow.setMinimumSize` API is available.

> so i cannot shrink it because parts of the app are not visible.

If this is an API question there absolutely are APIs for doing that at the Electron level.

>  i think it would be weird for the app to get larger if you open the sidebar and the window is too small.

In this scenario the user already has a "small" window, and when the sidebar opens for practical purposes the window's width gets increased, wouldn't it be worse if the user couldn't resize the window to its likings in the first place though?

Also I don't think it would look particularly weird, does the following look weird? Wouldn't it be more annoying if you couldn't resize the window down even if there's plenty of space available?

https://imgur.com/a/afXH65E

Lastly if this was configurable those who think this would be weird, and I guess aren't bothered by the recent change, would just not opt-in.

**Comment by sbatten** [comment]
@fabiospampinato thanks for the pointers, I will look into that.
to answer your question as to whether it looks weird: to me, yes, but i see there is precedent for it so i will try it out when I get the chance.

**Comment by fabiospampinato** [comment]
> but i see there is precedent 

To be fair that's my app so maybe it still behaves weird for most other people, I'm not sure 😄 Although I had received a bunch of issues about the app being too wide in the past, and since I implemented dynamic minimum sizing nobody has complained to me about it.

> we typically aren't adding any new functionality that relies on electron-specific api, but given the difference in window sizing for the web version, i will take a look.

Technically the current minimum sizing feature relies on Electron already, so this would be more of a further polishing than a new feature I think. 

Thanks 👍

**Comment by fabiospampinato** [comment]
A related issue: apparently there are limits on how narrow the editor area can get, so I can't increase the width of the sidebar any more than this:

![image](https://user-images.githubusercontent.com/1812093/73861259-a8759980-4834-11ea-9982-5f05163f3bae.png)

I'd say under such circumstances it's way more useful to the user to be able to increase the width of the sidebar than having the VSCode logo displayed at will size. Perhaps the size of the logo should adjust with the available width and/or disappear if there isn't enough space for it.

**Comment by rzhao271** [comment]
Notes for tester(s):

- When the panel is on the bottom, no matter its visibility or maximization state, the window can be resized to a minimum width of 400px
- When the panel is on the left or right, no matter its visibility or maximization state, the window can be resized to a minimum width of 600px
- When the panel is at the bottom and the window is resized to a width of 400px, when the user moves the panel left or right, then the window should automatically resize to the new minwidth of 600px

Definitely not the most eloquent solution, but hopefully it can provide some relief to cases such as OP's above.

Notes for documentation:

- The minimum width of the window is now down to 400px when the panel is placed at the bottom. If the panel is placed on either side, the minimum width of the window is still the original value of 600px
