### ISSUE TITLE
Add a way to view all functions/variables/symbols/etc available in scope of where the cursor is?

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode#89725]
Given that jsconfig.json has been declared and vscode is able to analyze code using the ts engine. It'd be really useful to place a cursor somewhere and view the all the variables and functions available in that scope somehow.

In debug mode you have variables panel, in chrome source tab in developer tools you have scope panel.
 
![image](https://user-images.githubusercontent.com/4664695/73469176-ee71bf80-4353-11ea-9cf3-f8fec4c8e9cd.png)

It's helpful for really big files this way you can see what variables are available to you.

Unless I'm missing something outline panel shows entire page's scope, no way to all and just variables available to scope in which the cursor is.

**Comment by isidorn** [comment]
This is a fair feature request, however it would require knowledge from the language service thus first forwarding to @weinand to think about this.

**Comment by techsin** [comment]
I believe it'd be easy, "as rename symbol" is already able to recognize context.

**Comment by connor4312** [comment]
I don't think it would be very easy for me to do this in js-debug. CDP does not give information about the location/source ranges of scopes, and often the scopes are different between what's in the source code and what's actually running, particularly when using bundlers, downleveling, or other transformations.

**Comment by weinand** [comment]
There are no plans to add this feature.
