### ISSUE TITLE
Feature: Better control code and file extension support

### ISSUE THREAD

**Issue by tracker1** [microsoft/vscode#89732]
## Features

This request is for a few things that are all related...

* Show escape and other control characters on display, should look similar to how the old DOS EDIT.COM would display these characters.
  * Maybe with a toggle that will show space/placeholders for space, tab and other normally hidden characters.
* Allow specifying features not just by type, but by file extension (this part may be a duplication)
  * codepage
  * line ending
  * etc.

## Example

```
[.ans, .asc, .msg, .cfg]
{
  ...
}
```

Effectively, a section beginning with a `.` as a file extension, optionally with `/,\s*/` separators...

## Reasoning: 

I'd rather not have to create a new file type in order to specify/align a file extension to have a cleaner editing experience.  I'd also like to be able to hand edit files that have ANSI escape codes, and in the case of CP437 or even UTF line/block characters.

The Remote SSH plugin is amazing.  I have a classic BBS setup on a system that is remote to me, and a lot of the files are DOS line endings and CP437 (IBM DOS US code page), And while the Remote SSH gives me incredibly easy access, I really cannot effectively make tweaks or edits to these files.

**Comment by sandy081** [comment]
> Allow specifying features not just by type, but by file extension (this part may be a duplication)

Do you mean settings or something else?

**Comment by tracker1** [comment]
@sandy081 Both...

* "Allow specifying features by file extension" - I want to be able to specify the codepage and the line endings etc by file extension.  Right now, I can only do it by supported "file type" ...  I'm working with text files, but these files are codepage 437, and I only want .ans, .asc, etc.  It's not a programming language, so there's no highlighting... just certain file extensions.

* "Show escape and other control characters" - if you load a .ans (ansi) file in the old EDIT.com, you would see characters represented for the control characters (byte values under 32) [0]

I cannot be the only person that wants to edit files with control characters in a specific code page and be able to see the control characters in something I can reasonably copy/paste/modify.

[0] https://www.ascii-codes.com/

**Comment by tracker1** [comment]
Right now, I can set something specific to a file type, like `[css]`, but that isn't a file extension, just a type... I want to make settings by file extension.

The second half, and the reason I want this, is that currently, VS Code lacks any display for control characters in a file.

**Comment by tracker1** [comment]
By duplication, I meant that there may be another issue already requesting said feature, but with tens of thousands of issues, it's hard to grok through.

**Comment by tracker1** [comment]
My mistake, it looks like, when I have the `"files.encoding": "cp437",` it does show the control and line/block art characters... however, I really would like to set this by file extension.. going to close and create a new issue just for the configuration option.
