### ISSUE TITLE
Option to disable workspace overriding of specific settings.json entries

### ISSUE THREAD

**Issue by Drigax** [microsoft/vscode#89737]
Say I have my user settings.json configured with a particular `workbench.colorCustomizations` theme,
and I open a shared workspace that is configured with a particularly obnoxious `workbench.colorCustomizations` theme. 

I would then have to go through the trouble of disabling this theme manually (and potentially setting up git to ignore changes to this file) to restore my desired setting which seems like a sub-optimal solution.

There should be some way to indicate that a user or default setting is not overridable by workspace settings, in order to ensure consistency in experience when working on different projects.

**Comment by sandy081** [comment]
/duplicate

https://github.com/Microsoft/vscode/issues/40233
