### ISSUE TITLE
Apps shut down/freezes after a while

### ISSUE THREAD

**Issue by Kingscity** [Microsoft/vscode#8973]
- VSCode Version: 1.3.0
- OS Version: Windows 10

After a while of editing, the apps freezes. It's happen quite often after upgrade to new version

**Comment by bpasero** [comment]
@Kingscity can you share more details about your workspace where this happens?

**Comment by Kingscity** [comment]
I'm using Windows 10, and just upgrade the Visual Studio Code to 1.3.0.

I experience quite often that, after a while of editing (e.g. typing, copy,
pasting, selecting, open a split view), then the window freeze, and I have
to close the app and restart.

On Fri, Jul 8, 2016 at 10:54 PM, Benjamin Pasero <notifications@github.com>
wrote:

> @Kingscity <https://github.com/Kingscity> can you share more details
> about your workspace where this happens?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode/issues/8973#issuecomment-231517427>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AO97Cc52d4iz_gMKgwk4mVbU13JAEjY1ks5qTzeIgaJpZM4JIXhF>
> .
>



-- 
Best regards,
*Kenneth Chau*
1.604.729.7380

**Comment by Kingscity** [comment]
BTW, I'm using MS Surface Pro 4

On Sat, Jul 9, 2016 at 11:45 AM, Kenneth Chau <kenneth@kennethchau.com>
wrote:

> I'm using Windows 10, and just upgrade the Visual Studio Code to 1.3.0.
>
> I experience quite often that, after a while of editing (e.g. typing,
> copy, pasting, selecting, open a split view), then the window freeze, and I
> have to close the app and restart.
>
> On Fri, Jul 8, 2016 at 10:54 PM, Benjamin Pasero <notifications@github.com
> > wrote:
>
>> @Kingscity <https://github.com/Kingscity> can you share more details
>> about your workspace where this happens?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Microsoft/vscode/issues/8973#issuecomment-231517427>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AO97Cc52d4iz_gMKgwk4mVbU13JAEjY1ks5qTzeIgaJpZM4JIXhF>
>> .
>>
>
>
>
> --
> Best regards,
> *Kenneth Chau*
> 1.604.729.7380
>



-- 
Best regards,
*Kenneth Chau*
1.604.729.7380

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by wUFr** [comment]
I think freeze problem could do something with "autosave", it happenes to me while opening files and writing changes info them

**Comment by bpasero** [comment]
@wUFr does this happen only with large files maybe? or any file?

**Comment by wUFr** [comment]
any files, PHP or editing css/less and these are not really big, maybe few hundreds KB.

**Comment by wUFr** [comment]
looks like new version (1.3.1) got released, gonna test it and report if anything happens... :)

**Comment by wUFr** [comment]
ok, soo far not single freeze today, so you can slooowly close this issue :)

**Comment by wUFr** [comment]
@Kingscity did you edit your files on network shared storage? cuz my editor just froze today :D yesterday was ok tho, we use WinSSH to connect to local server. I think it is related to that.

I have autosave enabled, so **maybe it will try to save file, but server won't respond in time and editor will freeze**

@bpasero bad news ^^ (:

*switched off autosave for now, but i bet its that (:*
