### ISSUE TITLE
Add support for auto-expand snippet

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89731]
Idea is to have next label of tab completions, e.g have snippets that expand/insert themselves as soon as the prefix is typed, similar to the https://github.com/federico-terzi/espanso text expander. It could be as easy as flag when defining snippets and/or a user setting (maybe a setting per snippet prefix)

**Comment by movermeyer** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/64135
