### ISSUE TITLE
GeoJSON should be syntax highlighted as JSON instead of plain text

### ISSUE THREAD

**Issue by theel0ja** [microsoft/vscode#89734]
- VSCode Version: 1.41.1
- OS Version: Linux

Steps to Reproduce:

1. Open a GeoJSON file
2. Get no syntax highlighting

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Assuming your GeoJSON files use the .geojson file-extension, the `files.associations` setting enables you to [tell VS Code to treat these as JSON](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language). This can even be done without going into the Settings Editor. Instead, open a .geojson file, click on the "Plain Text" language mode indicator on your status line, pick "Configure File Association for '.geojson'...", and pick "JSON".
