### ISSUE TITLE
StatusBar cause docs below to have margin

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#89736]
Version: 1.42.0-insider
Commit: 9e8c4c247a779cdd1f4f53db963bc6124a28ac2f
Date: 2020-01-30T05:27:10.308Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

---

![image](https://user-images.githubusercontent.com/4033249/73481822-73a7a500-4351-11ea-9a97-3c03737f9c49.png)

- Current insiders
- Make window narrow
- StatusBar takes place and shifts docs window

**Comment by joaomoreno** [comment]
How can I get that description for aria attrbutes?

**Comment by octref** [comment]
@joaomoreno Just auto complete here `<div aria|></div>`, any completion item with description will do.

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/73541274-4da60180-4432-11ea-9b49-8b51379b36f0.png)

**Comment by octref** [comment]
@joaomoreno You need to Ctrl + Space to expand

**Comment by joaomoreno** [comment]
I get the details in the side pane when I press Ctrl Space:

![image](https://user-images.githubusercontent.com/22350/73638891-8977db80-466b-11ea-9693-91a9c3a51b70.png)

**Comment by octref** [comment]
@joaomoreno Now make VS Code narrower than the width of suggest + docs-box 😉

**Comment by joaomoreno** [comment]
What am I doing wrong? :cry: 

![image](https://user-images.githubusercontent.com/22350/73665786-f908bd80-46a1-11ea-86e9-941f0a67dddb.png)

**Comment by octref** [comment]
Try even narrower, maybe also close sidebar?

![image](https://user-images.githubusercontent.com/4033249/73669788-ed46d800-465c-11ea-965f-5c25a518c439.png)

**Comment by joaomoreno** [comment]
OK got it to work. There's some weird layout though:

![image](https://user-images.githubusercontent.com/22350/73727802-78de6880-4732-11ea-8f79-82078344d628.png)

**Comment by octref** [comment]
@joaomoreno That's a wrong amount of margin. Wanna open a new issue with your font, font-size, and OS?
