### ISSUE TITLE
Auth flow is broken in Web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89730]
Auth flow in Web is taking to insiders

![Kapture 2020-01-30 at 18 25 01](https://user-images.githubusercontent.com/10746682/73473963-eafb2a00-438d-11ea-8a10-eb5327f5f8e4.gif)

**Comment by IllusionMH** [comment]
Is it installed PWA?
![image](https://user-images.githubusercontent.com/1312662/73474995-361a3a80-4398-11ea-8c92-90d58b65ac2e.png)
