### ISSUE TITLE
Code Actions on Save for a particular source waits for all outstanding code action requests to complete

### ISSUE THREAD

**Issue by jvilk-stripe** [microsoft/vscode#89745]
- VSCode Version: Reproduced on Insiders version:

```
Version: 1.42.0-insider
Commit: be9c72410acc677070685a616773b122f4c5e141
Date: 2020-01-29T05:35:51.712Z
```

- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Have a project that includes both ESLint, Prettier, and Flow configured in LSP mode, e.g. using extensions:
  * `dbaeumer.vscode-eslint`
  * `flowtype.flow-for-vscode` 
  * `esbenp.prettier-vscode`
2. Configure ESLint with the following option to auto apply fixups on save _for eslint diagnostics only_:

```
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
}
```

3. When saving a file, VS Code sends diagnostics with `source: "eslint"` to Flow via code actions, and seems to wait for Flow to respond (as a "save participant") before running Prettier. As flow is sometimes slow to respond on large projects, this can be a noticeable delay (1-2 seconds).

The timeline I've assembled from independent logs from ESLint, Flow, and Prettier seem to confirm this. If there is a VS Code log that confirms what is a save participant, I would be happy to collect it and report it here. You can see more details [here](https://github.com/microsoft/vscode-eslint/issues/833#issuecomment-579508145) and [here](https://github.com/microsoft/vscode/issues/84602#issuecomment-579987144); ESLint takes ~250 ms and Prettier takes ~53ms, leaving over a second of unexplained time that seems to correlate well with slow code action requests to Flow.

The impact to users on an internal repository at my company is that, when Flow is backed up with typechecking changes, VS Code applies Prettier changes ~1-2 seconds after they hit save, which interrupts their flow.

## Questions

Is the above design intentional? If so, is there a way to disable sending blocking code actions to certain extensions? I understand that we can configure a 'timeout', but if Flow is slow in the common case, I don't want users to suffer from worst-case save performance.

If this design is intentional, then I expect it to cause many problems like I've described. I think that most implementations of code actions assumed that that request would never block something as time-critical as saving. (As an language server developer for [Sorbet](https://sorbet.org), I certainly didn't think code actions would be on a critical editor path!)

Does this issue occur when all extensions are disabled?: The issue is relevant to a VS Code feature that interacts with extensions, so the issue isn't relevant when extensions are disabled.

cc @dbaeumer who asked me to file this as a new issue. :)

**Comment by mjbvz** [comment]
From your description, this sounds like the bug is on the flow extension side. The flow extension should either:

- Register its code action provider with the correct `CodeActionProvider.metadata` so the VS Code never invokes it in the first place
- If its code action provider is invoked, quickly check if its actions are not being requested. If they are not, return before doing anything expensive.

**Comment by jvilk-stripe** [comment]
@mjbvz where is `metadata` defined? It is not described here as a provider option:

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction

is this a custom VS Code extension to the protocol?

**Comment by jvilk-stripe** [comment]
It looks like 'metadata' is just 'code action kinds':

https://code.visualstudio.com/api/references/vscode-api#CodeActionProviderMetadata

Which code action kind is expected to block saving?

**Comment by jvilk-stripe** [comment]
```typescript
export namespace CodeActionKind {

	/**
	 * Empty kind.
	 */
	export const Empty: CodeActionKind = '';

	/**
	 * Base kind for quickfix actions: 'quickfix'.
	 */
	export const QuickFix: CodeActionKind = 'quickfix';

	/**
	 * Base kind for refactoring actions: 'refactor'.
	 */
	export const Refactor: CodeActionKind = 'refactor';

	/**
	 * Base kind for refactoring extraction actions: 'refactor.extract'.
	 *
	 * Example extract actions:
	 *
	 * - Extract method
	 * - Extract function
	 * - Extract variable
	 * - Extract interface from class
	 * - ...
	 */
	export const RefactorExtract: CodeActionKind = 'refactor.extract';

	/**
	 * Base kind for refactoring inline actions: 'refactor.inline'.
	 *
	 * Example inline actions:
	 *
	 * - Inline function
	 * - Inline variable
	 * - Inline constant
	 * - ...
	 */
	export const RefactorInline: CodeActionKind = 'refactor.inline';

	/**
	 * Base kind for refactoring rewrite actions: 'refactor.rewrite'.
	 *
	 * Example rewrite actions:
	 *
	 * - Convert JavaScript function to class
	 * - Add or remove parameter
	 * - Encapsulate field
	 * - Make method static
	 * - Move method to base class
	 * - ...
	 */
	export const RefactorRewrite: CodeActionKind = 'refactor.rewrite';

	/**
	 * Base kind for source actions: `source`.
	 *
	 * Source code actions apply to the entire file.
	 */
	export const Source: CodeActionKind = 'source';

	/**
	 * Base kind for an organize imports source action: `source.organizeImports`.
	 */
	export const SourceOrganizeImports: CodeActionKind = 'source.organizeImports';
}
```

I'm assuming you want Flow to advertise that it doesn't offer quick fixes?

But what if Flow wants to offer quick fixes for its own errors, but it is slow to provide them since typechecking can be expensive?

**Comment by jvilk-stripe** [comment]
It looks like VS Code added some non-standard code action kinds:

https://code.visualstudio.com/api/references/vscode-api#CodeActionKind

I think it's source.fixAll...

**Comment by mjbvz** [comment]
None of the code action kinds specifically block saving. 

Please follow up with the flow extension upstream to see how they want to fix this issue. As I said, Flow needs to either use the metadata field to tell VS Code what kinds of actions it returns (which lets it avoid being called at all).  If that is not possible, the code action provider can use `context.only` to decide if it should do the expensive work to commute its code actions or not

**Comment by jvilk-stripe** [comment]
> None of the code action kinds specifically block saving.

@mjbvz I respectfully disagree! From what you're saying, with:

```
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
}
```

VS Code will query all code action providers that presumably provide `source.fixAll` code actions for fixes, wait for them to respond, and will only proceed to run prettier and save the final version of the file once the code actions come back.

I think there's a timeout that you can configure, so maybe technically speaking it's blocking with timeout. Nonetheless, I was surprised that code actions could hold up saving like this.

**Comment by mjbvz** [comment]
Yes, that's the designed behavior but it is not specific to any one code action kind

Again, follow up with flow about why they are invoked at all in the case where we only request code actions of kind `source.fixAll.eslint`

**Comment by rattrayalex-stripe** [comment]
@mjbvz (John's colleague here) – we're following up on the Flow side, but I think this issue is more about two things:

1) Code actions seem to apply serially, in ways which can cause poor user experiences. For example, the "prettier" extension is applying after others, which means that developers wait a second or two before seeing prettier apply (a regression; historically, it applied in under 100ms).

2) Code actions seem to apply unexpectedly in some cases (eg; Flow when only eslint is configured; it sounds like that's on the Flow extension to fix, but perhaps VS Code could make this behavior more clear).

I think you've mostly been responding to (2), but (1) is the bigger issue here. Does that make sense?
(John, anything to correct/add?)

**Comment by rattrayalex-stripe** [comment]
(Some additional background/research at https://github.com/microsoft/vscode-eslint/issues/833#issuecomment-579508145)

**Comment by dbaeumer** [comment]
@mjbvz one things I still don't understand is whether VS Code invokes the code action provider on save if an extension has not provided any meta data. I agree that for backwards compatibility we need to call the code action provider for the light bulb but for code actions on save wouldn't it be fair to not invoke them?
