### ISSUE TITLE
A function definition is not treated as a reference in Go to References when there are exactly 2 references

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89740]
I was just in this situation:

```ts
foo();

function foo() {
}
```

On the first call to `foo()` I hit shift+f12 expecting a peek to show me all the references since there are 2 references (the call and the definition). Instead it just flashes `foo` as if it was the only reference.

Doing it on this snippet works as expected as it will show 3 references in the peek as expected:

```ts
foo();

foo();

function foo() {
}
```

Something else that adds to this inconsistency is the fact that the `foo` flashes when you Go to References in this snippet:

```ts
function foo() {
}
```

Everything seems to treats the function definition as a reference except for Go to References when there are exactly 2 references. This was pretty confusing to me initially and I ended up hitting shift+f12 multiple times as I didn't believe that was the only reference.

**Comment by jrieken** [comment]
>  hit shift+f12 expecting a peek to show me all the references 

Shift+F12 is bound to "*Go to* References" (that's something we have changed in Oct/Nov), not peek and go-to does this on purpose. Reference providers are the only that (sometimes) return the definition of a symbol and we have cases (like this one and peek references) were we don't want the definition to be part of the references. 

The simplest for you is to (re)bind Shift+F12 to "*Peek* References"
