### ISSUE TITLE
Add a CSS class for editor tabs with file status in Git

### ISSUE THREAD

**Issue by rkyoku** [microsoft/vscode#89749]
It would be nice to have in editor tabs the same capabilities there are in the file tree view: a specific CSS class matching the status of the file in Git.

That way, we would be able to immediately see which tabs represent new files, which ones have been modified since the last commit, etc.

Seems like a must-have to me, and an easy one to implement I guess?

What is your opinion on this?

Best,

**Comment by joaomoreno** [comment]
@jrieken @bpasero This is about decorations in editor tabs.
