### ISSUE TITLE
PascalCase-naming doesn't work with Emmet completion in JSX

### ISSUE THREAD

**Issue by Darkzarich** [microsoft/vscode#89746]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

1. Create `file.jsx` (`*.jsx`, `*.js`, `*.html`, `*.vue` will do as well)
2. Input the code below:
```javascript
function test() {
    return (
    // step 3 here
    )
}
```
3. In return block inside parenthesis start typing `my-awesome-component`
4. Notice how Emmet will suggest to transform it to `my-awesome-component></my-awesome-component>`
![image](https://user-images.githubusercontent.com/18618206/73493522-f6694800-43c3-11ea-98ba-20b8dc37cccc.png)
5. Try to do the same with PascalCase-named component, Emmet will not suggest to transform it.
![image](https://user-images.githubusercontent.com/18618206/73493540-fec18300-43c3-11ea-8b9c-a985961be12e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Darkzarich** [comment]
Is there another place I can ask in? Seems like I can't get an answer either here or on Stackooverflow :disappointed:

**Comment by rzhao271** [comment]
@Darkzarich I can confirm this is still an issue. A workaround is to explicitly open up the command palette and run the `Emmet: Expand Abbreviation` command.

**Comment by rzhao271** [comment]
\closedWith 5bab307980f747f62d5410acb7cc22b391608df9
