### ISSUE TITLE
Rename contributions page in extension view

### ISSUE THREAD

**Issue by bepvte** [microsoft/vscode#89753]
Issue Type: <b>Feature Request</b>

I never used the "Contributions" tab in extensions, thinking it was for recent github contributions to the extension. I accidentially pressed it once, and found it very useful. I think the name "Contributions" is confusing and that "Details", "Internals" , "Technical Details", or something similar would make it much clearer.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.4.14-200.fc31.x86_64

**Comment by sandy081** [comment]
These are in fact contributions to VS Code. How about `Feature Contributions` ?
