### ISSUE TITLE
Stop suggesting this 'liveshare' thing to me

### ISSUE THREAD

**Issue by khanks** [microsoft/vscode#89752]
Issue Type: <b>Bug</b>

WTF is liveshare and why are you jacking up my menu items with it? And why are you reading my damn contacts?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the suggestion? What extensions do you have installed?

**Comment by khanks** [comment]
Laravel extensions pack, visual studio code. No, I can't show you
screenshot. This live share thing opens up in its own panel. Maybe it's the
extensions pack, but their docs didn't say anything about this item.

**Comment by joaomoreno** [comment]
What does `code --list-extensions` return?
