### ISSUE TITLE
Opening a new tab/untitled/unsaved file from text content

### ISSUE THREAD

**Issue by iambibhas** [Microsoft/vscode#8975]
- VSCode Version: 1.3.0
- OS Version: Ubuntu 14.04

I'm building an extension where I need to show the user a git patch. I have the patch string in a variable, but I have to show that to the user in a new tab/document on the side. I'm kind of clueless how to achieve that. I'm reading about `TextDocumentContentProvider` but not sure how to set the content for it. Is there any example for this?

**Comment by jrieken** [comment]
You can find a sample here: https://github.com/Microsoft/vscode-extension-samples/tree/master/contentprovider-sample. In short, you do this:

1. register a TextDocumentContentProvider for a uri scheme
2. tell the editor to open an uri that uses the scheme

**Comment by shanalikhan** [comment]
There should be a small example to do this.
I also want to open the untitled file and add text content on it.
I have opened the JSON file by using this code
`  var setting: vscode.Uri = vscode.Uri.file(en.APP_SETTINGS);
        vscode.workspace.openTextDocument(setting).then((a: vscode.TextDocument) => {
            vscode.window.showTextDocument(a, 1, false);
        });`

How to open the untitled file and add text content in it ?
