### ISSUE TITLE
Breakpoints are not able to move to different sources on update

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89756]
See https://github.com/microsoft/vscode-js-debug/pull/277#issuecomment-580530048. Tl;dr is that in a new debug session, the 'same' sources can get assigned different source references. Although we can use extra information in the `adapterData` of the source to reconcile the breakpoint to the correct place, updating the source referenced in the breakpoints changed event doesn't appear to have an effect.

**Comment by isidorn** [comment]
I acknowledge this limitation.
Breakpoint currently do not support this, the only update from the session they respect are in this [interface](https://github.com/microsoft/vscode/blob/af69a4f2b1d7d796af904af31328ec8e85b66bd9/src/vs/workbench/contrib/debug/common/debugModel.ts#L512). So the fix would be that breakpoints also allow the uri to be updated via the update event (which the DAP supports).
Let me know if this is important for your scenario and I can look into it next milestone potentially.

Code pointer https://github.com/microsoft/vscode/blob/af69a4f2b1d7d796af904af31328ec8e85b66bd9/src/vs/workbench/contrib/debug/common/debugModel.ts#L599

**Comment by connor4312** [comment]
Not super high priority but I would prefer this to get fixed before js-debug exits preview, so within the next two milestones probably.

**Comment by isidorn** [comment]
Ok, makes sense. Let's assign to February and try to get it in then.

**Comment by connor4312** [comment]
Played around with this, where we derive the sourceReference from a hash of the original source data: https://github.com/microsoft/vscode-js-debug/pull/277#issuecomment-580836736

However it looks like even if the source reference and paths is the same between sessions, VS Code still treats them as separate files. So then it looks like unless the source reference is 0 they're always different, I don't think there's any path to implement this correctly at the moment.

Here's a log of a restarted debug session:

```
A set breakpoint from first session being restored: 
{"command":"setBreakpoints","arguments":{"source":{"name":"extension.js","path":"/Users/copeet/.vscode-insiders/extensions/samverschueren.final-newline-0.3.2/out/extension.js","sourceReference":257145157},"lines":[23],"breakpoints":[{"line":23}],"sourceModified":false},"type":"request","seq":3}

Load the same source again--everything identical:
{"seq":264,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"extension.js","path":"/Users/copeet/.vscode-insiders/extensions/samverschueren.final-newline-0.3.2/out/extension.js","sourceReference":257145157}}}

Getting the paused stacktrace: 
{"seq":376,"type":"response","request_seq":11,"command":"stackTrace","success":true,"body":{"stackFrames":[{"id":56,"name":"_onWillDocumentSave","line":23,"column":18,"source":{"name":"extension.js","path":"/Users/copeet/.vscode-insiders/extensions/samverschueren.final-newline-0.3.2/out/extension.js","sourceReference":257145157},"presentationHint":"normal"}],"totalFrames":31}}

Then vscode thinks ref 257145157 is a new file from the one I have open in the editor already and requests its contents:
{"command":"source","arguments":{"sourceReference":257145157,"source":{"path":"/Users/copeet/.vscode-insiders/extensions/samverschueren.final-newline-0.3.2/out/extension.js","sourceReference":257145157}},"type":"request","seq":8}

Swapping back to the old source requests it again:
{"command":"source","arguments":{"sourceReference":257145157,"source":{"name":"extension.js","path":"/Users/copeet/.vscode-insiders/extensions/samverschueren.final-newline-0.3.2/out/extension.js","sourceReference":257145157}},"type":"request","seq":19}
```

**Comment by isidorn** [comment]
@connor4312 I pushed a potential fix for this. Please try it out and let me know how it goes.
I changed two things:
1) When a source gets opened in the editor ignore the query (which has the source). That way mutiple sessions should open the same file hopefully
2) Breakpoints now allow for hte update event to change their Source

**Comment by connor4312** [comment]
Works beautifully, thank you!

**Comment by isidorn** [comment]
Good to know, thanks!

**Comment by isidorn** [comment]
@connor4312 actually my change to ignore the query when opening the source is BAD. @weinand just found a regression.
I forgot that later on we are reliying on decoding the session id and the reference from the source uri query. Thus we can not do that. So I reverted my commit
Code pointer where we relly on the session id https://github.com/microsoft/vscode/blob/df5969701ee6fe14fa6cae5adeaa89562e30527d/src/vs/workbench/contrib/debug/common/debugContentProvider.ts#L84

So across sessions the sources with sourceRef != 0 will always be different.

**Comment by connor4312** [comment]
Hm, okay. Well if the breakpoint can still move to a different Source it will still be better than it was--just confusing if the user kept the file from the previous session open in their editor.

**Comment by isidorn** [comment]
Yeah, breakpoints can still move to a different Source I did not revert that. That part is perfectly fine.
