### ISSUE TITLE
initializing js/ts language features

### ISSUE THREAD

**Issue by zecjy** [microsoft/vscode#89755]
Issue Type: <b>Bug</b>

Very laggy interface and the whole time in the bottomrow it showes "initializing js/ts language features" all the time.
Restarting TypeScript server via command wasn't helping.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

error message:
TypeScript language service was restarted 5 times during the past 5 minutes.

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
language-gettext|mro|0.1.1
vscode-language-pack-de|MS-|1.41.2
cpptools|ms-|0.26.3
csharp|ms-|1.21.9
LiveServer|rit|5.6.1
vscode-arduino|vsc|0.2.29

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by zecjy** [comment]
It's working fine there, no problems at all. I will try to track down the issue in my running installation but it might be some complication with a damaged HDD or smth...

**Comment by zecjy** [comment]
Well, now its also happening to the insiders build without any extensions:
VS Code version: Code - Insiders 1.42.0-insider (be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b, 2020-01-31T13:53:58.701Z)
Any further suggestions to track that issue down?
"Initializing JS/TS language features" sticks to the bottom and every now and then it offers the error reporter since it crashes 5 times in 5 minutes...

**Comment by zecjy** [comment]
Restarting seems to fix the issue temporally.
Since my whole system is quit slow due to a bad HDD that maybe could be part of the cause.

**Comment by mjbvz** [comment]
Are you using a workspace version of TypeScript?
