### ISSUE TITLE
Auth providers - show dialog on token access

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#89754]
Refs: https://github.com/microsoft/vscode/issues/89390

Currently, when using the `getSessions` method on an auth provider from an extension, a consent dialog is shown to the user. Since sessions may be empty or have no sessions with the required scopes, the extension may not even get an access token and instead of to immediately call login, showing another consent prompt. Instead of protecting `getSessions`, the `accessToken` property on a session should be protected

**Comment by Tyriar** [comment]
@RMacfarlane please add a test plan or verification needed

**Comment by RMacfarlane** [comment]
To verify, create an extension that uses the proposed API and calls `accessToken` on a session:
```ts
const provider = vscode.authentication.providers.find(provider => provider.id === "MSA");

if (provider) {
	const session = await provider.getSessions();
	if (session.length) {
	    return session[0].accessToken();
	}
}

vscode.authentication.onDidChangeAuthenticationProviders(async changed => {
	if (changed.added.includes('MSA')) {
		const provider = vscode.authentication.providers.find(provider => provider.id === 'MSA');
		if (provider) {
			const session = await provider.getSessions();
			if (session.length) {
				return session[0].accessToken();
			}
		}
	}
});
```
