### ISSUE TITLE
file search: include workspace folder in filter

### ISSUE THREAD

**Issue by urbas** [microsoft/vscode#89764]
The "Go to File..." popup should allow filtering files by the containing workspace folder.

This would be particularly useful when your workspace contains multiple folders each of which contains the same file at the top-level.

A common example is the `README.md` file. Say you want to find a `README.md` file from a particular workspace folder. Say you're looking for the `README.md` file in the folder called `my-folder`. Before this feature you'd have press the `Down` button a few times before you could get to the file.

With this feature you'd instead search for `mfREADME.md`. The desired readme file should now appear closer to the top of the file search popup.

Most closely related existing issue I could find is #81250, but the feature requested there would not resolve this feature request.

**Comment by roblourens** [comment]
Thanks for the issue and PR, unfortunately it's not that simple. I think it should only filter that way when in a workspace with multiple folders, not when a single folder is open. That means this will impact extension API for search providers. 

I have https://github.com/microsoft/vscode/issues/32444 for this, but your PR proves that this is pretty simple, so maybe I can get to it in Feb
