### ISSUE TITLE
JavaScript highlighting broken in Markdown preview

### ISSUE THREAD

**Issue by deunlee** [microsoft/vscode#89760]
- VSCode Version: 1.41.1 (also 1.42.0-insider)
- OS Version: Windows 10

Steps to Reproduce:

1. Open markdown file.
2. Type this code. (I think **`set` keyword** causes a problem.)

+ Error :
```js
const set = new Set([1, 2]);
for (const e of set)
console.log(e);
```

+ OK : 
```js
const set1 = new Set([1, 2]);
for (const e of set1)
console.log(e);
```

![aaaa](https://user-images.githubusercontent.com/54697735/73509617-11b77000-4423-11ea-9413-4704e7b1fa06.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The previews uses highlight.js out of the box. Please file an issue against them upstream
