### ISSUE TITLE
VSCode does not restore its window after minimized and called for open another file

### ISSUE THREAD

**Issue by vladon** [Microsoft/vscode#8976]
- VSCode Version: 1.3.0
- OS Version: Windows 10 Pro 1511 Build 10586.420

Steps to Reproduce:

1. Open VSCode
2. Minimize it
3. Open another file from any file manager, for example by pressing F4 in Total Commander (where VSCode is set as default editor)
4. VSCode does not restore its window, but just flashes in taskbar. One need to Alt-Tab to its window. It is uncomfortable.

**Comment by wtjones** [comment]
This also happens when using code.exe.

VSCode doesn't have to be minimized to demonstrate. If it is in the background, opening a file in the editor will not restore focus.

**Comment by vladon** [comment]
@wtjones Yes, I just checked and can confirm it.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/929
