### ISSUE TITLE
Extension Context Menu: 'Configure...' the name configure is not clear 

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#89769]
The extension context menu now has a 'Configure...' command that opens the settings editor for an extension's settings. This is great, but the name 'Configure...' is not clear:
![image](https://user-images.githubusercontent.com/172399/73529733-7cfb4500-4417-11ea-8b35-3919a51c8ffa.png)

Suggest to use 'Extension Settings'  (without ... since the command does not require further input). 

This is also consistent with the gear menu:

![image](https://user-images.githubusercontent.com/172399/73530044-06127c00-4418-11ea-980d-4cbaa76c69f5.png)

**Comment by sandy081** [comment]
It used to be `Configure Extension Settings` and I changed it to simplify. But if it is not clear I would prefer moving it back to what it was before.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/10746682/73531740-65be5680-441b-11ea-9e5d-f6ee3c6bcd04.png">

**Comment by egamma** [comment]
@sandy081 this is better. Since the main purpose of settings is to change them and to use them for configuration I don't think verb 'Configure' is needed.

We also do not use 'Configure Settings' and 'Configure Online Services Settings' in the gear menu: 

![image](https://user-images.githubusercontent.com/172399/73532363-d1ed8a00-441c-11ea-9867-c2445903d863.png)

**Comment by sandy081** [comment]
👍  Changed to `Extension Settings`
