### ISSUE TITLE
Launch debug session from terminal: "code-gdb --args ./mytool --foo"

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#89763]
(Originally reported at https://github.com/microsoft/vscode-cpptools/issues/4916 but I was told it belongs here.)

I often have the scenario that I have a terminal open where I'm running and testing a program that I'm developing. Wouldn't it be awesome if I could start a VS Code debug session directly from the terminal simply by prefixing my command with something like `code-gdb`?

The time it takes me to setup a real debug config in VS Code is insane, and often it's very specific to a certain command line -- I wouldn't commit that to source control. Starting debugging from the terminal eliminates this friction and would be a big productivity boost for me.

**Comment by isidorn** [comment]
Thanks for the suggestion however dup of https://github.com/microsoft/vscode/issues/10979
