### ISSUE TITLE
Warnings shown for devcontainer.json file

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#89768]
1. Create a folder
2. Add dev container configuration files
3. Open the `devContainer.json` file

-> you will see warnings for all properties

![image](https://user-images.githubusercontent.com/172399/73528983-2ccfb300-4416-11ea-8623-2284a5116fd9.png)

**Comment by egamma** [comment]
@chrmarti confirmed that this issue has been fixed, closing.

**Comment by chrmarti** [comment]
Fixed as https://github.com/microsoft/vscode-remote-release/issues/2265.
