### ISSUE TITLE
Suggest widget status bar setting should be show, not hide

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89772]
Should we switch the setting to be `Show status bar`, instead of `Hide status bar`?

I just got very confused as to why the status bar wasn't rendering, when the checkbox was checked.

**Comment by octref** [comment]
@joaomoreno The intention was that it'll be turned on by default in Insiders, during this iteration, to get feedback.

I followed `zenMode.hideStatusBar`, but maybe I should have followed `workbench.statusBar.visible`, what do you think?

**Comment by joaomoreno** [comment]
I prefer the `.visible` pattern.
