### ISSUE TITLE
Collapse Folders in Explorer no longer working

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89773]
Issue Type: <b>Bug</b>

With a folder open in a single container. (https://github.com/microsoft/vscode/issues/88146?)

VS Code version: Code - Insiders 1.42.0-insider (8d4cdbaa8d64514a5eb3b186b9a31b66cd8a9753, 2020-01-31T08:55:07.092Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.39GB free)|
|Process Argv|-psn_0_1724837|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (2.28GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
vscode-versionlens|pfl|0.24.0
vscode-open-in-github|sys|1.13.0
tsl-problem-matcher|eam|0.1.0
vscode-docker|ms-|0.10.0
remote-containers|ms-|0.100.0
remote-ssh-edit-nightly|ms-|2020.1.43083
remote-ssh-nightly|ms-|2020.1.43083
remote-wsl|ms-|0.42.1
debugger-for-chrome|msj|4.12.6

</details>

**Comment by isidorn** [comment]
<img width="507" alt="Screenshot 2020-01-31 at 11 37 42" src="https://user-images.githubusercontent.com/1926584/73532992-1cbbd180-441e-11ea-9e1f-50c33a18f4ec.png">

**Comment by joaomoreno** [comment]
Great catch! 🙏
