### ISSUE TITLE
Warning when undoing inside search editor

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89770]
Testing https://github.com/microsoft/vscode/issues/89396

1. Open new Search Editor
2. Search for anything
3. Focus the editor
4. Undo twice

![image](https://user-images.githubusercontent.com/22350/73530250-66092280-4418-11ea-9295-1ac3b45ea32d.png)

**Comment by JacksonKearl** [comment]
Fixed in 708877d8257a27107b841b5411a7add663ddc65c
