### ISSUE TITLE
JS highlighting in certain situations involving strings and HTML tags is incorrect.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#8978]
- VSCode Version: Code - Insiders 1.4.0-insider (4c0676ab472a92f5269ac4995cdc81db8bc94896, 2016-07-08T15:19:23.853Z)
- OS Version: Windows_NT ia32 10.0.14372

Steps to Reproduce:

* Open VS Code to a JS file
* Paste this snippet of code:
```js
var [] = 'fafa'.replace('blah');
console.log('hello');
```

* Observe the incorrect syntax highlighting following `var [] = '`

![image](https://cloud.githubusercontent.com/assets/494055/16702767/14f473a2-451d-11e6-9697-a204b3373be6.png)

* Also change the contents of the string at the end of the line to include angle brackets (like an HTML tag):
```js
var [] = 'fafa'.replace('<blah>');
console.log('hello');
```

![image](https://cloud.githubusercontent.com/assets/494055/16702817/66e81ccc-451d-11e6-8afb-beafd9274dcd.png)

* Also note highlighting of keywords inside and outside of braces:
```js
var [] = 'fafa'.replace('<blah>');
console.log('hello');
while { while() {} }
```

![image](https://cloud.githubusercontent.com/assets/494055/16702849/8fde68d4-451d-11e6-96d6-fb2ee2009f51.png)

Originally observed in this snippet of code:
![image](https://cloud.githubusercontent.com/assets/494055/16702633/2fa6a36a-451c-11e6-85c5-c7a8709f8898.png)

Is also an issue with double-quotes `"` instead of single quotes `'` and with or without semicolons.

Not running with any plugins. `code-insiders --disable-extensions`.

**Comment by joaomoreno** [comment]
@aeschli Is this #8045?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#203
