### ISSUE TITLE
Collapse folders in explorer no longer collapsing

### ISSUE THREAD

**Issue by s-xync** [microsoft/vscode#89787]
Issue Type: <b>Bug</b>

The collapse folder in explore no longer collapsing in the latest code-insiders update.

VS Code version: Code - Insiders 1.42.0-insider (8d4cdbaa8d64514a5eb3b186b9a31b66cd8a9753, 2020-01-31T08:55:07.092Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
bracket-pair-colorizer-2|Coe|0.0.29
vscode-clock|Com|0.0.1
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
vscode-eslint|dba|2.0.15
githistory|don|0.4.14
es7-react-js-snippets|dsz|2.5.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
edge|luo|0.3.2
select-highlight-minimap|mde|0.0.8
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
emoji|Per|0.0.3
material-icon-theme|PKi|3.9.2
highlight-matching-tag|vin|0.9.6
material-theme|zhu|3.2.1

</details>

**Comment by s-xync** [comment]
it is an old issue which has been closed. but the issue came up again.

**Comment by joaomoreno** [comment]
Fixed in `master` already.
