### ISSUE TITLE
Collapse all folders not working 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89789]
* today's insiders
* expand some folders in explorer 
* press collapse all
* :bug: nothing happens, no errors on the console

[Jan-31-2020 16-19-42.mp4.zip](https://github.com/microsoft/vscode/files/4140085/Jan-31-2020.16-19-42.mp4.zip)

**Comment by isidorn** [comment]
Thanks for filling this, however dup of https://github.com/microsoft/vscode/issues/89773
