### ISSUE TITLE
Eager creation/execution of update service in main process

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89784]
* run `code --prof-startup`
* you'll notice that in the main process *before* creating the renderer the update service takes its time (~5-10ms). while that's not much it seems unnecessary and "block" the renderer for no good reason

<img width="1101" alt="Screenshot 2020-01-31 at 14 45 07" src="https://user-images.githubusercontent.com/1794099/73544042-8f39ab00-4438-11ea-908c-60c3564b7e47.png">

**Comment by joaomoreno** [comment]
This is only problematic in macOS where `buildUpdateFeedUrl` calls into the native `electron.autoUpdater.setFeedURL` which blocks.

**Comment by jrieken** [comment]
Thanks
