### ISSUE TITLE
Add github.com to trusted badge providers

### ISSUE THREAD

**Issue by zawataki** [microsoft/vscode#89781]
Could you please consider adding `github.com` to the trusted badge providers?
The GitHub Actions generates a status badge like ![CI status on GitHub Actions](https://github.com/zawataki/vscode-mirai-translator/workflows/Build%20and%20Test/badge.svg).

Currently, `github.com` is not in the trusted badge providers, so `vsce publish` command fails with the error below: 
```
ERROR  SVGs are restricted in README.md; please use other file image formats, such as PNG
```

Thanks.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-vsce/issues/389

**Comment by zawataki** [comment]
Thank you for reporting the duplicate issue and closing.
