### ISSUE TITLE
Source control showing nothing

### ISSUE THREAD

**Issue by jorgelfons** [microsoft/vscode#89799]
There is pending versions, but nothing showing in the left bar.

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/32112292/73554540-ed0aca80-4419-11ea-9c53-046948d027d3.png)

**Comment by laurenclark** [comment]
I'm getting this too. 

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by sportshead** [comment]
Try reloading your window with <kbd>Cmd</kbd><kbd>R</kbd>.

**Comment by laurenclark** [comment]
I think I found a solution. Somehow the source control isn't looking at the current directory anymore you have to right click and make sure the tick is there in the dropdown, and then it seems to work! 

![Screenshot 2020-02-01 at 17 37 26](https://user-images.githubusercontent.com/5822683/73596374-8a98f380-4519-11ea-892b-5db45749c971.png)

**Comment by jorgelfons** [comment]
Thanks @laurenclark that works for me to !!!
