### ISSUE TITLE
Update manual smoke test

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89794]
- [x] Some sections (Data migration or loss, First time experience, Localization) should be excluded for VS Code Web or update how it can be supposed to test for VS Code Web.

- [x] Verify quick open sorting makes sense and it respects fuzzy matching (e.g. 'a.s' should produce 4 results) is showing only 3 results in all products

- [x] Debug section needs to be updated as the new view is shown now

**Comment by isidorn** [comment]
I have updated the manual smoke test.
@sandy081 and yes I would like the debug to remain in the manual smoke test, since with intregration tests I couldd cover 70% of what I want.

Thus closing this

**Comment by sandy081** [comment]
@isidorn If we run automated smoke tests in Endgame, then debug smoke tests will not be covered at all. So, does it makes sense to have them then?

**Comment by isidorn** [comment]
Yeah. I would like to keep the debug smoke tests in the manual one and not have them in the automatic one.
