### ISSUE TITLE
Snippet Tabstops prioritized over Snippet Expansion

### ISSUE THREAD

**Issue by kedestin** [microsoft/vscode#89793]
Issue Type: <b>Bug</b>
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

Description:

The snippet engine seems to prioritize moving to tabstops over attempting to expand snippets when pressing tab. This makes it hard to quickly expand nested snippets. Note, this behavior is only present when autocomplete is turned off. Leaving autocomplete on does make snippets behave as expected.

Steps to Reproduce:

1. Define snippets

```jsonc
        "Math Mode": {
                "prefix": "$",
                "body": "\\$${1:placeholder}\\$$0",
                "description": "Enter math mode"
        },
        "fraction": {
                "prefix": "\\frac",
                "body": "\\frac{${1:numerator}}{${2:denominator}}$0",
                "description": "Latex Fraction"
        }
```
2. Insert Math Mode Snippet

3. Attempt to insert fraction snippet while within math math snippet

![](https://i.imgur.com/SwLfzEY.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This setting will help you: editor.suggest.snippetsPreventQuickSuggestions
