### ISSUE TITLE
Weird scrollbar behavior

### ISSUE THREAD

**Issue by emzero** [Microsoft/vscode#8979]
- VSCode Version: 1.3.0
- OS Version: Win 7 x64 SP1

As soon as the the file being edited has more than one line, the vertical scrollbar appears even though it's not needed.
It seems that the end position of the scrollbars aligns with the last line of the file being the only one visible.

Is this the expected behavior? I don't remember being it this way in 1.2.0 and I don't think any other editor behaves like this.

![animation](https://cloud.githubusercontent.com/assets/412489/16703754/9684be4e-4546-11e6-8fa3-21277c901891.gif)

![image](https://cloud.githubusercontent.com/assets/412489/16703583/30703274-4545-11e6-95d3-aced827ad22f.png)

![image](https://cloud.githubusercontent.com/assets/412489/16703573/1d713bfa-4545-11e6-9289-487fd3cd30a4.png)

**Comment by bpasero** [comment]
Just set `editor.scrollBeyondLastLine: false` in settings
