### ISSUE TITLE
Configure tasks does not generate tasks.json

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#89790]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open empty folder in VS Code
2. `F1` > `Configure Task` > `Create tasks.json file from template`.

:bug: => nothing happens.

VS Code version: Code - Insiders 1.42.0-insider (be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b, 2020-01-31T13:53:58.701Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.9
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
xml|Dot|2.5.0
gitlens|eam|10.3.0-alpha
EditorConfig|Edi|0.14.4
vscode-pull-request-github-insiders|Git|2020.1.32642
latex-workshop|Jam|8.7.1
rainbow-csv|mec|1.5.0
openapi-lint|mer|1.0.4
vscode-azureappservice|ms-|0.16.2
vscode-docker|ms-|0.10.0
vscode-language-pack-ru|MS-|1.42.1
python|ms-|2020.1.58038
remote-containers|ms-|0.100.0
remote-ssh-edit-nightly|ms-|2020.1.43083
remote-ssh-nightly|ms-|2020.1.43083
remote-wsl|ms-|0.42.1
azure-account|ms-|0.8.8
csharp|ms-|1.21.9
js-debug-nightly|ms-|2020.1.43263
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vetur|oct|0.23.0
material-icon-theme|PKi|3.9.2
java|red|0.55.1
vscode-yaml|red|0.6.1
vscode-sort-json|ric|1.18.0
unittest-navigate|rob|0.0.2
vscode-autohotkey|sle|0.2.2
ayu|tea|0.18.0
vscode-java-debug|vsc|0.24.0
vscode-scope|yiw|0.0.21
markdown-all-in-one|yzh|2.7.0

(8 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Do you have any other setup instructions? I'm seeing a tasks.json get created
![configureTask](https://user-images.githubusercontent.com/38270282/73555536-1a716b80-444e-11ea-99a0-60c569ec9be6.gif)

**Comment by sbatten** [comment]
@alexr00 honestly not sure, I've tried with extensions disabled and just an empty folder but still I select the create from template option and then a small loading circle appears, disappears and nothing. no errors in console either.

**Comment by sbatten** [comment]
@alexr00 I finally figured out why this was happening. Doesn't seem major but I'll leave it to you for triage.

I happen to have `"tasks.terminal.windowsAllowConpty": true` still configured in my settings. 

The code below checks the config to determine if the task template prompt should be shown and does nothing if a config value is present.

https://github.com/microsoft/vscode/blob/bfc01bb9ea31d48133d6053de97dc7f8b2011b10/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2524-L2531

**Comment by alexr00** [comment]
The hit rate for that should be pretty low and I think that bad setting never made it past insiders, so not for February. Thanks for figuring it out!

**Comment by alexr00** [comment]
Actually, the bad setting only existed for 1 day. Not worth fixing, as the only person who will hit the issue (you, because you were involved in the other issues around that setting) has found the problem and worked around it.
