### ISSUE TITLE
Format code doesn't work for C# code

### ISSUE THREAD

**Issue by z2xlong** [Microsoft/vscode#898]
Format code doesn't work for C# code file on my mac, but it works for json file

**Comment by jrieken** [comment]
@z2xlong Please provide reproducible steps that. Also note that you must have an active project (project.json, mwsbuild-solution) for this to work.

**Comment by z2xlong** [comment]
Hi @jrieken , thanks for your reply. 
I can restore/build/run my project base on coreclr 1.0.0-rc1-final version on my mac, but can not just format code, neither trigger suggest via shortcut.
The VS code version is 0.10.3, project.json looks like:

{
  "version": "1.0.0-*",
  "description": "CSharpCode Console Application",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "tooling": {
    "defaultNamespace": "CSharpCode"
  },

  "dependencies": {
  },

  "commands": {
    "CSharpCode": "CSharpCode"
  },

  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}

**Comment by jrieken** [comment]
Thanks, can you also paste the omnisharp log please (Cmd+L, L)?

**Comment by jrieken** [comment]
@z2xlong Please provide the OmniSharp log. Only then I can reopen this

**Comment by shaneparsons** [comment]
@jrieken I'm having this issue as well. My OmniSharp log is empty.

**Comment by jrieken** [comment]
fyi - we have moved the omnisharp bits to it's own repo: https://github.com/OmniSharp/omnisharp-vscode.
