### ISSUE TITLE
Highlighting Issue in code cell in Jupyter Notebooks using Solarized Light Theme

### ISSUE THREAD

**Issue by graphitical** [microsoft/vscode#89809]
- VSCode Version: 1.41.1
- OS Version: MacOS 10.15.2

## Issue

Highlighting in a code cell within a Jupyter Notebook in VS Code while using the Solarized Light Theme results in an "invisible" highlight, with just the start/stop ends of the highlighting being visible. This issue has been resolved previously in the standard editor, but looks like has resurfaced with the introduction of Jupyter Notebooks in VS code.

#### Solarized Light
<img width="1440" alt="Screen Shot 2020-01-31 at 10 04 21 AM" src="https://user-images.githubusercontent.com/15367628/73564237-fb55e800-4413-11ea-8304-f1fe5df5848d.png">

#### Solarized Dark
<img width="1440" alt="Screen Shot 2020-01-31 at 10 04 08 AM" src="https://user-images.githubusercontent.com/15367628/73564265-0a3c9a80-4414-11ea-8bf7-792204dcd397.png">

## Previous resolved issues
1. [#24040](https://github.com/microsoft/vscode/issues/24040)
2. [#28343](https://github.com/microsoft/vscode/issues/28343)
3. [#24292](https://github.com/microsoft/vscode/issues/24292)

## Steps to Reproduce:

1. Set colortheme to 'Solarized Light' or 'Solarized Light +'
- Cmd-Shift-P (on Mac) --> Preferences: Color Theme --> Solarized Light (+)
2. Open .ipynb file in VS code
2. Generate a code cell
3. Highlight section inside code cell

Does this issue occur when all extensions are disabled?: ~~Yes/No~~
Disabling IPython extension results in a non-formatted .ipynb file so issue cannot exist since there isn't a code cell to evaluate against...so, technically no?

**Comment by plattenschieber** [comment]
I can confirm this issue in `Solarized Light`.

**Comment by rebornix** [comment]
Please file issues against the Python extension as the notebook features is provided by it at this moment.
