### ISSUE TITLE
Command variables in debug adapter freeze VSCode

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#8980]
- VSCode Version: 1.3.0 and insiders 4c0676ab472a9
- OS Version: Windows 10

I was trying out the feature [Debug Extension Authoring: Command Variables](https://code.visualstudio.com/Updates#_extension-authoring) for the Microsoft C++ extension.

Back when command variables [were introduced in master](https://github.com/Microsoft/vscode/issues/6569#issuecomment-222913734), it worked fine. However, now that 1.3.0 has been released, I tried again and on Windows the whole editor freezes for about 10 seconds when triggering the command that shows the list of processes as a quick pick dropdown.

I reproed this on my main Windows box, however it doesn't repro on a secondary box I have. I'm not restarting my main box in case you guys need the repro machine.

I took a CPU profile but it just shows `(program)` where it spent most of the time. From what I read online, that's just the actual Chromium code:

![image](https://cloud.githubusercontent.com/assets/637952/16703448/7668aaf4-4522-11e6-8e00-1ebf1dcb737d.png)

I also didn't really see much in the "Timeline" tab for the dev tools.

Also note that CPU usage for a VSCode process goes up:

![image](https://cloud.githubusercontent.com/assets/637952/16703922/76129b60-4526-11e6-9efb-5ac9c46029d1.png)

Let me know if you need the profiling dump and I can share it with you internally.

Mentioning @isidorn since he implemented command variables afaik.

**Comment by isidorn** [comment]
@edumunoz there was an issue with substituting command variables inside objects which might have effected this but might be unrelated.
Let me know if you see it again with tomorrow's insider. And if you see it can you share your project and launch.json with me so I try to repro on my machine - thanks!
