### ISSUE TITLE
Only use React icon for TSX resources within React projects

### ISSUE THREAD

**Issue by dylans** [microsoft/vscode#89808]
VS Code currently shows the React icon for all TSX files. JSX/TSX syntax are not exclusive to React applications.

The React logo should only be shown when the TSX file is in a React app to avoid confusing users of other frameworks from believing that the other framework leverages or uses React rather than just using the JSX/TSX syntax.

**Comment by mjbvz** [comment]
Extensions can configure the icon theme

**Comment by dylans** [comment]
> Extensions can configure the icon theme

While I agree with this statement, the current default behavior is confusing to non-React TSX users and should not require an extension in my opinion.

Or are you saying that this only occurs because of an extension I am using?
