### ISSUE TITLE
Consider removing "recently used" from first item in command palette 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#89816]
I'm opening this because of issue https://github.com/microsoft/vscode-python/issues/9826.

When you use the "Python: Select Interpreter" command, it will display a list of available Python interpreters that you can pick from. But whenever you open the command prompt again, it will show "Python: Select Interpreter" at the top, since it was the last used command, but it will also display a "recently used" tag by its side:

![image](https://user-images.githubusercontent.com/45497113/73568380-22fd7e00-441d-11ea-8959-70bce7545a94.png)

The problem is that like we see in issue  https://github.com/microsoft/vscode-python/issues/9826, some people think the "recently used" is related to the command itself (i.e. in this case, "select recently used interpreter").  Since the last used command is already shown on the highlighted on the top of the list, is it really necessary to add "recently used" to its side?

**Comment by bpasero** [comment]
I would not want to change this because you can see here how it is being used:

![image](https://user-images.githubusercontent.com/900690/73645432-94d10400-4677-11ea-91e3-24d901ac1799.png)

We use these blue group markers quite consistently throughout quick picks.

**Comment by yume-chan** [comment]
Maybe the "recently used" should be a header instead of a tag, and "other commands" should be called "all commands"?

![image](https://user-images.githubusercontent.com/1330321/73903970-808a4280-48d5-11ea-8ede-40b14804a780.png)

It looks pretty bad if the first command also has a keyboard shortcut.

**Comment by bpasero** [comment]
Commands which are in the "recently used" bucket are not in "other commands" so we cannot really rename it to "all commands".

**Comment by yume-chan** [comment]
> Commands which are in the "recently used" bucket are not in "other commands" so we cannot really rename it to "all commands".

@bpasero Oh I never knew that. My expectation was the two buckets are only sorted differently (by recently used or alphabetically).
