### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229)

### ISSUE THREAD

**Issue by xtianus79** [microsoft/vscode#89819]
- VSCode Version:
version 1.41
- OS Version:
MAC

Steps to Reproduce:

1. run debug through npm and port 9229
2. Here is json
```
"configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "start"
            ],
            "envFile": "${workspaceFolder}/.env.development",
            "port": 9229
        },
```
here is response: 
```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).
```

here are logs:
```
[20:39:47.869 UTC] Getting browser and debug protocol version via http://127.0.0.1:9229/json/version
[20:39:47.869 UTC] Discovering targets via http://127.0.0.1:9229/json/list
[20:39:47.870 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:47.870 UTC] There was an error connecting to http://127.0.0.1:9229/json/version : connect ECONNREFUSED 127.0.0.1:9229
[20:39:47.870 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:47.870 UTC] Discovering targets via http://127.0.0.1:9229/json
[20:39:47.871 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.075 UTC] Getting browser and debug protocol version via http://127.0.0.1:9229/json/version
[20:39:48.075 UTC] Discovering targets via http://127.0.0.1:9229/json/list
[20:39:48.076 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.076 UTC] There was an error connecting to http://127.0.0.1:9229/json/version : connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.076 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.076 UTC] Discovering targets via http://127.0.0.1:9229/json
[20:39:48.076 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.280 UTC] Getting browser and debug protocol version via http://127.0.0.1:9229/json/version
[20:39:48.280 UTC] Discovering targets via http://127.0.0.1:9229/json/list
[20:39:48.281 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.281 UTC] There was an error connecting to http://127.0.0.1:9229/json/version : connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.281 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229
[20:39:48.281 UTC] Discovering targets via http://127.0.0.1:9229/json
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ashwamegh** [comment]
It may occur because of the reasons:
- Your code is failing
- You don't have sufficient memory

Anyways, the default timeout is of 10000ms. 
You can change that default value in the config json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    {
        "type": "node",
        "request": "launch",
        "name": "nodemon",
        "runtimeArgs": ["NODE_ENV=development"],
        "runtimeExecutable": "nodemon",
        "program": "${workspaceFolder}/index.js",
        "restart": true,
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        "skipFiles": [
            "<node_internals>/**"
        ],
        "timeout": 20000
    }
    ]
}
```

**Comment by weinand** [comment]
It looks like nobody is listening on the debug port 9229.
@xtianus79 does your npm "start" script configure node to be run in debug mode?

**Comment by xtianus79** [comment]
Ok I'm going yo try that. Thanks for the link. I will update when I add this in

**Comment by sheunaluko** [comment]
was this resolved?

**Comment by thebat93** [comment]
I have the same issue after updating to 1.43.0

**Comment by weinand** [comment]
@thebat93 How does your launch config look like?

**Comment by thebat93** [comment]
I'm starting a Next.js custom server like this
`    {
      "type": "node",
      "request": "launch",
      "name": "Next: Server",
      "runtimeVersion": "13.0.1",
      "runtimeArgs": ["server.js"],
      "smartStep": false,
      "env": {
        "NODE_PATH": "${workspaceFolder}",
        "NODE_OPTIONS": "--inspect",
        "DEBUG": "site:api:http"
      },
      "restart": true,
      "port": 9229,
      "console": "integratedTerminal"
    },`

This config successfully works for me:
`    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "runtimeVersion": "13.0.1",
      "program": "${workspaceFolder}/server.js",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "env": {
        "NODE_PATH": "${workspaceFolder}"
      }
    },`

But I still get the same error when trying to connect to a nodemon process with Attach config:
`    {
      "type": "node",
      "request": "attach",
      "name": "Node: Nodemon",
      "processId": "${command:PickProcess}",
      "restart": true,
      "protocol": "inspector",
  },`

I'm choosing the correct Nodemon process PID, but get the timeout error

**Comment by sheunaluko** [comment]
Not sure if any of you are having this problem - but I originally was getting this error then realized I had not set any breakpoints yet, so my script was just running and exiting before the debugger could connect to it.  

Make sure you have breakpoints set in your code in order to pause the node script and allow debugger to connect :)

**Comment by TylerSustare** [comment]
This is also happening to me using Create React App with typescript template. this is my launch.json
``` json
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch via NPM",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run-script", "start"],
      "port": 9229,
      "skipFiles": ["<node_internals>/**"]
    }
  ]
}
```
My `start` script is the default for CRA 
```json 
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
```

**Comment by weinand** [comment]
@TylerSustare does your npm "start" script really enable debugging?
"react-scripts start" does not sound like debugging to me...

**Comment by pierce-h** [comment]
@thebat93 were you able to figure this out? I am trying to get this setup with a next.js app as well. Thanks!

**Comment by thebat93** [comment]
@pierce-h no. I have the following new config for debugging Node.js. It uses a custom express server to run the app.
```
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "runtimeVersion": "13.0.1",
      "program": "${workspaceFolder}/server.js",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "env": {
        "NODE_PATH": "${workspaceFolder}"
      }
    }
```

**Comment by pierce-h** [comment]
@thebat93 thank you so much for getting back to me! So that launch config allows you to debug the node/server side code but not the browser? Did you have to do anything special with your npm scripts in your package.json? Here are mine currently.

```
  "scripts": {
    "dev": "NODE_OPTIONS='--inspect' next",
    "build": "next build",
    "start": "next start -p $PORT",
    "quality": "eslint . --ext .ts,.tsx && jest",
    "test": "jest"
  },
```

**Comment by thebat93** [comment]
@pierce-h yes, I only need to debug the express route handlers and server rendering rendering of next.js app.
My launch config doesn't run any script in `package.json`. It just runs the file that I specified with this string: `${workspaceFolder}/server.js"`. I have a few other environment variables in the `env` property of the config, but left them out because of security reasons.
