### ISSUE TITLE
Cannot scroll settings with keyboard, middle mouse click, or up/down arrows

### ISSUE THREAD

**Issue by timhermann** [microsoft/vscode#89814]
Issue Type: <b>Bug</b>

With a lot of settings, the scroll indicator is tiny. Trying to scroll only a couple lines down to finish reading truncated text is nearly impossible as there are no arrows for small scrolling in VSCode and neither the arrow keys, page up/down, nor middle click can be used to invoke a slow scrolling state. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (15.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.33.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.6
docs-images|doc|0.0.4
docs-markdown|doc|0.2.37
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.38
docs-yaml|doc|0.2.4
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
swagger-doc-viewer|mim|1.0.4
vscode-service-fabric-reliable-services|ms-|0.1.6
python|ms-|2020.1.58038
sarif-viewer|MS-|2.14.0
remote-wsl|ms-|0.41.7
cpptools|ms-|0.26.3
csharp|ms-|1.21.9
Go|ms-|0.12.0
powershell|ms-|2020.1.0
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.3
vscode-yaml|red|0.6.1
code-spell-checker|str|1.7.22

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/66237
