### ISSUE TITLE
MEMORY KILLER!

### ISSUE THREAD

**Issue by SakamotoLfe** [microsoft/vscode#89827]
Issue Type: <b>Bug</b>

Right, i don't know why but, when i save or do something the Visual Studio Code just EAT all my RAM!! I have 32Gb RAM and right now he's eating more than 23GB!!!! HELP!

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.900.8
vscode-mysql-manager|cwe|1.5.2
vscode-simpler-icons|dav|1.6.5
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.20.0
vscode-npm|fkn|3.3.0
angular-essentials|joh|0.6.3
Angular2|joh|8.3.0
vscode-peacock|joh|3.3.1
Angular-BeastCode|Mik|8.1.2
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
angular2-inline|nat|0.0.17
angular-console|nrw|10.0.0
vscode-versionlens|pfl|0.24.0
vscode-spring-boot|Piv|1.15.0
material-icon-theme|PKi|3.9.2
java|red|0.55.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-icons|vsc|9.7.0

(2 theme extensions excluded)

</details>

**Comment by SakamotoLfe** [comment]
I just found the process that is causing the issue.
3	203	19712	             electron_node tsserver.js 
What should i do?

**Comment by BitesizedLion** [comment]
Well you do have 31 extensions... maybe try disabling them?

**Comment by jeanp413** [comment]
@SakamotoLfe  I think this is a duplicate of #85919

**Comment by SakamotoLfe** [comment]
Well, probably yes! I've removed the Prettier extension and the issue isn't occouring animore. I think is fixed! But, this bug you mentioned, they sayd that is a bug on the TS editor extension, I noticed that this issue that occour with me just occour on TS files, when I save or press crtl + space or alt + shift + F. But, for now, it's fixed! Thank you guys!
