### ISSUE TITLE
launch.json: values from envFile not substituted in args

### ISSUE THREAD

**Issue by endquote** [microsoft/vscode#89825]
A simple repro:

#### index.js
```javascript
console.log(process.argv);
```

#### .env
```
FOO=bar
```

#### launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceFolder}/index.js",
      "args": ["--user=${env:USER}", "--foo=${env:FOO}"],
      "envFile": "${workspaceFolder}/.env"
    }
  ]
}
```

When debugging, the output is:

```
... "--user=joshs", "--foo="
```

The `foo` variable defined in .env isn't passed through.

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

**Comment by isidorn** [comment]
This is currently not supported because this would be sort of a two step substition. The configuration resovler service is currently unaware of meaning of these attributes and it can not first substititute envFile and then the rest.
However this is a valid feature request, thus leaving it open and assigning to backlog

fyi @alexr00

**Comment by chriscamplejohn** [comment]
@isidorn would you expect it to work when the env vars are stored in user settings under "terminal.integrated.env.osx" or if they are stored in launch.json in the env property? I cannot get env substitutions to work at all on macOS. Is there anyway to get it to pick up OS environment variables?

**Comment by weinand** [comment]
The ".env" file is read and processed **after** VS Code has substituted variables in the launch config. So your program will indeed see the environment variable "FOO" with the correct value but VS Code's variable substitution in the launch.json will not see it.

The reason for this is that ".env" files are a node.js concept and not a generic platform mechanism. So VS Code does not know anything about .env files, but the node.js debugger knows about .env files.

**Comment by chriscamplejohn** [comment]
That makes sense in the context of node and .env files, but with regards to the vs code ${env:_Name_} substitutions, is that expected to pick up OS environment variables?

**Comment by weinand** [comment]
Sure, `${env:Name}` is expected to pick up OS environment variables. But it can not pick up anything from an .env file that is processed **after** `${env:Name}` has been substituted.

**Comment by dellagustin-sap** [comment]
So, `envFile` seems to be specific to some debuggers (maybe only node? I did not check, - https://code.visualstudio.com/docs/nodejs/nodejs-debugging), but what I actually miss is a way for user specific variable substitution that does not require OS environment variables.

Supporting some kind of `.env` file that I can exclude from my repo using `.gitignore` would be helpful.

**Comment by weinand** [comment]
@dellagustin-sap you can easily reference VS Code settings as variables through the `${config:name}` syntax.

So add a variable to your settings with this `"myVariable": "foobar"` and then you can use it in launch.json or task.json with `${config:myVariable}`.

As always see our documentation: https://code.visualstudio.com/docs/editor/variables-reference#_configuration-variables

**Comment by weinand** [comment]
Closing, since VS Code provides a solution (see my last comment)
