### ISSUE TITLE
Extension API Request for `when` from keybindings

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#89839]
It would be quite useful to be able to programmatically ask VS Code whether a [`when` condition](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) is true.

Use cases:

* Show all currently applicable keybindings (by parsing the default keybindings json and evaluating all when conditions)
* Custom Status Bar items which are only visible on certain conditions that are defined by the user

This is a duplicate of #77630 which itself was flagged as duplicate, but I never found the original issue.

**Comment by usernamehw** [comment]
#10471

**Comment by hediet** [comment]
Thanks, @usernamehw! The mentioned issue is mostly about `setContext` while I am more interested in `getContext` but that is also discussed there, so I'll close this one.
