### ISSUE TITLE
Suggestion to add firt or any letter as shortcut to command id "editor.action.refactor

### ISSUE THREAD

**Issue by LoveraSantiago** [microsoft/vscode#89831]
Hello good night.

On command id "editor.action.refactor" it shows a window to select several options to refactor my code. (I'm using java).

It's there a page to teach how to do it.
https://code.visualstudio.com/docs/java/java-editing#_refactoring-and-code-actions

I would like as user, to select one option with just one keyboard action (could be any or first letter of options) and dont have to press arrow down on keyboard a couple of times to select the option that I want.

*I would like to ask where I can see the code definition to command id "editor.action.refactor" to try to make a workaround to me?

Thanks.

I just love vscode.

**Comment by sportshead** [comment]
@LoveraSantiago You can edit and set keybindings by pressing <kbd>Ctrl</kbd>+<kbd>K</kbd> then <kbd>Ctrl</kbd>+<kbd>S</kbd> (or <kbd>Cmd</kbd>+<kbd>K</kbd> then <kbd>Cmd</kbd>+<kbd>S</kbd> on mac). Here you can set the keybinding for `editor.action.refactor` by searching for it.

The default keybinding for `editor.action.refactor` is <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>  (same for both platforms) if you don't want to change the settings.

**Comment by LoveraSantiago** [comment]
@sportshead  thank you.

As I could understand when I call the keybinding  Ctrl+Shift+R vscode runs the command "editor.action.refactor". Where I can see the code of this command, please?

**Comment by mjbvz** [comment]
[This documentation](https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions) describes how to configure keybindings for specific refactorings
