### ISSUE TITLE
Omnisharp error when starting VSCODE from unity3d

### ISSUE THREAD

**Issue by ziad10a** [microsoft/vscode#89835]
Hi,
I've made VSCODE the main IDE for unity in Ubuntu and whenever I open a script it shows me an error, also I can't use the "Go to definition" feature.

Using:

- VSCode Version: 1.41.1
- OS Version: Ubuntu 18.04.3
- Unity3D Version: 019.3.0f6

Steps to Reproduce:

1. Double clicking a c# script from within unity3d editor

Error:

Starting OmniSharp server at 2/1/2020, 12:02:17 PM
Target: /home/ziad/UnityProjects/IdleNumbers/IdleNumbers.sln

OmniSharp server started.
Path: /home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run
PID: 15402

Starting OmniSharp on ubuntu 18.4 (x64)
info: OmniSharp.Services.DotNetCliService
DotNetPath set to dotnet
info: OmniSharp.MSBuild.Discovery.MSBuildLocator
Located 1 MSBuild instance(s)
1: StandAlone 16.3 - "/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin"
info: OmniSharp.MSBuild.Discovery.MSBuildLocator
MSBUILD_EXE_PATH environment variable set to '/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
info: OmniSharp.MSBuild.Discovery.MSBuildLocator
Registered MSBuild instance: StandAlone 16.3 - "/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin"
CscToolExe = csc.exe
MSBuildToolsPath = /home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin
CscToolPath = /home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Roslyn
BypassFrameworkInstallChecks = true
MSBuildExtensionsPath = /home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild
info: OmniSharp.Cake.CakeProjectSystem
Detecting Cake files in '/home/ziad/UnityProjects/IdleNumbers'.
info: OmniSharp.Cake.CakeProjectSystem
Could not find any Cake files
info: OmniSharp.MSBuild.ProjectSystem
Detecting projects in '/home/ziad/UnityProjects/IdleNumbers/IdleNumbers.sln'.
info: OmniSharp.MSBuild.ProjectManager
Queue project update for '/home/ziad/UnityProjects/IdleNumbers/Assembly-CSharp.csproj'
info: OmniSharp.Script.ScriptProjectSystem
Detecting CSX files in '/home/ziad/UnityProjects/IdleNumbers'.
info: OmniSharp.Script.ScriptProjectSystem
Could not find any CSX files
info: OmniSharp.WorkspaceInitializer
Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
info: OmniSharp.MSBuild.ProjectManager
Loading project: /home/ziad/UnityProjects/IdleNumbers/Assembly-CSharp.csproj
info: OmniSharp.WorkspaceInitializer
Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
info: OmniSharp.WorkspaceInitializer
Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
info: OmniSharp.WorkspaceInitializer
Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
info: OmniSharp.WorkspaceInitializer
Configuration finished.
info: OmniSharp.Stdio.Host
Omnisharp server running using Stdio at location '/home/ziad/UnityProjects/IdleNumbers' on host 15298.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.Timeline.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.VSCode.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.Recorder.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.Recorder.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'UnityEngine.UI.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.Timeline.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.CollabProxy.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.Rider.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.2D.Sprite.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.2D.Tilemap.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'Unity.Analytics.DataPrivacy.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
The referenced project 'UnityEditor.UI.csproj' does not exist.
fail: OmniSharp.MSBuild.ProjectLoader
The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
Failed to load project file '/home/ziad/UnityProjects/IdleNumbers/Assembly-CSharp.csproj'.
/home/ziad/UnityProjects/IdleNumbers/Assembly-CSharp.csproj
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.Timeline.Editor.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.VSCode.Editor.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.Recorder.Editor.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.Recorder.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'UnityEngine.UI.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.Timeline.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.CollabProxy.Editor.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.Rider.Editor.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.2D.Sprite.Editor.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.2D.Tilemap.Editor.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'Unity.Analytics.DataPrivacy.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1895,5): Error: The referenced project 'UnityEditor.UI.csproj' does not exist.
/home/ziad/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1191,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

Attempted to update project that is not loaded: /home/ziad/UnityProjects/IdleNumbers/Assembly-CSharp.csproj

**Comment by gjsjohnmurray** [comment]
/causedByExtension see https://github.com/OmniSharp/omnisharp-vscode
