### ISSUE TITLE
Closing a dirty split editor (existing OR untitled) should not affect the initial editor

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#8983]
- VSCode Version: 1.3.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Open (or create) a file.
2. Split the editor.
3. Add some text in either editor.
4. Close either editor.
5. Select "Don't save" when prompted.

There are two end states produced by these steps:

#### When an existing file is used
The other editor remains, but the text is reverted to the state on disc.

#### When a file is created
The other editor is also closed.

**Comment by bpasero** [comment]
This is interesting. In ST you can close the dirty one and the other one remains dirty. In Atom, they actually allow you to close a dirty one without being prompted.

@stevencl @bgashler1 fyi, I do like our current behaviour and would not change it though.

**Comment by bpasero** [comment]
@stevencl and interestingly, VS also does not ask to save when closing the second dirty editor! maybe we should revisit this :)?

**Comment by zbjornson** [comment]
Came across this after posting to uservoice:

https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/15156702-don-t-prompt-to-save-when-closing-a-file-tab-that

**Comment by bgashler1** [comment]
I remember initially suggesting not prompting if there is another dirty editor still open, but we hypothesized that users would be afraid they lost changes if there wasn't a prompt every time, no matter how many instances are open.

@bpasero I think it would be good to revisit this in light of user feedback that's coming in.  Let's put this on the UX agenda for when @stevencl is back.  I know he will want to have a say in this.

**Comment by bpasero** [comment]
Yes, 👍

**Comment by mysticatea** [comment]
For what it's worth, I'm surprised that I have lost my editing...

![lost](https://cloud.githubusercontent.com/assets/1937871/16984780/36136310-4eb7-11e6-9450-d00183ad1ad6.gif)

**Comment by stevencl** [comment]
Thanks for the feedback. I agree, the current behaviour for closing split editors needs a little finessing.

We have a couple of options:

1. Don't prompt when the user closes a dirty split editor. Only prompt when the user closes the initial editor (when dirty).
2. Prompt, but preserve the state in the initial editor if the user chooses 'don't save'. We would need to change the text on the dialog so that it doesn't say that the changes will be lost.

Whichever option we choose, the behaviour should be the same regardless of whether or not the file exists on disk or if the user is editing an untitled file.

**Comment by zbjornson** [comment]
Option 1 is closer to what it was before tabs I think: no matter what, if you closed an editor there would be no prompt, the file would remain open in the sidebar, right?

**Comment by bgashler1** [comment]
**UX meeting notes:**
We agree that we should no longer prompt users to save when they close a dirty editor if there is another duplicate editor still open.  However, we will wait until the August milestone to get one last team member’s feedback before making the change.

**Comment by bpasero** [comment]
Pushed a change to not ask for saving when the editor to close is opened in another group. This should work for all our actions that close editors (close all, close group, close editor, etc.)
