### ISSUE TITLE
Partial folder expand in explorer

### ISSUE THREAD

**Issue by horsten** [microsoft/vscode#89849]
Issue Type: <b>Feature Request</b>

When navigating to a file e.g. in node_modules, the whole of the node_modules tree expands even though 99% of it is irrelevant to what I'm looking at.

What I'm looking for is a feature so that, for certain folders either with more than x entries or named specifically (e.g. node_modules), it will not expand the whole folder by default but put ellipses above and below the currently expanded subfolder. Easier to explain with a picture, see below.

This would remove a lot of cruft from the sidebar and make the important directories for my project still reachable without having to scroll up and up and up and collapse the whole node_js tree.

Here are the pictures, imagine "_before" and "Z_after" being clickable [...] icons.

What I'd like to see:

![vscode-collapse2](https://user-images.githubusercontent.com/3442409/73599396-6520df80-4543-11ea-85c3-26aca2198658.png)

What it looks like now:

![vscode-collapse1](https://user-images.githubusercontent.com/3442409/73599394-5f2afe80-4543-11ea-9360-684d199534fd.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.15.0-74-generic
Remote OS version: Linux x64 4.15.0-74-generic
Remote OS version: Linux x64 4.15.0-74-generic

**Comment by horsten** [comment]
Just to make it even clearer, I made a more realistic mockup in Paint:

![vscode-collapse3](https://user-images.githubusercontent.com/3442409/73599609-8c78ac00-4545-11ea-822c-cdb6a56b17fb.png)

**Comment by Adondriel** [comment]
Personally, I think the "click to show X hidden folders" being at the top & bottom would get annoying. It should just be one or the other (top would be my preference, but this could easily be a new option)

**Comment by thelazydogsback** [comment]
Also see #88810 to approach this issue in a different way
