### ISSUE TITLE
No intellisense for external JS files

### ISSUE THREAD

**Issue by anon176** [microsoft/vscode#89847]
Folder structure:
```
├── index.html
├── jsconfig.json
├── main.js
└── pixi.js
```

I added pixi.js and main.js to my html file. I can use the pixi library from main.js but I just don't get intellisense.

jsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
  },
  "exclude": ["node_modules"],
  "include": ["pixi.js"]
}
```
I also tried adding `/// <reference path="pixi.js" />` to main.js but that did not give me intellisense.

**Comment by mjbvz** [comment]
You should generally not copy the source code of libraries into your workspace. Try using `npm` if possible

If that will not work, please share your project on stackOverflow so that someone can help you configure it correctly

**Comment by anon176** [comment]
Well I'm specifically trying not to use npm... Plus, my project structure cannot be any simpler. It's an html file with 2 javascript files. 
Anyways, I just found this strange but a lot of things are strange with javascript.
