### ISSUE TITLE
VSCode stops responding with long line like "((a+a) (a+a) (a+a) (a+a) ..." when in C# language

### ISSUE THREAD

**Issue by Maxpxt** [microsoft/vscode#89846]
Issue Type: <b>Bug</b>

Create a file in plain text mode and fill it with:
`((a+a)` + ~30 times <code>&emsp;(a+a)</code>, which looks like `((a+a) (a+a) (a+a) (a+a) ...`

Change the file language to C#.

This causes VSCode to stop responding.

This does not happen with other languages like C++, F#, Java, JavaScript.

Interestingly, in the following slight variations of this, everything works fine.

* `(` on line 1 + `(a+a) (a+a) (a+a) (a+a) ...` on line 2
* `((a+a)(a+a)(a+a)(a+a) ...`

When the line is smaller (around 15 to 20 times <code>&emsp;(a+a)</code>), the the editor does not stop responding, but takes long to respond to any changes made to the file (like typing a letter). The larger the line, the longer it takes.

If it is not possible to easily fix this, it would be nice to, instead of the current "not responding, would you like to restart" message, have something like "The \<whatever is hanging\> is not responding. Would you like to view this file in plain text mode instead? \<button to change to plain text\>"

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
Moved the grammar issue to the repo that owns the grammar, and opened a separate issue for grammars not being able to freeze VS Code.
