### ISSUE TITLE
VS Code: Unable to add folder to untitled workspace

### ISSUE THREAD

**Issue by ianwashburn** [microsoft/vscode#89843]
I cannot add a folder to a workspace in VS Code. The workspace was called "untitled workspace" however the folders and files accessed by VS Code are in a path called: C:\Users\ianwa\Google Drive\All Sync\js_practice\react-course. The folder name where the project folders and files are in is called "react-course." I am on a PC using running Windows 10. 

These are the steps to reproduce my issue:

1. Highlight Workspace
2. Click File > Add Folder to Workspace
3. File explorer opens
4. Enter folder name and click Add
5. Modal warning displays: Path does not exist. Check the path and try again.

Also, when I create the folder in file explorer, the folder does not appear in the workspace, however files in already created folders appear. I have tried refreshing after folder creation.

I tried to rename the workspace to the same name as the parent folder. I tried to rename it to a different name. Nothing takes.

![newFolder](https://user-images.githubusercontent.com/32419323/73596494-7391db80-44f0-11ea-877b-df7e6c50f914.PNG)

**Comment by ianwashburn** [comment]
I did work my way around this by not using a worskpace and just opening the folder using the explorer for VS Code.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
