### ISSUE TITLE
Builtin HTML, CSS and JS preprocessors like in CodePen

### ISSUE THREAD

**Issue by GladunovDenis** [microsoft/vscode#89845]
I work with html documents most of the time, and i like vscode a lot in that way, especially builtin emmet. But recently i found out that it's easier for me to work with HTML, CSS and JS in CodePen actually, because of popular already builtin preprocessors like HAML, SCSS, TypeScript. I know that vscode supports these via extensions, but to setup everything properly takes some effort, whereas in CodePen you get them "for free" (without using ruby or js) + realtime preview of changes made to the document.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/12080 goes in the same direction.
What CodePen is is a server that watches files, runs build scripts and has a web server running http://livereload.com/ is something similar that also runs on a local machine. 

VSCode is foremost a code editor and typically we keep out of build scripts and running servers. It's also hard to decide which live preview server technology to choose.
But this is a good extension opportunity.
