### ISSUE TITLE
Live Share

### ISSUE THREAD

**Issue by mprodhan** [microsoft/vscode#89848]
Issue Type: <b>Feature Request</b>

The user code for live share is not working. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
