### ISSUE TITLE
Ubuntu extension manager not working properly

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#8984]
- VSCode Version: 1.3.0	
- OS Version: Ubuntu 16.04

I have extensions installed, but they do not show up. I can not install them either. here are some screen shots:

![screenshot from 2016-07-08 19-35-55](https://cloud.githubusercontent.com/assets/1571806/16704911/570e02a0-4543-11e6-85b8-7f994ed826bd.png)

![screenshot from 2016-07-08 19-40-41](https://cloud.githubusercontent.com/assets/1571806/16704962/f738c1f2-4543-11e6-8ffa-febdebfd77b1.png)

![screenshot from 2016-07-08 19-41-01](https://cloud.githubusercontent.com/assets/1571806/16704961/f7341d78-4543-11e6-9f63-f355a3ba7d88.png)

**Comment by sebadoom** [comment]
I am seeing this too on Arch using the latest stable release (1.3.0):

https://az764295.vo.msecnd.net/stable/1.3.0/VSCode-linux-x64-stable.zip

**Comment by sebadoom** [comment]
#8967 has a workaround for this: delete the $HOME/.cache/Code directory after closing all instances of Visual Studio Code (killall code might be necessary if they are running in the background).

**Comment by tony-garcia** [comment]
@sebadoom -- your workaround worked for me (had to do killall code). Thanks.

**Comment by RemKolomna** [comment]
I'm experiencing the same issue. However command code --install-extension ms-vscode.csharp works perfectly!

**Comment by TheColorRed** [comment]
That workaround fixed it!

```
killall code
rm -rf ~/.cache/Code
```

**Comment by zealotds** [comment]
In my case, also needs to remove ~/.vscode (Ubuntu 14.04LTS)

**Comment by GregoryLundberg** [comment]
On Arch, none of the workarounds helped for me. Not a big problem since I'm not using any for the project I'm working on right now (there are none) but it would be nice to be able to use extensions in the future.

**Comment by sebadoom** [comment]
@GregoryLundberg did you run ```killall code``` from a terminal before removing ~/.cache/Code. I'm on Arch too and this worked.

**Comment by joaomoreno** [comment]
#8859 (see last comment)
