### ISSUE TITLE
Ruby Syntax Highlighting Incorrectly parses a string as regex

### ISSUE THREAD

**Issue by Pugio** [microsoft/vscode#89858]
Issue Type: <b>Bug</b>

```ruby
a = base_path / 'sub/origin'
```
Incorrectly tries to highlight: `/'sub/o` as a regex, breaking the rest of page's highlighting.

This only seems to occur when the second slash has the letters "or" after it, and in no other case I tried.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 17.7.0

<img width="264" alt="image" src="https://user-images.githubusercontent.com/286180/73603844-1a9f7180-45dc-11ea-8f17-e9e1af75ae99.png">

**Comment by alexr00** [comment]
I can't reproduce the issue with that example:
![image](https://user-images.githubusercontent.com/38270282/73732136-f5287a00-4739-11ea-87f4-8920a86ceaf9.png)
Please try disabling all extensions to find the one that is causing the problem.
