### ISSUE TITLE
Sticky Headers in the Explorer Tree view?

### ISSUE THREAD

**Issue by minig0d** [microsoft/vscode#89856]
I saw there had been a few similar issues in the past that people had raised without luck, but I'm hoping a visual aid may help demonstrate why this could be needed or maybe inspire an alternate solution that you would be willing to consider....

The explorer view is very cumbersome to scroll through and find the correct file quickly while "keeping your place" especially in projects with lots of files/folders.  It's likely not as big an issue for developers in projects with smaller amounts of files (ex. smaller C# and node ones), but in certain cases like (modern) web design (especially with CMS's and multiple frameworks/libraries, the file system can be quite extensive.

Matter of fact, so extensive, that it's pretty easy for there to be so many files that you cant even see a SINGLE parent folder as a frame of reference (ex. second screenshot)

Multi-Root workspaces further make it difficult in incorporating even more file systems into an already cramped space and the potential to have side by side directories with similar or even identical structures (ex. DEV/PROD servers,  v1.0 / v1.1alpha, etc.)

Given the number of people who could benefit and the potential harm from inadvertantly editing a wrong file instance, I do believe it's worth it to rehash this (especially since some of the previous requests were prior to multi-root).  

I really have no opinion on whether sticky headers, statusbar indication, breadcrumbs, a two panel file browser, or horizontal tabs (one for each WS, rather than vertical stacking) is ideal, but all of these could be viable resolutions and surely one of them couldn't be too difficult to implement, while benefiting a large percentage of Code users.

It's very hard to demonstrate in a photo, this top screenshot is as small of a font as I can handle, on a 1920x1080 24" monitor... (it's even worse on a laptop...)
![image](https://user-images.githubusercontent.com/54046315/73602498-803b2180-453a-11ea-80e5-f7e5ba62cd8c.png)

![2020-02-01_22h00_23](https://user-images.githubusercontent.com/54046315/73602760-53890900-453e-11ea-999a-23cead5e95d2.png)

**Comment by yume-chan** [comment]
It's so difficult to find where I am in the explorer, so I always collapse all then expand folders one by one to find the file I want. Or I just use <kbd>Ctrl</kbd> + <kbd>P</kbd>.

However I'm a little bit concerned about how many characters can fit in the sticky header, if the current file is deeply nested.

**Comment by minig0d** [comment]
> It's so difficult to find where I am in the explorer, so I always collapse all then expand folders one by one to find the file I want. Or I just use Ctrl + P.
> 
> However I'm a little bit concerned about how many characters can fit in the sticky header, if the current file is deeply nested.
Agree.  I'm not quite sure if these are the best answer.  Potentially a multi-layered sticky header or showing the first few letters of each path segment would help.  Or while it may be a little awkward to look at, maybe actively showing the path in the status bar would be an acceptable compromise?  Or maybe it should be the sticky bar, except the bar popped out of the sidebar into a floating bar while it was active and collapsed back while not.  

what about more of a floating popup that was wider than the bar but collapsed when not in use?  Surely the wheel doesn't need to be reinvented for something so basic....  
![2020-02-05_02h43_08](https://user-images.githubusercontent.com/54046315/73825978-922ef580-47c2-11ea-8da5-1ea371924ae2.png)
