### ISSUE TITLE
npm extension: unable to debug script in subdirectory from NPM Scripts view

### ISSUE THREAD

**Issue by kherock** [microsoft/vscode#89854]
- VSCode Version: 1.14.1 (user setup)
- OS Version: Windows 10 18362

Steps to Reproduce:

1. Open a folder with `package.json` at the root to enable the NPM Scripts panel
2. In a subfolder, initialize a new npm project, and add a script with a debug line:
```json
{
  "name": "example",
  "scripts": {
    "start": "node --inspect=9229 example.js"
  }
}
```
3. In the NPM Scripts panel, click on the debug icon action for the task created above. VSCode will notify with the error:
> Error running command npm.debugScript: Cannot read property 'match' of undefined. This is likely caused by the extension that contributes npm.debugScript.

I believe the error is thrown here:
https://github.com/microsoft/vscode/blob/c4309702c525d61b34bb6403a121a0595a473974/extensions/npm/src/npmView.ts#L148-L150

where `scripts[task.name]` is actually `undefined`.

Does this issue occur when all extensions are disabled?: Yes (NPM extension is built in)

**Comment by egamma** [comment]
Debugging npm scripts is now so much simpler/better with the new JS debugger please give it a try https://code.visualstudio.com/updates/v1_46#_new-javascript-debugger.

We should consider deprecating/removing this feature.
