### ISSUE TITLE
Have collapse phenomenon

### ISSUE THREAD

**Issue by dongrizhixue** [Microsoft/vscode#8985]
I didn't notice it for a period of time, when I want to open it, can't see it, can't see process in task manager

**Comment by dongrizhixue** [comment]
I cannot prove him now, because I don't know how to submit the log.

**Comment by bpasero** [comment]
@dongrizhixue can you attach a screenshot about the issue?

**Comment by dongrizhixue** [comment]
@bpasero I can't provide screenshots, because I don't know when to quit it。
