### ISSUE TITLE
File Popup's get stuck on screen

### ISSUE THREAD

**Issue by DanJ210** [microsoft/vscode#89863]
Issue Type: <b>Bug</b>
<details>
<summary>Bug Description</summary>
This happens all the time I've just decided to report it finally because it's so distracting. These popup's shown in the screen shot will show up and permanently stay until a computer restart. Sometimes they'll go away from some random event I can't make a correlation to. But most of the time they stay until a restart. Never seen more than one stay at one time. But this happens every time I use VS Code and usually minutes after I first start using it will I get one stuck.

![image](https://user-images.githubusercontent.com/16159685/73610854-d5fae280-45a9-11ea-9cf4-066e34a40d4f.png)
</details>

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|2.0.15
xml|Dot|2.5.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
dotnet-test-explorer|for|0.7.1
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
rest-client|hum|0.23.1
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
dotnet-core-essentials|Kis|0.0.8
vscode-attrs-sorter|mrm|2.1.0
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.2
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.2
vscode-azurestorage|ms-|0.8.0
vscode-cosmosdb|ms-|0.12.1
vscode-docker|ms-|0.10.0
vscode-edge-devtools|ms-|1.0.6
mssql|ms-|1.8.0
azure-account|ms-|0.8.8
azurecli|ms-|0.4.6
csharp|ms-|1.21.9
powershell|ms-|2020.1.0
vscode-node-azure-pack|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.1507
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.3
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.13
vuejs-extension-pack|mub|1.1.5
vetur|oct|0.23.0
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.9.2
tslint-vue|pro|1.5.6
LiveServer|rit|5.6.1
vscode-essentials-snippets|rob|2.0.0
yo|sam|0.9.3
code-settings-sync|Sha|3.4.3
git-autoconfig|shy|0.0.1
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.4
azure-iot-toolkit|vsc|2.15.0
vscode-icons|vsc|9.7.0
WebTemplateStudio-dev-nightly|WAS|0.1.1934601
wilderminds-aspnetcore-snippets|wil|0.2.1
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by DanJ210** [comment]
I could add that they do swap out for one another, this just happened.

![image](https://user-images.githubusercontent.com/16159685/73610992-49512400-45ab-11ea-91f6-0b6d1e8830e2.png)

**Comment by lastlink** [comment]
I'm running 1.49.1 on a windows 10 and having the same issue. It happens quite often. I usually run 3 visual studio codes at a time.

**Comment by rzhao271** [comment]
Does the issue still occur for either of you on the latest VS Code? Unable to reproduce the issue on Windows 10, VS Code 1.52.1
