### ISSUE TITLE
Extension host terminated unexpectedly. Code: 3221225477, Signal: null

### ISSUE THREAD

**Issue by Polda18** [microsoft/vscode#89865]
When I try to open a folder in VS Code, suddenly Extension Host terminates unexpectedly. It doesn't happen when no folder is being opened (I have to close the folder before quiting VS Code to open it again). I have no idea if this is caused by some malfunctioning extension or it is a bug within VS Code. What do you guys think?

- VSCode Version: 1.41.1
- OS Version: Windows 10, v2004 (build 19555.1001 - Windows Insider)

Steps to Reproduce:

1. Open VS Code
2. Open a folder

Does this issue occur when all extensions are disabled?: No

**Comment by alexdima** [comment]
@Polda18 In your comment you mention that this issue does not occur when all extensions are disabled, so I can conclude that this is caused by one of your installed extensions. Can you please try to enable them one-by-one and see which one leads to the crash?

**Comment by Polda18** [comment]
Okay, it seems the only extension from my currently installed that causes Extension Host crash is The Travis Client (`lakkannawalikar.the-travis-client`). I shall report this bug to extension developer then. Sorry to bother you.

**Comment by macroking** [comment]
Is there any easy way to find out which extension is causing the problem?
