### ISSUE TITLE
Make sash sizes longer

### ISSUE THREAD

**Issue by corbane** [microsoft/vscode#89861]
Adding the functionality to detach a tab in a floating window will be really handy
[Roadmap 2020, section Workbench layout](https://github.com/microsoft/vscode/wiki/Roadmap)

It is true that reducing or enlarging the terminal to interact with it is tedious when it is used a lot.

I find it convenient to have larger resizing handles. And it's easy to do.
currently the handles are 4 pixels wide.

![image](https://user-images.githubusercontent.com/8430545/73609351-fc7e4500-45cc-11ea-9d5f-db90e35b875a.png)

it's really small.  The larger the screen, the more concentration it takes to grab this 4px handle.

I often double these values. test them, it's much more comfortable.

```css
.monaco-sash.vertical {  width: 8px; }
.monaco-sash.horizontal { height: 8px; }
```

for information, the handles of Visual Studio measure 6px and those of the edges of Win10 windows seem even wider (but I could not measure it with precision)

thank tou.
jmv

**Comment by corbane** [comment]
In addition, it would be quick to change the size of the tabs, if as with Chrome DevTool it was possible to have all the free space in the toolbar as a handle

![image](https://user-images.githubusercontent.com/8430545/73611490-a5836a80-45e2-11ea-8fc2-da233d431bb5.png)

**Comment by corbane** [comment]
Helo,

Also, is it possible to override the CSS rules of VSCode without compiling it (so as not to have to open DevTools every time)?

thank you,
jmv

**Comment by corbane** [comment]
![image](https://user-images.githubusercontent.com/8430545/80597571-505fc500-8a28-11ea-998c-097aafb4258a.png)

**Comment by sbatten** [comment]
see setting `workbench.sash.size`
