### ISSUE TITLE
save/open dialog has wrong scaling on high res displays

### ISSUE THREAD

**Issue by ardeego** [microsoft/vscode#89867]
save/open dialog has wrong (font) scaling on high res displays, i.e. dpi is not scaled properly when system uses a 4k display for example and uses  windows based % up scaling.

**Comment by gjsjohnmurray** [comment]
Probably a duplicate of #38976

**Comment by zenzoa** [comment]
I'm seeing an unscaled file dialog only since the Feb update. I use Window 10 on remote desktop with a high-res display (a MacBook Pro 13" 2017).
