### ISSUE TITLE
Double tab tag closing removes one space from the tab

### ISSUE THREAD

**Issue by fygascod** [Microsoft/vscode#8986]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.Press tab
2.Start a tag with "<" (eg."<div") and press tab twice
3.One space from the tab is removed so that the code loses the alignment with other lines in the same column

**Comment by joaomoreno** [comment]
Can you show me a recording of what you mean?

**Comment by fygascod** [comment]
I've attached a recording of the bug. I believe the bug was introduced in the recent July update.
[● bug.html - Web - Visual Studio Code 12_07_2016 14_35_39.zip](https://github.com/Microsoft/vscode/files/359211/bug.html.-.Web.-.Visual.Studio.Code.12_07_2016.14_35_39.zip)

**Comment by joaomoreno** [comment]
Thanks for the video, it makes it really clear. 👍

**Comment by aeschli** [comment]
Introduced by
https://github.com/Microsoft/vscode/commit/3d119458fef8d58814d249eedb34009b995e9297#diff-c52863ed5cad1e72f02c5394452c2b9cR76
