### ISSUE TITLE
commenting out selection does not work

### ISSUE THREAD

**Issue by aybiss** [microsoft/vscode#89878]
Issue Type: <b>Bug</b>

when selecting part of a line and pressing Ctrl+/ or Ctrl+K,Ctrl+C the editor comments out the entire line instead of the part of the line that's selected

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

**Comment by sportshead** [comment]
The keybinding for toggle block comment is <kbd>Shift</kbd>+<kbd>Option</kbd>+<kbd>A</kbd>. <kbd>Ctrl</kbd>+<kbd>/</kbd> and <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>C</kbd> are for toggling/adding line comments. To change the keybindings, press <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>S</kbd> to open the `Keyboard Shortcuts` editor. Here you can search for and change the keybinding for toggle block comment if you wish, or to view other keybindings.
