### ISSUE TITLE
Markdown preview does not show code blocks unless preceded by a blank line

### ISSUE THREAD

**Issue by heliusblackstar** [microsoft/vscode#89877]
Issue Type: <b>Bug</b>

Correctly formatted codeblocks are not rendered in Preview as codeblocks unless preceded by a blank line.

Paste this into a .md file and Preview in VS Code to see the issue.

```
Correctly Formatted Code Block:
    Per the Original Variant of Markdown, this is a correctly formatted codeblock that does not show as a codeblock in Visual Studio Code's Markdown Preview.
    4 spaces before each line are all that's necessary.
    This is a bug in VS Code that should be fixed.
```
```
Second Code Block.  VS Code only shows this as a code block due to the empty line before the code block, which is not in any way defined as necessary in the Original Variant of Markdown.

    this is also a correctly formatted codeblock.  Visual Studio Code only shows this as a code block due to the blank line before the code block.
    The blank line is not necessary per Markdown.
```
![2020-02-02 16_31_40-](https://user-images.githubusercontent.com/41092706/73615821-8df3b400-45d9-11ea-8176-9f4fec5be0f0.png)

VS Code version: Code - Insiders 1.42.0-insider (be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b, 2020-01-31T13:53:58.701Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
It woks as expected

VSCode uses markdown-it which in turn follows CommonMark Spec which requires blank line between paragraph and following code block:

> An indented code block cannot interrupt a paragraph, so there must be a blank line between a paragraph and a following indented code block. (A blank line is not needed, however, between a code block and a following paragraph.)

See https://spec.commonmark.org/0.29/#indented-code-blocks

BTW: GitHub doesn't render content of first code block as code block as well unless you add empty line between them.

**Comment by heliusblackstar** [comment]
Ah--that explains it then.

I accept this answer.

**Comment by IllusionMH** [comment]
Could you please close issue if question is resolved?
