### ISSUE TITLE
Maybe a code highlight bug in JavaScript regular expression

### ISSUE THREAD

**Issue by MatherLyn** [microsoft/vscode#89873]
I wrote a regular expression in JavaScript to detect punctuators in a string like this -- `/[!$%^&*\-_+=|\\<>.]/`. The '-' in this regexp has been escaped by the '\' before, but its color still remains red(I use the default style). Im sorry because I m a Chinese student speaking terrible English, but I love VS code very much. Hope you can understand what I was talking about!
![image](https://user-images.githubusercontent.com/48438633/73614608-a85e7980-463b-11ea-8d87-3243c808263b.png)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/804 to track upstream
