### ISSUE TITLE
Chinese localization is not completed.(v1.3.0)

### ISSUE THREAD

**Issue by yanxiaodi** [Microsoft/vscode#8987]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.Click the Extensions View icon.
2.Click on the ... More button, "show popular extensions" is still English.

**Comment by dbaeumer** [comment]
Our translation process takes around a week to finish. This is why milestones builds will always have a minor amount of strings in English (especially around new features).
