### ISSUE TITLE
Unnecessary 'await' inserted

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89879]
```ts
const readFile = util.promisify(fs.readFile);

const includedContents = await readFile(includePath).
```

![Feb-02-2020 13-45-04](https://user-images.githubusercontent.com/323878/73615955-43b30880-45c2-11ea-9488-a344d968b4cb.gif)

When I type `.toString()`, wrapping in parens is correct but it also inserts a second `await` which is redundant, and the ... appears to suggest removing the redundant await.

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/36596 to track upstream
