### ISSUE TITLE
[i18n] Incorrect French localization for "rename symbol"

### ISSUE THREAD

**Issue by FremyCompany** [Microsoft/vscode#8988]
- VSCode Version: 1.3

Should be "Renommer le symbole":

    https://github.com/Microsoft/vscode/blob/5b9ec15ce526decc5dd0488339e798f6bcb4ec46/i18n/fra/src/vs/editor/contrib/rename/browser/rename2.i18n.json#L7

File is marked as autogenerated, hence I didn't bother making a pull request.

**Comment by johnliu2016** [comment]
@lukaschal Please implement linguistic review and bug fixing to the only translation in 
/Localize/fra/vscode/src/vs/editor/contrib/rename/browser/rename2.nls.resx.lcl

      <Item ItemId=";rename.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Rename Symbol]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New" AutoAppr="N/A">
            <Val><![CDATA[Symbole Renommer]]></Val>
          </Tgt>
        </Str>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed.

File: src\vs\editor\contrib\rename\browser\rename.nls.resx
ID: ".resx", 0; "rename.label"
SRC: Rename Symbol
TGT: Renommer le symbole
