### ISSUE TITLE
npm install @babel/preset-env --save-dev

### ISSUE THREAD

**Issue by PaolaS2992** [microsoft/vscode#89880]
Error al ejecutar:
npm install @babel/preset-env --save-dev
Sale este error:
code EIO
syscall read 
errno -5
EIO: i/o error, read
A complete log of this run can be found in
 /home/paolasonia/.npm/_logs/2020-02-02T18_59_42_268Z-debug.log

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you specify how exactly it is related to VS Code editor itself?
If it is related - provide description of environment and exact steps in VS Code to reproduce this issue.
