### ISSUE TITLE
The VS Code asks to compare files all time.

### ISSUE THREAD

**Issue by iaxat** [microsoft/vscode#89886]
Whenever I am editing my codes, the VS Code shows a small notification to compare the files and says that it is not saved. I am totally frustrated with this situation.

The codes that are in my google drive, which I have added via r-clone, The Google G suite Account. It does not used to happen much but it is getting pretty annoying since few days. I love Vs Code and would like to use it even further, I do have Premium Jet brains for all tools, but even after that I like to use VS Code, please help me with this problem so that I can continue to use this.

It happens more frequently when I am on live share, the frequency of file save failed and notification to compare comes again and again. It is really annoying and the code does not even run with out comparing and saving the file again.

OS Version - Ubuntu 19.10
The extension I am using is:
Python, Java all extension(provided by Microsoft), Latex Workshop, C/C++, Intellisense, Go, Rust, JS

To recreate the problem:
1. Create a workspace with folders and files on your google drive.
2. Edit codes on live-share or even edit codes as normal and the notification will appear.
3. Check and compare the files, and save again, again after few edits it will appear.

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_42.md#ignore-save-conflicts perhaps the coming ability to ignore save conflicts will help you.  If that is the notification you are referring to.

**Comment by eamodio** [comment]
@iaxat please try out the insiders build (which is 1.42) or wait until later this week when 1.42 is released and then please report back. Thanks!

**Comment by bpasero** [comment]
You can configure: `files.saveConflictResolution: overwriteFileOnDisk`
