### ISSUE TITLE
Editor can offer useless suggestions

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89889]
e.g.

![image](https://user-images.githubusercontent.com/6157073/73618806-1302bb80-4622-11ea-9f81-4e3d209ca048.png)

EDIT: Grr. Github discarded my edit when I submitted a comment in another tab.

EDIT 2: This suggestion is useless, since accepting it enters nothing. The list's effect is only negative - to consume a TAB or Enter. Expected behaviour is that such useless suggestions not appear. In this case, the list would not appear.

V1.14.1, Windows 7 Pro 64-bit

**Comment by sportshead** [comment]
This is by VS Code's design. IntelliSense offers `Hi` as a suggestion since you typed it before.

Plus how can you manage to make 11 issues in 2 hours? Get a life

**Comment by chrisjj** [comment]
> This is by VS Code's design.

Source?

> Plus how can you manage to make 11 issues in 2 hours?

I'm more productive than average. :)

**Comment by IllusionMH** [comment]
This is controlled by `editor.wordBasedSuggestions`.
You can also check `editor.suggest.showWords` which controls if suggestion with `text` type should be in list.

**Comment by chrisjj** [comment]
> This is controlled by `editor.wordBasedSuggestions`.

The useless suggestion behaviour I'm reporting is not.

> You can also check `editor.suggest.showWords` which controls if suggestion with `text` type should be in list.

That too is not specific to the useless ones.

**Comment by chrisjj** [comment]
> /needsMoreInfo

Do you see the same behaviour?

**Comment by marechal-p** [comment]
@chrisjj go in your preferences and put `editor.wordBasedSuggestions` to `false`. If that doesn't work you'd have to film exactly what you do and upload here because it should work.

**Comment by IllusionMH** [comment]
It means that there is not enough info to see what problem is if disabling settings mentioned above doesn't work for you.

So you need to describe what is expected behavior, what actually happens and why settings above don't work for this problem.

**Comment by chrisjj** [comment]
IllusionMH Do you see this behaviour?

> you need to describe what is expected behavior

Sorry - I thought that was obvious. Now added.

> what actually happens

Already done. That's the screenshot.

> and why settings above don't work for this problem.

[Already done. ](https://github.com/microsoft/vscode/issues/89889#issuecomment-581485957)

**Comment by octref** [comment]
There might be other suggestions that follow the list, even in your case there isn't.

![image](https://user-images.githubusercontent.com/4033249/73889202-fb932080-4823-11ea-8756-5408cf1a04dd.png)

Showing completion item that matches current word is a design decision made long time ago. We won't change that.

**Comment by chrisjj** [comment]
> There might be other suggestions that follow the list, even in your case there isn't.

I'm reporting the case where there is not.

> Showing completion item that matches current word is a design decision made long time ago

To what purpose?

**Comment by IllusionMH** [comment]
After updates it became more clear.

> To what purpose?

Not that useful in plain text files but in JS/TS and other languages it will also provide ability to auto-import for matching name, so it's not useless by default. Also - good way to check if I haven't done any typos, but that's for me.

I guess that part of the problem come from the fact that VS Code will show suggestions automatically.
This behavior can be controlled by `editor.quickSuggestions` to turn off automatic suggestions display and `editor.quickSuggestionsDelay` to delay automatic display.
Combined with the fact that it can be configured for each language separately makes reasonable balance: while matching selections will still be there for all languages - there will be no automatic suggestions that "eat" keystrokes for `.txt` and `.md` files.

**Comment by chrisjj** [comment]
> Not that useful in plain text files 

Is there _any_ use in plain text files?

> but in JS/TS and other languages 

This behavior is supposed to be language-aware, right?

> I guess that part of the problem come from the fact that VS Code will show suggestions automatically.

I don't think so. All of the problem is that is shows suggestions that are useless - because accepting them does nothing.

> This behavior can be controlled by `editor.quickSuggestions` to turn off automatic suggestions display and `editor.quickSuggestionsDelay` to delay automatic display.

This behaviour is useless suggestions and those options control all suggestions regardless.
