### ISSUE TITLE
Cannot launch program ...; setting the 'outFiles' attribute might help.

### ISSUE THREAD

**Issue by caub** [microsoft/vscode#89882]
- VSCode Version: 1.41.1
- OS Version: Lubuntu 18.04

Steps to Reproduce:

1. Debug a file whose name starts with `._`
2. a A dialog opens and say: "Cannot launch program ...; setting the 'outFiles' attribute might help."

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Everything works well if the filename to debug starts with alpha chars, it seems related to the leading dot in the name

**Comment by roblourens** [comment]
Is it missing the `.js` extension? We will also check for a hashbang at the top of the file like `#! /usr/bin/env node`.

**Comment by caub** [comment]
@roblourens No hashbang, it's a classic JS file, named `._indexMemdb.js` that starts an express server

**Comment by roblourens** [comment]
Oh, then I can't reproduce this. Can you share your launch config?

**Comment by caub** [comment]
Oh, today it works, strange

my launch.json was just:

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--timeout",
        "999999",
        "--colors",
        "${file}"
      ],
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```

**Comment by roblourens** [comment]
Yeah that's a pretty normal launch config. Let me know if it happens again.
