### ISSUE TITLE
VS Code Server patches fs.stat, breaking an overload

### ISSUE THREAD

**Issue by brunnerh** [microsoft/vscode#89887]
Issue Type: <b>Bug</b>

vscode-server appears to use an outdated version of `graceful-fs` which has this function in `polyfills.js` which replaces `fs.stat`:

```js
function statFix (orig) {
  if (!orig) return orig
  // Older versions of Node erroneously returned signed integers for
  // uid + gid.
  return function (target, cb) {
    return orig.call(fs, target, function (er, stats) {
      if (!stats) return cb.apply(this, arguments)
      if (stats.uid < 0) stats.uid += 0x100000000
      if (stats.gid < 0) stats.gid += 0x100000000
      if (cb) cb.apply(this, arguments)
    })
  }
}
```

Newer versions of [`fs.stat`](https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback) can take an options argument after the path, but this function will falsely assume the second argument to always be a callback function causing it to throw on `cb.apply`.

**This issue already appears to be fixed in newer versions ([see master file in `graceful-fs`](https://github.com/isaacs/node-graceful-fs/blob/master/polyfills.js)).**

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.1.4-arch1-1-ARCH

**Comment by alexdima** [comment]
@brunnerh I acknowledge, we use an older version of `graceful-fs`. But how is this affecting you? (Our usage should not affect extensions AFAICT).

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/c635cab02908bd4bf3626dd34bab7f9c3e753468 updates `graceful-fs` to `4.2.3`.

**Comment by brunnerh** [comment]
@alexdima When my extension was executed remotely via the SSH extension, this version of `fs.stat` was executed and threw an exception.

**Comment by bpasero** [comment]
This change will be in insiders end of week and then please report back how it goes.
