### ISSUE TITLE
Display hostname on recently opened SSH locations

### ISSUE THREAD

**Issue by yseymour** [microsoft/vscode#89885]
Under the `File | Open Recent` menu, SSH locations are only identified by the suffix `[SSH]`.
If two directories with the same path are opened on two different machines, it's impossible to tell which one is which.  It would be helpful if the suffix could be `[SSH: host]` instead.

<img width="715" alt="Screen Shot 2020-02-03 at 8 42 58 am" src="https://user-images.githubusercontent.com/33473032/73616626-76f8a480-4661-11ea-84d3-3bedf6dac574.png">

VS Code version: 1.41.1
OS: MacOS 10.15.2

I searched for: open recent ssh

**Comment by roblourens** [comment]
If you successfully connected to that workspace, it should already do that. When you open that workspace, what do you see in the lower left corner?

**Comment by yseymour** [comment]
>When you open that workspace, what do you see in the lower left corner?

I see `SSH: host`, exactly what I'd also like to see in the Open Recent menu.

**Comment by roblourens** [comment]
@aeschli do you know what could be going wrong here?

**Comment by yseymour** [comment]
More info:  I just noticed I do actually have one entry in the menu that shows the hostname, so it seems to be working sometimes but not most of the time (for me, anyway).   The entry that does show the hostname is for a workspace (it has the `(Workspace)` suffix before `[SSH: host]`).  Of the rest of the entries, one is for a workspace and the rest are for directories, and none of them show a hostname.

**Comment by roblourens** [comment]
If you had tried to connect to those folders without the full label, and it failed to connect, then the label is missing. But you have tried to open those exact folders and it still doesn't show the label?

**Comment by yseymour** [comment]
>you have tried to open those exact folders and it still doesn't show the label?

Yes, I closed the editor, then reopened the folder from the Recent menu and there is no change to the label.  Everything opened successfully.

**Comment by roblourens** [comment]
Sorry, I really have no idea. Is this still an issue?

**Comment by bct-github** [comment]
I mean, it's a very minor issue, I'm not exactly bothered by it on a daily basis, but it's still there.

**Comment by yseymour** [comment]
I mean, it's a very minor issue, I'm not exactly bothered by it on a daily basis, but it's still there.

**Comment by roblourens** [comment]
Ok, gonna close this then.
