### ISSUE TITLE
Incorrect English and punctuation in Settings

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89899]
![image](https://user-images.githubusercontent.com/6157073/73621969-04230580-4630-11ea-9d66-92fe263846dc.png)

"strategy". No. Method.

"Language specific". Missing hyphen.

"indentation based". Missing hyphen.

Also "if available" fails to say that if not, indentation method is used.

**Comment by sportshead** [comment]
We're *programmers*, not spell checkers

**Comment by chrisjj** [comment]
> We're programmers, not spell checkers

Which is why you welcome reports such as this, right?
