### ISSUE TITLE
Maximize current editor group (or temporarily hide other editor groups)

### ISSUE THREAD

**Issue by jasongrout** [Microsoft/vscode#8989]
It would be great if there was a way to quickly hide other editor groups to focus on a single editor (or editor group) without actually closing all the other files. A common workflow for me is to flip between having multiple files open side by side, and having just the currently focused file shown, which is pretty painful to do now.

This is akin to the zen mode or no-distraction mode you see in other software. https://packagecontrol.io/packages/MaxPane also implements this for Sublime.

**Comment by bpasero** [comment]
There are some commands to do this:
* Maximize editor group and hide side bar
* Minimize other editor groups

Please give them a try.

**Comment by jasongrout** [comment]
Sorry, I just saw this. This helps get into a MaxPane-like mode, but it doesn't help getting out of it. Ideally, there would be an easy way to maximize the editor group *and* restore the previous layout.

**Comment by bpasero** [comment]
`Even Editor Group Widths`

**Comment by fikovnik** [comment]
Is it possible to actually use it as a toggle (maximize/even) and bind that to a key?

**Comment by bradparks** [comment]
I'd like this as well - I have a similar feature I use in Vim, [ZoomWin](http://www.vim.org/scripts/script.php?script_id=508), and for this feature to be useful, it has to be able to restore to the previous state... thanks!

**Comment by jasongrout** [comment]
Related to #12940.

**Comment by rob3c** [comment]
So if the `workbench.action.maximizeEditor` command isn't going to be a toggle, then what's the complementary command to undo the action when you're done and want to go back to the previous layout?

**Comment by wkerswell-gresham** [comment]
@rob3c If you set `Even Editor Group Widths` you can go back. It wont have the same layout as you had before but will split the editors to be even widths which is pretty much there. I had to set up a keybinding for each though as they arent toggles

**Comment by goofle** [comment]
Are these settings (e.g. `workbench.action.maximizeEditor` and etc.) still available in vscode?
I don't seem to able to find them. 

Version 1.14.2

**Comment by arcseldon** [comment]
A toggle that retains the previous layout would be ideal. The `maximise editor groups` / `even editor group widths` combination is just about good enough - please consider a complete solution though 😃
