### ISSUE TITLE
Folding icons - behaviour and docs fail to accord

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89893]
Behaviour shows arrowhead icons that appear (incredibly sluggishly) when the gutter is hovered:

![image](https://user-images.githubusercontent.com/6157073/73620064-18630480-4628-11ea-8e5e-8e9d7bb72fb4.png)

Docs shows conventional boxed + and - icons:

![image](https://user-images.githubusercontent.com/6157073/73620118-41839500-4628-11ea-8e08-23ec78d27aa1.png)

PS If anyone knows a workaround to remove the hover requirement, please do say. Likewise to get the conventional icons.

**Comment by sportshead** [comment]
Settings: `editor.showFoldingControls` to `always`

This should help you fix it.
![Screenshot 2020-02-03 at 10 16 06 AM](https://user-images.githubusercontent.com/32637656/73620931-035d9400-466f-11ea-994c-166740a6ff60.png)

**Comment by chrisjj** [comment]
Thanks, but that doesn't remove the hover requirement. It removes only the hover _effect_ - leaving the icons hidden regardless.

**Comment by chrisjj** [comment]
Thanks. You'd never know it from that faulty labelling, would you? Reported here https://github.com/microsoft/vscode/issues/89900 .

**Comment by chrisjj** [comment]
> /duplicate being handled in #89900

Er, no. That's a totally independent issue - wrong labelling of related options in Settings. This one is about the icons that appear in the Editor.

**Comment by gjsjohnmurray** [comment]
Please log documentation issues at https://github.com/microsoft/vscode-docs

**Comment by chrisjj** [comment]
How is one to ascertain whether a failure of program and docs to accord is a program issue or a docs issue?
