### ISSUE TITLE
Unfold All (Ctrl+K Ctrl+3) is recognised but fails to take effect

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89898]
E.g.

![image](https://user-images.githubusercontent.com/6157073/73621740-13558380-462f-11ea-8cfd-e6833af742f9.png)

Press Ctrl+K Ctrl+3.

According to the docs, we should have

![image](https://user-images.githubusercontent.com/6157073/73621766-308a5200-462f-11ea-93ed-eb78506fefe1.png)

But there's no change.

V1.14.1, Windows 7 Pro 64-bit.

**Comment by sportshead** [comment]
I fail to understand. Your title says <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>J</kbd> but you press <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>3</kbd>

Is that why there's no change? By the way you should try multiple times before you make an issue

**Comment by chrisjj** [comment]
> Your title says Ctrl+K Ctrl+J 

Whoops. Now Corrected. Thanks.

**Comment by gjsjohnmurray** [comment]
@chrisjj did you change the keyboard shortcuts from defaults?

![image](https://user-images.githubusercontent.com/6726799/73660489-33695f00-4690-11ea-81b3-adac376f023b.png)

![image](https://user-images.githubusercontent.com/6726799/73660601-6d3a6580-4690-11ea-97c3-68045ad9c9d9.png)

**Comment by chrisjj** [comment]
Apologies. This report is erroneous. Closing.
