### ISSUE TITLE
Suggestions disappear upon program switch

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89890]
... and fails to reappear on program regaining focus.

E.g.

![image](https://user-images.githubusercontent.com/6157073/73618922-a5a35a80-4622-11ea-8252-ea69a0bce109.png)

Switch to Notepad:

![image](https://user-images.githubusercontent.com/6157073/73618935-c1a6fc00-4622-11ea-8035-82aaa80f9972.png)

Suggestion gone.

Switch back:

![image](https://user-images.githubusercontent.com/6157073/73618943-cf5c8180-4622-11ea-85d8-3e6afe961f3b.png)

Suggestions still missing.

Workaround for second case: Press Ctrl+Space

**Comment by anotherglitchinthematrix** [comment]
I believe this is intended behavior of the panel but you can always use the `CTRL + SPACE` combination at the end of the word to open the suggestion panel again.

**Comment by chrisjj** [comment]
> I believe this is intended behavior of the panel 

I can't imagine why it would be. It does nothing but disadvantage the user.

> but you can always use the CTRL + SPACE combination

As I already said. And for the second case only.
