### ISSUE TITLE
VS Code UI has mistaken "chord" to mean sequence

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89895]
e.g.  status bar

![image](https://user-images.githubusercontent.com/6157073/73621020-59f5ae80-462c-11ea-9a25-e8cf8d46db75.png)

The program isn't waiting for the second key of a chord, It is waiting for second key (or chord) of a sequence.

EDIT: Further instance:

![image](https://user-images.githubusercontent.com/6157073/73890432-e17c3100-4869-11ea-98e4-0d3dbbef3a87.png)

**Comment by sportshead** [comment]
Why don't you just put all of your problems with VS Code into one issue

Plus as I said in #89899 "We're programmers, not spell checkers"

So you can stop complaining about bad grammar. Or fix it yourself and make a PR

**Comment by chrisjj** [comment]
> Why don't you just put all of your problems with VS Code into one issue

I prefer to follow good practice - and the guidelines. "File a single issue per problem"

>Plus as I said in #89899 "We're programmers, not spell checkers"

This isn't a spell-check issue.

> So you can stop complaining about bad grammar.

This isn't a complaint - it is an defect report. And this issue isn't about grammar.

**Comment by gregvanl** [comment]
I'm not sure I understand your issue.
VS Code uses chord to refers to a sequence of two or more separate key presses (including any modifiers like ctrl, alt, shift) so the Status bar comment seems accurate. The status bar is indicating that another keypress is necessary to complete the chord and activate the command.

**Comment by chrisjj** [comment]
> I'm not sure I understand your issue.
> VS Code uses chord to refers to a sequence of two or more separate key presses

There's the issue. That's not what chord means 

> The status bar is indicating that another keypress is necessary to complete the chord and activate the command.

And that's not true. What is true, is that another keypress or chord is needed to complete the _sequence._

**Comment by chrisjj** [comment]
Could someone please reopen this issue please? It was closed by a contributor who said "I'm not sure I understand your issue." since which he/she has been given further information to help him understand it.

**Comment by gregvanl** [comment]
Hi @chrisjj, Sorry to not get back to you. Technology often stretches the definition of English words to explain new ideas or features. VS Code uses "chord" in this way and so far it has resonated with most users. I don't think it is necessary to change the Status bar text.

**Comment by chrisjj** [comment]
> Technology often stretches the definition of English words to explain new ideas or features. 

The existing meaning of chord in keyboard technology is far from new. See Wikipedia https://en.wikipedia.org/wiki/Chorded_keyboard .

The fact the term may be new to some VS Code users is a poor excuse for miseducating them, and for reducing accessibility to experienced users.
