### ISSUE TITLE
Sequence Ctrl+K Ctrl+0 fails to execute

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89896]
Despite that the docs say

> Fold All (Ctrl+K Ctrl+0) folds all regions in the editor.

this sequence has no effect on the folds, and leave the status bar saying:

![image](https://user-images.githubusercontent.com/6157073/73621125-c2449000-462c-11ea-906c-9a669d09f2ae.png)

EDIT: On V1.41.1 https://i.imgur.com/buSySUk.png Windows 7 64-bit.

**Comment by sportshead** [comment]
You probably didn't press <kbd>Ctrl</kbd>+<kbd>0</kbd>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have any keymap extension or custom keybindings configured for these combinations?

What are your VSCode version and OS?

**Comment by chrisjj** [comment]
> /needsMoreInfo
> Is it reproducible with all extensions disabled?

Relevance? I'm reporting on the standard distribution.

Do you see the same on the standard distribution?

> Do you have any keymap extension or custom keybindings configured for these combinations?

I have whatever the standard distribution provides and no more.

> What are your VSCode version and OS?

V1.41.1, Windows 7 64-bit.

**Comment by IllusionMH** [comment]
> Relevance? I'm reporting on the standard distribution.

Because you omitted a lot of fields form issue template and your report had no information to help triage issue, until you added it. 
```md
<!-- Please read our Rules of Conduct: https://opensource.microsoft.com/codeofconduct/ -->
<!-- Please search existing issues to avoid creating duplicates. -->
<!-- Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/ -->

<!-- Use Help > Report Issue to prefill these. -->
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

<!-- Launch with `code --disable-extensions` to check. -->
Does this issue occur when all extensions are disabled?: Yes/No
```
Without this info it is impossible to tell what is your setup, if it's really an issue with VS Code etc.

Reasoning is simple - there is a ton of reports that use outdated version of VS Code, have extension that are root cause of problem or have keybindings installed/configured and wonder why default doesn't work.

> Do you see the same on the standard distribution?

I see no issues with Stable and Insiders builds (https://code.visualstudio.com/insiders/), however I'm on Windows 10.

So after you provided at least some info it might be OS specific if you have no extensions and no changes to keybinding.

You also can check Insiders build (link above) to see if Electron update helps.

**Comment by chrisjj** [comment]
> So after you provided at least some info it might be OS specific 

Anyone here got it to work on Windows 7?

> if you have no extensions 

I do have extensions - those included as standard.

> and no changes to keybinding.

None I know of.

**Comment by alexdima** [comment]
@chrisjj I cannot reproduce. In a vanilla VS Code installation, `Ctrl+K Ctrl+0` works fine:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/73726681-459ada00-4730-11ea-9f20-7c12cb7cfb19.gif)

**Comment by chrisjj** [comment]
@alexdima, Thanks but needsMoreInfo :) Which OS?

**Comment by alexdima** [comment]
@chrisjj I am trying to reproduce your issue on Windows. Our default keybindings are the same both on Windows 7 or Windows 10. Have you tried commenting out your `keybindings.json`? Have you tried disabling all of your extensions? Are you pressing `Ctrl+K Ctrl+0` or `Ctrl+K 0` (the Ctrl must be pressed for the second part of the chord too).

**Comment by chrisjj** [comment]
> @chrisjj I am trying to reproduce your issue on Windows. Our default keybindings are the same both on Windows 7 or Windows 10. 

Have you got it to work on Windows 7?

> Have you tried commenting out your `keybindings.json`? 

No.

> Have you tried disabling all of your extensions? 

"Your extensions"? I haven't added any. The only extensions are those included as standard, to my knowledge.

> Are you pressing `Ctrl+K Ctrl+0` or `Ctrl+K 0` (the Ctrl must be pressed for the second part of the chord too).

As I said, Ctrl+K Ctrl+0. Thanks for checking though.

**Comment by alexdima** [comment]
@chrisjj 
What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by chrisjj** [comment]
> Perhaps the keybinding Ctrl+0 does not reach VS Code due to other software on your machine?

It is possible. But the press has no visible effect on any other program.

> What does VS Code detect when you press the desired key combination? 

When I press Ctrl+0? As I said, it leaves the status bar saying "Waiting for second key of chord".

> Please hover over the input box and take a screenshot:
> ![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

Does this suffice?  https://i.imgur.com/mucHrhT.png

Have you got this to work on Windows 7?

**Comment by alexdima** [comment]
@chrisjj Can you please try to check if VS Code receives the keybinding? This is possible to check by opening your `keybindings.json` file and clicking the blue button and pressing the key combination like I do in the following GIF:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/73882594-9f032600-4862-11ea-904d-570de0f9c514.gif)

**Comment by chrisjj** [comment]
> @chrisjj Can you please try to check if VS Code receives the keybinding? This is possible to check by opening your `keybindings.json` file and clicking the blue button and pressing the key combination like I do in the following GIF:

On pressing Ctrl+0 I get this:

![image](https://user-images.githubusercontent.com/6157073/74521189-eba8ca00-4f10-11ea-8a55-4d740b8fe37f.png)

**Comment by alexdima** [comment]
@chrisjj This indicates that VS Code does not receive `Ctrl+0` on your system. This is most likely caused by 3rd party software that "eats up" keybindings. Can you confirm that `Ctrl+0` works for you in any other application on the same machine?

**Comment by chrisjj** [comment]
> @chrisjj This indicates that VS Code does not receive `Ctrl+0` on your system. This is most likely caused by 3rd party software that "eats up" keybindings. 

Could be.

> Can you confirm that `Ctrl+0` works for you in any other application on the same machine?

No. But I have none that says it uses it.

Can you suggest a tester program?
