### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by CNMan** [Microsoft/vscode#8990]
- VSCode Version:1.3.0 stable ( https://code.visualstudio.com/docs?dv=winzip )
- OS Version:Windows Server 2012 R2

Steps to Reproduce:

1. run "E:\Program Files\VSCode\Code.exe" --user-data-dir="E:\Backup\VSCODE" --extensionHomePath="E:\Backup\VSCODE\extensions"
2. then "Extension host terminated unexpectedly. Please reload the window to recover."
3. reload but "Extension host terminated unexpectedly. Please reload the window to recover." again.
4. repeat

**Comment by bpasero** [comment]
@CNMan so does it not happen when you are not specifying those arguments?

**Comment by CNMan** [comment]
@bpasero it don't happen when no arguments.

**Comment by bpasero** [comment]
@CNMan is the E: drive any special?

**Comment by CNMan** [comment]
@bpasero no,it is a normal logical drive of hard disk

**Comment by bpasero** [comment]
@CNMan something in the console (open dev tools from help menu)?

**Comment by CNMan** [comment]
@bpasero nothing.fresh os and fresh vscode.

**Comment by bpasero** [comment]
@CNMan can we find out which of the 2 arguments is causing it by using one and then the other?

**Comment by CNMan** [comment]
@bpasero tested and the error occurs when run vscode with 2 arguments only.

**Comment by bpasero** [comment]
@CNMan do you actually have something in the extensions folder (both in E:\Backup\VSCODE\extensions and E:\Backup\extensions)?

I cannot reproduce the extension host crash but I can also not install any extensions when running like that (@joaomoreno fyi).

**Comment by CNMan** [comment]
```bash
rd /s /q c:\Users\Administrator\.vscode\
rd /s /q c:\Users\Administrator\AppData\Roaming\Code\
```

[VSCODE.ZIP](https://github.com/Microsoft/vscode/files/358555/VSCODE.ZIP)
![2016-07-12_122635](https://cloud.githubusercontent.com/assets/8692234/16755202/7e465c3c-482c-11e6-8e7f-ae01a2bc2a43.png)

**Comment by bpasero** [comment]
@CNMan are those folders empty or do they have extensions? I am talking about `E:\Backup\VSCODE\extensions` and `E:\Backup\extensions`

**Comment by CNMan** [comment]
@bpasero 
E:\Backup\VSCODE\extensions is empty.
E:\Backup\extensions does not exist.

**Comment by bpasero** [comment]
@CNMan does it fix the issue when you create `E:\Backup\extensions` ?

**Comment by CNMan** [comment]
@bpasero no

**Comment by garethflowers** [comment]
I'm getting the same thing - and can easily replicate it by doing the following...
```batch
rd /s /q %USERPROFILE%\.vscode
rd /s /q %APPDATA%\Code
md %TEMP%\vscode\extensions
code --user-data-dir="%TEMP%\vscode" -extensionHomePath="%TEMP%\vscode\extensions"
```
![image](https://cloud.githubusercontent.com/assets/587323/17430088/4be3aed6-5aea-11e6-869b-1080077d4efb.png)

**Comment by bpasero** [comment]
With the screenshot it looks like the shared process is not healthy. @joaomoreno moving to you.

**Comment by joaomoreno** [comment]
No @bpasero. The screenshot also shows that the extension host being broken...

**Comment by sushruth** [comment]
I had the same issue on windows (in a very restricted corporate environment) and could not find a solution anywhere. The following solved the problem for me (not sure why) :

Edit the vscode shortcut and in `Target` field, type the following text
(Please make sure the paths are right).
```
C:\Windows\System32\cmd.exe /c "C:\Program Files (x86)\Microsoft VS Code\bin\code"
```

hope this helps.

**Comment by joaomoreno** [comment]
@CNMan Do you still have this issue?

**Comment by garethflowers** [comment]
This is fixed for me in the latest v1.5.2.

**Comment by CNMan** [comment]
@joaomoreno it seems already fixed for me in v1.5.3. thanks.

**Comment by joaomoreno** [comment]
Thanks guys

**Comment by Tyre88** [comment]
I had the same problem but then i installed the "insider" version and it worked... 
https://code.visualstudio.com/insiders

**Comment by sixtrees** [comment]
坑啊，一堆问题。。。还说会保留设置。。。
