### ISSUE TITLE
Settings Show folding controls answers have reverse effect

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#89900]
![image](https://user-images.githubusercontent.com/6157073/73622166-8b707900-4630-11ea-8116-32775d367146.png)

"Controls whether fold controls on [sic] the gutter are automatically hidden" "always" is incorrect. That option _shows_ the controls always

"Controls whether fold controls on [sic] the gutter are automatically hidden" (upon) "mouseover" is incorrect. That option _shows_ the controls on mouseover. EDIT: Collapse only. Expand (">") is shown regardless... which may be a bug.

Correct is "Fold controls in the gutter are shown" always / while mousedover .

**Comment by gjsjohnmurray** [comment]
@chrisjj I agree. I am preparing a PR.
