### ISSUE TITLE
Command+Enter to commit does not work anymore

### ISSUE THREAD

**Issue by daimor** [microsoft/vscode#89904]
- VSCode Version: 
Version: 1.42.0-insider
Commit: be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b
Date: 2020-01-31T13:51:59.883Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
- OS Version: macOS Catalina 10.15.2

Steps to Reproduce:

1. put some SCM commit message
2. Press ⌘Enter, and nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe caused by #84831

cc @joaomoreno

**Comment by joaomoreno** [comment]
Interesting, I can't repro here. Do you have Cmd Enter configured to more commands in your keybindings? Run `Preferences: Open Keyboard Shortcuts` and search for `Cmd Enter`

**Comment by daimor** [comment]
Yep, found it. I have a custom keybinding for trigger suggest.
<img width="1173" alt="Screenshot 2020-02-03 at 13 42 43" src="https://user-images.githubusercontent.com/1212251/73646930-812f9880-468b-11ea-9b78-14c09f96057a.png">
But I think it should not trigger there. So, it should work anyway.

**Comment by daimor** [comment]
And it works after reset

**Comment by joaomoreno** [comment]
:+1: Got it, you can add `&& !editorSimpleInput` to that `when` condition.

**Comment by daimor** [comment]
@joaomoreno thanks, would it be possible to add it default keybindings as well?
So, next time, it would be possible to just change `key` without changing `when`.

**Comment by joaomoreno** [comment]
Actually, the suggest widget will come to simple editor inputs as well, albeit as `Ctrl Enter`, so we can't change the default `when` clause.
