### ISSUE TITLE
Nagivgates back to another pane if the same file opened there too.

### ISSUE THREAD

**Issue by whitecolor** [microsoft/vscode#89903]
Navigates back to another pane if the same file opened there too, though more expected that it should navigate back to the same tab.

- VSCode Version: 1.42.0-insider
- OS Version: windows 10

Steps to Reproduce:

1. Open file in the left pane
2. Open the same file in the right pane
3. From the right pane code go to some other file (for example open type definition of some code element)
4. Press Alt+left to navigate back to the previous location.

It jumps to the left pane (as there opened the file that it should be navigated to). **But to me seems more expected that it would return the previous file in the right pane.** As it would do if in the left pane there was opened another file.

**Comment by whitecolor** [comment]
@bpasero what issue is it duplicate of?

**Comment by LinAGKar** [comment]
@bpasero, None of the issues listed there is the same as this issue. While at it, #67335, which was linked to from here, is not a duplicate of anything either.

**Comment by bpasero** [comment]
Check out https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aworkbench-history+, e.g. there is one that asks for a per-editor group history, which would help here. 

On top of that, https://code.visualstudio.com/updates/v1_42#_navigate-most-recently-used-editors would probably help if you only want to navigate between editors.

**Comment by LinAGKar** [comment]
From that list, this looks like a duplicate of #9526 and #45233. When marking something as a duplicate, it would be helpful to link to the issue it's a duplicate of, rather than just a bunch of unrelated issues.
