### ISSUE TITLE
Feature request for nedit-like rectangular editing feature

### ISSUE THREAD

**Issue by alexanderbruns** [microsoft/vscode#89901]
Hi,

We are looking in the company I work for, for a replacement for nedit (https://en.wikipedia.org/wiki/NEdit). 
I just saw that a little bit column editing is possible in vscode.

The thing is, that we often use the special unique rectangular editing
feature in nedit and I would like to ask, if this could be implemented
in vscode.

To see it, you have to try it with nedit, which is in most linux distributions
still available, although it is no longer maintained.

These features I would like to request:

What do I mean with "rectangular block editing"?

Like in nedit, in vscode it is possible to  mark
a rectangular part of the text with LM+Shift+Alt (Left Mouse button pressed)

So Shift-Alt-LM for marking.

Within nedit, it exists very powerfull features with this marked block.

After with Ctrl+LM a block of the text is marked, you can

*

move the block with just MM (Middle Mouse) without keyboard
and move away text which was at the target position of the movement
press MM and move the text and release it to stop moving.

*

move the block with C+MM and replace the text which was at
the position where you move th block to. The block at the
origin gets replaced by white spaces.

*

copy the block with CS+MM (Ctrl+Shift+MiddleMouse) and replace the
text which was at the position where you move the block to. The
block at the origin stays the same, so really copy no deletion.

This is really powerfull and because we often edit large text-files,
where the data is aranged in column order, it is often used by us.

Isn't this worth to make vscode to be the one unique sucessor which
is enabled of this feature?

To show the capabilities of nedit I created a short 2min 
screencast with nedit and uploaded it ot youtube:

https://youtu.be/QfN8cGAViJc

Greetings

Alexander Bruns

**Comment by skmcgowan** [comment]
The link posted to Nedit is a forum to some sort of online casinos and gambling forum

**Comment by alexanderbruns** [comment]
> The link posted to Nedit is a forum to some sort of online casinos and gambling forum

THX. I did not visit this page for a long time, but in meanwhile it seems to be used diferently. 
I linked to wikipedia.

**Comment by alexanderbruns** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).
> 
> Happy Coding!

What exactly is meant with an upvote?
