### ISSUE TITLE
Intellisense stops working with javascript

### ISSUE THREAD

**Issue by simone-omniaweb** [microsoft/vscode#89920]
5Issue Type: <b>Bug</b>

1. Fresh download of portable version of Insider, 1.42.0
2. No plugins installed
3. Opened a react-native project
4. IDE starts "initializing JS/TS language features"
5. After maybe 20 seconds of work intellisense stops working

The same thing with the non insider version, 1.41.1. Previous version (1.40.2) works fine.

VS Code version: Code - Insiders 1.42.0-insider (be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b, 2020-01-31T13:53:58.701Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After restarting VS Code, does that fix the problem?

**Comment by simone-omniaweb** [comment]
> Can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After restarting VS Code, does that fix the problem?

Yes, it fixes the problem, thanks. Is there a known "bug" in the current stable version?

**Comment by mjbvz** [comment]
Closing as fixed in typescript 3.8 which will be released with VS Code 1.43
