### ISSUE TITLE
Introduce enum for escaped characters in SemanticTokenTypes

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode#89929]
Talked to @dbaeumer about this on Slack and he suggested I open a ticket about this.

I am using the VS Code LSP bridge to experiment with the new semantic tokenization API. Given a string `"abc\n\ndef"`, I would like to highlight `\n\n` differently similar to what VS Code does right now for TypeScript.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/15629116/73660879-0fddee80-4667-11ea-8793-52d6e91a2080.png">

I could not figure out an appropriate enum for describing this semantic highlighting. Can one be added?

https://github.com/microsoft/vscode/blob/be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L372-L408

**Comment by IllusionMH** [comment]
Wondering if this one can help with help with #89873

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#token-classification on how you can define your own token type.

**Comment by aeschli** [comment]
Coloring escaped characters could also be done through a TextMate grammar injection. It's not the classical 'semantic' example tgat we're currently after (Highlighting based on resolved symbol information).
But. nevertheless, please try it out! 
A custom toke types seems appropriate to me. So closing the issue

**Comment by rcjsuen** [comment]
@aeschli Thank you for the details. I'll see about pushing for the token type in the LSP and then maybe we can setup a custom thing in `vscode-languageclient` I guess...?

**Comment by aeschli** [comment]
Yes, in the LSP it would be the same. We have a 'standard' set of token types & modifiers, but each server is free to define new ones.
