### ISSUE TITLE
How to open new tab with some formatted text from the extension API

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#8992]
Hi , 
I dont find any simple example to open new text document and write some formatted text in it using Visual Studio Code API.

Please provide a small example where i can insert text.
I need it for "visual studio code Settings Sync" Extension

**Comment by jrieken** [comment]
It depends on what you mean by `formatted text` and `write`. There are these samples

1. Have synthetic content in the editor using the [TextDocumentContentProvider](https://github.com/Microsoft/vscode-extension-samples/tree/master/contentprovider-sample)
2. Preview html in the [editor](https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample)
3. Open a new buffer that should be saved to [disk](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3438) using the `untitled` scheme

**Comment by felixhao28** [comment]
@jrieken Hi, how do I open a new buffer using the untitled scheme? I tried this:

```js
var doc = vscode.window.activeTextEditor.document;
var untitledFile = doc.uri.with({
    scheme: 'untitled'
});
vscode.workspace.openTextDocument(untitledFile);
```

But the error says the file already exists. Then I tried this:

```js
var doc = vscode.window.activeTextEditor.document;
var untitledFile = doc.uri.with({
    scheme: 'untitled',
    path: ''
});
vscode.workspace.openTextDocument(untitledFile);
```

And the error becomes "path or authority must be set".

So how do I create an untitled buffer that triggers save file dialog when user wants to save it?

Thank you.

**Comment by jrieken** [comment]
Try with an uri that has a scheme and path, like this `Uri.parse('untitled:my/path/proposal')`

**Comment by Jakobud** [comment]
@jrieken Is it possible to open a new buffer with an untitled document in it, but without specifying the path to where the file will be saved when you Save it? I want to have a new buffer opened and then when I click save, I want a Save dialog box to come up where they choose where to save it (just like a normal Untitled document). Currently with the `untitled:` Uri approach, you are forcing the resulting path of the file. The user of the extension has no open of picking where they want to save the file. Does that make sense?

Essentially, you know how you go use the Mouse to goto the File menu and click on New File? How do you recreate that exact action using the API?

**Comment by jrieken** [comment]
@Jakobud please open a new issue for this and note that comments on closed issues are likely to be missed

**Comment by Jakobud** [comment]
Sure thing. Thanks,
