### ISSUE TITLE
Add Untitled-x to the title attribute of Untitled files

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#89921]
With recent changes Untitled files display first line content as editor tab name and Untitled-x as description, however title attribute only contains first line content.

And while Untitled-x as description helps to avoid ambiguity between tabs with same first line content, it is impossible to rely on title in case when I have `"workbench.editor.tabSizing": "shrink"` or in Open Editors section.

It can be `import React from 'react'; - Untitled-2` (using same separator as in window title) or something like `Untitled-2: import React from 'react';` (may be `Untitled-2 editor: import React from 'react';` )

Editor tabs for saved files have full path to file which helps to avoid ambiguity.

/cc @bpasero

**Comment by bpasero** [comment]
@IllusionMH to be clear you are asking for having the `"<first line> <untitled-n>"` for the title attribute of labels so that this appears in the hover?

**Comment by IllusionMH** [comment]
Yes.

Some separator would be nice so Untitled-8 won't blend with content
![image](https://user-images.githubusercontent.com/1312662/73654702-0ff4e300-4695-11ea-988b-d63138893fc6.png)

**Comment by bpasero** [comment]
Yeah, maybe we could use a dot as separator, similar to how we do it for multi root labels.

**Comment by bpasero** [comment]
**Verification:** hover over an untitled editor tab and verify:
* you see the "Untitled-N" in the hover separated by a dot from the name of the untitled editor if the first line of the editor has words
* you do not see it twice if the first line does not contain words

**Comment by bpasero** [comment]
@IllusionMH  can you verify from insiders? Then I can set the verified label.

**Comment by IllusionMH** [comment]
@bpasero sorry - missed this one.

Editor tabs and Open editors entries have expected title.
Search result has previously used title `\Untitled-1` but it's not ambiguous.

However noticed that display of tile looks strange if there are no words in first line:

Old (1.41.1)
![image](https://user-images.githubusercontent.com/1312662/75047612-b9c6d300-54cf-11ea-8f87-8b4ef49937a2.png)

With words (Untitle-1 in description, looks good)
![image](https://user-images.githubusercontent.com/1312662/75047532-91d76f80-54cf-11ea-9e02-38264933427f.png)

No words (`\` in description - looks strange)
![image](https://user-images.githubusercontent.com/1312662/75047558-9bf96e00-54cf-11ea-9ff2-193f3b15e944.png)

Is it intended? Can `\` be removed?

**Comment by bpasero** [comment]
Thanks, I will check this out.

**Comment by bpasero** [comment]
Yeah good catch, I was not properly setting the title for the label for untitled. It should now be the same as for the editor:

![Kapture 2020-02-21 at 18 53 42](https://user-images.githubusercontent.com/900690/75058549-7f633300-54db-11ea-9abf-4bcf82a3c9d7.gif)

**Comment by IllusionMH** [comment]
@bpasero
I checked all places (tabs, open editors, and search results entries) - everything looks as expected.
Also nice to see that there are no extra `\` in search results.

Thanks!

**Comment by bpasero** [comment]
Thanks, adding verified label thereby.
