### ISSUE TITLE
Gear menu flashes context menu, triggers action on a single click

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89927]
Might only happen with native title bar.

![context](https://user-images.githubusercontent.com/2193314/73660316-cda7b380-464c-11ea-8a31-0515b47fef7a.gif)

Version: 1.42.0-insider (user setup)
Commit: be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b
Date: 2020-01-31T13:53:58.701Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by sbatten** [comment]
native only, not a regression

**Comment by Tyriar** [comment]
Hope it gets fixed eventually, found my other duplicate which I thought would have been fixed.

/duplicate https://github.com/microsoft/vscode/issues/79476
