### ISSUE TITLE
Break point indicator

### ISSUE THREAD

**Issue by jezzye13** [microsoft/vscode#89922]
Issue Type: <b>Bug</b>

It is about the red circle next to the line number. When you hover there appears a less red circle and when I move my mouse it is gone.
The bug having visual code on second monitor maximized:
When my mouse is next to a line number and I windows flag + L and log back in with a different mouse position the dark red circle stays visible. It does not happen on my first monitor.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.3

</details>

**Comment by isidorn** [comment]
It only happens on the window that has focus.
And this is how we designed this feature: to make breakpoitns more discoverable.
So far nobody has complained which makes me believe that it is getting the job done.
However keeping this open as a feature request and we can potentially change it in the future. Thank you
