### ISSUE TITLE
Terminal quits accepting input after a couple minutes while connected to Online Environments

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode#89935]
Issue Type: <b>Bug</b>

I connected to a new Online Environment and used the terminal for several commands. A few minutes later I came back to that VS Code window and that same terminal window no longer accepts input. No characters get echo'd back as I type them. The only keystroke that seems to do *anything* is Ctrl+C, which emits `^C` in the terminal and reprints the prompt. See screenshot.

During this time, editing of ordinary files seems to still work. I could also open new files, so this wasn't a connectivity issue.

![image](https://user-images.githubusercontent.com/3548/73676417-90a1e800-4671-11ea-9bb5-c1de088bf1e8.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.0.0-1028-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.87GB free)|
|Process Argv|--open-url -- vscode://ms-vsonline.vsonline/connect?environmentId=ed2de422-b308-4e9f-9ffc-1e11c8bc4628&sessionPath=/home/vsonline/workspace&correlationId=9107ab16-7490-4ed5-a971-06c629d46c82|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|VS Online: vs-streamjsonrpc|
|OS|Linux x64 5.0.0-1028-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (10.09GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.10.0
remote-wsl|ms-|0.41.7
vsonline|ms-|1.0.1507
debugger-for-chrome|msj|4.12.6
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
vscode-icons|vsc|9.7.0
azure-account|ms-|0.8.8
vsliveshare|ms-|1.0.1510
vsonline|ms-|1.0.1507
vscodeintellicode|Vis|1.2.4

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@AArnott can you check devtools console and the renderer log file for errors?

**Comment by AArnott** [comment]
I don't have that window running any more. I'm trying to repro it now.
Where can I find the renderer log file from the prior session?

**Comment by Tyriar** [comment]
Not sure about on the web, on desktop you use the commands Developer: Open Log File/Folder

**Comment by AArnott** [comment]
This was the VS Code desktop app. 
Here is the renderer log that has a timestamp shortly before I reported this:
[main.log](https://github.com/microsoft/vscode/files/4154580/main.log)

It hasn't repro'd yet so I guess I can't recover the live devtools console output.

**Comment by Tyriar** [comment]
This looks like the main process log, the renderer log will be under `Developer: Open Log File > Window`. Let me know if you find any other info.

**Comment by AArnott** [comment]
That's strange. I thought I'd dragged the renderer log in. It looks like in the last few hours VS Code cleaned up yesterday's logs, so I don't have any from yesterday morning any more. :(
