### ISSUE TITLE
Markdown preview jumps a bit on every keystroke

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#89930]
Issue Type: <b>Bug</b>

* have a markdown preview to the side
* type in the `.md` file
* the preview jumps a bit on each keystroke

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/73661040-a9be8f00-4699-11ea-9c49-ef9f838f9385.gif)

VS Code version: Code - Insiders 1.42.0-insider (be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b, 2020-01-31T14:45:49.503Z)
OS version: Windows_NT ia32 10.0.18362

**Comment by mjbvz** [comment]
This is related to how the markdown is syncing the scroll. Some points of interest:

1. This code runs in the markdown preview (which is  a webview): https://github.com/microsoft/vscode/blob/b10335675f9673cbd87e04d6a9808d3d6a75975a/extensions/markdown-language-features/preview-src/scroll-sync.ts#L1

1. Look at where function such as `scrollToRevealSourceLine` are being called from

**Comment by meganrogge** [comment]
@mjbvz There isn't a script called build-preview in the extensions/typescript-language-features [package.json](https://github.com/microsoft/vscode/blob/937b30edf2671e6e13a044b76b412174ddf5135a/extensions/typescript-language-features/package.json#L35). 

Also, I can't re-produce this issue.

**Comment by mjbvz** [comment]
Should be fixed by 8f672cac62d52f47439a4afc014c63bd8aba97bd

![recording (2)](https://user-images.githubusercontent.com/12821956/139756108-68c869c3-3e60-4feb-a389-e2880183fcc8.gif)

There are likely still a few edge cases where it won't work perfectly, but the original example and other tests in vscode-docs worked for me
