### ISSUE TITLE
The terminal process terminated with exit code: 1

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#89932]
- VSCode Version: 1.41.1
- OS Version:10.0.19555

Steps to Reproduce:

1. Open terminal with Ctrl+`  or
1. Open terminal from menu Terminal New Terminal

Does this issue occur when all extensions are disabled?: Yes

A quick message appears and disappears:
"Windows Subsystem for Linux has no installed distributions"

**Comment by Tyriar** [comment]
You need to install WSL for it to work. Change your default shell if you don't want to use WSL (F1, "default shell"

**Comment by theking2** [comment]
No Wsl is not really needed. but if it was installed once and than remove
vscode very much might not be having a terminal anymore.
