### ISSUE TITLE
TypeScript language service died 5 times right after it got started

### ISSUE THREAD

**Issue by Juwon22** [microsoft/vscode#89937]
Issue Type: <b>Bug</b>

Launch vscode with .js

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.3.0

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.0
flutter|Dar|3.8.0
python|ms-|2020.1.58038
java|red|0.55.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Closing as not actionable without more info
