### ISSUE TITLE
Source control view not showing up

### ISSUE THREAD

**Issue by navidarry** [microsoft/vscode#89939]
new Feb 2019 Update has been not working source control, this is empty
![Screenshot_20200203_212828](https://user-images.githubusercontent.com/54308558/73677941-8fea6f80-46cc-11ea-836a-e355168c9269.jpeg)

**Comment by joaomoreno** [comment]
Can you open `Developer: Toggle Developer Tools`, any errors there?

**Comment by navidarry** [comment]
I right clicked on source controller window then click on the project name, this resolve issue, 
thanks
