### ISSUE TITLE
Add support for rebinding Column Selection

### ISSUE THREAD

**Issue by Aarilight** [Microsoft/vscode#8993]
Currently there is no way to rebind column selection. The only bindings that can be changed for column selection are as follows:
![](http://puu.sh/pVyet/447aaf5f64.png)

 In other programs it's bound by default to `middle click` or `alt+drag`, but in VSCode it's bound to `alt+shift`. It's not an inherently bad thing to do bindings different than other programs, but it'd be nice if it was configurable. I'd really like to change it to `alt`, personally. [And I'm not alone, either.](https://github.com/Microsoft/vscode/issues/1515#issuecomment-224232517)

It's possible that it can already be rebound, but as it's not in the `Default Keyboard Shortcuts` file, there's no way for the basic user to find out that it can be rebound. This would be an even easier fix if that was the case, tho--simply add an entry for it.

**Comment by alexandrudima** [comment]
:+1: Let's track this request in #3130
