### ISSUE TITLE
Contributed actions from extensions no longer work

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#89948]
Appears to have been caused by https://github.com/microsoft/vscode/commit/ec28475881d4b5ad4570a579381317b29bbd2a5d

Contributed actions from the SCM viewlet, remote explorer, other extensions etc. no longer work in `master`. This also affects the right-click menus. Reverting the above commit fixes the issue.

**Comment by jrieken** [comment]
Thanks @misolori
