### ISSUE TITLE
Tab indent much larger and converting to spaces even though Tab Size is set to 2 Spaces and Insert Spaces disabled

### ISSUE THREAD

**Issue by JoelLisenby** [microsoft/vscode#89941]
Issue Type: <b>Bug</b>

Enter PHP file, hit tab.

Expected behavior-- 2 space width tab

Actual behavior-- 8 spaces inserted. Tab indent much larger and converting to spaces even though Tab Size is set to 2 Spaces and Insert Spaces disabled

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (23.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.12.9
remote-wsl|ms-|0.41.7

</details>

**Comment by JoelLisenby** [comment]
I ran a search before hand and none of those seem related I think.

**Comment by eamodio** [comment]
What is your `editor.tabSize` setting set to? Do you have any language specific settings for it? Like:
```
"[php]": {
  "editor.tabSize": 8
}
```

**Comment by JoelLisenby** [comment]
Below is my current settings.json. I do not think I have any language specific settings.
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "droid sans mono",
    "editor.fontSize": 13,
    "php.validate.executablePath": "E:\\software\\php\\php.exe",
    "editor.minimap.enabled": false,
    "git.enableSmartCommit": true,
    "window.zoomLevel": 0,
    "breadcrumbs.enabled": false,
    "sftp.debug": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "diffEditor.renderSideBySide": true,
    "editor.insertSpaces": false,
    "workbench.editor.highlightModifiedTabs": true,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": false,
    "editor.tabSize": 2,
    "diffEditor.ignoreTrimWhitespace": false
}
```

**Comment by eamodio** [comment]
I can't seem to reproduce this -- can you capture a gif/video of the behavior you are seeing?

**Comment by JoelLisenby** [comment]
![image](https://user-images.githubusercontent.com/428122/73697012-690f4780-4692-11ea-988e-45b4c1ca6324.png)

I think I found out where I can adjust the configuration as seen above which is in the bottom right status bar. I did not know about this-- 8 spaces seems to be the setting for only this particular file as set here. I never adjusted that via that button, perhaps there is a keyboard shortcut I accidentally typed that changed it for this particular file...

**Comment by alexdima** [comment]
@JoelLisenby By default, the editor will examine the file you open and guess the desired indentation based on the file content.

```
	// Controls whether `editor.tabSize#` and `#editor.insertSpaces` will be automatically detected when a file is opened based on the file contents.
	"editor.detectIndentation": true,
	// The number of spaces a tab is equal to. This setting is overridden based on the file contents when `editor.detectIndentation` is on.
	"editor.tabSize": 4,
	// Insert spaces when pressing `Tab`. This setting is overridden based on the file contents when `editor.detectIndentation` is on.
	"editor.insertSpaces": true,
```

You can disable this behavior by setting `"editor.detectIndentation": false`, in which case the configured `tabSize` and `insertSpaces` will be used.

If you think the detected indentation (spaces @ 8) is unexpected, please share the file with us so we can take a look at our indentation guessing code and see if it should have worked better in this case.

**Comment by JoelLisenby** [comment]
I'm pretty sure in this case it may have guessed correctly as > 50% of tabs in this particular file do appear to have 8 spaces inserted. Thanks for the clarification!
