### ISSUE TITLE
I can not open a 380 MB text file In VSC on Mac.

### ISSUE THREAD

**Issue by jason-west** [microsoft/vscode#89949]
- VSCode Version: 1.41.1
- OS Version:  Catalina 10.15.3

Steps to Reproduce:

1.  Open a 380 MB file
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamodio** [comment]
Can you provide more details on the type of text file -- just normal txt? Also please describe what happens when you try to open the file.

**Comment by rebornix** [comment]
Can you try to set `files.maxMemoryForLargeFilesMB` to a large value and see if it helps?
