### ISSUE TITLE
Editors are marked as visible when not in the DOM

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89943]
Add this code to settingsEditor2.ts, layout()

```ts
		if (!DOM.isInDOM(this.rootElement)) {
			console.log('not in dom');
			return;
		} else {
			console.log('in dom');
		}
```

![image](https://user-images.githubusercontent.com/323878/73682240-d7451180-4674-11ea-8ce2-81a9c8822678.png)

Then open two editor groups, open the settings UI in one, click the button to toggle horizontal/vertical orientation, and see that the first branch is hit.

I think that an editor should not be called "visible" if its root element is not in the DOM.

I think that this is new, because I think the `if (!this.isVisible())` check was trying to fix the same issue, but it might not be new.

**Comment by sbatten** [comment]
looks like we keep everything visible during the flipNode operation and looking at it, we might break other things if we changed that behavior

/cc @joaomoreno

**Comment by joaomoreno** [comment]
We could potentially prevent `layout` calls during `flipNode` since there's an [absolute `layout` call done right after](https://github.com/microsoft/vscode/blob/2524412d5c400f94f75e5e4098e8d65654837e58/src/vs/base/browser/ui/grid/gridview.ts#L766).
