### ISSUE TITLE
It doesn't appear to me gutter indicators.

### ISSUE THREAD

**Issue by Dezyderyjczyk** [microsoft/vscode#89947]
Hello.

I'm sorry, I do not know English. This is the translation of the program.

System: Linux.
Version VSC: 1.41.1
Configuration files - deleted.

I open vsc, point to the working directory of the git repository, edit the file from the repository, the git icon indicates changes but no markings on the gutter indicators.

I am asking for advice. What to look for?

**Comment by eamodio** [comment]
Do you see the repository and the changed file in the Source Control view?

**Comment by Dezyderyjczyk** [comment]
OS: Ubuntu bionic
VSCode: 1.41.1 install from repo apt-get.
EXT:
adamvoss.vscode-languagetool-3.8.0
adamvoss.vscode-languagetool-en-3.8.0
adamvoss.vscode-languagetool-pl-3.8.0
alefragnani.project-manager-10.10.0
coenraads.bracket-pair-colorizer-1.0.61
ecmel.vscode-html-css-0.2.3
fallenmax.mithril-emmet-0.7.3
felixfbecker.php-debug-1.13.0
felixfbecker.php-intellisense-2.3.14
formulahendry.auto-close-tag-0.5.6
formulahendry.auto-rename-tag-0.1.1
imanilchaudhari.yii2-snippets-0.1.2
lonefy.vscode-js-css-html-formatter-0.2.3
pranaygp.vscode-css-peek-3.0.2
ritwickdey.live-sass-3.0.0
ritwickdey.liveserver-5.6.1
sidthesloth.html5-boilerplate-1.0.3
streetsidesoftware.code-spell-checker-1.7.22
streetsidesoftware.code-spell-checker-polish-1.0.2
syler.sass-indented-1.7.4
xyz.local-history-1.7.0
yo1dog.cursor-trim-1.0.0
zignd.html-css-class-completion-1.19.0

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?

**Comment by Dezyderyjczyk** [comment]
Looking for git in: git
Using git 2.17.1 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: /home/www/project
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git check-ignore -v -z --stdin
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel

**Comment by joaomoreno** [comment]
If you edit the file, does new output come along?

**Comment by Dezyderyjczyk** [comment]
Sometimes. But no errors.

git rev-parse --show-toplevel

**Comment by joaomoreno** [comment]
You're giving me very little information to understand what is going on.

Can you reproduce in another repository?

**Comment by Dezyderyjczyk** [comment]
Can you reproduce in another repository?

I don't understand.

**Comment by joaomoreno** [comment]
Do you have the same issue on other repositories?

**Comment by Dezyderyjczyk** [comment]
Yes, I tried with many. With old and new. Initialized from the command line and from vscode. I deleted the vscode configuration, all plugins, and nothing helped.

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`, **while** you open files and make changes on them?

**Comment by Dezyderyjczyk** [comment]
Looking for git in: git
Using git 2.17.1 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: /home/www/project
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git rev-parse --show-toplevel
...[> git rev-parse --show-toplevel] * 17
> git rev-parse --show-toplevel
> git check-ignore -v -z --stdin
> git rev-parse --show-toplevel
.... [> git rev-parse --show-toplevel] *

Nothing more. The last line appears before the activation of the editing window (after switching to a new or reactivation).

**Comment by joaomoreno** [comment]
And what's the full file path of the file you have opened and made changes on?

**Comment by Dezyderyjczyk** [comment]
These balls belong to the repository and are in the workspace.

**Comment by joaomoreno** [comment]
I'm sorry but I simply can't understand this. If you find a friend/colleague who can express your issue a bit better, please have them help you in describing it. Thank you.

**Comment by Dezyderyjczyk** [comment]
Problem solved. VSCode on linux works badly on non-local file systems (NFS, symlink ...).
