### ISSUE TITLE
Extraneous error: "Please clean your repository working tree before checkout"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89944]
1. Have a commit ahead of master and unstaged local changes. No commits behind master.
2. Run `git.sync` (with or without rebase)
3. 🐛 See "Please clean your repository working tree before checkout" error. This shouldn't be necessary if I'm not pulling any commits.

**Comment by joaomoreno** [comment]
We always pull since there's no way of knowing whether there are any new commits in the server without doing so. We could run a fetch before the pull, but that just seems excessive. Since this is such a (seemingly) rare situation, would a `Just Push` choice button in that dialog be enough?

**Comment by JacksonKearl** [comment]
I see, that’s fine I can just run push instead.
