### ISSUE TITLE
I commented on an issue with my full name and forgot about it before deleting my account. Is it possible for someone to delete the comment or at least hide it?

### ISSUE THREAD

**Issue by sudousrcode** [microsoft/vscode#89956]
I'm really sorry about this but I haven't been able to get a response from anyone about this on twitter.

**Comment by chrisdias** [comment]
which issue?

**Comment by sudousrcode** [comment]
@chrisdias https://github.com/microsoft/vscode/issues/15820#issuecomment-302288430

**Comment by chrisdias** [comment]
fixed
