### ISSUE TITLE
"The TypeScript language service died 5 times right after it got started. The service will not be restarted."

### ISSUE THREAD

**Issue by remy** [microsoft/vscode#89955]
Issue Type: <b>Bug</b>

Was running vs code, it keeps popping up a message saying "The TypeScript language service died 5 times right after it got started. The service will not be restarted."

This is a screenshot: https://cloudup.com/c3LCalNoXr7

Since it kept asking me to report, that's what I'm doing (though it seems like the notification should and could prepopulate this form - I've discarded it three times already…)

Happy to debug further with directions as I don't know what I should be looking for…

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|49, 30, 19|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-syntax|ati|0.5.1
vscode-mjml|att|1.6.0
code-gnu-global|aus|0.2.2
lit-html|bie|1.11.1
vscode-styled-jsx|bla|1.5.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
twitch-highlighter|cla|0.2.3
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
vscode-dash|dee|2.0.0
EditorConfig|Edi|0.12.8
vscode-npm-script|eg2|0.3.5
retroassembler|Eng|1.1.0
prettier-vscode|esb|3.18.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-pull-request-github|Git|0.12.0
rest-client|hum|0.21.2
z80-asm|Ima|0.0.3
search-node-modules|jas|1.3.0
copy-markdown-as-html|jer|1.1.0
jq-syntax-highlighting|jq-|0.0.2
vscode-github|Kni|0.30.3
graphql-for-vscode|kum|1.15.3
VS-code-vagrantfile|mar|0.0.7
slugify-vscode|max|1.1.0
rainbow-csv|mec|1.5.0
vscode-language-babel|mgm|0.0.21
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-autoprefixer|mrm|3.0.0
vscode-json5|mrm|1.0.0
vscode-azurestorage|ms-|0.7.1
python|ms-|2019.4.12954
azure-account|ms-|0.3.3
cpptools|ms-|0.21.0
csharp|ms-|1.21.9
Go|ms-|0.8.0
powershell|ms-|2019.12.0
sublime-keybindings|ms-|4.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.540
debugger-for-chrome|msj|4.11.1
language-liquid|nei|0.1.1
vetur|oct|0.21.0
react-proptypes-intellisense|OfH|1.0.3
vscode-docker|Pet|0.5.2
polacode|pnp|0.2.2
toggle|reb|0.0.1
postcss|ric|2.0.0
bash-debug|rog|0.3.6
nunjucks|ron|0.2.3
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
scope-info|sie|0.2.0
mdx|sil|0.1.0
vscode-fileutils|sle|3.0.1
addDocComments|ste|0.0.8
rewrap|stk|1.9.1
code-spell-checker|str|1.7.21
tabnine-vscode|Tab|2.1.22
python|tht|0.2.3
react-redux-es6-snippets|tim|2.1.0
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.274
wallaby-vscode|Wal|1.0.165
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(6 theme extensions excluded)

</details>

**Comment by remy** [comment]
@vscodebot thanks robot, but those other issues were closed because not enough information was provided. I'm hoping a humung will reply with details on how to dig out the information. Now go back to your robot planet for a snooze.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by dzpt** [comment]
@mjbvz no, it works fine with `TypeScript and JavaScript Language Features` vscode extension disabled. But since this is the built-in extension, how do we fix it?

**Comment by mjbvz** [comment]
Did you try the insiders build?

**Comment by dzpt** [comment]
@mjbvz i've solved it by upgrading typescript to latest version and using `TypeScript and JavaScript Language nightly build`

**Comment by banuiliuta** [comment]
The issue persists also in 1.42. For me didn't work any other solution than the rollback to version https://code.visualstudio.com/updates/v1_39.

**Comment by banuiliuta** [comment]
The issue persists also in 1.42. For me didn't work any other solution than the rollback to version https://code.visualstudio.com/updates/v1_39.

**Comment by dzpt** [comment]
@banuiliuta have you tried this one https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next ?
I'm using Typescript Version 3.7.5, vscode 1.4.2 and it's solved

**Comment by mjbvz** [comment]
@remy Did you get a change to test this?

**Comment by banuiliuta** [comment]
> @banuiliuta have you tried this one https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next ?
> I'm using Typescript Version 3.7.5, vscode 1.4.2 and it's solved
What you suggest I already tried several time but In my case didn't work.

**Comment by remy** [comment]
I did, and running Insiders with no extensions doesn't replicate the
problem. But then, I'd expect that. It's like testing an old machine's bug
against a brand new fresh machine. At least it rules out some core
underlying issue.

It doesn't help of course that the original issue is intermittent and I
suspect is related to CPU contention…

**Comment by mjbvz** [comment]
CPU usage would not cause this issue but other extension behavior certainly can. If you see this issue in insiders, then try tracking down which one triggers this. The most likely candidate are ones that ship with TypeScript server plugins
