### ISSUE TITLE
contextmenu

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#8995]
- VSCode Version: Code - Insiders 1.4.0-insider
- OS Version: Windows_NT 10.0.10586

![2016-07-09_172948](https://cloud.githubusercontent.com/assets/8591065/16707295/3e16175c-45fb-11e6-9b1d-3ca9ebc1870b.png)

Intended to be？

**Comment by jrieken** [comment]
Happens with empty buckets

**Comment by jrieken** [comment]
@ZCShou Can you paste your `package.json` so that I can understand where the empty bucket comes from?

**Comment by ZCShou** [comment]
@jrieken  where is the file？

**Comment by jrieken** [comment]
@ZCShou since it doesn't repro for me I assume that you have an extension that adds content menu items?

**Comment by ZCShou** [comment]
@jrieken have no any extension！
![2016-07-14_175814](https://cloud.githubusercontent.com/assets/8591065/16835726/90b63588-49ec-11e6-9352-0343c6b1d52e.png)

**Comment by jrieken** [comment]
That's interesting... Doesn't show for me.
![screen shot 2016-07-14 at 12 46 48](https://cloud.githubusercontent.com/assets/1794099/16837014/10e92728-49c1-11e6-8faa-64904e8cc78b.png)

**Comment by jrieken** [comment]
ok - I can reproduce on windows - seems like on mac the leading and trailing separators are ignored

**Comment by jrieken** [comment]
related to #8880

**Comment by ZCShou** [comment]
@jrieken  I find this issue this issue appears again on Win10
