### ISSUE TITLE
vscode.openFolder does not support switching local/remote environments

### ISSUE THREAD

**Issue by Christilut** [microsoft/vscode#89952]
Issue Type: <b>Bug</b>

It looks like the `vscode.openFolder` API does not support opening a remote folder when the current environment is not remote.

To reproduce:
1. Optional: Install `vscode-projects-plus` extension
2. Open a folder on the local filesystem
3. Now either use `vscode-projects-plus` to open a WSL folder or call the openFolder function manually
4. VSCode opens the folder but shows an error "Can not resolve workspace folder"

It should auto-detect that this folder is a remote folder or the `vscode.openFolder` command should be able to take an extra parameter to indicate where it should open it.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by aeschli** [comment]
`vscode.openFolder` can open remote folders. But you need to know the remote URI, which depends on the remote extension.
For WSL it is:
`vscode-remote://wsl+Ubuntu/home/joe/project`
  - Ubuntu is the name of the distro to open
  - `/home/joe/project` is the path in the distro
