### ISSUE TITLE
[feature] add scope support for CompletionItemProvider

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#89953]
atm the [CompletionItemProvider](https://code.visualstudio.com/api/references/vscode-api#CompletionItemProvider) doesn't have any scope constraints other than the `DocumentSelector` which is very generic

and similar to the snippets scopes issue https://github.com/microsoft/vscode/issues/89951#issuecomment-581592830 its makes it hard to find the exact completion item

however if we have an optional new key to specify where this completion should show up ex.
```js
let comp = new CompletionItem('sometext, CompletionItemKind.Text)
comp.scope = ["string.quoted.double", "string.quoted.single"] // omitting this will fall back to the original behavior

// ...
```
now the completion will only be visible if we called it inside a single or double quotes & it will have a higher score over other completions that doesn't have this key which will make it far easier to find exactly what you want

**Comment by jrieken** [comment]
There is no scope information available, it's up to extensions to implement semantics
