### ISSUE TITLE
The terminal process terminated with exit code: {0} when clicking New Terminal

### ISSUE THREAD

**Issue by gfinzerScotts** [microsoft/vscode#89950]
Version: 1.42.0-insider (system setup)
Commit: 705f01577dd37d6f17eaa683ab89b0c392fa1a7c
Date: 2020-02-03T14:02:55.075Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:
1.  Click New Terminal
2.  Error appears:  The terminal process terminated with exit code: {0}

Does this issue occur when all extensions are disabled?: Yes/No
Yes

FYI, this error started appearing after I did a Windows Update today.

**Comment by Tyriar** [comment]
/duplicate https://www.github.com/microsoft/vscode/issues/86432
