### ISSUE TITLE
Black Screen after remote desktop

### ISSUE THREAD

**Issue by llali** [microsoft/vscode#89967]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code in a Windows machine
2. From another machine remote access to the first machine
3. go back to the original machine 

Expected: VS code should be still open
Actual: VS code in the original machine turns to back screen 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
Is this still an issue with our latest insiders https://code.visualstudio.com/insiders
