### ISSUE TITLE
Unable to rename parent folder

### ISSUE THREAD

**Issue by RussKie** [microsoft/vscode#89969]
Issue Type: <b>Bug</b>

Create few nested folders, the top folder must have only a single child folder.
The VSCode doesn't expand the tree, instead inlines the parent folder.
When attempting to rename the parent folder, the child folder is renamed.

![image](https://user-images.githubusercontent.com/4403806/73705380-e9dd4a80-4749-11ea-91be-313eeef25013.png)
![image](https://user-images.githubusercontent.com/4403806/73705403-f95c9380-4749-11ea-8631-36d3ac7f628e.png)
![image](https://user-images.githubusercontent.com/4403806/73705424-0083a180-474a-11ea-8a57-1a10dce4e9b7.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (12 x 3402)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (12.91GB free)|
|Process Argv|C:\Development\!Tests\DynamicApps|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
quick-html-previewer|dai|1.0.1
dotnet-test-explorer|for|0.7.1
csharp|ms-|1.21.10
powershell|ms-|2020.1.0
prettier-plus|svi|3.6.3

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by IllusionMH** [comment]
@isidorn it is reproducible in Insiders as well, however it's not related to compact folders.

Expand any folder in Explorer, rename it - it will be collapsed after rename.

However if I have file opened somewhere deep in folder that I rename - it is noticeable that folder is collapsed after rename (for a second) and then expanded again because I have `"explorer.autoReveal": true`. All other folders that are not in path to file but nested in renamed folder will be collapsed.

**Comment by RussKie** [comment]
@isidorn the Insider build right clicking on an inlined parent works. <kbd>F2</kbd> only allow renaming the child, which, I think, is acceptable.
![vscode-rename](https://user-images.githubusercontent.com/4403806/73802874-14470a80-4813-11ea-82d6-1d536642feac.gif)


> Expand any folder in Explorer, rename it - it will be collapsed after rename.

This is a separate issue.
