### ISSUE TITLE
Feature request: Nest Extensions installed by Extension Packs

### ISSUE THREAD

**Issue by nejento** [microsoft/vscode#89964]
Hi,
I'd like to share an idea which I think might be super handy end ergonomic and I'm kinda wondering why no one propoed such idea earlier.
### Current state
When you go to Extensions tab after a month or so, you can't really differentiate which Extension got installed by which Extension Pack. Take for example this situation:
![obrazek](https://user-images.githubusercontent.com/1355003/73697162-2ffcc480-46de-11ea-80a7-645fef52d0ab.png)

I installed *Live Share Extension Pack* which installed three more Extensions: *Live Share*, *Live Share Audio* and *Live Share Chat*. 
But sorting of that list doesn't really make sense as the *Live Share Expansion Pack* which I installed and which doesn't really do anything on its own is listed as third Extension. 
I don't really have a way of knowing which Extension got installed by which Extension Pack. Orienting in such situation espetially when there are more Extensions and for example uninstalling is much more complicated then it could be.

### Proposed state
I'd like to see some kind of nesting of Extensions installed by Extension Packs or a simple line at every extension installed by Extension Pack so that I could easily say that I don't need to uninstall that because it got installed by an Extension Pack and is useful for that use.

Thanks for support 🙂

**Comment by nejento** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Add visual indicator for extension packs in extension search results (#89962)](https://www.github.com/microsoft/vscode/issues/89962)

My Feature request is similar to the #89962 however it doesn't propose nesting feature in the list itself. Also mine is a bit more detailed. 🙂

**Comment by fiveisprime** [comment]
Nested is also an idea I was considering. Thanks for opening this! :)

**Comment by sandy081** [comment]
/duplicate

#89962
