### ISSUE TITLE
Allow MarkdownString to only allow a specific set of commands

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#89966]
**Problem**
I want to use a command uri in some markdown content. However I don't want to enable all command uris since I am dealing with user content that could use unsafe command Uris.

**Feature Request**
Rather than trying (and likely failing) to sanitize my markdown content, it would be helpful if `MarkdownString` supported whitelisting one or more specific commands

Something like:

```ts
export class MarkdownString {
    ...

    trustedCommands?: readonly string[];
}
```

**Comment by eamodio** [comment]
I like it -- so if `trustedCommands` is `undefined` you get the current trust behavior and if specified then only linkify matches, right -- no errors or anything, just ignored content.

**Comment by jrieken** [comment]
Not very excited - this seems very specific for a use-case and it something that you easily achieve yourself..

**Comment by mjbvz** [comment]
Leaving this up to extensions feels like a recipe for problems. Even I don't feel I can be 100% that I've properly stripped out all bad command  uris. Better to have an extra layer of validation here.

From what I've seen, the most common use case of command uris is to enable a small set of known commands and not to enable arbitrary commands. Whitelisting specific command uris would be a alternative to `isTrusted`

---

The background for this: I'm exploring improving our JSDoc support. Since JSDocs are user content, I would like to enable a specific command in rendered JSDocs while not enabling arbitrary command uris

**Comment by eamodio** [comment]
@mjbvz Definitely agree. I could take advantage of this in GitLens -- where I only have ~5 commands I allow from the hovers (though since I markdown escape all the commit messages it isn't really an issue). Having a nice safety net to deal with content you didn't generate feels to me like a nice thing to have - and avoids parsing/safety issues spread around in each extension (if they bother at all).

**Comment by jrieken** [comment]
> Since JSDocs are user content, I would like to enable a specific command in rendered JSDocs while not enabling arbitrary command uris

Is that intermixed with the user doc? Iff not you could just return another hover-object. We added the `isTrusted`-flag for command links so it's weird if we add another property for that. If we need to go down that road, that I am more in favour of using another type, e.g `isTrusted: boolean | string[]`

**Comment by eamodio** [comment]
Yeah, I agree on `isTrusted: boolean | string[]` -- was thinking the same thing as it will be a bit strange to have 2 "flags" for trust

**Comment by eamodio** [comment]
@mjbvz is this still important to you?

**Comment by mjbvz** [comment]
Not today but we need this for JSDoc `@see` tag support, which depends on TS work that I'm hoping happens this year. I want to make sure we are ready to ship on the VS Code side once the TS part lands

**Comment by mjbvz** [comment]
Closing this for now since we came up with an API on the TS side can use normal `file` style links instead of command links
