### ISSUE TITLE
codeActionsOnSave eslint indent doesn't work sometimes

### ISSUE THREAD

**Issue by devhyunjae** [microsoft/vscode#89971]
- VSCode Version: 1.41.1
- OS Version: macos catalina 10.15.2

Steps to Reproduce:

1. Change the indent and press save
2. and it triggers the eslint autofix
```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
  },
```

sometimes it works
![150](https://user-images.githubusercontent.com/12890257/73706633-1777c300-474d-11ea-84f5-b2b6eccf01c4.gif)

sometimes it doesn't
![151](https://user-images.githubusercontent.com/12890257/73706652-23638500-474d-11ea-8cdf-2c24c13a36ae.gif)

Does this issue occur when all extensions are disabled?: Yes/No NO

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by mjbvz** [comment]
Also, this probably should be filed against the eslint extension

**Comment by devhyunjae** [comment]
@mjbvz if you think this is a eslint ext issue, you can close this

**Comment by devhyunjae** [comment]
@mjbvz and also doesn't work in insiders build too :(

**Comment by mjbvz** [comment]
Thanks for checking. Please try filing this issue against the ESLint extension first. They can follow up with us if they feel it's a VS Code issue
