### ISSUE TITLE
Task "DependsOn" Ignores And Discards Matched Child Problems

### ISSUE THREAD

**Issue by serialprimate** [microsoft/vscode#89975]
- VSCode Version: 1.41.1
- OS Version: Arch Linux

Steps to Reproduce:

I have a number of tasks of type shell, each with their own separate problem matchers. When I combine them as per below, then:

1. the problems for each child task are kept only until the next child task runs
2. the failure of a child task does not abort the combined task

The compound task definition:
```
        {
            "label": "all",
            "type": "shell",
            "dependsOn": ["configure", "build", "test", "install", "package"],
            "dependsOrder": "sequence",
            "problemMatcher": []     <== I have tried with and without this
        }
```
Each child task runs in its own terminal. I am not sure why.

```
"presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true      <== I have tried true and false
            }
```

Does this issue occur when all extensions are disabled?: Yes

Anyway thanks for all the hardwork. Please let me know if I am doing anything silly or if you need further feedback.  ;-)

Matt

**Comment by alexr00** [comment]
The failure of one child task doesn't stop execution of all is a duplicate of https://github.com/microsoft/vscode/issues/84789 which is fixed for the 1.42 release.

I'll take a look at the problem matcher issue.

**Comment by alexr00** [comment]
I can't repro the problem matcher issue. Can you try out the insiders build and see if you're having the same problem there?

**Comment by serialprimate** [comment]
The problem does not happen with insiders!

Thanks for looking into it.
