### ISSUE TITLE
'Access is Denied' Message When Compile C++ 

### ISSUE THREAD

**Issue by JabariD** [microsoft/vscode#89972]
Issue Type: <b>Performance Issue</b>

I get an "Access is Denied" message everytime I try to compile a NEW C++ file. C++ files that I made a while ago STILL work and do not give me an 'Access is Denied' message.

I can see the .exe files show up but then disappear after a few seconds which gives me the message "Access is Denied".

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.50GB free)|
|Process Argv|C:\Users\denni\Desktop\Google\Source1.cpp|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	 18880	code main
    0	    13	  3448	   electron-crash-reporter
    0	    80	  5224	   shared-process
    0	    67	  5408	   window (Issue Reporter)
    0	   343	  7672	   gpu-process
    0	   258	 14884	   window (Untitled-1.cpp - Visual Studio Code)
    0	    68	   472	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   190	  2456	     extensionHost
    0	    85	  2228	       electron_node server.js 
    0	    30	  4048	       electron_node server.js 
    0	    34	  6648	       electron_node server.js 
    0	    24	  9604	       c:\Users\denni\.vscode\extensions\ms-vscode.cpptools-0.26.3\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    48	  1196	         "c:\Users\denni\.vscode\extensions\ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 9604 3
    0	    10	 16652	         console-window-host (Windows internal process)
    0	   532	 11244	       "C:\Program Files\Java\jdk1.8.0_241\bin\java" -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar c:\Users\denni\.vscode\extensions\redhat.java-0.55.1\server\plugins\org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar -configuration c:\Users\denni\.vscode\extensions\redhat.java-0.55.1\server\config_win -data C:\Users\denni\AppData\Local\Temp\vscodesws_40a69\jdt_ws
    0	    11	  3192	         console-window-host (Windows internal process)
    0	    36	 14204	       electron_node server.js 
    0	    33	 19096	       electron_node server.js 
    0	     5	 19344	     console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (105)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
easy-cpp-projects|ACh|1.7.7
vscode-sql-formatter|adp|1.4.4
c-cpp-makefile-project|adr|1.1.0
aessoft-class-autocomplete|AES|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
html-class-suggestions|And|1.0.7
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
lit-html|bie|1.11.1
vscode-intelephense-client|bme|1.3.9
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
gdb-debug|Dam|1.0.7
c-cpp-compile-run|dan|1.0.5
vscode-markdownlint|Dav|0.34.0
algorithm-mnemonics-vscode|dav|1.0.3
vscode-eslint|dba|2.0.15
python-preview|don|0.0.4
githistory|don|0.4.15
jquerysnippets|don|0.0.1
java-debug|DSn|0.0.2
css-flexbox-cheatsheet|dzh|1.2.1
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
prettier-vscode|esb|3.20.0
bootstrap-4-cdn-snippet|eve|1.3.0
git-project-manager|fel|1.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
file-icons|fil|1.0.21
vscode-firefox-debug|fir|2.6.1
vscode-npm|fkn|3.3.0
code-runner|for|0.9.15
sass-lint|gle|1.0.6
CppSnippets|har|0.0.14
live-html-previewer|hdg|0.3.0
animate-css|Hri|1.0.0
jquery-snippets|Hri|1.0.0
path-autocomplete|ion|1.13.3
java-properties|ith|0.0.2
vscode-gnu-global|jay|0.3.2
c-cpp-flylint|jbe|1.4.1
better-cpp-syntax|jef|1.14.22
bracket-peek|jom|1.1.0
mips|kda|0.0.5
vsc-python-indent|Kev|1.8.1
vscode-github|Kni|0.30.3
clangcomplete|kub|1.0.1
jlang-clang|l3d|0.0.8
vscode-JS-CSS-HTML-formatter|lon|0.2.3
javadoc-tools|mad|1.3.1
vscode-language-babel|mgm|0.0.25
git-graph|mhu|1.21.0
python|ms-|2020.1.58038
remote-wsl|ms-|0.41.9
cpptools|ms-|0.26.3
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|3.8.20200201
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
php-docblocker|nei|2.1.0
clang-tidy|not|0.3.0
emoji|Per|0.0.3
material-icon-theme|PKi|3.9.2
vscode-css-peek|pra|3.0.2
java|red|0.55.1
LiveServer|rit|5.6.1
dashmips-debugger|roa|0.1.3
sql-snippets|sad|0.0.4
vscode-javascript-booster|sbu|0.11.0
git-merger|sha|0.4.1
sql-bigquery|shi|1.4.0
html5-boilerplate|sid|1.0.3
code-spell-checker|str|1.7.22
bootstrap4-vscode|the|6.1.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
c-cpp-flag-debugging|uts|0.0.1
Angular2|UVB|0.4.1
better-mips|vas|0.2.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
gitblame|wad|3.0.1
vscode-todo-highlight|way|1.0.4
bootstrap-3-snippets|wcw|0.1.0
html-snippets|wge|0.1.5
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
clang-format|xav|1.9.0
mip-snippets|xue|0.0.4
bootstrap-v4-snippets|Zac|1.1.3
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by eamodio** [comment]
Please reach out the the [C++ extension](https://github.com/microsoft/vscode-cpptools) and hopefully they can help you resolve the issue.
