### ISSUE TITLE
Visual Studio Code for MAC automatically remove carriage return when saving the file.

### ISSUE THREAD

**Issue by ashraftm** [microsoft/vscode#89970]
I am using Visual Studio Code 1.41.1 for MAC.
Visual Studio Code for MAC automatically remove carriage return from every line if I save the file. This is an issue if I compare in GIT.

HEX value shows (Example)
0D0A -- original (carriage return + line feed)
0A -- if I save the file in visual studio code
0D0A - if I use another editor (ex: text editor)

Local setup
1. Remove all extensions
2. Auto format disabled when save
3. Open an existing .cs file in VS Code, add few lines  (carriage return + line feed)
4. Compare files  (mine don't shows carriage return but shows only line feed)

**Comment by rebornix** [comment]
By default we will choose the line feed to use based on OS, you can disable this feature by setting `files.eol` to `\r\n` for your workspace.
