### ISSUE TITLE
Git checkout won't work

### ISSUE THREAD

**Issue by Susanthab** [microsoft/vscode#89973]
- VSCode Version: 1.41.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. git checkout -b somebranch
2. modify any file.
3. git checkout master
4. You still see the modifications done in <somebranch> to that file, which should not be the case.
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
This is correct behavior with Git -- as long as the edited file isn't in conflict when you change branches it will leave the file edited, otherwise the `checkout` will fail.

**Comment by Susanthab** [comment]
Hi @eamodio , File will remain edited but the changes should not be visible when I checkout the branch. For example, If I do some edit on file A in branch A, then I do a checkout master, I should not see the changes I made to file A in branch A. That is the issue here.

**Comment by eamodio** [comment]
@Susanthab The behavior you are seeing is correct (and also has nothing to do with VS Code -- it is Git's behavior). Git doesn't wipe out uncommitted edits when you switch branches.

**Comment by Susanthab** [comment]
Okay. Cool. Thanks for the clarification.
