### ISSUE TITLE
Nesting of file level very difficult to see

### ISSUE THREAD

**Issue by jianlin** [microsoft/vscode#89985]
- VSCode Version:

Version: 1.41.1

- OS Version:

Mojave

Steps to Reproduce:

It is very difficult to see the nest level. I often clicked the wrong file in a wrong folder:

https://imgur.com/a/kyN9LiH

Compare it with Atom:

https://imgur.com/HibjXXw

**Comment by eamodio** [comment]
You can change the indent level of the tree views by changing `"workbench.tree.indent": <number>,`. Let me know if that solves the issue for you.

**Comment by jianlin** [comment]
> workbench.tree.indent

ok it worked... to set the number of pixels...
