### ISSUE TITLE
A blank line found every time I type in the first command in the integrated command prompt.

### ISSUE THREAD

**Issue by joshivaibhavs** [microsoft/vscode#89988]
Every time I open the integrated cmd inside vs code, I see a blank line before I type the first command. If I press enter, the blank line goes away.

![vs-code-terminal-error](https://user-images.githubusercontent.com/60647675/73732573-69761400-4760-11ea-864d-854aa98dde49.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
