### ISSUE TITLE
Zen mode doesn't rescale to large resolution

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode#89981]
Issue Type: <b>Bug</b>

Minor inconvenciance but feels like a bug.

1. Start Zen mode on lower resolution screen (laptop screen in my case)
2. Send application to larger screen (using Win+Shift+Arrow)
3. Observe Zen mode still active but no longer full screen

VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T14:02:55.075Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

![bild](https://user-images.githubusercontent.com/1297882/73723623-bee2fe80-4729-11ea-8b4b-79519d1b2185.png)

**Comment by isidorn** [comment]
This feels like an electron bug.
@csholmq can you reproduce this with Chrome, and going to full screen?
fyi @deepak1556 in case you are aware of an existing Electron issue

**Comment by csholmq** [comment]
@isidorn Using normal Chrome browser and running full screen (F11) I was not able to reproduce.

**Comment by isidorn** [comment]
@csholmq can you still reproduce this with latest vscode insiders?
If yes let us know and we can reopen this
