### ISSUE TITLE
Installing C# extension fails

### ISSUE THREAD

**Issue by epicvrvs** [Microsoft/vscode#8998]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.6.3-1-ARCH

Steps to Reproduce:

1. Ctrl + P
2. ext install csharp
3. Click "Install"

Expected behaviour:

Visual Studio Code installs the C# extension.

Actual behaviour:

Visual Studio Code does nothing.

Additional information:

I tried to obtain additional information by launch VSCode from the commandline, hoping for cerr output. No luck. I'm not sure if it writes to any log files either.

**Comment by er3456qi** [comment]
So am I

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408 for a solution!
