### ISSUE TITLE
organizeImports duplicates and removes code (destroys syntax)

### ISSUE THREAD

**Issue by Spenhouet** [microsoft/vscode#89984]
### Two issues:

- Unstable / inconsistent formatting - Formatting changes with every save
- **Removes or duplicates code - Destroys code base and syntax**

### Steps to Reproduce:

1. Use the following setting:
```
{
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        }
    }
}
```
2. Open a python file
3. Enter the following import
```
from utils.python_utils import (CaseInsensitiveDict, CaseInsensitiveKey, CaseInsensitiveSet,
                                UpperLowerBound)
```
4. Press save

### Result

You will either get this (duplicated and destroyed code):

```
from utils.python_utils import (CaseInsensitiveDict, CaseInsensitiveKey,
                                CaseInsensitiveSet, UpperLowerBound)
    UpperLowerBound)
```

or that:

```
from utils.python_utils import (CaseInsensitiveDict, CaseInsensitiveKey,
                                CaseInsensitiveSet, UpperLowerBound)  
```

### Expected Result

Nothing changes. 
No imports need to be sorted. Everything is sorted. 
The import was already formatted correctly.

This is really bad. If this happens the first time, saving a second time will be very destructive to your code. It will start duplicating and deleting other lines in your file.

Environment:
- VSCode Version: 1.41.1
- OS Version: Windows 10 (build 1909)

**Comment by eamodio** [comment]
Please open an issue for the [Python extension](https://github.com/Microsoft/vscode-python).

**Comment by Spenhouet** [comment]
Thanks for the redirect. I opened an issue here: https://github.com/microsoft/vscode-python/issues/9889
