### ISSUE TITLE
no IntelliSense inside snippets

### ISSUE THREAD

**Issue by borishere** [microsoft/vscode#89997]
Issue Type: <b>Bug</b>

1. in a .js file insert 'if' snippet
2. you won't see IntelliSense panel while filling in condition

![Screenshot_6](https://user-images.githubusercontent.com/4622497/73738165-0468f100-4755-11ea-9c4c-c272f75b0f81.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
/confirmationPending

![image](https://user-images.githubusercontent.com/1312662/73739275-96213000-474e-11ea-9002-52457fd72571.png)

Works fine in Insiders and Stable if I check in regular and Untitled-x files if I press <kbd>Ctrl</kbd>+<kbd>Space</kbd>.

Does IntelliSense works in other places?

**Comment by ViniciusFXavier** [comment]
Works fine
![image](https://user-images.githubusercontent.com/40774281/73740963-023c6d80-4728-11ea-8bf4-7739a35590a5.png)

**Comment by IllusionMH** [comment]
Could you please clarify the problem is that:
you start typing but no suggestions until you manually trigger them with <kbd>Ctrl</kbd>+<kbd>Space</kbd>
or there are no suggestions even if you trigger them?

I only observer first case

**Comment by borishere** [comment]
> Could you please clarify the problem is that:
> you start typing but no suggestions until you manually trigger them with Ctrl+Space
> or there are no suggestions even if you trigger them?
> 
> I only observer first case

I'm talking about the first case. Works fine after manual trigger but it should appear automatically.

**Comment by IllusionMH** [comment]
/confirm

(sorry for the spam, missed the command. Removed previous message)

**Comment by jrieken** [comment]
This setting: `editor.suggest.snippetsPreventQuickSuggestions`

**Comment by borishere** [comment]
> This setting: `editor.suggest.snippetsPreventQuickSuggestions`

Thanks, it solves the issue.
