### ISSUE TITLE
Workspace with ASP.NET Core (Microsoft.NET.Sdk.Web) project

### ISSUE THREAD

**Issue by Aggravate** [microsoft/vscode#89990]
Issue Type: **Bug**

Go to definition and similar c# tools are not working when project is part of a workspace. It works fine when opened as single project.

- VSCode Version: **1.41.1 (user setup)**
- OS Version: **Windows**

- Electron: **6.1.5**
- Chrome: **76.0.3809.146**
- Node.js: **12.4.0**
- V8: **7.6.303.31-electron.0**
- OS: **Windows_NT x64 10.0.18362**

Steps to Reproduce:
1.  Create a web project from cli like this:
```
dotnet new webapi -o TodoApi
```
2. Create a Workspace and add the project from **Step 1** to this workspace
3. Open Startup.cs or WeatherForecastController.cs and try to use some stuff like:
- Go to Definition
- Go to Implementation
- ...

Expected: Go to Definition, Go to Implementation, ...
Actual: "No Definition found for '...'"

![image](https://user-images.githubusercontent.com/638400/73733186-cc08e900-473b-11ea-8660-d8c215946576.png)

**Comment by eamodio** [comment]
Please file this issue with the [C# extension](https://github.com/OmniSharp/omnisharp-vscode)

**Comment by Aggravate** [comment]
On my way, thank you. :)
