### ISSUE TITLE
Whitespaces are not rendered correctly for "non-bold" fonts.

### ISSUE THREAD

**Issue by muhammedatici** [microsoft/vscode#89991]
VSCode Version: 1.42.0-insider (system setup)
Date: 2020-02-03T14:02:55.075Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

It happens when you make non-bold fonts bold.

***Scenario 1***: bitstream-vera-sans-mono.ttf, bitstream-vera-sans-mono-italic.ttf **installed**, bitstream-vera-sans-mono-**bold**.ttf **not installed** and "editor.fontWeight": "600"

![bsvrm](https://user-images.githubusercontent.com/38614535/73732848-f1055800-474b-11ea-965a-b4a006d70485.png)

***Scenario 2***: bitstream-vera-sans-mono.ttf, bitstream-vera-sans-mono-bold.ttf, bitstream-vera-sans-mono-italic.ttf (all bitstream-vera-sans mono font variants) **installed**, and "editor.fontWeight": "600"

![scenario-2](https://user-images.githubusercontent.com/38614535/73733088-5f4a1a80-474c-11ea-9c37-e6df2f15226b.png)

I tried this for other fonts (monaco, hack, fira code etc.) but results are the same for all fonts! 

This bug exists only in the Insiders version (1.42), not in the stable (1.41.1) version.

**Comment by alexdima** [comment]
I believe the fix for https://github.com/microsoft/vscode/issues/90197 (https://github.com/microsoft/vscode/commit/e0322d3f5c19d15feadbb3337ffb9a5e39674834) also fixes this issue.

**Comment by dbaeumer** [comment]
Marking as duplicate.
