### ISSUE TITLE
Document language type

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#90]
On this page, https://code.visualstudio.com/docs/extensionAPI/activation-events, specifically: activationEvents.onLanguage

How does one determine the string that is valid for onLanguage? For example, in my CSS file, would I use:

css
CSS
stylesheet

etc?

**Comment by jrieken** [comment]
That isn't a finite list but depends on the installed extensions. Use `languages.getLanguages` (https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages) to get a list of all installed languages

**Comment by cfjedimaster** [comment]
Fair enough, but could the docs mention that?

On Thu, Nov 19, 2015 at 1:51 AM, Johannes Rieken <notifications@github.com>
wrote:

> That isn't a finite list but depends on the installed extensions. Use
> languages.getLanguages (
> https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages) to
> get a list of all installed languages
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/90#issuecomment-158006992>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
