### ISSUE TITLE
[C#] syntax coloring breaks down with interpolated strings

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#900]
Using VSCode 0.10.3

The C# syntax coloring breaks down when interpolated strings are involved.

Example code

    namespace Test
    {
        public class Foo
        {
            static string AddTableName(string suffix) => $"Bar{suffix}_ADD";

            static string ModTableName(string suffix) => $"Bar{suffix}_MOD";

            static string DelTableName(string suffix) => $"Bar{suffix}_DEL";
        } 
    }

VSCode screenshot

![capture](https://cloud.githubusercontent.com/assets/563860/11524059/965e200e-991b-11e5-869b-2ec886350ee0.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-csharp#43

**Comment by aeschli** [comment]
Now tracked in https://github.com/OmniSharp/omnisharp-vscode/issues/101
