### ISSUE TITLE
Add option to show ruler in Zen mode

### ISSUE THREAD

**Issue by mononym** [microsoft/vscode#90003]
Title says it all.

Comments and docs cannot always be auto-formatted. It would be nice to be able to keep the visual marker of where these strings should be broken up.

**Comment by isidorn** [comment]
Please use the `"editor.rulers": []` setting. It shuold add the thing you are looking for.
If you only want this as part of zen mode then it is a duplicate of https://github.com/microsoft/vscode/issues/45617
