### ISSUE TITLE
Feature Request: Bind mouse buttons

### ISSUE THREAD

**Issue by karai17** [Microsoft/vscode#9000]
- VSCode Version: 1.3.0
- OS Version: Linux (Fedora 24)

Unless I am mistaken, there seems to be no way to remap/bind mouse buttons. One very useful use case for this is to drag-create multiple cursors by holding ctrl/alt+middle_mouse. Currently I need to manually select each individual line with alt+left_mouse (which i cannot remap to ctrl+left_mouse) which can be very tedious when I want to quickly select 15~ lines on the same column.

A good example of this would be the following Atom extension: https://atom.io/packages/Sublime-Style-Column-Selection or, as the name suggests, it is a native feature in Sublime Text.

**Comment by alexandrudima** [comment]
@karai17 In the meantime, could you workaround with the column selection (shift+alt+ drag) ? In any case let's track this feature request in #3130

**Comment by karai17** [comment]
I was not aware of that shortcut. That'll do for now. :)
