### ISSUE TITLE
Page Up/Down messes up layout when used in source control comment

### ISSUE THREAD

**Issue by brunnerh** [microsoft/vscode#90008]
Issue Type: <b>Bug</b>

I had a multi-line comment in the source control panel and pressed page up and down a few times and it scrolled the entire window content. The top part is scrolled outside the visible area and below it parts of a garbled console window show:

![image](https://user-images.githubusercontent.com/834235/73750011-bd7ef980-475c-11ea-9bca-494d05c7b9bc.png)

The scrolling can be fixed by moving the focus around by pressing Tab or focusing a menu item using e.g. `Alt+H`.

The console has to have been opened before, for the issue to occur.

Possibly relevant settings:

```json
{
    "terminal.integrated.rendererType": "experimentalWebgl",
    "window.titleBarStyle": "custom",
}
```

I was able to reproduce the issue with extensions disabled.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
Are you able to test with [Insiders](https://code.visualstudio.com/insiders)? The input box on the Source Control view has been changed significantly in the upcoming 1.42 release, and you can preview it now in Insiders.

**Comment by eamodio** [comment]
I can't reproduce this on insiders.

**Comment by brunnerh** [comment]
@gjsjohnmurray Just downloaded Insiders and it does not happen there 👍.
