### ISSUE TITLE
Code hangs on search

### ISSUE THREAD

**Issue by Anschur** [microsoft/vscode#90002]
Issue Type: <b>Bug</b>

When I start typing in the search box, Code seems to query as I type but the process seems blocking and leaves Code unresponsive for significant periods. This makes for a really crappy search experience. It would be better if it waited searching until I have finished formulating my query.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3691)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (5.47GB free)|
|Process Argv|search-dev-app.generated.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.0
RunOnSave|eme|0.2.0
prettier-vscode|esb|3.20.0
RelativePath|jak|1.4.0
sarif-viewer|MS-|2.14.0
csharp|ms-|1.21.10
powershell|ms-|2020.1.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
ejs-language-support|Qas|0.0.1
vscode-yaml|red|0.6.1
code-spell-checker|str|1.7.22

</details>

**Comment by JacksonKearl** [comment]
You can set ‘search.searchOnType: false’ or configure the ‘search.searchOnTypeDebouncePeriod’ in settings.
