### ISSUE TITLE
Merge conflict code lens doesn't work for me anymore

### ISSUE THREAD

**Issue by spmeesseman** [microsoft/vscode#90017]
- VSCode Version: 1.41.1
- OS Version: WIndows 10

Steps to Reproduce:

1. Create a merge conflict in SCM
2. Open conflict view, both sides of view are the same version

Does this issue occur when all extensions are disabled?: N/A

For some time now, my code lens view of merge conflicts has not been working.  I thought I might see that as an issue others are having, but found nothing that was not resolved.  Both options for the code lens that are needed are enabled.  I use the SVN extension for SCM, and this always used to work, I assume because Tortoise SVN output merge files in a format that VSCode can read, and present in the code lens?  I'm just trying to understand how it works, I did upgrade Tortoise to the latest some time ago and it was around the time the lens stopped working, not sure if coincidence or not.

Anything else I could check, or what could be wrong?

**Comment by spmeesseman** [comment]
I see whats happening now.  There are no line breaks in the markers.  WHen I add line breaks in the conflict view file, the lens appears.  Is this a Tortoise issue?
![mergeconflict-lens](https://user-images.githubusercontent.com/48744816/73763640-b5649100-473f-11ea-84dc-f4e123ef5fba.png)

**Comment by chrmarti** [comment]
Looks like a problem with the markers themselves, as you suggest. Any idea why the newlines are missing?
