### ISSUE TITLE
Mac: Move tabs down when moving mouse to the top in full screen mode

### ISSUE THREAD

**Issue by tarurar** [Microsoft/vscode#9001]
- VSCode Version: 1.3.0
- OS Version: OS X El Capitan

Steps to Reproduce:
1. Open VS Code in full screen mode
2. Make some files to be opened and the appropriate tabs to be shown in the top of the editor.
3. Move mouse to the top of the screen (trying to switch the tabs)
4. Can't click on the tabs

Have a look at the screenshots below:

<img width="1440" alt="screen shot 2016-07-09 at 16 54 57" src="https://cloud.githubusercontent.com/assets/142044/16708053/6c747e7c-45f6-11e6-8d33-ff6e1c22d090.png">

<img width="1440" alt="screen shot 2016-07-09 at 16 55 01" src="https://cloud.githubusercontent.com/assets/142044/16708054/7e5430a6-45f6-11e6-82fc-c04a3682070f.png">

Just to foreseen possible answer please have a look how chrome browser gently handles it:

<img width="1440" alt="screen shot 2016-07-09 at 16 55 23" src="https://cloud.githubusercontent.com/assets/142044/16708055/b8e5081c-45f6-11e6-8ae4-7feb68452765.png">

**Comment by bpasero** [comment]
Neither ST nor Atom solve this either, will require API from Electron to know when this happens. Marking as upstream.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
