### ISSUE TITLE
intelisense issue 

### ISSUE THREAD

**Issue by princemehta** [microsoft/vscode#90011]
please find the method to disable Mdn reference on hover without changing rest of the feature of intelisense..

**Comment by gjsjohnmurray** [comment]
Is this what you are seeking?

`"editor.hover.enabled": false`

**Comment by octref** [comment]
Please include more details, such as why you want this change. Many people find them useful.

**Comment by princemehta** [comment]
thanks for the solution but it disabled all hover effects like colour picker. i just need to remocve mdn reffernce feature in it
