### ISSUE TITLE
Expose and Expand other breakpoint/debug stuff colors

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#90013]
Right now, when you try to customize (via `workbench.colorCustomization`) breakpoint/debug color stuff,  you can only customize the _debug icon_ element. The _line_ is not available.

Today, only the _current stack frame_ line has color (that _yellowish_), with no customization at all.

It would be interesting to see:

* Customize the _current stack frame_ line background color (ie. `debugLine.breakpointCurrentStackFrameBackground`)

And, expand the `debugIcon` colors to _line_, creating similar `debugLine` elements, like:

* `debugLine.breakpointBackground`
* `debugLine.breakpointDisabledBackground`
* `debugLine.breakpointUnverifiedBackground`

Thank you

**Comment by isidorn** [comment]
We currently support 
`editor.stackFrameHighlightBackground` and `editor.focusedStackFrameHighlightBackground`
So the first part of your request is already there.

For the breakpoint line that is currently not supported and for that I can leave this open as a feature request for now.
Thanks!

**Comment by alefragnani** [comment]
Thank you @isidorn ! 

I can't believe I didn't find these two 🤦‍♂ ...

**Comment by isidorn** [comment]
The problem is that they do not have the word "debug" in them :-/

**Comment by alefragnani** [comment]
Yep... I wasn’t sure about looking for `debug`, `breakpoint` or `step`, and probably missed `stack`. 
Thank you 👍 .

**Comment by isidorn** [comment]
We have added some debug colors to the themes so they are customisable now.
Other colors we might add in the future.
