### ISSUE TITLE
How can a DebugConfigurationProvider determine Debug vs Run without Debugging

### ISSUE THREAD

**Issue by awschristou** [microsoft/vscode#90018]
If an extension implements a `DebugConfigurationProvider`, it would be useful to know if `resolveDebugConfiguration` was triggered in debug mode or run without debug mode.

The `debugConfiguration: vscode.DebugConfiguration` parameter appears to contain a `noDebug = true` property when using run without debug, but I don't see this mentioned in the VS Code API types or on the [API reference](https://code.visualstudio.com/api/references/vscode-api).

I'd like to know if `noDebug` is the endorsed way of detecting debug mode, and if it isn't, I'd like to request a way to detect this. I'm using `@types/vscode` v1.40

**Comment by weinand** [comment]
The "noDebug" attribute is specified in the Debug Adapter Protocol (DAP): https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Launch.
You can include that protocol as a TypeScript d.ts npm module [vscode-debugprotocol](https://github.com/microsoft/vscode-debugadapter-node).   

Please note that the DAP is not duplicated (or automatically included) in VS Code's extension API.
