### ISSUE TITLE
Comments with apostrophes disrupt code block indentation

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#90025]
Issue Type: <b>Bug</b>

I only tested in javascript.

Commented apostrophes on the same line as code that makes up a block will cause all lines after in a block of code to be indented incorrectly when you run the command 'Reindent Lines' via ctrl + shift + P

```
// good indent
if() {
    if() {
        
    } else {
        
    }
}
```

```
// bad indent
if() { //'

if() {
    
} else {
    
}
}
```

VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T14:02:55.075Z)
OS version: Windows_NT x64 10.0.18362

**Comment by eamodio** [comment]
I can reproduce this with other characters as well 
```
`"'
```

**Comment by rebornix** [comment]
We have increase indentation rules like

```
^((?!\/\/).)*(\{[^}"'`]*|\([^)"'`]*|\[[^\]"'`]*)$
```

and the part which leads to this issue is 

```
\{[^}"'`]*
```

`{"` will then not match

**Comment by rebornix** [comment]
@mjbvz the `onEnter` rules have higher priority than the indentation rules, so if tweaking the indentations is too complex, we can probably add a new onEnter rule for this case in particular.
