### ISSUE TITLE
Use IViewsService while using views and view containers

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90020]
Views should not be using panel service or viewlet service since they can be movable. Instead they should be using `IViewsService`.

All panels use `TogglePanelAction` to toggle the visibility. This should also be adopted.

**Comment by sandy081** [comment]
Introduce a context key `${view.id}.visible` that can be used for visible views.

**Comment by sandy081** [comment]
@sbatten Started refactoring `ActivityBarPart` to handle ViewContainers and remove `ViewletService` and `Viewlets`.

**Comment by sandy081** [comment]
Removed Viewlet semantics from Activity Bar and deals with new View terminology (ViewContainer)

**Comment by sbatten** [comment]
anything else that needs to be done here?

**Comment by sandy081** [comment]
Yeah.. Still have to go through all references of `IPanelService` & `IViewletService` and replace them with `IViewsService` and make sure those services are used only in `ViewsService`.

I will tackle it in next milestone.

**Comment by sandy081** [comment]
Remaining:

-  go through all references of `IPanelService` & `IViewletService` and replace them with `IViewsService`
- Use `IViewsService` instead of `IPaneCompositePartService` in workbench layout

**Comment by sandy081** [comment]
This is ✅
