### ISSUE TITLE
Contributed tree view sometimes not rendering children

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#90027]
Issue Type: <b>Bug</b>

1. Install GitHub Pull Request Extension and focus the viewlet
2. Check out a pull request so that the "Changes in Pull Request" view shows up
3. Expand the view
4. Reload the window
5. In the "Changes in Pull Request" view, expand "Files" or "Commits"

No children are shown under these nodes. From the extension side, I saw that "getChildren" was not being called at all on the tree. This seems to have started happening after https://github.com/microsoft/vscode/commit/28bf0b1f56dc4530331edb2e6e8bbc3df192372e

I'm not sure if this is the fault of the tree itself - I haven't seen this with other trees. What specifically seems to impact whether "getChildren" is called is this: https://github.com/microsoft/vscode-pull-request-github/blob/2285fdc17d20ce325163c23215f5fabc7a923be9/src/view/prChangesTreeDataProvider.ts#L63-L73

The view is made visible by the change to the a context key. When this is followed by an `onDidChange` event, "getChildren" is called on the context key change, but not when "onDidChange" is fired and expanding/collapsing the nodes does nothing. If the "onDidChange" is removed from there, or put before the context key change, then "getChildren" gets called twice and there is no issue with expanding/collapsing the children.

Since changing the context key causes the tree to re-render anyway, I can remove the "onDidChange" being fired there. But I'm worried there's still an underlying timing issue.

VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T13:59:34.701Z)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
Accepted as candidate as it is a regression
