### ISSUE TITLE
"Tab changes focus" mode is permanently on.

### ISSUE THREAD

**Issue by matek997** [microsoft/vscode#90026]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

1. Start VS Code
2. Open any file
3. Press "tab" while editing
4. Enable "tab changes focus"
5. Press "tab"
6. Disable "tab changes focus"
7.Press tab

Expected result:
Indentation with tab on steps 3, 7.

Does this issue occur when all extensions are disabled?: Yes

![Peek 2020-02-04 20-20](https://user-images.githubusercontent.com/46403984/73779288-ce476380-478c-11ea-9298-85c72815915a.gif)

**Comment by eamodio** [comment]
FWIW -- I can't seem to reproduce this on stable or insiders.

**Comment by matek997** [comment]
I can't point you in what led to it, it switched to this in middle of working.

> sudo apt purge code && sudo apt autoremove 

don't fix the problem, is the setting stored somewhere they don't get to?

**Comment by matek997** [comment]
Turning editor.tabCompletion on and off seems to have fixed issue for some reason.
