### ISSUE TITLE
UI freeze after moving to trash on KDE

### ISSUE THREAD

**Issue by jamezrin** [microsoft/vscode#90034]
Similar to https://github.com/microsoft/vscode/issues/54493

- VSCode Version: 1.41.1
- OS Version: Manjaro KDE 18.1.5 with latest updates

Steps to Reproduce:

1. Open a directory in VSCode
2. Delete a directory or a file (must be going to trash)

If I use Shift and Delete, it does not freeze.
It does not matter if the directory or file are empty, it happens anyway.
It takes approximately 3-4 seconds to unfreeze.

Does this issue occur when all extensions are disabled?: Yes

More relevant information of my installation:
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.99-1-MANJARO
```

**Comment by jamezrin** [comment]
Okay... I just went to the ArchLinux wiki article on Visual Studio Code and played with the `ELECTRON_TRASH`. Supposedly the default is `gio` but I think under KDE it is set to `kioclient5` or `kioclient`.

So, the solution is to launch Visual Studio Code like this `ELECTRON_TRASH=gio code` makes file/directory moves to the trash bin instant.

For now, I have created the file `~/.config/plasma-workspace/env/electron-trash-gio.sh` with
```bash
export ELECTRON_TRASH=gio
```

**Comment by k00ni** [comment]
I can confirm this behavior on **Ubuntu 18.04.4** running **plasma-desktop 5.12.x**. 

VSCode: 1.42.1

The **workaround** of @jamezrin works for me. :+1:

**Comment by mrkeuz** [comment]
Confirm. On Ubuntu 18.04 + KDE 5 same issue. 

Seems duplicate to #101920
Thanks to @jamezrin for solution

```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:15.161Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic
```
