### ISSUE TITLE
vscode.workspace.fs.readDirectory() reports symlinks to sockets incorrectly.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#90032]
(for use in the Python extension)

If a directory contains a symlink to a socket file then `vscode.workspace.fs.readDirectory()` will include it in the results.  However, the file type is reported as `SymbolicLink | File`.  I'd expect it to be `SymbolicLink | Unknown`.

Related: #84524, #84605, #90031

**Comment by bpasero** [comment]
Thanks for reporting these issues.

**Comment by connor4312** [comment]
Something I noticed that with this plus https://github.com/microsoft/vscode/issues/90031 it's now impossible to distinguish between a symbolic link that points to a socket and a broken link, since the unknown type is just `0` in the bitfield.
