### ISSUE TITLE
Blank window when more than 4 instances of VS Code Opened

### ISSUE THREAD

**Issue by chaitanyapotti** [microsoft/vscode#90037]
- Version: 1.41.1
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-20T11:11:01.597Z
- Electron: 6.1.7
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Linux x64 4.19.97-1-MANJARO

Steps to Reproduce:

1. Open 4 instances of vs code
2. Open 5th and it renders blank except for NavBar
![Screenshot from 2020-02-04 13-51-12](https://user-images.githubusercontent.com/1688380/73718026-51999280-4756-11ea-8b5c-29baaee4a2bd.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It looks like you built vscode your self ("Code - OSS"), does this happen when using the official build of VS Code?

**Comment by chaitanyapotti** [comment]
I just used the package from AUR
