### ISSUE TITLE
vscode opens a random file and wont let me close it

### ISSUE THREAD

**Issue by GingkathFox** [microsoft/vscode#90038]
- VSCode Version: 1.41.1
- OS Version: macOS 10.14

Steps to Reproduce:

1. Open up the Interactive Playground.  
For me atleast, a file named "vs_code_editor_walkthrough.md" will open. WHenever you close it, it will re-open itself, and it will not allow you to focus on a different file.

Does this issue occur when all extensions are disabled?: No

**Comment by eamodio** [comment]
Unfortunately I can't reproduce this. Can you provide any other details? What settings do you have set?

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: No

@GingkathFox it looks like the problem is caused by one of your extensions. I suggest you bisect (disable 50% of your extensions, re-test, repeat) until you find which one, then report it to the extension developer.

**Comment by GingkathFox** [comment]
Alrighty, will do.

**Comment by chrmarti** [comment]
Thanks.
