### ISSUE TITLE
Exclude Duplicate Lines in Search Results

### ISSUE THREAD

**Issue by jpragit** [microsoft/vscode#90033]
When you do a search in VS Code, it will return the same line multiple times if the search string is found in a line multiple times. For example, if you search for "Automobile", the following line will show up 3 times in the search results:

`var myAutomobile = CreateAutomobile('Ford Automobile');`

I'd like a feature or a setting so that each line is displayed in the search results only once.

(I know that I can manually remove a line from the search results by clicking the 'x' on the right-hand side, but it would be a huge time savings if there was an automated way to do this.

**Comment by ArturoDent** [comment]
You may want to check my comment back on SO: https://stackoverflow.com/questions/60006913/how-to-exclude-duplicate-lines-in-vs-codes-search-results/60013518?noredirect=1#comment106231547_60013518

**Comment by JacksonKearl** [comment]
This is a known limitation of the search viewlet, but in the search editor duplicates will show up on the same lime. 

I see in the linked SO post you mention not being able to open links from the search editor, they can be opened with F12, Ctrl/Cmd + Click, or Double Click.
