### ISSUE TITLE
Search Editor: entry missing from command palette

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#90039]
When I search for the `Open New Search Editor` command in the command palette it finds nothing.

![search open command](https://user-images.githubusercontent.com/31813701/73803775-ffb93280-477e-11ea-9acb-1aeaf52c6697.gif)

Version: 1.42.0-insider (user setup)
Commit: 705f01577dd37d6f17eaa683ab89b0c392fa1a7c
Date: 2020-02-03T14:02:55.075Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19555

Happens with all extensions disabled.

**Comment by ArturoDent** [comment]
Despite the gif above - it has started to work suddenly??  Very curious.

**Comment by JacksonKearl** [comment]
Unfortunately the current model will only acknowledge the "experimentalSearchEditorPreview" flag when you open the search viewlet. This is carried over from when the only way to access the Search Editor was from the viewlet. I am in the middle of a reworking that will fix this, but until then a workaround is to either use a keybinding to run the command, or open the search viewlet before running it.

**Comment by JacksonKearl** [comment]
Fixed in cf88fb47a578e4e1e51eb0997ad9d0d5b76963bd
