### ISSUE TITLE
[php] Ability to turn off PHP autocompletion by VSCode

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#9003]
There is now a better Intellisense plugins for Vscode PHP: [vscode-php-intellisense](https://github.com/felixfbecker/vscode-php-intellisense) and [crane](https://github.com/HvyIndustries/crane).

In it's known issues it says "There may be duplicate suggestions for functions or variables. This is because VS Code has it's own (very limited) code-completion support for PHP, and there is currently no way to turn this off."

This indeed is annoying, the vscode suggestions are too broad and are just noise compared to accurate entries by crane.

**Comment by jrieken** [comment]
It should be possible to uninstall the VS Code php extension.

**Comment by jrieken** [comment]
@joaomoreno fyi

**Comment by Ciantic** [comment]
I think crane still uses vscode's syntax highlighter for PHP. So if one were to remove VSCode's internal PHP extension, would it also remove the syntax highlighter?

**Comment by jrieken** [comment]
Yes - but we can also think about splitting our extension into one part that does highlighting and bracket config and another that does completions. That would allow for more freedom.

**Comment by Ciantic** [comment]
This is now annoying the testing of proper language server in here : https://github.com/felixfbecker/php-language-server/pull/165

Quote:

> VS Code has its own inferior completion. The only way to disable is going to the installation dir under resources/app/extensions/php/out/phpMain.js and commenting out the registration of the completionProvider.

**Comment by felixfbecker** [comment]
Related #16586

**Comment by felixfbecker** [comment]
Any update on this?

**Comment by felixfbecker** [comment]
I have been holding back the PHP IntelliSense release with intelligent completion for over a month now because it is useless if VS Code just spams the completion list with countless functions that do not make sense in the context. When will we get the option to disable or uninstall the built-in PHP completion?

**Comment by mousetraps** [comment]
I agree it makes sense to provide a temporary option to disable this. Just submitted a PR here: #19015

**Comment by mousetraps** [comment]
Also @felixfbecker, just checking - at this point in time, is there anything else about the built-in support that is interfering with the experience?

**Comment by felixfbecker** [comment]
@mousetraps thanks for looking into this. Signature help is being implemented right now, iirc there is no built-in hover. It would be great if all of them could be disabled (everything except syntax highlighting).

**Comment by aeschli** [comment]
I pushed the PR and changes the setting name for the code completion to "php.suggest.basic".

**Comment by ADmad** [comment]
I don't think the `php.suggest.basic` achieves the desired result. Setting `php.suggest.basic` to `false` I no longer get suggestion completions even from PHP Intellisense extension. If have to use `Ctrl + space` to trigger the completions suggestion list.

**Comment by felixfbecker** [comment]
@ADmad I don't think this is related, this only removes the built-in completion provider.

**Comment by ADmad** [comment]
So something else which controls the display of suggestions list from extensions like php intellisense is broken?

**Comment by felixfbecker** [comment]
So apparently this did _not_ make it into the January release?

**Comment by aeschli** [comment]
Part of the January build.
Add
` "php.suggest.basic": false`
to your settings to disable all completions from the built-in PHP extension.
