### ISSUE TITLE
Way to discern keyword by textMateRules scope

### ISSUE THREAD

**Issue by Billy-Sheppard** [microsoft/vscode#90035]
Would help custom textmate/syntax highlighting rules if you could hover over text in editor with Ctrl+Alt+Shift for instance and the popup would show the scope of the highlighted keyword/variable. E.g. hover over a variable declaration and it shows variable, but over the "var"/"let" as a keyword etc.

**Comment by gjsjohnmurray** [comment]
Is this what you are looking for?

https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector

**Comment by Billy-Sheppard** [comment]
Ah fantastic! I never realised it existed, despite my searching! Many thanks.
