### ISSUE TITLE
Suggestions missing on optional object properties after required properties are written.

### ISSUE THREAD

**Issue by maxijonson** [microsoft/vscode#90042]
Issue Type: <b>Bug</b>

Using the following code (TS 3.7.3)
```ts
interface ITextField {
    type: string;
    placeholder?: string;
    label?: string;
}

interface IUseFormProps{
    fields: { [name: string]: ITextField };
}

export const useForm = <T extends IUseFormProps>(
    options: T
) => { /* ... */ };
```
When I start typing:
```ts
const form = useForm({ fields: { firstName: { /* Ctrl+space here */ } } })
```
I can see all the `ITextField` options as expected. But as soon as I enter the `type` property (which is the only required one)

```ts
const v = useForm({ fields: { firstName: { type: "asdf", /* Ctrl+space here */ } } });
```

all the optional properties become no longer suggested. However, entering `placeholder: 123` does give a type error, as if it actually knows the type, but won't show suggestions for it.

I have tried disabling the extensions as well.

This is the actual use case. I have simplified the one above for clarity and also tried it to confirm it doesn't work.

Types:
```ts
interface IBaseField<T> {
    placeholder?: string;
    label?: string;
    hint?: string;
    required?: boolean;
    initial?: T;
    validation?: (value: T) => string | undefined;
}

interface ITextField extends IBaseField<string> {
    type: "text";
}

type IField = ITextField;

interface IUseFormProps {
    fields: { [name: string]: IField };
}
export const useForm = <T extends IUseFormProps>(
    options: T
) => { /* ... */ };
```

Works as expected:
![image](https://user-images.githubusercontent.com/23557893/73805997-46feed80-4796-11ea-8226-507f8e04f675.png)

Fails to suggest the remaining properties. I would expect it to show the remaining optional properties like it did just before I entered the required properties.
![image](https://user-images.githubusercontent.com/23557893/73806034-5da54480-4796-11ea-9938-574ff15079c1.png)

Still gives errors when giving a wrong type:
![image](https://user-images.githubusercontent.com/23557893/73806078-7ca3d680-4796-11ea-89e0-c660911c208d.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.0
prettier-vscode|esb|3.20.0
vscode-styled-components|jpo|0.0.28
remote-wsl|ms-|0.41.9
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.4
vscode-icons|vsc|9.7.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by mjbvz** [comment]
Confirmed as broken with TS 3.7 but works for me with TypeScript 3.8:

<img width="1401" alt="Screen Shot 2020-02-05 at 12 38 23 AM" src="https://user-images.githubusercontent.com/12821956/73824926-e2e92300-47af-11ea-9608-bb1146f9c063.png">


Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) (or use the VS code 1.43 insiders builds)
