### ISSUE TITLE
Add an option to turn off html tooltips

### ISSUE THREAD

**Issue by svetoslav80** [microsoft/vscode#90048]
![image](https://user-images.githubusercontent.com/10635709/73817489-b2c37380-47f3-11ea-8976-f09d85f575d3.png)

As stated here https://github.com/microsoft/vscode/issues/86009 , there is no setting to turn off html tooltips and they can be really annoying. Please add an option to turn them off. Entirely disabling hover is not a solution because of other useful tooltips.

**Comment by usernamehw** [comment]
You can make delay for hover longer just for `html` files (from **settings.json**):
```js
"[html]": {
	"editor.hover.delay": 2500
},
```

**Comment by svetoslav80** [comment]
usernamehw Thank you, this is a smart workaround.

**Comment by octref** [comment]
Or:

```json
"[html]": {
	"editor.hover.enabled": false
}
```

**Comment by svetoslav80** [comment]
> Or:
> 
> ```json
> "[html]": {
> 	"editor.hover.enabled": false
> }
> ```

Cool, thank you. This was suggested in the linked thread but I didn't realize this will disable hover only for html.
