### ISSUE TITLE
After period of time Intellisense is not working

### ISSUE THREAD

**Issue by mks-94** [microsoft/vscode#90045]
Issue Type: <b>Bug</b>

-->After period of time intellisense and suggestions is not working for my working reactjs projects.
-->when I create brand new project using create-react-app everything is working fine.
****Any One please suggest how resolve this problem.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (11.59GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.20.0
material-icon-theme|PKi|3.9.2

</details>

**Comment by mks-94** [comment]
Currently I'm working on React project with dependencies as follows
 "@material-ui/core": "^4.3.2",
    "@material-ui/icons": "^4.2.1",
    "axios": "^0.19.0",
    "material-ui-flat-pagination": "^3.2.0",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-google-login": "^5.0.5",
    "react-redux": "^7.1.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.3.0",
    "react-select": "^3.0.8",
    "react-toastify": "^5.3.2",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",

While working with vs code intellisense, Hover and suggestions are not working.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
