### ISSUE TITLE
Allow to customize command palette via CSS

### ISSUE THREAD

**Issue by iTouchTheSky** [Microsoft/vscode#9004]
Hi there,

This is not an issue, more like a request/suggestion.

I'm probably not the only one prefering the command palette from Atom to the one of vscode.
I like how they styled it.

My request/suggestions is that you add something to allow us to customize vscode visual elements (like the command palette) from within a custom stylesheet(that we would specify on the configuration file) or change the style of elements via the Extension API.

Thanks for taking the time to read this and I am hoping we can see this one day

**Comment by bpasero** [comment]
@iTouchTheSky so what exactly do you like more in Atoms version over Codes?

**Comment by iTouchTheSky** [comment]
Actually it's not only the command palette itself (to do actions), but all overlay like command palette, the "goto" file palette, etc that I want to be able to customize.

Atom allows theme to edit css of command palette, goto files, etc ...

[Atom's default command palette](http://i.imgur.com/6N0GA3b.png)
[Atom's command palette via a theme `nucleus-dark-ui`](http://i.imgur.com/ImkwwJe.png)

**Comment by glen-84** [comment]
This might be relevant: #459.

**Comment by iTouchTheSky** [comment]
@glen-84 To do it by hand, yes. But via a theme, no

**Comment by bpasero** [comment]
Closing for https://github.com/Microsoft/vscode/issues/3112
