### ISSUE TITLE
yarn start / stop bug

### ISSUE THREAD

**Issue by JasonCruz-Dev** [microsoft/vscode#90041]
W
Issue Type: <b>Bug</b>

when running Yarn start to see project, when i want to stop yarn i usually do a control C and it stops the process.. When doing it now, it doesnt close the process and im forced to close the terminal. maybe a bug?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
Bookmarks|ale|10.7.0
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.6
dokd-vscode-preview|bew|0.2.1
htmltagwrap|bra|0.0.7
simple-react-snippets|bur|1.2.2
bracket-pair-colorizer|Coe|1.0.61
vscode-download-file|dar|0.0.1
vs-code-snippet-generator|dku|1.1.0
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|2.5.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
vscode-powertools|ego|0.56.2
LogFileHighlighter|emi|2.7.1
prettier-vscode|esb|3.20.0
vscode-transmit|fab|2.0.3
github-actions|for|0.0.1
dummytextgenerator|gur|1.0.1
live-html-previewer|hdg|0.3.0
rest-client|hum|0.23.1
ftp-simple|hum|0.7.5
vscode-sprint-planner|ipa|0.4.0
vscode-peacock|joh|3.3.1
chat|kar|0.31.0
vscode-gutter-preview|kis|0.25.0
MagicPython|mag|1.1.0
metago|met|2.11.0
vscode-language-babel|mgm|0.0.25
vscode-azureterraform|ms-|0.3.0
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
vsliveshare|ms-|1.0.1510
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
gitdownloadazurerepos|nei|1.0.9
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.2
polacode|pnp|0.3.4
vscode-css-peek|pra|3.0.2
gitlink|qez|0.5.1
LiveServer|rit|5.6.1
code-stats-vscode|riu|1.0.17
terraform-doc-snippets|run|0.4.0
stylelint|shi|0.51.0
vsc-quokka-statusbar|ske|1.2.2
vscode-link|sle|1.0.0
install-time|sof|0.1.5
unique-window-colors|stu|1.0.51
vscode-babel-repl|t-s|0.1.2
python|tht|0.2.3
vsfire|tob|1.4.1
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.4
devops-extension-pack|wal|0.0.14
quokka-vscode|Wal|1.0.276
vscode-import-cost|wix|2.12.0
dom-code-snippets|yon|1.0.2
html-css-class-completion|Zig|1.19.0

(5 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you share your settings file?

**Comment by JasonCruz-Dev** [comment]
the bug fixed itself. idk why it happened. i restarted pc and everything, and it wasnt working, then 1 day randomly it worked.. so idk
