### ISSUE TITLE
Wrong margin in suggest widget status bar details

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#90053]
From #89736 

Seen on Linux with

```
	"editor.fontSize": 14,
	"editor.fontFamily": "Fira Code, Retina",
```

![image](https://user-images.githubusercontent.com/22350/73727802-78de6880-4732-11ea-8f79-82078344d628.png)

**Comment by jrieken** [comment]
This is the problem. The reserved space is static but the actual hight is 80% of the font size... 

https://github.com/microsoft/vscode/blob/6338aed25d6b07324883e1dea49b7b06837147c6/src/vs/editor/contrib/suggest/media/suggestStatusBar.css#L10
