### ISSUE TITLE
WorkspaceEdit.prototype.replace not work

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#90052]
Issue Type: <b>Bug</b>

```ts
const editor = new vscode.WorkspaceEdit();
editor.replace(uri, range, "new text");

// here is the uri:
// $mid:1
// external:"file:///Users/{username}/gpm/github.com/axetroy/deno_dnx/mod.ts"
// path:"/Users/{username}/gpm/github.com/axetroy/deno_dnx/mod.ts"
// scheme:"file"

// here is the range:
// [{"line":7,"character":7},{"line":7,"character":21}]
```

I found this didn't work at all.

Is the method I used incorrect?

VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T13:59:34.701Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 7|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
s4|axe|0.1.1
vscode-auto-schema|axe|0.1.0
vscode-changelog-generator|axe|0.4.1
vscode-comment-autocomplete|axe|0.4.2
vscode-gpm|axe|2.3.6
vscode-http-proxy|axe|0.1.3
vscode-movie|axe|0.5.0
vscode-npm-import-package-version|axe|0.7.5
vscode-open-in-browser|axe|1.0.0
vscode-static-server|axe|0.3.1
github-markdown-preview|bie|0.0.2
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
dart-code|Dar|3.8.0
flutter|Dar|3.8.0
vscode-eslint|dba|2.0.15
vscode-deepscan|Dee|1.9.5
docs-yaml|doc|0.2.4
xml|Dot|2.5.0
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
comment-translate|int|1.4.2
vscode-placeholder-images|Jak|0.1.0
statusbarerror|Joe|0.4.0
vscode-colorize|kam|0.8.15
git-graph|mhu|1.21.0
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.42.1
python|ms-|2020.1.58038
Go|ms-|0.13.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.23.0
indent-rainbow|ode|7.4.0
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
nginx-formatter|ray|0.0.7
vscode-yaml|red|0.6.1
vscode-sort-json|ric|1.18.0
rust|rus|0.7.0
extension-update-reporter|ryu|1.0.3
px-to-rem|sai|1.2.8
bash-beautify|sha|0.1.1
vscode-nginx|sha|0.6.0
trailing-spaces|sha|0.3.1
prettier-vscode|Sim|1.1.11
svg-preview|Sim|2.8.2
code-spell-checker|str|1.7.22
vscodeintellicode|Vis|1.2.4
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|2.7.0
grammarly|znc|0.6.2

(2 theme extensions excluded)

</details>

**Comment by eamodio** [comment]
@axetroy Once you create the edit, you need to apply it: https://code.visualstudio.com/api/references/vscode-api#workspace.applyEdit. Alternatively you can just edit a specific editor using: https://code.visualstudio.com/api/references/vscode-api#TextEditor.edit
