### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by Gwom** [microsoft/vscode#90050]
Sure this must already be requested somewhere, but would be great if the computer is offline, then OmniSharp, NET Core Debugger, Razor Language Server (and anything else), use a cached version you already have on the computer.

I often am offline, and therefore can't really code unless I boot up the program when online before hand. There are steps to work around this but I worry they are quite techy, and may not sort all the different packages that update / download.

Really love the product, this would make it more accessible in my opinion, but know you have a lot on :) Thanks for reading (you guys rock).

**Comment by eamodio** [comment]
It sounds like you should open this issue with the [C# extension](https://github.com/OmniSharp/omnisharp-vscode) as they would need to support what you are asking for, as those services are loaded by that extension.
