### ISSUE TITLE
wordWrap setting by file type

### ISSUE THREAD

**Issue by skmcgowan** [microsoft/vscode#90067]
I'd like the ability to control editor.wordWrap by file type.

Like this in settings.json:

`"[txt]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 80
    },`

By default I have word wrap turned off globally but I would like to turn it on, only in certain file types such as .txt files.

If this behaviour is already intended then it isn't working for me as the settings above are copied from my editor.  I had to turn on 'editor.wordWrap' globally for the settings above to take effect.

My current VS code is:

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
```diff
- "[txt]"
+ "[plaintext]"
```

**Comment by skmcgowan** [comment]
Changing txt to plaintext has solved this.  Many thanks!
