### ISSUE TITLE
The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})

### ISSUE THREAD

**Issue by vitomir-motion** [microsoft/vscode#90069]
- VSCode Version:
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
- VSCode Insiders Version:
Version: 1.42.0-insider (user setup)
Commit: 705f01577dd37d6f17eaa683ab89b0c392fa1a7c
Date: 2020-02-03T14:02:55.075Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
- OS Version:
Microsoft Windows 10 Pro 10.0.17763

Steps to Reproduce:

1. Open VSCode
2. Terminal -> New Terminal
3. `The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})`

Does this issue occur when all extensions are disabled?: Yes

**Comment by timothyblue** [comment]
My **Malwarebytes ransomware protection** was causing this.

I had to add my `Microsoft VS Code` folder to the `Allow List`

**Comment by vitomir-motion** [comment]
> My **Malwarebytes ransomware protection** was causing this same issue.
> 
> I had to add my `Microsoft VS Code` folder to the `Allow List`

It worked, thank you.
