### ISSUE TITLE
High vscode.exe CPU usage when lots of stdout going through terminal (even if terminal not displayed)

### ISSUE THREAD

**Issue by kierenj** [microsoft/vscode#90066]
Issue Type: <b>Bug</b>

I'm running a tool which generates a huge amount of output to stdout, in the VSCode powershell terminal.

Even if the terminal is not visible (VSCode minimised, or a different terminal selected from the dropdown), CPU use stays at a steady 20%.

Note that the tool itself isn't parented to the VSCode process, so it's definitely something related to the output.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
vscode-custom-css|be5|3.0.9
vscode-new-file|dku|4.0.2
githistory|don|0.4.15
xml|Dot|2.5.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.20.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-pull-request-github|Git|0.14.0
gc-excelviewer|Gra|2.1.32
solidity|Jua|0.0.68
docomment|k--|0.1.8
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.0.9
python|ms-|2020.1.58038
remote-wsl|ms-|0.41.9
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
csharp|ms-|1.21.10
powershell|ms-|2020.1.0
cinnamon-snippets|red|0.0.10
java|red|0.55.1
vscode-yaml|red|0.6.1
vscode-hexdump|sle|1.7.2
vscode-helm|tec|0.4.0
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@kierenj is it VS Code, conhost or powershell using most of the CPU?
