### ISSUE TITLE
[Semantic sugar] type aliases are lost using IntelliSense

### ISSUE THREAD

**Issue by Sgt-Nukem** [microsoft/vscode#90061]
When using a type alias in an interface (as semantic sugar) ... **(A)**

... this sugar is lost when using IntelliSense's "blue bulb" click -> "Implement interface XY" function. **(C)**

(See **(B)** for concrete type alias used here)

Appendix: Also, this semantic sugar is lost in IntelliSense hover tooltips -- see **(D)**, where semantic sugar type "UUID" gets de-aliased down to "string" in the tooltip.

![image](https://user-images.githubusercontent.com/4144388/73833382-31c3a680-480a-11ea-9cfc-9d5f8370fe53.png)

**Comment by mjbvz** [comment]
Please provide repo steps with example code (as text)

/needsMoreInfo

**Comment by yume-chan** [comment]
It (at least your figure D) should be caused by a limitation of TypeScript (see Microsoft/TypeScript#34778).

Basically TypeScript will not record you are using a type aliases, only the resolved type.

**Comment by Sgt-Nukem** [comment]
> Please provide repo steps with example code (as text)


**Minimal Repo:**

`export type UrlString = string;
export type UUID = string;

export interface I_IdToUrlMapper {
	mapIdToUrl(id: UUID): UrlString
	mapUrlToId(url: UrlString): UUID
}

export class IdToUrlMapper implements I_IdToUrlMapper {

}`

_Now click the "blue bulb" that appears after clicking "IdToUrlMapper" (underlined in red) and choose "Implement interface 'I_IdToUrlMapper'" --> the resulting code is stripped off of any semantic sugar type aliases:_

`
	mapIdToUrl(id: string): string {
		throw new Error('Method not implemented.');
	}
	mapUrlToId(url: string): string {
		throw new Error('Method not implemented.');
	}
`

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/microsoft/TypeScript/issues/36761 to track upstream
