### ISSUE TITLE
Jupyter notebook autocompletion on variables fails within a cell

### ISSUE THREAD

**Issue by ArnoBen** [microsoft/vscode#90062]
Greetings,

I installed the jupyter notebook extension for vscode and starter a project with it.
It's working fine however the autocompletion is frustrating : it doesn't work for variables within a cell, even though it works between different cells, as shown below.

![Intellisense](https://user-images.githubusercontent.com/14088321/73833486-59b30a00-480a-11ea-9319-06ac80496d6b.gif)

I have seen several other instances of autocompletion failing.
Is it a known issue, an intended behaviour or a misconfiguration on my end ?

**Comment by rebornix** [comment]
Thanks for reporting, since this feature is provided by the Jupyter notebook extension, please file issues with that extension.
