### ISSUE TITLE
Error while writing to User Settings when using Stable build

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90072]
Used the stable built on v1.42 for sanity test and I see following error

![image](https://user-images.githubusercontent.com/10746682/73848650-cccb7900-4828-11ea-9d7e-1287f90dde49.png)

I suspect this is because we removed the search location setting and trying to remove its value as migration

**Comment by sandy081** [comment]
@sbatten Instead of removing the setting, please deprecate it.

**Comment by sandy081** [comment]
BTW I see this error every time I open stable.

**Comment by sbatten** [comment]
To verify:
1. Go to `settings.json` and manually set `search.location` to `panel`.
2. Reload the window

ensure that:
- no error notification appears
- search is in the panel upon reload
- the setting is removed from your `settings.json`
