### ISSUE TITLE
option to move vertical scrollbar to left side --> to put decorations closer to code

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#90079]
Putting the **scrollbar on the left side** would make lots of **useful information† closer to the code**, and thus easier to access peripherally without breaking focus.  

**vs. current behavior:** 
Case 1: Editor window is not split --> editor fills wide screen --> scrollbar is far away from code, at right
Case 2: Editor window is split vertically --> scrollbar decorations are actually closer to the code in the next pane.  

†Examples of info useful to have in the corner of your eye, right by the code:  
"Find" widget matches, current block scope, error decorations

**Comment by alexdima** [comment]
@ultraGentle The only available workaround at this time is to use the minimap and `"editor.minimap.side": "left"`

**Comment by ultraGentle** [comment]
@alexdima Thanks for your response.  I think that can be a good compromise for those who use the minimap.  In my case, I appreciate the space-efficiency and abstraction of the scrollbar decorations.
