### ISSUE TITLE
[Serviceability] Trace server updates by machine id

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90074]
Include machine information (id) as part of the request that is updating data on the server. This will be helpful in diagnosing issues.

**Comment by Tyriar** [comment]
How will this be exposed to the user?

**Comment by sandy081** [comment]
Its not needed to expose it to the user from the product but it will be useful to get the information from the server (through logs or any other means) while diagnosing the issue

**Comment by sandy081** [comment]
Reopening this as @Tyriar requested to reset machine id after turning off.

**Comment by sandy081** [comment]
Added following headers

- `X-Client-Name`
  - `code-insiders` , `code-insiders-web`, `code`, `code-web`
- `X-Client-Version`

- `X-Machine-Session-Id` - Reset when user session is cleared on server
- `X-User-Session-Id` - Session id that received from the server

- `X-Machine-Id`
