### ISSUE TITLE
Differentiate between user shell args and automation shell args

### ISSUE THREAD

**Issue by kzu** [microsoft/vscode#90073]
After the introduction of [differentiated automationShell](https://github.com/microsoft/vscode/issues/78497) settings, it's now possible to have distinct settings for both, which is great. 

One thing left out of [the original commit](https://github.com/microsoft/vscode/commit/37e0b8e229305c09b0cd3753cc28e314b60d93f3) introducing the feature, though, is that the `terminal.integrated.shellArgs.[platform]` seems to be pulled in for both, with no way of distinguishing one from the other.

So, for example, I have the following customization to use a very specific shell and args for my interactive shell:

```
    "terminal.integrated.shell.windows": "${env:USERPROFILE}\\.dotnet\\tools\\pwsh.exe",
    "terminal.integrated.shellArgs.windows": [
        "-noe",
        "-c",
        "\"&{ Import-Module \\\"${Env:ProgramFiles(x86)}\\Microsoft Visual Studio\\2019\\IntPreview\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\\\"; Enter-VsDevShell 0c9b3655; Set-Location \\\"${workspaceFolder}\\\" }\""
    ],
    "terminal.integrated.automationShell.windows": null,
```

but which now causes the automation/tasks shell to not run properly because it's not expecting any of those args to be present. (it's not important what those args do, btw, just that they should not be present in the automation shell, of course ;))

So I think maybe a separate `terminal.integrated.automationShellArgs.[platform]` key should be supported.

Thanks!

**Comment by kzu** [comment]
The only way I found to work around this issue is to specify *per task* an overriden config for the shell options, like:

```
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"options": {
				"shell": {
					"executable": "C:\\WINDOWS\\System32\\cmd.exe",
					"args": [ "/d", "/c" ]
				}
			},
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
```
Moving these options outside the `tasks` property into the `windows` top-level one so it's shared across mulitple tasks doesn't work either:

```
{
	"version": "2.0.0",
	"windows": {
		"options": {
			"shell": {
				"executable": "C:\\WINDOWS\\System32\\cmd.exe",
				"args": [
					"/d",
					"/c"
				]
			},
		},
	},
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

(in this case, the settings.json args are still passed in to the task shell when it runs npm watch :( )

**Comment by Tyriar** [comment]
Shell args are meant to be ignored?

![image](https://user-images.githubusercontent.com/2193314/73862757-dedef480-47f3-11ea-8678-38d703b7511c.png)

@alexr00 is this not working anymore? I've barely touched the terminal recently.

**Comment by kzu** [comment]
Something may have changed rather recently, because I think this was working earlier last week :/. But it's definitely not being ignored in my 1.41.1 version

**Comment by alexr00** [comment]
I still see it get ignored.

**Comment by issenn** [comment]
I have same problem.

**Comment by Tyriar** [comment]
Is the problem here the OP didn't set a shell in the `automationShell setting`? Shouldn't it be this:

```
"terminal.integrated.automationShell.windows": "${env:USERPROFILE}\\.dotnet\\tools\\pwsh.exe",
```

**Comment by issenn** [comment]
if `terminal.integrated.automation.*` does not set, the `terminal.integrated.shellArgs.*` are expected to take effect with `terminal.integrated.shell.*`, but in fact, `terminal.integrated.shellArgs.*` are always ignored with `"terminal.integrated.automation.*": null`

**Comment by alexr00** [comment]
@Tyriar I think you're right. When I set an automation shell the shell args get ignored correctly.
