### ISSUE TITLE
Explorer: decorate files of type "unknown"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90077]
With https://github.com/microsoft/vscode/commit/aaa3c3e26c0a4b5039c917384cabca93d66d5510 the file service will be able to return symbolic links for a folder even if they point to invalid files. Currently in the file explorer we have no way of indicating these. In addition, some files may neither be files nor folders, e.g. block devices or sockets.

I wonder if the explorer could have another set of decoration to indicate that, similar to how we decorate symbolic links. Basically:
* a decoration for a symbolic link that points to a non existing file (stat would be i`sFile: false, isDirectory: false, isSymbolicLink: true`)
* a decoration for any non-file, non-folder (stat would be `isFile: false, isDirectory: false, isSymbolicLink: false`)

![Screenshot 2020-02-05 at 16 12 10](https://user-images.githubusercontent.com/900690/73854464-e2de3700-4832-11ea-82bf-8d4222c66007.png)

**Comment by isidorn** [comment]
I use a question mark `?` and the following hover message "Unknown resource"
If you have a better idea please let me know.
Also I did not try it out in action, so please try it out and let me know if it behaves well for you.
Also I do not distuingsh between the symbolic link and not symbolic link unwkown case. You could argue that the symbolic link should also have the arrow, if you are passionate about that let me know and I can change.

**Comment by bpasero** [comment]
Ah nice, yeah I think we can try it out.

**Comment by bpasero** [comment]
Looks like symbolic links, even when they point to non existing files, are very functional. You can open them and type to create the target ad-hoc. As such I will push a slight change to still render dangling symbolic links as usual.

**Comment by isidorn** [comment]
Makes sense. Thanks for the tweaks!
