### ISSUE TITLE
Create sync test suite that verifies the right headers are being sent in various situations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90076]
I suggest creating unit tests that swap out the request service in order to simulate the server. This is very important as shipping a version where the requests are broken has the potential to DDoS the server which will cause problems that we can't really fix without waiting it out for clients to update, and there will always be a long tail of clients that don't get updated. Some cases we need to test:

- A fresh sync sends no `if-none-match`
- A fresh sync where the server has data will send no `if-none-match`, a follow up will correctly set `if-none-match`
- Writing a sync and then syncing will set the expected `if-none-match`
- The cases we've had problems with already:
  - Syncing different versions where no changes exist https://github.com/microsoft/vscode/issues/89817
  - https://github.com/microsoft/vscode/issues/89623
  - Verify correct number of requests are being made https://github.com/microsoft/vscode/issues/89626, when the new API is adopted this should go into details like fetching all latest, then fetching each resource individually and verifying the requests are correct
  - Correct handling/backing off when errors occur https://github.com/microsoft/vscode/issues/88317, https://github.com/microsoft/vscode/issues/85211
  - Verify correct data is being sent https://github.com/microsoft/vscode/issues/85052

Consider starting on the framework for this as a minimum in Feb, we need a comprehensive test suite by the time we're out of preview.

**Comment by sandy081** [comment]
Added tests to cover all sync scenarios.
