### ISSUE TITLE
Panel: sometimes "Terminal" appears as second item

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90078]
Do not really have steps, but I often see my "Terminal" be the second element in the panel list, even though I always have it last.

![image](https://user-images.githubusercontent.com/900690/73854713-381a4880-4833-11ea-8c3d-8387ae6504b7.png)

I think @alexr00 also noticed this once.

**Comment by alexr00** [comment]
I sometimes see it be the second to last, between Debug Console and Problems.

**Comment by sandy081** [comment]
Can't repro it but will keep an eye on it if it happens

**Comment by bpasero** [comment]
I have not seen this lately.
