### ISSUE TITLE
Normalize open*settings commands args

### ISSUE THREAD

**Issue by mtirionMSFT** [microsoft/vscode#90086]
- VSCode Version: 1.41.1
- OS Version: Win10 1909

Steps to Reproduce:

In an extension:
1. commands.executeCommand('workbench.action.openWorkspaceSettings', 'telemetry');
2. Workspace settings open, but without a search filter

No, as there is nothing to run that code

**Comment by roblourens** [comment]
Why do you need this? You can use `workbench.action.openSettings` but I don't really want to provide a ton of commands to control all the different options in the settings UI.

**Comment by mtirionMSFT** [comment]
There is a difference between User settings or Workspace settings, there is different UI and comparable methods in the API to reach them. The openWorkspaceSettings has the same signature as openSettings, but they don’t behave the same way. That’s why I think this needs to be resolved to be consistent.

Martin

Martin Tirion  |  senior software engineer |  CSE | Agile Response Team | Spatial Computing | Microsoft
Tel +31 (6) 1250 6153  |  Twitter @mtirion  |  Blog mtirion.nl<http://mtirion.nl/>

**Comment by rainfore** [comment]
Same issue. I just want to open the workspace settings and filter by my extension name.

**Comment by BeFunes** [comment]
Same here!

**Comment by yanmofeixi** [comment]
+1

**Comment by frenya** [comment]
+1

**Comment by xspenc3r** [comment]
This is exactly what I need to programmatically open the workspace settings for my extension, allowing users to easily make changes.
For anyone who needs this feature, execute openSettings with your search, then execute openWorkspaceSettings. It will switch the current settings window over to workspace settings while keeping your search string.

Example
`vscode.commands.executeCommand('workbench.action.openSettings', 'telemetry' );
vscode.commands.executeCommand('workbench.action.openWorkspaceSettings');`

**Comment by johnpaliotta** [comment]
Thanks @SpenceV1  and @JensWallgren for documenting this workaround
I had this same need btw.
