### ISSUE TITLE
Tilde character ~ is not displayed in terminal using Belgian keyboard layout

### ISSUE THREAD

**Issue by pierredewilde** [Microsoft/vscode#9008]
- VSCode Version: 1.3.0
- OS Version: Mac OS X El Capitan 10.11.5 with Belgian keyboard

Steps to Reproduce:
1. Open Integrated Terminal (`View > Integrated Terminal`)
2. Type `cd ~` + Enter

The tilde character (~) is not displayed.
`$ cd`

**Comment by Tyriar** [comment]
- Does it show up if you hit `~` multiple times?
- Does it actually input a `~` or skip the character (does the cursor move right when you hit `~`, what does tab completion do when you type `cd ~/`?

**Comment by pierredewilde** [comment]
- The tilde does not appear even if hit multiple times.
- The cursor does not move. `cd ~/` is inputed as `cd /`

Note that if I copy `cd ~/` from the code editor and paste it in the integrated terminal, it works as expected.

**Comment by nih0** [comment]
I have the same issue with a german keyboard on macOS(`OS X 10.11.1`).

- `OS X 10.11.1`
- `Version 1.3.0`

**Comment by Tyriar** [comment]
Thanks, I think this is to do with lack of AltGr support (#7061). Please confirm :smiley:

**Comment by pierredewilde** [comment]
I am using a MacBookAir with a Belgian keyboard layout:
https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/belgian_keyboard.png

There is no AltGr key on Apple keyboard layout.

**Comment by Tyriar** [comment]
@pierredewilde if possible, could you setup https://github.com/sourcelair/xterm.js and check to see if this reproduces in the demo? This should get it up and running easily:

```bash
git clone https://github.com/sourcelair/xterm.js.git
cd xterm.js
npm install
npm start # I think this needs node <= 4
# open browser at http://0.0.0.0:3000
```

**Comment by pierredewilde** [comment]
Yep, same issue after installing and running `xterm.js`: no tilde appears.

BRW, you don't need `node <= 4`. Tested with `node 6.3.0`.

**Comment by Tyriar** [comment]
This issue was moved to sourcelair/xterm.js#174

**Comment by Tyriar** [comment]
@pierredewilde thanks, moved it upstream :)

**Comment by Tyriar** [comment]
Tracking this in https://github.com/sourcelair/xterm.js/issues/174
