### ISSUE TITLE
Dart extensions are available for wrong data type in Visual Studio Code

### ISSUE THREAD

**Issue by bambinoua** [microsoft/vscode#90089]
Issue Type: <b>Bug</b>

I have two extensions for differente types `String` and `DateTime`. Why extensions for `String` and `DateTime` (as mentioned above) are visible in suggestions for `int` (and any other) type?

Link on stackoverflow.com with image
https://stackoverflow.com/q/60060242/1798328

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by yume-chan** [comment]
Hi @bambinoua 

I don't think Visual Studio Code contains native support for Dart. If you are using the [Dart](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code) extension, please report issues to its corresponding  [GitHub repository](https://github.com/Dart-Code/Dart-Code/issues).
