### ISSUE TITLE
Usage of @optional decorator is dangerous

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90098]
Currently almost all uses of `@optional` do not use `| undefined` which could lead to runtime errors. I'm using a workaround to keep TS safety when I use it due to https://github.com/microsoft/vscode/issues/81988, but it relies on someone not accidentally changing that code:

https://github.com/microsoft/vscode/blob/3a35fae761e2d4fc8ef7c23871913cf369d35226/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L103-L106

For example, making this line `| undefined`:

https://github.com/microsoft/vscode/blob/3a35fae761e2d4fc8ef7c23871913cf369d35226/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L108

Results in the following errors:

![image](https://user-images.githubusercontent.com/2193314/73876382-c24eb680-480b-11ea-9567-b75afeaccfbc.png)

**Comment by jrieken** [comment]
Yeah, feel free to work on an improvement here. Generally, usage of `@optional` should be kept to an absolutions minimum. Even an optional dependency to `IElectronService` from /browser/ smells like a layering issue.

**Comment by Tyriar** [comment]
Removed just for terminal. To verify make sure the following works on Windows:

1. Open a regular Windows file in the workspace (eg. `C:\...\README.md`)
2. Open a wsl terminal
3. Run the active file, it should run the WSL path (eg. `/mnt/c/.../README.md`)

**Comment by aeschli** [comment]
Verified
