### ISSUE TITLE
Debug Console hangs after many lines are printed out

### ISSUE THREAD

**Issue by rogeryen** [microsoft/vscode#90099]
- VSCode Version: 1.41.1
- OS Version: MacOS 10.15.2

Steps to Reproduce:

1. Run a simple python (not sure if language matters) script in debug console
```
import time

i = 0
while True:
    print(i)
    i += 1
    time.sleep(0.001)
```
I have noticed that it doesn't matter whether I have the sleep or not, for me it always stops at 5136.

Is this by design?

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/81464
You can find all the details in that issue, thanks!
