### ISSUE TITLE
Intellisense is much more narrow than before when the description is visible

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90093]
Create the following keybinding and open intellisense in the command:

```
{ "key": "ctrl+f1", "command": "terminalrename" }
```

Lots of wasted space and I can no longer tell which one is `rename` and which is `renameWithArgs`:

![image](https://user-images.githubusercontent.com/2193314/73872981-94ff0a00-4805-11ea-9a8c-d7cb80b09ed8.png)

In stable:

![image](https://user-images.githubusercontent.com/2193314/73873096-ced01080-4805-11ea-8194-c7f662feeca2.png)

Version: 1.42.0-insider (user setup)
Commit: 536757fcc0308b444cbe9ce04f1f013903641ae3
Date: 2020-02-05T16:51:41.553Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by octref** [comment]
Verifier: Verify that completing `workbench.action.terminal.rename` use most of the spaces, like in Stable. There's 18px to the right which is reserved for the scrollbar that we don't use.

![image](https://user-images.githubusercontent.com/4033249/73874934-3fc4f780-4809-11ea-9f37-86b7b3a6d8a2.png)
