### ISSUE TITLE
Autocomplete makes app unusable

### ISSUE THREAD

**Issue by imagtek** [microsoft/vscode#90097]
Autocomplete in Visual Studio Code is visually distracting and makes app unusable.
There appears to be no way to turn this 'feature' off.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you talking about suggestions/IntelliSense content or the fact that it might be showed automatically while you are type?

If second you can configure `editor.quickSuggestions` not to "automatically show up while typing."
```json
"editor.quickSuggestions": {
    "other": false,
    "comments": false,
    "strings": false
}
```
also you can use `"editor.quickSuggestionsDelay": 10000` to delay suggestions for 10s or whatever delay you like.

If not about automatic suggestions - provide more details on what's wrong.

**Comment by imagtek** [comment]
This fixed my problem!

Thank you very much for your prompt response.
I can type very rapidly and the constant flickering of selection menus 
was giving me a headache.

Thank you again.

John Powers

**Comment by IllusionMH** [comment]
/question
Will close this issue because your problem should be solved now.
