### ISSUE TITLE
Builtin Git extension gives annoying popup that reappears on restart despite dismissal

### ISSUE THREAD

**Issue by sohomdatta1** [microsoft/vscode#90092]
- VSCode Version: 1.14.1
- OS Version: Ubuntu 18.04.4 LTS x86_64

Steps to Reproduce:

* Open/edit any file that is in your home, Downloads, Desktop, Documents (or any other non-git enabled heavily used directory)
* Pop-up with the following text comes up with a "Don't show again" button
 * >The git repository at '/home/sohom' has too many active changes, only a subset of Git features will be enabled.
* Dismiss the pop-up using the "Don't Show Again" button
* Restart visual studio
* Pop-up shows up again 

Does this issue occur when all extensions are disabled?: Yeah

**Comment by joaomoreno** [comment]
> or any other non-git enabled heavily used directory

It appears you have initialized a git repo where you shouldn't have. Run `git rev-parse --show-toplevel` from the Desktop to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by sohomdatta1** [comment]
Okay, it appears I have free floating `.git` in my home folder for some reason. Sorry for bothering you guys :)
