### ISSUE TITLE
Cannot untoggle intellisense details when no details exist for entry

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90094]
Related: https://github.com/microsoft/vscode/issues/90093

Repro:

- Open intellisense on `{ "key": "ctrl+f1", "command": "terminalrename" }`
- Press down
- Open details (ctrl+space)
- Press up
- Close details (ctrl+space), it doesn't work.

![image](https://user-images.githubusercontent.com/2193314/73873189-f921ce00-4805-11ea-87a0-e732622c9d29.png)

Version: 1.42.0-insider (user setup)
Commit: 536757f
Date: 2020-02-05T16:51:41.553Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by octref** [comment]
Just linking this up to #88749.

**Comment by jrieken** [comment]
Pushing a change that allows you untoggle details when on an item without details - but not the other way around

![Oct-02-2020 14-23-55](https://user-images.githubusercontent.com/1794099/94922688-f6719880-04ba-11eb-9f0e-1139c1913e11.gif)
