### ISSUE TITLE
No intellisense/autocomplete for class in a different JS file

### ISSUE THREAD

**Issue by steveharoz** [Microsoft/vscode#9009]
- VSCode Version: 1.3.0
- OS Version: Windows 8.1

There are 3 files: index.html, library.js, main.js

Both js files are included in index.html
```
<script src="js/library.js"></script>
<script src="js/main.js"></script>
```

library.js includes some classes and functions:
```
class Thing{
    constructor() { this.value = 5; }
    some_method() {}
}
```

Intellisense in main.js doesn't know about the contents of library.js:
![image](https://cloud.githubusercontent.com/assets/2257540/16709613/e720376c-45db-11e6-8287-54d618a4b2b3.png)

Same for methods and properties of the object:
![image](https://cloud.githubusercontent.com/assets/2257540/16709631/2959fb0e-45dc-11e6-913a-141355a77e55.png)

When I move the class into the same js file, it works fine.

**Comment by dbaeumer** [comment]
If you want to have main.js and library.js in the same JS space (e.g. project) you need to have a jsconfig.json in your folder. See https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson for details.
