### ISSUE TITLE
Deploy Source to org failure

### ISSUE THREAD

**Issue by Sjohns10** [microsoft/vscode#90102]
Issue Type: <b>Performance Issue</b>

I have tried to reinstall VS Code and uninstall the Salesforce CLI Integration and reinstalled everything and started new project.  Every time that I try to send any thing to my authorized org it wouldn't let me.  It get the error

Starting SFDX: Deploy Source to Org
09:19:57.709 sfdx force:source:deploy --sourcepath c:\Users\SJohns10\Desktop\VSC\Meredith Salesforce\NationalMedia_Salesforce\force-app\main\default\objects\Account\fields\Contracted_Agency__c.field-meta.xml --json --loglevel fatal
09:20:01.399 sfdx force:source:deploy --sourcepath c:\Users\SJohns10\Desktop\VSC\Meredith Salesforce\NationalMedia_Salesforce\force-app\main\default\objects\Account\fields\Contracted_Agency__c.field-meta.xml --json --loglevel fatal ended with exit code 1

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (20.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    86	  3876	code main
    0	   253	  8000	   window (AccountId.field-meta.xml - Meredith Salesforce - Visual Studio Code)
    0	    16	  9612	     watcherService 
    0	    14	 17828	       console-window-host (Windows internal process)
   21	   139	 12072	     extensionHost
    9	    69	  4380	       electron_node server.js 
    0	    40	 20344	     searchService
    2	   151	 10600	   gpu-process
    1	    71	 14148	   window (Issue Reporter)
    0	    20	 19044	   electron-crash-reporter
   38	    93	 21192	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (AccountId.field-meta.xml - Meredith Salesforce - Visual Studio Code)
|    Folder (Meredith Salesforce): 3980 files
|      File types: xml(2580) cls(320) js(135) svn-base(112) page(75) cmp(48)
|                  css(37) html(36) trigger(29) ts(28)
|      Conf files: launch.json(1) settings.json(1) jsconfig.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.15
salesforcedx-vscode|sal|47.17.1
salesforcedx-vscode-apex|sal|47.17.1
salesforcedx-vscode-apex-debugger|sal|47.17.1
salesforcedx-vscode-apex-replay-debugger|sal|47.17.1
salesforcedx-vscode-core|sal|47.17.1
salesforcedx-vscode-lightning|sal|47.17.1
salesforcedx-vscode-lwc|sal|47.17.1
salesforcedx-vscode-visualforce|sal|47.17.1

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

Please report this issue to in Saleforce extension repo https://github.com/forcedotcom/salesforcedx-vscode/issues
