### ISSUE TITLE
RegExp substring replace does not work for new Global Search&Replace

### ISSUE THREAD

**Issue by nsgundy** [Microsoft/vscode#9010]
- VSCode Version: 1.3.0
- OS Version: Win10

Steps to Reproduce:
File contents:
```ts
let fs = require('fs');
```
1. Start Global Search&Replace `CTRL+SHIFT+H`
2. For the search term use `let\s+(\w+)\s*=\s*require\s*\(\s*['"]([\w\.\-/]+)\s*['"]\s*\)\s*;`
3. For the replace term use `import * as $1 from '$2';`

#### Issue:
When replacing, the file looks like this:
```ts
import * as $1 from '$2';
```
Expected
```ts
import * as fs from 'fs';
```

_Note_: This works using Local Search&Replace (`CTRL+H`).

**Comment by sandy081** [comment]
Replace text does not yet support taking groups arguments from search text. But I agree this is a parity issue with local find. Will try to get this soon. Thanks

**Comment by sandy081** [comment]
FYI @egamma Pushed this and will be available in tomorrow's insiders build.

**Comment by xekri** [comment]
I hope the replace term '&$' can be supported, which is just the word it matches. I know I can do this by grouping the search word with brackets(like '([^\s])', and make the replace term like '$1', but it's more  troublesome. Thanks.
