### ISSUE TITLE
Provide a Rename option when right clicking an open file's tab

### ISSUE THREAD

**Issue by awarmfastbear** [microsoft/vscode#90104]
A previous issue was created but was closed, I completely disagree with the idea that we need to request this feature by making an extension for it popular - https://github.com/microsoft/vscode/issues/21919 

It would be nice if we could get a Rename option when right clicking an open file's tab in main view. I realize that there is a Rename option in the Explorer view, but that view isn't always open and those coming from other text editors used to this functionality would appreciate this. An extension for this seems excessive as described below. Atom and Webstorm, two of the most popular editors available provide this by default. 

**Describe the solution you'd like**
When right clicking an open tab at the top of the window of a file, provide a Rename option. Otherwise provide this as an optional setting that can be enabled for users that may not want any additional entries in their context menu.

**Describe alternatives you've considered**
An alternative would be developing a small extension for this but I think that's an unreasonable ask due to concerns users or companies may have around security. For instance, certain users of Wordpress rely too heavily on 3rd party plugins, these inevitably end up having security holes in them. But they are used to finding plugins for small quality of life fixes. Having users look for 3rd party extensions for small enhancements like this will create a bad habit of creating too much trust. As Visual Studio Code's popularity grows, extensions will eventually be targeted by bad actors as an attack vector. Every user installing a 3rd extension should not trust it by default, certain untrusted extensions can and will likely end up allow keylogging and executing rogue code even. Until you read and understood the source code of a 3rd party extension, it should be untrusted unless its from a first party like Microsoft.

Users should be instead voting up valid quality of life enhancements to show demand, we should not tell them to blindly go find extensions that will fix all their problems.

**Additional context**

Thank you all for developing Visual Studio Code <3

**Comment by Pranav2612000** [comment]
@awarmfastbear I agree with you and such a feature is needed. I recently started using Visual Studio Code and have clicked on the tab multiple times looking for a rename option. This happens instinctively, and many other users would agree with me too. If it is decided to incorporate this feature, I am interested to help.
And again, Thank you for developing this amazing software.
