### ISSUE TITLE
Etag is not read from the response in Web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90112]
Sync is throwing following error in Web

<img width="830" alt="image" src="https://user-images.githubusercontent.com/10746682/73897152-6b85c300-4885-11ea-8c48-3428655904f8.png">

**Comment by sandy081** [comment]
Currently this error is silent. Added a change to turn off sync when this error happens.

@bpasero FYI Sync is broken on web currently.

**Comment by Tyriar** [comment]
I don't see this on selfhost web with either local or test server? I'm also doubting this would be a problem on the server's end, there's nothing there that treats web different to desktop.

**Comment by sandy081** [comment]
@Tyriar can you please check in your network tab if the requests are not failing because of CORS?

**Comment by sandy081** [comment]
@Tyriar I can still repro it when self hosting on web. I am seeing server returning following response in the network tab

<img width="380" alt="image" src="https://user-images.githubusercontent.com/10746682/73972998-0df38400-4922-11ea-9bc3-cb1e91ffa23a.png">

But the xhr request handler is not including all response headers in the result as the CORS server is not saying to show all headers. Server has to add the necessary response headers to `Access-Control-Expose-Headers` response header so that the client can read them.

**Comment by Tyriar** [comment]
This should be fixed now.
