### ISSUE TITLE
Blank VS Code window when rebuilding container after changes to Dockerfile

### ISSUE THREAD

**Issue by ob** [microsoft/vscode#90113]
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

- VSCode Version: 1.41.1
- Local OS Version: macOS Catalina
- Remote OS Version: RedHat 7
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Modify `.devcontainer/Dockerfile`
2. Click "Reopen in Container"
3. Click on "Rebuild"

While the container is being built, the VS Code window is completely blank. After the container is rebuilt it goes back to normal but I can't find the logs of the `docker build` command anywhere.

**Comment by eamodio** [comment]
This looks like possibly another case of https://github.com/microsoft/vscode/issues/89035

**Comment by ob** [comment]
I tried VS Code insiders and it is fixed there.
