### ISSUE TITLE
No syntax highlighting inside CDATA

### ISSUE THREAD

**Issue by OmgImAlexis** [microsoft/vscode#90115]
- VSCode Version: 1.41.1
- OS Version: macOS 10.15.2

Steps to Reproduce:
1. Create file.xml with this contents.

```xml
<FILE Name="/etc/rc.d/rc.unraid-api" Mode="0755">
<INLINE>
<![CDATA[
#!/bin/sh
# unraid-api-handler
downloads=(graphql-api plugins)
node_apps=(graphql-api)
]]>
</INLINE>
</FILE>
```

I would have expected to see the bash code to be syntax highlighted.
![Screen Shot 2020-02-06 at 3 04 41 pm](https://user-images.githubusercontent.com/6525926/73906203-05835500-48f2-11ea-80f1-9a3b8da609b9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
@OmgImAlexis how is the XML language processor going to decide what language to treat the CDATA as?

**Comment by OmgImAlexis** [comment]
I was hoping it’d use the shabang line if present. 

Otherwise is there not a way for vs code to detect the specific language?

**Comment by alexr00** [comment]
To keep the XML language grammar light, it doesn't look for shebang lines. It's possible there is another XML grammar extension that does look for shebang lines and provides highlighting for them. If there isn't an existing extension, then this would make a very nice extension.
