### ISSUE TITLE
Decoration for symbolic link not showing up in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90119]
Steps to Reproduce:

1. create a folder with a couple of files and one symbolic link (`ln -s <existing file> <symlink name>`)
2. open this folder in VSCode
3. notice how the symlink correctly gets the arrow decoration for sym link
4. click on the link to open it
5. reload window

=> 🐛 the decoration does not appear anymore. it seems that as soon as an editor is opened matching the symlink, the decoration is not resolved?

Somehow does not reproduce in current insiders, so I wonder what changed here and if it could possibly be my change from yesterday, but I do not understand the correlation.

**Comment by isidorn** [comment]
If it does not reproduce in current insiders I will look at it as fixed :)

For more details we could put a breakpoint [here](https://github.com/microsoft/vscode/blob/9a839aa9f8102c8db4134fe768793c6f137bade9/src/vs/workbench/contrib/files/browser/views/explorerDecorationsProvider.ts#L18)
And check what is the state that the `ExplorerItem` is in when we are asked to provide decorations.

**Comment by bpasero** [comment]
@isidorn maybe I was not clear, this fails running out of sources and our insiders is not up to date.

**Comment by isidorn** [comment]
Looked into this and it is a timing issue.
If you open the file in an editor it will try to get the decoration provided before the Explorer has a chance to resolve it (because the tab area is rendered before the explorer area).
Thinking about a solution...
