### ISSUE TITLE
[yaml] Syntax highlighting bug - escaped double quotes

### ISSUE THREAD

**Issue by ZombieHippie** [Microsoft/vscode#9011]
- VSCode Version: June 2016 (version 1.3)
- OS Version: OS X 10.11.5 (15F34)
- Kernel Version: Darwin 15.5.0

![image](https://cloud.githubusercontent.com/assets/2925395/16710036/685bb4d6-45e7-11e6-9557-c29c967442c3.png)

Steps to Reproduce:

\1. Type in:
```yaml
commands:
  - "echo '{ \"allow_root\": true }' > .bowerrc"
  # hello
  - ls
```
\2. Set Language Mode to YAML

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#15

**Comment by ZombieHippie** [comment]
Thank you
