### ISSUE TITLE
Breakpoints keep extension from activating

### ISSUE THREAD

**Issue by slanden** [microsoft/vscode#90118]
Using breakpoints when debugging a custom extension prevents the extension from being activated in the debug session.

- VSCode Version: 1.42.0-insider | 1.41.1
- OS Version: Linux x64 5.3.0-28-generic (Ubuntu 18.04.3 LTS)

Steps to Reproduce:

1. Create a new VS Code extension project using `npm init yo code`
2. Choose "JavaScript extension", then "no type checks", then click through every other prompt to use defaults
3. Add `"*"` to `activationEvents` property of package.json for automatic activation (though the behavior is the same for any activation event)
4. Start debugging (default shortcut is F5)
5. Notice the "Congratulations..." message in debug console
6. Place a breakpoint somewhere in extension's `activate()` function, I placed it on the `let disposable = vscode.commands.registerCommand(`...
7. Restart the debugger and notice it's no longer showing the "Congratulations..." message, nor is it hitting the breakpoint

Does this issue occur when all extensions are disabled?: Yes

I also didn't have this problem yesterday.

### UPDATE
Some minutes later, after blankly looking at the screen about to rain `console.log` everywhere, the breakpoint hit. I then restarted the debug session multiple times to verify it will continue to hit, and it does (much faster than minutes).

BUT, that "Congratulations..." message is still not printing to the debug console so I'm not confident it's actually working.

### UPDATE 2
Being a new day, I opened the project again and thought I was back at the original problem. But, the breakpoint hit after some time. Maybe it's just really slow on the first run of VS Code after rebooting the computer?

I also noticed that although the "Congratulations..." message isn't logged after that code is hit, if I press "continue" after the last breakpoint has been hit, the `console.log` statement is logged.

**Comment by isidorn** [comment]
I believe this is due to the `stopOnEntry` that the node debug extension does in order to insert breakpoints. Forwarding to @weinand and @roblourens to investigate
fyi @connor4312

**Comment by weinand** [comment]
@slanden I cannot reproduce the problem because there is something missing from your steps.

After pressing "F5" there cannot be a "Congratulations..." message on the debug console because the newly created extension does not activate automatically.

The extension will activate only if you run the "Hello World" command vi F1 and the type "hello".

After setting breakpoints on the "console.log" statements in the "activate" function, you will hit them when running the "Hello World" command. This worked fine for me even If I restarted the debug session with the "Restart" button in the debug action bar.

**Comment by slanden** [comment]
@weinand You're right, I forgot to add "activate extension" to the steps but I added it now, as step 3. Please note, how the extension is activated doesn't matter. The behavior is the same.

I added a second update to the post, but I'm confused about the problem now. It seems maybe the first part is it's just really slow to hit a breakpoint on the first run of VS Code after the computer is rebooted, and then normal speed on subsequent debug runs.

Secondly, this is probably a stupid question but is `console.log` statements in debug mode prevented from logging until all breakpoints have been hit first? I know normal lines of code are run but logging seems to be different.

**Comment by slanden** [comment]
I tried again by following the reproduction steps. The extension activated and hit the breakpoint without a problem. The original repo that had this issue works as well.

Closing as the issue seems to be gone.
