### ISSUE TITLE
Show caps lock on/off as an indication in editor window

### ISSUE THREAD

**Issue by gs-rbarman** [microsoft/vscode#90120]
When writing code, a lot of the time we are declaring and writing constant variables. We are having to switch caps lock state. It would be great to know in the editor whether caps lock is on or off without having to either look at the keyboard or typing and deleting in case we start off typing with the wrong state of caps lock

**Comment by ATheCoder** [comment]
Isn't that the keyboard's job?

**Comment by gs-rbarman** [comment]
I agree about the keyboard's job part. This suggestion was only made in the interest of increased usability , just like how a login form does indicates caps lock on for a password field
