### ISSUE TITLE
Add toggle for "ignore trim whitespace" while diffing

### ISSUE THREAD

**Issue by Alexendoo** [Microsoft/vscode#9012]
- VSCode Version: 1.3.0
- OS Version: Windows 8.1

Steps to Reproduce:
1. Modify some whitespace in a file (can include converting between tabs/spaces)
2. Make a non-whitespace change elsewhere in the same file
3. View the in-editor diff

Without other modifications:

![Without other modifications](https://cloud.githubusercontent.com/assets/1830331/16710046/f799417c-4619-11e6-85bb-433683ffd454.png)

With other modifications:

![With other modifications](https://cloud.githubusercontent.com/assets/1830331/16710048/006933b6-461a-11e6-96fb-5309cc1cf67d.png)

**Comment by alexandrudima** [comment]
That is correct, we do the following:
* run a diff with trim whitespace ignored
* if there is no diff, then we run a diff again with trim whitespace not ignored

**Comment by theoy** [comment]
Would it be possible to have an option to ignore all whitespace diffs?

Sometimes I want to be able to compare semantic changes (e.g. typically non-whitespace diffs) vs. diffs that are only with regards to formatting (which may be in between tokens, not just trim beginning/end of line).

**Comment by sahas-** [comment]
+1 pls

**Comment by danielo515** [comment]
It would be nice if someone on the vscode team says if this is accepted and is planned to be implemented, even if they don't know when

**Comment by alexandrudima** [comment]
Here is the button:
![image](https://user-images.githubusercontent.com/5047891/35564143-764d7398-05b9-11e8-9d16-cb5e2c5df243.png)

**Comment by sandy081** [comment]
@alexandrudima Not sure if it is expected, why does the additional space in the second line in the following diff is not highlighted

![image](https://user-images.githubusercontent.com/10746682/35578635-f323c022-05e4-11e8-99b6-4bcb44498e46.png)

**Comment by alexandrudima** [comment]
@sandy081 Extracted to https://github.com/Microsoft/vscode/issues/42751
