### ISSUE TITLE
save file error

### ISSUE THREAD

**Issue by tom-vision** [microsoft/vscode#90126]
Issue Type: <b>Bug</b>

When saving the file, the prompt "Run [File] save participant: Quick fix" resulted in the failure to save the file. need to restart vscode to resume normal operation.

VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T14:02:55.075Z)
OS version: Windows_NT x64 10.0.19555

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.10.0
eggjs|ati|0.3.1
color-info|bie|0.5.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.15
vscode-faker|dee|1.3.0
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
HTMLHint|mka|0.6.0
vscode-language-pack-zh-hans|MS-|1.42.2
remote-wsl|ms-|0.42.3
vetur|oct|0.23.0
minapp-vscode|qiu|2.2.2
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
var-translation|sve|0.7.2
vscode-icons|vsc|9.7.0
quokka-vscode|Wal|1.0.277

(1 theme extensions excluded)

</details>

**Comment by eamodio** [comment]
Is this reproducible with all extensions disabled? My guess is an extension is causing this.

**Comment by happyTonakai** [comment]
Features like Format on Save and Fix on Save will cause it.

**Comment by tom-vision** [comment]
The problem was solved when I turned off the vetur extension

**Comment by tom-vision** [comment]
> Features like Format on Save and Fix on Save will cause it.

The problem was solved when I turned off the vetur extension

**Comment by happyTonakai** [comment]
> > Features like Format on Save and Fix on Save will cause it.
> 
> The problem was solved when I turned off the vetur extension

I also encountered this problem in matlab-formatter when saving matlab files, which worked well yesterday.

This is probably caused by the new update of vscode.

<img width="715" alt="批注 2020-02-07 170010" src="https://user-images.githubusercontent.com/21305646/74016485-764b6f80-49cd-11ea-98ae-821d8d62dea4.png">

**Comment by tom-vision** [comment]
> > > Features like Format on Save and Fix on Save will cause it.
> > 
> > 
> > The problem was solved when I turned off the vetur extension
> 
> I also encountered this problem in matlab-formatter when saving matlab files, which worked well yesterday.
> 
> This is probably caused by the new update of vscode.
> 
> <img alt="批注 2020-02-07 170010" width="715" src="https://user-images.githubusercontent.com/21305646/74016485-764b6f80-49cd-11ea-98ae-821d8d62dea4.png">

I think so too, no problem before. Now i have replaced vetur with eno snippets

**Comment by CatoMinor** [comment]
The issue may relate to an extension, but there was no problem prior to the latest release of vscode.

**Comment by jwbaldwin** [comment]
Also having this problem and didn't have it before latest vscode update.

**Comment by LolliDepp** [comment]
Yeah would be great if maintainers stopped marking all of these as "caused by extensions" since it seems like every single extension is causing it

Also happens with no extensions and large TS codebase.

**Comment by b00f** [comment]
> Yeah would be great if maintainers stopped marking all of these as "caused by extensions" since it seems like every single extension is causing it.

That's true. I don't know why they close this issue when this is really a headache for developers.
