### ISSUE TITLE
Quick Open should be able to find the file item if the path entered is a full existing relative path to the project root, even a "search.exclude" settings excluded the path

### ISSUE THREAD

**Issue by johnnytemp** [microsoft/vscode#90127]
Corresponding to this ticket: #15604
and this comment: https://github.com/microsoft/vscode/issues/15604#issuecomment-582788918

> 
> Or furthermore to a new command, may the default `Quick Open` action able to show the file item if the path entered is a full existing relative path to the project root?
> 
> I feel it quite strange & stupid, to discover that "Quick Open" cannot find the file I want, even I gave the full relative path, which is the almost-complete hint. :-/ (Always needing to copy from or make an absolute path is tedious)

### Reasoning

Use case example: For some PHP exception tracing from apache server's log, I need to open some files locally in the "vendor" folder (excluded from `search.exclude` setting).

"search.exclude" is majorly for Ctrl-Shift-F (Text search) and only semi for Ctrl-P (Quick Open). Although not showing the excluded files normally in Ctrl-P, it is good to make Quick Open easier to open those files with a full relative path hint. (to be more user friendly)

Remark: Fire this request because it can be considered separately from #15604. Although either will help.

**Comment by roblourens** [comment]
We actually had this feature before, and we removed it due to complicating things and low use. You can actually do this with an absolute path though, if that helps.

**Comment by johnnytemp** [comment]
I see. BTW, the server's log absolute path for the uploaded file is different with local path, so absolute path doesn't help in this case.

However, closing this is acceptable, as this may complicate VSCode's code... XD (but may be more user friendly?). Thank you.

It still have a workaround to do a command "code relative-path", although more typing. :)
