### ISSUE TITLE
angular *ngFor index problem

### ISSUE THREAD

**Issue by DavidOs55** [microsoft/vscode#90124]
Issue Type: <b>Bug</b>

I installed th last version of vs code : 1.41.1 and when I use *ngFor in a component template I get strange template behaviour :  
1. A red close tag of the div: '>'  
2. A strange closing elements colors at the bottom of the html (light blue).
3. When I try to make some elements in remark , they don't get in remark.

All this code worked perefect before I did the upgrate of the vs code. Also when I remove  the index the problem is gone , but I need the index. 
This is the line of code :
<div class="row" *ngFor="let ingredient of getControls(); let i=index" [formGroupName]="i" >
The last > char is red until I remove  let i=index.
Thanks,
David

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.10
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.3
Angular2|joh|8.3.1
Angular-BeastCode|Mik|8.1.2
debugger-for-chrome|msj|4.12.6
angular-inject-service|The|0.1.2

</details>

![vsCode1](https://user-images.githubusercontent.com/20335174/73918929-3ac87c80-48cb-11ea-9d54-5990723bb539.jpg)
![vsCode2](https://user-images.githubusercontent.com/20335174/73918932-3bf9a980-48cb-11ea-803d-81c64a0f15c1.jpg)
![vsCode3](https://user-images.githubusercontent.com/20335174/73918938-3c924000-48cb-11ea-9047-7443680f5375.jpg)

**Comment by Grompie** [comment]
Also having this issue, also happens with the other local variables (first, last, even, odd).

Adding an extra ; to the end of the ngfor does seem to solve the problem.

**Comment by soulicious** [comment]
@Grompie Thanks for noting about adding the semi-colon at the end, that saved me!  It was getting really confusing for my commented sections to not show as comments!

**Comment by DavidOs55** [comment]
Thanks @Grompie  , It solved the problem.

**Comment by rthm93** [comment]
> Also having this issue, also happens with the other local variables (first, last, even, odd).
> 
> Adding an extra ; to the end of the ngfor does seem to solve the problem.

You will need to add semicolon `;` if you are assigning variable name in `*ngIf`. example: ```
``` 
<div *ngIf="variableName as var;" [something]="var"></div>
```
