### ISSUE TITLE
Multiple Cursors appear in VSCode Extension for Code Completion When insertText starts with \n

### ISSUE THREAD

**Issue by vinnichase** [microsoft/vscode#90135]
- VSCode Version: 1.41.1
- OS Version: macOS Catalina 10.15.2

I'm experiencing strange behaviour during extension development. If a `CompletionItem`s `insertText` starts with a newline character (`\n`, later newlines are not a problem), submitting the completion item will resolve with two active cursors. But that only happens if you trigger the completion at an indented position (space indent inserted by the tab key). For me it is not a problem since I can remove the newline char. However I wonder If that behaviour is intended.

![screencast1](https://user-images.githubusercontent.com/1173475/73939238-55a9e980-48e9-11ea-8ce3-79bc08eeedf7.gif)

Steps to Reproduce:

1. Create a new extension boilerplate with `yo` as described in the VSCode docs
2. Paste the following example code in `extension.ts`:
```TypeScript
import * as vscode from 'vscode';

class FooCompletionItemProvider implements vscode.CompletionItemProvider {
    public provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken):
        Thenable<vscode.CompletionItem[]> {
        const item = new vscode.CompletionItem('test', vscode.CompletionItemKind.Interface);
        item.insertText = '\nfoo';

        return Promise.resolve([
            item,
        ]);
    }
}

export function activate(ctx: vscode.ExtensionContext): void {
    ctx.subscriptions.push(
        vscode.languages.registerCompletionItemProvider(
            'plaintext',
            new FooCompletionItemProvider(),
        ),
    );
}

// this method is called when your extension is deactivated
export function deactivate() { }
```
3. Test the extension, open a new plaintext document and press tab to indent (should insert spaces in the document, I did not test it with tab indents).
4. Trigger completion and submit the `test` completion item
5. Your editor file should look like this (pipes are cursors):
```
|
    foo|
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
I cannot reproduce... Are you sure that's a cursor and not indent guides? What happens when you type? Can you attach a screen capture

**Comment by vinnichase** [comment]
Updated my post with a screen capture. Typing is not the problem. Just submitting a completion (tab or enter)

**Comment by jrieken** [comment]
I can still not reproduce, make sure to disable other extensions that might be causing this.

**Comment by vinnichase** [comment]
Are you using tabs or spaces? Problem occurs if you use spaces as indent (4 in my case) but insert them with the tab key. If you just type 4 spaces and trigger completion it works fine.

Here all extensions are disabled:

![Bildschirmvideo aufnehmen 2020-02-06 um 16 41 04](https://user-images.githubusercontent.com/1173475/73953040-19ce4e80-4900-11ea-8680-3ebc540170bb.gif)

**Comment by jrieken** [comment]
Indeed. I have tried with a line that indented with spaces but it seems to matter if the document is set to use spaces over tabs. 😱

**Comment by jrieken** [comment]
@alexdima This is actually happening inside `ICodeEditor#executeEdit`. I debugged this into `TextModel#_pushEditOperations` and its handling of edits near the cursor but could pin point this to something.
