### ISSUE TITLE
Vscode crashes sometimes when performing some actions like closing a file

### ISSUE THREAD

**Issue by webczat** [microsoft/vscode#90139]
I am using vscode-insiders for a relatively long time on linux with a screenreader. That may be relevant as it's likely this bug is triggered by screenreader usage.

Generally sometimes when performing some actions, vscode crashes. I have hard time describing that because it doesn't always happen, however:
When the vscode is set to open new untitled file on startup, then closing this file quite often triggered this crash. I saw it also sometimes being triggered by closing editors displaying extension info, by switching views, etc. It's quite random, but not rare, and affects both electron6 and electron7 versions of vscode including newest insiders build.

Environment:
os: linux
using orca screenreader from git master (if relevant)
vscode version info from about dialog:
Version: 1.42.0-insider
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-05T20:04:52.050Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.2-arch1-1

**Comment by webczat** [comment]
Well, I am not sure if it is the same bug, but I can trigger a segfault by pressing esc key in the explorer view, in the file tree. Not sure if that is still reproducible in electron7, need to wait for appropriate build to test it.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by webczat** [comment]
Seems to me like current upgrade to electron7 may have fixed this bug. There are slowdowns, but no crash this day, and this never happened before.
