### ISSUE TITLE
node2 debug adapter sometimes not returning response for launch request

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#90134]
I have written an integration test that tests debug starting.
However this integration tests fails on a build machine every 10th time on average. It always works locally.
After writing a lot of `console.log` as the only way to debug it when it runs on a build machine I have come to believe that the node2 debug adapter sometimes does not return a response for the `launch` request.
Even though the respone is not returned, node2 continues normally and sends all the `initialized`, `variables` and all other responses.

As a workaround for the intregration tests to always pass I am no longer awaiting on the start debugging, but just await on the `initialized` and everything else. And this seems like a fine workaround for now. However I wanted to create this issue to see if you have some ideas what might be wrong and why would `node2` randomly not return from the `launch` request even though it launches just fine.

Example of a failed integration tests with my "logging"
https://dev.azure.com/vscode/VSCode/_build/results?buildId=36396&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=db522a89-84be-55c1-d087-ef4dde315b47

For reference here's the debug intregration test in question
https://github.com/microsoft/vscode/blob/5835d42bdf2f683c703de611f9043171953a1f35/extensions/vscode-api-tests/src/singlefolder-tests/debug.test.ts#L75

fyi @weinand and @connor4312 for potential ideas.

**Comment by weinand** [comment]
@isidorn are you sure that there is really no response?

- there should be a timeout in VS Code in this case.
- some debug adapters trigger their initialization sequence from within processing the launch request. That delays the launch response until after the configurationDone request. See second diagram in https://github.com/microsoft/vscode/issues/4902#issuecomment-368583522

**Comment by isidorn** [comment]
@weinand I am not 100% sure, but it looks like that. Due to it not being easy to debug I stopped my investigation and outlined all the information I found above.
If there was a timeout there would be an error response and the tests would fail, not just await infinitly.
Even if the launch response would come after the configuartionDone the test would pass. It is written in a way to not care in what order they come, they just both have to arrive. Also that would not explain the flakiness.

**Comment by roblourens** [comment]
Would it be possible to start the DA with the 'trace' parameter, then write out the log from the DA?

**Comment by isidorn** [comment]
@roblourens yes I can do that. However the problem with that it is not so easy to reach the output files on the build machine. 
For that I need to do specify the file as an asset which can later be downloaded. And as far as I see the debug adapter picks a file randomly?
Is there a way that I tell the debug adapter where it should write the logs and that it simply writes them there?

**Comment by roblourens** [comment]
You can set `"trace": "verbose"` then the DA will send all logs as Output events and you can make sure those get console.logged. Or you can find the output event with the path of the file and have your test code read it and write that to the console.

**Comment by isidorn** [comment]
I have changed the intregration tests to run with the new node debug. And so far they seem to work fine.
However to help you identify the node2 issue, I have re-ran the old tests with the trace verbose, and here's a test that fails. 
https://dev.azure.com/vscode/VSCode/_build/results?buildId=37031&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d2c76452-9b5b-53aa-b9e7-4eac61843d9f

It has all the debug output in there. Sorry for the bad formatting!

**Comment by roblourens** [comment]
All I can tell is that the adapter got the "launch" request and seems to have sent a response, and nothing crazy happened

```
0-02-11T10:39:31.4171438Z [7235:0211/103931.416291:INFO:CONSOLE(84)] "From client: launch({"type":"node2","request":"launch","name":"Launch debug.js","stopOnEntry":true,"program":"/home/vsts/work/1/s/extensions/vscode-api-tests/testWorkspace/debug.js","trace":"verbose","cwd":"/home/vsts/work/1/s/extensions/vscode-api-tests/testWorkspace","__nodeVersion":"v12.13.0","logFilePath":"/tmp/tmp.G3mJU0ZLqN/logs/20200211T103926/exthost1/ms-vscode.node-debug/debugadapter.txt","__debuggablePatterns":["*.js","*.es6","*.jsx","*.mjs"],"__sessionId":"1c1f3976-9c5c-49e6-838a-ba062e21b2ee"})
2020-02-11T10:39:31.4171997Z ",
2020-02-11T10:39:31.4172722Z [7235:0211/103931.416393:INFO:CONSOLE(84)] "To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"Versions.DebugAdapterCore":"6.8.7","Versions.DebugAdapter":"1.42.1","request":"launch","args":["type","request","name","stopOnEntry","program","trace","cwd","__nodeVersion","logFilePath","__debuggablePatterns","__sessionId","enableSourceMapCaching","sourceMapPathOverrides","smartStep","sourceMaps","showAsyncStacks"]}}}
```

**Comment by isidorn** [comment]
Thanks for looking into it. Yes the flakiness also happens with the new javascript debugger (only discoverd this over the night) just rarer than with node2.
So my main suspect is the communication implementation on the vscode side. Particularly the queueing of messages [here](https://github.com/microsoft/vscode/blob/4d3d0036f838dc8d252de66e154ba1d67e7c3e6a/src/vs/workbench/contrib/debug/common/abstractDebugAdapter.ts#L145)

I will try to get more details today.

**Comment by isidorn** [comment]
The queue communcitaion does not seem to be the case. My latest suspicion is that the test actually takes more than a minute to finish sometimes. Increasing timeout and checking if it helps

**Comment by isidorn** [comment]
Leaving for next debt week unfortunetly.

**Comment by isidorn** [comment]
I have reanabled the test and now they have one more retry. So if they fail two times in a row, only then they fail. That is the best approach I could find since the flakiness on the build machine was very hard to investigate further.
Alternative idea from @bpasero is to use Mock debugger instead of node to not have to launch a process which might reduce flakiness. Missing piece there is that mock debug is not a builtin extension so we would have to somehow install it. We could have a command line argument, but we can look into that if this retry attempt fails.
