### ISSUE TITLE
[feature] make problems view settings permanent

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#90130]
the settings are 
- `show active file only` 
- `hide excluded files`

basically on each time you open a workspace, you'll have to re-enable them.

so could we plz get a way to set them once and for good ?

**Comment by sandy081** [comment]
These are local filters and having some per workspace and some for all will be inconsistent also with other such features.

**Comment by ctf0** [comment]
@sandy081 if there an api i can use to allow this, plz give me the link and i will happily make an extension for it

**Comment by sandy081** [comment]
Sorry this is in internal storage and not exposed.

**Comment by ctf0** [comment]
ok np, thanx
