### ISSUE TITLE
PHP Outline for Classes not updating

### ISSUE THREAD

**Issue by KWIPPED** [microsoft/vscode#90138]
Issue Type: <b>Bug</b>

I have a file I created and have been working in for a while. Recently I went in and moved a method from one location to the bottom of the file and now it will not show when clicking on it in the outline view. It has been over a week now and has not updated to the correct locations

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.10.0
es6-string-css|bas|0.1.0
laravel-blade|cjh|1.1.2
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
terminal|for|0.0.10
vscode-mysql|for|0.4.0
vscode-es6-string-html|hjb|1.1.1
mysql-syntax|jak|1.3.1
easy-icons|jam|0.3.1
mysql-scratchpad|jbl|0.1.1
python|ms-|2020.1.58038
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.49.0
remote-ssh-explorer|ms-|0.49.0
sqltools|mtx|0.21.6
laravel-blade|one|1.20.0
material-icon-theme|PKi|3.9.2
laravel-helpers|raf|0.2.2
es6-string-html|Tob|1.8.8
vscode-workspace-explorer|tom|1.5.0
vscode-icons|vsc|9.7.0
html-css-class-completion|Zig|1.19.0
es6-string-javascript|zjc|1.0.1

</details>

**Comment by roblourens** [comment]
Please file this issue on the PHP extension that you are using, thanks.
