### ISSUE TITLE
Extensions update button hidden on narrow space

### ISSUE THREAD

**Issue by gradha** [Microsoft/vscode#9013]
- VSCode Version: 1.3.0 (1.3.0) e724f269ded347b49fcf1657fc576399354e6703
- OS Version: OSX El Capitan 10.11.5 (15F34)

Steps to Reproduce:

1. Open the extension left pane when there are updates
2. Reduce the space. See attached screenshots.

Actually the buttons were missing for me, the default space was not enough. Maybe buttons in different lines would display better. Or resize themselves proportionally to the width. 

![captura de pantalla 2016-07-09 a las 23 07 05](https://cloud.githubusercontent.com/assets/101927/16710320/653838e0-462a-11e6-9dcc-ca42f9f9b2ef.png)

![captura de pantalla 2016-07-09 a las 23 07 13](https://cloud.githubusercontent.com/assets/101927/16710321/69f888ee-462a-11e6-9e11-c0712254ccb5.png)

**Comment by wallverb** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/8510

**Comment by joaomoreno** [comment]
@dbaeumer : I want to forward this to the translation team. In Spanish, the `Uninstall` button seems way too long and includes the word `extension` unnecessarily.

**Comment by dbaeumer** [comment]
@joaomoreno you can always assign @johnliu2016 from the translation team.

@johnliu2016 can you have a look.

**Comment by johnliu2016** [comment]
@joaomoreno Looks this is a loc check-in timing issue, now Spanish button string has been re-translated to "Desinstalación"

**Comment by joaomoreno** [comment]
Thanks @johnliu2016 !

**Comment by johnliu2016** [comment]
Thanks for pointing that, @joaomoreno 
@lukaschal please send to linguistic review and implement bug fixing

[extensionsActions.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fesn%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Fextensions%2Felectron-browser%2FextensionsActions.nls.resx.lcl&version=GBmaster&_a=contents)
      <Item ItemId=";uninstall" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Uninstall]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Desinstalación]]></Val>
          </Tgt>
          <Prev Cat="Text">
            <Val><![CDATA[Uninstall Extension]]></Val>
          </Prev>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed.

SRC: Uninstall
NEW TGT: Desinstalar
