### ISSUE TITLE
Creating a file in explorer view also opens a previously focused file

### ISSUE THREAD

**Issue by webczat** [microsoft/vscode#90140]
environment:
Version: 1.42.0-insider
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-05T20:04:52.050Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.2-arch1-1

I am not sure if this issue is specific to the fact that I am navigating vscode by keyboard or not...
It seems that creating a new file when another file is selected in vscode opens both the new file and the previously selected one.

Steps to reproduce:

* Launch vscode and go to explorer view with some folder opened,
* Select (but not open) some file for example README.md,
* Press the "new file" on the toolbar to create a new file,
* type new filename and press enter

expected result:

new file is created and opened

actual results:

new file is created and opened, but the previously selected file is also opened with it.

**Comment by isidorn** [comment]
This is an actual issue, however we already have it captured here https://github.com/microsoft/vscode/issues/87524
So let's close this issue as a duplicate and continue the conversation there.
We have this behavior from way back that focus on explorer automatically opens the file, however I personalyl would remove it. Some details here https://github.com/microsoft/vscode/issues/67708

Anyways I am in discussion with @bpasero on this and we might change the behavior, follow https://github.com/microsoft/vscode/issues/87524 for details. Thanks

**Comment by webczat** [comment]
I hit the mentioned issue, but I am not fully certain if they are the same. :) Maybe after I get a build with this one fixed I will be able to check.

**Comment by isidorn** [comment]
They are the same, I am fully certain :)
The build should be out next week so let us know then.
