### ISSUE TITLE
Debug session without a name

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#90149]
- change debug type of "Launch VS Code" debug configuration to pwa-debug
- set breakpoint in extensionsDevOption.ts:22
- start debug session

Observe:
Session name in CALL STACK View is empty:

![2020-02-06_16-30-12](https://user-images.githubusercontent.com/1898161/73951819-7597d800-48fe-11ea-8a07-755ea24ff910.png)

**Comment by connor4312** [comment]
This is because the page and URL for the attached target are both empty

![image](https://user-images.githubusercontent.com/2230985/73952218-9850cf00-48b3-11ea-84ab-bbf9b467c7f5.png)


I could put something like `Target Page` there as placeholder.

**Comment by weinand** [comment]
It would be great if we could find a way to use and show the same "role" names  that we show in VS Code's built-in Process Explorer:

![2020-02-06_16-44-55](https://user-images.githubusercontent.com/1898161/73953101-37031d00-4900-11ea-8f8f-098150738e88.png)

**Comment by connor4312** [comment]
Actually, it sometimes work (shows workbench.html correctly). This is a race in the adapter. Ideally:

 1. We get a new target page that's empty. And on a global level with listen to target info page
 2. We attach to it (async)
 3. We register it in our map
 3. We get a target info changed event and update the target

If the info changed event comes in between steps 2 and 3, we miss the event and leave it as an empty page.

**Comment by connor4312** [comment]
It now seems to more consistently title the target correctly:

![image](https://user-images.githubusercontent.com/2230985/73962875-14531300-48c4-11ea-9aa9-2f058f7c53b9.png)

> It would be great if we could find a way to use and show the same "role" names that we show in VS Code's built-in Process Explorer.

This is an interesting idea. I think we can probably get closer to that for attached processes, which right now we always title "Remote Process"s. For child processes we use the spawned name, which gets is fairly close 

![image](https://user-images.githubusercontent.com/2230985/73963137-993e2c80-48c4-11ea-9bd3-586a00495b93.png)


Open to ideas on how to improve this :)
