### ISSUE TITLE
Add `@deprecated` filter to Setting GUI search input

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#90144]
Currently there seems to be only 3 predefined filters `@ext` / `@modified` / `@tag:usesOnlineServices `

It might be useful to get all deprecated settings.

**Comment by roblourens** [comment]
Deprecated settings are not even shown in the settings UI at all. I'm not sure we want to make them more discoverable. Why would this be useful for you?

**Comment by usernamehw** [comment]
> Why would this be useful for you?

They are often deleted/renamed before I notice them.

--- 

I was just scrolling and there was a flash of a different color:

![Screenshot (139)](https://user-images.githubusercontent.com/9638156/74006940-31541880-498e-11ea-8c91-c3c258d2a790.png)

I think it would be better if all of the deprecated settings were shown in Settings GUI.

**Comment by roblourens** [comment]
I still don't know, typically we deprecate settings but still respect them if they are set. We aren't expecting anyone to have to keep on top of deprecated settings to migrate them every month, or anything like that. If there is something important that people need to know about a setting, it is typically in the release notes and I think that is a better place for info like that.
