### ISSUE TITLE
Code suggest isn't working.

### ISSUE THREAD

**Issue by alpgul** [microsoft/vscode#90141]
- VSCode Version:1.41.1
- OS Version:W7

![vs](https://user-images.githubusercontent.com/5773704/73943338-a3cae700-4901-11ea-9b78-d323842f8138.gif)

**If I define "default value" in the method, the code suggestion does not work.**

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/28210
