### ISSUE TITLE
Problems syncing globalState on web ENOENT argv.json

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90145]
Right after turning on sync this happens (selfhost web, local server).

```
[2020-02-06 06:26:14.856] [userDataSync.log] [error] GlobalState: Unable to read file 'vscode-userdata:/User/argv.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/Users/daimms/.vscode-web-dev/data/User/argv.json')
```

<img width="1233" alt="Screen Shot 2020-02-06 at 6 27 28 AM" src="https://user-images.githubusercontent.com/2193314/73945834-c6c9ac80-48a9-11ea-896f-840d64848832.png">

**Comment by sandy081** [comment]
`argvResource` is not available in resource.

@bpasero I remember we discussed about this that `argvResource` has to be made optional in web?

**Comment by bpasero** [comment]
@sandy081 but it is defined for web:

https://github.com/microsoft/vscode/blob/bb3edc40e6430179721ce2c7945557958fd94b7e/src/vs/workbench/services/environment/browser/environmentService.ts#L137

I am not sure how useful it is for web though, I do not think we currently reference it for web anywhere.
