### ISSUE TITLE
@-moz-document returns errors in SCSS when inside selector

### ISSUE THREAD

**Issue by rafaucau** [microsoft/vscode#90151]
Issue Type: <b>Bug</b>

In SCSS, you can add @media in the selector, but when I add @-moz-document url-prefix (), VS Code returns errors, although it works and compiles well to CSS.
![scss](https://user-images.githubusercontent.com/25438601/73953495-c6103500-4900-11ea-8788-cf4818e1d504.jpg)

```
.hero {
	background-attachment: fixed;
	@-moz-document url-prefix() {
		background-attachment: scroll;
	}
}
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
gutensnip|ash|1.0.5
vscode-intelephense-client|bme|1.3.9
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
prettier-vscode|esb|3.20.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.15
minify|Hoo|0.4.3
vscode-browser-sync|jas|1.3.1
vscode-gutter-preview|kis|0.25.0
sftp|lix|1.12.9
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.9.0
python|ms-|2020.1.58038
remote-wsl|ms-|0.41.9
cpptools|ms-|0.26.3
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|3.9.2
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.5
wordpress-toolbox|wor|1.3.6
material-theme|zhu|3.2.2

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
I'm not sure why SCSS is not following the spec: https://developer.mozilla.org/en-US/docs/Web/CSS/@document, which says inside the `@document` block there should be a ruleset like `.foo { color: blue; }` not `color: blue;`.
