### ISSUE TITLE
Multiline search causes all cores to max out, and stay maxed out

### ISSUE THREAD

**Issue by AlanRosenthal** [microsoft/vscode#90154]
Issue Type: <b>Bug</b>
When I search a single line:
![image](https://user-images.githubusercontent.com/1288897/73954759-49fdf900-48d0-11ea-8c1b-40b40c85a8e4.png)

![image](https://user-images.githubusercontent.com/1288897/73954723-39e61980-48d0-11ea-83c7-38a55f7ad8ef.png)

When I search for multiple lines:

![image](https://user-images.githubusercontent.com/1288897/73955066-c4c71400-48d0-11ea-952e-22d51b263da2.png)

![image](https://user-images.githubusercontent.com/1288897/73955216-fb9d2a00-48d0-11ea-96ad-af057b0b07f2.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 3980)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|8, 8, 5|
|Memory (System)|31.00GB (1.42GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.4.0
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.29
doxdocgen|csc|0.5.2
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.0
json-tools|eri|1.0.2
unsaved|esa|0.2.5
hex-fmt|ker|1.0.0
prettify-json|moh|0.0.3
binary-viewer|mom|0.0.1
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
proto|pet|0.0.2
vscode-yaml|red|0.6.1
code-spell-checker|str|1.7.22

</details>

**Comment by roblourens** [comment]
It is definitely more expensive, that is expected. Does it still finish eventually? Is your workspace really large?

**Comment by AlanRosenthal** [comment]
It does eventually finish. It would be great if it didn't use all of my computer's cores, making my computer mostly unusable

**Comment by JacksonKearl** [comment]
How many files are in the project (`code --status`) and how long does the search take? Do you have exclude files configured for search?

**Comment by roblourens** [comment]
There are some general tips here: https://github.com/microsoft/vscode/wiki/Search-Issues#search-including-too-many-results

But yeah otherwise I don't want to restrict the parallelization of search because it would slow it down. Multiline search is just fundamentally more expensive

**Comment by AlanRosenthal** [comment]
|      File types: c(4563) h(2706) xml(587) png(562) mk(521) py(485) pod(451)
|                  pem(320) S(315) json(311)
|      Conf files: makefile(92) cmake(87) tsconfig.json(28) package.json(27)
|                  sln(6) tslint.json(6) launch.json(3)

single line search takes maybe ~0.5 seconds if that
multi line search takes roughly 45 seconds
|                  settings.json(2) tasks.json(1)

**Comment by AlanRosenthal** [comment]
looks like its roughly the same as ripgrep
```
❯ time rg "asdf"
rg "asdf"  1.63s user 1.39s system 957% cpu 0.316 total

```
❯ time rg --multiline "asdf\nasdf"
rg --multiline "asdf\nasdf"  1249.32s user 17.14s system 1015% cpu 2:04.70 total
```

IMO, as a user, I'd rather only dedicate half or most (not all) of my cores to multiline search, since my computer becomes unusable for almost two minutes

**Comment by roblourens** [comment]
That's quite the explosion in time. Thanks for verifying that though.

I would be open to limiting search parallelization. Will leave this open

**Comment by JacksonKearl** [comment]
If you play around with parallelism (`-j6, -j8, -j10, -j11`) how does search time and machine usability change?

**Comment by roblourens** [comment]
And how many cores do you have?

**Comment by BurntSushi** [comment]
@AlanRosenthal Multiline search can sometimes be more expensive, but the times you're reporting seem like a much bigger increase than I would expect. Is it possible for you to reproduce that disparity on a corpus that we both have access to?

**Comment by kissstudio** [comment]
mark.

**Comment by danieldelcore** [comment]
Hey 👋,

I've been experiencing issues with this too. 
Seems to be whenever i try and do a project-wide search, a process called `rg` spins up and requires 900% of my CPU:

![image](https://user-images.githubusercontent.com/3030010/75299819-310eb500-588a-11ea-923d-1596d26382de.png)

I'm on a MacBook Pro with Mojave

**Comment by roblourens** [comment]
Please open your own issue with some more details. You can see troubleshooting tips here too: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
