### ISSUE TITLE
VSCode remains opened sometimes after being closed

### ISSUE THREAD

**Issue by aleksandaratanasov** [Microsoft/vscode#9015]
- VSCode Version: just updated to 1.3.0
- OS Version: Debian Jessie 64bit

Steps to Reproduce:

1. Start VSCode
2. Close VSCode

**Detailed description:**

I've recently installed VSCode for the first time on my system. I've noticed that after closing VSCode a couple of processes remain active namely `code/code`, `Microsoft.VSCode.CPP.Extension.linux` , `code/code /usr/share/resources/app/out/bootstrap --type=SharedProcess` and probably a bunch of others which I haven't found yet. `code/code` is (if I'm not mistaken) the main process of VSCode. And the fact that all other processes remain in memory can only mean that VSCode hasn't actually closed and keeps running in the background.

The first time my alarm bell rang was when my system exhibited high memory usage and high CPU usage (resulting in a core temperature of 68 degrees Celsius or so with the usual temperature being approx. 50). I then noticed that this happened **quite often** (but **not always**) after I used VSCode. When I opened `htop` to view the active processes I was really surprised to find out that `Microsoft.VSCode.CPP.Extension.linux` was there and it was eating up approx. 25% of my CPU resources...half an hour or so after closing VSCode. Further investigation showed me the other processes related to VSCode that I've mentioned above.

**Comment by joaomoreno** [comment]
Thanks for the detailed info!

#8859
