### ISSUE TITLE
Clarify language in git extension for creating new branch from another branch

### ISSUE THREAD

**Issue by eyeino** [microsoft/vscode#90158]
When using the git extension, the intent is clear when clicking on "+ Create new branch..." and immediately being prompted "Please provide a branch name".

![image](https://user-images.githubusercontent.com/1900909/73965949-12e51300-48e3-11ea-9342-b4d7100146aa.png)

![image](https://user-images.githubusercontent.com/1900909/73965784-c26db580-48e2-11ea-8234-1a40c2a22a89.png)

 But, when clicking on "+ Create a new branch from..." the intent is ambiguous, since the statement "Please provide a branch name" could refer to the branch from which you wish to base the new branch or the name of the new branch, the latter being what actually happens. I've gotten confused one too many times, and inadvertently typed "develop" for the first prompt, only to be prompted with "Select a ref to create the 'develop' branch from". Whoops, time to start over.

![image](https://user-images.githubusercontent.com/1900909/73965834-ddd8c080-48e2-11ea-84c9-3ffc295086af.png)

By specifying "Please provide a *new* branch name...", the intent is clear: the prompt is asking for the name you wish to call the new branch.

**Comment by joaomoreno** [comment]
Let's swap the pick order, what do you think?

**Comment by joaomoreno** [comment]
Oh I see you already have a PR for it 👍
