### ISSUE TITLE
Word wrapping on non-monospace still fails

### ISSUE THREAD

**Issue by paul-go** [microsoft/vscode#90156]
- VSCode Version: 1.42.0-insider
- OS Version: macOS 10.13.6

@alexdima
I was the one who reported #2654 many moons ago. The purported fix at #89389 does not appear to address the problem of word wrap occurring prematurely when a proportional font is used:

![Screen Shot 2020-02-06 at 12 03 56 PM](https://user-images.githubusercontent.com/16612419/73960569-2a1f0300-48d9-11ea-90d5-c14cb8261d3b.png)

Relevant configuration settings from my `settings.json` file:

![Screen Shot 2020-02-06 at 12 07 50 PM](https://user-images.githubusercontent.com/16612419/73960879-a0236a00-48d9-11ea-93ed-365aacc7b442.png)

As can be seen, the new `editor.wrappingAlgorithm` setting does not appear to be recognized, which would suggest I either don't have the latest version of VS Code, or have some misconfiguration, but I'm out of ideas in this regard.

Open Sans Code is a derivation of the Open Sans font that I tuned for proportional font coding. I've swapped this out for other proportional fonts (Lato, Helvetica) with no success.

I also attempted to pass these settings directly to a test project that uses the Monaco editor with similar results.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Per #89573 it got renamed `editor.wrappingStrategy`
