### ISSUE TITLE
Focus not restored properly after hovering over a symbol while debugging

### ISSUE THREAD

**Issue by GoaLitiuM** [microsoft/vscode#90167]
When debugging and having the debugger on break, hovering over any symbol changes the cursor focus to text editor instead of back to the UI element which was previously focused on. This issue manifests when I use the document search while the debugger is paused and the focus suddenly changes back to editor without touching any keys other than enter in order to jump to the next search result.

**To Reproduce**
1. Start debugging the application.
2. Hit Pause in debugger.
3. Open up the document search box (CTRL-F) and type something in the field.
3. Move the mouse cursor over any symbol (function, variable etc.) in the editor which prompts the inspector/info box.
4. Move the cursor away to dismiss the info box.
5. Observe the focus changing back to the previous cursor location in text editor instead of back to the search box.

**Expected behavior**
The focus should be restored back to the previously active element instead of the text editor.

- OS and Version: Windows 10
- VS Code Version: 1.41.1

**Comment by isidorn** [comment]
Thanks for filling this issue. We have pushed a fix and you can try vscode insiders from next week to verify the issue got fixed.
Now we only focus back the editor if the debug hover actually had focus.
