### ISSUE TITLE
Deleted folder reappears

### ISSUE THREAD

**Issue by jalal1** [microsoft/vscode#90169]
Issue Type: <b>Bug</b>

1- Select a folder on vsc menu and press "delete" ( I turned off the warning message that asks me if I am sure to delete) so the folder disappeared/deleted.
2- Refresh from the top right corner, and the folder reappear! 
3- I went to the folder location and still I can see it. 
4- I tried to delete the folder, it said : "Folder in use", try again..

It seems one of the files lock the deletion, but from vsc it allows me to delete and it appears as deleted, but it is not. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
vscode-postgres|cko|1.1.11
gitlens|eam|10.2.0
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|2.1.32
latex-workshop|Jam|8.7.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-filesize|mkx|2.1.3
mssql|ms-|1.8.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.58038
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
java|red|0.55.1
vscode-java-debug|vsc|0.24.0

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/43819
