### ISSUE TITLE
Undo can fail to restore previous text

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90168]
On Windows 7.

1 In a new file type `int bob`
2 Press Ctrl+Shift+LeftArrow, selecting `bob`
3 Type `jim`
4 Press Ctrl+Z to Undo

Expected: `int bob`
Observed: `int`

Workaround: at 2, instead press Press Shift+LeftArrow thrice.

**Comment by chrisjj** [comment]
> Please also check if it is already covered by an existing one

I did already, as per the posting form's instructions.

Please stop wasting user time, bot.

**Comment by alexdima** [comment]
Duplicate of #51275
