### ISSUE TITLE
Missing command substitution in args for launch.json

### ISSUE THREAD

**Issue by shawn-higgins1** [microsoft/vscode#90165]
Issue Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.3.0

Steps to Reproduce:

1. Create a new launch configuration
2. In the args field add an arg with command substitution. e.g. $(pwd)
3. The command doesn't get run and instead a string of the command is passed as the argument

**Comment by weinand** [comment]
`${pwd}` is not something VS Code understands. Please see https://code.visualstudio.com/docs/editor/variables-reference
