### ISSUE TITLE
Undo and Redo are missing from documentation

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90173]
1 At https://code.visualstudio.com/Search, enter `undo` and press Enter
2 Using browser Find, search each result for `undo` or `redo`

Expected: documentation on undo / redo
Observed: none

Windows 7 and Google Chrome

Please do not mistake this as a duplicate of https://github.com/microsoft/vscode/issues/90174

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-docs/issues/3393. Should show up in search shortly.
