### ISSUE TITLE
All pixels shifts up miserably

### ISSUE THREAD

**Issue by lextm** [Microsoft/vscode#9017]
- VSCode Version: 1.3.0
- OS Version: OS X 10.11.5

I don't know how it ended up with this, so sorry no step to reproduce. A screen shot is as below,

![screen shot 2016-07-10 at 11 57 49 am](https://cloud.githubusercontent.com/assets/425130/16711620/cc3e6c54-4697-11e6-9f5d-857563304477.png)

I will try to reproduce it in the future and add more info if possible.

**Comment by bpasero** [comment]
@lextm yes, some steps would be greatly appreciated.

**Comment by lextm** [comment]
Closed temporarily till I can reproduce it.
