### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by keldju** [microsoft/vscode#90175]
Issue Type: <b>Bug</b>

cannot select theme clicking in cog

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.19559

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
gitlens|eam|10.2.0
flutter-mobx|Flu|0.0.5
adb-interface-vscode|vin|0.14.0

</details>

**Comment by eamodio** [comment]
Oops, the bot was overzealous there. I can't reproduce it -- can you provide more details?

**Comment by keldju** [comment]
Displaying the Release Notes page, when clicking on the cog it is not possible to select the theme change

**Comment by eamodio** [comment]
I can now reproduce it -- so a webview need to be the active editor, and then you will see the quick pick for the color theme flash and disappear.

**Comment by eamodio** [comment]
@keldju Why did you close this one?

**Comment by aeschli** [comment]
I'm not able to reproduce:
- Open release notes
- Click on the gear, color theme
- Picker opens and I can use cursor keys, mouse, keyboard to select a theme
