### ISSUE TITLE
Colour picker text could be better

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90189]
In

![image](https://user-images.githubusercontent.com/6157073/73991452-18bf1080-4944-11ea-8be4-880e71eac607.png)

![image](https://user-images.githubusercontent.com/6157073/73991427-06dd6d80-4944-11ea-9685-28d69c098f0f.png)

1) The code in the top bar could be properly centred 

2) The second's first line would be better if it were consistent - "Color of an element's background"

3) Is there any point to the third line's `Syntax:<colour>` ?

4) Color is misspelt. Only kidding! :)

**Comment by rebornix** [comment]
@octref correct me if I'm wrong, the wording `Syntax: <color>` is from the CSS extension?

**Comment by octref** [comment]
Yes but we won't change that. It describes the property value's syntax:

![image](https://user-images.githubusercontent.com/4033249/74175567-ed118400-4bea-11ea-9e34-c7782610a308.png)

I pushed a commit to make the description consistent.

**Comment by chrisjj** [comment]
> It describes the property value's syntax:

I think it fair to say that `<color>` does not _describe_ anything.

**Comment by octref** [comment]
It says the value is a color, not a number, not a pixel value, etc.
