### ISSUE TITLE
Syntax color highlight wrong

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#90184]
- VSCode Version: v1.42
- OS Version: macOS 10.15.3

Steps to Reproduce:

1. Open [this](https://github.com/dalisoft/nanoexpress/blob/pro/src/Route.js#L459-L486) file and go-to L459-486
2. See how it's syntax highlight gets lost highlight after load

Screenshots:
![](http://joxi.ru/Vm6nZjzCj43P8m?d=1)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Looks like an issue in the TypeScript Textmate grammar. 


![image](https://user-images.githubusercontent.com/6461412/74021553-053f9400-499c-11ea-93f9-f022817e667e.png)

**Comment by JacksonKearl** [comment]
minimal repro: 

```ts
!/s?/
{ let foo; }
```

![image](https://user-images.githubusercontent.com/8586769/74042094-c00b6a00-497b-11ea-8944-cf111e8e09b6.png)
![image](https://user-images.githubusercontent.com/8586769/74042104-c4d01e00-497b-11ea-838f-e377a8715305.png)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/805 to track upstream
