### ISSUE TITLE
[cpp] Visual Studio Code highlights C++14 Digit Separators Incorrectly

### ISSUE THREAD

**Issue by BillyONeal** [Microsoft/vscode#9018]
- VSCode Version: 1.3.0
- OS Version: Windows 10 10586

![Broken digit separators demonstration](https://cloud.githubusercontent.com/assets/1544943/16711798/101ddb64-4623-11e6-91e1-74c6bf5d0bc3.png)

**Comment by BillyONeal** [comment]
Note: Does not matter whether or not the C++ extension is installed.

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#154
