### ISSUE TITLE
VSCode + GIT + WSL refuse to work well together?

### ISSUE THREAD

**Issue by marbuser** [microsoft/vscode#90186]
Issue Type: <b>Bug</b>

I'm using WSL and using VSCode as my editor, but upon trying to push any code via VSCode's built-in SCM, I get "permission denied", which I know is a git issue. However, if I run `git push` from either WSL or even Windows CMD prompt, it prompts me for my password and then pushes the code perfectly file. I'm not entirely how to fix this as it seems like solely a VSCode issue?

Obviously this is happening because my GIT ssh key isn't being added to some type of agent, so can someone please give some information as to how I could fix this because in all my searching, all I keep finding is people using passwords and not SSH Keys, and also people saying I need to install some WSL extension for Code which I've already done and it doesn't fix it at all. I also found a powershell command that apparently is supposed to add your keys to the agent, but that didn't work either. So I'm really not sure what to do about this. Hopefully someone can help me out.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.82GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
increment-selection|alb|0.2.0
vscode-tailwindcss|bra|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
language-postcss|cpy|1.1.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.0.15
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.0
macros|ged|1.2.1
vue-snippets|hol|0.1.11
auto-comment-blocks|kev|1.0.1
expand-region|let|0.1.4
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.6
vetur|oct|0.23.0
vscode-versionlens|pfl|0.24.0
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.1
lorem-ipsum|Tyr|1.2.0
vscode-icons|vsc|9.7.0
quokka-vscode|Wal|1.0.277
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.7.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by marbuser** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [git push to a remote with an ssh password (#69033)](https://www.github.com/microsoft/vscode/issues/69033)

To any non-bot who reads this, not a duplicate. I've tried all the solutions on any issue even remotely related to this and none of them work at all.

**Comment by Falanke21** [comment]
I'm experiencing the same issue here. I also use WSL and Git with Vscode and the git diff color hint in the editor is not working right now. 
I'm guessing this is a new bug introduced by the new release of VSCode since I just update it.

**Comment by Falanke21** [comment]
Somehow I got rid of this bug by uninstalling and reinstalling Vscode. Maybe try that?

**Comment by danjdewhurst** [comment]
I'm unable to push or pull when working on a WSL project. I'm forced to close VS Code, push or pull and then open it back up or it's unable to properly lock/unlock the repository.

**Comment by gusbemacbe** [comment]
Hi, I have solved it, helping my friend to fix it on WSL terminal, but I did not remember how I did. I am waiting for my friend to send the bash history I will find for you.

**Comment by gusbemacbe** [comment]
My friend removed the Ubuntu app. :-( SO I made an installation by myself and a test. The git worked on WSL without error. 

I guess you were using the WSL 1, @marbuser, @danjdewhurst and @Falanke21

**Comment by joaomoreno** [comment]
@marbuser Is this still an issue?
