### ISSUE TITLE
Make --wait support resilient against moved editors that issue a close event

### ISSUE THREAD

**Issue by WesToleman** [microsoft/vscode#90193]
Issue Type: <b>Bug</b>

## Bug discovery and motivation

This bug was discovered when entering a Git interactive rebase and dragging the *git-rebase-todo* tab between columns. When the file is closed it begins the rebase. This may happen before the todo list is in a desirable state.

## Steps to reproduce

1. Have the editor in two column layout
1. Open a file in the first column
1. Drag the file to the second column

## Behaviour

Expected Behaviour: The existing file handle is maintained
Observed Behaviour: The file is closed and re-opened in the second column

---

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
overtype|ada|0.2.0
ng-template|Ang|0.900.11
spellright|ban|3.0.50
unique-lines|bib|1.0.0
markdown-checkbox|bie|0.1.3
markdown-preview-github-styles|bie|0.1.6
better-whitespace|chm|1.0.1
ssh|chr|0.0.4
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.34.0
vscode-quick-select|dba|0.2.8
confluence-markup|den|0.1.8
EditorConfig|Edi|0.14.4
json-tools|eri|1.0.2
vscode-diff|fab|1.4.0
ansible|haa|0.2.8
githd|hui|2.2.0
reg|ion|1.0.1
svelte-vscode|Jam|0.9.3
csharpextensions|jch|1.3.1
read-time|joh|0.2.0
docomment|k--|0.1.8
restructuredtext|lex|117.0.0
HTMLHint|mka|0.6.0
mssql|ms-|1.8.0
python|ms-|2020.1.58038
powershell|ms-|2020.1.0
sublime-keybindings|ms-|4.0.6
vscode-typescript-tslint-plugin|ms-|1.2.3
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.12.6
vscode-yaml|red|0.6.1
partial-diff|ryu|1.4.1
jinjahtml|sam|0.11.0
trailing-spaces|sha|0.3.1
vscode-table-formatter|shu|1.2.1
line-endings|ste|1.0.3
rewrap|stk|1.9.1
open-in-browser|tec|2.0.0
vscode-tidymarkdown|teh|0.0.4
org-mode|too|0.5.0
vscode-ansible|vsc|0.5.2
gitblame|wad|3.0.1
highlight-bad-chars|wen|0.0.3
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.7.0
tabindentspacealign|zhi|1.2.3

</details>

**Comment by bpasero** [comment]
I think the issue here is not the fact that the editor closes but the fact that we have some listener that thinks the file got closed for good and then issue back to the waiting process that it can release, would you agree?

**Comment by WesToleman** [comment]
Yes, the main issue is the waiting process sees the file as closed and continues on. Resolving that would be sufficient to fix the bug.
