### ISSUE TITLE
[BUG] Can't open unzip file

### ISSUE THREAD

**Issue by BlackYuzia** [microsoft/vscode#90196]
## Description

When you move file from atchive to vscode window. You get error what file don't found.
For example, when you use NPP (Notepad ++) he didn't have this trouble and he can open files with this method without troubles.

## Info

- VSCode Version:  **1.37.x**
- OS Version: **Windows 7**

Steps to Reproduce:

1. Create archive with any file
2. Open this archive
3. Select file and move this to vscode window.
4. Get **error** about `can't found XXX file`
5. Profit.

> Does this issue occur when all extensions are disabled?: Yes

### Example:
I have Archive: 
![image](https://user-images.githubusercontent.com/25010528/74000628-71f16900-4971-11ea-9ec9-ddcf024468cb.png)
When I try move file **Demo.cs** I get this:
![image](https://user-images.githubusercontent.com/25010528/74001012-b3cedf00-4972-11ea-95cb-547eed8bf433.png)
> Translated to eng: Can't open 'Demo.cs': Can't read file ( Erorr: File don't found (../Demo.cs)

PS: Try find the same issue but I fault, so I was create this one :c

**Comment by bpasero** [comment]
@BlackYuzia what zip program are you using to move files out of?

**Comment by BlackYuzia** [comment]
@bpasero **WinRAR**

**Comment by bpasero** [comment]
I tested this and I am not getting back any path from the drop event, so we open a file that does not exist. I will add this issue to the list in https://github.com/microsoft/vscode/issues/164
