### ISSUE TITLE
Configured debug type 'pwa-node' is not supported.

### ISSUE THREAD

**Issue by rwu823** [microsoft/vscode#90195]
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. step node debug in `.vscode/launch.json`
```
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/app.js",
      "skipFiles": [
        "<node_internals>/**"
      ]
    },
```
2. run the debug

![image](https://user-images.githubusercontent.com/890063/73999945-52723480-49a1-11ea-8ebc-f8639af0fab7.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by AssisrMatheus** [comment]
I'm having the same issue with

```
{
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "runtimeArgs": ["--inspect-brk", "${workspaceRoot}/node_modules/jest/bin/jest.js", "--runInBand", "crmSync"],
      "console": "internalConsole",
      "internalConsoleOptions": "neverOpen",
      "port": 9229
    }
```

![image](https://user-images.githubusercontent.com/12276174/74049970-f95fcc00-49b3-11ea-911b-1c092340ed55.png)

Had it working fine before.

**Comment by AssisrMatheus** [comment]
I noticed that for me, the issue is that I had in my settings.json
````
"debug.node.useV3": true,
"debug.chrome.useV3": true
```
But I have uninstalled the extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly.

Removing the settings fixed it for me

**Comment by connor4312** [comment]
Do you have either `debug.node.useV3` or `debug.javascript.usePreview` enabled? If so, you'll need to install [js-debug-nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly) to allow it to work.

**Comment by rwu823** [comment]
I remove `debug.node.useV3 ` setting and it's worked fine, thanks. close it.

**Comment by Didier68** [comment]
Version : 1.43.0 (system setup)
Validation : 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date : 2020-03-09T19:47:57.235Z
Électron : 7.1.11
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/49448202/76440265-e2026d00-63bd-11ea-83bd-e30c991acf16.png)


Hi to all,

I  updated VSCode, installed **js-debug-nightly**, and set the parameter ["debug.node.useV3": true]  to test this extension.

Then I decided to unstall the js-debug extension and also removed  this option ["debug.node.useV3": true],...  Now, I have the  same issue than @AssisrMatheus  (but in french)

The content of  C:\Users\xxx\AppData\Roaming\Code\User\settings.json: 
`
{
    "editor.minimap.showSlider": "always",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "window.zoomLevel": 0,
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "editor.minimap.size": "fill",
    "editor.columnSelection": false,
    "editor.minimap.enabled": false
}`
