### ISSUE TITLE
Files set in .gitignore are not grayed out in sidebar

### ISSUE THREAD

**Issue by Infifty** [microsoft/vscode#90192]
Issue Type: <b>Bug</b>

After updating Visual Studio Code to the latest version, files and folders set in .ignore in some Git local repositories are no longer displayed in gray in the sidebar.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
markdown-preview-github-styles-custom|dmo|0.1.4
gitlens|eam|10.2.0
auto-rename-tag|for|0.1.1
code-runner|for|0.9.15
git-graph|mhu|1.21.0
HTMLHint|mka|0.6.0
sublime-keybindings|ms-|4.0.6
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|3.9.2
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
partial-diff|ryu|1.4.1
japanese-word-handler|sgr|1.2.0
vscode-autohotkey|sle|0.2.2
selectline-statusbar|tom|0.0.2
highlight-matching-tag|vin|0.9.6
markdown-all-in-one|yzh|2.7.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
@Infifty does this still happen if you launch with all extensions disabled?

**Comment by Infifty** [comment]
Yes, I tried disabling all extensions but it didn't change.
It was the same even if VSCode is uninstalled and initialize the settings.

**Comment by isidorn** [comment]
This is done by the git decoration provider, thus forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
Can you reproduce on other repositories in your system?

**Comment by Infifty** [comment]
If I tried cloning the repository, the files and folders specified in .gitignore can be grayed out properly.

By replacing the cloned repository with the original, we were able to get back to the original state.

Thanks for helping!

**Comment by Conduitry** [comment]
This is happening for me as well, on multiple repositories, upon updating to 1.42.0. When I re-clone one of the repositories to a new location and open that, ignored files are once again grayed out in the file explorer, but this still feels like a bug.
