### ISSUE TITLE
Whitespace character not rendering properly when using serif fonts.

### ISSUE THREAD

**Issue by alexcheninfo** [microsoft/vscode#90197]
VSCode Version: 1.42.0-insider.
OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Set a serif font. E.g. `"editor.fontFamily": "'Input Serif Narrow'"`
2. Render whitespace characters: `"editor.renderWhitespace": "boundary"`

Screenshots:

![Screenshot from 2020-02-07 12-34-52](https://user-images.githubusercontent.com/1061237/74001560-0de99780-49a7-11ea-8356-79df6c40c36f.png)
![Screenshot from 2020-02-07 12-43-06](https://user-images.githubusercontent.com/1061237/74001668-6b7de400-49a7-11ea-99a4-b1fe5efc8ce3.png)

(Fonts used: Input Mono and Input Serif Narrow. [Source](https://input.fontbureau.com/).)

> Does this issue occur when all extensions are disabled? Yes.

Note: Whitespace rendering looks better in VSCode version 1.41.1 (stable).

![Screenshot from 2020-02-07 12-44-15](https://user-images.githubusercontent.com/1061237/74001724-a718ae00-49a7-11ea-8128-93b128767d62.png)

**Comment by alexdima** [comment]
This is caused by the fix for https://github.com/microsoft/vscode/issues/87359

Note how in 1.41.1 you have the problem described in #87359 , where the `&middot` overruns the characters... It is just for this font, the effect is not so bad.

**Comment by alexcheninfo** [comment]
@alexdima Thanks for the fast reply. You are right. Other serif fonts are okay. 

So I guess this isn't going to be labeled as a bug and fixed.
