### ISSUE TITLE
Monokai theme shows different markdown syntax highlight at 1.3.0

### ISSUE THREAD

**Issue by venele** [Microsoft/vscode#9019]
- VSCode Version: 1.3.0
- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:
1. Use monokai built-in theme.
2. Open markdown file

1.2.1
![before_1 3 0](https://cloud.githubusercontent.com/assets/467125/16712127/a62972dc-46b7-11e6-98d3-0433807033af.png)

1.3.0
![1 3 0](https://cloud.githubusercontent.com/assets/467125/16712128/a81ce9d4-46b7-11e6-8a50-303064618334.png)

I read 1.3.0 release changelog, there's description about extracting markdown feature to extension.
but i don't know the description includes changes of syntax highlight also.

Is it a bug?

**Comment by gerane** [comment]
this is every theme but the built in dark theme for me right now.

**Comment by mjbvz** [comment]
I believe this change was by design, but please let us know if you have any suggestions or ideas on how any of the themes could better display markdown content. Thanks.
