### ISSUE TITLE
"source is not available" when i use http module in vscode plugin

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#902]
It throw “source is not available” error when I imported “http” module and use one API in my code ,anyone know what’s the problem?

Code :
                      http.request('http://www.google.com', function(response) {
                            console.log(response.statusMessage)    });
plugin sample code(http://mediasvc1nxn1n47jdwb5.blob.core.windows.net/guided-tours/testIntellisenseJavascript.zip) 

Steps for repro this problem:
1.	Download the source and open it in VSCode
2.	Run it and you will see an vscode instance 
3.	Change the language mode in “untitled-1” from “Plain Text” to “Javascript”
![aa](https://cloud.githubusercontent.com/assets/15098626/11526687/37e5d638-9917-11e5-8e1c-4a983b8ef6ab.png)
4.Type an character and it will trigger the method “”,then you will see the error.
![bb](https://cloud.githubusercontent.com/assets/15098626/11526691/3cee574a-9917-11e5-9b7b-93b3a23d4cb0.png)

**Comment by weinand** [comment]
@BleyChen In what line do I have to set a breakpoint? (Breakpoints are not stored in your zipped workspace). Do I have to step through the code?

**Comment by BleyChen** [comment]
Set breakpoint on line 52 for the code :			
http.request('http://www.google.com', function(response) {
				console.log(response.statusMessage) // Show the HTML for the Google homepage. 
			});

in  "extension.ts" file

**Comment by BleyChen** [comment]
@weinand  can you repro this problem?

**Comment by weinand** [comment]
@BleyChen yes, I can reproduce the problem. This problem is unrelated to the imported "http" module. The debugger ended up in some internal JavaScript code for which no TypeScript source is available. Instead of trying to show the *.ts source we should show the *.js instead.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#21
