### ISSUE TITLE
Add API to create uris for extension resources

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#90208]
Today, there is `asAbsolutePath(relativePath: string): string;` which is used to create paths for resources contained inside extension, e.g images for tree view items etc.  Given remoteness of things this isn't sufficient anymore, e.g a scenario in which the renderer is on a different machine than the extension doesn't work with file paths but needs uris.

**Comment by jrieken** [comment]
The proposal is to add a new function to `vscode.ExtensionContext` like so `asExtensionUri(relativePath: string): Uri;`

**Comment by jrieken** [comment]
What's maybe better is to simply expose the full extension URI, similar to [`Extension.extensionPath`](https://github.com/microsoft/vscode/blob/efb781e5becac763a91e7a7434aaef671b38d9a9/src/vs/vscode.d.ts#L5009) there could be `Extension.extensionUri`. Then to derive new URIs we could expose something similar to our (internal) [`joinPath`](https://github.com/microsoft/vscode/blob/a94e5d915c29906bcf3e375f57420522c29c8e36/src/vs/base/common/resources.ts#L109)-function, e.g a util that combines an uri and a relative path into a new uri. That would be more universal and also help with `workspace.fs` usage

**Comment by jrieken** [comment]
There is two ideas/proposals

**1.** Extend `Uri.with` so that it accepts a `relativePath`. A sample would look like this:
```ts
const newUri = someUri.with({ relativePath: './tsconfig.json' });
```
😄 this builds on the existing `with`-modifier concept
😕 we need doc to clarify what happens in this case  `someUri.with({ path: 'foo', relativePath: './bar' })`

**2.** Add a new static factory function `Uri.joinPath` which takes a base uri and a relative path to construct a new uri. The sample from above is now this:
```ts
const newUri = vscode.Uri.joinPath(someUri, './tsconfig.json');
```

😄 easy to disover and opens the door for more "path modifiers" like URI.dirname etc
😕 this competes with the `with`-modifier concept

**Comment by jrieken** [comment]
We have decided for option 2 but not yet on the details of its implemenation corner cases, e.g should a file-uri with windows-path on unix be treated as win32-path or as posix-path?

**Comment by jrieken** [comment]
@srivatsn @lostintangent ping - the 2nd proposal has been renamed to `Uri.joinPath` (no plural). I am also planning to remove the 1st proposal so let me know if you are using any of those proposal currently

**Comment by srivatsn** [comment]
We are using `asExtensionUri`. @rodrigovaras can you please make this change? @BrunoGuardia

**Comment by jrieken** [comment]
Moving to April for API feedback and finalziation

**Comment by jrieken** [comment]
@rodrigovaras @BrunoGuardia @srivatsn the old proposal is now gone, the new proposal is available and we will finalise it this month

**Comment by jrieken** [comment]
Proposal which is up for finalization:

https://github.com/microsoft/vscode/blob/c139d3bf1e829a703d7ef15e1ea41329a7d5b51f/src/vs/vscode.proposed.d.ts#L1925-L1966

**Comment by rodrigovaras** [comment]
Our code is ready to priorize the new extenion context property, thanks for letting us know.

**Comment by jrieken** [comment]
This has now been finalised

**Comment by jrieken** [comment]
To *verify* use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to fetch the latest version of `vscode.d.ts` and make sure you can use these APIs without enabling proposed API for your extension
