### ISSUE TITLE
Install extension extremely slow

### ISSUE THREAD

**Issue by xhinker** [Microsoft/vscode#9020]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. install markdownlint extension 
2. location: China mainland and HongKong

It takes almost 30 mins, and still in processing

**Comment by joaomoreno** [comment]
#7853
