### ISSUE TITLE
Emmet should not take precedence on arbitrary words-with-dashes completions

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#90206]
- VSCode Version: 1.40.0
- OS Version: Irrelevant

FYI I don't want to have to disable Emmet to prevent this, as I'm interested in trying Emmet out and I don't want it to interfere with completions from extensions.

Steps to Reproduce:

1. Install my extension: https://marketplace.visualstudio.com/items?itemName=vscodeshift.material-ui-snippets
2. Enable tab completion
3. Create a new `.tsx` file
4. Type `mui-button` and press Tab
5. It gets expanded as an Emmet abbreviation instead of the completion from my extension.

Since my extension specifically provides `mui-button`, it should take precedence.  Emmet should not take precedence on any word-with-dashes unless it's explicitly reserved.

Does this issue occur when all extensions are disabled?: Yes, because Emmet appears to be built in

**Comment by octref** [comment]
If you are talking about `mui-button` -> expanding to your snippet, currently AFAIK there's no way to do that unless you do Ctrl+Space and accept the result.

**Comment by jedwards1211** [comment]
Is "Enable tab completion" supposed to make automatically insert the best matching completion when I press tab, or is it something else?

**Comment by octref** [comment]
Emmet does not load your snippets.

**Comment by jedwards1211** [comment]
Perhaps I haven't made myself clear.  I'm talking about **Editor: Tab Completion**, not the Emmet setting.

![image](https://user-images.githubusercontent.com/1448194/74801409-1346bc00-529c-11ea-9b5a-19ca3e669d36.png)

As it says, it will insert the "best matching suggestion".

I don't even have the **Emmet: Trigger Expansion On Tab** setting checked.  But it doesn't matter because Emmet's suggestion is at the top of the list:

![image](https://user-images.githubusercontent.com/1448194/74801427-26f22280-529c-11ea-85fd-888c1460b6ae.png)

Emmet is obviously providing a completion item for any arbitrary word-with-dashes, and that completion item winds up at the top of the list.  I want Emmet to either stop providing completion items for arbitrary words it has no a priori knowledge of, or ensure that such items will be way lower in the list.

Is this finally clear?

**Comment by octref** [comment]
So you are asking emmet to be first when it's `div`, but not `mui-button`?

But even if Emmet could do that (it can't yet), your snippets would show below the various button in this case. `button` but not `mui-button` is considered a word and used for matching completion items here.

One solution is you can set this for your filetype:

```json
{
  "emmet.showExpandedAbbreviation": "never"
}
```

So

**Comment by jedwards1211** [comment]
Right emmet has a priori knowledge of `div` and probably a lot of other specific things but not `mui-button` for example.

> button but not mui-button is considered a word and used for matching completion items here

Okay, so it's hard to tell what the convention is for snippet names, but one example in https://code.visualstudio.com/docs/editor/userdefinedsnippets is `for-const`, so it seems like maybe what the editor chooses for matching completion items should be different?  But if camel case would work better I could use camel case.

And just to be 100% clear my extension provides completion items via the JS API which insert snippets when selected, rather than static snippets.

Does `"emmet.showExpandedAbbreviation": "never"` disable all Emmet suggestions?  I don't use Emmet right now so it's fine for me, I just wanted to bring this issue up because it would be nice if people using my extension can get the best experience without disabling Emmet.

**Comment by jrieken** [comment]
> Emmet is obviously providing a completion item for any arbitrary word-with-dashes, and that completion item winds up at the top of the list. 

Yes - that the design of emmet (and afaik the value proposition of emmet). You have to disable emmet inside auto complete or not use tab completion - there is no other alternative

**Comment by jedwards1211** [comment]
> and afaik the value proposition of emmet
I question this.  Abbeviation examples on Emmet's website use well-known HTML tag names.   It would be completely reasonable for Emmet to continue to provide completions for other arbitrary tag names but to deprioritize them if they don't contain HTML tag names

**Comment by jedwards1211** [comment]
In any case I imagine this is probably a low priority issue...I'd be more satisfied with a response like "well, I can see what you mean about how there's room for improvement in the ability to use tab completion for extensions together with Emmet, but there's too many higher priority things we have to deal with right now".

Because I'm sure you'd agree that Emmet shouldn't dominate *literally all tab completions* AFAICT when it's enabled?
