### ISSUE TITLE
Search all with CP850 encoding does not work

### ISSUE THREAD

**Issue by BriseBalloches** [microsoft/vscode#90209]
- VSCode Version:1.42.0
- OS Version: windows 10.0.15063

Steps to Reproduce:

1. Set default encoding to CP850 in the settings
2. Search all (ctrl + shift + f) in my workspace.

It starts searching and displays good results but almost instantaneously disappear to show the message "Unknown encoding : cp850". It works fine with windows1252 and UTF8 though.

Does this issue occur when all extensions are disabled?: Yes

EDIT:
I know an issue has already been opened and then closed but the problem still exists.

Thank you,

Guillaume.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/68237
