### ISSUE TITLE
Enhance the codicon reference in treeview

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#90200]
Thank you for providing the codicon reference features to the TreeView. I have some question during using it:

- Can the extension change the color of the codicon when assign it to the tree item? for example, I hope when I'm using `ThemeIcon('error')`, the icon could be red in the treeview.

- Can the codicon in the treeview applies the spin style?

**Comment by eamodio** [comment]
You can't control the color, but you can apply the `spin` style.

**Comment by jrieken** [comment]
> but you can apply the spin style.

Unfortunately not in the `ThemeIcon` - I am unsure if that should work implicitly or if it should be explicit, using another ctor-argument like modifier. 


Also adding @aeschli to this because he has ideas of making this more open for extensions, e.g adding more icons

**Comment by aeschli** [comment]
Colors always have to come from the color theme and are not part of the icon.
We should add a color property to the `TreeItem` with type `ThemeColor`.
Examples for that are the icon colors we have already added. See https://code.visualstudio.com/api/references/theme-color#symbol-icons

**Comment by aeschli** [comment]
The ThemeIcon now allows to specify a color: https://github.com/microsoft/vscode/issues/103120

**Comment by jdneo** [comment]
Thank you, @aeschli. Will VS Code team considering also adding the spin style to `ThemeIcon`?

**Comment by aeschli** [comment]
@jdneo No plans at the moment as I'm not aware of much demand for that feature. But please file a separate issue just for that request.
