### ISSUE TITLE
vscode always crashes when I close the debug terminals

### ISSUE THREAD

**Issue by Pudron** [microsoft/vscode#90205]
Maybe it is a bug.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please include platform and version information, plus repro steps. Also confirm whether it occurs if you run with all extensions disabled.

**Comment by Pudron** [comment]
* version:1.42.0
* platform:windows10
* extension:C/C++,C++ intellisense
There no problems when I run without all extensions.
After lanuching the debugging,I closed the automatically opened task terminal and debug terminal by the icon 'bin'.But it crushed.
