### ISSUE TITLE
January 2020 Recovery Endgame

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90202]
- [x] Create a milestone `January Recovery 2020` **owner**
- [x] Bump the version number **owner**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22January+2020+Recovery%22)
- [ ] Include an issue 'update translations' **owner**
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [ ] Make rpm signing request **@Tyriar**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - **@bpasero**
  - [x] OS X - **@weinand**
  - [x] Linux - **@isidorn**
- [x] Sanity check of installable bits
  - [x] Windows 32 bit **@bpasero**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit **@@bpasero**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] OS X - **@weinand**
  - [x] Linux
    - [x] deb package 64-bit **@isidorn**
    - [x] rpm package 64-bit **@jrieken**
    - [x] archives **@jrieken**
	- [x] snap @joaomoreno 
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers)) **@sandy081**
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [ ] Publish rpm to repository manually **@Tyriar**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z`

**Comment by gulshan** [comment]
I think new milestones are needed for recovery versions. Same monthly milestone can be used for this.

**Comment by sandy081** [comment]
@egamma This is for recovery milestone.
