### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by ewantowie** [microsoft/vscode#90219]
Issue Type: <b>Performance Issue</b>

After using a workspace for a period of time I find that VSCode starts to become very unresponsive. Exitting the application and reloading the workspace resovles the issue for a short period. Typically it takes a few hours of workspace usage for this to occur.

From using the Process Explorer I see that window ( <my workspace name> - Visual Studio Code) is consuming 3-4% of CPU which corresponds to a single core on my 28-core workstation. This follows with the top output at the terminal that shows (one of) the code processes consuming 100% of a core.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 3.10.0-957.5.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (28 x 2399)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|251.63GB (142.88GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	     0	 11080	code main
    0	     0	 11082	   zygote
    0	     0	 11102	   gpu-process
    0	     0	 11235	   shared-process
    0	     0	 35895	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 11938	   window (Process Explorer)
    0	     0	 35530	   window (Issue Reporter)
    0	     0	 35896	   /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    3	   515	 60779	   window (● BTEScatteringAssembler.cc - banditDevel (Workspace) - Visual Studio Code)
    0	     0	 60806	     extensionHost
    0	   773	 60868	       /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0	     0	 60843	     watcherService
    0	     0	196242	     searchService
    0	   258	174042	   window (Device.cc - banditDebug (Workspace) - Visual Studio Code)
    0	     0	174070	     extensionHost
    0	   258	174126	       /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0	   258	185343	         /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 174126 5
    0	   773	191395	         /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 174126 6
    0	     0	174105	     watcherService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● BTEScatteringAssembler.cc - banditDevel (Workspace) - Visual Studio Code)
|  Window (Device.cc - banditDebug (Workspace) - Visual Studio Code)
|    Folder (bandit): 2610 files
|      File types: tdr(433) plt(264) log(257) o(234) testdef(177) dat(152)
|                  tcl(128) hh(124) cc(109) cmd(100)
|      Conf files: tasks.json(1)
|    Folder (bandit): 3146 files
|      File types: tdr(423) log(342) o(329) plt(264) testdef(177) testlog(173)
|                  xml(173) dat(132) tcl(125) hh(124)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg(2);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
togglehs|bbe|0.1.2
vscode-boost-jam|mlo|0.0.2
cpptools|ms-|0.26.3
tcl|sle|0.2.0
perforce|sle|3.2.0

</details>

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by ewantowie** [comment]
Ok, I did some google searching and realised that I had defined a circular link within the include path setting for the Intellisense engine. I've removed the circular path and it has removed the periodic slowdown I had in VSCode.

I'm not sure if this is only limited to the C/C++ plugin, but that is where the include path setting resides that was causing me problems.

E.g. in the include setting I had
```
${workspaceRoot}/**
/home/ewan/workspace/**
```
where `${workspaceRoot}` is within `/home/ewan/workspace/`

**Comment by bpasero** [comment]
Ok good. Circular links on disk can produce issues.

**Comment by ewantowie** [comment]
It seems that the issue hasn't disappeared, it just takes longer to appear. Below is the output from the `code --status` command:

code --status
Version:          Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS Version:       Linux x64 3.10.0-957.5.1.el7.x86_64
CPUs:             Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (28 x 2400)
Memory (System):  251.63GB (97.82GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox
GPU Status:       2d_canvas:                     unavailable_software
                  flash_3d:                      disabled_software
                  flash_stage3d:                 disabled_software
                  flash_stage3d_baseline:        disabled_software
                  gpu_compositing:               disabled_software
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        disabled_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  disabled_software
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         unavailable_software
                  webgl2:                        unavailable_software

CPU %   Mem MB     PID  Process
    0        0   11080  code main
    0        0   11082     zygote
    0        0   11102     gpu-process
    0        0   11235     shared-process
    0        0  114901       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0      258   29744     window (● kdTree_RosettaCode.cc - Visual Studio Code)
    0        0   29794       extensionHost
    0        0   29956         /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0        0   30007           /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 29956 0
    0        0   30130       /bin/bash
    0        0  154950     window (dfdcubicspline_interp.c - mkl_datafittingc (Workspace) - Visual Studio Code)
    0        0  154978       extensionHost
    0        0  155031         /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0        0  155145           /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 155031 0
    0        0  155214           /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 155031 1
    0        0  155013       watcherService
    0      258  158108     window (Jamroot.installation - banditDevel (Workspace) - Visual Studio Code)
    0        0  158135       extensionHost
    0      773  158188         /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0        0  158169       watcherService
    3     1031  174042     window (Device.hh - banditDebug (Workspace) - Visual Studio Code)
    0        0  174070       extensionHost
    0     1546  174126         /u/etowie/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0        0  174105       watcherService

Workspace Stats:
|  Window (Jamroot.installation - banditDevel (Workspace) - Visual Studio Code)
|  Window (dfdcubicspline_interp.c - mkl_datafittingc (Workspace) - Visual Studio Code)
|  Window (Device.hh - banditDebug (Workspace) - Visual Studio Code)
|    Folder (datafittingc): 105 files
|      File types: c(45) out(19) res(18) csv(9) inc(3) lst(1) dat(1) json(1)
|                  cc(1) hh(1)
|      Conf files: makefile(1)
|    Folder (bandit): 2944 files
|      File types: o(465) tdr(435) plt(264) log(257) testdef(177) dat(152)
|                  tcl(128) hh(127) cc(111) cmd(100)
|      Conf files: tasks.json(1)
|    Folder (bandit): 3750 files
|      File types: o(563) log(551) tdr(445) plt(278) testdef(177) testlog(172)
|                  xml(172) dat(162) tcl(125) hh(124)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg(2)

**Comment by ewantowie** [comment]
@bpasero Could you reopen this issue?

**Comment by bpasero** [comment]
@ewantowie looks like the C++ extension, does it reproduce if you uninstall that extension or disable it?

**Comment by ewantowie** [comment]
@bpasero Let me try and get back to you, although it may take a few days of use. I'll post an update here when I have an anser.
