### ISSUE TITLE
Sort files and folders in Explorer in case-sensitive mode

### ISSUE THREAD

**Issue by Jonathan0wh** [microsoft/vscode#90217]
Now VScode could already config 5 ways to sort files and folders in Explorer:

| | |
| - | - |
| ![VScode setting](https://i.ibb.co/k1p1krz/Screen-Shot-2020-02-07-at-9-53-11-pm.png) | ![Folder Structure](https://i.ibb.co/hFyXtKS/Screen-Shot-2020-02-07-at-9-54-50-pm.png)

But these files and folders are sorted in case-insensitive alphabetical order. Is it possible to add a case-sensitive setting or option to allow the files and folders to be sorted in case-sensitive alphabetical order, like the default way in Github here:

![Github way of sorting files and folders](https://i.ibb.co/mbmvQ3k/Screen-Shot-2020-02-07-at-9-55-03-pm.png)

**Comment by Jonathan0wh** [comment]
I already checked the related feature request #43889 and #41351, and my point of case-sensitive sorting was not covered by them yet. This feature request is more like an enhancement to the function required in those two.

**Comment by isidorn** [comment]
Please comment on #41351 as if we ever improve file explorer sorting we would like to do it as part of that feature request and we would like to have all the data in one place. Thank you. Closing this as duplicate
