### ISSUE TITLE
Copy file `foo.spec.js` in same dir as `foo.spec copy.js` seems wrong

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#90212]
I write lots of test at work and at home and this feature really bugs me. I was even forced to extend one of my extensions so I don't rely on proper copy of file.

Feel free to ignore it, as that won't stop me using VSCode, but if you need my spec suggestion, it would be any of:

- foo.spec.js => foo1.spec.js

- foo.spec.js => foo copy.spec.js

- foo.spec.js => foo_copy.spec.js

**Comment by isidorn** [comment]
@selfrefactor Please use this setting `"explorer.incrementalNaming": "smart"`.
Also we accept prs which would fix the corner case you are hitting. 

Code pointer
https://github.com/microsoft/vscode/blob/bc61602b8591e5c42e6a21adad3d912777085ee3/src/vs/workbench/contrib/files/browser/fileActions.ts#L366

**Comment by selfrefactor** [comment]
I will try to add a PR for that. Thank you @isidorn for pointing to the file related to this feature.

**Comment by isidorn** [comment]
Thanks. Also make sure to also add a unit test here
https://github.com/microsoft/vscode/blob/93e0c1481de388189c5430f22fe32dd16ae64cb5/src/vs/workbench/contrib/files/test/browser/fileActions.test.ts#L1

**Comment by selfrefactor** [comment]
Feel free to close it, as I am unable to install VSCode deps on Ubuntu19.10

`
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
`

and therefore I am unable to run the tests for the `incrementFileName` module.

**Comment by isidorn** [comment]
Try this
`scripts/tests.sh -f "Files"`

**Comment by selfrefactor** [comment]
I thank you for the effort to help me out, but I am still doing something wrong.

I create bad assertion in `fileActions.test.ts` and I do:

1. cd `scripts`
2. `./test.sh`

It runs lots of tests but I don't see a failing test at the end. 

If I run `./test.sh -f "ABSOLUTE_PATH_TO_TEST_FILE"` it does nothing.

**Comment by isidorn** [comment]
How about if you just literally run what I mentioned in the previous comment
`scripts/tests.sh -f "Files"`

-f does glob mathicn, and the "Files" should glob mathc for that unit test

**Comment by selfrefactor** [comment]
Yes, that works. Now if I leave only one spec in the test file, this is not reflected when I run the command. It is like I am missing a build step.

**Comment by selfrefactor** [comment]
I am closing this issue, as on clean Ubuntu 19.10 I cannot pass `yarn i` and therefore I cannot run the unit tests. I'd suggest improvement of unit test readme as instructions seems insufficient.
