### ISSUE TITLE
Inconsistent GUI behavior when tasks are defined in user settings.json and project launch.json

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#90216]
- VSCode Version: 1.42.0, 1.43.0 insiders
- OS Version: Windows 10

Steps to Reproduce:
1. Have a launch configuration A in your users `settings.json`.
2. Have an additional `.vscode\launch.json`, holding another configuration B, in your project folder.

First problem
-
In "Run and Debug", clicking "Open launch.json" while having configuration A selected opens "Settings" instead. I see where this is coming from, but the hover text of the button does not match its behavior.

Second problem
-
While having launch config A selected in "Run and Debug", changing any configuration (either A in `settings.json` or `B` in `.vscode\launch.json`), results in configuration B being selected in "Run and Debug". (Note that it is not enough to simply re-save these files - you actually have to make a meaningful, non-whitespace edit within a launch configuration to trigger refresh of the launch config selection. It does *not* require *visible* a change of name/order/..., though.)

**Comment by jeremy-w** [comment]
I was thoroughly perplexed by this just recently. It would have been a substantial improvement to have the opened settings.json scroll to the "launch" key in the file. As it stands, it opens to the top of the file, and if you have a lot of config, the "launch" key might not be at all in sight.
