### ISSUE TITLE
Stop on Breakpoint doesn't work after 1.42 update

### ISSUE THREAD

**Issue by daniell0gda** [microsoft/vscode#90211]
Hey

A I have my protractor lunch configuration configured like that: 

            "name": "Launch potractor",

            "type": "node",

            "autoAttachChildProcesses": true,

            "showAsyncStacks": true,

            "sourceMaps": true,

            "request": "launch",

            "program": "c:/Users/feren/AppData/Roaming/npm/node_modules/protractor/bin/protractor",

            "stopOnEntry": true,

            "smartStep": true,

            "args": ["${workspaceRoot}/e2e/protractor.conf.js", "--suite", "precise"],

            "outputCapture": "console"

And now after lunching, breakpoint is not catched - like sourcemaps wouldn't be there.
Don't work both on typescript&javascript file.

OS: windows 10

**Comment by daniell0gda** [comment]
it started to working..what Have I done? 😕

**Comment by eamodio** [comment]
If it comes back, please open another issue. Thanks!
