### ISSUE TITLE
Editor: Selecting text automatically calls copy

### ISSUE THREAD

**Issue by tomaszhlawiczka** [microsoft/vscode#90222]
Issue Type: <b>Bug</b>

Selected text is always copied, even without coping it.

1) Open any code file: jsx, bash script, scss etc
2) Select text using a keyboard or a mouse (do not call copy, just select it)
3) Paste system clipboard (ctrl+v) - pasted fragment is a previously selected text, but instead a explicitly copied content should be used

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 5.4.18-gentoo
Remote OS version: Linux x64 4.15.0-76-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 3806)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.31GB (24.10GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.207.3|
|OS|Linux x64 4.15.0-76-generic|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz (8 x 3792)|
|Memory (System)|39.29GB (11.67GB free)|
|VM|100%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
material-icon-theme|PKi|3.9.2
mako|tom|0.2.0
yandex-translate|air|1.0.5
Bookmarks|ale|10.7.0
pgformatter|bra|1.11.0
vscode-eslint|dba|2.0.15
githistory|don|0.4.17
gitlens|eam|10.2.0
vscode-google-translate|fun|1.4.2
todo-tree|Gru|0.0.167
beautify|Hoo|1.5.0
python|ms-|2020.1.58038
sqltools|mtx|0.21.6
vscode-extension-auto-import|Nuc|1.4.3

</details>

**Comment by gjsjohnmurray** [comment]
I think this was a recent change (#63374). See #88683 for the issue it fixed.

What is your `editor.selectionClipboard` setting?

**Comment by tomaszhlawiczka** [comment]
`editor.selectionClipboard = true`

After setting this to `false` selection works fine! Thanks!

**Comment by tomaszhlawiczka** [comment]
Yes, looks like it's dup of #88683.

**Comment by dobosgy** [comment]
If I set up `"editor.selectionClipboard": false`, I dont get the same function as in other editors on linux.
In this way I loose the excellent linux function of inserting the selection with mouse-middle-button.
If `"editor.selectionClipboard": true`, I have the mouse-middle-button insert, but not have the Shift-Insert function as usual.
It would be better to return to the former behavior, because it is a good thing, that all editors work the same on an operarting system.

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/90297#issuecomment-583779433 help you change keybindings so you can have `"editor.selectionClipboard": true` and also get `Shift+Insert` paste from the clipboard that `Control+Insert` copies a selection to?

**Comment by dobosgy** [comment]
@gjsjohnmurray Thank you, it looks like OK.
The `"editor.selectionClipboard"` is `true`, and the default `Shift+Insert` shortcut is deleted.
In this way, everything works as before.
