### ISSUE TITLE
cant't load more than one directory in the explorer

### ISSUE THREAD

**Issue by TUTUBIG** [Microsoft/vscode#9022]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:
I don't want to load it's parentdir , just load some which exsist in the  parentdir,but not all 

![image](https://cloud.githubusercontent.com/assets/13084076/16712964/95ce3888-46ca-11e6-9925-6f4c3b66d476.png)

**Comment by SangLiang** [comment]
Yes,i need this,and sublime text do better

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.
