### ISSUE TITLE
Git API log formatting error

### ISSUE THREAD

**Issue by kahole** [microsoft/vscode#90229]
- VSCode Version: 1.42.0
- OS Version: Darwin x64 19.2.0
- Git version: 2.24.1

Steps to Reproduce:

1. Make and Debug extension
2. Run git api commands, specifically `repository.log`
```
const gitExtension = extensions.getExtension<GitExtension>('vscode.git')!.exports;
if (!gitExtension.enabled) {
  throw new Error('vscode.git Git extension not enabled');
}

const gitApi = gitExtension.getAPI(1);

const repository = gitApi.repositories[0];

if (repository) {
  repository.log({ maxEntries: 10 });
}
```

Results in
```
{
  "exitCode": 128,
  "gitCommand": "log",
  "stdout": "",
  "stderr": "fatal: unrecognized argument: --format:%H\n%aN\n%aE\n%at\n%P\n%B\n"
}
```

This format option was introduced here, and seems to be the change causing the issues I'm experiencing:
https://github.com/microsoft/vscode/commit/87c2332fedc9d0ca4bcc695aa21c55d1bcaaa5b6#r37162132

**Comment by sandy081** [comment]
Reopening as it is not merged yet.
