### ISSUE TITLE
Add option to set organizeImports provider

### ISSUE THREAD

**Issue by Spenhouet** [microsoft/vscode#90221]
Currently `source.organizeImports` activates all extensions that provide this functionality.
This leads to problems like this: https://github.com/microsoft/vscode/issues/90220

I wish that similar to `python.formatting.provider` we could also set a `python.organizeImports.provider`.

This would control which extension is supposed to run the organizeImports action (and which one not).

**Comment by mjbvz** [comment]
Extensions can already provide for more scoped code actions kinds, such as `source.organizeImports.python` to support this

We could consider allowing `codeActionsOnSave` to specify which extension to use for a given on save action, the way `editor.defaultFormatter` woks

**Comment by Spenhouet** [comment]
Sounds good. That would do the job.

**Comment by copdips** [comment]
@mjbvz 
vscode 1.44 introduced [code actions order](https://code.visualstudio.com/updates/v1_44#_explicit-ordering-for-code-actions-on-save), what is the correct settings if I want to use this new feature ? The given setting example doesn't work, if I don't use your tip on `source.organizeImports.python`. The new feature even changed the type of the setting, `editor.codeActionsOnSave` was a dict before, and now it's an array.

```json
"editor.codeActionsOnSave": [
    "source.organizeImports",
    "source.fixAll"
]
```

I gave the initial import order like:
```python
import sys
import os
```

after save, vscode changed it to (it deleted import):
```python
import os
import os
```

**Comment by mjbvz** [comment]
@copdips My example was theoretical, I'm not sure it has been implemented by python

**Comment by copdips** [comment]
@mjbvz your example `source.organizeImports.python` fixed the issue. And as vscode 1.44 introduced the sorted code actions, I would like to know if we can do something with it.

**Comment by etienne-monier** [comment]
Hi, this topic is quite old.

I've got the same problem with imports like 
```
from mypackage import (
    function1,
    function2,
    function3,
    function4,
    function5,
    function6,
    function7,
    function8,
    function9,
)
```

with the configuration
```
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "--line-length",
        "80"
    ],
    "editor.formatOnPaste": false,
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "file",
    // Options for isort
    "python.sortImports.args": [
        "--settings-path=${workspaceFolder}/pyproject.toml",
    ],
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports.python": true,
        },
        "editor.rulers": [
            72,
            79
        ]
    },
```
When I save it, the import list get into line format, then comes back to column. I tried to use the `source.organizeImports.python: true` instead of ` "source.organizeImports.python": true,`, but this did not work.

Help!

**Comment by mjbvz** [comment]
Closing  due to lack of additional feedback since it was opened. Adding additional scopes to code action names can help users running into this in advanced cases
