### ISSUE TITLE
Multiple code actions conflict due to a race condition

### ISSUE THREAD

**Issue by Spenhouet** [microsoft/vscode#90220]
### Environment:
- VSCode Version: 1.42
- OS Version: Windows 10 v1809
Does this issue occur when all extensions are disabled?: No

### Issue:

This is what happens when only pressing save once (only input 1 x STRG+S):
![test](https://user-images.githubusercontent.com/7819068/74024627-90bc2380-49a2-11ea-9d80-bc2d1e9be2f5.gif)

This is due to multiple code actions running in parallel.
This is not an issue with the extensions them self (I tested them independently and they work fine), this is a VS code issue.

### Steps to Reproduce:

1. Install the `Python` and `Pyright` extensions.
    - `ms-python.python`
    - `ms-pyright.pyright`
2. Use the following VS code settings:
    ```
    {
        "editor.formatOnSave": false,
        "python.jediEnabled": false,
        "[python]": {
            "editor.codeActionsOnSave": {
                "source.organizeImports": true,
            }
        }
    }
    ```
3. Create an empty python file
4. Insert this import statement:
    ```
    from test_module import (test_method_1, test_method_2, test_method_3, test_method_4, 
                             test_method_5, test_method_6)
    ```
5. Save (STRG + S)

### Possible solution:

Code action providers should run successively.

### Others:

I want to mention that code actions and formatting also conflicts with a race condition. This should also be addressed independently and is tracked here: https://github.com/microsoft/vscode/issues/83586

**Comment by mjbvz** [comment]
This seems like the same issue as #83586 When I investigated the issue, it seems that VS Code is doing the right thing. However it is possible there is a bug in the extensions.

VS Code executes the actions in the correct order but extensions need to return a promise that tracks when they have completed editing the file. If an extension does not do this, we will try executing the next actions before the previous one completed

Please try following up with the python extensions on this. If they come back and say that VS Code really is doing the wrong thing, we will take a look.

**Comment by Spenhouet** [comment]
@mattbierner You did see that the `editor.formatOnSave` was set to `false`?

It has nothing to do with formatting. It has nothing to do with the issue you linked... in which I was also active.
Please confirm that you checked with formatting turned off.
Please reopen if closing this was a mistake.

**Comment by Spenhouet** [comment]
@mattbierner I also already did what you are asking me to do. I reported this issue on the vscode-python extension before opening this issue here, see: https://github.com/microsoft/vscode-python/issues/9889

Could you please reopen this issue?

**Comment by Spenhouet** [comment]
@mattbierner I also want to make sure that it is clear that the extensions independently work without any issues.

I checked the code of the pyright extension and it looks to me like they are returning the promise as you expect: https://github.com/microsoft/pyright/blob/master/client/src/progress.ts

So I guess we are back here. Could you please reopen.

**Comment by mjbvz** [comment]
@Spenhouet Yes. I'd really like an extension author to look at this and tell me what exactly VS Code is doing wrong here. There's are many cases where it's the extension themselves misbehaving so I'd really like to know what the issue is from the extension's point of view before diving into this

**Comment by Spenhouet** [comment]
I don't know since when this is option is available but I did see that pyright now has the option to disable their import organizer. **This does not solve the underlying issue!**
But, it is a work around. Since with the pyright import organizer disabled only one code action is active, the above mentioned issues does no longer appear.

`"pyright.disableOrganizeImports": true,`
