### ISSUE TITLE
Tabs still show with workbench.editor.showTabs = false 

### ISSUE THREAD

**Issue by pdkovacs** [microsoft/vscode#90227]
- VSCode Version:  1.42.0
- OS Version: MacOS 10.15.3 

Steps to Reproduce:

1. Set `workbench.editor.showTabs` to `false`

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/4629413/74027886-63bf3f00-49a9-11ea-816b-c0886a7660a0.png)
As you can see on the screenshot the editor tab is still displayed.

**Comment by pdkovacs** [comment]
The expected behavior is not showing the tabs.
`showTabs === true`: show the tabs
`showTabs === false`: don't show the tabs

**Comment by gjsjohnmurray** [comment]
See #33607 for an enhancement request to hide this element.

**Comment by pdkovacs** [comment]
I see this this differently from how it is perceived in #33607. I don't see this as a case for enhancement. I see this as a bug: setting `showTabs` to `false` doesn't achieve the expected behavior to any degree. The feature simply doesn't work as expected _at all_ and the introduction of this option doesn't seem to bring any enhancement/usefulness visible to the naked eyes.

What it brings is [confusion](https://stackoverflow.com/questions/48589785/vscode-showing-only-one-file-in-the-tab-bar-cant-open-multiple-files) and, in my view, this feature has a net effect of deterioration in usability. IMHO, this option should be removed (or at least no short-cut to it should be provided by default) until the intended useful feature aimed with it is actually implemented. (I ran into this issue on Mac, but right now I am on Windows and cannot see any keyboard short-cut to this option on Windows. I am not exactly sure of the situation in terms of short-cuts...)

**Comment by gjsjohnmurray** [comment]
@pdkovacs when you have more than one file open, do you see anything changing as you toggle `showTabs`?

**Comment by pdkovacs** [comment]
Yes. I can see the following abilities removed:
- changing the active document ("editor" in VSCode lingo) with a single mouse-click
- seeing a list of open documents (clicking on the tab displays only a list of _recently opened_ documents).

While the first item is a plain (and serious) loss in functionality, the second item sticks out with the confusion it creates:

When I start closing previously opened (and not yet closed) documents ("editors"), the ones still "open" keep getting revealed one by one (until I close all of them). The point being the quotes around "open":
the concept of "open"-nes 
(1) is somehow still there, but
(2) loses its well defined, widely understood original meaning of "instantaneous access regardless of their location (in the File Explorer)" and
(3) fails to get refilled with any obvious meaning.

**Comment by pdkovacs** [comment]
@gjsjohnmurray do you think a screen recording would help clarifying things up? (I would be happy to provide one.)

**Comment by gjsjohnmurray** [comment]
@pdkovacs is it a problem with terminology?

These are tabs:
![image](https://user-images.githubusercontent.com/6726799/74106977-78dfcd80-4b63-11ea-9628-ff86ff9f10bd.png)

This isn't a tab. It's the title of the editor:
![image](https://user-images.githubusercontent.com/6726799/74107016-ce1bdf00-4b63-11ea-8da9-fddc44497296.png)

When the editor content supports the breadcrumb, the title area is used for that:
![image](https://user-images.githubusercontent.com/6726799/74107046-16d39800-4b64-11ea-9b85-8c6ccaeb7fda.png)

And as you have already observed, clicking on the file name in the title area opens the quickpick for recently-opened documents.

**Comment by pdkovacs** [comment]
@gjsjohnmurray Yes, this seems to be a terminology issue, indeed. If the long tab is called _window title_, then `workbench.editor.showTabs === false` works as expected: no tab is shown (a window title is shown in place of the tab).

And I also realize that I overlooked the benefit of the breadcrumb not taking up an additional row from the editor's real estate.

Thank you for the clarification!
