### ISSUE TITLE
Order of entries in Quick View

### ISSUE THREAD

**Issue by adam-romaniuk** [microsoft/vscode#90232]
- VSCode Version: 1.42
- OS Version: Kubuntu 19.10

Steps to Reproduce:

1. Open Quick View (command palette "View: Quick Open View")

Previously that menu was ordered in a different way than after update 1.42 (same applies to current Insiders build), now extensions' entries are placed above the default ones (Explorer, Search, Source control etc.). Is there any way to use previous sorting or customize the order?

Previous version (1.41.1):
![image](https://user-images.githubusercontent.com/60779249/74032792-206acd80-49b5-11ea-834b-135b59b5493b.png)

Current version (1.42):
![image](https://user-images.githubusercontent.com/60779249/74032239-bef62f00-49b3-11ea-9cf3-d601ed26b1f0.png)

Does this issue occur when all extensions are disabled?: No (but that's not the solution)

**Comment by eamodio** [comment]
@sbatten I think this might be related to the new view work. Also note that it looks like hidden views also show up in that list.

**Comment by sbatten** [comment]
fyi @sandy081 not sure how you feel about this for the recovery. not functionally broken, but it is a regression from expected behavior.

**Comment by sandy081** [comment]
Agreed regression but not important to be a candidate for recovery.

Regarding sorting agreed that `undefined` should go at the end and panels should also be consistent.

https://github.com/microsoft/vscode/blob/7ecb3a3703202041353a72593ba502394bb38ac5/src/vs/workbench/browser/parts/panel/panelPart.ts#L398

https://github.com/microsoft/vscode/blob/7ecb3a3703202041353a72593ba502394bb38ac5/src/vs/workbench/browser/parts/sidebar/sidebarPart.ts#L224

@bpasero @isidorn  FYI

**Comment by gjsjohnmurray** [comment]
@sandy081 I foresee this regression annoying users whose muscle-memory is trained to use `Ctrl+Q` followed by a specific number of extra `Q` presses (while `Ctrl` is held down) to navigate the UI.

What is the risk of including the fix in the recovery?

**Comment by sandy081** [comment]
I see your point and will add the `candidate` tag which can be discussed in the team.

**Comment by adam-romaniuk** [comment]
> @sandy081 I foresee this regression annoying users whose muscle-memory is trained to use `Ctrl+Q` followed by a specific number of extra `Q` presses (while `Ctrl` is held down) to navigate the UI.
> 
> What is the risk of including the fix in the recovery?

That's exactly my case :) and because of this I'll just stick with 1.41 for now.

**Comment by sandy081** [comment]
Accepted for recovery.
