### ISSUE TITLE
arm64 is not supported

### ISSUE THREAD

**Issue by peter197321** [microsoft/vscode#90233]
I am  connecting to my device via VSCode I'm getting notification "Architecture arm64 is not supported"

![image](https://user-images.githubusercontent.com/46971586/74033497-8efc5b00-49b6-11ea-9e5f-6f7a02ea46b3.png)

Why? And where is getting from what extension is notifying me?

**Comment by eamodio** [comment]
That is from the `C/C++` extension (see the source in the image).
