### ISSUE TITLE
Tree view filter seems broken

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#90237]
- VSCode Version: 1.42
- OS Version: Ubuntu 18.04

Filtering the tree view seems to have some issues.

Filtering with a single 'x' works as expected:
![image](https://user-images.githubusercontent.com/376658/74040743-3a5bde80-49bc-11ea-9fa2-97dcbeeee617.png)

Adding a second 'x' does not:
![image](https://user-images.githubusercontent.com/376658/74040772-4cd61800-49bc-11ea-859e-e9ba7cfc6c72.png)

The third 'x' is OK though:
![image](https://user-images.githubusercontent.com/376658/74040875-7bec8980-49bc-11ea-9b9d-b66ea5d50a30.png)

This might be related to the fix for #89295 ?

**Comment by eamodio** [comment]
I can't seem to reproduce this.

**Comment by Gruntfuggly** [comment]
I think it might be something to do with the tree not being fully expanded. I was seeing it on my work machine, so I'll have to check it again on Monday.

**Comment by heaths** [comment]
Filtering never used to require the tree view to be expanded for me. I'm having the oppose but probably related problem where I search for a known pattern in many files that are not visible, and nothing shows up (in the screenshot below, only 1 of 3 shows up; prior to finding this issue none showed up):

![image](https://user-images.githubusercontent.com/1532486/75801962-d1ecec80-5d30-11ea-8586-ba81dbd7dbed.png)

...which brings up the other issue: it's inconsistent. If I search for "Client" - of which there are 6 matches - only one showed up.

Something is definitely broken with filtering compared to previous releases.

**Comment by alexr00** [comment]
Filtering only filters on nodes that have been expanded, since to expand all node could be a performance problem.
