### ISSUE TITLE
Cmd+Enter sometimes doesn't commit in SCM input box

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#90234]
I've been getting reports (cc @jrieken) that `Cmd+Enter` no longer commits in the SCM input box. @jrieken found out that the keybinding was being dispatched to `search.action.openInEditor`. And it indeed is:

https://github.com/microsoft/vscode/blob/1f06066a9c57b789ef3f72371dc9541387fa1d31/src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts#L170-L175

So, the only way I can see this happening is if `SearchViewFocusedKey` is erroneously set.

Having a global `SearchViewFocusedKey` is problematic and a perf issue since it requires having a FocusTracker tracking focus, which must work flawlessly. The whole point with the Context Key Service is that it operates on scoped DOM nodes. You can simply have a `SearchViewFocusedKey` key which is always `true` but set on a scoped context key service anchored on the search viewlet DOM node. That way if `Cmd Enter` is invoked when the `document/activeElement` is a descendant of the search viewlet DOM node, it will always evaluate to true.

**Comment by jrieken** [comment]
Alternatively (and maybe better) you can use the [`FocusedViewContext`](https://github.com/microsoft/vscode/blob/24de3c0faccc710b848de32af5b63f6bdaeda8e3/src/vs/workbench/common/views.ts#L378), e.g like so: https://github.com/microsoft/vscode/blob/35b26f49b7f7de8267ee34387a9df65f2942d8d3/src/vs/workbench/contrib/bulkEdit/browser/bulkEdit.contribution.ts#L167

**Comment by joaomoreno** [comment]
@jrieken I was thinking about that and how it must be implemented the same way as the current `SearchViewFocusedKey`, so it might also run into the same issues.

**Comment by jrieken** [comment]
Currently it likely is (cc @sandy081) but when all use the same content key for logical the same thing then we only need to do a solid implementation once.

**Comment by JacksonKearl** [comment]
Similar bug was fixed with #88803, maybe theres another layer of bug here. I will look in to using the scoped context keys.

**Comment by JacksonKearl** [comment]
The events that trigger `FocusedViewContext` changes also trigger `SearchViewFocusedKey` changes, per-view. But `FocusedViewContext` changes across-views overwrite each other, so there are likely cases where `SearchViewFocusedKey` is true at the same time `FocusedViewContext` is not SEARCH_VIEW_ID. 

We only use `FocusedViewContext` in one other place so I think moving to the less error-prone scoped context keys makes sense.

**Comment by sandy081** [comment]
Just FYI `focusedView` context key is also used by the extensions for their custom views and have not seen any issues yet.

I see the glitches with focus tracker so I think the right approach would be is to have consistent and reliable focus tracker

**Comment by joaomoreno** [comment]
Verified by code review and lack of issues.
