### ISSUE TITLE
'Invalid variable attributes' shows instead of variables 

### ISSUE THREAD

**Issue by Flintols** [microsoft/vscode#90238]
- VSCode Version: 1.42.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:
Have Python and Gauge loaded
1. Build Gauge .spec file, step_implement Python file with variables present.
2. Set debug start point in Python file. 
3. Run 'debug scenario' to begin spec. 
4. Local variables show up as ': Invalid variable attributes'; watches show up as 'NameError("name '(watched item)' is not defined")'

Does this issue occur when all extensions are disabled?: No, debug option disabled when Gauge unloaded, Python will not run with Python unloaded.

**Comment by Flintols** [comment]
Python version 3.7.6 32-bit
Gauge version 0.0.11

**Comment by luabud** [comment]
@Flintols I opened the issue on the Python extension repo: https://github.com/microsoft/vscode-python/issues/9982.

**Comment by gjsjohnmurray** [comment]
Probably an extension issue revealed by fix for #85645 which just landed in 1.42
