### ISSUE TITLE
ERR Unable to write to User Settings because ... is not a registered configuration.

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#90249]
Steps to Reproduce:

1. git clone https://github.com/sguillia/vscode-repro
2. cd vscode-repro
3. npm ci
4. vsce package
5. code-insiders .
6. Toggle developer tools
6. In code-insiders marketplace, Install from VSIX, select helloworld-sample-0.0.1.vsix
7. Observe the error in the console:

>  ERR Unable to write to User Settings because hello.token is not a registered configuration.: Error: Unable to write to User Settings because hello.token is not a registered configuration.

![Capture du 2020-02-07 17-42-17](https://user-images.githubusercontent.com/15984272/74047798-35edf080-49d1-11ea-8182-2690fb40ccfa.png)

The thing is, `hello.token` is a registered configuration, [right here](https://github.com/sguillia/vscode-repro/blob/master/package.json#L28)

The problem happens only when installing the extension in an already open vscode instance.
The problem does not happen when you open or reload while the extension is already installed.
The problem also happens with extensions published on the marketplace, it is not related to Installing from VSIX. (this breaks our production environment)

Version: 1.43.0-insider
Commit: beaf391bc53136912e4f0bbdfb7844ad954247db
Date: 2020-02-07T05:34:00.212Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-76-generic

**Comment by sandy081** [comment]
can you please open the extension from the extension viewlet and see if the contributions have the setting?

**Comment by sguillia** [comment]
@sandy081 It does

![Capture du 2020-02-10 16-18-26](https://user-images.githubusercontent.com/15984272/74162509-3086e500-4c21-11ea-9e48-1d4b678252aa.png)

**Comment by sandy081** [comment]
Can you also please double check by opening the settings editor?

**Comment by sguillia** [comment]
@sandy081

![Capture du 2020-02-12 17-43-19](https://user-images.githubusercontent.com/15984272/74356774-331f4100-4dbf-11ea-9d37-42ed2fa0f42b.png)

**Comment by sandy081** [comment]
I tried the sample and it worked for me. I do not see any errors. Can you please open extensions folder and check if extension you wanted is properly installed?
