### ISSUE TITLE
Debugging Python in Docker via SSH, breakpoints will not be hit

### ISSUE THREAD

**Issue by eohlde** [microsoft/vscode#90244]
Issue Type: <b>Bug</b>

-> vscode-remote ssh into ubuntu remote machine
-> docker-compose build [app]
-> docker-compose up [app]
    -> CMD python -m ptvsd --host 0.0.0.0 --port 5678 --wait server.py
-> attach debugger

I then expect the breakpoints I have defined in source (little red dots) to be stopped at. This does not happen.
-> only 'breakpoint()' will be stopped at, then any red dot breakpoints will be honored in the same .py file

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-29-generic
Remote OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (2 x 2808)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|7.78GB (2.78GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.0.1.252|
|OS|Linux x64 4.15.0-72-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz (2 x 2500)|
|Memory (System)|3.71GB (0.32GB free)|
|VM|50%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.10.0
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.41.9
vscode-remote-extensionpack|ms-|0.19.0
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038

</details>

**Comment by eohlde** [comment]
When I start the debugger, I get this in **Output -> Log (Window)**:

> [2020-02-07 11:11:31.932] [renderer5] [error] 'setBreakpoints' request must be issued after 'launch' or 'attach' request.: Error: 'setBreakpoints' request must be issued after 'launch' or 'attach' request.
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async R.sendBreakpoints (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5114:210)
    at async Y.sendToOneOrAllSessions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5146:591)
    at async Promise.all (index 0)
    at async Y.sendAllBreakpoints (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5145:441)
    at async file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5120:850

**Comment by roblourens** [comment]
Please file this on the python extension's repo first - thanks!
