### ISSUE TITLE
Add ability to use yaml, cjs, mjs settings files extentions

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/vscode#90242]
such as `settings.cjs`, `setting.mjs`, `setting.yaml`.

if we can use javascript in settings, we can import config from other file.

**Comment by xiaoxiangmoe** [comment]
BTW: should we ignore `.vscode/settings.json` in our git repo?

**Comment by roblourens** [comment]
We don't plan to support different types of settings files. I recommend checking in your `.vscode/settings.json`. Usually those are settings related to the project which are relevant for anyone working on the same project.
