### ISSUE TITLE
Line numbers invisible after Zen Mode toggled off

### ISSUE THREAD

**Issue by 10bo** [microsoft/vscode#90240]
- VSCode Version: 1.41.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Ensure you have at least one file open in editor
2. Enable Zen Mode
3. Click on a file in the Source Control tab under the *CHANGES* sub-heading to open the side-by-side diff
4. Disable Zen Mode
5. Click on the tab for the file opened in step 1 & observe the area where line numbers should appear

![image](https://user-images.githubusercontent.com/12775505/74042986-74c77a80-49c0-11ea-8488-971220c51bd6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I acknowledge this issue.
The problem is how we reset the line numbers after exiting zen mode
Code pointer https://github.com/microsoft/vscode/blob/8d17dc1e84d53f5fd4ed0d05fabaa3062259633d/src/vs/workbench/browser/layout.ts#L780

An elegant PR that fixes this is welcome.
We might also look into this in the future.

**Comment by jeanp413** [comment]
@isidorn I took a look at this and to fix this we need not just the `visibleTextEditorWidgets` but the non-visible ones too. I looked around and it seems there is no method for this in `IEditorService` or `IEditorGroupsService`
There is an array in `EditorControl` that holds the visible and non-visible editors, would it be fine to expose this variable ?
https://github.com/microsoft/vscode/blob/2175713d900c83f77df33623e3a7612c0564d0c4/src/vs/workbench/browser/parts/editor/editorControl.ts#L39

**Comment by isidorn** [comment]
@jeanp413 thanks for looking into this. That sounds reasonable. However let's check with @bpasero if he wants to expose non visible editors in the `editorService` or if he has a better suggestion for this.

**Comment by bpasero** [comment]
@isidorn `IEditorService#editors` gives access to all opened editors.

**Comment by isidorn** [comment]
Ok thanks. @jeanp413 so that + `.getControl()` should probably give you all the `editorWidgets`.

**Comment by jeanp413** [comment]
`IEditorService#editors` gives an array of `IEditorInput` which doesn't have a `.getControl()` method.
Is there a way to get a `BaseEditor` from an `IEditorInput`?

**Comment by isidorn** [comment]
I believe the Editor control only exists for the visible editors (thus we create just one editor per Group). To save on resources.
So I believe the correct way to fix this is to remember all the editors that we have hidden line numbers for, and then when bringing them back to go through those editors.

@bpasero can correct me if I am wrong. Thansk

**Comment by bpasero** [comment]
Yes, for performance reasons we only allocate 1 editor control per visible tab, not for each tab that is hidden.

**Comment by jeanp413** [comment]
I pushed 2 branches with different fixes for this issue
1. https://github.com/jeanp413/vscode/tree/zen-mode-linenumbers-1 
This branch fixes it by using a `Set` to remember all the editor we have hidden line numbers as isidorn suggested. Not sure if it's safe to call `updateOptions` on disposed editor widgets (this could happen if we have multiple editor groups and we close any of them)
2. https://github.com/jeanp413/vscode/tree/zen-mode-linenumbers-2
This branch fixes it by exposing the `controls` array in `EditorControl` and updating the `IEditorGroup` and `IEditorService` interfaces

@isidorn let me know which approach is preferred to create the corresponding PR

**Comment by isidorn** [comment]
@jeanp413 let's go with approach 1. Once you create the PR i can further comment on it. Thanks a lot!

**Comment by isidorn** [comment]
Thanks @jeanp413 for fixing this 👏
