### ISSUE TITLE
Frequent SSH disconnects and failure to reconnect without reloading window

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#90255]
I'm connected over SSH to my work machine from home, but VSCode keeps disconnecting frequently. I'm not sure if it's some timeout (never have problems with an ssh term connection) or what, but when Code tries to reconnect it fails after some time and tells me to reload the window, which works but is very disruptive.

Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Set up OpenSSH on Windows (remote machine).
2. Connect to remote host (Windows) from client (Windows).
3. Do some work, like modifying files, etc.
4. After some time, Code reports the connection was lost and tries to reconnect unsuccessfully.

Would love to provide more information if you tell me what you want me to collect.

Does this issue occur when all extensions are disabled?: No - I couldn't connect remotely, then. FWIW, very few extensions are installed in both the remote host and client.

**Comment by heaths** [comment]
I was running a timer and there doesn't seem to be any consistency in timeouts/disconnects, but I added `ServerAliveInterval` and `ServerAliveCountMax` like so to my ~/.ssh/config file and haven't experienced any disconnects for a long time:
```
Host machinename
  HostName machinename
  ForwardAgent yes
  User username
  ServerAliveInterval 30  # <-- Added this
  ServerAliveCountMax 4   # <-- Added this
```
The rest was already there, presumably added by Code.

I also updated the description to note I was connecting to an OpenSSH daemon in Windows - the built-in one - using key authentication (password auth disabled).

**Comment by roblourens** [comment]
To make sure I understand, are you saying that adding those 2 fields to your ssh config solved the issue?

**Comment by heaths** [comment]
So far, it seems that way, yes.

**Comment by roblourens** [comment]
I'm glad that worked - if you feel like investigating more, I would be curious to see the output of the Remote-SSH output channel from a time when reconnecting fails, without those additions.

**Comment by heaths** [comment]
I was planning on pasting some of that in the bug originally, but there's nothing interesting in the output, surprisingly, which is why I was figuring it was the server that disconnected me. I was thinking that maybe you could add those by default when you update .ssh/config. Thoughts?

**Comment by roblourens** [comment]
Well, I really have no clue why that would prevent you from being disconnected, so I don't want to apply it to every connection.

**Comment by heaths** [comment]
It's a matter of timeouts. Perhaps Windows SSH is unique in this matter. I will see what I can find out. What the settings do is send a ping to the server (or client) to keep the connection alive. It's not clear from initial reading into the problem if this happens by default on a regular interval but, if it does, I wonder if Windows's implementation has a different (longer?) interval that causes it to timeout. That said, when I use Windows's ssh to remote into a Windows sshd I don't see this happen, but maybe there's some timeout differences in the client code Code uses. (Just speculation.)

**Comment by opopnhwth** [comment]
I can't cennect the windows host. （vscode inside is set with official Docs）
shell returns timeout. 
how do you do?
