### ISSUE TITLE
alt+tab does not switch tabs in spite of keybindings

### ISSUE THREAD

**Issue by vict0rsch** [microsoft/vscode#90259]
- VSCode Version: 1.42.0
- OS Version: macOS 10.14.6

Following up on #44328, I can't switch tabs whereas I have the following fields in my keybindings.json:

```
    {
        "key": "alt+tab",
        "command": "workbench.action.quickOpenNavigateNextInEditorPicker",
        "when": "inEditorsPicker && inQuickOpen"
    },
    {
        "key": "shift+alt+tab",
        "command": "workbench.action.quickOpenNavigatePreviousInEditorPicker",
        "when": "inEditorsPicker && inQuickOpen"
    },    
	{
        "key": "alt+tab",
        "command": "workbench.action.openNextRecentlyUsedEditorInGroup"
    },
    {
        "key": "shift+alt+tab",
        "command": "workbench.action.openPreviousRecentlyUsedEditorInGroup"
    }
```

Basically nothing happens, it does not open an editor selector. [Full `keybindings.json` gist](https://gist.github.com/vict0rsch/adccdcd4ea9ccf477fd44258a9091f6a)

**Comment by vict0rsch** [comment]
There seems to be a mixup with `ctrl`: 

```
    {
        "key": "ctrl+tab",
        "command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "-workbench.action.openPreviousRecentlyUsedEditorInGroup"
    },
```

But this used to work fine until new release...

**Comment by danleepw** [comment]
Both keybindings are no longer working. Please fix that

**Comment by alexdima** [comment]
@vict0rsch Nothing changed in the keybinding story in this latest release, so the keybinding rules and the keybinding dispatching work exactly the same.

But those actions (`quickOpenNavigateNextInEditorPicker`, etc) might work differently now.

@bpasero giving to you to explain/investigate what is now different.

**Comment by bpasero** [comment]
Can people read https://code.visualstudio.com/updates/v1_42#_navigate-most-recently-used-editors and let me know if that helps? There were changes to commands.

**Comment by vict0rsch** [comment]
Well according to @bpasero's there was changes in the end...

It did solve my issue, replacing 

```
	{
        "key": "alt+tab",
        "command": "workbench.action.openNextRecentlyUsedEditorInGroup"
    },
    {
        "key": "shift+alt+tab",
        "command": "workbench.action.openPreviousRecentlyUsedEditorInGroup"
    }
```

by

```
    {
        "key": "alt+tab",
        "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"
    },
    {
        "key": "shift+alt+tab",
        "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"
    },
```
