### ISSUE TITLE
Cannot set PATH variable in integrated terminal

### ISSUE THREAD

**Issue by DrAndyRoid** [microsoft/vscode#90257]
- VSCode Version: 1.41. and 1.42.
- OS Version: Kubuntu 19.10

I'm not able to set the PATH variable the integrated terminal starts with. I tried several options to set the "terminal.integrated.env.linux" variable, e. g. plain setting of PATH (see below), appending PATH by using `${env:PATH}` and so on, but nothing works. After starting a new terminal, an `echo $PATH` always prints the original PATH variable as set in /etc/environment in my case.

Other shell variables are set correctly.

Steps to Reproduce:

1. Set the file "setting.json" to:
```
{
    "terminal.integrated.env.linux": {
        "PATH": "/home/test",
        "TEST_PATH": "/home/test"
    }
}
```
2. Start vscode on a linux terminal (bash):
code

3. Select Terminal-->New Terminal

4. Inside the new terminal type:
```
xxx@yyy:~$ echo $PATH
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
xxx@yyy:~$ echo $TEST_PATH
/home/test

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by DrAndyRoid** [comment]
Today I got access to a computer running the same OS. There it works as expected: The "settings.json" from above result in an error since /usr/bin is not included in the path whereas the settings below append the path correctly:
```
{
    "terminal.integrated.env.linux": {
        "PATH": "${env:PATH}:/home/test",
        "TEST_PATH": "/home/test"
    }
} 
```

On my computer, however, both settings-files do **not** produce an error but do **not** change my PATH variable.

**Comment by Tyriar** [comment]
This is by design, I believe what is happening is your shell is finding PATH is broken so it reinitializes is. I can reproduce it and that's what happens on my Debian box.
