### ISSUE TITLE
ripgrep: yarn install fails if run in a directory with spaces

### ISSUE THREAD

**Issue by richard-townsend-arm** [microsoft/vscode#90258]
- VSCode Version: master (b98f647)
- OS Version: Windows 10

Steps to Reproduce:

1. "git clone" vscode into a directory which contains spaces in its name (e.g. "C:\scripts\VsCode Test\vscode")
2. "yarn install"

<pre>
Downloading ripgrep failed: Error: Command failed: powershell -ExecutionPolicy Bypass -Command Expand-Archive -Path C:\Windows\TEMP\vscode-ripgrep-cache-1.5.7\ripgrep-v11.0.1-2-i686-pc-windows-msvc.zip -DestinationPath C:\Program` Files (x86)\Jenkins\workspace\vscode-master\node_modules\vscode-ripgrep\bin -Force
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:144
+ ... 6-pc-windows-msvc.zip -DestinationPath C:\Program` Files (x86)\Jenkin ...
</pre>

Does this issue occur when all extensions are disabled?: n/a

**Comment by roblourens** [comment]
Oops, that will happen if there is more than one space in the destination path.
