### ISSUE TITLE
Application keeps pausing for debugger on start

### ISSUE THREAD

**Issue by dancrumb** [microsoft/vscode#90251]
Issue Type: <b>Bug</b>

My "API Server" launcher keeps pausing at startup on a line without a breakpoint.

I can't figure out why or how to even go about debugging this. When I click the Play button, everything continues fine, but it doesn't make sense and is frequently disruptive to my workflow.

Thanks!

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 5|
|Memory (System)|16.00GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
jsrefactor|cms|2.20.5
githistory|don|0.4.17
es7-react-js-snippets|dsz|2.5.0
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
vscode-mocha-test-adapter|hbe|2.2.2
vscode-test-explorer|hbe|2.15.0
vscode-styled-components|jpo|0.0.28
vscode-colorize|kam|0.8.15
vscode-commitizen|Kni|0.8.4
vscode-docker|ms-|0.10.0
vscode-postgresql|ms-|0.2.0
remote-containers|ms-|0.101.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
vscode-jest|Ort|3.1.1
vscode-coverage-gutters|rya|2.4.3
vscode-javascript-booster|sbu|0.11.0
gitblame|wad|3.0.1

</details>

**Comment by dancrumb** [comment]
Launch configuration:
```
{
      "type": "node",
      "request": "launch",
      "name": "API Server",
      "args": ["${workspaceFolder}/src/server.ts"],
      "console": "integratedTerminal",
      "runtimeArgs": ["-r", "ts-node/register", "-r", "tsconfig-paths/register"],
      "env": {
        "RAVEN_ENVIRONMENT": "local",
        "NODE_ENV": "local",
        "AWS_REGION": "us-west-2",
        "LOG_LEVEL": "debug"
      }
    },
```

**Comment by roblourens** [comment]
What is the pause reason shown above the callstack? Is it pausing on an exception?

Also, the experimental new js debugger works better with ts-node and you might want to try it out to see if it fixes your issue. See the steps here: https://github.com/microsoft/vscode-js-debug

**Comment by dancrumb** [comment]
It says "Paused on Debugger Statement"

However, it's stopped on line 2 of one of my source files that begins:

```
import {config} from 'dotenv';
import {resolve} from 'path'; // paused here...
import {apiApp} from './api';
import {connection} from './connection';
import {DbProvider} from './dbProvider';
import {logger} from './logger';
```

**Comment by dancrumb** [comment]
The new debugger seems to be working, although it has a few teething issues of its own.

**Comment by connor4312** [comment]
Please open any issues you run into with the new debug on [its repo](https://github.com/microsoft/vscode-js-debug)!

**Comment by roblourens** [comment]
Great - if the new one has solved this issue then let's stick with that and we'd like to hear about any issues you see with it like Connor said.
