### ISSUE TITLE
Allow extensions to contribute a command to viewContainer title bar

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode#90268]
Rather than contribute a command at the "view" level which is possible today, we want to contribute a command at the "viewContainer" level. In our scenario, we're trying to clean up duplicate subscription nodes in the Azure views:
![Screen Shot 2020-02-07 at 4 31 02 PM](https://user-images.githubusercontent.com/11282622/74075710-c3791280-49c8-11ea-9283-80bf2460fee2.png)

I would love to have a dropdown that shows the current subscription, but would also settle for a simple button:
![Screen Shot 2020-02-07 at 4 33 01 PM](https://user-images.githubusercontent.com/11282622/74075620-2cac5600-49c8-11ea-9f93-185b715f8fe9.png)  ![Screen Shot 2020-02-07 at 4 36 26 PM](https://user-images.githubusercontent.com/11282622/74075629-36ce5480-49c8-11ea-91bb-e26faca060a0.png)

It seems like other viewContainers not contributed by extensions already support this, like Debug and Remote:
![Screen Shot 2020-02-07 at 4 04 25 PM](https://user-images.githubusercontent.com/11282622/74074757-68452100-49c4-11ea-8840-8c9ebc3fee5f.png)
![Screen Shot 2020-02-07 at 4 25 32 PM](https://user-images.githubusercontent.com/11282622/74075283-8c096680-49c6-11ea-84f8-154a17485e64.png)

cc @fiveisprime

**Comment by misolori** [comment]
We also have https://github.com/microsoft/vscode/issues/89243 regarding using the dropdown in the sidebar header

**Comment by gjsjohnmurray** [comment]
#110218 would combine well with this, allowing a contributed command to produce a submenu of your subscriptions. So you may like to upvote it.

**Comment by gplumb** [comment]
How can we go about re-opening this issue?

**Comment by gjsjohnmurray** [comment]
@gplumb if #108271 makes some progress perhaps it will get generalized beyond just the Explorer.

cc @eamodio @isidorn

**Comment by sandy081** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
