### ISSUE TITLE
Add option to turn off decorations in overview ruler

### ISSUE THREAD

**Issue by Guptajakala** [microsoft/vscode#90263]
I'm meeting the same issue with this
https://stackoverflow.com/questions/46797701/what-do-the-grey-marks-in-the-visual-studio-scroll-bars-indicate

From the answers, it seems to be some annotations to show the locations of suggestions for code fixes. However, the gray markers are kind of annoying, distracting me from other annotaions I care about (e.g. changes to the code). 

Could you guys please add an option to turn off ONLY this gray markers? I don't need those suggestions for code fixes at all. Thanks in advance!

**Comment by mjbvz** [comment]
@RMacfarlane Maybe you know who owns the overview ruler?

**Comment by Guptajakala** [comment]
@mjbvz I think recently what I meet arises from the extension "todo tree" when I mark somewhere TODO. But is there a way to disable all these kind of annotations on scroll bar somewhere in VSCode? Because I have also met some markers like this some time ago coming from VSCode's suggestions not 3rd party extensions.

**Comment by RMacfarlane** [comment]
Hmm, I'm also not sure who owns the overview ruler.

@Guptajakala Unfortunately, I don't think there's a current setting to disable all decorations in the overview ruler. I'll mark this as a feature request

**Comment by zyy7259** [comment]
Hi, I want to know how do I upvote this issue?

I didn't find a upvote button in [Backlog Candidates](https://github.com/microsoft/vscode/milestone/107) or [Issues Triaging](https://github.com/microsoft/vscode/wiki/Issues-Triaging#our-triaging-flow)

**Comment by RMacfarlane** [comment]
Hi @zyy7259, to upvote the issue, please react with a 👍 on the first message in this issue
