### ISSUE TITLE
Restore previously opened, SAVED files when open a file from Windows File Explorer

### ISSUE THREAD

**Issue by DoCode** [microsoft/vscode#90261]
### Steps to reproduce

1. VS Code settings:

   ```json
   . . .
   "files.hotExit": "onExitAndWindowClose",
   "window.restoreWindows": "all",
   . . .
   ```

2. Open VS Code
3. Open any existing file from your disk
4. Create a new Tab in VS Code and type anything
   _(Do **NOT** save this work!)_
5. Exit VS Code
6. Go to Windows File Explorer and open any existing file from your Disk
   _(Windows File Explorer -> Select a file -> right-click -> open in VS Code!)_

### Expected behavior

**Opened tabs in VS Code:**

- Existing file from Step 2 _(Steps to reproduce)_
- New, not saved, file from Step 3 _(Steps to reproduce)_
- Existing file opened with Windows File Explorer from Step 5 _(Steps to reproduce)_

### Actual behavior

**Opened tabs in VS Code:**

- New, not saved, file from Step 3 _(Steps to reproduce)_
- Existing file opened with Windows File Explorer from Step 5 _(Steps to reproduce)_

### Environment data

- VSCode Version: 1.42.0
- OS Version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/14675
