### ISSUE TITLE
The "Copy Value" selection in debugger is always grayed out and unusable

### ISSUE THREAD

**Issue by djangofan** [microsoft/vscode#90260]
The "Copy Value" right-click selection in the debugger is always grayed out and unusable.

Previously closed related issue: https://github.com/microsoft/vscode/issues/67047

VSCode version:
> Version: 1.42.0
> Commit: ae08d5460b5a45169385ff3fd44208f431992451
Also tested on 1.41.x
- Mac OSX Mojave

Steps to Reproduce:

1. Download my sample project:  https://github.com/djangofan/karate-api-sample
2. In VSCode, install the VSCode debugger plugin and Cucumber plugin
3. I include a debug runtime .vscode/launch.json in the above mentioned github repo
4. Put breakpoint on line 18 of this file: https://github.com/djangofan/karate-api-sample/blob/master/src/test/java/features/jph/getalltodos.feature
5. When debugger stops on that line, you will NOT be able to "Copy Value" from the debugger stack list.

Does this issue occur when all extensions are disabled?  
    Unable to reproduce since my Debug session relies on the debugger/Karate plugin

**Comment by isidorn** [comment]
Please file this issue against the karate debugger which you are using as the debugger.
Tell them they need to provide the `evaluateName` property for the variables (in case you are talking about the Copy Value in the VARIABLES view).
VS Code uses this property to properly evlauate the variable which it will copy with that command.
