### ISSUE TITLE
Can't get VSC to switch to/open the files for the Repo open in GitHub Desktop

### ISSUE THREAD

**Issue by madehmer** [microsoft/vscode#90264]
Issue Type: <b>Performance Issue</b>

VSC is stuck in the wrong repo and is not synching with GitHub Desktop. I've checked for updates in both apps, rebooted my computer, and closed and reopened the apps, and signed in and out of GitHub, and so far not working. Selecting "Open in VSC" from Desktop app does nothing now. 

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    75	 13648	code main
    0	   128	 10076	   window (microsoft-graph-docs - Visual Studio Code)
    0	    14	  4264	     watcherService 
    0	    11	 10480	       console-window-host (Windows internal process)
    0	    68	 11412	     extensionHost
    0	    36	 13812	       electron_node server.js 
    0	    14	 11608	   electron-crash-reporter
    0	   109	 13580	   gpu-process
    3	    64	 14228	   window (Issue Reporter)
   82	    68	 14740	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (microsoft-graph-docs - Visual Studio Code)
|    Folder (microsoft-graph-docs): 16073 files
|      File types: md(15809) png(135) svg(27) PNG(13) json(12) yml(11) jpg(3)
|                  ps1(2) gitattributes(1) gitignore(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.34.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.6
docs-images|doc|0.0.4
docs-markdown|doc|0.2.44
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.38
docs-yaml|doc|0.2.4
vscode-yaml|red|0.6.1
code-spell-checker|str|1.7.22

</details>

**Comment by eamodio** [comment]
When you say not sync'ing with GitHub desktop -- what do you mean? As far as I know there isn't any integration between the 2 apps except for GitHub desktop being able to open vscode. Was what you are expecting working before the 1.42 upgrade?
