### ISSUE TITLE
Debugger Panel Header Arrangement Options (Suggestion)

### ISSUE THREAD

**Issue by ivanthewebber** [microsoft/vscode#90275]
The header of the debugger panel shares space with the launch selector and icons for debugging settings and console.

Notice how cramped this region is (I can't see the title of the selected launch).

![Screenshot (108)](https://user-images.githubusercontent.com/42590900/74078684-90e01180-49ea-11ea-908a-f63f07518598.png)

The header and icons are consistent with other panels, but the selector simply doesn't have enough space. Instead it should be dropped to a new line, thus enhancing readability and visual appeal.

For visualization purposes I edited the below screenshot to display the way I envision. Honestly it has a little too much space, but perhaps you can see what I'm talking about.
 
![Screenshot (111)](https://user-images.githubusercontent.com/42590900/74078877-15339400-49ed-11ea-8b05-3ebb887fccda.png)

Ideally this could be an optional setting (compact vs. cozy (could space be allocated based on an individual's usage patterns?)).

**Comment by isidorn** [comment]
This is a fair feature request. However putting it in a new line makes sense while you are not debugging, but as soon as you start debugging there are a 4 views with useful information, and all the vertical space is necessery to convery all these information.
I would prefer to just have a shorter title, for example "Run" instead fo "Run And Debug".

Thus leaving this open for now and we might address it in the future.

**Comment by isidorn** [comment]
We have renamed the viewlet title to be just RUN. So there should be more space.
Thus closing this as will not fix, as now the situation should be a bit better.
