### ISSUE TITLE
It should be possible to relaunch compound debug configs and relaunch/re-attach to only the missing subset of processes

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#90271]
Issue Type: <b>Feature Request</b>

I'm extensively using the multi-process debugger features in vscode to connect to chrome, multiple rails server's, and multi background job workers at the same time.

Because of the way my infrastructure works -- the debug configs for the server processes are all 'attach' based rather than launch based.  Whenever any of these processes dies some external-to-vscode infrastructure ensures they are relaunched in a mode where they are waiting for debugger connections.

Sometimes one of these processes dies or I have some other need to restart a subset of the processes (maybe to pickup a code change).  Ideally I could 'relaunch' the compound debug config -- vscode would see that a subset of the processes are still attached in vscode and then only re-attach/relaunch the missing subset.  

The current behavior in this scenario is that I get an error dialogue saying that the debug config is already in launched.  

<img width="490" alt="image" src="https://user-images.githubusercontent.com/434034/74078235-e31e3400-49e4-11ea-89d5-62f7f7880cef.png">

Its possible for me to identify the missing subset, switch debug configs, and reconnect to only that subset -- however this is extremely fiddly and annoying -- and vscode already knows which of the processes in the debug config its not connected to -- so it _ought_ to be able to reconnect/relaunch _just the missing_ processes specified by the compound config ...

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

**Comment by isidorn** [comment]
This is a fair feature request. And we are open to adding it in the future.
For now leaving a code pointer in case somebody is interetsted in providing a PR
https://github.com/microsoft/vscode/blob/4d3d0036f838dc8d252de66e154ba1d67e7c3e6a/src/vs/workbench/contrib/debug/browser/debugService.ts#L284
