### ISSUE TITLE
Typescript language service crashing

### ISSUE THREAD

**Issue by delfuego** [microsoft/vscode#90272]
I'm getting regular popups in the lower right that read "The Typescript language service died 5 times right after it got started. The service will not be restarted."

I'm not sure how to debug this, or what is happening; it's new as of today (when I was automatically updated to the latest VSCode version).

<img width="1904" alt="Screen Shot 2020-02-07 at 10 06 42 PM" src="https://user-images.githubusercontent.com/550511/74078294-aa875600-49f6-11ea-9699-28985275919b.png">

Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 10, 8, 6
Memory (System) | 32.00GB (0.41GB free)
Process Argv | .
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
Handlebars | and | 0.4.1
npm-intellisense | chr | 1.3.0
systemd-unit-file | coo | 1.0.6
vscode-eslint | dba | 2.0.15
FreeMarker | dco | 0.0.9
xml | Dot | 2.5.0
gitlens | eam | 10.2.0
vscode-html-css | ecm | 0.2.3
vscode-npm-script | eg2 | 0.3.11
prettier-vscode | esb | 3.20.0
code-runner | for | 0.9.15
beautify | Hoo | 1.5.0
rest-client | hum | 0.23.1
vscode-random | jre | 1.6.1
rainbow-csv | mec | 1.5.0
vscode-docker | ms- | 0.10.0
mssql | ms- | 1.8.0
remote-containers | ms- | 0.101.0
remote-ssh | ms- | 0.49.0
remote-ssh-edit | ms- | 0.49.0
remote-wsl | ms- | 0.42.3
vscode-remote-extensionpack | ms- | 0.19.0
vsliveshare | ms- | 1.0.1510
debugger-for-chrome | msj | 4.12.6
hl7 | pbr | 0.0.12
logstash | Ran | 0.0.4
java | red | 0.55.1
vscode-yaml | red | 0.6.1
code-settings-sync | Sha | 3.4.3
vscode-maven | vsc | 0.21.0
vscode-icons | vsc | 9.7.0
propertylist | zho | 0.0.2

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
