### ISSUE TITLE
Request: Add a way for exstensions to show an update log

### ISSUE THREAD

**Issue by LucaVazz** [Microsoft/vscode#9028]
I think it would be very nice to have a way to display logs of new features and bug fixes after an update of an extension, similarly to [what the PackageControl-Plugin from Sublime Text offers](https://packagecontrol.io/docs/messaging).

<sup>I couldn't find any trace of a way to add update logs for Code-extensions, but feel free to point me in the direction if I just missed it ;)</sup>

**Comment by joaomoreno** [comment]
Your extension can actually open a read-only document containing that info, through the API.

**Comment by LucaVazz** [comment]
Thanks for the answer.
While this does feel like a *"hack"*, it's at least a way to archive that functionality...
