### ISSUE TITLE
Enable click & drag in code navigation view

### ISSUE THREAD

**Issue by eliyo** [microsoft/vscode#90280]
Issue Type: <b>Feature Request</b>

When we left-click and drag in the navigation view (right pane) outside of the current preview area, the preview area does move to this new position.. We need to release the mouse button, click on the preview area and drag it which is... a drag. 

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
What is the navigation view? can you add more info?

**Comment by eliyo** [comment]
oh, I probably don't know the proper name for it, I mean the view to the right where you can see the whole code in very small characters and you can pan vertically into it.

**Comment by alexdima** [comment]
Let's track in #64459
