### ISSUE TITLE
workbench.editor.limit immediately closes untouched file before limit is reached

### ISSUE THREAD

**Issue by frfancha** [microsoft/vscode#90283]
Scenario:
-workbench.editor.limit.value = 3 (just for the sake of example)
-3 files are opened: A, B, C, all recently modified
-you want to modify file D & E
-open file D
-open file E
Expected: file A, B or C is closed
Actual: file D, just opened is closed

**Comment by bpasero** [comment]
@frfancha with recently modified, do you mean they are dirty? this limit does not work on dirty editors at the moment.

**Comment by frfancha** [comment]
No not dirty (then I would understand that VSCode doesn't close them).
And just retried: bug is much worst than that:
-no files at al opened (or just one)
-open file A
-open file B
==> file A is closed !!

**Comment by bpasero** [comment]
@frfancha can you give me your exact settings for the limit and explain exactly the steps for the A/B issue you just reported?

**Comment by frfancha** [comment]
Limit settings:
![image](https://user-images.githubusercontent.com/9610263/74088792-651c6480-4a9a-11ea-86d6-a577daa1285a.png)

Failing scenario is following one:

-no tab or any file is opened
-click on file A in explorer: file A is opened
-click on file B in explorer: file B is opened but at the same time file A is closed!

A working scenario is:

-no tab or any file is opened
-click on file A in explorer: file A is opened
-do ctrl-S (without changing anything, just ctrl-S)
-click on file B in explorer: file B is opened in new tab, file A is kept opened

**Comment by bpasero** [comment]
@frfancha I think you are confusing this with our preview feature. 
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by frfancha** [comment]
Oops sorry then let's close this one
