### ISSUE TITLE
Linux: tab title is wrongly cropped for certain file names

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#90299]
- VSCode Version: 1.42.0
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open a file named model.pxd
2. Look at its tab title:

![image](https://user-images.githubusercontent.com/2845433/74090977-26ce7780-4a91-11ea-976a-bbd663b67386.png)

Does this issue occur when all extensions are disabled?: Yes

I'm not 100% sure but this might be a regression in 1.42.0.

Settings that may be relevant:

```
    "window.zoomLevel": 0.70,
    "window.menuBarVisibility": "toggle",
```

My screen is hidpi, scaling factor is 2x, font is default Ubuntu one.

**Comment by bpasero** [comment]
This does not look new to me. I think italic fonts are not pushing the parent div large enough for some reason. Up for help if someone has clues how to resolve this, ideally with CSS and no hacks.

**Comment by bpasero** [comment]
This seems to only happen on Linux and seems to be related to using `overflow: hidden`. I have reported this as https://bugs.chromium.org/p/chromium/issues/detail?id=503426
