### ISSUE TITLE
VS Code doesn't see `reject` on `Promise`.

### ISSUE THREAD

**Issue by JamieCorkhill** [microsoft/vscode#90295]
- VSCode Version: 1.42.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Launch a TypeScript project.
2. Create an `async` function in a TS file.
3. Attempt to return out of the function with `return Promise.reject(/* ... */)`

After step 3, you should see a red line underneath `reject` from `Promise.reject` with the error message "Property 'reject' does not exist on type 'PromiseConstructor'".

Indeed, this could be more of a DefinetelyTyped issue, but, if I hit Ctrl + S anywhere inside of the editor, nothing happens. However, if I specifically click somewhere on the keyword "reject" such that the cursor is now placed somewhere between the letters of "reject", and then hit Ctrl + S, the error goes away and the red line disappears until I close and re-open the TS file in question again.

![image](https://user-images.githubusercontent.com/28678855/74089864-42268c00-4a6b-11ea-88fd-b1b0a8d5e048.png)

Does this issue occur when all extensions are disabled?: No

I thought it might have been the linter, but I disabled it, and I still see issue. The project does compile and there is a type definition file for Node inside of `node_modules` that contains the typings for `Promise.reject`.

**Comment by mjbvz** [comment]
Please share a self contained code example (as text!)

**Comment by JamieCorkhill** [comment]
@mjbvz Well, any code whatsoever that uses `Promise.reject` leads to the issue. But, if you want just one example:

```typescript
public async hashPassword(plainTextPassword: string, rounds: number = 12): Promise<string> {
    try {
        const salt = await this.hashHandler.generateSalt(rounds);
        return await this.hashHandler.generateHash(plainTextPassword, salt);
    } catch (e) {
        return Promise.reject(ApplicationErrors.UnexpectedError.create());
    }
}
```

**Comment by mjbvz** [comment]
Does not repo for me:

![Screen Shot 2020-02-10 at 2 13 05 PM](https://user-images.githubusercontent.com/12821956/74195144-79ce3900-4c0f-11ea-9982-2fb14661a571.png)

What file is opened if you run `f12` (go to definition) on `Promise?

**Comment by JamieCorkhill** [comment]
I've looked at that, @mjbvz. There are two files that both contain definitions for `Promise`. One of them is `lib.es2018.promise.d.ts`, which only contains `finally`, and the other is `lib.es2015.promise.d.ts`. That one does contain the definition/signature for `reject`, but the `readonly` modifier is used inside every signature, and I see the error "A parameter property is only allowed in a constructor implementation.".

So, inside that latter file:

```
/**
     * Creates a new rejected promise for the provided reason.
     * @param reason The reason the promise was rejected.
     * @returns A new rejected Promise.
     */
    reject<T = never>(readonly reason?: any): Promise<T>;
```

Even if I remove the `readonly` modifier and restart VS Code, I still have the same issue.

**Comment by mjbvz** [comment]
This seems like a TS issue to me. Please [file this against TS upstream](https://github.com/microsoft/TypeScript/issues/new/choose)

**Comment by JamieCorkhill** [comment]
Will do, thanks @mjbvz.

**Comment by JamieCorkhill** [comment]
Just to let you know, @mjbvz, I found the source of the problem. Every single type def file and any usage of `reject`, `resolve`, `all`, `race`, etc., on Promise were all failing. It turns out it was due to a very badly made Intellisense extension for VS Code. Thanks for your help.
