### ISSUE TITLE
Log into SQL Server from python script via ODBC Driver 17 for SQL Server fails

### ISSUE THREAD

**Issue by phasedephase** [microsoft/vscode#90291]
i haven't changed my simple test python script in a week. i turn on OSX laptop and try running it again against the local test DB and get this error: 

cnxn = pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}', host=server, database=database, user=username_db, password_db=password_db, autocommit=False)
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

when a week ago it worked just fine--again, no changes to the script.

since i am running this on OSX, the DB is running inside Docker, but that is not the issue because last night i had this exact same issue when i tried to run the same scripts on my Windows 10 machine at work that has SQL Server 2017, Azure Data Studio, and SSMT installed, and was working fine last week. again no changes. 

i just booted up, opened ADS, SSMT, connected to the DB with both apps, then opened VS, and clicked the run button for the script. and got the error above. so i thought i'd try on my home machine later, the OSX laptop. and same problem there but different error. on the PC it complains about the connection string not being conform: this string: driver='{ODBC Driver 17 for SQL Server}', host=server, database=database, user=username_db, password_db=password_db, autocommit=False).

and yet,  i can log into the DB with the same credentials just fine using Azure Data Studio on my Mac OSX system, and on the PC as well.

so if i can manually log into the DB then logically it is not a credential issue. and if it isn't, then the script shouldn't generate the error above. so we have a contradiction here. WTF!!!  

i am sick and tired of having to fight with the tools instead of being able to dedicate my precious time to the task of coding.  why all this over-complexity when it comes to SQL Server??? why is it always with Microsoft that just when you thought you figured out the last hurdle, there is always some other new and totally illogical and ridiculous problem that creeps up???  the amount of time wasted on trying to figure out why the tools suddenly crap out for no reason could be time spent working on the code i have to write.

this is precisely why i abandonned Windows and everything Microsoft.  how old is Microsoft?  40+ years and end users still have to deal with this kind of subpar experience??? honestly, i want to hurl half a dozen expletives at you right now, i am so mad.  

[sql.ipynb.zip](https://github.com/microsoft/vscode/files/4174658/sql.ipynb.zip)

**Comment by GoEagles999** [comment]
^ this guy needs a chill pill.
Advice: report the problem to developer succinctly and work on something else till it was resolved

**Comment by eamodio** [comment]
Sorry for your frustration, but what is the issue you are seeing with VS Code?
