### ISSUE TITLE
Shift+Ins shortcut not works properly

### ISSUE THREAD

**Issue by inflop** [microsoft/vscode#90297]
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.11-050311-generic

Disabled all extensions.

I always use shortcuts Ctrl+Ins(copy), Shift+Ins(paste), Shift+Del(cut),
instead of standard Ctrl+C/V/X. They are available in all editors that I used without any interference in the application settings. This was also the case in VSCode up to version 1.42.0. Using these shortcuts from this version without changing the settings is not possible.
The main problem is that I can't overwrite the previously selected text with the clipboard text using the Shift+Ins shortcut.

Steps to reproduce:
1. Open not empty text file.
2. Select text you want to copy.
3. Use Ctrl+Ins to copy text.
4. Select another text you want to overwrite.
5. Use Shift+Ins to paste copied text from clipboard.

**Comment by jeanp413** [comment]
@inflop  there is a new command `editor.action.selectionClipboardPaste` that affects that behavior, just remove the keybinding.
More info #36170 #63374

**Comment by inflop** [comment]
Thanks, works fine.
