### ISSUE TITLE
anyone can give me an sample to call web api in vscode plugin?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#903]
I want to call web api in my vscode plugin ,anyone can provide an sample for me?

**Comment by alexandrudima** [comment]
@BleyChen here is an example:

http://stackoverflow.com/a/7971584

**Comment by BleyChen** [comment]
It throw “source is not available” error when I imported “http” module and use one API in my code ,do you know what’s the problem?

Code : set breakpoint on line 52 in extension.ts for below code.
                      http.request('http://www.google.com', function(response) {
                            console.log(response.statusMessage)    });
plugin sample code(http://mediasvc1nxn1n47jdwb5.blob.core.windows.net/guided-tours/testIntellisenseJavascript.zip) 

Steps for repro this problem:
1.	Download the source and open it in VSCode
2.	Run it and you will see an vscode instance 
3.	Change the language mode in “untitled-1” from “Plain Text” to “Javascript”
![aa](https://cloud.githubusercontent.com/assets/15098626/11526687/37e5d638-9917-11e5-8e1c-4a983b8ef6ab.png)
4.Type an character and it will trigger the method “”,then you will see the error.
![bb](https://cloud.githubusercontent.com/assets/15098626/11526691/3cee574a-9917-11e5-9b7b-93b3a23d4cb0.png)

**Comment by alexandrudima** [comment]
@BleyChen 
Here are the nodejs docs corresponding to the nodejs version inside VSCode 0.10.3:
https://nodejs.org/docs/v4.1.1/api/

I think you might want to use [`http.get`](https://nodejs.org/docs/v4.1.1/api/http.html#http_http_get_options_callback) which accepts a string as the first argument. `http.request` accepts a literal with options as the first argument.

You might also want to change in your `package.json` (to indicate your extension would work with all API compatible versions of VSCode >= 0.10.0). I'm also wondering why you're not updating to 0.10.3 yourself:
```
"engines": {
	"vscode": "^0.10.0"
},
```

Forwarding to @weinand  regarding the `Source is not available` message

**Comment by BleyChen** [comment]
thank you ! i can call now
