### ISSUE TITLE
Synchronization: Workspace View, File System

### ISSUE THREAD

**Issue by jbdoster** [microsoft/vscode#90306]
**Synchronization: Workspace View, File System** 

**As a** VS Code user,
**I want** my open workspace to synchronize with changes I make to my file system
**so that** I do not have to relocate the moved path with the file explorer.

Scenario:
**Given** that a user has an open workspace in the VS Code application
**when** the user moves the open workspace path
**and** the move is made outside of the VS Code application context
**then** the VS Code application should be notified about the event
**and** the VS Code application context should be updated with the changes.

This is a great IDE, thank you!

**Comment by bpasero** [comment]
This should already happen, can you give me steps to reproduce where it does not happen?

**Comment by jbdoster** [comment]
Hello! Yes

_Step 1_
Open vscode and import a project

_Step 2_
move the current project name/directory in the vscode terminal with the command `mv`

![Screenshot from 2020-02-18 20-25-59](https://user-images.githubusercontent.com/31192968/74801895-fbb40700-528c-11ea-8a02-a0a388ffcec9.png)

![Screenshot from 2020-02-18 20-23-08](https://user-images.githubusercontent.com/31192968/74801905-0373ab80-528d-11ea-8ca1-ce634eae3324.png)

_Expected result_
Updated path for the workspace project in vscode

_Actual result_
Path not updated, file not found/deleted
