### ISSUE TITLE
prompting always

### ISSUE THREAD

**Issue by irfan3616** [microsoft/vscode#90300]
.

Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (10.24GB free)|
|Process Argv|typesints.ts|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
node-json-autocomplete|bhs|0.1.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.20.5
vscode-eslint|dba|2.0.15
vscode-npm-script|eg2|0.3.11
search-node-modules|jas|1.3.0
vscode-codemetrics|kis|1.23.1
node-module-intellisense|lei|1.5.0
vscode-exec-node|mir|0.5.1
vscode-azurefunctions|ms-|0.20.2
azure-account|ms-|0.8.8
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|3.8.20200207
vsliveshare|ms-|1.0.1510
vsliveshare-audio|ms-|0.1.80
debugger-for-chrome|msj|4.12.6
vscode-for-node-js-development-pack|nod|2.0.1
typescript-hero|rbb|3.0.0
code-settings-sync|Sha|3.4.3
nodejs-extension-pack|wad|0.1.9
NodeJS-extension-pack|wal|0.0.2
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
