### ISSUE TITLE
Command like `filesExplorer.openFilePreserveFocus` but don't preserve focus

### ISSUE THREAD

**Issue by sashaweiss** [microsoft/vscode#90305]
Thank you for building and maintaining VSCode! I love it and how configurable it is.

I'm currently building a set of shortcuts for myself that mimic `NERDTree` behavior for navigating the Explorer sidebar viewlet. In doing so I'm using `filesExplorer.openFilePreserveFocus`, but to more accurately emulate the `NERDTree` behavior it'd be great to have a command that opens a file and moves focus to it - basically `filesExplorer.openFileDontPreserveFocus`.

**Comment by isidorn** [comment]
Thanks.

@sashaweiss as far as I remember `filesExplorer.openFilePreserveFocus` was introduced as an alternative to regular open. And you would like the opposite of `filesExplorer.openFilePreserveFocus`, thus you want the original command which is `list.select`. So please try to assign a custom keybinding for that and it should do the job.
If you want the keybinding to only work in the explorer you can use some fancy context key like `filesExplorerFocus`.

Let me know how it goes and id anything is missing.

**Comment by sashaweiss** [comment]
Correct me if I'm wrong, but doesn't list.select trigger a rename of the file rather than open it? I could have sworn I tried that - and can try again when I get to my machine.

I wonder if that functionality changed at some point - I was scrolling through some old SO posts trying to find a workaround and folks proposed list.select, so maybe it used to open without preserving focus? Or maybe it opens the file on one platform but not on all? It'd be in-line with the Mac list paradigm for "select" to rename in a file list, as that's what Finder (and Xcode) will do as well - and it'd make sense for it to open a file on Windows.

I can follow up here with some experimentation when I get to my machine.

**Comment by sashaweiss** [comment]
Nope, `list.select` does what you're describing. Not sure why I was running into issues with it previously - if I had to guess I tested it by using a shortcut that was being intercepted somewhere and was triggering rename, rather than actually triggering `list.select`.

Will close this issue and the PR - thanks for the attention!

**Comment by isidorn** [comment]
Not sure what platform you are on. But for example Enter is list.select on Win / Linux and Rename on Mac.
Cmd + Down is list.select on mac. So we align with native finder.

**Comment by sashaweiss** [comment]
Makes sense - I bet I saw "Enter" as the shortcut on Windows and then tried that on my Mac and got the rename behavior instead, without realizing that the shortcut would be different. (Which makes sense, but slipped my attention.)

Thanks for your help!
