### ISSUE TITLE
the windows is no longer responding (always need to click "keep waiting" to open it)

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode#90318]
Issue Type: <b>Bug</b>
![image](https://user-images.githubusercontent.com/24194840/74100965-e45e7680-4b34-11ea-9714-6a8a82632efc.png)

Each time I launch VScode (since I installed it)  I'm bothered by this seemingly useless popup. I need to click each time on "keep waiting" to use it. 

How can I disable this popup?

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
replacerules|bhu|0.4.1
transformer|dak|1.6.0
vscode-todo-plus|fab|4.14.1
code-runner|for|0.9.15
macros|ged|1.2.1
beautify|Hoo|1.5.0
vscode-favorites|how|1.4.0
reg|ion|1.0.1
vscode-opn|lfu|1.1.2
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
powershell|ms-|2020.1.0
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.1
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
html-preview-vscode|tht|0.2.5
local-history|xyz|1.7.0

</details>

**Comment by WiliTest** [comment]
What's wrong with my report, how can I improve it?

In case this was missing:

> Operating System: Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
> Processor: Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 CPUs), ~2.4GHz
> Memory: 8192MB RAM
>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by WiliTest** [comment]
thanks but it did not work (launching it at startup, trigger the same popup)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by WiliTest** [comment]
I exuted: code --disable-extensions then rebooted and started vscode insider, I did not have this popup. I then started vscode, and it also worked. So you are right. But:

1/ How can I reverse the ode --disable-extensions? 

2/ How to know which extension causes the problem ?
Is there a better solution than starting vscode 18 times, by disabling them one after another?

**Comment by bpasero** [comment]
So it seems to me that it now works even without the `--disable-extensions` switch?

**Comment by WiliTest** [comment]
Yes it seems to work. My bad I thought `--disable-extensions` was disabling it until another command enabled it. 

So yes it work for both (insider and classical), **but why** ? (Since nothing changed in the classical version, if I understand well).

**Comment by bpasero** [comment]
I cannot answer why it works now.

**Comment by WiliTest** [comment]
By the way, it doesn't work anymore. (It somehow worked during ≈12h)
