### ISSUE TITLE
When tabs are disabled, make the close button on editor panels to close the panel directly instead of closing one file

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#9031]
And move the unmodified filed into other editor panels.

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by bpasero** [comment]
-1, but we have another issue where someone asks to show the "Close All" button in the actions area.

**Comment by bpasero** [comment]
I am closing this as I find this to be confusing behaviour. The request in #7046 is still valid. Meanwhile there is a "Close All" in the context menu on the title.
