### ISSUE TITLE
intellisense say error on clone new constructor() syntax

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#90311]
![image](https://user-images.githubusercontent.com/24865815/74095735-cce6a580-4ac2-11ea-9f29-44f0a46091db.png)

```js
class _A extends _a{
    constructor() {
        super();
    }
};

class _a {
    constructor() {
    }
    clone(){
        return new this.constructor() 
    }
};

const A = new _A();
const clone = A.clone();
```

**return new this.constructor()** should no a type error ?!!.

---
Version : 1.42.0 (user setup)
Validation : ae08d5460b5a45169385ff3fd44208f431992451
Date : 2020-02-06T10:51:34.058Z
Électron : 6.1.6
Chrome : 76.0.3809.146
Node.js : 12.4.0
V8 : 7.6.303.31-electron.0
OS : Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug upstream](https://github.com/microsoft/TypeScript/issues/new/choose)

**Comment by djmisterjon** [comment]
ok it seem a very old knowing issue thanks
https://github.com/microsoft/vscode/issues/90311#event-3020816501
