### ISSUE TITLE
"[Log]": {"editor.fontSize": 12} can't change fontsize in output log now in 1.42.0 version

### ISSUE THREAD

**Issue by A1bertY** [microsoft/vscode#90310]
according to the official document:

// Main editor
"editor.fontSize": 18,
// Terminal panel
"terminal.integrated.fontSize": 14,
// Output panel
"[Log]": {
    "editor.fontSize": 15
}

Main editor and Terminal panel worked well , But Log panel (which I think is "output" panel  right?) doesn't work.
![2020-02-09_112309](https://user-images.githubusercontent.com/22695643/74095634-a0687300-4b2e-11ea-8bb1-5586d2fd7805.png)

**Comment by eamodio** [comment]
@sandy081 changing it to (notice the lowercase `L`):
```
"[log]": {
	"editor.fontSize": 22
}
```

Changes the output panel font, but will also change any file set to the `log` language. Was there a recent change here?

**Comment by sandy081** [comment]
Both `log` and `Log` works but former is for logs and latter is for output channels. No changes here.

**Comment by A1bertY** [comment]
> Both `log` and `Log` works but former is for logs and latter is for output channels. No changes here.

Why both my two computers failed to change the output panel fontsize with whatever 'log' or 'Log'

**Comment by sandy081** [comment]
Check if reloading the window works?

**Comment by A1bertY** [comment]
> Check if reloading the window works?

Sadly, not work! I have tried in windows 7,64 bits and windows 10 32 bits. But both failed to change the size of output panel
![2020-02-13_211329](https://user-images.githubusercontent.com/22695643/74438768-d5b1ef80-4ea5-11ea-865b-3ca5c904b1f1.png)

**Comment by sandy081** [comment]
Which channel are you looking at? Did you also try `[Log]`?

**Comment by A1bertY** [comment]
> Which channel are you looking at? Did you also try `[Log]`?

I tried Log,But didn't work. What do you mean channel?  By the way,Could you show me a Screenshot in which you successfully changed your front size of the output panel? I suppose Everyone can't do that .    it is a bug.

**Comment by sandy081** [comment]
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/10746682/74733996-e075d700-524d-11ea-8eb0-02f264e24f89.png">

By channel I mean the selected entry in the output panel
