### ISSUE TITLE
Open next recently used editor in group

### ISSUE THREAD

**Issue by DeveloperDavo** [microsoft/vscode#90316]
- VSCode Version: 1.42.0
- OS Version: Mac OS 10.15.3

Steps to Reproduce:

1. Action: "open next recently used editor in group"
2. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
Did you go backward in time first - to a previously used editor?  Then `next` works to go forward in time.  The terminology is a little confusing at first.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/90316#issuecomment-583870688
