### ISSUE TITLE
searching on large project like chromium makes all cpu load full.

### ISSUE THREAD

**Issue by kissstudio** [microsoft/vscode#90315]
Issue Type: <b>Performance Issue</b>

open directory of chromium project using vscode , execute a keyword search. all cpu cores load full.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.83GB free)|
|Process Argv|D:\chromium|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    81	  1792	code main
    0	    11	  5900	   electron-crash-reporter
    0	    90	 14004	   gpu-process
    0	    68	 26940	   window (Issue Reporter)
    0	   301	 29080	   window (test_support_modified.cc - chromium - Visual Studio Code [Administrator])
    0	    13	  6948	     watcherService 
    0	     5	 32600	       console-window-host (Windows internal process)
    0	   117	 30352	     extensionHost
    6	   139	  9988	       c:\Users\linswin\.vscode\extensions\ms-vscode.cpptools-0.26.3\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    21	  7076	         "c:\Users\linswin\.vscode\extensions\ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 9988 24
    0	   123	  7620	         "c:\Users\linswin\.vscode\extensions\ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 9988 22
    0	   844	 16304	         "c:\Users\linswin\.vscode\extensions\ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 9988 20
    0	   171	 24976	         "c:\Users\linswin\.vscode\extensions\ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 9988 37
    0	     5	 29624	         console-window-host (Windows internal process)
    0	     4	 15100	       cmd /s /c "C:\Users\linswin\.vscode\extensions\ms-vscode.csharp-1.21.11\.omnisharp\1.34.11\OmniSharp.exe -s d:\chromium\src\native_client\tools\hermetic_cygwin\MkLink\MkLink.sln --hostPID 30352 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\linswin\.vscode\extensions\ms-vscode.csharp-1.21.11\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	    46	 20672	         C:\Users\linswin\.vscode\extensions\ms-vscode.csharp-1.21.11\.omnisharp\1.34.11\OmniSharp.exe  -s d:\chromium\src\native_client\tools\hermetic_cygwin\MkLink\MkLink.sln --hostPID 30352 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\linswin\.vscode\extensions\ms-vscode.csharp-1.21.11\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	     5	 29928	         console-window-host (Windows internal process)
    0	    35	 20872	       c:\Users\linswin\.vscode\extensions\ms-python.python-2020.1.58038\languageServer.0.5.30\Microsoft.Python.LanguageServer.exe
    0	     5	  2540	         console-window-host (Windows internal process)
    0	    38	 30812	     searchService
   20	    76	 36876	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test_support_modified.cc - chromium - Visual Studio Code [Administrator])
|    Folder (chromium): more than 56281 files
|      File types: cc(7467) h(5733) md(430) xtb(365) py(348) gn(337) dll(299)
|                  mm(185) lib(166) gni(119)
|      Conf files: makefile(2) settings.json(1) sln(1);
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
javac-linter|fau|1.3.1
flatbuffers|gab|0.1.0
cmake-integration-vscode|go2|0.7.1
vscode-test-explorer|hbe|2.16.0
syntax-project-pbxproj|mar|0.1.3
vscode-catch2-test-adapter|mat|2.8.4
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
remote-wsl|ms-|0.41.9
cmake-tools|ms-|1.3.0
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
vscode-gn|npc|1.1.0
java|red|0.55.1
ninja|sur|0.0.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0

</details>

![image](https://user-images.githubusercontent.com/2771647/74098174-f994ce80-4b4f-11ea-90a0-ecaa39d933c9.png)

**Comment by JacksonKearl** [comment]
Our search engine (ripgrep) is multi-threaded, so this is somewhat expected. Tracking options to limit the number of threads at #90154.

**Comment by kissstudio** [comment]
can we make search thread number go with cpu core number auto and let cpu some free,  so that it can both doing search quickly and will not make system load full.

**Comment by JacksonKearl** [comment]
Yes that’s what we’re discussing in #90154.
