### ISSUE TITLE
White lines

### ISSUE THREAD

**Issue by JackWangCA** [microsoft/vscode#90314]
Issue Type: <b>Bug</b>

There are white lines on the application interface when you leave it there for over 30 seconds

VS Code version: Code - Insiders 1.43.0-insider (beaf391bc53136912e4f0bbdfb7844ad954247db, 2020-02-07T05:29:40.363Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
material-icon-theme|PKi|3.9.2

</details>

**Comment by joshhmann** [comment]
Does it look like this? Been having bleeding white lines as I move my mouse around VS Code 
![QqFgpZL](https://user-images.githubusercontent.com/15977276/74108316-1bd61e80-4b47-11ea-9df8-da008438df18.png)

**Comment by JackWangCA** [comment]
That is correct

**Comment by bnfzrsydn** [comment]
> Does it look like this? Been having bleeding white lines as I move my mouse around VS Code
> ![QqFgpZL](https://user-images.githubusercontent.com/15977276/74108316-1bd61e80-4b47-11ea-9df8-da008438df18.png)

i have the some problem, how do you fix this?

**Comment by deepak1556** [comment]
Does disabling hw acceleration help  https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration ? 

Also can you try our exploration build  https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209

**Comment by bnfzrsydn** [comment]
> Does disabling hw acceleration help https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration ?
> 
> Also can you try our exploration build [#94074 (comment)](https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209)

It really helps! Thanks you so much, I really appreciate it.

**Comment by bnfzrsydn** [comment]
> Does disabling hw acceleration help https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration ?
> 
> Also can you try our exploration build [#94074 (comment)](https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209)

It really helps! Thank you so much, I really appreciate it.

**Comment by deepak1556** [comment]
Closing as part of issue grooming https://github.com/microsoft/vscode/wiki/Issue-Grooming#upstream-issue
