### ISSUE TITLE
Expand `w100vw` to `width: 100vw`

### ISSUE THREAD

**Issue by Dan-Gamin** [microsoft/vscode#90321]
### So I had a small idea:
Basically imagine that you're setting the width/height of an element in CSS like this:  `width: 100vw;` so you use emmet: `w100vw` but if you typed; `w100v` it will autocomplete to this: `width: 100vw;` same as height: emmet: `h100v` autocompleted: `height: 100vh` . that's the whole idea not much still I would like it in VS Code

**Comment by krupenja** [comment]
In 1.43 Insiders 8d17dc1e84d53f5fd4ed0d05fabaa3062259633d, `w100vw` actually auto-completes to `width: 100vw` at my end.

**Comment by octref** [comment]
You are right, this seems working as expected for me as well:

![image](https://user-images.githubusercontent.com/4033249/74278672-72ba3000-4cce-11ea-9fbd-e9799496b93d.png)
