### ISSUE TITLE
large/rapid removals of files do not register in Source Control (git) extension

### ISSUE THREAD

**Issue by bnb** [microsoft/vscode#90329]
Issue Type: <b>Bug</b>

Seems related to #88804

1. check in large (1k+) directory of files (I used node_modules for a GitHub Action)
2. delete the directory
2.1. Source Control: git should not update
3. quit and re-open VS Code
4. Source Control: git should now show the deleted files

VS Code version: Code - Insiders 1.43.0-insider (beaf391bc53136912e4f0bbdfb7844ad954247db, 2020-02-07T05:30:08.850Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (3.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-standardjs|che|1.2.3
bracket-pair-colorizer-2|Coe|0.0.29
vscode-github-actions|csc|0.1.10
vscode-markdownlint|Dav|0.34.0
mustache|daw|1.1.1
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.0
vscode-pull-request-github|Git|0.14.0
material-icon-theme|PKi|3.9.3
vscode-icons|vsc|9.7.0

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you show me a screen recording of the issue?

**Comment by bnb** [comment]
Yes, will snag that this week for you (currently on a train to a conf) 👍

**Comment by bnb** [comment]
Apologies for the delay! I've uploaded a MP4 here: https://imgur.com/a/MgrPWuG

**Comment by joaomoreno** [comment]
We have an upper limit of 5000 changes in a repository, once that limit is hit, there are no more file change events due to performance reasons. You got a warning explaining that, surely. You can see that warning once again if you close and open the window.

Once you hit that amount of active changes, you have to manually click the refresh action.
