### ISSUE TITLE
Search editor: view state is not preserved between reloads

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90325]
Steps to Reproduce:

1. save a search editor
2. select some lines
3. reload

=> 🐛 lines are not selected

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/90326 could be a solution

**Comment by JacksonKearl** [comment]
Unable to reproduce. Is this on Insiders? We do have logic for restoring view state

https://github.com/microsoft/vscode/blob/d40fcf36ebfef12a2de60634ab5db5116ddc7934/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L468-L476

**Comment by bpasero** [comment]
Yes insiders! I can reproduce. Are you doing window reloads?

**Comment by JacksonKearl** [comment]
Verification: Save search, reload. Select text in search and reload *using keybinding*. Text should still be selected.

**Comment by bpasero** [comment]
@JacksonKearl this only works from a dirty search editor it seems, as for a saved search editor we do not show the results we had, so no view state is restored.
