### ISSUE TITLE
Out of memory crash on Ubuntu x64

### ISSUE THREAD

**Issue by IljaK** [microsoft/vscode#90327]
- VSCode Version: 1.42.0 ae08d5460b5a45169385ff3fd44208f431992451 x64
- OS Version: Ubuntu 18.04.4
Memory: 12 gb ram
Processor: Intel® Core™ i5-3210M CPU @ 2.50GHz × 4 

Visual Studio code closes after few seconds after launch. Command line options: --disable-extensions --disable-gpu did not changed result. Log file has none critial errors. Using --verbose command shows before crash:
```
[14510:0209/173346.908838:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[14510:0209/173346.909675:FATAL:memory.cc(22)] Out of memory. size=524288
```
PC have 12gb of ram when only 3gb where used by other processes. Right after vscode launch it is growing till 3.5gb and app crashes.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by IljaK** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

That one works fine.
