### ISSUE TITLE
Update 1.3 breaks markdown code block highlighting

### ISSUE THREAD

**Issue by uxsoft** [Microsoft/vscode#9032]
- VSCode Version: 1.3
- OS Version: Windows 10 x64

Inside of a csharp code block highlighted properly (vscode 1.2)
![vsmarkdown12](https://cloud.githubusercontent.com/assets/1889343/16715052/1f72b2f2-46d6-11e6-9ed7-57f884d8cb12.PNG)

Same file loses highlighting with the 1.3 update
![vsmarkdown13](https://cloud.githubusercontent.com/assets/1889343/16715051/1f6d4844-46d6-11e6-9e39-8f466f85664d.PNG)

**Comment by glennsarti** [comment]
I too am having the issue of code highlighting.  I found the syntax highlight can also 'bleed' out of the code block to subsequent text

Test Info:
VS Code :1.3
OS: Mac OSX 10.11.5

Test Case 1

Before

<img width="760" alt="Test_case_1_before" src="https://cloud.githubusercontent.com/assets/5819622/16755111/fb874834-47ad-11e6-84bc-37f68619afc6.png">

After: Adding a single quote before the word `production` makes the rest of the code block highlighted, include bleeding out past the end-of-block marker of 3 backticks

<img width="759" alt="Test_case_1_after" src="https://cloud.githubusercontent.com/assets/5819622/16755172/80c199aa-47ae-11e6-90d7-07523abf4a83.png">


Test Case 2

Before - Note that the top code block is prefaced with the powershell type, and bottom code block has no type.  And yet the bottom code block is highlighted like a powershell one

<img width="634" alt="Test_case_2_before" src="https://cloud.githubusercontent.com/assets/5819622/16755184/9f5a57c6-47ae-11e6-9d8f-9e704541e79d.png">

After - Removing the powershell code block type at the top also changes the highlighting on the bottom code block.  Also note the highlight for the text `### Try out the ....` has changed.  Before it was powershell highlighted and now it's regular markdown highlighted.

<img width="752" alt="Test_case_2_after" src="https://cloud.githubusercontent.com/assets/5819622/16755205/cc3bc1ee-47ae-11e6-831f-e10a67144f05.png">

**Comment by schorg** [comment]
I have the same problem, with a language extension I created locally using a .vsix file.

For my installed extensions I observe the following behaviour:

* The C# language extension does not highlight code blocks.
* The Lua language extension does highlight code blocks.

Infos:
* VS Code :1.3
* OS: Microsoft Windows 7 Professional

**Comment by unional** [comment]
Another case:
![image](https://cloud.githubusercontent.com/assets/3254987/16785293/255ff52c-4842-11e6-9683-0b7e76f70806.png)

**Comment by glennsarti** [comment]
Refs: https://github.com/Microsoft/vscode/issues/8259

**Comment by gerane** [comment]
It is breaking more than this. There is a long list of issues that I have found, especially in regards to anything related to bullets or asterisks. Ref: #9075

**Comment by Thraka** [comment]
still waiting for a fix :sob:

**Comment by gerane** [comment]
Still waiting on an status update on this one.

**Comment by mjbvz** [comment]
#14626 fixed many of the issues with fenced code blocks leaking their syntax highlighting. Please try out the latest insiders builds and report any additional issues you notice with markdown syntax highlighting. Thanks.
