### ISSUE TITLE
Freeze when remaining in the file menu

### ISSUE THREAD

**Issue by nolex90** [microsoft/vscode#90328]
Issue Type: <b>Bug</b>

I am experiencing a bug in the newest vscode.
Reproduction steps:

1. On the left up corner, hit 'file'
2. Move the cursor into the dropdown.
3. Dont move cursor at least 70 sec
4. When you move the cursor again, menu freezes and vscode crashing out

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.15.0-76-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.31GB (25.71GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.900.11
swagger-viewer|Arj|2.2.2
cform|aws|0.0.24
vscode-pytest|Cam|0.1.1
aws-cloudformation-yaml|Dan|0.2.2
vscode-markdownlint|Dav|0.34.0
githistory|don|0.5.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
angular-essentials|joh|0.6.3
Angular2|joh|8.3.1
vscode-peacock|joh|3.3.1
vscode-esp8266fs|kas|1.1.0
restructuredtext|lex|117.0.0
Angular-BeastCode|Mik|8.1.2
prettify-json|moh|0.0.3
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
angular2-inline|nat|0.0.17
angular-console|nrw|10.0.0
vscode-serial|olb|2.0.3
material-icon-theme|PKi|3.9.3
vscode-yaml|red|0.6.1
reloaded-cpp|rel|0.1.9

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
i can repro this, but given https://github.com/microsoft/vscode/issues/55347, I am ask @deepak1556 to take a look

**Comment by nolex90** [comment]
Issue disappeared in the latest, closable.
