### ISSUE TITLE
Search editor: should extend BaseTextEditor?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90326]
It seems to me that the search editor could extend [`BaseTextEditor`](https://github.com/microsoft/vscode/blob/718331d6f3ebd1b571530ab499edb266ddd493d5/src/vs/workbench/browser/parts/editor/textEditor.ts#L36) to benefit from a few things, such as helper methods for storing and restoring view state. 

There is also [`TextFileEditor`](https://github.com/microsoft/vscode/blob/718331d6f3ebd1b571530ab499edb266ddd493d5/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L38) specifically for files, though not sure that it would add a lot.

**Comment by JacksonKearl** [comment]
With regard to view state, we already delegate out to CodeEditorWidget for view state tracking. We need to specially handle restoring focus to the query editor widget or the results widget either way so I don’t think inheriting from BaseTextEditor would simplify much there but possibly, I’ll look more in to what else we’d inherit.

**Comment by bpasero** [comment]
@JacksonKearl there is a few things:
* ARIA label handling
* automated update of editor options based on settings changes
* specific [editor overrides](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/textEditor.ts#L119)
* forwarding of visibility to the editor based on workbench editor visibility (you need that if you don't have it)
* focus / layout forwards
* editor view state loading and restoring

**Comment by JacksonKearl** [comment]
@bpasero moved to inheriting from `BaseTextEditor`, but it seems like some of the stuff you mention is actually in `TextFileEditor`, such as editor view state loading and restoring and forwarding of visibility to the editor based on workbench editor visibility.

**Comment by bpasero** [comment]
@JacksonKearl not sure I understand, e.g. [`setEditorVisible`](https://github.com/microsoft/vscode/blob/cfa6daa6b9f1396237cc0b2b81cb993715848d62/src/vs/workbench/browser/parts/editor/textEditor.ts#L175) is in text resource editor. 

The reason why I think text resource editor is doing everything you need is because e.g. untitled editors are text resource editors and not text file editors.

**Comment by JacksonKearl** [comment]
Reopening to look back into visibility.
