### ISSUE TITLE
untitled editor window does not show the text from first line

### ISSUE THREAD

**Issue by wahab896** [microsoft/vscode#90339]
Issue Type: <b>Bug</b>

Untitled editor window does not show the text from first line in following case:
1. When we type // the untitled window will not show //. But after we write //Hello, It will show the name as //Hello.
2. If we just write // and then press enter and start writing from new line then the window remains as untitled.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
This is intentional. It falls back to the old "Untitled-<number>" scheme if the first line is empty or does not contain any words.

**Comment by IllusionMH** [comment]
See https://github.com/microsoft/vscode/issues/37414#issuecomment-576721206 for details

**Comment by gjsjohnmurray** [comment]
Also stated explicitly in the [release notes](https://code.visualstudio.com/updates/v1_42#_untitled-editor-improvements).
![image](https://user-images.githubusercontent.com/6726799/74144424-9ad56080-4bf4-11ea-8ae9-b6b8602d7be4.png)

**Comment by xnsdns** [comment]
That's all nice but is there a way to switch back to the old behavior?

**Comment by IllusionMH** [comment]
Old behavior was to only show Untitled-x without first line content.
Current - show first line if there are words.

There is no flags to have old behavior except having line without words on the first line (empty line, `//` comment sequence, `{` formatted JSON etc.)

**Comment by xnsdns** [comment]
@IllusionMH That's sad. Thanks for the info though.

**Comment by akbyrd** [comment]
I also do not want this behavior. https://github.com/microsoft/vscode/issues/90495
