### ISSUE TITLE
Contextual "Manage" menu initially partially hidden

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#90331]
This is a tiny thing but still could be improved: At least on macOS, clicking on the gear icon in the lower left to open the "Manage" options, the contextual menu is partially hidden and needs to be scrolled. Smart contextual menus are aware of their position on the screen and automatically place themselves to be fully visible.

| Bad (current behavior) | Better |
|---|---|
| ![bad-menu](https://user-images.githubusercontent.com/30958850/74108502-e5ae9400-4b72-11ea-8700-24973f9ccaed.png) | ![better-menu](https://user-images.githubusercontent.com/30958850/74108503-e6dfc100-4b72-11ea-910f-319f3592403a.png) |

**Comment by sbatten** [comment]
this is duplicate, but I'm not sure the state of the original issue.

**Comment by sbatten** [comment]
@deepak1556 not sure if you have a separate issue for this
