### ISSUE TITLE
Install remote extensions locally [Remote: SSH, Extensions]

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/vscode#90332]
I don't know if this is a missing feature or a bug

I have come across [this](https://marketplace.visualstudio.com/items?itemName=lior-chamla.google-fonts) extension, what is (I imagine) server side only, and I noticed that I cannot install it locally. (there is no option for it) If I install it and disconnect, the extension is not installed and it is available to be installed from the marketplace.

If connected, the only thing that is presented is the option to "Install on SSH: myserver.tld". The only way to install it locally is by disconnecting or opening another, local window. 

The option to install locally while connected to a remote machine would be appreciated.
Additionally, there should be option to install all remote extensions locally (just like the function currently present, but in the other direction)

If this is an existing feature then the discoverability could be improved.

Google Fonts | 0.0.1
VSCode | 1.42.0 - ae08d5460b5a45169385ff3fd44208f431992451

**Comment by mhanuszh** [comment]
Clarifying:

Only local-only extensions can be installed locally while connected to remote host.

**Comment by mhanuszh** [comment]
> /duplicate

I did look for this issue, but I haven't found anything. Can you please give me a link?

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/83675
