### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by parys** [microsoft/vscode#90333]
Issue Type: <b>Bug</b>

tryied to open my project and see this issue

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (6.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.11
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.0.15
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
auto-rename-tag|for|0.1.1
code-runner|for|0.9.15
beautify|Hoo|1.5.0
Angular2|joh|8.3.1
vscode-typescript-tslint-plugin|ms-|1.2.3
typescript-hero|rbb|3.0.0
sass-indented|rob|1.5.1
vscode-icons|vsc|9.7.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by parys** [comment]
My bad. It was mistype in tsconfig pathes.

**Comment by mjbvz** [comment]
Can you share the config that caused this? Misconfiguration should never cause a crash

**Comment by estruyf** [comment]
I'm getting this as well more and more since the latest two VSCode updates.

Steps to reproduce are to start with a new `react app` which uses TypeScript. Add a couple of components, builds has no errors, but VSCode TS intellisense crashes all the time.
