### ISSUE TITLE
VSCode should self-configure debug settings when added to ASP.NET Core projects

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/vscode#9033]
- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create ASP.NET Core project using either Visual Studio 2013 or via Yeoman ("yo aspnet") at the command-line
2. At the command-line, navigate to the root of the project (wherever project.json resides)
3. Run `dotnet restore`: Dependencies should be downloaded
4. Run `dotnet run`: Project should build & run
5. Run `code .`: VS Code should load and open the project folder
6. Open debug tab and hit "play button": VS Code displays an error that "launch.json must be configured"
![saved image from tweetium](https://cloud.githubusercontent.com/assets/961950/16714984/52e9b980-4688-11e6-9af5-3264bedd456c.jpg)

I [asked about this on Twitter](https://twitter.com/bitcrazed/status/751464295121063936) and received help from @jchannon, @shanselman and @damianedwards (thanks guys): Turns out that I had to manually determine the `target-framework` and `project-name` fields. I also had to [set the "debugType": "portable" in project.json](https://github.com/bitcrazed/HelloWorldCore/commit/7c34f86998dc53e0a0d4409e7e130f540890b0b0). (see [request to set this by default](https://github.com/aspnet/Templates/issues/650))

I would have expected that since VS Code injected `launch.json` into the project, and that it had access to `project.json` etc. that it'd be able to determine the target-framework automatically.

**Comment by weinand** [comment]
VS Code by itself does not know anything about .NET projects and project.json.
So it can only be the .NET extension that creates a launch.json that corresponds to the project.json.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#556
