### ISSUE TITLE
Keyboard shortcut for named global task shows selection

### ISSUE THREAD

**Issue by HackerBaloo** [microsoft/vscode#90344]
Issue Type: <b>Bug</b>

If I move a command from workspace tasks to global tasks. 
And then try to activate it with the following shortcut configuration.
```
        "key": "ctrl+d",
        "command": "workbench.action.tasks.runTask",
        "args": "open in commander"
```
It will show the list of tasks instead of just run the task. When the task is in the workspace tasks it will run directly.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.15.0-76-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7960X CPU @ 2.80GHz (32 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 4|
|Memory (System)|62.59GB (3.28GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
gitlens|eam|10.2.0
macro-commander|jef|1.2.8
svn-scm|joh|2.6.1
protobuf|kan|1.1.6
restructuredtext|lex|117.0.0
camelcasenavigation|map|1.1.1
ecdc|mit|1.3.0
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.0.9
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
Go|ms-|0.13.0
vscode-yaml|red|0.6.1
jinja-json-syntax|rya|0.0.3
cmake|twx|0.0.17
clang-format|xav|1.9.0

</details>

**Comment by joehillen** [comment]
Pinging @alexr00 because she wrote https://github.com/microsoft/vscode/pull/81496

**Comment by markushoff** [comment]
I faced the same issue (the task list was presented) with a task defined in my multiroot workspace file (.code-workspace). 
When I moved the task definition to the task.json everything works as expected.

Is this issue also fixed with your fix?
