### ISSUE TITLE
Not able to open terminal in visual studio code

### ISSUE THREAD

**Issue by pkmarathe** [microsoft/vscode#90349]
Hi,

I am trying to open terminal in vs code but giving below error. Please assist
Error: Terminal process terminated with exist code:259

![image](https://user-images.githubusercontent.com/45457172/74138734-c9563a00-4bfa-11ea-81b8-a1b049f5d3e9.png)

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
