### ISSUE TITLE
Handling "visible" TextEditor in api

### ISSUE THREAD

**Issue by peni4142** [microsoft/vscode#90345]
`window.visibleTextEditors` and `window.onDidChangeVisibleTextEditors(actualState)` while splitscreen does not have all visible `TextEditors` in it.

Steps to Reproduce:

1. clone https://github.com/peni4142/work-as-two
2. debug my extension
3. open a few `TextEditor` in split-screen
4. set a breakpoint in work-as-two/src/integration/api.ts at line 16
5. open another TextEditor
6. check the value `actualState.length`

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> while splitscreen does not have all visible TextEditors in it.

Not sure what that means

**Comment by peni4142** [comment]
One picture could say more than thousands of words.

![visual example](https://user-images.githubusercontent.com/33463108/74220632-5f986780-4cb0-11ea-8193-9561f7cd8826.png)

`actualState.length` should have been 4. There are 4 visible `TextEditor`.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aapi+label%3Afeature-request

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/15178

**Comment by peni4142** [comment]
At all, it does not match the description:

![image](https://user-images.githubusercontent.com/33463108/74222985-f6b3ee00-4cb5-11ea-8191-6cd3a9ab7fa8.png)

**Comment by peni4142** [comment]
I think you should open the thread again until the description matches the functionality. A possible description would be: "The currently visible editors in the active column or an empty array."
