### ISSUE TITLE
[HTML] Provide completion/go to definition for CSS classes and ids inside HTML files

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode#90343]
From https://github.com/eclipse/wildwebdeveloper/issues/342
When editing some HTML, it would be quite interesting to get some content-assist, go to definition and hover for the CSS classes and ids that are either embedded in the HTML file or referenced as stylesheet.

**Comment by mickaelistria** [comment]
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like: [html][css] Investigate cross css/html support (#47331)

I think there is a strong relationship, but that other one is more about internals of the language server while the one I suggest is more about usage.
Also, there are probably ways to fix this issue without fixing that other one.

**Comment by ArturoDent** [comment]
Have a look at the "CSS Peek" extension.  https://marketplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek  It looks like it provides what you are seeking.

**Comment by mickaelistria** [comment]
Thanks @ArturoDent . However I'm not using VSCode directly (I'm using the related language services in Eclipse Wild Web Developer), so I can't leverage extensions, nor really want to ;)
I think such feature would better be offered directly by the main language service, and I don't see a particular blocker in it.
Have you considered implementing such features directly inside VSCode and submitting a PR?

**Comment by aeschli** [comment]
We have #47331 to track such a cross language / multi-file support
