### ISSUE TITLE
Debug: hover shows scrollbars always and has weird margins

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90341]
The debug hover seems to always show scrollbars for me, even if not needed. Also there seems to be a weird margin on the left:

![image](https://user-images.githubusercontent.com/900690/74126556-884d2e00-4bd8-11ea-93ca-4a99090aaa36.png)

**Comment by bpasero** [comment]
This is using web btw.

**Comment by isidorn** [comment]
Pushed fix for margins.
For showing scrollbars dup of https://github.com/microsoft/vscode/issues/67643
