### ISSUE TITLE
Drag and drop selected text

### ISSUE THREAD

**Issue by Ed-Dikotope** [Microsoft/vscode#9034]
I often miss this feature from other editors. I just would like a way to be able to drag and drop my selected text instead of a whole copy & paste operation. Thanks for Tabs by the way!! With this little feature I'll be super happy 😃 .

**Comment by JoshMcCullough** [comment]
Yes, this is a great feature in Visual Studio which I often miss in VS Code.

**Comment by mahomedh** [comment]
The lack of this feature is REALLY killing my productivity. So much so I may have to go back to sublime now.

Also looks like this may be a duplicate of https://github.com/Microsoft/vscode/issues/1046 which was logged in Dec 2015.

**Comment by alexandrudima** [comment]
Let's track in #1046
