### ISSUE TITLE
The software is always in the foreground

### ISSUE THREAD

**Issue by nasmi3** [microsoft/vscode#90346]
Issue Type: <b>Bug</b>

Hi,

I am using the Visual Studio Code insider program.
Once I opened the software, it is working as expected however I can not switch to any other application as it is located *on top* of all the other windows. It doesn't go to the background.

Details :

- It occurs only when launched as an administrator
- I can minimize the application and then I am able again to use the rest of the applications
- When two or more windows of Visual Studio Code are opened, I can switch between by clicking on them but not with other applications
- Minimizing by clicking on the window's taskbar is not working too, only on the icon on top of the window

VS Code version: Code - Insiders 1.43.0-insider (beaf391bc53136912e4f0bbdfb7844ad954247db, 2020-02-07T05:29:40.363Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2399)|
|Memory (System)|6.13GB (4.42GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.42.3
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.20.0
vscode-wordcount-cjk|hol|1.3.1
latex-workshop|Jam|8.7.1
python|ms-|2020.3.62366-dev
vscode-yaml|red|0.6.1
markdown-preview-enhanced|shd|0.5.2
code-spell-checker|str|1.7.22
code-spell-checker-french|str|0.1.6
pdf|tom|0.5.1
vscodeintellicode|Vis|1.2.5
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?
