### ISSUE TITLE
Debug: integration tests fail on Linux

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90342]
Noticed this here for example: https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=67005&view=logs&j=50a69d0a-7972-5459-cdae-135ee6ebe312&t=0fd26d6d-1412-52a0-245a-c59f83ba439c&l=681

I [pushed a change](https://github.com/microsoft/vscode/commit/b49c688023511ae4e5188e61e7e7ca4d9b4a0742) to skip this test, please investigate.

**Comment by isidorn** [comment]
Thanks. I will look into this.

**Comment by isidorn** [comment]
Hopefully fixed via 2270536e85
So far so good
