### ISSUE TITLE
The new files.defaultLanguage setting for Untitled Editors doesn't include Markdown

### ISSUE THREAD

**Issue by matt123miller** [microsoft/vscode#90348]
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
Open the settings. Applyu the new `files.defaultLanguage` setting. In the json settings view it will offer autocompletions but Markdown isn't one of them. Typing markdown will work for new Untitled Editors though.

Does this issue occur when all extensions are disabled?: Yes

I couldn't reproduce this specific issue in the current release of Insiders because there was no autocomplete at all in the json editor for me.

![image](https://user-images.githubusercontent.com/9091121/74138488-96f01100-4be9-11ea-9f57-0d803a43a14c.png)

**Comment by bpasero** [comment]
It looks like https://github.com/microsoft/vscode/commit/9772efe6bc65d5b6594167d3bb93d8a4493d8eac added a weird check for the config that filter out languages that have overrides. Since this method is used in other places, I think this change needs to be adjustable through a flag.

**Comment by sandy081** [comment]
Those completion items are for language override identifiers and the check is to remove duplicates.
