### ISSUE TITLE
syntex coloring is broken

### ISSUE THREAD

**Issue by abecus** [microsoft/vscode#90354]
Syntex coloring works well normally but when I start using python's arg input type declaration feature it gets broke. see the attached image

- VSCode Version:1.42
- OS Version: win10 

Steps to Reproduce:
1. use python's arg input type declaration feature

Does this issue occur when all extensions are disabled?: Yes
Uninstalling and installing again was making it work well in the previous version of vs code but now
it is not working even if I uninstall and install again.
![Annotation 2020-02-10 160021 PNG](https://user-images.githubusercontent.com/32030745/74142889-cde11980-4c1f-11ea-88cc-2eeea7592730.jpg)

**Comment by alexr00** [comment]
Please provide some copy-pastable code that reproduces the issue.

**Comment by abecus** [comment]
here's the code.
```
class FenwickTree:
	def __init__(self, arr):
		self.tree = [0]+arr.copy()
 
	def rangeSum(self, leftIndex:int, rightIndex:int)-> int:
		"equivalent to sum(arr[leftIndex:rightIndex]) but in O(ln(rightIndex))"
		pass

	def update(self, index:int, value: int)-> None:
		pass
```

**Comment by alexr00** [comment]
I'm not able to see that issue:
![image](https://user-images.githubusercontent.com/38270282/74331757-9f387f80-4d94-11ea-8c87-6633f3ebaff2.png)
Are you sure you disabled all extensions and don't have any settings or themes that might be causing this?

**Comment by abecus** [comment]
@alexr00 issue has been solved, a setting was causing the problem, thanks!
