### ISSUE TITLE
Text save participants are overwritten for each extension host

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90359]
Only on Windows I see this test failing and as such have pushed a skip() for just that:

```
  1) workspace-namespace eol, change via onWillSave:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(called)

      + expected - actual

      -false
      +true

      at extensions\vscode-api-tests\src\singlefolder-tests\workspace.test.ts:242:13
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by bpasero** [comment]
Actually seeing this on Linux too, I have pushed a change to disable it when running from web.

**Comment by jrieken** [comment]
@bpasero add you for debugging help. This test work on playwright+macOS, in electron, and also when running from within web-selfhost. I see them failing on playwright+windows but the debugging is so limited that I don't know how to drill into it

**Comment by bpasero** [comment]
@jrieken maybe with this [`sloMo`](https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md#browsertypelaunchoptions) option you could artificially slow down the test run to get a hold of the dev tools within? But I guess simple timeouts in the test would also help already.

**Comment by bpasero** [comment]
Turns out that this is a race between the web worker extension host and the remote one and the text exposes it.
