### ISSUE TITLE
Detached child process gets closed if IDE closes

### ISSUE THREAD

**Issue by mschaefer88** [microsoft/vscode#90351]
This is an issue when creating extensions for VS Code.
The spawned child process is supposed to stay open after VS Code closes but doesn't.
When the code gets executed (just as node app) everything works as intended but from within VS Code it gets closed. Spawning the process from within a node process (aka fork) doesn't get closed down.

- VSCode Version: 1.41.1
- OS Version: Win 10 x64

Steps to Reproduce:

1. Create extension
2. Execute following Code after activated
```
let cp = require('child_process')
var child = cp.spawn('notepad', [], {
            detached: true,
            stdio: 'ignore'
            });

        console.log(`PID is ${child.pid}`);
            child.unref();
```

3. Close VS Code Instance

Notepad is supposed to stay open but closes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@mschaefer88 I cannot reproduce. I have tried with the following extension:

* `package.json`
```
{
    "name": "90351",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.31.0"
    },
    "activationEvents": ["*"],
    "contributes": {
        "commands": [{
            "command": "startNotepad",
            "title": "90351: Start Notepad"
        }]
    },
    "main": "index.js"
}
```

* `index.js`:
```
const cp = require('child_process');
const vscode = require('vscode');

exports.activate = function() {
    vscode.commands.registerCommand('startNotepad', function () {
        let child = cp.spawn('notepad', [], {
            detached: true,
            stdio: 'ignore'
        });
        console.log(`PID is ${child.pid}`);
        child.unref();
    });
}

```
