### ISSUE TITLE
Intellisense not working when creating new typescript file and referencing another ts file

### ISSUE THREAD

**Issue by alverLopez** [Microsoft/vscode#9035]
- VSCode Version: 1.3.0
- OS Version: windows 10

Hello, it seems when i create a new ts file, intellisense doesn't recognize it when i reference it.
![vs_code_bug](https://cloud.githubusercontent.com/assets/8460975/16715418/69db472e-46df-11e6-8d78-54c0792253e4.png)

As you can see, intellisense doesn't show me Phaser options, when i restart vs code it starts to work

**Comment by dbaeumer** [comment]
Moving to TS team

@alverLopez can you share the project. having steps or code to verify always helps to fix the problem.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9612
