### ISSUE TITLE
Help request analyze api

### ISSUE THREAD

**Issue by thiago-barros-souza** [microsoft/vscode#90358]
Issue Type: <b>Feature Request</b>

Hello, I'm having trouble debugging my PHP api's, as vscode can only stop debugging using a browser plugin, how can I perform api debugging, and the request can come from many places, sometimes not from a browser .

If you already have a solution ready, you can give me an answer, or the possibility to implement this functionality.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 6.1.7601

**Comment by IllusionMH** [comment]
You can just send proper payload using any REST client. E.g. Postman extension if there are extra steps for user login, and it will be easier to log in to application and then send required requests with existing session, use extensions e.g. https://marketplace.visualstudio.com/items?itemName=humao.rest-client , or use standalone REST Client

**Comment by JacksonKearl** [comment]
Are you using a PHP debugging extension? Such as: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug
