### ISSUE TITLE
.Git folder becomes too big

### ISSUE THREAD

**Issue by johnfercher** [Microsoft/vscode#9036]
- VSCode Version: Latest Version on site
- OS Version: Linux 16:04
- Language: C++

This actual version it's very good, I loved. But I notice a problem, I use OpenCV and Qt and includes the directories "/usr/include" and "/usr/local/include" on c_cpp_properties.json for the intellisense work with this libraries, after that, the size of.git folders jump of 33 mb to 607mb. If I not change the c_cpp_properties the size of .git folder stay ok.

**Comment by joaomoreno** [comment]
Can you make a screen recording of the behaviour you are experiencing?

**Comment by johnfercher** [comment]
This is the actual folder .git
![vs-git01](https://cloud.githubusercontent.com/assets/4752636/16737960/0c5134b6-476a-11e6-88aa-5ffa0625452d.png)

The Intellisense doesn't work if the includes has this error
![vs-git02](https://cloud.githubusercontent.com/assets/4752636/16737961/0c5989f4-476a-11e6-8f4d-cef718d656cf.png)

To resolve the error, I folllow the tutorial on VSCode site and add c_cpp_properties.json
![vs-git03](https://cloud.githubusercontent.com/assets/4752636/16737962/0c6401ae-476a-11e6-87bf-9da2b830446d.png)

After resolver the error, I run git add -A
![vs-git04](https://cloud.githubusercontent.com/assets/4752636/16737963/0c74b5d0-476a-11e6-8e19-70e9afc4bfb9.png)

And the .git folder now has 407mb
![vs-git05](https://cloud.githubusercontent.com/assets/4752636/16737964/0c7dbd6a-476a-11e6-89a1-8c893b6225b1.png)

**Comment by joaomoreno** [comment]
Right before running `git add -A`, what was the result of `git status`?

What extensions do you have installed?

**Comment by johnfercher** [comment]
Here is the result of git status
![git-last](https://cloud.githubusercontent.com/assets/4752636/16781904/bd8f4f4e-4853-11e6-824d-8d40f39b3653.png)

I only use C/C++, C++ Intellisense and Aurora Theme.

**Comment by joaomoreno** [comment]
#5350

Your `.git` folder grows due to the `.browse.VS.db*` files. The C/C++ extension creates them. You should ignore them from your git repository:

- First, close VS Code.
- Clean them: `git checkout .vscode/.browse.VC*`
- Remove them: `git rm .vscode/.browse.VC*`
- Commit that: `git commit -m "remove cpp files"
- Add the following line to the `.gitignore` file: `.vscode/.browse.VC*`
- Continue developing.
