### ISSUE TITLE
Double backticks causes VS Code to hang and then crash

### ISSUE THREAD

**Issue by njlr** [microsoft/vscode#90369]
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic
```

CPUs | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2707)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 4, 3, 3
Memory (System) | 15.43GB (2.15GB free)
Process Argv | . --no-sandbox
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
better-toml | bun | 0.3.2
vsc-material-theme | Equ | 32.4.0
vsc-material-theme-icons | equ | 1.1.3
Ionide-fsharp | Ion | 4.5.0
terraform | mau | 1.4.0
azure-account | ms- | 0.8.8

Steps to Reproduce:

1. Be editing an F# test file
2. write `let ``some test name goes here` -
3. VS Code will hang and then offer to quit, reopen or wait

Does this issue occur when all extensions are disabled?: No

**Comment by JacksonKearl** [comment]
This sounds like the issue is with the F# extension. Please file the issue over there: https://github.com/ionide/ionide-vscode-fsharp
