### ISSUE TITLE
Suggestion: QuickFix for renaming afterwards, instead pressing F2 before rename.

### ISSUE THREAD

**Issue by MBODM** [microsoft/vscode#90361]
Please introduce renaming of variables AFTER we renamed a variable, via QuickFix, like VS do. 

Having in mind to always press F2 first, to rename, is horrible. Changing a name of a variable and say "reflect that to all uses of that variables" AFTERWARDS, is imo 100 times better.

And nearly every modern IDE has this feature.

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode/issues/88424

**Comment by MBODM** [comment]
Maybe my english is not good enough (i am not a native english speaker), but my suggestion has in no way anything to do with either [Issue 87853](https://www.github.com/microsoft/vscode/issues/87853)

**Comment by gjsjohnmurray** [comment]
@MBODM 87853 was suggested by the bot but is irrelevant. As I understand 88424 its idea of **synced regions** would provide a foundation for rename to be triggered by editing, without having to use F2.

**Comment by MBODM** [comment]
> @MBODM 87853 was suggested by the bot but is irrelevant. As I understand 88424 its idea of **synced regions** would provide a foundation for rename to be triggered by editing, without having to use F2.

My suggestion is not about a direct change of all occurences of a variable name, when renaming that variable. Its about changing the name of variable at the definition of the variable in lets say `let bunny = 'hop';` to `let ape = 'eat banana'` and AFTERWARDS a quick action tells you "Rename all occurences of "bunny" to "ape". If you execute the quick action, all bunny occurences are renamed to ape.

Did none of you ever used Visual Studio 2013, 2015 or 2019 ? Or Rider ? Or Android Studio ? Or whatever. They all use this feature. 

Do not get it.

**Comment by MBODM** [comment]
Hmm,

not to be salty here, but it seems there is less hope for a standard feature, every halfway modern development IDE has since years, when even a member of the VS Code development team (at least it seems @jrieken is one of them) thinks this suggestion is related to a totally another issue/suggestion.

So i assume (because it is a standard feature) there are A LOT of ppl out there would like to see this quick action added. But none of these ppl ever find or use issues/suggestions like this. And since obviously the devs seem to not see this as a needed feature (otherwise they had already did it), i assume this suggestion will dive into the shadows. Do not get that.

PS: Hi @jrieken, i think you are around 70 KM beeline away from here. So best regards to Wallisellen. :)
