### ISSUE TITLE
Multi-select QuickPick using canPickMany is missing a confirmation button

### ISSUE THREAD

**Issue by mjcrouch** [microsoft/vscode#90365]
When opening a quick pick that has multi-select enabled, there is no confirmation button. The only way I have found to confirm the selection by clicking into the quick pick text and pressing enter.

![1581341713001_image001](https://user-images.githubusercontent.com/49367953/74154269-43da8600-4c0a-11ea-9915-08d3dd7a6d64.png)

I'm fairly sure I'm not imagining that there was previously a confirmation button on 1.41.1, though I'm not currently in a position to prove it!

- VSCode Version: 1.42.0
- OS Version: Win 7 Enterprise 

Steps to Reproduce:

1. Open a multi-select quickpick
2. Observe the lack of a button

Does this issue occur when all extensions are disabled?: Not checked as I don't know a core menu that has multi-select

**Comment by shasank** [comment]
Yes, the same was working properly in 1.41.1.
![image](https://user-images.githubusercontent.com/4426919/74433204-fa966a80-4e85-11ea-94af-69f0971804a0.png)

**Comment by frnk01** [comment]
@chrmarti I’ve tried pressing enter multiple times. It does not work.

**Comment by frnk01** [comment]
@chrmarti I’ve tried pressing enter multiple times. It does not work. The list disappears but the selection is not saved.

**Comment by JacksonKearl** [comment]
@chrmarti is this in todays build? Not seeing button, but I did notice focus returns to the input on selection, so you can just submit with enter (no mouse needed).

![image](https://user-images.githubusercontent.com/8586769/75575914-ed948200-5a14-11ea-91f5-52c1fdedff37.png)

**Comment by JacksonKearl** [comment]
Disregard. I was using an old build.
