### ISSUE TITLE
Convert Indents to Tabs Remove Hidden Code Sections

### ISSUE THREAD

**Issue by Skatterbrainz** [microsoft/vscode#90368]
Issue Type: <b>Bug</b>

Possible bug in 1.41.1 on Windows 10.  If I collapse code sections, then run F1 to convert indent spaces to tabs, it removes the hidden/collapsed code sections entirely.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
aadb2c|Azu|1.2.77
xml|Dot|2.5.0
vscode-html-css|ecm|0.2.3
terraform|mau|1.4.0
rainbow-csv|mec|1.5.0
mssql|ms-|1.8.0
azure-account|ms-|0.8.8
powershell|ms-|2020.1.0
sqltools|mtx|0.21.6
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|9.7.0
markdown-all-in-one|yzh|2.7.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by JacksonKearl** [comment]
I can't reproduce on 1.42, are you able to?

**Comment by Skatterbrainz** [comment]
Yep.  Fixed in 1.42 - Thank you! :)
