### ISSUE TITLE
launch.json should pass arguments verbatim (Unexpected parsing args of format `{,}`)

### ISSUE THREAD

**Issue by samloescher** [microsoft/vscode#90362]
- VSCode Version:
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.17-1-MANJARO

- OS Version: Manjaro Linux

When providing arguments in the format `{x,y}` they are expanded into two distinct arguments `x` and `y`. This is unexpected, there also appears no way to stop this parsing occurring, and I've not found what causes this from the docs. As shown you can avoid this behaviour by adding a space character after the comma (`{x, y}`) however it should be possible to provide arguments verbatim. Perhaps a flag to disable any parsing of `args`?

Steps to Reproduce:

1. Create task in launch.json with `{x,y}`

```
        {
            "name": "vscode {} parsing",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/saml/workspace/vscode-braces/build/parseargs",
            "args": ["{1,2}", "\"{3,4}\"", "{5, 6}", "(7,8)"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
``` 
example cpp parser
```
#include <iostream>

int main(int argc, char **argv) {
    for (auto i = 0; i < argc; i++) {
        std::cout << argv[i] << std::endl;
    }
}
```

Expected:
/home/saml/workspace/vscode-braces/build/parseargs
{1,2}
"{3,4}"
{5, 6}
(7,8)

Actual:
/home/saml/workspace/vscode-braces/build/parseargs
1
2
"3"
"4"
{5, 6}
(7,8)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Thanks for filling this issue, however can you please file it against the C++ team.
Then they can investigate the actual issue and see if it is on their side and if not send it to us. Thanks a lot 
https://github.com/microsoft/vscode-cpptools

**Comment by samloescher** [comment]
Hey @isidorn, folk over in C++ team suggest it looks like the parsing happens in vscode and not the plugin. (https://github.com/microsoft/vscode-cpptools/issues/4962#issuecomment-585915792). Can you reopen this issue?

I've since tried recreating the issue with another launch.json (target Python), but the result is as expected so it appears C++ parsing specific
```
"configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": ["{1,2}"]
        }
    ]
```
```
import sys
print (sys.argv[1:])
```
prints `['{1,2}']`

**Comment by isidorn** [comment]
Sure I can reopen the issue. However vscode does not do anything with the `args`. That is why it is working on the python side. I trully believe this is a C++ issue. Of course if the issue is on the VS Code side I am open for accepting a PR that fixes it.

Unless I am missing something @weinand

**Comment by weinand** [comment]
VS Code's json parsing does not look inside strings, so "{1,2}" is not parsed as a json and it is left as is.

However, when passing arguments to a program (as it is done in with the args in the launch config shown in the first comment), the shell might see an unquoted `{1,2}` which is broken into two arguments `1` and `2`.

I've confirmed this by running `echo {1,2}`  and `echo "{1,2}"` in bash on macOS:

![2020-02-14_11-00-15](https://user-images.githubusercontent.com/1898161/74521115-31699080-4f19-11ea-99c4-13a8827f513a.png)

Please try to find the command line that gets executed when running the launch config from above. There you should see how the "args" form the command line are quoted/escaped.

**Comment by samloescher** [comment]
Ah interesting, I'll look into getting the printout for what actually gets launched with C++, in the meantime python is much easier to see as it dumps the command straight to the console

From launch.json
```
$ /usr/bin/python3 /home/saml/.vscode-server/extensions/ms-python.python-2020.2.63072/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher /home/saml/workspace/vscode-braces/hello.py {1,2}
['{1,2}']
```

From the python example running directly:
```
$ python3 hello.py {1,2}
['1', '2']
$ python3 hello.py "{1,2}"
['{1,2}']
```

I'd still like to carry on further as I have a c++ application which takes arguments in the form: 
`"--xyz{0,1,2}"`
Which we should somehow be able to express, I was hoping something like:
`"\"{3,4}\""` (also tried `"\\\"{3,4}\\\""` which didn't work as mentioned https://code.visualstudio.com/docs/cpp/launch-json-reference#_args). Noting that guys in C++ Extension couldn't reproduce running directly from the terminal

> $./main.out "{1,2}" "\"{3,4}\"" "{5, 6}" "(7,8)"
>
> output:
>
> ./main.out
> {1,2}
> "{3,4}"
> {5, 6}
> (7,8)

**Comment by GitMensch** [comment]
I *guess* @samloescher has fixed the launch configuration to add quotation where necessary in the meantime.
In any case it looks like this can be closed as it was proven that vscode does not tamper with the specified arguments at all.

**Comment by weinand** [comment]
@samloescher do you agree? Can we close the issue?

**Comment by samloescher** [comment]
Sadly not fixed, however I'm happy to close this ticket as I couldn't recreate with Python so appears like the C++ plugin specifically so I'll keep that ticket open. Thank you for looking into this.
