### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by filipporemonato** [microsoft/vscode#90366]
I get the error "Extension host terminated unexpectedly" after about 1-2h of the code running, and the code's execution halts.
![VSCode 1](https://user-images.githubusercontent.com/6236646/74154287-afc0ec80-4c12-11ea-8375-5aa0a8a431ea.PNG)

The code is running training of some neural networks, in Python. I have been using VS Code for over a year and never had such problem before, but it has now happened once yesterday, and Three times in a row today, completely wasting a day's work.
Clicking on "Restart extension host" does not work, as the code does not resume progress after the halt.

I have the following extensions
![VSCode 4](https://user-images.githubusercontent.com/6236646/74154211-8a33e300-4c12-11ea-9a21-b0d6bd107669.PNG)
but I have been using them for many many months, so I doubt the problem is there.
I have also tried disabling all Extensions but the Python ones, but the issue persists.

Clicking on "Open Developer Tools" presents me with a pane where about 16 errors are reported, having to do with VS Code dark theme, padding, etc. I can post a screenshot of that, too, once it happens again.

Any help would be appreciated.

**Comment by JacksonKearl** [comment]
This is an issue with the Python extension, please post an issue on https://github.com/Microsoft/vscode-python
