### ISSUE TITLE
Do not require a type attribute for `enableBreakpointsFor` contributions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#9037]
There is no real connection between a `enableBreakpointsFor` contribution and a debug type because breakpoint enablement applies to files with a specific language independent from the debugger used for that language.

Currently it is necessary to contribute to a type which results in this duplication:
```ts
       "debuggers": [
			{
				"type": "node",
				"enableBreakpointsFor": {
					"languageIds": [
						"typescript", "typescriptreact"
					]
				}
			},
			{
				"type": "extensionHost",
				"enableBreakpointsFor": {
					"languageIds": [
						"typescript"
					]
				}
			}
        ]
```

Please consider to eliminate the need for the type here.

**Comment by isidorn** [comment]
July to investigate

**Comment by isidorn** [comment]
The above example shows how an extension contributes to VSCode file types for which it is possible to add breakpoints.

After discussing with @weinand putting "enableBreakpointsFor" under "debuggers" does not make much sense, since this contibution is per language not per debugger (e.g. enabling setting breakpoints in a python file). And having to specify a type does not make sense for this (as shown above).
As an example, we looked into TS [package.json](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L44) and found two approaches:
* Move "enableBreakpointsFor" under "contributes"."languages"
* Move "enableBreakpointsFor" under a new top level field "contributes"."breakpoints"

@aeschli @alexandrudima opinions are very welcome

**Comment by isidorn** [comment]
After discussing with @aeschli and @weinand we have decided to introduce a top level "breakponits" under "contributes"

```json
"breakpoints": [
	{
		"language": "typescript"
	}
]
```

Using an object we can later extend this approach such that the adapter can contribute additional info for breakpoints.
For the following sprint (july) we will also support the old way of contributing breakpoints - 'enableBreakpointsFor'

**Comment by weinand** [comment]
With this the old contribution for typescript: 
```json
		"debuggers": [
			{
				"type": "node",
				"enableBreakpointsFor": {
					"languageIds": [
						"typescript", "typescriptreact"
					]
				}
			},
			{
				"type": "extensionHost",
				"enableBreakpointsFor": {
					"languageIds": [
						"typescript"
					]
				}
			}
		],
```

becomes a much clearer:
```json
		"breakpoints": [
			{
				"language": "typescript"
			},
			{
				"language": "typescriptreact"
			}
		],
```

@isidorn since there still duplication when adding language variants like in this example, I wonder whether it would make sense to support something like this:

```json
		"breakpoints": [
			{
				"languages": [ "typescript", "typescriptreact" ]
			}
		]
```

**Comment by isidorn** [comment]
@weinand not a big fan of that since we do not support it for `snippets`, `grammers` etc...

**Comment by octref** [comment]
Is it possible to let user specify a list of languages he can enable debugger for? Not with extension, but as user setting.

Today a user asked if he could debug F# (fsx) files transpiled to JS through http://fable.io/. As fable generates sourcemap I was able to get it working by adding `fsharp` to `enableBreakpointsFor` in Chrome Debugger's `package.json`, but that does't make much sense.
We should be able to debug any languages [here](https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js) that outputs sourcemap, and that list of languages doesn't belong to any extension IMO.

**Comment by weinand** [comment]
@octref the `breakpoints` contribution for `fsharp` should be done in the fsharp extension.

**Comment by octref** [comment]
@weinand 
There are hundreds of languages that compile down to JS: https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js

If they have a sourcemap we can debug them using Chrome Debugger.
It doesn't make sense to make an extension for each language to only enable debugging, right?

**Comment by weinand** [comment]
@octref I've created https://github.com/Microsoft/vscode/issues/13507
