### ISSUE TITLE
Ctrl+F6 does not work

### ISSUE THREAD

**Issue by ConnorsFan** [microsoft/vscode#90373]
- VSCode Version: 1.42
- OS Version: Windows 7

Steps to Reproduce:

1. Open several files in one project
2. Press Ctrl+F6
3. Nothing happens

However, here is a different behavior:

1. Open several files in one project
2. Press Ctrl+Shift+F6 (once or several times)
3. It works
4. Press Ctrl+F6
5. Now that also works

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

What do you expect to happen?
I don't see <kbd>Ctrl</kbd>+<kbd>F6</kbd> in list of default Windows keybindings.

**Comment by ConnorsFan** [comment]
Sorry, I did not remember that these were not default mappings. I have had the following mappings  since 2016 or 2017, and their behavior changed in the past few days:

```
{
  "key": "ctrl+f6",
  "command": "workbench.action.openNextRecentlyUsedEditorInGroup"
}
{
  "key": "ctrl+shift+f6",
  "command": "workbench.action.openPreviousRecentlyUsedEditorInGroup"
}
```

**Comment by IllusionMH** [comment]
Have you checked release noted for latest update specifically [Navigate most recently used editors](https://code.visualstudio.com/updates/v1_42#_navigate-most-recently-used-editors) section?

Looks like you need to change command (and may be condition) to have restore previous behavior.

**Comment by ConnorsFan** [comment]
I took a look at the notes but I was looking for Ctrl+F6, since this key combination is universal in Windows, and I thought it was a default key combination in VSCode also. I will take time to read that section and adapt my key bindings. Thanks!
