### ISSUE TITLE
[TS/JS] Option to disable auto imports from specific paths

### ISSUE THREAD

**Issue by NiciusB** [microsoft/vscode#90370]
When working on a React Native project, I keep accepting components from the wrong npm package, causing all kind of weird bugs and headaches.

For example, when importing `<TouchableOpacity>` I get suggestions from both packages `react-native-gesture-handler` and `react-native`, but the wrong one appears first
![image](https://user-images.githubusercontent.com/2421121/74158784-f87ca380-4c1a-11ea-84a4-6f4a5aee1ca0.png)

It would be nice to have a way to disable TS Auto Imports for specific paths, for example `["node_modules/react-native-gesture-handler/*"]`

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
