### ISSUE TITLE
Setting environment variables for DAP terminal requests

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#90375]
Continuing https://github.com/microsoft/vscode-js-debug/issues/318

We use environment variables to wire up Node for debugging, and send them through the `env` option in the DAP `runInTerminal` request. This causes the following issue:

> This [issue is] because you use nvm, which runs an npm command to get configuration when the terminal opens. The debugger right now doesn't know that npm is not what we actually want to debug--so it treats it as the main target, and then after it disconnects (i.e. the session is over) just kills everything else.

I think the best solution from my point of view would be to never set the environment variables on the global terminal level, and always set them per-command. We actually do this already in `prepareCommand` if we're going to reuse a terminal. 

https://github.com/microsoft/vscode/blob/a0328d26aca420f9d0606b825f5a326dc6d0d398/src/vs/workbench/api/node/extHostDebugService.ts#L111-L112

This would also be a little more consistent for debuggers. For instance, if I had `env: { FOO: '1' }` in my first launch request, and `env: { BAR: '2' }` in the second request, the launched process would see `env: { FOO: '1', BAR: '2' }` since it would inherit the previous environment variables set on a terminal level as well as the new variables set for the specific process.

**Comment by connor4312** [comment]
@weinand this is a pretty easy to hit bug with js-debug; if you think the proposed fix is the way to go (omitted the `env` in the created terminal and always letting it bubble to prepareCommand) I'm happy to stick in a fix for it for this month :)

**Comment by Tyriar** [comment]
I don't understand the connection between setting environment variables and the debugger seeing nvm and attaching to that first?

**Comment by connor4312** [comment]
js-debug uses the `NODE_OPTIONS` environment variable to `--require` a bootloader that connects back to a server the extension is running to start debugging. When set on a terminal level, this causes any Node processes inside the user's .*rc file to connect as debug targets--nvm executes an npm command (`npm config get prefix`), which connects to us and causes us to think that it's in the debugee.

**Comment by Tyriar** [comment]
@connor4312 and the fix involves launching the terminal without `NODE_OPTIONS` and running the debug targets like this?

```
export NODE_OPTIONS=blah
foo.js
```

**Comment by connor4312** [comment]
Essentially yes. prepareCommand has logic that does this already, which we omit for the first launch and instead set the variables on a terminal. I propose always using prepareCommand's version of variable setting.

https://github.com/microsoft/vscode/blob/a0328d26aca420f9d0606b825f5a326dc6d0d398/src/vs/workbench/contrib/debug/node/terminals.ts#L114-L123

**Comment by weinand** [comment]
@connor4312 I think your proposal makes sense, please go ahead and fix this.

But what does this mean for the debug terminal?
If it relies on the global environment, it will suffer in the same way as discussed in https://github.com/microsoft/vscode-js-debug/issues/318: it will try to debug just about everything that see the NODE_OPTIONS, right? So if I run a node.js-based build tool in that terminal, that tool will always run in debug mode...

**Comment by connor4312** [comment]
That's right, any node process with that environment variable will be debugged, including build tools.

**Comment by weinand** [comment]
That excludes anything nodemon-based. A workaround would be to run those build tools via `env NODE_OPTIONS= nodemon program.js`

**Comment by connor4312** [comment]
I didn't have an trying to boot and break in a program with nodemon in the debug terminal. It looks like killing and letting nodemon reboot the program works, though when the debug session gets terminated it'll kill everything. Are there issues you anticipate running Nodemon in the debug terminal?
