### ISSUE TITLE
Changes in extended tsconfig.json file are ignored

### ISSUE THREAD

**Issue by slavafomin** [microsoft/vscode#90372]
Hello!

I have a clear setup of VSC (no extra plugins or such).

Consider you have two files:
- /project-root/tsconfig.json
- /project-root/package/tsconfig.json

With the latest file extending the previous using [`extends`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends) option.

However, when the extended config file is updated, VSC doesn't see those changes at all. The only solution is to re-start the IDE.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug for this upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
