### ISSUE TITLE
Search only returns first 10,000 items found

### ISSUE THREAD

**Issue by nyghtly-derek** [microsoft/vscode#90383]
Issue Type: <b>Bug</b>

1. Open file containing more than 10,000 instances of a string such as "hello,"
2. Search for "hello,"
3. Only 10,000 results will be found

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.00GB (1.83GB free)|
|Process Argv|file.txt|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32
mssql|ms-|1.8.0
csharp|ms-|1.21.11
powershell|ms-|2020.1.0

</details>

I'm aware of existing issues such as https://github.com/microsoft/vscode/issues/8563

What makes my issue unique is that it properly identifies this search limitation as a **bug**. The search module does not indicate anywhere that there is a limit to the number of results that will be returned. Thus it is a reasonable for the user to assume that the search module will return all possible results. 

Either this bug needs to be fixed, or a warning needs to be added when the results limit is reached. As is stands a user might believe that they are getting all the results, even though they are not.

**Comment by nyghtly-derek** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [search results have a limit of 10000 items (#29120)](https://www.github.com/microsoft/vscode/issues/29120)
> * [Increase the number of cursors from 10000 (#81589)](https://www.github.com/microsoft/vscode/issues/81589)

From original bug report:

>I'm aware of existing issues such as https://github.com//issues/8563
>
>What makes my issue unique is that it properly identifies this search limitation as a bug. The search module does not indicate anywhere that there is a limit to the number of results that will be returned. Thus it is a reasonable for the user to assume that the search module will return all possible results.
>
>Either this bug needs to be fixed, or a warning needs to be added when the results limit is reached. As is stands a user might believe that they are getting all the results, even though they are not.

**Comment by JacksonKearl** [comment]
Are you referring to the in-editor search, or the entire workspace search?

**Comment by nyghtly-derek** [comment]
@JacksonKearl - The entire workspace search. I didn't test ctrl-f on the individual file.

The reason I discovered this in the first place is because I was trying to find-and-replace all instances of a string in my file. Other editors like notepad++ can do it no problem.

**Comment by JacksonKearl** [comment]
You should see a warning like:
![image](https://user-images.githubusercontent.com/8586769/74365178-61326000-4d82-11ea-8d36-5ba47fdff99d.png)

Do you not?

**Comment by nyghtly-derek** [comment]
I will attempt this again and report back with a screenshot...

**Comment by nyghtly-derek** [comment]
I received no such warning.

A comparison of the search methods:
![hello-10080](https://user-images.githubusercontent.com/7283262/74401002-c1ea8880-4dd4-11ea-80dd-2cfb201c1438.PNG)

Unable to search and replace all instances of "hello," with "hello,goodbye":
![uh-oh](https://user-images.githubusercontent.com/7283262/74401004-c2831f00-4dd4-11ea-8192-eb1440ea85ed.PNG)

**Comment by roblourens** [comment]
Yeah, we don't correctly compute whether to show that warning when the max is hit in an open file. And actually the editor doesn't tell us whether the result was hit, so we will have to ask for max+1 results and work it out from that.

**Comment by JoeEarly** [comment]
Been able to reproduce this but also getting an extremely slow instance of vscode while performing the replace. 
![Screenshot 2020-02-21 at 16 33 35](https://user-images.githubusercontent.com/5208459/75052699-e971dd00-54c7-11ea-9311-2ba67cae752e.png)
