### ISSUE TITLE
ANDROID_HOME env. var. not recognized

### ISSUE THREAD

**Issue by o6l6** [Microsoft/vscode#9038]
- VSCode Version: 1.3.0
- OS Version: Windows 8.1 64bit

Steps to Reproduce:
Run "cordova build" from the command palette. It will say: "Error: Failed to find 'ANDROID_HOME' environment variable." even though ANDROID_HOME is most definitely defined, both as a user and as a system variable, and was defined before VS Code was started.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
