### ISSUE TITLE
Missing line number after exiting zen mode

### ISSUE THREAD

**Issue by ohunter** [microsoft/vscode#90393]
![pre_zen_bug](https://user-images.githubusercontent.com/2663525/74189229-44c0e700-4c0d-11ea-89b8-05839f0db4a7.png)
![2020-02-10_13-53](https://user-images.githubusercontent.com/2663525/74189253-4db1b880-4c0d-11ea-8879-bf18925ec923.png)
![2020-02-10_13-54](https://user-images.githubusercontent.com/2663525/74189262-50aca900-4c0d-11ea-9855-96b3eda9a855.png)
![2020-02-10_13-54_1](https://user-images.githubusercontent.com/2663525/74189271-530f0300-4c0d-11ea-86a0-34c3d22e0bea.png)

Issue Type: <b>Bug</b>

I know its the same issue as #86365, but it has yet to be fixed.
1. Open any document with content
2. Enter Zen mode
3. Create a new document (using hotkeys)
4. Exit Zen mode
5. Go to the document with content
6. Line numbers should be missing

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 5.3.0-29-generic

**Comment by JacksonKearl** [comment]
\duplicate #90240
