### ISSUE TITLE
Attribute requires netstandard

### ISSUE THREAD

**Issue by PlumbingWorldNZ** [microsoft/vscode#90397]
Issue Type: <b>Bug</b>

Create an Azure function using the steps described here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-csharp

Created code contains errors on the attributes (and objects): e.g. "The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'"

Adding reference to netstandard.dll doesn't help, nor does installing netstandard library nuget package.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.20.0
vscode-solution-explorer|fer|0.3.7
vscode-nuget-package-manager|jmr|1.1.6
json-escaper|jos|1.1.0
vscode-azurefunctions|ms-|0.20.2
python|ms-|2020.1.58038
azure-account|ms-|0.8.8
csharp|ms-|1.21.11
vscode-nuget-gallery|pat|0.0.7
beautify-json|ran|1.0.1
json|Zai|1.0.4

</details>

**Comment by JacksonKearl** [comment]
Is this error coming from C# or Azure Functions? You can tell by hovering over it and checking the greyed out text:
![image](https://user-images.githubusercontent.com/8586769/74197448-65d90600-4c14-11ea-8377-ef717aa5001e.png)
`ts`, in this case. 

If its coming from C# extension you can report it here: https://github.com/OmniSharp/omnisharp-vscode
If its coming from Azure Functions you can report it here: https://github.com/Microsoft/vscode-azurefunctions

**Comment by PlumbingWorldNZ** [comment]
C#, I’ll report it there, thanks.


P Please consider the environment before printing this e-mail.
