### ISSUE TITLE
Request: show basic file properties in the explorer window (size, date modified) 

### ISSUE THREAD

**Issue by arkid** [microsoft/vscode#90395]
Very simply I would like to have the option of showing some core data about each file within the explorer window aside from it's file name.  ie file size, date last modified.     It really surprises me this isn't present and would surely be quick to add.

**Comment by arkid** [comment]
@isidorn  I didn't think that customising what returns in the default explorer window is possible (hence my request)   Is there documentation to clarify that ?

**Comment by isidorn** [comment]
Yes it is not possible to add in the explorer. But the extension could add a new view in the Explorer Viewlet, and the new view could show the file properties. There is probably already an extension for this. I would first checkout the marketplace.
