### ISSUE TITLE
Fail to open large minimized file with DOM based word wrap

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#90391]
Issue Type: <b>Bug</b>

* set `editor.wrappingStrategy` to `advanced`
* open a large minimized file (for example minimized workbench.main.js which has just a few lines)
* file opening failed, with below errors

```
Failed to execute 'setStart' on 'Range': The offset 120985 is larger than the node's length (65536)..
```

ref: https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/view/domLineBreaksComputer.ts#L285

VS Code version: Code - Insiders 1.43.0-insider (8d17dc1e84d53f5fd4ed0d05fabaa3062259633d, 2020-02-10T10:42:15.424Z)
OS version: Darwin x64 19.2.0

**Comment by gino8080** [comment]
same error, needed to turn option back to **simple**
