### ISSUE TITLE
Ultimately cannot upload to the target

### ISSUE THREAD

**Issue by al-davis** [microsoft/vscode#90392]
- VSCode Version:  1.42
- OS Version: Win10 latest update
Steps to Reproduce:

1.Open new project with platformio 
2.add line printf("Hello World"); on loop
click checkmark in bottom of page blue highlited area
popup at top of window "Select task to run" with build as only choice
click "build" & get the following in the terminal window.

Does this issue occur when all extensions are disabled?: Yes/No yes
[ReqHelpVScode.txt](https://github.com/microsoft/vscode/files/4182996/ReqHelpVScode.txt)

**Comment by JacksonKearl** [comment]
Please report this on the platformio repository. https://github.com/platformio/platformio-vscode-ide
