### ISSUE TITLE
Codelens showing number of references twice!

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode#90396]
- VSCode Version: 1.42.0
- OS Version: 10.15.2 Mac

Steps to Reproduce:

1. Go to existing project with lot of dependencies.
2. look at the class/func being declared.  There will be small snippet at top telling you number of references you have. 
3. Need to have jsconfig.json and have codelens for js enabled. 

![Screen Shot 2020-02-10 at 4 54 25 PM](https://user-images.githubusercontent.com/4664695/74194323-09cbad00-4c27-11ea-8eae-79788db2d3df.png)

Is it normal behavior? do they tell two different things?

Does this issue occur when all extensions are disabled?: Yes

Tried with Insider as well

**settings.json**
```

 {
    "javascript.referencesCodeLens.showOnAllFunctions": true,
    "javascript.referencesCodeLens.enabled": true,
    "editor.formatOnSave": true
}
```

Left one is wrong since it counts the declaration as a reference too, maybe subjective but annoying for sure. It's not a new problem, I think I first noticed it in Sep 2019. 

**For Example:**
Left one (wrong)
![image](https://user-images.githubusercontent.com/4664695/74194786-f836d500-4c27-11ea-8709-4f1c2dc7e5eb.png)

Right one (correct)
![image](https://user-images.githubusercontent.com/4664695/74194822-07b61e00-4c28-11ea-8291-38e3ee2755a9.png)

**Comment by techsin** [comment]
I had this issue for a while not with latest update. I probably first noticed like Sep 2019.

**Comment by mjbvz** [comment]
Please share a complete, self contained code example (as text!)

**Comment by techsin** [comment]
https://github.com/techsin/vscode_bug_double_references

**Comment by techsin** [comment]
I've created the repo. Minimal. Turns out adding PropTypes to a function being exported is what triggers it. Hopefully that is of some importance.

**Comment by mjbvz** [comment]
Thanks @techsin! Very simple repo:

```js
function A() {
  console.log("hi");
}

A.x = {};
```

**Comment by techsin** [comment]
Thanks for quick action
