### ISSUE TITLE
Endless toast popups

### ISSUE THREAD

**Issue by drawcard** [microsoft/vscode#90399]
Issue Type: <b>Bug</b>

Video of issue: 
![2020-02-11 09 27 46](https://user-images.githubusercontent.com/1435638/74198249-d5043800-4cb0-11ea-89c0-c5a5e6da858f.gif)

Can't dismiss the toast, it keeps replacing itself

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-inky-snippets|ade|1.0.1
vscode-browser-preview|auc|0.5.9
git-commit-message-helper|D3s|1.2.0
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
prettier-vscode|esb|3.20.0
comment-anchors|Exo|1.6.1
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
html-tag-wrapper|hwe|0.2.3
path-autocomplete|ion|1.13.3
auto-comment-blocks|kev|1.0.1
cssSuggestions|kun|1.0.11
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
vscode-foundation6-snippets|nat|0.0.1
material-icon-theme|PKi|3.9.3
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.2
faster-new|wen|1.0.7
wordpress-toolbox|wor|1.3.6
markdown-all-in-one|yzh|2.7.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by misolori** [comment]
Can you post a screenshot and can you try disabling all of your extensions to see if this persists? Then you can enable one by one until you find the culprit extension.

**Comment by drawcard** [comment]
Just posted a screenshot. Will try disabling extensions when I get a moment

**Comment by drawcard** [comment]
Just restarted VSCode and the problem has gone way, will test again if it returns :)

**Comment by misolori** [comment]
Thanks, go ahead and re-open if this happens again. cc @mattbierner
