### ISSUE TITLE
VSCode should have hidden the cursor automatically when I was typing

### ISSUE THREAD

**Issue by larryw3i** [microsoft/vscode#90394]
VSCode should have hidden the cursor automatically when I was typing

**Comment by pumpkinlink** [comment]
#79915

**Comment by JacksonKearl** [comment]
Quoting from #79915:
> VS Code is based on Electron, which is based on Chromium. This is an upstream issue in Chromium which was previously reported here -- https://bugs.chromium.org/p/chromium/issues/detail?id=254430
