### ISSUE TITLE
Massive issue on Mac OSX with emoji

### ISSUE THREAD

**Issue by codepo8** [Microsoft/vscode#904]
I don't know what's going on, but when you insert an emoji, there is some odd repetition of markup happening. 
![emoji](https://cloud.githubusercontent.com/assets/13508/11526767/b3ec737e-98d4-11e5-984d-668210fdcdde.gif)

**Comment by be5invis** [comment]
Perhaps related to non-BMP character handling?

**Comment by alexandrudima** [comment]
Indeed, input handling is ... difficult to get right :)

**Comment by alexandrudima** [comment]
@weinand Does this work as expected now?

**Comment by weinand** [comment]
@alexandrudima this seems to work now. I couldn't reproduce the problem from above. But I'm not sure what tool @codepo8 was using to insert the emojis.

**Comment by anoff** [comment]
Still experiencing this issue on code `1.10.1`
![zyyaoycnym](https://cloud.githubusercontent.com/assets/7142618/23572355/e1da4790-006e-11e7-8076-7090f394e086.gif)
