### ISSUE TITLE
Support sanctioned package.json comment style

### ISSUE THREAD

**Issue by clavecoder** [Microsoft/vscode#9040]
# Suggestion
`npm` sanctions the use of the `"//"` property for comments in `project.json` [\[1\]][1] [\[2\]][2], but vscode JSON intellisense complains. Allow this comment style in project.json files in opened npm project folders.

## Environment
- VSCode Version: 1.3
- OS Version: Windows 10

## Steps to Reproduce

1. Add `"//": "...",` to `project.json`.
2. Observe green undersquiggle with tooltip: `Duplicate object key`.

[1]: https://groups.google.com/forum/#!msg/nodejs/NmL7jdeuw0M/yTqI05DRQrIJ
[2]: https://github.com/npm/npm/issues/4482#issuecomment-32267045

![vscode-issue](https://cloud.githubusercontent.com/assets/3524633/16716658/ed7402d6-46c8-11e6-8f21-6ed8db8ccf8f.PNG)

**Comment by clavecoder** [comment]
In retrospect, the error is for multiple properties names "//", which is a JSON rule not an NPM issue. One would have to inquire with the good folks at NPM, whether that was their intention, or if it was only that they would never use the "//" property or dis-allow it.

**Comment by aeschli** [comment]
I don't see us adding package.json specific syntax checking or syntax highlighting in the near future, especially given the ongoing (heated) discussions. An extension could do that, however.
