### ISSUE TITLE
Small warning when submitting a bug report

### ISSUE THREAD

**Issue by drawcard** [microsoft/vscode#90403]
When submitting a bug report via VSCode, if the message is too long, it is copied to the clipboard. However there is no warning given to the user about that, so if there is something important currently in the clipboard, it gets lost.

Perhaps a character counter or other prompt would be handy to give the user a chance to back out or save their clipboard contents elsewhere. Or maybe even offer to export a text file instead?

**Comment by RMacfarlane** [comment]
@drawcard What version of VSCode are you using? There should be a dialog asking to confirm writing to the clipboard now:
![Screen Shot 2020-02-10 at 3 59 05 PM](https://user-images.githubusercontent.com/3672607/74201363-637ba980-4c1e-11ea-8562-07807d94f40f.png)

**Comment by drawcard** [comment]
I'll check when I'm back in the office. But it may have been prior to the January 2020 update, if that was when the feature was added.
