### ISSUE TITLE
Saving SVG files will stall subsequent file saves

### ISSUE THREAD

**Issue by chanmathew** [microsoft/vscode#90400]
**Bug Report**
When opening and saving any SVG files, it will cause a delay in saving subsequent files even if they are small code files. This has the side effect of breaking linters and code formatters like Prettier as well that rely on "Format on Save".

**Steps to reproduce:**
1. Open an SVG file, make an edit, then save
2. Subsequent file saves will be delayed, thereby causing linters and code formatters like Prettier to no longer trigger as there is a file save delay.

**Comment by jrieken** [comment]
This lacks basic and specific information

- what version of vscode are you using
- does this reproduce when 'format on save' is disabled
- do you see a progress notification talking about save participants
