### ISSUE TITLE
Unable to load library

### ISSUE THREAD

**Issue by StevenTheGit** [microsoft/vscode#90407]
Issue Type: <b>Bug</b>

I was trying to import selenium and it didn't work. It said:  "Unable to import selenium, pyplint(import error)". So I went into the terminal and typed: "pip install selenium" in case I didn't installed it yet. But it said that all requirements are satisfied. I re-saved my code and it still had the error. What is happening? I don't know what to do. Please help.

![image](https://user-images.githubusercontent.com/54953179/74201307-5a4b0680-4c37-11ea-9080-f9a17f9cd2d8.png)

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (2.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.15
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.1.58038
deepdark-material|Nim|3.2.0
vscode-css-peek|pra|3.0.2
vscode-yaml|red|0.7.2
LiveServer|rit|5.6.1

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the python extension
