### ISSUE TITLE
Add quick pick option without input filtering

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#90402]
Currently for Settings Sync, we show this dialog with filtering:

![image](https://user-images.githubusercontent.com/35271042/74197311-12ff4e80-4c14-11ea-8400-50e4967daa0c.png)

It would be great if we had an option to hide the input filter when it doesn't make sense, like on short lists where there's no need to filter. It could look something like this:

![image](https://user-images.githubusercontent.com/35271042/74198590-9fab0c00-4c16-11ea-8a1d-b5f570e24f21.png)

cc @sandy081 @Tyriar @RMacfarlane

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/89595
