### ISSUE TITLE
Keep window maximized when screen resolution changes

### ISSUE THREAD

**Issue by johnendev** [microsoft/vscode#90412]
Issue Type: <b>Bug</b>

When ever the screen resolution changes, the VS Code window becomes un-maximized.
The window should stay maximized.

This has been an issue for as long as I can remember using VS Code.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
This sounds like the OS should take care of it. I doubt VSCode should do something specifically.

**Comment by johnendev** [comment]
@bpasero VS Code manages it's own window state. There is a setting to always start maximized for example, if the window was maximized last time VS Code was closed.
This issue happens in another electron based app as well, so maybe it's a bug on that end. VS Code knows the window has become un-maximized though as clicking maximize brings it back to the correct state. With the other app, it seems to not be aware of the window state change and you have to click it twice.

A probably related issue is, if you use win+shift+left or win+shift+right to switch between displays it also doesn't maintain the maximized state.

**Comment by bpasero** [comment]
@johnendev would you mind filing an issue against Electron itself if you can e.g. reproduce with their app: https://www.electronjs.org/fiddle

**Comment by johnendev** [comment]
@bpasero I've tested Electron Fiddle and results are as follows

**Electron v6.1.6 (currently used by VS Code)**
This issue is present

**Electron v6.1.7**
This issue is present

**Electron 7.0.0**
This issue is fixed

Guess that means just wait for VS Code to upgrade to a newer version of Electron. I see it's in progress already: (#90371)

**Comment by bpasero** [comment]
@johnendev interesting, our insider builds already run with Electron 7. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by johnendev** [comment]
@bpasero ok, tested it on the insiders build and the maximized state is preserved correctly.
There is another issue though, with the rendering and dimensions after the screen resolution has changed. Should I create a new issue for that and close this one, or add details here?

**Comment by bpasero** [comment]
Yes.
