### ISSUE TITLE
quick fix: up/down key should rewind when selected first/last item

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#90410]
By default the first (top) item is selected among the items suggested by Quick Fix, and assuming the one I want to select is at the bottom.

As someone who prefers keyboard navigation using up/down keys, and because there're too many items to scroll down, I pressed the up key, expecting the last item at the bottom to be selected, just finding it doesn't work, hence this request, thanks!

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

**Comment by JacksonKearl** [comment]
We use native context menus for the quick fix selection, which don't typically wrap. However, you can use Cmd+Down or Cmd+Up to go to bottom/top.

**Comment by ryenus** [comment]
@JacksonKearl thanks! Cmd+Down helped.
But may I ask why using native context menu for this?  performance?
