### ISSUE TITLE
CodeLens text jumps up and down (bounces) with every keystroke when window.zoomLevel set

### ISSUE THREAD

**Issue by TEC10101** [microsoft/vscode#90413]
```
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.14393
```

AND

```
Version: 1.43.0-insider (user setup)
Commit: 8d17dc1e84d53f5fd4ed0d05fabaa3062259633d
Date: 2020-02-10T09:59:32.290Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393
```

Steps to Reproduce:

1. set settings.json `"window.zoomLevel": -1` (or 2 works to show issue as well)
2. enable codeLens with gitLens or by set settings.json `"typescript.referencesCodeLens.enabled": true`
3. type in a file with codeLens (like a TS file) and you'll notice every key the codeLens text bounces up and down

Does this issue occur when all extensions are disabled?: Yes

See prior issue unable to reproduce: https://github.com/Microsoft/vscode/issues/56688#issue-351617009

**Comment by jrieken** [comment]
This is likely electron related not outside our control, tho 1.42 should use the same electron version as 1.41. @TEC10101 Can you confirm that you seeing this also with 1.41

**Comment by TEC10101** [comment]
I cannot confirm or deny that @jrieken.

I can confirm that it is not present on Mac:

```
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by bpasero** [comment]
@TEC10101 does this still reproduce with our latest insider bits?
