### ISSUE TITLE
[C/C++] Allow IntelliSence with fieldname struct initialization

### ISSUE THREAD

**Issue by Loen10** [microsoft/vscode#90417]
When initializing a struct with fieldnames, IntelliSence should pop up.

![struct-init](https://user-images.githubusercontent.com/38378951/74211281-71e0ba00-4c4c-11ea-824b-019a48e34c82.png)

This is more of a C feature as I don't think C++ has this type of initialization, but the IntelliSence for C is bundled with the C/C++ extension.

**Comment by JacksonKearl** [comment]
Please file here: https://github.com/Microsoft/vscode-cpptools
