### ISSUE TITLE
No response for FORWARDED PORTS 

### ISSUE THREAD

**Issue by axiqia** [microsoft/vscode#90416]
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

CPUs | Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1512)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 3.91GB (0.45GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Remote | SSH: sxue
-- | --
OS | Linux x64 4.9.168
CPUs | Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz (96 x 2699)
Memory (System) | 376.78GB (3.37GB free)
VM | 0%

Steps to Reproduce:

1. Connect to a remote server
2. Try to add a `FORWARDED PORTS` in `Remote Explorer`
3. No response

**Comment by alexr00** [comment]
What port are you trying to forward?

**Comment by axiqia** [comment]
@alexr00 there is even no input window when I click the add button.

**Comment by alexr00** [comment]
Can you share a gif or screen shot? Are you using the "+" button?

**Comment by axiqia** [comment]
![image](https://user-images.githubusercontent.com/22564578/74228799-22f25d80-4cfc-11ea-8b01-9f641de230ca.png)

**Comment by alexr00** [comment]
Thanks! Can you open the dev tools and see if there's anything in the console?

**Comment by axiqia** [comment]
@alexr00 Yep. When I click the "+"  button, there is an error in the console.
![image](https://user-images.githubusercontent.com/22564578/74259572-13dad200-4d33-11ea-9ca8-61b0f516d037.png)

**Comment by alexr00** [comment]
@axiqia thanks for helping track this down. Would you be able to test with the next(in 1-2 days) Insiders build to see if you still can't forward a port? Insiders installs side by side with stable, so you wouldn't lose anything by installing it. https://code.visualstudio.com/insiders/

**Comment by axiqia** [comment]
@alexr00 I'd like to. Please notify me if the next build is released.

**Comment by alexr00** [comment]
@axiqia We've had a couple build that contain the fix now. If you install Insiders you'll get a build with the fix. Thanks for testing this!

**Comment by axiqia** [comment]
@alexr00 Thank you for fixing the bug. I have tested the fix. It works in my env.
