### ISSUE TITLE
Extension views contributions permanently cached.

### ISSUE THREAD

**Issue by dougwollison** [microsoft/vscode#90414]
I wanted to try making an extension but I ran into a very odd road block pretty quickly on when I experimented with view contributions. It seems that VS Code caches the container assignments for views, permanently.

- VSCode Version: 1.42.0
- OS Version: macOS 10.15.3

---

Steps to Reproduce:

1. Setup a new extension (I've been using the Yeoman tutorial)
2. Register a custom view; I initially put it under `explorer`.

```
"views": {
    "explorer": [
        {
            "id": "myissuePanel",
            "name": "My Issue"
        }
    ]
}
```

3. Save and run the debugger. The view will appear in the explorer container as expected.
4. Now, register a new container, and re-assign the custom view to it (becaues you realize your extension is better with it's own activitybar item).

```
"viewsContainers": {
    "activitybar": [ {
        "id": "myissue",
        "title": "My Issue",
        "icon": "path/to/some/icon.svg"
    } ]
},
"views": {
    "myissue": [ {
        "id": "myissuePanel",
        "name": "My Issue"
    } ]
}
```

5. Save and run the debugger again. The view will remain in the explorer container, in a different order than before as well.

---

Further Steps for Sanity:

6. Change the ID of the view and try again, it will show up normally.

```
"views": {
    "myissue": [ {
        "id": "myissuePanel1",
        "name": "My Issue"
    } ]
}
```

7. Now assign this renamed view back to explorer, but don't delete the viewsContainers entry. Running it this time will cause the view to stay in the container until you remove it's entry, at which point it will appear in the explorer and stay there.

```
"views": {
    "explorer": [ {
        "id": "myissuePanel1",
        "name": "My Issue"
    } ]
}
```

---

I've tried this on two separate macs, as well as a windows machine though not as thoroughly. My assumption is Code caches the contributions, but only updates that cache when the container it's being assigned to is no longer registered. Restarting both the app and my machine has shown no effect. If I start a new extension project with a different name, but use the same names in step 4 for my view/container, the view still shows up in the explorer instead. If I run the code from another user account, it will correctly place the view in the container until I start changing it, so the cache is user level.

I know this can be avoided by simply changing the name of the view, it's just annoying having to change an ID for the sake of bypassing a cache. Plus, it suggests that if a production extension was changed to move views into a different container, previous users would not get those changes.

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
fixed by 8f286708860325a176d1a7d0eb80e0ca55cacb56
