### ISSUE TITLE
vscode did not highlighted the changed files or new files in repo tree?

### ISSUE THREAD

**Issue by alansplaza** [microsoft/vscode#90420]
版本: 1.42.0
提交: ae08d5460b5a45169385ff3fd44208f431992451
日期: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

Steps to Reproduce:

1. Using remote ssh connected to linux.
2. The changed files in remote server did show highlight color at sidebar in vscode.

![image](https://user-images.githubusercontent.com/11846497/74213821-e27fe900-4cd5-11ea-9734-bdd7c8ad1a80.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alansplaza** [comment]
I checked several servers. Only one had this issue. Does anyone know the reason? Maybe the server lacks of some dependent libs?

**Comment by joaomoreno** [comment]
Can you compare the versions of git across the servers?

**Comment by PoundXI** [comment]
I also have a same problem on Ubuntu 18.04 x64 with git 2.25.0 and fresh installed vscode from snap (c47d83b2).
I create a new git repo and made file change and create new file. But..
- No color highlighted in file explorer.
- Not showing file diff when clicking "Open changes" button.

**Comment by joaomoreno** [comment]
@alansplaza Can you compare the versions of git across the servers?

**Comment by PoundXI** [comment]
@joaomoreno It not happens in repo created with git version 2.17.0.

**Comment by joaomoreno** [comment]
@PoundXI is it related to which version the repo gets created with, or rather with which version VS Code uses? Please provide more details.

**Comment by PoundXI** [comment]
@joaomoreno Sorry to cause confusion.
It may not related to repo create with or vscode use. Both version works fine.
But I think vscode detect changes slow with unknown reason.
Sometimes fast, sometimes more than 3 seconds.
And first time I reported may very very slow with many minutes.
If I encounter a problem again, I'll test for more details and let you know.
Thank you.
