### ISSUE TITLE
output window is not realtime!

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [Microsoft/vscode#9042]
- VSCode Version: 1.3
- OS Version: 8.1-64

hi, i wrote a simple python script and run it from output window(not terminal):

    for i in range(1,1000001):
        print i

after while output window show: 1,2,3,...,9568
then output will freeze and again after while show another part: 9569,9570,...,18536
and again,again,again... 

**BUT** if i run this script in terminal, all numbers will print one after another: 1,2,3,4,....,1000000

in the other words: output window is not real time or live!

**Comment by DonJayamanne** [comment]
This issue has been moved to DonJayamanne/pythonVSCode/issues/203
