### ISSUE TITLE
When using *ngFor="let i = index", the colors of closing divs are wrong

### ISSUE THREAD

**Issue by Hagay-Reinman** [microsoft/vscode#90428]
- VSCode Version: 1.42.0
- OS Version: Ubuntu 18.04.3 LTS 
When using ngFor; let i = index, the div closing are highlight with Black instead of Brown
Steps to Reproduce:
1. Create simple html with
`<div *ngFor="let i of columns" ><button >{{i}}</button></div>`
`<div *ngFor="let i = columns" ><button >{{i}}</button></div>`
2. See that the first </div> is in the same color as it <div>, but the second on is in black.
3. Pay attention that the problem is happening when the </div> is no in the same row, as in the attached picture.
4) The problem does not exist in code_1.40.2-1574694120_amd64.deb

Does this issue occur when all extensions are disabled?: Yes
![Selection_124](https://user-images.githubusercontent.com/45554685/74220186-8f973900-4cb7-11ea-92f2-0cddd9dbdb65.png)

**Comment by JacksonKearl** [comment]
Are you using an extension for Angular syntax highlighting?

**Comment by JacksonKearl** [comment]
I'm guessing you're using https://github.com/angular/vscode-ng-language-service, please file an issue on that repository.

**Comment by Hagay-Reinman** [comment]
As I wrote I had a problem when I start VS-code without any extension.
In any case I am not using  Angular syntax highlighting.
When I am downgrading to VS-code 1.40.02, the problem does not exist.
Thanks
Hagay

**Comment by JacksonKearl** [comment]
With no extensions we do not know about anything Angular specific, so I see the attributes highlighted as simple text strings:
![image](https://user-images.githubusercontent.com/8586769/74350776-0f321000-4d6b-11ea-9347-0b160931122f.png)

With the Angular extension, the JavaScript syntax is injected into the HTML syntax for all `ng-binding`'s, so we get syntax highlighting in the quoted string, but in this case a bug in their injection causes it to never stop injecting JavaScript's syntax, even after the string terminates.

![image](https://user-images.githubusercontent.com/8586769/74351183-a39c7280-4d6b-11ea-8b3b-1626dd6c35b8.png)

![image](https://user-images.githubusercontent.com/8586769/74351216-ae570780-4d6b-11ea-887a-72e827f64ba5.png)

If you're seeing this highlighting but you're sure you don't have the Angular extension installed, could you run `Developer: Inspect Editor Tokens and Scopes" and share what the window shows at the `div`?

**Comment by Hagay-Reinman** [comment]
Hi
I checked again, and somehow the problem disappeared also in 1.42.0.
So you can close this case.
Thanks for the help
Hagay
