### ISSUE TITLE
Editing File name exits automatically after a very short time

### ISSUE THREAD

**Issue by akash1997** [microsoft/vscode#90423]
Issue Type: <b>Bug</b>

1. Right click on a Folder.
2. Click on New File.
or
1. Right click on an existing file.
2. Click on rename.

The cursor to type the name of the file blinks for a very short duration and exits the rename automatically. It takes multiple tries to just rename a single file.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.15.0-76-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|7.69GB (1.28GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.11
gitlens|eam|10.2.1
python|ms-|2020.1.58038

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by gjsjohnmurray** [comment]
Also probably worth testing with all extensions disabled.

**Comment by akash1997** [comment]
Hi guys, I am really sorry for replying so late, but even I am not able to reproduce the issue. If it starts happening again, I will reopen the issue.
