### ISSUE TITLE
Inconsitency of (CTRL+H CTRL+F) and (CTRL+SHIFT+H CTRL+SHIFT+F)

### ISSUE THREAD

**Issue by andreElrico** [microsoft/vscode#90429]
VSCODE INFO:

Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.4.0-170-generic

Steps to Reproduce:

1. use CTRL+SHIFT+H => Global find and replace opens
2. use CTRL+SHIFT+F =>  The "replace field" vanishes and we have "global find"

Now lets do the same in a **random file**:

3. use CTRL+H => box with "find and replace" opens
4. use CTRL+F => The same "search and replace box" is present. I will have to close it first and then use "CTRL+F"

**Expected Behavior**

In step 4 I would like for that the "replace"-row vanishes and the box looks like normal "CTRL+F", so it behaves exactly like the "global"-counterpart.

**Comment by sreeragh-ar** [comment]
I am working on this issue.

**Comment by sreeragh-ar** [comment]
I worked on it as part of the open-source night.
https://www.meetup.com/Hyderabad-Open-Source-Development-Night/events/268532015
I could reproduce the issue but could not fix and I do not think my schedules will let me spend any more time on the issue.

**Comment by andreElrico** [comment]
Thank you for trying @sreeragh-ar

**Comment by codymaust** [comment]
i'm working on this issue
