### ISSUE TITLE
enableProjectDiagnostics "collects" type definition from node_modules

### ISSUE THREAD

**Issue by enko** [microsoft/vscode#90430]
I tried the insider build and set `enableProjectDiagnostics` to true, but it is for me not right usable, because you "collect" over the time of the vscode runtime many type definitions.

For example I have this file:

```typescript
export function log(logString: string) {
    console.dir(logString);
}
```

If follow to the definition of `console.dir` and it shows me instantly the "problems" of `globals.d.ts` and then of many other dependent files, even if I close `globals.d.ts`.

See the attached screenshot:

![grafik](https://user-images.githubusercontent.com/19407/74222476-e5b6ad00-4cb4-11ea-8050-e6d18fdfd259.png)

As you can see the issues of the `test.ts` file are drowned in the issues of the type definitions which are primary linting issues of `tslint-language-service`, which I do not care much of, at least in the type definitions.

**Comment by mjbvz** [comment]
Can you share a small project that demonstrates this? I don't see this behavior

**Comment by enko** [comment]
@mjbvz Sure.

Here you go: https://git.sr.ht/~xaffe/vscode-issue-90430

Repro Steps:

```
git clone https://git.sr.ht/~xaffe/vscode-issue-90430
cd vscode-issue-90430
npm ci
```

Open the Project in vscode and switch to the workspace typescript, open `src/test.ts` and monitor the problems tab.

I think the problem here stems from `tslint-language-service` that I'm using inside the project. Maybe I need to tell it, not to lint `node_modules`? If that is even Possible?

**Comment by enko** [comment]
Oh, if I would have used [`typescript-tslint-plugin`](https://github.com/Microsoft/typescript-tslint-plugin) I would have not have had that issue 🤦‍♂ 

Sorry for the noise!
