### ISSUE TITLE
Clear search scope when find widget is hidden

### ISSUE THREAD

**Issue by dend** [Microsoft/vscode#9043]
- VSCode Version: 1.3.0
- OS Version: macOS X El Capitan 10.11.5 (15F34)

Steps to Reproduce:

1. Open a Markdown file (`.md`)
2. Select a fragment that has the `bold` formatting included (`**`).
3. Use `Command + F` to Find, then expand the little popup to `Replace`.
4. In the replace field, type in the code delimiter character (```).
5. Perform replace.
6. Now press `ESC` and select another line that has `bold` formatting included (`**`).
7. `Command + F` to find - notice that it says `No results`

![screenshot 2016-07-10 17 11 35](https://cloud.githubusercontent.com/assets/1389609/16717051/653d32ee-46c2-11e6-90af-db4ba2caf69d.png)

**Comment by alexandrudima** [comment]
@dend I'm not sure I understand what the bug is. Please note: In 1.3.0 the find in selection does not auto-activate when opening the find widget and having a multi-line selection because it interferes and blocks multi-line search.

Here I am doing what you describe and it seems to function ok for me - sorry about the gif contrast which makes it difficult to see the find-in-selection range:
![find-in-selection](https://cloud.githubusercontent.com/assets/5047891/16727109/1cb53a2a-4768-11e6-8c7c-eec1bc53d7c7.gif)
:

**Comment by dend** [comment]
@alexandrudima here is what I am talking about:
![tempgif](https://cloud.githubusercontent.com/assets/1389609/16756003/bf6da1dc-47b6-11e6-8acd-98ef0e3c3bb6.gif)

**Comment by alexandrudima** [comment]
@dend The find in selection button sets the search range when it is clicked. So if you select lines at the beginning of the file and the click the find in selection button, the search range will be those lines at the beginning of the file.

Moving the selection afterwards does not change the search range, it always remains that at the beginning of the file (as that was defined when the button was clicked).

To improve our behaviour in this area, what would you expect? Should the search range be cleared when closing the find widget?

**Comment by dend** [comment]
Thanks for the clarification, @alexandrudima.

My personal expectation would be to clear the selection context when I press `ESC` (in the scenario above, I did so). Selecting a new line after that and seeing the old line as the context is somewhat useless because I already have shown my intent to cancel out of it, but the editor maintains it.

**Comment by sandy081** [comment]
@alexandrudima <kbd>esc</kbd> is behaving differently in following scenarios

Scenario 1:
1. Select some text where there is at least one find match
2. <kbd>ctrl</kbd>+<kbd>f</kbd> to open find widget. Provide search string
3. <kbd>esc</kbd> to cancel
Notice that selection is cleared

Scenario 2:
1. Select some text where there is no find match
2. <kbd>ctrl</kbd>+<kbd>f</kbd> to open find widget. Provide search string
3. <kbd>esc</kbd> to cancel
Notice that selection is not cleared

See the attached videos:

![jul-28-2016 12-27-58](https://cloud.githubusercontent.com/assets/10746682/17209810/6731d720-54bf-11e6-9695-3830b25b2c61.gif)


![jul-28-2016 12-28-55](https://cloud.githubusercontent.com/assets/10746682/17209815/6c01076c-54bf-11e6-9766-1b9a054f81dc.gif)

**Comment by alexandrudima** [comment]
@sandy081  This issue is about the search scope which gets removed in both cases, not about the editor selection

**Comment by sandy081** [comment]
@alexandrudima Agreed. Filed a new issue for the editor selection scenario - https://github.com/Microsoft/vscode/issues/10536
