### ISSUE TITLE
Unable to install extension on vscode/Windows 10

### ISSUE THREAD

**Issue by alexearnshaw** [microsoft/vscode#90439]
Issue Type: <b>Bug</b>

Installed the latest stable version of vscode on new Windows 10 laptop and tried to install the markdownlint extension. The installation failed with the error:
>EBUSY: resource busy or locked, rename 'C:\Users\aearnshaw.vscode\extensions.davidanson.vscode-markdownlint-0.34.0' -> 'C:\Users\aearnshaw.vscode\extensions\davidanson.vscode-markdownlint-0.34.0'
Failed Installing Extensions: DavidAnson.vscode-markdownlint

I was able to install the extension manually with the extension author's help.

However, when someone from vscode looked at the issue they indicated it was a vscode bug so I am opening it here.

More details are available on this issue in markdownlint project https://github.com/DavidAnson/vscode-markdownlint/issues/104

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.73GB (7.03GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.41.9
vscode-markdownlint|Dav|0.34.0
markdown-shortcuts|mdi|0.12.0
code-spell-checker|str|1.7.22
errorlens|use|2.9.0

</details>

**Comment by alexearnshaw** [comment]
@sandy081 I've created this issue as requested

**Comment by sandy081** [comment]
@bpasero I am using `path` module in `common` and it is not joining correctly when a folder starts with `.`

https://github.com/microsoft/vscode/blob/57ac3ed29dbefcd74377cca6f2df284f302a4076/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L464-L465

**Comment by bpasero** [comment]
@sandy081 please follow up with @sbatten who created this library from the node.js version. Check if you can reproduce with bare node.js and if not we might have to bring our library up to speed with latest.

**Comment by sandy081** [comment]
@sbatten Can you please provide steps for the user to repro it using node.js.

**Comment by bpasero** [comment]
@sandy081 can we not simply conduct a test ourselves to join a path with "." in node.js and compare that to our version?

**Comment by sbatten** [comment]
`join('C:\\Users\\sbatten\\Desktop', '.myFolder')` produces the same output for our module and the node version.

**Output** `C:\Users\sbatten\Desktop\.myFolder`

**Node Version** `v10.16.2`

**Comment by sandy081** [comment]
@sbatten Can you please provide steps to user to repeat the same on their machine?

**Comment by sbatten** [comment]
I don't think we could ever reproduce this, I am closing as not-reproducible now. If we get more cases/info in the future we can re-open
