### ISSUE TITLE
JSON comments should not be marked as an error

### ISSUE THREAD

**Issue by jez9999** [microsoft/vscode#90438]
I'm using VS Code to get a diff of a modified JSON config file right now and JSON comments are being highlighted, loudly, as errors:

![json](https://user-images.githubusercontent.com/793830/74228487-6aef9100-4cb8-11ea-89c8-7f85b8c09962.png)

I know they go against the original JSON spec.  However, it is widely accepted as problematic that JSON doesn't allow comments when it's being used for a config file, which has resulted in many JSON parsers explicitly allowing them, including (notably) ASP.NET Core's default JSON parser.  There are also extensions to the spec like HSJON that allow comments, and how does VS Code know that such an extension isn't being used?

I think marking these comments as errors is overly pedantic, and outright wrong considering that the user could purposely be using a form of JSON that allows comments.  The errors should be removed, by default.

**Comment by IllusionMH** [comment]
VSCode supports JSON with comments format which is enabled by default for set of files (`tsconfig.json`, `settings.json` etc.) but putting comments in e.g. `package.json` will cause an error so VSCode will warn against it.

I doubt that comment should be allowed by default.

However **if you are sure that tooling support comments** in your JSON files, you can use `files.associations` to force `jsonc` format by default for those files (using full name as below or wildcard `*.json`) in your user or workspace configs.

```json
"files.associations": {
    "package.json": "jsonc" // allows comments in package.json which will lead to a runtime error
}
```
