### ISSUE TITLE
A JavaScript error occurred in the main process.

### ISSUE THREAD

**Issue by UTexas80** [microsoft/vscode#90447]
Whenever I attempt to open either VS Code I receive the following error:

"A JavaScript error occurred in the main process."

Uncaught Exception:
Error Cannot find module 'C:\Program Files\Microsoft VS Code\resources app\out\mai
Require stack: 

![VSCodeError](https://user-images.githubusercontent.com/16102161/74240235-83a37b00-4ca7-11ea-986e-49b07f06ee44.png)

I have tried to uninstall VS Code and have removed the entire directory completely but that didn't solve the issue.

Thank you

**Comment by WiFiUncle** [comment]
@UTexas80 Have you solved this problem?

**Comment by UTexas80** [comment]
WiFiUncle - Thank you for following up. The issue apparently took care of itself in VS Code v 1.46.1 & VS Code Insiders 1.47. It was persistent for quite awhile but finally is resolved (fingers crossed)
