### ISSUE TITLE
ConfigurationService - Node trigger configuration change event

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90440]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=67154&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=855ed636-0983-5316-9b28-7efa8f10a65b&l=11552

```
 1 failing

  1) ConfigurationService - Node trigger configuration change event:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

```

**Comment by sandy081** [comment]
Removed old config watcher that was used in node based configuration service in shared process, cli and main. Instead `FileService` is used everywhere whose change events are more reliable.

**Comment by bpasero** [comment]
👏
