### ISSUE TITLE
Premissions for extensions

### ISSUE THREAD

**Issue by mnini** [microsoft/vscode#90448]
I don't like the fact, that some random extension can modify files on my computer and execute shell commands.

**Comment by gjsjohnmurray** [comment]
Related to #68590

**Comment by usernamehw** [comment]
Possibly related to #52116

**Comment by mnini** [comment]
With permission basis, source code of extensions is easily filterable by code.

Actually extensions doesn't have to be "publisher" verified, while they can be verified by running in virtual machine to see if they can play with something they are not allowed to.

**Comment by JacksonKearl** [comment]
> source code of extensions is easily filterable by code.

Not really. Node allows dynamic runtime imports, so statically figuring out what a piece of code does is unsolvable. 

> verified by running in virtual machine to see if they can play with something they are not allowed to

I'm not sure what you mean by this. Could you explain further?
