### ISSUE TITLE
CPU 100% frequently when using VSCode

### ISSUE THREAD

**Issue by George-BC** [microsoft/vscode#90451]
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:
1. Open VSCode on MacBook Pro (15-inch, 2018) / 10.15.3 (19D76)
2. Use as normal with Node.JS language.

Does this issue occur when all extensions are disabled?: Yes and insiders build.

Issue is already reported [here](https://github.com/microsoft/vscode/issues/88779
) but some reason I have been make asked to make another issue. Quite frustrating, listening to Mac fans at 100% all day because of the CPU usage.

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`
