### ISSUE TITLE
ESP32 Project Inspect Hangs, multiple machines

### ISSUE THREAD

**Issue by davepl** [microsoft/vscode#90454]
Issue Type: <b>Bug</b>

My ESP32 Arduino project (I can provide the binary) cannot be inspected.  It runs to near 70% and then just exits and returns to the previous menu.  On my other machine it hangs at that point.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 12, 8|
|Memory (System)|16.00GB (1.40GB free)|
|Process Argv|-psn_0_94231|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.14.23
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
platformio-ide|pla|1.10.0
vscode-lldb|vad|1.4.5

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Please file on the platformio repo. https://github.com/platformio/platformio-vscode-ide
