### ISSUE TITLE
Format Document in HTML documents breaks lines in weird places

### ISSUE THREAD

**Issue by chrisjfinlay** [microsoft/vscode#90458]
Issue Type: <b>Bug</b>

Note: I've tried this with and without all my extensions enabled, same result

Whenever using format document on an HTML document, VSC tries to wrap text at a specific length, resulting in it randomly putting in new lines mis-paragraph where they don't make sense. I've tried this with and without Word Wrap on. See screenshots below:

This is the text unformatted:
![unformatted](https://user-images.githubusercontent.com/60757030/74250937-44931b00-4ce3-11ea-9b19-6bca5b4e450a.png)

And this is the formatted result:
![formatted](https://user-images.githubusercontent.com/60757030/74250969-54126400-4ce3-11ea-8b10-ba01d7d257a7.png)

The maximum line length I've seen seems to be 115 characters, counted from the very start of a line.

As you can see, the link to the pdf is broken at the attributes, and the paragraphs are broken wherever it can find a whitespace around that length. I've tried making the link ridiculously long as a test, and it let it go on for a seemingly unlimited length, before breaking at the attributes again.

Obviously this doesn't affect the rendering, but it's a pain to edit.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gc-excelviewer|Gra|2.1.32

</details>

**Comment by chrisjfinlay** [comment]
(I had a look at existing flags of similar issues, and it seems most of them are about breaking on certain tags or characters. This seems a bit different as it doesn't seem to happen on any specific character except a whitespace)

**Comment by JacksonKearl** [comment]
`html.format.wrapLineLength` setting should help.

**Comment by JacksonKearl** [comment]
Also, `html.format.preserveNewLines` (enabled by default) should allow you to explicitly add a break before the `<br />`, for instance, and keep that on format.

**Comment by chrisjfinlay** [comment]
Wonderful, thank you Jackson!
