### ISSUE TITLE
Notifications that timeout do not continue code path

### ISSUE THREAD

**Issue by cazfletch** [microsoft/vscode#90452]
- VSCode Version: 1.39
- OS Version: mac

When you have a notification with buttons that times out and so disappears then the code following this will not be executed, i.e `window.showWarningMessage` does not return undefined if it times out. No code is called afterwards. This means that the user has to take action or nothing will happen but in our extension we still want to do something even if the user takes no action.

Steps to Reproduce:

1. Have a message with buttons that times out and disappears no extension code is called after this. The message doesn't return undefined

Does this issue occur when all extensions are disabled?: Yes/No n/a

**Comment by JacksonKearl** [comment]
Notifications do not time out, they do hide but they can be shown again by clicking the notifications icon in the status bar:
![image](https://user-images.githubusercontent.com/8586769/74268768-477b1500-4cbd-11ea-9135-0b3e053a5edb.png)

So a user could wait until the notification disappeared, then later go in and act on it, at which point the promise would resolve. 

You might be better off using a quick pick for this, notifications aren't really intended for cases where interaction is required. https://code.visualstudio.com/api/references/vscode-api#window.showQuickPick

**Comment by gjsjohnmurray** [comment]
See also #65459
