### ISSUE TITLE
php.exe is not a valid php executable

### ISSUE THREAD

**Issue by diewaves** [microsoft/vscode#90469]
Issue Type: <b>Bug</b>

PHP intellisense don't works because VS don't recognizes my php.exe. 
I have installed PHP 7.3.7 with Xampp and included the path in my environment variables. I tried with 7.4 too, same result.

I added the following lines to my settings.json:
```
    "php.suggest.basic": false,
    "php.validate.run": "onType",
    "php.validate.executablePath": "C:/xampp/php/php.exe"
```

I tried with // and double backslash.  It still doesn't work. What can i do now?

Here is error messsage: 

> Cannot validate since is not a valid php executable. Use the setting 'php.validate.executablePath' to configure the PHP executable.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
jsrefactor|cms|2.20.5
php-pack|fel|1.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
es6-css-minify|olb|3.3.2
php-formatter|Sop|0.2.4
vscodeintellicode|Vis|1.2.5

</details>

**Comment by connor4312** [comment]
This is caused by a ENOENT being returned from spawning the executable. Make sure that the path exists and works if you use it from cmd.exe.
