### ISSUE TITLE
Fitt's law fails on high DPI & certain zoom levels: close button not reachable at upper-right corner when maximized

### ISSUE THREAD

**Issue by GeeLaw** [microsoft/vscode#90466]
- VSCode Version: 1.42.0 (user setup; ae08d5460b5a45169385ff3fd44208f431992451)
- OS Version: Windows 10 build 10.0.18363

**Steps to Reproduce.**

1. Set DPI scaling to 200% (Surface Book 2 default).
2. Open VSCode, paste the following `settings.json` and save:
```json
{
    "window.zoomLevel": 2
}
```
3. When VSCode has responded to the setting changes, maximize it. If there are multiple monitors, put it on a monitor whose upper-right corner is **not** connected to another monitor.
3. Point to the upper-right-most corner of the monitor and click. Observe.

**Expected Behavior.** The close button is hovered (in red). Clicking at that point closes the window.

**Actual Behavior.** The close button is not hovered (not in red). Clicking at that point has no effect.

**Does this issue occur when all extensions are disabled?** Yes.

**Comments.** Notepad, Explorer and UWP apps (basically, any app that uses a system-provided non-client area) implements Fitt's law --- when they are maximized, they can be closed by throwing the pointer to the upper-right corner of the monitor and clicking. VS Code uses Electron, which seems to implement its own non-client area. It should also implement these standard UI features. This problem seems to happen with other Electron-based apps, too, e.g., Slack (specific zoom levels needed). The problem also reproduces at zoom level 4, 5, 6 among -2 to 6.

**Comment by sbatten** [comment]
@GeeLaw I am using a SurfBook2 with default 200% scaling and cannot repro the issue. A maximized vs code successfully closes for me using the upper right most pixel of the screen.

**Comment by GeeLaw** [comment]
@sbatten Thanks for the info. I tried again and figured out that the problem reproduces only for certain `window.zoomLevel`s. Among `-2` to `6`, the levels `2`, `4`, `5`, `6` will reproduce this problem. I'll update the issue description.

**Comment by sbatten** [comment]
turns out this is failing because `window.innerWidth` is rounding down and thus our entire workbench is ~1px offset from the right side of the window. not sure why `body` rounds up and `window` rounds down, but we can't use the `body` dimensions because they aren't reliable on window resize events.

@deepak1556 @bpasero any ideas?

**Comment by vainamov** [comment]
In addition to #106801, this was also fixed for me in 9de65ab77e587cf7ab5dd00ea301cd5431b0f397.

**Comment by sbatten** [comment]
@deepak1556  should this be resolved now?

**Comment by deepak1556** [comment]
@GeeLaw can you confirm if this is still an issue with latest insiders https://code.visualstudio.com/insiders/ ?
