### ISSUE TITLE
Allow moving debug viewlet items to the panel

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#90468]
Tracking issue for adopting movable property in debug views

**Comment by sbatten** [comment]
with my commit, views can be moved, but there are a few rough edges.

1) When all views are moved, there is an empty viewlet with the launch config selector toolbar.
2) I didn't allow moving the simple start view because the above. if they moved together, maybe it would make more sense.
3) Most of the views have some header actions on hover. When they are the only view in the container (pre-existing issue in sidebar), these actions are not visible. e.g. If watch is the only view in the view container, you have to know to right click the pane and `add expression`

**Comment by isidorn** [comment]
To tackle 1 and 2 I suggest the following limitation for now: if a view is the last view in the container it is not moveable.
3 is fine for now. 

I saw your changes to the debug views and they make sense overall. My only concern is that this feels like a lot of duplication, and I am not sure if the view should be the one that cares about having proper background based on where it is located. Does it make sense to extract this out of the views, so we avoid duplication and make adoption more easier?

**Comment by isidorn** [comment]
Also let me know if you would like me to adopt the Explroer or if there is some more work needed in the debug views.

**Comment by sandy081** [comment]
If user decides to move all views and leave it empty then it is up to the user. I think having special logic to not to move view when single might make things confused. So I would allow move them all and show the empty viewlet. How about unpinning the viewlet when empty?

**Comment by sbatten** [comment]
After discussion, we will leave the current state as-is and allow the user to configure.
