### ISSUE TITLE
Weirdly pixelated mouse cursor when opening a new tab

### ISSUE THREAD

**Issue by DarkCircles** [microsoft/vscode#90467]
Issue Type: <b>Bug</b>

The mouse cursor changes to a weirdly and overly pixelated "open hand" when I move it the right of an open tab in the open space at the top where I can double click to open a new tab/document.  I am running duel 4k monitors scaled at150% (Windows 10).

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32
mssql|ms-|1.8.0
python|ms-|2020.1.58038
powershell|ms-|2020.1.0
material-icon-theme|PKi|3.9.3

</details>

![VS Code pixelated mouse](https://user-images.githubusercontent.com/37905547/74260475-2c110980-4cbf-11ea-8ed1-4f9ea4bd2778.png)

**Comment by JacksonKearl** [comment]
This is the system rendering of `cursor: grab` in Windows.
