### ISSUE TITLE
Stuck in python2 mode on macOS

### ISSUE THREAD

**Issue by bcdady** [microsoft/vscode#90463]
Issue Type: <b>Bug</b>

Similar to https://github.com/microsoft/vscode/issues/89037#issue-553001407, 
when launching code from the terminal, I get this error:

```zsh
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory
```
I'm successfully using Python3 on this system, however since python2 is still installed in the (Catalina) OS, it seems code's runtime is defaulting there.

```zsh
Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!
```

I will attach my trace results for more context.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 6|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bcdady** [comment]
As was suggested in #89037, I edited `code` to echo realpath. Here's what I got:

```zsh
added realpath echo:
/usr/local/bin/code
Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!
     PYTHONPATH is currently: "/Users/bryandady/Library/Python/3.7/lib/python/site-packages/:/usr/local/lib/python3.7/site-packages"
     You should `unset PYTHONPATH` to fix this.

end realpath
Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!
     PYTHONPATH is currently: "/Users/bryandady/Library/Python/3.7/lib/python/site-packages/:/usr/local/lib/python3.7/site-packages"
     You should `unset PYTHONPATH` to fix this.
/usr/local/bin/code: line 15: ./MacOS/Electron: No such file or directory
```

**Comment by joaomoreno** [comment]
Could you perhaps fix your PYTHONPATH? Or make sure Python3 is ahead in the PATH of your shell?

**Comment by bcdady** [comment]
It's not clear to me that anything is wrong with my $PYTHONPATH (I'll include it below), and my $PATH only includes paths to Python 3.7 or 3.8 resources; there are no Python 2 statements to move them ahead of.

```shell
echo $PYTHONPATH
~/Library/Python/3.7/lib/python/site-packages/:/usr/local/lib/python3.7/site-packages
```

**Comment by bcdady** [comment]
The only workaround that has worked for me is to edit my `/usr/local/bin/code` such that the 
realpath() function calls `python3 -c`  instead of `python -c`.
I imagine their are more elegant long-term solutions, but this is what I can most easily do to make it work (but must repeat after a reboot).

**Comment by joaomoreno** [comment]
> and my $PATH only includes paths to Python 3.7 or 3.8 resources; there are no Python 2 statements to move them ahead of.

This seems to contradict with what's happening. If you run `python --version` do you get version 3?

**Comment by bcdady** [comment]
Yes, when I run it at the prompt, I get `Python 3.8.0`.
But when I add `python --version` in my `/usr/local/bin/code`, it prints `Python 2.7.16`.

**Comment by joaomoreno** [comment]
Interesting. So in the same shell, when running `python --version` you get 3, but when running `code`, it picks up 2? Can you show me the full contents of `/usr/local/bin/code`?

**Comment by bcdady** [comment]
Sure. Here's my current copy that's working as expected:

```bash
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() { python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

**Comment by bcdady** [comment]
@joaomoreno I shared my working copy of `code` a few days ago.
Do you have any updates or any additional questions I can address?

**Comment by joaomoreno** [comment]
Sorry, @bcdady, I was out of office for a while.

Is your shell `bash`? In your shell, if you first run `bash` and then `python --version`, what's the result?

**Comment by bcdady** [comment]
No, Apple changed up the default shell to ZSH https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features

But if I get into BASH first, I get Python v2:
```bash
bash-3.2$ python --version
Python 2.7.16
bash-3.2$
```

I also use pwsh, and have the same symptom when in that shell.

**Comment by joaomoreno** [comment]
That explains it then! I wonder how come python3 is in the path for zsh but not for bash?

**Comment by bcdady** [comment]
That would be because I've got `export PYTHONPATH` set in my [OhMyZSH](https://github.com/ohmyzsh/ohmyzsh/) profile. But since I don't launch bash, I never modified that profile.
So the right long-term fix is for VS Code for MacOS to embrace ZSH and Python 3, right?

It would be helpful if the realpath function knew to prefer Python3, and maybe only provide Python2 backward compatibility support via a parameter / argument? https://pythonclock.org/

**Comment by joaomoreno** [comment]
Well, `PYTHONPATH` shouldn't affect `PATH`... that doesn't full explain why Python3 runs in zsh. There must be another change to `PATH` in your zshrc which gets Python3 in the path.

`PYTHONPATH` does affect the runtime behavior of Python 2 though... so have you considered removing it from your zshrc?

**Comment by bcdady** [comment]
Sure, I can fix my environment.
Is it useful for me to submit a Python 2 deprecation issue, or is that already in the roadmap?

**Comment by joaomoreno** [comment]
The thing is that script works in both 2 and 3, that's the point, so no need to deprecate 2 since it works for a lot of people. Python just doesn't like it if your PYTHONPATH is incompatible with whatever python is in the PATH. Thanks!
