### ISSUE TITLE
Install extension only for this workbench

### ISSUE THREAD

**Issue by wtto00** [microsoft/vscode#90462]
Hi,
I hope that I can choose an option that **only for this workbench** when I install a extension. Because I use many different languages usually so that I have to forbid many extensions for other languages when I edit a new project use a different language.

**Comment by JacksonKearl** [comment]
You can use the "Disable (Workspace)" and "Enable (Workspace)" menu items on the extension toggle enablement button to achieve this. 
![image](https://user-images.githubusercontent.com/8586769/74265439-6b3b5c80-4cb7-11ea-9ef8-2066d91ad7e0.png)
![image](https://user-images.githubusercontent.com/8586769/74265465-75f5f180-4cb7-11ea-9911-0d2dff5b0cf0.png)

**Comment by wtto00** [comment]
@JacksonKearl Sorry, I guess you didn't understand what I mean.
For example, I install "Vetur" for a vue project, then I start one or many react project, so I have to disable this extension in every workspace!
I have to disable it **every time** when I start many php project or python project or some else.
Of course, it doesn't matter if I don't disable it. But I think lots of extensions maybe slow VS Code down.

**Comment by JacksonKearl** [comment]
In that case, you would install Veuter, disable it, then any ttime you start a new Vue project, choose "Enable (Workspace)". It will default to disabled and you'll only need to enable it once per workspace.

**Comment by wtto00** [comment]
> In that case, you would install Veuter, disable it, then any time you start a new Vue project, choose "Enable (Workspace)". It will default to disabled and you'll only need to enable it once per workspace.

This is one solution. Grate!
