### ISSUE TITLE
Cannot update to 1.42

### ISSUE THREAD

**Issue by Nightvalzin** [microsoft/vscode#90460]
Issue Type: <b>Bug</b>

After I click on "Check for Updates", I then click to install the update. But after it starts doing that it says that it cannot due to a firewall or runaway processes. I've tried disabling my firewall but it still won't allow the update to install.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.69GB (1.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ev3dev-browser|ev3|1.0.4
ev3-micropython|leg|1.0.3
vsliveshare|ms-|1.0.1510
LiveServer|rit|5.6.1

</details>

**Comment by JacksonKearl** [comment]
> VS Code version: Code 1.33.1 

It seems like you haven't been able to update in a while - can you download and install directly from the website? Your settings will persist.

**Comment by Nightvalzin** [comment]
That did the trick as it no longer says any new updates. Thanks for the info.
