### ISSUE TITLE
Allow to navigate in MRU without picker until keybinding is released

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#90465]
- VSCode Version: 1.43 & 1.42
- OS Version: Win10

The [January 2020 changelog](https://code.visualstudio.com/updates/v1_42#_navigate-most-recently-used-editors) mentioned there's a new command to switch to previously used editor without a picker:

> If you want to navigate the list without using a picker, there are new commands:
> - View: Open Previous Recently Used Editor (`workbench.action.openPreviousRecentlyUsedEditor`)
> - View: Open Next Recently Used Editor (`workbench.action.openNextRecentlyUsedEditor`)

However, after calling `workbench.action.openPreviousRecentlyUsedEditor` to switch to the previous editor, the previous editor doesn't become the 1st in the most recently used (MRU) list.

Example: 
By default, suppose a scenario where I'm on Tab3. If I press `ctrl-tab` and get switched to Tab5, then it means if I do `ctrl-tab` again I'll get back to Tab3. 
However, if I use `workbench.action.openPreviousRecentlyUsedEditor`, the sequence is different. I won't get back to Tab3 on the second time.

Steps to Reproduce:
1. Open several tabs, do `ctrl-tab` and let go, repeat `ctrl-tab` and let go. Repeat several times to observe the normal behavior (with a picker).
1. In keybinding.json, add in the bottom:
```	
{
  "key": "ctrl+tab",
  "command": "workbench.action.openPreviousRecentlyUsedEditor"
},
```
3. Repeat steps in 1, see how the sequence is different. (For the desired behavior, try doing it in Sublime Text, that's the desired behavior of `ctrl-tab` without a picker. Also notice how they handle `ctrl-tab-tab-tab`, which behaves the same as the VSCode picker, which is also crucial when consider how to handle this bug. Basically in VSCode, both `ctrl-tab, ctrl-tab, ctrl-tab` and `ctrl-tab-tab-tab` should be consistent between "with a picker" and "without a picker").

Thanks!!

**Comment by bpasero** [comment]
@ZYinMD I understand the desire but this is probably not easy for us to implement. To clarify: you want that - as long as the Ctrl+key is pressed and hold - pressing Tab cycles through all the recently opened editors. That means, if you reached the last recent editor and hit Tab it would go back to the first, is that true?

Or maybe I am misunderstanding and you ask for something else. 

When invoking the commands to navigate without picker we essentially block any recording of MRU history. That is the same behaviour when using the "Go Back" and "Go Forward" commands. Otherwise you would end up navigating always between 2 editors.

**Comment by ZYinMD** [comment]
Hi @bpasero , thanks for your reply! No that's not what I meant. Let me try to describe it again, reducing to the most simplified scenario:

1. Suppose I'm on editor#5 in a multi editor window.
2. In command palette, run `View: Open Previous Recently Used Editor` `(workbench.action.openPreviousRecentlyUsedEditor)`
3. Suppose I'm now on editor#3
4. Now If I repeat step 2 again, where should I expect to go to? In my opinion, I expect to go back to editor#5, but it's not the current behavior.

**Comment by bpasero** [comment]
@ZYinMD I understand, but then this action would be limiting you to never go back more than 1 editor because the last one always becomes the active one? The idea of this command is to allow navigation in the entire stack, not just the last one.

**Comment by bpasero** [comment]
Hm, maybe I understand your point: someone could not be understanding that this command works like a stack. So would you suggest that this command is always bringing you to the last editor that was used? I think we would need a different command for that purpose.

**Comment by bpasero** [comment]
So a way how this could work: as long as the modifier key is pressed and hold (e.g. Ctrl), we would allow to navigate, but then when you release it, that editor becomes the active one.

As I said, this is technically hard for us to implement because we do not really have knowledge when all the keys have been released. Someone could have configured a keybinding that does not use modifiers at all.

**Comment by ZYinMD** [comment]
> So a way how this could work: as long as the modifier key is pressed and hold (e.g. `Ctrl`), we would allow to navigate, but then when you release it, that editor becomes the active one.

Yes, this was what I was hoping for. From a user's standpoint, I simply hope to use `ctrl-tab` without a picker - quick preview file content instead of looking at the picker. The reasoning is I'm looking for an editor that matches my visual memory, instead of a filename-match in the picker. What I described is the default behavior of Sublime Text.

I was hoping to achieve this by using the new `workbench.action.openPreviousRecentlyUsedEditor`, but if it's technically hard, then there are different approaches - if there's an option to enable "quick preview file content on ctrl-tab`, then problem solved.

**Comment by bpasero** [comment]
So we do have https://github.com/microsoft/vscode/issues/8939 logged to support the preview thing. 

I am fine leaving this open but would put it to backlog candidates and start that process.

**Comment by bwhitty** [comment]
I've been in search of this forever. This is how Sublime Text and Firefox handle tab switching and the important thing it allows it **switching back and forth between two files** extremely simply: just hit "ctrl+tab" and "ctrl+tab" again. In the current implementation, this is never possible.

Hopefully this video conveys the implementation (this is from Firefox):
![tab-mru-stack](https://user-images.githubusercontent.com/1571966/74783227-1620bd00-525a-11ea-8073-41a9924e5378.gif)


In words it's this:

| Key          | MRU Stack after key |
|--------------|-----------|
| n/a          | 1,2,3     |
| ctrl+tab     | 2,1,3     |
| ctrl+tab     | 1,2,3     |
| ctrl(hold)+tab+tab | 3,1,2     |
| ctrl+tab     | 1,3,2     |

**Comment by bpasero** [comment]
@bwhitty to clarify, this kind of navigation is possible in VSCode and `Ctrl+Tab` is even assigned as default keybinding. What is not working is using this without a picker UI.

**Comment by bwhitty** [comment]
@bpasero it is? I swear I’ve searched and searched for this and never was able to achieve it. You say it’s possible, but should I reset my keybindings to default in order to achieve this? Or are you alluding to some other custom setup?

**Comment by bpasero** [comment]
Yes please do.

![Kapture 2020-02-19 at 8 33 53](https://user-images.githubusercontent.com/900690/74811827-9692fc80-52f2-11ea-8428-ff60daa3d5ec.gif)

**Comment by bwhitty** [comment]
Well, you've made my week. I had it overridden with "openPreviousEditor". Thank you for the extra effort and the random support here @bpasero. You're a hero!
