### ISSUE TITLE
Flaky test: active editor not always correct...

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90470]
This test started to fail recently. At first I thought it was only in browser but I also see it in electron now:

https://github.com/microsoft/vscode/blob/4978f52ec8d56ae52809b6a3683b80e4144bdf50/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts#L154

https://github.com/microsoft/vscode/runs/438638035#step:13:397

When I briefly debugged this in the browser I noticed how - when the second editor opens to the side - both editors show blinking cursors and as such I suspect an issue with our focus tracking in the editor. That is also why the first editor shows as active even though the second one opened.

I have for now disabled this test.

**Comment by jrieken** [comment]
>  At first I thought it was only in browser but I also see it in electron now:

You cannot debug this test because it depends on correct focus-logic - this and other tests mean you cannot touch your keyboard/mouse when running API tests locally. I wonder if playwright has issues with that and that it is failing on the build machines more often because of that

**Comment by bpasero** [comment]
I can reproduce it locally when I run with UI, e.g. not headless. That is how I noticed that 2 editors show a blinking cursor each which hints to focus problem. 

As for electron: this has started to happen with the E7 adoption, so we might hit a browser issue now that came into Electron too.

**Comment by jrieken** [comment]
> That is how I noticed that 2 editors show a blinking cursor each which hints to focus problem.

There is well known issue (since very long) for those two blinking cursors. @alexdima introduced me to this and I don't remember if its chrome or electron but it happens on mac  when using multiple desktops.

**Comment by alexdima** [comment]
The known issue is #82326 -- having two windows on macOS might lead to both of them believing they have focus after unlocking or after switching desktops, but that is not about two editors in a single window having focus...

@bpasero How can I reproduce locally the two editors with two blinking cursors?

**Comment by bpasero** [comment]
@alexdima steps:
* from `master` with distro mixed in
* change this [line](https://github.com/microsoft/vscode/blob/89a1183946e430adb5500aeaecba315dec1f6776/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts#L154) to `suite.only`
* add a timeout after this [line](https://github.com/microsoft/vscode/blob/89a1183946e430adb5500aeaecba315dec1f6776/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts#L167) `await new Promise(c => setTimeout(() => c(), 10000))`
* run `resources/server/test/test-web-integration.sh --debug`

**Comment by alexdima** [comment]
@bpasero I have investigated by adding logging to the relevant code in the editor.  Basically, `focus` and `blur` events are not delivered to DOM nodes... so that's why both editors believe they are focused... 

I think this is an issue with the automation...

**Comment by alexdima** [comment]
I have created https://github.com/microsoft/playwright/issues/979

**Comment by bpasero** [comment]
@alexdima thanks!
