### ISSUE TITLE
Single click highlights word but selects full line.

### ISSUE THREAD

**Issue by mcohoon** [microsoft/vscode#90476]
- VSCode Version: 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451)
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

1. Single click a word in a function definition: `foo` in `def update_value(self, foo)`
2. The word `foo` highlights.
3. Copy by either hitting <kbd>CMD+C</kbd> or go the menu `edit->copy`
4. Click elsewhere in the file, hit <kbd>CMD+V</kbd> or go to the menu `edit->paste`
5. The full line `def update_value(self, foo)` is pasted where I would expect only the word `foo`

Does this issue occur when all extensions are disabled?: Yes

If selecting the full line is the intended behavior then I would expected some visual indication that the line is selected not just the word. Ideally if I single click a word and the word highlights I would like only the word to be copied.  [Stackoverflow has been silent as writing this issue](https://stackoverflow.com/questions/60155620/vscode-will-copy-full-line-when-only-a-word-is-selected-single-click) as to if this is the intended behavior or if there are any settings that might "fix" this behavior. This could be viewed as an accessibility bug/feature.

**Comment by JacksonKearl** [comment]
Double clicking selects the word. Single clicking only places your cursor on the word. But, we apply a highlight to the word under the cursor and any instances of that word in the rest of the file. Copy when there is no selection copies the whole line.

No selection, highlights matching words:
![image](https://user-images.githubusercontent.com/8586769/74270064-77c3b300-4cbf-11ea-8b5c-42d45f186105.png)

Selection, matching words remain highlighted:
![image](https://user-images.githubusercontent.com/8586769/74270096-84480b80-4cbf-11ea-82b1-6975b7d8a50a.png)

**Comment by mcohoon** [comment]
That explains the behavior I am seeing; for others who find there way here:
- The word the cursor is on (from a single click) is highlighted along with every occurrence of that word. The word is not selected (that would be a deeper blue). 
- By default copying without a selection copies the current line.

This in my opinion is an Accessibility issue, as there are strong visual clues that a word is selected. I have found that the behavior can be made more intuitive if you set these to settings. 

    // Controls whether copying without a selection copies the current line.
    "editor.emptySelectionClipboard": false,
    // Controls whether the editor should highlight semantic symbol occurrences.
    "editor.occurrencesHighlight": false,

With these two settings the word the cursor is on will not be highlighted (nor any other occurrences of that word). And if you do happen to copy with an empty selection, the editor will behave similar to how other applications behave and not copy the current line.
