### ISSUE TITLE
Many issues with styling different tokens

### ISSUE THREAD

**Issue by that70schris** [Microsoft/vscode#9047]
Hello,

I recently started trying to build a custom theme from scratch and I've run into a few issues as well as find it very confusing to know which selectors are applied where.

One issue I've noticed in certain places is the assignment operator `=` appears to not be it's own token making it impossible to style separately:
https://cl.ly/3M2I3y0u0K1q

A similar issue happens sometimes with the property separator `:`, which ruins the ability to style both the separator and whatever follows:
https://cl.ly/3M2I3y0u0K1q

And the declaration and comparison operators `=`,`==`,`===` all have the exact same classes, at least most of the time:
https://cl.ly/3M2I3y0u0K1q

Sometimes the classes they have are completely different and not specific enough to pinpoint the right tokens:
https://cl.ly/100S2w3X1T0n

These are just a few of the issues I'm seeing when trying to style different parts of the syntax.  What I was expecting to be able to do was to use a selector like `operator.declaration` to color all `=`'s, and something like `operator.comparison` to target all `==`,`!=`,`===`,`!==`, etc..

Maybe these are leftovers from TextMate theming?  Or maybe I'm just missing something about the way these classes/themes are supposed to work?

I'm also open to contributing, but some guidance would be helpful.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#204
