### ISSUE TITLE
Backspace key does not work in VSCode Online in mobile browser

### ISSUE THREAD

**Issue by seajhawk** [microsoft/vscode#90472]
I've tried to use online.visualstudio.com from my mobile phone with both Edge & Chrome, and I've used SwiftKey and GBoard keyboards.
In all cases, the backspace key fails to work.
In addition, when I hit the space key (at least with SwiftKey) it enters the word from the suggestions which is typically the word I just typed.

**Comment by rebornix** [comment]
@seajhawk may I know what OS you are using?

**Comment by seajhawk** [comment]
I’m using Android 9. (I should have mentioned that!)

Thanks,
Chris

________________________________

**Comment by SpinningK** [comment]
same issue, backspace in soft keyboard can't work in editor of vscode(terminal and other places works well) in a android browser. But physical keyboard(bluetooth or wired connected to mobile) works well in editor. This issue may related to android keyboard mechanism.
You can test the difference between soft keyboard and physical keyboard's behavior in android browser in https://keycode.info
physical keyboard works normally on this website and soft keyboard works not very well.

**Comment by SpinningK** [comment]
Any news? I come from code-server's(a project based on vscode) issue:
https://github.com/cdr/code-server/issues/1141
And the developer said vscode should fix this bug.

**Comment by rebornix** [comment]
Currently I don't have an Android device to troubleshoot this issue but PRs are always welcome.

**Comment by AnErW** [comment]
It seems that Microsoft haven't fix it yet.
But I found another replacement called gitpod, and it can work on android.
Maybe We can have a try on it, it support vscode plugin.(but maybe have some bugs)

**Comment by ppoak** [comment]
Same problem, when coding with my iPad, the backspace button works just fine. However, when I turn to my Android devices, I find the the backspace doesn't function well.
I have already read the `code-server` issue, they said that vscode should fix this bug.

**Comment by bpasero** [comment]
Is https://github.com/microsoft/vscode/issues/107602 related and/or duplicate maybe?

**Comment by guinmoon** [comment]
Work with this keyboard
Hacker's Keyboard
https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=ru

**Comment by mariusandra** [comment]
It still didn't work for me, even with the hacker keyboard, while running github codespaces.

The "del" key under "fn" in the hacker keyboard works though. Not ideal, but at least something gets deleted.
