### ISSUE TITLE
Search editor highlights are misplaced or missing

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#90471]
Issue Type: <b>Bug</b>

**Repo**
1. In the VS Code codebase
1. Search `refactor`

**Bug**
Notice that many of the match highlights are shifted off slightly or missing:

<img width="686" alt="Screen Shot 2020-02-11 at 10 03 25 AM" src="https://user-images.githubusercontent.com/12821956/74264652-d97f1f80-4cb5-11ea-8b79-71a1ada3ba5b.png">

VS Code version: Code - Insiders 1.43.0-insider (8d17dc1e84d53f5fd4ed0d05fabaa3062259633d, 2020-02-10T10:42:15.424Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JacksonKearl** [comment]
I've seen this happen when you modify the file and reload, but not on a fresh search. Was this from a fresh search?

**Comment by mjbvz** [comment]
Yes, from a fresh search, but it seems to be tied to clicking `Open in editor`. If I re-search inside the search editor, the ranges are updated correctly

**Comment by JacksonKearl** [comment]
Oh now I can reproduce
