### ISSUE TITLE
Tasks: Can't retain "Do Nothing" as the default behavior

### ISSUE THREAD

**Issue by shogerr** [microsoft/vscode#90478]
When a user has a failed task from a build, they are prompted with a dialog as seen in the image below.

A user has two options that can be made the default: Debug Anyway & Show Errors. Both options present a new interface layout to the user. Debug anyway launches the process, and show errors switches from the build output to the error list.

Both of these actions are EXTREMELY annoying, and cancel is by far the preferred choice, however, the cancel option does not register as a default action when "Remember my choice" is selected. As a result, a user must press cancel every time they build if they wish to see the build output rather than the buggy error list view or ... continuing to debug a failed build?!?! what?!?!

Please allow a user to retain the selection of 'Cancel' as option that "does nothing"

![image](https://user-images.githubusercontent.com/10454476/74271889-8495d600-4cc2-11ea-89b4-5e9dce9ee8a3.png)

**Comment by isidorn** [comment]
Makes sense. I have pushed a fix for this.
I apppologize that I did not see your PR before I coded this up. Due to that I will have to close your PR. Sorry about that!

**Comment by shogerr** [comment]
Note to self, don't bother contributing code to vscode. Got it.

**Comment by jwunderl** [comment]
It looks like there was a minor typo in that fix; it uses an assignment expression rather than an equality check and mutates `result.choice`, so it would always count as a cancel action.  Put up a pr fixing that https://github.com/microsoft/vscode/pull/90558 -- can file a separate issue if needed, just in a meeting for a moment

**Comment by shogerr** [comment]
Before I go ahead and have my CLA contract revoked, here is the PR that was ignored.

**Comment by shogerr** [comment]
Thinking about this again, shouldn't a cancel button have no side effects? That is, a user should expect to be able to back out of any changes and not affect the system state. In both PRs the cancel button click is saved to settings.json as the preferred choice.

Would it be a better UX choice to add a third button whose action is to "not prompt", and save that?

**Comment by JacksonKearl** [comment]
It might be better to rename it "Abort". But if you have manually selected "save my choice" then hit cancel I don't think it's unexpected that it saves that you canceled the operation.

**Comment by isidorn** [comment]
@shogerr I already appologized about me missing your PR. There is not more I can do, sorry.
@jwunderl Thanks, I have fixed the assignment / equality
@JacksonKearl going with 'abort' for now, thanks for the suggestion.

**Comment by shogerr** [comment]
@JacksonKearl It doesn't make a lick of sense to save the 'cancel' action as the default behavior except to a lazy programmer.

**Comment by connor4312** [comment]
It looks like we forgot to update the key to `abort` here, which results in a validation error

https://github.com/microsoft/vscode/blob/093ada38305dc4b26bdfb62ae86bca245cb9d233/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L270

works otherwise
