### ISSUE TITLE
Allow updating of snippets that are loaded

### ISSUE THREAD

**Issue by jschuler** [microsoft/vscode#90485]
In my extension, I can configure the snippets in package.json, e.g.
```
"snippets": [
      {
        "language": "markdown",
        "path": "./snippets/snippets_2020.01.json"
      }
    ]
```
But i'd like to be able to load a different snippet file (for example a different version) when a command is issued

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asnippets
