### ISSUE TITLE
Enable Project Diagnostics not searching through unopened files

### ISSUE THREAD

**Issue by etanb** [microsoft/vscode#90483]
- VSCode Version: 1.43.0-insider
- OS Version: Mac OS 10.13.6 

Steps to Reproduce:
1. Enable `TypeScript › Tsserver › Experimental: Enable Project Diagnostics`
2. Created TS error in a file and the problem rendered correctly in the problem panel
3. Closed file and navigated away. Problem doesn't get reported by VS.
4. Reopen file, TS error is properly reported.

**Comment by mjbvz** [comment]
The design of this setting is to report issues in opened projects. This means you have to have at least one file from the project opened (but when you do have a file open, you should see errors for all files in that project)

The rational is that workspaces can often contain a very large number of tsconfig projects. It would quickly get very expensive to proactively check the for these

Does this description match what you are seeing?

**Comment by etanb** [comment]
Hmm...I've opened a few files in the project, including ones in the same folder as the file with a TS error, and there's no errors reported. As soon as I open that specific file, however, I do see the error. It immediately goes away once the file is closed.

**Comment by mjbvz** [comment]
Can you please provide repo steps and an example project that demonstrates the issue?

**Comment by etanb** [comment]
I'll have to make a new seed project to share with y'all as I'm using this on my private company repos. All I'm doing is opening VS code in our repo (it's a simple create-react-app base) and looking for errors. Can try to make something publicly shareable later today.

**Comment by mjbvz** [comment]
I haven't been able to repo using a create-react-app so please share an example project when you get a chance!
