### ISSUE TITLE
Option to disable setting language of untitled file on paste

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#90492]
The new feature that automatically sets the language of an untitled editor is blowing up my language setting even after I set it explicitly.

**Repro**
Open a new file
Explicitly set it to plain text
Paste text from another editor
Notice it changes the language mode

I use plain text editors constantly and this is frustrating.

**Comment by gjsjohnmurray** [comment]
> **Repro**
> Open a new file
> Explicitly set it to plain text
> Paste text from another editor
> Notice it changes the language mode

@akbyrd I'm not clear why you need to set language mode explicitly to plain text right after opening a new file. Perhaps you have set `files.defaultLanguage`

But assuming that step **is** necessary, can you simply defer doing it until after pasting?

I'm not disagreeing with your request for this new behaviour to be switchable. Just trying to understand if you can work around it without having an extra step to do.

**Comment by akbyrd** [comment]
I don't _have_ to set the language to plain text right after opening. I'm using that step to demonstrate that the new feature will alter something is **explicitly** set, which it should never do.

My untitled files already default to plain text because
`"files.defaultLanguage": ""`

Perhaps this alternate repro will demonstrate the problem more clearly:
* Open a new file (defaults to plain text)
* Paste text from another editor
* Notice it changes the language mode (expected, fine)
* Set language back to plain text
* Paste again
* Notice it changes the language mode again (problem!)
* Set language back to plain text
* Repeat ad nauseam

**Comment by bpasero** [comment]
The current heuristic in insiders (changed slightly from stable) is as follows:
* if the language mode is not plain-text, we ignore the mode from the paste
* if you paste anywhere outside of line 1, column 1, we ignore the mode too assuming that you have already worked with the untitled file (this is new from stable)

I think the only solution here is to provide a setting because I find it rather weird that configuring the language mode to "plain text" if it is already "plain text" should have any impact?

Curious if insiders improves this situation for you given the change we did.  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Oh sorry, I just found a bug in insiders (fixed via https://github.com/microsoft/vscode/commit/7e0133d184cce0b0eb5b7a6b34ae4bb83c164d90). To see the behaviour I describe in action you need to paste into anywhere that is not line 1 and not column 1. The change I pushed makes this easier to not apply the mode unless you truly paste into line 1 and column 1.

**Comment by akbyrd** [comment]
How does this work when I select all and paste? This is something I frequently do and I assume that counts as pasting into 1:1. The heuristic fails here.

> I find it rather weird that configuring the language mode to "plain text" if it is already "plain text" should have any impact?

I don't follow what you mean here. In my second repro above I only demonstrate setting to plain text from some other language that was automatically set when pasting. At no point do I set it to plain text while it is already plain text.

I think this issue should be separate from the other that you closed. This issue is a _bug_. You can't just run around changing the settings I want. A heuristic simply isn't enough. There's a difference between "the editor tried to automatically infer what I want" and "I explicitly set this thing". It's fine to override the former, but _not_ the latter. You need to track "did the user explicitly set a language?" and disable the heuristic.

You can introduce an option to disable it entirely (and in my case that happens to be good enough) but that's a workaround for UX that absolutely should not exist.

**Comment by bpasero** [comment]
I pushed a change that will disable this feature of setting the mode automatically upon paste.

**Verification:**
* you picked "plain text" on an untitled file (even if it is already "plain text") - this is now a hint to the editor that the mode was chosen by the user and should not be changed
* this is persisted across restarts - if you have an untitled editor open and you once changed the mode explicitly, we remember that and will not change the mode on paste ever
* you configure `"files.defaultLanguage": "plaintext"` - this is basically now a way to disable this feature for good
