### ISSUE TITLE
"Run search" persists after search has run

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#90490]
![image](https://user-images.githubusercontent.com/8586769/74287894-eca6e500-4cdf-11ea-9bef-040039db25ce.png)
shouldnt see both "run search" and results.

**Comment by mjbvz** [comment]
Just tested but I never see the `Run Search` button. @JacksonKearl  Anything required to trigger it or has it been removed?

**Comment by JacksonKearl** [comment]
@mjbvz reload with a non-dirty search editor
