### ISSUE TITLE
Update discard text string in SCM

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#90496]
<img width="80%" src="https://user-images.githubusercontent.com/35271042/74289916-33e3a480-4ce5-11ea-8425-1775de024ad9.png">

I noticed that our discard text in SCM has lots of variations of all caps and exclamation points, something we don't do anywhere else and doesn't look very good.

Can we update these types of text to read:

> If you delete ${filename}, you won’t be able to recover it later. Do you want to continue?

And have Yes/No buttons instead?

**Comment by joaomoreno** [comment]
Even though you're 100% correct, we can't change it. There have been many issues in the past with people deleting their files, which drove us to this. The all caps is there specifically to look odd and out of place.

**Comment by misolori** [comment]
What's the TL;DR version of why we can't recover items from the trash like the GitHub's Desktop app?

![image](https://user-images.githubusercontent.com/35271042/74389170-3e1fa480-4db2-11ea-86a8-52cae3a3e9ce.png)

**Comment by joaomoreno** [comment]
Great question. We simply never implemented that. We spawn `git clean`, and equivalents, which do not send anything to the trash, so maybe GH for Desktop does a bit more than simply invoking git.

It is something worth investigating, tho surely a path with many traps. 👍
