### ISSUE TITLE
"Render whitespace" shows boxes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#90498]
![image](https://user-images.githubusercontent.com/323878/74291740-af942000-4cea-11ea-9360-52485002be45.png)

**Comment by roblourens** [comment]
This is from my font :(

**Comment by alexdima** [comment]
@roblourens We now use either `U+00B7 - MIDDLE DOT` or `U+2E31 - WORD SEPARATOR MIDDLE DOT` for the whitespace rendering, whichever one is closer in width to `&nbsp;`

**Comment by roblourens** [comment]
The latest Cascadia Code has the right character, I updated and it works now.
