### ISSUE TITLE
Option to disable naming untitled files with the first line of text

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#90495]
1.42 introduced a feature that uses the first line of text in an untitled file as the name of the editor. This is not a useful feature for me. It's distracting and I'd like an option to disable it.

I use untitled files as a scratch space and I'm frequently pasting log snippets and such into them. I have no need for that to be the name of the editor.

![image](https://user-images.githubusercontent.com/484784/74288851-6049f180-4ce2-11ea-863a-238e9e879caa.png)

**Comment by IllusionMH** [comment]
Previous discussion #88971

Just in case: you can make first line empty to get pure Untitled-x tab. Shouldn't be a big problem for log files (I doubt that there are formatters that remove first line if empty and needs diff between difs a lot)
