### ISSUE TITLE
Option to disable setting language of untitled file on paste

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#90494]
1.42 introduced a feature that automatically sets the language of an untitled editor upon paste. I never want this behavior and I'd like an option to disable it outright.

I almost exclusively use plain text when creating an untitled file. If I want it to be something more than notes and a scratch space to paste things I would have created a new _named_ file and given it the proper extension.

Therefore, the result of this feature is that in the common case I create a new untitled file, paste something, get weird highlighting, set the language back to plain text to make it stop.

And due to [this bug](https://github.com/microsoft/vscode/issues/90492) I have do this every time I paste.

**Comment by bpasero** [comment]
Let's move this into https://github.com/microsoft/vscode/issues/90492 which I have renamed.
