### ISSUE TITLE
Migrate to AppCenter for crash reports

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#90491]
`HockeyApp: error Error: Unexpected response: {"errors":{"app":["App cutover to App Center"]}} (AppID: df720085b30c42c09326b68b40f13a35)`

TODO:
- [ ] Enable automatic symbol uploads from the build pipeline
- [x] Get windows crash report working

**Comment by bpasero** [comment]
Assigning to @deepak1556 who is taking care of moving us to the new crash world.

**Comment by lumaxis** [comment]
@bpasero It does!
Let me know if you need any help with this.

**Comment by deepak1556** [comment]
The current VS Code stable `1.43` ships with crashes reporting to appcenter on macOS, linux and windows. There are some followup issues that needs work and help from appcenter

1) Crash reports from windows don't show up on appcenter, although they are sent are from the client and there is a successful correlation id.

Mathias Wenz from the Appcenter team spent time investigating this on the server side and found that the parsing of minidump files failed, the reason being `minidump_stackwalk` tool from breakpad that is used to generate the json format of symbolized data fails to escape some windows path with special characters like lowercase drive letters ex: `"path":"\\?\d:\github\vscode\node_modules\vscode-sqlite3\build\Release\sqlite.node"` . An internal support ticket has been raised for this, will add the link here once I obtain it.

2) There are bogus crash reports from our macOS app that has no versions and no meaningful symbolized data, not sure where these are coming from. I have raised a support request for debugging this further, awaiting appcenter response. Here is a video demo of the issue https://streamable.com/urs7y , also this only affects macOS, linux reports are fine.

3) Unable to use search filter with User ID, we use guid format for the user id, we are able to confirm the reports are present manually, just the search filter doesn't work on them. Again raised a support request, awaiting response.

Any help on moving these forward is appreciated. Thanks!

**Comment by deepak1556** [comment]
Update:

1) Have obtained internal bug report id https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/77695

2) Awaiting response.

3) Was requested further debugging info, provided them today. Awaiting issue confirmation.

**Comment by bpasero** [comment]
Isn't this complete?
