### ISSUE TITLE
Can't Opt + Click to open partial, get "Invalid Arguments" error

### ISSUE THREAD

**Issue by TimJKStrickland** [microsoft/vscode#90497]
Issue Type: <b>Bug</b>

In a rails app, I Opt + click on a partial, and it would open that file. Now it reads "Unable to open '{name of file}': Invalid arguments." I'm not sure what changed from yesterday, was working fine < 12 hours ago

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|66, 22, 8|
|Memory (System)|16.00GB (3.53GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
html-snippets|abu|0.2.1
vscode-color-pick|ada|0.6.2
vscode-inky-snippets|ade|1.0.1
ruby-on-rails-snippets|ate|0.0.1
rails|bun|0.13.2
vscode-gemfile|bun|0.0.2
solargraph|cas|0.21.1
turbo-console-log|Cha|1.3.1
vscode-eslint|dba|2.0.15
es7-react-js-snippets|dsz|2.5.0
prettier-vscode|esb|3.20.0
docker-explorer|for|0.1.6
beautify|Hoo|1.5.0
rails-snippets|Hri|1.0.8
sublime-babel-vscode|jos|0.2.10
rainbow-csv|mec|1.5.0
vscode-language-babel|mgm|0.0.25
ruby-rubocop|mis|0.8.1
vscode-autoprefixer|mrm|3.0.0
vscode-docker|ms-|0.10.0
color-highlight|nau|2.3.0
language-liquid|nei|0.1.1
emoji|Per|0.0.3
ruby|reb|0.26.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
stylelint|shi|0.51.0
slim|sia|0.1.2
html5-boilerplate|sid|1.0.3
mdx|sil|0.1.0
character-count|ste|0.1.1
haml|vay|1.0.1
simple-ruby-erb|vor|0.2.1
vscode-ruby|win|0.26.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Please file on the extension providing the language support. (Probably Ruby or Rails)

**Comment by TimJKStrickland** [comment]
Ok, will do. Thank for the clarity!
