### ISSUE TITLE
Wordwrap to end of line, not specific column

### ISSUE THREAD

**Issue by weeblr** [Microsoft/vscode#905]
If I'm not mistaken, the only option ATM for wordwraping is to set editor.wrappingColumn to a number of columns. This will apply to all files.

I would suggest that instead, or as another option, wrapping can simply happen at the end of the current line, as defined by the current edition window width.

This is much more convenient one needs not adjust editor.wrappingColumn when switching from one screen to another or when resizing windows, etc

Rgds

**Comment by alexandrudima** [comment]
@weeblr Try `editor.wrappingColumn = 0`

**Comment by weeblr** [comment]
Sorry, my bad, didn't read the comment :(
