### ISSUE TITLE
Sidebar Explorer: Double clicking on already open file should bring that group and file to focus (not open another view into that file in another panel group)

### ISSUE THREAD

**Issue by mkormendy** [microsoft/vscode#90502]
Issue Type: <b>Bug</b>

1. I have a configured workspace with a number of different files open in a number of editor panel groups. (in my case it's only two panels).

2. The editor that I am focused on, is in editor panel group 1.

3. I double click on "example.file" in the sidebar explorer of a file that is already open in editor panel group 2.

4. Instead of focusing on "example.file" in panel group 2, VSCode opens a new view in editor panel group 1, and now I unexpectedly have two editors with the same file open in both editor panel groups.

The expected outcome is that the VSCode brings to focus, the editor of already open file and NOT to open yet another view in a different active group.

Please fix this.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_106522|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.9
vscode-devtools-for-chrome|cod|0.0.6
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|2.0.15
vscode-dash|dee|2.3.0
githistory|don|0.5.0
permute-lines|ear|1.1.0
prettier-vscode|esb|3.20.0
vscode-browser-refresh|fab|1.1.5
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.1
vscode-mysql|for|0.4.0
beautify|Hoo|1.5.0
cpptools|ms-|0.26.3
debugger-for-chrome|msj|4.12.6
code-settings-sync|Sha|3.4.3
uridecode|sry|0.3.5
ghosttext|tok|1.1.0
gistfs|vsl|0.0.51
in-any-case|wil|1.1.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
`"workbench.editor.revealIfOpen": true`

**Comment by mkormendy** [comment]
Configuration successful.
