### ISSUE TITLE
Inconsistent name in launch.json in debugging

### ISSUE THREAD

**Issue by mcwindy** [microsoft/vscode#90503]
Issue Type: <b>Bug</b>

In the "launch.json", it is "stopAtEntry" in cppvsdbg while it is "stopOnEntry" in python.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.9
vscode-markdownlint|Dav|0.34.0
githistory|don|0.5.0
gitlens|eam|10.2.1
php-intellisense|fel|2.3.14
code-runner|for|0.9.15
latex-workshop|Jam|8.7.1
vscode-language-pack-zh-hans|MS-|1.42.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.62710
cpptools|ms-|0.26.3
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.2.5

</details>

**Comment by JacksonKearl** [comment]
This is decided by extensions, in this case https://github.com/microsoft/vscode-cpptools and https://github.com/microsoft/vscode-python. You can file issues for reconciliation there if you'd like.
