### ISSUE TITLE
VSCode shows blank white window after version 1.40/1.41/1.42

### ISSUE THREAD

**Issue by lugt** [microsoft/vscode#90504]
- VSCode Version: 1.42.0-1580986622, APT (system package manager) installed.
```
About Info:
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-76-generic
```
- OS Version: Ubuntu 16.04.4 LTS, in a VM running on macOS.

Steps to Reproduce:

0. Have a Ubuntu 16.04 platform and a VSCode 42/41/40.
1. Launch with code from terminal or Launch with icon from desktop
2. The window of the VSCode is blank white, yet the menu bar is still working, but any new popup window is also fully white.

- *This issue does not occur when using VSCode 39.2 or earlier, only starting from version 40*

Does this issue occur when all extensions are disabled?: 
Yes, this issue still arise.

**Comment by lugt** [comment]
@ramya-rao-a

**Comment by IllusionMH** [comment]
Have you tried to launch VSCode with `--disable-gpu` flag?

**Comment by lugt** [comment]
Thanks for the quick response.
Not previously.
Just after trying this out. it seems that this works.


Does this still count as a bug or should this be closed?

**Comment by JacksonKearl** [comment]
We unfortunately cannot hope to manage every GPU/OS/VM manager/Guest OS combination out there so we close out issues that can be worked around with `--disable-gpu`. You can permanently configure this with `Preferences: Configure Runtime Arguments`.
