### ISSUE TITLE
Type phonetic notation in edit area may stuck input cursor

### ISSUE THREAD

**Issue by thkaw** [microsoft/vscode#90501]
Hi VS dev team,

I found a problem that when I type some English alphabet, then immediately after some phonetic notation(This a kind of Chinese-Traditional input method).

The input cursor in edit area may stuck.
If this problem happend, need reopen that tab to solve this problem.

**Comment by rebornix** [comment]
@thkaw may I know what IME you are using when running the problem? Can you provide a minimal reproduce steps for it?
