### ISSUE TITLE
Investigate to cancel a running save participant when saving again

### ISSUE THREAD

**Issue by dydzio0614** [microsoft/vscode#90509]
It seems that if you save multiple times then waiting time for saving participants is not cancelled, probably due to not cancelling progress from 1st saving attempt. If it's not the case then this issue can be closed. Use case: After pressing save I spotted a typo and fixed it within few seconds and re-saved on PC with slow CPU.

**Comment by jrieken** [comment]
Yeah, I don't think that we cancel a save when another one is on its way. Assigning @bpasero for consideration

**Comment by bpasero** [comment]
This code is probably triggered:

https://github.com/microsoft/vscode/blob/3cb35b0d5e857cc0f7246337916603e1fccae2ed/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L601

If a save is pending (that includes save participants and the actual writing of the file), we wait for that to complete and then trigger it. Basically ensuring that only 1 save operation per file is running at the same time. 

@dydzio0614 @jrieken you will have to clarify what you expect to happen in this case. Would you expect the save participant to get cancelled? Clearly we cannot easily cancel the file-write operation.

**Comment by jrieken** [comment]
Unsure what's best but yeah we could check if we still waiting for participants and cancel the them (and the same operation) in that case. So, we have two phases

1. run particpants
2. save file 

We don't ever want to interrupt/cancel 2. but we can cancel 1. and decide if we want to continue then with 2. or not (I am in favour of always saving)

**Comment by bpasero** [comment]
@jrieken how can I cancel the save participant that starts here:

https://github.com/microsoft/vscode/blob/3cb35b0d5e857cc0f7246337916603e1fccae2ed/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L628

Can you add `CancellationToken` support? I think that would be the first step for allowing to cancel this when a second save is triggered.

**Comment by jrieken** [comment]
I already have a [token](https://github.com/microsoft/vscode/blob/94f93598c5f87aa49b58aa46fa80371952b446da/src/vs/workbench/api/browser/mainThreadSaveParticipant.ts#L370) which is linked to the progress UX. Just pass me one in the participant function and I hook them up

**Comment by jrieken** [comment]
One thing we should keep in mind here is save participants that call save (see https://github.com/microsoft/vscode/issues/90273) again. E.g indirectly cancelling themselves and hopefully not getting into a save-loop

**Comment by bpasero** [comment]
@dydzio0614 maybe you could verify this fix in tomorrows insider build

**Comment by bpasero** [comment]
@dydzio0614 ping

**Comment by bpasero** [comment]
Actually we do have a test for this now.
