### ISSUE TITLE
"There is no formatter installed" after uninstalling default formatter, even if another one remains

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#90507]
- VSCode Version: 1.42.0
- OS Version: Windows 10

Steps to Reproduce:
1. Install Name: XML Tools (https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml) and XML Format (https://marketplace.visualstudio.com/items?itemName=mikeburgh.xml-format)
2. Open and format any XML file.
3. VSCode will ask for a default formatter: select XML Format
4. Note that VSCode adds the following to settings:
```
    "[xml]": {
        "editor.defaultFormatter": "mikeburgh.xml-format"
    },
```
5. Uninstall XML Format, click "Reload required"
6. Try to format XML file.

Expected:
- XML Tools is used for formatting, or VSCode says 
> Extension 'mikeburgh.xml-format' is configured as formatter but not available. Select a different default formatter to continue.

Actual:
- On first try, VSCode says
> There is no formatter for 'xml' files installed.
- On second and further tries, VSCode says
> Extension 'mikeburgh.xml-format' is configured as formatter but not available. Select a different default formatter to continue.

![image](https://user-images.githubusercontent.com/12128514/74313850-bebfb000-4d74-11ea-8a78-6f1c69f7dc95.png)

**Comment by bersbersbers** [comment]
This may be a race condition: I may be formatting the XML file before the XML extension is fully loaded (this issue is reproducible after reload and restart of VSCode, but not when I give VSCode a couple of seconds before trying to format my file). Still, the message "no formatter installed" is misleading: it *is* installed, it's simply not loaded. Couldn't formatting (and thus this error message) be delayed until all extensions waiting to be loaded have finished loading?

**Comment by jrieken** [comment]
>  Still, the message "no formatter installed" is misleading: it is installed, it's simply not loaded. Couldn't formatting (and thus this error message) be delayed until all extensions waiting to be loaded have finished loading

Unfortunately not - we don't know what's there to come and we can not just wait for all extensions to be loaded. It might be that the extension is very slow to load, please check via "F1 > Show Running Extensions"

**Comment by bersbersbers** [comment]
77/88 ms for XML Tools, 1 ms for XML Format. Maybe I am just being too fast.

**Comment by jrieken** [comment]
You must be very game... Can you enable trace logging (F1 > Set Log Level > Trace) and then check the window & extension host log?

**Comment by bersbersbers** [comment]
@jrieken out of curiosity, I did - see attached. The `x.xml` I used had a single `s`, nothing more.
[Extension Host.txt](https://github.com/microsoft/vscode/files/4207518/Extension.Host.txt)
[Window.txt](https://github.com/microsoft/vscode/files/4207519/Window.txt)

I think I'm not THAT fast - I believe I format some 300ms after it seems that the file is loaded:
```
[2020-02-15 01:36:02.479] [renderer1] [trace] [text file model] load() - exit - without loading because model is dirty or being saved file:///c%3A/Work/Desktop/x.xml
[2020-02-15 01:36:02.776] [renderer1] [trace] CommandService#executeCommand editor.action.formatDocument.none
```

But yes, that seems to be too fast for the extension to be loaded:
```
[2020-02-15 01:36:02.572] [exthost] [info] ExtensionService#_doActivateExtension DotJoshJohnson.xml {"startup":false,"extensionId":{"value":"DotJoshJohnson.xml","_lower":"dotjoshjohnson.xml"},"activationEvent":"onLanguage:xml"}
[2020-02-15 01:36:02.572] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/bers/.vscode/extensions/dotjoshjohnson.xml-2.5.0/out/extension
[2020-02-15 01:36:02.743] [exthost] [trace] ExtensionService#loadExtensionContext DotJoshJohnson.xml
...
[2020-02-15 01:36:03.286] [exthost] [trace] ExtensionService#_callActivateOptional DotJoshJohnson.xml
[2020-02-15 01:36:03.287] [exthost] [trace] ExtHostCommands#registerCommand xmlTools.formatAsXml
```

**Comment by jrieken** [comment]
Yes - there is nothing I can do. It just takes a while and the `editor.action.formatDocument.none` exists on purpose. Usually, language commands that depend on extensions don't do anything when extensions aren't ready yet. However, with formatting we have added this default/catch-all command on purpose because users have been confused that they cannot format "go"-files even though they can format "ts"-files. That's why we have this special case for format...
