### ISSUE TITLE
JSDoc @this/@lends/@namespace tags are ignored inside Object

### ISSUE THREAD

**Issue by AGluk** [microsoft/vscode#90512]
Issue Type: <b>Bug</b>

<b>MyElement.d.ts</b>
```ts
declare class MyElement {
    constructor(target: Element);
    target: Element
}
```

<b>MyElement.js</b>

`@this` on globally defined function works as expected, Ctrl+Space shows the correct type of target - Element!
![image](https://user-images.githubusercontent.com/6419937/74323355-71ecd100-4d96-11ea-93d8-64a79434a1de.png)

`@this` before function in the object doesn't take into account!
![image](https://user-images.githubusercontent.com/6419937/74324433-158ab100-4d98-11ea-94dc-6ab4923ed95d.png)

`@lends` before the object itself is also not taken into account!
![image](https://user-images.githubusercontent.com/6419937/74324780-9ba6f780-4d98-11ea-9eba-5e1f84950fff.png)

the same with `@namespace`
![image](https://user-images.githubusercontent.com/6419937/74324680-70240d00-4d98-11ea-96b3-df002531d414.png)

I couldn't find the way to point the correct "this" type for function in objects.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Our JavaScript IntelliSense  is powered by the TypeScript project. Please [file a bug report/feature request upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
