### ISSUE TITLE
TypeScript functionality stops working intermittently 

### ISSUE THREAD

**Issue by MelvIsntNormal** [microsoft/vscode#90514]
Issue Type: <b>Bug</b>

While working on a TS document, VS Code's IntelliSense and syntax highlighting stops working after a seemingly random amount of time since the last reload. After it stops working, the Developer Console outputs various stack traces every time I type something that should invoke IntelliSense.

[Dev Console Log (-1581504690085.log)](https://github.com/microsoft/vscode/files/4191578/1581504690085.log)

VS Code version: Code - Insiders 1.43.0-insider (f4c95d5b9cfb2265f1730d564df1709533eff55e, 2020-02-12T06:05:34.092Z)
OS version: Linux x64 5.5.2-arch2-2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.54GB (3.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Thanks for the logs. I see you are using TS 3.7.4. Does this work properly if you switch to use TS 3.8-rc, which is included in the current VS Code insiders builds?

**Comment by MelvIsntNormal** [comment]
@mjbvz Just got back to work today, apologies for the late reply. I'll switch to that and update you if it happens again

**Comment by mjbvz** [comment]
@MelvIsntNormal Have you seen this again using the insiders build?

**Comment by MelvIsntNormal** [comment]
I have not seen this issue for a while now. However, I'm a bit wary that the version in my build is 3.*9*.0-dev.202002*23*. How would I switch to the versions you suggested?

**Comment by mjbvz** [comment]
Closing this for now since it seems fixed in insiders. Let me know if you see this in VS code 1.43 using TS 3.8
