### ISSUE TITLE
Add error code getter to FileSystemError

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#90517]
Add an `exists(uri: Uri): Thenable<boolean>` method to the `FileSystem` interface.

The current options are:
- trying to stat the `uri` and seeing if it fails — we have no way to tell why it failed;
- reading a parent directory — we may not have read access to the parent directory;
- using node's `fs` — only works for the local filesystem.

**Comment by JacksonKearl** [comment]
@jrieken I see `FileSystemProvider`s are spec'd to thow `FileSystemError.FileNotFound` on `stat` when the file doesn't exist, but `FileSystem` does not spec such errors.

**Comment by jrieken** [comment]
We have no plans for adding `exists` and instead `stat` should be used (this goes along the deprecated to NodeJS's [file.exists](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_exists_path_callback)-deprecation). Still, I do agree that we should spec the error

**Comment by iliazeus** [comment]
Would https://github.com/microsoft/vscode/pull/90586 be a passable solution?

**Comment by jrieken** [comment]
Re-open for API proposal/finalization. Proposal is to add a field `code` to the `FileSystemError`-class

```ts
export interface FileSystemError {
	/**
	 * A code that identifies this error.
	 *
	 * Possible values are names of errors, like [`FileNotFound`](#FileSystemError.FileNotFound),		 * or `undefined` for an unspecified error.
	 */
	readonly code?: string;
}
```

**Comment by iliazeus** [comment]
@jrieken should I rename the issue to better reflect the proposal?

**Comment by jrieken** [comment]
> @jrieken should I rename the issue to better reflect the proposal?

👍 

Reactions during the API meeting were positive, so I am confident that we can finalize this during the current milestone. One feedback item was to always have a value for `code`, e.g. let its default value be something like `FileSystemError` or `Unspecified`

**Comment by iliazeus** [comment]
> One feedback item was to always have a value for `code`, e.g. let its default value be something like `FileSystemError` or `Unspecified`

#92427 

I did a quick search of the codebase, and it looks like `'Unknown'` is usually used for such cases in the various error code enums.

**Comment by jrieken** [comment]
This is now in `vscode.d.ts` and will be stable API with the next relase. @iliazeus thanks for the help 👏
