### ISSUE TITLE
code upload issue 

### ISSUE THREAD

**Issue by tayyabhussain512** [microsoft/vscode#90519]
unable to upload code for SFCC, getting error

Using config file 'd:\BB\bookbrother\dw.json'
Error: EmptyError: no elements in sequence
Error: undefined

my dw.json file is 
{
    "username": "username",
    "password": "password@1234",
    "hostname": "*.demandware.net",
    "code-version": "version1"
}

**Comment by BENAZOUZK** [comment]
I have a same error

**Comment by gcaponero1** [comment]
The problem is the version of Prophet, install the version 1.2.11.

**Comment by gcaponero1** [comment]
The problem is the version of prophet, install version 1.2.11.
