### ISSUE TITLE
Macro definition digital display error

### ISSUE THREAD

**Issue by zhuoshipuyang** [microsoft/vscode#90513]
code↓
----------------------------
    `#define TEST 9`
--------------------------------------
`      #if TEST < 8`
`          XXXXXXXXXXXXXXX;`
`      #else`
`          XXXXXXXXXXXXXXX;`
 `     #endif`

Theoretically it should be #if TEST <8 is virtual below, but it is actually virtual below #else

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including what language you are using, and what extensions.

**Comment by zhuoshipuyang** [comment]
C++,the virtual font display
[
![sendpix0](https://user-images.githubusercontent.com/19303634/74395947-99ea3c00-4e4b-11ea-913c-130ec6d67747.jpg)
![sendpix2](https://user-images.githubusercontent.com/19303634/74395952-9b1b6900-4e4b-11ea-81b3-4df92f527d9b.jpg)

](url)

**Comment by JacksonKearl** [comment]
@zhuoshipuyang that looks correct to me -- the excluded path is rendered with reduced saturation.

**Comment by gjsjohnmurray** [comment]
@JacksonKearl doesn't the OP's first screenshot show them defining the macro with a value that should activate the else clause rather than the if?

**Comment by JacksonKearl** [comment]
Yes you're right, my bad. @zhuoshipuyang the C++ support is provided by a different repository, you should file an issue here: https://github.com/Microsoft/vscode-cpptools
