### ISSUE TITLE
Debug's session badge is slighty confusing in js-debug

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#90518]
Insiders:

- debug a simple express app with js-debug

Observe:
the debug icon's badge shows 2 sessions:

![2020-02-12_12-22-41](https://user-images.githubusercontent.com/1898161/74330823-ac546f00-4d92-11ea-8c2a-52fb0bd73ea9.png)

This is slightly confusing since a user is only aware of a single session.

The first "session" is an implementation detail of js-debug. It is not really a debuggee that the user can interact with (e.g. set breakpoints and stop somewhere). We should not count it as a real debug session (and we should consider to hide it in the CALL STACK view as long as there is only a single child).

**Comment by isidorn** [comment]
Agree, since this debug session is an implementation detail it should not be visible anywhere in the UX, not only in the badge.
So it should not be seen in the call stack, repl dropdown, debug toolbar etc...
I believe we would need new api for the debug extension to be able to specify this to the frontend.

**Comment by connor4312** [comment]
I think the badge should count how many top-level sessions there are, without counting children. From a naive user POV that's what I assumed its intention was.

**Comment by isidorn** [comment]
I can also change how the badge counts as you propose. However I do not see the value of seeing the parent session in the call stack view, or I might be missing something?

Also for the cluster sample, it might be nice to have the total number of clusters. Do I do agree that just having 1 might work.

**Comment by connor4312** [comment]
>  However I do not see the value of seeing the parent session in the call stack view, or I might be missing something?

We may want to hide it from the UI if there's only a single child, but in js-debug having the parent session is important. If I have a shell script as my `program` that spins up multiple concurrent Node processes, these Node process will end up being children of the 'virtual' parent session; if we didn't have the parent we'd show the first process. We could alternately have some shim with custom dap requests that result in multiple `startDebugging` requests for each child, but then there's no way for a user to easily terminate the entire tree of debug sessions.

**Comment by isidorn** [comment]
For terminating multiple debug sessions -> this seems like an unrelated issue which we can fix via introducing a new command, or allowing multi selection in the call stack view.
Yes, havgin mutliple startDebugging for each child makes sense to me.

**Comment by connor4312** [comment]
I don't agree that it's unrelated. Say I have a shell script like that which spawns a cluster of processes in some way, and a config that debugs a frontend. Right now, if I go ahead and boot that from a compound launch config, users get a tree like this:

```
Open Frontend
└── index.html
Start Server
├── cluster.js
├── cluster.js
└── cluster.js
```

Without a top-level session that would be simply

```
index.html
cluster.js
cluster.js
cluster.js
```

It becomes harder to see which is which, and there's no clear way to kill all the cluster children. Mentally I think this _should_ be a hierarchal view since the clusters are children of a single launch config.

**Comment by isidorn** [comment]
I meant we have that issue other way that there are multiple sessions which the users wants to close together.

If you really like the hierarchial view you can stick with that but please use the heuristic: if there is only one child, do not create a parent.
We use this heuristic across the CallStack view to make the data more presentable to the user - we do not show threads if there is only 1, same with sessions etc...

**Comment by connor4312** [comment]
The difficulty from the debug adapter is that we cannot know if there will be multiple children until the point in time that we see them--a program might spawn any number of children at any time--at which point our session is already set up and running. We could terminate the old top-level session and recreate it as a child, but restoring all the debugger state perfectly would be very delicate.

**Comment by weinand** [comment]
IMO there are two issues:
- what does the badge show?
- what do we do with "pseudo" debug sessions (sessions that are not really debuggable but only exist as an implementation detail).

**What does the badge show?**
It should show the number of user initiated sessions, but not their sub-sessions. So for the cluster example or a session with the new js-debug the badge always shows 1 (independent from the number of worker processes or spawned sub processes). 
For compound session we could use the same approach but I understand that might be difficult to achieve since we have no representation of a compound config. We only see two or more sessions without a common parent.

**What do we do with "pseudo" debug sessions?**
To avoid cluttering the CALL STACK view with "uninteresting" sessions (e.g. the pseudo session of the new js-debug), we should use the "compact" tree rendering that we use elsewhere: automatically hide parent nodes if they only have a single child. We do this already in the CALL STACK and LoadedScripts view. Now we should extend this for hierarchical sessions as well.
But there is a twist: if the parent is actually a "real" debug session (and not a pseudo session), there must be a way to turn off the auto-hiding. Whether the distinction between the two cases can be made implicitly by DAP usage or whether we need explicit extension API, is an open question.

**Comment by isidorn** [comment]
Agree for the number badge. I have pushed a fix for that.

Also agree for the "pseudo" debug sessions argument: we should hide them.
We can first try to be smart and if that does not work we need to add API (for example a capability).

Oversimplified heuristics which might work: 
* when there is only one parent session `A` and only one child session `B`, only render the sessions if they are stopped. We would only render `A` if `B` exists and `A` is stopped. Of course we render `A` if it has multiple child sessions `B1`, `B2`... Downside of this approach is that user can not pause / terminate `A` when it is not stopped.
* We consider a session a dummy session if some request has never been sent to it. Dummy sessions we do not render we they have only one child.

**Comment by isidorn** [comment]
Just want to add that showing the parent sessions is one of the biggest pain points for me personally while self hosting. 
@connor4312 let me know how you would prefer that we tackle this. Also js-debug can not compute better names than the current number naming?

![Screenshot 2020-02-19 at 15 47 54](https://user-images.githubusercontent.com/1926584/74845420-4b4b0f00-532f-11ea-8d59-82d28260f98b.png)

**Comment by connor4312** [comment]
Naming is definitely something we can fix, at least in most cases :)

As far as getting rid of the top-level wrapper session. There have been some refactors in js-debug recently which make this easier to do. That is, not have the wrapper session and if there are multiple children they would appear as separate top-level sessions in the UI. The outstanding question I have, is around how users will kill that session. For instance, if the 'program' is a shell script that runs `node a & node b & wait` in bash, we currently have the ability to kill that command by sending `terminate` to the wrapper session. If `node a` and `node b` were totally separate debug sessions, how would that work? We could make killing one also kill the other, but that seems like a kind of weird experience. Thoughts?

**Comment by isidorn** [comment]
@connor4312 my thoughts are keep it simple: killing one does not kill the other. User has to manualy kill both. Once users complain this is too much work we can think about simplyfing.
This problem is similar to the Compounds on VS Code side. Killing one session does not kill the others that were launch with it as part of the Compoound. Users find this behavior intuitive, and we should not change it for js-debug imho

**Comment by isidorn** [comment]
@connor4312 just a friendly ping for this. Could we look into imrpoving the multi sessions for js-debug. Also unassagning myself for now since this should mostly be done by the js-debug extension

**Comment by connor4312** [comment]
Thinking about this some more, there's another case I'm having trouble with. Say I have this shell script that I set as my `program`:

```sh
npm run build
sleep 10 # or do other things...
npm test
```

Today this is not hard to deal with. We have the top level session, and the build and tests tasks would come in as children as they start up. During the `sleep`, there would be no child sessions.

Without a top level session, the question arises--what happens during the `sleep`? There is no Node.js debug target running. The options I see are:

1. Not show anything any running session during this time. This would be the natural result of not having the top-level session, but then the shell script would be a background task that's impossible to monitor or terminate.

   This is the approach the debug terminal takes today, but the terminal itself is the UI that can be used to monitor and terminate the script. Running from a launch config using the `internalConsole` (vs an internal or external terminal) we don't get this.

2. Open runtimeExecutables that aren't  `node`/`node64` in the integratedTerminal by default. I don't like this very much as it forces a workflow change on users.
3. Keep whatever the last session target we had open as a 'zombie' and use that as the handle to the shell script. That is, we would pretend `npm run build` is still ongoing until the new script starts. Would solve the problem but kind is a bit of a hack and confusing to users.
4. Don't support this scenario / treat it as an edge case: kill the shell script when the number of attached targets reaches 0.

**Comment by isidorn** [comment]
I feel like both 1 and 4 are ok options. I would go with 1 and if the user need arrises for this we can investigate what can be done (create some zombie fake session etc)

**Comment by connor4312** [comment]
I think this is now resolved with the compact sessions work. Reopen if there's any remaining parts to address.
