### ISSUE TITLE
mouse-wheel scroll on integrated terminal scrolls 1 line at a time

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#9052]
- VSCode Version: 1.3.0
- OS Version: Xenial

Steps to Reproduce:

1. Print a lot of text to the integrated terminal
2. Scroll the mouse wheel

Notice that the mouse-wheel scrolls one line at a time... this is really slow, and not like other terminals (gnome terminal scrolls 4 lines at a time by default).
Would be nice if mouse-scroll did scroll the normal amount of lines.

**Comment by Tyriar** [comment]
This would come with implementing a native scroll bar, closing in favor of #6602.
