### ISSUE TITLE
Disable "Debug Console input history suggestions" configuration

### ISSUE THREAD

**Issue by pankaj-webkul** [microsoft/vscode#90520]
Allow "Debug Console input history suggestions" to be disabled from settings.

**Comment by kalingibbons** [comment]
God Yes! The debugger is damn near unusable in this current state. If I'm moving quickly, the history suggestion will substitute something like this:

![image](https://user-images.githubusercontent.com/11838956/74899352-e78a0b80-5359-11ea-939e-4637bb7a92b5.png)

Then, while I'm fixing it, it will autocomplete a different, but still totally wrong history item. It basically takes me 3 to 5 attempts to get a single correct statement entered into the debugger. I keep having to periodically restart vscode to clear the history so I can have a half hour to get any work done, lest the required attempts count keep climbing. Maybe I can set up some kind of global git hook to restart it after every commit 😄 

I am loving all the rest of the enhancements in the January update, though.

**Comment by isidorn** [comment]
Added `debug.console.historySuggestions` which by default is `true`. So you can set it to `falser`.
You can try it out in tomorrow's vscode insdiers.
Thanks for feedback
