### ISSUE TITLE
Update to 1.42: Getting EACCES: permission denied 0.0.0.0:9000

### ISSUE THREAD

**Issue by khooz** [microsoft/vscode#90523]
- VSCode Version: 
  * Version: 1.42.0 (system setup)
  * Commit: ae08d5460b5a45169385ff3fd44208f431992451
  * Date: 2020-02-06T10:51:34.058Z
  * Electron: 6.1.6
  * Chrome: 76.0.3809.146
  * Node.js: 12.4.0
  * V8: 7.6.303.31-electron.0
  * OS: Windows_NT x64 10.0.18363
- OS Version: Windows 10 Pro 1909 Build 18363.592

Steps to Reproduce:

1. Install VS Code prior to 1.42
2. Install PHP package from welcome screen (which installs [felixfbecker/vscode-php-debug](https://github.com/felixfbecker/vscode-php-debug))
3. Make the default debug configuration for PHP
4. Run a debug session (works fine)
5. Update VS Code using the setting's Cogwheel to recent
6. Run a debug session. It aborts saying:
```
Error: listen EACCES: permission denied 0.0.0.0:9000
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at c:\Users\Admin\.vscode\extensions\felixfbecker.php-debug-1.13.0\out\phpDebug.js:236:24
    at new Promise (<anonymous>)
    at createServer (c:\Users\Admin\.vscode\extensions\felixfbecker.php-debug-1.13.0\out\phpDebug.js:184:40)
    at PhpDebugSession.<anonymous> (c:\Users\Admin\.vscode\extensions\felixfbecker.php-debug-1.13.0\out\phpDebug.js:240:27)
    at Generator.next (<anonymous>)
    at c:\Users\Admin\.vscode\extensions\felixfbecker.php-debug-1.13.0\out\phpDebug.js:7:71
    at new Promise (<anonymous>) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 9000
}
```
Somehow VS Code prevents scripts from binding to ports? Port 9000 is not already bound as you can see here:
![Imgur](https://i.imgur.com/6Cs2wZL.png)

However, it allows me to use ports greater than and equal to 10000.

Does this issue occur when all extensions are disabled?: This needs php-debug extension

**Comment by alexdima** [comment]
@khooz Please open an issue directly against https://github.com/felixfbecker/vscode-php-debug

VS Code does not interfere with port listening, so IMHO this might be an issue with the extension itself... Perhaps it tries to bind twice to the same port, etc.  It's also curious that such a nice port number would be used by the extension. Normally, the best practice is to bind to port `0` which means that the OS should allocate to you an available port and then you can read the port and use that. IMHO that should be the pattern used by the extension, given that this is not a user-facing port.
