### ISSUE TITLE
Add API support for deprecating settings

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#90526]
Currently, if I need to rename an old setting in my extension I have to go through quite a bit of effort. The new version of a setting can be created, but there is no way to remove the old version of the setting, unless I keep it's definition in the package.json, which then defeats the purpose of renaming it.

It would be handy if there was a way to mark a setting as 'deprecated' and even better if there was a way to indicate how the setting had changed.

**Comment by sandy081** [comment]
Did you try using `deprecationMessage` while registering the configuration?

**Comment by Gruntfuggly** [comment]
No - is it documented anywhere?

**Comment by sandy081** [comment]
> No - is it documented anywhere?

No.

> I can see it shows a message in red in the settings GUI. Does it do anything else?

No, this will help setting owners to inform users about deprecated setting and remove it eventually. We do the same too,

**Comment by Gruntfuggly** [comment]
OK thanks - it's a good starting point.
