### ISSUE TITLE
Unable to open file: Invalid arguments error, after updating to 1.42

### ISSUE THREAD

**Issue by AgisilaosVasileiadis** [microsoft/vscode#90524]
When trying to debug a COBOL file, an error message appears saying :
"**Unable to open 'filename.cbl': Invalid arguments.**"  

If the file is already opened,  it is closed forcibly after that.
If the file is not already opened, it is not opened after that.
When I manually open the file I can see that it is being debugged and the statement where it stopped is highlighted like it would normally be. 

The language that is debugged in this occasion is COBOL.
No other extension is used at the same time.
This started directly after the VSCode updated to v. 1.42

- VSCode Version: 1.42
- OS Version: 10

Steps to Reproduce:

1. Start a debug session.
2. Try to resume or step over.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Please file on your COBOL extension, thanks
