### ISSUE TITLE
Tests: consider to convert search smoke tests to integration tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90537]
We would like to reduce our smoke tests and move them to integration tests if possible. The advantage is:
* integration tests run nightly (including browser)
* integration tests run local and remote
* smoke test has a history of being very flaky and harder to maintain compared to integration tests

Tests:
```
Search
      ✓ searches for body & checks for correct result number
      ✓ searches only for *.js files & checks for correct result number
      ✓ dismisses result & checks for correct result number
      ✓ replaces first search result with a replace term
```

Feel free to close if this is not easily possible.

**Comment by roblourens** [comment]
We have good coverage of search in integration tests already, and these smoke tests are testing the UI in a way that we can't do in integration tests. If we want to reduce the number of smoke tests, we could delete some of these.
