### ISSUE TITLE
Tests: consider to convert Terminal smoke tests to integration tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90539]
We would like to reduce our smoke tests and move them to integration tests if possible. The advantage is:
* integration tests run nightly (including browser)
* integration tests run local and remote
* smoke test has a history of being very flaky and harder to maintain compared to integration tests

Tests:

```
Terminal
      ✓ opens terminal, runs 'echo' and verifies the output
```

Feel free to close if this is not easily possible.

**Comment by Tyriar** [comment]
@bpasero is there a way to make custom calls that are not in the extension API? You cannot for example get at the terminal buffer from vscode's extension API.

**Comment by Tyriar** [comment]
If not, adding a way to do this, a "private testing api", would probably enable us to replace all the single-window smoke tests.

**Comment by bpasero** [comment]
@Tyriar yeah such API currently does not exist. I was hoping an extension could get at the terminal output, isn't there extension API to do that?

**Comment by Tyriar** [comment]
Well actually there is the forever proposed one to read text which should work in our tests so I think I can do this without many changes.

**Comment by bpasero** [comment]
@Tyriar yeah proposed is totally fine 👍

**Comment by bpasero** [comment]
Thanks!
