### ISSUE TITLE
How to disable the background of these lines?

### ISSUE THREAD

**Issue by jonasmarco** [microsoft/vscode#90534]
How to disable the background of these lines?

![VSCODE](https://i.imgur.com/P4D4Lm3.jpg)

PS: this happens in all types of files, not only in style sheets.

**Comment by BrandonShega** [comment]
This was added in the latest release of Code, check out the [Release Notes].(https://code.visualstudio.com/updates/v1_42)

You can disable it with 

```"editor.foldingHighlight": false```

You can also change the color using
```
"workbench.colorCustomizations": {
  "editor.foldBackground": "#355000"
}
```
