### ISSUE TITLE
Tests: consider to convert CSS smoke tests to integration tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90538]
We would like to reduce our smoke tests and move them to integration tests if possible. The advantage is:
* integration tests run nightly (including browser)
* integration tests run local and remote
* smoke test has a history of being very flaky and harder to maintain compared to integration tests

Tests:
```
CSS
      ✓ verifies quick outline
      ✓ verifies warnings for the empty rule
      ✓ verifies that warning becomes an error once setting changed
```

Feel free to close if this is not easily possible.

**Comment by octref** [comment]
@sandy081 Correct me if I'm wrong, but I guess you wrote those tests to test views/panels, not to test CSS functionalities. So there's no way to move them to CSS integration test, right?

**Comment by sandy081** [comment]
@octref this is not testing views/panels but smoke testing css functionality as it was written in manual smoke tests.

**Comment by octref** [comment]
The tests are all covered by vscode-css-languageservice.

**Comment by bpasero** [comment]
Cool!

**Comment by aeschli** [comment]
By removing the CSS smoke tests, we lost the following test coverage:
- css files are correctly associated to css files
- the outline shows up on a given input file with the correct number of entries
- the problems view show the correct number of error
- changing a setting in the settings editor changes the number of errors
- the css language server works as well as the communictaion of document symbols / problems across 3 processes.

I suggest we bring it back...

**Comment by octref** [comment]
@aeschli I thought this was for testing CSS functionality, but now it seems to be a hodgepodge test for language features in workbench. I will bring it back then, but naming them more explicitly as language server tests.

**Comment by aeschli** [comment]
Yes, giving it a better name would be good. Let's call it Language Features.

**Comment by aeschli** [comment]
I made the rename
