### ISSUE TITLE
Scrollbar can't be clicked or dragged on 1.42.0 xfce redhat

### ISSUE THREAD

**Issue by ginozhu** [microsoft/vscode#90531]
- VSCode Version: 1.42.0
- OS Version: redhat 7.3 + xfce

Steps to Reproduce:

1. install vscode 1.42.0 on redhat 7.3
2. click or drag scroller bar in a long file

Working fine on 1.41.1

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Is this still an issue with our latest insiders https://code.visualstudio.com/insiders ?
