### ISSUE TITLE
Cant Scroll up on integrated terminal

### ISSUE THREAD

**Issue by aelbore** [Microsoft/vscode#9053]
- 1.3.9:
- OS X El Capitan:

Steps to Reproduce:

1. has long string in terminal (integrated terminal)
2. cant scroll up.

**Comment by ownadi** [comment]
:+1:

**Comment by Tyriar** [comment]
You're likely either experiencing:

- Shrinking and growing the terminal horizontally breaks scrolling in the resized area #8740 (fixed in Insiders)
- Integrated terminal scrolling not working in oh-my-zsh #7817
