### ISSUE TITLE
Improve "Open editors" Feature View

### ISSUE THREAD

**Issue by snigle** [microsoft/vscode#90533]
Hello, we had an idea to improve the Explorer feature.

When I work on lots of file and I have an enormous workspace, it's difficult to navigate between opened files and folders. The only way I found is the CTRL+P (search file).

I thought that it could be great if you display the "open editors" as a tree view exactly like the workspace explorer (group file by folder).
It should be easier to switch between open files.

Do you think it could be implemented ?

**Comment by usernamehw** [comment]
Possible duplicate of #81544

**Comment by snigle** [comment]
Yes it's exactly the same as #81544!
Thanks I will up it :)
