### ISSUE TITLE
Install all remote extensions locally [Remote: SSH]

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/vscode#90548]
I know https://github.com/microsoft/vscode/issues/83675 exists, but I don't think it contains this scenario. If it does so, please close this issue.

I have a remote server, where I "store" my extensions and whenever I log into that server I would like to install all of the extensions locally. A button, a menu option or a command would be perfect.

I know the extensions and settings sync functionality is being worked on, but I think this should be implemented, as it allows scenarios like installing all extensions from a shared server, without credentials (except ssh, of course).

**Comment by sandy081** [comment]
Added `Install Remote Extensions Locally...` command to support this.
