### ISSUE TITLE
V1.42 no typescript features working...completely broken.

### ISSUE THREAD

**Issue by aroraenterprise** [microsoft/vscode#90547]
Summary: Today was a nightmare when vs code updated to 1.42
React/typescript
Typescript: 3.7.5
MacOS. High Sierra
Autocomplete not working, imports not working, anything language feature related broken. Uninstalled all extensions deleted all vscode files installed fresh. Worked for two mintues. stops working after you add a new file. Downgraded to 1.41.1 now that didn't work anymore either. (I think this is because 3.7.5 was now installed as i upgraded my dependency). finally went to file this issue after chatting on Slack. Downloaded insiders version -> it is typescript 3.8.1-rc and it works for now.

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Can you please try upgrading VS Code 1.42 to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that fix the issue?

**Comment by ming436534** [comment]
I upgraded and using that extension, but still not working

**Comment by aroraenterprise** [comment]
What ming said is right. The intellisense is just not responding. Where did you find the error?

**Comment by mjbvz** [comment]
@aroraenterprise First make sure you are using the VS Code insiders build. If you see the error:

1. In VS Code, run `Developer: Toggle developer tools`
1. Then open the console from the developer tools. Please share any TypeScript related errors you see in there

**Comment by aroraenterprise** [comment]
Hey, I started using the insider edition which is working fine.

**Comment by mjbvz** [comment]
Thanks for testing.

Let me know if you see this again in VS Code 1.43 (the current insiders build)
