### ISSUE TITLE
TypeScript errors in new files until reload VSCode

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#9054]
- VSCode Version: 1.3.0
- OS Version: Windows 7 Version 6.1 SP1

Steps to Reproduce:

1. Install angular-cli 1.0.0-beta.9 `npm install -g angular-cli`
2. Create a new Angular project `ng new TestApp`
3. Open TestApp-Folder with VSCode
4. Create a new TypeScript file in the src/app folder e.g. first.component.ts
5. Insert code in file (see below)

As you can see now VSCode shows some errors in first.component.ts

1. Cannot find name 'module'
2. Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

When you take a look in src/tsconfig.json you'll see that **experimentalDecorators** is set to true that typings.d.ts is included in the files section. While src/typings.d.ts declares the module variable.

Only if you reload VSCode the errors disappear but when you have a TypeScript file in a (sub-) subfolder it may happen, that the error will appear again.

**src/app/first.component.ts**
```typescript
import { Component, OnInit, OnDestroy } from "@angular/core";

@Component({
	moduleId: module.id,
	selector: "first-component",
})
export class NameComponent implements OnInit, OnDestroy {

	constructor() {}

	public ngOnInit() {}

	public ngOnDestroy() {}

}
```

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/6200. This is actually a problem of the ng new command generating a wrong tsconfig.json. See https://github.com/angular/angular-cli/issues/684 as well.
