### ISSUE TITLE
workbench.action.togglePanelPosition was removed?

### ISSUE THREAD

**Issue by udielenberg** [microsoft/vscode#90544]
- VSCode Version: 1.42.0
- OS Version: macOS catalina

Steps to Reproduce:

1. Try to add a new shortcuts into `keybinding.json`
2. the autocomplete doesnt have 'workbench.action.togglePanelPosition'

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/updates/v1_42#_moving-the-panel

**Comment by udielenberg** [comment]
Oh, thats a real bummer

**Comment by JacksonKearl** [comment]
@udielenberg 

You can use an extension like https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler to create your own toggle command between any positions:

```
{
	"key": "F4",
	"command": "toggle",
	"args": {
		"id": "panelLocation", // must be unique
		"values": [ // Note: use the same settings in each values object
			{
                                 "workbench.panel.defaultLocation": "right"
			},
			{
                                  "workbench.panel.defaultLocation": "bottom"
			}
		]
	}
}
```

**Comment by wzlwit** [comment]
why not keep that command (just right <->bottom, or plus: left -> bottom), that is useful and we just need one key binding.... 

Feel sad it is removed.

**Comment by JacksonKearl** [comment]
Having a separate command for each possible cycle explodes quickly. With two positions its one command, with three its 4, if we ever add a fourth it'd be 11.

**Comment by dschuessler** [comment]
@JacksonKearl I hope it is ok if I ask here, because I think it is safe to assume, people affected by this change will look for a solution here.

You're example doesn't work. According to https://github.com/hoovercj/vscode-api-playground/issues/4#issuecomment-330988921 `"command": "toggle"` needs to be replaced with `"command": "settings.cycle"`, but even then the panel stays in its place. Have you tried it yourself?

**Comment by JacksonKearl** [comment]
@sbatten I would expect the panel to write to and read from "workbench.panel.defaultLocation" for its location.

**Comment by sbatten** [comment]
@dschuessler please use this for a single keybind method to get the old behavior
```
    {
        "key": "<your keybind here>",
        "command": "workbench.action.positionPanelRight",
        "when": "panelPosition == 'bottom'"
    },
    {
        "key": "<your keybind here>",
        "command": "workbench.action.positionPanelBottom",
        "when": "panelPosition == 'right'"
    }
```
