### ISSUE TITLE
Can't un-sign CLA agreement

### ISSUE THREAD

**Issue by shogerr** [microsoft/vscode#90549]
Users cannot un-sign the CLA agreement short of starting a new Github account. I personally wish to expunge my signature to the agreement.

**Comment by jhpratt** [comment]
The CLA is a contract. How would "unsigning" it even work? Any contributions you've previously made remain bound by that, and nothing forces you to contribute in the future.

**Comment by shogerr** [comment]
Drop the record associated with this account from the MS SQL Server database for CLA agreements Microsoft operates for the repo, of course.

**Comment by jeffwilcox** [comment]
Hi,
The CLA Assistant can note the date that you wish to no longer accept the CLA as 2/12/2020, can you confirm @shogerr that this is what you would like the system to reflect?

In the future, you will be able to sign the CLA again, if you wish, and from that date forward any additional contributions would be covered again.

**Comment by shogerr** [comment]
Yes, please remove my account from the CLA.

**Comment by jeffwilcox** [comment]
@shogerr we have completed your request and terminated your CLA agreement with Microsoft as of today, 2/13/2020.

@chrisdias feel free to close this issue.
