### ISSUE TITLE
When signature or qualifier are long, label can be cut off

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#90552]
Related: #39441

We should always give higher precedence to label than signature/qualifier:

![image](https://user-images.githubusercontent.com/4033249/74373177-cb520180-4d90-11ea-9623-e09c6c4db78d.png)

```ts
import * as vscode from 'vscode'

const documentation = 'placeholder documentation'

const oldItems: vscode.CompletionItem[] = [
  {
    label: 'short',
    documentation
  },
  {
    label: 'short-with-short-details',
    detail: 'details',
    documentation
  },
  {
    label: 'long-with-no-details-looooooooooooooooooooooooooooooooooooooooooooong',
    documentation
  },
  {
    label: 'long-with-short-details-looooooooooooooooooooooooooooooooooooooooooooong',
    detail: 'details',
    documentation
  },
  {
    label: 'long-with-long-details-looooooooooooooooooooooooooooooooooooooooooooong',
    detail: 'details-looooooooooooooooooooooooooooooooooooooooooooong',
    documentation
  }
]

function getItem(name: string, signature: string, qualifier: string, type: string, detail?: string): vscode.CompletionItem {
  return {
    label: name,
    label2: {
      name,
      signature,
      qualifier,
      type
    },
    detail: detail || 'placeholder details',
    documentation
  }
}

const items: vscode.CompletionItem[] = [
  getItem('name', '(a, b)', 'some.qualifier', 'MyType'),
  getItem('name-looooooooooooooooooooooooooooooooooooooooooooong', '(a, b)', 'some.qualifier', 'MyType'),
  getItem('name', '(a, b, looooooooooooooooooooooooooooooooooooooooooooong)', 'some.qualifier', 'MyType'),
  getItem('name', '(a, b, looooooooooooooooooooooooooooooooooooooooooooong)', 'some.qualifier', 'MyTypeLooooooooooooooooooooooooooooooooooooooooooooong'),
  getItem('name', '(a, b)', 'some.qualifier.looooooooooooooooooooooooooooooooooooooooooooong', 'MyType'),
  getItem('name', '(a, b)', 'some.qualifier', 'MyTypeLooooooooooooooooooooooooooooooooooooooooooooong'),
  getItem('name', '(a, b)', 'some.qualifier', 'MyType', 'details-looooooooooooooooooooooooooooooooooooooooooooong'),
]

export function activate(context: vscode.ExtensionContext) {
  vscode.languages.registerCompletionItemProvider('plaintext', {
    provideCompletionItems() {
      return oldItems.concat(items)
    }
  })
}
```

**Comment by octref** [comment]
Improved:

![image](https://user-images.githubusercontent.com/4033249/74374388-27b62080-4d93-11ea-84d1-1e9498c78071.png)

**Comment by jrieken** [comment]
@octref Maybe also give the type-label a higher priority than the qualifier

**Comment by octref** [comment]
@jrieken Type already has higher-priority, but it has a max-width of 45%, same as the old details rendering. Or do you mean give signature help higher priority than qualifier?

**Comment by jrieken** [comment]
![74374388-27b62080-4d93-11ea-84d1-1e9498c78071](https://user-images.githubusercontent.com/1794099/74513989-0dec1900-4f0c-11ea-84a6-2eb015207189.png)

I would have expected a type label for those two items

**Comment by octref** [comment]
I can give `type` a minimum width, but I'm thinking what should be my layout strategy when space is not enough for more than 1 field.

**Comment by connor4312** [comment]
I noticed that the 🔧  has vertical alignment issues on looong names

![image](https://user-images.githubusercontent.com/2230985/75579551-f720e880-5a1a-11ea-8b85-6bbd19076d44.png)

**Comment by octref** [comment]
The label name is no longer being cut off so I wouldn't reopen this.
@connor4312 I opened #91784 as candidate for the new bug.
@jrieken I moved https://github.com/microsoft/vscode/issues/90552#issuecomment-586150833 to a new bug #91785 for March.

Verifier: Please verify that the `name` field shows full width:

![image](https://user-images.githubusercontent.com/4033249/75585751-ab287080-5a27-11ea-8b2a-c0707742107b.png)

Updated: 

![image](https://user-images.githubusercontent.com/4033249/75585789-c2fff480-5a27-11ea-92c6-31f962f907af.png)
