### ISSUE TITLE
Revisit OS X fonts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9055]
@fitojb says of 50d96e219097973dcce551cb6cdc589ecaba7362

> The Display variant of the SF typeface should not be used for small UI copy, as it is simply too thin. Please use the Text variant instead: .SFNSText-Light. And then, I'm not sure why pick the Light weight over Regular...

**Comment by joaomoreno** [comment]
Verifier reference:

- https://developer.apple.com/videos/play/wwdc2015/804/?time=610

**Comment by aeschli** [comment]
Verified that we now use the San Fransisco Text font.
