### ISSUE TITLE
userDataSyncService.resetLocal doesn't appear to do anything

### ISSUE THREAD

**Issue by scovetta** [microsoft/vscode#90555]
The userDataSyncService.ts -> [resetLocal](https://github.com/microsoft/vscode/blob/master/src/vs/platform/userDataSync/common/userDataSyncService.ts) function looks like it's missing a call to synchroniser.resetLocal(), see below.

```
	async resetLocal(): Promise<void> {
		await this.checkEnablement();
		for (const synchroniser of this.synchronisers) {
			try {
				synchroniser.resetLocal(); <-- Suggest adding this here?
			} catch (e) {
				this.logService.error(`${synchroniser.source}: ${toErrorMessage(e)}`);
				this.logService.error(e);
			}
		}
	}
```

**Comment by alexr00** [comment]
How should this be verified?

**Comment by sandy081** [comment]
Turn off sync and Turn on sync again. This should show the first time sync dialog.
