### ISSUE TITLE
Don't use rootPath in built-in extension

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#90562]
Discovered as part of #88391

Looks like some of out built-in extensions are still using `rootPath`:

- [x] Php @roblourens https://github.com/microsoft/vscode/blob/ca22de4b17af4ec84394537546998bba195e84cd/extensions/php-language-features/src/features/validationProvider.ts#L250
- [ ] Emmet @octref  https://github.com/microsoft/vscode/blob/99d5ff9c0f5a66a9e1cd7d49f9af6892e13f96a4/extensions/emmet/src/util.ts#L35
- [x] json @aeschli https://github.com/microsoft/vscode/blob/ce31ace9d9e4a67851c0fb4ed5633ebb494f8c6f/extensions/json-language-features/client/src/jsonMain.ts#L415

**Comment by roblourens** [comment]
lol, how did I miss those?

**Comment by roblourens** [comment]
The builtin PHP validation is very simple and I've wanted to delete it, and nobody has ever complained that it doesn't work correctly in multiroot, so I'm not bothering to actually fix it for multiple folders.

**Comment by gjsjohnmurray** [comment]
Looks like #87493 is this for Emmet

**Comment by octref** [comment]
Emmet seems a bit more complicated — I'll track it in #87493 then.
