### ISSUE TITLE
Extension api that show input box in workspaces

### ISSUE THREAD

**Issue by Senasiko** [microsoft/vscode#90564]
The `explorer.newFile` command create an input box in workspaces, like this.
![2254DA84-3D2C-4977-9AD2-64A83427546E](https://user-images.githubusercontent.com/14193002/74397573-f5b6c400-4e4f-11ea-8185-135ccdebf1dd.png)
But I can't find an extension api that do it.
So I want to have an api, like `vscode.workspaces.showInputBox(uri: vscode.Uri): string`

**Comment by JacksonKearl** [comment]
It's not clear to me what exactly you're trying to do. What would `uri` be, what would this return, and what would it do? Also what problem are you trying to solve?

**Comment by Senasiko** [comment]
I want to do something in a folder, so I want to show an input box under folder to get user's input to run different command, the `uri` is folder that user selected or click context menu with. the return value is the input value, or an Object include input value and folder path.
`vscode.workspaces.showInputBox(folder: vscode.Uri): string` 
or
`vscode.workspaces.showInputBoxUnderFocusedFolder(): { value: string, folder: vscode.Uri }`

**Comment by JacksonKearl** [comment]
It's still not clear to me how this would be used, which helps me to understand if an existing solution might work. For instance, could you have a context menu item that opens an [input box](https://code.visualstudio.com/api/references/vscode-api#window.showInputBox) work?

**Comment by Senasiko** [comment]
For example. I want to create `html` `css` `js` file just by inputting once. I can click a context menu of folder and `window.showInputBox`, get the input value as file name. 
the command callback.
```ts
vscode.commands.registerCommand('extension.myExtension', async function (event) {
  const name = await vscode.window.showInputBox();
  const { fsPath } = event;
  const fileName = fsPath + name + '.html';
  ...
}
```
It's ok.
If i have a keybinding.
```json
{
  "keybindings": [
    {
	"command": "extension.myExtension",
	"key": "s",
	"mac": "s",
	"when": "filesExplorerFocus"
    }
  ]
}
```
Select a folder and press 's', in the command callback.
```ts
vscode.commands.registerCommand('extension.myExtension', async function (event) {
  const name = await vscode.window.showInputBox();
  // event is undefined, can't get the selected folder's path.
  // const { fsPath } = event;
  ...
}
```
so, if there has an api that can get input value and selected folder's path when use keybinding, it's useful for me.

**Comment by isidorn** [comment]
Got it. Leaving this open as a feature request.
We will probably not do this, as we do not expose UX things like this in the API.
