### ISSUE TITLE
Reference tab showing blank row for a searched item

### ISSUE THREAD

**Issue by khaled4vokalz** [microsoft/vscode#90566]
See the image. When I tried to trigger show all **references** for a function, it's showing a blank row under a file. Even though when I click it it works and takes me to that usage.

![image](https://user-images.githubusercontent.com/14083655/74399899-8b4d5600-4e46-11ea-99b0-52a9e8f671be.png)

**system info:**

Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-29-generic

**Comment by jrieken** [comment]
Please add information/steps that allow me to reproduce this

**Comment by khaled4vokalz** [comment]
@jrieken , There's no steps. I have my project that has lots of folder structure.
1. Open an angular service that has some function in it which is used in other places.
2. Click mouse right button on the function name and trigger **Find all references**
3. You'll see the problem mentioned in the image. 

I've found it today also.
![image](https://user-images.githubusercontent.com/14083655/74722737-a1528080-5263-11ea-95d5-500beab730ba.png)
