### ISSUE TITLE
How to remove unmatched outline in Integrated Terminal

### ISSUE THREAD

**Issue by LOGANLEEE** [microsoft/vscode#90568]
- VSCode Version:
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.4.0
- OS Version: Mac OS Catalina Version 10,15,4 Beta (19E224g)

Steps to Reproduce:

1. open integrated terminal
2. click with mouse point

Does this issue occur when all extensions are disabled?: YES

![Screen Shot 2020-02-13 at 15 10 30](https://user-images.githubusercontent.com/26853553/74406722-c5811c80-4e73-11ea-9177-d281a263ac3d.png)

**Comment by Tyriar** [comment]
Not sure how to reproduce this, it's always the correct width for me:

<img width="736" alt="Screen Shot 2020-02-13 at 9 23 07 AM" src="https://user-images.githubusercontent.com/2193314/74460876-7cfd3b00-4e42-11ea-994f-42983bb291a0.png">

**Comment by LOGANLEEE** [comment]
It's gone now after rebooting computer.

Maybe that's just was UI bug.

Sorry to bother you :(

**Comment by Tyriar** [comment]
Weird, will keep an eye out for it.
