### ISSUE TITLE
Extra : and ; getting added on pressing tab after : in css rules in scss file

### ISSUE THREAD

**Issue by codingonHP** [Microsoft/vscode#9056]
- VSCode Version: Code - Insiders 1.4.0-insider (4b84f6d791203e71fee10537f27fc8add9357160, 2016-07-08T07:45:28.445Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. write a css rule in scss file.
2. press tab after : in any of the rule
3. notice: extra : and ; are getting added
![image](https://cloud.githubusercontent.com/assets/7105293/16723170/03ee3b30-4769-11e6-9a6d-7756d67a758a.png)

![image](https://cloud.githubusercontent.com/assets/7105293/16723146/d330c2b0-4768-11e6-8463-5cae073c5b2b.png)

**Comment by aeschli** [comment]
Emmet does that.

**Comment by mrmlnc** [comment]
Hi, @codingonHP,

Unfortunately, this is not a problem VS Code. It is a problem of Emmet.

![2016-07-11_18-22-44](https://cloud.githubusercontent.com/assets/7034281/16736150/79c9fa94-4794-11e6-9010-43ad28c79509.gif)

**Comment by egamma** [comment]
@codingonHP you can disable emmet completion on tab using the setting.
```
   "emmet.triggerExpansionOnTab": false
```

Closing as an upstream issue.

**Comment by codingonHP** [comment]
@egamma : thanks. I have disabled emmet and now it works perfectly fine :)

**Comment by ramya-rao-a** [comment]
With the new Emmet improvements in VS Code 1.15, this is no longer a problem

Tab will no longer trigger Emmet, instead Emmet abbreviations will show up in suggestion/auto-completion list.

In this particular case, emmet will not provide any suggestions either

Please read more on what else is new at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
