### ISSUE TITLE
Support Android as a host system for running VSCode

### ISSUE THREAD

**Issue by behrangsa** [microsoft/vscode#90565]
Now that there are smartphones with 12-16GB of RAM that can directly connect to an external monitor and present a desktop-like environment to users, coupled with VS Code's remote development features, if we can run Code on Android, we could potentially only use our phones for software development.

**Comment by JacksonKearl** [comment]
VS Code is based on Electron which likely won’t ever support Android, so it’s unlikely that VS Code the desktop client would. However VSO may in the future: https://visualstudio.microsoft.com/services/visual-studio-online/
