### ISSUE TITLE
Main menu should show all actions

### ISSUE THREAD

**Issue by jkufner** [microsoft/vscode#90560]
Main menu should present all features of a program to user. VSCode shows only a few features in the main menu and most of the functionality is well hidden. A good menu provides discoverability to all features.

What I miss in the main menu, in particular, are refactoring features, everything from context menu (it should be in both places), … I have no ide what VSCode actualy can do and what is still hidden from me.

For example, PHPStorm has a very nice "Code" menu which provides code manipulation features and refactoring.

**Comment by JacksonKearl** [comment]
We list all available commands in the command pallet, you can read more about it here: https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

**Comment by jkufner** [comment]
Well, technically yes. There is list of everything. However, from UX point of view, that list cannot replace menu because the list does not present features — it presents all possible actions. The main difference between the main menu and the command palette is that the menu is structured and curated to be meaningful. Each of these two are designed for different use-cases.

**Comment by JacksonKearl** [comment]
We have too many actions to possibly list them all in the menus in a coherent way. If you think particularly important actions are missing you can file separate reports for those.
