### ISSUE TITLE
Arresti continui

### ISSUE THREAD

**Issue by domenicosf92** [microsoft/vscode#90573]
Il programma si arresta continuamente rendendo impossibile lo sviluppo di qualsiasi applicazione

**Comment by domenicosf92** [comment]
Program have continue crash make develop very difficult

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!

**Comment by domenicosf92** [comment]
At the moment it seems going well. I hope it was a momentary problem
