### ISSUE TITLE
git changes not showing in active editor

### ISSUE THREAD

**Issue by tusharcoder** [microsoft/vscode#90574]
Issue Type: <b>Bug</b>

git changes not showing in active editor after January 2020 update

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 3.10.0-1062.12.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2508)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|15.41GB (1.27GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
vscode-sqlite|ale|0.8.1
vscode-eslint|dba|2.0.15
jquerysnippets|don|0.0.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-mysql|for|0.4.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vue|jcb|0.1.5
recent-files|jun|1.1.10
python|ms-|2020.2.63072
JavaScriptSnippets|xab|1.7.2
local-history|xyz|1.7.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?

Can you show me a screenshot of what you mean by _git changes_?
