### ISSUE TITLE
teminal vim mouse can't use.

### ISSUE THREAD

**Issue by HONEY-SUNMX** [microsoft/vscode#90571]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. connect to ubuntu subsystem in windows 10 using VSCode WSL.
2. can't use mouse to control cursor in vim.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
How are you "connecting"? Are you using the Remote WSL extension? https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

**Comment by HONEY-SUNMX** [comment]
> How are you "connecting"? Are you using the Remote WSL extension? https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

Yes, when i use Remote WLS extension, i can't use mouse to control cursor when i want to edit in vim.

**Comment by Tyriar** [comment]
Did you enable mouse mode in vim?

**Comment by HONEY-SUNMX** [comment]
> Did you enable mouse mode in vim?

Yes, the problem will not present when i use vim in a common terminal rather than the WSL in the vscode.

**Comment by Tyriar** [comment]
Unconfirmed.

**Comment by rzhao271** [comment]
Closing in favour of #96058
