### ISSUE TITLE
Freezes intellisense

### ISSUE THREAD

**Issue by Iosif380** [microsoft/vscode#90575]
Issue Type: <b>Bug</b>

When triggering intellisense vs code, the whole system freezes

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 5.3.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3228)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 9, 5|
|Memory (System)|15.51GB (10.96GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.900.12
vscode-custom-css|be5|3.0.9
bracket-pair-colorizer|Coe|1.0.61
compulim-vscode-closetag|Com|1.2.0
angular-schematics|cyr|3.0.1
vscode-eslint|dba|2.0.15
xml|Dot|2.5.0
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
todo-tree|Gru|0.0.167
Angular2|joh|9.0.1
vscode-sshfs|Kel|1.16.3
Angular-BeastCode|Mik|8.1.2
import-sorter|mik|3.3.1
vscode-language-pack-ru|MS-|1.42.2
powershell|ms-|2020.1.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1587
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|3.9.3
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|1.4.3
simontest|Sim|1.8.1
code-spell-checker|str|1.7.22
code-spell-checker-russian|str|0.2.4
ayu|tea|0.18.0
vscodeintellicode|Vis|1.2.5
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(7 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
