### ISSUE TITLE
Add "Inline variable" refactoring

### ISSUE THREAD

**Issue by DanielSWolf** [microsoft/vscode#90572]
VSCode offers several "Extract to constant" refactorings that move a literal value into a constant. I often need the reverse operation: inlining a value that is currently defined in a constant.

Here are some examples.

```ts
// Before:
function add(a: number, b: number) {
  const result = a + b;
  return result;
}

// After inlining `result`:
function add(a: number, b: number) {
  return a + b;
}
```

```ts
// Before:
const message = 'Processing successful.';
console.log(message);

// After inlining `message`:
console.log('Processing successful.');
```

For reference, here is the [documentation of that feature in ReSharper](https://www.jetbrains.com/help/resharper/Refactorings__Inline_Variable.html).

**Comment by JacksonKearl** [comment]
Please file a request on TypeScript: https://github.com/microsoft/TypeScript/

**Comment by DanielSWolf** [comment]
@JacksonKearl Thank you for your fast reply! I'm a bit confused, though. It is my understanding that [the code for "Extract to constant"](https://github.com/microsoft/vscode/blob/fb622a8b83c3f9fb661f7a86ffb89ccb6a2b0581/extensions/typescript-language-features/src/features/refactor.ts) is part of this repository, not TypeScript. Am I missing something?

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/18459
