### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by mnini** [microsoft/vscode#90576]
Settings that would do following on enabled:

- [x] Allow letter spaced grid on the working window.
- [x] When pushed arrow down, you would be in exact same column on the text as before.
- [x] A really subtle display of grid

Just three check-boxes in settings...

**Comment by JacksonKearl** [comment]
It's not clear to me what you mean by these. Could you explain further, with use cases and why our current grid actions don't work for them?

**Comment by mnini** [comment]
Unispaced font deserve, that when you press arrow down on a end of the line, you end up exact same number of characters from \n

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/74681514-6d4e6100-5178-11ea-943a-47f20faffd12.png)
This is the behavior currently and it is consistent with other editors, how would you specifically like it to be different?

**Comment by mnini** [comment]
get cursor down, visualy...
therefore, when tere is aligning to } , it should end up filling white space and having same horizonatal coordinate on a grid

**Comment by mnini** [comment]
Maybe some special thing in editor, like escape sequence, that would keep e.g. comments behind the line at certain offset would be visually also very nice.
