### ISSUE TITLE
Drag and drop not working on multiple gnome workspace

### ISSUE THREAD

**Issue by ClemsRocket** [microsoft/vscode#90585]
- VSCode Version: 1.42.0
- OS Version: Fedora 29, Gnome 3.30.2

Steps to Reproduce:

1. Open vscode on gnome
2. Right click on top bar and select always on visible workspace
3. Change gnome workspace
4. Try to use any drag and drop feature (move window around, move file, etc.) -> nothing happens

I am not sure if it is a gnome or a vscode issue, it only happens with vscode though (I tried to reproduce on other software such as chromium but couldn't reproduce) 

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Do you see similar behaviour in other Electron or Chromium apps?

**Comment by ClemsRocket** [comment]
No, I tried with chromium and slack, no similar behaviour

**Comment by rebornix** [comment]
@ClemsRocket can you try https://microsoft.github.io/monaco-editor/ in the browser and see if drag and drop content in the editor work?

**Comment by ClemsRocket** [comment]
Drag and drop text works, but it does too in vscode. What I can't drag and drop is windows or files in the tree 
![Issue](https://user-images.githubusercontent.com/22476783/74840854-040d5000-5328-11ea-80aa-997fda296953.gif)

**Comment by ClemsRocket** [comment]
@isidorn Can I have a bit more info about why this has been written as out of scope?

**Comment by isidorn** [comment]
There are already other DnD issues which cover parts of issues like this which you can find in our reposotiry.
Also I do not plan to work on this in the forceable future.
