### ISSUE TITLE
Expand selection in words with underscores is inconsistent

### ISSUE THREAD

**Issue by artem-karpenko** [microsoft/vscode#90589]
Issue Type: <b>Bug</b>

1. Open any file which contains word consisting of letters with underscores (f.e. hello_world). For simplicity let's assume only one underscore is present.
2. Place cursor in various places of this word and activate expand selection command (either via keyboard shortcut or keybinding)
3. Observe:
 3a. cursor is not near underscore (underscore is not immediately to the left or right of cursor) - part of the word selected, bounded by word beginning/end and underscore - OK
 3b. underscore is immediately left to the cursor - part of word to the right of cursor is selected - OK
 3c. underscore is immediately right to the cursor - the whole word is selected - UNEXPECTED.

For 3c I expected only part of the word selected as well, not the whole word.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
quick-open-prefill-selection|col|0.0.1
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-great-icons|emm|2.1.47
intellij-idea-keybindings|k--|0.2.37
camelcasenavigation|map|1.1.1
material-icon-theme|PKi|3.9.3
partial-diff|ryu|1.4.1
terminal-tabs|Tyr|0.2.0

(5 theme extensions excluded)

</details>

**Comment by vhpgomes** [comment]
Tried to fix this in the PR #90736

PS - this is my first PR for a OSS, ever... please forgive me for any mistake or misconduct.
