### ISSUE TITLE
More customizable design toolkit...

### ISSUE THREAD

**Issue by mnini** [microsoft/vscode#90580]
Allow extensions access to DOM element ( which is quite necessary for e.g. custom animations or borders ) of:

- [ ] Every possible element
With access to DOM like that and canvas, there are literally infinite design pattern solutions, that are better than blank screen
- [ ] Workspace background is good, but solving whole browser as background with transparency or fully transparent window with blur and opacity is possible in electron.
Transparency looks good, vibrancy looks even better, but I don't think electron's able to do that on linux...
- [ ] Command to open custom script tab on the workspace
So you can change animation that is there...
- [ ] Command that allows to open custom global script
So you have some default fallback
- [ ] Allow support for transparent window
Transparency is good...
- [ ] Allow support for frameless window( custom frame )
Maybe theming can get too far...
- [ ] Allow themes semantical font and font size 
Maybe...
- [ ] Browser with true live preview on templates
So we can see what is going on...

**Comment by JacksonKearl** [comment]
Many of these items have existing issues tracking them, for instance #32257, 26128, #1833, etc. Please check for existing issues before filing more. Also please don't file issues in batches, we need to be able to assign issues to individual contributors to track the status of individual bugs and feature requests.
