### ISSUE TITLE
Live share doesn't save changes

### ISSUE THREAD

**Issue by bespoyasov** [microsoft/vscode#90582]
When I share code from Visual Studio to VS Code via Live Share, the changes applied to code are not being saved.

To be more precise, they appear to be saved, however code reverts to previous, unchanged version after a second or so. The revert may be connected to Visual Studio window being focused when I switch between editors.

**Comment by JacksonKearl** [comment]
Please file on live share extension: https://github.com/MicrosoftDocs/live-share
