### ISSUE TITLE
Typescript rename refactor doesn't rename `Pick` fields

### ISSUE THREAD

**Issue by Svish** [microsoft/vscode#90587]
Issue Type: <b>Bug</b>

Not sure where to report this, if this is part of VS Code, or a Typescript extension, or what, but, given the following for example:

```ts
interface Foo { a: string, b: string }
type Bar = Pick<Foo, 'a'>;

const formatFoo = ({a, b}: Foo) => `${a} ${b}`;
```

If I rename `a` in `Foo` to e.g. `c`, the function is updated correctly, but the type is not. I.e. the `'a'` should become `'c'`, but it doesn't. 😕

I assume the same thing would apply for other things, like `Omit`.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
vscode-styled-jsx|bla|1.5.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
vscode-faker|dee|1.3.0
githistory|don|0.5.2
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.4.0
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
vscode-text-pastry|jkj|1.2.0
vscode-peacock|joh|3.3.1
vscode-gutter-preview|kis|0.25.0
sftp|lix|1.12.9
vscode-docker|ms-|0.10.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
csharp|ms-|1.21.11
vsliveshare|ms-|1.0.1587
hide-gitignored|npx|1.0.1
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.3
vscode-sort-json|ric|1.18.0
vscode-sanity|san|0.0.2
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.5
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug upstream](https://github.com/microsoft/TypeScript/issues/new/choose) for this

**Comment by Svish** [comment]
I see. Seems in that project it has already been reported and rejected. Oh well... 😕

https://github.com/microsoft/TypeScript/issues/30263
