### ISSUE TITLE
Open file in editor with double click from git panel

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#90583]
In Git tab add the ability to open file in editor with double click.

So: at single click on the file the diff changes appear as it works now at double click on the file **Open File** command is executed.

Reason: 
1. easy of use for most obvious command 
2. the icons on file item are hard to click because of their size

**Comment by joaomoreno** [comment]
Closing as won't implement.

That's exactly what that `File` icon does, when you hover over a change:

![image](https://user-images.githubusercontent.com/22350/74519695-81932380-4f16-11ea-9f6f-ab3aa1bce077.png)
