### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Skirann** [microsoft/vscode#90596]
#Issue Type: <b>Feature Request</b>

turning into captical strings or lower case letters when we grep the text 

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

i have got my answer....sorry for the inconvenience

**Comment by gjsjohnmurray** [comment]
@chrmarti any idea why the bot didn't act on my /question response? If that has been dropped maybe update the wiki at https://github.com/microsoft/vscode/wiki/Community-Issue-Tracking

**Comment by JacksonKearl** [comment]
@gjsjohnmurray the bot has been a bit sleepy lately, I'm doing some work on improving that this iteration. As far as I know `/question` as a keyword was not removed.
