### ISSUE TITLE
When using the C# plug-in development, will often lose the smart tips.

### ISSUE THREAD

**Issue by lvse** [Microsoft/vscode#9059]
- VSCode Version: 1.3.0
- OS Version: win 10

Steps to Reproduce:

1. When using the C# plug-in development, will often lose the smart tips.

**Comment by weinand** [comment]
@lvse since the C# extension is not part of VS Code, please create a new issue in the C# repository: https://github.com/OmniSharp/omnisharp-vscode/issues.
