### ISSUE TITLE
 Cannot read property 'getResource' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#90599]
Issue Id: <b>729aa3f4-c1c8-a165-cab7-c597f972f4cc</b><br /><br />*Versions* <br />- 1.42.0<br />-  705f01577dd37d6f17eaa683ab89b0c392fa1a7c<br />-  be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b<br />-  8d4cdbaa8d64514a5eb3b186b9a31b66cd8a9753<br />*Stack* <br />TypeError: Cannot read property 'getResource' of undefined<br />[/vs/workbench/contrib/debug/browser/debugSession.ts#765:10 (stoppedDetails)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/debug/browser/debugSession.ts#L765:10 (stoppedDetails))<br />[/vs/workbench/contrib/debug/browser/debugSession.ts#598:11 (this)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/debug/browser/debugSession.ts#L598:11 (this))<br />[/vs/base/common/event.ts#567:6](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/common/event.ts#L567:6)<br />[/vs/workbench/services/textfile/common/textFileEditorModel.ts#588:25](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L588:25)<br />[/vs/workbench/services/textfile/common/textFileEditorModel.ts#579:25](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L579:25)<br />[/vs/workbench/services/textfile/common/textFileEditorModel.ts#551:25 (this)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L551:25 (this))<br />[/vs/base/common/event.ts#567:6 (adjustedTabDragBackground)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/common/event.ts#L567:6 (adjustedTabDragBackground))<br />[/vs/workbench/browser/parts/editor/tabsTitleControl.ts#1405:59 (workbenchBackground)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L1405:59 (workbenchBackground))<br />[/vs/workbench/browser/parts/editor/tabsTitleControl.ts#1335:146](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L1335:146)<br />[/vs/workbench/browser/parts/editor/tabsTitleControl.ts#514:21](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L514:21)<br />[/vs/workbench/browser/parts/editor/tabsTitleControl.ts#468:26 (this)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L468:26 (this))<br />[/vs/workbench/browser/parts/activitybar/activitybarPart.ts#511:35 (undefined)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L511:35 (undefined))<br />[/vs/workbench/browser/parts/activitybar/activitybarPart.ts#512:31](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L512:31)<br />

**Comment by isidorn** [comment]
This strack trace is invalid and I can not do anything with it. Thus closing
There is no reference of `getResource` in the `debugSession.ts`
