### ISSUE TITLE
Debugging on macOS

### ISSUE THREAD

**Issue by AkeSamuelson** [microsoft/vscode#90597]
1. Set a few break points in the .ps1 script
2. Start debugging script with F5.
3. While it's processing commands, remove a breakpoint from a line that hasn't been passed.

It now stops on the line with removed breakpoint and I can't get passed that. F keys do not work and debug panel do not work either (only pause, restart and stop are enabled).

**Comment by JacksonKearl** [comment]
Please file on the powershell extension: https://github.com/PowerShell/vscode-powershell
