### ISSUE TITLE
Web: the setting 'remote.extensionKind' is not available in the Web

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#90598]
The screenshot below is from VSO, as you can see the setting `remote.extensionKind` is not known in the web version. The setting should also be available in the web version so that a user can configure the extensionKind for an extension, for example, to change a 'ui' extension into a 'workspace' extension.

![image](https://user-images.githubusercontent.com/172399/74444242-de3e0200-4e74-11ea-93e3-8de6f50829fa.png)

**Comment by rebornix** [comment]
Verified in web self host.
