### ISSUE TITLE
Live Share code does not sync

### ISSUE THREAD

**Issue by alexandertrefz** [microsoft/vscode#90592]
Issue Type: <b>Bug</b>

When I start a liveshare session with a coworker we both can see our cursors moving, and can both type, but the changes are not transmitted to the other participant.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

**Comment by JacksonKearl** [comment]
Please file on the live share extension: https://github.com/MicrosoftDocs/live-share
