### ISSUE TITLE
Tab Indention Spaces Setting Doesn't Stick

### ISSUE THREAD

**Issue by TheOneDaveYoung** [microsoft/vscode#90591]
Issue Type: <b>Bug</b>

Weird one here. In the status bar (bottom) where the indentation spaces is shown. You can click `spaces` and it will display the actions menu filtered with choices for setting tab spacing. All good so far.
![image](https://user-images.githubusercontent.com/33292917/74434544-802f0180-4e17-11ea-8543-c5c3b79c6058.png)

If I click the `change view` link in the actions menu I'm presented with options for tab spaces 1-8 with the currently configured size (in settings) indicated.
![image](https://user-images.githubusercontent.com/33292917/74434587-93da6800-4e17-11ea-8364-bfca5138d21b.png)

My current setting is at 2 spaces. However, in the status bar for whatever reason, it indicates 4 spaces. So, I click the status bar, click `change view`, then select 2 from the menu. So far so good.
![image](https://user-images.githubusercontent.com/33292917/74434660-b2d8fa00-4e17-11ea-9016-e4cfb3a885e6.png)

What is weird though is that if I switch to a different program (take focus away from VS Code) then return the tab space setting automatically resets back to 4! 

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-goto-view|cod|1.3.2
bracket-pair-colorizer-2|Coe|0.0.29
vue-peek|dar|1.0.2
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
githd|hui|2.2.1
php-cs-fixer|jun|0.1.129
dotenv|mik|1.0.1
vuejs-extension-pack|mub|1.1.5
php-docblocker|nei|2.1.0
vetur|oct|0.23.0
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
vscode-phpcbf|per|0.0.8
material-icon-theme|PKi|3.9.3
vscode-essentials-snippets|rob|2.0.0
sass-indented|rob|1.5.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.8.0
code-spell-checker|str|1.7.22
lorem-ipsum|Tyr|1.2.0
vscode-phpsab|val|0.0.4
php-docblock-generator|vin|0.0.1
vsc-php-snippets|vsc|0.0.30
JavaScriptSnippets|xab|1.7.2
local-history|xyz|1.7.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
Maybe set `"editor.detectIndentation": false` so that when you first open this file the status bar will show your configured settings (Spaces 2) rather than deriving settings from the existing content.

**Comment by JacksonKearl** [comment]
Not able to reproduce. Could you provide an example file where you see this, along with your settings for `editor.tabSide` and  `editor.detectIndentation`?

**Comment by TheOneDaveYoung** [comment]
Thanks for the super-fast response guys!!!

My config vals are: `"editor.tabSize: 2"`, `"editor.detectIndentation": true`

It's happening with all files. For example, the Vue file below is indented at 2 spaces but the detected spaces are 4. It's like the detection is happening every time focus comes to the editor but it's confused.

![image](https://user-images.githubusercontent.com/33292917/74473340-4d592d80-4e58-11ea-9852-22225366e588.png)

Interestingly I can't recreate this either on another machine, so I'm guessing there's some combination of extensions/settings on this one machine that's causing this. Probably not worth going down the rabbit hole to figure it out (nobody else is raising their hands about this).

Anyway, here's a sample file where this is happening. I'll try setting detect to false and report back.

```
<template>
  <div class="min-w-32 min-h-48 font-medium card">
    <div class="w-32 flex-none rounded-t lg:rounded-t-none lg:rounded-l text-center">
      <div class="block rounded-t overflow-hidden text-center">
        <div class="bg-primary text-white p-3">
          {{ parsedDay.month }}
        </div>

        <div class="flex items-center justify-between">
          <button class="btn btn-white self-stretch p-3 rounded-b-lg" type="button" @click="move(-1)">
            <icon type="play" class="rotate-180" />
          </button>
          <div class="flex-1">
            <div class="pt-1 border-l border-r border-white bg-white">
              <span class="text-3xl font-bold leading-tight p-3">
                {{ parsedDay.day }}
              </span>
            </div>
            <div class="border-l border-r border-b rounded-b-lg text-center border-white bg-white">
              <div class="text-sm pb-3 px-3">
                {{ parsedDay.weekday }}
              </div>
            </div>
          </div>
          <button class="btn btn-white self-stretch p-3 rounded-b-lg" type="button" @click="move(1)">
            <icon type="play" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Day',

  props: {
    day: [String, Object],
  },

  computed: {
    parsedDay() {
      const d = moment(this.day)
      return {
        month: d.format('MMMM'),
        day: d.format('Do'),
        weekday: d.format('dddd'),
      }
    }
  },

  methods: {
    move(num) {
      const d = moment(this.day).add(num, 'd')
      this.$emit('date', d.format('YYYY-MM-DD'))
    }
  }
}
</script>
```

**Comment by TheOneDaveYoung** [comment]
Okay, so setting `"editor.detectIndentation": false` has resolved the issue. I tried testing in reverse, setting tabs to 4 spaces, switching to another app, then switching back and the setting stayed at 4 spaces.

So, some extension may be interfering with the tab space detection algo in my env. 🤷‍♂ 

Thanks for the help guys!
