### ISSUE TITLE
 TreeError [VariablesView] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#90605]
Issue Id: <b>efbdcad3-dfe5-7f15-d8a4-98924fd9728c</b><br /><br />*Versions* <br />- 1.42.0<br />-  705f01577dd37d6f17eaa683ab89b0c392fa1a7c<br />-  be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b<br />-  536757fcc0308b444cbe9ce04f1f013903641ae3<br />*Stack* <br />Error: TreeError [VariablesView] Tree element not found: [object Object]<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#270:24 (getElementLocation)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/objectTreeModel.ts#L270:24 (getElementLocation))<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#213:24 (length)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/objectTreeModel.ts#L213:24 (length))<br />[/vs/base/browser/ui/tree/abstractTree.ts#707:100 (focus)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/abstractTree.ts#L707:100 (focus))<br />[/vs/base/browser/ui/tree/dataTree.ts#203:11 (setChildren)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/dataTree.ts#L203:11 (setChildren))<br />[/vs/base/browser/ui/tree/dataTree.ts#158:13 (this)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/dataTree.ts#L158:13 (this))<br />[/vs/base/browser/ui/tree/dataTree.ts#114:30 (indexOf)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/dataTree.ts#L114:30 (indexOf))<br />[/vs/base/browser/ui/tree/dataTree.ts#73:23 ([object Object])](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/dataTree.ts#L73:23 ([object Object]))<br />[/vs/base/browser/ui/tree/abstractTree.ts#1563:1 (view)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/abstractTree.ts#L1563:1 (view))<br />[/vs/base/browser/ui/tree/abstractTree.ts#1544:7 (removeBreakpoints)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/abstractTree.ts#L1544:7 (removeBreakpoints))<br />[/vs/workbench/contrib/debug/browser/debugService.ts#928:14](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/debug/browser/debugService.ts#L928:14)<br />

**Comment by joaomoreno** [comment]
@JacksonKearl This is **VariablesTree**.

**Comment by isidorn** [comment]
This stack trace is not complete. And I can not do anything about it.
@bpasero I think you created this issues, is there a way to get a more complete stack trace?

**Comment by bpasero** [comment]
I don't know, I used our error reporting app to create the issue, maybe ask @sbatten

**Comment by isidorn** [comment]
@sbatten let me know if we can get a more complete stack trace. Since the current one looks very wrong to me. And definetely not complete

**Comment by sbatten** [comment]
```
Error: TreeError [VariablesView] Tree element not found: [object Object]
at t.ObjectTreeModel.getElementLocation (out/vs/workbench/workbench.desktop.main.js:135:14)
at t.ObjectTreeModel.isCollapsed (out/vs/workbench/workbench.desktop.main.js:134:122)
at r.isCollapsed (out/vs/workbench/workbench.desktop.main.js:1070:430)
at q.setChildren (out/vs/workbench/workbench.desktop.main.js:1090:576)
at q.doRefreshNode (out/vs/workbench/workbench.desktop.main.js:1089:763)
at async q.doRefreshSubTree (out/vs/workbench/workbench.desktop.main.js:1089:342)
at async q.refreshAndRenderNode (out/vs/workbench/workbench.desktop.main.js:1088:874)
at async q._updateChildren (out/vs/workbench/workbench.desktop.main.js:1086:82)
at async q.updateChildren (out/vs/workbench/workbench.desktop.main.js:1085:787)
at async g.runner (out/vs/workbench/workbench.desktop.main.js:5528:870)
```

This is the original stack trace that came with the error.

**Comment by isidorn** [comment]
That stack trace is minified. The only thing I see is that I am calling `updateChildren` from the variables tree and that the tree throws that the element is not found. Which should not happen.
@joaomoreno is there something I am missing here?

**Comment by sbatten** [comment]
@isidorn yea the deminified stacks seem weird. and I asked @alexdima for his tool to help deminify it and it also gets weird results so that's still under investigation
