### ISSUE TITLE
 TreeError [SearchView] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#90601]
Issue Id: <b>798c3081-2ea4-6672-ce56-a8afb1c71cbd</b><br /><br />*Versions* <br />- 1.42.0<br />-  705f01577dd37d6f17eaa683ab89b0c392fa1a7c<br />-  be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b<br />*Stack* <br />Error: TreeError [SearchView] Tree element not found: [object Object]<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#270:24 (element)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/objectTreeModel.ts#L270:24 (element))<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#55:49](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/objectTreeModel.ts#L55:49)<br />[/vs/base/browser/ui/tree/abstractTree.ts#1072:7 (SyncActionDescriptor)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/abstractTree.ts#L1072:7 (SyncActionDescriptor))<br />[/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#224:33](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#L224:33)<br />    at Array.forEach (<anonymous>)<br />[/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#224:33 (OpenRawDefaultSettingsAction)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#L224:33 (OpenRawDefaultSettingsAction))<br />[/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#219:124 (instantiationService)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#L219:124 (instantiationService))<br />[/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#180:13](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#L180:13)<br />[/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#440:73 (this)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L440:73 (this))<br />[/vs/base/common/event.ts#567:6 (onEnablementChanged)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/common/event.ts#L567:6 (onEnablementChanged))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#106:50 (this)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L106:50 (this))<br />[/vs/base/common/event.ts#567:6 (Promise)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/common/event.ts#L567:6 (Promise))<br />[/vs/workbench/contrib/remote/common/showCandidate.ts#19:37](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/remote/common/showCandidate.ts#L19:37)<br />    at out/vs/workbench/w<br />

**Comment by joaomoreno** [comment]
@JacksonKearl This is **SearchTree**.

**Comment by JacksonKearl** [comment]
@joaomoreno I see, sorry I wasn't sure what to do with the `vscodeerrors` reports.

**Comment by joaomoreno** [comment]
@JacksonKearl No worries. ;)
