### ISSUE TITLE
 TreeError [SettingsTree] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#90600]
Issue Id: <b>a5d39d35-f2ec-cebb-30f8-bf7b129c1200</b><br /><br />*Versions* <br />- 1.42.0<br />-  be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b<br />-  705f01577dd37d6f17eaa683ab89b0c392fa1a7c<br />*Stack* <br />Error: TreeError [SettingsTree] Tree element not found: [object Object]<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#270:24 (this)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/objectTreeModel.ts#L270:24 (this))<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#194:19](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/objectTreeModel.ts#L194:19)<br />[/vs/base/browser/ui/tree/abstractTree.ts#771:25](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/base/browser/ui/tree/abstractTree.ts#L771:25)<br />[/vs/workbench/contrib/preferences/browser/settingsTree.ts#1512:22 (fgWithOpacity)](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L1512:22 (fgWithOpacity))<br />[/vs/workbench/contrib/preferences/browser/settingsTree.ts#1520:144](https://github.com/microsoft/vscode/blob/ae08d5460b5a45169385ff3fd44208f431992451/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L1520:144)<br />

**Comment by joaomoreno** [comment]
@JacksonKearl This is **SettingsTree**.

**Comment by roblourens** [comment]
Stale and I don't know why the stack is pointing at theming code
