### ISSUE TITLE
[scss] syntax highlighting breaks after nested braces

### ISSUE THREAD

**Issue by lediur** [Microsoft/vscode#9060]
- VSCode Version: 1.4.0-insider f6227ca
- OS Version: Windows 10 Pro Insider 14385

Steps to Reproduce:

1. Create a SCSS file. Note that syntax highlighting works.

![image](https://cloud.githubusercontent.com/assets/1077648/16724906/d136291e-4709-11e6-9d0e-6d51b92a0bb7.png)

2. Add any level of nested braces within. Note that syntax highlighting works inside the nested braces:

![image](https://cloud.githubusercontent.com/assets/1077648/16724891/b5fd051e-4709-11e6-9cb3-4e94b708a1a6.png)
![image](https://cloud.githubusercontent.com/assets/1077648/16724936/f039c8f2-4709-11e6-82e1-81c3cfb7fa9f.png)

3. Add more code after the nested braces. Syntax highlighting is now broken for code after the braces.

![image](https://cloud.githubusercontent.com/assets/1077648/16724898/c2049e12-4709-11e6-8e63-aa08fb3c77c4.png)
![image](https://cloud.githubusercontent.com/assets/1077648/16724959/01999618-470a-11e6-830c-49e3f2cdadab.png)

**Comment by aeschli** [comment]
Fixed by 3558e7e862f8d67368e17e2d93dcbb7925a7c6e2
