### ISSUE TITLE
Backspaces do not work in Pseudoterminal

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#90618]
I don't know if I'm supposed to be handling this (I can't find an obvious way to do it).

Take the sample code from https://code.visualstudio.com/api/references/vscode-api#Pseudoterminal:

```ts
const writeEmitter = new vscode.EventEmitter<string>();
const pty: vscode.Pseudoterminal = {
  onDidWrite: writeEmitter.event,
  open: () => {},
  close: () => {},
  handleInput: data => writeEmitter.fire(data === '\r' ? '\r\n' : data)
};
vscode.window.createTerminal({ name: 'Local echo', pty });
```

Run this code and type into the `Local echo` terminal, and hit `<backspace>` - nothing happens.

@Tyriar

**Comment by Tyriar** [comment]
Backspace should fire `0x7F` (DEL, ^?), if you simply print this it won't do anything, you need to say how to handle it explicitly. You can see what keys fire by enabling escape sequence logging via command palette and checking devtools console for what gets printed.

**Comment by DanTup** [comment]
@Tyriar is there a way I can find all of the things that won't work and need special handling? It'd be nice to document this against Pseudoterminal (like `\r\n`) since presumably everybody using this class is going to need to handle this themselves?

**Comment by DanTup** [comment]
@Tyriar I tried catching this and sending `\b`:

```ts
handleInput: (data) => {
	switch (data) {
		case "\r":
			data = "\r\n";
		case String.fromCharCode(127):
			data = "\b";
	}
	writeEmitter.fire(data);
},
```

However that moves the cursor back without erasing what's been printed. I'm not sure how I can handle that?

**Comment by Tyriar** [comment]
@DanTup yes this is by design, you would need to clear the cell a well. Things get even more complicated when you want to wrap lines. Essentially your extension needs to keep a model of the viewport around so it can re-write the line when needed. The various sequences available to manipulate the terminal are documented in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html

**Comment by DanTup** [comment]
Oh, I see - I mistakenly thought that would've been handled. I'll revert this and get it working through a real terminal - using this seemed like a short-cut, but this looks like it'll end up much more complicated than getting the debugger connected with a real terminal-based execution. Thanks for the info!
