### ISSUE TITLE
Follow link on hovers isn't a link when you hover immediately after writing the text

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90614]
Repro:

1. Install GHPR
2. Type `// #90101` and hover the link quickly

<img width="304" alt="Screen Shot 2020-02-13 at 8 13 10 AM" src="https://user-images.githubusercontent.com/2193314/74454501-d8c2c680-4e38-11ea-82a5-15f95132fba7.png">

**Comment by rebornix** [comment]
I saw that once in the UX meeting.

**Comment by rebornix** [comment]
Will look into this issue in debt week of April.

**Comment by rebornix** [comment]
GH PR seems no longer using link provider now.

**Comment by Tyriar** [comment]
@rebornix this is still a bug with the document link provider API though right?
