### ISSUE TITLE
Make preview text in unsaved tab labels accessible via go to anything 

### ISSUE THREAD

**Issue by mmcintyre123** [microsoft/vscode#90613]
**_Please see below for requested version numbers and environment info._**

The new [feature](https://github.com/microsoft/vscode/issues/37414) whereby the first line of unsaved files is displayed as preview text in the tab title is very useful - it would be even more useful if the preview text were accessible to "go to anything". So in the GIF below, the files would be found by typing any part of the preview text - just like go to anything for saved files.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12388285/74070273-a21b2500-49ce-11ea-93cc-369892d4cbd8.gif)

### Requested info
VSCODE:
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

My OS: Windows 10

Installed Extensions:
74th.monokai-charcoal-high-contrast
aaron-bond.better-comments
acarreiro.calculate
akamud.vscode-javascript-snippet-pack
albymor.increment-selection
alefragnani.Bookmarks
andrejunges.Handlebars
AndreyVolosovich.monokai-st3
bibhasdn.unique-lines
brainfit.split-lines
buianhthang.xml2json
chris-noring.ts-snippets
christian-kohler.npm-intellisense    
christian-kohler.path-intellisense   
ckolkman.vscode-postgres
Cmacu.gotoanything
CoenraadS.column-jump
cstrap.flask-snippets
dakara.dakara-foldplus
dakara.transformer
dbaeumer.vscode-eslint
dbankier.vscode-quick-select
donjayamanne.jquerysnippets
DotJoshJohnson.xml
ecmel.vscode-html-css
eg2.vscode-npm-script
esbenp.prettier-vscode
foxundermoon.shell-format
gerane.Theme-Dark-Dracula
hoovercj.vscode-settings-cycler
huizhou.githd
jasonnutter.search-node-modules
jeremyljackson.vs-docblock
jianbingfang.dupchecker
johnpapa.vscode-peacock
karigari.chat
konstantin.wrapSelection
letrieu.expand-region
michelemelluso.code-beautifier
Mikael.Angular-BeastCode
mishkinf.vscode-edits-history
mksafi.find-jump
mohd-akram.vscode-html-format
ms-python.python
ms-vscode-remote.remote-wsl
ms-vscode.sublime-keybindings
ms-vscode.vscode-typescript-tslint-plugin
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
ms-vsliveshare.vsliveshare-pack
msjsdiag.debugger-for-chrome
mtxr.sqltools
nemesv.copy-file-name
nikitaKunevich.snippet-creator
oliversturm.fix-json
redhat.java
Rubymaniac.vscode-paste-and-indent
ryu1kn.text-marker
ryuta46.multi-command
sadeghpm.sql-snippets
sallar.json-to-js-object
sashaweiss.block-travel
sensourceinc.vscode-sql-beautify
shardulm94.trailing-spaces
sleistner.vscode-fileutils
spoonscen.es6-mocha-snippets
techer.open-in-browser
Tino.simple-rest-client
TzachOvadia.todo-list
usernamehw.change-language-mode
vilicvane.es-quotes
waderyan.nodejs-extension-pack
wcwhitehead.bootstrap-3-snippets
wmaurer.change-case
wmontalvo.vsc-meta-snippet
wwm.better-align
xabikos.JavaScriptSnippets
Zignd.html-css-class-completion

**Comment by mmcintyre123** [comment]
@bpasero 🙂

**Comment by bpasero** [comment]
@mmcintyre123 hm, are you maybe having the editor history disabled in settings? the match should show up from there:

![image](https://user-images.githubusercontent.com/900690/74453374-9de58080-4e82-11ea-8d3a-b999290ca352.png)

**Comment by mmcintyre123** [comment]
@bpasero indeed that was it! `search.quickOpen.includeHistory` must be true.
I forget why I disabled it, I'll probably remember in a few days and come back with a new idea.
But in any case that fixed this issue - thanks!
