### ISSUE TITLE
Update to V1.42:Unable to open file: Invalid arguments error

### ISSUE THREAD

**Issue by AgisilaosVasileiadis** [microsoft/vscode#90612]
Following up on a closed issue [#90524 ](https://github.com/microsoft/vscode/issues/90524) for an error while debugging a Cobol File: **"Unable to open 'filename.cbl': Invalid arguments."**. 
The following sequence of messages exchanged between ide and adapter worked fine in the **previous version**:

``` 
ide  <- adapter: {"type":"event","seq":8,"event":"stopped","body":{"reason":"exception","description":"ABEND","threadId":356,"allThreadsStopped":false}}
ide  -> adapter: {"seq":6,"type":"request","command":"threads","arguments":{}}
ide  <- adapter: {"type":"response","seq":9,"request_seq":6,"command":"threads","success":true,"body":{"threads":[{"id":356,"name":"Task: 356"}]}}
ide  -> adapter: {"seq":7,"type":"request","command":"stackTrace","arguments":{"startFrame":0,"levels":20,"threadId":356}}
ide  <- adapter: {"type":"response","seq":10,"request_seq":7,"command":"stackTrace","success":true,"body":{"stackFrames":[{"id":356,"name":"FILENAME","source":{"name":"filename.cbl","path":"/Users/amagex/workspace-dap-tast/.extsrcs/filename.cbl"},"line":357}],"totalFrames":1}}
ide  -> adapter: {"seq":8,"type":"request","command":"scopes","arguments":{"frameId":356}}
ide  <- adapter: {"type":"response","seq":11,"request_seq":8,"command":"scopes","success":true,"body":{"scopes":[{"name":"Locals","variablesReference":1,"expensive":true,"source":{"name":"filename.cbl","path":"/Users/amagex/workspace-dap-tast/.extsrcs/filename.cbl"}}]}}
```

Both path and filename look fine, and without any invalid arguments, in above messages. 

While experimenting, I tried to provide a non-existent filepath, so VSCode asked me to create a new file as the one I provided did not exist.  Even when I created it and tried to use that one, I got the same error after _Resuming_ or _Stepping Over_: **"Unable to open 'filename.cbl': Invalid arguments."**

Do you require any extra information on this issue or do I do something wrong?

- VSCode Version: 1.42
- OS Version: Windows 10

Steps to Reproduce:

1. Start a debug session.
2. Try to resume or step over.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ishche** [comment]
Are there any updates on this issue?

**Comment by weinand** [comment]
@ishche I don't know where the "Unable to open 'filename.cbl': Invalid arguments." comes from.

I tried to make the error occur in VS Code by returning a non existing file from the debug adapter in Mock Debug with this code (in `mockDebug.ts`):
```ts
private createSource(filePath: string): Source {
  const fp = filePath.replace('readme.md', 'readme2.md');
  return new Source(basename(fp), this.convertDebuggerPathToClient(fp), undefined, undefined, 'mock-adapter-data');
}
```

When running that code and stepping through a markdown file I was seeing this error notification popping up in VS Code:

![2020-03-05_17-23-14](https://user-images.githubusercontent.com/1898161/76002327-ba675c80-5f06-11ea-8e5b-24d17ec746c6.png)

I did not see the "Invalid arguments error" message.

Do you see your error even if you disable all extension?

**Comment by ishche** [comment]
> The path in your DAP trace from above is `/Users/amagex/workspace-dap-tast/.extsrcs/filename.cbl`. This is not a Windows path but you are filing the issue on Windows?
> Can you explain the discrepancy?

Yes, sorry, DAP log is from my computer. I also can reproduce it on Mac.

![image](https://user-images.githubusercontent.com/590426/76069360-0eb81e00-5f93-11ea-9b6a-01a2131909e0.png)

If a file is missing then create file notification appears. But if a file exists then we have this error.

**Comment by weinand** [comment]
The "create file notification appears" is produced by VS Code. But the "Invalid arguments" is not. 
I suspect this comes from a Cobol extension that tries to do something with a "*.cbl" file.
Could you disable all extension but enable the Cobol debugger?

**Comment by ishche** [comment]
I have the same error with only COBOL debug extension.
Can you give a hint, which vscode API part could be the reason for "Invalid arguments"?

![image](https://user-images.githubusercontent.com/590426/76071207-2ba22080-5f96-11ea-95b2-79208bbdeb6b.png)

**Comment by weinand** [comment]
Most "invalid arguments" are thrown in the [codeEditorWidget](  https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/widget/codeEditorWidget.ts).
Could it be that a source location or range returned from the debug adapter is "out of range"?

**Comment by ishche** [comment]
> Most "invalid arguments" are thrown in the [codeEditorWidget](https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/widget/codeEditorWidget.ts).
> Could it be that a source location or range returned from the debug adapter is "out of range"?

I dive deeper and find the source of error:
here: https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/widget/codeEditorWidget.ts#L652
something value is: Object {startLineNumber: 357, startColumn: undefined, endLineNumber: 357, endColumn: undefined}

I found relative changes here: https://github.com/microsoft/vscode/commit/b84d08be70d1efe55d6097d3badcc03297a27635#diff-d6d4527bd487a54f95c554d21f5e05ebL1087

Should I put startColumn and endColumn in our extension? It's not clear from DAP specifications.

**Comment by weinand** [comment]
The DAP clearly states whether an attribute is mandatory or optional.
Where do you think is the DAP spec not clear?

**Comment by ishche** [comment]
> The DAP clearly states whether an attribute is mandatory or optional.
> Where do you think is the DAP spec not clear?

Yep, I misread column mandatory.
https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame

**Comment by weinand** [comment]
@ishche So does the problem go away if you provide a column in the StackFrame object?

@isidorn our debugger frontend could be more forgiving when the `column` attribute is missing. Letting an "Invalid arguments" error from a lower layer ripple up is not very helpful...

**Comment by ishche** [comment]
> @ishche So does the problem go away if you provide a column in the StackFrame object?

It works now. Thank you for help!
I have one question - just curiosity. Why column number is not optional?

**Comment by weinand** [comment]
@ishche for historical reasons...
