### ISSUE TITLE
TypeScript/JavaScript language features failed

### ISSUE THREAD

**Issue by justisGipson** [microsoft/vscode#90628]
Issue Type: <b>Bug</b>

Extension constantly fails after latest VSC update

Error: The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

Extension version: 1.2.5
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by justisGipson** [comment]
@mjbvz Please let me know if you need anymore info regarding this.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

If it does, please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the **first time** the path to the semantic error log file is printed. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs from the crashed instance .

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by justisGipson** [comment]
I will work on getting you this info today so we can hopefully get this resolved.

**Comment by justisGipson** [comment]
@mjbvz I cannot reproduce this issue in the vscode insiders build... I have tried disabling all extensions, and this one keeps failing for me.
