### ISSUE TITLE
TypeScript language service died 

### ISSUE THREAD

**Issue by prma85** [microsoft/vscode#90627]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by prma85** [comment]
**System Information**
```
CPUs | Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 11, 9, 12
Memory (System) | 16.00GB (0.04GB free)
Process Argv | /Users/paulo/
Screen Reader | no
VM | 0%


```

**Comment by prma85** [comment]
**Enabled Extensions***
<img width="605" alt="Screen Shot 2020-02-13 at 1 12 41 PM" src="https://user-images.githubusercontent.com/1236101/74469597-9615e400-4e62-11ea-91c4-3216615962de.png">

**Comment by prma85** [comment]
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

Source: TypeScript and JavaScript Language Features (vscode.typescript-language-features built-in)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by prma85** [comment]
Hi @mjbvz I disabled all extension and I still got the same issue.
This happens from time to time, not always.
Closing and opening the VS Code solves the problem temporarily, but after some time, it will happen again.
MacOS Catalina.

**Comment by mjbvz** [comment]
Did you also try using the insiders build?

If you still see the crash in that, please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by TomLuna** [comment]
There are no tserver.log file under the folder, the err messages just pop up very quickly and never stop until you close the ts file. My vscode version is 1.42.1 and tsc version is 3.7.5

**Comment by christianbradley** [comment]
I am also having this issue - started today with Typescript 3.7.5

**Comment by maksad** [comment]
I fixed the issue by disabling and enabling `TypeScript and JavaScript Language Features` extension:

This extension is built-in, so once `vscode` shows `TypeScript language service died` error you can click on the `Manage extension`. 

![Screenshot 2020-02-19 at 14 23 34](https://user-images.githubusercontent.com/4527650/74834139-834c5500-5323-11ea-901b-404437bdfe28.png)

This will open the extension preview where you can disable it:

![Screenshot 2020-02-19 at 14 04 01](https://user-images.githubusercontent.com/4527650/74832971-32d3f800-5321-11ea-8c6b-efca1310c1a9.png)

Reload VS code and go to the `extensions` -> disabled and `TypeScript and JavaScript Language Features` extension.

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this.

The insiders build includes a new TS version that addresses many possible causes of crashes such as this. If you see this again in the insiders build, please open another issue with the logs so we can investigate
