### ISSUE TITLE
git.openFile vs. git.openFile2?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#90621]
Not clear what the difference is between these. 

![image](https://user-images.githubusercontent.com/8586769/74465322-07956880-4e4a-11ea-9f39-32bbe3574e5b.png)

**Comment by joaomoreno** [comment]
Just some internal differences which I could not resolve in a single command, and there is no way to hide one of them from the keyboard shortcuts view. If you want to assign a keybinding, I would go for `git.openFile`.
