### ISSUE TITLE
Add support for package.json engines key

### ISSUE THREAD

**Issue by custompro12** [microsoft/vscode#90622]
Feature request:
Terminals (used in tasks and the interactive Terminal tab in the Panel) should try to load/use the version of node/npm specified in the packages.json ["engines" key](https://docs.npmjs.com/files/package.json#engines)

Possibly utilizing `nvm` if it is installed/available on the system is the most straightforward approach.

**Comment by Tyriar** [comment]
The terminal doesn't know anything about node, what you're after would be best to happen as part of an extension to your shell or changing your start up scripts.
