### ISSUE TITLE
Cannot start live share session

### ISSUE THREAD

**Issue by Jacob-Bordelon** [microsoft/vscode#90629]
I tried to start a live share session and this error popped up

_An update or installation of VS Live Share failed due to a corrupted download. Please uninstall and reinstall the extension to resolve. See https://aka.ms/vsls-corrupted-install for more details._

I uninstalled and reinstalled as told and it didn't change anything.
Please help.

**Comment by JacksonKearl** [comment]
Please file on the live share extension: https://github.com/MicrosoftDocs/live-share
