### ISSUE TITLE
Explorer tree filtering is useless if it does not search in collapsed folders!

### ISSUE THREAD

**Issue by frevds** [microsoft/vscode#90625]
Filtering the tree could be a wonderful feature, if it was actually looking into folders that are not open. 

People use the filtering function mainly because they have too many files in it, naturally in deep folder structures. Right now there is no point to using this feature, as it does not do what it needs to do. 

Also, I find it cumbersome to having to focus the tree before I can filter it, inasfar as I must click on some free space (to avoid switching the editor file). Also I can never be sure whether the focus is in the tree and the next keypress will filter, as opposed to type into the editor. This needs improvement, imho.

**Comment by JacksonKearl** [comment]
> I find it cumbersome to having to focus the tree before I can filter it

You can use `Explorer: Focus on Folders view` to focus the explorer. This can be tied to a keybinding if you'd like. 

cc @joaomoreno for filtering non-visible files.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/66971
