### ISSUE TITLE
Multiple search in a same document

### ISSUE THREAD

**Issue by josexlito** [microsoft/vscode#90633]
Sometimes, i must to find serveral strings in a document at same time.

I have a trick to do this, but it only allow to do with 2 strings and its bit shabby:

![imagen](https://user-images.githubusercontent.com/16820141/74437197-083cf780-4e68-11ea-9d03-3dd490767bbb.png)

I don't know if is possible to do now in VSCode, but I might be very useful can do several string search at same time. 

At this moment, i can see an issue closed talkin' about this #45585, #16488, but the solution provided is not the same. I've tested it in VSCode Insiders versions and this ( #88154 ) is not the feature that I saying.

**Comment by JacksonKearl** [comment]
You can use regex for this, in this case: `\$other_output|print`. Unfortunately supporting many find widgets is not likely to happen any time soon.
