### ISSUE TITLE
Terminal prompt is never available

### ISSUE THREAD

**Issue by migfig** [microsoft/vscode#90639]
Issue Type: <b>Bug</b>

When i  open a new terminal or add a new terminal/split terminal, the terminal window is displayed, but the prompt for typing commands is never available (being displayed)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-76-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.37GB (10.36GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
Bookmarks|ale|10.7.0
vscode-sqlite|ale|0.8.1
flutter-snippets|ale|2.0.0
vscode-apollo|apo|1.14.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-eslint|dba|2.0.15
bazel-code|Dev|0.1.9
vscode-nomnoml|doc|0.3.0
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
gitlens|eam|10.2.1
tslint|eg2|1.0.44
reasonml|fre|1.0.38
gc-excelviewer|Gra|2.1.32
language-cython|guy|0.0.6
beautify|Hoo|1.5.0
ibm-blockchain-platform|IBM|1.0.19
yuml|Jai|3.5.1
plantuml|jeb|2.13.6
Angular2|joh|9.0.1
solidity|Jua|0.0.70
vscode-map-preview|jum|0.5.1
restructuredtext|lex|117.0.0
Kotlin|mat|1.7.1
Angular-BeastCode|Mik|8.1.2
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.0.9
python|ms-|2020.2.63072
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
Go|ms-|0.13.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.0
vetur|oct|0.23.0
javascript-test-runner|osh|1.2.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.15.0
vscode-manifest-yaml|Piv|1.15.0
vscode-spring-boot|Piv|1.15.0
material-icon-theme|PKi|3.9.3
vscode-protolint|ple|0.2.0
vscode-graphql|Pri|0.2.2
quicktype|qui|12.0.46
java|red|0.55.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.7.2
rust|rus|0.7.0
scala|sca|0.3.9
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6
markdown-all-in-one|yzh|2.7.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by ivanmartinezmorales** [comment]
I am having a similar issue. When trying to open a new terminal, it fails and closes the terminal drawer.

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by migfig** [comment]
After reading your wiki page, i was able to see why it is failing:

> TRACE CommandService#executeCommand workbench.action.terminal.toggleTerminal
> log.ts:173 TRACE terminalInstance#ctor (id: 1) {}
> log.ts:197   ERR A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'

Seem my user does not have the necessary permissions to access the `/proc/PID/environ` file.
I launched vs code with root and terminal works properly:

`sudo code . --user-data-dir`

Hope this helps a bit.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.
