### ISSUE TITLE
vscode-json-languageserver 1.2.2 from npmjs is incompatible with vscode-langaugeserver lib

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode#90634]
I'm using vscode-json-languageserver 1.2.2. from npmjs is custom packaging. Previous versions used to work fine.
Recently (~3 weeks ago), I updated from 1.2.1 to 1.2.2 and I get a failure because `configuration` is null in `TextDocuments` from the vscode-languageserver module. I checked the code and it seems that the code in the vscode-json-languageserver 1.2.2 module actually relies on an incompatible TextDocuments constructor. NPM resolves to an incompatible version of the vscode-languageserver (can't say if it's too old or too recent) that expects a `configuration` to be passed when instantiating a new `TextDocuments`, while vscode-json-languageserver ignores this constructor.

Looking into https://github.com/microsoft/vscode/blame/master/extensions/json-language-features/server/package.json , it seems like the depedency constraint could be fixed. So I guess the solution would be to publish a vscode-json-languageserver 1.2.3 to npmjs.

**Comment by aeschli** [comment]
What caused the breakage is that we had `^vscode-json-languageserver@6.0.0-next.1` as dependency and 6.0.0-next.2 was not backward compatible. We should never use ^ with next dependencies.
But nevertheless, I published a new version vscode-json-languageserver@1.2.3

**Comment by aeschli** [comment]
To verify: 
Check that vscode-json-languageserver@1.2.3 got published
