### ISSUE TITLE
Please change the default behavior of shift-insert back to paste

### ISSUE THREAD

**Issue by jludwig75** [microsoft/vscode#90637]
- VSCode Version:
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-29-generic
- OS Version:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Steps to Reproduce:

shift-insert used to be paste like ctrl-v. It is now "Paste Selection Clipboard." I used Ctrl-insert and shift-insert for copy/paste commands, because these are used in most newer linux terminals (ctrl-c and ctrl-v don't work in terminals). This is also supported for all other applications I use. I use ctrl-insert/shift-insert, because it is universally supported by all applications I use. Please revert the default for shift-insert back to paste. I know I can change the key binding, which I did, but paste should be the default behavior.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by solerman** [comment]
Took me a while to notice that was that specific shortcut that was causing the behavior, I thought that all selections where being copied to the clipboard. One workaround is call the shortcut editor (ctrl+k ctrl+s on linux), search for selectionClipboardPaste, right click on it and delete the binding

**Comment by sergeyvfx** [comment]
I totally agree here: none of other software I know have different behavior for Ctrl-V and Shift-Insert, those are expected to be the same thing. Difference in behavior in VS Code just causes frustration. Would also imagine this now have different behavior on different platforms: don't think Windows will have selection buffer, so Shift-Insert will be same as Ctrl-V there?

For pasting selection buffer middle mouse button is commonly used.

**Comment by alexdima** [comment]
This got changed in 1.42 for https://github.com/microsoft/vscode/issues/36170 . I don't know at this point what is the expected Shift+Insert Linux behavior. Those folks claim Shift+Insert should paste from the PRIMARY clipboard, while you claim it should not.

I have to be honest and say that I don't know what is really expected, or if this is something that simply differs across distributions. In any case, this can be easily tweaked on your side:

```
{
	"key": "shift+insert",
	"command": "editor.action.clipboardPasteAction",
	"when": "textInputFocus && !editorReadonly"
}
```

**Comment by moodboom** [comment]
I think all those nbs that fought for this Shift-Insert change were wrong.  IMHO.  Ha.  Damn my Microsoft ancestry... thanks for the configuration tip.
