### ISSUE TITLE
VSC stop working

### ISSUE THREAD

**Issue by wilson-burea** [microsoft/vscode#90630]
All VSC feature stop working and keeping showing an error message: https://recordit.co/5jU9LBYb9k

CPUs | Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 223, 157, 103
Memory (System) | 16.00GB (0.06GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
atlascode | atl | 2.4.2
vscode-node-readme | ben | 3.0.2
path-intellisense | chr | 1.4.2
bracket-pair-colorizer | Coe | 1.0.61
vscode-eslint | dba | 2.0.15
es7-react-js-snippets | dsz | 2.5.0
gitlens | eam | 10.2.1
vsc-material-theme | Equ | 32.4.0
vsc-material-theme-icons | equ | 1.1.3
vscode-todo-plus | fab | 4.14.1
git-graph | mhu | 1.21.0
vscode-typescript-tslint-plugin | ms- | 1.2.3
debugger-for-chrome | msj | 4.12.6
color-highlight | nau | 2.3.0
indent-rainbow | ode | 7.4.0
material-icon-theme | PKi | 3.9.3
vscode-yaml | red | 0.7.2
LiveServer | rit | 5.6.1
trailing-spaces | sha | 0.3.1
markdown-preview-enhanced | shd | 0.5.2
highlight-matching-tag | vin | 0.9.6

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
