### ISSUE TITLE
Keeps Closing and Attempting to download dependencies for js/ts intellisense

### ISSUE THREAD

**Issue by Eazash** [microsoft/vscode#90643]
Issue Type: <b>Bug</b>

Open vscode
Open a js or ts file

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-flutter-helper|aks|0.2.5
flutter-snippets|ale|2.0.0
cc-nodejs|cc-|0.0.3
path-intellisense|chr|1.4.2
regex|chr|0.2.0
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.2
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-eslint|dba|2.0.15
devdocs|dei|0.1.4
githistory|don|0.5.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
php-intellisense|fel|2.3.14
sass-lint|gle|1.0.6
nodejs-module-snippet|gun|0.0.2
ansible|haa|0.2.8
docker-linter|hen|0.5.0
vue-snippets|hol|0.1.11
RelativePath|jak|1.4.0
search-node-modules|jas|1.3.0
vscode-codemetrics|kis|1.23.1
flutter-tree|mar|1.0.0
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.9.0
vscode-docker|ms-|0.10.0
azure-account|ms-|0.8.8
awesome-flutter-snippets|Nas|2.0.3
vetur|oct|0.23.0
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
nodejs-snippets|piy|0.0.2
java|red|0.55.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
laravel-5-snippets|sac|2.0.1
vue-vscode-snippets|sdr|1.8.0
trailing-spaces|sha|0.3.1
html5-boilerplate|sid|1.0.3
guides|spy|0.9.3
ansible-autocomplete|tim|0.0.2
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
nodejs-extension-pack|wad|0.1.9
material-theme|zhu|3.2.2

(4 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
