### ISSUE TITLE
[Feature request] Support templates for workspaces

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#90649]
Hello,

We all know the command `--disable-extensions` which disables all the extensions when opening VSCode via terminal.

1. Yes, we also know the option `--extensions-dir`, but if we have to do it with this option, we have to create multiple folders prefixed with `.vscode-*` and symlink some extensions. 
2. And for the command `--disable-extension` – it allows disabling only one extension and not more than extensions. 

The ideal is that, we would like to open VSCode only with few extensions and excluding/disabling all other to optimise the performance due to the #89300, which showed that, with many extensions, searching and replacing all files at once will slow down the performance of VSCode and of the PC.

So we would add the new command `--enable-extensions <id> <id> <id> ...`.

**Comment by gusbemacbe** [comment]
Hello @bpasero, @JacksonKearl, @roblourens  @sandy081 and @Tyriar  !

I have read another topic about the workspaces with few extensions (#15611). According to you, the enabled extensions in each workspace are locally stored in the cache folder `Code - Insiders/User/workspaceStorage/`, the problem is that we want to back up the workspaces and the settings and it is useless to copy the whole `workspaceStorage` folder full of many unnecessary previous caches and states. For example, lets us call two computers A and B:

- I will copy the `.code-worskapce` files from the computer A to the computer B;
- In the computer B, I will open `.code-workspace` with VSCode, but you see that all extensions are enabled, because the `workspaceStorages` and caches are available only on the computer A.
- So, in the computer B, I have to redo what I did in the computer A. It is a waste of time. Too much repetitive. 

It is why you should add `--enable-extensions` or let us config only the extensions we can enable in the `.code-workspace` file.

**Comment by sandy081** [comment]
May I know why you would like to backup user data (settings etc)? Is it for syncing across machines?

Is your request similar to this - https://github.com/microsoft/vscode/issues/40239 ?

**Comment by gusbemacbe** [comment]
> May I know why you would like to backup user data (settings etc)? Is it for syncing across machines?

Yes, it is. I use @shanalikhan's [Settings Sync](https://github.com/shanalikhan/code-settings-sync). It backs up the workspace folder, but does not back up the `workSpaces` folder. 

> Is your request similar to this - #40239 ?

Reading this topic...:

- In @michaeljota's and @ramya-rao-a's case, he and she want to disable **some** extensions. In my case, I want to enable some and disable **all other*. Their case is team-specific;
- In @JordyScript's case, it is project-specific instead of workspace-specific. Not global. I want to set the specific workspace for every project, for example: A workspace called "PHP Projects" with PHP-specific extensions for any PHP project;
- Regarding @Sti2nd's summary, it is mostly team-specific and project-specific, I am the only user that wants to sync across multiple machines of mine, need to apply it to a specific workspace for any project made in a specific language;
- Regarding @aaronpowell's extension [VSCode Profile Switcher](https://github.com/aaronpowell/vscode-profile-switcher), what I said and what @TheryFouchter said, we have to create multiple folders and multiple symlinks, but multiple `user-data` increases the file size. Only the new command `--enable-extensions` and `.code-workspace` with enabled extensions and all disabled extensions will save the file size. Note that @shanalikhan's [Settings Sync](https://github.com/shanalikhan/code-settings-sync) does not back up the profiles generated by @aaronpowell's extension [VSCode Profile Switcher](https://github.com/aaronpowell/vscode-profile-switcher).

I do not want to use recommendations because they will not install or not enable automatically them.

**Comment by gusbemacbe** [comment]
Hi @sandy081!

What is your decision?

**Comment by sandy081** [comment]
FYI we are currently working on providing sync OOB and since your requirement is to sync workspaces, I would tag this as a sync request.

**Comment by gusbemacbe** [comment]
Hello @sandy081 !

There is a small problem.

I do not want to add folders to the workspaces because each workspace is for **any** project.

**Comment by sandy081** [comment]
Not sure if I understand what you meant. Can you please elaborate?

**Comment by gusbemacbe** [comment]
> Not sure if I understand what you meant. Can you please elaborate?

The folders are always saved in the workspace. When I open the workspace, the projects are there. I do not want to add or save them, I want an empty workspace, because the workspace is for any project, not just for added or saved project.

**Comment by sandy081** [comment]
Then what does the workspace configuration file shall contain?

**Comment by gusbemacbe** [comment]
> Then what does the workspace configuration file shall contain?

```json
{
	"folders": [
		{
			"path": "/home/gusbemacbe/Templates/Alan Silva"
		}
	],
	"settings": {
		"liveServer.settings.multiRootWorkspaceName": "Formulário com Validação"
	}
}
```

Look at `folders`. I do not want the workspaces to keep or save these folders for the next times.

**Comment by sandy081** [comment]
It means you only want settings to be synced? If so how different this is to have this setting in user settings and get synced?

**Comment by gusbemacbe** [comment]
> It means you only want settings to be synced? If so how different this is to have this setting in user settings and get synced?

Yes, with JSON of enabled extensions, similar to [Sync Settings](https://github.com/shanalikhan/code-settings-sync). Only it will not download the extensions. It will check if which extensions should be enabled and not enabled when I open the workspace.

If you have difficulty to understand my explanation due to language barrier, maybe  @shanalikhan will explain better or I will explain with JSON.

**Comment by sandy081** [comment]
Yeah it is difficult to understand your requirement. Can you please explain your use case with an example?

**Comment by gusbemacbe** [comment]
> Yeah it is difficult to understand your requirement. Can you please explain your use case with an example?

@sandy081 

Here is how should `.code-worksapce`:

```json
{
  "settings": 
  {
    "extensions": 
    {
      "dart-code.dart-code": "disabled",
      "dbaeumer.jshint": "disabled",
      "dustinsanders.an-old-hope-theme-vscode": "enabled",
      "ms-vscode.atom-keybindings": "enabled",
      "pranaygp.vscode-css-peek": "disabled"
    },
    "folders": 
    {
      "addFolderToWorkspace": false,
      // or
      "saveFolderToWorkspace": false,
      "path": ""
    }
  }
}
```

**Comment by sandy081** [comment]
Sorry still unclear to me. Please explain me the end to end scenario.

**Comment by gusbemacbe** [comment]
Hello @sandy081 

I simplified a bit, removing `settings`. I will explain each part. The whole code:

```json
{
	"folders": 
	[
		{
			"path": "",
			"saveFolderToWorkspace": false,
		}
	],
	"extensions":
	[
		{
		  "dart-code.dart-code": "disabled",
	      "dbaeumer.jshint": "disabled",
	      "dustinsanders.an-old-hope-theme-vscode": "enabled",
	      "ms-vscode.atom-keybindings": "enabled",
	      "pranaygp.vscode-css-peek": "disabled
		}
	]
}
```

1. In this part, if I set `false` to `saveFolderToWorkspace`, the added folder will never saved to workspace when I close the workspace or VSCode and when I open the workspace or VSCode next time:

```json
"folders": 
[
	{
		"path": "",
		"saveFolderToWorkspace": false,
	}
]
```

This is important for the user who **_opens_ different** PHP projects with **a same** PHP-specific workspace without getting bothered with a formerly saved/added folder/project, so he does not have to remove that project from workspace. _Opening_ is different of _adding_. Adding bothers more the user because it always saves the folder or projects to the workspace. 

If I set `true`, the added folder will be always be saved to the workspace when you close or open the workspace or VSCode, like:

```json
"folders": 
[
	{
		"path": "/home/gusbetuga/Projects/PHP-Workspace",
		"saveFolderToWorkspace": false,
	}
]
```

1. In another part, setting `disabled` or `false` means the extension is disabled, and setting `enabled` or `true` means the extension is enabled, so the user does not have to enable and disable manually the extensions the extensions in each workspace in a new machine:

```json
[
	{
		"dart-code.dart-code": "disabled",
	  "dbaeumer.jshint": "disabled",
	  "dustinsanders.an-old-hope-theme-vscode": "enabled",
	  "ms-vscode.atom-keybindings": "enabled",
	  "pranaygp.vscode-css-peek": "disabled
	}
]
```

**Comment by sandy081** [comment]
I see there are two requests.

1. You want a workspace template.
2. You want to persist extensions enablement for a workspace. This is a separate request which is tracked already. 

This issue will be tracked for workspace template.

**Comment by gusbemacbe** [comment]
@sandy081 

I think it will not be moved to the backblog as it will not receive votes, as the vscodebot has said.

**Comment by sandy081** [comment]
Yeah it is true as mentioned in the [documentation](https://aka.ms/vscode-issue-lifecycle).

**Comment by gusbemacbe** [comment]
@sandy081,

I'm going to close the issue as it does not have less than 20 votes. I'll create several workspaces folders by language and symlimk some specific language extensions for each workspace folder. 

Or I must migrate from VSCode to another lightweighting text editor with very low memory requirements.
