### ISSUE TITLE
Smaller Twitter logo

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#9064]
`workbench\parts\feedback\browser\media\twitter.svg` is 42KB. Can we drop the icon or replace it with a smaller one please?

Follow up from #7839

**Comment by bpasero** [comment]
@yfdyh000 is your commit a suggested fix for this? I gave your logo a try and it seems to work fine. If so, can you make a pull request?

**Comment by yfdyh000** [comment]
@bpasero discuss on PR #27290.

**Comment by bpasero** [comment]
@yfdyh000 ah yeah, sorry, long time ago 👍

**Comment by bpasero** [comment]
@isidorn can we activate our UX resources for a new smaller twitter SVG?

**Comment by isidorn** [comment]
@chryw as @bpasero mentions above could we get the smaller twitter SVG image?
Our current one can be found here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/feedback/electron-browser/media/twitter.svg#L1

**Comment by chryw** [comment]
[BrandTwitter.zip](https://github.com/Microsoft/vscode/files/1471859/BrandTwitter.zip)
@isidorn could you try the attached files? svg should be responsive so it should fit in whatever the container size is.

**Comment by isidorn** [comment]
@chryw thanks. it worked great.

![screen shot 2017-11-14 at 18 45 34](https://user-images.githubusercontent.com/1926584/32795455-02d504dc-c96c-11e7-8e4f-317e70cf8599.png)
