### ISSUE TITLE
Typescript intellisense failing for web worker despite separate tsconfig.json files

### ISSUE THREAD

**Issue by pierznj** [microsoft/vscode#90642]
Issue Type: <b>Bug</b>

I cannot get typescript intellisense to work correctly with web worker code. Despite the fact that I have a correctly configured tsconfig.json in the web worker code folder, with no tsconfig files further up in the directory structure of the project, vscode continues to use types from `lib.dom.d.ts`. The tsconfig.json inside the web worker folder is definitely correct, since I can compile and run the web worker code during the build process.

To reproduce:
Create a folder structure:
```
-src
  -app
    tsconfig.json
  -worker
    worker.ts
    tsconfig.json
```

Where `tsconfig.json` inside the worker folder is:

```
{
  "compilerOptions": {
    "lib": ["scripthost", "ES2015", "webworker"],
    "importHelpers": true,
    "target": "es5",
    "sourceMap": true,
    "inlineSources": true,
    "diagnostics": true,
  },
  "exclude": ["node_modules"],
  "files": ["./*.ts"]
}
```
The `tsconfig.json` is standard for a browser project. In my case:
```
{
  "compilerOptions": {
    "lib": ["es2018", "dom"],
    "importHelpers": true,
    "target": "es2015",
    "jsx": "react",
    "sourceMap": true,
    "moduleResolution": "node",
    "inlineSources": true,
    "diagnostics": true,
    "types": [
      "react",
      "react-dom",
      "hls.js"
    ]
  }
}
```

Inside `worker.ts` add the single line: `postMessage('hi');`
Intellisense underscores the code in red: `lib.dom.d.ts(17924, 44): An argument for 'targetOrigin' was not provided.`

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
simple-react-snippets|bur|1.2.2
vscode-perl|cfg|1.18.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.9.1
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|2.2.2
sass-lint|gle|1.0.5
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.2.5
vscode-peacock|joh|2.4.0
chat|kar|0.31.0
git-graph|mhu|1.21.0
code-beautifier|mic|2.3.3
python|ms-|2019.6.24221
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1615
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
material-icon-theme|PKi|3.9.3
vscode-data-preview|Ran|1.8.0
java|red|0.46.0
sass-indented|rob|1.5.1
selectline-statusbar|tom|0.0.2
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.18.1
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
Version 1.33.1 is nearly a year old. Can you update and then re-test?

**Comment by pierznj** [comment]
Thanks - updated (VSCode was in a read-only folder). But problem persists.

**Comment by pierznj** [comment]
I found the problem. It seems VSCode silently ignores tsconfig if there are any problems with it. `"files": ["*.ts"]` is invalid because files does not allow glob patterns.

**Comment by mjbvz** [comment]
Thanks for testing and tracking down the cause.

This would be easier to detect with https://github.com/microsoft/TypeScript/issues/30623
