### ISSUE TITLE
Sync: Turn off sync on all devices does not work

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#90640]
![image](https://user-images.githubusercontent.com/35271042/74487357-1f81e200-4e74-11ea-8074-9e271ad0dc83.png)

1. Setup sync on two machines
2. Turn off sync and check "Turn off sync on all devices" on primary machine
3. :bug: Secondary machine never gets turned off
<img width="50%" src="https://user-images.githubusercontent.com/35271042/74487482-6c65b880-4e74-11ea-8e92-2b17535e34e2.png">

4. Turn on sync on primary machine
5. :bug: Primary machine does NOT get prompted to sign in again and starts syncing. Secondary machine picks up changes, so the "Turn off sync on all devices" never worked

**Comment by sandy081** [comment]
> 🐛 Secondary machine never gets turned off

Turning off sync automatically on other machines is working for me when sync is turned off completely on one machine. Am I missing any steps here?

>  🐛 Primary machine does NOT get prompted to sign in again and starts syncing. Secondary machine picks up changes, so the "Turn off sync on all devices" never worked

You might be hitting this issue - https://github.com/microsoft/vscode/issues/89750

Regarding not showing sign in - we do not sign out when turning off. Filed a separate issue - https://github.com/microsoft/vscode/issues/90867

Closing this as the issues are tracked individually.
