### ISSUE TITLE
Folder named CVS not showing in explorer

### ISSUE THREAD

**Issue by philipmat** [microsoft/vscode#90641]
- VSCode Version: 1.42.0, 1.42.1 (user setup)
- OS Version: Windows 10 (Windows_NT x64 10.0.18362)

Steps to Reproduce:

1. Create a sub-folder called "CVS" (with or without files in it)
2. Open parent folder - notice the "CVS" folder is not visible in Explorer
3. Rename to "cvs" => folder visible
4. Rename back to "CVS" folder disappears

Note: any other variations such as "CVS1" or "CVX" show in Explorer. Only CVS doesn't

Does this issue occur when all extensions are disabled?: Yes

- !["CVS" folder not showing](https://user-images.githubusercontent.com/709928/74490446-2b7a9d80-4e8e-11ea-8fe3-7f54876a3fac.png)
- !["cvs" folder showing](https://user-images.githubusercontent.com/709928/74490472-39c8b980-4e8e-11ea-82aa-13ea51ae8d00.png)

I believe it's related to commit [fa0bc23382316d](https://github.com/microsoft/vscode/commit/fa0bc23382316d6ec2cd6bd7d9b198f0511e3b42) in v1.39.1 which ignores "CVS" folders, presumably as associated with the CVS versioning system.

Is there a way to override this for those of us who work with a client called CVS?

**Comment by JacksonKearl** [comment]
```
"files.exclude": {
   "**/CVS": false
}
```
