### ISSUE TITLE
Variable explorer functionality broken

### ISSUE THREAD

**Issue by aksharOza** [microsoft/vscode#90646]
I am running an interactive python session using sklearn and pandas and variable explorer no longer shows the size of the variables just the count. Before we could see if a variable was a vector or a matrix along with the number of dimensions from the size. Also, variables are no longer individually viewable in a Data viewer tab (although a pandas dataframe still is). Finally, somehow my terminal is also no longer working, starting a new terminal always results in the followin error: 
The terminal process command 'C:\Windows\System32\cmd.exe' failed to launch (exit code: {2})

These errors are all new after the January 2020 update, before the update everything was working as expected.

**Comment by gjsjohnmurray** [comment]
/causedByExtension Issue probably belongs at https://github.com/microsoft/vscode-python/issues
