### ISSUE TITLE
Switching the Chinese input method causes the input window to be abnormal.

### ISSUE THREAD

**Issue by dv0** [microsoft/vscode#90647]
- VSCode Version:1.42.1 (user setup)
- OS Version:Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Use Sogou Pinyin input method to enter the code.
2. Enter characters in the input method window that pops up, and then switch input methods.
At this time, the code window started abnormally, and characters could not be entered and deleted normally.
![GIF 2020-2-14 11-50-27](https://user-images.githubusercontent.com/5212015/74500483-fcae0700-4f21-11ea-8f98-7ca70df002e5.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@dv0 can you try turn on `editor.renderControlCharacters ` and provide another screen recording ?
