### ISSUE TITLE
feature request: typescript rename refactor operation that propogates renames as far as possible

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#90645]
Rename refactoring of typescript performs a rename over the smallest domain it possibly can ...

Given this code:
```
const example = ({ arg1, arg2 }: { arg1: string; arg2: string }) => {
  console.log({ arg1, arg2 });
};

const exampleCallSite = ({ arg1 }: { arg1: string }) => {
  example({ arg1, arg2: "value2" });
};
```

triggring rename refactor on either the first or third occurences of arg1 in `example` produces this:

```
const example = ({ arg1: renamed, arg2 }: { arg1: string; arg2: string }) => {
  console.log({ arg1: renamed, arg2 });
};

const exampleCallSite = ({ arg1 }: { arg1: string }) => {
  example({ arg1, arg2: "value2" });
};
```

renaming the second occurrence produces this:

```
const example = ({ renamed: arg1, arg2 }: { renamed: string; arg2: string }) => {
  console.log({ arg1, arg2 });
};

const exampleCallSite = ({ arg1 }: { arg1: string }) => {
  example({ renamed: arg1, arg2: "value2" });
};
```

In each of these cases, the refactor performs an operation which changes the name of arg1 in the smallest possible set of places ...

This is I suppose trying to be `more safe` in that it cuts down on the number of places where the compiler might not find the places that need renaming -- but not propogating the change as far as possible is almost always the "wrong" rename operation for smaller codebases where the code needs to be compatible only with itself ...

I would really like a refactor operation that produced this result:

```
const example = ({ renamed, arg2 }: { renamed: string; arg2: string }) => {
  console.log({ renamed, arg2 });
};

const exampleCallSite = ({ renamed }: { renamed: string }) => {
  example({ renamed, arg2: "value2" });
};
```

I would really like a rename refactoring operation which propagates the rename _as far as it can_ rather than _as little as it can_ ... Ideally it would only perform the 'safe rename' style change to adjust call sites for 'external' code -- where 'external' would be some sort of reasonable heuristic for 'a code boundary which the compiler doesn't understand sufficiently well to propogate changes into '  ...

Or perhaps an even simpler and even less safe heuristic -- perform the 'safe rename' only at call-sites of functions defined outside the project.

**Comment by mjbvz** [comment]
Our renames try to be as safe as possible by default. You can opt out of this by setting  `"typescript.preferences.renameShorthandProperties": false`.

After setting this, do you get the behavior you are after?

**Comment by breathe** [comment]
Thank you @mjbvz !  This is making me much happier!  :)
