### ISSUE TITLE
Crashed no response

### ISSUE THREAD

**Issue by Lanseria** [microsoft/vscode#90652]
Issue Type: <b>Bug</b>

When I ended development and closed the terminal by the way, vscode stuck and became unresponsive

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (24.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.63072
remote-containers|ms-|0.101.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
vetur|oct|0.23.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.3
prisma|Pri|0.0.22
vscode-graphql|Pri|0.2.2
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4
yarn-ui|xqc|0.1.2

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Please consult https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests for information on how to document reproducing this so we can fix it.

**Comment by Lanseria** [comment]
TA shared a file for you, enter the pickup code on cowtransfer.com (cowtransfer.com): slnmxa (valid within 24 hours) View the file list, or click the pickup link directly: https://c-t.work/s/939dfe39c1ff4d View file list

**Comment by Lanseria** [comment]
I recorded a video https://www.youtube.com/watch?v=4BN306UDG4k

**Comment by Lanseria** [comment]
This may be related to my `setting.json` configuration file, I don't seem to have this problem on another computer, I go back to try it at night
