### ISSUE TITLE
Freezes my Operating System (Ubuntu)

### ISSUE THREAD

**Issue by kimbosanz-dev** [microsoft/vscode#90654]
Every time i code inside VS Code it constantly freezes my total Cpu Sytem

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo by "freezes" do you mean 100 percent CPU utilisation? Please see wiki page about how to submit performance issues.

**Comment by JacksonKearl** [comment]
Also see https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests for information on how to help us reproduce and fix the issue.
