### ISSUE TITLE
Unable to see all the symbols in the file when I use the @option in the command pallete.

### ISSUE THREAD

**Issue by SriramDineshVanama** [microsoft/vscode#90651]
- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a .c file which has more than 30 functions definitions. (I just assume that this might be the scenario because I don't have seen anything else special with the file I am facing issue with)
2. Browse for a function name (which is defined near the end of the file) in the command pallete using @  prefix. You won't find that function.
Note : There seems to be some boundary in the file before which all functions defined are appearing in my @search but functions defined after that are not appearing in the @search.

Does this issue occur when all extensions are disabled?: If I disable the extensions none of the functions will be seen which is expected.

**Comment by JacksonKearl** [comment]
Other providers are able to produce results for the whole file, I think this is likely and issue with the C/C++ extension. Please file over there, and if possible include a file that reproduces the error, there might be some special syntax that is causing parse to fail past a point.
