### ISSUE TITLE
Font rendering messed up with too much spacing

### ISSUE THREAD

**Issue by zskamljic** [microsoft/vscode#90659]
- VSCode Version: 1.42.1
- OS Version: Linux (5.5.3-arch1-1) with GNOME Shell 3.34.3

Steps to Reproduce:

1. Open VS Code
2. Observe

Does this issue occur when all extensions are disabled?: Yes

I have tried deleting the ~/.vscode and ~/.config/Code directories completely, the error persists. The fonts look like the following:

![image](https://user-images.githubusercontent.com/14160663/74510963-299ff100-4f05-11ea-8510-f1b46848d860.png)

**Comment by deepak1556** [comment]
Can you provide your `settings.json` configs ? Also how does it look when launching with `--disable-gpu` ?

**Comment by zskamljic** [comment]
I tried running it with `--disable-gpu`, looks the same. My settings.json is empty (`{}`), it happens even after fresh install.

**Comment by alexdima** [comment]
@zskamljic Can you try to download the zip version and extract it / execute it in a clean way (without settings or extensions). I believe you might have installed an extension or something that has changed our CSS file.

**Comment by zskamljic** [comment]
Tried running the clean version, created a separate user for it and the result is the same. Possibly worth noting, I didn't have VSCode installed before reporting this issue, I experienced the bug on a clean install
