### ISSUE TITLE
Suggest Widget lazy rendering

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#90653]
Suggest Widget is a content widget in Monaco Editor and usually it's fast, when comparing with costly operations. However when exploring Notebooks, we made quite a few attempts to improve the initial rendering performance, after which, Suggest Widget stands out

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/876920/74504766-1c094d80-4eaa-11ea-8644-9870c469d878.png">

I created multiple Monaco editors in sequence while scrolling and the rendering/layout of Suggest Widget triggers forced reflow because the first the content widget is rendered, we will check its dimension.

https://github.com/microsoft/vscode/blob/20f4cbf4b6e585a15751effe59ab40e180d11b43/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts#L437-L441

**Comment by rebornix** [comment]
Some more details.

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/74808554-f613ec80-529f-11ea-8dc5-7e88281fb913.png">

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/74808565-fb713700-529f-11ea-81d2-7e0d3cfe2271.png">


If we stop rendering of suggest widget, the chart is *green*

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/74808730-5d31a100-52a0-11ea-905d-b12a3d39bef3.png">

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/74808806-94a04d80-52a0-11ea-9128-9d29ab4d6df8.png">

**Comment by rebornix** [comment]
Moving to March and + @jrieken as the Suggest Widget seems pretty complex now after adopting the List View ;)

**Comment by jrieken** [comment]
hm.. the suggest widget should only be created when there is slack time (https://github.com/microsoft/vscode/blob/031bb8e6c3ed2958ccc0160fc9778a18c2c52033/src/vs/editor/contrib/suggest/suggestController.ts#L123). Anyways, does it make sense to tackle this for the suggest widget alone? Isn't this an issue with all content widgets then?

**Comment by jrieken** [comment]
This is the bad call, right: https://github.com/microsoft/vscode/blob/6338aed25d6b07324883e1dea49b7b06837147c6/src/vs/editor/contrib/suggest/suggestWidget.ts#L648. We should be able to change that with easy, e.g only add the widget when showing it (the first time)

**Comment by rebornix** [comment]
@jrieken all content widgets might contribute to the rendering cost but since suggest widget is complex, it adds "a lot" of overhead (around 10ms, which is small most of the time, but large in Notebook case). If we can postpone the registration or creation, it can mitigate this issue.

**Comment by jrieken** [comment]
I have pushed a change that makes the suggest widget "more lazy". We should do a similar change for the light bulb, because it's also a content widget and usually created when the language "has smarts"

**Comment by jrieken** [comment]
The suggest widget is now off the hook. I have figured its still a long way until the light bulb comes onto the radar then we should tackle it as its own issue, or better tackle this as the editor level
