### ISSUE TITLE
Cannot display marketplace content without specifying --ignore-gpu at startup

### ISSUE THREAD

**Issue by chenweize1998** [microsoft/vscode#90658]
- VSCode Version: 1.42.1 (updated today, the problem also exists in the previous versions and insider version)
- OS Version: Linux x64 5.4.18-1-MANJARO

Steps to Reproduce:

1. Launch VSCode normally. The extension marketplace keeps loading. No error message like "Cannot connect to the marketplace" is shown. I toggle developer tools and see a warning in the console "renderer did not receive lazyEnv in time" (the message appears 10 seconds after startup, nothing is shown in the background in these 10 seconds). 
2. Launch VSCode with "--ignore-gpu" or "ignore-gpu-blacklist", and everything will be fine.

Does this issue occur when all extensions are disabled?: Yes

Here is my system information.
![2020-02-14 15-27-09屏幕截图](https://user-images.githubusercontent.com/32613237/74510366-94215300-4f3e-11ea-9044-efd7c0562d89.png)

And here is the warning displayed in the console.
![2020-02-14 15-30-28屏幕截图](https://user-images.githubusercontent.com/32613237/74510553-f5e1bd00-4f3e-11ea-99aa-06fc10540227.png)

**Comment by sunnyrains** [comment]
THE SAME ISSUE IS ON VSCODE INSIDERS VERSION APRIL .
UNABLE TO CONNECT IT ON UBUNTU 16.04 
THIS IS SERIOUS AND  URGENT ISSUE .

**Comment by deepak1556** [comment]
@chenweize1998 can you try our exploration build which seems to have reports of better gpu support https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 

@sunnyrains when you mean similar issue , do you also have to start VSCode with `--ignore-gpu-blacklist` ?

If thats not the case then please open a new issue with screenshots of the issue you are seeing, launch insiders with `--verbose` and attach the log after performing some actions with the marketplace. Thanks!
