### ISSUE TITLE
Allow "access" to "Retry as sudo" by keyboard

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode#90661]
Anytime I save a file that requires elevated permissions using `Ctrl+S`, I get the popup with the button to `Retry as Sudo`. This is perfectly fine, but there doesn't seem to be any way to "run" `Retry as Sudo` using the keyboard. I have to use the mouse to actually click the `Retry as Sudo` button.

This is very cumbersome when performing many changes in such a file. E.g. the following workflow could be performed completely without "mouse interaction" if `Retry as Sudo` could be activated by keyboard:

* Changes to "system file"
* Save -> Click on `Retry as Sudo`
* Test changes in cmd line
* More changes
* Save -> Click on `Retry as Sudo`
* Test
* More changes
* ...

If this is already possible somehow, please also answer [this stackoverflow question](https://stackoverflow.com/questions/56933085/save-with-retry-as-sudo-using-keyboard-commands) (by someone else).

**Comment by JacksonKearl** [comment]
`Notifications: Focus Notification Toast` (this can be mapped to a keybinding)
`Tab`
`Enter`
