### ISSUE TITLE
Search everywhere is not working anymore using Double-Shift?

### ISSUE THREAD

**Issue by floschl** [microsoft/vscode#90662]
Issue Type: <b>Bug</b>

This seems that it has been removed since last 1.42 version update.
How can I reactivate it?

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.15.0-76-generic snap

**Comment by JacksonKearl** [comment]
I'm not sure what you mean, did you add a custom keybinding for shift chorded to shift?

**Comment by floschl** [comment]
I am still not quite sure, but I might have confused that with my PyCharm IDE, where there is such a shortcut. I am sorry. I'll close this ticket.
Thanks anyway!
