### ISSUE TITLE
manjaro ntfs git目录识别不到

### ISSUE THREAD

**Issue by 354651432** [microsoft/vscode#90665]
Issue Type: <b>Bug</b>

挂载一个ntfs硬盘
在上面新建一个git目录
vscode打开这个目录,
修改文件, 并不会出现git相关信息

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.18-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.67GB (4.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
shell-format|fox|7.0.1
rest-client|hum|0.23.1
vscode-phpfmt|kok|1.0.30
git-graph|mhu|1.21.0
vscode-language-pack-zh-hans|MS-|1.42.2
sublime-keybindings|ms-|4.0.6
vetur|oct|0.23.0
laravel5-snippets|one|1.7.0
material-icon-theme|PKi|3.9.3

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
This issue is being closed because its description is not in English, that makes it hard for us to work on it. Please open a new issue with an English description. You might find [Bing Translator](https://www.bing.com/translator) useful.
