### ISSUE TITLE
Hot exit should be disabled when opening secure locations

### ISSUE THREAD

**Issue by EricPell** [microsoft/vscode#90667]
Issue Type: <b>Bug</b>

Due to the use of temporary files, files opened from the encrypted OneDrive vault are avilable even after the Vault is locked, and VS Code is closed.

Reopening, the cached file is still available. 

This is a potential security risk. It would be awesome if VS Code recognized that the file opened was from the Vault, and therefore cleared the cache when closed. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19559

**Comment by JacksonKearl** [comment]
You can disable hot exit `"files.hotExit": "off"`. Ping @bpasero for if this can be disabled automatically.

**Comment by bpasero** [comment]
@EricPell to clarify, you mean files can be recovered when they are dirty? If so, the suggested workaround from https://github.com/microsoft/vscode/issues/90667#issuecomment-586419179 would help.

**Comment by bpasero** [comment]
Alternatively, maybe the portable mode would also be something to use: https://code.visualstudio.com/docs/editor/portable

**Comment by EricPell** [comment]
> @EricPell to clarify, you mean files can be recovered when they are dirty? If so, the suggested workaround from [#90667 (comment)](https://github.com/microsoft/vscode/issues/90667#issuecomment-586419179) would help.

Hi, the issue is that Code caches the file, which is normally encrypted in the FileVault. 

If you close Code, then the file vault, or in opposite order, without trying to save any changes to the file, the next time you re-open Code you get the cached file, which you would assume is protected in the Vault.

Disabling hotExit for all files isn't an option, because it's a good option. Just not for the one specific location that MS makes secure, your FileVault.

I don't think disabling things that makes Code a useful editor, like resuming workspaces is the solution. 

I think just a simple check on exit for any files that were opened from the Vault should be cleared from memory.
