### ISSUE TITLE
.tsx code format broken

### ISSUE THREAD

**Issue by mbilling** [Microsoft/vscode#9067]
- VSCode Version: Code - Insiders 1.4.0-insider (f6227ca157caed3ce3224ad9f760a8d5c8ed0e4d, 2016-07-11T05:07:20.965Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open new VSCODE
2. Paste kode from file [Configurations.txt](https://github.com/Microsoft/vscode/files/356989/Configurations.txt) into Untitled-1
3. Save as e.g. "test.tsx"
4. Jump to line 1457
5. Press Alt + Shift + F or run format code command
6. Nothing happens - code is still the same (i believe the format code service dies here)
7. Create a new .tsx file make some simple typescript, e.g.
```
function(test:string)
   {
      let example      =   test;
   } 
```
8. Press Alt + Shift + F and nothing happens. You need ´to restart VSCode to run "Format Code" again

/Michael

**Comment by mbilling** [comment]
Also try and fold the code on the render() method
This shows a bug in code folding - maybe there are some issues reported on that too.
So maybe a fix fixes multiple bugs

**Comment by dbaeumer** [comment]
Was able to reproduce this. It is a bug in the tsserver. The request returns with the following error:
```
Response received: configure (7). Request took 3 ms. Success: true 
Sending request: format (8). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/9067/test.tsx",
    "line": 1,
    "offset": 1,
    "endLine": 1947,
    "endOffset": 1
}

Response received: format (8). Request took 293 ms. Success: false . Message: Error processing request. Debug Failure. False expression: 
```

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9668
