### ISSUE TITLE
Move blocks in diff view

### ISSUE THREAD

**Issue by modbw** [microsoft/vscode#90678]
It would be handy to be able to move blocks of code in diff view around like for example in WinMerge with Alt+LeftArrow/RightArrow or with some sort of arrows in the splitter of the diff view

![winmerge](https://user-images.githubusercontent.com/4498104/74521678-13506000-4f1a-11ea-8a54-619382c3324e.gif)

**Comment by JacksonKearl** [comment]
Does `Git: Revert Selected Ranges` help any here?

**Comment by modbw** [comment]
Unfortunately not because I regularly diff config files from two machines and would like to copy blocks from one side to the other like I can do in WinMerge or in other visual diff tools like Meld

![image](https://user-images.githubusercontent.com/4498104/74712226-169f6080-5226-11ea-9564-0b99629d748e.png)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/25887
