### ISSUE TITLE
Keyboard Shortcuts' (sic) key input dialog disappears when program loses focus

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90679]
1 In Keyboard Shortcuts (sic), click a Keybinding (sic)
2 See the (untitled) key combination input dialog:

![image](https://user-images.githubusercontent.com/6157073/74522235-bb622b00-4f12-11ea-9f77-35d190a4a624.png)

3 Switch to another open program that does not cover this program's window

Expected: dialog box still present
Observed: dialog box gone.

![image](https://user-images.githubusercontent.com/6157073/74522149-979ee500-4f12-11ea-8e8d-ec65c31589ed.png)

V1.42.1 on Windows 7.

For avoidance of doubt, this is a bug report, not a feature request. The "feature-request" tag wasn't added by me, and I can find no way to remove it. Would someone please remove it? Thanks.

**Comment by JacksonKearl** [comment]
Most of out dialog boxes disappear when we lose focus, for instance QuickPicks for go to file and the command pallet. I'm not sure that this should be different.

**Comment by chrisjj** [comment]
> Most of out dialog boxes disappear when we lose focus, for instance QuickPicks for go to file and the command pallet. I'm not sure that this should be different.

I agree. None should be different. I'll report others as I find them.

**Comment by chrisjj** [comment]
> JacksonKearl closed this 9 minutes ago

Why has this been closed? I've seen no comment disputing that this is a defect.

**Comment by JacksonKearl** [comment]
All temporary inputs in the application disappear on window blur. There's no reason to "fix" over "fixing" the others, and I'm as of yet unconvinced that the current behaviour is broken.

**Comment by chrisjj** [comment]
> All temporary inputs in the application disappear on window blur.

"temporary inputs"??

> There's no reason to "fix" over "fixing" the others

Agreed 100%. All are equally deserving.

> and I'm as of yet unconvinced that the current behaviour is broken.

I can see no advantage to this behaviour, let alone one sufficient to compensate for the disadvantage to the user e.g. throwing away his VS Code input in progress when a calendar program pops-up a reminder.

Which is probably why I've never seen another Windows program that behaves so badly in this regard. That includes not just programs using Windows native UI API, but cross-platforms UIs too.

**Comment by JacksonKearl** [comment]
If the input closes when it loses focus, it also closes when the window loses focus.

**Comment by chrisjj** [comment]
> ... the input closes when it loses focus...

Schoolboy error.

**Comment by chrisjj** [comment]
bot wrote:
> This feature request is now a candidate for our backlog. 

Where did the bot get the idea this is a feature request? It is not. It is a bug report.

**Comment by sandy081** [comment]
I do not think it is a bug as the current behaviour is intended. This request is to change the behaviour.

**Comment by chrisjj** [comment]
> I do not think it is a bug

Since I doubt the bot read your mind :) my question stands.

**Comment by chrisjj** [comment]
> This feature request 

This is a bug report, not a feature request. The "feature-request" tag wasn't added by me, and I can find no way to remove it. Would someone please remove it? Thanks.

**Comment by chrisjj** [comment]
> this feature request

This is not a feature request. This is a bug report. Would the person who falsely tagged this "feature request" (or anyone else) please remedy that? Thanks.
