### ISSUE TITLE
Change Tweet Feedback Button back to smiley

### ISSUE THREAD

**Issue by niderhoff** [microsoft/vscode#90674]
Hey,
I recently noticted that the little smiley feedback button has been changed to some generic icon with a person and a textbubble(?). The smiley really was the only reason I had the button enabled in the UI and it really liked the little thing grinning at me every time I opened VSCode. 

Was the change documented anywhere? I couldn't find an Issue regarding it.

What do I have to do to change it back?

**Comment by misolori** [comment]
See #87775, this is to align with the Feedback icon used in other Microsoft products (like Edge and Visual Studio). You can upvote #89894 which will allow you to use custom icons throughout the workebench.
