### ISSUE TITLE
No need of intellisense when type 'as' in python

### ISSUE THREAD

**Issue by missingdaysqxy** [microsoft/vscode#90673]
Issue Type: <b>Bug</b>

example: 
1. when I typed "import numpy as np" and then press enter, the 'np' will auto changed into 'numpy', I don't need it.
2. Also "from matplotlib import pyplot as plt" will change "plt" into "pyplot", why????

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.15
vscode-gnu-global|jay|0.3.2
plantuml|jeb|2.13.6
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.63072
remote-wsl|ms-|0.42.3
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
team|ms-|1.161.0
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by JacksonKearl** [comment]
Please file against the Python extension.
