### ISSUE TITLE
VS Code ignores .gitignore

### ISSUE THREAD

**Issue by Friksel** [microsoft/vscode#90670]
- VSCode Version: 1.42.0 [edit: still there in 1.43.0]
- OS Version: Windows 10 

Steps to Reproduce:

1. Change files in folders that are mentioned in the .gitignore file
2. Look in the repository panel of vs code and see the files are mentioned as changed and can be staged to commit (these files should not be in the list, but are)
3. Try to commit --> This throws an error by git.exe itself because some of the files we try to commit are in the .gitignore list and therefore cannot be commited to the repository. So the full commit fails and VS Code leaves the files that should be ignored in the list as changed and/or staged.

Does this issue occur when all extensions are disabled?: Yes

Not sure if this issue appeared in version 1.42.0 or a previous version, but before this first commit after the VS Code update to 1.42.0 I never seen this problem before in VS Code. With neither of the projects I'm working on.

**Comment by joaomoreno** [comment]
>Look in the repository panel of vs code and see the files are mentioned as changed and can be staged to commit

Were these files ever committed to the repository, or are they untracked?

> Try to commit --> This throws an error by git.exe itself because some of the files we try to commit are in the .gitignore list and therefore cannot be commited to the repository.

What error? Git won't ever issue an error if you try to commit ignored files.

**Comment by Friksel** [comment]
`What error? Git won't ever issue an error if you try to commit ignored files.`

![git message vs code](https://user-images.githubusercontent.com/3089978/74758430-9f92b800-5277-11ea-8dc5-26b75dba1c6d.jpg)
![git message vs code - terminal](https://user-images.githubusercontent.com/3089978/74758440-a15c7b80-5277-11ea-81a9-baf1561cfc1e.jpg)

**Comment by joaomoreno** [comment]
Oh that's new! What git version do you have installed? Can you repro with an earlier version? Did you upgrade git recently?

**Comment by Friksel** [comment]
I didn't upgrade git recently. I did upgrade VS Code though and since than having this problem once in a while with different projects.
Using git 2.22.0 windows

**Comment by Friksel** [comment]
Unfortunately this issue is still there in version 1.43.0. This thing is pretty annoying as it pops up every time eventhough there's nothing wrong. 

Is this being looked at?

**Comment by joaomoreno** [comment]
How does the flow work in the command line if you try to:

```
git add .
git commit -m 'try to commit'
```

**Comment by Friksel** [comment]
@joaomoreno 
This is not a git issue, this is a refresh issue. After having the error popup in VS Code showing the git message, sometimes it just works but most times I need to refresh the source control list and works after that.
Because it happens randomly IMHO it doesn't debug anything to switch over on those random moments to direct git commands when it happens. IMHO it doesn't prove anything, because it looks like a timing/refresh issue in the UI trying to do things while git is not done with some operation or something like that. So even if it would work with the git command line, we still don't know anything more than we do know now.

**Comment by Friksel** [comment]
@joaomoreno
This doesn't look like a git issue to me, but a refresh issue in vs code. After having the error popup in VS Code showing the git message, sometimes it just works but most times I need to refresh the source control list and works after that.
Because it happens randomly IMHO it doesn't debug anything to switch over on those random moments to direct git commands when it happens. IMHO it doesn't prove anything, because it looks like a timing/refresh issue in the UI trying to do things while git is not done with some operation or something like that. So even if it would work with the git command line, we still don't know anything more than we do know now.

**Comment by joaomoreno** [comment]
> How does the flow work in the command line if you try to:
> 
> ```
> git add .
> git commit -m 'try to commit'
> ```

Can you give this a try?

**Comment by Friksel** [comment]
> Can you give this a try?

I refer to my last post.

**Comment by joaomoreno** [comment]
I'm sorry, I don't know how I can help you. This is very likely not a timing issue at all. You're trying to stage something inside the `dist` folder. If you try to do that in your command line you'll see the exact same error, which is what I'm trying to show you by asking you to run those commands. This is a git error, and it's there to prevent you from staging something which is listed in your ignore file.

**Comment by Friksel** [comment]
@joaomoreno  Really? You are just closing issues you are not willing to solve or cannot solve nor recognise this issue and use excuses for it you know that aren't true? That's pretty unprofessional and a strange way to get the issues count down.

Shame on you.

**Comment by joaomoreno** [comment]
I don't know what to tell you. Please read through the issue once again. I have asked you to provide very specific information, and you still haven't done so. If you manage to show me that `git commit` won't fail in the terminal when you have ignored files in your index, please let me know.

Until then, there's no need for that sort of language; this is your first warning.
