### ISSUE TITLE
Running SFDX: Authorize an Org --> Running long and cant able to Authorise my Org

### ISSUE THREAD

**Issue by ganapathybaskar** [microsoft/vscode#90684]
Running SFDX: Authorize an Org --> Running long and cant able to Authorise my Org, Please help to fix.
git id: ganapathybaskar

![Running long](https://user-images.githubusercontent.com/60092504/74525127-6a6c2a00-4f46-11ea-8e60-e0e4a3f9c383.PNG)

**Comment by IllusionMH** [comment]
/causedByExtension

Please report this issue in SFDX extension repo

**Comment by ganapathybaskar** [comment]
How to do that @IllusionMH 
I am new to this forum

**Comment by IllusionMH** [comment]
I just mean that this is issue tracker for VS Code editor itself however you are using extension for working with SF. And issue with SF should be reported extension's repo and not it this repository.

I would guess that this should be https://github.com/forcedotcom/salesforcedx-vscode repo (has `SFDX: Authorize an Org` line), but you can check Repository link in your extension description to be sure.

**Comment by JacksonKearl** [comment]
@IllusionMH thanks. Still haven't been able to get the bot back up.

**Comment by ganapathybaskar** [comment]
This was not caused by extension, i resolved it now.
Its due to my google chrome which acted as a default browser blocked the pop up of salesforce authentication.

We just need to change the system default browser to Edge or Internet explorer or Firefox and it worked :)
