### ISSUE TITLE
wrong character display when using chinese input

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [microsoft/vscode#90688]
i input chinese text and save, reopen, it will be broken text.

"files.autoGuessEncoding": true,
Files: Encoding: utf8

version 1.42 is ok, this verison is broken

versioninfo

version: 1.42.1
commit: c47d83b293181d9be64f27ff093689e8e7aed054
date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.0-8-amd64

**Comment by rebornix** [comment]
@ziyouchutuwenwu could you share the content to help troubleshoot?

**Comment by ziyouchutuwenwu** [comment]
- here are the steps:
```bash
i create a file named aaa in /home/mmc/downloads/
right click on the file, choose open with vscode
input any chinese character, for example, 啊啊啊
save and reopen it, it will show unknown character
```

here is the snapshot
![1](https://user-images.githubusercontent.com/7458713/74584626-7c65cf80-500f-11ea-8fb2-1da3a1e25038.png)
this is the image i input

![2](https://user-images.githubusercontent.com/7458713/74584631-87206480-500f-11ea-8072-c99876cd0d12.png)
this is the broken character

**Comment by ziyouchutuwenwu** [comment]
when i set "files.autoGuessEncoding": false, it woks fine.
```bash
echo $LANG
zh_CN.UTF-8
```

and i just open and save with vscode, no other editor opened.
