### ISSUE TITLE
VSCode stealing focus / switching macOS spaces

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#90680]
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
<br>OS version: macOS Catalina (Darwin x64 19.3.0)

I'm seeing the same issue as described in #85294 and it's been bothering me for a while so I'd like to gather as much info as possible here (that issue is locked).

### What I'm seeing

VSCode sometimes steels focus when I'm **switching between two other apps**, e.g., Chrome and Finder, and **VSCode is in another space** (screen / Mission Control space) – usually **full-screen** but I've seen it even with a normal windowed mode (but still in _another space_; that is important). It also seems to happening only when I have an **external monitor** connected – I haven't seen this behavior with a built-in display only.

Example scenario:

- I have VSCode in full screen mode on an external monitor.
- I have Finder in a normal windowed mode on that same external monitor (currently not visibile as I'm in the VSCode's space) and Chrome on the built-in display.
- I have a focus in Chrome and press `Cmd-Tab` to go to Finder.
- At this point, macOS triggers the transition to the desktop space on the external monitor but immediately after that, it starts transitioning back to the VSCode space. I'm seeing two subsequent "swipe" animations but the focus seems to be stolen by VSCode instead of being kept in Finder.
- At this point, pressing `Cmd-Tab` to go to finder again mostly fails again, but sometimes succeeds.
- Three-finger swipe is _usually_ a more reliable way to switch spaces but even there, I've seen situations where macOS immediately transitions me back to the VSCode space.

I have verified that the issue happens also with extensions disabled (I suspected it might be one of my many (30+) extensions I have installed but it's not the case).

### Could it be an Electron issue?

There's an issue "Electron apps steal focus" https://github.com/electron/electron/issues/12369 which might be the underlying cause. But that one also suffers from the lack of reliable repro steps.

### Could it be an iTerms issue?

I should note that I started noticing this issue since I upgraded to a larger monitor and started using VSCode side by side with iTerms in a [**split view**](https://support.apple.com/en-us/HT204948).

Signals that it could be iTerm:

- The order of icons in Cmd-Tab preview indicate that iTerms is the cause: instead of seeing `[Chrome] [Finder] [...the rest]` (expected MRU order), it's actually `[Chrome] [iTerm] [Finder]`.
- There's this issue: https://gitlab.com/gnachman/iterm2/issues/5260 and maybe even better, this one: https://gitlab.com/gnachman/iterm2/issues/3258.

Signals against iTerm:

- I'm pretty sure I specifically tested the behavior with iTerm closed and was still able to reproduce it. But I can't do it right now. (That's the problem with this issue, I don't know how to reliably reproduce it.)

**Comment by borekb** [comment]
I still don't know why or when this is happening but it's most probably **not** a VSCode issue: I've seen this with iTerm, Caret (Markdown editor) and other apps as well.

For anyone encountering this by googling, I unfortunately can't figure out when this happens, or what's causing it. It just seems to be related to:

- External monitor
- Split view
- Multiple spaces

**Comment by flehoux** [comment]
Have you figured anything out @borekb ? Use VSCode and iTerm in the same manner and havent been able to find a fix so far.

**Comment by borekb** [comment]
I've been trying to observe this carefully but still don't have a clue what's causing it. For a while, I thought it might be iTerm, see https://gitlab.com/gnachman/iterm2/issues/5260#note_307169088, but then, I reproduced it even with the built-in Terminal. I have also seen the issue with VSCode alone, after the other app was de-fullscreened and hence left the split view.

It's still a complete mystery to me and I don't even have a guess whether it's the apps causing it, or macOS itself.

But it's annoying as hell, I see it several times every day 😄.

**Comment by flehoux** [comment]
Guess we're on the same boat. This also happens with osx's Mail app, when a gmail account is linked. Not too sure what to be looking for 😆
