### ISSUE TITLE
Bigger terminal and unable to reduce size in Vertical mode

### ISSUE THREAD

**Issue by NathBabs** [microsoft/vscode#90681]
![split](https://user-images.githubusercontent.com/17989552/74522557-b2c22280-4f1b-11ea-8433-75c3a746f25d.PNG)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Snap to the right with Win + right
2.Right click on terminal tab and Move Panel to the Right

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by nikoladev** [comment]
For anybody else looking for the duplicate issue: #87347
