### ISSUE TITLE
Feature Request: Right Click -> Copy Path on file list

### ISSUE THREAD

**Issue by georgeedwards** [Microsoft/vscode#9068]
It would be really helpful to copy the path of a file. For example, if I search for something and a file is pulled up, with a long and complex path, it would be good to capture that, see below:

[![enter image description here][1]][1]

Being able to right click (ctrl + click on mac) on the file (which I am hovering over in the picture) and copy the file path would be really handy. 

  [1]: http://i.stack.imgur.com/hanic.png

**Comment by sandy081** [comment]
duplicates #8594
