### ISSUE TITLE
Mis-identify python script to CUDA file

### ISSUE THREAD

**Issue by innerlee** [microsoft/vscode#90689]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04.4 LTS

![image](https://user-images.githubusercontent.com/9464825/74530104-3c95de00-4f64-11ea-816f-e8978946ef34.png)

Does this issue occur when all extensions are disabled?: **No**

My proposal is: if the file does not contain extension and does contain shebang line, then respect the shebang indication.

**Comment by alexr00** [comment]
> Does this issue occur when all extensions are disabled?: No

VS Code doesn't have a build in CUDA grammar, so this must be coming from an extension. The extension causing this would need to make a change to fix it.

**Comment by innerlee** [comment]
Yes sure it is caused by extension. I uninstalled that extension because of this. But on the vscode side, my proposal was, vscode change the identification priority (for files without extension) so that the shebang line is respected (if exists).

**Comment by alexr00** [comment]
The shebang line is used for detecting that the language is python but if an installed extension overrides that, then we follow the installed extension. This is so that if you have a _better_ python extension than our built in one, you can get the benefits of that.
