### ISSUE TITLE
Reload window and recent workspaces overlap on keybindings

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#90698]
On the mac reload window is Cmd +R, and recent workspaces is Ctrl + R.
However on Linux and I guess Windows they overlap.
Can we change the default reload command to be Ctrl + K, Ctrl + R. Or fix this overlap in some other way?

![Screenshot 2020-02-14 at 15 25 10](https://user-images.githubusercontent.com/1926584/74539392-3bea5100-4f3e-11ea-8c26-40d309c86dd9.png)

**Comment by sbatten** [comment]
I've always used `Ctrl+Shift+R` for reload since it rarely conflicts with `Refactor` or quick open navigation.

**Comment by isidorn** [comment]
Yeah we could try that as the default.

**Comment by sbatten** [comment]
anyone opposed be me just making the swap?

**Comment by isidorn** [comment]
Well the current default behavior is that only in development we bind ctrl+R to reload.
I would check if our Win devs would be pissed by this change.
So I propose to have Ctrl+Shift+R for all builds, not only development. As you suggested.

**Comment by bpasero** [comment]
I actually run with this config for years and I am very happy with it, maybe we can make it the default:

macOS:
```json
 {
    "key": "cmd+shift+r",
    "command": "workbench.action.openRecent"
}
```

Linux/Windows:
```json
{
    "key": "ctrl+shift+r",
    "command": "workbench.action.openRecent"
}
```

**Comment by sbatten** [comment]
Customers will most likely be used to `Ctrl+R` for open recent than reload for our product so I would be more worried about changing that one.

**Comment by bpasero** [comment]
@isidorn I checked Windows and Linux and I see no conflict. 

**Windows:**
![image](https://user-images.githubusercontent.com/900690/74584149-4dc80480-4fcf-11ea-8d93-8030e12e874d.png)

**Linux:** I can use both Ctrl+R and Ctrl+Shift+R without issues.

Please clarify.

**Comment by isidorn** [comment]
@bpasero Yeah if there are no conflicts I would just push those as the defaults.

**Comment by bpasero** [comment]
Great. They are the defaults already.
