### ISSUE TITLE
Unable to load schema from ...

### ISSUE THREAD

**Issue by Coolkkmeat** [microsoft/vscode#90693]
Issue Type: <b>Bug</b>

# I will use Google Translate
# Questions are as follows
"Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': Unable to load schema from 'https://schemastore.azurewebsites.net/schemas/json/package.json': connect ETIMEDOUT 168.62.224.13:443."
# Details
When I am writing a Node (Electron) project, VSCode will prompt the content above. But I copied this URL into my browser and this URL can be opened.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (3.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|1.3.10
bracket-pair-colorizer|Coe|1.0.61
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.63072
vetur|oct|0.23.0
minapp-vscode|qiu|2.2.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.2
vscode-hexdump|sle|1.7.2
vscode-icons|vsc|9.7.0
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by aeschli** [comment]
Are you behind a proxy?

**Comment by Coolkkmeat** [comment]
> Are you behind a proxy?

Yes，v2ray，

**Comment by robjac** [comment]
happens when on a VPN/proxy

**Comment by chuhemiao** [comment]
close V2ray or ClashX etc

**Comment by chrmarti** [comment]
Does the proxy need authentication?

**Comment by Coolkkmeat** [comment]
> 代理需要认证吗？
