### ISSUE TITLE
Close node_modules after browsing files of some library

### ISSUE THREAD

**Issue by ironsoul0** [microsoft/vscode#90694]
Suppose I have this at the top of my `js` file:

`import { StaticQuery, graphql } from 'gatsby';`

Suppose I Cmd+LeftClick 'gatsby'. Then node_modules is revealed and I can browse gatsby source files.

When I close the file and want to proceed with code writing, the giant listing of node_modules folders is still there and it is really painful to scroll up and hide it every time

How about fixing this? Does anyone also feel pain with it?

**Comment by JacksonKearl** [comment]
You can collapse trees with left arrow, does that help?

**Comment by ironsoul0** [comment]
> You can collapse trees with left arrow, does that help?

The point is that I should scroll up an infinite number of folders to find that arrow and press it.

**Comment by JacksonKearl** [comment]
You can have focus on some deeply nested file, and repeatedly press left arrow to collapse upwards. You don’t need to first locate the uppermost directory.
