### ISSUE TITLE
Updates lock code.exe until reboot

### ISSUE THREAD

**Issue by jfarraraains** [microsoft/vscode#90699]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

We get notice of an update... and tell it to proceed. This has happen to our dev team on different machines and on home machines as well as work machines.

Issue Type: <b>Bug</b>

We get notice of an update... and tell it to proceed. This has happen to our dev team on different machines and on home machines as well as work machines.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.7.0
project-manager|ale|10.10.0
cucumberautocomplete|ale|2.14.1
gitstash|art|3.2.0
atlascode|atl|2.4.2
featurehighlight|Blo|1.7.1
gitignore|cod|0.6.0
vue-peek|dar|1.0.2
jenkins-runner|dav|1.2.2
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.0.15
daddy-jest|dev|1.0.0
git-extension-pack|don|0.1.3
githistory|don|0.5.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
auto-close-tag|for|0.5.6
restore-git-branch-tabs|gko|0.3.0
vscode-nginx-conf-hint|han|0.1.0
beautify|Hoo|1.5.0
rest-client|hum|0.23.1
compareit|in4|0.0.2
vscode-peacock|joh|3.3.1
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
chat|kar|0.31.0
openapi-lint|mer|1.0.4
vscode-docker|ms-|0.10.0
duffle-coat|ms-|0.3.4
duffle-vscode|ms-|0.3.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
csharp|ms-|1.21.11
vsliveshare|ms-|1.0.1615
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
vetur|oct|0.23.0
vscode-jest|Ort|3.1.1
vscode-coldbox|ort|0.1.0
vscode-testbox|ort|0.2.0
jenkins|p1c|0.1.0
jest-cucumber-code-generator-extension|pio|1.0.2
polacode|pnp|0.3.4
vscode-yaml|red|0.7.2
vue-vscode-snippets|sdr|1.8.0
gherkin-autocomplete|sil|1.3.3
bdd-highlighter|Tam|0.0.5
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

</details>

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.7.0
project-manager|ale|10.10.0
cucumberautocomplete|ale|2.14.1
gitstash|art|3.2.0
atlascode|atl|2.4.2
featurehighlight|Blo|1.7.1
gitignore|cod|0.6.0
vue-peek|dar|1.0.2
jenkins-runner|dav|1.2.2
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.0.15
daddy-jest|dev|1.0.0
git-extension-pack|don|0.1.3
githistory|don|0.5.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
auto-close-tag|for|0.5.6
restore-git-branch-tabs|gko|0.3.0
vscode-nginx-conf-hint|han|0.1.0
beautify|Hoo|1.5.0
rest-client|hum|0.23.1
compareit|in4|0.0.2
vscode-peacock|joh|3.3.1
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
chat|kar|0.31.0
openapi-lint|mer|1.0.4
vscode-docker|ms-|0.10.0
duffle-coat|ms-|0.3.4
duffle-vscode|ms-|0.3.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
csharp|ms-|1.21.11
vsliveshare|ms-|1.0.1615
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
vetur|oct|0.23.0
vscode-jest|Ort|3.1.1
vscode-coldbox|ort|0.1.0
vscode-testbox|ort|0.2.0
jenkins|p1c|0.1.0
jest-cucumber-code-generator-extension|pio|1.0.2
polacode|pnp|0.3.4
vscode-yaml|red|0.7.2
vue-vscode-snippets|sdr|1.8.0
gherkin-autocomplete|sil|1.3.3
bdd-highlighter|Tam|0.0.5
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by garciadev** [comment]
This happened to me too.

**Comment by JoeDickson** [comment]
Me too.

**Comment by garciadev** [comment]
I ended up rebooting my machine and then manually re-installing VC Code.

**Comment by joaomoreno** [comment]
What happened? Is there an error? Can you show me a screenshot?

**Comment by jfarraraains** [comment]
The error was the code.exe was locked. Once we reboot it releases the lock and we can either install or for a number of us, we can download VSCode again and install. The settings are still stored properly, just an issue with updates.

**Comment by joaomoreno** [comment]
What does the error look like? Is there a dialog?

**Comment by jfarraraains** [comment]
I don't remember specifically and apologize for that gap. I could use this approach but didn't.
https:\/\/www.windowscentral.com\/how-delete-locked-files-windows-10

**Comment by jfarraraains** [comment]
Let me reverse the question since more updates are coming... are there any log files or settings we could put into play to assist reproducing the issue?

**Comment by joaomoreno** [comment]
If there's an error dialog, it will point you to the log file. Let me know!
