### ISSUE TITLE
Git built-in extension does not work anymore if opening a .csproj file with Qub's XML Tools installed

### ISSUE THREAD

**Issue by borgdylan** [microsoft/vscode#90691]
- VSCode Version: 1.43-insiders
- OS Version: Ubuntu 19.10 x64 (Linux 5.5.3)

Steps to Reproduce:

1. Install Qub XML Tools extension
2. In a project under git version control, open its .csproj file
3. The git extension goes berserk or does not load

Workaround:

Uninstall or Disable Qub's XML Tools entirely

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Very likely https://github.com/danschultequb/qub-typescript-xml-vscode/issues/17
