### ISSUE TITLE
Hide "New File" icon in the top of Explorer

### ISSUE THREAD

**Issue by kiwenlau** [microsoft/vscode#90690]
I'd like to hide "New File" icon in the top of Explorer for 2 reasons:

- I never use it. 
- It blocks the project name(directory name), which is quite useful for me to distinguish different projects.

Actually, I want to hide everything but the project name...

<img width="304" alt="截屏2020-02-1420 50 59" src="https://user-images.githubusercontent.com/10240841/74533672-0ad54500-4f6d-11ea-9c6f-23f5100eeb41.png">

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by coderfin** [comment]
@kiwenlau This is now supported.  Right click to show and hide items.
