### ISSUE TITLE
Outline Fold button and Collapse All (sic) button icons are inconsistent

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90706]
The Outline tree's Fold button icon is (nonsensically) uses a down-pointing arrow whereas the Collapse All button's icon uses the conventional boxed '-' as per e.g. the documentation https://github.com/microsoft/vscode/issues/90705 and the File... dialog.

![image](https://user-images.githubusercontent.com/6157073/74545645-232f6a80-4f41-11ea-9ed8-e9f423d37bcf.png)

V1.42.1 on Windows 7.

Note: This should not be mistaken for a duplicate of https://github.com/microsoft/vscode/issues/89894 .

**Comment by misolori** [comment]
This is intentionally designed this way, as already mentioned in #89894, trees use `>` and collapsing multiple items typically use `[-]`. This also matches other paradigms in the Microsoft design system, like Outlook:

Collapse all icon
![image](https://user-images.githubusercontent.com/35271042/74558155-92439980-4f16-11ea-8847-bba3c682db39.png)


Folding tree
![image](https://user-images.githubusercontent.com/35271042/74558125-7e983300-4f16-11ea-89f0-c04e3fed99a4.png)

You might be interested in upvoting #79130, which will allow you to select a custom icon set for the workbench.

**Comment by chrisjj** [comment]
> This is intentionally designed this way, as already mentioned in #89894

Some mistake I think. #89894 does not mention that one uses an arrow and the other a boxed '-'.

> trees use `>` and collapsing multiple items typically use `[-]`. 

Thanks for the confirmation.
