### ISSUE TITLE
Source Control Pane Hide/Show Issues

### ISSUE THREAD

**Issue by aarondake** [microsoft/vscode#90708]
Issue Type: <b>Bug</b>

For some reason I can't get the "Source Control Providers" option to display (Source Control: Git).  Right-clicking the SC title bar and checking that option (SCP) doesn't seem to do anything.

Furthermore, unchecking an option appears to remove the option below it (if checked) instead of itself.  Perhaps there is an wrong-index issue here.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
I don't understand what you mean, can you please provide a [screen recording](https://getkap.co/)?

**Comment by betterthanclay** [comment]
I have seen this issue too, it appears to be caused the the customise-ui extension. Disabling this extension and reloading the monkey patch code causes the SCM side bar to function properly again.

I've created a new issue on the extension repo, here: https://github.com/iocave/customize-ui/issues/35
