### ISSUE TITLE
OOTB Command Palette offers many commands that do not exist

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90705]
1 Launch OOTB V1.42.1 on Windows 7.
2 In Command Palette attempt to execute Git: Open Checkout to...

![image](https://user-images.githubusercontent.com/6157073/74545053-1eb68200-4f40-11ea-9efa-f6b170c90e3f.png)

Expected: Git checkout dialog box
Observed:  "command 'git.checkout' not found". 
![image](https://user-images.githubusercontent.com/6157073/74545107-35f56f80-4f40-11ea-8a62-ddcee6c0a2b3.png)

**Comment by joaomoreno** [comment]
It seems that the Git extension is disabled. Can you check in the extensions panel? Can you check your user settings?

**Comment by chrisjj** [comment]
> It seems that the Git extension is disabled. Can you check in the extensions panel? Can you check your user settings?

As I said I'm using VS Code OOTB. I've made no change to extensions or extensions-related settings.

Have you tried this on an OOTB installation?

**Comment by joaomoreno** [comment]
Are there any other errors?

What does the Console show in `Developer: Toggle Developer Tools`?

**Comment by chrisjj** [comment]
> What does the Console show in `Developer: Toggle Developer Tools`?

**Comment by joaomoreno** [comment]
You seem not to have git installed.

You should've gotten a notification in the bottom right corner of the workbench saying that Code couldn't find `git.exe`. Did you get one?

**Comment by joaomoreno** [comment]
Nevertheless, the commands should not appear when git is missing, so I hid them in that case.

**Comment by chrisjj** [comment]
> You should've gotten a notification in the bottom right corner of the workbench saying that Code couldn't find `git.exe`. Did you get one?

No. Did you?

The only notification I got was the one I showed in the report.

> Nevertheless, the commands should not appear when git is missing, so I hid them in that case.

"In that case." Isn't the program supposed to hide inactive commands automatically in general?
