### ISSUE TITLE
Closing split view prompts to discard saved changes

### ISSUE THREAD

**Issue by mjohnsonengr** [Microsoft/vscode#9070]
- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open any file, make some changes to it (don't save)
2. Split the editor
3. Make more changes; close one of the splits and choose "Don't save" -- changes are reverted even though the file is still open and in plain sight.

It makes sense that the changes are discarded since I said Don't save, but it does not make sense that I should have been prompted that at all.

Don't quote me on this (I didn't test it) but I have a feeling this is a regression.  I feel like I've done this all the time.  I quickly tested by disabling tabs and still get the same result though.

**Comment by bpasero** [comment]
Sounds like https://github.com/Microsoft/vscode/issues/8983
