### ISSUE TITLE
Command Palette dialog box disappears when program loses focus

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90704]
1 Open Command Palette e,g,

![image](https://user-images.githubusercontent.com/6157073/74544209-ab604080-4f3e-11ea-835e-e97c46fb7c17.png)

2 Switch to another open program that does not cover this program's window

Expected: Command Palette still present
Observed: Command Palette gone.

Workaround: none known.

Likewise switching to a program that covers this program's window and swicthing back to this program finds the Command Palette gone. Workaround: reopen it, reeter your input, and repeat your navigation in the list.

V1.42.1 on Windows 7.

**Comment by chrmarti** [comment]
You can disable that in the settings:
![image](https://user-images.githubusercontent.com/9205389/74722750-bc0fff80-5239-11ea-8d2c-0b4c531a04c3.png)

**Comment by chrisjj** [comment]
Thanks for the workaround. I've added it to the report.

You closed this apparently in error. A workaround is not a fix.
