### ISSUE TITLE
Update fails to remove files in windows

### ISSUE THREAD

**Issue by mbourret** [microsoft/vscode#90702]
Issue Type: <b>Bug</b>

Visual Studio Code tries to update when I close it at the end of the day. It can't remove some files in the install directory in the resources folder because they have been locked. I believe it's because they are being used by a program based on my observations. When I reboot my machine Visual Studio Code is put into a state where it won't open from the usual shortcuts. I have to uninstall and re-install it. Then the issue happens all over again when it tries to update.

When I uninstall it, I am only able to remove the files from the install directory manually after uninstalling it and I have to do it early after a boot otherwise something opens/locks those files. I haven't pinned down exactly which program is doing it but It seems maybe a microsoft product like Teams or Onedrive. The install directory is not in a OneDrive folder, to be clear.

We are upgrading to newer dell laptops in our office and my co-worker is also seeing the same issue.

![Capture](https://user-images.githubusercontent.com/3497048/74542284-e6e01800-4f08-11ea-8517-9ef6290400fc.PNG)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|OS|Windows 10 Enterprise 64-bit (10.0, Build 18362)|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.5.0
prettier-vscode|esb|3.20.0
vscode-jest-runner|fir|0.4.15
sublime-babel-vscode|jos|0.2.10
remote-wsl|ms-|0.42.3
csharp|ms-|1.21.11
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by steve43276** [comment]
I am seeing the same issue since the 1.42 update.  Going through the same cycle of update and crash as described above.  The two files that get locked or corrupted are code.exe and codehelper.exe.  I have turned off auto updates to break the cycle until the issue is resolved.
