### ISSUE TITLE
Error in importing custom package: no name in module

### ISSUE THREAD

**Issue by shenxumingpy** [microsoft/vscode#90712]
The engineering structure is as follows:
Folder
    FolderA
        fileA
            from FolderB.fileB import XXX
            # Error here
            # no-name-in-module
    FolderB
        fileB
            class XXX():
                xxxx

Please help me,I'm a novice.How can I deal with this exception.
My mailbox:shenxuming@gmail.com

Thank you very much.Wish you good luck.

**Comment by shenxumingpy** [comment]
> The engineering structure is as follows:
> Folder
>     FolderA
>         fileA
>             from FolderB.fileB import XXX
>             # Error here
>             # no-name-in-module
> FolderB
>     fileB
>         class XXX():
>             xxxx
> 
> Please help me,I'm a novice.How can I deal with this exception.
> My mailbox:[shenxuming@gmail.com](mailto:shenxuming@gmail.com)
> 
> Thank you very much.Wish you good luck.

**Comment by shenxumingpy** [comment]
> windows 10
The engineering structure is as follows:
> Folder
> FolderA
> fileA
> from FolderB.fileB import XXX
> # Error here
> # no-name-in-module
> FolderB
> fileB
> class XXX():
> xxxx
> 
> Please help me,I'm a novice.How can I deal with this exception.
> My mailbox:[shenxuming@gmail.com](mailto:shenxuming@gmail.com)
> 
> Thank you very much.Wish you good luck.

**Comment by JacksonKearl** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
