### ISSUE TITLE
Disable interaction with popup for 250ms or so?

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#90718]
Accidentally hovering over something just long enough to trigger a popup which then gets directly in the way as I try to click something happens often enough that for the past few months it's made using VS Code a bit unpleasant. I propose that a simple 250ms delay before interaction is allowed with the popup at all would fix this. Perhaps even 100ms. Thank you for your time.

**Comment by ktex** [comment]
I'm following this thread, getting also a problem with that. 
The best would be a possibility to also desactivate the MDN Reference box.

**Comment by isidorn** [comment]
Please use the following setting to customise this behavior
	`"editor.hover.delay": 500`

If this does not help please search for open issues in the Hover area. Thus closing. Thanks
