### ISSUE TITLE
Apply debug console font size setting to input field

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#90714]
It's possible to adjust the debug console's font size via

```json
"debug.console.fontSize": 12,
```

This currently does not affect the input field as is obvious when cranking up the size to 20. Since the input is part of the debug console, I think it should though. 

![large-font](https://user-images.githubusercontent.com/30958850/74558869-fdaf5a80-4f5a-11ea-9886-78edb6fa25ba.png)

**Comment by isidorn** [comment]
I agree with you. `debug.console.fontSize` should also be aplied to the debug console input.
There might be some hard coded sizes that might not make this trivial to implement.

We are open to a PR that fixes this
https://github.com/microsoft/vscode/blob/6ec6f9e3f4d17f0cef0480688a1f350b9141e567/src/vs/workbench/contrib/debug/browser/repl.ts#L254

In the meantime assigning this to backlog as we might tackle this in the future.
Thanks

**Comment by isidorn** [comment]
To verify:
1. Start debugging and hit a brekapoint
2. Change `debug.console.fontSize` and make sure that the debug console input also respect the font size and that the input chevron looks good

**Comment by janosh** [comment]
Thanks for fixing this!

**Comment by isidorn** [comment]
@janosh you should thank @jeanp413 he fixed it nicely via a PR

**Comment by janosh** [comment]
Gave him a thumbs up over at #91261 first but also wanted to thank you for the quick merge and review.
