### ISSUE TITLE
SCSS formatter doesn't work anymore

### ISSUE THREAD

**Issue by mmswi** [Microsoft/vscode#9071]
- VSCode Version: 1.3
- OS Version: OS X El Capitan 10.11.5

Steps to Reproduce:

1. SHIFT + ALT + F in an SCSS file

Hello,

This was working before but not it stopped. Tried installing plugins, etc. Still nothing. 

Thanks

**Comment by kartheininger** [comment]
It is even not listed anymore when typing F1 and entering "Forma..."
That is one change related to the F1-key i found:
https://github.com/Microsoft/vscode/commit/c6456a0ab096798202cd7d2619df418a4b1d4ed9

**Comment by aeschli** [comment]
SCSS formatting is only provided by extensions. Which extension did you use?
Reason for the formatter not to work anymore has probably to do with the fact that the scss language id has changed (from sass to scss). I've pinged all SCSS extension writers that I found, to update their extensions. If you can tell me which extension you have used, I can contact them (again).

**Comment by mmswi** [comment]
hello aeschli, I'm using either https://marketplace.visualstudio.com/items?itemName=dbalage.vscode-stylesheet-formatter or https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint but nothing seems to work.

**Comment by aeschli** [comment]
Thanks for the pointers.
- https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint  seems to be updated to the new language id. If updating the extension doesnt help, then I suggest to file an issue directly at https://github.com/shinnn/vscode-stylelint/issues.
- For https://marketplace.visualstudio.com/items?itemName=dbalage.vscode-stylesheet-formatter I created a pull request. I hope the author can include the change soon and create a new update.
