### ISSUE TITLE
Shift-Insert to paste odd behavior

### ISSUE THREAD

**Issue by elucidsoft** [microsoft/vscode#90716]
I double checked my keymappings and they are all default.

If I copy text from something, then hit the following key sequences:

1. In target file: CTRL + A
2. Delete key or Backspace Key
2. Shift+Insert 

I would expect it to paste the contents of the clipboard into the file.  Instead what happens is somehow, the original contents of the file get restored in the file and the contents of the clipboard do not get pasted.

I can verify the contents of the clipboard are not replaced by right clicking in the file window and pasting and the text pastes as expected.

I can repeat this process over and over, I think it's a bug introduce recently as this behavior is relatively new.

**Comment by rebornix** [comment]
@elucidsoft could you share more info about your set up, like what OS, which version of VS Code you are using, what's the last version of VS Code you saw the right behavior?

**Comment by gjsjohnmurray** [comment]
If you are on Linux see #90222

**Comment by elucidsoft** [comment]
@gjsjohnmurray Yes I am on Linux, thank you!

**Comment by elucidsoft** [comment]
btw, my 2 cents, that's an awful default.

**Comment by alexdima** [comment]
This got changed in 1.42 for https://github.com/microsoft/vscode/issues/36170. There are two camps, one that wants shift+insert to paste the selection clipboard and another camp that wants shift+insert to paste the "clipboard" clipboard. We have chosen to align with the classical linux applications, like terminals, and have by default mapped shift+insert to paste the selection clipboard.

I am sorry about the disruption this causes if you have gotten used to the previous default behaviour.

There is a simple workaround available, you can map shift+insert back to pasting the "clipboard" clipboard, just add the following to your `keybindings.json`:

```
{
	"key": "shift+insert",
	"command": "editor.action.clipboardPasteAction",
	"when": "textInputFocus && !editorReadonly"
}
```
