### ISSUE TITLE
Debug empty viewlet has no padding

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#90717]
![image](https://user-images.githubusercontent.com/35271042/74560776-22381200-4f1c-11ea-84d1-b79a81082d93.png)

Possibly broken by @sbatten's change here https://github.com/microsoft/vscode/commit/5def21f51c58d6d3fc0bd9d4cbf85e6b3cc723f8?

**Comment by chryw** [comment]
I think it's just this one need to be renamed to `debug-pane`
https://github.com/microsoft/vscode/blob/1a5ffab445273820c35681c60656a7fcdfbe788c/src/vs/workbench/contrib/debug/browser/debugViewlet.ts#L86

**Comment by sbatten** [comment]
/duplicate @isidorn has already fixed for next build.
