### ISSUE TITLE
VSCode does not react to close when background tasks are pending

### ISSUE THREAD

**Issue by abergmeier** [microsoft/vscode#90724]
When background tasks are pending (in this scenario it was the Go plugin which went haywire) VSCode completely ignores all close signals (e.g. ALT+F4).

- VSCode Version: 1.42.0
- OS Version: Ubuntu 18.04

IMO no plugin or other part of VSCode should
a, do non-transactional longrunning tasks
b, have the power to "disable" close events

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
