### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by antoniorib91** [microsoft/vscode#90722]
Vscode is freezing with ts lang in ubuntu mate, I removed my vscode watch from node_modules, but sometimes freezing again.

**Comment by mjbvz** [comment]
Please fill out the issue template

/needsMoreInfo

Also, since this is a performance issue, please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by mjbvz** [comment]
Closing as not actionable without more info
