### ISSUE TITLE
Problem to show Arabic characters in ".bas" (VBA) files

### ISSUE THREAD

**Issue by imiimiimi** [microsoft/vscode#90723]
Issue Type: <b>Bug</b>

VSCode shows Arabic characters as unreadable characters after opening "**.bas**" files that exported by office VBA:
for example should be like this:
**`Range("tbl_P[گروه]")`**
but show this, if **disabled** "**Files: Auto Guess Encoding**":
**`Range("tbl_P[����]")`**
and show this if **enabled** "**Files: Auto Guess Encoding**":
**`Range("tbl_P[Ńćĺ]")`**

**Notes:**
- changed font to "**Courier New**" which office VBA used and support Arabic but it didnt fix problem
- **Notpad**, **WordPad**, **Notepad++** dont have this problem
- ".bas" files are **ANSI**
- my office is 2019 x64 and VBA is v7.1
- copy-past from Office VBA Editor has the same problem

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
