### ISSUE TITLE
VS Code Flutter starts in debug mode even though I started the app without debugging

### ISSUE THREAD

**Issue by raphtlw** [microsoft/vscode#90737]
Issue Type: <b>Bug</b>

1. On the top bar of VS Code, click the debug tab
2. Click run without debugging

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-markdownlint|Dav|0.34.0
xml|Dot|2.5.0
vsc-material-theme|Equ|32.4.0
prettier-vscode|esb|3.20.0
python|ms-|2020.2.63072
material-icon-theme|PKi|3.9.3
java|red|0.55.1
LiveServer|rit|5.6.1
relative-line-height|use|1.0.2
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-todo-highlight|way|1.0.4

(11 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report on Flutter extension repo.

**Comment by raphtlw** [comment]
@gjsjohnmurray Done
