### ISSUE TITLE
Red alert

### ISSUE THREAD

**Issue by Rifai514** [microsoft/vscode#90738]
I have the wrong script where it raises a red mark but after I fix it the red mark stays and doesn't disappear

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including VSCode version, platform, language you are scripting in, what extensions you are using, and simplest possible steps to reproduce the issue.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including VSCode version, platform, language you are scripting in, what extensions you are using, and simplest possible steps to reproduce the issue.

**Comment by Rifai514** [comment]
it was already gone when I restart the vs code

**Comment by gjsjohnmurray** [comment]
Unless you plan to try and recreate this issue and post more info please close it.
