### ISSUE TITLE
Typescript and js language features extension

### ISSUE THREAD

**Issue by LeTanque** [microsoft/vscode#90735]
Issue Type: <b>Bug</b>

Opened up a super basic knexfile and the popup started freaking out

```
// Update with your config settings.

module.exports = {

  development: {
    client: 'sqlite3',
    connection: {
      filename: './src/data/zicka.sqlite3'
    },
    migrations: {
      directory: './src/data/migrations',
      tableName: 'knex_migrations',
    },
    seeds: {
        directory: './src/data/seeds',
    },
    useNullAsDefault: true,
  },

  production: {
    client: 'sqlite3',
    connection: {
      filename: './src/data/zicka.sqlite3'
    },
    migrations: {
      directory: './src/data/migrations',
      tableName: 'knex_migrations',
    },
    seeds: {
        directory: './src/data/seeds',
    },
    useNullAsDefault: true,
  }

};
```

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
python-quick-print|Aha|0.2.0
vscode-sqlite|ale|0.8.1
vscode-apollo|apo|1.14.1
cobol|bit|6.0.12
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
console-log|dot|0.6.2
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
vscode-pull-request-github|Git|0.14.0
vscode-styled-components|jpo|0.0.28
solidity|Jua|0.0.70
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|1.5.0
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
python|ms-|2020.2.63072
Go|ms-|0.13.0
vsliveshare|ms-|1.0.1615
material-icon-theme|PKi|3.9.3
prisma|Pri|0.0.22
better-less|rad|0.5.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vscode-npm-scripts|tra|0.2.1
quokka-vscode|Wal|1.0.277

</details>

**Comment by JacksonKearl** [comment]
What do you mean by "the popup started freaking out"?

**Comment by LeTanque** [comment]
Sorry, should have been more clear. 

What I mean is the small popup window on the bottom right of the screen opened up, then closed, opened up, then closed and kept doing that until I closed the knexfile.js.

The popup had `TypeScript and JavaScript Language Features` in the title.

What I did to address the issue locally:
Closed the knexfile. Closed vscode; completely quit. Then opened again, open a new workspace with only that repo. 

Then, popup freak out happened again, accept this time it flashed a different popup first, but only the once. I didn't notice it before. A graphql extension I had installed, by "Maxime Quandalle". 

I disabled the graphql extension and everything works normal now.

Link to the repo that produced the problem:
https://github.com/LeTanque/next-portfolio-v2

**Comment by mjbvz** [comment]
Does not repo for me in insiders or stable with that project

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
