### ISSUE TITLE
Outline view is missing the keyboard command to just move the editor to the current a symbol

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90732]
1 In Outline View, mouse-click on a symbol e.g,.
![image](https://user-images.githubusercontent.com/6157073/74577695-69f48300-4f88-11ea-86a2-14cc7bda4198.png)
2 See the editor moves to that symbol
3 Press Down Arrow to move to another symbol.
4 Try to find a keypress that just moves the editor to that symbol.

Expected: success
Observed: failure, here. There's none I can find by experiment or reading docs. The nearest is Enter, but that also switches focus away.

Check the Command Palette. Neither this or any other commands to operate Outline View are present.

V1.42.1 on Windows.

**Comment by lambainsaan** [comment]
@jrieken I am working on this.

**Comment by jrieken** [comment]
code pointer: https://github.com/microsoft/vscode/blob/a1f61fd0fec2e3dbe159264f4b69148554fcbfd9/src/vs/workbench/contrib/outline/browser/outlinePane.ts#L580

Something similar for focus events is needed

**Comment by bpasero** [comment]
**Verification:** bind a key to the new `list.selectAndPreserveFocus` command to verify this ask.

**Comment by isidorn** [comment]
This does not really work in Outline, however it works just fine in other views. For example in the References view and the explorer.
However since the original ask was for Outline I am reopening this.

**Comment by bpasero** [comment]
@jrieken the only reason this does not work is this code:

https://github.com/microsoft/vscode/blob/85d3eb2c644aa8253f529ba73e2071e2d23da194/src/vs/workbench/contrib/outline/browser/outlinePane.ts#L567

If I remove `|| !!e.editorOptions.pinned` it works fine. What is the rationale?

**Comment by jrieken** [comment]
> What is the rationale?

idk @joaomoreno added this via `bb5b4e9a22ab73f0b85a73bef3c774944080cc2c`

**Comment by joaomoreno** [comment]
Yeah definitely an issue with https://github.com/microsoft/vscode/commit/bb5b4e9a22ab73f0b85a73bef3c774944080cc2c

With the fix, `list.selectAndPreserveFocus` should now work.

**Comment by bpasero** [comment]
Thanks!
