### ISSUE TITLE
Program fails to respect Windows desktop theme

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90731]
1 Launch the program

Expected: windows respected desktop theme.
Observed: program completely ignores desktop theme.

E.g. compared to Notepad: 
![image](https://user-images.githubusercontent.com/6157073/74593436-3a468900-5023-11ea-8ac6-44a22a9f81b4.png)

V1.42.1 on Windows 7.

**Comment by misolori** [comment]
Can you give more information about what desktop theme you are using and what user settings you have configured?

**Comment by chrisjj** [comment]
> Can you give more information about what desktop theme you are using 

This issue is not specific to any one theme. It

> and what user settings you have configured?

I know of no Windows settings that affect this and I have no relevant VS Code settings configures to my knowledge.

**Comment by misolori** [comment]
I’m still not understanding the problem. Are you expecting VS Code to inherit the system theme like dark/light mode? Or is this something else?

**Comment by chrisjj** [comment]
>Are you expecting VS Code to inherit the system theme like dark/light mode?

Yes. Like all well-behaved Windows programs.

**Comment by misolori** [comment]
This is a new feature that was just released in 1.42, please enable the `window.autoDetectColorScheme` setting in your users settings. See our [release notes](https://code.visualstudio.com/updates/v1_42#_auto-switch-theme-based-on-os-color-scheme) for more info.

**Comment by chrisjj** [comment]
> This is a new feature that was just released in 1.42

I take it "this" refers to respecting Windows desktop theme.

> please enable the `window.autoDetectColorScheme` setting in your users settings. See our [release notes](https://code.visualstudio.com/updates/v1_42#_auto-switch-theme-based-on-os-color-scheme) for more info.

Thanks. That doesn't say how to enable this setting so I guessed:

![image](https://user-images.githubusercontent.com/6157073/74733244-d8b13500-5243-11ea-9fdc-bad923ff0970.png)

but this had no effect. Even after restart.

**Comment by misolori** [comment]
Here's an example showing how this works, notice that after you enable `window.autoDetectColorScheme` when you switch desktop themes (light/dark) the editor also changes.

![Kapture 2020-02-18 at 21 58 45](https://user-images.githubusercontent.com/35271042/74806091-e396b480-5299-11ea-9eb6-b0d63ded359a.gif)

**Comment by chrisjj** [comment]
Switching light/dark does not equal respecting the desktop theme.

**Comment by misolori** [comment]
If you are wanting the native title bar menu like below, please set `window.titleBarStyle` to `native`:

![image](https://user-images.githubusercontent.com/35271042/75077973-2bdfed80-54b9-11ea-8002-435d50fb7eb6.png)

That's the closest that you can get to your screenshot of notepad. Hope that helps.

**Comment by chrisjj** [comment]
> That's the closest that you can get to your screenshot of notepad. 

Thanks for the confirmation of this issue.
