### ISSUE TITLE
Code line splitted wrongly

### ISSUE THREAD

**Issue by ktex** [microsoft/vscode#90739]
Issue Type: <b>Bug</b>

Hi, 

I don't know how to describe it, so I link a picture here, it will be easy to understand.

[https://i.ibb.co/582VLGC/vsc.png
](url)
As the best, I would like to choose where to split it. Or at least use the maximum lengh.

Thanks

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by JacksonKearl** [comment]
Does this reproduce in a monospaced font?

**Comment by alexdima** [comment]
@ktex It appears you are using a non monospace font. Please use `"editor.wrappingStrategy": "advanced"`
