### ISSUE TITLE
Firstline not working

### ISSUE THREAD

**Issue by sasial-roblox** [microsoft/vscode#90740]
Issue Type: <b>Bug</b>

---
I am making an extension and firstline does not work.
When I add
```json
{
"firstLine": "-- #\/Teverse"
}
```
to my package.json, it won't work.
The first line of the file is:
```lua
-- #/Teverse
```
in test.lua

---
The workaround for this is if I set add:
```json
{
    "extensions": [
        ".lua"
    ],
}
```
to package.json. But, every lua file has the custom language.

---
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.22.3
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.0.15
vscode-npm-script|eg2|0.3.11
vscode-rojo|eva|1.11.1
glitch|gli|0.1.5
beautify|Hoo|1.5.0
discord-vscode|icr|3.13.0
path-autocomplete|ion|1.13.3
vscode-peacock|joh|3.3.1
chat|kar|0.31.0
electron-debug|kod|18.11.1
remote-wsl|ms-|0.42.3
vsliveshare|ms-|1.0.1615
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.0
LiveServer|rit|5.6.1
ejs-snippets|Tao|0.1.0
vscodeintellicode|Vis|1.2.5
vscode-icons|vsc|9.7.0

</details>

**Comment by sasial-roblox** [comment]
See https://regex101.com/r/ryzHjf/1 for regex info.

**Comment by alexdima** [comment]
@sasial-roblox  That works for me.

When using:
```js
"contributes": {
    "languages": [
      {
        //...
        "firstLine": "-- #\/Teverse",
      }
    ]
}
```

And opening a file *with an unknown extension*, like `test.tssss` with the contents:
```
-- #/Teverse

This is interesting
```

The file is associated with the language I have chosen. Do you perhaps try to open a file with a file extension that is defined by another extension?

**Comment by sasial-dev** [comment]
Yeah.
I'm doing `.lua`, so it is overwritten by lua.
Is there anyway to get around that?

**Comment by sasial-dev** [comment]
@alexdima 
Yeah.
I'm doing `.lua`, so it is overwritten by lua.
Is there anyway to get around that?

**Comment by sasial-dev** [comment]
Also,
If there an activation event for on save?

**Comment by alexdima** [comment]
@sasial-dev No, extension matches get higher priority. First line matches are only considered if a file is not recognized by its filename. You can write an extension and change the language of the lua documents after they have been opened.
