### ISSUE TITLE
Macbook Pro touch bar not working

### ISSUE THREAD

**Issue by danielwpz** [microsoft/vscode#90745]
- VSCode Version:  1.42.1
- OS Version: Mac OS 10.15.1

Steps to Reproduce:

1. I'm using a macbook pro with touch bar, and my touch bar doesn't work with the latest update of vscode. However, other apps don't have this problem at the same time.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!

**Comment by bpasero** [comment]
I cannot reproduce, it is possible that maybe you have configured something wrong in macOS settings that would show other keys than the app keys.

**Comment by danielwpz** [comment]
hey I think it's vim extension. I re-installed it and it started to work now. thanks
