### ISSUE TITLE
When setting new TypeScript version expected DOM lib no longer available 

### ISSUE THREAD

**Issue by David-Else** [microsoft/vscode#90747]
Issue Type: <b>Bug</b>

Enable TS 3.81rc from global install in `settings.json`
```
  "typescript.tsdk": "/home/david/.nvm/versions/node/v12.15.0/pnpm-global/3/node_modules/typescript/lib",

```
Select inside the project to use that clicking bottom right 'use vs codes version 3.81rc...'

Non of the DOM elements are available any more, they all have red squiggles under them.
```
const canvas = document.getElementById("game-canvas");
assert(
  canvas instanceof HTMLCanvasElement,
  `Element is null/undefined or not a HTMLCanvasElement.`
);
```
`document` and `HTMLCanvasElement` are red squiggles

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.18.0-147.5.1.el8_1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|7.50GB (0.29GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-deno|axe|2.0.0
spellright|ban|3.0.50
markdown-preview-github-styles|bie|0.1.6
vscode-eslint|dba|2.0.15
prettier-vscode|esb|3.20.0
shell-format|fox|7.0.1
debugger-for-chrome|msj|4.12.6
LiveServer|rit|5.6.1
shellcheck|tim|0.9.0
quokka-vscode|Wal|1.0.277

</details>

**Comment by mjbvz** [comment]
Works for me using TS 3.8.1rc

Could be pnpm related? What if you install that typescript version into the workspace and try using that instead?

**Comment by David-Else** [comment]
I now think it is related to the Deno extension and have reported it there. Cheers, will close this.

**Comment by David-Else** [comment]
@mjbvz It was the Deno extension, and the author needs help with a certain bit of information to fix it. If you could spare a moment to help him it would be great :)

https://github.com/axetroy/vscode-deno/issues/60

https://stackoverflow.com/questions/60087597/how-to-trigger-typescript-recompilation-within-extension
