### ISSUE TITLE
Zoom + not working when I preview file

### ISSUE THREAD

**Issue by thinkermao** [Microsoft/vscode#9074]
- VSCode Version: 1.3.0
- OS Version: Win10

Steps to Reproduce:

1.  Open a md file, edit, and zoom + Editor
2.  OpenPreview

![image](https://cloud.githubusercontent.com/assets/7908062/16734118/ee0f727c-47b6-11e6-9b5b-491d50aa1c8a.png)

**Comment by bpasero** [comment]
#5745
