### ISSUE TITLE
For current terminal session, 'Environment Variable' blade is needed to understand the environment contexts.

### ISSUE THREAD

**Issue by enihcam** [microsoft/vscode#90744]
When a terminal is opened, it would be good to see _Environment Variable_ blade in VSCode Explorer. This would help me quickly understand the environment contexts of the current terminal session.

**Comment by Tyriar** [comment]
You can view what the environment was when the terminal was launched by enabling trace logging and viewing the log: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
