### ISSUE TITLE
showInlineBreakpointCandidates doesn't work

### ISSUE THREAD

**Issue by icetbr** [microsoft/vscode#90749]
Steps to Reproduce:
- set  "debug.showInlineBreakpointCandidates": false
- create a test.js file
- declare an object
- add a breakpoint
- run debug (F5)

![breakpoint](https://user-images.githubusercontent.com/1111617/74587092-18221c00-4fcd-11ea-829d-be6c6413c0cb.png)

Tested on a new installation, no special configs or extensions. Also tested on 1.42 on Linux.

Version: 1.43.0-insider
Commit: 4c9161a3f125f5a788aafa73a4ecfcb27dcfc319
Date: 2020-02-14T05:34:36.456Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
This is expected behabior. breakpointCandidates are "gray breakpoint locations". Turning the setting off disables those.
What you want to disable are column breakpoints which we do not support disabling.
It is up to the debug extension to move a breakpoint wherever it wants and in this case it moves it inside the line. Thus closing as designed.
