### ISSUE TITLE
In Markdown "-", Multi-cursor + Enter does not meet expectations

### ISSUE THREAD

**Issue by faydanube** [microsoft/vscode#90748]
Eg
- AA BB CC
Multi-cursor + Enter
- AA
- BB CC

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
