### ISSUE TITLE
Springboot Symbol are not getting recognise 

### ISSUE THREAD

**Issue by gnumonk** [microsoft/vscode#90741]
<img width="382" alt="Screenshot 2020-02-15 at 10 45 06 AM" src="https://user-images.githubusercontent.com/1131808/74582557-c0db7600-4fe3-11ea-9c3d-cd0a8ef93050.png">

SpringBoot Symbols are not getting recognized, for example, @SpringBootApplication, though when you look for definitions, file SpringBootApplication.class will be open.

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JacksonKearl** [comment]
This looks like an issue with the Java extension rather than VS Code core. Please file at https://github.com/redhat-developer/vscode-java, or whatever extension you use for Java.
