### ISSUE TITLE
Broken Markdown Syntax Highlighting since 1.3.0

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#9075]
EDIT: most of these issues appear to be from 1.3.0. If I try the same files in an earlier version of code, they look closer to those in the atom examples. I added a pre 1.3.0 VSCode image to example 2. None of the other issues such as bold, italics, html, code blocks, or anything else have issues in earlier versions. These all seem to have been introduced recently when making markdown its own language I am guessing.

I use markdown for writing documentation and blog posts, and this is the one thing keeping me from 100% moving to VSCode. The syntax is so poor that I have to continue using atom for things like blog posts, which is ironic since half my posts these days are about VSCode. I am adding a few pictures to show how bad VSCode is in comparison to Atom and point out some of the areas that need improvement.
## Example 1

VSCode
![vscodemarkdown](https://cloud.githubusercontent.com/assets/6662208/16732906/e9226dd6-4744-11e6-8309-9a542d6b88ce.png)
Atom
![atommarkdown](https://cloud.githubusercontent.com/assets/6662208/16732930/043b1096-4745-11e6-815c-ecb307e3531d.png)
## Example 2

VSCode Pre 1.3.0
![image](https://cloud.githubusercontent.com/assets/6662208/16735454/b49cfdc4-474e-11e6-875c-dd1744a8e80f.png)
VSCode
![vscodemarkdown2](https://cloud.githubusercontent.com/assets/6662208/16732953/10a011f6-4745-11e6-87a7-c69dbeee6574.png)
Atom
![atommarkdown2](https://cloud.githubusercontent.com/assets/6662208/16732964/1a270522-4745-11e6-9ba2-18dcc22fc320.png)

You get the same poor results in pretty much every theme. 

A few of the issues that stand out:
- adding bold or italics to a list breaks the coloring.
  ![bolditalics](https://cloud.githubusercontent.com/assets/6662208/16733515/7c2a2fea-4747-11e6-9a8b-05ce0673bbca.png)
- Lists should appear like Atom with only the bullet being colored as seen in example 2 above.
- Lists for sections like Jekyll blogs should properly highlight similar to Atom.
  ![atomlistjekyll](https://cloud.githubusercontent.com/assets/6662208/16733658/147b92c0-4748-11e6-98d9-45b99adb6835.png)
  ![listjekyll](https://cloud.githubusercontent.com/assets/6662208/16733665/18d6b73c-4748-11e6-9e8a-760d2af5a802.png)
- Having multiple bold or italics words in the same line breaks the rest of the document.
  ![vscodehtml](https://cloud.githubusercontent.com/assets/6662208/16733830/c2a91d9a-4748-11e6-8ae6-c934f0e36b7a.png)
  ![atomhtml](https://cloud.githubusercontent.com/assets/6662208/16733833/c58f1b54-4748-11e6-96ed-3cb465e6310f.png)
- Small amounts of html like <kdb> it can't handle if in a list
  ![vscodehtmllist](https://cloud.githubusercontent.com/assets/6662208/16733951/4dc39608-4749-11e6-9971-ceef68976b3c.png)
- Lists break any syntax coloring in the line.
  ![atomsyntaxlist](https://cloud.githubusercontent.com/assets/6662208/16734057/bb391c94-4749-11e6-9efb-36a3b17d9ed7.png)
  ![vscodesyntaxlist](https://cloud.githubusercontent.com/assets/6662208/16734071/c7d1bcb8-4749-11e6-915a-8f0ad6b9a734.png)

There are likely some other issues, but they are escaping me right now. I will try to update this if I can remember any others.
- VSCode Version: 1.4.0-insider
- OS Version: Windows 10

Steps to Reproduce:
1. Compare 2 theme between Atom and VSCode

**Comment by gerane** [comment]
These seem more like issues in the language\tmlanguage and not simple theme\tmtheme issues. Every single theme has these issues that I have tried. While Dark and Dark+ may have fixed the bullet part, all of the other issues are still present.

**Comment by gerane** [comment]
I edited the original post, I hadn't used code for markdown in a while and was attempting to finally switch. It appears the syntax for markdown used to be pretty decent, but some recent changes have made it terribly broken. To the point it is unusable for me. I checked an older version of code and the syntax works just fine. None of the issues highlighted here were issues in the earlier version.

**Comment by MovGP0** [comment]
Here is a nice example with a table and escaped regex that is broken: 

;proper highlighting in Github
```markdown
### regular expressions

<table>
<tbody>
<tr><td>`^`</td><td>Begin</td></tr>
<tr><td>`$`</td><td>End</td></tr>
<tr><td>`.`</td><td>any character</td></tr>
<tr><td>`[A-Z]`</td><td>range</td></tr>
<tr><td>`\d`</td><td>digit</td></tr>
<tr><td>`?`</td><td>0 or 1</td></tr>
<tr><td>`+`</td><td>1 or more</td></tr>
<tr><td>`*`</td><td>0 or more</td></tr>
<tr><td>`[^a]`</td><td>except a</td></tr>
<tr><td>`\\`</td><td>escape sequence</td></tr>
<tr><td>`\w`</td><td>whitespace</td></tr>
<tr><td>`\s`</td><td>space</td></tr>
</tbody>
</table>
```

; broken highlighting in Code 
![regex in table](https://cloud.githubusercontent.com/assets/83339/16738205/07ce3382-4795-11e6-9c63-70785f3b542d.png)

; broken rendering in Code 
![regex in table preview](https://cloud.githubusercontent.com/assets/83339/16738206/07cef47a-4795-11e6-9d39-2299a431f844.png)

**Comment by MovGP0** [comment]
seems like the [Markdown plugin](https://github.com/Microsoft/vscode/tree/8b60f07f6912b63fe5bae9a70d75cbce30437582/extensions/markdown) uses [markdown-it](https://github.com/markdown-it/markdown-it) for markdown rendering and [highlight.js](https://highlightjs.org/) for syntax highlighting of code blocks. it delegates the view of markdown sourcecode to the text editor of code. so its probably not an issue of the extension.

**Comment by gerane** [comment]
ref #8214

**Comment by gerane** [comment]
Any updates on this?

**Comment by mjbvz** [comment]
@MovGP0 The syntax highlighting of your examples seems to have been fixed:

![screen shot 2016-11-11 at 2 33 59 pm](https://cloud.githubusercontent.com/assets/12821956/20232275/e9f1533e-a81b-11e6-8cf7-2e87f8530a53.png)

The renderer uses commonmark, which [does not yet support tables in markdown](
https://talk.commonmark.org/t/tables-in-pure-markdown/81/104), so the second example is rendered incorrectly.

Please give the latest insiders builds a try and open bugs for any issue you notice. Thanks.

**Comment by mjbvz** [comment]
@gerane Can you please try out the latest insiders builds to see what has been fixed. We've made a number of fixes to the markdown grammar, and these may resolve many of problems you were seeing.

I'm going to close this issue, but if you are still seeing any syntax highlighting problems, please open new issues for these (smaller issues are generally better). Please include the markdown source to help with investigation and testing. Thanks
