### ISSUE TITLE
Debugging stops working

### ISSUE THREAD

**Issue by Hernan0728** [microsoft/vscode#90756]
Issue Type: <b>Bug</b>

In any script, 
1. start a debugging session
2. Use the debugging tools (Step over, step into, etc).
3. At some line (random) it stops working. 

# You can still use the STOP button to stop the debugging session, but the cursor won't advance with any of the other debugging controls.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.7.2
abaqus|JP|1.0.0
linter-gfortran|krv|2.1.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.63072
cpptools|ms-|0.26.3
vscode-yaml|red|0.7.2
material-theme|zhu|3.2.2

(2 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!

**Comment by joltman61** [comment]
I am experiencing the same behavior. During a current debug session, I will be stepping through the code fine and then have all of the run / step options stop working.  I have not seen any outward failure indication.  I had thought I might be tying to step too quickly.  I have not seen the issue when running between breakpoints.  The Call Stack will indicate PAUSED ON STEP.

**Comment by JacksonKearl** [comment]
@joltman61 please file against the Python extension. They'll be more able to help, as they control that debugger.
