### ISSUE TITLE
Semantic colors don't go away when toggling comments

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90754]
cmd+/ in a TS file:

![Kapture 2020-02-15 at 5 32 00](https://user-images.githubusercontent.com/2193314/74588826-945c3580-4fb4-11ea-889d-7cf6d7091a2c.gif)

Version: 1.43.0-insider
Commit: 4c9161a3f125f5a788aafa73a4ecfcb27dcfc319
Date: 2020-02-14T05:26:38.779Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

**Comment by alexdima** [comment]
@Tyriar If you toggle line comments and just wait until the language server has a chance to compute them, do they repair themselves?

The editor does not synchronously remove those semantic tokens. This is explained in #89640 , as the editor sees an insertion for `//` and does not understand that that is different than an insertion of `aa` for example. 

But things should heal themselves after the new semantic tokens come in. Do things correct themselves given sufficient waiting time?

**Comment by Tyriar** [comment]
I waited a good 5-10 seconds and no change happened. Normally the tokens go away after 500ms or so but not so when I was seeing this.

**Comment by alexdima** [comment]
Are there some reproducible steps? I can then imagine that semantic tokens was permanently broken for this file?

**Comment by Tyriar** [comment]
I can't reproduce it anymore, feel free to close. Would this maybe be the fault of the TS extension?

**Comment by alexdima** [comment]
:+1: I think so, if `tsserver` is unhealthy, semantic tokens will be unhealthy. Please reopen if you find steps, it would also be interesting if you could check when this happens if intellisense / hovers / etc still work.
