### ISSUE TITLE
Menu bar color has changed to light blue

### ISSUE THREAD

**Issue by gahisee** [microsoft/vscode#90759]
Issue Type: <b>Bug</b>

The main menu bar has changed its background to white and
foreground to pale blue, nearly invisible. This is new with the latest update and irrespective of color themes.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3780)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|23.41GB (15.48GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
java|red|0.55.1
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-maven|vsc|0.21.0

(2 theme extensions excluded)

</details>

**Comment by xTibor** [comment]
I'm also started suffering from this after the latest update (c47d83b293181d9be64f27ff093689e8e7aed054). Here's a screenshot how it looks under KDE:
![Screenshot_20200216_050458](https://user-images.githubusercontent.com/1627292/74599059-6fcb9080-507c-11ea-97ce-3735f17c9bd5.png)

**Comment by gjsjohnmurray** [comment]
Does the problem also occur if you launch code.exe with the `--disable-gpu` switch?

**Comment by xTibor** [comment]
@gjsjohnmurray Still occurs with `--disable-gpu`, it doesn't make a difference.

**Comment by xTibor** [comment]
Found the root cause: The menubar mixes the system titlebar font color with the system window background color. Semantically incorrect color pairing.

**Comment by xTibor** [comment]
Turns out it was a KDE GTK theme bug in my case that has been fixed last week: https://phabricator.kde.org/D27390 They are planning to release the fix in Plasma 5.18.1.

@gahisee Do you also encountered this with KDE? If so, I think this issue could be closed.

**Comment by gahisee** [comment]
yes, KDE 5.18.0.
