### ISSUE TITLE
Improve module import in Typescript

### ISSUE THREAD

**Issue by kresdjan** [microsoft/vscode#90764]
VSCode isn't being helpful or not picking up on modules when trying to import them. Take a fresh Angular project as an example. It imports BrowserModule `import { BrowserModule } from '@angular/platform-browser';` as default. But if I also want to import the `BrowserAnimationsModule` located in `@angular/platform-browser/animations` already installed in the node_modules folder. Shouldn't VSCode auto-import that module if I add `BrowserAnimationsModule` to the imports array, or at least prompt me?

```.ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I apologise if this is way off. In my mind VSCode should know that module exists.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature an issue upstream](https://github.com/microsoft/TypeScript/issues/new/choose) for this
