### ISSUE TITLE
Even edited tabs I want to stay open go to "temporary" status and get closed if I open something else.

### ISSUE THREAD

**Issue by Muzical84** [Microsoft/vscode#9076]
- VSCode Version: 1.3.0
- OS Version: Win7 Enterprise x64

Steps to Reproduce:

1.  Have tabs opened.  Edit them so the tab title should not be italics.
2.  Open something else, breathe, anything, click out and back in to a window, etc., and magically the tab you have focused now has an italics title and if you don't notice right away and open something else, the italics-titled tab naturally goes away.  (I honestly spent most of Friday trying to figure out a reason or rhyme for what triggers this bug, but I have no idea.)

This wouldn't be annoying if I didn't have gigantic PHP files I'd just spent a long while collapsing stuff on so I could scroll it easier; I have to re-do that every time I have to reopen the file.  It's frustrating enough to make me consider going back to Sublime :(

**Comment by bpasero** [comment]
@Muzical84 can you provide steps? btw you can disable the preview feature altogether setting `"workbench.editor.enablePreview": false`

Still what you describe sounds like a major bug.

**Comment by Muzical84** [comment]
@bpasero I honestly can't find a concrete set of circumstances that makes this happen; it just "does," and as a dev myself I do know that's not what anyone wants to read.  I do have two separate windows open, if that helps, and both have PHP git repos open.

I'll turn off previews in preferences for now; I'd forgotten I could do that.

**Comment by bpasero** [comment]
@Muzical84 could it be you have the same file open in 2 windows? we do not share the preview state across windows nor editor groups (if you open side by side)

**Comment by Muzical84** [comment]
No, these are two separate folders.

**Comment by bpasero** [comment]
Ok let me know if you found out anyhow to reproduce.
