### ISSUE TITLE
`cmd+p` File Opener shows old names of renamed files

### ISSUE THREAD

**Issue by kortina** [microsoft/vscode#90761]
- VSCode Version: 1.42.0
- OS Version: Mac OS X 10.15.3 (19D76)

Steps to Reproduce:

1. Right click on a file in the File Explorer and choose `rename`. Make sure this is a file that you have opened several times using the `cmd+p` shortcut in the past
2. Change filename from `file-1.txt` to `file-2.txt`
3. `cmd+p` and type "file"

`file-1.txt` still shows up.

Here is example where I changed typo in filename, `berkley-forum-2020.md` → `berkeley-forum-2020.md` and typing "berk" still shows the old filename:

![example](https://s3.amazonaws.com/4rk/screen-shot-2020-02-15-09.09.44-znd8rujm.png)

Does this issue occur when all extensions are disabled?: Yes.

The problem also persists upon a quit + relaunch of vscode.

**Comment by josmithua** [comment]
I've noticed this issue on my mac for a while now.

**Comment by bpasero** [comment]
I just tried and cannot reproduce. I am using the explorer to rename a file and the history shows the renamed file properly. 

I am probably missing a specific step that you people do that I do not do, so maybe be more specific or show a screencast.

**Comment by kortina** [comment]
Hmm, this is very odd, I am trying to duplicate again for screencast and it is no longer happening. The static screenshot I took above exhibits the behavior but I can no longer replicate...
