### ISSUE TITLE
The Remote - WSL Plug-in Caused Some Code Highlighting to Fail

### ISSUE THREAD

**Issue by zhao170628** [microsoft/vscode#90768]
After opening the C + + Code in WSL, some of the variable and data type names in the code are not highlighted, but are returned to normal when opened again under Windows.

- Version: 1.42.1 (user setup)
- Electron: 6.1.6
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.18363
- WSL: Kali Linux

**Comment by aeschli** [comment]
Do you have the C++ extension installed on the WSL side?

**Comment by zhao170628** [comment]
Yes, I do.

**Comment by aeschli** [comment]
I suspect that it's an issue in the C++ extension.
The C++ implements semantic highlighting by it's own. To get the colors it looks at the currently installed theme. In a remote setup themes run on the UI side but the C++ extension on the remote side and can't access the themes extensions

**Comment by zhao170628** [comment]
But most code highlighting is fine.

**Comment by zhao170628** [comment]
But most code highlighting is fine.So why is that?

**Comment by aeschli** [comment]
The C++ language server adds semantic highlighting on top of the syntax (TextMate) highlighting.
On remote the semantic doesn't work.

**Comment by zhao170628** [comment]
Please solve this problem as soon as possible. Thanks. Good luck with VSCode.  I like this editor.
