### ISSUE TITLE
Live Share won't let me edit partner's directory...

### ISSUE THREAD

**Issue by zpiell** [microsoft/vscode#90763]
Issue Type: <b>Bug</b>

My partner and I just downloaded the Live Share extension for VS Code. It worked for the first day, but every time since then every change one of us makes to a document is not seen on the other's computer. It seems like something is set to read only because we are able to see each others' cursors, but cannot make edits. I do recall pressing a button to make sure my partner was not in read only as well. Please let me know ways I can circumnavigate this issue. Thank you.

**Comment by JacksonKearl** [comment]
Live Share functionality is provided by a separate extension, please file over at https://github.com/MicrosoftDocs/live-share/issues?utf8=%E2%9C%93&q=is:issue+is:open+sort:reactions-%2B1+. Thanks!
