### ISSUE TITLE
TypeScript formatter keeps crashing with JS file opened from Trash

### ISSUE THREAD

**Issue by Holben888** [microsoft/vscode#90769]
Not sure how to explain. Here's what I did:
- Opened a JS file from a standard directory
- Opened another JS file from my Trash
- I went back to the other tab where my standard JS file was open

Now, the formatter keeps crashing, claiming a TypeScript fault though this is a ".js" file. It also messes with my code's spacing unexpectedly.

**Comment by mjbvz** [comment]
I can repo this in a clean insiders build on MacOS but in the future please make sure to fill out the issue template

**Comment by Holben888** [comment]
Yeah sorry about that! I hit the "report" button on the error and it took me to a blank issue page without a template. I'll check for the template in the future, but idk why it was missing 🤷‍♀

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/36862 to track upstream
