### ISSUE TITLE
Undo history crashing VSCode when viewing log file

### ISSUE THREAD

**Issue by chofsass** [microsoft/vscode#90765]
- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:

1. create a file that is continuously  updating in the background
2. open the file in VSCode
3. open task manager and watch VSCode memory usage grow

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rebornix** [comment]
VS Code does have a memory limit based on the operating system and setting `files.maxMemoryForLargeFilesMB`. You can try to bump this setting to a higher one.
