### ISSUE TITLE
ampersand(&) error

### ISSUE THREAD

**Issue by EraseKesu** [microsoft/vscode#90762]
- VSCode Version: Update 1.42.1
- OS Version: windows 10

Steps to Reproduce:

1.rename the user profile directory to have an ampersand(&) in it
2.Done

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
