### ISSUE TITLE
The Terminal is Not Working

### ISSUE THREAD

**Issue by ssshreyans26** [microsoft/vscode#90775]
[We]([
![Screenshot from 2020-02-16 11-44-09](https://user-images.githubusercontent.com/37295393/74600067-bedfe880-50b1-11ea-81db-35be6b5d1b06.png)
) have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
