### ISSUE TITLE
JS syntax highlight

### ISSUE THREAD

**Issue by rafapaulin** [microsoft/vscode#90779]
Issue Type: <b>Bug</b>

When editing javascript Angular (8+) html templates, when you have a template dynamic attribute with "let" keyword in a context different than an *ngFor (in this case, on the table component of the Angular Material lib "*matCel" directive), the parser gets confused and does not process the closing double quotes correctly, destroying the hightlights after it (https://snipboard.io/ouydw0.jpg).

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         965  @ 3.20GHz (8 x 2393)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|9.72GB (1.64GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.12
vscode-apollo|apo|1.14.1
vscode-intelephense-client|bme|1.3.11
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.0.15
vscode-new-file|dku|4.0.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
php-debug|fel|1.13.0
sass-lint|gle|1.0.6
better-shellscript-syntax|jef|1.0.11
dotenv|mik|1.0.1
vscode-docker|ms-|0.10.0
python|ms-|2020.2.63072
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vetur|oct|0.23.0
laravel-blade|one|1.20.0
try-material-icon-theme|raf|3.9.0
vscode-workspace-switcher|sad|1.14.0
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.7.5
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Please file against the Angular extension: https://github.com/angular/vscode-ng-language-service
