### ISSUE TITLE
Debugger not stopping on breakpoints.

### ISSUE THREAD

**Issue by MarkBaggett** [microsoft/vscode#90777]
Issue Type: <b>Bug</b>

SYSTEM SETUP:
Host Windows 10 Home Edition
Environment Information:  Python 3.8.1
Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

TO REPRODUCE:
Create a Virtual environement and activate ( I have tried both venv and virtualenv. They both produce the same error).

C:\Users\mark_\Documents>python -m virtualenv MyVirtualEnv
C:\Users\mark_\Documents>cd MyVirtualEnv
C:\Users\mark_\Documents\MyVirtualEnv>powershell
PS C:\Users\mark_\Documents\MyVirtualEnv> .\Scripts\activate.ps1
(MyVirtualEnv) PS C:\Users\mark_\Documents\MyVirtualEnv> code .

Step 2: Try to debug a program.
Create a python program (I created as simple loop with a print statement) and put break points on every line.

When the interpreter is set to the MyVirtualenv:venv it will not stop at breakpoints.  When it is set to the main system interpreter it does.  (But no modules are available.)

Nothing special about launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}

Integrated Terminal Output:

PS C:\Users\mark_\Documents\MyVirtualEnv> cd 'c:\Users\mark_\Documents\MyVirtualEnv'; ${                                            on-2020.2.63072\pythonFiles\ptvsd_launcher.py' '--default' '--client' '-env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Users\mark_\Documents\env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUMyVirtualEnv\Scripts\python.exe' 'c:\Users\mark_\.vscode\extensions\ms-python.python-202ark_\.vscode\extensions\ms-python.python-202NBUFFERED}='1'; & 'C:\Users\mark_\Documents\MyVirtualEnv\Scripts\python.0.2.63072\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '54576' 'c:\Users\mark_\Documents\MyVi 'localhost' '--port' '54576' 'c:\Users\mark_\Documents\MyVirtualEnv\tesport' '54576' 'c:\Users\mark_\Documents\MyVirtualEnv\test.py'
1
2
..

There is this (perhaps) unrelated error in be CONSOLE tab of the developer tools

/C:/Program Files/Mi…desktop.main.js:259 [Extension Host] Error Python Extension: 2020-02-16 06:28:26: Failed to get interpreter information for 'C:\Users\mark_\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\mark_\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\mark_\.vscode\extensions\ms-python.python-2020.2.63072\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:200:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\mark_\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" ' +
    '"c:\\Users\\mark_\\.vscode\\extensions\\ms-python.python-2020.2.63072\\pythonFiles\\interpreterInfo.py"'
}
/C:/Program Files/Mi…desktop.main.js:259 [Extension Host] Error Python Extension: 2020-02-16 06:28:26: Failed to get interpreter information for 'C:\Users\mark_\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\mark_\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\mark_\.vscode\extensions\ms-python.python-2020.2.63072\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:200:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\mark_\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" ' +
    '"c:\\Users\\mark_\\.vscode\\extensions\\ms-python.python-2020.2.63072\\pythonFiles\\interpreterInfo.py"'
}
/

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (2 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|2.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.2.63072

</details>

**Comment by JacksonKearl** [comment]
Thanks for the bug report. This looks like an issue with the Python extension rather than core VS Code, could you file an issue at https://github.com/Microsoft/vscode-python?

**Comment by MarkBaggett** [comment]
Will do thanks.
