### ISSUE TITLE
Run the project by using the built-in command line, after being stopped, vscode will freeze 

### ISSUE THREAD

**Issue by hsl947** [microsoft/vscode#90770]
Run the project by using the built-in command line, after being stopped, vscode will freeze , and have to restart. It happened many times. thankyou

**Comment by hsl947** [comment]
By the way, Only the new version will reappear this problem.

```
版本: 1.42.1 (user setup)
提交: c47d83b293181d9be64f27ff093689e8e7aed054
日期: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
