### ISSUE TITLE
Be more explicit on what we expect from pull requests

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9077]
In order to avoid wasted effort such as in #7563, we should be more explicit on pull requests [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#pull-requests):

- Note that it may require discussion unless there is an explicit verbal call for a PR or has the help-wanted label. A GitHub issue may be a feature request, but it may not be a *valid* feature request given the direction of the product and need to keep everything light and responsive.
- Note importance of code organization page?

Sub-tasks:

- [x] Update how to contribute wiki page
- [ ] Add PULL_REQUEST_TEMPLATE.md

**Comment by bpasero** [comment]
Could we show a template for when a new PR is opened similar to issues?

**Comment by Tyriar** [comment]
I think [CONTRIBUTING.md](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) gets linked to in issues and PRs. Not sure all people click through to that though.

PULL_REQUEST_TEMPLATE.md was added in when ISSUE_TEMPLATE.md was though :+1: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by bpasero** [comment]
Yeah that sounds like the right way 👍

**Comment by Tyriar** [comment]
@bpasero any ideas on the PR template? I thought about it and think it's a bit little to try to educate people on what not to do.

**Comment by tonyeung** [comment]
A youtube video on the process and expectations of PRs would be awesome and also how the codebase is put together would be awesome. One of the reasons why I haven't even attempted to contribute is the amount of details that must be known before a PR is even considered acceptable. There's also the historical luggage that's associated with doing PRs like tests are required, certain code conventions, etc..
