### ISSUE TITLE
How automatically kill the task terminal after debugging?

### ISSUE THREAD

**Issue by Xiagb728** [microsoft/vscode#90786]
`"preLaunchTask": "startDebug",
 "postDebugTask": "closeDebug"`
.........................................................................
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "startDebug",
            "type": "shell",
            "command": "make -j4; openocd -f interface/cmsis-dap.cfg -c 'transport select swd' -f target/stm32f1x.cfg",
            "isBackground": true,
            "problemMatcher": {
                "pattern": {
                    "regexp": "."
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": ".",
                    "endsPattern": "."
                }
            }
        },
        {
            "label": "killOpenOCD",
            "type": "process",
            "command":[
                "${command:workbench.action.tasks.terminate}",
                // "${command:workbench.action.acceptSelectedQuickOpenItem}"
             ]
        }
    ]
}
```
The OpenOCD service does not end automatically like the make command, only depends on closing the terminal or executing Ctrl + C.
How to automatically close the task terminal after debugging？
Or execute Ctrl + C command automatically in the task terminal to end the Openocd service.
The currently used killOpenOCD method requires manual clicking on the pop-up list.

**Comment by Xiagb728** [comment]
No problems writing, messing up the layout when previewing ...

**Comment by alexr00** [comment]
You should be able to use some combination of command input variables to provide an argument to workbench.action.tasks.terminate.

https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by Xiagb728** [comment]
> 您应该能够使用命令输入变量的某种组合为workbench.action.tasks.terminate提供参数。
> 
> https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

Thank you.
This example happens to close the task terminal.
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Terminate All Tasks",
      "command": "echo ${input:terminate}",
      "type": "shell",
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "terminate",
      "type": "command",
      "command": "workbench.action.tasks.terminate",
      "args": "terminateAll"
    }
  ]
}
```
