### ISSUE TITLE
INVISIBLE PARTITION

### ISSUE THREAD

**Issue by Tclark0755** [microsoft/vscode#90789]
Issue Type: <b>Performance Issue</b>

I can only see a file called recovery on the File Explorer.  It has a total of 15GB with most used.  There is no other partitioned drive that I can see.  Where is the rest of my drive.  I copied a bunch of stuff onto the drive, but I don't see it.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you specify how this is related to VS Code editor?

**Comment by Tclark0755** [comment]
I have no idea, but it is the only category that let me send it.  All I know is that it is supposed to be 8T and only shows 15Gb.

Best regards,

Turia A Day, Managing Partner

[cid:c1d8fa39-a425-43d0-881e-91482fef6053]
2197 Hutt Ct.
Port Charlotte, FL 33952

Mobile:  (703)470-5948
FAX: (941)237-4913

APPOINTMENTS?  Visit https://aandbentllc.com<https://aandbentllc.com/> and click "BOOK TODAY"

This e-mail communication and any attachments are confidential and intended only for the use of the designated recipients named above. This communication may be a confidential or privileged communication.. If you are not the intended recipient, you are hereby notified that you have received this communication in error and that any review, disclosure, dissemination, distribution or copying of it or its contents is prohibited. If you have received this communication in error, please notify Turia Day  immediately by telephone at (703.470.5948)  and destroy all copies of this communication and any attachments. Thank you.

________________________________

**Comment by IllusionMH** [comment]
You aren't using latest VS Code version which is 1.42. Please update and check again.

>File Explorer

Is is Explorer(sidebar) or Open file/Open folder dialogs?

(guess work here, because initial report doesn't provide enough info) Explorer (sidebar) in VS Code only shows content of Workspace (opened folder). You need to use `File > Open folder` to open older with your project.
