### ISSUE TITLE
Terminal Panel is now too Wide.

### ISSUE THREAD

**Issue by GTruslove** [microsoft/vscode#90783]
Issue Type: <b>Performance Issue</b>

With this update the terminal panel which I place on the right has a minimum width that is far too wide. I barely have enough room left to code. The terminal panel only needs to be 1/2 this width.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

**Comment by sbatten** [comment]
fixed in insiders
