### ISSUE TITLE
Maybe unsound await in your codebase

### ISSUE THREAD

**Issue by Veetaha** [microsoft/vscode#90785]
Steps to Reproduce:
1. Look at the type declaration of `allPromises` variable.
2. See that an await is applied not to `Promise<T>` but to `Promise<T>[]`
https://github.com/microsoft/vscode/blob/b4eb9933a45aba1d5d74ccbde425dc524d88546a/src/vs/workbench/api/common/extHostExtensionService.ts#L185-L197

Maybe steps to fix:
`await Promise.all(allPromises)`

I know there is a `tslint` rule [await-promise](https://palantir.github.io/tslint/rules/await-promise/) that could potentially prevent this kind of bug, though don't know what is the equivalent in eslint...

**Comment by alexdima** [comment]
Good catch, thank you.

**Comment by Veetaha** [comment]
Your welcome)
