### ISSUE TITLE
C++ Intellisense does not apply code conformance

### ISSUE THREAD

**Issue by TheMarkie** [microsoft/vscode#90784]
I've recently migrated my c++ project from VS to VS Code. While I find that VS Code already handles c++ highlighting and compiling pretty well, Intellisense is kinda lacking and broken.

For example: My codebase is old and require these options:
- `/Zc:wchar_t-`
- `/Zc:forScope-`
- `/Zc:inline`
- `/Zc:implicitNoexcept-`

Compiling using MSBuild or CL is completely fine, only highlighting and error reporting is problematic. I've tried the `compilerArgs` setting in `c_cpp_properties.json` but it doesn't seem to be designed for this. I've tried putting in a shortcut (that runs cl.exe with the proper parameters) but that doesn't work either.

Any idea? Would be nice if this is implemented.

**Comment by JacksonKearl** [comment]
The C and C++ tooling is managed in a different repo, please file there: https://github.com/Microsoft/vscode-cpptools
