### ISSUE TITLE
high cpu

### ISSUE THREAD

**Issue by pilosof** [microsoft/vscode#90782]
Issue Type: <b>Bug</b>

renderer process on 100% without any open tabs...

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (17.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

![image](https://user-images.githubusercontent.com/627208/74605644-9ae0cf00-50d2-11ea-9d5d-e5d5a4c62d93.png)
![image](https://user-images.githubusercontent.com/627208/74606462-29f0e580-50d9-11ea-8a20-d4926abd315f.png)

**Comment by JacksonKearl** [comment]
Please see here for tips on diagnosing performance issues so that we have a better understanding of what is going on here: https://github.com/Microsoft/vscode/wiki/Performance-Issues
