### ISSUE TITLE
Extension Host fails to launch on some sample plugins

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode#90781]
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

[See this.](https://github.com/microsoft/vscode-extension-samples/issues/254) I also noticed that when I do `Ctrl + Shift + B`, the build would never finish.

I can't find a specific reason why this is happening.

Does this issue occur when all extensions are disabled?: Yes

I can however report that it did make the `lsp-sample` work again, though the `statusbar-sample` fails to launch even with all the extensions disabled.

Also I tested it with the Insiders version and that seems to work on everything. So this might have been fixed in the nightly. I'll just use that till this gets fixed.

**Comment by JacksonKearl** [comment]
Please create a new issue with detailed reproduction steps if this comes up again, thanks!

**Comment by mrakgr** [comment]
It seems completely arbitrary to me, so even if it happens again I doubt I will have anything useful to say. Do you have any advice for how to debug this?

I think to get to the bottom of this I'd have to compile VS Code from source and trace it through the system until I find a clue if the error appears again. In fact, I'd gone with that idea, but after many restarts, the completed build fails to run for me even though it says it is successful.

```
E:\Typescript\vscode/scripts/code.bat --no-cached-data
yarn run v1.22.0
$ node build/lib/electron
Downloading electron-v7.1.11-win32-x64.zip...
Downloaded electron-v7.1.11-win32-x64.zip
Done in 128.47s.
[13:28:44] Syncronizing built-in extensions...
[13:28:44] You can manage built-in extensions with the --builtin flag
[13:28:44] Downloading extension: ms-vscode.node-debug@1.43.0 ...
[13:28:44] Downloading extension: ms-vscode.node-debug2@1.42.1 ...
[13:28:44] Downloading extension: ms-vscode.references-view@0.0.47 ...
[13:28:44] Downloading extension: ms-vscode.js-debug-nightly@2020.2.1317 ...
[13:28:46] [marketplace] ms-vscode.node-debug ✔︎
[13:28:49] [marketplace] ms-vscode.references-view ✔︎
[13:28:50] [marketplace] ms-vscode.js-debug-nightly ✔︎
[13:28:52] [marketplace] ms-vscode.node-debug2 ✔︎

[Error: ENOENT: no such file or directory, open 'e:\Typescript\vscode\out\vs\code\electron-main\main.js'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'e:\\Typescript\\vscode\\out\\vs\\code\\electron-main\\main.js',
  phase: 'loading',
  moduleId: 'vs/code/electron-main/main',
  neededBy: [ '===anonymous1===' ]
}
```

For some reason electron is not getting compiled, and I have no idea why. The `electron-main\main.js` file is not there just as the error says.

VS Code is about as difficult to build as you'd expect for a 50mb codebase - I am hardly shocked that this is happening.

**Comment by mrakgr** [comment]
Since I am not having these issues anymore, let me close this.
