### ISSUE TITLE
Maximized terminal won't toggle

### ISSUE THREAD

**Issue by David-Else** [microsoft/vscode#90780]
Issue Type: <b>Bug</b>

Open the terminal, maximize the size with the arrow up icon. Now toggle the terminal on and off with ctrl + `... it always toggles back to the last size it was before being maximized. The same happens if you drag the terminal up and it becomes maximized. You can't toggle a maximized terminal.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.18.0-147.5.1.el8_1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3548)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.50GB (0.54GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-deno|axe|2.0.0
spellright|ban|3.0.50
markdown-preview-github-styles|bie|0.1.6
vscode-eslint|dba|2.0.15
prettier-vscode|esb|3.20.0
shell-format|fox|7.0.1
debugger-for-chrome|msj|4.12.6
LiveServer|rit|5.6.1
shellcheck|tim|0.9.0
quokka-vscode|Wal|1.0.277

</details>

**Comment by ArturoDent** [comment]
There is a command:

`workbench.action.toggleMaximizedPanel` unbound.  Try that instead.

It toggles between full panel and your last unmaximized panel size - no need to maximize the panel first.

If you are trying to toggle between a maximized panel and a maximized editor, see https://stackoverflow.com/questions/48511956/toggle-between-fullscreen-editor-and-terminal-in-vs-code/48512128#48512128


```
{
  "key": "ctrl+alt+t",  // you could use  "key": "ctrl+`",   if you wish
  "command": "workbench.action.closePanel",
  // "when": "terminalFocus"
},
{
  "key": "ctrl+alt+t",  // use   "key": "ctrl+`"   here if you used it above
  "command": "workbench.action.toggleMaximizedPanel",
  "when": "!terminalFocus"
},
```

**Comment by sbatten** [comment]
@David-Else yes @ArturoDent has provided the proper set up to toggle maximized panel
