### ISSUE TITLE
Extensions_issue

### ISSUE THREAD

**Issue by MohamedShahed** [microsoft/vscode#90792]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please provide details of the problem. Review advice at https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
