### ISSUE TITLE
Is it possible to show the outline of HTML tag inside of  JS files?

### ISSUE THREAD

**Issue by tranceyos2419** [microsoft/vscode#90799]
When I was writing React.js, I thought if the structure of html tags appears in the outline section, it would be convenient when I'm styling with CSS in JS. Is it possible to add this feature to VSCode?

**Comment by gjsjohnmurray** [comment]
@mjbvz can confirm, but I think it'd require an enhancement in the https://github.com/microsoft/TypeScript project.

**Comment by aeschli** [comment]
@tranceyos2419 Can you add a small code snippet and the expected outline?

**Comment by aeschli** [comment]
Closing due to lack of additional information
