### ISSUE TITLE
sort extentions by installed date

### ISSUE THREAD

**Issue by surpavan** [microsoft/vscode#90797]
Is it possible to add 'sort' option in extentions sidebar to sort by installation date.  This is usefull to remove extentions that we are installing now to give a try and remove them after 1 or 2 days.

Without this option we are stuck to remembering the name of the extension to uninstall it.

**Comment by gjsjohnmurray** [comment]
@surpavan maybe add your support to #53405 and close this one?

**Comment by surpavan** [comment]
@gjsjohnmurray  - I have given the support to the ticket. Closing this now.
