### ISSUE TITLE
Failed to save a file that starts with '//'

### ISSUE THREAD

**Issue by onlineservices283418** [microsoft/vscode#90790]
- VSCode Version: 1.42.1
- OS Version: Windows 10, build 18363
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create a new file with the single line `// Can't save this file.`
2. Saving the file with 'Save' or 'Save As' command fails with the following message:
`Failed to save '// Can't save this file.': [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")`

![image](https://user-images.githubusercontent.com/29972256/74610879-c62de300-50ff-11ea-980e-428204c6931b.png)

#90433 is closed as not reproducible, but the bug is still here and I can reproduce it on ver. 1.42.1.

**Comment by gjsjohnmurray** [comment]
/confirmed reproducible in 1.42.1

Already fixed in 1.43.0-insider, as detailed in #90433 

/duplicate
