### ISSUE TITLE
Graphical saturation issue

### ISSUE THREAD

**Issue by imlazyeye** [microsoft/vscode#90795]
Issue Type: <b>Bug</b>

1. Open VSC on my machine
2. Observe colors being whack

![image](https://user-images.githubusercontent.com/39664206/74615866-0c784780-50ea-11ea-9dc1-179bef718e09.png)

The above picture shows what the theme "Andromeda Italic Bold" looks like on my machine. This doesn't just pertain to the editor itself -- viewing a screenshot in the extensions marketplace on VSC will also show the colors looking the same way.

![image](https://user-images.githubusercontent.com/39664206/74615892-2ca80680-50ea-11ea-853f-f8728a4da3a8.png)

This above image shows what the colors should look like (pictured on another machine).

This happens no matter what theme I use, and happens regardless of if extensions are enabled. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpfixformat|Leo|0.0.84
gml-support|lia|1.7.2
python|ms-|2020.2.63072
csharp|ms-|1.21.11
unity-debug|Uni|2.7.2
vscode-icons|vsc|10.0.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Is #65816 relevant? Do you have multiple monitors?

**Comment by imlazyeye** [comment]
Doesn't seem so, I have tired the various command line arguments suggested on this thread and other similar ones with no change. I only use one single monitor. A lot of similar issues seem to indicate this was an issue resolved with Electron 6.0.x but I am on the latest version of VSC.

**Comment by deepak1556** [comment]
@imlazyeye is this still an issue with latest insiders https://code.visualstudio.com/insiders ? Also what are the command line options you have tried so far ?
