### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by hzdzlwh** [microsoft/vscode#90796]
Issue Type: <b>Bug</b>

typescript/lib doesn't point to a valid tsserver install

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 7, 4|
|Memory (System)|8.00GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.4.2
simple-react-snippets|bur|1.2.2
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
vscode-fileheader|mik|0.0.2
vetur|oct|0.23.0
minapp-vscode|qiu|2.2.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have custom value for `typescript.tsdk` in User or Workspace settings?
If it's `"typescript.tsdk": "node_modules/typescript/lib"` make sure that you installed packages with  `npm install` or `yarn`?

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
