### ISSUE TITLE
Prevent selected file in explorer from opening on explorer focus

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#90798]
We should prevent a focus on the explorer panel from opening the previously selected file.

Steps to Reproduce:

1. Open a file by clicking in the explorer.
2. Close the file.
3. Switch panel.
4. Go back to the explorer panel.

Result: reopen the file.
Wanted: does not reopen the file.

![gif](https://user-images.githubusercontent.com/9438102/74629625-f5247300-5158-11ea-866d-d892907c1a8a.gif)

```
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by gjsjohnmurray** [comment]
See #87524 and maybe try Insiders to see if it now behaves as you want.

**Comment by inwardmovement** [comment]
Indeed it works as expected in Insiders, thanks!
