### ISSUE TITLE
Inconsistent colorization of multiline union and intersection types

### ISSUE THREAD

**Issue by vagarenko** [Microsoft/vscode#9079]
- VSCode Version: 1.3.0
- OS Version: Windows 7

Steps to Reproduce:
I'm using Dark+ (default dark) theme but some other themes have same issue:
![vscode-bug](https://cloud.githubusercontent.com/assets/1395677/16736118/1bb9499e-47a5-11e6-9180-0651db9177ff.png)

As you can see `B` and `C` are never colorized in multiline declarations and `A` is colorized in some cases. Same for string literal types.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#206
