### ISSUE TITLE
VScode update kills my custom theme

### ISSUE THREAD

**Issue by FrancisVila** [microsoft/vscode#90805]
This was already reported in https://github.com/Microsoft/vscode/issues/66499, but the issue was closed. It has happened to me twice now, so I'm sure this is due to the update itself and not some manipulation error.

- VSCode Version: Version: **1.42.1** (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: **2020-02-11**T14:45:59.656Z
OS: Windows_NT x64 10.0.18363
- OS Version: Windows 10 Enterprise **1909**

Steps to Reproduce:
1. in the extensions folder, copy-paste one of the themes delivered with VScode
2. edit new theme to give it a new name, then edit some settings. Note: I gave it a name close to the old one (specifically, monokay_fvila), might that have something to do with it?
3. select new theme in VScode, enjoy
4. wait for the next update to delete your work

All the folders in my extension folder are dated 2020-02-14. My theme was last modified on  2020-02-13.

**Comment by gjsjohnmurray** [comment]
I don't think direct manipulation of theme files that way is supported, in which case you must take your own precautions to have your changes survive an update.

See https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme for a supported way of customising a theme (or all themes). The same page also tells you how to create a complete theme of your own.

**Comment by JacksonKearl** [comment]
All of the VSCode source code will be rewritten on update. @gjsjohnmurray linked to the supported way for customizing themes.
