### ISSUE TITLE
Latest version is slower

### ISSUE THREAD

**Issue by mallardexpress** [microsoft/vscode#90809]
- VSCode Version: 1.42.1
- OS Version: 10.11.6

Steps to Reproduce:

1. this version is much slower than previously, especially Outline Editor takes a full 10 seconds 'loading symbols' when I select a new file.
2. i am coding for flutter, with dart and flutter extensions only, no other extensions

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
@mallardexpress please review https://github.com/microsoft/vscode/wiki/Performance-Issues and consider submitting more information.

**Comment by trikarai** [comment]
mine also 

- VSCode Version: 1.42.1
- Electron : 6.1.6
- Chrome : 76.0.3809.146
- Node.js : 12.4.0
- V8 : 7.6.303.31-electron.0
- OS : Windows_NT x64 10.0.18363

System Info

CPUs | Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 11.90GB (6.23GB free)
Process Argv |  
Screen Reader | no
VM | 0%

CPU % | Mem MB | PID | Process
-- | -- | -- | -- 
2	  |  87	|  1880	|code main
59	  |  80	|  1108	|   shared-process
0	  |  14	|  3368	|   electron-crash-reporter
4	  |  66	|  5092	|   window (Issue Reporter)
 0	 |  231	| 12472	|   window (Inovasi3 (Workspace) - Visual Studio Code)
0	 |   69	|  5468	|     extensionHost
0	  |  48	| 10756	 |      electron_node eslintServer.js 
0	   | 67	| 12312	  |     electron_node vueServerMain.js 
0	    |37	| 10108	  |   watcherService
10	  | 131	| 13300	|   gpu-process

Extension | Author (truncated) | Version
-- | -- | --
vscode-intelephense-client | bme | 1.3.11
vscode-eslint | dba | 2.0.15
gitlens | eam | 10.2.1
discord-vscode | icr | 3.13.0
vscode-peacock | joh | 3.3.1
vsliveshare-pack | ms- | 0.3.4
vetur | oct | 0.23.0
vue-beautify | pea | 2.0.4
vue-vscode-snippets | sdr | 1.8.0
vuetify-vscode | vue | 0.2.0
