### ISSUE TITLE
When opening multiple pages at the same time, the page can not be switched directly in the display area

### ISSUE THREAD

**Issue by Simplemu** [microsoft/vscode#90803]
When opening multiple pages at the same time, the page can not be switched directly in the display area, before it can be switched by clicking on the page title, now it is particularly inconvenient to use, please fix it as soon as possible.

**Comment by gjsjohnmurray** [comment]
I don't understand your description. Please give more details. Perhaps paste some screenshots or an animated GIF or a link to a video.

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
