### ISSUE TITLE
Integrated terminal fonts are blurred

### ISSUE THREAD

**Issue by dzintars** [microsoft/vscode#90802]
Integrated terminal fonts are not crisp when multiple terminal panes are used.
When i do resize the panes, at some point i can get booth terminals crisp.

Single terminal is crisp and fine (using external terminal Alacritty)
![Screenshot from 2020-02-17 09-32-45](https://user-images.githubusercontent.com/547420/74633498-6e789180-516a-11ea-8c9c-c6a083361cb7.png)

When new pane is created, first terminal gets blurry and hard for my eyes. Second terminal is crisp and fine.
![Screenshot from 2020-02-17 09-34-02](https://user-images.githubusercontent.com/547420/74633509-72a4af00-516a-11ea-98b7-64d223cf79d7.png)

When resizing the panes i can get booth terminals crisp. There is some magic point, where the switch is happening from blurry to crisp. It seems to me that it is somewhat related to line-brakes.
![Screenshot from 2020-02-17 09-36-21](https://user-images.githubusercontent.com/547420/74633517-76383600-516a-11ea-927f-1d3cad3ee1a9.png)

Same happens when `--disable-extensions` and with default `xterm`

- VSCode Version: 1.42.1 c47d83b293181d9be64f27ff093689e8e7aed054 x64
- OS Version: Fedora 31

Steps to Reproduce:

1. Open integrated terminal
2. Split terminal
3. Resize terminal panes

Does this issue occur when all extensions are disabled?: Yes

**Comment by dzintars** [comment]
Ouh. Sorry. GitHub's image compression ruins my sample images and it's hard to tell the difference. But you have my word, that in 2nd image right terminal fonts are pretty blurred.

**Comment by vitaltechmax** [comment]
Same issue here. Let me know if you find out why this is the case.

**Comment by Tyriar** [comment]
Can you share your settings.json file?

> using external terminal Alacritty
> with default xterm

You're using VS Code's terminal in the screenshots, not alacritty or xterm?

**Comment by vitaltechmax** [comment]
Hi @Tyriar,

If it helps at all - I'm using VS Code. 

`{
    "window.zoomLevel": -1,
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "blade.format.enable": true,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.enableBell": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "vsintellicode.java.completionsEnabled": false,
    "vsintellicode.python.completionsEnabled": false,
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "workbench.iconTheme": "Monokai Pro (Filter Machine) Icons",
    "workbench.colorTheme": "Atom One Dark",
    "editor.fontFamily": "'Fira Code', monospace",
    "workbench.startupEditor": "welcomePage"
}`

**Comment by dzintars** [comment]
Confirming - `"window.zoomLevel": 0,` fixes the issue, but... that font size is too big for me. :(
