### ISSUE TITLE
setDecoration is not persistent or rendered in minimap

### ISSUE THREAD

**Issue by meakbiyik** [microsoft/vscode#90801]
- VSCode Version: 1.42.1
- OS Version: Windows 10

I am developing an extension with syntax highlighting, but have several issues with using editor.setDecorations() function. First of all, it is not persistent: when I change editors, I observe that the code goes white and then recolored. Secondly, the coloring does not appear on the minimap: I see that the basic coloring from textmate is there but the rest is not rendered. I suspect that the latter issue has something to do with #73140, but the former is something different (maybe #41965? But I do not have the problem pointed out there, see code below). Any help is appreciated!

Here's the somewhat-stripped-down implementation:

```typescript
export async function activate(context: vscode.ExtensionContext) {

    const trees: { [uri: string]: Parser.Tree } = {}

    async function open(document: vscode.TextDocument) {
        const language = languages[document.languageId]
        const t = language.parser.parse(get_text_without_margins(document)) // TODO don't use getText, use Parser.Input
        trees[document.uri.toString()] = t
        if (vscode.window.activeTextEditor && (document.uri == vscode.window.activeTextEditor.document.uri)){
            colorActiveEditor(vscode.window.activeTextEditor)
        }
    }

    function edit(edit: vscode.TextDocumentChangeEvent) {
        const language = languages[edit.document.languageId]
        updateTree(language.parser, edit)
        if (vscode.window.activeTextEditor && (edit.document.uri == vscode.window.activeTextEditor.document.uri)){
            colorActiveEditor(vscode.window.activeTextEditor)
        }
    }
   
    function colorActiveEditor(e: vscode.TextEditor|undefined) {
        if(!e) return;
        const language = languages[e.document.languageId]
        if (language == null) return
        const scopes = language.color(t)
        for (const scope of scopes.keys()) {
            const dec = decoration(scope)
            if (dec) {
                const ranges = scopes.get(scope)!.map(range)
                e.setDecorations(dec, ranges)
            }
        }
    }
    context.subscriptions.push(vscode.window.onDidChangeActiveTextEditor(colorActiveEditor))
    context.subscriptions.push(vscode.workspace.onDidChangeTextDocument(edit))
    context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(open))

}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Hey @meakbiyik, that's correct. This looks like a duplicate request of https://github.com/microsoft/vscode/issues/73140, currently the minimap renders only a subset of the decorations from the editor.

For the first problem of the code being white before being colorized, I believe this is expected behavior  - @rebornix do we do any caching for colorizing?

**Comment by meakbiyik** [comment]
Textmate coloring does not do that "going white" thing though, so I imagine there is a cache but it setDecorations cannot utilize it?

**Comment by rebornix** [comment]
There is no cache for tokens so when swiching editors, we do re tokenization so there might be a period that the text has no color, which is white in a dark theme.
