### ISSUE TITLE
autocompletion SCSS

### ISSUE THREAD

**Issue by mediaclap** [microsoft/vscode#90815]
Issue Type: <b>Bug</b>

on SCSS files autocompletion doesnt works !
body {
  b..
}
not propose border or background

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Probably belongs at https://github.com/microsoft/vscode-css-languageservice

**Comment by mediaclap** [comment]
the probleme was just with live share !

**Comment by JacksonKearl** [comment]
@mediaclap the liveshare project is also a separate repository, https://github.com/MicrosoftDocs/live-share/issues?utf8=%E2%9C%93&q=is:issue+is:open+sort:reactions-%2B1+. But its not clear to me why you think this is part of Live Share.

**Comment by octref** [comment]
Please open issue for Liveshare then
