### ISSUE TITLE
Some problems with typescript language server

### ISSUE THREAD

**Issue by artem-malko** [microsoft/vscode#90812]
Issue Type: <b>Bug</b>

Just issue from vs code from the bottom right alert

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (1.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
project-manager|ale|10.10.0
vscode-sqlite|ale|0.8.1
Handlebars|and|0.4.1
dart-code|Dar|3.8.1
vscode-eslint|dba|2.0.15
githistory|don|0.5.3
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
prettier-vscode|esb|3.20.0
vscode-styled-components|jpo|0.0.28
vscode-docker|ms-|0.10.0
python|ms-|2020.2.63072
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-ssh-explorer|ms-|0.49.0
azure-account|ms-|0.8.8
Go|ms-|0.13.0
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|3.9.3
quicktype|qui|12.0.46
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
addDocComments|ste|0.0.8
pdf|tom|0.5.1
gitblame|wad|3.0.1

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!

**Comment by artem-malko** [comment]
Hi @JacksonKearl 
This issue was created automatically from VS Code. It said, ts-server was restarted several times during last 5 minutes. And that is all)

**Comment by JacksonKearl** [comment]
@artem-malko Thanks! Closing this for now but if you encounter it popping up frequently with particular operations or in particular repositories please don't hesitate to file a report with detailed reproduction steps and we can investigate further.
