### ISSUE TITLE
Wrong typescript auto imports when there are json imports

### ISSUE THREAD

**Issue by mukaschultze** [microsoft/vscode#90817]
- VSCode Version: 1.42.1
- OS Version: KDE Neon x64

Steps to Reproduce:

1. Create a typescript project with `"resolveJsonModule": true`
2. Create a new TS file and import a JSON module (`import { payload } from "../payload.json";`)
3. Create another TS file with another class on it
4. Go back to the original file and use the auto-import to import the new class

You should see that it imported the class from a JS file instead of the TS, even though the JS file does not exist.

#### With JSON modules being imported
![image](https://user-images.githubusercontent.com/13923364/74652174-379f7d00-5164-11ea-9251-2dbeff947ab5.png)

#### Without JSON modules
![image](https://user-images.githubusercontent.com/13923364/74652138-248cad00-5164-11ea-9bd1-9c2c07fae860.png)

This little `.js` is easily missed by our eyes and can cause some serious bugs that are really hard to debug.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please create a small GitHub repo that demonstrates this issue

**Comment by mukaschultze** [comment]
@mjbvz 

### https://github.com/mukaschultze/vscode-bug-90817

And a GIF as I think it nicely demonstrates what's going on

![demo](https://user-images.githubusercontent.com/13923364/74833010-5da95680-52f7-11ea-9eed-7621d24de6aa.gif)

**Comment by mukaschultze** [comment]
This might be a bug with `tsserver` actually, I'm seeing the `.js` file in the response from `completionInfo`

**Comment by mukaschultze** [comment]
This does not happen when using `typescript@next`, I was checking tsserver source code and I guess this was fixed by microsoft/TypeScript#36615 as it changes the behavior of `getFixesForAddImport` method.

**Comment by mjbvz** [comment]
Ok, thanks for the investigation!

Closing this as fixed in TS 3.8 which will ship with VS code 1.43
