### ISSUE TITLE
Duplicate search results after using "Go to definition" with C language

### ISSUE THREAD

**Issue by baltth** [Microsoft/vscode#9081]
- VSCode Version: 1.3.0
- OS Version: Ubuntu 16.14 LTS
- Microsoft C/C++ extension installed

Steps to Reproduce:
1. Open a folder (eg "/home/user/src")
2. Use Go to definition or Peek definition on any symbol
3. Search something with the search panel (ctrl+shift+f)
4. Get duplicate results from the _same file with two different paths:_
/home/user/src/src.c
///home/user/src/src.c

**Comment by sandy081** [comment]
@baltth Is it possible to access to the workspace/repository to reproduce this?

**Comment by sandy081** [comment]
Please reopen it with the requested details.
