### ISSUE TITLE
a file named '\' causes "Initializing TS/JS language features" to hang

### ISSUE THREAD

**Issue by jakob-bebop** [microsoft/vscode#90811]
When such a silly file is present, the js/ts builtin cannot load, and typescript navigation doesn't work. There is no error message.

- VSCode Version:
1.42.1
- OS Version:
Linux x64

Steps to Reproduce:

1. In a typescript project, create an empty file e.g. `touch 'src/\'`
2. open vscode `code .`

Does this issue occur when all extensions are disabled?:
Yes

**Comment by mjbvz** [comment]
Doesn't repo for me on MacOS or Linux (Ubuntu 18)

![Screen Shot 2020-02-18 at 11 01 57 AM](https://user-images.githubusercontent.com/12821956/74768827-1a3ee180-523e-11ea-89c5-7233f6226d15.png)

Do you see this in an empty workspace (I tried it in one with just a package.json and a ts file)
