### ISSUE TITLE
Issues opening data frames in Variable Explorer

### ISSUE THREAD

**Issue by S-UP** [microsoft/vscode#90818]
I get this error when trying to open a data frame.

Must be due to the data structure in the file as I generally have no issue, but it's difficult to figure out what exactly is the problem.

Let me know how to help narrowing it down.

Note: Changed the true data values to xxx for data privacy reasons.

Here is the error:

Error: Failure during variable extraction: --------------------------------------------------------------------------- JSONDecodeError Traceback (most recent call last) ~/analytics/consolidatedCRM/consolidatedCRM/py_modules/formstack_client.py in <module> 9 # In IJupyterVariables.getValue this '{"count":527,"name":"answers_data","shape":"(527, 6)","size":0,"supportsDataExplorer":true,"truncated":true,"type":"DataFrame","value":"form_name question_1 \\\\n 0 Care_Kit_FR first = xxx\\\nlast <...>\\n 72 address = xxx\\\ncity = xxx... xxx\\n "}' will be replaced with the json stringified value of the target variable 10 # Indexes off of _VSCODE_targetVariable need to index types that are part of IJupyterVariable ---> 11 _VSCODE_targetVariable = _VSCODE_json.loads("""{"count":527,"name":"answers_data","shape":"(527, 6)","size":0,"supportsDataExplorer":true,...

**Comment by gjsjohnmurray** [comment]
I think this issue needs to be raised at https://github.com/microsoft/vscode-python
