### ISSUE TITLE
[powershell] syntax highlighting error

### ISSUE THREAD

**Issue by syrigos** [Microsoft/vscode#9082]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Create a powershell script
2. Create an object with a property that has a space, such as $obj."Property with space"
3. The highlight for the quotes doesn't display properly.

**Comment by gerane** [comment]
This should be fixed soon I think.

CC @daviwil @gravejester

**Comment by gravejester** [comment]
That's correct. This bug is fixed in https://github.com/PowerShell/EditorSyntax/pull/12

**Comment by OCram85** [comment]
I noticed a similar effect with this:
![ps-highlight](https://cloud.githubusercontent.com/assets/13993700/16796697/51520aec-48e4-11e6-94cd-af99cda5ffc9.png)

- With VSCode Version 1.3.1 on a Windows7 64Bit system.

**Comment by anmo13** [comment]
Similar issue as @OCram85:
![image](https://cloud.githubusercontent.com/assets/20575007/17016437/6dfbc51a-4f2f-11e6-8608-1fc2608127d7.png)
VSCode Version 1.3.1 on Windows10 64Bit
