### ISSUE TITLE
[Bug] - Typescript intellisense not picking up other .tsx files when importing

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#90823]
- VSCode Version: 1.42.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. clone https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example
2. Try to import `test.tsx` into page pages/index.tsx

![no_auto_complete](https://user-images.githubusercontent.com/936006/74658988-5cf3b180-518b-11ea-9d2e-38bd4084a615.gif)

## TS Server trace
It does work if i just type it out in the document without being inside of import braces.

Looks like the difference is a `competionInfo` request is sent to the typescript server when i type in the document and i get a response with suggestions, but inside of `import` i get 
```
[Trace  - 14:23:48.406] <semantic> Response received: completionInfo (1416). Request took 5 ms. Success: false . Message: No content available.
```
### Typing inside import
![Screenshot 2020-02-17 at 14 28 45](https://user-images.githubusercontent.com/936006/74662686-4b61d800-5192-11ea-901a-ce285b88981b.png)

### Typing inside document
![Screenshot 2020-02-17 at 14 35 27](https://user-images.githubusercontent.com/936006/74663047-f5d9fb00-5192-11ea-817a-23fe79752b28.png)

**Comment by mjbvz** [comment]
Auto imports mean that you don't need to write imports at all: just start typing the name of the symbol where you want to use it and accept the suggestion:

![Screen Shot 2020-02-18 at 2 41 21 PM](https://user-images.githubusercontent.com/12821956/74784439-c0014900-525c-11ea-9f72-e980b69bc2fa.png)

This will add the import to the top of the file:

```
import { Welcome } from "components/test";
```

**Comment by mjbvz** [comment]
If you still want to see the auto imports work inside `import` statements, you can [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) against the TypeScript project since it powers this feature

**Comment by jasonwilliams** [comment]
Linking with https://github.com/microsoft/TypeScript/issues/31658
