### ISSUE TITLE
Document that registerTextEditorCommand does not work with asyncrhonous operations

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#90834]
According to this issue: #16814 commands registered using `registerTextEditorCommand` can not run asynchronously or an error will be thrown.
This is somewhat unexpected because the API documentation does not mentions anything about that. It only says what the callback function will get, which is very convenient if you want to make some editions to the current file without having to worry about checking its existence.
Here is a screenshot of the [documentation](https://code.visualstudio.com/api/references/vscode-api#commands.registerTextEditorCommand):
![image](https://user-images.githubusercontent.com/2270425/74668906-76562700-51a6-11ea-9c05-7aec6d16e11b.png)

I propose to add an extra sentence warning that this command must run synchronously or the provided textEditor and TextEditorEdit instances will not be longer valid.

**Comment by dhairyanadapara** [comment]
@jrieken I have started working on this issue.

**Comment by eishan05** [comment]
@jrieken @danielo515 If still needed, I can take this task on

**Comment by kit-repo-depot** [comment]
May I address the issues from PR #91823 to make the note usable for this issue?

**Comment by danielo515** [comment]
People learn from examples better than anything else. Including an example will not hurt, IMO

**Comment by kit-repo-depot** [comment]
Alright thanks I’ll get started on that!

**Comment by kit-repo-depot** [comment]
Alright thanks, I'll see what I can do!

**Comment by tabaddor** [comment]
Does #98116 resolve this issue? If not, I can look into it.
