### ISSUE TITLE
Docker extension: windows escaped strings break syntax highlighting

### ISSUE THREAD

**Issue by zhammer** [microsoft/vscode#90833]
Windows dockerfiles require double quotes in `RUN` commands to be escaped, like `\"` (see: https://github.com/StefanScherer/dockerfiles-windows/tree/master/quotes).

Escaping a doublequote in vscode breaks the docker extension's syntax highlighting:
![screenshot of broken syntax highlighting](https://user-images.githubusercontent.com/6956487/74667423-450f3400-5171-11ea-9bca-c6b01106906f.png)

------

- VSCode Version: 1.42.1
- OS Version: Darwin x64 18.6.0

Steps to Reproduce:

1. Make a new Dockerfile and paste the following content:
```
FROM microsoft/windowsservercore:latest

RUN powershell Write-Host \"Hello world\"

COPY . .
```

Does this issue occur when all extensions are disabled?: N/A (specifically a docker extension bug)

**Comment by JacksonKearl** [comment]
We pull the Docker grammar from https://github.com/moby/moby/blob/master/contrib/syntax/textmate/Docker.tmbundle/Syntaxes/Dockerfile.tmLanguage, I have opened an issue on that repository: https://github.com/moby/moby/issues/40536
