### ISSUE TITLE
PHP Syntax Highlighting of Closure Variable Inconsistent

### ISSUE THREAD

**Issue by PythooonUser** [microsoft/vscode#90832]
- VSCode Version: `1.42.1`
- OS Version: Windows 10, 1709

```
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299
```

Steps to Reproduce:

1. Set Color Theme to e.g. Dark+
1. Define a function closure and assign it to a variable
1. Call the closure
1. The `$` is inconsistently colored

```php
<?php

class Test
{
    public function test()
    {
        $callback = function() {};

        $callback;      // Consistent coloring
        $callback();    // Inconsistent coloring
    }
}
```

Dark+ Color Theme (Inconsistent)
![image](https://user-images.githubusercontent.com/13063023/74665584-49067a80-51a0-11ea-83d0-715762e9ac03.png)

Dark Color Theme (Consistent)
![image](https://user-images.githubusercontent.com/13063023/74666032-127d2f80-51a1-11ea-8650-3de0e1c62612.png)

I looked trough the existing default color themes.

Inconsistent:
- Light+
- Dark+
- Monokai Dimmed
- Red
- Tomorrow Night Blue
- High Contrast

Consistent:
- Light
- Quiet Light
- Solarized Light
- Abyss
- Dark
- Kimbie Dark
- Monokai
- Solarized Dark

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
We pull the php syntax from an upstream repository. I have filed an issue there: https://github.com/atom/language-php/issues/382
