### ISSUE TITLE
Markdown preview is broken in 1.3.0 release

### ISSUE THREAD

**Issue by MovGP0** [Microsoft/vscode#9083]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Open a markdown file
2. the magnifier glass for preview is absent on the top right 

see also #8130 

`Ctrl+Shift+V` works fine

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7666 for the issue that the action moved into the tab context menu.

**Comment by mjbvz** [comment]
I believe this was fixed by 99aa1bc6b095f1954a0f4088fdd0c674e4d1d580
