### ISSUE TITLE
Provide ability to hide debug error

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#90844]
Issue Type: <b>Feature Request</b>

Thanks to a poorly written debugger by Adobe called ExtendScript Debugger, every time I debug .jsx files I will receive an error notification that one or more debug expressions in the Watch drop-down failed to evaluate.

[Here's the error.](https://pasteboard.co/IV8LVrf.png)
[Here's the reason for the error.](https://pasteboard.co/IV8NdeI.png)

I just double click the expression and then click off which will force it to refresh and display a proper value but the error notification in the bottom right obviously won't disappear from me doing that.

Can we get an ability to hide this error notification in settings? This would be useful since I am almost always forced to see this error even though it's just something that I can safely ignore.

Thanks.

VS Code version: Code - Insiders 1.43.0-insider (6ec6f9e3f4d17f0cef0480688a1f350b9141e567, 2020-02-17T05:42:20.509Z)
OS version: Windows_NT x64 10.0.18362

**Comment by connor4312** [comment]
This error appears to be coming from inside the extendscript debugger, so you'll need to open an issue on them to fix it.

```
PS E:\Downloads\Adobe.extendscript-debug-1.1.2> rg "Switch Frame"
extension\dist\session\ESDebugRuntime.js
184:                reject("Switch Frame Timeout.");
```

**Comment by ariffjeff** [comment]
> 
> 
> This error appears to be coming from inside the extendscript debugger, so you'll need to open an issue on them to fix it.
> 
> ```
> PS E:\Downloads\Adobe.extendscript-debug-1.1.2> rg "Switch Frame"
> extension\dist\session\ESDebugRuntime.js
> 184:                reject("Switch Frame Timeout.");
> ```

Ah I didn't think that that would have been the issue. Thanks for notifying me.
