### ISSUE TITLE
Zooming too sensitive when pinch

### ISSUE THREAD

**Issue by EntherH** [microsoft/vscode#90845]
On windows 10, when use pinch to zoom it has always been way too sensitive anywhere.

Version: 1.42.1 (user setup)Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

List of extensions:
Not related.

**Comment by JacksonKearl** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!

**Comment by EntherH** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

have updated. Thank you.

**Comment by alexdima** [comment]
@EntherH I'm not sure. Can you please explain what exact gesture are you doing? AFAIK we don't support pinch to zoom anywhere in VS Code so please explain in greater detail.

**Comment by EntherH** [comment]
> @EntherH I'm not sure. Can you please explain what exact gesture are you doing? AFAIK we don't support pinch to zoom anywhere in VS Code so please explain in greater detail.

Hi Alex. Sorry for lack of information. I mean pinch to Zoom in the editing zone. Or when zooming pics or pdf loaded with extensions, e.g. latex workshop.

**Comment by alexdima** [comment]
@EntherH Can you please show a screenshot of a typical place where you can use pinch to zoom? I believe you are referring to what we internally call Webviews but I would like to confirm that is the case.

**Comment by EntherH** [comment]
> @EntherH Can you please show a screenshot of a typical place where you can use pinch to zoom? I believe you are referring to what we internally call Webviews but I would like to confirm that is the case.

![image](https://user-images.githubusercontent.com/44420541/74831350-00200480-530d-11ea-8e1b-975159b74b18.png)
![image](https://user-images.githubusercontent.com/44420541/74831356-01e9c800-530d-11ea-9f33-1da966753f16.png)

Here they are

**Comment by alexdima** [comment]
@mjbvz The editor does not pinch-zoom AFAIK, so I believe this issue is about the PDF preview that shows in the webview.

**Comment by EntherH** [comment]
> @mjbvz The editor does not pinch-zoom AFAIK, so I believe this issue is about the PDF preview that shows in the webview.

It indeed does. I think this is related to a option that allows you to zoom using mouse wheels.

**Comment by alexdima** [comment]
@EntherH Sorry, but this is as designed. You have configured `"editor.mouseWheelZoom": true`. That makes that ctrl + mouse wheel will zoom the font size. So if you don't like that, then please remove that and use `"editor.mouseWheelZoom": false`.
