### ISSUE TITLE
Use relative paths when linking to files

### ISSUE THREAD

**Issue by redstubble** [microsoft/vscode#90848]
In VSCode I can link to files within the comments
```javascript
/**
 * Pretty things file:///<fullPath>/colors.js
 */
```

Is there any way to do this with relative links e.g.
```javascript
/**
 * Pretty things file:///${workspaceFolder}/colors.js
 */
```

**Comment by alexdima** [comment]
You can now write links like `file://./relativeFile.txt` or `file:///./relativeFile.txt` and they will be interpreted as relative to the current opened file.
