### ISSUE TITLE
npm Hover Run Script not working

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#90855]
- VSCode Version: 1.42.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Hover over name of script in `package.json`
2. Click "Run Script"
3. Nothing happens

I've tracked the issue to https://github.com/microsoft/vscode/blob/92a9a07213688168fd1f8b606198988aa072785e/extensions/npm/src/scriptHover.ts#L105-L110

where `folder` is getting `undefined`. It seems to be an encoding issue with the `args.documentUri` that's not being decoded properly after being passed through the command link. It works if the `Uri` is reformatted by changing line 105 to
```typescript
let documentUri = Uri.file(args.documentUri.fsPath);
```
Based on the specific encoding issue I see, I think this might only affect Windows.

**Comment by egamma** [comment]
Looks like this issue is back https://github.com/microsoft/vscode/issues/65561

**Comment by egamma** [comment]
Confirmed it is the same encoring issue as in #65561
![image](https://user-images.githubusercontent.com/172399/75680326-a535c800-5c91-11ea-9e95-8f11ae609c08.png)

Left is the URI that is used for the markdown creation function `createRunScriptMarkdown`, right is the decoded documentURI received in `runScriptFromHover`.

**Comment by egamma** [comment]
Pinging @jrieken for additional insights.

**Comment by jrieken** [comment]
Interestingly, this is already broken in the Nov19 release (1.41). Pretty sure this regressed when we started to open links as URI-objects or as strings. The `CommandOpener` [parses](https://github.com/microsoft/vscode/blob/614a837995878e0de96ffb65a972cfce98e4acfc/src/vs/editor/browser/services/openerService.ts#L29) a string into a uri and I am pretty sure this leads to subsequent double decoding...

**Comment by egamma** [comment]
@jrieken adding the work around as suggested in the description and doing `let documentUri = Uri.file(args.documentUri.fsPath)` or investigate into the real solution?

**Comment by jrieken** [comment]
I will look into a real fix, e.g don't double decode but I am first looking so some test harness so that this stops breaking

**Comment by jrieken** [comment]
So, this has actually regressed with https://github.com/microsoft/vscode/commit/c26146d7c5a7b9b4b01e7b5d758fae087dea834a... Now I just need to remember why that change was done...

**Comment by jrieken** [comment]
change  https://github.com/microsoft/vscode/commit/c26146d7c5a7b9b4b01e7b5d758fae087dea834a was done because dom-uris are [encoded](https://github.com/microsoft/vscode/blob/9d40b2408c65cb05402bfb6761c28aadb52c3bf7/src/vs/base/common/network.ts#L93) and not decoding them would break icon fetching. Still, the fix is covering too much - the decoded variant should only be returned when dealing with a dom uri
