### ISSUE TITLE
Git dies a brutal death when capitalization changes are involved

### ISSUE THREAD

**Issue by TheMageKing** [microsoft/vscode#90852]
Issue Type: <b>Bug</b>

The exact details of how to reproduce the issue from scratch are unknown to me, and I really would rather not try and break Git again.  However, this is the approximately the steps:
1. Have a file on Machine A with one capitalization ("FileName")
2. Commit, and push, that file (all good so far) to Branch A
3. Pull Branch A to Machine B
4. Make a new Branch B on Machine A, and rename the file to another capitalization ("fileName").
5. Commit, and push, the renamed file 
6. Merge Branch B into Branch A
7. Push Branch A.
8. On machine B, pull branch A
9. Suffer: Git in VS Code will not correctly display the proper state of the file, nor allow you to interact with it via the UI.  In our case, an incorrect version of the code was being displayed

I should point you to a repository that demonstrates this.  github.com/FRC-999/FRC-2020, on the wertz branch, from commits ID 01adb5 to when it was resolved fully in c65f75b.  01ad introduced new changes, and those changes were not available at 7b13.  It took until c65f to resolve all the issues.  Three separate machines saw an incorrect version of the code at 7b13, one of which was pulling for the first time since before 01ab.  

If you are looking at the log, I am TheMageKing, JEWertz is a third party, and Coypirus is the one who made the changes in 01ab (under my name, ironically). 

In order to resolve this issue, I had to manually remove the problem files (as in, by using Explorer), commit, and then restore the old versions.   Until c65f, the VS code GUI was displaying phantom changes, refusing to pull or behave.  Even after Coypirus's machine received c65f, it took a restart of VSCode before the file behaved.

Sorry for such a verbose bug report: I am not sure where the bug is, from a corrupt merge commit to a capitalization bug.  If you need me to explain more, contact me.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.33.0
git-coauthors|drr|0.1.2
gitlens|eam|10.2.0
git-assistant|iva|1.2.2
remote-wsl|ms-|0.41.7
cpptools|ms-|0.26.2
vsliveshare|ms-|1.0.1456
java|red|0.55.1
markdown-preview-enhanced|shd|0.5.1
code-spell-checker|str|1.7.20
vscodeintellicode|Vis|1.2.3
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.2
vscode-wpilib|wpi|2020.1.2
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by joaomoreno** [comment]
> Git in VS Code will not correctly display the proper state of the file, nor allow you to interact with it via the UI

What about `git status` in the command line?

**Comment by TheMageKing** [comment]
Git status was accurately stating that the file had not been modified, even as VSCode listed it as being changed.

**Comment by joaomoreno** [comment]
Can you show me with a recording or a screenshot?
