### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by Derrick98** [microsoft/vscode#90858]
Issue Type: <b>Feature Request</b>

The terminal shell path "C:\msys64\usr\bin\bash.exe" does not exist
Please how can i fix this?

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
Does the path exist?

**Comment by Derrick98** [comment]
That's what pops up and I don't know how to create that path

**Comment by Tyriar** [comment]
That only pops up because you (or an extension you installed) has configured the path in your settings. Go into your settings and change `terminal.integrated.shell.windows` or alternative hit F1 and type "Default Shell" and run that command to change your shell.
