### ISSUE TITLE
vscode autocomplete prompt keep loading and intellisense not working when i edit vue project

### ISSUE THREAD

**Issue by L-Devil-GitHub** [microsoft/vscode#90854]
- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:

1. after i edit the scripts parts in .vue file(most of the time caused by this, Especially when i edit the component property called 'props' in script part, other parts may sometimes cause this problem), vscode autocomplete prompt keep loading and intellisense not working
![image](https://user-images.githubusercontent.com/26218200/74696589-fa55f080-5232-11ea-8a7a-0524c6add2cc.png)

2. because my code is in disk D, so then i try to upgrade my workspace to use typescript@next by installing JavaScript and TypeScript Nightly and it still happen
![image](https://user-images.githubusercontent.com/26218200/74696611-0c379380-5233-11ea-8e42-423c2c44f904.png)
![image](https://user-images.githubusercontent.com/26218200/74698058-8a963480-5237-11ea-868f-13cde3edcf33.png)

3. then i try to move my code to disk C, it seems working for a while, but it gone bad after i kept working for about 10 minutes

4. And once it happens, vscode keeps taking up cpu power ten times or even dozens of times higher than usual until i reload the window

Does this issue occur when all extensions are disabled?: No.

**Comment by L-Devil-GitHub** [comment]
But I only use the extension called Vetur for the Vue file, and others around me dont have this problem by using Vetur.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/new
https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

**Comment by L-Devil-GitHub** [comment]
ok, thanks
