### ISSUE TITLE
[Feature Request] Drag and Drop Tabs to Different Windows

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9086]
- VSCode Version: Code - Insiders 1.4.0-insider (f6227ca157caed3ce3224ad9f760a8d5c8ed0e4d, 2016-07-11T05:07:20.965Z)
- OS Version: Windows_NT ia32 10.0.14372

Drag and drop open tabs between different VS Code windows. Or drag out to create new window. (Similar behavior to web browser tabs.)

**Comment by bpasero** [comment]
I pushed a change for the former, the latter is already covered in another issue (https://github.com/Microsoft/vscode/issues/8171)

**Comment by dilijev** [comment]
@bpasero just tried it, works great! Thanks!

**Comment by Tyriar** [comment]
Verified, created minor bug https://github.com/Microsoft/vscode/issues/9915
