### ISSUE TITLE
Go to definition not working anymore

### ISSUE THREAD

**Issue by alice0ch** [microsoft/vscode#90863]
# Environment data

- VS Code Version：1.42.1
- Extension version (ms-python.python)：2020.2.63072
- OS and Version：Windows 17763.973
- Python Version：3.8.0
- Type of virtual environment used：virtualenv
- Relevant/affected Python packages and their versions: None

# Expected behaviour
Visual Studio Code navigate to the definition of the function which resides inside the workspace (Working fine earlier)

# Actual behaviour
Popup with Message: "No definition found for 'function_name' "

# Logs
No logs or errors in console

# Same Issue Before
https://github.com/microsoft/vscode-python/issues/5425
But now the version is newer and this issue is existing

**Comment by gjsjohnmurray** [comment]
Please raise your issue at https://github.com/microsoft/vscode-python so it gets seen by the team best able to help you. Feel free to link from here to the new issue there before closing here.

**Comment by SVilgelm** [comment]
Same behavior with Go extension

**Comment by gjsjohnmurray** [comment]
@SVilgelm has this been reported at the repository of the Go extension that you are using?

**Comment by SVilgelm** [comment]
@gjsjohnmurray I found this one: https://github.com/microsoft/vscode-go/issues/3072
