### ISSUE TITLE
Bui;d issue

### ISSUE THREAD

**Issue by al-davis** [microsoft/vscode#90861]
Issue Type: <b>Bug</b>

Trying Build results in this error in the Terminal window

    Executing task: msbuild /property:GenerateFullPaths=true /t:build /consoleloggerparameters:NoSummary <

'msbuild' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

I do have an msbuild.exe on my system (Win10).  Possible path issue ?  Is msbuild the expected ?  
Something else Ib should look into ?

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment]
Please share all your settings.json, your tasks.json, and the result of `path` when you run `process.env` from the developer tools (command palette -> Toggle Developer Tools)

**Comment by al-davis** [comment]
I should mention that I am fairly new to VScode and don't understand all the inner  workings.  I was able to use it without issue for several days before problems arose.  Following , hopefully, is what you asked for.
{
   // See https://go.microsoft.com/fwlink/?LinkId=733558
   // for the documentation about the tasks.json format
   "version": "2.0.0",
   "tasks": [
      {
         "label": "build",
         "type": "shell",
         "command": "msbuild",
         "args": [
            // Ask msbuild to generate full paths for file names.
            "/property:GenerateFullPaths=true",
            "/t:build",
            // Do not generate summary otherwise it leads to duplicate errors in Problems panel
            "/consoleloggerparameters:NoSummary"
         ],
         "group": "build",
         "presentation": {
            // Reveal the output only if unrecognized errors occur.
            "reveal": "silent"
         },
         // Use the standard MS compiler pattern to detect errors, warnings and infos
         "problemMatcher": "$msCompile"
      }
   ]
}
{
    "workbench.startupEditor": "none",
    "C_Cpp.updateChannel": "Insiders",
    "editor.renderControlCharacters": true,
    "editor.tabSize": 3,
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingOvertype": "never",
    "editor.autoClosingQuotes": "never",
    "editor.accessibilitySupport": "off",
    "editor.formatOnType": true,
    "task.autoDetect": "off",
    "platformio-ide.useBuiltinPIOCore": true,
    "workbench.enableExperiments": false,
    "workbench.list.automaticKeyboardNavigation": false,
    "workbench.view.alwaysShowHeaderActions": true,
    "extensions.autoUpdate": false,
    "update.enableWindowsBackgroundUpdates": false,
    "update.mode": "none",
    "telemetry.enableCrashReporter": false,
    "breadcrumbs.enabled": true,
    "editor.renderWhitespace": "all",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"
} 

{Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///C:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/browser/ui/codiconLabel/codicon/codicon.ttf?be537a78617db0869caa4b4cc683a24a
workbench.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///C:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/theme-seti/icons/seti.woff
workbench.desktop.main.js:sourcemap:259 [Extension Host] activating extension
workbench.desktop.main.js:sourcemap:259 [Extension Host] starting language server
2workbench.desktop.main.js:sourcemap:259 [Extension Host] (node:10768) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:sourcemap:259
workbench.desktop.main.js:sourcemap:259 [Extension Host] Git installation not found.
t.log @ workbench.desktop.main.js:sourcemap:259
workbench.desktop.main.js:sourcemap:259 [Extension Host] runCommand platformio Array(1) Object
workbench.desktop.main.js:sourcemap:259 [Extension Host] Found PIO Core 4.2.1
workbench.desktop.main.js:sourcemap:259 [Extension Host] runCommand platformio Array(8) Object
workbench.desktop.main.js:sourcemap:259 [Extension Host] runCommand C:\Users\User\.platformio\penv\Scripts\python.exe Array(1) Object
workbench.desktop.main.js:sourcemap:259 [Extension Host] C:\Users\User\.platformio\penv\Scripts\python.exe
workbench.desktop.main.js:sourcemap:259 [Extension Host] runCommand C:\Users\User\.platformio\penv\Scripts\python.exe Array(2) Object

process.env
{ALLUSERSPROFILE: "C:\ProgramData", APPDATA: "C:\Users\User\AppData\Roaming", CommonProgramFiles: "C:\Program Files\Common Files", CommonProgramFiles(x86): "C:\Program Files (x86)\Common Files", CommonProgramW6432: "C:\Program Files\Common Files", …}

**Comment by al-davis** [comment]
Is other information needed ?

**Comment by alexr00** [comment]
Can you share the value of `process.env["Path"]` from the console?

**Comment by al-davis** [comment]
From the above post.  Is this what you want ?
process.env
{ALLUSERSPROFILE: "C:\ProgramData", APPDATA: "C:\Users\User\AppData\Roaming", CommonProgramFiles: "C:\Program Files\Common Files", CommonProgramFiles(x86): "C:\Program Files (x86)\Common Files", CommonProgramW6432: "C:\Program Files\Common Files", …}

**Comment by al-davis** [comment]
process.env["Path"]
"C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\AOMEI Backupper;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin"

**Comment by alexr00** [comment]
It looks like msbuild isn't on your path, so when you run the task it doesn't know where msbuild is. If you add it to your path (for me, it is installed at `C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe`) then you should be back in business.
