### ISSUE TITLE
Git: Open Repository does not open the folder

### ISSUE THREAD

**Issue by ramgesg** [microsoft/vscode#90866]
Issue Type: <b>Bug</b>

Is this the expected behavior?
From the command pallette, while opening a git repo through `Git: Open Repository` the explorer shows `You have not yet opended a folder`

VS Code version: Code - Insiders 1.43.0-insider (6ec6f9e3f4d17f0cef0480688a1f350b9141e567, 2020-02-17T05:42:20.509Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (20.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
code-runner|for|0.9.15
docthis|joe|0.7.1
vscode-devskim|MS-|0.2.2
python|ms-|2020.2.63072
remote-containers|ms-|0.101.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|3.9.20200215
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
vetur|oct|0.23.0
java|red|0.55.1
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-icons|vsc|10.0.0

</details>

**Comment by joaomoreno** [comment]
You might be looking for the `File: Open Folder...` command.

**Comment by ramgesg** [comment]
Shouldn't the `Git: Open Repository` open the folder as well?

**Comment by joaomoreno** [comment]
No, it opens a repository. You can have 0 open folders and N open repositories. You can also have N open folders and 0 open repositories. Folders are represented in the Explorer view. Repositories are represented in the SCM view.
