### ISSUE TITLE
Error while loading extensions. connect ENOENT //1.42.1-shared.sock

### ISSUE THREAD

**Issue by Architha18** [microsoft/vscode#90868]
Issue Type: <b>Bug</b>

Cannot load any extensions

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment]
Please provide repdoucable steps. I have no clue what you are doing.
Can you reproduce with vscode insdiers?

**Comment by Architha18** [comment]
There are not many steps to reproduce, i just can't load any extensions on VS Code
<img width="397" alt="Screenshot 2020-02-18 at 5 25 49 PM" src="https://user-images.githubusercontent.com/9497168/74734124-f1394380-5273-11ea-8cc6-601694bd7af6.png">

This has happened after a recent update.

**Comment by Architha18** [comment]
<img width="389" alt="Screenshot 2020-02-18 at 5 29 39 PM" src="https://user-images.githubusercontent.com/9497168/74734307-46755500-5274-11ea-9cd3-d63922e19338.png">

**Comment by joaomoreno** [comment]
1. Quit Code
2. Delete `/Users/architha/Library/Application Support/Code/1.42.1-shared.sock`

Retry. Does it fix it?

**Comment by Architha18** [comment]
yes it does, Thanks
