### ISSUE TITLE
Suggestion label cropped too soon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#90865]
* vscode workspace
* enable snippet suggestion
* type `@inject`

<img width="519" alt="Screenshot 2020-02-17 at 15 10 54" src="https://user-images.githubusercontent.com/1794099/74716997-e0ff7500-522f-11ea-96e4-8cd7b5cdd051.png">

**Comment by octref** [comment]
How can I make this happen? I tried a clean install with font size setting to 18:

![image](https://user-images.githubusercontent.com/4033249/75400288-ab076400-58b3-11ea-8c62-a691eba67bad.png)

And my default setup:

![image](https://user-images.githubusercontent.com/4033249/75400299-b3f83580-58b3-11ea-81b1-743e2e7b2780.png)

**Comment by jrieken** [comment]
<img width="697" alt="Screenshot 2020-02-27 at 09 17 15" src="https://user-images.githubusercontent.com/1794099/75424961-fec08e80-5941-11ea-9228-77c09e9900bc.png">

idk - for me this always happens... If that font dependent? I am using FiraCode, font size 13

**Comment by octref** [comment]
Found it. This only happens for `"editor.suggest.showIcons": false`.
