### ISSUE TITLE
Fonts in menu bar are grey

### ISSUE THREAD

**Issue by Toothless204** [microsoft/vscode#90873]
- VSCode Version: 1.42.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Install from the Snap Store
2. Simply open vscode

![Screenshot of the application](https://user-images.githubusercontent.com/38069888/74724295-f5457100-5233-11ea-91f1-10333f1581bb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe #90759

**Comment by isidorn** [comment]
Closing as duplicate
