### ISSUE TITLE
Hey there, I want to report the issue that we cannot edit / or put cursor at multiple places while writing code( via pressing one extra key such as ctrl etc).I hope the image will give you an insight of what I mean.

### ISSUE THREAD

**Issue by noobmaster440** [microsoft/vscode#90875]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Where is the image? Also, please use a shorter title and write the details in the description field.

**Comment by noobmaster440** [comment]
Please open the link for image

**Comment by gjsjohnmurray** [comment]
Seems to be a screenshot of Sublime Text containing a job application letter with lots of personal information.

Maybe you're looking for this doc:

https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

**Comment by noobmaster440** [comment]
Thank you sir. It's a great help.

**Comment by gjsjohnmurray** [comment]
@noobmaster440 then please close this issue.

**Comment by noobmaster440** [comment]
Okay , sir. Issue closed.
