### ISSUE TITLE
intgrated terminal

### ISSUE THREAD

**Issue by RomanovaDI** [microsoft/vscode#90878]
Issue Type: <b>Bug</b>

Integrated terminal does not working. I can't type anything there and in the list there is no "1: bash" option or any  other options, I've got just "1:" or "2:". In settings /bin/bash is chosen.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 2326)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|9.69GB (2.82GB free)|
|Process Argv|./ --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.50
latex-workshop|Jam|8.7.2
ctags-support|jay|1.0.19
python|ms-|2020.2.63072
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
cpptools|ms-|0.26.3
code-spell-checker|str|1.7.23
code-spell-checker-russian|str|0.2.4

(1 theme extensions excluded)

</details>

**Comment by slemly** [comment]
Adding to this - terminal window briefly appears then vanishes when the [control]+[`] key combo is used, and the same behavior occurs when the terminal is opened from the View or Terminal menu bar sections.

macOS Catalina 10.15.3 (19D76)
VS Code Version: 1.42.1
               Commit: c47d83b293181d9be64f27ff093689e8e7aed054
               Date: 2020-02-11T14:44:27.652Z

**Comment by Tyriar** [comment]
Can you share your settings.json file?

Do you see a notification when you try open a terminal?

Could you capture a trace log of when the terminal is launched, this will show what parameters are used when launching the process https://github.com/Microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by slemly** [comment]
A restart/refresh seed to fix it; I haven't had any issues with it for a few days. If there's a way to view a changelog of the settings.json, I can try to track down the version that allowed the issue to happen.

**Comment by Tyriar** [comment]
No that should be ok, just let us know if you see it again and provide the above information if you see it.

**Comment by RomanovaDI** [comment]
My problem is still actual. My settings.json:
{
    "latex-workshop.view.pdf.viewer": "tab",
    "cSpell.language": ",ru",
    "vim.history": 500,
    "editor.wordWrap": "on",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Solarized-light",
    "explorer.confirmDelete": false,
    "spellright.language": [
        "en_US",
        "ru_RU"
    ],
    "spellright.documentTypes": [
        "markdown",
        "latex",
        "plaintext"
    ],
    "terminal.integrated.inheritEnv": false,
    "terminal.integrated.shell.linux": "/bin/bash"
}
