### ISSUE TITLE
Multiple search tabs

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#90870]
Sometimes, when refactoring, I search for a keyword, then when browsing the result's code, I want to take a deeper look into it and do another (sub)search. Currently I need to remove the current content in the search bar and enter the other keyword, but then I lose the previous list of results along with the state of where I was, processing the results.

Feature request: add multiple tab support to search so multiple (nested) searches can be performed. Would be very useful for refactoring.

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_42#_search-editor

**Comment by JacksonKearl** [comment]
/duplicate #16488

But yes Search Editors are our answer to the "multiple search" use case.
