### ISSUE TITLE
Can't Debug

### ISSUE THREAD

**Issue by Ventus218** [microsoft/vscode#90872]
Issue Type: <b>Bug</b>

i just configured my tasks, launch and prooerties .json files but when i try to debug i get this Warning and the debugger just ignore my breakpoints.

Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
The program '/Users/Alessandro/Desktop/Prova VS-Code/main' has exited with code 0 (0x00000000).

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.15
cpptools|ms-|0.26.3

</details>

**Comment by isidorn** [comment]
Please file against the debug extension you are using. Thank you
