### ISSUE TITLE
Relative path menu entry not available on splitted window pane

### ISSUE THREAD

**Issue by crazycodr** [microsoft/vscode#90885]
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-7625-generic

Steps to Reproduce:

1. Open 3 or more files
2. Drag one to the right to split the code view
3. Right click on the tab, no option to "Copy path" or "Copy relative path"
4. Drag another file from left split to right split
5. Right click on the tab of the original file, options are present
6. Drag the 3rd file back to the left side
7. Right click on the tab of the original file, options are still present
8. Drag the 2nd file back to the left side, options are present
9. Draw the 2nd file to the rigth to create a new code view, options are **not** present anymore

Does this issue occur when all extensions are disabled?: Yes

**More info in case it might help**
1. I have a saved workspace, can't seem to reproduce with a brand new code window
2. Workspace has multiple folders (projects) attached to it
3. Files are from the same project but different paths (app/backend/controllers/, tests/app/backend/controllers/)
4. Project is PHP based

**Comment by bpasero** [comment]
Hm good catch, not sure yet what this is. Open for help, I suspect an issue with context keys somehow.

**Comment by MarkBouk** [comment]
I was able to reproduce this issue. I would be interested in attempting to make the fix if you don't mind. I have been looking for an entry point to contributing.

**Comment by bpasero** [comment]
Thanks but I think this was really hard to figure out.
