### ISSUE TITLE
Process restarting

### ISSUE THREAD

**Issue by mentesan** [microsoft/vscode#90886]
Issue Type: <b>Bug</b>
VSCode reported it has restarted TypeScript plugin too many times and would not restart again.

Just installed and opened VSCode.

VS Code version: Code - Insiders 1.43.0-insider (6ec6f9e3f4d17f0cef0480688a1f350b9141e567, 2020-02-17T05:42:20.509Z)
OS version: Windows_NT x64 10.0.19564

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (15.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.42.3
powershell-preview|ms-|2020.1.0
vim|vsc|1.12.4

</details>

**Comment by mjbvz** [comment]
1. In VS Code, run `Developer: Toggle developer tools`
1. In the developer tools, open the console
1. Please share any errors/warnings that are printed in there
