### ISSUE TITLE
VSC did't check that the variable "maybyNum" didn't exist, and it got stuck

### ISSUE THREAD

**Issue by bonasort** [microsoft/vscode#90882]
Issue Type: <b>Bug</b>

def isAGoodGuess(self,chars,top):
        isOk = False
        maybeNum = 0
        pseudo = chars.strip()
        
       try: 
            maybeNum = int(pseudo)   #### HERE can produce an exeption
            isOk = (maybeNum >=0) and (maybyNum <=top) 
        except:
            isOk = False
        finally:
            pass
        #e-try
        return isOk 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19564

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 x 2128)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.68GB (2.78GB free)|
|Process Argv|C:\Users\josep\Google Drive\LT-pep\python\005 guessgame\tools.py|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Please file this against the extension you are using. Thank you very much
