### ISSUE TITLE
Setting "Quick Open Close on Focus Lost" UI and behavior fail to accord

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90880]
This settings value

![image](https://user-images.githubusercontent.com/6157073/74734548-b240c900-5246-11ea-932c-312933b69c5b.png)

affects Quick Open as expected, but Command Palette too.

V1.42.1 on Windows 7.

**Comment by chrmarti** [comment]
These are the same widget, the setting controls them both. That is as intended.

**Comment by chrisjj** [comment]
> These are the same widget, the setting controls them both. 

Thank for the confirmation.

> That is as intended.

Figures. But I really doubt the reported issue is intended.

**Comment by chrisjj** [comment]
> chrmarti added the needs more info label 2 hours ago

What more info?

**Comment by chrmarti** [comment]
It sounds like you would want separate settings to control QuickOpen and the Command Palette separately. These are really the same UI.
