### ISSUE TITLE
Open or close projects

### ISSUE THREAD

**Issue by oOAkiraOo** [microsoft/vscode#90895]
Issue Type: <b>Feature Request</b>

Hello, 
I would like to close or open projects in a workspace like the Eclipse IDE, because I have many microservices in projects and sometimes I use 3 or less of them. I think it will be easy to see the project (it can appear in the project as prioritized) and the search feature can only be searched in the open project (it is more practical and the search feature can have the search flag only in open projects).

Best regards.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
There are already requests like this thus closing as duplicate and you can search through our issues
