### ISSUE TITLE
Miss some icons

### ISSUE THREAD

**Issue by cj1024** [microsoft/vscode#90892]
Issue Type: <b>Bug</b>

Missing some icons in side bar and bottom bar
![d5c882d8-c001-4126-aba3-8f1a1ff13d5e.png](https://storage.live.com/items/466EFEB9563FF263!3672133?authkey=AAvwilPT5OKbBb0)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19564

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (107)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-base64|ada|0.1.0
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|10.7.0
vscode-icontheme-nomo-dark|be5|1.3.6
imagepreview|buz|0.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
vscode-qrcode|Com|0.2.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.0.15
githistory|don|0.5.3
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
json-tools|eri|1.0.2
prettier-vscode|esb|3.20.0
unixtime-converter|esp|0.0.2
vs-code-xml-format|fab|0.1.5
vscode-diff|fab|1.4.0
vscode-firefox-debug|fir|2.6.1
vscode-npm|fkn|3.3.0
url-encode|fle|1.1.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
terminal|for|0.0.10
jsx-beautify|gog|0.0.5
todo-tree|Gru|0.0.167
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
easy-icons|jam|0.3.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
code-eol|jef|1.0.11
react-component|jer|1.0.4
diff-tool|jin|0.0.1
svg|joc|1.1.1
docthis|joe|0.7.1
minifyall|jos|2.1.4
testing-regex|jus|0.0.2
swift|Kas|0.2.0
vscode-codemetrics|kis|1.24.0
vscode-gutter-preview|kis|0.25.0
vscode-simple-icons|Lau|1.12.0
vscode-regexp-preivew|le0|0.0.3
node-module-intellisense|lei|1.5.0
syntax-project-pbxproj|mar|0.1.3
ecdc|mit|1.3.0
vscode-html-format|moh|0.0.4
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.15
vscode-azurefunctions|ms-|0.20.2
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.63072
remote-wsl|ms-|0.42.3
atom-keybindings|ms-|3.0.6
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
node-debug2|ms-|1.42.1
vsliveshare|ms-|1.0.1615
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.0
vuejs-extension-pack|mub|1.1.5
color-highlight|nau|2.3.0
live-server-preview|neg|0.1.4
vscode-for-node-js-development-pack|nod|2.0.1
vetur|oct|0.23.0
es6-css-minify|olb|3.3.2
fix-json|oli|0.1.2
ios-snippets|orn|0.0.15
vscode-ios-common-files|Ort|1.0.5
open-html-in-browser|pea|2.1.2
diff|raf|0.0.1
json-organizer|rin|0.0.4
LiveServer|rit|5.6.1
vscode-essentials-snippets|rob|2.0.0
partial-diff|ryu|1.4.1
vue-vscode-snippets|sdr|1.8.0
preview-vscode|sea|2.0.3
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
markdown-preview-enhanced|shd|0.5.2
code-spell-checker|str|1.7.23
vscode-material-ui-snippets|Swo|1.0.1
html-preview-vscode|tht|0.2.5
vscode-status-bar-format-toggle|tom|2.0.0
vscode-iconfont-preview|und|0.1.0
ramdajs-snippets|use|1.0.5
vscode-icons|vsc|10.0.0
vscode-mermaid-preview|vst|1.5.0
gitblame|wad|3.0.1
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0
vscode-preview-server|yui|1.3.0
markdown-all-in-one|yzh|2.7.0
material-theme|zhu|3.2.2
vscode-firstupper|zki|0.2.1

(13 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Some of your extensions is breaking this. Just unsinstall all extensions and it should work. Or just use vscode insdiers
