### ISSUE TITLE
Enable running PowerShell with Arguments (ex: -sta)

### ISSUE THREAD

**Issue by PeterHodges15** [microsoft/vscode#90896]
Issue Type: <b>Feature Request</b>

In Settings.JSON I can specify:
    "powershell.powerShellAdditionalExePaths": [
	{
	    "exePath": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
	    "versionName": "7-preview",
	},
But this does not enable me to start up Powershell with certain arguments.
Namely I want to start like:
    "powershell.powerShellAdditionalExePaths": [
	{
	    "exePath": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
	    "Arguments": "-sta",
	    "versionName": "7-preview",
	},
so that the thread starts in "Single-Threaded Apartment" (This cannot be changed once started)

VS Code version: Code - Insiders 1.43.0-insider (595f98455be0aac7372a0ae7841efae9b91b848e, 2020-02-18T13:52:42.988Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Please file against Powershell extension. Thanks
