### ISSUE TITLE
"Toggle View Mode" for Search.

### ISSUE THREAD

**Issue by yasintz** [microsoft/vscode#90898]
The **Toggle View Mode** feature is not available for _search_.
Do not hesitate to close this issue, if any.
If not, can it be done ?

**Comment by JacksonKearl** [comment]
What do you mean by `Toggle View Mode`? Like moving it to the panel? You can right-click the search viewlet and select "Move to Panel".

![image](https://user-images.githubusercontent.com/8586769/74763554-e01d1200-5234-11ea-94da-471f7004148f.png)

**Comment by yasintz** [comment]
No @JacksonKearl  
![Screenshot_18](https://user-images.githubusercontent.com/36041339/74764410-b4307980-5292-11ea-96a5-195d7b2ec173.png)

**Comment by JacksonKearl** [comment]
Duplicate of #90898

**Comment by yasintz** [comment]
> Duplicate of #90898

Both are the same issue. not a duplicate.

**Comment by JacksonKearl** [comment]
Oops, my bad. #20224.
