### ISSUE TITLE
JSX Interpolation Issue with Embedded JavaScript Expressions

### ISSUE THREAD

**Issue by andrewjmead** [microsoft/vscode#90897]
- VSCode Version: 1.42.1
- OS Version: macOS Catalina 10.15.2

### Steps to Reproduce:

1. Create a JavaScript file
2. Paste in the following code:
```
const someJSX = (
    <p>{</p>
)
```
3. Add the closing curly brace for the expression.

### Expected result:

```
const someJSX = (
    <p>{}</p>
)
```

### Actual result:

```
const someJSX = (
<p>{}</p>
)
```

I noticed this come up sometime within the last month. I found others with the same issue [here](https://old.reddit.com/r/vscode/comments/eyvlyo/issue_with_jsx_interpolation/) and [here](https://twitter.com/andrew_j_mead/status/1229805049611792385).

Does this issue occur when all extensions are disabled?: Yes

I have tested this without extensions. I have also tested this with both javascript and javascriptreact language modes. I have a very minimal set of user settings shown below:

```
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.fontSize": 13,
    "editor.hover.enabled": false
}
```

Thanks for taking a look.

**Comment by andrewjmead** [comment]
I ran some tests on my end, and this issue seems to have first come up in version 1.40 (October 2019. Everything worked as expected in version 1.39 and 1.38.

**Comment by mjbvz** [comment]
As a partial workaround, set `"editor.formatOnType": true`. This still de-dents on `}` but then immediately re-indents things

**Comment by andrewjmead** [comment]
Yeah. It's a little jumpy, but it does indeed work. For the moment, I'll stick with 1.39.

**Comment by dormesica** [comment]
If I got some direction on where to start looking I would be glad to help with that.

**Comment by andrewjmead** [comment]
I was digging around in `extensions/javascript/`, but I have no idea if that's the right place or not.

**Comment by mjbvz** [comment]
This probably needs to be fixed in core VS Code. I suspect our indentation rules have a bug around mixed language files (we have different indentation rules for inside jsx tags and for regular JS)

@rebornix Do you have any suggestions on where someone would start investigating this issue?

**Comment by JW9506** [comment]
Glad somebody brings this up. It isn't a huge issue but it does throw people off when something suddenly indents your code.

**Comment by JW9506** [comment]
![image](https://user-images.githubusercontent.com/34848995/81034782-23ffda80-8e66-11ea-9311-93f81e6cfaaa.png)
I figured simply selecting "Advanced" in Editor: Auto Indent will resolve this issue

**Comment by dougkrahmer** [comment]
I was going to report this issue too. Hopefully a fix can be committed soon. I've tried the **Auto Indent: Advanced** workaround, and it seems to work without unwanted side effects in JS and JSX. I am worried about the impact of the setting on other language, as it will vary based on how they define their own indentation rules.

**Comment by u3u** [comment]
As a supplement, can the closing curly brace be typed automatically in jsx/tsx?

**Comment by rebornix** [comment]
I pushed a change to stop any auto indentation if the line contains multiple languages (in this case it's jsx and typescript).

**Comment by meganrogge** [comment]
@rebornix this doesn't look like expected behavior. am I doing something wrong? 
![recording (63)](https://user-images.githubusercontent.com/29464607/101071677-c776b200-3551-11eb-93df-3c66d86b0ae3.gif)

**Comment by mjbvz** [comment]
@meganrogge You need to be in the `javascript react` language mode for this to work. Otherwise JSX expressions are not fully supported.

You can either change the language manually or use `.jsx` files

Marking as verified based on my testing
