### ISSUE TITLE
Debug console uses 'ctrl+click' to follow links.

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#90891]
Debug console uses `ctrl+click` to follow links. However, everywhere else in vscode we use `alt+click` to do the same.

**Comment by isidorn** [comment]
No, `ctrl` is everywhere. Most improtatnly in the explroer.
Where is altr + click for link following? Also on what platform are you?

**Comment by psclkhoury** [comment]
Forgot to add the info. I am on Windows.
And it is always alt+ click to open files from links (editor, problems panel, termnial, output panel...)

Examples:
![image](https://user-images.githubusercontent.com/9846892/74754310-b9310100-5271-11ea-86ad-ccde5c73dcec.png)

![image](https://user-images.githubusercontent.com/9846892/74754467-ee3d5380-5271-11ea-809d-ac90cdb5631a.png)

![image](https://user-images.githubusercontent.com/9846892/74754671-41170b00-5272-11ea-84d8-0f89b85462aa.png)


Debug Console:
![image](https://user-images.githubusercontent.com/9846892/74754494-f9907f00-5271-11ea-86a2-8cd46b1f4e2a.png)


Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
You pobably have some setting for this. And it seems like the debug console is not supporting this setting.
I am open for a PR which fixes this.
Code pointer https://github.com/microsoft/vscode/blob/33e78e0978b032d6cddef69bcc650a1d488d7297/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L148

**Comment by psclkhoury** [comment]
> You pobably have some setting for this. And it seems like the debug console is not supporting this setting.

 I don't think it is a setting. But looking through the code, I saw somewhere a check if the multiCursorModifier == ctrlCmd.
If that is the case then, `alt+click` is used instead of `ctrl+click`.


> I am open for a PR which fixes this.

Okay nice. I will give it a go (will be my first time). Can I also make the casing of `alt` consistent? If yes then should the first letter be capitalized or not?

**Comment by isidorn** [comment]
@psclkhoury let's go with small caps `alt`. That is more recognizable to users imho.
Thanks!

**Comment by psclkhoury** [comment]
@isidorn I tried to fix the issue and this is what I have so far.
The keybinding to follow the link depends on the setting of `editor.multiCursorModifier` as in other parts of the code. 
There is one thing that is still missing. If a link is already decorated in the `debug console` with `Follow link (alt+click)`, then I change the setting `editor.multiCursorModifier` from `ctrlCmd` to `alt`, then the decorated link in the debug console does not change.

In the other views there is some kind of listener to this setting and the tooltip/keybinding is updated accordingly. But I don't know how to do that.

```diff
diff --git a/src/vs/workbench/contrib/debug/browser/linkDetector.ts b/src/vs/workbench/contrib/debug/browser/linkDetector.ts
index ff264cc8c2..d09c4ac75c 100644
--- a/src/vs/workbench/contrib/debug/browser/linkDetector.ts
+++ b/src/vs/workbench/contrib/debug/browser/linkDetector.ts

+       private _getModifierKey(): 'alt' | 'meta' | 'ctrl' {
+               const multiCursorModifer = this._configurationService.getValue<'ctrlCmd' | 'alt'>('editor.multiCursorModifier');
+               if (multiCursorModifer === 'ctrlCmd') {
+                       return 'alt';
+               } else {
+                       if (platform.isMacintosh) {
+                               return 'meta';
+                       } else {
+                               return 'ctrl';
+                       }
+               }
+       }
+
+       private _getLinkHoverString(modifierKey: 'alt' | 'meta' | 'ctrl'): string {
+               const tooltipLabel = localize('links.navigate.follow', 'Follow link');
+
+               const tooltipKeybinding = modifierKey === 'ctrl'
+                       ? localize('fileLink.ctrl', 'ctrl + click')
+                       : modifierKey === 'meta'
+                               ? localize('fileLinkMac.cmd', 'cmd + click')
+                               : platform.isMacintosh ? localize('fileLinkMac.option', 'option + click') : localize('fileLink.alt', 'alt + click');
+
+               return `${tooltipLabel} (${tooltipKeybinding})`;
+       }
+
        private decorateLink(link: HTMLElement, onclick: () => void) {
                link.classList.add('link');
-               link.title = platform.isMacintosh ? nls.localize('fileLinkMac', "Cmd + click to follow link") : nls.localize('fileLink', "Ctrl + click to follow link");
-               link.onmousemove = (event) => { link.classList.toggle('pointer', platform.isMacintosh ? event.metaKey : event.ctrlKey); };
+               const modifierKey = this._getModifierKey();
+               link.title = this._getLinkHoverString(modifierKey);
+               link.onmousemove = (event) => {
+                       link.classList.toggle('pointer', modifierKey === 'meta' ? event.metaKey : modifierKey === 'ctrl' ? event.ctrlKey : event.altKey);
+               };
                link.onmouseleave = () => link.classList.remove('pointer');
                link.onclick = (event) => {
                        const selection = window.getSelection();
                        if (!selection || selection.type === 'Range') {
                                return; // do not navigate when user is selecting
                        }
-                       if (!(platform.isMacintosh ? event.metaKey : event.ctrlKey)) {
+                       if (!((modifierKey === 'meta' && event.metaKey) || (modifierKey === 'ctrl' && event.ctrlKey) || (modifierKey === 'alt' && event.altKey))) {
                                return;
                        }
                        event.preventDefault();
```

**Comment by isidorn** [comment]
Feel free to create a PR. Try to make it elegent, the less code there is the higher chance that we merge it in. 
If you do not have time I can look into this in the future. Thanks!

**Comment by justingrant** [comment]
Still a problem. Would be great to see a fix for this!

**Comment by dbcam** [comment]
On my setup (Windows) ctrl-click on a link doesn't work, but alt-ctrl-click does!
