### ISSUE TITLE
Update problems (diagnostics) on file modification

### ISSUE THREAD

**Issue by pkruk2** [microsoft/vscode#90890]
### Introduction

Problems view shows Diagnostic. Some of them generated on the fly, as the user types code - for example from C# extension, from tslint etc. Other are "static" - generated on some action, for example after running a build, the build output is parsed.

### Current behaviour

For "static" Diagnostics, when user edits source file, the Diagnostics in Problems view are getting out of sync. They still point to the old location. 

For example after running build I got following Problem about non existing name:

![1 after build](https://user-images.githubusercontent.com/34373523/74745370-1756e780-5264-11ea-8b22-0844a4490a76.jpg)

As you can see, the entry in the Problems view has the "9, 48" location, so it's line 9. In editor, the squiggly line also correctly underlines the "foo" name.

Below you can see what happens after I add a new line just above the Console.WriteLine (the build action is not run):

![2 file edited](https://user-images.githubusercontent.com/34373523/74745569-63099100-5264-11ea-870a-cdd2161bfc36.jpg)

The "foo" name is now in line 10. **The squiggly line was updated, it still correctly underlines the "foo" name. But in the Problems view, the Diagnostic entry still retains old locations, that is line 9. Clicking on it takes me to the old/wrong location.**

### Proposed improvement

Please add mechanism to easily update Diagnostics after used edits source file. I expect you already have it somehow handled, because the squiggly lines locations are updated. And you already have connection between squiggly line and the Diagnostic problem, so it should be possible to update Diagnostics locations too.

**Comment by sandy081** [comment]
By static diagnostics you mean those created using tasks?

**Comment by pkruk2** [comment]
Yes, for example those created using tasks.

But it could/should also work for diagnostic created by extensions. For example we're creating an extension right now, which provides command to execute external tool which analyzes source files and produces xml. This xml is then parsed and converted to diagnostics. When user edits the source files, the diagnostic are not updated and point to incorrect location.

**Comment by sandy081** [comment]
I would start with tasks first to check if they are creating diagnostics correctly.

**Comment by alexr00** [comment]
I think that the diagnostic is created correctly. The task runs, creates markers, then exits. Once the task exists the markers are only changed once the task runs again. This is the expected behavior.

The behavior you want for tasks is already supported with background tasks and watching problem matchers. To have a task that creates markers that change, you'll have to convert your task into a background task and your problem matcher into a watching problem matcher. https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks

**Comment by pkruk2** [comment]
No, it does not cover my needs.

In my case the action of creating diagnostics is triggered manually by user. Also, it is not a task, but an extension that creates the diagnostics. Converting it into background task and using watching problem matcher is not possible.

I understand that it currently works as designed, which is why this issue is a feature request, not a bug report. My hope was that since vscode already knows how to update range (squiggly lines) when user edits source code, this could be exposed as an API that could be used either explicitly by extension (which would cover my needs), or implicitly to update diagnostics reported from tasks (which I don't need but seems reasonable).

Right now I have implemented onDidChangeTextDocument and I'm updating diagnostics myself. It works quite well, but it's not a straightforward code, and it's a work that need to be re-done by many extension authors which provide diagnostics which are not re-created on every source code change.

**Comment by alexr00** [comment]
@sandy081 looks like the use-case isn't a task.

**Comment by sandy081** [comment]
> My hope was that since vscode already knows how to update range (squiggly lines) when user edits source code,

Not sure if this is true. We always update all diagnostic decorations (including squigglies) using diagnostics information. Otherwise it should be a bug from our side. Can you please provide a sample extension that I can reproduce this behaviour?

**Comment by pkruk2** [comment]
I was able to reproduce this using the official extension samples: https://github.com/microsoft/vscode-extension-samples/tree/master/diagnostic-related-information-sample

1. you have to comment out the `onDidChangeActiveTextEditor` subscription
2. the code did not compile on my machine, had to update dependencies
Pasting diff with those changes at the end for your convenience.

The sample extension shows a diagnostic on the `sample-demo.rs` file when you open it. You can edit the file, for example add a new line before the squiggly line, and the squiggle will be updated. But the diagnostic location will still point to the old location - problems view has old location and clicking on it will take you to the original location.

```
diff --git a/diagnostic-related-information-sample/package-lock.json b/diagnostic-related-information-sample/package-lock.json
index cb876b0..3d9b9de 100644
--- a/diagnostic-related-information-sample/package-lock.json
+++ b/diagnostic-related-information-sample/package-lock.json
@@ -308,9 +308,9 @@
 			}
 		},
 		"typescript": {
-			"version": "3.4.5",
-			"resolved": "https://registry.npmjs.org/typescript/-/typescript-3.4.5.tgz",
-			"integrity": "sha512-YycBxUb49UUhdNMU5aJ7z5Ej2XGmaIBL0x34vZ82fn3hGvD+bgrMrVDpatgz2f7YxUMJxMkbWxJZeAvDxVe7Vw==",
+			"version": "3.8.2",
+			"resolved": "https://registry.npmjs.org/typescript/-/typescript-3.8.2.tgz",
+			"integrity": "sha512-EgOVgL/4xfVrCMbhYKUQTdF37SQn4Iw73H5BgCrF1Abdun7Kwy/QZsE/ssAy0y4LxBbvua3PIbFsbRczWWnDdQ==",
 			"dev": true
 		},
 		"wrappy": {
diff --git a/diagnostic-related-information-sample/package.json b/diagnostic-related-information-sample/package.json
index 295ae73..2e3f5cd 100644
--- a/diagnostic-related-information-sample/package.json
+++ b/diagnostic-related-information-sample/package.json
@@ -21,9 +21,9 @@
 		"watch": "tsc -watch -p ./"
 	},
 	"devDependencies": {
-		"@types/node": "^7.0.43",
+		"@types/node": "^12.11.7",
 		"tslint": "^5.16.0",
-		"typescript": "^3.5.1",
+		"typescript": "^3.6.4",
 		"@types/vscode": "^1.32.0"
 	}
 }
diff --git a/diagnostic-related-information-sample/src/extension.ts b/diagnostic-related-information-sample/src/extension.ts
index 3764012..2d625d4 100644
--- a/diagnostic-related-information-sample/src/extension.ts
+++ b/diagnostic-related-information-sample/src/extension.ts
@@ -8,11 +8,11 @@ export function activate(context: vscode.ExtensionContext) {
 	if (vscode.window.activeTextEditor) {
 		updateDiagnostics(vscode.window.activeTextEditor.document, collection);
 	}
-	context.subscriptions.push(vscode.window.onDidChangeActiveTextEditor(editor => {
-		if (editor) {
-			updateDiagnostics(editor.document, collection);
-		}
-	}));
+	// context.subscriptions.push(vscode.window.onDidChangeActiveTextEditor(editor => {
+	// 	if (editor) {
+	// 		updateDiagnostics(editor.document, collection);
+	// 	}
+	// }));
 }
 
 function updateDiagnostics(document: vscode.TextDocument, collection: vscode.DiagnosticCollection): void {
```

**Comment by pkruk2** [comment]
To be precise, with the sample extension, you may need to have the `sample-demo.rs` file opened and active when the extension activates.

**Comment by pkruk2** [comment]
Do you still need more info?

**Comment by sandy081** [comment]
Will try it out and let you know if needed.

**Comment by pkruk2** [comment]
This issue was incorrectly closed. All required info was provided.

**Comment by sandy081** [comment]
This is a bug from our side that squiggles are not updated on content change. Fixed it.

To verify:

- Use the sample - https://github.com/microsoft/vscode-extension-samples/tree/master/diagnostic-related-information-sample
- Comment out the onDidChangeActiveTextEditor subscription at line 11
- Run the extension and open `sample-demo.rs` file available in the same sample
- add a new line before the squiggly line, and the squiggle should remain at the same location

**Comment by pkruk2** [comment]
> This is a bug from our side that squiggles are not updated on content change
> To verify:

Hmm I'm not sure about that.
The squiggles were updated. It's the diagnostics in the Problems view that were not updated.

So either a different issue was fixed than reported, or the verification step must be extended to check the the Problems view.

> add a new line before the squiggly line, and the squiggle should remain at the same location

I hope "same location" means same code should be underlined, not the same line, column values (which would mean the new line...)

**Comment by sandy081** [comment]
@pkruk2 

> The squiggles were updated. It's the diagnostics in the Problems view that were not updated.

It is not correct. Squiggle were out of sync with diagnostics. It is responsibility of the diagnostics owner to update the diagnostics on content change and update them.

**Comment by pkruk2** [comment]
@sandy081  

In my case the squiggles were updated after content change. Yes, they became out of sync with diagnostics after that:
- the squiggles pointed to new location after content change
- the diagnostic pointed to old location after content change

**Do I understand correctly, that you consider the update of the squiggle as the bug, and changed it to not be updated on content change?**

That's the opposite of what I hoped ;)

**Yes, now both squiggle and diagnostic point to the same location, but on the other hand that location is wrong... Is it possible to have a feature of updating both squiggle and diagnostic to point to the new location?**

**Comment by sandy081** [comment]
In short, VS Code shall not make any assumptions about the content edits and cause models to be out of sync. It is extension's responsibility to update the diagnostics and keep them in sync.

> Is it possible to have a feature of updating both squiggle and diagnostic to point to the new location?

Yes, you can file that agains the corresponding extension.

**Comment by pkruk2** [comment]
Thanks.

**Comment by dbaeumer** [comment]
Doesn't work for me or I misunderstand what the behavior should be. Here is what I see

<img width="702" alt="capture" src="https://user-images.githubusercontent.com/1931590/80618298-734ba280-8a43-11ea-8d8c-0570d8efbec7.png">

and then after inserting a new line

<img width="579" alt="capture" src="https://user-images.githubusercontent.com/1931590/80618337-82caeb80-8a43-11ea-922b-a2b302379c50.png">

which looks wired to me. I would have expected that `x = 6;` is still squiggled.

**Comment by sandy081** [comment]
@dbaeumer Yes whatever you see is expected. 

>  I would have expected that x = 6; is still squiggled

To have this, corresponding diagnostic has to be updated. All diagnostics related UI should be in sync with diagnostics.

**Comment by sandy081** [comment]
Here are the steps to verify

To verify:

- Use the sample - https://github.com/microsoft/vscode-extension-samples/tree/master/diagnostic-related-information-sample
- Comment out the onDidChangeActiveTextEditor subscription at line 11
- Run the extension and open `sample-demo.rs` file available in the same sample
- squiggly is shown on line 4
- add a new line before the squiggly line
- Verify that squiggly should remain at same line 4
