### ISSUE TITLE
Cannot connect to wsl not install vscode-remote

### ISSUE THREAD

**Issue by ernestochaves** [microsoft/vscode#90899]
Issue Type: <b>Bug</b>

This worked yesterday, today cannot edit or do anything. I get errors about not being able to install extensions, cannot connect to server, etc. Like 
Unable to open 'Tarea2': Unable to read file 'vscode-remote://wsl+ubuntu/mnt/c/Users/myuser/folder' (Error: connect ENETUNREACH 127.0.0.1:52176). 

My list of extensions wont load. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'WSL: Ubuntu' failed: connect ENETUNREACH 127.0.0.1:52176

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.90GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/Users/Ernesto/JupiterHomework/Tarea2 --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: connect ENETUNREACH 127.0.0.1:52176
</details>Extensions: none

**Comment by aeschli** [comment]
It's likely unrelated to the WSL extesnion. Try to shutdown the WSL distro and restart it.
`wsl -d <distro> --shutdown`

**Comment by ernestochaves** [comment]
Please close. This was blocked by Windows defender. Was working until the
day before.
