### ISSUE TITLE
Errors remain even when fixed when running in watch mode

### ISSUE THREAD

**Issue by nilshedstrom** [Microsoft/vscode#909]
I run webpack from Visual Studio Code (0.10.3). When an error is found by webpack it is found by Visual Studio Code (I can see it when I press Ctrl+Shift+M). 
But when I correct the error I can still see it when I press Ctrl+Shift+M. I would like to dissapear from that list so I know which real errors that real.
Even when I terminate the task and run it again the error remain when I press Ctrl+Shift+M.
When I trigger the task normally (Ctrl+Shift+B) without watch then the errors dissapear after I fix them.

This is the task from tasks.json

			"args": [
				"-d",
				"--watch" 
			],
			"suppressTaskName": true,
			"taskName": "webpack watch",
			"showOutput": "silent",
			"isWatching": true,
				"problemMatcher": [{
				"owner": "webpack",
				"fileLocation": ["relative", "${workspaceRoot}"],
				"severity": "warning", 
				"pattern": [
					{
					"regexp": "WARNING in (.*)",	
					"file" : 1 
					},
					{
					"regexp": "\\[(\\d+),\\s(\\d+)\\]:\\s(.*)",
					"line":1,
					"column": 2,
					"message": 3
					}			
					]
				},
				{
				"owner": "webpack",
				"fileLocation": ["relative", "${workspaceRoot}"],
				"severity": "error", 
				"pattern": [
					{
					"regexp": "ERROR in (.*)",	
					"file" : 1 
					},
					{
					"regexp": "\\((\\d+),(\\d+)\\):(.*)",
					"line":1,
					"column": 2,
					"message": 3
					}			
					]
				}]

**Comment by dbaeumer** [comment]
Besides setting isWatching to true you need to tell the problem matcher when a watch runs begins and when it ends. To do so you can add a watching property to the problem matcher. For TypeScript this looks like this:

```json
watching: {
	activeOnStart: true,
	beginsPattern: { regexp: /^\s*(?:message TS6032:|\d{1,2}:\d{1,2}:\d{1,2} (?:AM|PM) -) File change detected\. Starting incremental compilation\.\.\./ },
	endsPattern: { regexp: /^\s*(?:message TS6042:|\d{1,2}:\d{1,2}:\d{1,2} (?:AM|PM) -) Compilation complete\. Watching for file changes\./ }
}
```

which then treats output from the tsc compiler when run in watch mode:

message TS6042: Compilation complete. Watching for file changes.
message TS6032: File change detected. Starting incremental compilation...
extension.ts(21,2): error TS2304: Cannot find name 'xx'.
message TS6042: Compilation complete. Watching for file changes.

The task system assumes that a compiler generates all errors for every triggered compile. So if a file A has an error and a watch trigger the compile and the compiler doesn't generate an error on A the error gets removed from the system.

**Comment by altano** [comment]
@dbaeumer Is there a working example anywhere that works with a continuous watching build script?  I just can't get this to work.

**Comment by dbaeumer** [comment]
@altano while coming up with an example I discovered a bug when the watching task doesn't ignore documents open in the editor and I am pretty sure you are hit by this I fixed the bug and a fix will be available in the next update. A full example for a watching task using the tsc compiler looks like this

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-w", "-p", "."],
    "showOutput": "silent",
    "isWatching": true,
    "problemMatcher": {
        "fileLocation": "relative",
        "pattern": {
            "regexp": "^([^\\s].*)\\((\\d+|\\d+,\\d+|\\d+,\\d+,\\d+,\\d+)\\):\\s+(error|warning|info)\\s+(TS\\d+)\\s*:\\s*(.*)$",
            "file": 1,
            "location": 2,
            "severity": 3,
            "code": 4,
            "message": 5
        },
        "watching": {
            "activeOnStart": true,
            "beginsPattern": "^\\s*(?:message TS6032:|\\d{1,2}:\\d{1,2}:\\d{1,2} (?:AM|PM) -) File change detected\\. Starting incremental compilation\\.\\.\\.",
            "endsPattern": "^\\s*(?:message TS6042:|\\d{1,2}:\\d{1,2}:\\d{1,2} (?:AM|PM) -) Compilation complete\\. Watching for file changes\\."
        }
    }
}
```

**Comment by alexdresko** [comment]
@dbaeumer Dunno if this is the best place to ask, but can you explain `watchedTaskEndsRegExp` and `watchedTaskBeginsRegExp`, please?

**Comment by nevir** [comment]
> a bug when the watching task doesn't ignore documents open in the editor

Why would you want the watching task to ignore open documents? I'd love to additional problem matching on documents I'm working on, too.

**Comment by nevir** [comment]
Just to follow up, I believe I'm encountering the same issue for the following task definition:

```json
{
  "version": "0.1.0",
  "command": "./node_modules/.bin/gulp",
  "isShellCommand": true,
  "showOutput": "silent",
  "tasks": [
    {
      "taskName": "watch",
      "isBuildCommand": true,
      "showOutput": "silent",
      "isWatching": true,
      "problemMatcher": [
        {
          "fileLocation": ["relative", "${workspaceRoot}"],
          "pattern": [
            {
              "regexp": "^\\s*(error)\\s+([\\w\\-]+)\\s+(.*)$",
              "severity": 1,
              "code": 2,
              "message": 3
            },
            {
              "regexp": "^\\s*(.*):(\\d+):(\\d+)$",
              "file": 1,
              "line": 2,
              "column": 3
            }
          ],
          "watching": {
            "beginsPattern": "^.*\\[wulp\\].+Running.*\\.\\.\\.$",
            "endsPattern": "^.*\\[wulp\\] Tasks ran in \\d+ms$"
          }
        }
      ]
    }
  ]
}
```

**Comment by nevir** [comment]
Never mind! I can verify that this works on `master` - deleting my prior (misleading) comments :)

**Comment by dbaeumer** [comment]
watchedTaskEndsRegExp  and watchedTaskBeginsRegExp  is deprecated and got replaced by waching.beginsPattern and watching.endsPattern.

**Comment by alexdresko** [comment]
@dbaeumer Yay! Just got the insider update and it's fixed! Thank you!

**Comment by dbaeumer** [comment]
Assigning to @aeschli for verification.

**Comment by aeschli** [comment]
Marking as verified based on the comment from @alexdresko.
@dbaeumer If you want me to verify this as well then I need steps.

**Comment by dbaeumer** [comment]
@aeschli: makes sense to rely on @alexdresko 
@alexdresko: thanks for verifying

**Comment by ricjac** [comment]
This is still happening in v1.4.0.

I'm running a gulp task, using **"problemMatcher": "$eslint-stylish"** in **"isWatching": true** mode, but after fixing the error in the JS file, the error message remains in VSCode.

```javascript
{
    // tasks.json doco: http://code.visualstudio.com/docs/editor/tasks
    //multiple tasks: https://github.com/Microsoft/vscode/issues/981
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "showOutput": "always",
    "args": ["/C"],
    "tasks": [
        {
            "taskName": "gulp dev",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "gulp dev"
            ],
            "isWatching": true,
            "problemMatcher": "$eslint-stylish"
        },
        {
            "taskName": "gulp unit",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "gulp unit"
            ],
            "isWatching": false
        },
        {
            "taskName": "gulp unit debug",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "gulp unit --debug"
            ],
            "isWatching": true
        }
    ]
}
```

**Comment by aeschli** [comment]
@ricjac Please file a new issue so we can investigate...
