### ISSUE TITLE
Can we do more to prevent duplicate view ids from extensions?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#90904]
Last week, an issue arose around 2 extensions creating separate views with the same view ids. This is not supported by our contributable view model but we don't do anything to prevent. Further issues arose around the fact that we now map view ids to positions in the workbench.

What measures do we have in place to prevent duplicate ids?
Do we have code that handles duplicate ids at all?
Should we be doing more in the view descriptor service to handle duplicate ids from different extensions?

**Comment by sandy081** [comment]
We never supported custom views with duplicate ids. We already have a check that checks for uniqueness within container. I think we need to broaden this check across containers. Also as @sbatten suggested we shall also improve the doc and suggesting authors to create unique ids.

**Comment by sbatten** [comment]
updated checks here c303fc0ab24be137d4e365a024ec69cefbdfe979

**Comment by sbatten** [comment]
updated docs description da72f1fea39c4653a17aa44f08c88ee10467ecd5
