### ISSUE TITLE
{0} in ignored settings description

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90905]
![image](https://user-images.githubusercontent.com/2193314/74762892-98e25180-5233-11ea-8483-b1518175dba4.png)

Version: 1.43.0-insider (user setup)
Commit: 595f98455be0aac7372a0ae7841efae9b91b848e
Date: 2020-02-18T13:52:42.988Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by sandy081** [comment]
I don't see it

<img width="645" alt="image" src="https://user-images.githubusercontent.com/10746682/74766303-63665400-5285-11ea-89e2-ef20d7a875ce.png">

Are you on latest insiders?

**Comment by Tyriar** [comment]
It appears you fixed it in 62265b4ee2f0131ea53f6d3aa69247f61ebe16eb, however I still see it in today's Windows Insiders build somehow?

![image](https://user-images.githubusercontent.com/2193314/74767539-df3bae80-523b-11ea-8b7b-bd7c6cd75358.png)

**Comment by sandy081** [comment]
No clue. Could be your installation is corrupted?

**Comment by Tyriar** [comment]
Yeah I'll assume it's an issue with the install, I should reinstall.
