### ISSUE TITLE
`code -n filename` should implicitly open containing folder

### ISSUE THREAD

**Issue by jonpryor** [microsoft/vscode#90901]
VS Code Version info:

```
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
```

Consider a directory structure in which the following files exist:

  * `path/to/helper.cs`
  * `path/to/app.cs`
  * `path/to/app.csproj`

If I open a single file into a new window:

```bash
% code -n path/to/app.cs
# or, if "lazy": code -n `find . -iname app.cs`
```

I am now editing `app.cs`.  I make some changes, such that `app.cs` is not saved.

Command+P (macOS) / Ctrl+P (Windows?) doesn't allow me to find other files in the same directory; only `app.cs` is shown.

That's "okay", so I open Explorer (Command+Shift+E) then click **Open Folder**, which helpfully contains the folder containing `app.cs`, then click **Open**.

At this point -- on macOS -- I am prompted with a window sheet:

> **Do you want to save the changes you made to app.cs?**
>
> Your changes will be lost if you don't save them.
>
> [**Don't Save**] [**Cancel**] [**Save**]

Clicking **Save** or **Don't Save** results in *closing* `app.cs`, resulting in a Window with the folder open in the left, and the *Welcome* file/tab on the right.  `app.cs` is no longer open.

For starters:

 1. Opening a folder *should not* result in closing the files that are already open.
 2. If I open a folder while a file is already open, I should not be prompted to save `app.cs`.  *It should remain open after opening the folder.*

That said, "more user friendly" (to me?) would be if `code -n path/to/file` *implicitly opened* `path/to` in the Explorer.  This would allow Command+P to find other files in the same directory and subdirectories such as `app.csproj` and `helper.cs`, without needing to explicitly open the containing folder.

**Comment by BenBtg** [comment]
Love this! 
Is there currently an explicit argument for folder opening?

**Comment by jonpryor** [comment]
> Is there currently an explicit argument for folder opening?

Yes; `code --folder-uri` will accept a folder.  However, it appears to want a *complete* URI.

```
code -n --folder-uri folder
```

doesn't load `folder` within Explorer.  Instead, it must be:

```
code -n --folder-uri file://`pwd`/folder
```

will open `folder` within Explorer.

That said, `pwd` isn't something that works "normally" on Windows, so it's kind of an "ugly" solution.
