### ISSUE TITLE
Highlighting after HTML comments not consistent

### ISSUE THREAD

**Issue by jpderrick** [Microsoft/vscode#9090]
- VSCode Version: 1.3.0
- OS Version: El Capitan 10.11.1

Steps to Reproduce:

1. <!-- comment -- > gives the highlighting as if the comment has the correct syntax (green comment, rest is in HTML highlighting, whereas this isn't a valid comment closing, so the rest of the file is regarded as a comment

**Comment by aeschli** [comment]
Check out https://www.w3.org/TR/html-markup/spec.html#comments, you can't have a space between `--` and `>`.
The syntax highlighting is correct here.
