### ISSUE TITLE
Problem with VSC macOS indenting after copy & paste

### ISSUE THREAD

**Issue by themelz** [microsoft/vscode#90913]
VSC's behavior with auto-indenting has changed when pasting lines.

It no longer adhere's to the current indent of the line I'm pasting on. Many times the indenting of the line(s) above and/or below the current line also change. Extremely annoying.

The images show a simple example. The three lines are copied and then pasted 3 times. Note how each paste increases the indent successively. Also note the line below the 3 lines also changes on each paste.
 
Is there a setting who's default behavior has changed and is the cause of this?
How do I change this behavior?

I'm writing Haxe code if that makes a difference.

![indent1](https://user-images.githubusercontent.com/38919440/74769168-7d853f80-524f-11ea-94a8-c31d43797363.jpg)
![indent2](https://user-images.githubusercontent.com/38919440/74769177-82e28a00-524f-11ea-9462-73aad1366508.jpg)

**Comment by themelz** [comment]
The paste seems to trigger two actions, the paste and then a separate indent. I discovered accidentally that doing a undo right after the paste undoes the indenting with out undoing the paste. Still shouldn't have to do that.

Is there a setting in VSC that controls this behavior?

**Comment by rebornix** [comment]
This feature can be disabled by `editor.autoIndent`.
