### ISSUE TITLE
Latest update causes intermittent freezes in active editor

### ISSUE THREAD

**Issue by appeality** [Microsoft/vscode#9091]
- VSCode Version: 1.3.0
- OS Version: Windows Server 2008 R2 Datacenter (Remote Workspace)

Steps to Reproduce:

1. Open more than one tab/file
2. One or more tabs become unresponsive (happens intermittently) and the only way to regain responsiveness (e.g. select text or scroll) within the affected tab is to restart VS Code

This issue only started happening after the 1.3.0 update.

Thanks!

**Comment by bpasero** [comment]
@appeality are you moving editors around with Drag and Drop?

**Comment by appeality** [comment]
I did drag and drop tabs within the editor.

**Comment by bpasero** [comment]
Ok, this is https://github.com/Microsoft/vscode/issues/9045 then.

@appeality are you using a VM or just pure Windows? Do you manage to reproduce this? I would like to understand how you got there.

**Comment by appeality** [comment]
I'm running on a VM in Windows. I looked at the related issue and interestingly, I was also dragging files between windows, but not to the editor. 


On July 11, 2016, at 10:04 PM, Benjamin Pasero <notifications@github.com> wrote:

Closed #9091.

**Comment by bpasero** [comment]
@appeality can you be more specific how you dragged files? I would really like to reproduce this!

**Comment by appeality** [comment]
Sure.

After making edits in VS Code to a specific JS file or HTML file, I have a
requirement to drag the affected file from the file location and into a
SharePoint Site Assets document library. At first I did not know what was
causing the issue, but after reading through the related issue
(specifically the fact that the error occurred when dragging files), I am
confident that was the cause. Although, I never had that issue prior to the
1.3.0 update.

My use case was very similar:
1. I'm using a Windows VM;
2. I edit files in VS Code, then drag them to another system from the file
system.

This seems like a weird bug. :-)

**Comment by bpasero** [comment]
@appeality so what would be the steps to reproduce? Do you drag a file from within VS Code outside to another VM? Or do you drag a file from a VM into VS Code? Or do you just drag "over" VS Code when doing so?

**Comment by appeality** [comment]
I just installed the 1.3.1 update and I no longer have the issue.

Steps:

1. Edit the JS file in VS Code and save
2. Open file explorer window, usually on top of VS Code window
3. Drag the file out of the file explorer window to a second monitor (VM is
running split screens) and drop into SharePoint document library

**Comment by bpasero** [comment]
@appeality yes it is fixed with a hacky workaround, would still like to understand how it happened in the first place.

So if I am reading your steps correctly, you start dragging from the windows explorer, your mouse moves over VS Code and eventually reaches a second window with a VM running another OS?

**Comment by appeality** [comment]
I'm running completely in a VM (Windows Server 2008 R2 Datacenter), but on
2 monitors.

**Comment by bpasero** [comment]
@appeality is that on a Mac using Parallels?

**Comment by appeality** [comment]
It's Amazon Workspaces on Windows 10

Sent from my Fire

On July 13, 2016, at 11:52 AM, Benjamin Pasero <notifications@github.com> wrote:

@appeality is that on a Mac using Parallels?
