### ISSUE TITLE
Error notification when turning off sync while signed out

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#90916]
Issue Type: <b>Bug</b>

1. Sign in and start settings sync
2. Run `Sync: Sign Out`
3. Run `Sync: Turn off Sync`

Notification is shown that says "Error while turning off sync: Not Authenticated. Please sign in to start sync."

VS Code version: Code - Insiders 1.43.0-insider (595f98455be0aac7372a0ae7841efae9b91b848e, 2020-02-18T13:53:05.200Z)
OS version: Darwin x64 18.7.0

**Comment by RMacfarlane** [comment]
@sandy081 There are many places we call `checkEnablement` which checks if there's a token. IMO I think we shouldn't check the token status at all in that function, it seems like it shouldn't matter if you're signed in or not to perform all of these operations

**Comment by sandy081** [comment]
I encountered this today and felt the same and removed this check for this method - 6b1e0937e87d05877d84efbc011a2f2037e36079

But after thinking a bit, this service `UserDataSyncService` should not bother about authentication. `UserDataSyncStoreService` is the one that should be aware of auth token and throw proper errors. Hence removed auth stuff from `UserDataSyncService`.
