### ISSUE TITLE
Codicon aliases

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#90919]
I think when an icon is renamed, that new name should be added as an alias for the codicon. For example in https://github.com/microsoft/vscode-icons/commit/55a478ba49ce3ec0d96f3ea4f7316ecbe36bc354 the icon was renamed from "play" to "run", but `$(run)` does not work.

**Comment by misolori** [comment]
This was fixed via https://github.com/microsoft/vscode/commit/0c35df539186a91f45dc37344b17d5ecb6692e60. I mapped `play` and `run` to point to the same icon.

**Comment by misolori** [comment]
Verification steps:
- Contribute an item to the status bar or create a task and in the label use `$(play)`
- Verify that the icon is the same as `$(run)`
