### ISSUE TITLE
VS-CODE: Terminal output: user@ZorinOS15-USB:~/Py-Projects$ cd /home/user/Py-Projects ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/bin/python3 /home/user/.vscode/extensions/ms-python.python-2020.2.63072/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 45031

### ISSUE THREAD

**Issue by alextuvi** [microsoft/vscode#90912]
Issue Type: <b>Performance Issue</b>

This issue happen while I was coding normally, I do not remember having changed any setting. Of course I am a noob and I started some weeks ago.
This is my test code, named "test.py" :
#Test
print("h")

This is the following output:
user@ZorinOS15-USB:~/Py-Projects$ cd /home/user/Py-Projects ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/bin/python3 /home/user/.vscode/extensions/ms-python.python-2020.2.63072/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 45031 /home/user/Py-Projects/test.py 
h

I know its working, but it is annoying. Thanks for helping!

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz (4 x 1881)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|3.71GB (0.14GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   141	  3035	code main
    0	    42	  3037	   zygote
    0	    80	  3074	   gpu-process
    0	   327	  3082	   window (test.py - Py-Projects - Visual Studio Code)
    0	   144	  3134	     extensionHost
    0	    61	  3272	       electron_node main.js 
    0	    95	  3665	       /snap/code/25/usr/share/code/code /snap/code/25/usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3134
    0	    23	  4356	       /usr/bin/python3 completion.py
    0	    19	  4359	         /usr/bin/python3 lib/python/jedi/inference/compiled/subprocess/__main__.py lib/python 3.6.9
    0	    65	  3168	     watcherService
    0	    65	  3194	     searchService
    0	     4	  4128	     /bin/bash
    0	     4	  4323	     /bin/bash
    0	   110	  3122	   shared-process
    0	     0	  4441	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  4442	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   110	  4418	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test.py - Py-Projects - Visual Studio Code)
|    Folder (Py-Projects): 4 files
|      File types: json(2) py(1)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python(2);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.2.63072

</details>

![Screenshot from 2020-02-18 16-03-26](https://user-images.githubusercontent.com/61206136/74768997-55eea100-5268-11ea-8482-f3e97fbfbcb3.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
