### ISSUE TITLE
Adopt codicons for bundled extensions

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#90911]
With #84695 and related issues deployed, bundled extensions like [npm](https://github.com/microsoft/vscode/tree/master/extensions/npm) and [git](https://github.com/microsoft/vscode/tree/master/extensions/git) can replace most of their bundled svg icons with native codicons.

**Comment by misolori** [comment]
@aeschli I don't believe we have an issue that covers re-using codicons via extensions, like our file icons and npm/git extensions. Ideally we'd like to use the same syntax as #84695 like:

![image](https://user-images.githubusercontent.com/35271042/75173492-ce7bb480-56e3-11ea-95ff-ef3cbd7bf734.png)

**Comment by jrieken** [comment]
> our file icons and npm/git extensions. Ideally we'd like to use the same syntax as #84695 like:

@misolori I can not follow. What is "_folder_dark"?

**Comment by misolori** [comment]
This is from our built-in "Minimal" file icon theme: 

https://github.com/microsoft/vscode/blob/20b4e047c6c43223ce9f66055fa5f58eab8aa36b/extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json#L2-L8

**Comment by misolori** [comment]
Moving the discussion from using codicons in file icons to #91973 as this issue is specific to our bundled extensions.

**Comment by KamasamaK** [comment]
Looking over the two example bundled extensions, I've found a couple limitations that would prevent completely replacing with codicons.

- For `npm`, the `prepostscript.svg` cannot be replaced because codicons do not have adjustable opacity.
- For `git`, none of the `status-*.svg` have equivalent codicons.

**Comment by misolori** [comment]
@KamasamaK I'm working on updating these two extensions and will address those two issue.

**Comment by KamasamaK** [comment]
Just to be complete, even though I only mention those two examples there's also [markdown-language-features](https://github.com/microsoft/vscode/tree/master/extensions/markdown-language-features) and possibly [image-preview](https://github.com/microsoft/vscode/tree/master/extensions/image-preview) that could use this treatment.

**Comment by misolori** [comment]
This is already done. The markdown extension has been updated (we still need the preview icon since codicons aren't supported there) and the image preview is a webview.

**Comment by KamasamaK** [comment]
Thanks. I see #99976 was opened for the Markdown extension.
