### ISSUE TITLE
Do not show merge/use local dialog on first sync for user

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90921]
Repro:

- Turn off sync, delete all data
- Turn on sync

The dialog should not show since the data will be the first on the server (so there's nothing to merge).

**Comment by sandy081** [comment]
I dont think we show this dialog if it is first time ever. Can you repro this?

**Comment by Tyriar** [comment]
This happened several times in the UX study, @misolori could you send links to the videos to @sandy081 if you haven't yet?

**Comment by misolori** [comment]
This happens every single time you set up sync for the first time. It happened to every participant today. I’ll fwd the videos.

**Comment by Tyriar** [comment]
@misolori by the first time your mean after checking the clear data checkbox right?

**Comment by misolori** [comment]
Sorry, yes after clearing out the data with the checkbox.

**Comment by sandy081** [comment]
I cannot repro this locally. Can you please repro again and give me steps.

**Comment by Tyriar** [comment]
@sandy081 there is video evidence, please watch the videos. They're linked on yesterday's Teams meeting.

**Comment by sandy081** [comment]
@Tyriar I am trusting you that it happened. Since you guys have already seen it, it would be great if you can point me to the exact location of the video.

**Comment by Tyriar** [comment]
This is actually a server problem; the cache isn't getting cleared so manifest comes back as it was before.

**Comment by sandy081** [comment]
Please close this if fixed on server.
