### ISSUE TITLE
Delay in initiallizing Angular Language Features

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#90920]
Issue Type: <b>Bug</b>

When I open a project with Angular files, the status bar shows "Initiallizing Angular Language Features" for a good 15 seconds.  A few times, it has taken much longer leading me to quit and re-launch Code.

Once it finished loading, the syntax coloring of the currently-open TS file changes as the new `editor.semanticHighlighting.enabled` kicks in.  That it, many items are colored the older textmate way, then change to the new colors.

This is especially visible on imports, where they are all colored the same and then `entity.name.function` imports change color (for example).

VS Code version: Code - Insiders 1.43.0-insider (595f98455be0aac7372a0ae7841efae9b91b848e, 2020-02-18T13:53:05.200Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_3183369|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
project-manager|ale|10.10.0
ng-template|Ang|0.900.12
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
ecdc|mit|1.3.0
HTMLHint|mka|0.6.0
theme-monokai-pro-vscode|mon|1.1.15
vscode-scss|mrm|0.9.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
angular2-inline|nat|0.0.17
angular-component-extension|oni|0.0.14
vscode-versionlens|pfl|0.24.0
quicktype|qui|12.0.46
format-html-in-php|rif|1.6.2
code-settings-sync|Sha|3.4.3
rewrap|stk|1.9.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.0.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.7.0

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
I believe this is caused by the angular extension. That extension contributes a TypeScript server plugin and our  semantic coloring is also run on the Typescript server, so if angular is slowing down the server that would explain why the semantic colors take such a long time to come in
