### ISSUE TITLE
Terminal does not respect DPI Change

### ISSUE THREAD

**Issue by Tadimsky** [microsoft/vscode#90927]
Issue Type: <b>Bug</b>

1. Open an integrated terminal in VS Code
2. Change DPI (such as unplugging or plugging in external monitor)
3. View the integrated terminal

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|-psn_0_6620752|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.7.0
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.0.15
yarn-task-provider|dkn|0.2.2
githistory|don|0.5.3
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
vscode-yarn|gam|1.7.0
vscode-pull-request-github|Git|0.14.0
vscode-circleci|jva|0.5.0
vscode-github|Kni|0.30.3
graphql-for-vscode|kum|1.15.3
terraform|mau|1.4.0
import-sorter|mik|3.3.1
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.0.9
mssql|ms-|1.8.0
python|ms-|2020.2.63072
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1615
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.0
vscode-jest|Ort|3.1.1
material-icon-theme|PKi|3.9.3
vscode-graphql|Pri|0.2.2
vscode-yaml|red|0.7.2
markdown-preview-enhanced|shd|0.5.2
code-spell-checker|str|1.7.23
vscodeintellicode|Vis|1.2.5
vscode-icons|vsc|10.0.0
markdown-all-in-one|yzh|2.7.0

(3 theme extensions excluded)

</details>

Before:

![image](https://user-images.githubusercontent.com/1149244/74781535-7b72af00-5256-11ea-91a5-bbf4bf90ba23.png)

After:

![image](https://user-images.githubusercontent.com/1149244/74781546-82012680-5256-11ea-8269-573bcd734943.png)

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by Tadimsky** [comment]
> Can you share your settings.json file?

```
{
    "editor.renderWhitespace": "all",
    "workbench.iconTheme": "vscode-icons",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "workbench.colorTheme": "Monokai Dimmed",
    "editor.fontFamily": "Cascadia Code PL",
    "editor.fontLigatures": true,
    "files.trimTrailingWhitespace": true,
    "window.zoomLevel": 0,
    "git.autofetch": true,

    "typescript.updateImportsOnFileMove.enabled": "always",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "cSpell.allowCompoundWords": true,
    "cSpell.diagnosticLevel": "Hint",
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "tslint.packageManager": "yarn",
    "files.associations": {
        "tslint.json": "jsonc"
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[yaml]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "diffEditor.ignoreTrimWhitespace": false,
    "[markdown]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "jest.autoEnable": false,
    "explorer.confirmDragAndDrop": false,
    "git.confirmSync": false,
    "python.jediEnabled": false,
    "editor.semanticHighlighting.enabled": true,
    "python.formatting.provider": "black"
}
```

**Comment by Tyriar** [comment]
Can you clarify what the issue is? The after screenshot looks correct due to emoji/powerlines glyph sizes? Are the screenshots labelled incorrectly?

**Comment by Tadimsky** [comment]
Before is when the issue happens and then after is when I resize the terminal to fix the issue.

So yeah, the before is what happens when I change DPI on the device (by plugging in external monitor). So it looks like maybe that's not triggering some re-render of the terminal until I do something like resize the terminal.

**Comment by shubhams** [comment]
can confirm! just had the same issue.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
