### ISSUE TITLE
Find & Replace new-line characters does not work

### ISSUE THREAD

**Issue by metafractal** [Microsoft/vscode#9092]
- VSCode Version: 1.3.0
- OS Version: Window 10

Steps to Reproduce:

1. Open sample file with multiple lines:
[a.txt](https://github.com/Microsoft/vscode/files/357836/a.txt)

2. "CTRL+SHIFT+H" to find and replace "\n" with any non new-line character. Ensure that 'Use regular expression' is selected.

(The new line characters are not being replaced, rather being appended to)

**Comment by alexandrudima** [comment]
@metafractal When I openend the attached file, I have noticed that it uses \r\n as a line separator:
![image](https://cloud.githubusercontent.com/assets/5047891/16761589/73c9ea60-4829-11e6-85fb-1178fde8c8c1.png)

![image](https://cloud.githubusercontent.com/assets/5047891/16761608/8d63f592-4829-11e6-817f-d8a9d7c35142.png)

Would searching for `\r\n` fix your problem in this case?

**Comment by metafractal** [comment]
Didn't notice line ending was CRLF. This was a false alarm.
Thanks!
