### ISSUE TITLE
Changing the capitalization of a filename leaves a duplicate entry in search results

### ISSUE THREAD

**Issue by riknoll** [microsoft/vscode#90926]
- VSCode Version: 1.43.0-insider
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Open an empty folder
2. Create a file (e.g. `testFile`)
3. Right click on the file and rename it to the same name with different capitalization (e.g. `testfile`)
4. Press cmd+P to look at the recently opened files and note that there are two entries
5. If you try to open the old name, you will now have two editors open with different names but pointing to the same file (no new file is created on disk)
6. If you try to search for a string that appears in the file, you will get two entries in the search pane. One with the old name and one with the new name.

Does this issue occur when all extensions are disabled?: Yes

Please note that I tested this on macOS so filenames are case sensitive.

**Comment by riknoll** [comment]
And here's a gif of that repro:

![2020-02-18 13 55 25](https://user-images.githubusercontent.com/13754588/74781531-79105500-5256-11ea-9c92-8bcb06dbdac7.gif)

**Comment by bpasero** [comment]
A bug in file watchers, reported as https://github.com/paulmillr/chokidar/issues/977

**Comment by paulmillr** [comment]
Is that related to case-sensitive, or case-insensitive filesystem?

**Comment by bpasero** [comment]
@paulmillr this is on macOS where by default the file system is case-preserving but case-insensitive (same as Windows).

**Comment by NicolasBuecher** [comment]
Same here (in Windows).

![image](https://user-images.githubusercontent.com/6748903/91592695-3e9f1780-e95f-11ea-9588-72767a3ff6b3.png)

**Comment by bpasero** [comment]
This has been resolved meanwhile, you will only ever see one editor even for different path casing.
