### ISSUE TITLE
Undesirable Font Variations in Terminal

### ISSUE THREAD

**Issue by zcoffin86** [microsoft/vscode#90928]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open the terminal (Ctrl + ~) and observe variations in the font as across the full horizontal width of the window. Download and zoom in on screenshot and you'll see that on the far left and far right of the window, the pipe characters look fine, but in the middle of the window they appear fuzzy. with text characters this significantly impacts legibility.

![Code_pPtrc9gDDr](https://user-images.githubusercontent.com/32465097/74781767-be894e00-5267-11ea-9628-c23aceea65a0.png)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (19.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
Do you set window.zoomLevel? Can you share your settings.json file?

**Comment by zcoffin86** [comment]
Yes, I set it to -1.

**Comment by zcoffin86** [comment]
Settings.json:
```
{
    "git.autofetch": true,
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[properties]": {},
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "java.actionsOnPaste.organizeImports": false,
    "[sql]": {
        "editor.defaultFormatter": "bradymholt.pgformatter"
    },
    "git.pullTags": false,
    "editor.tabSize": 2,
    "diffEditor.ignoreTrimWhitespace": false,
    "[css]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "git.confirmSync": false,
    "editor.largeFileOptimizations": false,
    "[less]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "window.zoomLevel": -1
}
```

**Comment by Tyriar** [comment]
I recommend keeping window.zoomLevel as 0 and then change font size settings instead /duplicate https://github.com/microsoft/vscode/issues/85154

**Comment by zcoffin86** [comment]
I do not like that "solution". the zoom level controls other aspects of the GUI besides the font size in the integrated terminal. By setting the zoom level to -1 other aspects of the GUI shrink down to allow more space in the editor for viewing and working with the source code. For now I will still use zoom level -1 and just pipe the terminal output to a file and view it in an editor tab, so that the font doesn't get messed up.

It is strange to me that the font inside the editor tabs doesn't get messed up but the font in the terminal does.

**Comment by Tyriar** [comment]
They're rendered differently. You can change the terminal to work like the editor by setting renderer type to "dom" but it will be slower. This is AFAICT a limitation in the web platform around canvas, I guess because canvas isn't often rendering pixel-perfect glyphs like this.

It's my hope in the future that window.zoomLevel scales all the fonts instead of just telling Electron to change the zoom level.
