### ISSUE TITLE
Shift-insert broken.

### ISSUE THREAD

**Issue by bsutton** [microsoft/vscode#90929]
Issue Type: <b>Bug</b>

Until recently I've been able to shift-insert to paste into a vscode editor.

In the last few weeks (not certain exactly when) shift-insert only works sometimes.

Mostly shift-insert will perform no action. Occasionally it will paste the text as expected.

shift-insert still works outside of vscode.
Occasionally it will work for extended periods and then randomly stop.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3521)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.53GB (5.87GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
flutter-snippets|ale|2.0.0
vscode-browser-preview|auc|0.5.9
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
gitlens|eam|10.2.1
LogFileHighlighter|emi|2.7.1
code-runner|for|0.9.15
pubspec-assist|jer|0.3.6
vscode-gutter-preview|kis|0.25.0
dart-import|lua|0.1.6
git-graph|mhu|1.21.0
vscode-docker|ms-|0.10.0
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
awesome-flutter-snippets|Nas|2.0.3
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.3
polymer-ide|pol|0.6.0
java|red|0.56.0
LiveServer|rit|5.6.1
vscode-multiclip|sle|0.1.5
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
local-history|xyz|1.8.0

</details>

**Comment by bsutton** [comment]
So I've just realised that it will actually paste to 'insert' new text into the editor but it won't paste to 'replace' existing text.

So my normal workflow (I'm left handed) is to double click a piece of text, ctrl-insert, to copy the text, double click on a word I want to replace and then do, shift-insert, to overwrite the existing text.

Using ctrl-c, ctrl-v still works as expected, but as a left handed mouse user these keys are not convenient.

**Comment by bsutton** [comment]
I've looked at the keyboard short cuts and it appears that ctrl-v and shift-insert have different definitions.
Paste Ctrl -v  has 'textInputFocus && !editorReadonly'
Paste Selection Clipboard shift-insert has 'config.editor.selectionClipboard && editorTextFocus && !editorReadonly'

If I map the standard Paste to shift-insert then everything works as expected, however out of the box I would expect shift-insert to have the same behaviour as ctrl-v

**Comment by gjsjohnmurray** [comment]
See #90222.

**Comment by alexdima** [comment]
This got changed in 1.42 for https://github.com/microsoft/vscode/issues/36170. There are two camps, one that wants shift+insert to paste the selection clipboard and another camp that wants shift+insert to paste the "clipboard" clipboard. We have chosen to align with the classical linux applications, like terminals, and have by default mapped shift+insert to paste the selection clipboard.

I am sorry about the disruption this causes if you have gotten used to the previous default behaviour.

There is a simple workaround available, you can map shift+insert back to pasting the "clipboard" clipboard, just add the following to your `keybindings.json`:

```
{
	"key": "shift+insert",
	"command": "editor.action.clipboardPasteAction",
	"when": "textInputFocus && !editorReadonly"
}
```

**Comment by vlad-vinogradov** [comment]
@alexdima 
This new feature should be clearly described in the documentation. And there should be an option to disable this feature in the Settings.

I suppose that many Linux users of VS Code recently went to the store to buy a new keyboard )))

**Comment by bsutton** [comment]
@alexdima I have to say that this is an odd decision.
Every editor/word processor/application...... I've ever used causes a paste action from the clipboard.

This goes back to at least windows 3.x (yes I'm that old).

The linux terminal is the one exception that I know of and for the terminal we have middle mouse button to paste from selected.

Yes you can modify it which is great, but I can so no argument for this being the default and I'm an extensive terminal user.

**Comment by alexdima** [comment]
I've opened #91051 to investigate what other code editors do by default.

**Comment by bsutton** [comment]
I've used shift-insert for 30 years and don't remember any editor working
the way vscode does now.

**Comment by bsutton** [comment]
The list of editors that I currently use that work the way I expect:
Eclipse
Intellij
Word
Libre Office
Google docs
Notepad
Leaf
Chrome's search bar :)
gmail's editor
Even the gnome terminal's Find field.
Any text field in any app that I've ever used.

The only 'editors' that I know of that don't support the default
shift-insert are
vi
terminal.

**Comment by SodomousPrime** [comment]
I was also tripping up on this change, I am happy that the key bindings work around solution was posted here.
