### ISSUE TITLE
Extensions require manual install

### ISSUE THREAD

**Issue by mahkassem** [microsoft/vscode#90933]
Issue Type: <b>Bug</b>

All extensions has broken image and no README available, it also fail to install unless if I download it manualy after  vscode alert me that.

![image](https://user-images.githubusercontent.com/12067112/74783898-64ac7680-52af-11ea-8a16-3cc61821564e.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (9.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.42.3

</details>

**Comment by gjsjohnmurray** [comment]
Looks like a DNS issue.

**Comment by mahkassem** [comment]
Fixed after applying google DNS from the router 8.8.8.8, 8.8.4.4
