### ISSUE TITLE
Git error on attempt to commit when auto-stage: tracked and only untracked files present

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#90934]
Have `"git.enableSmartCommit": true` and `"git.smartCommitChanges": "tracked"`. 

Working directory contains an untracked file and nothing more.

Attempt to commit.

Error:
![image](https://user-images.githubusercontent.com/8586769/74784747-77965b00-525d-11ea-8cc0-492d84b91211.png)
Log isn't helpful:
![image](https://user-images.githubusercontent.com/8586769/74784777-8a109480-525d-11ea-8a47-ffb1665b666e.png)

Normally we don't run any command when theres nothing that would be committed, I think we should either do the same if only untracked files are present and only tracked files are smart committed, or show a more specific error message.

**Comment by joaomoreno** [comment]
Great catch!
