### ISSUE TITLE
Search in all files within opened folders.

### ISSUE THREAD

**Issue by jamesford42** [microsoft/vscode#90932]
Searching for a term known to exist in a file within an opened folder, finds no results, unless the file itself is open as a document.
How is this "find in files" then? It behaves like find in documents.

**Comment by jamesford42** [comment]
Not sure if this other issue was resolved, but the reported behavior is the same. Is there some reason a large binary file with the extension *.bin would be excluded from searches even though I disabled the exclusion rules via the search ui?

**Comment by roblourens** [comment]
We only search text files. We don't know how to interpret binary files. What sort of result are you expecting to get?

**Comment by jamesford42** [comment]
It does a good job interpretting binary files if its open as a document... it finds the embedded string i searched for. Why can't it do the same when it isn't open as a document?

**Comment by roblourens** [comment]
It's not unlikely for people to have really large binary files in their workspaces, and searching all binary files by default would slow down search, so I don't plan on doing that. In general vscode will only work well with text code files.

**Comment by jamesford42** [comment]
That as the default behavior makes sense. But what about when the file extension is specifically included, or exclusions are entirely disabled?

**Comment by roblourens** [comment]
The way search works, that's not really practical to do.
