### ISSUE TITLE
Unresponsive saving for some SQL files

### ISSUE THREAD

**Issue by CNick** [microsoft/vscode#90937]
Issue Type: <b>Bug</b>

When trying to save some SQL files, VS Code doesn't show file has been saved (Explorer icon indicates an unsaved change & trying to close the file prompts to save) but the file has already been saved. This happens with all extensions disabled (and window reloaded).

Additionally, when trying to submit an issue using Report Issue from the Command Palette, if I choose "File on > Don't Know" nothing happens when I click the Preview on GitHub button and I'm unable to report the issue from that form.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 8, 5|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|-psn_0_4166649|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
php-debug|fel|1.13.0
diff-tool|jin|0.0.1
vscode-text-pastry|jkj|1.2.0
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.9.6
searchwpdocs|yog|2.0.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
