### ISSUE TITLE
Hard to click "Quick Fix" button

### ISSUE THREAD

**Issue by BoltonBailey** [microsoft/vscode#90936]
Not sure if this is a bug or a feature request or worth fixing, but here is my issue.

My linters identify problems in my code by underlining them. I can mouse over the underlined problem, and a box appears immediately above the problematic line that describes the problem. The bottom of the box has a "peek problem" button and a "quick fix" button, and I usually want the quick fix. The trouble is, when I mouse over to the quick fix button, the mouse momentarily leaves the problematic text before it reaches the box, so the box disappears. Is there a way to make the box stick around for a bit so that I don't have to mouse back to the issue and move my mouse carefully over the box to the quick fix button?

**Comment by BoltonBailey** [comment]
I'll note that this problem is particularly prevalent when the issue is only one character long, meaning you have to mouse to the problem, then specifically move your mouse up, then to the right.

**Comment by mjbvz** [comment]
Could you use the quick fix command / its keyboard shortcut: cmd+. on Mac?

It brings open the same menu

**Comment by sandy081** [comment]
I do not think there is a way to have sticky hover. For discoverability we can add keyboard shortcut label to the command in the hover so that you can use the keyboard shortcut if hover is not accessible.

**Comment by sandy081** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/10746682/77922087-ddd0bd80-72a0-11ea-9174-9c10f137e934.png">

**Comment by sandy081** [comment]
Verify that the actions in the hover status bar show keybinding labels.
