### ISSUE TITLE
sync.ignoredExtensions should provide intellisense

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90931]
Related: https://github.com/microsoft/vscode/issues/90930

<img width="493" alt="Screen Shot 2020-02-18 at 2 10 53 PM" src="https://user-images.githubusercontent.com/2193314/74782537-7e6e9f00-5258-11ea-8690-21e3656a5022.png">

Should auto complete to all currently installed extensions.

**Comment by sandy081** [comment]
Best we can do is to show the list of installed extensions ids as proposals which we do same for others (recommendations).

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/74835242-35345300-531d-11ea-8130-b39e9bb43ce1.png)

**Comment by Tyriar** [comment]
Perfect, thanks!
