### ISSUE TITLE
command palette - too narrow

### ISSUE THREAD

**Issue by pisz123** [microsoft/vscode#90948]
Hello,
when looking for symbol (e.g. same functions with different set of arguments) to less characters are shown to choose proper definition.
See no possibility to make command palette wider.
What about introducing parameter to define width of command pallete ?

Thanks

Version:1.42.1
OS: WIndows_NT x64 10.0.18363

**Comment by isidorn** [comment]
@gjsjohnmurray thanks a lot for help!
