### ISSUE TITLE
HTML syntax highlighting broken by inline script tag

### ISSUE THREAD

**Issue by mathiasvr** [microsoft/vscode#90942]
The HTML syntax highlighting can be broken by inserting an inline script tag with if condition.

- VSCode Version: 1.42.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Insert `<script>if (1) {}</script>` or `<script>if (1) func()</script>` into an HTML file.
2. Syntax highlighting is broken.

This can generally be worked around by adding a closing semi-colon.
The first example can also be worked around by removing a space: `<script>if (1){}</script>`.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by KamasamaK** [comment]
Related to #20488

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/70614
