### ISSUE TITLE
 The file name is named pascalcase, and there are many levels. The diff of Git is missing

### ISSUE THREAD

**Issue by xiaojun996** [microsoft/vscode#90946]
Issue Type: <b>Bug</b>

The file name is named pascalcase, and there are many levels. The diff of Git is missing！
Document hierarchy：
--Home
         HomeAxxx
             HomeAxxx.vue
         HomeBxxx 
             HomeBxxx.vue
         HomeCxxx
             HomeCxxx.vue
         HomeDxxx
             HomeDxxx.vue
         HomeExxx
             HomeExxx.vue
         Home.vue
but,Change the file name to home, and diff will be normal。

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.86GB free)|
|Process Argv|-psn_0_147492|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
px2rem|art|0.0.3
color-info|bie|0.5.1
turbo-console-log|Cha|1.3.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
code-runner|for|0.9.15
vscode-gutter-preview|kis|0.25.0
vscode-filesize|mkx|2.1.3
vscode-language-pack-zh-hans|MS-|1.42.2
debugger-for-chrome|msj|4.12.6
vetur|oct|0.23.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|1.8.0
background|sha|1.1.23
code-settings-sync|Sha|3.4.3
vscode-leetcode|she|0.16.0
vscode-icons|vsc|10.0.0
JavaScriptSnippets|xab|1.7.2
super-translate|xue|1.0.9
material-theme|zhu|3.2.2

</details>

**Comment by xiaojun996** [comment]
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

**Comment by octref** [comment]
What do you mean by "there are many levels. The diff of Git is missing！"? Do you have a screenshot?
