### ISSUE TITLE
Dragging folders no longer works on Mac

### ISSUE THREAD

**Issue by cliffowen** [Microsoft/vscode#9094]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.4.0

Steps to Reproduce:

1. Open Finder on Mac
2. Find a folder with a number of source files. Drag the folder onto the VS Code window.

Past behavior would add the folder/subfolders and files to the VC Code "solution". This is now broken and you must click the folder icon, "Open Folder" button and go find the folder you would like to add, which is cumbersome and time consuming.

**Comment by f111fei** [comment]
duplicate #8726. This had been repaired in master and [insiders](http://code.visualstudio.com/Download#insiders).
