### ISSUE TITLE
Miss Git Decoration in Explorer View

### ISSUE THREAD

**Issue by gnought** [microsoft/vscode#90943]
- VSCode Version: 1.42.1
- OS Version: OSX 10.15.3

Steps to Reproduce:

1. Open a Git project
2. Change a file
3. There should have a "M" status for the file

Does this issue occur when all extensions are disabled?: Yes

**Comment by sanket-bhalerao** [comment]
this is working fine in the insiders build.
Version: 1.43.0-insider (user setup)
Commit: 595f98455be0aac7372a0ae7841efae9b91b848e
Date: 2020-02-18T13:52:42.988Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
@gnought 
Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

**Comment by gnought** [comment]
@joaomoreno nope.
Maybe it's my first time to run VS code insider, a little bit slow to show the "M" status.

**Comment by joaomoreno** [comment]
And can you reproduce reliably on stable?

Can you reproduce with *any* git repository?

Do you have any specific setting which disables the feature?

**Comment by gnought** [comment]
I clean up my settings.json, and disable all extensions by `code --disable-extensions`
1. yes, reproducible.
2. I have testd 5 git repo.

**Comment by joaomoreno** [comment]
@gnought Can you show me a screenshot as well?
