### ISSUE TITLE
Hot exit: folders with backups no longer restore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90949]
Steps to Reproduce:

1. open a folder
2. make some files dirty
3. close the window
4. from the command line open code with a different folder

=> 🐛 the folder opens but I would expect a second window opening with the dirty files from the first session

I think this somewhat broke with https://github.com/microsoft/vscode/commit/7b681aa2fb49229e8a51443f782270937a175588 where I see that we now seem to be adding these folders (looking for `backupMainService.getFolderBackupPaths()`).

The idea behind hot exit was always that a user would get all sessions with dirty files back as a window when started on a different workspace (@Tyriar correct me if we changed that assumption).

**Comment by bpasero** [comment]
Was this supposed to be:

`**foldersToOpen**.push(...foldersToRestore.map(f => ({ folderUri: f, remoteAuhority: getRemoteAuthority(f), isRestored: true })));`

?

**Comment by aeschli** [comment]
Yes, you are correct!

**Comment by Tyriar** [comment]
> The idea behind hot exit was always that a user would get all sessions with dirty files back as a window when started on a different workspace

Yes, by default all backed up workspaces would restore whenever VS Code is launched 

![image](https://user-images.githubusercontent.com/2193314/74841834-2f6b4d00-52de-11ea-880c-198eabd40d69.png)

**Comment by bpasero** [comment]
This will probably come to a surprise for many people once they update to next stable where we would restore all workspaces with untitled files at once. I find it interesting that no one complained so far, this might backfire :)
