### ISSUE TITLE
Integrated Terminal Doesnt Render properly

### ISSUE THREAD

**Issue by shsaci** [microsoft/vscode#90945]
Issue Type: <b>Bug</b>

Hello,
  Powershell is currently selected as integrated terminal.

When I press 'Ctrl + ~' to request terminal, a blank window appears at the bottom of my editor with no prompt. 

If I enter any misc. command, the command works and the terminal prompt then appears normally.

Have tried switching to windows prompt and also to Git bash. Windows prompt produces the same outcome, but with Git bash, instead of appearing as an integrated terminal, it sprouts as a separate window, outside of the editor.

Have not tried doing a clean reinstall of VS Code yet.

Is there a way for terminal prompt to show properly first render onwards?

Thanks

VS Code version: Code 1.42.1 
(c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G   (4 x 3094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.95GB (8.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
![Code_9Q9wBy3uas](https://user-images.githubusercontent.com/12632597/74806664-70e61180-534b-11ea-8fc9-20d1551f5034.png)
![Code_ENyR5MVHHK_b](https://user-images.githubusercontent.com/12632597/74806670-780d1f80-534b-11ea-8684-e6a693044d88.jpg)

---|---|---
prettier-vscode|esb|3.20.0
auto-using|Fud|0.7.9
csharp|ms-|1.21.11
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.5

</details>

**Comment by shsaci** [comment]
![Code_9Q9wBy3uas](https://user-images.githubusercontent.com/12632597/74806745-b0acf900-534b-11ea-8b21-2fb2231298ef.png)

![Code_ENyR5MVHHK_b](https://user-images.githubusercontent.com/12632597/74806757-b7d40700-534b-11ea-8b32-1cb16ecc96fa.jpg)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
