### ISSUE TITLE
Языковая служба TypeScript пять раз непредвиденно завершила работу за последние пять минут.

### ISSUE THREAD

**Issue by sirtakidancers** [microsoft/vscode#90959]
Issue Type: <b>Bug</b>

just work in js file

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (2.51GB free)|
|Process Argv|-psn_0_4703356|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
ActiveFileInStatusBar|Ros|1.0.3
Bookmarks|ale|10.7.0
vscode-intelephense-client|bme|1.3.11
path-intellisense|chr|1.4.2
language-postcss|cpy|1.1.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
code-runner|for|0.9.15
seito-openfile|Fr4|1.8.5
backbone-js-snippets|Hri|1.0.0
rest-client|hum|0.23.1
underscore-snippets|jan|1.3.1
vscode-lebab|jer|1.0.5
docthis|joe|0.7.1
vscode-colorize|kam|0.8.15
node-module-intellisense|lei|1.5.0
require-js|lic|0.1.33
sftp|lix|1.12.9
twig-language-2|mbl|0.9.0
vscode-language-babel|mgm|0.0.25
postcss-language|mhm|2.1.0
git-graph|mhu|1.21.0
theme-monokai-pro-vscode|mon|1.1.15
vscode-scss|mrm|0.9.0
language-gettext|mro|0.1.1
vscode-language-pack-ru|MS-|1.42.2
atom-keybindings|ms-|3.0.6
vscode-typescript-next|ms-|3.9.20200215
indent-rainbow|ode|7.4.0
vscode-code-outline|pat|0.0.12
javascript-typescript|sou|0.0.7
addDocComments|ste|0.0.8
code-spell-checker|str|1.7.23
code-spell-checker-russian|str|0.2.4
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.5
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by isidorn** [comment]
Please file a new issue in english. Thanks!
