### ISSUE TITLE
[feature] extend HTML Wrap attributes support for other languages

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#90957]
languages like `php, blade, twig, etc...`, basically any html like syntax

**Comment by aeschli** [comment]
@ctf0 What is HTML wrap? You mean `Emmet, wrap with Abbreviation`?

**Comment by ctf0** [comment]
i mean `html.format.wrapAttributes`

**Comment by aeschli** [comment]
You need to make that request to the formatters that you use for each of the languages. 
`html.format.wrapAttributes` is a setting from the HTML formatter which is based on jsbeautify. jsbeautify is not really designed for templating languages like Blade and Twig.
