### ISSUE TITLE
Global search not working

### ISSUE THREAD

**Issue by mjacqmin** [microsoft/vscode#90951]
Issue Type: <b>Bug</b>

1. I click on the magnifying glass on the left side
2. I click in the search text input
3. I type text
4. Nothing happens (not even a message saying that there is no results)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19564

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-postgres|cko|1.1.11
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.1
procfile-support|log|0.0.1
rainbow-csv|mec|1.5.0
git-graph|mhu|1.21.0
vscode-remote-workspace|mkl|0.43.1
python|ms-|2020.2.63072
remote-wsl|ms-|0.42.3
vscode-microsoftteams|ste|1.0.6
pdf|tom|0.5.1

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?
