### ISSUE TITLE
Cannot debug extension on SSH remote

### ISSUE THREAD

**Issue by GongT** [microsoft/vscode#90958]
- VSCode Version: 1.42.1
- OS Version: Windows 10 / Fedora 31

Steps to Reproduce:

1. Clone `microsoft/vscode-extension-samples` somewhere on **remote host**
    * I'm using SSH target
1. Open `helloworld-sample` using VSCode Remote feature
1. Run `npm install`
1. Press F5
1. Continue edit files (eg, append more space at end of `extension.ts`) in **original** VSCode window, not the "extension develop host"
1. After some time (<10s), a "disconnected" error occur
1. The "extension develop host" can open/edit file instead of original one.

If you check log, you will see `Error: Connection error: Unknown reconnection token.`

**Comment by alexdima** [comment]
@GongT I cannot reproduce. This works fine for me. I can set breakpoints, they are hit, I can inspect variables, etc. and I don't see the disconnected prompt. Are there any more steps?

**Comment by GongT** [comment]
Thanks for your time.

I also cannot reproduce anymore...

I have reset my windows few days ago, and the issue disappears. I think it's nothing about VSCode.     
Forgot to close this issue, sorry.
