### ISSUE TITLE
Make relative path interpretation for markdown compatible with pandoc

### ISSUE THREAD

**Issue by ImkeF** [microsoft/vscode#90956]
Currently, the relative paths for images in markdown are interpreted differently in pandoc and VS Code, which limits the way for project organisation considerably. Therefore it would be great if VS Code would interpret:

```![Image Caption](images/SomeImageFile.jpg)```

as relative to the working directory like pandoc does and not relative to the directory where the current file is stored.

**Comment by IllusionMH** [comment]
VSCode uses markdown-it which doesn't transform src attribute in any way, and changing default logic will be breaking change.

Most likely you'll need to create simple VSCode extension that adds markdown-it plugin that alters renderer for images.

**Comment by ImkeF** [comment]
Thanks @IllusionMH ,
but this would only be the last resort, as we want to run intermediate builds as well. We're multiple authors working on cloned GitHub repos, so interested to keep the relative path syntax in the files.
