### ISSUE TITLE
Two-step collapse in multi-root Explorer setting

### ISSUE THREAD

**Issue by SamJust** [microsoft/vscode#90961]
Can we, maybe, have a setting to control this behavior? Because I don't like it, and I'm VERY used to collapsing everything in one click, since even on top level my folders have almost two dozens entries each, and if i want to quickly find something, I still need to scroll. Though I do see the usefulness of this.

We should have setting to control this behavior, IMO.

**Comment by isidorn** [comment]
This is a fair feature request. We might introduce this setting in the future, thus assigning this to Backlog.
fyi @roblourens

**Comment by roblourens** [comment]
Out of curiosity @SamJust would you also want a setting to disable this in the search view, or is that not an issue for you?

**Comment by SamJust** [comment]
@roblourens Not really, because I usually search in a specific folder, so I don't get results in multiple folders. Though, I think, that if you are to add setting for file explorer, it'd be good to have one for search bar, for consistency.

**Comment by blocknonip** [comment]
Honestly, I'm amazed that the default behavior that has existed since *forever* was changed without so much as an option to undo it. I've been happily minimizing all folders since the first release of VSCode, and now I have to spam-click the mouse button instead. It's quite infuriating.

Also, I think this ticket could use a more descriptive title.

**Comment by SamJust** [comment]
@isidorn HI! This behavior is annoying. So, I consider doing changes to the code myself. I know I am to discuss this with feature owner, whom I assume is you. The question is, can I start on this, or you don't accept external help for this issue?

**Comment by isidorn** [comment]
We still do not accept PRs for this. Though this might change in the future.

**Comment by blocknonip** [comment]
> We still do not accept PRs for this. Though this might change in the future.

It sounds like the feature should be reverted, then. This was clearly a short-sighted change that did not take into account users' workflows over the past **4 years**.

**Comment by blocknonip** [comment]
@isidorn This isn't a feature request. This is a bug report for expected behavior that was changed after **4 years** of daily use.

I don't think it's fair to your users to whisk this away under the carpet.
