### ISSUE TITLE
debug session badge doesn't drop to zero after a debug session ends

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#90965]
Issue Type: <b>Bug</b>

- start a debug session

Observe: debug sessions badge shows a "1"

- stop debug session

Observe: debug sessions badge still shows "1"

VS Code version: Code - Insiders 1.43.0-insider (595f98455be0aac7372a0ae7841efae9b91b848e, 2020-02-18T13:53:05.200Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.1.0
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
gitblame|wad|3.0.1

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/90940
