### ISSUE TITLE
Sync status indication

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90967]
From user study: 

Users were not sure whether sync was working, they all manually searched through settings/extensions to verify that sync was working and everyone expressed a desire for an indicator (last synced timstamp, sync is on, etc.)

**Comment by Tyriar** [comment]
This could be fixed as part of https://github.com/microsoft/vscode/issues/90385 by adding a progress badge to it (maybe only on first sync?).

**Comment by sandy081** [comment]
Agreed to make it part of account UI.

**Comment by sandy081** [comment]
Reopening this - we can provide at least last time successful sync message.

**Comment by sandy081** [comment]
We show now when was the last time it synced to indicate user about sync activity and clicking on it will guide user to see more detailed activity. 

<img width="287" alt="Screenshot 2020-02-20 at 17 46 55" src="https://user-images.githubusercontent.com/10746682/74963209-a2c1ab80-5411-11ea-8ff3-e22ced28c723.png">

<img width="343" alt="Screenshot 2020-02-20 at 17 56 18" src="https://user-images.githubusercontent.com/10746682/74962645-9a1ca580-5410-11ea-98b4-d1acca8c7717.png">

<img width="343" alt="Screenshot 2020-02-20 at 17 56 18" src="https://user-images.githubusercontent.com/10746682/74963229-abb27d00-5411-11ea-8d24-ec9fc9456c62.png">

<img width="679" alt="Screenshot 2020-02-20 at 17 56 25" src="https://user-images.githubusercontent.com/10746682/74962654-9f79f000-5410-11ea-8495-0350ef1d1e69.png">

**Comment by misolori** [comment]
My personal preference is to keep the command clean, `Sync is on`, and to show the last synced timestamp in the quick pick:

![image](https://user-images.githubusercontent.com/35271042/75083785-56897080-54d0-11ea-80cf-2004a31adef5.png)

**Comment by sandy081** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/10746682/75111768-cbc68400-563d-11ea-9a89-195ddd12091d.png">
