### ISSUE TITLE
global search and replace doesn't respect regex variables

### ISSUE THREAD

**Issue by ChrisJefferson** [Microsoft/vscode#9096]
- VSCode Version: 1.3.0
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:

1. Try using a regex with a `$` variable in global search and replace. For example replace

```for(.*)``` with ```cat$1```

In a single file search and replace this replaces 'for' with 'cat'. In a global search and replace it deleted the whole line after ```for``` (including for), replacing it with ```cat$1```, removing the rest of the line. Basically, it doesn't realise it should treat `$1` specially.

**Comment by sandy081** [comment]
duplicates #9010
