### ISSUE TITLE
GitHub bot not acting on /-comments from community issue trackers

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#90964]
@chrmarti recently the bot doesn't seem to have been processing /xxx comments that I've been adding to issues. Is it sulking? Or out for maintenance?

**Comment by IllusionMH** [comment]
Only info I've seen on this topic: https://github.com/microsoft/vscode/issues/90684#issuecomment-586328876

**Comment by chrmarti** [comment]
We're working on it. Sorry for the inconvenience. /cc @usernamehw

**Comment by chrmarti** [comment]
Fixed. Let us know if anything is not working as expected yet.
