### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by pesachoice** [microsoft/vscode#90963]
Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
php-autocomplete|bsc|0.4.2
githistory|don|0.5.3
gitlens|eam|10.2.1
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-peacock|joh|3.3.1
chat|kar|0.31.0
php-constructor|Meh|0.1.2
vscode-docker|ms-|0.10.0
python|ms-|2020.2.63072
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1615
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
vetur|oct|0.23.0
vue-beautify|pea|2.0.4
vscode-php-getters-setters|php|1.2.3
LiveServer|rit|5.6.1
vscode-nginx|sha|0.6.0
php-formatter|Sop|0.2.4
material-theme|zhu|3.2.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
