### ISSUE TITLE
Edit in settings.json is not helpful

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90969]
During settings sync user study - Everyone was confused when they clicked on “Edit in settings.json”, they expected to start editing the setting in the settings.json file

**Comment by Tyriar** [comment]
I also came to the same conclusion when I try it myself before they I saw participants do it. I thought we used to support this? @roblourens mentioned yesterday that auto save complicates this.

**Comment by usernamehw** [comment]
#67908

**Comment by roblourens** [comment]
Also sort of related to https://github.com/microsoft/vscode/issues/89512

I still feel that giving the "edit in settings.json" button side effects will be bad because users will end up with lots of settings configured as their default values, which is confusing, but we could experiment.
