### ISSUE TITLE
Change -> Undo no longer marks document non-dirty

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90973]
Steps to Reproduce:

1. fresh code insiders
2. open a file
3. type 1 letter
4. undo

=> 🐛 file is still marked as dirty

I am not sure if this is me or you Alex, wonder if any changes in editor could cause this around undo stops?

**Comment by alexdima** [comment]
@bpasero I just wrote a test to verify and I think the editor works fine, the alternative version id returns after an undo.
