### ISSUE TITLE
Indicator to show a setting or an extension is not synced

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90977]
User can configure extensions and settings to be ignored while syncing. There are also some settings which are ignored by default (like machine settings). 

We would need some UI indication representing that these items are not getting synced

**Comment by sandy081** [comment]
Some mock ups from @misolori here:

And when ignore we append a badge, similar to when we disable an extension:

![image](https://user-images.githubusercontent.com/35271042/71298547-81730f00-233d-11ea-88a8-d00020a529b1.png)

**Comment by sandy081** [comment]
@misolori How does this look for settings. Is it possible to have just an icon due to the real estate constraints in extensions?

**Comment by misolori** [comment]
We could use just an icon right next to the gear and then have the tooltip show this info.

**Comment by roblourens** [comment]
Should I work on this? Is this icon checked in somewhere or can you send it to me?

**Comment by misolori** [comment]
@roblourens yep, you can use `eye-closed` for this:

![image](https://user-images.githubusercontent.com/35271042/75934381-2aa3ae80-5e31-11ea-99c1-0afe38ebad9f.png)

**Comment by sandy081** [comment]
@roblourens @misolori I played around a bit and I felt the descriptive label is bit too much to have in the extensions view. There is already space constraints. Hence I would like to have only icon and show the text on hover. (Also same in the extension editor)

<img width="682" alt="image" src="https://user-images.githubusercontent.com/10746682/77916113-d7d6de80-7298-11ea-82fa-8f876ef3d581.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/10746682/77916180-f2a95300-7298-11ea-80a7-f053bb7efa21.png">

**Comment by misolori** [comment]
My only concern is that this is very subtle and most users might miss this if they don't do this action from the extension gear.

We should also provide for an option to re-sync from the extension list. Maybe under the disable dropdown button?

**Comment by sandy081** [comment]
> My only concern is that this is very subtle and most users might miss this if they don't do this action from the extension gear.

Not sure if I understand the point here. What does users might miss when only icon is shown?

> We should also provide for an option to re-sync from the extension list. Maybe under the disable dropdown button?

True. I am planning to add gear icon in the extension editor too.

**Comment by misolori** [comment]
> Not sure if I understand the point here. What does users might miss when only icon is shown?

If you ignore an extension from the Settings UI, you likely won't ever noticed the small icon in the extension viewlet, which is why I'm concerned that the icon alone might not be enough.

**Comment by sandy081** [comment]
I see and agree with you. I also think the icon + label are causing UI clutter as extension view is already filled with too much data. If icon is not too expressive, is it possible to get a different icon which is prominent?
