### ISSUE TITLE
support snippets in integrated terminal

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode#90975]
I'd like to use snippets inside integrated terminal, so that I can e.g. write `grh<tab>` to expand it to `git reset --hard`.

**Comment by Tyriar** [comment]
We won't support something like this as trying to do this on our end would be a significant change in thinking of how the terminal works (and probably unreliable). I recommend doing it the way your shell does, for example: `alias grh=git reset --hard`, git also has other ways to do aliases that you might want to look into.

**Comment by dwelle** [comment]
Yea, I was specifically not looking for aliases (and there's only so much one can do with bash for windows), but thanks for the response!
