### ISSUE TITLE
shell per project

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode#90972]
I'd like to have different default shells per project.
Sometimes I work within WSL and need the WSL/Bash to be my default shell, but sometimes I work on Windows and then I need powershell/cmd.

Currently I always change the `"terminal.integrated.shell.windows"` setting manually to have the right shell, but I'd like to have a way for vscode to just know which shell to use.

**Comment by Morgy93** [comment]
nvm this seems to be solved via https://github.com/microsoft/vscode-remote-release

**Comment by IllusionMH** [comment]
Just in case - have you tried to put "terminal.integrated.shell.windows" in Workspace settings (`.vscode/settings.json`)?
If you have different workspaces for these two cases you can have different configs for each of them.
