### ISSUE TITLE
[RFI] tasks inside workspace file

### ISSUE THREAD

**Issue by TriMoon** [microsoft/vscode#90979]
Hi, could you please add support for defining tasks inside the `*.code-workspace` file?

This would allow to create specific tasks without polluting the workspace directory, in cases like `/etc/systemd/` and the like...
It would also enable to have per-developer tasks for a project they are working on by simply editing their personal `*.code-workspace` files.

Yes people use this editor for other purposes (like system administration) instead of just code development :smile:

**Comment by alexr00** [comment]
Tasks are already supported in *.code-workspace files.

**Comment by TriMoon** [comment]
@alexr00 Could you please direct me to some documentation where this is explained/demonstrated?
Thanks

**Comment by alexr00** [comment]
Looks like I missed adding it to the release notes last month. Try running the Tasks: Open Workspace Tasks command.

**Comment by TriMoon** [comment]
Tanks a lot using it now :+1:
