### ISSUE TITLE
Add commands to restore previous non-tabs behaviour

### ISSUE THREAD

**Issue by danvk** [Microsoft/vscode#9097]
- VSCode Version: 1.3.0
- OS Version: Mac OS X 10.11.4

I really liked the old vscode behavior: I could have several splits open, each of which showed a single file. It was very vim-like. I like tabs in my browser but not my editor. It would be great if there were a way to disable tabs entirely and get the old behavior. I miss keyboard shortcuts like Cmd-Opt-Right to either switch splits or open a new split.

**Comment by mrmlnc** [comment]
Option `workbench.editor.showTabs` did not help you?

**Comment by danvk** [comment]
That just hides the tab bar. It doesn't change the behavior.

For example, when I hit Cmd-Opt-Left and Cmd-Opt-Right, I cycle through the (now invisible) tabs, rather than changing splits.

**Comment by danvk** [comment]
The old behavior for alt+cmd+left and alt+cmd+right is what I really want. If there were an editor action for switching between editor groups (as opposed to tabs) then I think I could define my own keybindings to make myself happy. Having alt+cmd+right create a new split when you're on the rightmost one (like it used to) would also be really nice!

**Comment by bpasero** [comment]
@danvk I think you can configure everything as you like, the commands to move between groups are `workbench.action.focusNextGroup` and `workbench.action.focusPreviousGroup`.

Please let me know what else is missing and we can add those commands back 👍

**Comment by danvk** [comment]
@bpasero That's perfect. Thank you!
