### ISSUE TITLE
support new "selection" feature of debug completion items

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#90974]
We've added support in the DAP for controlling the selection after a completion item has been inserted. See https://github.com/microsoft/debug-adapter-protocol/issues/87.

Now VS Code needs to implement the client side of this feature.

Implementation hint: controlling the selection in VS Code seems to be only possible by using the snippet support. So it might be necessary to convert the result from the DAP completion request into a snippet that uses variables to specify the selection.

**Comment by isidorn** [comment]
I do not think there will be time for this this milestone.
So highly likely we push this out of February.

PR to fix this is welcome
Code pointer https://github.com/microsoft/vscode/blob/66b5e9837d4c6091531f3e32c6e25c0709542aa4/src/vs/workbench/contrib/debug/browser/repl.ts#L134

**Comment by isidorn** [comment]
I have pushed a change that when the `selection` is specified by the debug adapter that we convert the completion item to a snippet and that the selection is respected on snippet accept.
@weinand it would be great if Mock Debug was implementing this so we could try it out in practice. For now adding verification needed label.

Also fyi @connor4312

**Comment by weinand** [comment]
@isidorn I'll add code to Mock debug to exercise the completion request.

**Comment by weinand** [comment]
@isidorn I've added two new completions items to Mock Debug:
in "array[]" the cursor is moved between the brackets and in "func(arg)" the "arg" is selected.

It seems that you are ignoring the selection if the attribute "selectionStart" is set but "selectionLength" is missing (as done in the "array[]" case).
The spec says that "selectionLength" should be assumed to be "0" in that case.

**Comment by isidorn** [comment]
Oh, so that means just place the cursor. Got it. Yeah I can do the change.

**Comment by connor4312** [comment]
I have a change ready to go for this in js-debug as well once the next insiders is released

**Comment by isidorn** [comment]
@weinand pushed a change to cover that case and infer that `selectionLength` is 0 in that case.

**Comment by weinand** [comment]
@isidorn this works fine now, thanks!
