### ISSUE TITLE
colorCustomizations and autoDetectColorScheme

### ISSUE THREAD

**Issue by efc** [microsoft/vscode#90989]
Issue Type: <b>Feature Request</b>

Now that we can `autoDetectColorScheme` (thank you thank you) it seems there should be a way to change `colorCustomizations` automatically too. 

Maybe we need `colorCustomizationsForLightColorTheme` and `colorCustomizationsForDarkColorTheme` for customizations that only apply in one or the other circumstance. The old `colorCustomizations` could still apply across the board, as it does now.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

**Comment by aeschli** [comment]
colorCustomizations can already by scoped to specific themes:

```
"workbench.colorCustomizations": {
    "[Monokai]": {
        "sideBar.background": "#347890"
    }
}
```

**Comment by efc** [comment]
Ah! That'll do. I did not know about the theme scoping.
