### ISSUE TITLE
Editing settings fails with multiple windows

### ISSUE THREAD

**Issue by Blaisorblade** [microsoft/vscode#90986]
1. Open multiple VSCode windows with different folders
2. Open User Settings in multiple windows.
3. Add entries to "Files: Exclude" and "save" them.
4. The entries are not shown in the other windows, and lost on reload.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (2.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
gitignore|cod|0.6.0
unicode-math-vscode|Gui|0.2.6
ott|Joe|0.0.6
lean|jro|0.15.3
dotty|lam|0.1.16
vscoq|max|0.3.0
hide-gitignored|npx|1.0.1
unicode-latex|oij|1.1.2
java|red|0.56.0
scala|sca|0.3.9
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vim|vsc|1.12.4
cursorCharCode|zei|0.1.1

</details>

**Comment by sandy081** [comment]
@Blaisorblade Just want to be sure.. did you  make changes to settings file in all windows or in just one window? Also did you save the file from one window?

**Comment by Blaisorblade** [comment]
I tried again and it's even simpler: 
- use Cmd-, in the first window, add a sample entry `foo` to Files: Exclude and close the settings; the entry is "saved", as can be confirmed by reopening the dialog:
![image](https://user-images.githubusercontent.com/289960/74857104-7ccdd580-5343-11ea-8668-4b3a0468a72a.png)

- check with Cmd-, in the second window — the entry is not there.
![image](https://user-images.githubusercontent.com/289960/74857127-88b99780-5343-11ea-8f6e-f15acbb3d9e8.png)

However, this time after restarting vscode the entry was there again (in both editors). I'll try to find out how to reproduce that part too.

**Comment by Blaisorblade** [comment]
I can also add `foo` in a window, `bar` in another, and only one change will persist after reload. I suppose who writes last wins, but I'd need more experiments to drill this down. Can you reproduce what I documented in the snapshots?

**Comment by sandy081** [comment]
Sorry I can't reproduce. 
- Can you please try with our latest insiders
- Also please open the settings file (which is the truth behind the UI) and check if the file is getting updated or not?
