### ISSUE TITLE
update-alternatives: error: alternative path /usr/bin/code-oss doesn't exist

### ISSUE THREAD

**Issue by chhavikishore** [microsoft/vscode#90982]
- VSCode Version: 1.42
- OS Version: Ubuntu 18.04.4 LTS

Steps to Reproduce:

sudo dpkg -i ./.build/linux/deb/amd64/deb/code-oss_1.43.0-1582114742_amd64.deb

Error :

(Reading database ... 259673 files and directories currently installed.)
Preparing to unpack code-oss_1.43.0-1582114742_amd64.deb ...
Unpacking code-oss (1.43.0-1582114742) ...
Setting up code-oss (1.43.0-1582114742) ...
update-alternatives: error: alternative path /usr/bin/code-oss doesn't exist
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...

Can someone tell how to resolve this issue ?

**Comment by Tyriar** [comment]
We don't distribute code-oss, did you build this yourself?

**Comment by chhavikishore** [comment]
In the Packaging section of How to Contribute section it's written how to package it. I just followed the steps from there and tried to package it using the command : yarn run gulp vscode-linux-x64-build-deb. For reference use the link : https://github.com/Microsoft/vscode/wiki/Cross-Compiling-for-Debian-Based-Linux 
I just used the last command and changed arm to x64 for my OS and it built a package called code-oss, and then while unpacking it gave the error as mentioned in above comment. 
Could you guide me to resolve the issue ?

**Comment by Tyriar** [comment]
The symlink `/usr/bin/code-oss` is created on the line directly above that:

https://github.com/microsoft/vscode/blob/194dae557cf71ceb01fea39c0d56bd1b440e673c/resources/linux/debian/postinst.template#L8-L13

Maybe your session doesn't have permissions to create the symlink? This works fine in other builds so it seems like a problem with your environment. You can always comment out that line if it's blocking you.
