### ISSUE TITLE
Create sign in/sign out commands

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90988]
The sign out command used to be part of the sync component (`Sync: Sign Out`), it should be part of core but its own component that manages multiple accounts, for example `Account: Sign In`, `Account Sign Out`.

**Comment by Tyriar** [comment]
@RMacfarlane wouldn't a generic sign in command be better than extension-specific ones? I'd prefer to see in the command palette just "Account: Sign In" rather than "Microsoft: Sign in", "GitHub: Sign in", etc.

**Comment by KamasamaK** [comment]
@Tyriar And would that generic command then just display a `QuickPick` of the available providers?

**Comment by Tyriar** [comment]
Yes, consolidating the sign out logic into core such that provider extensions don't need to worry about it.
