### ISSUE TITLE
Missing support for for allCommitCharacters

### ISSUE THREAD

**Issue by kirillbobyrev** [microsoft/vscode#90987]
- VSCode Version: 1.42.0
- OS Version: Linux

Steps to Reproduce:

1. Connect to the Language Server which provides `allCommitCharacters` on initialization (I'm using HEAD version of Clangd where I implemented this feature).
2. Open the source file that is supported by this Language Server.
3. Start typing to get completions.
4. Type any character from the server commit characters.

The completion items are not selected which is not the expected behavior.

I don't have much experience with VSCode sources, but I skimmed through the code after installing all node modules and I couldn't find any mentions of `allCommitCharacters` in types or anywhere else. I suspect it is currently not implemented.

It would be great to have this support because this doesn't look too complicated to implement and not having it forces Language Servers to send commit characters for each completion item which is an overhead.

**Comment by jrieken** [comment]
We support [`commitCharacters`](https://github.com/microsoft/vscode/blob/efb781e5becac763a91e7a7434aaef671b38d9a9/src/vs/vscode.d.ts#L3458) on completion items and [`triggerCharacters`](https://github.com/microsoft/vscode/blob/efb781e5becac763a91e7a7434aaef671b38d9a9/src/vs/vscode.d.ts#L8989) on completion providers. I don't know what you are trying to achieve and what API you are following...

**Comment by kirillbobyrev** [comment]
@jrieken What I'm trying to achieve is avoiding sending `commitCharacters` for every completion item and send `allCommitCharacters` during the server initialization via server capabilities to avoid overhead.

`allCommitCharacters` field is part of `completionOptions` in [Completion Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) section. This is the API I'm looking for -- here's the code from LSP specification:

```typescript
/**
 * Completion options.
 */
export interface CompletionOptions extends WorkDoneProgressOptions {
        // ... other code

	/**
	 * The list of all possible characters that commit a completion. This field can be used
	 * if clients don't support individual commit characters per completion item. See
	 * `ClientCapabilities.textDocument.completion.completionItem.commitCharactersSupport`.
	 *
	 * If a server provides both `allCommitCharacters` and commit characters on an individual
	 * completion item the ones on the completion item win.
	 *
	 * @since 3.2.0
	 */
	allCommitCharacters?: string[];

        // ... other code
}
```

So far I couldn't find this in VSCode. Am I missing something?

**Comment by Trass3r** [comment]
clangd doesn't follow the spec though (while it does make much more sense to use a `string` than `string[]` of length 1 each).
https://github.com/llvm/llvm-project/blob/7a514c9bf8f2513b57aee685879dd2c104381d99/clang-tools-extra/clangd/ClangdLSPServer.cpp#L595

**Comment by kirillbobyrev** [comment]
> clangd doesn't follow the spec though (while it does make much more sense to use a `string` than `string[]` of length 1 each).
> https://github.com/llvm/llvm-project/blob/7a514c9bf8f2513b57aee685879dd2c104381d99/clang-tools-extra/clangd/ClangdLSPServer.cpp#L595

Oh, you are right, thanks for spotting it!

**Comment by kirillbobyrev** [comment]
@jrieken can you please explain why this is out of scope? `allCommitCharacters` is in **Language Server Protocol Specification**, VSCode implements this protocol and hence should implement this feature, too. Because it is in LSP, some clients already implement it and servers might rely on it, too, which would bring worse experience to VSCode users and put them at disadvantage.

As per decision-making process [guidelines](https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests):

> In summary, a feature needs to pass one of 1-3 and 4. Otherwise, we'll close it as out of scope. We'll unsubscribe from these issues to reduce the overall number of issue notifications we receive every day.

This issue certainly passes this criteria.

> 1. Has the community at large expressed interest in this functionality? I.e. has it gathered more than 10 up-votes or more than 10 comments? This criterion alone covers more than 650 of the 2850 open feature requests as of right now, October 9th, 2019.

Since you already mentioned this is rather an extension of existing behaviour, this one should be passing, too.

> 2. Does the functionality described in the feature request have any reasonable chance to be implemented in the next 24 months? 24 months is longer than our roadmap which outlines the next 6-12 months. Thus, there is some crystal ball reading on our part, and we'll most likely keep more feature requests open than what we can accomplish in 24 months.

And, finally

> 4. Can our team afford to implement the feature? I.e. are the costs to implement the functionality reasonable compared to the size of our team?

Again, the effort of implementing this should not be very high and it should not be time-consuming.

If you don't plan on implementing this feature, please remove it from LSP. If it is not removed from LSP, it should be implemented in VSCode.

**Comment by jrieken** [comment]
> If you don't plan on implementing this feature, please remove it from LSP. If it is not removed from LSP, it should be implemented in VSCode.

LSP != VSCode - there are likely other clients that do support this directly, VSCode supports this indirectly via `CompletionItem#commitCharacters`

**Comment by kirillbobyrev** [comment]
Yes, but that's an inefficient workaround. Sending a lot of redundant information is not a good strategy. Also, as I already mentioned, it makes UX of VSCode users worse because most servers will just implement LSP and keeping track of where exactly LSP != VSCode is not something they should be worrying about: do servers have to check all the functionality promised in LSP for VSCode now?

Again, the decision process guidelines have criteria saying anything passing 2 out of 4 points should be within the scope. I do not understand why a clearly useful feature is accepted into the roadmap. There are enough users interested in seeing this functionality, it is clearly valuable since it was added to LSP in the first place, not having it hurts VSCode users, and as you already mentioned there is similar infrastructure that can be reused for implementing this feature which significantly reduces the effort required for a sensible implementation.

**Comment by kirillbobyrev** [comment]
@jrieken any update on why this is closed?

**Comment by genlu** [comment]
Looks like this was fixed in https://github.com/microsoft/vscode-languageserver-node/commit/642b0bf71ae782718560ce99ff30e1ca86176c07
