### ISSUE TITLE
Sourcemaps not working in elaborate setup with system.js/node.js/babel/typescript (has example repro project)

### ISSUE THREAD

**Issue by mavericken** [Microsoft/vscode#9098]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:
1. Get https://github.com/mavericken/jspm-node-typescript-vscode.git
2. npm install
3. npm install -g node-inspector
4. node-debug loader.js app.ts (see sourcemaps working)
5. open in vscode and click debug (see sourcemaps not working)

Screenshots here:
# https://github.com/mavericken/jspm-node-typescript-vscode/issues/2

**Comment by roblourens** [comment]
Trying to get the repro to run, and I see a wide variety of errors. I think it has succumbed to bit rot.
