### ISSUE TITLE
Setting UI tabs should have tooltips with settings locations

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#90981]
Issue Type: <b>Bug</b>

If I open a **folder** (not a workspace), then go to the Settings Editor, the second tab is confusingly captioned "Workspace".

![image](https://user-images.githubusercontent.com/6726799/74835041-80963380-5314-11ea-9ea3-0ab60bd58f30.png)

Yet the settings are actually stored in the .vscode\settings.json file within the folder.

If I create a single-root workspace that accesses the same folder, the Settings Editor has 3 tabs as expected, and the one which affects the .vscode\settings.json file is sensibly captioned to indicate this:

![image](https://user-images.githubusercontent.com/6726799/74835333-fb5f4e80-5314-11ea-9fb3-3a70a07d6d25.png)

In this case the Workspace tab is where changes are made that go into the .code-workspace file.

I think that when only a folder is open (not a workspace) the second tab should be captioned in the same way as the third tab on the workspace-mode screenshot.

VS Code version: Code - Insiders 1.43.0-insider (c94724193451009962e2c116808f71a3328a9836, 2020-02-19T09:02:21.024Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
This is actually by design and is consistent with the way we generally use the term "workspace". I get the confusion but don't plan to change it.

**Comment by gjsjohnmurray** [comment]
@roblourens I take your point. Would you at consider making the hover tips for those tabs display the fullly-pathed name of the file that each one affects? At the moment the only way I know of discovering this is to use the Open Settings (JSON) button.

**Comment by roblourens** [comment]
That's a good idea
