### ISSUE TITLE
Window is too wide in word-wrap mode, some text is hidden

### ISSUE THREAD

**Issue by Kinrany** [microsoft/vscode#90992]
Issue Type: <b>Bug</b>

With word-wrap enabled, some text is still not visible without using the scroll bar. Logically there should be no scroll bar in the first place.

This is especially noticeable with minimap enabled.

![bug](https://user-images.githubusercontent.com/1634186/74844914-3f674900-533f-11ea-9837-6ae2edeac23f.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
vscode-firefox-debug|fir|2.6.1
vscode-pull-request-github|Git|0.14.0
rust-analyzer|mat|0.1.20200211
vscode-typescript-tslint-plugin|ms-|1.2.3
vscodeintellicode|Vis|1.2.5
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by alexdima** [comment]
@Kinrany It looks that you are using a script which might use glyphs which are non-monospace. Can you please try `"editor.wrappingStrategy": "advanced"`?

**Comment by Kinrany** [comment]
That helped, thanks!

I wonder if this is something that could be detected automatically?
