### ISSUE TITLE
Declaration Navigation shouldn't expand entire node_modules folder

### ISSUE THREAD

**Issue by Adondriel** [microsoft/vscode#90997]
When I press f12, to navigate to typedefs/source code in my project, and that action navigates to a file in node_modules, don't expand the whole node_modules folder.
I have a couple ideas for how this could be implemented.
1. Just navigate to the file, and don't actually open the node_modules folder at all
2. Use the new sub-folder concatenation thing that was recently added, where it puts 2 folders into 1 tree item.

example of 2 (using NestJS & Fastify as a complex example):
Press F12 on FastifyAdaptor class (This navigates to "node_modules/@nestjs/...")
The file tree should show:
node_modules / @nestjs with all files contained under that
The tree should NOT show ANY other node_modules folders.
Clicking the concatenated tree item should expand the whole node_modules folder.

Current Behavior:
![Code_2020-02-19_10-28-44](https://user-images.githubusercontent.com/1113496/74848427-a8ca6600-5305-11ea-89ad-ee9980cd156a.png)

Suggested Behavior:
![vscode-new-feature-example](https://user-images.githubusercontent.com/1113496/74848568-cb5c7f00-5305-11ea-9100-dcf18c16fa15.jpg)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/89849
And some other issue here https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Afile-explorer+node_modules
