### ISSUE TITLE
Clicking on a icon in the side bar should not close the viewlet but refocus it instead

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#90995]
I very oftern click on the debug icon in the side bar and want to focus it. However if it is focused it closes it which is very disturbing. I would like to request an option to allow me to re-focus instead of closing.

**Comment by sbatten** [comment]
hmm, shouldn't this just be handled by clicking inside the viewlet?

**Comment by dbaeumer** [comment]
This forces me to first look if the debug view is active :-). Here is what usually happens:

- explorer is in front
- I want to debug and press the debug view icon. Everything is nice
- I do some code fixes and want to debug can and press the debug view icon (view closes :-( )

I am so used to clicking the icon when I want to debug that I find it very disturbing when the view closes when I click on it.

**Comment by sbatten** [comment]
@dbaeumer team had some resistance to this, thus leaving it to candidates.

**Comment by dbaeumer** [comment]
What's about a setting. I can understand that breaking this might cause unnecessary swirl.

**Comment by dbaeumer** [comment]
@sbatten any chance to convince you ?

**Comment by dbaeumer** [comment]
@sbatten any feedback?

**Comment by sbatten** [comment]
When I first had this configured the teams was even resistant to a setting but I might add this anyway. How do you feel about letting double click *anywhere* on the activity bar to hide. Single click only changes focus.

**Comment by dbaeumer** [comment]
I like this but it might cause problems due to muscle memory. You would need to put this behind a setting.

**Comment by dbaeumer** [comment]
@sbatten when coming to Redmond the next time :-) I will buy you a beer.

**Comment by sbatten** [comment]
sorry dirk, next month :P

**Comment by dbaeumer** [comment]
No problem :-)

**Comment by dbaeumer** [comment]
THANKS !!!

**Comment by dbaeumer** [comment]
and verified :-)
