### ISSUE TITLE
Function breakpoints experience for debuggers that don't support them is still half-there

### ISSUE THREAD

**Issue by wesrupert** [Microsoft/vscode#9099]
- VSCode Version: 1.3.0
- OS Version: Windows 10

# Steps to Reproduce:

1. Set and hit a breakpoint in a C# app using the C# extension
2. Click the "Add Function Breakpoint" button in the debug pane
3. Type "GarbageMethodName()" and hit enter

*Note: the C# extension does not support function breakpoints, and sends `supportsFunctionBreakpoints: false` during initialization* 

# Expected Result

User cannot even start creating a function breakpoint. Barring that, hitting enter displays an error message that setting function breakpoints is not supported for this debugger.

# Actual Result

Function breakpoint is placed in the "Breakpoints" list with a checkmark beside it, implying it has bound properly:

![image](https://cloud.githubusercontent.com/assets/2474675/16748234/cac124d0-4777-11e6-9a00-960d877c38e7.png)

Looking through the events we get, we aren't even notified that this unsupported breakpoint was created, so we aren't able to surface any meaningful response to the user. The above expected results would be far better fixes for the user, though.

**Comment by weinand** [comment]
@wesrupert breakpoints are not bound to a debug type. One reason for this is that they can be created at any time, even if no debug adapter is running. A consequence of this is that you can create them even if one of the currently installed debuggers cannot handle them.

A checkmark in the "Breakpoints" list does not mean that a breakpoint has bound properly. A checkmark means that the user has enabled the breakpoint.

I agree that breakpoints that are not supported by a running debug adapter should be shown as 'not supported'.

**Comment by isidorn** [comment]
Assigning to july to mark function breakpoints 'unsupported' as soon as a debug session starts
