### ISSUE TITLE
python version shows 2.7.17 while the virtual env 

### ISSUE THREAD

**Issue by mahendrark** [microsoft/vscode#90998]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04.3 LTS

Does this issue occur when all extensions are disabled?: Yes

When I run the python script with the command `print(sys.version)`, it ouputs python version as 2.7.17. 
But, the environment which is activated has python version 3.8.0. The attached screenshot shows that. 
![Screenshot_2020-02-19_16-56-54](https://user-images.githubusercontent.com/13640220/74849948-a255e180-5339-11ea-8141-57e3270673fd.png)

**Comment by isidorn** [comment]
Please file against pyhton extension here. Thank you
https://github.com/microsoft/vscode-python
