### ISSUE TITLE
"editor.minimap.mode": "contain" not behaving as expected with wrapping on

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#90990]
Issue Type: <b>Bug</b>

Testing #90808 by @alexdima 

I set "editor.minimap.mode": "contain" and opened a document for which, prior to this new feature landing, the minimap would extend off the bottom of the window. My actual doc was docs\editor\command-line.md from the microsoft/vscode-docs repo.

With "contain" the minimap behaved as though I had set "actual" (or simply not defined the setting at all), in that it scrolled off the bottom. To get the expected behaviour I had to set "cover".

VS Code version: Code - Insiders 1.43.0-insider (c94724193451009962e2c116808f71a3328a9836, 2020-02-19T09:02:21.024Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alexdima** [comment]
@gjsjohnmurray I am really looking forward to ideas on how to name these settings and perhaps how to improve their documentation, but what you have observed is correct:
* `cover`: the minimap is stretched or shrinked (sampling) such that it always has its contents take the height of the editor.
* `contain`: the minimap is never stretched, just shrinked (sampling) such that it never has its contents take more theight than the editor.
* `actual`: the minimap is never stretched, nor shrinked, each line in the minimap gets a height attributed to it, like 2px, and then the line count determines the height of the minimap content.

Please let me know if you have other ideas for the names or for the descriptions, the current settings I took with a lot of inspiration to the CSS background-image properties.

**Comment by gjsjohnmurray** [comment]
@alexdima I like the names you have chosen, and I was able to understand the descriptions you gave them. But here is a GIF showing the same document, first in  "actual" mode, then in "cover" and finally in "contain". I show the Settings page before each demonstration.

![junk](https://user-images.githubusercontent.com/6726799/74848526-aa108880-532f-11ea-96c4-0242dd8e8de7.gif)

I don't understand why "contain" behaves like "actual" (notice how the minimap scroller isn't the same size as the adjacent scrollbar scroller). I expected "contain" to be the same as "cover".

**Comment by alexdima** [comment]
Thank you, I can reproduce! It reproduces when using wrapping

**Comment by alexdima** [comment]
FYI after #91405, the new setting is `minimap.size` and the values `proportional`, `fit` and `fill`.
