### ISSUE TITLE
anyone know the code in "vscode source code" that implement javascript  intellisense in vscode?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#910]
I want to know how vscode implement JavaScript completions Intellisense, anyone can tell me which place I can to see in "vscode source code"?

**Comment by egamma** [comment]
voila: src\vs\languages\javascript\common\javascriptWorker.ts

**Comment by vaibhavspawar** [comment]
Hello, 
I think the code is modified now. I can't find it at specified location. Can anybody please tell me the new location for the same? Thanks.
