### ISSUE TITLE
died 5 times

### ISSUE THREAD

**Issue by sanbeaman** [microsoft/vscode#91001]
Issue Type: <b>Bug</b>
The TypeScript language service died 5 times right after it got started. The service will not be restarted.
Source: TypeScript and JavaScript Language Features

<b>I just installed code-insider and imported same extensions and settings.. works fine so far on code-insider</b>

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.02GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|2.0.1
better-comments|aar|2.0.5
atlascode|atl|2.4.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
es7-react-js-snippets|dsz|2.5.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
json-tools|eri|1.0.2
prettier-vscode|esb|3.20.0
auto-close-tag|for|0.5.6
vscode-styled-components|jpo|0.0.28
pop-n-lock-theme-vscode|Lux|3.20.15
vscode-language-babel|mgm|0.0.25
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.6
deepdark-material|Nim|3.2.0
material-icon-theme|PKi|3.9.3
vscode-yaml|red|0.7.2
synthwave-vscode|Rob|0.1.1
tint|rsr|1.0.1
code-settings-sync|Sha|3.4.3
sql-bigquery|shi|1.4.0
swdc-vscode|sof|2.1.7
vscodeintellicode|Vis|1.2.5
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0
html-css-class-completion|Zig|1.19.0

(9 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing since this works fine on VS Code insiders. The insiders build contains fixes for this problem
