### ISSUE TITLE
The engine "vscode" appears to be invalid

### ISSUE THREAD

**Issue by g2-aj** [microsoft/vscode#91009]
I have the following section in my package.json:

  "engines": {
    "vscode": "^1.33.0"
  },

When I run "npm vsce package --yarn" I get the following warning:
The engine "vscode" appears to be invalid

If I remove engines.vscode, I get the error:
Error installing vscode.d.ts: Missing VSCode engine declaration in package.json

The yarn version I am using is v1.15.2

How can I get rid of this error?

**Comment by IllusionMH** [comment]
In this case it's useless warning and can be ignored.
Unfortunately - only way to hide error specifically for vscode - only all errors about engine [`yarn install --ignore-engines`](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-ignore-engines)

**Comment by g2-aj** [comment]
Thank you Andrii, this worked to remove the warnings. Thanks!

**Comment by isidorn** [comment]
Not sure if `^` is supported in the engines field. Myabe try some other version. Since you are running vsce forwarding this issue to @joaomoreno

**Comment by weinand** [comment]
I think Andrii's workaround is the only way to get rid of this warning.

(I'm just ignoring the warning)

**Comment by IllusionMH** [comment]
Sorry, removed initial answer, because only later noticed that yarn wasn't launched directly and I wasn't sure if option can be passes. Original answer below:

> In this case it's useless warning and can be ignored.
> Unfortunately - only way to hide error specifically for vscode - only all errors about engine [`yarn install --ignore-engines`](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-ignore-engines)

**Comment by joaomoreno** [comment]
This seems to be a yarn feature.
