### ISSUE TITLE
An ability to link to a file and line and share that link with other person working on that project?

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode#91007]
My and my coworker are working on a project together.

He asks me where is xyz coming from. I investigate, and find the place. I should be able to right click and do copy link to the line and send him the link, which when he clicks opens up the file and highlights the line. Sort of like github similar feature where you can link to file number in a file. Assuming he is working on a same project as well. 

I'm fine if it requires specifying some field jsconfig or such.

**Comment by isidorn** [comment]
Check out some extensions like Open in Github, and GitHub PR extension which shuold have copy line location
fyi @alexr00

**Comment by techsin** [comment]
Ok I'll it a go

**Comment by techsin** [comment]
this is actually pretty integral part of workflow. being able to link to exact file in a project. It'd require all parties to have an extension installed which is unlikely.

**Comment by isidorn** [comment]
Checkout live share.
We will not make this a part of vscode code. VS Code tries to be lean and minimastic.
