### ISSUE TITLE
"Go to definition" stops working

### ISSUE THREAD

**Issue by ashep** [microsoft/vscode#91004]
- VSCode Version: 1.42.1
- OS Version: x86_64 GNU/Linux

Steps to Reproduce:

1. Open editor
2. Work
3. Use "Go to definition" on some object once.
3. After some time "Ctrl + Left Click" stops working, F12 doesn't work, "Go to definition" disappears from the context menu.

[![IMG](https://img.youtube.com/vi/71N-EXgcauw/0.jpg)](https://www.youtube.com/watch?v=71N-EXgcauw)

**Comment by mjbvz** [comment]
Please file this issue agains the python extension
