### ISSUE TITLE
Terminal test failure

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#91003]
`window namespace tests Terminal window.onDidWriteTerminalData should listen to all future terminal data events:`

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=67818&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=c9c1d16f-6a21-57a3-556a-d7a168909c84

**Comment by Tyriar** [comment]
Assuming this happened in remote/web where the tests are flaky.

/duplicate https://github.com/microsoft/vscode/issues/96057
