### ISSUE TITLE
Convert multiple cursors into tab stops

### ISSUE THREAD

**Issue by rsml** [microsoft/vscode#91017]
I'd like to be able to convert my multiple cursors into tab stops.

For example if you had multiple cursors selected and execute this new command:
* Each of your cursors convert into a tab stop (as if you had just inserted a snippet between the first and a last cursor, inclusively).
* The cursor would jump to the first tab stop just like after adding a snippet.
* If the original cursor included a range of characters, then it'll be just like using a snippet tab stop where the default text is the same as the original selection.
* Hitting tab would go to the next tab stop, and so on.

This would be extremely useful for inserting different words at specific points in a systematic way. First you can select all the insertion points, then insert the words one by one.

**Comment by ArturoDent** [comment]
Is this extension what you want?  https://marketplace.visualstudio.com/items?itemName=danseethaler.tab-through-selections

**Comment by rsml** [comment]
Yes! Thank you!
