### ISSUE TITLE
SPACE SPACE in the "Find" text input may insert PERIOD on macOS

### ISSUE THREAD

**Issue by dinofx** [microsoft/vscode#91015]
On Mojave, the OS keyboard/text setting "Add period with double-space" is enabled by default.  This is useful when typing messages, emails, etc.  But when doing a find/replace in VSCode, this keyboard behavior should be suppressed, similar to how smart quotes, spell correction, auto capitalization are suppressed.

- VSCode Version:
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

Steps to Reproduce:

1. Open a text editor and use COMMAND+F to open find
2. press the keys: A SPACE SPACE
3. Notice that the text input now contains a period ( content will be "`a . `")

**Comment by dinofx** [comment]
<img width="324" alt="Screen Shot 2020-02-19 at 2 54 42 PM" src="https://user-images.githubusercontent.com/7581987/74870522-e17b3700-5327-11ea-9ab7-da7ae64e7038.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/7581987/74870559-f0fa8000-5327-11ea-9f39-3da72ea71e28.png">

**Comment by rebornix** [comment]
AFAIK, there is no way for us to disable this feature.
