### ISSUE TITLE
Extra title on panels shown before window loads fully

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91014]
- Connect to a remote
- Before we finish connecting to the remote, I see this title on panels which lets me collapse them.

![image](https://user-images.githubusercontent.com/323878/74866548-eb8d3d80-5307-11ea-97a6-7a75c399ebdf.png)

![image](https://user-images.githubusercontent.com/323878/74866615-06f84880-5308-11ea-86b2-f86a807efa48.png)

**Comment by sbatten** [comment]
adding @sandy081 in case this happened with viewlets before and the fix is known.

**Comment by sandy081** [comment]
It did not happen in viewlets but I suspect in remote it takes long time for extensions be ready. Not sure if we have cache for single view or not for panels which we have for viewlets.

**Comment by sbatten** [comment]
After testing, it looks like this repro's in search viewlet even in much older stable builds but it only happens when there is no cache (a new workspace). It is exaggerated by the remote connection startup time as mentioned by @sandy081

**Comment by sbatten** [comment]
Our behavior is code here: https://github.com/microsoft/vscode/blob/ca05440d7051a764843f2928a118eb6876251863/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L977-L989

After checking if we have a single view and we should indeed merge if there is no other view, we fallback to not merging if the cache is not yet populated. That means for all single view panels, we will see this flashing on the first time opening a workspace where extensions are not yet ready. Either way we will be wrong sometimes, but I am changing this to the opposite as it is more common I believe.
