### ISSUE TITLE
Customize the key for "open to side" in quickopen window

### ISSUE THREAD

**Issue by ppwwyyxx** [microsoft/vscode#91018]
Currently, `<Ctrl+Enter>` seems the only way to "open to side" inside a quickopen window (e.g. after using `<Ctrl+P>`).

I would like to customize the key to have unified experience with other editors I've used. Such feature is possible in ctrlp.vim or ivy (for emacs). Or even better, have different keys to open it to vertical side or horizontal side.

**Comment by bpasero** [comment]
This is now possible via the new `workbench.action.alternativeAcceptSelectedQuickOpenItem` command.

**Comment by bpasero** [comment]
**Verification**
Ensure that you can change the `workbench.action.alternativeAcceptSelectedQuickOpenItem` command key and that it allows to open an editor (e.g. from `Cmd+P`) to the side.
