### ISSUE TITLE
VSCode aggressively changes tab white space settings

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/vscode#91010]
**VSCode Version**: 1.42.0
**OS Version**: Windows 7 x64 Pro

**Steps to Reproduce**: As far as I could determine,
1. I dropped some additional files into my project.
1. Opened using VSCode.
1. Suddenly my tab white space treatment was *tabs* and not *spaces (4)*.

The only thing I can figure is that VSCode somehow "saw" some of the files, which themselves had tabs among the white spaces, and took that to mean "I want tabs, not spaces, for white space".

In a word, **_UGLY_**. An editor should never, ever make this kind of decision, least of all without warning an end user. And, please do not take that to mean, "I want a warning". The editor should just never make that kind of decision, period, end of story.

After digging around a bit, I was able to remediate the situation through corrective actions in my settings, but still.

Using [SQF editor](/Armitxes/VSCode_SQF) for this.

**Comment by mwpowellhtx** [comment]
Should also clarify, the advertised behavior *Editor: Detect Indentation*, *Editor: Insert Spaces*, and possibly *Editor: Tab Sizes*, is simply not working as advertised. I disable detect, insert is enabled, and I am still getting tabs instead of spaces.

**Comment by mwpowellhtx** [comment]
Additionally, I searched and replaced tabs with spaces, rebooted *VSCode*, now spaces are inserted instead of tabs.

**Comment by mwpowellhtx** [comment]
I'm not 100% positive, but there are a couple of sound files among the code, `.ogg` files, which may be causing undue influence in the *VSCode* logic as to whether to use spaces. These are binary files, of course. Is there a way to ignore these files? And/or to include only the files you want for white space consideration?

**Comment by alexdima** [comment]
@mwpowellhtx VS Code has the following options around indentation settings:
```js
	// Controls whether `editor.tabSize#` and `#editor.insertSpaces` will be 
    // automatically detected when a file is opened based on the file contents.
	"editor.detectIndentation": true,
	// The number of spaces a tab is equal to. This setting is overridden based 
    // on the file contents when `editor.detectIndentation` is on.
	"editor.tabSize": 4,
	// Insert spaces when pressing `Tab`. This setting is overridden based on the 
    // file contents when `editor.detectIndentation` is on.
	"editor.insertSpaces": true,
```
By default, `editor.detectIndentation` is true, which means that whenever a file is opened, the indentation settings are picked up from the file. If the file is empty or has no indented lines, the indentation cannot be detected, and the values `editor.tabSize` and `editor.insertSpaces` are used.

If `editor.detectIndentation` is false, then always the values `editor.tabSize` and `editor.insertSpaces` are used.

Additionally, you can install an extension like editor config which will tweak the indentation settings based on its own rules.

What exactly is not working for you? Can you please specify precise steps and explain what is expected, and what is the actual behaviour that you observe?

**Comment by mwpowellhtx** [comment]
I understand that is what it *should* be doing. However, that is *not* what it ***IS*** doing. Best guess, VSCode is finding a binary `.ogg` file in the project work space and interpreting the tabs there as my "intention".

**Comment by alexdima** [comment]
@mwpowellhtx Can you please provide reproducible steps? Otherwise I cannot attempt to reproduce.

**Comment by mwpowellhtx** [comment]
I was able to get into the settings for the file type itself after everything. Not sure why it was defaulting to tabs, however, in spite of the *VSCode* settings. Maybe something to do with the *SQF extension*.

```JSON
{
    // ...
    "[sqf]": {
        "editor.tabSize": 4,
        "editor.detectIndentation": false,
        "editor.insertSpaces": true
    }
}
```
