### ISSUE TITLE
Should "Reopen with Encoding" dropdown include UTF-8 with BOM?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#9101]
- VSCode Version:1.3.0
- OS Version: Windows 10

Steps to Reproduce:

1. Click on Encoding button on Status Bar
2. Select "Reopen with Encoding"

UTF-8 with BOM is not in the list.
It is included if you select "Save with Encoding". 
This came up when looking at vscode-docs bug https://github.com/Microsoft/vscode-docs/issues/402 which calls out that UTF-8 with BOM is missing in the screen shot for "Select File Encoding to Reopen File" dropdown.

**Comment by bpasero** [comment]
No, this only applies to when saving. When a BOM is present we always open with UTF 8.
