### ISSUE TITLE
View: Toggle Panel removes scrollbar from the panel.

### ISSUE THREAD

**Issue by alexander-zolkin** [microsoft/vscode#91019]
Issue Type: <b>Bug</b>

Then I hotkey on "View: Toggle Panel", panel appears without a scrollbar but I can scroll with mouse wheel.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic snap

**Comment by sbatten** [comment]
this is specific to terminal based on my testing.
