### ISSUE TITLE
Notorize me!

### ISSUE THREAD

**Issue by rderewianko** [microsoft/vscode#91021]
Issue Type: <b>Bug</b>

Hello,

VS code is not notorized for distribution on macos. Could that please be done?
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Running commands like 
`xcrun stapler validate /Applications/Visual\ Studio\ Code.app                                             
Processing: /Applications/Visual Studio Code.app
Visual Studio Code.app does not have a ticket stapled to it.`

show indeed there is no notorization

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

**Comment by mattacosta** [comment]
Already done. See #74782.

**Comment by rderewianko** [comment]
Wasn't on the one i pulled off the site this morning :(

**Comment by mattacosta** [comment]
It won't be in the release build until early March. Until then, you have to use the [insiders build](https://code.visualstudio.com/insiders/).

**Comment by rderewianko** [comment]
ahhh okay!
