### ISSUE TITLE
Why did we lose the ability to visualize markdown files? 

### ISSUE THREAD

**Issue by j-martens** [Microsoft/vscode#9102]
- VSCode Version: 1.3.0 
e724f269ded347b49fcf1657fc576399354e6703

2016-07-07T16:50:53.590Z
- OS Version: Mac latest

Steps to Reproduce:

1. I used to be able to click an icon in the upper left to see how the markdown will render.
2. The icon is now gone.

**Comment by f111fei** [comment]
You can right click on the editor tab title and select `open preview`.

**Comment by bpasero** [comment]
Closing as duplicate of https://github.com/Microsoft/vscode/issues/7666
