### ISSUE TITLE
[folding] Command to jump to previous/next fold

### ISSUE THREAD

**Issue by plynch-chwy** [microsoft/vscode#91023]
It would be useful for navigating code to have a command to jump to previous/next foldable line. This would allow me to easily jump to the lines that I can either fold/unfold.

**Comment by aeschli** [comment]
To verify:
- assign keyboard shortcuts to the new fold navigation commands
e.g.
[
	{
		"key": "ctrl+k ctrl+,",
		"command": "editor.jumpToNextFold"
	},
	{
		"key": "ctrl+k ctrl+.",
		"command": "editor.jumpToPreviousFold"
	},
	{
		"key": "ctrl+k ctrl+;",
		"command": "editor.jumpToParentFold"
	}
]
- try the commands

**Comment by plynch-chwy** [comment]
Awesome! Do I need to update my version to add this? I'm on macos Version: 1.58.2 currently and tried to my shortcuts, but didn't get it to work.

**Comment by gjsjohnmurray** [comment]
@plynch-chwy to get it you need to install Insiders.

**Comment by plynch-chwy** [comment]
Ahh I see the `insiders-released` tag now, thanks.
