### ISSUE TITLE
[json schema 'defaultSnippets'] escaping of '$' chars don't work

### ISSUE THREAD

**Issue by joem-msft** [microsoft/vscode#91024]
I'm adding a 'defaultSnippets' property to a schema in my workspace that has a tabstop and some '$' chars that need to be in the output.

Here's an example schema with a couple examples of the escaping:
```json
{
    "type": "object",
    "properties": {
        "parameters": {
            "type": "object",
            "defaultSnippets": [
                {
                    "label": "Snippet with '$' chars",
                    "body": {
                        "${1:paramName}": {
                            "description": "This is a description for parameter ${1:paramName} which uses \$valueSuffix in the key.",
                            "keyName": "${2:YourApiName}-$(\$valueSuffix)-${1:paramName}"
                        }
                    }
                }
            ]
        }
    }
}
```

Here's what the default snippet produces:
```json
{
  "parameters": {
    "paramName": {
      "description": "This is a description for parameter paramName which uses valueSuffix in the key.",
      "keyName": "YourApiName-$(valueSuffix)-paramName"
    }
  }
}
```

And this is what's expected (note the '$' chars before the occurrances of 'valueSuffix'):
```json
{
  "parameters": {
    "paramName": {
      "description": "This is a description for parameter paramName which uses $valueSuffix in the key.",
      "keyName": "YourApiName-$($valueSuffix)-paramName"
    }
  }
}
```

I've tried many ways of escaping and nothing seems to work correctly. It seems that the $ before a ( char does show up correctly though.

**Comment by ArturoDent** [comment]
Try escaping with a `$` so actualy `$$` to get one `$`.

**Comment by aeschli** [comment]
'\' is the correct escape character: See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar

But as this inside a JSON string and `\` is also the JSON escape character, you need `\\`.

**Comment by joem-msft** [comment]
Is there a way to re-open an issue?

It would be great if the suggestions given as a fix actually work. ;-) Please have the examples a try on your own instances to confirm. A reply with valid escaping working would be helpful too.

> '' is the correct escape character

oh, haha, looks like GitHub MD editor hid the character but I'm guessing you meant '\\' (the backslash char).

Yes, the documentation grammar does state that the backslash character *should* escape the $ char. But this bug is to say that it doesn't work as documented.

Here is another schema file with examples where each snippet is an attempt to escape the chars. This is the simplest form of snippet body values and it still repros:

Save to file named: snippets-test.schema.json
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "./snippets-test.schema.json",
    "type": "object",
    "properties": {
        "expected": {
            "enum": [
                "[$valueSuffix]"
            ]
        },
        "snippet-escaping": {
            "type": "object",
            "properties": {
                "no-escaping": {
                    "type": "string",
                    "defaultSnippets": [
                        {
                            "body": "[$valueSuffix]"
                        }
                    ]
                },
                "single-backslash": {
                    "type": "string",
                    "defaultSnippets": [
                        {
                            "body": "[\$valueSuffix]"
                        }
                    ]
                },
                "double-backslash": {
                    "type": "string",
                    "defaultSnippets": [
                        {
                            "body": "[\\$valueSuffix]"
                        }
                    ]
                },
                "tripple-backslash": {
                    "type": "string",
                    "defaultSnippets": [
                        {
                            "body": "[\\\$valueSuffix]"
                        }
                    ]
                },
                "double-$$": {
                    "type": "string",
                    "defaultSnippets": [
                        {
                            "body": "[$$valueSuffix]"
                        }
                    ]
                },
                "single-quotes": {
                    "type": "string",
                    "defaultSnippets": [
                        {
                            "body": "['$'valueSuffix]"
                        }
                    ]
                }
            }
        }
    }
}
```

Save the following as the initial json file in the same folder as the schema above:
```json
{
    "$schema": "./snippets-test.schema.json",
    "expected": "[$valueSuffix]",
    "snippet-escaping": {
    }
}
```

Then, add each property under 'snippet-escaping' using auto-fill intellisense to activate each snippet. (e.g. use ctrl+spac => enter, for each property available)
![image](https://user-images.githubusercontent.com/11097302/74981366-f965c000-53e6-11ea-878f-aca13cf0a481.png)

 The following are the results:
```json
{
    "$schema": "./snippets-test.schema.json",
    "expected": "[$valueSuffix]",
    "snippet-escaping": {
        "no-escaping": "[]",
        "single-backslash": "[valueSuffix]",
        "double-backslash": "[\]",
        "tripple-backslash": "[\valueSuffix]",
        "double-$$": "[$]",
        "single-quotes": "['$'valueSuffix]"
    }
}
```
None of these work!

If escaped properly, the property value should be equal to `"[$valueSuffix]"`.
The backslash chars don't work at all to show the '$' char, but does help to show the `valueSuffix` part.
While the double `$$` seems to work to make the `$` show up, the BUG is that the 'valueSuffix' that follows the `$$` is lost.

**Comment by aeschli** [comment]
Ok, sorry, it's been a while since I've looked at that. First we read the body from a JSON string, then we stringify it again to generate the proposal text. There's no way of having "\$valueSuffix" as the output of a JSON.stringify.
That's why we came up with another approach as documented in https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas:

>  If a string starts with ^, the string content will be inserted as-is, not stringified

So this should do it for you:
```json
{
  "defaultSnippets": [
    {
      "label": "Snippet with '$' chars",
      "body": "^{\n\t\"${1:paramName}\": {\n\t\t\"description\": \"This is a description for parameter ${1:paramName} which uses \\$valueSuffix in the key.\",\n\t\t\"keyName\": \"${2:YourApiName}-$(\\$valueSuffix)-${1:paramName}\"\n\t}\n}"
    }
  ]
}
```
Not pretty, but better than nothing, right?

**Comment by joem-msft** [comment]
Thank you Martin!

That got me unblocked to see a literal example. Yes, that is a non-pretty solution yet better than nothing. And I have good news, it can still be pretty. Only certain strings need to use the '^' escaping technique above.

Essentially, 
> a string in the "body" that contains a '$' char followed by 1+ word chars would need '^' escaping along with backslash escaping in order to work correctly.

This makes it so we can still keep json-formatting for most of the snippet body.

Example:
```json
{
  "defaultSnippets": [
    {
      "label": "Snippet with '$' chars",
      "body": {
        "${1:paramName}": {
          "type": "integer",
          "title": "This string doesn't need to be '^' escaped because it doesn't need backslash character escaping of '$' characters.",
          "description": "^\"This is a description for parameter ${1:paramName} which uses \\$valueSuffix in the key.\"",
          "keyName": "^\"${2:YourApiName}-$(\\$valueSuffix)-${1:paramName}\""
        }
      }
    }
  ]
}
```

Another thing about this final result has is that both the schema file and the end snippet result does not have invalid character escaping errors of the use of the backslash character. For most of my other examples, VS Code was highlighting invalid '\\' char usage with RED coloring. Heck, even GitHub's MD viewer is doing this highlighting (see above json code).

Thanks again Martin!

**Comment by joem-msft** [comment]
For completeness, here's what the output of my last snippet produces:
```json
{
  "paramName": {
    "type": "integer",
    "title": "This string doesn't need to be '^' escaped because it doesn't need backslash character escaping of '$' characters.",
    "description": "This is a description for parameter paramName which uses $valueSuffix in the key.",
    "keyName": "YourApiName-$($valueSuffix)-paramName"
  }
}
```
