### ISSUE TITLE
Progress icon is shown when sync server is slow to respond

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91026]
I don't think we want to be showing when the server is slow to respond to the user as when this does happen it should (hopefully) get resolved relatively quickly. A more toned down way of notifying would be preferable like an indicator inside the gear menu on the turn off sync icon, or alternatively none at all.

This has happened sometimes when tweaking with the infrastructure and while we'll try minimize this in production, the client shouldn't be telling everyone or otherwise we might interrupt people and could get a bunch of unnecessary issue reports.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/89006
