### ISSUE TITLE
TypeScript and JavaScript Language Features, as well as VS Code, crashing intermittently

### ISSUE THREAD

**Issue by desnor** [microsoft/vscode#91025]
Issue Type: <b>Bug</b>

VS Code just told me that the TypeScript and JavaScript Language Features extension crashed soon after restarting  five times overnight, so it will no longer start it.

Lately I've found my VS Code app to be very slow, and often it says that it has crashed unexpectedly, showing me a confirmation dialogue. I click OK and the application just continues as usual. So I'm not sure exactly what has failed, seeing the overall app has continued to function, albeit often very slowly. It can take 10 - 15 seconds sometimes to evaluate the type of a variable when I hover the cursor over it.

I have tried restarting VS Code, as well as my machine, and I keep the versions up to date. So I'm not really sure what's up, and I'm sorry I can't give more info but it's happening quite often now and is a real pain.

Thanks for any help you can offer on this

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2687)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 1, 0|
|Memory (System)|15.50GB (5.29GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-eslint|dba|2.0.15
tslint|eg2|1.0.44
prettier-vscode|esb|3.20.0
vscode-styled-components|jpo|0.0.28
atom-keybindings|ms-|3.0.6
color-highlight|nau|2.3.0
vetur|oct|0.23.0
indent-rainbow|ode|7.4.0
seti-icons|qin|0.1.3
ruby|reb|0.26.0
java|red|0.56.0
salesforcedx-vscode|sal|48.1.0
salesforcedx-vscode-apex|sal|48.1.0
salesforcedx-vscode-apex-debugger|sal|48.1.0
salesforcedx-vscode-apex-replay-debugger|sal|48.1.0
salesforcedx-vscode-core|sal|48.1.0
salesforcedx-vscode-lightning|sal|48.1.0
salesforcedx-vscode-lwc|sal|48.1.0
salesforcedx-vscode-visualforce|sal|48.1.0
code-settings-sync|Sha|3.4.3
vscode-status-bar-format-toggle|tom|2.0.0
transpose|v4r|0.0.5
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
quokka-vscode|Wal|1.0.278
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.26.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0

(8 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by desnor** [comment]
Thanks for the reply, I installed the insiders build and it has been all
good since then, with and without extensions running. So I think I'll just
keep using this version anyway now.
