### ISSUE TITLE
There is no keyboard shorcut to open keybindings.json

### ISSUE THREAD

**Issue by AndrewRayCode** [microsoft/vscode#91033]
There is no keyboard shortcut to open the page that customizes keyboard shortcuts.

keybindings.json is impossible to find :(

**Comment by ArturoDent** [comment]
Are you talking about:

> workbench.action.openGlobalKeybindingsFile
>  `"command": "workbench.action.openGlobalKeybindingsFile"`

**Comment by sandy081** [comment]
Yes it has no shortcut by default. You can assign one from Keyboard Shortcuts Editor.
