### ISSUE TITLE
Issue reporter UI should better indicate that "Don't Know" cannot be used for submission

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#91032]
Extracted from https://github.com/microsoft/vscode/issues/90937

> Additionally, when trying to submit an issue using Report Issue from the Command Palette, if I choose "File on > Don't Know" nothing happens when I click the Preview on GitHub button and I'm unable to report the issue from that form.

VS Code version: Code 1.42.1 (c47d83b, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

**Comment by gjsjohnmurray** [comment]
@RMacfarlane related to this issue, can @connor4312's [suggested improvement](https://github.com/microsoft/vscode/issues/73515#issuecomment-579853925) to the use-case of picking an extension without a GH repo also be implemented?

**Comment by RMacfarlane** [comment]
Added validation messages for empty fields with https://github.com/microsoft/vscode/commit/fe4d4f7d027ed65cd02197e73b364548e6b6ef13.
