### ISSUE TITLE
editor.foldBackground affect editor.selectionBackground color

### ISSUE THREAD

**Issue by bwnl** [microsoft/vscode#91034]
Issue Type: <b>Performance Issue</b>

Set up editor.foldBackground or editor.selectionBackground in settings.json will affect display of the other. If editor.foldBackground is specified, folded code selected in editor will not have visible highlighting.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
Add a transparency value to your `editor.foldBackground`

![image](https://user-images.githubusercontent.com/6726799/74918032-687bee00-53c0-11ea-9076-937b4564f429.png)

**Comment by aeschli** [comment]
Yes, that's correct, the `editor.foldBackground` should always be defined with a transparency value.
I updated the description.
