### ISSUE TITLE
Ctrl+Up/Down and Stift+Tab trigger new search if focus "files to include/exclude" fields

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#91031]
Issue Type: <b>Bug</b>

When <kbd>Ctrl</kbd>+<kbd>↑</kbd> or <kbd>Shift</kbd>+<kbd>Tab</kbd> focus "files to include" or "files to exclude" fields new search is triggered even if no changes were made. There are no problems if these actions focus "Search" and "Replace" fields or if I use <kbd>Tab</kbd>.

1. Make sure that `search.searchOnType` is `true` and you have search results in Find in Files (it's also possible to remove few results to see effect)
1. Focus "files to exclude" field
1. Press <kbd>Ctrl</kbd>+<kbd>↑</kbd>
1. Searh is performed again (all result are resotred if some were removed)
1. Press <kbd>Ctrl</kbd>+<kbd>↑</kbd> again (focus will be in "Search" or "Replace" field)
1. No new search until triggered by change

/cc @JacksonKearl 

VS Code version: Code - Insiders 1.43.0-insider (13d7b3066ab6e8993f12c28b0ced297781055ffc, 2020-02-19T17:43:05.977Z)
OS version: Windows_NT x64 10.0.19564

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by JacksonKearl** [comment]
Thanks!

More complicated of a fix than strictly necessary but it cleans things up quite a bit.
