### ISSUE TITLE
Debugging call stack is missing frames

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#91037]
- VSCode Version: 1.42.1
- OS Version: Windows

Steps to Reproduce:

1. I'm using the C/C++ extension to debug C/C++ code, but the call stack is cutoff. The top of the call stack has no symbols, which could be the cause (deep call stacks with symbols at the top show all the frames)...this is with multiple threads as well. See the screenshot. There's no option to show more frames.

![image](https://user-images.githubusercontent.com/19859882/74894766-c79c1d00-5344-11ea-970c-6ecfe0cd44e6.png)

I filed a previous issue at https://github.com/microsoft/vscode/issues/68474 but it got closed with needing more info. The fixed bug at https://github.com/microsoft/vscode/issues/81406 might have the same root cause, but might need a fix in a different place.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sean-mcmanus** [comment]
@pieandcakes @WardenGnaw The C/C++ extension wouldn't be the cause of this, right?

**Comment by isidorn** [comment]
1. Do you see VS code requesting for the top of the call stack in the C++ extension
2. Is the C++ extension properly responding to this request
3. Can you reproduce with vscode insiders?

No other extension is seeing this, thus my main suspicion would be in the extension code.

**Comment by sean-mcmanus** [comment]
Our C/C++ debugger team told me to enable their logging, but now I'm not repoing the bug any more (I'm not aware of what changed to cause it to stop reproing, maybe the repro conditions were more complicated).
