### ISSUE TITLE
Replace Context Menu/Edit Install Option

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#9103]
I'd like an install option to have vscode replace Notepad/Powershell ISE/etc as my default editor when I select "Edit" from the context menu.

**Comment by joaomoreno** [comment]
What is your OS?

**Comment by garfieldbanks** [comment]
W10

**Comment by joaomoreno** [comment]
We won't overwrite that `Edit` menu, but you can associate your file to open with VS Code, such that a double click would do it.
