### ISSUE TITLE
High CPU usage when typing a comment (~15%)

### ISSUE THREAD

**Issue by ProgrammingLife** [microsoft/vscode#91046]
- VSCode Version: 1.42.1
- OS Version: Linux Mint 19.3

Steps to Reproduce:

1. Start typing any comment like this: // asdf asdf asd fasd asdf
2. CPU goes from 0-1% usage up to 15% and never falling back to 1% while you are still typing a comment

Looks like it didn't work like this in the previous version of VS Code. Right just after update.
There is no such big CPU usage when I type just a text near a code. Issue is only with the comments.

My project is big but it's just a comment. I don't want that my comments will be analyzed by VS Code. Why does it work like this?

**Comment by gjsjohnmurray** [comment]
What language are you coding in? And does the problem also happen if you launch with all extensions disabled?
