### ISSUE TITLE
Terminal  prompt emoji chars conflict with each other

### ISSUE THREAD

**Issue by jaredyam** [microsoft/vscode#91043]
- VSCode Version: 1..42.1
- OS Version:  macOS Catalina 10.15.3 (19D76)

Steps to Reproduce:

1. **Zsh theme setting**
I am using iTerm2 with `spaceship` theme. Using the zsh config below
```bash
ZSH_THEME="spaceship"
SPACESHIP_CHAR_SYMBOL=(" \u203d ")
SPACESHIP_CHAR_PREFIX=(🌈💛🧡💜)
``` 
I can get the bash prompt looks like this:
![image](https://user-images.githubusercontent.com/50312506/74903532-26fd3a00-53e4-11ea-9d56-f2293b395b6e.png)

2. **Open the vscode Terminal**
All emoji chars have been conflicted with each other, here is my screenshot:
<img width="586" alt="Screen Shot 2020-02-20 at 1 08 00 PM" src="https://user-images.githubusercontent.com/50312506/74903863-36c94e00-53e5-11ea-8272-56b52bd108f8.png">

So, How can I get rid of this awkward situation with an ugly deformed look?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
