### ISSUE TITLE
1.43 insider error Illegal value for 'line'

### ISSUE THREAD

**Issue by SanJin-hx** [microsoft/vscode#91049]
```
版本: 1.43.0-insider (user setup)
提交: 13d7b3066ab6e8993f12c28b0ced297781055ffc
日期: 2020-02-19T17:43:05.977Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

![image](https://user-images.githubusercontent.com/26178326/74907901-52d1ed00-53ef-11ea-8b4d-bbcc03f3cae0.png)

**Comment by gjsjohnmurray** [comment]
Seems to be coming from your spywhere.guides extension. Please report in on that extension's repo and close here.
