### ISSUE TITLE
Suggestions and Intellicode no longer working after changing color theme

### ISSUE THREAD

**Issue by prasadz133** [microsoft/vscode#91045]
what I did is just changed the color theme and after that, it is stopped working as expected regular behavior, It is **not showing suggestions**, **VS Code IntelliCode** also not working as before I have done efforts of my side as like uninstalled all extensions and installed them again, deleted VS Code from applications and installed it again.
In the image, You can see the extensions which are using currently and also you can observe that I'm using the style of justify-content when I typed the quotes then it is supposed to show all the values available for it. but it is not showing currently.
![Screenshot 2020-02-20 at 10 33 58 AM](https://user-images.githubusercontent.com/47117216/74905155-78e99400-53d3-11ea-87c9-bf5af7a96c45.png)

Please let me know, are there any possible ways to get back to the normal behavior of VS Code for Mac? I already uninstalled all the extensions and installed them again, removed VS Code from Applications. and downloaded the latest version from the official VS Code site.

**Comment by mjbvz** [comment]
Please fill out the issue template with your VS Code version and OS

 /needsMoreInfo

**Comment by prasadz133** [comment]
Hi,
VS Code version: 1.42.1,
OS: Darwin x64 19.3.0

Finally, I have created another User account. It is working fine in new user account.
May be I missed some VSCode settings in previous user account.
