### ISSUE TITLE
Investigate what Shift+Insert should do by default on Linux

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91051]
With #36170, we have changed Shift+Insert on linux to paste from the selection clipboard. There are a lot of complaints following this change - #90929, #90297, #90637, #90716

This issue is a plan item to investigate what do other well established Linux code editors do by default and then see what is expected.

fyi @Tyriar

**Comment by bsutton** [comment]
The list of editors that I currently use that work the way I expect:
Eclipse
Intellij
Word
Libre Office
Google docs
Notepad
Leaf
Chrome's search bar :)
gmail's editor
Even the gnome terminal's Find field.
Any text field in any app that I've ever used.

The only 'editors' that I know of that don't support the default
shift-insert are
vi
terminal.

**Comment by vlad-vinogradov** [comment]
@alexdima  Actually the question should be:  what is Shift-Insert used for most often - for Insert or Replace?

And keep in mind that for several years of using VS Code users have acquired certain automatic editing skills that are difficult to change. For this reason it is always wiser to provide a new style of Copy/Paste operations as an additional option rather as the default mode.

**Comment by StephenSeltzer** [comment]
I would also add to @vlad-vinogradov that it isn't just VS Code, it is pretty much all editors I have used that support Shift+Insert the same way that VS Code used to. @alexdima I can appreciate the thought behind what was done but the difference is that when working on the command line you never want to replace text, just paste it. In an editor I expect to be able to highlight a block of text, press Shift+Insert, and have that block replaced with whatever I copied using Ctrl+Insert (or Ctrl+C).

**Comment by foxsam21** [comment]
@vlad-vinogradov This is an issue of what clipboard is used when pasting with `shift+ins` it has nothing to do with insert vs replace.

It seems that the users claiming 'true' linux uses `shift + ins` to paste from selection keyboard are [correct](https://askubuntu.com/a/356032). However it does seem like most of us, even long-time linux users, are used to the non-linux style which is more prevalent on today's guis. It would probably be best to have the `shift+ins` binding off by default and those that are used to the 'correct' linux way can just enable the binding.

**Comment by vlad-vinogradov** [comment]
@foxsam21 We are all "true" VS Code users here.
Until recently, the use of Shift-Insert in VS Code was the equivalent of Ctrl-V. So each of us used the keys combination more convenient for him personally - and it is already hardcoded in "muscle firmware". Earlier those who use Shift-Insert  could select a certain text fragment with the keyboard and replace it with the Clipboard contents. Now in default mode  this operation cannot be performed using Shift-Insert - you need to change what has already turned into a reflex. To restore previous mode of operation 1) you need to guess that something has changed in VS Code and not just the keyboard is malfunctioning, and 2) you need to take some unobvious steps to reconfigure VS Code. This is what causes inconvenience to users.

**Comment by foxsam21** [comment]
> We are all "true" VS Code users here.

I am talking about "true" **_linux_** users. The ones that are used to using two clipboards.

**Comment by bsutton** [comment]
I wonder if the real point of difference here is gui vs console.

The gnome gui and all gui applications define shift-ins to be the same as ctrl-v.

I'm not surprised that the console works differently but I am surprised when a gui app works differently.

**Comment by unitysipu** [comment]
I also consider current version of VSCode with the altered behavior completely broken to the point of affecting my productivity. I've been using shift-insert as "paste" from the 90's and this works in pretty much any other editor also on linux.

**Comment by gjsjohnmurray** [comment]
@unitysipu are you aware of how you can [revert the change](https://github.com/microsoft/vscode/issues/90716#issuecomment-588116868) ?

**Comment by unitysipu** [comment]
Yeah, thanks. I'm just annoyed I had to waste time on this. 
As a multi-OS user I value consistency in the behavior of multi-platform tools.

**Comment by alexdima** [comment]
I have also tried some GUI applications on Ubuntu, including the default Text Editor and can confirm that Shift+Insert is pasting from the "clipboard" clipboard, not from the selection clipboard, so I will change Shift+Insert to basically work as Ctrl+V by default (like it was before 1.42). It will still be possible to get that Shift+Insert pastes from the selection clipboard by using:
```
{
	"key": "shift+insert",
	"command": "editor.action.selectionClipboardPaste",
	"when": "textInputFocus && config.editor.selectionClipboard"
}
```
