### ISSUE TITLE
ContextKey: weird behaviour in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91058]
I figured this out after a long time looking into https://github.com/microsoft/vscode/issues/90885 and wonder if this is a more general issue with context keys.

Steps to see the bug:
* revert https://github.com/microsoft/vscode/commit/a3c79c70b027aa7ad24be3b681f6dcc76a8d6931
* open vscode out of sources with no file open
* open 1 file
* click split button
* right click into that split editor tab that just opened

![image](https://user-images.githubusercontent.com/900690/74918868-088a4500-53ca-11ea-89b4-f493dce5ddd9.png)

=> 🐛 you see no entries for "Copy Path" and "Copy Relative Path"

Now, these commands are contributed to the tab context menu via [`ResourceContextKey.IsFileSystemResource`](https://github.com/microsoft/vscode/blob/a3c79c70b027aa7ad24be3b681f6dcc76a8d6931/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L169).

Interestingly, inspecting the context keys on the tab shows that `IsFileSystemResource` equals to `false` which explains why the commands are not appearing. However, other context key properties that are related do show up properly, e.g. `resourceScheme`. They are all set from [`ResourceContextKey`](https://github.com/microsoft/vscode/blob/a3c79c70b027aa7ad24be3b681f6dcc76a8d6931/src/vs/workbench/common/resources.ts#L19) and I verified that they are properly set.

So that leaves the question: how come that the default value for a context key (basically the commit I had to do in https://github.com/microsoft/vscode/commit/a3c79c70b027aa7ad24be3b681f6dcc76a8d6931) impacts the result of the context key? 

To add to the complexity: context key services are scoped per editor group (from [here](https://github.com/microsoft/vscode/blob/a3c79c70b027aa7ad24be3b681f6dcc76a8d6931/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L173)). 

Maybe this is an issue only for scoped context keys when resolving the value?

**Comment by alexdima** [comment]
@bpasero 

`undefined` behaves differently than `false` when it comes to inheriting contexts, which appears that the workbench is making heavy use of. I have added tracing to how the context key `isFileSystemResource` is used. This can be done in here -- https://github.com/microsoft/vscode/blob/093ada38305dc4b26bdfb62ae86bca245cb9d233/src/vs/platform/contextkey/browser/contextKeyService.ts#L29-L53

---

For a child context, the value `undefined` means that the context key value should be inherited from the parent context. The value `false` means that the context key value is false.

So when defining `isFileSystemResource` to be `false` by default, it means that all the child contexts will have the value `false` until the value is set to `true` explicitly on them.

When defining `isFileSystemResource` to be `undefined` by default, it means that all the child contexts will inherit the value from their parent context until the value is set explicitly on them.

From what I can tell, the key `isFileSystemResource` is set to true in a parent context and is not set in the child context, so using `false` will make the effective value be `false`.
