### ISSUE TITLE
[Feature Request]: Variable Watch Folders

### ISSUE THREAD

**Issue by chrisaramar** [microsoft/vscode#91055]
Hi I would like to request a feature which I think is really simple and helps a lot.

While debugging my python scripts I like to use the "watch" for variables to see whats their value. 

My request is:

Add folders to watch so you can group watch variables and so it's possible to fold them and unfold them. This is helpfull if you debug a script through multiple function calls which are not in the same script. So every var is shown as "Not defined" while in the same script. With folder it's possible to get more structure into debugging :)

Only a thought.

Regards
chrisaramar

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
