### ISSUE TITLE
Resolve Environment Variables in Args defined in launch.json for Debugging

### ISSUE THREAD

**Issue by BorisPolonsky** [microsoft/vscode#91053]
For debugging configuration in `launch.json`, it will be helpful if VSCcode resolves environment variables (defined in `env`) in `args`.

 A typical user case will be something like this:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Squad 2.0 Training (Bug)",
            "type": "python",
            "request": "launch",
            "program": "run_squad.py",
            "console": "integratedTerminal",
            "justMyCode": true,
            "env": {
                "PRETRAIN_BERT_DIR": "/path/to/pretrained_model",
                "SQUAD_DIR": "/path/to/squad",
                "OUTPUT_DIR": "./path/to/output"
            },
            "args": [
                "--vocab_file", "${env:PRETRAIN_BERT_DIR}/vocab.txt",
                "--bert_config_file", "${env:PRETRAIN_BERT_DIR}/bert_config.json",
                "--init_checkpoint", "${env:PRETRAIN_BERT_DIR}/bert_model.ckpt",
                "--do_train", "True",
                "--train_file", "${env:SQUAD_DIR}/train-v2.0.json",
                "--do_predict", "True",
                "--predict_file", "${env:SQUAD_DIR}/dev-v2.0.json",
                "--train_batch_size", "24", 
                "--learning_rate", "3e-5",
                "--num_train_epochs, 2.0",
                "--max_seq_length", "384",
                "--doc_stride", "128",
                "--output_dir", "${env:OUTPUT_DIR}",
                "--do_lower_case=False",
                "--version_2_with_negative", "True"
            ]
        }
    ]
}
```
where the user may wish to alter values of key `vocab_file`, `bert_config_file` and `init_checkpoint` in `args` in one shot by defining environment variables in `env`, instead of repeatedly searching and substituting those common sub-strings in `args` every time he wish to alter `PRETRAIN_BERT_DIR`.

In current Version of VSCode, using `${VARIABLE}` or `${env:VARIABLE}` syntax in `args` will return empty strings in current version of VSCode. 

## Note
This has already been acknowledged as bug of Python extension in #77050, I filed #10163 as bug and the respond is that I should file it as feature request of VSCode.

**Comment by gjsjohnmurray** [comment]
@BorisPolonsky the correct link to the issue you raised on the extension's repo is https://github.com/microsoft/vscode-python/issues/10163

I think the extension needs to adopt the new-in-1.42 `DebugConfigurationProvider` hook `ResolveDebugConfigurationWithSubstitutedVariables` that receives the debug configurations with all variables resolved. Details can be found in #89375

**Comment by isidorn** [comment]
Thanks a lot @gjsjohnmurray for answering. Thus closing, please continue the discussion in the python respository

**Comment by karthiknadig** [comment]
@isidorn Does `ResolveDebugConfigurationWithSubstitutedVariables` resolve the case that user posted? If you look the `PRETRAIN_BERT_DIR` env variable is defined in the `env` field, and later used in the `args` field. Can VSCode resolve environment variables defined int eh config itself?
