### ISSUE TITLE
Visual Studio code hangs after killing the Terminal

### ISSUE THREAD

**Issue by ritatinoco** [microsoft/vscode#91066]
Issue Type: <b>Bug</b>

When I debug a some karma tests and then click on kill terminal my vs code hangs and then crashes. 

This also happens on tasks that didn't completed yet and I simply kill it before ending

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (3.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.12.0
gitlens|eam|10.2.1
vscode-great-icons|emm|2.1.47
duplicate|gee|1.0.1
csharp|ms-|1.21.11

</details>

**Comment by gjsjohnmurray** [comment]
Can you reproduce this after running the command to reload with all extensions disabled?

If so, [follow these steps to capture the native crash](https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#windows).

**Comment by ritatinoco** [comment]
Yes I can. I've attached these two files with exceptions 

[Code__PID__26104__Date__02_20_2020__Time_10_49_55AM__780__Log.txt](https://github.com/microsoft/vscode/files/4231093/Code__PID__26104__Date__02_20_2020__Time_10_49_55AM__780__Log.txt)
[Code__PID__34092__Date__02_20_2020__Time_01_37_40PM__221__Log.txt](https://github.com/microsoft/vscode/files/4231094/Code__PID__34092__Date__02_20_2020__Time_01_37_40PM__221__Log.txt)

Let me know if you need anything else 😁

**Comment by ritatinoco** [comment]
I might be helpful I'm able to reproduce this everytime that I kill the process and then I imidiately start to change any file

**Comment by sythem** [comment]
This is **not** fixed in Windows > 1903 as stated in [76548](https://github.com/microsoft/vscode/issues/76548).

VScode 1.42.1 on Windows 10 x64 18363 (1909) using CMD as the terminal still hangs when closing a used terminal manually or through vscode.Terminal.dispose().

**Comment by Tyriar** [comment]
No it's not fixed, Windows reverted the fix and there's a tracking item in the terminal repo https://github.com/microsoft/terminal/issues/1810
