### ISSUE TITLE
Post-installation tip: The selected drive or UNC share does not exist or is inaccessible. Please choose another

### ISSUE THREAD

**Issue by yizeAnkh** [microsoft/vscode#91064]
- VSCode Version: 1.42.1
- OS Version: win 10

Steps to Reproduce:

1.I deleted the vscode software file between them, and the disk on which It was also formatted and merged into other disks
2.Now download the installation package again to reinstall, there is no place to select the installation directory and prompt "The selected drive or UNC share does not exist or is inaccessible." Please select another installation error

![错误截图](https://user-images.githubusercontent.com/48954766/74922251-e6b0b280-5409-11ea-91f2-2a2daec0bb99.jpg)

**Comment by joaomoreno** [comment]
Please do not install on a UNC path, but on a local path.
