### ISSUE TITLE
Unable to install and build all of the dependencies for VSCode 1.39.2

### ISSUE THREAD

**Issue by LunaLovegoood** [microsoft/vscode#91073]
I tried to install and build all of the dependencies using `yarn` (following these instructions [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute)) for VSCode 1.39.2 (latest release) and received following error:
```
error D:\Projects\vscode\1.39.2\vscode\node_modules\nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\Projects\vscode\1.39.2\vscode\node_modules\nsfw
Output:
D:\Projects\vscode\1.39.2\vscode\node_modules\nsfw>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.19.0 | win32 | x64
gyp info find Python using Python version 2.7.17 found at "C:\Python27\python.exe"
gyp http GET https://atom.io/download/electron/v4.2.10/node-v4.2.10-headers.tar.gz
gyp http 200 https://atom.io/download/electron/v4.2.10/node-v4.2.10-headers.tar.gz
gyp http GET https://atom.io/download/electron/v4.2.10/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v4.2.10/win-x86/node.lib
gyp http GET https://atom.io/download/electron/v4.2.10/win-x64/node.lib
gyp http GET https://atom.io/download/electron/v4.2.10/win-arm64/node.lib
gyp http 200 https://atom.io/download/electron/v4.2.10/win-x86/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'C:\Users\yurii.khomiak\AppData\Local\node-gyp\Cache\4.2.10\ia32\node.lib'
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\vscode\1.39.2\vscode\node_modules\nsfw
```

I tried building following native packages and didn't encounter any problems at all:
- bson;
- bufferutil;
- kerberos;
- node-sass;
- sqlite3;
- phantomjs;
- utf-8-validate.

Configuration:

- OS Name:                   Microsoft Windows 10 Pro
- OS Version:                10.0.18362 N/A Build 18362
- node: v10.19.0
- git: version 2.25.0.windows.1
- yarn: 1.21.1
- python: Python 2.7.17
- Visual Studio: Visual Studio Professional 2017 15.9.20 ("Desktop Development with C++" with "VC++ 2015.3 v14.00 (v140) toolset for desktop" is installed)

Environment Variables:

- npm_config_arch: x64
- npm_config_target_arch: x64

npm config:

- arch = "x64"
- msvs_version = "2017"
- python = "python2.7"

NOTE: My profile path contains only english letters and '.' character.  
NOTE: `~/.node-gyp` folder is not present after running yarn.

I also tried running `yarn cache clean` command and then running `yarn` again but still encountered the same error.

**Comment by LunaLovegoood** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [yarn install error:Command: node-gyp rebuild (#86885)](https://www.github.com/microsoft/vscode/issues/86885)

I tried solutions in this issue but they haven't solved my problem.

**Comment by LunaLovegoood** [comment]
It seems that setting `npm_config_node_gyp` variable and also `npm config python` to absolute path to python executable solved the issue.
Closing it now.

**Comment by bhavyasf** [comment]
@LunaLovegoood how can we set npm_config_node_gyp variable ???

**Comment by LunaLovegoood** [comment]
@bhavyasf you need to create and set it to the path to `node-gyp.js` file.

For me it's:  
`%USERPROFILE%\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js`
