### ISSUE TITLE
LanguageMode - Shell Script: Syntax highlighting bugged

### ISSUE THREAD

**Issue by TriMoon** [microsoft/vscode#91079]
From the About popup:
- Version: 1.42.1
- Commit: c47d83b293181d9be64f27ff093689e8e7aed054
- Date: 2020-02-11T14:50:36.977Z
- Electron: 6.1.6
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Linux x64 5.3.0-40-generic

Steps to Reproduce:
```bash
# Set logfile
# shellcheck disable=SC2034
logfile="$logDir/${0##*/}.log"
```
Is being rendered like:
![Screenshot20200220_153627 VSC Shell Script Highlight bug](https://user-images.githubusercontent.com/1723378/74934291-ef4bbd80-53f6-11ea-8209-4648d18830a8.png)
There are more highlighting problems but this is the one that caught my attention at moment...

Does this issue occur when all extensions are disabled?: **No idea, did not try**

**Comment by alexr00** [comment]
Looks like it's one of the extension you have installed:
![image](https://user-images.githubusercontent.com/38270282/74954004-b44f8700-5402-11ea-8fc8-9eb30cb1a41e.png)

**Comment by TriMoon** [comment]
> @alexr00  Looks like it's one of the extension you have installed:

Hmm weird, okay i will investigate further in that case...

**Comment by TriMoon** [comment]
Ok first try seems to have found the cause.
I disabled `aaron-bond.better-comments` and seems the highlight bug is gone, will try to file there...
:+1:
