### ISSUE TITLE
[RFI] inputs; selection with user input as choice.

### ISSUE THREAD

**Issue by TriMoon** [microsoft/vscode#91076]
Using these definitions:
```json
"inputs": [
    {
        "type": "promptString",
        "id": "hostname",
        "description": "Name of the host.",
        "default": "www"
    },
    {
        "type": "pickString",
        "id": "hostnames",
        "description": "Select a predefined host.",
        "default": "ns",
        "options": [
            "ns",
            "www",
            "google.com"
        ]
    }
]
```
It would be nice if we somehow could use the `promptString` entry as an option for the selections of the `pickString` entry.
I tried adding `"${input:hostname}"` to the options of it but that did not work...

**Comment by chrmarti** [comment]
@isidorn Is this a feature request for QuickPick? Or maybe this is tasks?

**Comment by isidorn** [comment]
I have no clue, I am not a good inbox tracker :)

**Comment by alexr00** [comment]
We will not support this to prevent recursion in the inputs. We may support simple replacement someday: https://github.com/microsoft/vscode/issues/64358

**Comment by TriMoon** [comment]
@alexr00 Recursion would not be a problem if it was only allowed in `pickString` types that reference `promptString` types...
