### ISSUE TITLE
is it possible to use vscode itself as a vscode remote server?

### ISSUE THREAD

**Issue by ssddi456** [microsoft/vscode#91077]
i have multiple working laptop, which have installed vscode already and have different env setup, can i use vscode itself  as vscode remote server and connect to it, so i can work like on that machine?

**Comment by IllusionMH** [comment]
It seems that you are looking for something like [Self-hosted environment for VS Online](https://docs.microsoft.com/en-us/visualstudio/online/how-to/vscode#self-hosted)

**Comment by ssddi456** [comment]
thanks, i'll look into it

**Comment by ssddi456** [comment]
vs online need an azure account and to regist required a visa credit card which i dont have....
is there alternatives?
