### ISSUE TITLE
Copying files with double extension generates wrong file names

### ISSUE THREAD

**Issue by Ares9323** [microsoft/vscode#91071]
Everytime I copy a file with a double extension the editor creates a new file with a "wrong name":

If I copy a .blade.php file (or a .min.css, .map.js) what I get is:
"Example.blade.php" -> "Example.blade copy.php"

I'd like to set it to "Example copy.blade.php",

I'm not sure if this is a bug or a feature request but It's very important to me, it would be a great time-saver

**Comment by isidorn** [comment]
Fair feature request. In the meatnime you can try using 	`"explorer.incrementalNaming": "smart"` setting

**Comment by Ares9323** [comment]
I tired using @isidorn setting but it was not the best solution, then I found an extension to duplicate a file with a command with the option to rename it in real time, it's a decent solution for now but in my opinion this is a big lack in vscode explorer, I'm sorry you're not going to implement it.

Thank you for your time, I hope you'll consider this in future.
