### ISSUE TITLE
Problem with staging and committing changes

### ISSUE THREAD

**Issue by georges-dib** [microsoft/vscode#91072]
I went through the file and staged the changes that I wanted. When I clicked stage, nothing changed in the line highlight on the left, but in the changes panel, the file appeared in the staged section. I went and continued staging changes in the same file. Clicking on the staged file showed that there are no differences in the code at all.
I thought it was a UI issue, so I committed and pushed, and nothing was pushed in the commit.

VS code v: 1.42.1

**Comment by joaomoreno** [comment]
Can you reproduce? If so, can you show me the output of `Git: Show Git Output`?

**Comment by georges-dib** [comment]
Hi,
I cannot reproduce that exact scenario because when I closed the window and reopened it, it worked fine. However when I make some changes in my file, and I click on the diff, VS shows me my current changes, AND the changes of the previously merged commit (doesn't necessarily have to be mine). When I stage the file, it shows me the correct changes only without the previous changes.
It's a very weird behaviour but it has been going on for some time now, and when I close and reopen the window it works fine.

**Comment by joaomoreno** [comment]
Show me the output of `Git: Show Git Output`, once it comes back, thanks!

**Comment by georges-dib** [comment]
![Capture2](https://user-images.githubusercontent.com/11720762/75426374-3123b900-594d-11ea-8bd5-a71acd3d41e6.PNG)
The commit in the image is not mine. I dont know if this is what you want.

**Comment by georges-dib** [comment]
I got screenshots for my previous comment, the changes in the working tree are NOT ONLY mine (first image):
![Capture-working tree](https://user-images.githubusercontent.com/11720762/75426498-7516be00-594d-11ea-8eb4-bb4af206864f.PNG)
In the index after staging, they are the correct changes (2nd image):
![Capture-index](https://user-images.githubusercontent.com/11720762/75426516-81028000-594d-11ea-8f17-98371ec1ff1a.PNG)

**Comment by joaomoreno** [comment]
No, I want the contents of <kbd>F1</kbd>, `Git: Show Git Output`.

**Comment by georges-dib** [comment]
Hello,
sorry for the latency I was off for some time, maybe this is what you're looking for. Let me know if I can help you further :)

> git rev-list --left-right CoreDev...refs/remotes/origin/CoreDev
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Failed to watch ref 'c:\Users\Alain\Desktop\ui_v2\.git\refs\remotes\origin\CoreDev', is most likely packed.
Error: ENOENT: no such file or directory, watch 'c:\Users\Alain\Desktop\ui_v2\.git\refs\remotes\origin\CoreDev'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1270:11)
	at Object.t.watch (c:\Users\Alain\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:592073)
	at E.updateTransientWatchers (c:\Users\Alain\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:123277)
	at l.fire (c:\Users\Alain\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:561)
	at R.updateModelState (c:\Users\Alain\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:142135)
> git config --get commit.template
