### ISSUE TITLE
"Discard all changes" doesn't delete files

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#91080]
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: macOS Catalina (Darwin x64 19.3.0)

**Steps to Reproduce:**

1. Have some untracked files
2. Click "Discard all changes"
3. Confirm file deletion
4. See how files are _not_ deleted

Does this issue occur when all extensions are disabled?: **Yes**

![Screen Recording 2020-02-20 at 13 30 48 2020-02-20 13_49_12](https://user-images.githubusercontent.com/101152/74935062-e0114380-53e7-11ea-8a96-f2037a6efc00.gif)

---

I've also verified this in Insiders 1.43.0-insider (9c341b3d8f2f41277be6dd59e7f4e847e6b594ac, 2020-02-20T05:36:57.672Z)

**Comment by borekb** [comment]
The files are in a `.now` folder – can the **dot** be significant? I've tried another file in a non-dot folder and discarding it from the SCM panel successfully deleted the file.

**Comment by jahusa02** [comment]
Having the same problem on Windows (Ver. 1909).

Have many untracked files i want do discard but nothing happens

**Comment by joaomoreno** [comment]
@borekb Are you on git 2.25? Can you repro on an earlier git?

**Comment by vhemt** [comment]
having the same issue, `git 2.25.0`, `macos 10.15.3`

**Comment by borekb** [comment]
@joaomoreno It is indeed a regression with the Git 2.25.

Try Git 2.24:

```
$ brew unlink git
Unlinking /usr/local/Cellar/git/2.25.0_1... 205 symlinks removed

$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/aacb808c01ea353820313b2fdf240923e53c301c/Formula/git.rb
[...]

$ git --version
git version 2.24.1
```

At this point, VSCode behaves correctly. ✅

Let's go back to Git 2.25:

```
$ brew switch git 2.25.0_1
[...]

$ git --version
git version 2.25.0
```

The issue is now reproducible again. 🚫

**Comment by joaomoreno** [comment]
@borekb Git has since release 2.26, can you check?

**Comment by borekb** [comment]
@joaomoreno All's fine with 2.26.0 again 🎉.

Do you know if this was a Git bug? Discarding changes should be pretty stable by now I'd guess?!

**Comment by joaomoreno** [comment]
Thanks a lot for confirming! Yeah, this wasn't the first issue we bug with git 2.25... it was definitely buggy with regards to file paths...
