### ISSUE TITLE
Please keep collapsed/expanded state when staging a changed files folder

### ISSUE THREAD

**Issue by Friksel** [microsoft/vscode#91081]
[vs code 1.42.1]

When adding a collapsed folder with changed files in the source control panel to the 'staged changes' before commit, the folder is expanded in the 'staged changes' list. This is very inconvinient as we collapsed the changed-files-folder on purpose and want to keep that state during this transition.
This way we have to do extra clicks to collapse them again after the staging. Which is timeconsuming, confusing, unintuitive and not much fun to do everytime...

So please keep the collapsed/expanded state of folders with changed files in the Source Control panel during the transition to the 'staged changes' panel.

**Comment by Friksel** [comment]
The 'Experimental duplicate detection' here      /\     is obviously wrong; this is a different one.

**Comment by jeanp413** [comment]
I think this is related to #89145 and the PR #89313 which makes possible to remember the collapse state of the scm tree elements

**Comment by Friksel** [comment]
> I think this is related to #89145 and the PR #89313 which makes possible to remember the collapse state of the scm tree elements

It's definitely related, but not the same. In the thread you mention it's about having a setting for collapsed state, but that's not what I mean. What I mean is that when collapsing groups in the 'changes' panel, those items will open again when added to stage, while I would like them to remain their collapsed state during that transfer.

Being able to set a default for both is a nice to have, but I'd rather like to see the current state each group is in transfered with the transfer to the stage.

**Comment by Friksel** [comment]
@joaomoreno  Any hint on why this 'wont-fix' is added?
