### ISSUE TITLE
Automated install of CLI extension on azure VM via custom script extension

### ISSUE THREAD

**Issue by deltadan** [microsoft/vscode#91087]
I'm working on a project to help people use the azure CLI for doing azure administrations.  I've created a VM using the custom-script extension which to installs a bunch of tools (via chocolatey), including VSCODE and would like to auto-install this extension on provision. 

The issue I'm running into is the extension seems to install to the user path rather than to a common location.

I was using this:
#Install Visual Studio Code Extensions
& 'C:\Program Files\Microsoft VS Code\bin\code.cmd' --install-extension ms-vscode.azurecli

Do you have suggestions?

See this repo for the vm: https://github.com/Build5Nines/az-kung-fu-vm

I'm going to be releasing a large set of samples using the extension here: https://github.com/Build5Nines/az-kung-fu

**Comment by sandy081** [comment]
Extensions are installed in default extensions directory in user home. You can change it using `--extensions-dir` argument.
