### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1012808318** [Microsoft/vscode#9108]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.Cannot drag and drop open folder
2.Cannot open multiple folders at the same time

**Comment by f111fei** [comment]
duplicate https://github.com/Microsoft/vscode/issues/8726. This had been repaired in master.

**Comment by bpasero** [comment]
Yup.
