### ISSUE TITLE
Separate sync and auth functionalities

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#91089]
Currently [UserDataSync](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/userDataSync/browser/userDataSync.ts) is mixed up with auth and sync features. To avoid a kitchen sink, we shall separate these two.

**Comment by RMacfarlane** [comment]
@sandy081 Where do you expect to draw the line between these? Should the gear not update when you're not signed in?

IMO, since auth is a requisite for having sync, completely separating them doesn't make sense.

**Comment by sandy081** [comment]
In terms of code organisation they should be separate. Currently sync is taking care of auth management in core. Instead, I would suggest to move auth management as a separate folder and allow sync to use services or context defined there.
