### ISSUE TITLE
Search inside search result

### ISSUE THREAD

**Issue by bpGusar** [microsoft/vscode#91088]
I have component "ComponentOne" which have props "blaBla"
Me need to rename this props inside entire project
But I have props "blaBla" in another component "ComponentTwo"
Me need to find files which have "ComponentOne", next only in files which have "ComponentOne" rename props "blaBla" to "balabol"

**Comment by JacksonKearl** [comment]
To be clear, you'd like to replace the string `blaBla` with the string `balabol` in all files which contain the string `ComponentOne`?
