### ISSUE TITLE
Workspace find and replace all, sometimes replaces whole file contents

### ISSUE THREAD

**Issue by simplyandyg** [microsoft/vscode#91091]
Issue Type: <b>Bug</b>

Sometimes when using global find and replace all, VS Code will copy the entire contents of an unrelated file and paste it over the contents of another file.

Example: Find 'tree' - Replace with 'bush'
File A - contains ‘tree’
File B - contains ‘tree’

Replace All Performed

File A - now contains none of its original content and all contents of file B
File B - ‘tree’ correctly replaced with ‘bush’

I can’t seem to find a rhyme or reason to it, except that it seems to be happening more frequently when the search term is found in more than 4 or 5 files.

It also doesn’t seem to have a pattern in terms of what file contents is copied into another from what I can tell so far. At least in terms of where the files show up in the search list. I thought maybe it would be that the first file it was doing the replace in would always be the one having another file dumped into it, but that doesn’t seem to be the case.

Just to be clear, this does not happen all the time, but I can reproduce it fairly easily.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_3261212|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
path-intellisense|chr|1.4.2
vscode-new-file|dku|4.0.2
vscode-great-icons|emm|2.1.47
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
gc-excelviewer|Gra|2.1.33
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.2.5
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.129
rainbow-csv|mec|1.5.0
mssql|ms-|1.8.0
node-debug2|ms-|1.42.1
vsliveshare|ms-|1.0.1615
vscode-react-native|msj|0.14.1
color-highlight|nau|2.3.0
vetur|oct|0.23.0
code-settings-sync|Sha|3.4.3
html-preview-vscode|tht|0.2.5
sort-lines|Tyr|1.9.0
vscode-todo-highlight|way|1.0.4

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Is it possible to provide a sample repo that I can use to reproduce this?

**Comment by simplyandyg** [comment]
Unfortunately, I can't share any of the codebase I'm working with because of restrictions by the employer.

**Comment by sandy081** [comment]
I can understand, but I am not able to repro it. Is it possible it provide a sample that does not have your code ?
