### ISSUE TITLE
"Replace All" in "Search" tab is a no-op

### ISSUE THREAD

**Issue by martellaj** [microsoft/vscode#91099]
Version: 1.43.0-insider (user setup)
Commit: 9c341b3d8f2f41277be6dd59e7f4e847e6b594ac
Date: 2020-02-20T05:39:38.179Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Try to search and replace all

Does this issue occur when all extensions are disabled?: Yes

**Comment by martellaj** [comment]
I need to go through each result and click "Replace" on each file. Is that the intention?

**Comment by sandy081** [comment]
With above steps it works for me. 

Please provide exact steps and an example to repro
