### ISSUE TITLE
VS Code font "Times New Roman" applies only to .html .css and .js files

### ISSUE THREAD

**Issue by louis60** [microsoft/vscode#91092]
Whenever i try to change the font , .html .css and .js files won't change their font. 
I tried to install font switch extension but it doesn't work either.

Html font : 
![image](https://user-images.githubusercontent.com/56726690/74948366-849d8080-53fc-11ea-9a06-8e97ad57110c.png)

Php font : 
![image](https://user-images.githubusercontent.com/56726690/74948448-a1d24f00-53fc-11ea-9742-ba3e6e51b75a.png)

Settings.json
![image](https://user-images.githubusercontent.com/56726690/74948618-d80fce80-53fc-11ea-882e-6776c532e47b.png)

And yes, i already tried to : 
- Save settings.json
- Uninstall and Reinstall VS Code
- Restart my computer

None of them worked...

Thanks

**Comment by octref** [comment]
Setting the font to something else applies to all documents for me:

![image](https://user-images.githubusercontent.com/4033249/75296254-80e57180-57e1-11ea-870f-141361c36ee1.png)
