### ISSUE TITLE
git.ignoredrepositories on windows not working

### ISSUE THREAD

**Issue by theophane-girard** [microsoft/vscode#91093]
Hello,

- Version: 1.42.1 (user setup)
- OS: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. add folder to git ignored repo tried with upper and lower cases, 
![ignored](https://user-images.githubusercontent.com/11314829/74949141-9af80c00-53fd-11ea-8436-4fbdb1742aab.PNG)

which gives following json
![json env](https://user-images.githubusercontent.com/11314829/74949236-c4b13300-53fd-11ea-8d5a-142b74627617.PNG)

2. git still displays env file to commit
![env](https://user-images.githubusercontent.com/11314829/74947478-3471ee80-53fb-11ea-8c2a-1e209cd123cd.PNG)

Does this issue occur when all extensions are disabled?: Yes

tried to restart vs code/remove folder to workspace + re-add but nothing fixed it :'(

EDIT : This is Git output

```sh
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.21.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: c:\_my\_src\php\<PROJECT_NAME>
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse feature/9879
> git rev-parse --symbolic-full-name feature/9879@{u}
> git rev-list --left-right feature/9879...refs/remotes/origin/feature/9879
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse feature/9879
> git rev-parse --symbolic-full-name feature/9879@{u}
> git rev-list --left-right feature/9879...refs/remotes/origin/feature/9879
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git show :ngapp/src/environments/environment.ts
> git ls-files --stage -- C:\_my\_src\php\<PROJECT_NAME>\ngapp\src\environments\environment.ts
> git cat-file -s 20eebd8a2693169aeb12e7b101400212e2fd785a
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse feature/9879
> git rev-parse --symbolic-full-name feature/9879@{u}
> git rev-list --left-right feature/9879...refs/remotes/origin/feature/9879
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
```

Thank you for your help

**Comment by joaomoreno** [comment]
What does `Git: Show Git Output` show?

**Comment by theophane-girard** [comment]
I just edited my post with Git Output :)

**Comment by joaomoreno** [comment]
Does it work if you reload the window? Note that the setting only affects repository *discovery*. It won't remove any repositories that have already been detected.

**Comment by theophane-girard** [comment]
even after reload, my file is still in git changes :'( 

![image](https://user-images.githubusercontent.com/11314829/75434625-27e91b00-5952-11ea-9a4e-cd6b935e2997.png)

**Comment by joaomoreno** [comment]
You should add the root of the repository: `c:\_my\_src\php\<PROJECT_NAME>`.

You seem to be adding a sub folder: `c:\_my\_src\php\<PROJECT_NAME>\src\environments`

**Comment by theophane-girard** [comment]
By adding root repository, all changes are ignored, I just want to git to ignore my env files without using .gitignore.

You mean I can't ignore a sub folder this way ?

**Comment by joaomoreno** [comment]
> I just want to git to ignore my env files without using .gitignore.

This is currently not supported, since VS Code would ignore it, but command line git would not ignore it, which is pretty inconsistent.

Why not using gitignore?

**Comment by theophane-girard** [comment]
because in my team we have a kind of token in env.ts which has to be updated every day, So i don't want to revert it every time i have to push

and using gitignore will ignore the file update if a dev add a field in the env file

But nevermind, we can close this issue :) 

Thank you

**Comment by joaomoreno** [comment]
@theophane-girard This might be useful: http://gitready.com/intermediate/2009/02/18/temporarily-ignoring-files.html

**Comment by theophane-girard** [comment]
this works well ! Thank you :)
