### ISSUE TITLE
Right-click to make a menu and VSC Not Responding

### ISSUE THREAD

**Issue by whrool** [Microsoft/vscode#9109]
### I right-click to make a menu and keep it for a long time(no more than one minute). It will report VSC Not Responding. But the fact is reverse. Actually, it is responding.

- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.![image](https://cloud.githubusercontent.com/assets/7413974/16753229/b7c1cf26-481a-11e6-8be3-db3346daa9af.png)

2.
![image](https://cloud.githubusercontent.com/assets/7413974/16753243/d73de1c8-481a-11e6-86a6-97d72f2cd8e1.png)

**Comment by f111fei** [comment]
duplicate https://github.com/Microsoft/vscode/issues/6414

**Comment by bpasero** [comment]
YUP :D
