### ISSUE TITLE
Python pytest Test Discovery failed

### ISSUE THREAD

**Issue by SonOfDiablo** [microsoft/vscode#91098]
Hello,
I'm having an issue where Test Dicovery fails in VS Code.
It worked without issues yesterday.

I have tried to re-install the Python Extension and also update pytest.
The Discovery works just fine outside of VS Code as well.

From the Python Test Log:
```
python c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\testing_tools\run_adapter.py discover pytest -- --rootdir d:\Path\To\Project -s --cache-clear Tests
Test Discovery failed: 
Error: spawn C:\Users\USERNAME\AppData\Local\Programs\Python\Python38\python.exe ENOENT
```

- VSCode Version: 1.42.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363
(Copied from Help > About, since Help > Report Issue didn't work)

Steps to Reproduce:

1. Open a Python project
2. Run Test Discovery

Does this issue occur when all extensions are disabled?: 
This wouldn't really apply in this case as I need the Python extension enabled to run Test Discovery.

**Comment by IllusionMH** [comment]
/causedByExtension

You need to file this issue in extension repo https://github.com/microsoft/vscode-python/issues/
