### ISSUE TITLE
Task progress does not stop turning

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#911]
- git clone https://github.com/Microsoft/vscode-extension-samples.git 
- cd to the new folder
- `npm run install-all`
- `code .`
- in the debug viewlet, run 'Launch decorator sample'
- note that the task progress is rotating
- terminate the debug connection
- task progress is still turning

**Comment by dbaeumer** [comment]
Problem is the new 1.7 TS which has a different message for watching.

Duplicates #918

**Comment by dbaeumer** [comment]
@aeschli I played the steps from above and I can't reproduce this anymore (the spinner stops). Can you please let me know why you think that this is not fixed. You added verification-regression

**Comment by dbaeumer** [comment]
And Joh closed #918 as verified :-)

**Comment by dbaeumer** [comment]
The problem is local specific. Martin is running under Swiss locale and me under US. We changed the pattern to be locale independent.

**Comment by aeschli** [comment]
Now it works! Thanks!
