### ISSUE TITLE
Hard to select text in the debug console

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#91103]
If you try to select text in the debug console from the left edge it won't work, because of an overlapping margin:

![image](https://user-images.githubusercontent.com/641685/74967527-2b772200-53e7-11ea-865c-09f78452bab5.png)

**Comment by isidorn** [comment]
Thanks for feedback,
This is due to the fact that we are using tree as the underlying implementation fo the debug console.
I see this as being a pain however while we use the tree I do not see a way to fix this. Thus leaving this open and assigning to backlog.

**Comment by isidorn** [comment]
Will not fix, until we change the underlying debug console implementation -> not on the plan thus closing
