### ISSUE TITLE
CSS syntax highlighting never terminates in HTML document when using multiple nested @ rules

### ISSUE THREAD

**Issue by aahancoc** [microsoft/vscode#91107]
Issue Type: <b>Bug</b>

When using multiple nested @ rules in an inline <style> tag in an HTML document, the CSS syntax highlighting doesn't stop when the </style> tag is encountered.

Here's a minimal test document that exhibits the buggy behaviour. (Strangely, this seems to break in GitHub's syntax highlighter as well.)
```html
<style>
	@page {
		@bottom-center { }
		@bottom-right { font-weight: bold; }
	}
</style>

<div class="example">
	Some page div
	span {font-size: 14pt;}
</div>
```
![image](https://user-images.githubusercontent.com/14837209/74968607-0f748000-53e9-11ea-94fd-3a93d1a0c9e0.png)

The `span` rule in the `div` tag is hilighted as if it was in the `style` tag, and the `class` attribute on the `div` tag is not higlighted.

Removing the `font-weight` rule fixes the issue, as does removing `@bottom-center`. This also works fine, for some reason:

```html
<style>
	@page {
		@bottom-center { }
		@bottom-right { font-weight: bold;
		}
	}
</style>

<div class="example">
	Some page div
	span {font-size: 14pt;}
</div>
...
```

![image](https://user-images.githubusercontent.com/14837209/74968687-39c63d80-53e9-11ea-8570-9e3a2df643d7.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
@octref the problem is in https://github.com/octref/language-css and my usual system for grammar issues is to file them in the owning repo then close the vscode issue as upstream. Are you no longer maintaining that repo?

**Comment by octref** [comment]
You can open issues in atom/language-css...I'm not sure when I'll get around to fixing that.

**Comment by alexr00** [comment]
Moved to upstream repo: https://github.com/atom/language-css/issues/168
