### ISSUE TITLE
Explore animation for when sync makes changes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91101]
Since some feedback we've seen is there's no feedback for when a sync happens and a notification would be too heavy (https://github.com/microsoft/vscode/issues/86088), I think we should consider an icon that briefly shows over the gear menu. Note that this should not show for every sync, but only when a change is actually happening (first sign in or merge). What I'm envisioning is a rotating refresh icon that transforms into a tick over 2-3 seconds, we haven't done anything like that yet though.

cc @sandy081

**Comment by misolori** [comment]
Why don't we just re-use the sync icon we already use to show progress and animate that?

![image](https://user-images.githubusercontent.com/35271042/75083616-f6de9580-54ce-11ea-91a9-93b1a54a8b77.png)

**Comment by Tyriar** [comment]
@misolori we could, but that just communicates "something is happening" not "something was successful"? At the time we show this indicator we already know that syncing was successful.

**Comment by misolori** [comment]
So I imagine something like this:

![Kapture 2020-02-24 at 12 02 47](https://user-images.githubusercontent.com/35271042/75186879-b153df80-56fd-11ea-9d95-6243185ec1e8.gif)


Though I might add an alternate "check" icon with a circle as this check on this badge looks a little odd.

**Comment by bpasero** [comment]
> Note that this should not show for every sync, but only when a change is actually happening (first sign in or merge).

This is different from what the title suggests though? +1 for not showing this spinner when changes are sent out because this can happen everytime I focus the window.

**Comment by sandy081** [comment]
Agreed that showing spinner while syncing will be noisy as it happen always and takes the attention. 

I understand users need to know what activity is going on with sync but I want to question how often users want to know about this? Is it worth having a prominent indicator thats on the face even when something is imported or exported? Is not the current two step process is enough? 

![image](https://user-images.githubusercontent.com/10746682/75781799-278bbe00-5d5e-11ea-990a-8f6e702966ef.png)

**Comment by misolori** [comment]
Given this issue has been been open for ~1.5 years I don't think this is a real issue, closing.
