### ISSUE TITLE
incorrect translation

### ISSUE THREAD

**Issue by scu319hy** [Microsoft/vscode#9110]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. with simplified chinese language
2. GIT pannel: "此工作区尚未在 GIT 源控件之下" should be "此工作区未被 GIT 管理"
3. Debugger pannel: "调用堆栈" should be "调用栈"

**Comment by johnliu2016** [comment]
@lukaschal Please send to linguistic review and implement fix as appropriate

[emptyView.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fchs%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Fgit%2Fbrowser%2Fviews%2Fempty%2FemptyView.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";noGit" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[This workspace isn't yet under git source control.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[此工作区尚未在 GIT 源控件之下。]]></Val>
          </Tgt>
        </Str>

4 instances found for "调用堆栈"
/Localize/chs/vscode/src/vs/workbench/parts/debug/browser/debugViewer.nls.resx.lcl
/Localize/chs/vscode/src/vs/workbench/parts/debug/browser/debugViewlet.nls.resx.lcl
/Localize/chs/vscode/src/vs/workbench/parts/debug/browser/debugViews.nls.resx.lcl

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Please is it possible to answer on question from linguist ?

Placeholder {1} is explanatory text for process '{0}' OR an error message at the end of this string ?

**Comment by johnliu2016** [comment]
@lukaschal which string is referred to?

/Localize/chs/vscode/src/vs/workbench/parts/debug/browser/debugViewer.nls.resx.lcl
ResID:
stackFrameAriaLabel
threadAriaLabel

**Comment by lukaschal** [comment]
Referred to this string:

SRC: Attach to process: cannot enable debug mode for process '{0}' ({1}).
TGT: 没有调用堆栈，因为计划已在 JavaScript 外暂停。

**Comment by johnliu2016** [comment]
@lukaschal The 'TGT' seems outdated as 'call stack' no longer appears in 'SRC' @dbaeumer Can you explain the question - Placeholder {1} is explanatory text for process '{0}' OR an error message at the end of this string ?

**Comment by dbaeumer** [comment]
@isidorn can you please clarify.

**Comment by isidorn** [comment]
It is an error message at the end of the string.

Additional info if needed: this error message is coming from the node debug adapter [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L934)

**Comment by johnliu2016** [comment]
@lukaschal please proceed on the fix with the context info, Thanks @isidorn

**Comment by lukaschal** [comment]
New translation implemented.

File: out\node\nodeDebug.nls.resx
ID: ".resx", 0; "VSND2021"
SRC: Attach to process: cannot enable debug mode for process '{0}' ({1}).
TGT: 附加到进程: 无法对进程 "{0}" 启用调试模式 ({1})。
