### ISSUE TITLE
Go to File not working with search.exclude

### ISSUE THREAD

**Issue by pacifier007** [microsoft/vscode#91102]
Issue Type: <b>Bug</b>

I have a folder in my Workspace as follows:

project-core
project-core/blocks/name/options.php

I have been trying to exclude the all .php files from project-core/blocks but have been unsuccessful. I have tried numerous restarts and in User settings.json and Workspace settings.json. All that I have tried:

```
		"files.exclude": {
			"**/project-core/blocks/**/*.php": true
		},
		"search.exclude": {
			"**/project-core/blocks": true,
			"project-core/blocks": true,
			"project-core/blocks/**/*.php": true,
			"**/project-core/blocks/**/*.php": true,
			"**/project-core/blocks/*": true,
			"./project-core/blocks": true
		}
```

Every time I Cmd+P (Go to file) and type options.php, I get results from under project-core/blocks/ too. 

Note: This isn't listed in "recently opened". I have cleared that just in case too. But it's listed under **file results**. 

Edit: Have the same issue with search too, despite cog icon being enabled next to files to exclude.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 5|
|Memory (System)|32.00GB (10.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by pacifier007** [comment]
Sorry, I figured out the problem. Looks like folder name isn't supported, as it's a relative path, and I have to use "/blocks" instead. 

If I have two folders in my project:

project/blocks
project-core/blocks

And I only wish to exclude project-core/blocks, is there any way to do that?

**Comment by IllusionMH** [comment]
You can create create per-folder settings using `.vscode/settings.json` inside of `project-core` or picking this folder in Settings UI (dropdown after Workspace) and add `blocks/**/*.php` to exclude pattern.
However it will hide these files from explorer too.

**Comment by isidorn** [comment]
Seems like this has been answered. Thanks @IllusionMH 
Thus closing
