### ISSUE TITLE
Completion target shown in italics when `"editor.suggest.insertMode": "replace"`

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#91104]
![image](https://user-images.githubusercontent.com/641685/74967695-83158d80-53e7-11ea-9d1e-79e37c599847.png)

Can this be turned off? Or changed to be a selection-type highlight rather italics?

Also this behavior seems to happen even if the extension doesn't support replace.

**Comment by eamodio** [comment]
I don't see this same behavior with `json` (which works) but with `typescript` I see it and the replace doesn't work (#91105)

**Comment by jrieken** [comment]
Yeah, there is setting for this `"editor.suggest.insertHighlight": true`. I am open for suggestions but the idea is that the italics part shows unexpected insert behaviour. E.g you have configured replace behaviour but this insertion only support insert (and the other way around).

**Comment by eamodio** [comment]
So the italics is kind of an error case? Is it worth trying to show that? Because I'm not sure anyone will figure out the meaning without being told.

**Comment by jrieken** [comment]
Not really an error case but a kind of "you will likely be surprised". Tho, given that we now have the  (optional) suggest widget status bar we could remove this again. The status bar should be telling if something can be inserted or replaced only

<img width="407" alt="image" src="https://user-images.githubusercontent.com/1794099/75015145-3afa7780-5488-11ea-93ad-bb6c2df95d9b.png">

**Comment by jrieken** [comment]
Decided to remove this - users that need more guidance should use the `editor.suggest.statusBar.visible` setting

**Comment by IllusionMH** [comment]
@jrieken but how I can be sure what part will be replaced?

TS usually completes name, however other plugins might also go for next punctuation characters or more.

Instruction to use Shift in status bar suggest that it can be used, but doesn't help to determine what actually will be replaced.
