### ISSUE TITLE
"editor.suggest.insertMode": "replace" not working at start of work in TypeScript

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#91105]
Issue Type: <b>Bug</b>

Related #91104

VS Code version: Code - Insiders 1.43.0-insider (9c341b3d8f2f41277be6dd59e7f4e847e6b594ac, 2020-02-20T05:39:38.179Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Yes - there is a reasonable default but every language needs to implement this by themselves

**Comment by mjbvz** [comment]
@eamodio Please share repo steps and example code

**Comment by eamodio** [comment]
@mjbvz It happens when starting the auto-complete from a `.`, it seems to work if there is one or more characters

Fails:
![image](https://user-images.githubusercontent.com/641685/75014313-fc4aca00-5453-11ea-9234-da02776b22b7.png)

Works:
![image](https://user-images.githubusercontent.com/641685/75014352-0cfb4000-5454-11ea-95e8-4b9f98761d33.png)

**Comment by mjbvz** [comment]
**Repo**
```js
class Foo {
    bar = 1;
    bad = 1;

    foo() {
        this.bar
    }
}
```

1. Place cursor after `.` in `this.bar`
1. Trigger suggestions and accept a replacement for `bad`

**Expected**
`this.bad`

**Actual**
`this.badbar` (🐘)
