### ISSUE TITLE
VS Code opens multiple instances of VS COde when I try to open the application

### ISSUE THREAD

**Issue by tyyoder23** [microsoft/vscode#91112]
When I open VS Code it opens several instances maybe like 20-30. So, it ends up slowing down my computer by quite a bit. I have uninstalled and reinstalled it and the problem still persists. I'm using Windows 10 and all the other code editing platforms I've used run fine even VS 2019. So, I really don't know what the issue is and would love to have a bit of help figuring it out. Thanks!

**Comment by bpasero** [comment]
@tyyoder23 did this happen recently? are you using insiders? are these instances having dirty files in them?
