### ISSUE TITLE
Privacy Error when trying to download

### ISSUE THREAD

**Issue by tmel3000** [microsoft/vscode#91116]
Hi, clicking on the download links from the page https://code.visualstudio.com/Download results in a Privacy Error warning.
![image](https://user-images.githubusercontent.com/52987411/74984925-9b8ab400-548a-11ea-9661-5f16476a97e0.png)

**Comment by joaomoreno** [comment]
@octref A lot of the aka.ms and go.microsoft.com links were pointing to the *very* deprecated `vscode-update` domain... since a long time we use `update.code.visualstudio.com`. I've gone through all the links and updated them.
