### ISSUE TITLE
The window is no longer responding

### ISSUE THREAD

**Issue by hrnagesh** [microsoft/vscode#91118]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Launch Code

[Window Title]
Visual Studio Code

[Main Instruction]
The window is no longer responding

[Content]
You can reopen or close the window or keep waiting.

[Reopen] [Keep Waiting] [Close]

Does this issue occur when all extensions are disabled?: Yes/No
Not sure; how to disable extensions prior to launch

**Comment by deepak1556** [comment]
Are you on a citrix environment ? 

Which version of vscode is this ? Can you try with latest insiders https://code.visualstudio.com/insiders/

> Not sure; how to disable extensions prior to launch

You can launch with `--disable-extensions` from the command line.

Also if you still see the issue with latest insiders, try launching with `--verbose` flag and please attach the log here. Thanks!

**Comment by hrnagesh** [comment]
Hi Deepak
Yes, on Citrix.
I disabled all the extensions and launched code.exe from command prompt; 
still code.exe errors
[code_report_err.txt](https://github.com/microsoft/vscode/files/4238686/code_report_err.txt)

**Comment by deepak1556** [comment]
Thanks for the log, this is a known issue with citrix environments, please try the workaround mentioned https://github.com/microsoft/vscode/issues/84914#issuecomment-556033410 .

/duplicate https://github.com/microsoft/vscode/issues/84914

**Comment by hrnagesh** [comment]
Thanks @deepak1556 

link https://support.citrix.com/article/CTX265011 solved the issue.
