### ISSUE TITLE
Incorrect underline when moving text

### ISSUE THREAD

**Issue by danybeam** [microsoft/vscode#91111]
Issue Type: <b>Bug</b>

Working in markdown
before:
```
* [facebook](facebook.com)
  * Foo
* [google](google.com)

```
after:

```
* [facebook](facebook.com)
* [google](google.com)
  * Foo
```

after I make the change from "before" to "after", "Foo" gets underlined as if the text "google.com" was still there

maybe an extension from this https://github.com/microsoft/vscode/issues/48321

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

Edit: Marked example text as code so it doesn't render in markdown

**Comment by deepak1556** [comment]
Thanks for the report, I was able to repro but the cause is same as https://github.com/microsoft/vscode/issues/48321 . Lets track it there.

/duplicate https://github.com/microsoft/vscode/issues/48321
