### ISSUE TITLE
[json] "Format document" on a large JSON file adds extra bracket

### ISSUE THREAD

**Issue by billbliss** [microsoft/vscode#91125]
[appInfo.json.txt](https://github.com/microsoft/vscode/files/4234215/appInfo.json.txt)

Issue Type: <b>Bug</b>

Actual:
1. Opened ~large JSON file (4415 lines when formatted)
1. Last character is a ] (it's an array of objects)
1. Right click, choose "Format document"
1. An extra bracket - ] - is added at the end, syntax error detected

Expected:
1. No extra bracket added, no syntax error

(rename attached file to .json, just strip the .txt extension - GH doesn't allow me to paste JSON)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-markdown|doc|0.2.50
rest-client|hum|0.23.1
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.2
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.2
vscode-azurestorage|ms-|0.8.0
vscode-cosmosdb|ms-|0.12.1
vscode-docker|ms-|0.10.0
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.10
azurerm-vscode-tools|msa|0.8.4
LiveServer|rit|5.6.1
azure-iot-toolkit|vsc|2.16.0

</details>

**Comment by thesofakillers** [comment]
Has this fix been deployed? I am still getting this in
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
```
If I check for updates it says there are no updates available

**Comment by aeschli** [comment]
It's in 1.43 (latest insiders or out as stable next week)
