### ISSUE TITLE
The terminal shell CWD "/Users/jasonli/web/12\xe6\x9c\x88/learn-ts/ts-crawl" does not exist

### ISSUE THREAD

**Issue by Brolly0204** [microsoft/vscode#91128]
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

**Comment by gjsjohnmurray** [comment]
@Brolly0204 you previously commented on #86857 which looks very similar. Please review that issue, which was ultimately closed as "caused by extension".

**Comment by Tyriar** [comment]
Please share your settings and extension, how do you launch the terminal?

**Comment by Brolly0204** [comment]
> share your settings and extensio

How to share settings and extension information, thank you

**Comment by Brolly0204** [comment]
> Please share your settings and extension, how do you launch the terminal?

Split command line number error reported

**Comment by Brolly0204** [comment]
![image](https://user-images.githubusercontent.com/16096724/75138142-79ac5e00-5724-11ea-95c6-54daafc22794.png)

**Comment by gjsjohnmurray** [comment]
> 
> 
> > share your settings and extensio
> 
> How to share settings and extension information, thank you

From the Command Palette run `Preferences: Open Settings (JSON)`

Paste the contents here, but mask any confidential strings.

One way of getting a list of extensions is to use Report Issue from the Help menu to begin a new one. Preview it on GitHub. Copy the extensions info from the preview, then abandon the page without filing the new issue. Paste the info here.

**Comment by Brolly0204** [comment]
## 38 theme extensions excluded
ejs-language-support | Qas | 0.0.1
-- | -- | --
vsc-material-theme-italicize | Ser | 0.0.14
ejs-snippets | Tao | 0.1.0
terminal-tabs | Tyr | 0.2.0
vue-material | abh | 0.0.2
html-snippets | abu | 0.2.1
vscode-caniuse | aka | 0.5.3
vscode-javascript-snippet-pack | aka | 0.1.5
pug | ama | 1.0.1
vscode-color | ans | 0.4.5
eggjs | ati | 0.3.1
color-info | bie | 0.5.1
vscode-styled-jsx | bla | 1.5.0
vue-css-peek | Cha | 1.0.0
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
vscode-wxml | cod | 0.1.9
dart-code | Dar | 3.8.1
flutter | Dar | 3.8.1
vscode-markdownlint | Dav | 0.34.0
vscode-eslint | dba | 2.1.1
app-migrator | deb | 0.0.6
githistory | don | 0.5.3
python-extension-pack | don | 1.6.0
es7-react-js-snippets | dsz | 2.6.0
gitlens | eam | 10.2.1
EditorConfig | Edi | 0.14.4
vscode-npm-script | eg2 | 0.3.11
we-app-vscode | eme | 0.8.0
react-native-react-redux | EQu | 2.0.3
vsc-material-theme | Equ | 32.5.0
vsc-material-theme-icons | equ | 1.1.4
carbon-now-sh | eri | 1.2.0
prettier-vscode | esb | 3.20.0
markdown-table-formatter | fcr | 2.0.3
file-icons | fil | 1.0.22
node-version | fiv | 0.0.1
auto-close-tag | for | 0.5.6
auto-complete-tag | for | 0.1.0
auto-rename-tag | for | 0.1.1
code-runner | for | 0.9.16
terminal | for | 0.0.10
vscode-mysql | for | 0.4.0
next-js | fox | 0.0.2
vscode-yarn | gam | 1.7.0
vscode-flow-ide | gca | 1.2.0
vscode-nginx-conf-hint | han | 0.1.0
vue-snippets | hol | 0.1.11
beautify | Hoo | 1.5.0
vscode-power-mode | hoo | 2.2.0
vscode-favorites | how | 1.4.0
rest-client | hum | 0.23.1
path-autocomplete | ion | 1.13.3
search-node-modules | jas | 1.3.0
vscode-pigments | jas | 2.0.0
docthis | joe | 0.7.1
azure-functions-tools | joh | 0.3.3
intellij-idea-keybindings | k-- | 0.2.37
auto-comment-blocks | kev | 1.0.1
vscode-codemetrics | kis | 1.24.0
vscode-gutter-preview | kis | 0.25.0
node-module-intellisense | lei | 1.5.0
sftp | lix | 1.12.9
MagicPython | mag | 1.1.0
one-dark-pro-italic | mar | 4.4.5
vscode-fileheader | mik | 0.0.2
HTMLHint | mka | 0.6.0
prettify-json | moh | 0.0.3
vscode-autoprefixer | mrm | 3.0.0
vscode-pugbeautify | mrm | 1.0.2
vscode-scss | mrm | 0.9.0
vscode-azurefunctions | ms- | 0.20.2
vscode-docker | ms- | 0.10.0
mssql | ms- | 1.8.0
python | ms- | 2020.2.64397
azure-account | ms- | 0.8.8
vscode-typescript-tslint-plugin | ms- | 1.2.3
vsliveshare | ms- | 1.0.1653
debugger-for-chrome | msj | 4.12.6
vscode-react-native | msj | 0.14.1
vscode-paste-image | mus | 1.0.4
live-server-preview | neg | 0.1.4
vscode-for-node-js-development-pack | nod | 2.0.1
vscode-extension-auto-import | Nuc | 1.4.3
prettier-standard-vscode | num | 0.6.0
vetur | oct | 0.23.0
code-rhythm | onv | 1.0.6
material-icon-theme | PKi | 3.9.3
vscode-css-peek | pra | 3.0.2
minapp-vscode | qiu | 2.2.2
typescript-hero | rbb | 3.0.0
java | red | 0.57.0
prettier-now | rem | 1.4.9
LiveServer | rit | 5.6.1
code-settings-sync | Sha | 3.4.3
vscode-nginx | sha | 0.6.0
markdown-preview-enhanced | shd | 0.5.2
vscode-leetcode | she | 0.16.1
code-spell-checker | str | 1.8.0
sass-indented | syl | 1.7.5
language-stylus | sys | 1.11.0
react-beautify | tai | 0.3.0
open-in-browser | tec | 2.0.0
vscode-markdown-paste-image | tel | 0.12.3
stylus-supremacy | thi | 2.13.0
python | tht | 0.2.3
python-extended-snippets | tus | 0.0.1
codelf | unb | 11.7.0
vscodeintellicode | Vis | 1.2.5
vscode-java-debug | vsc | 0.25.0
vscode-java-dependency | vsc | 0.9.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.22.1
vscode-maven | vsc | 0.21.0
vscode-icons | vsc | 10.0.0
nodejs-extension-pack | wad | 0.1.9
quokka-vscode | Wal | 1.0.279
vscode-import-cost | wix | 2.12.0
JavaScriptSnippets | xab | 1.7.2
ReactSnippets | xab | 2.4.0
material-theme | zhu | 3.2.3

**Comment by Brolly0204** [comment]
## settings
```json
 "codemetrics.basics.ComplexityLevelExtremeDescription": "😱",
    "codemetrics.basics.ComplexityLevelHighDescription": "😳",
    "codemetrics.basics.ComplexityLevelLowDescription": "🤓",
    "codemetrics.basics.ComplexityLevelNormalDescription": "🤔",
    "codemetrics.basics.ComplexityTemplate": "Complexity is {0} {1}",
    "codemetrics.basics.CodeLensEnabled": false,
    "editor.fontSize": 16,
    "editor.tabSize": 2,
    "editor.wordWrap": "wordWrapColumn",

    "emmet.includeLanguages": {
        "vue-html": "html",
        "ejs": "html",
        "javascript": "javascriptreact",
        "wxml": "html",
        "typescript": "typescript"
    },
    "workbench.editor.enablePreview": false,
    "editor.multiCursorModifier": "ctrlCmd",
    // 控制终端的字号(以像素为单位)。
    "terminal.integrated.fontSize": 15,
    "workbench.iconTheme": "material-icon-theme",
    "liveServer.settings.donotShowInfoMsg": true,
    "files.associations": {
        "*.vue": "vue",
        "*.stylus": "stylus",
        "*.cjson": "jsonc",
        "*.wxss": "css",
        "*.wxs": "javascript",
        "*.mvue": "vue",
        "*.mina": "vue",
        "*.css": "source.css.jsx.styled"
    },
    "gitlens.advanced.messages": {
        "suppressResultsExplorerNotice": true,
        "suppressShowKeyBindingsNotice": true
    },
    "terminal.external.osxExec": "iTerm2.app",
    "prettier.singleQuote": true,
    "prettier.semi": false,
    "stylusSupremacy.insertColons": false, // 是否插入冒号
    "stylusSupremacy.insertSemicolons": false, // 是否插入分好
    "stylusSupremacy.insertBraces": false, // 是否插入大括号
    "stylusSupremacy.insertNewLineAroundImports": false, // import之后是否换行
    "vetur.format.defaultFormatter.html": "js-beautify-html",
    "minapp-vscode.disableAutoConfig": true,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true,
    "pasteImage.showFilePathConfirmInputBox": true,
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "emmet.triggerExpansionOnTab": true,
    "liveServer.settings.donotVerifyTags": true,
    "editor.formatOnSaveTimeout": 180,
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[markdown]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[css]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        {
            "language": "typescript",
            "autoFix": true
        },
         {
            "language": "typescriptreact",
            "autoFix": true
        }
    ],
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[scss]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.rendererType": "dom",
    "cSpell.enabledLanguageIds": [
        "asciidoc",
        "c",
        "cpp",
        "csharp",
        "css",
        "git-commit",
        "go",
        "handlebars",
        "html",
        "jade",
        "java",
        "javascript",
        "javascriptreact",
        "json",
        "jsonc",
        "latex",
        "less",
        "markdown",
        "php",
        "plaintext",
        "pug",
        "python",
        "restructuredtext",
        "rust",
        "scala",
        "scss",
        "text",
        "typescript",
        "typescriptreact",
        "yaml",
        "yml"
    ],
    "[typescriptreact]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[less]": {
        "editor.defaultFormatter": "remimarsal.prettier-now"
    },
    "[vue]": {
        "editor.defaultFormatter": "octref.vetur"
    },
    "cSpell.userWords": [
        "antd",
        "echarts",
        "fastclick",
        "styl",
        "wechat",
        "weixin"
    ],
    "leetcode.defaultLanguage": "javascript",
    "leetcode.endpoint": "leetcode-cn",
    "leetcode.workspaceFolder": "/Users/jasonli/study/fullstack/算法/算法训练营/leetcode",
    "leetcode.hint.commandShortcut": false,
    "leetcode.hint.configWebviewMarkdown": false,
    "leetcode.hint.commentDescription": false,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "[java]": {
        "editor.defaultFormatter": "georgewfraser.vscode-javac"
    },
    "powermode.enableShake": false,
    "python.jediEnabled": false,
    "javascript.implicitProjectConfig.experimentalDecorators": true,
    "[wxml]": {
        "editor.defaultFormatter": "qiu8310.minapp-vscode"
    },
    "[stylus]": {
        "editor.defaultFormatter": "thisismanta.stylus-supremacy"
    },
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "material-icon-theme.activeIconPack": "vue",
    "typescript.preferences.quoteStyle": "single",
    "editor.formatOnSave": true,
    "eslint.alwaysShowStatus": true,
    "terminal.integrated.fontFamily": "Consolas",
    "editor.fontFamily": "Dark Mono, Menlo, Monaco, 'Courier New', Consolas",
    "workbench.colorTheme": "Braver's Solarized Dark (themed workbench)",
    "eslint.enable": false,
    "typescript.updateImportsOnFileMove.enabled": "always",
```
