### ISSUE TITLE
Multi-Window support.

### ISSUE THREAD

**Issue by ryantheleach** [microsoft/vscode#91122]
This is a clear duplicate of https://github.com/microsoft/vscode/issues/10121#issuecomment-345770248 .

It's your most voted for feature, on GitHub.

I realize this won't actualize overnight, and there is significant blockers.

Can that thread be updated to contain a clear roadmap of what specifically is blocking it, and what related dependent tickets to watch for progress? Even if no progress is currently being made on it, I'd just like to see the progress tick down on dependent tickets.

**Comment by ryantheleach** [comment]
@isidorn I realize there is significant work maintaining issues, (I've done it extensively on a popular project) But I really do hope that you read the last half of what I wrote, and will consider updating the locked issue.

**Comment by isidorn** [comment]
fyi @bpasero for updating the locked issue

**Comment by bpasero** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/87491
