### ISSUE TITLE
All text is blurry on screen

### ISSUE THREAD

**Issue by chriswinslow** [microsoft/vscode#91120]
- VSCode Version: 1.42.1
- OS Version: Windows 10.0.18363

Steps to Reproduce:

1. Opening Visual studio code 1 in 4 times I get a strange blurry effect on the text. Image dabbing some water on some written text in ink on paper, that is the same effect I get on my screen. This has been happening for about a year but I've not had enough of it and I'm now reporting it. See the attached image for an example. The only way to get rid of it is to restart windows. The blurry text does not happen for the first couple of seconds while VSC is loading up as you can see from the last screenshot when all the themes are loaded up that is when the fault happens and it happens with any theme even the built-in ones,
2.
![Untitled](https://user-images.githubusercontent.com/46504252/74994576-56449300-5446-11ea-919d-396e2f4f8553.jpg)
![Untitled02](https://user-images.githubusercontent.com/46504252/74994781-e1258d80-5446-11ea-8d1e-b34510bd4cb1.jpg)
![Untitled03](https://user-images.githubusercontent.com/46504252/74995221-2a2a1180-5448-11ea-8a09-3d282a0cc12b.jpg)
![Untitled04](https://user-images.githubusercontent.com/46504252/74995441-d66bf800-5448-11ea-8008-02d6f77a022a.jpg)

Does this issue occur when all extensions are disabled?: No

**Comment by deepak1556** [comment]
Does this happen on latest insiders https://code.visualstudio.com/insiders/ ?

Have you tried changing the font family and did the issue still persist ?

What is your graphics card ? Can you try running with `--disable-gpu` from command line.

**Comment by chriswinslow** [comment]
Ok, I've disabled installed extensions one-by-one and when I disabled an extension called Material Icon Theme the screen returned to normal and when I enabled the extension it went blurry again. SO I suppose this issue can be closed and I will raise it with the makers of the extension. Thanks.

**Comment by chriswinslow** [comment]
Ok, I've disabled installed extensions one-by-one and when I disabled an extension called Material Icon Theme the screen returned to normal and when I enabled the extension it went blurry again. SO I suppose this issue can be closed and I will raise it with the makers of the extension. Thanks.
