### ISSUE TITLE
Explore replacing notification count with alternate icon

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91130]
Currently when you have multiple notifications you see a notification count like:

![image](https://user-images.githubusercontent.com/35271042/75007233-54b8a200-5429-11ea-9674-963f8a2f5a55.png)

It would be interesting to explore reducing the shift of showing the number count with an alternate icon like so:

![image](https://user-images.githubusercontent.com/35271042/75007277-7580f780-5429-11ea-8e6e-cc51e053835a.png)

**Comment by bpasero** [comment]
**Verification:**
* install a tool such as https://marketplace.visualstudio.com/items?itemName=svipas.notification-tester
* bring up notifications
* hit ESC
* you should see a DOT over the bell until you open notification center once
