### ISSUE TITLE
The terminal process terminated with exit code: 4294967295

### ISSUE THREAD

**Issue by karuncs** [microsoft/vscode#91136]
Issue Type: <b>Bug</b>

The terminal process terminated with exit code: 4294967295

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
