### ISSUE TITLE
Sidebar: Option to Hide "Open editor" if folder is open

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#91138]
**My idea:**
1. If the project folder is open and there are no open files outside the project:
![obraz](https://user-images.githubusercontent.com/30685349/75026486-591ea280-549d-11ea-8a28-b1c296fd32ad.png)

2. If there is no open folder but any files are open:
![obraz](https://user-images.githubusercontent.com/30685349/75026520-689deb80-549d-11ea-80b1-152509f86b3b.png)

**Comment by isidorn** [comment]
You can right click on the Open Editrs section and just hide it. We try not to automatically hide things in the layout as it might confuse users.
However leaving this open as a feature request.
