### ISSUE TITLE
Duplicate copy of file created when renaming the containing folder and changes to file not saved.

### ISSUE THREAD

**Issue by BondiGeek** [Microsoft/vscode#9113]
- VSCode Version: 1.3.0
- OS Version: Windows 10 Build 14385

Steps to Reproduce:

1. Create a folder (A) and place a couple of files in the folder with VSCode
2. Save any changes
3. Make an edit to one of the files in folder (A)
4. Do not save the changes to the file
5. Now rename folder A to folder B
6. You will not be prompted to save any changes or prevented from renaming the folder
7. If all goes as expected you will end folder B containing all the files from A *AND* folder A will still exist with the edited version of the file and no others.

Certainly not a showstopper but it caused me concern at first when I went to edit the edited file in the new folder B and my edits had apparently been lost.

Would be great if it prompted you to save changes and proceed OR cancel the rename until changes had been saved.

Cheers,
James

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.
