### ISSUE TITLE
VSCode doesn't show certain characters inside the code, but stores it inside the files.

### ISSUE THREAD

**Issue by baermathias** [microsoft/vscode#91137]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04

VSCode doesn't show certain characters inside the code, but saves it anyway. So other entities like e.g. a browser try to process it and then fail. 
This character e.g. is shown at jsfiddle as a bullet point or something similar:  
![Screenshot from 2020-02-21 11-12-51](https://user-images.githubusercontent.com/45003352/75026106-aa7a6200-549c-11ea-93b3-b22563154582.png)
In VSCode it looks like this
 `{{ value }}`

Steps to Reproduce:

1. Paste the wollowing character between the code and try to process it with the browser or some other tool:
` ‌ `
>  ‌

**Comment by alexdima** [comment]
@baermathias Can you please give the Unicode code point value or a file with the problematic character saved as UTF8?

**Comment by IllusionMH** [comment]
@alexdima can be zero-width space.
Copied text from https://en.wikipedia.org/wiki/Zero-width_space and I can see that I need to press arrow 2 timed between words.

**Comment by baermathias** [comment]
u200C

**Comment by alexdima** [comment]
Please use https://marketplace.visualstudio.com/items?itemName=wengerk.highlight-bad-chars#overview or another extension that highlights such atypical for programming characters.
