### ISSUE TITLE
Terminal Scroll bar appears in the middle

### ISSUE THREAD

**Issue by goxr3plus** [microsoft/vscode#91135]
Gif attached below : 

![2020-02-21_11-37-58](https://user-images.githubusercontent.com/20374208/75022395-b109d900-549e-11ea-992b-fc8576227621.gif)

Also sometimes when i opper two terminals side by side and i close the second , the first one doesn't resize properly .

![image](https://user-images.githubusercontent.com/20374208/75022466-d0086b00-549e-11ea-8fee-63a90f89ff48.png)

Version: 1.43.0-insider (system setup)
Commit: e6a45f4242ebddb7aa9a229f85555e8a3bd987e2
Date: 2020-02-21T05:42:20.536Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by goxr3plus** [comment]
Version: 1.43.0-insider (system setup)
Commit: e6a45f4242ebddb7aa9a229f85555e8a3bd987e2
Date: 2020-02-21T05:42:20.536Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Does this also occur if you run from command line and disable GPU?

`code --disable-gpu`

**Comment by IllusionMH** [comment]
This might be related to the fact that after I hide/show bottom panel there is difference in width of `div.terminal.xterm`

Fresh terminal in bottom panel
![image](https://user-images.githubusercontent.com/1312662/75030179-3e9ff580-54ac-11ea-95d1-a19782c5988c.png)
Click hide panel or switch to any other tab in panel and show terminal again
![image](https://user-images.githubusercontent.com/1312662/75030583-149b0300-54ad-11ea-89c8-e1622b06346c.png)

Which might explain issue with wrong outline in #90568 (and issues that I had when sometimes input line had line breaks early)

It looks funnier immediately after I switch from `experimentalWebgl` renderer to `auto` and terminal is hot-reloaded.
![image](https://user-images.githubusercontent.com/1312662/75030918-d4885000-54ad-11ea-81f6-3c91bc050571.png)
_(after hot reload of renderer I also see that in this case I also see that `.split-view-view.visible` will change it width, but doesn't happen in case described above)_

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:42:20.536Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (11.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
I suspect a race where viewport doesn't update when resize is fired multiple times in quick succession.

**Comment by Tyriar** [comment]
@sbatten I think the workbench view refactor caused this and https://github.com/microsoft/vscode/issues/91119. Are there additional resize events being fired now when the view is hidden?

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/75056921-c83fcb00-548c-11ea-9f65-1298b3266c0a.png)

initial layout calls, after initial layout no more calls to layout are made with terminal hidden.

**Comment by IllusionMH** [comment]
Not sure if directly related to this one (most likely same as second case in my example with renderer).
If I change `editor.font` I'll get wrong dimensions for teriminal inside tab
![image](https://user-images.githubusercontent.com/1312662/75079604-f87d7d00-5511-11ea-8962-a90424867d2b.png)

**Comment by Tyriar** [comment]
Solid repro: https://github.com/microsoft/vscode/issues/91135

**Comment by Tyriar** [comment]
@sbatten please review https://github.com/microsoft/vscode/commit/622ddc0d6794450de81bdd4fd020dd219be1b926, also why does layoutBody take height first then width? This is backwards to the standard and results in things like this happening?

**Comment by sbatten** [comment]
not sure, @joaomoreno implemented it that way a long time ago.

**Comment by joaomoreno** [comment]
What standard? 😕 

Historically, split views only had one dimension, so it was `layout(size)`. Then, as panels appeared, they were forcibly vertical, so that became `layout(height)`. Then, it turns out we needed to pass in width as well, so then `layout(height, width)` was born.

We can easily change that to a `layout(dimension)`.

**Comment by Tyriar** [comment]
@joaomoreno by standard I mean industry standard that it's almost always (x, y), (width, height), (horizontal, vertical), etc.
