### ISSUE TITLE
Region Folding support for golang

### ISSUE THREAD

**Issue by micharaze** [microsoft/vscode#91140]
Other language like for example Python has the possibility to fold a region by adding the comment tags `#region` and `#endregion`. It seems like that vs code doesn't support that for golang yet. This would be helpful to have a better overview of the code.

**Comment by gjsjohnmurray** [comment]
It already seems to be there:

![image](https://user-images.githubusercontent.com/6726799/75031535-64be9900-549e-11ea-92a6-d12d455c3a83.png)

This is from 1.43.0-insider

[Code pointer](https://github.com/microsoft/vscode/blob/68a1013668b6587ed5cc6489de16b0d22bbb3352/extensions/go/language-configuration.json#L31-L35)

**Comment by IllusionMH** [comment]
Should work for at least 2 stable releases:
![image](https://user-images.githubusercontent.com/1312662/75032125-7b6deb80-54b0-11ea-9b02-8b522df7836e.png)
![image](https://user-images.githubusercontent.com/1312662/75032245-c25be100-54b0-11ea-9c89-081cc6451f1d.png)

**Comment by isidorn** [comment]
@gjsjohnmurray @IllusionMH thanks a lot for help!
Seems to work. Thus closing

**Comment by micharaze** [comment]
Its not working on my version:
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
```

**Comment by micharaze** [comment]
I fixed this problem with adding following config:

`    "editor.foldingStrategy": "indentation", 
`

**Comment by IllusionMH** [comment]
In my case it was `auto`, but I don't have any Go extensions.

Is it possible that LS can erase fold regions based on comments?
