### ISSUE TITLE
TS: no longer seeing an error when not calling function in check

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91144]
I think a while ago we got nice errors when forgetting to call a function, e.g.:

![image](https://user-images.githubusercontent.com/900690/75033736-d81ad780-54ab-11ea-93b0-b74178bc5f50.png)

(from https://github.com/microsoft/vscode/blob/7d10b5a8faf9520c03510cebcdf37e32dab1c6e4/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L407)

Is actually not using the function call properly and is always true. 

Did we loose this feature?

**Comment by IllusionMH** [comment]
Doesn't look like it should work with expressions [Playground](https://www.typescriptlang.org/play/index.html?ssl=9&ssc=35&pln=9&pc=43#code/GYVwdgxgLglg9mABACwIYGcAKAnOBzbAU3XQAoBKRAb0QF8BYAKCaZmEVLS1wOPUqpNEwxBATo4AG0IA6SflIByACoBlRAFFsubIvJMGzRmw4BCU1xz4iJAUJFiwE6XIWKA6nEIBrdIgyIhAAeAA6E0IQAJnoGLEYmpBYYVry21PbCjs6y8nhKAPKFmKoxjIZMQA)

**Comment by bpasero** [comment]
Thanks for looking this up.

**Comment by mjbvz** [comment]
Closing as upstream

Thanks @IllusionMH!
