### ISSUE TITLE
Open files and jump directly to line number given on command line

### ISSUE THREAD

**Issue by coveritytest** [microsoft/vscode#91145]
In Sublime Text, there is this very neat feature, that you can open a file and jump directly to line number given on command line. Just like this:

Linux:

code /home/user/file.c:72

Windows:

Code.exe C:\Users\user\file.c:72

This would be a very useful feature for vscode, too.

**Comment by bpasero** [comment]
We support this with the --goto CLI option.

**Comment by ArturoDent** [comment]
See https://code.visualstudio.com/docs/editor/command-line#_core-cli-options
