### ISSUE TITLE
Deadlock in VC debug config parsing logic (attach to gdbserver)

### ISSUE THREAD

**Issue by Ts-OV** [microsoft/vscode#91147]
- VSCode Version: 1.42.1
- OS Version: Ubuntu Linux 18.04.4 LTS x64, 4.15.0-88-generic

Other VS Code ver. details: 
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

**Deadlock in VC debug config parsing logic (attach to gdbserver)**

Steps to Reproduce:

1. Add debug configuration template:
```
        {
            "name": "(gdb) Attach to QEMU gdbserver",
            "type": "cppdbg",
            "request": "attach",
            "MIMode": "gdb",
            "miDebuggerPath": "/path/to/gdb/../../bin/mips-mti-linux-gnu-gdb",
            "miDebuggerServerAddress": "localhost: 1234",
            "program": "${workspaceFolder}/path/to/binary",
            // "processId": "${command:none}",
            // "processId": "${command:pickProcess}",
            // "processId": "54234",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
```

2. Attempt to start debugging (when **no "processId" is provided**)
3. ### Cannot start debugging. 
    Complains: `"unable to parse process id"` 
    [screenshot](https://i.stack.imgur.com/rnzCH.png)

4. If **"processId" is given** by some option of the "processId" unlocked in the config (_and some process from the list selected, if requested according to the corresponding option_), it cannot start debug session with:
   Complain: `"'processId' cannot be used with miDebuggerServerAddress"`
   [screenshot](https://i.stack.imgur.com/dxbG3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Please file against the C++ extension. Thank you 
https://github.com/microsoft/vscode-cpptools

**Comment by Ts-OV** [comment]
I used the _bug-report_ link exactly from there (https://code.visualstudio.com/docs/cpp/launch-json-reference) ;)
