### ISSUE TITLE
Debugging cpp program throws exception on combase.dll

### ISSUE THREAD

**Issue by paedocypris** [microsoft/vscode#91146]
Issue Type: <b>Bug</b>

I have a project which I'm using CMake and Visual Studio 2017 to build successfully from vscode (Visual Studio 15 2017 Win64 host=x64). However, I'm unable to debug it from vscode due to an Access violation in a combase.dll.

I am able to debug the same executable generated from the build with VS 2017 by calling devenv path/program.exe from a terminal.

Here is the debug console output:

`Loaded 'D:\Work\3.PD\2.program\1.cpp\bin\Debug\main.exe'. Symbols loaded.
Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\tmumh\20019\AddOn\7.0.0.1169\TmUmEvt64.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\psapi.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFDF596448E (combase.dll) in MdaMeX.exe: 0xC0000005: Access violation reading location 0x0000000000000008.`

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz (32 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|255.70GB (244.76GB free)|
|Process Argv|D:\Work\3.PD\2.program\1.cpp|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
extended-cursormove|Bil|0.0.2
latex-workshop|Jam|8.7.2
linter-gfortran|krv|2.1.1
python|ms-|2020.2.63990
cpptools|ms-|0.26.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.5

</details>

**Comment by isidorn** [comment]
Please file against the C++ extension. Thank you 
https://github.com/microsoft/vscode-cpptools
