### ISSUE TITLE
Test save and open dialog title proposed API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91153]
Refs: https://github.com/microsoft/vscode/issues/82871

- [ ] macOS @rebornix
- [x] linux @mjbvz
- [x] windows @connor4312

Complexity: 3

The `OpenDialogOptions` and `SaveDialogOptions` both include a `title` property in the proposed API. Write an extension that shows an open and a save dialog with the title option set.
Verify:
- That the title specified is used when the dialog is shown. Compare the behavior to that of File -> Open Workspace and File -> Save Workspace as.. If the title of those dialogs is set to mention "workspace", then this proposed API should also set the title on the OS that you're using.
- That the API makes sense (the name just comes from electron)
- That the simple file dialog respects this title. This can be tested by enabling the simple file dialog in settings or by connecting to a remote.

**Comment by GustavoASC** [comment]
Maybe it's a good idea to test on different operating systems.
According to PR #90493:

> Note: on this version of Ubuntu the Save Dialog title is not shown, but it's an OS-related behaviour.
> Every save dialog of VSCode running on Ubuntu 19.10 ignores the specified title as can be seen on 'File -> Save Workspace As...' (On Windows it shows 'Save Workspace' but on Ubuntu no title is shown).

Thanks in advance!
If you need anything I am on hand to help :smile:

**Comment by alexr00** [comment]
Updated. Good feedback, thank you @GustavoASC !

**Comment by rebornix** [comment]
@alexr00 what's the expected behavior on macOS which is using the native dialog? I didn't see title bar on the dialogs.

![image](https://user-images.githubusercontent.com/876920/75276124-6b108600-57ba-11ea-88f4-957df69679dc.png)

**Comment by alexr00** [comment]
@rebornix I'm not sure. What happens when you run File -> Open Workspace and File -> Save Workspace as.. If the title of those dialogs is set to mention "workspace", then this proposed API should also set the title on the OS that you're using.

**Comment by GustavoASC** [comment]
@alexr00 @rebornix 

>  I'm not sure. What happens when you run File -> Open Workspace and File -> Save Workspace as.. If the title of those dialogs is set to mention "workspace", then this proposed API should also set the title on the OS that you're using.

If title is never show on any dialog while running on macOS, it's a behavior of the operating system. Thus, we could add a description above _title_ parameter on _OpenDialogOptions_ and _SaveDialogOptions_ pointing this out.

**Comment by rebornix** [comment]
I think that's the system behavior, we'd better document it.

**Comment by GustavoASC** [comment]
@rebornix I'll make a pull request improving the _title_ documentation on vscode.proposed.d.ts :+1:

**Comment by rebornix** [comment]
@GustavoASC thanks!
