### ISSUE TITLE
Clean reload

### ISSUE THREAD

**Issue by al-davis** [microsoft/vscode#91158]
A recent oddball problem leaves me without a properly functioning VScode system.  Is there a method to uninstall and reinstall to get a clean reload ?

I have tried the normal uninstall (which warns that extensions and setting are NOT uninstalled), download and reinstall without success.  That sequence resulted in the new VScode opening with the same project and workspace in the exact same condition and positions as before.  I retried the same including removing all the folders I could ID as being related but without success.  Attempts at success posting on this site haven't ended with a working system either.

 Is there a method to uninstall and reinstall to get a clean reload ?

**Comment by isidorn** [comment]
Yeah just uninstall vscode and reinstall it.

**Comment by al-davis** [comment]
Seriously ?  Why claim this is a help site ?
