### ISSUE TITLE
Create additional syntaxes/grammars for catering for the various SQL variants 

### ISSUE THREAD

**Issue by gontadu** [Microsoft/vscode#9115]
Getting into SQL dev now, I see that although largely the same, there are some important syntax differences between the popular SQL implementations in Oracle, PostgreSQL, MySQL and T-SQL (Microsoft SQL Server).

This issue is evident here e.g. https://github.com/Microsoft/vscode/issues/5223

I propose that additional syntax files are added to the sql extension. Other projects are also facing the same issue e.g. https://github.com/atom/language-sql/issues/40 & https://github.com/textmate/sql.tmbundle

**Comment by gontadu** [comment]
I am happy to do the pull request myself - but I am unaware of all the architectural changes required to recognise and add the new syntax file. Happy to get cracking with a guide of some sort.

**Comment by mjbvz** [comment]
Extensions are able to provide additional grammars. Please look in the marketplace to see if one already exists for what you are after, or look into creating your own
