### ISSUE TITLE
[Feature Request] In sidebar tree view, visually distinguish where folder contents end

### ISSUE THREAD

**Issue by revelt** [microsoft/vscode#91151]
Currently, the sidebar folder tree is quite cognitively taxing — it's hard to visually detect where contents of a folder ends, especially when many folders are nested.

In large projects, only indentation is not enough.

What if we added a small gap or any other sort of visual marker to distinguish where the folder contents end?

For example:

<img width="101" alt="sidebar_under_tree" src="https://user-images.githubusercontent.com/8344688/75039217-17e3be00-54b0-11ea-96ff-ea139cafe9db.png">

Notice the line and gap under expanded folder's contents.

What do you think?

**Comment by Gama11** [comment]
Have you tried this setting? Personally I use a value of 20.

```json
"workbench.tree.indent": 20
```

**Comment by revelt** [comment]
@Gama11 that's awesome! Thank you, I did try, it did work. My concern is that that's horizontal indentation, my concern is that if the folders are deeply nested, in bigger projects, horizontal indentation alone will push folders too much to the right. This issue is for **vertical indentation**, idea being, this would allow to keep horizontal indentation (`workbench.tree.indent`) tighter and see boundaries by vertical mark or indentation.

Having said that, if VSCode maintainers deem this an unneeded feature, feel free to close. It's mostly relevant for very large projects anyway.
