### ISSUE TITLE
Test: Notifications changes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91163]
Refs: https://github.com/microsoft/vscode/issues/91130, https://github.com/microsoft/vscode/issues/90274

- [x] anyOS @eamodio
- [x] anyOS @isidorn

Complexity: 3

* Verify that we no longer show the number of unread notifications but a different icon instead
    * install a tool such as https://marketplace.visualstudio.com/items?itemName=svipas.notification-tester
    * bring up notifications
    * hit ESC
    * you should see a DOT over the bell until you open notification center once
    * the tooltip (hover) still shows the number of "unread" notifications
* Verify that notifications with progress behave according to these rules (you can use below code [1] to bring up a notification programmatically)
    * notifications with progress can no longer be removed as long as they are running and once done they remove automatically
    * as long as the progress notification is neither showing as toast (e.g. by using `ESC` to hide all toasts) and the notification center is not visible (by clicking on the bell icon for example), a spinning indicator next to the bell gives a hint that the operation is still running

![Kapture 2020-02-21 at 15 56 48](https://user-images.githubusercontent.com/900690/75044996-cf81cb80-54c2-11ea-892e-ecaa006ae8dd.gif)

[1]
```ts
class ProgressAction extends Action {

	static readonly ID = 'workbench.action.ProgressAction';
	static readonly LABEL = nls.localize('ProgressAction', "ProgressAction");

	constructor(
		id: string,
		label: string,
		@IProgressService private readonly progressService: IProgressService
	) {
		super(id, label);
	}

	run(): Promise<void> {
		this.progressService.withProgress({
			location: ProgressLocation.Notification,
			title: `Some long running operation`,
			cancellable: true
		}, progress => {
			return timeout(20000);
		});

		return Promise.resolve();
	}
}
```

**Comment by eamodio** [comment]
LGTM!
