### ISSUE TITLE
[themes] auto detect color scheme not working on Linux

### ISSUE THREAD

**Issue by gombosg** [microsoft/vscode#91169]
- VSCode Version: latest stable & also 1.43.0-insider
- OS Version: Fedora 31, GNOME 3.34.4

Steps to Reproduce:

1. Launch VScode, set `window.autoDetectColorScheme` to `true`
2. Set dark/light Adwaita theme in GNOME
3. Firefox 73 & Chromium 79 does react, VS Code doesn't.

Does this issue occur when all extensions are disabled?: Yes/No

VS Code insiders, fresh profile.
```
Version: 1.43.0-insider
Commit: e6a45f4242ebddb7aa9a229f85555e8a3bd987e2
Date: 2020-02-21T05:40:52.685Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.20-200.fc31.x86_64
```

I did some debugging, [this](https://github.com/microsoft/vscode/blob/7d715621403d24d8359d79469ef8da7c75352115/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L392) is where the magic happens.

Unfortunately, `window.matchMedia(`(prefers-color-scheme: light)`).matches === true` and `window.matchMedia(`(prefers-color-scheme: dark)`).matches === false` regardless of my system theme.

This is maybe a Chromium bug since the same wrong values are returned in Chromium but the right values are returned in Firefox. On the other hand, Chromium does auto-switch its color theme.

Also there's a [`nativeTheme`](https://www.electronjs.org/docs/api/native-theme) Electron API. What does that have to do with this?

**Comment by usernamehw** [comment]
Release notes specifically says that it only works in `Windows` / `Mac` 

https://code.visualstudio.com/updates/v1_42#_auto-switch-theme-based-on-os-color-scheme

**Comment by gombosg** [comment]
I'm trying to figure out why since `prefers-color-scheme` is supposed to be OS and browser independent.
It's probably [this](https://bugs.chromium.org/p/chromium/issues/detail?id=889087#c66) and especially [this](https://bugs.chromium.org/p/chromium/issues/detail?id=998903) bug.
Apparently someone tried to fix it but it didn't work out as expected.

**Comment by gombosg** [comment]
I tested the [`nativeTheme` API](https://www.electronjs.org/docs/api/native-theme#nativethemeshouldusedarkcolors-readonly) and it also returns the wrong (always light theme) value on Linux. :crying_cat_face:

**Comment by aeschli** [comment]
Thanks for digging up the links. We will have to wait for Chromium to have the feature.
In the meantime I can disable the feature for Linux or add a remark to the description, if that's any help.

**Comment by Siilwyn** [comment]
Tested with VSCode 1.50.1 on (Ubuntu) GNOME 3.26.3, and currently it works when launching the editor but will not change when the theme is switched while the editor is open.

**Comment by ryanerwin** [comment]
I'm getting the same behaviour as @Siilwyn 

When I close VSCode, I can get the theme to toggle between light and dark, but since VSCode is basically always open this doesn't really help.

Any suggestions on how to get this to work without closing VScode though? Even a command line workaround would be fine...

**Comment by aeschli** [comment]
As mentioned, we're waiting for Electron/Chromium support to detect os color scheme changes. There's no workaround yet.

**Comment by aeschli** [comment]
Yes, I can also confirm that this works now with Ubuntu 21.10

**Comment by silviuvulcan** [comment]
Doesn't work for me on Fedora 35 and KDE switching between Breeze and Breeze Dark has no effect. Turning `window.autoDetectColorScheme` to `true` imediately switches to the Light theme.

**Comment by thefoxie** [comment]
@silviuvulcan not sure if there's such thing in KDE, but theme and color scheme are two different things. Theme is just a theme and color scheme should trigger changes accross the system if it's implemented (like in vscode or by default in gtk apps).

Found this switcher but not sure whether it will be helpful
https://github.com/baduhai/Koi

Works for me on Arch Linux with Gnome 41.3 and oss version that uses system electron.

**Comment by connor4312** [comment]
Verified on Ubuntu as well

**Comment by silviuvulcan** [comment]
KDE has (not sure since what version) a global Dark/Light switch that changes theme and color scheme together. Also switching plasma style between a dark, light or "follow color scheme" one has no effect.

Due to either KDE not reporting it or vscode not reading it switching any of the above between light and dark has no effect in vscode. I think it's safe to assume this is fixed only for Gnome not Plasma.

**Comment by aeschli** [comment]
VS Code relies on Electron here, so please file an issue about missing support for KDE Dark/Light at https://github.com/electron/electron/issues.
You can use https://github.com/aeschli/electron-theme-test to test the Electron `nativeTheme` API.

**Comment by firefoxic** [comment]
> I think it's safe to assume this is fixed only for Gnome not Plasma.

In Gnome 42, with the addition of the system light/dark theme switcher, this also broke.
