### ISSUE TITLE
Auto Save in menu conflicts with setting in preferences

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#91160]
I have **Auto Save** set to _onWindowChange_. Sometimes I accidentally click the **Auto Save** option in the File menu which turns it off. If I then click the menu option to turn it back on again it sets it to _afterDelay_. 

This can be confusing to say the least. When selecting the menu item it should either remember the previous setting, or prompt for which setting to use.

**Comment by ad8e** [comment]
#39749 is a dupe with other possible solutions.

**Comment by Gruntfuggly** [comment]
This was never a feature request - it's a bug, and a horrible user experience. The marked duplicate was a feature request and was closed.
