### ISSUE TITLE
lost code due to editing in debug mode

### ISSUE THREAD

**Issue by cpwang007** [microsoft/vscode#91162]
Issue Type: <b>Bug</b>

1. Start remote debug
2. work on a file and save
3. stop the debugger and close the file
4. open the file from Explorer -> the edits are gone

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-0.1.ac.235.83.329.metal1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-dsk-chunpe-2a-d0990051.us-west-2.amazon.com|
|OS|Linux x64 4.9.184-0.1.ac.235.83.329.metal1.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz (16 x 2899)|
|Memory (System)|29.44GB (1.87GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
vscode-icons|vsc|10.0.0
material-theme|zhu|3.2.3
python|ms-|2020.2.63990
autodocstring|njp|0.4.0
material-theme|zhu|3.2.3

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
