### ISSUE TITLE
VSCode is automatically copying anything which is highlighted to the clipboard

### ISSUE THREAD

**Issue by roncemer** [microsoft/vscode#91167]
- VSCode Version:
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1.Edit any file.
2.Highlight a line or two of code with the keyboard.  It is automatically copied to the clipboard, overwriting whatever you had in the clipboard before.
3.Search for something which exists. The highlighted instance of what you searched for is automatically copied to the clipboard, overwriting whatever you had in the clipboard before.

This is a serious productivity killer.  It makes it impossible to paste one piece of code over another, because as soon as you select the block of code to be replaced, the code you wanted to paste over it is lost from the clipboard.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Turning off Editor: Selection Clipboard fixes the bug.  Therefore, the default value for Editor: Selection Clipboard should be OFF, and no update should ever turn this ON.

DO NOT CLOSE THIS ISSUE AS A DUPLICATE!

This issue has NOT been dealt with in an update, therefore, it should NOT be closed until it has been properly resolved.  If there is a setting which enables this unwanted functionality, that setting should default to OFF.  The default for a functionality-breaking "feature" (AKA "BUG") should NEVER be ON.

**Comment by gjsjohnmurray** [comment]
Please see #91051. Some of the issues linked from there also offer workarounds. And maybe consider closing this one so as to keep the focus in one place.

**Comment by alexdima** [comment]
@roncemer Do you by any chance use Shift+Insert to paste? As @gjsjohnmurray points out, in the latest release we have changed Shift+Insert to paste from the selection clipboard, and not from the regular clipboard. This is explained in greater detail in #91051 .
