### ISSUE TITLE
Color picker closes prematurely (for real).

### ISSUE THREAD

**Issue by JackSuede** [microsoft/vscode#91164]
This is not like the other issue with the same title. That one was the bug where the color picker closed when the picker hung over a boundary.

The issue I am having is the color picker just disappears 100% of the time in all situations. When I hover over a color in css, the color picker pops up. 

Lets say the color picker pops up directly above the color code so that it seems to be slightly overlapping with the line of code and centered right above the color code. As I move my mouse upwards to enter into the color picker, just as I transition from code to color picker, the color picker disappears. 

Lets say I stopped moving my mouse as soon as the color picker disappears. If i proceed to move the mouse upwards (as pixel by pixel as I can), it seems like once I have moved one pixel higher than the spot where the color picker disappeared, it reappears again. If I move another pixel, it disappears. 

Lets say that once it reappeared, I don't move an extra pixel. At this point the tip of the pointer is on the edge of the color picker. If i hold right click, I can move my mouse onto the color picker. At this point i can freely move my mouse in and out of the color picker where ever I please and it won't disappear unless I release right click. From here I can use left click to drag the circle around to select a new color. As soon as I release left click to drop the circle, the color picker closes, locking in the color the circle was last dragged over.

If the color picker must appear below the color code due to lack of space above the code, then none of the above is possible. It just vanishes with no hope to circumvent.

This all happens 100% of the time without fail. The color picker is therefore, as they say, broken. I have tested with no extensions and a clean install of vs code. Running windows 10. I'd say I can't do anything more to get it working, and chalking it up to being a bug.

**Comment by rebornix** [comment]
@JackSuede thanks for reporting the issue, can you please provide a bit more information like

* what version are you using
* what's the scale of the display
* could you provide a screen recording/gif to help me understand it more (I think I understand what you are running into, but a screen recording may help troubleshoot)
