### ISSUE TITLE
Excessive battery drain

### ISSUE THREAD

**Issue by levous** [microsoft/vscode#91171]
Issue Type: <b>Performance Issue</b>
**How to reproduce:**
Edit markdown documents in Visual Studio Code.
View Energy tab on MacOS Activity Monitor.  Notice VSCode is bananas :)

**More Detail:** 

My battery is being slammed by VS Code.  I'm only using it to edit markdown, at the moment.  I would expect that to be very low impact.  I am previewing the markdown using the build in markdown preview.

I don't see the diagnostics mentioned in https://developercommunity.visualstudio.com/content/problem/537783/insane-battery-consumption.html
I'm happy to grab some data for you, just let me know how.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (4.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    82	 20049	code main
    0	    33	 20050	   gpu-process
    0	   213	 20052	   window (Settings — audit-bell-canada-ios-2020)
    0	    16	 20497	     extensionHost
    0	     0	 26401	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=20497
    0	     0	 28868	       electron_node server.js 
    0	     0	 20505	     watcherService
    0	    16	 20507	   shared-process
    0	     0	 32576	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    33	 25567	   window (undefined)
    0	    66	 32574	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings — audit-xxx-2020)
|    Folder (xxx.-ios-2020): 15 files
|      File types: md(5) png(3) DS_Store(1) gitignore(1) pdf(1)
|      Conf files: makefile(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.50
code-spell-checker|str|1.7.24

</details>

<img width="1372" alt="Screen Shot 2020-02-14 at 1 28 15 PM" src="https://user-images.githubusercontent.com/28144/75062628-30a0a380-54b1-11ea-92b3-d2c1ff950e10.png">

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

The spell checker ones could cause this

**Comment by rizalarsal** [comment]
i have this issue, using latest version, all plugin disabled still happen, no other app opened, im opening project folder for react native, tested in macbook pro retina late 2014, OS catalina. only 5 minute then my fan active, my mac book become so hot. i cant work with this IDE, it can burn my macbook. 

its really weird, i dont have issue like this using other editor.

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by mjbvz** [comment]
Ah, just saw that @rizalarsal is no the original poster.  @rizalarsal please open a separate issue with the collected perf info

@levous Please test with all extensions disabled

**Comment by rizalarsal** [comment]
check #91523

**Comment by mjbvz** [comment]
Closing this as we need more info from the original poster. Let me know if you see this in VS Code 1.43 with all extensions disabled
