### ISSUE TITLE
diffEditor.ignoreTrimWhitespace unclear wording

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91177]
`diffEditor.ignoreTrimWhitespace`: `Controls whether the diff editor shows changes in leading or trailing whitespace as diffs.`

I think:
`Controls whether the diff editor *ignores* changes in leading or trailing whitespace in diffs.`
or 
`When enabled, the diff editor ignores changes in leading or trailing whitespace in diffs.`

Would be more clear.

**Comment by thernstig** [comment]
@JacksonKearl Should it maybe even say "leading AND trailing"?
