### ISSUE TITLE
Ctrl+H does not have any effect

### ISSUE THREAD

**Issue by sc-bperry** [microsoft/vscode#91174]
Issue Type: <b>Bug</b>

The Ctrl+H key combination no longer displays the Find & Replace dialog. Selecting Edit > Replace from the menu bar does work. The Ctrl+F combination does display the Find dialog.

Repro Steps:
1. Type Ctrl+H.
2. No action occurs.

VS Code version: Code - Insiders 1.43.0-insider (c94724193451009962e2c116808f71a3328a9836, 2020-02-19T09:02:21.024Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (15.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|0.20.2
mssql|ms-|1.8.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
azure-account|ms-|0.8.8
powershell-preview|ms-|2020.2.0
markdown-preview-enhanced|shd|0.5.2

</details>

**Comment by rebornix** [comment]
@sc-bperry can you go to Keybindings Editor (F1 -> Preferences: Open Keyboard Shortcuts) and search for ctrl+h, and then share what you get ?

**Comment by sc-bperry** [comment]
Thanks @rebornix! It looks like there is indeed a keybinding for the Replace command. Here are the results when I search for Ctrl+H:

```
Command                   Keybinding        When  Source
Replace                   Ctrl + H          --    Default
Search: Replace in Files  Ctrl + Shift + H  --    Default
```

**Comment by rebornix** [comment]
Thanks, it means the keybinding is not override by any other commands. Could you please try to turn on keyboard recording mode (by toggling the first button in the search bar on the right side) and see what happens when you press ctrl+h?

**Comment by sc-bperry** [comment]
It looks like my OS is not registering the "H" in the Ctrl+H command. When I type Ctrl+H in the recording mode, I get this result:
`"ctrl+"`
For further illustration, when I type Ctrl+F followed by Ctrl+H, I get this:
`"ctrl+f ctrl+"`

I just noticed that Ctrl+H doesn't work in other apps, such as Notepad++. This is not a problem with VSCode. I'll see what's going on post the answer just in case someone else comes across this thread. (FYI, my H key does work, just not Ctrl+H).

**Comment by rebornix** [comment]
thanks for the detailed info! The keyboard shortcut might be used already by some other application.
