### ISSUE TITLE
When entering snippets, allow autocomplete

### ISSUE THREAD

**Issue by ThinkSalat** [microsoft/vscode#91175]
In snippets, it would be nice to allow autocomplete. At the moment, it doesn't have autocomplete or anything.

If it's because you the tab button is used to go to the next spot for input in the snippet, you could just make it so tab autocompletes if the autocomplete dialog is up, or goes to the next spot if it's not.

**Comment by ThinkSalat** [comment]
Yes that's not related

**Comment by gjsjohnmurray** [comment]
/duplicate of #89997, which points to the `editor.suggest.snippetsPreventQuickSuggestions` setting.

**Comment by ThinkSalat** [comment]
> /duplicate of #89997, which points to the `editor.suggest.snippetsPreventQuickSuggestions` setting.

Thanks!
