### ISSUE TITLE
Add FixMe Mode

### ISSUE THREAD

**Issue by shogerr** [microsoft/vscode#91173]
VSCode lacks a FixMe mode. Pretty fundamental stuff for a source code editor.
This feature constantly gets deferred with "belongs in an extension"; except the extensions are garbage. Deferring fundamental features to extensions, features that have been the bread and butter for programmers for some 30 years is just stupid.

Before the replies are "write your own extension" -- submitting code to vscode is a waste of time as the team sucks at interacting with the community -- let MS staff write this application and supporting tools, because MS will fuck over your work at some point anyway. It will take a few years, but they will. Users like me will just go back to Vim or Emacs instead of contributing to this dumpster fire.

**Comment by ryankeener** [comment]
@shogerr I was dealing with a similar issue and found [this to be a helpful resource](https://www.betterhelp.com/advice/anger/the-danger-of-misplaced-anger/)

**Comment by shogerr** [comment]
@ryankeener 
Hey, I'm only meeting the community promoted here at VSCode. You all have somehow managed to create a fairly unfriendly project to participate in. I believe VSCode is a viable editor that may end up existing in 10 years, which is why I'm still here.
However, Microsoft has a history of sending everyone's work down the garbage chute when the work doesn't align with their business values.  Microsoft itself is responsible for the negativity in the community surrounding their work  simply because they've spent the last 5 decades trashing users and developers in search of the dollar.

Calling frustration or anger towards MS as an entity misplaced is moderately laughable, and shows you don't understand the negative force MS has been in the industry.

When you see this kind of bullshit in the CLA, you know something is rotten: 
>b.	Patent	License.	You	grant	Microsoft,	and	those	who	receive	the	Submission directly	or	
indirectly	from	Microsoft,	a	perpetual,	worldwide,	non-exclusive,	royalty-free,	irrevocable	license	under	
Your	patent	claims	that	are	necessarily	infringed	by	the	Submission	or	the	combination	of	the	
Submission	with	the	Project	to	which	it	was	Submitted	to	make,	have	made,	use,	offer	to	sell,	sell	and	
import	or	otherwise	dispose	of	the	Submission	alone	or	with	the	Project.

**Comment by ryankeener** [comment]
@shogerr 
Sorry about the snarky response earlier but you do seem very angry about a free product that you don't have to use. As you suggested, you could just use Vim or Emacs if you don't want to use something by the Bill Gates Evil Empire.

If you're still interested in a FIXME feature for Vscode you might take a look at https://github.com/Gruntfuggly/todo-tree I've been using it for quite some time and find it very useful.

Fwiw, I'm not affiliated with this project in any way, just a satisfied user.
