### ISSUE TITLE
Completion items are mysteriously missing

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#91184]
In the Haxe extension, we are running into an issue where some completion items are mysteriously not being shown, even though they don't violate any of the "known limitations" like "text edit must be single line and on the same line" (at least to my knowledge). I'm not seeing any output in the dev console like you would for those.

I reduced it to a completion provider which returns 10 items with the bare minimum properties, of which only 5 are shown:

![](https://i.imgur.com/AiPgu0L.png)

To reproduce, create a txt file with the following content and request completion after `ele`...

```
class Main {
	static function main() {
		ele
	}
}
```

...while having this extension running:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	vscode.languages.registerCompletionItemProvider('plaintext', {
		provideCompletionItems() {
			const range = new vscode.Range(2, 2, 2, 5);
			return {
				isIncomplete: false,
				items: [
					{
						label: "ElementCreationOptions - js.html.ElementCreationOptions",
						textEdit: new vscode.TextEdit(range, "ElementCreationOptions")
					},
					{
						label: "Element - js.html.Element",
						textEdit: new vscode.TextEdit(range, "Element")
					},
					{
						label: "Element - js.html.svg.Element",
						textEdit: new vscode.TextEdit(range, "Element")
					},
					{
						label: "SelectionMode - js.html.SelectionMode",
						textEdit: new vscode.TextEdit(range, "SelectionMode")
					},
					{
						label: "AElement - js.html.svg.AElement",
						textEdit: new vscode.TextEdit(range, "AElement")
					},
					{
						label: "SelectElement - js.html.SelectElement",
						textEdit: new vscode.TextEdit(range, "SelectElement")
					},
					{
						label: "Selection - js.Selection",
						textEdit: new vscode.TextEdit(range, "Selection")
					},
					{
						label: "Selection - js.html.Selection",
						textEdit: new vscode.TextEdit(range, "Selection")
					},
					{
						label: "GElement - js.html.svg.GElement",
						textEdit: new vscode.TextEdit(range, "GElement")
					},
					{
						label: "else",
						textEdit: new vscode.TextEdit(range, "else")
					}
				]
			}
		}
	})
}
```

____

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
The prefix `ele` is compared against the completion items (label here) and only strong matches pass, e.g the first prefix character `e` must match strong (a first upper case character or character after separator)

**Comment by Gama11** [comment]
Hm... I guess that doesn't work well for "camel-case-edge-cases" like `AElement` and `GElement`, where we technically do have `Ele` after a separator.

**Comment by Gama11** [comment]
This does lead to some awkward situations - let's say we're writing JS code and look for `HTMLElement` by searching for `ele`. This seems to find all sorts of `HTML*Element` classes, just not the one where there's no word in the middle (`HTMLElement` itself):

![](https://i.imgur.com/aigeJpu.png)
