### ISSUE TITLE
"editor.suggestSelection" doesn't seem to work as a language-specific setting

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#91180]
I was trying to contribute a default configuration for `"editor.suggestSelection"` in the Haxe extension as described here by @jrieken: https://github.com/MicrosoftDocs/intellicode/issues/138

However, I couldn't make this work, which made me test if it even works if it's configured by the user in `settings.json` rather than via a `configurationDefaults`. I couldn't make this work as a language specific setting either, not even for TypeScript.

The following .gif shows how `TextEncoder` is pre-selected when completion is invoked (because I had previously selected it), despite the config in the lower panel. Only the non-language-specific setting seems to have an effect.

![](https://i.imgur.com/NAh99Qv.gif)

______

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
> The following .gif shows how TextEncoder is pre-selected when completion is invoked

Please as steps. A gif complements but doesn't replace steps. Adding them will cost way less time than the time it takes me to stare at a looping gif

**Comment by Gama11** [comment]
First, to "initialize" the completion memory, request completion after `Tex` in a TS file and select `TextEncoder`. Undo and press Ctrl+Space again, this time `TextEncoder` should be pre-selected due to the default value of `"editor.suggestSelection"` (`recentlyUsed`).

![](https://i.imgur.com/CPLYrek.png)

____

Add the following to your settings:

```haxe
"[typescript]": {
    "editor.suggestSelection": "first"
}
```

Expectation: this should clear the pre-selection / select the first item when we request completion again, but instead there's no change:

![](https://i.imgur.com/74GTkVR.png)

_____

Now move the setting out of the `[typescript]` block. Only now does the setting have an effect:

![](https://i.imgur.com/sxnYJ20.png)

**Comment by jrieken** [comment]
Yes - turns out this isn't implemented ;-)
