### ISSUE TITLE
how to debug vscode from full compile output?

### ISSUE THREAD

**Issue by Luncher** [Microsoft/vscode#9118]
- VSCode Version: 1.4
- OS Version: fedora 21

Steps to Reproduce:

1.  git clone vscode repository & gulp compile-client-build
2.  ./scripts/code.sh . --remote-debugging-port=9222

questions:  

I want to debug src / vs / code folder, but devtools directory structure looks like this:
![screenshot from 2016-07-12 16 03 32](https://cloud.githubusercontent.com/assets/5138977/16759571/456fdc48-47dd-11e6-9ea3-521915474fe6.png)

not found code folder.

**Comment by weinand** [comment]
@Luncher here is an example for how to set and hit a breakpoint:

- git clone https://github.com/Microsoft/vscode
- cd vscode
- ./scripts/npm.sh install
- gulp compile
- ./scripts code.sh
- F1: toggle developer tools
- set breakpoint in quickOpenController.ts:442 (method 'show') 
- click into VS Code editor area to transfer focus to it
- open Quick Open by pressing Control/Cmd-Shift-O

You should hit the breakpoint in TypeScript source.

**Comment by Luncher** [comment]
I know how to debug, how to set a breakpoint.

I found some code after I started devtools can not debug, for example 
`src / vs / code` directory. I want to debug all the code how do I do that?

thanks :)

**Comment by Luncher** [comment]
@weinand

**Comment by weinand** [comment]
@Luncher follow this: http://stackoverflow.com/questions/31429394/debugging-electron-atom-script-with-visual-studio-code
