### ISSUE TITLE
Should not allow file or directory names to start with space

### ISSUE THREAD

**Issue by ragurney** [microsoft/vscode#91187]
I realize this is entirely user error, but I just wasted a good amount of time trying to track down why a path wasn't resolving, only to find that when creating a folder I had accidentally added a space to the beginning of the name 🤦‍♂ 

<img width="174" alt="Screen Shot 2020-02-21 at 1 52 57 PM" src="https://user-images.githubusercontent.com/15261525/75075609-123ba780-54b3-11ea-9e3a-ab7bf2da0ba2.png">

I can't think of a case where this would actually be desired? It would be great if VS Code wouldn't allow this, and show a validation error if a file or folder name starts with a space. 

I'd be happy to attempt to open a PR for this if this is something you would accept and if someone could point me to the right place to start in the codebase.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What VS Code and OS verisons you are using?

Doesn't happen on Windows 10 in 1.42 and 1.43(Insiders) when I try to add space at the beginning or at the end
![image](https://user-images.githubusercontent.com/1312662/75080096-a89fb580-5513-11ea-88a2-27f2272fff96.png)

**Comment by ragurney** [comment]
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

I'm able to create both a file and folder with a space at the beginning.

![demo](http://recordit.co/1SiE5Mf281)

**Comment by IllusionMH** [comment]
/confirm

Found that I can do this under WSL.
Also found #50631

**Comment by IllusionMH** [comment]
Looks like it was removed in 627ab44080253f7dce5e4972d4398b1aa5da4618 but it's unclear if it was intentional to remove this functionality.
/cc @isidorn

**Comment by isidorn** [comment]
@IllusionMH thanks for help!
We are open to a PR that fixes this elegantly.

**Comment by jeanp413** [comment]
@isidorn would it be ok to change the `IEditableData.validationMessage` method return type to something like `validationMessage: (value: string) => { message:string, type?: MessageType} | null;` ? Though this will require to update some code in `tunnelView.ts` which also uses that method.
https://github.com/microsoft/vscode/blob/811c4b5552e4165262cb25eeb6480e04c295bd9a/src/vs/workbench/common/views.ts#L582-L587

**Comment by isidorn** [comment]
@jeanp413 that makes sense, but if you introduce more stuff like a `type` can be get rid of the `null`?

**Comment by jeanp413** [comment]
Well `null` is returned when the value is valid. I'll create a PR later today then and we can improve from there 👍

**Comment by isidorn** [comment]
To verify: make sure that you get a warning when a file or direcotry start or end with a whitespace.

**Comment by ragurney** [comment]
Awesome, sorry I didn't have any time to look into this. Thanks a lot!
