### ISSUE TITLE
Font not changing, after changing it in User and Workspace settings, and restarting

### ISSUE THREAD

**Issue by Santosh-Gupta** [microsoft/vscode#91186]
- VSCode Version: 1.42.1
- OS Version: Windows 10

I am trying to install the Cascadia font from Microsoft. I am following the instructions here

https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code#installing-cascadia-code-in-vs-code

I have changed both the user settings

https://snipboard.io/ijbqez.jpg

and workspace settings

https://snipboard.io/J2HidL.jpg

And restarted vscode, checking to see the changed remain. However, the text editors still displays Consolas.

**Comment by KamranMackey** [comment]
@Santosh-Gupta Did you install the font for *all* users, or just yourself? If just yourself, I'd try reinstalling the font but install it for *all* users and then try seeing if VS Code sees the font then.

**Comment by IllusionMH** [comment]
/needsMoreInfo

There are 4 downloads what version of font have you used? Do you see this font in Settings > Personalization > Fonts ?

**Comment by Santosh-Gupta** [comment]
I initially installed for myself. After seeing your message I right clicked on the tff file and selected 'Install for all users'. 

I restarted VSC but the font is still the same. I have not restarted my computer yet (some important tabs are open) but I am considering trying this soon. Or let me know if this is useless.

**Comment by Santosh-Gupta** [comment]
> /needsMoreInfo
> 
> There are 4 downloads what version of font have you used? Do you see this font in Settings > Personalization > Fonts ?

I installed 'CascadiaMonoPL.ttf'. 

Turns out that's it was named 'Cascadia Mono PL' in my windows settings, so I changed the name to that, now it works.

**Comment by IllusionMH** [comment]
Just in case if you are using Mono version of the font there are no font ligatures.
From details for latest release on github
> As in 1911.20, this release includes Cascadia Mono, a version of Cascadia that doesn't have ligatures (#80)

So if you plan to use them you'll need to download `CascadiaPL.ttf` and set `'Cascadia Code PL'` in `editor.fontFamily`
