### ISSUE TITLE
delete it

### ISSUE THREAD

**Issue by cm2001218** [microsoft/vscode#91195]
Issue Type: <b>Feature Request</b>

how to delete the navigation bar between tag and editor... it looks like: app>post.php>post 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Jack5079** [comment]
Disable "Breadcrumbs" in Settings (gear at the bottom left)
![Easygoing Snowleopard](https://user-images.githubusercontent.com/29169102/75085849-59e62180-54fb-11ea-99e6-0ce4054a9749.gif)

**Comment by cm2001218** [comment]
thanks!
