### ISSUE TITLE
Update "Turn on sync" text strings

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91192]
<img width="50%" src="https://user-images.githubusercontent.com/35271042/75083425-7d927300-54cd-11ea-9f39-c20d3ffb3620.png">

One of the pieces of feedback we got were that people were looking for an "Account" or "Sign in" terms when looking to enable sync. Can we update the `Turn on sync` text string to read: `Sign in to turn on sync`? Below are examples:

**FireFox**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/75083376-42903f80-54cd-11ea-8423-377eb40548ff.png">

**Chrome**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/75083382-47ed8a00-54cd-11ea-9222-7aafba1d2e1f.png">

**Edge**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/75083383-4a4fe400-54cd-11ea-864e-3062682d3f89.png">

**Comment by sandy081** [comment]
Current menu item is under gear icon which is nothing to do with accounts. So this might go well when we have account management UI.

**Comment by sandy081** [comment]
Improved the title here - https://github.com/microsoft/vscode/issues/92990
