### ISSUE TITLE
Launching mocha with package.json in sub folder doesn't work though 'cwd' option is set

### ISSUE THREAD

**Issue by jschirrmacher** [microsoft/vscode#91196]
- VSCode Version: 1.42.1
- OS Version: OSX 10.15.3

Steps to Reproduce:

1. Have a `nodejs` folder in your workspaceFolder with `package.json` and `node_modules` in it.
2. Create a `launch.json` file in the workspaceFolder with the following content:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "cwd": "${workspaceFolder}/nodejs/",
      "program": "${workspaceFolder}/nodejs/node_modules/mocha/bin/_mocha",
      "args": [
        "-u",
        "tdd",
        "--timeout",
        "999999",
        "--colors",
        "${workspaceFolder}/nodejs/**/*.test.js"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "skipFiles": [
        "<node_internals>/**"
      ]
    }
  ]
}
```

and try to run this target. The result is an execption with the message `Error: Cannot find module 'assume'`. Actually, the module is installed in `node_modules`, but cannot be found because of the subfolder.

Changing to the `nodejs` folder in a terminal window and running `npm test` works correctly.

**Comment by connor4312** [comment]
I'm not able to repro this. Here's my setup.

 1. Outer folder containing `nested` and the `.vscode` launch config.
 2. A file `nested/x/y.test.js` containing `console.log(require('assume'));`
 3. The launch config:

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "cwd": "${workspaceFolder}/nested/",
      "program": "${workspaceFolder}/nested/node_modules/mocha/bin/_mocha",
      "args": [
        "-u",
        "tdd",
        "--timeout",
        "999999",
        "--colors",
        "${workspaceFolder}/nested/**/*.test.js"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "skipFiles": [
        "<node_internals>/**"
      ]
    }
```

4. Running that outputs

```
function Assume(value, flags) { … }
  0 passing (0ms)
```

**Comment by jschirrmacher** [comment]
You're right. The problem was not, as I expected, that VSCode has a problem with the working directory. Instead, my search pattern for test files matched these in `node_modules` as well. And some of these referenced other modules, which are not installed when only used as dependency.

I changed the pattern and then only had to solve the problem, that the `-u tdd` doesn't work as expected [described here](https://stackoverflow.com/questions/55283725/unit-test-mocha-visual-studio-code-describe-is-not-defined) to made my tests run successfully.

Thanks!
