### ISSUE TITLE
Support Format SQL Code

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#9119]
- VSCode Version: 1.3
- OS Version: Fedora 24

Steps to Reproduce:
1. Paste a SQL code
2. Try to format the code
3. No change..
   ![screenshot from 2016-07-12 11-46-08](https://cloud.githubusercontent.com/assets/13297000/16760815/479a3100-4826-11e6-913b-0efb60494413.png)

**Comment by alefragnani** [comment]
I was starting to create an extension for this :smile: 

I tested 3 different npm packages that does the job, but for complex statements, the results were mixed (not as good as I wanted). But I didn't play that much with each package to see how flexible it was to customize the formatting rules.

The ones I tested:

- format-sql
- sqlformatter
- vkbeautify

@weinand do you pretend use an _in house_ approach or search for npm packages?  Let'me know if you need any help/info about the results that I found.

**Comment by weinand** [comment]
@eladcandroid I'm just doing VS Code issue triage this week, so don't expect any additional insights or recommendations from me. I've added the 'help-wanted' tag to indicate that the VS Code team does not intend to work on this feature request.

Two tips:
- You might want to contact the authors of other SQL extensions.
- Consider to investigate how other VS Code language extensions provide formatting functionality.

**Comment by dpkm95** [comment]
I want to contribute this feature. I didn't understand the execution flow for javascript code format (ctrl+shift+i). I'm still learning Typescript. Could anyone point to some resource or explain how code format works in VS Code? Should feature must be provided as an extension? Any help is appreciated.

**Comment by aaronsteers** [comment]
I'm interested in contributing to this cause. Does anyone have a project started?
