### ISSUE TITLE
Reword sign in text in quick pick

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91193]
![image](https://user-images.githubusercontent.com/35271042/75083187-3eafed80-54cc-11ea-92c4-ecc06146bee7.png)

The text `Please sign in...` is very long and wordy (on Windows it wraps to two lines). Can we shorten to something simple like `Sign in to synchronize your data across devices`?

A few examples from others:

**Chrome**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/75083382-47ed8a00-54cd-11ea-9222-7aafba1d2e1f.png">

**Edge**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/75083383-4a4fe400-54cd-11ea-864e-3062682d3f89.png">

**Comment by sandy081** [comment]
I think it is necessary to say using which account you want to sign in. Other examples are quite obvious about account but we are not. So I would shorten it to following

`Sign in with your Microsoft account to synchronize your data across devices`
