### ISSUE TITLE
Create a "sync" tag for sync settings

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91194]
![image](https://user-images.githubusercontent.com/35271042/75083819-8c2e5980-54d0-11ea-9ee8-2d945f04b15b.png)

When going to the sync settings from the sync menu, we use `sync:` to query sync settings. This causes issues because it shows other sync settings from other places (like Git). We should create a `@tag:sync` and tag the sync settings so we an easily query them.

**Comment by roblourens** [comment]
Would this be used by some button or command somewhere? If it would only be used by people typing it in/intellisense, it doesn't seem discoverable enough to be worth it.

**Comment by misolori** [comment]
We have a command from the Sync menu that would trigger this:

![image](https://user-images.githubusercontent.com/35271042/75085307-d4ec0f80-54dc-11ea-8bad-30f76463338f.jpg)

**Comment by roblourens** [comment]
Oh ok yeah I'll add it

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/75097217-f096fa80-555c-11ea-96b5-ce0e6b6a1480.png)
