### ISSUE TITLE
Theme doesn't apply after sycn when accepting remote to resolve conflicts

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91202]
What I did:

- Pressed show conflicts
- Accepted remote

The remote theme didn't apply, despite being installed:

![image](https://user-images.githubusercontent.com/2193314/75095962-1f0dd900-554f-11ea-89a2-bde55dc9aa31.png)

Version: 1.43.0-insider (user setup)
Commit: e6a45f4242ebddb7aa9a229f85555e8a3bd987e2
Date: 2020-02-21T05:42:20.536Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
Assigning to Feb for investigation

**Comment by sandy081** [comment]
@Tyriar it is working for me. Any specific steps to repro?

**Comment by Tyriar** [comment]
Only steps I have are above, it definitely happened though. Close if this isn't actionable.

**Comment by sandy081** [comment]
When you see it next time provide me the sync logs. It could also happen that theme service has not picked it.
