### ISSUE TITLE
Terminal not scrolling down

### ISSUE THREAD

**Issue by RicBent** [microsoft/vscode#91204]
Issue Type: <b>Bug</b>

When executing a command that produces relatively much output, the terminal often does not scroll down automatically anymore. Seemingly random. After scrolling down manually it works again until the same bug occurs once more.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.4.18-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3927)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (4.79GB free)|
|Process Argv|/home/bent/Documents/Projects/HX1K/iceblink|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
arm|dan|0.7.2
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
veriloghdl|msh|1.0.4

</details>

**Comment by Tyriar** [comment]
Not yet confirmed
