### ISSUE TITLE
Editor: undo no longer reveals

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91203]
Steps to Reproduce:

1. make a change to a line
2. scroll it out of view
3. undo 

=> 🐛 the line is not revealed where the undo happens

**Comment by alexdima** [comment]
Thank you, good catch!

**Comment by houmark** [comment]
Thanks for the regression fix @alexdima.

I also noticed one and think this can maybe be tweaked a bit more after trying the most recent nightly with the fix. On undo it's scrolling to the very first/last visible line in the editor. Maybe it could scroll a bit more so you get more context?

In a perfect world, it would remember where you were when you did the edit that you are now undoing to bring you back to the same position. If that's not possible, then at least a bit more context above or below.
