### ISSUE TITLE
Explorer Shortcut Not Working (macOS)

### ISSUE THREAD

**Issue by r3volution11** [microsoft/vscode#91206]
Issue Type: <b>Bug</b>

1. Enter Explorer shortcut: Command + Shift + E
2. Nothing happens.

Note: Using the menu option works fine. The shortcuts for Search, Debug, etc. work as expected.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|-psn_0_14024031|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
scss-lint|ada|0.1.10
Bookmarks|ale|11.0.0
project-manager|ale|10.10.0
Handlebars|and|0.4.1
vscode-color|ans|0.4.5
razor-plus|aus|0.1.4
vscode-intelephense-client|bme|1.3.11
twigcs|cer|1.1.0
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.34.0
mustache|daw|1.1.1
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
css-initial-value|dzh|0.2.3
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
moxer-icons|Equ|5.4.0
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
php-intellisense|fel|2.3.14
cshtml-tm|fir|1.0.0
text-transform|flo|0.1.0
auto-close-tag|for|0.5.6
html-leaf|Fra|0.1.3
unibeautify-vscode|Gla|0.7.0
npm-dependency-links|her|1.0.1
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.13.3
svg|joc|1.1.1
classic-asp-html|jtj|0.1.2
swift|Kas|0.2.0
vscode-swift|kia|0.8.0
tag-rename|kri|0.2.1
twig-language|mbl|0.9.0
twig-language-2|mbl|0.9.0
dotenv|mik|1.0.1
HTMLHint|mka|0.6.0
vscode-scss|mrm|0.9.0
python|ms-|2020.2.64397
remote-ssh-edit-nightly|ms-|2020.2.29760
remote-ssh-nightly|ms-|2020.2.29760
color-highlight|nau|2.3.0
vetur|oct|0.23.0
material-icon-theme|PKi|3.9.3
material-design-icon-svg-snippets|r3v|4.9.95
vscode-swift-language|rlo|0.2.0
gi|rub|0.2.11
aspnet-helper|sch|0.6.4
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
swiftlint|shi|0.1.3
vscode-fileutils|sle|3.0.1
highlight-matching-tag|vin|0.9.6
vscode-swift-development-environment|vkn|2.8.3
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2
wordpress-toolbox|wor|1.3.6
better-align|wwm|1.1.6
vscode-surround|yat|1.0.2

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by r3volution11** [comment]
Yes, I just double-checked and the issue still occurs with extensions disabled.

**Comment by r3volution11** [comment]
Welp, after 2 days it just randomly started working again.
