### ISSUE TITLE
Pasting on OS X has recently become very slow

### ISSUE THREAD

**Issue by varkor** [microsoft/vscode#91213]
- VSCode Version: 1.42.1
- OS Version: 10.12.6

Steps to Reproduce:

1. Copy some text (it does not need to be a large selection).
2. Paste it. There will often be a delay of several seconds.

I'm afraid this issue might be non-actionable, because it's hard to quantitatively reproduce. I have just noticed that since the last couple of versions (probably 1.42), often when using VS Code, pasting will lag for several seconds. Perhaps this is related to changes in pasting behaviour (e.g. https://github.com/microsoft/vscode/issues/90913).

I have https://github.com/rubymaniac/vscode-paste-and-indent bound for pasting, but this extension has not been updated in several years, so the fault is unlikely to be there directly, though it could be some interaction with VS Code's pasting/indentation in recent versions.

**Comment by varkor** [comment]
I wonder if this is actually a problem with performance in triggering extensions: I've just noticed that https://github.com/usernamehw/vscode-indent-one-space is lagging when being triggered too. (After the first trigger, it seems to work okay again for a while.)

**Comment by gjsjohnmurray** [comment]
Maybe use tips from https://github.com/Microsoft/vscode/wiki/Performance-Issues to investigate this, then post extra information here.
