### ISSUE TITLE
vscode jupyter notebook cannot switch kernel

### ISSUE THREAD

**Issue by lx1054331851** [microsoft/vscode#91223]
- VSCode Version: 1.42.1
- OS Version: win10 1909

Steps to Reproduce:

1.install anaconda
2.install a env enviroment
3.in vscode, i can use base anaconda jupyter kernel, but i cannot switch to the env jupyter kernel, when click currnet kernel at the right up conner and select the env kernel, vscode gives a tip to switch the kernel, but after few minites, the used kernel is still the base kernel.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Currently we don't have builtin notebook support in VS Code. Please file issues against the extension which provides the notebook feature.
