### ISSUE TITLE
Test: "Open in Desktop" from web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91225]
Refs: 

- [x] macOS @roblourens
- [x] linux @JacksonKearl
- [x] windows @chrmarti

Complexity: 3

Verify that you can open VSCode insiders on a remote workspace from the web.
* open a workspace via web
* verify you see a "Open in Desktop" status entry that you can click
* verify this opens the remote workspace in your local installed VSCode insiders when VSCode is not running
* verify this opens the remote workspace in your local installed VSCode insiders when VSCode is running on a different workspace

**Comment by JacksonKearl** [comment]
> open a workspace via web

@bpasero  Not sure how to do this, `yarn web` puts me in a sample folder and in that case "Open in Desktop" just opens Insiders to whatever was last open. And VSO does not have an "Open in Desktop" button.
