### ISSUE TITLE
Test Settings Sync for Preview

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#91226]
Ref - #90129 #2743

- [x] mac @roblourens
- [x] win @joaomoreno
- [x] linux @aeschli (test cross platform)

Complexity: 5

---

## Set Up

- Follow instructions [here](https://github.com/microsoft/vscode-settings-sync-server#self-hosting)
- To test, have two insiders open with different user data directories and extension directories

## Testing

In this milestone we fine tuned the feature to make it ready for the preview in insiders. Hence we concentrated mostly on core concepts like design, back ups, error handling and UX. So, I would ask the assignees to do an exploratory testing in all sync areas. Also try to step in as an end user and mainly check if user is able to recover from all sorts of issues (worst - data loss/recovery). Here are some key areas to test.

- Make sure you get a preview confirmation dialog when you turn on sync for the very fist time. This is for the user to opt in to use settings sync preview feature. If you think wordings can be improved, please provide better suggestions. Also note that the documentation link is in progress hence it is currently pointing to a wrong location.
- Test experience of first time syncing from a machine.
- Test settings, keybindings, extensions and display language are syncing across devices flawlessly.
  - Test `machine` and `machine-overridable` scoped settings are ignored by default. These are typically settings that has local paths  as values.
  - Test enablement state of built in extensions are synced 
  - Test advanced settings - ignoring settings, extensions and syncing keybindings across platforms
  - Test you can able to understand and resolve conflicts if they occur.
- Test overall UX. Make sure you can track and monitor sync activity and discover all necessary sync features.
- Retrieving local back ups
- Turning off experience (test this [scenario](https://github.com/microsoft/vscode/issues/89750#issuecomment-587640131)) 
- Test client is not making too many requests when there is no sync activity. For eg., if there are no changes to sync, client shall send only one request to server. You can verify this by enabling log level to trace and monitoring sync activity.

Authors: @sandy081 @Tyriar @misolori @roblourens @RMacfarlane

**Comment by joaomoreno** [comment]
@sandy081 @Tyriar Since auto sync runs every time the window gets focused, this can happen too often. I could get it to run every 2 seconds by focusing in/out of the window. Not sure whether you want to put a rate limiter there, since it will generate *lots* of traffic once every user uses it.
