### ISSUE TITLE
Unstage changes for specific code selection

### ISSUE THREAD

**Issue by szmarczak** [microsoft/vscode#91224]
Instead of clicking on the blue mark and using the `Revert Change` icon every line, I think it would be very useful to select the code, right click and click the `Revert changes` menu entry.

**Comment by joaomoreno** [comment]
You can do that, once you open the diff editor.

**Comment by szmarczak** [comment]
> You can do that, once you open the diff editor.

Yeah, that works too. But that's not what I meant:

> I think it would be very useful to **select the code, right click and click the Revert changes menu entry**.

**Comment by joaomoreno** [comment]
Yes, you can do that in the diff editor. Can you try?

**Comment by szmarczak** [comment]
Sorry I haven't provided more details :sweat_smile: It works in the diff editor, but I meant to ask if it's possible to do so without opening the diff editor, in the default one. If it's not possible, is there a command to revert selected changes?

**Comment by joaomoreno** [comment]
Actually... this works in the regular editor as well. After selection, run <kbd>F1</kbd>, `Git: Revert Selected Ranges`.

**Comment by szmarczak** [comment]
Thank you very much! :raised_hands:
