### ISSUE TITLE
save file

### ISSUE THREAD

**Issue by uzer-13** [microsoft/vscode#91229]
Issue Type: <b>Feature Request</b>

LMB double click on tab to save the file

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.3.9600

**Comment by gjsjohnmurray** [comment]
Doubleclick on a (preview)[https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode] tab already has a function, which is to turn it into a normal tab.

Would you be satisfied with a Save option on the context (i.e. RMB) menu? If so, please upvote #90231
