### ISSUE TITLE
Emmett does not work for Jsx and After saving any jsx file or component representation of code is changed

### ISSUE THREAD

**Issue by rjptechsolutions** [microsoft/vscode#91228]
We have written the neWhen I used JSX my emmet goes off and my representation of code changes at saving of code like that
  return ( <
        footer >
        <
        div className = "footer-block" >
            div.container   
        <
        /div> <
        /footer>
    )
before saving a file it is good after that it changes prettier does not do anything for it is issued in vscode data into your clipboard because it was too large to send. Please paste.

**Comment by octref** [comment]
Please clarify: What's the reproducible steps, expected behavior, etc
