### ISSUE TITLE
Follow link doesn't work for local file in terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91233]
In the xterm.js codebase (the file is relative to the opened folder):

![image](https://user-images.githubusercontent.com/2193314/75115072-64460f80-5610-11ea-9292-dfab958e5e8d.png)

![image](https://user-images.githubusercontent.com/2193314/75115080-74f68580-5610-11ea-9476-7de9356669be.png)

fyi @jmbockhorst

**Comment by Tyriar** [comment]
Happens outside of remote workspaces apparently https://github.com/microsoft/vscode/issues/91294

**Comment by jmbockhorst** [comment]
I am working on a fix so that the widget uses the existing link handlers to open the link instead of the generic opener service. This way, Follow Link will be handled the same way as Ctrl + Click for all types of links (Local, hyperlink, diff, and custom).

**Comment by Tyriar** [comment]
@jmbockhorst sounds great! 🙂

**Comment by jmbockhorst** [comment]
Found a separate but related issue while working on this: #91479.
