### ISSUE TITLE
Chords not working in integrated terminal

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#91238]
Issue Type: <b>Bug</b>

I use key chords heavily in VSCode to navigate and execute actions. It appears that VSCode ignores chords that look like the following: "`modifier+character character`". I've made sure that [the option for allowing chords in the terminal is checked](https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/2NuBA0W2/Image+2020-02-23+at+12.34.46.png?v=9696a06dd75459ec2b59a642716a313f).

Take the following key chord as an example:

![image](https://user-images.githubusercontent.com/8128941/75116842-4a212700-563a-11ea-8d4e-940347d2d534.png)

Below is a gif that shows the issue that I'm experiencing; VSCode recognizes the beginning of the chord, but then sends subsequent characters to the integrated terminal instead of executing the chord. You can see that it's waiting for the next character in the sequence in the status bar at the bottom:

![Screen Recording 2020-02-23 at 12 43](https://user-images.githubusercontent.com/8128941/75116873-9bc9b180-563a-11ea-97c0-7de373efdd49.gif)

This seems like a bug to me; please let me know if there's anything that I can do to narrow down the issue further.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 6|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|-psn_0_610453|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (142)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
scss-lint|ada|0.1.10
vscode-caniuse|aga|0.5.0
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|10.10.0
spellright|ban|3.0.50
vscode-combine-scripts|Bat|2.0.5
search-crates-io|bel|1.2.1
color-info|bie|0.5.1
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
htmltagwrap|bra|0.0.7
better-toml|bun|0.3.2
markdown-jira|chi|1.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.0.29
compulim-vscode-closetag|Com|1.2.0
vscode-svgviewer|css|2.0.0
perl-toolbox|d97|1.4.0
transformer|dak|1.6.0
scala|dal|0.0.5
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
vscode-dash|dee|2.3.0
confluence-markup|den|0.1.8
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
vscode-powertools|ego|0.58.0
LogFileHighlighter|emi|2.7.1
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
json-tools|eri|1.0.2
prettier-vscode|esb|3.20.0
vscode-open-in-github|fab|1.2.3
vimL|fal|0.0.3
markdown-table-formatter|fcr|2.0.3
file-icons|fil|1.0.22
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.16
shell-format|fox|7.0.1
nightswitch|gha|1.1.0
vscode-pull-request-github|Git|0.14.0
gc-excelviewer|Gra|2.1.33
todo-tree|Gru|0.0.167
beautify|Hoo|1.5.0
snooty|i80|0.0.10
output-colorizer|IBM|0.1.2
applescript|idl|0.18.1
customize-ui|ioc|0.1.32
monkey-patch|ioc|0.1.7
path-autocomplete|ion|1.13.3
jbockle-format-files|jbo|3.0.0
docthis|joe|0.7.1
intellij-idea-keybindings|k--|0.2.37
vscode-gist|ken|3.0.3
TypeScriptImport|kev|1.17.0
vscode-gutter-preview|kis|0.25.0
git-indicators|lam|2.1.2
vscode-fix-checksums|leh|1.1.0
node-module-intellisense|lei|1.5.0
expand-region|let|0.1.4
codeacejumper|luc|3.2.0
bash-ide-vscode|mad|1.4.0
MagicPython|mag|1.1.0
rust-analyzer|mat|0.1.20200217
Lisp|mat|0.1.10
terraform|mau|1.4.0
rainbow-csv|mec|1.5.0
git-graph|mhu|1.21.0
vscode-antlr4|mik|2.2.3
HTMLHint|mka|0.6.0
vscode-html-format|moh|0.0.4
theme-monokai-pro-vscode|mon|1.1.15
vscode-docker|ms-|0.10.0
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
csharp|ms-|1.21.12
Go|ms-|0.13.0
debugger-for-chrome|msj|4.12.6
vuejs-extension-pack|mub|1.1.5
vscode-json-editor|nic|0.2.3
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.23.0
fix-json|oli|0.1.2
advanced-new-file|pat|1.2.0
markdown-checkbox|PKi|1.6.0
vscode-css-peek|pra|3.0.2
seti-icons|qin|0.1.3
java|red|0.57.0
vscode-xml|red|0.10.1
vscode-yaml|red|0.7.2
shellman|Rem|4.4.0
vscode-sort-json|ric|1.18.0
vscode-essentials-snippets|rob|2.0.0
bash-debug|rog|0.3.7
zsh-debug|rog|0.1.3
partial-diff|ryu|1.4.1
multi-command|ryu|1.4.0
vscode-javascript-booster|sbu|0.11.0
crates|ser|0.4.7
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
mdx|sil|0.1.0
vscode-fileutils|sle|3.0.1
guides|spy|0.9.3
autoimport|ste|1.5.3
rewrap|stk|1.9.1
tmlanguage|Tog|0.9.0
ghosttext|tok|1.1.0
vscode-status-bar-format-toggle|tom|2.0.0
go-to-method|tri|0.2.0
terminal-tabs|Tyr|0.2.0
vscode-lldb|vad|1.4.5
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-icons|vsc|10.0.0
vim|vsc|1.12.4
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.7.0
propertylist|zho|0.0.2
material-theme|zhu|3.2.3
html-css-class-completion|Zig|1.19.0

(10 theme extensions excluded)

</details>

**Comment by macintacos** [comment]
None of those issues seem to be quite right. Also, for clarity; the key chords work perfectly fine everywhere else (when sidebar, editor, debug console, search panel, problems, etc. have focus, it's fine). Seems to be an issue with the terminal itself.

**Comment by IllusionMH** [comment]
/confirm

Reproduced even on Insiders build on Windows (using PS and Git Bash but I doubt that it depends on shell)

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:42:20.536Z)
OS version: Windows_NT x64 10.0.19569

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
So this still works but you will need to add the command you're using to `terminal.integrated.commandsToSkipShell`, I might not have noticed that as I was testing this with commands that were already configured there by default.

Fixing this would be a good improvement.

**Comment by Tyriar** [comment]
To verify:

1. Focus terminal
2. Execute a command bound to a chord that is not in the default commands to skip shell list. Eg. `ctrl+k p` to copy active file name

**Comment by IllusionMH** [comment]
Worked for me after fix
Checked on <kbd>Ctrl</kbd>+<kbd>K</kbd> with <kbd>O</kbd>/<kbd>P</kbd>/<kbd>S</kbd>/<kbd>M</kbd>/<kbd>Ctrl</kbd>+<kbd>S</kbd>/<kbd>Ctrl</kbd>+<kbd>M</kbd>

**Comment by Tyriar** [comment]
Great! Thanks @macintacos for the report, this is now way better than how it was 👍

**Comment by macintacos** [comment]
Awesome, glad to hear it, appreciate the quick turnaround!
