### ISSUE TITLE
VSCode 1.42.1 javascript intellisense broken, works in insiders

### ISSUE THREAD

**Issue by ffpetrovic** [microsoft/vscode#91236]
- VSCode Version: Version: 1.42.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

Steps to Reproduce:

1. Open fresh install of VSCode  1.42.1
2. Type `[].fo`
3. Expected intellisense with Array methods

Does this issue occur when all extensions are disabled?: Yes

![default](https://user-images.githubusercontent.com/5026566/75115445-eceb9c80-565e-11ea-9a02-552cde16125f.PNG)
![insiders](https://user-images.githubusercontent.com/5026566/75115446-ee1cc980-565e-11ea-9a3a-86ad927769b3.PNG)

**Comment by mjbvz** [comment]
Closing this since it works in insiders (which will be released as VS Code 1.43 shortly)
