### ISSUE TITLE
TypeScript Intellisense sometimes lose track of project definitions.

### ISSUE THREAD

**Issue by thomthom** [Microsoft/vscode#9124]
- VSCode Version: 1.3.0
- OS Version: Windows 10

I don't have a way to reliably reproduce when I observe this, but I wanted to describe it:

I have a project where I use typings to manage definitions for third party libs. (https://github.com/typings/typings)

This saves me from having to use reference comments in every file - instead I rely on `import` statements entirely. 

This works well in VSC - at least when I initially open the project folder. Then after some while I start to get complains from Intellisense that objects and/or properties doesn't exists. These are stem from the definitions from `typings`. But by just restarting VSC the intellisense works fine again - for a while.

I've yet not been able to determine what trigger the intellisense to stop using the `typings` definitions during a session.

The compiler never run into issues - it's just the intellisense that fail after a while in a running session.

Anyone else experienced this? Or have any suggestions to what I can try to debug or create a reliable repro case?

Here is a screen capture that shows the bug in action - intellisense fails to pick up on my third party references. Then I close and reopen the project - and everything works again:

![visualstudiocodeintellisensebug](https://cloud.githubusercontent.com/assets/192418/16766845/adac8f40-483c-11e6-8713-717c01f4ce62.gif)

**Comment by dbaeumer** [comment]
Moving to the TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9666
