### ISSUE TITLE
VS Code constantly unresponsive with no extensions. Have to restart every time.

### ISSUE THREAD

**Issue by Peavii** [microsoft/vscode#91241]
I'm using Visual Studio Code for school and it's really getting frustrating to use on my school laptop... I can't use this program longer than 10mins at most before it goes completely unresponsive. This happens randomly. It also happens while closing a terminal, & while saving occasionally. This really throws off my flow & makes keeping up with the lectures hard every-time I must restart VSC.
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>code

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>code --status

Version:          Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS Version:       Windows_NT x64 10.0.18363
CPUs:             AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx   (4 x 2495)
Memory (System):  5.90GB (2.92GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       92     864  code main
    0      176    2212     window (Mathematical.cpp - Visual Studio Code)
    0       55    5412       extensionHost
    0        6    8276       console-window-host (Windows internal process)
    0       14    7044     electron-crash-reporter
    0       66    8260     shared-process
    0      149    8444     gpu-process

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>
```

Things I've tried are.
-Delete folder and reinstall
-Control Panel uninstall and reinstall
-code --disable-gpu
-Configure runtime arguments, set GPU to disabled.
-Uninstalling the MS C/C++ extension (the only extension I'm using).
-Having only one file open at a time.
-Installing Code in a place other than the C: drive & moving my project to said place.

What else can I try? Should I/can I try an earlier version.

**Comment by gjsjohnmurray** [comment]
Instead of trying an earlier version I suggest you try Insiders, which is a preview of the next version.

https://code.visualstudio.com/insiders/

**Comment by Peavii** [comment]
Thanks for the advice but I have a silly question about Insiders... My course has me launching VS Code from the VS 2019 Developer Command Prompt for an unexplained reason (possibly you know?). Insiders appears to use a different launch command (as opposed to 'code') and I can't find it. Is there a method or should I just use a normal desktop shortcut?

**Comment by seongwon-kang** [comment]
@Peavii Developer Command Prompt sets PATH variable for some build tools (ex: msbuild.exe), so you can execute msbuild.exe in correct path.
maybe your instructor wants to eliminate uncertainty of your machine settings.

**Comment by Peavii** [comment]
So, while it seemed to help a lot (in fact, I rewrote an entire basic cmd prompt game without a crash), Insiders just gave me the typical "The window is no longer responding" message either after closing the terminal or by coincidence while testing my little game.

Also, weird little thing, my ASCII art that worked in the normal VS Code cmd terminal is too long in the Insiders cmd terminal & displays incorrectly due to the lines being too long.

(This displays incorrect on some website (forewarning if this is messy))
```
std::cout << R"(
         ___      ___       __  ___________  __    __    _______  ___      ___       __  ___________  __     ______        __      ___       
        |"  \    /"  |     /""\("     _   ")/" |  | "\  /"     "||"  \    /"  |     /""\("     _   ")|" \   /" _  "\      /""\    |"  |      
         \   \  //   |    /    \)__/  \\__/(:  (__)  :)(: ______) \   \  //   |    /    \)__/  \\__/ ||  | (: ( \___)    /    \   ||  |      
         /\\  \/.    |   /' /\  \  \\_ /    \/      \/  \/    |   /\\  \/.    |   /' /\  \  \\_ /    |:  |  \/ \        /' /\  \  |:  |      
        |: \.        |  //  __'  \ |.  |    //  __  \\  // ___)_ |: \.        |  //  __'  \ |.  |    |.  |  //  \ _    //  __'  \  \  |___   
        |.  \    /:  | /   /  \\  \\:  |   (:  (  )  :)(:      "||.  \    /:  | /   /  \\  \\:  |    /\  |\(:   _) \  /   /  \\  \( \_|:  \  
        |___|\__/|___|(___/    \___)\__|    \__|  |__/  \_______)|___|\__/|___|(___/    \___)\__|   (__\_|_)\_______)(___/    \___)\_______) 
    )";
```

**Comment by Peavii** [comment]
So I found that if I put `cls` into the cmd terminal and then close it, Insiders freezes 100% of the time for me. No random freezes or while saving though! :)
