### ISSUE TITLE
Jupyter NB python kernel only starts in 'base':conda environment

### ISSUE THREAD

**Issue by xamwets** [microsoft/vscode#91240]
Issue Type: <b>Bug</b>

I am using Anaconda and VS Code. Does the Jupyter NB feature only work in the 'base':conda installation? If I try a different conda environment the Jupyter python kernel does not start.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.16
gc-excelviewer|Gra|2.1.33
prettify-json|moh|0.0.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
printcode|nob|3.0.0
vscode-yaml|red|0.7.2
vscode-fileutils|sle|3.0.1
vscodeintellicode|Vis|1.2.5

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

This functionality is provided by Python extension and should be reported in its repo https://github.com/Microsoft/vscode-python/issues
