### ISSUE TITLE
Test column selection mode toggle

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91249]
- [x] anyOS @egamma
- [x] anyOS @octref 

Complexity: 2

---
Please test:
* In the Selection menu, check "Column Selection Mode"
* While this is checked, selecting with the mouse will create a column selection and Shift+arrow keys and Shift+Page Up/Down keys will also create column selection.
* uncheck "Column Selection Mode".
* selecting with the mouse / arrows is back to normal

**Comment by octref** [comment]
Good work. Like it. Agree with Erich there should be a status bar indication and not put to View category.
