### ISSUE TITLE
Folder panel (file selector) broken with MacOs 10.15.4 if files are in iCloud

### ISSUE THREAD

**Issue by stlxiii** [microsoft/vscode#91255]
Issue Type: <b>Bug</b>

Files appear to have the .icloud extension even though they don't if you look at them in Finder.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
terminal|for|0.0.10
prettify-json|moh|0.0.3
python|ms-|2020.2.64397
python-docs|Muk|0.8.3
back-n-forth|nic|0.2.1
rf-intellisense|Tom|2.8.0

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by stlxiii** [comment]
Hello!  Yes I did test also with the nightly version.  I'm not sure how much of an issue it is with VSCode rather than with the beta version of MacOS.  All the files seem to be aliases.

Still works fine if opened from Finder, just not from the folder panel inside VSCode.

I can post a screenshot later if it's not clear.

Thank you

**Comment by isidorn** [comment]
A screenshot would be helpful. Thanks

**Comment by stlxiii** [comment]
I did some more tests and the problem can simply be fixed by making a copy of the folder, or moving it to a different location and moving it back.  Maybe some kind of cache issue?  In the backgroud, the icloud files have moved to a different folder.

Here's two screenshot, one with the problem visible, and the second one after making a copy of the original folder.
<img width="1266" alt="1-problem" src="https://user-images.githubusercontent.com/44322645/75298318-2576ac00-5800-11ea-923d-21fdeb0440e2.png">
<img width="932" alt="2-after_a_copy" src="https://user-images.githubusercontent.com/44322645/75298325-28719c80-5800-11ea-83b6-337a67fd815f.png">

I'm not sure if I should close this issue after all?

**Comment by edgarMejia** [comment]
Just go to settings, find **Files: exclude** and add this rule: `**/*.icloud`

**Comment by boborbt** [comment]
I have a similar issue. Whenever a folder sits in a path handled by iCloud visual studio code does not show any of the files in the folder.

Here is the listing of the folder I'm working on. It sits in a folder named "code" of a sub-...-subfolder of "~/Documents", which is handled by iCloud via the "Documents in the cloud" features of macOS. 

<img width="1627" alt="Screenshot 2022-06-24 at 09 48 16" src="https://user-images.githubusercontent.com/204476/175489090-a23c4f3c-b820-4dc0-b239-d676381b87c2.png">

This is what I'm seeing after issuing `code .`

<img width="1113" alt="Screenshot 2022-06-24 at 09 51 03" src="https://user-images.githubusercontent.com/204476/175489591-c51a5e36-4914-4f12-9220-fc49a4f2eedb.png">

As you can see the file browser is completely empty.

Is there any way to fix it? I already tried starting vscode disabling all extensions and it does not work. The same problem I verified it happens for all folders handled by iCloud (I actually only checked several of them) while it works fine anytime I open vscode outside that folder.
