### ISSUE TITLE
Pyqt-program condn't display icon in toolbar in VSCode.

### ISSUE THREAD

**Issue by drongh** [Microsoft/vscode#9125]
- VSCode Version: 1.3
- OS Version: win10

I use vscode to running pyqt program, but there are no icons on the toolbar. Pyqt program is OK in pycharm. If any help, I would be appreciated.

**Comment by weinand** [comment]
@drongh what python extension are you using?
Your problem description does not provide enough details. Please add reproducible steps.

**Comment by drongh** [comment]
Thanks for you reply.
The extension name is `python`  wrote by Don Jayamanne.
The pyqt-program project has a `.py` file and a `icon` directory. In the icon-directory, there are many icons which are used in toolbar. When running the pyqt-program, there are no icons in toolbar, but the buttons can be clicked.

**Comment by drongh** [comment]
Thanks for you reply.
The extension name is `python`  wrote by Don Jayamanne.
The pyqt-program project has a `.py` file and a `icon` directory. In the icon-directory, there are many icons which are used in toolbar. When running the pyqt-program, there are no icons in toolbar, but the buttons can be clicked.

**Comment by DonJayamanne** [comment]
Closing this issue, as it has been moved to the Python repo.
