### ISSUE TITLE
Test new minimap modes

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91250]
Test plan item for #21849

- [x] anyOS @weinand 
- [x] anyOS @dbaeumer

Complexity: 3

---
There are two new minimap modes that can be set to `editor.minimap.mode`: `contain` and `cover`.

Please check:
* using render characters or render blocks
* using `editor.minimap.scale` which then acts as a maximum scale
* using short, medium sized and large files (where sampling kicks in)
* try editing the file and check how the minimap adjusts (the sampling one is most interesting)
* please keep an eye out for any rendering artefacts

**Comment by gjsjohnmurray** [comment]
Maybe also test with and without line wrapping.
