### ISSUE TITLE
Option to move suggest widget item detail on mouseover 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91259]
Issue Type: <b>Bug</b>

It would be helpful to mouse users if the details for the suggest widget changed on `mouseover` of the suggest list items.

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:39:20.465Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Rust|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (6 x 2600)|
|Memory (System)|1.95GB (0.47GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
rust|rus|0.7.0
vscode-lldb|vad|1.4.5
tsl-problem-matcher|eam|0.1.1
vscode-firefox-debug|fir|2.6.1
remote-containers|ms-|0.102.0
remote-ssh-edit-nightly|ms-|2020.2.33077
remote-ssh-nightly|ms-|2020.2.33077
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
debugger-for-chrome|msj|4.12.6
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
ayu|tea|0.18.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
Sounds useful, let me try in March.
