### ISSUE TITLE
Flaky test: Terminal sendText immediately after createTerminal should not throw

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91263]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=68166&view=logs&j=935a53e5-ce00-51d1-185d-b2f737723cea&t=78251e6f-ceae-58b8-b69e-6d3a7d24b6bc

This just broke the integration tests on Windows 32bit.

**Comment by joaomoreno** [comment]
@Tyriar Is this still an issue?

**Comment by meganrogge** [comment]
Duplicate of #92826
