### ISSUE TITLE
Word suggestions are disabled by default in the SCM input

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#91260]
Looks like word suggestions are disabled by default in the SCM input. This means that suggestions marked as `vscode.CompletionItemKind.Text` will not show up

This was quite confusing to debug. I had to switch the kind of my extension's completion items to `Property`, which is not ideal since they are text suggestions. Here's my current workaround: https://github.com/mattbierner/vscode-emojisense/commit/6d04db03e39cb0cbee44a78d999245386a1c3e74#diff-54b0565b99df34c8aaedf4df4d9ef741R85

**Comment by gjsjohnmurray** [comment]
Probably a consequence of #90994

**Comment by joaomoreno** [comment]
This is due to the fact that we can't disable "words that appear in the document" suggestions. cc @jrieken

**Comment by jrieken** [comment]
> This is due to the fact that we can't disable "words that appear in the document" suggestions. cc @jrieken

Sure you can. There is a setting `editor.wordBasedSuggestions` that you can set on each instance of the editor.

**Comment by joaomoreno** [comment]
I was under the impression this couldn't be done, given the last time we spoke about it. Awesome!

**Comment by joaomoreno** [comment]
Nope, still not easily feasible since that prop doesn't seem available in the `CodeEditorWidget`.

@jrieken suggests:

> ask @sandy081  - I think you can set a transient value for a resource in the config service

**Comment by sandy081** [comment]
You can use `ConfigurationTarget.Memory` to have transient value. This is currently available only in core and we also do not have UI to transient values.

**Comment by joaomoreno** [comment]
But how to do it for [my code editor widget instances only](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/scm/browser/repositoryPane.ts#L755).

**Comment by sandy081** [comment]
Ok, just read the whole issue. It seems `editorWorkerServiceImpl` is reaching out to `configurationService` for `editor.wordBasedSuggestions` config value. So you can update this setting for your resource and all code editor instances of yours using your resource will have this value.

```ts
this.configurationService.updateValue('editor.wordBasedSuggestions', false, { resource: uri }, ConfigurationTarget.MEMORY);
```

**Comment by sandy081** [comment]
It is not scoped to code editor instance, but to a resource. I assume your resource is used only by your code editors.

**Comment by joaomoreno** [comment]
Fantastic! Thanks, @sandy081!
