### ISSUE TITLE
Terminal | Ctrl + Backspace

### ISSUE THREAD

**Issue by elshobokshy** [microsoft/vscode#91267]
Can we have an option to be able to delete left words in the vscode integrated terminal by Ctrl + Backspace ? In the windows shell it doesn't work. I know this might not a priority but it's frustrating not being able to do so. 

I know there's a current feature request open for this, but we can't comment of give any feedbacks about it. Any idea when would this be implemented or how to do it differently on Windows?

**Comment by AllElbows** [comment]
And CTRL + Left Arrow. Works in ISE but not VScode.

**Comment by elshobokshy** [comment]
@AllElbows Ctrl+Left/Right Arrows does work for me

**Comment by Tyriar** [comment]
If the shell accepts something to delete a word to the left you can make a keybinding to send it:

```json
{
    "key": "ctrl+backspace",
    "command": "workbench.action.terminal.sendSequence",
    "when": "terminalFocus",
    "args": {
        "text": "something"
    }
}
```

This would be the best VS Code core could do as well as, just sending stuff to the shell. @TylerLeonhardt there's nothing we can send to powershell for this right?

**Comment by TylerLeonhardt** [comment]
In PSReadLine we added additional keybinding for VS Code:
https://github.com/PowerShell/PSReadLine/blob/ebfe4ce0db94d7dc507c87e412b747def5a1c6e6/PSReadLine/KeyBindings.cs#L232-L235

So as long as you have a newer version of PSReadLine, Ctrl+Backspace should "just work".

Which version of PSReadLine do you have?

In PowerShell 6+:
```pwsh
Get-Module PSReadLine
```
In Windows PowerShell:
```pwsh
# Run both
Get-Module PSReadLine
Get-Module PSReadLine | % { $_.PrivateData.PSData }
```

If you don't have the 2.0.0 _stable_ version of PSReadLine, please follow these steps to update:
https://github.com/PowerShell/PSReadLine#upgrading

Then this should "just work"

**Comment by TylerLeonhardt** [comment]
Now for Ctrl+Arrow keys, I'm not sure how VS Code sends those to the shell. @Tyriar do you know?

**Comment by Tyriar** [comment]
Doesn't work for me?

![image](https://user-images.githubusercontent.com/2193314/78578828-e8c9a780-77e4-11ea-860b-97f301707c88.png)

You can see what gets sent by enabling escape sequence logging: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by Tyriar** [comment]
Note for ctrl+backspace there is this default keybinding:

```json
{ "key": "ctrl+backspace",        "command": "workbench.action.terminal.deleteWordLeft",
	"when": "terminalFocus" },
```

This binds the same as ctrl+w:

https://github.com/microsoft/vscode/blob/9fea64a934a9c00f7b38ef2519baaa188bcb2567/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L196-L197

**Comment by Tyriar** [comment]
Updating to PowerShell 7 fixes the issue for me 🎉

**Comment by elshobokshy** [comment]
Thanks it does work now!
