### ISSUE TITLE
Custom ( not auto detected ) highlighting

### ISSUE THREAD

**Issue by mnini** [microsoft/vscode#91266]
Is it possible to get syntax highlighting triggered by hitting P bar?

Maybe it would be possible to not dot files then and remain highlighted.

**Comment by IllusionMH** [comment]
/needsMoreInfo

I guess that "P bar" is Command palette - you can use `>Change Language Mode` (<kbd>Ctrl</kbd>+<kbd>K</kbd><kbd>M</kbd> (on Windows)) to pick and picking expected language. This choice should be saved for current workspace.

Or file association can be added to match all needed files 
```
"files.associations": {
    "*.out": "log"
},
```

If that's no what you are looking for - you need to provide examples and detailed explanation

**Comment by mnini** [comment]
Normal people doesn't look for Language Mode, but for somethings like "syntax" at least I've had had.
