### ISSUE TITLE
Can't install extensions on 1.3.0

### ISSUE THREAD

**Issue by cschjolb** [Microsoft/vscode#9127]
When pressing the install button on an extension, absolutely nothing happens. Tried to launch code with --verbose too, but no errors are logged. 
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.6.0-0.bpo.1-amd64
- Distro LMDE2
Steps to Reproduce:

1. Install code on LMDE2 (debian jessie based)
2. Try to install extension

**Comment by bpasero** [comment]
Please see https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408
