### ISSUE TITLE
February 2020 Endgame

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91278]
- *February 24* Code freeze for the endgame
- *February 28* [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)
- *March 4* Expected release date (this may change)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday
- [x] Run [OSS tool](https://github.com/microsoft/vscode-build-tools/tree/master/distro-tools) **endgame master**
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] Create test plan items following the template [here](https://github.com/microsoft/vscode/wiki/Writing-Test-Plan-Items) by 5pm PT
- [x] Add verification-needed label to features needed testing and are not tested by TPIs.
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/
- [x] Create Test plan item for smoke testing (OS & browser coverage!) **endgame master** https://github.com/microsoft/vscode/issues/91337
- [x] Review the `extensionKind` list in `product.json` both for stable and insiders, see this [tracking issue](https://github.com/microsoft/vscode-internalbacklog/issues/932). 

##### Tuesday
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
  - [Assigned to you](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3A%40me++label%3Atestplan-item+)
- [x] [🔖All closed feature-requests](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22February+2020%22+label%3Afeature-request+-label%3Averification-needed+-label%3Aon-testplan+-label%3Averified+-label%3A*duplicate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release) either have a `verification-needed` or `on-testplan` label
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] [🔖Testing](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Atestplan-item+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22February+2020%22+label%3Averification-needed+-label%3Averified+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)

##### Wednesday
- [x] [🔖Testing](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Atestplan-item+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+)
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22February+2020%22+label%3Averification-needed+-label%3Averified+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] Prepare for Smoke test: Make sure all smoke test issues are labelled `smoke-test` and fixed **endgame master**

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [🔖Verification needed](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22February+2020%22+label%3Averification-needed+-label%3Averified+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] [🔖Verification](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+is%3Aissue+milestone%3A%22February+2020%22+label%3Abug+-label%3Averified+-label%3Aon-testplan+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] Prepare for Smoke test: Make sure all smoke test issues are labelled `smoke-test` and fixed **endgame master**

##### Friday
- [x] Pause scheduled `insider` builds **endgame master**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
  - [x] js-debug **@connor4312**
- [x] All issues [🔖verified](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+is%3Aissue+milestone%3A%22February+2020%22+label%3Abug+-label%3Averified+-label%3Aon-testplan+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) (⚠️ MUST run with `--stable-build` argument ⚠️ )	
  - [x] Windows - @dbaeumer 
  - [x] OS X - @sandy081 
  - [x] Linux - @aeschli 	
  - [x] Web (Chromium) - @alexr00 
- [x] All release notes updated
  - release notes are collected in a file named *`v<Major>_<Minor>.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @aeschli
  - [x] @alexdima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @connor4312
  - [x] @dbaeumer
  - [x] @deepak1556 
  - [x] @eamodio
  - [x] @egamma
  - [x] @isidorn
  - [x] @JacksonKearl 
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [x] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-js-debug **@connor4312**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexdima**
  - [x] vscode-loader **@alexdima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [ ] vscode-recipes **@chrisdias**
  - [x] localization **@weeteckt**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [x] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **endgame master**
- [x] Acknowledge [issue trackers](https://github.com/microsoft/vscode-internalbacklog/wiki/Community-Triage:-Credits) from the community **@chrmarti**
- [x] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **endgame master**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **endgame master**
- [x] Bump up the version in package.json - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [x] [🔖milestone issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A%22February+2020%22+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] [🔖candidate issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release)
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **endgame master**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [x] Build stable for all platforms as new candidate issues come in **endgame master**
- [x] Documentation updated
  - [x] @aeschli
  - [x] @alexdima
  - [ ] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @connor4312
  - [x] @dbaeumer
  - [x] @deepak1556 
  - [x] @eamodio
  - [x] @egamma
  - [x] @isidorn
  - [x] @JacksonKearl 
  - [x] @joaomoreno
  - [ ] @jrieken
  - [ ] @kieferrm
  - [x] @mjbvz
  - [ ] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [x] Run `scripts/test-documentation.sh|bat` and add file or fix issues if there are new colors that are not documented.

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame. **endgame master**

##### Wednesday/Thursday
- [x] Build stable for all platforms **endgame master**
- [x] Sanity check of installable bits
  - [x] Windows 32 bit @sbatten 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit @rebornix 
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] OS X - @Tyriar 
  - [x] Linux
    - [x] deb package 64-bit @JacksonKearl 
    - [x] rpm package 64-bit @RMacfarlane 
    - [x] archives @RMacfarlane 
    - [x] snap @JacksonKearl 
  - [x] Server
    - [x] Linux ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers)) @Tyriar
    - [x] macOS @roblourens 
    - [x] Windows @roblourens 
- [x] Publish website **@gregvanl**
- [x] Publish Localization language pack **@weeteckt**
- [x] Publish to stable **endgame master**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **endgame master**
- [x] [Publish @types/vscode](https://github.com/microsoft/vscode/wiki/Publish-vscode-types) **endgame master**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@chrisdias**

**Comment by sandy081** [comment]
swapping with @chrmarti for buddy role.

**Comment by sanket-bhalerao** [comment]
is setting sync going to be released as part of this release?

**Comment by Techman** [comment]
Is the OSS build tool link private?

**Comment by Stanzilla** [comment]
@sanket-bhalerao I don't think so, it's still disabled in Insider builds...but it's mentioned in the changelog.

**Comment by sanket-bhalerao** [comment]
@Stanzilla, i saw that, raised a bug for this.
#91875 - closed without a proper explanation, why its in release notes if its not released.
so created another #91882

**Comment by gjsjohnmurray** [comment]
@sanket-bhalerao I guess the release notes in Insiders aren't formally released yet, so are subject to change.

**Comment by gjsjohnmurray** [comment]
> 
> 
> @sanket-bhalerao I guess the release notes in Insiders aren't formally released yet, so are subject to change.

Seeing it another way, when 1.43 releases (probably later this week) its release notes will tell 1.43 users that they can get a preview of Settings Sync in the Insiders release, which by then will be 1.44.0-insider.

**Comment by sandy081** [comment]
@sanket-bhalerao We are preparing release notes for next major release (1.44.0) and we are making Settings Sync ready for preview from next insiders (1.44.0-insiders). I was completely forgotten that current insiders picks up this release notes. I will update the release notes and mention from which insiders it will be available from. 

Sorry for the confusion.

**Comment by gjsjohnmurray** [comment]
> @sanket-bhalerao We are preparing release notes for next major release (1.44.0) and we are making

Typo there. The next major release @sandy081 is referring to is 1.4**3**.0

**Comment by sanket-bhalerao** [comment]
@sandy081 thanks for the update,
@gjsjohnmurray thanks for the clarification.

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks for the correction. Updated my comment.

**Comment by gudvinr** [comment]
> release notes are collected in a file named **`Month_Year.md`**

Your endgame template still quite outdated (:

**Comment by Tyriar** [comment]
@gudvinr updated the issue and template 👍

**Comment by usernamehw** [comment]
Is it possible to use the last day as "expected release date", because It's usually published later:

> March 4 Expected release date (this may change)

> Wednesday/Thursday
> - [ ]  Build stable for all platforms endgame master
> - [ ] ...


Wednesday - March 4
Thursday - March 5

```diff
- March 4 Expected release date (this may change)
+ March 5 Expected release date (this may change)
```

Also using a link to the release notes document instead of repository:

```diff
- https://github.com/Microsoft/vscode-docs/tree/vnext/release-notes
+ https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_43.md
```

https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_43.md

**Comment by nicholasengleman** [comment]
What is the hold up here?

**Comment by Tyriar** [comment]
Released this yesterday.

@nicholasengleman sometimes things get delayed due to bugs we find late or issues we hit during release.

@usernamehw added the expected release day note, I'm not changing the link to the release notes md though as that would require yet another thing for the endgame master to do every month.
