### ISSUE TITLE
Test SCM welcome view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#91270]
Test plan item for #61491

- [x] macOS @RMacfarlane
- [x] anyOS @fiveisprime

Complexity: 2

---

Please go through the [5 different cases of SCM](https://github.com/microsoft/vscode/issues/61491#issuecomment-586945696) git welcome view content and make sure they all work:

1. Git extension disabled
2. No git installed
3. No open folder
4. Current folder is not (inside) a git repo
5. Current workspace has no folder which is (inside) a git repo

Let me know if you think there are additional situations which should be covered.

**Comment by fiveisprime** [comment]
Tested in Windows

1. ✔️ 
1. ✔️ No error is awesome and the links are helpful 👍 
1. ✔️ 
1. ✔️ 
1. ✔️  The init correctly prompts for directory to initialize
