### ISSUE TITLE
Typescript service failed

### ISSUE THREAD

**Issue by vinayakshahdeo** [microsoft/vscode#91277]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

failed typescript

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-1069-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3683)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|15.54GB (6.94GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-multi-line-tricks|big|0.0.3
turbo-console-log|Cha|1.3.1
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.6.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vscode-firefox-debug|fir|2.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-auto-open-markdown-preview|hnw|0.0.4
graphql-for-vscode|kum|1.15.3
git-graph|mhu|1.21.0
prettify-json|moh|0.0.3
python|ms-|2020.2.64397
debugger-for-chrome|msj|4.12.6
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.3
code-spell-checker|str|1.8.0
vscode-open-in-github|sys|1.13.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
