### ISSUE TITLE
Fold all block html comments in Markdown

### ISSUE THREAD

**Issue by atanasj** [microsoft/vscode#91271]
It would be great to be able to quickly fold `html` comments that span multiple lines in `markdown`. This feature is available standard in `emacs` and makes for a quick distraction free writing experiences (if you're someone like  me who likes to use comment blocks for notes in documents). Not sure if the scope of the [issue here](https://github.com/microsoft/vscode/issues/85783) covers this feature request.

Not sure how hard this would be, but I for one would LOVE IT!

**Comment by blueworrybear** [comment]
Hi, I am interesting in this feature. May I work on this?

**Comment by blueworrybear** [comment]
It turns out that the solution is quite simple 😎
Below is the demo. @atanasj please let me know if this is what you expect:

[![fold block](https://i.imgur.com/KQRDpJC.png)](https://i.imgur.com/5h0Erv8.mp4)

**Comment by mjbvz** [comment]
Yeah actually this already seems to work for me too. If there is some case that doesn't work, please post example markdown that demonstrates the issue

**Comment by mjbvz** [comment]
Actually, one thing isn't working properly is tagging the range type to be comment

**Comment by roblourens** [comment]
> Actually, one thing isn't working properly is tagging the range type to be comment

What change should I see as a result? I think this looks the same as in stable

**Comment by mjbvz** [comment]
You need to run the fold comments commands specifically. Before we created folding ranges for html comments but they were not tagged as comments

**Comment by roblourens** [comment]
I am running that command in stable and it folds the block comments

**Comment by roblourens** [comment]
"In Markdown" wow reading comprehension
