### ISSUE TITLE
Issue with CPU on MacOS when I try to use autocomplete

### ISSUE THREAD

**Issue by sashkomatviychuk** [microsoft/vscode#91289]
Issue Type: <b>Performance Issue</b>

VS Code was updated today. When I try to use autocomplete (press shortcut) I see loading message. In Activity Monitor Code Helper Renderer takes more than 100% of CPU

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 6|
|Memory (System)|16.00GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    98	  1466	code main
    1	    82	  1467	   gpu-process
    1	   279	  1471	   window (user.js — server)
    0	   131	  1491	     extensionHost
    0	    82	  1497	       /usr/bin/java -classpath /Users/oleksandr/.vscode/extensions/adamvoss.vscode-languagetool-3.8.0/lib/languagetool-languageserver/build/install/languagetool-languageserver/lib/*:/Users/oleksandr/.vscode/extensions/adamvoss.vscode-languagetool-en-3.8.0/lib/* App 49850
    0	    66	  1500	       electron_node eslintServer.js 
    0	    82	  1566	       node /Users/oleksandr/projects/vibo/server/node_modules/.bin/jest --testLocationInResults --json --useStderr --outputFile /var/folders/5x/myc6q49j5zqggl79xpld_5cr0000gn/T/jest_runner_server.json --watch --no-coverage --no-color --reporters default --reporters /Users/oleksandr/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js
    0	    66	  1755	       electron_node tsserver.js 
    0	   508	  1756	       electron_node tsserver.js 
    0	    49	  1757	         electron_node typingsInstaller.js typesMap.js 
    0	    33	  1492	     watcherService
    0	    33	  1505	     searchService
    0	    98	  1541	   shared-process
    0	     0	  1788	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    98	  1779	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (user.js — server)
|    Folder (server): 326 files
|      File types: js(144) html(38) wt(21) json(7) lock(2) 0000000001(2)
|                  css(2) dockerignore(1) env(1) dev(1)
|      Conf files: package.json(1) launch.json(1) settings.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
jest-snippets|and|1.7.0
node-snippets|chr|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-express|Com|0.0.5
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.6.0
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
docthis|joe|0.7.1
dotenv|mik|1.0.1
vscode-filesize|mkx|2.1.3
vscode-docker|ms-|0.10.0
debugger-for-chrome|msj|4.12.6
vscode-jest|Ort|3.1.1
vscode-graphql|Pri|0.2.2
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
