### ISSUE TITLE
Keep all validation but turn off "convert to an ES6 module"

### ISSUE THREAD

**Issue by WORMSS** [microsoft/vscode#91282]
I see many issues of how to disable the individual feature, and the same answer is always given, to disable ALL validation.

So I thought best to make a very specific issue

I would like to keep ALL validation except one. The "Convert to an ES6 module.".
How to disable this ONE feature, but keep all other validation.

Advice on how to disable ALL validation is not a valid response.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by WORMSS** [comment]
Or, you could intercept the error, and just ignore it in vscode, no need to change typescript then.
