### ISSUE TITLE
I can't to see  the plus icon to expand my code, when it's collapsed

### ISSUE THREAD

**Issue by henriquecustodia** [Microsoft/vscode#9128]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. change a code already commited by git 
2. In the same line, I cannot to see the plus icon to expand my code (when it is collapsed)

![vscode issue](https://cloud.githubusercontent.com/assets/5140430/16768907/b6ed1dd8-481c-11e6-9a54-6aac100aad3e.jpg)

**Comment by aeschli** [comment]
dup of #9222
