### ISSUE TITLE
Panel read only indicator doesn't display correctly for first line

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91287]
@rebornix for monaco

![image](https://user-images.githubusercontent.com/2193314/75167798-c79c7400-56da-11ea-979a-2a366e4a5db5.png)

**Comment by Tyriar** [comment]
Works fine in the editor

![image](https://user-images.githubusercontent.com/2193314/75167924-f3b7f500-56da-11ea-9cf5-fdfd451204ab.png)

**Comment by rebornix** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/876920/98175526-a3b94100-1eab-11eb-8033-c7b03d403038.png">

Currently it's working fine.
