### ISSUE TITLE
Prompt if moving files/folders inside the `node_modules`

### ISSUE THREAD

**Issue by szmarczak** [microsoft/vscode#91291]
I accidentally moved a folder inside the `node_modules` directory (meant to just collapse it) and had to run `rm -rf node_modules && npm install` to fix things. I think it's worth prompting users to confirm such action.

**Comment by isidorn** [comment]
We always prompt, make sure you do not have this disabled in your settings

![Screenshot 2020-02-25 at 15 32 58](https://user-images.githubusercontent.com/1926584/75256687-226dc280-57e4-11ea-9803-180d7f024bfd.png)

**Comment by szmarczak** [comment]
> make sure you do not have this disabled in your settings

I can't find anything related to this. What do you have in mind?

**Comment by isidorn** [comment]
`explorer.confirmDragAndDrop` is the name of the setting

**Comment by szmarczak** [comment]
Oh, didn't notice that, thank you :)
