### ISSUE TITLE
Tooltips not loading and autocomplete not showing up.

### ISSUE THREAD

**Issue by Noxillio** [microsoft/vscode#91295]
![image](https://user-images.githubusercontent.com/40806092/75175576-959e0880-5700-11ea-886a-034793b1ff74.png)

OS: Windows 10 Pro Insider Preview 19569
VSC Version: 1.43.0-insider
TypeScript version: 3.8.2

Issue occurs when editing .ts files.

Update: Tooltip finally decided to show up, but autocomplete still isn't working and quick fixes don't show either.
Update 2: Tooltips are getting stuck again

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
