### ISSUE TITLE
C# syntax highlighting, after wrong XML Comment doesn't work.

### ISSUE THREAD

**Issue by saxc** [microsoft/vscode#91292]
- VSCode Version: 1.43.0-insider (user setup)
- Commit: 07c33977da255861edf71e65b18249d2f67d0762
- OS Version: Windows_NT x64 10.0.18363
- without extensions

Steps to Reproduce:

The test code was write in VS 2019 (works).
By removing an quote in the XML comment, VS Code shows all subsequent lines as string.

![VS-Code](https://user-images.githubusercontent.com/7613585/75173516-4a4f1e80-572f-11ea-8ab5-c2683e441642.png)

```csharp
using System;

namespace ConsoleApp1
{
    class Program
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="args></param>
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

**Comment by alexr00** [comment]
Moved to owning repo.
