### ISSUE TITLE
Control clicking a relative path in the terminal works, but not clicking "Follow link"

### ISSUE THREAD

**Issue by Kurtoid** [microsoft/vscode#91294]
Issue Type: <b>Bug</b>

If I control+click a relative file path in the terminal, the file opens without an issue. If I hover over it, and press "Follow link", the workspace flickers, and the "Unable to open ... Unable to read file..." error appears.

I have a multi-folder workspace, structured as so
- backend
     - src
- frontend
     - etc

the relative path is 
"./src/componets/somefile.js"

Oddly enough, if I add backend/src as a workspace folder, both methods of clicking the link work.

tl;dr: the terminal handles relative paths inconsitently

VS Code version: Code - OSS 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-17T09:32:31.598Z)
OS version: Linux x64 5.5.5-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4052)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.44GB (7.34GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
java|red|0.57.0
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vim|vsc|1.12.4

</details>

**Comment by Kurtoid** [comment]
The workaround is easy enough, either
* add backend/src as a project folder
    * but this feels redundant though
* or control-click on the path
    * which works just fine

It's just strange that pressing "Follow link" works differently than control+click, which should do the exact same thing

**Comment by Tyriar** [comment]
Looks like this is https://github.com/microsoft/vscode/issues/91233

/duplicate
