### ISSUE TITLE
Add support for "global comment" next to file format comment

### ISSUE THREAD

**Issue by amadeuszkryze** [microsoft/vscode#91302]
I'd like to have a feature to comment things in global way regardless of what comment type certain file type has, eg.:
- JinjaYAML file has `{##}` notation under `command+/` shortcut
- YAML file has `#` notation under `command+/` shortcut

I'd like to comment whole blocks with `#` block comment in JinjaYAML without changing file type to YAML and then go back to JinjaYAML after commenting.

New shortcut could be `command+shift+/` or whatever else.

**Comment by alexdima** [comment]
Please open an issue directly against the extension providing JinjaYAML support. It appears the problem is with the language definition, which does not define a line comment token (`#`), and only block comment tokens (`{#`, `#}`).
