### ISSUE TITLE
/absolutepath:line:col links in term don't --goto

### ISSUE THREAD

**Issue by edrex** [microsoft/vscode#91306]
- VSCode Version: `pacman -Q code # code 1.42.1-1`
- OS Version: Arch Linux

Steps to Reproduce:

1. run some npm script that produces a trace
2. "Follow link" on one of the /path:line:col refs

Eg:

```
(node:30905) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'byKey' of undefined
    at Object.list (/home/eric/src/gitlab.com/coboxcoop/core/cobox-server/node_modules/cobox-config/lib/handlers/keys.js:37:40)
```

Result:
```
Unable to open 'keys.js:37:40': Unable to read file '/home/eric/src/gitlab.com/coboxcoop/core/cobox-server/node_modules/cobox-config/lib/handlers/keys.js:37:40' (Error: Unable to resolve non-existing file '/home/eric/src/gitlab.com/coboxcoop/core/cobox-server/node_modules/cobox-config/lib/handlers/keys.js:37:40').
```
Expect: goto that line/col, as indicated by @Tyriar in #66957

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
