### ISSUE TITLE
Test GitHub authentication provider

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#91309]
Refs: https://github.com/microsoft/vscode/issues/90384

- [x] macOS @kieferrm
- [x] linux @jrieken
- [x] windows @stevencl

Complexity: 3

A built in GitHub authentication provider is now in core. This is not yet being used by anything else in core, but is available to other extensions. To test, please use the new Authentication Provider API in an extension: https://github.com/microsoft/vscode/blob/64517a93849bcb9c4e270fb3e46a17473f03cf13/src/vs/vscode.proposed.d.ts#L19-L79

- Are you able to find the provider in `vscode.authentication.providers`
- When calling ` login`, is a consent dialog shown
- When fetching the value of `accessToken` on a session, is a consent dialog shown
- Are you able to complete GitHub auth and get an access token

Here is some example code you can use to get started:
```ts
async function getCachedSesssionOrLogin(provider: vscode.AuthenticationProvider) {
	const sessions = await provider.getSessions();
	if (sessions.length) {
		const token = await sessions[0].accessToken();
		console.log(token);
	} else {
		const token = await provider.login(['user:email']);
		console.log(token);
	}	
}

const provider = vscode.authentication.providers.find( provider => provider.id === 'GitHub');
if (provider) {
	getCachedSesssionOrLogin(provider);
}

vscode.authentication.onDidChangeAuthenticationProviders(async changed => {
	if (changed.added.includes('GitHub')) {
		const provider = vscode.authentication.providers.find(provider => provider.id === 'GitHub');
		if (provider) {
			getCachedSesssionOrLogin(provider);
		}
	}
});
```

Documentation on the available `scopes` that can be used with login is available here: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

**Comment by kieferrm** [comment]
I have two items that I will file:
- the open URL dialog after login
- that I have to OK the access to the token for the extension that logged in

**Comment by KamasamaK** [comment]
@kieferrm Have you filed those issues yet? I can't find them.
