### ISSUE TITLE
Unexpected setting sync conflict with boolean setting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91308]
The highlighted line is the only change:

![image](https://user-images.githubusercontent.com/2193314/75184692-a39c5b00-56f9-11ea-9820-f7cf5f35d115.png)

This happens after turning sync back on and hitting merge

**Comment by sandy081** [comment]
@Tyriar Is not this expected when you turn sync back on and merging? Remote and local has different values and hence conflict is shown.

**Comment by Tyriar** [comment]
You're right, brain fart I guess 😅
