### ISSUE TITLE
Suggest widget with codicons are off aligned

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91300]
When using codicons in the suggest widget detail pane, they appear to be off aligned:

![image](https://user-images.githubusercontent.com/35271042/75178592-3aaee600-56ed-11ea-8fc7-9d6e691ad2ad.png)

Tweaking the CSS I was able to use `vertical-align: sub` to get it closer:

![image](https://user-images.githubusercontent.com/35271042/75178828-b01ab680-56ed-11ea-9567-7941884e5855.png)

cc @alexr00

**Comment by octref** [comment]
`vertical-align: middle;` is there: https://github.com/microsoft/vscode/blame/master/src/vs/editor/contrib/hover/hover.css

Looks like this to me. How can I reproduce your layout?

![image](https://user-images.githubusercontent.com/4033249/75294575-a8d2d600-57dd-11ea-82cc-8b5683160c2a.png)

**Comment by misolori** [comment]
@octref try it in the SCM input box

![image](https://user-images.githubusercontent.com/35271042/75296332-b9854b00-57e1-11ea-9b95-6ac9fffefdc1.png)

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/75401515-3f26fa80-58b7-11ea-98a8-b2cd199cac22.png)
