### ISSUE TITLE
VS Code Freezes after stop debugging and do some stuff

### ISSUE THREAD

**Issue by dralpus** [microsoft/vscode#91313]
It freezes all the time just after stop debugging and do some stuff without having any randomness.

$ code --status

Version:          Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)
Memory (System):  31.73GB (8.73GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     unavailable_software
                  flash_3d:                      disabled_software
                  flash_stage3d:                 disabled_software
                  flash_stage3d_baseline:        disabled_software
                  gpu_compositing:               disabled_software
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        disabled_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  disabled_software
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         unavailable_software
                  webgl2:                        unavailable_software

CPU %   Mem MB     PID  Process
    0       74   52300  code main
    0      218   20580     window (index.html - MSN.Library.OneService.Functions - Visual Studio Code)
    0       35   35304       searchService
    0        5   50800       C:\windows\System32\cmd.exe
    0       36   51440         electron_node cli.js
    0       61   59632           "C:\Users\Alp\AppData\Local\Programs\Microsoft VS Code\Code.exe" --status
    0       98   40892             gpu-process
    0        6   54348       console-window-host (Windows internal process)
    0      214   57712       extensionHost
    0       56   27856         "C:\Users\Alp\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Alp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=57712
    0       34   51352         electron_node server.js
    0       36   54548         electron_node server.js
    0       11   57864       watcherService
    0       11   50040         console-window-host (Windows internal process)
    0       53   50284     shared-process
    0        5   52548     electron-crash-reporter
    0       48   52812     gpu-process

Workspace Stats:
|  Window (index.html - MSN.Library.OneService.Functions - Visual Studio Code)
|    Folder (MSN.Library.OneService.Functions): 448 files
|      File types: js(89) dll(80) html(55) json(41) css(25) md(16) png(12)
|                  kql(4) cache(4) yaml(4)
|      Conf files: csproj(1) package.json(1) launch.json(1) settings.json(1)
|                  tasks.json(1)
|      Launch Configs: node

**Comment by isidorn** [comment]
Reproducable steps please.
