### ISSUE TITLE
Unable to open ... Document already exists viewType:imagePreview.previewEditor

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91317]
1. Create `icon.png` as empty file and open it
2. Add some other file, like `git.png`.
3. Delete `icon.png` and rename `git.png` to `icon.png`.
4. Open `icon.png`

![image](https://user-images.githubusercontent.com/8586769/75196216-62637580-5710-11ea-8497-26a108249d23.png)

**Comment by mjbvz** [comment]
**Another Repo**
1. Copy and paste next to the existing image  the explorer

**Comment by mjbvz** [comment]
@JacksonKearl Thanks for catching this. Let me know if you see this again with your repo steps
