### ISSUE TITLE
Can't install, update, delete, view extentions

### ISSUE THREAD

**Issue by vitalijsozornins** [Microsoft/vscode#9131]
- VSCode Version: 1.3.0
- OS Version: Linux RFE005 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Ctrl+P
2. paste any install e.g.:  ext install JavaScriptSnippets
3. Press "install" button
4. No results

Also 
1. Ctrl+Shift+X
2. press "..."
3. Show Installed extentions
4. No results at all.

Toggle Developer tools:
Every second or like that exception in console:

`Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23456),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416(anonymous function) @ shell.ts:318e.onUnexpectedError @ errors.ts:73u @ errors.ts:88(anonymous function) @ winjs.base.js:43(anonymous function) @ winjs.base.js:38
winjs.base.js:45 WARNING: Promise with no error callback:154`

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408
