### ISSUE TITLE
not load opened files after closing vscode and reopening with double click on a file.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#91319]
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. open some files in vscode
2. close vscode
3. open a file: right click on a vscode supported file and from "Open With" menu select "vscode"
after this the file opening but all opened file before close vscode not showing!

Does this issue occur when all extensions are disabled?: No

**Comment by byehack** [comment]
can u say this duplicate with which issue?
if any same issue exists, it is not open. but the problem is still exists.
:)

**Comment by jdmacdaddy** [comment]
I also cannot find this as an open duplicate issue/feature request elsewhere. Can you please provide a link to the open issue? 

To reiterate the steps @byehack indicated: 

1. Open several files in VS Code
2. Close VS Code
3. Re-open VS Code by double-clicking on a file type that is associated with VS Code. 

VS Code closes all other files you had open and only opens the one. If you remember to open VS Code first and then double-click on the file you need to open, all open files remain open. I have disabled all extensions and the issue persists. 

This is not related to workbench.editor: enable preview.
