### ISSUE TITLE
Typing code forces new window to open

### ISSUE THREAD

**Issue by gvashishtha** [microsoft/vscode#91316]
Issue Type: <b>Bug</b>

Use `code` to open a file from a newly-opened terminal running WSL. Instead of opening up the file in the existing window, it will open up a new window with the file and a new terminal. This is annoying.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (1.86GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (1.86GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.10.0
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-ssh-explorer|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
vscode-icons|vsc|10.0.0
markdown-preview-github-styles|bie|0.1.6
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.34.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.6
docs-images|doc|0.0.5
docs-markdown|doc|0.2.51
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.39
docs-yaml|doc|0.2.4
extbundles-csharp|Fel|2.0.0
docomment|k--|0.1.8
csharp-colors|log|0.1.7
vscode-docker|ms-|0.10.0
python|ms-|2020.2.64397
csharp|ms-|1.21.12
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.7.2
code-spell-checker|str|1.8.0
msbuild-project-tools|tin|0.3.3

</details>

**Comment by aeschli** [comment]
If there's already WSL window, that window will be used to open the file.
But if there's just a normal (non-WSL) window, or a WSL-Window for an other distro, a new window will be opened.
Is that what you see?

That has to be like that so that rich language services (e.g. TypeScipt) work properly.
