### ISSUE TITLE
The font won't change to anything other than Consolas or monospace.

### ISSUE THREAD

**Issue by man-ahmad** [microsoft/vscode#91312]
- VSCode Version: 1.42.1 
- OS Version: 10.0.17763 Build 17763

Steps to Reproduce:

1. Open VS Code
2. Open the Command Palette
3. Enter User Settings (JSON)
4. Change `editor.fontFamily` to `Fira Code, monospace`

Does this issue occur when all extensions are disabled?: Yes

Basically, I open up VS Code and try to change the user settings to a different font that's NOT Consolas or the fallback monospace font, but it doesn't seem to work. The fonts seem to be working elsewhere on my computer (Word, Notepad), so I'm not sure how to work through this one. Any help is greatly appreciated!

**Comment by misolori** [comment]
If you are seeing the consolas font, that means either that you are typing in the name of the font wrong or you don't have the font installed. 

Can you verify that the font is installed on your machine using Font Book and under "User"?

![image](https://user-images.githubusercontent.com/35271042/75192921-144b7380-570a-11ea-8447-282a918c193c.png)

And can you verify that you don't have any errors in your `settings.json`?
![image](https://user-images.githubusercontent.com/35271042/75192988-37762300-570a-11ea-98d4-1e90328c78da.png)
