### ISSUE TITLE
Provide better way for plaintext completion providers to opt out of being enabled in scm input

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#91310]
**Problem**
My extension registers completion providers using the following `DocumentSelector`(s):

- All plain text files for any scheme: `{ langaugeId: 'plaintext' }`
- The scm input text area: `{ scheme: 'vscode', pattern: 'scm/**/input' }`

We also allow users to enable or disable trigger characters for each of these individually. However I cannot currently register separate completion item providers for these two because the language ids are the same

Using the two above schemes, the provider ends up being enabled twice inside the scm input. It seem unexpected that all plaintext based completions would end up in the scm input

**Ideas**
- Give scm inputs a pseudo language id, such as `scminput`.
- Let `DocumentSelector` use negation: https://github.com/Microsoft/vscode/issues/27051

**Comment by joaomoreno** [comment]
Created a `scminput` mode with mimetype `text/x-scm-input`.

**Comment by joaomoreno** [comment]
cc @alexr00

**Comment by jrieken** [comment]
verified in source
