### ISSUE TITLE
[CSS] Current color indicator freezes on old color

### ISSUE THREAD

**Issue by wUFr** [Microsoft/vscode#9132]
- VSCode Version: 1.3.0 (current stable)
- OS Version: Win 10 pro x64 - stable, updated

Steps to Reproduce: *im sorry, but i dont know how this happened :D* **, but problem appeared after new VSC release** 

Best way is to look on this screenshot from editor. Color indicator is present even if you remove value completely - have to remove whole line to get rid of it :)

![color](https://cloud.githubusercontent.com/assets/10975377/16770779/70206360-484e-11e6-9c5f-a53825732d10.png)

*sorry if its already reported, didnt have much time to look into all issues*

**Comment by aeschli** [comment]
If you find reproducible steps that would be awesome. But I looked at the code and found some possible causes. We only track the active editor (not all visible editor) and we don't clean up properly.

**Comment by wUFr** [comment]
could be related to VSC freezes in old 1.3.0 version, which are no longer present in 1.3.1
