### ISSUE TITLE
Show completion items that have already been returned while waiting for other slow completion item providers

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#91324]
Various plugins I have like the Flow plugin can be slow to provide completion items.  But some of my own extensions can provide completion items almost immediately, for example `Material-UI Snippets` providing `mui-button`.

When I'm trying to use my `mui-button` completion, it sucks to have to wait more than 10 seconds because other plugins like Flow are taking a long time to provide completion items.  Why not just go ahead and show the completion items that are ready, and add the stragglers as they finish?  It would be a big help.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest

**Comment by jedwards1211** [comment]
Help me as in there's some kind of configuration workaround?
