### ISSUE TITLE
If the default selected launch config is a compound, a different config is run when you click start

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91322]
- Open the vscode repo
- Set the "Gulp Build" launch config to be hidden by adding

```
"presentation": {
	"hidden": true
}
```

- Open code-insiders with a fresh user-data-dir
- Open the debug viewlet, see that "Debug VS Code Main, Renderer, and EH" is selected by default in the launch config picker ✔️ 
- Click the green triangle to start debugging
- The "Gulp Build" config is actually started 🐛

**Comment by isidorn** [comment]
Great catch and great steps. Thanks a lot for filling good issues.
