### ISSUE TITLE
Js-debug smoke test

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91326]
Another iteration, another js-debug sanity check! If you were on https://github.com/microsoft/vscode/issues/85984 or https://github.com/microsoft/vscode/issues/89393 and the tool assigns you, feel free to swap with someone else for fresh 👀 
 
 Please file issues on the js-debug repo: [click to file](https://github.com/microsoft/vscode-js-debug/issues/new)
 
 - [x] anyOS @dbaeumer  
 - [x] anyOS @weinand
 
 Complexity: 4
 
 ---
 
 ### Prerequisite
 
  - Install the latest `js-debug-nightly` extension from the marketplace.
  - Be on Insiders, of course :
 ### Node.js testing
 
  - Pick any Node.js project you have configured for debugging with VS Code
  - Prefix its launch config type with `pwa-`
  - Verify that you can *launch* the program and debug as usual:
     - The program launches
     - You can set breakpoints before and while the program is running, and they get hit
     - You can step into, out of functions.
     - Stack traces etc. display correctly.
     - Restarting the program works
     - Stopping the program works
  - Verify that you can *attach* to this Node.js process running in debug mode, and debug as usual.
 
 ### Debug Terminal
 
  - For any Node.js app without an complex launch.json, verify that you can launch the program and hit breakpoints using the debug terminal
  
     1. "Open Debug Terminal" from the command pallette
     2. Run your program via "npm start" and the like
 
 ### Edge Testing testing
 
  - Pick any browser/Chrome project you have configured for debugging with VS Code, with Edge installed
  - Changes it launch type to `pwa-msedge`
  - Verify that you can *launch* the project and debug as usual:
     - The browser launches and opens your project
     - You can set breakpoints before and while the program is running, and they get hit
     - You can step into, out of functions.
     - Stack traces etc. display correctly.
     - Restarting the program should refresh the page
     - Stopping the program should close the browser
  - Verify that you can *attach* to a running browser with your project open.
     - Note that you need to launch Chrome with special flags for this, on my machine: `/Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge --remote-debugging-port=9222 --user-data-dir=/tmp/chrome-debug`
 
 ### Extension Host testing
 
  - Pick any extension you have configured for debugging with VS Code
  - Prefix its launch config type with `pwa-`
  - Verify that you can launch the extension and debug as usual:
     - The extension host launches with your extension
     - You can set breakpoints before and while the program is running, and they get hit
     - You can step into, out of functions.
     - Stack traces etc. display correctly.
     - Restarting the extension reloads the extension host window
     - Stopping the program closes the extension host window

### Etc.

Play around with js-debug's features while testing, such as autocompletion in the debug console, debugging child processes/targets, and so on. Let us know if you run into issues!

**Comment by chrmarti** [comment]
@Tyriar Could you swap my assignment here with someone else's? I would test this the 3rd time. :)
