### ISSUE TITLE
This is an interesting and convenient experience.

### ISSUE THREAD

**Issue by DivenLee** [Microsoft/vscode#9133]
When we select our code, and then drag the selected part, you can move to the specified location.
Because windows has always been such a feature, so we have been accustomed to such an operation. But VSCODE is still no way to achieve such an operation, so that we are not accustomed to her.
If you agree, please add this function to us.

**Comment by weinand** [comment]
@DivenLee do you mean that VS Code does not support to move/copy text by dragging a text selection?

**Comment by DivenLee** [comment]
@weinand No, it is not. The contents of the file within the drag. You can drag the selection to the specified location, so that we do not need to copy the code and then paste into the desired position.

**Comment by eriawan** [comment]
@DivenLee please rephrase your issue's title. I think it's not clear enough, it's almost unrelated to the intent what you are trying to propose.

**Comment by weinand** [comment]
@DivenLee so you agree with my problem description?

**Comment by eriawan** [comment]
@weinand 
I suggest we should close this issue for now. We can reopen later if @DivenLee has given us more info.
