### ISSUE TITLE
Test new bots

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91333]
Refs: #91332

- [x] anyOS @gregvanl
- [ ] anyOS @bowdenk7
- [x] anyOS @chrmarti

Complexity: 2

---

The old bots could be tricked by the same account reacting with many different reactions. Additionally, the old bots didn't have any telemetry, so it was difficult to tell what they were up to.

We have a new bot deployed to the test repository at https://github.com/chrmarti/testissues/issues, ensure that it is not subject to the old bot's reaction bug (only one reaction is enough to promote an issue on that repo, so just make sure reacting to comments or reacting besides "+1" doesn't advance it.

Additionally the events should be logged to https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/asset/AppInsightsExtension/ApplicationInsights/subscriptions/9b16b0df-65b6-46d3-b9c9-e4fbc86b1fa7/resourcegroups/GitHub-Automation-Test/providers/microsoft.insights/components/probot-telemetry, still tbd on how to verify that. But if you poke around you should see that events are logged and they make sense.

**Comment by JacksonKearl** [comment]
@gregvanl @bowdenk7  This hasn't been deployed yet, will update with more information when it's out.

**Comment by chrmarti** [comment]
There is telemetry and it looks like it makes sense. The UI is difficult to navigate. Can this be queried with Kusto queries too?

**Comment by JacksonKearl** [comment]
Yes we will be changing the endpoint over to the global vS code telemetry endpoint when this goes stable.

**Comment by JacksonKearl** [comment]
@bowdenk7 this can be tested now, sorry for not updating earlier.

**Comment by Tyriar** [comment]
Closing out since it's too late in endgame now, this already has 2 check marks as well.
