### ISSUE TITLE
Test contributing timeline providers with paging from extensions

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#91330]
Refs: #84297

- [x] anyOS @connor4312 
- [x] anyOS @rebornix 

Complexity: 4

---

Similar to #89385.

Extensions can now contribute timeline providers to show time-series information in a new _Timeline_ view in the Explorer sidebar.

Develop an extension that can contribute a `TimelineProvider` to provide time-series information given a `Uri`. Here is an [example provider](https://github.com/microsoft/vscode/blob/master/extensions/git/src/timelineProvider.ts).

Here is the current API declarations:
https://github.com/microsoft/vscode/blob/2c9ce783fb3c696e5f633b8201d89349b58df7d2/src/vs/vscode.proposed.d.ts#L1547-L1710)

- For now, only test with 1 provider at a time because there are many known issues with multiple providers and paging. You can use the `timeline.excludeSources` setting to filter out the `git-history` source
- Implement paging in the provider
- Make sure there is a command contributed to each timeline item for the on click action.
- Contribute a command to the `timeline/item/context` for specific timeline items
- Try updating provider data after initial load (using `onDidChange`) and ensure the view is updated

**Comment by alexr00** [comment]
Blocked testing on https://github.com/microsoft/vscode/issues/91400

**Comment by weinand** [comment]
@eamodio same here, I cannot get my timeline items to show up. Please advise.

**Comment by eamodio** [comment]
@weinand Ensure you are returning a `Timeline` interface out of the `provideTimeline` method, since that seemed like it was the issue Alex was having.

**Comment by connor4312** [comment]
Started playing around will it, will finish my testing in the morning
