### ISSUE TITLE
Intelisense Ctl Space says No Suggestions

### ISSUE THREAD

**Issue by tyo-intel** [microsoft/vscode#91334]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by tyo-intel** [comment]
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-20-generic

**Comment by tyo-intel** [comment]
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by tyo-intel** [comment]
![extensions](https://user-images.githubusercontent.com/61440037/75205577-fb05ef80-5728-11ea-8b5a-195cfd73a888.PNG)

**Comment by tyo-intel** [comment]
I searched for related issues and didn't find anything related that solved this problem

**Comment by gjsjohnmurray** [comment]
What language are you coding in? Look at the indicator on the status line.

Is there some reason you aren't using the latest version of VSCode?

Does the problem also happen after you use VSCode's Command Palette to reload with all extensions disabled?

If yes, please give us step-by-step instructions about how to reproduce the issue. Screenshots, animated GIFs, or videos may be useful to show the problem.

**Comment by tyo-intel** [comment]
Found the problem:
autocomplete was Disabled
