### ISSUE TITLE
Issue with terminal.integrated.fontSize not displaying anything in terminal

### ISSUE THREAD

**Issue by sgornik** [Microsoft/vscode#9134]
- VSCode Version: Version 1.3.0, Commit e724f269ded347b49fcf1657fc576399354e6703
- OS Version: 3.13.0-91-generic #138-Ubuntu SMP

OS running is XUbuntu.

Steps to Reproduce:

1. Open Visual Studio Code
2. Open the terminal and there is nothing being shown in the terminal window.
3. Change "terminal.integrated.fontSize" to something not 0 and then it works.

Error is that "terminal.integrated.fontSize" is set to 0 which is supposed to be "editor.fontSize", but it does not get the value in a right way

![outfile](https://cloud.githubusercontent.com/assets/2914031/16771192/daad57b4-484f-11e6-931c-2a99db472afa.gif)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
