### ISSUE TITLE
Some multiline shell commands may incorrectly highlighted

### ISSUE THREAD

**Issue by GreenYun** [microsoft/vscode#91345]
- VSCode Version: 1.43.0-Insider
- OS Version: Ubuntu Desktop 19.10 (also tested with Window 10 1909)

Steps to Reproduce:

1. Select the language mode to "Shell Script"
2. Paste the following lines into the editor

```
comms=$(cat some_file.txt 2>&1 | while read -r line; do \
                                    printf "%s\n" "${line%%=*}="; \
                                done)
```

The issue comes that all the lines following these lines may be incorrectly highlighted, that it seems to consider the parentheses not closed. In fact the script can be run perfectly in shell, which mean the lines are legal.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by alexr00** [comment]
https://github.com/atom/language-shellscript owns this, but they are no longer maintaining the grammar.
If there is better/better maintained shell script grammar I can look at updating to that.

**Comment by alexr00** [comment]
Could be solved by https://github.com/microsoft/vscode/issues/77675, so closing in favor of that issue.
