### ISSUE TITLE
 [loc][Query][vscode-azure-sphere-tools] Localizability of string: 0; "./src/resources.errorConfigUnavailable"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#91349]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Error: Required azure sphere settings not found. Please configure in settings.json or run command 'Azure Sphere: Configure settings' to apply default settings.

File:
Src\vscode-extensions\vscode-azure-sphere-tools.xlf

Query:
Please, determine whether this command should be translated

**Comment by chrmarti** [comment]
Please check https://marketplace.visualstudio.com/ for the extension this belongs to.
