### ISSUE TITLE
How to show specified display language out-of-box?

### ISSUE THREAD

**Issue by tonyank** [microsoft/vscode#91347]
I have added a non-english language extension pack to vscode portable, and edited file: <VSCODE_HOME>\data\argv.json like this,
"locale": "ja"
then chose Japanese as display language.
But when I copy this vscode portable to another PC, I found the display language is still english. What else do I need to do so that vscode portable can display Jap out-of-box?

**Comment by dbaeumer** [comment]
The correct way to specify the locale is by running the command `Configure Display Language`. However I am not sure if this is correctly handled by a portable version.
