### ISSUE TITLE
Debug: 'Auto attach' does not work for new express app

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#91340]
Issue Type: <b>Bug</b>

**Repo**
1. Create simple express app: `npx express-generator`
1. Open the project in VS Code and enable auto attach
1. Try starting the app with `npm run start -- --inspect-brk`

**Bug**
I can't get auto attach to work. The debug controls show up and the progress indictor is active for around 10 seconds

I also do not know how to debug why it does not work. I can't find any logs for why it does not connect

VS Code version: Code - Insiders 1.43.0-insider (07c33977da255861edf71e65b18249d2f67d0762, 2020-02-24T05:32:20.492Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.50GB free)|
|Process Argv|-psn_0_6043075|
|Screen Reader|no|
|VM|13%|
</details>

**Comment by mjbvz** [comment]
I also tried using the feature with `create-react-app` but could not get it working either

**Comment by connor4312** [comment]
1.49 brought the arrival of a new, more durable auto attach. Please let me know if you run into problems with it.
