### ISSUE TITLE
[loc][Query][vscode-azure-sphere-tools] Localizability of string: 0; "package.azure-sphere-tools.azurespheredbg.launch.setupCommands.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#91348]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
One or more GDB commands to execute in order to setup the underlying debugger. Example: "setupCommands": [ { "text": "-enable-pretty-printing", "description": "Enable GDB pretty printing", "ignoreFailures": true }].

File:
Src\vscode-extensions\vscode-azure-sphere-tools.xlf

Query:
Should we localize "Enable GDB pretty printing"?

**Comment by chrmarti** [comment]
@PDostalek Please check with https://github.com/MicrosoftDocs/azure-sphere-issues. That seems to be the extension having that string.
