### ISSUE TITLE
 [loc][Query][vscode-azure-sphere-tools] Localizability of string:0; "./src/tree.error.update.code.model.on.nonexist.folder"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#91352]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Updating code model on folder that does not yet exist?

File:
Src\vscode-extensions\vscode-azure-sphere-tools.xlf

Query:
Please, explain better this sentence.
Do we need the question mark in this string?

**Comment by chrmarti** [comment]
Please check https://marketplace.visualstudio.com/ for the extension this belongs to.
