### ISSUE TITLE
[loc][Query][vscode-azure-sphere-tools] Localizability of string: 0; "./src/cmake-tools.please.upgrade.cmake"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#91354]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
For the best experience, CMake server or file-api support is required. Please upgrade CMake to {0} or newer.

File:
Src\vscode-extensions\vscode-azure-sphere-tools.xlf

Query:

Is "file-ap" translatable?
 We would say so by checking https://github.com/microsoft/vscode-cmake-tools/pull/720.

Same for cmake-file-api in following strings:

Cache object version ({0}.{1}) of cmake-file-api is unexpected.   
0; "./src/drivers/cmakefileapi/api_helpers.cache.object.version

"Code model version ({0}.{1}) of cmake-file-api is unexpected.
0; "./src/drivers/cmakefileapi/api_helpers.code.model.version"

**Comment by chrmarti** [comment]
Please check https://marketplace.visualstudio.com/ for the extension this belongs to.
