### ISSUE TITLE
VS Code Go to definition (command + click) not working unity

### ISSUE THREAD

**Issue by rohitvishwakarma1819** [microsoft/vscode#91350]
- VSCode Version: 1.42.1
- OS Version:  Mac OS Catalina 10.15.3 (19D76)

Steps to Reproduce:

1. Update Unity to 2019.2.0f6
2. Update VS code to 1.42.1 and try command + click on a function of another class

Does this issue occur when all extensions are disabled?: Yes

**Comment by Oddioengineer** [comment]
I have the same issue.
