### ISSUE TITLE
[loc][Query][vscode-azure-sphere-tools] Localizability of string: 0; "package.cmake-tools.command.cmake.cleanRebuildAll.title"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#91351]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Clean Rebuild All Projects

File:
Src\vscode-extensions\vscode-azure-sphere-tools.xlf

Query:
What does "Clean Rebuild All Projects" mean?
It can be "Clean 'rebuilding all projects'"?
Or "Clean-rebuilding 'all projects'"? (like "clean-installing")
Would you please confrim that "Clean" can be understood as 'completely' just like a 'clean boot?"

All the affected resource ids:

0; "package.cmake-tools.command.cmake.cleanRebuildAll.title"
0; "package.cmake-tools.command.cmake.outline.cleanConfigureAll.title"

**Comment by PDostalek** [comment]
Same questions for " Clean Reconfigure All Projects "

**Comment by chrmarti** [comment]
Please check https://marketplace.visualstudio.com/ for the extension this belongs to.
