### ISSUE TITLE
Go To Definition should support Webpack resolve paths

### ISSUE THREAD

**Issue by methyl** [Microsoft/vscode#9135]
Currently Go To Definition works perfectly well for relative paths within application, eg:

```
import something from './something'
```

However, after I add some resolve paths in Webpack config, like

```
  resolve: {
    root: [
      path.resolve(rootPath, 'app/frontend/lib'),
```

I can import files like this

```
import something from 'something'
// instead of 
// import something from 'app/frontend/lib/something' or
// import something from '../../lib/something'
```

The problem is that VSCode won't follow these resolve paths.

The solution could be to add configuration which will define additional resolve paths for Go To Definition functionality.

**Comment by dbaeumer** [comment]
Might be solveable with the new baseURL support in TS 2.0. Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9667

**Comment by methyl** [comment]
@dbaeumer will this also work for JS then?

**Comment by dbaeumer** [comment]
The TypeScript server is the backbone for the JS smartness as well.

**Comment by jake-daniels** [comment]
Hi @dbaeumer, 
How can I make this feature work when I'm using JS, not TypeScript?
I have `jsconfig.json` file inside `.vscode` folder:
```
{
    "compilerOptions" : {
        "target" : "es6",
        "pretty" : true,
        "experimentalDecorators" : true
    },
    "files" : [
        "../src"
    ]
}
```
Adding `"baseUrl": "app/frontend/lib"` doesn't work, VSCode displays `Property baseUrl is not allowed.`

**Comment by olafahn** [comment]
Hello, @dbaeumer !
this feature seems not working for me.

i checked my vscode version, (1.7.2) which uses typescript server 2.0.10
and i also tried to use `typescript@next` for my vscode,
but vscode hint me with underline as **Property baseUrl is not allowed.**

so i changed jsconfig.json => tsconfig.json,
then add allowJs true at compilerOptions, but still not working.
is there anything else that i'm missing?

(p.s. I really enjoy coding with vscode. Thank you! * 10000)

**Comment by dbaeumer** [comment]
@olafahn can you please open an issue here Microsoft/TypeScript or comment on the moved issue Microsoft/TypeScript#9667.

**Comment by AndrewRayCode** [comment]
For the Googlers (this was the first result in Google for me), [I made a writeup](http://blog.andrewray.me/autocomplete-es-modules-webpack-vscode/) on how to accomplish this.  TL;DR add 

```
{
  "compilerOptions": {
    // This must be specified if "paths" is set
    "baseUrl": ".",
    // Relative to "baseUrl"
    "paths": {
      "*": [
        "*",
        "mypath/*"
      ]
    }
  }
}
```

to your jsconfig.json or tsconfig.json in your project's root
