### ISSUE TITLE
Suggestion: Markdown settings for highlightjs theme

### ISSUE THREAD

**Issue by jods4** [Microsoft/vscode#9136]
The markdown extension uses `highlight.js` for code highlighting, which comes with many themes inside its `styles` folder.

Yet, the default theme (`tomorrow.css`) is hardcoded here:
https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/extension.ts#L237

It is possible to override this by finding and copying the theme you like into your project and referencing the file with `markdown.styles` settings. This work but it's not easy/intuitive and it does not actually remove the `tomorrow` rules/stylesheet from the document (which can provide some unwanted defaults).

I suggest that you make the default theme easily changeable with a new settings, maybe `markdown.highlightStyle: "tomorrow"` and support all the hightlight.js built-in styles.

BTW I think `tomorrow` is a _very colorful_ choice for a default settings, but that's just my taste.

**Comment by mjbvz** [comment]
Closing in favor of #22916 Let me know if you are interested in developing a markdown extension that can provide this functionality

**Comment by jods4** [comment]
Sorry, I don't have the time to look into VS Code extensions, although that looks like an exciting area.

If I had more time, I would surely try to add AsciiDocs support. There are some extensions in the market place but only one supports preview and it needs a globally installed Python AsciiDoctor, even though a perfectly fine AsciiDoctor.js exists!?

I've recently come to love AsciiDocs as a much better LML than Markdown.
