### ISSUE TITLE
Collapsed view can load before other views in a container and get expanded, even though the real top view will load shortly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91367]
Currently it shows quite prominently.

**Comment by isidorn** [comment]
I also provided feedback in the UX call that this view should be shown not be in the Explorer.
Potentialy SCM (even though I uderstand that not all of it's functionality is realted to scm)

**Comment by sbatten** [comment]
To verify:

1) Ensure that timeline is in the explorer viewlet along with the file explorer.
2) Hide all other views in the viewlet.
3) Create a new empty folder somewhere on your disk.
4) Open this folder with VS Code.

Ensure that timeline is visible in the explorer viewlet but collapsed.
