### ISSUE TITLE
Undo/Redo: better name for "Workspace Edit"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91369]
Refs: #91248 

If I do a "Rename" workspace edit, we should ideally use that as a label over the generic "Workspace Edit".

**Comment by jrieken** [comment]
This will also be helpful for refactor preview

**Comment by jrieken** [comment]
In fact, there already is `IBulkEditOptions#label` and rename sets a value for it

**Comment by alexdima** [comment]
This looked low hanging, so I just tackled it.

**Comment by jrieken** [comment]
I have pushed another change that makes code actions also set a label

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/75468568-b333d200-598d-11ea-8dfc-d5adaa07e0ca.png)

Still a clash of quotes, but that is just polish or we leave it.

**Comment by alexdima** [comment]
@bpasero I tackled that in a different issue with feedback from you, but I don't think there is an insiders available yet.

**Comment by bpasero** [comment]
@alexdima ah ok good, thanks!
