### ISSUE TITLE
Could not undo 'Workspace Edit' across all files.

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#91379]
re #91248

* don't use workbench tabs
* java-8 dev container
* in `AppTest.java` add a reference to `App`, like `assertTrue(new App().equals(new App()));`
* from `AppTest.java` rename `App` to `App2`
* undo
* 🐛 seeing the message below, the file `App.java` seems to have been disposed/closed already

```
Could not undo 'Workspace Edit' across all files. The following files have been closed: /workspaces/vscode-dev-containers/containers/java-8/test-project/src/main/java/com/mycompany/app/App.java.
```

**Comment by alexdima** [comment]
The root cause is that currently, when a TextModel is disposed, the undo/redo stack elements associated with that resource are dropped.

I suggest we track in #7169 which is a precursor to support this.
