### ISSUE TITLE
Undo/Redo: notification for not being able to apply undo is not very helpful

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91371]
Refs: #91248

Talking about:

![image](https://user-images.githubusercontent.com/900690/75248329-46c1a300-57d4-11ea-9b75-0af3231783b4.png)

I wonder how helpful this is for the user to show. I doubt a user would have a model of the undo/redo stack in mind, so it would appear as if suddenly undo would be stuck once and then continue to work again.

Maybe we should bring this up to the UX meeting at one point. Would it make sense to simply jump over this undo step when we cannot apply it or apply it only for the current file if possible?

**Comment by bpasero** [comment]
Similar problem exists for the other case of where an editor is closed that was part of the undo/redo stack.

**Comment by alexdima** [comment]
Today, if the cross-file undo cannot be applied, the pop-up is showed and nothing happens.

Let me change this to show the pop-up and also execute the local undo (in the current file).
