### ISSUE TITLE
Icons don't form a connected line

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91376]
Testing #91329

The icons for the entries in the timeline view are not connected

![image](https://user-images.githubusercontent.com/5047891/75252516-22b68f80-57dd-11ea-9689-f799e39d5731.png)

I have seen this representation in other tools, but in there the rendering is slightly better, with the dots being connected:

![image](https://user-images.githubusercontent.com/5047891/75252582-48dc2f80-57dd-11ea-9db1-a00c157d6c71.png)

**Comment by eamodio** [comment]
The commit icon is just the icon provided by the Git timeline provider (and the fact that our commit icon is vertical rather than horizontal). As other providers are mixed in there will be many different icons in that space.
