### ISSUE TITLE
Set environment variables for extensions when VS Code is not launched via terminal 

### ISSUE THREAD

**Issue by tsnobip** [microsoft/vscode#91372]
Sometimes, we want VS Code extensions to have access to customized environment variables. 

This is doable via `terminal.integrated.env.osx` setting for the integrated terminal but these variables are not accessible by the extensions. 

A workaround when VS Code is launched via terminal is to set the variable before calling code like this: 
```FOO=Value code .``` 
but this is not doable when launching it via the shortcut and it can be nice to have this value set per workspace.

Somehow duplicate of #69728.

**Comment by joaomoreno** [comment]
What's the example here?

**Comment by tsnobip** [comment]
I don't know how common my use case is, but I use vscode for Ocaml (more precisely Reason but it's pretty much the same) and the extension we use to have intellisense and LSP support also builds the project. Sometimes we want to pass flags to the compiler and one way to do that is by using env variables, it works very well when building on the terminal but there's no way to do this when using the extension. Do you need more details or use cases?

**Comment by joaomoreno** [comment]
Does the extension spawn the compiler? Why doesn't the extension have an ocaml-specific setting for you to provide extra env variables?

**Comment by tsnobip** [comment]
Yes the extension spawns the compiler.
I guess it'd be doable to have it as a setting of the extension, I just thought adding this option in vscode itself would be a more generic solution. Especially since the OCaml/Reason/Bucklescript extension scene is a bit scattered at the moment, so it would require to update multiple extensions. These flags are often used by PPXes which are basically extensions of the compiler, so it's hard to have a solution that can cover all the use cases.

**Comment by joaomoreno** [comment]
OK, I'll close this with the recommendation to create said setting in the extension. Thanks for the clarification!
