### ISSUE TITLE
Replace <sha>^ with the previous sha (or something more acceptable) in the diff editor title

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91377]
Testing #91329

When viewing the timeline for a file, and clicking on the item, the title looks like:
![image](https://user-images.githubusercontent.com/5047891/75252726-8640bd00-57dd-11ea-8bfd-51d073e8d190.png)

Two things stand out:
* there appears to be a unicode string encoding issue, where the unicode code point is escaped `\u27f7`
* the same commit sha is rendered twice, once with `sha^` format, which is very technical and not user friendly IMHO. I recommend to try to render the sha only once.

**Comment by eamodio** [comment]
I've fixed the encoding problem, but will still need to address the previous sha (`<sha>^`) issue
