### ISSUE TITLE
Support file operations (create, rename, delete) in cross file undo

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#91383]
re #91248

This is a feature request (or request for complete feature) so that things like "Java-class rename" or "TS extract to new file" refactorings can be undone safely

**Comment by jrieken** [comment]
I have enabled undo for rename operations. What's still missing

* [ ] file and text undo element aren't connected yet, e.g TypeScript's "Move to new file" or the Java class rename, need two undos
* [ ] undo is always driven by the active editor which means delete file has no "UX hook" for its undo operation

**Comment by jrieken** [comment]
To verify:

* have a Java project
* rename (F2) a class name so that its file name changes
* press undo _two times_ and make sure every thing is bad to normal
* to the same with TypeScript and "move to new file"

Note the comment above with means two undos, one for textual and for file operations, are needed. This is temporary!

**Comment by connor4312** [comment]
Java works fine, but for TS:

 1. Create `x.ts` with `function foo() {}`
 2. Refactor `foo` and move to new file. It moves it to a new foo.ts file ✔️ 
 3. Undo it. Accept `Undo in 2 Files`
 4. The function is copied back to x.ts, but foo.ts still exists 🐛 

![](https://memes.peet.io/img/20-07-efd9ec18-9dea-4f29-a812-a43e8a0af4be.png)

**Comment by jrieken** [comment]
> The function is copied back to x.ts, but foo.ts still exists

Yeah, that's expected. You need another undo inside the foo.ts files. That should delete it. The issue is that there are two operations that aren't linked together: a textual operation spanning two files, and a file create operation. Because both aren't "connected" undoing in x.ts only undos the textual operation, unding in foo.ts will undo the file operation. 

What puzzles me is how you got the notification about foo.ts being modified on disk?

**Comment by connor4312** [comment]
One thing is that I have the prettier extension installed. All of my "Format On *" options are turned off, but I noticed that if I type

```js
function foo() {}
```

The function in the moved file is


````js
function foo() { } // <- with a space
```

Which looks like formatting happened at some point.

I will remove the verified tag and let someone else take a shot at this.
