### ISSUE TITLE
A lot of repetition in timeline view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91382]
![image](https://user-images.githubusercontent.com/2193314/75254197-d6476180-5794-11ea-8580-2d9520073987.png)

Might be worth exploring something like this?

![image](https://user-images.githubusercontent.com/2193314/75254368-1dcded80-5795-11ea-8762-ae9338d76fb4.png)

Also spelling out the actual word might be better? months instead of mos, etc.

**Comment by eamodio** [comment]
Yeah, I had an experiment that was very close to that, but I haven't been able to figure out a way to implement it properly. The main issues are ensuring that the first item in the view always has a timestamp and that as time ticks on deal with items that change groupings
