### ISSUE TITLE
Process explorer isn't working

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91384]
![image](https://user-images.githubusercontent.com/2193314/75255197-65a14480-5796-11ea-8612-b03be29db288.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by RMacfarlane** [comment]
I wasn't able to repro this, but I have checked in a fix that should avoid a NPE. Also created a follow up issue to investigate why/how a null value was passed here in the first place.
