### ISSUE TITLE
Extension API: Add support for targeting nested folders

### ISSUE THREAD

**Issue by shaneparsons** [microsoft/vscode#91385]
I'd like to be able to control the icons of nested folders, and I've been told that support for such functionality needs to be added to your "Extension API".

Please see [this issue](https://github.com/PKief/vscode-material-icon-theme/issues/645) and [this issue](https://github.com/PKief/vscode-material-icon-theme/issues/631) for more background.

**Comment by aeschli** [comment]
dup of #12493
