### ISSUE TITLE
Minimap indication and scrollbar have different height

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#91387]
Testing: https://github.com/microsoft/vscode/issues/91250

Setting `"editor.minimap.mode": "contain"`

Observe: the minimap scroll indication and the scrollbar handle have different height. Should they be the same in that mode.

<img width="100" alt="capture" src="https://user-images.githubusercontent.com/1931590/75256546-df135400-57e3-11ea-8405-63cc58316253.png">

**Comment by IllusionMH** [comment]
Scroll bar has minimal height for large files, and if minimap shrinks to fit all content it wont be definitely smaller that scroll.

**Comment by alexdima** [comment]
Indeed, they normally would be the same height. But the scrollbar slider is artificially inflated to a minimum height (20px) to make it possible to easily grab it with the mouse
