### ISSUE TITLE
Rendering rule annotation (e.g. changed lines) in minimap and scrollbar is confusing

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#91389]
https://github.com/microsoft/vscode/issues/91250

Mode: `"editor.minimap.mode": "cover"`

Observer that the changed line annotation is rendered in the scroll bar and the minimap. I found that confusing and first thought it is a rendering bug.

<img width="184" alt="capture" src="https://user-images.githubusercontent.com/1931590/75257632-88a71500-57e5-11ea-9f81-78529e5ca94a.png">

**Comment by alexdima** [comment]
This is intentional. There are other decorations, like errors, warnings, find matches, cursor position which are rendered in both places.

We could add an option to hide the scrollbar and the overview ruler entirely at #28653 , so I suggest we track in #28653.
