### ISSUE TITLE
Sync: Documentation link points to the wrong place

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#91393]
Testing #91226 on Windows

Turning on Sync for the first time shows a prompt with a `Open Documentation` button which points to:

https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

This seems like the wrong link

**Comment by joaomoreno** [comment]
@sandy081 Also, the second button should be `Turn On Sync` instead of `Continue`, which is ambiguous.

**Comment by joaomoreno** [comment]
Oh just read it:

> Also note that the documentation link is in progress hence it is currently pointing to a wrong location.

**Comment by Tyriar** [comment]
@sandy081 currently placeholder link in the docs repo is https://code.visualstudio.com/docs/editor/settings-sync

**Comment by sandy081** [comment]
Yup, I think we need a short link for this.
