### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by azoh** [Microsoft/vscode#9139]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Does anyone have a similar problem?
http://i.imgur.com/J4fEopn.jpg

**Comment by mrmlnc** [comment]
Have you tried this [instruction](http://code.visualstudio.com/docs/setup/windows#_common-questions)?

**Comment by mrmlnc** [comment]
Have you tried this [instruction](http://code.visualstudio.com/docs/setup/windows#_common-questions)?

**Comment by mrmlnc** [comment]
Have you tried this [instruction](http://code.visualstudio.com/docs/setup/windows#_common-questions)?

**Comment by wUFr** [comment]
no problem here, you could try switching Theme tho

**Comment by bpasero** [comment]
@azoh does this help? http://code.visualstudio.com/docs/setup/windows#_common-questions

**Comment by azoh** [comment]
thanks a lot, it helped
