### ISSUE TITLE
password description needs polish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91399]
refs: #91152

"Set to true to show a password prompt that will not show the typed value."

We usualy use the term `controls` if it is a boolean, we do not nudge the user to set it to `true`.
Also there seems to be one negation at the end which might overcomplicate what you are trying to say.

All in all, I suggest the following
"Controls if a password prompt is shown. Password prompt hides the typed value."
Or some variation of that, consider using "text" instead of "value"

**Comment by alexr00** [comment]
This is directly copied from the quick input API documentation. @chrmarti, do you mind if I change it there too: "Controls if a password input is shown. Password input hides the typed text."

**Comment by chrmarti** [comment]
@alexr00 Yes, please. Thanks!
