### ISSUE TITLE
Unity UI is not working with intellisense

### ISSUE THREAD

**Issue by Stax124** [microsoft/vscode#91394]
Issue Type: <b>Bug</b>

using UnityEngine.UI is not working with current intellisence. I´m using latest Unity version with latest Visual Studio Code plugin installed. Unity still reads that with no problem but here it shows me more than 60 errors.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.61GB free)|
|Process Argv|C:/Users/tamon/Desktop/Coding/Unity/Tutorial -g C:\Users\tamon\Desktop\Coding\Unity\Tutorial\Assets\Scripts\SettingsButtons.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.20.0
vscode-firefox-debug|fir|2.6.1
vsc-python-indent|Kev|1.8.1
unity-code-snippets|kle|1.3.0
csharpfixformat|Leo|0.0.84
python|ms-|2020.2.64397
remote-wsl|ms-|0.42.3
cpptools|ms-|0.26.3
csharp|ms-|1.21.12
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
unity-tools|Tob|1.2.3
material-theme|zhu|3.2.3

</details>

**Comment by roblourens** [comment]
Please file this on the repo for the C# extension: https://github.com/OmniSharp/omnisharp-vscode
