### ISSUE TITLE
Hard to read results when there are many matches on a line

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91392]
Not sure if this has come up, but for this case it's tough to parse the results because:

- The text in the results changes for every entry, making it harder to realize the match is on the same line
- It takes up a lot of vertical space 

![image](https://user-images.githubusercontent.com/2193314/75258875-fb8b9e00-579b-11ea-8959-e74fd0c681fc.png)

Might be worth exploring merging them into a single line and selecting all the matches on that line when you click?

**Comment by roblourens** [comment]
It has come up before, I don't want to do that because it will result in matches being hidden, 1 row per match is probably easier for the user, and now you should try our new search editor which has the behavior you expect 😁
