### ISSUE TITLE
Evaluable expression API - comments feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91404]
#91268

Looking at the `EvaluatableExpressionProvider` API and docs I have the following feedback:
* "The evaluatable expression provider interface defines the contract between extensions and the debug hover". Contract between sounds very general. I would try to find something more understandable
* "debug hover is opened" sounds a bit unfitting to me. It is not like users open the debug hover. "debug hover is used" or something in that manner
* The lack of a result can be signaled by returning `undefined` or `null`. Should we make this more strict to only allow by spec one of those?

**Comment by gjsjohnmurray** [comment]
>     * "debug hover is opened" sounds a bit unfitting to me. It is not like users open the debug hover. "debug hover is used" or something in that manner

Maybe this:
```
* @param document The document in which the debug hover appears.
* @param position The document position for which the debug hover appears.
```

**Comment by weinand** [comment]
I tried to align the documentation (comments) with the existing documentation for hovers (which is probably similar to even more APIs). So if we change one, we will have to change all of them to keep them aligned.

**Comment by isidorn** [comment]
If all the other hovers use the same docs then it makes sense to be aligned.

**Comment by isidorn** [comment]
It would be great if we add some comments to clarify that this is really an evaluable expression and not the result of the evaluation. I think this can confuse some API users as it confused me.

**Comment by isidorn** [comment]
The updates to the docs look good to me. Thanks!
