### ISSUE TITLE
Replace doesn't work with regex lookahead or lookbehind

### ISSUE THREAD

**Issue by ThubLives** [Microsoft/vscode#9140]
- VSCode Version: 1.1.0
- OS Version: Windows 7 SP1

Steps to Reproduce:
1. Highlight string "A B C D E F"
2. Search string "\s(?=\w)" replace string "\n"
3. Click replace all button.

Nothing changes.  Note that the spaces between the letters do match and the parser will cycle through them with the arrow buttons.  If you change to lookbehind (i.e. move the whitespace to the end) nothing will match.

**Comment by IllNate** [comment]
I would also like to see vscode support lookbehind regex

**Comment by alexandrudima** [comment]
Lookaheads already work today (i.e. the example in the OP's comment).

Lookbehinds will come once v8 implements them, I think they are in the ES6 spec.

Closing because there is nothing actionable on our side.

**Comment by dbaeumer** [comment]
Verified that lookahead already works.
