### ISSUE TITLE
Evaluatable expression off by one in range computation

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91406]
Refs: https://github.com/microsoft/vscode/issues/91268

1. Use the mock debug evaluatble expression API
2. Hover over some word
3. Notice how the range highlight in the editor is 1 character shorter than it should be. WHile the extracted result is correct

Upon looking at the mock debug implementation it seems like Mock debug incorectly returns a Range shorter by 1. And it seems like vscode properly shows this in the higlighted background, however the result extraction takes 1 character too much.

Contrast is not so strong but this picture shows the issue. `y` in `funcitonlaity` is not highlighted, while funcitonlaity is extracted as the result.
![Screenshot 2020-02-25 at 16 37 06](https://user-images.githubusercontent.com/1926584/75262617-133f4280-57ed-11ea-9dcc-a1f1ea362b69.png)

**Comment by connor4312** [comment]
I'm seeing that the `EvaluatableExpression` seems to take one character too much off the word. In the simple test case:

```
  vscode.languages.registerEvaluatableExpressionProvider('javascript', {
    provideEvaluatableExpression(document, position) {
      const word = document.getWordRangeAtPosition(position)
      return new vscode.EvaluatableExpression(word);
    },
  });
```

Hovering over the `console` in a `console.log()` correctly selects the word "console", but over DAP I see an evaluate request for `console.`

**Comment by weinand** [comment]
Great find (because of the weak contrast of the selection color I did notice the selection being off-by-one).
Please note: the fix is both in VS Code and Mock Debug.
