### ISSUE TITLE
Sync: "Show Activity" should be called "Open Log"

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#91409]
Testing https://github.com/microsoft/vscode/issues/91226 on Windows

When searching for `sync log` in the command palette, nothing comes up.

**Comment by sandy081** [comment]
Sync log has sync activity and hence called it `Sync: Show Activity` and thought there is more probability that users click on this button to see the activity.

To open a logs we already have a command `Developer: Show Logs`. 

So please let me know if there is any confusion going with existing command.

**Comment by gjsjohnmurray** [comment]
I agree with @joaomoreno that it would help to put the word 'Log' in the command name.

**Comment by joaomoreno** [comment]
@sandy081 No confusion. It's just bad if user's can't find anything when they type `sync log` in the command palette.

**Comment by sandy081** [comment]
It is just experimenting out. Changed `Sync: Show Activity` to `Sync: Show Log`.
