### ISSUE TITLE
Strange activation notification when opening ESLint extension

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#91407]
1. Install ESLint extension
2. Click it in the extensions viewlet

This notification comes up:

![image](https://user-images.githubusercontent.com/22350/75262633-1803f680-57ed-11ea-82b0-e42130afa091.png)

**Comment by connor4312** [comment]
This is fixed in https://github.com/microsoft/vscode/commit/b304296e82305e082d8520c0027641e12167b9d3, Ben [mentioned it on Slack](https://vscodeteam.slack.com/archives/G1C2N25T8/p1582642347003100)
