### ISSUE TITLE
Allow dropping views within the entire part (sidebar or panel)

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91419]
Refs: https://github.com/microsoft/vscode/issues/91335

Drag a view, like the open editors view and drop it into the panel area
Notice how there is no effect, you have to actually drop it in the Panel Title area.
I understand how this makes sense from the implementation persepctive, however this makes the feature pretty undiscoverable and potentially broken for the users.
I believe the whole part should be the drop target. So either the panel or the sidebar...

**Comment by sbatten** [comment]
definitely agree, current design is a function of implementation and should be improved.

**Comment by sana-ajani** [comment]
And vice versa? Take a view in the panel and be able to drop it in the Explorer area, instead of dragging it to the Explorer icon.

**Comment by sbatten** [comment]
also done
