### ISSUE TITLE
Move debug toolbar location to Call Stack

### ISSUE THREAD

**Issue by DanielPower** [microsoft/vscode#91411]
Currently, the debug toolbar can be floating (default), docked, or hidden. 

The default floating position is annoying because it covers part of the editor, or tab bar.

The docked position is better, but if you have multiple debuggers open, and your sidebar is narrow, you lose the kebab menu, and can no longer open new debuggers, and also it becomes difficult to see which debugger is selected if multiple have similar names.

But notice that when you have multiple debuggers open, they also go into the Call Stack, and you can hover them to see their individual controls. This is the perfect solution in my opinion, but unfortunately, debuggers only appear in the Call Stack when multiple are open.

In my opinion, even when only one debugger is running, it should appear in the call stack, then the debugger toolbar can be set to hidden without losing functionality.

![Screen Shot 2020-02-25 at 12 25 32 PM](https://user-images.githubusercontent.com/12166320/75264409-f2192a80-57c9-11ea-92dc-717febb1748f.png)

This would be the desired behavior:
![Screen Shot 2020-02-25 at 12 29 36 PM](https://user-images.githubusercontent.com/12166320/75264821-8c796e00-57ca-11ea-9488-297a7dbdb141.png)

Note that this currently works great when multiple debuggers are running, but if only one debugger is running, it does not appear in the Call Stack.

**Comment by isidorn** [comment]
This is very good feedback.
And I do agree with this. Thus assigning to Backlog as we might tackle in the future.
An elegant PR which tackles this is also welcome
