### ISSUE TITLE
Drop feedback is missing when dragging views

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91418]
Refs: https://github.com/microsoft/vscode/issues/91335

Take a view, for example Open Editors view and start Dragging it
Notice how there is no drop feedback on what the legal targets are.
Due to this it is very hard for the user to discern where he or she can drop the view

Good example of nice drop feedback: Explorer when DnD files

**Comment by sbatten** [comment]
There is similar hover feedback to the explorer when dragging views into the activity bar and composite. 
![image](https://user-images.githubusercontent.com/6561887/75270387-51b60c80-57af-11ea-8f22-c89161d374f5.png)

This seems similar to the explorer.

I want to add some pre-hover feedback, e.g. a transparent color above the whole activity bar and panel header area when you start dragging to improve this.

**Comment by isidorn** [comment]
Agree, some transaparent color would be great.

**Comment by sbatten** [comment]
I think this is addressed after all the changes done
