### ISSUE TITLE
second level groups are not automatically expanded

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#91417]
Testing #91095:

- use vscode-mock-debug project
- change the code in mockDebug.ts:85 to
  ```ts
			if (text === 'start' || text === 'startCollapsed') {
				e.body.group = text;
				e.body.output = `group-${text}\n`;
			}
			if (text === 'end') {
				e.body.group = text;
				e.body.output = ``;
			}
  ```
- use a readme.md file with this content:
  ```
  log(start)
  log(arbitrary line of text)
  log(start)
  log(arbitrary line of text level 2)
  log(another line of text level 2)
  log(end)
  log(another line of text)
  log(end)
  ```
- run the mock session with F5
- step through the test input line by line

Observe:
second level nodes are not automatically expanded:
![2020-02-25_17-45-23](https://user-images.githubusercontent.com/1898161/75267513-9fa23300-57f6-11ea-9f7f-3716da8c064b.png)

**Comment by connor4312** [comment]
For me the first level groups are not automatically expanded either, running the latest from sources

![image](https://user-images.githubusercontent.com/2230985/75381115-0a05b280-588d-11ea-80b8-e1c7b5ec4606.png)

**Comment by isidorn** [comment]
I am not happy with the implementation of auto expand on my side, assignign to next milestone to look into a cleaner solution then.
