### ISSUE TITLE
Cannot download extensions

### ISSUE THREAD

**Issue by aedrax** [Microsoft/vscode#9141]
- VSCode Version: 1.3.0
- OS Version: Linux Mint 18 64 bit
- Kernel: 4.4.0-28-generic

Steps to Reproduce:

1. Open Visual Studio Code
2. Open Extension Manager
3. Search for any extension
4. Click install and nothing happens

I'm not sure if this has anything to do with it but the console is outputting the following
`shell.ts:416 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)`

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408
