### ISSUE TITLE
Select a destination area for the view feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91422]
Refs: https://github.com/microsoft/vscode/issues/91335

![Screenshot 2020-02-25 at 18 06 49](https://user-images.githubusercontent.com/1926584/75269719-a2525780-57f9-11ea-8423-3a407227ff82.png)

1 . There is no need for `...` at the end of message
2. Start each word with Upper Case: "Select a Destination Area for the View"
3. Always preselect the part that the view is in, or is not. But do not default select sidebar always
4. "Sidebar" should be "Side Bar"

**Comment by isidorn** [comment]
Same feedback for this message
![Screenshot 2020-02-25 at 18 11 16](https://user-images.githubusercontent.com/1926584/75270086-420fe580-57fa-11ea-9fa4-434f7b75e574.png)


Actually consider just mergeing this two dialogs into one and using groups to group options together. First the Side Bar options than the Panel options

**Comment by isidorn** [comment]
Can not verify this since the move focused view command now never works for me (already captured in the seperate issue). `There is no view currently focused`

**Comment by sbatten** [comment]
To verifier: You must use a keyboard shortcut to run this command. In the next insiders build, it will not show up in the command palette to avoid confusion.
