### ISSUE TITLE
Print or Export Outline

### ISSUE THREAD

**Issue by sharkweek** [microsoft/vscode#91424]
I tried searching the feature requests for this but couldn't find anything, so please forgive me if the request exists elswhere.

It would be really useful if there was an option to export the Outline as text or copy it to the clipboard. Something that would work similarly to the [Show Functions](https://marketplace.visualstudio.com/items?itemName=qrti.funclist) extension but would be native and have the same fidelity of the Outline. For example--thinking in C++--it could give you the option of exporting only variables or classes, or only declarations without definitions, or only objects of certain types, etc. Even if it was just a straight copy of what's shown in the Outline would be great and could be parsed manually afterward.

This would be super helpful for creating documentation and also as a more "qualitative" search tool.

**Comment by jrieken** [comment]
This is cool idea for an extension, and also easy to do: Use the `vscode.executeDocumentSymbolProvider`-api command (like in this [test](vscode.executeDocumentSymbolProvider)) and you'll have the outline of a file.

**Comment by sharkweek** [comment]
Thanks!
