### ISSUE TITLE
There is no view currently focused

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91423]
Refs: https://github.com/microsoft/vscode/issues/91335

Move a view via a "Move a focused view" command
Once the view is moved notice how the focus is still on the view
Trigger the command again -> get the `There is no view currently focused` error.
Please try it a couple of times, I do not repro 100%

**Comment by sbatten** [comment]
I hit this too, there is something wrong with the context key, need to investigate.

**Comment by isidorn** [comment]
I can still reproduce this with VSCode 0eebaf9ad23748baca2afc0da425650922bc23de
Which seems to contain the fix. Thus reopening

**Comment by sbatten** [comment]
@isidorn I can use the command, were you trying to do it from the command palette? If so, the command palette steals focus so it won't work there. The above commit will keep it from appearing there to avoid confusion.

**Comment by isidorn** [comment]
You are correct. And yes it should not appear there
If I use the shortcut it works fine -> verified
