### ISSUE TITLE
snippets don't expand on long lines

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#91427]
Issue Type: <b>Bug</b>

In a line of a file that's long enough to not have syntax highlighting, snippet expension does not work either.  I had an XML file, formatted for small size instead of readability, and with a custom snippet that normaly expands on "e", I instead got a pair of "em" tags.  If I added a couple of line breaks such that I had syntax highlighting, and tried again, then I got my custom snippet.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
Yes - we have done this on purpose. I don't recall the exact reasons but it is because snippet completions need to loop over the current line prefix. Tho, we might be able to find a better solution here. Having said that, you can always use "F1 > Insert Snippet"

**Comment by roblourens** [comment]
I wasn't able to repro the original issue in stable, is it just

- Have an extremely long line
- At the end of it, trigger suggest
- Pick a snippet

It seems to expand fine

**Comment by roblourens** [comment]
Ping @jrieken

**Comment by jrieken** [comment]
Trigger IntelliSense on column 10001 or higher and make sure that you see snippet suggestions
