### ISSUE TITLE
.Ipynb with kernelspec error under VSC

### ISSUE THREAD

**Issue by Ensae2018** [microsoft/vscode#91428]
Hello, 

  I ve tried to run some .ipynb files under VSC, but I have always a trouble with the error "kernelspec" (see picture). I have removed jupyter and installed it again, but no success. Anyone can help?
Regards

- VSCode Version: 1.42.1
- OS Version: Windows 10
![Capture](https://user-images.githubusercontent.com/44882917/75271102-f1998780-57fb-11ea-8c49-ee5252605ee4.JPG)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
