### ISSUE TITLE
Code formatter Jumps Back to Cursor Location

### ISSUE THREAD

**Issue by alaswer** [microsoft/vscode#91430]
Issue Type: <b>Bug</b>

When I hit Shift+Option+F on Mac, the formatting is done as it's supposed except the view is taken back to where the cursor is.. and that is annoying, sometimes when I format code I'm usually reading it or something, not typing, so I want to format and keep reading the exact part of the code before I hit the above shortcut, but instead to jumps back to the location of the cursor (which where I left it earlier before formatting)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.2.0

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.14
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
vscode-ionic-snippets|fiv|2.0.2
angular-essentials|joh|9.0.1
Angular2|joh|9.1.1
vscode-peacock|joh|3.4.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
angular2-inline|nat|0.0.17
angular-console|nrw|11.1.3
material-icon-theme|PKi|3.9.3

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
