### ISSUE TITLE
instanceLimit doesn't seem to work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91438]
#91154

![image](https://user-images.githubusercontent.com/2193314/75275905-13721a80-57ba-11ea-97f5-c01575258cc8.png)

I just added instanceLimit to the first task in vscode:

```
{
			"type": "npm",
			"script": "watch",
			"label": "Build VS Code",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"problemMatcher": {
				"owner": "typescript",
				"applyTo": "closedDocuments",
				"fileLocation": [
					"absolute"
				],
				"pattern": {
					"regexp": "Error: ([^(]+)\\((\\d+|\\d+,\\d+|\\d+,\\d+,\\d+,\\d+)\\): (.*)$",
					"file": 1,
					"location": 2,
					"message": 3
				},
				"background": {
					"beginsPattern": "Starting compilation",
					"endsPattern": "Finished compilation"
				}
			},
			"runOptions": {
				"instanceLimit": 2
			}
		}
```

How I ran it:

![image](https://user-images.githubusercontent.com/2193314/75275964-2be23500-57ba-11ea-9a2a-e38f78332750.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment]
Works when I add it to "Run tests", not "Build VS Code" though 😕

**Comment by alexr00** [comment]
Good find, thank you! This was actually a wider problem.
