### ISSUE TITLE
Human readable release date in about

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91431]
It'd be nice if the "date" here was something more readable, like "11 hours ago" or "2 weeks ago". It can be hard to tell if your insiders is todays or yesterdays if you need to convert to/from UTC time/etc. 

![image](https://user-images.githubusercontent.com/8586769/75273559-f5a2b680-57b5-11ea-9432-100f842956a3.png)

**Comment by JacksonKearl** [comment]
https://github.com/microsoft/vscode/blob/89cafb24e5d75a0c8d561a6cdd95e93b5679e152/src/vs/base/common/date.ts recent work from @eamodio will help here

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/75731606-f307fb80-5ca4-11ea-8245-1cee428720c2.png)

hell yes

**Comment by sbatten** [comment]
@JacksonKearl hey when was that build from?
