### ISSUE TITLE
Terminate task numbering could be better

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91440]
#91154

![image](https://user-images.githubusercontent.com/2193314/75276429-fc7ff800-57ba-11ea-9d37-7cb84aacf982.png)

Suggestion when there are multiple of a task:

Run tests (1)
Run tests (2)

Version: 1.43.0-insider (user setup)
Commit: 89cafb2
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by meganrogge** [comment]
I'm not sure how to verify this because when I try to run the same task, I see a notification

`The task 'Run tests (vscode)' is already active.`

**Comment by alexr00** [comment]
To get multiple of one task running you need to allow it in the tasks.json for that task:
```json
			"runOptions": {
				"instanceLimit": 4
			},
```
