### ISSUE TITLE
VS Code ipynb notebook: selects every cell or scrolls to bottom with no input

### ISSUE THREAD

**Issue by kkimatx** [microsoft/vscode#91448]
- VSCode Version: 1.42.1
- OS Version: Darwin x64 19.2.0

Steps to Reproduce:

1. When I am browsing between tabs in VS code, multiple things happen with the VS Code notebook:
2. If I go back to a Notebook tab, it will auto scroll to the bottom with no input.
3. Every other notebooks open will have every cell selected, with a cursor active in every cell. 
4. Not sure exactly what triggers it, but this happens frequently. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
