### ISSUE TITLE
Add aka.ms to trusted domains

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#91441]
Testing https://github.com/microsoft/vscode/issues/91270

When git is disabled, there's a link to the documentation to read about source control, which is an aka.ms link. Since this is a link owned by MS, I think it should not cause the "Configure Trusted Domains" prompt

**Comment by octref** [comment]
We whitelist code.visualstudio.com but for aka.ms we did it case-by-case.
@joaomoreno Is there a specific reason you had to use aka.ms instead of directly linking to our website?

**Comment by joaomoreno** [comment]
Not really, just thought that was the way to go since we can always update it off band.

**Comment by octref** [comment]
OK will add it, we already have go.microsoft.com.
