### ISSUE TITLE
Git diff traversing buttons are missing

### ISSUE THREAD

**Issue by iradul** [Microsoft/vscode#9144]
- VSCode Version: 1.3.0
- OS Version: Win 7 Pro

Version 1.3 misses git diff traversing buttons when git file compare is opened:
![vsc13](https://cloud.githubusercontent.com/assets/2411422/16773936/cde70fa2-4827-11e6-9dc7-1e2261e6b332.png)

I guess it has something to do with new tabs feature. Right click gives missing options but it's really tedious to right click every time you want to move to the next change...

Older version 1.1 looked like this:
![vsc11](https://cloud.githubusercontent.com/assets/2411422/16773984/06b2e2ac-4828-11e6-85a5-e25039e84edf.png)

Also it would be nice to have some keyboard shortcut for this.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7666

You can assign keybindings for next/previous diff.

**Comment by iradul** [comment]
Thanks
```
    { "key": "ctrl+alt+]", "command": "workbench.action.compareEditor.nextChange" },
    { "key": "ctrl+alt+[", "command": "workbench.action.compareEditor.previousChange" },
```
