### ISSUE TITLE
Better support for slow symbol providers in symbols picker

### ISSUE THREAD

**Issue by jvilk-stripe** [microsoft/vscode#91445]
- VSCode Version: 1.42.0
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Install an extension that is fast to return workspace symbols, and a second extension that takes tens of seconds to return workspace symbols.
2. Watch as symbol search takes tens of seconds.

Does this issue occur when all extensions are disabled?: No

I'm filing this as a 'bug' because the design of this feature seems flawed.

I support (and implement extensions for) VS Code at my company, including a custom symbol search provider. A user reported that symbol search was taking tens of seconds, and I traced it back to the Go extension they had installed:

https://github.com/microsoft/vscode-go/issues/3066

This type of issue is both difficult to debug and endemic to how VS Code supports language features across multiple extensions via aggregation. Users of my extension view this slowdown as a bug in my code, and I'm certain that authors of open source extensions shoulder a similar support burden! 

At the same time, I understand that this design was likely made intentionally. One strawman 'fix' for this issue would be to support live updating the list of workspace symbols as results come in from multiple extensions, but this 'fix' comes with the downside that the list may update as the user attempts to navigate it, which is also frustrating.

Another solution for corporate users like myself would be the ability to restrict which extensions can provide language features via a workspace setting. The following GitHub issue seems related:

 https://github.com/microsoft/vscode/issues/80889

Another possible solution is to surface what extension VS Code is waiting for somewhere so that users know which extension is responsible for the slowdown.

Anyway, my primary motivation for opening this bug is to alert the development team of this issue, and to hope that they agree that it is worth addressing in some manner (or point me to efforts underway to fix or mitigate the problem).

**Comment by jrieken** [comment]
Quik pick doesn't support stream of results and it's also very unclear how that should behave, esp when conflicts happens, like when a user wants to select a symbol from provider A while results from provider B come in.

**Comment by bpasero** [comment]
Alternative to streaming the results is to time out the provider after a while and provide a hint to re-run the provider to get additional results.
