### ISSUE TITLE
Search editor doesn't play nice with provided links

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91453]
`#1685` is a link from the GH extension, ctrl+clicking it appears like it attempts to open both the link and the search result.

![image](https://user-images.githubusercontent.com/2193314/75280528-77004600-57c2-11ea-94f0-a1904d0d0652.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by JacksonKearl** [comment]
Decided to just disable links in search editors.

**Comment by JacksonKearl** [comment]
Reverted earlier commit as it made the header links also broken. Will find a better solution.
