### ISSUE TITLE
After closing Intellisense, keep closed until next time its needed

### ISSUE THREAD

**Issue by the-lambda-way** [microsoft/vscode#91454]
It would be nice if the suggestion box remained closed once you close it, until the next time you create or modify a different token. This is a frequent problem for me when lining up code up with a line below. Since the suggestions reopen everytime I press space, I have to switch between adding spaces and hitting escape to see the line below.

It's also annoying when typing out a token and close the suggestion box, when it reopens with the next character I type. If I close the box, it should remember my preference as long as I'm still doing the same thing.

![image](https://user-images.githubusercontent.com/32426282/75279880-06612580-57d2-11ea-9f36-f489012c93fa.png)

**Comment by jrieken** [comment]
Two settings exit for this: `editor.quickSuggestions` and `editor.suggestOnTriggerCharacters`

**Comment by the-lambda-way** [comment]
Thanks @jrieken, I did not know about `editor.suggestOnTriggerCharacters`. I think my suggestion still makes sense, as trigger characters are still useful in themselves (especially the dot character), but I don't really understand why "space" makes sense as one. Or a way to customize which characters are triggers

Anyway, turning off trigger characters altogether works well enough as a workaround.
