### ISSUE TITLE
EvaluatableExpression should request cancellation when hovering off the expression

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91457]
Ref: https://github.com/microsoft/vscode/issues/91268#event-3067581669

I noticed the cancellation token is seemingly never cancelled. We can probably cancel it when the user changes their hover position or hovers off the document.

**Comment by RMacfarlane** [comment]
I'm having trouble getting the hover to show up in the first place. I have an extension with the following code:

```ts
	class SimpleEvaluatableExpressionProvider implements vscode.EvaluatableExpressionProvider {

		provideEvaluatableExpression(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): vscode.ProviderResult<vscode.EvaluatableExpression> {
	
			token.onCancellationRequested(e => {
				console.log('CANCELLATION REQUESTED');
			});

			const lineContent = document.lineAt(position.line).text;
	
			let expression = /\w+/g;
			let result: RegExpExecArray | null = null;
	
			// find the word under the cursor
			while (result = expression.exec(lineContent)) {
				let start = result.index;
				let end = start + result[0].length - 1;
	
				if (start <= position.character && end >= position.character) {
					return new vscode.EvaluatableExpression(new vscode.Range(position.line, start, position.line, end));
				}
			}
	
			return undefined;
		}
	}

	vscode.languages.registerEvaluatableExpressionProvider({ scheme: 'file', language: 'javascript' }, new SimpleEvaluatableExpressionProvider());
```

I start debugging the extension, then debug a js file from the extension development host that just has "console.log('hello world')" with a breakpoint on it. I see that `provideEvaluatableExpression` is hit when I mouse over it, but nothing changes in the UI. Is there something I'm missing?

**Comment by connor4312** [comment]
I think what you have is right. You would not expect to see a change in the UI necessarily -- the expression provider provides the expression that's sent to the debug adapter to execute when hovering on a variable. The result of that evaluation is shown.

Also, the cancellation token hooked up through the rpc protocol is ignored once the provider returns. So you want to add something like `await new Promise(r => setTimeout(r, 1000));`. Probably the simplest way to test for js would be

```js
class SimpleEvaluatableExpressionProvider implements vscode.EvaluatableExpressionProvider {
	async provideEvaluatableExpression(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Promise<vscode.EvaluatableExpression | undefined> {
		token.onCancellationRequested(e => {
			console.log('CANCELLATION REQUESTED');
		});
		await new Promise(r => setTimeout(r, 1000));
		return new vscode.EvaluatableExpression(new vscode.Range(position, position), '42');
	}
}

vscode.languages.registerEvaluatableExpressionProvider({ scheme: 'file', language: 'javascript' }, new SimpleEvaluatableExpressionProvider());
```

**Comment by RMacfarlane** [comment]
Thanks @connor4312!
