### ISSUE TITLE
Syntax highlighting in python gets weird when line begins with `*`

### ISSUE THREAD

**Issue by TansyArron** [microsoft/vscode#91456]
Issue Type: <b>Bug</b>

Passing `*` in a list of arguments to a function is valid python (everything after the * must be specified as a kwarg.)

When a list of arguments is on more than one line and a `*` is the first argument on the line, the syntax highlighting gets very odd. Everything on that line is a pale green color.
<img width="1096" alt="Screen Shot 2020-02-25 at 14 40 53" src="https://user-images.githubusercontent.com/3494066/75281274-fac72c00-57dc-11ea-9b04-6e07ecbf6c63.png">

<img width="859" alt="Screen Shot 2020-02-25 at 14 33 38" src="https://user-images.githubusercontent.com/3494066/75281144-b9cf1780-57dc-11ea-8ec5-758a208ba037.png">
repro

Everything is fine here:
```
def my_func(*, foo, bar, baz=True)
```

Here the middle line turns pale green:
```
def my_func(
  *, foo, bar, baz=True,
)
```

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
pubmanager|bco|0.0.13
dart-code|Dar|3.8.1
terraform|mau|1.4.0
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.0.9
python|ms-|2020.2.64397
Go|ms-|0.13.0
vscode-yaml|red|0.7.2
jinjahtml|sam|0.11.0
preview-vscode|sea|2.1.0
vscode-djaneiro|the|1.4.2
gitblame|wad|3.1.0

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
