### ISSUE TITLE
Debug start view: Cannot activate debugger extension

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#91450]
Testing #91143

```bash
mkdir test
code-insiders test
```

- Go to Debug View
- Click "create a launch.json file"

![image](https://user-images.githubusercontent.com/4033249/75280080-9fd40b80-57c1-11ea-9678-b2d27327a64d.png)

**Comment by isidorn** [comment]
This is up to the Javascript Debugger extension. Forwarding to @connor4312 
And he can assign back to me if it is a vscode issue (which I believe it is not)
