### ISSUE TITLE
Smoke test: search test failure

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#91451]
Testing https://github.com/microsoft/vscode/issues/91337

When running the Web tests with Chromium, I see this test failure:
```
  1) VSCode Smoke Tests (Web)
       Search
         searches for body & checks for correct result number:
     Error: Timeout: get text content '.search-view .messages .message>span' after 20 seconds.
      at /Users/ramacfar/dev/vscode/test/automation/out/code.js:176:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/ramacfar/dev/vscode/test/automation/out/code.js:9:58)
```

**Comment by bpasero** [comment]
Seems a flaky one, I saw this only once and then it was fine.

**Comment by chrmarti** [comment]
Seeing the same with Webkit, screenshot:
![image](https://user-images.githubusercontent.com/9205389/75333857-29014600-5887-11ea-8515-fc17a0ab1f19.png)

**Comment by roblourens** [comment]
This is due to running the search a millisecond before the provider in the EH has registered. It's only possible to hit manually if you are very fast. I want to fix SearchService to defer searches until a matching provider has registered so I'll wait for March.

**Comment by connor4312** [comment]
I ran smoke tests a few times and didn't see a failure here.
