### ISSUE TITLE
Debug start view: include documentation for `viewsWelcome`

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#91465]
Testing #91143

`viewsWelcome` is very vague. What is "welcome content"?

![image](https://user-images.githubusercontent.com/4033249/75282026-32c27500-57c5-11ea-8627-1090c71f64e4.png)

Please also add it to the reference: https://code.visualstudio.com/api/references/contribution-points.

Ideally I think there should be a "Welcome View" guide next to [tree view guide](https://code.visualstudio.com/api/extension-guides/tree-view), with a sample `welcome-view-sample`.

**Comment by joaomoreno** [comment]
@octref Note this is still proposed, so I won't add to documentation or samples yet.
