### ISSUE TITLE
Two icons for representing notification progress are confusing

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91469]
Refs: https://github.com/microsoft/vscode/issues/91163

We showing notificatino progress we render two icons in the status bar. The ball and the spinner.
I am not a big fan of this appraoch as they seem like two disconnected icons to me. We should somehow marry them, or show a progress in some other way.
On the very least they should share some backgroun color / outline

![Screenshot 2020-02-25 at 21 01 59](https://user-images.githubusercontent.com/1926584/75282891-14369b00-5812-11ea-82c7-924a0686536f.png)

**Comment by bpasero** [comment]
Agree. @misolori might need your help.

**Comment by bpasero** [comment]
For example:

![image](https://user-images.githubusercontent.com/900690/75321465-23006a80-5871-11ea-8c72-b7b427115473.png)

**Comment by isidorn** [comment]
Yeah that would be pretty cool. If the spinning is ike a spinning badge on the bell.

**Comment by bpasero** [comment]
I doubt we can animate just that part of the bell. It would be static and not spinning.

**Comment by misolori** [comment]
You can now use `bell-progress` though it's a bit hard to make out the smaller icon (had to reduce the amount of lines to make it stand out more):

![image](https://user-images.githubusercontent.com/35271042/75410723-a6ea3f00-58d1-11ea-9e02-96dd9a6bcb39.png)

**Comment by bpasero** [comment]
I ended up not using this icon as I felt it was too subtle. What I did instead is to simply use the bell with a dot whenever a notification is in progress. I think this is easier to understand because this indicates that "something" is going on in the hidden notification center.

**Verification:** follow steps from https://github.com/microsoft/vscode/issues/91163 and verify the bell shows a dot for as long as the notification is in progress.

**Comment by jrieken** [comment]
Are we sure this isn't too subtle? We have never finishing save operations that can be behind this...

**Comment by bpasero** [comment]
@jrieken the alternative is what I suggested earlier to promote a running save operation to the status bar where we usually show progress when not in notification.

**Comment by bpasero** [comment]
Went back to the original model where we would indicate the progress in the status bar whenever the notification is hidden:

![Kapture 2020-02-27 at 12 55 36](https://user-images.githubusercontent.com/900690/75442877-9f25ab80-5960-11ea-9bbf-e56ac6ee1c78.gif)

**Verification:**
* craft a action that you can use to bring up a notification with progress (see below)
* as long as the notification is visible either as toast or in the notification center no status entry shows
* once you hide the notification toast with ESC key, status bar shows progress for as long as the progress goes on
* once you hide the notification center, status bar shows progress for as long as the progress goes on
* ensure the status bar entry can be clicked to open the notification center
* ensure the status bar entry is always showing the latest progress step message
* ensure the status bar entry goes away when the progress is done

**Comment by joaomoreno** [comment]
@bpasero Fantastic verification steps!

**Comment by bpasero** [comment]
Thanks for verifying so fast 👍

**Comment by misolori** [comment]
Since we won't be using the subtle icon (which I agree with) I'll remove it from our library
