### ISSUE TITLE
Debug start view: No completion or documentation for valid `view` values

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#91466]
Testing #91143

I cannot find any documentation on what's valid values for `view`.

There's no JSON completion either:

![image](https://user-images.githubusercontent.com/4033249/75282449-f3e0ef00-57c5-11ea-9391-13752123b05b.png)

**Comment by isidorn** [comment]
This is fair feedback, forwarding to @joaomoreno since he introduced this.
Feel free to assign back to me since I can also tackle this.

**Comment by joaomoreno** [comment]
Decided to create view aliases and add them as `enum` to the schema:

- `explorer`
- `debug`
- `scm`
