### ISSUE TITLE
Wrong TS auto-import after using JS library (Angular project)

### ISSUE THREAD

**Issue by oleh-nesterchuk** [microsoft/vscode#91476]
Issue Type: <b>Bug</b>

1. Import any JS library (CanvasJS in my case) in some component.
2. Inject any service (that hasn't been imported yet) at the component.
3. Use auto-import to import the service.
4. Here we go: we get imported the wrong service (more precisely, the one with extension .js instead of .ts).

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (3.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.1
prettier-vscode|esb|3.20.0
debugger-for-edge|msj|1.0.14
material-icon-theme|PKi|3.9.3

</details>

**Comment by mjbvz** [comment]
Can you please provide a code example that demonstrates this issue
