### ISSUE TITLE
Debug start view: rendering order not guaranteed

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#91471]
Testing #91143

![image](https://user-images.githubusercontent.com/4033249/75282948-bfb9fe00-57c6-11ea-962b-9822e4e28412.png)

- Clone https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample
- Add below to `package.json`

	```
	"viewsWelcome": [
		{
			"view": "workbench.debug.startView",
			"contents": "😋\n[Refresh Entry](command:nodeDependencies.refreshEntry)"
		}
	]
	```

- Focus Explorer
- Reload
- Navigate to Debug View
- Contributed content show above default content 🐛 

My guess is this corresponds to the extension activation order. If I focus on Debug View and reload, the order is like this:

![image](https://user-images.githubusercontent.com/4033249/75283155-22ab9500-57c7-11ea-8080-38080fb495da.png)

**Comment by isidorn** [comment]
@joaomoreno I believe we should always give priority to the views which are contribued from Core, not from Extensions.
Does this make sense?

**Comment by joaomoreno** [comment]
There is no ordering implemented yet. I'll try to find something which works.

**Comment by isidorn** [comment]
@joaomoreno please note that I changed in latest from master when I register my views. So now I do this quite upfront and this bug might no longer be reproducable using @octref steps.
Though we do need ordering either way.

**Comment by octref** [comment]
Still reproduces for me on b0be0672c210f1fa76109ce675365bb785657e84

**Comment by joaomoreno** [comment]
I've changed it to the following:

- Core welcome content has highest priority
- Built-in extensions go next
- Other extensions go next

**Comment by isidorn** [comment]
Great, this makes a lot of sense.
