### ISSUE TITLE
Feature Request: Add an always stage+commit button to source control UI

### ISSUE THREAD

**Issue by fab1o** [microsoft/vscode#91472]
-  VSCode 1.42.1
-  OS Version: macOS High Sierra 10.13.5
-  Source Control: Git

### Description:

*Enable Smart Commit* settings will stage and commit files.

When you click the current :heavy_check_mark: button, it stages and commits:

```sh
> git add -A -- .
> git commit --quiet --allow-empty-message --file -
```

But when there's files in the staging area, it doesn't re-stage, it only commits:

```sh
> git commit --quiet --allow-empty-message --file -
```

The problem is when you use tools like lint-staged combined with ESLint for instance, that prevents a commit if there's an error from eslint. After the first attempt to commit, if lint-staged prevents the commit, the files will remain in staging. The 2nd attempt to commit, VSCode won't re-stage such files and so the button will never work.

### Idea:

1) Add a second :heavy_check_mark: button for an always stage+commit which will always auto-stage files that are already staged (only those already staged, it's not a "Commit All" button) and then commit.
2) Remove the "Enable Smart Commit" setting because it's unecessary now.

What do you think?

### Steps to Reproduce:

1. Setup a JS project with lint-staged and husky and this package.json setting as an example:
```json
  "lint-staged": {
    "*.js": [
      "eslint"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
```
2. Make sure *Enable Smart Commit* on VSCode settings is on
3. Change a file in your local branch that will cause an ESLint error
4. Click the :heavy_check_mark: button to stage and commit
5. You should see an error and the file remains in staging
6. Re-edit the file and fix the ESLint issue.
7. Now there's a copy of the file in staging and another unstaged. Click the :heavy_check_mark: button again.

Expected to see the file auto staged and commited. But it won't until you manually re-stage the file.

**Comment by joaomoreno** [comment]
I don't think a second checkbox would be a good idea for the majority of our users.

But you can always add it yourself by creating an extension which contributes said command to that menu!
