### ISSUE TITLE
Search Editor peek say "Definitions ()"

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#91478]
- VSCode Version: 1.43 Insiders
- OS Version: Windows 10

Found while testing #91331

Steps to Reproduce:

1. Open the vscode-docs repo and create an empty Search Editor
2. Search for "VSCode" and set Match Case and Match Whole Word
3. Double-click on a file path to open the Peek view.

Title bar says "Definitions ()" with the count. I would have expected the text to say "Matches ()"

![image](https://user-images.githubusercontent.com/12818376/75286045-a1ef9780-57cc-11ea-89ca-6b480abf8bee.png)

**Comment by JacksonKearl** [comment]
Currently using all of the go-to-definition infrastructure for things like peek, open to side, keybinds, etc, I don't think we can change this without reimplementing all of that specific to the editor so going to close this out.
