### ISSUE TITLE
Add Open in New Window to folder's context menus

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#91475]
When opening a mono-repo with many projects, I often want to "scope" down to a single path within it, so I would like to have a _Open in New Window_ command or similar on the folder's context menu. So I can open that folder in a new vscode window. Additionally it might be nice to also have a command to open it in the existing window, but I don't feel I would use that as often.

**Comment by Coops9** [comment]
This feature (if I am correct) sounds like it could be a step in a direction towards floating windows. [Issue 10121](https://github.com/microsoft/vscode/issues/10121)

I know there is a comment [#10121 (comment)](https://github.com/microsoft/vscode/issues/10121#issuecomment-345770248) which goes into great depth about how technically challenging this feature is but maybe just having the ability to right-click a tab or right-click a file to either "Duplicate Workspace in New Window" OR "Open Active File in New Window"

This goes part of the way to creating an easier user experience, especially if you have multiple screens and want to look at 2 different files in the same workspace.
