### ISSUE TITLE
Feature: Focus Tab by Number

### ISSUE THREAD

**Issue by wulftone** [Microsoft/vscode#9148]
It's very handy to be able to move to a tab by selecting tab number, e.g. Cmd+3 focuses the third tab, Cmd+1 focuses the first one.  I'd like to be able to set these keyboard shortcuts!  Pretty much all of the popular editors allow this.

**Comment by bpasero** [comment]
Just assign to `workbench.action.openEditorAtIndex1` - `workbench.action.openEditorAtIndex9` in keybindings.

**Comment by wulftone** [comment]
Nice, thank you, I missed that in the keyboard settings file
