### ISSUE TITLE
yum repo has unsigned "hello" RPM

### ISSUE THREAD

**Issue by discard-this** [microsoft/vscode#91488]
CentOS RPM

Package hello-2.8-1.x86_64.rpm is not signed
Removing hello-2.8-1.x86_64.rpm due to failed signature check.
rs: reposync - vscode exited with code 1 -- aborting.

Please sign the hello-2.8-1 RPM (or remove it)

thanks,
nomad

**Comment by RMacfarlane** [comment]
@discard-this Thanks for reporting! I've notified the linux repo team at Microsoft.
