### ISSUE TITLE
Heighlighted text in the terminal

### ISSUE THREAD

**Issue by devd8292** [microsoft/vscode#91489]
Issue Type: <b>Bug</b>

I don't know why but everything in my Vscode powershell terminal is heighlighted. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz (8 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (32.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
wlpfo-log-highligter|Ale|0.0.6
vscode-nm|dpa|0.2.0
systemverilog|eir|0.9.5
LogFileHighlighter|emi|2.7.1
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
veriloghdl|msh|1.0.4
incrementor|nms|0.1.0
vscode-yaml|red|0.7.2
tcl|sle|0.2.0
msbuild-project-tools|tin|0.3.3

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by roblourens** [comment]
A screenshot might help too

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

You might be able to fix this issue by removing customizations to cmd.exe's theme.

**Comment by devd8292** [comment]
I have attached the screenshot here.

[image: image.png]

I don't understand the solution you provided. Can you please explain in
simple language?

Dev

**Comment by Tyriar** [comment]
@devd8292 the solution is to upgrade to Windows 10 v1903 to move to the new backend that is maintained by the Windows terminal team and fixes a bunch of issues.
