### ISSUE TITLE
Hide password inputs from tasks on output

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91485]
Testing #91152

![image](https://user-images.githubusercontent.com/35271042/75292418-fa2c9680-57d8-11ea-9ac9-76436cb123d0.png)

Even though I was doing a test that would echo the password, or whatever the input i typed, should we always prevent from any type of "password" from being shown in the console? I'm not sure what use case we'd want to show the password in the console, so I'm thinking it's better to be safe than sorry? Especially since terminals don't ever show passwords.

![image](https://user-images.githubusercontent.com/35271042/75292704-96569d80-57d9-11ea-87af-ec6a3260f546.png)

**Comment by alexr00** [comment]
This was my concern when I accepted the PR to do the password input :) I was worried that there would be a false sense of security.
But we already allow extensions to use the quick input with a password input and then they can show your password input where ever they choose, so this jus follows the same model.
We also can't know what the task does with the password input, so we can't prevent it anyway.
