### ISSUE TITLE
Settings backups should be named with .json

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91487]
Testing https://github.com/microsoft/vscode/issues/91226

I think these backups should have the `.json` extension. A more user-friendly name might be like `timestamp-settings.json`

![image](https://user-images.githubusercontent.com/323878/75292583-52fc2f00-57d9-11ea-8140-edcef0872eef.png)

**Comment by sandy081** [comment]
Agreed to add `.json` extension. But will leave the name as is because they are already under settings folder.
