### ISSUE TITLE
Maybe '.sync' folder shouldn't be dot-prefixed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91486]
Testing https://github.com/microsoft/vscode/issues/91226

I don't see why the `.sync` folder is not just named `sync`? I think the `.` implies that it is private or not something the user cares about but it is just user data

![image](https://user-images.githubusercontent.com/323878/75292583-52fc2f00-57d9-11ea-8140-edcef0872eef.png)

**Comment by sandy081** [comment]
Yes. It is private data maintained by sync feature.

**Comment by Tyriar** [comment]
I kind of agree with @roblourens; globalStorage and workspaceStorage are also private data maintained by a feature in VS Code? Dot files are also a Nix* concept (that only came about because of a bug in a shell I think) which we shouldn't need to being in to a pretty hidden config folder.

**Comment by sandy081** [comment]
Changed `.sync` folder to `sync` and also removed other dot notations `.lastSync${area}.json` to `lastSync${area}.json`.

There should not be any impact.

**Comment by Tyriar** [comment]
I saw this but that's just because I hadn't changed my account type. The error is descriptive enough already (since a sync didn't happen yet):

<img width="473" alt="Screen Shot 2020-02-28 at 7 42 42 AM" src="https://user-images.githubusercontent.com/2193314/75563060-85d33c80-59fe-11ea-8226-f20c86e92ef8.png">

**Comment by sandy081** [comment]
I guess you saw this when you are trying to open backups? Yes it happened because sync did not happen yet.
