### ISSUE TITLE
vscode disable extension not installed on wsl

### ISSUE THREAD

**Issue by nguyenmao2101** [microsoft/vscode#91480]
Issue Type: <b>Bug</b>

Extensions already installed on local will be disabled if not installed on wsl.
Kite engine does not support wsl yet, so i need to install engine on windows then use autocomplete plugin on local not in wsl.
if i enable this extension on wsl, it show kite engine is not installed.

![disabled on wsl](https://user-images.githubusercontent.com/22334887/75287203-8b892080-584c-11ea-956d-7ccfd3b38962.png)

![enabled wsl](https://user-images.githubusercontent.com/22334887/75287749-85e00a80-584d-11ea-8331-e8b5b4639fbb.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2294)|
|Memory (System)|6.11GB (5.11GB free)|
|VM|0%|
</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.34.0
prettier-vscode|esb|3.20.0
vscode-lua-format|Koi|1.3.3
python|ms-|2020.2.64397
cmake-tools|ms-|1.3.1
cpptools|ms-|0.26.3
autodocstring|njp|0.4.0
markdown-preview-enhanced|shd|0.5.2
remote-wsl|ms-|0.42.3

</details>

**Comment by roblourens** [comment]
Please file this issue on the extension's repo. A language extension like that will probably have to run on the remote.
