### ISSUE TITLE
I shouldn't be signed in automatically when launching vscode with a fresh user data dir

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91482]
Testing https://github.com/microsoft/vscode/issues/91226

- Sign in to Sync
- Start vscode with a fresh userDataDir
- Start Sync
- I am already signed in and don't need to sign in again (but do need to enable sync)

Usually all the important pieces of information are in the userDataDir so this felt surprising. Discussed offline

**Comment by RMacfarlane** [comment]
The only way I can think to fix this right now is by using `globalStoragePath` as part of the key when storing it in the keychain. I'm not sure if this would cause further issues (are there characters that aren't supported in the key?), so I'm going to wait and fix this in March

**Comment by roblourens** [comment]
You could hash the path so you don't have to think about weird characters or very long keys
