### ISSUE TITLE
"A system error occurred" when opening web in desktop

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91495]
ref #91225 on ubuntu

![image](https://user-images.githubusercontent.com/8586769/75296888-4b418800-57e3-11ea-8397-5bbe3639b1e5.png)

**Comment by bpasero** [comment]
This seems unrelated to opening a link to me.

**Comment by joaomoreno** [comment]
Caused by https://github.com/microsoft/vscode/pull/89199, will be fixed with https://github.com/microsoft/vscode/issues/89593

@bpasero Is it critical for February?

**Comment by bpasero** [comment]
If you ask for the "Open in Desktop" support, I think this is not critical for February. But I am not sure how this triggers the issue. It would probably happen for any protocol link invocation then.
