### ISSUE TITLE
[Bug] Tree View Filter hides helpful shortcuts

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#91491]
Bringing this here from: https://github.com/PowerShell/vscode-powershell/issues/2497

# Summary
![PowerShellFilterBug](https://user-images.githubusercontent.com/25514145/75272725-72408f80-57cc-11ea-9f26-72bc72526bdd.gif)

## System Details
```
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

## Issue Description

I am experiencing a problem with the user interface. The filter on PowerShell commands is extremely useful to have. But the filter overlaps the first row of commands and I can't click on the `"Get Help for Command"` or the `"Insert Command"` shortcuts.

### Expected Behavior

Filter control doesn't hide the shortcuts on the first row.

### Actual Behavior

Hides helpful shortcuts on first row of commands after filter is applied.

## Possible Solution

Would be nice to have padding above the first row if filter applied.

Similar to VS code find-and-replace functionality:
![PowerShellFilterBugSolution](https://user-images.githubusercontent.com/25514145/75274076-2bed2f80-57d0-11ea-9f78-5f95a609ed43.gif)

**Comment by joaomoreno** [comment]
You can drag the orange box to the left.
