### ISSUE TITLE
Protocol links do not work in Firefox

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91496]
#91225 on ubuntu

Have a workspace open in web. 

Have some other folder open in insiders

Close insiders

Click "open in desktop"

Bug: Insiders opens to the folder it opened last, rather than the workspace I had open in web.

**Comment by bpasero** [comment]
Since this works fine on Windows and macOS, I suspect an issue with how we support to open links on Linux. Maybe we are missing to forward the right parameters?

**Comment by bpasero** [comment]
@JacksonKearl actually this works fine for me if I use the latest build: https://az764295.vo.msecnd.net/insider/b0be0672c210f1fa76109ce675365bb785657e84/code-insiders_1.43.0-1582695407_amd64.deb

![Kapture 2020-02-26 at 8 15 41](https://user-images.githubusercontent.com/900690/75321040-41b23180-5870-11ea-823b-4c5fe98aae0e.gif)

Did you use an older build maybe? Or possibly snap?

**Comment by JacksonKearl** [comment]
This is only a bug in firefox, as firefox does not delegate to `xdg-open` for URI's. Chrome is good.

**Comment by bpasero** [comment]
@JacksonKearl did you find the bug in Firefox or would you be willing to report one?

**Comment by JacksonKearl** [comment]
@bpasero I'd like to figure out what URI code is actually being opened with in order to get more info, but I cant seem to get a handler for the `code-oss` scheme to register, even for `xdg-open`. Do you have ideas on how to get a more concrete repro?

**Comment by bpasero** [comment]
@JacksonKearl follow the usages of `urlProtocol` from https://github.com/microsoft/vscode/blob/fc9543ac88a6ddd541d319d6425e1734ccb36f72/product.json#L22. That is what we use to register a handler with the OS.  However for Linux it seems we are also needing this to work: https://github.com/microsoft/vscode/blob/fc9543ac88a6ddd541d319d6425e1734ccb36f72/resources/linux/code-url-handler.desktop#L1

Would be great to isolate this into a standalone repro.

**Comment by JacksonKearl** [comment]
I looked further into this and set up my own url handler that simply writes the arguments it gets to a file:

```sh
#!/bin/bash

OUT="/home/parallels/echoer_out";

echo "New Invocation" >> $OUT;
echo "$@" >> $OUT;
```

and found that in both Firefox and Chrome the same argument info is being passed:

```
New Invocation
vscode-insiders://vscode-remote/localhost:9777/home/parallels/testworkspace.code-workspace
New Invocation
vscode-insiders://vscode-remote/localhost:9777/home/parallels/testworkspace.code-workspace
```

which would seem to suggest its not actually a Firefox problem?

**Comment by bpasero** [comment]
@JacksonKearl the URL seems fine to me. What does `xdg-open vscode-insiders://vscode-remote/localhost:9777/home/parallels/testworkspace.code-workspace` result in on your Linux?

**Comment by JacksonKearl** [comment]
I'm actually now able to reproduce this on both firefox and chrome, but it's flakey on both. Directly calling `xdg-open` seems to work reliably.

**Comment by JacksonKearl** [comment]
This is what I'm seeing:

1. Start server, with either Safari or Chrome as default broswer
1. Run xdg-open in terminal. Works.
1. attempt to open in desktop. fails
1. open new tab to the remote, attempt to open in desktop. fails.
1. open new window of same browser to remote, without closing old. Attempt. Fails.
 1. open new window of different browser to remote. Attempt. Works.
1. After opening in alternate browser works, attempt in original window. Fails.
1. close original window. open a new window of the same browser. Attempt. Works.

**Comment by bpasero** [comment]
@JacksonKearl for the sake of testing, let's ignore that the workspace when opened in desktop is functional or not. "Open in Desktop" is known to actually not work well for localhost testing. For the sake of testing, consider the test as success if you see this in the status bar:

![image](https://user-images.githubusercontent.com/900690/75851956-34a2be80-5deb-11ea-8bdd-1c6a8ff69cd2.png)

Here is again how it works for me using Firefox:

![Kapture 2020-03-04 at 7 37 45](https://user-images.githubusercontent.com/900690/75851983-45ebcb00-5deb-11ea-8fc1-a742fb70a022.gif)

Can you completely uninstall VSCode insiders and reinstall from the deb package? 

Last, how does the situation look like when you try normal file protocol links and not `vscode-remote`, e.g. `vscode-insiders://file/<path>`?

**Comment by bpasero** [comment]
This still needs more info from https://github.com/microsoft/vscode/issues/91496#issuecomment-594353613

**Comment by JacksonKearl** [comment]
I do not get `vscode-remote` in the status bar in any of the failure cases. 

Navigation to a `vscode-insiders://file/...` URI gives similarly broken behaviour.

**Comment by bpasero** [comment]
Ok, then this seems unrelated to "Open in Desktop" but a general issue.

**Comment by JacksonKearl** [comment]
It isn't just Firefox. A more accurate title might be "Protocol links do not work in the browser instance spawned by web.sh"

**Comment by bpasero** [comment]
@JacksonKearl so is this the gist of the issue that protocol links work when you manually open a browser?

**Comment by JacksonKearl** [comment]
@bpasero yeah that seems right

**Comment by bpasero** [comment]
Ok, that does not seem like it has impact on users then. I am using the opn library to open a browser but you can pass `--launch=false` to prevent the browser from opening. 

I can only speculate that possibly protocol handlers require the app to be started using the dock and not from the command line.
