### ISSUE TITLE
Debug adapter 'continued' event not working

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#9149]
vscode-chrome-debug is firing the private 'continued' event to support the continued button that shows up on the Chrome window, but it seems like that's not working anymore. Is there still some way to implement this?

Microsoft/vscode-chrome-debug#201

**Comment by isidorn** [comment]
No, this was an internal event which we used as a workaround. Since we fixed #5966 we have removed that event.
If we want to add this we should first surface it in the protocol, thus assigning to @weinand

**Comment by weinand** [comment]
@isidorn I've added a ContinuedEvent to the protocol.
