### ISSUE TITLE
HTML not rendered

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#91501]
refs #91328

I can only assume this is supposed to render the html

![image](https://user-images.githubusercontent.com/6561887/75297410-ac1d9000-57e4-11ea-9a77-f15cad1e66a5.png)

**Comment by rebornix** [comment]
We sanitized it when rendering it in the core. Probably we should render it in the webview if the users want to have a full featured markdown rendering.

**Comment by mjbvz** [comment]
We now support html inside of notebook markdown cells
