### ISSUE TITLE
Try moving off of gulp-tsb to use TypeScript "Fast and Loose" incremental checking

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#91503]
TypeScript 3.8 now supports ["Fast and Loose"](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/#assume-direct-dependencies) incremental checking. This should match `tsc --watch` just as fast as `gulp-tsb`

In debt week, let's investigate adopting the new `assumeChangesOnlyAffectDirectDependencies` compiler option and see if it allows us to move off of gulp-tsb

**Comment by jrieken** [comment]
I like - we should dig up the old test cases so that we have something to compare

**Comment by jrieken** [comment]
👯‍♂ 👯 Looking very good! I re-ran the tests from https://github.com/microsoft/vscode/issues/80074#issuecomment-527851536 with `npx tsc -p src/tsconfig.json --assumeChangesOnlyAffectDirectDependencies --watch` and in all scenarios the reconcile took <1 sec. I think as a next step we should find a few volunteers to selfhost on `tsc` for a while.

**Comment by jrieken** [comment]
Early adopters! Do this:

* run `yarn watch` so that non-emitted files, like css, images, fonts etc, are copied to the out folder. 
* kill the `yarn watch` but remember to restart it when new resources arrive (seldom)
* run `npx tsc -p src/tsconfig.json --assumeChangesOnlyAffectDirectDependencies --watch`. Note that this only compiles VS Code but not the extensions-folder, for now more tsc-processes must be started

**Comment by joaomoreno** [comment]
@mjbvz Any plan on having the tsc watcher simply copy resources, in order to prevent having yet another watcher in parallel?

**Comment by Tyriar** [comment]
Nice! After this is smoothed out a bit we can explore using project references to explicitly declare dependencies between components which should boost performance and could also act as a framework for code splitting where components not used are lazy loaded.

**Comment by jrieken** [comment]
ping @Danielrosenwasser for https://github.com/microsoft/vscode/issues/91503#issuecomment-597090804

**Comment by DanielRosenwasser** [comment]
Hey all, we don't have any plans to introduce file copying. We've discussed it in the past at https://github.com/microsoft/TypeScript/issues/30835 and don't believe it falls within TypeScript's scope.

**Comment by jrieken** [comment]
Yeah, I kinda agree but it is a pity that we run yet another file-watcher along all those others...

**Comment by jrieken** [comment]
This is abandoned, the new trend is to decouple compile from transpile
