### ISSUE TITLE
"Open in Desktop" opens a empty workspace  when an instance of insiders is already running

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91500]
Ref #91225 on ubuntu

Web open on some workspace

Insiders open on some other folder

"Open In Desktop"

Bug: a new empty workspace insiders opens rather than the workspace that was open in web

**Comment by bpasero** [comment]
@JacksonKearl also cannot reproduce, similar to https://github.com/microsoft/vscode/issues/91496#issuecomment-591276117 please try what I suggest there.

**Comment by JacksonKearl** [comment]
Firefox only. Closing to track in https://github.com/microsoft/vscode/issues/91496#issuecomment-592150902
