### ISSUE TITLE
Can't render 2 notebooks?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#91506]
refs #91328

Open 2 notebooks side by side:

e.g. `runCode_iframe_form_15.ipynb` and `runCode-slim.ipynb`

iframes fail to render

**Comment by mjbvz** [comment]
@rebornix Can you please test the change I just pushed. The error does not happen reliably so I'm not sure if I fixed it or not

**Comment by rebornix** [comment]
It seems it's fixed. I'll close it for now, thanks for the quick fix!

**Comment by rebornix** [comment]
Verification:

* Open a notebook which contains html outputs
* Split the editor
* Make sure the html outputs are rendered in both panels.
