### ISSUE TITLE
Javascript looks wrong for samples/mimetypes

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#91505]
refs #91328

![image](https://user-images.githubusercontent.com/6561887/75298540-9bbae480-57e7-11ea-9b0b-7c38f784a51c.png)

**Comment by rebornix** [comment]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/876920/77804914-e8d7e380-703d-11ea-9b61-0691fc2778fe.png">

Now we set min height for an output. For the `application/javascript` mime type output, the output is empty thus you didn't see anything but a gray background.
