### ISSUE TITLE
iframe loses state if navigated away from editor

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#91507]
refs #91328

**Comment by rebornix** [comment]
Interesting and challenging problem, currently we don't have any way to restore view states for web views when switching editors (because they are disposed and then recreated). Same issue for markdown preview.

**Comment by mjbvz** [comment]
I'm going to close this as by-design.

As @rebornix notes, we actually destroy the webview when it is not visible. There is no reliable way for VS Code to restore the focus for extensions. Instead, each extension will need to implement this themselves.

The basic idea would be:

- In the extension's webview JavaScript, track the currently focused element in the webview state.
- When the webview is loaded and its scripts are executed (this would happen when its visibility is restored), check the webview state to see if anything has been saved off.
- If there is webview state, then restore the focus to the correct element.
