### ISSUE TITLE
Add rerunSearchEditorSearch to Command Palette

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#91508]
- VSCode Version: 1.43 Insiders
- OS Version: Windows 10

Found while testing #91331

Tricky to find command to rerun the last Search Editor search. Putting it in the Command Palette would aid discovery.

For example, user mistakenly has focus in the Search editor text and starts pressing Enter or other characters to mess up result. Would be nice to rerun the current search via Command Palette or keyboard shortcut.

**Comment by JacksonKearl** [comment]
There is now a rerun editor action contribution in search editors and a rerun command in command pallet.
