### ISSUE TITLE
A newly saved file doesn't show in the 'File -> Open recently opened files' list

### ISSUE THREAD

**Issue by imxys** [microsoft/vscode#91515]
- VSCode Version:1.39.1
- OS Version:Ubuntu 18.04.3 with KDE

Steps to Reproduce:

1. create a new file, write anything
2. save the file to anywhere
3. Open menu Files->Open recently opened files(not sure, I'm not using code in English)
4. cannot find the recently file saved before
5. What's more, if I try these steps in a code window that opens a directory (extensions enabled) , I can't find this file with CTRL-P(go to files),  while I can find it in an new window without any dir opened (extensions disabled).

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
That's an old version of vscode. Could you update and try again?

**Comment by bpasero** [comment]
File > Open Recent is seeded only from files you open via File > Open..., the command line or DND.

A workspace scoped history is accessible via `Cmd+P`.

**Comment by imxys** [comment]
> File > Open Recent is seeded only from files you open via File > Open..., the command line or DND.
> 
> A workspace scoped history is accessible via `Cmd+P`.

Got it, thanks.
