### ISSUE TITLE
Debug mode doesn't stop/pause at breakpoints

### ISSUE THREAD

**Issue by nguyendviet** [microsoft/vscode#91513]
Version: 1.42.1
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
OS: Darwin x64 19.3.0

Steps to Reproduce:

1. I was using the same VSCode, on the same machine, to debug the same `.js` file and it worked fine. I was able to jump code line by line and check my variables after each iteration. Today, however, I do the same thing but the debug just runs through my `.js` file without pausing or stoping at any breakpoint. 
2. The `Debug toolbar` just appears in less than half a second and I cannot use F5 or click on it to pause it.

I only get this from the terminal:

```bash
/Users/viet/.nvm/versions/node/v10.16.0/bin/node --inspect-brk=39702 rotting-oranges.js 
Debugger listening on ws://127.0.0.1:39702/9e12a5d7-3a98-424c-9c8d-3af50be96e4b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
```

Here's my `launch.json`:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/rotting-oranges.js"
        }
    ]
}
```

I've tried:

- Restart my computer.
- Use VSCode on my work macbook to run the debug on other `.js` files and the debug never stops at any of the breakpoints.
- Make a simple for loop with a bug just to make sure I actually have a bug but the debug still doesn't stop or pause.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Does it pause if you add a `debugger` statement to the file?

**Comment by nguyendviet** [comment]
No, it doesn't. Same behaviour: The toolbar quickly showed up and disappeared.
![Screenshot 2020-02-26 at 09 15 24](https://user-images.githubusercontent.com/30057363/75353129-d882ec00-5878-11ea-85d1-9b1fcfdebb02.png)

The `debugger` works if I run `node inspect rotting-oranges.js`:

```bash
$ node inspect rotting-oranges.js 
< Debugger listening on ws://127.0.0.1:9229/2114d303-4d48-421b-a52f-67a369920b43
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
Break on start in file:///.../rotting-oranges.js:1
> 1 /**
  2  * https://leetcode.com/problems/rotting-oranges/
  3  * In a given grid, each cell can have one of three values:
debug> 
```

I've tried adding:  `"protocol": "inspector"` to the `launch.json` file but it still doesn't work.

**Comment by roblourens** [comment]
Could you set `"trace": true` in your launch config, try again, and share the log file from the debug console?

**Comment by nguyendviet** [comment]
Thank you @roblourens  for bearing with me. I've done it and received nothing.
![Screenshot 2020-02-26 at 11 35 34](https://user-images.githubusercontent.com/30057363/75366132-3a008600-588c-11ea-902d-bd821a68d109.png)

**Comment by roblourens** [comment]
Check the debug console

**Comment by nguyendviet** [comment]
Sorry. I should've included this. It still shows the same thing I described above in my first post:
<img width="1124" alt="Screenshot 2020-02-26 at 19 53 50" src="https://user-images.githubusercontent.com/30057363/75402032-c97c5800-58d1-11ea-84f5-bbb0646e7e07.png">

**Comment by roblourens** [comment]
Well we set the breakpoints and they were bound to the right lines but never hit. Are you sure those lines of code were running?

**Comment by nguyendviet** [comment]
Oh! Thank you @roblourens . I was confused between the different files I was trying to run. At one point, I reconfigured the `launch.json` and the code of the `program` was actually not executed. Sorry.
