### ISSUE TITLE
Running make command in a shell inside tasks.json results in an error and 

### ISSUE THREAD

**Issue by Akidus** [microsoft/vscode#91518]
- VSCode Version: 1.42.1
- OS Version: Windows_NT x64 10.0.17763 (Windows 10 Pro)

Steps to Reproduce:
1.  Ctrl + Shift + B -> Build DEBUG

Does this issue occur when all extensions are disabled?: YES

I have an issue when I run the `Build DEBUG` task I get an error **AFTER** it successfully compiles (as far as I'm aware).
This is my error:

![image](https://user-images.githubusercontent.com/13293994/75311412-e3576580-5813-11ea-809d-828c0e09dc8d.png)

If I run the command `make Debug -j -s 2>&1` inside `mingw32.exe`, the command executes successfully.  Command Prompt results in a similar error. 
I tried setting the type to the process `mingw32` because it is set in PATH and CMD can call it, but it also gave me an error because it's not a recognized type. 

I am trying to run OpenFrameworks with VScode but I continue to run into this error. 

Another error that continues to appear is with C++ Intellisense plugin. I set the include paths in the `c_cpp_properties.json`:

`{
    "env": {
        "ofPath": "C:/Developer/of_v0.11.0_vs2017_release"
    },

            "name": "Win32",
            "includePath": [
                "C:/msys64/mingw32/include/c++/9.2.0",
                "C:/msys64/mingw32/i686-w64-mingw32/include",
                "${ofPath}/libs",
                "${ofPath}/addons",
                "${ofPath}/libs/openFrameworks",
                "${ofPath}/libs/openFrameworks/3d",
                "${ofPath}/libs/openFrameworks/app",
                "${ofPath}/libs/openFrameworks/communication",
                "${ofPath}/libs/openFrameworks/events",
                "${ofPath}/libs/openFrameworks/gl",
                "${ofPath}/libs/openFrameworks/graphics",
                "${ofPath}/libs/openFrameworks/math",
                "${ofPath}/libs/openFrameworks/sound",
                "${ofPath}/libs/openFrameworks/types",
                "${ofPath}/libs/openFrameworks/utils",
                "${ofPath}/libs/openFrameworks/video",
                "${ofPath}/libs/boost/include",
                "${ofPath}/libs/cairo/include",
                "${ofPath}/libs/curl/include",
                "${ofPath}/libs/fmodex/include",
                "${ofPath}/libs/FreeImage/include",
                "${ofPath}/libs/freetype/include",
                "${ofPath}/libs/glew/include",
                "${ofPath}/libs/glfw/include",
                "${ofPath}/libs/glm/include",
                "${ofPath}/libs/json/include",
                "${ofPath}/libs/pugixml/include",
                "${ofPath}/libs/rtAudio/include",
                "${ofPath}/libs/tess2/include",
                "${ofPath}/libs/uriparser/include",
                "${ofPath}/libs/utf8/include"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "",
                "path": [
                    "${ofPath}/libs",
                    "${ofPath}/addons",
                    "${ofPath}/libs/openFrameworks"    
                ]
            },
            "intelliSenseMode": "clang-x64",
            "compilerPath": "C:/msys64/mingw32/bin/g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}`

Yet, I continue to see this error with all header files I include:
`#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Developer\openframeworks\14_vscode\src\main.cpp).C/C++(1696)
cannot open source file "cairo.h" (dependency of "ofMain.h")C/C++(1696)`
From what I can tell, cario.h may have issues, but that's none of my concern because my code compiles and runs fine with `mingw32.exe`.

Are there any temporary workarounds to these issues for the time being?

tasks.json:

```
{
    "version": "2.0.0",
    "shell":{
        "task": true
    },
    "tasks": [
        {
            "type": "shell",
            "label": "Build RELEASE",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make -j -s 2>&1 && make RunRelease",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Build DEBUG",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make Debug -j -s 2>&1",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Clean DEBUG",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make CleanDebug",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Clean RELEASE",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make CleanRelease",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Clean ALL",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make clean",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
         }
    ]
}
```

**Comment by roblourens** [comment]
Can you share the task you are running for the first issue?

For the second, please file this on the repo for the C++ extension https://github.com/microsoft/vscode-cpptools

**Comment by Akidus** [comment]
tasks.json:
`{
    "version": "2.0.0",
    "shell":{
        "task": true
    },
    "tasks": [
        {
            "type": "shell",
            "label": "Build RELEASE",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make -j -s 2>&1 && make RunRelease",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Build DEBUG",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make Debug -j -s 2>&1",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Clean DEBUG",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make CleanDebug",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Clean RELEASE",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make CleanRelease",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
        },
        {
            "type": "shell",
            "label": "Clean ALL",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "command": "make clean",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
              }
         }
    ]
}
`

**Comment by Akidus** [comment]
Updated. It is nearly the same as OpenFrameworks example tasks.json

**Comment by roblourens** [comment]
If this make command has to be run inside `mingw32.exe` then I assume it's failing because the task will run it in cmd.exe? Can you wrap it with `mingw32.exe /c "..."` or something like that?

**Comment by alexr00** [comment]
@Akidus can you try adding something like the following to your task?
```
"options": {
				"shell": {
					"executable": "full path of mingw32",
					"args": ["/c"] // You'll need to check what this is supposed to be with mingw32. /c in cmd means execute the following command
				}
			}
```
Otherwise, you'll need to figure out how to make your task run in cmd or powershell, which are what tasks usually use.

**Comment by Akidus** [comment]
I was unaware of the options for shell you could add. It worked without any args (It failed when there were arguments).
