### ISSUE TITLE
"Extension host terminated unexpectedly" error, tried everything, not going away.

### ISSUE THREAD

**Issue by Gray-Dark10227** [microsoft/vscode#91512]
- VSCode Version: 1.42.1 x64
- OS Version: Windows 10

Steps to Reproduce:

1. Run Visual Studio
2. Get the error

Does this issue occur when all extensions are disabled?: No

The extensions I have installed are:
Better Comments
Java support
Java compiler
Java dependency check
Java pack
Java test
Java debug
I use VS Code for Java development, hence all the java extensions.

**Comment by roblourens** [comment]
Does it happen if you start with `--disable-extensions`?

Can you try downloading the Insiders' build and installing the same extensions and tell me whether it happens there? https://code.visualstudio.com/insiders
