### ISSUE TITLE
cpu usage too high on idle

### ISSUE THREAD

**Issue by rizalarsal** [microsoft/vscode#91523]
- VSCode Version: 1.42.1
- OS Version: Mac OS Catalina 10.15.1

Steps to Reproduce: 

1. open react native project folder using VS Code. 
2. just wait, then the fan will start active within 2 minute.
3. the fan keep on even i wait 30 minute more, all heated up. i cant continue to risk my mac. using battery will definitley drained within 1 hour.

Does this issue occur when all extensions are disabled?: Yes

note:
1. last year i have angular project, there nothing wrong. all good.
2. just started a react native project few day ago. i cant continue, because this issue. 
4. i don't do anything. the app that using significant energy is always visual code, it doesn't disappear from list until i close it.
5. i test other editor goes up only 5 minute after open project, then it become cool. vscode running permanently.

-------

Version:          Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS Version:       Darwin x64 19.0.0
CPUs:             Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)
Memory (System):  8.00GB (0.10GB free)
Load (avg):       3, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    74	  2538	code main
    0	    33	  2541	   gpu-process
    0	   180	  2544	   window (SignInScreen.js — mtms)
    0	    33	  2847	     extensionHost
    0	    16	  2849	       electron_node tsserver.js 
   96	    74	  2850	       electron_node tsserver.js 
    0	    16	  2859	         electron_node typingsInstaller.js typesMap.js 
    0	    25	  3222	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=2847
    0	    16	  2848	     watcherService
    0	    33	  3247	     searchService
    0	    49	  2844	   shared-process
    0	     0	  3897	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (SignInScreen.js — mtms)
|    Folder (mtms): 1786 files
|      File types: gz(766) json(697) js(133) png(45) bin(10) xml(7) lock(6)
|                  properties(5) gradle(3) gitignore(2)
|      Conf files: package.json(1) settings.json(1)

**Comment by gjsjohnmurray** [comment]
Are you able to test with the Insiders build?

**Comment by rizalarsal** [comment]
where i can download insider build ?

**Comment by mjbvz** [comment]
https://code.visualstudio.com/insiders/

*(or just type `vscode insiders build` in your preferred search engine!)*

**Comment by rizalarsal** [comment]
ok,
i cant reproduce the issue using insiders build.

------
Version:          Code - Insiders 1.43.0-insider (b0be0672c210f1fa76109ce675365bb785657e84, 2020-02-26T05:28:00.237Z)
OS Version:       Darwin x64 19.0.0
CPUs:             Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)
Memory (System):  8.00GB (1.51GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    90	 10905	code-insiders main
    0	    49	 10907	   gpu-process
    0	    16	 10910	   utility
    0	    98	 11219	   shared-process
    0	     0	 11938	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   303	 11241	   window (App.js — mtms)
    0	    98	 11242	     extensionHost
    0	    74	 11268	       electron_node tsserver.js 
    0	   336	 11269	       electron_node tsserver.js 
    0	    66	 11273	         electron_node typingsInstaller.js typesMap.js 
    0	    33	 11279	       /private/var/folders/zj/g7tjfz752xv2vkqcfsvrlxm00000gn/T/AppTranslocation/AE79D2D8-89C2-4C89-B842-0A1E27B9DCEF/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /private/var/folders/zj/g7tjfz752xv2vkqcfsvrlxm00000gn/T/AppTranslocation/AE79D2D8-89C2-4C89-B842-0A1E27B9DCEF/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=11242
    0	    33	 11244	     watcherService

Workspace Stats: 
|  Window (App.js — mtms)
|    Folder (mtms): 1786 files
|      File types: gz(766) json(697) js(133) png(45) bin(10) xml(7) lock(6)
|                  properties(5) gradle(3) gitignore(2)
|      Conf files: package.json(1) settings.json(1)
