### ISSUE TITLE
Debug: 2 welcome experiences

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91524]
![image](https://user-images.githubusercontent.com/900690/75317213-ab7a0d80-5867-11ea-9ab8-1f4ec9c26b8f.png)

Steps to Reproduce:

1. opened https://vscode-web-test-playground.azurewebsites.net/?enter=true
2. opened debug viewlet
3. clicked on create launch config
4. opened markdown file
5. started debug
6. stopped debug

**Comment by gjsjohnmurray** [comment]
Maybe dup of #91426

**Comment by isidorn** [comment]
Yeah, ti is a duplicate. Thus closing.
Thanks for filling and thanks for help @gjsjohnmurray
