### ISSUE TITLE
Search editor usability refinements

### ISSUE THREAD

**Issue by lucascosti** [microsoft/vscode#91520]
A few refinements the the search editor preview that I'd love to have:

* Include the count of results in the `search.action.openNewEditor` top-of-the-screen interface, like there is in the bottom panel (e.g. _20 results in 15 files_).
* Remember the `Show context` setting (both its activation and the number of lines). I have to re-set it each time a do a new search.

cc @JacksonKearl

**Comment by JacksonKearl** [comment]
> Include the count of results in the search.action.openNewEditor top-of-the-screen interface, like there is in the bottom panel (e.g. 20 results in 15 files). 

We do include the result count at top of the editor. If you're on Insiders you should see it. Let me know if that works for you

Remembering the show context setting fits in with a larger picture of what inputs should be saved across searches.

**Comment by JacksonKearl** [comment]
See #89353 for saving search config.

**Comment by lucascosti** [comment]
Thanks for the reply, @JacksonKearl!

> We do include the result count at top of the editor. If you're on Insiders you should see it. Let me know if that works for you

Yep, confirmed. I was using the current stable release 😊 

It looks like another issue that I am having is also fixed in Insiders: parsers like cSpell were crashing the search editor for large result sets. This doesn't seem to happen on Insiders 🎉 

> Remembering the show context setting fits in with a larger picture of what inputs should be saved across searches.

Thanks for the link to #89353. Although I think that the context setting is probably something people would not want to change frequently  (at least compared with case matching, whole words, etc), it makes sense to it track there.

I think we can close out this one 🙂
