### ISSUE TITLE
Screen issue

### ISSUE THREAD

**Issue by flagtrax** [microsoft/vscode#91522]
- VSCode Version:1.42
- OS Version:Windows 10

Steps to Reproduce:

1.When launched the latest version appears on the screen of my Lenovo ideapad 320 about 2/3 full screen with the title bar unseen (hidden at the top of the screen) It can't be pulled down, the window won't resize and renders it totally useless. This is the only app with this behavior, I'd been using it for about 2 months without issue until the update was installed.
2.

Does this issue occur when all extensions are disabled?: Yes/No Can't get that far.
![Capture](https://user-images.githubusercontent.com/13992362/75315668-4efbfb80-5831-11ea-84fe-43787b3eb52e.PNG)

**Comment by IllusionMH** [comment]
Just in case: Quick fix should be focus VS Code, <kbd>Win</kbd>+<kbd>↑</kbd>, grab window title and drag it to visible area.

Have you used VS Code with 2 monitors configuration? Are you using system scaling?

**Comment by flagtrax** [comment]
Hi, thanks for a rapid response!
1 I can't see the title bar the top (appx) 20% of the window is off the top
of the screen. 2 yes I have been work with 2 screens.
I accidently found that "grabbing" the right border of the window "resets"
(for lack of a better term) the window to a restored down state, with all
elements shown. Maximizing the window works, and closing and reopening
works as well.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
