### ISSUE TITLE
C++ code highlight anomaly

### ISSUE THREAD

**Issue by foreignmeloman** [microsoft/vscode#91529]
Seems like VS Code does not highlight correctly function calls which have "pthread_t" prefix in the name:

Examples:
pthread_threadid_np();
pthread_tfoo()

Screenshot:
![image](https://user-images.githubusercontent.com/11769352/75319975-1981fd00-5887-11ea-9001-a398480f8523.png)

**Comment by gjsjohnmurray** [comment]
Are you using any C++ extensions? Does the problem also happen if you launch with all extensions disabled? If not, please report the issue to the repository of the extension.

**Comment by foreignmeloman** [comment]
No C++ extension was installed, I also tried the latest insiders build with no extensions and default theme. The result is the same.

Version: 1.43.0-insider (system setup)
Commit: b0be0672c210f1fa76109ce675365bb785657e84
Date: 2020-02-26T05:30:24.470Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.16299

![image](https://user-images.githubusercontent.com/11769352/75332947-b2704280-589e-11ea-9358-130a1dc84b03.png)

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/452
