### ISSUE TITLE
"editor.colorDecorators" is not respected in language configs

### ISSUE THREAD

**Issue by Jupakabra** [microsoft/vscode#91533]
Version: 1.43.0-insider
Commit: b0be0672c210f1fa76109ce675365bb785657e84
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a css file
```css
.test {
    color: #ff0000;
}
```
2. Change css language decoration to none
```json
{
    "[css]": {
        "editor.colorDecorators": false
    }
}
```
3. Reopen css file again, color decorator is still there.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/323878/75368233-424dc680-5876-11ea-92cf-f6ff006785b5.png)

**Comment by roblourens** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/323878/75368233-424dc680-5876-11ea-92cf-f6ff006785b5.png)

Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by Jupakabra** [comment]
Ye I tested on live and on insiders (clean zip download without settings) on b0be067, might need to reopen file it goes back to decorations.
![image](https://user-images.githubusercontent.com/12775282/75370733-3db4fc80-58ce-11ea-8b6e-4ce349960f35.png)

**Comment by roblourens** [comment]
Ah I see it now

**Comment by joaomoreno** [comment]
@aeschli @jrieken Actually I do not know who this should be addressed to, so sorry for the spam! 🙏

**Comment by Jupakabra** [comment]
@roblourens guess you forgot to remove "needs more info" tag 😃

**Comment by Jupakabra** [comment]
Can this be reopened @roblourens ? 😢
