### ISSUE TITLE
ILinksList.dispose is never called

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#91536]
We use it via Monaco and it's never called. Looking at the code, links are used only here: https://github.com/microsoft/vscode/blob/b0be0672c210f1fa76109ce675365bb785657e84/src/vs/editor/contrib/links/getLinks.ts#L77 but not dispose method. And then provider itself is registered as disposable, although `LinkProvider` does not have `dispose` method.

Do we overlook anything? If not it would mean that https://github.com/microsoft/vscode/blob/3de5a8a6a2ea77f08174f1c5341248401a377973/src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts#L473-L477 is never called either and the extension host process leaking links.

**Comment by jrieken** [comment]
It's called [here](https://github.com/microsoft/vscode/blob/334b664a8bfb034a2697551ecf36b9931dbda179/src/vs/editor/contrib/links/links.ts#L205) via [this](https://github.com/microsoft/vscode/blob/481485b354b6a32eac31101daaf8cd1cc81787da/src/vs/editor/contrib/links/getLinks.ts#L81). Please add a repro sample

**Comment by akosyakov** [comment]
It is reproducible with any tsconfig.json file with links.

You are right, provider is added as disposable, but provider is not disposable. Instead a link should be added:
<img width="1312" alt="Screenshot 2020-02-26 at 13 40 02" src="https://user-images.githubusercontent.com/3082655/75345833-c9fafb80-589d-11ea-8941-b2047db951ee.png">
<img width="1312" alt="Screenshot 2020-02-26 at 13 40 06" src="https://user-images.githubusercontent.com/3082655/75345841-ca939200-589d-11ea-81d2-765679c08f3a.png">

When dispose is called, disposable storage is empty:
<img width="1312" alt="Screenshot 2020-02-26 at 13 40 54" src="https://user-images.githubusercontent.com/3082655/75345847-cc5d5580-589d-11ea-86b1-cc6a9f1de01c.png">

**Comment by jrieken** [comment]
> You are right, provider is added as disposable, but only if it is disposable.

🤦‍♂ D'oh... Yes this shouldn't be the provider but the result of it...
