### ISSUE TITLE
Revealing settings or keybinding files in explorer

### ISSUE THREAD

**Issue by Jupakabra** [microsoft/vscode#91534]
Version: 1.43.0-insider
Commit: b0be0672c210f1fa76109ce675365bb785657e84
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open settings.json in json format.
2. Reveal in explorer option is not there in the context menu or through a shortcut

Does this issue occur when all extensions are disabled?: Yes

Was this purposely removed for settings? Because it used to work before and now there is no way to get to settings files for backup or copy purposes.

**Comment by roblourens** [comment]
@aeschli maybe https://github.com/Microsoft/vscode/commit/d0fd0e2c20517b01fe1f59a8c2de4f23f03a019a? I think the settings file is not file: scheme

**Comment by sandy081** [comment]
@aeschli Can we enable this to the resource scheme - `vscode-userdata` and not in web?

**Comment by Jupakabra** [comment]
Doesn't seem to work, at least in zip version.
It opens current project parent folder instead, or just documents folder if no project is loaded.
Also, current stable release allows opening it through a shortcut correctly, even thought reveal in explorer is not visible.
![settings](https://user-images.githubusercontent.com/12775282/101042714-2bb36900-3586-11eb-93c0-1e75681ae3f6.gif)

```
Version: 1.52.0-insider
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by roblourens** [comment]
@meganrogge you can reopen issues when you add verification-found

**Comment by sandy081** [comment]
It was working while fixed. After bisect, I figured out that Fix of https://github.com/Microsoft/vscode/issues/110353 broke this.

@isidorn FYI

**Comment by isidorn** [comment]
@sandy081 thanks a lot for investigating and for bisecting!
I reverted my commit and verified this now works as expected

**Comment by isidorn** [comment]
@JacksonKearl the bot is bullying me here :D

**Comment by rzhao271** [comment]
\closedWith 8f410da

**Comment by JacksonKearl** [comment]
@isidorn looking at the timeline I can't figure out why it was repeatedly commenting... it's expected to comment if `author-verification-requested` is added without a closing commit being found, but I don't know why it'd do it multiple times. I'd expect it to remove the `author-verification-requested` label instead.
