### ISSUE TITLE
Cannot activate the 'JavaScript Debugger (Nightly)' extension

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#91530]
Issue Type: <b>Bug</b>

* Open a `package.json` file
* The following error prompt appears

![image](https://user-images.githubusercontent.com/5047891/75321600-65c24280-5871-11ea-9fbc-748ef6e3f935.png)

VS Code version: Code - Insiders 1.43.0-insider (89cafb24e5d75a0c8d561a6cdd95e93b5679e152, 2020-02-25T05:28:31.292Z)
OS version: Darwin x64 19.3.0

**Comment by bpasero** [comment]
@alexdima I think this should be fixed if you update to todays insider.

**Comment by alexdima** [comment]
:+1: You're right, sorry about that.
