### ISSUE TITLE
Support group ordering

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#9153]
- VSCode Version: 1.3
- OS Version: OSX

Steps to Reproduce:

1. Add menus to the explorer context menu
2. Run extension
3. Note the sorting order where your contributions are at the top

![image](https://cloud.githubusercontent.com/assets/1487073/16778866/c96040fa-4824-11e6-9087-fc557429de88.png)

Related to #8756?

The source for the extension is here: https://github.com/chrisdias/vscode-opennewinstance

**Comment by jrieken** [comment]
@chrisdias What is you see is the implemented behaviour. What is did you expect?

**Comment by chrisdias** [comment]
Assuming I don't have the ability to control the exact location in the list, I would expect the navigation section of the menu to be sorted:

New File
New Folder
Open in Terminal
Open New Workbench Here
Reveal in Finder
Scope Workbench to Here

Alternatively, can I create my own group and how would I position that group between the Navigation (top) and the "Find in Folder" section?

**Comment by jrieken** [comment]
> Alternatively, can I create my own group and how would I position that group between the Navigation (top) and the "Find in Folder" section?

That we don't support yet. Today the `navigation` group comes first and contributions to that group come first as well. Any other group comes at the end, ordering of group is still to be implemented. The idea is that we have a set of groups like `navigation`, `modification` etc with a fixed order.

**Comment by chrisdias** [comment]
I like the idea of ordering of core menu groups, it keeps the experience consistent even if there are 100s of extensions contributing to the menus.  

I realize now that we don't sort the built-in menus, so having the contribution be sorted in that list doesn't make sense either.  However, I think I might like to see contributed menus after the built-in menus within a group rather than before. Again, I think this would help make the experience be more consistent regardless of the extensions that are loaded.

**Comment by jrieken** [comment]
Groups are now sorted lexically with the exception of `navigation` which always comes first. Within groups you can sort by adding number like so `navigation@10` or `navigation@-.9`. Legacy commands have the implicit order of zero (`navigation@0`)
