### ISSUE TITLE
git gutter and file status no longer working with git 2.25 on mapped network drive

### ISSUE THREAD

**Issue by krskrs** [microsoft/vscode#91548]
![immagine](https://user-images.githubusercontent.com/2150068/75331377-dd4c9d80-5882-11ea-9d16-1265c7ae6bec.png)

I saw several filed issues related to casing differences with latest git for windows >2.25, but I believe this one is different. 
I work on repositories mapped on a network drive, and after upgrading git to 2.25, gutter and file status in VScode file explorer are no longer updating on changes.
This is what's happening:

![immagine](https://user-images.githubusercontent.com/2150068/75331516-27ce1a00-5883-11ea-8beb-4ec42bc561db.png)

And I verified from command prompt that issuing (W: is amapped network drive)

```
W:\mti_sysadmin\ansible\misc-server>git rev-parse --show-toplevel
//centos7-kvm-dev/home_krs/mti_sysadmin/ansible

```

while with previous git versions (**drive letter was used, instead of unc path**)

```
W:\mti_sysadmin\ansible\misc-server>git rev-parse --show-toplevel
W:/mti_sysadmin/ansible

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Damn it, Git 2.25 broke a lot of stuff.

As a workaround, I suggest you downgrade your git version.

**Comment by krskrs** [comment]
Hi @joaomoreno thanks! I had already done it (downgraded git to 2.24) to be able to keep on working. And yes, I hear you! from developer to developer, they broke a lot of stuff, probably just changing an API call to improve some other things (I found something in the git for windows repository while investingating the issue). Anyway, thank you and keep up the good work!

**Comment by gdsotirov** [comment]
I'm having exactly the same issues with repositories on mapped network drive after upgrading to Git 2.25.1, so I'll downgrade waiting for the next VSCode upgrade.

**Comment by sedwards2009** [comment]
Opening the folder in VSCode using the UNC path in the folder dialog, is another work around. Just navigate to your project in the dialog using `\\192.168.2.1\myshare\project` etc instead of going through the mapped network drive letter.

**Comment by eamodio** [comment]
To verify:

Open a repo over a network share and observe:
- Timeline should work
- Git "gutter" decorations should be displayed
