### ISSUE TITLE
Add issue and user completion item kinds

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91541]
I've had several requests for this now: 
Custom icons:
https://github.com/microsoft/vscode-pull-request-github/issues/1529

Codicons:
![image](https://user-images.githubusercontent.com/38270282/75328392-3cf47a00-587e-11ea-9e48-d56fa12c866e.png)

**Comment by jrieken** [comment]
Yes - we don't want to allow arbitrary custom icons but supporting `ThemeIcon` is something that we should discuss.

**Comment by alexdima** [comment]
Today, we already allow extensions to contribute custom icons to our UI. The custom icons can be very prominent rendered too, like in the editor title area. So IMHO the door is already open for custom icons.

I would like to suggest that we allow custom icons in the suggest widget as well, to cover cases such as this, where seeing the profile picture might be helpful:

![image](https://user-images.githubusercontent.com/5047891/75327133-26e5ba00-587c-11ea-9459-8174ea8a8b78.png)

I agree that this is difficult with LSP, but perhaps we can keep this part out of LSP.

**Comment by jrieken** [comment]
@alexr00 fyi I have pushed proposed API which adds two new completion item kinds for user and issue 👇 

<img width="683" alt="Screenshot 2020-03-19 at 11 29 59" src="https://user-images.githubusercontent.com/1794099/77085802-1f3fae00-6a01-11ea-89e4-3362d3e8cd3d.png">

**Comment by alexr00** [comment]
@jrieken good stuff, thank you! I'll adopt it tomorrow.
