### ISSUE TITLE
unable to open from console file with line number.

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode#91547]
- VSCode Version: 1.42
- OS Version: ubuntu 18.04

Many developer tools report error in format <file>:line number, for example (gcc, clang)
When I try to open file with such format (ex: art/libdexfile/external/dex_file_supp.cc:58 ) from Quick Open (CTRL+P) it is ok.
But when I try to open such file from console:

`code art/libdexfile/external/dex_file_supp.cc:58 `

VSCode open empty file with name dex_file_supp.cc:58 

I understand, that symbol ":" can be part of filename, But it is not common case.  Also I think it will be more usable to can ability to just copy paste part of error containing line number with colon format and just open it vis VSCode instead of converting it in separate format:

`code art/libdexfile/external/dex_file_supp.cc +58 `

**Comment by IllusionMH** [comment]
![image](https://user-images.githubusercontent.com/1312662/75344336-17c63280-58a3-11ea-98ba-1407c3889784.png)
It is supported by VS Code but you need to use `--goto` or `-g` to specify that path has line/character info

`code -g art/libdexfile/external/dex_file_supp.cc:58` would do what you expect

**Comment by dibalavs** [comment]
Thanks.
