### ISSUE TITLE
Sync: Skip `First time Sync` dialog if nothing changed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#91545]
Testing  https://github.com/microsoft/vscode/issues/91226 on Windows

1. Turn on Sync
2. Turn off Sync
3. Turn on Sync

The `First time Sync` dialog comes up:

![image](https://user-images.githubusercontent.com/22350/75331964-df632c00-5883-11ea-8a90-28494f27438a.png)

A few things:

- The title of the dialog looks weird, should it rather just be `Sync`?
- The first sentence is also missing a pronoun. Passive suggestion: `It looks like this is the first time Sync is set up.`
- Could we skip this dialog altogether, if we preemptively detect there are no changes coming in from the cloud?

**Comment by sandy081** [comment]
Updated the labels. 

Will look into skipping this dialog if nothing has changed in next milestone.

**Comment by connor4312** [comment]
Could not verify due to https://github.com/microsoft/vscode/issues/94223, removing the tag so someone else can try

**Comment by alexr00** [comment]
Verified the language in the dialog.
