### ISSUE TITLE
UX: Improve menu File > Preferences > Sync

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#91544]
Testing https://github.com/microsoft/vscode/issues/91226 on Windows

![image](https://user-images.githubusercontent.com/22350/75331722-80051c00-5883-11ea-8b7c-c70fdb9d6fde.png)

Regarding the `File > Preferences > Sync is on` menu:

- `Sync is on` looks like a bug: should we maybe call it `Sync...`, since it will open the command palette with all the sync commands?
- Or, even better, should it simply be a `Sync` item with a submenu containing all the sync actions?

**Comment by sandy081** [comment]
Changed the label and will look into sub menu in next milestone

**Comment by misolori** [comment]
The one thing that this does is remove the ability to see if Sync is on from a single click. So this now adds an extra click and the next screen doesn't explicitly say it is on (you can guess by the "activity" item):

![image](https://user-images.githubusercontent.com/35271042/75377661-21da3800-5887-11ea-8d85-540ff448994e.png)

**Comment by sandy081** [comment]
Agreed. Reverted the label change.

**Comment by sandy081** [comment]
The current actions and menus are good enough so there are no plans to add sub menus. Hence closing this.
