### ISSUE TITLE
vscode fails to fetch correct vscode.d.ts without installing yo

### ISSUE THREAD

**Issue by dilin-MS** [microsoft/vscode#91558]
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
There is a weird dependency between yo and vscode.
1. On a very clean machine, I install node, npm and my repo. 
2. Run `npm i` to install dependency successfully. **BUT**, warnings saying
```
npm WARN lifecycle vscode-iot-workbench@0.11.0~postinstall: cannot run in wd vscode-iot-workbench@0.11.0 node ./node_modules/vscode/bin/install (wd=/mnt/c/Users/dilin/workspace/repo/vscode-iot-workbench)
npm WARN lifecycle vscode-iot-workbench@0.11.0~prepare: cannot run in wd vscode-iot-workbench@0.11.0 npm run compile (wd=/mnt/c/Users/dilin/workspace/repo/vscode-iot-workbench)
```

3. I have   ```"engines": {"vscode": "^1.39.0"}``` in my pacakge.json file. But the npm compile bring me the wrong `vscode.d.ts` file. I notice that because I cannot find `ExtensionKind` in `vscode.d.ts` file. I have installed the correct `vscode@1.1.36` and my vscode is the latest 1.42.1.
It cost me a lot of time to finally figure a way out: I have to first install `yo` using `npm i -g yo` and yo will somehow configure a vscode-related environment for my vscode, enabling vscode to detect its own version.
I found the tricky method [here](https://github.com/Microsoft/vscode-extension-vscode/issues/143#issuecomment-478565843).

4. After installing yo, vscode can succeed to fetch the correct vscode.d.ts now. But neither the dependency nor the error message is making no sense! Why can't I install the correct vscode.d.ts file with a correct vscode engine and right node, npm version?

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you share your repo or the package.json?

**Comment by octref** [comment]
I cannot repro. I'm running `npm i` in a folder with only this package.json:

```json
{
  "name": "vscode-iot-workbench",
  "engines": {
    "vscode": "^1.39.0"
  },
  "scripts": {
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
  "devDependencies": {
    "vscode": "^1.1.33"
  }
}
```

Here's the output:
```
 foo > npm i       
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> vscode-iot-workbench@ postinstall /Users/octref/Code/foo
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.39.0
Found minimal version that qualifies engine range: 1.39.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN vscode-iot-workbench@ No description
npm WARN vscode-iot-workbench@ No repository field.
npm WARN vscode-iot-workbench@ No license field.

added 86 packages from 528 contributors and audited 129 packages in 6.507s
found 0 vulnerabilities
```

Your machine for some reason didn't run the postinstall script. Can you run it manually?

**Comment by dilin-MS** [comment]
If you have ever ran the `yo` command on your machine then you will not encounter this issue. Yesterday I try it on my clean machine which just re-installed system.

Can you check the logic of fetching vscode.d.ts? Will it be smoothly successful **on a clean machine** if I have installed the correct VS Code, node and npm? It seems not. And from [here](https://github.com/Microsoft/vscode-extension-vscode/issues/143#issuecomment-478565843) I know I am not the only one met this issue. 

When and where is the `process.env.npm_package_engines_vscode` being set? Thank you.

**Comment by octref** [comment]
Create a new folder with below package.json:

```json
{
  "name": "test",
  "scripts": {
    "postinstall": "node test.js"
  }
}
```

`test.js`:

```js
console.log(JSON.stringify(process.env, null, 2))
```

Run `npm i`. See all the `npm_packages` environment variables.

**Comment by dilin-MS** [comment]
The issue has resolved for me since I run the `yo` command. I came here to open this issue because the solution makes no sense and error message is not helpful, either. 

I was hoping vscode can better handle this situation and provide better solution to make vscode a more wonderful tool. 

If you plan to do nothing, then I hope this can at lease help other people who encounter the same issue and save them from mud.

**Comment by octref** [comment]
Your error message indicates here's the issue:

```js
var engine = process.env.npm_package_engines_vscode;
if (!engine) {
    exitWithError('Missing VSCode engine declaration in package.json.');
}
```

https://github.com/microsoft/vscode-extension-vscode/blob/0090df8e01649f76a8a3a72d7edb78aa41c7e910/bin/install#L12-L15

First, I can't really repro your issue. I tried that in parallels VM.
Second, `vscode` package is deprecated. See https://github.com/microsoft/vscode-extension-vscode
