### ISSUE TITLE
Open response time is long

### ISSUE THREAD

**Issue by mannokage** [microsoft/vscode#91550]
Issue Type: <b>Bug</b>

The software runs for a long time, and there is a period of delay after the software is started.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (11.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-subtitles|ast|0.3.2
vscode-eslint|dba|2.1.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
csharp|ms-|1.21.12
js-atom-grammar|ms-|0.1.14
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|3.9.20200225
debugger-for-chrome|msj|4.12.6
java|red|0.57.0
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by roblourens** [comment]
Please give more details about the problem and what you are seeing
