### ISSUE TITLE
Revisit use the Thenable in vscode.d.ts

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#91552]
When VS Code's API happened, the native Promise wasn't a well established thing yet. Because of that we went with the `Thenable` type - which is like a promise. We should consider to revisit this, there is two cases

1. the API returns a promise
1. the API accepts a promise

The former case could be changed to spec that a promise is being returned, the latter would be making the API stricter...

related to https://github.com/microsoft/vscode/issues/91549

**Comment by dbaeumer** [comment]
I actually moved away from Thenable in all my npm modules I maintain.
