### ISSUE TITLE
Mismatch between tasks.json "type" default value from schema and reality

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#91553]
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

(also tested with Insider's build b0be0672c)

____

According to the `tasks.json` schema / completion details, tasks use `"type": "shell"` by default:

![](https://i.imgur.com/WkT8Pkg.png)

To me this means that there should be no difference between having an explicit `"type": "shell"` and not having `"type"` specified at all.

___

In practice, this does not seem to be the case. To reproduce, create a `tasks.json` that looks like this:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "test",
			"command": "test"
		}
	]
}
```

Also add this `test.cmd` file to your workspace root:

```cmd
echo hello
```

It may be necessary to have `"terminal.integrated.shell.windows": "cmd.exe"` in the settings as well.

Running the `test` task results in this error:

```
> Executing task: <workspace-path>\test  <

The terminal shell path "<workspace-path>\test" does not exist
```

___

Now add an explicit `"type": "shell"` to the task - it now works as expected:

```
> Executing task: test <


<workspace-path>>echo hello 
hello
```

**Conclusion: either the default value of `"type"` is not actually `"shell"`, or something else is wrong.**

**Comment by dbaeumer** [comment]
Verified that `process` is now the default value.
