### ISSUE TITLE
Cannot reopen folders closed by Cmd+W in 1.3

### ISSUE THREAD

**Issue by segawm** [Microsoft/vscode#9156]
- VSCode Version: 1.3
- OS Version: Mac OS 10.11.5

Steps to Reproduce:

1. Open any folder.
2. Press Cmd+W or click red [x] button, then window will be closed.
3. Run vscode, then no folder is opened.

1.2.1 could reopen the folder.

**Comment by bpasero** [comment]
This is standard Mac OS X behaviour.

**Comment by segawm** [comment]
All previous versions reopened the folder closed by Cmd+W.
1.3 broke it. Strange...

**Comment by bpasero** [comment]
@segawm that is because all previous versions of VS Code behaved wrong and not accordingly to Mac OS UX guidelines.
