### ISSUE TITLE
Custom editor: viewType => id

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91563]
Refs: #91325

I am always confused by `viewType`. I suggest to rename it to `id`. I am not sure how much value we get out of keeping the name. Is there any reason? A command for example also registers with an `id` I think.

**Comment by bpasero** [comment]
Hm, it looks like we simply call it `command` in `package.json` so maybe it should be `editor`?

![image](https://user-images.githubusercontent.com/900690/75341863-987e3200-5895-11ea-860f-dc2b2c32621b.png)

**Comment by mjbvz** [comment]
The name `viewType` comes from the `WebviewPanel` class:  https://github.com/microsoft/vscode/blob/a980d877773120a7aec99238701bad4418d3f566/src/vs/vscode.d.ts#L6413

I feel it makes sense to use the same name for custom editors too. Having the `contributions` also use `viewType` also makes sense to me
