### ISSUE TITLE
Custom editor: find widget?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91564]
Refs: #91325

I think we need to revisit what it means to have the find widget enabled for a custom editor?

![image](https://user-images.githubusercontent.com/900690/75341765-6e2c7480-5895-11ea-98cd-db70fca42746.png)

Maybe better for now to only allow for the other option to retain the webview when hidden.

**Comment by mjbvz** [comment]
And specific concerns about allowing the find widget?

**Comment by bpasero** [comment]
@mjbvz how can I use it from my custom editor? I think it is a good idea to allow for it, I was just not sure how to utilize it.

**Comment by mjbvz** [comment]
Custom editors use the same find widget that we support for webviews:

![Screen Shot 2020-02-27 at 11 32 31 AM](https://user-images.githubusercontent.com/12821956/75479778-f291fc80-5954-11ea-88a7-44892da8946a.png)

The find operation itself is all handled by the webview (electron). In the future, we could also add hooks that let extensions control how the find operation works  but let's see if extension authors express interest in this
