### ISSUE TITLE
Strange viewlet title

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#91567]
Testing https://github.com/microsoft/vscode/issues/91326

See the title: RUN: START which is very strange.

<img width="360" alt="capture" src="https://user-images.githubusercontent.com/1931590/75342474-ce6fe600-5896-11ea-9f63-8f91299e42ba.png">

**Comment by isidorn** [comment]
Yeah, agree there is a bit of duplication there.
What title do you think would work here?

**Comment by dbaeumer** [comment]
Why not simple RUN:

**Comment by isidorn** [comment]
I think that makes sense.  We would need to allow views to control the title when they get merged fyi @sbatten

**Comment by sbatten** [comment]
similar to #89523
