### ISSUE TITLE
Duplicate sections in Debug viewlet

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#91566]
Testing https://github.com/microsoft/vscode/issues/91326

Tested the new PWA debugger (see item above) and tested the new Debugger Terminal. After running a simple main my debug viewlet looked like this:

<img width="360" alt="capture" src="https://user-images.githubusercontent.com/1931590/75342392-a3859200-5896-11ea-94c5-529f1b0bbe03.png">

**Comment by dbaeumer** [comment]
Actually every launch from the Debugger Terminal duplicate the section again.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/91426
