### ISSUE TITLE
Conflict between hover and diagnostics

### ISSUE THREAD

**Issue by henryju** [microsoft/vscode#91561]
- VSCode Version: 1.42.1
- OS Version: Fedora 31

(using VSCode Java and SonarLint, but I think it is a more general problem)

If code contains both some documentation and diagnostic hover, the UX is not good, and it is impossible to see the diagnostic hover.
![sonarlint_vscode_hover-2020-02-26_12 25 57](https://user-images.githubusercontent.com/281596/75341315-77691180-5894-11ea-8203-575de361d387.gif)

In the screen capture you can see the diagnostic hover briefly appearing, and almost immediately being replaced by the other (documentation) hover contributed by vscode-java language server.

**Comment by IllusionMH** [comment]
Hover block is scrollable and there should be visible scroll bar on the right (which is cropped on your recording).

You can just move your cursor over hover and scroll it.

**Comment by henryju** [comment]
You're right.
![image](https://user-images.githubusercontent.com/281596/75427170-46e1b000-5946-11ea-8ec8-3664eda670bb.png)

This is IMO not very practical to have to scroll to reach diagnostics (especially when documentation is long), but at least it is there.

Feel free to close this issue, or rename it "Long description hover make difficult to see diagnostic details"

**Comment by IllusionMH** [comment]
Same problem will be if they swapped - you get long diagnostics and have to 

You can use `>Go to Next Problem` (<kbd>Alt</kbd>+<kbd>F8</kbd>) or `>Go to Next Problem in Files` (<kbd>F8</kbd>) to get only problem info without need to scroll.

Otherwise it's duplicate of #29126 and #56525

**Comment by henryju** [comment]
OK, thanks for the reply.
