### ISSUE TITLE
Custom editor: "Reopen with" should only be shown if there is more than one choice

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91569]
Refs: #91325

Otherwise you are forcing a "..." menu on each editor group when tabs are disabled

![image](https://user-images.githubusercontent.com/900690/75342890-94ebaa80-5897-11ea-8019-aaf0c93b9777.png)

**Comment by bpasero** [comment]
vs stable:

![image](https://user-images.githubusercontent.com/900690/75342915-a03ed600-5897-11ea-91f7-9771de5b4c26.png)

**Comment by mjbvz** [comment]
This command only show ups in image and markdown files, correct?

**Comment by bpasero** [comment]
True, closing. Not sure what I was thinking, this seems to be working ok.
