### ISSUE TITLE
Custom editor: rename webview to panel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91568]
Refs: https://github.com/microsoft/vscode/issues/91325

`resolveCustomTextEditor(document: TextDocument, webview: WebviewPanel)` => `resolveCustomTextEditor(document: TextDocument, panel: WebviewPanel)`

Otherwise I end up typing `webview.webview` all the time.

**Comment by mjbvz** [comment]
Good suggestion! I'm going to change them to `webviewPanel` since that's what we use for the existing APIs in `vscode.d.ts`: https://github.com/microsoft/vscode/blob/a980d877773120a7aec99238701bad4418d3f566/src/vs/vscode.d.ts#L6494

**Comment by mjbvz** [comment]
Fixed. Just a d.ts update
