### ISSUE TITLE
Apply change to workspace is updating more than one file

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#91573]
Testing #91331

Not sure if it is an extension issue, hence filing it here.

- In VS Code workspace, search for term `pref`
- Edit first result and do some changes
- Now run `Apply Search Editor Changes to Workspace` 

🐛 More than one file gets updated.

**Comment by JacksonKearl** [comment]
I see, the lines sometimes contain only part of a line, so the change detector doesn't work correctly.

**Comment by JacksonKearl** [comment]
Tracking on the extension.
