### ISSUE TITLE
Setting sync: `Turn On` instead of `Turn on`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#91576]
Testing #91226

Enable setting sync:
![image](https://user-images.githubusercontent.com/6461412/75349163-86f05680-58a4-11ea-904f-be5716705878.png)

Should be `Turn On` instead of `Turn on` to be consistent with
![image](https://user-images.githubusercontent.com/6461412/75351259-282cdc00-58a8-11ea-9249-c280779f0130.png)
![image](https://user-images.githubusercontent.com/6461412/75351422-6fb36800-58a8-11ea-9e2c-36d23deae31a.png)

**Comment by aeschli** [comment]
Similar issue:
![image](https://user-images.githubusercontent.com/6461412/75351070-cd938000-58a7-11ea-8e0f-14e03d31f52c.png)

**Comment by sandy081** [comment]
`on` and `off` are in lower case because they are verbs. where as in other cases they are nouns (`Folder`, `Repository`).

**Comment by Tyriar** [comment]
When you're using title case that doesn't matter though, which I think is the intent. While "on" is normally lowercased that isn't the case when it's at the end of the title:

Correct:
Turn On
Turn on Sync

Wrong:
Turn on
Turn On Sync

https://capitalizemytitle.com/
