### ISSUE TITLE
Missing terminal output when scrolling up

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#91574]
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Run a simple script in the terminal a few times.
   Ex: `console.log('Hello world');`
2. Scroll up.
3. For previously hidden output, one of the first few lines is now missing.

![terminal](https://user-images.githubusercontent.com/1007463/75335421-b96b6680-5846-11ea-8efa-54405de1268e.png)

**Notes:**
- I have no custom terminal settings.
- ~If the output has more than 1 line, subsequent lines are shown.~

VS Code version: Code - Insiders 1.43.0-insider (b0be0672c210f1fa76109ce675365bb785657e84, 2020-02-26T05:30:24.470Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.1
vscode-icon-theme|jtl|1.6.5

</details>

**Comment by Tyriar** [comment]
By first line do you mean at the top or bottom? A gif would be helpful to see if a line is going missing.

**Comment by mattacosta** [comment]
After more testing... I don't even know what's going on anymore:

```js
console.log('1');
console.log('2');
console.log('3');  // <-- missing
```
![terminal_3](https://user-images.githubusercontent.com/1007463/75494118-ba9cb080-5978-11ea-8522-faacc8866f82.gif)
```js
console.log('1');
console.log('2');  // <-- missing
console.log('3');
console.log('4');
```
![terminal_4](https://user-images.githubusercontent.com/1007463/75494137-c6887280-5978-11ea-8120-274a64c93221.gif)

Tests:
- 2 lines: the line with "2" went missing
- 3 lines: the line with "3" went missing - see gif above
- 4 lines: the line with "2" went missing - see gif above
- 5 lines: the line with "5" went missing
- 6 lines: the line with "1" went missing

**Comment by Tyriar** [comment]
Unconfirmed, likely an upstream problem.

**Comment by YaAlfred** [comment]
Have same behavior. It is repeated only when you choose powershell, cmd works fine. Howewer it is not repeated from powershell started as standalone process. The version of powershell is 5.1.18362.628, located under C:\Windows\System32\WindowsPowerShell\v1.0

**Comment by jppm99** [comment]
Disabling conPTY fixed this for me.

**Comment by mattacosta** [comment]
Did more digging and this looks very similar to: https://github.com/microsoft/terminal/issues/3163

That in turn links to https://github.com/PowerShell/PSReadLine/issues/724 which was fixed a little over a year ago. As far as I can tell, my system already has the latest version (2.0.0) of this module though...
