### ISSUE TITLE
Should be a way to retrieve sessions with specific provider and scope

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#91571]
Testing https://github.com/microsoft/vscode/issues/91309

provider.getSessions() returns an array of sessions. If it is possible that each of those sessions could have a different scope it might be helpful to have a simple way to get a session with a specific scope.

**Comment by rebornix** [comment]
@RMacfarlane it seems we are now back to `getSessions()` again in current master?

**Comment by RMacfarlane** [comment]
Ah, to clarify, there are two different `getSessions()`. One is under `AuthenticationProvider`, so someone implementing a provider would write that method. But under the `authentication` namespace there should now be `getSessions(providerId: string, scopes: string[])` to make it easier to use as a consumer

**Comment by RMacfarlane** [comment]
Here is a some sample code for an extension:
```ts
import * as vscode from 'vscode';

const providerId = 'microsoft';
const scopes = ['openid', 'offline_access'];

export async function activate(context: vscode.ExtensionContext) {
	async function getCachedSesssionOrLogin() {
		const sessions = await vscode.authentication.getSessions(providerId, scopes);
		if (sessions.length) {
			const token = await sessions[0].getAccessToken();
			console.log(token);
		} else {
			const token = await vscode.authentication.login(providerId, scopes);
			console.log(token);
		}
	}

	if (vscode.authentication.providerIds.includes(providerId)) {
		getCachedSesssionOrLogin();
	}

	vscode.authentication.onDidChangeAuthenticationProviders(async e => {
		if (e.added.includes(providerId)) {
			getCachedSesssionOrLogin();
		}
	});
}
```
Note that you need to enable the proposed API
