### ISSUE TITLE
Indicate which authentication provider is used

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#91575]
Testing https://github.com/microsoft/vscode/issues/91226

I was already signed-in with the Microsoft Account when I started testing #91226.
Do when enabling settings sync the `Turn On Sync` dialog will just show `Turn on`  and all works without signing in.
That's great but it would be good to know what Account was used
- To know what user is used (maybe it's not right one, and I rather want to sign in with a different one)
- To know what command I need to run to sign out (`Microsoft Account: Sign out`)

**Comment by Tyriar** [comment]
This came up in yesterday's meeting in Redmond too; if a user has already signed in and turn off sync then it's difficult to sign in with another account since the credentials are cached. Maybe we should present the cached account or allow the user to sign in again if the are cached credentials?

**Comment by misolori** [comment]
What if in this scenario when they click on “Turn on” after selecting their configuration, we show another quick pick that says something like “You are currently signed in as <email>. Would you like to stay signed in or use another account?” [Stay signed in] [Choose another account]?

**Comment by Tyriar** [comment]
Yeah something like that, maybe make the first option show the account so users can action it a little faster "Use x@y.com (Microsoft)" instead of "Stay signed in"?

**Comment by sandy081** [comment]
Agreed. There needs to be a way to choose other account. How about following picker after turn on?

![image](https://user-images.githubusercontent.com/10746682/75362444-038d3000-58b9-11ea-8f7c-ec017415659d.png)

**Comment by Tyriar** [comment]
Hmm, maybe not include Microsoft after rethinking it since that's the only option atm?

**Comment by sandy081** [comment]
I am showing Account:id every where as the identity to indicate that you are logging into `Microsoft` account using the `sasomava@microsoft.com` in this example. Yes it is the only account for now but it is to provide more information.

**Comment by sandy081** [comment]
Changed to 

![image](https://user-images.githubusercontent.com/10746682/75367551-cb89eb00-58c0-11ea-857a-1c198d4c5f5d.png)

Inlining with

![image](https://user-images.githubusercontent.com/10746682/75367066-ffb0dc00-58bf-11ea-9cbb-db88c0123131.png)

All labels are picked from account extension.

**Comment by sandy081** [comment]
Choosing another account will log out from existing account and shows the log in page.
