### ISSUE TITLE
Execution controls missing if code cell is not focused

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#91587]
refs #91328

Even if a notebook is focused, if a code cell is not focused, there are no execution controls. I expect to see `Execute Notebook (Run all cells)`

![image](https://user-images.githubusercontent.com/6561887/75363235-acfb0400-586e-11ea-8383-9c89206af053.png)

**Comment by rebornix** [comment]
The notebook editor's behavior is the same as text editor, if users open a file through file explorer, the focus doesn't go into the editor group, thus there are no cell execution commands. If users click into the editor, or click the title bar, the editor is then focused and all editor actions should be there.
