### ISSUE TITLE
Require second parameter for Map.set

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91582]
@mjbvz https://github.com/microsoft/vscode/commit/af9dddd0fcd65f310cc795e0c7c5370b4ca17086 is beyond my understanding. This changed the semantic of `Map` that previously had `undefined` values to only add values that are not `undefined`. Can you explain?

As one of the regressions, this caused https://github.com/microsoft/vscode/issues/91410 where removing a key in the SQLite storage data base is no longer triggering an event. 

There maybe other regressions looking at changes in other files.

According to MDN, it is valid to put `undefined` as value of a map.

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/commit/af9dddd0fcd65f310cc795e0c7c5370b4ca17086 fixed a real error in our typings. In JS, calling `.set(key, undefined)` or just `.set(key)` will put an entry for undefined into the map:

```ts
var a = new Map();
a.set(1, 'abc')
a.set(2, undefined) // or a.set(2)
a.size === 2
a.has(1) === true
a.has(2) === true
```

This is almost always a mistake in properly typed code. 

Further, with strict null checks enabled, TypeScript does not permit the second parameter of a map to be undefined:

```ts
var a = new Map<number, string>();
a.set(1, 'abc')
a.set(2, undefined) // error here!
```

In cases where we do want  to store `undefined` in the map, we need annotate the map type to allow this.

So I think the typing change is correct but my attempt to patch this may have caused regression in previously non-type safe code.

---

Let's just review the code changes from af9dddd:

- [ ] `storageIpc.ts` @bpasero 
- [ ] `mainThreadTask` @alexr00

**Comment by bpasero** [comment]
Yes, the intent was to store `undefined` in the map to signal that a key in storage was removed. Otherwise I have no way of signaling this.

**Comment by foxtango** [comment]
> @mjbvz [af9dddd](https://github.com/microsoft/vscode/commit/af9dddd0fcd65f310cc795e0c7c5370b4ca17086) is beyond my understanding. This changed the semantic of `Map` that previously had `undefined` values to only add values that are not `undefined`. Can you explain?
> 
> As one of the regressions, this caused #91410 where removing a key in the SQLite storage data base is no longer triggering an event.
> 
> There maybe other regressions looking at changes in other files.
> 
> According to MDN, it is valid to put `undefined` as value of a map.

Without having much TypeScript experience:

https://www.typescriptlang.org/docs/handbook/advanced-types.html has this:

Optional parameters and properties #
With --strictNullChecks, an optional parameter automatically adds | undefined:
(...and for optional properties too).

**Comment by bpasero** [comment]
I decided to not allow for `undefined` in the `Map` but rather explicitly distinguish between changed and deleted storage keys.

**Comment by alexr00** [comment]
mainThreadTask.ts looks ok.

**Comment by Tyriar** [comment]
This good to close now?
