### ISSUE TITLE
CustomTextEditorProvider and WebviewCustomEditorProvider have inconsitent names

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91583]
Testing https://github.com/microsoft/vscode/issues/91325

These are difficult to name, but it bothers me that both have the word "custom" but the word is in a different position. What about `TextCustomEditorProvider` and `WebviewCustomEditorProvider` ?

**Comment by mjbvz** [comment]
Make sure you are using the latest typings from `master`. The types should now be: `CustomEditorProvider` and `CustomTextEditorProvider`

Let me know if you see something different in `vscode.proposed.d.ts`
