### ISSUE TITLE
Typescrip language services keep crashing

### ISSUE THREAD

**Issue by florestankorp** [microsoft/vscode#91585]
Issue Type: <b>Bug</b>

Typescrip language services keep crashing

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-88-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3597)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.61GB (5.15GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.900.14
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
vscode-diff|fab|1.4.0
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
svelte-vscode|Jam|0.9.3
angular-essentials|joh|9.0.1
mssql|ms-|1.8.0
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
material-icon-theme|PKi|3.9.3
python-string-sql|ptw|1.1.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.2
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.8.0
vscode-npm-scripts|tra|0.2.1
vscode-icons|vsc|10.0.0
jinja|who|0.0.8
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
