### ISSUE TITLE
Double confirmation dialog on conflict resolution

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#91588]
Testing #91226

- create a setting sync conflict
- in the conflict dialog choose to 'Show Conflicts`
- the diff editor shows up with the `Accept Remote` and `Accept Local` buttons (looks good!)
- Click on `Accept Local`
- Another dialog asks me if I'm sure. That dialog seems to much for me. Is it necessary?

![image](https://user-images.githubusercontent.com/6461412/75363082-ec027700-58b9-11ea-9445-fecb4badcc2f.png)

**Comment by sandy081** [comment]
May or may not be. Since it is not an often action and also we want to be sure, added one more check. But open to remove it.

**Comment by Tyriar** [comment]
I'd say keep it for now personally as it clarifies what the button does. If the user accidentally does the wrong thing the cost can be somewhat high as they may need to figure out how to view backups.
