### ISSUE TITLE
`Unable to sync notification` comes too early

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#91584]
Testing #91226

- enable setting sync
- in the setting JSON editor, star adding color customization
- In the middle of typing you get a notification

![image](https://user-images.githubusercontent.com/6461412/75359724-16056a80-58b5-11ea-9e83-9e61f29324d2.png)

- it would be better to wait a bit as I'm just in the middle of editing.
- maybe a symbol on the status bar would be better to indicate that syncing is halted
- can there be warnings that prevent syncing or is it just errors?
- Uppercase/lowercase: the button should be `Open Settings File` and the text should say `Unable to sync settings...`

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/75362928-b198da00-58b9-11ea-866f-20157f7e7c95.png)
Again 'Settings' should be lower case,

**Comment by Tyriar** [comment]
I think @chrisdias mentioned this today as autosave was on.
