### ISSUE TITLE
visual studio code shows black screen

### ISSUE THREAD

**Issue by Tejasanthosh** [microsoft/vscode#91599]
- VSCode Version: VSCodeUserSetup-x64-1.42.1
- OS Version: windows 7 -x64

Steps to Reproduce:

1.When I launch VS Code after installation, I get black screen. I tried to reinstall it, but without a result and I also tried to run with this in cmd prompt- code --disable-gpu . I got opened for once only. If I close window and again I open, then facing same issue that is black screen. Is there any possible solution for this?
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/87049#issuecomment-566033360 for a pointer on how to disable GPU on every launch.

**Comment by roblourens** [comment]
☝️  Does that resolve your issue?

**Comment by rogeraabbccdd** [comment]
I just doing a fresh vscode and XAMPP install in my Windows 7 x64 PC.
VSCode shows black screen and freeze  after I install XAMPP.
And yes `--disable-gpu` solves to issue.
