### ISSUE TITLE
“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software. (Attempt to reopen issue #82534)

### ISSUE THREAD

**Issue by arrbie** [microsoft/vscode#91593]
<img width="488" alt="Screenshot 2020-02-26 at 17 36 38" src="https://user-images.githubusercontent.com/9554571/75367758-199eee80-58c1-11ea-89ac-e9f535ec63da.png">

- VSCode Version: 1.42.1
- OS Version: MacOS X 10.15.3

Steps to Reproduce:

1. Just try to start the application

**Notice**: This is an attempt to reopen issue #82534 since the problem persists. The previous issue was closed because the "solution" suggested was to disable the Mac security system(!!!). This is, of course, neither sensible nor a solution to the bug. The problem still persists, and is a **major blocker** since it makes the product virtually unusable.

Does this issue occur when all extensions are disabled?: Not applicable

**Comment by arrbie** [comment]
This is **not a duplicate issue**, since all previous issues on this theme is referring to an issue that was closed for the wrong reasons. The issue **needs to be reopened and correctly solved**.

There is not a single Mac user who can use the Visual Studio Code application without disabling the Mac security system, which of course is entirely unacceptable — especially for this kind of product. The Mac security system is quite important and an essential part of a functional and safe MacOS. It is there for a good reason.

**Comment by gjsjohnmurray** [comment]
I understand it is already resolved in the current Insiders build, and will probably land next week when the current endgame completes.

**Comment by arrbie** [comment]
> /duplicate of #74782

Which is closed although **not** solved (as I clearly stated in the issue above)!
Issue #74782 says: Solve problem by disengaging MacOS security protocols. **Is that a solution???**

**Comment by arrbie** [comment]
> Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for existing issues [here](https://aka.ms/vscodeissuesearch). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

Please read this issue carefully. I know all about the so called "duplicates". But I have already clearly replied to that in the description above. All of those "duplicates" are already closed. But none of them has solved the problem. Actually, every single one of them has made the problem worse since they advice Mac users to either circumvent the MacOS security system or switch it off entirely. This is one of the worst suggestions I have ever heard, and have trouble understanding that this is coming from anything but amateurs. With "solutions" like that we don't need any issues/bugs.
**So, my case rests; this is an unsolved issue!**

**Comment by gjsjohnmurray** [comment]
@arrbie have you tried installing Insiders from https://code.visualstudio.com/insiders/ yet?

**Comment by arrbie** [comment]
> @arrbie have you tried installing Insiders from https://code.visualstudio.com/insiders/ yet?

Just did, and it eventually works. So I will stay on that until stable release. Guess this issue can be closed now, or?
