### ISSUE TITLE
Open CustomTextEditors aren't restored 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91595]
Testing https://github.com/microsoft/vscode/issues/91325

If I have a `CustomTextEditorProvider` and a file is dirty and open, I expect some sort of "do you want to save" prompt when I close the window. Or, if we don't have that, then I expect the dirty state of the TextDocument to be saved and the custom editor to be opened again when the folder is opened.

**Comment by mjbvz** [comment]
I believe we disable hot exit in extension development mode

In my testing, I always see the editor itself being restored properly. If I package the extension and install it, I also see the text model being backed up as expected.

Please test installing the extension and let me know if you are still seeing issues

**Comment by alexr00** [comment]
Yes, that was the problem.
