### ISSUE TITLE
Default code formatter for JSON should not remove blank lines

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#91596]
**Default** code formater for JSON removes blank lines. This is a pretty destructive behavior, and should be avoided by default. I am aware that I can install prettier for formatting JSON documents, but I do believe that the default should be conservative: I hit `ctrl+shift+I` automatically, and I don't want to install 3rd party tools/explicitly change config just to make my editor not to do bad stuff.

**Comment by aeschli** [comment]
duplicate of #23260
