### ISSUE TITLE
Endgame - misses smoke test before closing for release

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91592]
Looking either at https://github.com/microsoft/vscode/wiki/Endgame-Template or https://github.com/microsoft/vscode/issues/91278 I only see the smoke test mentioned once in the beginning of the week. However I think we need to run them also at the end before closing for the release.

Please update the template and the endgame plan accordingly.

**Comment by Tyriar** [comment]
@bpasero isn't that the point of running them early? @jrieken reached out to me asking for the opposite.

**Comment by bpasero** [comment]
@Tyriar my understanding was that we run them early to be able to fix issues early on and not on the last day. I was never thinking we would then not run them again before we close for the release. After all, that is actually the purpose of the smoke test.

**Comment by jrieken** [comment]
> Running them once while we still make changes defeats the purpose imho.

Which isn't Friday but usually Monday, Tuesday, sometimes Wednesday.

**Comment by bpasero** [comment]
Yeah, then let's run them as part of the sanity checking of builds. In fact, that would probably be the replacement for the rather stupid sanity checking we do today.

**Comment by Tyriar** [comment]
Ok, I'll add it back
