### ISSUE TITLE
Add an entry point for sync from the settings ui

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91601]
One of the things that came out of the study was that users often went to the settings ui to try to set this up. Now, they may not have known what word to look for (see #91192) but they did scan the page for some type of entry point.

I'm not quite sure if and where this should live, but figured I'd get the conversation going. I'm not saying this is something we should do, just that we know this is the first place users go to. 

One idea is to add a button somewhere, but then that brings up the "where does Sync live” and where else we'd want to show indicators:

![image](https://user-images.githubusercontent.com/35271042/75376805-84323900-5885-11ea-9d21-f2d0cc9f1e71.png)

Or maybe it's just that we add a setting that is bubbled up to the top:

![image](https://user-images.githubusercontent.com/35271042/75377480-c90a9f80-5886-11ea-8f67-35b488038997.png)

Other browsers do something similar when going to the browsers settings, but have a different approach with an actual "profile" section as the first item:

**Chrome**

![image](https://user-images.githubusercontent.com/35271042/75376150-631d1880-5884-11ea-9505-2d96d3548ce7.png)

**Edge**

![image](https://user-images.githubusercontent.com/35271042/75375987-19343280-5884-11ea-9719-b294ad3c9d8e.png)

cc @Tyriar @RMacfarlane

**Comment by sandy081** [comment]
Liked the `Turn on Sync` explicit action.

**Comment by roblourens** [comment]
Talking about this with Kai we were thinking that we should add the `Turn on Sync` button and also a "Last Synced..." timestamp to the settings editor outside of the setting itself. In the first screenshot, I think I like the option that puts it in the sidebar, but I could do either one. 

Thoughts @misolori @sandy081?

**Comment by sandy081** [comment]
I also liked the first option. There is no explicit last synced time for settings, I need to add it. Also, I would suggest to add enabling/disabling settings sync.

**Comment by sandy081** [comment]
Reopening this for the discussion to use `icon` instead of `blue button`

Some concerns:

- How can the same action can be shown in Keybindings editor & Extensions viewlet? Is it consistent to go with an action with icon just like other actions? This will make it easier to adopt sync action in other places too. Why are we not going with an action with icon here?

- Re: advertising the feature - We do not follow the same for other features. We assume icons are discoverable. Advertising features is a good problem but not sure big blue buttons are the solutions. 

- Also this button will be shown always to the users who do not want to sync and might be annoying.

**Comment by roblourens** [comment]
1. Even though Sync works for more features than Settings, people seem to closely associate it with settings, and I think this comes from people in user studies opening the settings editor looking for a way to enable settings sync. Could add it to other places too but I don't know if that's necessary.
2. I might have to defer to @kieferrm or @misolori here, I don't have a strong preference either way.

**Comment by kieferrm** [comment]
We can reconsider once we see how it's perceived.

**Comment by misolori** [comment]
We've already added this in the settings ui:

![image](https://user-images.githubusercontent.com/35271042/84832212-b658d980-afe1-11ea-98c6-273280c5c19b.png)
