### ISSUE TITLE
[folding] Editor folding function calls

### ISSUE THREAD

**Issue by MKRhere** [microsoft/vscode#91605]
VSCode allows function bodies to fold, however, it does not allow function calls to be folded. This is especially painful when you have functions that can accept deeply nested or a very large number of parameters.

Here's an example from my project. I have a helper playground here (forgive horrible styling, I wrote it in under an hour): https://h2h.dev.thefeathers.in/

If you paste HTML on the left panel, this generates function calls similar to the following:

```js
div[".left"](
	div(
		a[".left-panel-button"](
			{ href: "#Personal" },
			h2(`Personal details`),
			div(),
		),
		a[".left-panel-button"](
			{ href: "#Education" },
			h2(`Educational details`),
			div(),
		),
		a[".left-panel-button"](
			{ href: "#Experience" },
			h2(`Experience`),
			div(),
		),
		...
	),
	...
```

My example is small, but you can infer that this can become huge very quickly, and to begin refactoring this into components, it'd be useful if I can fold function calls.

>Edit: In relation to this, I believe vim's solution is to allow folding of anything that's indented, without need for language awareness.

**Comment by mjbvz** [comment]
To use indentation based folding, just set `"editor.foldingStrategy": "indentation"`

**Comment by MKRhere** [comment]
That works great for me, thanks @mjbvz 🙂
I'd been looking for fold on calls that I didn't realise there was a strategy for fold by indent.
