### ISSUE TITLE
React Stateless function don't get syntax coloring

### ISSUE THREAD

**Issue by prashid** [Microsoft/vscode#9160]
Hi,
Using latest version of VSCode with [React Native extension](https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native). 

I don't get syntax coloring for React Stateless functions. You can see in the image. There is no yellow coloring on `<Text></Text>` or `<View></View>`
![problem](https://cloud.githubusercontent.com/assets/620377/16782006/254de526-4897-11e6-96c0-733a48f82488.png)

**Comment by aeschli** [comment]
The inconsistent coloring is caused by #3008.
