### ISSUE TITLE
Search Editor presents files before results, opposite of Search view

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#91607]
- VSCode Version: 1.43 Insiders
- OS Version: Windows 10

Found while testing #91331
Steps to Reproduce:

1. Open the vscode-docs repo and create an empty Search Editor
2. Search for "VSCode" and set Match Case and Match Whole Word

![image](https://user-images.githubusercontent.com/12818376/75383619-8ac6ad80-5891-11ea-98fc-aa1a4a2a9603.png)

This changed recently. Should these be consistent between the two Search results?

**Comment by JacksonKearl** [comment]
Closed in 7f1f3981cef74c2fd41b864ddecdb506579723be
