### ISSUE TITLE
type check is cannot run

### ISSUE THREAD

**Issue by yearn2012** [microsoft/vscode#91608]
- VSCode Version: 1.42.1
- OS Version: win-nt x64 10.0.19041

Steps to Reproduce:

1. I Declared a class and then set a value int type,not report wrong.
```
    IndicatorDataSeries MacdOtherFrameSeries { get; set; }
 private void IndicatorArea_MouseUp(ChartMouseEventArgs obj)
        {
        
           ###  MacdOtherFrameSeries = 2;
            fxMacd.GetMacd_OtherFrame();
            Print("good");
        }
```

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by roblourens** [comment]
Please file this on the repo for the C# extension: https://github.com/OmniSharp/omnisharp-vscode
