### ISSUE TITLE
Auto update always installs in 'C:\Program Files (x86)' even though VS Code was installed in different drive.

### ISSUE THREAD

**Issue by rosdi** [Microsoft/vscode#9161]
- VSCode Version: 1.0
- OS Version: Windows 10 Pro 64 bit

Due to limited space in my SSD 256GB C: drive I installed VS Code on D: drive instead. But today VS Code informed me there is a new 1.3 version and asked whether I would like to update.... I clicked Yes.

To my surprise, the installer installs the latest version into 'C:\Program Files (x86)' instead of overwriting my current installation folder.

Steps to Reproduce:

1. Install VSCode 1.0 into D: or E: drive... as long as it is not C: drive.
2. Run VSCode, and wait for it to offer to update itself to latest version. Click Yes.
3. The latest version (1.3 as of this writing) will be installed in 'C:\Program Files (x86)' and the old 1.0 version will be left orphaned in D: or E:

**Comment by joaomoreno** [comment]
This is strange, it should just work. What happens if you install in C:\ but in another folder?

**Comment by rosdi** [comment]
I am not able to find the installer for older versions of vscode... the website always download the latest version... so I could not reproduce this problem for now... right now I am on version 1.3.1.

I guess I will have to wait for newer version to come out before I can test again? 

Currently I have VSCode installed in `C:\Misc Programs\Microsoft VS Code`.

**Comment by joaomoreno** [comment]
Feel free to try to reproduce with our [Insider release](https://code.visualstudio.com/insiders). There is a new release every day there.

**Comment by scottpschaffer** [comment]
I installed the Insider release to a different location on my C: drive and when I updated the next day, nothing seemed to install on my Program Files (x86) folder.

**Comment by rosdi** [comment]
Yea I am not able to reproduce this either... perhaps it is my error... have been drinking coffee too much I guess... I will close this.

**Comment by joaomoreno** [comment]
Thanks!
