### ISSUE TITLE
Debug console suggestions should not fuzzy match on history entries

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#91617]
In the image below the `itemsMap` variable is a `Map`, but it doesn't even seem to be seen as an object at all.

![image](https://user-images.githubusercontent.com/641685/75386608-fcadef80-58af-11ea-867a-f684244923bc.png)

**Comment by eamodio** [comment]
I think the more important issue here, is why didn't I get real completion for the object itself?

**Comment by roblourens** [comment]
Can you share the code that you were paused in or a wider screenshot? Did it show up in the variables pane?

**Comment by isidorn** [comment]
@connor4312 your idea makes sense, however the suggestWidget deos not support different matching styles on different suggestions. As far as I know @jrieken 
We always fuzzy match

**Comment by eamodio** [comment]
I can repro with a very simple sample:

```js
const http = require("http");

const hostname = "127.0.0.1";
const port = process.env.PORT === undefined ? 8080 : process.env.PORT;

function setup() {
  const server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader("Content-Type", "text/plain");
    res.end("Hello World!\n");
  });

  server.listen(port, hostname, () => {
    console.log(`Server running at http://${hostname}:${port}/`);
  });
}

setup();
```

If you set a breakpoint in the `createServer` lambda and then type `res.` in the Debug Console there will be no completion. But `res` does show up in the locals

**Comment by connor4312** [comment]
Okay, there's two issues here--completions not showing and items from the history showing when they probably should not. I'll reopen an issue for the former in js-debug's repo.
