### ISSUE TITLE
funky js block indentation

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#91614]
Issue Type: <b>Bug</b>

Not sure if this is a bug or intentional. As far as I can tell it's a bug since it messes up all indentation after a block of code.

The indentation of this code will be incorrect when I use the 'Reindent Lines' command:
```
if(a &&
    b) {
        
    }
```

It should end up like this (ending brace is on the same indent level as line 0):
```
if(a &&
    b) {
        
}
```

This is caused by the if statement argument being on multiple lines. Multiple iterations of this line splitting of the if statement argument adds to the indentation problem (with sub arguments wrapped in parentheses I think?).

Obviously this code isn't a great representation of why I would put 'b' on a second line. But I do have if statements with multiple long strands of arguments that I want to stop from going off the right of the screen, therefore I put parts of the long argument on newlines. I am aware it's probably not the best practice for writing code but regardless, is this indentation behavior a bug?

VS Code version: Code - Insiders 1.43.0-insider (b0be0672c210f1fa76109ce675365bb785657e84, 2020-02-26T05:30:24.470Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Closing due to lack of further user interest on this issue.

Use the `Format` commands instead of the `reindent` commands. The format commands are much more consistent and reliable
