### ISSUE TITLE
Issues with "Running save participants..."

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode#91610]
Hi! I work on the Go language server ([`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md)), and I wanted to raise a general issue about the removal of on-save timeout in version 1.42. This change caught us a bit by surprise, since `gopls` is still in an alpha state and may occasionally have a slow code action on save.

Some users were relying on these timeouts, and there have been a few reports of users losing code because their files never got saved. We're currently adding support for timeouts in code actions and formatting to mitigate the problem, but it would've been really helpful to know about this change before 1.42 was released. Is there any channel where major changes are announced, or should we should just have a set of people testing with VS Code Insiders?

On a related note, we have noticed that the "Running save participants..." box sometimes remains open even when the code action response has been sent. We cannot reliably reproduce it, but it's come up a couple of times. If it's helpful, I can attach a `gopls` log from an instance when it happened, but is there any way to investigate what is happening in VS Code when this happens?

Thank you!

**Comment by jrieken** [comment]
> should we should just have a set of people testing with VS Code Insiders?

🔝 that.

**Comment by jrieken** [comment]
For 1.43 we have pushed a couple of improvement but we stay to the none-timeout version of save participants. We have changed

* the progress message shows what extensions/participant is running
* the progress message brings you to the setting to disable save participants
* the progress message cannot be dismissed so easily anymore

**Comment by jrieken** [comment]
> On a related note, we have noticed that the "Running save participants..." box sometimes remains open even when the code action response has been sent. We cannot reliably reproduce it, but it's come up a couple of times. If it's helpful, I can attach a gopls log from an instance when it 

Please file an issue with repro steps for that

**Comment by stamblerre** [comment]
> > should we should just have a set of people testing with VS Code Insiders?
> 
> 🔝 that.

My only concern with this approach is that we probably still wouldn't have caught this issue. Slow code actions occur when a user's workspace is misconfigured in some way, and that probably wouldn't happen to someone using Insiders. I will try to be more active on the VS Code Slack group and see how that works out, but it would be nice to get some advance warning about the deletion of settings.

> > On a related note, we have noticed that the "Running save participants..." box sometimes remains open even when the code action response has been sent. We cannot reliably reproduce it, but it's come up a couple of times. If it's helpful, I can attach a gopls log from an instance when it
> 
> Please file an issue with repro steps for that

Will do, once we are able to repro more consistently. So far, it's happened a few times, but it's hard to investigate. Seeing which participant it's blocked on will help.
