### ISSUE TITLE
Debug console group headers with variablesReferences are empty

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91621]
Refs: https://github.com/microsoft/vscode/issues/91095

In the Chrome console:

![image](https://user-images.githubusercontent.com/2230985/75394398-dfbfef00-58a4-11ea-9daa-dbadcc65f62a.png)

In VS Code:

![image](https://user-images.githubusercontent.com/2230985/75394407-e77f9380-58a4-11ea-8f2d-57fb87328feb.png)

DAP log:

```
{"seq":106,"type":"event","event":"output","body":{"category":"stdout","output":"This is the outer level\n","source":{"name":"main.js","path":"/Users/copeet/Github/vscode-pwa/demos/node/main.js","sourceReference":0},"line":1,"column":9}}
{"seq":107,"type":"event","event":"output","body":{"category":"stdout","output":"","variablesReference":10,"group":"start","source":{"name":"main.js","path":"/Users/copeet/Github/vscode-pwa/demos/node/main.js","sourceReference":0},"line":2,"column":9}}
{"seq":108,"type":"event","event":"output","body":{"category":"stdout","output":"Level 2\n","source":{"name":"main.js","path":"/Users/copeet/Github/vscode-pwa/demos/node/main.js","sourceReference":0},"line":3,"column":11}}
```

**Comment by isidorn** [comment]
This is not yet supported. Assinging to March to investigate then to introduce this support.
Thanks

**Comment by isidorn** [comment]
We would have to support Group start event with variable references.
[Code pointer](https://github.com/microsoft/vscode/blob/1d8df428978f70bd20ffc7527d6bbf2a1534fef2/src/vs/workbench/contrib/debug/browser/debugSession.ts#L849)

Not for march, leaving open as feature request for future.
