### ISSUE TITLE
Realtime preview (with Split Editor) by one-click

### ISSUE THREAD

**Issue by masa36** [Microsoft/vscode#9162]
- VSCode Version: 1.3.1
- OS Version: Windows 7 SP1
#### Steps to Reproduce:
- Open file.md file
- [Split Editor]
- Right-clicking the tab "file.md" in the right pane
- [Open Preview]
- Close the tab "README.md" in the right pane
#### Expected
- Open file.md file
- Right-clicking the tab "file.md" in the right pane
- [Preview in Split Editor] ?
  - Left-split tab: file.md (source)
  - Right-split tab: Preview 'file.md' (preview)

![image](https://cloud.githubusercontent.com/assets/3655468/16789668/83b3df64-48ea-11e6-97c7-f0f47134c641.jpg)

**Comment by kieferrm** [comment]
The command `Open Preview to the Side` bound to <kbd>Cmd/Crtr+K V</kbd> by default opens the preview side-by-side with the source. We are also tracking how to eliminate the need for a separate step altogether in #2766.

**Comment by masa36** [comment]
`Cmd/Crtr+K V` works fine. Thank you very much for handling.
