### ISSUE TITLE
Turning sync on/off triggers first time sync dialog

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#91626]
This also came up in the study but I don't see an issue for this already. When you turn Sync off and then back on, you always get this dialog:

![image](https://user-images.githubusercontent.com/35271042/75395933-3844bb80-58a8-11ea-870b-cf6f0089225b.png)

1. Turn on sync
3. Turn off sync
4. :bug: Dialog appears asking to merge

Expectation is that you shouldn't get this dialog because there are no new changes.

**Comment by misolori** [comment]
@sandy081 can you link to the duplicate issue so that I can follow up? Thanks.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/91545
