### ISSUE TITLE
Retain order of views when moving back to sidebar

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#91632]
Testing https://github.com/microsoft/vscode/issues/91335

In this case, the views sort of "rearrange". I'd expect them to stack in the specific order I've dragged them back to the sidebar.

![Kapture 2020-02-26 at 15 26 28](https://user-images.githubusercontent.com/9721254/75397717-67f5c280-58ac-11ea-8bd0-1d1e084a9c77.gif)

**Comment by sbatten** [comment]
no longer valid with new drag and drop behavior
