### ISSUE TITLE
Support detecting `bash.bat` shells correctly 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#91631]
This comes from https://github.com/microsoft/vscode-python/issues/9795

The Python extension uses the VS Code API to detect shells, and if it fails, it tries to detect it itself. If it fails, it falls back to the default terminal in that OS.

The issue in question is that we don't detect git bash. While we could implement the detection ourselves, it seems that having this upstream would benefit more than just the Python devs.

**Comment by Tyriar** [comment]
Git bash should be detected here?

https://github.com/microsoft/vscode/blob/3c1e64220f137f9f4710841022b9d58e654e9f01/src/vs/workbench/contrib/terminal/node/terminal.ts#L115-L121

Could you elaborate where you're expecting it or what's not working?
