### ISSUE TITLE
Reveal in Side Bar not working

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode#91635]
Hello,

  I noticed that the Reveal In Side Bar doesn't appear to be working anymore in my project.  This feature used to work, but not sure if first occured in 1.42.x or the prior version.

Regards,
Mark

CPUs | Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.88GB (7.44GB free)
Process Argv |  
Screen Reader | no
VM | 0%

OS | Linux x64 4.13.4-1.x86_64
CPUs | Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)
Memory (System) | 15.53GB (10.72GB free)
VM | 0%

**Comment by roblourens** [comment]
It's working for me, can you explain how you are invoking this feature and what happens when you do?

**Comment by EmbeddedBacon** [comment]
@roblourens, hmm, this feature hasn't been working for me during the past few days.  I restarted VS Code, even though I had done that before, and it seems to be working now.  

Generally, I would right-click a tab and select "Reveal in Side Bar".  The Side Bar would be focused, but wouldn't go to the file.    Not sure what happened this time around.  Perhaps your testing was quantum entangled with my machine and now works?? ;-)

Closing

**Comment by EmbeddedBacon** [comment]
I ran into this issue again, twice today.  Each time I had to restart VS Code.  I am not sure what is triggering it, perhaps there are too many tab editors open?  No idea, but kind of annoying having to restart VS Code each time this occurs.  I will try determine a pattern, but so far I haven't seen any.
