### ISSUE TITLE
vscode-icon is disabled after update VS code

### ISSUE THREAD

**Issue by nguyenquynhan** [Microsoft/vscode#9163]
- VSCode Version: (version 1.3)
- OS Version: WIN 10

Steps to Reproduce:

Each updated times, vscode-icon is disabled, then I must reenable vscode-icon, why? Can you help me please?

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by nguyenquynhan** [comment]
Thanks!
