### ISSUE TITLE
Persist views in their expanded/collapsed state

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#91630]
Testing https://github.com/microsoft/vscode/issues/91335

When moving views within the sidebar to another viewlet, can we keep them as expanded/collapsed if they were moved that way? i.e. I expand npm scripts view before I drag it to another viewlet and it currently becomes collapsed in the new view

![Kapture 2020-02-26 at 15 13 45](https://user-images.githubusercontent.com/9721254/75396987-a0949c80-58aa-11ea-8cf2-cc763e5b7141.gif)

**Comment by sbatten** [comment]
I think its best that we focus and expand them consistently.

Verifier: 
1) Drag a collapsed view to a new container and verify it is expanded and focused in the new container. 
2) Drag the view back to its original container and verify it is expanded and focused in that container.
