### ISSUE TITLE
Unsupported Text and Binary files

### ISSUE THREAD

**Issue by jalissaw** [microsoft/vscode#91640]
I keep trying to download files and upload them to VS Code but it keeps saying that it's binary or it's an unsupported text. Even the videos I had before in VS Code that were working and downloaded, now all say the same thing. How can I solve this problem? Are there any solutions?

**Comment by roblourens** [comment]
We don't support displaying videos or binary files. Are you sure you were using vscode before?

**Comment by jalissaw** [comment]
Yes I'm sure I was using VS code. That's why I was confused as to why it wasn't working any longer.

**Comment by roblourens** [comment]
We should be able to show some images but not videos or anything else.

**Comment by jalissaw** [comment]
So, why did it before?

**Comment by roblourens** [comment]
I'm pretty sure it didn't, unless you had some extension that could handle it.

**Comment by jalissaw** [comment]
So what is the extension that could handle it then?
