### ISSUE TITLE
unity3d debugging broken in vscode insiders

### ISSUE THREAD

**Issue by jaroslaw-weber** [microsoft/vscode#91645]
Problem: when debugging unity3d game, I cannot see values of variables in editor. Need to open another editor to debug.

- VSCode Version: 1.43.0-insider
- OS Version: macos mojave 10.14.6

Steps to Reproduce:

1. Add breakpoint
2. Run unity project in editor
3. Run > Start Debugging
4. Game stops on breakpoint but "Variables" is empty.

**Comment by roblourens** [comment]
C# right? Please file this on the repo for the C# extension: https://github.com/OmniSharp/omnisharp-vscode
