### ISSUE TITLE
"Go to Next Difference" is quite broken

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91644]
It renders very oddly:
![image](https://user-images.githubusercontent.com/8586769/75404189-a85e3c00-58be-11ea-9199-c6c2eb2fc28e.png)

And causes the editor to be stuck in a weird diff state where all diffs opened use the above view, and `toggle inline` no longer works.

**Comment by JacksonKearl** [comment]
It repros in Stable but not 1.40.

**Comment by sanket-bhalerao** [comment]
is this related to merge conflicts?

**Comment by JacksonKearl** [comment]
@sanket-bhalerao no this is my working directory gif.

**Comment by JacksonKearl** [comment]
Still finding its impossible to exit this diff mode, even if you close all diff windows and open a new diff it will still be in this mode. Opened #91776 to track.

**Comment by alexdima** [comment]
@JacksonKearl Good catch. Can you please open a separate issue. The close button in the upper right corner doesn't render OK since the codicon changes, but the area is clickable. Escape will leave this mode.
