### ISSUE TITLE
always reopen all files

### ISSUE THREAD

**Issue by caiqichang** [microsoft/vscode#91650]
version:  1.42.1 x64  .zip 
os: win10 x64 home

i have set :
"window.restoreWindows": "none",
"files.autoSave": "onFocusChange",
"files.hotExit": "off",

but every time i open the vscode, it reopens all files that i never close last time. 
the problem seems appear in this version (1.42.1).

**Comment by bpasero** [comment]
Please provide steps how to reproduce with a fresh user data directory by running "`code --user-data-dir <empty folder>`".

**Comment by bpasero** [comment]
I cannot reproduce btw.

**Comment by caiqichang** [comment]
@bpasero 

1. run command "code demo.txt" open a file.
2. close the vscode directly.
3. run command "code", and the vscode also open the demo.txt.

**Comment by bpasero** [comment]
If I configure `"window.restoreWindows": "none"`, running `code` a second time does not restore that file for me.

**Comment by caiqichang** [comment]
@bpasero 

i try using  ver. 1.42.0 just now, it does well.
then i reuse ver. 1.42.1, and the problem disappear!

i think it may due to some userfile or cache.
