### ISSUE TITLE
Custom editors: wire in editor options

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91658]
Refs: #91325

I feel like `resolveCustomTextEditor` needs to give me access to the set of options that was used in the workbench when opening the editor. For example:
* preserving focus or not
* selecting a certain line/column

More: [`IEditorOptions`](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/platform/editor/common/editor.ts#L124) and [`ITextEditorOptions`](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/platform/editor/common/editor.ts#L238)

**Comment by mjbvz** [comment]
I believe that VS Code itself can handle focusing. The webview panel for the editor should correctly get focus or not depending on `preserveFocus`

We may need a hook for going to a line numbers. We can see if this is something that extension authors ask for

**Comment by mjbvz** [comment]
Actually this is probably better track by #91667
