### ISSUE TITLE
Right Alt + Left Arrow doesn't work

### ISSUE THREAD

**Issue by trucbinh** [Microsoft/vscode#9165]
- VSCode Version: 1.3.1
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Right Alt + Left Arrow doesn't work. Expect it works as Left Alt + Left Arrow

**Comment by NalinNexus** [comment]
Similar in Mac OSX - have lost this as well using Alt + cmd + right arrow to open a new split pane?

**Comment by bpasero** [comment]
@NalinNexus you can rebind keybindings to get the old behaviour back for splitting editor (look for `workbench.action.focusNextGroup`).

As for Alt+Gr (right Alt), I am not sure we can support this key easily. On my Windows machine it turns my display around so it seems like a very native build in OS key.

Moving to @alexandrudima if he has an idea.

**Comment by alexandrudima** [comment]
@trucbinh Try defining your keybinding in the "Define Keybinding" widget, it's there to help out :)

Does it correctly identify your keypresses?

![keybindings](https://cloud.githubusercontent.com/assets/5047891/16842105/d4622a74-49e4-11e6-8820-44eae3edbd95.gif)

**Comment by alexandrudima** [comment]
Closing after a number of days without a reply.
