### ISSUE TITLE
Is it able to support the standard escape sequence `echo -ne '\ec'` (i.e. "\x1bc") to clear screen, in Integrated Terminal?

### ISSUE THREAD

**Issue by johnnytemp** [microsoft/vscode#91668]
I am used to this platform compatible way to clear screen & scroll-back with bash: `alias cls='echo -ne "\ec\e[3J"'`.

It works on many platforms: Linux, macOS Terminal, Cygwin mintty, WSL, Android Termux.

However, '\ec' (ESC-c) have no effect to clear screen on VSCode's integrated terminal. I know there is workaround Ctrl-L to call "Terminal:Clear" on VSCode. I'm just used to my alias.

- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:

1. In integrated terminal (with cygwin), type command `seq 200`, then `echo -ne '\ec'`.
2. The second command is expected to clear screen (not including scroll-back history), but nothing happens.

My settings for integrated terminal:

    "terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["/bin/xhere", "/bin/bash"],

Reference:
- https://askubuntu.com/questions/25077/how-to-really-clear-the-terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What build of Windows 10 do you have? Type `ver` in cmd.exe to get it.

**Comment by johnnytemp** [comment]
Version 10.0.18362.657

**Comment by johnnytemp** [comment]
In addition, in some platforms, `Ctrl-L` just clear screen and cannot clear the scroll-back history. Like "Cygwin mintty", "macOS Terminal". Thus, that alias is more reliable/cross-platform...

**Comment by Tyriar** [comment]
Does [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab) have the same problem?

**Comment by johnnytemp** [comment]
@Tyriar I installed the app from the link you given. After launched the program, I enterred `bash` (C:\Windows\System32\bash.exe for WSL), then enter `seq 200; echo -ne '\ec'`. It works there. And with the `cls` alias above, the scroll-back also gone.

**Comment by Tyriar** [comment]
This works fine in a [Remote-WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) connected window which is the recommended way to use WSL in vscode. For Cygwin something is likely going wrong in the emulation layer called conpty, you will probably find that windows terminal does not work as well if you configure it to use cygwin. Report to https://github.com/microsoft/terminal if so.

**Comment by johnnytemp** [comment]
For your info: running the "cls" alias in Cygwin (enter `C:\cygwin64\bin\bash.exe -l`) inside both "Windows Terminal" (above) and Windows Command Prompt both work. Just when running "cls" in VSCode's integrated terminal not work.
