### ISSUE TITLE
Custom editors: how to integrate custom text editor into workbench?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91667]
Refs: https://github.com/microsoft/vscode/issues/91325

I am still missing a few hooks into the workbench for my custom markdown editor:
* status bar: how do I reflect the selected line/column etc?
* search: how can I highlight words from search results that the user did?

For the status bar it would be odd to task the extension for doing their own entries, rather there should be some provider API.

**Comment by mjbvz** [comment]
If there's demand for these, I believe we can add hooks for these after the initial custom editor API is finalized

**Comment by mjbvz** [comment]
Closing this since we have not seen extension authors requesting these features
