### ISSUE TITLE
User task input variable not defined

### ISSUE THREAD

**Issue by Steve30** [microsoft/vscode#91660]
1. I defined inputs in user task config
2. I want to use a specific input with id
3. When I run the task, show the error message, which describe the  input variable not defined, but in the inputs config in defined

**Comment by alexr00** [comment]
Please share your tasks.json

**Comment by alexr00** [comment]
Actually, I can repro the issue.

**Comment by Steve30** [comment]
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run Jira Server in Standalone",
            "detail": "Global task for start Jira Standalone Server",
            "type": "shell",
            "problemMatcher": [],
            "options": {
                "cwd": "/home/juhaszi/JiraServers"
            },
            "command": "atlas-run-standalone",
            "args": [
                "--product",
                "jira",
                "--version",
                "8.3.2",
                "--context-path",
                "ROOT",
                "-Dmaven.javadoc.skip=true"
            ]
        },
        {
            "label": "Atlas clean install",
            "detail": "Atlas clean with production",
            "type": "shell",
            "problemMatcher": [],
            "command": "atlas-mvn",
            "args": [
                "clean",
                "install",
                "-Dmaven.javadoc.skip=true"
            ]
        }
    ],
    "inputs": [{
        "description": "Jira version",
        "default": "8.3.2",
        "id": "jira-version",
        "type": "promptString"
    }]
}
`
