### ISSUE TITLE
Go to symbol filters on truncated symbol name, not actual symbol name

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9166]
- VSCode Version: Code - Insiders 1.4.0-insider (583f439c1d49128a4775c1ba5a1ac8c6ddd63d5f, 2016-07-12T05:13:58.023Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

File used: https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js

![image](https://cloud.githubusercontent.com/assets/2193314/16791018/ad8f9146-486f-11e6-9f54-f78c4b6ee6a1.png)

Press e

![image](https://cloud.githubusercontent.com/assets/2193314/16791028/c0987366-486f-11e6-91e5-7fee79a52961.png)

**Comment by bpasero** [comment]
I can see that the quick open handler already gets the results back from the language service with "...". 

![image](https://cloud.githubusercontent.com/assets/900690/16792418/8eba93fc-48c8-11e6-91b8-dc63721e4230.png)

@dbaeumer any clue why that is?

**Comment by dbaeumer** [comment]
It is a dup of https://github.com/Microsoft/TypeScript/issues/8238.

**Comment by d48** [comment]
How does this get integrated into VS Code? I'm still seeing this truncation on my Windows version 1.3.1. Thanks for any info

**Comment by dbaeumer** [comment]
This will be fixed with TS 2.0 which we will integrate into VS Code as soon as it is official available.

**Comment by d48** [comment]
Fantastic, thanks for the detail @dbaeumer
