### ISSUE TITLE
Quick pick shows wrong selected items

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#91661]
Steps to Repro

- Set up settings sync - Follow instructions [here](https://github.com/microsoft/vscode-settings-sync-server#self-hosting)
- Turn on Sync
- From the gear icon, select `Sync is on` entry
- Quick pick is shown. From the quick pick click on `Sync: Configure` entry
🐛 Quick pick with wrong selected items is shown

<img width="631" alt="image" src="https://user-images.githubusercontent.com/10746682/75426408-df773080-5944-11ea-9eb0-83fbd95ab786.png">

Expected:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/10746682/75426430-edc54c80-5944-11ea-8112-7636a6db4e7d.png">

Note: Expected is shown when you use keyboard to select `Sync: Configure` entry. It happens only when you use mouse and click.

**Comment by chrmarti** [comment]
@sandy081 There is a change event on the checkbox from the mouse up on the `Sync: Configure` entry. I don't have a fix in QuickInput currently, can we change https://github.com/microsoft/vscode/blob/8ef18acdaf4502e3b81efc498036b432e925df04/src/vs/workbench/contrib/userDataSync/browser/userDataSync.ts#L996 to:
```ts
run(): any { return new Promise(r => setTimeout(r)).then(() => that.configureSyncOptions()); }
```

That appears to let the mouse up pass without triggering the change event on the checkbox.

**Comment by sandy081** [comment]
@chrmarti Is this a temp workaround and do you have plans to fix it in quick pick later?

**Comment by chrmarti** [comment]
@sandy081 It’s certainly a workaround. I don’t have a proper fix yet.
