### ISSUE TITLE
integrated serial port terminal 

### ISSUE THREAD

**Issue by prashanjitghosh** [microsoft/vscode#91662]
Can we have a option to open a serial port for example the COM3 or COM5 if we need to see debug prints coming out of an embedded product connected to our PC for which we are writing code.
I use the VS code extensively to write codes for ARM microprocessors which gives console output in our serial ports I use now applications like Tera Term to connect to them can we have integrated inside the "Terminal" tab as selectable by "Add new terminal"

**Comment by prashanjitghosh** [comment]
No ! the bug descibded #90340 is for a program which is opening a serial port.
I am suggesting to have a terminal application as one tab where we can see outputs of COM ports similar to what teraterm and other terminal application does.

**Comment by Tyriar** [comment]
I don't know exactly about what you're trying to do, but I believe an extension should be able to provide the functionality to drive the terminal as you're after. Look the createTerminal API.
