### ISSUE TITLE
Ability to view multiple pages of the same file

### ISSUE THREAD

**Issue by McGittyHub** [microsoft/vscode#91664]
Hi vscode devs, I was wondering if it would be possible to have the same file be split to multiple pages, horizontally, I'm dealing with some long files and have a widescreen monitor so this would be much needed. Scrolling one view would scroll the other views and each show a different section of the code. Splitting into 3 horizontal views would be ideal.

**Comment by rebornix** [comment]
![Kapture 2020-02-27 at 9 48 32](https://user-images.githubusercontent.com/876920/75471003-6a0c5f80-5946-11ea-960b-ec05054a4a57.gif)

It seems you can do that already in VS Code?

**Comment by McGittyHub** [comment]
Sorry, I guess I didn’t explain properly..
What I wanted was to have views scroll lock and show continuing  parts of the code.

**Comment by rebornix** [comment]
@McGittyHub If I understand correctly, you might be updating the content in one tab, which triggers the document in another tab to be scrolled, right?

**Comment by McGittyHub** [comment]
Yes, that is correct. Each 'tab' should show continuing parts of the code. Scrolling in one tab should scroll in the others.

**Comment by subscribe-lark** [comment]
Tedt


 Original Message 
Sender: github-actions[bot]<notifications@github.com>
Recipient: microsoft/vscode<vscode@noreply.github.com>
Cc: Subscribed<subscribed@noreply.github.com>
Date: Sunday, Jun 28, 2020 19:26
Subject: Re: [microsoft/vscode] Ability to view multiple pages of the samefile (#91664)


Hey @rebornix, this issue might need further attention.
@McGittyHub, you can help us out by closing this issue if the problem no longer exists, or adding more information.

**Comment by subscribe-lark** [comment]
Test


 Original Message 
Sender: tom510230<tom510230@larkmail.xyz>
Recipient: microsoft/vscode<reply@reply.github.com>
Date: Monday, Jul 6, 2020 21:04
Subject: Re: [microsoft/vscode] Ability to view multiple pages of the samefile (#91664)


Tedt


 Original Message 
Sender: github-actions[bot]<notifications@github.com>
Recipient: microsoft/vscode<vscode@noreply.github.com>
Cc: Subscribed<subscribed@noreply.github.com>
Date: Sunday, Jun 28, 2020 19:26
Subject: Re: [microsoft/vscode] Ability to view multiple pages of the samefile (#91664)


Hey @rebornix, this issue might need further attention.
@McGittyHub, you can help us out by closing this issue if the problem no longer exists, or adding more information.
