### ISSUE TITLE
Showing method signature only working with certain characters following

### ISSUE THREAD

**Issue by dustin2711** [microsoft/vscode#91678]
On pressing Ctrl+Shift+Space, the method signature shows up. Unfortunately, this only works when certain characters follows the cursor, e.g. a space, a quote or a bracket.
I show you some examples with the str() method where this | is the cursor.

Signature showing up:
str(|), str( | ), str(|"foo"), str( | "foo"), str( | foo)

Signature not showing up:
str(|foo), str(|str(""))

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
