### ISSUE TITLE
No warning or error when trying to save a non-editable CustomEditor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91675]
Testing https://github.com/microsoft/vscode/issues/91325

When I try to save a read only css file, I get this toast: 
![image](https://user-images.githubusercontent.com/38270282/75438140-bf9d3800-5957-11ea-8f90-f60fbc944826.png)

When I try to save a custom editor that doesn't have `CustomEditorCapabilities.editing` it silently doesn't save.

**Comment by mjbvz** [comment]
I discussed this with @bpasero as some point. My understanding is that we actually have two types of `readonly` files internally:

- Readonly editors. For example, the left side of a git diff view or files opened by a `TextDocumentProvider` are readonly and cannot be edited.

- Files stored in readonly locations. These files can be edited but not saved back to the file system

Custom editors without `editable` are closer to the first case however I believe that notification is actually for the second case of readonly.

For readonly editors, save does nothing. I believe this is the correct behavior for custom editors as well
