### ISSUE TITLE
CustomEditorEditingCapability backup delay should be documented

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91676]
Testing https://github.com/microsoft/vscode/issues/91325

I found that if I made an edit then immediately closed the window, `backup` will not be called. I think this is just the debounce, but it would be helpful to include the length of the delay in the doc for `backup`

**Comment by alexr00** [comment]
Additionally the `Thenable<boolean>` should also be documented. What does the boolean mean?

**Comment by mjbvz** [comment]
The first case seems like a bug (unless you had auto-save enabled)

**Comment by mjbvz** [comment]
I believe the first issue should be fixed now too

Adding documentation on the delay
