### ISSUE TITLE
diff editor: key command for revert current change 

### ISSUE THREAD

**Issue by RichardHuenermann** [microsoft/vscode#91679]
In WinMerge, you can open two files and scroll through the diffs using alt down/up. You can then use alt left/right to copy code from one file to the other, which makes the workflow very fast. 

Something similar would be nice for the diff editor in VSCode. I could not find any way of doing this.  In thread #20038 I found the actions workbench.action.compareEditor.nextChange and workbench.action.compareEditor.previousChange, which seem to be the only ones for the compareEditor so far.

Since the key commands for scrolling through diffs are alt+F5 and alt+shift+F5, maybe alt+F6 would be a good choice to revert the change. This would accelerate the pre-commit checks a lot. Thanks in advance!

**Comment by roblourens** [comment]
There is the command "Revert selected ranges", does that do what you are looking for? If not, can you explain some more?

**Comment by RichardHuenermann** [comment]
Thanks for getting back to me so quickly. I only found the revert selected ranges command for Git. I'm primarily working with SVN as source control right now, so that doesn't help me at the moment. I just tried the command with a git working copy and yes that would do exactly what I'm looking for. Does that mean I should file a feature request with the SVN extension?

**Comment by roblourens** [comment]
Yes, I think so. Thanks
