### ISSUE TITLE
Custom editor: closing custom editor does not dispose text model

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91670]
Refs: https://github.com/microsoft/vscode/issues/91325

* open a custom editor associated with a text document
* close that editor

=> 🐛 I see no dispose call to the text file editor model

**Comment by mjbvz** [comment]
This is definitely a bug, however I'm holding off on fixing this until March because the fix is risky and because we don't ship any built-in text based custom editors

**Comment by mjbvz** [comment]
I'll also add a test for this to the custom editor example extensions
