### ISSUE TITLE
Lines are not exactly the same height

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode#91686]
``` jsonc
"diffEditor.insertedTextBackground": "#2c9b0033",
"diffEditor.insertedTextBorder": "#000000",
```
![Screenshot from 2020-02-27 15-22-17](https://user-images.githubusercontent.com/20030910/75443383-845e3180-5976-11ea-8811-5fee31a36b41.png)
![Screenshot from 2020-02-27 15-31-42](https://user-images.githubusercontent.com/20030910/75443593-fc2c5c00-5976-11ea-9cc2-4969bf637361.png)

And I have a question.
When I Set the color of `diffEditor.insertedTextBorder` to `"#00000000"`:

![Screenshot from 2020-02-27 15-52-42](https://user-images.githubusercontent.com/20030910/75444853-7d84ee00-5979-11ea-975d-a279f74f7e8b.png)

The lines collide, Why? and When comment `diffEditor.insertedTextBorder` :

![Screenshot from 2020-02-27 16-00-45](https://user-images.githubusercontent.com/20030910/75445271-5844af80-597a-11ea-8e32-967b11d74d17.png)

- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04
- Resolution: 3840×2160

**Comment by roblourens** [comment]
Are you zoomed in? I think I see the first screenshot when I zoom a few levels.

**Comment by fakhamatia** [comment]
> Are you zoomed in?

Yes, I set `"window.zoomLevel": 0.50`
When I comment it, I didn't see height size problem. But I still have lines collide thing.

**Comment by alexdima** [comment]
This is due to using `window.zoomLevel`. I recommend to use `editor.fontSize` for pixel perfect rendering. The `window.zoomLevel` is implemented outside of our control and even if we render rectangles at integer coordinates that perfectly touch each-other, the zooming might introduce rounding errors and create such artefacts.
