### ISSUE TITLE
Show Local broken

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#91687]
It keeps showing remote:
![showlocal](https://user-images.githubusercontent.com/9205389/75449979-48bf6980-596e-11ea-97da-9cb58b4795a7.gif)

Version: 1.43.0-insider
Commit: 0eebaf9ad23748baca2afc0da425650922bc23de
Date: 2020-02-27T07:32:05.320Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

**Comment by chrmarti** [comment]
Uploaded wrong GIF. Working on getting screencapture working again...

**Comment by chrmarti** [comment]
Updated GIF.

**Comment by alexr00** [comment]
Caused by 5dfa261ceddacf93eefc9612e48b170f3ee8bbf0, which deleted the check for local schema.
