### ISSUE TITLE
Allow warning popup box for git branch

### ISSUE THREAD

**Issue by deepika231-max** [microsoft/vscode#91684]
Hi,
I Suggest you to allow a warning popup box while we open vscode for the first time in a day.
So that it should be cleared which branch you are working on.

Thanks!

**Comment by roblourens** [comment]
I'm not sure this is necessary - we already have the branch name in the status bar.

A notification could add a warning popup if you really want it.

**Comment by deepika231-max** [comment]
Yes I know a branch name is populated in the status bar.
But still a warning could be better. Because we will not be able to ignore the warning popup
