### ISSUE TITLE
CSS property "content" has wrong syntax highlighting color in SCSS files

### ISSUE THREAD

**Issue by JayEn84** [microsoft/vscode#91685]
Issue Type: <b>Bug</b>

If you open an SCSS file, the CSS property "content" will have the color of a CSS selector and not the color of a CSS property:

![grafik](https://user-images.githubusercontent.com/4518738/75444632-11e45600-5964-11ea-9d99-36ffdafdc4d2.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
vscode-intelephense-client|bme|1.3.11
vscode-eslint|dba|2.1.1
githistory|don|0.5.4
gitlens|eam|10.2.1
apacheconf-snippets|eim|1.3.0
githd|hui|2.2.3
smarty|imp|0.3.0
vscode-apache|mrm|1.2.0
es6-css-minify|olb|3.3.2
phpdoc-comment-vscode-plugin|rex|1.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
phpdoc-generator|ron|1.0.3
vscode-fileutils|sle|3.0.1
pdf|tom|0.5.1

</details>

**Comment by usernamehw** [comment]
/duplicate of https://github.com/atom/language-sass/issues/226
