### ISSUE TITLE
Log (Sync) is empty

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91696]
I was testing https://github.com/microsoft/vscode/issues/90150 and made my settings file really big. Then I went to the Output for Log (Sync) to see what was happening. The Output is empty. When I Open Log File the file userDataSync.log is also empty. The Copy Path command only copies the file name, so I think the file doesn't exist.

**Comment by alexr00** [comment]
Huh, looks like sync had gotten turned off and that's why the log was empty. It might be good to have something in the log that indicates that sync isn't on. Or just don't show it in the Output drop down if the file doesn't exist.

**Comment by sandy081** [comment]
Hmm yes and no. Not sure how often this would be that going to sync log when sync is turned off in a new session. 

I will keep it open in case if users also get into this.

**Comment by alexr00** [comment]
The problem was that I thought sync was on (because I had turned it on), and didn't understand why the log was empty. I soon thought to look for the Turn Sync On command, but it would have been better if the log had said that sync got turned off.

**Comment by sandy081** [comment]
I see. Agreed to add status of the sync when VS Code is started.

**Comment by sandy081** [comment]
To verify: Make sure Settings Sync log shows status of the Sync always (even when it is disabled).
