### ISSUE TITLE
Allow to set background color for active panel title

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#91699]
Currently it is possible to change the border color for the active panel title using `panelTitle.activeBorder`, allow a similar setting for the background color, maybe `panelTitle.activeBackground`. 

## Current
![1](https://user-images.githubusercontent.com/5412540/75462894-365b2500-599a-11ea-993c-11def6e76fdf.png)

## Desired 
![2](https://user-images.githubusercontent.com/5412540/75462952-4d017c00-599a-11ea-8849-2ead27d209a3.png)

**Comment by bpasero** [comment]
fyi a PR is up for this to address.
