### ISSUE TITLE
InvalidOperation exception when trying to view Registers in debugging session

### ISSUE THREAD

**Issue by omendezmorales** [microsoft/vscode#91694]
Issue Type: <b>Bug</b>

Entered a debug session using 1-1.cpp from this [repo](https://github.com/usernamegenerator/CrackingTheCodingIntervew4th) , and then set a breakpoint in line 28 (within the uniqueCharUsingArray function) . 
The debug session looks like it broke, and in the Debug console, I read:
_"Stopping due to fatal error:  Invalid OperationException: No handler registered for request of type 'read-register-list'"_.

Not sure this is expected behavior during a debugging session.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|19.39GB (4.02GB free)|
|Process Argv|CrackingTheCodingIntervew4th/ --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
ballerina|bal|1.1.3
calva|bet|2.0.77
clj-kondo|bor|2020.2.15
better-toml|bun|0.3.2
code-runner|for|0.9.16
kotlin|fwc|0.2.11
plantuml|jeb|2.13.6
julia-debug|Jud|0.0.32
language-julia|jul|0.13.1
vscode-idl|kur|0.1.2
vscode-sbt-scala|lig|0.2.4
Kotlin|mat|1.7.1
vscode-docker|ms-|0.10.0
python|ms-|2020.2.64397
cmake-tools|ms-|1.3.1
cpptools|ms-|0.26.3
platformio-ide|pla|1.10.0
vscode-yaml|red|0.7.2
rust|rus|0.7.0
scala|sca|0.3.9
crates|ser|0.4.7
code-settings-sync|Sha|3.4.3
html-preview-vscode|tht|0.2.5
language-pde|Tob|1.4.1
pdf|tom|0.5.1
vscode-icons|vsc|10.0.0
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
grammarly|znc|0.6.2

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
