### ISSUE TITLE
Custom editor: extension should create CustomDocument and get it passed into resolveCustomEditor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91690]
Refs https://github.com/microsoft/vscode/issues/91325

When implementing a custom editor that is not text based, I have to implement 2 methods:
* `resolveCustomEditor`
* `resolveCustomDocument`

The editor is actually the one that is driving everything, e.g. edits emit from there. However, the capabilities are in some other place, associated to the document? 

It is not clear to me how I get access to my capabilities from the document. Should I use the user data for that purpose?

**Comment by bpasero** [comment]
I will end up having to keep a `Map<CustomDocument, CustomEditorCapabilities>` in some global to get around this.

**Comment by bpasero** [comment]
I think what I actually want is that I am returning a CustomDocument from `resolveCustomDocument` which is then getting passed into the `resolveCustomEditor` method. I would then operate on methods from my own custom document in the same way I can do operations on `TextDocument`.

**Comment by bpasero** [comment]
This is especially confusing because the method is called `resolveCustomDocument` while it only returns `CustomEditorCapabilities`

**Comment by mjbvz** [comment]
Yes, the `userdata` field was intended for this purpose. However I find myself setting `userData` to the capabilities object.

Some possible api directions:

- Have `capabilities` be a property on `CustomDocument` that extensions can get or set (possibly replacing `userData`)

- Move all the capabilities back onto the `CustomEditorProvider` and update all the capability methods to take a `CustomDocument` as their first argument

**Comment by mjbvz** [comment]
The more I think about it, the more I like approach two. This is basically the delegate based approach we already tried. This would move `CustomEditorEditingCapability` to a property on `CustomEditorProvider` and update each of the `CustomEditorEditingCapability` methods to take `CustomDocument` as its first argument. 

I believe this would also play more nicely with any future methods we may add to custom documents, such as handlers for rename.

**Comment by mjbvz** [comment]
We've changed to what should be a more familiar model:

- `CustomDocument` is now a class
- renamed `resolveCustomDocument` to `openCustomDocument`
- `openCustomDocument` now returns a `CustomDocument`
