### ISSUE TITLE
Reopen #16221 (Parameter Hints shown inline all the time (like IntelliJ))

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode#91692]
Parameter and type hints shown inline in the editor like IntelliJ. 

The rust-analyzer extension has them (https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/features.md#code-hints) but they do have bugs since this is not a officially supported by vscode.

The issue mentioned #16221 was closed because of the [recommendation](https://github.com/microsoft/vscode/issues/16221#issuecomment-577377154) for using a plugin that **only works** with typescript.

**Comment by roblourens** [comment]
That issue isn't closed, it's still open to track this issue. It was just locked due to spam.
