### ISSUE TITLE
"Running Save Participants" preventing saving...

### ISSUE THREAD

**Issue by raptor235** [microsoft/vscode#91693]
"Running Save Participants" may take very long to complete alert is preventing saving...

This has just started happening across multiple php files... 

<img src='http://www.flowpress.com/screenshots/screenshot%202020-02-27%20at%209.17.39%20AM.png'/>

Seems to be related to formatting... not sure what to do other then disabling format on save.

**Comment by aldendaniels** [comment]
Also hitting this in a large TS project

**Comment by jrieken** [comment]
> Seems to be related to formatting... not sure what to do other then disabling format on save.

- Disable format on save
- File an issue against the php formatter
