### ISSUE TITLE
Default search on ctrl+shift+F without pressing enter key is not working anymore

### ISSUE THREAD

**Issue by AravindGopala** [microsoft/vscode#91691]
- VSCode Version: 1.43.0 insiders
- OS Version:19.14 ubuntu

Steps to Reproduce:

1. In the editor try to search a word in a file in the entire workspace using ctrl+shifr+f, then the work is not searched in the entire workspace until unless I explicitly press enter on the word in the search window
2. Previously as long as the word in the editor is selected using ctrl+shifr+f, the word is automatically searched in the entire workspace.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
This was changed on purpose to prevent accidental search triggering. From https://github.com/microsoft/vscode/issues/90962 I'm still not sure how I feel about it. Will leave it open for feedback.

**Comment by AravindGopala** [comment]
Is it possible to turn back on via a setting?

**Comment by JacksonKearl** [comment]
Same as #91901. More discussion over there.

**Comment by RodriguezLucha** [comment]
So there is no way to turn this back on?

**Comment by JacksonKearl** [comment]
See https://github.com/microsoft/vscode/issues/91901#issuecomment-598296691, we'll improve this this iteration.
