### ISSUE TITLE
Custom editors: how to find out that text document is readonly?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91697]
Refs: https://github.com/microsoft/vscode/issues/91325

A text document can be readonly if it's underlying file system provider is readonly. I am not sure how a custom editor implementor can figure this out and provide the correct experience.

**Comment by mjbvz** [comment]
Could we add a `isReadOnly` property to `TextDocument`?

Does VS Code already know if a given textDocument is `isReadOnly`?

**Comment by bpasero** [comment]
We basically ask the file system provider for the resource of the document for being readonly or not. That should be doable.
