### ISSUE TITLE
Custom editors: backup has cancellation but others not?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91702]
Refs #91325

I am not sure why `backup` comes with cancellation support but e.g. `save` does not. Would we not cancel a save when a second save attempt is made? I also wonder about the other methods.

**Comment by mjbvz** [comment]
Yes, probably makes sense for `save` at least. 

I added a cancellation on `backup` because I expected it to take the most time, but `save` could also be expensive

**Comment by bpasero** [comment]
I think we should add it to all long running operations even if we do not call it in the beginning.

**Comment by mjbvz** [comment]
I have added cancellation tokens to all file operations (save, backup) as well as to the providers themselves
