### ISSUE TITLE
Regression: Quickly closing a git commit message in VS code skips autosave, causing a 

### ISSUE THREAD

**Issue by lukewlms** [microsoft/vscode#91709]
There appears to be a regression of this fix: https://github.com/microsoft/vscode/issues/72573

- VSCode Version: 1.42.1
- OS Version: MacOS 10.14.6

Steps to Reproduce are identical to before:

1.    Add VS Code as git commit editor (code --wait)
2.    Perform a git commit
3.    Edit the commit message in Code
4.    Quickly close the commit message in Code, before autosave occurs

Result: git reports an empty commit message, even though Autosave is enabled in VS Code.  This makes VS Code not very useful as a git commit message editor as I'm not certain it will actually save what I'm writing.

Does this issue occur when all extensions are disabled?: Yes

Thanks!

**Comment by roblourens** [comment]
I can't repro this. What are your autosave settings?

**Comment by lukewlms** [comment]
As follows - 1 second with delay.  Often I am pasting in a task identifier and immediately closing, which is very quick.

![image](https://user-images.githubusercontent.com/19214773/75496606-add78700-598f-11ea-9823-675f409da556.png)
