### ISSUE TITLE
multi-view horiz scroll causes vert scroll

### ISSUE THREAD

**Issue by CNSKnight** [microsoft/vscode#91708]
Issue Type: <b>Bug</b>

In a window with 2 views (split right), any attempt to grab horizontal scrollbar in either view causes that view to:
- select from the currsor position
- scroll vertically, expanding selection, whilst the horiz scroll bar is engaged

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-76-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 3647)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 0|
|Memory (System)|17.46GB (2.42GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-peek|dar|1.0.2
githistory|don|0.5.4
xml|Dot|2.5.0
vscode-style-formatter|dwe|1.0.0
vscode-babel-coloring|dza|0.0.4
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
vue-snippets|hol|0.1.11
copy-current-file-path|ion|0.0.3
vue|jcb|0.1.5
sublime-babel-vscode|jos|0.2.10
php-cs-fixer|jun|0.1.129
vscode-sshfs|Kel|1.16.3
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
vuejs-extension-pack|mub|1.1.6
vetur|oct|0.23.0
vscode-essentials-snippets|rob|2.0.0
php-formatter|Sop|0.2.4
prettier-plus|svi|3.6.5
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.5
babelrc|wad|1.0.0
quokka-vscode|Wal|1.0.279
markdown-all-in-one|yzh|2.7.0
json|Zai|1.0.4

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I can't reproduce this, or I don't understand. 

Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

Or is there any way you can record the screen to show us the issue?
