### ISSUE TITLE
Use proper SVG icons for tree twistie

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#9170]
@joaomoreno see attached the SVGs. I also noticed that for HC theme we seem to use a data URI already?

[Twisty_icon_16x.zip](https://github.com/Microsoft/vscode/files/360772/Twisty_icon_16x.zip)

**Comment by joaomoreno** [comment]
That icon set seems to lack the expanded (filled) twistie. Where did you get that from?

**Comment by bpasero** [comment]
@bgashler1 can you answer?

**Comment by joaomoreno** [comment]
Oh they are all there, something's wrong with my OS X's preview feature. The expanded icons look broken, but they are OK.
