### ISSUE TITLE
Custom editors: revert() is missing?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91700]
Refs https://github.com/microsoft/vscode/issues/91325

I think for a non-text custom editor, it needs to expose a `revert` method. I know we could play-back all edits we got, but for normal files a revert will actually re-read the file from disk. This may have different semantic for custom editors too.

**Comment by mjbvz** [comment]
Yes my intent was to use `undoEdits`/`applyEdits` for this but having an explicit `revert` method may be helpful
