### ISSUE TITLE
Extension API to access and manage Debug Configurations

### ISSUE THREAD

**Issue by awschristou** [microsoft/vscode#91716]
I'd like to request an API for extension developers to use in order to retrieve, modify, and add debug configurations to `launch.json`. 

Benefits:
* reduce the risk of data corruption when extensions directly write to the file (for example: writing an invalid structure)
* encapsulate handling whether or not the file exists in the workspace
* encapsulate file content concerns such as existing formatting/comments

**Comment by Gama11** [comment]
It's not quite the same thing, but are you aware of the [`DebugConfigurationProvider`](https://code.visualstudio.com/api/references/vscode-api#DebugConfigurationProvider) API?

**Comment by awschristou** [comment]
@Gama11 absolutely -- the nuance with `DebugConfigurationProvider` is that `provideDebugConfigurations` only kicks in when populating a launch.json file from scratch. There are times when an extension would want to add more entries into an existing launch.json, for example when users add more entrypoints into a workspace.

**Comment by weinand** [comment]
This is mostly covered by #88230.

**Comment by awschristou** [comment]
I like the proposal in #88230 . 

I'm unclear if that proposal provides users with a way to see and insert new debug configurations that a `DebugConfigurationProvider` detects after launch.json has been populated.

If that is (or can be) accommodated in the 88230, this is great. If not, this feature request would allow extensions to surface suitable gestures to users, which in turn can update launch.json.

**Comment by weinand** [comment]
As part of #88230 it has become possible to add a dynamic launch config to the launch.json by clicking in the gear button on the right hand side of the QuickPick menu:

![2020-11-09_18-13-09 (1)](https://user-images.githubusercontent.com/1898161/98573908-97702200-22b7-11eb-9013-6ff7943bcd01.gif)
