### ISSUE TITLE
Align line numbers in search editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91718]
![image](https://user-images.githubusercontent.com/2230985/75491959-a605eb80-596b-11ea-97a1-31d064f0458d.png)

Notice that the line numbers have a different number of digits, so the code is aligned differently on line 8 versus 31. It'd be nice to pad the numbers so that code is consistently aligned within each search result.

![image](https://user-images.githubusercontent.com/2230985/75492056-cdf54f00-596b-11ea-8f3f-432bfe1d7718.png)

**Comment by JacksonKearl** [comment]
Yeah... been meaning to do this for a while now lol

**Comment by JacksonKearl** [comment]
2158b1aa6566ccde4898200e7d39861b308ba2b0
