### ISSUE TITLE
Debug start view duplicating whenever a debug session ends

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91712]
![image](https://user-images.githubusercontent.com/2230985/75481505-012de300-5958-11ea-85b3-209dacc7c1a1.png)

Recording: https://memes.peet.io/img/9c69f466-3157-4e82-979b-45b882852df9.mp4

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders.
@connor4312  Are you sure you are on latest?

**Comment by connor4312** [comment]
yep, my bad, was a day behind on insiders
