### ISSUE TITLE
Save as doesn't work when using jupyter notebooks

### ISSUE THREAD

**Issue by shneezers** [microsoft/vscode#91715]
Issue Type: <b>Bug</b>

I can open up a notebook, make changes and then when selecting `save as` through the File menu drop down, nothing happens.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.34.0
json-tools|eri|1.0.2
path-autocomplete|ion|1.13.3
python|ms-|2020.2.64397
atom-keybindings|ms-|3.0.6
vscode-terminal-here|Tyr|0.2.4
vscodeintellicode|Vis|1.2.5
markdown-pdf|yza|1.4.2
material-theme|zhu|3.2.3

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
