### ISSUE TITLE
VSCode crashes in WSL/Linux during DAP failure responses

### ISSUE THREAD

**Issue by g2-aj** [microsoft/vscode#91719]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04.4 LTS
Note - this also occurs on WSL

Steps to Reproduce:

1. DAP "success:false" response for Launch request results in VSCode crashing and not showing the DAP message to user in notification pop-up like it does in windows
2. Using Nodejs Mocha test framework and module 
import {DebugClient} from 'VSCode-debugadapter-testsupport' - tests that check for failure responses abort and I believe it is because of the crash mentioned in 1.
3. Related to 2 - all tests time out on ubuntu and WSL even though the debugger works (manually verified).

Does this issue occur when all extensions are disabled?: Yes

**Comment by g2-aj** [comment]
By tests timing out I mean from things like:

let dc = DebugClient;

dc...send requests
dc.WaitForEvent()… // this times out even though my logging of all DAP requests and responses shows that the output event in question did occur.

**Comment by weinand** [comment]
What is your WSL setup?
The "Steps to reproduce" from above are not actionable. Please provide real steps that I can reproduce.

**Comment by g2-aj** [comment]
Let's go with Ubuntu setup:
OS Version: Ubuntu 18.04.4 LTS

**Packages installed:**
sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
sudo apt-get install npm
sudo npm install -g vsce

**Typescript mocha tests that test for expected failures:**
I followed the example from the mock debugger here: https://github.com/microsoft/vscode-mock-debug/tree/master/src/tests

`import * as assert from 'assert';
import {DebugClient} from 'vscode-debugadapter-testsupport';
import * as fs from 'fs';
import * as Path from 'path';

suite('SingleThreaded', () => {

    let dc: DebugClient;

    setup( () => {
        // DEBUG_ADAPTER for me is a full path to my C++ debugger executable
        dc = new DebugClient(DEBUG_ADAPTER, '', 'debugger-type-name');
        return dc.start();
    });

    teardown( () =>
    {
        dc.stop();
    });

    suite('unknownRequest', () => {

        test('unknown request should produce error', done => {
            dc.send('gibberish').then(() => {
                done(new Error("does not report error on unknown request"));
            }).catch(() => {
                done();
            });
        });
    });
	
	suite('noDebugSymbolsProvided', () => {

        test('should fail launch request', () => {

            return Promise.all([
                dc.configurationSequence(), // waits for initialized event then sends configurationDone request
                dc.launch({ program: PROGRAM, args: [BYTECODE], stopAtEntry: false, traceDAP: true, cwd: CWD }).then(response => {
                    response.body = response.body || {};
                    assert.equal(response.success, "false");
                })

            ]).catch(error => {
                console.log("noDebugSymbolsProvided error (expected): ", error.message);
            });
        });
    });
});`

I execute these tests as follows:
`npm run compile && mocha -u tdd --timeout 10000 --colors ./out/debug_test/`

When I run the above command, the first test starts, times out and then says "KILLED".

**Reproducing manual VScode crash:**
My debugger checks the launch options during the DAP Launch request. If there is something wrong or missing I return a launch failure response that looks like:
{"seq":1,"type":"response","request_seq":2,"**success":false**,"command":"launch","**message**":"launch: property 'x' is missing or empty"}

On Windows, the **message** in the Launch response above is displayed in a Notification window to the user. On Linux, Vscode just crashes. However I can see though logging within my debugger that this failure response was returned.

**Comment by g2-aj** [comment]
I tried running the tests from https://github.com/microsoft/vscode-mock-debug/tree/master/src/tests and did not run into the timeout issues I exprience with my own tests. Let me use this as a starting point to compare.

**Comment by g2-aj** [comment]
I am trying to reproduce the failed launch response in the Mock Debugger (if I can). However when I launch the "Extension" option, there is no "Mock Debug" option that is available. Note: I don't want to install the Mock Debug extension available on marketplace, I want to use the example using the Extension Development Host.
What am I missing?

Just to clarify I want to launch this option:

`"configurations": [
		{
			"name": "Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "npm: watch"
		},`
