### ISSUE TITLE
DocumentSelector instead of scheme(s) for registerTimelineProvider

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91721]
`registerTimelineProvider` takes as its enablement clause a string or array of strings for the schemes to which it applies. It would be nice if this were instead the `DocumentSelector` that we use in other providers, as that offers more flexibility (search editors for instance are defined by language rather than scheme: `{ language: 'search-result' } `.

**Comment by eamodio** [comment]
@JacksonKearl @jrieken and I talked about using a `DocumentSelector` vs scheme and we felt that scheme was more appropriate here, because a `TimelineProvider` is `Uri`-based, not document-based. For example, the `Uri` could be a folder or workspace.

**Comment by jrieken** [comment]
Yeah, I still think that scheme-only is correct because the timeline is per resource. Maybe, simplify the `register`-function to only accept a single string (like other scheme-only providers) so that this doesn't look like a doc-selector.

**Comment by eamodio** [comment]
Without allowing multiple schemes, it will make it more complicated to use. For example, the Git provider registers `file`, `git`, and `gitlens-git` right now. Although, I could go back to using `*` instead.

**Comment by jrieken** [comment]
Yeah - we could allow `*` but calling register three times or in a loop shouldn't be too much a hassle

**Comment by eamodio** [comment]
Even though it is non-standard, I really like being able to target multiple schemes with 1 provider registration, having multiple registrations seems like needless ceremony imo.

See the usage here:
https://github.com/microsoft/vscode/blob/28dbe0755ec2a103ea500f4c40d7229c435720a6/extensions/git/src/timelineProvider.ts#L77
