### ISSUE TITLE
Intellisense unusably slow for large (node.js) project on linux

### ISSUE THREAD

**Issue by BhavinIoT** [Microsoft/vscode#9172]
- VSCode Version: 1.3.1
- OS Version: Linux 3.13.0-65-generic (Ubuntu 14.04)

Hey, guys. First off, kudos! Just switched from sublime text 3 a week ago and I'm liking what I see. One big issue I've faced: Intellisense stops working if my project gets too large. I've done the following to narrow the issue down:
1. Disabled all plugins. _INTELLISENSE DOESN'T WORK_
2. Duplicated the project without .git folder and opened in VSCode. _INTELLISENSE DOESN'T WORK_
3. Opened a single file/small project. _WORKS_ 

Steps to Reproduce:
1. Create a large project (10,000+ LoC, node_modules ignored). 
2. Setup a git repo
3. Work for a couple of days (I've made 100+ commits in the past 5 days. It stopped working 3 days in)

P.S: It's a sails.js project

Thnx

**Comment by dbaeumer** [comment]
@BhavinIoT can you share your project? Otherwise it is hard to understand why code complete doesn't work for you.

**Comment by waderyan** [comment]
Closing until more info is obtained.
