### ISSUE TITLE
Cannot find help for trying to #include libraries in C++

### ISSUE THREAD

**Issue by zenderman333** [microsoft/vscode#91728]
Issue Type: <b>Feature Request</b>

After many hours of searching, I cannot find help for including libraries in C++ (when #include <stdio.h> is inputted the open source cannot find the file). I am assuming that there is a seperate download for this, but I cannot find such download or help towards it.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
Have you followed all steps in setup https://code.visualstudio.com/docs/languages/cpp ?
Please note:
> The C/C++ extension does not include a C++ compiler or debugger. You will need to install these tools or use those already installed on your computer.

**Comment by roblourens** [comment]
Please see those docs or file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
