### ISSUE TITLE
Two-finger swipe is not sensitive

### ISSUE THREAD

**Issue by BobbyBBY** [microsoft/vscode#91729]
Issue Type: <b>Feature Request</b>

When using notebook ’s trackpad to slide slowly with two fingers, it can swipe up but not down, and there is no problem when swiping quickly. This problem was also found on other notebooks of different models. This leads to inaccurate control when trying to see the next few lines. If this is an anti-false touch function, it is desirable to be able to set a switch.
The link below is the question display
https://youtu.be/iCwzUaw0nF0

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
What model of laptop is that?

**Comment by BobbyBBY** [comment]
Xiaomi Notebook Pro and dell latitude 7300
