### ISSUE TITLE
Qsharp: qs module fails to import when running regularly the first time

### ISSUE THREAD

**Issue by malimban** [microsoft/vscode#91733]
- Version: 1.42.1 (user setup)
- OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Attempt to run the python file using the green arrow
2. ModuleNotFoundError: No module named

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/17767075/75504080-6fe55d80-59a5-11ea-9b61-4c6f489c52f1.png)
Picture displaying command failing in VS Code, but works fine when copied to native cmd terminal.

**Comment by malimban** [comment]
So after looking at it for some time, the error is not from
- commands too long
- being in directory\foo and executing ./bar/host.py
- improperly installed qsharp

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
