### ISSUE TITLE
Prioritize key press for the integrated terminal panel

### ISSUE THREAD

**Issue by 999-Victor** [microsoft/vscode#91735]
* VS Code Version: 1.42.1 (system setup)
* OS: Windows_NT x64 10.0.17763

Hello.
I use a integrated bash terminal for ssh connection to Linux server. Some Linux apps assign the function keys (F1-F12) to control their work, but if you'll press F1, for example, VS Code will open Command Palette.
Is it possible to prioritize key press for the integrated terminal panel when it's active?

**Comment by IllusionMH** [comment]
/question

It is possible with overriding entries in `terminal.integrated.commandsToSkipShell`. It has long default list and `workbench.action.showCommands` which is mapped to <kbd>F1</kbd> is in the list. Use `-` before command name to remove it from list
e.g.

```json
"terminal.integrated.commandsToSkipShell": [
    "-workbench.action.showCommands"
]
```
