### ISSUE TITLE
Keyboard arrows keys don't scroll in the Extensions window

### ISSUE THREAD

**Issue by Moke-RS** [Microsoft/vscode#9173]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Home Insider Preview

Steps to Reproduce:

1. Open Extensions window
2. Select "Show Popular Extensions" (I think this issue will happen in any case of scrollbar appearing - showing popular extensions is enough to do the trick)
3. Select any extension that appears
4. Press continually keyboard arrow down key

It will swap the selected extensions but it is not going to scroll, what is weird.

**Comment by joaomoreno** [comment]
#8621
