### ISSUE TITLE
Mac OS installation problem with Microsoft Visual Studio Code 

### ISSUE THREAD

**Issue by DhruvDoshi** [microsoft/vscode#91734]

**Comment by DhruvDoshi** [comment]
The major problem comes when I downloaded a package from the official webspace and as I tried to run it, it cracks up and pops up message that it is not uptodate thing. Well I downloaded it few minutes ago what should I drop I also tried with home-brew and Curl codes still they aren't working

**Comment by gjsjohnmurray** [comment]
/duplicate - see https://github.com/microsoft/vscode/issues/91593#issuecomment-591682821 for latest advice
