### ISSUE TITLE
Marketplace problem

### ISSUE THREAD

**Issue by ahmadosgalal** [microsoft/vscode#91739]
Issue Type: <b>Bug</b>

The marketplace extensions can't be downloaded directly, I have to download them manually and then install  them from the VSIX file. The marketplace doesn't even show  extensions icons.
Thanks in advance!

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.19.0
python-extension-pack|don|1.6.0
vscode-html-css|ecm|0.2.0
MagicPython|mag|1.1.0
python|ms-|2019.5.18875
cpptools|ms-|0.26.3
material-icon-theme|PKi|3.9.3
vscodeintellicode|Vis|1.1.7
vscode-icons|vsc|10.0.0
jinja|who|0.0.8
material-theme|zhu|3.2.3

</details>

**Comment by gjsjohnmurray** [comment]
Maybe DNS or proxy issues? Please search here for similar ones, some of which have tips about what to try.

**Comment by mattiaskagstrom** [comment]
Yupp, Automatic updates and Extension Marketplace broke in version 1.40 if you are behind a corporate proxy. Possibly a bug in Electron. Still unkown.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by mattiaskagstrom** [comment]
> Please follow these steps
> 
> * Help -> Toggle Developer Tools -> Network
> * Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
> * To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
> * If it is not a network issue, please share the logs from the following locations
>   
>   * Help -> Toggle Developer Tools -> Console
>   * View -> Command Pallette... -> Toggle Shared Process -> Console
>   * View -> Open View… -> Log (Shared)
>   * View -> Open View… -> Log (Window)

Requests fails in network tab
I can access the python logo

logs only give a "Request timed out" as pasted above

and as stated above, this is a network issue. After vs code 1.40 vs code can no longer access the internet through our corporate proxy. If i downgrade to 1.39 it all works.

**Comment by sandy081** [comment]
Looks proxy releated.

**Comment by mattiaskagstrom** [comment]
This seems to work in vs code 1.43 insider

**Comment by mattiaskagstrom** [comment]
hmmm, never mind! A Colleague noticed that the problem only occurs when running vs code as administrator.

Requests to the marketplace and update server works when not running as administrator.

(Works in both 1.42 and 1.43)
It also breaks in 1.43 when starting it as admin.

**Comment by chrmarti** [comment]
Does is work with 1.39 in admin mode?

**Comment by emiltorp** [comment]
I have the same problem, and yes, it does work in admin mode on 1.39.

**Comment by deepak1556** [comment]
Sorry for the delay, can you launch code with `--log-net-log=netlog.json` , perform the failed extension search and quit the app. Perform this when launching as an admin and user mode, attach both the logs. Thanks!
