### ISSUE TITLE
Change position for the git peekview actions 

### ISSUE THREAD

**Issue by abaracedo** [microsoft/vscode#91745]
I would like to suggest to change where the git peekview tools are displayed, now the actions are displayed on the right. That means the user has to move the cursor from the gutter to the action to execute.

![Captura de pantalla 2020-02-28 a las 11 13 07](https://user-images.githubusercontent.com/9487675/75539908-53840800-5a1b-11ea-9ed4-4f386ce3e815.png)

It would be great to have those actions on the left so the cursor is closer to them (maybe the name of the file can be omitted).

![Captura de pantalla 2020-02-28 a las 11 22 14](https://user-images.githubusercontent.com/9487675/75540584-97c3d800-5a1c-11ea-8f70-bc56afc416a6.png)

**Comment by joaomoreno** [comment]
I think this is fine, given that there are keyboard shortcuts for every action in there.

cc @jrieken
