### ISSUE TITLE
Allow to scroll all opened editors at the same time 

### ISSUE THREAD

**Issue by paritosh149** [Microsoft/vscode#9175]
- VSCode Version: 1.3
- OS Version: Windows 7 SP1

- Feature request.

**Comment by bpasero** [comment]
@paritosh149 can you please be more specific what you are asking for?

**Comment by paritosh149** [comment]
I am asking that when two or three editors are open, a setting should allow user to scroll all visible documents, simultaneously. This would be useful while comparing two or three documents.

**Comment by paritosh149** [comment]
Command Palette.... has a Command to Compare and that does synchronous scrolling. So the feature is already present.
