### ISSUE TITLE
runInTerminalRequest doesn't work with new DebugAdapterInlineImplementation

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#91759]
I have implemented a DA inline in our Julia extension. I'm using the default implementation from  vscode-debugadapter. Everything works great, except that it doesn't seem to be feasible to make the reverse request `runInTerminalRequest`. Is support for that something that could be added?

**Comment by weinand** [comment]
Investigation revealed that this is actually a problem in the debug adapter. Moving back to debugadapter repo.

**Comment by davidanthoff** [comment]
Awesome, thanks!

**Comment by weinand** [comment]
@davidanthoff does the fix work for you?

**Comment by davidanthoff** [comment]
Yes, I was able to start a terminal this way. But then I realized that it will actually start a shell and then start things inside that shell, which is not really what I wanted, I had hoped I could start the program directly inside a new terminal in VS Code. Maybe I need to revisit how I'm thinking about this, but in any case, the functionality clearly works now. Thanks!

**Comment by weinand** [comment]
@davidanthoff thanks for your response - I'll add a Verified label.

Please note that the "runInTerminalRequest" supports three types of terminals.
Have you tried the `"kind": "integrated"`? It will create a new terminal in VS Code.

**Comment by davidanthoff** [comment]
I thought so, but I'll double check!
