### ISSUE TITLE
Open new folder - File explorer stuck to Window

### ISSUE THREAD

**Issue by steffanhalv** [microsoft/vscode#91758]
- VSCode Version: 1.42.1
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

1. In macOS top menu, click 'File + Open'
2. Drag position of the file explorer no longer works

Does this issue occur when all extensions are disabled?: Yes

# Description

The 'File explorer' window is stuck to the VS Editor Window & is no longer draggable after update. I also have issues resizing the window as it keeps the file explorer centered which cause it to move out of my monitor screen:

![Skjermbilde 2020-02-28 kl  14 39 04](https://user-images.githubusercontent.com/4593184/75553546-e3847a80-5a38-11ea-8006-af94d14b4fa9.png)

**Edit:**

Looks like githubusercontent has some trouble displaying the image, here is another link:

https://drive.google.com/file/d/1nArKENVd6fjLEYcb9RZFgt6GmyQlCjS4/view?usp=sharing

Please revert this behaviour, it is very frustrating.

**Comment by roblourens** [comment]
I think it has always worked this way. I even checked version 1.16 and it was the same. You can probably drag the whole window to the side to get an edge to resize it.
