### ISSUE TITLE
Terminal dropdown has shrunk

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#91750]
Stable above, insiders below:
![image](https://user-images.githubusercontent.com/38270282/75543019-3ce0af80-5a21-11ea-963b-9de026262383.png)

**Comment by Tyriar** [comment]
Doesn't seem to happen on macOS and the regression happened in the last couple of days. @sbatten have panel/view-related changes happened that could have caused this?

**Comment by Tyriar** [comment]
Affects tasks/custom terminals pretty badly:

<img width="146" alt="Screen Shot 2020-02-28 at 6 42 45 AM" src="https://user-images.githubusercontent.com/2193314/75557827-9f23bb00-59f5-11ea-965c-eaa8ef8d4d19.png">
<img width="226" alt="Screen Shot 2020-02-28 at 6 43 15 AM" src="https://user-images.githubusercontent.com/2193314/75557831-a054e800-59f5-11ea-8c09-c0efba6af892.png">

**Comment by sbatten** [comment]
Likely my fault from drag and drop change
