### ISSUE TITLE
Support MP4 Video Previews

### ISSUE THREAD

**Issue by khalidabuhakmeh** [microsoft/vscode#91756]
If an `mp4` or other web-supported video format exists, it would be nice to be able to preview the video inside of the VS Code editor. This feature would look similar to how a `GIF` might be previewed except with a play head.

You may commonly have video files as part of your directory if they are part of your blog or static site.

**Comment by gjsjohnmurray** [comment]
See also #72280, #87706

**Comment by khalidabuhakmeh** [comment]
Ok, it makes sense. I will close this issue.
