### ISSUE TITLE
Save in User/settings.json "Don't ask about .[extension]" 

### ISSUE THREAD

**Issue by gandalfsaxe** [microsoft/vscode#91764]
First time I open a .out file, a notification pops up to ask if I want to search the market place for this. When I click "Don't ask me again", I don't know where this information is stored, but it's not in `User/settings.json` which I was hoping, since I sync this across machines.

So in the interest of not having to do this many times for various filetypes, I'd like to see this being able to be added to my `User/settings.json`. I'm also curious to know where this is currently written to, so I can perhaps find some workaround for now :)

**Comment by sandy081** [comment]
It is written in global state which cannot be accessed. 

Regarding syncing we are working on syncing global state across machines - #86679
Let me know if this helps you?

**Comment by gandalfsaxe** [comment]
Ok, too bad. Consider this a feature request for changing this to be added into some local / syncable file, .e.g `User/settings.json` or `User/dontask.json` or whatever makes sense :)

About #86679, good to know. I've added a comment to it :)

**Comment by sandy081** [comment]
Ok, changed to feature request.
