### ISSUE TITLE
Debugging in 1.42.1 does not work in macOS

### ISSUE THREAD

**Issue by rhooper1967** [microsoft/vscode#91761]
- VSCode Version: 1.42.1
- OS Version: 10.14.6 and 10.15.3

Steps to Reproduce:

1. Create simple python file
2. Set breakpoints
3. Define default debugging configuration for Current File
4. Start debugging
5. Debug widget appears, a clock appears over the debug icon on the left vertical menu and nothing happens. 

Following the same steps in a Windows 10 machine with the same version of VSCode I am able to set breakpoints and debug the python code.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
