### ISSUE TITLE
Setting extensionHomePath does not install extensions into there

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#9176]
When I set the `extensionHomePath` from the command line and install extensions, I do not find the extension in that location I specified.

**Comment by joaomoreno** [comment]
@bpasero Is this a duplicate of #7505?

**Comment by bpasero** [comment]
@joaomoreno not sure, when I tried I created all the folders before hand.

**Comment by joaomoreno** [comment]
Duplicate of #7505
