### ISSUE TITLE
Add "Cut All" command to search results context menu.

### ISSUE THREAD

**Issue by KrasimirZl** [microsoft/vscode#91760]
Hello,

Would it be possible to add "Cut All" command on Search result. I see "Copy All" is implemented. 
I find it very useful especially when working with text to "cut all lines" from text where search term is found.

Example For "Copy All" context menu.
![image](https://user-images.githubusercontent.com/38329649/75557095-1b46ee80-5a48-11ea-9b94-91b915083df7.png)

Regards,
Krasimir

**Comment by roblourens** [comment]
So you want it to cut the result from the actual file? Hm, I think that's not what I would expect, especially since "copy" copies stuff besides just the result text. I think I would expect a "cut" to copy the result and just remove those rows from the viewlet without touching the file.

**Comment by KrasimirZl** [comment]
Hi Roblourens,

Yes I would like to "Cut" actual lines from files. I am doing this by hand now. 
I am keeping .txt/.md file with project notes. When I start working on a topic/code change usually I find all the relevant lines by keyword and then extract them on top so I can focus on short listed content. This will be able to automate what i am doing on hand and keep me focused on the actual notes not spending time collecting them and moving them around and compacting holes left out  from cutting lines. This might be useful when working with CSV files too.

If search result is for code I think I doesn't make  sense since usually code require more context.

**Comment by roblourens** [comment]
This is an interesting idea but I don't think it's really practical for us to do. Maybe an extension or just some script could help with your workflow.
