### ISSUE TITLE
Configurable editor actions

### ISSUE THREAD

**Issue by aliev** [microsoft/vscode#91763]
It would be great to be able to add additional buttons with editor actions to the "Editor Actions" panel.

<img width="263" alt="Screen Shot 2020-02-28 at 7 35 42 PM" src="https://user-images.githubusercontent.com/407134/75562137-87821c00-5a61-11ea-936c-79374e5c60f4.png">

**Comment by roblourens** [comment]
You can by writing an extension 😁 https://code.visualstudio.com/api

Otherwise you might be looking for something like this request https://github.com/microsoft/vscode/issues/41309
