### ISSUE TITLE
minor: Documentation copypasta bug

### ISSUE THREAD

**Issue by bolinfest** [microsoft/vscode#91772]
The docs for `FoldingRangeProvider` appear to have been copied from `DocumentColorProvider`:

https://github.com/microsoft/vscode/blob/cdde27aea0816662a290b9aa6303fbfe907a5c1e/src/vs/editor/common/modes.ts#L1248-L1256

**Comment by bolinfest** [comment]
Also, is `FoldingContext` supposed to be an empty interface?

**Comment by aeschli** [comment]
Thanks.

yes, `FoldingContext` is empty but there for future options.
