### ISSUE TITLE
Emmet snippets expansion not working on PHP

### ISSUE THREAD

**Issue by raphievila** [microsoft/vscode#91778]
Issue Type: <b>Bug</b>

I'm trying to create an HTML document wrapped on a PHP file extension and the Emmet snippets expansion do not seem to be called to process something like:

```html
main.#main-content.content
```

to turn it into:

```html
<main id="main-content" class="content"></main>
```

when one hits the tab key. If I do the template as a *.html I have no issues, but if I want to change or add something to the template after is changed to *.php the expansion stop executing.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz (28 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (45.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
php-autocomplete|bsc|0.4.2
vbscript|Dar|1.0.4
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
apacheconf-snippets|eim|1.3.0
json-tools|eri|1.0.2
php-intellisense|fel|2.3.14
vscode-apache|mrm|1.2.0
vscode-edge-devtools|ms-|1.0.7
mssql|ms-|1.8.0
remote-wsl|ms-|0.42.3
debugger-for-edge|msj|1.0.14
php-files|sev|0.0.5

</details>

**Comment by raphievila** [comment]
The links suggested are not the same, I checked them before submitting. Their issue is apparently with IntelliSense. My issue with the Emmet Snippets, IntelliSense works fine.

**Comment by octref** [comment]
When I write the abbreviation I see:

![image](https://user-images.githubusercontent.com/4033249/75695247-a13c8280-5c5e-11ea-80df-b208d64cd4de.png)

If I set `"emmet.triggerExpansionOnTab": true` tab also expands.
