### ISSUE TITLE
Brief weird font rendering in terminal

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#91774]
Issue Type: <b>Bug</b>

Unfortunately I don't have good repro steps for this. I had the terminal open and was doing other things, and saw that the font had changed to look like this:
![Screen Shot 2020-02-28 at 10 17 19 AM](https://user-images.githubusercontent.com/3672607/75575299-c047d400-5a14-11ea-91fc-4049cc6862ac.png)

I thought that something must have happened with settings sync, but looking at the log from there, ` Settings: No changes found during synchronizing settings` was the only message from all of the attempted syncs I had this morning. When I switched focus back from the output panel to the terminal, it rerendered to look normal again:
![Screen Shot 2020-02-28 at 10 17 39 AM](https://user-images.githubusercontent.com/3672607/75575353-c342c480-5a14-11ea-8ce2-fcff9a844019.png)

VS Code version: Code - Insiders 1.43.0-insider (0eebaf9ad23748baca2afc0da425650922bc23de, 2020-02-27T07:32:05.320Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
This is to do with switching monitors with different DPIs, typically happens during/after meetings https://github.com/xtermjs/xterm.js/issues/2137

Can you clarify if you're using webgl renderer?
