### ISSUE TITLE
vscode.workspace.fs.readDirectory, unclear if broken symlink type is correct

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91771]
Setup:

```sh
mkdir /tmp/foo
cd /tmp/foo
touch target
ln -s symlinkWithTarget target
ln -s nonExistingTarget symlinkWithoutTarget
```

Extension code:

```ts
export async function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
        const result = await vscode.workspace.fs.readDirectory(vscode.Uri.file('/tmp/foo'));
        console.log(result[0]);
        console.log(result[1]);
        console.log(result[2]);
    });

    context.subscriptions.push(disposable);
}
```

Run the command, get this output:

![image](https://user-images.githubusercontent.com/323878/75570347-d7ce8f00-5a0b-11ea-8e25-1e8e059ce5b3.png)

From https://github.com/microsoft/vscode/issues/90031#issuecomment-582348477

> readdir will now return symbolic links that are pointing to non existing paths as FileType.SymbolicLink | FileType.Unknown

But the type of the symlink that points to the non-existing path is just `FileType.SymbolicLink`, since Unknown is 0, it's not like I can check `& FileType.Unknown`. But maybe just since it is not `FileType.File` or `FileType.Directory` then this is the expected result?

**Comment by bpasero** [comment]
Yes, I think it is fair to say that `FileType.SymbolicLink | FileType.Unknown` is to be read as `FileType.SymbolicLink` with neither `FileType.File` nor `FileType.Directory`, but moving to Jo to confirm. There is no other field I can use in the API for this purpose.

**Comment by jrieken** [comment]
Yeah - that the current design. We can always add another bit to indicate "more unknown" but you cannot really do anything with that information. Hence the simplicity.
