### ISSUE TITLE
Expose TextEditor identity

### ISSUE THREAD

**Issue by Veetaha** [microsoft/vscode#91788]
Might I ask you to expose the `id` field of `TextEditor` interface for the users?
This is very important and is required in our use case! We would like to lookup the editors by some unique identifier, but this is currently only possible through your private API, which **is not stable**!
We would like this, because we want to implement the correct `inlay hints` (#16221) for our language server, that will be able to work even when there are multiple editors opened for a single source file (https://github.com/rust-analyzer/rust-analyzer/issues/3008).

The format of the `id` should be opaque, you may use any private protocol for it which you want. The only work that is needed to be done to implement this feature, is adding `id: string` property for `TextEditor` in
`vscode.d.ts`:
https://github.com/microsoft/vscode/blob/7f1bde5cb770ea12154d09c7b311e4ad205c6932/src/vs/vscode.d.ts#L1082

![image](https://user-images.githubusercontent.com/36276403/75587267-c5416d80-5a7e-11ea-879d-e4ce1d170a76.png)

The issue where I initially requested this feature: #91782

**Comment by rebornix** [comment]
Object identifier is recommended in this case.
