### ISSUE TITLE
With strictNullChecks enabled, seeing null value returned from WorkspaceConfiguration.get

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#91787]
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

My understanding is that VS Code uses strict null checking.  https://code.visualstudio.com/blogs/2019/05/23/strict-null

We are trying to enable structNullChecks in our extension, and are seeing an unexpected result from WorkspaceConfiguration.get().  It's defined as:

```
get<T>(section: string): T | undefined;
```

So, I would not expect to receive a `null` from it.  However, I'm seeing:

![image](https://user-images.githubusercontent.com/49173979/75583124-e0ca5b00-5a21-11ea-8c3a-35acd7c63c1a.png)

**Comment by mjbvz** [comment]
Strict null checking does not effect runtime behavior, only type checking

**Comment by Colengms** [comment]
Obviously, the issue here is that, if the function may return null, it should be declared with `| null`.  Since it is not declared with `| null`, the expectation is that it cannot return null, or it circumvents proper use of strict null checking in the calling code.

**Comment by Colengms** [comment]
This may be complicated by how we declare the setting.  i.e.:

```
        "C_Cpp.default.compileCommands": {
          "type": [
            "string",
            "null"
          ],
          "default": null,
          "description": "%c_cpp.configuration.default.compileCommands.description%",
          "scope": "resource"
        },
```

This is possibly the source of the `null` I'm seeing returned from WorkspaceConfiguration.get().  If I don't specify a default, I get `""` from get().  The above seems to be the only way to distinguish between unset and `""`.  It also has the unfortunate side-effect of not allowing its value to be edited as a string in settings UI. :/

The proper approach seems to be to avoid assigning a special meaning to `""`, considering it the same as undefined, and not specifing "null" as a type or default in package.json.

**Comment by mjbvz** [comment]
Yes the default value is the cause. Again, TypeScript only add type information to your code; it does not effect how code works at runtime (the fix is to update your types to match the runtime behavior: add `| null`)

**Comment by Colengms** [comment]
I'm not sure why this isn't clear, but, again, the TypeScript types available for _VS Code_ indicate that this API function may return "T | undefined", but should instead indicate "T | undefined | null" if null may be returned from it (regardless of why).  Otherwise, it circumvents (compile-time) strict null checking of calling code, as a null may (at runtime) now propagate through code that does not expect it.  The issue here is that this API function signature is not sufficiently correct for clients that want to use strict null checking.

**Comment by mjbvz** [comment]
What you are describing is the expected behavior, your extension's types are just wrong. Update your code to `.getConfigration<string |  null>`. 

Again, for all VS Code cares, you can say `.getConfiguration<{ '🦄': true }>(...)` in your code but the api will still return whatever value is actually set (including the default!) at runtime. Strict null checking has nothing to do with this
