### ISSUE TITLE
Use aka.ms links in vscode.d.ts?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#91780]
## Problem
`vscode.d.ts` includes a number of links to the VS Code website. Almost all of these are direct links.

<img width="784" alt="Screen Shot 2020-02-28 at 11 54 55 AM" src="https://user-images.githubusercontent.com/12821956/75582766-276b8580-5a21-11ea-8919-bdcea84f3e4e.png">

This is problematic because we sometimes change the structure of the website in ways that make these old links invalid. Extension developers will often have the older `vscode.d.ts` version cached on their system for quite a long time (because they are using an older `@types/vscode` version), and this means the documentation links will not work for them

## Proposal
We should look into making sure that all links in `vscode.d.ts` use aka.ms links. That way we can automatically redirect the links when the structure of the website changes.

**Comment by octref** [comment]
Or we should improve this page and start offering long-lasting links: https://code.visualstudio.com/api/language-extensions/programmatic-language-features, and when those links have to change offer redirects.

**Comment by IllusionMH** [comment]
Will hashes survive redirects in all browsers?

**Comment by mjbvz** [comment]
I believe so. We already use this pretty heavily in our links, for example: https://aka.ms/vscode-remote/containers/getting-started

**Comment by octref** [comment]
> Will hashes survive redirects in all browsers?

Yes

**Comment by octref** [comment]
I can go through them and update them with latest links in /api.

**Comment by mjbvz** [comment]
Closing due to lack of interest / potential maintenance overhead of the change
