### ISSUE TITLE
Terminal selector goes wild if piping to VSCode

### ISSUE THREAD

**Issue by jbsulli** [microsoft/vscode#91790]
Issue Type: <b>Bug</b>

If I pipe command output to VSCode from VSCode's terminal, the terminal selector starts throwing a wild party:

![2020-02-28 14 23 45](https://user-images.githubusercontent.com/3790122/75592212-96070e00-5a36-11ea-8e90-c9d538292f45.gif)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz (8 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|-psn_0_508028|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mjml|att|1.6.0
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
vscode-pull-request-github|Git|0.14.0
vscode-docker|ms-|0.10.0
vscode-typescript-tslint-plugin|ms-|1.2.3
graphviz-interactive-preview|tin|0.0.6
alphabetical-sorter|ue|2.0.1

</details>

**Comment by jbsulli** [comment]
The terminal selector is unusable until you close the output file. Everything goes back to normal afterward.

**Comment by IllusionMH** [comment]
Looks like duplicate of #78539

**Comment by jbsulli** [comment]
@IllusionMH, it does look like this is a dup. Sounds like mine is doing more dancing but it's probably the same root cause. Feel free to close this ticket 🙂
