### ISSUE TITLE
All buttons are missing in Debug view's WATCH section after reloading window

### ISSUE THREAD

**Issue by GeekArthur** [microsoft/vscode#91797]
- VSCode Version: 
```
1.42.1
```
- OS Version: 
```
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A603
```

Steps to Reproduce:

1. Launch any workspace
2. Switch to debug view and confirm `Add Expression`, `Collapse All`, `Remove All Expressions` are exist in WATCH section
3. Reload window
4. Switch to debug view, `Add Expression`, `Collapse All`, `Remove All Expressions` are missing in WATCH section

**Below is the GIF for steps to reproduce:**
![Kapture 2020-02-28 at 23 23 46](https://user-images.githubusercontent.com/15131537/75600779-af817780-5a81-11ea-9e13-124b5fa1208a.gif)

Does this issue occur when all extensions are disabled?: Yes/No
```
Yes
```

**Comment by isidorn** [comment]
Fixed in vscode insiders. This will be fixed in the vscode stable in a couple of days. Thus closing. Thanks
