### ISSUE TITLE
PHP: Problems console not remove php file after closed that are open by FTP  

### ISSUE THREAD

**Issue by jaydeepchauhan7** [microsoft/vscode#91809]
I have a open the remote php  file using vscode and after complete the work i've closed the file. but it can't removed from PROBLEMS console, it's still show the files and errors when i click its reopen. 
it should be gone from PROBLEMS console..

**Comment by roblourens** [comment]
Are you using a PHP extension?

**Comment by jaydeepchauhan7** [comment]
Yes, I'm using PHP Intelephense.
