### ISSUE TITLE
quick fix shortcut keys not work

### ISSUE THREAD

**Issue by fantasy0v0** [microsoft/vscode#91802]
Issue Type: <b>Bug</b>

When there is an error in the file, it can be solved by clicking quick fix with the mouse, but the shortcut key (Ctrl +.) does not work.

VS Code version: Code - OSS 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-17T09:32:31.598Z)
OS version: Linux x64 5.5.6-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 1390)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.66GB (6.35GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.14
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
EditorConfig|Edi|0.14.4
vscode-lombok|Gab|1.0.1
vsliveshare|ms-|1.0.1653
gradle-language|nac|0.2.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.15.0
vscode-manifest-yaml|Piv|1.15.0
vscode-spring-boot|Piv|1.15.0
java|red|0.57.0
vscode-gradle|ric|2.4.13
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-maven|vsc|0.21.0
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by fantasy0v0** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Thank you for reply.
I found the reason. It indicates that the shortcut key is inconsistent with the actual shortcut key.
![Screenshot from 2020-03-05 12-39-51](https://user-images.githubusercontent.com/9549027/75948813-6b5a0100-5edf-11ea-9308-c22ebc693e14.png)


actual shortcut key is shift + alt + .
![Screenshot from 2020-03-05 12-51-47](https://user-images.githubusercontent.com/9549027/75949158-592c9280-5ee0-11ea-8460-dfab895a0493.png)
