### ISSUE TITLE
Unable to debug Java program built with Maven.. @ sign in command line arguments for some reasonk

### ISSUE THREAD

**Issue by dgh1000** [microsoft/vscode#91801]
The issue is that upon launching a debugger, VS Code runs this command line:

~/Sync/projects/music/music-03:cd /Users/Mike/Sync/projects/music/music-03 ; /Library
/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java 
-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:58363 
-Dfile.encoding=UTF-8 @/var/folders/pn/3p41p2fj14d50n707c7x2p4c0000gn
/T/cp_90sfb6m3zinsbhwyvyknqb5hv.argfile ptcs.App 

And I get this error:
Error: Could not find or load main class
@.var.folders.pn.3p41p2fj14d50n707c7x2p4c0000gn.T.cp_90sfb6m3zinsbhwyvyknqb5hv.argfile

I have no idea where the command line came from... as far as I can tell, it's illegal on Mac to use an "at sign" @ in the command line, and java is trying to interpret that as the main class, so something is wrong.

- VSCode Version: 1.42.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Basically create Maven project in VS Code... install all Java extensions.
2. Work with project for several months, making many changes. Not sure what details are significant.
3. Try to launch debugger in maven project, using the default launch.json. I'm not using the "current file" one, using the other one.

    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch) - Current File",
            "request": "launch",
            "mainClass": "${file}"
        },
        {
            "type": "java",
            "name": "Debug (Launch)-App<music-03>",
            "request": "launch",
            "mainClass": "ptcs.App",
            "projectName": "music-03"
        }
    ]

Does this issue occur when all extensions are disabled?: Yes/No

Not sure how to answer this.. the issue is with an extension so I can't duplicate it when I disable all extensions.

**Comment by roblourens** [comment]
Please file this on the repo for the Java language extension: https://github.com/redhat-developer/vscode-java/issues

Thanks!
