### ISSUE TITLE
Font-Family issue

### ISSUE THREAD

**Issue by cce82407** [microsoft/vscode#91815]
Issue Type: <b>Performance Issue</b>

Hello, when I try to change the font-family to cursive or fantasy, it does not change on my website. I am using chrome.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-28-generic

**Comment by alvintangz** [comment]
Did you try saving the file? Please provide more detail if you're not serving it directly from your files.
