### ISSUE TITLE
rev-parse --symbolic-full-name master@{u}: fatal: no upstream configured for branch 'master'

### ISSUE THREAD

**Issue by zmni** [microsoft/vscode#91811]
- VSCode Version: `1.42.1`
- OS Version: `Windows 8.1`

Steps to Reproduce:

1. Create local repo with no upstream.
2. Work on the repo.

Git output:
```
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
```

Does this issue occur when all extensions are disabled?: Yes

Related: https://github.com/arialdomartini/oh-my-git/issues/14

**Comment by roblourens** [comment]
Is this causing a problem? I think an error message in the git log by itself isn't an issue.

**Comment by zmni** [comment]
Actually there is no problem. Just a suggestion to consider, maybe vscode can add some kind of logic to check whether it has upstream or not before running that command? Imho, simple edit and save should not trigger this message, unless the user explicitly performs an action that requires the existence of upstream.

Come to think of it, it looks like the title has to be changed to match what I explained above.

**Comment by joaomoreno** [comment]
This is fine.
