### ISSUE TITLE
Extension API to set a TextDocument's title

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#91810]
Issue Type: <b>Feature Request</b>

For some reason i need to open some files

These file names are not readable, but I can map it to a readable file name

eg.
open the file `/Users/name/Library/Caches/deno/deps/https/cdn.pika.dev/6e869320415a66586bcaf25474be6bf831fe66934ce0e372ecdd58b076e2ce1a` and show the title `https://cdn.pika.dev/fp-ts`

![截屏2020-02-2921 01 09](https://user-images.githubusercontent.com/9758711/75608034-f7160b00-5b36-11ea-917c-6949f96257df.png)

VS Code version: Code - Insiders 1.43.0-insider (0eebaf9ad23748baca2afc0da425650922bc23de, 2020-02-27T07:32:05.320Z)
OS version: Darwin x64 19.2.0

**Comment by roblourens** [comment]
You want to enter a different name for it manually? Can you rename the file?

**Comment by axetroy** [comment]
@roblourens 

The filename is fixed and I cannot change it

tab name defaults to the filename

So, I want an API that can change to the tab's name of a TextDocument which should get better display experience

**Comment by roblourens** [comment]
I think that would be confusing, but I'll pass it on
