### ISSUE TITLE
truncatechars_html

### ISSUE THREAD

**Issue by mauare73** [microsoft/vscode#91812]
Issue Type: <b>Bug</b>

truncatechars_html  message when i use snippet "html"

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2397)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (7.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
vscode-custom-css|be5|3.0.9
vscode-intelephense-client|bme|1.3.11
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
opencv-intellisense|did|0.0.4
jquerysnippets|don|0.0.1
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|2.6.0
vscode-npm-script|eg2|0.3.11
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
pythonsnippets|frh|1.0.2
search-node-modules|jas|1.3.0
react-native-snippet|jun|0.5.6
rn-full-pack|kel|0.7.0
kite|kit|0.109.0
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.25
python|ms-|2020.2.64397
vscode-react-native|msj|0.14.1
color-highlight|nau|2.3.0
vscode-qt-for-python|sea|0.4.2
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.5
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does this problem still happen if you run with all extensions disabled?

**Comment by mauare73** [comment]
Resolved, I unistall the visual studio code end I delete manually al folder
which the program has saved their settings.
I installed again vscode and the problem has disappears.



Il dom 1 mar 2020, 00:29 vscodebot[bot] <notifications@github.com> ha
scritto:

**Comment by gjsjohnmurray** [comment]
Please close this issue.
