### ISSUE TITLE
[Arch Linux]: Toggle Developer Tools crashing

### ISSUE THREAD

**Issue by jchand99** [microsoft/vscode#91824]
- VSCode Version: 1.42.1
- OS Version: Linux x64 5.5.6-arch1-1

Steps to Reproduce:

1. Install vscode using 'visual-studio-code-bin' package from AUR
2. Click Help->Toggle Developer Tools -> watch it crash

Does this issue occur when all extensions are disabled?: Yes/No

Yes, both with running --disable-extensions and when no extensioins are installed.
(This issue exists with both VSCode and VSCode-Insiders for Arch Linux).

Running with no extensions installed (Terminal output):
![image](https://user-images.githubusercontent.com/18605513/75613876-6f150e80-5b00-11ea-959c-1bb912b41e9a.png)

Running with --disable-extensions (Terminal output):
![image](https://user-images.githubusercontent.com/18605513/75613887-8522cf00-5b00-11ea-8ab4-990573950b83.png)

**Comment by deepak1556** [comment]
Thanks for the report, this is an issue with chromium and glibc-2.31. Its fixed in https://github.com/electron/electron/pull/22338, VSCode will get it once we upgrade to the version.
