### ISSUE TITLE
Dataviewer enrichment for List, Dictionary and Row

### ISSUE THREAD

**Issue by Gcsaniz** [microsoft/vscode#91827]
Currently, the Data Viewer support for list (array), dictionary (map), and Row objects in a Pandas data frame is very basic. In fact, dictionary columns are unusable as they all simply display `[object Object]`.

This feature request is to uplift the capability to at least the level supported by other rich python IDE's like Spyder. For complex, pure python objects outside of Pandas, Data Viewer capabilities to "drill down" into the data structures is highly desirable.

A comparison and illustration of the desired functions are communicated through the attached screen shots.

#### Current VS Code Data Viewer Function
![Screen Shot 2020-02-29 at 3 53 44 PM](https://user-images.githubusercontent.com/16419745/75615060-40e9fb80-5b0d-11ea-9f6a-9b65d68a3f9d.png)

#### Requested VS Code Data Viewer Function
![Screen Shot 2020-02-29 at 3 52 59 PM](https://user-images.githubusercontent.com/16419745/75615057-40e9fb80-5b0d-11ea-9366-a443193f993b.png)

#### Requested VS Code Data Viewer Function -- "Drill Down"
![Screen Shot 2020-02-29 at 4 04 43 PM](https://user-images.githubusercontent.com/16419745/75615061-40e9fb80-5b0d-11ea-92f7-9f1a77bb99de.png)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
