### ISSUE TITLE
Allow debug configuration to Ignore exceptions by Type

### ISSUE THREAD

**Issue by JavaScriptDude** [microsoft/vscode#91822]
The break on `Uncaught Exceptions` feature is great but it would be very handy to be able to ignore certain types of exceptions. For instance in Python, system.exit(<code>) will generate a _SystemExit_ exception that I don't want the debugger to pay attention to and simply exit the debugger. I write a lot of Python CLI apps and sys.exit() is the canonical way to send exit codes out to the caller.

One way to solve this is to add a new  _configurations_ entry in _launch.json_  like:` "debugger-ignore-exceptions": ["<exc_identifier_1>"[, "<exc_identifier_2>"...]` where the exception identifier is the final exception class name or dot notation to the exception class type `"<library>.<class>.<exc_type>"` when the language supports such notation in its debugging tokens.

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues

**Comment by JavaScriptDude** [comment]
Shouldn't such a solution be language agnostic? It just happens that I discovered this using Python but I could see this being useful for any language.

**Comment by JavaScriptDude** [comment]
Found a relevant issue: https://github.com/microsoft/vscode-python/issues/5584

**Comment by roblourens** [comment]
Actually no, different languages have different exception models and the number, labels, and behavior of those debug checkboxes are totally up to the language

**Comment by JavaScriptDude** [comment]
Acknowledged. Thanks for the quick response.
