### ISSUE TITLE
Unmapped System Keyboard Shortcuts Conflict with VS Code

### ISSUE THREAD

**Issue by mergesort** [microsoft/vscode#91828]
**- VSCode Version: 1.42.1 and prior versions**
**- OS Version: macOS 10.5.3**

Hi there, I'd like to re-open #62810, with more detail, as demonstrated in the video (attached as a zip because GitHub doesn't support videos). [VS Code Keyboard Shortcuts.mov.zip](https://github.com/microsoft/vscode/files/4271090/VS.Code.Keyboard.Shortcuts.mov.zip)

**Steps to Reproduce:**

In the video you'll see me run VS Code 3 times I've made a video demonstrating how to reproduce the behavior, restarting VS Code after changing the system keyboard shortcuts, and demonstrating different behavior.

1. In the first run through cmd + left and cmd + right are mapped to macOS's Mission Control's "Move left a space" command.

I tap the keyboard shortcut cmd + shift + left, which should take me to the beginning of the line, but nothing occurs. I try cmd + shift + right, which should take me to the end of the line, but that doesn't work either.

The confusing thing is that cmd + shift + left/right isn't even mapped, it's actually stealing that key command even though it's mapped to cmd + left/right, not cmd + shift + left.

2. I change the OS's keyboard shortcut to option + left/right, and restart VS Code so it can be aware of the change, and all of a sudden cmd + shift + left/right begin working.

3. I change the OS's keyboard shortcut back to cmd + left/right, and restart VS Code one last time, and cmd + shift + left/right are once again broken.

I unfortunately don't have much more information to provide, I hope the video is enough, but I'm extremely happy to help debug and answer questions as necessary. This is the only thing stopping me from using VS Code because those key commands are such an engrained part of my text editor workflow. So much so that I spent a week with a remapped macOS shortcut, but couldn't get used to it unfortunately. 😕

Does this issue occur when all extensions are disabled?: Yes/No
Yes, it still occurs when all extensions are disabled.

**Comment by alexdima** [comment]
@mergesort When you configure the OS keyboard to `"cmd+left/right"`, does any of the installed applications on your machine receive the keybindings `"cmd+shift+left/right"`? If VS Code does not receive the keybinding, there is nothing we can do.

---
You can check if we receive the keybindings by opening one of those inputs and seeing if VS Code receives it:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by mergesort** [comment]
@alexdima This is what I confirmed:

When I have macOS's Mission Control OS's shortcut mapped to option + left/right, that text field does indeed receive the key bindings of cmd + shift + left/right.

When I have macOS's Mission Control OS's shortcut mapped to cmd + left/right, that text field does not anymore indeed receive the key bindings of cmd + shift + left/right.

I've attached a video demonstrating how when cmd + left/right are mapped to the operating system's Mission Control functionality, it never allows me to press left or right on the key binding screen, which is why I I suspect that VS Code is conflicting with the OS shortcuts somehow, despite them not being mapped to the same values.

[Key bindings.mov.zip](https://github.com/microsoft/vscode/files/4275634/Key.bindings.mov.zip)

**Comment by alexdima** [comment]
@mergesort I am sorry, but if we don't receive the `keydown` event in the input box, there is no possible code change I can do on our side to improve things.

If you want to pursue this further, you can try opening https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html in Chrome and Safari on the same machine. Does `cmd+shift+left` reach Chrome? Does it reach Safari?

**Comment by mergesort** [comment]
@alexdima This could explain it! It's working fine in Safari, but the events are not being reached in Chrome.

Safari:
<img width="1149" alt="Safari" src="https://user-images.githubusercontent.com/716513/75708584-1922a100-5c8f-11ea-845c-9d55475700a8.png">

Chrome:
<img width="1149" alt="Screen Shot 2020-03-02 at 2 05 58 PM" src="https://user-images.githubusercontent.com/716513/75708508-f2fd0100-5c8e-11ea-8d74-13ddabcf9c0a.png">

I don't know much about web development so this is all a grain of salt, but the Chrome UI (such as the address bar) respond to cmd + shift + left/right, which would lead me to think maybe it's a bug in the rendering engine, and/or they're doing some special override in the UI?

**Comment by alexdima** [comment]
@mergesort This indicates that it is an issue with Chromium. VS Code is built with Electron, which is built with Chromium. Can you please open an issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to it here? You can show how a web app in Safari receives the `keydown` events correctly and one in Chromium does not.
