### ISSUE TITLE
Why compiler output plenty of errors when use vscode and linked libs, but in Terminal compiled normally?

### ISSUE THREAD

**Issue by xiaohaoxiang** [microsoft/vscode#91820]
#include <json/reader.h>
int main(){}

Just this code, when in Terminal I input g++ -g a.cpp -o a -ljsoncpp, it is successfully compiled, and even if I don't add "-ljsoncpp", g++ only output a few lines of link error.

but when I use vscode, add "-ljsoncpp"  to tasks.json, and press F5 to run, the Terminal will output plenty of errors, and the errors are mostly messy code, such as:

In file included from /usr/include/json/value.h:12,
                 from /usr/include/json/reader.h:11,
                 from /home/xhx/Desktop/lane/lane.cpp:4:
./array:49:111: Error：expected declaration before ‘}’ token
   49 |                           t                                                          %                             �             H8      H8                                     �              @       @      h                             �             hD      hD      �                              �             8E

and the errors are so many that only the last hundreds lines of errors can be seen.
I have tried a lot, such as reinstall vscode. It's seem like when I use vscode, the linker can't work properly.
I am very very sad.  T_T

**Comment by xiaohaoxiang** [comment]
Apologize for my poor English.

**Comment by xiaohaoxiang** [comment]
vscode work properly on my Ubuntu, but this is on Manjaro 19.0, can this be the final reason?

**Comment by xiaohaoxiang** [comment]
And I can't link any library with vscode, anybody know what maybe the reason?

**Comment by xiaohaoxiang** [comment]
I have solve this problem. It is because the auto-make tasks.json, all we need to do is delete the item option:
            "options": {
                "cwd": "/usr/bin"
            },
delete it ,then vscode will work properly.
oh yeah!

**Comment by xiaohaoxiang** [comment]
But I still don't know why. This FXXK problem cost me more than 5 hours.

**Comment by xiaohaoxiang** [comment]
I know why is it. Because when cwd is /usr/bin, Terminal do not have root, so if you are in /usr/bin or other root only path, and use g++ to compile, it will fail. but sudo g++ will be ok. Then you can set the root path so solve this problem.

**Comment by roblourens** [comment]
So did you solve it? If not please file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
