### ISSUE TITLE
Several problems encountered on expanding Workbench Parts

### ISSUE THREAD

**Issue by Luncher** [Microsoft/vscode#9182]
- VSCode Version: 1.4
- OS Version: fedora21

I've clone  vscode repository, try to modify some code, ask a few questions,
1, if I use a third-party npm module, how can I import it?
2, my javascript code uses commonJs format, compiled code when prompted Cannot find name '__dirname'. , how do I deal with it?

![screenshot from 2016-07-13 15 56 50](https://cloud.githubusercontent.com/assets/5138977/16795910/7c6c290e-48a5-11e6-9e79-ac1413ec96dd.png)

thanks

**Comment by weinand** [comment]
@Luncher just copy how we use npm modules: add dependency to package.son, run `./script/npm.sh install`and then `gulp watch`.

**Comment by Luncher** [comment]
thank you @weinand
