### ISSUE TITLE
Terminal Path showing corrupted path

### ISSUE THREAD

**Issue by sunilsk1** [microsoft/vscode#91836]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

In the terminal the path shows a corrupted name. I see this :: 
```

%{[white]%} %{[cyan]%}%D %D{%L:%M:%S}%{[white]%}%{%} %{[green]%}%n%{%}@%{[green]%}%m:%{[magenta]%}%~%{%}$ 
%{[white]%} %{[cyan]%}%D %D{%L:%M:%S}%{[white]%}%{%} %{[green]%}%n%{%}@%{[green]%}%m:%{[magenta]%}%~%{%}$ 
%{[white]%} %{[cyan]%}%D %D{%L:%M:%S}%{[white]%}%{%} %{[green]%}%n%{%}@%{[green]%}%m:%{[magenta]%}%~%{%}$ top |head -2
Processes: 403 total, 2 running, 401 sleeping, 2172 threads 
2020/02/29 19:03:32
```

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.6.0
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|3.20.0
code-runner|for|0.9.16
vscode-language-babel|mgm|0.0.25
vscode-docker|ms-|0.10.0
LiveServer|rit|5.6.1

(2 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/10577105/75618696-d9d94080-5b26-11ea-927f-0abc5ce933c4.png)

**Comment by Tyriar** [comment]
It looks like you've installed some helper that modifies `$PS1`, but your shell (bash) doesn't understand it. This isn't a VS Code problem.
