### ISSUE TITLE
Breadcrumbs don't working on Java Library class !

### ISSUE THREAD

**Issue by adamvscele** [microsoft/vscode#91839]
Breadcrumbs don't show on Java Library class ,just show on my custom class!
Library class:
![image](https://user-images.githubusercontent.com/6405610/75619702-6f71e000-5bba-11ea-9024-6c9e2fda7327.png)
Custom class:
![image](https://user-images.githubusercontent.com/6405610/75619753-da231b80-5bba-11ea-9642-457054b8fbf4.png)

**Comment by gjsjohnmurray** [comment]
My guess is this is similar to #62290. Is the support for Java code coming from an extension? If yes, maybe it serves library classes from a virtual filesystem by implementing FileSystemProvider

**Comment by adamvscele** [comment]
Yes,the code is coming from Java extension？Might you consider adding the function feature?

**Comment by roblourens** [comment]
I think so, thanks @gjsjohnmurray!
