### ISSUE TITLE
Blank Terminal (possible LTSC issue)

### ISSUE THREAD

**Issue by deciacco** [microsoft/vscode#91831]
Issue Type: <b>Bug</b>

Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763.1039 LTSC 1809
Powershell Version: 5.1.17763.1007

When I click on New Terminal, the terminal opens up at the bottom of the VScode window, but I expect to see the powershell prompt with cursor, instead it remains blank until I hit enter or start typing a command. If I scroll up on the termnial window the copyright is there but it remains blank until I type something or hit enter. 

I've tested this on two computers, both running the same version of Windows 10 and they both exhibit the same behavior. My home computer, which doesn't not have LTSC, works as expected.

Same thing happens with powershell core 6.2.4. 

If I change either powershell to "use legacy console", it works as expected.

If I use Command Prompt as the default shell it works as expected.

No errors in Dev Tools Console when I click on "New Terminal".

I'm happy to provide additional info.

Thank you.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx   (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|29.94GB (25.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
prettier-vscode|esb|3.20.0
vscode-firefox-debug|fir|2.7.0
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
vscode-remote-extensionpack|ms-|0.19.0
material-icon-theme|PKi|3.9.3
LiveServer|rit|5.6.1
vscode-autohotkey|sle|0.2.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
What Windows version is the home computer where you don't see the problem?

I think https://github.com/microsoft/vscode/issues/45693#issuecomment-456937675 may be relevant.

**Comment by gjsjohnmurray** [comment]
Also #90945

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
