### ISSUE TITLE
vscode does not render math symbols using ipyton display, Math, latex

### ISSUE THREAD

**Issue by caedmon-kitty** [microsoft/vscode#91834]
In both **jupyter** and the **atom** text editor this python code displays a nice math equation with the square root sign over the (a^2 + b^2) and the ^2 correctly rendered as superscripts.

from IPython.display import display, Math, Latex
display(Math(r'\sqrt{a^2 + b^2}'))

In vscode this is what I get: 

$\displaystyle \sqrt{a^2 + b^2}$

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.21-100.fc30.x86_64

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
