### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Aselor** [microsoft/vscode#91848]
Issue Type: <b>Bug</b>

When the terminal is opened, flickering occurs and indents increase. You can see how in the screenshot.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763
![image](https://user-images.githubusercontent.com/61655112/75626474-88858b80-5bd0-11ea-8c09-066318980681.png)

**Comment by IllusionMH** [comment]
Looks like you are using pretty old version 1.40. Could you update to latest stable 1.42 or better insiders 1.43 and check if it is still reproducible.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
