### ISSUE TITLE
Manually change the order of the folders and files that are listed in VSCode Explorer

### ISSUE THREAD

**Issue by hegedis-andor** [microsoft/vscode#91843]
As a user i **would like to sort my folder and files order in the explorer manually** within it's parent folder, so i can decide how folders and files follow each other.

Currently it is sorted by alphanumeric, which does not follow the logicality of the project. **It would make much easier to find files and understand project by looking on the logically sorted order.** 

Suggested implementation: drag + drop, keycombination + mouse scroll wheel.

**Comment by gjsjohnmurray** [comment]
You can already set up a multiroot workspace to give you control of the sequence of your first-level folders. That's not everything you asked for, but maybe some help?

**Comment by isidorn** [comment]
@gjsjohnmurray great suggestion. Multi root workspaces sounds like the way to go here.
Thus closing this issue as we do not plan to add additional support for this scenario.

**Comment by hegedis-andor** [comment]
With multi root workspaces how can one sort the files in the folder? To have all the similar logical files in different folder in the same order.

**Comment by hegedis-andor** [comment]
![image](https://user-images.githubusercontent.com/22738075/79243862-773dc900-7e76-11ea-953c-d51e8f61d17d.png)

I still wish this feature to be added. It would really make finding files easier, especially when there are a lot in the same folder. It could also follow the logical / user flow.
