### ISSUE TITLE
Backup folder read-only inside project folder!

### ISSUE THREAD

**Issue by PresKhaled** [microsoft/vscode#91840]
Hello
VS Code makes a backup folder inside current project folder, this backup folder is read-only.
when need an old code i get it from backup read-only (because filenames the same)
therefore i don't need to open .zip, .rar  and open file with the same name.

**Comment by gjsjohnmurray** [comment]
Is this a bug report or a suggestion for an enhancement? If a bug report please provide missing details such as version, platform, and whether it happens with all extensions disabled.

**Comment by PresKhaled** [comment]
> Is this a bug report or a suggestion for an enhancement? If a bug report please provide missing details such as version, platform, and whether it happens with all extensions disabled.

It's a feature request.

**Comment by roblourens** [comment]
You may want to check out source control systems like Git, sounds like it may help
