### ISSUE TITLE
VS-Code hangs after start a task

### ISSUE THREAD

**Issue by JamHamburg** [microsoft/vscode#91841]
Issue Type: <b>Bug</b>

CenttOS7
code  installed: code.x86_64 0:1.42.1-1581433057.el7

Description:
I try to start a "BuildTtask" form Menu:
  Menu Terminal
  use "Build Task"  Menu Item
  select "prepare dir"  (one of my tasks)
  My Terminal console outputs:
> Executing task: mkdir -p build/debug build/release install/debug install/release <

and nothing happend, the Task simply does not do any actions.
There is no further output

## tasks.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "prepare dir",
            "type": "shell",
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "command": "mkdir -p build/debug build/release install/debug install/release",
            "args": [],
            "group": "build"
        },
        {
            "label": "cmake3-debug",
            "type": "process",
            "options": {
                "cwd": "build/debug"
            },
            "command": "cmake3",
            "args": [
                "-DCMAKE_INSTALL_PREFIX=${workspaceFolder}/install/debug",
                "-DCMAKE_BUILD_TYPE=debug",
                "${workspaceFolder}/repo"
            ],
            "group": "build",
            "dependsOn": "prepare dir",
            "problemMatcher": []
        },
        {
            "label": "make-debug",
            "type": "process",
            "options": {
                "cwd": "build/debug"
            },
            "dependsOn": "cmake3-debug",
            "command": "make",
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        },
        {
            "label": "install-debug",
            "type": "process",
            "options": {
                "cwd": "build/debug"
            },
            "dependsOn": "make-debug",
            "command": "make",
            "args": [
                "install"
            ],
            "group": "build"
        },
        {
            "label": "cmake3-release",
            "type": "process",
            "options": {
                "cwd": "build/release"
            },
            "command": "cmake3",
            "args": [
                "-DCMAKE_INSTALL_PREFIX=${workspaceFolder}/install/debug",
                "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
                "${workspaceFolder}/repo"
            ],
            "group": "build",
            "dependsOn": "prepare dir"
        },
        {
            "label": "make-release",
            "type": "process",
            "options": {
                "cwd": "build/release"
            },
            "dependsOn": "cmake3-release",
            "command": "make",
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        },
        {
            "label": "install-release",
            "type": "process",
            "options": {
                "cwd": "build/release"
            },
            "dependsOn": "make-release",
            "command": "make",
            "args": [
                "install"
            ],
            "group": "build"
        },
        {
            "label": "clean all",
            "type": "shell",
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "command": "rm -rf build/* install/*",
            "args": []
        },
        {
            "label": "package",
            "type": "process",
            "options": {
                "cwd": "build/release"
            },
            "dependsOn": "make-release",
            "command": "make",
            "args": [
                "package"
            ],
            "group": "build",
            "problemMatcher": []
        },
        {
            "label": "runt test",
            "type": "process",
            "options": {
                "cwd": "build/debug"
            },
            "dependsOn": "make-debug",
            "command": "make",
            "args": [
                "test"
            ],
            "group": "test"
        }
    ]
}
```

## system details:
ps -ef | fgrep code  come up with:

develop+   5137   5089  4 08:58 ?        00:00:23 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --field-trial-handle=5649571921935166394,9707460531161987047,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --lang=en-US --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-path=/usr/share/code/resources/app --node-integration --webview-tag --no-sandbox --no-zygote --background-color=#ffffff --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=4223453478068586205 --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
develop+   5165   5137  0 08:58 ?        00:00:02 /usr/share/code/code --inspect-port=0 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost
develop+   5180   5137  0 08:58 ?        00:00:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=watcherService
develop+   5194   5137  0 08:58 ?        00:00:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=searchService
develop+   5203   5165  0 08:58 ?        00:00:00 /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5165
develop+   5204   5165  0 08:58 ?        00:00:01 /usr/share/code/code /home/developer/.vscode/extensions/simonsiefke.prettier-vscode-1.1.18/packages/server/dist/serverMain.js --node-ipc --clientProcessId=5165
develop+   5241   5089  0 08:58 ?        00:00:01 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --field-trial-handle=5649571921935166394,9707460531161987047,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --disable-gpu-compositing --lang=en-US --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-path=/usr/share/code/resources/app --node-integration --no-sandbox --no-zygote --background-color=#ffffff --disable-blink-features=Auxclick --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=739109720448388954 --renderer-client-id=6 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
develop+   5316   5089  2 08:59 ?        00:00:09 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --field-trial-handle=5649571921935166394,9707460531161987047,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --disable-gpu-compositing --lang=en-US --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-path=/usr/share/code/resources/app --node-integration --no-sandbox --no-zygote --background-color=#f3f3f3 --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=16177622627044515124 --renderer-client-id=8 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
develop+   5552   3635  0 09:06 pts/0    00:00:00 grep -F --color=auto code

  

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 3.10.0-1062.9.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|5.31GB (2.26GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
kivy-vscode|Bat|0.5.3
doxdocgen|csc|0.5.2
python|ms-|2020.2.64397
cmake-tools|ms-|1.3.1
cpptools|ms-|0.26.3
prettier-vscode|Sim|1.1.18
cmake|twx|0.0.17

</details>

**Comment by alexr00** [comment]
Can you share all your settings.json?

**Comment by JamHamburg** [comment]
[settings.json.txt](https://github.com/microsoft/vscode/files/4288915/settings.json.txt)

Thie problem of not starting task also happend if I use a complete new directory,
start code .   in the directory
create the default echo task and try to start the task!
Just showing that the task is starteing but no 'hello'

thanks
JaM

**Comment by alexr00** [comment]
@JamHamburg is that your full user settings, or just your folder settings? (if it's the folder settings can you share your user settings too?)

**Comment by JamHamburg** [comment]
I did not know that i have some additional config directory.  Anyway, I found the stuff and I got a log for the error:
[2020-03-05 18:58:50.490] [renderer1] [error] A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'
Nevertheless I Add my code directory ( a subset, I removed all cached data)
[Code.tar.gz](https://github.com/microsoft/vscode/files/4294408/Code.tar.gz)

I hope this clarifies the problem.

**Comment by JamHamburg** [comment]
Seems, I got it!
After checking the error.log and seraching for the proc/1/environ error 
I change my user.config:
"terminal.integrated.inheritEnv": true
switching from false to true.
And now I get the echo Hello task running.

Thanks for the help!
JaM
