### ISSUE TITLE
[semantic][typescript] Class fields assigned by constructor parameters are tokenized as parameters throughout the class

### ISSUE THREAD

**Issue by dannymcgee** [microsoft/vscode#91847]
**VSCode Version**: 1.43.0-insider
**OS Version**: Windows 10

**Minimal repro**:
```typescript
class Foo {
    private bar: string;

    constructor(private baz: string) {}

    private compareBarVsBaz(): void {
        const bar = this.bar;
        const baz = this.baz;
    }
}
```

**Expected behavior**:
`bar` and `baz` receive the same semantic token type outside of the constructor, since they are both class fields.

**Actual behavior**:
`bar` receives "property" token type, while `baz` receives "parameter".

**Does this issue occur when all extensions are disabled?**:
Yes

**Comment by aeschli** [comment]
fixed in 1.43.1
