### ISSUE TITLE
Display More Progress in "Git Clone"

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/vscode#91845]
VSCode October 2019 update introduced the progress bar when cloning a repository from inside VSCode. That's nice. However, when cloning a big repository (like the vscode repo itself...) this progress bar may hang and seems to not advance. Git, for a long time, displays more information about the progress:
```
Cloning into 'vscode'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (28/28), done.
Receiving objects:   5% (42568/851351), 8.68 MiB | 1.79 MiB/s
```
That would be nice if VSCode would display this information in the "Cloning" message.

**Comment by joaomoreno** [comment]
You can always open `Git: Show Git Output`.
