### ISSUE TITLE
Ability to search installed extension when offline

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/vscode#91857]
If this is an existing feature, then the discoverability could be improved.

**Comment by sandy081** [comment]
You can open installed extensions view as below

<img width="784" alt="Screenshot 2020-03-02 at 10 31 42" src="https://user-images.githubusercontent.com/10746682/75663457-203ab680-5c71-11ea-8394-0ed10063fc9c.png">

and filter

![image](https://user-images.githubusercontent.com/10746682/75663484-2b8de200-5c71-11ea-8441-eca1132b12ef.png)
