### ISSUE TITLE
Enlarged window on second screen overflows screen boundaries

### ISSUE THREAD

**Issue by jpbourgeon** [microsoft/vscode#91856]
Issue Type: <b>Bug</b>

On my system, when I display VSCode in enlarged mode on the second screen, the app overflows the screen boundaries.
The problem doesn't happen in fullscreen mode.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.92GB free)|
|Process Argv|--file-uri file:///c%3A/Users/bourgeonjp/Documents/Dropbox/Projets/%40freelance/2020_bourgeon-jp-net/jp%40bourgeon-jp-net.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.1
toggle-excluded-files|eam|1.7.0
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
vscode-language-pack-fr|MS-|1.42.2
markdown-preview-enhanced|shd|0.5.2
vscode-icons|vsc|10.0.0
vscode-import-cost|wix|2.12.0
material-theme|zhu|3.2.3

</details>

**Comment by IllusionMH** [comment]
Most likely duplicate of #85592 or #88653 but hard to say without screenshots.
Please check mentioned issues, provide more info in existing issue and close this one if it's a duplicate.

**Comment by jpbourgeon** [comment]
It is a duplicate of #85592
Thank you for pointing this out
