### ISSUE TITLE
selectionRangeProvider on inner array always returns outer array

### ISSUE THREAD

**Issue by fvclaus** [microsoft/vscode#91852]
Issue Type: <b>Bug</b>

Steps to Reproduce:

Execute `selectionRangeProvider` in an JSON array that is enclosed in another array. It will return the outer array. This behavior changed from 1.41.0 to 1.42.0. In 1.41.0 the inner array was returned.

![enclosing_array](https://user-images.githubusercontent.com/2384738/75629815-81b54380-5be5-11ea-8237-03090c09c9ef.png)

If the selectionrange provider is executed at the current position, it will return the top array (first and last line). In previous version, it returned the array from line 4-7. 

I have created a repository with a single that demonstrates this behavior:

https://github.com/fvclaus/vscode-selectionrangeprovider/blob/master/src/test/suite/searchEnclosingArray.test.ts

`npm run test` will execute the test. The vscode version can be changed in `src/test/runTests.ts`

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-74-generic snap

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (16 x 2282)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|23.55GB (4.92GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.16
vscode-emacs-improved|rkw|1.1.0

</details>

**Comment by aeschli** [comment]
When I try your sample with the `Expand Selection` command, it seems to work correctly. 
![expand2](https://user-images.githubusercontent.com/6461412/75681077-293c7f80-5c93-11ea-90a5-3dda5a1ed4f1.gif)

I tried with your test, but it various issues" document is empty when breaking at the assert, position as described in the issue.

**Comment by fvclaus** [comment]
Expand to selection works, I know.  It must do something different.

Yes, the position in the document was wrong. Maybe I changed it by accident before pushing. Anyway, I fixed the position. If you pull again, you will see the correct position.

I think those issues you are referring to are linter issues? If so, they don't matter, but I fixed them anyway.

Here is a screenshot of an active debug session:

![foo_array](https://user-images.githubusercontent.com/2384738/75682827-59d1e880-5c96-11ea-9714-7ff9205ddf83.png)

And here is the value of `selectionRanges`:

```
[
  {
    "range": [
      {
        "line": 0,
        "character": 0
      },
      {
        "line": 11,
        "character": 1
      }
    ]
  }
]
```

**Comment by aeschli** [comment]
It seems that the positions don't make it back to the JSON language server:

I add the following to the beginning of the test:
```
        vscode.languages.registerSelectionRangeProvider('json', {
            provideSelectionRanges(d, p) {
                console.log(JSON.stringify(p));
                return null;
            }
        });
```

When the test is run, the following is printed:
`[{"line":null,"character":null}]`

**Comment by jrieken** [comment]
I can reproduce with our api command tests

<img width="750" alt="Screenshot 2020-03-02 at 17 37 11" src="https://user-images.githubusercontent.com/1794099/75696923-a0324200-5cac-11ea-8141-45ba3d50cb79.png">

**Comment by fvclaus** [comment]
I just tried it with 1.44-insider and my tests work again. Thanks!
