### ISSUE TITLE
Some Keyboard ShortCuts Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by SkyRiderMike** [microsoft/vscode#91866]
- VSCode Version:  1.42.1
- OS Version: Ubuntu 18.04

When i installed the version 1.42.1, some of important keyboard shortcuts doesn't work on Ubuntu 18.04.

Steps to Reproduce:

1. The keyboard shortcut settings look like this:
![image](https://user-images.githubusercontent.com/7625094/75639100-37c27100-5c6a-11ea-8785-e1b5d9b9b694.png)

However When i type Ctrl + Shift + E, it doesn't shows the explorer window. Also Ctrl+Shift+F doesn't works.

**Comment by roblourens** [comment]
Please see whether any of the tips here help: https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexdima** [comment]
What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
