### ISSUE TITLE
Unable to add Debug Watch items during screenshare session

### ISSUE THREAD

**Issue by madarp** [microsoft/vscode#91868]
Issue Type: <b>Bug</b>

1. Create a running python debug session (any code, paused at a breakpoint).  Note that you may add Watch expressions with the "+" button that appears when mouse hovers on Watch menu bar.
2. Jump into a Zoom video meeting and share the VSCode application window. 
3. The Debug Watch menu bar icons do not show up after sharing the window to the Zoom meeting.  There is no "+" mouse-activated button available.
4. Unshare the VSCode application window from the Zoom video meeting -- Debug Watch icons reappear and are functional.

Not sure if this is a Zoom thing, or a VSCode thing.  But it's frustrating when doing a live demo.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 3|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|-psn_0_11332302|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.14.0
nbpreviewer|jit|1.2.2
vscode-peacock|joh|3.5.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.10.0
python|ms-|2020.2.64397
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
cpptools|ms-|0.26.3
vsliveshare|ms-|1.0.1653
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
vscode-gitignore-generator|pio|1.0.1
LiveServer|rit|5.6.1
vscode-hexdump|sle|1.7.2
vscode-arduino|vsc|0.2.29

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Do the actions show up in other views? Like above the file explorer? @isidorn not sure if related to https://github.com/microsoft/vscode/issues/91797 somehow

Or if you click in that spot, does it trigger the action anyway?

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by madarp** [comment]
@roblourens @isidorn  I just tried flipping the view to file explorer and then back to debug, and it worked! The mouse actions are appearing again in both views.  But if I stop the screenshare and restart it, they are gone again until I switch the view.  I have not yet tried this with the insiders edition.
