### ISSUE TITLE
Screen Glitch

### ISSUE THREAD

**Issue by Nibroc-Fitz** [microsoft/vscode#91864]
- VSCode Version:  1.42
- OS Version: Windows 1909

Steps to Reproduce:

1. Open VS CODE
2. Screen glitch after sitting idle for a little while.

Does this issue occur when all extensions are disabled?: N/A

![image](https://user-images.githubusercontent.com/61170112/75636098-df4b8f00-5be9-11ea-89d8-5c9a53e2f43b.png)

**Comment by gjsjohnmurray** [comment]
Does this reproduce if you launch with the --disable-gpu command line argument?

**Comment by Nibroc-Fitz** [comment]
Not sure how to launch like that. I don't have any more info to provide.

**Comment by gjsjohnmurray** [comment]
When you currently start VSCode you're running an executable called code.exe (perhaps via a desktop shortcut).

Instead of running this:

`code.exe`

run this:

`code.exe --disable-gpu`

**Comment by jpaolinelli** [comment]
I am also experiencing this problem, it started recently and only on my PC. I tried --disable-gpu as the previous poster suggested and so far no glitch like the screenshot shown above. In my case it happened almost immediately, I didn't have to leave it idle, moving the window or typing would make it go away.

**Comment by Nibroc-Fitz** [comment]
Turning off image sharpening in my Nvidia control panel fixed this issue.

**Comment by roblourens** [comment]
Thank you for following up!
