### ISSUE TITLE
support for reuse window but new tab

### ISSUE THREAD

**Issue by magicdawn** [microsoft/vscode#91876]
Window: Open folders in new window current support this
![image](https://user-images.githubusercontent.com/4067115/75649242-7d446580-5c8d-11ea-9982-54aaeb8f69f3.png)

Window: 

## My config
```js
{
  "window.zoomLevel": 0,
   "window.nativeTabs": true,
  "window.titleBarStyle": "native",
}
```

And I always use 1 window & many tabs like
![image](https://user-images.githubusercontent.com/4067115/75649343-c8f70f00-5c8d-11ea-8670-c32dee46716b.png)

But when I use the command line `code .`
if I set `Window: Open folders in new window` to `on`, it will open a seperate new `Window`, not a window Tab
if I set `Window: Open folders in new window` to `off`, it will open in current window, & the previous windows is replaced.

What I want is: reuse current system window, but create a new native tab.
After search, I believe it's not current supported. so I'm requesting this.

**Comment by magicdawn** [comment]
@vscodebot it's not the same.

**Comment by bpasero** [comment]
This is a macOS configuration:

![image](https://user-images.githubusercontent.com/900690/75670005-431e9800-5c7c-11ea-99e5-3d3258dd26e4.png)

**Comment by magicdawn** [comment]
![image](https://user-images.githubusercontent.com/4067115/75670759-53ecff00-5cb8-11ea-9bfd-bff97cdc7242.png)

Hi, my current configuration is already `Always`. ("总是" in chinese)

**Comment by bpasero** [comment]
Yes that should work. I cannot reproduce your issue, for me typing "code ." with an existing window open, shows a new native tab given I have macOS configured to always open windows as tabs.

**Comment by magicdawn** [comment]
I'm using macos catalina 10.15.3 (19D76)

vscode
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

I still have this problem 😂

**Comment by bpasero** [comment]
I think I cannot help further, please engage with the OS vendor.
