### ISSUE TITLE
Lower resolution: unable to set breakpoints

### ISSUE THREAD

**Issue by JurgenStillaert** [microsoft/vscode#91878]
Issue Type: <b>Bug</b>

My colleague who needs to work in a higher resolution and bigger fonts cannot see the edge on the editor pane where one can click to place breakpoints.
The tabs seems to be under the activity bar. But also when we hide the activity bar and not maximizing the window, the left tab and left part of the editor is also not fully visible.

His screen resolution is 1024*768.

![D31708E1](https://user-images.githubusercontent.com/6113713/75655927-2b86e580-5c63-11ea-8277-7ab8ebcf354c.PNG)
![5FC6D460](https://user-images.githubusercontent.com/6113713/75656152-a0f2b600-5c63-11ea-92f0-665da409f5f3.PNG)

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

**Comment by weinand** [comment]
@JurgenStillaert please confirm that I understand this correctly: the issue is not about "setting breakpoints". The problem is that not all editor tabs are visible if you have more than fit into the window, correct?

In this case you can use horizontal (mouse) scrolling to reach the non-visible editor tabs.

**Comment by JurgenStillaert** [comment]
@weinand Just the vertical line where you click to set a breakpoint is not visible or clickable on his screen. There is no scroll bar. As you can see on the first screenshots - without activity bar -, the first tab is only visible less than half (nent.ts), the line numbers are right after the window border.
On the second screenshot - with activity bar -, the tab is more visible (etail.component.ts) and the linenumbers are glued to the activity bar. There should be some space to click for setting and viewing breakpoints.

**Comment by weinand** [comment]
There are two independent issues:
- the half-visible tab is a consequence of too many open tabs and a small screen size. You can scroll the horizontal tab region by scrolling horizontally in that region.
- the missing vertical area where you set breakpoints (so called "gutter") only exists, if you can  actually set breakpoints in the underlying file. What type of file is visible in that screen shot?

**Comment by JurgenStillaert** [comment]
Ok, the first one is a non-issue.

The second one: it's a typescript file. Same setup as the last pc, on which it is working.

**Comment by JurgenStillaert** [comment]
![B6765B34](https://user-images.githubusercontent.com/6113713/75684030-66574080-5c98-11ea-8c8f-acf80e7f5b5b.PNG)

When setting a breakpoint with shortcuts, there is a breakpoint icon in the text, but not in the gutter.

**Comment by weinand** [comment]
@isidorn it the gutter hidden if there is not enough space?

**Comment by isidorn** [comment]
No the gutter does not get gidden.
@JurgenStillaert can you repro with vscode insiders
https://code.visualstudio.com/insiders/

**Comment by JurgenStillaert** [comment]
We've uninstalled VS Code, removed all extensions and settings for the user, re-installed and now the gutter is visible again. We will try to install the extensions again and see if it disappears again.

**Comment by isidorn** [comment]
@JurgenStillaert it might be one of the extensions that disables the gutter.
Make sure that you do not have in your setting file 
`"editor.glyphMargin": false`

If you find reproducable steps let us know and we can reopen.
If it is one of the extension please file the issue against that extension. Thank you
