### ISSUE TITLE
Unable to see settings sync on option in the "gear icon menu"

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#91875]
Issue Type: <b>Bug</b>

The release notes for  V1.43.0-insiders show the option however, I am still unable to see the settings sync option in the Gear icon menu.

is there some setting or flag I need to enable in order to check/use this feature?

VS Code version: Code - Insiders 1.43.0-insider (17c6d123d212f90300429ecad3fc96fcec6e338f, 2020-02-28T12:46:02.355Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-88-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (2.45GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.7.0
vscode-docker|ms-|0.10.0
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
js-debug-companion|ms-|0.0.4
debugger-for-chrome|msj|4.12.6
ng-template|Ang|0.900.14
atlascode|atl|2.4.2
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
cloudcode|goo|1.1.2
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.1.0
powershell|ms-|2020.1.0
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|1.9.2
vscode-react-native|msj|0.14.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.7.2
vscodeintellicode|Vis|1.2.5

</details>

**Comment by sandy081** [comment]
> The release notes for V1.43.0-insiders show the option however, I am still unable to see the settings sync option in the Gear icon menu.

Which release notes do you mean and where did you find it?

**Comment by sanket-bhalerao** [comment]
i am talking about the insiders build release notes:
menu -> help -> release notes
following is the image i am talking about.
this is under the preview features.
![image](https://user-images.githubusercontent.com/9264813/75663814-76baeb80-5c97-11ea-9af4-0254c6d5fac9.png)

why is this issue closed?

**Comment by sanket-bhalerao** [comment]
> 
> 
> Settings Sync is not yet enabled in insiders. We are planning to enable it in 1.44.0-insiders.
> 
> > The release notes for V1.43.0-insiders show the option however, I am still unable to see the settings sync option in the Gear icon menu.
> 
> Which release notes do you mean and where did you find it?

if so then what is this?
Preview features
Preview features are not ready for release but are functional enough to use. We welcome your early feedback while they are under development.

Settings Sync
We have been working the last couple of months to support synchronizing VS Code preferences (settings) across machines (popular feature request #2743). In this milestone, we are happy to announce that this feature is ready for preview in our Insiders release. You can now have your preferences synchronized in all your VS Code installs across all your machines. You can also bootstrap VS Code with your personal preferences on a fresh machine with minimal effort.

Bootstrap VS Code using Settings Sync

**Comment by sandy081** [comment]
@sanket-bhalerao As mentioned in other issue

We are preparing release notes for next major release (1.44.0) and we are making Settings Sync ready for preview from next insiders (1.44.0-insiders). I was completely forgotten that current insiders picks up this release notes. I will update the release notes and mention from which insiders it will be available from. 

Sorry for the confusion.
