### ISSUE TITLE
when i drop a file to vscode,editor is unable to work.

### ISSUE THREAD

**Issue by boomyao** [Microsoft/vscode#9187]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

**Comment by bpasero** [comment]
@boomyao can you provide more details? are you dropping a folder maybe?

**Comment by wUFr** [comment]
probably folder. Tried this with file and no problem, but folder will result in infinite loading in top bar, even if it contains just 4 small PHP files :)

1) shouldnt be able to drag folder
or better solution
2) ask if you want to open all files in folder; all files in folder and sub folders or do nothing :)

**Comment by bpasero** [comment]
We fixed this for insiders: dropping a folder opens it in VS Code as it used to before 1.3.
