### ISSUE TITLE
In some situations, the orca is muted when the focus is moved to the file explorer

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#91884]
Version: 1.43.0-insider
Commit: d1c48c103cabc6e729f59787c0b9c86fb3d39e73
Date: 2020-02-29T01:05:21.867Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.6-arch1-1
Steps to Reproduce:

1. Make sure that orca is running
2. Press ctrl+shift+e to activate the file explorer. Note that orca announces the explorer as expected.
3. Press shift+tab.
4. Press tab 5 times. The focus is moved to the explorer but orca stays mute.
5. Press tab and shift+tab. The focus is moved to the explorer and now orca announces the explorer as expected.

@isidorn @webczat Would it be possible to confirm?

**Comment by isidorn** [comment]
If I follow this extect steps on my Ubuntu 18 in step 4, if I press tab 5 times focus is moved to the Explorer and orca properly announces "Files explorer, use the navigation keys to navigate tree". Which I think is expected.

Let's see if other users also reproduce.

**Comment by webczat** [comment]
yeah, not confirmed on insiders.

**Comment by jvesouza** [comment]
Curiously, I can't reproduce the problem anymore. Before reporting the 
problem I did several tests to confirm the existence of it and all tests 
were positive.

I'm sorry for the noise!

**Comment by isidorn** [comment]
No problem. Closing and will reopen if you get steps and we can consistently reproduce this.
