### ISSUE TITLE
Empty lines added when viewing on a different system

### ISSUE THREAD

**Issue by bfiessinger** [microsoft/vscode#91889]
![empty-lines](https://user-images.githubusercontent.com/41627893/75676204-1624b200-5c89-11ea-998d-e905d23cc795.PNG)

Steps to reproduce (does not apply to all files):
1. Created a PHP File on a Linux Server (everything looks good)
2. Opened it up on another PC (vscode added empty lines)
3. Save it (empty lines are now saved)

If I download it from the server (before saving) the file looks good on both system. Else only system 1 shows the correct number of lines.

I don't know exactly if it is about vsCode but I cannot work on different systems like this.

**Comment by IllusionMH** [comment]
> If I download it from the server (before saving) the file looks good on both system.

How do you open same file if you don't download them in first steps?
Are you using Git? Do you have adequate configs for line endings in git?

Is it reproducible in other editors?

**Comment by weinand** [comment]
It looks like you changed the "End of line sequence" on Windows from a one character LF from linux to a two character LF/CR which then shows up on linux as an additional empty line.

**Comment by bfiessinger** [comment]
Thanks @weinand it was about the End of line sequence.
