### ISSUE TITLE
Debug variable overlay disappears when mouse not over text editor

### ISSUE THREAD

**Issue by httpdigest** [Microsoft/vscode#9188]
- VSCode Version: 1.4.0-insider (commit 50a0945)
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Start a JavaScript or TypeScript application in debugging mode (F5)
2. Set a breakpoint
3. Hit the breakpoint
4. Mouse-over a variable
5. The "debug variable"? overlay appears
6. Move the mouse cursor still inside that overlay, but outside of the editor region
7. The overlay disappears

Description: When I wanted to debug an application, I used the debugger with the "variable overlay" to inspect variables inside the editor. However, when I wanted to inspect a variable that was rendered in that overlay _but_ was outside of the editor region, the overlay disappeared, even though it should have had the mouse focus.

The following image shows what I mean:
![debug_overlay_bug](https://cloud.githubusercontent.com/assets/7488613/16797622/acd9e50c-48e8-11e6-9b62-7a1e3a13ebd8.png)

**Comment by isidorn** [comment]
Thanks for the great description, however dup of #3528

**Comment by httpdigest** [comment]
Oh, you are right. Sorry for double-posting! :)
