### ISSUE TITLE
Option to disable extension(s) via workspace config files.

### ISSUE THREAD

**Issue by TriMoon** [microsoft/vscode#91885]
I am in need of an option to disable extension(s) via workspace config `*.code-workspace` files.
This need was created because of a non-functioning extension, https://github.com/editorconfig/editorconfig-vscode/issues/265#issuecomment-593083638, to make sure it is disabled while using a workspace config, without disabling or uninstalling it completely...

**Comment by weinand** [comment]
you can disable extensions per workspace via the dropdown menu:

![2020-03-02_12-16-12](https://user-images.githubusercontent.com/1898161/75671788-ae1d9e00-5c7f-11ea-8481-cfb116480392.png)

**Comment by TriMoon** [comment]
@weinand didn't you read my first line?
> I am in need of an option to disable extension(s) via **workspace config `*.code-workspace` files**.

I know we can use that option you mentioned, but that is a choice the user needs to initiate, not a setting that can be propagated using files under version control and distributed to others...

Please re-open this issue...

**Comment by gjsjohnmurray** [comment]
@TriMoon this looks like a dup of #18386

**Comment by TriMoon** [comment]
> @gjsjohnmurray 
> this looks like a dup of #18386

Wow i didn't see that one, its dated `Jan 11, 2017` :rofl: :roll_eyes: but yea you're right.
As can be seen by my report this is **still needed** functionality. :+1:
