### ISSUE TITLE
No XML Highlight

### ISSUE THREAD

**Issue by Wolly300** [microsoft/vscode#91888]
Issue Type: <b>Bug</b>

Filename: document.xml
Visual Code language (right-bottom-corner): XML

But the XML Tags are not highlighted.

The file has 3868120 Lines.

I also can't use my XML Extensions.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.58GB free)|
|Process Argv|C:\Users\rkr\Downloads\ifs_document_completed-2\ifs_document_completed-2.xml|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
prettier-vscode|esb|3.20.0
vs-code-xml-format|fab|0.1.5

</details>

**Comment by weinand** [comment]
file this issues against the XML extension

**Comment by Wolly300** [comment]
I removed all extensions, restarted the computer, reload the file, but it still don't worked.
It has to be a Visual Code issue.

**Comment by alexr00** [comment]
Please share the file.

**Comment by pgfearo** [comment]
It’s possible that this issue has been caused by the built-in XML extension (which does syntax highlighting) being disabled, perhaps by another extension that is currently disabled?

**Comment by Wolly300** [comment]
1. I can't share the file, because it's a customer file.
2. I deinstalled all extensions, so there should be nothing disabled.
3. I think the file size is to big. I opend the file in Visual Studio 2019 and i had the same problem, but i got the warning, the file is to big, it can't be opened with XML ... I have to edit the registry to change the file size from defaul 10 mb to custome one.

The file is 290 mb big, so i set it to 1 GB and after restarting i got the syntax highlighting.

So, how can i edit such an environment variable in Visual Code ?

**Comment by alexr00** [comment]
In VS Code are there any notifications that say that the file is too big?
If you open the Developer Tools (Developer: Toggle Developer Tools) are there any errors in the console there?

**Comment by alexr00** [comment]
We do have limits on file size for colorization. Max file size of 20 MB and max line count of 300K lines.
In your settings you can set `	"editor.largeFileOptimizations": false` to forcefully tokenize (colorize) your large file.
