### ISSUE TITLE
Options to remove DocumentLink

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#91881]
Issue Type: <b>Feature Request</b>

In my project, I need to often jump to local modules by URL

the trusted domain is very annoying

Ask me every time if I want to add to the trusted domain

actually, I don't want to open it in the browser and I need an option to turn it off.

Because it's really annoying

![1](https://user-images.githubusercontent.com/9758711/75662523-33b64380-5caa-11ea-9792-28763f5f9680.gif)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.2.0

**Comment by gjsjohnmurray** [comment]
Any reason not to mark that domain as trusted by VSCode?

**Comment by axetroy** [comment]
Because once it is marked as a trusted domain

when I click on it and it opens in the browser, which is not what I want

**Comment by gjsjohnmurray** [comment]
For me this kind of thing required Ctrl+Click (I'm on Windows). If an unmodified click is trying to follow a link, perhaps you've got a non-default setting or an extension that's doing this. Does it reproduce after you run the command that reloads with all extensions disabled?

**Comment by octref** [comment]
Clicking a https link should open it in browser — what else do you expect?

**Comment by JacksonKearl** [comment]
@octref Deno uses an ... unusual ... approach of making module import paths the literal URLs of wherever they happened to be hosted when the script was written, then caching them for future uses. I think the user here wants click to go to the local cache rather than the actual URL.

**Comment by JacksonKearl** [comment]
@axetroy does "go to definition" (f12) work as a keyboard workaround?
