### ISSUE TITLE
Peek view code has orange background

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#91894]
Issue Type: <b>Bug</b>

Angular app, option-click component name.  Peek view opens for that component.

All the code inside the component decorator has an orange background and is hard to read.  Happens with all themes including default dark.

See attached, included theme inspector in screenshot

![CleanShot 2020-03-02 at 08 44 16](https://user-images.githubusercontent.com/835148/75681829-5de41300-5c62-11ea-956c-c0fa8a43dce4.jpg)

VS Code version: Code - Insiders 1.43.0-insider (0eebaf9ad23748baca2afc0da425650922bc23de, 2020-02-27T07:32:05.320Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
project-manager|ale|10.10.0
ng-template|Ang|0.900.14
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
todo-tree|Gru|0.0.169
ecdc|mit|1.3.0
HTMLHint|mka|0.6.0
theme-monokai-pro-vscode|mon|1.1.15
vscode-scss|mrm|0.9.0
js-debug-companion|ms-|0.0.4
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
angular2-inline|nat|0.0.17
angular-component-extension|oni|0.0.14
vscode-versionlens|pfl|0.24.0
quicktype|qui|12.0.46
format-html-in-php|rif|1.6.2
code-settings-sync|Sha|3.4.3
rewrap|stk|1.9.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.0.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.7.0

(5 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
The problem is that the location of the search results cover the whole component. they should only covert the component name.

This need to be filed against the extension that provides these references results. I guess its `ng-template` extension.
