### ISSUE TITLE
npm vscode not pointing to github vscode

### ISSUE THREAD

**Issue by dzienisz** [microsoft/vscode#91893]
Steps to Reproduce:

1. https://www.npmjs.com/package/vscode is not pointing to https://github.com/microsoft/vscode

**Comment by IllusionMH** [comment]
See https://github.com/microsoft/vscode-extension-vscode/pull/160 for details

**Comment by dzienisz** [comment]
but it's still not working correctly

**Comment by IllusionMH** [comment]
That package is released from linked repo, not from this one.

Why it should point to this one?

**Comment by dzienisz** [comment]
I mean that this fix don't work. Npm/vscode is still pointing to that minor
plugin instead of vscode app or maybe I'm wrong. I know that It's just
visual fix but it's numer 3 result on Google.

W dniu pon., 2.03.2020 o 15:32 Andrii Dieiev <notifications@github.com>
napisał(a):

**Comment by IllusionMH** [comment]
> The `vscode` NPM module provides VS Code extension authors tools to write extensions.

`vscode` package is aimed for extension developers - it doesn't contain editor and **not released from https://github.com/microsoft/vscode repo**.

After https://github.com/microsoft/vscode-extension-vscode/pull/160 link on npm correctly points to the repo where `vscode` package is released from - https://github.com/microsoft/vscode-extension-vscode

**Comment by dzienisz** [comment]
Ohh ok

W dniu pon., 2.03.2020 o 16:11 Andrii Dieiev <notifications@github.com>
napisał(a):
