### ISSUE TITLE
GUI displays goes wrong on Fedora 31

### ISSUE THREAD

**Issue by afranko** [microsoft/vscode#91895]
- VSCode Version: 1.42.1
- OS Version: Fedora 31

This happens after a few minutes:

![vscode_issue](https://user-images.githubusercontent.com/23009527/75683022-af0dfa00-5c96-11ea-9c96-fb1d8097b180.PNG)

It seems that last OS update on Fedora caused this, since I haven't face this issue before.

Does this issue occur when all extensions are disabled?: Yes

I also tried `--disable-gpu` option, which fixed the main screen, however new windows (open files, stc.) are still suffering from these bug.

**Comment by weinand** [comment]
Does this occur even if you disable all extensions?

**Comment by afranko** [comment]
As I wrote it in the original post: "Does this issue occur when all extensions are disabled?: **Yes**"

**Comment by weinand** [comment]
Fedora is running in a VM, correct?

**Comment by afranko** [comment]
> 
> 
> Fedora is running in a VM, correct?

Yea, It is running in VMWare Workstation Player 15 under Windows 10.

**Comment by tylerdmace** [comment]
![fedora31](https://user-images.githubusercontent.com/5430823/75710383-b8d93280-5c81-11ea-9621-2afff7691f4c.png)

![visualstudio](https://user-images.githubusercontent.com/5430823/75710459-d73f2e00-5c81-11ea-9fcc-08db9efa7866.png)

![vscodedetails](https://user-images.githubusercontent.com/5430823/75710609-1a999c80-5c82-11ea-8d46-1dd3eb9a25c7.png)

Same thing for me, too.

**Comment by tylerdmace** [comment]
Update: this has occurred now for other applications and is not strictly limited to VS Code. I believe we can close this issue as it doesn't appear to be a VS Code problem.

**Comment by tylerdmace** [comment]
**Note:** Once VS Code starts having rendering problems I start seeing it in other applications (like Chrome).

**Comment by tylerdmace** [comment]
Looks like this may be the root issue: https://bugzilla.redhat.com/show_bug.cgi?id=1803819

The fix (for now) is to disable `Accelerate 3D Graphics` under your VMWare display settings.

**Comment by tylerdmace** [comment]
@afranko This may be the root issue: https://bugzilla.redhat.com/show_bug.cgi?id=1803819

The fix, for now, is to disable `Accelerate 3D graphics` under your VMWare display settings.

**Comment by deepak1556** [comment]
Thanks @tylerdmace , seems like there is nothing actionable for VS Code at the moment on this issue. Will leave it open for other future duplicate issues.

**Comment by afranko** [comment]
@tylerdmace Thank you for the advice! It solved the problem.

**Comment by felloz** [comment]
Well Atom here we come!

**Comment by linguohua** [comment]
@afranko , @tylerdmace , guys, it seems this bug has been fixed by https://github.com/vmware/open-vm-tools/issues/400, I upgrade fedora, now mesa version is:
 OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.5
after two days using, it seems been fixed.

**Comment by tylerdmace** [comment]
To be clear, you're able to run VMWare with hardware acceleration enabled,
correct?

**Comment by linguohua** [comment]
@tylerdmace yes, it is.

**Comment by jamsoft** [comment]
I'm seeing similar graphical issues in VirtualBox on Fedora 31. Turning off 3D Acceleration does seem to have fixed it there as well.

**Comment by deepak1556** [comment]
Closing since upstream issue has been closed.
