### ISSUE TITLE
VSCode becomes slower after 1-2 hours

### ISSUE THREAD

**Issue by umutbozdag** [microsoft/vscode#91890]
Issue Type: <b>Performance Issue</b>

As the title says, my VSCode is running slower after 1-2 hours. When i close and start the VSCode again its working normally. This issue happens since 5-6 months or more. I have disabled all extensions and tried it again but i was getting the same behavior again.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (Startup Performance - fylo-dark-theme-landing-page-master - Visual Studio Code [Administrator])
|    Folder (fylo-dark-theme-landing-page-master): 31 files
|      File types: svg(11) jpg(6) png(4) md(2) gitignore(1) html(1) map(1)
|                  scss(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.1
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|2.6.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.20.0
vscode-styled-components|jpo|0.0.28
vscode-github|Kni|0.30.3
vetur|oct|0.23.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-snapshot|rob|0.2.1
preview-vscode|sea|2.1.0
sass-indented|syl|1.7.5
ayu|tea|0.18.0
vscode-icons|vsc|10.0.0

(3 theme extensions excluded)

</details>

**Comment by weinand** [comment]
@umutbozdag please review https://github.com/microsoft/vscode/wiki/Performance-Issues and consider submitting more information.

**Comment by weinand** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
