### ISSUE TITLE
First Report .

### ISSUE THREAD

**Issue by evaraja-slenopapsode** [microsoft/vscode#91897]
1 . Terminal not functional at all .
2 .  Intellisense for phyton (vscode) too small ,i can't see it .

**Comment by weinand** [comment]
Please follow these [guidelines](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) how to submit bug reports.

I see at least 4 problems with your "first report":
- do not combine multiple unrelated problems in one report
- use a good title for the bug report
- describe your setup: what version of VS Code, which extensions
- explain the problem in a way that we can understand and reproduce it.
