### ISSUE TITLE
Opening root drive in remote displays as 'C:'

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91903]
From https://github.com/microsoft/vscode-remote-release/issues/1596#issuecomment-592687964

Should it be displayed as `C:\` though? Just `C:` looks weird to me. But it's an edge case and I don't know what other people expect. This is after I typed `C:\` in the picker

![image](https://user-images.githubusercontent.com/323878/75580820-47994580-5a1d-11ea-9386-39fa9ebf9aad.png)

**Comment by isidorn** [comment]
Not a lot of feedback regarding this. Closing as will not fix for now.
