### ISSUE TITLE
VS Code crashes when deleting files from the "Explorer"

### ISSUE THREAD

**Issue by jbakchr** [microsoft/vscode#91902]
Issue Type: <b>Bug</b>

### Issue
When just deleting one or more unneeded files from a newly created project such as a React one with "npx create-react-app <projectname>" in the Explorer then VS Code first freezes and thereafter crashes prompting me to either close it or reopen it.

### Steps to reproduce
So, the steps to reproduce is just is actually very short and straight forward since it is, at a minimum, just:

1) Delete a file or more from the "Explorer"

### "Bonus info"
I have tried to disable some of my extension to see if that would help. But it hasn't ... But I of course try disabling some more combinations thereof so that might be able to help more with this issue myself.

Hope this description of this issue is okay. Otherwise, let me know.

Br. Jonas

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.6.0
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
graphql-for-vscode|kum|1.15.3
debugger-for-chrome|msj|4.12.6
vscode-jest|Ort|3.1.1
colonize|vms|2.2.2

</details>

**Comment by jbakchr** [comment]
"Ps.", if this info might be of any help or usage at all, but when using the terminal to remove files, no such problem occur.

Just wanted to share that (even though it be a complete noob kind of obvious info ... but still .. bear with me :) )

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by jbakchr** [comment]
Yeah okay, @bpasero . I will of course have a look at it in order to help as much as I can. But you've been nice to know that I should've included more info when trying to fill out your "issue template" (or whatever no would call it) in the beginning ..

But "anywho", I'll of course have a look at it and try my best to supply you with as much info as I can.

**Comment by bpasero** [comment]
Great to hear.
