### ISSUE TITLE
Please make invalid code highlight in red (or a similarly distinct color) in Abyss

### ISSUE THREAD

**Issue by gaoutilityman** [microsoft/vscode#91909]
The default syntax highlighting for invalid code is red in the default dark color scheme, which is great.  But it defaults to bright white in Abyss, which is quite similar to valid code.  
Consider making something like the setting below the default for Abyss and any other default color scheme that does not make invalid code jump out and perhaps also documenting this feature better -- it took me about an hour to figure out that this was I needed to add to my settings.json file

"editor.tokenColorCustomizations": {

        "[Abyss]": {

[{"scope":"invalid", "settings":{"foreground":"#f44747"}}] }

    },

**Comment by gjsjohnmurray** [comment]
/causedByExtension see https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Abyss for a link to the theme's repo, where you need to submit your request.
