### ISSUE TITLE
cannot GET/ index.html/ 

### ISSUE THREAD

**Issue by vvesser** [microsoft/vscode#91912]
When i try to open my index.html file with live server it opens a google web browser but says " Cannot GET/ index.html/  and Failed to load resource: the server responded with a status of 127.0.0.1/:1
 404 (Not Found)

**Comment by weinand** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
