### ISSUE TITLE
vscode.WorkspaceConfiguration.update('tasks', [...]) does not add version property 

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode#91911]
- VSCode Version: 1.42.1
- OS Version: Windows 10 (19041.113)

When calling `vscode.WorkspaceConfiguration.update('tasks', [...])` to programmatically add tasks, and no existing `tasks.json` exists in the workspace folder, a new `tasks.json` will be created but it will not contain the suggested `version` property, which then results in a warning in the "problems" window: `Missing property "version".`

Note that the tasks function as expected; it's simply cluttering the problems window.

**Comment by davidshq** [comment]
Can tag fixed next release be added to this ticket? Looking on how to correct this error and Google dropped me here.

**Comment by alexr00** [comment]
Please check out our development process and our iteration plan. We map issues to a release based on the Milestone. https://github.com/microsoft/vscode/wiki/Development-Process
