### ISSUE TITLE
All Explorer tabs (NPM Scripts, Docker, Outline) are all missing.

### ISSUE THREAD

**Issue by spydmobile** [microsoft/vscode#91915]
Issue Type: <b>Bug</b>

YMMV but on my system, open code and the tabs that are normally there are missing.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.88GB (36.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
numbered-bookmarks|ale|7.0.0
atlascode|atl|2.4.4
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.1
emoji-snippets|dev|1.1.0
vscode-docker-syntax|dun|0.1.5
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
auto-rename-tag|for|0.1.1
rest-client|hum|0.23.1
better-dockerfile-syntax|jef|1.0.1
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
appidocsnippets|mya|0.1.19
JavaScriptSnippets|nat|0.2.0
prettier-standard-vscode|num|0.6.0
quicktype|qui|12.0.46
vscode-yaml|red|0.7.2
color-manager|roy|0.5.5
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.0.3
vsc-quokka-statusbar|ske|1.2.2
addDocComments|ste|0.0.8
vscode-icons|vsc|10.0.0
vscode-wakatime|Wak|4.0.0
quokka-vscode|Wal|1.0.281
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

**Comment by spydmobile** [comment]
![Screenshot 2020-03-02 13 17 30](https://user-images.githubusercontent.com/1065978/75714171-6f401600-5c88-11ea-9f06-5acdd82487cb.png)

**Comment by gjsjohnmurray** [comment]
What does the context menu from that EXPLORER: INTELxxx header show?

**Comment by spydmobile** [comment]
Man, I searched and read for over an hour, thank you, 
In the context menu, all the tabs were unchecked in there, I did not do this, but I am so happy to turn it back on!!
