### ISSUE TITLE
Running Save Participants BUG

### ISSUE THREAD

**Issue by webdevnerdstuff** [microsoft/vscode#91916]
- VSCode Version: 1.42.1
- OS Version: Mac & Windows

Steps to Reproduce:

1. Save a file

Does this issue occur when all extensions are disabled?: No

This problem is occurring with many different extensions from searching through other tickets with this problem. We cannot just disable all of our extensions and keep working without them. None of these extensions had a problem before the last update.

One extension in particular that I was having this issue with was Vetur. One co-worker has the same VS Code version and Vetur version, and he does not have this problem. But for me I have the problem on both my work PC and Macbook Pro at home. So perhaps there was an issue with the latest release for some people but not others?

**Comment by gjsjohnmurray** [comment]
Are you willing to test with Insiders? Otherwise I suggest you wait a few days for the 1.43 endgame to finish.

**Comment by webdevnerdstuff** [comment]
@gjsjohnmurray I don't really have the time to at the moment. Too much work to get done. Hopefully the 1.43 version will resolve the issue, I can wait a few days and deal with the annoyance for now I guess. Thank you for the response.

**Comment by ricealexander** [comment]
I've been having issues with Save Participants on my PHP files on and off for the last few weeks. At first I thought it was a problem with ESLint (HTML Plugin) and uninstalling it solved the issue for a while, and now it's back.

It would be nice if the "Running Save Participants" popup at the bottom would have some kind of message of what extensions are affecting it.

**Comment by webdevnerdstuff** [comment]
I was also having this issue over the weekend with PHP files. Not just VUE files.

**Comment by gjsjohnmurray** [comment]
> It would be nice if the "Running Save Participants" popup at the bottom would have some kind of message of what extensions are affecting it.

https://github.com/microsoft/vscode/issues/90851#issuecomment-589681352 indicates new stuff in this area is coming in 1.43, due out later this week. If you can't wait, try Insiders.

**Comment by pascalandy** [comment]
+1 

> It would be nice if the "Running Save Participants" popup at the bottom would have some kind of message of what extensions are affecting it.
