### ISSUE TITLE
macOS Pause Button not sending PauseRequest

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#91918]
**Issue**: VS Code is not sending PauseRequest to Debug Adapter on macOS. 

- VSCode Version: 1.41.1 and 1.43.0-insider
- OS Version: macOS Mojave 10.14.6

--------------------------------

Steps to Reproduce:

1. Install C/C++ extension
2. Create a simple C++ project and attach to it.

<details>
<summary>launch.json</summary>

```
{
   "version": "0.2.0",
   "configurations": [
      {
         "name": "(lldb) Attach",
         "type": "cppdbg",
         "program": "${workspaceFolder}/a.out",
         "processId": "${command:pickProcess}",
         "MIMode": "lldb"
      }
   ]
}
```

</details>

<details>
<summary>main.cpp</summary>

```
#include <unistd.h.>
#include <iostream>

int main(int argc, char *argv[]) {
   while(1) {
      std::cout << "Hello World" << std::endl;
      sleep(10);
   }

   return 0;
}
```

</details>

3. Hit the pause button in the debug tool bar.

Expected: PauseRequest sent to DebugAdapter
Actual: No message is sent.
-----------------------

*Additional Notes*
The debug adapter does not get any message to read from the stream when the pause button is hit,.

I set a breakpoint on https://github.com/microsoft/vscode/blob/33e78e0978b032d6cddef69bcc650a1d488d7297/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L315, but it does not get hit when I select the pause button. 

As a validation, I do hit the breakpoint when I select disconnect and hit this line: https://github.com/microsoft/vscode/blob/33e78e0978b032d6cddef69bcc650a1d488d7297/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L253

**Comment by isidorn** [comment]
@WardenGnaw thanks for looking into this. I have tried reproducing this with nodejs and I could not reproduce, the `pause` gets nicely sent out. I see you can reproduce also with VS Code stable and if there was a general issue I would expect more users to have hit this.

I have a new machine with no C++ repositories, can you please share a simlpe starter C++ repository with a `launch.json` so I try this out on my macOS.
Alternative is if you can put a brekapoint [here](https://github.com/microsoft/vscode/blob/a03ea07917ea1ccdd4821befac6f292f5fb71c09/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L265) and see if the thread is properly identified and if the `thread.pause` gets called.

**Comment by WardenGnaw** [comment]
@isidorn As usual, we always appreciate your help!

At the moment, it may be an issue on our side. When `focusedSession.getAllThreads()` is called. we return `[]`, therefore there is no thread to pause on. 

https://github.com/microsoft/vscode/blob/a03ea07917ea1ccdd4821befac6f292f5fb71c09/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L83

I'm currently investigating why we have no threads.

**Comment by WardenGnaw** [comment]
It was an issue with our debugger not reporting any active threads even though the process was running. We have found a fix. 

Thanks again @isidorn for the help!

**Comment by isidorn** [comment]
Great, glad you found the root cause.
