### ISSUE TITLE
"editor.codeActionsOnSaveTimeout" is an "Unknown Configuration Setting"

### ISSUE THREAD

**Issue by Wolven531** [microsoft/vscode#91917]
Version: 1.43.0-insider
Commit: d1c48c103cabc6e729f59787c0b9c86fb3d39e73
Date: 2020-02-29T02:17:38.054Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

Steps to Reproduce:

1. Open User settings file `settings.json` (I used the Mac shortcut `Cmd` + `,` )
2. Search for the setting "Editor: Code Actions On Save" (I entered the text `codeAction` in the search box at the top of the UI)
3. Click the link to jump to `settings.json`
4. Paste the following line `"editor.codeActionsOnSaveTimeout": 1000,`
5. Hover over the grayed out line (it is grayed out because VSCode Insiders doesn't recognize the property)
6. See the warning message: "Unknown Configuration Setting"

Does this issue occur when all extensions are disabled?: Yes (see screenshots)

Note that this occurs when the relevant extensions (ESLint in this case) are ENABLED or DISABLED

<img width="1462" alt="Screen Shot 2020-03-02 at 3 32 10 PM" src="https://user-images.githubusercontent.com/2125913/75724224-28a7e700-5c9b-11ea-84ca-0bf4f60f7323.png">

<img width="995" alt="Screen Shot 2020-03-02 at 3 32 51 PM" src="https://user-images.githubusercontent.com/2125913/75724237-2e053180-5c9b-11ea-93d2-edceb7529ef1.png">

<img width="1040" alt="Screen Shot 2020-03-02 at 3 32 59 PM" src="https://user-images.githubusercontent.com/2125913/75724245-3493a900-5c9b-11ea-8ac1-91edec2d3bb6.png">

<img width="902" alt="Screen Shot 2020-03-02 at 3 34 53 PM" src="https://user-images.githubusercontent.com/2125913/75724373-7b819e80-5c9b-11ea-9fc6-57acc897571f.png">

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/87449#issuecomment-572609688 shows where @jrieken removed this setting from the current Insider (1.43)

**Comment by weinand** [comment]
@jrieken so the removal of the "editor.codeActionsOnSaveTimeout" seems to be "as designed", correct?

**Comment by jrieken** [comment]
Yes - as designed. Also see https://code.visualstudio.com/updates/v1_42#_handling-slow-save-operations
