### ISSUE TITLE
Bad layout in debug console with long console message location

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91924]
- Debug Chrome
- Navigate to microsoft.com

![image](https://user-images.githubusercontent.com/323878/75733460-403a9c00-5caa-11ea-8dde-06627db137d7.png)

The same message in chrome devtools

![image](https://user-images.githubusercontent.com/323878/75733520-68c29600-5caa-11ea-8f81-e8ccb053eb94.png)

**Comment by isidorn** [comment]
Are you seeing this with latest out of source?
Potenital duplicate of https://github.com/microsoft/vscode/issues/91899

**Comment by roblourens** [comment]
Yes, I don't think it's the same
