### ISSUE TITLE
vscode use too much memory ，it cost 14Gb  that is 95% of my computer

### ISSUE THREAD

**Issue by wflixu** [microsoft/vscode#91927]
vscode version: 1.42.1
OS win7

**Comment by weinand** [comment]
@wflixu please review https://github.com/microsoft/vscode/wiki/Performance-Issues and consider submitting more information.

**Comment by wflixu** [comment]
Thanks so much，I disabled all the extendsions, then the problem was reversed. So is caused by some extendsion I installed.

**Comment by weinand** [comment]
You can try to enable one extension at a time and see when the problem shows up again.
