### ISSUE TITLE
Resuming in the call stack view for the unselected debug child does not update editor decoration

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91922]
1. Set a breakpoint here 

https://github.com/microsoft/vscode-js-debug/blob/d80e89a33fd3c5c0a62f96d490df30ceca2b599f/demos/node/cluster.js#L24

2. Start the server, see a bunch of children paused on that line

3. _Without_ selecting each child debug session individually in the calls stack, click the resume button

4. Observe that the breakpoint decoration is not removed

If you have the child selected and then click resume, the line decoration is removed correctly

Video: https://memes.peet.io/img/1b47320c-6cd5-4bce-b511-af2191a921a5.mp4

cc @kieferrm

**Comment by isidorn** [comment]
Thanks for steps!
However in the video I see you are launching `Launch Program` launch configuration which I do not see when I clone the vscode-js-debug.
I tried running the "Debug Server" one but that one complains about the prot `4711` being already in use.
So what exact launch configuration are you using?

**Comment by connor4312** [comment]
I'd modified the "launch program" config in vscode-js-debug/demos/node to launch cluster.js instead of main.js. You can also run it from the debug terminal.

**Comment by isidorn** [comment]
Great steps. Thanks a lot!

**Comment by isidorn** [comment]
@connor4312 can you no longer repro this? Asking becasue I would like to add a verified label. Thanks!

**Comment by connor4312** [comment]
yep, looks good!
