### ISSUE TITLE
Add wrapping support to variable values in debug sidebar

### ISSUE THREAD

**Issue by Domush** [microsoft/vscode#91920]
Since multi-window support is a long way off (if ever), please add a way to wrap the values of variables in the debug Watch and Variables sidebar.

Having to hover over a value over and over is really annoying and slows down debugging.

A way to move the Debug sidebar to the bottom would also be nice, as an alternative, so long values can use the entire display width.

**Comment by isidorn** [comment]
Debug views can be moved to the bottom palen actually starting from next vscode stable (in a couple of days).
Please try it out and let us know if you still see something missing.
Please note that moving views is still work in progress and we plan to improve on that fron.

Thus closing this
