### ISSUE TITLE
Can't debug vscode-js-debug extension 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91923]
- Clone https://github.com/microsoft/vscode-js-debug, build it, run "Extension" launch config
- The builtin version of the extension is used instead, and it always shows a "Reload window" button on it:

![image](https://user-images.githubusercontent.com/323878/75732103-61998900-5ca6-11ea-9701-25eba859744b.png)

- If I 'disable' the builtin instance of the extension, it shows as disabled but still runs the builtin instance of the extension

@connor4312 you're not seeing this?

**Comment by sandy081** [comment]
I think it should use the one you are debugging. Can you please confirm that by opening running extensions?

**Comment by connor4312** [comment]
I see the constant "reload" button button as well but it appears to be using the correct version for me

![image](https://user-images.githubusercontent.com/2230985/75798597-a4517480-5d2b-11ea-934c-170e0a549cdb.png)

**Comment by connor4312** [comment]
Actually, I just saw this happen. Will see if I can get repro steps.

**Comment by roblourens** [comment]
I was having issues last night but it seems to be working fine today and I actually don't even see the reload button 🤷‍♂

**Comment by roblourens** [comment]
It seems kind of random, @sandy081 the running extensions page doesn't tell me where the extension is loaded from, just the name, which is the same.

**Comment by sandy081** [comment]
Ah, its not helpful. I will add at least version and location details to it.

**Comment by sandy081** [comment]
Added version details. Please try again and let me know.
