### ISSUE TITLE
refactor - Extract to function disabled in v1.42.1

### ISSUE THREAD

**Issue by erickyi2006** [microsoft/vscode#91921]
- VSCode Version: 1.42.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Highlight a block of code (nodejs javascript source code)
2. Press Ctrl+Shift+R
The refactor menu is shown but the Refactor to Function is disabled

![image](https://user-images.githubusercontent.com/19684107/75730579-6e1eef80-5d41-11ea-8771-525791ede282.png)

Does this issue occur when all extensions are disabled?: Yes
Updated: I did a disable all extensions and the issue still occurred

This used to work in previous vscode

**Comment by mjbvz** [comment]
This is by-design. We show that we support these functions but you cannot use them with the current selection. We're looking into surfacing the reason why they are disabled with: https://github.com/microsoft/TypeScript/issues/35098

**Comment by erickyi2006** [comment]
i don't understand this "by design". 
are you saying:
1. code reactoring is not supported by vscode on nodejs source code? or 
2. refactoring when i select a block of code is not supported?

**Comment by mjbvz** [comment]
2. The block you selected can't be extracted. We gray out the extract items in the refactor menu when that's the case (similar to how debug menu items are grayed out if you are not debugging anything)

**Comment by erickyi2006** [comment]
thanks for the hint. 

I investigated further and found that refactor to a function will fail to refactor if there is a return in the code selection.  Happy with the explanation. Thanks guys
