### ISSUE TITLE
Encoding priority?

### ISSUE THREAD

**Issue by VillSnow** [microsoft/vscode#91925]
I am one of who have encoding trouble.

I am Japanese-speaker and often use UTF-8 and Shift-JIS
When I open UTF-8 file, it's sometimes guessed as Windows 1252. When I open Shift-JIS file, it can be opened as ISO-8859-2.

These code pages are not general in Japan, and probably many other non European language speaking countries.
Conversely, Shift-JIS would not common outside Japan. GBK and Big5 are not common outside China and Taiwan, and it is said about all code pages (except for unicode).

So I suggest to set encoding priority in user preference like
```json
"favoriteEncodings": ["UTF-8", "Shift-JIS", "EUC-JP"]
```
then everyone in the world would be happy.

How is this? If possible, it is more practical than removing jschardet.

**Comment by WangShuoran** [comment]
I love it! Same suggestion!
