### ISSUE TITLE
I want vscode's embedded terminal to mute

### ISSUE THREAD

**Issue by WangShuoran** [microsoft/vscode#91928]
I love VScode, I love it.
Now, I will contribute my first contribution to open source.
In our work, we usually use terminal. We can't leave it.
But lots of us coding with music,so that terminal audio is very harsh and unpleasant.
But we can‘t mute VScode because maybe VScode will sand an important audio.
So I want increase a button to mute vsocde embedded terminal!
Thank you! I love you! I love VScode!

**Comment by Tyriar** [comment]
You can turn off the bell by setting `terminal.integrated.enableBell` to false, but that's the default. That's the only sound VS Code controls, maybe your shell is making the sound?

**Comment by WangShuoran** [comment]
Until now, I have not heard any terminal sound. Maybe this succeeded.
