### ISSUE TITLE
file changes error

### ISSUE THREAD

**Issue by sohaibyounas** [microsoft/vscode#91933]
when file changes occur, it's give errors. like changes in tags opening are separated by space and when  remove spaces & save file, it remain same as previous state. Solve this ASAP
![Uploading vs error2.png…]()
![vs error](https://user-images.githubusercontent.com/23151927/75746591-8f311180-5d3c-11ea-908b-2d6e048108ed.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including, platform, version, whether it reproduces when all extensions are disabled, and a set of clear repro steps

**Comment by weinand** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
