### ISSUE TITLE
Semantic token color highlighting fails on line with selected text

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode#91936]
This issue occurs when running a language extension that uses the proposed Semantic Tokens API for all syntax-highlighting. 

To reproduce:
1. In Visual Studio Code Insiders, open the extension project [XML Spectrum (on GitHub)](https://github.com/pgfearo/vscode-xslt-tokenizer) that uses the Semantic Tokens API
2. Run the extension in the Extension Development Host
3. In the Extension Development Host, open a file with a .xsl extension (e.g. [sample/w3c-xslt.xsl](https://github.com/pgfearo/vscode-xslt-tokenizer/blob/master/sample/w3c-xslt.xsl) in the project.

When editing the XSLT file, select text on a line where syntax highlighting occurs. 

The syntax highlighting colors are no longer shown on the same line as the start of the text-selection, see screenshot:

![semantic-highlighting-on-selection](https://user-images.githubusercontent.com/2734234/75751897-7fef9b00-5d1f-11ea-98a8-85b7a827e751.png)

In the case when you use a multi-line text-selection, all lines with text selected are affected in a similar way.

- VSCode Version: 1.43.0-insider
- OS Version: Darwin x64 18.7.0

Does this issue occur when all extensions are disabled?: Yes

Environment:

Version: 1.43.0-insider
Commit: 0eebaf9ad23748baca2afc0da425650922bc23de
Date: 2020-02-27T07:32:05.320Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by alexdima** [comment]
@pgfearo Can you please provide clear steps to reproduce with code that is copy-paste friendly and not in a screenshot, etc.

**Comment by pgfearo** [comment]
@alexdima I've added more detail on how to reproduce using my own VSCode extension project, but I was guessing this could be reproduced using any such project using the Semantic Tokens API.

**Comment by alexdima** [comment]
@pgfearo Thank you for the additional steps. I could not reproduce with the built-in TS semantic tokenizer, nor with the sample at https://github.com/microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample

I could also not reproduce with your extension. For me, the coloring looks very different than in your screenshot:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/75773331-f99e7d80-5d4d-11ea-9ca6-0cc16db2685c.gif)

**Comment by pgfearo** [comment]
@alexdima I'm afraid I don't understand why I'm getting different colorisation of the tokens. It seems that the tokens are produced ok even on your animated screenshot, at least for the first token on each line, and sometimes it gets as far as 4 tokens.

One thing of note from your screenshot: on the mini map on the right, if you look carefully, the tokens are colorised properly - 'then' is colored purple and the enclosed strings like '\\' are colored brown.

Do you know how the tokens could be colored correctly in the mini-map, but not those in the main editor view?

**Comment by alexdima** [comment]
:+1: I can reproduce now. The trick is it only reproduces when using `"editor.renderWhitespace": "selection"`
