### ISSUE TITLE
!/a/无语法高亮

### ISSUE THREAD

**Issue by yunxu1019** [microsoft/vscode#91939]
- VSCode Version:
- OS Version:

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/15274374/75754794-4abb6b00-5d68-11ea-907c-d210ca9884a3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate - see https://github.com/microsoft/TypeScript-TmLanguage/issues/806#issuecomment-593587276 for a workaround
