### ISSUE TITLE
SSH Agent forwarding does not work with "terminal.integrated.inheritEnv": true

### ISSUE THREAD

**Issue by babrodtk** [microsoft/vscode#91934]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Set "terminal.integrated.inheritEnv": true in settings
2. Use remote development environment to connect to a remote machine
3. In the remote terminal, execute cat $SSH_AUTH_SOCK
4. Should say something like cat: /foo/bar: No such file or directory

This means that ssh cannot contact the ssh agent. Using ssh -v <third host> within the terminal should reveal something like 
vs code debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
which I believe is related to the wrongly sett SSH_AUTH_SOCK. 

Does this issue occur when all extensions are disabled?: Not tested. 

My understanding is that inheritEnv sets the SSH_AUTH_SOCK to the path on the local machine, which of course is not available on the remote. One solution could be that SSH_AUTH_SOCK does not inherit/reset everything, but skips certain variables such as this one.

**Comment by babrodtk** [comment]
This also affects things like X11-forwarding, in which DISPLAY is wrongfully set. 

I believe it was the Python extension which detected that I was running Anaconda which suggested setting "terminal.integrated.inheritEnv": true, and this subsequently caused all of these other side effects.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1835
