### ISSUE TITLE
Peek: does not remember size anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91937]
Steps to Reproduce:

1. open peek (e.g. Find References)
2. resize it to be larger
3. ESC to close
4. do again

=> 🐛 size is not restored

![Kapture 2020-03-03 at 8 30 12](https://user-images.githubusercontent.com/900690/75752554-3906a300-5d29-11ea-9a99-82db0530bdfc.gif)

**Comment by jrieken** [comment]
Hm... Looks like the onDidClose-event doesn't fire
