### ISSUE TITLE
TS: refactoring a class that gets imported and renamed does not update the import

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91940]
Steps to Reproduce:

1. have an import such as `import { IEditor as IWorkbenchEditor } from 'vs/workbench/common/editor';`
2. refactor rename `IEditor` to `IEditorSomething`

=> 🐛 the import is not updated

**Comment by martinjaime** [comment]
I'd love to help with this. This would be my first experience contributing to open source. Can someone point me in the right direction?

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/37188 to track upstream

@martinjaime Please follow up with the TypeScript team to see how you can help out
