### ISSUE TITLE
Add Common Method Autocomplete Unity C# in VSCode

### ISSUE THREAD

**Issue by komputerboy** [microsoft/vscode#91942]
Hi,

I using VSCode as my Unity C# Script editor. I've follow this tutorial: [https://code.visualstudio.com/docs/other/unity](url) to install it. 

It worked very well, but there is a little problem. So, why there are no autocomplete / intellisense of common method like: Start(), Update(), FixedUpdate(), etc? 

It will be very great if not only object or variable intellisense but also for common method too.

Thanks

**Comment by weinand** [comment]
Please file this issue against the Unity extension.
