### ISSUE TITLE
Order of custom tree views is not mapped 1:1 from package.json

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#91947]
- VSCode Version: 1.42.1
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Create a custom extension that contributes a custom view or take one from the extension samples, e.g. the [tree-view-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample).
2. Open the `package.json`, find the contributed views (where there are multiple ones!) and shuffle them around.
3. Debug the extension with vscode
4. Observe that the custom views appear in a non-deterministic order (it is non-deterministic in the sense that there is no clear mapping between the order in the `package.json` and the displayed order. The same `package.json` creates the same displayed order though).

For example, this snippet from `package.json`: 
``` json
			"explorer": [
				{
					"id": "ftpExplorer",
					"name": "FTP Explorer"
				},
				{
					"id": "testView",
					"name": "Test View"
				},
				{
					"id": "fileExplorer",
					"name": "File Explorer"
				},
				{
					"id": "jsonOutline",
					"name": "Json Outline",
					"when": "jsonOutlineEnabled"
				}
			]
```
results in the views being ordered as follows: "Json Outline", "FTP Explorer", "Test View", "File Explorer" (Json outline should be the last, but it is not).

In contrast to that, this one: 
``` json
			"explorer": [
				{
					"id": "jsonOutline",
					"name": "Json Outline",
					"when": "jsonOutlineEnabled"
				},
				{
					"id": "testView",
					"name": "Test View"
				},
				{
					"id": "fileExplorer",
					"name": "File Explorer"
				},
				{
					"id": "ftpExplorer",
					"name": "FTP Explorer"
				}
			]
```
creates the expected order: "Json Outline", "Test View", "File Explorer", "FTP Explorer".

I can reproduce this behavior also with other extension, but haven't found a pattern yet.

Does this issue occur when all extensions are disabled?: Yes (except for the `tree-view-sample` extension).

**Comment by alexr00** [comment]
The views are shown in the order that they are listed in package.json, **unless** the order has already been cached from running the extension before. To have the views show in the package.json order, you should clear you local storage.

**Comment by dcermak** [comment]
> The views are shown in the order that they are listed in package.json, **unless** the order has already been cached from running the extension before. To have the views show in the package.json order, you should clear you local storage.

Hm, how would I clear the local storage? I have deleted `~/.config/Code` and `~/.vscode/` but to no avail, the order of the containers is still wrong.

**Comment by alexr00** [comment]
The easiest way is probably to use the cli to point to a different user data directory so that you don't have to delete all your VS Code user data. Check out the `--user-data-dir` arg [here](https://code.visualstudio.com/docs/editor/command-line)
