### ISSUE TITLE
VS code Error

### ISSUE THREAD

**Issue by priyakshirsagar3010** [microsoft/vscode#91944]
We have written the needed data into your clipboard because it was too large to send. Please paste.

every time after opening VS code application  it get close unexpectedlly..also getting error window has been crased ..so please help

**Comment by weinand** [comment]
/needsMoreInfo including, platform, version, whether it reproduces when all extensions are disabled, and a set of clear repro steps

**Comment by priyakshirsagar3010** [comment]
Thank you for reply, I'm getting these errors.. Plz check this

On Mar 3, 2020 3:28 PM, "Andre Weinand" <notifications@github.com> wrote:

/needsMoreInfo including, platform, version, whether it reproduces when all
extensions are disabled, and a set of clear repro steps

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/microsoft/vscode/issues/91944?email_source=notifications&email_token=AOKXURXKZGHBESBG5LN74PDRFTIF5A5CNFSM4LAGUREKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENS2UHQ#issuecomment-593865246>,
or unsubscribe

**Comment by weinand** [comment]
@priyakshirsagar3010 check what? I do not see any helpful information.

**Comment by weinand** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
