### ISSUE TITLE
[folding] [copy] [paste] keep code snippet folded when copy-&-pasted

### ISSUE THREAD

**Issue by rowild** [microsoft/vscode#91948]
I did my best. Due to the statement that an issue is moved up due to voting AND duplication (ssee last statement in https://github.com/microsoft/vscode/issues/16082), I post this issue again, with links to related issues.

When a code snippet that is folded is copied-and-pasted to another place in the file, the folded-status should be kept on paste. Currently, the snippet is unfolded again.

The desired behaviour can be observed, when a selected folded code snippet is moved using SHIFT-&-CursorUp (not down, because that adds indentation).

Use case scenario:
In a json file (e.g. .stylelintrc), order the rules alphabetically.

No folding extensions used.
IMO should be a native feature.

Related:
https://github.com/microsoft/vscode/issues/16082
https://github.com/microsoft/vscode/issues/58209
https://github.com/Microsoft/vscode/issues/49886

**Comment by rowild** [comment]
The suggested issue is not related to this issue.

**Comment by aeschli** [comment]
It's a dup of #16082.
I reopen #16082 to see if other request that too.

**Comment by rowild** [comment]
@aeschli Thank you! Wouldn't it be necessary to make #16082 open for discussion, too? It is currently locked to collaborators. Or am I misunderstanding sth here?

**Comment by aeschli** [comment]
Oh yes, of course. I unlocked the conversation.
