### ISSUE TITLE
Press Exit option closes all the instance

### ISSUE THREAD

**Issue by Susendran** [microsoft/vscode#91949]
Issue Type: <b>Bug</b>

Suppose i open 2 or more instance of Visual Studion Code, Click on  File -- > Exit closes all the instances .Expectation only current instance should get close.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.1
githistory|don|0.6.0
vscode-docker|ms-|0.10.0
csharp|ms-|1.21.12

</details>

**Comment by gjsjohnmurray** [comment]
I think that's as designed. If you want to close only the current window from the File menu, use "Close Window".

I can see how this may be unexpected though. Perhaps the "Exit" text could be made smart enough to read "Exit All Windows (3)" if there are, say, 3 windows currently open.

**Comment by Susendran** [comment]
It's not duplicate..
