### ISSUE TITLE
Eating 25GB of RAM

### ISSUE THREAD

**Issue by SandorSzilard** [microsoft/vscode#91946]
Issue Type: <b>Performance Issue</b>

electron_node tsserver.js CPU and RAM usage is huge. It makes the visual studio code environment useless.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 11160	code main
    0	   216	 13844	   window (● leas.service.ts - **data censured** - Visual Studio Code)
    0	    66	  5436	     extensionHost
    0	    32	  5260	       "C:\**data censured**\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\**data censured**\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=5436
    6	   218	 10220	       electron_node tsserver.js 
    0	    45	 16104	         electron_node typingsInstaller.js typesMap.js 
    0	    58	 15080	       electron_node tsserver.js 
    0	     8	  9096	     winpty-process
    0	    65	 13952	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 22188	         C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    36	 18912	           "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" start
    0	     5	 16060	             electron_node conf.js 
    0	   350	 22656	               node   "E:**data censured**\node_modules\.bin\\..\@angular\cli\bin\ng" serve --proxy-config proxy.conf.json
    0	    55	 24296	                 "C:\Program Files\nodejs\node.exe" "E:\**data censured**\node_modules\@ngtools\webpack\src\type_checker_worker.js" 9d93e901-158a-4cf9-ba1b-2f0582ffcfeb
    0	    12	 23092	       console-window-host (Windows internal process)
    0	    17	 12200	     watcherService 
    0	    11	 11364	       console-window-host (Windows internal process)
    0	   107	 14848	   gpu-process
    0	    14	 15720	   electron-crash-reporter
    0	    69	 17620	   shared-process
    0	    66	 22108	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● leas.service.ts - **data censured** - Visual Studio Code)
|    Folder (**data censured**): 1565 files
|      File types: ts(436) html(267) png(152) ttf(83) json(66) js(66) scss(66)
|                  svg(59) css(43) gif(22)
|      Conf files: tslint.json(2) package.json(1) tsconfig.json(1)
|                  launch.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-beautifier|mic|2.3.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6

</details>

**Comment by gjsjohnmurray** [comment]
Did you yet try the command to reload with all extensions disabled?

**Comment by SandorSzilard** [comment]
I tried it now with the extensions disabled for a few hours. I had to enable chrome debugger. But everything works OK (Now I have only 2 plugins disabled).
Visual Studio Code worked fine before the update with the plugins enabled, so I supposed it is a problem with it.

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Perhaps an incompatibility between one (or both) extension(s) and the current version of VS Code. I suggest you try to work out exactly which extension is triggering the issue, then open an issue in the home repo of that extension.
