### ISSUE TITLE
Corrupt file data if VSCode save it

### ISSUE THREAD

**Issue by saippuakauppias** [microsoft/vscode#91958]
Issue Type: <b>Bug</b>

After editing and saving the https://github.com/vrana/adminer/releases/download/v4.7.6/adminer-4.7.6-mysql-en.php file, the browser showed me js and css parsing errors.
It’s all because there is encoded binary data inside the file, but why does the editor change it?

You can play the bay of the edited file to the server and requesting urls:
adminer-4.7.6-mysql-en.php?file=default.css&version=4.7.6
adminer-4.7.6-mysql-en.php?file=functions.js&version=4.7.6 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
unique-lines|bib|1.0.0
python-extension-pack|don|1.6.0
vscode-html-css|ecm|0.2.3
json-tools|eri|1.0.2
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
todo-tree|Gru|0.0.169
vsc-python-indent|Kev|1.8.1
vscode-phpfmt|kok|1.0.30
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.10.0
vscode-language-pack-ru|MS-|1.42.2
python|ms-|2020.2.64397
Go|ms-|0.13.1
python|tht|0.2.3
shellcheck|tim|0.9.0
vscodeintellicode|Vis|1.2.5
twig|wha|1.0.2
jinja|who|0.0.8

</details>

**Comment by alexdima** [comment]
VS Code is not a binary editor, but a code editor, which works more like a text editor.

So when a file is opened, it gets decoded according to the configured encoding (UTF8 by default) to a string. Then, when saving the file, the string is encoded as configured (UTF8 by default) to disk.
