### ISSUE TITLE
format large json

### ISSUE THREAD

**Issue by Mahatoha** [microsoft/vscode#91959]
Issue Type: <b>Bug</b>

1 - open a "big" json file (30000 lines in my case)
2 - Format the file with vs code (alt+shift+f)
3 - VS Code add a closing char at the end ("}" if object, "]" if list)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (4.41GB free)|
|Process Argv|C:\Users\girault\Downloads\contrat_BMCI_3-3-2020 (12).json|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
vscode-lombok|Gab|1.0.1
docthis|joe|0.7.1
Angular-BeastCode|Mik|8.1.2
vscode-language-pack-fr|MS-|1.42.2
vscode-manifest-yaml|Piv|1.15.0
vscode-spring-boot|Piv|1.15.0
material-icon-theme|PKi|4.0.1
java|red|0.57.0
vscode-xml|red|0.10.1
vscode-yaml|red|0.7.2
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6
html-css-class-completion|Zig|1.19.0

</details>

**Comment by weinand** [comment]
Does this happen if you disable all extensions?

**Comment by gjsjohnmurray** [comment]
Looks like a duplicate of #91125

**Comment by weinand** [comment]
This should be fixed in Insiders.
