### ISSUE TITLE
Scrollbar to navigate open file tabs is next to IMPOSSIBLE to use!

### ISSUE THREAD

**Issue by scunliffe** [microsoft/vscode#91952]
Issue Type: <b>Bug</b>

If you routinely have 8+ files open, the tabs at the top (Windows) have a tiny 1-2px scrollbar that only shows on hover just underneath them. Attempting to grip this toolbar is crazy hard vs. dragging the tab or focusing the document.

I would prefer **ANY** UX afordance over this current implementation. I currently have to keep closing files instead to attempt to manage file navigation.

Please add standard < Left, Right > arrows at the end of the tab strip. See the Firefox browser for how to properly implement scroll arrows on tabbars.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (8.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
sort-imports|ama|6.1.0
auto-align|bla|0.0.13
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-ipaddress|Com|1.0.0
vscode-autohotkey-plus|cwe|2.0.2
vs-treeview|DaG|2.7.0
vscode-eslint|dba|2.0.15
vscode-ahk-manager|Den|0.0.18
githistory|don|0.5.2
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
windows-explorer-context-menu|ele|2.0.0
LogFileHighlighter|emi|2.7.1
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
prettier-vscode|esb|3.20.0
vscode-firefox-debug|fir|2.6.1
docker-explorer|for|0.1.6
glitch|gli|0.1.5
beautify|Hoo|1.5.0
launcher|ili|0.0.4
auto-comment-blocks|kev|1.0.1
vscode-gutter-preview|kis|0.25.0
vscode-docker|ms-|0.10.0
mssql|ms-|1.8.0
cordova-tools|msj|1.9.2
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
live-server-preview|neg|0.1.4
indent-rainbow|ode|7.4.0
vscode-jsp|pth|0.0.3
java|red|0.55.1
prettier-now|rem|1.4.9
sonarlint-vscode|Son|1.14.0
open-in-browser|tec|2.0.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
#32192 is an open issue about adding a way to make that horizontal scrollbar easier to grab. Doesn't seem to cover your request for scroll-arrows though.

Do you have a mousewheel? If so, did you discover how this allows you to scroll tabs?

**Comment by scunliffe** [comment]
Thanks @gjsjohnmurray I didn't know about the mousewheel scroll option (handy for docked coding), though I'd still like to see a better option (esp. for laptop use w/ no mouse)... I'll follow the https://github.com/microsoft/vscode/issues/32192 bug to see if there will be a better option going forward.

**Comment by gjsjohnmurray** [comment]
@scunliffe please close this then. And if you want to push for scroll-arrows I suggest you add a comment to that issue.

**Comment by scunliffe** [comment]
Closing as duplicate.
