### ISSUE TITLE
Start using GitHub Releases again

### ISSUE THREAD

**Issue by ffes** [microsoft/vscode#91951]
Could you please create releases on GitHub again? According to https://github.com/microsoft/vscode/releases the last release is from September, which obviously is not true.

The main advantage is that a GitHub user can Watch Releases and get a notification that a new version has been released. IMHO there is no need to copy the full release notes there. Just a link to the release notes will do, as was done with the September Recovery releases.

Note that this is basically a dup of #76146, but after those three September releases the team stopped creating the releases again. And that issue is locked

**Comment by egamma** [comment]
Releases have been updated.
