### ISSUE TITLE
Add the ability to import a list of files from a file

### ISSUE THREAD

**Issue by leon0625** [microsoft/vscode#91957]
I'm a C developer. We have more than 10w files in one project (include Linux kernel code), but there are about 2000 files used for each compilation. I can know the list of these files. I want to import into the workspace once.

For now, I can only use the exclude function to reduce the time spent parsing analysis files, There are too many useless files. It's a bit slow.

**Comment by weinand** [comment]
What do you mean by "I want to import into the workspace once."?
VS Code has no "Import file into workspace" functionality.
