### ISSUE TITLE
Why does Ctrl + Shift + W close the VSCode

### ISSUE THREAD

**Issue by angusfenying** [Microsoft/vscode#9196]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Press down Ctrl + Shift + W
2. Only only all tabs, but also the VSCode application will be closed.

Shouldn't it just close all tabs opened?

**Comment by bpasero** [comment]
@angusfenying did you try configuring keybindings to change that?

**Comment by attilah** [comment]
It is not an issue it is a feature ;-)

Ctrl+W is the standard to close current window (or tab) in MDI.
Ctrl+Shift+W is the standard to close all windows.

It works the same way in Chrome for example.

**Comment by bpasero** [comment]
Closing since this is configurable.

**Comment by angusfenying** [comment]
However, it doesn't close the VSCode if I press Ctrl+W to close the last one opened tab, while Chrome do.
It makes an illusion that Ctrl+W just close a tab, and then Ctrl+Shift+W also should close only tabs, as SHIFT key meas ALL.

**Comment by bpasero** [comment]
Yup, thats another issue  where we have an issue for.
