### ISSUE TITLE
Never stops trying to open a file and then "The window has crashed"

### ISSUE THREAD

**Issue by sebastianbarria** [microsoft/vscode#91960]
Hi Everyone.
Once I opened a CSV file and while trying to open it, my VSCode crashed and I had to reopen.
After that, it never stopped trying to open the same file every time I launch VSCode.
I uninstalled the program and re-installed again (didn't work).
I tried configuring the software to never re-open files (didn't work... it keeps trying to open it).
I tried replacing the csv file with a new one blank (didn't work)
I tried removing the file wich is trying to open (didn't work)
I tried using the Debug Diagnostic Tool but it didn't detected the crash.

The only solution I've found is to open VSCode and quickly go to "explorer" and then click the "open folder" button... I open any folder and it start a new VSCode window... the other one crashes but I can keep working. The next time I open the software it crashes again and so on.

I don't know what else to do. Is there any file or registry wich I could clear or remove so it never try to open that file again?

Thanks!

**Comment by bpasero** [comment]
@sebastianbarria you can always force VSCode to open a specific folder or file by running from the command line and typing "code <folder path>". 

As for the crash: 
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
