### ISSUE TITLE
Ability to filter user-made variables

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#91967]
Often when I'm looking in the Variables View to check multiple variables I've created and I will have to scroll for ages to find one. I don't want to use the filter ability to single out a variable because then other variables that I also want to be looking at will be hidden. I can't use the Watch view to solve my problem either as watching a javascript object with the debug extension I'm using doesn't allow you to see the object's contents, which is obviously ridiculous. I'm aware this would work in nodejs or something else probably but I'm locked into using a certain antiquated debugger.

So I think it would be beneficial for the Variables view to allow the user to filter away all variables except those explicitly declared/initialized inside the current open file, by the click of a button perhaps. This would help prevent users from needing to traverse hundreds of variables they didn't create and have no interest in that were automatically created by the environment. It's also similar to but a faster method of having to type in your variables into the Watch view.

I think this would be especially some nice functionality to add for the smaller files where you just need to quickly see whatever variables you made among the clutter.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
