### ISSUE TITLE
ctrl-pageup/down only inconsistently switching editor tabs

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [microsoft/vscode#91963]
- VSCode Version: January 2020 (1.42)
- OS Version: PopOS 19.10

Steps to Reproduce:

1. open vscode with two editor tabs open
2. hit ctrl-PgUp or ctrl-PgDn

Does this issue occur when all extensions are disabled?: No it does not.

...Only extensions I have enabled (new machine) are: `Python` & `Better TOML`. I'm finding this very hard to reproduce. Sometimes ctrl-PgUp/Dn works as expected, sometimes it doesn't. At first I assumed it must be something wrong with my keyboard, but every time I switch to another application (e.g. web browser) when ctrl-PgUp is not working for switching tabs in vscode it always & immediately works in the browser, so it's not my keyboard...

**Comment by bpasero** [comment]
@MaxPowerWasTaken to clarify, the keybinding works correctly but sometimes stop working?

**Comment by MaxPowerWasTaken** [comment]
Correct. And it seems to be consistently inconsistent. After exiting and re opening vscode several times, I still keep getting the keyboard shortcut working and not working seemingly arbitrarily within each session.

**Comment by bpasero** [comment]
@MaxPowerWasTaken what is this `PopOS 19.10` you are running on? Could that be related?

**Comment by alexdima** [comment]
@MaxPowerWasTaken Can you please check if VS Code always receives the keybindings?

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
