### ISSUE TITLE
Terminals not preserved on reload

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91964]
There are probably a bunch of issues / request for this but I could not find them. Sorry.

Open two terminal tabs. Reload. Now I have 1 terminal tab. I would expect two.

fyi @connor4312 I keep hitting this with the javascript debug terminal since it does not get preserved

**Comment by Tyriar** [comment]
I explored doing this about a year ago and came to the conclusion that trying to retain terminals across reloads like this was going to get too complicated for the setups people want. So I deter to extensions like https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

Keeping the processes alive between reloads is definitely something I hope to do eventually https://github.com/microsoft/vscode/issues/20013
