### ISSUE TITLE
Linux keybinds not observing keyboard layout

### ISSUE THREAD

**Issue by PinkFlufflyLlama** [microsoft/vscode#91968]
- VSCode Version: Insiders 1.43.0-1582938799 && Regular 1.42.1-1581432938
- OS Version: Ubuntu 19.10 and Ubuntu 19.04 // I updated recently to 19.10 and the issue persisted

Steps to Reproduce:

1. In ubuntu settings > languages and region > input sources, add another keyboard, Colemak is the layout that I use
2. attempt to use or set a keybind in vscode, you will find that it still acts like a querty keyboard

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@PinkFlufflyLlama Can you please check https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings and see if any of that applies to you?

**Comment by PinkFlufflyLlama** [comment]
"keyboard.dispatch": "keyCode" works, sorry for the late response @alexdima . Why isn't this the default setting for Linux? Is there some sort of performance impedance?

**Comment by alexdima** [comment]
The `keyboard.dispatch` setting is an emergency setting. It bypasses all of our native node module that reads the keyboard layouts and gives the nativeness of a web app running in a web browser.

Let's track in #24166 .
