### ISSUE TITLE
Port electron menu handling code back to electron core.

### ISSUE THREAD

**Issue by adamulrich** [microsoft/vscode#91970]
VS Code has a great implementation for top level menus; they work as you would expect native menus to work. Unfortunately, this code has not been backported to electron core, leaving other electron apps with a poor menu experience. Basic things like mnemonic support is quite broken. https://github.com/electron/electron/issues/18482. 

Please port this to electron core.

**Comment by sbatten** [comment]
I love the thought but unfortunately this isn't a small amount of work as some of the good functionality is coupled with VS Code specific code. So unfortunately this is out of scope.
