### ISSUE TITLE
Should Debug: commands have Run: sibling commands?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#91978]
- VSCode Version: 1.43 Insiders
- OS Version: Windows 10

With the rename of the Debug view and menu to Run, should the Debug: also be renamed? 
Or should the Debug: commands be left alone for backward compatibility and there be Run: commands for discoverability and parity with the Run menu?

**Comment by weinand** [comment]
Yes, we should keep the "Debug:" but consider to have "Run:" too.

**Comment by isidorn** [comment]
Renaming https://github.com/microsoft/vscode/issues/91975 makes perfect sense and I plan to do this
From this issue I will only rename 
Debug: Run (Start Withtout Debugging) to
Run: Start Without Debugging

If you have other good candidates to rename please let me know.
All new commands that we add we should consider if they should have the Run: or the Debug: prefix
