### ISSUE TITLE
Auto import suggestion is not working only on first suggest.

### ISSUE THREAD

**Issue by ohjeyong** [microsoft/vscode#91974]
- VSCode Version: 1.42.1
- OS Version: Mac 10.15.3

Steps to Reproduce:

1. Type something to import.
2. Vscode suggest some imports but, the only first suggestion doesn't work auto import. From the second suggestions, it works, but only first suggestion doesn't automatically import when I press enter.
3. If I remove last alphabet and type it again, then first suggestion works.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/11625617/75813052-acb0ba80-5dd2-11ea-9204-18d4b2f40825.gif)

My team also get this problem. Not every auto import suggest, but almost 50 ~ 60% of auto import suggest appear this problem.

Does this issue occur when all extensions are disabled?: Yes/No
Yes. I double checked.

**Comment by ohjeyong** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Auto Suggestion NOt working (#90131)](https://www.github.com/microsoft/vscode/issues/90131)

No, this is totally different. My problem is, import suggestion is working but not working only for the first suggestion.

**Comment by PachowStudios** [comment]
Also experiencing this. I have to re-trigger the suggestions to get the import paths to show up. Seems like it started happening after the last update.

```
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by ohjeyong** [comment]
@mjbvz I can't download VS Code insiders. It's download speed is too slow and during download, it failed due to network error.(In chrome and safari) Can you please check? @PachowStudios

**Comment by ohjeyong** [comment]
@mjbvz I test it and the problem is not solved.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11625617/76243054-0f92cd80-627b-11ea-8756-b7441376dad0.gif)

**Comment by mjbvz** [comment]
Can you please share an example project that demonstrates this issue
