### ISSUE TITLE
Command Palette still shows View: Show Debug

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#91975]
- VSCode Version: 1.43 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open Command Palette and filter on view

![image](https://user-images.githubusercontent.com/12818376/75813364-bb509080-5d44-11ea-8d67-742f33a8db85.png)

Should probably say View: Show Run to match new Activity Bar text and view name

**Comment by isidorn** [comment]
For backward compatibility decided to rename this on to
Show Run and Debug
