### ISSUE TITLE
Unable to run tasks

### ISSUE THREAD

**Issue by ronniehicks** [microsoft/vscode#91988]
Issue Type: <b>Bug</b>

Not sure how to reproduce, but I'm unable to run basically any tasks from VSCode. I have tried the insiders build as well. The errors most often seen are:

`The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command echo testing' failed to launch (exit code: {2})`; 

and

`The terminal process terminated with exit code: {0}`

VS Code version: Code - Insiders 1.43.0-insider (3943d614597f9f7c384846613d417e97ea6d5ab4, 2020-03-03T21:20:08.233Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (4.64GB free)|
|Process Argv|--folder-uri file:///src/jessefuckingbaker.visualstudio.com/GuitarScraper/scraper-processor|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.0.29
git-project-manager|fel|1.7.1
camelcasenavigation|map|1.1.1
vscode-azurefunctions|ms-|0.21.0
remote-containers|ms-|0.106.0
remote-wsl|ms-|0.42.3
azure-account|ms-|0.8.8
csharp|ms-|1.21.12
vsliveshare|ms-|1.0.1653
material-icon-theme|PKi|4.0.1
quicktype|qui|12.0.46
</details>

**UPDATE**:
Just tested the same task against the same version with all extensions disabled, same results.

**Comment by alexr00** [comment]
Please share your tasks.json and all settings.json.

**Comment by ronniehicks** [comment]
> Please share your tasks.json and all settings.json.

Will do tonight.

**Comment by ronniehicks** [comment]
tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "clean",
            "command": "dotnet",
            "args": [
                "clean",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "type": "process",
            "problemMatcher": "$msCompile"
        },
        {
            "label": "build",
            "command": "dotnet",
            "args": [
                "build",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "type": "process",
            "dependsOn": "clean",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": "$msCompile"
        },
        {
            "label": "clean release",
            "command": "dotnet",
            "args": [
                "clean",
                "--configuration",
                "Release",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "type": "process",
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "args": [
                "publish",
                "--configuration",
                "Release",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "type": "process",
            "dependsOn": "clean release",
            "problemMatcher": "$msCompile"
        },
        {
            "type": "func",
            "dependsOn": "build",
            "options": {
                "cwd": "${workspaceFolder}/bin/Debug/netcoreapp3.1"
            },
            "command": "host start",
            "isBackground": true,
            "problemMatcher": "$func-watch"
        }
    ]
}
```

.vscode/settings.json
```json
{
    "azureFunctions.deploySubpath": "bin/Release/netcoreapp3.1/publish",
    "azureFunctions.projectLanguage": "C#",
    "azureFunctions.projectRuntime": "~2",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.preDeployTask": "publish"
}
```

user/settings.json
```jsonc
{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.startupEditor": "none",
    "material-icon-theme.showUpdateMessage": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,

    // EDITOR SETTINGS
    "editor.fontSize": 13,
    "editor.fontWeight": "500",
    "editor.fontFamily": "Fira Code, SauceCodePro Nerd Font Mono, Delugia Nerd Font, UbuntuMono Nerd Font Mono, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "editor.formatOnPaste": false,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true,
        "source.fixAll": true,
    },
    "editor.suggestSelection": "first",
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "editor.insertSpaces": true,
    "editor.detectIndentation": false,

    "emmet.showSuggestionsAsSnippets": true,
    "problems.decorations.enabled": true,
    "debug.inlineValues": true,

    // SETTINGS SYNC
    "sync.gist": "c7359002cbd157e21f3d763beefbfb37",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.forceDownload": false,
    "sync.quietSync": false,
    "sync.removeExtensions": true,
    "sync.syncExtensions": true,

    // GIT PLUGINS
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "git.autofetch": true,
    "gitProjectManager.baseProjectsFolders": [
        "~/src",
        "/src"
    ],
    "diffEditor.renderSideBySide": false,

    // TERMINAL
    "terminal.integrated.fontFamily": "SauceCodePro Nerd Font Mono, Delugia Nerd Font, UbuntuMono Nerd Font Mono, Menlo, Monaco, 'Courier New', monospace",
    "terminal.integrated.fontSize": 13,

    // LANGUAGE SETTINGS

    // PYTHON

    // MARKDOWN
    "[markdown]": {
        "editor.wordWrap": "on",
        "editor.quickSuggestions": false,
    },

    // TYPESCRIPT
    "typescript.updateImportsOnFileMove.enabled": "always",
    "[typescript]": {
        "editor.tabSize": 2
    },
    "[javascript]": {
        "editor.tabSize": 2
    },

    // DOTNET
    "dotnet-test-explorer.testProjectPath": "**/*Test*/*.csproj",
    "dotnet-test-explorer.testArguments": "/p:CollectCoverage=true /p:CoverletOutputFormat=\"lcov\" /p:CoverletOutput=\"../reports/\"",

    // JAVA
    "java.configuration.checkProjectSettingsExclusions": false,
    "java.codeGeneration.generateComments": true,
    "java.implementationsCodeLens.enabled": true,
    "java.referencesCodeLens.enabled": true,

    "[jsonc]": {
        "editor.formatOnSave": false
    },

    "coverage-gutters.coverageFileNames": [
        "lcov.info",
        "coverage.info",
        "cov.xml",
        "jacoco.xml",
        "coverage.xml"
    ],
    "python.insidersChannel": "weekly",
    "python.jediEnabled": false,
}
```

**Comment by alexr00** [comment]
Nothing suspicious looking there. I don't see the "echo testing" task you mention. Can you share that? Also, can you try disabling all extensions and see if it still occurs?

**Comment by ronniehicks** [comment]
> Nothing suspicious looking there. I don't see the "echo testing" task you mention. Can you share that? Also, can you try disabling all extensions and see if it still occurs?

Sorry, not getting email notifications here for some reason. Yea, I'll try that tonight. As for the echo testing failure, I removed it after it didn't work.

```jsonc
{
      "type": "shell",
      "command": "echo testing",
      "label": "testing"
}
```

**Comment by alexr00** [comment]
Thanks for the additional testing. I still can't get a repro though. In the integrated terminal can you try the following:
- launch cmd (just run `cmd`)
- run `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command echo testing`. This is the command that the task is running.

What is the output?

**Comment by ronniehicks** [comment]
> What is the output?

`testing`

**Comment by alexr00** [comment]
@Tyriar Do you have any ideas about what could be going on here? @ronniehicks is getting this error when running a very simple task:
`The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command echo testing' failed to launch (exit code: {2})`
 The command doesn't require that anything be on the path: `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command echo testing`
And the exit code looks to be bogus and I don't understand why that could be happening based on the code here: 
https://github.com/microsoft/vscode/blob/2502f01cb4b12a872c8103f56f43684b6653c267/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1058-L1058

**Comment by Joinyy** [comment]
After updating to `1.43` I am also unable to run any shell tasks. Instead it just opens a shell, when exiting the shell it "finishes" the task.

Settings for my integrated terminal:
```json
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.fontFamily": "Fira Mono",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\app\\CMDer\\vsCode.bat"
    ],
```

The task I tested to run:

```json
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello",
            "group": "build",
            "problemMatcher": [],
            "options": {
                "shell": {
                    "executable": "C:\\WINDOWS\\System32\\cmd.exe",
                    "args": []
                }
            }
        }
```

I tried to specify the shell without any commands in the `"option"` setting, as I am using the CMDer init batchfile in my standard VS Code shell settings. But that didn't help either.

What I see in the shell opened by the task:

```
> Executing task: echo Hello <

Microsoft Windows [Version 10.0.17763.1039]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\RJI1SGM\Documents\140_Skripte\testfolder>dir
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 6C74-AE1F

 Verzeichnis von C:\Users\RJI1SGM\Documents\140_Skripte\testfolder

10.03.2020  15:42    <DIR>          .
10.03.2020  15:42    <DIR>          ..
10.03.2020  15:42    <DIR>          .vscode
10.03.2020  15:42                52 test.py
               1 Datei(en),             52 Bytes
               3 Verzeichnis(se), 118.185.291.776 Bytes frei

C:\Users\RJI1SGM\Documents\140_Skripte\testfolder>exit

Terminal will be reused by tasks, press any key to close it.
```

**Comment by alexr00** [comment]
@Joinyy in the future, please open a new issue if it isn't 100% clear that your issue is the same. 

Your task also doesn't work in 1.42 because you don't have any `args` here:
```
            "options": {
                "shell": {
                    "executable": "C:\\WINDOWS\\System32\\cmd.exe",
                    "args": []
                }
            }
```
And it doesn't work without the `options` because you specify args here and they conflict with the args that tasks automatically uses:
```
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\app\\CMDer\\vsCode.bat"
    ],
```
I recommend removing the `options` from your task and setting `"terminal.integrated.automationShell.windows": "cmd.exe"`

**Comment by Joinyy** [comment]
@alexr00 thanks for your recommendation, I'll take a closer look at the issues in the future.

The tasks are working now for me, so something might have changed from 1.42 on as you mentionned.

**Comment by Tyriar** [comment]
These errors are often related to anti-virus software blocking the terminal from being created. Things you can do:

- Try set/unset the windowsEnableConpty setting
- Try trace logging to see if that gives any useful information https://github.com/microsoft/vscode/wiki/Terminal-Issues
- Check devtools for errors

**Comment by ronniehicks** [comment]
> ```js
>  "gitProjectManager.baseProjectsFolders": [
>         "~/src",
>         "/src"
>     ],
> ```

After a little more digging I discovered the issue, and I believe it's been impacting my OmniSharp experience as well. I use Git Project Manager to quickly switch between projects and since I work across Mac and Windows I put both OS locations in the list. The second one, `/src` is for windows and apparently VSCode does not like that path for relative pathing. When I switch it to `C:/src` for the windows path it works fine.

Thanks for the help all! Let me know if you're interested in any of the logs or anything else.
