### ISSUE TITLE
vscode.workspace.getConfiguration ('tasks') cannot get user level task

### ISSUE THREAD

**Issue by actboy168** [microsoft/vscode#91986]
- VSCode Version: 1.42.1

If tasks.json already exists in the workspace folder, vscode.workspace.getConfiguration ('tasks') can only get tasks.json in the workspace folder. Only when tasks.json does not exist in the workspace folder, vscode.workspace.getConfiguration ('tasks') can get user level tasks.

**Comment by gjsjohnmurray** [comment]
Can you use vscode.tasks.fetchTasks to do that?

**Comment by gjsjohnmurray** [comment]
Or maybe use inspect() in place of get() on the WorkspaceConfiguration returned from getConfiguration

**Comment by actboy168** [comment]
> Can you use vscode.tasks.fetchTasks to do that?

I use both vscode.tasks.fetchTasks and vscode.workspace.getConfiguration ('tasks'). The reason is # 67095.

> Or maybe use inspect() in place of get() on the WorkspaceConfiguration returned from getConfiguration

This can solve my problem, thank you very much.

**Comment by alexr00** [comment]
@gjsjohnmurray thanks for responding! Yes, `inspect()` is the correct/intended way to get user tasks.
