### ISSUE TITLE
Feature Request: Left Side Panel showing Opened Folder should have a shortcut to launch File Explorer and Command-line tool

### ISSUE THREAD

**Issue by paritosh149** [Microsoft/vscode#9198]
- VSCode Version: 1.3.1
- OS Version: Windows 7 SP1

Feature Request:
Left Side Panel showing Opened Folder should have a shortcut to launch File Explorer and Command-line tool having Opened Folder as present working directory.

**Comment by weinand** [comment]
@paritosh149 since VS Code has a large of command, we cannot assign keyboard shortcuts to all of them. Please define your own shortcuts (Preferences > Keyboard Shortcuts). 

'Open in Command Prompt' does open the workspace folder in a command prompt.

**Comment by paritosh149** [comment]
Yeah. I got it. Command Palette... has the one I wish for. Thanks
