### ISSUE TITLE
Suggestions does not update when there are no matched characters

### ISSUE THREAD

**Issue by aldwong** [microsoft/vscode#91983]
- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new python file in vs code
2. Press Ctrl + Space to trigger suggestions
3. Start typing in letters that doesn't match many of the suggestions ( For example: qqqq)
4. Suggestions list does not update to reflect suggestions to what is currently typed

Expected: the suggestions should hide or display "No Suggestions."

Screenshot of issue:
![image](https://user-images.githubusercontent.com/59587663/75837077-a857b380-5d78-11ea-8a8f-90c7c375c91c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Pls file against Python extension

**Comment by aldwong** [comment]
@weinand  This issue is also can be reproduced with other types of files as well like:  C#, Typescript, JavaScript, etc. 
Should I file a issue for each one of these extensions?

**Comment by aldwong** [comment]
Hi @weinand 

It appears that this issue is not caused by the python extension as detailed in the comment linked below.
https://github.com/microsoft/vscode-python/issues/10436#issuecomment-596810525

The suggestion issue was reproducible in C# and JavaScript as mentioned by @kimadeline.
Could this issue be reopened?

**Comment by jrieken** [comment]
<img width="719" alt="Screenshot 2020-03-10 at 08 39 08" src="https://user-images.githubusercontent.com/1794099/76289972-9f03a500-62aa-11ea-8825-b27307d754cb.png">

Does not reproduce for me, please add repro steps that allow me to

**Comment by kimadeline** [comment]
Behaviour 1 (the letter doesn't show up in any of the suggestions):
- Create a new C file in vs code
-  Press Ctrl + Space to trigger suggestions
- Start typing in letters that don't match any of the suggestions ( For example: yyyy)
- Suggestions list does not update to reflect suggestions to what is currently typed

Example:

![suggestions_no_letter](https://user-images.githubusercontent.com/51720070/76341179-e80f2580-62b9-11ea-9a2f-82692a059ef6.gif)

Behaviour 2 (some of the suggestions contain the letter being typed):
- Create a new JS file in vs code
-  Press Ctrl + Space to trigger suggestions
- Start typing in letters that exist in some of the suggestions ( For example: qqqq)
- Suggestions list does not update to reflect suggestions to what is currently typed

Example:

![suggestions_existing_letter](https://user-images.githubusercontent.com/51720070/76341283-0b39d500-62ba-11ea-9983-d34c62f9c300.gif)

**Comment by jrieken** [comment]
Thanks for clarifying

**Comment by jrieken** [comment]
This is actually the designed behaviour - let me explain what's happening: There are two modes of IntelliSense - "auto" and "manual". 
1. "auto" is IntelliSense-as-you-type and others,
1. "manual" is explicit IntelliSense request by a user gesture. like Cmd+Space. 

In auto-mode IntelliSense hides when there are no more matches, in manual mode we don't do that. The reasoning is that you explicitly requested IntelliSense and we don't just wanna take it away from you, e.g. in the screen shot below I am in manual mode, typed `a3` (misspell of `ae`) and the widget is now "frozen", the last good state is shown but no more filtering is happening. This allows you select an item or dismiss the completions but we don't wanna take them away from you automatically.

<img width="324" alt="Screenshot 2020-03-10 at 18 58 56" src="https://user-images.githubusercontent.com/1794099/76344045-34318880-6301-11ea-85ba-5841457e1267.png">
