### ISSUE TITLE
Make location of * .sock files configurable

### ISSUE THREAD

**Issue by eszlari** [microsoft/vscode#91984]
Under Linux, to find other running instances, VSCode uses `$XDG_RUNTIME_DIR/vscode-${somehash}-${version}-shared.sock`. This doesn't work under Flatpak, because `$XDG_RUNTIME_DIR` is unique to each flatpak sandbox. Other apps use `$TMPDIR`, which can be set to a usable location.

Related flatpak issue: https://github.com/flathub/com.visualstudio.code/issues/75

**Comment by joaomoreno** [comment]
You can simply configure the `--user-data-dir`

**Comment by eszlari** [comment]
This doesn't work:
```
$ mkdir test_dir
$ code --user-data-dir test_dir
$ find test_dir -name '*sock*'
test_dir/CachedData/0ba0ca52957102ca3527cf479571617f0de6ed50/socksclient-6a388774eb91a64537954a35624201a0.code
```
