### ISSUE TITLE
Terminal gets messed up and needs restarting after logging back from suspended machine on Ubuntu

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#91996]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Open an internal terminal in VS Code
2. Suspend machine
3. Log back in
4. See terminal being empty or with random chars and cursor placed at some random position. Unable to type in anything

Does this issue occur when all extensions are disabled?: Yes

**Comment by slhck** [comment]
I am experiencing the same issue with Ubuntu 19.10 and VSCode 1.43.2.

**Comment by Tyriar** [comment]
Can you share a screenshot, your settings.json file and let me know whether pressing ctrl++ then ctrl+- fixes the issue?

**Comment by slhck** [comment]
![image](https://user-images.githubusercontent.com/582444/78528980-f3823d80-77e0-11ea-8719-b2e0bbc2a09a.png)

This is a screenshot of a window (that had three terminals open), after wake from suspend. For some reason, background colors and unicode symbols are rendered. The terminals are all responsive, but I can't see any text I'm typing. Note that typing `reset` in the terminals does not change anything.

Pressing `Ctrl-+` and `Ctrl--` indeed fixes the issue.

These are my [`settings.json`](https://gist.githubusercontent.com/slhck/5a5dc06d77046a894025d593447bfdc8/raw/763c3f59c85524c39986c3d78bd3dede3b5ad66c/settings.json).
