### ISSUE TITLE
Creating multiple directories with multiple intermediate subdirectories

### ISSUE THREAD

**Issue by behrangsa** [microsoft/vscode#91991]
I think somewhere I read this feature exists but I can't seem to find it.

Allow creating multiple directories with multiple intermediate directories in one go. 

For example, allow creating this structure in one go:

```
src
   main
      java
      resources
   test
      java
      resources
```

with a syntax like this:

```
src/{main,test}/{java,resources}
```

from the explorer.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
