### ISSUE TITLE
VUE项目自动保存格式化问题

### ISSUE THREAD

**Issue by lsm2039** [microsoft/vscode#91994]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.
![image](https://user-images.githubusercontent.com/25899640/75851873-b4e61580-5e25-11ea-8cc6-9dfce2156710.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JS-mark** [comment]
set false
![image](https://user-images.githubusercontent.com/31335385/76499025-f0618f00-6478-11ea-8cfd-39e8f156be02.png)
