### ISSUE TITLE
Close non existing files

### ISSUE THREAD

**Issue by wissog** [microsoft/vscode#91999]
Issue Type: <b>Bug</b>

When you move from branch1 to branch2 and there are files which were added on branch1 but not exist on branch2 - these file windows have to be closed by vs code.

now it behaves strangely and unexpectedly

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
All-Autocomplete|Ati|0.0.23
vscode-typescript-refactors|can|0.0.22
gitignore|cod|0.6.0
macros|ctf|0.0.4
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
lintlens|ghm|2.7.0
todo-tree|Gru|0.0.169
vscode-dimmer-block|ima|2.2.0
easy-snippet|inu|0.1.7
vscode-essentials|jab|1.4.0
hungry-delete|jas|1.6.0
vscode-text-pastry|jkj|1.2.0
vscode-format-context-menu|lac|1.0.4
metago|met|3.2.0
git-graph|mhu|1.21.0
Angular-BeastCode|Mik|8.1.2
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
abracadabra|nic|3.2.1
vscode-jscpd|pau|0.3.4
vscode-versionlens|pfl|0.24.0
subtle-brackets|raf|3.0.0
typescript-hero|rbb|3.0.0
rewrap|stk|1.9.1
control-snippets|svi|1.7.4
vscodeintellicode|Vis|1.2.5
gistfs|vsl|0.0.60

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Configurable via `workbench.editor.closeOnFileDelete`
