### ISSUE TITLE
Unable to launch application on OSX

### ISSUE THREAD

**Issue by ElliotChong** [Microsoft/vscode#92]
When doing a fresh download, copying `Visual Studio Code.app` to `/Applications`, and executing I receive the error: `The application “Visual Studio Code.app” can’t be opened.`

Upon looking at the console logs I see the following errors:
```
11/18/15 11:44:47.046 lsd[371]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
11/18/15 11:44:47.049 lsd[371]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
11/18/15 11:44:47.058 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000046.Atom[62821]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/Visual Studio Code.app/Contents/MacOS/Atom
11/18/15 11:44:47.058 Finder[749]: spawn_via_launchd() failed, errno=111 label=[0x0-0x11dc1db].com.github.atom-shell path=/Applications/Visual Studio Code.app/Contents/MacOS/Atom flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
11/18/15 11:44:47.058 Finder[749]: spawn_via_launchd() failed, errno=111 label=[0x0-0x11dc1db].com.github.atom-shell path=/Applications/Visual Studio Code.app/Contents/MacOS/Atom flags=1
11/18/15 11:44:47.061 lsd[371]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
```

It appears that the App is looking for `/Applications/Visual Studio Code.app/Contents/MacOS/Atom` when the correct path should be `/Applications/Visual Studio Code.app/Contents/MacOS/Electron`

I'm attempting to upgrade from the original beta, is there something else that needs to be removed to properly make the transition besides deleting the old App in `/Applications`?

**Comment by ElliotChong** [comment]
I renamed `/Applications/Visual Studio Code.app/Contents/MacOS/Electron` to `/Applications/Visual Studio Code.app/Contents/MacOS/Atom` which then caused a new "broken" error to occur. I then deleted the `.app` again and copied it fresh from the zip and it seems to be functioning fine now.

**Comment by TuiKiken** [comment]
The same problem. @ElliotChong solution work fine, thanks.

**Comment by matthewkimber** [comment]
Same problem here.

**Comment by indrasantosa** [comment]
Same problem, worked for me as well. Thanks!

**Comment by jackd942** [comment]
Thanks for the workaround!

**Comment by dpnevmatikos** [comment]
@ElliotChong solution works fine!

**Comment by yoeun** [comment]
It's 9 Feb 2016 and this problem still exists. Fortunately, this solution still works. Thanks!

**Comment by dspork** [comment]
Thanks, the above workaround also worked for me!

**Comment by cheizer** [comment]
Issue is still occurring with 0.10.11.

I simply added a symlink and that works

`ln -s /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Atom`

**Comment by Tyriar** [comment]
@joaomoreno is this something we need to fix?

**Comment by joaomoreno** [comment]
First time I see this, thanks for the dig. I can look into it.

**Comment by tristian2** [comment]
tried chezier's suggestion which seems reasonable, but i still get this..

freds-MacBook-Pro:MacOS userbob$ code /
  File "<string>", line 1
    import os,sys; print os.path.realpath(sys.argv[1])
                          ^
SyntaxError: invalid syntax
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory
freds-MacBook-Pro:MacOS userbob$ code .
  File "<string>", line 1
    import os,sys; print os.path.realpath(sys.argv[1])
                          ^
SyntaxError: invalid syntax
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory

**Comment by tristian2** [comment]
i got it working on my mac... i corrected the python path in the bash file

open -e /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() { **/usr/bin/python** -c "import os,sys; print os.path.realpath(sys.argv[1])" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?

then i installed the Electron app from http://macappstore.org/electron/

i can now run code . from my app folder neatly

**Comment by alapolloni** [comment]
This work around is easy (but still weird):   http://apple.stackexchange.com/questions/214879/visual-studio-code-app-wont-run-from-applications-folder

**Comment by joaomoreno** [comment]
@tristian2 is referring to #3790

**Comment by joaomoreno** [comment]
@cheizer @alapolloni @dspork @yoeun What are the contents of `/Applications/Visual\ Studio\ Code.app/Contents/Info.plist` in your case?

I believe this all comes from people that had a *very* old version of Code (in which the executable was `Atom`) and got upgraded to a more recent one (in which the executable is `Electron`) and the update framework failed to do the move properly.

**Comment by alapolloni** [comment]
@joaomoreno  the modified date/time is from when I ran the workaround...I didn't save a copy of the eariler one.  (in fact, it could be that I had an old version as this wasn't on my main work machine). As requested: [Info.zip](https://github.com/Microsoft/vscode/files/221162/Info.zip)

**Comment by cheizer** [comment]
Here is the contents of my Info.plist. I should note that this was recent download, like 2 weeks ago.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>BuildMachineOSBuild</key>
    <string>14B25</string>
    <key>CFBundleDisplayName</key>
    <string>Code</string>
    <key>CFBundleExecutable</key>
    <string>Electron</string>
    <key>CFBundleIconFile</key>
    <string>Code.icns</string>
    <key>CFBundleIdentifier</key>
    <string>com.microsoft.VSCode</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>Code</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>0.10.11</string>
    <key>CFBundleVersion</key>
    <string>0.10.11</string>
    <key>DTSDKBuild</key>
    <string>14D125</string>
    <key>DTSDKName</key>
    <string>macosx10.10</string>
    <key>DTXcode</key>
    <string>0640</string>
    <key>DTXcodeBuild</key>
    <string>6E35b</string>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.developer-tools</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.8.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSMainNibFile</key>
    <string>MainMenu</string>
    <key>NSPrincipalClass</key>
    <string>AtomApplication</string>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright (C) 2015 Microsoft. All rights reserved</string>
    <key>CFBundleDocumentTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeName</key>
        <string>Visual Studio Code document</string>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleTypeOSTypes</key>
        <array>
          <string>TEXT</string>
          <string>utxt</string>
          <string>TUTX</string>
          <string>****</string>
        </array>
        <key>CFBundleTypeExtensions</key>
        <array>
          <string>ascx</string>
          <string>asp</string>
          <string>aspx</string>
          <string>bash</string>
          <string>bash_login</string>
          <string>bash_logout</string>
          <string>bash_profile</string>
          <string>bashrc</string>
          <string>bat</string>
          <string>bowerrc</string>
          <string>c</string>
          <string>cc</string>
          <string>clj</string>
          <string>cljs</string>
          <string>cljx</string>
          <string>clojure</string>
          <string>cmd</string>
          <string>coffee</string>
          <string>config</string>
          <string>cpp</string>
          <string>cs</string>
          <string>cshtml</string>
          <string>csproj</string>
          <string>css</string>
          <string>csx</string>
          <string>ctp</string>
          <string>cxx</string>
          <string>dockerfile</string>
          <string>dot</string>
          <string>dtd</string>
          <string>editorconfig</string>
          <string>edn</string>
          <string>eyaml</string>
          <string>eyml</string>
          <string>fs</string>
          <string>fsi</string>
          <string>fsscript</string>
          <string>fsx</string>
          <string>gemspec</string>
          <string>gitattributes</string>
          <string>gitconfig</string>
          <string>gitignore</string>
          <string>go</string>
          <string>h</string>
          <string>handlebars</string>
          <string>hbs</string>
          <string>hh</string>
          <string>hpp</string>
          <string>htm</string>
          <string>html</string>
          <string>hxx</string>
          <string>ini</string>
          <string>jade</string>
          <string>jav</string>
          <string>java</string>
          <string>js</string>
          <string>jscsrc</string>
          <string>jshintrc</string>
          <string>jshtm</string>
          <string>json</string>
          <string>jsp</string>
          <string>less</string>
          <string>lua</string>
          <string>m</string>
          <string>makefile</string>
          <string>markdown</string>
          <string>md</string>
          <string>mdoc</string>
          <string>mdown</string>
          <string>mdtext</string>
          <string>mdtxt</string>
          <string>mdwn</string>
          <string>mkd</string>
          <string>mkdn</string>
          <string>ml</string>
          <string>mli</string>
          <string>nqp</string>
          <string>p6</string>
          <string>php</string>
          <string>phtml</string>
          <string>pl</string>
          <string>pl6</string>
          <string>pm</string>
          <string>pm6</string>
          <string>pod</string>
          <string>pp</string>
          <string>profile</string>
          <string>properties</string>
          <string>ps1</string>
          <string>psd1</string>
          <string>psgi</string>
          <string>psm1</string>
          <string>py</string>
          <string>r</string>
          <string>rb</string>
          <string>rhistory</string>
          <string>rprofile</string>
          <string>rs</string>
          <string>rt</string>
          <string>scss</string>
          <string>sh</string>
          <string>shtml</string>
          <string>sql</string>
          <string>svg</string>
          <string>svgz</string>
          <string>t</string>
          <string>ts</string>
          <string>txt</string>
          <string>vb</string>
          <string>wxi</string>
          <string>wxl</string>
          <string>wxs</string>
          <string>xaml</string>
          <string>xml</string>
          <string>yaml</string>
          <string>yml</string>
          <string>zsh</string>
        </array>
        <key>CFBundleTypeIconFile</key>
        <string>code_file.icns</string>
      </dict>
    </array>
  </dict>
</plist>
```

**Comment by joaomoreno** [comment]
@alapolloni @cheizer Both your files are pointing to an `Electron` executable file. It makes no sense that OS X is looking for an `Atom` executable.

**Comment by alapolloni** [comment]
@joaomoreno I'll grab the plist from before the workaround from my backup when I'm back home.

**Comment by alapolloni** [comment]
@joaomoreno I checked and the info.plist was in fact from April 13th.(before the install of the new Code)

**Comment by joaomoreno** [comment]
And what does the `CFBundleExecutable` value have?

**Comment by Oceanswave** [comment]
+1

**Comment by joaomoreno** [comment]
This is so strange. Like [OS X caches the executable name somewhere](https://discussions.apple.com/thread/1496021?start=0&tstart=0)...

**Comment by alapolloni** [comment]
@joaomoreno 
    <key>CFBundleExecutable</key>
    <string>Electron</string>

**Comment by loverde** [comment]
I had the same issue yesterday upgrading from an ancient version to the latest 1.0.0 version.  It worked with all names except the old /Applications/Visual Studio Code.app name.  Taking a queue from the comment about OS X caching the plist information, I just rebooted my Mac and it worked.  So it's probably related to the cfsprefsd cache and I could have probably killed that process to avoid a reboot.  But the reboot worked and I'd recommend that for anyone having this issue as a workaround.

**Comment by aguevara716** [comment]
I just attempted to upgrade my Visual Studio Code to v1.10, but I kept getting this error. I was originally unzipping the archive using Stuffit Expander 16.0.5 from the Mac App Store when this happened. I don't know what possessed me to try it, but I unzipped the archive using the built-in Archive Utility and guess what? It worked fine after that.

**Comment by joaomoreno** [comment]
Closing the issue, since there seems to be nothing we can do in code. Workarounds and fixes found in comments.

**Comment by RTirumala** [comment]
This worked for me also. thanks a lot.

**Comment by cynhard** [comment]
All methods used, vs code still cannot be started, my system is osx

**Comment by rdandy** [comment]
@ElliotChong  Save my day! Thanks!

**Comment by pritibiyani** [comment]
@ElliotChong 
This might sound little stupid, but which `.app` folder are we referring to here? 
@yoeun 
Which `zip` are we referring to?

**Comment by yoeun** [comment]
@pritibiyani The `Visual Studio Code` app bundle in your root `Applications` folder on your Mac. If you view it in terminal, it can be found at `/Applications/Visual Studio Code.app`. If you view it in Finder, most likely you won't see a `.app` extension. 

1. Do the `Electron` to `Atom` for the `Visual Studio Code` app already installed on your computer. 
2. Open the `Visual Studio Code` app and see a new error
3. Download new version of Visual Studio Code from website. This will be a zip file
4. Unpack that zip and save the new `Visual Studio Code` app to `Applications`. This will replace the old one. 
4. Open the `Visual Studio Code` app from `Applications`. It should now work.

**Comment by pritibiyani** [comment]
@yoeun Thanks for the awesome explanation! Its working now. 👍

**Comment by luiz-c** [comment]
I had this problem and I did the following:

From terminal, run code as sudo.
It'll prompt that you shouldn't use as root. Close code and open it without sudo, it's supposed to open normally. (Worked for me)

The reason that the application wasn't opening previously is that the application had no permission to create an entry in the Cache data folder. This is probably related with the application update but I'm not sure of this.

Hope this help.
