### ISSUE TITLE
New release chews CPU and puts weird squiggles in JavaScript code

### ISSUE THREAD

**Issue by jwulf** [Microsoft/vscode#920]
![screen shot 2015-12-02 at 10 33 10 pm](https://cloud.githubusercontent.com/assets/406975/11530990/11334704-9945-11e5-8bc4-b3fa3323d91e.png)

**Comment by jrieken** [comment]
@jwulf What do the squiggles message read when you hit F8 to jump to them? Also, do you have some JS linter installed?

**Comment by jrieken** [comment]
Please provide the necessary details
