### ISSUE TITLE
Adopt native iterator in tree/list land

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#92000]
This is a continuation of https://github.com/microsoft/vscode/issues/90676.

We now have ES6 everywhere and with that comes native iteration protocol, generators, and yield.  Our custom version of `Iterator<E>` is pretty compatible and often it's enough to remove the import and instead implement the native iterator. Tho, rewriting an iterator to using yield often reduces complexity.

The goal of this issue is to not have custom interfaces for Iterator anymore but to keep our iteration utils. I have also added a [`Iterable`](https://github.com/microsoft/vscode/blob/18945092df3d0c16af75ff9befc62eff70d80129/src/vs/base/common/iterator.ts#L37) util which works on iterables - which is often more handy than working with an iterator directly.

**Comment by jrieken** [comment]
List of consumers of our custom `Iterator` interface

```
- [ ] src/vs/workbench/contrib/timeline/browser/timelinePane.ts 
- [ ] src/vs/workbench/contrib/search/browser/searchView.ts 
- [ ] src/vs/workbench/contrib/scm/browser/repositoryPane.ts 
- [ ] src/vs/workbench/contrib/preferences/browser/tocTree.ts 
- [ ] src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts 
- [ ] src/vs/workbench/contrib/markers/browser/markersView.ts 
- [ ] src/vs/base/test/common/iterator.test.ts 
- [ ] src/vs/base/test/browser/ui/tree/objectTreeModel.test.ts 
- [ ] src/vs/base/test/browser/ui/tree/objectTree.test.ts 
- [ ] src/vs/base/test/browser/ui/tree/indexTreeModel.test.ts 
- [ ] src/vs/base/test/browser/ui/tree/compressedObjectTreeModel.test.ts 
- [ ] src/vs/base/common/resourceTree.ts 
- [ ] src/vs/base/common/iterator.ts 
- [ ] src/vs/base/browser/ui/tree/tree.ts 
- [ ] src/vs/base/browser/ui/tree/objectTreeModel.ts 
- [ ] src/vs/base/browser/ui/tree/indexTreeModel.ts 
- [ ] src/vs/base/browser/ui/tree/indexTree.ts 
- [ ] src/vs/base/browser/ui/tree/dataTree.ts 
- [ ] src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts 
- [ ] src/vs/base/browser/ui/tree/asyncDataTree.ts 
```

**Comment by joaomoreno** [comment]
You're getting me excited here.

**Comment by jrieken** [comment]
Just fyi that I have added [`Iterable`](https://github.com/microsoft/vscode/blob/98c180c5eaed682341257ae793712eb00c05487d/src/vs/base/common/iterator.ts#L37) which better with the new world than `Iterator`

**Comment by joaomoreno** [comment]
Stop it!!
