### ISSUE TITLE
Show parent folder for recent workspaces in taskbar icon context menu

### ISSUE THREAD

**Issue by SimonG96** [microsoft/vscode#92003]
When working with SVN you usually have a `trunk` folder that contains your workspace. When working with multiple projects all you can see in the context menu of the taskbar icon is multiple trunk folders:

![image](https://user-images.githubusercontent.com/21110158/75864184-ebaa3480-5e01-11ea-99c0-45f57f85334d.png)

Without knowing the parent folder the only way to find out which workspace you want is to hover over and wait for the mouse over.

It would be great if the parent folder of a recent workspace would be shown in the context menu so that you could quickly see to which project it belongs.

**Comment by weinand** [comment]
/needsMoreInfo
I don't understand your setup. Are you using any extensions? 
"Context menu of the taskbar icon": what taskbar icon?

**Comment by SimonG96** [comment]
@weinand: With context menu of the taskbar icon I mean the menu that opens when you right click on the Visual Studio Code Icon in the windows taskbar or in the windows start menu.

This is not related to any extension.

**Comment by weinand** [comment]
Oh, you are on Windows. How should I know...
(Please read and follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines)
