### ISSUE TITLE
CSS Class Completion Extension locks up whole of VS Code v1.3 or v1.3.1

### ISSUE THREAD

**Issue by Howshall** [Microsoft/vscode#9200]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Install previously good working extension https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion 
2. Open a folder of HTML/CSS/JS project or just an HTML file to trigger 'HTML CSS Class Completion: Fetching CSS rules from CSS files, please wait.' extension running message.
3. Shortly after about 80% of the time the whole of VS Code main window will become unresponsive. Not able to scroll opened file, move text cursor or click on any VS Code UI elements or Explorer Tree. Only elements that still respond are top File, Edit, View, Goto, Help menu dropdowns.

Issue only started happening with VSCode v1.3.0, still present with VSCode v.1.3.1 even after uninstalling and re-installing extension.

Not just myself getting this issue, as can be seen by new 1 star reviews being left at bottom User Reviews section for extension at https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion

**Comment by weinand** [comment]
dup of https://github.com/Zignd/HTML-CSS-Class-Completion/issues/22

**Comment by Howshall** [comment]
@weinand Are you therefore happy that this VSCode lockup behaviour is solely down to this 1x extension, not a wider extensions issue that was brought on by significant extension changes in v1.3?

I wasn't sure whether other extensions might be having the same problem? Hence my post here for VSCode devs to review (as well as specifically looking to highlight issue to specific CSS Class Completion extension 3rd party dev)

**Comment by weinand** [comment]
@Howshall I'm not (yet) seeing a wide-spread issue here. 
We (VS Code) do not have enough resources to analyse all extension issues in order to rule out that VS Code is the culprit. So if extension issues are filed against VS Code, we normally move them to the individual extensions first. If their analysis shows that the issue is a VS Code issue, we will get the issue back anyways.

**Comment by Howshall** [comment]
Thanks, that strategy does make sense. Glad you're not currently seeing any widespread extension issues from v1.3 changes. I'll try some alternate CSS class completion extensions in the meantime and let you know if I find similar problems across more than 1 extension.

**Comment by weinand** [comment]
@Howshall thanks for your understanding and support.

**Comment by Howshall** [comment]
@weinand Just to let you know it appears that completely separate coded https://marketplace.visualstudio.com/items?itemName=AndersEAndersen.html-class-suggestions extension also locks up VS Code v1.3.1 on attempting to parse CSS styles for class completion suggestion (a pretty essential missing feature from VS Code's otherwise excellent HTML/CSS intelisense features)

I can confirm that a derivative of Zignd's original extension https://marketplace.visualstudio.com/items?itemName=AndersEAndersen.html-class-suggestions also causes same VS Code lockup problem in v1.3.1

**Comment by weinand** [comment]
@aeschli are you aware of any issues in this area?

**Comment by aeschli** [comment]
Looking at the code of the extensions, they both are not affected by the latest changes to the vscode css/less/sass language mode as they don't make use of it.
Both search the workspace for css files (using `workspace.findFiles`) but use an external 'css' node_modules library to parse the files.
It would be great if the authors can track down the issue. If it has to do with a change in workspace.findFiles, then we'd be happy to look at it.

**Comment by Howshall** [comment]
Thanks for your initial investigations @aeschli (and @weinand referral) I'll try to make contact with the Andersen extension author. 

But I can confirm Zignd's original CSS Class completion extension had no issues with VSCode lockup in any previous version of VS Code before v1.3 and I've been using it almost daily since 3rd May this year without any change to my PC install. 

So there has been a definitely change in behaviour of these CSS class extensions in v1.3.0 and still v1.3.1

Let me know if there is any debug or error info I can try to collect for you as the problem is easy to replicate my end if I re-install the extension. At the moment I've had to uninstall to make VS Code usable.

**Comment by Howshall** [comment]
Hi @aeschli and @weinand, it looks like Andersea author of alternative HTML Class Suggestions Extension, that had the same VS Code lockup problem as Zignd's extension under VS Code v1.3+ has found the root cause of this problem. Thought you'd appreciated the heads up on his findings which seem to be due to slow performance of a VS Code API (which I guess must have got slower in v1.3+)  https://github.com/andersea/HTMLClassSuggestionsVSCode/issues/1#issuecomment-234101402
