### ISSUE TITLE
Pick string input cannot be canceled.

### ISSUE THREAD

**Issue by karol57** [microsoft/vscode#92009]
Issue Type: <b>Bug</b>

Hi,
I have the following input defined for the task
```
{
    "id": "component",
    "description": "Which component do you want to build?",
    "type": "pickString",
    "options": [ "XXX", "YYY", "ZZZ" ],
    "default": "XXX"
}
```
and in task I'm using
``` "command": "make build${input:component}exe" ```

When the *"Which component do you want to build?"* dialog is shown and I press <kbd>ESC</kbd> key the VS Code runs following command:
``` make buildexe ```. 

I think that default behavior should be canceling the task.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

**Comment by alexr00** [comment]
I can't reproduce this issue. When I have a pickString input in a task and I use ESC on the picker for the pickString, the task doesn't run. Can you please provide a full copy+pastable example where you see the issue?
