### ISSUE TITLE
Always pop up a messagebox with unins000.exe

### ISSUE THREAD

**Issue by AJLu-AMAT** [microsoft/vscode#92007]
- VSCode Version: newest version
- OS Version: win10

Steps to Reproduce:

1. After install the VScode, it will pop-up message box with 
C:/Program Files/Microsoft VS Code/unins000.exe
Ann error occurred while trying to create a file in destination directory: Access is denied.
Please Retry to try again. Ignore to skip this file (not recommended) or abort to cancel installation

Does this issue occur when all extensions are disabled?:  No

**Comment by weinand** [comment]
You said:
> Does this issue occur when all extensions are disabled?: No

Please find out what extension is doing this.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
