### ISSUE TITLE
VS-Code pollutes source code directory

### ISSUE THREAD

**Issue by Smit-tay** [microsoft/vscode#92013]
VS Code adds undesired files into the source code directory of "projects" added to a workspace.
(e.g.  workspaces.json, .vscode, ...)

Perhaps I have the nomenclature wrong, but, VS Code own documentation uses the word "workspace" inconsistently so you'l have to forgive me.

There is no reason for VS Code to create files or directories, whether they are hidden or not, in my project's source tree.  All of this information should be stored in a meaningful way under the user's configuration location (e.g. - linux:  $HOME/.vscode/workspace_a, $HOME/.vscode/workspace_b, etc..)

**Comment by bpasero** [comment]
This is probably getting better once we support workspace settings from outside the workspace.

**Comment by pkruk2** [comment]
On the hand, having config files in your source code directory allows the files to be commited into scm and shared with other people. So while I understand that this is not everyone wants, I hope this feature stays as an option. Not sure if I'd prefer it to be default or not.

**Comment by diminutivesloop** [comment]
@bpasero Is there an issue for that feature I can subscribe to? I'd love to know when it's ready to go.

**Comment by sandy081** [comment]
/duplicate

https://github.com/Microsoft/vscode/issues/40233

**Comment by Smit-tay** [comment]
> On the hand, having config files in your source code directory allows the files to be commited into scm and shared with other people. ...

You could just as easily share your settings when kept separate.  Maybe it's one additional step.
