### ISSUE TITLE
[Really sorry for my bothering again.]  My last issue about my user's snippets didn't trigger any snippets wasn't solved.

### ISSUE THREAD

**Issue by LongyuanCode** [microsoft/vscode#92018]
I've put every details about the problem i am facing on [my locked issue](https://github.com/microsoft/vscode/issues/92005)
**'Hope the assignee read _step 5_ in my locked issue.'**
**'Hope the assignee read _step 5_ in my locked issue'**
**'Hope the assignee read _step 5_ in my locked issue'**
_**And it would be nice of you to be patient, thanks.**_

- It's odd that when i change my `language model` to JavaScript all my 'user's snippets' work, but They don't when my `language model` is Markdown. (I've writen `markdown` in `"scope":`.)
![image](https://user-images.githubusercontent.com/37867843/75893999-8a6c7a80-5e6e-11ea-89c4-e1d1bca28e68.png)
![image](https://user-images.githubusercontent.com/37867843/75894141-bf78cd00-5e6e-11ea-9a6d-4545ceba76e1.png)

Before all of my 2 issues, I also read 2 web pages below carefully but didn't make it to solve the problem.  It seems that my issue is not singular.
[https://github.com/microsoft/vscode/issues/88129](https://github.com/microsoft/vscode/issues/88129)
[https://stackoverflow.com/questions/44321000/visual-studio-code-user-snippets-not-working/48119011](https://stackoverflow.com/questions/44321000/visual-studio-code-user-snippets-not-working/48119011)

**Comment by jrieken** [comment]
Please add a comment to the original issue then
