### ISSUE TITLE
Avoid new files to default to any language

### ISSUE THREAD

**Issue by gennaro-tedesco** [microsoft/vscode#92010]
- VSCode Version: 1.42
- OS Version: MacOs Catilina 10.15.1

Steps to Reproduce:

1. have an open file with an extension
2. create a new blank file which defaults to abovementioned extension

since the January 2020 release, empty new files default to whichever language it is you are using already; apparently, this behaviour can be cured by 
```
"files.defaultLanguage": <extension>
```
to force an extension for new files; however, such option either does not work the way it should, or its grammar is quite obscure - at least for default plain text. Besides the fact that initialising an empty file to another language should **not** be the default - the user should not have to force back a natural behaviour (rather the opposite).

Question:
- how can I avoid new files to be defaulted to whichever language it is I am currently using?
- how to specify correct grammar in `"files.defaultLanguage": <extension>`?

**Comment by bpasero** [comment]
I cannot reproduce, I just did this:
* run `code --user-data-dir <some new folder>` from command line
* opened a markdown file
* `Cmd+N` to open a new untitled file

=> that untitled file had the "Plain Text" mode and not markdown.

**Comment by gennaro-tedesco** [comment]
I have narrowed down the problem to essentially a copy&paste issue: if I follow your steps, I too see "plain text" mode - as you confirmed; however, if I copy the text from another file (whatever extension) and I paste it in a new empty one, the new blank file acquires the same extension of the file the original content comes from. This is furthermore in line with the 1.42.1 release notes:

> In addition, when you copy and paste text into an untitled editor, VS Code will now automatically change the language mode of the untitled editor if the text was copied from a VS Code editor:

Is there a way to avoid this behaviour for copy&paste? I guess this brings us back to `"files.defaultLanguage": <extension>`?

**Comment by bpasero** [comment]
@gennaro-tedesco did you even try with `"files.defaultLanguage": "plaintext"` ?

**Comment by gennaro-tedesco** [comment]
Yes, my configuration is indeed set-up on `"files.defaultLanguage": "plaintext"`, nevertheless the copy&paste behaviour still preserves other extensions (say `.py`, `.json`, `.html` according to what is opened in the previous editor).

Does it work in your case?

**Comment by bpasero** [comment]
@gennaro-tedesco oh sorry for that, I changed this only for the upcoming release. Can you try in our insiders build: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gennaro-tedesco** [comment]
I see, I will try it out, thanks for looking into it. So this should be the expected behaviour for the upcoming release (namely `"files.defaultLanguage": "plaintext"`)?

**Comment by bpasero** [comment]
Yes.
