### ISSUE TITLE
Wildcard / Path segment in folder icons 

### ISSUE THREAD

**Issue by Varkal** [microsoft/vscode#92017]
Hi,

Today, according to the [documentation](https://code.visualstudio.com/api/extension-guides/icon-theme), icon themes doesn't support wildcards or path segments in the "folderNames" property.

It could be very useful to specify folder icons based on their position in the tree, or by wildcard.

```json
{
    "folderNames": {
        "interfaces/*": "folder-interface",
        "**.interfaces": "folder-interface"
    }
}
```

If someone can give me some basic informations on where to look, i could try to do a PR.

**Comment by aeschli** [comment]
duplicate of #12493
