### ISSUE TITLE
VSCODE crashes opening .md files and github projects

### ISSUE THREAD

**Issue by sbattagi** [microsoft/vscode#92011]
- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:
The latest VSCODE 1.42.1 version I have installed on my windows 10 laptop, crashes every time I try to open a github project directory or a simple .md file.
I have used the DebugDiagnostics tool and got the crash log file. Attached the same for your review.
Please review and help me with a solution for this issue.

Thanks
Sambasiva

[Code__PID__10080__Date__03_04_2020__Time_05_08_32PM__323__Log.txt](https://github.com/microsoft/vscode/files/4287080/Code__PID__10080__Date__03_04_2020__Time_05_08_32PM__323__Log.txt)
[Code__PID__17020__Date__03_04_2020__Time_05_08_31PM__163__Log.txt](https://github.com/microsoft/vscode/files/4287081/Code__PID__17020__Date__03_04_2020__Time_05_08_31PM__163__Log.txt)
[Code__PID__13976__Date__03_04_2020__Time_05_08_27PM__804__Log.txt](https://github.com/microsoft/vscode/files/4287082/Code__PID__13976__Date__03_04_2020__Time_05_08_27PM__804__Log.txt)

  

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
@sbattagi Does this issue occur when all extensions are disabled?
("yes/no" is not a helpful answer)

**Comment by sbattagi** [comment]
Answer is Yes. 
I have disabled all the installed extensions using command pallet. Still seeing this issue.

**Comment by sbattagi** [comment]
Appreciate any fix/workarounds for this issue.

**Comment by deepak1556** [comment]
Can you update to latest stable `1.43.1` and see if the crash still happens.

And if the crash happens can you provide the crash id following the steps at https://github.com/microsoft/vscode/issues/92192#issuecomment-598579176 . Thanks!
