### ISSUE TITLE
Integrated terminal doesn't start bash or any other shell.

### ISSUE THREAD

**Issue by RomanovaDI** [microsoft/vscode#92012]
There is another issue about this problem, but it was closed before it was solved:
https://github.com/microsoft/vscode/issues/90878

I assume that these are problems with python, but I don’t understand which ones, because I don’t know how to look at the vscode launch logs or integrated terminal launch logs.

- VSCode Version: About:
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic

- OS Version: Ubuntu 18.04.4 LTS

settings.json file:
```js
{
    "latex-workshop.view.pdf.viewer": "tab",
    "cSpell.language": ",ru",
    "vim.history": 500,
    "editor.wordWrap": "on",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Solarized-light",
    "explorer.confirmDelete": false,
    "spellright.language": [
        "en_US",
        "ru_RU"
    ],
    "spellright.documentTypes": [
        "markdown",
        "latex",
        "plaintext"
    ],
    "terminal.integrated.inheritEnv": false,
    "terminal.integrated.shell.linux": "/bin/bash",
    "editor.renderWhitespace": "all",
    "cSpell.userWords": [
        "modelling"
    ]
}
```

**Comment by loomlike** [comment]
I had the same issue on my Ubuntu machine. Somehow, removing 
`"terminal.integrated.inheritEnv": false` from my settings.json resolved the issue for me.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.

**Comment by RomanovaDI** [comment]
It didn't help me =(

**Comment by Tyriar** [comment]
Try enabling trace logging and seeing what the logs say when the terminal is created and shutdown https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
