### ISSUE TITLE
C++ 

### ISSUE THREAD

**Issue by niharshah1996** [microsoft/vscode#92023]
Issue Type: <b>Feature Request</b>

I would like to code in C++ but i did not check the update box for it when downloading. Can this be reversed?

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
Are you talking about "Visual Studio" or "Visual Studio Code"?

**Comment by niharshah1996** [comment]
Visual Studio Code. thanks for correction. But I already have installed the program so I am not sure if it comes with C++ functionalities? I will send printscreen

 C:\Users\Nihar Shah\Desktop\Coding\Javascript (client side interaction)\Javascript Visual Studio Code Project 1\home.js

**Comment by IllusionMH** [comment]
VS Code doesn't come with built-in C++ support.
You need to follow steps described in https://code.visualstudio.com/docs/languages/cpp to properly setup your environment.
