### ISSUE TITLE
View action bar context menu focus hides action bar

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#92029]
Issue Type: <b>Bug</b>

It feels strange to me that when opening the context (`...`) menu of a view, that it goes away when the menu gets focus.

![focus](https://user-images.githubusercontent.com/641685/75915294-3dfc4d00-5e24-11ea-856b-4abba173b5ea.gif)

Related: #90729

VS Code version: Code - Insiders 1.43.0-insider (3943d614597f9f7c384846613d417e97ea6d5ab4, 2020-03-03T21:20:08.233Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sbatten** [comment]
resolved previously with shadow dom menu
