### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by davmann** [microsoft/vscode#92022]
Issue Type: <b>Bug</b>

from tkinter import *
root = Tk()
myLabel1 = Label(root, text="Hello World")
myLabel2 = Label(root, text="TKinter")
myLabel1.grid(row=0, column=0)
myLabel2.grid(row=1, column=0)
root.mainloop()

Result (Terminal):
Traceback (most recent call last):
  File "/home/user/VEs/python3_env/projects/tkinter_test.py", line 1, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'

VS Code version: Code - OSS 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2020-01-19T05:18:46.103Z)
OS version: Linux x64 4.19.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 3490)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.39GB (12.41GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.2.64397

</details>

**Comment by weinand** [comment]
VS Code has no built-in Python support.
Please file this issue against the Python extension.
