### ISSUE TITLE
Discuss about the clickBehavior on explorer to open editor

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#9202]
#### 1. Down or Up

Now we can open an editor by **mouse down** on explorer tree.
I am very surprised why not **mouse up** or **click** to open an editor.

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L377

I can't stand it.

#### 2. Double Click

I hope add a configure to allow user open editor by **double click** on explorer tree rather than  **click**.  I think it's easy.

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L464

change to

```
let needOpen = !configuration.explorer.openWhenDoubleClick || isDoubleClick;
if (needOpen) {
    this.openEditor(stat, preserveFocus, event && (event.ctrlKey || event.metaKey), isDoubleClick);
}
```

**Comment by bpasero** [comment]
We use mouse down so that it needs less time from the user interaction until the editor is opened. This is consistent throughout the UI and we do not plan to change this.
