### ISSUE TITLE
Discrepancy with Bracket Matching in VS Code in presence of Commented Code

### ISSUE THREAD

**Issue by ysahil97** [microsoft/vscode#92026]
- VSCode Version: 1.42.1-1581432938
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open a new File and Select the language mode to be C++
2. Paste this code into the file
```
void grapple(void){
    if (statement1){
        if(statement2){
/*            if(statement3){
a = 1;                
            }*/
        }
    }    
}
```
3. Try to do Bracket matching for opening brace for `if(statement3)` by executing Ctrl+Shift+\ command
4. The Ideal behavior should be such that the cursor should jump to closing brace of `if(statement3)`. But the current behavior shows the cursor to jump to closing brace of `if(statement2)`, which is not an expected behavior and could hamper code reading for large nested blocks of code.
Note: This kind of Behavior is also applicable to this piece of code
```
void grapple(void){
    if (statement1){
        if(statement2){
//            if(statement3){
//a = 1;                
//            }
        }
    }    
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Any bracket characters (like `{` or `}`) are ignored inside comments.

The reason is that most of the time comments do not contain syntactically correct source code.
