### ISSUE TITLE
Git is not detecting file changes and out of sync with git command (no git lens extension installed)

### ISSUE THREAD

**Issue by dbradleyfl** [microsoft/vscode#92028]
Issue Type: <b>Bug</b>

Using WSL. Not running in WSL remote mode.  Working on Svelte project. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-svelte-snippets|fiv|0.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
svelte-vscode|Jam|0.9.3
mssql|ms-|1.8.0
remote-wsl|ms-|0.42.3

</details>

**Comment by dbradleyfl** [comment]
Disabled svelte plugin after submitting this issue and found it to be the cause.

**Comment by dbradleyfl** [comment]
Nevermind - it is still happening without the svelte plugin

**Comment by weinand** [comment]
/needsMoreInfo
please provide reproducible steps.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
