### ISSUE TITLE
the width of space is only half character

### ISSUE THREAD

**Issue by jerryyyq** [microsoft/vscode#92024]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. the width of space is only half character!
2. It's so ugly and it's hard to accept!

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

What font is used in editor that causes problem?

Is it reproducible it in Insiders build? https://code.visualstudio.com/insiders/

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
