### ISSUE TITLE
Review usage/overrides of get.*Actions on ViewPanes

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#92038]
With the introduction of View Menu Actions its possible for ViewPanes to accidentally override them. We should verify if this is happening and consider if we still want View Menu Actions with DnD for views already introduced.
/cc @eamodio 

### Updated Description

Currently `ViewPanes` and `ViewPaneContainers` can contribute Primary, Secondary and ContextMenu actions in following ways
- Primary actions
  - Provide using `getActions`
  - Register to [ViewContainerTitle](https://github.com/microsoft/vscode/blob/a416c1534bb9159c7ad9d88f19d70019ded16a6a/src/vs/platform/actions/common/actions.ts#L115-L115) menu with `navigation` group
  - Register to [ViewTitle](https://github.com/microsoft/vscode/blob/a416c1534bb9159c7ad9d88f19d70019ded16a6a/src/vs/platform/actions/common/actions.ts#L117-L117) menu with `navigation` group

- Secondary actions
  - Provide using `getSecondaryActions`
  - Register to [ViewContainerTitle](https://github.com/microsoft/vscode/blob/a416c1534bb9159c7ad9d88f19d70019ded16a6a/src/vs/platform/actions/common/actions.ts#L115-L115) menu
  - Register to [ViewTitle](https://github.com/microsoft/vscode/blob/a416c1534bb9159c7ad9d88f19d70019ded16a6a/src/vs/platform/actions/common/actions.ts#L117-L117) menu

- Context menu actions
  - Provide using `getContextMenuActions`
  - Register to [ViewContainerTitleContext](https://github.com/microsoft/vscode/blob/a416c1534bb9159c7ad9d88f19d70019ded16a6a/src/vs/platform/actions/common/actions.ts#L165-L116) menu
  - Register to [ViewTitleContext](https://github.com/microsoft/vscode/blob/a416c1534bb9159c7ad9d88f19d70019ded16a6a/src/vs/platform/actions/common/actions.ts#L118-L118) menu

We would like to move away from `get*Actions` and use Menu registry because 

- All actions shall be command driven so that user can assign keybindings 
- Facilitates providing customizable menus
- Improves code quality
  - One consistent way to register actions across workbench
  - Allows removing redundant code if the same action is used at multiple places
  - Helps in removing ambiguity of actions lifecycle and simplifies views as they do not need to maintain actions state

I will be removing the `get*Actions` method after everyone move away from it. I listed the existing consumers of this and assigned the respective owner. Please adopt using Menu registries. 

Here are some tips that might help you while adopting

- If you have a custom UI for your action, you can override `getActionViewItem` like before and provide custom implementation. 

Example:
https://github.com/microsoft/vscode/blob/af29768f18350bdb9deb0cbf81982eddff285321/src/vs/workbench/contrib/markers/browser/markersView.ts#L852-L857

- If your action needs access to your view's or view container's state, you can use [ViewAction](https://github.com/microsoft/vscode/blob/56e35cf038f2a5543f767cb53b80145f6acebcca/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L1683-L1683) or [ViewPaneContainerAction](https://github.com/microsoft/vscode/blob/56e35cf038f2a5543f767cb53b80145f6acebcca/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L1668-L1668). They will pass our view or viewPaneContainer as arg in run method

Example:

https://github.com/microsoft/vscode/blob/56e35cf038f2a5543f767cb53b80145f6acebcca/src/vs/workbench/contrib/outline/browser/outlinePane.ts#L641-L660

### To Adopt

- [ ] Search - @roblourens 
  - https://github.com/microsoft/vscode/blob/2ecb47d4ecc46343c3ed64b92ca6c1be32725a34/src/vs/workbench/contrib/search/browser/searchView.ts#L1849-L1849

- [ ] Terminal - @Tyriar @meganrogge 
  - https://github.com/microsoft/vscode/blob/0ef0d2d65a3d109efa59499594ef322f176678f5/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L157-L157

**Comment by sbatten** [comment]
Looking a little more at this, there may be other uses?

**Comment by bpasero** [comment]
@sbatten @sandy081 I wanted to follow up on a related topic, not sure if it is the same as this issue: today, `Composite` has methods `getActions` and `getSecondaryActions` (even `getContextMenuActions`?). We probably have other view related pieces with this kind of API.

That API should be deprecated imho and removed in favour of registering commands to Menu locations, as we e.g. do with all editor related actions in the editor tool bar. There should be no reason that any piece of UI is required to return actions upfront from these methods and every location should be capable of receiving actions with proper menu contributions and commands.

**Comment by sandy081** [comment]
@sbatten Not sure if I understand this debt item. Can you please elaborate more?

**Comment by sandy081** [comment]
@bpasero Yes, I completely agree.

Thanks to @jrieken who provided support for contributing menu actions to any view. I discussed with him then and discussed about the future plan of moving away from `get*Actions` to MenuRegistry.

We can use this item to migrate.

**Comment by sandy081** [comment]
I also quickly looked into this then and figured out that there are some actions which need `ActionItem` infrastructure. For eg: 
- `FilterAction` in problems panel
- `Dropdowns in Terminal and Output panel etc.,

**Comment by eamodio** [comment]
FWIW, When adding commands to the Timeline view -- I first added them through the `MenuRegistry` and context keys, but I ultimately removed all of that and moved to `get*Actions` because it was so much easier, especially dealing with internal view state. Also the Timeline has a custom list of "filters" which are the labels of the sources registered, so hooking that into `getSecondaryActions` was quite trivial, where as to provide that with the `MenuRegistry` would require a lot more indirection and complexity.

**Comment by sandy081** [comment]
@eamodio Can you please provide an example of the complexity and indirection you mentioned. At the end you need to have a logical condition to show an action in `get*Actions` or through `MenuRegistry`. Is not it possible to compute the logical state in your view and set that as context?

**Comment by eamodio** [comment]
Ultimately it turned out not to be a big deal -- I converted Timeline back to using the `MenuRegistry` via `registerAction2`

**Comment by sbatten** [comment]
If I understand the desired action from @bpasero and @sandy081, this is the list of usages that should be migrated. Perhaps we can have view owners migrate during upcoming debt week.

https://github.com/microsoft/vscode/blob/15c02dca3a95c1515d112b0f1bc97b3090402fdb/src/vs/workbench/contrib/comments/browser/commentsView.ts#L122-L129

https://github.com/microsoft/vscode/blob/c650757bd48b936987f1be4350a8f359b1a76550/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L231-L237

https://github.com/microsoft/vscode/blob/7653d836944892f83ce9e1f95c1204bafa1aec31/src/vs/workbench/contrib/debug/browser/callStackView.ts#L182-L188

https://github.com/microsoft/vscode/blob/e3a36fa10c0d3ad278dbdc8cad449c6c79295d01/src/vs/workbench/contrib/debug/browser/repl.ts#L446-L456

https://github.com/microsoft/vscode/blob/9a2062ff5df3cf05c763b7ed6dadff26ddce00c4/src/vs/workbench/contrib/debug/browser/variablesView.ts#L153-L155

https://github.com/microsoft/vscode/blob/de3e5a4bf4beaf404d06d4375f6b5d3cd24c3ef8/src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts#L153-L159

https://github.com/microsoft/vscode/blob/86161ffb9807b29959f40a4dc9c7ba3fe7b526dc/src/vs/workbench/contrib/extensions/browser/extensionsViews.ts#L923-L930

https://github.com/microsoft/vscode/blob/86161ffb9807b29959f40a4dc9c7ba3fe7b526dc/src/vs/workbench/contrib/extensions/browser/extensionsViews.ts#L1020-L1029

https://github.com/microsoft/vscode/blob/187dedbdc33e91b53dff9e3ed0f8278b27d113c7/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L287-L298

https://github.com/microsoft/vscode/blob/7653d836944892f83ce9e1f95c1204bafa1aec31/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L308-L314

https://github.com/microsoft/vscode/blob/7bd4ccb711d73e07509c86d6bdacc0070866c803/src/vs/workbench/contrib/outline/browser/outlinePane.ts#L411-L417

https://github.com/microsoft/vscode/blob/25e889af458c2be6b2ba2a3b5510b370586bb5c5/src/vs/workbench/contrib/remote/browser/tunnelView.ts#L575-L577

https://github.com/microsoft/vscode/blob/1a95f3134a8f81487f6680a4463e4b031e1db1ac/src/vs/workbench/contrib/scm/browser/repositoryPane.ts#L1062-L1073

https://github.com/microsoft/vscode/blob/79a1f5a5ca0c6c53db617aa1fa5a2396d2caebe2/src/vs/workbench/contrib/search/browser/searchView.ts#L1779-L1787

https://github.com/microsoft/vscode/blob/8a56212a5b6fde3ceb0e910d8cde74537a432503/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L131-L145

https://github.com/microsoft/vscode/blob/7bd4ccb711d73e07509c86d6bdacc0070866c803/src/vs/workbench/contrib/outline/browser/outlinePane.ts#L419-L436

https://github.com/microsoft/vscode/blob/1a95f3134a8f81487f6680a4463e4b031e1db1ac/src/vs/workbench/contrib/scm/browser/repositoryPane.ts#L1074-L1076

**Comment by joaomoreno** [comment]
@sbatten This isn't trivial for SCM, since we have the `scm/title` contributable menu.

![image](https://user-images.githubusercontent.com/22350/101902400-707f6700-3b67-11eb-9f64-067bf675ac0c.png)

1. This is a general SCM view action
2. These come from the `scm/title` contributable menu
3. These are view actions
4. These are general SCM view actions
5. These come from the `scm/title` contributable menu

Any thoughts on how to adress that?

**Comment by sandy081** [comment]
@joaomoreno Interesting. If the order is always consistent & same (general SCM actions followed by scm/title actions) how about providing your contributable menu ids to (super) `ViewPane` class so that I can build the list for you ? For eg, in your case:

- You can contribute your general SCM view actions to `ViewTitle` menu.
- Pass your `scm/title` menu id to super `ViewPane`
- `ViewPane` class will build the primary and secondary actions from `ViewTitle` menu and contributable menus in the oder you provide the menu ids?

**Comment by joaomoreno** [comment]
@sandy081 One more problem, the SCM contributable menu requires specific context keys: 

https://github.com/microsoft/vscode/blob/5a968d0235bfc975d7bf3e5dbdcb0f06222c0d5c/src/vs/workbench/contrib/scm/browser/menus.ts#L182-L185

**Comment by sandy081** [comment]
@joaomoreno Please ignore my previous comment. Currently you can override view title menu id using `[titleMenuId](https://github.com/microsoft/vscode/blob/56e35cf038f2a5543f767cb53b80145f6acebcca/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L67-L67)` option. So you can contribute your general SCM view actions to `scm/title` menu and pass `scm/title` menu id using `titleMenuId` option. 

Regarding context keys, can you create a scoped contextkey service and pass it to the viewPane and update the scoped contextkey service with your contexts whenever they change?

> Should removing getActions() be the ultimate goal here? IMO the default getActions() should do the best for most consumers, but it should still be overridable to get full control, like in SCM.

Yeah, aiming towards single consistent solution for all views to contribute actions ie., through menus. Helps in removing ambiguity of actions lifecycle and simplifies views as they do not need to maintain actions state. It will also make it easy in code to discover the actions by using menu id. Also facilitates customisable menus going forward.

**Comment by alexr00** [comment]
@sbatten I'm not sure how to adopt this for this case:

https://github.com/microsoft/vscode/blob/15f38fe338a791de62b1c448f0035b199ba27a04/src/vs/workbench/contrib/remote/browser/remote.ts#L538-L548

This is for the dropdown/picker in the remote explorer.

**Comment by sandy081** [comment]
@isidorn Sorry that my previous list was missing one view (CallStacksView). Added it and assigned to you.

**Comment by isidorn** [comment]
@sandy081 somehow I missed that one. I just pushed a commit that tackles that. Thanks

**Comment by joaomoreno** [comment]
@eamodio FYI I started with this for SCM.

**Comment by joaomoreno** [comment]
@sbatten I started this for SCM: https://github.com/microsoft/vscode/compare/joao/scm-menu-actions

After 1 hour of work I'm not even 10% done, so I decided to pause it.

There are usually two reasons for forcing everyone to invest their time in large refactorings:

1. To benefit from fixes / new features
2. To eventually delete the old way of doing things

Today, actions in SCM work just fine and don't leak. Jumping to menus is a big investment since not only all actions need to be converted but all the view state they depend on needs to be accessible via context keys. This is considerable effort, even without the fixing of the eventual bugs which always come after a large refactoring. I can see that moving to menus could enable user customizable menus in the future. But until this is on the near future plan, I do not think it is reasonable to invest so much time in refactoring for no added immediate benefit.

How necessary is it that all parts of Code move and could we maintain both menus and getActions until we decide to implement a feature which actually depends on views only having actions via menus?

**Comment by joaomoreno** [comment]
Might just push this out to February's debt week, since it's hard to do a staged rollout of this.

**Comment by sandy081** [comment]
Thanks @joaomoreno - I also updated the description with the benefits and reasons behind this.

**Comment by Tyriar** [comment]
I started this but will also push it to Feb so it gets more testing before stable.

**Comment by joaomoreno** [comment]
@eamodio I've refactored the SCM world for this: https://github.com/microsoft/vscode/commit/e83180b96f2d85540aba11663c3fb0c80b1956cf I smoke tested it quite heavily, but still be on the lookout for upcoming issues surrounding menu items in SCM, feel free to assign them to me as they come.

**Comment by Tyriar** [comment]
I've done my piece here. It was a lot of changes so I'll also be on the lookout for issues but the terminal action code is in a much better shape as a result of this, thanks!
