### ISSUE TITLE
Bad Typescript support compared to WebStorm

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#92036]
![vscode](https://user-images.githubusercontent.com/2149294/75927305-c60a4300-5e74-11ea-97de-bb64f827d308.png)

I remember that VSCode used to have better integration with Typescript.

As you can see, VSCode suggest `foo` just based on lexical analysis instead of using Typescript information?!

With extensions or without, the result is as in the image. I try it on all three VSCode instances to the same effect.

I don't like Webstorm and I barely use it, but this is major con.

Initially, I brought the issue to Reddit and one user suggested to check if Typescript extension log errors, but it did not.

- VSCode Version: Latest
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Create a class in typescript file
2. Create a method
3. Create second method
4. Write inside the second method `this.` and press `crtl+space` to see suggestions

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Have you disabled the built-in JavaScript and TypeScript extension?

![Screen Shot 2020-03-04 at 2 16 32 PM](https://user-images.githubusercontent.com/12821956/75928206-c37efd80-5e22-11ea-80d6-bf56f497ee18.png)

```
class Foo { 
	bar() { }

	foo() {
		this.
	}
}
```
