### ISSUE TITLE
Disambiguation tab folder hint is using wrong slash ".\" in WSL

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#92030]
It seems to be using the slash based on the frontend OS, not the backend.

![image](https://user-images.githubusercontent.com/2193314/75915406-485e1d00-5e0b-11ea-8051-bb693c9454de.png)

Repro:

1. Open WSL workspace
2. Open 2 files with same name

**Comment by bpasero** [comment]
Good catch, I am using `IRemotePathService#path` now for the code that shortens the tab labels when there are duplicates. Needs verification though.
