### ISSUE TITLE
Add a CLI for controlling the integrated terminal

### ISSUE THREAD

**Issue by ranyitz** [microsoft/vscode#92031]
## 🙋‍♂️ Feature request
Controlling the integrated terminal using the CLI will enable devs to program predefined terminal experiences in Visual Studio Code.

The most basic functionality would be to open a **new tab** and **split pane**.

### API suggestion

After discussing the subject on an [issue](https://github.com/ranyitz/newsh/issues/11) in a utility library for controlling terminals.

@Tyriar's [suggested](https://github.com/ranyitz/newsh/issues/11#issuecomment-594591915) to go for an API that looks like this:

```sh
code terminal split-pane
```

```sh
code terminal new-tab
```

In order to not pollute the top-level `code` namespace.

**Important to note** that there is an API with similar functionality which is being developed for [microsoft/terminal](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#using-the-wtexe-commandline)

**Comment by memark** [comment]
Any hint on where in the code to start looking at this?

Are there any other examples of a "subgroup"/2nd level namespace? Running `code -h` suggests there aren't.

**Comment by Tyriar** [comment]
@memark I don't believe there are namespaces yet. Created https://github.com/microsoft/vscode/issues/93241 for discussion on that.
