### ISSUE TITLE
Terminal issues with ANSI colors and UTF-8 strings

### ISSUE THREAD

**Issue by mikbox74** [microsoft/vscode#92032]
Issue Type: <b>Bug</b>

Terminal doesn't show ANSI colors when strings generated by PHP scripts.
You can see it running e.g. composer.phar.
Additionally, I see strange symbols and some extra letters when script prints an UTF-8 string.
This issues appear only when terminal program runs as integrated shell. CMD, PowerShell, git-bash, Cmder tried.

![image](https://user-images.githubusercontent.com/1404546/75921481-3f546680-5e72-11ea-9d4a-d320cbc066b8.png)

![image](https://user-images.githubusercontent.com/1404546/75921535-5004dc80-5e72-11ea-9993-b6e083dad6fc.png)

![image](https://user-images.githubusercontent.com/1404546/75921978-2e582500-5e73-11ea-91f0-9efa4a9d2ae2.png)

![image](https://user-images.githubusercontent.com/1404546/75922004-3adc7d80-5e73-11ea-8319-2e270ac71d07.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

Terminal settings:
```json
{
  "terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe",
  "terminal.integrated.env.windows": {
    "LESSCHARSET": "utf-8",
    "path": "d:\\PHP\\php;d:\\PHP\\composer",
    "CMDER_ROOT": "D:\\PHP\\cmder"
  },
  "terminal.integrated.shellArgs.windows": [
    "/K",
    "%CMDER_ROOT%\\vendor\\init.bat"
  ]
}
```

**Comment by Tyriar** [comment]
The terminal does support colors, but something is likely going wrong how you're launching cmd. I suggest trying to get it working in Windows Terminal first and send issues to https://github.com/microsoft/terminal if it doesn't work as they maintain the backend we use on Windows.
