### ISSUE TITLE
[json] support "$id" references.

### ISSUE THREAD

**Issue by rbuckton** [microsoft/vscode#92042]
The relevant documentation for `$id` can be found here: https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref

- Version: 1.43.0-insider (user setup)
- Commit: 17c6d123d212f90300429ecad3fc96fcec6e338f
- Date: 2020-02-28T12:46:02.355Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/3902892/75932440-3f317800-5e2c-11ea-95c9-e1aea6a2f685.png)

This validates correctly using ajv@6.6.2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Implemented by https://github.com/microsoft/vscode-json-languageservice/pull/107
