### ISSUE TITLE
There are two "Node debug" in the settings.

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#92047]
Issue Type: <b>Bug</b>
It's confusing.
![图片](https://user-images.githubusercontent.com/54468/75937635-75b8d280-5ec0-11ea-8ad5-1e3cc82fd7d9.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by weinand** [comment]
@connor4312 I suggest to add something to the second "Node Debug" that makes clear what it does, e.g. "Node Debug (Experimental)".

**Comment by connor4312** [comment]
This is because extension host debugging is contributed by node2, and the other settings are contributed by node1. I will just remove the v3 setting from node2, since we're pointing people towards `usePreview` now.

**Comment by connor4312** [comment]
Actually, I'll leave it there for people who still want to toggle things individually, but just move it to node1. It's slightly weird because node1 doesn't provide extension host debugging, but I think it's the simplest way for what will be a temporary flag regardless.
