### ISSUE TITLE
Pressing esc crashes VSCode

### ISSUE THREAD

**Issue by khaled-e-a** [microsoft/vscode#92048]
Issue Type: <b>Bug</b>

Sometimes when I press the esc button to dismiss dialogs like the search dialog,  VSCode crashes.  This occurs both for system whose report is attached (Ubuntu 16.04), and on my macbook pro running Catalina 10.15.2. 

VS Code version: Code - Insiders 1.43.0-insider (17c6d123d212f90300429ecad3fc96fcec6e338f, 2020-02-28T12:48:39.706Z)
OS version: Linux x64 4.4.0-174-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.53GB (3.21GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-django|bat|0.20.0
solargraph|cas|0.21.1
smali|cra|1.0.1
vscode-markdownlint|Dav|0.34.0
xml|Dot|2.5.0
gitlens|eam|10.2.1
gc-excelviewer|Gra|2.1.33
latex-workshop|Jam|8.7.2
MagicPython|mag|1.1.0
apex-pmd-code-scanner|moh|0.0.40
python|ms-|2020.2.64397
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
cpptools|ms-|0.26.3
vscode-jscpd|pau|0.3.4
java|red|0.57.0
code-settings-sync|Sha|3.4.3
vscode-checkstyle|she|1.3.2
fish-vscode|sky|0.2.1
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

Please clarify what you mean by "crashes". Screenshots may help. 

If a so-called "native crash" see https://github.com/microsoft/vscode/wiki/Native-Crash-Issues for how to get more information.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

**Comment by lochstar** [comment]
I'm also experiencing this issue. VSCode shuts down completely without warning, a minute or so later a dialog appears saying Electron has crashed (macOS).

Crash logs:
https://pastebin.com/2G3aPHRV
https://pastebin.com/BPqRtk6L
