### ISSUE TITLE
VSCode 1.42.1: ctrl + / in html file displays {% comment %} {% endcomment %}

### ISSUE THREAD

**Issue by nivre** [microsoft/vscode#92045]
- VSCode Version: 1.42.1
- OS Version: Windows 10

Steps to Reproduce:
1. highlight block of html codes
2. ctrl + /

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
