### ISSUE TITLE
VSCode and Remote task bar

### ISSUE THREAD

**Issue by nomadus** [microsoft/vscode#92049]
I am using VsCode and Remote desktop connection at the same time. When VsCode is started and I open Remote desktop connection I see my host's taskbar, when I close VsCode and relaunch Remote desktop connection, only then I see remote host's taskbar. How to fix this?

**Comment by weinand** [comment]
/needsMoreInfo
What platform, what version of VS Code?
a screenshot would help too.

**Comment by nomadus** [comment]
Hi, sorry, I forgot to update with the version info. 
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
I still don't understand the issue.
Please add a screenshot that shows where you expect to "see" something that isn't there...

**Comment by nomadus** [comment]
See the screenshot attached. I see my (local) host's taskbar, instead of the remote computer's taskbar.

![image](https://user-images.githubusercontent.com/3382143/75988085-3e2b4400-5f1b-11ea-9083-7c586ec5da15.png)

**Comment by weinand** [comment]
And how is this related to VS Code?

**Comment by nomadus** [comment]
It happens when I have vscode open. It seems vscode sets host taskbar to always shown mode, so it shows only host taskbar

**Comment by IllusionMH** [comment]
Is it reproducible with `"window.titleBarStyle": "native"`? With other Electron apps launched? Or with any other Win32 app?

**Comment by nomadus** [comment]
I am positive, that I have not seen similar issues with any other Win32. Can't say about other Electron apps. I shall test the first option and update.

**Comment by bpasero** [comment]
Please do.
