### ISSUE TITLE
`<?=` PHP opening tag throws css(css-ruleorselectorexpected) error 

### ISSUE THREAD

**Issue by alystair** [microsoft/vscode#92043]
`<?php` opener does not throw errors, however `<?=` short open/echo tag does.

- VSCode Version: 1.42.1
- OS Version: Windows 10 x64 1909

Steps to Reproduce:

1. Create index.php file with HTML and CSS Style in it
2. Add PHP code in the style header using the `<?=` tag.

```html
<!DOCTYPE html><html lang="en-US">
<head><title>Test</title>
<style>
<?=file_get_contents('index.css');?>
</style>
</head><body><?="Hello world";?></body></html>
```

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
please file against php extension
