### ISSUE TITLE
Bug with source control

### ISSUE THREAD

**Issue by Shapovalov-Dmitry** [microsoft/vscode#92059]
Issue Type: <b>Bug</b>

Hello!

I have made some changes to a file and staged them and then I make some more changes to the file, but don't stage them, because I want to commit previous ones first.
Let's say that I have raw code in the not staged changes with some errors or warnings from linters. But the staged part has no errors. BUG here is that in the staged file I can't see any errors, but on the file link the error count is shown.

VS Code version: Code - Insiders 1.43.0-insider (17c6d123d212f90300429ecad3fc96fcec6e338f, 2020-02-28T12:46:02.355Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.91GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.0.0
time-tracker|ale|1.0.4
vsc-rename-files|alf|1.0.0
ng-template|Ang|0.900.15
multi-cursor-case-preserve|Car|1.0.5
split-line|che|1.0.1
path-intellisense|chr|1.4.2
bracket-select|chu|2.0.1
angular-schematics|cyr|3.3.0
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
settings-on-fire|edb|1.0.3
vandelay|edb|4.3.0
prettier-vscode|esb|3.20.0
macros|ged|1.2.1
toggler|hid|0.0.3
smartmulticursor|ida|0.0.3
angular2-switcher|inf|0.3.2
vscode-angular2-emmet|jak|2.0.3
vscode-text-pastry|jkj|1.2.0
vscode-gutter-preview|kis|0.25.0
vscode-regexp-preivew|Lul|1.0.0
jumpt|mbn|1.3.0
theme-monokai-pro-vscode|mon|1.1.15
vscode-csscomb|mrm|5.3.0
remote-wsl|ms-|0.42.3
vscode-typescript-tslint-plugin|ms-|1.2.3
easyzoom|Nab|0.1.0
gremlins|nho|0.15.1
syncing|non|3.0.13
material-icon-theme|PKi|4.0.1
bracketeer|pus|1.2.7
vscode-sort-json|ric|1.18.0
synthwave-vscode|Rob|0.1.1
vscode-autohotkey|sle|0.2.2
vscode-smoothtype|spi|1.2.0
comment-divider|sta|0.2.1
tech-debt-tracker|Ste|0.26.1
addDocComments|ste|0.0.8
code-spell-checker|str|1.8.0
transpose|v4r|0.0.5
quokka-vscode|Wal|1.0.282
joinlines|web|1.1.1
unsaved-files-vscode|wra|2.1.1

(3 theme extensions excluded)

</details>

![Snipaste_2020-03-05_10-13-58](https://user-images.githubusercontent.com/35997118/75961127-0e078500-5eca-11ea-863d-8ba69446ca87.png)

**Comment by Shapovalov-Dmitry** [comment]
![Snipaste_2020-03-05_10-13-58](https://user-images.githubusercontent.com/35997118/75961180-2d9ead80-5eca-11ea-8ee0-d825dcc00b2e.png)

**Comment by joaomoreno** [comment]
Errors are per file, not per version of the file. Unfortunately this won't get fixed any time soon given it requires many changes by many areas of tooling. Closing as out of scope.
