### ISSUE TITLE
Increase current view size command is not working

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode#92054]
Issue Type: <b>Bug</b>

open a left side bar view 
run the command:  increase current view size 

nothing happens

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vsc-organize-imports|alf|0.1.9
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
dotnet|for|0.0.4
mssql|ms-|1.8.0
sqlops-debug|ms-|1.3.0
csharp|ms-|1.21.12
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6

</details>

**Comment by sbatten** [comment]
@alanrenmsft the command needs to be run from a keyboard shortcut, so one must be assigned by the user. The focus of the current view is not maintained in the command palette so if you are running it from there, it won't work unfortunately.

/cc @chrmarti

**Comment by alanrenmsft** [comment]
@sbatten it works. thanks!
