### ISSUE TITLE
 Force Collapsible Regions Adds //

### ISSUE THREAD

**Issue by shirish212** [microsoft/vscode#92051]
When we type ` //#` it shows region as suggestion, 
Then when we press enter - it auto generate `////#region`

same as for `endregion` tag

**Comment by shirish212** [comment]
![11](https://user-images.githubusercontent.com/50163760/75962037-0e634880-5ee9-11ea-8e0b-0d3aca460c42.png)
![12](https://user-images.githubusercontent.com/50163760/75962043-10c5a280-5ee9-11ea-8f0a-2d7cb5b775e2.png)

While pressing enter for the suggestion displayed on image 11, It prints as shown in the image 12.

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic

**Comment by aeschli** [comment]
This is just regular code snippet with the name `#region` and content `//#region`
Code snippets are not smart.

You have to use it at the very beginning of the line.
