### ISSUE TITLE
Optionally allow Problems, Debug Console,  Terminal, or Output to be shown as Sidebar Icons

### ISSUE THREAD

**Issue by Ace-Cassidy** [microsoft/vscode#92052]
**Use Cases:**
While editing I would like to be able to have two editors split left/right, terminal at the bottom, and problems showing on the left.
OR
While editing I would like to quickly be able to open/close Output/Problems with CTRL + B
OR
While debugging I would like to be able to have output and debug console open at the same time

**Description:**
Right clicking on Problems, Debug Console,  Terminal, or Output would show an option to 'Move to Sidebar' whereupon a new icon appears in the sidebar which grants access to the aforementioned. 
AND/OR
In settings provide 'Problems/Debug/Console/Terminal/Output: Default Location' with Sidebar/Panel options.

**Comment by isidorn** [comment]
This is currently on the plan and @sbatten has it on the horizon, thus assigning this issue to him
Also @misolori since we would need probably more icon design when views are moved to the sidebar (to show the icons in the activity bar)

**Comment by sbatten** [comment]
icons are in, all panels can be dragged to the activity bar.

terminal, output, and debug have outstanding issues to resolve before this item is closed
