### ISSUE TITLE
Problem with polish letter

### ISSUE THREAD

**Issue by paulhendrix** [Microsoft/vscode#9205]
- VSCode Version: 1.3.1
- OS Version: WIndows 10

Steps to Reproduce:

1. Press key RightAlt-l
2. Instead of getting polish character "Ł" some other operation is done (cursor is going to 1 col)

**Comment by alexandrudima** [comment]
@paulhendrix We do not bind by default any `ctrl+alt+` keybindings on Windows (the key codes generated when pressing `AltGr+`) especially to not prevent input in these cases.

Is it possible you have installed an extension that takes this keypress? Does this reproduce when running `code --disable-extensions`

You can try searching in the Default keybindings for "ctrl+alt+" and report here if you find one that involves a letter such as "ctrl+alt+l" and show the rules here --- they might be coming from an extension.

**Comment by paulhendrix** [comment]
Yes you are right!
After I run "code --disable-extensions" the problem dissapeard.
I have extension "Bookmarks Alessandro Fragnani" and the problem is with that extension.
Thanks you very much!

**Comment by alexandrudima** [comment]
@paulhendrix Please feel free to create an issue straight with the extension at https://github.com/alefragnani/vscode-bookmarks/issues , it uses `ctrl+alt+k`, `ctrl+alt+l` and `ctrl+alt+j` which might impact other languages as well.

**Comment by alefragnani** [comment]
Hi @alexandrudima , 

Do you have any suggestions on how could I update the default keybindings for extension, without affecting the already installed users?

I was thinking about to display a message right after installing the update, asking if the user would like to keep with the original keybindings, or replace with the new ones. If the user decides to keep the originals, I would update `keybindings.json`, adding the original values. Unless I was able to detect the keyboard layout and suggest another keybindings.

Thanks for your help.

**Comment by alefragnani** [comment]
I search other reported issues about keybindings and keyboard layout and found this one (https://github.com/Microsoft/vscode/issues/1240) which would probably handle my case.

**Comment by alexandrudima** [comment]
We plan at one point to improve the extension viewlet with information regarding the contributions each extension makes. So, at one point, as an end user, you could click on an extension and see the commands it contributes, the default keybindings it wishes to define for them, etc. But yeah, to come ...
