### ISSUE TITLE
FormatOnSave.exceptions settings property

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#92067]
When working with git submodules I would like to have the `formationOnSave` option enabled for certain submodules/folders while having it disabled for other submodules/folders. I can currently achieve this behaviour by creating separate vscode workspaces for each submodule and then open each workspace separately. While doing so I set the `"editor.formatOnSave:"` option in the main `settings.json` to false and I set `"editor.formatOnSave"` in the ".vscode/settings.json" to true or false. I, however, think to have an `editor.formatOnSave.exceptions` property or a FormatOnSave toggle in the status bar would be a very helpful addition to have when working with submodules. Another way would be to use the `editor.formatOnSave` property of the `~/.vscode/settings.json` file inside a submodule/folder if it is present.

**Comment by weinand** [comment]
Have you tried to use different folders for the submodules in a single workspace and then use folder specific settings for the "editor.formatOnSave:"?

**Comment by rickstaa** [comment]
@weinand Thanks a lot i wasn't aware of the folder specific settings.
