### ISSUE TITLE
View file History of file changes (local history)

### ISSUE THREAD

**Issue by Jijokoickal** [Microsoft/vscode#9206]
- VSCode Version: 1.2
- OS Version: W7

Steps to Reproduce:Copy paste content

When copy file content from one to another, it replaces the whole content, sometimes not intended to do so,  and there is no option to undo that action. The whole work will loose. Especially found when VS code becomes slow and hanging

**Comment by alexandrudima** [comment]
@Jijokoickal Can you perhaps show a screen recording of what is going on? I have copied and pasted content from one file to another multiple times with 100% success rate.

Do you have some sort of external program that modifies the files on disk?

Can you please provide more specific steps.

**Comment by Jijokoickal** [comment]
unfortunately I don't have a screen recording. I am working in an organization and I dont have options for that too. Still issue is happening even if I update VS code. Copy part of file from one to another and when I come to old tab, some contents are copied from the other file and it is saved. Even I am unable to revert by Ctrl+Z, because the file will be already saved. If we have an option to history like android studio it will be easy to revert the file.

**Comment by alexandrudima** [comment]
My belief is that there is some other third party software editing the file on disk. That is the only time AFAIK the workbench causes the model to drop its undo stack. Leaving this issue to track as a feature request for local history. fyi @bpasero

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by cwagner22** [comment]
I think this is a really useful feature in intellij. I don't understand why there is no interest to implement it. I especially like knowing my changes are always tracked so if I mess something up I can revert it quickly, also useful when making changes that are not ready to be committed on git.
