### ISSUE TITLE
Search in different workspaces (projects)

### ISSUE THREAD

**Issue by Yuvelir1993** [microsoft/vscode#92066]
Hi, I think it would be very convenient to have a possibility to find some string not only in the currently opened project, but in different ones (ex. find in choosed workspaces or in all from the "projects.json" file)

Thank you for all of the things that you did for us!

Best regards, 
Pavlo Lozovikov

**Comment by roblourens** [comment]
You can put a path from another folder into the `files to include` input in the search view
