### ISSUE TITLE
Using extension with form

### ISSUE THREAD

**Issue by RaynDol** [microsoft/vscode#92062]
we need to create a new vs extension and I wonder if there is API that we can use to create some form, i.e. when user click on treeView or something similar , we will open in the editor a UI  that user can edit etc, I didnt see something like this...is it possible?  , if yes how.

**Comment by weinand** [comment]
No, there is nothing like "form" support in VS Code.
For simple interactions you can try to use the QuickPick UI, for more complex ones you could use a WebView.

**Comment by RaynDol** [comment]
@weinand  - thanks also in vs insiders ?  it will be great if you could provide any reference

**Comment by weinand** [comment]
Not surprising, you can find this in the VS Code documentation:
e.g. https://code.visualstudio.com/api/extension-capabilities/common-capabilities#quick-pick
and https://code.visualstudio.com/api/extension-guides/webview
