### ISSUE TITLE
Display "git add --chmod" changes (File mode) in Source Control view

### ISSUE THREAD

**Issue by krawinkelm** [microsoft/vscode#92060]
`git add` command has an [chmod option](https://git-scm.com/docs/git-add#Documentation/git-add.txt---chmod-x).

> Override the executable bit of the added files. The executable bit is only changed in the index, the files on disk are left unchanged.

Git Gui shows me that file mode change, if I perform a `git add` with `chmod` option like this:

`git add --chmod=+x -- file.sh`

**Screenshot fom Git Gui:**
![Screenshot Git Gui after git add command](https://user-images.githubusercontent.com/8292903/75960595-997c1880-5ec0-11ea-8f76-65223f910dc3.png)

I can not find this file mode change in VSCs Source Control View.

Is it possible to show this kind of change?

**Comment by joaomoreno** [comment]
Does the file appear at all in the source control view?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/26360
