### ISSUE TITLE
Do not show status bar (open with shortcut) in Zen mode

### ISSUE THREAD

**Issue by SmalBox** [microsoft/vscode#92063]
Issue Type: <b>Bug</b>

# Do not show status bar (open with shortcut) in Zen mode

   1. Assign a shortcut "ctrl+k j" to show status bar.
   2. Using shortcut "ctrl+k z" into Zen mode.
   3. Using shortcut "ctrl+k j" do not show status bar. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (1.23GB free)|
|Process Argv|C:\Users\tt\Desktop\event_driven_programming|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.1
vscode-html-css|ecm|0.2.3
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
markdown-preview-enhanced|shd|0.5.2
html-preview-vscode|tht|0.2.5
vim|vsc|1.13.0

</details>

**Comment by isidorn** [comment]
This is a clear limitation of zen mode that you can not toggle status bar visibility while in zen mode.
As a workaround try using 
`"zenMode.hideStatusBar": false`

In the meantime leaving this open as a feature request.

**Comment by SmalBox** [comment]
Thanks!
   - And I found that the **"Activity Bar"** and **"Menu Bar"** have the same problem.
   - After my try, In **"View/Appearance"** , Two funtion about show function have shortcut key by default, **"Show Side Bar"** and **"Show Panel"** , both function is work in Zen mode. Other function event if I assign shortcut is do not work in Zen mode.
