### ISSUE TITLE
"Add Selection To Next Find Match" not behaving consistent

### ISSUE THREAD

**Issue by JHenneberg** [microsoft/vscode#92068]
# Description
You add a selection by pressing ```ctrl + D``` and pressing it again to find the next match then the selection concatenate with something  is ignored. If the first selection is done by the cursor or pressing ```shift + leftarrorw``` the next match is found although it is concatenate with something.

![05-03-_2020_10-43-04](https://user-images.githubusercontent.com/6606609/75969528-5e351600-5ecf-11ea-8bf8-0a7a2b8f3866.gif)

# Steps to Reproduce:
1. Go to a text part you want to select with the cursor and press ```ctrl + D``` to select
2. Press ```ctrl + D``` again to select next match

# VS Code
## Stable
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
## Insiders
Version: 1.43.0-insider (system setup)
Commit: b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0
Date: 2020-03-05T00:59:24.612Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by rebornix** [comment]
I feel like it's a bug as I expect cmd+d on single cursor or selection work the same (as they select the same word `name`) but @alexdima might have reasons why it's designed this way.

**Comment by alexdima** [comment]
This is intentional.
* when starting with the cursor on a word, and pressing cmd+D, the search will become for "whole words"
* when starting with a selection (on a word or otherwise), the search will respect whatever is checked in the find widget for "whole words".
