### ISSUE TITLE
Remove 'Select for Compare'

### ISSUE THREAD

**Issue by Siccity** [microsoft/vscode#92069]
When comparing file diffs i noticed this awkward workflow, the `Select for Compare` option.
1) Right click first file and select `Select for Compare`
2) Right click second file and select `Compare with Selected`

![image](https://user-images.githubusercontent.com/6402525/75970525-c1737800-5ed0-11ea-9056-6075228c6d8f.png)

With the `Select for Compare` option you get this awkward 'invisible' compare-exclusive selection that is inconsistent with existing functionality.

I suggest we remove that option, as the context menu is already getting rather long, and let `Compare with Selected` compare the right-clicked file with the active selected file.

1) Left click select first file
2) Right click second file and select `Compare with Selected`

I believe this is more intuitive, and is a win-win by both cutting down on unnecessary UI options and beginner roadbumps.

Additionally, I would suggest to also add the `Compare with Selected` context menu option to tabs.

**Comment by isidorn** [comment]
This is are all fine suggestions, however changing this is breaking users muscle memory.
Thus I would not do any of those changes atm and will keep this open as a feature request which we might tackle in the future.

**Comment by Siccity** [comment]
Thank you for the consideration, but what is there to gain from waiting?
The longer you wait, the more people will grow accustomed to the 'old' method, and will eventually have to "relearn" the new.
Or do you have some kind of periodical big release where you do these kinds of changes?

**Comment by isidorn** [comment]
To be honest we will probably never change this. However there might a chance that we decide to restrucutre the explorer context menu and then this might make sense.

**Comment by Siccity** [comment]
In that case I will suggest adding a check that compares with active file if no file has been selected through `Select for Compare`. That way you can ease the transition without hurting previous functionality.

Pseudocode:
```
func OnCompareWithSelected() {
  if (selectForCompareTarget == null)
    Compare(activeTarget);
  else
    Compare(selectForCompareTarget);
}
```

**Comment by isidorn** [comment]
Makes sense.

As a workaround to make it easier for you I suggest just select two files and Context Menu -> Compare selected. That way you can do it in one go.
![Screenshot 2020-03-06 at 11 44 38](https://user-images.githubusercontent.com/1926584/76076813-dff47480-5f9f-11ea-89d4-5da044ef81fe.png)

**Comment by Siccity** [comment]
I didn't know of that feature, thanks.
