### ISSUE TITLE
More stable history in references viewlet

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#92073]
Currently, history entries in the references viewlet are not dynamic. That often leads to a non working or bogous behaviour, e.g the lines have moves and reference search is now run on a different symbol or not at all anymore. This is to add some additional word-refinding-logic so that history is somewhat dynamic.

**Comment by connor4312** [comment]
@jrieken can you add verification steps?

**Comment by jrieken** [comment]
To verify:

* Search for symbol `foo`
* clear results
* in the same add or remove lines above symbol `foo`
* re-run search from history and make sure it still searches for `foo`
