### ISSUE TITLE
IntelliSense, Formatting & Overall Extensions stop working after copy/pasting extremely long strings - SVG Files / Minified Files

### ISSUE THREAD

**Issue by StanielPetrov** [microsoft/vscode#92071]
- VSCode Version: **1.42.1**
- OS Version: **Microsoft Windows 10 Home 1903 OS Build: 18362.657**

I've been having this problem for a long long time and i wanna report my observations in hope that it will get fixed, since i didn't manage to find other issues with this exact cause & effect. The problem occurs everytime when **SVG File** or **Minified File** containing very long strings is opened and you start copying and pasting long strings around. **Formatters**, **IntelliSense**, **Extensions**, **Emmet** e.t.c it all freezes or is stuck at loading. I really hope that this information will help you with fixing the problem guys.

Steps to Reproduce:

1. Open a Minified File or SVG with long path strings
2. Copy/Paste some very long strings or the entire contents of the file.
3. Try using any Extensions, Formatter, Emmet or IntelliSense

Does this issue occur when all extensions are disabled?: **No**

Copying and Pasting long strings in SVG doesn't produce any visible problems when all extensions are disabled, but I think that it will be helpful to list the extensions i use here:

- **Auto Close Tag** - Jun Han
- **Auto Complete Tag** - Jun Han
- **Auto Rename Tag** - Jun Han
- **Bootstrap v4 Snippets** - Zaczero
- **Copy Relative Path** - alexdima
- **dark-plus-syntax** - dunstontc
- **Debugger for Chrome** - Microsoft
- **ESLint** - Dirk Baeumer
- **Flat UI** - Kaiyuan Liu
- **Format HTML in PHP** - rifi2k
- **Formatting Toggle** - tombonnike
- **GitLens** - Eric Amodio
- **Highlight Matching Tag** - vincaslt
- **HTML CSS Support** - ecmel
- **IntelliSense for CSS class names in HTML** - Zignd
- **JavaScript (ES6) code snippets** - charalampos karypidis
- **jQuery Code Snippets** - Don Jayamanne
- **JS & CSS Minifier (Minify)** - olback
- **JS JSX Snippets** - sky ran
- **Live Sass Compiler** - Ritwick Dey
- **Live Server** - Ritwick Dey
- **Markdown All in One** - Yu Zhang
- **markdownlint** - David Anson
- **Material Icon Theme** - Philipp Kief
- **npm** - egamma
- **npm intellisense** - Christian Kohler
- **Numbered Bookmarks** - Alessandro Fragnani
- **One Dark Pro** - binaryify
- **Path Intellisense** - Christian Kohler
- **PHP Intelephense** - Ben Mewburn
- **Prettier - Code Formatter** - Esben Petersen
- **Sass** - Syler
- **SCSS Formatter** - Sibiraj
- **SVG** - jock
- **SVG Snippets** - sidthesloth
- **SVG Viewer** - cssho
- **Vetur** - Pine Wu
- **Visual Studio IntelliCode** - Microsoft
- **VSCode Essentials Snippets** - Roberto Achar
- **vscode-icons** - VSCode Icons Team
- **vscode-styled-jsx** - niceSprite
- **Vue 2 Snippets** - hollowtree
- **Vue Peek** - Dario Fuzinato
- **Vue VSCode Snippets** - sarah.drasner
- **Vue.js Extension Pack** - Muhammad Ubaid Raza

Thank you for your amazing work!
Staniel P.

**Comment by amidesfahani** [comment]
Same problem.
