### ISSUE TITLE
VSC not saving files

### ISSUE THREAD

**Issue by DUCKYOUMICROSOFT** [microsoft/vscode#92075]
The file was "saved" a couple of times and today when I got back on the pc the file was empty. I have made myself a list of what else I need to do for a project and now 130 lines of the to-do list are gone.
This is the second time this had happened and after a simple google search, I see that this problem is old. I have used save as twice (always twice) and at the exit, there was no warning about saving. That means the file should save itself but at exit it deleted it. Well, the file stayed but the lines are gone.  So this is not getting fixed? Back to NPP it is

**Comment by DUCKYOUMICROSOFT** [comment]
Here more info. The program is running on windows, on a pc that is plugged into electricity. The weather is sunny today. 
what else do you need?

**Comment by DUCKYOUMICROSOFT** [comment]
Latest version, win10 insider edition, full VS package, have no time to reproduce the bug and it was a normal .txt file made with save as option

**Comment by piyush-kansal** [comment]
I am facing a similar issue. The Golang code changes are not getting saved. Here are the details of my VSC installation.

```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
