### ISSUE TITLE
MySQL Integration

### ISSUE THREAD

**Issue by adammendyk** [microsoft/vscode#92077]
Issue Type: <b>Feature Request</b>

Hi,
there is no chance to communicate vsc with MySQL 8.0 due to password scheme incompatibility where PyCharm is working quite well. I'd love to keep using vsc for its tidiness and I need to know is there any chance of solving this issue in a near future. I'm still learning but I'll have to choose IDE at the end.
Otherwise I like vsc a lot.
Best,
Adam

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 17.7.0

**Comment by IllusionMH** [comment]
/causedByExtension
This repo is only for editor issues and VSCode doesn't provide MySQL functionality out of the box.
You need to file this request in repo of extension you are using for MySQL.
