### ISSUE TITLE
Nested SQL block comments not formatted correctly

### ISSUE THREAD

**Issue by Conbhair** [microsoft/vscode#92078]
Issue Type: <b>Bug</b>

Open a new tab, change the language to SQL and paste the following:
```sql
/*
    /*
        SELECT 'hello1'
    */
    SELECT 'hello2'
*/

SELECT 'hello3'
```
If the formatting was correct, the hello2 line would also be green however it is displaying as if it's uncommented (when it's not). The only uncommented (non green) line here should be the last one with 'hello3'

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (20.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Are you sure this code is correct and not just error swallowed by DB?
Haven't seen language that supports nested comments, therefore first all `/*` inside comment are just text and first `*/` will end multiline comment. In your case you just have extra `*/` in the middle of  your code.

**Comment by Conbhair** [comment]
If you copy and paste the code I provided into SSMS, the formatting is different to how it is being displayed. If you also execute the code in SSMS, the only result you get back is 'hello3'. The issue i've raised isn't about the code being correct, it's the formatting display for SQL language which clearly shows SELECT 'hello2' as being not being commented whereas it is actually commented.

In SSMS (with results):
![Issue 92078 example](https://user-images.githubusercontent.com/5824259/75987546-ffc86180-5ee7-11ea-9928-39c6ebd11d27.PNG)

In Visual Studio Code:
![Issue 92078 example 2](https://user-images.githubusercontent.com/5824259/75987610-18387c00-5ee8-11ea-9eb2-1a50cf13c3f9.PNG)

**Comment by IllusionMH** [comment]
It's valid in T-SQL and looks like PostgreSQL also allows nested comments in most cases, on the other hand it's not supported in MySQL.

**Comment by alexr00** [comment]
Moved to the repo that owns the grammar we use for SQL: https://github.com/microsoft/vscode-mssql/issues/1654
