### ISSUE TITLE
Code dumps executable debug logging to stdout/err

### ISSUE THREAD

**Issue by jtnord** [microsoft/vscode#92080]
- VSCode Version: 1.42.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. start a cmd.exe
3. in the console type `"c:\Program Files\Microsoft VS Code\Code.exe"`  (using the actual path to code!)

Observe the console has debug log printed - even though there is no foreground process (this messes with other programmes at random times)

logging can be forced by clicking `[Help] ` -> `[Check for Updates]`

![image](https://user-images.githubusercontent.com/494726/75981308-284a5e80-5edc-11ea-8ac7-47496779de5b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Do not use `Code.exe` directly. Use `code`.

**Comment by jtnord** [comment]
So this behaviour is sub par because

if you want to use "code" to start via "winkey+r" then you will have registered "code.exe" in your app path.
then if you use the shortuct `"start code somefile"` from the command line then you get this bad behavour.

if you register code.cmd rather than code.exe then you get good behaviour from `start` but when using `winkey+r` you get an unneeded console window.

there is no way to not have some bad behaviour as far as I can tell.

**Comment by jtnord** [comment]
as designed is still a bug in the design - but I can not re-open this.

**Comment by jtnord** [comment]
this does not work as expected either.

it is normal for users to register [APP_PATHS](https://helgeklein.com/blog/2010/08/how-the-app-paths-registry-key-makes-windows-both-faster-and-safer/) to save typing.

if you register `code.bat`  then `winkey+r code` will open a console window, yet `start code` from a cmd.exe will do the right thing.
if you register `code.exe` then you get a working `winkey+r code` but the behaior described above.
