### ISSUE TITLE
not closed connections

### ISSUE THREAD

**Issue by Starling2804** [microsoft/vscode#92087]
:8080       :::*             LISTEN               14946/__debug_bin   
:1:8080    ::1:44744  ESTABLISHED   14946/__debug_bin   
:1:44744  ::1:8080    ESTABLISHED   1738/chrome --type= 

conns still alive after shut down VSCode&Browser.
cant start app:  "8080 already in use"
it makes me rebooting every time

**Comment by Starling2804** [comment]
i use http localhost connections. suddenly, during debug session text "address 8080 already in use" appeared in the debug console. So, i shut down VS Code and my browser, chrome. Then i check ports in terminal. There was 3 rows containing "8080". Seems like "__debug_bin" at the end of them means that this process  was started by VS Code.

**Comment by weinand** [comment]
What type of debugging are you using?

**Comment by Starling2804** [comment]
I press f5, sometimes run in terminal С уважением,Саркисов Мосес17:20, 9 марта 2020 г., Andre Weinand <notifications@github.com>:What type of debugging are you using?

**Comment by weinand** [comment]
Sorry, but "F5" is not a helpful answer as F5 starts the debugger that the user has selected in the launch configuration drop down, but I don't know what debugger extensions you have installed and which one you have selected...

So let me try to ask again with different wording: 
what debugger extension do you have installed and what are you using?
E.g. Node.js, Python, C++, PHP, etc.

**Comment by Starling2804** [comment]
Sorry, my English is bad. I installed some Golang packages, may be i can just send you some VS Code journal? Is there somthing like "make response" button?-- С уважением,Саркисов Мосес+ 7 (915) 014-37-68mos575@yandex.ru

**Comment by weinand** [comment]
So you are debugging "Go", correct?

**Comment by Starling2804** [comment]
Yes, you are right. С уважением,Саркисов Мосес18:22, 10 марта 2020 г., Andre Weinand <notifications@github.com>:So you are debugging "Go", correct?

**Comment by weinand** [comment]
Please file this issue against the GO extension: https://github.com/Microsoft/vscode-go/issues

**Comment by Starling2804** [comment]
Ok, thank you! С уважением,Саркисов Мосес18:42, 10 марта 2020 г., Andre Weinand <notifications@github.com>:Please file this issue against the GO extension: https://github.com/Microsoft/vscode-go/issues
