### ISSUE TITLE
Remote Editing Can't Open Multiple Windows

### ISSUE THREAD

**Issue by jeremyhawkins1** [microsoft/vscode#92088]
Issue Type: <b>Bug</b>

When editing in one document either locally or on a remote workspace when trying to open another window to another remote workspace (one the same server or a different server) the additional windows will not open.

the error is the vscode can't make a connection to a non-existing pipe.

If I close all other windows and then open the remote workspace it works.  Can only have one remote workspace opened at a time.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'SSH' failed: The process tried to write to a nonexistent pipe

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.16GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The process tried to write to a nonexistent pipe
</details>Extensions: none

**Comment by roblourens** [comment]
This should work. Could you share the log from the Remote-SSH output channel in the window where it doesn't work? It sounds like it would be an unrelated error. But it sounds like the same remote is working for you when it's the only window opened.
