### ISSUE TITLE
Feature request: terminal cursor that matches editor cursor style

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#9208]
It would be great if there was an option for the terminal cursor style to match the editor cursor style, or at least an option to change the default terminal one (block).

**Comment by kennytm** [comment]
Fixed in 553baf9b5a9d9b522d38dfee76e70fd3e20f0161? You can change the `terminal.integrated.cursorStyle` setting in 1.9 (Jan '17).

**Comment by Tyriar** [comment]
Yes this is fixed, thanks for pointing it out @kennytm :smiley:
