### ISSUE TITLE
Open Folder by command line

### ISSUE THREAD

**Issue by shpsyte** [microsoft/vscode#92095]
Issue Type: <b>Feature Request</b>

Version of VS Code: 1.42.1

We know that we can open the folder by menu, however, will be amazing if we can open by command line, instead of use "code ."

Could be "code .."
and just open the current folder without other instance of Vscode

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-88-generic

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide what you try, what you expect and what is actual behavior?

`code .` opens current folder, in the same way you can open any folder `code ~/.ssh` as well as one level above `code ..` (or you can try `code ../`)

Moreover you can specify `-n` to force new window or in your case `-r` to open folder in latest opened window.

Just tried on Windows and works as expected: I have 2 code instances opened (project1 and project2, later is active) I'm in separate terminal app inside of `~/project3/node_modules` and run `code -r ..`. Window with project2 is reloaded with project3 (as expected - not in `node_modules`)

**Comment by shpsyte** [comment]
Thanks for your quick answer @IllusionMH  

I see now the parameter -r to open the folder in current opened windows I.

This was what I am looking for.
