### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/vscode#921]
I am not sure if this is a vscode issue or something with the integration with the language services in TypeScript.

When I have a project running off of TypeScript 1.6.2, the editor behaves as normal.  When I upgrade the project to TypeScript 1.7.3, in the editor I constantly am getting `ERROR: Cannot read property 'kind' of undefined`.  I am not sure how to get a stack trace of these errors.  Reverting the project back to 1.6.2, doing an `npm install` fixes the issue.

![vcode issue](https://cloud.githubusercontent.com/assets/1282577/11531090/2e0150ae-98f2-11e5-86b2-27ee3f53ddc6.gif)

**Comment by kitsonk** [comment]
Also, this was both on 0.10.2 and 0.10.3.

**Comment by dbaeumer** [comment]
@kitsonk did you configure VSCode to use the install typescript using typescript.tsdk. And is the code public somewhere so that I can try to reproduce?

**Comment by kitsonk** [comment]
> did you configure VSCode to use the install typescript using typescript.tsdk

I am not sure what you are referring to.  In all cases I have been using `npm` to install TypeScript and exiting and launch VSCode before and after the install.  I have moved back and forth from 1.6.2 to 1.7.3 a few times.  I am on OSX.  I have installed the `tslint` plugin as well.  Other than that, it is a vanilla VSCode install.  My user settings are:

```json
{
	"editor.fontFamily": "Hack",
	"editor.glyphMargin": true,
	"editor.tabSize": 4,
	"editor.formatOnType": true,
	"editor.renderWhitespace": true,
	"editor.wrappingColumn": 0
}
```

> And is the code public somewhere so that I can try to reproduce?

Yes, it is available at [kitsonk/actions](https://github.com/kitsonk/actions).  It should be fairly straight forward:

```sh
git https://github.com/kitsonk/actions.git
cd actions
vi package.json
npm install
code .
```

**Comment by egamma** [comment]
Can you try to uninstall `tslint` and reproduce the problem, this helps us narrow down the issue.

**Comment by kitsonk** [comment]
Yup, that was it...  Removed `tslint` restarted VSC, migrated back to TypeScript 1.7.2 for the project, restarted VSC, no error...  Installed `tslint` 0.5.1, restarted VSC, issue returned.

How best to report issues with extensions?

**Comment by egamma** [comment]
Report the issue against microsoft/vscode-tslint please.

Am 02.12.2015 um 18:00 schrieb Kitson Kelly <notifications@github.com<mailto:notifications@github.com>>:


Yup, that was it... Removed tslint restarted VSC, migrated back to TypeScript 1.7.2 for the project, restarted VSC, no error... Installed tslint 0.5.1, restarted VSC, issue returned.

How best to report issues with extensions?

-

**Comment by kitsonk** [comment]
Ported, thanks.
