### ISSUE TITLE
Allow download extensions from different sources/marketplace

### ISSUE THREAD

**Issue by yhvicey** [microsoft/vscode#92106]
Is there any possibility that we can add different extension sources/marketplace (public, internal, even local folder) to download extensions from, just like NuGet feeds?

E.g. Besides downloading extensions from public VS Code extensions marketplace, one can:

1. Have an 'Preview Channel'-like thing which will host all preview/unstable extensions, etc.
1. Host a self-hosted extension marketplace and share private extensions to other colleagues, e.g. company-wide sharing

**Comment by prashantvc** [comment]
@yhvicey I am curious to know what is your use case to have a internal/local marketplace feed.

**Comment by yhvicey** [comment]
@prashantvc For example there's an internal programming language and I'd like to create an extension for it, however I'm not sure if publishing such extension (which includes syntax parser, language specific binaries and some other internal tools) would violate company compliance.
If there's an internal feed for VSCode users within the company, it'd be great for developing the plugin & get feedback & not get involved with compliance stuffs.
