### ISSUE TITLE
VS Code window crashes when discarding changes in a big file

### ISSUE THREAD

**Issue by CookiePLMonster** [microsoft/vscode#92109]
- VSCode Version: 1.42.1 x64 (user setup)
- OS Version: Windows 10 Pro 1903 x64

# Steps to Reproduce:
1. Have a big text file - my test case is a 750mb .log file. Contents seem to be irrelevant - I could reproduce it also with a 800mb .log file with nothing but "Foo" lines in it.
2. Open it with VSCode.
3. Press Ctrl+A to select all text, then press Delete to delete the contents.
4. Try to discard changes by selecting File -> Revert File

# Observed behaviour
VS Code window crashes:
![image](https://user-images.githubusercontent.com/7947461/76019000-569e5d00-5f21-11ea-920c-4ff01ffaa352.png)
Changes are not reverted on the next run if VS Code is configured to remember changes across sessions. This effectively leaves the user stuck with a modified file, unless they remove/rename the file, or save changes.

# Expected behaviour
VS Code should revert the entire file and continue as normal.

Does this issue occur when all extensions are disabled? **Yes**

**Comment by alexdima** [comment]
@bpasero Giving to you to first investigate why File > Revert File is crashing.

**Comment by bpasero** [comment]
Help wanted: F12 devtools -> heap monitor

**Comment by CookiePLMonster** [comment]
> Help wanted: F12 devtools -> heap monitor

Do I need to enable anything additional to get this to show up? Closest I've been able to find is DevTools window from under Help -> Toggle Developer tools

**Comment by bpasero** [comment]
Yeah I mean those devtools 👍

**Comment by CookiePLMonster** [comment]
I managed to record this using Memory -> Allocation Sampling. I apologize for delivering this in such a stupid way, but I haven't found a way to save a crash dump to a file or anything like this.
![image](https://user-images.githubusercontent.com/7947461/76142193-7cd01400-606b-11ea-94b2-c383a3955286.png)

Dumping a .heapprofile file seems to be impossible when the app is broken into a debugger, so:
![image](https://user-images.githubusercontent.com/7947461/76142206-b3a62a00-606b-11ea-96da-a54a2e466ddd.png)

To me it looks like vscode should instruct the user to reopen the file with a 4GB heap (like it does when opening very big files), but isn't doing that here?

**Comment by bpasero** [comment]
> To me it looks like vscode should instruct the user to reopen the file with a 4GB heap (like it does when opening very big files), but isn't doing that here?

Yes very likely, though we have file limits in place that should prevent us from opening such large files, so I wonder why there is no error thrown before reading the file. The limit is defined here: 

https://github.com/microsoft/vscode/blob/c2a6e09c7d5a9b5cfd090ced5c1d4548cb2d64b5/src/vs/platform/files/node/files.ts#L6

**Comment by CookiePLMonster** [comment]
> Yes very likely, though we have file limits in place that should prevent us from opening such large files, so I wonder why there is no error thrown before reading the file.

My test file itself is 900mb, so technically well below the limit. Might be that history is stored in a way which makes it inflate over this limit - although in that case it'd be optimal if vscode could detect this in advance and eg. warn the user that "the action they are about to perform (like in my case, removing contents of the entire file) requires more memory in order for history to work correctly".

**Comment by bpasero** [comment]
@rebornix I can reproduce and the crash seems to happen in piece tree:

![image](https://user-images.githubusercontent.com/900690/76288489-1b948480-62a7-11ea-9625-eb90c4ad2e2d.png)

I verfied on my end that I am just calling [`this.modelService.updateModel`](https://github.com/microsoft/vscode/blob/ffcd280b5382e89571e16b17c7157de0ed925b7f/src/vs/workbench/common/editor/textEditorModel.ts#L152) with the file on disk after reverting. 

The file I use is:
[file.txt.zip](https://github.com/microsoft/vscode/files/4310791/file.txt.zip)

Steps:
* open it
* select all -> delete
* close tab

**Comment by rebornix** [comment]
This is a typical OOM issue for the piece tree buffer. Most memory in the piece tree buffer is used in storing line breaks and tree nodes, the more lines a file has, the higher memory it will use.

**Comment by bpasero** [comment]
@rebornix can you mention the duplicate?

**Comment by rebornix** [comment]
We can use https://github.com/microsoft/vscode/issues/70433 to track this type of issues, where the file is relatively small but it has many lines.

**Comment by rebornix** [comment]
Also the exception won't happen with `split` again as with Alex's refactoring of undo/redo, the text will not be split anymore.
