### ISSUE TITLE
Show scopes errors in variables view rather than notification

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#92102]
Ref: https://github.com/microsoft/vscode-js-debug/issues/353

I tried returning an error to the UI when requesting `scopes` for async stacks. Right now this shows a notification to the user if `showUser: true`, and shows nowhere if it's false.

![](https://memes.peet.io/img/20-03-fca3fc16-2989-4b9d-b86a-aea47fab95d1.png)

It would be nice to show the error in the Variables view like we do if the variables request errors.

**Comment by isidorn** [comment]
For that we would have to introduce a scope placeholder for an error. Similar to how we have a variable error placeholder.
The error would need to be caught [here](https://github.com/microsoft/vscode/blob/2362584a626621a80ec4af3bea52d2f0513e9383/src/vs/workbench/contrib/debug/browser/debugSession.ts#L435)

**Comment by isidorn** [comment]
@connor4312 please provide some verification steps. Thanks

**Comment by connor4312** [comment]
Using a recent version of js-debug, have code like:

```
setTimeout(() => {
  debugger;
}, 1);
```

Once you hit the debugger statement, click on a stack frame before the "setTimeout" boundary. Verify that the variables view shows an appropriate error message, rather than being blank.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/78190139-48603580-7428-11ea-974f-ed55a11cc7a3.png)
If possible, it might be nicer to have it say something like "stack frame not valid past XXX boundary"  (setTimeout? event queue? idk)

**Comment by connor4312** [comment]
It looks like that error is coming from the old debugger, Jackson. The new debugger has a nicer message (show in the screenshot at the top) 🙂
