### ISSUE TITLE
Closing a duplicate view of an unsaved file closes both views

### ISSUE THREAD

**Issue by jaminthorns** [Microsoft/vscode#9210]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Create a new file and type some character into it
2. Go to another editor and open the new file with Command + P
3. Close either of the editors
4. You are asked if you want to save the file, and both views are closed when an action is selected

**Comment by bpasero** [comment]
Lets move to https://github.com/Microsoft/vscode/issues/8983
