### ISSUE TITLE
npm.exclude doesn't accept standard glob patterns for excluding folders

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#92114]
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (13.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.10.0
ng-template|Ang|0.900.15
scratchpads|bue|0.0.7
find-related|eam|0.9.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
kotlin|fwc|0.2.11
todo-tree|Gru|0.0.169
rest-client|hum|0.23.1
search-node-modules|jas|1.3.0
svg|joc|1.1.3
vscode-commitizen|Kni|0.8.4
vscode-duplicate|mrm|1.2.1
vscode-azureappservice|ms-|0.16.2
mssql|ms-|1.8.0
python|ms-|2020.2.64397
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1711
debugger-for-chrome|msj|4.12.6
java|red|0.58.0
vscode-xml|red|0.10.1
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0
vim|vsc|1.13.0
material-theme|zhu|3.2.3
</details>

Steps to Reproduce:

1. Open a project in VSCode with multiple `package.json` files located under a subfolder. This could be a multi-package project managed by Lerna for example.
2. Add `"npm.exclude": "<subfolder name>/**"` to `settings.json`.

   Scripts from npm packages in subfolder are not excluded from npm script explorer and task runner. This can be fixed by using the glob pattern `**/<subfolder name>/**` but this setting should accept other standard folder glob patterns such as `<subfolder name>/**`. Alternatively if this is expected behavior then the supported glob syntax should be documented.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
This would be straightforward to do, but would be a breaking change.
