### ISSUE TITLE
Incorrect SQL Syntax Begin/End Single Quote Textmate Scope

### ISSUE THREAD

**Issue by prayforwinter** [microsoft/vscode#92112]
- VSCode Version: 1.43.0-insider
- OS Version: Windows 10 Enterprise 1903

Steps to Reproduce:

1. Create a SQL syntax document. 
2. Enter SQL syntax containing single quotes: 
```SQL
SELECT * FROM dbo.Person
WHERE firstname = 'Ashleigh'
-- example: in the Nord theme the above opening quote is white, closing is green
ORDER BY birthdate DESC
```
3. Launch Developer: Inspect Editor Tokens and Scopes from the Command Palette.
4. Navigate cursor to left side of either single quote.
5. Note incorrect/missing begin/end single quote textmate scope.

**Actual:** 
Opening single quote scope reads _punctuation.definition.string.end.sql_ and the closing single quote *does not* have a textmate scope.

**Expected:**
Opening single quote textmate scope reads _punctuation.definition.string.begin.sql_ and closing single quote textmate scope reads _punctuation.definition.string.end.sql_

**Screenshot:**
https://i.imgur.com/RUjU07W.png

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
I agree that the first quote having and `end` scope is incorrect, but the closing quote does still have `string.quoted.single.sql` scope, so your theme could handle that better (the default Dark+ theme and the theme I use(One Dark Pro) both color the quotes nicely).

**Comment by alexr00** [comment]
Moved to owning repo
