### ISSUE TITLE
Language client is not ready yet error only in Insiders

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode#92124]
Repro steps:
1. Try to activate the CosmosDB Extension

Other information:
This started happening suddenly and has happened in the past.  Today, if you install the extension in Insiders, it will repro.  But if you try it in Stable, it doesn't.

Reported on our extension [here](https://github.com/microsoft/vscode-cosmosdb/issues/1334)

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.12.1
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.42.0-insider
Language: en

**Comment by dbaeumer** [comment]
Very likely caused by the extension itself. I will comment here: https://github.com/microsoft/vscode-cosmosdb/issues/1334
