### ISSUE TITLE
Electron Webview crashed when splitting editors

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#92128]
Steps: 

* Follow https://github.com/microsoft/vscode/wiki/Notebook-Smoke-Test to set up notebook
* Open `samples/runCode_iframe_form_15.ipynb` from https://github.com/rebornix/notebook-test
* Split the editor quickly after opening the notebook

1 out of 5 times the webview in original editor group crashed even though the DOM node for the original editor group is not modified (only size change)

![Kapture 2020-03-05 at 17 08 23](https://user-images.githubusercontent.com/876920/76040400-1086d080-5f04-11ea-81e9-34d4f654800e.gif)

When it happens, the webview content is now empty 

<img width="2139" alt="image" src="https://user-images.githubusercontent.com/876920/76040477-4c219a80-5f04-11ea-8d9e-d63eff92a409.png">

I'm also seeing https://github.com/microsoft/vscode/issues/92127 when this happened. If @deepak1556 or @mjbvz can provide steps about how to troubleshoot, I can provide more info.

**Comment by deepak1556** [comment]
This is most likely https://github.com/microsoft/vscode/issues/92420 , should be fixed in master.

**Comment by rebornix** [comment]
@deepak1556 thanks! I didn't seem to reproduce this issue any more.
