### ISSUE TITLE
Webview post message exception

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#92127]
After merging `rebornix/notebook` with master, I'm constantly seeing following error messages

```
Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.WebViewElement.getWebContentsId (/Users/penlv/code/vscode/out/vs/code/electron-browser/workbench/electron/js2c/renderer_init.js:3681)
    at HTMLElement.send (/Users/penlv/code/vscode/out/vs/code/electron-browser/workbench/electron/js2c/renderer_init.js:3711)
    at ElectronWebviewBasedWebview.postMessage (/Users/penlv/code/vscode/out/vs/workbench/contrib/webview/electron-browser/webviewElement.js:230)
```

Didn't see any real misbehaving but the error message explains what's happening.

**Comment by deepak1556** [comment]
We are calling a method of webview before it is available via the `dom-ready` event.

**Comment by mjbvz** [comment]
We wait on posting messages until our webview can post a message back to us: https://github.com/microsoft/vscode/blob/d16ffac0202c22528caab153a8df77f9a744d9fd/src/vs/workbench/contrib/webview/browser/baseWebviewElement.ts#L176

https://github.com/microsoft/vscode/blob/b75371ce023b2b7deaf6ab956064008e730cc09e/src/vs/workbench/contrib/webview/browser/pre/main.js#L581

Do you think we also need to wait for the `dom-ready` event?

**Comment by deepak1556** [comment]
I see that we post the message on `DOMContentLoaded`, technically this is correct as electron's `dom-ready` signal is based on the same just there is some delay due to ipc. And electron internal webview relies on this signal to validate the method calls, I will see if we can change this on electron side to rely on `DOMContentLoaded` but for now changing to `dom-ready` on our end should fix the issue.

Nature of Call:

```
<--- call is received on renderer side by webview and available to users --->
<--- electron emits dom-ready event on this call to JS --->
content::WebContentsObserver::DOMContentLoaded
<--- sends ipc to main process ---->                                  // async
------------------------------------------------------------->  // sync blink emits DOMContentLoaded
blink::LocalFrameClient::DispatchDidFinishDocumentLoad
blink::FrameLoader::FinishedParsing
blink::Document::FinishedParsing
```

**Comment by mjbvz** [comment]
10f5103a12e0aac3a452333ee466a5208ab1a9ce added an await on `dom-ready`. @rebornix Please let me know if you still see this issue after the change
