### ISSUE TITLE
Error: Dynamics 365 BC

### ISSUE THREAD

**Issue by palhido82** [microsoft/vscode#92123]
Authenticated as user 'xxxxxx'. Please note that these credentials are cached. Clear the credentials cache to authenticate as another user.

Reason: Service Unavailable

Error: a server-side error occured while processing the request.

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.

Thanks

**Comment by weinand** [comment]
/needsMoreInfo

Please provide reproducible steps.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
