### ISSUE TITLE
[Feature Request] Open with external Editor in Context Menu

### ISSUE THREAD

**Issue by SDXC** [Microsoft/vscode#9213]
Sometimes you may want to open a file in a different editor (e.g. large files or other IDEs), but you can't directly do that within VSCode. It would be nice to configure an external editor (path to exe in the settings) that would be added to the context menu of the file selection.

As of now all the functions and plugins I tested only work with opened files, but too large files can't be opened in VSCode.

**Comment by hashhar** [comment]
I implemented this right now. I'll submit a PR.

**Comment by mrmlnc** [comment]
IMO, this functionality is a good candidate for expansion.

**Comment by hashhar** [comment]
@mrmlnc I don't know if vscode provides APIs to do that. I implemented it in the core and have submitted a PR. But yes, if there are the required APIs it SHOULD be delegated to an extension.

**Comment by mrmlnc** [comment]
@hashhar,

Menu Items and Context Menu Entries: https://code.visualstudio.com/updates/June_2016#_extension-authoring
Open: https://github.com/sindresorhus/opn or https://github.com/pwnall/node-open or your code in `EditInExternalEditor` class.

**Comment by hashhar** [comment]
So, what should I do now? Do you know any similar extension? Maybe I can submit a pull to it instead.

**Comment by hashhar** [comment]
@SDXC It seems [this extension](https://marketplace.visualstudio.com/items?itemName=lfurzewaddock.vscode-opn) does what you requested?

**Comment by SDXC** [comment]
@hashhar thanks for your efforts but this extension does not do what I need. It's somewhat more complex designed than it helps, I think. I need an extension or built-in functionality that lets me open any file in a configured editor (for example notepad++). Your suggested extension doesn't provide the possibility to open "any" file in an external editor (limited) and like every other extension that uses vs-commands it can't open files that are too big for vscode. For the vs-command or shortcut to work you have to open the file within vscode. That's why I'd like to have a contextmenu entry for that in the file selection view.

**Comment by mrmlnc** [comment]
@SDXC, I can write this extension on this week.

@hashhar, if you want to write this extension, I'll be happy with that.

> So, what should I do now?

It's your PR and I am not a team member VS Code. So I would advise to wait @bpasero.

**Comment by hashhar** [comment]
@mrmlnc I think you should go ahead and author an extension or maybe add the feature to lfurzewaddock/vscode-opn because honestly I don't think I'll be able to maintain the extension.

**Comment by Urethramancer** [comment]
I miss this sort of functionality a lot lately.

There should be configurable external apps and a default "open" option which uses the system default for that file type. Then you use the short name for each app in each file type definition. Just a configurable extension would be enough.

If the underlying OS lacks a command line program to open files with the default editor, that's a different problem to solve. On macOS there's /usr/bin/open, and I think Windows supports simply launching with Explorer. Ubuntu has xdg-open, so I think the major systems are covered.

**Comment by hashhar** [comment]
@Urethramancer See the [extension](https://www.github.com/lfurzewaddock/vscode-opn) we are talking about above.

**Comment by Urethramancer** [comment]
Thanks, looks decent :)
