### ISSUE TITLE
vscode-terminal powershell Text display disorder

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#92131]
- VSCode Version: 1.42
- OS Version:win10x64
![vscode power shell ](https://user-images.githubusercontent.com/1876302/76047509-e124a200-5f9d-11ea-9ff3-86e3201c0a00.png)

**Comment by heartacker** [comment]
vscode setting:
fontsize:14
fontfamily: Cascadia Code,

**Comment by Tyriar** [comment]
This is likely a powershell issue
