### ISSUE TITLE
Enhance dotfiles by allowing a global extensions.json

### ISSUE THREAD

**Issue by Ace-Cassidy** [microsoft/vscode#92130]
**Use Cases:**
 As a user who switches computers/images often I would like to have a portable set of configurations for vscode to avoid manually reinstalling my extensions each time.

**Description:**
I have a set of dotfiles located at for example https://github.com/Ace-Cassidy/dotfiles. I can easily save a settings.json or keybindings.json and place it into .config/Code/User to transfer my settings to a new machine. I would like to be able to place an extensions.json into this folder and have it provide an 'install all' popup when missing extensions are detected.

**Comment by sandy081** [comment]
VS Code is providing Sync OOB from next insiders which will sync 
- Settings, Keybindings, Extensions & Global State.
