### ISSUE TITLE
Feedback on "Ok to install"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92139]
Just a small polish:

![image](https://user-images.githubusercontent.com/900690/76063710-8e8cbb00-5f88-11ea-841d-d2784c94ea3b.png)

I find this wording not so ideal. How about something like "Do you want to install the extension?"

**Comment by aeschli** [comment]
But wouldn't that mean I have to change the buttons to Yes /  No?

**Comment by bpasero** [comment]
I think the button is fine. Since this is pretty much a Yes | Cancel thing, having 1 button and the X for close is ok imho.
