### ISSUE TITLE
ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92138]
Seeing this running our integration tests, I think it originates from https://github.com/microsoft/vscode/blob/811c4b5552e4165262cb25eeb6480e04c295bd9a/src/vs/workbench/contrib/webview/electron-browser/webviewProtocols.ts#L18

**Comment by mjbvz** [comment]
https://www.electronjs.org/docs/api/breaking-changes-ns#planned-breaking-api-changes
