### ISSUE TITLE
[Git Extension] ApiRepositoryState.refs seem to contain a wrong commit hash

### ISSUE THREAD

**Issue by ole1986** [microsoft/vscode#92146]
- VSCode Version: 1.42.1
- OS Version: Win 10 / Linux
- Git CLI version: 2.11

Steps to Reproduce:

1.  mkdir testrepo && cd testrepo 
2. echo "testcontent" > testfile
3. git add .
4. git commit -a -m "initial commit"
5. git log --oneline

Result:
**e9cba6f** (HEAD -> master) Initial commit

**Adding a tag**

1. git tag -a 1.0.0 -m "Version 1.0.0"
2. git log --oneline

Result:
**e9cba6f** (HEAD -> master, **tag: 1.0.0**) Initial commit

Calling `extensions.getExtension<GitExtension>('vscode.git')!.exports.getAPI(1).repositories[0].state.refs` returns the following:

```
[
    {
        "name": "master",
        "commit": "e9cba6fa041b7d8f53ce8365835695cee25be935",
        "type": 0
    },
    {
        "name": "1.0.0",
        "commit": "099eb26e234e6742bf000b756bc58ee8a8d4f8ba",
        "type": 2
    }
]
```

While commit "099eb26e234e6742bf000b756bc58ee8a8d4f8ba" does not exist in the repository

**Comment by ole1986** [comment]
Question is here if its intended to not have a annotation tag hash dereferenced

**Comment by joaomoreno** [comment]
Great catch. We might have to replace [this](https://github.com/microsoft/vscode/blob/1ef5d986de644af7496f91b80569c9a01435905d/extensions/git/src/git.ts#L1780-L1780) with:

```
git for-each-ref --format "%(refname) %(objectname) %(*objectname)"
```

**Comment by stschoberg** [comment]
Hey João. I'd like to fix this. Seems like a trivial issue for a first time commit to the codebase.

**Comment by ole1986** [comment]
This is not yet included in the VSCode insiders preview, right?

**Comment by joaomoreno** [comment]
Exactly, the bot will remove the `unreleased` label and add `insiders-released` when that happens.
