### ISSUE TITLE
Insert multiline snippets

### ISSUE THREAD

**Issue by taoqf** [microsoft/vscode#92140]
I would like use the api to insert multiline snippets, just like the action like code add user snippets. But I could not find a way. any clue?

**Comment by weinand** [comment]
https://stackoverflow.com/questions/45082780/how-do-i-add-a-snippet-programmatically

**Comment by taoqf** [comment]
@weinand Thank you. I still could not find any clue to add this?

```ts
const foo = 'bar';
if(foo) {
  console.log('true');
}else{
  console.log('false');
}
```

I just could not build SnippetString with multiline strings. If i do, the format would not be write if I insert into this section:

```ts
function myfun(){
  if (true) {
    if (flase){
      // insert snippet here
    }
  }
}
```

After I insert snippet here.

```ts
function myfun(){
  if (true) {
    if (flase){
      const foo = 'bar';
if(foo) {
  console.log('true');
}else{
  console.log('false');
}
    }
  }
}
```

The indent would not be correct.

But If I edit user snippet and use vscode command insert this snippet manually. the format is good.

My point is **multiline**. sorry for my poor english.

**Comment by taoqf** [comment]
@weinand
