### ISSUE TITLE
Needs to provide ability for watching sources from github inside vs code 

### ISSUE THREAD

**Issue by ndomanovskiy** [microsoft/vscode#92147]
I work with net core every day. Sometimes i really want to watch inside some classes, for example, i want to understand how i can use my own ```IGroupManager``` in Signalr Core, or maybe i want to understand possibility of catch ```NRE``` when i use ```MemoryCache.Get```. For investigate this thing i every time go to browser, go to github, and trying to find necessary sources there. 

It is possible to watch sources from github inside my visual studio code? Maybe you know about extensions which can decompile sources or redirect me to github page with source code.

This can be useful on other programming platforms, not only netcore.

**Comment by weinand** [comment]
You can easily navigate from source in your VS Code workspace to the corresponding github source via this extension: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-github

**Comment by ndomanovskiy** [comment]
@weinand i tried to investigate this extension yesterday. can you provide any example how can i use this for different repository?

Little example of what i want:
1) I have my own repository **A** on netcore
2) I use some libs in my project from nuget packages which code hosted on github (for example its repo **B** and **C**)
3) i want to navigate on source code of this libs directly to github in one click

How can i do this with this extension?

**Comment by weinand** [comment]
Sorry, but I do not have time to investigate user problems unrelated to VS Code.
Please ask on StackOverflow.
