### ISSUE TITLE
TypeScript extension breakdown

### ISSUE THREAD

**Issue by mahorad** [microsoft/vscode#92141]
Issue Type: <b>Bug</b>

Always when editing JavaScript code

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-react-hooks-snippets|ant|0.1.2
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
gc-excelviewer|Gra|2.1.33
beautify|Hoo|1.5.0
open-file-from-path|jac|1.3.3
vscode-codemetrics|kis|1.24.0
rainbow-csv|mec|1.6.0
vscode-docker|ms-|0.10.0
mssql|ms-|1.8.0
python|ms-|2020.2.64397
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
debugger-for-chrome|msj|4.12.6
autodocstring|njp|0.4.0
indent-rainbow|ode|7.4.0
java|red|0.57.0
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.6.0
code-spell-checker|str|1.8.0
serverless-ide-vscode|Thr|0.5.16
vscode-fold-level|vik|0.0.12
vscodeintellicode|Vis|1.2.5
colonize|vms|2.2.2
vscode-java-debug|vsc|0.25.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0
quokka-vscode|Wal|1.0.282
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
city-lights-icon-vsc|Yum|1.1.3

(8 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
