### ISSUE TITLE
Keeping indentation in commit msg box changes spaces to tabs

### ISSUE THREAD

**Issue by Alex131089** [microsoft/vscode#92148]
- VSCode Version: 1.42.1
- OS Version: Win 10 1809

Steps to Reproduce:

1. In a project using a CVS (Git in my case), enter commit message, indenting a line using spaces
2. Type enter
3. Next line will be indented using tab and not spaces as the previous line

Does this issue occur when all extensions are disabled?: Yes

Example of resulting commit msg: 
```md
test

  * line 1[enter]
	* line 2
```

Related custom settings:
```jsonc
{
    "editor.detectIndentation": true, // default
    "editor.tabSize": 2,
    "editor.insertSpaces": false,
}
```

Edit: I don't think this behavior was present a few month ago

**Comment by weinand** [comment]
Yes, the commit box is now a full VS Code editor and supports all features...

**Comment by joaomoreno** [comment]
Since you have `"editor.insertSpaces": false`, you're using tabs for indentation in that editor too. Would you like a different setting for that editor?

**Comment by Alex131089** [comment]
I don't know about a setting, do what you consider best, but I don't consider the commit box as "an editor" and the result is currently awful as you can see.
Do I need to open another issue now it is closed?
