### ISSUE TITLE
Poor framerate/noticeable lag when expanding/collapsing/scrolling through File Explorer

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#92151]
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
```

## Description

I noticed that when I expand/collapse a large folder (ie. _node_modules_), or when I scroll through such a large folder, there is a significant framerate drop in the scroll and a noticeable delay in the expansion/collapse of the folder after I click on it. I have captured a performance report and it seems that there are tens of forced reflows per folder expansion/collapse, causing the UI update to take as long as 150-200ms on my machine. Those same forced reflows also happen when scrolling through the File Explorer with many files visible. DevTools performance reports are attached below.

## Steps to Reproduce:

1. Expand/collapse a large folder in the File Explorer, or scroll through a large expanded folder in it
2. Notice observable delay in UI after clicking on the folder / degraded framerate during scrolling

Does this issue occur when all extensions are disabled?: **Yes**

## Expected behaviour

Buttery-smooth scrolling through the files/near-instantaneous folder expansion when clicking on a folder with large number of files 🙏 

## Performance profiles

[explorer-expanding-forced-reflow.json.zip](https://github.com/microsoft/vscode/files/4298142/explorer-expanding-forced-reflow.json.zip)
[explorer-scrolling-forced-reflow.json.zip](https://github.com/microsoft/vscode/files/4298143/explorer-scrolling-forced-reflow.json.zip)

**Comment by deluksic** [comment]
I also noticed this. Even simply mousing over from text editing area to explorer and back causes excessive reflows:


[Profile-vscode-slow-mouseover.zip](https://github.com/microsoft/vscode/files/4298643/Profile-vscode-slow-mouseover.zip)

**Comment by isidorn** [comment]
Thanks for filling this issue. Looking at the performance trace the `measureItemWidth` is taking up most of the time. Thus I am assuming you are using 	`"workbench.list.horizontalScrolling": true`
This has a performance implication which we are all aware, I am just surpsied that the setting descripton does not have a warning against this.
So please disable this setting if you want good perfomance.

**Comment by robertrossmann** [comment]
I can confirm that disabling horizontal scrolling returns performance to buttery-smooth levels. 🚀 Thanks for the tip. Since you know about the issue I guess this may be safely closed. A note about performance degradation would be a much welcome addition, indeed! I enabled that setting a long time ago and completely forgot about it, just noticed that performance issue today. 🤷‍♂

**Comment by isidorn** [comment]
I have changed the description of the setting such that it mentions a warning: that enabling the setting has a performance implication.
Thanks for sending good performance analysis.
Thus closing this
fyi @joaomoreno
