### ISSUE TITLE
vscode use symlink path instead of target path

### ISSUE THREAD

**Issue by Acidham** [microsoft/vscode#92150]
vscode auto-detects the language mode of a file but when I open a symlink .file vscode opens the target file, which in my case does not contain the dot. 

Better would be when vscode opens the symlink .file which allows the language mode to auto detect as environment variables.

**Comment by bpasero** [comment]
I am not sure I understand fully, can you give an example how to reproduce?

It is expected that VSCode does not alter the symlink when you open it. The tab should show the symlink as path, not the target.

**Comment by Acidham** [comment]
I am not sure if this happens on e.g. python files as well but for .files I can see that behavior. 

I symlinked ~/.zshrc → to /somewhere/zshrc (without the dot)

I am opening ~/.zshrc via drag and drop from Finder (dd to vscode in Dock). Maybe it is an issue with Finder that Finder translates it into target (/somewhere/zshrc)

**Comment by bpasero** [comment]
If it only reproduces via DND through Dock, it is likely a macOS issue. Can you verify?

**Comment by Acidham** [comment]
yep that's my assumption as well. I created the issue without testing via command line. For now using command line is sufficient, from my POV.
