### ISSUE TITLE
VSCode CPU Utilization on macOS Catalina

### ISSUE THREAD

**Issue by collin-miller** [microsoft/vscode#92154]
- VSCode Version: 1.42.1
- OS Version: macOs Catalina 10.15.3

Steps to Reproduce:

Open VSCode with a moderately sized mono-repository and Code Helper (renderer on macOS) is running on 15 threads and >250% of CPU (this metric seems strangely defined since the user CPU is nowhere near the this amount). VS Code Alone is consuming > 20% of available CPU (User CPU) for more than 20 minutes since opening.

Does this issue occur when all extensions are disabled?: Yes (I disabled the extensions one by one in an attempt to identify the culprit).

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by collin-miller** [comment]
@bpasero I'm unable to replicate the behavior today without the extensions enabled. The behavior I had seen in activity monitor didn't reflect the issue I had been seeing last week. However, it does appear a
large amount of CPU is being utilized by an electron process (` 666	    33	  8254	       electron_node package.js`). I'm assuming this has something do do with the JavaScript extension?


<b>With Extensions Eabled</b>:

```
Version:          Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS Version:       Darwin x64 19.3.0
CPUs:             Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)
Memory (System):  16.00GB (2.95GB free)
Load (avg):       6, 12, 9
VM:               0%
Screen Reader:    no
Process Argv:     .
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    1	    98	  8220	code main
    0	    66	  8230	   gpu-process
    2	   213	  8232	   window (Welcome — CloudSentry)
    5	    82	  8235	     extensionHost
    0	    33	  8236	     watcherService
    0	    33	  8252	     searchService
  666	    33	  8254	       electron_node package.js 
    0	    33	  8241	   utility
    2	   131	  8255	   shared-process
    0	     0	  8271	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (Welcome — CloudSentry)
|    Folder (CloudSentry): more than 35459 files
|      File types: go(3568) py(2269) bazel(1190) xml(463) rst(406) txt(405)
|                  h(367) c(317) sh(311) runfiles_manifest(304)
|      Conf files: package.json(22) makefile(21) cmake(11) tsconfig.json(3)
|                  sln(3) settings.json(2) tslint.json(2)
|                  gulp.js(1)```

<b>With Extensions Disabled</b>:

```
Version:          Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS Version:       Darwin x64 19.3.0
CPUs:             Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)
Memory (System):  16.00GB (3.04GB free)
Load (avg):       5, 10, 9
VM:               0%
Screen Reader:    no
Process Argv:     . --disable-extensions
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    4	    98	  8320	code main
    0	    66	  8330	   gpu-process
    7	   213	  8332	   window (Welcome — CloudSentry)
    0	    66	  8335	     extensionHost
    0	    66	  8336	     watcherService
    0	    33	  8357	   utility
    2	   115	  8375	   shared-process
    0	     0	  8390	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (Welcome — CloudSentry)
|    Folder (CloudSentry): more than 36190 files
|      File types: go(3568) py(2316) bazel(1190) h(465) xml(463) txt(406)
|                  sh(311) c(311) runfiles_manifest(304) bzl(275)
|      Conf files: package.json(22) makefile(21) cmake(11) tsconfig.json(3)
|                  sln(3) settings.json(2) tslint.json(2)
|                  gulp.js(1)
```

**Comment by roblourens** [comment]
I'm not sure why it shows `electron_node package.js ` under the searchService. If a search is happening, it should show the ripgrep command is being run. But I assume that's what's happening? Does it show basically the same thing if you try this again?

Typically this is due to an extension triggering an expensive search, but you said it happens when extensions are disabled. To check why a search is being triggered, you can run "Set Log Level", pick Trace, then find the search logs
