### ISSUE TITLE
TypeScript - Crashes multiple times in a row

### ISSUE THREAD

**Issue by TimmJensen** [microsoft/vscode#92155]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
gutensnip|ash|1.0.5
atlascode|atl|2.4.9
vscode-database|baj|2.2.0
vscode-intelephense-client|bme|1.3.11
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-clock|Com|0.0.1
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
githistory|don|0.6.1
es7-react-js-snippets|dsz|2.6.0
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
apacheconf-snippets|eim|1.3.0
LogFileHighlighter|emi|2.7.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.7.0
auto-close-tag|for|0.5.6
vscode-yarn|gam|1.7.0
beautify|Hoo|1.5.0
composer|ika|0.7.1
vscode-pigments|jas|2.0.0
rainbow-csv|mec|1.6.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.15
vscode-duplicate|mrm|1.2.1
language-gettext|mro|0.1.1
vscode-docker|ms-|0.10.0
atom-keybindings|ms-|3.0.6
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1711
debugger-for-chrome|msj|4.12.6
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.2
vscodeintellicode|Vis|1.2.5
vscode-icons|vsc|10.0.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0

(4 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
