### ISSUE TITLE
Use Token Modifier to set editorUnnecessaryCode.opacity through SemanticTokens API

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode#92157]
When using the proposed Semantic Tokens API #86415 , I'd like to be able to use a Token Modifier to de-emphasize _variable_ or _function_ Token Types in the code open in the active editor that aren't being used.

From the [Semantic Tokens API Documentation](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) there doesn't seem to be a way to do this.

I'm proposing we have have a specific 'unnecessary' Token Modifier and then have a way to style  this with a _semanticTokenStyleDefaults_ 'opacity' property setting.

**Comment by alexdima** [comment]
Both semantic tokens and diagnostics are semantic code annotations, and they result in the color changing, but at this time the only API we have for setting this is via diagnostics that have the tag `DiagnosticTag.Unnecessary`.

I am not in favor of adding competing API that gives two distinct ways to achieve the same effect.

Diagnostics are established, and are used also for code fixes, which can participate on save, show lightbulbs, and a custom message. Also, diagnostics can show in the problem panel when a severity of at least warning is used.

**Comment by pgfearo** [comment]
@alexdima Thanks, I wasn't aware of the Diagnostics API as an alternative. In light of this, I'm happy to close this issue.
