### ISSUE TITLE
There is nothing in source control side window 

### ISSUE THREAD

**Issue by Saitamata** [microsoft/vscode#92159]
Issue Type: <b>Bug</b>

I used git in the vscode, and everything went ok. But after I update the vscode, 
the cource control window couldn't show anything. And I could do nothing when I want to commit my code to remote repository. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.95GB (8.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.12.9
vscode-language-pack-zh-hans|MS-|1.42.2
csharp|ms-|1.21.13
python|ms-|2020.2.64397
cpptools|ms-|0.27.0-insiders2
sublime-keybindings|ms-|4.0.6
markdown-preview-enhanced|shd|0.5.2
markdown-pdf|yza|1.4.2
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by Saitamata** [comment]
I have tried to set  both {"git.enabled": true} and  {"git.path": "C:\\Program Files\\Git\\bin\\git.exe"}

**Comment by Saitamata** [comment]
I have tried to set both {"git.enabled": true} and {"git.path": "C:\Program Files\Git\bin\git.exe"}，But it didn't work.

**Comment by joaomoreno** [comment]
What's the output of `Git: Show Git Output`?
