### ISSUE TITLE
Problems with crashes in the linux operating system

### ISSUE THREAD

**Issue by geissondaSilva** [microsoft/vscode#92152]
- VSCode Version: 1.42.1
- OS Version: Linux x64 4.15.0-76-generic

Steps to Reproduce:

1.Uses the vscode editor for angular, medium scale projects.

Does this issue occur when all extensions are disabled?: Yes

description: I am facing the following problem with vscode, in our company about 20 angular programmers use vscode for development, those using the linux mint operating system, version 19.3 are facing problems of locking in the operating system. The only way to solve this problem is to delete the repository, and clone navigate from a git repository. If you can resolve it, thank you.

**Comment by weinand** [comment]
/needsMoreInfo

Without info about the crashes we are not able to do anything.

For so-called "native crash" see https://github.com/microsoft/vscode/wiki/Native-Crash-Issues for how to get more information.
