### ISSUE TITLE
"Problems" filter criteria find nothing when a new Java file is selected on the "Explorer" panel

### ISSUE THREAD

**Issue by agigleux** [microsoft/vscode#92162]
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Install Language Support for Java: https://marketplace.visualstudio.com/items?itemName=redhat.java v0.58
2. Install SonarLint:https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode v1.15
3. Open a Java project having some Java files with some mistakes (code smells, bugs, ...)
4. Open the "Problems" tab
5. Select a .java file having some code smells raised either by Language Support for Java or SonarLint
6. Enter into the filter field of the "Problems"tab  the word: "sonarlint" to see only issues raised by SonarLint
7. Select another .java file on the Editor panel : the "Problems" tab is showing: "No results found for the provided filter criteria"
8. Select the first file by clicking on its name on the open files
9. Select the second file the same way by clicking on its name (not on the Explorer panel, on the open files) => you see the issues matching filter criteria

Does this issue occur when all extensions are disabled?: No

Thanks
Alex

**Comment by sandy081** [comment]
Are the problems shown without filter?

**Comment by agigleux** [comment]
Yes, when there is no filter, I can see all the "problems/code issues" raised by the two extensions.

**Comment by agigleux** [comment]
Maybe this screen recording will help to better understand the problem.

![92162](https://user-images.githubusercontent.com/1057037/76196548-b8ddb300-61ea-11ea-804d-452d6dac5832.gif)

**Comment by sandy081** [comment]
Can you please click on the funnel icon in the filter box and see if you have more filter enabled?

**Comment by agigleux** [comment]
I have this in the funnel icon:

![image](https://user-images.githubusercontent.com/1057037/76214953-03245b80-620e-11ea-9430-3e347ee8fa02.png)

**Comment by sandy081** [comment]
You have `Show Active File Only` filter on. Hence you are seeing problems only for the active editor. You have to disable this filter to see problems for all files.

**Comment by agigleux** [comment]
I'm sorry but when I double-click on the file on the left panel to open it, I consider that this file is becoming the active one so I don't understand why you consider that doing this action should not display the "Problems" of this file?
Or maybe we have a different definition of what is the "active file". To me, that's the file that is currently opened / selected, the one I'm editing / about to edit.

**Comment by sandy081** [comment]
Does the problems panel show errors when the above filter `Show Active File Only` is disabled?

**Comment by agigleux** [comment]
When the `Show Active File Only` is disabled, I confirm I see ALL the errors of my project and the filtering based on the word "sonarlint" is working fine: I see only the errors reported by SonarLint.
The problem is that I expect, thanks to the `Show Active File Only` to see only the errors of the currently active file which is for me the purpose of this `Show Active File Only` option.

The behavior of the "Problems" tab is correct when I click on one of the "Opened Editors" tabs but it is not correct when I open a new file (ie: when a new tab is added to the list of "Opened Editors").

Did you manage to reproduce the problem on your side?

**Comment by sandy081** [comment]
Thanks for the explanation and understood the issue. 
Is it possible to provide a sample repo that can repro this issue?

**Comment by agigleux** [comment]
You can reproduce the problem with this repo: https://github.com/agigleux/analyzers-playground

**Comment by sandy081** [comment]
I tried to reproduce this using a sample extension and I do not see this issue. 

![Kapture 2020-04-06 at 12 15 00](https://user-images.githubusercontent.com/10746682/78548059-66e77780-7800-11ea-8b51-58c96c691685.gif)

Above repo is not helpful because there are no steps to repro other than just cloning. 
I would recommend to help me in giving a small sample that I can use to repro.

**Comment by agigleux** [comment]
The repo https://github.com/agigleux/analyzers-playground is the one I used to produce the small recorded video showing the problem.
You need first to open the file ValidationSocket.java, enter the filter "sonarlint" and then S4719_ExpectedIssue.java

**Comment by sandy081** [comment]
It seems I have to install other tools too?
