### ISSUE TITLE
terminal.integrated.cwd in User Settings only applies to the first Terminal when you have more than one Folder in your Workspace

### ISSUE THREAD

**Issue by mccarthyp-snet** [microsoft/vscode#92168]
Issue Type: <b>Bug</b>

Steps:
1. Set the terminal.integrated.cwd setting in User Settings.
2. Add a Folder to your Workspace.
3. Add a 2nd Folder to your Workspace.
4. Open a Terminal with Ctrl+`.
5. Open another Terminal with Ctrl+Shift+`.

2nd Terminal brings up the "Select current working directory for new terminal" picker.

Happens with extensions disabled.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
This keybinding should get the behavior you're after:

```
{ "key": "ctrl+shift+`", "command": "workbench.action.terminal.newInActiveWorkspace" }
```
