### ISSUE TITLE
Auto import not suggested when exported file is closed

### ISSUE THREAD

**Issue by madacol** [microsoft/vscode#92163]
Javascript exported constant is not suggested for **auto imports** if the exported file is closed

Issue Type: <b>Bug</b>

1. Open new window with an empty folder
2. Add new file with content `export const testexport = 123;`
3. Save and **close** last file
4. Add new file and write `teste` to trigger vscode suggestion (`testexport` is not suggested)
![image](https://user-images.githubusercontent.com/6379896/76093380-ddd5ea00-5f8e-11ea-9a76-a0e405679a16.png)
5. Open the exported file and try again the suggestion (now it works!)
![image](https://user-images.githubusercontent.com/6379896/76094086-06121880-5f90-11ea-94a0-01262c2d5221.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|15.53GB (0.37GB free)|
|Process Argv|/dev/shm --no-sandbox|
|Screen Reader|no|
|VM|57%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
I think you need to have `tsconfig.json` to ensure that files will be added to project.

Without config VS Code will create "anonymous" project but will include only opened editors there.

**Comment by madacol** [comment]
- Added empty `jsconfig.json` file
- Reloaded windows
It works fine now!

Do I need to put that file in the root folder of my projects for auto imports to fully work?

**Comment by mjbvz** [comment]
Yes, see https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson
