### ISSUE TITLE
Shortkey Presenter

### ISSUE THREAD

**Issue by bahrmichael** [microsoft/vscode#92167]
Similar to the [Presentation Assistant Plugin](https://plugins.jetbrains.com/plugin/7345-presentation-assistant) from IntelliJ I'd like to show my peers the shortcuts I'm using while working. That plugin shows overlays of the shortcuts you use, when in presentation mode. It differentiates itself from plugins that teach _you_ shortcuts, by showing every shortcut that you did use (e.g. Cmd+Shift+P), in contrast to the ones that you didn't use (e.g. click on debug).

![Example of the shortcut info](https://i.imgur.com/u1xtpfM.png)

I've seen that listening to events was [decided against](https://github.com/microsoft/vscode/issues/78091#issuecomment-518545491). Therefore this can't be added as a plugin. If you register a plugin for all the commands, then you run into endless loops trying to show a message and then invoking the command.

[Therefore I suggest](https://github.com/microsoft/vscode/issues/78091#issuecomment-521640092) an opt-in feature, which displays the command alongside the used shortcut.

Pseud-Code:

```
vscode.commands.listenToCommand('*', command => {
    vscode.overlay.show(command.name + ' was invoked with ' + command.shortcut);
});
```

I am happy to help with this, if it's something you find valuable for the core. I would need some guidance on which files are relevant for this, too.

**Comment by weinand** [comment]
see https://code.visualstudio.com/updates/v1_31#_screencast-mode

**Comment by bahrmichael** [comment]
Thank you!
