### ISSUE TITLE
Top stack frame indicator gets more yellow for each instance

### ISSUE THREAD

**Issue by SantoJambit** [microsoft/vscode#92165]
Not sure if this is a vscode issue or a debugger issue, but when I use jest to test something and the debugger stops at a breakpoint, it shows the current line highlighted with a semi-transparent yellow background.

The issue comes when multiple threads trigger this breakpoint, the line gets an additional semi-transparent background, making it more yellow with each thread that stops there. I.e. I get a full yellow, opaque background, which makes it hard to read the code.

Sideissue: When I then stop the debugger, the line stays yellow until I switch to another tab and back again (including the yellow arrow in the breakpoint column (between numbers and code).

**Comment by isidorn** [comment]
Yeah I marketed this as a feature so far. So users can see if mulitple threads are stopped on a line or just one.
I can see how this is an issue when too many threads are stopped and the text becomes unredable.

**Comment by isidorn** [comment]
Closing as will not fix, since we did not get too much negative feedback regarding this.
