### ISSUE TITLE
Blank workspace

### ISSUE THREAD

**Issue by sebastienwood** [microsoft/vscode#92161]
**Short description**: sometimes, the SSH extension gets into a locked state when launching VS Code. There are apparently locks in the server installation which never disappear. Fortunately, a quick workaround is to simply close VS Code and rm the locks from a standard terminal SSH into the server installation folder. However, when launching the SSH VS Code afterward the workspace appears to be blank quite often
![Capture d’écran, le 2020-03-06 à 09 20 31](https://user-images.githubusercontent.com/18282449/76091531-be898d80-5f8b-11ea-9f0e-413b6595d215.png)
.

- VSCode Version: 1.43 Insiders
- OS Version: MacOS 10.15.3

Steps to Reproduce:

1. Have a SSH session in VS Code that doesn't manage to connect
2. Remove manually the locks in the server installation folder
3. Relaunch VS Code SSH session and notice the workspace is blank.
(4). (Workaround) Relaunch again VS Code

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
It sounds like this is the same as https://github.com/microsoft/vscode-remote-release/issues/2518
