### ISSUE TITLE
Binary files are temporarily registered as working copies 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#92179]
From #92037

**Repro**
1. Open two image editor for the same resource side-by-side
1. Now reopen one of them using VS Code's standard editor (this should be VS code's standard binary file view)

**Bug**
Second editor crashes because there is already a working copy registered for it

The cause sis that during the reopen, we try to register a working copy while constructing a TextFileEditorModel for the binary resource. This happens before we detect the resource is binary and discard the TextFileEditorModel.

**Comment by bpasero** [comment]
@mjbvz this is not fixing it entirely I can still get into the issue if I:
* open 2 images side by side
* in the first: reopen with vscode
* then click on "open as text"

I feel we should first have the discussion how custom editors register as working copies if they are not using the text document based approach before doing this.

**Comment by bpasero** [comment]
Closing as discussed.
