### ISSUE TITLE
Can't navigate to nested declaration with `ctrl-p`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#9217]
- VSCode Version: 1.3.1
- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:

1. Open an empty TypeScript file.
2. Type:

```ts
function f1() {
    function f2() {
    }
}
```

3. Hit `ctrl-p` and type `f1`. You can successfully navigate to it.
4. Hit `ctrl-p` and type `f2`. You get "No results found".

Note that `#f2` and `@f2` work, as well as hovering over `f2`.

Due to #9215, I am using my globally installed typescript to reproduce this.

See also Microsoft/TypeScript#9576

**Comment by dbaeumer** [comment]
This is on purpose. Ctrl+P is scoped to global symbols and files to avoid pollution. If you want to see all symbols you can the Ctrl+T

**Comment by andy-ms** [comment]
It makes sense to leave out symbols that are only locally visible.
But, symbols may be globally available (though not 'true' JS globals, i.e. properties of the global object) even if they syntactically exist inside of nested declarations.

For example:

    // fooFn.d.ts
    declare module "foo" {
        // Globally available as `import { fooFn } from "foo"`
        function fooFn(): number;
    }

    // myFn.ts
    namespace MyNamespace {
        // Globally available as `MyNamespace.myFn`, or simply `myFn` if within `MyNamespace`
        export function myFn() {
            // Not globally available
            function someHelper() {}
        }

        // Not globally available
        function otherHelper() {}
    }

Since we namespace our code, the new behavior seems to require us to default to using `ctrl+t`.

In addition, the new behavior includes some symbols which exist un-nested but which are *not* globally available.

    // Globally available
    export function exportFn() {}
    
    // This file is a module, so a function declared without `export` is *not* globally available
    function anotherHelper() {}

I suppose this is a hard problem, so I'll close the corresponding issue in the TypeScript repo.
