### ISSUE TITLE
Auto detect color scheme breaks occassionally

### ISSUE THREAD

**Issue by Inventrohyder** [microsoft/vscode#92173]
Issue Type: <b>Bug</b>

It doesn't happen all the time but this is how I got  the issue on my mac

Set window: auto detect color scheme to true

Open a jupyter notebook that is in a git repository

Make some changes

Go to the source control tab

Click the jupyter notebook that has changes to see the diff

**The problem strikes there** It was at night for me so the theme should be dark and it was, but when I opened the diff, it automatically when to light mode (when it should be dark). Restarting vs code doesn't help

A work around is turning the feature off, then on

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.1
vscode-pull-request-github|Git|0.14.0
vscode-pull-request-github-insiders|Git|2020.2.8161
vscode-peacock|joh|3.5.0
chat|kar|0.31.0
vscode-docker|ms-|0.10.0
csharp|ms-|1.21.13
mssql|ms-|1.8.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.64397
cmake-tools|ms-|1.3.1
cpptools|ms-|0.26.3
github-issues-prs|ms-|0.9.2
Go|ms-|0.13.1
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.1711
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
cordova-tools|msj|1.9.2
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.1
biosyntax|rea|0.0.9
java|red|0.58.0
vscode-yaml|red|0.7.2
unity-debug|Uni|2.7.2
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0

</details>

**Comment by aeschli** [comment]
Can you add a screenshot?
When you opened the diff, did all of VSCode switch to the light theme? Or just the diff editor's colors were wrong?

**Comment by Inventrohyder** [comment]
Sure,

Normally, at night, it has the following dark theme
 
<img width="1542" alt="Screenshot 2020-03-10 at 04 59 07" src="https://user-images.githubusercontent.com/22187034/76265955-ec244e80-628b-11ea-89d0-42b4790c2564.png">

However, when I open the diff of a Jupyter notebook,
It turns to the light theme

<img width="1542" alt="Screenshot 2020-03-10 at 05 00 37" src="https://user-images.githubusercontent.com/22187034/76266010-1c6bed00-628c-11ea-9ee7-8907850f966e.png">


And one way I found of solving it is by turning the setting off and on again

<img width="1136" alt="Screenshot 2020-03-10 at 05 01 46" src="https://user-images.githubusercontent.com/22187034/76266055-458c7d80-628c-11ea-92ab-9bc13230fd28.png">

**Comment by Inventrohyder** [comment]
I have just tried it out again.

Many things might have changed

However, the issue does not arise again.

It seems fixed 🛠

**Comment by aeschli** [comment]
@Inventrohyder Thanks a lot for checking again. I wasn't able to reproduce either.
