### ISSUE TITLE
Running C++ code will not allow user to input text in Terminal.

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#92178]
Running C++ code will not allow user to input text in Terminal.

For example:  

`
#include <iostream>
#include <string>
using namespace std;

string name;

int main(){

    std::cout << "What Is Your name " << std::endl;
    std::cin >> (name);
    std::cout << "Hello " + (name) << std::endl;
}`

When using extension RUN-CODE or any other extension that does the same thing,
or visual studio code & insiders on its own, to run the C++ file,
It will not allow users to actually input text directly into the (terminal) window tab.
I have tried many times and when running the C++ code, it will process and only go to the 
OUTPUT Window even when the code asks for users input, not allowing user to interact with the terminal.
I have complained about this several times and every time the Issue gets ignored and closed.
I dont know how else to explain what I am doing but it wont allow user to input text.
I SHOULD be able to answer the code question within the actual Terminal Window of
VS-Code Insiders or Main release.
I should be able to run the code without having to type the directory path and executable file each and every time I want to run a file in C++.
I should be able to just run the file, just like Visual Studio 2019 does.
But within Visual Studio Code and Insiders edition.
.

![Doesnt Allow User To Input Text](https://user-images.githubusercontent.com/18384135/76119821-32dd2480-5fbe-11ea-9847-6ec69478d9d6.png)

It works in VS-2019
But I dont feel comfortable & feel out of sorts coding in VS-2019 for many reasons.
I want to do it in VS-Code & Insiders instead.
.
![It works in VS-2019](https://user-images.githubusercontent.com/18384135/76120616-d975f500-5fbf-11ea-95dc-7ebed4e795c8.png)

**Comment by weinand** [comment]
Pls file issue against C++ extension.
