### ISSUE TITLE
Default width of extension list is too small and hides extensions' logo.

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#9218]
- VSCode Version: 1.4.0-Insider
- OS Version: Windows 10.

Steps to Reproduce:

1. Install VS Code 1.4.0-Insider
2. Navigate to the extension view, and it will load `@popular`

![image](https://cloud.githubusercontent.com/assets/876920/16808621/ccf5e202-494f-11e6-86ce-31caf60ee4c3.png)

Logo of all extensions are hidden.

**Comment by joaomoreno** [comment]
@rebornix I don't think there is actually a _default_ width. It's just the width you had from last time.

For the _responsive_ design, I had to pick a min width at which icons would be removed. I ended up picking [300](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L117).

Any suggestions, ideas?

**Comment by rebornix** [comment]
I thought  it's default because that's my first time run it. Besides, I also installed VS Code 1.3.0 and see below

![image](https://cloud.githubusercontent.com/assets/876920/16810736/b7357f38-4957-11e6-8972-c31082386d02.png)

You can't see all five stars. I'm not sure is it because my laptop display resolution is too high, is it just me (or Dell XPS 13 user) seeing this problem?

**Comment by joaomoreno** [comment]
That's an issue that got out with the last stable. The extension name and version push the stars out of the container. It's fixed in Insiders.
