### ISSUE TITLE
[folding] command that adds folding markers

### ISSUE THREAD

**Issue by timothyslau** [microsoft/vscode#92185]
I'm a Data Scientist, and I find an exceptional value add from the code folding within sections feature.
e.g., [https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections](https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections)

My source code gets to hundreds of lines long fairly quickly and Jupyter notebooks are cumbersome to scroll and find stuff within.

It allows me to jump between sections more easily and stay organized in the development 
e.g.,
```
# Load Necessary Packages
<import tensorflow as tf>
# Load Data
...
# QA Data
...
# Transform Data
...
# Descriptives
...
# Models
...
# Model Evaluation
...
# 
```

An example of a workflow I'm developing in Visual Studio Code is below. Where if I could collapse some sections, it would be awesome. Thank you!

![image](https://user-images.githubusercontent.com/3031952/76127351-ada63f80-5fbe-11ea-94fa-a8b762bc78f1.png)

**Comment by KamasamaK** [comment]
Have seen the documentation on folding yet?
https://code.visualstudio.com/docs/editor/codebasics#_folding

**Comment by timothyslau** [comment]
@KamasamaK , yeah, but that's code folding on functions and not sections right?

**Comment by KamasamaK** [comment]
@timothyslau There are different ways VS Code recognizes folding regions. One is based on the `editor.foldingStrategy` setting -- default is `indentation`. Another is the user-defined regions based on markers. Both of those are covered in the documentation I linked and you can find the markers for each language in the table in that section of the doc that designate the start and end of a custom folding region.

The final one is API-driven based on something called a `FoldingRangeProvider`.

**Comment by timothyslau** [comment]
@KamasamaK I get it now, thanks for the patience. Do you know if this region functionality is something I can make a keyboard shortcut for?

**Comment by timothyslau** [comment]
Having nesting functionality added to the regions would make this even more useful.

**Comment by timothyslau** [comment]
Update:
I don't think there's an easy way to add the keyboard shortcut. But somebody did think of this already and made an extension so that you could use a keyboard shortcut.
https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder

**Comment by KamasamaK** [comment]
@timothyslau Nesting is supported. Have you tried it?

I don't see a native command for adding folding markers, but I think it's a reasonable request for the editor. It has commands to add/toggle language-aware comments based on language configuration. I'm surprised that I couldn't find that feature request already. If you'd like this feature, I'd advise created a new issue since this one is already cluttered with questions and information about how folding works in the editor.

**Comment by aeschli** [comment]
VSCode has code snippets for every language that add the language specific `#region` marker, but for Python its missing.

But the suggestion of a command might even be better, like in the (very nice) extension that was recommended

**Comment by aeschli** [comment]
You can, since a while, select a range and create a manual folding range: https://github.com/microsoft/vscode/issues/18805
