### ISSUE TITLE
Overview ruler border is shown when there is nothing to scroll

### ISSUE THREAD

**Issue by LunarTwilight** [microsoft/vscode#92186]
Issue Type: <b>Bug</b>

1) Open a file that is short enough that it doesn't need to scroll
2) Notice that while theres no cursor, there is still an overview ruler border

VS Code version: Code - Insiders 1.43.0-insider (b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0, 2020-03-05T00:59:24.612Z)
OS version: Windows_NT x64 10.0.18363

Extensions: none

**Comment by LunarTwilight** [comment]
![image](https://user-images.githubusercontent.com/13520392/76128158-03bfb680-5fb0-11ea-9d64-84f5cc14f7dc.png)

**Comment by alexdima** [comment]
This is intentional, because there could still be decorations rendered in there, even when there is no scrollbar

![image](https://user-images.githubusercontent.com/5047891/76199937-09580f00-61f1-11ea-869d-ece2d8cc67ea.png)
