### ISSUE TITLE
TypeScript refactoring: moving files around messed up with imports

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#92182]
I'm moving files around in vscode repo. Say I have following folder structure

```
- notebook
      - renderers
      - outputs
      - notebook.ts
```

and then I want to create a `view` folder under `notebook` and move `renderers` and `outputs` into `view`, what I ended up with is 

```
- notebook
      - renderers
      - view
        - renderers
        - outputs
      - notebook.ts
```

My suspicion is the typescript LS is busing while I was doing the file movement and it somehow duplicated folder `renderers` and all the content in the `notebook/renderers` have weird imports as below

```
import * as DOM from './node_modules/vs/base/browser/dom';
import { Disposable } from './node_modules/vs/base/common/lifecycle';
import * as path from './node_modules/vs/base/common/path';
import { URI } from './node_modules/vs/base/common/uri';
import * as UUID from './node_modules/vs/base/common/uuid';
import { IEnvironmentService } from './node_modules/vs/platform/environment/common/environment';
import { INotebookEditor } from './node_modules/vs/workbench/contrib/notebook/browser/notebookBrowser';
import { INotebookService } from './node_modules/vs/workbench/contrib/notebook/browser/notebookService';
import { CellViewModel } from './node_modules/vs/workbench/contrib/notebook/browser/viewModel/notebookCellViewModel';
import { CELL_MARGIN, IOutput } from './node_modules/vs/workbench/contrib/notebook/common/notebookCommon';
import { IWebviewService, WebviewElement } from './node_modules/vs/workbench/contrib/webview/browser/webview';
import { WebviewResourceScheme } from './node_modules/vs/workbench/contrib/webview/common/resourceLoader';
```

@mjbvz is this something you find familiar ?

**Comment by mjbvz** [comment]
I suspect this can happen if you moved the second file while we were computing the edit for the first file move. The time it takes to compute the edits should be reduced with: https://github.com/microsoft/TypeScript/issues/30535

**Comment by mjbvz** [comment]
@rebornix Have you seen this again recently? I'm having trouble reproducing this issue?

Also, did you try moving both folders at once or did you move them individually?
