### ISSUE TITLE
Blank when edit file from terminal

### ISSUE THREAD

**Issue by workabyte** [Microsoft/vscode#9219]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:28:46.761Z)
- OS Version: Linux x64 4.4.0-28-generic
- running in virtual box
-- host pc windows 10

Steps to Reproduce:

1. $ code /some/path/to/a.sh
2. code launches showing either black background (first time) or same content as desktop (second time)

**Comment by workabyte** [comment]
seems like this was caused by "Enable 3D Acceleration"
after turning off that option this seems to be resolved

**Comment by Tyriar** [comment]
Yes this is due to limitations in Chromium.
