### ISSUE TITLE
Indicate active UI compoment in the workbench that has focus

### ISSUE THREAD

**Issue by computHome** [microsoft/vscode#92191]
Currently, it is difficult to tell which window has keyboard focus and much time is wasted due to this.
I recommend that the window would have a red border to let devs know which window has keyboard focus. as a devs, I think that usefulness takes precedence than look and feel, every second count for devs!

**Comment by bpasero** [comment]
See https://code.visualstudio.com/updates/v1_40#_themable-window-border

**Comment by computHome** [comment]
This is only telling which vscode instance you are working on. what I meant is the tab/pane/area would be highlighted or bordered when it had keyboard focus. e.g. you might open 2 files side by side in one vscode instance, the theme you mentioned will not highlight the tab you are working on, it only highlight the whole vscode instance.

**Comment by bpasero** [comment]
@computHome you can play around with configuring these theme colors in settings:

```json
"tab.activeBackground": "#ff0000",
"tab.unfocusedActiveBackground": "#000000"
```

That would draw the focused tab differently from unfocused.

**Comment by computHome** [comment]
Thanks for the tips. but if there is a theme which can really highlight which area you are working on is much better and more consistent since the keyboard focus could go to search pane, terminal pane and other areas too.
