### ISSUE TITLE
Extension authoring: expose TypeScript AST?

### ISSUE THREAD

**Issue by panlina** [microsoft/vscode#92195]
As I know extension authors have to find their own way to parse js/ts source code if they want their extensions to provide functionalities based on AST. Since the built-in js/ts support works great, is there any plan to make it visible to extension authors?

**Comment by mjbvz** [comment]
The built-in JS/TS extension does not have access to the AST: it uses the [TypeScript Server](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29)

To access the AST and other low level information (such as types) you can use a [TypeScript language service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin)

**Comment by panlina** [comment]
I didn't know about this before. Thanks for pointing out, but is it accessible to extensions? For an extension that offers a particular functionality, TypeScript editing experience is just part of it. It should be integrated with other features, like code actions, commands, fs events, etc.

**Comment by mjbvz** [comment]
Extensions can contribute plugins: https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins

That is the only was to access the AST
