### ISSUE TITLE
Blank source control window

### ISSUE THREAD

**Issue by tmulgrew** [microsoft/vscode#92190]
I believe this is the same as [82203](https://github.com/microsoft/vscode/issues/82203) and [82325](https://github.com/microsoft/vscode/issues/82325) but they are locked now.

I've managed to reproduce the issue where the SOURCE CONTROL pane stays blank, with the default git provider.

Steps:
1. Open a folder that is under source control
2. "File > Open File..." and browse to a file in a different folder that belongs to a different git repository
3. The SOURCE CONTROL pane should now show two providers, one for the current folder and one for the file just opened
4. Select the one for the file just opened
5. Close said file in the editor
6. Close and restart the editor

When I do this the SOURCE CONTROL pane ends up blank.
Toggling the "Scm: Always Show Providers" setting brings it back

Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
@tmulgrew I can't repro this, can you still reproduce?

**Comment by tmulgrew** [comment]
@joaomoreno no I can't reproduce either. Just tried now on v1.43.2
