### ISSUE TITLE
How to disable vendor prefixes in VS Code?

### ISSUE THREAD

**Issue by FlagElitov** [microsoft/vscode#92197]
Issue Type: <b>Feature Request</b>

When I write in SCSS:
display: flex;
then in CSS it writes:
display: -webkit-box;
display: -ms-flexbox;
display: flex;
How to make only display: flex; ?
How to disable vendor prefixes in VS Code?

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

**Comment by ArturoDent** [comment]
How are you compiling your scss to css?  Are you using Autoprefixer plugin during your css build?

**Comment by FlagElitov** [comment]
> Як ви збираєте scss до css? Чи використовуєте плагін Autoprefixer під час створення css?

I use Live Sass Compiler for compiling  . 
I did not install the Autoprefixer plugin . 
I want to get rid of vendor prefixes

**Comment by FlagElitov** [comment]
> How are you compiling your scss to css? Are you using Autoprefixer plugin during your css build?

I use Live Sass Compiler for compiling .
I did not install or use the Autoprefixer plugin .
I want to get rid of vendor prefixes
