### ISSUE TITLE
Response jamming when inputting very multilayer nested square brackets

### ISSUE THREAD

**Issue by ouv** [microsoft/vscode#92205]
Issue Type: <b>Performance Issue</b>

- By typing (press and hold the <kbd>[</kbd> key):
  Starting from about two hundred pairs, machines with better performance may start from thousands of pairs.
- By pasting:
  Pasting 5k pairs of nested square brackets (10k characters) directly will freeze for four to five seconds.

And for the reproduction of the pop-up error message  "The TypeScript language service died 5 times right after it got started" – just open a js file containing 5k pairs of nested square brackets.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.14393

![A js file containing 5k pairs of nested square brackets](https://user-images.githubusercontent.com/10680156/76144904-a0bd4500-60bf-11ea-8bcd-165095b24327.png)
![Message 'The TypeScript language service died 5 times right after it got started'](https://user-images.githubusercontent.com/10680156/76144913-ac107080-60bf-11ea-88ba-60e234708173.png)
![Message 'The window is no longer responding'](https://user-images.githubusercontent.com/10680156/76144948-11646180-60c0-11ea-8e42-1d005532d4d3.png)

**Comment by mjbvz** [comment]
I can't repo this. Tested with 1000 brackets. 

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please share an example file that triggers this

**Comment by ouv** [comment]
Tested with a fresh install (also my first download) of the Visual Studio Code Insiders build, the following is a report generated by the VS Code Insiders Issue Reporter:

![still jammed](https://user-images.githubusercontent.com/10680156/76507359-a338e980-6487-11ea-8e3f-a4b826c6b1da.png)

### TS Server fatal error:  Maximum call stack size exceeded

**TypeScript Version:** 3.8.3


**Steps to reproduce crash**
1. Open VS Code
2. Open a JS file that contains only 5000 pairs of consecutively nested square brackets.
3. The UI freezes for 9 to 10 seconds, then two prompts pop up saying that the same built-in extension has crashed, which is "TypeScript and JavaScript Language Features (`vscode.typescript-language-features`)".


**TS Server Error Stack**
```
RangeError: Maximum call stack size exceeded
    at parsePrimaryExpression (tsserver.js:22642:40)
    (... repeated ...)
    at parseMemberExpressionOrHigher (tsserver.js:22173:30)
    at parseLeftHandSideExpressionOrHigher (tsserver.js:22118:92)
    at parseUpdateExpression (tsserver.js:22048:30)
    at parseUnaryExpressionOrHigher (tsserver.js:21920:40)
    at parseBinaryExpressionOrHigher (tsserver.js:21780:31)
    at parseAssignmentExpressionOrHigher (tsserver.js:21421:24)
    at parseArgumentOrArrayLiteralElement (tsserver.js:22702:21)
    at parseListElement (tsserver.js:19914:20)
    at parseDelimitedList (tsserver.js:20208:31)
    at parseArrayLiteralExpression (tsserver.js:22713:29)
    at parsePrimaryExpression (tsserver.js:22658:28)
```


VS Code version: Code - Insiders 1.44.0-insider (1df23554b2e3d5f1efc6fbc76ee61d3f7f186c6d, 2020-03-12T05:28:56.968Z)
OS version: Windows_NT x64 10.0.14393


<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|AMD A8-5600K APU with Radeon(tm) HD Graphics    (4 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.19GB (2.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
Extensions: none

<br><br>

**P.S.** Strangely, although [Monaco Editor]( https://microsoft.github.io/monaco-editor ) also reported errors exceeding the maximum call stack size, it could continue to type with almost no jamming in the same huge amount of nested brackets.

**Comment by mjbvz** [comment]
Did you hit this in actual code?

While this sounds like it may be a bug, it's going to be very low priority if it does not impact a more normal workflow

**Comment by ouv** [comment]
Never hit.

And I fully understand your prioritization – this issue is a backlog with the lowest priority. 😉

**Comment by mjbvz** [comment]
Thanks. Given that I don't see us addressing this anytime soon given the number other bugs and feature requests we have for more real world code, I'm closing the issue
