### ISSUE TITLE
Allow extensions to provide order for its contributed configuration properties

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#92207]
Our extension has quite a few settings at this point and our users are providing us feedback that it is hard to navigate through our extension settings.

They appear to be ordered alphabetically by title, what would be nice is to be able to group the settings, and then order the settings within each group.

**Comment by GabeDeBacker** [comment]
The folder grouping is not the same request.

**Comment by roblourens** [comment]
Covered by https://github.com/microsoft/vscode/issues/70589
