### ISSUE TITLE
Java Scanner.next() ocurr Exception when input is chinese character

### ISSUE THREAD

**Issue by zhfff4869** [microsoft/vscode#92203]
Issue Type: <b>Bug</b>

when run Java process，use Scanner.next() to input chinese character  will occur NoSuchElementException.while I run it in intelliJ not.This is the print:

Exception in thread "main" java.util.NoSuchElementException
        at java.util.Scanner.throwFor(Scanner.java:862)
        at java.util.Scanner.next(Scanner.java:1371)
        at StudentManager.addStudent(StudentManager.java:132)
        at StudentManager.run(StudentManager.java:25)
        at StudentManager.main(StudentManager.java:9)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.34.0
python-extension-pack|don|1.6.0
translation|dus|0.0.4
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.42.2
python|ms-|2020.2.64397
vscode-boot-dev-pack|Piv|0.0.8
vscode-spring-boot|Piv|1.15.0
java|red|0.58.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6
jinja|who|0.0.8

</details>

**Comment by gjsjohnmurray** [comment]
/question which doesn't seem to be related to the VS Code product.
