### ISSUE TITLE
wrong results in settings search

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#92219]
- VSCode Version: 1.43.0-insider
- OS Version: Ubuntu 20.04

## Steps to Reproduce:

1. Search for `- off` in settings.

## Expected behavior: 
It searches for `- off` and highlights it.

## Actual behavior: 
It searches for `.` and some spaces and highlights them, some occurrences of `off` are highlighted, some are not.

![search-bug](https://user-images.githubusercontent.com/23744935/76153270-fc8ccb80-60c9-11ea-959f-dbad730fde2b.png)

Does this issue occur when all extensions are disabled?: Yes

Related issue: 
https://github.com/microsoft/vscode/issues/27677

**Comment by sandy081** [comment]
This editor is in maintenance mode.

Happy to take PR to fix this.

**Comment by hunghw** [comment]
I would like to take this PR.

**Comment by aeschli** [comment]
@sandy081 Adding you as owner as otherwise the issue shows up in the Team Inbox
