### ISSUE TITLE
Not able to change shells

### ISSUE THREAD

**Issue by ClydeFrogg0** [microsoft/vscode#92215]
![vsCode](https://user-images.githubusercontent.com/50798422/76152007-1bd02c80-60bb-11ea-8856-dc12793b7118.png)
Issue Type: <b>Bug</b>

1. install git
2.set vscode as default editor
3.Try to change the shell in the terminal dropdown

Expected
option for powershell, cmd and bash

actual
options for powershell and cmd

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Since you are running VSCode on Windows, where do you expect the bash shell to come from?

**Comment by ClydeFrogg0** [comment]
Sorry If I'm mistaken here. But I was following this guide https://community.dynamics.com/business/b/tharangacnavblog/posts/git-bash-on-visual-studio-code-integrated-terminal
