### ISSUE TITLE
ability to manipulate configuration variables

### ISSUE THREAD

**Issue by amir-arad** [microsoft/vscode#92218]
I've encountered a similar need to #73888 . I pass `${workspaceFolder}` as a parameter to some (`ms-vscode.cmake-tools` plugin) and it parses the string, producing the following error:
```
[cmake]   Syntax error in cmake code when parsing string
[cmake] 
[cmake]     c:\workspace\EmptyEpsilon/../SeriousProton/src/soundManager.cpp
```

So for my specific case I need a version of `workspaceFolder` with either backward slashes, or double forward slashes. But in general I think a way to manipulate the value (replace?) can come in handy.

**Comment by weinand** [comment]
Where are you passing `${workspaceFolder}` as a parameter?
Please be aware that in general variables like `${workspaceFolder}` can only be used in launch.json and tasks.json.

**Comment by amir-arad** [comment]
> Where are you passing `${workspaceFolder}` as a parameter?
as part of a parameter. [This](https://gist.github.com/amir-arad/169993b47e97034277e0e5dfe18b1397#file-settings-json) is a workspace configuration I wrote, which several people use, and for some reason no longer works.

> Please be aware that in general variables like `${workspaceFolder}` can only be used in launch.json and tasks.json.
could you please show me a reference to what configuration should go where?so that I can re-write my configuration, or at least offer a heads up to the `vscode-cmake-tools` people

**Comment by weinand** [comment]
@bpasero do we have a list of variables that can be used in settings.json? 
(The variables available in launch.json and tasks.json are specified here: https://code.visualstudio.com/docs/editor/variables-reference)

**Comment by bpasero** [comment]
Forwarding to @roblourens @sandy081  do we have a complete list of variables that can be used in settings.json?

Maybe they should be showing up in IntelliSense?

**Comment by roblourens** [comment]
They do show up in intellisense, but they are only supported as special cases for specific settings.

**Comment by sandy081** [comment]
We do not support any variables in settings. Its up to each setting to define their own variable and resolve them. 

See - #2809
