### ISSUE TITLE
C# extension has been searched via old extension name

### ISSUE THREAD

**Issue by jprimke** [microsoft/vscode#92210]
Issue Type: <b>Bug</b>

if you open C# code then VS Code is asking for installing a new extension and is searching for ms-vscode.csharp but this is renamed to ms-dotnettools.csharp

VS Code version: Code - Insiders 1.43.0-insider (5996fb81591e92fd0c547dc45e3f0350026d5962, 2020-03-06T23:17:52.931Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3209)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (18.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.66773-dev
remote-wsl|ms-|0.42.3

</details>

**Comment by gregvanl** [comment]
Reason for https://github.com/microsoft/vscode/issues/92153
