### ISSUE TITLE
"Invalid 'reference' directive syntax" Typescript2 @types references

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#9221]
- VSCode Version: 1.3.1 (latest)
- OS Version: Win7

Install typescript2 @types
Reference them

![image](https://cloud.githubusercontent.com/assets/2574412/16810860/bcc08e8e-48f3-11e6-97a2-04f5fff9884b.png)

I'm trying to create the references for @types I've installed (TS2beta-latest), but vscode seems to have a problem with the way these are setup?

When looking at one that's downloaded (let's say browserify), it has the same problem.

![image](https://cloud.githubusercontent.com/assets/2574412/16810894/e33f0860-48f3-11e6-8f6b-a0ff4fc116fd.png)

**Comment by jrieken** [comment]
Do you have a tsconfig.json file? Iff so can you share it here?

**Comment by dbaeumer** [comment]
Closing since no additional information has been provided in the last 2 weeks.

**Comment by MarkPieszak** [comment]
Apologies @dbaeumer!

 I forgot to close this one out! The issue was VSCode wasn't aware of TS2.0 and the `tsdk` had to be changed.  (For anyone else who runs into this issue).
