### ISSUE TITLE
[folding] missing outlining expander

### ISSUE THREAD

**Issue by fcrick** [Microsoft/vscode#9222]
- VSCode Version:
Version 1.3.1
Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
Date 2016-07-12T13:35:06.227Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
- OS Version:
Windows 10

Steps to Reproduce:

1.  Create a folder, and run git init inside it.

2.  Open the folder in Visual Studio Code.

3. Create a file with the following 6 lines, and commit:
var foo: number[] = [
    1,
];
var bar: number[] = [
    2,
]; // comment

4. Remove lines 3, 4, and 5 to leave:
var foo: number[] = [
    1,
]; // comment

5. Collapse the array using the minus to hide the contents of the array.

Result:
Notice the + expander is not present. The red marker seems to hide it.

Expected:
Collapsed sections always show the expander, otherwise.

![vscode_bug_missingexpander](https://cloud.githubusercontent.com/assets/283047/16813978/c6807c8c-48e8-11e6-971a-defeaef0ae1c.gif)

**Comment by aeschli** [comment]
Proposed fix is in #9266
