### ISSUE TITLE
Find/Replace history

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#92222]
Issue Type: <b>Feature Request</b>

Find/replace doesn't seem to keep any kind of history. So if I use a cool regex to edit one file and dismiss the find/replace panel, doing the same thing in another file is not cool anymore. Re-inventing the same regex becomes burdensome.

Can VScode please keep a history?

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by thany** [comment]
Or at least not clear the Search field when re-opening the Find/Replace panel... A history of 1, as it were, is still better than no history at all.

**Comment by gjsjohnmurray** [comment]
Don't you get previous entries when you press the cursor-up key when focused on the field?

**Comment by weinand** [comment]
Yes, you can step through the history via the cursor-up and cursor-down keys

**Comment by thany** [comment]
No, actually you can't. Or it's not working. Or it's limited to one file. Or something else.

**Comment by gjsjohnmurray** [comment]
@thany please retest after running the Command Palette entry that reloads with all extensions disabled. If the problem remains please give detailed repro steps. An animated GIF or video may help communicate.

**Comment by weinand** [comment]
@thany what Find/replace are you talking about? The one in the editor (single file) or the one from the activities bar (multi file)?

**Comment by thany** [comment]
Repro:
1. Reload with extensions disabled
2. Open a file
3. Ctrl+F and search for "test"
4. Esc to close the Find panel
5. Ctrl+F and search for "test2"
6. Arrow up to, indeed, go back in history to "test"
7. Reload with extensions disabled
8. Ctrl+F
9. Up/down keys do noting.

So in my repro steps, I've found that it's limited to one session. But before I didn't know that the up/down keys triggered scrolling through history (if any), there is no visual cue that there's any history, nor is it accessible by mouse/touch.

**Comment by thany** [comment]
I don't know what more to add. Please let me know if anything is needed.
