### ISSUE TITLE
Can't unbind a key in an extension?

### ISSUE THREAD

**Issue by gilescope** [microsoft/vscode#92226]
- VSCode Version: 1.42.1
- OS Version: nixos (linux)

The following removes a keybinding:
```
{
        "key": "alt+right",
        "command": "-workbench.action.nextEditor"
}
```
However if you try and do this in an extension then when you look in the keyboard settings there's a
`--workbench.action.nextEditor` setting in there?
I.e. for some reason it gets another hyphen put in front. I seem to have tried every which way to override this keybinding from an extension and it seems not possible. Ideally I don't want to get rid of it, just supply another more specific action when in debug mode but the next action takes priority.

Steps to Reproduce:

You can see what I'm trying to do in the extension here - there's nothing to it, just some keybindings:
http://github.com/gilescope/ArrowDebugging.git 

Any hints or tips are most appreciated! Also if you want to change the vscode default keybindings to these that's fine too ;-)

**Comment by gilescope** [comment]
https://github.com/gilescope/ArrowDebugging/blob/master/package.json is the keybindings file

**Comment by gilescope** [comment]
You're suggesting it's a feature request - is it not possible then to remove a keybinding as an extension at the moment? I'm just trying to get clarity on this point.

**Comment by alexdima** [comment]
@gilescope Yes, it is possible to add keybindings rules, but it is not possible to remove keybindings rules. Keybinding rules are documented [here](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules).

So in your case you can just map `alt-left` and `alt-right` to do whatever you want. The built-in keybinding will be shadowed by your keybindings. It is not necessary that you remove the built-in keybinding rules.

**Comment by gilescope** [comment]
I do indeed map alt+left but whether I say when editorTextFocus or isDebugMode or do not set when, it is the view: Open previous editor that wins out on the keybinding. If I add a user overide of a ‚when’ to „view: Open previous editor“ mine triggers. Essential there is no way currently to override via an extension for this alt left and alt right.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gilescope** [comment]
I think the problem is the view: open previous editor is at the bottom on the priority order so will always match first. No idea how I can ask vscode to load my extension towards the end of the extensions it loads?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gilescope** [comment]
I mean that view keybinding must be a built in extension that sets it up so am really surprised that my keybinding comes higher in the list.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
