### ISSUE TITLE
Terminal freezing after a few minuts of opening - VScode on WSL Ubuntu on Windows 10

### ISSUE THREAD

**Issue by JoseLuisRaMen** [microsoft/vscode#92229]
Issue Type: <b>Performance Issue</b>

My dev setup is VScode + WSL Ubuntu on Windows 10

The last 3 or 4 times I opened VS code to work on one of my projects on the WSL, evertything starts like normal, but after a while, the terminal 'freezes' - the cursor stops blinking and does not respond to keyboard input

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.88GB (54.84GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/joselo/DASH-X/movementtravel-as-package --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (8 x 3096)|
|Memory (System)|63.88GB (54.84GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	 10848	code main
    0	    69	  3896	   window (Issue Reporter)
    0	    72	  5992	   shared-process
    0	   228	  6520	   window (Area.py - movementtravel-as-package [WSL: Ubuntu] - Visual Studio Code)
    0	    57	 14972	     extensionHost
    0	    31	 12432	       electron_node wslDaemon.js 
    0	     7	  6180	         C:\Windows\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" c47d83b293181d9be64f27ff093689e8e7aed054 stable .vscode-server 0  '
    0	     6	 17580	           C:\Windows\System32\lxss\wslhost.exe {3dbc4d97-576b-45b9-8e2e-3d175c41ee65} 456 464 468
    0	    14	  6008	             console-window-host (Windows internal process)
    0	    12	 20132	           console-window-host (Windows internal process)
    0	    15	  8608	   electron-crash-reporter
    0	   277	 15300	   gpu-process

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	    86	remote agent
    0	     0	   117	   watcherService
    0	     0	   148	   extensionHost
    0	     0	   161	     /bin/bash
    0	     0	   298	     /home/joselo/anaconda3/envs/DASH/bin/python completion.py
    0	     0	   321	       /home/joselo/anaconda3/envs/DASH/bin/python lib/python/jedi/inference/compiled/subprocess/__main__.py lib/python 3.7.6
    0	     0	   696	     /home/joselo/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node /home/joselo/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=148
    0	     0	   712	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	   713	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu|    Folder (movementtravel-as-package): 253 files|      File types: csv(134) py(35) p(20) pkl(19) pyc(14) nml(10) json(2)
|                  nbc(1) nbi(1)
|      Conf files: settings.json(2);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
gitlens|eam|10.2.1
git-graph|mhu|1.21.0
python|ms-|2020.2.64397
autodocstring|njp|0.4.0
markdown-preview-enhanced|shd|0.5.2

</details>

**Comment by Tyriar** [comment]
Does this still happen? I use Windows -> WSL daily and have never seen this happen. Is the rest of the UI responsive? Are there errors in the devtools (via Help) console?

**Comment by JoseLuisRaMen** [comment]
hi @Tyriar 
No; whatever was causing this issue, it would appear to have been resolved with the latest VScode update. Thanks for looking into this anyway.

**Comment by Tyriar** [comment]
Great to hear, and sorry about the delay in getting back to you.
