### ISSUE TITLE
Cant add files or make changes to any projects in vscode 

### ISSUE THREAD

**Issue by norrby91** [microsoft/vscode#92224]
Issue Type: <b>Bug</b>

Unable to write file 'c:\Users\Firebase_setup\hello' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, open 'c:\Users\Firebase_setup\hello')

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (2.86GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Firebase_setup|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-react-native|msj|0.14.1

</details>

**Comment by Dudeplayz** [comment]
Same problem here but with installing any extension. If I start the application with admin privileges VSCode crashes on opening the extension window.

**Comment by bpasero** [comment]
I suggest to open a separate issue. In general we discourage from running VSCode as admin

**Comment by Dudeplayz** [comment]
I only tried to run it as admin because the extension error occurred. I fixed it now by deleting the `.obsolte` file in the extensions folder.

**Comment by bpasero** [comment]
Ok
