### ISSUE TITLE
SCM autosuggest input does not properly fetch results when re-triggered

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#92239]
Issue Type: <b>Bug</b>

Using GHPR nightly, trigger an autosuggest popup in SCM viewlet using `#` trigger char. Type some things to fileter. Esc. Trigger again with ctrl+space. No results. In Extension Search and Settings Editor Search, you can escape and retrigger to get the previous suggestions. 

VS Code version: Code - Insiders 1.43.0-insider (5996fb81591e92fd0c547dc45e3f0350026d5962, 2020-03-06T23:58:52.927Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (14.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.2
markdown-preview-github-styles|bie|0.1.6
multi-cursor-case-preserve|Car|1.0.5
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.1.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
vscode-firefox-debug|fir|2.7.0
vscode-pull-request-github-insiders|Git|2020.3.8167
search-editor-apply-changes|jak|0.1.1
graphql-for-vscode|kum|1.15.3
find-jump|mks|1.2.4
vscode-selection-flip|mle|1.0.0
python|ms-|2020.2.64397
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
js-debug-nightly|ms-|2020.3.617
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
toggle|reb|0.0.1
bash-debug|rog|0.3.7
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
vscode-multiclip|sle|0.1.5
ayu|tea|0.18.0
polacode-fork|Tox|0.6.0
errorlens|use|3.0.0
vscodeintellicode|Vis|1.2.6
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.7.0

(2 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
CC @RMacfarlane not sure if this is core or the extension so I filed here.

**Comment by alexr00** [comment]
I got a ton of feedback that the suggest was too eager and that people don't want issues and users in their suggest when they trigger the suggest manually. So now when you trigger suggest I only provide the users or issues when you trigger it and the previous character is a `@` or `#` respectively.

I suspect in the SCM view it's ok to provide users and issues no matter where the suggest is triggered, whereas in the editor that is not the case.
