### ISSUE TITLE
Global Find/Replace with Regex not working

### ISSUE THREAD

**Issue by chuckries** [Microsoft/vscode#9223]
_From @jchannon on July 13, 2016 7:55_

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version:1.3
C# Extension version:1.2.2

## Steps to reproduce
Do a global search with regex turned on and with capture groups eg `(this)` then in the replace enter `$1` which will replace what it finds with the first capture group

## Expected  behavior
Replace with the value of `$1` not the actual string of `$1`

## Actual behavior
Replaces all found items with the string of the capture group

<img width="454" alt="screen shot 2016-07-13 at 08 55 02" src="https://cloud.githubusercontent.com/assets/105126/16795865/860b71fe-48d7-11e6-8d90-a15362db8cc4.png">

_Copied from original issue: OmniSharp/omnisharp-vscode#562_

**Comment by sandy081** [comment]
This is fixed in #9010 and is available in insiders build. 

duplicates #9010
