### ISSUE TITLE
F5 launces iis express instead of following what is in launch.json

### ISSUE THREAD

**Issue by eliassal** [microsoft/vscode#92230]
Issue Type: <b>Bug</b>

Hi, I have just installed VSC with several extensions. I have a very simple console app which I run by pressing F5 or Ctrl + F5, I get IE triggered instead of the application, here is the launch.json contents
```
{
    "version": "2.0.0"  ,
    "tasks": [
        {
            "label": "pizzaconsoletestbuild",
            "type": "shell",
            "command": "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\csc.exe",
            "args": [
                "/r:\"../PizzaLib/bin/PizzaLib.dll\",\"../PizzaLib/bin/PizzaLib.dll\"",
                "/out:bin/PizzaConsoleTest.exe",
                "*.cs"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        }
    ]
}
```
and here is what I get

Starting IIS Express ...
Successfully registered URL "http://localhost:38527/" for site "PizzaConsoleTest-3f60cd63-c9ad-4f80-92ea-74f8a3d37313" application "/"
Registration completed for site "PizzaConsoleTest-3f60cd63-c9ad-4f80-92ea-74f8a3d37313"
IIS Express is running.
Request started: "GET" http://localhost:38527/

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.61GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
swagger-viewer|Arj|2.2.2
path-intellisense|chr|1.4.2
regex|chr|0.2.0
xml|Dot|2.5.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
vscode-diff|fab|1.4.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
docker-explorer|for|0.1.7
vscode-mysql|for|0.4.0
auto-using|Fud|0.7.15
beautify|Hoo|1.5.0
rest-client|hum|0.23.1
icon-fonts|idl|2.2.4
vscode-tfs|iva|0.7.2
RelativePath|jak|1.4.0
csharpextensions|jch|1.3.1
vscode-csharp-snippets|jor|0.3.1
vscode-phpfmt|kok|1.0.30
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ftp-sync|luk|0.3.9
rainbow-csv|mec|1.6.0
HTMLHint|mka|0.6.0
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.2
vscode-azureappservice|ms-|0.16.3
vscode-azurefunctions|ms-|0.21.0
vscode-azurestorage|ms-|0.8.0
vscode-cosmosdb|ms-|0.12.1
vscode-docker|ms-|0.10.0
csharp|ms-|1.21.13
mssql|ms-|1.9.0
remote-containers|ms-|0.101.1
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
powershell|ms-|2020.3.0
vscode-node-azure-pack|ms-|0.0.10
azurerm-vscode-tools|msa|0.8.4
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
sqltools|mtx|0.21.6
color-highlight|nau|2.3.0
advanced-new-file|pat|1.2.0
Csharp-ASPNETCore|rah|1.11.0
format-html-in-php|rif|1.6.2
bootstrap4-vscode|the|6.1.0
terminal-tabs|Tyr|0.2.0
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
iis-express|war|1.1.2
markdown-all-in-one|yzh|2.7.0
bootstrap-v4-snippets|Zac|1.1.3
material-theme|zhu|3.2.3
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by aeschli** [comment]
The content is from `tasks.json`. Can you provide the content of `launch.json` ?

**Comment by aeschli** [comment]
Closing due to lack of information.
