### ISSUE TITLE
Emmet expression with attributes not expanding

### ISSUE THREAD

**Issue by wkt84** [microsoft/vscode#92231]
- VSCode Version: 1.42.1
- OS Version: Windows10 Pro (64-bit)

Steps to Reproduce:

1. Create a file as html.
2. Type some emmet abbreviations with attribute like below.

```html
div[role=tab]>(div>div)+div
```
expected result will be below.

```html
<div role="tab">
  <div>
    <div></div>
  </div>
  <div></div>
</div>
```

But when I select `div[role=tab]>(div>div)+div` and select `Emmet: Expand Abbreviation` from command pallet, vscode does not expand these abbreviation.
When I remove attribute `[role=tab]`, it works correctly.

I'm not sure what rules cause this to happen.
Sublime text can expand this but vscode cannot 😢 .

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
\closedWith dc5a3da
