### ISSUE TITLE
Add command line option to launch folder in WSL

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#92232]
I would love a new command line parameter to launch Code directly into WSL mode, currently I have to do `code .` and then click on the remote button and then "reopen in WSL".

So something like `code . --use-wsl` would be nice. Also for 3rd party programs like a Git client that offers a button to open a repository in VS Code.

**Comment by aeschli** [comment]
You can already do it with the `--remote` command line parameter. 
`code --remote wsl+<distro> <pathInWSL>`

For example: `code --remote wsl+Ubuntu /home/me/project`
