### ISSUE TITLE
Picker: separators should not get filtered away

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92248]
Steps to Reproduce:

1. click on the indentation picker in the status bar
2. notice how there are separators in place
3. start to filter

=> 🐛 the separators are gone

This is not what quick open does and we should try to preserve the separators. In other words, they should not get excluded away when searching. 

![Kapture 2020-03-09 at 8 34 04](https://user-images.githubusercontent.com/900690/76191928-bfffc380-61e0-11ea-90ef-b10a86554b6d.gif)

**Comment by chrmarti** [comment]
The groups are not preserved by the sorting, so it makes sense to remove the separators.

**Comment by bpasero** [comment]
Yes you are right, this is the correct behaviour if `sortByLabel` is true, which is the default.
