### ISSUE TITLE
Support ANSI encoding

### ISSUE THREAD

**Issue by akos127** [microsoft/vscode#92240]
Issue Type: <b>Feature Request</b>

We need ANSI encoding for Visual Studio Code by default.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by akos127** [comment]
![image](https://user-images.githubusercontent.com/15962488/76262408-88366180-625c-11ea-8d76-67d13858a8be.png)
There is no ANSI encoding what i need.

**Comment by bpasero** [comment]
@akos127 isn't that just Windows 1252 (https://en.wikipedia.org/wiki/Windows-1252)?

**Comment by akos127** [comment]
![image](https://user-images.githubusercontent.com/15962488/76356044-95fbed80-6315-11ea-8cc1-9b36f999150a.png)
Not same. "ű" "Ű" "ő" "Ő" and many other characters are wrong

**Comment by akos127** [comment]
So I'm forced to use another program and it would be very good because it has a lot of good features.

**Comment by bpasero** [comment]
Can you maybe find your encoding in this list: https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

That is the library we are using and most of those encodings are also enabled in VSCode.

**Comment by akos127** [comment]
I need ASCII-extended but not here.

**Comment by Akarinnnnn** [comment]
> @akos127 isn't that just Windows 1252 (https://en.wikipedia.org/wiki/Windows-1252)?

No, ANSI also meant GBK, Shift-JIS

**Comment by bpasero** [comment]
@akos127 unclear to me what exact encoding this is, can you see if it exists here https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings or file an issue to them to support it?
