### ISSUE TITLE
Sideloading an extension .vsix doesn't prompt the user

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#9224]
- VSCode Version:1.3.1
- OS Version:Windows 10

Steps to Reproduce:

1. Open an extension .vsix file with File > Open File...

The extension is correctly installed but there is no indication that the install finished or succeeded. If you go to the Extensions view, you can see the extension but only Uninstall is shown and not the blue Enable button to prompt the user for a restart.

**Comment by joaomoreno** [comment]
This was fixed since. Just make sure it works in the insiders release.
