### ISSUE TITLE
Printing does not work on remote files

### ISSUE THREAD

**Issue by jwvdvuurst** [microsoft/vscode#92249]
Have several extensions installed, among which:
- Remote SSH
- PrintCode

I have a file open on a remote LINUX RHEL server via remote SSH.
When I than press CTRL-SHIFT-P and select Print, it won't print.

Workaround:
- Copy the code
- Paste in local file
- CTRL-SHIFT-P and select Print and it works 

I am not sure whether this is an issue in VS Code, or in either one of the extensions (or an interference of the two extensions).

**Comment by weinand** [comment]
VS Code does not support printing out-of-the-box (see https://github.com/microsoft/vscode/issues/5953). So this must be an extension issue.
