### ISSUE TITLE
Chinese fonts monospace rendering is not correct

### ISSUE THREAD

**Issue by snakesgun** [microsoft/vscode#92244]
- VSCode Version: 1.42.1; c47d83b293181d9be64f27ff093689e8e7aed054; x64
- OS Version: Windows 10.0.18363 Build 18363

Steps to Reproduce:

1. Without any configurations or steps to reproduce
2. Just open a file contains some Chinese characters, Chinese characters could not be aligned correctly, just like the screeshot under below.
![vscode-screenshot 2020-03-09 112838](https://user-images.githubusercontent.com/6904436/76180977-8d62c480-61fa-11ea-83f6-622e1a7f2f82.png)

I have tested other Chinese fonts with monospace like "黑体", "Microsoft Yahei". The problem is same as default settings.

Does this issue occur when all extensions are disabled: Yes

**Comment by alexdima** [comment]
The width of characters is defined by the font. If you want to have 1 wide character = 2 latin characters, then please use a font which defines that. e.g. Inconsolata.

**Comment by snakesgun** [comment]
> 
> 
> The width of characters is defined by the font. If you want to have 1 wide character = 2 latin characters, then please use a font which defines that. e.g. Inconsolata.

Thanks for your reply，I have try your suggestion to set Inconsolata as my default font settings. The problem has been solved. Thank you.
