### ISSUE TITLE
Typescript server dying

### ISSUE THREAD

**Issue by josh-tracey** [microsoft/vscode#92246]
Issue Type: <b>Bug</b>

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|15.50GB (1.02GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color-pick|ada|0.6.2
vscode-base64|ada|0.1.0
project-manager|ale|10.11.0
copy-relative-path|ale|0.0.2
vscode-standard-format|che|0.0.12
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-select|chu|2.0.1
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.34.0
vscode-instant-markdown|dba|1.4.4
githistory|don|0.6.2
es7-react-js-snippets|dsz|2.6.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
vscode-npm|fkn|3.3.0
provision-lens|Foo|3.0.3
typescript-code-navigator|kdc|1.2.4
typelens|kis|1.9.4
expand-region|let|0.1.4
prettify-json|moh|0.0.3
vscode-docker|ms-|0.10.0
mssql|ms-|1.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|4.0.1
vscode-graphql|Pri|0.2.2
vscode-yaml|red|0.7.2
classio|rex|0.3.4
classlens|rex|0.7.1
rust|rus|0.7.0
vscode-ts-decorators|sem|1.0.2
php-formatter|Sop|0.2.4
ReactSnippetsStandard|Tim|1.1.0
sort-lines|Tyr|1.9.0
JavaScriptSnippets|xab|1.7.2
tslint-snippets|zuo|1.1.0

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
