### ISSUE TITLE
Could VSCode support dirty lines like VS？

### ISSUE THREAD

**Issue by farqq** [microsoft/vscode#92255]
Could VSCode support dirty lines like VS, so that I can figure out what lines have changes.
Just tag them by a marked color between line No and main text of the opened editor when finding diff between dirty file and saved file.

**Comment by weinand** [comment]
VS Code supports "dirty lines" if your workspace is under source control (e.g. git).

This screenshot shows that a file is modified in the explorer ("m") and shows the changed lines with a blue bar in the editor:
![2020-03-09_10-51-43](https://user-images.githubusercontent.com/1898161/76202064-8c2e9900-61f4-11ea-93ed-2c85b3b12aed.png)
