### ISSUE TITLE
VS code terminal cursor does up 2 lines when a closed terminal is maximized with keyboard shortcut

### ISSUE THREAD

**Issue by karthikeyann** [microsoft/vscode#92258]
The issue is shown in the following video.
https://youtu.be/nl5efRzhPek

- VSCode Version: 1.42.1 
- OS Version: Windows 10 Enterprise 1809
Using VS code using remote SSH feature of an Ubuntu machine

Steps to Reproduce:

1. Set keyboard shortcuts as shown in video.
workbench.action.closePanel to `Ctrl+ Shift + 2 ` , and When to terminalFocus
workbench.action.toggleMaximizedPanel to `Ctrl+ Shift + 2` and When to !terminalFocus
2. Open remote-SSH connection
3. Open terminal and press Enter few times (say 10 times)
4. Press `Ctrl+ Shift + 2` repeatedly. 

Does this issue occur when all extensions are disabled?: No
Issue is in remote-ssh and terminal.

**Comment by finite-light** [comment]
I also encountered this problem, it is really very annoying. Is there any progress?

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by finite-light** [comment]
@Tyriar Actually I'm using ConPTY as my `settings.json` contains the following Settings
  ```json
  {
    "terminal.integrated.windowsEnableConpty": true
  }
```

**Comment by Tyriar** [comment]
@finite-light OP is on Windows 1809 (build no. 17763) in which case that setting is ignored as per it's docs:

> Whether to use ConPTY for Windows terminal process communication (requires Windows 10 build number 18309+). Winpty will be used if this is false.

**Comment by finite-light** [comment]
@Tyriar I'm using Windows 18363.
![image](https://user-images.githubusercontent.com/62316053/78618115-1c233980-78ac-11ea-961a-468c46c4f920.png)

And as English is not my mother tongue, I cannot understand the meaning of `OP`, can you explain it, thank you.

**Comment by Tyriar** [comment]
@finite-light np, OP means original poster; the person who created the issue.

**Comment by finite-light** [comment]
@Tyriar Oh, thanks for your patience to explain, I may have mistaken whom you replied to before. In fact, I encountered the same problem with OP, and my OS is Windows10x64-18363 as mentioned before, do you have any clue?

**Comment by Tyriar** [comment]
@finite-light yes you're on the newer version of Windows. Make sure you have the windowsEnableConpty setting set to true. There's another issue which sounds a lot like this but on Linux in https://github.com/microsoft/vscode/issues/91817, it could be related to yours/

**Comment by finite-light** [comment]
@Tyriar Thanks for your guidance, you are right, that issue is closer to mine. The operating system of my remote host is `ubuntu-18.04-x64`, and **this strange behavior of the terminal cannot be reproduced in the local machine (the Windows-x64 OS)**. I have subscribed to that issue, but I cannot provide more valid information than the OP provided at the moment.
