### ISSUE TITLE
Focus moves into collapsed view when it should not

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92261]
Found when trying out https://github.com/microsoft/vscode/issues/91602

1. Collapse Open Editors view but have it visible
2. Reload
3. Tab to move focus through the views in the Explorer section
4. Notice how focus is moved inside Open Editors view 🐛 

The focus should just be on the title, and should not move in the body of the Open Editors view.
Not expand and collapse the Open Editors view -> focus does not move in the body and all is good.
So this only happens when the view is collapsed from the beginning.

**Comment by sandy081** [comment]
This is in split view. Split view removes the body on collapsed and add it back on expanded. But it is not removing it when collapsed while created.

**Comment by isidorn** [comment]
Thanks for fixing this. I just checked and this works as expected, adding verified label.
