### ISSUE TITLE
Microsoft Visual C++ 14.0 problem

### ISSUE THREAD

**Issue by Souravdey15** [microsoft/vscode#92263]
I am trying to install tensor flow,pyaudio,sphinxbase , en_core_web_sm for my python project but its is not getting installed it shows  Microsoft Visual C++ 14.0 required but I have the latest versions and its not working with them .Please tell me what to do 
![error](https://user-images.githubusercontent.com/37394522/76207820-805acb00-6224-11ea-9098-2f9ed1aad51e.PNG)

**Comment by daniladyabin** [comment]
Have you tried installing C++ from VS build tools? 
[Official VS build tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16)

**Comment by weinand** [comment]
How is your problem related to Visual Studio Code?

**Comment by rebornix** [comment]
Closing as lack of enough information to help troubleshoot.
