### ISSUE TITLE
Support for multi project workspace with all config at workspace level 

### ISSUE THREAD

**Issue by aussiross** [microsoft/vscode#92260]
I use vscode with one workspace to hold all of my esp32 projects (TestBlink, TestWifi, ..), and I'm trying to configure all of my development tasks and settings at the esp32 workspace level - ideally with no .vscode in each project. I use the cmake extension for project building, and gdb/openocd over jtag for flash and debug.

I have three issues/feature requests between me and "success".

1) It seems to me a sensible use case that I have several projects in my esp32 workspace, with some concept of a currently selected project which my scripts then operate on. The cmake extension almost supports this with its "Select Active Folder", but there doesn't appear to be a way to access this selection in my scripts (e.g. ${command:cmake.activeFolder} or similar). I may yet raise a feature request with them for this, but it does seem a better solution that vscode supports this (and changes ${workspaceRoot} accordingly). However, in the scenario with multiple projects 
with no .vscode, I'm told by vscode that "${workspaceRoot} cannot be resolved, please open a folder". Just so, but what does opening a folder mean? The only workaround is to only ever have a single project loaded into my workspace. 

2) I use a preLaunchTask to flash the target. However, it seems I'm forced to provide a project level tasks.json defining "Flash", because otherwise vscode won't resolve the "Flash" task name to a workspace level task. Or perhaps I'm not using the undocumented "type:" in the preLaunchTask config correctly? 

3) Rather than the (naff) situation at present where "Run without Debug" still hits the debug entry breakpoint, I'd like some variable (e.g. ${currentCommand} or similar) which I can pass into my pre-launch Flash script. This could perform the Flash, then switch on the command and if "Run without Debug" it can just issue a hard reset to the target before exiting with nonzero status to bypass the debugger. Does a suitable variable exist?

**Comment by sandy081** [comment]
We already support workspace level settings, tasks and launches. Looks like user have issues with 
1. `${workspaceRoot}` - resolving this config variable (Debug or Tasks)?
2. `preLaunchTask` - Tasks
3. `currentCommand` in Run without Debug

Hence moving to tasks and debug owners.

**Comment by isidorn** [comment]
1. Please use ${workspaceFolder} scoped per folder. More details here https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder
2. I leave this to Alex Ross
3. This sounds like a feature request please file a new concise issue explaiaing what exaclty you need

**Comment by alexr00** [comment]
> I use a preLaunchTask to flash the target. However, it seems I'm forced to provide a project level tasks.json defining "Flash", because otherwise vscode won't resolve the "Flash" task name to a workspace level task. Or perhaps I'm not using the undocumented "type:" in the preLaunchTask config correctly?

Can you give an example of the relevant files for this (launch.json, .code-workspace, and task.json)?

**Comment by aussiross** [comment]
On Mon, 2020-04-06 at 02:07 -0700, Alex Ross wrote:
> > I use a preLaunchTask to flash the target. However, it seems I'm
> > forced to provide a project level tasks.json defining "Flash",
> > because otherwise vscode won't resolve the "Flash" task name to a
> > workspace level task. Or perhaps I'm not using the undocumented
> > "type:" in the preLaunchTask config correctly?
> 
> Can you give an example of the relevant files for this (launch.json,
> .code-workspace, and task.json)?
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/microsoft/vscode/issues/92260#issuecomment-609670184
> ",
> "url": "
> https://github.com/microsoft/vscode/issues/92260#issuecomment-609670184
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
Hi,
In trying to reproduce I now realise this is only an issue when
attempting to call a workspace-level task from a project-level launch
task (and maybe vice versa - I haven't tried that). So with everything
at workspace level (as in working-example...) the Flash task executes,
but with the project-level launch task I get "Could not find task
Flash".

Since my aim was everything at the workspace level, this is no longer
an issue for me.  However, I guess somebody else may
come up against the issue.

Cheers,
Ross.     

{
	"settings": {
		"C_Cpp.default.compilerPath": "${env:HOME}/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc",
		"C_Cpp.default.compileCommands": "${workspaceFolder}/build/compile_commands.json",
		"C_Cpp.default.includePath": ["${env:HOME}/esp32/esp-idf/components/xtensa/include","${env:HOME}/esp32/esp-idf/components/xtensa/esp32/include","${env:HOME}/esp32/esp-idf/components/newlib/platform_include","${env:HOME}/esp32/esp-idf/components/freertos/include","${env:HOME}/esp32/esp-idf/components/freertos/xtensa/include","${env:HOME}/esp32/esp-idf/components/heap/include","${env:HOME}/esp32/esp-idf/components/log/include","${env:HOME}/esp32/esp-idf/components/lwip/include/apps","${env:HOME}/esp32/esp-idf/components/lwip/include/apps/sntp","${env:HOME}/esp32/esp-idf/components/lwip/lwip/src/include","${env:HOME}/esp32/esp-idf/components/lwip/port/esp32/include","${env:HOME}/esp32/esp-idf/components/lwip/port/esp32/include/arch","${env:HOME}/esp32/esp-idf/components/soc/src/esp32/.","${env:HOME}/esp32/esp-idf/components/soc/src/esp32/include","${env:HOME}/esp32/esp-idf/components/soc/include","${env:HOME}/esp32/esp-idf/components/esp_rom/include","${env:HOME}/esp32/esp-idf/components/esp_common/include","${env:HOME}/esp32/esp-idf/components/esp32/include","${env:HOME}/esp32/esp-idf/components/driver/include","${env:HOME}/esp32/esp-idf/components/driver/esp32/include","${env:HOME}/esp32/esp-idf/components/esp_ringbuf/include","${env:HOME}/esp32/esp-idf/components/efuse/include","${env:HOME}/esp32/esp-idf/components/efuse/esp32/include","${env:HOME}/esp32/esp-idf/components/esp_timer/include","${env:HOME}/esp32/esp-idf/components/soc/soc/esp32","${env:HOME}/esp32/esp-idf/components/soc/soc/esp32/include","${env:HOME}/esp32/esp-idf/components/soc/soc/esp32/../include","${env:HOME}/esp32/esp-idf/components/vfs/include","${env:HOME}/esp32/esp-idf/components/esp_wifi/include","${env:HOME}/esp32/esp-idf/components/esp_wifi/esp32/include","${env:HOME}/esp32/esp-idf/components/esp_event/include","${env:HOME}/esp32/esp-idf/components/esp_netif/include","${env:HOME}/esp32/esp-idf/components/esp_eth/include","${env:HOME}/esp32/esp-idf/components/tcpip_adapter/include","${env:HOME}/esp32/esp-idf/components/app_trace/include","${env:HOME}/esp32/esp-idf/components/mbedtls/port/include","${env:HOME}/esp32/esp-idf/components/mbedtls/mbedtls/include","${env:HOME}/esp32/esp-idf/components/wpa_supplicant/include","${env:HOME}/esp32/esp-idf/components/wpa_supplicant/port/include","${env:HOME}/esp32/esp-idf/components/wpa_supplicant/include/esp_supplicant","${env:HOME}/esp32/esp-idf/components/bootloader_support/include","${env:HOME}/esp32/esp-idf/components/app_update/include","${env:HOME}/esp32/esp-idf/components/spi_flash/include","${env:HOME}/esp32/esp-idf/components/nvs_flash/include","${env:HOME}/esp32/esp-idf/components/pthread/include","${env:HOME}/esp32/esp-idf/components/espcoredump/include","${env:HOME}/esp32/esp-idf/components/perfmon/include","${env:HOME}/esp32/esp-idf/components/asio/asio/asio/include","${env:HOME}/esp32/esp-idf/components/asio/port/include","${env:HOME}/esp32/esp-idf/components/cbor/port/include","${env:HOME}/esp32/esp-idf/components/coap/port/include","${env:HOME}/esp32/esp-idf/components/coap/port/include/coap","${env:HOME}/esp32/esp-idf/components/coap/libcoap/include","${env:HOME}/esp32/esp-idf/components/coap/libcoap/include/coap2","${env:HOME}/esp32/esp-idf/components/console","${env:HOME}/esp32/esp-idf/components/nghttp/port/include","${env:HOME}/esp32/esp-idf/components/nghttp/nghttp2/lib/includes","${env:HOME}/esp32/esp-idf/components/esp-tls","${env:HOME}/esp32/esp-idf/components/esp_adc_cal/include","${env:HOME}/esp32/esp-idf/components/esp_gdbstub/include","${env:HOME}/esp32/esp-idf/components/tcp_transport/include","${env:HOME}/esp32/esp-idf/components/esp_http_client/include","${env:HOME}/esp32/esp-idf/components/esp_http_server/include","${env:HOME}/esp32/esp-idf/components/esp_https_ota/include","${env:HOME}/esp32/esp-idf/components/protobuf-c/protobuf-c","${env:HOME}/esp32/esp-idf/components/protocomm/include/common","${env:HOME}/esp32/esp-idf/components/protocomm/include/security","${env:HOME}/esp32/esp-idf/components/protocomm/include/transports","${env:HOME}/esp32/esp-idf/components/mdns/include","${env:HOME}/esp32/esp-idf/components/esp_local_ctrl/include","${env:HOME}/esp32/esp-idf/components/sdmmc/include","${env:HOME}/esp32/esp-idf/components/esp_serial_slave_link/include","${env:HOME}/esp32/esp-idf/components/esp_websocket_client/include","${env:HOME}/esp32/esp-idf/components/expat/expat/expat/lib","${env:HOME}/esp32/esp-idf/components/expat/port/include","${env:HOME}/esp32/esp-idf/components/wear_levelling/include","${env:HOME}/esp32/esp-idf/components/fatfs/diskio","${env:HOME}/esp32/esp-idf/components/fatfs/vfs","${env:HOME}/esp32/esp-idf/components/fatfs/src","${env:HOME}/esp32/esp-idf/components/freemodbus/common/include","${env:HOME}/esp32/esp-idf/components/idf_test/include","${env:HOME}/esp32/esp-idf/components/jsmn/include","${env:HOME}/esp32/esp-idf/components/json/cJSON","${env:HOME}/esp32/esp-idf/components/libsodium/libsodium/src/libsodium/include","${env:HOME}/esp32/esp-idf/components/libsodium/port_include","${env:HOME}/esp32/esp-idf/components/mqtt/esp-mqtt/include","${env:HOME}/esp32/esp-idf/components/openssl/include","${env:HOME}/esp32/esp-idf/components/spiffs/include","${env:HOME}/esp32/esp-idf/components/ulp/include","${env:HOME}/esp32/esp-idf/components/unity/include","${env:HOME}/esp32/esp-idf/components/unity/unity/src","${env:HOME}/esp32/esp-idf/components/wifi_provisioning/include"],
		"C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools",
		"cmake.generator": "Ninja",
		"cmake.environment": {
			"IDF_PATH": "${env:HOME}/esp32/esp-idf",
			"IDF_TARGET": "esp32",
			"PYTHON_DEPS_CHECKED": "1",
			"ESP_PLATFORM": "1",
			"CCACHE_ENABLE": "0",
			"PATH": "${env:HOME}/esp32/esp-idf/components/esptool_py/esptool:${env:HOME}/esp32/esp-idf/components/espcoredump:${env:HOME}/esp32/esp-idf/components/partition_table/:${env:HOME}/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:${env:HOME}/.espressif/tools/xtensa-esp32s2-elf/esp-2019r2-8.2.0/xtensa-esp32s2-elf/bin:${env:HOME}/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/openocd-esp32/v0.10.0-esp32-20191114/openocd-esp32/bin:${env:HOME}/esp32/esp-idf/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"CXXFLAGS": "-DRMT_DEBUG"},
		"task.autoDetect": "off",
		"terminal.integrated.env.linux": {
			"IDF_PATH": "${env:HOME}/esp32/esp-idf",
			"PATH": "${env:HOME}/esp32/esp-idf/components/esptool_py/esptool:${env:HOME}/esp32/esp-idf/components/espcoredump:${env:HOME}/esp32/esp-idf/components/partition_table/:${env:HOME}/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:${env:HOME}/.espressif/tools/xtensa-esp32s2-elf/esp-2019r2-8.2.0/xtensa-esp32s2-elf/bin:${env:HOME}/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/openocd-esp32/v0.10.0-esp32-20191114/openocd-esp32/bin:${env:HOME}/esp32/esp-idf/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"IDF_WORKSPACE": "${env:HOME}/esp32/esp-idf_workspace",
			"OPENOCD_SCRIPTS": "${env:HOME}/.espressif/tools/openocd-esp32/v0.10.0-esp32-20191114/openocd-esp32/share/openocd/scripts"
        }
	},
	"launch": {
		"configurations": [
			{
				"name": "Debug",
				"type": "gdb",
				"request": "launch",
				"preLaunchTask": "Flash",
				"gdbpath": "${env:HOME}/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gdb",
				"autorun": [
					"target remote | ${env:HOME}/.espressif/tools/openocd-esp32/v0.10.0-esp32-20191114/openocd-esp32/bin/openocd -c 'gdb_port pipe' -f ${env:HOME}/esp32/esp-idf_workspace/esp32_jlink.cfg",
					"set remote hardware-watchpoint-limit 2",
					"mon reset halt",
					"flushregs",
					"thb app_main",
					"c"
				],
				"cwd": "${workspaceRoot}",
				"target": "${command:cmake.launchTargetPath}",
				"internalConsoleOptions": "openOnSessionStart",
				"valuesFormatting": "parseText"
			}
		]
	},
	"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"type": "shell",
				"label": "Flash",
				"command": "${env:HOME}/esp32/esp-idf_workspace/flash.sh all jtag '${command:cmake.launchTargetPath}'",
				"problemMatcher": [],
				"presentation": {
					"panel": "shared",
					"reveal": "always",
					"showReuseMessage": false
				}
            }
        ]
    },
    "folders": [
		{
			"path": "."
		}
	]
}

{
	"settings": {
		"C_Cpp.default.compilerPath": "${env:HOME}/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc",
		"C_Cpp.default.compileCommands": "${workspaceFolder}/build/compile_commands.json",
		"C_Cpp.default.includePath": ["${env:HOME}/esp32/esp-idf/components/xtensa/include","${env:HOME}/esp32/esp-idf/components/xtensa/esp32/include","${env:HOME}/esp32/esp-idf/components/newlib/platform_include","${env:HOME}/esp32/esp-idf/components/freertos/include","${env:HOME}/esp32/esp-idf/components/freertos/xtensa/include","${env:HOME}/esp32/esp-idf/components/heap/include","${env:HOME}/esp32/esp-idf/components/log/include","${env:HOME}/esp32/esp-idf/components/lwip/include/apps","${env:HOME}/esp32/esp-idf/components/lwip/include/apps/sntp","${env:HOME}/esp32/esp-idf/components/lwip/lwip/src/include","${env:HOME}/esp32/esp-idf/components/lwip/port/esp32/include","${env:HOME}/esp32/esp-idf/components/lwip/port/esp32/include/arch","${env:HOME}/esp32/esp-idf/components/soc/src/esp32/.","${env:HOME}/esp32/esp-idf/components/soc/src/esp32/include","${env:HOME}/esp32/esp-idf/components/soc/include","${env:HOME}/esp32/esp-idf/components/esp_rom/include","${env:HOME}/esp32/esp-idf/components/esp_common/include","${env:HOME}/esp32/esp-idf/components/esp32/include","${env:HOME}/esp32/esp-idf/components/driver/include","${env:HOME}/esp32/esp-idf/components/driver/esp32/include","${env:HOME}/esp32/esp-idf/components/esp_ringbuf/include","${env:HOME}/esp32/esp-idf/components/efuse/include","${env:HOME}/esp32/esp-idf/components/efuse/esp32/include","${env:HOME}/esp32/esp-idf/components/esp_timer/include","${env:HOME}/esp32/esp-idf/components/soc/soc/esp32","${env:HOME}/esp32/esp-idf/components/soc/soc/esp32/include","${env:HOME}/esp32/esp-idf/components/soc/soc/esp32/../include","${env:HOME}/esp32/esp-idf/components/vfs/include","${env:HOME}/esp32/esp-idf/components/esp_wifi/include","${env:HOME}/esp32/esp-idf/components/esp_wifi/esp32/include","${env:HOME}/esp32/esp-idf/components/esp_event/include","${env:HOME}/esp32/esp-idf/components/esp_netif/include","${env:HOME}/esp32/esp-idf/components/esp_eth/include","${env:HOME}/esp32/esp-idf/components/tcpip_adapter/include","${env:HOME}/esp32/esp-idf/components/app_trace/include","${env:HOME}/esp32/esp-idf/components/mbedtls/port/include","${env:HOME}/esp32/esp-idf/components/mbedtls/mbedtls/include","${env:HOME}/esp32/esp-idf/components/wpa_supplicant/include","${env:HOME}/esp32/esp-idf/components/wpa_supplicant/port/include","${env:HOME}/esp32/esp-idf/components/wpa_supplicant/include/esp_supplicant","${env:HOME}/esp32/esp-idf/components/bootloader_support/include","${env:HOME}/esp32/esp-idf/components/app_update/include","${env:HOME}/esp32/esp-idf/components/spi_flash/include","${env:HOME}/esp32/esp-idf/components/nvs_flash/include","${env:HOME}/esp32/esp-idf/components/pthread/include","${env:HOME}/esp32/esp-idf/components/espcoredump/include","${env:HOME}/esp32/esp-idf/components/perfmon/include","${env:HOME}/esp32/esp-idf/components/asio/asio/asio/include","${env:HOME}/esp32/esp-idf/components/asio/port/include","${env:HOME}/esp32/esp-idf/components/cbor/port/include","${env:HOME}/esp32/esp-idf/components/coap/port/include","${env:HOME}/esp32/esp-idf/components/coap/port/include/coap","${env:HOME}/esp32/esp-idf/components/coap/libcoap/include","${env:HOME}/esp32/esp-idf/components/coap/libcoap/include/coap2","${env:HOME}/esp32/esp-idf/components/console","${env:HOME}/esp32/esp-idf/components/nghttp/port/include","${env:HOME}/esp32/esp-idf/components/nghttp/nghttp2/lib/includes","${env:HOME}/esp32/esp-idf/components/esp-tls","${env:HOME}/esp32/esp-idf/components/esp_adc_cal/include","${env:HOME}/esp32/esp-idf/components/esp_gdbstub/include","${env:HOME}/esp32/esp-idf/components/tcp_transport/include","${env:HOME}/esp32/esp-idf/components/esp_http_client/include","${env:HOME}/esp32/esp-idf/components/esp_http_server/include","${env:HOME}/esp32/esp-idf/components/esp_https_ota/include","${env:HOME}/esp32/esp-idf/components/protobuf-c/protobuf-c","${env:HOME}/esp32/esp-idf/components/protocomm/include/common","${env:HOME}/esp32/esp-idf/components/protocomm/include/security","${env:HOME}/esp32/esp-idf/components/protocomm/include/transports","${env:HOME}/esp32/esp-idf/components/mdns/include","${env:HOME}/esp32/esp-idf/components/esp_local_ctrl/include","${env:HOME}/esp32/esp-idf/components/sdmmc/include","${env:HOME}/esp32/esp-idf/components/esp_serial_slave_link/include","${env:HOME}/esp32/esp-idf/components/esp_websocket_client/include","${env:HOME}/esp32/esp-idf/components/expat/expat/expat/lib","${env:HOME}/esp32/esp-idf/components/expat/port/include","${env:HOME}/esp32/esp-idf/components/wear_levelling/include","${env:HOME}/esp32/esp-idf/components/fatfs/diskio","${env:HOME}/esp32/esp-idf/components/fatfs/vfs","${env:HOME}/esp32/esp-idf/components/fatfs/src","${env:HOME}/esp32/esp-idf/components/freemodbus/common/include","${env:HOME}/esp32/esp-idf/components/idf_test/include","${env:HOME}/esp32/esp-idf/components/jsmn/include","${env:HOME}/esp32/esp-idf/components/json/cJSON","${env:HOME}/esp32/esp-idf/components/libsodium/libsodium/src/libsodium/include","${env:HOME}/esp32/esp-idf/components/libsodium/port_include","${env:HOME}/esp32/esp-idf/components/mqtt/esp-mqtt/include","${env:HOME}/esp32/esp-idf/components/openssl/include","${env:HOME}/esp32/esp-idf/components/spiffs/include","${env:HOME}/esp32/esp-idf/components/ulp/include","${env:HOME}/esp32/esp-idf/components/unity/include","${env:HOME}/esp32/esp-idf/components/unity/unity/src","${env:HOME}/esp32/esp-idf/components/wifi_provisioning/include"],
		"C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools",
		"cmake.generator": "Ninja",
		"cmake.environment": {
			"IDF_PATH": "${env:HOME}/esp32/esp-idf",
			"IDF_TARGET": "esp32",
			"PYTHON_DEPS_CHECKED": "1",
			"ESP_PLATFORM": "1",
			"CCACHE_ENABLE": "0",
			"PATH": "${env:HOME}/esp32/esp-idf/components/esptool_py/esptool:${env:HOME}/esp32/esp-idf/components/espcoredump:${env:HOME}/esp32/esp-idf/components/partition_table/:${env:HOME}/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:${env:HOME}/.espressif/tools/xtensa-esp32s2-elf/esp-2019r2-8.2.0/xtensa-esp32s2-elf/bin:${env:HOME}/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/openocd-esp32/v0.10.0-esp32-20191114/openocd-esp32/bin:${env:HOME}/esp32/esp-idf/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"CXXFLAGS": "-DRMT_DEBUG"},
		"task.autoDetect": "off",
		"terminal.integrated.env.linux": {
			"IDF_PATH": "${env:HOME}/esp32/esp-idf",
			"PATH": "${env:HOME}/esp32/esp-idf/components/esptool_py/esptool:${env:HOME}/esp32/esp-idf/components/espcoredump:${env:HOME}/esp32/esp-idf/components/partition_table/:${env:HOME}/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:${env:HOME}/.espressif/tools/xtensa-esp32s2-elf/esp-2019r2-8.2.0/xtensa-esp32s2-elf/bin:${env:HOME}/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:${env:HOME}/.espressif/tools/openocd-esp32/v0.10.0-esp32-20191114/openocd-esp32/bin:${env:HOME}/esp32/esp-idf/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"IDF_WORKSPACE": "${env:HOME}/esp32/esp-idf_workspace",
			"OPENOCD_SCRIPTS": "${env:HOME}/.espressif/tools/openocd-esp32/v0.10.0-esp32-20191114/openocd-esp32/share/openocd/scripts"
        }
	},
	"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"type": "shell",
				"label": "Flash",
				"command": "${env:HOME}/esp32/esp-idf_workspace/flash.sh all jtag '${command:cmake.launchTargetPath}'",
				"problemMatcher": [],
				"presentation": {
					"panel": "shared",
					"reveal": "always",
					"showReuseMessage": false
				}
            }
        ]
    },
    "folders": [
		{
			"path": "."
		}
	]
}

**Comment by LucaGabi** [comment]
@aussiross can you also please read this here: https://github.com/microsoft/vscode/issues/95182 and upvote if you find it useful ?

**Comment by weinand** [comment]
Since author said:
> Since my aim was everything at the workspace level, this is no longer
an issue for me.

I'm closing this issue.
