### ISSUE TITLE
Markdown code highlighting not the same in preview

### ISSUE THREAD

**Issue by DasJott** [microsoft/vscode#92267]
Issue Type: <b>Bug</b>

1. Create a README.md file.
2. Write a code example (I used go).
3. See the code within the code area gets highlighted.
4. Ctrl+Shift+v to the preview.
5. See the code highlighted differently!

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.4.23-1-MANJARO

**Comment by weinand** [comment]
Please provide screenshot showing the issue.

**Comment by DasJott** [comment]
## README.md
![image](https://user-images.githubusercontent.com/6298761/76223505-b778ae80-621b-11ea-9107-aa4d7560e14b.png)

## Preview of README.md
![image](https://user-images.githubusercontent.com/6298761/76224063-e1ca6c00-621b-11ea-8520-06271a0cbc37.png)

They look quite differenty.

**Comment by johanwendin** [comment]
Also, adding your own language for braced code blocks works great while editing, but doesn't highlight at all while previewing.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/84572

**Comment by DasJott** [comment]
https://github.com/microsoft/vscode/issues/84572#issuecomment-553127811

That is a rather lame excuse. ;-)

**The issue is, that it is not consistent!**

**Comment by mjbvz** [comment]
Yes, and you can install an extension to make it more consistent if you want that

**Comment by johanwendin** [comment]
Which extension can you install to have your own language extension highlighted in the markdown preview? Not even the superjs example has it, nor documentation on how to implement it yourself.

**Comment by mjbvz** [comment]
Did you try the extension from the [linked to comment](https://github.com/microsoft/vscode/issues/84572#issuecomment-553127811): https://marketplace.visualstudio.com/items?itemName=bierner.markdown-shiki?

**Comment by johanwendin** [comment]
Yes, that only changes the styling of existing highlighting - it does nothing for extension languages.

**Comment by DasJott** [comment]
In my opinion vscode should just make it consistent, not the user.
If you use two different highlightings, simply change that. I like the code one better than the preview one.
