### ISSUE TITLE
Docker command not found / task not executing in bash / command working

### ISSUE THREAD

**Issue by gr4nt3d** [microsoft/vscode#92262]
- About VSCode:
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

- Steps to Reproduce:
as described [there](https://stackoverflow.com/questions/56552022/vscode-how-to-run-docker-in-a-task-docker-build-task-does-not-work):
1. create a LaTeX-file
2. use the following task
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "runit",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "command": "docker",
            "args": [
                "run",
                "-v",
                "${fileDirname}:/doc/",
                "-t",
                "-i",
                "mytexlive",
                "pdflatex",
                "${fileBasename}"
            ],
            "problemMatcher": []
        }
    ]
}
```
3. try to build the file with [this](https://hub.docker.com/r/thomasweise/docker-texlive-full/) docker image and task from step 2 (worked in command line in every single occasion)

- Does this issue occur when all extensions are disabled?: No (Could possibly occur without aswell)

list of extensions
```
alefragnani.Bookmarks
Gimly81.matlab
huizhou.githd
James-Yu.latex-workshop
jithurjacob.nbpreviewer
ms-azuretools.vscode-docker
ms-python.python
ms-vscode.cpptools
psioniq.psi-header
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-german
vscode-icons-team.vscode-icons
```

Occurs randomly without any obvious indication. Stops at some point -- again for no good reason. When trying to reproduce it without extensions, it did not occur. However, it did not afterwards too (with extensions enabled again).

The issue #6579 describes the exact same problem, though it doesn't seem to be fixed.

**Comment by alexr00** [comment]
Looks like docker isn't on your path. Can you open the dev tools in VS Code and run `process.env.path`? What is returned from that? Where do you have docker installed?

**Comment by gr4nt3d** [comment]
Not sure I used the right console:
CMD+Shift+P: `> Developer: Open Webview Developer Tools`

`> process.env.path` returns
```
VM214:1 Uncaught ReferenceError: process is not defined
    at <anonymous>:1:1
```

I installed docker via Homebrew (`which docker` -> `/usr/local/bin/docker`)

Moreover, I can not say this is representative of the bug, as I do not have problems anymore with the task execution right now.

**Comment by alexr00** [comment]
Not quite the right developer tools, can you try with Developer: Toggle Developer Tools? 

How do you launch VS Code?

**Comment by gr4nt3d** [comment]
CMD+Shift+P: > `Developer: Toggle Developer Tools`
`> process.env.path` returns `undefined`
Calling just from command line with `code -n .` most of the time.

**Comment by alexr00** [comment]
Sorry, can you try `process.env.Path`? Perhaps it is case sensitive on your system.

**Comment by gr4nt3d** [comment]
Could have thought about that myself, thank you for the hint:
```
> process.env.Path
undefined
> process.env.PATH
"/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```
Please also note, that I have [upgraded my bash](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba) and set `"terminal.integrated.shell.osx": "/usr/local/bin/bash"` in my `settings.json`.

**Comment by alexr00** [comment]
Ok, it looks like your path isn't getting set in the way you expect when you launch VS Code. Related (but not identical I think) issue: https://github.com/microsoft/vscode/issues/21655
In the dev tools console, can you run `getLazyEnv().then(e => console.log(e))` and share the output from that?
There are a lot of difficulties around getting the path set nicely when VS Code is launched, so you can probably work around this by changing the way you launch it.

**Comment by gr4nt3d** [comment]
Tried to split the lines a bit:
<details> 
<summary> <code> getLazyEnv().then(e => console.log(e))</code></summary><p>

    Promise {<pending>}
    __proto__: Promise
    catch: ƒ catch()
    arguments: (...)
    caller: (...)
    length: 1name: "catch"
    __proto__: ƒ ()
    apply: ƒ apply()
    arguments: (...)
    bind: ƒ bind()
    call: ƒ call()
    caller: (...)
    constructor: ƒ Function()
    length: 0name: ""toString: ƒ toString()
    Symbol(Symbol.hasInstance)
    : ƒ [Symbol.hasInstance]()
    get arguments: ƒ ()
    set arguments: ƒ ()
    get caller: ƒ ()
    set caller: ƒ ()
    __proto__: Object
    [[FunctionLocation]]: <unknown>
    [[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]
    constructor: ƒ Promise()
    finally: ƒ finally()
    then: ƒ then()
    Symbol(Symbol.toStringTag): "Promise"
    __proto__: Object[[PromiseStatus]]: "resolved"
    [[PromiseValue]]: undefined

    APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: "true"
    ELECTRON_NO_ATTACH_CONSOLE: "1"
    HOME: "/Users/user_name"
    LOGNAME: "user_name"
    LaunchInstanceID: "447924C8-0E58-4C87-98B9-5FBEDDC61C68"
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin"
    PWD: "/Users/user_name"
    SHELL: "/bin/zsh"
    SHLVL: "2"
    SSH_AUTH_SOCK: "/private/tmp/com.apple.launchd.YDZiOMAruI/Listeners"
    TMPDIR: "/var/folders/hd/jtlkxw110cl8rvqcdz_b2y3h0000gn/T/"
    USER: "user_name"
    VSCODE_CLI: "1"
    VSCODE_IPC_HOOK: "/Users/user_name/Library/Application Support/Code/1.42.1-main.sock"
    VSCODE_LOGS: "/Users/user_name/Library/Application Support/Code/logs/20200310T103733"
    VSCODE_NLS_CONFIG: "{"locale":"en","availableLanguages":{},"_languagePackSupport":true}"
    VSCODE_NODE_CACHED_DATA_DIR: "/Users/user_name/Library/Application Support/Code/CachedData/c47d83b293181d9be64f27ff093689e8e7aed054"
    VSCODE_PID: "652"
    XPC_FLAGS: "0x0"
    XPC_SERVICE_NAME: "0"
    _: "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"
    __CF_USER_TEXT_ENCODING: "0x1F5:0:0"
    __proto__: Object
</p></details>

**Comment by gr4nt3d** [comment]
It seems that -if the problem occurs- the error is somewhat reproducible. The aforementioned **automator script leads to the problem**, whereas starting vscode from a terminal via `code -n .` at the same directory does not.

**Comment by joaomoreno** [comment]
Yup. That's exactly the issue. Can you try rewriting the script using [`open`](https://scriptingosx.com/2017/02/the-macos-open-command/) instead of calling `/usr/local/bin/code`?

**Comment by gr4nt3d** [comment]
These are my results:
```sh
#!/bin/sh
# /usr/local/bin/code -n "$1" # (1) fails from time to time
# open /usr/local/bin/code -n "$1" # (2) worked when (1) failed but does not respect the passed arguments and keeps terminals open
VSCODE_FORCE_USER_ENV=1 /usr/local/bin/code -n "$1" # (3) worked just fine and as expected when (1) failed
```
It does seem to fix it for the moment. Though, I am not completely sure where the problem came from in the first, as it does not appear to happen all the time.

**Comment by joaomoreno** [comment]
OK let me know if you still see it.
