### ISSUE TITLE
Opening settings UI when .json needed

### ISSUE THREAD

**Issue by daniladyabin** [microsoft/vscode#92264]
- VSCode Version: latest 1.43.0-insider
- OS Version: Linux x64 5.3.0-42-generic, also tested on newest Windows 10 x64

Steps to Reproduce:

1. Use any global debug configuration
2. Click on "settings" button called open launch.json, near selected debug configuration
3. When expecting settings.json, vscode will open settings UI

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Good catch. I have pushed a fix for this which you can see in vscode insiders from Wednesday. Let us know if it works for you know (though I verified and it is fixed for me).
Thanks!

**Comment by isidorn** [comment]
Did you get a chance to try this out in [VS Code insiders](https://code.visualstudio.com/insiders/)? Asking because we would like to add a verified label to this issue if it got fixed for you? Thanks

**Comment by daniladyabin** [comment]
Yes, works fine for me. Thanks!

**Comment by isidorn** [comment]
Great, thanks for letting us know. Adding verified label,
