### ISSUE TITLE
Change type of the scm.diffDecorations setting to Array.

### ISSUE THREAD

**Issue by agilesteel** [microsoft/vscode#92279]
As a user I would like to be able to specify multiple diff decorations like so:

```js
"scm.diffDecorations": ["gutter", "minimap"]
```

**Comment by smithjosh115** [comment]
I am going to give a try at resolving this.

**Comment by joaomoreno** [comment]
Do a full text search for `scm.diffDecorations` and go from there. ;)

**Comment by jpshrader** [comment]
@smithjosh115 I wouldn't mind cutting my teeth on this as well, if you'd like a second pair of eyes.
