### ISSUE TITLE
[Bug] tslint doesn't detect webpack aliases?

### ISSUE THREAD

**Issue by Luchillo** [Microsoft/vscode#9227]
- VSCode Version: 1.3.1
- OS Version: Ubuntu 15.10

Steps to Reproduce:

I have a webpack config with an alias for an import path, VSCode doesn't recognize this, i've tried with 
the `tsconfig.json`'s paths option:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "filesGlob": [
    "**/*.ts",
    "!node_modules/**/*"
  ],
  "exclude": [
    "node_modules",
    "typings/global",
    "typings/global.d.ts"
  ],
  "paths": {
    "tao-animations": "app/theme/core/app.tao-animations.ts"
  },
  "compileOnSave": true,
  "atom": {
    "rewriteTsconfig": false
  }
}
``` 

But it still doesn't find the module even if webpack compiles ok:
![image](https://cloud.githubusercontent.com/assets/9698639/16816733/f80f40b4-4904-11e6-91bf-cac6644f8d88.png)

**Comment by egamma** [comment]
@Luchillo does this work when you invoke tslint on the command line?

**Comment by Luchillo** [comment]
The error mesage says `ts` so i guess it is the ts version, is there a way to tell ts to map or alias a file path just like i do in webpack?

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10088

**Comment by dbaeumer** [comment]
Moved to the TS team.

**Comment by Luchillo** [comment]
Does it really belongs to the ts team? isn't the vscode editor the one showing an error because my build process with webpack has aliases but vscode can't know that?

**Comment by Luchillo** [comment]
I've updated to TS2 but the VSCode project still shows the error, could it be that vscode uses it's own ts version aside of the one installed global with npm?

**Comment by dbaeumer** [comment]
@Luchillo VSCode ships out of the box with a ts version (which is the latest official version 1.8.10). If you want to use a different version you can set the setting
```
"typescript.tsdk": "./node_modules/typescript/lib"
```

if for example you want to use the ts support from the local TS npm module.

**Comment by Luchillo** [comment]
I can't use the local since i open the parent folder to view multiple projects  at once, so i installed globally and put this in the `.vscode/settings.json` file however the error still shows:

```json
// Place your settings in this file to overwrite default and user settings.
{
  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"
}
```

Here's the `package.json` of that typescript folder:

```sh
$ cat /usr/local/lib/node_modules/typescript/package.json 
{
  ...
  "license": "Apache-2.0",
  "main": "./lib/typescript.js",
  "maintainers": [ ... ],
  "name": "typescript",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Microsoft/TypeScript.git"
  },
  "scripts": { ... },
  "typings": "./lib/typescript.d.ts",
  "version": "2.0.0"
}
```

**Comment by dbaeumer** [comment]
@Luchillo a global version of the TS compiler should work  as well. 

I moved this to the TS team since we use the tsserver/compiler from them to generate the errors. If this is to be supported it has to come from them.

**Comment by Luchillo** [comment]
So it works but the TS v 2.0 that supposedly supported this feature fail to parse my code?

**Comment by Luchillo** [comment]
Sorry, was a bad miss-configure in my `tsconfig.json`, all works now as expected.
