### ISSUE TITLE
Font change in quick pick selection

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#92270]
- Clone https://github.com/microsoft/vscode-eslint
- Run command `Run Task`

![bug](https://user-images.githubusercontent.com/4033249/76229182-03f1c900-61df-11ea-99f0-97634f417e47.gif)

**Comment by chrmarti** [comment]
Sorry, what font change? What's actual vs. expected behavior?

**Comment by octref** [comment]
Sorry, for some reason, I thought the blue text became larger, whereas it was just offseted by the gear icon... 🤦‍♂
