### ISSUE TITLE
Allow horizontal scrolling in the debug sidebar

### ISSUE THREAD

**Issue by somebeaver** [microsoft/vscode#92286]
Currently, it is impossible to scroll horizontally in the debugger sidebar (where you view your variables during breakpoints).

It would be very convenient to be able to do so instead of having to resize the entire sidebar to expand deeply nested objects and read their long string properties.

Thank you for your consideration.

**Comment by ArturoDent** [comment]
Enable this setting:

`Workbench > List: Horizontal Scrolling`
