### ISSUE TITLE
ElementaryOS: does not show recents in dock

### ISSUE THREAD

**Issue by katlimruiz** [microsoft/vscode#92289]
For elementaryOS, when right clicking the icon, it should show the "Recent Folders" opened. Like VsCode does in Windows.

**Comment by bpasero** [comment]
Please report this against [Electron](https://github.com/atom/electron), we use their API for this purpose which seems unsupported on Linux:

https://github.com/electron/electron/blob/7-1-x/docs/api/app.md#appaddrecentdocumentpath-macos-windows
