### ISSUE TITLE
Cant enter @ (at symbol) in VS Code file/TERMINAL

### ISSUE THREAD

**Issue by jitendrakansal** [microsoft/vscode#92281]
Issue Type: <b>Bug</b>

Hi Team, I am unable to enter @ (Ampersat, arobase, asperand, at, or at symbol) in a file  and in TERMINAL as well. When i press this symbol on Mac keyboard, it displays a warning "command 'extension.generateLinkReport' not found". 
I checked some existing posts but couldnt get it working. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
markdown-preview-github-styles|bie|0.1.6
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.34.0
xml|Dot|2.5.0
copy-relative-path|eri|0.0.4
prettier-vscode|esb|3.20.0
beautify|Hoo|1.5.0
RelativePath|jak|1.4.0
java|red|0.58.0
vscode-xml|red|0.10.1
vsc-extension-mbt|SAP|1.4.0
vsc-extension-mdk|SAP|1.14.1
vscode-cds|SAP|1.2.11
markdown-preview-enhanced|shd|0.5.2
nativescript|Tel|0.11.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0

</details>

**Comment by retnikt** [comment]
It looks like you have set it as a keyboard shortcut for a command (`extension.generateLinkReport`) provided by an extension that no longer exists. You can remove it in File -> Settings -> Keyboard Shortcuts

**Comment by jitendrakansal** [comment]
Awesome, appreciated your fast response. 
Got it working now.
