### ISSUE TITLE
Malformed manifest.yml in project prevents opening of Bluemix panel

### ISSUE THREAD

**Issue by jpapejr** [Microsoft/vscode#9229]
- VSCode Version: 1.3.1
- OS Version: 10.11.5

Steps to Reproduce:

1. Create a new project in Bmx Code
2. Create a malformed manifest.yml file
3. Try to open the Bluemix panel by clicking on the Bluemix logo in the left portion of the screen. 

Expectation:

Toss an error or handle it quietly, still showing the panel contents for the Bluemix stuff.

**Comment by weinand** [comment]
@jpapejr I don't recognize "Bmx" or "Bluemix" as a part of VS Code. If "Bmx" is an extension, please create an issue against the corresponding extension.

**Comment by jpapejr** [comment]
Wrong product sorry.

**Comment by weinand** [comment]
@jpapejr no problem ;-)
