### ISSUE TITLE
Sometimes a bunch of my files are duplicated and a 2 is appended to the filename

### ISSUE THREAD

**Issue by aaronbuchwald** [microsoft/vscode#92292]
This is a very strange issue when I'm using visual studio, sometimes some of my files get duplicated and there's a 2 at the end of the name of the file. For instance mod.mk gets duplicated to create a file called "mod 2.mk"

**Comment by rebornix** [comment]
@aaronbuchwald can you help confirm 

1. you are using VS Code, other than Visual Studio
2. Do you run into the same issue when you have extensions disabled?

**Comment by aaronbuchwald** [comment]
I am using Visual Studio Code version 1.43.1 on Mac OSX. The issue occurs somewhat randomly, so I have not tried turning off extensions to see if the issue still occurs.

**Comment by Lozni** [comment]
I am getting the EXACT same issue with duplicated files and with 2 (and sometimes a 3 at the end). I noticed the issue when I was on version 1.40.2 and I updated it today on 1.43.2 and the same happened. Random amounts of files get duplicated when I open the Visual Studio Code or if my Mac goes to sleep mode or stand by. Please help me with this!
