### ISSUE TITLE
Search Editor for current document

### ISSUE THREAD

**Issue by ldsands** [microsoft/vscode#92298]
Hi all,

First off I love this new Search Editor feature! One thing that would be handy is the ability to use the `search.action.openInEditor` command to lauch the editor from the search box if the cursor is in the search box. By search box I mean the little search box that comes up when pressing `Ctrl` + `F` not the search sidebar.

Thank you for this new feature I'll be using it a lot!

**Comment by JacksonKearl** [comment]
How would this work exactly? Start a new workspace search with the configuration you have in you in-editor search?

**Comment by ldsands** [comment]
That is what I had in mind. Though now that I think about it, it might be nice to have an option to just search the current document and open those results in the search editor.

**Comment by JacksonKearl** [comment]
That could be cool.

**Comment by JacksonKearl** [comment]
Going to fold this in to #95582.

**Comment by JacksonKearl** [comment]
With #95582 you should now be able to do something like:
```
    {
        "key": "ctrl+shift+g",
        "command": "search.action.openNewEditor",
        "args": {
            "query": "${selectedText}",
            "filesToInclude": "${relativeFile}"
        },
        "when": "editorTextFocus"
    }
```
