### ISSUE TITLE
Localization mistakes

### ISSUE THREAD

**Issue by dy55** [microsoft/vscode#92306]
Issue Type: <b>Bug</b>

I just found some problems related to localization.

Select "zh-cn" (Simplified Chinese) as display language, and reopen VS Code. 

And then you will see something wrong with the "Open Folder" button and "Clone Repository" button in the explorer at the side bar. They should be "[打开文件夹](command: workbench.action.files.openFolder)" and "[克隆存储库](command: git.clone)".

And there is another mistake at the custom title bar. The bar item read "&运行" should be "运行(R)".

![批注 2020-03-10 101601](https://user-images.githubusercontent.com/44740171/76273454-da0cd500-62b8-11ea-9b1d-0190d52e893d.png)

We will appreciate it if they would be solved. Thanks🙂

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
docs-yaml|doc|0.2.4
vscode-html-css|ecm|0.2.3
vscode-firefox-debug|fir|2.7.0
vscode-pull-request-github|Git|0.14.0
minify|Hoo|0.4.3
minifyall|jos|2.1.5
Kotlin|mat|1.7.1
vscode-language-pack-ja|MS-|1.43.2
vscode-language-pack-zh-hans|MS-|1.43.2
csharp|ms-|1.21.13
vscode-edge-devtools|ms-|1.0.7
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.64397
vscode-ai|ms-|0.6.9
remote-wsl|ms-|0.42.3
azure-account|ms-|0.8.8
cpptools|ms-|0.26.3
Go|ms-|0.13.1
powershell|ms-|2020.3.0
typescript-javascript-grammar|ms-|0.0.53
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1711
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.15.0
vscode-manifest-yaml|Piv|1.15.0
vscode-spring-boot|Piv|1.15.0
java|red|0.58.0
vscode-xml|red|0.10.1
vscode-yaml|red|0.7.2
rust|rus|0.7.0
usql-vscode-ext|usq|0.2.15
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by zhaohaiyanggit** [comment]
I met the same problem. And the ‘Run and debug’  button can't work when use Chinese (Traditional) Language Pack for Visual Studio Code

**Comment by lukaschal** [comment]
On review.

SRC: In order to use git features, you can open a folder containing a git repository or clone from a URL. [Open Folder](command:vscode.openFolder) [Clone Repository](command:git.clone) To learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm).


TGT: 为了使用 git 功能，可打开包含 git 存储库的文件夹或从 URL 克隆。 [打开文件夹](命令: vscode.openFolder) [克隆存储库](命令: git.clone) 要详细了解如何在 VS Code 中使用 Git 和源代码管理，[请阅读我们的文档](https://aka.ms/vscode-scm)。


SRC: You can also clone a repository from a URL. To learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm). [Clone Repository](command:git.clone)

TGT: 还可从 URL 克隆存储库。要详细了解如何在 VS Code 中使用 Git 和源代码管理，[请阅读我们的文档](https://aka.ms/vscode-scm)。 [克隆存储库](命令: git.clone)


SRC: To customize Run and Debug, [open a folder](command:{0}) and create a launch.json file.
TGT: 要自定义运行和调试，请[打开文件夹](命令 :{0}) 并创建一个启动.json 文件。


SRC: You have not yet opened a folder. [Open Folder](command:{0})
TGT: 你尚未打开文件夹。 [打开文件夹](命令: {0})


SRC: Connected to remote. [Open Folder](command:{0})
TGT: 已连接到远程。 [打开文件夹](命令: {0})

**Comment by dy55** [comment]
> On review.
> 
> SRC: In order to use git features, you can open a folder containing a git repository or clone from a URL. Open Folder Clone Repository To learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm).
> 
> TGT: 为了使用 git 功能，可打开包含 git 存储库的文件夹或从 URL 克隆。 [打开文件夹](命令: vscode.openFolder) [克隆存储库](命令: git.clone) 要详细了解如何在 VS Code 中使用 Git 和源代码管理，[请阅读我们的文档](https://aka.ms/vscode-scm)。
> 
> SRC: You can also clone a repository from a URL. To learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm). Clone Repository
> 
> TGT: 还可从 URL 克隆存储库。要详细了解如何在 VS Code 中使用 Git 和源代码管理，[请阅读我们的文档](https://aka.ms/vscode-scm)。 [克隆存储库](命令: git.clone)
> 
> SRC: To customize Run and Debug, open a folder and create a launch.json file.
> TGT: 要自定义运行和调试，请[打开文件夹](命令 :{0}) 并创建一个启动.json 文件。
> 
> SRC: You have not yet opened a folder. Open Folder
> TGT: 你尚未打开文件夹。 [打开文件夹](命令: {0})
> 
> SRC: Connected to remote. Open Folder
> TGT: 已连接到远程。 [打开文件夹](命令: {0})
---

Thank you so much for the info🤝

The main problem is some words or code should not be translated, but they are done.

The buttons such as `[Open Folder](command: vscode.openFolder)` should be translated to `[打开文件夹](command: vscode.openFolder)` (Just translate words in the square brackets).

In addition, the translator software usually translates English punctuation marks to Chinese ones, but some of them are parts of code. It causes error too.

In my view, those translations should be:

SRC: In order to use git features, you can open a folder containing a git repository or clone from a URL. Open Folder Clone Repository To learn more about how to use git and source control in VS Code read our docs.

TGT: 想要使用 git 功能，可以打开包含 git 存储库的文件夹或通过 URL 克隆。 [打开文件夹](command: vscode.openFolder) [克隆存储库](command: git.clone) 要详细了解如何在 VS Code 中使用 Git 和源代码管理，请阅读我们的文档。

SRC: You can also clone a repository from a URL. To learn more about how to use git and source control in VS Code read our docs. Clone Repository

TGT: 还可从 URL 克隆存储库。要详细了解如何在 VS Code 中使用 Git 和源代码管理，请阅读我们的文档。 [克隆存储库](command: git.clone)

SRC: To customize Run and Debug, open a folder and create a launch.json file.
TGT: 要自定义运行和调试，请[打开文件夹](command: {0}) 并创建一个 launch.json 文件。

SRC: You have not yet opened a folder. Open Folder
TGT: 你尚未打开文件夹。 [打开文件夹](command: {0})

SRC: Connected to remote. Open Folder
TGT: 已连接到远程。 [打开文件夹](command: {0})

**Comment by lukaschal** [comment]
All instances of "(command:" are in english now on all languages.

**Comment by danyeh** [comment]
FYI. @weeteckt
