### ISSUE TITLE
Revisit usage of box-shadow

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#92301]
IMO the shadows used in the app are weird, here's a notification with its default shadow:

```css
box-shadow: rgba(0, 0, 0, 0.53) 0px 0px 8px;
```

![image](https://user-images.githubusercontent.com/1812093/76266745-5c1cdf80-6260-11ea-94c4-7ae190821820.png)

That shadow is unnatural, shadows are caused by objects obstructing a light source, the object in this case is the notification itself and for that shadow to happen the light source should come perpendicularly out of the notification, i.e. it should be perpendicular to the screen, basically it's as if I'm the light source in this scenario, and I'm not usually the main light source in the real world.

In the real world the biggest light source is the sun and during the day it's pretty much always above the objects obstructing its light rays, i.e. the shadow one sees usually is more accentuated at the bottom, not at the top, nor it is uniformly distributed like in the screenshot above.

Here's what a notification with a more natural shadow would look like:

```css
box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.4);
```

![image](https://user-images.githubusercontent.com/1812093/76266914-f11fd880-6260-11ea-897e-d220effe5e2e.png)

I think that's a significant improvement, considering we are talking about a shadow, enough of an improvement that I had to open this issue 😅

**Comment by fabiospampinato** [comment]
I wonder how the bot would think this issue is about a slow startup, maybe sun -> star -> start-up? 🤔

**Comment by isidorn** [comment]
Forwarding to @bpasero and @misolori since this is notifications.

**Comment by bpasero** [comment]
We do not have to support to specify more than one shadow color for theme authors. We use `widget.shadow` currently:

https://github.com/microsoft/vscode/blob/12979c45f17ca571cab023d3542626940d7f3ab6/src/vs/workbench/browser/parts/notifications/notificationsToasts.ts#L452

If we want to revisit `box-shadows`, we should probably do this consistently throughout all of our uses, there are many more.

**Comment by misolori** [comment]
Verification:

- Compare notifications/quick pick/web dialog shadows are less vibrant than stable version ([see for comparison](https://github.com/microsoft/vscode/pull/110272#issue-518116735))
