### ISSUE TITLE
[json] Trying to set local JSON Schema file, generates empty files while typing the filename

### ISSUE THREAD

**Issue by ajdvoynos** [microsoft/vscode#92300]
Issue Type: <b>Bug</b>

1. Open new tab
2. Set language to JSON
3. Create an empty json object
4. Start typing a "$schema" property that points to a local schema file (in the same folder for example)

Expected: No other tabs are created while typing
Actual: VSCode starts creating new tabs with the partial filename that I'm writing.

For example, if I try to set the schema to "./schema.json" it would create 11 new tabs(one for each letter I typed after the ./"

![image](https://user-images.githubusercontent.com/5531373/76267495-495bd800-626b-11ea-82a3-2f023c65ffae.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettify-json|moh|0.0.3
vscode-azurefunctions|ms-|0.21.0
csharp|ms-|1.21.13
remote-wsl|ms-|0.42.3
azure-account|ms-|0.8.8
vsliveshare|ms-|1.0.1711
vscode-json-path|wei|2.3.1
markdown-pdf|yza|1.4.2

</details>

**Comment by ajdvoynos** [comment]
@aeschli That was a really fast fix, thanks! Unfortunately, there's still something weird happening. It seems like Code is still trying to open the tabs, but it's hiding them or something?

At first the only indication is in the Explorer view (notice 4 unsaved elements when I don't have any open unsaved documents):
![image](https://user-images.githubusercontent.com/5531373/78678849-ca999f80-78e9-11ea-8a1c-810e3b5ebd9a.png)

But if you close Code and open the workspace again, it opens all the tabs again:
![image](https://user-images.githubusercontent.com/5531373/78678951-e8670480-78e9-11ea-8809-3b2f875ae32a.png)

This happens to me every time I reopen the workspace where I'm working with the json schema.

Let me know if you need more info. Thanks!

**Comment by ajdvoynos** [comment]
I'm having a hard time reproducing this consistently. The only consistent behavior I'm seeing is when you reopen the workspace it tries to open the tabs. 

The real strange thing though, is that even after renaming the $schema to something else, it still tries to open the old schema file, which is not referenced anywhere anymore, so that leads me to believe it may be a bug tied specifically to workspaces? It's still somewhere holding a reference to those files?

**Comment by aeschli** [comment]
@ajdvoynos no worries, we understand the issue and a fix has been pushed a while ago to insiders. You can try things there. Or wait for stable (1.44) which will come out these days.

**Comment by ajdvoynos** [comment]
Oh my bad! I thought the issue was resolved in 1.43 which is the one I was using. I just tried it out in 1.44 and I'm not seeing any issues anymore.
