### ISSUE TITLE
contributes.jsonValidation fileMatch should allow array

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#92302]
The [contributes.jsonValidation](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation) `fileMatch` appears to only accept `string`, but the `json.schemas` configuration `fileMatch` accepts `array`. I think they should both accept `array`.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/commit/785eb0872a97f18775ca294fe2a4e4e35fc6a10e
