### ISSUE TITLE
Disable or remove specific code action/fixes/refactoring

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#92305]
Because when some code action is available, there will be a icon shows on the code editing area. 
If some fixes I always not want, it's annoying that the clickable icon will show every time my cursor move on the code or select some code or some other actions. Especially when the current line left is not white spaces, the icon will show at previous line and cover the privious line code.

For example, I always want use `require` in js file not `import`.

And maybe some visual effect like the dash underline, the `show fixes` button in the popup tip, the dimmed color text should be removed, when the relate code action is disabled. Because these hint there are problems in my code but actually not.

**Comment by mjbvz** [comment]
You can disable the lightbulb by setting: `"editor.lightbulb.enabled": false`

Disabling individual actions is up to the extension that provides these actions. Please open individual issues for these

**Comment by heroboy** [comment]
hi @mjbvz ,  the code actions are queried and show the ui by vscode, vscode has a way to filter them.
And it's more generial if this implement in the vscode side.

**Comment by themattsterr** [comment]
I agree with @heroboy. I want the lightbulb to be displayed, but it is always suggesting I change modifiers to final where possible.

I'm using the Language Support for Java(TM) by Red Hat extension.
