### ISSUE TITLE
Please support Relaxed JSON

### ISSUE THREAD

**Issue by Skeeve** [microsoft/vscode#92319]
You already support JSON with comments. I'd love to see this going one step further to [Relaxed JSON](http://www.relaxedjson.org/).

It not only has comments in but also allows for trailing commas, which really is a relief when you want to add more elements to an array or object. You do not need to remember to add a comma in the line before and do not need to not put a comma at the end. You simply always put a comma.

But there is more. Please check the description.

**Comment by aeschli** [comment]
Relaxed JSON looks great but we currently have no plans of supporting another JSON flavor. We do so for JSON with comments as it's what we use in our settings files.
