### ISSUE TITLE
Unable to start debugging. No terminal is available to launch the debugger. Please install Gnome Terminal or XTerm.

### ISSUE THREAD

**Issue by naveedrasheed** [Microsoft/vscode#9231]
- VSCode Version: 1.3.1
- OS Version: ArchLinux

Steps to Reproduce:

1. Build a C\C++ project.
2. Create launch.json
3. Try to start debugging.

I think there should be an option in launch.json to set terminal path as well.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscppsamples#98
