### ISSUE TITLE
Task error with Powershell script ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#92310]
I have a task which loads a PowerShell script, the `command` property is used within the `tasks.json` file; besides changing the name of the Powershell script, the path location is the same but my previous script worked, my changed script is not working, same path, different file name ?

The error I'm getting is this;

> Executing task in folder CodeProjects: ./tasks/pathExtend.ps1 -$argList <
> 
> The terminal shell CWD "\\Custom Program Settings\Projects.Code" does not exist
> 
> Terminal will be reused by tasks, press any key to close it.

Here is a snippet of the first part of the task;

```
"version": "2.0.0",
    "tasks": [
        {
            "label": "EXRTool",
            "type": "shell",
            "command": [
                "./tasks/pathExtend.ps1 -$argList" 
            ],

```

I would like to know what went wrong, why the first script worked; the new changed script doesn't as so I don't encounter this problem any longer ?

**Comment by alexr00** [comment]
It looks like the current working directory (CWD) that you have doesn't exist. Some ideas to get you started:
- Is "\Custom Program Settings\Projects.Code" a valid path on your system? 
- Where might "\Custom Program Settings\Projects.Code" be coming from?
- Is the folder you have open unusual in some way (is it not on your local system for example)?
- Does the problem happen if you disable all extensions?
- Do you have any terminal settings set?

**Comment by SheepDomination** [comment]
@alexr00 

Of course `"\Custom Program Settings\Projects.Code"` is a valid path on my system. 

What do you mean by; 

> Where might "\Custom Program Settings\Projects.Code" be coming from?

 ?

> Is the folder you have open unusual in some way (is it not on your local system for example)?

These questions seem redundant, as I mentioned the folder is existing on my local system.

What do you mean;

> Do you have any terminal settings set?

?

**Comment by alexr00** [comment]
Are you using Windows? `\Custom Program Settings\Projects.Code` doesn't look like a full Windows path, which is why I'm asking where it's coming from. For terminal settings, you can look in your VS Code settings and see if you have any settings related to terminal, since they can affect your CWD.

**Comment by SheepDomination** [comment]
Yes I'm using Windows. 
`C:\Custom Program Settings\Projects.Code` is a full Windows path. There is no other setting in my settings file related to CWD.
