### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by sysdl132** [microsoft/vscode#92313]
- VSCode Version:1.43.0
- OS Version:windows 10 1903

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/54708046/76281691-cf5e3a00-62d0-11ea-9072-06e138051cf0.png)

直接打开vscode就像这样
if I open the vscode directly,it will like this.

使用：Chinese (Simplified) Language Pack for Visual Studio Code
Used:Chinese (Simplified) Language Pack for Visual Studio Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by sysdl132** [comment]
same in 2 windows.
![image](https://user-images.githubusercontent.com/54708046/76282065-a0949380-62d1-11ea-9de4-07073cfa6ac8.png)

**Comment by rebornix** [comment]
mnemonics is broken in localization.

**Comment by dbaeumer** [comment]
The latest translation packs have not been shipped yet. So I would wait investigate until they are out.

**Comment by dbaeumer** [comment]
@janbaltus can you please ping when the LP are available.

**Comment by janbaltus** [comment]
1.43.2 which is latest LP contain this issue. We will fix for 1.44.0

**Comment by sysdl132** [comment]
Thanks for your answer

**Comment by sysdl132** [comment]
In 1.43.2:Problem solved.Thanks!
![image](https://user-images.githubusercontent.com/54708046/77622800-e1e79d00-6f79-11ea-8e54-2a9db93e7dd3.png)
