### ISSUE TITLE
Fonts switch to incorrent styles after a split second of selecting a theme

### ISSUE THREAD

**Issue by imAliAzhar** [microsoft/vscode#92327]
- VSCode Version:  1.43.0
- OS Version: MacOS Catalina, 10.15.3

Steps to Reproduce:

1. Switch color themes

Does this issue occur when all extensions are disabled?: Yes (for defaults themes like Red, Solarized Dark etc)

In the GIF, observe `dispatch` function, it updates color after selecting a theme.
![vscode-themes-bug](https://user-images.githubusercontent.com/18743730/76296811-96c25e80-62d8-11ea-90f3-83c296d1d89c.gif)

**Comment by gjsjohnmurray** [comment]
Some themes haven't yet been updated by their maintainers to support semantic highlighting. See https://github.com/microsoft/vscode/issues/92308#issuecomment-596885893 for a workaround.

**Comment by aeschli** [comment]
@gjsjohnmurray Themes don't need any adoption. Themes continue to work on the same textmate scopes as input. But the input is no longer just coming from the TextMate grammar, but also from the semantic highlighter.
Some identifiers have been re-categorized based on their resolved symbol.

`dispatch` is a parameter and now gets the parameter color everywhere.
What's special here is that dispatch is callback and is used like a function and was colored as such.
I have to think what we should to do.

**Comment by aeschli** [comment]
The issue that `dispatch` is shown as a parameter but you expect it to be a function is https://github.com/microsoft/vscode/issues/91038

Marking as duplicate.
