### ISSUE TITLE
Icons in Git panel are invisible

### ISSUE THREAD

**Issue by blindrood** [microsoft/vscode#92322]
- VSCode Version: 1.43
- OS Version: Windows 10

Steps to Reproduce:

1. Update to 1.43
2. Open git panel

![image](https://user-images.githubusercontent.com/48821393/76292532-b2653f00-62af-11ea-92b5-24b4644ae1e4.png)

Buttons for commit, refresh etc. are invisible. They are there, still working, have label but invisible

**Comment by rebornix** [comment]
@sbatten any idea of what's going on?

**Comment by sandy081** [comment]
Can you please try to repro by disabling all installed extensions?

**Comment by blindrood** [comment]
Extensions -> 3 dots -> Disable All Extenstions -> Stop -> Start
Result: No change

**Comment by dlucazeau** [comment]
I tried this before your post and I confirm that it doesn't change anything.
I returned to the previous version

**Comment by sandy081** [comment]
Can you please do following steps:

- Open Developer Tools (Use command `Developer: Toggle Developer Tools`)
- Go to element tab and click on the mouse pointer cursor
- And point to the empty space where icons are missing
- This shall reveal the corresponding HTML in the elements tab
Provide us the screen shot of those elements tab.

**Comment by dlucazeau** [comment]
Done
![image](https://user-images.githubusercontent.com/4538922/76652639-4ca2dc80-6567-11ea-96c6-e5a1c3eb4976.png)

**Comment by sandy081** [comment]
Can you please show the styles section to see where icon is located and if icon exists or not in the location.

**Comment by dlucazeau** [comment]
The first screenshot concerns an unvailable icon and the second a normal situation. In the first case when we click on ::before, this pseudo-element disappear from the dom.
![image](https://user-images.githubusercontent.com/4538922/76833002-c4545e00-682a-11ea-8862-0befe9a50a89.png)
![image](https://user-images.githubusercontent.com/4538922/76833012-cf0ef300-682a-11ea-99ae-f09ae4d69212.png)

**Comment by sandy081** [comment]
@dlucazeau It shows following for me. If you see in the right of the screenshot there is a location of the icon. Do you see the same for the icon which is not visible?

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/10746682/77102118-a3e9f680-6a18-11ea-994a-5b123a7dfa0d.png">

**Comment by dlucazeau** [comment]
With VSCode insiders and the last version of VSCode, I don't see the place for GitLens icon. With the previous version (1.42.1) of VSCode, yes i have the icon. This bug has already be corrected some version ago.
The icon lacking in a sent screenshot is GitLens.

**Comment by sandy081** [comment]
@dlucazeau Can you please take the screenshot by inspecting the invisible icon (gitlens in your case). I would like to know the location of the icon as in the screenshot I sent.

**Comment by joaomoreno** [comment]
@misolori Any insights, regarding the adoption of codicons?

**Comment by blindrood** [comment]
Please reopen and provide step-by-step info on how to proceed with inspecting.
Issue still occurs. I'm missing icons in git panel as well as couple icons on main bar for extensions (e.g. docker, gitlab workflow)

**Comment by sandy081** [comment]
Please follow the discussion in https://github.com/microsoft/vscode/issues/92323 as there are some interesting results revealed there.
