### ISSUE TITLE
When clause startsWith operator

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode#92329]
Hi,
It will be handy to test if a string startsWith a substring in the case of displaying a menu when declaring it in package.json.

It will be reasonable to have also other operators like:
- startsWith 
- endsWith
- contains

**Comment by mjcrouch** [comment]
You can definitely do contains using `key =~ /<value>/` - it is a regular expression, though I haven't tested the anchor characters to confirm that they work

**Comment by llgcode** [comment]
Hi @mjcrouch ,
Really sorry, I didn't read the doc well. 
Thanks
Laurent

**Comment by llgcode** [comment]
I wrote this to have startsWith:
`key =~ /^prefix-/`

You may add the operator to this list:
https://code.visualstudio.com/docs/getstarted/keybindings#_conditional-operators
