### ISSUE TITLE
Orca not reading languages list

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92324]
In Ubuntu, Orca doesn't speak the language modes when pressing ctrl+k, m when in Code Insider's.
Ubuntu 20.04, Orca master (3.37.1 pre), Code Insider's 1.44.

1.	Start Orca.
2.	Load Code Insider's.
3.	If not in an editor, press ctrl+n to create one.
4.	Press ctrl+k, m for a language.
5.	Press up/down arrows, or start typing your favorite programming language.

Actual results: Orca only speaks the number of results found. For example, 1 of 59.
Expected results: Orca should speak the language name and the number of results found. For example, Python, 1 of 2.

**Comment by jvesouza** [comment]
When I'm in an editor and I press ctrl + k + m, I only hear the number of languages ​​found.
I press up arrow and down arrow but the orca is silent.
Am I doing something wrong?

**Comment by isidorn** [comment]
The issue here seems to be that the @chrmarti Quick Input does not provide an `accessibilityProvider`  to the list and manually sets it on each element. I believe this can cause to `ariaLabels` not being properly set and potetnially overwritten by the tree.

Thus I have pushed a potential fix for this. I have tried it out on my mac and now I see
@jvesouza can you please verify with vscode insiders tomorrow and let us know if it is now trully fixed for you.
fyi @bpasero since you are jumping on the new quick pick

**Comment by jvesouza** [comment]
I just updated the VSCode and coincidentally the update for this problem is present in this update.
As we say here in Brazil: "show de bola"!
Which means to say that it was excellent. Problem solved.
Congratulations and thank you.

**Comment by isidorn** [comment]
Show de bola it is then :)
Great, adding verified label. Thanks for letting us know it works.

**Comment by ajborka** [comment]
After updating to the newest build 20 minutes ago, I can verify that this bug is now fixed. Thanks for the quick work!
