### ISSUE TITLE
Can't find VS Code in Start Menu

### ISSUE THREAD

**Issue by markrazorx** [microsoft/vscode#92328]
Issue Type: <b>Bug</b>

Can you please share where the .exe file is so I can manually add it to the Start Menu

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

Extensions: none

**Comment by sbatten** [comment]
`C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\Code.exe` is the user install location
