### ISSUE TITLE
1.43 Update brakes again the Serial COM port selection

### ISSUE THREAD

**Issue by AGhost88** [microsoft/vscode#92325]
- VSCode Version: 1.43
- OS Version: Windows 10
- Arduino plugin: 0.2.29

same as issue: #84192  #76538
Steps to Reproduce:

1. update from 1.42.1 to 1.43
2. Try change serial port for arduino project

Does this issue occur when all extensions are disabled?: Without extension serial port selection not available

**Comment by rebornix** [comment]
Please file issues against the arduino extension , thanks!
