### ISSUE TITLE
Icon setting restored

### ISSUE THREAD

**Issue by PinkiePieStyle** [microsoft/vscode#92320]
Issue Type: <b>Bug</b>

After update to "March 2020 (version 1.44)" icons are restored on each start

VS Code version: Code - Insiders 1.44.0-insider (1876b51870e30e9ba8f35dc0dcfaf49a3799a8ef, 2020-03-09T19:46:29.230Z)
OS version: Windows_NT x64 10.0.18363

**Comment by folke** [comment]
Fixed for me in the latest build! b0791e5236f462fbb785e9a00319705607cefb9d

```
Version: 1.44.0-insider
Commit: b0791e5236f462fbb785e9a00319705607cefb9d
Date: 2020-03-10T11:17:54.705Z (1 hr ago)
```
