### ISSUE TITLE
TS symbol search is broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#92338]
* latest 1.44.0 insider 
* open the VS Code project
* use symbol search, it is broken 9 of 10 cases

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1794099/76301018-ea737e80-62bd-11ea-88fc-b248b658ed65.png">

**Comment by jrieken** [comment]
oh, also using 3.9.0-dev.20200304

**Comment by mjbvz** [comment]
Also with TS 3.8.3. I see the server returning the correct info so need to look into what's going on here
