### ISSUE TITLE
Does the vscode not support multi-thread view on debug?

### ISSUE THREAD

**Issue by zxgm** [microsoft/vscode#92330]
Does the vscode not support multi-thread view on debug? The vscode have not the feature on current?

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language and debug extension you are using?

This functionality is supported by VS Code, but extension needs to provide this info to VS Code. [Example for C++](https://code.visualstudio.com/docs/cpp/cpp-debug#_multithreaded-debugging)

**Comment by zxgm** [comment]
Thank you very mush.
