### ISSUE TITLE
Typescript2 @types not being recognized by the compiler (still throwing errors)

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#9233]
- VSCode Version: 1.3.1
- OS Version: Win7

Steps to Reproduce:
1. Install any `@types` that would normally replace a `typings` (let's say `@types/core-js`)
2. TS Errors will be thrown for things such as `require` / `Promise` etc, that shouldn't.

If you manually implement `/// <reference path="node_modules/@types/core-js/index.d.ts" />` on top of a page, the errors will go away for that page. Of course this shouldn't have to be done, `@types` should be globally seen by the compiler.

For example:
![image](https://cloud.githubusercontent.com/assets/2574412/16819608/381ed29e-491b-11e6-91b7-ad8e279d35d9.png)

**Comment by jrieken** [comment]
@MarkPieszak did you configure VS Code to use the latest version of TypeScript (will indicate in the status bar)?

**Comment by reach4thelasers** [comment]
Adding     `"typescript.tsdk": "node_modules/typescript/lib"` to the settings.json fixed this for me

**Comment by MarkPieszak** [comment]
Forgot to respond yes this fixed it for me as well needed to update tdsk to point to TS globally installed. Apologies.

**Comment by anilanar** [comment]
`@types` must be resolved according to the nearest `tsconfig.json` relative to the file. I don't know what `vscode` does right now, but I know that it does wrong. If it's the `tsdk`, then by default `tsdk` should be `./node_modules/typescript/lib` relative to each `tsconfig.json`.
