### ISSUE TITLE
 Disk File Service "after each" hook for "readFile - FILE_TOO_LARGE - streamed"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92334]
Electron unit test failure here https://dev.azure.com/vscode/VSCode/_build/results?buildId=39020&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=08e986c2-058e-5f01-51da-ae4278e2d74e

**Comment by bpasero** [comment]
I added a larger timeout of 10s vs 5s and want to monitor if this helps. As last resort, I can disable this test for operating systems that have a bad file system implementation (Windows).
