### ISSUE TITLE
Latest update to 1.43.0 broke color theme "Atom One Dark"

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode#92335]
- VSCode Version: `1.43.0`
- OS Version: `Win 10 v1909`

Steps to Reproduce:

1. Download & activate theme [Atom One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)
2. Tokens are colorized different then in previous versions
3. In "side by side" diff view, correct colors are shown on the left side (the original):

![2020-03-10_10h25_27](https://user-images.githubusercontent.com/30658772/76299806-fbbb8b80-62bb-11ea-9f05-11c90dd40ce9.png)

Some more observations:
* When activating the theme, it appears "normal" for a moment and changes shortly after
* Same after starting VSCode. The colorization is initially correct and changes once the status message "Initializing JS/TS language features" disappears

![2020-03-10_10h36_02](https://user-images.githubusercontent.com/30658772/76299587-a67f7a00-62bb-11ea-9378-9b60582846a0.gif)

Does this issue occur when all extensions are disabled?: No, since the theme is not loaded then ;)

Also happens in fresh installation of VS Code insider with only `Atom One Dark` extension installed.

**Comment by themeler** [comment]
I've the same problem (Base16 Tomorrow Dark theme). Colors are completly messed up.

**Comment by cuddeford** [comment]
This is also happening for me with Ruby Blue

**Comment by janos-kasa** [comment]
This comment helped me: https://github.com/microsoft/vscode/issues/92308#issuecomment-596885893

Themes need to be updated to support semantic highlighting.

**Comment by cuddeford** [comment]
The workaround worked for me

**Comment by CombeeMike** [comment]
Works for me as well. Am I correct in assuming that the theme maintainer need to update their themes to work with the new semantic highlighting as well?

**Comment by cuddeford** [comment]
> Works for me as well. Am I correct in assuming that the theme maintainer need to update their themes to work with the new semantic highlighting as well?

As far as I can tell, yes. Here's is some reference reading: https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by Whitefox98** [comment]
Same problem

**Comment by rebornix** [comment]
thank you all for feedback, let's track this issue in https://github.com/microsoft/vscode/issues/92308 and for now you can turn off the semantic syntax highlighting feature by changing below setting:

```
"editor.semanticHighlighting.enabled": false
```
