### ISSUE TITLE
While Debugging, Theme is changed

### ISSUE THREAD

**Issue by marcocavanna** [microsoft/vscode#92341]
Issue Type: <b>Bug</b>

Hi,

when running a Debug instance of a NodeApp my Theme will stop working and some keyword are changing color to default (white). This happens only after installed last release

Thanks,

Marco

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|-psn_0_26995133|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
react-nitro-snippets|are|1.0.2
path-intellisense|chr|1.4.2
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-diff|fab|1.4.0
vscode-scss|mrm|0.9.0
vscode-language-pack-it|MS-|1.43.2
mssql|ms-|1.9.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
polacode|pnp|0.3.4
seti-icons|qin|0.1.3
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
blueprint|tea|3.0.0
quokka-vscode|Wal|1.0.282
vscode-todo-highlight|way|1.0.4
vscode-js-console-utils|wht|0.7.0
better-align|wwm|1.1.6

</details>

**Comment by syd619** [comment]
I have a similar issue after the latest update, class names, require, as well as class getters & setters appear in light blue (see screenshots attached).

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

![vscode2](https://user-images.githubusercontent.com/5445023/76310254-1cdda580-62d7-11ea-8c0d-e29d4d731355.PNG)
![vscode](https://user-images.githubusercontent.com/5445023/76310256-1e0ed280-62d7-11ea-9504-fc6170a17fc7.PNG)

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by marcocavanna** [comment]
I found the problem and it's not related to new release, not at all.

It was the Semantic Highlight Settings that is turned on by default.
