### ISSUE TITLE
Windows Explorer shows File type as Visual Studio Code for Files Set to Open with VSCode

### ISSUE THREAD

**Issue by nathanblair** [Microsoft/vscode#9234]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Pro Build 10586.420

Steps to Reproduce:

1. Set VSCode as default application to open with raw text file of yet-unknown file type (e.g. README.md has unknown .md file type; set README.md to Open With VSCode - and default VSCode to open all files of .md file type)
2. View file in Windows Explorer and under "Type" column, shows "Type" as Visual Studio Code.

The file shown should display whatever the file-type/extension is; in the example given above, should display MD File or perhaps even Markdown as file type as it does if set to open with any other text editor like Sublime.

**Comment by joaomoreno** [comment]
#3419
