### ISSUE TITLE
Smoke test failure: checks if 'Go to Line' works if called from the status bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92345]
Smoke test failure

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=69344&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d

**Comment by bpasero** [comment]
Seems to have stabilized.
