### ISSUE TITLE
[json] Wrong resolution of relative path in JSON schema reference

### ISSUE THREAD

**Issue by antonGritsenko** [microsoft/vscode#92348]
- VSCode Version: 1.42.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Create new json schema 
2. Create new json file, reference schema to newly created schema using **file URI** and relative path.

Sample:
D:\test\schema.json
D:\test\my.json
in my.json:
```
{
    "$schema": "file:schema.json"
}
```
Error: _Unable to load schema from '\schema.json': ENOENT: no such file or directory, open 'd:\schema.json'_

The VS Code resolve this to d:\schema.json, so "file:test/schema.json" will work, but none really relative kind of paths will work (like file:../schema.json). 
According [rfc8089](https://tools.ietf.org/html/rfc8089#appendix-E.2.1), relative path must work.

Does this issue occur when all extensions are disabled?: Yes

PS ./ format works fine, so "$schema": "./schema.json" will work. #6974

**Comment by aeschli** [comment]
I'm not sure what `file:schema.json` means. Relative URIs don't have a schema, see https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#URI_references. That's also what the example in [rfc8089](https://tools.ietf.org/html/rfc8089#appendix-E.2.1) shows.

As you mention, `./schema.json` works. No action planed.
