### ISSUE TITLE
Syntax Highlighting for PHP in HTML-Documents

### ISSUE THREAD

**Issue by mazuk6** [microsoft/vscode#92349]
Issue Type: <b>Feature Request</b>

I use .htm/.html documents as templates to have full code-completion and highlighting available in editors. 
PHP-Snippets in the HTML-code arent recognised as PHP. Some simple highlighting would really help.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

![Unbenannt](https://user-images.githubusercontent.com/35265677/76311212-b8b7e300-62d0-11ea-86f0-671138b6f4cb.PNG)

**Comment by aeschli** [comment]
The main language of the file is PHP, not HTML. `<?` is not a valid HTML tag.

-> This need to be provided by PHP, not HTML.

**Comment by roblourens** [comment]
So the file is a .html file? Can you use the `files.associations` setting to map .html files to the php type?

**Comment by mazuk6** [comment]
I clearly see the problem of mixed languages and I can switch to php to get the proper highlighting of the php part, but I loose the completion functionality of the html part.
I just switched from Notepad++ which handles this very smoothly (without the completion anyway). It would be helpful to at least highlight things like <? and $varname and Strings.

Mixed languages are reality out there. There is no such thing like clean HTML. There are always scripts and styles and placeholders like from smary and so on....

**Comment by murraycollingwood** [comment]
> Mixed languages are reality out there. 

I agree, however using <? and ?> doesn't necessarily identify the language.
What happens if you use "<?php" and "?>"  ?  Does that help?

**Comment by mazuk6** [comment]
no, it is not dependend on short or long notation (<? or <?php).
It seems to me that Notepadd++ uses the same definition for HTML and PHP. When I switch Language there is no difference in the highlighting.
