### ISSUE TITLE
Typescript crashing constantly 

### ISSUE THREAD

**Issue by fivepoint-0** [microsoft/vscode#92354]
Issue Type: <b>Bug</b>

Simply creating and modifying typescript project. I initiated a project with 'tsc --init', configured and installed tslint, and also installed express. I cannot get intellisense to work with express apps. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|2.1.1
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.3.11
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
vetur|oct|0.24.0
vscode-yaml|red|0.7.2
ftp-kr|rua|1.3.16
vuetify-vscode|vue|0.2.0
material-theme|zhu|3.2.3

(10 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Maybe try updating to 1.43 which just released.
