### ISSUE TITLE
debugAdapter Package.json does not respect OSType when nesting InitialConfigurations

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#9235]
- VSCode Version: 1.3.1
- OS Version: Ubuntu 16.04, OSX El Capitan

Steps to Reproduce:

we have a block:

```
    "initialConfigurations": [
      {
        "name": "C++ Launch",
        "type": "cppdbg",
        "request": "launch",
        "targetArchitecture": "x64",
        "program": "enter program name, for example ${workspaceRoot}/a.out",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceRoot}",
        "environment": [],
        "externalConsole": true
      }]
```

that we want to override with this block on osx:

"osx": {
           "initialConfigurations": [
              {
                "name": "C++ Launch",
                "type": "cppdbg",
                "request": "launch",
                "targetArchitecture": "x64",
                **"MIMode": "lldb",**
                "program": "enter program name, for example ${workspaceRoot}/a.out",
                "args": [],
                "stopAtEntry": false,
                "cwd": "${workspaceRoot}",
                "environment": [],
                "externalConsole": true
              }]}
on OSX, i'm still getting the top block.

**Comment by weinand** [comment]
@pieandcakes please read section "OS specific launch configurations" of latest release notes: https://code.visualstudio.com/Updates. I'm sure that addresses your issue.

**Comment by pieandcakes** [comment]
My problem with that is that we offer this across Linux and Windows and OSX and it seems to get pretty crowded if we start doing this. If I were a Linux or Windows user i'd probably not care about the OSX default parameters. Is it possible to support it at a higher level such as by specifying different InitialConfigurations based on OS?

**Comment by weinand** [comment]
@pieandcakes yes, we can do this "at a higher level". But for the time being an acceptable solution exists.

**Comment by weinand** [comment]
This can now be done through the dynamic "initialConfigurations" possible via the [`DebugConfigurationProvider.provideDebugConfigurations`](https://github.com/Microsoft/vscode/blob/27e9d4c196fb38edc3a630732dd221c7aaff7634/src/vs/vscode.d.ts#L6086)
