### ISSUE TITLE
Windows OS - Horizontal scroll using trackpad

### ISSUE THREAD

**Issue by ckr1989** [microsoft/vscode#92355]
In Windows settings, trackpad scroll is set to "Natural Scrolling".

In VScode, only vertical scroll works as per this setting, whereas, the horizontal scroll works in opposite direction.

This is not consistent. It should work in any one particular way. Either both vertical and horizontal do a natural scroll or a regular scroll.

This is only with "Two finger" trackpad scroll. VSCode version: 1.42.1

**Comment by alexdima** [comment]
@ckr1989 VS Code is built with Electron, which is built with Chromium. Can you please try to scroll with Chrome? Does that respect the OS settings?

**Comment by ckr1989** [comment]
I checked in chrome browser. Same problem exists in chrome. So, does it mean it's an issue in chromium?

**Comment by alexdima** [comment]
Yes, you can report against Chromium at https://bugs.chromium.org/p/chromium/issues/list
