### ISSUE TITLE
Allow Shift+Delete to remove recently opened entries from quick pick

### ISSUE THREAD

**Issue by thw0rted** [microsoft/vscode#92358]
The "Go To File..." (CTRL+P) menu shows a mix of files that match from the current workspace, other files you've opened recently, and who knows what.  Sometimes these results rank things I don't want (e.g. files with same names from another workspace) higher than the file I'm actually trying to open.  I'd like to be able to "delete" suggestions so they don't appear again in the future.

There are a bunch of features that allow you to use the keyboard to navigate to a recently-opened file, and they all work a little differently.  #15340 is about the "recently opened" picker (cc @bpasero )  and is referenced in #31221.  #34097 is about the "quick open" menu, which I guess is different for some reason? Anyway, that's supposed to be resolved by #30770 but I don't actually want to *never* get history results, I just want to get rid of the ones that bother me the most.

As for implementation, I like the idea mentioned on several of those tickets: if I open a "select file" quick menu of any stripe, I should be able to highlight an entry and remove it with `shift + delete`.

**Comment by bpasero** [comment]
@thw0rted you can do this today already, what is missing?

![image](https://user-images.githubusercontent.com/900690/76388473-8a3a1680-6369-11ea-8ece-18fcdac1c8e1.png)

**Comment by thw0rted** [comment]
I hadn't seen that, thanks.

The original intent of the issue was to point out that the Open Recent picker has a nice "X" button:

![image](https://user-images.githubusercontent.com/943160/76391909-ca50c780-6370-11ea-93be-c62a5a917237.png)

but the Go To File picker does not:

![image](https://user-images.githubusercontent.com/943160/76392055-1ef44280-6371-11ea-8d0d-086ab3d339a8.png)

and neither does Quick Open Recent:

![image](https://user-images.githubusercontent.com/943160/76392038-1865cb00-6371-11ea-9781-dd321b5388ea.png)

It would be nice to see consistent behavior between the 3 very similar file picker menus.  Having to run a separate command to clean up these lists is a convoluted workflow.  It doesn't have to be a keyboard shortcut, I just want to be able to remove the entry I'm looking at from any of those lists.

Actually... I just checked and the third example (Quick Open Recent) doesn't show up in Remove From History, because that command seems to manipulate *file* history, not *workspace* history.  Maybe I should change this ticket title to "Make consistent UX for removing items from quick-pick lists"?

**Comment by bpasero** [comment]
@thw0rted understood, I can see about adding it to quick open.

As for recently opened, that sounds like a bug to me! I do not see that:

![image](https://user-images.githubusercontent.com/900690/76394125-48af6880-6375-11ea-8914-bfe93fa8851e.png)

Do you see that with latest VSCode?

**Comment by thw0rted** [comment]
I had a pending update, on restart I now see the X on `Open Recent...`.  That gets it down to one (`Go To File...`) but unfortunately that's the one I actually use all the time.

**Comment by thw0rted** [comment]
Thanks @bpasero .  Just to double check, is "quick pick" the panel you get with CTRL+P?  Ideally this behavior would work everywhere, but that's the one that's most important to me personally.

**Comment by bpasero** [comment]
Yes. It would probably work in pickers that allow to remove entries (not all do).
