### ISSUE TITLE
[json] Problems loading reference with schema service

### ISSUE THREAD

**Issue by folke** [microsoft/vscode#92353]
- VSCode Version: 1.44.0-insider
- OS Version: Darwin x64 19.3.0
```
Version: 1.44.0-insider
Commit: b0791e5236f462fbb785e9a00319705607cefb9d
Date: 2020-03-10T11:17:54.705Z (1 hr ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

Steps to Reproduce:

1. Open any `package.json` or `tsconfig.json` file
2. The schema will fail loading with the following error:

> Problems loading reference 'schemaservice://combinedschema/schemas/package.schema.json': Unable to load schema from 'schemaservice://combinedschema/schemas/package.schema.json': Request vscode/content failed with message: cannot open schemaservice://combinedschema/schemas/package.schema.json. Detail: resource is not available.

Does this issue occur when all extensions are disabled?: **Yes**

**Edit:** I'm not using a proxy

**Comment by surajmandalcell** [comment]
+1 Same
OS: Windows 10 x64

**Comment by DaCurse** [comment]
Same issue happens to me, same error message, not using a proxy, Windows 10 64 bit

**Comment by yoshiotobe** [comment]
I'm having the same issue.
After installing Nuxt.js, all json file get the error message inside the nuxt directory.
However, outside the nuxt directory, it does not happen.
Nuxt seems to be working fine but I'm not sure if I have to fix this problem or just ignore it.
It's a bit annoying to see the error message.

・Host OS: Windows 10
・Guest OS: Ubuntu 18.04 (Vagrant)
・VSCode: 1.44.0-insider
・Usage: SSH into Ubuntu

Similar issues are below.
・[Less distracting error message for JSON schema resolution issues](https://github.com/microsoft/vscode/pull/60219)
・[Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': connect ECONNREFUSED](https://github.com/Microsoft/vscode/issues/65728)

**Comment by surajmandalcell** [comment]
Can confirm it gets fixed after switching to previous point release. Its bugged for current release only.

**Comment by afflexux** [comment]
Still present in the latest release for me.

```
Version: 1.44.0-insider
Commit: ef75c4bb445e5021065cf0012cfa2c66e55bfa16
Date: 2020-03-11T09:09:04.033Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by xpyxel** [comment]
Hope this is fixed soon, it's quite an annoyance.

**Comment by matepek** [comment]
Hello,

I'm not sure it is related, but heres my problem:
`{ "$ref": "file:///<absolute_path>/defs.json#/definitions/someprop"  }` works.
`{ "$ref": "defs.json#/definitions/someprop"  }` doesn't work.

It is in the `package.json` and and the `defs.json` is next to it.

If I merge `defs.json` to `package.json` and try `{ "$ref": "#/definitions/someprop"  }` 
then I get the following error:
```
$ref '/definitions/someprop' in 'vscode://schemas/settings/folder' can not be resolved.
```

Shall I open a new issue or will it be resolved with this?
