### ISSUE TITLE
VSCode randomly closes

### ISSUE THREAD

**Issue by moritzwilksch** [microsoft/vscode#92356]
Issue Type: <b>Bug</b>

At random times, when working with jupyter notebook or the interactive Python window, VSCode just quits. This also happens, when the window is just open in the background.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|2.0.1
bracket-pair-colorizer-2|Coe|0.0.29
gitlens|eam|10.2.1
nasc-touchbar|fel|1.12.0
python|ms-|2020.2.64397
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.6
material-theme|zhu|3.2.3

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@moritzwilksch when do you start to see this problem? Do you see the same issue if you have  all extensions disabled?

**Comment by moritzwilksch** [comment]
Issue only started with the February Update 1.43.0. Before the update VSC was stable.
I'll try to disable all extension (except for the python one), but since I can't specifically reproduce the issue it might take some time to check. VSC just quits at random in the background (most of the times) or even while using (only a few times until now)

**Comment by deepak1556** [comment]
@moritzwilksch I see you also commented on https://github.com/microsoft/vscode/issues/92420 ,  I would like track this issue in one common place, please provide updates there. Thanks!
