### ISSUE TITLE
The "Problems, Output, Debug Console, Terminal" panel needs to be minimize-able to a tabstrip or something

### ISSUE THREAD

**Issue by StingyJack** [microsoft/vscode#92363]
When I'm typing it eats up screen real estate. I just need it minimized then. 

If I start to debug, then I will need it restored. When I stop debugging, it should return to its pre-debugging state.

**Comment by sbatten** [comment]
@StingyJack the panel can be hidden by clicking the `X` button on the top right or using the command `Toggle Panel`. Additionally there is a setting: `debug.console.closeOnEnd` for closing the debug console automatically when you are done debugging.
