### ISSUE TITLE
[Mitagated] Screenshots of VSCode in Windows 10 with HDR are washed out

### ISSUE THREAD

**Issue by seanthegeek** [microsoft/vscode#92365]
Note: This is not related to issues #68069  #88491 #92361 

When taking screenshots of HDR apps and games in Windows 10, including, but not limited to other Electron apps (i.e. this is also a problem when taking screenshots or streaming DirectX games with HDR) like Microsoft Teams, the colors are washed out.

[Example screenshot](https://imgur.com/a/ZZ1oZqX)

As a result, you need to turn off HDR in Windows 10 to get an accurate screenshot of Visual Studio Code.

This Windows 10 HDR screenshot bug is [almost three years old now](https://steamcommunity.com/app/589360/discussions/0/1726450077632091930/). It would be great is you could work with the Windows team to finally fix it.

**Comment by deepak1556** [comment]
@seanthegeek how does it look with chrome beta release https://www.google.com/chrome/beta/?platform=win64 ?

**Comment by seanthegeek** [comment]
Same issue with Chrome Beta. Since this also happens in games, I think this is a Windows bug, rather than a Chrome/chromium/Electron bug like the other HDR problems.

![image](https://user-images.githubusercontent.com/44679/76374666-3d7b1f00-631a-11ea-825a-cdecdb4cb94d.png)

![image](https://user-images.githubusercontent.com/44679/76374786-8af78c00-631a-11ea-8e51-473e59dede27.png)

**Comment by deepak1556** [comment]
Thanks for testing! I can't speak for the windows bug, but the steam client you are referring also has chromium components, I wouldn't be surprised if its affected by it.

There seems to be an upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=964759 for this issue, I would suggest to follow that and also mention the issue you are facing.

I will leave this bug open to avoid duplicate issues in future.

**Comment by seanthegeek** [comment]
@deepak1556 There is no issue with the Steam client. The forum thread just happens to be on the Steam fourm because lots of gamers talk there. It's a bug when trying to take a screeenshot of anything with HDR support enabled, so it's probably Windows bug. Check out this screenshot of Forza Horizon 4, a Microsoft UWP game in the Microsoft Store (not Steam) when HDR is enabled:

![image](https://user-images.githubusercontent.com/44679/76430271-836dcc80-6386-11ea-956b-58599aebcbe6.png)

**Comment by deepak1556** [comment]
Thanks @seanthegeek but there is nothing VS Code can do at this point, I am leaving this issue open to track progress on the above chromium issue.

**Comment by seanthegeek** [comment]
@deepak1556 It turns out, setting `"force-color-profile": "srgb"` in `argv.json` instead of changing `disable-color-correct-rendering` in `argv.json` fixes the rendering completely, including with screenshots. 😄

**Comment by deepak1556** [comment]
I am merging this to https://github.com/microsoft/vscode/issues/88491 , thanks for the update!
