### ISSUE TITLE
Flutter Daemon has terminated 

### ISSUE THREAD

**Issue by vasavi730** [microsoft/vscode#92367]
Issue Type: <b>Bug</b>

I'm getting the errors as
1) The Flutter Daemon has terminated
2)THe Dart Analyzer could not be started
Can you help me in fixing this problem

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G    (2 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.8.0
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
adb-interface-vscode|vin|0.14.0

</details>

**Comment by rebornix** [comment]
Please file issues against the Flutter extension you are using, thanks!
