### ISSUE TITLE
Commit warning covers the button "Stage all changes"

### ISSUE THREAD

**Issue by ChayMartis** [microsoft/vscode#92362]
Issue Type: <b>Bug</b>

Minor visual issue:
- Long commit message warning box covers the button "Stage all changes".

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
As soon as you focus away from the input box, you can click the button.
