### ISSUE TITLE
Remote WSL messing with themes highlight

### ISSUE THREAD

**Issue by Azeveco** [microsoft/vscode#92364]
- VSCode Version: 1.43
- Extension Version: 0.42.3
- OS Version: Windows 10 Home SIngle Language - Build 1903

Theme syntax highlightning not working properly with Remote-WSL extension.

Steps to Reproduce:

1. Install Remote WSL extension and reload
2. Open a new remote wsl window
3. Create a new .js file and fill it with some content
4. Bring up the command pallet (F1) and search for "Color Theme"
5. Go up or down and watch the highlight works perfectly for just a second and then turning into something else

Does this issue occur when all extensions are disabled?: No, because the extension that's causing this is the WSL. I've deactivated all the extensions and reloaded, only left the Remote-WSL active and the problem was still there. When I deactivated Remote-WSL, eveything worked perfectly.

I recorded a small video showing this behaviour with Remote-WSL enabled and another one with Remote-WSL disabled. Take a closer look at require, req, res and module.exports.
VIdeo: https://drive.google.com/open?id=1hr2QI2ZtPO3efsQYOoyh4uXUQtez0Y8A

**Comment by MatiasOlivera** [comment]
Maybe this will help you: https://github.com/microsoft/vscode/issues/92308#issuecomment-596885893

**Comment by Azeveco** [comment]
> Maybe this will help you: [#92308 (comment)](https://github.com/microsoft/vscode/issues/92308#issuecomment-596885893)

That's it! Thank you, @MatiasOlivera !
