### ISSUE TITLE
A better rating system for extensions

### ISSUE THREAD

**Issue by wwmyers** [microsoft/vscode#92377]
I think I've figured out a better way to rate someone's extension in VSCode.

Problem:
I feel like just displaying an install count with a star rating isn't very accurate in VSCode. Most seem to just uninstall the extension if they don't like it instead of rating it. Many that do rate it are probably just friends helping out. I've seen extensions with several thousands of installs with very few ratings, if any at all. Also with very few ratings, if even just 1 user finds a bug that's yet to be fixed, and gives it a poor rating, that can ruin that extension. Another thing, with more installs, that extension gets more popular for next to no reason if many users aren't even using it. That can easily be manipulated with the info page making it sound better than it may actually be. To me, that's kind of deceiving.

Solution:
Instead of using just an install count with a star rating, use an install count with a percentage of users that still have that extension in their list. In my opinion that's a much more accurate rating towards how many people actually like that extension. Most aren't going to want to keep an extension on their list cluttering it up with what they don't want or dislike. Can still keep the star rating, but I think a percentage of users actively still using can be very useful in knowing how great it might actually be.

**Comment by sandy081** [comment]
@fiveisprime FYI

**Comment by isidorn** [comment]
Opened upstream issue https://github.com/microsoft/vsmarketplace/issues/150

**Comment by isidorn** [comment]
Upstream issue is tracking this. Thus closing this one
