### ISSUE TITLE
everything looks wierd

### ISSUE THREAD

**Issue by arg9244** [microsoft/vscode#92379]
Issue Type: <b>Bug</b>

https://imgur.com/FdosNjq
it happened after the update
when vscode is in background happens but not in foreground
im using latest windows 10 and latest nvidia driver

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (13.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.16
material-icon-theme|PKi|4.0.1
vscodeintellicode|Vis|1.2.6
material-theme|zhu|3.2.3

</details>

**Comment by deepak1556** [comment]
@arg9244 How does it look when you disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration ?

**Comment by arg9244** [comment]
that fixed it
thank you

**Comment by deepak1556** [comment]
Thanks for confirming, closing as no further action can be taken from VS Code at the moment, might want to check with the flag removed in future releases.
