### ISSUE TITLE
Moving the cursor stops working 5 seconds after startup

### ISSUE THREAD

**Issue by tukiato1** [microsoft/vscode#92376]
Issue Type: <b>Bug</b>

1) Open a .cs file with the editor 
2) Wait 5 seconds
3) Try to move the cursor with arrow keys (or emacs shortcuts)

NOTE: my intellisense is also broken after the VSCode update.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.57GB free)|
|Process Argv|C:/omat/Projects/bowling-mobile -g C:\omat\Projects\bowling-mobile\Assets\Scripts\BallRTTService.cs:26:18|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.14
center-editor-window|kai|2.3.0
vscode-emacs-friendly|lfs|0.9.0
csharp|ms-|1.21.13
python|ms-|2020.2.64397
remote-wsl|ms-|0.42.3

</details>

**Comment by rebornix** [comment]
@tukiato1 do you see the same issue with all extensions disabled?
