### ISSUE TITLE
File icons keeps resetting to seTi

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#92374]
Issue Type: <b>Bug</b>

Every time I startup vscode insiders the file icons are reset back to the SETi icon theme. This behavoir is also present when disabling all extensions.

VS Code version: Code - Insiders 1.44.0-insider (1876b51870e30e9ba8f35dc0dcfaf49a3799a8ef, 2020-03-09T20:10:25.732Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 1799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 7, 7|
|Memory (System)|62.63GB (50.98GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
numbered-bookmarks|ale|7.0.0
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
compulim-vscode-closetag|Com|1.2.0
vscode-markdownlint|Dav|0.34.0
xml|Dot|2.5.0
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
git-project-manager|fel|1.7.1
todo-tree|Gru|0.0.169
CppSnippets|har|0.0.14
vscode-test-explorer|hbe|2.17.0
vscode-github|Kni|0.30.3
restructuredtext|lex|120.0.0
vscode-remark|mrm|1.2.0
vscode-docker|ms-|1.0.0
vscode-ros|ms-|0.6.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.64397
remote-containers|ms-|0.107.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
cmake-tools|ms-|1.3.1
cpptools|ms-|0.26.3
autodocstring|njp|0.4.0
vscode-singularity|onn|0.5.0
ros-snippets|pij|0.3.1
material-icon-theme|PKi|4.0.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.7.2
rescuetime|Res|1.0.1
bash-debug|rog|0.3.7
code-spell-checker|str|1.8.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.6
vim|vsc|1.13.0
gitmoji-vscode|Vtr|0.1.8
highlight-trailing-white-spaces|yba|0.0.2
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

**Comment by rickstaa** [comment]
Thanks! The problem appear to be fixed in the last insider release:

**Version:** 1.44.0-insider
**Commit:** eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc
**Date:** 2020-03-11T05:33:48.554Z
**Electron:** 7.1.11
**Chrome:** 78.0.3904.130
**Node.js:** 12.8.1
**V8:** 7.8.279.23-electron.0
**OS:** Linux x64 5.3.0-40-generic

**Comment by aeschli** [comment]
This got fixed by https://github.com/microsoft/vscode/commit/9f802b22fc57c39ff6bd2c2878a1cb3e668c4e3f
