### ISSUE TITLE
Allow sync storage locations other than web

### ISSUE THREAD

**Issue by maxrothman** [microsoft/vscode#92370]
Web sync storage backends might be the right solution for many users, but they're inflexible and won't work for everyone. For example, users who work in internet-restricted environments, or whose configs contain sensitive or proprietary information (e.g. in build tasks) won't be able to use public sync backends, and the companies they work for might not be willing to dedicate the time to running a central sync backend server.

A simple solution would be to allow for non-web sync backends: initially it should be possible to sync your settings to a local directory, and eventually maybe ssh, sftp, etc could be supported (though those features could potentially be provided by extensions).

Many other dev tools such as Alfred and iTerm2 allow users to save their settings to a custom location, this would be similar. This approach would put the power in the hands of the user to build sync solutions that work the way they need them to.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/92357

**Comment by maxrothman** [comment]
@sandy081 I don't understand how this is a duplicate of #92357. All of the discussion in #92357 is around custom backend servers, whereas this issue is suggesting a settings sync option that uses no backend at all. Solving #92357 requires establishing a generalized protocol with which VSCode can communicate with arbitrary backend servers, solving this issue requires teaching the Settings Sync feature how to talk to filesystems.

**Comment by sandy081** [comment]
A backend can be anything.. it can be a remote server or on local disk. #92357 is allowing to support a custom backend which can be a server on web or local disk. Hence marked as dup.
