### ISSUE TITLE
"Add folder to workspace" prompt duplicates itself if you add and then remove a folder from the workspace repeatedly 

### ISSUE THREAD

**Issue by RM-Eric** [microsoft/vscode#92381]
- VSCode Version: 1.43.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Add a folder to the workspace
2. Remove the folder from the workspace, so that there are no folders in the workspace.
3. Add another folder to the workspace
4. Remove that folder from the workspace
5. Repeat 

![image](https://user-images.githubusercontent.com/59585041/76336139-9075b780-62c3-11ea-84cd-d787c7809103.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@RM-Eric good catch. Thanks for filling this!
