### ISSUE TITLE
Cannot use keyboard arrows on terminal/bash on windows

### ISSUE THREAD

**Issue by ricardosantos9521** [Microsoft/vscode#9238]
- VSCode Version: all
- OS Version: all with bash
Steps to Reproduce:

1. Using the tutorial to run bash on code
2. Cannot use arrows from keyboard on bash on code.

Thanks please add this feature.

**Comment by Tyriar** [comment]
Can you provide a little more information? What do you expect it do to? Also the version information is very important, you can have this auto-filled by opening an issue through VS Code's Help > Report Issues menu.

**Comment by jakubsuchybio** [comment]
When you type something in bash in vscode on windows, you can't navigate left/right.
When you use 'nano' you can't navigate via arrows.
When you want to use last command, you can't arrow up does nothing.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10163
