### ISSUE TITLE
SearchEditor does not respect  `search.useIgnoreFiles`

### ISSUE THREAD

**Issue by petekinnecom** [microsoft/vscode#92384]
- VSCode Version: 1.44.0 (built on master branch)
- Commit: f618e507fbeec9bc23e1a04cae63e767fb601b2d
- OS Version: Darwin x64 19.2.0

Steps to Reproduce:

1. Add `thing.txt` to `.ignore` file
1. `echo searchquery >> thing.txt`
1. Set `"search.useIgnoreFiles": false` in `settings.json`
2. Open a search editor
3. Search for a `searchquery`
4. No results found
5. Search for `searchquery` using sidebar
6. Result found

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
@roblourens how is "search.useIgnoreFiles" supposed to interact with the "Use Exclude Settings and Ignore Files" option?

**Comment by roblourens** [comment]
The `disregardIgnoreFiles` option is `boolean | undefined`, so only set it if you want to override the setting.
