### ISSUE TITLE
Lost ability to scroll through content in panel

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#92387]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Show the output panel.
2. Depending on the output length, try to scroll from the top to the end.
3. The scroll bar goes right off the edge when using a mouse, or can not scroll at all if clicking somewhere and using arrow keys (mainly when the content is long enough to be in the hidden area, but short enough to not need scrolling).

![output_panel_1](https://user-images.githubusercontent.com/1007463/76339942-07a54e80-62b8-11ea-8e3d-5135151d9cde.gif)

VS Code version: Code - Insiders 1.44.0-insider (b0791e5236f462fbb785e9a00319705607cefb9d, 2020-03-10T11:23:10.498Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.1
vscode-icon-theme|jtl|1.6.5
material-theme|zhu|3.2.3

</details>

**Comment by rebornix** [comment]
I'm seeing the same issue in Search View in Panel.

**Comment by eamodio** [comment]
I'm seeing the same as well.

**Comment by eamodio** [comment]
Fix looks good!

**Comment by sbatten** [comment]
To Verify:
1. Open output and select a channel with a lot of content (has a scrollbar).
2. Try to scroll all the way to the bottom.
3. Ensure scrollbar stops at the bottom and all content is reachable.
