### ISSUE TITLE
Jupyter code cell folding feature request

### ISSUE THREAD

**Issue by jordan-schneider** [microsoft/vscode#92389]
When you have a python file with jupyter code cells (using `# %%`), it would be nice if I could fold individual cells, like I can fold functions.

![2020-03-10-125037_612x111_scrot](https://user-images.githubusercontent.com/1740270/76343380-054def00-62ce-11ea-9877-b89c12ec4410.png)

**Comment by jordan-schneider** [comment]
Oh this is a vscode-python issue isn't it?

**Comment by rebornix** [comment]
Please file issue against Python extension which provides this feature, thanks!
