### ISSUE TITLE
Themes Syntax Color Issue: "editor.semanticHighlighting.enabled" (Release v1.43.0)

### ISSUE THREAD

**Issue by webdevnerdstuff** [microsoft/vscode#92390]
VSCode Version: 1.43.0

This new setting `editor.semanticHighlighting.enabled` should be set to **false** as the default.

It's going to break a lot of peoples color schemes and cause headaches for people who have themes in the VSCode Marketplace. Not everybody is going to read through support Issues to figure this out.

For anybody having the issue, add this to your settings.
```
"editor.semanticHighlighting.enabled": false
```

**Comment by Joe-Pena** [comment]
Thank you! I was wondering why suddenly every theme except the default ones were broken.
