### ISSUE TITLE
Version in package.json incorrect at tag 1.43.0

### ISSUE THREAD

**Issue by slokhorst** [microsoft/vscode#92403]
Looking at `package.json` at the 1.43.0 tag, it says `"version": "1.44.0"`: https://github.com/microsoft/vscode/blob/1.43.0/package.json

I think this is the cause of some version mismatch error I am getting during runtime.

Note that for the e.g. [1.42.0](https://github.com/microsoft/vscode/blob/1.42.0/package.json) and [1.41.0](https://github.com/microsoft/vscode/blob/1.41.0/package.json) tags, the versions do match.

**Comment by Tyriar** [comment]
Good find, not sure what happened there.

**Comment by Tyriar** [comment]
Fixed, thanks.
