### ISSUE TITLE
Emojis in Integrated Terminal Do Not Display Correctly

### ISSUE THREAD

**Issue by joeparislbcc** [microsoft/vscode#92409]
Issue Type: <b>Bug</b>

Even after the update to VS Code 1.43.0 using Unicode 11 some emoji do not display correctly.

## Steps to Reproduce:

1. Write code that will output text containing emoji
1. Run the code, outputting to the integrated terminal
1. Note the broken wide characters

## Sample Code (Python)

```python
#! /usr/bin/env python3.8
print("🦄😉👍❤️")
```
## Expected Results

(screenshots taken from Windows Terminal 0.9.433.0)

### PowerShell 7.0

![pwsh-expected](https://user-images.githubusercontent.com/7649433/76369720-adc17a80-62f1-11ea-813c-5a7feec604e1.png)

### WSL

![wsl-expected](https://user-images.githubusercontent.com/7649433/76369716-a4d0a900-62f1-11ea-8008-8cd09b8eb646.png)

## Actual Results 

(screenshots taken from VS Code 1.43)

### PowerShell

![pwsh-actual](https://user-images.githubusercontent.com/7649433/76369743-c6ca2b80-62f1-11ea-90f4-569eb63dc7e7.png)

### WSL

![wsl-actual](https://user-images.githubusercontent.com/7649433/76369748-cdf13980-62f1-11ea-9cb9-4932866673d0.png)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.6.1
vscode-markdownlint|Dav|0.34.0
vscode-quick-select|dba|0.2.8
vscode-pandoc|Dou|0.0.8
gitlens|eam|10.2.1
code-runner|for|0.9.16
docker-explorer|for|0.1.7
vscode-codeql|Git|1.0.6
latex-workshop|Jam|8.7.2
vscode-hacker-typer|jev|0.1.1
theme-dark-plus-contrast|k3a|0.1.101
theme-monokai-pro-vscode|mon|1.1.15
vscode-docker|ms-|1.0.0
python|ms-|2020.4.67210-dev
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
cpptools|ms-|0.26.3
powershell|ms-|2020.3.0
vsliveshare|ms-|1.0.1742
autodocstring|njp|0.4.0
printcode|nob|3.0.0
material-icon-theme|PKi|4.0.1
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.6.0
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.8.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
material-theme|zhu|3.2.3

(8 theme extensions excluded)

</details>

**Comment by ThaddeusJiang** [comment]
MacOS has same issue 
<img width="664" alt="Screen Shot 2020-03-11 at 12 42 12" src="https://user-images.githubusercontent.com/17308201/76380515-54f7ed80-6396-11ea-8045-4e09a4c2414b.png">

expect:
 ♻️Refactoring

**Comment by Tyriar** [comment]
For Windows this is a known issue as conpty is emitting something different to nix ptys, this is currently tracked in https://github.com/xtermjs/xterm.js/issues/2693 /duplicate

@ThaddeusJiang for mac I believe it's a font config issue
