### ISSUE TITLE
Debug viewlet panes out of order and imporperly rendered

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#92405]
Notice the breakpoints pane is untitled. Ran into this while debugging a node app using the debugger terminal @connor4312 

![image](https://user-images.githubusercontent.com/8586769/76364209-dc375980-62e1-11ea-8431-6f5c2b0d5808.png)

**Comment by connor4312** [comment]
We saw this before when the welcome view was initially added. I don't think we ever got a consistent repro, does it happen reliably for you?

cc @isidorn

**Comment by JacksonKearl** [comment]
No, I think @eamodio ran in to this as well in the timeline pane and the issue was the one pane gets added first and gets the viewlet stuck in the single pane mode. But it doesn't reliably repro. I've only seen it the one time and I'm not quite sure how I got there.

**Comment by connor4312** [comment]
Oh, okay. Maybe it's not specific to the debug view then and adding the welcome view just triggered the same behavior somehow.

**Comment by sbatten** [comment]
@JacksonKearl Are you still in the state? Can you get more info about what views are "supposedly" visible by right-clicking the header of the viewlet?
