### ISSUE TITLE
Default terminal powershell doesn't respect folder casing

### ISSUE THREAD

**Issue by Luciden** [microsoft/vscode#92406]
When I open the integrated powershell terminal the casing for the folders is always lowercase even though my foldernames have mixed cases. This causes an error in npm run build in certain situations, e.g. having a VueJs folder based project within a DotNet core project. 

Default: PS D:\projects\repos\...
What it should be: PS D:\Projects\Repos\...

**Comment by Tyriar** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/2193314/78565400-badb6780-77d2-11ea-8692-20a8a14bd5dc.png)
