### ISSUE TITLE
Update 1.43 Italic imports and theme not recognizing function names TypeScript

### ISSUE THREAD

**Issue by jmadelaine** [microsoft/vscode#92407]
After updating to VS Code v1.43 (macOS Mojave v10.14.6) all of my default imports are now displayed in italics and the color is wrong.

For example, if I import using destructing, the imports are not italicized, and imported functions are displayed correctly in blue (my theme's function color).

For example:

```javascript
import styled from '@emotion/styled'

const Tab = styled(Flex)({
```

The default import `styled` is now italicized, and when I call `styled(...)` the word styled is white (default text color) instead of indicating that `styled` is a function.

Prior to the update, the default import `styled` was not italicized and when I called `styled(...)`, the word `styled` was in the correct text color for a function using my theme.

I understand that my theme may need to be updated to apply the new text color, but why does it need to be updated in the first place? Why is a default import no longer recognized as a function by my theme?

Why has font-style (italics) been forced on everyone by default?

**Comment by jmadelaine** [comment]
Okay so this looks like it is caused by the new semantic highlighting functionality. Most themes don't support it yet, so you can disable it in settings with `"editor.semanticHighlighting.enabled": false`.

**Comment by wKich** [comment]
@jmadelaine, thanks a lot for figure out why highlighting is changing on opening vscode. I spent few hours to try understand why my code goes to ugly highlighting.

**Comment by aeschli** [comment]
The semantic highlighter finds our that `styled` is a function, so the default import is highlighted as a function. That's the point of semantic highlighting
But why the second 'styled' is not classified as a function is a bug that I have to investigate.

No changes are required to themes (or even possible) for supporting semantic highlighting.

**Comment by jecsham** [comment]
Omg lot of thanks @jmadelaine 
This new feature is really very nice, but sadly, my theme dont support it :s

**Comment by aeschli** [comment]
With semantic highlighting, the second `styled` is now classified as a function.
Since 1.43.1 imports are all the same color (no longer show the type of the symbol)
