### ISSUE TITLE
Migrate viewlet-level progress indication to view-level

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#92400]
Refs: #92135

Now that we can support view-level progress indication, there doesn't seem like much reason to have viewlet-level progress.

This can also address the concerns here: https://github.com/microsoft/vscode/pull/92136#pullrequestreview-371744519

/cc @bpasero @sbatten

**Comment by bpasero** [comment]
@eamodio I guess one problem is that extensions can still use API to report progress on the viewlet container right? I forgot about that when I suggested this, so we may not easily be able to remove this.

**Comment by eamodio** [comment]
Yeah, we won't be able to remove it, but we *could* deprecate it to encourage view-level use.

I've added an API proposal here for extensions: https://github.com/microsoft/vscode/issues/92421

**Comment by eamodio** [comment]
Since we really only expose `ProgressLocation.SourceControl` (and it is kind of special), I don't think its worth doing anything here.
