### ISSUE TITLE
Color theme bug

### ISSUE THREAD

**Issue by peckas13** [microsoft/vscode#92419]
Since yesterday I experiment a bug that makes the editor be unable to take the font color properly and the text turn almost as the same color and hard to read.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have a screenshot?

What language are you using? If it's JS/TS then please check if its same as #92308

**Comment by peckas13** [comment]
> 
> 
> /needsMoreInfo
> 
> Do you have a screenshot?
> 
> What language are you using? If it's JS/TS then please check if its same as #92308

Yes i´m using JS and TS and is the same issue as you send me

**Comment by aeschli** [comment]
Duplicate of #92308.
