### ISSUE TITLE
i cant run my program!

### ISSUE THREAD

**Issue by isaiah218s** [microsoft/vscode#92411]
Issue Type: <b>Performance Issue</b>

My name is Isaiah Thompson im 16 and from Detroit Michigan and i want to be a Machines Engineer and i wanted to learn how to program and your pc application is very helpful on giving a coding playground,but i cant run the small programs that i make. I'm not sure if it's because i'm using a school computer that owned by my schools,school district or i'm didn't set up a compilier properly or i didn't get the right compilier.I really need your help thank you so much.I now this a report issue but I hope so one and not a automated system reades this.

**Comment by JacksonKearl** [comment]
Hey Isaiah, what language are you using?
