### ISSUE TITLE
sometimes does not recognize venv in python

### ISSUE THREAD

**Issue by leandroluk** [microsoft/vscode#92416]
Issue Type: <b>Bug</b>

sometimes, when i install a new library or pull the project in git, vscode does not recognize these changes and says that the code is invalid or that the library is not found in the virtual environment. yes, i am activating virtualenv using the command "python3 -m venv venv" and then "source ./venv/bin/activate" to then install the requirements and any other library and even then, every time there are changes I have to select another different pythonpath and then go back to venv

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|-psn_0_45067|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
env-vscode|Ber|0.1.1
vscode-eslint|dba|2.1.1
vscode-test-explorer|hbe|2.17.0
golang-tdd|joa|0.0.9
vscode-python-test-adapter|lit|0.3.17
MagicPython|mag|1.1.0
vscode-docker|ms-|1.0.0
python|ms-|2020.2.64397
Go|ms-|0.13.1
appidocsnippets|mya|0.1.20
vscode-yaml|red|0.7.2
vscode-sort-json|ric|1.18.0
vscode-scss-formatter|sib|1.4.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
json|Zai|1.0.4

</details>

**Comment by rebornix** [comment]
Please file issue against Python extension, thanks!
