### ISSUE TITLE
VS Code Terminal Bug

### ISSUE THREAD

**Issue by CQBoyBrand** [microsoft/vscode#92415]
Issue Type: <b>Bug</b>

Input method input characters in Chinese state, and then switch to English or multiple identical characters appear。

![](https://imgchr.com/i/8kmb34)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.37
vetur|oct|0.24.0
vue-helper|she|2.2.3
open-in-browser|tec|2.0.0

</details>

**Comment by CQBoyBrand** [comment]
like this
[![8kmb34.gif](https://s2.ax1x.com/2020/03/11/8kmb34.gif)](https://imgchr.com/i/8kmb34)

**Comment by Tyriar** [comment]
The terminal acts the same as the editor from my testing just now.

**Comment by rebornix** [comment]
This behavior is controlled by the IME being used.

**Comment by CQBoyBrand** [comment]
> This behavior is controlled by the IME being used.

The Mac's built-in Chinese input method
