### ISSUE TITLE
[less] color info missing

### ISSUE THREAD

**Issue by lanten** [microsoft/vscode#92417]
- VSCode Version: 1.43.0
- OS Version: macOS 10.15.3

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/16203518/76378258-f6c40e00-6387-11ea-9753-10dc155a2d30.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by KennanChan** [comment]
Same issue after updating to 1.43.0

**Comment by rickstaa** [comment]
I experience the same issue in:

Version: 1.44.0-insider
Commit: ef75c4bb445e5021065cf0012cfa2c66e55bfa16
Date: 2020-03-11T09:19:54.444Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic

**Comment by octref** [comment]
@aeschli Does this have anything to do with the recent change in less?

**Comment by aeschli** [comment]
caused by https://github.com/microsoft/vscode-css-languageservice/commit/5dc5edb81f61ce2745213591af6608fb967e19ef

**Comment by aeschli** [comment]
PR created, @octref to review (and merge, if ok)

**Comment by aeschli** [comment]
To verify open a 'less' file with content `@var: #112233;` and check that there's a color decorator
