### ISSUE TITLE
JS Intellisense not working in "with" statement

### ISSUE THREAD

**Issue by younggeun0** [microsoft/vscode#92413]
Hi, I found JS intellisense issue when I use 'with' statement.
Please check this out.

- VSCode Version: 1.43.0
- OS Version: Windows10

Steps to Reproduce:

1. make some simple.js file and type 'with' statement codes like below 
```javascript
with(__some_namespace__) {
  document.
}
```

2. press ctrl+space next to "document." for built-in JS intellisense, but it dosen't work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Our IntelliSense engine does not support `with` statements as they are not widely used in code and are recommended against (https://github.com/microsoft/TypeScript/issues/10601)

You can see this by enabling semantic checking in the JS file: just a `// @ts-check` comment to the top of it. This will show an error on the `with` statement:

<img width="1001" alt="Screen Shot 2020-03-16 at 8 21 16 PM" src="https://user-images.githubusercontent.com/12821956/76818772-b3243680-67c3-11ea-90ff-09d6e0113e41.png">
