### ISSUE TITLE
cannot scroll down debug console

### ISSUE THREAD

**Issue by sandyman96** [microsoft/vscode#92428]
Issue Type: <b>Bug</b>

1. create a node app.js file. 
2.create many console.log() commands to will the debugger console.
3.press F5 to run as debugger.
4. The debugger window wil not scroll, even though there are texts beneath it.

VS Code version: Code - Insiders 1.44.0-insider (b0791e5236f462fbb785e9a00319705607cefb9d, 2020-03-10T11:34:00.960Z)
OS version: Linux x64 4.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3442)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.51GB (1.92GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
bracket-pair-colorizer-2|Coe|0.0.29
prettier-vscode|esb|3.20.0
vscode-docker|ms-|1.0.0
indent-rainbow|ode|7.4.0
vscodeintellicode|Vis|1.2.6

</details>

**Comment by borgdylan** [comment]
Encountered the same issue on the insiders build.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/92430
fyi @sbatten
