### ISSUE TITLE
python doc string underscore

### ISSUE THREAD

**Issue by germayneng** [microsoft/vscode#92429]
Currently any arguments with _ will result in a backslash:

I am following the format of the numpy doc string: 

![Screenshot 2020-03-11 at 2 08 13 PM (2)](https://user-images.githubusercontent.com/22788747/76387489-07817d80-63a2-11ea-8132-00aa95dcb200.png)

cant seem to find any solution to this! Thanks

**Comment by alexr00** [comment]
@germayneng does this reproduce if you disable all extensions?
Can you please provide a copy/pastable example?

**Comment by germayneng** [comment]
Here is a simple example

`
def test(x_arg,y_arg):
    '''
    Parameters
    ----------
        x_arg: first argument 
        y_arg: second argument
    '''

    return x_arg*y_arg
`

**Comment by alexr00** [comment]
If I disable the python extension then there is no hover. This is an issue with one of the extension.
