### ISSUE TITLE
Unable to save the file, possible of loosing data

### ISSUE THREAD

**Issue by b00f** [microsoft/vscode#92426]
vscode is unable to save the files. It can't be easily reproduced and looks happens randomly.
Specially when the user enabled 'auto save'.
This bug has been reported by users frequently. However the vscode team claims that this is extensions issue. Even an extension have internal bug, it shouldn't affect saving file.

You can find similar bugs here:
https://github.com/microsoft/vscode/search?q=%22Running+Save+Participants%22&type=Code

Is there any way to find out which extension has this bug, at least we can find a workaround for that.

**VSCode Version:** 
- Version: 1.42.1
- Commit: c47d83b293181d9be64f27ff093689e8e7aed054
- Date: 2020-02-17T09:32:31.598Z
- Electron: 6.1.9
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Linux x64 5.4.24-1-lts

Does this issue occur when all extensions are disabled?: 
No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by b00f** [comment]
> Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code),

Yesterday I tried running vscode without any extensions. At least during my work I didn't see this issue, However without extensions vscode is only a text editor, So I enabled it almost after an hour. One more thing I noticed. In some cases after this error I am not able to close vscode. I need to kill the instance manually. Looks something is running in background.

**Comment by b00f** [comment]
Is it possible to put some logs here to find out which promis is not returning:

https://github.com/microsoft/vscode/blob/8b955610988d28cf98ae316dc1a3d44f599a358f/src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts#L51

**Comment by bpasero** [comment]
@jrieken save participant it seems

**Comment by jrieken** [comment]
> Is there any way to find out which extension has this bug, at least we can find a workaround for that.

Yes - have you reported this against 1.42.1. In later versions the extension name/id is part of the progress message

**Comment by b00f** [comment]
Closing and ignoring issues is part of Microsoft culture!
