### ISSUE TITLE
Bug Report: Scroll stops working in Output Window

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#92425]
Version: 1.44.0-insider (user setup)
Commit: b0791e5236f462fbb785e9a00319705607cefb9d
Date: 2020-03-10T11:23:10.498Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. From the command-line, launch vscode insider's build with `code-insiders --disable-extensions`
2. Maximize the VS Code window.
3. Run the command, `Output: Focus on Output View`
4. Resize the Output Window to take up 1/2 screen height.
5. Change the Output View to `Log (Extension Host)` (this should have some default output)
6. Reduce the size of the Output View so that it needs to be scrolled.

Does this issue occur when all extensions are disabled?: Yes

Expected Behavior:
* Should scroll

Actual Behavior
* Does not scroll

---

Sometimes the scroll will work at first. If it does, try launching with the Window maximized, repeat the steps, then minimize the window. Also try resizing the output window, switching focus to another window, and coming back. Eventually the scroll feature will stop working.

Using the developer tools, and comparing to a non-insider's build, I can see in `Developer Tools` elements explorer that the div at `document.querySelector("#workbench\\.panel\\.output > div > div > div.split-view-container > div > div > div.pane-body")` is not updating in height with the `code-insiders` build, but it is updating in height with `code`.

**Comment by mattacosta** [comment]
Probably a duplicate of #92387.

@smcenlly Can you try the latest insiders? It should be fixed now.

**Comment by smcenlly** [comment]
@mattacosta - everything is working now. Thanks.
