### ISSUE TITLE
Show wrong branch name in status bar on startup

### ISSUE THREAD

**Issue by borishere** [microsoft/vscode#92431]
1. Switch to branch other than 'master'.
2. Start VSCode.
3. You will see 'master' branch in status bar, it will be changed only when you open some file.
![Screenshot_6](https://user-images.githubusercontent.com/4622497/76389390-2836dc80-637c-11ea-812e-feb159734870.png)

Issue Type: <b>Bug</b>

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
pascal|ale|9.0.0
pascal-formatter|ale|2.2.0
vscode-toggle-quotes|Bri|0.3.2
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.1
vscode-faker|dee|1.3.0
vscode-npm-script|eg2|0.3.11
output-colorizer|IBM|0.1.2
innosetup|idl|1.2.0
nsis|idl|3.25.1
vscode-placeholder-images|Jak|0.1.0
HTMLHint|mka|0.6.0
vscode-filesize|mkx|2.1.3
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
incrementor|nms|0.1.0
LiveServer|rit|5.6.1
vscode-qt-for-python|sea|0.4.2
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
vscode-stylelint|sty|0.83.0
open-in-browser|tec|2.0.0
material-theme|zhu|3.2.3

</details>

**Comment by joaomoreno** [comment]
You seem to have multiple repositories open, maybe it's showing that it's in the `master` branch of another repository? That would explain it would change once you open a file.

**Comment by borishere** [comment]
@joaomoreno Yes, I confirm it. I have a repo inside another repo and at start it shows 'master' branch of another repo even if the opened file at start is from non-master branch of another repo.

**Comment by borishere** [comment]
Looks like it shows the first or main repo of a workspace.

**Comment by borishere** [comment]
@joaomoreno  Fixed or?

**Comment by joaomoreno** [comment]
The status bar will only show the branch name of one of your open repositories. By default it will take the first one. It will then switch if you open files inside other repositories or interact with them in the SCM view.

**Comment by borishere** [comment]
Why not take the repository of the file opened with VS Code start.
