### ISSUE TITLE
Add recent search strings to Search

### ISSUE THREAD

**Issue by KevinGrealish** [microsoft/vscode#92435]
Issue Type: <b>Feature Request</b>

When using search (ctrl-shift-F) there is no recnt searched for strings so to search for the prior value I searched for I have to retyp it. All other tools I use have a drop-down or auto-complete that offers recent search strings. Please also provide this.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:46:03.121Z)
OS version: Windows_NT ia32 10.0.18363

**Comment by IllusionMH** [comment]
You already can access history in Find in files and Find (in editor) with <kbd>Alt</kbd>+<kbd>↑</kbd>/ <kbd>↓</kbd> (however usually simple <kbd>↑</kbd> and <kbd>↓</kbd> works)
No dropdown though
