### ISSUE TITLE
Remote SSH cannot be used

### ISSUE THREAD

**Issue by Regzanate** [microsoft/vscode#92439]
Issue Type: <b>Bug</b>

I was able to connect via SSH normally before updating to the latest version, but after updating I was unable to connect.
This is output to the log.

Stopped parsing output early.Remaining text: OpenSSH_7.9p1, OpenSSL 1.1.1a 20 Nov 2018Can't open user config file "C: \\ Users \\\ xxx \ xxx \ xxx \ xxx \ xxx \ xxx \ xxx \ xxx \ xxx \ xxx \ xxx \ xxx \\. ssh \\ config ": No such file or directory

"xxx" is number.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363
Fetching remote diagnostics for 'SSH' failed.

**Comment by sanket-bhalerao** [comment]
@Regzanate  can you try to downgrade "Remote - SSH" extension version to 0.49.0?

**Comment by Regzanate** [comment]
@sanket-bhalerao It was available after downgrading. Thank you.

**Comment by sanket-bhalerao** [comment]
great :)

**Comment by roblourens** [comment]
You can also upgrade again and use these settings:

```
"remote.SSH.useLocalServer": false,
"remote.SSH.windowsRemotes": ["<your remote hostname>"] // only if the remote is Windows
```
