### ISSUE TITLE
SCM View does not span available hight

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92430]
Seeing this running out of sources on macOS:

![image](https://user-images.githubusercontent.com/900690/76389018-adb19100-636a-11ea-864b-98464645098c.png)

**Comment by bpasero** [comment]
Also in insiders from today.

**Comment by eamodio** [comment]
I think this issue with the SCM message box is related too
![image](https://user-images.githubusercontent.com/641685/76389249-3a475980-6341-11ea-9ba4-b7fad6ac3261.png)

**Comment by eamodio** [comment]
Related: https://github.com/microsoft/vscode/issues/92387

**Comment by sanket-bhalerao** [comment]
there are blank areas in the extension viewlet as well. is this related to same issue?
![image](https://user-images.githubusercontent.com/9264813/76389862-4c051d00-6392-11ea-8b17-ae81f641b315.png)

**Comment by mattacosta** [comment]
The explorer view is also chopped off.

![exporer_view](https://user-images.githubusercontent.com/1007463/76396770-0d8e4480-6337-11ea-9961-0851b4de5569.png)

**Comment by sandy081** [comment]
Caused by #92387. 

Fixed.

**Comment by sbatten** [comment]
To Verify:
1. Open SCM viewlet with no other views inside the SCM viewlet.
2. Select the changes tree view and verify that the focus border spans all the way to the bottom of the viewlet.
