### ISSUE TITLE
Explorer don't display full size at vertical

### ISSUE THREAD

**Issue by feidianbo** [microsoft/vscode#92442]
Issue Type: <b>Bug</b>

The left explorer don't display full size at vertical, whever how to resize.

VS Code version: Code - Insiders 1.44.0-insider (eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc, 2020-03-11T05:33:39.535Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.11.0
ng-template|Ang|0.900.15
aurelia|Aur|1.0.5
path-intellisense|chr|1.4.2
ng-alain-extension-pack|cip|7.1.0
ng-alain-vscode|cip|7.0.0
ng-zorro-vscode|cip|8.3.2
angular-schematics|cyr|3.3.0
markdown-table-prettify|dar|2.4.0
prettier-vscode|esb|3.20.0
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
angular2-switcher|inf|0.3.2
docthis|joe|0.7.1
git-graph|mhu|1.21.0
vs-deploy|mkl|14.0.0
vs-rest-api|mkl|3.0.1
vscode-docker|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.1.0
remote-wsl|ms-|0.42.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-versionlens|pfl|0.25.0
quicktype|qui|12.0.46
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
move-ts|str|1.12.0
vscode-todo-highlight|way|1.0.4
vscode-httpie|wk-|0.0.3

</details>

**Comment by dagi3d** [comment]
+1
seems to happen in all the containers inside the side bar
![screenshot](https://i.imgur.com/AzpHrAZ.png)

**Comment by IllusionMH** [comment]
/duplicate

Thanks @sanket-bhalerao
