### ISSUE TITLE
All recently opened files are opened at the same time when I start code

### ISSUE THREAD

**Issue by clshu** [microsoft/vscode#92444]
I just updated vscode today  2020/03/10. vscode behaved differently. It opened all the recently oped files at the same time. It created many windows. I cleared recently opened file from File -> Open Recent -> Clear Recently Open but it still opened a lot of files. After a while, it seems to be back to normal. I want to keep the list of recently opened files but only open when I clicked on it. Not be opened automatically.

**Comment by gjsjohnmurray** [comment]
Were you previously on 1.42 or on an earlier version? I am asking because 1.42 changed the default for the `window.restoreWindows` setting, so maybe this is causing what you are seeing.

**Comment by bpasero** [comment]
Either that or duplicate of https://github.com/microsoft/vscode/issues/92318.
