### ISSUE TITLE
Text color show incorrect after last update.

### ISSUE THREAD

**Issue by boypro2007vn** [microsoft/vscode#92447]
Some text color show incorrect after last update.
https://imgur.com/a/jH51pVX

**Comment by mattacosta** [comment]
Duplicate of #92308.

Assuming that `isNullOrUndefinedOrEmpty` is a function, then this is just the semantic highlighter doing its thing. You can turn it off using: `"editor.semanticHighlighting.enabled": false`.

**Comment by aeschli** [comment]
Duplicate of #92308.
