### ISSUE TITLE
Replace All Does not work

### ISSUE THREAD

**Issue by yj7** [microsoft/vscode#92443]
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Search for a string in the sidebar
2. Open the search in the search editor
3. Change the sidebar from search to search and replace
4. Enter the replace string
5. Replace all does not work

Does this issue occur when all extensions are disabled?: Yes

**Comment by MythicalFish** [comment]
I'm having the same issue on Mac.
Clicking "Replace all" opens up the new Search Editor, but with none of the results replaced.
I'm able to edit the results but I can't save or apply.

**Comment by eladcandroid** [comment]
Same issue... Version 1.43.0, OS: Darwin x64 19.3.0

**Comment by smuuf** [comment]
Same issue, OS Win10 Insiders 19577, working with project inside WSL via Remote-WSL.

![a](https://user-images.githubusercontent.com/6860713/76563723-439f0600-64a8-11ea-8d27-ddc351b7cf2b.gif)

_Replace All_ doesn't replace anything.

**Comment by ringcrl** [comment]
> Same issue, OS Win10 Insiders 19577, working with project inside WSL via Remote-WSL.
> 
> ![a](https://user-images.githubusercontent.com/6860713/76563723-439f0600-64a8-11ea-8d27-ddc351b7cf2b.gif)
> 
> _Replace All_ doesn't replace anything.

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

Same issue

**Comment by roblourens** [comment]
This works for me. Any idea @JacksonKearl?

Are there any errors in the devtools console? (Help > Toggle Developer Tools)

**Comment by JacksonKearl** [comment]
I am able to reproduce. Opening the search editor seems to get it into a strange state that isn't resolved until a full reload.

**Comment by roblourens** [comment]
I see it. Thanks @JacksonKearl

**Comment by PerpetualWar** [comment]
same problem here.... after last update, it does nothing, regardless of keyboard shortcut or UI button.

**Comment by eladcandroid** [comment]
@JacksonKearl 
You closed all the duplicate issues and the bug still exists...

**Comment by smuuf** [comment]
Is this maybe fixed in 1.43.1? I don't see this in [list of closed issues](https://github.com/Microsoft/vscode/issues?q=is:issue+milestone:%22February+2020+Recovery%22+is:closed).🤔

**Comment by eladcandroid** [comment]
@smuuf  Nope...

**Comment by JacksonKearl** [comment]
The bug is fixed in insiders. It was not in the recovery build. It will be in the next stable build.
