### ISSUE TITLE
"Run" doesn't have a quick shortkey in the menu

### ISSUE THREAD

**Issue by MaledongGit** [microsoft/vscode#92441]
Issue Type: <b>Bug</b>

For "Run" in the menu of VS Code, there's only a "&", where is the letter "R"? Maybe it should look something like "运行(R)"?

PS: Just this is found in the Chinese version, not sure whether English or other versions have this problem or not.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:37:31.640Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.15GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
vscode-language-pack-zh-hans|MS-|1.43.2
python|ms-|2020.2.64397
vscode-icons|vsc|10.0.0
</details>

Please notice the yellow words in the menu in the following graphic:

-----
![Err](https://user-images.githubusercontent.com/52018749/76393953-9943b780-63af-11ea-995d-769ce28c1b7a.PNG)

**Comment by janbaltus** [comment]
Same as https://github.com/microsoft/vscode/issues/92313

**Comment by janbaltus** [comment]
Will be fixed in 1.44 LP
