### ISSUE TITLE
Highlighted areas next to lines of code that aren't selected

### ISSUE THREAD

**Issue by Devjacky** [microsoft/vscode#92449]
Issue Type: <b>Bug</b>
![pic 1](https://user-images.githubusercontent.com/13607101/76398004-728d7d00-63bf-11ea-82e6-f7f2c8c086c0.png)
![pic 2](https://user-images.githubusercontent.com/13607101/76398016-76210400-63bf-11ea-8c17-295eedb7a933.png)

Regardless of file type and color theme, there are highlighted areas next to lines of code that aren't currently selected. When I move my cursor to the lines where the highlighted areas exist, the highlighted areas get pushed up/down.
I've run the uninstaller as well as deleting the Appdata folders containing my settings and extensions. Even after doing a clean install and trying the insiders version, I still have this issue.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rebornix** [comment]
Can you try to run VS Code by disabling gpu optimization `code --disable-gpu` and see if you still run into this issue?

**Comment by Devjacky** [comment]
That worked! Is there a way to make disabling gpu optimization the default value within vscode, or will I have to keep using that command?

**Comment by rebornix** [comment]
You can turn if off by setting `disable-hardware-acceleration` to `true`, thanks!
