### ISSUE TITLE
Search results window doesn't fill all awailable space in sidebar

### ISSUE THREAD

**Issue by alexander-zolotykh** [microsoft/vscode#92451]
Issue Type: <b>Bug</b>

See video https://take.ms/sT9Nf and https://take.ms/XWZYO

VS Code version: Code - Insiders 1.44.0-insider (eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc, 2020-03-11T05:31:25.663Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_4170746|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-eslint|dba|2.1.1
vscode-dash|dee|2.3.0
githistory|don|0.6.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|3.20.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
vscode-back-forward-button|gri|0.1.2
todo-tree|Gru|0.0.169
beautify|Hoo|1.5.0
vscode-jetbrains-keybindings|isu|0.1.9
vscode-edit-csv|jan|0.2.6
vscode-styled-components|jpo|0.0.28
intellij-idea-keybindings|k--|0.2.37
rainbow-csv|mec|1.6.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.0.0
python|ms-|2020.2.64397
Go|ms-|0.13.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
vscode-jest|Ort|3.1.1
vscode-graphql|Pri|0.2.2
project-snippets|reb|0.5.0
vscode-yaml|red|0.7.2
colored-console-log|reh|1.0.7
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.1
multi-command|ryu|1.4.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
vscode-npm-scripts|tra|0.2.1
vscodeintellicode|Vis|1.2.6
gitblame|wad|3.2.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0
local-history|xyz|1.8.1
markdown-all-in-one|yzh|2.7.0
material-theme|zhu|3.2.3

(8 theme extensions excluded)

</details>

**Comment by phihakan** [comment]
I noticed that the height grows when change the width to be greater,  and gets smaller(height) when you make it the width smaller

**Comment by alexander-zolotykh** [comment]
@phihakan like this https://take.ms/XWZYO?

**Comment by phihakan** [comment]
> @phihakan like this https://take.ms/XWZYO?

Yes, I think the height is equal to the width of the component. probably a small mess up in the styling

**Comment by Frix-x** [comment]
I can confirm that I get the same behavior on VSCode Insiders. It looks to be caused by https://github.com/microsoft/vscode/issues/92387 and was fixed a couple hours ago.

Version: 1.44.0-insider (user setup)
Commit: eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc
Date: 2020-03-11T05:33:39.535Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
