### ISSUE TITLE
VSCode abnormal while saving

### ISSUE THREAD

**Issue by luthfikw** [microsoft/vscode#92454]
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. After do update, 5 min vscode close unexpected
2. Then i running again (look like normal)
2. Then open existing file (in my case golang file)
2. Saving with CTRL+S or via menu

here video https://youtu.be/Z3e6PWXLS_c

**Comment by bangroot** [comment]
I have a similar issue saving `java` files. Where the interface hangs trying to get Code Actions. I had to revert to 1.42.1.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by luthfikw** [comment]
@bpasero i've been check it, and saving going well

**Comment by bpasero** [comment]
@luthfikw can you pin point which extension is causing this?

**Comment by jrieken** [comment]
@luthfikw Can you try to disable code actions running during save via `editor.codeActionsOnSave`. The go-extension is know for being super slow when it participates in saves and that likely causes this.

**Comment by luthfikw** [comment]
> @luthfikw Can you try to disable code actions running during save via `editor.codeActionsOnSave`. The go-extension is know for being super slow when it participates in saves and that likely causes this.

still happening, this my setting:

```
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
        }
    },
```

**Comment by luthfikw** [comment]
> @luthfikw can you pin point which extension is causing this?

i can't identify that, but i can lists my enable extensions

this the list:
- alefragnani.bookmarks
- coenraads.bracket-pair-colorizer
- mihelcic.colored-regions
- mikestead.dotenv
- editorconfig.editorconfig
- ms-vscode.go
- aleksandra.go-group-imports
- pkief.material-icon-theme
- arcticicestudio.nord-visual-studio-code
- zhuangtongfa.material-theme
- fabiospampinato.vscode-projects-plus
- foxundermoon.shell-format
- gearintellix.vscode-sqml
- gruntfuggly.todo-tree
- shardulm94.trailing-spaces
- zxh404.vscode-proto3
- redhat.vscode-yaml

**Comment by jrieken** [comment]
Than also disable format on save. And read the progress message that will appear on the lower right of your screen. It names the operation (formatting, code actions) and the extension that's performing it

**Comment by luthfikw** [comment]
> Than also disable format on save. And read the progress message that will appear on the lower right of your screen. It names the operation (formatting, code actions) and the extension that's performing it

on old version, it appear
not to latest version

**Comment by luthfikw** [comment]
i've been found extension that trouble maker, that `aleksandra.go-group-imports`
but on vscode self, i think having bug too

see this: https://youtu.be/RFsqW0aZ2lk
