### ISSUE TITLE
Missing keyboard shortcuts in command palette

### ISSUE THREAD

**Issue by krainboltgreene** [microsoft/vscode#92455]
Issue Type: <b>Bug</b>

Many of the cursor/selection commands seem to be missing from the command palette but have shortcuts.

<img width="654" alt="Screen Shot 2020-03-11 at 2 00 38 AM" src="https://user-images.githubusercontent.com/334809/76401020-7b8a3a00-633e-11ea-8fda-2ecc93962d9d.png">
<img width="607" alt="Screen Shot 2020-03-11 at 2 04 22 AM" src="https://user-images.githubusercontent.com/334809/76401022-7cbb6700-633e-11ea-9186-cc632b0ec163.png">
<img width="658" alt="Screen Shot 2020-03-11 at 2 19 09 AM" src="https://user-images.githubusercontent.com/334809/76401191-c0ae6c00-633e-11ea-96b0-37bdca0abf7b.png">
<img width="608" alt="Screen Shot 2020-03-11 at 2 18 57 AM" src="https://user-images.githubusercontent.com/334809/76401188-bee4a880-633e-11ea-932d-e30cb36d4c38.png">

This might actually be a feature, but some of the ones I've checked are shortcuts.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.40GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.0
vscode-eslint|dba|2.1.1
fontsize-shortcuts|fos|1.5.0
cloudcode|goo|1.2.0
elixir-ls|Jak|0.2.25
vscode-docker|ms-|1.0.0
atom-keybindings|ms-|3.0.6
debugger-for-chrome|msj|4.12.6
change-case|wma|1.0.0

</details>

**Comment by alexdima** [comment]
There are many editor commands not shown in the command palette.

IMHO it is difficult to strike a good balance between discoverability and sheer overload. You can discover more keybindings and commands in the keybindings editor (Ctrl+K Ctrl+S) by scrolling down:
![image](https://user-images.githubusercontent.com/5047891/76509203-ef683780-644f-11ea-935c-ade51e4f10a4.png)

I will not add the cursor movements commands to the command palette.

**Comment by bpasero** [comment]
For reference, quick access (the new quick open) get's the editor actions from:

https://github.com/microsoft/vscode/blob/630ad91cdbd5ab707aebeb2a9906dcbabb5a5d29/src/vs/editor/contrib/quickAccess/commandsQuickAccess.ts#L39

via `getSupportedActions`.

**Comment by alexdima** [comment]
@bpasero :+1: My point is I don't want to bring all editor commands to the command palette, not because it is difficult, but because it is not helpful to have cursor left, cursor left select, etc. in the command palette.

**Comment by bpasero** [comment]
@alexdima yeah understood, makes sense like it is 👍

**Comment by krainboltgreene** [comment]
I see this as a usability mistake. Here you have a fantastic interface for finding out what the editor can do (and what shortcut triggers it) in a way that literally every modern editor has made available and vscode is the only one to take this stance it looks like.
