### ISSUE TITLE
Remote SSH uses hostname instead of username

### ISSUE THREAD

**Issue by FIAPT** [microsoft/vscode#92459]
- VSCode Version: 1.43.0
- OS Client: Windows 10
- Remote: Ubuntu

When upgrading to Remote-SSH Extension Version 0.50.0 from Version 0.49.0 the Extension uses username of the host instead of username of the remote for connecting to remote.

**Comment by sanket-bhalerao** [comment]
possible duplicate of #92439

**Comment by FIAPT** [comment]
Additional comment and possible temporary fix: The ssh connection still works after switching the extension back to version 0.49.0

**Comment by blarzHernandez** [comment]
I just downgraded it too 0.49.0 and it worked. Thanks

**Comment by roblourens** [comment]
Dupe of https://github.com/microsoft/vscode-remote-release/issues/2512
