### ISSUE TITLE
Main window margin

### ISSUE THREAD

**Issue by nikdiklic** [microsoft/vscode#92460]
Issue Type: <b>Bug</b>

Upon updating to 1.43.0, The main window seems a bit off.
The title bar is pushed up and left, and there are black margins on the bottom and right sides. 
Please see the screenshot here: https://imgur.com/a/USMPpe4

![screenshot](https://i.imgur.com/TGgzv8G.png)

Thanks

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|1.5.0
es7-react-js-snippets|dsz|2.6.1
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0

</details>

**Comment by IllusionMH** [comment]
Wonder if workaround proposed in https://github.com/microsoft/vscode/issues/85592#issuecomment-596416698 helps here

**Comment by nikdiklic** [comment]
Yes, it fixes the margins. 
Thanks

**Comment by deepak1556** [comment]
Thanks @IllusionMH 

@nikdiklic can describe the steps that led to this issue on your display, if it is the same as https://github.com/microsoft/vscode/issues/85592 I would like to merge the issue and track there, Thanks!
