### ISSUE TITLE
Failed to install Visual Studio Code update.

### ISSUE THREAD

**Issue by AnthonyB955** [microsoft/vscode#92461]
While checking and installing updates for Visual Studio Code on a Microsoft Windows 10 Version 1909 (OS Build 18636.719), vscode icon disappears and updates do not complete and throw an error with this message:

"Updates may fail due to anti-virus software and/or runaway processes.  Please try restarting your machine before attempting to update again."

I've checked all this and everything is good. What I noticed was that the path to the actual executable file (Code.exe) is located in the underscore sub-folder and not in the parent Microsoft VS Code folder (i.e, "C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\_\Code.exe" ).

The target location is set to (i.e, "C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe") and not (i.e, "C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\_\Code.exe"). I have include a screenshot for your convenience.  

Thank you.

![2020-03-10_16-23-50](https://user-images.githubusercontent.com/60510954/76407430-b782c680-6361-11ea-93ec-3259d785e4e2.png)

**Comment by Golfdriver97** [comment]
I have found a way around it: I delete the files in the default location MS puts VS Code in, and reinstall the program.
Since there are no longer any files, I can then choose the install location. I choose a completely different location and VS Code installs and launches.

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by Golfdriver97** [comment]
I have disabled all updates for VS Code. I didn't do so through Powershell, but the settings in VS Code, turning off my router before I launched the program.

**Comment by joaomoreno** [comment]
@AnthonyB955 Let me know how it goes.

**Comment by ofadieiev** [comment]
I have this issue. I think it is because VSCode is launched and stays in the memory, and update happens in background:
![image](https://user-images.githubusercontent.com/49716172/78889185-ddd47880-7a6b-11ea-8b25-34f9cede3f7b.png)

**Comment by joaomoreno** [comment]
@AnthonyB955 Did it get better?

@ofadieiev Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by ofadieiev** [comment]
@joaomoreno I'm ready to live with the problem :) But if you need to check reproducibility I can disable.

**Comment by AnthonyB955** [comment]
It happened again, this morning.  There was a newer version of VSCODE from 1.44.0 to 1.44.1.  I had to go to the site and download the latest version and install it.  I didn't use the user install. I used the system install so the application is stored in the Program Files directory. It never can locate the VSCODE.exe.  I have disabled Windows background updates.  I'll see what that does for the next update.  Thank you.

**Comment by ofadieiev** [comment]
Is it closed by mistake?

**Comment by AnthonyB955** [comment]
I believe he could have been.  I didn't close it.

**Comment by ofadieiev** [comment]
@joaomoreno Hi! Is the issue solved with some patch?

**Comment by ksharda** [comment]
[vscode-inno-updater-1590872248.log](https://github.com/microsoft/vscode/files/4706492/vscode-inno-updater-1590872248.log)

Hi guys,
Facing the same issue again and again while trying to update VS Code. I have attached the log file. Can you please tell me what is wrong?
