### ISSUE TITLE
WebView width is too low

### ISSUE THREAD

**Issue by SharakPL** [microsoft/vscode#92462]
WebView width is limited to 780px.
![obraz](https://user-images.githubusercontent.com/5007456/76405552-95506f00-6388-11ea-9c33-a821819f49de.png)

It shrinks all images included what makes them barely readable. What's the point of this limit? It should be set to either 100% or more reasonable 1200px, but would be best to manage it through settings.json. 

- VSCode Version: 1.43
- OS Version: Windows 10

Steps to Reproduce:

1. Check any extension page including images in VSCode or hit _Help -> Release notes_

Does this issue occur when all extensions are disabled?: Yes and with all themes

**Comment by mjbvz** [comment]
Very long lines of text are not readable

You can view the web release notes (or the ones on GitHub) if you want a different layout

**Comment by SharakPL** [comment]
@mjbvz seriously? Someone having problems with **reading lines longer than 780px** is the reason for this!? Do you even realise how ridiculous it is? And what exact;ly is a design problem here that it can't be managed by user settings like almost everything else?

**Comment by mjbvz** [comment]
You are welcome to submit a PR that makes images larger (while keeping the max text line length the same). However even the images should likely have a max width. See GitHub how GitHub and many other sites render readmes

**Comment by SharakPL** [comment]
My point exactly! GitHub's limit for content width is 882px and I believe it was also like that for VSCode few versions ago. Why it was lowered to 780px is inexplicable.

**Comment by mjbvz** [comment]
It is now 100px wider :)

**Comment by SharakPL** [comment]
@mjbvz Baby steps 😛 I'd rather make it 1200px or 100%, but I doubt it would be approved. Maybe someday it will be managed through settings for everyone's content...

Thanks
