### ISSUE TITLE
Left sidebar panes are not scaling correctly

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#92463]
Issue Type: <b>Bug</b>

The results of a `search in file` search (linux: ctrl + shift + F)` are not rendered correctly. The results field doesn't use all possible space (See gif). Behaviour also appears with all extensions disabled.

![search panel not maximized](https://user-images.githubusercontent.com/17570430/76410127-b8cae800-638f-11ea-8158-a4eb34091260.gif)

VS Code version: Code - Insiders 1.44.0-insider (eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc, 2020-03-11T05:33:48.554Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|62.63GB (45.05GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
numbered-bookmarks|ale|7.0.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.34.0
githistory|don|0.6.2
xml|Dot|2.5.0
gitlens|eam|10.2.1
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
git-project-manager|fel|1.7.1
todo-tree|Gru|0.0.169
restructuredtext|lex|120.0.0
vscode-ros|ms-|0.6.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.64397
cpptools|ms-|0.27.0-insiders2
autodocstring|njp|0.4.0
ros-snippets|pij|0.3.1
material-icon-theme|PKi|4.0.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.7.2
rescuetime|Res|1.0.1
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
vim|vsc|1.13.0
highlight-trailing-white-spaces|yba|0.0.2
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

#### Updates:
- As pointed out by @furai it appears to affect all panes.

**Comment by furai** [comment]
I'm getting same issue but with all the panes in on the left. They are all cutting off midway. Seems like the height of the pane with search/files is set to whatever is the current width of the pane right now.

**Comment by rickstaa** [comment]
@furai Ah thanks a lot for pointing that out. I didn't notice the other panes being off. I updated the title.

**Comment by furai** [comment]
Actually it has been fixed for me in the latest insiders that has been just pushed out.

**Comment by rickstaa** [comment]
Fixed in v1.44.0-insider commit ef75c4bb445e5021065cf0012cfa2c66e55bfa16.
