### ISSUE TITLE
Folder tab does not expand to full height in the explorer sidebar

### ISSUE THREAD

**Issue by sirdmon** [microsoft/vscode#92475]
**Specification:**

Version: 1.44.0-insider
Commit: eb4ebee6a3310df8ff5f36f78f209c2658cfcdfc
Date: 2020-03-11T05:33:48.554Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.10.0-42-generic snap
**Steps to Reproduce:**

1.Launch VSCode
2.Open a folder that contains many sub-folders and files.

**Expected behavior:**
Folder tab in the explorer sidebar expands to full available height and then it shows a scrollbar to reach deeper sub-folders.

**Current behavior:**
Folder tab doesn't expand to full available height. Instead, it seems to be limited to a fixed height.

![image](https://user-images.githubusercontent.com/32838302/76414766-427eb380-6398-11ea-97b5-b18a6ae94009.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by nityanandagohain** [comment]
Facing the same problem

**Comment by cb-li** [comment]
Same issue. Also happens with list of extensions:

![image](https://user-images.githubusercontent.com/41158110/76427061-2422b300-63ac-11ea-8a5a-8caea5904a13.png)

**Comment by EmilianoTalamo** [comment]
Same, here. Quite annoying.

![image](https://user-images.githubusercontent.com/12476222/76438881-575c4680-639a-11ea-9180-f02c19c63845.png)

![image](https://user-images.githubusercontent.com/12476222/76438928-680cbc80-639a-11ea-9ed4-63c9b0e91dac.png)

**Comment by umyesi** [comment]
same problem :(

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/92430
fyi @sbatten
