### ISSUE TITLE
Regression: Command 'Search: Find in Files' no longer respects search.searchOnType

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#92477]
Steps to Reproduce:

1. Select some text
2. Run the command `Search: Find in Files`
3. The Search side bar opens, with the selected text entered into the search field, but it does not automatically updated the search results even if `search.searchOnType: true`

This worked before 1.43.0.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/duplicate

Improvements tracked in #91901

See #91691 and #90962 for details
