### ISSUE TITLE
Minimap shows like static and sometimes out of place

### ISSUE THREAD

**Issue by MooseTheCoder** [microsoft/vscode#92470]
- VSCode Version: 1.43
- OS Version: Ubuntu 18.04.4 LTS

![MapIssue](https://user-images.githubusercontent.com/16779909/76412832-3f7dc600-638c-11ea-8c22-6624a2cf9f26.png)

Steps to Reproduce:

1. Open a file with a large Minimap
2. Lock the computer w/ `Ctrl+L` 
3. Wait a short time
4. Unlock the machine to Vscode

At this point, the Minimap will display like static (see attached screenshot), and sometimes will render completely out of place (again, see attached screenshot).

Navigating through the minimap does not fix this but switching files does

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Can you please try opening https://jsfiddle.net/o35uvkLn/ in Chromium and doing the same sleep/resume steps?

**Comment by MooseTheCoder** [comment]
Just gave it a shot and it kept working as it should. Vscode however done the same thing again

**Comment by alexdima** [comment]
@deepak1556 This might be an electron only issue ... Any advice?

**Comment by deepak1556** [comment]
I am unable to repro on Ubuntu 18.04 parallels vm, I tried the steps from the original post. 

@MooseTheCoder can you try loading the gist https://gist.github.com/51a9d6e639906b3333d8edff1143ab17 in electron-fiddle https://github.com/electron/fiddle/releases/tag/v0.13.1

Please try electron versions `7.1.11` and `8.2.0`

Also can you give the following VS Code exploration build a try https://az764295.vo.msecnd.net/exploration/2766badcb6c29445f5289033f1343f373802315c/code-exploration-1585360520.tar.gz that comes with chrome 80.
