### ISSUE TITLE
trimmed end whitespace when create new file

### ISSUE THREAD

**Issue by HikaruEgashira** [microsoft/vscode#92473]
## specification

```
Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041
```

## current

![image](https://user-images.githubusercontent.com/39324739/76413211-5d711800-63d8-11ea-964f-41484b4f9ae9.png)
type: `mian.yml `←exist whitespace

![image](https://user-images.githubusercontent.com/39324739/76413227-6661e980-63d8-11ea-925f-8bc548a72831.png)
filename: `main.yml `←exist whitespace

## expect

![image](https://user-images.githubusercontent.com/39324739/76413349-9ad5a580-63d8-11ea-8a4b-cbacd34fa008.png)
filename: `main.yml`←no whitespace

It because `touch main.yml `←exist whitespace
to be `main.yml`←no whitespace

**Comment by HikaruEgashira** [comment]
I checked and my issue did not match above issues.

**Comment by IllusionMH** [comment]
Trimming was intentionally reverted in #12013

However there will be warning after PR for #91187 will be merged.

**Comment by HikaruEgashira** [comment]
thanks! :+1:
