### ISSUE TITLE
Interface hangs after any file update.

### ISSUE THREAD

**Issue by miguelmello** [microsoft/vscode#92479]
Issue Type: <b>Bug</b>

Everytime the file is saved, the interface stops responding for a  while. This began since last update. 

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.5.8-200.fc31.x86_64 snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2046)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|15.59GB (6.59GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
random-string-password-generator|bib|1.0.2
gitignore|cod|0.6.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
git-extension-pack|don|0.1.3
githistory|don|0.6.2
gitlens|eam|10.2.1
vscode-detect-charset|yel|0.0.1
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by rebornix** [comment]
Can you follow the wiki https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process to provide profiles?
