### ISSUE TITLE
proposal: lazy load language-specific extensions on first file that matches

### ISSUE THREAD

**Issue by jokeyrhyme** [Microsoft/vscode#9248]
- VSCode Version: `code --version` => 1.4.0-insider
- OS Version: macOS Sierra 10.12 Beta (16A238m)

Steps to Reproduce:

1. install vscode-lint extension: https://github.com/Microsoft/vscode-tslint
2. start a new non-TypeScript project
3. observe the "Failed to load tslint library" error toast / snackbar

What I'm experiencing is mostly just a nuisance, but there's a question of efficiency / performance here as well. It appears that the tslint-server is started with each VSCode window, even before I've even opened a TypeScript file, even when the project does not even include any TypeScript files.

Because the tslint-server is always started, I get the toast / snackbar error "Failed to load tslint library" even in projects where it would never make sense for me to have the tslint NPM package installed. Note that I very much appreciate this message for TypeScript projects, it's very helpful in that case.

The majority of my projects use plain JavaScript, although I do hop through several TypeScript projects, too.

I'm not sure whether this is an extension-specific issue, or whether VSCode itself could be using documentSelector information from an extension to delay loading it until the first time a matching document type is encountered. /shrug

**Comment by jokeyrhyme** [comment]
https://github.com/Microsoft/vscode-tslint/issues/64

**Comment by jokeyrhyme** [comment]
As the primary desire here is to not see irrelevant error messages, perhaps hiding such error messages from non-matching extensions (until a matching document is encountered) would be an alternative approach?

**Comment by egamma** [comment]
closing - tracking this in vscode-tslint.
