### ISSUE TITLE
Debug : attach to process error: Could not attach to pid:####

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [microsoft/vscode#92486]
- VSCode Version:
1.42.1
- OS Version:
Linux x64 4.15.0-88-generic
Steps to Reproduce:

1.Installed tendermint network in virtual machine
2.launch.json
{
"version": "0.2.0",
    "configurations": [

        {
            "name":"attach to process",
            "type": "go",
            "request": "attach",
            "mode": "local",
            "processId": 32103
        }
                        
    ]
}

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Anjana-Prabhakar** [comment]
Could not attach to pid: 32103  this could be caused by a kernel security setting, try writing "0" to /proc/sys/kernel/yama/ptrace_scope

**Comment by rebornix** [comment]
Please file issues against Go extension you are using, thanks!
