### ISSUE TITLE
Sudenly debuger canceled on start.

### ISSUE THREAD

**Issue by Choockas** [microsoft/vscode#92481]
W
Issue Type: <b>Bug</b>

int main(){   
    int exi;
    map<int, string> mym;
    array<int, 10> fiar;
    //array<int, 10> fiar={0 };
  -  it is work

int main(){
   map<int, string> mym;
    array<int, 10> fiar={0 };
    ..................................
     - this is not work !!!

  int main(){
    array<int, 10> fiar={0 };
    .........................
 this is work again!  (?)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 220 Processor (2 x 2813)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (3.19GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
midl-webidl-syntax|dav|0.0.1
gitlens|eam|10.2.1
vscode-idl|kur|0.1.2
cpptools|ms-|0.27.0-insiders2

</details>
e have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rebornix** [comment]
Please file issues against C++ extension which provides this feature.
