### ISSUE TITLE
vscode can't save my file.

### ISSUE THREAD

**Issue by tolgit** [microsoft/vscode#92484]
Issue Type: <b>Bug</b>

Failed to save 'index.html': Unable to write file 'c:\Users\beby\Desktop\the_odin_project\google-homepage-\index.html' (Unknown (FileSystemError): Error: EBUSY: resource busy or locked, open 'c:\Users\beby\Desktop\the_odin_project\google-homepage-\index.html')

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz (2 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|1.93GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
It looks like maybe another process is holding a lock to the file given the message `resource busy or locked`, does it reproduce after a restart?
