### ISSUE TITLE
Quick input: should reserve space for actions?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92489]
When showing both separator and action I wonder if the toolbar should push out the separator always even when hidden to have a more consistent look:

![image](https://user-images.githubusercontent.com/900690/76424431-85e11e00-63a8-11ea-861e-1592adb1f3ec.png)

In other words, a hidden toolbar reserves space still.

Does that make sense?

**Comment by chrmarti** [comment]
This is consistent with other places (Debug stack view comes to mind). It might be problematic when there are several actions because more space needs to be reserved. /cc @isidorn @sandy081

**Comment by bpasero** [comment]
With 1 action and groups:

![image](https://user-images.githubusercontent.com/900690/76508704-1ffba180-644f-11ea-9011-0432a481d386.png)

With multiple actions and groups (we do not use this a lot):

![image](https://user-images.githubusercontent.com/900690/76509212-f0996480-644f-11ea-828e-aa860287107d.png)

When scrolled out of view:

![image](https://user-images.githubusercontent.com/900690/76509259-060e8e80-6450-11ea-96b0-db842bf00220.png)

not too bad I would say.

CSS changes:

https://gist.github.com/bpasero/95a2e48e7c20ef63ed21f0b2163a13fd

**Comment by isidorn** [comment]
The location should be fixed, the actions should not push other things so UI is stable and not flickery.
Call Stack is not doing it proper imho.

**Comment by chrmarti** [comment]
Sounds good. @bpasero Could you push your fix?

**Comment by bpasero** [comment]
Yes, can do that. If we think it behaves odd we can always revert, I do not have very strong feelings.
