### ISSUE TITLE
Terminal selector hover + scroll should change the current terminal without clicking

### ISSUE THREAD

**Issue by djsall** [microsoft/vscode#92482]
If you have two or more builtin terminals open, you should be able to hover over the box which shows the selected terminal and change the selected terminal by scrolling over it, without clicking and selecting another terminal.
![image](https://user-images.githubusercontent.com/4785203/76420824-04d35800-63a3-11ea-8001-cc0c9a2b71e1.png)
The highlighted selector above is the one I'm referring to.

**Comment by Tyriar** [comment]
Feature request for the custom dropdown

**Comment by isidorn** [comment]
I do not own the custom dropdown. Though I do not mind this issue being assigned to me.
