### ISSUE TITLE
Update-issue in Terminal

### ISSUE THREAD

**Issue by honekamp** [microsoft/vscode#92496]
Issue Type: <b>Bug</b>

It seems that the Terminal does not properly update after the panel was maximized while a process was producing textual output. That is, the cursor moves but nothing is displayed.

After scrolling with the mouse wheel or using "Restore Panel Size" and maximizing the panel again, the missing text is displayed properly. But it immediately goes out of sync again, i.e. cursor starts to move without anything getting displayed.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by honekamp** [comment]
Thanks for the fast response!
