### ISSUE TITLE
VSCode Online not saving settings

### ISSUE THREAD

**Issue by Relms12345** [microsoft/vscode#92499]
- VSCode Version: VSCode Online
- OS Version: Not sure because its online

Steps to Reproduce:

1. Purchase VSCode Online
2. Change some settings from the borwser
3. Close VSCode Online and open it in another computer
4. Settings are not changed

Does this issue occur when all extensions are disabled?: Yes

So basically I am trying to change some settings in VSCode Online to sync them across computers. But when I save and close VSCode Online in the browser and open it up in another computer, extensions are synced and all BUT settings that I changed under user settings are not saved.

**Comment by sandy081** [comment]
Please file the issue against VS Online.
