### ISSUE TITLE
i get so many error with fresh vscode and python extension

### ISSUE THREAD

**Issue by ghassemi-ehsan** [microsoft/vscode#92492]
Issue Type: <b>Bug</b>

i am newbie in python ,and just practicing.
i have installed fresh vscode and just python extension
but when i go to developer tools section i see many errors.
i tried vsode and vscode insider ,different version of python extension
but always same result.
vscode has found all python versions in left-bottom section and i can choose them and even execute my codes without error.
also, my all linters didnt work when i'm typing until i run or save my code 

this is my errors:
﻿
```
console.ts:137 [Extension Host] Error Python Extension: 2020-03-11 17:13:34: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.8-64
 -3.7-64
 -3.7-32
 -3.4-64
 -2.7-64 does not exist (at t (c:\Users\Ghassemi.ehsan\.vscode-insiders\extensions\ms-python.python-2020.2.64397\out\client\extension.js:1:6002))
console.ts:137 [Extension Host] Error Python Extension: 2020-03-11 17:13:34: failure while getting file type for "C:\Windows\CSC" [Error: EPERM: operation not permitted, lstat 'C:\Windows\CSC'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\Windows\\CSC'
} (at t (c:\Users\Ghassemi.ehsan\.vscode-insiders\extensions\ms-python.python-2020.2.64397\out\client\extension.js:1:6002))
t.log	@	console.ts:137
console.ts:137 [Extension Host] Error Python Extension: 2020-03-11 17:13:34: Failed to get interpreter information for '(value not set)\python.exe' [Error: Command failed: "(value not set)\\python.exe" "c:\Users\Ghassemi.ehsan\.vscode-insiders\extensions\ms-python.python-2020.2.64397\pythonFiles\interpreterInfo.py"
The system cannot find the path specified.

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"(value not set)\\\\python.exe" "c:\\Users\\Ghassemi.ehsan\\.vscode-insiders\\extensions\\ms-python.python-2020.2.64397\\pythonFiles\\interpreterInfo.py"'
} (at t (c:\Users\Ghassemi.ehsan\.vscode-insiders\extensions\ms-python.python-2020.2.64397\out\client\extension.js:1:6002))
2
console.ts:137 [Extension Host] (node:1824) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
```

VS Code version: Code - Insiders 1.44.0-insider (ef75c4bb445e5021065cf0012cfa2c66e55bfa16, 2020-03-11T09:14:53.536Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|27%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.2.64397

</details>

**Comment by rebornix** [comment]
Please file issues against the Python extension you are using, thanks!
