### ISSUE TITLE
Please allow release note animations speed to be adjusted and stopped

### ISSUE THREAD

**Issue by dws14159** [microsoft/vscode#92493]
I find release notes very difficult to read with all those animations frantically flashing away trying to show me their exciting new features.  Especially when it's a handful of text between two large flashing images.  Often I give up, which is a shame really cos I'd really like to know what's new.

It would be very nice to be able to click on something to say "please shut up, I'm reading something else", and "you're too quick, please slow down".

**Comment by mjbvz** [comment]
Is this for the release notes on the website or in product?

**Comment by dws14159** [comment]
In VSCode itself.  I think I can probably do all this within a browser, but in VSCode the animations have no controls.

**Comment by mjbvz** [comment]
Not sure what we can easily do here. They are using video tags to add the controls. All our release note animations are gifs (we don't ship support for showing video in VS Code)
