### ISSUE TITLE
Rename Symbol / F2 gives no result in HTML file

### ISSUE THREAD

**Issue by BillyCottrell** [microsoft/vscode#92498]
When editing a HTML file Rename symbol gives no result:
![](https://i.imgur.com/NbP7F8o.gif)

- VSCode Version: 1.43.0
- OS Version: Windows 10 Pro 1909

Steps to Reproduce:

1. Create a .html file
2. Paste following code:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form>
        <section class="form-block">
            <div class="form-group">
                <label for="empTitle">Title</label>
                <label for="empTitle" aria-haspopup="true" role="tooltip"></label>
            </div>
        </section>
    </form>
</body>
</html>
```
3. Right click on the empTitle inside label for attribute
4. Click Rename Symbol
5. Enter different name (in example its empName)
6. press enter (in bottom right "no result" will be displayed)

Does this issue occur when all extensions are disabled?: Yes

I do have to mention that doing this in a js and css file didn't create this issue, so only html file has this issue (as far as I know of other types of files may have this aswell).
I have also tested this with a saved .html file and a not saved .html file both had this issue.

**Comment by octref** [comment]
Rename only works for tag names.
