### ISSUE TITLE
minimap.background also makes the text transparent

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#92490]
The `minimap.background` artificially sets opacity on the whole canvas instead of just making the background transparent. This makes also the text transparent, which decreases its readibility. 
```
  "workbench.colorCustomizations": {
      "minimap.background": "#12121280",
```
I would prefer if only the background was transparent so that the text map keeps its contrast and readability.

I have tested the viability here: [codesandbox.io/s/canvas-opacity-vs-background-transparency](https://codesandbox.io/s/canvas-opacity-vs-background-transparency-f2tpq)
![image](https://user-images.githubusercontent.com/2313018/76423981-e58af980-63a7-11ea-9c09-d8b9b970198a.png)

---

`default: #1e1e1e`
![image](https://user-images.githubusercontent.com/2313018/76412016-2f1d1980-6393-11ea-8d24-5b7780b59d37.png)

`#1e1e1e80`
![image](https://user-images.githubusercontent.com/2313018/76412285-a652ad80-6393-11ea-97a7-2b2031b54051.png)

After digging deeper, I realised that the minimap is rendered into canvas and that the transparency is done by artificially setting opacity on the canvas. As my case study above suggests, it is possible to remove the background from the canvas and move it to css where it is possible to make it transparent separately, without affecting the canvas' opacity.
![image](https://user-images.githubusercontent.com/2313018/76412776-85d72300-6394-11ea-98c7-47ea795ada9f.png)
_note: `opacity: 0.502` equals the alphachannel value of the color above `#1e1e1e80`_

**Comment by ackvf** [comment]
@alexdima Don't get me wrong, I try to understand the amount of work and pressure you guys are under and i made this issue, because this subtle behavior got me off guard. I spent hours investigating to make sure I don't write bs. That being said, I think this is more of a bug than feature request. When the option says "`minimap.background`", it is really unintuitive to expected that it affects the whole minimap (even foreground, text) and not just its background. I even tried to fix that myself, but the internals are so obscure for me to work with. Perhaps if you could help point me the right direction I would then fix it. Basically what I need is
1) read the value from options
2) find the place where it calculates opacity and remove that
3) and instead use the value and put it into css sheet or inline for the minimap dom element.

**Comment by ackvf** [comment]
Thank you

**Comment by Krysl** [comment]
A small hack for `VSCode v 1.59`
<img width="606" alt="minimap" src="https://user-images.githubusercontent.com/5905801/130754099-f6de60f7-cce5-4780-b3a3-68f507c3b054.png">

"[VS Code Install Path]\resources\app\out\vs\workbench\workbench.desktop.main.js"
1. set background opacity:
    - use regex to search `\w\[\w\+3\]=\d+,\w\+=4`
        - Found `B[W+3]=255,W+=4`
    - replace `255` with `128`(background opacity) 
2. set text opacity:
    - use regex to search `\w\[\w\+\+\]=\w\+\w\*\w,\w\+\+`
        - Found `v[_++]=u+d*L,_++`
    - replace `_++` with `v[_++]=255`(text opacity) 
3. `Ctrl+Shift+P`:`Reload Window`
(need to disable config for `"minimap.background"`)
![minimap](https://user-images.githubusercontent.com/5905801/130753786-b986849f-974d-41a9-8ff0-b89f0ad05143.gif)

**Comment by ackvf** [comment]
@Krysl wow 🤯

**Comment by ackvf** [comment]
https://github.com/microsoft/vscode/pull/61021

**Comment by Krysl** [comment]
> So close #61021

My hack is based on the core code of this patch.

There is already a pull request, but it has not been merged. What a pity

**Comment by alexdima** [comment]
I have revived #61021 in #132681 and it is now possible to configure the background opacity independently of the text's opacity e.g.:

```js
// this makes the minimap background completely transparent, and the minimap text 68% opaque
"workbench.colorCustomizations": {
	"minimap.background": "#ffffff00",
	"minimap.foregroundOpacity": "#ff0000af",
}
```

![image](https://user-images.githubusercontent.com/5047891/135342817-9e3904a2-50bb-42a1-8fcb-58afc52e34ba.png)
