### ISSUE TITLE
incorrect comment color in javaScript after customization

### ISSUE THREAD

**Issue by FatTonyy** [microsoft/vscode#92494]
Issue Type: <b>Bug</b>

"editor.tokenColorCustomizations": {
    "comments": "#0da707"
  }

after this customization all comments appear deep green in HTML and CSS except comments in javascript.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Perhaps caused by Javascript now using semantic highlighting by default. See https://github.com/microsoft/vscode/issues/92308#issuecomment-597208066 for info about how to discover what semantic element your Javascript comments are being classified as. Then set your dark green custom color on that.

**Comment by aeschli** [comment]
Semantic highlighting does not affect comment.

But the inspect tool (`Developer: Inspect Editor Tokens and Scopes`) tool will be able to help to see what scopes a identifier has. Set the cursor on the comment with the wrong color and invoke the command.

Can you try this and add a screenshot to the issue?

I followed your steps and for me all JavaScript comments correctly get the new color.
Maybe you have a custom JavaScript grammar installed?

**Comment by FatTonyy** [comment]
> Semantic highlighting does not affect comment.
> 
> But the inspect tool (`Developer: Inspect Editor Tokens and Scopes`) tool will be able to help to see what scopes a identifier has. Set the cursor on the comment with the wrong color and invoke the command.
> 
> Can you try this and add a screenshot to the issue?
> 
> I followed your steps and for me all JavaScript comments correctly get the new color.
> Maybe you have a custom JavaScript grammar installed

**Comment by FatTonyy** [comment]
It works when you use multiple line in js (/*comments */) , however with single-line comment
(// only the slashes turns, but the comments itself doesn’t.
