### ISSUE TITLE
Stop adding features, It works just fine!

### ISSUE THREAD

**Issue by ExDeaDguY** [microsoft/vscode#92497]
Why must features on top of features keep getting added? I use VSCode for its speed and performance over visual studio. What is the point if you guys keep flooding it with more and more crap that bogs it down. Now all of a sudden I'm getting "window has crashed" when VSCode runs through its compile time update cycle to check for inline errors. Just stop and leave it alone. Bugfixes only man!

**Comment by BillyCottrell** [comment]
I partially agree that adding features constantly will remove its key benefits like speed and performance. Although I do have to say that some features are really usefull/necessary in probably most environments.

I kinda feel like there should be a way to start VSCode as a basic lightweight editor where the user choose to add/enable more features based on the needs of certain projects/environments the user has to deal with. Which might improve VSCode for those that don't really need a lot of features, and also make it more flexible to those that need it.

**Comment by ExDeaDguY** [comment]
@BillyCottrell Yeah true, But I've been able to do the work I'm doing for the last year or 2 now without issue. Any added features I generally don't use. The should be focusing features into extensions so everyone isn't forced to use em. Such as this "dotted line" crap that shows up before each line of code now (representing indentation?) and the line. Just my opinion anyways ;)

**Comment by chrisdias** [comment]
@ExDeaDguY sorry that you ran into the "window has crashed" problem.  Are you still seeing this issue?  if you can repro the problem still can you add the steps here? Also, this link may help: https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

We do try to build as much as we can of VS Code as extensions. In fact, you can see all of the built-in extensions, and disable them, from the Extension Viewlet. click on the "..." and choose `Show Built-In Extensions`:

![image](https://user-images.githubusercontent.com/1487073/76647748-0166da80-6523-11ea-8e66-cab74e3fae61.png)

@ExDeaDguY the dotted lines you see may be a change we made in the latest release to show whitespace on selection by default (see https://code.visualstudio.com/updates/v1_43#_render-whitespace-on-selection). You can turn this off by changing the `renderWhitespace` setting to `none`, like this in `settings.json`:

```
{
   "editor.renderWhitespace": "none"
}
```
