### ISSUE TITLE
debugging coreclr applications on mac and linux [Question]

### ISSUE THREAD

**Issue by shahid-pk** [Microsoft/vscode#925]
I am sorry if this has been asked before or if this is not the appropriate place to ask. Why vscode does not support coreclr based application debugging on mac and linux ? i know that pdb is not cross platform but roslyn can also generate ppdb which is xplat. Is their any blocker ?

**Comment by egamma** [comment]
A first version of coreclr debugging was presented at the Connect() event, a first version will be available in the first quarter.
