### ISSUE TITLE
[BUG] [Regression] "Rename failed to execute" when renaming a variable in TypeScript

### ISSUE THREAD

**Issue by jsgoupil** [microsoft/vscode#92507]
Regression on 
"Rename failed to execute" when renaming a variable in TypeScript #81125

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Please provide example code and steps to reproduce

**Comment by jsgoupil** [comment]
@mjbvz Same exact steps and *video* from the other bug.

**Comment by mjbvz** [comment]
Please share code (as text)!

**Comment by mjbvz** [comment]
Or is this for all code? We get a lot of issue reports so please include all required info upfront to save everyone time

**Comment by jsgoupil** [comment]
It would have saved time if there were unit tests with the previous bug fix.

> Steps to Reproduce:
> 
> Open a TypeScript file
> Click on a variable
> Press F2
> Click on the variable above the rename box that opened (you should be clicking in the code)
> Click in the rename box to put back the focus where you want to rename.
> Rename the variable and press Enter.
> ACTUAL:
> Rename failed to execute
> 
> EXPECTED:
> Rename the variable appropriately.

> I can definitely repro.
> I think it has one more "rule" to this.
> When you click back on the variable, you have to change the cursor position.
> So if your variable is "hello" and your cursor is positioned at the end of the word. Press F2, then move the cursor between the two "L".
> 
> Attached video.
> ● after-view-init.directive.ts - MapRadius.Web.Client - Visual Studio Code - Insiders 2019-09-23 21-40-10.mp4.zip

**Comment by mjbvz** [comment]
@jrieken I think this broken during the rename preview refactoring. Can you please take a look?

**Comment by jsgoupil** [comment]
Thanks for fixing this! Greatly appreciated.
Do you guys write some unit tests for for bugs like this? This one crept up twice in less than 1 year.
