### ISSUE TITLE
Watch typescript files included in tsconfig.json / jsconfig.json

### ISSUE THREAD

**Issue by c3-willydouhard** [microsoft/vscode#92500]
Hello,

I have a jsconfig.json file including some type definitions living outside of the VSCode workspace I am working in. Let's call one of those definitions `foo.d.ts`.

When the TS language service is booting for the first time, everything works fine. However if `foo.d.ts` is modified by a third party program (eg the user did not open this file in the workspace) then the type definition will not be updated in VSCode. As soon as I open `foo.d.ts` in the workspace the type definition updates.

One hack is to Restart the TS language service manually.

I tried to use the latest features of the insiders version, like `Tsserver: Watch Options` and `Tsserver › Experimental: Enable Project Diagnostics` without success.

I would like VSCode to watch files outside of my workspace (included in `jsconfig.json`) without having to open them explicitly. 

My `jsconfig.json`:

```js
{
 "compilerOptions": {
  "target": "es5",
  "lib": ["es2015"],
  "checkJs": true
 },
 "typeAcquisition": {
  "include": ["jasmine", "underscore"],
 },
 "include": ["src", "test", "/Users/willydouhard/types"]
}
```

**Comment by mjbvz** [comment]
I can't reproduce this in VS code 1.44 on MacOS.

Can you confirm that both files are part of your jsconfig project by opening them and running the `TypeScript: Go to project configuration` command. This should open up the jsconfig
