### ISSUE TITLE
VS Code and Code-Insiders to Share Same extension (toggle)

### ISSUE THREAD

**Issue by Mac-DevOSYandex** [microsoft/vscode#92504]
1. Is it possible for VSCode and Code-Insiders to share the same extension since it is a dot directory (macOs) in the root. 

2. It would be nice to have npm (I am specifically thinking of Angular2+) to reside in root under a dot directory..

**Comment by sandy081** [comment]
You can launch either of them using the command line argument `--extensions-dir` pointing to the extensions directory.

**Comment by Mac-DevOSYandex** [comment]
Hey sandy081, 

Thanks. I'll give it a try. 

Once again many thanks
