### ISSUE TITLE
Visual Code launches on wrong Xserver instance

### ISSUE THREAD

**Issue by fdk17** [microsoft/vscode#92503]
- VSCode Version: 
code --version
1.43.0
x64

- OS Version:
Ubuntu 18.04.4 LTS

Steps to Reproduce:
1. Run a X2GO server
2. Log into Ubuntu machine
3. From a remote computer log into X2Go server
4. Launch Visual Code
5. Visual Code will open on real desktop (:0.0) not the X2GO instance (:50.0).

Explicitly setting DISPLAY on the command line doesn't help.
$ DISPLAY=:50 code --verbose --disable-gpu
[main 2020-03-11T17:02:31.304Z] Sending env to running instance...
[main 2020-03-11T17:02:31.405Z] Sent env to running instance. Terminating...
[main 2020-03-11T17:02:31.406Z] Lifecycle#kill()

The window is created on DISPLAY ':0'. 
Code will check to see if DISPLAY does exist.
$ DISPLAY=:51 code --verbose --disable-gpu
(code:10267): Gtk-WARNING **: 13:04:31.873: cannot open display: :51

**Comment by rebornix** [comment]
Not sure which piece of code controls this behavior, please help @deepak1556

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ? Also try launching with `--no-xshm` with insiders.
