### ISSUE TITLE
点击“终止终端”反应十分缓慢

### ISSUE THREAD

**Issue by hrpzcf** [microsoft/vscode#92505]
Issue Type: <b>Bug</b>

点击“终止终端”(终端界面右上角的垃圾桶图标)反应十分缓慢，我是在运行python代码时遇到这个问题的，我的终端设置是cmd。

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.64GB free)|
|Process Argv|D:\zz_Python\learning\RenameTool|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
code-runner|for|0.9.17
vscode-language-pack-zh-hans|MS-|1.43.2
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
vscode-icons|vsc|10.0.0
pyqt-integration|zho|0.2.0
material-theme|zhu|3.2.3

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
> 点击“终止终端”(终端界面右上角的垃圾桶图标)反应十分缓慢，我是在运行python代码时遇到这个问题的，我的终端设置是cmd。

Kill Terminal is really slow and run into this issue when running Python code.

**Comment by Tyriar** [comment]
Can you define what slow means?

Is the terminal you're using a Python-extension terminal? You can post a screenshot here of the terminal panel (including dropdown) to tell.

**Comment by hrpzcf** [comment]
> Can you define what slow means?
> 
> Is the terminal you're using a Python-extension terminal? You can post a screenshot here of the terminal panel (including dropdown) to tell.

It means that when I click on the "Kill terminal" button, there is no response for two or three seconds, and it is finally terminated. 
![批注 2020-03-13 011918](https://user-images.githubusercontent.com/58855572/76548181-5249e500-64c9-11ea-863c-2f41dfb5747d.png)
