### ISSUE TITLE
Configured debug type 'pwa-node' is not supported (VSCode 1.43.0)

### ISSUE THREAD

**Issue by Didier68** [microsoft/vscode#92506]
It the same problem that  #90195 ..  

Version : 1.43.0 (system setup)
Validation : 78a4c91
Date : 2020-03-09T19:47:57.235Z
Électron : 7.1.11
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Windows_NT x64 10.0.17763
 
![Image 3](https://user-images.githubusercontent.com/49448202/76444059-ae2a4600-63c3-11ea-8b85-625b408a4d7f.png)

Hi to all,

I updated VSCode, installed js-debug-nightly, and set the parameter ["debug.node.useV3": true] to test this extension.

Then I decided to unstall the js-debug extension and also removed this option ["debug.node.useV3": true],... Now, I have the same issue than @AssisrMatheus (but in french)

The content of **C:\Users\xxx\AppData\Roaming\Code\User\settings.json**:
{ 
  "editor.minimap.showSlider": "always", 
  "typescript.updateImportsOnFileMove.enabled": "always", 
  "window.zoomLevel": 0, 
   "git.autofetch": true, 
   "git.enableSmartCommit": true, 
   "editor.minimap.size": "fill", 
    "editor.columnSelection": false, 
   "editor.minimap.enabled": false 
}
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Didier68** [comment]
After continuing to search the configuration files, I found the option `"debug.node.useV3": true` in workspace.json, as duplicate of setting.json

By removing this option, everything is back to normal, and I can use my favorite debugger again!
Sorry for the inconvenience

**Comment by AlexZeitler** [comment]
For me it was `Application Support/Code - Insiders/User/settings.json` (on macOS): `debug.javascript.usePreview` was still `true`.
