### ISSUE TITLE
Markdown Preview significantly worse after the update

### ISSUE THREAD

**Issue by jerry-sky** [microsoft/vscode#92519]
Issue Type: **Bug**

## Steps to reproduce
1. Open any Markdown file containing more than just very basic Markdown using VS Code.
2. Turn on preview (default keybinding: `Ctrl + K, V`).

The output is horrendous in comparison of what the preview shows in the old (January) version.\
One example of that behavior would be broken LaTeX support as shown in the example below.\
Another one would be broken links to other local Markdown documents. Also, these links have an ugly yellow outline.

The preview works like a _very basic_ Markdown parser - which was not the case in the previous version. **Markdown Preview in the previous version was a very good tool.**

## Example
`tmp.md`:
```markdown
# Title

$$
\sum_{k=0}^{n}\binom{n}{k} = 2^n
$$

```
Normally this file would generate following output:
![expected preview](https://user-images.githubusercontent.com/4989529/76454412-e5552300-63d4-11ea-861e-75b853b92427.png)

In the new version the preview looks like it barely works: 
![current version preview](https://user-images.githubusercontent.com/4989529/76454534-20575680-63d5-11ea-9d7e-8ed3a67328a8.png)

## Please note:
**I'm using the insiders version, but this behavior is identical to this of the latest version of `1.43`.**

_For now I'm downgrading back to January version._

---
VS Code version: Code - Insiders 1.44.0-insider (ef75c4bb445e5021065cf0012cfa2c66e55bfa16, 2020-03-11T09:19:54.444Z)
OS version: Linux x64 5.3.6-050306-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3172)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|11.58GB (1.03GB free)|
|Process Argv|tmp.md --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jerry-sky** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Help test and implement the markdown custom editor preview (#84520)](https://www.github.com/microsoft/vscode/issues/84520)
> * [Auto Preview for Markdown File (#85483)](https://www.github.com/microsoft/vscode/issues/85483)
> * [How to set off automatic preview of markdown files (#91251)](https://www.github.com/microsoft/vscode/issues/91251)
> * [Drag markdown preview to New Window (#32818)](https://www.github.com/microsoft/vscode/issues/32818)
> * [Can't scroll a markdown preview using touch (#39195)](https://www.github.com/microsoft/vscode/issues/39195)

These are not related to this issue.

**Comment by mjbvz** [comment]
VS code's markdown preview has never included LaTeX support out of the box: this must have come from one of the extensions you had installed. Please make sure the extension you want is installed and file an issue against them if something doesn't work

**Comment by jerry-sky** [comment]
> VS code's markdown preview has never included LaTeX support out of the box: this must have come from one of the extensions you had installed. Please make sure the extension you want is installed and file an issue against them if something doesn't work

I did not realize this feature is a part of a separate extension. I took it for granted and didn't check without any extensions enabled. I do apologize.
