### ISSUE TITLE
Issues with VSCode and Python Kernel version for datascience library due to MS Python extension

### ISSUE THREAD

**Issue by leestott** [microsoft/vscode#92511]
Hi I have come across some issues with the running VS Online and Jupyter Python

Code version 1.43.0 
![code version](https://user-images.githubusercontent.com/2511341/76449510-1d079f00-63c4-11ea-8bc8-455a6a8e9c6a.PNG)

I have a custom docker image which gets deployed as VS Online or can be used within VS Code if you installed the associated libraries. see https://github.com/leestott/MSLearn-DataScience you can use this for repo if required

The specific Library I have noticed a issue with is the datascience Library from UC Berkeley https://pypi.org/project/datascience/

Specific issues are around the use of the datascience library

I'm seeing is a issues with the MS python vs code extension where it seems to be getting in the way of the Jupyter Python Kernel.. so you get errors like this.. I am getting the same error in VS Code and VS Online see https://github.com/MicrosoftDocs/vsonline/issues/342

![datascienceerror](https://user-images.githubusercontent.com/2511341/76449587-40324e80-63c4-11ea-965f-eccc8ce7d6c9.png)

ImportError: cannot import name 'Table' from 'datascience' (c:\Users\leestott.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\datascience_init_.py) See how its using ms-python>

I am running 3.7.4 within Code as defined by the docker image.

I am getting the same error in both VS Code and VS Online so this seems to make me think it is related to the MS-Python Extension. running the same code in Azure Notebooks works perfectly see https://mslearndatascience-leestottmicrosoft.notebooks.azure.com/j/notebooks/labs/scratchpad/scratchpad.ipynb

I have confirmed that the libraries have been installed within my VS Code and VS online with python -c datascience from the terminal and inline !pip install which confirms the libraries are there.

**Comment by DonJayamanne** [comment]
We [Python Extension](https://github.com/microsoft/vscode-python) could rename the folder from `pythoFiles/datascience` to pythonfiles/pvsc_datascience` or similar.
Ensure the name is specific to the python extension or similar (to avoid conflicts with similar/generic names).

**Comment by leestott** [comment]
Thanks. For the confirmation
