### ISSUE TITLE
Resize Pane Crashing

### ISSUE THREAD

**Issue by mecfletcher** [microsoft/vscode#92513]
Issue Type: <b>Bug</b>

EVERY single time I resize a pane in VSCode the window or whole application crashes. This is infuriating.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|32.00GB (11.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
jquerysnippets|don|0.0.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-sort-json|ric|1.18.0
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you launch with all extensions disabled?
