### ISSUE TITLE
[Feature Request] Command Line Option to prompt for Sync

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#92516]
Love the new sync feature! I would like to be able to make a portable vscode zip that, upon startup, would immediately prompt for sync login, start the sync, and then reload with my new sync, so I can download it to a computer I'm guesting on and have basically my normal experience with little hassle.

I figure this is best either as a command line option or as a settings.json item that can be pre-populated.

**Comment by sandy081** [comment]
If I understand correctly you would like to start vs code with sync turned on? For eg: saying `code --sync on` shall start VS Code with sync started?

**Comment by JustinGrote** [comment]
@sandy081 or just `--sync` that will basically call the "Sync: Configure" task on startup, skip the "what to sync" prompt, and just ask me for my Microsoft Login, immediately sync, and reload if required to apply the synced settings/extensions, if that makes sense.

Goal is to make a portable zip that I don't have to go through the sync configure process every time I open it on a new computer or system.

**Comment by sandy081** [comment]
it will be `--enable-sync` or `--disable-sync`. 

Enabling sync will enable sync in VS Code. You are already `signed in` sync will continue otherwise there will be a notification in the gear icon showing an action to sign in.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/10746682/76658545-a5c53d00-6574-11ea-93c2-79a058755960.png">

**Comment by JustinGrote** [comment]
Close enough. Thanks for your assistance!

**Comment by sandy081** [comment]
Provided following option

```
  --sync <on> <off>                 Turn sync on or off
```

`code-insiders --sync on` Turn sync on
`code-insiders --sync off` Turn sync off

**Comment by Tyriar** [comment]
I brought up in https://github.com/microsoft/vscode/issues/93262 why this CLI exists as CLI space is at a premium (especially if we don't have namespacing). This seems like a helpful way to automate for a handful of people while adding an extra line of text for everyone else, cluttering the CLI.

> if I want to start VS Code by disabling sync because if sync is on there is no way to start VS Code without triggering sync. By the time window comes up and I disable sync VS Code would have already started syncing. It is very similar to --disable-extensions.

This doesn't seem that useful either; if someone enabled sync, they can just launch the client to turn it off. It's not the same as `--disable-extensions` as that's temporary, I'm assuming this is not?

**Comment by sandy081** [comment]
> If someone enabled sync, they can just launch the client to turn it off.

This is for the case that I want to launch code without sync getting started at all. It can happen that sync can happen in the time between I start VS Code and turn it off. As @bpasero mentioned in the other issue, this scenario comes under trouble shooting. 

If it is an issue with namespace or cli cluttering, I am ok to move to other section or completely hide it.

**Comment by bpasero** [comment]
I would at least have it under `Troubleshooting` and not the main category.
