### ISSUE TITLE
Ghost window when enabling extensions

### ISSUE THREAD

**Issue by nadrojisk** [microsoft/vscode#92523]
**Describe what happened:**
When opening vscode in full screen mode on macOS there is this weird graphical bug that shows up. It looks like || essentially. It will disappear if not clicked on after a few seconds, I assume it has to do with the extension loading but it is distracting. Also if you click and drag on it, it can be opened as a window.

**What was your system configuration?**
vscode: 1.43.0
*OS Version*: macOS 10.15.3 (19D76)

**Steps to Reproduce / Scenario:**
Open VScode in full screen mode with live share disabled
Enable live share

![Screen Shot 2020-03-10 at 2 14 17 PM](https://user-images.githubusercontent.com/37343577/76350281-78109780-62d9-11ea-82e7-e3db355ad5d8.png)

![weird_window](https://user-images.githubusercontent.com/37343577/76350817-6d0a3700-62da-11ea-97c0-1214ee6f64cb.gif)

[logs.zip](https://github.com/MicrosoftDocs/live-share/files/4314332/logs.zip)

Does this issue occur when all extensions are disabled?: No

I have already posted this on liveshare's github and they recommended they I post it on the main vscode issue board as they think it is the overall application and not the extension.

https://github.com/MicrosoftDocs/live-share/issues/3240

**Comment by sandy081** [comment]
Does this happen for all extensions? Or only for this extension?

**Comment by nadrojisk** [comment]
@sandy081 originally I believed it only occurred with liveshare. But yesterday when I was messing around and created a new window it occurred with share disabled.

**Comment by sandy081** [comment]
Not sure where this window is coming from and how to know, hence assigning to you.

**Comment by bpasero** [comment]
@nadrojisk so does this only happen when you transition the liveshare extension between enabled <=> disabled? Can you please try with other extensions.

**Comment by bpasero** [comment]
Also, does this window show up with a dock entry?

**Comment by nadrojisk** [comment]
@bpasero no window appears with the docker entry. It happened a few days ago with another extension being enabled but I could not remember the name. I will try to recreate it with something other than liveshare.

**Comment by bpasero** [comment]
Yes please do and if it only reproduces with Liveshare, I think we should move this issue to them. Maybe their extension is doing something that is triggering it.

**Comment by nadrojisk** [comment]
Sorry forgot about this. Yes I couldn't find an instance of where it wasn't Liveshare causing this bug.
