### ISSUE TITLE
Serial port cannot be selected 1.43

### ISSUE THREAD

**Issue by DerekFoster1976** [microsoft/vscode#92521]
Auto-updated from 1.42 to 1.43 on Windows 10 and serial port selector no longer works, need for development on MXChip. Downgraded to 1.42 and everything working again.

**Comment by gjsjohnmurray** [comment]
Is the "serial port selector" something added by one of your extensions?

**Comment by rebornix** [comment]
Please file issues against the extension which provides this feature, I think it's because they didn't publish a new version which works with latest Electron VS Code is using.
