### ISSUE TITLE
Highlighting a selected search result doesn't provide any visual feedback

### ISSUE THREAD

**Issue by christophebedard** [microsoft/vscode#92529]
- VSCode Version: 1.43.0 (78a4c9)
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Search for a string in a workspace (`Ctrl+Shift+F`)
2. Click on one result from the results list. It should be highlighted in white-ish

![Screenshot from 2020-03-11 18-42-01](https://user-images.githubusercontent.com/3717345/76471049-09f6ce00-63c8-11ea-897d-f09498c58c8f.png)

3. Hightlight it (or part of it). In the screenshot below, I've highlighted the portion from the end of the line to the cursor (in the second occurrence of `json`).

![Screenshot from 2020-03-11 18-43-10](https://user-images.githubusercontent.com/3717345/76471115-314d9b00-63c8-11ea-8c32-19033895018b.png)

There is no visual feedback (like what you'd get if you did a simple/normal hightlight). Proof is that pressing delete/backspace deletes that part.

Highlighting/selecting text should always provide visual feedback, no matter what.

There's even situations where the highlighting gesture (when you're holding the mouse button down and moving it to where you want the highlighted portion to end) shows you moving the cursor, kind of like if you were moving highlighted text around.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/43928
