### ISSUE TITLE
Font colors sporadically changes itself after reload

### ISSUE THREAD

**Issue by Silind** [microsoft/vscode#92520]
- VSCode Version: 1.43
- OS Version: Ubuntu 19.10

Since upgrading to 1.43, font colors seem to be automatically changing a few seconds after reload.

### Demonstration
Initially with preferred colors.
After 3-5 seconds they change.

Additionally, the colors seem to apply in a weird, non-logical way.
![](https://i.imgur.com/9xqCxvw.gif)

In the screenshot, I'm using Material Theme.
If I change to any other theme (VSCode inbuilt, incl.), the problem remains, however, the actual colors are different.

Does this issue occur when all extensions are disabled?: Yes, it still occurs.

**Comment by tdnl** [comment]
Happening here as well. The colors change right after the TS server's initialization.

**Comment by JosefBud** [comment]
+1 here. Using the [Electron theme](https://marketplace.visualstudio.com/items?itemName=kuscamara.electron&ssr=false#overview) it goes from the correct theme
![correct](https://i.imgur.com/g72xenp.png) To an entirely different theme: 
![incorrect](https://i.imgur.com/iJDG45B.png)

This happens after initializing.

**Comment by hauntedlollipop** [comment]
+1 here, it all started when I installed the latest update...

**Comment by bartoszmagier** [comment]
+1 here. I am also using Material Theme, but it also happens on other themes even with all extensions disabled.

**Comment by Gama11** [comment]
https://stackoverflow.com/a/60623984/2631715

**Comment by jaszhix** [comment]
How do you customize the semantically highlighted keywords? 

Before:
![before](https://user-images.githubusercontent.com/6859057/76467647-11ae7680-63b8-11ea-92bd-6ca76905d2ef.jpg)

After:
![after](https://user-images.githubusercontent.com/6859057/76467654-170bc100-63b8-11ea-857a-52a232f0c358.jpg)

I can see how this can be helpful to differentiate the variable types, but I would like to saturate the colors more so the function invocations don't look so similar to the function definitions.

[Theme used](https://github.com/jaszhix/monokaimega-vscode-theme)

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/92308#issuecomment-597208066
