### ISSUE TITLE
Clear Recently Opened doesn't clear Peek window

### ISSUE THREAD

**Issue by sharkweek** [microsoft/vscode#92525]
I'm programming in C/C++ and using the Microsoft C/C++ extension enabled for finding definitions. I also have `editor.gotoLocation.multipleDeclarations` set to `peek`.

When I use the `Go to Definition` command and have multiple definitions, the Peek window also includes recently opened files that are not in my project's working directory. I have tried using the `Clear Recently Opened` command, but these files are not cleared from the Peek results. I've also tried reloading the window, but they still show up.

So far the only thing I've found that helps is deleting the recently opened file, which is less than ideal...

__System info:__
Version: 1.43.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by sbatten** [comment]
@sharkweek when you `Clear Recently Opened`, these files no longer appear in the menu/open recent section, correct?

@isidorn do you know how these commands populate results with recently opened files?

**Comment by sharkweek** [comment]
@sbatten That's correct. The `Clear Recently Opened` seems to work fine for everything else.

**Comment by isidorn** [comment]
@sbatten no, I do not know. But I see that there is api `addRecentlyOpened` on the `WorkspaceService`. I would check users of that.
Also @jrieken might know for peek.

**Comment by jrieken** [comment]
Peek has no connection to the list of recently opened files - its contents are entirely computed by extensions - the c/cpp extension in this case

**Comment by sharkweek** [comment]
Ah, okay. I'll create a new issue on that extension. Thanks!
