### ISSUE TITLE
"Cut the line" shortcut

### ISSUE THREAD

**Issue by Damag3d** [microsoft/vscode#92524]
Add shortcut to cut the line. Here i mean not only spaces but text as well. Option copy to clipboard would make it even more useful.
Ctrl+Shift+Delete. 

Thank you!

**Comment by ArturoDent** [comment]
Do you have a set character limit that you want?  You could make your own shortcut to do this.

**Comment by IllusionMH** [comment]
There is already <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>K</kbd> for removing line. You can change shortcut to one that suits you better using `>Preferences: Open Keyboard Shortcuts` or in `keybindings.json`:

```json
{
    "key": "shift+alt+delete",
    "command": "editor.action.deleteLines",
    "when": "textInputFocus && !editorReadonly"
}
```

For cutting line into clipboard you can just use <kbd>Ctrl</kbd>+<kbd>L</kbd> to select whole line and then regular <kbd>Ctrl</kbd>+<kbd>X</kbd>
