### ISSUE TITLE
button has gone！

### ISSUE THREAD

**Issue by smarteng** [microsoft/vscode#92534]
- VSCode Version:1.43
- OS Version:macOS 10.14.6

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/663786/76476508-3567d000-643d-11ea-8e92-76ec81a41ec1.png)
I update vscode ，and then，the open folder button has gone！
![image](https://user-images.githubusercontent.com/663786/76476545-4ca6bd80-643d-11ea-8a43-7e5f7315f74e.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
This is either a bug with the translation itself and or how we handle the string in a tranlated version. I will start with @isidorn as a owner of the explorer. 

@isidorn if you think that is a translation problem please assign to @danyeh @janbaltus.

**Comment by isidorn** [comment]
Thanks @dbaeumer 
I have pushed a comment to all these strings that the word `command` should **not** be transalted.
Forwarding this issue to @danyeh and @janbaltus as this has to be fixed on the transaltion side.
It would be very cool if we fix this as soon as possible as it breaks one of the key flows in VS Code.
For transparency adding Important label.

**Comment by janbaltus** [comment]
Please update the LP version to 1.43.7

**Comment by isidorn** [comment]
@janbaltus thanks a lot for the quick fix!
