### ISSUE TITLE
Find and replace opens edited files

### ISSUE THREAD

**Issue by mandrakejons** [microsoft/vscode#92530]
When you use the Replace in Files command, after you finish replacing what you indicate, each and every one of the files where it was found is opened and the text you indicate is replaced.

I don't want the files that were modified to open.

**Comment by mandrakejons** [comment]
When you use the Replace in Files command, after you finish replacing what you indicate, each and every one of the files where it was found is opened and the text you indicate is replaced.

I don't want the files that were modified to open.

**Comment by roblourens** [comment]
Does this happen if you start vscode with `--disable-extensions`?
