### ISSUE TITLE
Open folder button disappears in explorer 

### ISSUE THREAD

**Issue by MeansonChen** [microsoft/vscode#92539]
Issue Type: <b>Bug</b>

The open folder button and clone repository button in explorer when i upgrade to 1.43.0.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.5.8-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2652)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 11, 10|
|Memory (System)|15.52GB (2.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
include-autocomplete|ajs|0.0.4
vscode-browser-preview|auc|0.5.9
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-html-css|ecm|0.2.3
code-runner|for|0.9.17
vscode-mysql|for|0.4.0
beautify|Hoo|1.5.0
path-autocomplete|ion|1.13.3
mysql-syntax|jak|1.3.1
vs-color-picker|lih|1.0.0
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.43.2
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
view-in-browser|qin|0.0.5
java|red|0.58.0
LiveServer|rit|5.6.1
vscode-leetcode|she|0.16.1
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-test|vsc|0.22.2
vscode-icons|vsc|10.0.0

</details>

**Comment by bpasero** [comment]
@rebornix please assign issues for the explorer to Isi

**Comment by MeansonChen** [comment]
I find the way to slove this problem in settings .
