### ISSUE TITLE
TreeView reveal should not trigger warnings

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#92538]
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Have a view with a `when` context that causes it to be show/hidden. For example, by using `onDidChangeActiveTextEditor` to hide the view when the `languageId` isn't supported.
2. Have the view's data provider trigger a command that executes `TreeView.reveal()` just prior to the view being hidden. In my case, this is caused by listening to `onDidChangeTextEditorSelection`.

   This is the command handler:
```ts
LogService.info('onRevealTreeItem: isVisible=' + this.view.visible);
const item = this.provider.findTreeItemAt(position);
if (item !== null) {
  this.view.reveal(item, { select: true });
}
```
3. As far as I can tell, when selecting a different text editor this occurs:
   - `onDidChangeTextEditorSelection` is triggered for the original editor (with a 0,0 selection) prior to being triggered again on the new editor. The first event is therefore unstoppable from the provider side.
   - The command handler for the first event executes. At this point `view.visible` is still `true`, meaning that the call to `reveal` is unstoppable from the view side.
   - The `onDidChangeActiveTextEditor` event then executes, which hides the view, since `reveal` is asynchronous.
   - The queued `reveal` then executes, **and should fail** (the context is correct), while triggering the warning.

   Relevant log entries:

```
[info] onDidChangeTextEditorSelection (file:///c%3A/Users/Matt/Documents/VSCode/Projects/redacted/test.js)
[info]   start={3, 0}, end={3, 0}
[info]   execute revealTreeItem
[info] onRevealTreeItem: isVisible=true
[info] onDidChangeTextEditorSelection (file:///c%3A/Users/Matt/Documents/VSCode/Projects/redacted/test.js)
[info]   start={0, 0}, end={0, 0}
[info]   execute revealTreeItem
[info] onRevealTreeItem: isVisible=true
[info] context changed
[info] onDidChangeTextEditorSelection (file:///c%3A/Users/Matt/Documents/VSCode/Projects/redacted/readme.md)
[info]   start={12, 0}, end={12, 0}
```

**Actual result:**
```
rejected promise not handled within 1 second: Error: Unknown view customView
stack trace: Error: Unknown view customView
    at e.isVisible (file:///C:/Users/Matt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5320:911)
    at e.toggleViewVisibility (file:///C:/Users/Matt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5873:597)
    at e.openView (file:///C:/Users/Matt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5872:580)
    at i.openView (file:///C:/Users/Matt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3553:624)
    at e.openView (file:///C:/Users/Matt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5332:168)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Expected result:**
Since this is technically how it's supposed to work, just catch and ignore the exception. Alternatively, don't trigger a fake `onDidChangeTextEditorSelection` event, but that wouldn't solve similar cases.

VS Code version: Code - Insiders 1.44.0-insider (2f3fe9c9c36f935ec83113ef749d1a62ff7d07b6, 2020-03-11T20:45:29.164Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.1
vscode-icon-theme|jtl|1.6.6
material-theme|zhu|3.2.3

</details>

**Comment by alexr00** [comment]
@mattacosta is there more to that stack trace? Is it possible for you to handle the failed reveal in your extension?

**Comment by mattacosta** [comment]
Nope, that's the entire stack trace, and yes is possible to chain a rejection callback that silently ignores the problem. Adding that to every `reveal()` that could potentially cause the issue isn't ideal though.

**Comment by alexr00** [comment]
As you say adding a rejection callback to every `reveal()` that could end up like this isn't ideal, but the contract of `reveal()` is that the view will be revealed. If it isn't revealed, the extension should know that (by the exception).

**Comment by mattacosta** [comment]
I disagree. If the `reveal()` method can fail by design, then in practice, the contract is only that it will *attempt* to reveal a view (and the result should just be returned instead). Furthermore, if an extension really needs to know the state of the view after calling `reveal()` in its current implementation, then it is already possible for the extension to re-check the `visible` property, making the exception pointless.
