### ISSUE TITLE
Markdown preview window not sync when scroll

### ISSUE THREAD

**Issue by lin2code** [microsoft/vscode#92537]
Issue Type: <b>Bug</b>

1. open some md files and preview window.
2. close vs code.
3. open vs code.
4. the default open md window and preview window are not scroll sync .
5. close file, open it again, then normal.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vue-snippets|hol|0.1.11
python|ms-|2020.2.64397
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by mjbvz** [comment]
I can't repo this. How are you opening the markdown file? Is it part of a workspace?

**Comment by 631320085** [comment]
It's part of a workspace.
1. close all open windows.
2. open an md file and open preview window.
3. scroll up some distance.
4. close vs code.
5. open vs code.
It's kind of by chance, but by doing this, mostly you can see the preview window is at the start position and md file remain the position, then it's lost sync.
step3 is important.
![QQ截图20200319183437](https://user-images.githubusercontent.com/4160160/77059308-af85ef00-6a11-11ea-9bc6-336f410f6540.png)

**Comment by mjbvz** [comment]
This should be fixed in insiders

If there's a specific case that isn't working, please share a file to reproduce this and steps to reproduce the issue
