### ISSUE TITLE
Reset VS Code to default

### ISSUE THREAD

**Issue by StefanMoore** [microsoft/vscode#92533]
Issue Type: <b>Feature Request</b>

Is there a way to reset VS Code to it's default settings without having too reinstall my entire OS? 

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by MatiasOlivera** [comment]
You can set the value of `settings.json` as an empty JSON:

```
{}
```
