### ISSUE TITLE
Format document doesn't use space and tab settings

### ISSUE THREAD

**Issue by znarkd** [microsoft/vscode#92535]
Issue Type: <b>Bug</b>

In Preferences/Settings, I set the Editor: tab size setting to 2 and the Editor: Insert  Spaces setting to checked.  When selecting "Format Document" neither of those settings is used.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (27.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-hexdump|sle|1.7.2

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by znarkd** [comment]
Expected behavior:  When the Insert Spaces setting is checked, format document will not insert tabs for indenting, only spaces.  When tab setting size is set to 2, format document will use 2 spaces rather than 4 spaces when indenting.

**Comment by jrieken** [comment]
All formatting is done through extensions. Since you don't tell me in what language (and with what file) this happens, I am assuming this isn't any of the built-in extensions.

**Comment by znarkd** [comment]
I am editing HTML, JavaScript, and CSS files.  I believe that the built-in extensions are used for those types of files.

It appears that the user setting for Editor: Detect Indentation affects how indentation is performed during "Format Document."  When unchecked, my tab size settings are used during formatting.  When I thought there was a problem, this setting was checked.

Sometimes as a developer, one will receive requests from layman users.  One shouldn't expect them to be knowledgeable about the inner workings of a program.  Part of your job as a developer is to interpret those ill-defined requests into working requirements, or to point the user to relevant documentation.  :)
