### ISSUE TITLE
search result automatically collapse failed

### ISSUE THREAD

**Issue by cnjeffliu** [microsoft/vscode#92549]
Issue Type: <b>Bug</b>

My vscode config the item "Search: Collapse Result" to auto.
But it had no effection.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
Works for me. What are you expecting to happen, and what actually happens?
