### ISSUE TITLE
Fold bug

### ISSUE THREAD

**Issue by vacheli** [microsoft/vscode#92541]
- VSCode Version: 1.43.0
- OS Version: Mac 10.15.2 (19C57)

Steps to Reproduce:

1. abc.conf
```
location /abc {
# comments
# if ($a -eq $b) {
#    aaa
#}
    #if ( $a -eq $b ){
    #  aaa
    #}
}
```
2.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/5040231/76488303-f9923200-645f-11ea-82a9-cba49677cad7.png">
<img width="229" alt="image" src="https://user-images.githubusercontent.com/5040231/76488330-0b73d500-6460-11ea-881c-5466a6dde23f.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
What you see it the default folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

For some file types we also have language aware folding. For that you need a language extension that provides a folding provider. I 'm not aware of one for shell script, but you can check the Extension Marketplace.
