### ISSUE TITLE
function jsdoc blocks interface and namespace and other issues

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#9254]
Likely tsc error?
VSCode: 1.3.1
ts: 2.1.0-dev.20160712

```ts
/**
 * some function
 */
function foo() {}

/**
 * some interface
 */
interface foo {}

/**
 * some namespace
 */
namespace foo {}
```
![image](https://cloud.githubusercontent.com/assets/3254987/16831061/bf2d9fb8-4957-11e6-96aa-3a812926abe0.png)

It works like this when it is variable:
```ts
/**
 * some variable
 */
let foo: any;

/**
 * some interface
 */
interface foo {}

/**
 * some namespace
 */
namespace foo {}
```
![image](https://cloud.githubusercontent.com/assets/3254987/16831159/36418826-4958-11e6-8b98-0690f31767b9.png)

![image](https://cloud.githubusercontent.com/assets/3254987/16831083/da1d098a-4957-11e6-874c-51e4c0c4a364.png)

The highlighting is also wrong for interface, and interface is hidden when hovering variable and namespace.

**Comment by unional** [comment]
For fun:
![image](https://cloud.githubusercontent.com/assets/3254987/16893380/0f05e4e8-4aeb-11e6-95bb-6186b6d02e21.png)

Notice this only happens on Windows to me. OSX is working fine. Both on `typescript@beta = 2.0.0`

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10091
