### ISSUE TITLE
Source control doesn't  working only showing files

### ISSUE THREAD

**Issue by PratikMMohite** [microsoft/vscode#92544]
Issue Type: <b>Bug</b>

After updating to newer version of VSCode 1.43.0 the source control window only shows the file name but on clicking on the file doesn't  opening any file also by right click options only display but won't work any option.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
csharp|ms-|1.21.14
cpptools|ms-|0.26.3
vscode-typescript-tslint-plugin|ms-|1.2.3
awesome-flutter-snippets|Nas|2.0.3
vscode-scss-formatter|sib|1.4.3
vscode-echarts-extension|sus|0.1.2

</details>

**Comment by joaomoreno** [comment]
Can you reproduce with `code --disable-extensions`?
