### ISSUE TITLE
F12 navigation definition cannot be used

### ISSUE THREAD

**Issue by x102549** [microsoft/vscode#92543]
In JS file, F12 navigation definition cannot be used, Vue syntax cannot be recognized

**Comment by x102549** [comment]
`var $vue = new Vue({
    el: '#vue-j',
    data: {
        message: 'Hello',
    },
    methods: {
        toTest: function () {
            var _this = this;
            _this.message = "ces";
        }
    }
})`

**Comment by mjbvz** [comment]
Please share a complete code sample and describe where you are trying to use f12

/needsMoreInfo
