### ISSUE TITLE
Cannot copy text from extension details page using keyboard shortcuts

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/vscode#92545]
Issue Type: <b>Bug</b>

When I click on an extension in the marketplace, I am unable to copy any text from the extension details screen using keyboard shortcuts on my Mac. However, going to the Edit menu and choosing Copy copies text to the clipboard correctly.

VS Code version: Code - Insiders 1.44.0-insider (1df23554b2e3d5f1efc6fbc76ee61d3f7f186c6d, 2020-03-12T05:29:05.555Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_1208615|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Hey @JacksonKearl, can you take a look at the bot

**Comment by JacksonKearl** [comment]
@mjbvz my bad, duplicates still needs to run on the old bot. Fixed with  ce5506487379e897f208b4afed1939449514361d

**Comment by wyattbiker** [comment]
I have same problem as original poster. Cannot copy from the details text of an extension using cmd+c, but have to use the menu > Edit > Copy.

```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Thanks

**Comment by smithjosh115** [comment]
I would like to take a look at resolving this. Are there any specific files I should be looking into?

**Comment by mjbvz** [comment]
Duplicate of #86658
