### ISSUE TITLE
compare untitled files: title

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#92556]
- VSCode Version: 1.43.0
- OS Version: macOS 10.15.3

When I compare two untitled files, it's hard to identify in "open editors" now.

<img width="744" alt="2" src="https://user-images.githubusercontent.com/11925432/76505722-e6458d80-6484-11ea-9d51-9a12192c3cc2.png">
 

For example : in old version of VScode, the title is "Untitled1 <-> Untitled2", now it's "2".

"Untitled1 <-> Untitled2" or "1 <-> 2" both are OK, but "2" is hard to distinguish from normal editors.

**Comment by bpasero** [comment]
I pushed a fix to restore how the label used to be for diff editors when untitled are involved. 

![image](https://user-images.githubusercontent.com/900690/76600336-028a0e80-6507-11ea-9d59-e372bf83cf18.png)
