### ISSUE TITLE
Unable to open folders in explorer

### ISSUE THREAD

**Issue by t34rus** [microsoft/vscode#92558]
- VSCode Version: 1.43.0
- OS Version: Catalina 10.15.3 (19D76)

Steps to Reproduce:

1. goto any folder and type "code ."
2. you see No Folder Opened Tab with Open Folder buttons (but i expect list of files in current folder)
3. Press Open Folder and choose any folder
4. vscode restarts and i see No Folder Opened tab (but i expect list of files) 

Does this issue occur when all extensions are disabled?: Yes

==> Installing Cask visual-studio-code
==> Moving App 'Visual Studio Code.app' to '/Applications/Visual Studio Code.app'.
==> Linking Binary 'code' to '/usr/local/bin/code'.
🍺  visual-studio-code was successfully installed!

Reinstall from Brew - still not working (( 

Short video - https://yadi.sk/i/RASpEeXGTbohKw

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by t34rus** [comment]
> Thanks for filling this issue. I can not reproduce this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

`brew cask instal  visual-studio-code-insiders`
`brew cask instal visual-studio-code`
and 
`code .`  - not works
`code-insiders .` - works fine

small video - https://yadi.sk/i/NU1MXZs8OjGymA

**Comment by isidorn** [comment]
If it works with vscode insiders than it is fixed in latest, or you are using some extension which breaks this flow.
Please either use vscode insiders or try to find what extension breaks this.
Either way closign this issue. Thanks

**Comment by t34rus** [comment]
> If it works with vscode insiders than it is fixed in latest, or you are using some extension which breaks this flow.
> Please either use vscode insiders or try to find what extension breaks this.
> Either way closign this issue. Thanks

`code . --disable-extensions` not works

This is not extension problems

**Comment by isidorn** [comment]
Well if you can not reproduce with vscode insiders that means this is fixed with latest out of master.
@aeschli @bpasero if you might have ideas on potential regression with opening vscode
