### ISSUE TITLE
shortcut save ( ⌘ + S ) osx doesn"t work on Catalina 10.15.3

### ISSUE THREAD

**Issue by AurelienConil** [microsoft/vscode#92557]
- VSCode Version: 1.43.0
- OS Version: 10.15.3

Steps to Reproduce:

1.  ⌘ + S doesn't work
2. ALT +⌘ + S ( save all ) works ! 

Does this issuvse occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
@AurelienConil does File -> Save from the menu bar work?

**Comment by AurelienConil** [comment]
@rebornix  : Yes it works

I realized today, that randomly (⌘ + S ) works. I am looking for how to reproduce properly the issue and the non-issue.

**Comment by rebornix** [comment]
@AurelienConil could you please check next time when it stops working, open Keybindings Editor, turn on recording mode, and then type CMD+S to see if `CMD+S` is recorded. If not, it means it's hijacked by other applications.
