### ISSUE TITLE
Search Editor: Focus on editor with keyboard

### ISSUE THREAD

**Issue by franciscolourenco** [microsoft/vscode#92567]
After searching in the search editor search box, I would like to be able to press the down key, and have the caret focus on the editor. 

I couldn't find a keyboard shortcut to do this.

**Comment by ArturoDent** [comment]
F4 : `search.action.focusNextSearchResult` will take you from the search editor input box to the first result and then next, next, next.  Rebind if you want the downarrow instead:

     {
      "key": "down",
      "command": "search.action.focusNextSearchResult",
      "when": "hasSearchResult || inSearchEditor"
    },
    {
      "key": "f4",
      "command": "-search.action.focusNextSearchResult",
      "when": "hasSearchResult || inSearchEditor"
    }

**Comment by JacksonKearl** [comment]
There's also `search.focus.nextInputBox`

**Comment by franciscolourenco** [comment]
@ArturoDent thanks. is there a way to limit this shortcut to when the focus is on the search box?

**Comment by franciscolourenco** [comment]
Tried `textInputFocus` and `inputFocus` but both seem to be false

**Comment by JacksonKearl** [comment]
{
  "key": "cmd+down",
  "command": "search.focus.nextInputBox",
  "when": "inSearchEditor && inputBoxFocus || inputBoxFocus && searchViewletVisible"
}

alternatively just modify/use the existing `focus next input`.
