### ISSUE TITLE
UI feature panel dockable or split like editors

### ISSUE THREAD

**Issue by omegaluo** [microsoft/vscode#92560]
this request is very simple to explain, some one have request similar one 3 years ago, but it still not supported in march 2020.

you may have same problem with big project in big monitor / screen which resolution >= 1920x1080.

> the problem is: **panels are fixed**, can not floating or move to free space to improve working efficiency.

![panel-dockable-request](https://user-images.githubusercontent.com/11284310/76507734-3f62f080-6488-11ea-84ed-d7669e8e3dc4.png)

**Comment by sbatten** [comment]
@omegaluo currently we are exploring more flexible layouting. Work currently being done is about moving views between the panel and sidebar as well as allowing multiple views in panel at one time. As for this request, today, the panel can be moved to the right, left, or bottom (its default).

**Comment by omegaluo** [comment]
> @omegaluo currently we are exploring more flexible layouting. Work currently being done is about moving views between the panel and sidebar as well as allowing multiple views in panel at one time. As for this request, today, the panel can be moved to the right, left, or bottom (its default).

Thank you for the response. I am very pleasure to hear this news that you have working on it and it almost done!  

Move the panel container from left to right it can not fix the panels crowded problem.  the situation is you have a office building for rent. 4th floor for company A and 5th floor for company B. but company B has too many people, it crowded.  

then you suggest company B move to 4th floor, and company A move to 5th. you know this can not solve the problem.  the real problem is company B just want move some department to company A's floor.

anyway, it's good to know that you have almost solved this problem.

Cheers!!!

have a nice day!

omega
