### ISSUE TITLE
[VSCODE:1.43.0]input type file with webkitdirectory is not working

### ISSUE THREAD

**Issue by Raghu-BV** [microsoft/vscode#92563]
- VSCode Version: 1.43.0
- OS Version: macos catalina 10.15.3

Steps to Reproduce:

[webview-sample.zip](https://github.com/microsoft/vscode/files/4323412/webview-sample.zip)
Please find attached code
1. run the sample webview extension in vscode 1.42.1  working  as expected 
below code allowing select to destination folder.
`<div class="col-80">
              <input
                type="file"
                name="exportDestination"
                webkitdirectory
                directory
                id="destination-export"
              />
            </div>`
![image](https://user-images.githubusercontent.com/24713770/76508805-ff464280-6474-11ea-98b1-c419eed76bee.png)

2. run the sample webview extension in vscode 1.43.0  not working  as expected 
below code not allowing to select destination folder but showing folder content count.
`<div class="col-80">
              <input
                type="file"
                name="exportDestination"
                webkitdirectory
                directory
                id="destination-export"
              />
            </div>`
![image](https://user-images.githubusercontent.com/24713770/76509050-5a783500-6475-11ea-99ce-ef2447ff6b1c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does that html input work as you expect it to in the latest Chrome?

**Comment by Raghu-BV** [comment]
not working as we expected in chrome (Google Chrome Version 80.0.3987.132 (Official Build) (64-bit))

Test link
https://www.w3schools.com/code/tryit.asp?filename=GCWXZ8IL5WML


<img width="1419" alt="Screenshot 2020-03-17 at 12 41 44 PM" src="https://user-images.githubusercontent.com/24713770/76831185-d9da7f80-684c-11ea-886d-790da175826c.png">

**Comment by mjbvz** [comment]
Thanks for testing. Please file an issue against Chrome for this then: https://bugs.chromium.org/p/chromium/issues/list
