### ISSUE TITLE
Using VS code with android or IOS phone

### ISSUE THREAD

**Issue by BasemSrour** [microsoft/vscode#92569]
Issue Type: <b>Feature Request</b>

Hello, everyone.
I want to ask you to have VS code for phone.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.3.0-40-generic

**Comment by rebornix** [comment]
You can try https://visualstudio.microsoft.com/services/visual-studio-online/
