### ISSUE TITLE
Search Editor: editor.action.selectAllMatches

### ISSUE THREAD

**Issue by franciscolourenco** [microsoft/vscode#92568]
The find widget has a command to select all matches.
![image](https://user-images.githubusercontent.com/208149/76512537-c1352880-644c-11ea-8db0-ce37fed7838e.png)

This is a feature request for the same command to work in the search editor.

**Comment by ArturoDent** [comment]
There is a different command for the search editor:

`selectAllSearchEditorMatches` 

you could rebind that to Alt+Enter to match the find widget command.

**Comment by JacksonKearl** [comment]
It cant be the same command as that would cause issues when you are finding within a search editor.
