### ISSUE TITLE
Maximized Panel state not persistent

### ISSUE THREAD

**Issue by vdegenne** [microsoft/vscode#92566]
When I maximized the panel and toggle it off it loses its maximized state. When I toggle it on back it is reduced to an initial size (a bit annoying).
Here's a screencast :

<img src="https://i.imgur.com/iKIQgGX.gif">

Thanks in advance for your consideration.

- VSCode Version: 1.43.0
- OS Version: Fedora (Thirty One)

**Comment by sbatten** [comment]
@vdegenne We provide a command `workbench.action.toggleMaximizedPanel` which can be bound to allow you to go directly from closed to maximized if that is your preferred workflow.
