### ISSUE TITLE
Store extensions enabled only in a workspace in the workspace settings.json

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#92575]
**Scenario**

Some extensions are only used in specific projects. For example, I use 7 specific extensions when I use 1 specific workspace. Today 

1 - I install them one by one
2 - on an extension, I right click disable
3 - right click, enable for workspace
4 - repeat steps 2 and 3 for each extension

**Challenges**

1. This takes 21 clicks to install (not including finding the extensions), disable, then enable for workspace
1. When someone on my team starts on the same project they have to do the same thing, as this information is not in workspace settings 

**Proposal**

Store workspace extensions in `.vscode/settings.json` so we can commit and push it to source control.

**Comment by johnpapa** [comment]
can you point to the duplicate?

the ones listed by the bot are not the same as this

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/69958
