### ISSUE TITLE
Variables view after execution is terminated doesn't clear itself and next the Variables view becomes unusable in next execution.

### ISSUE THREAD

**Issue by Rajsmit** [microsoft/vscode#92577]
- VSCode Version: 1.35.1
- OS Version: windows 8

Steps to Reproduce:

1. using custom debug adapter
2. when program terminates debug adapter sends Terminate Request to client.
3. when debug adapter received Disconnect request it closes the session with client.
4. before the terminate there was one variables request pending as its response was not sent.
5. once disconnect the execution stops but the variable view keeps showing loader and it never clear the loader as the response to variables request was never sent.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
This is fixed with latest vscode. You are using version 1.35 which is like a year old.
If you can reproduce with vscode insiders let us know and we can  reopen.
Thank you
