### ISSUE TITLE
Blue background when typing in the integrated console in VS Code. 

### ISSUE THREAD

**Issue by tanguyen78** [microsoft/vscode#92576]
- VSCode Version: 1.43
- OS Version: Windows 10 LTSC

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
This is due to the old backend, you should upgrade Windows 10 or try to remove customizations to cmd.exe's background color.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
