### ISSUE TITLE
A proper toolbar

### ISSUE THREAD

**Issue by XeonG** [microsoft/vscode#92573]
https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar

Something like that but better and directly supported so other addons can provide options to include icons/toggle icons/dropdown menus etc for there own extensions, as ctrl+shift+p and having to constantly type out shortcuts or setup up keybinds is just silly when a toolbar was designed for this exact usability improvement. With the ability to move it onto its own tab bar position, even better if supported in multiple areas of the gui, horizontal/vertical etc. instead of it sharing the same bar as the tabbar leaving less room for actual tabs..

**Comment by MikeRosoft** [comment]
It *is* duplicate, but the issue in question has been open and summarily ignored by developers for more than two years. (With the exception of a response by @isidorn, essentially, that a pull request introducing a toolbar wouldn't be accepted.)
