### ISSUE TITLE
Cannot run with "break on error" anymore

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#9257]
I always end up in a `throw ni()` thingy here (e.g. when switching the active editor):

![image](https://cloud.githubusercontent.com/assets/900690/16831832/6a97a246-49a7-11e6-9bf6-c03ab6456107.png)

**Comment by jrieken** [comment]
@alexandrudima I think that's a regression from the refactoring you did. I also see the JS lightbulb not going away anymore. My guess is `$dispose` vs `dispose`


![screen shot 2016-07-14 at 09 47 40](https://cloud.githubusercontent.com/assets/1794099/16831935/1af1af42-49a8-11e6-9b5d-d1684edfc995.png)

**Comment by alexandrudima** [comment]
I renamed all of those with `F2`...

**Comment by alexandrudima** [comment]
yes, `F2` fails to rename correctly `dispose` to `$dispose`. It renames the call site but not the overwritten method

**Comment by jrieken** [comment]
😱

**Comment by alexandrudima** [comment]
@jrieken pushed a fix -- I can still repro the rename fail - go to extHostProtocol.ts on `MainThreadStatusBarShape.$dispose` and rename to `dispose`.  `MainThreadStatusBar.dispose` is not renamed. I am thinking that maybe other renames have failed too, and opting to remove the `extends` again

Thoughts?
