### ISSUE TITLE
Add terminal path heading

### ISSUE THREAD

**Issue by dillingham** [microsoft/vscode#92578]
Imagine having 3 terminal panels open (side by side) with `npm --watch`
Quickly becomes hard to know which panel is for which folder within the workspace.
Some sort of 20px high heading with some sort of path identifier would be great.

![Screen Shot 2020-03-12 at 9 55 22 AM](https://user-images.githubusercontent.com/29180903/76528795-bdeb6e00-6447-11ea-9861-65f444e5d867.png)

For background: 

I have a `/frontend` `/web-app` & `/electron`
Changes to `/frontend` get synced to `/web-app` and `/electron`
So its not a very obscure use case :)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/29816, https://github.com/microsoft/vscode/issues/10546

**Comment by dillingham** [comment]
@Tyriar @rebornix this isn't a duplicate of the 6 yr old issue. 
I just was suggesting a panel heading
