### ISSUE TITLE
SSH error in VSCode: Permission denied, please try again.

### ISSUE THREAD

**Issue by b-atlas** [microsoft/vscode#92579]
- VSCode Version: 1.43.0
- OS Version: Windows 10

I want to access a remote `VM` with `Remote - SSH` extension from a Windows 10 machine. But I don't seem to succeed as `VSCode` is keeping prompting me to enter the password and deny the access each time. The `VM` runs on a `Ubuntu 18.04 LTS OS`.

I generated a `ssh key` for authentication and that's how I am able to acces the `VM `from the command line with a `ssh` client.

Steps to Reproduce:

1. I access normally the remote `VM` from `MobaXterm`.
2. I generate a `ssh key` in my `windows 10` computer.
3. I Install the public key in the remote server.
4. I make sure that I can access the `VM `from the command line and it works fine.
5. I install the `Remote - SSH` extension on `VSCode`.
6. Press `F1` > search and click `Remote-SSH: connect to a host` > execute command `ssh username@ipaddress`
7. `VSCode` launch a new instance and prompt me for the password of `username@ipaddress`.
4. I enter the password, and it prompts for the same reason with a message: `Permission denied, please try again.`

This is the output on `VSCode`:
```
[15:59:33.542] Showing password prompt
[15:59:33.543] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-d9c3e8222ce4d3d9ee41d8ec1b64bb868ac4183c-sock
[15:59:33.543] Writing password prompt to globalState
[15:59:46.762] Got password response
[15:59:46.763] Interactor gave response: *****
[15:59:46.763] Cleaning up other-window auth server
[15:59:48.746] stderr> Permission denied, please try again.
[15:59:48.915] Got askpass request: {"request":"ssh <username>@<ipaddress>'s password: "}
[15:59:48.916] Showing password prompt
```

This issue occur even when all extensions are disabled.

**Comment by bjayakumar** [comment]
I have this error as well after the update.  Mine in linux machine.


Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-88-generic

**Comment by b-atlas** [comment]
Here is how I managed to connect to the remote `VM`:

1. Access normally the remote `VM` from `MobaXterm` or other `ssh client` to verify it's working.
2. Generate a `ssh key`:
`ssh-keygen -t rsa`
3. Install the public key in the remote server:
`ssh-copy-id -i $HOME/.ssh/id_rsa.pub <username>@<ipaddress>`
4. Make sure that you can access the `VM` from the command line using `ssh`.
5. Install the `Remote - SSH` extension on `VSCode`.
6. Press `F1` > search and click `Remote-SSH: connect to a host` > click `Add New SSH Host`
7. Write `ssh <username>@<ipaddress>` and press Enter.
8. Choose the config file generated with the `ssh key`.
9. You can now connect to the `remote server`.

That should do it, so I am going to go ahead and close the thread.
