### ISSUE TITLE
Duplicate extensions after creating new files while updating them

### ISSUE THREAD

**Issue by OshotOkill** [Microsoft/vscode#9258]
- VSCode Version: 1.3.1
- OS Version: win10-x64-10586.420

Steps to Reproduce:

1.  Switch to `Extension` tab on the left
![1](https://cloud.githubusercontent.com/assets/6079112/16832247/08a3858e-49dc-11e6-9ae5-2a4a70d221ac.PNG)

2.  Click to update some extensions
![2](https://cloud.githubusercontent.com/assets/6079112/16832255/0d04f4aa-49dc-11e6-8411-9bccf833f70b.PNG)

3.  Switch to `Explorer` tab and add some new files
![3](https://cloud.githubusercontent.com/assets/6079112/16832259/107fe928-49dc-11e6-811a-7301a55e4a57.PNG)

4.  Switch to `Extension` tab again and duplicate extension will show on the bottom
![4](https://cloud.githubusercontent.com/assets/6079112/16832265/13bcf356-49dc-11e6-83fa-0e9b8cdc9f18.PNG)

**Comment by bpasero** [comment]
Wow 👍

**Comment by joaomoreno** [comment]
#8795
