### ISSUE TITLE
Discard Changes on unstaged file will abort the current merge

### ISSUE THREAD

**Issue by maslade** [microsoft/vscode#92587]
Issue Type: <b>Bug</b>

These steps may be more specific than they need to be, but they're what I was following:

1. From a clean working directory, merge changes from another branch that produce a conflicted file.
2. Note that 'git status' reflects that you are currently in the middle of a merge.
3. Add the conflicted file to the staging area so all conflicts appear resolved.
4. Make another change to the conflicted file, so it is reflected as an unstaged change.
5. Click the "Discard Changes" button on the unstaged file to revert the change you made in step 4.

Expected behavior: I should be back where I was at the end of step 3 -- with my unstaged change removed, but still in a merging state.

Actual behavior: The unstaged change is correctly removed, but 'git status' reflects that I am no longer merging. I am unable to complete the merge without restarting it from the beginning.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (14.68GB free)|
|Process Argv|--file-uri file:///c%3A/Users/slademar1/workspaces/sitecore.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.3.3
xml|Dot|2.5.0
gitlens|eam|10.2.1
todo-tree|Gru|0.0.169
azure-pipelines|ms-|1.165.1
vscode-azureappservice|ms-|0.16.3
vscode-azurefunctions|ms-|0.21.0
vscode-azurestorage|ms-|0.8.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.13
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
powershell|ms-|2020.3.0
vscode-node-azure-pack|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.1736
azurerm-vscode-tools|msa|0.8.4
gulptasks|nic|1.3.1
vscode-scss-formatter|sib|1.4.3

</details>

**Comment by joaomoreno** [comment]
I can't reproduce. When I run `git status` after step 5 I get:

```
➜  fakeproject git:(master) ✗ git status
On branch master
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

        modified:   file.txt
```

Notice the `All conflicts fixed but you are still merging.`.
