### ISSUE TITLE
vscode unresponsive using remote-ssh editing c++ win10 to ubuntu

### ISSUE THREAD

**Issue by nhorlock** [microsoft/vscode#92588]
Issue Type: <b>Performance Issue</b>

Not sure if this is the same as issue #92229, but since the most recent update I am seeing regular cases of the windows-side vscode becoming unresponsive and consuming high CPU. 

There seems to be no specific trigger :-( 

A prompt will appear sooner or later suggesting to re-open the app (or wait), waiting does not seem to help.

I am working using remote ssh on an Ubuntu Linux server (that is sat next to me on the same LAN) 
running top on the server-side shows no CPU usage for the code instance and there is no apparent network issue as XWindows processes such as Gitkraken are operating quite happily throughout. 

I have only seen this since the update to 1.43 so I am wary of saying this is the same problem as the issue noted above but it seems to be manifesting in the same way.

Neil

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-88-generic
Remote OS version: Linux x64 4.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: babbage|
|OS|Linux x64 4.15.0-88-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 800)|
|Memory (System)|31.28GB (20.78GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: babbage|
|OS|Linux x64 4.15.0-88-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 800)|
|Memory (System)|31.28GB (20.78GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	 13808	code main
    0	   134	  3288	   gpu-process
    0	    12	  4180	   electron-crash-reporter
    0	    25	 11348	   utility
    0	    73	 12576	   shared-process
    0	   180	 15232	   window (pcapMatch.cpp - stac-ts-framework [SSH: babbage] - Visual Studio Code)
    0	    35	 17872	     extensionHost
    0	    68	 36396	   window (Issue Reporter)
    0	   231	 37108	   window (fixfactory.cpp - order-router (Workspace) [SSH: babbage] - Visual Studio Code)
    0	    74	 38656	     extensionHost

Remote: SSH: babbage
CPU %	Mem MB	   PID	Process
    0	     0	  5562	remote agent
    0	     0	  5767	   extensionHost
    0	     0	  5873	     clangd --clang-tidy --completion-parse=always --completion-style=bundled --header-insertion=iwyu --header-insertion-decorators -j=4 --suggest-missing-includes --clang-tidy-checks=*,-fuchsia-*,-modernize-use-trailing-return-type, -google-global-names-in-headers, -modernize-use-trailing-return-type --compile-commands-dir=${workspaceFolder} --log=verbose
    0	     0	  5905	     /home/neil/.vscode-server/extensions/ms-vscode.cpptools-0.27.0-insiders2/bin/cpptools
    0	     0	 13183	       /home/neil/.vscode-server/extensions/ms-vscode.cpptools-0.27.0-insiders2/bin/cpptools-srv 5905 26
    0	     0	  6135	     /home/neil/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node /home/neil/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5767
    0	     0	  6996	     /home/neil/.vscode-server/extensions/ms-python.python-2020.2.64397/languageServer.0.5.31/Microsoft.Python.LanguageServer
    0	     0	  5788	   watcherService
    0	     0	 32622	   watcherService

Remote: SSH: babbage
CPU %	Mem MB	   PID	Process
    0	     0	  5562	remote agent
    0	     0	  5767	   extensionHost
    0	     0	  5873	     clangd --clang-tidy --completion-parse=always --completion-style=bundled --header-insertion=iwyu --header-insertion-decorators -j=4 --suggest-missing-includes --clang-tidy-checks=*,-fuchsia-*,-modernize-use-trailing-return-type, -google-global-names-in-headers, -modernize-use-trailing-return-type --compile-commands-dir=${workspaceFolder} --log=verbose
    0	     0	  5905	     /home/neil/.vscode-server/extensions/ms-vscode.cpptools-0.27.0-insiders2/bin/cpptools
    0	     0	 13183	       /home/neil/.vscode-server/extensions/ms-vscode.cpptools-0.27.0-insiders2/bin/cpptools-srv 5905 26
    0	     0	  6135	     /home/neil/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node /home/neil/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5767
    0	     0	  6996	     /home/neil/.vscode-server/extensions/ms-python.python-2020.2.64397/languageServer.0.5.31/Microsoft.Python.LanguageServer
    0	     0	  5788	   watcherService
    0	     0	 32622	   watcherService
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: babbage
|  Remote: SSH: babbage|    Folder (stac-ts-framework): 1201 files|      File types: cmake(104) make(88) idx(78) tex(70) txt(60) py(56) json(49)
|                  h(40) o(38) cpp(29)
|      Conf files: cmake(104) makefile(24) launch.json(1) settings.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
sourcetrail|ast|0.0.2
doxdocgen|csc|0.5.2
gitlens|eam|10.2.1
cmake-test-adapter|fre|0.5.0
todo-tree|Gru|0.0.169
vscode-test-explorer|hbe|2.17.0
vscode-gist|ken|3.0.3
vscode-clangd|llv|0.0.21
vscode-catch2-test-adapter|mat|2.8.8
vscode-docker|ms-|1.0.0
vscode-language-pack-en-GB|MS-|1.43.6
python|ms-|2020.2.64397
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0-insiders2
cmake|twx|0.0.17
better-comments|aar|2.0.5
blender-python-code-templates|ble|0.9.6
lsl-fp|Dal|1.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
better-cpp-syntax|jef|1.14.24
vscode-docker|ms-|1.0.0
vscode-language-pack-en-GB|MS-|1.43.6
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
material-icon-theme|PKi|4.0.1
code-settings-sync|Sha|3.4.3
discord-js-boilerplate|sir|0.0.2

(2 theme extensions excluded)

</details>

**Comment by nhorlock** [comment]
OK, so a little more data, nothing concrete in terms of a repro BUT...
It tends to be happening when some form of IntelliSense or similar popup/query is being executed

Here is an example of one in "action"
![image](https://user-images.githubusercontent.com/2581250/76665336-47ea2280-657f-11ea-8826-04b2bff26a8a.png)

the code.exe instance on this machine will now sit there consuming what shows up as 12.5% CPU (it's an 8 core machine so I'm guessing it's pegging a core in reality even though that is not showing in CPU tools, it may be coincidental number though)

**Comment by roblourens** [comment]
Hm, I'm not sure what to ask. vscode processes do not seem to be using high CPU or memory, as would often be the case. How often do you see this?

Do you use local vscode windows in your workflow and do you ever see it there, or only remote? If you do see it in a local window, I would ask you try launch vscode with the `--disable-extensions` flag and using that for a little while to check whether that helps. That won't work for a remote window.

**Comment by nhorlock** [comment]
I think it is using high CPU, I think it is masked by the 8 cores and shows as less overall. I'll dig deeper on that next time I see it. 

I have not been using any local windows, but I have a windows c++ project I can work on over the next few days so that will perhaps help. I'll update when I have something useful to add. Thanks and have a great weekend

**Comment by roblourens** [comment]
At least in the details in the original post, all processes are showing 0% CPU, but you can run `code --status` when the issue happens again to collect the info again.

**Comment by nhorlock** [comment]
Do you think the report #92369 matches what I was seeing? It sounds plausible. I've updated to 1.43.1 If I don't update this again I think it is safe to assume it was the same/similar root cause.

**Comment by roblourens** [comment]
It's possible! Let me know if you see it again.
