### ISSUE TITLE
Relative Filepath Rewriting

### ISSUE THREAD

**Issue by Ngranger** [microsoft/vscode#92589]
In Dreamweaver, when you save a file to a new folder it offers to do an automatic rewrite on any relative file paths so they would still point to the same locations.

**Example scenario below:**

/ Site Root / templates / generic.html
/ Site Root / media / header.jpg
/ Site Root / pages / people / forename_surname.html

If you open **"generic.html"** and then save it to **"/pages/people"** with some person's name but the file paths needs changed so the image source in **"generic.html"** pointing to **"../media/header.jpg"** needs to be adjusted to **"../../media/header.jpg"** in order to still work properly (_while you can do this manually, it is an annoyingly repetitive task_).

Adding a feature like this would greatly help reduce the chances of an error 404 for a website due to incorrect file paths or for modules in a javascript file, just to name a couple of examples.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
