### ISSUE TITLE
Fulltext search extremely slow. Extremely.

### ISSUE THREAD

**Issue by mifrdlik** [microsoft/vscode#92584]
Issue Type: <b>Bug</b>

Fulltext search extremely slow. Extremely.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
markdown-mermaid|bie|1.4.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.1
githistory|don|0.6.2
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
graphql-for-vscode|kum|1.15.3
python|ms-|2020.2.64397
powershell|ms-|2020.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
markdown-preview-enhanced|shd|0.5.2
mdx|sil|0.1.0
alphabetical-sorter|ue|2.0.1

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@mifrdlik did you see the slowness only on 1.43?
