### ISSUE TITLE
不能直接通过拖拽文件夹打开项目

### ISSUE THREAD

**Issue by jackYin888** [Microsoft/vscode#9259]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.不能直接通过拖拽文件夹打开项目
2.

**Comment by weinand** [comment]
bing translate:
"Cannot open the project by dragging a folder"

Opening a project by dragging a folder works on OS X but not on Window (I believe).

**Comment by bpasero** [comment]
This was fixed for July on all OS.
