### ISSUE TITLE
No response in use for a while

### ISSUE THREAD

**Issue by Njup** [microsoft/vscode#92596]
Issue Type: <b>Bug</b>

1.When I open vscode and run it in the background for a while,  then I switch it to the top.At this time I want scroll through my code, It's not responding for a long time ..
2.When I trying to adjust the window size of vscode, I see a translucent window above the vscode window, and this translucent window is bigger than vscode window. Then I ignored it and continued to resize the window, at this time, vscode is not responding for a short time.
English is not my native language, so my expression may not be clear enough.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17
vscode-language-pack-zh-hans|MS-|1.43.7
python|ms-|2020.2.64397
cpptools|ms-|0.26.3

</details>

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?
