### ISSUE TITLE
XML autocomplete closing tag cursor always goes to the end

### ISSUE THREAD

**Issue by artmasa** [microsoft/vscode#92595]
Issue Type: <b>Feature Request</b>

When auto-completing closing tags suggested by the editor I would expect the  cursor to remain between the opening and the closing tags in order to add content to the element since adding the closing tag means it's not an empty element.
Currently the cursor is moved to the end of the closing tag and me having to move back between tags to add content.
Can this be configured anywhere?

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.19564

**Comment by octref** [comment]
Please report this to the XML extension you are using.

**Comment by artmasa** [comment]
@octref what is the default XML extension installed on VSCode? I have not installed any XML extension. This is the default behavior I get when using the editor.

**Comment by octref** [comment]
Can you run "Developer: Toggle Screencast Mode" and record a gif?

Here's what I see before completion:

![image](https://user-images.githubusercontent.com/4033249/76891970-1e631c80-6847-11ea-9972-3a85326a964f.png)

And after, where cursor is between the two tags

![image](https://user-images.githubusercontent.com/4033249/76891980-2327d080-6847-11ea-8f9d-d081f3ffa278.png)

**Comment by artmasa** [comment]
The case you present here works perfectly fine. Using HTML tags behaves just as you are showing in these images. I'm not editing HTML. I'm working with XML files.
If I enter a tag for example `CustomElement` without the opening brackets I dont get the opening and closing tag.
The case I'm talking about is when I have `<CustomElement attribute="value"`, When closing the opening tag with `>` I'm presented the suggestion `</CustomElement>` which I love but instead of leaving the cursor in the current position (`...="value">|</CustomE...` before the closing tag) the cursor gets moved to the end of the closing tag (`..."value"></CustomElement>|`)

**Comment by artmasa** [comment]
I don't think this issue should be closed since it's not caused by an extension

**Comment by octref** [comment]
I don't see that either. Have you tried disabling all extensions?

![Kapture 2020-03-17 at 12 50 46](https://user-images.githubusercontent.com/4033249/76895848-03e07180-684e-11ea-912b-a2ddd2f405b3.gif)

**Comment by artmasa** [comment]
@octref, now try to do the same in a file with .xml extension, I'm not working with HTML files

**Comment by artmasa** [comment]
VSCode needs to bring all the HTML fancy stuff to XML

**Comment by octref** [comment]
> now try to do the same in a file with .xml extension,

When I do it in XML, there's no auto closing. If you have auto-closing, that means you are using an XML extension. Report bugs to them.

> VSCode needs to bring all the HTML fancy stuff to XML

No, we maintain a stable core and leave the fancy stuff to extensions.

**Comment by artmasa** [comment]
are you using an HTML extension? What you showed me on HTML works on mine without extension. Why isn't the same HTML stable core (fancy) functionality available for XML?
Again for XML it's not auto closing. I'm given the suggestion to auto-close which I'm pretty sure is the same behavior you get.

**Comment by artmasa** [comment]
@vscode-triage-bot reopen this issue

**Comment by octref** [comment]
That feature is offered to you by https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml. In fact just after installing the extension I get the auto closing behavior, and it's working fine for me. After I uninstall there's no support.

![xml](https://user-images.githubusercontent.com/4033249/76898551-29bc4500-6853-11ea-9d8f-7e60307a13cb.gif)

There's no code I can change in microsoft/vscode to fix your bug.

**Comment by artmasa** [comment]
Thank you! I like your recommendation for XML
