### ISSUE TITLE
Theme's Color changed by itself randomly 

### ISSUE THREAD

**Issue by mostafaabobakr7** [microsoft/vscode#92591]
**Theme color is changed after update to v1.43 !!**
On vscode start colors are "Before" ✔
After 2 seconds  changes to "After" ❌

- VSCode Version: 1.43
- OS Version: Win10 pro1909 

![image](https://user-images.githubusercontent.com/27288406/76549780-a937c600-6499-11ea-8c2a-40e269e7d948.png)

**Comment by elramus** [comment]
This is happening for me too. Persists even when all extensions are disabled. Upon reloading the window the highlighting is correct for a few seconds, and then the moment "Initializing JS/TS Language Features..." finishes, the highlighting gets all messed up.

**Comment by ArturoDent** [comment]
/duplicate of #90379

As a workaround you could disable semantic highlighting

**Comment by mostafaabobakr7** [comment]
@ArturoDent 

> As a workaround you could disable semantic highlighting

Could you please Show How ?

**Comment by ArturoDent** [comment]
Disable 

> Editor > Semantic Highlighting : Enabled

in your settings.

**Comment by gjsjohnmurray** [comment]
Ongoing discussion is on #92308
