### ISSUE TITLE
Razor file language mode on WSL: Ubuntu-18.04

### ISSUE THREAD

**Issue by ofrades** [microsoft/vscode#92592]
- VSCode Version: 1.44.0-insider
- OS Version: Windows 10 19041.113

Steps to Reproduce:

1. Open WSL Ubuntu-18.04 Remote Window
2. Open razor file

The problem is that the only language mode available to razor files is Razor and not the regular auto detection mode of macos and windows aspnetcorerazor.

With Windows and Mac the two options are available but not in the Distro.

**Comment by aeschli** [comment]
The rich razor support comes from the C# extension. Please file the issue there. https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

**Comment by ofrades** [comment]
Thanks, I did not noticed that the C# extension had to be installed in WSL because I had it in my Windows already.

![image](https://user-images.githubusercontent.com/31070771/76618666-09257f80-6521-11ea-96e4-434f496a9a6e.png)
