### ISSUE TITLE
Icons for dynamic views

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#92590]
## Overview
This issue is to identify what icons we use for dynamic sidebar views. Views can be moved into the panel, sidebar, and activity bar. When views are in the activity bar, we'll need to decide which icons we use and what the default is when there are no icons defined (extensions will be able to define a custom icon).

## Out of scope
Allowing users to select an icon

## Current Proposal
![image](https://user-images.githubusercontent.com/35271042/76548957-cc885400-644c-11ea-85fa-8d7e0d3dbf24.png)

**Comment by misolori** [comment]
Feedback from the Redmond team:

1. Problems ✅
2. Output: first icon is preferred
3. Debug console ✅
4. Terminal ✅
5. Custom Views: indifferent, last one looks similar to extension icon (might cause confusion?)

**Comment by Tyriar** [comment]
@misolori some thoughts:

- Output: First one says clipboard to me, I prefer the second as it kind of communicates (log) book. Still not the strongest association though.
- Terminal: Could we try a box outline similar to debug console as well to see how that looks?
- Custom views: First one means package or method to me, we also already use it
   <img width="169" alt="Screen Shot 2020-03-17 at 2 16 14 PM" src="https://user-images.githubusercontent.com/2193314/76902747-e31e1900-6859-11ea-9380-18ec74992524.png">

**Comment by misolori** [comment]
@Tyriar here's the console version for comparison and a few others for custom views:

![image](https://user-images.githubusercontent.com/35271042/76911177-6137eb00-686d-11ea-89a6-a44991d533ee.png)

**Comment by misolori** [comment]
Here's the proposed icons after the last round of feedback:

![image](https://user-images.githubusercontent.com/35271042/77440846-012dd100-6da6-11ea-8077-01403ec61a1b.png)

**Comment by Tyriar** [comment]
@misolori looks fantastic!

By the way this is what I was trying to describe as an alternative for custom views:

![image](https://user-images.githubusercontent.com/2193314/77444637-57504380-6da9-11ea-921c-70d230d4a5e2.png)

The view would show the first for 1 view, second for 2 and third for 3+. If there ended up being a bunch of these then it might be easier to differentiate? Might also be trying to solve a problem that doesn't exist 😄

**Comment by misolori** [comment]
I like that idea, but I agree that it might be a bit overkill (esp. if you have lots of views w/ more than 3). I do like the "dynamicness" of the icon though 👌

**Comment by regs01** [comment]
Most important icon is missed - Outline

**Comment by misolori** [comment]
@regs01 please see https://github.com/microsoft/vscode/issues/93964#issuecomment-606855048
