### ISSUE TITLE
Manipulating on-the-go 🏃‍♂️️

### ISSUE THREAD

**Issue by babakks** [microsoft/vscode#92594]
# Manipulating on-the-go 🏃‍♂️️

This happens to me a lot to go through other people's codes (usually in form of legacy) codes and try to understand it and then extend and/or debug their work. Whenever I'm doing this, I find myself redirect the control flow by interventions like:

* Manipulating local variables (mostly boolean flags).
* Putting fake implementation for long-running or external API-dependent methods.
* Raising unreal exceptions.
* Jumping over some lines of code (*not running to the cursor location*).

The thing is I always make sure doing these without ever actually modifying the original code. There are always risks that I forget to revert my changes and, as you've already guessed, commit-and-push my faulty version up to the remote repository. So, there'd be no recourse other than debugger tools that let me alter things on the run. The point is, I feel VS Code can still use some improvements on these kind of tools, like the brilliant one that recently was added which is "jumping over".

## Suggestions

I suggest the features below. Please note that these are not thought through needs, so I'm just trying to deliver my point. 

* Being able to add some temporary lines of code, at any point, and disable, enable, and precondition them just like breakpoints. This alone hugely facilitates code investigation and catching of bugs. *Currently there's no way to do this but to use the debug console.*
* Commenting on the run, by which some lines could be commented out for the debug session in progress. This, too, needs enable/disable/precondition functionalities. Although this seems like the jumping over feature, but the point is you wouldn't have to pause and jump the control manually every time.

## Note on feasibility

I don't really know if my requested features are feasible, or, if they are, to what extent, but the least of such functionalities like manipulating variables (even locals), which are totally feasible, would hugely help in many scenarios.

Also, I have yet to see such features in any well-known editor/IDE.

**Comment by rebornix** [comment]
Starting from Debug land @isidorn :)

**Comment by isidorn** [comment]
This is a feature request against debug. For now leaving it open and assigning to backlog.
It would be good fi the suggestion was more concise and clear what exactly should be changed

**Comment by weinand** [comment]
@babakks I do not really understand this enough to be already sure that this is a "debug feature".

For me it sounds like you are asking for some "conditional compilation" feature like the C's and C++'s preprocessor statements "#if", "#endif" etc. This feature allows you to have additional code in your programs that can easily be excluded from production code. And since the code lives in the source (and the repo), it is more likely to be up-to-date than temporary code living somewhere else.

On the other hand if you are looking for a way to have the additional code maintained by the debugger, then you could try to use "conditional breakpoints". Here you can run arbitrary code when your programs hits a breakpoint.
Have you tried that?

**Comment by babakks** [comment]
@weinand  The second interpretation is closer. To elaborate, currently, one can set breakpoints to be of either conditional or hit-count triggered or logger type. I'm, actually, talking about a _new_ type of breakpoints with which the user could add a few lines of code (in a separate box like they do in conditional breakpoints, but not limited to one expression) which automatically be executed when the control reaches the breakpoint. This let's users to intervene in execution, without actually modifying the original code base.
