### ISSUE TITLE
Can't save .htaccess file. EPERM error.

### ISSUE THREAD

**Issue by Bartmax** [Microsoft/vscode#926]
![image](https://cloud.githubusercontent.com/assets/3386797/11532938/cc4fb744-98e5-11e5-9042-ba5bda9982a8.png)

Even running vscode as administrator gives me the same error.

**Comment by bpasero** [comment]
@Bartmax This is just the native error from node, not sure what we can do here. Could it be that the file has the "hidden" flag set on Windows? We cannot save files that are hidden. I assume it is that.

**Comment by Bartmax** [comment]
Oh yes. It was because of a hidden attribute. Didn't know code can't save hidden files. Thanks.

**Comment by bpasero** [comment]
I think its a fair bug, I opened https://github.com/Microsoft/vscode/issues/931

**Comment by Karpot** [comment]
A coding tool which cant modify system and config files (for ftp server) is an EPIC FAIL. :-(
