### ISSUE TITLE
x64 large files problem

### ISSUE THREAD

**Issue by ymg2006** [microsoft/vscode#92602]
Hello,
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

I was trying to open a 1GB file in vscode with "files.maxMemoryForLargeFilesMB": 11000
but i get :
the file is not displayed in editor because its too large.

Does this issue occur when all extensions are disabled?: Yes

you mentioned that there is [no file limit for x64 build](https://code.visualstudio.com/updates/v1_15#_windows-64-bit).

**Comment by ymg2006** [comment]
I searched previous errors in github, but there is no fix. how to fix this ?

**Comment by rebornix** [comment]
@ymg2006 I guess the file has a lot of lines?

**Comment by ymg2006** [comment]
@rebornix  of course it has a lot of lines.
