### ISSUE TITLE
Custom editor undo/redo not working on Linux

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#92608]
@mjbvz Hi! I'm working along with @tiagobento integrating the new Custom Webview Editor API in our editors. 

I've been focused on integrating the Undo/Redo on our editor state control API. I managed to succesfully propagate each change that happens on our editor by generating an edit and firing the `onDidChange` event on our `CustomEditorEditingCapability`, however I found two issues when trying to execute the Undo/Redo from VSCode.

The first issue is that Undo/Redo menu actions under Edit menu are not working. Clicking them isn't notifying our `CustomEditorEditingCapability` to execute the `undoEdits`/`applyEdits` methods. However the key shortcuts (Ctrl+Z / Ctrl+Y) seem to work, and our capability is able to execute the `undoEdits`/`applyEdits` methods.

Second one only happens when running VSCode on **Linux**. Looks like if two or more changes happen on the editor and I execute the Undo/Redo key shortcut the undo's/redo's are executed twice. For example if we make two changes on the editor that generate two separate edits (_edit1_ and _edit2_). If later I try to undo last change (_edit2_), our capability `undoEdits` method is executed twice, first time for _edit2_ and then for _edit1_. As I said, the same error happens with Redo. We tried this on different computers (Fedora, Ubuntu, Mac & Windows) and it seems to be present only **Linux** ones. I attached some gifs showing the error on different systems.

![bug_linux](https://user-images.githubusercontent.com/2429832/75879255-5d42ac80-5e1b-11ea-87bc-2270766549fc.gif)
_Wrong behaviour (Fedora): undoing two edits at same time_

![bug_mac](https://user-images.githubusercontent.com/2429832/75879404-aabf1980-5e1b-11ea-9238-a8a3767111a2.gif)
_Correct behaviour (Mac): undoing only a single edit each time_

![bug_Windows](https://user-images.githubusercontent.com/2429832/75879465-c32f3400-5e1b-11ea-9317-982133c028fd.gif)
_Correct behaviour (Windows): undoing only a single edit each time_

_Originally posted by @pefernan in https://github.com/microsoft/vscode/issues/77131#issuecomment-594493351_

**Comment by pefernan** [comment]
@mjbvz just some more info that may help you. Looks like same issue is also happening on the current extension api's (not the proposed). 

I think that the issue is that while pressing **Ctrl+Z** on webviews it triggers the undo faster than on text editor, so not necessarily _two times_. In a normal "press" it executes twice the udno while on a text editor it executes only one time. If we keep the **Ctrl+Z** pressed to undo multiple changes happens exactly the same, on webviews it triggers the undo more times.

**Comment by mjbvz** [comment]
Thanks for testing this!

The edit-> undo menus not working is a known issue: #90110. We're looking into it but may not get around to in April

The duplicate undo/redo has the same root cause as #82670. Should be fixed in the next insiders build. Let me know if you still see the duplicate commands once the next VS Code insiders
