### ISSUE TITLE
Cant open remote ssh 

### ISSUE THREAD

**Issue by MIennaco** [microsoft/vscode#92606]
Issue Type: <b>Bug</b>

Worked yesterday. After system reboot (I assume a Windows Update) can not connect to remote linux system with SSH extension

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (25.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none

**Comment by roblourens** [comment]
Could you share the log from the Remote-SSH output channel?

Does setting `"remote.SSH.useLocalServer": false` help (and if your remote is Windows, setting `"remote.SSH.windowsRemotes": ["<hostname>"]`?

**Comment by alazaro** [comment]
I had the same issue. Setting `"remote.SSH.useLocalServer": false` did fix it. It would be a good idea to change the default value of this setting on Windows.

**Comment by jghal** [comment]
cross-linking to comment on [vscode-remote-release#2551](https://github.com/microsoft/vscode-remote-release/issues/2551#issuecomment-599782534).

**Comment by MIennaco** [comment]
Just for reference. I went to the target machined (Ubuntu) and removed the .vscode and .vscode-server directories and was able to connect. I had to reinstall extensions, but it worked.

It would be nice if there was a utility that could analyze and/or fix corrupted directories avalable.

**Comment by roblourens** [comment]
Please share the log if it happens again, otherwise I can't diagnose the issue.

**Comment by g24swint** [comment]
It seems that a corrupted remote .vscode-server directory also caused a problem for me, although no error message seemed to indicate that. Like the poster above, deleting the remote ~/.vscode-server directory seemed to allow the connection to proceed. 

Setting "remote.SSH.useLocalServer" flag to false had no effect.
