### ISSUE TITLE
Unity Intellisense Not Working

### ISSUE THREAD

**Issue by Oddioengineer** [microsoft/vscode#92603]
Issue Type: <b>Bug</b>

I'm in various versions of Unity 2019, and suddenly VS Code stopped completing code, and Command-clicking variables does not take me to the definition. When I rollover things, I only see "Loading..." and it never resolves.

I have uninstalled and reinstalled VS Code, and I have the latest .Net and Mono.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (33.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.21.14
unity-tools|Tob|1.2.3

</details>

**Comment by rebornix** [comment]
Please file issues against Unity extension.

**Comment by dftty** [comment]
You can try update c# extension to 1.21.14. I have the same issue on windows 10, after upgrade, everything work fine.
