### ISSUE TITLE
Improve User Overrides for Keybindings

### ISSUE THREAD

**Issue by jkassismz** [microsoft/vscode#92601]
I'm frustrated with the keybinding interface...

PROBLEMS

- Cannot view default JSON
GUI view mixes defaults and user setting, while json view does not. Thus there is no way to reveal the JSON of the default bindings.

- Keybinding deletion is too complicated and redundant
Deleting a default binding from the GUI *adds* an override to my user bindings.
Deleting the same default binding from the GUI *adds* a duplicate override to my user bindings.
Deleted bindings *still appear* in the list if bindings in the GUI, leading the user to believe that they are *not deleted*.

- Command discovery is broken
In the GUI view there is no way to discover a command unless a key is already bound it.
In the JSON view... text expansion / autocompletion of the command field mashes together *all* possible commands and overflows the view. there is no partial autocompletion to discover commands incrementally 

SOLUTION
if an overlay system is required... identify keybindings by mnemonic id so that entries the delete bindings added by deeper layers are easier to comprehend. fix the bugs with duplication. expose the default json so that it is discoverable. fix autocompletion.

USE CASE
Try remapping all of your function keys. It is extremely difficult.

**Comment by sandy081** [comment]
> Cannot view default JSON

- There is an action to see only Default keybindings

<img width="277" alt="image" src="https://user-images.githubusercontent.com/10746682/76650420-e5832900-6562-11ea-8cf1-c9bc7fabdc87.png">

- There is also a command to open as json file `Preferences: Open Default Keyboard Shortcuts`

> Deleting a default binding from the GUI adds an override to my user bindings.

This is the only way you can delete a default keybinding. Please let me know If you have other ideas.

> Deleting the same default binding from the GUI adds a duplicate override to my user bindings.

Please provide me an example to repro.

> Deleted bindings still appear in the list if bindings in the GUI, leading the user to believe that they are not deleted.

Can you please be specific. Please give an example.

> In the GUI view there is no way to discover a command unless a key is already bound it.

Also please give us an example.

> In the JSON view... text expansion / autocompletion of the command field mashes together all possible commands and overflows the view. there is no partial autocompletion to discover commands incrementally

Also please give us an example with screenshot. Easier to understand.
