### ISSUE TITLE
Search in Panel sizing error

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#92610]
Issue Type: <b>Bug</b>

* Open Search in Panel
* Cmd+down to move focus to the include pattern input box

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/876920/76579065-1e020480-6488-11ea-9df4-a4533bd936db.png">

VS Code version: Code - Insiders 1.44.0-insider (1df23554b2e3d5f1efc6fbc76ee61d3f7f186c6d, 2020-03-12T05:29:05.555Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|-psn_0_39531953|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
vscode-pull-request-github-insiders|Git|2020.3.8167
vscode-language-pack-zh-hans|MS-|1.43.7
remote-ssh-edit-nightly|ms-|2020.3.13860
remote-ssh-nightly|ms-|2020.3.13860
js-debug-nightly|ms-|2020.2.2917
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@sbatten @roblourens does any one of you get a chance to take a look? I'm still seeing this issue in today's Insiders.

**Comment by roblourens** [comment]
Investigating

**Comment by sbatten** [comment]
that looks right, if overriding layout calls, we need to send the right dimension
