### ISSUE TITLE
too hard to download off-line extension package

### ISSUE THREAD

**Issue by ericsoul1987** [microsoft/vscode#92618]
Issue Type: <b>Feature Request</b>

Sometimes,we need to install some extension off-line,but it's usaully too hard to find the entrance for download the package from vs code.It's really too hard for me!I must find it everywhere,but still can't find.I'm so sad.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

**Comment by sandy081** [comment]
> must find it everywhere,but still can't find.I'm so sad.

Not sure if understand what you mean by this. Can you please be clear and specific about this?
