### ISSUE TITLE
JavaScript debugger drops Block scoped variables before return executes

### ISSUE THREAD

**Issue by john-aws** [microsoft/vscode#92617]
VSCode Version: 1.43.0
OS Version: Mac OS X 10.14.6

With the following JavaScript code (this is just a simple example), run under the VS Code debugger:

```js
function convertAttribute(attr) {
  if (attr) {
    const key = 1;
    const val = 2;
    return val;
  }

  return attr;
}

convertAttribute(42);
```

If you place a breakpoint on the `const val = 2;` statement then the debugger shows the following variables (correctly):

- Block
  - this
  - key: 1
  - val: undefined
- Local
  - attr: 42

If you step over the `const val = 2;` statement to the subsequent `return val;` statement then the debugger shows the following variables (incorrectly):

- Local
  - Return value: 2
  - this
  - attr: 42

The problem is that the debugger has dropped the Block scoped variables *before* the return statement has executed. It's a common debugging technique to break on a return statement  so that you can see the state of variables prior to return.

This also happens if you place the (only) breakpoint on the `return val;` statement and run to it.

**Comment by connor4312** [comment]
This is an optimization made by Chrome/V8; we just don't get the information for those variables. You can see the same behavior in the chrome devtools

![](https://memes.peet.io/img/20-03-5ccc68cb-0a93-4228-af21-c70f7b4e741f.png)

I've opened an issue on Chromium for this: https://bugs.chromium.org/p/chromium/issues/detail?id=1061306

Thanks for the report!

**Comment by connor4312** [comment]
Chromium has closed this as a wontfix--see the linked issue for details.
