### ISSUE TITLE
Lag while typing

### ISSUE THREAD

**Issue by rusinghmsft** [microsoft/vscode#92619]
Issue Type: <b>Bug</b>

There is very recognizable lag in typing, which slow productivity and causes multiple mistakes.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.19580

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.80GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|2.0.1
Bookmarks|ale|11.0.0
stackoverflow-search|Ale|1.2.0
open-osg|anm|0.0.1
multiline-find-and-replace|axl|0.0.1
indent-to-bracket|Cod|1.2.2
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
output-colorizer|IBM|0.1.2
vscode-smart-split-into-lines|Jul|0.0.1
vscode-backlog-wiki-preview|k--|0.0.6
guid|kos|0.0.1
pomodoro|lky|1.1.3
tdpcode|Mic|1.3.3
vscode-nmake-tools|Mic|2.0.200218004
cpptools|ms-|0.27.0-insiders2
vsnotes|pat|0.7.1
datetime|rid|1.0.8
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.3.1
indenticator|Sir|0.6.0
vscode-todo-highlight|way|1.0.4

(5 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you launch with all extensions disabled?

**Comment by jsgoupil** [comment]
@gjsjohnmurray I don't know if it is related, but I was going to open a bug on 1.43 but it seems to be fixed in the insider. (and it was fine on 1.42)
When having 500+ cursor, it's impossible to type fast... it freezes for a good 30 seconds. It's fixed in 1.44.

**Comment by gjsjohnmurray** [comment]
@jsgoupil that's good to hear. Please close the issue.

**Comment by jsgoupil** [comment]
@gjsjohnmurray I'm not the owner of this issue. And I don't know if that's what the person was referencing. I was not able to find the bug/commit regarding *my* problem.

**Comment by rusinghmsft** [comment]
I can verify that there's no such issue on the insiders build(1.44.0). Closing this issue.
