### ISSUE TITLE
Changes to files are not detected in source control module

### ISSUE THREAD

**Issue by mcgodan** [microsoft/vscode#92612]
Repository within hidden folder does not reflect changes in source control tab.

I have searched for similar issues and whilst there are some, i feel they are different to my issue here. This issue is occurring on a newly installed OSX, with a clean VSCode and newly cloned repo. 

Tried with and without extensions and used the default apple git version 2.21.1 in /usr/bin/git and the LTS 2.23.0 installed into /usr/local/bin/git

Vscode is installed on default drive/partition in applications folder with shell extension enabled.
repo is installed into /users/[me]/.git/[repo] seemingly fails to detect changes 

- VSCode Version: 1.43.0
- OS Version: MacOSX 10.15.3

Steps to Reproduce:

1. clone repo into hidden folder
2. make changes to any file or create a new one
3. changes are not detected until a manual sync in performed

Does this issue occur when all extensions are disabled?: Yes

Edit: Of course it can easily be fixed by not using hidden folders...

**Comment by rebornix** [comment]
@mcgodan what's the result when you run `git status` in the terminal?

**Comment by mcgodan** [comment]
Git status correctly identifies the changes

D

**Comment by joaomoreno** [comment]
What do you mean by hidden folder? How do you hide a folder? Are there any symlinks involved? Can you show me the full content of `Git: Show Git Output`?

**Comment by mcgodan** [comment]
Why has this been closed? Did you need me to tell you how a folder was hidden on a Mac?

**Comment by joaomoreno** [comment]
From https://github.com/microsoft/vscode/issues/94898#issuecomment-612266788:

> By hidden folder I mean a folder with a . (dot) preceding the name. On Linux/Mac environments they are hidden by default. In Windows you can alter the folder attributes to make it hidden.
>
> There are no symlinks involved. 
> 
> I’ll get back to you with the git output but I doubt that matters.
> 
> Simply put, the git integration in vscode didn’t detect changes when my files were stored In a hidden folder named .git, renaming the folder to git solves the problem. 
> 
> I only logged the improvement in case anyone else notices the same issue, if there is a way for vscode to work within a hidden folder I imagine it may be useful.

**Comment by joaomoreno** [comment]
> Simply put, the git integration in vscode didn’t detect changes when my files were stored In a hidden folder named .git, renaming the folder to git solves the problem.

This is how Git works. This is not an issue with VS Code at all, nor is it an issue with hidden folders. It's a limitation of git: you can't have a folder called `.git ` a git repository.
