### ISSUE TITLE
Git causes terminal to lag when using WSL bridge

### ISSUE THREAD

**Issue by adrianord** [microsoft/vscode#92615]
Issue Type: <b>Performance Issue</b>

This behavior just started on a new laptop with a newly installed vscode using minimal plugins. When doing any operation in git in the integrated terminal, the entire terminal will start lagging. It'll be behind when I'm typing and sometimes freeze. This only seems to happen when using the WSL bridge, setting my terminal to wsl.exe and using it outside of the WSL bridge doesn't have this problem. Disabling git using `"git.enabled": false"` also fixes the issue but this is a poor workaround.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.19569
Remote OS version: Linux x64 4.4.0-19569-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (40.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19569-Microsoft|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|Memory (System)|63.73GB (40.95GB free)|
|VM|50%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    84	 35844	code main
    0	    54	  2076	   electron-crash-reporter
    0	    41	 20228	   utility
    0	    82	 29928	   window (Issue Reporter)
    0	   335	 32820	   gpu-process
    0	    88	 35668	   shared-process
    0	   182	 38440	   window (settings.json - templates [WSL: Ubuntu] - Visual Studio Code)
    0	    90	 38672	     extensionHost
    0	     6	 27684	       C:\Windows\system32\wsl.exe /home/aordonez/nvim-linux64/bin/nvim -N --embed -c "source $(wslpath 'c:\Users\Adrian Ordonez\.vscode\extensions\asvetliakov.vscode-neovim-0.0.50\vim\vscode-options.vim')" --cmd "source $(wslpath 'c:\Users\Adrian Ordonez\.vscode\extensions\asvetliakov.vscode-neovim-0.0.50\vim\vscode-neovim.vim')"
    0	     6	 19880	         C:\WINDOWS\system32\lxss\wslhost.exe {61584952-56c6-461b-96d1-127633e3a75e} 480 488 492
    0	    12	 26336	           console-window-host (Windows internal process)
    0	    11	 25868	         console-window-host (Windows internal process)
    0	    62	 35492	       electron_node wslDaemon.js 
    0	     6	  3956	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 78a4c91400152c0f27ba4d363eb56d2835f9903a stable .vscode-server 0  '
    0	    11	 18412	           console-window-host (Windows internal process)
    0	     6	 35476	           C:\WINDOWS\system32\lxss\wslhost.exe {61584952-56c6-461b-96d1-127633e3a75e} 492 500 504
    0	    12	 28496	             console-window-host (Windows internal process)

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	 17971	remote agent
    0	     0	 17987	   watcherService
    0	     0	 18058	   extensionHost
    0	     0	 18078	     /mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node /mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=18058
    0	     0	 19266	     /usr/bin/zsh
    0	     0	 19325	       /usr/bin/zsh
    0	     0	 20615	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 20616	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu|    Folder (templates): 4 files|      File types: yml(2) md(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.20.0
vscode-kubernetes-tools|ms-|1.1.0
vscode-yaml|red|0.7.2
vscode-neovim|asv|0.0.50
remote-wsl|ms-|0.42.3
code-settings-sync|Sha|3.4.3
viml|Xad|0.0.2

</details>

**Comment by adrianord** [comment]
After testing a few of the settings, it appears that gitlab.autorefresh is specifically what's causing this lag. Again, this only happens when using the WSL bridge (remote WSL). Setting `"gitlab.autorefresh": false` is a better workaround, but still not ideal for most.

**Comment by Tyriar** [comment]
Could you check the git output channel (Output in the panel, then choose git in dropdown) for whether there are a lot of git commands that happen when you're using git in the terminal? Maybe your workspace is triggering the git extension to start hammering git for some reason 🤔 

I use Remote WSL quite a bit and haven't noticed anything like this.

Could you also share your settings.json file?

**Comment by adrianord** [comment]
Sure, here's just spamming the terminal with git commands
I'm in that gitlab-runner helm chart repo here but it happens with much smaller repositories as well.

```
charts/gitlab-runner master
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
charts/gitlab-runner master
❯ git add .     
 charts/gitlab-runner master
❯ git commit    
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
charts/gitlab-runner master
❯ git status  
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

This caused significant lag while typing `git add .` and `git commit` where the text didn't appear for a couple seconds.

Here is the output of git
```
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git ls-files --stage -- /mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/templates/deployment.yaml
> git rev-parse --symbolic-full-name master@{u}
> git cat-file -s b3512a991ed76777b04440c8210b4badbf3be54e
> git rev-list --left-right master...refs/remotes/origin/master
> git show :templates/deployment.yaml
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Failed to watch ref '/mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/.git/refs/remotes/origin/master', is most likely packed.
Error: ENOENT: no such file or directory, watch '/mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/.git/refs/remotes/origin/master'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1270:11)
	at Object.t.watch (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:596727)
	at E.updateTransientWatchers (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:82685)
	at l.fire (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/out/vs/server/remoteExtensionHostProcess.js:48:865)
	at R.updateModelState (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:101543)
> git config --get commit.template
> git ls-files --stage -- /mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/templates/deployment.yaml
> git cat-file -s b3512a991ed76777b04440c8210b4badbf3be54e
> git ls-files --stage -- /mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/templates/deployment.yaml
> git cat-file -s b3512a991ed76777b04440c8210b4badbf3be54e
> git show :templates/deployment.yaml
> git ls-files --stage -- /mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/templates/deployment.yaml
> git status -z -u
> git cat-file -s b3512a991ed76777b04440c8210b4badbf3be54e
> git symbolic-ref --short HEAD
> git rev-parse master
> git show :templates/deployment.yaml
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Failed to watch ref '/mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/.git/refs/remotes/origin/master', is most likely packed.
Error: ENOENT: no such file or directory, watch '/mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/.git/refs/remotes/origin/master'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1270:11)
	at Object.t.watch (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:596727)
	at E.updateTransientWatchers (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:82685)
	at l.fire (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/out/vs/server/remoteExtensionHostProcess.js:48:865)
	at R.updateModelState (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:101543)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Failed to watch ref '/mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/.git/refs/remotes/origin/master', is most likely packed.
Error: ENOENT: no such file or directory, watch '/mnt/c/Code/public/gitlab/gitlab-org/charts/gitlab-runner/.git/refs/remotes/origin/master'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1270:11)
	at Object.t.watch (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:596727)
	at E.updateTransientWatchers (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:82685)
	at l.fire (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/out/vs/server/remoteExtensionHostProcess.js:48:865)
	at R.updateModelState (/mnt/c/Users/Adrian Ordonez/Home/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/extensions/git/dist/main.js:1:101543)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
> git config --get commit.template
```

Here is my settings.json
``` jsonc
{
    // #region neovim
    "vscode-neovim.useWSL": true,
    "vscode-neovim.neovimPath": "/home/aordonez/nvim-linux64/bin/nvim",
    // #endregion
    // #region editor
    "editor.fontFamily": "SauceCodePro NF",
    "editor.fontSize": 12,
    "editor.wordWrap": "off",
    "editor.wordWrapColumn": 120,
    "editor.minimap.enabled": false,
    "explorer.openEditors.visible": 0,
    "editor.lineNumbers": "relative",
    "editor.formatOnSave": false,
    "editor.formatOnPaste": true,
    "editor.tabSize": 2,
    "editor.rulers": [
        120
    ],
    // #endregion
    // #region workbench
    "workbench.sideBar.location": "right",
    "workbench.editor.enablePreview": false,
    "workbench.activityBar.visible": false,
    "workbench.settings.editor": "json",
    "workbench.colorTheme": "Monokai",
    "workbench.startupEditor": "newUntitledFile",
    // #endregion
    // #region terminal
    "terminal.integrated.fontFamily": "SauceCodePro NF",
    "terminal.integrated.fontWeightBold": "500",
    "terminal.integrated.shell.windows": "wsl.exe",
    "terminal.integrated.rendererType": "dom",
    // #endregion
    // #region Language Specific
    "[htlm]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[rust]": {
        "editor.tabSize": 4
    },
    "[helm]": {
        "editor.rulers": []
    },
    // #endregion
    // #region files
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.associations": {
        "[Dd]ockerfile*": "dockerfile"
    },
    // #endregion
    // #region prettier
    "prettier.proseWrap": "always",
    "prettier.printWidth": 120,
    "prettier.tabWidth": 2,
    "editor.renderWhitespace": "all",
    "sync.gist": "[REDACTED]",
    "[yaml]": {
        "editor.defaultFormatter": "redhat.vscode-yaml"
    },
    // #endregion
    "git.enabled": true,
    "gitlens.advanced.messages": {
        "suppressGitDisabledWarning": true
    },
}
```

**Comment by Tyriar** [comment]
Think this is related to git locking other git commands until they're done and just being generally slower over wsl bridge.

**Comment by joaomoreno** [comment]
Do you see the same slowness if you work on that repository directly from Windows? Instead of using the WSL bridge. It's generally a bad idea to be in Windows and use WSL to edit files on the Windows side... you're paying an unneccessary performance cost.

**Comment by adrianord** [comment]
@Tyriar I'm not seeing this same lag on an older laptop I have running the same set up. WSL bridge editing code on `/mnt/c/Code/` with the git extension enabled. I don't understand why git performing operations in the background would block the UI, especially for the terminal since it should be a child process, right?

@joaomoreno I don't see the same lag happening on Windows.
I work often in mono repos where the set up is ASP.NET Core and Angular in a ClientApp folder. I generally write dotnet in Rider and Angular in vscode. Rider doesn't have a WSL bridge, and can't edit WSL files, and I prefer to have all my tools in Linux and would if Rider had a WSL bridge. I'm playing around with running Rider in WSL using X11 and X410.

**Comment by adrianord** [comment]
@Tyriar  @joaomoreno I had forgotten to test whether I was getting this problem in the WSL file system and it seems I am. So to recap, when using the latest version of vscode through the WSL bridge, I get a laggy terminal from background git operations, possibly other background processes that would block the UI. This is occurring when using the WSL Bridge in WSL1 regardless of editing in the WSL file system or the Windows file system. The only mitigation so far is to use vscode without the WSL bridge editing on the Windows file system.

**Comment by Tyriar** [comment]
The "fix" here might be to patiently wait for WSL2 to hit stable Windows like I am.

**Comment by adrianord** [comment]
@Tyriar Haha, sorry for the mix up in terminology. I'll try to remember to call it Remote WSL.

I'm in the Windows Insider program and was able to test out the WSL Remote in WSL2, it all seems to work as expected and pretty smoothly even editing on /mnt/c which isn't its strong suit (https://github.com/microsoft/WSL/issues/4197).

I've been holding off on switching to WSL2 till it has a stable release but I might just switch over early. However, this might not be an option for everyone since WSL2 requires hyper-v, so people running anything less than Windows 10 Professional or are running VMWare Workstation won't be able to use WSL2. That, and AFAIK, WSL1 isn't going to be deprecated (https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#what-will-happen-to-wsl-1-will-it-be-abandoned) so this is still an issue.

I'm planning on trying a fresh install of vscode on a separate machine later this week and if it goes well, I'll reinstall on my workstation laptop to see if it fixes anything, fingers crossed.

**Comment by joaomoreno** [comment]
Great to know. Closing this as upstream then, since the fix will eventually land in Windows stable.
