### ISSUE TITLE
Hint at incorrect integrated terminal shell path if the process crashes immediately after launching

### ISSUE THREAD

**Issue by swarajgiri** [Microsoft/vscode#9261]
- VSCode Version: 1.3.1
- OS Version: Windows 7

Steps to Reproduce:

1. Install vscode outside windows installation drive
2. Switch terminal from `cmd` to `powershell` using `"terminal.integrated.shell.windows": "\\windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"` in `settings.json` file.

Terminal opens and then crashes with a console.error message
`console.error('Integrated terminal exited with code ' + exitCode);`

##### Suggestion
The above error message could be improved to give the user an hint  to use absolute path to `powershell` in `settings.json` or vscode could ask for the windows installation directory on first start.

#### Fix for using powershell
Use absolute path to powershell in `settings.json`

Example, with windows installed in C drive
`"terminal.integrated.shell.windows": "C:\\windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"`

**Comment by Tyriar** [comment]
I don't think it's a big enough use case of starting a path on Windows using `\\` to add special logic for advise on this, particularly when the advise could be wrong.

I do see it being useful to give a less generic message if the shell crashes immediately after trying to be launched, something like "The terminal shell could not be launched, is the path correct?"

**Comment by swarajgiri** [comment]
Yeah, a better console message would work.
Thanks for putting it up in the next milestone.

**Comment by Tyriar** [comment]
Closing in favor of #9087
