### ISSUE TITLE
Noised blank lines in terminal

### ISSUE THREAD

**Issue by keelung-yang** [microsoft/vscode#92621]
- VSCode Version: 1.42.1, 1.43
- OS Version: Windows 10.0.17763.973, 64 bit

Steps to Reproduce:
1. Open menu: view->terminal
2. Select default shell to "Command Prompt" 
3. Input any character, then you got:
![image](https://user-images.githubusercontent.com/20385450/76587524-2d805c80-651f-11ea-91b2-e9ebd05c2ecd.png)

If you can't reproduce, please try modifying terminal height by mouse.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
