### ISSUE TITLE
The ripgrep search is not support "Unicode character class" syntax

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#92626]
Issue Type: <b>Bug</b>

1. open the search panel.
2. enable regex search, and seach with "\p{script=Han}"
3. vscode tell me "invalid property name".
But when I run the "rg.exe" bundled with vscode, it will success.

try this, the arguments are captured in command line when vscode run the "rg.exe". I replace the regex.
```
rg.exe --hidden --ignore-case --max-filesize 17179869184 --no-ignore --follow --crlf --auto-hybrid-regex --regexp "\p{script=Han}" --no-config --no-ignore-global --json -- <some file to search>
```

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
debug-visualizer|hed|0.13.0
generate-switch-case-for-enum-type|her|0.0.6
vscode-power-mode|hoo|2.2.0
code-beautifier|mic|2.3.3
vscode-json5|mrm|1.0.0
Go|ms-|0.13.1
vscode-typescript-tslint-plugin|ms-|1.2.3
synthwave-vscode|Rob|0.1.1
vscode-lua|tri|0.12.4
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0

</details>

**Comment by roblourens** [comment]
We don't support exactly what rg supports, we support the intersection of rg and Javascript regexes. It looks like `sc=Han` is the correct way to do this in Javascript and this works for me, can you try that?

![image](https://user-images.githubusercontent.com/323878/76664282-076bb400-6541-11ea-84f7-532187e15538.png)

**Comment by heroboy** [comment]
Thanks @roblourens , it works for me.
It's OK that it only support javascript regex syntax.
