### ISSUE TITLE
Semantic highlighting overrides token color customizations even when the specified scope is a more specific version of the semantic scope

### ISSUE THREAD

**Issue by noinkling** [microsoft/vscode#92627]
- VSCode Version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
- OS Version: Windows_NT x64 10.0.18363

As per the title, but this should make it clear - I want the colour of that crossed out line at the bottom to be applied:

![image](https://user-images.githubusercontent.com/4338251/76591544-97b3f400-6555-11ea-9dac-127e356c9945.png)

Relevant part of settings:

```json
"editor.tokenColorCustomizations": {
  "[One Dark Pro]": {
    "textMateRules": [
      {
        "scope": [
          "support.variable.property.js",
          "variable.other.property.js"
        ],
        "settings": {
          "foreground": "#BBBBBB"
        }
      }
    ]
  }
}
```

In general I would expect my `editor.tokenColorCustomizations` to always override the semantic highlighting colour if the specified scope is more "specific" (more dots or whatever). But even if that's not desirable in the general case (i.e. regardless of what the scope actually is, as per #90379), in this specific case `variable.other.property.js` is a strict extension/superstring/subscope(?) of `variable.other.property`, and therefore my colour should definitely take precedence/be used in JavaScript files.

Specifying `variable.other.property` without the `js` part works, but I only want it to affect JS highlighting.

**Comment by noftaly** [comment]
I’m experiencing the same problem. I just want to show another scenario where this happens which is even more troublesome:
![Capture d’écran 2020-03-13 à 18 59 23](https://user-images.githubusercontent.com/34779161/76647280-ced9d380-655c-11ea-8b10-ab6ff613320a.png)
Here I obviously want the "callback()" to be colored as a function, not as a parameter

**Comment by noinkling** [comment]
@noftaly That's only tangentially related to my specific issue (except for possibly highlighting the need for some way to selectively override/opt out of semantic highlighting), but I will add that I have also seen that behaviour.

**Comment by noftaly** [comment]
I'm not experiencing this issue anymore
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
OS: Darwin x64 19.3.0

**Comment by noinkling** [comment]
Just tested 1.43.1, my issue remains (after re-enabling semantic highlighting by setting `"semanticHighlighting": true` under `editor.tokenColorCustomizations`).

@noftaly Are you sure it's not just because semantic highlighting was disabled for external themes by default? See the changes made in: https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by aeschli** [comment]
Semantic highlighting wins against semantic highlighting as the semantic token provider has a better understanding of the source than the regex based TextMate grammar.

Issue mentioned by @noinkling:
For colouring, each semantic token is mapped to a TextMate scope. For properties this is currently `variable.other.property`. What's still missing is that the scope we maps to also have language information (the `.js` in `variable.other.property.js`). That's on the plan: https://github.com/microsoft/vscode/issues/86390.

Issue mentioned by @noftaly:
`callback` is classified as a parameter, but you want it to be a function: We have issue https://github.com/microsoft/vscode/issues/91038 for that.

**Comment by gjsjohnmurray** [comment]
> Semantic highlighting wins <strike>against semantic highlighting</strike> as the semantic token provider has a better understanding of the source than the regex based TextMate grammar.

@aeschli - maybe delete the bit I've crossed out in the above quote?

**Comment by aeschli** [comment]
Thanks @gjsjohnmurray, corrected my sentence.
