### ISSUE TITLE
Extension Settings in Extension Packs

### ISSUE THREAD

**Issue by smhmd** [microsoft/vscode#92624]
Add Property in `package.json` of an extension pack for those extension's settings that'll be appended to the user's own `settings.json`. Would make extension packs even more [useful](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup#_why-would-i-want-to-create-an-extension-pack).
```js
{
  ...
  "categories": ["Extension Packs"],
  "extensionPack": [
    "bradlc.vscode-tailwindcss",
    "octref.vetur",
  ],
  "extensionsSettings": {
    "vetur.grammar.customBlocks": {
      "docs": "md",
      "i18n": "json",
      "page-query": "graphql",
      "static-query": "graphql"
    },
    "tailwindCSS.emmetCompletions": true
  }
}
```

**Comment by sandy081** [comment]
/duplicate

#46851
