### ISSUE TITLE
VSCode language changed on New Window

### ISSUE THREAD

**Issue by zaevi** [microsoft/vscode#92636]
Issue Type: <b>Bug</b>

I'm using VSCode with zh_hans language extension. When I opened a new window, its language changed back to English.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.34.0
pawn-scripting-language-support|dce|0.0.5
vscode-diff|fab|1.4.0
godot-tools|gee|1.0.3
gc-excelviewer|Gra|2.1.34
vscode-language-pack-zh-hans|MS-|1.43.7
csharp|ms-|1.21.14
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
mono-debug|ms-|0.15.8
powershell|ms-|2020.3.0
debugger-for-chrome|msj|4.12.6
java|red|0.58.0
vscode-il|sol|0.0.1
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1

</details>

**Comment by rebornix** [comment]
what happens if you try to Configure Display Language again?

**Comment by dbaeumer** [comment]
@zaevi I can't reproduce this with neither of the two Chinese Language packs. How to you instruct VS Code to start in the Chinese locale.
