### ISSUE TITLE
The text of the status bar is not clear because the color scheme of solarized light theme.

### ISSUE THREAD

**Issue by LittleboyHarry** [microsoft/vscode#92639]
- VSCode Version: newest stable 1.43.0

Steps to Reproduce:

I'm using the built-in solarized light theme.

<img width="301" alt="批注 2020-03-13 182319" src="https://user-images.githubusercontent.com/13063376/76613856-e82d5080-6559-11ea-8c0e-776874e0bdf6.png">

<img width="263" alt="批注 2020-03-13 182256" src="https://user-images.githubusercontent.com/13063376/76613879-f24f4f00-6559-11ea-9545-062205bf3489.png">

The warning and success color are too similar to background, which avoid w3c [WCAG](https://www.w3.org/TR/WCAG/#adaptable) Color Accessibility. So, I can't see it clearly.

https://contrastchecker.com/?c=f3fb79&b=eee8d5

https://contrastchecker.com/?c=bcf888&b=eee8d5

Does this issue occur when all extensions are disabled?: Yes/No
Can't reproduce this behaviour without extensions.

**Comment by IllusionMH** [comment]
/causedByExtension

This status bar entry provided by Powershell extension. Please report this issue in repo https://github.com/PowerShell/vscode-powershell/issues
