### ISSUE TITLE
Cannot open Code when an instance with admin rights is running

### ISSUE THREAD

**Issue by bgavrilMS** [Microsoft/vscode#9263]
- VSCode Version: 1.3.1
- OS Version: Win 10.0 (build 10240)

Steps to Reproduce:

1. Open an instance of VSCode with Admin privileges 
2. Go to any folder, right click and choose "Open with Code" 

**Actual**: a new instance of VSCode fails to open (or one does open but crashes instantly)
**Expected**: a new instance of VSCode with the folder open

**Comment by mjcheetham** [comment]
+1

**Comment by bpasero** [comment]
```
C:\GitDevelopment\monaco>code-insiders C:\GitDevelopment\electron --verbose

Error: connect EPERM \\.\pipe\Code - Insiders-9562c6-sock
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

@joaomoreno if you have an idea, the only fix might be to switch to Electrons API for detecting a running instance.

**Comment by bpasero** [comment]
Actually I wonder: We have many bugs where people say they cannot elevate Code after it has started and then we have this bug. Should we just open a completely separate instance of Code when you run as Admin? That way, this issue would be fixed and also it enables to run Code as admin after it has already started 👍

**Comment by bpasero** [comment]
Actually this look like https://github.com/Microsoft/vscode/issues/4921
