### ISSUE TITLE
Replace all not working

### ISSUE THREAD

**Issue by hamedmo** [microsoft/vscode#92637]
Issue Type: <b>Bug</b>

After submitting my search and filling the Replace textbox, Replace All button does not do anything.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.25GB free)|
|Process Argv|D:\MyProjects\BMI_InterACT_DB\InterACT.cydsn|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
scope-bar|amo|0.2.1
python|ms-|2020.2.64397
cpptools|ms-|0.26.3

</details>

**Comment by rebornix** [comment]
Are you using the Find Widget in the editor or Search Viewlet?

**Comment by hamedmo** [comment]
I used Search Viewlet. Seems like a reset fixed the problem anyways!

**Comment by silllli** [comment]
It's not working for me either

**Comment by mustafa0x** [comment]
Not working for me either. I tried the button and Cmd + Opt + Enter.
