### ISSUE TITLE
sync, problem with re-login

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#92638]
- VSCode Version:
Version: 1.44.0-insider
Commit: efd7548df65de8e775015b67863190e6bd4934fc
Date: 2020-03-13T06:01:51.669Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. click "sync sign in" menu
2. follow login on browser

![image](https://user-images.githubusercontent.com/168366/76613097-5ef42a80-6515-11ea-9445-37c643860a27.png)

**Comment by RMacfarlane** [comment]
This looks like an error returned from AAD itself, so I'm not entirely sure what's going on. What type of account were you trying to log in with? I think this message gets displayed when some account information needs to be updated. Can you try logging in at account.live.com?

**Comment by FernandoMiguel** [comment]
after much messing with this (very unclear error) ,  i got something pointing to a locked account.
was able to unlock it after entering my phone number
