### ISSUE TITLE
"Add all missing imports" is not working properly

### ISSUE THREAD

**Issue by hrishi2430** [microsoft/vscode#92631]
Issue Type: <b>Bug</b>

1. Add properties that you want to import from other file
2. Do not import one by one 
3. Use "Add all missing Import" hint to import all missing properties

By "Add all missing Import" it will add imports to the top of the file but it will 1st add multiple "," (comma's) then Properties

eg.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
Please share some example code that demonstrates the issue

Also it looks like your example was cut off (maybe an image wasn't uploaded?)

**Comment by hrishi2430** [comment]
images uploaded PFA

**Comment by mjbvz** [comment]
I don't see any images

**Comment by hrishi2430** [comment]
> I don't see any images

![VSCodeBug](https://user-images.githubusercontent.com/47298375/77226632-d70ac200-6b9f-11ea-866e-f6ef3bf45b35.png)
![VSCodeBug1](https://user-images.githubusercontent.com/47298375/77226633-da05b280-6b9f-11ea-9495-530eca651654.png)

**Comment by mjbvz** [comment]
Please share some complete example code (as text) that demonstrates the issue
