### ISSUE TITLE
python has stopped working 

### ISSUE THREAD

**Issue by shaikhsdf** [microsoft/vscode#92648]
Issue Type: <b>Performance Issue</b>

i am usig django and python and everythig ws going fine when sudenly i had this problem that python has stoped when i go to debug it says python37.pdb not loaded

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    66	  9392	code main
    4	    62	  2560	   window (Issue Reporter)
    0	    60	  4204	   shared-process
    2	   192	  4548	   gpu-process
    0	   157	  7436	   window (launch.json - pollsapp - Visual Studio Code)
    0	    84	  3144	     extensionHost
    0	    34	  4156	       C:\Users\Dell\AppData\Local\Programs\Python\Python37\python.exe completion.py
    0	    20	  2104	         C:\Users\Dell\AppData\Local\Programs\Python\Python37\python.exe lib\python\jedi\inference\compiled\subprocess\__main__.py lib\python 3.7.0
    0	     8	  9456	           console-window-host (Windows internal process)
    0	     8	  6252	         console-window-host (Windows internal process)
    0	    34	  8296	       "C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=3144
    0	    12	  8120	     watcherService 
    0	     7	  8800	       console-window-host (Windows internal process)
    0	    33	  9404	     searchService
    0	     5	 11280	     winpty-process
    0	     7	  1560	       console-window-host (Windows internal process)
    0	    48	 10648	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    12	  7708	   electron-crash-reporter
    0	    23	  8256	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (launch.json - pollsapp - Visual Studio Code)
|    Folder (pollsapp): 37 files
|      File types: py(15) pyc(12) json(1) sqlite3(1)
|      Conf files: launch.json(1)
|      Launch Configs: python;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.2.64397

</details>

![debug option](https://user-images.githubusercontent.com/61783748/76629752-d00efe80-6564-11ea-8eb6-06c899486ce9.PNG)
![python not working debugger](https://user-images.githubusercontent.com/61783748/76629764-d2715880-6564-11ea-82da-d3595400ee5d.PNG)

**Comment by rebornix** [comment]
It looks like a Python issue instead of a VS Code issue.
