### ISSUE TITLE
Extensions don't install

### ISSUE THREAD

**Issue by AlexHart** [Microsoft/vscode#9264]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Pro SP1

Steps to Reproduce:

1. Do a new clean Visual Studio Code installation
2. Try to install any extension

It stays "installing" forever and doesn't throw an error.

It could be because of domain policies, but then I think it should throw some kind of error.
![image](https://cloud.githubusercontent.com/assets/10497736/16834097/98f9a76e-49b2-11e6-970f-b342d4cc3cf6.png)

(Running as an administration doesn't change the situation)

Also it should show the progress of the downloads or something, the ouput window is empty.

**Comment by joaomoreno** [comment]
If you open the Developer Tools (<kbd>Ctrl Shift P</kbd>, `Developer Tools`), do you see anything?

If you launch it from the command line as `code --verbose` do you see anything?

**Comment by AlexHart** [comment]
The console is empty and on the command line doesn't show anything either.

When I click on a extension it show the circles of loading one time, and then doesn't load anything below. I connect via a proxy, so probably it can't connect because it's not able to use the proxy config, but then it should throw an error.

![image](https://cloud.githubusercontent.com/assets/10497736/16867378/d2e4aa7c-4a71-11e6-8f64-8407bbbf19ab.png)

**Comment by joaomoreno** [comment]
Did you configure those proxy settings in your user settings? VS Code does not automatically picks up the system settings.

**Comment by AlexHart** [comment]
No, it was empty.

The thing is that I had a .pac configuration file, i got the ip of the proxy from there and updated it on the User settings, and now it's working.

Thanks for the help ;)

**Comment by joaomoreno** [comment]
You may wanna track #7140
