### ISSUE TITLE
Javascript breakpoints stick until restart

### ISSUE THREAD

**Issue by richtera** [microsoft/vscode#92645]
Issue Type: <b>Bug</b>

When I add a js breakpoint now, clearing it doesn't work until I restart the code. I can't quite figure out when this started happening, but I see it more and more both using v10 and v12 of node. I set a breakpoint start debugging, hit the breakpoint and then clear the breakpoint. It will continuously stop at the breakpoint until I hit restart in the debugger.
Thanks
Andy

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-hie-server|ala|0.0.37
better-toml|bun|0.3.2
vscode-jq|dan|1.2.0
vscode-jq-playground|dav|2.1.1
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
code-runner|for|0.9.17
gc-excelviewer|Gra|2.1.34
rest-client|hum|0.23.2
language-haskell|jus|2.7.0
vscode-language-babel|mgm|0.0.26
dotenv|mik|1.0.1
vscode-docker|ms-|1.0.0
python|ms-|2020.2.64397
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-ssh-explorer|ms-|0.50.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
Go|ms-|0.13.1
debugger-for-chrome|msj|4.12.6
phoityne-vscode|pho|0.0.24
material-icon-theme|PKi|4.0.1
sass-indented|rob|1.5.1
gitconfig|sid|2.0.1
mdx|sil|0.1.0
stylelint|thi|0.51.0
quokka-vscode|Wal|1.0.282

(16 theme extensions excluded)

</details>

**Comment by richtera** [comment]
I looked at this list before posting. The problem seems independent of any of those.
Especially when the breakpoints are within loops they keep on getting hit and stopping there even though they were disabled. Restarting the debuggee resolve the problem, so somehow the breakpoints are sticking inside of the nodejs engine.

**Comment by connor4312** [comment]
Does this continue to happen in our [new javascript debugger](https://github.com/microsoft/vscode-js-debug#installation)? If so, please set `trace: true` in your launch config and share the logs with us.

**Comment by richtera** [comment]
I can try this, but it is a rather recent bug. This did not used to happen and has started at most 2 or 3 weeks ago.

**Comment by richtera** [comment]
Works fine with the preview debugger, yes. At least in the limited testing I did with the same breakpoint. Looking forward to this new version.

**Comment by connor4312** [comment]
Okay, thanks. Fyi @roblourens
