### ISSUE TITLE
'revealIfOpened' flag should start at active editor

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9265]
goto declaration now uses the [`revealIfOpened` flag ](https://github.com/Microsoft/vscode/tree/master) but there is this issue

* have the same file open two times
* in the second slot invoke go to def on a symbol that in the file
* 🐛 the first editor is revealed
* when the reveal-flag is set the search for the editor should start at the active editor not at the beginning

**Comment by bpasero** [comment]
Hm, though it does...

**Comment by bpasero** [comment]
...no, does not :)

**Comment by bpasero** [comment]
Ok it was not very smart and now I did more changes to find the best editor to open:
* first check if the active editor matches
* second check if any of the visible editors in the other editor groups match
* third check if any of the non visible editors in the active group match
* finally go through all groups from left to right to find the editor

**Comment by jrieken** [comment]
@bpasero This is still quite unhappy when working without tabs. See attached gif

![jul-15-2016 10-44-28](https://cloud.githubusercontent.com/assets/1794099/16868644/1ea212c2-4a79-11e6-80e7-11631115159b.gif)

I don't expect it to reveal an editor when not using tabs but when it has been opened in one of the other slots, only if its visible there.

**Comment by bpasero** [comment]
@jrieken should we just rename this to `revealIfVisible` and only do this on the visible editors instead of all groups?

**Comment by jrieken** [comment]
yeah - I think that's fair

**Comment by bpasero** [comment]
Pushed, let me know how it goes. This also pretty much restores the behaviour how it was from the explorer and history when navigating (there I am using this flag now).
