### ISSUE TITLE
[scss] support `@forward 'library' with` syntax

### ISSUE THREAD

**Issue by lekoala** [microsoft/vscode#92658]
Version: 1.43.0 (system setup)
Commit: 78a4c91
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
(i can also provide extensions but I don't think it really matters in this case)

Steps to reproduce

Open a .scss file
copy paste this
```
@forward 'library' with (
$black: #222 !default,
$border-radius: 0.1rem !default
);
```
Expected result : no problems
Actual result:
{
"resource": ".../sass/all.scss",
"owner": "generated_diagnostic_collection_name#0",
"code": "css-unknownkeyword",
"severity": 8,
"message": "unknown keyword",
"source": "scss",
"startLineNumber": 3,
"startColumn": 20,
"endLineNumber": 3,
"endColumn": 24
}

So it seems the sass module system (@use/@format) should be supported, but the support seem incomplete

The following examples do not work

```
@forward 'library' with (
  $black: #222 !default,
  $border-radius: 0.1rem !default
);
```

or

```
@use 'library' with (
    $black: #222 !default,
    $border-radius: 0.1rem
);
```

it seems support is missing for:
- @forward with configuration
- @use with !default in the configuration (@use with configuration without !default works fine)

**Comment by lekoala** [comment]
Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
(i can also provide extensions but I don't think it really matters in this case)

Steps to reproduce

1. Open a .scss file
2. copy paste this
@forward 'library' with (
  $black: #222 !default,
  $border-radius: 0.1rem !default
);

Expected result : no problems
Actual result:  
{
	"resource": ".../sass/all.scss",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "css-unknownkeyword",
	"severity": 8,
	"message": "unknown keyword",
	"source": "scss",
	"startLineNumber": 3,
	"startColumn": 20,
	"endLineNumber": 3,
	"endColumn": 24
}

**Comment by SharakPL** [comment]
Also `!default` is missing from the suggestions

![obraz](https://user-images.githubusercontent.com/5007456/79443340-00214580-7fda-11ea-88e9-0a74ebca60b7.png)
