### ISSUE TITLE
Filter debug variables

### ISSUE THREAD

**Issue by blacktop** [microsoft/vscode#92657]
I can only sometimes get debug variables to filter

I am using the vscode-lldb extension and no mater where I click in the variable panel I can't get it to except my input and start filtering.  Is there some trick to where I should click in the panel?

#13201

**Comment by blacktop** [comment]
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-12T18:47:40.536Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by isidorn** [comment]
@blacktop anywhere you click on the variables view and the filtering should just start.
Please note that this feature is disabled when you have a screen reader attached for accessibility reasons, so make sure you do not have `"editor.accessibilitySupport": "on"`
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
