### ISSUE TITLE
Open File from Cmd Pallette Uses Partial Path while Open from Search Results Uses Full Path

### ISSUE THREAD

**Issue by jkassis** [microsoft/vscode#92655]
When I open a file using the command palette, it recognizes that the file is relative to my document root.

When I open the file using search results from workspace-wide search, it opens with the full path.

The file opened by search results is then disconnected from the projects... code navigation commands don't work. SETTING BREAKPOINTS DONT WORK. Note that this could explain why some of the breakpoints not working tickets are hard to track down. It may have nothing to do with symlinks.

![image](https://user-images.githubusercontent.com/3630156/76637234-9b208e80-6507-11ea-936c-bd3ab913e61d.png)

**Comment by jkassis** [comment]
@ramya-rao-a ^^^ Maybe explains why debugger breakpoints don't work sometimes.

**Comment by jkassis** [comment]
more...
![image](https://user-images.githubusercontent.com/3630156/76637738-87c1f300-6508-11ea-9998-b141b80a04db.png)
![image](https://user-images.githubusercontent.com/3630156/76637880-bf309f80-6508-11ea-864e-557095c3ba8e.png)
![image](https://user-images.githubusercontent.com/3630156/76637946-dbccd780-6508-11ea-8717-a3040eb77040.png)

**Comment by jkassis** [comment]
maybe vscode needs a special system-wide cap-safe mode for osx?

**Comment by bpasero** [comment]
I think quick open does the right thing but search does not, moving to Rob.

**Comment by roblourens** [comment]
Hm, basically you search in folder `foo` and find file `bar` and we return `foo/bar`, there is no case-normalization step. Quickopen would normally do the right thing if Code was opened with the correctly cased workspace folder. But @bpasero I can reproduce the same thing with quickopen's absolute path handling logic -

```
mkdir Foo
touch Foo/bar
```

then in quickopen, open `~/folder/Foo/bar` and `~/folder/foo/bar`, and they open as separate tabs with differently cased paths. As far as I know we don't really do any case normalization anywhere in vscode and this would fall under the master path case issue that we have.

**Comment by bpasero** [comment]
If that is the issue, then it is https://github.com/microsoft/vscode/issues/12448
