### ISSUE TITLE
Formatting on Save hangs indefinitely starting in version 1.42

### ISSUE THREAD

**Issue by dionridley** [microsoft/vscode#92652]
Issue Type: <b>Bug</b>

Since version 1.42 my formatters stopped functioning properly.  Looking online it looks like many formatters are experiencing the same issue.  What is happening is when you save a file and the formatter runs it just hangs indefinitely.  If I hit cancel the file will format properly and finish saving.  This issue occurs on both Windows and MacOS. 

To work around the issue i've installed version 1.41

![2020-03-13 09 15 49](https://user-images.githubusercontent.com/947060/76635935-9adfbd80-651e-11ea-9e19-a7a589d339f2.gif)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|-psn_0_7513898|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
vscode-elixir|mjm|1.1.0
vscode-elixir-formatter|sam|0.2.0

</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aformatting

**Comment by ponchautf** [comment]
> This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title 😳 Anyways, searching for issues with the same labels will likely help you 👉
> [https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aformatting](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aformatting)

Unfortunately your link does not help at all.
Can't find any issue with your link (even searching wider and on closed issues also)

I have this issue with multiple languages : razor files, js files, ....
Don't seems to be related to an extention (as it occurs with prettier, onmisharp, ...)
