### ISSUE TITLE
codelens missing frequently

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#92660]
Issue Type: <b>Bug</b>

Codelens are missing (hidden) when splitting the editors or scrolling the editor up and down. The view zone is placed in the editor correctly but the commands are missing

<img width="476" alt="image" src="https://user-images.githubusercontent.com/876920/76644300-f8224180-6513-11ea-960f-37643f1dfae1.png">

VS Code version: Code - Insiders 1.44.0-insider (efd7548df65de8e775015b67863190e6bd4934fc, 2020-03-13T06:01:51.669Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.19GB free)|
|Process Argv|-psn_0_41727945|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
vscode-pull-request-github-insiders|Git|2020.3.18182
vscode-language-pack-zh-hans|MS-|1.43.7
remote-ssh-edit-nightly|ms-|2020.3.13860
remote-ssh-nightly|ms-|2020.3.13860
js-debug-nightly|ms-|2020.2.2917
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Can you inspect the dom when this happens? There should be a content widget and view zone, looks like one is missing

**Comment by rebornix** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/876920/76809866-6c294780-67a9-11ea-8a98-cb816f034d9c.png">

Actually they are both there but the content is empty.

**Comment by jrieken** [comment]
Can you check the TSServer log? This looks like a case in which we receive the (empty) code lenses but fail (or are super slow) to resolve them, e.g. only the resolving puts the text here... Adding @mjbvz to check if you have seen something like this.

I haven't noticed this but my code lens selfhosting is with the complexity metrics extensions which hints towards an extension issue

**Comment by mjbvz** [comment]
We treat resolving the code lenses as a low priority operation, so other actions such as suggest can interrupt it. Also, resolve can take a little time in large projects like VS Code

@rebornix Do the code lenses ever appear if you let the editor sit there for a moment?

**Comment by rebornix** [comment]
@mjbvz it doesn't, unless I make changes to the content again. Sometimes they come back just after a long period, but sometimes they never come back.

It will be helpful if one of you can tell me how to troubleshoot when the codelens are off positioned

<img width="722" alt="image" src="https://user-images.githubusercontent.com/876920/76908862-ff748280-6866-11ea-9237-9f54e79c0d68.png">

**Comment by rebornix** [comment]
tslog which might match what @mjbvz described, `references` is cancelled.


```
Info 24023[16:21:43.941] response:
    {"seq":0,"type":"response","command":"references","request_seq":7655,"success":true,"body":{"refs":[{"file":"/Users/penlv/code/vscode/src/vs/workbench/api/browser/mainThreadNotebook.ts","start":{"line":43,"offset":20},"end":{"line":43,"offset":26},"contextStart":{"line":43,"offset":3},"contextEnd":{"line":43,"offset":48},"lineText":"\t\tprivate readonly _proxy: ExtHostNotebookShape,","isWriteAccess":true,"isDefinition":true},{"file":"/Users/penlv/code/vscode/src/vs/workbench/api/browser/mainThreadNotebook.ts","start":{"line":75,"offset":38},"end":{"line":75,"offset":44},"lineText":"\t\tlet deleteExtHostCell = await this._proxy.$deleteCell(this.viewType, uri, index);","isWriteAccess":false,"isDefinition":false},{"file":"/Users/penlv/code/vscode/src/vs/workbench/api/browser/mainThreadNotebook.ts","start":{"line":85,"offset":24},"end":{"line":85,"offset":30},"lineText":"\t\tlet ret = await this._proxy.$saveNotebook(this.viewType, this.uri);","isWriteAccess":false,"isDefinition":false}],"symbolName":"_proxy","symbolStartOffset":20,"symbolDisplayString":"(property) MainThreadNotebookDocument._proxy: ExtHostNotebookShape"}}
Info 24024[16:21:43.941] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/Users/penlv/code/vscode/src/vs/workbench/contrib/notebook/browser/notebookEditorInput.ts","diagnostics":[]}}
Info 24025[16:21:43.951] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"/Users/penlv/code/vscode/src/vs/workbench/contrib/notebook/browser/notebookEditorInput.ts","diagnostics":[]}}
Info 24026[16:21:43.951] request:
    {"seq":7656,"type":"request","command":"references","arguments":{"file":"/Users/penlv/code/vscode/src/vs/workbench/api/browser/mainThreadNotebook.ts","line":44,"offset":10}}
Info 24027[16:21:44.93] response:
    {"seq":0,"type":"response","command":"references","request_seq":7656,"success":true,"body":{"canceled":true}}
Info 24028[16:21:44.93] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"/Users/penlv/code/vscode/src/vs/workbench/contrib/notebook/browser/notebookEditorInput.ts","diagnostics":[{"start":{"line":115,"offset":13},"end":{"line":115,"offset":18},"text":"'group' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":115,"offset":37},"end":{"line":115,"offset":44},"text":"'options' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true}]}}
Info 24029[16:21:44.94] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":7644}}
```

**Comment by rebornix** [comment]
I ran into this issue less often than before, a couple of times in last few weeks. The codelens come into view slower than before, not sure if we have any update in TS side @mjbvz . 

Occasionally I saw empty code lens and after debugging into this a bit, I found that the lens we received have empty title and command, which will end up with an empty span `<span></span>`

https://github.com/microsoft/vscode/blob/16a06751fe9da1a82c7791674e74db87ebd9dd10/src/vs/editor/contrib/codelens/codelensWidget.ts#L86-L103

**Comment by mjbvz** [comment]
Nothing has changed on the TS side within the last month or so.

We compute the references code lens with low priority requests against TS server. This means any user action will go ahead of these request. I wonder if semantic coloring is now causing these requests to be more delayed than they were previously? @rebornix Can you try disabling semantic highlighting just to check this

**Comment by jrieken** [comment]
I haven't seen this in a while? Did anyone else? A while back I did merge a PR that fixed some css issue which also could have caused this.
