### ISSUE TITLE
Terminal Ctrl + Shift + C broken in windows

### ISSUE THREAD

**Issue by tracker1** [microsoft/vscode#92666]
Fresh install, VS Code version 1.43.0, Windows x64 10.0.19035

For some reason, the ctrl+shift+c doesn't work in the terminal.. not sure if it's just this release or when it broke... It was working on another install without issue.

**Comment by choonghee-lee** [comment]
For me, Ctrl + C on termial doesn't work.
VS Code version 1.43.0, Windows x64 10.0.18362

**Comment by Tyriar** [comment]
@tracker1 ctrl+shift+c as in open external terminal? Does just nothing happen? Can you open devtools (help menu) and see if there are errors in the console?

**Comment by tracker1** [comment]
@Tyriar I think it may be another application is capturing global ctrl+shift+c ... no idea which one though.
