### ISSUE TITLE
[undo] Fold commands can't be undone

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#92667]
Issue Type: <b>Bug</b>

Fold commands like Fold Level 1 cannot be undone with ctrl + z.

VS Code version: Code - Insiders 1.44.0-insider (efd7548df65de8e775015b67863190e6bd4934fc, 2020-03-13T06:05:25.782Z)
OS version: Windows_NT x64 10.0.18363

**Comment by awhlmycn** [comment]
@aeschli  tthank you

**Comment by awhlmycn** [comment]
@aeschli  thank you
