### ISSUE TITLE
Strange behaviour of the hover tooltip when it is disabled (it disappears).

### ISSUE THREAD

**Issue by Mikhail22** [microsoft/vscode#92665]
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

How to reproduce:

I have disabled the hover tooltip, using this option:

```
    "editor.hover.enabled": false,
    "editor.hover.sticky": true,
```

Now the problem is that when I invoke the tooltip manually, **it dissapears immediately 
when I move the mouse cursor**. But it should be shown?
"hover.sticky" does not change anything.

I've found a workaround for now, just by setting a huge delay:

`	"editor.hover.delay": 300000,`

So it all works as I expect. 
But the "enabled" option does not work with "sticky"? 
Is it a bug or I misunderstood the "sticky" option?

**Comment by Mikhail22** [comment]
Also note: the hover delay currently cannot be set to arbitrary amount of ms,
I guess it is overriden by the internal max setting of 10000 ms,
meaning you can't set any bigger delay.

**Comment by dmakhun** [comment]
Have the same issue, but delay workaround doesn't work for me, hover disappears right after moving a cursor, it's only scrollable when the cursor was in the scope of a hover before calling it.
Are there any updates on this?

**Comment by Mikhail22** [comment]
> Have the same issue, but delay workaround doesn't work for me, hover disappears right after moving a cursor, 
Try to set hover.delay only (set  "editor.hover.enabled" : true or remove it from settings). But as said, it is only up to 10 seconds max.
