### ISSUE TITLE
"diffEditor.originalEditable" setting no longer works

### ISSUE THREAD

**Issue by BernardoFBBraga** [microsoft/vscode#92664]
![Screenshot from 2020-03-13 16-03-45](https://user-images.githubusercontent.com/3694228/76651944-4ea77400-6544-11ea-8ec6-aa46ca4a6852.png)
Previously, as I can see in the history of issues and from my personal experience, it was possible to edit the git diff on the left side.
however this is no longer possible
From the comments in the other issues, this is a very popular demand

**Comment by bpasero** [comment]
@BernardoFBBraga you no longer need this setting, if the left hand side of the diff editor is not readonly, you can edit. What are the exact steps to get to where you are where you cannot edit?
