### ISSUE TITLE
Explorer scroll tree by levels

### ISSUE THREAD

**Issue by PMoransais** [microsoft/vscode#92661]
Issue Type: <b>Feature Request</b>

In visual studio there is a feature that lets you make a node in the tree become the root, thus simplifying navigation when working on just one area of the tree.

Have you given thought about another way to provide similar functionality such as a left arrow button to move the tree left so that all level 2 nodes would show against the left border with a right arrow button.
The feature does not need to be limited to one tree level. 
It could be thought as a specialized scrollbar but scrolling a whole tree level at a time.

Thanks

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
You can always reopen that element in a new window and make it a root.
If there is not context action for that an extension could easily add it.
I can leave this feature request open though we have no plans to add this atm.
