### ISSUE TITLE
Format on paste should format only the pasted text instead of whole interface

### ISSUE THREAD

**Issue by wojpawlik** [microsoft/vscode#92670]
0. `"[typescript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" }`, `"editor.formatOnPaste": true`,

1. Open https://github.com/telegraf/telegraf/blob/develop/typings/index.d.ts,

2. Paste `foo()` into any of the interfaces,

3. Expectation: only `foo()` gets formatted.
Reality: entire interface gets formatted.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
ignoregit|And|1.0.1
vscode-node-readme|ben|3.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
auto-rename-tag|for|0.1.1
fontsize-shortcuts|fos|1.5.0
vscode-pull-request-github|Git|0.15.0
latex-workshop|Jam|8.7.2
vscode-commitizen|Kni|0.8.4
regex-railroad-diagrams|kog|0.2.4
calculator|lix|0.1.1
git-graph|mhu|1.21.0
sublime-keybindings|ms-|4.0.6
printcode|nob|3.0.0
livescript|pse|0.1.1
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|0.11.0
code-settings-sync|Sha|3.4.3
quokka-vscode|Wal|1.0.282

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
