### ISSUE TITLE
Saved changes not appearing in Git Changes

### ISSUE THREAD

**Issue by andpeterson** [microsoft/vscode#92673]
- Visual Studio Code Version: [e.g. 1.43.0]
 - Operating System: [MacOS 10.15.3]

Steps to Reproduce:
Not entirely sure what the steps to repo are as this appears to possibly be an edge case bug. More details shortly 
1. Create a new branch off of master using Git Graph Extension
1. Modify and save changes to a file
1. Open Git Panel and observe that no changes appear in changes

Update: The problem resolved itself. Its possible the polling for a change took a long time to either find a change or just it doesn't poll often?

I'm curious what others have to say about those possibilities. I'll update with more details if I see the issue occur again.
Feel free to close this issue if you don't have anything to add

This issue seems to be similar similar to: https://github.com/microsoft/vscode/issues/70953

**Comment by andpeterson** [comment]
Quick update. I'm seeing this issue more consistently now. I frequently have to manually press the refresh button for VSCode to pick up that a file was modified.

**Comment by joaomoreno** [comment]
You seem to be missing file events. Please go through the following steps:

1. Run `Git: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Reproduce the issue and wait 10-20 seconds
4. Paste the whole output here
