### ISSUE TITLE
Debug extensions on Windows is painfully slow

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#9267]
- VSCode Version: 1.4.0-Insider and 1.3.0
- OS Version: Windows 10 x64.
- Node.js Version: 6.3.0

Steps to Reproduce:
1. Download [VSCodeVim](https://github.com/VSCodeVim/Vim/) or [vscode-encourage](https://github.com/rebornix/vscode-encourage)
2. `npm install && npm run compile`, set breakpoints.

When I debug VSCodeVim, the breakpoint is hit but seems VS Code has a hard time requesting for variables and call stacks.

![image](https://cloud.githubusercontent.com/assets/876920/16834968/d486d28a-49e8-11e6-8344-93117b9f308e.png)

See the image above, the debug pallete shows the breakpint is already hit but no line is highlighted and the variables/call stack sections are still empty. It usually took me minutes to see the call stack.

When I debug my encourage extension, run into the same situation.

![image](https://cloud.githubusercontent.com/assets/876920/16835008/0b852e80-49e9-11e6-8a53-830c2913eb9c.png)

See the debug  pallete and call stack pane.

Previously I ran into this situation on Lenovo X1C with Windows 10 x64. Now I just set up dev env on my new Dell XPS 13 today and still see the problem. The debugging works perfectly on OSX.

Can anyone help provide me some steps to troubleshoot or gather logging about this issue?

**Comment by rebornix** [comment]
Downgrade Nodejs to v4.4.7 LTS and the problem is gone. It's likely a node issue. Keep this open for further investigation.

**Comment by weinand** [comment]
@rebornix we have not verified that VS Code works with node 6.3 (and I've seen already bugs related to that version). When debugging extensions please use the same version of node that electron uses (currently 5.10.0).

**Comment by rebornix** [comment]
Reinstall Nodejs and this time I used 5.10.0, played with Code for five days and this problem still exists in Insider but it's gone in Stable.

**Comment by rebornix** [comment]
More information here, seeing below in Console

```
[Extension Host] ApplicationInsights:Sender Array[1]
0: Object
     address: "111.221.29.254"
     code: "ETIMEDOUT"
     errno: "ETIMEDOUT"
     port: 443
     syscall: "connect"
     __proto__: Object
     length: 1__proto__: Array[0]
```
