### ISSUE TITLE
Same file opened on different path if a symlink exists one path

### ISSUE THREAD

**Issue by reporter123** [microsoft/vscode#92679]
- VSCode Version:1.43.0
- OS Version: Linux x64 5.3.0-generic

Steps to Reproduce:

1. Create a main.cpp at /usr/local/src
2. Symlink /usr/local/src to ~/src
3. Open ~/src in vscode
4. Open "main.cpp" via "Explorer" sidebar
5. Set a breakpoint.
6. Launch debugger.

The debugger will open a new copy of the file via its resolved absolute location /usr/local/src/main.cpp. The copy opened via "Explorer" uses a relative or unresolved path yielding 
~/src/main.cpp.
I would expect the symlink to be resolved when checking to see if these are the same file.

Does this issue occur when all extensions are disabled?: No need a debugger to reproduce.

**Comment by gjsjohnmurray** [comment]
/duplicate see https://github.com/microsoft/vscode/issues/34627#issuecomment-577968271
