### ISSUE TITLE
Auto Complete Problem

### ISSUE THREAD

**Issue by AlexPeake** [microsoft/vscode#92674]
Issue Type: <b>Bug</b>

Using Python.
import numpy as np<Enter>

It changes np to numpy
Wrong!

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
azds|azu|2.0.220200302
githistory|don|0.6.2
vscode-azurefunctions|ms-|0.21.0
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.1.0
mssql|ms-|1.9.0
python|ms-|2020.2.64397
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
vscode-yaml|red|0.7.2
scala|sca|0.3.9
python|tht|0.2.3

</details>

**Comment by mjbvz** [comment]
Please file this against the python extension
