### ISSUE TITLE
VS Code creates .browse.VC.db and .browse.VC.db-wal

### ISSUE THREAD

**Issue by tsolarin** [Microsoft/vscode#9268]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Open a new folder in VS Code that doesn't have `.vscode` folder.

Expected Behaviour:

1. Should leave the folder as is or give notification to setup additional tools e.g. .NET Core debugger

Actual Behaviour

1. Creates a `.vscode` folder containing `.browse.VC.db` and `.browse.VC.db-wal` files.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by tsolarin** [comment]
Thanks @bpasero turns out it was the C++ vscode extension. Removing it did the trick.
