### ISSUE TITLE
'new vscode.CompletionItem' starting from number immediatly closes the completition dialog

### ISSUE THREAD

**Issue by wzykio** [microsoft/vscode#92680]
Hello,
It seems that 

> new vscode.CompletionItem('10', vscode.CompletionItemKind.Text),

will close the completition dialog upon typing first digit '1'

> new vscode.CompletionItem('o10', vscode.CompletionItemKind.Text),

will keep the visibility of the dialog while typing.

Compilation: February 2020 (version 1.43)

**Comment by jrieken** [comment]
Use the `CompletionItem#range`-property in combination with the `filterText`-property for cases like this
