### ISSUE TITLE
Every time a new version came, VS code trying to install the Omnisharp again, wasting a lot of time.

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode#92682]
It's look like when a new vs code version came and it's get upgrade, it's trying to download all thing again like Razor Language, Omnisharp kind of things.

This is not good. Suppose someone have working setup and mistakenly it's getting update, now I need to wait for getting it fixed.

The omnisharp kind of thing is not utilizing the full internet so it will take a lot of time, Result in non-working piece of software.

**Comment by anirugu** [comment]
the version is latest one that is updated yesterday.

**Comment by aeschli** [comment]
Please file this against https://github.com/OmniSharp/omnisharp-vscode
