### ISSUE TITLE
Add ability to open files with the OS's default application

### ISSUE THREAD

**Issue by astier** [microsoft/vscode#92689]
I want to reopen the issue  #75188. It is about adding the ability to open files with the OS's default applications from within vscode. For example pdf-files. The program xdg-open could be used to determine the default applications on linux.

Here is what the original author @nabeelomer wrote:

> 
> A context menu option can be added to the file browser that allows files to be opened in the default application for that file type. For example if the file is a PDF document, opening the context menu and click "Open with desktop" will open the file with the default PDF reader.
> 
> This can be accomplished with the openItem() method from Electron's shell module.
> 
> I am aware that this particular feature has been suggested before in #50383 and #45989 but my suggestion is not the same as that.

I am using vscode 1.42.1

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Though I still believe this should be done via an extension. Thanks
