### ISSUE TITLE
Bug on Linux for Latest VSCode 1.43

### ISSUE THREAD

**Issue by MostafaMTH** [microsoft/vscode#92688]
There is a bug with rendering VSCode's editor since 1.43, when launching the window starts blank white. Then it continues normally but when i click on for example file or edit, its white then loads. I have a Ryzen 7 2700X and RTX 2060.
- VSCode Version:1.43
- OS Version: Manjaro 19.0.2 and also found it on Solus 4.1 I did not try it with other distros though so i dont know

Steps to Reproduce:

1.Make sure you are on Visual-Studio-Code  version 1.43
2.Launch the editor and must be on Linux
3. Press on file or anything and you should see a white screen then it loads.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by deepak1556** [comment]
@MostafaMTH can you try disabling hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if it still crashes. Thanks!
