### ISSUE TITLE
Debug Console mutiple statement lines input

### ISSUE THREAD

**Issue by iaso2h** [microsoft/vscode#92685]
Issue Type: <b>Feature Request</b>

Hi? I was wondering it is possible to evaluate mutiple mutiple statement lines at the same time?

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Yes it is possible, just use shift + enter to have multiline debug console input and evaluate whatever you want.
If the debug extensions does not nicely evaluate it then please file an issue against the debugger you are using. Thanks
