### ISSUE TITLE
Option to disable line numbers in search editor

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#92698]
When I get my search results to show in a search editor, most of the time I copy it to reuse in other part of my code base. If the line number can be hidden (which don't offer much use anyway), this scenario can be improved.

### The latest version of VS Code I've confirmed to not have this feature
Version: 1.44.0-insider
Commit: efd7548df65de8e775015b67863190e6bd4934fc
Date: 2020-03-13T06:01:51.669Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by ArturoDent** [comment]
Just a partial workaround in the meantime: the column selection mode might work for you in many instances.

**Comment by JacksonKearl** [comment]
> which don't offer much use anyway

In fact the line number is the means by which we link lines to their locations in the source text, so it must be present. 

An extension however could implement a command to filter out the line numbers on copy/paste. Or use column selection as noted above.

**Comment by ssbarnea** [comment]
@JacksonKearl I don't see any practical use for including the line:column prefix when someone does a right click copy on search results.
