### ISSUE TITLE
Fuzzy font in integrated terminal after resize

### ISSUE THREAD

**Issue by larsch** [microsoft/vscode#92693]
When resizing the main window, the font in the integrated terminal ends up fuzzy, seemingly dependent on the exact pixel size of the window. If adjusting by a few more pixels, it sometimes returns to normal rendering.

- VSCode Version: 1.43
- OS Version: Windows 10 1909

Steps to Reproduce:
1. Open integrated terminal
2. Resize main window by a few pixels

Used font: Fira Code, Font size: 11.5/12. Also occurs with Consolas font.

Here's the same window, resized in between each screensnip:

![IntegratedTerminal1](https://user-images.githubusercontent.com/15712/76683433-49a9f980-6604-11ea-97b5-b748f5363c40.png)
![IntegratedTerminal2](https://user-images.githubusercontent.com/15712/76683434-4a429000-6604-11ea-92e6-3a573277c1cf.png)
![IntegratedTerminal3](https://user-images.githubusercontent.com/15712/76683435-4adb2680-6604-11ea-8c77-63f2041dd30e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Do you have `window.zoomLevel` in your settings?

**Comment by larsch** [comment]
> Do you have `window.zoomLevel` in your settings?

Yes I did (value: 1). Problem gone after removing.

Didn't seem to make editor text fuzzy in the same way.

**Comment by Tyriar** [comment]
@larsch the editor is drawn using the DOM, the terminal uses canvas (unless you set it to the slower dom renderer). AFAIK there isn't a way to fix this one off rounding error that causes the blurriness when you scale the browser window. Closing as designed for now, I encourage setting fontSize settings instead of zoomLevel to avoid this.
