### ISSUE TITLE
Add ability to subscribe on settings changes

### ISSUE THREAD

**Issue by acherkashin** [microsoft/vscode#92699]
Hi, 

I was trying to find event to react on settings change, unfortunately I didn't find it. It would be cool to have an ability to update some data in extension (which depends on settings), when settings have been changed.

To get some context. I'm trying to integrate mp3 player to vs code to listen music inside (https://github.com/acherkashin/yandex-music-extension). I have added setting "Rewind time", to allow user adjust rewind time. Consequently, When user change it I will need update some data (buttons tooltips)  which use settings data.

Besides that, There are credentials "username"/"password". When user change it I need to change playlists and other things which depends on it.

I will really appreciate If you suggest me solution or add such ability to listen settings change. Thanks!

My VS Code Version:

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by acherkashin** [comment]
Version has been added.

**Comment by sandy081** [comment]
See - https://github.com/microsoft/vscode-extension-samples/tree/master/configuration-sample
