### ISSUE TITLE
File/Text search cancellation fails

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#927]
We should introduce real cancellation tokens for the search API instead of relying on the promise cancel which can easily get lost with all the chaining.

- [x] fix throttled-delayer use to cancel a search when typing and revisit 100ms delay
- [x] consider adopting a maxResults for quick open too

**Comment by bpasero** [comment]
Maybe verify by looking at the CPU when you run quick open and verify that it stops for a large workspace when you close quick open widget.

**Comment by aeschli** [comment]
I tried to see anything strange in the process explorer, but all looked normal.
