### ISSUE TITLE
Snippet Choice not accepting variables

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode#92703]
Issue Type: <b>Bug</b>

I'm trying to create this snippet but the choie won't accept the variable I'm passing after package.
`
"Create Class Main": {
		"description": "Create a java class definition with a main method inside.",
		"prefix": "classmain",
		"body": [
			"${1|/**,package ${TM_DIRECTORY};\n/**|}",
			"* ${TM_FILENAME_BASE}",
			"*/",
			"public class ${TM_FILENAME_BASE} {",
			"",
			"    public static void main(String[] args) {",
			"",
			"        $0",
			"    }",
			"}"]
	}
`

VS Code version: Code - Insiders 1.44.0-insider (efd7548df65de8e775015b67863190e6bd4934fc, 2020-03-13T06:06:14.299Z)
OS version: Linux x64 5.3.0-40-generic
Remote OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2134)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.35GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Java 12|
|OS|Linux x64 5.3.0-40-generic|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2134)|
|Memory (System)|7.67GB (0.35GB free)|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
read-only-indicator|ale|3.1.0
gitkraken-glo|axo|1.1.0
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.34.0
git-extension-pack|don|0.1.3
githistory|don|0.6.2
gitlens|eam|10.2.1
vscode-docker|ms-|1.0.0
resourcemonitor|mut|1.0.6
embrace|myc|1.0.0
java|red|0.58.0
markdown-preview-enhanced|shd|0.5.2
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.1
vscode-wakatime|Wak|4.0.0
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6
html-snippets|abu|0.2.1
project-manager|ale|10.11.0
bracket-pair-colorizer|Coe|1.0.61
vscode-firefox-debug|fir|2.7.0
remote-containers|ms-|0.107.0
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.6
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
vscode-icons|vsc|10.0.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by ArturoDent** [comment]
Snippet choices can't use variables.  See https://github.com/microsoft/vscode/issues/87949
