### ISSUE TITLE
Extension host terminated unexpectedly 

### ISSUE THREAD

**Issue by alicelnx** [microsoft/vscode#92707]
Issue Type: <b>Bug</b>

I have disabled all my extensions, even uninstalled them and reinstalled vs code but I still get the same error.. 

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
@alicelnx Can you please provide us with the extension host log that can be found under `F1 > Developer: Show Logs... > Extension Host` ?

**Comment by alicelnx** [comment]
Hi , do you mean this ?
[image: Screenshot (20).png]

**Comment by alexdima** [comment]
@alicelnx Please use the web ui at https://github.com/microsoft/vscode/issues/92707 . I cannot see any attachment. In the web ui you can upload text files.

**Comment by ShirshaDatta** [comment]
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/46640977/79072570-51da7f00-7cff-11ea-943f-58a0ccef09b4.PNG">


I have disabled all my extensions, even uninstalled them and reinstalled vs code but I still get the same error

**Comment by alexdima** [comment]
@ShirshaDatta Your issue is unrelated to the initial poster, because the initial poster was about 1.43. Please see https://github.com/microsoft/vscode/issues/94858#issuecomment-611924064
