### ISSUE TITLE
I can't get the extensions list

### ISSUE THREAD

**Issue by Sarctiann** [microsoft/vscode#92702]
Issue Type: <b>Bug</b>

i can`t get the extensions list. so i can`t install them. I'm using Mac OS 10.13.5

ERR net::ERR_FAILED: Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
workbench.desktop.main.js:1647   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
@Sarctiann can you launch code with `--log-net-log=netlog.json` and perform an extension search, quit the app and attach the json log. Thanks!

**Comment by Sarctiann** [comment]
Good afternoon, I solved the problem!! Was my connection settings, something with the proxi

Enviado desde mi iPhone

**Comment by 3v1n0** [comment]
Looks like something similar to me, but mostly related to some configuration issue.

In fact, using `HOME=/tmp/foobar` to launch the vscode snap works fine, even if I use as user-directory the one in my home and even I've sym-linked my `~/.vscode` to `/tmp/foobar/.vscode`, so nothing in vscode config itself seems to be wrong, but there's some local setting affecting it.

This is weird though, as being vscode the only app that doesn't work properly.

**Comment by deepak1556** [comment]
@3v1n0 which version of vscode are you seeing the issue with ? And what was the last version you see it working fine ?

The netlog shows you are behind proxy, how are you configuring it for vscode ?
