### ISSUE TITLE
I want the vscode for Mac UI to be as simple as the vccode for Windows

### ISSUE THREAD

**Issue by microestc** [microsoft/vscode#92708]
I want the vscode for Mac UI to be as simple as the vccode for Windows, with the toolbar and controls not too wide and as narrow as possible, and the interface for Windows to be fine.

**Comment by microestc** [comment]
Version: 1.43.0

**Comment by microestc** [comment]
set zoom  -1, still too wide and incongruous

**Comment by sbatten** [comment]
most of the UI is exactly the same in regards to dimensions. if it is wide, perhaps your scaling is much higher on macOS?

**Comment by microestc** [comment]
You may be right, but the macbook pro's 2880x1800 physical resolution is still too wide for the Max zoom display on the macos, which is probably only perfect for the iMac's 5k resolution

**Comment by microestc** [comment]
It may be that I am too particular about my requirements

**Comment by sbatten** [comment]
I am still not sure I understand. Can you zoom out more inside vscode? The dimensions are proportionately the same between platforms.
