### ISSUE TITLE
How can i get the terminal status when i used in vscode API?

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#92712]
I'm using vscode API to develop an extension and i create a terminal in the code. When running the extension , it will create the terminal as expect. But you know , I can close the terminal in the vscode window. After close the terminal , It still shows in the api that the terminal is open but i can't use it. So if there is a method that i can know the terminal is been killed in the API please ? Thanks a lot .

**Comment by Tyriar** [comment]
Here it is, it's pretty new:

https://github.com/microsoft/vscode/blob/3764d68e3b26fb8bd954ab61adef71a260f060e3/src/vs/vscode.d.ts#L5269-L5282

**Comment by Abbyyan** [comment]
> vscode/src/vs/vscode.d.ts

Thanks a lot. Which version of the api should i install please?

**Comment by Tyriar** [comment]
Somewhere around 1.41-1.43

**Comment by Abbyyan** [comment]
> Somewhere around 1.41-1.43

I've found in the https://code.visualstudio.com/updates/v1_44 that the latest version is 1.44xx; But when i package the vsix, it occurs such error `@types/vscode 1.41.1 greater than engines.vscode ^1.44.0. Consider upgrade engines.vscode or use an older @types/vscode version`. Which version of the ` engines.vscode` should i specified please ? Thanks a lot.

**Comment by Tyriar** [comment]
Typically you want to set both engines and types to the minimum version you want to support.

**Comment by Abbyyan** [comment]
> Typically you want to set both engines and types to the minimum version you want to support.

How can i know the minimum version support `@types/vscode 1.41.1` ? I've checked my vscode which is `1.44.0` and is updated in 2020, but it still doesn't work. Please give me some suggestions if possible . Thanks a lot .

**Comment by Tyriar** [comment]
@Abbyyan just set both to 1.44.0

**Comment by Abbyyan** [comment]
> > Typically you want to set both engines and types to the minimum version you want to support.
> 
> How can i know the minimum version support `@types/vscode 1.41.1` ? I've checked my vscode which is `1.44.0` and is updated in 2020, but it still doesn't work. Please give me some suggestions if possible . Thanks a lot .


> @Abbyyan just set both to 1.44.0

It really works. Thanks a lot !
