### ISSUE TITLE
Broken Syntax Highlighting for Javascript

### ISSUE THREAD

**Issue by Offpics** [microsoft/vscode#92714]
- VSCode Version: 1.43
- OS Version: Windows and Linux
- Color Theme: Dark+

Steps to Reproduce:

1. Open any javascript file within vscode

Does this issue occur when all extensions are disabled?: Yes

In earlier version the `document` object was highlighted with green color, now it's just blank.

**Expected Behaviour**
![](https://i.imgur.com/qVGi4VL.png)

**Actual Behaviour**
![](https://i.imgur.com/9PpWS74.png)

---

When you apply Dark+ color theme you can see `console` is colored green at first but then is overwritten with blank color. Gif included.

![](https://i.imgur.com/TtfBfV4.gif)

**Comment by gjsjohnmurray** [comment]
/duplicate of #90379

As a workaround you could disable semantic highlighting.

**Comment by Offpics** [comment]
@gjsjohnmurray 

For others, disable semantic highlighting by adding this line to the settings.json.
`"editor.semanticHighlighting.enabled": false`
