### ISSUE TITLE
Yellow Border  from VS CODE after cloning a git repository

### ISSUE THREAD

**Issue by JSierra0918** [microsoft/vscode#92723]
Like the title says, my VS Code border changed to this yellow after cloning a git repository.  I've tried changing themes, but all this does is change what's inside the yellow borders.  I'm sure there's a way to change the color, but I can't find how to change it.  I'm attaching an image to show what it looks like.

![Annotation 2020-03-15 105514](https://user-images.githubusercontent.com/47343394/76704181-7c5bfc80-66ad-11ea-82be-0927c88d0831.png)

**Comment by rebornix** [comment]
@JSierra0918 can you check your user setting or workspace settings or project settings (under .vscode folder in the project) to see if you have any settings related to theme customization?

**Comment by JSierra0918** [comment]
I was able to resolve the issue.  Turns out the guy repository was also
including a user setting in this weird folder.  I deleted it and it seems
to be working now
