### ISSUE TITLE
Watch requires up too much horizontal space, should utilize second line for values

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#92729]
Issue Type: <b>Bug</b>

The following is essentially useless:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/6913354/76707247-cabbcc00-66aa-11ea-923c-dcc62a56b584.png">
EXPECTED: it should place the value on the next line, so that I can at least see some of the value

Otherwise I have to expand the width of the watch window to take half of my debugging space in order to see something useful:
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/6913354/76707275-f9d23d80-66aa-11ea-84b4-f4e9ca534517.png">

VS Code version: Code - Insiders 1.44.0-insider (efd7548df65de8e775015b67863190e6bd4934fc, 2020-03-13T06:01:51.669Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|-psn_0_94231|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
todo-tree|Gru|0.0.169
vscode-antlr4|mik|2.2.3
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.14
vscode-dotnet-runtime|ms-|0.1.0-alpha-546387
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
azure-account|ms-|0.8.8
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.9.0-alpha
tmcolor|sle|0.0.1
vscode-todo-highlight|way|1.0.4
arm-params-generator|wil|0.8.1

</details>

**Comment by ArturoDent** [comment]
A workaround is to move the watch view to the bottom panel to utilize its width.  Right-click on the "watch" title area and select "Move to Panel."

**Comment by isidorn** [comment]
I like this workaround for now. Though leaving this open as it is a fair feature request.

**Comment by StephenWeatherford** [comment]
Okay, that workaround really helps, thanks!

**Comment by isidorn** [comment]
Closing as out of scope since our recommendation is to move it to a bottom panel
