### ISSUE TITLE
"JS/TS Language Services" won't start

### ISSUE THREAD

**Issue by andrewfluck** [microsoft/vscode#92722]
Issue Type: <b>Bug</b>

I open any TS or JS file. I notice my disk space goes down rapidly as this happens as well, RAM also spikes severely.

VS Code version: Code - Insiders 1.44.0-insider (efd7548df65de8e775015b67863190e6bd4934fc, 2020-03-13T06:01:51.669Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 4|
|Memory (System)|16.00GB (4.37GB free)|
|Process Argv|-psn_0_516222|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Are you using VS Code's bundled TS version or a custom one? Does this happen in all folders you open?

**Comment by andrewfluck** [comment]
It actually stopped happening after a day or so, thank goodness.

**Comment by mjbvz** [comment]
Ok, let me know if you start seeing this again
