### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by myuanqing** [microsoft/vscode#92726]
Issue Type: <b>Bug</b>

I changed my directory's name which is under User directory. As a result, when I try to update vscode, it's reported that installation directory cannot be created. It's obvious that you don't set the path in the form of an environment variable. Is there a way for me to change the path?

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Yes, uninstall VS Code and install it in the new path.
