### ISSUE TITLE
Maximizing integrated terminal causes scrollbar bug

### ISSUE THREAD

**Issue by ignatiusmb** [microsoft/vscode#92721]
Issue Type: <b>Bug</b>

Opening integrated terminal with `` Ctrl + ` `` and then maximizing works fine, but I've assigned a shortcut to immediately maximize the panel and the scrollbar moves to the middle left of the terminal and stays there until I reopened it using `` Ctrl + ` `` again.

This didn't happen before 1.43 update and I've tried reloading without extensions enabled and still get the same results so it couldn't be the extensions. I've tried this with my laptop, pc, and friends macbook all producing the same results so I don't think it's system dependent too.

Steps to reproduce:
1. Open any VS Code workspace
2. Have a keyboard shortcut assigned to the Toggle Maximized Panel at `workbench.action.toggleMaximizedPanel`
3. Open and use the terminal until you can scroll through it
4. Hide the terminal and use the keyboard shortcut to reopen it

## Using WSL
![image](https://user-images.githubusercontent.com/8156777/76703183-5b71c680-6702-11ea-8c4a-3f9bc01c024e.png)

## Using Windows CMD
![image](https://user-images.githubusercontent.com/8156777/76703202-80663980-6702-11ea-8c7a-e1128c333519.png)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.19536
Remote OS version: Linux x64 4.19.81-microsoft-standard

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
