### ISSUE TITLE
Expect to be able to use UI to move relative symbolic links

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode#92731]
Create a symbolic link `ln -s ../still/in/the/repro/foo.js foo.js` to a file using a relative path such that the link and its target remain in the git repo. Try to use VS Code to move the link from one directory to another. 

I expect VS code will detect the symbolic link is relative and pointing to a file in the repro and so will "move" the link by deleting the old link and creating a new link with a relative path that points to the same target but from the directory into which I dragged the linked file. 

What actually happens is that the link is deleted but no new link is created presumably because VS code doesn't like to display UI for the now broken link (which is a separate bug #44908 which would make sense to fix if this were also fixed).

**Comment by kingces95** [comment]
Version `Version 1.25.1 (1.25.1)`

**Comment by gjsjohnmurray** [comment]
Please update to latest version (1.43) and retest.

**Comment by kingces95** [comment]
Tried updating but it says I'm on the latest. I'm running on a mac.

**Comment by gjsjohnmurray** [comment]
What macOS version?

**Comment by kingces95** [comment]
10.14.6

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469 for advice on how to update.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
