### ISSUE TITLE
Error Ebusy

### ISSUE THREAD

**Issue by AndreaDemSeferi** [microsoft/vscode#92730]
Issue Type: <b>Bug</b>

Hi , when i wanna wanna save file I get this
Failed to save 'Document.html': Unable to write file 'c:\Users\dator\Desktop\testing\Document.html' (Unknown (FileSystemError): Error: EBUSY: resource busy or locked, open 'c:\Users\dator\Desktop\testing\Document.html')

Why is this happening how can I fix it

Greetings Andrea

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
/question Another app has the file open.

**Comment by AndreaDemSeferi** [comment]
What file? I restarted my pc and it doesn't do that anymore. I had open Git Bash open is that because of that?

**Comment by AndreaDemSeferi** [comment]
It does that again no apps open

**Comment by AndreaDemSeferi** [comment]
I was opening it with opera and now that i switched to Internet Explorer it went away. What is the reason this happens?

**Comment by gjsjohnmurray** [comment]
Sounds like Opera locks the file.

**Comment by AndreaDemSeferi** [comment]
Same things happens now again with internet explorer. Any idea how to unlock it?

**Comment by gjsjohnmurray** [comment]
Are you viewing the HTML document through a local webserver? Maybe it is locking the file.

Anyway, I don't see that this can be a VS Code issue. I suggest you use [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to investigate.

**Comment by AndreaDemSeferi** [comment]
This happens mostly when I add a picture at the file it says some pictures have been blocked to help prevent the sender from identifying your computer u have any solution please it not a local webserver
