### ISSUE TITLE
Add a cache busting parameter to vscode.workspace.getConfiguration()

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#92733]
When I gather the workspace configuration from the API `vscode.workspace.getConfiguration()` I would like it to get those values from whatever is in the workspace file. See the code below for an example. 

However, this code seems to be retrieving the values form a cache.

Scenario:

- the user change the order in which the entries of the workspace settings appear in the file
- the user then runs a command in my extension that changes one of those workspace settings
- my extension then reads the existing values and updates one of those values

The result is that the sequence in which te settings appear is reverted to an earlier state, prior to when the user changed the sequence.

Th expectation is that it leaves them in the same sequence.

Why is this important? Because users sometimes re-order workspace settings and want the order to stay the same.

*Proposal:*

If this API caches values (which appears to be happening), can an optional argument be passed to bust the cache and make it read from disk again?

- Add a cache busting parameter to `vscode.workspace.getConfiguration()` or the `inspect` method.

```typescript
export function getColorCustomizationConfigFromWorkspace() {
  const inspect = vscode.workspace.getConfiguration().inspect(Sections.peacockColorCustomizationSection);

  if (!inspect || typeof inspect.workspaceValue !== 'object') {
    return {};
  }

  const colorCustomizations: ISettingsIndexer = inspect.workspaceValue as ISettingsIndexer;
  return colorCustomizations;
}
```

**Comment by johnpapa** [comment]
I found a workaround ... I need to cache bust in this scenario. So I run this code:

```typescript
async function bustTheCache() {
  /**
   * Workaround: The following code forces VS Code to read the
   * workspace configuration fresh from the disk.
   * We change a value in the workspace (peacock.cacheBust),
   * which forces VS Code to read it again next time.
   *
   * If VS Code either stops caching or implements a way to
   * bust the cache so we can read the workspace configuration
   * fresh from the disk, then we can remove this code
   */
  const config = vscode.workspace.getConfiguration();
  const section = `${extensionShortName}.${StandardSettings.CacheBust}`;
  const cachebuster = Math.floor(Math.random() * Math.floor(1000000)).toString();
  await config.update(section, cachebuster, ConfigurationTarget.Workspace);
}
```

This is a hack ... I am adding a property to the workspace and changing tis value. I dont care about the value and do not use it 

Problems with this:

- It feels dirty
- I had to add a property to my extension's API for `cacheBust`
- users will see the property in Settings UI (tho I gave it a description telling them to ignore it)

I much prefer a way to bust the cache in the existing API.

**Comment by sandy081** [comment]
@johnpapa 

> Scenario:
the user change the order in which the entries of the workspace settings appear in the file
the user then runs a command in my extension that changes one of those workspace settings
my extension then reads the existing values and updates one of those values
The result is that the sequence in which te settings appear is reverted to an earlier state, prior to when the user changed the sequence.
Th expectation is that it leaves them in the same sequence.

Can you please provide a concrete example to understand what you mean?

**Comment by johnpapa** [comment]
Sure. Here is the code I added, then removed, to make cache busting work: https://github.com/johnpapa/vscode-peacock/commit/97e36ec17736366d674aa29b1f96ed0e90f47f39

With Peacock, people may change the order of the color customizations in the workspace file. The steps are

-  you open the file and move the settings (change their order)
- then you change a color in Peacock.
- Peacock reads the existing file (using the inspect API)
- Peacock takes that list and sets the colors to the new colors
- Peacock then tries to write the settings back to the file

The problem is that when peacock reads the file, it is not getting the new order that the user made. If you try this in peacock, you can see it happening.

**Comment by sandy081** [comment]
> you open the file and move the settings (change their order)

Can you please let me know which settings you mean? It would be great if we can break it down to a simple example that can be reproducible.

**Comment by johnpapa** [comment]
The workbench color customizations settings on the workspace settings

**Comment by sandy081** [comment]
So if I understand correctly - the request is to trigger a change event even if the settings order is changed? But I think this should be scoped to values of the settings but not the order of top level settings./
