### ISSUE TITLE
Can't stop vscode from auto updating

### ISSUE THREAD

**Issue by Ziriax** [microsoft/vscode#92735]
- VSCode Version: 1.40
- OS Version: Windows 10

Steps to Reproduce:

1. Install an old version (I installed 1.40)
2. Disable auto updating (put it to `manual` or `none` in prefs)
3. Work for a couple of days, re-opening vscode a couple of times
4. Notice that vscode will auto-update to a newer version, even if disabled.

I need to disable updates until #89294 is fixed, but for some reason, vscode keeps updating itself. I have this on 3 different systems.

**Comment by Ziriax** [comment]
I found something odd.

In the config panel, I noticed two versions of vscode.
- 1.40, the one I installed using the "system" setup.
- 1.42, that got automatically upgraded, but as a "user" setup.

**Comment by mjasnikovs** [comment]
Same issue, want to stick at version 1.42.1. As new versions are broken... But have to manually re-install every time i reopen vscode.

**Comment by joaomoreno** [comment]
@Ziriax Please uninstall both versions. Install just one and let me know if you still see this issue.

**Comment by Ziriax** [comment]
Since I the used the user installer, I don't have the issue anymore. 

Maybe the system installer that I normally use updated using the user installer, and caused this issue, I am not sure.

**Comment by mjasnikovs** [comment]
Still, auto updated after new version came out. So typical for Microsoft, force users do shit they don't want to do.

I uninstalled and fully reinstalled VS code, it kept it from updating to current newest version. Then newer version came out. And it auto updated. Update mode was set to none.
