### ISSUE TITLE
Fira Code broken on every VSC startup

### ISSUE THREAD

**Issue by exoRift** [microsoft/vscode#92744]
Every time I start up VSC on my Windows 10 PC, my font is completely broken. I'm using Fira Code Regular and to resolve the problem, I have to delete the font from the Control Panel and reinstall it and then restart Code. However, the next time I start up my PC and start VSC, it's broken again.

Disabling extensions does not resolve the issue.

**Comment by rebornix** [comment]
@mets11rap does Fira Code work in other applications ?

**Comment by mets11rap** [comment]
I haven't tested that out. I'll let you know tomorrow when I start my computer back up.

**Comment by mets11rap** [comment]
So, switching to Retina resolved the issue. It looks the exact same as Regular so I guess the problem is resolved? Just get Retina instead of Regular if Regular doesn't work.

**Comment by mets11rap** [comment]
@rebornix Alright, Retina didn't fix the issue. I tried testing the font in Notepad++ and it's working fine but not in VSC.

**Comment by EwdErna** [comment]
I assume that you have installed Fira for only one user.
try it:right click the font file (.ttf or something) and then select "Install for all users"
It works for me.

**Comment by mets11rap** [comment]
I believe installing Fira Code globally resolved the issue. However I think this should still be addressed because it's a strange interaction specific to VSC so I will leave the issue open.
