### ISSUE TITLE
Shortcut "Toggle Integrated Terminal" not working

### ISSUE THREAD

**Issue by okamototomoyuki1988** [microsoft/vscode#92746]
- VSCode Version:1.43.0
- OS Version:Windows 10 Pro 1903(OS Build 18362.720)

Steps to Reproduce:

1. Open and focus on a text file.
2. Press the shortcut "Toggle Integrated Terminal". Default is Ctrl + `.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
This works fine for me on Windows. Can you share your keybindings.json, settings.json and make sure you have disabled all extensions (close all windows and try `code --disable-extensions`.

**Comment by okamototomoyuki1988** [comment]
https://github.com/microsoft/vscode/issues/92746
This was caused by using Ctrl + Backquote on Japanese version of Windows.
I change the shortcut.
