### ISSUE TITLE
Multiple "New Folder" buttons after closing a workspace

### ISSUE THREAD

**Issue by Jacobboogiebear** [microsoft/vscode#92743]
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open visual studio code
2. Add any folder to the empty/new workspace
3. Open any file in said workspace
4. Right-click main workspace folder
5. Click "Remove folder from workspace"
6. There should be more buttons

Video: [Bug report](https://youtu.be/c7qlDZS6vCo)

Does this issue occur when all extensions are disabled?: Yes

**Comment by coalpha** [comment]
I am also getting this issue.
![image](https://user-images.githubusercontent.com/22552895/76712928-4123f280-66da-11ea-84b4-032ddb34c546.png)
