### ISSUE TITLE
Unable to hit breakpoint after upgrading vs code to 1.43.0

### ISSUE THREAD

**Issue by amitbarik167** [microsoft/vscode#92745]
I am not able to debug nodejs api in vs code 1.43.0 through postman. I was able to do it in the last version.
VSCode Version:1.43.0
OS Version:Windows 10 Home 1903
 
Steps to reproduce.
1.  Go to run, select "Attach by ProcessId".
2.  Click run and select "node server.js" processid.
3. Send a request through postman

Does this issue occur when all extensions are disabled?: Yes

Result - The debugger does n't hit, rather the Postman is giving results.

Note- Nothing changed in launch file. Everything was working fine before upgrade.

**Comment by weinand** [comment]
Are you using VS Code's [new JavaScript debugger](https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger)?
Do you actually have a breakpoint set in your server.js program?

**Comment by amitbarik167** [comment]
I am using VS code,  "Attach to Process" debugging process. Please check this link which I follow.

https://blogs.sap.com/2019/07/15/how-to-debug-a-node.js-rest-api-in-visual-studio-code-locally/

**Comment by roblourens** [comment]
First could you try this with our new debugger implementation? https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by amitbarik167** [comment]
But how it will help me in Postman debugging Node API endpoints ? Can you suggest me the steps? If its broken, then I understand I can wait for the next release. Please note everything was working before the upgrade.

**Comment by roblourens** [comment]
Well, the node debugger didn't change in the last update and hasn't changed in awhile. And the new debugger has a lot of fixes in general. Since our focus is on the new one, I think it's better to investigate your issue there.

**Comment by amitbarik167** [comment]
Ok Rob, Do you have documentation of this new debugger, how to debug through an external app like postman ? when I add the property "debug.javascript.usePreview": true in my launch.json node launch option, its giving error - Property debug.javascript.usePreview is not allowed.

The documentation/link you shared earlier was not clear.

**Comment by roblourens** [comment]
That's a setting for your settings file, not the launch config. You can also change the "type" in your launch config to `pwa-node`, if that is easier.

**Comment by amitbarik167** [comment]
Can I do it without installing insiders ? I selected "Debug:Pretty print for debugging", but still how can I debug with postman ? The process was so easy earlier with Attach to process.

**Comment by amitbarik167** [comment]
FYI - With my old debugging process - Attach to process,  its showing "unbound breakpoint".

**Comment by amitbarik167** [comment]
I am not sure, I may be silly or it might have fixed in 1.43.1. One thing I noticed, is putting a breakpoint in nodejs "exports" shows "unbound breakpoint", but when I put a breakpoint in the next line, it works. Strange not sure how breakpoints make a difference.
