### ISSUE TITLE
Previous Side Bar View should also wrap around

### ISSUE THREAD

**Issue by wdscxsj** [microsoft/vscode#92751]
View: Next Side Bar View wraps around as expected (from bottom to top), but View: Previous Side Bar View doesn't (from top to bottom). It'll be consistent and convenient if it does.

Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by sbatten** [comment]
To Verify:
1. Rearrange Activity Bar Icons from default (especially explorer)
2. Unpin a viewlet, then focus is with a keybinding
3. Run the command `Previous Side Bar View` repeatedly

Ensure that:
* After reaching the top viewlet icon, the command loops properly to the bottom icon
* After making one full loop, the command does not refocus the unpinned viewlet
