### ISSUE TITLE
Always be stuck when close lots of tab too quickly.  

### ISSUE THREAD

**Issue by wuxianxingkong** [microsoft/vscode#92754]
- VSCode Version:1.43.0
- OS Version:Linux x64 5.3.10-050310-generic
- Electron:7.1.11
- Chrome:78.0.3904.130
- Node.js:12.8.1
- V8:7.8.279.23-electron.0

Steps to Reproduce:

1.open lots of tab and fill some word into them.
2.close these tabs one by one quickly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?
