### ISSUE TITLE
Search: include/exclude is case sensitive

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92759]
Steps to Reproduce:

1. using latest insiders
2. search value: `openeditor`
3. files to include: `**/*acc*`

=> :bug: I see 2 results in `gotoLineQuickAccess.ts` and `gotoSymbolQuickAccess.ts` but the one in `symbolsQuickAccess.ts` is not there?

**Comment by bpasero** [comment]
@roblourens figured out what this is, the include/exclude seems to be case sensitive? Is that expected? I can get the proper results when I search in `**/*Access*` instead.

**Comment by roblourens** [comment]
Old issue: https://github.com/microsoft/vscode/issues/10633#issuecomment-355702819 I took a shot at solving it in the linked PR but it touches a lot of things and I couldn't decide how it should work exactly.

**Comment by bpasero** [comment]
@roblourens I understand that it might break a lot of things if we changed our glob implementation, but surely this goes out to RipGrep and is not using our glob, or is it???

**Comment by roblourens** [comment]
Yeah, ripgrep supports case-senstive and non-case-sensitive globs. That part is easy.

**Comment by bpasero** [comment]
@roblourens then please explain why we need to change our glob implementation for this to work

**Comment by roblourens** [comment]
Ours is case-sensitive. Giving it an option to be case-insensitive is easy, I was just stuck on whether it should be applied everywhere, or with a global flag, or if every glob consumer needs a separate flag or separate set of case-sensitive/insensitive globs, etc.
