### ISSUE TITLE
Global git ignore file doesn't work.

### ISSUE THREAD

**Issue by CzBiX** [microsoft/vscode#92757]
Issue Type: <b>Bug</b>

I added some rules in global git ignore file at `~/.gitignore`, but VSC doesn't follow it.  I had to add rules in repo's `.gitignore` to make it work.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

**Comment by joaomoreno** [comment]
Does normal command line git honor it? Did you set it as your global excludes file? https://stackoverflow.com/questions/7335420/global-git-ignore#7335487

**Comment by CzBiX** [comment]
Sorry, I missed it after reconfigure my environments.
Set it as global excludes file and it works now.
