### ISSUE TITLE
Closing one of multiple editors for a dirty file forces save

### ISSUE THREAD

**Issue by vogler** [Microsoft/vscode#9275]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.5.0

Closing an editor for a file that is opened in another editor group, shouldn't force the save dialog.

Steps to Reproduce:

1. Edit some file
2. Split Editor
3. Close Editor <- I shouldn't be prompted to save here

**Comment by bpasero** [comment]
Please search for existing issues before reporting new ones.

#8983
