### ISSUE TITLE
Code hint issue

### ISSUE THREAD

**Issue by wapony** [microsoft/vscode#92750]
VS Code version: 1.43.0
OS version: Mac os Mojave 10.14.6

![代码提示](https://user-images.githubusercontent.com/6447993/76716644-fb176f00-676b-11ea-8705-f1ed169abc9c.jpg)

![代码提示2](https://user-images.githubusercontent.com/6447993/76716876-b8a26200-676c-11ea-8d26-b542397cfb29.jpg)

1、 the msg‘s color is different  with the sender's color, but in the example their color is same.
2、If I define a function ,  when I call the function, there is no code hint this function name , I have to code the function full name.

**Comment by aeschli** [comment]
@wapony What language is that?
