### ISSUE TITLE
Hide search input box in search editor

### ISSUE THREAD

**Issue by ZhiruiLi** [microsoft/vscode#92768]
When using search editor, there is no way to hide the search input box, which makes it impossible to operate only with keyboard. For example, when using vim key binding, you search something by hit `cmd+shift+f` then hit `cmd+enter`, and the search editor pops up. But now the cursor focus on the input box, and there is no way to move cursor to the result area only by keyboard, you can only move cursor using trackpad. Similarly, when you have two pane open side by side, one is code editor, another is search editor, once you move cursor from code editor to search editor by `ctrl-w l`, the cursor will automatically focus on the input box, you can't just navigate in the search result and quick jump to another item.

![image](https://user-images.githubusercontent.com/6213647/76745515-f2955780-67b0-11ea-8f8a-e4bbdc86ccb4.png)

**Comment by JacksonKearl** [comment]
You can use `search.focus.nextInputBox` to focus the results just as you do in the search viewlet. Cmd+DownArrow by default. 

Focus should now be properly preserved when switching between windows, have your tried this on the latest Insiders?

**Comment by ZhiruiLi** [comment]
> You can use `search.focus.nextInputBox` to focus the results just as you do in the search viewlet. Cmd+DownArrow by default.
> 
> Focus should now be properly preserved when switching between windows, have your tried this on the latest Insiders?

That works for me, thanks.
