### ISSUE TITLE
Workspace symbols: no results found when all editors closed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92764]
Steps to Reproduce:

1. open a TS file
2. you can use `Cmd+T` to pick a symbol
3. close all editors

=> 🐛 `Cmd+T` no longer works

**Comment by mjbvz** [comment]
Root cause: https://github.com/microsoft/TypeScript/issues/2530

**Comment by bpasero** [comment]
That linked issue seems to be fixed and I think this is no longer an issue @mjbvz ?

**Comment by mjbvz** [comment]
Yes thanks, this should be fixed now. #92761 is still a  known limitation
