### ISSUE TITLE
How Can I associate a shortcut to view Side Bar / view Panel

### ISSUE THREAD

**Issue by blueray453** [microsoft/vscode#92769]
I am using   the following keybinding:

```
 {
        "key": "ctrl+b",
        "command": "workbench.action.openView"
},
```

Which Shows:

![Screenshot from 2020-03-16 16-14-06](https://user-images.githubusercontent.com/855297/76746206-09b35580-676f-11ea-913c-7f67f9a770d0.png)

How Can I associate a shortcut to `view side bar`:

![Screenshot from 2020-03-16 16-18-21](https://user-images.githubusercontent.com/855297/76746560-9cec8b00-676f-11ea-9eaa-42ad5e2b8c3a.png)

How Can I associate a shortcut to `view panel`:

![Screenshot from 2020-03-16 16-18-50](https://user-images.githubusercontent.com/855297/76746570-a0801200-676f-11ea-9fa3-3c37375a8b59.png)

**Comment by isidorn** [comment]
Currently not possible. This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by blueray453** [comment]
Is there any extension or hack by which I can send custom text (Ex. `view Panel ` or `view Sidebar`) to the command pallet using shortcut.

**Comment by isidorn** [comment]
As far as I know this is not possible.

**Comment by sbatten** [comment]
@blueray453 I am curious why there is a need for filtering to panel or sidebar. Would it not be easier to type `view <the view you want>`

**Comment by blueray453** [comment]
@sbatten If you look carefully to https://github.com/microsoft/vscode/issues/92769#issuecomment-599891254 you will find this feature might unlock a lot of possibilities. 

There are some texts we have to frequently type on that command pallet. I think a lot of developers wish they had a shortcut to put a custom text there. My usecase (`view side bar`, `view panel` etc.) serves just as an example here. I am sure there are a lot more usecases for this feature.

**Comment by sbatten** [comment]
@blueray453 try this:
```
    {
        "key": "ctrl+b",
        "command": "workbench.action.quickOpen",
        "args": "view side bar"
    }
```

**Comment by blueray453** [comment]
> @blueray453 try this:
> 
> ```
>     {
>         "key": "ctrl+b",
>         "command": "workbench.action.quickOpen",
>         "args": "view side bar"
>     }
> ```

Should I close this issue?

**Comment by sbatten** [comment]
if this solution meets your initial request, that would great

**Comment by blueray453** [comment]
@sbatten This is exactly what I needed.
