### ISSUE TITLE
TS: global symbols search only works when TS file is opened once

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92761]
I often end up in a situation where I reload the editor and fire up `Cmd+T` for symbol search but no symbols are found because I first have to open the typescript file to load it's extension.

I wonder if a better approach would be to simply activate each extension that is opened as editor in the workbench when doing the symbol search because the opened editor is a good sign that this is the thing I am interested in for the search.

**Comment by bpasero** [comment]
Actually it seems to also stop working when all files are closed, which seems like a bug to me. Reported as https://github.com/microsoft/vscode/issues/92764

**Comment by mjbvz** [comment]
The TS extension does activate when it sees a `tsconfig.json` file, but for workspace symbol search we also needs to load a TS project. That only happens when you actually open a JS/TS file

I'm not sure we'd want to try doing this eagerly

**Comment by mjbvz** [comment]
Closing this as by-design. Starting the TS Server and loading project symbols is expensive, so require that you have one JS/TS file open before doing this
