### ISSUE TITLE
mouse wheel to zoom font

### ISSUE THREAD

**Issue by frog1014** [microsoft/vscode#92765]
Issue Type: <b>Feature Request</b>

need mouse wheel to zoom font back

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alexdima** [comment]
This feature exists and needs to be enabled with `editor.mouseWheelZoom`.
