### ISSUE TITLE
(Feature request) Support for Multi-line template strings (backticks)

### ISSUE THREAD

**Issue by aamir1995** [Microsoft/vscode#9276]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Pro

## Current Behaviour:
When writing code in Typescript with Angular 2 framework, The IDE didn't recognize HTML tags in inline template with Multi-line strings (backticks), auto code formatting ignores HTML tags inside `backticks`, this situation makes code management much worse.

## Desired Behaviour:
Detection of HTML tags inside `backticks` while performing auto code formatting.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10090
