### ISSUE TITLE
Redesign VS Code CSS Color Picker.

### ISSUE THREAD

**Issue by rakibdev** [microsoft/vscode#92760]
Make the Color Picker larger, also a color preview box.
Redesign it similar as [Google Online Color Picker](https://www.google.com/search?q=%232962ff&oq=%232962ff)

**Comment by PlanMan1717** [comment]
or maybe allowing an option that allows you to pick between different styles?

maybe add a blender option?
![image](https://user-images.githubusercontent.com/51730258/77189607-35577800-6aae-11ea-9ca1-6a405773ee74.png)

or maybe allow you to save your favorites to the status bar?
