### ISSUE TITLE
Commenting doesn't work if child elements are commented in HTML

### ISSUE THREAD

**Issue by aniketdeshbhratar** [microsoft/vscode#92777]
Issue Type: <b>Bug</b>

Write html code. comment inner code and try to comment whole code ( from parent).
Example:

</div> -->

Here comment doesn't work for next lines if vs code found end tag "-->" in between. 

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
That's as designed. The comment code purely textual and does not modify the commented code. You will have to make these changes.

**Comment by aniketdeshbhratar** [comment]
I think it can be overlapped, no need to remove child element comments.
