### ISSUE TITLE
Automatically close center layout when panel opens at right

### ISSUE THREAD

**Issue by Vxider** [microsoft/vscode#92772]
Centered layout will automatically resize to maximum width when more than one group is open by setting `workbench.editor.centeredLayoutAutoResize`. But it will not resize when the panel opens at right. Can we have a setting to control the minimum resize width of centered layout ?

----
vscode version: _1.43.0_
<img width="1904" alt="截屏2020-03-1618 48 21" src="https://user-images.githubusercontent.com/6134315/76749669-d812ac80-67b7-11ea-9f7f-25e7af233d61.png">

**Comment by isidorn** [comment]
I would be open for a PR which changes the behavior of this setting. Such that if the panel is on the side and the setting is set it would also resize as @Vxider suggests.
The setting descirption would also need to be updated.
Code pointerhttps://github.com/microsoft/vscode/blob/464ef8c1b3fe2e29d4dfd7b3d74cdcade7840566/src/vs/workbench/browser/layout.ts#L960
