### ISSUE TITLE
npm scripts panel is not ordered

### ISSUE THREAD

**Issue by jmfrancois** [microsoft/vscode#92773]
- VSCode Version: 1.43.0
- OS Version: macos mojave
```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. open a project with multiple package.json containing some scripts
2. look at npm scripts panel

<img width="339" alt="Screenshot 2020-03-16 at 11 56 48" src="https://user-images.githubusercontent.com/19857479/76749727-47b77600-677d-11ea-8532-78bd6acd937e.png">

Order by path  is not respected as every where else in vscode and this make it not convenient.

Does this issue occur when all extensions are disabled?: Yes

Looking at the code i have found this place: 
https://github.com/microsoft/vscode/blob/master/extensions/npm/src/npmView.ts#L290

**Comment by jpSimkins** [comment]
To add to this:

It would be preferred to sort by alphabetical order as this would also keep packages and other workspaces organized in a clear, predictable manner. Also, state awareness of what is minimized and what is not would be very beneficial. When adding a new script to a project I lose the current order and they all are open again. Having over 50 package.json files... this is becoming an issue.
