### ISSUE TITLE
Closing side bar will stop maximize tab behaviour

### ISSUE THREAD

**Issue by rogeriocsilva** [microsoft/vscode#92776]
- VSCode Version:
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:

1. view 2 tabs in 2 columns 
2. maximize one ( double click on the tab)
2.5 (you can switch from one to another by switching focus)
3. close side bar (cmd+b)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
sounds like https://github.com/microsoft/vscode/issues/70083

**Comment by rogeriocsilva** [comment]
It is, my bad
