### ISSUE TITLE
sidebar-open editors-save all background

### ISSUE THREAD

**Issue by csongebalazs** [microsoft/vscode#92775]
In a newest version of the VSCode the background color of the Save All button in the OPEN EDITORS header is gone. In the past, it had a good, visible background color, when this button become active. Without a strong backgroud color user can find it hardly, and eazy to missclick to Close All beside it.

PLEASE FIX IT!

**Comment by bpasero** [comment]
@csongebalazs can you share a screenshot? What theme are you using?

**Comment by csongebalazs** [comment]
![kép](https://user-images.githubusercontent.com/10388621/76777541-9d554800-67a8-11ea-90ea-c35ece43f481.png)
![kép](https://user-images.githubusercontent.com/10388621/76777581-b2ca7200-67a8-11ea-84bf-71816cad57cd.png)

{
    "workbench.startupEditor": "newUntitledFile",
    "git.confirmSync": false,
    "editor.minimap.enabled": false,
    // The number of spaces a tab is equal to. This setting is overriden
    // based on the file contents when `editor.detectIndentation` is true.
    "editor.tabSize": 4,
    // Insert spaces when pressing Tab. This setting is overriden
    // based on the file contents when `editor.detectIndentation` is true.
    "editor.insertSpaces": true,
    // When opening a file, `editor.tabSize` and `editor.insertSpaces`
    // will be detected based on the file contents.
    "editor.detectIndentation": false,
    "sassFormat.indent": 4,
    "html.format.wrapAttributes": "force-aligned",
    "window.zoomLevel": 0,
    "[typescript]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    },
    "workbench.colorTheme": "Visual Studio Light",
    "editor.tokenColorCustomizations": {
        "comments": "#97c6b1",
        "strings": "#FF0000",
        "types": "#fc1bb1",
    },
    "workbench.colorCustomizations": {
        "sideBar.background": "#fcfcfb",
    },
    "git.enableSmartCommit": true,
    "gitlens.advanced.messages": {
        "suppressCommitNotFoundWarning": true,
        "suppressShowKeyBindingsNotice": true
    },
    "gitlens.historyExplorer.enabled": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true,
    "terminal.integrated.rendererType": "dom",
    "update.channel": "manual",
    "update.enableWindowsBackgroundUpdates": false,
    "breadcrumbs.enabled": true
}

**Comment by bpasero** [comment]
@csongebalazs so what do you mean by "the background is gone", do you mean it shows disabled

**Comment by csongebalazs** [comment]
In the past the save all button had a blue background or was filled with blue, when there were any unsaved changes. Now only the border of the button is black instead of grey.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by csongebalazs** [comment]
I downloaded, installed this Insiders, copy-pasted the settings, and opened a project, and everything was same like the image above.
