### ISSUE TITLE
Keyboard shortcut containing non-US character does not work

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#9277]
- VSCode Version: 1.3.1
- OS Version: OSX 10.10.5

Steps to Reproduce:
1. Create custom keyboard shortcut containing non-US character eg. "cmd+shift+æ"

**Comment by alexandrudima** [comment]
@ankyankyanky Please see https://code.visualstudio.com/docs/customization/keybindings#_accepted-keys and the next section at https://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts
