### ISSUE TITLE
Crash when update extensions

### ISSUE THREAD

**Issue by MarekLew** [microsoft/vscode#92783]
CPUs | Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.68GB (1.82GB free)
Process Argv | C:\Users\marek\Desktop\api3\api3.code-workspace
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
language-x86-64-assembly | 13x | 2.3.0
overtype | ada | 0.2.0
Bookmarks | ale | 11.0.0
vscode-sqlite | ale | 0.8.1
vscode-opennewinstance | chr | 0.0.7
bracket-pair-colorizer | Coe | 1.0.61
python-snippets | cst | 0.2.0
vsc-invoke | dch | 0.0.12
make-hidden | dev | 3.0.3
gitlens | eam | 10.2.1
windows-explorer-context-menu | ele | 2.0.0
vscode-great-icons | emm | 2.1.47
filter-line | eve | 2.0.1
vscode-projects-plus | fab | 1.23.2
vscode-npm | fkn | 3.3.0
code-runner | for | 0.9.17
vscode-commandbar | gsp | 0.3.1
vscode-nginx-conf-hint | han | 0.1.0
Python-autopep8 | him | 1.0.2
vscode-favorites | how | 1.4.0
rest-client | hum | 0.23.2
output-colorizer | IBM | 0.1.2
textile | idl | 0.1.5
reg | ion | 1.0.1
pytest-snippets | jai | 1.0.0
marginalia | jam | 1.0.3
c-cpp-flylint | jbe | 1.4.1
vscode-nuget-package-manager | jmr | 1.1.6
vscode-peacock | joh | 3.6.0
vscode-position | jtr | 1.0.1
theme-karyfoundation-themes | kar | 20.0.3
vscode-sshfs | Kel | 1.16.3
hex-fmt | ker | 1.0.0
graphql-for-vscode | kum | 1.15.3
eml | lei | 0.4.0
sftp | lix | 1.12.9
MagicPython | mag | 1.1.0
rainbow-csv | mec | 1.6.0
textile-preview | mic | 1.0.2
gitignore | mic | 1.0.1
vscode-checkpoints | mic | 1.3.0
colored-regions | mih | 0.0.3
vscode-kanban | mkl | 1.27.1
vscode-remote-workspace | mkl | 0.43.1
vscode-open-in-sourcetree | mor | 0.6.0
hg | mrc | 1.3.0
vscode-json5 | mrm | 1.0.0
python | ms- | 2020.2.64397
debugger-for-chrome | msj | 4.12.6
python-coding-tools | nil | 1.0.3
vscodeprefsync | Nim | 1.0.6
vetur | oct | 0.23.0
indent-rainbow | ode | 7.4.0
fix-json | oli | 0.1.2
vscode-gitignore-generator | pio | 1.0.1
material-icon-theme | PKi | 4.0.1
hgwo | pxg | 1.1.2
vscode-redmine | roz | 0.5.1
partial-diff | ryu | 1.4.1
text-marker | ryu | 1.11.0
multi-command | ryu | 1.4.0
copy-text | sal | 0.4.3
vscode-open | san | 0.1.0
vscode-asciidoc | sta | 0.0.3
ignore-gitignore | stu | 1.0.1
csharp-region-manager | sua | 1.0.11
msbuild-project-tools | tin | 0.3.3
pdf | tom | 0.5.1
run-commands-view | use | 0.3.10
gitflow | vec | 1.2.1
twig | wha | 1.0.2
local-history | xyz | 1.8.1
copy-with-line-numbers | yas | 0.0.4
FilterText | yhi | 0.0.15
material-theme | zhu | 3.2.3

When I open 3 projects and update 16 extensions, all windows close after 2 minutes without permission. This has never happened in previous versions.

**Comment by sandy081** [comment]
Which version of VS Code are you on?

**Comment by MarekLew** [comment]
> 
> 
> Which version of VS Code are you on?

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
@deepak1556 Assigning to you as it might be related to other crashes.

**Comment by deepak1556** [comment]
@MarekLew does the crash happen with latest stable `1.43.1` ?

Can you provide the crash id following these steps at https://github.com/microsoft/vscode/issues/92192#issuecomment-598579176

**Comment by MarekLew** [comment]
I haven't been able to reproduce it. All extension is upgradet.

**Comment by deepak1556** [comment]
Thanks I am merging this to https://github.com/microsoft/vscode/issues/92420 , please provide the crash id if you are still seeing the issue. Thanks!
