### ISSUE TITLE
Wrong title for the button that scrolls to the top

### ISSUE THREAD

**Issue by SevenAlpha** [microsoft/vscode#92785]
Issue Type: <b>Bug</b>

In the Release Notes tab, as you scroll there is a button that takes you back to the top, this button when I hover over it, the title shows the '#' sign instead of saying for example: 'Scroll to the top' and also, the scroll sometimes is not smooth and doesn't scroll to the top completely, so, when I click on it, it scrolls only to almost the top, not the full top **top**. Hope it gets fixed :)
![Snipshot_1](https://user-images.githubusercontent.com/41803599/76766742-2072a000-67a1-11ea-8b1c-d0a866e49f27.PNG)

**Comment by sohomdatta1** [comment]
Can I take a look at this issue and try to work on this?

**Comment by mjbvz** [comment]
Yes, this button comes from the VS Code release notes: https://github.com/Microsoft/vscode-docs/blob/52876af9117d50861e8c8563f109f0282b10a121/release-notes/v1_43.md#L842

**Comment by jppm99** [comment]
I've added a title tag to the button.

[https://github.com/microsoft/vscode-docs/pull/3501](url)

**Comment by mjbvz** [comment]
Closing as upstream
