### ISSUE TITLE
[FR] use the same console for output as it is for debug

### ISSUE THREAD

**Issue by farfromrefug** [microsoft/vscode#9278]
I just realized that the debug console was a repl viewer. And so for example JSON objects appear as a tree. Which i totally love!

Would be awesome to see that coming in the console view. Would be very practical

**Comment by weinand** [comment]
@farfromrefug with 'console view' you mean the 'integrated terminal'?

**Comment by farfromrefug** [comment]
No i am talking about the 'output console'.
sorry for not being clear

I think actually all console which can output json objects could use that.
