### ISSUE TITLE
Feature Request: Copy and replace within current block

### ISSUE THREAD

**Issue by folarinmartins** [microsoft/vscode#92784]
How about the ability to search and replace within the current code block only be it a method body, etc.

**Comment by aeschli** [comment]
Did you see the `Find in selection` feature? (https://code.visualstudio.com/docs/editor/codebasics#_find-in-selection)

Is that solving your issue?

**Comment by folarinmartins** [comment]
Find in selection would work in most cases, but the find in block would be a more applicable and mature implementation
