### ISSUE TITLE
Enable View Location customizations Part 3

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#92786]
As a continuation of https://github.com/microsoft/vscode/issues/89729

To Dos:
- [x] Improve the drag and drop feedback for views, including within and across composites https://github.com/microsoft/vscode/pull/92299
- [x] Allow for multiple views within a single panel to bring things inline with the Sidebar https://github.com/microsoft/vscode/pull/92294 https://github.com/microsoft/vscode/issues/11889
- [x] Allow built-in panels to move to the Sidebar https://github.com/microsoft/vscode/issues/92052
- [ ] Investigate handling of special case viewlets like SCM

**Comment by sbatten** [comment]
work for this milestone complete.

**Comment by saluto** [comment]
Thanks for the great work.
Maybe you are already aware of the following. As a continuation I highly suggest a more generalized layout system, similar to the one of [Theia](https://theia-ide.org/) (which itself uses concepts/extensions from VSCode). There seems to be no distinction between sidebar layout, panel layout and tab layout. Everything uses the same tab/grid layout system. This enables much more flexible and practical layouts.
Is this something you consider? And how difficult is it to implement?
