### ISSUE TITLE
npm scripts new bug in latest release

### ISSUE THREAD

**Issue by hughanderson4** [microsoft/vscode#92797]
Issue Type: <b>Bug</b>

in my workspace i have 4 separate folders added.
inside each folder is a package.json
inside each package.json is a command that has the same name.
using the npm scripts command palette, since latest release, i cannot execute the scripts simultaneously anymore.
it lets me run the first one, when i attempt to run subsequent ones, it is giving me a prompt that the command is already active.  although the command has the same name, it is NOT the same command, as it is run in a totally separate (sibling) folder to the one that is currently running.

NEW BUG introduced today.  thanks.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.14.4
docthis|joe|0.7.1
LiveServer|rit|5.6.1

</details>

**Comment by IllusionMH** [comment]
Looks like duplicate of #92508

**Comment by hughanderson4** [comment]
@IllusionMH right you are, closing as duplicate of #92508
