### ISSUE TITLE
Add visual indicators to the debugging call stack for where the frame originates from

### ISSUE THREAD

**Issue by ivanhernandez13** [microsoft/vscode#92798]
The debugging call stack displays the name of the function along with what file, line, and column it originates from, but it can be confusing to digest and determine which functions are parts of your changes and which are from libraries you are using. It would be nice if the call stack included icons to indicate where the individual frames are coming from. 

See "Highlighting Libraries" in the following article that describes such a feature being added to a debugger for Firefox, Chrome and Node:
https://hacks.mozilla.org/2017/05/debugger-html-call-stack-improvements/

**Comment by isidorn** [comment]
This is a fair feautre reuqest and I think it makes a lot of sense.
Related discussion https://github.com/microsoft/vscode/issues/83986

We would probably need to add debug protocol api for this such that debug extensions can control what icon to use
fyi @weinand @roblourens @connor4312
