### ISSUE TITLE
Window focus with mouse over

### ISSUE THREAD

**Issue by ugosantana** [microsoft/vscode#92796]
Issue Type: <b>Feature Request</b>

When i'm coding (in Python), several times I hit the "Run" icon to see the script on the terminal. Frequently, my scripts ask for information that I type, so it can continue. Several times, when the script ask something, and I start typing the cursor is still on the code panel and not active on the terminal. This is a bit annoying. It can be solved in two ways:

1. when I move the cursor over the terminal, the terminal become automatically active so I can type. Moving the mouse around could change the focus. (for me this is a better solution)

2. when I hit run, the terminal become automatically active so I can type, regardless the mouse position. In this scenario I would have to click on the code panel to continue coding.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

**Comment by aeschli** [comment]
Is that the run button contributed by Python? Can you make a screenshot of it?

**Comment by ugosantana** [comment]
It is this green arrow button. 

<img width="859" alt="Screen Shot 2020-03-16 at 13 24 35" src="https://user-images.githubusercontent.com/8770656/76779159-aa167380-6789-11ea-9e5b-fa3956a519d9.png">

**Comment by aeschli** [comment]
Cool thanks. That button comes from the python extension. I suggest to file the issue there: https://github.com/Microsoft/vscode-python
IMO bringing the focus to the terminal makes sense to me.
