### ISSUE TITLE
Variables not expanding when the terminal autoruns on startup (Win10 → WSL)

### ISSUE THREAD

**Issue by 747** [microsoft/vscode#92799]
Issue Type: <b>Bug</b>

1. set up your workspace JSON as follows:
```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"terminal.integrated.env.linux": {
			"PATH": "${workspaceFolder}:${env:PATH}"
		}
	}
}
```

2. close VSCode while in the workspace leaving the integrated terminal open (so that it restarts automatically at the next time)

3. launch VSCode again

4. the terminal pops up and says:
```
コマンド 'lesspipe' は以下の場所で利用できます
 * /bin/lesspipe
 * /usr/bin/lesspipe
'/bin:/usr/bin'がPATH環境変数に含まれていないためコマンドを特定できませんでした。
lesspipe: コマンドが見つかりません
コマンド 'dircolors' は '/usr/bin/dircolors' で利用できます
'/usr/bin'がPATH環境変数に含まれていないためコマンドを特定できませんでした。
dircolors: コマンドが見つかりません
```
 (it complains in Japanese about `/bin:/usr/bin` not included in $PATH)
```
$ echo $PATH
${workspaceFolder}:${env:PATH}
```

5. open a new terminal and it correctly sources PATH
```
$ echo $PATH
/mnt/my/Workspace/Folder:/home/me/.vscode-server/bin/blahblah...
```

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (21.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 3000)|
|Memory (System)|31.95GB (21.91GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
ace|eva|0.0.1
auto-close-tag|for|0.5.6
textile|idl|0.1.5
sdlang|Lau|0.1.2
procfile-support|log|0.0.1
vscode-language-pack-ja|MS-|1.43.6
remote-wsl|ms-|0.42.3
material-icon-theme|PKi|4.0.1
ayu|tea|0.18.0
vscode-ruby|win|0.27.0
material-theme|zhu|3.2.3
insert-unicode|bru|0.7.1
better-toml|bun|0.3.2
githistory|don|0.6.3
EditorConfig|Edi|0.14.4
crystal-lang|fau|0.3.14
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.169
align-by-regex|jan|1.0.4
asciidoctor-vscode|joa|2.7.13
nim|kos|0.6.4
formate|Mik|1.1.4
vscode-language-pack-ja|MS-|1.43.6
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
trailingwhitespacehighlighter|paj|0.0.2
ruby|reb|0.27.0
rust|rus|0.7.0
crates|ser|0.4.9
vscode-table-formatter|shu|1.2.1
sass-indented|syl|1.7.5
vscode-ruby|win|0.27.0
better-align|wwm|1.1.6

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Same root cause as https://github.com/microsoft/vscode/issues/81231 I believe.
