### ISSUE TITLE
ENOPRO: "No file system provider found for resource 'file:///'"

### ISSUE THREAD

**Issue by starccy** [microsoft/vscode#92795]
I just build a web version on my remote server according the wiki, then I run it with `yarn web` with those three arguments.      
However I cannot open any files / folders or save them. whatever I entered in the path dialog, it always says path does not exist.   
I saw the errors in the browser console:
```
ENOPRO: "No file system provider found for resource 'file:///'"
    withProvider fileService.ts:118
    doResolveFile fileService.ts:178
    resolve fileService.ts:162
    createItems simpleFileDialog.ts:883
    updatingPromise simpleFileDialog.ts:792
    createCancelablePromise async.ts:23
    updateItems simpleFileDialog.ts:791
    pickResource simpleFileDialog.ts:390
    pickResource simpleFileDialog.ts:261
    showOpenDialog simpleFileDialog.ts:165
    pickResource abstractFileDialogService.ts:223
    pickWorkspaceAndOpenSimplified abstractFileDialogService.ts:187
    pickWorkspaceAndOpen fileDialogService.ts:51
    run workspaceActions.ts:95
    triggerAndDisposeAction actions.ts:119
    createCommandHandler actions.ts:94
    invokeFunction instantiationService.ts:61
    _tryExecuteCommand commandService.ts:84
    executeCommand commandService.ts:73
    promise callback*executeCommand commandService.ts:73
    run actions.ts:253
    run actions.ts:320
    runAction actions.ts:198
    run actions.ts:190
    onClick actionbar.ts:180
    render actionbar.ts:148
    DomListener dom.ts:102
    addDisposableListener dom.ts:123
    render actionbar.ts:137
    render menu.ts:407
    push actionbar.ts:652
    push actionbar.ts:629
    Menu menu.ts:204
    createSubmenu menu.ts:761
    showScheduler menu.ts:650
simpleFileDialog.ts:893:11
```
And in the server console, it shows those error: 
```
Error: ENOENT: no such file or directory, stat '/root/vscode/out/vs/workbench/api/worker/extension.js.map'
Error: ENOENT: no such file or directory, stat '/root/vscode/remote/web/node_modules/vscode-textmate/release/main.js.map'
```
I have no idea why these files do not exist because I built it with no error.

- VSCode Version: **1.44.0**
- OS Version: **kali-rolling**

Steps to Reproduce:

1. Run command: `yarn web --host xxx.xxx.xxx.xxx --port 8080 --schema http`
2. Open vscode in the browser, open a workspace, enter the path. Then show the error.

Does this issue occur when all extensions are disabled?: Yes

I notice that #84645 and #84198 are a little bit similar with this problem, however neither is helpful.

**Comment by bpasero** [comment]
@starccy you cannot open workspaces/folders in `yarn web`, is that what you are trying? `yarn web` only provides a very limited in-memory only file system.

**Comment by starccy** [comment]
@bpasero  Yes that's what I have tried. so in another world, this error is expected to appear with `yarn web` as present?

**Comment by bpasero** [comment]
Yes, currently that's it. If you want to be productive with VSCode for Web, use VSO instead: https://visualstudio.microsoft.com/de/services/visual-studio-online
