### ISSUE TITLE
Comments: allow customize placeholder for input box

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#92794]
Issue Type: <b>Feature Request</b>

Currently the inputbox always shows `Reply ...` as the place holder while extensions might want to customize that. This can be done either through static contribution or through API.

VS Code version: Code - Insiders 1.44.0-insider (798481c7978af034b054e14ace4e471e7a83f665, 2020-03-16T07:10:59.884Z)
OS version: Darwin x64 19.2.0

**Comment by rebornix** [comment]
The commenting api now has interesting usage like CodeTour which is no longer just about code commenting thus the default placeholder we use for the input box might confuse CodeTour (and other similar extensions) customers, thus we are going to make this customizable. The proposal is introducing an option property for `CommentController`

```typescript
	//#region Peng - Comment
	export interface CommentOptions {
		/**
		 * An optional string to show on the comment input box when it's collapsed.
		 */
		prompt?: string;

		/**
		 * An optional string to show as placeholder in the comment input box when it's focused.
		 */
		placeHolder?: string;
	}

	export interface CommentController {
		/**
		 * Comment controller options
		 */
		options: CommentOptions;
	}
	//#endregion
```

**Comment by lostintangent** [comment]
@rebornix Does this new API allow hiding the reply functionality entirely? Or simply changing the prompt text that is displayed?

**Comment by rebornix** [comment]
@lostintangent no, this will only control the display text but not if the comment thread is readonly or not. I would imagine that's another metadata.
