### ISSUE TITLE
[html] punctuation for tags can not be colored by syntax themes

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#928]
I have tried several themes from the marketplace and created a few of my own. Punctuation on HTML files, such as `< > </> =`  cannot be colored by the theme.  When using a dark theme, for example, I always get the original default medium/light blue.

![screen shot 2015-12-02 at 9 43 50 am](https://cloud.githubusercontent.com/assets/835148/11533734/36673204-98d9-11e5-9815-0aa954644c59.png)

**Comment by aeschli** [comment]
Fixed to use the standard text mate tokens:
`<` : punctuation.definition.meta.tag.begin.html
`>` : punctuation.definition.meta.tag.end.html
`=` : meta.tag.assign.html
