### ISSUE TITLE
Junk in my editor

### ISSUE THREAD

**Issue by gambledrum** [microsoft/vscode#92807]
Issue Type: <b>Bug</b>

In the top right corner of my editor there's a line that is drawn from the edge of the editor inward, and also there is a blacked out area all the way down the editing window the width of that line.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
calva|bet|2.0.85
clj-kondo|bor|2020.2.28
Go|ms-|0.13.1

</details>

**Comment by gjsjohnmurray** [comment]
Annotated screenshot please.

And does it occur if you reload with all extensions disabled?

**Comment by gambledrum** [comment]
![Untitled](https://user-images.githubusercontent.com/51029250/76801013-2a010580-67ab-11ea-8b1c-8bf543bd4b24.png)

I've attached an image that shows the line...
Please let me know if I need to do something else.
I'm not sure what an annotated screenshot is and how to make one.

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/76809326-54ba8080-67e2-11ea-9cb9-04a25b4e7ecf.png)

That is the [Minimap](https://code.visualstudio.com/docs/getstarted/userinterface#_minimap).
