### ISSUE TITLE
Crashes When Switching Between Extension Tabs and Moving Minimized Window

### ISSUE THREAD

**Issue by sternex** [microsoft/vscode#92809]
When you switch between extensions installed and not installed then try to move your window Visual Studio Code quits the application, It happens when resizing and moving the non fullscreen window

**Comment by sternex** [comment]
![image](https://user-images.githubusercontent.com/17723510/76801893-ef986800-67ac-11ea-8087-c77f152edaa7.png)

**Comment by sternex** [comment]
Screen recording showing the crash
[Screen Recording 2020-03-16 at 5.41.32 PM.zip](https://github.com/microsoft/vscode/files/4340542/Screen.Recording.2020-03-16.at.5.41.32.PM.zip)

**Comment by sternex** [comment]
Not sure how to provide log but i found this in Console system.log after app crashes
`Mar 16 18:11:44 Joshuas-MBP com.apple.xpc.launchd[1] (com.microsoft.VSCode.5908[10604]): Service exited due to SIGSEGV | sent by exc handler[10604]`

**Comment by deepak1556** [comment]
@sternex thanks for the recording, this issue is same as https://github.com/microsoft/vscode/issues/92420 . Please follow that issue for udpates. Thanks!
