### ISSUE TITLE
actions.findWithSelection does not highlight search input

### ISSUE THREAD

**Issue by yordis** [microsoft/vscode#92801]
```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

### Steps to Reproduce:

1. CMD+F on a word
2. It doesn't highlight the searching input as it used to be

### Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using 1.40.0?
Latest versions is 1.43. Could you update and check if you have same issue with latest version?

**Comment by yordis** [comment]
@IllusionMH I am sorry, I updated the version, I think I copied the old version that I reversed to, still broken in the latest.

```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by aeschli** [comment]
Can you add a screenshot?

**Comment by yordis** [comment]
Notice that when CMD+F is pressed it doesn't highlight the input


![68814721-356be500-0682-11ea-8eae-ba84e12885e4](https://user-images.githubusercontent.com/4237280/77001640-7a957180-6917-11ea-8b0b-0499a5ab9165.gif)

**Comment by yordis** [comment]
@IllusionMH the information was provided, since "needs more info" tag is on, I want to make sure that everything is settled from my side.

Please give us a hand with this 😢

**Comment by yordis** [comment]
https://github.com/microsoft/vscode/issues/44093#issuecomment-546157573

................

**Comment by rebornix** [comment]
Based on the screenshot shown above, it seems when pressing cmd+f, the cursor is not inside a word, thus we don't fill that into the find widget.

**Comment by yordis** [comment]
@rebornix the problem happens with words as well, and regardless it was the default behavior of the feature until you decided to change it #44093
