### ISSUE TITLE
When Hitting "Check for Updates" Mac v1.27.2 says, "no available updates"

### ISSUE THREAD

**Issue by mikegwhit** [microsoft/vscode#92802]
- VSCode Version: 1.27.2
- OS Version: Mac OSX 10.13.6 (High Sierra)
 
Steps to Reproduce:

1. Configure to use the above mentioned versions (or test other impacted versions)
2. Hit Code -> Check for Updates
3. Watch it say, "no available updates."

Expected to download the latest version.  This is going to be a source of confusion for people and if they don't update could leave some systems vulnerable potentially.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469

Does this help you?

**Comment by mjbvz** [comment]
Closing as more information is needed to to investigate
