### ISSUE TITLE
extension to create task

### ISSUE THREAD

**Issue by farfromrefug** [microsoft/vscode#9280]
I am trying to develop an extention for the Titanium Mobile framework.
That extension allows you to build a project kind of like the cordova extension does.
To execute a build my extension runs a command using `shell.exec`

I would like to make my "build" a "task". The reason are :
- make my build appear as a "default task"
- use of problem matcher to detect errors
- allow the user to customize the build task?
- correct handle of keyboard shortcuts. I would like to use the same keyboard shortuct to run the default task and to build using TItanium. It makes sense because when in titatnium folder then it should build. But when in another folder (npm) it should run the default task.

I don't see anyway to do that right now. I have looked through existing extensions and no one seems to have gone that far.

I think this is a must have. This is the main reason why i still build my Titanium projects with Sublime Text.

**Comment by ulgrimar** [comment]
Would be a nice feature, probably not in the core but as a plugin.

**Comment by dbaeumer** [comment]
The only workaround that currently exists is to generate the tasks.json file directly from the extension. However this is error prone if we change the format.

**Comment by farfromrefug** [comment]
@dbaeumer yes and it also erases the user tasks.json? Which does not seem like a good idea.

**Comment by dbaeumer** [comment]
Task providers got added a long time ago.
