### ISSUE TITLE
Double parenthesis and double double quotes.

### ISSUE THREAD

**Issue by gambledrum** [microsoft/vscode#92806]
Issue Type: <b>Bug</b>

When I type (println"Hello") in my editor or REPL it prints:
(println""))
It makes vs code unusable.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
calva|bet|2.0.85
clj-kondo|bor|2020.2.28
Go|ms-|0.13.1

</details>

**Comment by gjsjohnmurray** [comment]
What language are you coding in?

Does this reproduce with all extensions disabled?

If yes, please post an animated GIF or a video, or detailed steps on how to recreate the issue.

**Comment by gambledrum** [comment]
I'm coding in Clojure.
The extension Clava is something that has what's called Paredit inside of it.  It matches parens and "'s and ]'s and }'s.
It won't reproduce with no extensions because then the Paredit mode won't be running.
How do I create an animated GIF?

**Comment by gambledrum** [comment]
I've discovered that this only happens in the Clava REPL, so I don't believe it's a VS Code issue.

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report the issue on the Clava extension
