### ISSUE TITLE
[Feature Request] Config option to show/hide comments with TODOs as a problem warning

### ISSUE THREAD

**Issue by wemersonrv** [microsoft/vscode#92810]
Hello,

I would like to suggest a configuration option to not display comments with TODO as warnings in the Problems tab.

**Comment by aeschli** [comment]
Which language? TypeScript?

**Comment by wemersonrv** [comment]
> Which language? TypeScript?

Hello, 

I had no idea that this was a specific language feature. I'm using dart!

**Comment by aeschli** [comment]
It must be an extension that creates the error. VSCode does not do that out of the box.
Is there any information in the problems view from where the problem is from?
Please check off your extensions one by one to see which one creates it.
