### ISSUE TITLE
When I write golang program，run debug mode, then I click "restart" button, throw Error " Unable to display threads"

### ISSUE THREAD

**Issue by YugeCse** [microsoft/vscode#92817]
Issue Type: <b>Bug</b>

When I write golang program，run debug mode, then I click "restart" button, throw an Error " Unable to display threads: {e}" in the bottom-right of screen. But the program can still exec without error.

编写Golang服务器程序（使用Gin第三方库），
debug模式下点击**重启按钮**，屏幕右下角出现错误提示，
右下角错误弹窗信息： **Unable to display threads: "{e}"**，
但是程序仍然能够正常执行。

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
ccs-flutter-color|cir|0.0.3
gitignore|cod|0.6.0
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-markdownlint|Dav|0.34.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
xml|Dot|2.5.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
auto-close-tag|for|0.5.6
kotlin|fwc|0.2.11
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
intellij-idea-keybindings|k--|0.2.37
vscode-language-babel|mgm|0.0.26
vscode-language-pack-zh-hans|MS-|1.43.7
Go|ms-|0.13.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.1
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
vscode-yaml|red|0.7.2
html-preview-vscode|tht|0.2.5
vscode-java-debug|vsc|0.25.1
vscode-maven|vsc|0.21.1
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Please file this against the Go extension: https://github.com/microsoft/vscode-go

**Comment by YugeCse** [comment]
OK. Thank U!
