### ISSUE TITLE
Run is wrong as Run()

### ISSUE THREAD

**Issue by googya** [microsoft/vscode#92816]
When opening vscode,  the gui shows something like in the picture below. It is weird and I do not think it is a feature, right?

version info below:

版本: 1.43.0
提交: 78a4c91400152c0f27ba4d363eb56d2835f9903a
日期: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

![图片](https://user-images.githubusercontent.com/118465/76813887-ac85d580-683c-11ea-9312-bb548a8ccdf2.png)

**Comment by janbaltus** [comment]
Same as https://github.com/microsoft/Localization/issues/98

**Comment by janbaltus** [comment]
Please test using 1.43.8 LP which was just published
