### ISSUE TITLE
empty Markdown preview window

### ISSUE THREAD

**Issue by o-khavin** [microsoft/vscode#92815]
Issue Type: <b>Bug</b>

Ubuntu 18.04.4 LTS.
Clean install of VSCode.
No one extention installed.
Mardown preview window show nothing for any .md file.
Language indicator show correct value.
Installed "shd101wyy.markdown-preview-enhanced" extension works correctly.
Dual graphics system: i5-6400/GTX 1060 (Clevo n950kp6) - both graphics modes are tested.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.25GB (26.91GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Did this work in the previous VS Code release? In VS Code, if you run `Developer: Toggle developer tools`, do you see any errors in the developer console related to markdown?

**Comment by o-khavin** [comment]
This is the first VS Code release I use.
No any unusual messages in developer console.
![Снимок экрана от 2020-03-17 14-53-07](https://user-images.githubusercontent.com/43133342/76826152-08615600-685f-11ea-89bc-357c7eee2bba.png)

**Comment by mjbvz** [comment]
Have you tried a markdown files that doesn't start with `---`?  You example is likely being parsed as [front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by o-khavin** [comment]
Oops.
It looks like **all** the files in this project start with these characters. :)
Adding any character to the beginning of the file solves the problem.
Is this a bug or a feature?

**Comment by gjsjohnmurray** [comment]
Feature. Used to be configurable but now always hidden unless you add an extension. See #66312

**Comment by o-khavin** [comment]
So it looks like this was my problem, not the VS Code problem.

**Comment by gjsjohnmurray** [comment]
Always something new to learn. Please close this issue.
