### ISSUE TITLE
Remote SSH: Syntax Highlighting/Coloring Does Not Work in Erlnag

### ISSUE THREAD

**Issue by mehrdad-drpc** [microsoft/vscode#92825]
I use vscode for my erlang development.

In my local machine, everything is, OK. but when I use ssh to connect into my remote server the Erlang syntax highlight does not work.

![erlang](https://user-images.githubusercontent.com/40826835/76678072-0f336300-65ea-11ea-8dd3-28761b24e079.jpg)

I use [ssh-remote](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) for connect to SSH remote server,
![vscoe-remoteSSH](https://user-images.githubusercontent.com/40826835/76828504-5dd53d00-6836-11ea-993f-e408d7242729.png) to handle my ssh connection.

And also, I use [this extension](https://marketplace.visualstudio.com/items?itemName=pgourlain.erlang) for erlang, 
![vscode-erlang](https://user-images.githubusercontent.com/40826835/76827948-24e89880-6835-11ea-8114-1437cf82c831.png)

**what is the solution to my problem**?

**Comment by aeschli** [comment]
I tried your steps and it works for me. I see Erlang syntax highlighting in a remote SSH window with the extension you showed.

Is the Erlang extension also installed on the remote side?
In the remote window open the extensions viewlet and search for the erlang extension and install it if net yet installed.

**Comment by mehrdad-drpc** [comment]
GREATE.
The Erlang extension was not installed on remote side.
