### ISSUE TITLE
vISUAL STUDIO CODE 1.43 IS NOT OPENING IN windows 8

### ISSUE THREAD

**Issue by PoojaChoudhury** [microsoft/vscode#92824]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by PoojaChoudhury** [comment]
Visual studio 1.43 is not opening..Plz help me.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo if a friend sent you a request for help like that, what questions would you want to ask them?
