### ISSUE TITLE
VSCode keyboard input stops with omnisharp plugin

### ISSUE THREAD

**Issue by v2k** [microsoft/vscode#92821]
- VSCode Version: 1.43.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Install ms-dotnettools.csharp
2.  Install vscodevim.vim (also same with neo vim)
3.  Open VSCode and edit a file.

Note keyboard will work for a 20-30 seconds, then it will stop.  Developer: Reload Window can get it working briefly, but it will stop again after 20-30 seconds.

I've tried using older versions of Vim, uninstalling all plugins and VSCode and reinstalling. 

I noticed that the reload window does trigger an OmniSharp refresh, so it must be related.   I've tried various C# projects, and they all seem to behave in the same manner.

**Comment by aeschli** [comment]
Looks like the C# extension blocks the extension host. The VIM extension also runs on the extension host.

Please file this against https://github.com/OmniSharp/omnisharp-vscode
