### ISSUE TITLE
[BUG] Multiple Types of variable in TypeScript

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#9282]
- VSCode Version: 1.3.1
- OS Version: Windows 10
- TypeScript

I created interfaces on my project and  applied multiple types on variable using operator | (or) but on body of class he throw new error: "Property 'Usuario' does not exist on type 'IUsuarioStorage__Dados | boolean'." and not return options of interface.

See the image:

![imagebug](https://cloud.githubusercontent.com/assets/5774595/16840709/7b97fde8-49ac-11e6-8644-e6ec379c2f39.png)

**Comment by cwberick** [comment]
-label:bug

**Comment by cwberick** [comment]
@egamma

**Comment by egamma** [comment]
Moving to TypeScript for comment.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#9760
