### ISSUE TITLE
Regression: No longer able to see source preview in Ctrl+hover

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#9283]
Reproduces also in stable 1.3.1. 

Have JS/TS code like this:

```
var foo = 3;
console.log(foo);
```

Ctrl+hover over foo and notice you are not seeing the source preview in the hover. However if I debug this, I see that the decoration receives the line content in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L393

@aeschli also adding you because according to Alex you changed decorations recently.

**Comment by aeschli** [comment]
Found the issue, fix is on the way.
