### ISSUE TITLE
Not able to Use terminal to run code

### ISSUE THREAD

**Issue by Divyanshu005** [microsoft/vscode#92837]
Issue Type: <b>Bug</b>

While running the code , Terminal is not responding and it is crashing ..
please work on this asap.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 4, 2|
|Memory (System)|3.71GB (0.18GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.2.64397
vscode-yaml|red|0.7.2

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by daravenrk** [comment]
This is the error in VSCode and it is caused during the terminal startup.

![Screenshot_1](https://user-images.githubusercontent.com/5263569/77009709-9bfd5a00-6925-11ea-9849-ff7d92fd4a46.png)

 
![Screenshot_2](https://user-images.githubusercontent.com/5263569/77009869-eaaaf400-6925-11ea-8196-abc1896867c0.png)

**Comment by Tyriar** [comment]
@daravenrk yours is a different thing, likely related to anti-virus software or the fact you're running as admin.
