### ISSUE TITLE
Breakpoint Panel Not Resizable

### ISSUE THREAD

**Issue by rushvora** [microsoft/vscode#92834]
- VSCode Version: 1.43.0
- OS Version: macOS 10.15.2

Steps to Reproduce:

1. Try to drag the breakpoints section in the sidebar, in order to vertically increase the length of the panel, so that a greater number of breakpoints can be viewed.
2. It does not seem to be draggable. All the other sections/panels are draggable.

Does this issue occur when all extensions are disabled?: Yes

I am assuming it's a bug since the other panels I tried resizing are easily resizable vertically. If it's intentional and not a bug, I apologise.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/46886
