### ISSUE TITLE
Disable the red problem highlightings in the minimap

### ISSUE THREAD

**Issue by iaso2h** [microsoft/vscode#92830]
Issue Type: <b>Feature Request</b>

Hi, Any can give me some hints how to disable the problem highlightings in the minimap?

Whenever I occurred a new problem in the problem panel, it is rendered in red color in the minimap  at the same time. I found it pretty annoying and I racked my brains to find the relative setting inside the `defaulsetting.jason` but to no avail.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by RMacfarlane** [comment]
There's currently not a setting for this, but you can add
```
"workbench.colorCustomizations": {
    "minimap.errorHighlight": <editor background color>
}
```
to make it not visible as a workaround
