### ISSUE TITLE
Allow hover providers to set a width on hovers

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#92833]
See https://github.com/microsoft/vscode-pull-request-github/issues/1578 for more context

Perhaps you could add a new enum parameter to the Hover constructor for size?
```typescript
	export enum HoverSize {
		// The current behavior.
		Default = 0,
		// Shrinks the size of the hover to fit the contents if they are smaller than default.
		Shrink = 1,
		// Expands the size of the hover to fit the contents if they are larger than the default.
		Expand = 2
	}

	export class Hover {
		contents: MarkedString[];
		range?: Range;
		constructor(contents: MarkedString | MarkedString[], range?: Range, size?: HoverSize);
	}
```

**Comment by octref** [comment]
@jrieken What do you think?

**Comment by jrieken** [comment]
I do agree that the hover sizing is really, really bad, but I am not a fan of extensions allowing to control this. IMO the only default should be fit e.g the hover is always as large or small as its contents, obviously within reasonable upper/lower bounds.

**Comment by octref** [comment]
The issue was caused by a bad CSS rule for `hr`, which makes it 100vw. I changed it to 100%.
The hover widget already "shrink to fit" the inner content.
