### ISSUE TITLE
Should allows comments in tsconfig/jsconfig schemas

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode#92839]
`tsconfig.json` supports comments as far as I know. I think `"allowComments": true,` should be added to those schemas:
https://github.com/microsoft/vscode/blob/88f63bcd875d986c616b4bc65bc7a590469985c7/extensions/typescript-language-features/schemas/tsconfig.schema.json#L1-L3

**Comment by mjbvz** [comment]
Comments already work for me in tsconfig files (by default VS Code associates them to the `JSON with comments` language)

@rchl What doesn't work?

@aeschli Do we observe `allowComments` from the schema?

**Comment by rchl** [comment]
You are right that comments already work. I've missed the fact that those are using `jsonc` language.

The reason I thought that these don't work was that I've only looked at the schema itself and noticed that it is missing `allowComments` property. I didn't bother to actually check how it behaves in practice.
And while it might seem strange that I based this issue solely on looking at the schema is because I was adapting those schemas to be used in Sublime Text language server.

So all in all, feel free to close this issue unless you believe that for the sake of semantic correctness or completeness that property should be added.

**Comment by mjbvz** [comment]
Thanks for clarifying

One note: we only use this schema when you are offline; otherwise we pull a much more complete tsconfig schema from schemastore (not sure if that schema sets `allowComments` or not)

**Comment by rchl** [comment]
I know about the online schema but the properties that allow trailing commas or comments are vscode extensions so those are not in those schemas and have to be added though local schema that I've linked.

**Comment by aeschli** [comment]
Just to clarify
> we only use this schema when you are offline
No, it's used all the time. All schemas contributed for a filename / extension are merged (anyOf).
That allows us to make contributions to the published schemas e.g. by adding VSCode specfic properties, including the `allowTrailingCommas` which VSCode specfic  and not part of JSON Schema
