### ISSUE TITLE
Filter children items inside of excluded parent folder when file inside it is opened.

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#92849]
Related to #92090

If I add `"**/a1": true` (similar to how defaults look like `**/.git`, `**/CVS` etc.) to `files.exclude` - whole tree content inside of `a1` in path to `comp1.js` and child items are shown:
![image](https://user-images.githubusercontent.com/1312662/76860108-2630ba00-6863-11ea-8f04-fc9399a4ef88.png)
_(only `src` and `index.js` are outside of ignored `a1`)_

I found that if I change it to `"**/a1/**": true` then I get much better behavior – Compact folders + only opened file in folder:
![image](https://user-images.githubusercontent.com/1312662/76860619-fe8e2180-6863-11ea-8001-99383c969318.png)

Would be nice to have later behavior without need to add `/**` to globs (does `/**` in globs affect performance?).

/cc @isidorn

**Comment by isidorn** [comment]
@IllusionMH thanks for creating the issue. And your suggestion makes sense. I will look into it that we fix it this milestone.
