### ISSUE TITLE
VsCode stop debugging dotnet core applications anymore

### ISSUE THREAD

**Issue by caglardursun** [microsoft/vscode#92844]
I was start to develop dotnet core based web api projects. 
But suddenly I couldn't debug it anymore (For any dotnet core apps)

I just check a few things. I don't think it's about my sdk versions but here is the result of 
dotnet --list-sdks 

2.1.804 [/usr/share/dotnet/sdk]
3.1.200 [/usr/share/dotnet/sdk]

I found something in my Log(Window) section and I just wondering what's this about ? I googled it but I couldn't find any information about that

[renderer1] [error] timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2953:952)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2953:250
    at async t.RawDebugSession.shutdown (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2951:336)

- VSCode Version: 1.43
- OS Version: Linux x64 5.3.0-42-generic

Does this issue occur when all extensions are disabled?: May be

**Comment by caglardursun** [comment]
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:

Well done. Bot answering ... But the problem is not even close. Who wrote this crap anyway

**Comment by aeschli** [comment]
Can you file this against the C# extension?
https://github.com/OmniSharp/omnisharp-vscode
