### ISSUE TITLE
Terminal does not start on remote connection

### ISSUE THREAD

**Issue by glaucoleme** [microsoft/vscode#92845]
Issue Type: <b>Bug</b>

With the remote connection extension, I connect from a windows 10 notebook into a ubuntu 18.04 linux machine (EC2) at AWS cloud network. The connection is good, all folders and files open without any trouble. I can also perform this connection from putty, mobafire and powersheel ssh command. But the integrated terminal stucks at 'Starting...' and is not possible to type anything.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-1060-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: DevAwsSandbox|
|OS|Linux x64 4.15.0-1060-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|Memory (System)|3.85GB (1.63GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
Angular-BeastCode|Mik|8.1.2
vscode-language-pack-pt-BR|MS-|1.43.6
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.20.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
vscode-solution-explorer|fer|0.3.9
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
compareit|in4|0.0.2
angular2-switcher|inf|0.3.2
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|3.6.0
docomment|k--|0.1.8
chat|kar|0.31.0
vscode-sshfs|Kel|1.16.3
csharpfixformat|Leo|0.0.84
vscode-docker|ms-|1.0.0
vscode-language-pack-pt-BR|MS-|1.43.6
csharp|ms-|1.21.14
python|ms-|2020.2.64397
Go|ms-|0.13.1
vsliveshare|ms-|1.0.1742
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
sqltools|mtx|0.21.6
printcode|nob|3.0.0
fix-json|oli|0.1.2
vscode-versionlens|pfl|0.25.0
typescript-hero|rbb|3.0.0
sonarlint-vscode|Son|1.15.0
vscode-ansible|vsc|0.5.2
markdown-pdf|yza|1.4.3
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/2313
