### ISSUE TITLE
VS Code goes fuzzy when popup box appears

### ISSUE THREAD

**Issue by tscpp** [microsoft/vscode#92841]
Issue Type: <b>Bug</b>

When you type something and a popup box appears with function documentation vscode goes fuzzy/blurry. For example when you type `new Promise((resolve, reject) => void)` in TypeScript it goes blurry after the second parenthese. Video (G Drive) https://drive.google.com/file/d/1arPFVi3sBKs6AYELuSljLICdzX1Lb5I_/view?usp=sharing

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz (8 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-beautifier|mic|2.3.3
vscode-icons|vsc|10.0.0

</details>

**Comment by tscpp** [comment]
I tried to reinstall but it didn't work

**Comment by aeschli** [comment]
You mean `resolve` gets a darker color? That's because it is an unused variable.

**Comment by tscpp** [comment]
Sorry I did some more research, and it wasn't VS Code's fault, it was my graphics settings that turned anti-aliasing on. But it only happens when the popup box with the documentaion showed up.
