### ISSUE TITLE
Reduce header size of extension view

### ISSUE THREAD

**Issue by valtism** [microsoft/vscode#92858]
In extension tabs, the header of extension takes up a significant amount of vertical space (220px). On smaller screens, especially with a terminal window open, this means that there is very little room for the content of the extension as seen here:

<img width="1392" alt="Screen Shot 2020-03-17 at 15 09 45" src="https://user-images.githubusercontent.com/1286001/76870489-abb36a80-6861-11ea-8d42-9a15705c4a00.png">

I propose changing the header to relative position rather than absolute, or alternatively a redesign of the header to include only important information and shrinking it down to a more reasonable size (< 80px).

This is a small quality of life feature request, and is low importance. Let me know what you think.

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by dormesica** [comment]
@sandy081 I've taked some "good first issues" in this repository before and I was looking for something bigger this time. So, if you think I can help I would like to take this on.

**Comment by sandy081** [comment]
That would be great. Please take a look.

**Comment by dormesica** [comment]
@sandy081 Just to be clear about the task. Should I simply make the title smaller or should I make it dynamic according to the available space?

**Comment by sandy081** [comment]
It has to flexible.
