### ISSUE TITLE
incorrect data structure description in collections.ts

### ISSUE THREAD

**Issue by videlalvaro** [microsoft/vscode#92857]
This function in collections.ts:

```typescript
/**
 * Returns an array which contains all values that reside
 * in the given set.
 */
export function values<T>(from: IStringDictionary<T> | INumberDictionary<T>): T[] {
	const result: T[] = [];
	for (let key in from) {
		if (hasOwnProperty.call(from, key)) {
			result.push((from as any)[key]);
		}
	}
	return result;
}
```

Talks about a set, but a `set` implies uniqueness of values, so perhaps it's better to talk about a `collection`? Unless a set in this case is taken as the `(key -> value)` pairs. In any case the resulting array can't guarantee value uniqueness.

**Comment by aeschli** [comment]
We keep the current comment.
