### ISSUE TITLE
VSCode opens multiple windows

### ISSUE THREAD

**Issue by 0xd114** [microsoft/vscode#92855]
- VSCode Version: 1.43.0
- OS Version: Windows 10

Steps to Reproduce:

1. open VSCode

Does this issue occur when all extensions are disabled?: Yes

Very annoying, because it opens many VSCode instance at once, and lead to CPU exhaustion. Please fix.

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #92318, which is scheduled to be fixed by the upcoming 1.43.1 recovery release.

**Comment by aeschli** [comment]
likly a duplicate of #92318 

If this is not about that bug: You can control which previous window are restored with the setting: `window.restoreWindows`
