### ISSUE TITLE
Control over snippets

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9286]
There are many different expectation wrt snippets and we should introduce some user settings and command to tackle that

- [x] add a config option to sort snippets in the suggest box like `top`, `bottom`, `inline`, `none`
- [x] **moved to separate issue** - [add a command to insert the best matching snippet suggestions](https://github.com/Microsoft/vscode/issues/9579) 
- [x] add a command to only show snippet suggestions (filter on `CompletionItemKind`)

**Comment by egamma** [comment]
Suggest to also add a setting to not show snippets in intellisense, e.g., top, bottom, natural, **none**.

**Comment by jrieken** [comment]
better naming ideas? favourites?

`snippetSuggestionsSortOrder: 'top' | 'bottom' | 'normal';` 
or 
`snippetSorting: 'top' | 'bottom' | 'normal'`

and then analog to `editor.wordBasedSuggestions` I'd add

`editor.snippetSuggestions: boolean,`

**Comment by alexandrudima** [comment]
I would go with one setting, it is IMHO more difficult for me to have to configure two settings which somewhat influence eachother

 `editor.snippetSuggestions : "top" | "bottom" | "mixed"  | "none"`

I would go for `"mixed"` or `"inline"` instead of `"normal"` because nobody knows what normal is :).

**Comment by alexandrudima** [comment]
@jrieken Is this item changing also the out of the box sort order? (i.e. is #8758 really a dup of this one?)

**Comment by jrieken** [comment]
Yeah, makes sense. To summarise: `editor.snippetSuggestions : "top" | "bottom" | "inline" | "none"`

**Comment by jrieken** [comment]
`snippetSuggestions: 'top' | 'bottom' | 'inline' | 'none';` it is

**Comment by shreyas-a** [comment]
is this feature live yet. if not when we can expect this

**Comment by dsifford** [comment]
@shreyas-a Yep, it's live. In your settings search for `editor.snippetSuggestions`. From there you can choose between `top`, `bottom`, `inline`, or `none`.

**Comment by shreyas-a** [comment]
Thanks, works perfectly. Don't you think the default option should be "inline"
I got easily confused about how my snippet suggestions suddenly started appearing at bottom. I'm sure many folks must be having same problem.

**Comment by PotterDai** [comment]
There should be an option of "inline-top".
Using current "inline" option, snippets will always come last.
