### ISSUE TITLE
Iconography: The field icon is too similar to the method icon (Accessibility)

### ISSUE THREAD

**Issue by mhoelzel142** [microsoft/vscode#92877]
Starting around the time that the vs code iconography was changed to the new pencil thin "high contrast" versions, the field icon became hollow and outlined. 

This does not match the iconography in any other Microsoft product, or IDE in general, and is objectively more difficult to identify at a glance. 

For those who are visually impaired, these icons are difficult to tell apart since the only difference between field and property are the width of the icons (which is only a few pixels): 

New "improved" iconography: 
![image](https://user-images.githubusercontent.com/15573387/76892632-01374980-6859-11ea-838d-0d2cbd92f4c2.png)

Old, universal, easy to see and easy to understand icon:
![image](https://user-images.githubusercontent.com/15573387/76892842-4eb3b680-6859-11ea-8a88-685b0c9748d1.png)

Same icons in Visual Studio (2017 and 2019): 
![image](https://user-images.githubusercontent.com/15573387/76893306-1eb8e300-685a-11ea-9c0c-e63fd696596c.png)

I'm requesting that the field icon be changed back to how it was before, as it impacts accessibility and productivity, especially for visually impaired people.

**Comment by misolori** [comment]
Please upvote #79130 where you will be able to customize icons to your liking
