### ISSUE TITLE
Java syntax colors is not working

### ISSUE THREAD

**Issue by shanewaz-abbas** [microsoft/vscode#92871]
Issue Type: <b>Bug</b>

I thought this might be a Java extension related issue, so I posted on their issue section, to no response. But I'm thinking that due to it using language server, its possible vscode latest version introduced some breaking changes?

Are there any logs that one can look at to pinpoint the issue?

![image](https://user-images.githubusercontent.com/61433809/76884079-e1edeb80-685b-11ea-90d7-a0b44873e1b1.png)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.19564
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 5.3.0-40-generic

<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|2.0.0
Angular2|joh|9.1.2
Angular-BeastCode|Mik|8.1.2
vscode-docker|ms-|1.0.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
sublime-keybindings|ms-|4.0.6
debugger-for-chrome|msj|4.12.6
awesome-flutter-snippets|Nas|2.0.3
vscode-icons|vsc|10.0.0
gitlens|eam|10.2.1
tslint|eg2|1.0.44
vscode-lombok|Gab|1.0.1
gradle-language|nac|0.2.3
vscode-spring-boot|Piv|1.15.0
java|red|0.58.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.1
vscode-spring-boot-dashboard|vsc|0.1.8

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Is this with all themes?
Can you select an identifier (e.g. `AwsBeanConfig`), invoke the command `Developer: Inspect Editor Tokens and Scopes` and attach a screenshot here?

**Comment by shanewaz-abbas** [comment]
Hi, @aeschli . Yes this is with _all_ themes. Here's the screenshot:

![image](https://user-images.githubusercontent.com/61433809/76981768-c812de00-6919-11ea-81b0-288fd939c38e.png)


Among other things, I've also tried reinstalling vs code.

**Comment by aeschli** [comment]
Make sure the Java Language Basics extension is enabled.

![image](https://user-images.githubusercontent.com/6461412/77001986-14324280-695b-11ea-9668-28b7384c8ea6.png)

**Comment by shanewaz-abbas** [comment]
Ah that explains it. Thanks that fixed it.
