### ISSUE TITLE
Tab key not auto completing 

### ISSUE THREAD

**Issue by dominait** [microsoft/vscode#92873]

**Comment by PlanMan1717** [comment]
I am not part of Microsoft's VS Code, but I think I can help you solve this problem.

Try adding ```"editor.tabCompletion": "on",``` to settings.json

1. Press Ctrl + ,
2. Press the little button above the right end of the search bar at the top that looks like an arrow pointing at a file.
3. Paste the code into the middle of the file somewhere where the other lines look similar in syntax.

Try that. Feel free to tell me if it doesn't work.

**Comment by gjsjohnmurray** [comment]
@PlanMan1717 suggested:

> Try adding `"editor.tabCompletion": "on",` to settings.json
> 
>     1. Press Ctrl + ,
> 
>     2. Press the little button above the right end of the search bar at the top that looks like an arrow pointing at a file.
> 
>     3. Paste the code into the middle of the file somewhere where the other lines look similar in syntax.

Even easier after step 1 is to search for 'tabcom', then alter the setting using the dropdown:

![image](https://user-images.githubusercontent.com/6726799/77189740-f508f180-6acf-11ea-9c61-5018b41bd141.png)

**Comment by aeschli** [comment]
Closing the issue. Please reopen if the suggestions did not solve the issue.
If you do so, please add more information that help us reproduce the issue.

**Comment by dominait** [comment]
Tab completion is on. Started when I updated to latest version...
Jim

**Comment by dominait** [comment]
Tab Completion is on that's why I thought... Still no tab auto completion
in the integrated terminal.
Had to switch to the built in MAC terminal.
Thanks For Helping
Jim
