### ISSUE TITLE
List: provide option to not render hover background feedback on certain elements

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92872]
In call stack view I would not like to render hover feedback for the Load More button. Related discussion https://github.com/microsoft/vscode/issues/83986#issuecomment-600117885

I would also potentially use it in the Debug Console

**Comment by joaomoreno** [comment]
Just reject the drag over call: https://github.com/microsoft/vscode/blob/a8c58cf52f4a217b0b0e374ee20d901e78013199/src/vs/base/browser/ui/list/list.ts#L103-L103
