### ISSUE TITLE
Jupyter notebook - Executing markdown cells adds unnecessary fields to metadata

### ISSUE THREAD

**Issue by hagh** [microsoft/vscode#92878]
- VSCode Version: 1.43.0
- OS Version: Ubuntu 18

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.0.0-1032-azure snap

Steps to Reproduce:

1. Open a Jupyter notebook (.ipynb file)
2. Execute a markdown cell
3. This adds additional properties 'outputs' and 'execution_count' which is not considered valid in some other parsers. For example Jupyter generates following error when you open the notebook:

Notebook validation failed: Additional properties are not allowed ('outputs', 'execution_count' were unexpected):
{
 "cell_type": "markdown",
 "execution_count": null,
 "metadata": {},
 "outputs": [],
 "source": "... some markdown ..."
}

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Please file this against the Python extension: https://github.com/Microsoft/vscode-python
