### ISSUE TITLE
cannot copy paste from/to terminal

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#9287]
- VSCode Version:1.3.1
- OS Version: ubuntu 16.4

Steps to Reproduce:

try to copy something `ctrl+c` naturally fails but normally on a terminal on linux you can use `ctrl+shift+c`
in vscode it opens a new terminal and also right click wont work

**Comment by weinand** [comment]
@NikosEfthias this is for the 'integrated terminal'?

**Comment by NikosEfthias** [comment]
@weinand yes it is

**Comment by Chiliyago** [comment]
I just noticed this today as well.  Cut & Paste not funtioning in terminal pane.

**Comment by Tyriar** [comment]
I just updated the website today to cover the topic :smiley: https://code.visualstudio.com/docs/editor/integrated-terminal#_key-bindings
