### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by eidmanna** [microsoft/vscode#92883]
Issue Type: <b>Performance Issue</b>

Very slow startup of VS Code after clean install.

Startup time > 30 sec.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3516)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (4.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    74	  8892	code main
    0	    24	  4924	   utility
    0	   102	 10488	   gpu-process
    0	   171	 10948	   window (prof-1261.main.cpuprofile.txt - Development - Visual Studio Code)
    0	    65	 12160	     extensionHost
    0	    11	 12580	     watcherService 
    0	    11	 12588	       console-window-host (Windows internal process)
    5	    67	 11068	   shared-process
    0	    14	 12508	   electron-crash-reporter
    0	    66	 12544	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (prof-1261.main.cpuprofile.txt - Development - Visual Studio Code)
|    Folder (Development): 2427 files
|      File types: class(626) png(553) gif(324) css(74) html(69)
|                  properties(68) xml(50) jpg(32) prefs(15) dat(12)
|      Conf files:;
```

</details>
Extensions: none

Profile files of 

code --prof-startup:

[prof-1261.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4345971/prof-1261.main.cpuprofile.txt)

[prof-1261.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4345972/prof-1261.renderer.cpuprofile.txt)

[prof-1261.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4345973/prof-1261.extHost.cpuprofile.txt)

**Comment by eidmanna** [comment]
Hi @jrieken,

pls tell me, what additional information you need.

You have 3 profile files and all the technical specs of my computer and the installed vs code.

I am using VS Code on several other computers (also with slower hardware)  and the startup time is always < 10 sec.

Only in this case I have > 20 sec.

What could be the problem?

BR

**Comment by eidmanna** [comment]
What is the reason for this?

7 sec for a crashreport, but I do not see a crash. 

After 30 sec VS Code is up and running without any problems.

![image](https://user-images.githubusercontent.com/978270/77013630-b6a8f080-6970-11ea-884f-a506fd4e521d.png)

**Comment by jrieken** [comment]
> pls tell me, what additional information you need.

I need those profile files that you have uploaded with your second edit

**Comment by jrieken** [comment]
It seems to take very long to launch new processes on that machine. That's a known issue on windows and often caused by AV software

<img width="998" alt="image" src="https://user-images.githubusercontent.com/1794099/77049883-264aca00-69c9-11ea-8c44-583c75048219.png">


<img width="452" alt="image" src="https://user-images.githubusercontent.com/1794099/77049885-28148d80-69c9-11ea-8e48-b65f58d094bf.png">

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aperf+label%3Aperf-startup+label%3Awindows
