### ISSUE TITLE
VSCode helper on macOS has excessive CPU usage

### ISSUE THREAD

**Issue by SumNeuron** [microsoft/vscode#92882]
- VSCode Version: 1.43.0
- OS Version: 10.15.3 macOs

Steps to Reproduce: just open a project with `code .`

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**NOTE**
As per this [statement](https://github.com/microsoft/vscode/issues/51776#issuecomment-427150562), new issue with vscode helper here

**Comment by aeschli** [comment]
If you can get additional information as described in https://github.com/microsoft/vscode/wiki/Performance-Issues that would be great.
