### ISSUE TITLE
Can't get intellisense to link params for anonymous functions

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#9288]
- VSCode Version: Version 1.3.1 (1.3.1)
- OS Version: osx 10.11.5 (15F34)

## Goal

```js
return sftp.readdirAsync(dir)
  .then(function(/*Array<String>*/dirList) {
    dirList // <-- I want intellisense hinting on this array
```

## Expected
<img width="314" alt="screenshot 2016-07-14 10 02 04" src="https://cloud.githubusercontent.com/assets/317498/16842074/0e2baf18-49aa-11e6-861d-e4ba747923d6.png">

## Actual
<img width="287" alt="screenshot 2016-07-14 10 02 49" src="https://cloud.githubusercontent.com/assets/317498/16842103/26229730-49aa-11e6-8a2c-d3223789ea1b.png">

## Things I've tried

1. `.then(function(/*Array<String>*/dirList ) {`
1. `.then(function(/**Array<String>*/dirList ) {`
1. `.then(function(/**@type Array<String>*/dirList ) {`
1. `.then(function(/**@type {Array<String>}*/dirList ) {`
1. `.then(function(/**@type {String[]}*/dirList ) {`
1. `.then(/**@param {String[]} dirList */ function(dirList ) {`
1. `.then(function(dirList/**=String[]*/) {`
1. `.then(function(dirList/*=String[]*/) {`
1. `.then(function(dirList/*:String[]*/) {`
1. `.then(function(/**{String[]}:*/dirList ) {`
1. `.then(function(/*String[]:*/dirList ) {`

😢 Help

**Comment by Sequoia** [comment]
readdirAsync is result of promisifyAll so not easily doc-linkable. (i.e. I can't easily mark the `@return {Promise<String[]>}` on that method).

**Comment by egamma** [comment]
@Sequoia in general the supported jsdoc annotation are defined in this [doc](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript).

This form works for me:
```js
 sftp.readdirAsync(dir)
  .then(
      /** @param {string} dirList*/function (dirList) {
```

This form does **not** work for me (open paren in front of jsdoc comment):
```js
 sftp.readdirAsync(dir)
  .then
      (/** @param {string} dirList*/function (dirList) {
```

Moving to TypeScript for comment.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#9755
