### ISSUE TITLE
Syntax highlight bug in js

### ISSUE THREAD

**Issue by felipe-ds-lima** [microsoft/vscode#92889]
Hello, in vscode version 1.43, I have a bug in the syntax color in the js files, always in function parameters with my official or standard dracula theme, the color is orange or blue, and the "require" function for example is also in blue, as well as some other syntaxes, but in version 1.43, they are white.

**Comment by felipe-ds-lima** [comment]
If someone falls here just put this configuration:

"editor.semanticHighlighting.enabled": false

**Comment by gjsjohnmurray** [comment]
Also see https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#semantic-highlighting

Improvements are coming soon in the 1.43.1 recovery release.
