### ISSUE TITLE
Crash on pressing ESC on MacOS

### ISSUE THREAD

**Issue by Hanlin-Dong** [microsoft/vscode#92880]
Issue Type: <b>Bug</b>

On pressing ESC, the VSCode exits without any warning(seems to crash). This issue happens after the latest update.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 6|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
todo-tree|Gru|0.0.169
latex-workshop|Jam|8.7.2
vscode-language-opensees|jam|0.1.2
calculator|lix|0.1.1
python|ms-|2020.2.64397
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
csv-to-table|php|1.2.3
material-icon-theme|PKi|4.0.1
vscode-javascript-booster|sbu|0.11.0
code-spell-checker|str|1.8.0
open-in-browser|tec|2.0.0
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by deadcoder0904** [comment]
Yes yes yes. This happened to me after the latest update 2-3 days ago.

I thought this happened because I enabled `Neon Glows` for the `Synthwave ‘84` theme & it gave the `Your Code installation appears to be corrupt. Please reinstall.` warning.

But it kept happening again & again. Now it has crashed for me 5-6 times in the span of 2-3 days.

Please look into this. VSCode never crashed for me for the last 3 years I’m using it until now :(

**Comment by deepak1556** [comment]
Can you try the latest insiders https://code.visualstudio.com/insiders/ and see if it still crashes ?

**Comment by Hanlin-Dong** [comment]
> Can you try the latest insiders https://code.visualstudio.com/insiders/ and see if it still crashes ?

@deepak1556  I updated to version 1.43.1 yesterday. It seemed that probably the issue was solved in this version. I will try this for a longer time and give a feedback.

**Comment by deepak1556** [comment]
Thanks @Hanlin-Dong for the update, I merging this to https://github.com/microsoft/vscode/issues/92420. Please do update with your findings there.
