### ISSUE TITLE
Minor UI inconsistencies

### ISSUE THREAD

**Issue by TimGr** [microsoft/vscode#92888]
Hi everyone, 

I build my own theme recently and have taken a detailed look at a few features and found some minor inconsistencies. Correcting these inconsistencies could help Visual Studio Code to look more harmonious in my opinion.

I hope it's okay to file them all in one issue? If not, please let me know so I can split them. And I'm sorry if this issue seems a bit picky :sweat_smile:.

Let me know if anything is unclear, or if I can help in any way.
Tim

---

## 1. Input heights
I found different heights within Visual Studio Code and counted a total of six different values: 38px, 48px, 50px, 52px, 56px and 60px. Perhaps we can reduce/unify these to a set of three values, like small, medium and large? In my opinion, at least the inputs in the sidebar should have identical heights to prevent small layout jumps when changing the sidebar view.

<img width="1280" alt="vscode-input-heights" src="https://user-images.githubusercontent.com/3532570/76908515-29e72f80-68a9-11ea-9e7b-fdfe11d6bd69.png">

## 2. Alignments in sidebar
The vertical alignment in the sidebar views could be more consistent. Please see the attached screenshot where I have marked the deviating areas.

<img width="1280" alt="vscode-sidebar-alignment" src="https://user-images.githubusercontent.com/3532570/76908563-4b481b80-68a9-11ea-8d82-0a9538b95956.png">

## 3. Input background colors

It would be great if theme designers could use inputs that are always brigther or darker than the underlying surface by setting e.g. #ffffff1A instead of a solid color. If you only can use a solid color you need to take a brigther or darker color than the brightest or darkest surface that hosts an input.  

It's currently possible, but some inputs are nested and the background color is applied to two elements and therefore you have two transparent colors on top of each other.
This can be seen in:
- the extension-search-input in the extension sidebar view
- the search-input in the preferences (UI) view 

<img width="1280" alt="vscode-transparent-input-backgrounds" src="https://user-images.githubusercontent.com/3532570/76908713-a974fe80-68a9-11ea-88d1-39b8a8216010.png">

## 4. Input theme references
I expected that the overall search input in the UI preferences view is styleable via `settings.textInputBackground` and `settings.textInputForeground`. But currently the search input is styled via `input.background` and `input.foreground`.

Please take a look at the attached screenshot. And you may want to use this setting snippet for further debugging.

<img width="1280" alt="vscode-input-theme-references" src="https://user-images.githubusercontent.com/3532570/76908802-e640f580-68a9-11ea-9c7e-c2644cf3dc85.png">

```
    "workbench.colorCustomizations": {
        "input.background": "#0000ff",
        "input.border": "#ffff00",
        "input.foreground": "#ffffff",
        "settings.textInputBackground": "#00ff00",
        "settings.textInputForeground": "#000000",
        "settings.textInputBorder": "#ff0000",
    },
```

**Comment by misolori** [comment]
Thanks for the suggestions. Do you mind breaking these out into separate issues so that we can better track and manage them? We try to avoid having meta issues (unless they're feature requests). A few thoughts:

1. I agree that all input heights should be the same
2. Spacing can be fixed
3. I don't quite understand this issues, but I believe #4 will solve this
4. I believe we should be able to create new styles for inputs in the sidebar and other places
