### ISSUE TITLE
The code writing assistance is not showing up after some hours of working!

### ISSUE THREAD

**Issue by gre-dev** [microsoft/vscode#92884]
Issue Type: <b>Bug</b>

Some of the extensions are not working after some hours of working in a not very large project. And the problem also effects in the whole editor, so I cannot writing the code with the assistance of the editor (with Tab key), I have to write it myself!

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.89GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
path-intellisense|chr|1.4.2
vscode-great-icons|emm|2.1.47
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-apache|mrm|1.2.0
vscode-autoprefixer|mrm|3.0.0
es6-css-minify|olb|3.3.2
sass-indented|syl|1.7.5

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
What programming language?

**Comment by gre-dev** [comment]
@mjbvz 

PHP, HTML, CSS and JS.
I'm facing the problem with any programing language I use.

I googled about this issue and I tried also disabling all the installed extensions I have, but it doesn't work.

I changed the computer also because I was using a little bit slow laptop and I said that it's normal to face problems like these. But after buying another computer (iMac), I see that I'm facing the same problem again!

But now, I'm solving the problem by reopening the program and it back to it's normal mode. And again after some hours of working I face the same problem and so on.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by jrieken** [comment]
esp this part of the aforementioned guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by gre-dev** [comment]
@jrieken 

Here is the profile of the running extensions:
I uploaded it [here](https://drive.google.com/file/d/1zArEiogBgsBCHLC7o8nk8iuXMvrWI_Xd/view?usp=sharing) because of it's size is over 10MB.

In the Runing Extentions page I see that "Auto Rename Tag" shows an alert say that there's a performance issue as the image below:
![Screen Shot 2020-03-19 at 20 58 03](https://user-images.githubusercontent.com/59331174/77099132-7f941700-6a24-11ea-8ecd-2777cd9e1ff9.png)

**Comment by jrieken** [comment]
Thanks for following. There is little that we can do except for asking you to file a bug with the extension author. Also, automatic tag rename is built into VS Code so this extension (if it does what its title suggests) shouldn't be needed anymore
