### ISSUE TITLE
Graphical glitch in Vscode under Windows 10

### ISSUE THREAD

**Issue by 4z3r** [microsoft/vscode#92887]
here a picture of the glitch:
![vscode](https://user-images.githubusercontent.com/58311900/76909349-497f5780-68ab-11ea-89c8-bc4e16293ab5.png)

- VSCode Version:1.43.0(user setup)
- OS Version:18363.693

Steps to Reproduce:

1.open Vscode
2.it happens randomly

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by gjsjohnmurray** [comment]
Does this reproduce if you launch with the --disable-gpu command line argument?

**Comment by 4z3r** [comment]
> Does this reproduce if you launch with the --disable-gpu command line argument?

It Works fine using the --disable-gpu method

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration for another way to make that setting happen.

Please close this issue.
