### ISSUE TITLE
Reduce delay on semantic tokens provider pull at moment file is opened.

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode#92886]
In VSCode Insiders 1.43: When opening in the editor a file associated with a semantic tokens provider, but no TM grammar for the language, there is a noticeable shimmer before highlighting takes effect - regardless of file size or number of tokens.

From #86168, I understand the reason for a delay while typing (which is hardly noticeable), but could this not be reduced for the initial file load?

From reading the source code it appears the delay is 300ms now, but I could’ve been looking at the wrong part.

**Comment by alexdima** [comment]
@pgfearo The source code is written to initially make the request without a delay of 300ms. I've added logging between buffer creation and the invocation to provide document semantic tokens to validate and I can confirm that this appears to work as implemented:
```
[1585603632044] createModel: file:///c%3A/Alex/src/TypeScript/src/compiler/builder.ts
[1585603632093] invoking provideDocumentSemanticTokens
```
The second one occurs about 49ms later, which is perhaps the time it takes the editor to create a new view and render the first frame...

Note that I have measured this for when the TS language service was already hot. The first opened document ends up waiting for the extension host to start, for the extension to activate, etc.

@pgfearo Have you observed on your side a delay between document creation and the semantic tokens request? You can log from the extension the document open event and the semantic request call.

**Comment by pgfearo** [comment]
Ok, thanks for the update,  I will put in some logging to time the delay as
you suggest.

**Comment by pgfearo** [comment]
Here are the typical timings I can measure:

15:44:49.608 onDidOpenTextDocument
15:44:49.631 provideDocumentSemanticTokens
15:44:49.641 return tokens count: 1999

So, just 23ms from the 'open' document event and the call to 'provideDocumentSemanticTokens'.
It then takes a further 10ms to return the (1999) tokens for 280 lines of XSLT code in this case.

So, 33ms is not much of a delay, but enough for the eye to perceive a flicker.

I suppose the only way to prevent this would be to avoid any rendering at all until either the semantic tokens are returned, or a predetermined 'timeout' interval has passed.

**Comment by alexdima** [comment]
> I suppose the only way to prevent this would be to avoid any rendering at all until either the semantic tokens are returned, or a predetermined 'timeout' interval has passed.

Everything in the editor is built to work with the extension host crashing on purpose. e.g. it is possible to continue typing and save your file even if the extension host process is dead. I will not block the rendering of the editor on an extension host request.

I acknowledge the fact that there is flickering, but how bad is it? Semantic tokens should complement the TM grammar, do you have a TM grammar?

**Comment by pgfearo** [comment]
The flickering isn’t too bad, probably more noticeable as I was watching for it. There’s a built in TM Grammar for ‘xsl’ (don’t know why it was misnamed, the only correct language name is ‘xslt’) but it comes with bracket matching settings etc that I don’t seem to be able to override in the extension I’m developing.

I could always incorporate that TM grammar (flaws and all) into my extension, safe in the knowledge that all TM tokens will be overridden by Semantic Tokens. It does seem a waste of cpu to tokenise twice though.

All that said, this flicker problem is not a priority, (the way I’m having to misuse semantic token super types for tags etc. Is more of a worry) and a workaround would be a transient TM Grammar, so I’m happy for this to issue to be closed.
