### ISSUE TITLE
YAML syntax highlighting fails on empty blocks

### ISSUE THREAD

**Issue by TJM** [microsoft/vscode#92885]
- VSCode Version:1.43.0
78a4c91400152c0f27ba4d363eb56d2835f9903a
x64
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Open a yaml file that has empty blocks with content below, such as https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml
2. Scroll down to line 233 - the color should be "green" (comment color) not "orange" (string color)... the highlighting is messed up until line 1078, then quickly goes astray again. In order to be considered part of the block, it should be indented, the next non-indented line ends the block. So, the first comment line that is not indented means the value is empty

Does this issue occur when all extensions are disabled?: Yes

![Screen Shot 2020-03-17 at 4 51 42 PM](https://user-images.githubusercontent.com/1641316/76908970-a0ffd200-686f-11ea-83aa-3ffcd3867bf2.png)

See Also: https://github.com/jfrog/charts/issues/687

REF: https://yaml-multiline.info/

**Comment by alexr00** [comment]
Moved to owning repo.

**Comment by TJM** [comment]
Thanks @alexr00 :)
