### ISSUE TITLE
the left- bottom git icon doesn't work well

### ISSUE THREAD

**Issue by hx83** [microsoft/vscode#92897]
Issue Type: <b>Bug</b>

When vscode startup ,click the left- bottom git icon,editor will show git branch list on the top,but after about 10s ,it doesn't work.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
docomment|k--|0.1.8
vscode-language-pack-zh-hans|MS-|1.43.7
csharp|ms-|1.21.14
Go|ms-|0.13.1
unity-tools|Tob|1.2.3
unity-snippets|Ycl|0.1.2

</details>

**Comment by aeschli** [comment]
What do you mean by it doesn't work?

**Comment by hx83** [comment]
> What do you mean by it doesn't work?

When I click the left- bottom git icon,git branch list doesn't show anymore

**Comment by hx83** [comment]
Sorry, after waiting a long time ... now everything is fine. Maybe the reason is that there are too many files in my project.
