### ISSUE TITLE
The comments API doesn't appear to allow comments to start out in edit mode

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vscode#92892]
I'm working on the [CodeTour](https://aka.ms/codetour) extension, and as part of that, I want to be able to create comments that start out in edit mode by default (to improve the walkthrough "recording" experience). However, I haven't been able to get that to work, and it *seems* like comments need to start out in preview mode, and then can only transition to edit mode in response to a user-action (e.g. running a command).

Aside from CodeTour, if I take the [comments sample](https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample) project, and tweak it to include the following simplified code on activation, then the displayed comment is shown in preview mode, despite the code indicating that it should be in editing mode.

**Code**

```javascript
const commentController = vscode.comments.createCommentController('test', 'Test');
vscode.workspace.onDidOpenTextDocument(document => {
	const range = new vscode.Range(0, 0, 0, 0);
	const comment = new NoteComment('Test', vscode.CommentMode.Editing, { name: 'Test' });
	commentController.createCommentThread(document.uri, range, [comment]);
});
```

**Behavior**

<img width="600px" src="https://user-images.githubusercontent.com/116461/76911375-08b51d80-686e-11ea-8af8-b202070a9722.png" />

Based on the above code snippet, it *seems* like the comments API doesn't respect the mode property when creating new comments. And it would be awesome if it did :) Also, it's possible that I'm doing something wrong, so any advice on this would also be greatly appreciated. Thanks!

// CC @rebornix

**Comment by rebornix** [comment]
Will look into this issue in debt week of April.

**Comment by roblourens** [comment]
I don't think this is working. I see a comment in each file when I open it but it is not expanded and not in edit mode.

**Comment by roblourens** [comment]
![Apr-29-2020 17-52-33](https://user-images.githubusercontent.com/323878/80654599-42b73900-8a42-11ea-85ae-fc5bff1fb4ad.gif)

**Comment by JacksonKearl** [comment]
Still seeing the same as rob

**Comment by JacksonKearl** [comment]
Verified comments do start out in edit mode, but they do not start expanded. Not sure if that's expected.
