### ISSUE TITLE
内容占用高

### ISSUE THREAD

**Issue by monty086** [microsoft/vscode#92896]
Issue Type: <b>Bug</b>

跟新到最新版本发现内容占用高，都没有启动服务，只是打开代码发现内容占用高

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

**Comment by zwuis** [comment]
English please.

It's meaningless to add an not detailed issue.

In my machine, VS Code uses about 180 MB memories without extension enabled.
