### ISSUE TITLE
Allow Code to be a default editor for json

### ISSUE THREAD

**Issue by xobs** [microsoft/vscode#92898]
Visual Studio Code has a pretty great JSON editor, and seems to have defaults for things like Windows Terminal Preview.  However, Visual Studio (not Code) takes the default extension registration for JSON.

It would be nice if Visual Studio Code could be registered as an editor for `.json` files.  Currently Windows does not appear to provide a means to set file association so that `.json` files can be edited by Code.

![image](https://user-images.githubusercontent.com/238325/76924309-e88a6a80-6910-11ea-89ed-6542beeb9222.png)

**Comment by gjsjohnmurray** [comment]
Is #61084 relevant? You haven't posted your version numbers.

**Comment by xobs** [comment]
I don't believe so.  I just installed vscode today.  Apologies for not including version numbers.

```
Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by gjsjohnmurray** [comment]
For me this procedure works:

1. In Windows Explorer right-click on a .json file and choose "Open with" to get this dialog:

![image](https://user-images.githubusercontent.com/6726799/76954143-cb04d300-6907-11ea-82c4-5875c606927b.png)

2. Choose "More apps"

3. Find Visual Studio Code in the list, select it and click OK.

My version info:
```
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
If this doesn't work for you, perhaps the fact that yours is "(system setup)" may be significant.

**Comment by xobs** [comment]
Right, step 1 requires me to find a .json file.  It seems like the official Windows way to set file associations is through `Setup -> Apps -> Default Apps -> Choose default applications by file type`.

"Microsoft Visual Studio 2019" shows up in that list, but "Visual Studio Code" does not, and there is no "More apps" option.

**Comment by xobs** [comment]
This became an issue today because I was trying to change the settings in Windows Terminal Preview, which opens the json config file in the default editor.  Visual Studio 2019 takes a long time to start up, so I thought I would change the file association.

Because I didn't have the location of the actual file, there was nothing to right-click.  I suppose I could have created a new text file, renamed it, and then right-clicked on it to get the "Open With" dialog, but if the recommended way of changing file associations in Windows is through "Choose default applications by file type", and Visual Studio Code is designed to edit json files by default, then Visual Studio Code should appear in that list.

It shows up there for `.txt`, but not for `.json`.

**Comment by xobs** [comment]
Additionally, it should be noted that if I create an empty file and rename it to have an extension that ends in `.json`, I can right click and change what it opens with there.  In that list, Visual Studio Code does show up:

![image](https://user-images.githubusercontent.com/238325/77033400-1ab7cd00-69e2-11ea-89dd-23deb2423211.png)

It still does not show up in the system-wide list of handlers for json, however.

**Comment by joaomoreno** [comment]
> It still does not show up in the system-wide list of handlers for json, however.

That seems like an issue of Windows though, I suggest giving them that feedback instead.

**Comment by xobs** [comment]
It seems like an issue with VSCode, though.  Visual Studio 2019 registers itself as an editor, but VSCode does not.
