### ISSUE TITLE
Venv and packages

### ISSUE THREAD

**Issue by lucas-giraldelli** [microsoft/vscode#92899]
With venv, using sudo inside terminal while trying to install packages(with pip in my case) causes you to install packages globally.

- VSCode Version: 1.43.0
- OS Version: Linux x64 4.19.0-8-amd64
- Distro: Debian GNU/Linux 10 (buster)

Steps to Reproduce:

1. Create a venv
2. Change your Interpreter
3. Try to use sudo to install any packages on your venv

**Comment by lucas-giraldelli** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [sometimes does not recognize venv in python (#92416)](https://www.github.com/microsoft/vscode/issues/92416)

This is very specific to sudo command, if i not use sudo, i can easily install packages (with pip at least)

**Comment by aeschli** [comment]
How's that related to VSCode?

**Comment by lucas-giraldelli** [comment]
Oh, this is related to Python microsoft's extension to vscode.. sorry.
