### ISSUE TITLE
Handle 410 from the sync server

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#92890]
410 (gone) will be returned from the server in the future after the API has been deprecated for a period and finally removed. This should disable sync for the client, present a message about how an update is needed and potentially provide links to make updating easier.

Proposed message:

> This version of ${product.nameLong} is no longer compatible with the Sync service.
>
> [Link to update/download latest]

Writing to the log that this happened, including the body text would also be good (in case we find a use for a custom message other than "Gone").

**Comment by sandy081** [comment]
@Tyriar Please verify.

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/83650945-ca2a2780-a56d-11ea-8bce-3e404b0c6843.png)

I think the wording could be improved as it's pretty verbose and "turn on sync to continue syncing" could be better, I also notice that the error message is shared between the client is very old (410 and local version incompatibility) and the client version is blocked due to a bug (426, #98530). Not having different messages could confuse people as a new version installed the same day could be blocked.

@gregvanl any suggestions for a better error message?

**Comment by gregvanl** [comment]
How about: "Preferences Sync is disabled because the current version (1.46, undefined) of <blah> is not compatible with the Sync service. Please update before turning on Preferences Sync."

**Comment by Tyriar** [comment]
Since we already know the topic is "Preferences Sync" how about contracting it and removing the caps?

> "Preferences sync is disabled because the current version (1.46, undefined) of is not compatible with the sync service. Please update before turning on sync."

**Comment by sandy081** [comment]
Thanks for better message. 

I would go with single message as both needs updating.  

> as a new version installed the same day could be blocked?

May I know how a new/latest version is blocked?

**Comment by Tyriar** [comment]
> May I know how a new/latest version is blocked?

If we wanted to blacklist a misbehaving client commit

**Comment by sandy081** [comment]
In which case there shall be a client commit (which I suppose latest than reported one) that users can update to. Otherwise there will not be any user action right?

**Comment by Tyriar** [comment]
@sandy081 that's right, was thinking we might get some issues from people asking why insiders is not compatible, sharing the message should be good enough though.
