### ISSUE TITLE
Hotkey  "alt+G" opened a "Go" menu, but I config this hotkey as goto define. I don't like use F12, because my left hand need move far. So I want a config to disable all hotkey of open a menu.

### ISSUE THREAD

**Issue by gzx-miller** [microsoft/vscode#92894]
Issue Type: <b>Feature Request</b>

Hotkey  "alt+G" opened a "Go" menu, but I config this hotkey as goto define. I don't like use F12, because my left hand need move far.
So I want a config to disable all hotkey of open a menu.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

**Comment by ArturoDent** [comment]
Try disabling

> Workbench > Enable Menu Bar Mnenomics

then you can use `alt+G` for some other command.

**Comment by aeschli** [comment]
@ArturoDent is right. Disable the mnemonics and add
```
    {
        "key": "alt+g",
        "command": "editor.action.revealDefinition",
        "when": "editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor"
    },
```
to you keyboard shortcut settings file.

**Comment by gzx-miller** [comment]
Thank you!
