### ISSUE TITLE
Dragging tabs to another open window does not do anything

### ISSUE THREAD

**Issue by bruno-tee** [Microsoft/vscode#9289]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Open two separate windows with files
2. Drag the a tab from one window to the tab bar in the other window
3. Nothing happens? I would expect this to move the file/tab to the window I just dragged it to.

**Comment by bpasero** [comment]
Has been fixed for July and you can try it from insiders build (see below).

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
