### ISSUE TITLE
Explorer is gone from the viewlet in insider

### ISSUE THREAD

**Issue by fara-nak** [microsoft/vscode#92891]
- VSCode Version: 1.44.0-insider
- OS Version: Win 10

Steps to Reproduce:

1. launch vscode insider

expected:
there should be a tab in the viewlet forexplorer:
![image](https://user-images.githubusercontent.com/48534922/76911457-53cf3080-686e-11ea-9730-c7e9307605ab.png)

actual:
there is no explorer tab:
![image](https://user-images.githubusercontent.com/48534922/76911580-60ec1f80-686e-11ea-8337-f9811d42bfca.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
When you right-click the activity bar, does `Explorer` show in the list?

![image](https://user-images.githubusercontent.com/6561887/76969482-ce489080-6900-11ea-90f3-6141941f3af2.png)

**Comment by fara-nak** [comment]
oh i probably unchecked it by mistake, sorry about that, thanks for the help :)
