### ISSUE TITLE
Incorrect code collapse if the text has no indentation

### ISSUE THREAD

**Issue by KostyaTretyak** [microsoft/vscode#92903]
```text
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic
```

Code to reproduce:

```ts
if (true) {
  const one = 1;
  const text = `first line
second line without indentation
`;
}
```

Result collapsing by curly braces
![image](https://user-images.githubusercontent.com/2286306/76931317-0f38a900-68f1-11ea-9f07-c783289b92d6.png)

As you can see, the collapse is incorrect due to the lack of indentation in the second line of text.

Generally, the same behavior is observed when there is no indentation near any code within the curly braces. But no indentation in the text has the necessary use case.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
What's the language mode of the editor?

**Comment by KostyaTretyak** [comment]
@aeschli, typescript

**Comment by gjsjohnmurray** [comment]
@KostyaTretyak have you seen the info here? https://code.visualstudio.com/docs/editor/codebasics#_folding

In particular:

> Folding regions are by default evaluated based on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

> Since the 1.22 release, folding regions can also be computed based on syntax tokens of the editor's configured language. The following languages already provide syntax aware folding: Markdown, HTML, CSS, LESS, SCSS, and JSON.

**Comment by KostyaTretyak** [comment]
@gjsjohnmurray, thanks for pointing to this documentation, I have read it now. However, I continue to view this as unexpected behavior. It is logical to assume that when you try to collapse the code in curly brackets, it collapses in curly brackets, not through indentation.

**Comment by aeschli** [comment]
Typescript has language aware folding and had an understanding of multi line strings.
Here's what I see when I try your example:
![tsfolding](https://user-images.githubusercontent.com/6461412/76953571-343c1480-690f-11ea-8dcf-eedc17cf35da.gif)

Please verify that your editor mode (lower right) is set to TypeScript.

**Comment by KostyaTretyak** [comment]
![image](https://user-images.githubusercontent.com/2286306/76953813-03141200-6918-11ea-900c-4e4c0b24e659.png)

**Comment by aeschli** [comment]
Did you change the setting `"editor.foldingStrategy"?
It should be "editor.foldingStrategy": "auto"

**Comment by KostyaTretyak** [comment]
I can't imagine when and for what I did it, but I had `"editor.foldingStrategy": "indentation"`. I apologize for the time you have spent.
