### ISSUE TITLE
Debug hover does not understand language syntax

### ISSUE THREAD

**Issue by a-magdy** [Microsoft/vscode#9290]
- VSCode Version:  1.3.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. We'll debug the following method with VSCode
2. Copy the following method:
    (function fn(){
      var x = '20'
      var y = 'x'
    })()  
3. Put a breakpoint on the line: var y = 'x'
4. Hover of the 'x' (inside the string)
5. Notice that the intellisense will show the value of x (the variable) on the string

**Comment by weinand** [comment]
@a-magdy this is a current limitation of debug hovers: the debug UI does not understand the language syntax.

**Comment by isidorn** [comment]
We have slightly imrpoved the debug hover so this specific bug is resolved.
Though debug hover still has the limitation that it does not understand the language syntax
