### ISSUE TITLE
Allow to run web integration tests against stable quality

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92908]
Currently seems to fail with our proposed API checks:

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=69868&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=087c9a82-9b9b-5b5f-17f2-a070cb4808e3

**Comment by bpasero** [comment]
I cannot get this to work and need help. Steps:
* download our **stable** server **with web** bits
* unzip
* `export VSCODE_REMOTE_SERVER_PATH=path/to/vscode-server-darwin-web`
* run `resources/server/test/test-web-integration.sh `

See:

```
[vscode.vscode-api-tests]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.vscode-api-tests: Error: [vscode.vscode-api-tests]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.vscode-api-tests
    at a (/Users/bpasero/Desktop/vscode-server-darwin-web/out/vs/server/remoteExtensionHostProcess.js:534:620)
    at Object.t.checkProposedApiEnabled (/Users/bpasero/Desktop/vscode-server-darwin-web/out/vs/server/remoteExtensionHostProcess.js:534:982)
```

What I did is, I made sure that I pass [`'--enable-proposed-api'`](https://github.com/microsoft/vscode/blob/e68ccf21bfe12b541ec3f26705441e5287e114c5/test/integration/browser/src/index.ts#L106) to the server process and I am greeted with this:

`Server stderr: Ignoring option enable-proposed-api: not supported for server.`

But I need a way to enable all proposed API for extensions when doing this because we run the `vscode.vscode-api-tests` which may access proposed API in tests.

@aeschli for the possibility that the server ignores this argument and @jrieken for the possibility that we actually never supported to enable proposed API like this from the command line for the server.

**Comment by aeschli** [comment]
Normally that's configured on the client side, and we don't need this cli option for the server.
I think for web it would make sense to add it. But in this example, it's about running a test and I would think that this is like running an extension under dev. 
`--extensionDevelopmentPath=$ROOT/extensions/vscode-api-tests` should be enough to signal that the proposed-api check is not necessary.

**Comment by bpasero** [comment]
> --extensionDevelopmentPath=$ROOT/extensions/vscode-api-tests should be enough to signal that the proposed-api check is not necessary.

Yes, you are right, so that puzzles me even more because obviously the `extensionDevelopmentPath` is making it to the extension host, otherwise none of the tests would run. Then maybe something is missing on the server to understand this?

My understanding is that all tests run in the server and not the web worker.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/9bd87e385258f7932abcf7943a011c8d43f5d4ba
