### ISSUE TITLE
Color block didn't work 

### ISSUE THREAD

**Issue by iRuxu** [microsoft/vscode#92905]
I uninstall all the plugins relatived to colors.
restart and all.
But in my files.
Some color block show,but some didn't.
![2](https://user-images.githubusercontent.com/8476969/76935217-ab7fa180-692b-11ea-8e6e-37b07cd5abc2.png)
Thanks a lot

**Comment by IllusionMH** [comment]
Is it LESS file?
Looks like duplicate of #92417

**Comment by iRuxu** [comment]
yes, it's a less file. 
This problem come out maybe two weeks?

**Comment by IllusionMH** [comment]
/duplicate of #92417

Should be fixed in recovery build for 1.43
