### ISSUE TITLE
Can't see data in QString and QObject

### ISSUE THREAD

**Issue by tusharma09** [microsoft/vscode#92910]
Issue Type: <b>Feature Request</b>

Cannot watch or hover check the values in QString while debugging which were available in QT. It would be nice to extend the support to view as many values in debugging. At the moment, this is the only thing making me go back to QT.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.3.0-42-generic snap

**Comment by aeschli** [comment]
Please file this against the C++ extension that provides the debugger:
https://github.com/microsoft/vscode-cpptools
