### ISSUE TITLE
ctrl+f and dragging the string duplicates it

### ISSUE THREAD

**Issue by Dangerous-Mind** [microsoft/vscode#92919]
Issue Type: <b>Bug</b>

Select a string then do ctrl+F.
Drag and drop the string.
It duplicates the string instead of moving it.

If you do F3 and drag/drop other strings they will also duplicate.
The "Spell" is broken if you click on the screen.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
spfx-snippets|eli|1.9.0
vscode-spfx-task-runner|eli|1.2.4
vscode-firefox-debug|fir|2.7.1
cpptools|ms-|0.26.3
powershell|ms-|2020.3.0
debugger-for-chrome|msj|4.12.6
vscode-spfx-deploy-package|Ren|1.1.0
vscode-scss-formatter|sib|1.4.3

</details>

**Comment by arjundevane** [comment]
Pressing Ctrl+F (windows) is not triggering `onKeyUp(e)` method. However `onKeyDown(e)` is triggered and that causes the drag-n-drop to consider the modifier button has been pressed.

Any other event that breaks the propagation chain ?
