### ISSUE TITLE
Test: debug progress events

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92914]
Refs: https://github.com/microsoft/vscode/issues/92253

- [x] any os @connor4312
- [x] any os @mjbvz

Complexity: 4

---

VS Code now shows [`debug progress events`](https://github.com/microsoft/vscode/blob/464ef8c1b3fe2e29d4dfd7b3d74cdcade7840566/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L321) via silent progress notifications.
Have a debug extensions that implements Progress Events, or use and modify the Mock Debug Extension https://github.com/microsoft/vscode-mock-debug (progress event is started by typing `progress` in debug console after staring a debug session).

Verify:

* VS Code shows progress with a 500 ms timeout (motivation here https://github.com/microsoft/vscode/issues/93029)
* VS Code shows an infinity blue spinner in the debug viewlet as long as there is an active progress event
* Have multiple progress events started simultaneously and make sure VS Code represents this correctly
* VS Code show a silent progress notification for each progress event
* If a progress event is `cancellable` make sure VS Code renders a Cancel button in the notification and pressing `Cancel` stops the progress
* Make sure the `label` of the debug extension is rendered as the `source` for the notification
* A `progressUpdate` event is respected (check that `message` gets updated)
* if the elapsed time between `progressStart` and `progressEnd` is shorter than 500 ms no progress is shown at all.
* Optional: check that `progressUpdateEvent` with `percentage` attribute is respected

**Comment by connor4312** [comment]
not opening a separate issue for the "message" not being visible since it looks like it's an outstanding item here: https://github.com/microsoft/vscode/issues/92253#issuecomment-600751222

**Comment by mjbvz** [comment]
Didn't see any issues in my testing on MacOS. Compound debugs with progress also worked great

**Comment by isidorn** [comment]
Thanks for testing it out 👏
