### ISSUE TITLE
cannot save as su

### ISSUE THREAD

**Issue by louisabraham** [microsoft/vscode#92918]
I'm using the headmelted buid on manjaro.

when trying to save a root file and retrying as a super user, I get the following error message:

```
Failed to save 'FILENAME': options.name must be alphanumeric only (spaces are allowed) and <= 70 characters.
```

I believe this comes from https://github.com/jorangreef/sudo-prompt

The error would be there:

https://github.com/microsoft/vscode/blob/e1d6bfe8b19eab7e4763f6dfb0e4bb5d1af9bf3f/src/vs/workbench/services/textfile/electron-browser/nativeTextFileService.ts#L289

It looks like `this.productService.nameLong`, defined in `src/vs/platform/product/common/product.ts` causes an error.

**Comment by bpasero** [comment]
@louisabraham so can you check what your value for `nameLong` is? It should appear when you open the welcome page (Help > Welcome) as the large name there.

**Comment by louisabraham** [comment]
Thanks for your answer!

I think nothing is written there so it's probably empty.

If it can help:
Version: 1.43.0 (user setup)
Commit: 6ec6f9e3f4d17f0cef0480688a1f350b9141e567

**Comment by bpasero** [comment]
@louisabraham where and how did you obtain this version of VSCode?

**Comment by louisabraham** [comment]
It's in my first sentence :) https://code.headmelted.com/

**Comment by bpasero** [comment]
I suggest you report this upstream to them. We do not support other distributions of VSCode and it is possible that they tamper with our product configuration in a bad way.
