### ISSUE TITLE
Code formatting causes Chinese character coding confusion in dart files.

### ISSUE THREAD

**Issue by yangfanyu** [microsoft/vscode#92912]
Issue Type: <b>Bug</b>

When I execute the code format operation shift + option + F in some dart files with Chinese characters, the Chinese character code of these files will become confused.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
githistory|don|0.6.3
code-runner|for|0.9.17
vscode-icons|vsc|10.0.0

</details>

<img width="453" alt="截屏2020-03-18下午5 31 53" src="https://user-images.githubusercontent.com/17940584/76946542-269e8300-693f-11ea-96a7-f62f6411f78d.png">
<img width="286" alt="截屏2020-03-18下午5 32 55" src="https://user-images.githubusercontent.com/17940584/76946579-361dcc00-693f-11ea-9d16-d04e5a4b6a04.png">
<img width="378" alt="截屏2020-03-18下午5 33 14" src="https://user-images.githubusercontent.com/17940584/76946587-3a49e980-693f-11ea-8790-4293c29af251.png">

**Comment by aeschli** [comment]
Please file this against the Dart extension: https://github.com/Dart-Code/Dart-Code
Also please provide the source snippet.
