### ISSUE TITLE
"open recent" files displays a list of recent files preceded with limited parent folder's names - 1.41.2

### ISSUE THREAD

**Issue by artofit** [microsoft/vscode#92924]
In Visual Studio Code 1.41.2 (under Linux).

**Select File> "Open Recent"**
A list of last opened files is displayed.
This list provides the full path name of each recent file preceding the actual file name.

**Problem**
if the path tree is deep or the names of the subdirectories are long, eg:
/run/media/toshpc/diskPh/share/data/skills/whatever/....etc
Because we do not see the name of the actual file(and it direct parent folder name), but the path tree from the root name.

**Solution**:
An option to limit the number of parent directories of a file
the option could be either an integer displaying the max number of parent directories, for example "2" parent directories.
That is: one wants to see the leave folder name and not the root name

AND/OR

an integer limit as the number of characters of the path name from its right, something as RIGHT(fullPathName, 50)

Thanks

**Comment by bpasero** [comment]
I suggest you start to use the recently opened picker via File > Open Recent > More. I do not intend to introduce a setting for this currently.
