### ISSUE TITLE
problem debugging second function in my function app

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [microsoft/vscode#92920]
We ha
Issue Type: <b>Bug</b>

My directory structure:
PythonFunctions
       MyFunc1
            _init_.py
            function.json        
       MyFunc2
            _init_.py
            function.json   
       local.settings.json
       requirements.txt
just as 'Azure Functions Python developer guide' recomends...

can successfully debug MyFunc1, but trying to debug MyFunc2 returns  404 Not Found when I call it using Postman, even vhen I close MyFunc1 from VS Code...
WHY ???

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.16.3
vscode-azurefunctions|ms-|0.21.0
python|ms-|2020.2.64397
azure-account|ms-|0.8.8
vs-keybindings|ms-|0.2.0
team|ms-|1.161.0
python|tht|0.2.3

**Comment by aeschli** [comment]
Please file this against the Python extension: https://github.com/Microsoft/vscode-python
