### ISSUE TITLE
searchEditor: "Go to definition" command opens "Peek definition" instead

### ISSUE THREAD

**Issue by franciscolourenco** [microsoft/vscode#92926]
- VSCode Version: 1.43.0
- OS Version: 10.14.6

Steps to Reproduce:

1. Search using the search editor
2. Right-click a path of a file in the results
3. Click "Go to definition"

![2020-03-18 14 19 35](https://user-images.githubusercontent.com/208149/76965107-0ca37700-6924-11ea-94fb-6ec8a7597181.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Yes - when there are two or more definitions, as in your sample, then the default is to show peek for all of them. You can configure this behaviour with the `editor.gotoLocation.multipleDefinitions`-setting.

cc @JacksonKearl for why there are multiple definitions

**Comment by franciscolourenco** [comment]
@jrieken this happens even when there is only one search result in the file.

**Comment by JacksonKearl** [comment]
@franciscolourenco I cant reproduce when there's only one result. Can you share an example where this happens?

**Comment by franciscolourenco** [comment]
@JacksonKearl can't reproduce, feel free to ignore. `editor.gotoLocation.multipleDefinitions` is good.
