### ISSUE TITLE
Quick input: should not select first when typing and not filtering

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92928]
I am trying to build a picker experience where the user types in the input field and the currently selected item should remain selected. I am getting far by simply not updating the picks on type and disabling filtering and sorting etc. but noticed that the input list is still calling this:

https://github.com/microsoft/vscode/blob/c3e6110d227eead3310c5f3851feb90d23823793/src/vs/base/parts/quickinput/browser/quickInput.ts#L626

Is there a reason this happens? Should it be disabled if filtering or sorting did not happen?

**Comment by bpasero** [comment]
I pushed this via:

https://github.com/microsoft/vscode/commit/106046c1ad0069b965390207cb8535df1bc78942#diff-89bb1f5035b9688644c4561e54de8279R625-R628

**Comment by roblourens** [comment]
I can't find the case where this happens

**Comment by bpasero** [comment]
Verification:
* Cmd+P
* type to get some results
* arrow down
* type `:` to enter line mode
* verify the selected item is still the same
