### ISSUE TITLE
Can't sign into Azure through VSC - getaddrinfo ENOTFOUND proxy

### ISSUE THREAD

**Issue by e14mattc** [microsoft/vscode#92932]
Issue Type: <b>Bug</b>

I'm currently unable to sign into my Azure account from Visual Studio Code. On picking Azure Sign In from the context menu, it opens up the Azure portal login page correctly, I pick my login, then it redirects and says;

An error occurred while signing in:
tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy

That's on page with the URL; http://127.0.0.1:52694/?error=tunneling%20socket%20could%20not%20be%20established%2C%20cause%3Dgetaddrinfo%20ENOTFOUND%20proxy

![image](https://user-images.githubusercontent.com/9819307/76970444-c77f4500-6923-11ea-957b-9f94785e658c.png)

There is no proxy currently set in VSC, or at the system level.

I'm not entirely sure what to try next.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.62GB (0.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
soysyntaxchecker|Blo|3.24.2
npm-intellisense|chr|1.3.0
transformer|dak|1.6.0
vscode-eslint|dba|2.1.1
FreeMarker|dco|0.0.9
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
vscode-apimanagement|ms-|0.1.2
vscode-azureappservice|ms-|0.16.3
vscode-azurefunctions|ms-|0.21.0
vscode-logicapps|ms-|0.2.32
csharp|ms-|1.21.14
python|ms-|2020.2.64397
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.10
vsonline|ms-|1.0.1736
azurerm-vscode-tools|msa|0.8.4
vscode-toggleproxy|sat|0.4.6
vscode-open-in-github|sys|1.13.0

</details>

**Comment by RMacfarlane** [comment]
@e14mattc Are you able to sign in without issue using the Azure Account extension? Can you open the output panel and select "Account" from the dropdown and copy-paste the output from there?

**Comment by e14mattc** [comment]
I'm not sure how I'd go about signing in manually without the Azure Account extension.. however when I tried again this morning VSC first updated to 1.43.1, and suddenly the login works, nothing displayed in the output panel. I guess close this out for now & I'll re-open if it starts happening again.
