### ISSUE TITLE
Cannot set zh-cn

### ISSUE THREAD

**Issue by YuxuanWang-CHINA** [microsoft/vscode#92937]
- VSCode Version: 1.43.0
- OS Version:win10

After windows upgrade KB4551762,cannot set zh-cn language

Does this issue occur when all extensions are disabled? Yes

**Comment by L1cardo** [comment]
mac version has the same issue

**Comment by zhangpengcheng2015** [comment]
me too

**Comment by aeschli** [comment]
dup of #92950
