### ISSUE TITLE
SmartSelect doesn't work in html section of Vue SFC

### ISSUE THREAD

**Issue by qgates** [microsoft/vscode#92936]
- VSCode Version: 1.43
- OS Version: Win10 / Linux Mint 19.3

Steps to Reproduce:

1. Create a Vue SFC `.vue` file of the following format:
```vue
<template>
  <div>
    <p>Some Text</p>
  </div>
</template>

<script lang="ts">
  import Vue, { VueConstructor } from 'vue'

  export default Vue.extend({
    props: {},
    data() { return {
    }},

    mounted() {},
    created() {},
    methods: {},

    computed: {},
    watch: {},
    components: {},
  })
</script>

<style>
</style>
```

2. Place cursor anywhere inside the HTML `<template>` section and attempt to use SmartSelect expand/grow feature to select the <p></p> or outer <div></div>

3. Doing so selects the whole file instead of expanding the selection to HTML 

Other notes:
- SmartSelect does work as expected in the `<script>` section.
- Pasting the `<template>` section into a blank file set to language mode HTML, SmartSelect works as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/1350

**Comment by qgates** [comment]
This is not extension related. Running vs code with extensions disabled I see the same issue. The problem relates to the inbuilt smartselect functionality. Please reopen - thanks.

**Comment by octref** [comment]
This functionality can only be implemented by extensions, not by core.

**Comment by qgates** [comment]
I don't understand. Smartselect works in all languages with no extensions installed. It only goofs up in the html section of vue sfc's?

**Comment by octref** [comment]
VS Code includes support for HTML/CSS/JS but not Vue files.

**Comment by qgates** [comment]
A vue file is just a collection of html, script and css. Admittedly, the html is a templating language (with directives, @attributes etc) but does conform to standards for markup. In any case, smartselect fails even when the html is just plain html. If I paste exactly the same into a file with another extension, it works. So this seems to be an issue with code.
