### ISSUE TITLE
Multiple workspaceStorage's created for the same path

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#92945]
- VSCode Version: 1.42
- OS Version: Windows

Steps to Reproduce:

1. No idea.
2. I just stumbled upon it.

Does this issue occur when all extensions are disabled?: Yes

It seems dependent on how do you invoke VS Code. Different commandline arguments lead to different storage paths.
In my case,

```
$ for f in ????*/; do echo "\"$f\" $( date "--reference=$f" +%F ) $( jq -r .folder -- "$f/workspace.json" )"; done | grep cce
"46cc4d47fca9179a9fdd2e73d8d75fe6/" 2020-02-10 file://hosting64.darkdragon.lan/wwwroot/ccenter
"53815217681e3f1670d179648b08b78f/" 2020-02-27 file://hosting64.darkdragon.lan/wwwroot/ccenter
"e8149ae36f6147f42e0e9f4222cd3753/" 2020-03-18 file://hosting64.darkdragon.lan/wwwroot/ccenter
```

…3 WS for the same path. More interesting is that the "folder" is literally the same in all 3. And all 3 were created relatively recently. Which can't be explained by changed hashing function.

Some of the variants I may have used are:
`"C:\Program Files\Microsoft VS Code\Code.exe" --new-window --folder-uri file://HOSTING64.DARKDRAGON.LAN/wwwroot/ccenter` (used by a script that opens the workspace by searching for `.vscode` directory up from current directory.)

`"C:\Program Files\Microsoft VS Code\Code.exe" "\\HOSTING64.DARKDRAGON.LAN\wwwroot\ccenter"` (right-click inside a directory - `Open with Code` in Explorer.)

Somebody did not normalize something before hashing?

**Comment by bpasero** [comment]
@AnrDaemon this is expected, we literally take the path as you give it and perform no normalization, e.g. to preserve the case of providing symbolic links. We used to normalize a long time ago but got negative feedback.

**Comment by AnrDaemon** [comment]
The problem is that, once the new workspace is created for the same path, all commands will be opening the new workspace. Old one will be left stale with no way to recover except manual intervention.
This makes me doubt your judgement. Even if current behavior is "by design", it is neither consistent, nor predictable.
