### ISSUE TITLE
Progress notifications: visually distinguish between title and message

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92948]
Currently the notificatino simply append progress title and message.
I suggest to have some visual distinction to make them more readable.

Use case: debug progress has both title and message, and it would be cool if they are nicely formated. Currently I can not append them to be in the same content since then the status bar message will be too long

fyi @weinand

**Comment by bpasero** [comment]
We currently just show `<title>:<message>` for progress notifications. Maybe we should show the title in bold. 

The reason notifications do not provide richer formatting capabilities is to prevent extensions from spamming with large formatted text. But I think for progress specifically we could make an exception.

//cc @misolori for input

**Comment by misolori** [comment]
We've gotten requests in the past from partners wanting to have a separate title and message like your typical notification:

![image](https://user-images.githubusercontent.com/35271042/76991264-8593d600-6906-11ea-91b4-6db3f340d4f4.png)

I think bolding could help, but I think it wouldn't satisfy the need for partners wanting them on their own line. It's a good in-between step though so I feel indifferent:

![image](https://user-images.githubusercontent.com/35271042/76991472-e3c0b900-6906-11ea-83e4-a66c6ee47103.png)

**Comment by bpasero** [comment]
Yeah to be fair this would make every progress notification larger by at least 1 line if we go with the approach of separating title and message more. I think that takes a bit of the lightweight nature...

**Comment by isidorn** [comment]
Title in bold + message works for me. That does not add a new line which is neat.
If when hidden in the status bar we only show the title.

**Comment by misolori** [comment]
To be clear, I'm not sure whether we should make the titles and description separate lines, I also like how lightweight they currently are.

@isidorn can you post a screenshot of your current notification?

**Comment by isidorn** [comment]
@misolori I don't really have a real life scenario for this yet. I can come up with a fake message though.

![Screenshot 2020-03-18 at 19 17 04](https://user-images.githubusercontent.com/1926584/76993395-11c8ec00-694d-11ea-89ff-d2aca754d4d9.png)

**Comment by bpasero** [comment]
@isidorn the status bar should show both title and message, as you can see from the code:

https://github.com/microsoft/vscode/blob/61d5f2b82f17bf9f99f56405204caab88a7e8747/src/vs/workbench/services/progress/browser/progressService.ts#L125-L130
