### ISSUE TITLE
Notification toast covers terminal prompt when terminal is on the right side of the screen

### ISSUE THREAD

**Issue by faultfactory** [microsoft/vscode#92942]
I use the ros extension with a widescreen setup with the terminal to the far right. 
As i open and close terminal instances, my cursor/prompt gets buried under notification toast stating the terminal process exited with exit code 130. 

I can't get rid of these without moving the mouse or shifting focus to a different pane, hitting escape and then going back to the terminal.

**Comment by bpasero** [comment]
> As i open and close terminal instances, my cursor/prompt gets buried under notification toast stating the terminal process exited with exit code 130.

This sounds like not a very useful notification to show Daniel. Rather something maybe more in place where the terminal was?

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by faultfactory** [comment]
I am using:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Ubuntu 16.04

Extensions;
C/C++ - Microsoft
CMake - twxs
CMake Tools - Microsoft
GitHub Pull Requests - GitHub
GitLens - Eric Amdodio
Markdown All In One - Yu Zhang
Python - Microsoft
Remote - Containers - Microsoft
ROS - Microsoft

This is not necessarily a terminal issue. It's a notification toast issue. The terminal works fine. 

The image below shows the notification I'm referring to. When i have an stale terminal from a task i'll use ctrl-D to close it. If the underlying terminal is full (which happens often when building) the 'active line' with the cursor is at the bottom of the screen and i have to wait till it clears or close the terminal, hit escape and close it again. 


![image](https://user-images.githubusercontent.com/32714474/77462548-a498d900-6dda-11ea-9182-f91ee92e44c8.png)

**Comment by Tyriar** [comment]
There's a setting to suppress this error:

```
"terminal.integrated.showExitAlert": false
```

The reason this notification is shown is because this is often important information. The issue is that some OS'/shells for some reason will give a non-zero exit code when they are closed. I don't know why they do this and this setting was added to work around this problem.

Also if you're using `exit` this may be causing this, you could switch to a keybinding to kill the terminal, eg.

```json
{ "key": "ctrl+shift+x",     "command": "workbench.action.terminal.kill" }
```

**Comment by faultfactory** [comment]
Thanks for the help. Didn't know that was available.
