### ISSUE TITLE
Feature request: Autocomplete for string literal types

### ISSUE THREAD

**Issue by calebegg** [Microsoft/vscode#9294]
- VSCode Version: 1.3.1
- OS Version: Ubuntu 14.04.1

It would be useful if string literal types in TypeScript had autocomplete

For example:

![image](https://cloud.githubusercontent.com/assets/782920/16849908/a54c0af8-49ca-11e6-9979-b7423336b3d1.png)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10089

**Comment by dbaeumer** [comment]
Moving to TS team since they are the code complete brain.
