### ISSUE TITLE
Staging/unstaging individual files/folders in source control view moves focus from commit box to tree

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#92946]
Version: 1.44.0-insider (system setup)
Commit: 708b019bb4e20f07cf89df9f1d943af3d38d7a70
Date: 2020-03-18T06:30:46.175Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a Git repository in VSCode and make some changes
2. Focus on the commit message box in the Source Control view
3. Click on the "+" next to a file
4. Focus is moved to the file tree, which means that typing will now start filtering the tree

This is not the behavior when clicking the "+" to the right of Changes to stage all files. This may initially seem like the desired behavior, however it's very frustrating when you start typing a message, add a file, and keep typing - suddenly you aren't typing in the box you thought you were.

**Comment by Dan503** [comment]
This is an infuriating issue.

It takes a couple seconds to stage a file so I often click the button to stage the file first and start typing the message while I wait, but as I'm typing it finishes staging then removes focus from the messsage box which means is starts trying to filter instead.

**Comment by Dan503** [comment]
It is a regression of this closed issue from earlier:
https://github.com/Microsoft/vscode/issues/8911

**Comment by QtRoS** [comment]
This bug is very annoying, happy that someone have already noticed that too. it there any workaround?

**Comment by Dan503** [comment]
> Is there any workaround?

Not really.

The best option is to wait until all files are staged before writing the message.

If you want to commit _all_ files, the best option is to type out the full message _first_ then press ctrl+enter while all files are **unstaged**. This will commit all unstaged changes. Note that if you haven't modified your settings, you will be prompted before the files are committed.

**Comment by iansan5653** [comment]
Closing because it's a duplicate of #92401. Please go Watch & 👍  that one!
