### ISSUE TITLE
Transparent backgrounds overlap in controls

### ISSUE THREAD

**Issue by videopilot** [microsoft/vscode#92949]
I am making a theme where I want to use a partially transparent background for controls (inputs, buttons, etc). The reason is because I use custom background colors for different projects and I want the input boxes to just be a slightly lighter version of that. The problem is that the controls have child elements that inherit the background-color. In most cases, it looks ok because the child elements are the same size even though the transparency is not the amount that is intended, but the problem is obvious in the Suggest Input Containers at the top of the settings window and extensions sidebar because the child elements are inset from the edges of the control.

Shouldn't just the parent elements have the background unless the child needs to set a different one (such as a button within an input box)?

![image](https://user-images.githubusercontent.com/6528746/76990491-69039800-691e-11ea-8981-ad0c4a8f87fc.png)

![image](https://user-images.githubusercontent.com/6528746/76990376-41143480-691e-11ea-8dd3-581dec936081.png)

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

**Comment by videopilot** [comment]
You can see this if you put the following into your settings:

"workbench.colorCustomizations": {
    "input.background": "#8881",
    "settings.textInputBackground": "#8881",
    "settings.numberInputBackground": "#8881",
    "checkbox.background": "#8881",
    "settings.checkboxBackground": "#8881",
    "button.background": "#8881",
    "dropdown.background": "#8881",
    "settings.dropdownBackground": "#8881",
}

**Comment by roblourens** [comment]
It looks like this was changed for https://github.com/microsoft/vscode/issues/85099, but yeah I think we should just not be setting the same background color on multiple levels.
