### ISSUE TITLE
Quick suggestions only for snippets

### ISSUE THREAD

**Issue by zjopy** [microsoft/vscode#92947]
Currently in a markdown file Quick Suggestions offers auto complete for words already typed in addition to any snippets.

<img width="462" alt="Screenshot 2020-03-18 at 18 05 54" src="https://user-images.githubusercontent.com/33468089/76987568-afb7b900-6943-11ea-8933-9e10e6448a37.png">

This quickly becomes distracting, since the Quick Suggestions popup becomes almost permanent because most of the words you type start with letters of words you already typed at least once. I don't want to turn of Quick Suggestions completely, since I use the snippets, but I do want to turn it off for anything else than snippets.

<img width="470" alt="Screenshot 2020-03-18 at 18 06 15" src="https://user-images.githubusercontent.com/33468089/76987700-e4c40b80-6943-11ea-8bcc-1534b55d95c8.png">

Proposal: Change the valid options for `editor.quickSuggestions` to `on`, `off` or `onlySnippets` from curerntly only `true` / `false`. This would also make it similar to how `editor.tabCompletion` works.

**Comment by IllusionMH** [comment]
There are already controls of what will be shown in suggestions

You can disable words suggestions with (example for Markdown but can be used globally):
```json
"[markdown]": {
    "editor.suggest.showWords": false
}
```

You can also check other detailed controls for suggestions in Settings.

**Comment by zjopy** [comment]
Thanks @IllusionMH that fixed it for me. This issue can be closed.

Though it would have been nice if these settings were a bit more documented, e.g. a mention about `editor.suggest` on [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense).
