### ISSUE TITLE
Cannot display Simplified Chinese

### ISSUE THREAD

**Issue by YouXam** [microsoft/vscode#92940]
- VSCode Version: 1.43.0 (system setup)
- OS Version: Windows 10 Home 1903

The problem didn't happen during the first installation.

After I installed the *Chinese (Simplified) Language Pack for Visual Studio Code* plugin and restarted vscode, vscode is still in English.
 
### What I did

- Press `ctrl + shift + p and choose to configure the display language to zh-cn
- Uninstall and reinstall the plugin
- Delete the .vscode folder in the user directory
- Reinstall vscode

Even after the above operations, vscode is still in English.

Additionally, this problem only appears in Simplified Chinese. The Traditional Chinese plugin works well.

**Comment by iocdacc** [comment]
用之前的历史版本没问题 
暂时只能这样了

**Comment by wangweixuan** [comment]
I unzipped the latest language pack extension (ms-ceintl.vscode-language-pack-zh-hans, version 1.43.8) and found out that `main.i18n.json` is saved in **UTF8 with BOM** encoding and therefore cannot be parsed. The bug need to be addressed quickly and I suggest a recovery version of the extension be published as soon as possible.

1.43.8 版本的语言包扩展中记录了翻译字符串的 JSON 文件使用了带 BOM 的 UTF-8 编码保存，而 JSON.parse() 无法处理 BOM，所以翻译就不能用了。这个错误看来要等新版本的扩展发布才能修复。

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/92950
