### ISSUE TITLE
[themes] seti: django html has no file icon

### ISSUE THREAD

**Issue by aledgriffiths79** [microsoft/vscode#92951]
Hello. I am using the vsc insider environment. When i add a html extension in my template it provides a text logo  and not with the html logo (<>). But strangely when i give the file a title of base.htm i have a html file with the (<>) at the end.

**Comment by aeschli** [comment]
Can you add a screenshot?

**Comment by aledgriffiths79** [comment]
Hello, yes certainly. I have attached it to this email.

Kind Regards

Aled
________________________________

**Comment by aledgriffiths79** [comment]
whereas the main editor of vsc works fine as shown in the picture attached

Kind Regards

Aled
________________________________

**Comment by aeschli** [comment]
Sorry, I can't see any screenshots. 
Not sure if that works with email, but what I always do is to drag and drop it to the comment field in the GitHub web page.

**Comment by aledgriffiths79** [comment]
![Screenshot (443)](https://user-images.githubusercontent.com/38667688/77118954-55932280-6a2d-11ea-9de5-abeb4bd46e5c.png)
![Screenshot (444)](https://user-images.githubusercontent.com/38667688/77118963-5c219a00-6a2d-11ea-8db0-08e4397632c5.png)

**Comment by aledgriffiths79** [comment]
Hi, ive dragged and dropped on github

Aled
________________________________

**Comment by aeschli** [comment]
Ok, thanks, I see. It's because you've assigned html to Django HTML. 
Seti has no icon for Django. We should use the HTML one by default.

**Comment by aledgriffiths79** [comment]
Hello, sorry i have had a look and i dont understand what you mean. As you can gather im a beginner. Can you illustrate in a picture what i need to change? Thank you

**Comment by aeschli** [comment]
There's nothing for you to change, I will have to fix it.
