### ISSUE TITLE
Themes: set classes to the <body> element

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92953]
Maybe there is a technical reason but I find it a bit weird that the theme service changes classes on the `<body>` element, especially when VSCode is running on Web in a specific container.

Do we actually need to do it this way, why can the theme service not set it on the workbench container?

![image](https://user-images.githubusercontent.com/900690/76992153-15f40a00-694b-11ea-93c0-6a84c12b35f4.png)

**Comment by bpasero** [comment]
This applies to file icons as well it seems.

**Comment by aeschli** [comment]
It is on the workbench container..
https://github.com/microsoft/vscode/blob/e38fba58226e85e6d41750c7543660e14f6ce512/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L102

Feel free to change it...

**Comment by bpasero** [comment]
@aeschli it is not so easy, changing it results in this flicker on startup:

![Kapture 2020-03-19 at 8 59 43](https://user-images.githubusercontent.com/900690/77044594-ff3bca80-69bf-11ea-86db-cec7029aa4c6.gif)

I am puzzled what condition could check on `body` for these classes, do you have any clue?
