### ISSUE TITLE
Add Visual Studio's Edit.SelectCurrentWord functionality

### ISSUE THREAD

**Issue by wasker** [microsoft/vscode#92959]
Hi all,

The closest to Visual Studio's Edit.SelectCurrentWord (Ctrl-W or Ctrl-Shift-W, depending on your settings) is VSCode's Ctrl-D, however, it has its own idea of word boundary (not compatible with Ctrl-Left/Ctrl-Right, for example), and multiple presses adds more selections to the editor.

I'd like to have a simple Edit.SelectCurrentWord, which selects the current word and works consistently across programming languages, unlike Ctrl-D.

Thanks.

**Comment by alexdima** [comment]
Duplicate of #15774

The change is available in the Insiders channel.

**Comment by wasker** [comment]
Available for all in 1.44.
