### ISSUE TITLE
Extension is not properly activated if a command is executed via context menu

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode#9295]
- VSCode Version: 1.3.1 + 1.4.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new instance of vscode
2. Execute a command from "editor/title" or "explorer/context" menu. ("Open Preview" on a markdown file)
3. The context menu closes and opens again
4. Click the context menu item again
5. The command is executed

_If you open the context menu and wait for a few seconds before clicking the menu item, the command is executed directly._

**Comment by jrieken** [comment]
> The context menu closes and opens again

Does this mean is closes/opens by itself or do open it, click somewhere else to close it and open it again?

> If you open the context menu and wait for a few seconds before clicking the menu item, the command is executed directly.

Does this mean the menu item clicks itself?

Last, when the menu item is selected do you see the error message about the command being unknown and about a potentially missing activation event?

**Comment by skolmer** [comment]
> Does this mean it closes/opens by itself or do you open it, click somewhere else to close it and open it again?
Indeed, the menu closes and reopens itself when I click the menu item. It seems it only happens if you quickly open the context menu and click the command. 

> Does this mean the menu item clicks itself?
If you open the context menu, wait for a few seconds or milliseconds (seems to depend on system performance) before you click the menu item, the command is executed immediately. The menu doesn't reopen. 

I also experienced that the menu item command is executed if I click in the editor window after the Context menu hast opened by itself. Open Context Menu -> Click an item -> Menu reopens magically -> Click in the editor window -> Menu closes (lost focus) -> Command is executed

**Comment by jrieken** [comment]
@bpasero @joaomoreno is this about the context menu on windows?

**Comment by bpasero** [comment]
I can not reproduce the behaviour shown. I open the menu and quickly click on "Open Preview" but the menu does not reopen.

**Comment by skolmer** [comment]
Do you have a "slow" machine where you can test it. I just realized that I can't reproduce the behavior on my laptop which has much better performance. 
The animation was taken on a intel nuc platform @ 1.9Ghz

**Comment by bpasero** [comment]
@skolmer any chance you could debug this? Add a breakpoint where we open the menu (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/contextview/electron-browser/contextmenuService.ts#L57) and see how is calling it a second time.

**Comment by skolmer** [comment]
@bpasero I will try to provide some debugging information when I find some time. thanks.

**Comment by skolmer** [comment]
I tried a quick debug in the release build with built in chrome developer tools but since focus is removed from the context menu when the debugger steps in, this cannot be reproduced. 
I never debugged vscode from source code so this might take more time. But I'm not sure if it's worth the effort if this cannot be reproduced on other systems.

**Comment by bpasero** [comment]
True, you would need a breakpoint that gets hit the SECOND time the menu opens.

**Comment by skolmer** [comment]
I can not reproduce this after updating to the latest windows insider build. not sure if this is related to windows 10 but feel free to close this issue.

**Comment by jrieken** [comment]
Ok - thanks for getting back to us. Feel free to ping us here if this happens again
