### ISSUE TITLE
Chinese (Simplified) Language Pack 1.43.8 seems to be broken

### ISSUE THREAD

**Issue by dirtypool96** [microsoft/vscode#92950]
Some plugins don't work on VSC 64-bit 
such as: ms-ceintl.vscode-language-pack-zh-hans

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. `npm i --save koa` in a folder
2. cd this folder
3. code .

before i use koa,everything is ok... please help me...

**Comment by dirtypool96** [comment]
I found the reason...
Chinese (Simplified) Language Pack for Visual Studio Code
this plugin updated to 1.43.8 , I rolled it back to 1.43.7 , now it works...
shit update...

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode/issues/92950:
I unzipped the latest language pack extension (ms-ceintl.vscode-language-pack-zh-hans, version 1.43.8) and found out that main.i18n.json is saved in UTF8 with BOM encoding and therefore cannot be parsed. The bug need to be addressed quickly and I suggest a recovery version of the extension be published as soon as possible.

**Comment by janbaltus** [comment]
Please see 1.43.9 LP with fix.

**Comment by dirtypool96** [comment]
Thanks, now it works
