### ISSUE TITLE
Unsaved file editor show up on restart, cannot save the file

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#92962]
- VSCode Version: 1.43.0
- OS Version: Ubuntu 16.04.5

I've got one file I made temporarily named `test.json` in my git repository. I've since closed that file (unsaved) and restarted VS Code. The file then pops up again on restart (blue top border on editor tab). Closing the file and choosing to not save it works, but again, upon re-start, it pops up again. Disabling extensions, restarting, nothing works to remove it. Every time I restart it pops up again in an unsaved state. Trying to save the file gives:

```sh
Failed to save 'test.json': Unable to write file 'vscode-remote://ssh-remote+vm/server/json/test.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/server')
```

I have no idea how to remove this unsaved editor. Not sure if it matters, but the file is empty. The `server` directory already exists and contains other files, so it's obvious that it trying to create that directory will fail.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you update to the 1.43.1 release that just came out?

**Comment by thernstig** [comment]
Yes.

**Comment by bpasero** [comment]
As a workaround you can delete the `Backups` folder in `~/.config/Code`. Be aware though that this deletes any dirty file you had, so maybe make sure to save all first.

**Comment by thernstig** [comment]
@bpasero Deleting `~/.config/Code/Backups` on the remote ssh host did nothing.

**Comment by bpasero** [comment]
@thernstig can you check if there are more code specific folders there, we may be using a different folder for when you use remote.

**Comment by thernstig** [comment]
Here we go:

```sh
~/.config/Code> ls -l
Backups/
blob_storage/
Cache/
CachedData/
CachedExtensions/
GPUCache/
Local Storage/
logs/
User/
webrtc_event_logs/
Cookies
Cookies-journal
languagepacks.json
machineid
Network Persistent State
Preferences
rapid_render.json
storage.json
```

**Comment by bpasero** [comment]
@thernstig sorry, I think I confused myself. Yes, backups should be there on your local machine inside that folder. Does it make any difference if you start explicitly with a different user data directory via `code --user-data-dir <some empty folder>`?

**Comment by thernstig** [comment]
@bpasero Since I am running with the ssh remote extension, the directory I pasted above was from the ssh host (i.e. my remote). Thus I cannot run `code` to start VS Code since I only connect to that ssh host via VS Code remote.

I tried opening another git repo on the remote and then the file did not open open reload, but if I opened the same previous git repo once again it showed up.

**Comment by bpasero** [comment]
@thernstig the backup directory is on your local machine though, try looking there!

**Comment by thernstig** [comment]
Yepp, got it! Found the file in `C:\Users\username\AppData\Roaming\Code\Backups\4d1f82cb36361e6c157417823d349758\untitled` , it contained this line `untitled:server/json/test.json
`.

I removed the file and then it was gone when re-opening VS Code. Thanks for the workaround! 😃

**Comment by bpasero** [comment]
I restored our treatment of backups on shutdown as it used to be: if there are no dirty files opened we simply delete the entire backups directory, which will also get rid of any stale backups should there be any.
