### ISSUE TITLE
Theme Changes to better align with Visual Studio Light and Dark themes

### ISSUE THREAD

**Issue by JoeRobich** [microsoft/vscode#92965]
I recently experimented with adding a semantic token provider to the C# extension (https://github.com/OmniSharp/omnisharp-vscode/pull/3667). This made apparent that the VS Code Light+ and Dark+ themes need to be updated so that the out of the box experience with semantic classification closely aligns with the default Visual Studio Light and Dark themes.

These are the changes I made to get an experience that was consistent with the Visual Studio default themes:
```javascript
 "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
            "textMateRules": [
                {
                    "scope": "entity.name.namespace",
                    "settings": {
                        "foreground": "#D4D4D4"
                    }
                },
                {
                    "scope": "entity.name.variable.field",
                    "settings": {
                        "foreground": "#D4D4D4"
                    }
                },
                {
                    "scope": "variable.other.property",
                    "settings": {
                        "foreground": "#D4D4D4"
                    }
                },
                {
                    "scope": "variable.other.constant",
                    "settings": {
                        "foreground": "#D4D4D4",
                    }
                },
                {
                    "scope": "variable.other.enummember",
                    "settings": {
                        "foreground": "#D4D4D4"
                    }
                },
                {
                    "scope": "entity.name.type.interface",
                    "settings": {
                        "foreground": "#b8d7a3"
                    }
                },
                {
                    "scope": "entity.name.type.enum",
                    "settings": {
                        "foreground": "#b8d7a3"
                    }
                },
                {
                    "scope": "entity.name.type.parameter",
                    "settings": {
                        "foreground": "#b8d7a3"
                    }
                },
                {
                    "scope": "storage.type.struct",
                    "settings": {
                        "foreground": "#86C691",
                    }
                },
                {
                    "scope": "entity.name.function.extension",
                    "settings": {
                        "foreground": "#DCDCAA",
                    }
                }
            ]
        },
        "[Default Light+]": {
            "textMateRules": [
                {
                    "scope": "entity.name.namespace",
                    "settings": {
                        "foreground": "#222222"
                    }
                },
                {
                    "scope": "entity.name.variable.field",
                    "settings": {
                        "foreground": "#222222"
                    }
                },
                {
                    "scope": "variable.other.property",
                    "settings": {
                        "foreground": "#222222"
                    }
                },
                {
                    "scope": "variable.other.constant",
                    "settings": {
                        "foreground": "#222222",
                    }
                },
                {
                    "scope": "variable.other.enummember",
                    "settings": {
                        "foreground": "#222222"
                    }
                },
                {
                    "scope": "entity.name.type.interface",
                    "settings": {
                        "foreground": "#267f99"
                    }
                },
                {
                    "scope": "entity.name.type.enum",
                    "settings": {
                        "foreground": "#267f99"
                    }
                },
                {
                    "scope": "entity.name.type.parameter",
                    "settings": {
                        "foreground": "#267f99"
                    }
                },
                {
                    "scope": "storage.type.struct",
                    "settings": {
                        "foreground": "#267f99",
                    }
                },
                {
                    "scope": "entity.name.function.extension",
                    "settings": {
                        "foreground": "#795E26",
                    }
                }
            ]
        }
    },
```

With Textmate Classification:
![image](https://user-images.githubusercontent.com/611219/76692801-81bb3780-6618-11ea-8f64-db9304ae119f.png)

With Semantic Classification:
![image](https://user-images.githubusercontent.com/611219/76692772-2c7f2600-6618-11ea-981e-c0cb13f1d770.png)

With Semantic Classification and Visual Studio 2019 theme tweaks:
![image](https://user-images.githubusercontent.com/611219/76692760-ecb83e80-6617-11ea-8c65-bf845e5d1eee.png)

**Comment by JoeRobich** [comment]
For reference
VisualStudio 2019 Windows:
![image](https://user-images.githubusercontent.com/611219/77004549-7881e180-691c-11ea-92fd-81a2170a0de1.png)

VisualStudio for Mac (8.5 preview):
![image](https://user-images.githubusercontent.com/611219/77004290-1628e100-691c-11ea-8aad-f0136daf698c.png)

**Comment by aeschli** [comment]
I added the rules for `"entity.name.function.extension"`. That's an easy one.

The other suggested changes are more controversial. Changes in out default themes have always led to many negative reactions, to the extend that we even had to revert them.
Being 1:1 on par with the original VS is not our main objective. It's very easy to add new themes and make the available in the marketplace and there are infact themes mimicking the VS 2019 theme ans so on.
That said, I'd like to bring in a different color for const variables to take advantage of the semantic highlighting capabilities. I'll play around with your suggestion and get back to you.

**Comment by aeschli** [comment]
`entity.name.function.extension"` as already covered by the `entity.name.function.` rule, e.g. for drk_ but the same for light+, and hc:
https://github.com/microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_plus.json#L9
So no change needed for that.

**Comment by JoeRobich** [comment]
> Changes in out default themes have always led to many negative reactions, to the extend that we even had to revert them.

Thanks for considering these suggestions. As someone who has changed the VS theme for C# & VB I totally understand.

> That said, I'd like to bring in a different color for const variables to take advantage of the semantic highlighting capabilities

When adding the "enhanced" 2019 theme for C# and VB I tried to make a differentiation between local (blue color) and member (text color) identifiers. Const was tricky for us because we didn't have the TokenModifiers concept. Hopefully when VS implements a similar classification scheme we won't have a single const color anymore.

**Comment by aeschli** [comment]
I change our default to use the default color for const. 

For now I want to leave it at that and see what the reactions are.

**Comment by aeschli** [comment]
Closing as no further changes planed.
