### ISSUE TITLE
VS Code Update Fails and Deletes the Application

### ISSUE THREAD

**Issue by Stoicus** [microsoft/vscode#92967]
Issue Type: <b>Bug</b>

VS Code is open.
Notification appears on Settings icon - update available.
Message box appears in lower right with button - Update Code.
Press button.
Confirm update.
Update runs.
Error message appears - cannot rename Code.exe.  Update fails.
Code icon is lost from Taskbar and Code application is not available.
Uninstall Code.
Reinstall Code.
Report bug.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.14
mssql|ms-|1.9.0
python|ms-|2020.2.64397
powershell|ms-|2020.3.0
vs-keybindings|ms-|0.2.0

</details>

**Comment by tmontney** [comment]
Similar thing happened to me just now, can't say which version but it was recent (last build or two). However, I cannot reinstall, it seems like the installer is broken.

**Comment by joaomoreno** [comment]
Can you fully uninstall and reinstall VS Code?

**Comment by tmontney** [comment]
I came back to it now and it reinstalled. Perhaps a reboot solved the issue (something might have been locking the file/directory).
