### ISSUE TITLE
Fails to open SD temp file when doing SD CHANGE if VS Code is already open

### ISSUE THREAD

**Issue by Piscean** [Microsoft/vscode#9296]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Set VS Code settings.json to include "window.openFilesInNewWindow": false
2. In your Source Depot setenv.cmd, set VS Code as your default editor with: set SDEDITOR="c:\Program Files\Microsoft VS Code\code.exe"
3. Have VS Code open with a file loaded.  Doesn't matter what, just needs to already be open
4.  From your enlistment, make a code change and run SD CHANGE
--> That should bring up a .tmp file to allow you to enter a description.  Instead, you get an error "Unable to open 't18832t1.tmp': A system error occured (ENOENT: no such file or directory, stat 'c:\temp\system\csrcrs1_refresh\t18832t1.tmp')."

If VS Code isn't already running prior to step 4, this works correctly.  Or, if you omit step 1, it works correctly.

**Comment by bpasero** [comment]
@Piscean can you make sure when this error happens that the file exists on disk?

**Comment by Piscean** [comment]
If VS Code is running when I attempt SD CHANGE, the .tmp file is not created.  If VS Code isn't running when I SD CHANGE, then the .tmp file is created.

**Comment by bpasero** [comment]
VS Code needs the file to be on disk, otherwise it cannot open it. This is how it works in Git too.

**Comment by Piscean** [comment]
I understand that the file needs to be there before it can be opened.  However, since VS Code appears to be the reason the file isn't there in the first place, there is still an issue here.
