### ISSUE TITLE
Missing padding on extension count?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#92968]
The number badge is right on the border, it seems like there should be a couple pixels of margin?

![image](https://user-images.githubusercontent.com/323878/77012159-acfc9a00-692a-11ea-8a82-e005436b8640.png)

![image](https://user-images.githubusercontent.com/323878/77012177-b6860200-692a-11ea-8621-5321f156866d.png)

**Comment by sandy081** [comment]
Fixed by 3cde29e3d938d239af973668212081188e852108
