### ISSUE TITLE
Running Save Participants: Formatting C++ Taking Multiple Minutes

### ISSUE THREAD

**Issue by JonathonMalcolm** [microsoft/vscode#92971]
Issue Type: <b>Performance Issue</b>

With my current setup, periodically when I have a .cpp file it will try formatting the file for mulitple minutes. The only way to fix is to restart VS Code and then it formats and saves just fine.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (16 x 2799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.65GB (6.20GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   128	 15944	code main
    0	    32	 15948	   zygote
    1	   160	 15970	   gpu-process
    1	   401	 15989	   window (● patternGen.cpp - procam-depth-extraction (Workspace) - Visual Studio Code)
    6	   176	 16244	     extensionHost
    0	   417	 16298	       /home/jonathon_malcolm/.vscode/extensions/ms-vscode.cpptools-0.27.0-insiders3/bin/cpptools
    0	   176	 18664	         /home/jonathon_malcolm/.vscode/extensions/ms-vscode.cpptools-0.27.0-insiders3/bin/cpptools-srv 16298 15
    0	   240	 19018	         /home/jonathon_malcolm/.vscode/extensions/ms-vscode.cpptools-0.27.0-insiders3/bin/cpptools-srv 16298 16
    0	   208	 19597	         /home/jonathon_malcolm/.vscode/extensions/ms-vscode.cpptools-0.27.0-insiders3/bin/cpptools-srv 16298 19
    0	    48	 16637	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=16244
    0	     0	 20755	       [sh] <defunct>
    0	     0	 20829	       [sh] <defunct>
    0	     0	 20831	       [sh] <defunct>
    0	     0	 20837	       [sh] <defunct>
    0	     0	 20915	       [sh] <defunct>
    0	     0	 21070	       [sh] <defunct>
    0	     0	 21084	       [sh] <defunct>
    0	    64	 16269	     watcherService
    0	    48	 16284	     searchService
    0	   112	 16377	   shared-process
    0	     0	 21119	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 21120	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    96	 21089	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● patternGen.cpp - procam-depth-extraction (Workspace) - Visual Studio Code)
|    Folder (procam-depth-extraction): 589 files
|      File types: png(207) make(60) o(41) cmake(36) cpp(34) txt(18)
|                  includecache(15) internal(15) jpg(12) hpp(9)
|      Conf files: cmake(36) settings.json(1) makefile(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|0.6.0
beautify|Hoo|1.5.0
cmake-tools-helper|mad|0.2.1
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0-insiders3
swdc-vscode|sof|2.1.22
rewrap|stk|1.9.1
vscode-status-bar-format-toggle|tom|2.0.0
cmake|twx|0.0.17

</details>

**Comment by aeschli** [comment]
Can you share the cpp file?
