### ISSUE TITLE
Internal pdf viewer turns to grey (developer tools too)

### ISSUE THREAD

**Issue by afranko** [microsoft/vscode#92970]
- VSCode Version: 1.43
- OS Version: Arch Linux x64 (5.5.9-arch1-2)

I use the Latex-workshop extension to create documents in VSCode, but something is wrong with the internal pdf viewer (tab). It start to display the pdf, it loads it, but suddenly the whole display (the viewer) turns to grey. If I close the tab and try it again the same happens as before.

![scre2](https://user-images.githubusercontent.com/23009527/77013568-31b9d900-6968-11ea-989d-30df1c3b2d00.png)
![scre1](https://user-images.githubusercontent.com/23009527/77013557-2797da80-6968-11ea-912b-192797e95be1.png)

I tired to check the developer tools to watch error log, but it doesn't contain any message, but after being opened for 4-5 sec it also turns to black. If I close the tab and try it again the same happens as before...

The only log I have is Latex-Workshop's one:

[22:21:17] Serving PDF file at http://localhost:43177/viewer.html?file=pdf..JTJGaG9tZSUyRmFmcmFua28lMkZ3b3Jrc3BhY2UlMkZpbmZva29tamVneXpldCUyRnNvdXJjZXMlMkZtYWluLnBkZg
[22:21:17] The encoded path is /home/afranko/workspace/infyzet/sources/main.pdf
[22:21:17] Open PDF tab for /home/afranko/workspace/infyzet/sources/main.pdf
[22:21:17] Handle data type: open
[22:21:17] Preview PDF file: /home/afranko/workspace/infyzet/sources/main.pdf
[22:21:17] Root file remains unchanged from: /home/afranko/workspace/infyzet/sources/main.tex.
[22:21:17] Handle data type: request_params
[22:21:20] Handle data type: close

I opened the issue here and in Latex-Workshop repo, because it also affect developer tools.

Does this issue occur when all extensions are disabled?: Yes, both of them.

**Comment by mjbvz** [comment]
We don't ship a pdf viewer so this must be coming from one of your extensions. Please file this agains them

**Comment by tamuratak** [comment]
Hi, I am one of the developers of the extension. He says the Developers Tool of VS Code also turns to black. So, this issue might be related to VS Code itself.

> but it doesn't contain any message, but after being opened for 4-5 sec it also turns to black.

**Comment by afranko** [comment]
@mjbvz 

This happens if a click "Toggle Developer Tools":

![tgtools1](https://user-images.githubusercontent.com/23009527/77056428-4b8c0800-69ca-11ea-8be7-c0f9da42ca26.png)

![tgtools2](https://user-images.githubusercontent.com/23009527/77056431-4cbd3500-69ca-11ea-8027-0b5ca17ed439.png)

I didn't do anything between shooting the two pictures. If you still says it's an extension related issue, than I move this conversation to Latex-Workshop repo.

**Comment by tamuratak** [comment]
@afranko If you use Arch Linux on VM in the same way as #91895, it would be the cause.

**Comment by afranko** [comment]
@tamuratak I use VirtualBox in this case, but I don't think it's the same problem here. I disabled 3D acceleration (I tried to enable, but the GUI collapsed the same way as the aforementioned issue), and I also tried all graphics controller in VBox -> Nothing changes...

**Comment by mjbvz** [comment]
Thanks for clarifying. This sounds like an electron (chromium) issue with your gpu under virtual box.

@deepak1556 Is there anything we should do to follow up on gpu related issues like this?

**Comment by invisiblearts** [comment]
@mjbvz Unfortunately, I also have this issue on my physical machine (amdgpu driver)

The open source version does not have this issue.

**Comment by deepak1556** [comment]
> If I don't maximize the vscode window and hit preview, it is possible that the preview displays properly. Maximizing it then may still work, but doing some more resizing will certainly break it.

@invisiblearts does the issue happen even with `--disable-gpu` flag ?

> Is there anything we should do to follow up on gpu related issues like this?

@mjbvz nothing specific, most of the issues are either an issue with chromium or vm, they can report it to upstream with a minimal repro.

**Comment by invisiblearts** [comment]
@deepak1556 no, it doesn't.

I tend to believe that this is related to #91824. The issue-free community version archlinux provides is compiled with Electron 7.11.4, which has merged the patch.
