### ISSUE TITLE
TypeScript Version Selection Only Works on Second Try

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#92975]
Issue Type: <b>Bug</b>

1. Select TypeScript version from bottom-right area of the VS Code tray.
2. Select VS Code's version or the workspace version (whichever isn't currently active).
3. Observe that nothing has changed.
4. Repeat the first two steps again.
5. Observe that this time it's worked.

![doubleSelectVersion3](https://user-images.githubusercontent.com/972891/77016078-e5ed3c80-6933-11ea-9bfb-cf66d8f4320e.gif)

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Can you please test this in VS Code insiders too. I've been reworking how the status bar button works (hopefully making it more helpful)

**Comment by DanielRosenwasser** [comment]
Thanks, seems fixed!
