### ISSUE TITLE
Ubuntu 18.04 freeze after each reboot

### ISSUE THREAD

**Issue by Adam123-png** [microsoft/vscode#92976]
Hello all,

I´m running Ubuntu 18.04. Since last week I´ve been struggling with rapid freezing - it appears after approximatelly 5 minutes. The only way is to reboot the system. I haven´t performed any update.

The details of Ubuntu. No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 18.04.3 LTS Release: 18.04 Codename: bionic

When typing "uname -r" the result is: 4.4.0-18362-Microsof. linux-generic-hwe-18.04 is already the newest version (5.3.0.42.99). xserver-xorg-hwe-18.04 is already the newest version (1:7.7+19ubuntu8~18.04.3).

I´ve tried many corrections I googled but still without any success. I´m new to Ubuntu. Please, could you help me? Where is the problem?

Thanks a lot Regards Adam

**Comment by aeschli** [comment]
You are talking about Ubuntu in WSL. Is WSL freezing? Is it related to VSCode or not?
If its a WSL issue and not VSCode related, you need to file the issue against https://github.com/microsoft/WSL

**Comment by Adam123-png** [comment]
the problem is related to to WSL thus I file the issue in https://github.com/microsoft/WSL. Closing the case. Thanks.
