### ISSUE TITLE
Sync requests to re-login every 2 minutes.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode#92972]
- VSCode Version:
```
1.44.0-insider
708b019bb4e20f07cf89df9f1d943af3d38d7a70
x64
```
- OS Version: `Linux sarahkitty 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux`

Steps to Reproduce:
1. See notification, "Sign in to sync"
2. Sign in up to the page where it says, "You are all set"
3. The notification goes away.
4. Wait <3 minutes
5. Notification is back, asking to sign in

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@sarahkittyy Can you open the output panel and choose "Account" from the dropdown, and copy-paste the output from there?

**Comment by sarahkittyy** [comment]
@RMacfarlane 
```
[Info  - 00:34:59.807] Logging in...
[Info  - 00:35:03.603] Exchanging login code for token
[Info  - 00:35:03.991] Exchanging login code for token success
[Info  - 00:35:03.993] Login successful
[Info  - 00:35:04.2] Token available from cache, expires in 3598990 milliseconds
[Error  - 00:35:04.44] Setting token failed: Error: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login
```

**Comment by RMacfarlane** [comment]
Thanks! Writing the token to the keychain is failing, so it seems like there's an issue with the way `gnome-keyring` is configured on your system. I'd like to pop up a notification in this case pointing to documentation on how to fix this. Can you see if adding `.local/share/keyrings/` to your home directory fixes this, or deleting `.local/share/keyrings/default` if you have such a directory?

**Comment by sarahkittyy** [comment]
@RMacfarlane `~/.local/share/keyrings/` exists, but is empty

**Comment by sarahkittyy** [comment]
I fixed it! Steps I took:

1. In ~/.xinitrc:
```
# not sure if this is necessary
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK 

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
```
2. Install and run `seahorse`
3. File => New Keyring => Name it "login"

After that it works perfectly :)

**Comment by autoferrit** [comment]
This doesn't seem to work if you are using KDE. The error I get is
```
Writing login information to the keychain failed with error 'The name org.freedesktop.secrets was not provided by any .service files'.
```
I found a solution which can be seen here under the "solution" header: 
https://rtfm.co.ua/en/linux-the-nextcloud-client-qtkeychain-and-the-the-name-org-freedesktop-secrets-was-not-provided-by-any-service-files-error/

As a summary, the solution (I am on arch) was to do install gnome keyring and qtkeychain
```bash
$ yay -S qtkeychain gnome-keyring
```
Verify it is present with
```bash
$ ls -l /usr/share/dbus-1/services/ | grep secret
-rw-r--r-- 1 root root 122 Oct 29 11:38 org.freedesktop.secrets.service

$ cat /usr/share/dbus-1/services/org.freedesktop.secrets.service
[D-BUS Service]
Name=org.freedesktop.secrets
Exec=/usr/bin/gnome-keyring-daemon --start --foreground --components=secrets
```
At this point I was able to log in. When I did, I did get a prompt that an application was trying to save something to a keyring and prompted for a password for a new default keyring. Once I did that everything seems to have worked fine.

**Comment by mort3za** [comment]
In kubuntu 20, installing `gnome-keyring` was enough for me.

`sudo apt install gnome-keyring`
