### ISSUE TITLE
Changing a parent folder's name causes loss of unsaved file changes.

### ISSUE THREAD

**Issue by treestryder** [Microsoft/vscode#9298]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Edit a file in a sub-folder, but do not save it.
2. Rename the sub-folder.

The file will still be marked as dirty, however it will no longer appear in the OPEN EDITORS section and all changes will be lost.

Possibly related to issue [#1350](https://github.com/Microsoft/vscode/issues/1350).

**Comment by bpasero** [comment]
Yup, duplicate. For me the dirty file is still in "Opened Editors", but showing the wrong (old) parent.
