### ISSUE TITLE
Copy-pasting in terminal on Linux with editor.selectionClipboard=OFF

### ISSUE THREAD

**Issue by DraTeots** [microsoft/vscode#92989]
This is continuation of #85694

- VSCode Version: 1.43.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. switch off editor.selectionClipboard
2. Column selection mode now works in code
3. But in terminal middle button doesn't do copy/paste (nor it does column selection which would not make sense in terminal anyway). The only way copy-pasting in terminal now ctrl+shift+c - ctrl+shift+v which is extreamly inconvenient

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by Tyriar** [comment]
@DraTeots you can make right click copy and paste in the terminal using `terminal.integrated.rightClickBehavior`. Can you clarify what you're asking for exactly? Do you expect when `editor.selectionClipboard` is false on Linux that middle click in the terminal will do column selection (ie. what alt+left click does)?

**Comment by DraTeots** [comment]
Ideal configuration that I would expect:

1. Editor middle button - does column select
2. Terminal some mouse button - does copy/paste
3. Terminal some mouse+key button - context menu

### Default
```
- editor.selectionClipboard=ON 
- terminal.integrated.rightClickBehavior=default
```
1. Editor middle button - does column select  ** FALSE **
2. Terminal some mouse button - does copy/paste  ** true **
3. Terminal some mouse+key button - context menu **true**

### #85694 solution
```
- editor.selectionClipboard=OFF 
- terminal.integrated.rightClickBehavior=default
```
1. Editor middle button - does column select  **true**
2. Terminal some mouse button - does copy/paste  **FALSE**
3. Terminal some mouse+key button - context menu **true**

### @Tyriar solution 
```
- editor.selectionClipboard=OFF 
- terminal.integrated.rightClickBehavior=copyPaste
```
1. Editor middle button - does column select  **true**
2. Terminal some mouse button - does copy/paste  **true**
3. Terminal some mouse+key button - context menu **FALSE**

**Why option 3 important?** - First is ability to clear the terminal. It doesn't have a key binding by default. Splitting the terminal is convenient too. @Tyriar the last solution is probably the most convenient. At least I can have a column select and type in F1+term+clear to clear the terminal. Still I wouldn't know there is a possibility to split a terminal if not that context menu - it is convenient.

**Comment by Tyriar** [comment]
> Ideal configuration that I would expect:
>
> 1. Editor middle button - does column select
> 2. Terminal some mouse button - does copy/paste
> 3. Terminal some mouse/+key button - context menu

What if shift+right click when `"terminal.integrated.rightClickBehavior": "copyPaste"` triggered the context menu?

**Comment by DraTeots** [comment]
I tried it the first thing! No, unfortunately it continues to copy/paste

**Comment by connor4312** [comment]
The fix doesn't work on Linux for me. I saw the context menu flash up briefly once but in general shift+right click wasn't working: https://memes.peet.io/img/20-04-f51eb315-20d5-4a67-a69b-80dd7e089f80.webm

```
Version: 1.45.0-insider
Commit: 4bd206856db30c27d38aa0f1fbe74bac6156edc7
Date: 2020-04-29T05:37:52.173Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic
```

**Comment by Tyriar** [comment]
@sbatten this reminds me of https://github.com/microsoft/vscode/issues/79476, could this be due to native title bar?

**Comment by Tyriar** [comment]
This is fixed according to @sbatten and the issue @connor4312 hit is #79476
