### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by vinnycrm** [microsoft/vscode#92985]
Issue Type: <b>Bug</b>

URL: https://twitter.com/intent/tweet?hashtags=HappyCoding&ref_src=twsrc%5Etfw&related=twitterapi,twitter&text=Nice%20progress%20keep%20it%20up,%20Keep%20up%20in%20market&tw_p=tweetbutton&via=code

Message: 403 Forbidden: The server understood the request, but is refusing to fulfill it.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
angular2-snippets|dan|1.0.21
prettier-vscode|esb|3.20.0
nodejs-module-snippet|gun|0.0.2
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1

</details>

**Comment by aeschli** [comment]
I don't see any problem with your link: I tried it and all worked: https://twitter.com/maeschli/status/1241723795758551043

**Comment by vinnycrm** [comment]
Okey nice
