### ISSUE TITLE
Predictive typing incorrectly performs selection when dot character is typed

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#92983]
Issue Type: <b>Bug</b>

When I start typing, "vue" the following predictive typing popup is display.

![bug](https://user-images.githubusercontent.com/439226/77030156-2e2c4f00-6974-11ea-9b43-811258e3e29f.png)

The problem is when I type ".", vscode incorrectly replaces the text "vue" with "VTTCue." which is not what I expect.

What I expect is, "__vue.__"

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:40:52.685Z)
OS version: Linux x64 5.5.7-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4051)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.30GB (1.35GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.1.8
vscode-base64|ada|0.1.0
Bookmarks|ale|11.0.0
ng-template|Ang|0.900.18
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
shell-format|fox|7.0.1
markdown-preview-bitbucket|hbr|1.0.0
vscode-peacock|joh|3.6.0
solidity|Jua|0.0.70
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.0.0
python|ms-|2020.3.64983-dev
cpptools|ms-|0.27.0-insiders2
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
angular2-inline|nat|0.0.17
vscode-yaml|red|0.7.2
markdown-preview-enhanced|shd|0.5.2
language-stylus|sys|1.11.0
sort-lines|Tyr|1.9.0
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.4

(5 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Adding @mjbvz for auto accept characters and for why `vue` isn't suggested 🤷‍♂

**Comment by jrieken** [comment]
@rajinder-yadav there is the `editor.acceptSuggestionOnCommitCharacter`-setting which control if certain character automatically accept a completion or not

**Comment by rajinder-yadav** [comment]
I rather not add special conditions.
