### ISSUE TITLE
保存代码右下角一直提示信息

### ISSUE THREAD

**Issue by BobsLi** [microsoft/vscode#92988]
Issue Type: <b>Bug</b>

vue-cli3，在组件内修改保存代码时，右下角一直提示信息，“正在保存“CommandChart.vue”: 正在从“'Vetur', 'ESLint'”获取代码操作([配置](命令: workbench.action.openSettings?%5B%22editor.codeActionsOnSave%22%5D))。”，从而导致所有扩展插件都不能用，有时候重启打开有用，有时候这样操作也无效

Google translate:
vue-cli3, when modifying the save code in the component, the message in the lower right corner keeps prompting, "Saving" CommandChart.vue ": getting code operations from" 'Vetur', 'ESLint' "([Configuration] (Command: workbench. action.openSettings?% 5B% 22editor.codeActionsOnSave% 22% 5D)). ", which causes all extensions to be unavailable, sometimes restarting and opening is useful, and sometimes this operation is also invalid.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vscode-element-helper|Ele|0.5.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.43.9
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|10.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by PoonKinWang** [comment]
You might use English.

**Comment by janbaltus** [comment]
Please test using  1.43.11 LP version.
Should be caused by overtranslated  command: https://github.com/microsoft/vscode-loc/commit/3b7dc489ad66b9667dea981622c02efb2666615e#diff-a1879ac213322ca36c7ba7f9d47a6ba5
