### ISSUE TITLE
Incorrect shared socket when debugging extension with custom data directories

### ISSUE THREAD

**Issue by arnohovhannisyan** [microsoft/vscode#92980]
I am trying to debug my [VSCode extension][1], but I need to use separate data paths because I don't want to mess up my local settings. After setting the data paths in the arguments for the extension host launcher, the extension marketplace becomes inaccessible to the extension host instance. Weirdly, this isn't an issue with portable versions.

- VSCode Version: `1.43.0`
- OS Version: `Linux 5.5.8-1-MANJARO`

> Note: I am currently using VSCodium, but I can confirm this also happens with the OSS and Insiders versions as well.

Steps to Reproduce:

1. Clone https://github.com/arnohovhannisyan/vscode-incorrect-socket
2. Run `start.sh` or `start.bat`
3. Start debugging with `F5`
4. Go to the `Extensions` tab to find the error
5. Check the console for the error

Screenshots:

![image](https://user-images.githubusercontent.com/25834068/77022986-353d6800-6948-11ea-82ef-442e81d9687b.png)

![image](https://user-images.githubusercontent.com/25834068/77023050-73d32280-6948-11ea-842b-9fd570549a3b.png)

Does this issue occur when all extensions are disabled?: Yes

[1]: https://github.com/arnohovhannisyan/vscode-syncify

**Comment by sandy081** [comment]
I have no idea how these arguments are executed when running extensions.

**Comment by bpasero** [comment]
You cannot use a different data dir and expect everything to work, I am sure there are more issues. Please remove those parameters from the launch configuration and it should be fine.
