### ISSUE TITLE
Cannot save/build Quasar App- Message Getting code actions from Vetur  | ESLINT.

### ISSUE THREAD

**Issue by RezaSeedin** [microsoft/vscode#92981]
- VSCode Version: 1.43.1
- OS Version: Windows  10 | 10.0.18363 Build 18363

Steps to Reproduce:

1. Running a Quasar app  CLI
2. When trying to save I get this message and will not build unless I cancel the message.
3. If I restart the app it goes  away but comes back after a few saves
4. When I cancel the message build continues

Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/18523110/77022928-f3133580-69de-11ea-9ec2-1f2a79907f33.png)

![image](https://user-images.githubusercontent.com/18523110/77023202-c0b60800-69df-11ea-9298-b3da3871ddfc.png)

**Comment by octref** [comment]
Please try disabling either extension and see if this issue persists and report to the other extension.
