### ISSUE TITLE
Debug Restart Button Not Working

### ISSUE THREAD

**Issue by shab15** [microsoft/vscode#92992]
Issue Type: <b>Bug</b>

The debug restart button not working sometimes it stop te process while clicking on restart button.

Steps to reproduce.
1. Start a nodejs debug process
2.  Try restarting from the ui restart button(Do not restart with keyboard shortcut)

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) 5350 APU with Radeon(tm) R3      (4 x 2046)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.44GB (3.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
vscode-eclipse-keybindings|alp|0.10.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
tslint|eg2|1.0.44
prettier-vscode|esb|3.20.0
gc-excelviewer|Gra|2.1.34
beautify|Hoo|1.5.0
mssql|ms-|1.9.0
python|ms-|2020.2.64397
cpptools|ms-|0.26.3
debugger-for-chrome|msj|4.12.6
java|red|0.58.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.1
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/92956
Let's continue the discussion there. It would be great if you provide exact reproducable steps

**Comment by shab15** [comment]
Steps to reproduce...
1. Open any Nodejs sample project in vs code.
2. Start the debug process (using the F5 button)
3. The server will get started successfully.
4. Restart server using Debug toolbar (Toolbar Image Attached)
5. Instead of restarting the server stops.
6. Again we have to manually start debugging using the F5 button.
