### ISSUE TITLE
Feature request: Toggle hide/show gitignore files

### ISSUE THREAD

**Issue by ElecTreeFrying** [microsoft/vscode#92999]
**VS Code: v1.43.0**

Feature request to toggle hide/show .gitignore files

Please add a feature just like this. (see .gif below)

Extensions hiding .gitignore files in explorer are available in marketplace. But most of them are not working well in some cases.

Atom have this built in feature to toggle .gitignore files by pressing `i` on treeview focus.

**Expected:** A VS Code built in command feature to toggle hide/show .gitignore files in Explorer .

**Feature request:**

![toggle gitignore](https://user-images.githubusercontent.com/19801459/77057200-929bec80-6a0e-11ea-8901-f7923bd59282.gif)

**Comment by isidorn** [comment]
An extension can solve this by contributing a command which manipulates the `files.exclude`  setting.
We will not have this command build in since the vscode core is not aware of git.
