### ISSUE TITLE
Rename "Turn on Sync..." to "Turn on Preferences Sync..."

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#92990]
`Turn on Sync...` action to turn on syncing preferences is bit not clear and does not say what it is syncing. User will come to know only after executing that action. Instead rename it `Turn on Preferences Sync...` so that user already knows what this action is about.

**Comment by GustavoASC** [comment]
I'll help you guys making a PR on this :smile:

**Comment by GustavoASC** [comment]
@sandy081 Some messages and labels have already been translated to different languages.

E.g.: the key "_turn on sync_" for nls.localize (found in userDataSync.ts) is "Ativar sincronização" in PT-BR according to [this file](https://github.com/microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-pt-BR/translations/main.i18n.json). Should we keep the same old key "_turn on sync_" or rename it and update all the language packs too?

**Comment by sandy081** [comment]
Do not update language packs. There is a team which will take care of this after we do the change here.

**Comment by GustavoASC** [comment]
@sandy081 Sorry if it's written somewhere but I searched and didn't find it. The option _Turn on sync..._ doesn't appear on Code OSS Dev on _File -> Preferences_ menu.

I tryed modifying _product.json_ inside _vscode_ root folder, adding:

	"configurationSync.store": {
		"url": "http://localhost:3000",
		"authenticationProviderId": "MSA"
	}

But even doing this the menu doesn't appear.
Is there something else to do so this menu appears on Code OSS Dev?

Debugging method registerTurnOnSyncAction() of  userDataSync.ts, I believe CONTEXT_SYNC_STATE keeps _Uninitialized_...

**Comment by sandy081** [comment]
Yup. Configuration store url is not public and hence I cannot provide it here. Sorry for that. Given this it is hard for users to submit PRs here. I will look into this.

**Comment by sandy081** [comment]
I would like to still have `Turn on` terminology as it is not one time sync, in fact it is turning on syncing preferences. Hence would like to call `Turn on Preferences Sync...`

**Comment by sandy081** [comment]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/10746682/77576256-3258ef00-6ed5-11ea-8fb5-2a8f210331e2.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/10746682/77576291-443a9200-6ed5-11ea-8cc3-258190e40b0d.png">

<img width="295" alt="image" src="https://user-images.githubusercontent.com/10746682/77576327-5288ae00-6ed5-11ea-9b97-585c22f2d82c.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/10746682/77576342-5a485280-6ed5-11ea-919e-1d77703a9dc0.png">
