### ISSUE TITLE
Duplicate "Add folder"

### ISSUE THREAD

**Issue by ryutoyasugi** [microsoft/vscode#92991]
- VSCode Version: 1.43.1
- OS Version: macOS Catalina 10.15.3

Steps to Reproduce:

1. Remove all folder from workspace
<img src="https://user-images.githubusercontent.com/12582702/77046649-b824f800-6a06-11ea-8616-95665bf789d6.png" width="300">

Does this issue occur when all extensions are disabled?: Yes

**Comment by edumqssan** [comment]
### About:
- Version: 1.43.1 (system setup)
- Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
- Date: 2020-03-18T07:01:20.184Z
- OS: Windows_NT x64 10.0.18363

### Extensions:
Activated or not the duplicated items appears.

### Steps to reproduce:

1. Add Folder in Workspace 
2. Remove Folder from Workspace

#### After Remove Folder from Workspace this happens:
![Capture(1)](https://user-images.githubusercontent.com/56772885/77064729-cfd88e00-69be-11ea-9d0d-b37efb2befe7.PNG)

After Close and open VSCode, the duplicated items vanish, but appears when remove another folder from workspace:

**Comment by isidorn** [comment]
Fixed in latest. Please use vscode insiders if you hate the issue.
Thanks
https://code.visualstudio.com/insiders/
