### ISSUE TITLE
F8 Code Action Rendering

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#9299]
- VSCode Version: 1.3.1
- OS Version: OS X

Steps to Reproduce:

1. Load up spell
2. F8 thru a file
3. Some tips will be garbled

![image](https://cloud.githubusercontent.com/assets/1051190/16854733/20e5c338-49c7-11e6-80ba-6e5a12fdaeee.png)

**Comment by jrieken** [comment]
I believe @aeschli implemented the code action in F8

**Comment by aeschli** [comment]
@jrieken you made the recent changes to gotoError 
If there are code actions we used to call this.show(..) with height 4, now it's only called with 3. The change for this is on 067428f585b6437db4e7debdff3c344489a02cd6.

**Comment by aeschli** [comment]
Still a bit hacky but I suggest we do the following changes:
- remove the absolute again from https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/gotoError/browser/gotoError.css#L38
- measure the lines we need
```
		this._fixesWidget
			.update(getCodeActions(this.editor.getModel(), range))
			.then(() => {
				let height = this._fixesWidget.domNode.clientHeight;
				let codeActionLines = Math.max(3, height / 12);
				this.show(range.getStartPosition(), lines + codeActionLines);
			});
```
Doesn't help with resizing but at least no screen cheese.
