### ISSUE TITLE
Feature request: Rename extension

### ISSUE THREAD

**Issue by ElecTreeFrying** [microsoft/vscode#92996]
**VS Code: v1.43.0**

**Feature request: Rename extension.**

I want to rename my extension completely without losing downloads/install data.

Though it is possible to rename the extension in marketplace by updating `displayName` in package.json without losing downloads.

Changing the unique identifier or the `name` key in package.json does. 

`publisher_name.unique_identifier`

**Expected:** Rename `unique_identifier` without losing downloads/install data.

https://github.com/Microsoft/vscode/issues/25988#issuecomment-304358692

> Hi sorry I just saw this
> 
> The ID for an extension is `publishername.extensionname` all meta data hangs off this e.g. downloads, ratings. This is also used for install/updates.
> 
> In this case I actually think most users would expect this to be a new extension i.e. it's pretty different from Material.
> 
> So I think publishing with a new ID would make the most sense - otherwise users will get updated and not understand that this is actually a different theme.
> 
> We don't have support for renaming today - so choosing a new name is typically something people only do in the display name or again they are forced to re-publish :(
> 
> Sean

I was told here updating `name` key in package.json will lose all my downloads and install data

https://github.com/Binaryify/OneDark-Pro/issues/54#issuecomment-599565246

> @Binaryify have you tried updating`"name"` in package.json to `"one-dark-pro"`? I also wanted to rename my extension. I resolved into what you did I renamed the `"displayName"`.
>
> @ElecTreeFrying that will lose download and install data

**Comment by prashantvc** [comment]
`publisher_name.unique_identifier` is the unique identifier for an extension. Updating it is not a common scenario on the Marketplace.

You can the Marketplace support to update identifier or transfer the extension to different publisher without loosing download counts

**Comment by ElecTreeFrying** [comment]
Yes, for now the best option is to contact Marketplace support regarding this.

Another reason why I think this feature is very helpful in VS Code, is because, in atom, publishers can [rename their package] by this script `apm publish --rename new-package-name`.

I hope they consider this feature in VS Code for extension publishers.

[rename their package]: https://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#rename-your-package

**Comment by isidorn** [comment]
No action items here, recommendation is to contact Marketplace support for this.

**Comment by TanyaScales** [comment]
For anyone that happens upon this thread -- the renaming of the extension identifier is no longer supported by the Marketplace. The renaming operation was breaking existing extension users and creating complications in the backend. I was able to verify this recently with Marketplace support.
