### ISSUE TITLE
Documentation issue for Extensions, LanguageServer

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#93]
On this page, https://code.visualstudio.com/docs/extensions/example-language-server, debugging the server is described like so:

"Since the server is started by the LanguageClient running the extension we need to attach a debugger to the running server. To do so switch to the VS Code instance containing the server code and press F5. This will attach the debugger to the server. Use the normal Debug View to interact with the running server."

I've tried this multiple times now and every time I do, the server fails to debug. I get this error:

cannot connect to runtime process (timeout after 5000ms)

**Comment by gregvanl** [comment]
Moved to vscode-docs repo https://github.com/Microsoft/vscode-docs/issues/44
Thanks @cfjedimaster for calling out the confusing text.
