### ISSUE TITLE
CTRL + K within terminal is priority bound to VSCode since v1.43.1

### ISSUE THREAD

**Issue by sunnylum** [microsoft/vscode#93005]
When using nano in bash on terminal, CTRL + K should cut a line. 

It has been doing this perfectly fine until I updated this morning to v1.43.1.

Now however, pressing CTRL + K even when focused in Terminal triggers VSCode's Ctrl + K sequence instead.

**Comment by IllusionMH** [comment]
See https://github.com/microsoft/vscode/issues/92656#issuecomment-599561292

**Comment by sunnylum** [comment]
Thanks, closing this.
