### ISSUE TITLE
Failed to show text document, should show in editor #undefined

### ISSUE THREAD

**Issue by Domiii** [microsoft/vscode#93003]
I am encountering same problem as #51906 and #73595 etc, however, the bug never got fixed; here I want to present a theory and a workaround:

## Bug Description

1. I encountered this error when calling `window.showTextDocument`  too fast, s.t. the second time I call it, the first has not resolved yet (both times I'm calling it with the same path).
   > Failed to show text document, should show in editor #undefined
1. The `activeEditor` is not of that path, and it is not pinned (i.e. it will get closed by the request)

## Workaround

Make sure that you don't call `window.showTextDocument` on the same `filePath` multiple times in quick succession:

```js


let editorOpenPromise;
let lastRequestedDocumentFpath;

/**
 * Hackfix for buggy `showTextDocument`.
 * It rejects all in-flight promises, if you query it too fast; so we need to slow things down.
 * @see https://github.com/microsoft/vscode/issues/93003
 */
async function showTextDocument(fpath) {
  if (lastRequestedDocumentFpath === fpath) {
    return editorOpenPromise;
  }
  // await editorOpenPromise;  // this will actually cause the bug again! (not sure why...)
  lastRequestedDocumentFpath = fpath;

  const uri = Uri.file(fpath);
  try {
    editorOpenPromise = window.showTextDocument(uri);
    const editor = await editorOpenPromise;
    return editor;
  }
  catch (err) {
    console.error('window.showTextDocument failed:', fpath, ' - ', err);
  }
  finally {
    // reset everything
    lastRequestedDocumentFpath = null;
    editorOpenPromise = null;
  }
  return null;
}
```

This works as expected! :)

**Comment by bpasero** [comment]
@Domiii what would be a sample code to trigger this error in the first place?

**Comment by Domiii** [comment]
Just created this minimal code sample to reproduce bug: https://github.com/Domiii/vscode-bug-1

### Instructions

1. Run extension
1. Execute "Hello World" command


### Bug reproduction recipe

1. Have an `activeEditor` that is not pinned
1. Try to open any window twice in quick succession and see it fail
   * NOTE: `vscode.window.showTextDocument(vscode.Uri.file(file2));` is not prefixed with `await`)

> Error: Failed to show text document file:///Users/domi/code/test/code-test-ext/b.txt, should show in editor #undefined

**Comment by bpasero** [comment]
@Domiii for some weird reason I can reproduce in stable but I cannot in insiders, can you give that a try quickly. 

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Domiii** [comment]
@bpasero Might be able to try on Wednesday - will let you know.

**Comment by bpasero** [comment]
Thanks
