### ISSUE TITLE
Launch Configuration "Attach by Process ID"  Not Showing Any Process IDs

### ISSUE THREAD

**Issue by mrroll** [microsoft/vscode#93009]
Issue Type: <b>Bug</b>

# Steps

1. Clone https://github.com/mrroll/vscode-attach-process
2. run `yarn && yarn start`
3. Ensure `Debugger listening on ws://127.0.0.1:9230` is present in the terminal output.
4. Hit F5

### Expected Result
5. See the node process on port 9230

### Actual Result
5. Don't see the node process.

---
# Additional Information

- It worked 2 versions ago.
- There are no errors in the developer console

---

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:17:38.324Z)
OS version: Linux x64 5.5.8-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3673)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (1.84GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mrroll** [comment]
Just a quick update. It works again. @weinand  I'm leaving it open for review in case you guys want to check it out further.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.5.13-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3189)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (4.70GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by connor4312** [comment]
Since this issue was written we have a [new debugger](https://github.com/microsoft/vscode-js-debug/). It sounds like you got it working, but please let us know if you hit it again. Thanks!
