### ISSUE TITLE
No auto import suggestion in JS node project

### ISSUE THREAD

**Issue by florian-milky** [microsoft/vscode#93002]
- VSCode Version: 1.43
- OS Version: macOs catalina but I have the same issue on windows

I am working in a pure Javascript NodeJs project. When I trigger the autocomplete I don't get any suggestion from imports.
In another es6 project, I get suggestions inconsistently. For example if don't get any auto import suggestion, but if I open the file I want to import from in another tab, then I get the suggestion.

Please advise, I have made some research about this issue but I can't find any help on how to fix this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Do you have `jsconfig.json` in your project?
See https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson for details

**Comment by florian-milky** [comment]
@IllusionMH No, it's not clear why I would need that?

**Comment by IllusionMH** [comment]
See #92163 for more details.

**Comment by florian-milky** [comment]
@IllusionMH This fixes indeed the inconsistent suggestions. However in my nodejs project, I still get no auto import suggestion

**Comment by IllusionMH** [comment]
You mean suggestions for built-in Node modules `fs` or `path`?

If yes - you can also force ATA for Node using `jsconfig.json`
```json
{
    "typeAcquisition": {
        "include": ["node"]
    }
}
```

**Comment by florian-milky** [comment]
No I mean simple imports from other files that I created in my project

**Comment by florian-milky** [comment]
I also don't get import suggestions from node modules

**Comment by florian-milky** [comment]
This fix you suggested also doesn't help with node native modules

**Comment by mjbvz** [comment]
Please share your project or code that reproduces the issue

**Comment by florian-milky** [comment]
I can't share the project but I will try to build a repro

**Comment by YYago** [comment]
@florian-milky Do you use NVM? I also encountered a similar problem on macOS Catalina, I suspect that NVM caused such an exception（default setting）. I tried it on Windows 10 without NVM, There is no similar situation（default setting）, It's normal. @mjbvz

**Comment by florian-milky** [comment]
Ok so here is what I did:
- I cloned my project
- Tested if import was working, no
- Deleted stuff step by step, import was never working
- Ended up with https://github.com/florian-milky/repro-no-import
- Started to rename stuff, and suddenly it started working
- Discarded my local changes
- Import still working

**Comment by florian-milky** [comment]
Ok so I rename date.js to import.js
=> I get the import suggestion in index.js
Revert the rename
=> Suggestion import still uses /import.js

At one point I got both suggestions but I cannot reproduce.

**Comment by florian-milky** [comment]
Now I use commonJs export and it doesn't work on my windows laptop actually. It seems like it's what confuses vs code

**Comment by florian-milky** [comment]
I updated the repo with another case.

Summary:
- `module.exports` is not included in import suggestions
- import suggestion doesn't not work if there is a `require` of a `module.exports` in the file

**Comment by florian-milky** [comment]
Can you guys reproduce?

**Comment by mjbvz** [comment]
Thanks for the example. Have you tried [creating a jsconfig.json](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) in your project?

**Comment by florian-milky** [comment]
Yes of course! @mjbvz  Do you have the issue in the repo I shared?

**Comment by mjbvz** [comment]
Should be fixed by https://github.com/microsoft/TypeScript/pull/37027

![Screen Shot 2020-03-27 at 12 54 37 PM](https://user-images.githubusercontent.com/12821956/77795147-4c581600-702a-11ea-819a-6af7dc260f66.png)

To check, please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by florian-milky** [comment]
Thank you, will do!
