### ISSUE TITLE
VS code hangs running python code

### ISSUE THREAD

**Issue by oliviercwa** [microsoft/vscode#93018]
Hello,
I am debugging Python code in VS Code and and in the middle of the debugging session, at random time, it hangs. Everything is still responsive, but the execution is frozen. I try to press F5, click on the Start button, but the session does not continue. 

Notes:
-  It can also happen after it hits a breakpoint and I type a debug command. Once it happens, there's a small arrow that appears to the left of the last command that was sent to the debug windows. All subsequent commands will show the same sign to the left. Also threads are shown as paused and clicking on resume does nothing.

- It also happens when using RUN WITHOUT DEBUGGING. But it does not happen when running outside of VS Code from a Powershell windows for example.

This is quite painful as prevents the ability to debug Python in good conditions.

Environment:
Windows 10
VS Code: Version: 1.43.1 (user setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by aeschli** [comment]
Please file this issue against https://github.com/microsoft/vscode-python
