### ISSUE TITLE
Cannot open correct external terminal for runnable tasks.

### ISSUE THREAD

**Issue by AlaricGilbert** [microsoft/vscode#93010]
- VSCode Version:1.43.1
- OS Version:Windows 10 1909

Steps to Reproduce:

1. Set settings of windows external terminal to a custom one (Windows Terminal, absolute path also tested)
```
 "terminal.external.windowsExec": "wt"
```

2. Able to open specified external terminal by `Ctrl+Shift+C`

3. Configure a runnable task with `externalConsole` set to `true`

4. Run the task configured but got default Windows conhost console

Does this issue occur when all extensions are disabled?: Yes.

**Comment by alexr00** [comment]
Can you please share a complete sample task that shows this issue?
