### ISSUE TITLE
Revert changes to scope inspector window

### ISSUE THREAD

**Issue by CameronBieganek** [microsoft/vscode#93019]
- VSCode Version: 1.43.1
- OS Version: macOS 10.13.6

I noticed that recently the layout and styling have changed for the window that is displayed when you run the `Developer: Inspect Editor Tokens and Scopes` command. I believe the format is now much less readable than it used to be.

Here's what the window used to look like:

![image](https://user-images.githubusercontent.com/8310743/77081163-37470b80-69c8-11ea-98e9-8778de63d5b2.png)

I don't have an apples to apples comparison, but here are a couple examples of what it looks like now.

![image](https://user-images.githubusercontent.com/8310743/77080246-1336fa80-69c7-11ea-897c-bd5b4c43097c.png)

![image](https://user-images.githubusercontent.com/8310743/77080912-e59e8100-69c7-11ea-8d29-1d82bb643385.png)

Observations:
- The json object in the foreground information at the bottom of the window often gets wrapped in awkward ways, especially if you're near the right edge of the editor.
- The nested TextMate scopes are much easier to read if they are left justified instead of right justified. I find the the bulleted list with left-justification in the original design to be much more readable.
- In the new layout, the TextMate scopes section and the foreground section blur together, because the dividing horizontal lines that were in the old layout have been removed. 

My examples may be a little contrived, but I've seen similar display issues during my normal workflow.

**Comment by IceSentry** [comment]
I believe this is the same issue, but currently the scope inspector sometimes looks like this:

![image](https://user-images.githubusercontent.com/8348954/79150793-5b172a80-7d97-11ea-9abb-800ad5b91cbe.png)

Which is essentially unusable. Even on an ultrawide monitor it doesn't always fit.

![image](https://user-images.githubusercontent.com/8348954/79150897-89950580-7d97-11ea-8ee9-2645ad23380c.png)

**Comment by aeschli** [comment]
The sizing issue has been tackled by https://github.com/microsoft/vscode/issues/95936.

We have no plans to revert the changes. With the semantic token information to be shows as well, it was necessary to make things more compact (and more consistent)
