### ISSUE TITLE
Add immediate-like permanent playground to VSCode

### ISSUE THREAD

**Issue by ucirello** [microsoft/vscode#93013]
It would super dope if VSCode could replicate the venerable QuickBasic 4.5 F6-style context switch to allow not only navigate around tabs etc. But also into an Immediate mode like the one in QB4.5:

![image](https://user-images.githubusercontent.com/138827/77073281-4324d480-69ac-11ea-9afb-5657dcd923ba.png)

In the 1990s, this immediate block was a sort of a permanent language-based playground that you could just switch into, type random pieces of code and see their response right away, without necessarily needing to change to a terminal or to a browser.

Several programming languages offer REPL hosts that could be used to implement this feature.

**Comment by IllusionMH** [comment]
This IDE supported only one language and provided its runtime by itself. VSCode supports other languages via extensions.

I guess that you'll need to find playground for required language:
For JS/TS it can be
https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode
Python extensions supports Jupiter notebooks
https://marketplace.visualstudio.com/items?itemName=ms-python.python#jupyter-notebook-quick-start

etc.
