### ISSUE TITLE
Notifications: if finished before delay starts the notification still shows briefly

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#93029]
If I want to use progress events for operations that may take long in some cases, but are mostly short running, I run into the problem that I do not know upfront whether to send progress events or not.

That means I always have to use progress so that progress is displayed if I need them.

This results in flicker in the notification "bell".
 
To repro replace the "nextRequest" method of mockDebug by the following:
```js
protected nextRequest(response: DebugProtocol.NextResponse, args: 
 DebugProtocol.NextArguments): void {
		const ID = '' + this._progressId++;
		this.sendEvent(new ProgressStartEvent(ID, "Step"));
		this.sendEvent(new ProgressUpdateEvent(ID, "update"));
		this._runtime.step();
		this.sendEvent(new ProgressEndEvent(ID, "end"));
		this.sendResponse(response);
}
```

If you now step through a Readme.md the little red dot on the bell flashes and if notifications are open I even see a notification popping up and disappearing immediately.

I suggest that we only show the progress UI if the progress runs longer than some threshold (e.g. 500 ms).

**Comment by isidorn** [comment]
Makes sense. I actually went with 500ms. Note that explorer shows progress on startup only after 800ms delay and search shows progress only after 300ms. So just for reference.

**Comment by isidorn** [comment]
This can be verified via the test plan item https://github.com/microsoft/vscode/issues/92914 , thus adding label on-testplan

**Comment by weinand** [comment]
I still see notifications on every step:

![2020-04-02_16-53-42 (1)](https://user-images.githubusercontent.com/1898161/78263982-e9bbba00-7502-11ea-90c0-90fe6de2388a.gif)

**Comment by isidorn** [comment]
We are passing a delay to the notification service here https://github.com/microsoft/vscode/blob/56df825f8412d48e1eb45d4c164e7483563593c8/src/vs/workbench/contrib/debug/browser/debugProgress.ts#L44

@bpasero is there something I am missing in the notification service? `delay` should be just respected?

**Comment by bpasero** [comment]
I am not sure I can reproduce an issue with regards to the `delay`, I tried the following:

Have an extension with the following code:

```ts
vscode.window.withProgress({
	location: vscode.ProgressLocation.Notification,
	title: 'Progress Title'
}, step => {
	step.report({
		message: 'Sub message'
	});

	return new Promise(resolve => {
		setTimeout(() => {
			resolve();
		}, 5000);
	});
});
```

Add an artificial delay of 2000ms here:

https://github.com/microsoft/vscode/blob/b720350e5cd02156f0f345116659fbc966f4962c/src/vs/workbench/services/progress/browser/progressService.ts#L173

e.g. 

```ts
options = {
	...options,
	delay: 3000
};
```

The notification with progress only appears after 3 seconds.

**Comment by isidorn** [comment]
@bpasero thanks for trying it out. Sorry for pinging you before I tried it out - I can also not reproduce this. 
I wrote a fake adapter that firest a debug start event, and increased the delay to 5000 ms. I can cleary see the progress starting with the delay of 5000ms.
@weinand can you please create a fork or branch of mock debug that shows this issue so we can investigate further. Thank you

**Comment by weinand** [comment]
@isidorn I was under the impression that my initial comment for this issue explains the problem in a reproducible way:

To repro replace the "nextRequest" method of mockDebug by the following:
```js
protected nextRequest(response: DebugProtocol.NextResponse, args: 
 DebugProtocol.NextArguments): void {
		const ID = '' + this._progressId++;
		this.sendEvent(new ProgressStartEvent(ID, "Step"));
		this.sendEvent(new ProgressUpdateEvent(ID, "update"));
		this._runtime.step();
		this.sendEvent(new ProgressEndEvent(ID, "end"));
		this.sendResponse(response);
}
```

**Comment by isidorn** [comment]
@weinand no I did not try to repro with that step, I did try now and the issue is the following:
If the progress is reported with a delay, and the progress ends before the delay starts the progress is briefly shown, it should not be shown.

@bpasero to reproduce in your example from your comment above in `progressService` on line 174 add the following
```
(<any>options).delay = 500;
```
In your extension sample, use a timeout of 0, not 5000 for the `progressEnd` event. So the following:
```javascript
vscode.window.withProgress({
	location: vscode.ProgressLocation.Notification,
	title: 'Progress Title'
}, step => {
	step.report({
		message: 'Sub message'
	});

	return new Promise(resolve => {
		setTimeout(() => {
			resolve();
		}, 0);
	});
});

```

**Comment by isidorn** [comment]
@bpasero a potential solution: here in the `setTimeout` you need to check if the notification is finished before creating it
https://github.com/microsoft/vscode/blob/b9413f670d47cd267715487033e59260728e3b35/src/vs/workbench/services/progress/browser/progressService.ts#L360

**Comment by bpasero** [comment]
I think this is a consequence of always waiting for 800ms before clearing the timeout. I now only force the notification to show for 800ms unless a delay is provided.

**Comment by isidorn** [comment]
@bpasero thanks for fixing this.
