### ISSUE TITLE
Hardware acceleration issue with Nvidia GTX 1060i

### ISSUE THREAD

**Issue by cbolden** [microsoft/vscode#93026]
The screen does not render properly whenever the mouse hovers over any object on the screen. Pixilation occurs to the poin where the text in unreadable. Needless to say, this is very annoying. How can I disable hardware acceleration?

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by cbolden** [comment]
Thank you for such a prompt response!

Sent from Mail for Windows 10
