### ISSUE TITLE
Treat CJK characters differently

### ISSUE THREAD

**Issue by revi** [microsoft/vscode#93021]
Issue Type: <b>Bug</b>

<img width="90%" alt="image" src="https://user-images.githubusercontent.com/7630875/77083814-6d74a180-6a41-11ea-8e53-4c2e56954ee1.png">
I can type following text (^) in VS code without being hit by 280 chars limit (in this case, 257) ...

```
가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마바사아자차카파타하가나다라마
```

But when I actually try to tweet this strings...

<img width="90%" alt="image" src="https://user-images.githubusercontent.com/7630875/77084434-51253480-6a42-11ea-8aae-7ef3aa447def.png">

It has -117 chars. As you might know (or not), this is because [Twitter lets CJK languages only 140 chars, as it was in the past](https://blog.twitter.com/en_us/topics/product/2017/Giving-you-more-characters-to-express-yourself.html).

>> Source above
>
> we're going to try out a longer limit, 280 characters, in languages impacted by cramming (which is all except Japanese, Chinese, and Korean).

This is similar to #39303 but in my case, locale of code is `en`, not `ko`.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.34.0
EditorConfig|Edi|0.14.4
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
php-intellisense|fel|2.3.14
discord-vscode|icr|3.13.0
phpcs|ika|1.0.5
mysql-syntax|jak|1.3.1
mediawiki|jak|2.1.0
vscode-peacock|joh|3.6.0
chat|kar|0.31.0
vscode-docker|ms-|1.0.0
python|ms-|2020.2.64397
azurecli|ms-|0.5.0
vsliveshare|ms-|1.0.1783
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
heroku-command|pko|0.0.8
code-settings-sync|Sha|3.4.3
vscode-wakatime|Wak|4.0.0
HCL|who|0.0.5

(1 theme extensions excluded)

</details>

**Comment by coughingmouse** [comment]
I would say this is a bug as revi initially suggested, not a feature-request. I'd love to know why anyone would think of this as a feature.
