### ISSUE TITLE
Minor UI inconsistencies: Input heights

### ISSUE THREAD

**Issue by TimGr** [microsoft/vscode#93022]
I found different heights within Visual Studio Code and counted a total of six different values: 38px, 48px, 50px, 52px, 56px and 60px. Perhaps we can reduce/unify these to a set of three values, like small, medium and large? In my opinion, at least the inputs in the sidebar should have identical heights to prevent small layout jumps when changing the sidebar view.

<img width="1280" alt="vscode-input-heights" src="https://user-images.githubusercontent.com/3532570/76908515-29e72f80-68a9-11ea-9e7b-fdfe11d6bd69.png">

**Comment by misolori** [comment]
I've updated all of the input heights to be `26px`, there are some cases where it needs to be smaller at `24px` like in the panel (problems/console). The find widget should also be updated cc @rebornix 

![image](https://user-images.githubusercontent.com/35271042/95380950-52ae3100-089c-11eb-89ed-c3f8b0599477.png)

**Comment by alexr00** [comment]
Verified by spot checking 4 different input areas.
