### ISSUE TITLE
Entire window goes black except for sections on certain mouse input/movement

### ISSUE THREAD

**Issue by Tetheta** [Microsoft/vscode#9302]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Enterprise Version 6.1.7601

Steps to Reproduce:

1.  Occurs on mouse movement/insert mode changes it seems. I can't reproduce it consistently. Has been doing it for the last few updates.

**Comment by bpasero** [comment]
Electron issue.

**Comment by bpasero** [comment]
@Tetheta this might help: https://code.visualstudio.com/Docs/supporting/faq#_vs-code-main-window-is-blank

**Comment by Tetheta** [comment]
@bpasero Great thanks, I'll try that. Here'a also a picture of what I mean:
![vs code error](https://cloud.githubusercontent.com/assets/3209941/16879433/69f4b446-4a65-11e6-920a-a81c08ff1578.png)

**Comment by Tetheta** [comment]
Here's a sample of what the bug looks like:
![image](https://cloud.githubusercontent.com/assets/3209941/16888094/b88e0c7e-4a92-11e6-8bdf-5ea61a614c97.png)

**Comment by bpasero** [comment]
@Tetheta  could you give our insider release a try to see if this issue is fixed? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Tetheta** [comment]
Hey @bpasero, sorry for not updating this. I haven't gotten this error in a month I think, looks like it was either fixed or I changed something on my end. Sorry for note closing the issue, I totally forgot about it. Thanks for the help!
