### ISSUE TITLE
Cannot drag a view into an unopened viewpanecontainer

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93039]
- Move time line view to panel as a separate panel
- Try to move time line view in panel into another panel (Problems?)  - Cannot

**Comment by sbatten** [comment]
To Verify:
1. Move timeline into the panel (by itself)
2. Move outline into the panel (by itsefl)
3. Try to drag timeline into outline by hovering the outline title for a second and then dropping it inside the panel.
