### ISSUE TITLE
Shortcuts not working. Mainly the ones with ctrl in them

### ISSUE THREAD

**Issue by charbelsako** [microsoft/vscode#93036]
- VSCode Version: 1.43.
- OS Version: Parrot home

Steps to Reproduce:

1. Get Parrot home
2. Install vscode

Does this issue occur when all extensions are disabled?: Yes

This is probably an issue with the os, maybe it uses ctrl for something else, even tho' I checked and it isn't, only combinations with alt are used. Furthermore, I have to type `ctrl+shift+و` to enter preferences. Is this induced by the keyboard app? I do have the options to change the keyboard model current one is **generic 105-key Pc (intl.)**

**Comment by charbelsako** [comment]
They work now. Maybe keyboard isn't good?

**Comment by alexdima** [comment]
@charbelsako Can you please try other software on the machine? How about Chrome, does Chrome receive keybindings with Ctrl?

**Comment by charbelsako** [comment]
Ctrl works everywhere else. I think this is because i had arabic as a higher priority than english. @alexdima

**Comment by alexdima** [comment]
:+1: Great that it worked. If you have other issues, you can also try `"keyboard.dispatch": "keyCode"`.
