### ISSUE TITLE
Cannot add debugging breakpoint 

### ISSUE THREAD

**Issue by aastein** [microsoft/vscode#93032]
- VSCode Version: 1.43.1
- OS Version: macOS 10.15.3

Steps to Reproduce:

1. Open a file
2. Click to the left side of the line count in the file to add a breakpoint, no breakpoint is added

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
>     1. Open a file

What language?

**Comment by aastein** [comment]
Golang, doing this https://github.com/Microsoft/vscode/issues/45486#issuecomment-372144694 fixed the issue. Must be my settings.

**Comment by aastein** [comment]
somehow this setting "debug.allowBreakpointsEverywhere" was false. Setting it to true fixed the issue.

**Comment by aastein** [comment]
root cause was go language support was disabled for the workspace. not sure how that happened.
