### ISSUE TITLE
Moving the timeline view from panel on to activity bar is changing the explorer position

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93037]
![Kapture 2020-03-19 at 19 58 10](https://user-images.githubusercontent.com/10746682/77104249-02fd3a80-6a1c-11ea-80c2-6ac461938233.gif)

Issues I see

- Activity bar is showing a valid drop target but it is still getting dropped insider a viewlet
- I cannot drop on top of the activity bar icon - which mean I want to drop this view in that view container. Looks like I can only drop it in the empty space in the activity bar. On doing so, it is moved to explorer viewlet 🤔

**Comment by sbatten** [comment]
yea in this case it is trying to move it into the default container, because we cannot create our own view container.

**Comment by sbatten** [comment]
this is fixed with custom view containers now working

**Comment by sbatten** [comment]
To Verify:
1. Ensure Explorer is at the top of the activity bar.
2. Drag Timeline from Explorer Viewlet to its own panel.
3. Drag Timeline to the activity bar below the last item in the activity bar.

Ensure you get a new viewlet using the custom view icon that is just for timeline and that explorer remains at the top of the activity bar.
