### ISSUE TITLE
Excess Composite Bar Feedback does not match the composite bar actions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93038]
![Kapture 2020-03-19 at 20 02 59](https://user-images.githubusercontent.com/10746682/77104670-ae0df400-6a1c-11ea-8889-073bdbcd7607.gif)

**Comment by sbatten** [comment]
To Verify:

1. Drag timeline to just after the last item in the activity bar and or panel header area.

Ensure that you get the same `insert-line` feedback that you get for the rest of the activity bar or panel titles.
