### ISSUE TITLE
Allow comments to include command links

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vscode#93034]
Currently, the comments API allows comments to include links to HTTP-based resources, but it would be great if they could also include references to VS Code commands (using the `[](command:commandName)` syntax). As part of building out the [CodeTour](https://aka.ms/codetour) extension, I'd like to be able to have tour steps include links to automate workbench actions such as starting the debugger/etc. (as opposed to telling the user to do it), which would help create a more interactive/guided experience.

To ensure this experience is secure/predictable, maybe the `CommentController` could introduce a new setting that determines whether command links are enabled or not? The `WebViewOptions` type already include a `enableCommandUris` setting, and so maybe we could add the equivalent to the `CommentController`? That way, the GitHub PR extension doesn't need to support them/etc. if it doesn't make sense.

// CC @rebornix

**Comment by rebornix** [comment]
Hey @lostintangent , I just realized this is already supported as we allow using `MarkdownString` for `Comment.body`, all you need to do in the extension is when you create a Comment object, make sure that `isTrusted` is set on `vscode.MarkdownString`.

```ts
let markdownBody = new vscode.MarkdownString(reply.text);
markdownBody.isTrusted = true;

let newComment = new NoteComment(markdownBody, vscode.CommentMode.Preview, { name: 'vscode' }, thread, thread.comments.length ? 'canDelete' : undefined);

```

**Comment by lostintangent** [comment]
Ah OK awesome! Thanks for that tip 👍
