### ISSUE TITLE
Add suggestions for key binding when clause contexts

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#9303]
When the user is creating custom keybindings, we now have suggestions (IntelliSense) for command ids.

Suggestions for then when clause contexts (ex, editorFocus, inDebugMode, etc) would also be useful.

**Comment by alexanderluchs** [comment]
Suggestion for new when clause context: contexts related to the source control viewlet.  e.g. sourceControlViewletFocus, souceControlInputBoxFocus, sourceControlFilesStaged, etc.

**Comment by isidorn** [comment]
@alexandrudima is there a central place where all the contexts are known so we inject this into the schema? If yes could you provide a code pointer, somebody might want to do a PR. Maybe @gregvanl

**Comment by alexandrudima** [comment]
@isidorn No, at this time, keybindings are contributed at runtime from various parts of our system...

**Comment by vasselai** [comment]
Would it be possible to add a 'when clause' that checks the name of currently active integrated terminal? That would make it so much easier to implement specific functionality for different types of terminal usage.

**Comment by isidorn** [comment]
@usernamehw if we had a hard coded list of context keys it would be easy to add them.
However having a hard coded list has the down side that we have to manage that list, and it might easily get out of sync with reality

**Comment by usernamehw** [comment]
It would still probably be better than no suggestions.

**Comment by jasonwilliams** [comment]
Is this still a possibility?

**Comment by usernamehw** [comment]
Made a minimalistic extension that adds autocomplete for context keys:

![](https://github.com/usernamehw/vscode-when-suggest/raw/master/img/demo.png)

https://marketplace.visualstudio.com/items?itemName=usernamehw.when-suggest

**Comment by jrieken** [comment]
I have pushed this for keybindings.json and for when-clauses in extensions' package.json files. Over time we are also adding descriptions to context keys. I'll create another issue for the UI keybindings editor


<img width="1254" alt="Screenshot 2021-02-17 at 14 36 03" src="https://user-images.githubusercontent.com/1794099/108221404-0c18ef00-7138-11eb-940b-c1a282402648.png">

**Comment by jrieken** [comment]
To verify: 

* open the `keybindings.json`-file and make sure context keys are suggested inside the when-clause
* open the `package.json`-file of an extension and make sure context keys are suggested inside the when clause of menu contributions
* make sure context keys aren't suggested outside of when-clauses

**Comment by bpasero** [comment]
**Verified:**
* works in `keybindings.json` and `menu` contributions
* has a little glitch when not typed a character: https://github.com/microsoft/vscode/issues/117594

As a follow up, it would be nice if:
* we expand the support for intellisense to any place that has `when` (e.g. extension contributed `keybindings` in `package.json`)
* we support this also in the keybindings UI editor where I can edit when clauses:

![image](https://user-images.githubusercontent.com/900690/109018531-80174200-76b8-11eb-877b-2bf70a245c97.png)

**Comment by jrieken** [comment]
> we support this also in the keybindings UI editor where I can edit when clauses:

Agree, we have https://github.com/microsoft/vscode/issues/116855 for that


> when (e.g. extension contributed keybindings in package.json)

Oh, that will be trival to do
