### ISSUE TITLE
Panel when moved to right or left is still having views side by side

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93040]
Panel when moved to right or left is still having views side by side

<img width="734" alt="image" src="https://user-images.githubusercontent.com/10746682/77105233-9420e100-6a1d-11ea-9fa3-4bf091b2e1d1.png">

Hope you already know about it. If there is an issue already close this as a dup.

**Comment by sbatten** [comment]
To Verify:
1. Start by creating a multipanel with timeline and outline
2. Move panel to the left or right
3. Verify that the panels reflow to vertical layout
