### ISSUE TITLE
Keeping open file history

### ISSUE THREAD

**Issue by rtorr** [Microsoft/vscode#9304]
So, one thing I really liked about 1.2 and prior, is files did not belong to an "editor" (pane). It was one of my favorite things about vscode. I can open and close editors when ever I want. Sometimes something is not relevant or I want more room for one file, so I will close other editors. Keeping files and editors separate lets you move around your codebase without worrying about losing history. I thought this was a bug at first, since I have both tabs and "open editors" hidden in the UI as I don't need or use them.

Via twitter I heard these new split editor features were wildly requested. Feature requests are easy to make, but its hard to vote on _keeping_ a feature that you already like.

My suggestion would be to keep the awesome work you did with tabs, but maybe store all open files in a single list also. So any time you open a file, it gets pushed to that list, while also being associated to and editor for tabs and what not.

Thoughts?

<3

- VSCode Version:
1.3
- OS Version:
OSX

**Comment by bpasero** [comment]
Read and follow `Ctrl+Tab to navigate in entire editor history` in https://github.com/Microsoft/vscode/issues/6605

**Comment by rtorr** [comment]
@bpasero

Can you have all editors closed and still have unsaved files/have edit history? I'm not sure your suggestion even relates to the feature I feel is now missing.

**Comment by bpasero** [comment]
@rtorr that in particular you cannot do anymore, closing a dirty file and having it floating around is gone. We have no intent to bring this behaviour back nor make it configurable.

**Comment by rtorr** [comment]
I really appreciate you taking the time fore the reply. On last note to think about and does not need a reply but is just feedback; The new open files list in editors on that replaces working files duplicates the functionality of open tabs, and it's hard to see how it is better than working files. Just saying I think you had it right the first time.

Thanks again! Keep up the awesome work (sincerely) :)

**Comment by rtorr** [comment]
The biggest pain point I have with this is I have to remember what file is in what editor/pane so I don't lose undo functionality

**Comment by bpasero** [comment]
Can you explain how that is a problem by an example?

**Comment by rtorr** [comment]
I viewed editors as temporary. I would open and close them as I need context of 1-3 files, not assuming I need the editor open for the life of a file. Open an editor/file, make some changes, close. Reopen said file in any editor and still have undo history if needed. Prior to this release, vscode viewed editors as a view to a file, not own it's lifecycle. That is what the now removed working files drop down did. I used the 'recent files' fuzzy finder as my goto for "working files".

**Comment by rtorr** [comment]
If I have both tabs and 'open editors' hidden (which I do because I don't use them in favor of recent files fuzzy finder), I have no context to when I'm going to lose file history

**Comment by bpasero** [comment]
We are working on a fix to keep the undo history even after closing the editor, so we are aware of this particular issue.

**Comment by rtorr** [comment]
Awesome!
