### ISSUE TITLE
Split webpack bundles are very difficult to load in webviews

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93041]
Playing with getting [speedscope](https://github.com/jlfwong/speedscope) into my profiler visualizer. Speedscope is a large and fairly complex web application, and like a good large web application it takes advantage of code splitting. I was struggling a bit with how to it working inside of webviews with my webpack build.

The issue is that the location where webview assets are loaded from is different on different machines, but webpack needs the public path to load them from. They "support" [setting it on the fly](https://webpack.js.org/guides/public-path/#on-the-fly), however this doesn't work for bundles, only static assets.

My solution was super ugly, setting the publicPath during the build to __PUBLIC_PATH__ and then (abbreviated):

```ts
export const getHtml = async (
  bundleFile: string,
  publicPath: string,
) => {
  let bundle = await fs.readFile(bundleFile, 'utf-8');
  bundle = bundle.replace(new RegExp('__PUBLIC_PATH__', 'g'), publicPath);
  
  return `<!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Custom Editor: ${bundleFile}</title>
    </head>
    <body>
      <script type="text/javascript" nonce="${nonce}">${bundle}</script>
    </body>
    </html>
  `;
};
```

Maybe we should provide some better guidance here, or even some webpack plugin people could use that (in tandem with some data that VS Code could inject) sets the public path correctly?

**Comment by mjbvz** [comment]
@rebornix Created https://github.com/rebornix/vscode-webview-react that may offer guidance. Maybe we could make that an official extension sample?

Can you use the html [base element](https://developer.mozilla.org/en-US/docs/web/html/element/base) so that all your scripts are belong to a specific root folder in your extension?

**Comment by connor4312** [comment]
The sample is nice, but it doesn't use any async imports. I suspect that doing so would exhibit the same failure 🙂  I'll give the base element a spin in the morning.

**Comment by rebornix** [comment]
I'm wondering if https://github.com/rails/webpacker/issues/2269#issuecomment-548816104 can help.

**Comment by connor4312** [comment]
I tried to 'demo' lazy loading in the vscode-webview-react library. One further issue I had there is the CSP nonce. It seems like create-react-app doesn't really have good support for this, and without ejecting the webpack config or adding `sed`-like postbuild steps it's hard to integrate into to the process.

CRA also doesn't provide a build-watcher mode, which makes webview development a pain... maybe we should create/rebuild the demo on a webpack build. Thoughts @rebornix?
