### ISSUE TITLE
find and replace not working properly like before

### ISSUE THREAD

**Issue by adilaijaz30** [microsoft/vscode#93043]
Issue Type: <b>Bug</b>

find and replace not working properly like before.

When I try to replace a CSS snippet with empty space, it doesn't work as it should.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.33GB free)|
|Process Argv|F:\dribbble\You Exec\Real work\Brave|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.20.0
beautify|Hoo|1.5.0
debugger-for-chrome|msj|4.12.6
remove-comments|pli|1.2.2
LiveServer|rit|5.6.1
vscode-status-bar-format-toggle|tom|2.0.0

</details>

**Comment by chrisbull** [comment]
Find and replace all also not working. 
Used to be able to use command + enter to replace all.
Now it opens and editor with all lines to files. 
The issue isn't the page. The issue is that now the key binding is `command + option + enter`... but only works once and then doesn't work again unless I close the app or do a hard refresh on the app.

**Comment by rebornix** [comment]
dup of https://github.com/microsoft/vscode/issues/92443
