### ISSUE TITLE
The VSCode extension docs should explain how to publish the extension

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/vscode#93050]
I don't see any information here about how to publish the extension:

https://code.visualstudio.com/api/get-started/extension-anatomy

is "how to publish your vscode extension" documented somewhere else? if so, it should be also in there.

**Comment by gjsjohnmurray** [comment]
Look in the next section, "Working With Extensions". There's a page titled "Publishing Extensions".

https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by aeschli** [comment]
Thanks @gjsjohnmurray !
