### ISSUE TITLE
Some completion items are ignored in certain scenarios

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#93054]
Issue Type: <b>Bug</b>

1) git clone https://github.com/microsoft/vscode-azurearmtools.git
2) cd vscode-azurearmtools
3) npm i
4) open in vscode, F5
5) Create a new json file with these contents:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        
    }
}
```
6) Place the cursor on the empty line under "parameters"
7) Type a double quote
8) Note that two completions show up from the extension
<img width="599" alt="image" src="https://user-images.githubusercontent.com/6913354/77124901-70e83880-6a01-11ea-889b-8ac9dcbc2d1f.png">
EXPECTED: Three should still show up

Code is in src/AzureRMTools.ts:
```json
private async onProvideCompletions(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Promise<vscode.CompletionList | undefined> {
        const oneBefore = new vscode.Position(position.line, position.character - 1);
        const oneAfter = new vscode.Position(position.line, position.character + 1);
        const one = new vscode.CompletionItem(`New parameter one - empty range`);
        const two = new vscode.CompletionItem(`New parameter two - range includes quotes`);
        const three = new vscode.CompletionItem(`New parameter three - range includes quotes, "quote in label`);

        one.range = new vscode.Range(position, position);
        one.insertText = `"parameter1": {` + EOL + `\t"value": "hello"` + EOL + `}`;
        one.kind = vscode.CompletionItemKind.Snippet;

        two.range = new vscode.Range(oneBefore, oneAfter);
        two.insertText = `"parameter1": {` + EOL + `\t"value": "hello"` + EOL + `}`;
        two.kind = vscode.CompletionItemKind.Snippet;

        three.range = new vscode.Range(oneBefore, oneAfter);
        three.insertText = `"parameter1": {` + EOL + `\t"value": "hello"` + EOL + `}`;
        three.kind = vscode.CompletionItemKind.Snippet;

        return new vscode.CompletionList([one, two, three]);
    }
```

Completion one appears okay because the range is empty, but then you end up with extra double quotes.
Completion two's range includes the quotes, but it doesn't show up in the list.
Completion three is the same as two, but I added a double quote *into the label*.  (Took quite a while to figure this out.)

This behavior is undocumented and weird and difficult to deal with.  Why should a double quote inside the label of all things make this change in behavior?  

VS Code version: Code - Insiders 1.44.0-insider (c0eea2a712471a4d242d15704cfa968241d63280, 2020-03-19T09:21:46.589Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
todo-tree|Gru|0.0.169
vscode-antlr4|mik|2.2.3
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.14
vscode-dotnet-runtime|ms-|0.1.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
azure-account|ms-|0.8.8
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.9.0-alpha
tmcolor|sle|0.0.1
vscode-todo-highlight|way|1.0.4
arm-params-generator|wil|0.9.0

</details>

**Comment by jrieken** [comment]
This is the expected behaviour - the range defines that that is being replaced *and* the prefix that is used to filter/rank items.

**Comment by StephenWeatherford** [comment]
@jrieken What does the label have to do with anything then?  I want the label to simply be "Insert new parameter", but it won't work that way.  Label should not affect functionality.  Also, the documentation is woefully inadequate on explaining how any of this is supposed to work.

**Comment by shmish111** [comment]
@jrieken I have opened https://github.com/microsoft/monaco-editor/issues/1889 which I think is the same as this issue. According to the monaco documentation (which is apparently generated from VSCode) there is a bug - the behaviour is different to the documentation. In the example @StephenWeatherford provided, it is my understanding that item two should show up however it doesn't because the range starts _behind_ the cursor.
