### ISSUE TITLE
QuickPick: on close shuold return focus to previously focused element

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode#93055]
- VSCode Version: 1.43.0
- OS Version: mac OS catalina

Steps to Reproduce:

1. open a quick pick dialog from a button in the view header using keyboard
2. close the dialog

Expected: the keyboard focus should return to the view header button

I have created a simple extension to reproduce the issue: https://github.com/alanrenmsft/vscode-extension

and here is the recording:
![Mar-19-2020 16-26-34](https://user-images.githubusercontent.com/13777222/77124689-ca039c80-6a00-11ea-8c0c-9e4ae7c18f5a.gif)

This PR: https://github.com/microsoft/vscode/pull/92969 will work for the scenarios where the original button is still present in the UI, but not for my scenario the view header buttons are only visible when the header is expanded and focused.

**Comment by isidorn** [comment]
We had a somewhat similar discussion regarding focus and action bar and what should happen on escape here https://github.com/microsoft/vscode/issues/91085

Though I do agree it would be best if quick pick would return focus to where it was before quick pick was opened.
Currently quick pick just passes focus to the editor. Which is a good assumption which works great most of the time.

Though since this is a feature request against quick pick forwarding to @bpasero and @chrmarti

**Comment by bpasero** [comment]
This would probably annoy a lot of users that are used to focus returning to the editor. I would do a change only after careful consideration. 

The focus is returned here: https://github.com/microsoft/vscode/blob/dd0f2fecd124767ba7565190190d27045e6e9249/src/vs/platform/quickinput/browser/quickInput.ts#L71

**Comment by chrmarti** [comment]
Did some testing and found that this might actually work well. We need to test it during daily work to be sure. I'm not sure in which cases this might be unexpected, but it does fix some obvious cases - like when the terminal has focus, you open the command palette and then escape to find the focus switched to the editor.

**Comment by chrmarti** [comment]
Change pushed to master for testing.

**Comment by bpasero** [comment]
@chrmarti it could break any command that expects focus to be in the editor when quick pick closes (talking about the command palette). Just so that you know...

**Comment by isidorn** [comment]
Good for pushing to master, so we see try it out and breakages early. Thanks

**Comment by chrmarti** [comment]
No feedback so far. Closing as fixed. :)
