### ISSUE TITLE
Error - Changes committed to remote repository but deployment to website failed. ; error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.

### ISSUE THREAD

**Issue by evavargas** [microsoft/vscode#93052]
Issue Type: <b>Bug</b>

- ------------------------- Whit file global.json configured to sdk 3.0.103:

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>dotnet --info
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.0.103
 Commit:    b7ef045669

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.103\

Host (useful for support):
  Version: 3.0.3
  Commit:  c03f2fe626

.NET Core SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

-  -------------------------WhitOUT the file global.json configured to sdk 3.0.103:

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>dotnet --info
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.0.103
 Commit:    b7ef045669

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.103\

Host (useful for support):
  Version: 3.0.3
  Commit:  c03f2fe626

.NET Core SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

-  ---------------------------------- Try to deploy in Azure

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git init
Reinitialized existing Git repository in C:/Users/EVA MARIA/Documents/kyt/knowyourteam/Knowurteam.API/.git/

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git add .

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git commit -m "try to deploy"
[master 43ecbd2] try to deploy
 2 files changed, 6 deletions(-)
 delete mode 100644 global.json
 delete mode 100644 nota.txt

- ---------------------------- PUSH to Azure **THE PROBLEM** 

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git push azure master
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 225 bytes | 225.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '43ecbd2852'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling ASP.NET Core Web Application deployment.
**remote: D:\Program Files (x86)\dotnet\sdk\2.2.109\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [D:\home\site\repository\Knowurteam.API.csproj]
remote: Failed exitCode=1, command=dotnet restore "D:\home\site\repository\Knowurteam.API.csproj"**
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://knowurteam.scm.azurewebsites.net:443/knowurteam.git
   c66523f..43ecbd2  master -> master

__________________________________________________________________________
 Directorio de D:\

10/03/2020  18:45    <DIR>          Documentos
11/03/2020  17:04               215 get user Inicial.txt
12/03/2020  14:21    <DIR>          IMAGENES
16/03/2020  23:28    <DIR>          javascript
15/02/2020  14:22    <DIR>          Mama
14/03/2020  15:11    <DIR>          pyclases
22/10/2019  11:24    <DIR>          Reserbar
               1 archivos            215 bytes
               6 dirs  20.542.353.408 bytes libres

the enviroment path for dotnet is: C: \ Program Files \ dotnet \ and there is not another enviroment var configured for dotnet neither sdk installed ... I don't know why take the disc D if no there relation.
I dont know if the problem is with azure, with dotnet, or what.
Is possible install the same SDK  in both Disks?
Help me please.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
vscode-caniuse|aka|0.5.3
vscode-sqlite|ale|0.8.1
vscode-intelephense-client|bme|1.3.11
vscode-standardjs|che|1.2.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.34.0
mustache|daw|1.1.1
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.7.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
RunOnSave|eme|0.2.0
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
auto-using|Fud|0.7.15
sass-lint|gle|1.0.6
beautify|Hoo|1.5.0
generic-extension-pack|itm|0.0.7
html-extension-pack|itm|0.0.6
node-babel-extension-pack|itm|0.0.6
node-extension-pack|itm|0.0.7
node-react-extension-pack|itm|0.0.6
csharpextensions|jch|1.3.1
webpack|jer|2.2.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
vscode-vsproj|jRi|1.2.1
vsc-python-indent|Kev|1.8.1
node-module-intellisense|lei|1.5.0
csharpfixformat|Leo|0.0.84
vscode-language-babel|mgm|0.0.26
code-beautifier|mic|2.3.3
vscode-csscomb|mrm|5.3.0
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.9.0
csharp|ms-|1.21.14
python|ms-|2020.2.64397
remote-wsl|ms-|0.42.4
azure-account|ms-|0.8.8
es6-typescript-import-sorter|nik|1.1.2
indent-rainbow|ode|7.4.0
fix-json|oli|0.1.2
vscode-jest|Ort|3.1.1
vscode-versionlens|pfl|0.25.0
material-icon-theme|PKi|4.0.1
vscode-react-refactor|pla|1.0.5
run-on-save|puc|1.1.4
vscode-xml|red|0.10.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
jenkinsfile-support|sec|0.1.0
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
auto-rename-tag|Sim|0.1.4
vscode-csstree|sme|0.8.0
csharp-code-snippets|Som|0.0.1
autoimport|ste|1.5.3
sass-indented|syl|1.7.5
modern-javascript-snippets|tun|1.1.0
vscode-w3cvalidation|Umo|2.6.3
vscode-wakatime|Wak|4.0.0
full-react-snippets|wal|1.4.1
beauty|yhp|0.0.2
markdown-all-in-one|yzh|2.7.0
json|Zai|1.0.4
html-css-class-completion|Zig|1.19.0
vscode-proto3|zxh|0.4.2

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
I don't think this has anything to with VSCode...

Sorry, you have to ask the question in a dot.net sdk forum, or search here: https://github.com/dotnet/sdk

**Comment by evavargas** [comment]
thankyou. I coppied this issue to https://github.com/dotnet/sdk/issues/10939
