### ISSUE TITLE
When shutdown VS Code directly nor the file, it didn't save the file!

### ISSUE THREAD

**Issue by xiaomaoaichiyu** [microsoft/vscode#93068]
Version: 1.43.1 (user setup)
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. when I change my file but not save it, and directly shutdown the VS Code. 
And VS Code will not remind me to save the file but directly shutdown.
2. Of course, when I open VS Code, the change will be here, and I still have it.
But thing is that the file is not changed when I only do 1, which means the file is still the same without any change.
3. if I shutdown the file nor VS Code, it will remind me to save it!
4 my question is if this is a Bug or just a design?
(sorry, my English is not very good!, hope you can understand this)

![image](https://user-images.githubusercontent.com/40788520/77142324-b87ecb00-6aba-11ea-93ee-a16c80d56213.png)
the left is reopen the VS Code after changed the file and shutdown VS Code directly!
while the right is actual file opened by VIM

Does this issue occur when all extensions are disabled?: No
I use VS Code practice my c++!
so the extensions include normal need！

**Comment by gjsjohnmurray** [comment]
VS Code calls this behaviour "hot exit". Search for that term in the docs and/or Settings page. It can be turned off.

**Comment by xiaomaoaichiyu** [comment]
ok，thx！
