### ISSUE TITLE
seach function problem

### ISSUE THREAD

**Issue by wilsonParm** [microsoft/vscode#93062]
1 .use  ctrl + F use search function.
2. no empty search box and press ESC

result: the vscode also show search highLight

----------------------------------------------------------------------------------------------------------
VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.29
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
vscode-vibrancy|eyh|1.0.9
theme-monokai-pro-vscode|mon|1.1.15
vscode-language-pack-zh-hans|MS-|1.43.9
python|ms-|2020.3.69010
cpptools|ms-|0.27.0-insiders3
debugger-for-chrome|msj|4.12.6
java|red|0.58.0
background|sha|1.1.23
ayu|tea|0.18.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.1
vscode-icons|vsc|10.0.0

(16 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Can you reproduce the issue after reloading with all extensions disabled?

**Comment by wilsonParm** [comment]
oh when i use vscode again today, this problem is miss, i no sure what i  have do to let it be fixed
