### ISSUE TITLE
Settings Sync not found

### ISSUE THREAD

**Issue by RashminDungrani** [microsoft/vscode#93065]
i am using vscode version 1.43.1 in Linux os
Settings Sync option not showing but release note shows that feature

**Comment by gjsjohnmurray** [comment]
Please look more closely at those release notes. This feature is currently only available in the Insiders build, 1.44. This is available for anyone to download and install. It coexists fine with the regular release (currently 1.43.1).

**Comment by RashminDungrani** [comment]
### no option from vscode sync

![Screenshot from 2020-03-20 11-21-20](https://user-images.githubusercontent.com/48521608/77139770-4ea3f880-6a9d-11ea-9968-15bd856b307f.png)

**Comment by RashminDungrani** [comment]
> Please look more closely at those release notes. This feature is currently only available in the Insiders build, 1.44. This is available for anyone to download and install. It coexists fine with the regular release (currently 1.43.1).

okok 😊
