### ISSUE TITLE
[Bug Report] Unexpected result during solving multi-line conflicts

### ISSUE THREAD

**Issue by Jabyn** [microsoft/vscode#93069]
- VSCode Version: 1.43
- OS Version: Fedora

Steps to Reproduce:

1. use `git pull` to pull a remote repository, which can trigger a lot of conflicts in a source file(e.g, helloworld.c), and the conflicts distributes in different lines.
2. solve the conflict using vscode, you have three choices to select: keep HEAD, incoming or both.
3. after you choose a solution for the first conflict, you click the selections for the second conflict, you will find the second will not be solved as you imagine. For example, I choose keep incoming for the second conflicts, it just insert `>>` or `====` in the end of original text, and the conflict still exists, except some useless contents are inserted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Screenshots or code sample would help...
