### ISSUE TITLE
QuickNav: Do not hide input box when already visible

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#93071]
Issue Type: <b>Bug</b>

- Ctrl + P, holding Ctrl -> Input box is shown.
- Ctrl + P -> Input box disappears, making the UI jump.

Should the input box stay when it is already shown?

VS Code version: Code - Insiders 1.44.0-insider (5d18ad4c5902e3bddbc9f78da82dfc2ac349e908, 2020-03-20T05:48:33.375Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (3.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.1.1
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-pull-request-github|Git|0.15.0
rest-client|hum|0.23.2
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.0.0
remote-containers|ms-|0.108.0
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
github-issues-prs|ms-|0.9.2
js-debug-nightly|ms-|2020.1.43263
debugger-for-chrome|msj|4.12.6
vscode-versionlens|pfl|0.25.0
vscode-yaml|red|0.7.2
vscode-open-in-github|sys|1.13.0
vscodeintellicode|Vis|1.2.6

</details>

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/72a381699f549b3f1c7c38b2b9a6d9a1de06f603
