### ISSUE TITLE
Bad use of commands argument processor 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93070]
Looks like no command from extension was working anymore in today's insider build.

Fix in https://github.com/microsoft/vscode/commit/64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed

As a reward, you can write an integration test that checks this works fine for the future 👍

**Comment by rebornix** [comment]
It's hard to write integration test to validate command arguments as the command execution needs to be invoked from the UI, for example, click event on a tree item, click on codelens, etc. It would be tricky to do so in integration tests so I wrote a smoke test instead.
