### ISSUE TITLE
Highlight error for function named 'is'

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#9307]
- VSCode Version: 1.3.1
- tsc: 2.0.0
- OS Version: Windows 2012 R2

![image](https://cloud.githubusercontent.com/assets/3254987/16858260/87ce8f04-49da-11e6-9a26-50f3169d594f.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#229
