### ISSUE TITLE
Extension icons disappear

### ISSUE THREAD

**Issue by dbalosetti** [microsoft/vscode#93073]
Issue Type: <b>Bug</b>

I canno't see my extension installed icons, on mouse over i can click on it but icons have disappeared

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (2.10GB free)|
|Process Argv|C:\Progetti\CarliSalesforce\fllicarli\workspace.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|10.2.1
quickOpenSelection|fin|1.1.0
auto-rename-tag|for|0.1.1
salesforce-commerce-cloud-productivity-pack|gkk|1.0.2
beautify|Hoo|1.5.0
js-patterns-snippets|nik|0.0.5
require-cartridge-resolve|pik|1.8.0
subtle-brackets|raf|3.0.0
trailing-spaces|sha|0.3.1
prophet|Sqr|1.2.46

</details>

**Comment by aeschli** [comment]
Can you add a screenshot and steps to reproduce?

**Comment by dbalosetti** [comment]
Yes sure, as you can see mouse over show the title of the extension but no icon

![Error](https://user-images.githubusercontent.com/15086430/77166251-35f30d00-6ab4-11ea-870b-7434a9010770.png)

**Comment by karineriquena** [comment]
I am having the same issue.
![image](https://user-images.githubusercontent.com/23150778/77318031-109c1400-6ceb-11ea-892a-57abe499cae8.png)
![image](https://user-images.githubusercontent.com/23150778/77319249-404c1b80-6ced-11ea-88e4-b30a5b6689cf.png)

**Comment by sandy081** [comment]
- Does it reproduce if you reload the window?
- Can you please try using fresh user data dir. Start code from command line as follows
`code --user-data-dir <path to a temp user data dir>`
- Open Developer tools (Developer: Toggle Developer Tools). Go to elements tab and inspect the element. Let me know where the icons are located. See eg:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/10746682/77729242-772c7500-6ffe-11ea-8fb3-3c9205e65062.png">

**Comment by sandy081** [comment]
/duplicate


https://github.com/microsoft/vscode/issues/92323
