### ISSUE TITLE
1.40.2之后的版本，该功能无效

### ISSUE THREAD

**Issue by anykk** [microsoft/vscode#93077]
Issue Type: <b>Feature Request</b>

File a:
module.exports = {
/** info */
  info:'a'
}

file b:
const StructA = require('./a');

/** @type {StructA['info'] */
let aInfo = '';

1.40.2及之后的版本，这种写法无效，望修复

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Also, you're on an old VS Code version. Please test using the latest VS code version
