### ISSUE TITLE
VS code uninstalled itself completely on closing open windows?!

### ISSUE THREAD

**Issue by waleedrana777** [microsoft/vscode#93072]
It left no trace anywhere, even the pinned shortcut from start gave an option to be deleted because the program was not found 🙄😐

**Comment by joaovbs96** [comment]
Same here! And this is like... the 3rd or 4th time this happened. It feels like every few months this issue comes up to me.

**Comment by VirtualAirwaves** [comment]
This happened to me too, on both my laptop and my desktop machine!

**Comment by s7ck** [comment]
Windows 10 Pro
10.0.18362 Build 18362

This just happened to me as well. This morning I was using Code for some Python work. Later I received a notification that there was a Git update available. I accepted it. Once it was completed, I shutdown for a couple of hours. Once I came back and booted up, Code is missing. The install directory still exists but it only contains the following files:
`
bin
    code
    code.cmd

tools
    inno_updater.exe
    vcruntime140.dll

chrome_100_percent.pak
chrome_200_percent.pak
unins000.dat
unins000.exe
unins000.msg
`
bin/code was modified on 3/18/2020 and contains a shell script.
bin/code.cmd also contains a shell script last modified on the 3/18/2020.

The shortcut to the app is now dead, but it does show up as an application I can uninstall in Add/Remove Programs.

**Comment by joaomoreno** [comment]
Somehow the background updater process seems broken on your machines. 
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by waleedrana777** [comment]
You are asking me to disable my windows updates?! This really is not a solution and if so until when? I can't do it as long as I have to keep vscode in my computer. Even if i do so, the issue is so random it happens god knows when! Also i don't know how to set it to false other than completely turning off updates from my windows settings. How should i do it? Thanks! from terminal and with what command? Thanks

**Comment by joaomoreno** [comment]
No, to disable the feature that VS Code is able to update itself in the background. Please go to VS Code settings and search for that setting name.

**Comment by s7ck** [comment]
This just happened to me AGAIN yesterday. What information do you need? I'll give you anything you need to make this stop.

**Comment by waleedrana777** [comment]
I set that to false just now. Sorry i was busy. Could not keep up! However yesterday my VS code updated itself in the background just fine (!! then it was set to true )and does not seem to be broken in this install. This issue is so random and many people have this issue! Thanks

**Comment by rjmxtechnology** [comment]
This just happened to me today, ridiculous. I did nothing to prompt it either. This needs to be fixed

**Comment by s7ck** [comment]
This just happened again to me this morning. It's looking like once every 5-7 days at this point.

**Comment by VirtualAirwaves** [comment]
This keeps happening. Happened again today.

**Comment by arpitkushwaha** [comment]
It is happening with me too for the past two weeks. It completely uninstalls itself whenever I install it. The same thing is happening again and again, it is a mess.

**Comment by VirtualAirwaves** [comment]
Clearly this isn't happening for everyone. I wonder if there's a plugin we're using that's causing this.

**Comment by waleedrana777** [comment]
> Somehow the background updater process seems broken on your machines.
> Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

Please fix this process!!!

**Comment by Salamafet** [comment]
Same problem. Last week and now today.

**Comment by waleedrana777** [comment]
Please file a new issue so your issue can be resolved. This one seems to be closed and may not get any response. I originally filed the isse

**Comment by jay-dimock** [comment]
This happened to me today for the 3rd time. Very annoying. I went ahead and disabled background updates and also disabled auto update for extensions. Hopefully that will fix it but jeez! It should not be happening, period.

**Comment by rjmxtechnology** [comment]
> 
> 
> This happened to me today for the 3rd time. Very annoying. I went ahead and disabled background updates and also disabled auto update for extensions. Hopefully that will fix it but jeez! It should not be happening, period.

Disabling the background updates seemed to fix it for me, but it shouldn't be happening to begin with, very frustrating

**Comment by UBrainDev** [comment]
It also happened to me, I stopped using VScode and now it seems to have uninstalled itself, but after further investigations, I found the reason: while the software was doing an update, I stopped my computer and all VScode files are now gone. This is why it happened to me, maybe it's the same thing for you.

**Comment by KDCinfo** [comment]
This has happened to me at least five or six times in the last two to three months (and again last night). But for me, it always happens when I exit VS Code. 

Every now and then, when I try to exit VS Code, it kicks off an update. After a minute, the update then throws an error (saying it can't access a file or something (---because it's locked by Windows)) for which "retry" doesn't work (even after closing everything else). So, you end up having to hit "cancel." But in hitting cancel, it's already been uninstalled, so..., I reboot to clear the Windows locks, re-download VS Code, and then reinstall VS Code.

**Comment by eyashi** [comment]
> It also happened to me, I stopped using VScode and now it seems to have uninstalled itself, but after further investigations, I found the reason: while the software was doing an update, I stopped my computer and all VScode files are now gone. This is why it happened to me, maybe it's the same thing for you.

(Windows 10 Enterprise report, Version 1909 Build 18363.778)
Found this thread after VSCode deleted itself on my computer. The is approximately what happened to me, but the _reason_ I had to restart my computer was because it was brought to a halt by Anti-malware Service Executable freaking out and eating 100% of my CPU.  That has never happened on this computer, and I'm reasonably suspicious that it was the VSCode instance being installed in the background that made Windows freak out.

Going to reinstall now, hopefully this doesn't happen as frequently as some people are reporting.

**Comment by r0hnx** [comment]
Just opened my windows only to see that VSCode is gone. Version 1903 OS Build 19013.1122

**Comment by VirtualAirwaves** [comment]
I had the exact same experience:

"Just opened my windows only to see that VSCode is gone. Version 1903 OS Build 19013.1122"

**Comment by CousinOkri** [comment]
This issue's been happening to me as well. VS Code uninstalls itself every couple of days after a failed update attempt.

**Comment by VirtualAirwaves** [comment]
I guess we'll have to wait 'til it happens to someone on the VS Code team for it to be fixed. I know it doesn't happen to everyone. And it only happens on one of my 3 machines (but they're all imaged the same way!). I'm wondering if it has to do with an extension. I have the Erlang, Elixir, and Elm extensions installed. Does everyone else here?

**Comment by KDCinfo** [comment]
> I have the Erlang, Elixir, and Elm extensions installed. Does everyone else here?

I'm not, and have never run any of those extensions. Based on your comment, I went through my extensions, and my current extensions include: [**Better Comments**], [**Dart**], [**Flutter**], [**HTML CSS Support**], and [**Todo Tree**]. And while I was in there, I also just now _uninstalled_ [**ES7 React/Redux/GraphpQL/React-Native snippets**], [**Laravel 5 Snippets**], and [**Laravel Blade Snipppets**]. And I just now _disabled_ [**Live Server**]. Will see what the future brings. :)

**Comment by VirtualAirwaves** [comment]
I had the upgrade fail on another machine today with the same can't move file problem. I don't think it's an extension anymore.  I keep my machines on the happy path, it's a licensed proper copy of Windows 10 Pro. 

When the failure happens, I just reboot the machine and reinstall VS Code from the installer

I tried running the filesystem permission repair tools here:  https://support.microsoft.com/en-us/help/17590/automatically-diagnose-and-repair-windows-file-and-folder-problems and then the DISM/sfc stuff (Don't run these without reading the docs and backing up!)

```
DISM.exe /Online /Cleanup-image /Restorehealth
sfc /scannow
```

But I don't expect that to fix anything.

The only other "non-happy path" things on my system are Malware Bytes premium version (in addition to Windows Defender) and Acronis True Image which has some sort of anti-ransomware thing built in that sometimes triggers. However they notify when they block an operation and neither one complained during the VS Code update. However, next time I see that the "reload to update" red dot is lit in VS Code, I'm going to try disabling both of these before telling it to update.

**Comment by jay-dimock** [comment]
> This happened to me today for the 3rd time. Very annoying. I went ahead and disabled background updates and also disabled auto update for extensions. Hopefully that will fix it but jeez! It should not be happening, period.

Today's update succeeded. As stated earlier, I had already disabled background updates.
Here's how I handled the update today: 

- Saw a popup message saying I needed to restart VS Code to install updates. Rather than clicking the button to restart the app & install, I shut down all instances of VS Code (I often have multiple), then re-launched. Still saw the "you need to update" message.
- Clicked the update button. 
- The update was successful. 

Time will tell if this approach always works. Will also test next time to see whether it works without taking the manual step of shutting down all instances.

**Comment by jay-dimock** [comment]
> 
> The only other "non-happy path" things on my system are Malware Bytes premium version (in addition to Windows Defender) and Acronis True Image which has some sort of anti-ransomware thing built in that sometimes triggers. However they notify when they block an operation and neither one complained during the VS Code update. Still, next time I see that the "reload to update" red dot is lit in VS Code, I'm going to try disabling both of these before telling it to update.

I have the same combo of premium MalwareBytes & Windows Defender. Per my recent post, I was able to update successfully today without disabling either of those. I think the key is disabling background updates, but maybe also shutting down multiple instances manually.
