### ISSUE TITLE
Search does not always respect .gitignore in subdirectories

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#93079]
- VSCode Version: 1.43.1
- OS Version: 16.04.5

I created a bug report previously, but back then I could not reproduce it, see https://github.com/microsoft/vscode/issues/89591

I experienced this problem again and now believe I know how to reproduce it.

1. Have a `.gitignore` in a root directory (with some ignores) and then a `.gitignore` in a sub-directory that might look like this:
```.gitignore
/target/
```
2. Searching now yields no results in the `/target/` directory
3. Click the `Use Exclude Settings and Ignore Files` (to disable it) and search, it should show results in the `/target/` directory.
4. Enable  `Use Exclude Settings and Ignore Files` and search again. It now still shows results in the `/target/` directory.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Did you open some of those files after step 3? If so you will always see results in files that are open in editors.

**Comment by thernstig** [comment]
Entirely possible, and that also makes sense to me. I guess again I'll have to close (and potentially re-open) if I experience this again. Feel like I'm taking too much of your time now.

**Comment by roblourens** [comment]
No worries, it's always possible that there are bugs too
