### ISSUE TITLE
screen crash when floating another window over VSCode

### ISSUE THREAD

**Issue by ReDvGaMe** [microsoft/vscode#93076]
Issue Type: <b>Bug</b>

Scrolling or floating another window on the vscode causes screen breaks like screenshots  

![vscode](https://user-images.githubusercontent.com/32252062/77150259-d65a2900-6ad6-11ea-89c5-c985f54790a0.PNG)

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.85GB (16.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
mdmath|goe|2.4.0
vscode-language-pack-ko|MS-|1.43.6
vscode-print|pdc|0.7.14

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Can you try our exploration build https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 and see if the issue repros.

Also if the issue is present, can you try with hw acceleration disabled following https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Thanks!
