### ISSUE TITLE
保存文件存在卡死情况

### ISSUE THREAD

**Issue by iimeepo** [microsoft/vscode#93080]
使用了'Vetur', 'ESLint'两个扩展配置了vue文件语法检查，保存时自动fix，经常会出现卡死，通知内容如下：
正在保存“index.vue”: 正在从“'Vetur', 'ESLint'”获取代码操作([配置](命令: workbench.action.openSettings?%5B%22editor.codeActionsOnSave%22%5D))。

![image](https://user-images.githubusercontent.com/20764007/77130483-17c8e500-6a93-11ea-8ac9-2f29d4b4d2f6.png)

**Comment by janbaltus** [comment]
Please test using  1.43.11 LP version.
Should be caused by overtranslated  command: https://github.com/microsoft/vscode-loc/commit/3b7dc489ad66b9667dea981622c02efb2666615e#diff-a1879ac213322ca36c7ba7f9d47a6ba5

**Comment by iimeepo** [comment]
Thank you very much. I'm going to try it. I'm looking forward to updating this issue in the next version!

**Comment by mrtangdong** [comment]
@iimeepo  是否是你同时开启了editor.formatOnSave 和 editor.codeActionsOnSave， 我怀疑如果你只要eslint的话 ，只要开启editor.codeActionsOnSave就可以了。这样就不会去走Vetur的情况
