### ISSUE TITLE
Git branch in VS Code doesn't update

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/vscode#93083]
- VSCode Version: 1.43.1
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Switch git branch from anywhere except VS Code's built-in UI, e.g. from a console or an extension, in my case [git-graph](https://github.com/mhutchie/vscode-git-graph).
2. The active branch name displayed (in two places) in VS Code's UI doesn't update.

Best illustrated with a GIF:

![image](https://user-images.githubusercontent.com/103348/77150441-2fed3400-6a94-11ea-9ba0-22dcbb863f6b.gif)

I initially filed this as a [bug report against the extension](https://github.com/mhutchie/vscode-git-graph/issues/280#event-3148646105) I'm using, and the author [explained](https://github.com/mhutchie/vscode-git-graph/issues/280#issuecomment-601614546) why he can't address this.

Likely this and similar issues affect all VS Code extensions that perform Git operations, as well as any user manually performing Git operations from a console.

I don't think there's any reason why this couldn't be improved - for example, I've never had similar issues with JetBrains IDEs. (I understand that's an entirely different platform, but JetBrains IDEs have to deal with the same problems as far as monitoring the file-system and git for changes, and they do so successfully under at least Ubuntu, Windows and Mac OS, that I know of.)

Possibly related to #36343.

**Does this issue occur when all extensions are disabled?**

Well, yes/no... with no extensions enabled, there ins't much else that can affect the state of the git respository - however, it does occur when manually doing git commands from a console.

**Comment by gjsjohnmurray** [comment]
See also #92431

**Comment by joaomoreno** [comment]
Please go through the following steps:

1. Run `Git: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Make some file changes and wait 10-20 seconds
4. Paste the whole output here

Thanks!

**Comment by mindplay-dk** [comment]
@joaomoreno sorry, but I lost my Ubuntu machine, and I can't reproduce the issue on my Windows machine. My Ubuntu system was a stock x64 Ubuntu 19.10, if that's any help...

**Comment by joaomoreno** [comment]
Oh I see now. The status bar shows the details of the *last focused repo*. If you were to focus the `app` repo, you'd see the right branch down there.
