### ISSUE TITLE
new quick open breaks customisations

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93084]
I have below keybinding which allow me to open file pick with `cmd+e`. The pressing `cmd+e` repeatedly selects entries down in this list. With new quick input I see two bugs

1. :bug: Pressing `cmd+e` goes into the input-less nav mode
1. :bug: The input-less nav mode doesn't accept arrow keys

```
{
	"key": "cmd+e",
	"command": "workbench.action.quickOpen"
},
{
	"key": "cmd+e",
	"command": "workbench.action.quickOpenNavigateNext",
	"when": "inQuickOpen"
},
```

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/72a381699f549b3f1c7c38b2b9a6d9a1de06f603
