### ISSUE TITLE
SemanticTokensBuilder#push is order sensitive

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93088]
Only after trail and error and I have realized that `SemanticTokensBuilder#push` must be called in order. E.g in my sample I traverse an AST but some container nodes are seens before child nodes, e.g the operator of a binary expression is seen before seeing the left and right nodes. Now, adding semantic tokens in that traversal order doesn't work and I need to collect them, sort them, and then feed the builder. IMO that defeats the point of having a the builder and it should

- cook the data (resort) when calling `build`
- or at least throw an error when being used incorrect

**Comment by alexdima** [comment]
Done via de1f8e5d9b344942d1289586b65f75d18afe1032
