### ISSUE TITLE
 The scroll bar on the right side of the command line is displayed abnormally

### ISSUE THREAD

**Issue by xoeaza** [microsoft/vscode#93086]
Issue Type: <b>Bug</b>

sometimes the scroll bar on the right side  trigger the wrong display

just as the pictrue show

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
vscode-ant-design-vue-helper|ant|1.0.6
vscode-styled-jsx|bla|1.5.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-faker|dee|1.3.0
es7-react-js-snippets|dsz|2.7.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.5.0
prettier-vscode|esb|3.20.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
terminal|for|0.0.10
rest-client|hum|0.23.2
search-node-modules|jas|1.3.0
autofilename|Jer|0.1.3
docthis|joe|0.7.1
vscode-gutter-preview|kis|0.25.0
vscode-filesize|mkx|2.1.3
vscode-csscomb|mrm|5.3.0
vscode-language-pack-zh-hans|MS-|1.43.9
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.2
vscode-leetcode|she|0.16.1
svg-preview|Sim|2.8.3
code-spell-checker|str|1.8.0
open-in-browser|tec|2.0.0
latex-support|tor|3.1.0
codelf|unb|11.7.0
quokka-vscode|Wal|1.0.284
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

![Jietu20200320-192241](https://user-images.githubusercontent.com/15125676/77159376-33a6a800-6ae0-11ea-88fa-7d9ee5013923.jpg)

**Comment by xoeaza** [comment]
[https://user-images.githubusercontent.com/15125676/77159376-33a6a800-6ae0-11ea-88fa-7d9ee5013923.jpg](url)

**Comment by xoeaza** [comment]
https://user-images.githubusercontent.com/15125676/77159376-33a6a800-6ae0-11ea-88fa-7d9ee5013923.jpg

**Comment by gjsjohnmurray** [comment]
@xoeaxa Perhaps a dup of #92721. If so please close this one and follow that one.

**Comment by Tyriar** [comment]
Yes looks like it

/duplicate
