### ISSUE TITLE
How do we completely remove all associations of the new 3-16-20 VSCode install with the latest Catalina release and Git?

### ISSUE THREAD

**Issue by rolandrgarceau** [microsoft/vscode#93094]
Issue Type: <b>Bug</b>

This may not be a bug I don't know. I don't know If I have VSCode for mac. I have a MBP and downloaded the installer from your website 3-18-20. It resides in my downloads directory and is not in the applications directory. I want to completely uninstall it from my machine and make sure their is no kept information about my git version control as I cannot use terminal to upload progress of any repo work right now. It appears vscode is not installed and runs from the downloads, as I used spotlight serarch to find the icon and then drug it to the dock, then used the dock to open the containing folder. The guiides does not address this, it talks about dragging it to the trash from applications and has links to github that corroborate that. What all is needed to completely clean this from my system today, as I noticed the new version is as of 3-16-20. Please do not send older guides. Thanks.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
File associations still there: Maybe this helps:  https://apple.stackexchange.com/questions/246745/how-to-reset-file-icons-associated-with-default-program-on-el-capitan

Remove all VSCode related meta data: https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec
