### ISSUE TITLE
Unable to install powershell extension in constrained language mode

### ISSUE THREAD

**Issue by CBkp599** [microsoft/vscode#93098]
Issue Type: <b>Bug</b>

Hi, 
Our powershell is locked down to only contstrained language mode by Group Policy :
$ExecutionContext.SessionState.LanguageMode = ConstrainedLanguage

In VS Code I try to install the PowerShell  extension but it fails with 'The Language Service could not be started' 
Log :
Exception encountered starting EditorServices. Exception logged in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 247 in EndProcessing:
System.Management.Automation.CmdletInvocationException: Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator. ---> System.NotSupportedException: Cannot dot-source this command because it was defined in a different language mode. To invoke this
command without importing its contents, omit the '.' operator.

I'm using VS Code 1.43.1

Can you advise please on this please ? 
Thanks

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.3.0

</details>

**Comment by aeschli** [comment]
Pleas file this against the Powershell extension:
https://github.com/powershell/vscode-powershell/issues
