### ISSUE TITLE
Arrow down key doesn't work in notebook suggest

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93099]
* open notebook
* trigger intelliSense on the last line of a code cell 
* arrow down to select an item
* 🐛 the next cell is focused

**Comment by rebornix** [comment]
I bind actions for arrow up and down then the cursor is at the first line or last line to move to previous/next cells. It doesn't know the Suggest Widget is open and the Suggest Widget should be the one to accept arrow keys.

My current fix is lowering the weight of these actions so the Suggest Actions can override them. I'm wondering if we should have a context key for `suggestWidgetVisible`. We used to have similar requests for Vim.

**Comment by jrieken** [comment]
> I'm wondering if we should have a context key for suggestWidgetVisible. We used to have similar requests for Vim.

That key exists but I don't know if we should use it in notebook commands. That's usually the last resort since there might be other commands also using arrow up/down. I think the weight change is good
