### ISSUE TITLE
struct sigaction (from signal.h) not recognized by vs code

### ISSUE THREAD

**Issue by kiko-g** [microsoft/vscode#93096]
Issue Type: <b>Bug</b>

struct *sigaction* is not recognized by vs code and it doesn't seem to be any setting or extension that i can tweak

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (22.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2001)|
|Memory (System)|31.84GB (22.99GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.27.0-insiders3
pdf|tom|0.5.1
html-snippets|abu|0.2.1
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.4
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.0.1
prolog|reb|0.0.4
material-theme|zhu|3.2.4

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Can you add a screenshot to clarify what exactly is not working.
Syntax highlighting? Or is it a validation error?

**Comment by kiko-g** [comment]
It's syntax highlighting and sigset_t is also not recognized

![image](https://user-images.githubusercontent.com/40745490/77253923-adac6d80-6c55-11ea-9ee7-8fe8a16bc138.png)
![image](https://user-images.githubusercontent.com/40745490/77253935-ba30c600-6c55-11ea-8b59-37b53ea0931e.png)

**Comment by aeschli** [comment]
That's a validation error. Please file the issue against https://github.com/microsoft/vscode-cpptools/issues
