### ISSUE TITLE
Extension node takes unreasonable high CPU

### ISSUE THREAD

**Issue by ritou11** [microsoft/vscode#93092]
Issue Type: <b>Bug</b>

The extension node began to take unreasonable high CPU. I'm working on an tex document using Latex-Workshop.
Simultaneously, other problems occurred after VScode started a while:
1) Cannot input `return` but have to use `shift+return`
2) Extremely slow to save a file

Bug occurred since 1.43.1
Also I have `"webview.experimental.useExternalEndpoint": true` as suggested in https://github.com/microsoft/vscode/issues/92420#issuecomment-598907473

Thanks.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv| ----- |
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
auto-rename-tag|for|0.1.1
latex-workshop|Jam|8.7.2
docthis|joe|0.7.1
language-julia|jul|0.14.18
stata-enhanced|kyl|1.6.1
vscode-docker|ms-|1.0.0
python|ms-|2020.3.69010
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
cpptools|ms-|0.26.3
Go|ms-|0.13.1
vsliveshare|ms-|1.0.1783
latex-utilities|tec|0.3.6
vscode-icons|vsc|10.0.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
