### ISSUE TITLE
Can't execute extension tests anymore

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#93097]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.44.0-insider (64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed, 2020-03-20T08:31:26.505Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.85GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
spellright|ban|3.0.50
vscode-eslint|dba|2.1.1
githistory|don|0.6.3
tsl-problem-matcher|eam|0.1.1
vscode-pull-request-github-insiders|Git|2020.3.26823
vscode-guid|hea|1.4.19
copy-github-url|mat|0.6.0
vscode-docker|ms-|1.0.0
vscode-language-pack-de|MS-|1.43.6
vscode-language-pack-en-GB|MS-|1.43.6
csharp|ms-|1.21.15
remote-containers|ms-|0.108.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-ssh-explorer|ms-|0.50.0
remote-wsl|ms-|0.44.1
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.8
vscode-lsif-win32-x64|ms-|0.4.4
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
vscode-icons|vsc|10.0.0

(1 theme extensions excluded)

</details>

Steps to reproduce:

- create an extension running yo code (choose TS, npm)
- cd into the directory. In my case `exttest`
- npm run compile
- npm test

Test hangs like
```
VSCode\Playgrounds\exttest> npm run test

> exttest@0.0.1 pretest C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest
> npm run compile && npm run lint


> exttest@0.0.1 compile C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest
> tsc -p ./


> exttest@0.0.1 lint C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest
> eslint src --ext ts


> exttest@0.0.1 test C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest
> node ./out/test/runTest.js

Found .vscode-test/vscode-1.43.1. Skipping download.


Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2020-03-20T13:32:33.568Z] update#setState idle

[main 2020-03-20T13:33:03.576Z] update#setState checking for updates

[main 2020-03-20T13:33:04.463Z] update#setState idle
```

**Comment by dbaeumer** [comment]
What works from the command line for me  is:

```
& 'C:\Users\dirkb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' --extensionDevelopmentPath=C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest --extensionTestsPath=C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest\out\test\suite\index
```

**Comment by dbaeumer** [comment]
In contrast this doesn't work
```
 & 'C:\Users\dirkb\AppData\Local\Programs\Microsoft VS Code\Code.exe' --extensionDevelopmentPath=C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest --extensionTestsPath=C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest\out\test\suite\index
```

Interestingly the process tree gets stuck with four processes

Root
```
"C:\Users\dirkb\AppData\Local\Programs\Microsoft VS Code\Code.exe" --extensionDevelopmentPath=C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest --extensionTestsPath=C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\exttest\out\test\suite\index
```

Child one

```
"C:\Users\dirkb\AppData\Local\Programs\Microsoft VS Code\Code.exe" --type=gpu-process --field-trial-handle=1732,228985947532180791,3569279775043352384,131072 --disable-features=LayoutNG,PictureInPicture,SpareRendererForSitePerProcess --disable-color-correct-rendering --gpu-preferences=KAAAAAAAAADgAAAwAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAFAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAQAAAAUAAAAQAAAAAAAAAAEAAAAGAAAA --service-request-channel-token=3443294701897226939 --mojo-platform-channel-handle=1764 --ignored=" --type=renderer " /prefetch:2
```

Child two

```
"C:\Users\dirkb\AppData\Local\Programs\Microsoft VS Code\Code.exe" --type=utility --field-trial-handle=1732,228985947532180791,3569279775043352384,131072 --disable-features=LayoutNG,PictureInPicture,SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=network --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --service-request-channel-token=15648213606867747812 --mojo-platform-channel-handle=2164 /prefetch:8
```

Child Three
```
"C:\Users\dirkb\AppData\Local\Programs\Microsoft VS Code\Code.exe" --type=renderer --disable-color-correct-rendering --field-trial-handle=1732,228985947532180791,3569279775043352384,131072 --disable-features=LayoutNG,PictureInPicture,SpareRendererForSitePerProcess --lang=en-US --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-user-model-id=Microsoft.VisualStudioCode --app-path="C:\Users\dirkb\AppData\Local\Programs\Microsoft VS Code\resources\app" --node-integration --no-sandbox --no-zygote --background-color=#1e2324 --disable-blink-features=Auxclick --device-scale-factor=1.5 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=5648122239649487306 --renderer-client-id=5 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=2704 /prefetch:1
```

**Comment by dbaeumer** [comment]
Interestingly three is no shared process running which I think is responsible for updating hence things get stuck.

**Comment by dbaeumer** [comment]
If I tweak by runTests to instruct using insiders everything works

```
		await runTests({
			extensionDevelopmentPath,
			extensionTestsPath,
			version: 'insiders'
		});
```

Using any stable build (even 1.41.1) doesn't work anymore.

**Comment by bpasero** [comment]
I cannot reproduce on macOS:

```
Extension Test Suite

    ✓ Sample test

  1 passing (23ms)

Error: The specified item could not be found in the keychain.

Exit code:   0
Done

```

**Comment by bpasero** [comment]
Works fine on Windows too.

**Comment by octref** [comment]
I cannot repro this locally on macOS either. Azure DevOps and Travis work fine as well: 

- https://dev.azure.com/vscode/vscode-test/_build/results?buildId=39426&view=results
- https://travis-ci.org/github/microsoft/vscode-test/builds/664954352

Are you running this on CLI when you already have Stable open?

**Comment by dbaeumer** [comment]
No, I run it locally on my machine. Any logs I could look at to find out was is going wrong. Everything works with Insider but not Stable

**Comment by dbaeumer** [comment]
After quite some digging and using restore point I was able to find out what happened.

- I installed a preview version of VS (16.6)
- this installed a new version of the VS installer (which is an Electron app)
- I don't know how but when running the test using stable for some reasons binaries from the VS installer were used (see the warning `Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.`). This doesn't happen when running test normally. I guess the VS installer ships with an older version of Electron

After removing VS 16.6 (reverting to a previous restore point) everything worked again. IMO the interesting question here is how this can happen since it might hit us in other scenarios as well.

@deepak1556 any idea?

**Comment by deepak1556** [comment]
I am not familiar with `vscode-test` but at a quick look it seems the executables for running tests are searched under `.vscode-test/..` https://github.com/microsoft/vscode-test/blob/master/lib/download.ts#L144 and also they specifically look for `Code.exe` on windows https://github.com/microsoft/vscode-test/blob/master/lib/util.ts#L62 .

I don't see how executable collision would happen in that case, can you share the process tree when you see its using `electron.exe` from VS installer ?

Also I don't see any `--sandbox` option passed in https://github.com/microsoft/vscode/issues/93097#issuecomment-601753195 , so not sure from where we picked that.

**Comment by dbaeumer** [comment]
Actually I restored the state on disk before I installed VS 16.6 to be able to continue working. However from trying to track this down I had the impression that the original executable is started correctly but that when we start the shared process that fails. The process tree I ended up with was this one https://github.com/microsoft/vscode/issues/93097#issuecomment-601753195

**Comment by deepak1556** [comment]
> I had the impression that the original executable is started correctly but that when we start the shared process that fails

How are we launching the shared process ? I don't see this process in the tree https://github.com/microsoft/vscode/issues/93097#issuecomment-601753195 , there is only the main, gpu, network and one renderer process.

> The process tree I ended up with was this one #93097 (comment)

That looks normal, I don't see anything odd there.

**Comment by dbaeumer** [comment]
@deepak1556 exactly. The other process never made it. I guess they got started and then terminated immediately (due to the working binaries) and therefore never showed up.
