### ISSUE TITLE
Quick pick: middle mouse results in weird selection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93090]
Steps to Reproduce:

1. enable quick input for quick open (`"workbench.quickOpen.enableExperimentalNewVersion": true`)
2. open the default picker for files
3. middle-mouse click into a file to open it in the background

=> 🐛 the item looks weird (old quick open was handling this better it seems)

![image](https://user-images.githubusercontent.com/900690/77164864-6c7b5880-6ab1-11ea-9301-ade2a358338d.png)

I think it should simply detect this and move focus back to the input field and not keep it in the list.

**Comment by chrmarti** [comment]
Middle-mouse click opens to the side and closes QuickAccess for me. Is there a setting for this?

**Comment by bpasero** [comment]
@chrmarti not for me, but you could programmatically prevent the selection from happening by commenting out this line:

https://github.com/microsoft/vscode/blob/8df646d3c5477b02737fc10343fa7cf0cc3f606b/src/vs/base/parts/quickinput/browser/quickInputList.ts#L329

**Comment by chrmarti** [comment]
@bpasero You added that line and it's called on right-click not middle-click.

I got confused using the Mac's trackpad. Using a proper mouse's middle-button works as you describe. I can pass the focus back to the text input for that.

**Comment by bpasero** [comment]
Thanks, seems to work fine 👍
