### ISSUE TITLE
El servicio de lenguaje TypeScript finalizó de forma inesperada cinco veces después de haberse iniciado y no se reiniciará.

### ISSUE THREAD

**Issue by ivanfretes** [microsoft/vscode#93106]
Issue Type: <b>Feature Request</b>

No se cuentas con mayores detalles, pero al parecer está relacionado con la transpiración a javascript.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 4.9.0-8-amd64

**Comment by gjsjohnmurray** [comment]
Please update to the current release, 1.43.1, then re-test.

**Comment by ivanfretes** [comment]
i updated the new version and solved me the problem, thks
