### ISSUE TITLE
Theme syntax highlighting broken after last update

### ISSUE THREAD

**Issue by Foxhoundn** [microsoft/vscode#93101]
- VSCode Version: Latest public
- OS Version: Latest MacOS

Steps to Reproduce:

1. Install my theme called `Synthax`

----

After the latest VSCode update, the syntax highlighting using my theme broke, as you can see on the gif below - the first few seconds is actually how it should look and looked before, but then it switches to the different highlighting that is weird. 

For example the `Room` class is being used as a type but is shown as the `class` type, which is something that worked fine before.

Why does it work correctly for the first few seconds / minute and then when `Initialising JS/TS language features` finishes, it changes to a different style?

![2020-03-20 16 18 41](https://user-images.githubusercontent.com/8861481/77178649-aa837700-6ac7-11ea-9b69-2564a6026f95.gif)

I actually like a lot of the changes in the new highlighting, but some of them do not make sense to me.

Thank you.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#semantic-highlighting

Sounds like you'd benefit from updating to 1.43.1 that came out earlier this week.

**Comment by Foxhoundn** [comment]
I see, thanks!
