### ISSUE TITLE
Dragging outline (a single view) from the sidebar to the activity bar provides no feedback but does something

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93104]

**Comment by sbatten** [comment]
this is fixed with custom view containers now being supported

**Comment by sbatten** [comment]
To Verify:
1. Drag outline from explorer to the activity bar
2. Ensure that dropping outline in the activity bar inserts a new custom view container holding outline.

**Comment by alexr00** [comment]
It works, but is it correct that the only way to get outline back into Explorer is to put it in the panel then move it back into explorer?

**Comment by sbatten** [comment]
No you should be able hover over the explorer icon until it opens up and then drop outline in the explorer viewlet.
