### ISSUE TITLE
Tkinter refuses to cooperate on closing and caused a crash once.

### ISSUE THREAD

**Issue by PlanMan1717** [microsoft/vscode#93107]
- VSCode Version: 1.44.0 Insider
- OS Version: Windows 10 Home

[problem.zip](https://github.com/microsoft/vscode/files/4360868/problem.zip)
contains the video of me attempting to close a tkinter window (not shown for some reason.)

and it did cause a crash once that happened before i could film it.
I could not recreate it, though.

**Comment by aeschli** [comment]
My understanding is that is issue should be filed against `tkinter`. How is VSCode related to the tkinter window?

Please reopen if you disagree
