### ISSUE TITLE
History entries navigation takes one extra navigate on start and end of history

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#93102]
- In the debug console, evaluate something, then `1+1` 3 times. 
- Press up, get `1+1`
- Press up again, get `1+1` again
- Press up again, get the previous history entry

Seems like it always reduces down to 2 entries, or there might be something else weird going on

**Comment by isidorn** [comment]
We are de-duplicating history entries which makes sense for me.
This is designed behavior 
What is the use case of seeing `1 + 1` 3 times in history?

**Comment by roblourens** [comment]
The bug is that I see it twice, when I should see it once

**Comment by isidorn** [comment]
@roblourens I can not repro.
What are you doing differnetly than me in this gif
Please note that I pressed up only two times at the end. Thus `1 + 1` is only once in history

![rob](https://user-images.githubusercontent.com/1926584/77185312-7dd45d00-6ad1-11ea-81ec-bd4aa173b229.gif)

**Comment by roblourens** [comment]
Hmm, extra steps

- Execute things as above
- Press up to go through history, it works
- Press down to go back
- Press down a couple extra times - I did this because I was expecting to get back to an empty input if I press down
- Then, I press up on `1+1` and nothing happens, it's still on `1+1`

![Mar-20-2020 09-58-32](https://user-images.githubusercontent.com/323878/77187242-64132580-6a91-11ea-89bb-8bc1b36de4e8.gif)

**Comment by isidorn** [comment]
Ok, the issue is when you reach the end of history up / down take an extra hit to get the previous or the next one.
Duplication is not related. Renaming this issue.
I am open for PRs that fix this
Code pointer https://github.com/microsoft/vscode/blob/0687d65b30a752cef32490bca7ca85f4b41015b2/src/vs/workbench/contrib/debug/browser/repl.ts#L235

Probably the historyNavigator has an issue at the end of history

**Comment by piraces** [comment]
Hello. I would like to contribute on this if you are open.

I will submit a PR as soon as I fix it :)

**Comment by isidorn** [comment]
To verify:
1. Start debugging, open debug console
2. Evaluate `1`, then evaluate `2`
3. Make sure pressing up gets you all the way back to the end of history in the debug console input
4. Make sure pressing down gets you immieadly to the previous history element. Thus no duplicatino happens
