### ISSUE TITLE
Language Detection does not identify virtual files as aspnetcorerazor

### ISSUE THREAD

**Issue by mjnorman** [microsoft/vscode#93116]
Issue Type: <b>Bug</b>

The autodetect language is not recognizing generated files such as  `FetchData.razor__virtual.html` as a Razor file, and in turn it is showing an errors for things that are valid in Razor such as 
```razor
<ConfirmDialog OnClick="@Delete"></ConfirmDialog>
```
The `@Delete` is being shown as a javascript/typescript error .
```
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.
```
I am able to work around these errors by including this in settings:
```json
    "files.associations": {
        ".razor_*": "aspnetcorerazor"
    }
```

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
razor-plus|aus|0.1.4
gitlens|eam|10.2.1
dotnet-test-explorer|for|0.7.1
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.21.15
vscode-concourse|Piv|1.16.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension - see https://github.com/microsoft/vscode/issues/92592#issuecomment-598682138 for a pointer
