### ISSUE TITLE
Editor no tab title area does not update

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93111]
1. Latest VS Code insiders
2. 	`"workbench.quickOpen.enableExperimentalNewVersion": true`, `"showTabs": false`
3. `Cmd + n`, open an `untitled` File
4. `Cmd + e`, choose some file, for example repl.ts, press enter
5. `repl.ts` is opened, but the no tab title area still has the `untitled` 🐛 

![Screenshot 2020-03-20 at 18 13 13](https://user-images.githubusercontent.com/1926584/77188556-79f70980-6ad6-11ea-8ddb-40ced1e093d3.png)

**Comment by bpasero** [comment]
Unrelated to new quick open, but boy, good catch because I saw this once and couldn't believe my eyes!

**Comment by isidorn** [comment]
Life is full of surprises!
Thanks for the quick fix
