### ISSUE TITLE
Be able to write longer git commit messages (e.g. paragraphs)

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#93117]
(Using VS Code version fe22a9645b44368865c0ba92e2fb881ff1afce94.)

I'd like to be able to write a few paragraphs under the main git commit message. I can do that with `git commit` on the command line, but not in VS Code.

I'd also like to be able to see the diffs of my commit while committing, so a modal would not be ideal, and the sidebar is too thin to add the text area into.

So I suggest adding a panel at the top or bottom of the window, perhaps in the same area the terminal emulator is. That might be fine, although ideally I'd prefer the text area at the top.

Thanks for listening to my suggestion. Hope you're having a good day, whoever reads this.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please post all the version information from your About dialog.

**Comment by sdegutis** [comment]
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
