### ISSUE TITLE
Feedback is missing for top element in activity bar 

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93114]
Try dropping a composite item above the topmost element in the activity bar
🐛 => no feedback

**Comment by sbatten** [comment]
To Verify:
1. Try dragging an activity bar icon above the topmost icon (e.g. search above explorer) and verify that there is an insert line above the topmost icon.

**Comment by mjbvz** [comment]
I verified the indicator shows up. However after I drop the item, the icons sometimes re-orders (putting the new item at the end). Is this a known issue or should I open a new bug?

**Comment by sbatten** [comment]
@mjbvz not a known issue, new bug please, preferably with a reliable repro
