### ISSUE TITLE
Allow toggle line comment accurately when language only support nested block comment

### ISSUE THREAD

**Issue by hackwaly** [microsoft/vscode#9311]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11 Beta

Steps to Reproduce:
1. Select a language mode which only support block comment. (eg. OCaml)
2. Write one line code contains a comment inline. (eg. `let x = 1 (* foo *)`)
3. Toggle line comment at that line. (eg. expect `(*let x = 1 (* foo *)*)`, but got `let x = 1 foo`)

If block comment can't be nested. We should not change the line `let x = 1 (* foo *)`, because we are toggling **LINE COMMENT**, not block comment.

**Comment by alexandrudima** [comment]
Not all languages allow for nested block comments. This is an information we don't have at this point in the comment lines command. We need to enrich the language configuration to include also a bit of information (a boolean) about nested block comments and then we can use that information to improve the behaviour.
