### ISSUE TITLE
New file saved using windows path format when in WSL mode

### ISSUE THREAD

**Issue by taha-yassine** [microsoft/vscode#93110]
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new file (ctrl+N)
2. Save file (ctrl+S)
3. Click on "Show Local"
4. Choose save location
5. Run some code (in my case a python script)

This is the error I get :
`/home/vodros/anaconda3/envs/bcom/bin/python: can't open file 'c:/Users/Taha/Documents/Projects/Playground/Untitled-1.py': [Errno 2] No such file or directory`

Windows path format is used and is not correctly parsed to its linux equivalent and this, I believe, is causing the error.

I don't know of it's the same issue as #24772 since when I hover over the file in the sidebar, it shows the file's path using the windows format. That sugggests that the bug is not caused by the python extension.
![image](https://user-images.githubusercontent.com/40228615/77187520-e96bf980-6ad4-11ea-9203-51f959f3d3db.png)

**Comment by aeschli** [comment]
In a remote window, the rich languages extensions run on the remote side. They have no access to local files.
The error message is not good and likely the Python extension didn't look at the URI it got (`vscode-local:///c:/Users/...`and just used fsPath on it.

**Comment by aeschli** [comment]
I created https://github.com/microsoft/vscode-python/issues/10694

**Comment by kimadeline** [comment]
Hi @aeschli 👋 

As @taha-yassine pointed out, this isn't specific to the Python extension for VS Code, I could reproduce it with the following steps and a JS file :

- Open folder in WSL
- Create a new JS file (ctrl+N)
- Save file (ctrl+S)
- Click on "Show Local"
- Pick a location where you want to save the file
- Debug view > Run and Debug > Node.js

Which fails:

![image](https://user-images.githubusercontent.com/51720070/77375058-a5bdfd80-6d29-11ea-941f-b51101cefec5.png)


When you click on "Show Local" when saving the file the breadcrumbs are updated to the local path:

![image](https://user-images.githubusercontent.com/51720070/77374820-f5e89000-6d28-11ea-8c55-1e6f48be41b0.png)

while if you double-click on the file in the file explorer it will show the WSL path:

![image](https://user-images.githubusercontent.com/51720070/77374827-fbde7100-6d28-11ea-83d0-2ac809782d71.png)

And running will work as expected:

![image](https://user-images.githubusercontent.com/51720070/77375116-cf772480-6d29-11ea-963e-03fe9c5fc4c4.png)

**Comment by weinand** [comment]
@taha-yassine and you can reproduce this problem with the latest stable version of VS Code (1.43)  too?

**Comment by weinand** [comment]
I can reproduce in VS Code 1.43. 

The problem is that the workspace lives in linux (via wsl) and most extensions are running there too (e.g. debuggers), but the newly created file in the editor lives on the Windows side.

With "Run and Debug" the debugger in linux is asked to debug a file living in Windows.
This is not supported.

You will see this limitations with all extension running on the linux side: they don't have access to resources on the Windows side. For example intellisense does not work in those files either.

**Comment by taha-yassine** [comment]
> I can reproduce in VS Code 1.43.
> 
> The problem is that the workspace lives in linux (via wsl) and most extensions are running there too (e.g. debuggers), but the newly created file in the editor lives on the Windows side.
> 
> With "Run and Debug" the debugger in linux is asked to debug a file living in Windows.
> This is not supported.
> 
> You will see this limitations with all extension running on the linux side: they don't have access to resources on the Windows side. For example intellisense does not work in those files either.
> 
> @aeschli @egamma please correct me if this assessment is wrong.

Since I created the file using and instance of VS Code connected to WSL, shouldn't the file live in linux ? I see no reason why it should be living on the Windows side.

**Comment by weinand** [comment]
The steps say:
> 3. Click on "Show Local"

With this the save dialog switches to the Windows side. So newly created file will be saved on the Windows (=local) side. 
Without the 'Click on "Show Local"' the file be saved on the linux side.

Why are you clicking on "Show Local" if you have no intentions to save locally?

**Comment by taha-yassine** [comment]
> Why are you clicking on "Show Local" if you have no intentions to save locally?

I wanted to bring up the save file dialog box to be able to choose where to save my file instead of manualy entering the path, but now I see the logic behind the "Show Local" button. I was just wondering what was the benefit of having a file saved on the Windows side when working with an instance of VS Code connected to WSL ?
My understanding is that it doesn't matter if it is saved on the windows or linux side as long as it's accessible from both. What matters is the path format, and since we're working with WSL, it only makes sense to have everything in linux format. Please enlighten me on this matter.

**Comment by weinand** [comment]
In neither mode of the Save dialog you have to "manually enter the path".
So switching to local mode does not give you anything in that regard.

Remote VS Code allows to save files locally because there are use cases where you want to have a single file open in your workbench that is not stored in the same location as all the other file of the workspace, e.g. a TODO list. 

But local (Windows) files in general are **not** accessible from the remote side (linux). So remote extensions do not have access to them. That's the way VS Code Remote works.
So don't save files locally if they should not live locally.

**Comment by taha-yassine** [comment]
Okay I got it, thank you !
