### ISSUE TITLE
'Please use yarn to install dependencies.' when using yarn

### ISSUE THREAD

**Issue by memark** [microsoft/vscode#93119]
Trying to install dependencies with yarn, which is installed globally via homebrew.
Yarn works perfectly for other projects.

- VSCode Version: latest master
- OS Version: Mac OS 10.15.3

Steps to Reproduce:

1. clone repo
2. run `yarn`

```
➜ node -v
v10.19.0

➜ yarn -v
1.22.4

➜ yarn
yarn install v1.22.4
$ node build/npm/preinstall.js
*** Please use yarn to install dependencies.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by aeschli** [comment]
What's the version of npm?

Can you edit https://github.com/microsoft/vscode/blob/88b1952cc498807bf66850f9643565f0d0bfe7ce/build/npm/preinstall.js#L27
and add a `console.log(process.env['npm_execpath'])`?

**Comment by memark** [comment]
```
➜ npm -v
6.13.4
```

Added the log statement, it gives
`/Users/memark/.yarn/releases/yarn-1.22.4.js`

**Comment by memark** [comment]
Thanks for a quick fix!
