### ISSUE TITLE
Expose theme color variables to webviews in JS

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93115]
I want to use theme colors in the flamegraph visualizer, but we can't use `var()`'s in the canvas' drawing API. I put together a [kind of hacky hook](https://github.com/microsoft/vscode-js-profile-visualizer/blob/master/src/common/client/useCssVariables.tsx) that regex-parses the variables from the `<html>` element, but it'd be nice to expose these more properly to the webview, perhaps through the VS Code API handle.

**Comment by mjbvz** [comment]
Can you use the dom apis for this: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#Values_in_JavaScript

**Comment by connor4312** [comment]
Yes, but that [forces a restyle and sometimes a relayout](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getcomputedstyle), which is quite computationally expensive.

**Comment by mjbvz** [comment]
I don't think the first example using `getPropertyValue` triggers this. You can call this on the root html element that has these inline

**Comment by connor4312** [comment]
Looks like you're right. That should work. Still maybe a good candidate for a utility library or set of typings so that people can get them in a safe manner :)

**Comment by connor4312** [comment]
I ended up making a small library with my variables boilerplate -- along with a codegen script that extracts and enumerates all the theme variables from the vscode repo: https://github.com/connor4312/vscode-webview-tools
