### ISSUE TITLE
'Unused variable' falsely reported in Javascript when `with` block is present

### ISSUE THREAD

**Issue by KernelDeimos** [microsoft/vscode#93124]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Declare some variables outside of a with block
- Use these variables inside the with block

vscode will report the variable is "unused". Commenting out the with block without modifying the code inside makes this message disappear.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.6.0

**Comment by mjbvz** [comment]
We don't support intellisense for `with` statements so many features may not work with it,
see https://github.com/microsoft/vscode/issues/92413#issuecomment-599857839
