### ISSUE TITLE
Add boolean setting to control whether editor should jump to active file in files list.

### ISSUE THREAD

**Issue by admorphit** [Microsoft/vscode#9312]
- VSCode Version: 1.3.1
- OS Version: 10.10.5

On large projects with many files and subdirectories, it can be annoying when switching between active files in the editor, **_also jumps to_** the actively selected file in the files list.

It would be great if the editor (preferably via a setting) only highlighted the active file in the files list **_without_** jumping to the file so as to keep current file list scroll position.

This would help when flipping between files in directory `A` and directory `Z`, while needing to keep an eye on structure of directory `A` in a large project where there are too many files between both directories for them to fit in same file list view.

Steps to Reproduce:

1. Open large project with many files and directories. 
2. Expand a directory near top of file list containing many files such that they fill the entire files list (ie. `node_modules` directory with many modules). Open a file in this directory.
3. Expand a directory near the bottom of the entire files list in a new tab.
4. Flip between the two files and notice the scroll position of files list changes.
5. There is no way to keep the scroll position of files list at the top.

**Comment by bpasero** [comment]
@admorphit did you try `"explorer.autoReveal": false`?

**Comment by admorphit** [comment]
Perfect, this does the trick @bpasero, thanks.
