### ISSUE TITLE
Ubuntu install vscode turn white in my mac Parallels Desktop

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [microsoft/vscode#93128]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by wangwenqiangGitHub** [comment]
1. 1.43.1
2.16.04

**Comment by wangwenqiangGitHub** [comment]
VSCode Version: 1.43.1
OS: Ubuntu 16.04

**Comment by wangwenqiangGitHub** [comment]
have already been solved

**Comment by aeschli** [comment]
I understand that the issue is solved now. Closing.
