### ISSUE TITLE
The visibleRanges of TextEditorVisibleRangesChangeEvents is not correct when chainging an activeTextEditor with clicking tabs.

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#93127]
Version: 1.44.0-insider
Commit: 64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed
Date: 2020-03-20T08:26:07.418Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Execute the following extension sample.
2. Open some files. TextEditorVisibleRangesChangeEvents are being fired when changing an activeTextEditor with clicking tabs.

Is this an intended behavior? Even if so, the visibleRanges are not appropriate since the TextEditor is not visible at all. Notice that the TextEditor of each event is a previous hidden TextEditor. 

![Mar-21-2020 09-19-22](https://user-images.githubusercontent.com/10665499/77215076-938b6600-6b55-11ea-9580-e31d3da6fe1d.gif)

```typescript
import * as path from 'path';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "helloworld-sample" is now active!');

	let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		vscode.window.showInformationMessage('Hello World!');
	});

	context.subscriptions.push(disposable);

	disposable = vscode.window.onDidChangeTextEditorVisibleRanges((e) => {
		vscode.window.showInformationMessage(`fired: ${path.basename(e.textEditor.document.fileName)}, ${JSON.stringify(e.visibleRanges)}`);
	 })
}

export function deactivate() {}
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@tamuratak I could not reproduce what you are describing.

I have changed your sample code to use `console.log` instead of the notifications, which get dismissed very easily:
```js
const vscode = require('vscode');
const path = require('path');

exports.activate = function(context) {
	vscode.window.onDidChangeTextEditorVisibleRanges((e) => {
		console.log(`fired: ${path.basename(e.textEditor.document.fileName)}, ${JSON.stringify(e.visibleRanges)}`);
	});
}
```

When I switch tabs I see a change event for the new tab being fired:

![Kapture 2020-03-30 at 15 39 46](https://user-images.githubusercontent.com/5047891/77918855-bed02c80-729c-11ea-884a-899e1e0582eb.gif)

**Comment by tamuratak** [comment]
Version: 1.44.0-insider
Commit: 13b38d2a494612ace32c4fb878824d6329d4c51e
Date: 2020-03-30T07:30:34.234Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

I have changed the sample code to use `console.log`.

``` typescript
import * as path from 'path';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "helloworld-sample" is now active!');

	let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		const editor = vscode.window.activeTextEditor
		if (editor) {
			console.log(`hello world: ${JSON.stringify(editor.visibleRanges)}`)
		}
	});

	context.subscriptions.push(disposable);

	disposable = vscode.window.onDidChangeTextEditorVisibleRanges((e) => {
		console.log(`fired: ${path.basename(e.textEditor.document.fileName)}, ${JSON.stringify(e.visibleRanges)}`);
	 })
}

export function deactivate() {}
```

The issue still happens as follows. 

![Mar-31-2020 08-10-54](https://user-images.githubusercontent.com/10665499/77970866-444cee80-7328-11ea-8494-98c222bf904d.gif)

It sometimes does not happen. But, by continuing clicking tabs, it begins to happen.

**Comment by tamuratak** [comment]
Still happens.

Version: 1.47.0-insider
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-08T11:58:31.614Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

**Comment by alexdima** [comment]
To verify, here is an extension:
* `package.json`
```
{
    "publisher": "alex",
    "name": "93127",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```
* `index.js`
```
const vscode = require('vscode');
const path = require('path');

exports.activate = function(context) {

	vscode.window.onDidChangeTextEditorVisibleRanges((e) => {
		console.log(`fired: ${path.basename(e.textEditor.document.fileName)}, ${JSON.stringify(e.visibleRanges)}`);
	});

}
```
