### ISSUE TITLE
phpcs: request workspace/configuracion filed

### ISSUE THREAD

**Issue by biechevarria** [microsoft/vscode#93122]
phpcs: Request workspace/configuration failed with message: Unable to locate phpcs. Please add phpcs to your global path or use composer dependency manager to install it in your project locally.
![visualstudio-bug](https://user-images.githubusercontent.com/6929125/77211194-7c238d00-6b03-11ea-96f8-35aff2a4a6c7.png)

**Comment by aeschli** [comment]
Can you file this against the PHP extension that you use? Thanks!

**Comment by biechevarria** [comment]
I'm working with the next extensions:

   1. phpcs (Ioannis Kappas)
   2. php IntelliSense
   3. php Intelephense
   4. php debug


Regardas,


*Borja Echevarria Basáñez.*

*Tel: 626 044 188*

**Comment by aeschli** [comment]
Then it's very likely the first extension that causes the issue. Please file an issue against https://github.com/ikappas/vscode-phpcs/issues
