### ISSUE TITLE
camera authority in macOS 10.15

### ISSUE THREAD

**Issue by Jamyw7g** [microsoft/vscode#93130]
I got camera permission before, but after I clear it by `tccutil reset camera`, vscode can't continue to use the camera

**Comment by deepak1556** [comment]
Which version of VS Code is this ? 

What do you mean by can't use the camera, after clearing the permissions do you mean the app is unable to request permissions again for using the camera ?

Also how are you using camera with VS Code, please provide a sample use case.

Does this happen with Electron fiddle https://github.com/electron/fiddle/releases/tag/v0.13.1 ?

**Comment by Jamyw7g** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Version: 1.43.1Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94Date: 2020-03-18T07:01:41.240ZElectron: 7.1.11Chrome: 78.0.3904.130Node.js: 12.8.1V8: 7.8.279.23-electron.0OS: Darwin x64 19.3.0Yeah, after clearing permissions, unable to request permissions again.The case is using opencv to record video.
    
    
      
    
        
                    
 
    

    On 03/23/2020 04:55，Robo<notifications@github.com> wrote： 



Which version of VS Code is this ?
What do you mean by can't use the camera, after clearing the permissions do you mean the app is unable to request permissions again for using the camera ?
Also how are you using camera with VS Code, please provide a sample use case.
Does this happen with Electron fiddle https://github.com/electron/fiddle/releases/tag/v0.13.1 ?

**Comment by deepak1556** [comment]
Thanks for the info, does this work with other notarized apps like chrome ?

Can you reset the permission with tccutil for chrome and does it request again ?

**Comment by Jamyw7g** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I have tried, Chrome can request again.
    
    

    On 03/23/2020 10:58，Robo<notifications@github.com> wrote： 



Thanks for the info, does this work with other notarized apps like chrome ?
Can you reset the permission with tccutil for chrome and does it request again ?

**Comment by deepak1556** [comment]
> The case is using opencv to record video.

@Jamyw7g how are you using it from inside vscode ? can you share an example ?

The VS Code app doesn't have camera access entitlement for catalina, hence this might happen. But I would like to understand the use case better before adding the entitlement.

**Comment by MHDFahz** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } I have tried, Chrome can request again. On 03/23/2020 10:58，Robo<notifications@github.com> wrote： Thanks for the info, does this work with other notarized apps like chrome ? Can you reset the permission with tccutil for chrome and does it request again ? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscrib

did your problem solved
I have same problem

**Comment by deepak1556** [comment]
@MHDFahz please follow https://github.com/microsoft/vscode/issues/95062 for updates. Thanks!
