### ISSUE TITLE
VS Code doesn't display Vietnamese tones at right position

### ISSUE THREAD

**Issue by ansidev** [microsoft/vscode#93131]
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:17:38.324Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic

Steps to Reproduce:

1. Type or copy this sample text and paste into VS Code editor panel: `Văn bản tiếng Việt hiển thị dấu không đúng vị trí.`
2. You can see the Vietnamese tones is at worng position for `tiếng`, `hiển`, `dấu`.

Compare with Gedit: https://imgur.com/aDPJF7J

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@ansidev Have you tried with a different font family?

**Comment by ansidev** [comment]
@alexdima Which font?

**Comment by alexdima** [comment]
@ansidev In the screenshot you have provided:
![image](https://user-images.githubusercontent.com/5047891/78035890-f22cbd00-7369-11ea-940b-a1e153e4f055.png)

VS Code has a different font than gedit. So a comparison of the characters rendering does not make sense, since the shape of the characters is defined by the font. It only makes sense to compare VS Code to gedit when configuring both tools with the same font.

**Comment by ansidev** [comment]
@alexdima Thank you.
Error font setting: `'Source Code Pro', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` (this is default font setting)
Currently, I use Consolas and it is OK. So the problem is the font.
Can you change the default font setting so the text will be displayed correctly?

**Comment by ansidev** [comment]
By default, gedit is using system font setting, FYI.

**Comment by alexdima** [comment]
@ansidev Please do the following: 
1. Find out what font gedit is using on your system.
2. Then, configure VS Code to also use that font using the setting `editor.fontFamily`.

**Comment by ansidev** [comment]
@alexdima I know that. The system mono font is Consolas.

**Comment by alexdima** [comment]
OK, then the recommendation is to use "Consolas"` if that font works better for the glyphs you want to use.
