### ISSUE TITLE
Starting Code on TS needs long time or Crash

### ISSUE THREAD

**Issue by ReneGubler** [microsoft/vscode#93136]
- VSCode Version: x64 1.40.1 System Installer 
- OS Version: Windows Server 2016 ENU Standard Edition X64 [Version 10.0.14393]

**Problem:**
The Version x64-1.39.2 runs without any problems. Any newer Version doesn't run on Windows Terminal Server. (It is **NOT** an installation in a **CITRIX Server!**) 

Steps to Reproduce:

1. Run VS Code
2. Wait: Sometimes the it opens after 1-2 Minutes, sometimes it crashes
![image](https://user-images.githubusercontent.com/25059443/77228850-673e0c80-6b8a-11ea-81fc-170d78a40cff.png)

Crash Dump Files:
https://1drv.ms/u/s!AqGCGberHVignBaK5m_XjxEXkQKc?e=tCfeSt

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please update to the current release which is 1.43.1

**Comment by deepak1556** [comment]
Do update to `1.43.1` version as mentioned by @gjsjohnmurray and try the following,

1) Launch with `--disable-gpu` from the terminal
2) And if it still crashes, download `1.43.0` and launch with `--verbose`, attach the console output here.

Thanks!

**Comment by ReneGubler** [comment]
The same issue. I also tried with the insider build with the same effect but it takes much more time to load and close. 

[](url)
[code 1.43.1 disable-gpu.txt](https://github.com/microsoft/vscode/files/4376810/code.1.43.1.disable-gpu.txt)
[code 1.43.1 no arguments.txt](https://github.com/microsoft/vscode/files/4376811/code.1.43.1.no.arguments.txt)
[Inserider 1.44.0 no arguments.txt](https://github.com/microsoft/vscode/files/4376828/Inserider.1.44.0.no.arguments.txt)

**Comment by ReneGubler** [comment]
Do you have any news or or do you need more information?

**Comment by gjsjohnmurray** [comment]
@ReneGubler the team is currently focused on the [1.44 endgame](https://github.com/microsoft/vscode/issues/93717) so I guess it may take a while before this gets looked at.

**Comment by deepak1556** [comment]
Is this still an issue with latest stable ?
