### ISSUE TITLE
Proposed API is only available when running out of dev... In Insiders

### ISSUE THREAD

**Issue by pushqrdx** [microsoft/vscode#93134]
- VSCode Version: 1.44.0-insider
- OS Version: MacOS 10.14.6 (18G2022)

Steps to Reproduce:

1. Use a proposed API with in insider with or without enableProposedApi in package.json
2. Extension fails to load with the error in the title

As specified [here](https://code.visualstudio.com/api/advanced-topics/using-proposed-api) it should be as simple as the three steps mentioned to used a proposed api in insiders but it doesn't

**Comment by jrieken** [comment]
> Extension fails to load with the error in the title

You need to start the extension from within VS Code - as if you are developing it.

**Comment by TomasHubelbauer** [comment]
I am doing that in #97181 and still I am receiving this error.
