### ISSUE TITLE
Separate js file cannot be automatically prompted jquery

### ISSUE THREAD

**Issue by Gin-Change** [microsoft/vscode#93135]
![Snipaste_2020-03-21_22-41-53](https://user-images.githubusercontent.com/54064847/77228987-0a604780-6bc6-11ea-9a82-844a80099cd3.png)
![Snipaste_2020-03-21_22-42-57](https://user-images.githubusercontent.com/54064847/77228991-0fbd9200-6bc6-11ea-974d-3b1ea90e63b8.png)

**Comment by gjsjohnmurray** [comment]
https://stackoverflow.com/questions/41777327/jquery-intellisense-in-vs-code/41778783#41778783 looks relevant

**Comment by Gin-Change** [comment]
thank you!!!

**Comment by gjsjohnmurray** [comment]
Please close this issue unless you still need help.
