### ISSUE TITLE
Allow hot-reloading content in webviews

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93146]
Right now the iteration time around webviews is pretty slow:

 1. Make a change
 2. Reload the debugged vscode instance (which closes any previously open devtools)
 3. Wait for it to load and webview to come up
 4. Open webview developer tools
 5. See errors

In comparison to the webpack-dev-server:

 1. Make a change
 2. The webpack dev server reloads the page I already have open and I see errors immediately

I ended up putting together a shimmed page that I could run via the webpack-dev-server to tighten my own loop, but this only works because I'm working on a mostly read-only editor where I could stub the APIs I needed pretty easily. It'd be awesome if we could hot-reload inside vscode.

For webpack, we could technically do this without changes in vscode via a plugin. I did something like this before--getting hot reloading to work in an environment it wasn't meant to--let me know if that approach would be preferable, I'd be happy to help get that working.

**Comment by mjbvz** [comment]
This seems like a library/framework candidate

VS Code core intentionally doesn't care where the webview content comes from our how it is generated. The `Developer: Reload webviews` command should cause a refresh if you are looking for a hook for that

**Comment by HamishWHC** [comment]
Sorry to ping this thread, but wanted to ask @connor4312 if you've had any success with creating a webpack/vscode plugin to allow for this. I'm trying to create an extension that has an embedded Svelte application, but the constant reloading is extremely frustrating.

**Comment by pokerII** [comment]
support to add this feature into webview plugin development experience, we can use webpack or esbuild watch and hot reload the source, but no way to fresh this develop sandbox.

**Comment by adamerose** [comment]
I think this is possible with the `hello-world-react-vite` template:  https://github.com/microsoft/vscode-webview-ui-toolkit-samples/blob/main/frameworks/hello-world-react-vite/docs/extension-development-cycle.md#move-to-traditional-extension-development

But you have to view the webview in a standalone embedded web browser that doesn't actually pass `postMessage` to VS Code.
