### ISSUE TITLE
Devtools "start profiling and reload page" reloads the entire extension host

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93147]
Trying to profile startup performance, this button causes the entire extension host to reload (which of course destroys the webview and closes the developer tools). I can actually just Ctrl+R in the devtools while a trace is running which causes only the webview to reload, so this doesn't block me being able to profile startup performance, but is kind of surprising/might give people difficulty if they don't figure out that workaround.

**Comment by mjbvz** [comment]
This seems like a chromium issue; we don't have any control over the dev tools (besides opening it)

Closing as upstream
