### ISSUE TITLE
Intellisense autosuggest not working properly

### ISSUE THREAD

**Issue by elmehdibm** [microsoft/vscode#93154]
I have updated to the newest verison 1.43.1 , the feature of auto-completion of javascript is not working properly it's always on relaoding , it just works on the first time for the first 2 seconds and doesn't work anymore et keep reloading.

**Comment by Hanawa02** [comment]
I have the same problem for typescript.

**Comment by elmehdibm** [comment]
I've tried to test if it work with other version like 1.31 but still don't work properly

**Comment by elmehdibm** [comment]
The Auto-Completion of Javascript stopped working , you can see here an example : 
![image](https://user-images.githubusercontent.com/29690231/77359841-27bb2000-6d44-11ea-889c-b4f0e6167ba9.png)
The Suggestions of variables , functions , ... doesn't appear anymore.

Thank you in advance

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by elmehdibm** [comment]
I disabled all my extensions and now it works fine 💯  , thank you for you help !

**Comment by mjbvz** [comment]
If you figure out which extension caused this, please file a bug against them so they can fix the issue
