### ISSUE TITLE
file reader

### ISSUE THREAD

**Issue by hemantkumarsingh** [microsoft/vscode#93158]
Issue Type: <b>Bug</b>

you have to run your code mutiple times so that code can read yor files in the same folder. 

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|3.20.0
gc-excelviewer|Gra|2.1.34
beautify|Hoo|1.5.0
python|ms-|2020.3.69010
vs-keybindings|ms-|0.2.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0

</details>

**Comment by hemantkumarsingh** [comment]
I have created, a folder in which I am running a simple python code. In this python file it ask for a txt file. I have to reload vscode multiple times or restart it. After many try it start reading that files.

**Comment by mjbvz** [comment]
Please start by filing this against the python extension

/extPython
