### ISSUE TITLE
Jupyter notebook

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [microsoft/vscode#93152]
1-enable vs code all extensions to work in the notebook such as prettier-code formatted, Bracket Pair Colorizer, Visual Studio IntelliCode etc.
2- improve UX/UI of notebook cell such as use default Jupiter notebook or Jupiter lab User interface in vs code
that will make vs code amazing

**Comment by AbdelrahmanHamdy1996** [comment]
code format not working in a notebook

**Comment by gjsjohnmurray** [comment]
Have you installed the Insiders version of VS Code yet? Looks like some new notebook stuff is coming soon.

**Comment by gjsjohnmurray** [comment]
See also #91987

**Comment by aeschli** [comment]
Closing, please track progress in #91987
