### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by JoeCare** [microsoft/vscode#93156]
Issue Type: <b>Performance Issue</b>

Please let me know how can I uninstall VSC from Ubuntu OS.
Best Regards,
Joe

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:17:38.324Z)
OS version: Linux x64 5.3.0-28-generic snap

**Comment by aeschli** [comment]
See last paragraph in
http://ubuntuhandbook.org/index.php/2019/04/install-visual-studio-code-official-snap-ubuntu-18-04/
