### ISSUE TITLE
extra bounding box on run and debug

### ISSUE THREAD

**Issue by johngrabner** [microsoft/vscode#93151]
![code not normal](https://user-images.githubusercontent.com/8209285/77236083-1b3e9800-6b89-11ea-8113-3e3b5e106274.JPG)
![code normal](https://user-images.githubusercontent.com/8209285/77236085-1e398880-6b89-11ea-9547-7edd18f54c62.JPG)

Issue Type: <b>Bug</b>

When you first select Run and debug (ctrl shift D),
the "run and debug" menu appears with an extra bounding box. 
Northing drasticaly wrong, just not profesional.
Then gets fixed with other actions that causes a page refresh.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (46.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.0.0
mssql|ms-|1.9.0
python|ms-|2020.3.69010
LiveServer|rit|5.6.1

</details>

**Comment by isidorn** [comment]
That is because the focus is on that box, and we always render focus.
Among other reasons we do this for accessibility, so people who can not use the mouse can still use our product.

For debug view we put the focus on the Start action since that is what users want most of the time.

This clusing this as designed.
