### ISSUE TITLE
Very slow startup (20-30 seconds)

### ISSUE THREAD

**Issue by DarylVirtualV** [microsoft/vscode#93155]
Issue Type: <b>Performance Issue</b>

Everytime when i want to start VS Code, it takes 20-30 seconds to open. I just remember, i changed a number in the settings to something like 999999999999 to load something, but I really can't remember what that was.
Thanks for your help.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.51GB free)|
|Process Argv|C:\Users\daryl\Desktop\AltVServer|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 14640	code main
    0	    70	 25660	   shared-process
    0	    14	 33936	   electron-crash-reporter
    0	   188	 34292	   window (AltVServer - Visual Studio Code)
    0	    63	 20752	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 35200	     console-window-host (Windows internal process)
    0	    11	 36208	     watcherService 
    0	    11	   564	       console-window-host (Windows internal process)
    0	    80	 36872	     extensionHost
    0	   280	 31436	       electron_node tsserver.js 
    0	    46	 35940	         electron_node typingsInstaller.js typesMap.js 
    0	    51	 31824	       electron_node tsserver.js 
    0	    68	 36824	   window (Issue Reporter)
    0	    25	 37112	   utility
    0	   129	 37208	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (AltVServer - Visual Studio Code)
|    Folder (AltVServer): 569 files
|      File types: ymap(63) ydr(62) js(52) ytd(41) ts(34) dmp(32) ydd(26)
|                  cfg(24) mjs(22) ttf(20)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|3.20.0
discord-vscode|icr|3.13.0
discord|Kua|0.0.6
atlv-complete|stu|0.1.3

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Did you try opening your settings in JSON format (settings json file) and searching the file?

**Comment by aeschli** [comment]
To find out if the slow startup is related the settings or any other state, run VSCode with a different user-data-dir: `code --user-data-dir c:\\test-user-dir` and see if that makes any difference

If that doesn't help, please see https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly for instructions on how to diagnose the slow startup.

**Comment by Xen1308** [comment]
> Did you try opening your settings in JSON format (settings json file) and searching the file?

No i didnt how can i do that?

**Comment by Xen1308** [comment]
> To find out if the slow startup is related the settings or any other state, run VSCode with a different user-data-dir: `code --user-data-dir c:\\test-user-dir` and see if that makes any difference
> 
> If that doesn't help, please see https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly for instructions on how to diagnose the slow startup.

Where do i have to write code --user-data-dir c:\\test-user-dir 
In the terminal?

**Comment by aeschli** [comment]
Yes, close all VSCode windows, open a command prompt and start VSCode with
`code --user-data-dir c:\test-user-dir`

**Comment by Xen1308** [comment]
> Yes, close all VSCode windows, open a command prompt and start VSCode with
> `code --user-data-dir c:\test-user-dir`

Okay do i have to do test-user-dir or does it not matter in which folder i do that?

**Comment by Xen1308** [comment]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-1cb7.extHost.cpuprofile.txt`
-`prof-1cb7.main.cpuprofile.txt`
-`prof-1cb7.renderer.cpuprofile.txt`

**Comment by Xen1308** [comment]
That should help you.

## Performance Marks

| What                                                            | Duration | Process          | Info                                       |
| --------------------------------------------------------------- | -------- | ---------------- | ------------------------------------------ |
| start => app.isReady                                            | 50       | [main]           | initial startup: true                      |
| nls:start => nls:end                                            | 1        | [main]           | initial startup: true                      |
| require(main.bundle.js)                                         | 60       | [main]           | initial startup: true                      |
| app.isReady => window.loadUrl()                                 | 142      | [main]           | initial startup: true                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 11048    | [main->renderer] | NewWindow                                  |
| require(workbench.desktop.main.js)                              | 521      | [renderer]       | cached data: YES, node_modules took 130ms  |
| require & init workspace storage                                | 33       | [renderer]       | -                                          |
| init workspace service                                          | 36       | [renderer]       | -                                          |
| register extensions & spawn extension host                      | 4344     | [renderer]       | -                                          |
| restore viewlet                                                 | 58       | [renderer]       | workbench.view.explorer                    |
| restore panel                                                   | 0        | [renderer]       | -                                          |
| restore editors                                                 | 4301     | [renderer]       | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                          | 4483     | [renderer]       | -                                          |
| workbench ready                                                 | 16305    | [main->renderer] | -                                          |
| extensions registered                                           | 16474    | [renderer]       | -                                          |
