### ISSUE TITLE
Configuration to hide debug toolbar

### ISSUE THREAD

**Issue by zooldk** [Microsoft/vscode#9315]
Hi I dont know if this is a vscode issue or cordova plugin issue. But here it goes.
- VSCode Version:1.3.1
- OS Version: OSX (latest)

Steps to Reproduce:
1. fire up your cordova project
2. run the project (F5)
3. try to change tabs.. 

Here it is easy to see that the run/debug/step into popup overlays with the new tabs for the files - hence makes it a bit hard to work and focus (see attachment).

![screen shot 2016-07-15 at 09 09 10](https://cloud.githubusercontent.com/assets/1841838/16866447/4686e5cc-4a6c-11e6-95e2-22fbd3111b6e.png)

**Comment by bpasero** [comment]
@zooldk for this reason we made the debug toolbar dragable. Did you try?

**Comment by zooldk** [comment]
yeah. I now.. but if it is filled (the tab bar) then what? can't I disable this toolbar. I use keybindings and shortcuts.. Is there a preference pane where I can disable it?

**Comment by G3z** [comment]
i think that better than hiding i think we can:

1. move it inside de debug view (above the variables panel)
2. move it near the split view editor in top right corner, and reduce space for tabs (when opened)
3. move it to the bottom bar (in the middle ?)

**Comment by dpix** [comment]
I'm happy with it being **anywhere** other than on top of the file tabs. It is the most frustrating position at the moment. Whilst debugging, I'm constantly having to drag it around so I can get to my open files.

I suggest using the big amount of empty space at the bottom of the left sidebar

**Comment by isidorn** [comment]
Just pushed `debug.hideActionBar` setting, for positioning there are already issues capturing htis
