### ISSUE TITLE
venv issue with intergrated terminal

### ISSUE THREAD

**Issue by AmericanY** [microsoft/vscode#93159]
Issue Type: <b>Bug</b>

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17
python|ms-|2020.3.69010

</details>

My Current Settings:

```json
{
    "workbench.startupEditor": "none",
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "code-runner.saveFileBeforeRun": true,
    "python.pythonPath": "env\\Scripts\\python.exe",
    "code-runner.showExecutionMessage": false,
    "code-runner.clearPreviousOutput": true,
    "terminal.integrated.copyOnSelection": true,
    "workbench.panel.defaultLocation": "right",
    "code-runner.executorMap": {
        "python": "$pythonPath -u $fullFileName"
    },
    "terminal.integrated.shellArgs.windows": [
        "-NoLogo"
    ],
    "python.terminal.activateEnvInCurrentTerminal": true,
    "python.jediEnabled": false,
    "code-runner.runInTerminal": true
}
```

![](https://serving.photos.photobox.com/9464303948796dcdedc9ab97bfb9c44b1e5b71fc43b0b3bbb36cfaf11aaa95c2b7b7f644.jpg)
my issue that when i open `vscode` and run code via `Code-Runner` shortcut <kbd>ALT</kbd> <kbd>CTRL</kbd> <kbd>N</kbd> the terminal will load the first time without being under my `venv` as you can see the difference between `1st` and `2st` run.

On the first run i got `[WinError 2] The system cannot find the file specified` and once it's end. so the `venv` activated automatically. so once i run the code again. it's works !

How i can get that to work from `1st` run.

**Comment by gjsjohnmurray** [comment]
I guess this is likely to be caused by the code-runner extension. It seems you have already opened https://github.com/formulahendry/vscode-code-runner/issues/592 on it.
