### ISSUE TITLE
Allow disabling selection search for Go to file

### ISSUE THREAD

**Issue by xixixao** [microsoft/vscode#93162]
Here's what happens:

1. I have some code selected
2. I hit cmd+P to go to a different file
3. The search bar is now full of gibberish text from my selection

Can we add a setting to disable this behavior? This makes sense for code search, not for file name search.

**Comment by roblourens** [comment]
This doesn't happen for me and I'm not aware of a setting that does this. Maybe you have `workbench.quickOpen.preserveInput` set?

**Comment by xixixao** [comment]
Sorry for the noise, I think this is something internal.
