### ISSUE TITLE
Exclusion in files search may not be able to hanlde this situation

### ISSUE THREAD

**Issue by 2482103133** [microsoft/vscode#93163]
Version: 1.43.1 (user setup)
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
1.
![image](https://user-images.githubusercontent.com/37145130/77241924-39ad9d80-6c34-11ea-835e-149dbb9145ac.png)
2.
![image](https://user-images.githubusercontent.com/37145130/77241936-5ea21080-6c34-11ea-9d14-bec8c341dfa6.png)
3.
![image](https://user-images.githubusercontent.com/37145130/77241932-50ec8b00-6c34-11ea-8dd2-078c16bc41ac.png)
4.
![image](https://user-images.githubusercontent.com/37145130/77242003-eee05580-6c34-11ea-9a15-15237cb4a9ca.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by 2482103133** [comment]
Maybe we should leave room for more separators because comma is a legal filename character.

**Comment by roblourens** [comment]
You can escape the `,` by wrapping it in `[,]`. Also closed a similar issue as out of scope, https://github.com/microsoft/vscode/issues/16834
