### ISSUE TITLE
Problem when working with files in Python

### ISSUE THREAD

**Issue by DUNNizbattle** [microsoft/vscode#93170]
Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.

**Comment by DUNNizbattle** [comment]
In the folder where I save all files with Python lessons, I created a text file.txt. I tried calling this file as shown below.
f = open ('text.txt')
print (f.read ())
The .py file where I am trying to open the text file.txt, and the text file itself.txt files are located in the same folder. The terminal writes that such a file does not exist, although this is not the case. However, the standard Python terminal that comes with the language itself outputs everything normally. How can I fix this problem?

**Comment by DUNNizbattle** [comment]
> (Экспериментальное обнаружение дубликатов)
> Спасибо, что прислали этот вопрос. Пожалуйста, также проверьте, если он уже покрыт существующим, например:
> 
> * [Удаляется VCode (#92214)](https://www.github.com/microsoft/vscode/issues/92214)

I will explain my problem in more detail. I am learning the Python programming language. I reached a lesson on YouTube, which deals with the issue of working with files. This lesson explained that if the files are in the same folder, when writing (f = fopen ('text.txt')), and then the commands (print (f. read ()) the file should be opened by default for reading, and the terminal should output all the contents of the called file. The problem is that the terminal of the VS Code editor displays an error that such a file does not exist. At the same time, everything works fine in the standard terminal, which is initially installed when installing the Python language itself from the developer's site.

**Comment by aeschli** [comment]
Sorry, I'm not able to reproduce:
![image](https://user-images.githubusercontent.com/6461412/77247578-d707d200-6c32-11ea-960e-74ac1faed4b9.png)

I'm quite sure the integrated terminal works as expected and this is some other issue, likely python related. I suggest to also print the working directory. Also double check you have no typo in the file name.

**Comment by DUNNizbattle** [comment]
> Извините, я не могу воспроизвести:
> ![изображение](https://user-images.githubusercontent.com/6461412/77247578-d707d200-6c32-11ea-960e-74ac1faed4b9.png)
> 
> Я совершенно уверен, что интегрированный терминал работает так, как ожидалось, и это какая-то другая проблема, вероятно связанная с python. Предлагаю также распечатать рабочий каталог. Также дважды проверьте, что у вас нет опечатки в имени файла.

To make it more clear, I will attach two screenshots. The first screenshot shows the result in VS Code, and the second shows the result in the standard Python terminal.
![image](https://user-images.githubusercontent.com/62498005/77249840-ded86e00-6c54-11ea-9cab-c35444778d44.png)
![image](https://user-images.githubusercontent.com/62498005/77249848-ea2b9980-6c54-11ea-9208-85164d6a7205.png)
In the first screenshot, the VS Code terminal displays an error that the file is text.txt does not exist. In the second screenshot, the standard Python terminal, which I downloaded along with the language itself from the developer's site, displayed the entire contents of the text file .txt.
In principle, I can work with the code through the standard Python editor and terminal, but I need a program like VSCode, so I can use it to learn different programming languages, including Python, which I am studying now. The vscode terminal itself reproduces code results such as (Hello World) and solutions to other tasks without problems . For example, I recently made a small calculator using a function (def) and conditional operators (if, elife). The terminal reproduces the results of this program normally.
I assume that in General the VS Code terminal works fine, but when I try, being in a file with the .py extension , using the entry (f = open ('text.txt') open this file and output it in the terminal using the entry (print (f. read ()), then it is possible that the VSCode program itself does not see this file for some reason and outputs an error that such a file does not exist.
The question is , how do I solve this problem? Maybe there is some special extension for the editor , installation of which can fix this problem, if so, what is it called?

**Comment by aeschli** [comment]
To run the program, did you press the `Play` triangle? That would explain it.
That opens the console with a different folder as current working directory (as you can see in the screenshot)
The Play button comes from the Python extension. You can file the issue there.
https://github.com/microsoft/vscode-python/issues

**Comment by DUNNizbattle** [comment]
> https://github.com/microsoft/vscode-python/issues

You're right. I actually used Play to launch programs . So you want to say that you had to run the program in the terminal using the Run tab , the F5 key, or ctrl + F5? Then VS Code will find the text file.txt?

**Comment by aeschli** [comment]
There are many ways of running a program. What's key for you is that the current working directly is set to the folder of the script.
One way that would work:
- select the script file in the explorer and run `Open in Terminal` from the context menu
- In the terminal that starts up, run `python yourscript.py`

**Comment by DUNNizbattle** [comment]
> Есть много способов запуска программы. Что является ключевым для вас является то, что текущая работа непосредственно устанавливается в папку скрипта.
> Один из способов, который будет работать:
> 
> * выберите файл сценария в проводнике и запустите `Open in Terminal`его из контекстного меню
> * В терминале, который запускается, запустите `python yourscript.py`
As you said, I launched the file via the context menu using the "Open in Terminal" command.
![image](https://user-images.githubusercontent.com/62498005/77464129-c6648100-6e17-11ea-9004-ab21e897be14.png)
After that, I wrote terminal (python yourscript.py).
![image](https://user-images.githubusercontent.com/62498005/77465131-3de6e000-6e19-11ea-8bc5-24c5cdcf6fde.png)
I didn 't understand how to correctly enter this command in the terminal to make it work. Apparently, the fact that even before installing VS Code, I worked in the standard Python IDE affects the fact that I have not yet fully understood how to work with the VS Code terminal . Before that, I took classes on working with functions, conditional operators, and exceptions. All these scripts I ran only through the triangle. I got stuck on file detection only when I started studying the topic "working with files in Python".
I am also interested in another question. The fact is that English is not my native language, so I write the file names in my native Russian, in this folder, which contains files with my scripts on the topics of other Python lessons, in English I named only the file (text.txt). Can errors with finding files when working with them with the VS Code editor be related to this? Maybe it would be better to name all the files in English?

**Comment by aeschli** [comment]
Sorry, I don't have any experience with using using Cyrillic letters in file names. Using English file names certainly makes things easier. 
If you have spaces in your file name, you need to use double quotes around the file name.

**Comment by DUNNizbattle** [comment]
> Извините, у меня нет никакого опыта использования кириллических букв в именах файлов. Использование английских имен файлов, безусловно, упрощает задачу.
> Если у вас есть пробелы в имени файла, вам нужно использовать двойные кавычки вокруг имени файла.

I understand that it is not the file names that matter, and I agree in principle that it is better to set the file names in English. I think the question in my case is different. 
The fact is that when I first started learning Python, following the tips from the lessons on YouTube, I first installed the so-called Python IDLE before installing VS Code. I have been programming in it for a long time, everything was simple there, you could check any Python script in the terminal of this program just by pressing the F5 button, this command easily launched any scripts on Python, including the script that allowed using Python code to output the contents of another file to the terminal of the Python IDLE program.
Then, following the tips from the same lessons from YouTube, I started looking for a more professional development environment. I was looking for a universal development environment. The point is that I don't just want to learn Python, but when I get used to it, I will definitely learn other languages, so I want to clog up my computer with ten development environments for ten programming languages. It would be convenient for me if I could program in different languages in the same development environment. This is what I thought when I installed VS Code.
After installing VS Code and installing an extension to support Python scripts, I continued working with the new editor as well as with Python IDLE. In VS Code, I went through what I went through earlier to repeat and to test the capabilities of the new development environment. All the scripts that I wrote on Python in VS Code, I played by clicking on the green triangle. Everything worked, problems only arose when I came to the topic "Working with files in Python". It is the solution to this problem that I am trying to understand and do by asking you my questions.
I believe that one of my key problems now when working with Python in VS Code is that I have abruptly moved from a simpler development environment like Python IDLE to a more complex VS Code. I continued programming as I had done in the previous development environment, without fully understanding the capabilities of this editor. I would also like to ask you if there are any lessons on YouTube in which Python programming is performed in the VS Code development environment? I would like to find a tutorial on YouTube that shows how to work with files of different types using Python scripts, where they would show the correct way to run the script that finds the file, output all its contents to the VS Code terminal.
I generally study programming on my own at home in my free time, sitting on the couch with my laptop. So I watch different lessons on YouTube, just visually from the image of the video I perceive information better than reading the text.
And also, I'm sorry to give you so much different information. The fact is that I don't have a single friend who is professionally engaged in programming. I try to learn it myself, using only the Internet, YouTube, forums and social networks. You are already a professional programmer who already has his own development, and I have just started my way to also start developing my own full-fledged applications, which is why I am studying Python. By the way, I have one more question for you. Are you a VS Code developer, or are you just consulting newcomers like me, helping them and me understand the possibilities of this development environment?
In any case, I will continue to study Python all the next weekend, but for a comfortable learning of this language and programming in it, I need to better and more thoroughly understand the VS Code editor itself.

**Comment by aeschli** [comment]
I'm happy to help and I'm glad you use VSCode. Learning a new language and environment is challenging and frustrating at times, I fully understand you.
I'm a actually developer from the VSCode (editor) team. I don't develop in Python and also don't know the Python extension very well. Also this is the VSCode issue tracker and not the right place for help.

For VSCode and VSCode Python related help we recommend to use ask questions on https://stackoverflow.com/questions/tagged/visual-studio-code?tab=Newest 

For bug reports against the VSCode Python extension (such as the play button, or the Python launch extension), please file issues against https://github.com/microsoft/vscode-python/issues
