### ISSUE TITLE
Slow Startup. Takes up to 30 seconds

### ISSUE THREAD

**Issue by DarylVirtualV** [microsoft/vscode#93175]
Issue Type: <b>Performance Issue</b>

When i start vscode its very slow. It takes 20 - 30 seconds maybe.
Here my Performance Marks
## Performance Marks

| What                                                            | Duration | Process          | Info                                       |
| --------------------------------------------------------------- | -------- | ---------------- | ------------------------------------------ |
| start => app.isReady                                            | 54       | [main]           | initial startup: true                      |
| nls:start => nls:end                                            | 1        | [main]           | initial startup: true                      |
| require(main.bundle.js)                                         | 62       | [main]           | initial startup: true                      |
| app.isReady => window.loadUrl()                                 | 137      | [main]           | initial startup: true                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 10715    | [main->renderer] | NewWindow                                  |
| require(workbench.desktop.main.js)                              | 507      | [renderer]       | cached data: YES, node_modules took 261ms  |
| require & init workspace storage                                | 4        | [renderer]       | -                                          |
| init workspace service                                          | 39       | [renderer]       | -                                          |
| register extensions & spawn extension host                      | 3881     | [renderer]       | -                                          |
| restore viewlet                                                 | 0        | [renderer]       | -                                          |
| restore panel                                                   | 0        | [renderer]       | -                                          |
| restore editors                                                 | 3777     | [renderer]       | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                          | 3919     | [renderer]       | -                                          |
| workbench ready                                                 | 15387    | [main->renderer] | -                                          |
| extensions registered                                           | 15585    | [renderer]       | -                                          |

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (10.02GB free)|
|Process Argv|C:\Users\daryl\Desktop\altv-server\resources\myresource\client\startup.mjs|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    78	 11692	code main
    0	    14	  1632	   electron-crash-reporter
    0	    75	 12948	   shared-process
    0	   155	 13476	   gpu-process
    0	    25	 13544	   utility
    0	   159	 14096	   window (Startup Performance - Visual Studio Code)
    8	   106	 19984	     extensionHost
    0	   180	 15396	   window (Startup Performance - Visual Studio Code)
    0	    65	 12416	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	 15052	       C:\WINDOWS\system32\cmd.exe /c ""D:\Microsoft VS Code\bin\code.cmd" --prof-startup"
    0	    37	  3472	         electron_node cli.js 
    8	    63	  5100	           "D:\Microsoft VS Code\Code.exe" --prof-startup --inspect-brk=24968 --remote-debugging-port=24969 --inspect-brk-extensions=24970 --prof-startup-prefix C:\Users\daryl\prof-cc04 --no-cached-data
    0	    42	  4380	             gpu-process
    0	     6	 12792	     console-window-host (Windows internal process)
    0	    97	 16344	     extensionHost
    0	    50	 14164	       electron_node tsserver.js 
    0	   134	 15460	       electron_node tsserver.js 
    0	    45	 16216	         electron_node typingsInstaller.js typesMap.js 
    0	    66	 19532	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|3.20.0
discord-vscode|icr|3.13.0
discord|Kua|0.0.6
atlv-complete|stu|0.1.3

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aperf-startup

**Comment by jrieken** [comment]
@deepak1556 we are seeing more of these. If there anything that has changed in electron? @DarylVirtualV What AV software are you using? Do you have an update pending?

**Comment by DarylVirtualV** [comment]
I have no AV and no updates

**Comment by DarylVirtualV** [comment]
> @deepak1556 we are seeing more of these. If there anything that has changed in electron? @DarylVirtualV What AV software are you using? Do you have an update pending?

I have no AV and updates

**Comment by deepak1556** [comment]
@jrieken nothing specific I can remember. But lets try this from the beginning.

@DarylVirtualV can you launch code with `--disable-extensions --trace` and once the window is loaded a popup will appear with path to the trace file, please attach the file here. Thanks!
