### ISSUE TITLE
class/function navigation bar similar to the Visual Studio

### ISSUE THREAD

**Issue by BIGWarriorSoftware** [microsoft/vscode#93172]
Issue Type: <b>Feature Request</b>

In the Visual Studio Community, Enterprise, etc. There is a class, and function dropdownlist the top of code editor field. It would be our work is easier if it would be in vs code. Can you implement it?

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aeschli** [comment]
VSCode has the [Breadcrumbs navigation bar](https://code.visualstudio.com/docs/getstarted/userinterface#_breadcrumbs) that also has dropdowns with classes/function.
