### ISSUE TITLE
(node:1412) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by AdamFeher2400** [microsoft/vscode#93177]
Issue Type: <b>Bug</b>

I found the following error on console of Developer Tools in Visual Studio Code.
(node:1412) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.3
es7-react-js-snippets|dsz|2.7.0
vscode-diff|fab|1.4.0
vscode-yarn|gam|1.7.0
gc-excelviewer|Gra|2.1.34
Angular2|joh|9.1.2
graphql-for-vscode|kum|1.15.3
php-ci|sma|0.3.6
yarn-ui|xqc|0.1.2

</details>

**Comment by zix66** [comment]
same here

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by zix66** [comment]
Hi there!I'm using VS Code only for working with Salesforce pack.Sure I can run VS Code without extensions .. but I need to work with my extensions :)
With best wishes, Igor Umansky
    On Tuesday, March 24, 2020, 07:26:43 PM GMT+2, Johannes Rieken <notifications@github.com> wrote:  
 
 


Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks.

**Comment by alexdima** [comment]
@zix66 The console receives warning messages from both VS Code and from extensions. Most likely it is one of your installed extensions that uses deprecated nodejs API. Unfortunately it is not easy to figure out which one because nodejs does not log the stack to the call.

**Comment by zix66** [comment]
Hi there!I did a little investigation : disabling & re-enabling each one from my extensions.So problem (funny!) with Microsoft Live Share. With best wishes, Igor Umansky    On Tuesday, March 24, 2020, 07:55:54 PM GMT+2, Alexandru Dima <notifications@github.com> wrote:  
 
 


@zix66 The console receives warning messages from both VS Code and from extensions. Most likely it is one of your installed extensions that uses deprecated nodejs API. Unfortunately it is not easy to figure out which one because nodejs does not log the stack to the call.

**Comment by alexdima** [comment]
Moved to https://github.com/MicrosoftDocs/live-share/issues/3331
