### ISSUE TITLE
Shared Settings

### ISSUE THREAD

**Issue by raz-avr** [microsoft/vscode#93179]
As highlighted in [this](https://github.com/microsoft/vscode/issues/40239#issuecomment-599119539) discussion, there is currently (as of version 1.43) no neat way of sharing VS Code settings (and tasks/launch configurations etc.) via source control. The `.vscode` folder and files within it may contain both user-specific workspace settings as well as settings which feel intended to be shared.

## Proposal
A third layer of settings (e.g. `Shared`), in addition to `User` and `Workspace`. It would override any User and Workspace settings similarly to how Workspace overrides User (this way a team could ensure that the shared settings are in effect for all members), and support both a single-file multi-root structure (i.e. `.code-workspace`) and a folder structure (i.e. `.vscode`). The file names would have to be different of course, (e.g. `.code-workspace-shared` and `.vscode-shared`).

It would be yet another file/folder to have in your project directory, yes, but it would give users freedom to have both user-specific workspace settings *and* shared workspace settings. Those who only need one of the two would only keep the one file/folder they need. This way the default `.code-workspace`/`.vscode` would become explicitly defined to not be checked into source control.

I think this would be a neater way of handing issue #40233 and would ideally function together with an extension whitelist setting (#40239) to allow sharing of enabled extensions. It would also remove the concerns illustrated [here](https://github.com/microsoft/vscode/issues/10708#issuecomment-241330047) and allow for user-specific and workspace-specific keybindings (#10708).

**Comment by sandy081** [comment]
Thanks for the proposal. We are already started discussing and designing user folder settings. We have a design proposal which supports folder level user settings, tasks, launches and extensions.  I will update in #40233.

Hence marking this as a duplicate.
