### ISSUE TITLE
Freezing VS Code problem

### ISSUE THREAD

**Issue by canbaran011** [microsoft/vscode#93174]
Yesterday vs code started to freeze when i write my codes . i tried disable , remove and such a solutions to understand what really causes to slow down my vs code . but non of them changed this situation. so i deleted settings.json and still problem continued when i did that. I also tried to install older version of vs code but no some different "maybe os based things make me slower. Thank you for helping me.

**Comment by canbaran011** [comment]
CPUs | Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.91GB (4.40GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by canbaran011** [comment]
CPU %	Mem MB	   PID	Process
    1	    70	  5592	code main
    2	    62	  2216	   window (Issue Reporter)
    1	   268	  5408	   window (products.pug - SadıkTuran - Visual Studio Code)
    0	    12	  6504	     watcherService 
    0	     3	  6252	       console-window-host (Windows internal process)
    0	   109	  7592	     extensionHost
    0	    95	   492	       electron_node tsserver.js 
    0	    41	  6608	         electron_node typingsInstaller.js typesMap.js 
    0	    46	  5924	       electron_node tsserver.js 
    7	    63	  7500	   shared-process
    6	   108	  8528	   gpu-process

**Comment by aeschli** [comment]
Do you have extensions disabled?

**Comment by canbaran011** [comment]
> Do you have extensions disabled?

yes i did. i also tried older version of vs code
