### ISSUE TITLE
Regex lookahead not working with replace

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#9317]
_Reported by @widarlein:_

**Sample:**
```
username: apa
password: bepa
```

**Static replace:**
Pattern: `(.+)(?=:)`
Replace: `bapap`

Only works with Replace All. Not with single Replace.

**Capturing replace:**
Pattern: `(.+)(?=:)`
Replace: `"$1"`

Nothing happens when trying to do a replace. 

VSCode 1.4.0-insider
Win10

**Comment by sandy081** [comment]
Fixed by d546a4a6ef121804728d52a13ae4fa860514972e

**Comment by csholmq** [comment]
Not able to do dynamic replace. Just me?

**Comment by sandy081** [comment]
@csholmq May I know what do you mean by dynamic replace?

**Comment by csholmq** [comment]
@sandy081 I actually meant Capturing replace as per my example in the top post. Sorry för the confusion.

**Comment by sandy081** [comment]
@csholmq Thanks for informing. Yes capturing groups in replace when find term is regex look ahead expression is not working. I filed a separate issue for this case #10799 as this case got over-looked while fixing/verifying.
