### ISSUE TITLE
Support Containerfile syntax highlighting

### ISSUE THREAD

**Issue by DCKcode** [microsoft/vscode#93183]
Many tools building Open Container Initiative (OCI) Linux container images have adopted the `Dockerfile` format to specify how a container should be built. Examples are tools like [kaniko](https://github.com/GoogleContainerTools/kaniko), [Buildah](https://buildah.io/), and [Podman](https://podman.io/).

Since these initiatives are not driven by Docker (the company), but in this case by Google and Red Hat, these projects have a preference to use the vendor neutral file name `Containerfile` for container build specifications in these projects. [Buildah now uses `Containerfile` by default.](https://buildah.io/releases/2020/01/14/Buildah-version-v1.12.0.html) It would be nice if VSCode would recognize and support `Containerfile` for syntax highlighting and other integrations.

Since the `Containerfile` syntax is exactly the same as the `Dockerfile` syntax, it should just require VSCode to appropriately recognize the file :slightly_smiling_face:

**Comment by LuisEnMarroquin** [comment]
A temporary fix is to add the following to your **User Settings** or your `.vscode/settings.json`

```shell
{
  "files.associations": {
    "**/Containerfile": "dockerfile"
  }
}
```
