### ISSUE TITLE
Allow passing repository as argument for Git-related commands

### ISSUE THREAD

**Issue by lekspyl** [microsoft/vscode#93181]
Hello, community.

I am proposing to implement "inline" repository passing for Git-related commands.
This would be useful for users who work with multiple repositories in a single workspace.
In VSCode 1.43.1 to, let's say, pull changes from a specific repo in a workspace one must:
1. Open command menu (`Ctrl+Shift+P`)
2. Find `Git: Pull` and press `Enter`
3. Select the repository:
![Screenshot from 2020-03-22 18-18-15](https://user-images.githubusercontent.com/31690776/77254501-0423a700-6c6a-11ea-8ae8-1871ff8eec39.png)

I propose to allow passing repository parameter to Git-related commands, example: `Git: Pull cm` for quick pull for `cm` repo.

**Comment by joaomoreno** [comment]
This is currently not supported by the command infrastructure, we're a long way for it.
