### ISSUE TITLE
No command to open workspace settings JSON

### ISSUE THREAD

**Issue by AndrewRayCode** [microsoft/vscode#93189]
Similar to: https://github.com/microsoft/vscode/issues/91033

In general I'd like to always edit settings in JSON format. The current UI makes this difficult. Trying to tell teammates how to add things to their global or local settings requires adding a screenshot to the instructions, because no one can find the "little piece of paper on the top right to switch to JSON view." The UI makes it impossible to know what settings I've manually added vs which ones are default, so if I want to go tweak a setting I know I've set, the UI gets in the way.

In that vein, as far as I can tell, there's no way to get to workspace settings.json. I found this command, which I am grateful for so I don't have to use my mouse to get to the global settings.json file:
```json
  {
    "key": "cmd-,",
    "command": "workbench.action.openSettingsJson"
  },
```

I don't see a command to open **workspace settings in JSON mode.** The closest I have found is installing [this macros extension](https://marketplace.visualstudio.com/items?itemName=geddski.macros) and setting up a macro to do this:
```json
  {
    "key": "cmd-k cmd-,",
    "command": "macros.openWorkspaceSettingsJSON"
  },
```
And adding a macro for it:
```json
  "macros": {
    "openWorkspaceSettingsJSON": [
      "workbench.action.openWorkspaceSettings",
      "workbench.action.openWorkspaceSettings",
      "settings.switchToJSON"
    ]
  }
```
I have to `openWorkspaceSettings` twice (at least), otherwise there's a race condition where it doesn't select the "workspace settings" tab fast enough, and `switchToJSON` runs and opens the global settings, instead of the workspace settings. Running `openWorkspaceSettings` twice is to really, _really_ select that tab. I don't know if this flakiness of running these two commands in a row is a VSCode bug or an extension bug.

Additionally, there appears to be no way to do the following set up a keyboard shortcut to open a specific file (which I could use to open `${workspaceRoot}/.vscode/settings.json`), at least not without writing an extension to do it.

**Comment by sandy081** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/10746682/77660581-cd0b0980-6f79-11ea-9675-d94609501b2d.png">
