### ISSUE TITLE
🔵 Problem to get Typescript *working* in a fresh new vscode #macOS-catalina #typescript

### ISSUE THREAD

**Issue by jeancharlesamey** [microsoft/vscode#93186]
- VSCode Version: 1.43.1
- Node.js : 12.8.1
- OS Version: Darwin x64 19.3.0
- Apple Model :	MacBook Pro 14,3
- MacOS : Catalina 10.15.3

Just download vscode on a Mac Book Pro 

Steps to Reproduce

1. **npm install -g typescript** _seems to install or update typescript@3.8.3 correctly_
2. _but then_ **tsc -v** _says tsc: command not found_

[same steps in video](https://www.dropbox.com/s/fr3yq8r0g9f4vsz/Enregistrement%20de%20l%E2%80%99%C3%A9cran%202020-03-22%20%C3%A0%2018.30.49.mov?dl=0)

Does this issue occur when all extensions are disabled?: Console says (when trying to disable extensions) **bash: code: command not found**

**Comment by Tyriar** [comment]
> but then tsc -v says tsc: command not found

This means that global node modules are not properly configured on your PATH. It's an environment issue. You could try tweak the `terminal.integrated.osx.shellArgs` setting to `[]` or `["l"]` to see if that fixes it.

> bash: code: command not found

There's a command (F1) to install this to your PATH.
