### ISSUE TITLE
Extensions: Custom menu label for contributes.menus

### ISSUE THREAD

**Issue by sleistner** [Microsoft/vscode#9318]
VSCode Version: 1.3.1
OS Version: OSX (10.11.5)

I was wondering if it should be possible to define a custom title/label for context menus.
E.g.

```json
"contributes": {
    "commands": [
      {
        "command": "extension.moveFile",
        "title": "File: Move"
      }
    ],
    "menus": {
      "explorer/context": [
        {
          "command": "extension.moveFile",
          "title": "Move",
          "group": "edit"
        }
      ]
    }
  }
```

**Comment by jrieken** [comment]
That isn't possible. Until now we are convinced that one command should only have one title/icon/etc. I believe you can solve your problem `File: Move` vs `Move` with the `category` property of the command. In places -like F1- we prepend that to the title where in others we don't

**Comment by sleistner** [comment]
Great, thanks. Didn't see such property in the docs.
