### ISSUE TITLE
Correct blazor sintax marked as incorrect

### ISSUE THREAD

**Issue by lfdgaliza** [microsoft/vscode#93187]
Issue Type: <b>Bug</b>

I have this code:
```razor
<span class="picked-word @(word.IsCorrect ? "correct" : "processed")">
    @word
</span>
```

This is correctly compiled and the code runs fine, but VSCode cannot understand the use of the quotation marks. So I have to use ' instead of " for this to not be marked as wrong such as the code below:

```razor
<span class='picked-word @(word.IsCorrect ? "correct" : "processed")'>
    @word
</span>
```

Also, when I use ' instead of " like the code above, the VSCode does not recognize the blazor code inside ' and this is shown as a regular string on VSCode, despite it is being correctly rendered on browser.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:17:38.324Z)
OS version: Linux x64 5.5.10-200.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2554)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (2.71GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-simpler-icons|dav|1.6.5
vscode-icon-theme|jtl|1.6.6
csharp|ms-|1.21.15
vs-keybindings|ms-|0.2.0
material-icon-theme|PKi|4.0.1
ayu|tea|0.18.0
vscode-icons|vsc|10.0.0

</details>

**Comment by aeschli** [comment]
What is the editor language mode (shown on the status bar at the bottom right)?

**Comment by lfdgaliza** [comment]
I tried with both razor and aspnetcorerazor.
