### ISSUE TITLE
Quick Open not showing files without extensions.

### ISSUE THREAD

**Issue by garretwilson** [microsoft/vscode#93182]
I'm using VS Code 1.43.1 on Windows 10.

I have a VS Code project directory with existing file `source/foo.bar`. I run a command from the command line that produces `target/foo` (with no filename extension).

I am accustomed to using `Ctrl+P` and typing "foo" to be able to see both `source/foo.bar` and `target/foo`. However in recent versions of VS Code, `target/foo` no longer appears as a choice in the drop-down list, and instead I have to manually browser to `target` in the explorer and click on `foo` to open it. Obviously this severely limits the usefulness of `Ctrl+P`.

Interestingly if I then close `target/foo` and use `Ctrl+P` again, `target/foo` in fact appears but with the "recently opened" label beside it. (Obviously manually finding a file in the explorer just so that it can be a "recently opened" file and appear in `Ctrl+P` list defeats the purpose of `Ctrl+P`.)

Note that clicking on "Refresh Explorerer" has no effect on this behavior. There seems to be some new filtering logic or setting (or bug) that is preventing `target/foo` from appearing in the Quick Open facility.

**Comment by bpasero** [comment]
This sounds more like a search issue to me than quick open. 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by roblourens** [comment]
Can you get search results in that file? Try when the file is not open.

And typically this is due to ignore settings/gitignore patterns, see the troubleshooting tips here: https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by garretwilson** [comment]
> Can you get text search results in that file? Try when the file is not open.

Project-wide searches (`Ctrl+Shift+F`) do not include content the file when it not open. However when I manually find the file in the tree and open it, it appears in project-wide search results. But then when I close the file it again no longer appears in project-wide search results.

That tree is placed in `.gitignore`. I just tested a `test.txt` file, and it behaves the same way: project-wide searches do not include the file, and `test.txt` does not appear in the `Ctrl+P` file open list! Could it be that project-wide searching and even resource opening is ignoring files from `.gitignore`? This would be new behavior.

**Comment by roblourens** [comment]
That's expected. It's not new, but you can disable using gitignore by setting `"search.useIgnoreFiles": false`
