### ISSUE TITLE
VSCode won't attach

### ISSUE THREAD

**Issue by Githamza** [microsoft/vscode#93188]
I'm trying to debug an azure function but the debugger does not debug , only rund program. so my console.log are running but not breakpoints.

Here's my conf

launch.json

```
        {
            "name": "Attach to Node Functions",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "preLaunchTask": "func: host start"
        },
```
tasks.json

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "npm install"
    },
    {
      "type": "shell",
      "label": "npm install",
      "command": "npm install"
    },
    {
      "type": "shell",
      "label": "npm prune",
      "command": "npm prune --production",
      "problemMatcher": []
    }
  ]
}
```

In my interface bottom bar does not pass to orange and loading symbol beside debug tab does not disappear

<img width="605" alt="Capture d’écran 2020-03-22 à 19 30 42" src="https://user-images.githubusercontent.com/11578288/77257379-2e7a6200-6c74-11ea-8ae1-a2f797212e17.png">

I also noticed that I don't get debugger attached line after program is running

```
[22/03/2020 18:10:55] Host lock lease acquired by instance ID '000000000000000000000000699AB618'.
[22/03/2020 18:10:55] Debugger attached.
```

**Comment by Githamza** [comment]
The solution was to provide the `AzureWebJobsStorage` value inside `local.settings.json`

**Comment by r3mattia** [comment]
I am encountering the same problem. @Githamza did you add the any port information in the `AzureWebJobsStorage` value that maps to the port specified in `launch.json`?
