### ISSUE TITLE
Disappearing file

### ISSUE THREAD

**Issue by imagtek** [microsoft/vscode#93193]
Issue Type: <b>Bug</b>

Using VSC under WIndows, to edit files in WSL Ubuntu account.
If I edit more than one file, the previous open file disappears from the tab at top of editor and is no longer selectable.
Only a single file is selectable in the file open tab at top of editor.
The previous file edit session disappears without a trace.
I cannot find a setting to correct this default behavior.
This makes the editor unusable for me.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (4.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2201)|
|Memory (System)|7.85GB (4.25GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.42.4
code-gnu-global|aus|0.2.2
cpptools|ms-|0.26.3

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Sounds like Preview Mode

https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by aeschli** [comment]
Preview mode (double click on the editor tab) allows you to pin an editor so it is no longer replaced

**Comment by aeschli** [comment]
Please reopen if this does not fix your problem

**Comment by imagtek** [comment]
I apologize for my rude behavior.
The tool is not intuitive and I have priorities other than investing 
large amounts of time figuring out its many nuances.
But I should not have been disrespectful.

John Powers
