### ISSUE TITLE
Avvio lento

### ISSUE THREAD

**Issue by zHaRdWay** [microsoft/vscode#93190]
Issue Type: <b>Performance Issue</b>

Quando avvio visual studio code ci mette 10/15 secondi per avviarsi, si apre la schermata e rimane nera per poi aprirsi dopo un po'.

Google translate:
When I start visual studio code it takes 10/15 seconds to start, the screen opens and it remains black and then opens after a while.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.86GB free)|
|Process Argv|C:\FXServer\cfx-server-data-master\server.cfg|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    77	 47288	code main
    0	    67	 34912	   window (Segnalazione problemi)
    0	   107	 38964	   gpu-process
    0	    26	 43336	   utility
    0	    67	 51216	   shared-process
    0	   140	 51300	   window (server.cfg - Visual Studio Code)
    0	    56	 48744	     extensionHost
    0	    14	 52344	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-it|MS-|1.43.6

</details>

**Comment by aeschli** [comment]
Please follow the steps here to collect more information:
https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by zHaRdWay** [comment]
Ho provato ad avviare con il cmd e con i parametri VS Code ma non trovo i "Due file" che mi ha creato, però nel cmd mi viene scritto questo, non so se è pertinente:

(node:49012) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information

**Comment by zHaRdWay** [comment]
![Cattura](https://user-images.githubusercontent.com/60584932/77481967-1f86e180-6e25-11ea-914b-1cb88066edee.PNG)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aneeds more info+label%3Aperf-startup

**Comment by jrieken** [comment]
This is the correct duplicate: https://github.com/microsoft/vscode/issues/56644
