### ISSUE TITLE
Markdown folding no longer works

### ISSUE THREAD

**Issue by DaveRainbowin** [microsoft/vscode#93199]
Issue Type: <b>Bug</b>

Not a step, but a note:
I have an extension that uses a !!! symbol for a markdown box thing, and now that can be folded unlike before, instead of the markdown headings.
1. Open markdown file w/ a couple headings
2. Try to fold it up
3. Realize you're wasting time trying to fold it because the headers won't fold

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
brainfuck-syntax|att|0.0.1
git-temporal-vscode|bee|1.0.0
markdown-mermaid|bie|1.4.2
markdown-shiki|bie|0.1.1
mermaid-markdown-syntax-highlighting|bpr|1.0.2
file-properties-viewer|bru|0.3.4
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.0.29
jshint|dba|0.10.21
json-colors|Den|0.0.6
xml|Dot|2.5.0
gitlens|eam|10.2.1
eppz-code|epp|1.2.41
chartjs-markdown-preview|Flo|0.0.2
vscode-pull-request-github|Git|0.15.0
mdmath|goe|2.4.0
discord-vscode|icr|3.13.0
vscode-postfix-ts|ipa|1.9.1
latex-workshop|Jam|8.8.0
markdown-extended|jeb|1.0.16
git-indicators|lam|2.1.2
linecounter|lyz|0.2.7
vscode-github-actions|me-|2.2.7
git-graph|mhu|1.22.0
vscode-filesize|mkx|2.1.3
csharp|ms-|1.21.15
python|ms-|2020.3.69010
indent-rainbow|ode|7.4.0
git-file-history|pom|1.0.1
java|red|0.58.0
vscode-yaml|red|0.7.2
timeit|smu|1.0.1
swdc-vscode|sof|2.1.26
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|10.0.0
literally-html|web|0.1.2
material-theme|zhu|3.2.4

(1 theme extensions excluded)

</details>

**Comment by DaveRainbowin** [comment]
Thanks, bot. None of these are close to my problem though!

**Comment by gjsjohnmurray** [comment]
Please clarify. Is this a problem that also occurs if you reload with all extensions disabled (hint - there's a command in the palette to do that)?

If the issue relates to an extension, please report it to the extension's repository. 

If the issue occurs with all extensions disabled please post more details here. Screenshots may help. And tell us if the problem is new. If so, do you know what version broke it?

**Comment by DaveRainbowin** [comment]
Okay, will do.

**Comment by DaveRainbowin** [comment]
Umm...
Sorry, it decided to work again?
