### ISSUE TITLE
Python intellisense, just stops working after 15 to 20 mins.

### ISSUE THREAD

**Issue by starkapandan** [microsoft/vscode#93194]
i have a hard time believing i am the only one, but vscode python intellisense just stops working after roughly 15 minutes, sometimes 1 hour etc.. and i have to restart each time, and it's back up working properly...

What is causing this? I do believe that there is an issue with vscode itself, since this behavior seems to be happening on javascript too. No extensions gives same result(except python extension of course).

I cannot give any steps to reproduce since it's happening on very random intervals... sometimes while i write code it stops working, sometimes i leave my desk come back and intellisense not working.

I can note however that every time intellisense stops working, the only suggestions i still get are "abc xxx" aka the previously written variables in the current file and no others.

**Comment by elmehdibm** [comment]
Happens also for javascript intellisense

**Comment by mjbvz** [comment]
Please file this against the python extension

**Comment by Manipandian** [comment]
I am not using any specific extension for javascript but I am also getting this issue, Not only in javascript, for all types of code this issue is happening.
