### ISSUE TITLE
Feature request: Sync active document with explorer

### ISSUE THREAD

**Issue by geirsagberg** [Microsoft/vscode#9319]
It would be nice to have a feature similar to Visual Studio's "Sync active document with solution explorer", for when you have `"explorer.autoReveal": false` to prevent the explorer jumping around, but still occasionally want to find the document you are working on.

- VSCode Version: 1.4.0-insider
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Set `"explorer.autoReveal": false`
2. Want to manually jump to active document in solution explorer, but can find no such command

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/16869509/747b9732-4a7d-11e6-8bf2-aeb1def11356.png)

**Comment by geirsagberg** [comment]
Ah, sweet! You guys are one step ahead of me ;)

For anyone else interested, the keyboard command is `workbench.files.action.showActiveFileInExplorer`.
