### ISSUE TITLE
Add extension contributed syntax colors to search results

### ISSUE THREAD

**Issue by Mackaber** [microsoft/vscode#93198]
Issue Type: Feature Request

I recently found this extension: https://marketplace.visualstudio.com/items?itemName=travisthieman.better-search. It was abandoned since VScode implemented the feature natively, however it is still missing the syntax colors for the search results. It would be very nice If you could include them like in the extension

![image](https://user-images.githubusercontent.com/496904/77269805-a09c7800-6c6f-11ea-9616-c33958c6e8f1.png)

VS Code version: Version: 1.43.1 (fe22a96,2020-03-18T07:01:41.240Z)
OS version: OS: Darwin x64 17.7.0

**Comment by JacksonKearl** [comment]
We do have syntax highlighting of search editors, what is it that you’re missing?

**Comment by Mackaber** [comment]
I'm sorry I didn't tested with another language, I tested it with python and ruby and it works fine. However, with the .todo syntax highlight from the Todo+ extension (https://github.com/fabiospampinato/vscode-todo-plus) doesn't seem to work, same thing with LateX. It seems languages included by default in VScode work just fine, but language support added by extensions don't

<img width="962" alt="Screen Shot 2020-03-23 at 10 04 04 AM" src="https://user-images.githubusercontent.com/496904/77336910-cb2d1600-6ced-11ea-8121-f49797748142.png">

<img width="968" alt="Screen Shot 2020-03-23 at 10 04 59 AM" src="https://user-images.githubusercontent.com/496904/77336914-cd8f7000-6ced-11ea-8ffa-823aac0a8920.png">

<img width="965" alt="Screen Shot 2020-03-23 at 10 08 51 AM" src="https://user-images.githubusercontent.com/496904/77337447-82c22800-6cee-11ea-8424-4da326b50746.png">

**Comment by JacksonKearl** [comment]
Unfortunately based on the way the textmate grammars work there isn’t much that can be done besides hard coding the extension=>scope rules. Figuring out what those associations should be for languages that don’t come bundled with VS Code poses some challenges: what happens if two competing extensions have different scope selectors? 

@mjbvz what is the process for extensions to augment existing grammars? I know for instance Apollo GraphQL adds highlighting to gql template strings in .js files.

**Comment by JacksonKearl** [comment]
A workaround for now is for the extension to declare an injection grammar which adds support for itself to Search Editors... this isn't ideal, I'll look more into how this can be made simpler. 

https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars

**Comment by mjbvz** [comment]
@JacksonKearl Yes, injection grammars or using the new semantic highlighting api
