### ISSUE TITLE
Footer bar: add number of selected lines

### ISSUE THREAD

**Issue by EthraZa** [Microsoft/vscode#932]
Footer shows:

```
Ln 10, Col 11 (123 selected)
```

It would be cool if it shows something like:

```
Ln 10-21, Col 11 (123 chars, 12 lines selected)
```

Right?

**Comment by iamdevlinph** [comment]
+1

Any update on this one?

**Comment by bpasero** [comment]
Just install https://marketplace.visualstudio.com/items?itemName=tomoki1207.selectline-statusbar

**Comment by mlewand** [comment]
@bpasero sure, extension is a solution, however this is a generic information. For many developers it's a way more useful information than selected chars count. As such imho it has to be out of the box.

It's useful when you want to tell how much LoC are in method that you're looking at.

**Comment by mlewand** [comment]
Added a pull request for this feature in #17955 🎉

**Comment by bpasero** [comment]
This can and should be provided from an extension.
