### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by messi-yang** [microsoft/vscode#93202]
- VSCode Version: 1.43.1
- OS Version: Darwin x64 19.3.0
![image](https://user-images.githubusercontent.com/17985592/77280528-890cd000-6cff-11ea-80ed-3c297ecdc66a.png)

Steps to Reproduce:

1. Open VS code
2. Show the error

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Does this happen with extensions disabled?
Please describe what you did before that happened.

**Comment by messi-yang** [comment]
@aeschli It disappeared after I updated some extensions related to "Live Share". I may think it's caused by these extensions. You can close it. Thanks your reply.
