### ISSUE TITLE
'Unable to write into user settings....

### ISSUE THREAD

**Issue by imagtek** [microsoft/vscode#93201]
Issue Type: <b>Bug</b>

I get the message 'Unable to write into user settings' when I attempt to change an editor setting.

VSC flags the 'settings.json' file as 'End of file expected'

I am getting tired of this. I have work to do.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (4.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.42.4

</details>

**Comment by gjsjohnmurray** [comment]
Screenshot(s) please

**Comment by imagtek** [comment]
I have a better idea.
I'm deleting this bloated, buggy, POS editor.

**Comment by aeschli** [comment]
There's a likely a syntax error in your settings.json file, likely some characters too much after closing brackets.

Open the setting/json file with: `Preferences: Open Settings (JSON)`
