### ISSUE TITLE
Cyclic dependency in notebook model

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93208]
This makes our product build fail.

Commented out bad code via https://github.com/microsoft/vscode/commit/0926b534553f3ff2f0cff0a741550a97df199706

**Comment by rebornix** [comment]
Thanks for the quick turnaround!

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/99f39de4af55c642908c4c7e19fb53ace5b58a09
