### ISSUE TITLE
Wrong style on debug console

### ISSUE THREAD

**Issue by wtklbm** [microsoft/vscode#93200]
Wrong style on debug console

- VSCode Version: 1.44.0-insider
  commit: 64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed
  data: 2020-03-20T08:31:26.505Z
- OS Version: Windows 10 2019 LTSC

Steps to Reproduce:

```js
// run code
console.log('\u001b[41m\u001b[97m [\u001b[4m\u001b[5mERROR\u001b[25m\u001b[24m] \u001b[0m\u001b[40m\u001b[97m \u001b[91m [method] Error，from: "X:\\xxx\\data.ts"\u001b[0m')
```

vscode:

![2020-03-23_09 38 21](https://user-images.githubusercontent.com/26459487/77272067-40e3b280-6ceb-11ea-90b3-e4233ec41e24.png)

cmd:

![2020-03-23_09 43 48](https://user-images.githubusercontent.com/26459487/77272081-4c36de00-6ceb-11ea-9523-908a029f436f.png)

**Comment by connor4312** [comment]
Looks like an issue in core--I see the debug adapter is sending the identical string as gets logged

```

Logged:          \u001b[41m\u001b[97m [\u001b[4m\u001b[5mERROR\u001b[25m\u001b[24m] \u001b[0m\u001b[40m\u001b[97m \u001b[91m [method] Error，from: "X:\\xxx\\data.ts"\u001b[0m
Sent in output: "\u001b[41m\u001b[97m [\u001b[4m\u001b[5mERROR\u001b[25m\u001b[24m] \u001b[0m\u001b[40m\u001b[97m \u001b[91m [method] Error，from: \"X:\\xxx\\data.ts\"\u001b[0m\n"
```

**Comment by isidorn** [comment]
Looks like ansi handling is off 
Code pointer https://github.com/microsoft/vscode/blob/2d85caa55586161faad7ce7c54e7335d3f14ac97/src/vs/workbench/contrib/debug/browser/debugANSIHandling.ts#L18

**Comment by isidorn** [comment]
Thanks to https://github.com/microsoft/vscode/pull/120891
This is now fixed 👏

**Comment by isidorn** [comment]
Super easy steps to verify:
Run this javascript code and make sure the output is styled in the debug console as is shown in the second picture

```
console.log('\u001b[41m\u001b[97m [\u001b[4m\u001b[5mERROR\u001b[25m\u001b[24m] \u001b[0m\u001b[40m\u001b[97m \u001b[91m [method] Error，from: "X:\\xxx\\data.ts"\u001b[0m')
```

**Comment by ArturoDent** [comment]
I get this (hopefully blinking is correct):

![ansiTest](https://user-images.githubusercontent.com/31813701/116719098-ea3db300-a997-11eb-8c4e-91dbe64153b8.gif)

Version: 1.56.0-insider (user setup)
Commit: 6449b6b7253b5808e2278903c82da8d59a230383
Date: 2021-04-30T11:35:41.567Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.21364

**Comment by isidorn** [comment]
@ArturoDent thanks for verifying 👏
