### ISSUE TITLE
CSS Intellisense not working inside <style> tag

### ISSUE THREAD

**Issue by vimalraj-a** [Microsoft/vscode#9320]
- VSCode Version: 1.3.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create plain HTML page
2. Add &lt;style&gt; tag inside head section
3. add css styles and hit ctrl + space

[VSCode screenshot](https://cloud.githubusercontent.com/assets/13977942/16867669/a9ff31b2-4a90-11e6-8203-8143086ece92.png)

**Comment by aeschli** [comment]
A known regression, that will be fixed again when #8938 is completed (planed for August)
