### ISSUE TITLE
& in Visual Studio Code

### ISSUE THREAD

**Issue by PissolatiSkywalker** [microsoft/vscode#93203]
Hello everybody! 
1st Problem: 
I'm using VSC in Catalina MAC OS system, and when I type & commercial to do a condition AND in C++ projects, either the project does not run or simply does not print the statement condition desired. How can I fix it? 
2nd Problem: 
I can't find in the tool bar the option to create a new project, only a file. So, when I want to create a Module or functions isolated from the main program, it doesn't work.

Thanks a lot!

**Comment by gjsjohnmurray** [comment]
> when I type & to work in C++ projects, it does not work

If you believe your "does not work" is caused by a VS Code bug please provide more information.

/needsMoreInfo
