### ISSUE TITLE
Error Line number and *.py file line number do not match in Python Interactive mode

### ISSUE THREAD

**Issue by andrews-tuwien** [microsoft/vscode#93209]
Issue Type: <b>Bug</b>

The displayed error is line 317 in the Python Interactive window, but the line is actually 319 in the .py file. This seems to happen with all errors.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.7.1
code-runner|for|0.9.17
blender-development|Jac|0.0.12
latex-workshop|Jam|8.8.0
vscode-docker|ms-|1.0.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.69010
remote-wsl|ms-|0.42.4
cpptools|ms-|0.26.3
vscode-yaml|red|0.7.2
vscodeintellicode|Vis|1.2.6
vscode-arduino|vsc|0.2.29

</details>

**Comment by aeschli** [comment]
Please file this against the Python extension: https://github.com/microsoft/vscode-python
