### ISSUE TITLE
 Cannot assign to read only property 'configure' of object '#<Object>'

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#93217]
Issue Id: <b>28476830-f66c-a858-1c7b-5482341dc384</b><br /><br />*Versions* <br />- 0eebaf9ad23748baca2afc0da425650922bc23de<br />-  e5834d3280fcd04898efeac32b9cf1b893f9b127<br />-  fe22a9645b44368865c0ba92e2fb881ff1afce94<br />*Stack* <br />TypeError: Cannot assign to read only property 'configure' of object '#<Object>'<br />[/vs/platform/configuration/common/configuration.ts#269:15 (addToValueTree)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/platform/configuration/common/configuration.ts#L269:15 (addToValueTree))<br />[/vs/platform/configuration/common/configuration.ts#345:2 (getDefaultValues)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/platform/configuration/common/configuration.ts#L345:2 (getDefaultValues))<br />[/vs/platform/configuration/common/configurationModels.ts#201:19](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/platform/configuration/common/configurationModels.ts#L201:19)<br />[/vs/workbench/services/configuration/browser/configurationService.ts#480:30 (onDefaultConfigurationChanged)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/workbench/services/configuration/browser/configurationService.ts#L480:30 (onDefaultConfigurationChanged))<br />[/vs/workbench/services/configuration/browser/configurationService.ts#97:136 (call)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/workbench/services/configuration/browser/configurationService.ts#L97:136 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/platform/configuration/common/configurationRegistry.ts#197:33 (registerConfigurations)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/platform/configuration/common/configurationRegistry.ts#L197:33 (registerConfigurations))<br />[/vs/workbench/api/common/configurationExtensionPoint.ts#187:24 (_handler)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/workbench/api/common/configurationExtensionPoint.ts#L187:24 (_handler))<br />[/vs/workbench/services/extensions/common/extensionsRegistry.ts#142:8 (_handle)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/workbench/services/extensions/common/extensionsRegistry.ts#L142:8 (_handle))<br />[/vs/workbench/services/extensions/common/extensionsRegistry.ts#133:7 (acceptUsers)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/workbench/services/extensions/common/extensionsRegistry.ts#L133:7 (acceptUsers))<br />[/vs/workbench/services/extensions/common/abstractExtensionService.ts#382:17 (path)](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L382:17 (path))<br />[/vs/base/node/pfs.ts#251:23](https://github.com/microsoft/vscode/blob/0eebaf9ad23748baca2afc0da425650922bc23de/src/vs/base/node/pfs.ts#L251:23)<br />

**Comment by sandy081** [comment]
No clue why a contributed default value is readonly.

@aeschli Any insights how this can happen?

**Comment by aeschli** [comment]
Similar: https://github.com/microsoft/vscode/issues/53152

My guess is there's a settings like `editor.hover` that used to be a boolean and then became an object.
As we have a test `if (typeof curr === 'object')` likely the old value is `null`.
I suggest to change
`if (typeof curr === 'object')` 
to
`if (typeof curr === 'object' && curr !== null)`
as well as adding a 'try catch' and print out the setting name that can not be assigned.

**Comment by sandy081** [comment]
Thanks @aeschli 

Followed your suggestion.
