### ISSUE TITLE
No VS Code window border

### ISSUE THREAD

**Issue by hoegge** [microsoft/vscode#93211]
Issue Type: <b>Performance Issue</b>

It is really annoying, that there is no window border arround Code - neither at the top or around the Windows - it is all black. It is bad practice to hijack the Windows theme and it makes it harder to see the differences and pick right window when you have mulitple black only windows on the screen. It creates confusion and is inefficient.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Have you tried any of the other themes that are either built-in or downloadable as extensions?

**Comment by misolori** [comment]
As @gjsjohnmurray mentioned, you can try other themes to see if one works better for you. We actually do something similar as the Windows file explorer and Edge:

![image](https://user-images.githubusercontent.com/35271042/77339236-b7cb7c00-6ce8-11ea-9508-8c807d869a99.png)

![image](https://user-images.githubusercontent.com/35271042/77339245-bb5f0300-6ce8-11ea-9d7e-d6f509973abc.png)

![image](https://user-images.githubusercontent.com/35271042/77339302-cc0f7900-6ce8-11ea-85df-f0de6b2d2ce2.png)

Will be closing this as `as designed`.

**Comment by joshuaquek** [comment]
Duplicated as of https://github.com/microsoft/vscode/pull/82781 . Issue resolved imo.
