### ISSUE TITLE
 Cannot read property 'pushStackElement' of null

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#93216]
Issue Id: <b>3860992b-6cc3-05fd-918f-490294a86840</b><br /><br />*Versions* <br />- 1.43.1<br />-  0eebaf9ad23748baca2afc0da425650922bc23de<br />-  e5834d3280fcd04898efeac32b9cf1b893f9b127<br />*Stack* <br />TypeError: Cannot read property 'pushStackElement' of null<br />[/vs/workbench/services/textfile/common/textFileSaveParticipant.ts#59:25](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts#L59:25)<br />

**Comment by jrieken** [comment]
@bpasero  this is your code I believe. It's also not spec'ed to be `null` https://github.com/microsoft/vscode/blob/01dbe67aa9a079424f5500c16296f4355f7b354d/src/vs/workbench/services/textfile/common/textfiles.ts#L428
