### ISSUE TITLE
Dual Monitors

### ISSUE THREAD

**Issue by joaquimbarreto** [microsoft/vscode#93212]
Issue Type: <b>Feature Request</b>

Dear Madam/Sir,

It would be nice to use VS Code over two monitors.

Kind regards,

Joaquim Barreto

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
You can already spread VS Code's single window across multiple monitors. See the [roadmap](https://github.com/microsoft/vscode/wiki/Roadmap#workbench) for some information about future direction.

/duplicate
