### ISSUE TITLE
Text selection problem

### ISSUE THREAD

**Issue by conglinyizhi** [microsoft/vscode#93210]
Issue Type: <b>Bug</b>

When editing JavaScript, this problem occurs after pressing ````Ctrl + A.```` However, this problem also occurs when multiple lines of code are selected.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:25.246Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.16GB (0.49GB free)|
|Process Argv|D:\WebAPP|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
tp5-snippet|dax|1.0.0
vscode-eslint|dba|2.1.1
javascript-ejs-support|Dig|1.3.1
tslint|eg2|1.0.44
php-debug|fel|1.13.0
vscode-npm|fkn|3.3.0
translator|for|0.0.3
dora|lin|0.4.1
ftp-sync|luk|0.3.9
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-language-pack-zh-hans|MS-|1.43.11
python|ms-|2020.3.69010
notepadplusplus-keybindings|ms-|1.0.5
vetur|oct|0.24.0
laravel-blade|one|1.20.0
material-icon-theme|PKi|4.0.1
vscode-icons|vsc|10.0.0
prettify|whi|0.0.3

</details>

**Comment by conglinyizhi** [comment]
![image](https://user-images.githubusercontent.com/42381347/77295345-bddd4f00-6d20-11ea-9d14-65dcb727ea30.png)

**Comment by gjsjohnmurray** [comment]
Does this also happen if you reload with all extensions disabled? Look in Command Palette for a command to do this.

**Comment by conglinyizhi** [comment]
Thank you for your answer, the problem has been resolved, this problem has not been reproduced after opening all plugins again
