### ISSUE TITLE
 Cannot resize a pty that has already exited

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#93218]
Issue Id: <b>5c7c8a2c-6c53-11f9-fe42-c0212f6d93fd</b><br /><br />*Versions* <br />- 1.43.1<br />-  0eebaf9ad23748baca2afc0da425650922bc23de<br />-  e5834d3280fcd04898efeac32b9cf1b893f9b127<br />*Stack* <br />Error: Cannot resize a pty that has already exited<br />    at WindowsPtyAgent.resize (\node_modules.asar\node-pty\lib\windowsPtyAgent.js:132:23)<br />    at WindowsTerminal.<anonymous> (\node_modules.asar\node-pty\lib\windowsTerminal.js:130:26)<br />    at WindowsTerminal._defer (\node_modules.asar\node-pty\lib\windowsTerminal.js:155:24)<br />    at WindowsTerminal.resize (\node_modules.asar\node-pty\lib\windowsTerminal.js:129:14)<br />[/vs/workbench/contrib/terminal/node/terminalProcess.ts#245:21 (resize)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L245:21 (resize))<br />[/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#244:17 (setDimensions)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L244:17 (setDimensions))<br />[/vs/workbench/contrib/terminal/browser/terminalInstance.ts#1379:23](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1379:23)<br />

**Comment by Tyriar** [comment]
I believe this isn't getting caught because _defer can be async:

https://github.com/microsoft/node-pty/blob/48bacd0260c9460cb0de6043b72aef0fe0f8b93f/src/windowsTerminal.ts#L148-L149

Not sure what the right fix is atm.

**Comment by Tyriar** [comment]
The right fix for this is probably to return promises in the node-pty defer calls and await them on the VS Code side so the exception can get handled.

**Comment by Tyriar** [comment]
We use ErrorNoTelemetry for this now
