### ISSUE TITLE
Executing command not working on terminal.

### ISSUE THREAD

**Issue by LBbhadula** [microsoft/vscode#93227]
Issue Type: <b>Bug</b>

Hi i am trying to execute my command **go run main.go** on VScode Terminal but every time it popups with "How do you want to open Application"
Same command if i run on CMD, that worked file.

Please suggest the solution 

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (22.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.13.1

</details>

**Comment by Tyriar** [comment]
That means that Go is not on your PATH, I suggest investigating why it's missing and/or asking the go extension.
