### ISSUE TITLE
Parenthesis, Quotation, Curly Brace, Square Brackets, Template Literal Override

### ISSUE THREAD

**Issue by surajitbasak109** [microsoft/vscode#93228]
Dear Developers,
I love the code editor you have introduced to us. But I have a request to fix the issue with Bracket override.
I mean when I am in Sublime Text if I type `()` and whenever my cursor is in middle of that parenthesis and if I press `)` again my cursor goes to the end of closing parenthesis. It doesn't matter how many times I press `)` when my cursor position in center of the parenthesis. Sublime Text does the magic to not put the duplicate `)`.

In Visual Studio Code if first time my cursor is in center of the parenthesis(`()`) and if I press closing bracket(`)`) the cursor goes to the end of closing bracket(`)`) which is fine. But second time if I do this again it creates another closing bracket(`)`) which I is annoying for me.

Sublime Text or Vim does not override this behaviour. So my request is to rectify this problem.

In Sublime Text
![sublime_text](https://user-images.githubusercontent.com/7413104/77310791-ecf5bf80-6d24-11ea-805d-96c7bff572ce.gif)

In VI improved
![vim](https://user-images.githubusercontent.com/7413104/77311795-cb95d300-6d26-11ea-9698-592aa02d8310.gif)

In Visual Studio Code
![vscode](https://user-images.githubusercontent.com/7413104/77310811-f8e18180-6d24-11ea-91bb-8e094074e06c.gif)

So, Please fix the bracket override issue in next major update. It would help my development environment.

**Comment by alexdima** [comment]
By default, only closing brackets that the editor has automatically inserted are being typed over. You can have that all closing brackets are being typed over using `"editor.autoClosingOvertype": "always"`.

**Comment by surajitbasak109** [comment]
@alexdima, thanks for the suggestion. But Visual Studio Code should make the auto closing over type behavior by default. You can close this issue I have asked here. Thanks again.

**Comment by alexdima** [comment]
@surajitbasak109 Thank you for your suggestion, but we have decided to make this behavior opt-in, that is why the setting is not `"always"` by default.
