### ISSUE TITLE
git.stage and git.unstage is not working as a shortcut

### ISSUE THREAD

**Issue by rebyatyonok** [microsoft/vscode#93225]
- VSCode Version: VSCode 1.44 - Insiders
- OS Version: macOS Catalina 10.15.3

As you can see on screenshot, I have a shortcut for staging files, and it is not working. But if I **click** the button - everything works well. 

The same thing goes for the git.unstage command. 

Similar shortcut for git.stageAll and git.unstageAll works fine.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/26152668/77305533-3df6bb00-6d07-11ea-8cbc-6972288e86fb.png">

This is an output of git:
```
git.stage 0
git.getSCMResource.uri undefined
repo root /Users/username/Documents/work/projectFolder
git.stage.getSCMResource null
```

Steps to Reproduce:

1. Add a shortcut for stage a single file
2. Try to use it

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Keyboard shortcuts for commands which depend on the SCM view selection are currently not supported.
