### ISSUE TITLE
Allow splitting of editor "into" existing group 

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode#93231]
I oftentimes use the "split editor" command to have a side by side view of my current file. This works perfectly fine if I'm in a "1 column" View. However, when I'm already in a "2 column" view, the command creates a 3rd column which is hardly ever what I want.

Therefore I'd like to see a new command named `Split editor into next group` (or something the like...) which places the new editor into the next horizontal group or creates a new group if in a "1 column" view.

Alternatively too me it would also be fine if the behavior of the existing command would change...

**Comment by gjsjohnmurray** [comment]
Did you investigate the `View: Move Editor into XXX` commands?

![image](https://user-images.githubusercontent.com/6726799/77317416-0f76e100-6d03-11ea-96c5-e75fd93a1301.png)

**Comment by CombeeMike** [comment]
@gjsjohnmurray Yes, I'm aware of those commands, but I don't really see how they can help me with my described use case?

I could probably create some kind of "command sequence" which performs `Split editor` & `Move to right` afterwards but that needs installation of another plugin which I'd rather refrain from if not absolutely needed.

Am I missing something here?

**Comment by gjsjohnmurray** [comment]
@CombeeMike ah I think I see. Maybe you'd like `Copy Editor into` equivalents on those commands, right?
