### ISSUE TITLE
cursorWordPart{left,right} moves too far

### ISSUE THREAD

**Issue by adzenith** [microsoft/vscode#93239]
Issue Type: <b>Bug</b>

cursorWordPartLeft and cursorWordPartRight move the cursor too far. The cursor moves past the next underscore instead of right before it.

Here's a gif of TextMate, which as far as I know was the first program to have a shortcut for something like this:
![TextMate](https://user-images.githubusercontent.com/614934/77323612-ef87f300-6ceb-11ea-8bb9-69db166c1dfc.gif)

Here's Sublime Text, which works the same way:
![Sublime Text](https://user-images.githubusercontent.com/614934/77323627-f57dd400-6ceb-11ea-9ab4-7064b93c5d99.gif)

And here's VS Code's implementation, which moves past the underscore instead of right up to it. This makes it difficult to change one part of a variable name, because if you select and then type it deletes the underscore.
![VS Code](https://user-images.githubusercontent.com/614934/77323692-0d555800-6cec-11ea-8700-70672cf0bfdf.gif)

I was surprised that I was unable to find anyone else reporting this issue. Perhaps this shortcut isn't used that much? I use it all the time which is why I noticed it. Any chance it could be swapped to work the same way as TextMate and Sublime Text?

VS Code version: Code - Insiders 1.44.0-insider (708b019bb4e20f07cf89df9f1d943af3d38d7a70, 2020-03-18T05:43:24.249Z)
OS version: Darwin x64 18.7.0

**Comment by ArturoDent** [comment]
You can add `_` to your editor wordSeparators.  Put this into your settings:

      "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?_"

note the added `_` at the end.  Now wordPart moves will act as you wish with respect to underscores.

**Comment by nikoargo** [comment]
Thanks for the quick reply! Unfortunately that doesn't do the right thing. If I add `_` to my word separators, then the insertion point (starting from the left) moves like this:
`|foo|_|bar|`
What I want is this:
`|foo_|bar|`

**Comment by adzenith** [comment]
Thanks for the quick reply! Unfortunately that doesn't do the right thing. If I add `_` to my word separators, then the insertion point (starting from the left) moves like this:
`|foo|_|bar|`
What I want is this:
`|foo_|bar|`
(which is what TextMate and Sublime Text both do by default)

**Comment by ArturoDent** [comment]
I am confused, your gifs show TextMate and ST doing this:

|foo|_bar|  .  Adding the underscore to wordSeparators gets you half-way there though, not all the way.

**Comment by adzenith** [comment]
Whoops - you're right. I accidentally put the pipe in the wrong spot. I've fixed my comment.

**Comment by adzenith** [comment]
Wow!! Thanks for the super fast fix! I am very excited for this to show up in my insiders :)

**Comment by ArturoDent** [comment]
I don't see any change in this behaviour as of 

Version: 1.45.0-insider (user setup)
Commit: 44c5185373d5f209cd6c0b5d29a216fb801da34e
Date: 2020-04-10T18:12:33.780Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19603

did this get merged yet?

**Comment by alexdima** [comment]
@ArturoDent Yes, the change is in any VS Code >=1.44. There is a test that asserts the change and it has been verified independently by @Tyriar .  Is it possible you are not testing `cursorWordPartLeft` but `cursorWordLeft` and assuming that would have changed ?
