### ISSUE TITLE
How to fix such bug about workbench core

### ISSUE THREAD

**Issue by ycagelulu** [microsoft/vscode#93238]
Issue Type: <b>Bug</b>

The thing is, the VS code pop up a message saying disable some features, I clicked yes. Then when I did local compile for my Photon, the message below is shown. I don't know how to fix it.
"Could not find task: Compile application (local) for /t:/OfficeSoft/EE1301_IoT_VS/IoTlab3/111"

Extension version: 1.10.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Sorry, more information is needed. What language is that? What extension do you use?
