### ISSUE TITLE
Unable to change keybindings

### ISSUE THREAD

**Issue by Kcko** [microsoft/vscode#93235]
I cannot change keybindings.

See short video (https://bit.ly/33LiTx9)
I cannot open keybiinginds.json via icon on the top right pane.
I cannot edit raw file, because is binary.

How can i do that?

**Comment by sandy081** [comment]
It seems your keybindings file is corrupted. Please delete the file and it shall work.

No idea how it got corrupted, may be you would have known if you have used any extensions that caused it.

**Comment by Kcko** [comment]
@sandy081 
It didn´t help. I uninstall VSC and manually delete settings & all files that remains after uninstaling and installed clean version and after import all backuped settings.

Now is everything fine.

**Comment by sandy081** [comment]
Ok. Sorry that I am not helpful here. Not sure how your file got corrupted.
