### ISSUE TITLE
Flow code highlighting with exact object

### ISSUE THREAD

**Issue by penx** [microsoft/vscode#93245]
- VSCode Version: 1.43.1
- OS Version: Mac OS X 10.15.3

Steps to Reproduce:

1. Open or create a project with Flow
2. Create a new JavaScript file
3. Set syntax to 'JavaScript React'
4. Paste in the following code

```jsx
// @flow
export const CorrectHighlight = () => 'example';

export const MyComponent = (someObject: {
	someProp: {| something: number |},
}) => 'example'

export const HighlightingBroken = () => 'example';
```

Note highlighting is incorrect on the last line:

![Screenshot 2020-03-23 at 14 46 55](https://user-images.githubusercontent.com/1027024/77328924-27576080-6d15-11ea-9544-df1e05e1386e.png)

Does this issue occur when all extensions are disabled?: Yes

![Screenshot 2020-03-23 at 14 47 26](https://user-images.githubusercontent.com/1027024/77328969-38a06d00-6d15-11ea-9e42-972455b047e8.png)

**Comment by mjbvz** [comment]
You need to install a Flow language grammar. Our built-in JavaScript React grammar does not support Flow
