### ISSUE TITLE
VSCode can't access php executable

### ISSUE THREAD

**Issue by spoyntersmith** [microsoft/vscode#93244]
Issue Type: <b>Bug</b>

Cannot validate since /usr/bin/php is not a valid php executable. Use the setting 'php.validate.executablePath' to configure the PHP executable.

- [x] Tried Disabling all Extensions

Source: PHP Language Features (Extension)

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:17:38.324Z)
OS version: Linux x64 5.3.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2421)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (4.07GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
laravel-extra-intellisense|ami|0.2.5
chronicler|arc|0.1.7
woocommerce|cla|1.1.0
laravel-goto-view|cod|1.3.2
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
vscode-pull-request-github|Git|0.15.0
phpcs|ika|1.0.5
vscode-peacock|joh|3.6.0
php-cs-fixer|jun|0.1.141
php-xdebug|kak|0.0.7
chat|kar|0.32.1
vscode-github|Kni|0.30.3
php-namespace-resolver|Meh|1.1.8
vscode-docker|ms-|1.0.0
mssql|ms-|1.9.0
vsliveshare|ms-|1.0.1783
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
laravel5-snippets|one|1.8.0
laravel-artisan|rya|0.0.27
html-preview-vscode|tht|0.2.5
screen-recorder|wk-|0.0.2

</details>

**Comment by roblourens** [comment]
I think the error message describes the issue - what's the problem?

**Comment by spoyntersmith** [comment]
The error keeps displaying in vscode, "/usr/bin/php" is definitely the correct path and I can use it from terminal.

I've set the following option in settings.json
    "php.validate.executablePath": "/usr/bin/php",
as suggested here https://code.visualstudio.com/docs/languages/php

I've verified that PHP is installed, I can also run php commands from terminal too.

**Comment by spoyntersmith** [comment]
I believe this error only happens when @builtin PHP Language Features is still enabled.
Which I didn't do during setup, the instructions were found [here](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).
So using intelephense only now.
I'm surprised that the core feature doesn't seem to be able to connect to /usr/bin/php.

Think this could be closed
