### ISSUE TITLE
Live share not working

### ISSUE THREAD

**Issue by wade-montague** [microsoft/vscode#93243]
Issue Type: <b>Bug</b>

Try to open live share session and get error message 

command 'liveshare.start' not found

This has only started happening in the last couple of weeks as I'm a regular long term user of liveshare with all of my team  

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 12, 9|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.1
vscode-styled-jsx|bla|1.5.0
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.7.0
gitlens|eam|10.2.1
vscode-phpmd|eco|1.2.0
prettier-vscode|esb|3.20.0
file-icons|fil|1.0.22
vscode-peacock|joh|3.6.0
vscode-styled-components|jpo|0.0.29
chat|kar|0.32.1
syntax-project-pbxproj|mar|0.1.3
vscode-docker|ms-|1.0.0
vsliveshare|ms-|1.0.1783
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
vscode-react-native|msj|0.14.2
vscode-jest|Ort|3.1.1
quicktype|qui|12.0.46
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.2.6
quokka-vscode|Wal|1.0.284
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

(3 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/MicrosoftDocs/live-share/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)

**Comment by wade-montague** [comment]
Will do thank you.
