### ISSUE TITLE
vscode command 'PowerShell.RunSelection' not found

### ISSUE THREAD

**Issue by marfoned** [microsoft/vscode#93240]
hello all,
i'm trying to execute part of script in powershell from vscode, but when i click on F8, or try to run the selection i get the following messages:
command 'PowerShell.RunSelection' not found

Client Windows 10
VSCode 1.43.1

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/powershell/vscode-powershell/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)
