### ISSUE TITLE
No Mocha test results in VS Code Debug Mode (TypeScript, async, fast-running, mocha tests)

### ISSUE THREAD

**Issue by n8sabes** [microsoft/vscode#93249]
**Problem:** No Mocha test results output to integrated-console in VS Code Debug Mode for TypeScript fast-running async tests.

1. The problem **does not** occur when executing the test in the console.
2. The problem **only occurs** when running the test in debug mode w/o breakpoints and the test is fast/short-running.

**Related issue:** [Mocha Issue #4213](https://github.com/mochajs/mocha/issues/4213)

**Environment:**
Mocha: 7.1.1
TypeScript: 3.8.3
Mac OS X: 10.15.3
VS Code: 1.44.0-insider

--> I have not found an existing issue in VS Code Issues, but please associate if one exists.

launch.json configuration:
```
        {
            "type": "node",
            "request": "launch",
            "name": "Fast Test",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "-r",
                "ts-node/register",
                "--timeout",
                "999999",
                "--colors",
                "--require=.env-test.ts",
                "${workspaceFolder}/tests/code-tests/fast_test.ts",
            ],
            "console": "internalConsole",
            "internalConsoleOptions": "neverOpen",
            "protocol": "inspector"
        },
```

fast_test.ts:
```
    it('Fast Test 1', async () => {
        assert(true);
    });

    it('Fast Test 2', async () => {
        assert(true);
    });
```

**Comment by n8sabes** [comment]
**WORKAROUND**

_This is the workaround I'm using to slow the test and allow output to flow to the integrated-console. The 500ms~1000ms delay may need to be adjusted based on target processor speed._

```
const sleep = promisify(setTimeout);

describe(`${__filename.slice(__dirname.length + 1).replace(/\.[^/.]+$/, "")} Tests`, () => {

    let gTestStartTime = Date.now();

    it('Fast Test 1', async () => {
        assert(true);
    });

    it('Fast Test 2', async () => {
        assert(true);
    });

    after('After running tests', async () => {
        // Force a delay
        const execTime = Date.now() - gTestStartTime;
        execTime < 1000 && await sleep(1000 - execTime);
    });
});
```

**Comment by connor4312** [comment]
Since this issue was written we have a [new debugger](https://github.com/microsoft/vscode-js-debug/) which has better behavior around ensuring that output is flushed before the process exits. Please let us know if you're still running into this issue in VS Code 1.50 or above.
