### ISSUE TITLE
Python Intelisense Module Detection

### ISSUE THREAD

**Issue by Shirsendu-Bairagi** [microsoft/vscode#93246]
Version: 1.43.1 (user setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Hi Python intelisense is not detecting a imported module which is installed via pip saying "unresolved import 'pyautogui'" but then i run the file which runs correctly.

Steps to Reproduce:
1.Just import any module which is not built-in
2.Use python 3.8.2 64-bit

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)
