### ISSUE TITLE
running django tests with --pattern results in 'Ran 0 tests'

### ISSUE THREAD

**Issue by nroberts1** [microsoft/vscode#93251]
- VSCode Version: 1.43.1
- OS Version: Ubuntu 18.04
- Python 3.7.6

Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:17:38.324Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic snap

Steps to Reproduce:

1. Using launch.json config of:
        {
            "name": "Python: Django Test Current",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "integratedTerminal",
            "justMyCode": false,
            "args": [
                "test",
                "--pattern='*${fileBasenameNoExtension}.py'",
                "--failfast",
                "--keepdb"
            ],
            "django": true
        },
2. select debugger in vscode and run the above config having test file open and selected in editor
3. Result is:
**env DEBUGPY_LAUNCHER_PORT=38999 /home/nathan/.pyenv/versions/app_name/bin/python /home/nathan/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher /home/nathan/Development/app_name/manage.py test --pattern='*test_km_concepts.py' --failfast --keepdb
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK**

4. Removing '--pattern' argument means all tests are picked up including the ones in this file, so it doesn't seem to be a python environment issue.

5. Using --pattern from command line runs fine 
python manage.py test --pattern='*test_km_concepts.py' --failfast --keepdb
**Ran 5 tests in 11.989s

OK
Preserving test database for alias 'default'...**

Does this issue occur when all extensions are disabled?: Python extension is essential for python, but disabled other extensions and still occurs

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)

**Comment by nroberts1** [comment]
Yes will do, thanks
