### ISSUE TITLE
can't keyboard around settings

### ISSUE THREAD

**Issue by derekriemer** [microsoft/vscode#93254]
Issue Type: <b>Bug</b>

1. Try moving around settings with the keyboard.
2. Attempt to quickly jump from section to section.

Expected: This should be doable with the treeview.
Actual: Tab traps make this impossible, and moving around is non-trivial. the tree's children are whole sections which makes the role="tree" paradime break, because the treeitem role should not have children. Perhaps using a separate tree, or an accordian would be better here, depending on what's visible.

VS Code version: Code - Insiders 1.44.0-insider (0926b534553f3ff2f0cff0a741550a97df199706, 2020-03-23T08:40:59.737Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.59GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Sorry, I'm not sure exactly what you are referring to, which tree/sections? This issue might be relevant if you are using a screenreader https://github.com/microsoft/vscode/issues/92488

**Comment by derekriemer** [comment]
I wasn't able to arrow between sections of settings on my work computer (I.E. from edit to workbench, etc. I am on my home machine. I am not sure why that was happening, perhaps I'll have to try again when I'm at work.

**Comment by derekriemer** [comment]
I cannot reproduce this again.
