### ISSUE TITLE
New "Run Selection" method breaks on switch statement

### ISSUE THREAD

**Issue by mbiver** [microsoft/vscode#93259]
Issue Type: <b>Bug</b>

I was working on my script last Friday and the switch statement below was working just fine when using "Run Selection" in VS Code.  The PowerShell below also runs fine when the script is executed in a regular powershell window.  There must have been an upgrade to VS Code over the weekend and now the "Run Selection" seems to be behaving differently and the switch statement below throws an error.

"At line:1 char:28
+     Switch($addressPrefix){
+                            ~
Missing condition in switch statement clause.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingSwitchConditionExpression
 "

Sample.  

    Switch($addressPrefix){

        10.0.0.0/16{$subnetPrefix = "10.0.0.0/24";$gwSubnetAddressPrefix = "10.0.1.0/24"}
        10.1.0.0/16{$subnetPrefix = "10.1.0.0/24";$gwSubnetAddressPrefix = "10.1.1.0/24"}
        10.2.0.0/16{$subnetPrefix = "10.2.0.0/24";$gwSubnetAddressPrefix = "10.2.1.0/24"}
        10.3.0.0/16{$subnetPrefix = "10.3.0.0/24";$gwSubnetAddressPrefix = "10.3.1.0/24"}
        10.4.0.0/16{$subnetPrefix = "10.4.0.0/24";$gwSubnetAddressPrefix = "10.4.1.0/24"}
        10.5.0.0/16{$subnetPrefix = "10.5.0.0/24";$gwSubnetAddressPrefix = "10.5.1.0/24"}
        10.6.0.0/16{$subnetPrefix = "10.6.0.0/24";$gwSubnetAddressPrefix = "10.6.1.0/24"}
        10.7.0.0/16{$subnetPrefix = "10.7.0.0/24";$gwSubnetAddressPrefix = "10.7.1.0/24"}
        10.8.0.0/16{$subnetPrefix = "10.8.0.0/24";$gwSubnetAddressPrefix = "10.8.1.0/24"}
        10.9.0.0/16{$subnetPrefix = "10.9.0.0/24";$gwSubnetAddressPrefix = "10.9.1.0/24"}        

    }
    

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Please start by filing this issue against the powershell extension

**Comment by mbiver** [comment]
Thanks, I've filed this against the PowerShell Extension.
