### ISSUE TITLE
Debugger still stopping at line after removing breackpoint

### ISSUE THREAD

**Issue by wmpauli** [microsoft/vscode#93250]
Issue Type: <b>Bug</b>

I am experience an issue that might be the same as this: https://github.com/Microsoft/vscode/issues/64072.

After removing a breakpoint, the debugger still stop in the line where the breakpoint used to be. Unfortunately, I cannot offer steps for reproducing at this point, but will now pay closer attention, and will follow up as soon as I have more info. 

CC: @isidorn .

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-1071-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: wopaulimlads.westus2.cloudapp.azure.com|
|OS|Linux x64 4.15.0-1071-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (6 x 2596)|
|Memory (System)|55.02GB (53.67GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.50.1
remote-ssh-edit|ms-|0.50.1
python|ms-|2020.3.69010

</details>

**Comment by wmpauli** [comment]
Here is a screenshot that shows the breakpoint removed in line 78. The debugger still stopped there. The removed breakpoints is still listed in the "BREAKPOINTS" window frame at the bottom left.

![image](https://user-images.githubusercontent.com/6539145/77336893-640b6380-6ce5-11ea-8617-5fdc5a9138aa.png)

**Comment by wmpauli** [comment]
Note, disabling/deleting the breakpoint in the "BREAKPOINTS" windows resolves the issue.

**Comment by isidorn** [comment]
@wmpauli thanks for opening the issue. However it is not the same issue as the one you linked, since this is happening for python.
The python extension is sending us stopped events and telling the VS UX when to stop. Thus this is controlled by the python extension. And it would be great if you open this issue here https://github.com/microsoft/vscode-python

I appologize for not communicating this straight away, I was not aware you are doing python.
If you are busy I can also move this issue to the python repo.
