### ISSUE TITLE
Debugging test in VS Code does not work

### ISSUE THREAD

**Issue by asipras** [microsoft/vscode#93255]
- VSCode Version: 1.43.1
- OS Version: Windows NT x64 10.0.18363

Steps to Reproduce:

1. Try to debug tests using unit test library, Click on the small bug icon for an individual test  to debug.
2. I get a dialog box error saying **Invalid message: Duplicate entries in "env"**. The two options i get are Open launch.json and Cancel.

I have checked my launch.json file i do not see any duplicate env entries. All entries are unique. What is interesting is that when I run the test (not in debug mode) they execute fine. 

Does this issue occur when all extensions are disabled?: No. The issue is that when i try to debug the test VS code throws an error prompt.

**Comment by aeschli** [comment]
For what language is that?

**Comment by asipras** [comment]
@aeschli  i am using vs code for debugging test in python.

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)

**Comment by asipras** [comment]
will do that @aeschli
