### ISSUE TITLE
Git commit amend

### ISSUE THREAD

**Issue by ebrown-SL** [microsoft/vscode#93258]
Issue Type: <b>Feature Request</b>

When amending a commit, the commit message no longer contains new lines. This means you have to amend the previous commit message via command line to add the new line characters back in to keep the formatting of the git commit message.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/40295
