### ISSUE TITLE
ctrl+F find does nothing now

### ISSUE THREAD

**Issue by cottrell** [microsoft/vscode#93266]
On Ubuntu. 

Suddently stopped working. restart fixes for a while.

can type in field but then nothing.

**Comment by roblourens** [comment]
Can you explain the problem some more? Does anything at all happen when you type in the find field? What version of vscode?

**Comment by cottrell** [comment]
I realize my comment is pretty useless, but what I am asking is *where* should I be looking (logs etc) to try to get more useful information when this is happening? 

I don't think there is much hope of getting anywhere without me finding a few more clues to paste.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by cottrell** [comment]
So here is one clear example: ctrl+f searching for "best" IN THE FILE ONLY, it find two entries and I can toggle bettween them. It *does not fine* "something_best". It's like it is inserting whitespace. Slash in vim mode works and it finds all the entries. 

This is a pretty new bug. Not sure if an update did it.

**Comment by cottrell** [comment]
https://developercommunity.visualstudio.com/content/problem/316778/whole-word-find-in-files.html

**Comment by roblourens** [comment]
I don't know what that link is supposed to show, but it sounds like you have whole-word search toggled on. Check whether that middle button in the find viewlet is turned on (with a background/border color)

**Comment by cottrell** [comment]
I restarted and it went away but it seems plausiable this is the cause. I don't think this visual tools are helpful. You can do all of this with regex or vim etc. We should strive to make all "UI" based tricks UGLY and BOLD. So anything nonstandard (click this, check that, should be RED and look broken). Visually impaired will not notice. There is a reason evevery uses vim or the other editor which I will not name.

**Comment by roblourens** [comment]
This is customizable if you prefer something like this:

![image](https://user-images.githubusercontent.com/323878/78041811-d4923000-7336-11ea-9581-04f6aab2da08.png)

Let me know if the problem shows up again
