### ISSUE TITLE
Add New Margin Options to DecorationRenderOptions

### ISSUE THREAD

**Issue by Mochnant** [microsoft/vscode#93260]
It would be useful to have an option to modify margins (CSS margin, margin-top, etc) in **DecorationRenderOptions** (https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions).

This would likely be useful in many places, but is being specifically driven by a request to the extension **Todo Tree** (https://github.com/Gruntfuggly/todo-tree/issues/290).

**Comment by piersdeseilligny** [comment]
This would also be extremely useful for my [betterfountain](https://github.com/piersdeseilligny/betterfountain) extension, as it would allow a more WYSIWYG type of behaviour. I can also see it being useful for other extensions which provide support for markup-type languages.
