### ISSUE TITLE
Welcome view content doesn't play nicely with i18n

### ISSUE THREAD

**Issue by Sebasdroid98** [microsoft/vscode#93269]
Issue Type: <b>Bug</b>

Al instalar el idioma español para programa, este pierde "botones/opciones" en la parte del explorador de archivos, los botones de "abrir carpeta" cambia a (command:workbench.action.files.openfolder) y "Clonar repositorio" cambia a (command:git.clone), las opciones en ingles son: Open Folder y Clone repository. Gracias por la atención prestada.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.85GB (6.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.1
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
code-runner|for|0.9.17
vscode-docker|ms-|1.0.0
vscode-language-pack-es|MS-|1.43.6
mssql|ms-|1.9.0
python|ms-|2020.3.69010
laravel-blade|one|1.20.0
bootstrap-v4-snippets|Zac|1.1.3

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/53841705/77368694-c9357800-6d2a-11ea-979b-6aaa0142348d.png)

![image](https://user-images.githubusercontent.com/53841705/77368727-dc484800-6d2a-11ea-93aa-5ff534638886.png)

**Comment by mjbvz** [comment]
> When you install the Spanish language for program, it loses "buttons/options" in the file explorer part, the "open folder" buttons changes to (command:workbench.action.files.openfolder) and "Clone Repository" changes to (command:git.clone), the options in English are: Open Folder and Clone Repository. Thank you for the attention given.

**Comment by nousmedis** [comment]
Same error here. It's present in Mac OS and Ubuntu Linux, so it's a wide extended bug.

**Comment by joaomoreno** [comment]
This is fixed in `master`.
