### ISSUE TITLE
Enabling word wrapping is not working

### ISSUE THREAD

**Issue by ferrecromain** [microsoft/vscode#93267]
- VSCode Version: 1.43.1
- OS Version: 10.0.18363.720

Steps to Reproduce:

1. in settings : Editor: wordWrap = "wordWrapColumn" and Editor: Word wrap column = 80
2. From menu View > Enable toggle word wrap
3. Create a new .md file
4. Writing text on one line and more than 80 chars is possible

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of #72559

#74195 Would make this more discoverable

**Comment by ferrecromain** [comment]
Yes, thanks you @mjbvz, so as it seems that these settings are applied for languages that do not have default word wrapping rules (unlike markdown). We have to override them.
