### ISSUE TITLE
Persistent syntax errors when content does not match the default type

### ISSUE THREAD

**Issue by jhoneill** [microsoft/vscode#93271]
### VSCode extensions:
```
andyyaldoo.vscode-json@1.5.0
ms-azure-devops.azure-pipelines@1.165.1
ms-azuretools.vscode-azurefunctions@0.21.0
ms-dotnettools.csharp@1.21.15
ms-mssql.mssql@1.9.0
ms-vscode-remote.remote-containers@0.106.0
ms-vscode-remote.remote-ssh@0.50.0
ms-vscode-remote.remote-ssh-edit@0.50.0
ms-vscode-remote.remote-wsl@0.42.4
ms-vscode-remote.vscode-remote-extensionpack@0.20.0
ms-vscode.azure-account@0.8.8
ms-vscode.powershell@2020.3.0
ms-vscode.powershell-preview@2020.3.0
```

- OS Version:
```
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
```

This was originally raised  here https://github.com/PowerShell/vscode-powershell/issues/2572 but it turns out not to be a PowerShell specific issue and affects (e.g.) C#

Steps to Reproduce:
When the default file type is PowerShell, and something else (e.g. JSON) is pasted into a new Window many syntax errors are detected and shown in the problem window
![image](https://user-images.githubusercontent.com/16209593/77182107-27145680-6ac4-11ea-9e2c-b576980d5515.png)

However if the document type changed to JSON or Plain Text the errors are not removed

![image](https://user-images.githubusercontent.com/16209593/77182398-99853680-6ac4-11ea-9661-917e2106e08e.png)

Even if the file is closed the errors remain 

![image](https://user-images.githubusercontent.com/16209593/77182864-5b3c4700-6ac5-11ea-8c8d-4b4a20c58543.png)

It appears code does not tell the default extension to stop reporting errors. 
https://github.com/PowerShell/vscode-powershell/issues/2572#issuecomment-602756070 shows an example with c#

**Comment by jrieken** [comment]
> It appears code does not tell the default extension to stop reporting errors.

We also don't ask it to start reporting errors. The error reporting model is a "push model" - that means extension decide when and for which file to add and remove errors, warning etc. It's also their responsibility to take them away. fyi @TylerLeonhardt

**Comment by jhoneill** [comment]
So we're saying multiple extensions have the same failure, but it's definitely in those extensions.

**Comment by jrieken** [comment]
yes - prove me wrong

**Comment by jhoneill** [comment]
Just double checking my understanding :-)  I thought it was an extension problem, and the author says "well it happens in other extensions"  - I think one assumes the fault isn't repeated in many extensions but that that assumption can be mistaken. I don't expect you to proved wrong, I wouldn't attempt it myself :-)

**Comment by gjsjohnmurray** [comment]
See also #66982

**Comment by TylerLeonhardt** [comment]
@jrieken the only request that comes through that I can see is `textDocument/codeAction` with the following payload:

```json
{
    "textDocument": {
        "uri": "file:///Users/tyleonha/Code/PowerShell/Misc/foo/gci.ps1"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 3
        },
        "end": {
            "line": 0,
            "character": 3
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 0,
                        "character": 3
                    }
                },
                "message": "'gci' is an alias of 'Get-ChildItem'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.",
                "severity": 2,
                "code": "PSAvoidUsingCmdletAliases",
                "source": "PSScriptAnalyzer"
            }
        ]
    }
}
```

There's no way for a language server to know that the file had its language changed without querying VS Code which would be silly and a perf hit.

What's the recommendation for a language server to handle this request?

**Comment by jrieken** [comment]
> There's no way for a language server to know that the file had its language changed without querying VS Code which would be silly and a perf hit.

When the language changes, the VS Code sends a close and open event.

https://github.com/microsoft/vscode/blob/d778f85cd5f23391cf94fa0965ada594c68e1fc5/src/vs/vscode.d.ts#L8798-L8820
