### ISSUE TITLE
skipFiles not work at all in debug!

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#93272]
Bug here when use `--remote-debugging-port` with any framework SDK with chromium debugger!!
The chrome developer tool continue to emit breakpoint.
Example debugger
```json
    "configurations": [
        {
            "type": "nwjs",
            "request": "launch",
            "name": "Launch NWjs",
            "runtimeExecutable": "${workspaceRoot}/node_modules/nw/nwjs/nw.exe",
            "runtimeArgs": [
                "--remote-debugging-port=9222",
            ],
            "webRoot": "${workspaceRoot}/src/",
            "port": 9222,
            "reloadAfterAttached": true,
            "sourceMaps": false,
            "skipFiles": [
                "${workspaceRoot}/node_modules/**/*.js",
                "${workspaceRoot}/src/vendor/handsontable.js",
              ]
        },
    ]
```
And check all exception
![image](https://user-images.githubusercontent.com/24865815/77376903-f6445380-6d47-11ea-9b76-2ac2be1946dc.png)

![vscode ignor debug  files](https://user-images.githubusercontent.com/24865815/77376138-ee83af80-6d45-11ea-9fc3-ad5ee878547d.gif)

Any trick or help about this ?
-----------------
Version : 1.43.1 (user setup)
Validation : fe22a9645b44368865c0ba92e2fb881ff1afce94
Date : 2020-03-18T07:01:20.184Z
Électron : 7.1.11
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Windows_NT x64 10.0.18363

**Comment by djmisterjon** [comment]
ok after hours , find a temporary solution.
Work for me so i share :)
Solution, copy the app binary adresse from chrome.
![image](https://user-images.githubusercontent.com/24865815/77377262-f55ff180-6d48-11ea-84fc-f45d6319478d.png)

**Comment by roblourens** [comment]
The `nwjs` debugger is from an extension that we don't own, and I'm not sure if it does something different than node/chrome, sorry.
