### ISSUE TITLE
premission request

### ISSUE THREAD

**Issue by ysreenu** [microsoft/vscode#93274]
Issue Type: <b>Bug</b>

When ever changing everytime i have to enter password to save the changes

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
Do you see this in VS Code 1.43?

**Comment by ysreenu** [comment]
yes using 1.4.1 version

**Comment by mjbvz** [comment]
What about in VS Code 1.43?
