### ISSUE TITLE
Allow to open file with line/col information added in brackets

### ISSUE THREAD

**Issue by akrantz** [microsoft/vscode#93278]
Issue Type: <b>Feature Request</b>

I copied from a build log to open a file with a build error. On the Windows command line I ran:

code F:\dev\api\main.cs(11,55)

It opened up a new file as if the file name is  "main.cs(11,55)".

It would be great if it could realize that there is a trailing part that indicates a line number or line and column. There could be various syntaxes supported for one or two numbers within a separator where it could open the file and then go to that line and column.

file.ext(15)     // go to line 15
file.ext(15,30)     // go to line 15, column 30

There are probably a few different variations that are prevelent for compiler error output and log files. It would be great to allow it to be smart and handle common scenarios easily. 

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
We currently only support line/col separated by colon `:` and require the `--goto` option.

**Comment by akrantz** [comment]
Yes, I discovered this after opening the bug. It would be nice to have this be handled automatically without requiring the --goto and more flexibly instead of only supporting colons as separators.

The goal here is to be able to copy from log files directly and not have to modify the copied string to conform to a limited syntax but rather handle it automatically when the line/col info is present on the end.
