### ISSUE TITLE
[js] syntax highlight goes to wrong by 'function' method

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#9327]
- VSCode Version: 1.4.0-insider (and 1.3.1)
- OS Version: Windows 7

Steps to Reproduce:

1. write a call of `function` method.

![image](https://cloud.githubusercontent.com/assets/1937871/16871368/7c1e484c-4ac1-11e6-9e1a-fcf9fed0e42c.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#214
