### ISSUE TITLE
Auto-complete registerCompletionItemProvider is not working when language is yaml.

### ISSUE THREAD

**Issue by chelsealopentinum** [microsoft/vscode#93279]
I am  testing vscode 1.43.1 example from [vscode-extension-sample: completions](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample) and have some issues.
When I set registerCompletionItemProvider language option to "yaml", the auto complete is not working anymore until I uninstall the [yaml extension](https://github.com/redhat-developer/vscode-yaml). 
It worked on vscode 1.42.1 with yaml extension. Does anybody encounter the same issue?

- VSCode Version: 1.43.1
- OS Version: Mac os mojave 10.14.5
- YAML Extension Version: 0.7.2

Steps to Reproduce:
1. Install YAML extension.
2. Using vscode-extension-sample: completions and modify the language  option to "yaml".

**Comment by jrieken** [comment]
>  the auto complete is not working anymore until I uninstall the yaml extension.

What does that mean? Isnt the provider called anymore or aren't its results not showing anymore?

**Comment by chelsealopentinum** [comment]
When I run with debug mode that show the provider called successful.
But Its results not showing anymore.
![image](https://user-images.githubusercontent.com/50311343/77402141-2abc1c00-6de9-11ea-9031-85b51177391b.png)

**Comment by jrieken** [comment]
> But Its results not showing anymore.

In what scenarios? When doing ctrl+space on an empty line?

**Comment by chelsealopentinum** [comment]
> > But Its results not showing anymore.
> 
> In what scenarios? When doing ctrl+space on an empty line?

I am testing this case from vscode-extension-sample: completions and modify the language to yaml.
code here:
https://github.com/microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts#L49
There trigger character is `.`.

I input `console.` In the empty yaml file and there has no item to show.
![nnn](https://user-images.githubusercontent.com/50311343/77405129-b2a42500-6ded-11ea-9c81-c2734104a87d.gif)

When I disable YAML extension, it seems work.
![yy](https://user-images.githubusercontent.com/50311343/77405543-4e359580-6dee-11ea-8c18-f40877878bc1.gif)

**Comment by jrieken** [comment]
> When I disable YAML extension, it seems work.

what do you expect me to do? this seems to be something with yaml, maybe its word definition?

**Comment by chelsealopentinum** [comment]
> > When I disable YAML extension, it seems work.
> 
> what do you expect me to do? this seems to be something with yaml, maybe its word definition?

I expect the yaml auto-complete results will show in vscode version 1.43.1 with yaml extension. Because it **worked on vscode 1.42.1** with yaml extension. After I upgrade **vscode version to 1.43.1 then it did not work.**

**Comment by jrieken** [comment]
Ok - then please file an issue against the yaml extension

**Comment by chelsealopentinum** [comment]
@jrieken 
Let me clear the question:

In vscode 1.42.1, I develop an auto-complete extension sample with the official guide `vscode-extension-sample: completions` which make sure that can work on `YAML`.
https://github.com/microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts#L49

But after upgrading to 1.43.1, the sample extension is not working anymore on `YAML` file unless I disable the `YAML Extension` and in the mean time the sample code is not modified. On the other hands, it's still working on `TEXT` file.

I try to debug the sample extension code but everything seems to go well as usual except the CompletionList Popup does not show up.
I thought that it suppose to relate to the language identifiers determination rather than `YAML Extension`.

Do you have any further idea about this issue?
