### ISSUE TITLE
File Doesn't Auto-reload When The Window is Out-Of-Focus on macOS

### ISSUE THREAD

**Issue by johnshamoon** [microsoft/vscode#93277]
Issue Type: <b>Bug</b>

**Steps to Reproduce**
1. Open VSCode.
2. Create a file: output.log
3. Continuously write output to output.log
- e.g. `while true; do echo "1\n"; done > output.log`
4. Focus the VSCode window

Expected Result: The file continuously reloads to show the newest changes on disk (if no changes have been made in VSCode), even when focused on another window.

Actual Result : The file reloads once and doesn't reload until the window is unfocused and then focused again.

This works very well on Linux, but it doesn't appear to work on Mac.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (4.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
LogFileHighlighter|emi|2.7.1
android-system-tools|fli|0.0.2
compare-folders|mos|0.8.0
cpptools|ms-|0.26.3
vscode-auto-scroll|pej|1.0.3
vim|vsc|1.13.1
material-theme|zhu|3.2.4
vscode-proto3|zxh|0.4.2

(2 theme extensions excluded)

</details>

**Comment by johnshamoon** [comment]
My use case for this is that I'm piping boot logs from a device to a file and viewing that file in VSCode (similar to `tee` on Linux). I would like it to render the new lines at the end of the file as soon as they're piped to the file.

I don't make changes to the logs I pipe in, but in another use case, it could cause inconsistencies between the file contents loaded in VSCode and the file contents on disk. This would cause the error bubble:
```
Failed to save 'output.log'. The content of the file is newer.
Please compare your version with the file contents or overwrite the contents of the file with your changes.
```

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

We have some logging in place to report back file changes to the dev console, can we try it and see if you get the events:
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

**Comment by johnshamoon** [comment]
Sure, here's the output: [console.log](https://github.com/microsoft/vscode/files/4376780/console.log).

**Comment by bpasero** [comment]
@johnshamoon so I see file events for `file:///Users/johnshamoon/Desktop/output.log`, is that the file? I see only 1 event though, did you change it many times?

If possible is there a way for me to reproduce what you do on my machine?

**Comment by johnshamoon** [comment]
Yes, that's the file. The file should have been almost constantly changing. For reference, the next time I unfocused and refocused the window, thousands of lines had been appended to the end of the file.

I am piping logs from a device booting up. I imagine you can reproduce it by building something (vscode?) from source and redirecting stdout to a file, or even a very simple bash script. I'll try to record a video on Linux and then again on macOS to make this a bit easier!

**Comment by bpasero** [comment]
@johnshamoon another question: is this a window with a) no folder opened, b) 1 folder opened or c) a multi root workspace? Can you try if it reproduces from opening a folder or opening a workspace with mutliple folders? We use different watchers in those cases.

**Comment by johnshamoon** [comment]
This in a window with a folder open (~/Desktop, where the output.log is located). I just opened a file that is not in an opened VSCode folder / workspace (~/file.log), and it seems to be working as expected!

**Comment by bpasero** [comment]
@johnshamoon not sure, are you a node.js/JS developer and could try a standalone example using our file watcher library: https://github.com/paulmillr/chokidar

Curious if this is just the file watcher not working (which I suspect), or VSCode.

**Comment by johnshamoon** [comment]
@bpasero Not quite, I work on operating systems and embedded systems. I _may_ have some time to try it out tomorrow if you don't beat me to it. Assuming the difference between the two methods (opened folder vs single file) is just the file watcher, I agree. I would suspect it's the file watcher.

For posterity, the attached file contains two videos demonstrating the difference between Linux and macOS. Both files are opened in a folder (\~/Desktop).
[mac_vs_linux.zip](https://github.com/microsoft/vscode/files/4379703/mac_vs_linux.zip)

**Comment by bpasero** [comment]
@johnshamoon ok it should be easy to try out with this:
* git clone https://github.com/bpasero/chokidar-test.git
* install node.js 12.x (https://nodejs.org/en/download/)
* open a terminal and type `node index.js` from that cloned repo

It will then watch the folder you checked out for file changes. You can point it to another folder though, e.g. your desktop by changing this line: `chokidar.watch(__dirname` to `chokidar.watch("desktop path"`

**Comment by johnshamoon** [comment]
Sorry for the delay @bpasero. I can confirm that the file watcher doesn't update on every write to the file/folder. It looks like it only updates on the first and last write. I've attached a video.

[file_watcher.mov.zip](https://github.com/microsoft/vscode/files/4416466/file_watcher.mov.zip)

**Comment by bpasero** [comment]
@johnshamoon great, could you report this to https://github.com/paulmillr/chokidar then?
