### ISSUE TITLE
CLI: move --telemetry under the Troubleshooting category

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93283]
I just noticed a new `--telemetry` CLI arg. This does not seem like the normal thing to execute in day to day business so I would suggest to move it out of the `Options` category into another place such as `Troubleshooting`. 

![image](https://user-images.githubusercontent.com/900690/77393021-857b5680-6d9c-11ea-8867-3dd2a71baf6f.png)

Besides, why was this added? Does it need to be so prominent? Can we not have this on some website?

//cc @kieferrm

**Comment by Tyriar** [comment]
There was a little debate earlier about whether this should be a CLI at all and I think it was added in the end for added transparency. With a simple command you can print out information on all telemetry that is gathered in the product. I do question it somewhat if it's not even mentioned on https://code.visualstudio.com/docs/getstarted/telemetry though.

**Comment by Tyriar** [comment]
I think @JacksonKearl worked on this

**Comment by bpasero** [comment]
Another alternative is to have a command in the command palette that opens an editor with all these keys.

**Comment by JacksonKearl** [comment]
I have no recollection of this.

https://github.com/microsoft/vscode/blob/7a20db3ee450d0e08f10421c04aeff489c1bc980/src/vs/platform/environment/node/argv.ts#L52 should be a matter of changing this `cat: 'o'` to a `cat: 't'` if we decide to recategorize.

**Comment by bpasero** [comment]
@JacksonKearl yes please do
