### ISSUE TITLE
browse.databaseFilename/${workspaceFolderBasename} fails when subdirectory isn't created first

### ISSUE THREAD

**Issue by boocs** [microsoft/vscode#93288]
# State

### State: Global User settings.json

```
    "C_Cpp.default.browse.databaseFilename": "k:\\.vscode\\cache\\browse\\${workspaceFolderBasename}\\global.vs.db"
```
1. Setting: C_Cpp.default.browse.databaseFilename
2. Value: "k:\\\\.vscode\\\\cache\\\\browse\\\\${workspaceFolderBasename}\\\\global.vs.db"

### State: Cache directory
* k:\\\\.vscode\\\\cache
* No subdirectories except for ipch (intellisense cache)
* k:\\\\.vscode\\\\cache\\\\browse isn’t created yet

### State: System
* Windows 10 (latest)
* VSCode (1.43.1)

### State: Extensions
* cpptools | ms- | 0.26.3

 # Results
    It works, but you have to start VSCode twice:

### Results: First Startup
1. VSCode creates k:\\\\.vscode\\\\cache\\\\browse
2. \\\\${workspaceFolderBasename}\\\\global.vs.db is not created
3. C++ Debug console: 
```
Failed to open the file k:\.vscode\cache\browse\MyApp\global.vs.db
```
4. Tag Parser doesn’t work

### Results: Second Startup
1. ${workspaceFolderBasename}\\\\global.vs.db gets created now that k:\\\\.vscode\\\\cache\\\\browse subdirectory has been created (on the first start of VSCode)
2. OS shows correct path has been created: k:.vscode\\\\cache\\\\browse\\\\MyApp\\\\global.vs.db
3. **Tag Parser works as expected**

# Irrelevant State (Probably)

### State: Global User settings.json
```
  "C_Cpp.intelliSenseCachePath": "k:\\.vscode\\cache",
  "C_Cpp.default.browse.path": [ ],
  "C_Cpp.default.browse.limitSymbolsToIncludedHeaders": true,
  "C_Cpp.default.compilerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\Hostx64\\x64\\cl.exe",
  "C_Cpp.loggingLevel": "Debug"
```

**Comment by mjbvz** [comment]
Please file this against the c++ extension
