### ISSUE TITLE
Global Search and Replace Using Regex Popup Dialog Improvement

### ISSUE THREAD

**Issue by peterjgrainger** [microsoft/vscode#93282]
Issue Type: <b>Bug</b>

## Scenario

Using Global Search (find and replace in all files) using regex for the search and replacing using a value found in the regex group.  Regex search was toggled on. This bug is about the message in the popup dialog.
```
Example text to find: "foo"
Search input: "([a-z]+)"
Replace input: <$1>
```

## Expected Dialog Message

Replace 51 occurances across 51 files with '\<foo\>'?

## Actual Dialog Message

Replace 51 occurance across 51 files with '<$1>'?

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.11GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.50
gitlens|eam|10.2.1
vscode-test-explorer|hbe|2.17.0
bash-ide-vscode|mad|1.8.0
terraform|mau|1.4.0
prettify-json|moh|0.0.3
azure-pipelines|ms-|1.165.1
vscode-docker|ms-|1.0.0
remote-wsl|ms-|0.42.4
azure-account|ms-|0.8.8
powershell|ms-|2020.3.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.7.0

</details>

![image](https://user-images.githubusercontent.com/1332395/77391494-c8cfc800-6d90-11ea-8d1c-249b7960851f.png)

**Comment by roblourens** [comment]
Actually, we unfortunately can't give a better message here because the regex group can be different for different matches. I could detect this case where it happens to be the same for every match, but I think it's better to be consistent.
