### ISSUE TITLE
Find and Search have the same colour!

### ISSUE THREAD

**Issue by aybiss** [microsoft/vscode#93280]
Issue Type: <b>Bug</b>

If I "search" (Ctrl+Shift+F) in my project, the search matches get highlighted in a sort of browny/orange colour with the default scheme.

If I "find" (Ctrl+F) within a file, the search matches remain but the find matches get highlighted in THE SAME COLOUR. 

(╯°□°)╯︵ ┻━┻

The concept of being able to do a "search" and a "find" at the same time and have them both active is actually a **REALLY** good one. But by having them both painted the same colour, it actually makes it extra hard to search OR find, and you often have to go close one or the other in order to just see the matches for the one you are presently trying to use.

This will probably become a feature request, but it's just such an annoying anti-feature, I just had to report it as a bug.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (20.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: W50567|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (48 x 3001)|
|Memory (System)|127.90GB (114.00GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.50.1
remote-ssh-edit|ms-|0.50.1
Bookmarks|ale|11.0.0
code-gnu-global|aus|0.2.2
svn-scm|joh|2.10.6
python|ms-|2020.3.69010
cpptools|ms-|0.26.3

</details>

**Comment by roblourens** [comment]
Easy to customize yourself:

```json
"workbench.colorCustomizations": {
        "editor.findMatchBackground": "#ff0000"
}
```

I will close this since I don't want to find different defaults for all of our themes, and I think it's not too bad to have one color that means "some sort of find match"

**Comment by aybiss** [comment]
> Easy to customize yourself:
> 
> ```json
> "workbench.colorCustomizations": {
>         "editor.findMatchBackground": "#ff0000"
> }
> ```
> 
> I will close this since I don't want to find different defaults for all of our themes, and I think it's not too bad to have one color that means "some sort of find match"

Sorry but did you read the actual problem? I don't want to customise the one colour, I want to have two colours. Having one colour for two different search functions that can be active at the same time literally makes searching harder than if there was only one search function active at a time.

**Comment by roblourens** [comment]
That controls only the color for the find editor so you can make them different colors. Here I have a search for `workbench` and the find widget is finding `color`

![image](https://user-images.githubusercontent.com/323878/77592032-82708b00-6eae-11ea-8e8b-7617d8eefbb3.png)

**Comment by roblourens** [comment]
Oh, I see that this only applies to the "active" find match. @rebornix how does the color for all find matches get set?

**Comment by roblourens** [comment]
Nevermind, I found `editor.findMatchHighlightBackground` which controls it for both find and search. We should add a token to override this for search.

**Comment by aybiss** [comment]
> That controls only the color for the find editor so you can make them different colors. Here I have a search for `workbench` and the find widget is finding `color`

No that affects both the find and the search.
![bullshit](https://user-images.githubusercontent.com/25842226/77592703-e21a7500-6f46-11ea-9f95-806c2357e661.png)

**Comment by roblourens** [comment]
It looks like you set `findMatchHighlightBackground` not `findMatchBackground`. But I understand that neither is exactly what you are looking for.

**Comment by aybiss** [comment]
Lol this triage process is a joke. How do people even vote?

But fine, if you want to ignore a really simple and useful enhancement, it's not my reputation as a developer at stake. 😂
