### ISSUE TITLE
source control discard changes removes everything on the pc

### ISSUE THREAD

**Issue by dpsqps** [microsoft/vscode#93290]
Issue Type: <b>Feature Request</b>

I wasn't going to use source control but accidentally I enabled through command ctrl + shift + G. After something showed on source control panel, I was discard changes. Never used it before and I thought it would just undo source control thing. However, by discarding changes, actual project files on my folder also deleted. So, without backup or anything I lost my hole project... I don't know why that removed everything(not in trash can neither) but please fix this. Thanks for help

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

When discarding the changes there was a dialog warning you that files would be deleted forever.
