### ISSUE TITLE
Simple editors styling is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93295]
Extensions viewlet:

![image](https://user-images.githubusercontent.com/22350/77410281-f467a800-6dba-11ea-8ff9-290d632f7403.png)

SCM: 

![image](https://user-images.githubusercontent.com/22350/77410312-fd587980-6dba-11ea-985a-78def6dd7456.png)

**Comment by sandy081** [comment]
@sbatten Reverted the code that globally registers editor background colour in the sidebar. Why not each view handle this like SCM?

**Comment by sbatten** [comment]
To Verify:
1. Check that SCM, Extensions, and Search input boxes have correct styling.
