### ISSUE TITLE
Test: call stack view improvements

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93297]
Refs: https://github.com/microsoft/vscode/issues/83986

- [x] any os @deepak1556 
- [x] any os @RMacfarlane

Complexity: 2

---

We have done some visual improvements to our call stack view. Start debugging multiple sessions (for example our smoketest express sample, and a simple one liner javascript file). 

Verify:

* We render an icon next to the debug session to make it more distinguishable
* Click elements like the `Load More Stack Frames` use the link color 
* Separator elements linke `async frames` are rendered with lower height
* Any suggestions on better presentation of data in the call stack view is welcome

**Comment by deepak1556** [comment]
Verified on linux 👍
