### ISSUE TITLE
Rename file with "Git: Rename file"

### ISSUE THREAD

**Issue by 1st** [microsoft/vscode#93299]
Issue Type: <b>Feature Request</b>

I found that time to time I do file rename. To do this, I need to open integrated terminal and do `git mv old_file_name new_file_name`. I think that it will be easier to do via `Command Palette` using **"Git: Rename file"** command. It looks easy to add. Can you please do it for me? Thank you!

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 19.3.0, macOS

**Comment by lszomoru** [comment]
@joaomoreno, I am happy to take a look at this one. Let's chat to lock down the requirements.

**Comment by 1st** [comment]
@lszomoru Please also consider rename for the folder as well, not only file. This way it will be reusable command

**Comment by lszomoru** [comment]
@1st will do. Will update the issue with the requirements after I sync with @joaomoreno.

**Comment by joaomoreno** [comment]
@1st Have you tried using https://marketplace.visualstudio.com/items?itemName=ambooth.git-rename ? This looks like a good solution. If it doesn't support all the feature you want it also looks like a great contribution opportunity.

**Comment by 1st** [comment]
But, to add extra one item to the built in menu, install a separate plugin? Don’t like to install any plugins that are not critical, especially if it just adds only an extra item to the list of existing features of the GIT built in plugin.

My request is to add a missing part of the built in VS Code plugin named Git. I can do many things with it, but can’t rename files or folders, reflecting this change in git.

**Comment by yume-chan** [comment]
Maybe we can tracking the already existed file renaming commands with [workspace.onDidRenameFiles](https://code.visualstudio.com/api/references/vscode-api#details-2729) event.

Then with a (user configurable) confirmation dialog, also rename the file with git-mv?

@joaomoreno Do you think this feature fit in Code itself? If so, I'd like to help implementing it. If not, maybe I can still contribute to the aforementioned extension.

**Comment by syepes** [comment]
This would be a great addition

**Comment by deepj** [comment]
I would appreciate more, if rthe ename functionality would use `git mv` behind in a project with git repository. It's logical because git can trace these changes than including showing changes in these renamed file. It doesn't have to be enabled by default, but give me an option to enable it.

**Comment by Kingwl** [comment]
I'd like to work on this..

**Comment by clarkttfu** [comment]
For javascript, vsc is now clever enough to update the path references automatically. It would be very helpful if vsc could also stage the file renaming/moving. Otherwise, to keep track the file origin without `git add`, user have to: 
1. backup the file in new destination (if changes were made)
2. git checkout original path
3. git mv original new
4. recover the backup in step 1
