### ISSUE TITLE
Test: explorer shows hidden files if they are open

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93298]
Refs: https://github.com/microsoft/vscode/issues/92090

- [x] any os @deepak1556 
- [x] any os @bpasero

Complexity: 2

---

If a file is hidden (via `files.exclude` ) and it is open and visible in the editor area Explorer will now show it and its parent chain.

Have some files and folders hidden via `files.exclude`.
Have a way to open those hidden files. For example via quick open, by setting `search.exclude` to contradict the `files.exclude` setting.

Open some of the hidden files in an editor and verify:
* Those files and their parents are shown in the explorer using a dimmed color
* As soon as the file is no longer visible it gets hidden in the explorer
* Make sure siblings of opened files are not shown. More precisly if `A` is a hidden folder, and `A/b.txt` and `A/c.`txt are its children. Make sure that opening `b.txt` does not show `c.txt` in the explorer

**Comment by deepak1556** [comment]
Verified on linux 👍
