### ISSUE TITLE
Comparing a number variable to a string shows a warning even though assigning a string is perfectly fine

### ISSUE THREAD

**Issue by Vannevelj** [Microsoft/vscode#933]
Consider the following example:

	function myFunc(myString) {
		let myVar = Infinity;
		myVar = myString.substring(1);
		if(myVar == 'ello') {
			
		}
	}

This will show a warning at the `if` statement saying the `==`  operator can't be used to compare a string and a number. Aside from the discussion whether this should be done in the first place, I think we can agree that it's handled inconsistently here: if we can assign a string to a number just fine then comparing a string to a number should be okay as well (and certainly if we use `==` instead of `===`).

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
