### ISSUE TITLE
Codicons are not rendered when filtering in quick pick

### ISSUE THREAD

**Issue by RomanNikitenko** [microsoft/vscode#93303]
- VSCode Version: 464ef8c1b3fe2e29d4dfd7b3d74cdcade7840566
- OS Version: Fedora 31

I’m trying to use `codicons` for actions. It works well at displaying in command palette, but for some case an icon is not rendered.
 
Let’s say, `Close Workspace` action has `$(chrome-close) Close Workspace` label.
The icon is rendered properly for the item in command palette. Let’s try to type `close` to filter all `close` items.  At this step the icon is not rendered.

I tested it using Monaco Playground:
![mon_playg](https://user-images.githubusercontent.com/5676062/77426950-31916180-6dde-11ea-99ae-47c79c836fa3.gif)

Steps to Reproduce:

1. Replace `label` value by `$(link) Open Link` for [OpenLinkAction](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/links/links.ts#L388)
2. F1 -> find `Open Link` -> the icon should be rendered
3. F1 -> type `link` -> the icon is not rendered

Please see: 
![vscode_codicon_issue](https://user-images.githubusercontent.com/5676062/77427452-212db680-6ddf-11ea-900b-f1e1de33bb5a.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by misolori** [comment]
I'm not able to reproduce this on the mac:

![image](https://user-images.githubusercontent.com/35271042/77499608-d1b3ae80-6e0f-11ea-8631-74dc0099a141.png)

@bpasero any ideas what could be happening here?

**Comment by misolori** [comment]
@RomanNikitenko can you link to a sample repo/extension where this is happening?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by RomanNikitenko** [comment]
@misolori 
In my case I have `$(link) Open Link`, (the icon contains **link**) and I'm typing `link`

Looks like you use label `$(rocket) Hello World` and you are typing `hello`.
So, the icon doesn't contain the word which you are typing (**rocket**).
For your case, please try to type `rocket`.

![rocket](https://user-images.githubusercontent.com/5676062/77513150-25101600-6e7d-11ea-9187-5c483d0aedc7.gif)

**Comment by bpasero** [comment]
@RomanNikitenko to clarify, you only see this in the monaco editor but not VSCode?

**Comment by RomanNikitenko** [comment]
@bpasero 
My second video (dark theme) was recorded using current master branch of VS Code.

In `steps to reproduce` section I mentioned that:
-  I go to `OpenLinkAction` https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/links/links.ts#L388
- and replace current link by `$(link) Open Link` 

Please, let me know if I'm doing something wrong.

**Comment by bpasero** [comment]
Indeed.

**Comment by bpasero** [comment]
I decided to strip codicons from commands for the command palette as I find this should have a consistent look and feel with our core commands that do not use icons too.

**Comment by misolori** [comment]
Sounds good, I don't think this should be a problem since most commands start with the extension name (category).
