### ISSUE TITLE
New install of Visual Studio and Salesforce CLI . Extensions fail to activate

### ISSUE THREAD

**Issue by llreed2020** [microsoft/vscode#93315]
- VSCode Version:1.43.1
- OS Version: Windows 10.0.18363 Build 18363
Steps to Reproduce:

1. Install the CLI and VS studio as instructed
2.

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/62074368/77445155-b9657480-6dba-11ea-81e0-d5cc7b98de33.png)

**Comment by mjbvz** [comment]
Please start by filing this agains the extension
