### ISSUE TITLE
Code doesn't update in the browser on save

### ISSUE THREAD

**Issue by coding507** [microsoft/vscode#93311]
I opened the project with live server, when I write some code and I save it, the browser with the project that I'm working on refreshes BUT when I inspect the page in the browser the code that I just saved doesn't appear in the browser even after many refreshes. I also disabled cache in browser, tried to refresh the page with ctrl+shift+R and the new code still not showing. Tried in both Chrome and Mozilla and the issue is the same. Basically, Live Server is not working properly. When I close and reopen the Live Server it works for a few minutes and then the issues reappear.

CPUs | AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 2096)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.81GB (1.64GB free)
Process Argv |  
Screen Reader | no
VM | 0%

CPUs | AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 2096)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.81GB (1.64GB free)
Process Argv |  
Screen Reader | no
VM | 0%

|  Window (Extension: Live Server - 4TECHNICALDOCUMENTATIONPAGE - Visual Studio Code)
|    Folder (4TECHNICALDOCUMENTATIONPAGE): 2 files
|      File types: html(1) css(1)
|      Conf files:

Extension | Author (truncated) | Version
-- | -- | --
vscode-intelephense-client | bme | 1.3.11
php-intellisense | fel | 2.3.14
LiveServer | rit | 5.6.1
html5-boilerplate | sid | 1.0.3

**Comment by mjbvz** [comment]
Please file this against the Live Server extension
