### ISSUE TITLE
VSCode crashes when parsing deep JSON strings in an extension

### ISSUE THREAD

**Issue by Foxhoundn** [microsoft/vscode#93310]
- VSCode Version: Latest public
- OS Version: MacOS latest, happens on other OS' as well

Steps to Reproduce:

1. Create a simple extension and try to `JSON.parse` the string below

```
{"name":"test","fields":{"test2":{"name":"test2","fields":{"test3":{"name":"test","fields":{"test4":{"name":"test","fields":{"test5":{"name":"test","fields":{"test6":{"name":"test","fields":{"test7":{"name":"test","fields":{"test8":{"name":"test","fields":{"test9":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
```

VSCode crashes with 

`[2020-03-24 14:19:17.617] [main] [error] [VS Code]: render process crashed!`

![Screenshot 2020-03-24 at 14 32 25](https://user-images.githubusercontent.com/8861481/77430992-571d6b80-6ddc-11ea-9cac-96e8b0633226.png)

2. Try again with 

```
{"name":"test","fields":{"test2":{"name":"test2","fields":{"test3":{"name":"test","fields":{"test4":{"name":"test","fields":{"test5":{"name":"test","fields":{"test6":{"name":"test","fields":{}}}}}}}}}}}}
```

Works just fine.

Wrapping the parse in `try/catch` did not help, nothing is caught.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@Foxhoundn I could not reproduce. I have tried with the following extension:

* `package.json`:
```
{
    "publisher": "alex",
    "name": "93310",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```

* `index.js`:
```
const vscode = require('vscode');

exports.activate = function(context) {

	const x = `{"name":"test","fields":{"test2":{"name":"test2","fields":{"test3":{"name":"test","fields":{"test4":{"name":"test","fields":{"test5":{"name":"test","fields":{"test6":{"name":"test","fields":{"test7":{"name":"test","fields":{"test8":{"name":"test","fields":{"test9":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{"name":"test","fields":{"test2":{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}`

	const y = JSON.parse(x);

	console.log(`I have parsed it!`);

}
```

And I am able to execute the extension and I see the message.

**Comment by Foxhoundn** [comment]
Hi @alexdima, yeah sorry, you're right. There's a few more steps.

The error only happens when you try **postMessage to a webview**

So if you create a webview and do `webview.postMessage({ foo: JSON.parse(*...the json*) })`, the whole extension window crashes.
