### ISSUE TITLE
Terminal: registers commands multiple times?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93317]
Moving to March, since this impacts the new quick open. See how many terminal related commands show up twice:

![image](https://user-images.githubusercontent.com/900690/77459218-aa54e580-6dff-11ea-87c4-3c3196e82f1a.png)

![image](https://user-images.githubusercontent.com/900690/77459235-b0e35d00-6dff-11ea-8d81-d8c291b15f4c.png)

I used to dedupe in the old world, but I am still curious why this happens, as other commands do not exhibit this behaviour.

**Comment by Tyriar** [comment]
This happens because historically you could not use `or` in when clauses, if this is changed I can merge the duplicates.

https://github.com/microsoft/vscode/blob/75f05c222bdc51ab505200fa67243db3a02c0787/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L582-L589

**Comment by Tyriar** [comment]
Yep works now, will make the change 👍

**Comment by Tyriar** [comment]
To verify:

- Open command palette and make sure duplicate don't show up
- Look at the commit and make sure some of the items that were merged work in both contexts

**Comment by Tyriar** [comment]
@bpasero not sure how to resolve this one where the secondary keybindings differ depending on what is focused:

https://github.com/microsoft/vscode/blob/75f05c222bdc51ab505200fa67243db3a02c0787/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L590-L598

**Comment by bpasero** [comment]
@Tyriar instead of using `registerWorkbenchAction` you should rather contribute the single command to the command palette menu. `registerWorkbenchAction` is actually deprecated, though still being used a lot. It does this registration under the hood.

**Comment by bpasero** [comment]
Example: https://github.com/microsoft/vscode/blob/d468b457a2f82264d3c53cc98c5f3077a4db32c2/src/vs/workbench/browser/parts/editor/editorCommands.ts#L296

**Comment by Tyriar** [comment]
@bpasero I don't see anywhere in the code indicating that it's deprecated. If it is then we should add `@deprecated` here?

https://github.com/microsoft/vscode/blob/5b7bfa753c059907b6f58b81e85d04b6238e6040/src/vs/workbench/common/actions.ts#L20-L27

**Comment by bpasero** [comment]
@Tyriar oh yeah, we can do that, but not sure if it is being displayed properly by TS yet. Needs a ton of adoption obviously.

**Comment by Tyriar** [comment]
@bpasero I'll make that `@deprecated` change so it's at least mentioned in code and defer the migration off it to https://github.com/microsoft/vscode/issues/93390 as debt week would be better. Looking forward to seeing actionRegistry.~~registerWorkbenchAction~~ from TS as the adoption will happen much faster then.

**Comment by Tyriar** [comment]
To verify:

- Open command palette and make sure duplicate don't show up (Find Next/Previous are the exception, they'll be handled in https://github.com/microsoft/vscode/issues/93390)
- Look at the commit and make sure some of the items that were merged work in both contexts

**Comment by bpasero** [comment]
@Tyriar sounds good, I also wanted to look into this in debt week. Please be aware that there is also [`registerAction2`](https://github.com/microsoft/vscode/blob/d468b457a2f82264d3c53cc98c5f3077a4db32c2/src/vs/platform/actions/common/actions.ts#L411) which seems to simplify a lot of it.
