### ISSUE TITLE
Smoke test: WSL prompt shows up on every open, even after dismissing it

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93318]
![](https://memes.peet.io/img/20-03-9176b7bb-2e9e-4514-b1a7-aba9d05fe52a.png)

I need to go to the gear and hit "don't show again", otherwise it pops up every time I open VS Code. This behavior doesn't happen on 1.43.1.

**Comment by aeschli** [comment]
Strange, I'm not aware of any recent changes. `Don't show again` was always necessary.
Maybe you didn't see the recommendation as you has Remote - WSL installed?

**Comment by connor4312** [comment]
Huh, I can't repro now. I was launching with a custom `--extensions-dir` but maybe I accidentally did something wrong before.
