### ISSUE TITLE
saving code formatte error ( Visual Studio Code)

### ISSUE THREAD

**Issue by AJGIT19** [microsoft/vscode#93329]
Issue Type: Performance Issue

It's been processing a command about "saving (name of the format) running 'prettier' - code formatter.
Its been like that for 20 minutes and got worst cause is saving 2 more formats and if I keep working it won't save my changes. 
What is that for???  

Thx for the help

**Visual Studio Code**

**Comment by mjbvz** [comment]
Seems like the prettier extension is hanging. Please file an issue against them
