### ISSUE TITLE
Bot Proposal: "Blocked on..."

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#93321]
## Background
We often have issues that are "blocked" on other underlying engineering work or features being implemented. Right now we can comment "blocked on #XXX" and leave it open or close it out, but we don't have much of a way to query for/against these blocked issues. 

## Proposal
On comment "/blocked #XXX", the bot will add a `blocked` label and a `blocked#XXX` label. 

When issue #XXX is closed, the bot will automatically delete the `blocked#XXX` label from all issues, and remove the `blocked` label from all issues with no other issues blocking them.

Thus you will be able to filter out blocked issues from queries and find all issues blocked on a particular issue.

**Comment by JacksonKearl** [comment]
^ we'll likely not require 20 upvotes. Just general consensus that this is something that would be helpful

**Comment by Tyriar** [comment]
@JacksonKearl might be better using the under-discussion label rather than backlog candidates for these?

**Comment by alexdima** [comment]
I have concerns that this would create too many spamy labels. Is there any other GH project that uses this approach?

**Comment by JacksonKearl** [comment]
@alexdima I don’t know of any. I see your concern, given nobody seems to actually want it I’ll likely just close this proposal out.
