### ISSUE TITLE
Feature: Debug GUI for Arguments

### ISSUE THREAD

**Issue by mohamedmansour** [microsoft/vscode#93327]
For debugging applications that have arguments, it requires the developer to hard code the arguments. Sometimes, I want to change the input without changing the launch.json (Since that is committed)..

Would be great if the Schema of `configuration[].args` has something like this:
```
"args": [
    "--name=${Name=string}",
    "--password=${Password=password|10}",
    "--log-level=${Log Level=enum|info,debug,error,critical}"
]
```

When passing templates to the argument, it follows some format `${Label=Type|exp}`, and the `Type` can be a `string`, `number`, `password`, `enum`, and the templates are piped to some `expression`. 

For example with expressions, you can specify rules (configuration) for that type.

The GUI will basically create a form of the arguments in that run and show case this on top. It will have history associated to it, similar on how webforms works today. We can take an extra step and let is save "arg" state so that next time we run it, we can choose arguments from previous run.

**Comment by isidorn** [comment]
Fair feature request however currently not on the plan. Thus assigning to the backlog.

**Comment by weinand** [comment]
@isidorn @mohamedmansour VS Code supports this for quite some time. Please see https://code.visualstudio.com/docs/editor/variables-reference#_input-variables
