### ISSUE TITLE
Bot Proposal: "Author Verified"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#93323]
## Background
We occasionally get issues from people with highly specific setups that can be very difficult to verify. These take a long time for the team to verify, but would be relatively quick for the original author to do the same. 

## Proposal 
After an issue has been closed with a commit, and that commit gets in the latest insiders, post a comment asking the original issue author to verify the fix with a link to insiders.

When the original author then comments "/verified" mark the issue verified. 

Potential issue is that we might put more work into verifying corner cases/etc. than the original author, so this may lower the bar for verification.

**Comment by isidorn** [comment]
I actually already have a predfined reply for exactly this. Not sure what it would bring if Bot replies instead of me.

**Comment by jrieken** [comment]
> Not sure what it would bring if Bot replies instead of me.

You don't have to comment on the issue! It all happens automatically, bot tells author to try, author thumbs-up, issue is verified

**Comment by isidorn** [comment]
Missed that part. Then yeah, upvoting this issue with all emojis known to humankind.

**Comment by bpasero** [comment]
This would really be great 👍

**Comment by JacksonKearl** [comment]
This seems to be the most popular proposal. Would this make more sense as something enabled for all `bug` issues, or just ones that a team member labels as `author-verification-requested` or similar? 

I'd think we do a more thorough job of verifying than the author might, so perhaps this should be restricted to issues that would be overly time-intensive for a team member to verify?

**Comment by jrieken** [comment]
I'd say this should be the default for everything labeled as `bug`

**Comment by JacksonKearl** [comment]
@Tyriar 

As seen here, the bot wont do anything if it cant find a closing commit. This is because the `/verified` is normally disabled until the closing commit is in Insiders. 

https://github.com/microsoft/vscode/issues/89443

In cases where issues are closed without a commit, we currently just leave a comment saying we can't find a commit and remove the `author-verification-requested` label. We could instead enable the `/verify` comment and leave the comment immediately in cases where the issue is closed without a commit.

**Comment by jrieken** [comment]
> In cases where issues are closed without a commit, we currently just leave

How about using the dates of when insiders was build and the date when the issue was closed? That's usually also a good hint.

**Comment by JacksonKearl** [comment]
> How about using the dates of when insiders was build and the date when the issue was closed? That's usually also a good hint.

That works most of the time but falls down during endgame. Currently we use commits if they're present and fall back to close time vs release time otherwise.
