### ISSUE TITLE
Bot Proposal: "New Issue from Testplan Item"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#93324]
## Background
When testing, the flow "`new issue => select "bug report" => add "Testing #blah"` is more clicks than it ought to be.

## Proposal
When an issue is labeled `testplan-item`, create a comment with a link that will open up to a new-issue form with the issue body prefilled to reference the original test plan item.

**Comment by bpasero** [comment]
How would that work exactly? Not clear to me from the descriptio.

**Comment by JacksonKearl** [comment]
@bpasero it's a very simple bot, see https://github.com/microsoft/vscode/issues/93411 for an example. This isn't going to massively speed up anyones workflow, but it's something that would at least save a few clicks and keytaps.

**Comment by alexdima** [comment]
Cool idea, I would put it in the test plan header. (next to the testers section)

**Comment by JacksonKearl** [comment]
@alexdima
Do you mean the bot would edit the original issue? I think that’s possible, but it opens up room for race conditions (bot estira while author is editing, only one succeeds). Would you be against it commenting?

**Comment by alexdima** [comment]
It could be done by the bot that assigns folks to test plan item, that bot is able to edit the test plan item and it could also drop in one more link somewhere in there.

**Comment by sandy081** [comment]
`Create Issue` link that creates issue with body `Testing #issue` is added to the TPI header while assigning

![image](https://user-images.githubusercontent.com/10746682/82930456-bbe47600-9f85-11ea-8ccd-90c623b8bf71.png)

**Comment by JacksonKearl** [comment]
Thanks!
