### ISSUE TITLE
Drop stash should ask for comfimation

### ISSUE THREAD

**Issue by LEGOL2** [microsoft/vscode#93320]
Code version: 1.43.1
In repo control, when you press 'Drop Stash' there is no popup to confirm this action. Due to fact that 'Apply Stash' is above drop, there is high probability to missclick (yes, I did it. I have deleted quite a lot of work) 
This feature can save a lot of accidents of deleting stash.
![screen](https://user-images.githubusercontent.com/22496424/77462231-22250f00-6e04-11ea-8f85-48e555e7bc04.png)

**Comment by dormesica** [comment]
I would like to take a look at that it's OK.

**Comment by tabaddor** [comment]
If still unresolved, I can look into this issue.
