### ISSUE TITLE
Clean up extensions view actions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93325]
![image (2)](https://user-images.githubusercontent.com/10746682/77470979-d6796200-6e11-11ea-8c58-5983dff72045.png)

**Comment by oriash93** [comment]
Would like to take up on that, if possible.
What exactly needs to be cleaned?

Thanks

**Comment by sandy081** [comment]
Sorry, this is no longer valid. It seems I cleaned up this while implementing other features.
