### ISSUE TITLE
 escaping CLI arguments in zsh doesn't work properly

### ISSUE THREAD

**Issue by eyehol3** [microsoft/vscode#93328]
- VSCode Version: 1.43.1
- OS Version: macOS 10.15

i opened an [issue](https://github.com/microsoft/vscode-python/issues/10701) at vscode-python because i couldn't launch a python file with characters that need to be escaped in path
but i've been told that their extension has nothing to do with it:
> This appears to be an issue with escaping CLI arguments. VS Code itself is in charge of properly escaping them for the various shells. Unfortunately the Python extension can't do much about this.

### Steps to Reproduce:
1. make zsh your vscode terminal
2. press a vscode-python run button in python file that has characters like [ ] in path

### result:
`/usr/local/bin/python3 /Users/qwerty/Dropbox/[STUDY]/OOP/1_farm_oop_concepts.py zsh: no matches found: /Users/qwerty/Dropbox/[STUDY]/OOP/1_farm_oop_concepts.py`

### expected:
`/usr/local/bin/python3 "/Users/qwerty/Dropbox/[STUDY]/OOP/1_farm_oop_concepts.py"`

**Comment by vulnbe** [comment]
1. Config
```
...
"args": [
        "--index", "x-*"
]
...
```
produces: 

```
test.py --index x-*
zsh: no matches found: x-*
```

2. Config
```
...
"args": [
        "--index", "x-\*"
]
...
```
produces: 
```
test.py --index x-
```
which is wrong

3. Config
```
...
"args": [
        "--index", "x-\\*"
]
...
```
produces: 

```
test.py --index x-\\*
zsh: no matches found: x-\*
```

Single quotes are escaped by vscode.

**Comment by Tyriar** [comment]
@brettcannon can you link to the code where this python3 terminal is launched if it still happens?

**Comment by karrtikr** [comment]
This is where the command is launched: https://github.com/microsoft/vscode-python/blob/c1a8d94c6b8caa658aa99109111a3ee3551c8fe0/src/client/terminals/codeExecution/codeExecutionManager.ts#L41

This is where we calculate the args which we then simply send to terminal: https://github.com/microsoft/vscode-python/blob/b363ffc69375892027cadbe110d8907a86e27589/src/client/terminals/codeExecution/terminalCodeExecution.ts#L32

**Comment by Tyriar** [comment]
This is just sending raw text to the terminal on the extension side so it's up to vscode-python to fix. I think we've discussed having a util method exposed on the VS Code api to do this but we probably won't end up doing that as it should be a relatively small amount of code to do the escaping properly and that sort of method doesn't really fit into our API.
