### ISSUE TITLE
Linux/Fedora24: Upgrade from 1.2.1 to 1.3.1 breaks launcher

### ISSUE THREAD

**Issue by bgse** [Microsoft/vscode#9332]
- VSCode Version: Upgrade to 1.3.1 from 1.2.1
- OS Version: Fedora24

Steps to Reproduce:

1. download 1.3.1 rpm package
2. "sudo dnf install _path_to_rpm_"
3. attempt to start vscode via the launcher

-> "failed to launch child process: /usr/bin/code not found: no such file or directory"

Workaround:

1. download 1.3.1 rpm package
2. "sudo dnf remove code"
3. "sudo dnf install _path_to_rpm_"

**Comment by bgse** [comment]
Maybe it has nothing to do with upgrade, and I've just run into this one?

https://github.com/Microsoft/vscode/issues/8942

**Comment by Tyriar** [comment]
#8942 should only apply to the deb package. Perhaps related to #7350 but I have tested it a few times :confused:

**Comment by Tyriar** [comment]
Duplicate of #11431
