### ISSUE TITLE
Integrated terminal is not executing pdftk command

### ISSUE THREAD

**Issue by juandsan91** [microsoft/vscode#93337]
As tittle says integrated terminal of visual code not recognizes pdftk command, it's already on the path. I can check pdftk --version on bash or cmd directly on windows but not in the terminal of vs code or even when i'm debugging. Pdftk is installed on windows as server and is used to merge pdfs and is on windows path

Actually I have read similar issues, but none of that solutions have worked.

![image](https://user-images.githubusercontent.com/7372992/77488696-f73abb00-6e03-11ea-9863-41ede338dd5e.png)

`"version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Node",
            "program": "${workspaceFolder}\\bin\\www"
        }
    ]`
![image](https://user-images.githubusercontent.com/7372992/77488675-e12cfa80-6e03-11ea-8de2-ccbfbf816e43.png)

**Comment by Tyriar** [comment]
If the shell is saying it cannot find the command then it doesn't exist on the PATH. Try investigating what `$PATH` is within the terminal and try restart VS Code completely.
