### ISSUE TITLE
White boxes in window

### ISSUE THREAD

**Issue by TheRevTasticTJ** [microsoft/vscode#93338]
- VSCode Version: 1.43.1
- OS Version: Windows 10 (latest stable build)

If you have the setting for play hdr games and apps turned on in display settings when using a monitor that supports it you get big boxes in the window for vs code. 

If you turn the setting off they go away.

Steps to Reproduce:
1. Open up display settings
2. Turn on the slider for "Play HDR Games and Apps"

Does this issue occur when all extensions are disabled?: Yes

![vscodebug](https://user-images.githubusercontent.com/9523996/77489057-02dab180-6e05-11ea-8bc6-4f77de7aed09.PNG)

**Comment by TheRevTasticTJ** [comment]
Forgot to mention...

This only happens on the monitor that supports the HDR setting. If you drag the vs code window to another monitor that doesn't have it turned on or is able to use the setting the boxes go away.

**Comment by IllusionMH** [comment]
Is it fixed if you disable hardware acceleration?
https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by TheRevTasticTJ** [comment]
> 
> 
> Is it fixed if you disable hardware acceleration?
> https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

That does not fix it

**Comment by johnfg10** [comment]
For reference was having the same issue disabling GPU acceleration did fix this issue for me after restarting vs code

**Comment by wangkezun** [comment]
same issue here. Turn off windows hdr from setting did help, but I think this need to be fixed.

**Comment by deepak1556** [comment]
@TheRevTasticTJ @wangkezun does it help when you start code with `--force-color-profile srgb` ?

**Comment by wangkezun** [comment]
> @TheRevTasticTJ @wangkezun does it help when you start code with `--force-color-profile srgb` ?

Yes. with this setting the window shows normally.

**Comment by deepak1556** [comment]
Thanks I am merging this to https://github.com/microsoft/vscode/issues/88491
