### ISSUE TITLE
VSCode keeps corrupting itself

### ISSUE THREAD

**Issue by ddejohn** [microsoft/vscode#93333]
Unable to submit a proper bug report because I can't reinstall or repair VSCode. This is the second time this week this has happened. I'll close the program after I'm done, and then I'll see a pop-up saying that VSCode is updating, which hangs at 0%. If I try to reopen the program, the executable is present, but nothing happens when I run it, and all of the other files are gone from `C:/Users/me/AppData/Local/Programs/Microsoft VS Code`.

I can't delete the files that remain even with administrator privileges, so I can't reinstall because the installation wizard always fails because files are already present in the directory.

OS: Windows 10 NT
VSC: 1.42.1

**Comment by cjingle** [comment]
I have the same issue as well.  Every time VS Code goes to update, it hangs at 0% and locks the EXE.  I have to uninstall VS Code, then reboot my PC.  Then download the latest and install it manually.  This has been the third update where I've had to do this.

**Comment by joaomoreno** [comment]
Does it work if you set `update.enableWindowsBackgroundUpdates` to `false`?

**Comment by ddejohn** [comment]
I've set it to false. We'll see.

**Comment by cjingle** [comment]
Same here.  I set it to false.  We'll see what happens.  Thanks.

**Comment by joaomoreno** [comment]
Let me know.
