### ISSUE TITLE
Opt in syncing global state

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93332]
We support now syncing global state - #86679. It is an opt in functionality. If you think the global state you own shall be synced, you have to opt in by registering your global state key to be syncable. 

Ref:
https://github.com/microsoft/vscode/blob/8410ac753f2fbb6c856c139d889d95aff9769eb8/src/vs/workbench/browser/parts/statusbar/statusbarPart.ts#L365

As shown above, you have to provide the storage key that has to be key along with version number. Versioning gives you flexibility to change your storage data semantics and makes sure old clients does not sync old data. 

@microsoft/vscode Please find references to [StorageScope.Global](https://github.com/microsoft/vscode/blob/8410ac7/src/vs/platform/storage/common/storage.ts#L119) and check the state you own and opt in to sync if you think so.

**Guidelines:** Here are some guidelines to follow. They are not fixed, feel free to add 
- Do not sync if state contains paths
- Do not sync if state is machine associated like any dimensions.
- Make sure the state update works across multiple windows of the same VS Code instance

Here is the list of usages. Please check off either by opting in or not

<details>
<summary>Completed (March + April)</summary>

- [x] `src/vs/editor/contrib/gotoSymbol/peek/referencesController.ts` - @jrieken 
- [x] `src/vs/editor/contrib/suggest/suggestMemory.ts` - @jrieken 
- [x] `src/vs/editor/contrib/suggest/suggestWidget.ts` - @jrieken 
- [x] `src/vs/platform/extensionManagement/common/extensionEnablementService.ts` - @sandy081
- [x] `src/vs/platform/quickinput/browser/commandsQuickAccess.ts` - @bpasero 
- [x] `src/vs/platform/serviceMachineId/common/serviceMachineId.ts` - @sandy081
- [x] `src/vs/platform/userDataSync/common/userDataSyncService.ts` - @sandy081
- [x] `src/vs/workbench/browser/parts/activitybar/activitybarPart.ts` - @sandy081 
- [x] `src/vs/workbench/browser/parts/editor/editorPart.ts` - @isidorn  
- [x] `src/vs/workbench/browser/parts/panel/panelPart.ts` - @sandy081 
- [x] `src/vs/workbench/browser/parts/statusbar/statusbarPart.ts` - @sandy081
- [x] `src/vs/workbench/browser/parts/titlebar/menubarControl.ts` - @sbatten 
- [x] `src/vs/workbench/browser/parts/views/views.ts` - @sandy081 
- [x] `src/vs/workbench/browser/workbench.ts` - @bpasero 
- [x] `src/vs/workbench/contrib/bulkEdit/browser/bulkEditPane.ts` - @jrieken 
- [x] `src/vs/workbench/contrib/callHierarchy/browser/callHierarchy.contribution.ts` - @jrieken 
- [x] `src/vs/workbench/contrib/callHierarchy/browser/callHierarchyPeek.ts` - @jrieken 
- [x] `src/vs/workbench/contrib/debug/browser/debugToolBar.ts` - @isidorn 
- [x] `src/vs/workbench/contrib/experiments/common/experimentService.ts` - @connor4312 
- [x] `src/vs/workbench/contrib/files/browser/editors/textFileSaveErrorHandler.ts` - @bpasero 
- [x] `src/vs/workbench/contrib/localizations/browser/localizations.contribution.ts` - @sandy081 
- [x] `src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts` - @roblourens 
- [x] `src/vs/workbench/contrib/quickopen/browser/commandsHandler.ts` - @bpasero 
- [x] `src/vs/workbench/contrib/remote/browser/explorerViewItems.ts` - @alexr00 
- [x] `src/vs/workbench/contrib/terminal/browser/terminalInstance.ts` (not a good candidate) - @Tyriar 
- [x] `src/vs/workbench/services/notification/common/notificationService.ts` - @bpasero 
- [x] `src/vs/workbench/services/remote/common/remoteExplorerService.ts` - @alexr00 
- [x] `src/vs/workbench/services/textMate/browser/abstractTextMateService.ts` - @alexdima 
- [x] `src/vs/workbench/services/views/browser/viewDescriptorService.ts` - @sandy081
- [x] `src/vs/workbench/services/workspaces/browser/workspacesService.ts` - @bpasero 
- [x] `src/vs/workbench/contrib/url/common/trustedDomains.ts` - @octref 
- [x] `src/vs/workbench/contrib/url/common/trustedDomainsFileSystemProvider.ts` - @octref 
- [x] `src/vs/editor/contrib/find/findWidget.ts` - @rebornix 
- [x] `src/vs/platform/telemetry/browser/workbenchCommonProperties.ts` - @RMacfarlane 
- [x] `src/vs/platform/telemetry/node/workbenchCommonProperties.ts` - @RMacfarlane 
- [x] `src/vs/workbench/api/browser/mainThreadAuthentication.ts` - @RMacfarlane 
- [x] `src/vs/workbench/contrib/extensions/browser/extensionTipsService.ts` - @sandy081 
- [x] `src/vs/workbench/contrib/surveys/browser/languageSurveys.contribution.ts` - @egamma  
- [x] `src/vs/workbench/contrib/surveys/browser/nps.contribution.ts` - @egamma  
- [x] `src/vs/workbench/electron-browser/window.ts` - @deepak1556 
- [x] `src/vs/workbench/services/integrity/node/integrityService.ts` - @alexdima  
- [x] `src/vs/workbench/services/themes/browser/fileIconThemeData.ts` - @aeschli 
- [x] `src/vs/workbench/services/themes/browser/productIconThemeData.ts` - @aeschli 
- [x] `src/vs/workbench/services/themes/browser/workbenchThemeService.ts` - @aeschli 
- [x] `src/vs/workbench/services/themes/common/colorThemeData.ts` - @aeschli 
- [x] `src/vs/workbench/contrib/update/browser/update.ts` - @joaomoreno 
- [x] `src/vs/workbench/services/extensions/browser/extensionUrlHandler.ts` - @joaomoreno 

</details>

- [x] `src/vs/workbench/browser/layout.ts` - @sbatten  
- [x] `src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.ts` - @sbatten  
- [ ] `src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts` - @sandy081

**Comment by isidorn** [comment]
Went through mine and did not fine good candidates for this.

**Comment by bpasero** [comment]
I added a few. There are some which I am unsure, such as NPS surveys or extension tips. My feeling is they should be synced too.

@sandy081 I tried to adopt the service for notifications that offer a "Do not show again" action, but get tons of exceptions when requiring it in my layer. I think I cannot depend on that service as it seems to drag in other things? Try adding the dependency to `notificationService.ts` to see that in action.

**Comment by sandy081** [comment]
@bpasero I tried adding `IStorageKeysSyncRegistryService` to `notificationService.ts` and it seems to work for me. I did not see any errors.

**Comment by bpasero** [comment]
Sorry, nevermind. I pushed a change to register these keys.

**Comment by bpasero** [comment]
NPS and language surveys is probably PM/DevLead decision, I assigned @egamma

**Comment by sandy081** [comment]
@microsoft/vscode

Those who opted in to sync their global state, can you please provide steps to verify them in the comment below

**Comment by sandy081** [comment]
- Activity bar icons and order
  - Status bar items
  - Panel items and order
  - Workbench views layout and visibility. **Note:** Views order is not yet synced
  - Settings UI (Automatically gets saved) notification is not shown again

**Comment by bpasero** [comment]
**Commands:** the recently used command is being synced to the other machine.

**Comment by jrieken** [comment]
for outline make sure this UX state is sync'd

<img width="420" alt="Screenshot 2020-03-31 at 10 07 31" src="https://user-images.githubusercontent.com/1794099/78002375-7285fa80-7337-11ea-94d4-dc0a3f5faf69.png">

**Comment by sandy081** [comment]
Recently used and commands and Outline state are not getting synced. 

- https://github.com/microsoft/vscode/issues/93881 @jrieken 
- https://github.com/microsoft/vscode/issues/93884 @bpasero

**Comment by connor4312** [comment]
I do not think experiment state should be synced at this time. We store evaluation results there, and between computers those results might be different. For instance, say we have an insiders-only experiment. If I happen to open stable first, that will evaluate to `NoRun`, and then syncs to my insiders instance, preventing me from ever seeing the experiment. We might want to add other user-global conditions later but for now I think keeping them locally is fine.

**Comment by octref** [comment]
@sandy081 Wondering what you think about trusted domains. I feel it shouldn't be synced but I could be convinced otherwise.

**Comment by sandy081** [comment]
I fee they should be synced. Its the user choice and as a I user I want my choice to be synced.

**Comment by sandy081** [comment]
@octref Can you please provide steps to test if trusted domains are synced and working as expected?

**Comment by octref** [comment]
@sandy081 Added trusted domains.

**Comment by deepak1556** [comment]
@sandy081 the crashreporter guid is machine dependent, it should not be synced. Removing my assignment.

**Comment by RMacfarlane** [comment]
Added trusted extensions.

To verify:
- Sign in with GH account to settings sync
- Write test extension that tries to access this same token:
```ts
	const session = await vscode.authentication.login("github", ['user:email']);
	const token = await session.getAccessToken();
	vscode.window.showInformationMessage('Successfully logged in');
```

Should be prompted to confirm that extension can access auth info on the first machine, and not see the consent dialog on subsequent machines

**Comment by aeschli** [comment]
For themes what's stored are the cached theme colors to avoid flickering on reload. We will not sync these at they also contain paths.

**Comment by sandy081** [comment]
We still have 3 instances to fix from @sbatten and me. 

One from me is not as simple as registering the keys as it needs updating the extensions resource while syncing. This is about locking the extension version to install. So will look into it early next milestone.

@sbatten Please take a look at the other two entries that are assigned to you.

**Comment by sandy081** [comment]
Closing this as the last action item is being tracked here - https://github.com/microsoft/vscode/issues/93332
