### ISSUE TITLE
Ctrl+F(num) doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by OleksandrKvl** [microsoft/vscode#93330]
- VSCode Version: 1.43.2
- OS Version: Ubuntu 18.04 on vmware (OS X Catalina host)

Steps to Reproduce:

1. Try to assign Ctrl+F(num)  to any command.
2. Try to use any existing Ctrl+F(num) command. 

Does this issue occur when all extensions are disabled?: Yes.

Hi, I have pretty strange behavior. Any Ctrl+F(num) shortcut doesn't work. All Ctrl+Shift+F(num) work. For example Ctrl+F3 doesn't do anything while Ctrl+Shift+F3 works as expected. Also I can't assign Ctrl+F(num) to any command, when I try to change keyboard shortcut and press Ctrl+F(num), only Ctrl part is detect by vscode and displayed in text window. At the same time Ctrl+Shift+F(num) is detected OK. It looks like Ctrl+F(num) isn't recognnized by vscode at some low-level and all related facilities just don't know that keys are pressed.
I have minimal installation of Ubuntu 18.04.1 with xfce4 as a desktop. First I suspected vmware/Ubuntu problems but in other programs this combination works fine. It also works on another vm Ubuntu 16. Got same problems with insiders build as well.

**Comment by OleksandrKvl** [comment]
I opened developer tools and set a simple logging listener document.onkeydown and it behaved in the same way, events were received in all combinations except Ctrl+F(num), in that case only Ctrl event was received.

**Comment by alexdima** [comment]
@OleksandrKvl 

You can try to use `"keyboard.dispatch": "keyCode"`.

But if VS Code does not receive the keybindings, there is nothing we can do. Do the keybindings arrive in other software in the same setup?

**Comment by OleksandrKvl** [comment]
@alexdima 
You're right, my fault, this problem is system-wide. While in other application(Krusader) I can at least  assign Ctrl+F(num) to some action(I can't do this in vscode) but this shortcut is still not detected. I checked it with xev and got FocusIn/Out instead of KeyPress/Release events. It looks like an error in xserver like the one described [here](https://forums.freebsd.org/threads/no-keypress-keyboard-events-for-some-keys-after-upgrade-to-xorg-1-20-7.74238/). So I hope it will be fixed in next xserver release.

**Comment by OleksandrKvl** [comment]
Finally I solve it. For some reason I didn't specify that my actual system is Ubuntu 18.04 + Xfce4. Xfce4 has system-wide keybindings(including Ctrl+F[0..12]) so another applications can't use them. The solution was to go to Settings -> Window manager -> Keyboard and clear shortcuts for Workspace[1..12].
