### ISSUE TITLE
Bot Proposal: "Caused by Extension X"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#93335]
## Background
We often get issues that should be filed on the extension's tracker. Currently the Inbox Tracker must find or memorize the extensions repo's URL and link to that with an explanation of the situation, or let the /causedByExtension command handle it, which provides limited guidance:

![image](https://user-images.githubusercontent.com/8586769/77484298-63f38c80-6de7-11ea-8a30-8b7fc4291418.png)

## Proposal
This could be implemented as simply as a set of new actions for the `commands` bot:
```
/python => Close & Comment "This issue is likely caused by the Python extension. Please file a report at https://github.com/Microsoft/vscode-python."
```
Similar for /c, /cpp, /c#, /ts, /js (same as ts), /go, /powershell, /liveshare, /docker, and more as we see fit.

**Comment by isidorn** [comment]
I like this and would use it.

**Comment by IllusionMH** [comment]
Also would be useful for community members with access to bot commands.

**Comment by bpasero** [comment]
I like the idea, but we have to be careful that we are not sending people to extension repositories to report it there if it is totally unrelated to that extension. I am not sure that checking for words in the issue is sufficient.

**Comment by JacksonKearl** [comment]
@bpasero this would be triggered by the inbox tracker. So it's saving the inbox tracker from digging up the right urls rather than saving them from doing anything at all.

**Comment by JacksonKearl** [comment]
Added some commands to the existing commands action to do this. It will direct users to the issue reporting template or CONTRUBUTING.md based on whats available.
![image](https://user-images.githubusercontent.com/8586769/77574360-1e8a9a00-6e8f-11ea-94a1-3ed8dcb81e73.png)
![image](https://user-images.githubusercontent.com/8586769/77574464-47ab2a80-6e8f-11ea-9d56-fbc1e5f0f1a9.png)

**Comment by jrieken** [comment]
Can you enumerate the list of supported commands? I have have tried /python but without success

**Comment by JacksonKearl** [comment]
\extPython
\extC
\extC++
\extTS
\extJS
\extC#
\extGo
\extPowershell
\extLiveShare
\extDocker

slashes are tilt-independent

**Comment by IllusionMH** [comment]
![image](https://user-images.githubusercontent.com/1312662/78040643-62dad600-7378-11ea-975d-38ae5f8f62a5.png)
Works as expected 😆

**Comment by JacksonKearl** [comment]
Side note: as with the prior bot, commands that close issues will not leave comments if the issue was already closed.

**Comment by jrieken** [comment]
Can we also add `/extJava` please

**Comment by JacksonKearl** [comment]
One issue with Java is that there's a bunch of different popular Java extensions:
![image](https://user-images.githubusercontent.com/8586769/78273790-2f0cc700-74c4-11ea-94c0-c73a8dd47c83.png)


It's not clear to me to which we should link.

**Comment by jrieken** [comment]
wow - soo many options. I think the red hat language service and debugger are the popular ones

**Comment by JacksonKearl** [comment]
Added `extJava` and `extJavaDebug`.
