### ISSUE TITLE
Accessing keybindings in webviews?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93331]
In the profiler webview, I want to be able to bind to some keyboard shortcuts. For example, Ctrl+F (or whatever the user has bound to "Find", should focus my custom filtering input. I'm not sure how to do this right now, it looks like there's not even an API to get the user's keyboard shortcuts.

**Comment by mjbvz** [comment]
Try creating commands (with keybindings) in your standard package.json that dispatch to your webview

There is no support for intercepting existing commands inside a webview
