### ISSUE TITLE
[Feature Request] Add Support New Line to Messages

### ISSUE THREAD

**Issue by BlackYuzia** [microsoft/vscode#93339]
Hi there.

#### Description

How we know we have method **showInformationMessage**, (check api for more info)
We can use it for show any info for user.

I want ask to add support `\n` **symbol** (aka New Line) to messages for formating text.

Why this is need?
For better formating text. What if I want add 3 or more line of text?

#### Screenshots

![image](https://user-images.githubusercontent.com/25010528/77489694-8d410680-6e41-11ea-89c0-7e6c0f06cb60.png)
![image](https://user-images.githubusercontent.com/25010528/77489703-97fb9b80-6e41-11ea-9fcb-04f3efcedcec.png)

**Comment by bpasero** [comment]
Closing as designed, I would like to keep notification styling to the minimum.
