### ISSUE TITLE
Debugger: message formatting using embedded variable does not work as described in DAP spec

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#93346]
Issue Type: <b>Bug</b>

Go extension's debug adapter uses structured message objects in error responses as specified in [DAP spec](https://microsoft.github.io/debug-adapter-protocol/specification). 

```
interface Message {
  ...
  /**
   * A format string for the message. Embedded variables have the form '{name}'.
   * If variable name starts with an underscore character, the variable does not contain user data (PII) and can be safely used for telemetry purposes.
   */
  format: string;

  /**
   * An object used as a dictionary for looking up the variables in the format string.
   */
  variables?: { [key: string]: string; };
...
}
```

We use the form '{}' for variable embedding as instructed. For example, [this](https://github.com/microsoft/vscode-go/blob/28bab92821e0233f2a3467b396ebfba22f94131e/src/debugAdapter/goDebug.ts#L922) is an example call site where the error object is constructed.

We observed the formatting does not work as expected when the message is shown to users.

![image](https://user-images.githubusercontent.com/4999471/77492678-87cec680-6e17-11ea-8463-d32bbf78b7c3.png)

From DAP tracing, we saw the debug adapter sent a message containing the format string and the 'variables' field with the referenced variable populated.

 ```
{"seq":0,"type":"response","request_seq":13,"command":"threads","success":false,
 "message":"Unable to display threads: \"{e}\"",
 "body":{
    "error":{
         "id":2003,
         "format":"Unable to display threads: \"{e}\"",
         "variables":{"e":"detached from the process"},
         "showUser":true
}}}
```

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. We have pushed a fix, the next VS Code insiders should include it. It would be great if you can try it out and let us know if the issue got fixed on your side. Thanks!
