### ISSUE TITLE
VSCode Showing Fake Error In Cpp-Properties

### ISSUE THREAD

**Issue by pitromattio** [microsoft/vscode#93341]
- VSCode Version: 1.43.2
- OS Version: Windows 10 1909

In the c_cpp_properties.json file, in the .vscode folder, VSCode says there are 4 errors. All those errors are because it cannot find a path to certain folders, but it is because they are under the mac configuration and I am on windows. Those are in fact fake errors, and they have never showed up before yesterday, when I opened the c_cpp_properties.json file to edit some cpp configurations, and those errors just popped up. The squiggly line below them is yellow instead of red, but its really annoying and I don't know how to remove it. 
![Capture](https://user-images.githubusercontent.com/22168596/77490937-aa270b00-6e3c-11ea-8400-bf2e1669bf0d.PNG)

**Comment by mjbvz** [comment]
Please start bu filing this against the c++ extension
