### ISSUE TITLE
[Request] Increase Number of Message 

### ISSUE THREAD

**Issue by BlackYuzia** [microsoft/vscode#93340]
Hi there. I will try be clear and short.

#### Description 

So, we have box messages (like info, warn, error messages)
I think we can use more like 3 message.

yep, I also know what he totaly 3, no more... BUT, I think 3 message is too small.
Why do not inc number of messages? **Like 5 or more.**
![image](https://user-images.githubusercontent.com/25010528/77489515-f411f000-6e40-11ea-876b-d9536c57e789.png)

Of course any count of messages can be too small for developer who push all info to information boxes... 

Also I was try push some info in to one message ... but I get screw up. 
There is reference to #93339

> After **inc** that I was also request inc `this.number++` again and again :eyes:

#### Screenshot

![image](https://user-images.githubusercontent.com/25010528/77489543-1146be80-6e41-11ea-8272-8d69efd07d35.png)

**Comment by bpasero** [comment]
This is to reduce the clutter for people that get spammed with notifications, no plans to change it.

**Comment by BlackYuzia** [comment]
@bpasero what about **auto delay**?

For example, currently,
If I create (show) more as 3 messages: `Message A1, A2, A3, A4`
`Message A1` was right away hide, I can't saw `Message A1` and I saw only A2, A3 and A4 messages.

What about delay something like ... I was push four messages.
User saw A1, A2, A3 message. Only when A1 message auto hide (or user manualy hide it)
vscode was show A4 message.

What about that?

**Comment by bpasero** [comment]
That is happening already, if you show 5 notifications, we display 3, but when 1 goes away, the other one will get revealed.

**Comment by BlackYuzia** [comment]
> That is happening already, if you show 5 notifications, we display 3, but when 1 goes away, the other one will get revealed.

Okey, I was try this one:
![image](https://user-images.githubusercontent.com/25010528/77512442-b8484c00-6e7b-11ea-9891-d89321c86ee2.png)

Just all what I get:
![image](https://user-images.githubusercontent.com/25010528/77512459-c302e100-6e7b-11ea-8d52-ee396eaf5abf.png)

Just three latest messages...

**Comment by BlackYuzia** [comment]
Oh, I actuly fuck up.
Yep. It works successfully. :thinking:
