### ISSUE TITLE
Change icon for .tsx file to .ts

### ISSUE THREAD

**Issue by calebmer** [microsoft/vscode#93347]
At Airtable we use the `.tsx` extension for all of our files. Including all our backend files. Having the React icon for all of these files is a little bit jarring. Could we change the `.tsx` icon extension to be identical to the `.ts` icon? Or at least make it configurable.

The way we think about it is `.tsx` is version 2 of the TypeScript dialect so we should just use it everywhere instead of supporting multiple dialects of TypeScript.

**Comment by JacksonKearl** [comment]
```
  "files.associations": {
    "*.tsx": "typescript"
  },
```

**Comment by calebmer** [comment]
@JacksonKearl will that break syntax highlighting for JSX?

**Comment by calebmer** [comment]
Confirmed that this does break JSX syntax highlighting. @JacksonKearl could you reopen?

**Comment by JacksonKearl** [comment]
Hm. Could you use a different icon set that doesn't give `.tsx` a react-looking icon?

**Comment by misolori** [comment]
You'll have to make this request over at the [seti-ui](https://github.com/jesseweed/seti-ui) repo since we use that icon library and don't make any customizations on our side.

**Comment by calebmer** [comment]
will do :+1:

https://github.com/jesseweed/seti-ui/issues/557
