### ISSUE TITLE
No response when pressing the 'clone repository' button 

### ISSUE THREAD

**Issue by qianxiaoxiamo** [microsoft/vscode#93349]
Issue Type: <b>Performance Issue</b>

No response when pressing the 'clone repository' button, no tips, no message,no popup. The root cause is  I don't have git installed on my computer. It SHOULD give the user a hint!

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
What clone button? Can you show me in a screenshot?
