### ISSUE TITLE
Sidebar bug

### ISSUE THREAD

**Issue by Prakhar314** [microsoft/vscode#93356]
When I move the cursor back and forth between the editor and project explorer sections a few times, these white pixels start showing up. Changing theme didn't do anything.

Version: 1.43.2 (user setup)
OS: Windows_NT x64 10.0.18363

![Annotation 2020-03-23 223007](https://user-images.githubusercontent.com/54989891/77508496-dcfaee80-6e90-11ea-8fd2-4b411d16ac86.png)

**Comment by gjsjohnmurray** [comment]
Try launching like this:

`code --disable-gpu`

**Comment by Prakhar314** [comment]
Disabling gpu works.

**Comment by deepak1556** [comment]
Thanks for the update! you can disable hw acceleration via the app following https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration . This is an issue with chromium, so might want to wait for updates to see if things get better.

Does this issue happen with https://vscode-web-test-playground.azurewebsites.net/ on chrome ?

**Comment by Prakhar314** [comment]
No, it works alright on the playground.

**Comment by deepak1556** [comment]
@Prakhar314 Can you try our exploration build without disabling gpu https://az764295.vo.msecnd.net/exploration/d45720441c97c3cca64c2868e2399c07a207f7e4/VSCodeSetup-x64-1.45.0-exploration.exe and see if the issue still repros. Thanks!
