### ISSUE TITLE
External debug console adds space in second line

### ISSUE THREAD

**Issue by pke** [Microsoft/vscode#9335]
- VSCode Version:
Version 1.3.1
Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
Date 2016-07-12T13:35:06.227Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version: Windows 8.1

Steps to Reproduce:

1. Start debugging with an external console window
2. The console window contains a first line with the debugger listening info
3. The third line contains a space
4. `console.log("test")` will be printed with a space in front.
5. All following lines are ok

![image](https://cloud.githubusercontent.com/assets/164625/16874535/0e1e1ace-4a9a-11e6-9c68-708025e14765.png)

**Comment by weinand** [comment]
@pke I cannot reproduce this:

![2016-07-15_17-39-14](https://cloud.githubusercontent.com/assets/1898161/16879947/1e804c02-4ab3-11e6-9973-e9b303d7fac9.png)

**Comment by pke** [comment]
hmm... 
![image](https://cloud.githubusercontent.com/assets/164625/16880306/e7ae0bd6-4ab4-11e6-8052-aa65fd3b12dc.png)

What we do now? I am using the newest IDE version

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by weinand** [comment]
What version of node are you using? (I don't mean the node 5.10 that VS Code uses internally)

**Comment by pke** [comment]
```
$ node -v
v6.2.1
```

I'll try without extensions later.

**Comment by weinand** [comment]
I can reproduce the issue with node 6.2.1.

**Comment by weinand** [comment]
The problem is a node problem and independent from VS Code.
When node is started with `--debug` a space appears on the following line:

![2016-07-15_23-11-58](https://cloud.githubusercontent.com/assets/1898161/16888638/b8752d68-4ae1-11e6-9c37-bdafbdc4b47b.png)

**Comment by pke** [comment]
thanks for figuring that out. I filed a bug over at nodejs https://github.com/nodejs/node/issues/7755
