### ISSUE TITLE
GremlinPython compatibility

### ISSUE THREAD

**Issue by nikhilpsathyanathan** [microsoft/vscode#93357]
- VSCode Version:   1.42.2
- OS Version: windows 10

Steps to Reproduce:

1. pip install gremlinpython   // tornado package issue

Vscode jupyter notebook section wont load when i installed that package
but i able to work on jupyter notebook

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
/causedByExtension please file this on the repo for the Python extension, which currently provides the notebook feature.
