### ISSUE TITLE
Find/Replace input box doesn't allow type new line by keyboard

### ISSUE THREAD

**Issue by lostindark** [microsoft/vscode#93354]
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
Scenario 1:
1. Without select any text in document, and no text in clipboard.
2. Open Find/Replace.
3. Trying to type Enter or Shift-Enter in the input box. Expect the input box expand to show a new line. Nothing happened.

Scenario 2:
1. Select multi-line text from current editor window.
2. Open Find/Replace.
3. No text shows up in Find input box.
The correct behavior is: fill the multi line text select into Find input box.
Note: Select text which is within a single line works.

Working Scenario:
1. Copy multi line text to clipboard.
2. Open Find/Replace.
3. Paste multi-line text to Find or Replace input box.
4. The input box expanded to multi line and correctly showed the copied text.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ChrisPapp** [comment]
Should you deside that this is not the desired behaviour, can I work on fixing this?

**Comment by lostindark** [comment]
Any update on the issue?

**Comment by rebornix** [comment]
@lostindark the keybinding to insert a new line in find on Windows is ctrl+enter.
