### ISSUE TITLE
Jupyter bugs: Out of sync source code and Undo doesn't work

### ISSUE THREAD

**Issue by sotheanith** [microsoft/vscode#93352]
VSCode version 1.43.2
**Problem**: Source code out of sync
**Description**: 
I encounter a problem with Jupyter notebook where source code on display in vscode is different that source code on disk(I assume this is the code executed by the kernel). I need to reopen the ipynb file to see the updated code. The problem usually occurs when cells are being executed and I make some editing to the code. For example, if I comment out multiple lines of code, it looks correct in vscode but it will throw a syntax error when I execute the cell. Upon reopening the ipynb file, the "#" is being inserted in the middle of a line instead of at the beginning like what vscode shown previously. Enable "Auto Save" causes the bug to occur more often. I started to have this problem two patches ago. 

VSCode Insider 1.44.0
**Problem**: Ctrl+Z doesn't work in Jupyter notebook
**Description**: Ctrl+Z doesn't work in Jupyter notebook but it works in other files. I try to setup Ctrl+Z in keybinding and it still doesn't work. I set it for "python.datascience.notebookeditor.undocells" and "python.datascience.undocells"

**Comment by gjsjohnmurray** [comment]
/causedByExtension please file this on the repo for the Python extension, which currently provides the notebook feature
