### ISSUE TITLE
VSCode incorrectly handles indention & outdention of "alignment along open delimiter"

### ISSUE THREAD

**Issue by circlecrystal** [microsoft/vscode#93358]
Wish to indent/outdent a block of code smoothly when developing in Python language, however, the vscode incorrectly aligns the block of code to "the guide of tabs". This behavior causes lots of trouble in daily usage (I have to re-adjust the block of code manually, repeatedly, to comply with the pep8 'align with the opening delimiter' requirement).

Most of all, this problem exists not only in Python but also other languages. The number of spaces of a code block indention/outdention is not the same. Very troublesome.

To better illustrate the issue, two gifs are provided from screen recording (the first for the current problematic vscode behavior, the second for the ideal behavior)

Compare vscode behavior (incorrect):
![vscode_indent_outdent](https://user-images.githubusercontent.com/5665980/77512400-f1011900-6ead-11ea-838c-da6015c8652b.gif)

Vim behavior (correct):
![vim_indent_outdent](https://user-images.githubusercontent.com/5665980/77512446-04ac7f80-6eae-11ea-9f71-47bd20857d6a.gif)

**Comment by rebornix** [comment]
Our indentation rules are regex based and can't handle this case properly, suggestion is using formatters.
