### ISSUE TITLE
completion.py consumes a lot of CPU (95-100%). Find References also not working

### ISSUE THREAD

**Issue by rahulpathakml** [microsoft/vscode#93355]
Hi

The vscode 1.43.1, the "Find all Reference" does not work and I can see that the completion.py consumes a lot of CPU and "Find All Reference" window remains empty.

Also when I hover on any symbol, instead of highlighting information, it shows a popup with "Loading" constantly.

- VSCode Version: 1.43.1
- OS Version: Ubuntu 18.04 64Bit 

Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:17:38.324Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic

Steps to Reproduce:

1.  Open code and "Find All References" for any symbol

![Screenshot from 2020-03-25 11-45-25](https://user-images.githubusercontent.com/23165276/77508751-70ccba80-6e91-11ea-999e-c01ca93fecbf.png)

Does this issue occur when all extensions are disabled?: Yes/No
This Reference feature in Right Click does not appear with all extensions disabled

**Comment by rahulpathakml** [comment]
Is "Find Reference", Symbols Peeking not an VScode implementation?

How can I find the extension which is doing this?

**Comment by JacksonKearl** [comment]
Language features (like go to definition, find all references, etc) are provided by the language extensions. In this case likely the Python extension.
