### ISSUE TITLE
Color decorator not showing when assigned to a LESS variable

### ISSUE THREAD

**Issue by orobert91** [microsoft/vscode#93351]
![image](https://user-images.githubusercontent.com/6403705/77498736-c3bd5800-6e26-11ea-983d-a37b03206129.png)

As soon as a semi-colon is added, the color decorator disappears:

![image](https://user-images.githubusercontent.com/6403705/77498752-cd46c000-6e26-11ea-9ac1-30870b9cfe30.png)

Plaftorm: Windows 10 x64 1909
Version: 1.43.0
Extensions installed: Debugger for Chrome

**Comment by orobert91** [comment]
No it is not.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo such as version and platform information

**Comment by orobert91** [comment]
I have added the requested info

**Comment by IllusionMH** [comment]
Looks like duplicate of #92417

Try to update to latest version 1.43.1 where it should be fixed

**Comment by orobert91** [comment]
@IllusionMH it is fixed indeed, thanks
