### ISSUE TITLE
Bot Proposal: Remove duplicate search

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93360]
* Since a while GH has duplicate search (while filing an issue) and we kinda compete with that now
* Our duplicate search is rarely successful often adds noise like this: user files issue, bot adds duplicate comments, user adds replies to that comment saying its not a dupe.

**Comment by isidorn** [comment]
If we do not want to remove it I would increase the threshold when we decide to comment, so the bot would comment more rarely.

**Comment by JacksonKearl** [comment]
@chrmarti owns duplicate search
