### ISSUE TITLE
Code Lens References misplaced

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#93367]
Issue Type: <b>Bug</b>

It seems that in some cases the code lens text seems to be off and overlapping code.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/30625381/77518779-a3b98300-6e7e-11ea-8bc5-9845f06300ee.png">

VS Code version: Code - Insiders 1.44.0-insider (073a24de05773f2261f89172987002dc0ae2f1cd, 2020-03-24T07:05:24.597Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 8, 7|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|-psn_0_20120367|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
maybe related to https://github.com/microsoft/vscode/issues/92660

**Comment by jrieken** [comment]
Any change that you can create repro steps?
