### ISSUE TITLE
JS spread operator messing with suggestions

### ISSUE THREAD

**Issue by Mangatt** [microsoft/vscode#93361]
- VSCode Version: 1.43.2
- OS Version: Win 10

Steps to Reproduce:

1. Create simple functional Component with spread operator for props
2. Add PropTypes for that Component
3. See provided suggestions for props of that Component
4. When you remove spread operator, everything works just fine

Does this issue occur when all extensions are disabled?: Yes

![spread1](https://user-images.githubusercontent.com/2706990/77514849-7d153f80-6eb2-11ea-8ef6-9695d5d425b0.png)
![spread2](https://user-images.githubusercontent.com/2706990/77514857-80103000-6eb2-11ea-95f5-e2290f0b7f32.png)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by Mangatt** [comment]
Not working:
```javascript
import React from 'react'
import PropTypes from 'prop-types'

const Component = ({ prop, ...otherProps }) => <div />

Component.propTypes = {
	/** Test prop */
	prop: PropTypes.bool
}

const test = <Component />

export default Component
```
Working correctly:
```javascript
import React from 'react'
import PropTypes from 'prop-types'

const Component = ({ prop }) => <div />

Component.propTypes = {
	/** Test prop */
	prop: PropTypes.bool
}

const test = <Component />

export default Component
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/37950 to track upstream
