### ISSUE TITLE
serverReadyAction isn't launching default browser on macOS Catalina

### ISSUE THREAD

**Issue by AlphaComposite** [microsoft/vscode#93371]
Hi. I tried using VS Code on an ASP.NET Core project and this methodology doesn't launch a browser on my Mac. It will build and it will listen on the correct port, but it will not launch the default browser. 

- VSCode Version: 1.43.2
- OS Version: macOS Catalina 10.15.3 

Here's my launch.json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/Project/bin/Debug/netcoreapp3.1/Project.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Project",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ASPNETCORE_URLS":"https://localhost:5001"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        }
    ]
}


Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
What is the exact message sent to the console that announces the used web port?

**Comment by AlphaComposite** [comment]
![image](https://user-images.githubusercontent.com/25360554/77593844-eef58500-6ec2-11ea-8086-abf768d6b1b3.png)

**Comment by weinand** [comment]
The serverReady feature works by scraping the program's output and looking for something like `listening on port 3000`. I cannot see anything like this is your output.
Please see our documentation for this feature: https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program

**Comment by AlphaComposite** [comment]
If you're going to introduce a breaking change to functionality, perhaps there could be an example of usage for ASP.NET Core projects. The example you sent isn't an ASP.NET Core project. The program.cs file will have to be changed, but to what...I have no idea because we don't have to manually change the program.cs file in Visual Studio for Mac/Mono/ or Rider for the browser to launch when we click "Run" to start our ASP.NET Core projects.

**Comment by weinand** [comment]
@AlphaComposite What "breaking change to functionality" are you talking about? There were no changes in this area since the feature was introduced.

Just add some console output of the form "listening on port NNNN" to your program.
