### ISSUE TITLE
The OUTLINE section can overlap with OPEN FOLDERS

### ISSUE THREAD

**Issue by wbpluto** [microsoft/vscode#93376]
Issue Type: <b>Bug</b>

Drag the border of the OUTLINE section up.
It can be overlap with OPEN FOLDERS section

VS Code version: Code 1.43.2 Stable and 1.44 Insider
OS version: Windows_NT x64 10.0.19587

![image](https://user-images.githubusercontent.com/5191513/77863282-bbfd1980-7253-11ea-9e13-2813d60bec75.png)

![image](https://user-images.githubusercontent.com/5191513/77944824-2f556880-72f2-11ea-9ecd-faa8d4011e30.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by wbpluto** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

Screenshot added.
Yes, reproduced on latest stable version 1.43.2

**Comment by mjbvz** [comment]
Please test this in the insiders build, VS Code 1.44

**Comment by wbpluto** [comment]
> Please test this in the insiders build, VS Code 1.44

Still reproduced on 1.44 insider

**Comment by isidorn** [comment]
I can not reproduce this. Also assigning to @joaomoreno to try to repro

**Comment by joaomoreno** [comment]
We fixed this last week.
