### ISSUE TITLE
vscode freezes when open specific JSON

### ISSUE THREAD

**Issue by Smoovsky** [microsoft/vscode#93370]
- VSCode Version: 1.43.2
- OS Version: win10-x64 1903

Steps to Reproduce:

1. open the JSON file 
2. try to interact with the editor a bit (select text, type, etc..)
3. vscode freezes

Does this issue occur when all extensions are disabled?: Yes

The JSON file sizes 2.5MB with moderate complexity. 
I tried on two machines with extensions disabled, both were able to reproduce the issue.

Tried:
`"editor.largeFileOptimizations": true,
"files.maxMemoryForLargeFilesMB": 12288,
`
didn't help.

Also, it seems that keeping the ".txt" file extension has a better chance to freeze the editor sooner than having ".json" file extension,

Once downgrade back to 1.42.1, the problem is gone and the editor is considerably more responsive (with 1.43.2, the editor was laggy after open the JSON before it crashes).

See the sample JSON:
[scrambledJson.txt](https://github.com/microsoft/vscode/files/4380032/scrambledJson.txt)

**Comment by aeschli** [comment]
This looks like a general issue with the editor and large file sizes: I can reproduce that even in plain text mode, editing the file is very sluggish.

**Comment by davidnich** [comment]
possibly related issue: #93310

**Comment by alexdima** [comment]
I have found this to be caused by bracket matching, specifically the way in which the reverse string is computed. A workaround is to use `"editor.matchBrackets": "never"`.

**Comment by roblourens** [comment]
I opened the file in insiders and it still hangs

![image](https://user-images.githubusercontent.com/323878/78380122-ff7bbe80-7598-11ea-91a7-38663707e9b2.png)

**Comment by alexdima** [comment]
@roblourens I have tried with VS Code stable (which should be the same version you used for verification), but the file does not freeze for me.

@Smoovsky Can you please verify if opening the file leads to a no longer responding dialog?

**Comment by roblourens** [comment]
Tried again and got the same result. And this is without `editor.matchBrackets` or any other settings set.

**Comment by Smoovsky** [comment]
@alexdima  I'm on 1.44.0 now, still able to reproduce this issue:
![image](https://user-images.githubusercontent.com/34542126/80215662-3321a400-8680-11ea-9810-feda811c1dc3.png)

**Comment by alexdima** [comment]
Thank you, after more trying I was able to reproduce too.
