### ISSUE TITLE
Extension development host crash in v1.43 - not in v1.42

### ISSUE THREAD

**Issue by pythoulon** [microsoft/vscode#93373]
- VSCode Version: 14.3.1/2
- OS Version: Windows 10 Home 1903 (build 18362.720)

Steps to Reproduce:

I have an extension project that uses the [@abandonware/noble](https://github.com/abandonware/noble) npm module. 
The first  `import * as noble from '@abandonware/noble';` causes the extension development host window to close without warning or error message in any of the output channels.
This occurs since 1.43. If I revert back to 1.42, it's back in order and everything works fine.
The setup to reproduce is a bit complex because of the nature of the noble module, which requires specific hardware (a 4.0 Bluetooth USB dongle) and software (the driver thereof).

I've tried to step through the code to try and understand what happens during the import that causes it to die (step into from the import line), but I tend to get lost in the extension host js code. It dies in `_activateExtensions()` in a file called `extHostExtensionActivator.ts` buried deep in `c:\Program Files\Microsoft VS Code\resources\app`.

I'm assuming this is a VS code issue and not a noble issue because it worked fine in 1.42.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does noble use native modules?

**Comment by deepak1556** [comment]
`1.43` ships with a new major electron version `7.1.11` and node version `12.8.1` while `1.42` is based on `6.1.5`. Can you make sure module is built for this version ? This mostly likely a `NODE_MODULE_VERSION` mismatch.

What is the output of launching code with `--verbose` flag ?

**Comment by pythoulon** [comment]
That may be the problem. Noble uses the USB module which is native and which I currently build against electron v6. I will build against v7, try again and report here.

**Comment by pythoulon** [comment]
Yep. That solved it. Thanks.
