### ISSUE TITLE
Option to open new tab on "Go to Definition"

### ISSUE THREAD

**Issue by s-gbz** [microsoft/vscode#93375]
Hello beautiful people!
First of all - thanks a lot for your continuous support and effort! VSCode is my goto editor of any kind and I strongly recommend the rest of the world population to use it as well. I came up with a new feature that could be very handy.

**Problem:**
It can be quite annoying to jump into a different spot in your source file when looking up a function definition (_in the same file_) and not being able to find the place you went from.

![image](https://user-images.githubusercontent.com/23424538/77526188-770b6880-6e8a-11ea-95c6-991134b9c6d6.png)
-> 
![image](https://user-images.githubusercontent.com/23424538/77526242-8ee2ec80-6e8a-11ea-934c-212f59502316.png)

**Solution / Feature Request:**
I'd love to have the option to open a new tab when navigating to a function definition (_in the same file_) and keep my main tab on the code at hand.  
I could then activate split view and have my file in two tabs on different positions.
![image](https://user-images.githubusercontent.com/23424538/77526638-32cc9800-6e8b-11ea-962a-c4cf068aeb08.png)

**Disclaimers:**
1. I noticed that there is an option to peek a definition while researching similiar issues and will try it out in the mean time.
-> _But_ this is a workaround and I'd love to have separate tabs that I can put into split view and move around freely.
2. I can open split view by hand and search for the definition I'm interested in. 
-> _But_ developers are lazy and so am I. I can't stress how often I'm faced with the issue described.

I guess this feature shouldn't be too hard to workout if we decided to pursue it.
It's probably still a challenging task for a newby of this codebase, but I would give it a try anyway if you like. 

Thank you for your time.
This feature is unavailable on v.1.43.2

**Comment by jrieken** [comment]
> This feature is unavailable on v.1.43.2

Sure about that? There is the "Open Definition to the Side" command. 

<img width="1158" alt="Screenshot 2020-03-25 at 17 37 16" src="https://user-images.githubusercontent.com/1794099/77561656-47c31e80-6ebf-11ea-83ef-836beee41e45.png">

There is also support for `alt+cmd+click` (config depended) to open a definition to the side via mouse

![Mar-25-2020 17-39-19](https://user-images.githubusercontent.com/1794099/77561880-9a043f80-6ebf-11ea-8ba2-4ff152579d33.gif)

**Comment by s-gbz** [comment]
Well `alt+cmd+click` offers the exact funtionality I requested. Lesson learned, thanks a lot..

The only thing left to consider is maybe highlighting/ mentioning the [shortcut list](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) to people that open feature PRs (in case you see the situation repeating).

Closed if there's nothing to add from your side :-)
