### ISSUE TITLE
Suggestions on Python highlighting

### ISSUE THREAD

**Issue by BornForFever** [microsoft/vscode#93382]
In VS Code, only builtin functions and classes are highlighted, while user-defined aren't. As for methods, both builtin and user-defined aren't highlighted. This makes those who has OCD feel awful.
![批注 2020-03-25 194935](https://user-images.githubusercontent.com/62426149/77533660-3f281380-6ed2-11ea-87ff-4978efef8850.png)
I hope both builtin and user-defined functions, classes and methods can be lighlighted.

**Comment by alexr00** [comment]
This would be something that your favorite python extension should implement using the new proposed semantic tokens api https://github.com/microsoft/vscode/issues/86415
