### ISSUE TITLE
[BUG] Can't Create Empty Option

### ISSUE THREAD

**Issue by BlackYuzia** [microsoft/vscode#93386]
#### Description

When I try create "empty" or "clear" option for user choose I was stuck with troubles.
I can't create empty option.

For example,

How we can see, we have `weapon_` option and `{empty}` option.
But actualy, this is only a space. 
![image](https://user-images.githubusercontent.com/25010528/77537323-8b5d5e80-6ea6-11ea-9d07-f86e4b175ebc.png)

So, because this is space I get that:
![image](https://user-images.githubusercontent.com/25010528/77537394-b2b42b80-6ea6-11ea-8adc-9c8acc025ec1.png)
This is a mistake (for my) I don't need space.

**I want get clear (empty) option without spaces (like `""` in javascript.**)

#### Information 

- VSCode Version: 1.43.2
- OS Version: Win 7 x64

#### Steps to Reproduce:

Space:
1. Create a snippet string
2. Add `${1|value1,value2, |}`, 
where `, |` is "empty" option.
3. Get space.

String only:
1. Create a snippet string
2. Add `${1|value1,value2,|}`,
where `,|` is empty option.
3. Get this:
![image](https://user-images.githubusercontent.com/25010528/77537830-6a493d80-6ea7-11ea-8c44-9da6569f657f.png)

Maybe, this isn't bug and this `*as-designed`, then can I get answer how to create empty options?

**Comment by jrieken** [comment]
Textmate snippets do not support empty options. That's how it is defined and the only workaround would be enclose things in another placeholder that you can then clear

**Comment by BlackYuzia** [comment]
> Textmate snippets do not support empty options. That's how it is defined and the only workaround would be enclose things in another placeholder that you can then clear

Can u give me example?
