### ISSUE TITLE
Missing "Select Default Shell" option for new VS Code instances

### ISSUE THREAD

**Issue by ktmeagher** [microsoft/vscode#93384]
When I launch a new instance of VS Code and the Terminal view is open, the dropdown for selecting a Terminal is missing the "Select Default Shell" option. The only option available is the previously selected shell. If you then use the + (add) button to add a new terminal window, you can then find the "Select Default Shell" option in the dropdown. The "Select Default Shell" option should be available when a new instance of VS Code is started.

<img width="1668" alt="VSCode_Missing_002" src="https://user-images.githubusercontent.com/59568577/77535234-a614e080-6e70-11ea-99f1-3c46fe8001f2.PNG">
<img width="1663" alt="VSCode_Missing_001" src="https://user-images.githubusercontent.com/59568577/77535235-a6ad7700-6e70-11ea-8df2-fce8175a8bb5.PNG">

**Comment by manastalukdar** [comment]
Its there, but you need to have > 1 terminal open for that option to show in the drop-down. Most likely a regression.

**Comment by Tyriar** [comment]
Probably a bug caused by the recent view/panel refactoring.
