### ISSUE TITLE
File compare opens the second file (or activates the tab) instead of opening compare for markdown

### ISSUE THREAD

**Issue by pdanpdan** [microsoft/vscode#93380]
Issue Type: <b>Bug</b>

Hello.
When using "File: Compare Active File With..." and selecting a file two things happen (instead of opening the compare between files):

- if the file is already opened in tab than that tab is focused
- else a tab is opened and focused for that file

This was introduced in: https://github.com/microsoft/vscode/commit/705aa30fe2c2e51b43dc6cc2bd17a7abb2a4e4bb#diff-ea019bd8e81f52d572da1f850e4a77cd

See https://github.com/microsoft/vscode/issues/88528 for the previous bug on this.

VS Code version: Code - Insiders 1.44.0-insider (073a24de05773f2261f89172987002dc0ae2f1cd, 2020-03-24T05:37:12.592Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
i18n-ally|ant|1.13.7
color-info|bie|0.5.1
markdown-mermaid|bie|1.4.2
gitignore|cod|0.6.0
transformer|dak|1.6.0
vscode-eslint|dba|2.1.1
githistory|don|0.6.3
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
vscode-pull-request-github|Git|0.15.0
sass-lint|gle|1.0.6
asciidoctor-vscode|joa|2.7.13
l13-diff|L13|0.21.0
rainbow-csv|mec|1.6.0
git-graph|mhu|1.22.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
vetur|oct|0.24.0
vuehelper|oys|0.1.0
vscode-versionlens|pfl|0.25.0
vscode-sort-json|ric|1.18.0
vscode-gtm|s3r|0.2.0
todotasks|san|0.5.0
sass-indented|syl|1.8.0
language-stylus|sys|1.11.0
gitflow|vec|1.2.1
markdown-all-in-one|yzh|2.7.0
cursorCharCode|zei|0.1.1

</details>

**Comment by bpasero** [comment]
Should be fine today with https://github.com/microsoft/vscode/commit/b78d88303be13bd5b851396ebf0ac54c1475d0b8

**Comment by pdanpdan** [comment]
I confirm its fixed in Version: 1.44.0-insider (user setup)
Commit: fc14315c37f3017af937270532ae2adfbdb6b45f
Date: 2020-03-25T10:51:45.506Z

**Comment by pdanpdan** [comment]
I'm sad to report this is broken again in: Version: 1.44.0-insider (user setup)
Commit: 6cf3dd97465b2f4f666b66758991d720e003b0f4
Date: 2020-03-27T06:00:06.803Z

I think this time is from https://github.com/microsoft/vscode/commit/ebcc8208f8acc8aca3b98c6d670619ab82677d2f#diff-ea019bd8e81f52d572da1f850e4a77cd

**Comment by bpasero** [comment]
I pushed a change that should fix it again, thanks for noting.

**Comment by pdanpdan** [comment]
It is fixed in Version: 1.44.0-insider (user setup)
Commit: 13b38d2a494612ace32c4fb878824d6329d4c51e
Date: 2020-03-30T07:32:20.024Z

Ty

**Comment by bpasero** [comment]
Thanks!

**Comment by pdanpdan** [comment]
Hello.
It is broken again in Version: 1.45.0-insider (user setup)
Commit: 44c5185373d5f209cd6c0b5d29a216fb801da34e
Date: 2020-04-10T18:12:33.780Z

Thank you.

**Comment by bpasero** [comment]
I can reproduce but only for markdown files. Somehow there is an override of custom editors kicking in, not clear to me why @mjbvz 

![image](https://user-images.githubusercontent.com/900690/79096969-da3c3c80-7d5e-11ea-8f8d-74e9cf83600a.png)

**Comment by pdanpdan** [comment]
Working as expected on Version: 1.45.0-insider (user setup)
Commit: c8826e4ff5246775ebee0fb932402de6af55ddc8
Date: 2020-04-14T05:58:16.222Z

Ty

**Comment by isidorn** [comment]
User verified, adding verified label.
