### ISSUE TITLE
IntelliSense doesn't respond to touch.

### ISSUE THREAD

**Issue by lujcon** [Microsoft/vscode#9338]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open any document with IntelliSense support
2. Press Ctrl + space to open suggestions
3. Use touch to choose one of the available options

It's impossible to use IntelliSense on touch only devices. Touch keyboard (Windows 10) doesn't have up/down arrows and IntelliSense suggestions doesn't support touch events.

![capture](https://cloud.githubusercontent.com/assets/1280399/16875132/0995345c-4a9e-11e6-9026-3c4221cc8e50.JPG)

**Comment by joaomoreno** [comment]
Great catch!

**Comment by juliannojungle** [comment]
Can also confirm the bug in other touch devices, such as HP Detachable PC. The scroll was indeed fixed, but not tapping an item to see the details. Verified on VsCode version 1.11.2.

Workaround to see the extension details:
1 - Enable the full touch keyboard: On "Windows 10, All Settings, Devices, Typing", enable "Add the standard keyboard layout as a touch keyboard option";
2 - Open the touch keyboard, tap on the language icon (lower right) and select the full layout keyboard (this way you get the up/down arrows); 
3 - On VsCode, tap on the extensions icon, search for the desired extension, on the touch keyboard use the arrow down/up to navigate and press enter to view the details.

This way you can open the details panel, but sadly the touch scroll doesn't work on this panel as well...
