### ISSUE TITLE
ctrl + / no working

### ISSUE THREAD

**Issue by luizfloripa** [microsoft/vscode#93388]
Issue Type: <b>Bug</b>

My keyboard ctrl + /  simply dont comment code, i don't know what more i can do to fix it.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (10.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
remote-wsl|ms-|0.42.4
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
vscode-icons|vsc|10.0.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language are you editing?

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
