### ISSUE TITLE
Custom language extensios are deleted on update

### ISSUE THREAD

**Issue by pcbt** [microsoft/vscode#93383]
- VSCode Version: 1.43.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Copy your custom language extension to "Microsoft VS Code\resources\app\extensions"
2. Update the VS Code

Does this issue occur when all extensions are disabled?: Yes

I have custom language extension which I copy under the "\Microsoft VS Code\resources\app\extensions".  My extension is deleted on every update. I think VS Code should keep the manually copied extensions.

**Comment by mjbvz** [comment]
Please install your extension using the normal flow, such as using `install from vsix`

The folder you listed is internal to vs code so modifying it is like changing the product code
