### ISSUE TITLE
Two build/watch tasks in same workspace can no longer run simultaneously since v1.43

### ISSUE THREAD

**Issue by markfinlabs** [microsoft/vscode#93398]
I have a workspace with two projects (folders) each of which has a build/watch task. It used to be fine to have the build/watch tasks run simultaneously, even on startup, but now this is not possible. The first task can always run but the second will produce a dialog stating "The task 'X (Y)' is already active." and offering to terminate or restart the first task. So it seems VS Code now sees them as one task.

The tasks both have the form below where I have tried renaming groups/labels and other things to work around this problem with no success.

```json
    {
      "label": "Build/watch 1",
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "option": "watch",
      "problemMatcher": [
        "$tsc-watch"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "group": "Build/watch 1a",
        "clear": true,
      }
      // "runOptions": {
      //   "runOn": "folderOpen"
      // }
    }
```

**Comment by markm77** [comment]
Thanks VS Code team for fixing this!
