### ISSUE TITLE
Move terminal off IWorkbenchActionRegistry.registerWorkbenchAction

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93390]
This registry is deprecated, the recommendation is to add keybindings and command palette entries directly. See https://github.com/microsoft/vscode/issues/93317

To verify make sure Terminal: Find Next/Previous only show up once in the command palette

![image](https://user-images.githubusercontent.com/2193314/77539716-0e5ac680-6e5f-11ea-8307-90f139da1dd9.png)

**Comment by Tyriar** [comment]
Preferable ways:

https://github.com/microsoft/vscode/blob/d468b457a2f82264d3c53cc98c5f3077a4db32c2/src/vs/workbench/browser/parts/editor/editorCommands.ts#L296-L314

https://github.com/microsoft/vscode/blob/ac209e9314586bdaa19c5ea856e42f86c8e451f1/src/vs/workbench/contrib/webview/browser/webview.contribution.ts#L37-L39

**Comment by jrieken** [comment]
what's here to verify?

**Comment by Tyriar** [comment]
The find next and find previous commands should not show up twice in the command palette and they should work.
