### ISSUE TITLE
Extra tab while copy-pasting some part of the code 

### ISSUE THREAD

**Issue by Ajitesh13** [microsoft/vscode#93391]
- VSCode Version: 
- OS Version: ubuntu 18.10 LTS

Steps to Reproduce:

1. Open a file where there is already some code, in any programming language 
2. Select a small part of the code 
3. Open a new window and paste that code 

You will get an extra "tab" after pasting, in the first line of the newly pasted code. Which i suspect shouldn't occur 

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/confirmationPending

I wasn't able to repro this using the instructions you gave. I used 1.43.2 on Windows.

Please add more details. Screenshots are good, and can often be pasted directly into the GH textfield. Animated GIFs are even better.

Please also provide your VS Code version info.

**Comment by rebornix** [comment]
What you ran into might be related to auto indent, which you can turn off by `editor.autoIndent`.
