### ISSUE TITLE
User-defined font is not used when opening folder

### ISSUE THREAD

**Issue by lepa22** [microsoft/vscode#93396]
Issue Type: <b>Bug</b>

On Ubuntu 18.04 (also 19.10), after setting a user-defined font and opening VSCode in a folder, the default VSCode font is used.

However, if, instead of a folder, a file is selected to be opened, using for example the following command, the font that is used is the user-defined one:

    code path/to/folder/file.py

**Steps to reproduce:**

1. Set a font of your choice.
2. Close VSCode.
3. Open VSCode in a folder using a terminal. For example:

       code path/to/folder

**Expected result:**

Open VSCode with the user-defined font.

**Actual result:**

VSCode opens using its default font.

---
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|7.53GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.69010

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Are you configuring the font as a workspace setting or as a user setting?

**Comment by lepa22** [comment]
I am configuring it as a user setting.

**Comment by alexdima** [comment]
@lepa22 VS Code has a concept of folder settings. Can you please try opening another folder? In the folder you open, very likely there is a file at `.vscode/settings.json` where perhaps you have changed the font family again.

**Comment by lepa22** [comment]
Yes, you are right! The `.vscode/settings.json` had indeed the previous font settings stored. I edited the file to set the correct font and now VS Code displays it as it should.

However, why does VS Code have this behavior? Shouldn't the in-folder `settings.json` be updated when I change the font from within VS Code settings?

**Comment by alexdima** [comment]
VS Code has a very intricate settings story, and folder settings overwrite user settings. There is this help page to explain it -- https://code.visualstudio.com/docs/getstarted/settings

**Comment by lepa22** [comment]
OK, I'll check it out. Thank you very much for looking into this!
