### ISSUE TITLE
Custom debug adapter, console ignores output containing ANSI color codes

### ISSUE THREAD

**Issue by jcward** [Microsoft/vscode#934]
I'm working on a custom debug adapter extension (a compiled executable, though not in Typescript, from Haxe source). I'm compiling my project and sending all STDOUT from the compile process to the debug console via [OutputEvents](https://github.com/Microsoft/vscode-mock-debug/blob/master/src/common/debugProtocol.d.ts#L103-L110). However, only some of the lines actually show up on the console. Many are ignored with no errors or other information.

Are there any restrictions on what can be displayed? Character lengths? Special characters? Multi-line strings? I did once note that splitting a long multi-line string into single lines and sending multiple messages may have helped.

Has anyone else experienced this problem? I'll try to put together a testcase extension and post it here later.

**Comment by isidorn** [comment]
No, there should be no restrictions. We do some grouping of output which might have caused an issue.
A testcase extension would be great so we could investigate on our side.

Thanks

**Comment by jcward** [comment]
Ah ha, I think I found the issue by looking at my log with `less` - my compiler outputs ANSI color sequences, and I was passing this directly through to the console:

![image](https://cloud.githubusercontent.com/assets/2192439/11592176/20f3b186-9a5a-11e5-8ec8-9b226d9cf8b8.png)

I stripped the color codes with by replacing `/\x1b\[[0-9;]*m/g` with `''` and I'm now getting the output I expect.

I've edited the issue title to indicate the problem, but I'm unblocked -- feel free to do what you like with this issue.

**Comment by weinand** [comment]
@bpasero ANSI color sequences should work, right?

**Comment by bpasero** [comment]
Yes, color codes from the target to the repl should show up as expected. You can see this from mocha tests that use coloring. We might not support the full set though. So we need to know what sequences are used here.

**Comment by jcward** [comment]
The above messages, when output to a terminal, look something like this:

![image](https://cloud.githubusercontent.com/assets/2192439/11593408/6dd4db0e-9a61-11e5-8c7d-476163e41c54.png)

In the sequence above I see `[33;1m`, `[33m`, `[1m`, and `[0m` (bright yellow, yellow, bright, and off) -- nothing too fancy. The only oddity I notice in the sequence above is that the off code `[0m` is sometimes repeatedly called even when a color is not currently active, e.g.:

![image](https://cloud.githubusercontent.com/assets/2192439/11593564/395ff272-9a62-11e5-98b5-8ba13b615146.png)

**Comment by isidorn** [comment]
Ben you wanna take this over, if not assign back.

**Comment by bpasero** [comment]
@jcward since we do support ANSI coloring in other places, I think the output you send might not be UTF 8 and thus we fail to understand the escape sequences. I am closing this one optimistically.
