### ISSUE TITLE
Python gets deleted every update

### ISSUE THREAD

**Issue by josh-65** [microsoft/vscode#93408]
Issue Type: <b>Bug</b>

I like to keep python and other interrupters installed in the VS code folder for easy moving and locating but when I update VS code it deletes them.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (11.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-peacock|joh|3.6.0
chat|kar|0.33.0
python|ms-|2020.3.69010
remote-wsl|ms-|0.42.4
vsliveshare|ms-|1.0.1783
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
python|tht|0.2.3

</details>

**Comment by joaomoreno** [comment]
Please don't put anything inside the VS Code folder. It's not supported.
