### ISSUE TITLE
manually run editor actions without binding to shortcut 

### ISSUE THREAD

**Issue by vegerot** [microsoft/vscode#93400]
For example, let's say I would want to run `editor.action.rename` without pressing F2, or if there an editor action (or any command) that is not bound to a keybinding that I want to run.  I intuitively thought I could just press shift+command+P and type "editor.action.foo", and I could run it from there.  However, I don't seem to know of any way to manually run editor actions.  

Proposal: Have shift+command+P autocomplete "editor.action.*" commands and have it execute them for you.

I've confirmed this behavior does not exist on the latest insider version of VSCode (
```
1.44.0-insider
fc14315c37f3017af937270532ae2adfbdb6b45f
x64
```
)

Thank you for taking the time to read this 😀

**Comment by ArturoDent** [comment]
Which language are you using at the time?  I think all languages do not support `Rename Symbol` for one thing.  And so the command palette will not show the `Rename Symbol` command when you type `rename`.  In the correct file type, you could type `rename` and choose `Rename Symbol` and it would work.

Your proposal to have the command palette  surface all commands by typing `editor.action.` is an intriguing one.

**Comment by vegerot** [comment]
At this time I'm mainly using TS and Vue.  I know the Vue language server doesn't support rename at this time.  But it's still a useful feature.  Another reason I'd like this feature is while testing out keybindings.  When I press command K+S and see the different options for commands, sometimes I'd like to see what they do

**Comment by bpasero** [comment]
This works now when you use insiders with the new quick open work:

![image](https://user-images.githubusercontent.com/900690/77613129-36fbc280-6f2a-11ea-9aba-a34864497490.png)

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by vegerot** [comment]
@bpasero I am an insider, and I actually wrote this issue while running Insider.  I am not getting this behavior when I press shift+command+p to open the quick actions, though.  I might be doing this wrong (but I don't know how I could be).  Could you reference me to the PR for this feature?

**Comment by bpasero** [comment]
@vegerot from what date is your insider version (Help > About) and what command ID are you using?

**Comment by vegerot** [comment]
```
❯ code-insiders --version
1.44.0-insider
e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c
x64
```

```
Version: 1.44.0-insider
Commit: e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c
Date: 2020-03-26T05:50:18.281Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by bpasero** [comment]
@vegerot got it, yes you need to paste the full absolute ID of the command, nothing else will be found. I do not think it is useful to show all the command IDs with fractional parts.

**Comment by vegerot** [comment]
@bpasero why don't you think it's useful?  It's good for discovering the possibilities of what you can do, and to speed up typing them.  

Additionally, since VSCode autocompletes everything else, it's a very unintuitive behavior.  So unintuitive, in fact, that I tried this for minutes, googled how to do it, wrote a GitHub issue, and communicated for days about this without realizing I could do it the whole time.  Because I had just assumed that VSCode autofills everything.

Is there a reason to NOT do it?  If I type `editor.action.ren`, why wouldn't somebody want to VSCode to speed it up for them by autofilling it for them?

**Comment by bpasero** [comment]
I am certain that a command should have a good human readable label and that you should be able to discover all commands typing that label. If a command does not provide this, we should update the label or alias to ensure that.

Mainly, quick open gives feedback as to why a input string matches a command by highlighting that part of the label. I worry that command identifiers (substrings) would result in too many matches that are hard to understand for the user as to why they suddenly match. This would change the way commands are returned from how it works today and could frustrate users a lot because suddenly a word that is typed produces a lot more command results and even the order might be different, so it destroys a lot of muscle memory.

**Comment by vegerot** [comment]
@bpasero thank you.  That cleared things up for me.  Does VSCode currently have a way of autosuggestions only after a certain point?  For example, I think we'd both agree that it would be good thing if it started autofilling after `editor.action.r`, `editor.action.rename` would be a suggestion.  But you probably wouldn't want that to be suggested after `edit`.  Does VSCode have a way of doing that, or does it gotta be all or nothing?  You have convinced me that if it is an all or nothing decision it's probably best to go with nothing.

**Comment by bpasero** [comment]
@vegerot if you ask about the input field in the quick pick, no, there is no support for auto suggest in there currently.

**Comment by vegerot** [comment]
Alright, then I agree with your decision.  Too bad it couldn't start suggesting after a certain prefix

**Comment by bpasero** [comment]
**Verification:**
Paste the absolute command ID into the command palette to see the command appear.
