### ISSUE TITLE
Formatting issue.

### ISSUE THREAD

**Issue by neerajrk2509** [microsoft/vscode#93404]
Issue Type: <b>Performance Issue</b>

I am facing a formatting issue while saving the files. My VS Code gets stuck and I need to wait till the formatter is formatting my document on save or even on manually triggering the format command. Previously, it use to happen in the blink of an eye but since the last two or three updates I have been facing the issue. Please resolve it as soon as possible as I always to restart my VS Code.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    69	  3112	code main
    1	   133	  3288	   gpu-process
    0	    23	  4276	   utility
    0	    11	 10744	   electron-crash-reporter
    0	    66	 11000	   window (Issue Reporter)
    0	   264	 11144	   window (paydetails.component.html - nexusmobile_25_02_26 - Visual Studio Code)
    0	     5	  1784	     winpty-process
    0	     7	 10156	       console-window-host (Windows internal process)
    0	     4	 12984	       "C:\Program Files\Git\bin\bash.exe"
    0	     6	 12556	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    29	  6364	     searchService
   13	   207	  6408	     extensionHost
    0	    26	  3644	       "C:\Users\neeraj.khandelwal\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\neeraj.khandelwal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=6408
    0	   320	  7200	       electron_node tsserver.js 
    0	    20	  2084	         electron_node typingsInstaller.js typesMap.js 
    0	    45	  7596	       electron_node tsserver.js 
    0	   307	 11032	       "C:\Users\neeraj.khandelwal\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\neeraj.khandelwal\.vscode\extensions\angular.ng-template-0.900.18\server --logFile c:\Users\neeraj.khandelwal\AppData\Roaming\Code\logs\20200325T184723\exthost1\Angular.ng-template\nglangsvc.log --logVerbosity terse --ngProbeLocations c:\Users\neeraj.khandelwal\.vscode\extensions\angular.ng-template-0.900.18\server,d:\nexusmobile_25_02_26 --tsProbeLocations c:\Users\neeraj.khandelwal\.vscode\extensions\angular.ng-template-0.900.18,d:\nexusmobile_25_02_26 --node-ipc --clientProcessId=6408
    0	    30	 13136	       "C:\Users\neeraj.khandelwal\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\neeraj.khandelwal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=6408
    0	    22	 14404	       "C:\Users\neeraj.khandelwal\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\neeraj.khandelwal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=6408
    0	    23	 15024	       electron_node server.js 
    0	    13	 12176	     watcherService 
    0	     5	 10200	       console-window-host (Windows internal process)
    2	    66	 12240	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (paydetails.component.html - nexusmobile_25_02_26 - Visual Studio Code)
|    Folder (nexusmobile_25_02_26): 3632 files
|      File types: ts(1274) svg(830) html(646) js(232) scss(231) png(142)
|                  xml(19) json(18) woff2(6) ttf(6)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.900.18
vscode-color|ans|0.4.5
blamer-vs|bea|0.5.2
vscode-multi-line-tricks|big|0.0.3
node-snippets|chr|1.0.0
angular-schematics|cyr|3.3.1
angular2-snippets|dan|1.0.21
githistory|don|0.6.3
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
vscode-svn|eli|0.1.0
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|3.20.0
tortoise-svn|fan|0.1.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-ionic-snippets|fiv|2.1.0
auto-rename-tag|for|0.1.1
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
triggertaskonsave|Gru|0.2.13
theme-macos-classic|hua|1.2.0
easy-icons|jam|0.3.1
angular-essentials|joh|9.0.1
vscode-peacock|joh|3.6.0
svn-scm|joh|2.10.6
vscode-icon-theme|jtl|1.6.6
angular1-code-snippets-johnpapastyle|lpe|0.1.0
code-beautifier|mic|2.3.3
vscode-autoprefixer|mrm|3.0.0
vscode-scss|mrm|0.9.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
color-highlight|nau|2.3.0
angular-console|nrw|11.1.3
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|4.0.1
seti-icons|qin|0.1.3
try-material-icon-theme|raf|3.9.0
vscode-seedling-icon-theme|ras|0.5.0
typescript-hero|rbb|3.0.0
ts-import-assistance|Sam|0.0.10
code-settings-sync|Sha|3.4.3
bootstrap4-vscode|the|6.1.0
Angular2|UVB|0.4.1
vscode-angular-support|vis|0.1.4
vscodeintellicode|Vis|1.2.6
vscode-todo-highlight|way|1.0.4
local-history|xyz|1.8.1
material-theme|zhu|3.2.4
html-css-class-completion|Zig|1.19.0
svn-helper|Zlo|1.0.3

(5 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> Previously, it use to happen in the blink of an eye but since the last two or three updates I have been facing the issue.

Previously we would simply cancel formatting after ~800ms - that means the file would have been saved without being formatted. Format on save is off by default, e.g users manually enable it and we have gotten feedback that we should honour user-choice and then wait for formatting to be finished. What you can do

* press cancel when the progress notification appears -> this will skip format on save for that one instance
* disable format on save globally via `editor.formatOnSave` or per language via `"[go]": { "editor.formatOnSave": false}`
