### ISSUE TITLE
source control panel takes unusually long to inititialize (detect?) git repository

### ISSUE THREAD

**Issue by lukkyjoe** [microsoft/vscode#93401]
Issue Type: <b>Bug</b>

actual: source control tab takes around 12 seconds to detect my git repo
expected: source control tab pretty immediately detects my git repo. 
source control tab takes around 12 seconds to detect my git repo

the way i opened vscode is to use the `code .` command from my working directory

here is a video recording of the lag: https://www.loom.com/share/f56d2b001b074e7da267ec091b29287b

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.24GB free)|
|Process Argv|-psn_0_5051601|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
vscode-pull-request-github|Git|0.15.0
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
python|ms-|2020.3.69010
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1783
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
heroku-command|pko|0.0.8
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|1.8.0
svg-preview|Sim|2.8.3
regexworkbench|ste|2.0.4
sass-indented|syl|1.8.0
language-stylus|sys|1.11.0
vscode-icons|vsc|10.0.0
file-size|zh9|0.1.3
material-theme|zhu|3.2.4

(5 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you reproduce with `code --disable-extensions`?

**Comment by lukkyjoe** [comment]
I realized once i disable-extensions it behaves as it should without delay.
Feel free to close if that means it's not within scope. 
But if I may ask, do you know of a fast way to test which extension may be causing my delay besides trial and error? i have lots of them....

**Comment by joaomoreno** [comment]
- Open `Developer: Show Running Extensions`
- Click the `Start Extension Host Profile` button at the top right, it's the circle
- Reproduce the issue
- Stop profile

You can show me a screenshot of the profile result. You can also send me the profiling results.
