### ISSUE TITLE
Can Timeline support author date as an option?

### ISSUE THREAD

**Issue by fivegreenapples** [microsoft/vscode#93405]
I'm trying out the new timeline view in production VS Code and loving it.

Looks like the entries for git commit history are showing committer date. Would it be possible to add an option to switch this to author date?

My use case is that we migrated our repo from Perforce to Git last year and in doing so we have a huge number of commits all with the same date, but each have the original perforce submit date preserved in the git author date field.

Cheers, Ben

**Comment by eamodio** [comment]
Closed by d8b1776

**Comment by fivegreenapples** [comment]
Thank you!
