### ISSUE TITLE
Give more context: Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#9340]
Just noticed this in selfhost, is there any chance we could print more info on the error like the resource that caused it?

![image](https://cloud.githubusercontent.com/assets/900690/16875291/fd7c6edc-4a9e-11e6-8ece-fa3ff2dbab6c.png)

**Comment by alexandrudima** [comment]
What file is it? What grammar --- or was it transient?

If it is transient and you don't notice it at the perfect time (when it happens), then the chances to reproduce are slim even if I print the line the grammar mis-behaves on.

**Comment by bpasero** [comment]
@alexandrudima I only found this later when looking at the log and thought if you give me more context (grammar name, file name) I could try to reproduce.

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscode-textmate#36
