### ISSUE TITLE
View action select boxes are not working properly in the sidebar

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93415]
1. Move Output or Terminal to Sidebar inside an existing viewlet
2. Click the select box in the view header
🐛 => the view collapses

Also the styling is off.

**Comment by sbatten** [comment]
To Verify:
1. Move terminal and output to the sidebar (in a viewlet with other views, not alone)
2. Verify that the select box (for selecting output channel and terminal) work correctly (you can click them and select an item).

**Comment by alexr00** [comment]
Something seems to be up with focus:
![blinky](https://user-images.githubusercontent.com/38270282/78382439-2c4ec680-75d7-11ea-8358-af84bc14e74d.gif)

**Comment by sbatten** [comment]
@bpasero @joaomoreno @isidorn took a sampling of committers on the team for the select box. I guess an open select box isn't maintaining focus within the header action toolbar so content auto-hides. any ideas?

**Comment by isidorn** [comment]
@sbatten this looks like the custom windows select box which is done by an outisde contributer. Your best bet is to investigate on your own.

**Comment by sbatten** [comment]
Turns out the custom select boxes use the context view service for rendering the dropdown. This means focus is not maintained just like the triple dot with menus. This is a general problem with the context views and focus. The custom select box doesn't need to use the context view service, but I think this problem should be tackled more generally.

@joaomoreno How would you feel about having the context view service allow a mode where it creates a view as a child of a passed in element and uses fixed position?

**Comment by joaomoreno** [comment]
> @joaomoreno How would you feel about having the context view service allow a mode where it creates a view as a child of a passed in element and uses fixed position?

Sure, give that a try.

**Comment by sbatten** [comment]
@joaomoreno, i tried it, seems to work 🤞

**Comment by sbatten** [comment]
found an issue in settings editor had to revert, bundling with separate PR
