### ISSUE TITLE
Webview-rendered output is wider then other output

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93412]
See attached screen shot

* have text-output => 👍 it is aligned nicely
* have output that is shown in the webview -> :bug: it is wider and underflows the output switcher

<img width="47" alt="image" src="https://user-images.githubusercontent.com/1794099/77564052-6b3b9880-6ec2-11ea-9a36-2707ee3c9f99.png">

**Comment by rebornix** [comment]
@jrieken I just pushed another change that fixes the width issue as I set `left` on the output container.
