### ISSUE TITLE
Tab Tab Auto Completion

### ISSUE THREAD

**Issue by jimbits** [microsoft/vscode#93410]
Issue Type:  Integrated Terminal Issue 
When trying to auto complete directory or file paths using the TAB key. I get a message in the 

Tab was pressed waiting for the second key chord
The key combination (Tab, Tab) is not a command.

It just started one day can't relate it to anything directly that I installed... Tab Tab auto completion is working in my MAC Terminal.app.

Any help would be appreciated.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 17.7.0
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)|

**Comment by gjsjohnmurray** [comment]
@jimbits please test after disabling all your extensions. Search Command Palette for "reload" to get a handy command for doing that.

**Comment by jimbits** [comment]
Still get the same error message even though all extensions are disabled using the reload with Developer Reload With Extensions Disabled. I am not sure why but option tab will do auto complete so I have access to the feature just not the way I used to use it?

**Comment by Tyriar** [comment]
It looks like you have a keybinding assigned to `Tab, Tab` which is a bad idea. Check your keybindings.json file, you say it happens with disabled extensions so it must be a keybinding you configured?

You can always turn off chords in the terminal with this setting:

```
"terminal.integrated.allowChords": false
```

If you can identify the Tab, Tab keybinding you could also add `"when": "!terminalFocus"` to it so it doesn't trigger within the terminal.
