### ISSUE TITLE
[theme] Wrong coloring in for cycle and break whole coloring

### ISSUE THREAD

**Issue by zozzz** [Microsoft/vscode#9341]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make a javascript file with the following contents:
```javascript
function test() {
	for (var i=0 ; i<l ; ++i) {

	}
}
```
another example:
```javascript
for (var i=0 ; i<l ; ++i) {

}
```
![example](https://cdn.pbrd.co/images/bMlkBeGSd.jpg)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#215
