### ISSUE TITLE
Emmet balance not working with PHP files

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#93413]
- VSCode Version / OS Version:
```
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

- Steps to Reproduce:
![emmet](https://user-images.githubusercontent.com/30685349/77564752-82c75100-6ec3-11ea-9e00-da0c1d44c24e.gif)

- Does this issue occur when all extensions are disabled?:
Yes

**Comment by octref** [comment]
This should be done by a PHP extension. Emmet does not understand PHP.

**Comment by kanlukasz** [comment]
> 
> 
> This should be done by a PHP extension. Emmet does not understand PHP.

Hmm, ok, but it's not inside a php tag.
I mean, it's in a php file, but outside of the php tag.
Note that Emmet tagging works well there, eg: `div>p*10`
