### ISSUE TITLE
Using --disable-telemetry in a test pipeline still makes DNS requests

### ISSUE THREAD

**Issue by tspence** [microsoft/vscode#93417]
- VSCode Version: 1.42
- OS Version: Mac OS X Catalina

In our automated test pipeline, my team started to see messages about rejected DNS requests for `dc.services.visualstudio.com`.  We were running VSCode with the `--disable-telemetry` command line parameter as described in [test/automation/src/code.ts](https://github.com/microsoft/vscode/blob/master/test/automation/src/code.ts).

We discovered that we could eliminate these messages by creating a custom settings.json file that set both `enableCrashReporter` and `enableTelemetry` to false.

Open question: Is the `--disable-telemetry` parameter working correctly, or does it only disable one type of telemetry?

Steps to Reproduce:

1. Set up a test pipeline that can detect DNS requests.
2. Launch vscode with the `--disable-telemetry` option.
3. Note that a request to contact `dc.services.visualstudio.com` occurs.

Workaround:
1. For the automated test suite server, create a User/settings.json file containing the following text:

```
{ 
  "telemetry.enableCrashReporter": false, 
  "telemetry.enableTelemetry": false 
}
```
2. Launch vscode with the option `--user-data-dir=`and point it to a folder containing that user/settings.json file.
3. VSCode does not make any DNS requests to `dc.services.visualstudio.com`.

**Comment by deepak1556** [comment]
The endpoint is not from the crashreporter, delegating to @sandy081 for telemetry related issue.

**Comment by sandy081** [comment]
Sorry I do not own telemetry related issues. I guess someone from Redmond team owns this.

@mjbvz Please reassign accordingly.

**Comment by Tyriar** [comment]
@tspence does it happen if you use `--disable-extensions` too?

**Comment by Tyriar** [comment]
@sbatten I guess you own this now?

**Comment by tspence** [comment]
> @tspence does it happen if you use `--disable-extensions` too?

Our test pipeline is specifically testing our custom built extensions, so we're using `'--extensionTestsPath=<path>'`.  I can try that out, but I'd imagine that --disable-extensions might interfere with the tests :)

**Comment by sbatten** [comment]
after a while of debugging I realize this is definitely extensions activating and includes some built-in extensions because --disable-extensions does not eliminate all cases. this is because the vscode-extension-telemetry module does not pay attention to the --disable-telemetry flag but rather the user setting `telemetry.enableTelemetry`.

**Comment by sbatten** [comment]
added note the identifiers associated with all events will be stripped still in this case

**Comment by sbatten** [comment]
With the release of new extension api and the update of the `vscode-extension-telemetry` module as well as updating our built-in extensions to use such module, this is resolved for the out of the box experience. Please file additional issues on extensions that do not properly use the new module or API.

**Comment by roblourens** [comment]
What's the new API? @tspence please let us know if you've verified that this works as expected in Insiders now.

**Comment by sbatten** [comment]
We can only verify this issue for the built-in extensions. To verify:
1. Download the latest stock vs code insiders without any settings.
2. Run it with the `--disable-telemetry` CLI flag. 
3. Use any network monitoring program to verify that calls to `dc.services.visualstudio.com` do not occur.
