### ISSUE TITLE
When terminal is moved, show running tasks does not work

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93416]
1. Move the terminal view to a new location. 
2. Run a long running build task
3. Switch to a new view so that terminal is no longer visible
4. Click show running tasks in the status bar

🐛 => It fails trying to show the old terminal panel (that is now hidden) instead of the hidden terminal view in its new view.

**Comment by alexr00** [comment]
@sbatten is this something I should fix in tasks? I do a bunch of checking if the terminal is visible then checking if the correct terminal is visible.

**Comment by sbatten** [comment]
fixed terminal showPanel https://github.com/microsoft/vscode/commit/0693d298a95f136855b5556a6a663123739bb6c7
