### ISSUE TITLE
Icon ugly on Latte Dock

### ISSUE THREAD

**Issue by coldspark29** [microsoft/vscode#93421]
- VSCode Version: 1.43.1
- OS Version: KDE 5.18.3

Steps to Reproduce:

1. Pin launcher to Latte Dock
2. Close the app

Does this issue occur when all extensions are disabled?: Yes

This bug is probably caused by a bad svg icon file

![image](https://user-images.githubusercontent.com/19779511/77571877-582ec580-6ece-11ea-8329-b9920eb75732.png)

**Comment by misolori** [comment]
We don't use an SVG for dock icons, we use a high quality image (png) on Linux. So I'm not sure why you're seeing this weird pixelation and likely an issue with Latte Dock. Can try this on a regular dock?

**Comment by coldspark29** [comment]
Well, it is possible that is an issue with Latte Dock. I unpinned and pinned it again, which solved it now. It did not solve it four days ago. I really have no idea. On Cairo Dock there are no issues. I think you can close this for now. Will get back at you if the problem reappears.

**Comment by psifidotos** [comment]
make sure that you have confirmed that this is now because of a faulty desktop file:
https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F
