### ISSUE TITLE
VSCode failing to debug python code in Ubuntu 16.04 LTS!

### ISSUE THREAD

**Issue by fieraloca** [microsoft/vscode#93429]
# VSCode Version:

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-88-generic

# OS Version: Ubuntu 16.04 LTS

# Steps to Reproduce:

1. Create and open a python file (testing.py; add a single line to it)
``` python 
print('... testing'). 
```

2.Configure launch.json to use python. 
3. Select Python: Interpreter. 
I have tried  with conda environments; and python 3.5; 3.6; 3.6 with same error result. 
4. Run the debugger (F5). 

Does this issue occur when all extensions are disabled?: Yes
Only python extension is enabled. Version : 2020.3.69010 (19 March 2020)

# Error  list

## Error Window Popup
``` python 
Session[1] timed out waiting for <debugpy.adapter.components.missing.<locals>.Missing object at 0x7fb9e2753cc0> to connect
```

## Console output
``` python
(TESTSUITE) rpglover@u832f94cf022e52:~/Desktop/deleteme$  env DEBUGPY_LAUNCHER_PORT=40883 /anaconda3/envs/TESTSUITE/bin/python /rpglover/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher /rpglover/Desktop/deleteme/testing.py 
Traceback (most recent call last):
  File "/anaconda3/envs/TESTSUITE/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/TESTSUITE/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/rpglover/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/__main__.py", line 80, in <module>
    main()
  File "/rpglover/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/__main__.py", line 42, in main
    launcher.connect(launcher_port)
  File "/rpglover/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/../../debugpy/launcher/__init__.py", line 27, in connect
    sock.connect(("127.0.0.1", launcher_port))
ConnectionRefusedError: [Errno 111] Connection refused

```

See attached file for outputs during debugging. 

[vscode not running python in ubuntu 16.04.txt](https://github.com/microsoft/vscode/files/4383119/vscode.not.running.python.in.ubuntu.16.04.txt)

**Comment by mjbvz** [comment]
Please start by filing this issue against the python extension

**Comment by heliocarbex** [comment]
I had a similar error today. I just reload VS Code with extensions disabled and after I reloaded again in normal state. The error has gone.

**Comment by a-kanaan** [comment]
I am facing the same issue

**Comment by zhongruiwang** [comment]
Got same issue on a PYNQ linux running on a Xilinx ZC702 FPGA
