### ISSUE TITLE
html.customData samples don't work as expected in VS Code 1.43.2

### ISSUE THREAD

**Issue by kpranavk** [microsoft/vscode#93427]
Our team has developed a bunch of custom tags which will be used as part of the HTML authoring. I started here https://code.visualstudio.com/docs/languages/html#_html-custom-data and ended up looking at samples at https://github.com/microsoft/vscode-custom-data

I am running VS Code 1.43.2 and unable to make these samples work as documented. I also see some limitations in the feature.

BUG: I tried the sample and I can only see the root element. After inserting <foo and space I don't see any attribute suggestions, although I can see the presence of the attribute if I scroll down in the suggestions list.

FEATURE REQUEST: I am unable to author child tags. the documentation only talks about root element and its attributes and global attributes. how do we author child tags? I tried to add another "tags" element as a sibling to "attributes" but it didn't do any good.

FEATURE REQUEST: How can I stop Intellisense showing HTML tags under custom tags? I ideally want to see only our custom tags.

BUG/FEATURE REQUEST: Whatever that is working is working only in workspace setting and not in global settings. As long as my settings.json is in .vscode directory it works. If I move the settings.json along with the html-data.json file to %appdata%\Code\User, it doesn't work at all. I also tried to restart VS Code with no luck. In fact I find more interesting and useful in user setting mode and not in workspace setting. Why would a user take pains to build a schema for himself/herself to insert those custom tags that others don't even know what they are and how to interpret? custom tags are more useful if a platform is written to parse them and an entire team or their customers can make use of it.

Is the validation built-in once I define my schema in the html-data.json? I am assuming yes but I couldn't validate because my basic scenario isn't working.

I love this overall feature and would love to make full use of this, provided I get some guidance on how to make this work.

Thanks, 
Pranav

**Comment by mjbvz** [comment]
ref https://github.com/microsoft/vscode-custom-data/issues/8

**Comment by aeschli** [comment]
We need separate issues in order to track the issues

Custom data has no support for element hierarchies. We currently have no plans to add that, we want to keep it simple. It will be up to users to know what elements can be inside what other elements.

I think there's currently no to disable the built-in html tags.

Custom data currently can only be defined in workspace settings, not in user settings. We have issue #79911 for that. The preferred way of consuming custom data is through extensions. So once you have a good version of your custom data, put it in an extension and publish it.

**Comment by aeschli** [comment]
We currently have no plans to add element hierarchies to custom data. If you want to provide smarter suggestions, I suggest to do this through an extension that implements a completion provider. We have the [vscode-html-languageserver](https://github.com/microsoft/vscode-html-languageservice) node module to simplify the implementation (check out the `ICompletionParticipant`)
