### ISSUE TITLE
Support \K regex in TextMate grammar patterns

### ISSUE THREAD

**Issue by xorye** [microsoft/vscode#93426]
For creating a VS Code language extension, it would be great if TextMate grammar patterns support the \K regex pattern: https://www.regular-expressions.info/keep.html

- VSCode Version: 1.43.0
- OS Version: Fedora 30

Steps to Reproduce:

1. Create a new VS Code extension, add the following to its package.json:
```
{
  "contributes": {
    "languages": [
      {
        "id": "abc",
        "extensions": [".abc"]
      }
    ],
    "grammars": [
      {
        "language": "abc",
        "scopeName": "source.abc",
        "path": "./syntaxes/abc.tmGrammar.json"
      }
    ]
  }
}
```
2. In the `./syntaxes/` directory, create a new file `abc.tmGrammar.json` with these contents:
```
{
  "scopeName": "source.abc",
  "patterns": [{ "include": "#expression" }],
  "repository": {
    "expression": {
      "match": "h\\Kd",
      "name": "keyword.other.definition"
    }
  }
}
```
3. Launch the VS Code extension, open a file and set the language mode to "abc".

4. Type "adhd" in the file.

What the syntax highlighting should be:
![image](https://user-images.githubusercontent.com/20326645/77575072-57376d00-6ea9-11ea-8e63-ac5d9eeebccf.png)

What the syntax highlighting actually is:
![image](https://user-images.githubusercontent.com/20326645/77575179-8c43bf80-6ea9-11ea-89b9-850d3e59f467.png)

**Comment by ArturoDent** [comment]
See related issue https://github.com/microsoft/vscode/issues/87842

**Comment by alexdima** [comment]
The TextMate grammars are standardized across editors and they all use a regular expression engine called `oniguruma`. We do not want to diverge from the official TextMate grammars because we believe that having grammars that work across multiple editors is more beneficial.
