### ISSUE TITLE
Endless update loop 🔄 to same version 1.44.0-insider to 1.44.0-insider

### ISSUE THREAD

**Issue by mavaddat** [microsoft/vscode#93423]
Symptoms I observe are like those in these existing, closed issues:

- [Insiders newest version update infinite loop bug important install-update verified vscode-build #70802 by B1indB1ink was closed on Mar 20, 2019](https://github.com/microsoft/vscode/issues/70802)
- [Infinite loop update to the same version *duplicate #70804 by KaoImin was closed on Mar 20, 2019](https://github.com/microsoft/vscode/issues/70804)

### Version info 
Property | Value
-- | --
Version | 1.44.0-insider (system setup)
Commit | 073a24de05773f2261f89172987002dc0ae2f1cd
Date | 2020-03-24T05:37:12.592Z
Electron | 7.1.11
Chrome | 78.0.3904.130
Node.js | 12.8.1
V8 | 7.8.279.23-electron.0
OS | Windows_NT x64 10.0.19587

### System info
Property | Value
-- | --
CPUs | Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.91GB (4.68GB free)
Process Argv | --disable-extensions
Screen Reader | no
VM | 0%

### Extensions enabled

Extension | Author (truncated) | Version
-- | -- | --
npm-intellisense | chr | 1.3.0
vscode-markdownlint | Dav | 0.34.0
vscode-eslint | dba | 2.1.1
githistory | don | 0.6.3
prettier-vscode | esb | 3.20.0
code-runner | for | 0.9.17
beautify | Hoo | 1.5.0
vscode-codemetrics | kis | 1.24.0
vscode-github | Kni | 0.30.3
bash-ide-vscode | mad | 1.8.0
vscode-azurefunctions | ms- | 0.21.0
python | ms- | 2020.3.69010
remote-wsl | ms- | 0.44.2
azure-account | ms- | 0.8.8
powershell-preview | ms- | 2020.3.0
vsliveshare | ms- | 1.0.1847
vsliveshare-audio | ms- | 0.1.80
debugger-for-chrome | msj | 4.12.6
vscode-for-node-js-development-pack | nod | 2.0.1
java | red | 0.58.0
vscode-xml | red | 0.11.0
vscode-checkstyle | she | 1.3.2
vscodeintellicode | Vis | 1.2.6
vscode-java-debug | vsc | 0.25.1
vscode-java-dependency | vsc | 0.9.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.22.2
vscode-maven | vsc | 0.21.2
vscode-import-cost | wix | 2.12.0
vscode-preview-server | yui | 1.3.0
markdown-all-in-one | yzh | 2.7.0

 
### Steps to Reproduce:

1. Run Visual Studio Code 1.44.0-insider as user or admin
2. See ⚙update pending 
3. Click gear ⚙to install update
4. > Visual Studio Code - Insiders 1.44.0-insider is being installed in the background; we'll let you know when it's done.
5. > Restart Visual Studio Code - Insiders to apply the latest update.
6. Start Visual Studio Code as **user**
7. Observe that extensions have errors loading due to permissions broken
8. Restart Visual Studio Code as **admin** to resolve extension broken permissions issue
9. Go to step 2. above, repeat 🔄

or

9. See ⚙update pending 
10. Try uninstalling Visual Studio Code entirely and reinstalling it from scratch using latest Visual Studio Code insiders installer
11. Go to step 2. above, repeat 🔄

Does this issue occur when all extensions are disabled?: Yes ✅ (`code-insiders --disable-extensions`)

**Comment by Tyriar** [comment]
FYI an easy workaround would be to switch to the user setup which has been the recommended install type for a while.

**Comment by mavaddat** [comment]
> FYI an easy workaround would be to switch to the user setup which has been the recommended install type for a while.

This did not work for me. I get the same problem whether I install as user or admin. I also get the same update issue in my portable (USB jump drive) Visual Studio Code Insiders: the evasive _pending update_ that can never be resolved or satisfied.

**Comment by mavaddat** [comment]
I have to apologize: It seems as though running updates with the extensions disabled (`code-insiders --disable-extensions` and then _click gear ⚙to install update_) actually resolves the issue. I was wrong in stating that the problem persisted. 🤦🏽‍♂️
