### ISSUE TITLE
Самопроизвольная смена цветовой схемы

### ISSUE THREAD

**Issue by danis-msk** [microsoft/vscode#93422]
Issue Type: <b>Bug</b>

Здравствуйте. Сегодня, после обновления VS Code, цветовая схема Monokai стала выглядеть иначе - изменились цвета, в целом текст смотрится более кислотным, ярким. Это не приятно для глаз, прошу вернуть мне как было !

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:36:51.261Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU B830 @ 1.80GHz (2 x 1795)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.40GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.7.0
EditorConfig|Edi|0.14.4
vs-color-picker|lih|1.0.0
vscode-language-pack-ru|MS-|1.44.0
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.0.1
wordpress-toolbox|wor|1.3.6

</details>

**Comment by mjbvz** [comment]
> Hello. Today, after the VS Code update, the monokai color scheme began to look different - colors have changed, the text looks more acidic and bright. It's not nice for the eyes, please give me back as it was

**Comment by mjbvz** [comment]
@danis-msk Can you please share a screenshot of this difference?

**Comment by danis-msk** [comment]
I apologize, I was inattentive, I chose the wrong color scheme. This is an incredible stupid mistake on my part. Thanks for the quick response, this is very cool

  
>Среда, 25 марта 2020, 21:45 +03:00 от Matt Bierner <notifications@github.com>:
> 
> 
>@danis-msk Can you please share a screenshot of this difference?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С уважением, Данис Ханипов
Телефон:  +7 977 983-27-94
E-mail:  danis_msk@mail.ru
