### ISSUE TITLE
Consider using new ARIA "code" role on the code editor

### ISSUE THREAD

**Issue by joanmarie** [microsoft/vscode#93438]
ARIA recently added a new `code` role ([definition](https://w3c.github.io/aria/#code)). As you will see there, it states:

> The primary purpose of the code role is to inform assistive technologies that the content is computer code and thus may require special presentation, in particular with respect to synthesized speech. More specifically, screen readers and other tools which provide text-to-speech presentation of content SHOULD prefer full punctuation verbosity to ensure common symbols (e.g. "-") are spoken.

It might be worth considering apply this role to the code editor in VSCode.

Use case: When the user is in settings, the user might not wish to hear common punctuation (commas, periods, colons, parentheses, etc.). But in the code editor, every symbol should be spoken. As a result, the user has the following options:

* Change the screen reader's punctuation level to ALL when in the code editor and to SOME/MOST/NONE when in settings.
* Put up those commas, periods, colons, parens, etc. being read in the settings.

I've just made a change to Orca master which looks for ARIA's `code` role and verbalizes all punctuation inside of it when the user's punctuation level is set to SOME or MOST. (If it's set to ALL, the speech synthesizer is already doing the work for Orca; if it's set to NONE, that means that for whatever reason the user has explicitly indicated they want to hear absolutely no punctuation).

I'm relatively certain that if VSCode were to apply the ARIA role to its code editor, Orca would exhibit the specified ARIA behavior but otherwise continue to work as expected. But if I'm wrong, I will happily make additional changes to Orca so that everything continues to work well.

I have absolutely no clue about what other screen readers might do should this change be made.

ATTN: @isidorn (who asked me to file this when Orca was in theory ready for the change)

**Comment by isidorn** [comment]
@joanmarie makes sense. Since we are now wrapping up the milestone I suggest we do this in our April milestone in 10 days. We will do it at the beginning of the milestone to test and get feedback for all platforms. If only Orca behaves well, we will apply the role `code` only on Linux for now.

@leonardder for NVDA

Also I wish I had some VoiceOver contacts. @joanmarie might you know somebody over at Apple that works on VoiceOver?

**Comment by MarcoZehe** [comment]
This is a great idea! A question about this, after reading the definition and the [role mapping](https://w3c.github.io/core-aam/): Does this go on what is considered the text box, or a container of that? @joanmarie how did you envision this? Because if it went on the textbox, the semantics for the textbox would be lost. However on the container, it would make more sense, because then output, suggestions etc., would also be read with all punctuation. Note that this is not to be confused with the "application" role on the root of VS Code. Joanie, is this what you had in mind? One of the intermediary containers?

**Comment by leonardder** [comment]
As for NVDA, I think that enforcing all punctuation within an container with role code will be considered too prescribing, so it will be optional. For what it's worth, I'd disable it as I use braille if I really want to see punctuation.

**Comment by joanmarie** [comment]
@MarcoZehe Good question. As a reminder: I am not an author/web developer, so my ideas need sanity checking. :smile: 

That said.... I had been thinking the editor would be generic element (e.g. `div` or `span`) with`contenteditable` and `role='code'`. But maybe that won't work for VSCode -- and there's no rule that says authors can't put the `code` role on an ancestor. So silly me for not including that possibility in Orca. I'll update Orca to handle that possibility. Thanks!

And agreed regarding this having nothing to do with the `application` role on the root of VSCode. We of course need that so that we treat the entire thing as a web application which should be interacted with (by default) in focus mode.

**Comment by isidorn** [comment]
For reference: VS Code editor has a hidden `textArea` Element which we fill in with content only for accessibility purpose.
That textArea we can assign any `role` we want. Here's a code pointer in case you want to experiment with it, since it is a trivial change https://github.com/microsoft/vscode/blob/51c5f904990a651cc859014971f29ecbb214ed84/src/vs/editor/browser/controller/textAreaHandler.ts#L127

**Comment by MarcoZehe** [comment]
I thought about this some more, and it appears that what you suggest is not the right way. The contentEditable div  right now has role "textbox" and aria-multiline="true" so ATs recognize it for what it is. If you put "code" on that, all the semantic gets lost. The HTML `<code>` element is an inline element, used like this:
`data:text/html,<p>The phrase <code>let i = 0;</code> is JavaScript, but has its roots in BASIC.</p>`
So if properly implemented, screen readers would read "let i equals 0" even though the equals sign might be suppressed in other contexts.
So where the role "code" might be used is on the individual lines of code inside the contentEditable div.

**Comment by MarcoZehe** [comment]
The problem would be the same for a textarea, overriding this with something that maps to a generic text frame, like a `<span>` element, would majorly break accessibility for the text input/code editor.

**Comment by joanmarie** [comment]
@MarcoZehe: What about leaving the element used for the code editor itself as-is, but giving it a parent `<div role='code'>`?

**Comment by MarcoZehe** [comment]
I think this might work. We'll have to try and possibly iterate over this.

**Comment by isidorn** [comment]
I have pushed a change that we now use role `code` for the HTML element that containes the editor.
Please try it out and see if this helps so we know if we should keep this change.

Please note that my approach is not perfect: I add this role on each editor instance, and for example an editor instance can also be markdown readonly for which the role might not be so fitting. 
Though I think this is a good start so you can try it out. Let me know how it goes.

**Comment by joanmarie** [comment]
Suh-weet! I had to make one more tweak in Orca, but Orca master is doing the right thing for me.

@isidorn: If memory serves me, you are using Orca's default punctuation level (most). What you should find with Orca master is that Orca now reads all the punctuation inside the code editor.

@jvesouza: If you set your punctuation level for VSCode to most or some, you should find that punctuation in documents, in VSCode's live region messages, the status bar, etc. is less chatty. But you hear everything verbalized automatically in the editor.

I think this is something that NVDA, et al. can start taking advantage of without anything breaking because the role was applied to an ancestor as discussed here. In other words, an interested screen reader has to go looking for the ancestor.

:crossed_fingers: 

Thanks again @isidorn!

**Comment by leonardder** [comment]
> I have pushed a change that we now use role `code` for the HTML element that containes the editor.

What HTML element is that? Is it the div with the monaco-editor class? 
I don't seem to be able to find the code role on that one.

**Comment by isidorn** [comment]
@joanmarie ok I am glad this worked. However a proper solution would be that we put it on the monaco-editor instance - because that actually means that we have a code editor. And it was also work in standalone monaco editor. Let me check with my collegue if he agrees and then I will move where we set the role.

@leonardder it is one div above it, the one with the `monaco-instance` class. However we would like to move it to the monaco-editor class as I just stated.

**Comment by MarcoZehe** [comment]
I just checked, and that should be fine @isidorn . It has no other role set, so setting it there instead of its parent should be just fine.

**Comment by isidorn** [comment]
@marcozehe thanks for checking, I also checked with @alexdima and he approved the change.
So I will just double check that nothing gets broken on windows and macOS and push it.

**Comment by isidorn** [comment]
I double checked and all seems good on Windows and macOS so I have pushed the change.
It would be great if somebody verifies on linux from Fridays VS Code insiders that punctionation gets nicely read so I add the verified label here. Thanks!

**Comment by jvesouza** [comment]
I believe I have encountered a small problem, perhaps related to the orca.
When I use the arrows to navigate the content the punctuation is read correctly. However, if I select a line, not all punctuation are read.

To reproduce try the following steps:
1. Create an empty file.
2. include the following line keeping the quotations, and press the enter key:
"a.b.c@,$#"
3. Use up and down to navigate in the file.
Orca reads the line including the punctuation.
4. Select the line using home+shift.
Orca announces what has been selected but some characters are not read.

**Comment by joanmarie** [comment]
@jvesouza: Should hopefully be fixed in Orca master.

**Comment by jvesouza** [comment]
> @jvesouza: Should hopefully be fixed in Orca master.

This is confirmed, thanks.

**Comment by isidorn** [comment]
Thanks for trying this out and for providing feedback. Seem to work fine, thus adding verified label.

**Comment by jvesouza** [comment]
@joanmarie I believe I have encountered yet another small problem. When I use the command where I am operation the current line is read without punctuation. Whether or not the line is selected.

**Comment by leonardder** [comment]
I filed https://github.com/nvaccess/nvda/issues/11033

'Honestly, I'm a bit conservative on this, and suggested that if NVDA does anything with this role, it should refrain from making this default behaviour until this role is in a released ARIA spec.

**Comment by joanmarie** [comment]
@jvesouza: The whereAmI punctuation verbalization should hopefully be fixed in Orca master.

**Comment by jvesouza** [comment]
@joanmarie It's great. Thanks.

**Comment by jvesouza** [comment]
@isidorn  @joanmarie  I believe I have encountered a problem with this feature.
My java code has the following line:
String atr = atrs.nextElement()

This line of code should end with a semicolon, but I deliberately omitted it to cause a syntax error in my code.

When I focus on problem view and scroll  in the list of erros I find the following message:
Syntax error, insert ";" to complete BlockStatements

The problem is that the orca doesn't read the ";" present in the error message, which makes it very difficult to understand.

**Comment by joanmarie** [comment]
@isidorn: Looks like syntax errors probably should also be contained in the ARIA `code` role.

Thoughts?

**Comment by isidorn** [comment]
@joanmarie looking at the `code` role [here](https://w3c.github.io/aria/#code) it should be used whenever a fragment of computer code is displayed.
So imho it makes sense to add this to the Problems view but also to the Search view since we also show code snippets there.
@joanmarie should the code role be on the container, like the `markers-panel-container` or what makes more sense to me on the exact elements that contain code like `marker-message` (which is contained in the role `treeitem`).
To put it closer to the actual code makes sense to me.
Once we decide where exactly to put the role I can do the same thing for search on the `match` class.

fyi @roblourens @sandy081

**Comment by joanmarie** [comment]
> @joanmarie should the code role be on the container, like the `markers-panel-container` or what makes more sense to me on the exact elements that contain code like `marker-message` (which is contained in the role `treeitem`).

If you were to replace `treeitem` with `code`, then screen readers wouldn't know that the thing is a `treeitem`. It might also break user agent calculation of properties like `posinset` and `setsize`.

It looks like `treeitem` doesn't have children-presentational set to true in the ARIA spec. So it potentially could go on a child of the `treeitem`. (That probably would not JustWork(tm) in Orca because Orca currently does not treat `treeitems` as things to dive down into. Though I could see about adjusting that.)

If you were to put it on an ancestor of the `tree`, I believe it would JustWork.

But others should chime in here. e.g. @MarcoZehe and @leonardder (even if he is conservative on this matter). :slightly_smiling_face:

**Comment by isidorn** [comment]
@joanmarie thanks for feedback, let's wait for other opinions. We would not replace the `treeitem` role, that would not make sense. So either a child of the `treeitem` which I prefer or one of the ancestors.

**Comment by MarcoZehe** [comment]
As @joanmarie says, putting it on an ancestor would just work. Likewise, it would only require screen readers to put in one heuristic, not several. If suddenly several controls which didn't have children before, started to have children, like tree items, that would hugely complicate things in general, but for getting the code role adopted specifically.

**Comment by sandy081** [comment]
@isidorn Problems do not show code always and also does not show code only. It includes a descriptive message always.  So if it is ok to add `code` role even if the message includes non code?

**Comment by isidorn** [comment]
@sandy081 good point, I thought about that and I think it is fine. It just means there might be code.
Similar to how the textEditor might contain non code in comments, but there is a good chance that there is code. So screen reader reads all the punctuation characters. And there is also a very good chance that there is code in problems view thus we could set the role. Also for search view.

**Comment by jvesouza** [comment]
@isidorn  Another place that will also need attention is the one that shows the differences when we are in the working tree compare  and press the f7 key. The punctuation is not read correctly by orca.

**Comment by isidorn** [comment]
@jvesouza makes sense. I have pushed 3dcbfe2b70 for this

**Comment by jvesouza** [comment]
@isidorn  It looks like it hasn't been fixed.
When reviewing the differences I have the following line:

// linha no inicio.

When the punctuation in orca is set to all a '-' is read in the begin of the line read by orca.
If the punctuation is set to some or most the '-' is not read.
There are other lines on which the punctuation  is not read either.
I can try to elaborate better if necessary.

**Comment by isidorn** [comment]
@jvesouza thanks for letting us know.
@joanmarie VS Code nicely sets the `code` role on the parent container. I am not sure why Orca is not recognising this.

Steps:
1. Have a repository under git control, have a change in a file
2. Open Git Viewlet (ctrl + shift + g)
3. Click on the file that is changed
4. Focus in the diff view (right hand side) press `F7`. You are now in the Review Mode and orca should detect `code` role on the parent.

**Comment by jvesouza** [comment]
@isidorn  @joanmarie  I am afraid I have found yet another place where the rule would have to be used, if possible. This is the file explorer.
I encountered the following situation while exploring a new project that I must work on:
* The project has a folder called config
* The project has a folder called config---
* The project has a folder called config--local

With the orca punctuation set to most or some, the orca does not read the - present in the folder names, which led me to explore the wrong folder for some time. The solution was to change the punctuation for all on orca,.

**Comment by isidorn** [comment]
@jvesouza thanks for feedback. However that part of vscode is not that logical to have the role `code` since it is not code we render there after all, but just a list of file names. I am not sure if there is any other way to notify Orca to read exactly what is written appart from using the role `code`.

**Comment by jvesouza** [comment]
@isidorn I understand perfectly. I just reported it because since I will have to keep the punctuation as all on the orca, this feature may not be of much help.

**Comment by joanmarie** [comment]
@isidorn. Confirmed. Investigating. Thanks!

**Comment by joanmarie** [comment]
@jvesouza and @isidorn: I believe I've fixed the issue for the diff viewer.

As for the filename. At least in the case of the[ `code` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element), it can apply to file names. The ARIA `code` role is there in part to achieve parity with HTML, so using it for filenames doesn't seem inconsistent with its purpose.

Related aside: I did a quick test with the `code` element and without any other attributes causing it to be included in the accessibility tree, it's getting pruned by Chromium presumably on account of being treated like a formatted span. :(

**Comment by isidorn** [comment]
@jvesouza thanks for fixing it for the diff viewer.
Aha I see that the `.code` could also be a filename. So might make sense to put that role there as well. 

@joanmarie not sure how you experimented, but you could add the following code snippet [here](https://github.com/microsoft/vscode/blob/aa0f90749fc5268eed6e0746400775733a69961e/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L266)

That way the role `code` will be set on the appropriate file element and in theroy it should work.

```
getRole(): string {
		return 'code';
	}
```

**Comment by jvesouza** [comment]
@joanmarie  @isidorn  The fix is confirmed, great!
Thanks.

**Comment by joanmarie** [comment]
@isidorn

> ```
> getRole(): string {
> 		return 'code';
> 	}
> ```

Assuming I understood you correctly, that causes the treeitems to no longer have the treeitem role. We don't want to lose that role. In addition, it impacts the files explorer, but not the open editors which also seems to contain file names whose punctuation we'd want verbalized. Could the code role be put on the ancestor split-view-container?

**Comment by isidorn** [comment]
@joanmarie you are correct that would cause the element to lose the `treeitem` role which is not what we want.

I think it makes sense to set the `role: code` on the split view. However before we make any decisions there I would like to think in what parts of our UI it does not make sense to have the `role: code`.
I believe only in user messages, so dialogs, notifications, menus, extensions list
Every other part of our UI we can show code or filenames and thus the role `code` is fitting.

@joanmarie so my question is does it make sense to just set the role: code somewhere top level and have a special role to cancel this out in these special places. Let me know what you think

also fyi @joaomoreno for split view and list / tree. Also role: code should be used so screen reader explicitly reads everything including punctuations.

**Comment by joanmarie** [comment]
> @joanmarie so my question is does it make sense to just set the role: code somewhere top level and have a special role to cancel this out in these special places. Let me know what you think

Good question.... On the one hand, that would presumably be far easier than adding the role in every last place it seems to belong. On the other hand, I don't believe there's any such role in ARIA that says "cancel the `code` role out." So that would be an undocumented -- and possibly unexpected by other web app developers -- "feature" of the screen readers.

For instance if Orca were to stop ascending the accessibility tree looking for the `code` role for a menu, what if some other web app developer has a menu which contains recently-opened files and puts the `code` role on an ancestor of that menu thinking that will cause punctuation to be read? That Orca fails to read the punctuation might seem like a bug. :woman_shrugging:

**Comment by isidorn** [comment]
@joanmarie thanks for clarification. So I have just opened this issue where we can list all the places we should add the code role. I am not such a big fan of this, so I will not immedatly do this change, but wait for more user feedback.
https://github.com/microsoft/vscode/issues/97014
