### ISSUE TITLE
VSCode adding /d and /c arguments to task command on execution?

### ISSUE THREAD

**Issue by roozmahdavian** [microsoft/vscode#93437]
I've configured the latest release of VSCode for SSH remote development from a local macOS machine to a remote Windows 10 machine. A task is configured to build an example C++ program:

```
{
    "version": "2.0.0",
    "tasks": [
      {
        "type": "shell",
        "label": "gcc",
        "command": "g++",
        "args": [
          "-g", 
          "${file}", 
          "-o", "${fileDirname}\\build\\${fileBasenameNoExtension}.exe"
        ],
        "problemMatcher": ["$gcc"],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
```

For whatever reason, executing this task in *any* shell other than cmd.exe causes "/d /c" to be prefixed to the command, which obviously breaks the build in that shell. Why is this happening? How do I disable it? I haven't touched any of the default VSCode settings and I haven't modified cpp_properties.json, and I can't find any other reports of this behavior.

`> Executing task: g++ -g c:\Users\home\dev\helloworld.cpp -o c:\Users\ home\dev\build\helloworld.exe <

/d : The term '/d' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ /d /c g++ -g c:\Users\home\dev\helloworld.cpp -o c:\Users\home ...
+ ~~
    + CategoryInfo          : ObjectNotFound: (/d:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by alexr00** [comment]
I think that not-Windows local to remote Windows probably doesn't work very well for tasks. You can probably work around this by setting `"options": {"shell": {"executable": "powershell.exe"}}` or by explicitly setting `"options": {"shell": {"args": ["-Command"]}}` since that's the correct args for powershell.

**Comment by LK4D4** [comment]
I encountered a similar problem with tasks today with recent VSCode. I do not use remote windows and develop Rust locally using nushell as shell.
Here is my task:
```
    {
      "type": "cargo",
      "subcommand": "run",
      "problemMatcher": ["$rustc"],
      "label": "Rust: cargo run - games",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "options": { "shell": { "args": [] } }
    }
```
And here is what I tried in settings:
```
  "terminal.integrated.shell.windows": "C:\\Users\\lk4d4\\.cargo\\bin\\nu.exe",
  "terminal.integrated.automationShell.windows": "C:\\Users\\lk4d4\\.cargo\\bin\\nu.exe",
  "terminal.integrated.shellArgs.windows": []
```
Error is:
```
Error: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
The terminal process "C:\Users\lk4d4\.cargo\bin\nu.exe /d /c cargo run" terminated with exit code: 1.
```
I have no idea what happened, it used to work perfectly until today when I restarted VSCode.

**Comment by alexr00** [comment]
@LK4D4 this issue is about tasks when running VS Code with a Windows remote. Please open another issue if you're seeing some other bad behavior.

**Comment by danielzfranklin** [comment]
Since I was confused by the workaround I thought I'd post a clarification. You set "options" on the task. For example:

```json
                     {
			"label": "My Task",
			"type": "shell",
			"command": "echo Hello",
			"problemMatcher": [],
			"options": {
				"shell": {
					"executable": "powershell.exe"
				}
			}
```

This successfully works around the issue for me as well.

**Comment by benjaminsuch** [comment]
I got the error in one of my NextJS projects, when I use `yarn dev`. Turns out (I use Windows), that I used the wrong node version. My project was using version 12 and nvm was using 10. Switching to 12 solved the issue.

It's not related to VSCode tasks, but I just wanted to add my two cents here, in case someone has the same issue.

**Comment by JacksonKearl** [comment]
Can any of the involved here confirm that this is now working as expected?

**Comment by meganrogge** [comment]
verifying this via code review and bc there have been no more reports
