### ISSUE TITLE
Can't use online.visualstudio.com (Version mismatch)

### ISSUE THREAD

**Issue by rasulkireev** [microsoft/vscode#93439]
Suddenly out of nowhere, VS Code Online stopped working.

Existing tickets did not help me to solve the issue.

This is the error code:
> Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)

Any suggestions? Thanks in advance.

**Comment by mjbvz** [comment]
Please file this issue against VS online: https://github.com/MicrosoftDocs/vsonline/issues/new
