### ISSUE TITLE
Detect indentation doesn't work on load

### ISSUE THREAD

**Issue by amweiss** [microsoft/vscode#93434]
Issue Type: <b>Bug</b>

When I open files, the indentation detection doesn't run. If I then select it from the command palette, it runs correctly.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|32.00GB (1.64GB free)|
|Process Argv|-psn_0_573580|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.15.0
jenkins-pipeline-linter-connector|jan|1.2.0
plantuml|jeb|2.13.6
docomment|k--|0.1.8
chat|kar|0.33.0
rainbow-csv|mec|1.6.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.15
vscode-edge-devtools|ms-|1.0.7
vscode-kubernetes-tools|ms-|1.1.0
python|ms-|2020.3.69010
sarif-viewer|MS-|2.14.0
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.1
remote-ssh-edit|ms-|0.50.1
remote-wsl|ms-|0.42.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.8
Go|ms-|0.13.1
mono-debug|ms-|0.15.8
powershell|ms-|2020.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1783
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
vetur|oct|0.24.0
quicktype|qui|12.0.46
java|red|0.58.0
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.6
vscode-maven|vsc|0.21.2
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by alexdima** [comment]
@amweiss If you use the EditorConfig, then that extension defines the indentation settings of VS Code. Please uninstall the extension if you don't need it / use it.
