### ISSUE TITLE
`editor.action.smartSelect.shrink` not working properly with PHP files

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#93430]
#### VSCode Version / OS Version:
```
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

### HTML code in HTML file (this is OK)
First selects current element, then all elements between the tags, and then together with the tag 

![html](https://user-images.githubusercontent.com/30685349/77578851-941b5800-6ed9-11ea-88d3-2c075104ad6b.gif)

### HTML code in PHP file (this is WRONG):
First selects the current element and then **immediately select everything together with the tag**.
With current behavior, this option is **completely useless because you can't select everything between the tags**

![php](https://user-images.githubusercontent.com/30685349/77578856-967db200-6ed9-11ea-92c5-6ed3805467b1.gif)

#### Does this issue occur when all extensions are disabled?:
Yes

#### Additional information:
`editor.emmet.action.balanceOut` it's not a solution because this not working with PHP files too (#93413)

**Comment by jrieken** [comment]
VS Code only provides the framework for smart select and a simple default implementation. Extensions have API to provide AST-based data - so this is either an issue with the extension that you are using or the lack of an extension

**Comment by kanlukasz** [comment]
`Caused-by-extension` ??
I tested it on a fresh installation without any additional extensions....

**Comment by jrieken** [comment]
>  so this is either an issue with the extension that you are using or the lack of an extension
