### ISSUE TITLE
Segmentation fault after update to ver 1.44

### ISSUE THREAD

**Issue by rADikal8e7** [microsoft/vscode#93432]
Issue Type: <b>Bug</b>

After update to ver 1.44 the remote server fails to start with the following error log.

```
/.vscode-server-insiders/bin/fc14315c37f3017af937270532ae2adfbdb6b45f/server.sh: line 12: 53557 Segmentation fault      "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"
> <<< End of server log
> c64395281831##32##
```

**Steps to reproduce:**

1. Let the vs code insiders auto update to ver 1.44
2. Connect to remote server using the remote-ssh extension
3. This only seems to affect some random machines since i am able to connect to other remote servers with the same vs code version

VS Code version: Code - Insiders 1.44.0-insider (fc14315c37f3017af937270532ae2adfbdb6b45f, 2020-03-25T10:51:12.912Z)
OS version: Darwin x64 19.3.0
Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start
</details>Extensions: none

**Comment by roblourens** [comment]
Can you try running the command "Kill VS Code Server on Host" so the the remote server will get reinstalled, then try connecting again and check whether you still see it?

**Comment by rADikal8e7** [comment]
@roblourens Yep that fixed it. I suspect this is due to a corrupt download/install on the home directory in the remote end.It didnt have enough disk space so vs code complained in the beginning of an earlier install. So i cleared up some space and the install went through. Tried remote connect and kept hitting this issue. once the "Kill vs code server on host" was issued to the remote host it fixed itself.
Apologies for the false negative and thanks for your help. I am going to close this.

```
[15:45:17.952] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/868382/vscode-ssh-auth-sock-850045900"}
[15:45:17.966] ------

[15:45:18.018] [Forwarding server 51423] Got connection 1
[15:45:18.019] [Forwarding server 51423] Got connection 2
[15:45:20.264] "Update SSH_AUTH_SOCK" terminal command done
```
