### ISSUE TITLE
Let openTextDocument create an untitled file with a specific file extension 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#93441]
## Problem
Custom editors support untitled resources. However it is currently not easy to open these untitled resources with our existing APIs because the untitled resources need to have a specific file extension.  Here's what I have to do today:

```ts
// Create untitled file
const newFileUri = vscode.Uri.file(path.join(vscode.workspace?.rootPath!, 'newFile.cscratch')).with({ scheme: 'untitled' });
await vscode.workspace.openTextDocument(newFileUri);

// Fill in initial content
const edit = new vscode.WorkspaceEdit();
edit.insert(newFileUri, new vscode.Position(0, 0), "{}");
await vscode.workspace.applyEdit(edit);

// Actually show the editor
vscode.commands.executeCommand('vscode.open', newFileUri);
```

This code works but is complex and fragile. For example, it breaks if a file called `newFile.csratch` already exists in the workspace

## Proposal
In the version of `openTextDocument` [that support untitled files](https://github.com/microsoft/vscode/blob/d778f85cd5f23391cf94fa0965ada594c68e1fc5/src/vs/vscode.d.ts#L8785), add a  new optional parameter for the file extension:

```ts
export function openTextDocument(options?: { language?: string; content?: string; fileExtension?: string }): Thenable<TextDocument>;
```

This would be used when creating the new file name so that custom editors can correctly enable themselves for it

**Comment by bpasero** [comment]
@mjbvz currently the only way that an untitled file allows to configure the file extension to use is either by:
* providing the full associated path (as you already found out)
* setting a language mode from which we then offer the extension

As such, this change also needs to include a way for untitled files to configure a file extension. And I would think that we should then also determine the language mode from such extension if it is not otherwise provided.

I can review a PR, I cannot work on this timewise though.

**Comment by jrieken** [comment]
@mjbvz Did you try [`setTextDocumentLanguage`](https://github.com/microsoft/vscode/blob/d778f85cd5f23391cf94fa0965ada594c68e1fc5/src/vs/vscode.d.ts#L9034)? That should work with untitled documents...

**Comment by mjbvz** [comment]
Custom editors are enabled/disabled based on file names instead of language

**Comment by bpasero** [comment]
@mjbvz isn't it weird though to call `openTextDocument` and get a non-text-based custom editor potentially?

**Comment by mjbvz** [comment]
@bpasero `openTextDocument` would be used for `CustomTextEditor` since they are also based on `TextDocument`

This does bring up to how to handle custom binary editors however since they do not have a `TextDocument`. Some possible options on how to open an untitled `CustomEditor`:

- Leave this up to extensions. They would need to make sure they create a unique untitled file each time

- Add an api that creates a unique uri for an untitled files (with a file extension)

**Comment by jrieken** [comment]
> Custom editors are enabled/disabled based on file names instead of language

You should be able to use the overload that takes an URI then, this: https://github.com/microsoft/vscode/blob/d778f85cd5f23391cf94fa0965ada594c68e1fc5/src/vs/vscode.d.ts#L8748-L8766

According to the doc, you call it like so: `openTextDocument(vscode.Uri.parse('untitled:/foo/bazz.json'))` and I would assume that it creates a JSON file

**Comment by bpasero** [comment]
Passing in `vscode.Uri.parse('untitled:/foo/bazz.json')` works fine but note that this assumes you want to save the file at `/foo/bazz.json`, that is, you will not be asked to provide a path when saving, it will just go there. 

This maps to the concept of "associated file path" for untitled, e.g. starting `code <some file that does not exist>` from the command line.

**Comment by jrieken** [comment]
Slowly understanding what this is about... The proposal has potential for conflict, e.g what should win when language and extension are present. What has come up often, and that might be helpful for this, is to have utilities that map from an extension to a language id (and maybe also the other way around).

**Comment by kieferrm** [comment]
@mjbvz @eamodio is looking into adding a view type parameter `vscode.open`. Does that suffice?

**Comment by DonJayamanne** [comment]
@rebornix we have a similar situation in Notebooks.
Today we need the ability to create untitled notebooks with some default content.

**Our solution:**
* Generate a name for the untitled file as follows 
```typescript
const fileName = 'untitled-1.ipynb';
const newUri = Uri.file(fileName).with({ scheme: 'untitled', path: fileName });
```
* Next, we invoke openWith as follows:
```typescript
commands.executeCommands('vscode.openWith', newUri, viewType);
```
* At this point, VS Code invokes our `NotebookContentProvider.openNotebook`, passing in the Uri we generated earlier for untitled file.
* Now we return the contents of this new untitled file to VSC.

Also, I'm not using the new command `workbench.action.files.newUntitledFile` for the following two reasons:
* We cannot pass default content
* Also the file extension is missing and at this point, there's no icon on the editor that's associated with the langauage (e.g. *.ipynb).

Please note, this isn't a blocker for us, I'm happy with our current solution, however @mjbvz solution does seem better if we could do the same for Notebooks.

**Comment by jrieken** [comment]
Adding @bpasero as the owner of untitled land

**Comment by bpasero** [comment]
@mjbvz this issue seems to get snow plowed for a while and I do not see it on the plan. My previous comment still holds true:

> I can review a PR, I cannot work on this in April though given sandbox duties.

Let me know if you want to open a PR for me to review, otherwise I suggest to move this to Backlog.

**Comment by bpasero** [comment]
Thinking more about this, I feel having this on `openTextDocument` is actually the wrong layer, because you want to control which editor to open for the document, but nothing about the text document itself changes.

I would enrich the options you can pass into `vscode.open` to allow to specify the identifier of an editor to use, i.e. somewhat exposing the `overrideId` option to extensions when opening editors.

**Comment by mjbvz** [comment]
This issue is now outdated. Instead, we now allow extension to the contribute to the `New File...` menu to create a file of a specific type
