### ISSUE TITLE
VS Code Mode | Different Modes with specific extensions

### ISSUE THREAD

**Issue by lflucasferreira** [microsoft/vscode#93452]
I believe there should be an option when starting the IDE where the user could choose his mode needed. The mode is like the preferences for that time opening. I mean, I set some modes like 'Python Environment', 'Ruby Environment, 'JavaScript Environment', and I could set specific extensions to each mode. 

This way I do not need to load all extensions (I have a bunch) when starting the app.

I hope to be clear about this request. Thank you in advance.

**Comment by sandy081** [comment]
There is already a duplicate of this extension.

**Comment by lflucasferreira** [comment]
> There is already a duplicate of this issue

What is the issue id number? I was looking through and I didn't see any.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/57548
