### ISSUE TITLE
Format Selection doesn't work

### ISSUE THREAD

**Issue by maxiwer** [microsoft/vscode#93459]
Issue Type: <b>Bug</b>

Format Selection (Ctrl + K Ctrl + F) formats all document.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 6.2.9200

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.0
vscode-eslint|dba|2.1.1
es7-react-js-snippets|dsz|2.7.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
vscode-angular2-emmet|jak|2.0.3
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-edge|msj|1.0.14
vscode-react-native|msj|0.14.2
angular2-inline|nat|0.0.17
angular-console|nrw|11.1.3
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|1.4.6
sass-indented|syl|1.8.0
vscodeintellicode|Vis|1.2.6

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Which language is this for?

**Comment by maxiwer** [comment]
> 
> 
> Which language is this for?

JavaScript/TypeScript.

**Comment by mjbvz** [comment]
Just tested. Our built-in JS/TS formatter handle format selection just fine so I suspect this is caused by one of your extensions, most likely prettier
