### ISSUE TITLE
The trigger character '_' does not work for a CompletionProvider

### ISSUE THREAD

**Issue by chelsealopentinum** [microsoft/vscode#93458]
- VSCode Version: 1.43.2
- OS Version: macOs Mojave 10.14.5

Register a CompletionProvider with underline (_) as a trigger character. 
The dash characters successfully trigger my completion provider, but not underline. 
Case here:
```
vscode.languages.registerCompletionItemProvider(
  'plaintext', myCompletionItemProvider, '_', '-'
)
```

**Comment by jrieken** [comment]
Using `_` works for me. What you likely running into is that `_` is a default word-character. That means suggestions that start with an underscore (`_`) are shown.

**Comment by jrieken** [comment]
You can tweak that by using the `range` property of the returned completion items, by using a different word definition, or by using the `filterText` property

**Comment by chelsealopentinum** [comment]
> Using `_` works for me. What you likely running into is that `_` is a default word-character. That means suggestions that start with an underscore (`_`) are shown.

@jrieken 
Thanks for your suggestion. I still can not use `_` to be a trigger character, but after I change the `filterText` and `range` property then it is work.
