### ISSUE TITLE
Some indication that search has wrapped around to the beggining of the file and/or beginning of the search

### ISSUE THREAD

**Issue by angusgraham** [microsoft/vscode#93454]
I often find myself searching for a string through very large text files.
When the search hits the end of the document, it wraps around to the beginning.
When there are no more results, the search returns to the first find and keeps going.
There's no super-obvious indication that either of these has happened - so I find myself having to keep an eye on the scrollbar and memorize the approximate location where the search started so I can know when I've probably passed that point again.
Visual Studio adds a message to status bar when wrapping to the start of the file.
By default it also has pretty good behaviour when the search is complete:
It plays the generic attention bong sound and changes the status bar to "Find reached the starting point of the search" and leaves the selection on the last found string. Thus it's quite obvious on that press of F3 when the selection doesn't change that the search is complete.
Pressing F3 again will move to the original selection and start searching again.
A lot of (most?) editors do something similar.

**Comment by santiagofavrin** [comment]
Sublime text has the option to turn wrap off. So it stays at the last result if you keep pressing enter. Something like this would be awesome.
