### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9345]
Feature request: Ability to duplicate file

1. Right click file in Explorer
2. New option: "Duplicate" 

which would open mini popup (or some other way) that I could provide new name for duplicated file

![image](https://cloud.githubusercontent.com/assets/1723815/16876961/136cf0e8-4a74-11e6-9650-674048126b2b.png)

**Comment by weinand** [comment]
@wallverb you can copy and then paste a file in the Explorer to create a duplicate

**Comment by wallverb** [comment]
Right, I switched from Atom to VSCode and just posted it as something I used there and found it useful.

If you think duplicate is not worth implementing, maybe we could improve copy and paste experience, because when you copy file `test.ts` and paste it - it will create `test.1.ts` but will go to content of the file - and most of the time - you want to set target name of the duplicate.

Like if it could go to this state then it would be very easy to set target name and hit Enter to accept:

![image](https://cloud.githubusercontent.com/assets/1723815/16879411/7a7d1ccc-4a7e-11e6-93c3-04555202ec10.png)

**Comment by mrmlnc** [comment]
I can create a plugin 😸

**Comment by mrmlnc** [comment]
@waderyan, @richarddavenport, try this plugin — [Duplicate file](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-duplicate).

If you find bugs, please create a PR or Issue :muscle:.

**Comment by bpasero** [comment]
Closing in favour of extensions 👍
