### ISSUE TITLE
Always show the info：An error occurred while trying to create a file in the destionation directory: Access is denied.

### ISSUE THREAD

**Issue by AJLu-AMAT** [microsoft/vscode#93461]
- VSCode Version: 1.43.0 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

Always show the message information.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, I alreadly uninstall all extensions.

![Untitled](https://user-images.githubusercontent.com/53816485/77617354-e3f82e80-6f6e-11ea-9099-53139c42a9b0.png)

**Comment by AJLu-AMAT** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * ['Access is Denied' Message When Compile C++  (#89972)](https://www.github.com/microsoft/vscode/issues/89972)

Hi, I have uninstalled all extensions. But still show this message

**Comment by mjbvz** [comment]
What triggers this? Are you saving a file?
