### ISSUE TITLE
VoiceOver reports all text in the editor when move the caret to the last line which is blank

### ISSUE THREAD

**Issue by yxycode17** [microsoft/vscode#93468]
Issue Type: <b>Bug</b>

1. Open vscode with VoiceOver enabled.
2. Create a new file with cmd+N
3. In the text editor enter some text but leave the last line blank.
4. Now use down arrow key to move the caret to the last line.
5. Instead of reporting "new line" which indicates a blank line, VoiceOver speaks out all text in the editor.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.84GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.69010
Go|ms-|0.13.1
jsbox|Yin|0.0.19

</details>

**Comment by isidorn** [comment]
Agree, and this is a painful issue.
Howeer we are already aware of this and both have opened issues on the Chrome side.
This issues on the vscode side track this https://github.com/microsoft/vscode/issues/70033 and https://github.com/microsoft/vscode/issues/89231
Thus closing as duplicate

Here's a list of all our known VoiceOver issues, just FYI https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+label%3Amac
