### ISSUE TITLE
Web: theme is always wrong when I debug

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93469]
I often notice that my theme is lost when I reload and now I think I found steps to reproduce:

Steps to Reproduce:

1. run web out of sources (`./resources/server/web.sh`)
2. open it on a hello world extension
3. configure a light theme in settings
4. F5

=> 🐛 the resulting window very often has the dark theme for me, not the light one. I can reproduce quite reliably on macOS, Chrome. Debugging this it seems that [`ThemeConfiguration#colorTheme`](https://github.com/microsoft/vscode/blob/7ca1a3577815bffd6de4c3c700d97e6d53b41531/src/vs/workbench/services/themes/common/themeConfiguration.ts#L210) returns `vs-dark`, even though it should be `vs`. 

Is this maybe an issue with config caching and a missing update?

**Comment by sandy081** [comment]
@bpasero Can you please check if you can hit the breakpoint here - 

https://github.com/microsoft/vscode/blob/e385a773879b312c1b6530a52ff73f6e8f316c46/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L252

**Comment by bpasero** [comment]
@sandy081 yes I see it hit:

![image](https://user-images.githubusercontent.com/900690/77636092-dda88900-6f53-11ea-9c89-8b98a34c065f.png)

**Comment by sandy081** [comment]
Assigning to @aeschli as the configuration change is being triggered.

**Comment by bpasero** [comment]
Btw I see this often in selfhosting too when I hit F5, sometimes even my file icon theme changes to the default, even though it is configured differently.

**Comment by sandy081** [comment]
Yup I also see it while self hosting. Reloading fixed it for me always.

**Comment by aeschli** [comment]
The file icon theme issue different bug that I recently fixed.

I was able to reproduce the web issue, but only once.

**Comment by aeschli** [comment]
If you can debug this and see who is setting setColorTheme with the new theme?
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L345

**Comment by bpasero** [comment]
@aeschli good to hear you found an issue with file icons, I got the bug today, did you fix it after today's insider?

I forgot to mention what kind of settings I have to reproduce the issue with getting the dark theme when hitting F5:

```
{
    "files.autoSave": "off",
    "terminal.integrated.windowsEnableConpty": false,
    "workbench.quickOpen.closeOnFocusLost": false,
    "workbench.colorTheme": "Default Light+",
    "debug.onTaskErrors": "debugAnyway"
}
```

As for your question:

```
setColorTheme (workbenchThemeService.ts:345)
initializeColorTheme (workbenchThemeService.ts:225)
await in initializeColorTheme (async)
initialize (workbenchThemeService.ts:246)
WorkbenchThemeService (workbenchThemeService.ts:141)
_createInstance (instantiationService.ts:111)
_createServiceInstance (instantiationService.ts:210)
_createServiceInstanceWithOwner (instantiationService.ts:199)
_createAndCacheServiceInstance (instantiationService.ts:188)
_getOrCreateServiceInstance (instantiationService.ts:136)
get (instantiationService.ts:54)
(anonymous) (workbench.ts:141)
invokeFunction (instantiationService.ts:61)
startup (workbench.ts:137)
open (web.main.ts:89)
await in open (async)
main (web.main.ts:335)
create (workbench.web.api.ts:212)
(anonymous) (workbench.ts:342)
(anonymous) (workbench.ts:348)
Module._invokeFactory (loader.js:1040)
Module.complete (loader.js:1050)
ModuleManager._onModuleComplete (loader.js:1667)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._onModuleComplete (loader.js:1679)
ModuleManager._resolve (loader.js:1627)
ModuleManager.defineModule (loader.js:1278)
load (loader.js:1556)
(anonymous) (css.js:103)
BrowserCSSLoader._onLoad (css.js:45)
callback (css.js:68)
loadEventListener (css.js:34)
load (async)
BrowserCSSLoader.attachListeners (css.js:40)
BrowserCSSLoader.createLinkTag (css.js:70)
BrowserCSSLoader.load (css.js:90)
CSSPlugin.load (css.js:102)
ModuleManager._loadPluginDependency (loader.js:1561)
ModuleManager._resolve (loader.js:1610)
ModuleManager.defineModule (loader.js:1278)
ModuleManager._onLoad (loader.js:1358)
(anonymous) (loader.js:1532)
OnlyOnceScriptLoader.triggerCallback (loader.js:591)
(anonymous) (loader.js:585)
loadEventListener (loader.js:617)
load (async)
BrowserScriptLoader.attachListeners (loader.js:623)
BrowserScriptLoader.load (loader.js:630)
OnlyOnceScriptLoader.load (loader.js:585)
loadNextPath (loader.js:1527)
ModuleManager._loadModule (loader.js:1539)
ModuleManager._resolve (loader.js:1623)
ModuleManager.defineModule (loader.js:1278)
ModuleManager._onLoad (loader.js:1358)
(anonymous) (loader.js:1532)
OnlyOnceScriptLoader.triggerCallback (loader.js:591)
(anonymous) (loader.js:585)
loadEventListener (loader.js:617)
load (async)
BrowserScriptLoader.attachListeners (loader.js:623)
BrowserScriptLoader.load (loader.js:630)
OnlyOnceScriptLoader.load (loader.js:585)
loadNextPath (loader.js:1527)
ModuleManager._loadModule (loader.js:1539)
ModuleManager._resolve (loader.js:1623)
ModuleManager.defineModule (loader.js:1278)
ModuleManager._onLoad (loader.js:1358)
(anonymous) (loader.js:1532)
OnlyOnceScriptLoader.triggerCallback (loader.js:591)
(anonymous) (loader.js:585)
loadEventListener (loader.js:617)
```

![image](https://user-images.githubusercontent.com/900690/77666597-6f7abb00-6f81-11ea-82cc-d6a04e9c9c60.png)

![image](https://user-images.githubusercontent.com/900690/77666618-74d80580-6f81-11ea-90a7-15b18b63848d.png)

**Comment by bpasero** [comment]
So it looks like `this.colorThemeRegistry.findThemeBySettingsId` returns the dark theme, which I think is simply using the configuration service directly @sandy081 ?

**Comment by bpasero** [comment]
At least the settings editor knows the correct value:

![image](https://user-images.githubusercontent.com/900690/77667027-ffb90000-6f81-11ea-9f0b-f0bf18f4c052.png)

**Comment by sandy081** [comment]
This is bug in configuration loading. There is a timing issue while switching from user settings to user configuration (settings + tasks).
