### ISSUE TITLE
Auto completion takes forever to load

### ISSUE THREAD

**Issue by unluckykc** [microsoft/vscode#93471]
Issue Type: <b>Performance Issue</b>

Create a variable of a well defined object type.
Start to type the name of the variable then hit Ctrl+Space.
Same when you type '.' after the name of the variable to get object properties.
Same when you press F12 on the class of the object to ceck manually which properties it has.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    70	  1048	code main
    0	    66	  1472	   window (Issue Reporter)
    1	   218	 14604	   gpu-process
    0	    24	 14904	   utility
    0	   188	 15344	   window (● 1585145028163-AddCodesAnalytiques.ts - tsmean (Workspace) - Visual Studio Code)
    0	    24	  2756	     searchService
    0	    52	 16992	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	 13864	       C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" run typeorm:local migration:run"
    0	    28	 18108	         "C:\Program Files\nodejs\\node.exe"  "C:\Users\ykc\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" run typeorm:local migration:run
    0	     4	 17144	           C:\WINDOWS\system32\cmd.exe /d /s /c ts-node ./node_modules/typeorm/cli.js --config properties/development.ormconfig "migration:run"
   27	  1027	 10928	             electron_node bin.js cli.js 
    0	     5	 17048	     console-window-host (Windows internal process)
    0	   100	 17108	     extensionHost
    0	    23	 15228	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=17108
    0	    14	 15852	       C:\wamp64\bin\php\php7.3.5\php.exe c:\Users\ykc\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:49941 --memory-limit=4095M
    0	     5	 15928	         console-window-host (Windows internal process)
    0	    49	 17520	       electron_node tsserver.js 
   25	   856	 17544	       electron_node tsserver.js 
    0	    22	 17988	         electron_node typingsInstaller.js typesMap.js 
    0	    27	 18168	     watcherService
    0	    13	 16428	   electron-crash-reporter
    0	    62	 16724	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● 1585145028163-AddCodesAnalytiques.ts - tsmean (Workspace) - Visual Studio Code)
|    Folder (shared): 325 files
|      File types: ts(201) js(69) json(8) prettierrc(1) npmignore(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|    Folder (backend): 1436 files
|      File types: ts(690) php(155) js(127) docx(95) json(22) jpg(20) png(17)
|                  xlsx(16) txt(13) dotx(7)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1)
|                  launch.json(1)
|      Launch Configs: node
|    Folder (frontend): 1652 files
|      File types: ts(754) scss(233) html(232) css(21) png(21) json(14) svg(9)
|                  js(5) eot(5) ttf(5)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  launch.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
Angular2|joh|9.1.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-apache|mrm|1.2.0
mssql|ms-|1.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by mjbvz** [comment]
Which language is this for?

**Comment by unluckykc** [comment]
It's for TypeScript, sorry.
After several hours of VS Code being open it finally worked again, but I didn't change anything since yesterday, and it worked as soon as I opened VS Code yesterday. I just remember updating the software but it  continued to work just after I did the update.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by unluckykc** [comment]
No it works fine on the  latest VS Code insiders build with all extensions disabled. Thank you.

**Comment by mjbvz** [comment]
Thanks for testing. Please see if you can track down which extension is causing this and file an issue against them
