### ISSUE TITLE
Notebook screen cheese when changing between tabs

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93474]
* open a notebook with editor and rich content (webview based)
* open a normal text file
* switch from the text file tab back to notebook tab
* 🧀 the editors are missing, everything looks a little off, see video

[Mar-26-2020 10-53-31.mp4.zip](https://github.com/microsoft/vscode/files/4386386/Mar-26-2020.10-53-31.mp4.zip)

**Comment by rebornix** [comment]
Fixed via 8932a57a10b9c97eb0d83b5801c8cf9fe3b35a4a
