### ISSUE TITLE
Code formatter 

### ISSUE THREAD

**Issue by rockyahmed** [microsoft/vscode#93478]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rockyahmed** [comment]
when i save then code formatter long time precessing not save code and not format.

**Comment by jrieken** [comment]
In past (~3months ago) we would cancel format on save after ~800ms - that means the file would have been saved without being formatted. However, format on save is off by default, e.g users manually enable it and we have gotten feedback that we should honour user-choice and then wait for formatting to be finished. What you can do

* press cancel when the progress notification appears -> this will skip format on save for that one instance
* disable format on save globally via `"editor.formatOnSave": false` or per language e.g. for go-lang it would be this: `"[go]": { "editor.formatOnSave": false}`
