### ISSUE TITLE
Suggestion (all lists?) styles are different in notebook

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93475]
See attached screen shots: Upper is notebook, lower is editor. The styles are very different, e.g

* background color
* no hover color
* selection color

<img width="562" alt="Screenshot 2020-03-26 at 11 01 03" src="https://user-images.githubusercontent.com/1794099/77634351-16932e80-6f51-11ea-82c9-4e0df2f9bb76.png">

<img width="306" alt="Screenshot 2020-03-26 at 11 01 21" src="https://user-images.githubusercontent.com/1794099/77634382-214dc380-6f51-11ea-80a7-b3a190e3209a.png">

**Comment by jrieken** [comment]
This happens because of this: https://github.com/microsoft/vscode/blob/6852fbc0aec32b5ec9cd75e29b3d82d1ad423bd7/src/vs/workbench/contrib/notebook/browser/notebookEditor.ts#L201.

**Comment by rebornix** [comment]
The styler for list view only protects itself from leaking to list views externally, for list views internally, they are all affected by the styler.

For example, the default styler used by the ListWidget will inject following style

```js
`.monaco-list${suffix}:focus .monaco-list-row.focused { color: ${styles.listFocusForeground}; }`
```

As you can see from above, any `.monaco-list-row` inside `.monaco-list${suffix}` will inherit this rule.

IMHO the rule should be as restrict as 

```
`.monaco-list${suffix}:focus > div.monaco-scrollable-element > .monaco-list-rows > .monaco-list-row.focused { color: ${styles.listFocusForeground}; }`
```

but I'm not confident to push this change to ListWidget, I'm sure it will break tons of list view which accidentally rely this loose rule. As a workaround, I plugin our own Styler for NotebookCellList, which only applies the CSS rules on the root list.

// @joaomoreno , @roblourens
