### ISSUE TITLE
XDebug is very slow when VSCode minimized (in background)

### ISSUE THREAD

**Issue by Student414** [microsoft/vscode#93477]
- VSCode Version: 1.43.2
- OS Version: Windows 10 Enterprise 1909 build 18363.720

Steps to Reproduce:

1. Configure XDebug in normal way and debug some php files as usual.
2. Minimize VSCode and re-debug it, networking will stuck about 10 second.
3. refume VSCode, nothing is wrong.

Does this issue occur when all extensions are disabled?: Yes/No
I don't know, sorry.

**Comment by mjbvz** [comment]
Please start by filing this against the extension that added XDebug support
