### ISSUE TITLE
Label formatter and suffixes 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93489]
We have the `ILabelService` and that has `registerFormatter` which allows to contribute custom formatting rules. This works fine (and is mostly used) with prefixed, e.g we have `[foo-remote] /some/path`. However, when you want to append something things get hairy. E.g. for notebooks we want to appending something but only to the file name. For instance the URL `vscode-notebook://some/folder/notebook.file?cell=1` should be rendered as `notebook.file, cell1` but the containing folder should *not* be rendered as ` /some/folder, cell1`. Today, exactly that happens 👇 

<img width="569" alt="Screenshot 2020-03-26 at 12 40 02" src="https://user-images.githubusercontent.com/1794099/77652755-0f7b1900-6f6f-11ea-9f95-a9d53efc123a.png">

There are two problems

* label formatting cannot express that only applies to the filename (and don't know how that would work...)
* URIs are split before formatting, e.g `ResourceLabelWidget` (and likely others) only formats the [`dirname`](https://github.com/microsoft/vscode/blob/dd0f2fecd124767ba7565190190d27045e6e9249/src/vs/workbench/browser/labels.ts#L360) of an URI, not the name itself. I think the label service should return formatted dirname, basename, fullpath instead.

**Comment by isidorn** [comment]
I agree this is an issue and the label service was done in a way it has rules, you give it an uri and you get back a label.
As you suggest we should enrich the label service such that you give it an uri and it returns a name and a description.  So something like `getUriNameAndDescription(resource: URI): {name: string, description: string}`.

**Comment by bpasero** [comment]
Anything actionable here?

**Comment by jrieken** [comment]
Actually not. We have discarded the label formatter approach because it wasn't usable for suffixes. It's a broader issue and need much adoption.
