### ISSUE TITLE
Terminal should use role=list

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93480]
Forked from https://github.com/microsoft/vscode/issues/93087#issuecomment-603867384

Terminal currently uses role=listitem for each line, however it does not set the role=list on the parent container. It should.
More about aria roles can be found here https://w3c.github.io/aria/#list

@Tyriar let me know if you need further help with this.

**Comment by Tyriar** [comment]
Upstream PR: https://github.com/xtermjs/xterm.js/pull/2814

**Comment by isidorn** [comment]
Thanks for fixing this!
