### ISSUE TITLE
please add a better way to force focus back to the editor

### ISSUE THREAD

**Issue by mehgcap** [microsoft/vscode#93486]
Issue Type: <b>Feature Request</b>

One problem with VSCode and screen readers is this: there seems to be no quick way to return focus to the editor after switching views.

1. Open a few files. Be sure you're in the editor for a file.
2. Press ctrl-shift-f to do a global search.
3. Try to get out of that and back to your editor. Since global find is a view, and the editor isn't a view but is always visible (I think), there's no keystroke/command to put you back in the editor.

I usually press ctrl-1, but if you use multiple groups, you have to know which group you want. Ctrl-k, e is the other option, but that puts you in a list, not straight back into the most recent editor.

It seems like there should be an easy way to get out of global search, debug, and the other views and back into the active editor. Yes, ctrl-k then e will bring up a list of editors with the most recent at the top, but you then have to press enter. Ctrl-{1-0} will work, but you have to know which group you want. The solutions I can come up with:

1. Offer a setting that allows the user to choose the behavior of ctrl-k, e. Either go to the most recent editor, or offer the list as happens now. Remapping this command and changing the setting would thus offer a single keystroke method for getting into the editor.
2. Offer a new command, and clarify the existing one so it is obvious that it will go to a list and not directly back to the editor.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.16.0-4-amd64

**Comment by bpasero** [comment]
You can do this through the command: `workbench.action.focusActiveEditorGroup`. It will pass focus to whatever editor group is active.
