### ISSUE TITLE
Output should use role=document

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93481]
Forked from #93087 (comment)

Output currently uses `role=textbox`, however it should use `role=document` due to its readonly structure
More about aria roles can be found here https://w3c.github.io/aria/#document

**Comment by sandy081** [comment]
Please let me know where can I fix this. I will be happy to do the change.

**Comment by isidorn** [comment]
I would simply in the render body on the conatiner add the attibute role=document
Code pointer https://github.com/microsoft/vscode/blob/04b2d52822edfc656d4b10ff5e6d28ea38662edc/src/vs/workbench/contrib/output/browser/outputView.ts#L89

**Comment by isidorn** [comment]
@sandy081 thanks for pushing the fix. I have checked it out and after doing some more thinking figured out that a better way to do this is to set the role directly on the editor. Thus I am doing that now.
Thanks!
