### ISSUE TITLE
Integrated Terminal - selection disappears on scroll

### ISSUE THREAD

**Issue by justinsamsky** [Microsoft/vscode#9348]
- VSCode Version: 1.3.1
- OS Version: Ubuntu 14.04 (fully updated)

Steps to Reproduce:

1. enter or output text to the integrated terminal; enough to allow scrolling
2. highlight some text
3. scroll up or down using the mouse wheel

Noticed while highlighting some database output for stare-and-compare.

**Comment by rmunn** [comment]
Still occurs on VS Code version 1.6.1 (commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e), and it's a major annoyance in my workflow. I'm using the Ionide plugin for F#, and Ionide recently switched where the F# Interactive window appears. It used to use the Output window, where scrolling works as I expect: I can hold down the mouse button, move the scroll wheel up or down, and select a bit block of text without all of it being on-screen. But now the Ionide plugin has switched to using the integrated terminal for F# Interactive -- and selecting a big block of text has become impossible. I can only select as much text as is on-screen at once. Then I have to scroll up by a page, select and copy the next page, and repeat. It's rather annoying.

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js/issues/68
