### ISSUE TITLE
Allow to move a file by adding path segments to rename box

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9349]
- VSCode Version: 1.4.0-insider
- OS Version: any

Feature request:

1. Right click + Rename or hit Enter on selected file to rename the file
2. Allow to not only change name but also to move the file, eg `test.ts` -> `../my-test.ts` would rename the file but also move it up one level

**Comment by bpasero** [comment]
That seems like a weird UI interaction. We do however have another feature request to be able to do this, possibly from quick open where you can edit the full path.

**Comment by wallverb** [comment]
@bpasero - Not sure why you think it's weird UI interaction - it's something that Atom / Sublime allows out of the box and it's really useful for power users that do not want to use their mouse to move things around.

Tried to find related feature request with 'quick open', 'move file', 'rename file' but no luck. I hope that gets implemented at some point. Thanks

**Comment by bpasero** [comment]
@wallverb while this might happen in other editors, it is not standard behaviour in file management tools on any OS I know (windows explorer, mac finder, linux).

**Comment by wallverb** [comment]
Thank you @bpasero for reconsidering. Agree that these standard tools are not geared towards power user - but old good `Total Commander` on Win and `muCommander` on Mac allows to do that. I think it would be similar to `mv` tool and node.js's `fs.rename(oldPath, newPath, callback)` which allow both to rename and move+rename file in one call. Thanks

**Comment by bpasero** [comment]
Let's move this into https://github.com/Microsoft/vscode/issues/12893
