### ISSUE TITLE
Problem with updating to newer version!

### ISSUE THREAD

**Issue by rediffusion** [microsoft/vscode#93491]
Aloha! 🙂

- VS Code is the last version.
- Windows 10 LTSB

 How to delete unwanted themes and theme icons forever? When «VS Code» updates to a newer version, everything is back! What a hack? **o_O**

**1.** Icons:
Seti (Visual Studio Code)
Simple icons

**2.** Theme:
Quiet Light
Solarized Light
Abyss
Monokai
Red
Solarized Dark

 _Kind regards!_

**Comment by JacksonKearl** [comment]
Sorry about all the bot posts. I'm working on that.

But it looks like those are all the default themes, which can be disabled but not uninstalled. Is it correct that this only affects default themese?

**Comment by rediffusion** [comment]
@JacksonKearl

Yes, it affects default themes. But thanks anyway! 😊

**Comment by sandy081** [comment]
> When «VS Code» updates to a newer version, everything is back!

They should be there always, please let me know if you had state that they were not there before? If so, how did you get into that state?

**Comment by rediffusion** [comment]
@sandy081 

 I deleted all themes which were in this folder:

> C:\Users\NIKA\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\

... after that, I updated to a newer version of 
«VS Code» and everything was back! WTF?

**Comment by sandy081** [comment]
@rediffusion I do not think you should be doing any operations in that folder. It is still not clear how you get in to this state

> How to delete unwanted themes and theme icons forever? When «VS Code» updates to a newer version, everything is back! What a hack? o_O

Did you tried to delete them manually?

**Comment by rediffusion** [comment]
> Did you tried to delete them manually?

Yes...

**Comment by sandy081** [comment]
I do not think that is expected to do and would have caused this. Please let me know why you want to delete them? And your issue is that they came back after update?

**Comment by rediffusion** [comment]
@sandy081 

 I want to delete it because I use another more coolest `Theme Extensions` from "VS Code Marketplace".
Right now I disable these extensions... After updating today to never version not shows in "Command Palette". I think it's fine now.  👍 😊
