### ISSUE TITLE
Better diff review keyboard navigation  

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93498]
Diff review is used when the changes view is opened and diffs are navigated via `F7` and `shift + F7`.

As reported by @jvesouza  It seems that I can only navigate the content using the up and down arrow. It would be interesting if we could use left and right, home and end in addition to ctrl + home and ctrl + end.

Code pointer for a potential pull request 
https://github.com/microsoft/vscode/blob/51c5f904990a651cc859014971f29ecbb214ed84/src/vs/editor/browser/widget/diffReview.ts#L137

**Comment by ChrisPapp** [comment]
I imagine that Left/Right should also move one line up/down, and home/end should jump to first/last line. But what about CRTL+Home/End?

This looks like a good first issue. Can I work on this?

**Comment by isidorn** [comment]
@ChrisPapp yes feel free to work on it. You can work with @jvesouza @mehgcap on what each keybinding should do exactly.  Once you have something create a PR and ping me on it. Thank you

**Comment by jvesouza** [comment]
@ChrisPapp @isidorn   For me the ideal is that the navigation with the keyboard was as if we were browsing in an editor.

* Up arrow: moves the cursor to the previous line.
* down arrow: moves the cursor to the next line.
* left arrow: moves the cursor to the previous character.
* right arrow: Moves the cursor to the next character.
* home: moves the cursor to begin of line.
* end: moves the cursor to the end of line.
* ctrl + home: moves the cursor to begin of diff.
* ctrl + end: moves the cursor to the end of diff.


It would be great if we could also navigate between words using ctrl + left and ctrl + right.

**Comment by isidorn** [comment]
Makes perfect sense to me to be aligned with the editor as much as possible.

**Comment by isidorn** [comment]
@ChrisPapp also note this issue in case you want to fix two https://github.com/microsoft/vscode/issues/93564

**Comment by ChrisPapp** [comment]
@isidorn 
I've been studying the code and trying to come up with a solution.
In order for this to work first of all we need to add a cursor to diffReview.

One solution, would be to add the following attribute to each dirr-review-row
`contentEditable: "true"`
to get a cursor to show, and then block the keyboard events, to make it not editable.

The second approach would be to somehow connect the cursor ViewPart of the editor to DiffReview if possible.

The third approach would be to make DiffReview extend CoreEditorWidget, and essentially make it a non-editable editor, which has some red/green rows.

Which approach (if any) do you think I should follow?

**Comment by isidorn** [comment]
@ChrisPapp thanks for looking into this. To be honest I am not sure what apporach would work best here. I suggest you try some out and whatever feels the cleanest you take and submit a PR and we can discuss from there.
