### ISSUE TITLE
Show context menu on a tab should be a command

### ISSUE THREAD

**Issue by skplunkerin** [microsoft/vscode#93497]
- **VSCode Version:** 1.43.2
- **OS Version:** macOS Catalina 10.15.3

**The issue:**

Adding a custom keybinding for the default `Shift+F10` keybinding (for command `editor.action.showContextMenu`) behaves differently for the files Explorer. Instead of working the same way as `Shift+F10`, a custom keybinding will take the focus out of the Explorer, place it into the editor, and then run the command.

**Does this issue occur when all extensions are disabled?:** Yes

**Steps to Reproduce:**

1. **How the default keybinding works:**
    1. When the text editor is focused
        - Type `Shift+F10`
        - The right-click context menu appears for that editor 👍

    2. When the file Explorer is focused
        - Type `Shift+F10`
        - The right-click context menu appears for the Explorer 👍

2. **Creating a custom keybinding (for the same command) doesn't work:** 👎 
     This is the default binding:
      ```
      {
        "key": "shift+f10",
        "command": "editor.action.showContextMenu",
        "when": "textInputFocus"
      }
      ```

    1. Create your own keybinding for the `Shift+F10` command
       - Here's a custom keybinding
          ```
          {
            "key": "shift+f1", // I've tried several different combinations
            "command": "editor.action.showContextMenu",
            "when": "textInputFocus" // I've also tried filesExplorerFocus
          }
          ```
    2. When the text editor is focused
        - Type `Shift+F1`
        - The right-click context menu appears for that editor 👍

    3. When the file Explorer is focused
        - Type `Shift+F1`
        - Nothing 👎
          _(makes sense, `textInputFocus` is false... yet the default worked? Let's try a different focus state)_

    4. If I change my custom keybinding to have `"when": "filesExplorerFocus"`
        - When the file Explorer is focused
            - Type `Shift+F1`
            - My focus is pulled out of the Explorer and placed into the editor 👎
              The context menu for the editor is opened 👎

I'm guessing something under-the-hood is happening when `filesExplorerFocus` is true, and `Shift+F10` typed (and it's not shown in the Keyboard Shortcuts?).
Why can't I create a custom keybinding for this that works the same way as the default keybinding? This seems like a bug, since every other keybinding I add a custom binding for works the same was as the default bindings.

**Comment by isidorn** [comment]
Well the `editor.action.showContextMenu` is the aciton only to trigger the context menu in the editor.

**Comment by bpasero** [comment]
Extracted the one for list to: https://github.com/microsoft/vscode/issues/93677
