### ISSUE TITLE
Can't open visual studio code

### ISSUE THREAD

**Issue by JirkaxV** [microsoft/vscode#93506]
- VSCode Version: 1.43.2
- OS Version:  **windows 10** 1909 x64

I tried to open visual studio code after a long time, and it didn't open. I tried opening it via command line with "**code**" command but nothing happened.
When I try "**code --verbose**", it gives no output.

**Comment by mjbvz** [comment]
Have you tried re-installing VS Code to see if that fixes the issue?

**Comment by JirkaxV** [comment]
> Have you tried re-installing VS Code to see if that fixes the issue?

Yes, I did. I also triedperforming

**Comment by JirkaxV** [comment]
> Have you tried re-installing VS Code to see if that fixes the issue?

Yes, I did. I also tried the system install instead of user install

**Comment by bpasero** [comment]
@JirkaxV so what happens when you type "code --verbose" does it immediately return? Can you alternatively try to run the `Code.exe` from the installation folder from the command line?

**Comment by JirkaxV** [comment]
> @JirkaxV so what happens when you type "code --verbose" does it immediately return? Can you alternatively try to run the `Code.exe` from the installation folder from the command line?

When I do `code --verbose` it doesn't give any output, but it freezes - it does not print a new line.
And when I try to run it from installation folder also nothing happends.
I noticed, that in task manager it's running in the **background**

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by JirkaxV** [comment]
No version worked, so I reinstalled winodws and now it works.
