### ISSUE TITLE
JSON Autocompletion not working

### ISSUE THREAD

**Issue by shide1989** [microsoft/vscode#93500]
- VSCode Version:
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- OS Version:
macOS Catalina 10.15.4

I create a **config.json** file
```json
{
  "api": { 
    "invokeUrl": ""
  } ,
  "cognito":{
    "REGION": "eu-west-1",
    "USER_POOL_ID": "tutu",
    "APP_CLIENT_ID": "tutu"
  }
}
```
import it in an **index.js** file using JS ES6 : `import config from './config';`

and there's no completion on it.
<img width="580" alt="Capture d’écran 2020-03-26 à 16 22 40" src="https://user-images.githubusercontent.com/7138331/77664005-047bb500-6f7e-11ea-88d8-6aade0aa295c.png">

Steps to Reproduce:

1. create a JSON file
2. import it in an index.js file

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
To properly type json imports, you need to set [`resolvejsonmodule`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---resolvejsonmodule). 

6bdf50706f4d7c1541778766a20c569c7d851f85 makes this the default for js/ts files that don't belong to any project. If your ts file is part of  project, you'll need to explicitly add `resolvejsonmodule` to your `tsconfig`

Also see https://github.com/microsoft/TypeScript/issues/24357 about requiring the `.json` extension in imports

**Comment by mjbvz** [comment]
Verification:

Create a folder with a single ts file and a json file (no tsconfig). Ensure that you can import the json file and get proper suggestions for it
