### ISSUE TITLE
New tab overwrites previous

### ISSUE THREAD

**Issue by polo7** [microsoft/vscode#93507]
Issue Type: <b>Bug</b>

I can't open few tabs, because every new tab overwrites current one tab. I have few files in current opened folder. I click on them to open files for editing, but new click opens editor in the place of the previously opened tab. But I can open file in a new tab if I drag it by mouse from left panel to tabs panel. I got this after last update.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.69010

</details>

**Comment by gjsjohnmurray** [comment]
This sounds like [Preview mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode), which is default behaviour.

**Comment by ArturoDent** [comment]
Double-click to open files not in Preview Mode.

**Comment by mjbvz** [comment]
See https://stackoverflow.com/questions/43605338/visual-studio-code-closes-my-file-when-i-search-for-new-ones/43615189#43615189

**Comment by polo7** [comment]
Thank you, that option helped me.

**Comment by polo7** [comment]
> See https://stackoverflow.com/questions/43605338/visual-studio-code-closes-my-file-when-i-search-for-new-ones/43615189#43615189

Thank you, that option helped me.
