### ISSUE TITLE
Partial JsDoc support

### ISSUE THREAD

**Issue by Legends** [microsoft/vscode#93514]
Issue Type: <b>Bug</b>

var /** HTMLInputElement */ fixedNavCb;

The above inline notation for JsDoc does not work, no intellisense in my js file.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
LinkCheckMD|bla|0.3.1
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.1
docs-article-templates|doc|0.2.7
docs-markdown|doc|0.2.60
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.44
docs-yaml|doc|0.2.4
githistory|don|0.6.3
jquerysnippets|don|0.0.1
vscode-generate-getter-setter|DSK|0.5.0
es7-react-js-snippets|dsz|2.7.0
gitlens|eam|10.2.1
tslint|eg2|1.0.44
json-tools|eri|1.0.2
prettier-vscode|esb|3.20.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
vscode-cdnjs|Jak|0.18.0
search-node-modules|jas|1.3.0
csharpextensions|jch|1.3.1
inline-types|Mar|0.3.0
code-beautifier|mic|2.3.3
csharp|ms-|1.21.15
debugger-for-chrome|msj|4.12.6
quicktype|qui|12.0.46
vscode-yaml|red|0.7.2
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.1
px-to-rem|sai|1.3.1
git-merger|sha|0.4.1
markdown-preview-enhanced|shd|0.5.2
html5-boilerplate|sid|1.0.3
addDocComments|ste|0.0.8
sass-indented|syl|1.8.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Is that valid JSdoc syntax?

**Comment by IllusionMH** [comment]
AFAIK this syntax is supported by Closure Compiler for type annotations, but not by TS

**Comment by Legends** [comment]
@IllusionMH 
It's not a TS file but ".js".  Ok, didn't know that the syntax is only supported by closure compiler.

Is it possible to declare a type once for all variables? The below syntax doesn't work:
```
/** @type {HTMLInputElement} */
var cbtoggleTheme, mobileNavCb, minifiedNavCb;
```

**Comment by IllusionMH** [comment]
> It's not a TS file but ".js". 

Both JS and TS functional are provided by TS Language Service.

> Is it possible to declare a type once for all variables? 
Unfortunately I don't think this is supported - you'll have to declare them separately.

More info on supported JSDoc https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc
