### ISSUE TITLE
Tooltip Scaling Between Monitor Resolutions

### ISSUE THREAD

**Issue by P-N-L** [microsoft/vscode#93518]
Issue Type: <b>Bug</b>

Steps to Reproduce:
0) Run Windows 10 1809 on a 2+ monitor setup, one 4k and one lower resolution (I am using 1360x768).
1) Launch VSCode on the 4k monitor.
2) Move VSCode to the lower-resolution monitor.
3) Hover over anything that generates a tooltip (such as a file, to see its full file path).

Expected:
The tooltip is a "reasonable size", similar in font size to the name of the file being hovered over for example.

Actual:
The tooltip has not been scaled properly, and appears to be a far larger font size than desired.

VS Code version: VSCodium 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-21T00:21:25.699Z)
OS version: Windows_NT x64 10.0.17763

**Comment by deepak1556** [comment]
Thanks for the report, I am merging this to https://github.com/microsoft/vscode/issues/85898 

Using `"window.titleBarStyle": "native"` should workaround for now.
