### ISSUE TITLE
API for improving UX in launch.json configuration  

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#93511]
The Python extension displays a list of configurations for users when they start debugging for the first time (i.e. no launch.json exists):

![image](https://user-images.githubusercontent.com/45497113/77674762-49d1bf80-6f49-11ea-9adc-da5b104d9a86.png)

Once the file is created, we also wanted to show this option when users click on "Add Configuration..." in the file. 

The solution we came up with was to add a grouping configuration called "Python", that once clicked shows the same list of possible configurations:

![image](https://user-images.githubusercontent.com/45497113/77675562-54408900-6f4a-11ea-90e7-d93e4d8fa911.png)

The problem is that in user studies we see people completely ignoring this item, as they look for "Python" options like the see for Node.js or Java. However, we'd prefer not to simply populate that view with all the Python options (e.g. Python: Current File, Python: Flask, Python: Django etc.) that once clicked would add a config template in the launch.json file, because we would still like to show the UI for adding arguments. For example, when you select "Python: Remote Attach", users can add the host name through the UI instead of the launch.json file. We've also seen in studies that new to VS Code users are intimidated by editing the json file directly.

One idea we discussed and that we thought would be a good solution to this is to allow the UI menu to show up once users clicked on a configuration that would be listed in the config lists. 

To exemplify the workflow we would like:

![image](https://user-images.githubusercontent.com/45497113/77676498-a6ce7500-6f4b-11ea-967a-959a8ce7a144.png)

Clicking on "Python: Remote Attach" would show the following configuration menu:

![image](https://user-images.githubusercontent.com/45497113/77676620-c9608e00-6f4b-11ea-8484-3c43e9098275.png)

But I think this isn't possible through the existing APIs. But even it is, I'd love to hear from you if you agree that this is a good middle ground solution. For reference, here's the discussion thread from some time ago around the same subject: https://github.com/microsoft/vscode-python/issues/3321.

**Comment by isidorn** [comment]
@luabud thanks for sharing this feedback. 

1) Clicking on the `Python: Remote Attach` could show that configuration menu, same way as clicking on `Python` shows the quick pick. I think you can use the same approach you use for the `Python` entry
2) I think your proposal makes sense and it would definetely help
3) What VS Code could improve is not show the unraleted  launch configuration suggestions (in this case Node is taking up too much of users attention.
4) @connor4312 is already looking into supporting launching Node as much as possible without a need for a launch configuraotion. It might be cool if he shares his experiences with your teams so Python also tries to reduce the need for having a launch.json only for advanced configurations. And that all simple use cases should not require one

fyi @weinand

**Comment by luabud** [comment]
Thanks @isidorn! It'd be great to learn more about @connor4312's work and see how we can improve the experience in a similar way 😊

**Comment by connor4312** [comment]
Sure. Much of this might be specific to the capabilities in Node, but perhaps you can find something useful here.

The first effort was around getting good out-of-the-box defaults such that 90% of users would never need to touch them. This is foundational to any zero-config experience: it doesn't matter if we're able to add easy entrypoints to debugging if the user needs to create a config to make it work properly anyway. For example, in the previous debugger users needed to manually configure the path in which we search for sourcemaps, the `outFiles`, whereas in the new debugger we figured out ways we could be smarter and find sourcemaps throughout the workspace automatically.

That in place, we added entrypoints to make debugging easier. The one we've been advertising most heavily has been the debugger terminal. This is a magic terminal where any Node.js command you run will automatically be debugged. ([gif](https://code.visualstudio.com/assets/updates/1_42/js-debug-terminal.gif))

We've also added a button to open this terminal to the [debug start view](https://github.com/microsoft/vscode/issues/85548)

![](https://user-images.githubusercontent.com/1926584/76077502-1c74a000-5fa1-11ea-9ebd-613d194355eb.png)

(Note that if you add buttons here, I think it's important to keep them as contextually relevant as possible and avoid presenting the user with a wall of buttons. You can use the `setContext` command from your extension to set context keys to vary the visibility of welcome views)

We also added a code lens which automatically runs tasks in the debug terminal from the package.json (sort of equivalent to a tox.ini in Python land...)

![](https://code.visualstudio.com/assets/updates/1_42/js-debug-code-lens.png)

Hope this gives you some ideas :)

**Comment by isidorn** [comment]
Closing as there are no action items to tackle regarding this in the near future
