### ISSUE TITLE
GitHub Logout

### ISSUE THREAD

**Issue by mrseankumar25** [microsoft/vscode#93510]
Issue Type: <b>Bug</b>

Hello,

I am having an issue after the last update. Whenever I close the VS Code and run it again I got a popup every time. It asking me to login again and again. Please take a look at this, it annoying me.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ACF-Snippet|ant|1.9.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.29
javascript-ejs-support|Dig|1.3.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
bootstrap-4-cdn-snippet|eve|1.3.0
auto-rename-tag|for|0.1.1
rest-client|hum|0.23.2
vscode-liquid-snippets|kil|1.3.0
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-docker|ms-|1.0.0
mssql|ms-|1.9.0
language-liquid|nei|0.1.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
shopify-liquid|sis|2.3.0
bracket-padder|via|0.2.0
wordpress-toolbox|wor|1.3.6
bootstrap-v4-snippets|Zac|1.1.3

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have example of this popup.

What is your git setup and where credentials are stored for Git?

**Comment by mrseankumar25** [comment]
Hello,

here is a video I have recorded.


Sandeep Kumar
Frontend Developer
 +919780447250
 seankumar946@gmail.com

**Comment by mrseankumar25** [comment]
Ok, I'll review them, but here is a video I have recorded, please check it
out.

Sandeep Kumar
Frontend Developer
 +919780447250
 seankumar946@gmail.com

**Comment by IllusionMH** [comment]
Looks like you are using GitHub app for authorization therefore when VS Code performs any action with network action with git - git will ask for creds (GitHub app)

Probably related to #490

**Comment by mrseankumar25** [comment]
Thank you sir, for the help, it's fixed now, I have re-login in it by git
bash and it works.


Sandeep Kumar
Frontend Developer
 +919780447250
 seankumar946@gmail.com
