### ISSUE TITLE
Hide terminal while working instead of deleting to hide it

### ISSUE THREAD

**Issue by aak-dev** [microsoft/vscode#93519]
Version: 1.43.2
OS: Darwin x64 18.7.0

Currently when i when i work i have to explicitly remove terminal and when i relaunch it a new terminal pops up, as i had to delete previous terminal to get real estate while coding on editor.

**Comment by sanket-bhalerao** [comment]
is this query about hiding the terminal in order to view a full screen editor window?
in that case use `ctrl+j` shortcut to toggle the terminal. this just hides the terminal and toggle back to same terminal window when you reopen.

**Comment by aak-dev** [comment]
command+j great, thanks!
