### ISSUE TITLE
launch.json: Start multi-target debugging in one launch configuration not working

### ISSUE THREAD

**Issue by adymorz** [microsoft/vscode#93523]
Issue Type: <b>Bug</b>

```
{
	"name": "Debug server and client",
	"type": "coreclr",
	"request": "launch",
	"preLaunchTask": "build",
	"program": "${workspaceFolder}/build/myTool.dll",
	"args": [],
	"cwd": "${workspaceFolder}",
LaunchJson-Console
	"console": "internalConsole",
	"stopAtEntry": false,
	"requireExactSource": true,
	"serverReadyAction": {
		"pattern": "Now listening on: http://[^0-9]*(.+)",
		"uriFormat": "http://localhost:%s",
		"action": "debugWithChrome"
	}
},
```

1. Use the configuration above to start debugging the server and client at once
2. Two debug session are started, but only the youngest session is shown in the debug toolbar. I expcted to see both sessions in the debug toolbar.

VS Code version: Code - Insiders 1.44.0-insider (e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c, 2020-03-26T05:51:24.240Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.15

</details>

**Comment by isidorn** [comment]
Please use debug compoound configurations. More about that can be found here https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations

If things still do not work then please file issue against C# extensions which you are using. Thank you

**Comment by adymorz** [comment]
Thanks for your fast reply. Compound configurations doest not help me because reading out the port from console output is not possible with compound configurations.

I created a bug report on omnisharp-vscode project: https://github.com/OmniSharp/omnisharp-vscode/issues/3695

**Comment by adymorz** [comment]
After the [comment of Joey Robich in the omnisharp-vscode project](https://github.com/OmniSharp/omnisharp-vscode/issues/3695#issuecomment-605355233), I think it is a VS Code issue. What do you think, @isidorn?

**Comment by isidorn** [comment]
@adymorz if they believe it is a vscode issue they should file a minimal reproducable steps issue in our repository.
VS Code properly shows mulitple sessions when only one session is launched, example being the new js-debug. So this works in general, their extension might be doing something special in which case it would be cool if they investigate and open an issue.
