### ISSUE TITLE
Alt activates on Ctrl + Alt

### ISSUE THREAD

**Issue by lambduli** [microsoft/vscode#93522]
- VSCode Version: 1.43.2
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Hit Ctrl + Alt
2. Observe menu - default Alt action was executed

Does this issue occur when all extensions are disabled?: Yes

It is kinda annoying - it captures my cursor and I am constantly interrupted by that whenever I want to hit Ctrl + Alt and switch workspace but I change my mind for whatever reason.

Also it can not be switched of while holding the Ctrl key even though Ctrl was down when it was switched on.

I hope it's relevant and it's not intended to behave like that - if yes - sorry to bother and would you please give me a hint how to disable it?

Thank you. Otherwise I like VSCode and what y'all do with it.

**Comment by sbatten** [comment]
The custom menus (enabled with `window.titleBarStyle` => `custom` do no repro this behavior. This means that it is the native electron menu with the issue.

**Comment by ru-ace** [comment]
I got same problem when hit Allt+Shift (to change keyboard layout). 
Its very annoying, cause changing keyboard layout interrupt text editing and i need hit esc to continue editing text.

**Comment by rzhao271** [comment]
@ru-ace what operating system are you on?
I'm unable to reproduce the issue on Windows 10 with v1.52.1. Also, I noticed that on Windows 10, using Shift+Alt instead of Alt+Shift changes the keyboard layout without the list of keyboard options popping up.

**Comment by ru-ace** [comment]
@rzhao271 Manjaro Linux with KDE. Problem persist at last vscode version(1.52.1).

**Comment by elahn** [comment]
Confirmed on Linux Mint 19.3 with vscode 1.63.2.

This bug also prevents Alt+Click for multi-cursor or navigation.

**Comment by deepak1556** [comment]
Unable to repro on Ubuntu 22.04 with latest stable `1.74`
