### ISSUE TITLE
Allow new editor to open with an empty file

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/vscode#9352]
- VSCode Version: 1.4.0-insider
- OS Version: macOS 10.11.5

Steps to Reproduce:

1. Close all other editors, work on a file, make some changes.
2. Press <kbd>⌘</kbd> + <kbd>\\</kbd> to open a new editor.
3. You want to work on another file in this editor and don't need the first file to be open here as well. But you can't close that file without first saving it. If you choose not to save, your changes are lost even in the first editor.

Point being, opening the same file in the new editor is a sensible default. But an option to not do so (perhaps with <kbd>Shift</kbd> + <kbd>⌘</kbd> + <kbd>\\</kbd>) should also be provided which would just open a new editor with an empty file and not continue with the one already open in the old editor.

Edit: I just remembered <kbd>Shift</kbd> + <kbd>⌘</kbd> + <kbd>\\</kbd> is already taken, so maybe some other. The other shortcuts to open/re-focus editors <kbd>⌘</kbd> + <kbd>2</kbd> / <kbd>3</kbd> could also be extended.

**Comment by bpasero** [comment]
It is our design decision since we introduced tabs/stacks that you cannot close a dirty file in the editor unless you save or discard and we do not plan to change this behaviour.
