### ISSUE TITLE
Be able to see if two files/functions are connected at all

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode#93521]
Often I need to know if this function is being called by code whether it's parent or child. Only way for me to is trace all imports and see they invoke anything if not then trace their imports. Similarly, see all references and see if THEY call the function in question, if not see if any of their children do. 

Reason I've to check children and parents is because how convoluted react code becomes. Data is being passed 8 levels down and then 5 levels further. Sometimes you need a certain piece of data and you wonder if xyz is already being called in some manner or not. 

Extra bonus: if works react context and redux.

**Comment by IllusionMH** [comment]
Have you checked https://code.visualstudio.com/updates/v1_43#_call-hierarchy-support-for-javascript-and-typescript ?
