### ISSUE TITLE
Piping stdout output to file

### ISSUE THREAD

**Issue by ftrofin** [microsoft/vscode#93520]
I have a Python program that I'm debugging and it generates lots of output (in verbose mode). The integrated terminal had limited buffer and can't hold all the output. I would like to pipe the output through the `tee` utility (on Mac) so I can see the output in VS Code window but also capture it in its full form in a file. I tried the following:
- using the `args` in the launch.json:
```			
"args": ["--myarg", "5",
	// more args,
	"|",
	"tee",
	"output.log"
],
```
This doesn't work because the "|" pipe character is not recognized and it's sent to my app (I understand that you have special handling of "<" and ">" but not "|")
- creating a wrapper script which calls my program and adds the "| tee output.log" at the end of the command. This also doesn't work because I can't debug my Python script.

**Comment by weinand** [comment]
I suggest to run the command with the pipe ('|') and "tee" from the command line and then use the Python debugger in "attach" mode.

Creating a wrapper script should work, but make sure that all arguments passed to that script by the Python debugger are properly propagated to the python runtime.

I suggest to ask the authors of the Python extension directly.
