### ISSUE TITLE
Terminal Text not showing international accented characters like 'ÖÁÍÉ' on macOS 10.15.4

### ISSUE THREAD

**Issue by sverrisson** [microsoft/vscode#93529]
- VSCode Version: 1.43.2
- OS Version: Darwin x64 19.4.0
macOS 10.15.4

Steps to Reproduce:

1. Log to terminal a string in Python. Run the following python code:
print('ÖÁÍÉ')
print('ÖÁÍÉ')
print('ÖÁÍÉ')

2. The accents will not be shown
3. See pic 
<img width="50" alt="Example" src="https://user-images.githubusercontent.com/1449655/77700695-9ef2ed00-6fac-11ea-9318-f11a9e5e9ba2.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by sportshead** [comment]
I can slightly make out an extra pixel for the accented characters:
![Screenshot 2020-03-27 at 4 25 33 PM](https://user-images.githubusercontent.com/32637656/77736722-aadfbd00-7047-11ea-8029-9fb3db350f0c.png)
Open the photo and zoom in.

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/35901

Fix it to move to the WIP webgl renderer or (slower) DOM renderer with these settings:
 
```
"terminal.integrated.rendererType": "dom"
"terminal.integrated.rendererType": "experimentalWebgl"
```
