### ISSUE TITLE
Allow different diff algorithms

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#93534]
https://link.springer.com/article/10.1007%2Fs10664-019-09772-z points out that the defualt git diff algorithm isn't great, and using  `histogram` can provide better results:
![image](https://user-images.githubusercontent.com/8586769/77706218-03975300-6f7f-11ea-9ab1-04339898a2d7.png)

This can be configured globally with `git config --global diff.algorithm histogram`, but it might be nice to allow users to configure it inside code, with the potential to switch between algorithms.

**Comment by joaomoreno** [comment]
#84981
