### ISSUE TITLE
Cannot commit any changes

### ISSUE THREAD

**Issue by dielleluis** [microsoft/vscode#93539]
Issue Type: <b>Performance Issue</b>

When I clicked on commit an alert appeared on the screen and I accidentally clicked on Never. Now I cannot commit anymore

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_823497|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    98	  3010	code main
    0	    49	  3014	   gpu-process
    0	    25	  3016	   utility
    0	   262	  3017	   window (Settings — revisaohtmlcss)
    0	    82	  3023	     extensionHost
    0	    66	  3027	       electron_node tsserver.js 
    0	    82	  3028	       electron_node tsserver.js 
    0	    57	  3035	         electron_node typingsInstaller.js typesMap.js 
    0	    66	  3060	       /private/var/folders/ss/m3h5r8wn493cxmb0_yzflpfr0000gn/T/AppTranslocation/DB851BE9-9CFB-466C-AC71-819953B9E692/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/ss/m3h5r8wn493cxmb0_yzflpfr0000gn/T/AppTranslocation/DB851BE9-9CFB-466C-AC71-819953B9E692/d/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=3023
    0	    49	  3079	       /private/var/folders/ss/m3h5r8wn493cxmb0_yzflpfr0000gn/T/AppTranslocation/DB851BE9-9CFB-466C-AC71-819953B9E692/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/ss/m3h5r8wn493cxmb0_yzflpfr0000gn/T/AppTranslocation/DB851BE9-9CFB-466C-AC71-819953B9E692/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3023
    0	    33	  3025	     watcherService
    0	    82	  3033	   shared-process
    0	     0	  3098	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    3	    74	  3095	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings — revisaohtmlcss)
|    Folder (revisaohtmlcss): 9 files
|      File types: gitignore(1) md(1) css(1) js(1) html(1) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
flask-snippets|cst|0.1.1
python-extension-pack|don|1.6.0
MagicPython|mag|1.1.0
start-git-bash|McC|1.2.1
vscode-exec-node|mir|0.5.1
python|ms-|2020.3.69010
watch-in-chrome|sne|0.0.2
python|tht|0.2.3
vscodeintellicode|Vis|1.2.6
jinja|who|0.0.8

</details>

**Comment by joaomoreno** [comment]
What happens when you try to commit? Can you provide more information? 
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by dielleluis** [comment]
I uploaded a video on YouTube showing what happens. Basically, when I try to commit nothing happens. I don't see the blue bar loading as if its trying to commit.

https://www.youtube.com/watch?v=tEi9xvIEXTc

**Comment by joaomoreno** [comment]
Can you run `Git: Show Git Output` and see what's in there?

**Comment by dielleluis** [comment]
I can run git commit from the command line with no problems at all. I've using the terminal to commit or pull my work.

See below the pic from the VScode Git Output.

Thanks for the help!



<img width="1522" alt="Screen Shot 2020-04-03 at 14 27 08" src="https://user-images.githubusercontent.com/60760696/78388374-42e52580-75b7-11ea-9c2d-b1182eab05cb.png">

**Comment by joaomoreno** [comment]
Can you reproduce if you run with `--disable-extensions`? When you press `Commit`, is there no output in that Git output?
