### ISSUE TITLE
"Show more" line is clipped

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#93532]
The "Show more" line is clipped at the bottom in Insiders:

<img width="426" alt="2020-03-26_23-44-38" src="https://user-images.githubusercontent.com/1898161/77703711-c8ffdb80-6fbb-11ea-9820-8786f370bf08.png">

**Comment by isidorn** [comment]
Good catch. Thanks

**Comment by weinand** [comment]
No longer clipped:
<img width="364" alt="2020-04-02_15-50-35" src="https://user-images.githubusercontent.com/1898161/78257139-bf193380-74f9-11ea-982c-ec93c825f55a.png">
