### ISSUE TITLE
Feature Request: A comprehensive editor UI for colorization/highlighting settings

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#93537]
It can be a technical hurdle for users to customize colors for syntax/semantic highlighting.  Those settings must be defined textually in settings.json.  For example:

```
    "editor.tokenColorCustomizations": {
        "comments": "#FF0000",
        "functions": "#FF0000",
        "textMateRules": [
            {
                "scope": "entity.name.namespace",
                "settings": {
                    "foreground": "#FF0000",
                    "fontStyle": "italic bold underline"
                }
            },
            {
                "scope": "variable.other.enummember",
                "settings": {
                    "foreground": "#FF0000"
                }
            }
        ]
    }
```

There are a few simplified categories, such as `comments` and `functions`, but most tokens require knowledge of TextMate rules, which is a loose standard and diverges significantly per language.

Could a colorization editor UI be added to make this simpler?

Perhaps it could be extensible, such that:
* Descriptions, etc., could be associated with TextMate grammers, to surface language-specific content/scopes.
* Extensions could similarly add descriptions, etc., for semantic token settings they provide (in `contributes`)

Perhaps it could facilitate applying color customizations per language.  ( https://github.com/microsoft/vscode/issues/66729 )

------

Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by aeschli** [comment]
Have a look at https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#token-styling. That's already in and functional. The idea is to merge that into editor.tokenColorCustomizations

```
 "editor.tokenColorCustomizationsExperimental": {
        "enumMember": {
            "foreground": "#ff4423"
        },
        "property.readonly": {
            "foreground": "#35166d"
        },
        "*.declaration": {
            "fontStyle": "underline"
        }
    }
```

- there's code completions for the selectors ('enumMember', ...) using on the contributed token types and modifiers.
- code completion descriptions are based on the descriptions from the [token type & modifier contributions](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#custom-token-types-and-modifiers)
- selectors can be language specific, and theme specific
```
 "editor.tokenColorCustomizationsExperimental": {
        "enumMember:java": {
            "foreground": "#ff4423"
        }
        "[Monokai]": {
            "enumMember": {
                 "foreground": "#ff4423"
            }
        }
}
```

**Comment by Colengms** [comment]
Hi @aeschli .  This request would be for an editor UI, not text-based.  Updating title to clarify.
