### ISSUE TITLE
Node debugger not stopping at most breakpoints when using ts-node

### ISSUE THREAD

**Issue by robin-hartmann** [microsoft/vscode#93535]
Issue Type: <b>Bug</b>

When debugging in ts-node, the debugger doesn't stop at most breakpoints, which are not in the entry file. To reproduce this, follow the steps outlined in the repository [robin-hartmann/bug-vscode-node-debug2-breakpoints](https://github.com/robin-hartmann/bug-vscode-node-debug2-breakpoints#readme), which contains a minimal working example.

While looking for a solution, I noticed this can already be fixed by using the new upcoming JavaScript debugger [vscode-js-debug](https://github.com/microsoft/vscode-js-debug#readme), which is also explained in the repository mentioned above. Nevertheless, I wanted to file an issue, because I don't know when the new debugger is coming and whether you want to fix this, after all. And maybe someone with the same problem might find this helpful.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (25.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by connor4312** [comment]
Thanks for the issue, and the repo. ts-node (and @babel/register, etc) is something that node-debug2 doesn't support, and we aren't planning to backport into node-debug2 as js-debug is becoming stable and the infrastructure to support ts-node isn't trivial to implement. Let us know if you run into any more issues!

/duplicate https://github.com/microsoft/vscode-js-debug/pull/174

**Comment by robin-hartmann** [comment]
> Thanks for the issue, and the repo. ts-node (and @babel/register, etc) is something that node-debug2 doesn't support, and we aren't planning to backport into node-debug2 as js-debug is becoming stable and the infrastructure to support ts-node isn't trivial to implement. Let us know if you run into any more issues!
> 
> /duplicate [microsoft/vscode-js-debug#174](https://github.com/microsoft/vscode-js-debug/pull/174)

Okidok, no problem!
