### ISSUE TITLE
Ability to remove file permanently (bypass trash)

### ISSUE THREAD

**Issue by narqo** [Microsoft/vscode#9354]
- VSCode Version: 1.3.1
- OS Version: OS X, 10.11

Steps to Reproduce:

1. Open file explorer.
2. Select a file.
2. Choose "Delete" from the contex menu or hit ⌘+Delete.

You'll be prompted to move the file to Trash. It'd be nice to have an ability (with a separate shortcut or by switching an IDE option in the config) to remove files permanently.

**Comment by bpasero** [comment]
Verify you can bypass trash by using the context menu "Delete" action while holding Shift (Windows, Linux) or Alt (Mac).

**Comment by roblourens** [comment]
Verified on OSX and Linux, but I don't see this on Windows. When I press Shift+Delete, nothing happens. Tried some other keys too.

**Comment by bpasero** [comment]
@roblourens works for me though: ![editors](https://cloud.githubusercontent.com/assets/900690/18942069/6cc30fd2-8616-11e6-81df-6cd5fbc0369c.gif)

**Comment by roblourens** [comment]
Uh... it's working now. And some of my keyboard shortcuts seem messed up in Parallels. I think it's fine.

**Comment by post2web** [comment]
On mac: command + option + delete

**Comment by skorunka** [comment]
Is it possible to delete file by default? I mean, without holding the `shift` key while pressing the `del` key?
