### ISSUE TITLE
"Find all references" not works fine if the file is not displayed

### ISSUE THREAD

**Issue by Fire-Kirin** [microsoft/vscode#93544]
VS Code: 1.43.2
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:
in file a.js
```
export const Name = 'abc';
```
in file b.js
```
import { Name } from './a.js';
const b = Name;
```

1. Open both file, and stay at `a.js` tab, then close VS Code.
2. Reopen VS Code, in a.js, right click the variable `Name`, then click "Find all references", you'll find only one result (`a.js`) is displayed in the left panel.
3. Click `b.js` tab to make it displayed.
4. Go back to `a.js`, and redo "Find all references", this time it will show `b.js` in the left panel as expected.

Does this issue occur when all extensions are disabled?: Yes

![](https://md-private-w-public-r-1256490109.cos.ap-guangzhou.myqcloud.com/others/20200327110357.png)

**Comment by mjbvz** [comment]
Have you tried [creating a `jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson)?

**Comment by sportshead** [comment]
@mjbvz Dosen't work even with `jsconfig`

**Comment by mjbvz** [comment]
Works for me in VS Code insiders with extensions disabled:

![Screen Shot 2020-03-27 at 12 57 42 PM](https://user-images.githubusercontent.com/12821956/77795313-9214de80-702a-11ea-9894-2d5fb26524b4.png)

What does your jsconfig contain?

**Comment by Fire-Kirin** [comment]
> Have you tried [creating a `jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson)?



> Works for me in VS Code insiders with extensions disabled:
> 
> ![Screen Shot 2020-03-27 at 12 57 42 PM](https://user-images.githubusercontent.com/12821956/77795313-9214de80-702a-11ea-9894-2d5fb26524b4.png)
> 
> What does your jsconfig contain?

It works fine with `jsconfig` which contains following codes and no need to disable any extensions, just reopen VS Code. Thanks !
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  },
  "include": ["src/**/*"]
}
```

**Comment by mjbvz** [comment]
Ok, closing this since is the designed behavior. A jsconfig tells VS Code to treat all JS files in your workspace as part of a single project, so it's required if you want to use operations like find all references
