### ISSUE TITLE
Notebook: scroll position should not be shared between notebooks

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#93542]
Issue Type: <b>Bug</b>

Repro:

* Open one notebook, scroll 
* Open a new one, the scorll position is kept

We should behave the same as monaco editor where each editor input has its own scroll state.

VS Code version: Code - Insiders 1.44.0-insider (e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c, 2020-03-26T05:50:18.281Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
vscode-pull-request-github-insiders|Git|2020.3.35461
vscode-language-pack-zh-hans|MS-|1.44.0
remote-ssh-edit-nightly|ms-|2020.3.35462
remote-ssh-nightly|ms-|2020.3.35462
js-debug-nightly|ms-|2020.3.1617
vsliveshare|ms-|1.0.1847
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8

(4 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
When switching between two notebooks, I'm now seeing the scroll position always be reset to the top. I'm using two `.github-issues` files
