### ISSUE TITLE
Notebook: max output height

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#93541]
Issue Type: <b>Feature Request</b>

Right now we don't set any max height for outputs thus in GitHub Issue Notebook, outputs are always long lists which make it hard to navigate between cells.

VS Code version: Code - Insiders 1.44.0-insider (e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c, 2020-03-26T05:50:18.281Z)
OS version: Darwin x64 19.2.0

**Comment by rebornix** [comment]
@jrieken for this iteration, we can probably add a max height for the output itself then we can see a scrollbar in the issues list. Later on outputs can come with metadata like dimensions but we need to think about how scrolling should be handled. Currently my take away is the renderer should do the max height styling.

**Comment by jrieken** [comment]
I have pushed a change for GH issue notebooks, let tackle the rest in April
