### ISSUE TITLE
Pls Remake color picker, just click and show, not hover

### ISSUE THREAD

**Issue by Doankidy** [microsoft/vscode#93549]
When i turn of Hover, it also disables color picker. which is weird. Pls make color picker "just click and show", not hover

**Comment by gfmoore** [comment]
I can't even get it to work and haven't had it working for over a year as far as I can remember.
How did you turn off hover?

**Comment by Doankidy** [comment]
Hi,
My problem is that the popup tips cover the content behind when I hover on
text, i found it very uncomfortable. Then, I disable the hover, but it also
disables the Color picker which I want to keep. So in my opinion, I think
you guys should make "tooltip hover" NOT related to "color picker hover".
Hope you understand, im trying to explain it in English :)

[image: a1.png]
Love you

**Comment by gfmoore** [comment]
Hi, sorry, must have misunderstood :(

Anyhow I totally got rid of VSCode and all the crud everywhere, new re-install and color picker now working - yay :)

**Comment by shungo27** [comment]
I want cmd + click to launch the color picker, not the click.
too annoying to launch with a hover.

**Comment by ghiscoding** [comment]
I've opened a similar issue [#33568](https://github.com/microsoft/vscode/issues/33568) to address the hover but unfortunately still waiting to get it resolved
