### ISSUE TITLE
used commit, gutter decoration is not updated

### ISSUE THREAD

**Issue by wtklbm** [microsoft/vscode#93552]
VSCode Version: 1.44.0-insider
Commit: e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c
Date: 2020-03-26T05:51:24.240Z
OS Version: Windows 10 2019 LTSC

Steps to Reproduce:
1. open the Source Control
2. input message，For example, enter `1`
3. commit
4. refresh Source Control
5. restart vscode, everything is fine.

It looks like this after submission:

![test](https://user-images.githubusercontent.com/26459487/77723443-6fcf9080-702b-11ea-8c0d-9a2359971d63.gif)

custom configuration:
```json
"git.autorefresh": true,
"git.autofetch": true,
"git.autofetchPeriod": 900,
"git.postCommitCommand": "push",
"git.enableSmartCommit": true,
"git.autoStash": true,
"git.showPushSuccessNotification": true,
"git.alwaysShowStagedChangesResourceGroup": true,
"git.fetchOnPull": true,
"git.ignoreLegacyWarning": true,
"git.ignoreMissingGitWarning": true,
"git.supportCancellation": true,
"git.untrackedChanges": "mixed"
```

**Comment by joaomoreno** [comment]
You seem to be missing file events. Please go through the following steps:

1. Run `Git: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Reproduce the issue and wait 10-20 seconds
4. Paste the whole output here

Thanks!

**Comment by joaomoreno** [comment]
Also, are your changes in a network share, or any other special file system location?

**Comment by wtklbm** [comment]
Sorry, I can’t send file events to you right now. Gutter is sometimes normal and sometimes abnormal. When I find that gutter is abnormal again, I will try to capture file events.

**Comment by joaomoreno** [comment]
OK let me know.

**Comment by wtklbm** [comment]
At your request, i captured file events. i opened 3 vscode windows. and every window is opened to connect to the remote git repository. to test the problem, i removed all vscode configurations, below is a screenshot i captured.i just refreshed the current repository, however, gutter is still not updated.

![test](https://user-images.githubusercontent.com/26459487/78153172-6308cd80-746d-11ea-9fe2-e3b5cd40b77c.gif)



```js
// file events.

> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
```

**Comment by joaomoreno** [comment]
You forgot to change the log level. Also, please give me the full log, I'd like to know the location of your git executable as well as your repository.

**Comment by wtklbm** [comment]
I waited for a few minutes and only saw these log messages. Do you need anything else.

```
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\compile\mergeLine.ts
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git add -A -- .
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
> git commit --quiet --allow-empty-message --file -
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\COMMIT_EDITMSG
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\COMMIT_EDITMSG
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\HEAD.lock
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\HEAD.lock
> git status -z -u
> git symbolic-ref --short HEAD
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\base\joinComment.ts.git
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\base\joinComment.ts
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\node_modules\wtools-translate\dist\index.dev.js.git
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\base\joinComment.ts
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\node_modules\wtools-translate\dist\index.dev.js
> git rev-parse master
> git cat-file -s 72a7dcb56834c75dbbf61213fd374181056399c5
> git show :node_modules/wtools-translate/dist/index.dev.js
> git show :src/base/joinComment.ts
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git push origin master:master
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\refs\remotes\origin\master\master
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\refs\remotes\origin\master\master
To https://github.com/wtklbm/cmtor
   b15f965..f47e342  master -> master
> git status -z -u
> git symbolic-ref --short HEAD
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\base\joinComment.ts.git
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\base\joinComment.ts
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\node_modules\wtools-translate\dist\index.dev.js.git
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\base\joinComment.ts
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\node_modules\wtools-translate\dist\index.dev.js
> git rev-parse master
> git cat-file -s 72a7dcb56834c75dbbf61213fd374181056399c5
> git show :node_modules/wtools-translate/dist/index.dev.js
> git rev-parse --symbolic-full-name master@{u}
> git show :src/base/joinComment.ts
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git config --get commit.template
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\config\verify\special.ts
> git cat-file -s dabca03e25ddfa85d142a1447cd71d126215c52d
> git show :src/config/verify/special.ts
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\config\verify\special.ts
> git cat-file -s dabca03e25ddfa85d142a1447cd71d126215c52d
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\config\verify\special.ts
> git cat-file -s dabca03e25ddfa85d142a1447cd71d126215c52d
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\config\verify\special.ts
> git cat-file -s dabca03e25ddfa85d142a1447cd71d126215c52d

```

**Comment by joaomoreno** [comment]
What git version do you have?

**Comment by wtklbm** [comment]
git version 2.25.1.windows.1

**Comment by joaomoreno** [comment]
Can you update to 2.26 and see if it still reproduces?

**Comment by wtklbm** [comment]
ok，let me try

**Comment by joaomoreno** [comment]
OK Let me know.

**Comment by wtklbm** [comment]
Much better than before，after submitting the code, occasionally there will be situations where gutter does not update. But after waiting for a time, it seems that gutter is updated automatically. thank you for your help.

**Comment by wtklbm** [comment]
@joaomoreno sorry, the problem appears again. I installed the latest vscode insider, gutter still cannot be updated occasionally, and clicking the refresh button has no effect. I waited a long time without updated. 

![2020-04-07_19 07 28](https://user-images.githubusercontent.com/26459487/78662507-1ad12b80-7903-11ea-954b-03ef8ba5aced.png)


···
> git add -A -- .
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
> git commit --quiet --allow-empty-message --file -
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\index
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\COMMIT_EDITMSG
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\COMMIT_EDITMSG
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\HEAD.lock
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\HEAD.lock
> git status -z -u
> git symbolic-ref --short HEAD
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\terminal\npm\base\initialProject.ts.git
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\terminal\npm\base\initialProject.ts
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\terminal\npm\install\modules.ts
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\terminal\npm\base\initialProject.ts
> git rev-parse master
> git cat-file -s 954777dfef4bb50d9b10503670b185e447da0838
> git rev-parse --symbolic-full-name master@{u}
> git show :src/terminal/npm/base/initialProject.ts
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git push origin master:master
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\refs\remotes\origin\master\master
[debug] [.git] Change: f:\Backup\my_snippets\cmtor\.git\refs\remotes\origin\master\master
To https://github.com/wtklbm/cmtor
   80fa1dc..21bb702  master -> master
> git status -z -u
> git symbolic-ref --short HEAD
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\terminal\npm\base\initialProject.ts.git
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\terminal\npm\base\initialProject.ts
[debug] [wt] Change: f:\Backup\my_snippets\cmtor\src\terminal\npm\install\modules.ts
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\terminal\npm\base\initialProject.ts
> git rev-parse master
> git cat-file -s 954777dfef4bb50d9b10503670b185e447da0838
> git rev-parse --symbolic-full-name master@{u}
> git show :src/terminal/npm/base/initialProject.ts
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git config --get commit.template
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\terminal\npm\base\translateTypescript.ts
> git cat-file -s e79d15139b3827ce97ab01d3f082ef7efff6546f
> git show :src/terminal/npm/base/translateTypescript.ts
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\terminal\npm\base\translateTypescript.ts
> git cat-file -s e79d15139b3827ce97ab01d3f082ef7efff6546f
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\terminal\npm\base\translateTypescript.ts
> git cat-file -s e79d15139b3827ce97ab01d3f082ef7efff6546f
> git ls-files --stage -- F:\Backup\my_snippets\cmtor\src\terminal\npm\base\translateTypescript.ts
> git cat-file -s e79d15139b3827ce97ab01d3f082ef7efff6546f
···

**Comment by wtklbm** [comment]
git version 2.26.0.windows.1
