### ISSUE TITLE
Integrated Terminal shows nothing

### ISSUE THREAD

**Issue by akaxxi** [Microsoft/vscode#9355]
- VSCode Version: 1.3.0 and 1.3.1
- OS Version: Windows 10 x64 [10586] 

Steps to Reproduce:
1. Open VSCode 
2. `Ctrl`+<code>`</code>

Integrated terminal didn't work after I updated to version 1.3.0 like this:
![image](https://cloud.githubusercontent.com/assets/7767960/16880205/af7593ec-4ae6-11e6-8ca9-28fc8c997b3e.png)

Here is my config (I didn't change anything):
```
"terminal.external.windowsExec": "cmd",
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
```
After checking task manager , I find that the terminal VSCode opened is '"C:\Windows\SysWOW64\cmd.exe". It isn't  the "C:\Windows\System32\cmd.exe".

**Comment by yanky2000** [comment]
Got the same problem,

**Comment by Tyriar** [comment]
Are there any errors in the dev tools console? (Help > Toggle Developer Tools).

There isn't any special logic to open `C:\Windows\SysWOW64\cmd.exe` instead in code but it's probably what you should be using since it's the 64-bit version of cmd.exe.

**Comment by yanky2000** [comment]
Devtools shows no errors.

I'm not sure if VSCODE running '"C:\Windows\SysWOW64\cmd.exe" or whatever as it was mentioned above. 

Just got updated and now terminal shows nothing. Any idea what could be wrong?

**Comment by Tyriar** [comment]
Does it work if you remove `terminal.integrated.shell.windows` from your settings.json and restart vscode?

**Comment by akaxxi** [comment]
@Tyriar There are no errors in DevTools. And removing  `terminal.integrated.shell.windows` doesn't work for me.
Here are the terminal's  html codes in DevTools. I have removed some repeated lines and spaces.
```
<div class="composite panel integrated-terminal" id="workbench.panel.terminal" aria-hidden="false">
    <style>
        .monaco-workbench .panel.integrated-terminal .xterm .xterm-color-0 {
            color: #000000;
        }
       /*more css setting start with ".monaco-workbench .panel.integrated-terminal .xterm" */
    </style>
    <div class="terminal-outer-container">
        <div class="terminal-wrapper active">
            <div style="font-family: Consolas, 'Courier New', monospace; line-height: normal; font-size: 0px;">
                <div class="terminal xterm xterm-theme-default" tabindex="0" spellcheck="false">
                    <div class="xterm-rows">
                        <div>Microsoft&nbsp;Windows&nbsp;[Version&nbsp;10.0.10586]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                        <div>(c)&nbsp;2015&nbsp;Microsoft&nbsp;Corporation.&nbsp;All&nbsp;rights&nbsp;reserved.&nbsp;</div>
                        <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                        <div>C:\Users\myusername&gt;<span class="reverse-video terminal-cursor blinking">&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                        <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                        <!--another 10 lines full of spaces like previous line.-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="display: none; font-family: Consolas, 'Courier New', monospace; font-size: 0px; line-height: normal;">X</div>
</div>
```

**Comment by Tyriar** [comment]
You have `editor.fontSize: 0` in your settings, that's the issue. I fixed this a few days ago in Insiders, in the meantime use a different value for the font size. If you want the default just remove your custom `editor.fontSize`.
