### ISSUE TITLE
Multi-cursor move incorrect on the end

### ISSUE THREAD

**Issue by rihkddd** [microsoft/vscode#93554]
- VSCode Version:
1.43.2
- OS Version:
OSX 10.15.4
Steps to Reproduce:

1. multi select some character and some of the character located at line end.
![image](https://user-images.githubusercontent.com/2656576/77732073-1709f300-703f-11ea-8a81-2008d4d900e1.png)

2. type left key once, then you will find that the cursor at the line end moved two character. 
![image](https://user-images.githubusercontent.com/2656576/77732112-2852ff80-703f-11ea-87eb-0f475c345c49.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> No

Please disable extensions until you discover which one is causing this. Then report it to the associated repo.

/causeByExtension
