### ISSUE TITLE
Any real reason why it's so hard do a simple "helloworld" MFC app in VSCode?

### ISSUE THREAD

**Issue by ruifortes** [microsoft/vscode#93566]
Other than the auto generated UI code it's basically streamlining a bunch of configuration parameters isn't it?

https://github.com/microsoft/vscode-cpptools/issues/5207#issuecomment-604941271

PS: I'm using VSCode 1.43.2 on Windows 10

**Comment by sean-mcmanus** [comment]
This isn't really an issue with our extension. It's outside of our extension's scope. The correct team to reach out to would probably be the MFC team.
