### ISSUE TITLE
shift+alt+arrow not recorded correctly

### ISSUE THREAD

**Issue by YannickWidmer** [microsoft/vscode#93562]
- VSCode Version: 1.43.2
- OS Version: Windows 10 Version 1909, OS build 18363.720

Steps to Reproduce:

1. Go to File -> Preferences -> Keyboard Shortcuts
2. Record keys
3. press shift+alt+downArrow 
Expected result "shit+alt+down" appears 
Result "shift+alt+" appears
Doing the same on numpad the expected result happen.

Meaning pressing shift+alt+arrow works on every arrow and numpad arrow except downArrow and upNumpadArrow.

I have seen similar issues but no resolution.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sportshead** [comment]
Works for me.
Note: Using macOS, so may be a OS problem
![out](https://user-images.githubusercontent.com/32637656/77750037-0f0d7b80-705e-11ea-868c-c5a4a258fe49.gif)

**Comment by gjsjohnmurray** [comment]
Works for me
![image](https://user-images.githubusercontent.com/6726799/77750766-48bd9280-701c-11ea-9de2-40ba33ef0e24.png)

Maybe you have something else running that intercepts that key sequence before VS Code can see it.

**Comment by YannickWidmer** [comment]
Is there a way to trace on windows what intercepts key strokes?

**Comment by sandy081** [comment]
Also works for me. Please check if there is another application that is capturing this key.

@alexdima Any insights please?

**Comment by alexdima** [comment]
This means that the keybinding is not reaching VS Code, so the OS or some other application on the machine is eating it up before it reaches VS Code. I have heard (in rare cases) of broken keyboards which can behave like this as well.

All in all, there is nothing to be done on the side of VS Code if we do not receive a key bindings.

**Comment by YannickWidmer** [comment]
ok thanks
