### ISSUE TITLE
Unable to Close Split Editor without saving or cancelling a dirty file

### ISSUE THREAD

**Issue by kwg105** [Microsoft/vscode#9356]
- VSCode Version: 1.3.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open a File.  
2. Make revisions to the file.
3. Click the Split Editor (opening the file in two editors).
4. Close the the second Editor.
5. If you click "Don't Save" it loses the changes on the first window.
Need a way to close a panel without saving or cancelling a save.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8983
