### ISSUE TITLE
Import quickfix not provided if importing file open when vs starts

### ISSUE THREAD

**Issue by arogg** [microsoft/vscode#93563]
- VSCode Version: 1.43.2
- OS Version: win 10 version 1809

Steps to Reproduce:

Issue tested with **typescript 3.8.3** although the problem shows it is **actually a vs code problem**

1. create and open a new ts file in vs
2. close vs
3. open vs (the previously opened ts file should automatically open with vs too!!)
4. create and open a new ts file and write "export const myvar = 42;" in it, keep the other file open
5. switch to the first file and write "const myvar2 = myvar;" and notice that vs does NOT offer to import if you tell it to!!

**this problem does NOT occur if vs does NOT open with a file to begin with in step 3!!**

Does this issue occur when all extensions are disabled?: Yes

**Comment by sportshead** [comment]
I can reproduce this, but it WILL work if you create a `tsconfig.json` file as shown [here](https://code.visualstudio.com/docs/typescript/typescript-tutorial#_tsconfigjson).

**Comment by arogg** [comment]
I did not read that page, but as soon as you mentioned tsconfig.json, i changed

```
"include": [
    "src"
  ]
```

to

```
"include": [
    "src/**/*"
  ]
```

and it seems to work... Maybe vs should give a hint that not using globs can cause a big headache for the user.

**Comment by mjbvz** [comment]
Closing as a question / configuration issue. You can always use the `TypeScript: Go to project configuration` command to check if the current TS file is part of a tsconfig project

https://github.com/microsoft/TypeScript/issues/30623 should help alert to cases where no files are included in your tsconfig project
