### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by pratham280** [microsoft/vscode#93565]
Issue Type: <b>Bug</b>

The text appearing in the  application becomes blurry gradually and when hovered over the text it appears crystal clear

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.94GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-eslint|dba|2.1.1
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.5.0
python|ms-|2020.3.69010
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|4.0.1
vscodeintellicode|Vis|1.2.6

(1 theme extensions excluded)

</details>

**Comment by sportshead** [comment]
Can you add a screen shot?

**Comment by pratham280** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/62375936/77749534-30fc0380-7048-11ea-9307-0af57e2d93c1.png)

**Comment by sportshead** [comment]
Looks like a font problem, but I don't have a Windows computer so can't debug. Wait a while and someone else might be able to help you

**Comment by deepak1556** [comment]
@pratham280 is this no longer an issue ?
