### ISSUE TITLE
VueJS function properties referencing the data object breaks semantic highlighting

### ISSUE THREAD

**Issue by jonasnordlund** [microsoft/vscode#93571]
- VSCode Version: 1.43.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. In the VueJS function `created`, or any of your own within `methods`, use this code:

```js
created: function() {
    this.name = getUserName();
    // code...
}
```
2. The property name `created` will be highlighted as a class and conversion from a constructor function to a class will be suggested.

Workaround is to instead use this code:

```js
created: function() {
    var self = this; 
    self.name = getUserName();
}
```

This issue frequently arises within VueJS models since you are meant to access the state (the `data` object) via `this` besides in special cases like when the scope has changed and you have to use a variable `self` as above. For example, it just happened to one of my event handlers too.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Can you paste the whole file?

**Comment by jonasnordlund** [comment]
Here's a sample that has the problem:

```js
var app = new Vue({
    el: '#app',
    data: {
        id: 0,
    },

    created: function() {
        this.id = 42;
    }
});
```

I have a feeling it's because an assignment to `this` is assumed/expected to be due to a constructor function, and if it's the first thing to happen in a function call it's taken as being a constructor? It's just unfortunate that I have this be pretty commonplace in VueJS code where you interact with the data object so often in that way.

**Comment by aeschli** [comment]
Reproduced with
```
const x = {
  xy: function () {
    this.id = 42;
  }
}
```

The appearance of a `this` makes typescript thing this is a class.

![image](https://user-images.githubusercontent.com/6461412/81301366-41f15900-9079-11ea-95fb-47ae31998cd7.png)

**Comment by aeschli** [comment]
I created https://github.com/aeschli/typescript-vscode-sh-plugin/issues/15.
