### ISSUE TITLE
Terminal Split Action Icon is using css to rotate, should update codicon

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93576]
https://github.com/microsoft/vscode/pull/93440#discussion_r399230906

**Comment by Tyriar** [comment]
Also this only worked previously when the terminal was panel on the side. To verify test that the split terminal icon is correct in the following cases:

- Terminal in bottom panel
- Terminal in left panel
- Terminal in right panel
- Terminal in viewlet
