### ISSUE TITLE
VSCode Debug Issue

### ISSUE THREAD

**Issue by CARBON-LABS** [microsoft/vscode#93579]
When I use VSCode to debug a Rust program with external console, I find that external console window quit immediately after the process ended. This occurred so fast that I cannot see what the process outputs. I checked the launch.json file and cannot find someway to let the console pause after process quit such as that in Visual Studio.

**Comment by CARBON-LABS** [comment]
VSCode version 1.43.2
System Windows 10

**Comment by mjbvz** [comment]
Please start by filing this issue against the rust extension

**Comment by CARBON-LABS** [comment]
I have installed the Rust extension. That is not the problem! It is the problem of VSCode. I don't know how to keep external console displaying after running by setting launch.json file.


-------- 原始邮件 --------
发件人： Matt Bierner <notifications@github.com>
日期： 2020年3月28日周六 03:27
收件人： microsoft/vscode <vscode@noreply.github.com>
抄送： CARBON-LABS <jasminefsb@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [microsoft/vscode] VSCode Debug Issue (#93579)

Please start by filing this issue against the rust extension

―
