### ISSUE TITLE
Allow users to export, import their settings as a zip file

### ISSUE THREAD

**Issue by kaushalyap** [microsoft/vscode#93572]
Allow users to export, import their settings as a zip file.
ex: [Exporting / Importing settings in JetBrains IntelliJ IDEA](https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html#import-export-settings)

**Comment by kaushalyap** [comment]
Please **do not** close as duplicates, issues was opened according to the recommendation of @sandy081 as mentioned [here](https://github.com/microsoft/vscode/issues/2743#issuecomment-603660605)

> I would recommend to create separate issues for separate requirements. Those might get untracked otherwise. So, please create separate issues for your wishes.

**Comment by sandy081** [comment]
@kaushalyap Thanks for filing separate issue. I was not aware that there is an issue for this already. I reopened the original issue and close this one as duplicate.

**Comment by sandy081** [comment]
/duplicate

#2816
