### ISSUE TITLE
Undo multi cursor edit corrupts document

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93585]
Create a new document with the following content:

```
hello world
hello world
```

1. Place cursor on second `world` and press <kbd>Ctrl D</kbd> twice to have both occurrences of `world` selected.
2. Type `noooo`.
3. Undo

Document becomes:

```
hello world
heworldl oo
```

If you redo, you get:

```
hello no
ohoeoworlnoooo
```

The original document is completely lost.

**Comment by joaomoreno** [comment]
I hit this a few times this week.

**Comment by alexdima** [comment]
@joaomoreno I'm having trouble reproducing, is there something more to it?

![Kapture 2020-03-27 at 19 34 22](https://user-images.githubusercontent.com/5047891/77788686-00c15e80-7062-11ea-8170-b791f8d3b271.gif)

**Comment by joaomoreno** [comment]
Place the cursor on the **second** world. 👍
