### ISSUE TITLE
Reports that file is saved while it is not (remote location, sshfs)

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#9358]
- VSCode Version: Version 1.2.1 (1.2.1)
- OS Version: OS X El Capitan 10.11.5 (15F34)

Steps to Reproduce:

1. Mount remote harddrive with sshfs and name 'ma'
2. Open 'ma' in VS Code
3. Open a file in working files
4. Edit and save (black dot will show up and hide). Check with 'cat' that the saved version is the same as in Code.
5. Remove mount
6. Edit file and save (black dot will show up and hide)
7. Check with 'cat' that the saved version is older than in Code

**Comment by bpasero** [comment]
@pcherkasova We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
Please reopen if you can still reproduce with insiders release.
