### ISSUE TITLE
extensions doesn't install

### ISSUE THREAD

**Issue by sameh00alsharawy** [microsoft/vscode#93588]
Extensions: none
VS Code version : 1.43.0 (user setup)
operating system version: windows 10 pro
steps to produce :  
i just install VSCode and when i try to install an extension  it gives me an error message 'failed to install' , i am still new to programming.

also there is no graphics
![VSCode](https://user-images.githubusercontent.com/62762826/77780856-4cbdd480-705d-11ea-83ce-26cf80231805.jpg)

**Comment by gjsjohnmurray** [comment]
Are you connecting to the internet through a firewall or a proxy? See https://code.visualstudio.com/docs/setup/network for some information and troubleshooting links.

**Comment by Tyriar** [comment]
@JacksonKearl again the bot isn't closing the issue

**Comment by JacksonKearl** [comment]
@Tyriar I wouldn't expect bot to close this because last commenter is not a team member
