### ISSUE TITLE
Problems with terminal display

### ISSUE THREAD

**Issue by yuuxeun** [microsoft/vscode#93583]
- VSCode Version:1.43.2

- OS Version:win10 LTSC 1809（OS内部版本17763.1131）

Steps to Reproduce:

1.no Steps to Reproduce. It's just open like this
![image](https://user-images.githubusercontent.com/44895726/77776298-bdc6b180-7088-11ea-875d-b2fb50bb3fcd.png)
2.

Does this issue occur when all extensions are disabled?: Yes
YES

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
