### ISSUE TITLE
Emmet not working properly

### ISSUE THREAD

**Issue by abhinandhari** [microsoft/vscode#93582]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Bug</b>

Emmet not having all functions for html and jss

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.20.0
emmet-jss|car|1.0.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
c-cpp-compile-run|dan|1.0.7
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
python-extension-pack|don|1.6.0
prettier-vscode|esb|3.20.0
vscode-firefox-debug|fir|2.7.1
beautify|Hoo|1.5.0
MagicPython|mag|1.1.0
python|ms-|2020.3.69010
cpptools|ms-|0.26.3
debugger-for-chrome|msj|4.12.6
LiveServer|rit|5.6.1
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
quokka-vscode|Wal|1.0.284
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2
emmet-live|yse|1.0.0

</details>
.

**Comment by mjbvz** [comment]
Please share an example of the problem

**Comment by octref** [comment]
Please open a new issue by turning off all extensions and providing a repro case.
