### ISSUE TITLE
Go to File includes files from history

### ISSUE THREAD

**Issue by canemacchina** [microsoft/vscode#93580]
- VSCode Version: 1.43.2
- OS Version: MacOS Catalina 10.15.4

Steps to Reproduce:

1. add this settings to try to exclude files from quick open:
```js
"files.exclude": {
    "**/node_modules/**": true,
},
"search.quickOpen.includeHistory": false,
"task.quickOpen.history": 0
```
2. Open an excluded file using "Open File"
3. Close the file
4. Trigger quick open using cmd + p: recently opened file are suggested (but they disappear when I start writing), marked as `recently opened`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Yes, this setting is only for when you start searching, hence the name `search` in the setting.
