### ISSUE TITLE
Setting PowerShell version commandline switch fails

### ISSUE THREAD

**Issue by Chiliyago** [Microsoft/vscode#9359]
- VSCode Version: 1.3.1
- OS Version: Windows

Steps to Reproduce:

1. update settings.json to "terminal.integrated.shell.windows": "C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe -version '2.0'"
2. ctrl+` to open terminal.
3. Terminal Window crashes and goes away.

**Comment by Tyriar** [comment]
This is as designed, there is no `shellArgs` settings like on the other platforms due to an upstream issue #8429. You could try create a wrapper script that calls powershell.exe with the args to get around this.
