### ISSUE TITLE
VSCode URL Handler not working

### ISSUE THREAD

**Issue by ashot11091950** [microsoft/vscode#93594]
Issue Type: <b>Bug</b>

when I am trying to open file with a link it does not open (in Chrome)
link: 

> vscode://open?url=file:///var/www/index.html:0

with Firefox browser I have the option to choose URL handler and there are two options
- Visual Studio Code - URL Handler 
- VS Code URL Handler 

when choosing first option nothing happens, but with the second option it works,
in Google Chrome I haven't option to choose handler so I can't open files via links

![image](https://user-images.githubusercontent.com/40325246/77784655-50a92100-7074-11ea-885d-10dd7665d4e8.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2898)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (0.15GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
gitlens|eam|10.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
nodejs-module-snippet|gun|0.0.2
smarty|imp|0.3.0
vscode-php-getters-setters|php|1.2.3
vscode-xml|red|0.11.0
twig|wha|1.0.2

</details>

**Comment by joaomoreno** [comment]
Please select the second one and click `Remember my choice`.

**Comment by ashot11091950** [comment]
> Please select the second one and click `Remember my choice`.

@joaomoreno Did you read the description?? It is available only in Firefox. I can't do it in Chrome

**Comment by joaomoreno** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
