### ISSUE TITLE
Map-Type Setting Rendered as Header and List of Settings in Settings Editor UI

### ISSUE THREAD

**Issue by savannahostrowski** [microsoft/vscode#93598]
It would be great to have a map-type setting specified in settings.json rendered as a header and a list of name/descriptions and values in the Settings Editor UI.

### Example:
There is a setting called "someGlobalSetting", which is an object. Both the keys and values have a list of permissible values.

``` 
{
"lang.someCategory.someGlobalSetting”: {
      “someName”: “someValue”,
      “someOtherName”: “somevalue”,
        …
    }
}
```

In the Settings Editor UI, the user would see some header (“someGlobalSetting”) and underneath it, they would see the keys and values mapped as a name/description (key) and an input mechanism (to select the value) as a list. In this case, it would be ideal if the input mechanism could be a dropdown for each key, value pair given that there are a fixed set of permissible values.

So the user could see something like:

#### Some Global Setting
someName           _dropdown of permissible values_
someOtherName  _dropdown of permissible values_
...

**Comment by roblourens** [comment]
It's true that we don't get intellisense for the array control in the nice way that we do for the json editor. One possible issue with this approach is that you wouldn't control the order, is that a problem?

So then a generic control for a type like 

```json
"someSetting": {
  "hey": true,
  "there": false
}
```

might be better

**Comment by savannahostrowski** [comment]
@roblourens That's a good question and a good catch. In my particular case, having the ability to keep the settings in a consistent order would be nice.

**Comment by savannahostrowski** [comment]
@roblourens The requirements for this have changed. As such, I've updated this ticket.

**Comment by 9at8** [comment]
Tracking everything related to the new renderer in #99635

**Comment by roblourens** [comment]
Closed with https://github.com/microsoft/vscode/issues/99635
