### ISSUE TITLE
Child sessions that finish launching after their parent exits can break the debug UI

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93592]
See https://github.com/microsoft/vscode-js-debug/issues/390#issuecomment-605147836: You should be able to reproduce by following the verification instructions with a js-debug-nightly version <= 2020.3.2517

**Comment by isidorn** [comment]
I see you were deep debugging into this. Do you have a proposed solution? How should the VS Code UI behave?

**Comment by connor4312** [comment]
Perhaps two things:

- Double check the parent session after returning from initialize. Iff it's present and in `State.Inactive`, then terminate it and reject with a 'canceled' error

https://github.com/microsoft/vscode/blob/2d85caa55586161faad7ce7c54e7335d3f14ac97/src/vs/workbench/contrib/debug/browser/debugService.ts#L531

-  For the specific problem, it's probably safe to `ignoreErrors` in .expand. I see we do this elsewhere in the file. The set is cleared after that function runs, so ignoring problems here shouldn't have negative effects on state elsewhere.

https://github.com/microsoft/vscode/blob/52df5961f3e8bb669de34fd32ab1f9df25bec5e2/src/vs/workbench/contrib/debug/browser/callStackView.ts#L136

**Comment by isidorn** [comment]
These two are great proposals. I can look into them, thus assigning to March.
If you want a PR is also welcome, if not I will tackle on Monday.
