### ISSUE TITLE
Test: Terminal link handler API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93596]
Refs: https://github.com/microsoft/vscode/issues/91606

- [x] macOS @connor4312 
- [x] linux @roblourens
- [x] windows @JacksonKearl

Complexity: 2

---

There is a new extension API that enables listening for clicks on terminal links and handling them from an extension. To test, scaffold out an extension and try out the new API and validate its documentation.

This is likely to finalize next iteration.

**Comment by roblourens** [comment]
I'm curious what the Terminal object would be used for, which implementor will do something different depending on which terminal the link was clicked in?

**Comment by JacksonKearl** [comment]
Seems to work fine. Assuming extensions providing link detectors is somewhere on the backlog?

**Comment by connor4312** [comment]
> which implementor will do something different depending on which terminal the link was clicked in

In js-debug we only handle links that come from the debug temrinal

**Comment by Tyriar** [comment]
@JacksonKearl yes but it's blocked on adopting an early xterm.js API and not sure about the priority relative to everything else. https://github.com/microsoft/vscode/issues/91290
