### ISSUE TITLE
Source maps don't work when attaching to running code

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#936]
Using this config:

    "sourceMaps": true,
    "outDir": null

An application structure that looks like this:

    test/
        src/
            some-test.js
        dist/
            some-test.js   

`dist/some-test.js` contains inlined source generated by Babel with "inline" option (as the documentation indicates vscode does not support separate map files, and indeed trying to use source maps with a seprate file just says "can't find source map"):

    //#sourceMappingURL=data:application/json;base64,
    eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImlvYy5qcy    JdLCJuYW1lcyI6W10sIm1hcHBpbmdzI

... etc

Starting from command line:

    mocha --debug-brk dist/some-test.js

Attaching with vscode and `sourceMaps: true`, it displays the actual file `dist/some-test.js` which contains inlined source, and breaks on the wrong line too.

Attaching from vscode and `sourceMaps: false`, it displays the same file (as expected) and breaks on the correct line.

Is there any way to make source maps work when attaching to a running process?

**Comment by weinand** [comment]
@jamietre What part of the VSCode says that 'VS Code does not support separate map files'?
VS Code does support separate map files.

In your launch config set "outDir" to the project relative folder where babel generates the *.js and *.map.js files.

This launch config should work for attach:

```json
{
	"name": "Mocha Attach",
	"type": "node",
	"request": "attach",
	"port": 5858,
	"sourceMaps": true,
	"outDir": "./dist"
}
```

If you want to run mocha tests from within VS Code you do not have to "attach" VS Code. The following launch config should work:

```json
{
	"name": "Mocha",
	"type": "node",
	"request": "launch",
	"program": "/usr/local/bin/_mocha",
	"args": [ "src/some-test.js" ],
	"sourceMaps": true,
	"outDir": "./dist"
}
```

**Comment by weinand** [comment]
@jamietre please reopen if this doesn't work for you.

**Comment by jamietre** [comment]
Let me address each issue here. Also I am running on windows, the example you give for mocha is for a *nix OS so I just wanted to make that clear in case it matters for my problem.

#### what doesn't work

I made a screen capture of what is happening. Note that it's not the tests that are compiled. it's the code being tested. 

I am unsure of how the `outDir` relates to using source maps, particularly when attaching to a running process. The file being debugged could have nothing to do with the entry point of the application. The source map should tell the debugger everything it needs to know about the source code, and indeed other debuggers like chrome and node-inspector work fine with the same code.

In the example below, the entry point is not even compiled (the test file is just under `test/ioc-tests.js` but it refers to an ES6 file `dist/ioc.js` compiled from source `src/ioc.js`. Here's what's happening.

https://youtu.be/0Y-BWB--1qw

Note that when using inline source maps (the first try), it breaks in the compiled code, at the wrong place. When using separate source map files, it says "Source is not available"

Also note the same thing happens when I just run an actual node app (this is a module) directly through VSCode. I actually can't get source maps to work anywhere, in any circumstances, it's not just related to attaching.

##### reference for vscode source map support:

https://code.visualstudio.com/Docs/editor/debugging

> Source maps can be generated with two kinds of inlining:
>
> * Inlined source maps: the generated JavaScript file **contains the source map as a data URI** at the end (instead of referencing the source map through a file URI).
> * **Inlined source:**  the source map contains the original source (instead of referencing the source through a path).
>
> VS Code supports inlined source maps but **not inlined source**.

Perhaps I misunderstood this as far as separate file vs. inline source code - but I read this to mean that I need to have a data URI to be supported. The documentation could probably be clearer since you can the source map inined, or not, and you can have the source code as part of the source map, or not, so there are really more than 4 possible types of maps. Babel includes the source code in the maps. In any event it doesn't really matter, I can't make it work no matter what kind of source maps I generate.

#### Config for running mocha

The reason I am attaching to a process to run a mocha test is because it's pretty inconvenient to have to go and change the `launch.json` every single time I want to debug a specific test. It's much easier to just start whatever from the command line and attach to it. 

A future ehancement that I think would add a lot of value would be a config that uses a template and applies to any matched pattern, e.g. something like

{
    "path": "test/**/*.js",
    "program": "mocha"
}

Then you could ideally just right-click a file, and it could match a launch config based on the glob.

**Comment by jamietre** [comment]
Note: I do not have rights to reopen this issue, I believe since you closed it.

**Comment by weinand** [comment]
@jamietre yes, the documentation could explicitly state that non inlined source maps (separate source maps) are supported as well. But I was assuming that this is the default and I do not have to mention this. I will improve the doc.

"outDir" is used in VS Code if you want to set breakpoints in the source. In this case VSCode needs to know where the generated *.js files live.

Since source maps work for us (and most other users) just fine, let's find the reason why they are not working for you.
I suggest that you let babel create source maps as separate files and without inlined source. In this case the source map lives next to the generated *.js file.
In the source maps the "sources" array should contain relative paths of the form "../src/some-test.js" and "sourceRoot" should be the empty string "". Is this the case?

**Comment by jamietre** [comment]
OK - so if I understand what this means is VsCode requires `sources` and will ignore `sourcesContent`?

Anyway - this seems to be an issue with my compilation pipeline. (facepalm) When I manually doctor the source map, it works. I just migrated this app to version 6... coincident with using VS code for the first time. When I said other debuggers were working, it didn't occur to me that they were working *before I updated*. Something in my pipeline is not respecting any of the source map directives other than `sourceMap`. I didn't look carefully enough at the output before complaining here. I am guessing there's a problem with gulp-babel version 6, or I just did something stupid.

Interestingly I have to remove the  `"sourceRoot"` definition, or it breaks on the wrong line. 

This works:

    {"version":3,
    "sources":["../src/ioc.js"],
    "names":[],
    "file":"ioc.js",

This breaks on the wrong lins:

    {"version":3,
    "sources":["../src/ioc.js"],
    "names":[],
    "file":"ioc.js",
    "sourceRoot":"../src/",

This is what babel was generating. 

    {"version":3,
    "sources":["ioc.js"],
    "names":[],
    "file":"ioc.js",
    "sourceRoot":"/source/",

No idea where it's getting "/source" from. This all worked fine prior to 6.

**Comment by weinand** [comment]
@jamietre yes, VSCode ignores the sourcesContent (for now) because it does not make much sense to use the embedded and readonly source from the sourceMap if you have the real source available in your VS Code workspace (where you can edit and compile it).

Usually the optional "sourceRoot" is the extracted common prefix of all paths in the "sources" array (to save space). So it is prepended to all paths from "sources". In most cases I've seen it to be the empty string or non existent (your first case). The second case looks already broken because sourceRoot looks like a common prefix but it is not removed from the path from "sources".  And the third case looks strange because sourceRoot is absolute (starts with a slash). This is always a problem because it makes the source map location dependent.

**Comment by jamietre** [comment]
Just a post mortem for anyone who happens to have the same issue.. the problem is entire config. Everything worked for me in other debuggers because they support inline source maps. When switching to external sources, `gulp-sourcemaps` has two issues

1. It defaults `sourceRoot` to "/sources/" which of course breaks everthing unless you happen to have your source in some file system rooted path "sources"

2. If all your source files are in the same level of a folder heirarchy, you can fix things by setting `"sourceRoot": "../src"` (or whatever) but this won't work for child folders, e.g.

    src
        util
            helper.js
    dist
        util
            helper.js

.. the source map for `dist/util/helper.js` won't be found because its relative path is different than the single `sourceRoot`.

There seem to be some pull requests in `gulp-sourcemaps` related to this but the repo owner has not commented so there may be no good public solution right now to using this structure & gulp-babel.

**Comment by nicky-lenaers** [comment]
I'm experiencing the same issue, where setting a breakpoint in my compiled files makes the red dot *jump* to the line where the content is in my source files, but these lines do not match 1 to 1 (e.g. my source files contain comments, my compiled files don't).

I tried the above solution by setting ``sourceRoot`` but it didn't change anything for me.

**Comment by jamietre** [comment]
The setting `sourceRoot` is for `gulp-sourcemaps` just to be clear.If you are using gulp to transform you probably have a script that looks like this

    gulp.src("src/**/*.js")
        .pipe(sourcemaps.init()) 
        .pipe(sourcemaps.write()
        .pipe(gulp.dest("dist"))

.. or thereabouts, the option would be added to 

        .pipe(sourcemaps.write({ sourceRoot: "../src" })

But again this will only work for trivial cases, if you have files in a child directory of `src`, it won't work.

I forked gulp-sourcemaps and have basically fixed the problem if you want to try it:

https://github.com/jamietre/gulp-sourcemaps

The change requires a new option `outputPath` that lets it know how to find the relative path from the source map to the source file, if your source maps are written alongside the compiled files, then it would just be the same as you pass to `gulp.dest`.

Works for me - not heavily tested though I did add unit tests - give it a shot if you like. I am not optimistic that `gulp-sourcemaps` itself will get fixed since there are stale pull requests that seem related to this, so I might publish to npm after road testing a bit.

**Comment by smithgeek** [comment]
Another option that worked for me is to use a function and return the absolute path to your source directory for every file.

```
sourceRoot: function(file){
    return file.cwd + '/src';
}
```
file.cwd should be the root directory of your project and then just append the source directory to it. At least for me it worked for files in nested directories as well. Not ideal but something that works with the existing sourcemaps repo.

**Comment by barake** [comment]
I was able to take the solution provided by @smithgeek and tweak it to generate working relative paths:
```
sourceRoot: function (file) {
    return path.relative(file.relative, path.join(file.cwd, 'src'));
}
```
Modify the `path.join` call to point to your source directory in the workspace.

**Comment by westy92** [comment]
Expanding on @barake's solution, this one works for me without hardcoding the source directory.

```js
sourceRoot: function (file) {
  return path.relative(path.join(file.cwd, file.path), file.base);
}
```

**Comment by Izhaki** [comment]
@westy92 solution work for me for debugging, but messed up the sourcemaps in the browser.

Here's a solution that works for both, albeit the specifics will vary per project: https://github.com/Microsoft/vscode-chrome-debug/issues/75#issuecomment-329187580
