### ISSUE TITLE
CSS Lint: expected property value - allow to add custom list of valid values/patterns

### ISSUE THREAD

**Issue by gaurav5430** [microsoft/vscode#93603]
I am using postcss simple variables in my project. 
I am using those variables as css property values.

The problem is that vscode css linting shows an error when i try to use those variables, and after that line css intellisense stops working.

I don't know if there is currently a way to make vscode to just ignore these property values, instead of trying to lint them.
I can turn csslint off, and intellisense still works, but then none of the css lint validations work.

As a start, it would make a lot of sense to allow user to add a list of property values, which should be considered valid property values or valid strings in property values.

For example:
something like `css.lint.validPropertyValues = ['$color-blue']`

and this wouldn't throw a lint error anymore:
`border-color: $color-blue`

or maybe allow adding patterns like `css.lint.validPropertyPatterns: ['$']`
now any property value starting with $ can be considered valid

**Comment by octref** [comment]
We only support standard CSS. PostCSS gives you infinite flexibility and we can't support all syntaxes.

**Comment by gaurav5430** [comment]
I understand.

This proposal is not about adding support for postcss though, it is more about allowing to add custom ignore rules to the css linter. I am not expecting vscode to fill in the values for postcss variables, just expecting the linter to not fail on them, so that I can still have intellisense/autocomplete working after using these values.

**Comment by octref** [comment]
However the parser can only handle known syntax. PostCSS gives you a way to extend CSS syntax so we can't have a parser that can always handle all cases.

**Comment by gaurav5430** [comment]
Ok, let's ignore postcss for a moment.

I think what I am talking about here is to have a way to ignore certain strings/patterns as invalid values in css lint validation, so that the lint does not fail and intellisense works alright on the following lines

**Comment by octref** [comment]
Our CSS parser is not as flexible. If you just want dollar sign to be valid and auto completion to continue to work, you can use `files.associations` to mark it as SCSS.

**Comment by gaurav5430** [comment]
That's actually not a bad solution for the problem at hand. Thanks.
Just that I can't find a setting to only change `files.associations `for css files to be scss in a particular project.

It seems that the setting is either globally applied, or can be applied per file, once.

**Comment by octref** [comment]
I believe `files.associations` take absolute path, so let's say your project name is `happy_cow`, try to use `/**/happy_cow/**/*.css` etc as a workspace level setting so it won't apply globally.
