### ISSUE TITLE
Expose webview URI

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#93608]
I am writing an extension. When I invoke a command via the `editor/title` contribution, the command is called with an argument.

[Contributions](https://code.visualstudio.com/api/references/contribution-points#menu-example)
> Note: When a command is invoked from a (context) menu, VS Code tries to infer the currently selected resource and passes that as a parameter when invoking the command.

When the editor is a webview, the argument is:
```javascript
Object
    $mid:1
    external:"webview-panel:webview-panel/webview-9dbc5868-4738-4397-81ef-a75013fcf7f9"
    path:"webview-panel/webview-9dbc5868-4738-4397-81ef-a75013fcf7f9"
    scheme:"webview-panel"
```

Now what am I supposed to do with this argument - how can I know which webview was active when my user clicked on the `editor/title` contribution?

Several options
1. Use`vscode.WebviewPanel._handle`.
In this case, it's `"9dbc5868-4738-4397-81ef-a75013fcf7f9"`.
Could work, but since it is a private field, I would rely on implementation details.
2. Constantly keep a reference to the currently active editor by listening to `onDidChangeViewState`
3. When the command is run, loop on all webviews I created, and select the one whose `active` flag is true.

Perhaps the type of the argument could also be documented

Do you recommend using `_handle` or would it be preferable for you to expose the URI?
Thanks!

**Comment by mjbvz** [comment]
Option 2 or 3  are the recommended approaches and is what our built-in webview extensions do. The `webview-panel` uri passed to commands lets you know that some webview is active but we don't provide a builtin api to know which one is active
