### ISSUE TITLE
Notebook: Change last cell kind scrolls the editor to top

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#93600]
Issue Type: <b>Bug</b>

* Create multiple cells in a notebook, make sure that the height of the document is larger than the viewport
* Scroll the last cell to the center of the viewport (make sure that the first cell is invisible)
* Add a new code cell below
* Escape to move the focus to the cell container
* Press 'm' to conver it to code cell

The cell should be converted to a code cell but currently the editor scrolls to the very top (`scrollTop = 0`).

VS Code version: Code - Insiders 1.44.0-insider (6cf3dd97465b2f4f666b66758991d720e003b0f4, 2020-03-27T05:28:16.333Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.73GB free)|
|Process Argv|-psn_0_1335622|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
vscode-pull-request-github-insiders|Git|2020.3.35461
vscode-language-pack-zh-hans|MS-|1.44.0
remote-ssh-edit-nightly|ms-|2020.3.38340
remote-ssh-nightly|ms-|2020.3.38340
js-debug-nightly|ms-|2020.3.1617
vsliveshare|ms-|1.0.1847
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8

(4 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
> Press 'm' to conver it to code cell
I don't see anything happen when I press m at this point. Nothing is converted into anything. However, it also doesn't scroll to the top.
