### ISSUE TITLE
Extension Authors Call for March 2020

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#93604]
Refs: #91714

Here is the rough plan for our extension authors call for **March**. The call will be on **April 7th**. The theme of this first call is "ice-breaker" 😄 

### Agenda
- [_~20 mins_] Introductions — we are planning on having ~6 community members and we want to hear about yourselves and your extension(s)
- [_~40 mins_] Discussions of each member's answers to "If you had 2 wishes to change/fix/improve VS Code and the marketplace, what would they be and why?", and also 1-2 (smaller) quality-of-life improvement items

### Participants
Since we want a small set of participants to facilitate richer and more effective communication, we are asking everyone who is interested in participating to fill out the sign up link below:

~~[Sign up to participate](https://www.surveymonkey.com/r/J5JLNHM)~~ *Sign-ups are over for this month's call*

Sign-ups will end on **April 1st**. After which, we will reach out and confirm the set of authors who will be participating in the call, and will update this post with the final list.

### Logistics
On **April 7th** at 9am PT (12pm ET), via a MS Teams call. Unfortunately, for this first call, we won't have a live stream setup for the broader community to join in and comment, but we will post a link to the recorded video at the end of the call. We are definitely looking into getting a live stream setup for future calls.

**Comment by eamodio** [comment]
The call will be held on **April 7th** (tomorrow) at **9 am Pacific Time**.

So far we will have the following participating extension authors:
- David Anthoff ([Julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia))
- Tyler Leonhardt ([PowerShell](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell))
- Taras Novak ([Data visualization extensions](https://marketplace.visualstudio.com/publishers/RandomFractalsInc)
- Peter Pezaris ([CodeStream](https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream))

**Comment by eamodio** [comment]
Thank you to everyone who participated in this first call!

### Video
[![](https://img.youtube.com/vi/-W6LViQaNco/maxresdefault.jpg)](https://www.youtube.com/watch?v=-W6LViQaNco)

### Participants
- David Anthoff ([Julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia))
- Caleb Collins-Parks ([AREPL for python](https://marketplace.visualstudio.com/items?itemName=almenon.arepl), and [more](https://marketplace.visualstudio.com/publishers/almenon))
- Alessandro Fragnani ([Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager), [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks), and [more](https://marketplace.visualstudio.com/publishers/alefragnani))
- Tyler Leonhardt ([PowerShell](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell))
- Taras Novak ([Data Preview](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview) and [more](https://marketplace.visualstudio.com/publishers/RandomFractalsInc))
- Peter Pezaris ([CodeStream](https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream))
- Yuki Ueda ([R](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r) and [more](https://marketplace.visualstudio.com/publishers/Ikuyadeu))

### Issues

Here are the issues tracking the features, bugs, etc that came up during the call.

- Pre-release extension support in the marketplace — https://github.com/microsoft/vscode/issues/15756
- Webviews in the sidebar — https://github.com/microsoft/vscode/issues/83911
- Pinned tabs — https://github.com/microsoft/vscode/issues/12622
- Hover/Clickable gutters — https://github.com/microsoft/vscode/issues/47559, https://github.com/microsoft/vscode/issues/28080
- Create a data science "working group" — https://github.com/microsoft/vscode/issues/94740
- Provide UI component toolkit — https://github.com/microsoft/vscode/issues/94741
- :bug: Funny behavior between auto-closing pairs and snippets https://github.com/microsoft/vscode/issues/58619
- Unit testing extensions is quite difficult — #94746
- Provide a telemetry story for extensions — #94748 
- Allow extensions to contribute to the VS Code welcome page — #94750
- Provide linting for extension APIs — #94751

#### Marketplace
- Dashboard stats — https://github.com/microsoft/vscode/issues/94744
- Reviews & ratings — https://github.com/microsoft/vscode/issues/92377, https://github.com/microsoft/vscode/issues/94743
- Update featured extensions more often — #94745

#### Documentation
- Provide "links" from our extension API docs to sample usage — #94747

Looking forward to next month!

P.S Extension authors — join our community run [VS Code Developer Community Slack](https://aka.ms/vscode-dev-community) 😄

**Comment by ppezaris** [comment]
Thanks to @eamodio and team for hosting! It was a fun and productive conversation. Glad to be a part of it.

**Comment by alefragnani** [comment]
Yeah, it was a great event! Looking forward the next one.

**Comment by alefragnani** [comment]
@eamodio ,

Another issue to link to the topic "Hover/Clickable gutters" is https://github.com/microsoft/vscode/issues/5455. I created it sometime ago 😬 

Thank you

**Comment by ppezaris** [comment]
@eamodio it would be awesome to be able to "close the loop" and be able to track the issues that were raised in this call, to be able to judge the effectiveness of the meetings and whether they were able to bring attention to the critical issues facing extension authors.

**Comment by idoprz** [comment]
Is there any call in May? Will be happy to participate in.

**Comment by eamodio** [comment]
@ppezaris All of the issues raised in the call are tracked above, each linked to their own issue -- so you can definitely track them there. As for any more "closing of the loop", what would you be looking for?

@idoprz Sign up here for the April call: https://github.com/microsoft/vscode/issues/96927

**Comment by ppezaris** [comment]
The call was great -- don't get me wrong -- but my hope coming out of that meeting was that there would be an outcome that had more teeth than "we made a list of the issues raised."

For example, if there was any discussion or activity within the vscode team about the call, and if the discussion had a positive impact on planning or prioritization, it would be great to surface that information somehow, as a positive reinforcement loop.

If on the other hand the purpose of the meeting is to just create another list of issues, that's cool too -- but I guess I was hoping that something more concrete would come out of it.

**Comment by eamodio** [comment]
While I can't really offer any concrete "teeth" outside of tracking issues and championing them -- which I am definitely doing. At the same time, I believe I can confidently say that the call has definitely had an impact on planning.

For example, the following are all in-progress in one stage or another (some in spec/planning, others in implementation)
- Dashboard stats — #94744
- Pre-release extension support in the marketplace — #15756
- Pinned tabs — #12622
- Provide UI component toolkit — #94741

And all of the other issues have been raised up and reviewed.

To be clear, I don't want "just another list of issues" — I want to create a space where we can hear/see/feel what the community really wants or needs. Hopefully, that will help foster more internal champions and influence planning and direction. I also want to put people and faces to the issues, to "feel" the pain/wants/needs more acutely than in an textual issue -- to help foster a better richer community. On that point, we had other members of the VS Code team listening into the call (and I'm sure others watched it after the fact), as well as members from the marketplace team.

Although, at the same time, just because the community wants or needs something doesn't make it happen (or happen quickly even if we agree), it has to align with team goals, priorities, effort, etc. But the better we understand (truly understand) the needs and wants of the community we will be much better equipped to help provide them.

I would also point back the goals of these calls outlined here: #91714. The above is one of the main goals, while the other is early feedback on proposed APIs. And this next call (#96927) will be diving into some of that.

I hope that makes sense and helps.

**Comment by prashantvc** [comment]
We have enabled the basic stats report for the extension authors on the VS Marketplace.
You can access it from the extension's `More Actions...` menu

<img width="592" alt="PNG image" src="https://user-images.githubusercontent.com/328076/81797980-17961480-952d-11ea-84d5-772e591566c9.png">

We will evolve the report based on the community feedback. Please give it a try and share your feedback
