### ISSUE TITLE
Open File explorer search doesn't include files in subdirectories

### ISSUE THREAD

**Issue by glarue** [microsoft/vscode#93615]
Issue Type: <b>Bug</b>

1. File > Open File (or ctrl + o)
2. Move to directory with subdirectory containing file of interest (FOI)
3. ctrl + f > partial name of FOI

Previously, this type of search from a parent directory would return results from all (afaik) child directories, but this now does not seem to be the case.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.5.8-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2709)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|15.40GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
open-html-in-browser|cod|0.1.21
vscode-markdownlint|Dav|0.34.0
vscode-html-css|ecm|0.2.3
python|ms-|2020.3.69010
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
markdown-pdf|yza|1.4.4

(3 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you please post a screenshot? I am not sure what exact search feature you are talking about. Thanks

**Comment by glarue** [comment]
@isidorn sure thing, here is a quick gif showing the behavior. In it, I am attempting to open the file `test_sub_script.py` in the subdirectory `subdir`. Previously, selecting "Open File" and then performing a search with ctrl-f (or simply typing a partial filename) would return all matching files in all subdirectories of the starting directory, but this appear to no longer work.

![Peek 2020-03-30 12-30](https://user-images.githubusercontent.com/6827531/77953547-583e1500-7282-11ea-8bd5-d47559d2c364.gif)

**Comment by isidorn** [comment]
This is a native dialog, whic I believe is controlled by your linux distrubtion and VS Code can not control it. Though forwarding to @deepak1556 as this might be electron specific. Though I think it is just native dialogs

**Comment by glarue** [comment]
@isidorn thanks, and sorry for the trouble. @deepak1556 if it helps, the file manager for my system is `Thunar 1.8.14-1`

**Comment by deepak1556** [comment]
As @isidorn suggested this is definitely an issue with the file manager, as I see things work fine with nautilus. But you can see if the issue repros with chromium or any other gui applications ?

Also I am having trouble setting up thunar on my system, it would help if you can run the following gist https://gist.github.com/deepak1556/8756c593cda34a102095f87f7aa8b066 with https://github.com/electron/fiddle/releases/tag/v0.14.0 and see if the issue repros. Thanks!

**Comment by glarue** [comment]
> as I see things work fine with nautilus.
I also have Nemo installed (which _does_ have built-in recursive search), and from what I can see Thunar has never had this, which leads me to believe somehow Nemo used to be the file manager requested for the Open File dialog. I don't see why this would have changed, however, as Thunar has been the default on my system the whole time.

It seems that there is at least one other related issue, or at least an issue that would presumably address this behavior: https://github.com/microsoft/vscode/issues/50386

Finally yes, can confirm that the issue repros w/ that gist via Fiddle.

**Comment by deepak1556** [comment]
@glarue thanks for investigating a bit more! you are correct and that would be reason for my issue with running thunar on my system.

There is a stalled PR in electron to address this https://github.com/electron/electron/pull/19159 . I will see if it can be merged in next iteration.
