### ISSUE TITLE
Notebook document metadata: optional execution count

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#93618]
Issue Type: <b>Feature Request</b>

Currently we always the execution count placeholder `[ ]` when a cell is not focused/hovered, and switch to a play button when it's focused/hovered. However for GitHub issues notebook, the execution count doesn't matter at all, you can declare a macro in one cell and use it in another cell, the second cell doesn't depend on the first cell being executed.

My proposal is having a document level metadata to control if `execution_count` will be ever set. If no, then we don't show the `[ ]` placeholder.

VS Code version: Code - OSS Dev 1.44.0 (Commit unknown, Date unknown)
OS version: Darwin x64 19.2.0

**Comment by roblourens** [comment]
Could also just not show `[  ]` when executionOrder is undefined, then that notebook could never set it. I don't know if the placeholder brackets are that helpful
