### ISSUE TITLE
Wrong file count

### ISSUE THREAD

**Issue by unional** [microsoft/vscode#93627]
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

The file count is off.

You can see in the screenshot that no file is opened but there is one unsaved
![image](https://user-images.githubusercontent.com/3254987/77813169-a0332100-7063-11ea-8111-c41088706211.png)

Just reporting, because it is likely not easy to reproduce.

**Comment by bpasero** [comment]
I am quite sure this is the same underlying issue that was fixed with https://github.com/microsoft/vscode/commit/305fbc16388bda35c09fec258865bbdbd25b7485.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by unional** [comment]
Very likely that is the case. I do recall there was an unsaved file opened.

Closing for now, as this is likely not reproducible. I can't reproduce it again with a few try.
