### ISSUE TITLE
Option for the default Explorer viewlet to open

### ISSUE THREAD

**Issue by wdscxsj** [microsoft/vscode#93629]
VSCode has amazing folder/project support, but oftentimes it's only used as a powerful text editor. That is, drag files in, do some editing (maybe with the help of Outline), and close all. User focus is on the files, but the 2 big blue buttons, Open Folder, Clone Repository, look so distracting. It costs 2 clicks to hide Folder and expand Outline.

So why not:

- Add an option for the default Explorer viewlet to open? `"telemetry.experiments.showDefaultViewlet": false` just hides the sidebar.
- Or, remember the last global choice? This seems to work in simple cases, but fails after using a folder/project or a Remote connection.
- Or, simply open the topmost viewlet in Explorer as default? This doesn't work by now.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

@bpasero didn't we have some setting to control what happens when a new window is opened?

**Comment by wdscxsj** [comment]
@isidorn Thanks for your response!

**Comment by bpasero** [comment]
Not sure, I don't think so.

For me the explorer is not visible when I open empty windows at least:

![image](https://user-images.githubusercontent.com/900690/77913798-339f6880-7295-11ea-85c7-3911e20dada5.png)

**Comment by wdscxsj** [comment]
> For me the explorer is not visible when I open empty windows at least

That's often because the sidebar was shut when you last quit VSCode. The sidebar remembers its last appearance in simple cases (like whether it's shut), but not very precisely (see my examples above), and not quite configurable.
