### ISSUE TITLE
Wrong column number detected when custom tab size is set

### ISSUE THREAD

**Issue by shaqque** [microsoft/vscode#93626]
- VSCode Version: 1.43.2
- OS Version: Darwin x64 19.3.0 (MacOS Catalina 10.15.3)

Steps to Reproduce:

1. Set "Editor: Tab Size" to be 4 in settings, and add 
    ```
    "[c]": {
       "editor.tabSize": 8
      },
    "editor.tabSize": 4,
    "editor.detectIndentation": false,
    ```
    to settings.json.
2. Make a line with >80 characters in a C file, including the number of spaces in a tab.
![image](https://user-images.githubusercontent.com/20341447/77812861-855fad00-7061-11ea-9220-e976e91926fa.png)
3. Hit the lower right "Go to line" button. The column number listed on the button does not match the one on top (81 vs 74).
![image](https://user-images.githubusercontent.com/20341447/77812915-f69f6000-7061-11ea-8ad3-c8aa273fe73e.png)

I'm mainly concerned about this because I think VSCode is detecting the line to have 77 characters instead of 81, so the C/C++ extension does not automatically wrap the line with clang-format because it doesn't detect that the line went over 80 characters.

**Comment by alexdima** [comment]
@shaqque The quick pick allows to pick a line;char position to go to, while the status bar renders a the current unicode character count, except for tabs, which are counted as the count of spaces to the next tab stop. I will make a change to the status bar message to clarify that they are not the same.

**Comment by alexdima** [comment]
To verify, open an empty file with one tab character and place the cursor after the tab character:

![image](https://user-images.githubusercontent.com/5047891/77899464-047cfd00-727d-11ea-982e-5cf261c2d3b6.png)
