### ISSUE TITLE
Menu bar's menu flashing

### ISSUE THREAD

**Issue by augustine98** [microsoft/vscode#93623]
Issue Type: <b>Bug</b>

I installed a dark theme on GNOME and all the menus in the menubar flash when the cursor is hovered over.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.5.10-200.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2818)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.45GB (4.27GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
solidity|Jua|0.0.71
cpptools|ms-|0.26.3
material-icon-theme|PKi|4.0.1
material-theme|zhu|3.2.4

(3 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
Does this reproduce with GPU acceleration disabled? https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by deepak1556** [comment]
Also does this happen with `window.titleBarStyle: custom` ?
