### ISSUE TITLE
Exhaustive variable substitutions

### ISSUE THREAD

**Issue by KingOfDuck** [microsoft/vscode#93628]
I was finding that custom settings can be defined in the workspace configuration file, but variabels substitution seems to be not recursive. Ive created a task like this in task.json:
```
        {
            "label": "echo",
            "type": "shell",
            "command": "echo ${config:myvar}",
        }
```
and added this in .code-workspace file:
```

	"settings": {
        ...
		"myvar2":"123",
		"myvar1":"${config:myvar2}",
		"myvar":"${config:myvar1}",
        ...
```
and running it shows
```
```
NOTHING.

If I change the task command as
```
            "command": "echo ${config:myvar1}",
```
or
```
            "command": "echo ${config:myvar2}",
```
then it will correctlly show
```
123
```
Are there any way to solve this problem? Cause I wanna make complex configurations for the project.

**Comment by alexr00** [comment]
@KingOfDuck this is by design as our goal with variable substitution isn't to create a complete programming language with recursive substitution but instead allow for simple substitutions.
