### ISSUE TITLE
Syntax highlighting doesn't update correctly after inserting a line

### ISSUE THREAD

**Issue by trevyn** [microsoft/vscode#93624]
Issue Type: <b>Bug</b>

![Screen Shot 2020-03-28 at 4 36 31 AM](https://user-images.githubusercontent.com/230691/77810667-1741d700-70af-11ea-9214-a4c0bf48e408.png)

Everything is fine, then I hit return to insert a new line, and the syntax highlighting goes all crazy:

![Screen Shot 2020-03-28 at 4 37 09 AM](https://user-images.githubusercontent.com/230691/77810638-f11c3700-70ae-11ea-985e-20e74134ed3c.png)

This only happens with the `vscode-clangd` extension (which for some reason isn't showing in the auto-report below, but is installed and functioning.), but since `Inspect Editor Tokens and Scopes` is showing the correct value, this appears to be a VS Code issue too.

Reloading the window fixes the problem until I hit return again. I tried disabling all extensions other than `vscode-clang`, and the problem remains.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.1
rust-analyzer|mat|0.3.105-nightly
vscode-versionlens|pfl|0.25.0
crates|ser|0.4.9
tabnine-vscode|Tab|2.5.2

</details>

![Screen Shot 2020-03-28 at 4 49 07 AM](https://user-images.githubusercontent.com/230691/77810726-828ba900-70af-11ea-8356-0b80a27a5915.png)

**Comment by trevyn** [comment]
Related: https://github.com/clangd/clangd/issues/232 , https://github.com/clangd/clangd/issues/210

**Comment by trevyn** [comment]
Ok, as mentioned in https://github.com/clangd/clangd/issues/232 above, this does work with clangd 10, though interestingly, VS Code still shows a glitch of the incorrect highlight colors, and then quickly resolves to the correct highlighting.

**Comment by alexdima** [comment]
IMHO this is an issue with the clang extension. Please reach out to that extension if there is still an issue, and they can investigate and report an issue to us if there is a problem with VS Code.

But given the issues you have linked, this appears to be a problem with the clang extension.
