### ISSUE TITLE
[cli] RFE: Opening file.go:47 should go to line 47 automatically

### ISSUE THREAD

**Issue by VojtechVitek** [Microsoft/vscode#9363]
Opening file from terminal using `$ code -r ./file.go:47` should go to line 47 automatically.

This feature would be much appreciated when developing on Linux / Mac OS X. Most modern IDEs (incl. Atom and SublimeText) can do this too.

**Comment by weinand** [comment]
@VojtechVitek `code --help` is your friend: use `-g` instead of `-r`

**Comment by VojtechVitek** [comment]
@weinand thank you, it really works.

btw: It's not very clear from the other sources / documentation that there's a `-g` option.

**Comment by VojtechVitek** [comment]
@weinand this should be default behavior, though. What do you think?

**Comment by weinand** [comment]
@VojtechVitek what do you mean by 'default behaviour'?

**Comment by VojtechVitek** [comment]
@weinand By default behavior I meant that `$ code ./file.go` should always try to append to the existing window and go to the provided line (ie. `-r` and `-g` options should be enabled by default).

Right now, when I CMD+click any filepath (ie. `./dir/file.go:47`) in the terminal (this is a feature of iTerm2 for example), it does not jump to the line 47 but it stays on the top of the document, which is unfortunate. Both Atom and SublimeText jump to the specified line by default.

**Comment by VojtechVitek** [comment]
For the time being, I will solve this by `alias code='code -r -g '`.

**Comment by bpasero** [comment]
We settled on the explicit -g option because we do not want to add any magic by looking into the file name and make a decision based on that (colon is a valid file name if you want to).
