### ISSUE TITLE
Javascript formatter conflict

### ISSUE THREAD

**Issue by jluisgarcia** [microsoft/vscode#93633]
- VSCode Version: 1.43.2
- OS Version: Ubuntu 18.04.4 LTS

Steps to Reproduce:

   I found out by chance that VScode uses two naming options [js] [javascript] when it comes to 
  Javascript default formatter.
    
```
  "[js]": {
       "editor.defaultFormatter": "HookyQR.beautify"
    },
  "[javascript]": {
       "editor.defaultFormatter": "chenxsan.vscode-standardjs"
   },
```

  The problem is when you don't know this beforehand and you have a long **settings.json** file.
  You might run into issues as I did and could take a while to know why.

 Because I believe repeated keys are not allowed by default in **settings.json** . At least, I get a 
 warning. But when you have two keys for the same setting, there is no warning.

 Is it possible to have only one option?

**Comment by sandy081** [comment]
Its not coming from VS Code out of the box. You might have two different java script extensions with different language ids. Please check your installed extensions contributions page and see if there are extensions contributing `js` language

**Comment by jluisgarcia** [comment]
Yes, more than one. I thought this IDs could be restricted inside VScode. If not, that's it. No more questions.
Thanks

**Comment by sandy081** [comment]
Not sure what you meant by restricting language IDs. VS Code internally does not know about any language, this knowledge comes from extensions. So it cannot associate.
