### ISSUE TITLE
Ignored Sync icon is not aligned 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93638]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/10746682/77820974-a9b19d00-70e6-11ea-89b1-1f9b3b69a2c7.png">

- Also, given the real estate constraints, is not it enough to just show the icon? 
- Icon is not shown in the editor

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/10746682/77821014-057c2600-70e7-11ea-85c6-16241b63594e.png">

@misolori FYI

**Comment by roblourens** [comment]
The gear icon is already shifted down by a bit, I think that is by design? 

![image](https://user-images.githubusercontent.com/323878/77832788-c6090600-70f5-11ea-8258-8660ee082e5e.png)

**Comment by sandy081** [comment]
You are right. I can look into that. 

Can you please add the ignore label also to extension editor?

**Comment by sandy081** [comment]
Closing this and reopening the main issue.
