### ISSUE TITLE
Quick access: editor picker

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93637]
Refs: https://github.com/microsoft/vscode/issues/69955

- [x] anyOS @Tyriar
- [x] anyOS @alexdima

Complexity: 3

---

Quick open is now using the quick input widget that leverages our new tree widget. All quick open providers have been rewritten from scratch. 

All of the existing commands for driving quick open have been preserved. Everything should work as before with some additional features as noted in the test plan. 

**Note:** configure `"workbench.quickOpen.closeOnFocusLost": false` to make testing easier by keeping quick open opened even if you navigate somewhere else.

* open a couple of editors in multiple editor groups
* have some dirty, have some in preview
* verify the editor picker `edt ` shows all opened editors across all groups by appearance
* verify the editor picker `edt active` shows all opened editors of the currently active group by most recently used
* verify the editor picker `edt mru` shows all opened editors across all groups by most recently used
* verify you can pick an editor to open it
* verify you can pick an editor in the background by pressing arrow-right key or clicking with middle mouse
* verify you can search editors by typing
* verify you can close editors from the picker
* verify dirty editors indicate their state on the close button
* verify preview editors appear in italics
* verify that you can quick-navigate through editors of the active group via `Ctrl+Tab` keybinding (in this mode you should not see an input field and pressing and releasing the keys should accept the active item at once)

**Comment by alexdima** [comment]
Works nice!
