### ISSUE TITLE
vscode interrupts Firefox drag and drop

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#93631]
Issue Type: <b>Bug</b>

When dragging a tab out of a Firefox window to create a new window, if the tab is dropped over vscode the tab is not created. This does not happen with Chrome or Edge. Dragging a Firefox tab over Notepad works as expected. I believe vscode thinks this is a drag and drop operation that it is able to handle and eating the event.

Steps to reproduce:
* Open Firefox
* Open multiple tabs in Firefox
* Drag one of the tabs out of Firefox and drop it on the desktop
* Notice a new Firefox window is created

![No Bug](https://user-images.githubusercontent.com/484784/77815149-5a7f5400-7075-11ea-9502-29e4ba3e34ab.gif)

* Open vscode
* Drag another tab out of Firefox
* Drop it over vscode
* Notice a new Firefox window is *not* created
* Notice vscode does not perform any action to indicate it did something useful with the drag and drop operation

![Bug](https://user-images.githubusercontent.com/484784/77815151-5e12db00-7075-11ea-942b-64404cbcf969.gif)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
I suggest you report this against Firefox. VSCode itself is listening on various drag and drop operations, such as possibly URI and text transfer which might eat the tab in this case. I am not planning to change this because it enables other scenarios like dropping text into the opened editor.

**Comment by akbyrd** [comment]
I'd agree if there were other programs that caused this behavior, but vscode is the _only one_ I can find. Notepad can accept dragged text and that doesn't cause the issue. Chrome can accept URIs and that doesn't cause the issue. Neither do Windows Explorer, Edge, Steam, or Visual Studio

As vscode is the odd man out here it's worth understanding why this is happening before punting to Firefox.

Drop targets typically have to explicitly accept an operation, which gives me more reason to believe vscode is the party getting this wrong.
