### ISSUE TITLE
Quick access: extension search and install

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93639]
Refs: https://github.com/microsoft/vscode/issues/69955

- [x] anyOS: @sandy081 
- [x] anyOS @deepak1556

Complexity: 2

---

Quick open is now using the quick input widget that leverages our new tree widget. All quick open providers have been rewritten from scratch. 

All of the existing commands for driving quick open have been preserved. Everything should work as before with some additional features as noted in the test plan. 

**Note:** configure `"workbench.quickOpen.closeOnFocusLost": false` to make testing easier by keeping quick open opened even if you navigate somewhere else.

* verify the quick access providers `ext ` and `ext install ` work as before for managing, searching and installing extensions

**Comment by sandy081** [comment]
There is a change in behaviour but the change is good. Typing `ext install pub.id` and if `pub.id` is not found 

- Previously it complains that this extension is not found.
- ✅ Now its asking to press enter to search for extension.
