### ISSUE TITLE
Terminal shows special characters on mac with oh-my-zsh when using cursor keys

### ISSUE THREAD

**Issue by rburgst** [microsoft/vscode#93632]
- VSCode Version: 1.43.2
- OS Version: OSX 10.15.3 (19D76)
- Shell: oh-my-zsh

Steps to Reproduce:

1. open the integrated terminal
2. type some command (e.g. `yarn develop`)
3. cancel the command with CTRL-C
4. move the focus to an editor (mouse)
5. move the focus back to the terminal (mouse)
6. use the cursor keys to scroll through the command history

in 80% of all cases typing cursor up will produce the following

```
^[OA
```
instead of showing `yarn develop` again.

![image showing special char](https://user-images.githubusercontent.com/22971/77816236-7b6d9680-70c1-11ea-8dcf-aff2fad5c08a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rburgst** [comment]
Problem also happens on latest insider build: 
```
Version: 1.44.0-insider
Commit: 6cf3dd97465b2f4f666b66758991d720e003b0f4
Date: 2020-03-27T05:28:16.333Z (1 day ago)
```

**Comment by rburgst** [comment]
also tried setting `PS1=empty` just to make sure its not due to the color codes in the shell prompt, did not help either.

**Comment by Tyriar** [comment]
> cursor up

The up arrow key?

Can you share your settings.json file?

**Comment by rburgstaller** [comment]
@Tyriar yes, the up arrow key.

I did some more digging and found that this problem also appears in iterm (however, funny enough I hardly ever noticed it there). 

I googled a bit and stumbled upon this article

https://superuser.com/questions/714412/zsh-or-maybe-oh-my-zsh-history-gets-confused-with-multi-line-commands

**Comment by rburgstaller** [comment]
I guess this can be closed.
