### ISSUE TITLE
Quick access: editor symbols

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93643]
Refs: https://github.com/microsoft/vscode/issues/69955

- [x] anyOS: @jrieken    
- [x] anyOS @roblourens

Complexity: 2

---

Quick open is now using the quick input widget that leverages our new tree widget. All quick open providers have been rewritten from scratch. 

All of the existing commands for driving quick open have been preserved. Everything should work as before with some additional features as noted in the test plan. 

**Note:** configure `"workbench.quickOpen.closeOnFocusLost": false` to make testing easier by keeping quick open opened even if you navigate somewhere else.

* verify you can see, filter and navigate to symbols of the active editor when typing `@` in quick open
* verify you see a symbol icon the reflects its kind
* verify that grouping by kind still works when using `@:` as prefix
* verify the symbol gets revealed in the background while selecting items
* verify the decorations are getting cleared when you cancel or navigate to a symbol
* verify the symbols update when you switch editors while quick open is visible
* verify you get a good meaningful default entry when no editor is opened or the active editor does not provide any symbols
* verify that you can narrow down symbols by container if you type the container name after a space (e.g. type `foo bar` to find all symbols that have `foo` in their label and `bar` in their description
* verify this works on the right hand side of a diff editor when invoked there

**Comment by roblourens** [comment]
> verify that you can narrow down symbols by container if you type the container name after a space (e.g. type foo bar to find all symbols that have foo in their label and bar in their description

What is a "container" here? I can't search for methods inside a certain class name, for example. I never get results if I have a space in the query.

**Comment by bpasero** [comment]
@roblourens the container if present will be shown as "description" label in smaller letters next to the label
