### ISSUE TITLE
Quick access: monaco standalone editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93649]
Refs: https://github.com/microsoft/monaco-editor/issues/1874

- [x] anyOS: @alexdima 
- [x] anyOS @mjbvz

Complexity: 2

---

The quick open facilities for the standalone editor are now sharing the same implementation as the workbench.

* Run the monaco editor out of sources as explained in https://github.com/microsoft/monaco-editor/blob/master/CONTRIBUTING.md#running-the-editor-from-source
* verify quick access works with these providers
  * help (by default)
  * commands
  * goto line
  * goto symbol

**Comment by mjbvz** [comment]
Just tried testing this but I'm seeing the error:

```
Error: [createInstance] CommandsHistory depends on UNKNOWN service IStorageKeysSyncRegistryService.
```

**Comment by bpasero** [comment]
@mjbvz good catch, I will have to add it.

**Comment by bpasero** [comment]
I pushed changes so that you can test this now 👍

**Comment by alexdima** [comment]
This works great! Thank you @bpasero ❤️
