### ISSUE TITLE
TypeScript Syntax highlighting doesn't work in a function has a return type that ends in a number

### ISSUE THREAD

**Issue by brianhoy** [Microsoft/vscode#9364]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Create a class that ends in a number.
2. In that class, create a function and specify the return type as the name of the class you just created.
3. Notice how syntax highlighting breaks in that function.

Notice how "return this" is black in the function that has a return type that ends in a number.
![tssyntaxhighlightingbug](https://cloud.githubusercontent.com/assets/7350617/16884398/20f60844-4a97-11e6-9099-f00811e0970a.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#213
