### ISSUE TITLE
Quick access: accessibility

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93648]
Refs: https://github.com/microsoft/vscode/issues/69955

- [x] macOS: @isidorn 
- [x] windows @misolori
- [x] Linux @weinand

Complexity: 2

---

Quick open is now using the quick input widget that leverages our new tree widget. All quick open providers have been rewritten from scratch. 

**Note:** configure `"workbench.quickOpen.closeOnFocusLost": false` to make testing easier by keeping quick open opened even if you navigate somewhere else.

**Accessibility**
* enable a screen reader and verify the output makes sense when interacting with quick open (can you operate quick pick without looking at the widget for example, is the output too verbose?)
* verify you can navigate and select using keyboard only
* verify that high contrast theme works on the quick pick widget

**Comment by isidorn** [comment]
Looks good. However we already got some great issues from the community regarding this, so it would be great if we fix them
https://github.com/microsoft/vscode/issues/93610
https://github.com/microsoft/vscode/issues/93657

**Comment by weinand** [comment]
In general Orca screenreader and high contrast themes worked fine with Quickpick.
The issues I filed are more questions...
