### ISSUE TITLE
Lua commenting using // doesn't actually comment

### ISSUE THREAD

**Issue by JacobGunther12** [Microsoft/vscode#9365]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Visual Studio Code does not automatically comment in Lua using // but it really should.

Steps to Reproduce:

1. Open a *.lua file
2. Type "// I am really commented text but VSCode doesn't show it."

**Comment by weinand** [comment]
@JacobGunther12 you mean 'syntax colouring' is not correct for lua comments?

**Comment by JacobGunther12** [comment]
@weinand Yes, syntax coloring, I forgot the name. Why does it need more info? I have provided enough information?

**Comment by weinand** [comment]
@JacobGunther12 If I'm waiting for additional information (like the question about 'syntax colouring'), I'm adding the 'needs more info' tag. Now I got confirmation and I'll remove the tag and assign the issue to the owner of lua 'syntax colouring'.

**Comment by brianhoy** [comment]
If I'm not wrong, comments in lua use "--" and "--[[ ]]--" for comments, not "//". If you type // into a [lua interpreter](http://www.lua.org/cgi-bin/demo), you get an error.

**Comment by JacobGunther12** [comment]
@brianhoy Hmm, thats weird. I write Lua all the time and use // as a commenting method and it doesn't produce any errors, it just ignores the line.

**Comment by weinand** [comment]
@brianhoy you are correct: https://www.lua.org/pil/1.3.html 

I'm closing this as invalid.
