### ISSUE TITLE
Cannot deploy artifacts when Maven is in offline mode

### ISSUE THREAD

**Issue by zhangqiannh** [microsoft/vscode#93652]
Issue Type: <b>Bug</b>

It shows " Cannot deploy artifacts when Maven is in offline mode" when i deploy a java maven project to nexus.  But other tools are good, such as eclipse.
I'm very confused.
Complete command executed:  mvn clean deploy -f "d:\java.java\WorkSpace\Vscode_nacos\nacos-demo-provider-client\pom.xml" -o -DskipTests

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eclipse-keybindings|alp|0.10.0
vscode-eslint|dba|2.1.1
korofileheader|OBK|4.6.1
vetur|oct|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-spring-boot|Piv|1.16.0
java|red|0.58.0
vscode-xml|red|0.11.0
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2
vscode-spring-initializr|vsc|0.4.6
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

VS Code doesn't interact with Maven by itself so most likely you need to report this in https://github.com/microsoft/vscode-maven/issues repo.

Moreover - make sure you don't have `-o` option in your `maven.executable.options` settings https://stackoverflow.com/questions/32047161/failed-to-execute-goal-org-apache-maven-pluginsmaven-deploy-plugin2-7deploy
