### ISSUE TITLE
CodeLens : Class extending Array and overwriting its methods gets referenced globally

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#93654]
```javascript
class X extends Array{
    filter(){}
}
```
```
"javascript.referencesCodeLens.enabled": true,
```
![Code_2020-03-28_14-41-45](https://user-images.githubusercontent.com/30108880/77824359-711fbc80-7102-11ea-9600-cd2b664d4cfa.png)
![Code_2020-03-28_14-49-59](https://user-images.githubusercontent.com/30108880/77824503-69144c80-7103-11ea-8c3e-199c07e60fcc.png)

1.43.2

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/37878 with root cause
