### ISSUE TITLE
Markdown syntax highlighter colors svg elements red

### ISSUE THREAD

**Issue by flyx** [microsoft/vscode#93650]
Issue Type: <b>Bug</b>

When I have this content inside a markdown file:

```markdown
## foo

<figure>
  <svg viewBox="-1 -1 382 182" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="30" width="380" height="130" fill="lightgray" />
  </svg>
</figure>

bar
```

all element names after the opening `<svg>` tag up until and including `</figure>` get colored red. This is wrong; it's valid SVG syntax. Even if I remove the `<rect>` element, `</svg>` and `</figure>` get colored red. Other elements inside the SVG image get colored red as well (e.g. `<g>`, `<text>`, `<style>`, …).

I expect all elements to be colored blue just like the opening `<figure>` and `<svg>` elements, since they are a valid structure. I certainly don't expect the markdown syntax highlighter to actually validate the SVG structure, but it shouldn't color something red that is valid.

VS Code version: Code - Insiders 1.44.0-insider (6cf3dd97465b2f4f666b66758991d720e003b0f4, 2020-03-27T05:28:16.333Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.27GB free)|
|Process Argv|-psn_0_3322667|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by flyx** [comment]
@vscodebot The linked issue is about HTML syntax highlighting, this is about Markdown, so it's not a duplicate.

**Comment by mjbvz** [comment]
This grammar rule from html seems to be incorrectly be applying: https://github.com/microsoft/vscode/blob/18bab626b9d54e836412b7a6aae620645da0422c/extensions/html/syntaxes/html.tmLanguage.json#L1085

Not sure why this is happening vs in normal html files

**Comment by mjbvz** [comment]
Actually, closing this in favor of microsoft/vscode-markdown-tm-grammar#70 since that is where the grammar is stored
