### ISSUE TITLE
Terminal output is not appropriate.

### ISSUE THREAD

**Issue by ViReSu** [microsoft/vscode#93655]
Issue Type: <b>Bug</b>

When I run java program, terminal do not show proper output. It cotains blank spaces which makes unable to read the output. This happens with other languages also.What to do?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 4.15.0-30deepin-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R)  CPU       E5700  @ 3.00GHz (2 x 2924)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.84GB (0.10GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-django|bat|0.20.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.34.0
python-extension-pack|don|1.6.0
prettier-vscode|esb|3.20.0
code-runner|for|0.9.17
terminal|for|0.0.10
MagicPython|mag|1.1.0
python|ms-|2020.3.69010
cpptools|ms-|0.26.3
java|red|0.58.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2
jinja|who|0.0.8

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo
