### ISSUE TITLE
better javascript/Node.js/es6 syntax highlighting

### ISSUE THREAD

**Issue by xpepermint** [Microsoft/vscode#9366]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.5.0

**Motivation**
It seems that nobody deeply cares about Javascript/Nodejs syntax highlighting. VSCode does a better job then other text editors (e.g. Atom) but it's not perfect. VSC could be the #1 choise for javascript developers if some common syntax highlighting bugs were fixed.

**Steps to Reproduce**

Example 1:
```js
let from = neki;
from = a; // is a variable and should be in white color like other variables
```

Example 2:
```js
exports.myVar = async (ctx, next) => {} // this is all in white but exports and async should be e.g. in red or blue
```

Example 3:
```js
t.me = 1;
t.is = 2; // `is` is in blue but should be the same color as the above (1)
t.in = 3; // `in` is in blue but should be the same color as the above (1)
t.of = 4; // `of` is in blue but should be the same color as the above (1)
```

**Comment by plaanupam** [comment]
I love vsc except the syntax highlighting part. It will be great to have this feature
