### ISSUE TITLE
node_modules folder not shown after installation

### ISSUE THREAD

**Issue by themzed** [microsoft/vscode#93666]
- VSCode Version: 1.43.2
- OS Version: macOS 10.14.6 

Steps to Reproduce:

1. Open a React app or another project
2. Type `yarn` or `npm i` in terminal
3. After installation is finished, you need to relaunch vscode to see node_modules folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
So this does not happen when you disable all extensions? Which extension causes this?

**Comment by themzed** [comment]
Sorry, there was a mistake, It does occur when all extensions are disabled too.

**Comment by themzed** [comment]
Sorry, there was a mistake, It does occur when all extensions are disabled. I just edited issue.

**Comment by isidorn** [comment]
I can not reproduce this.  Sounds like a missing file events 
Can you please post the output if you run vscode with the `verbose` flag from the command line. So we see if the file events are coming. Thanks

**Comment by themzed** [comment]
Yeah, files created but there is no folder at the end till I relaunch.
