### ISSUE TITLE
Explorer UI Shifts in the Middle of a Double-Click

### ISSUE THREAD

**Issue by bganotoo** [microsoft/vscode#93662]
Issue Type: <b>Bug</b>

**Repro steps:**
1) Ensure the Open Editors list is visible and expanded.
2) Pausing as long as your system allows between clicks, double-click an unopened file in the Explorer.

**Actual result:**
With the first click, the file is opened in preview mode and added to the Open Editors list. This shifts the entire Explorer UI down one row, moving the target of your double-click. The second click lands on the incorrect item.

**Expected result:**
The UI should never shift in the middle of a single interaction like a double-click.

**Potential solutions:**
1) Don't show previewed files in the Open Editors list.
2) Introduce a delay before single-click triggers a file preview.
3) When updating the Open Editors list, also shift the Explorer scroll position to avoid moving items on the screen.

**Workaround:**
Collapse the Open Editors panel.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Thanks for filling this, we are aware of this limiation, however I could not find an older issue which caputres this.
Maybe just try disabling preview editors as workaround?

We tried some of your potential solutions and each caused some other issue.

**Comment by faucct** [comment]
What does `out-of-scope` mean? Whose scope is this, if not the VS Code's?
