### ISSUE TITLE
IntelliSense doesn't work for all JavaScript methods.

### ISSUE THREAD

**Issue by GeorgeFlorian** [microsoft/vscode#93660]
- VSCode Version: February 2020 (1.43)
- OS Version: Windows 10

Steps to Reproduce:

1. Create a .js file
2. Type in 
```
var title = document.querySelector('.title');
var text = title.innerText;
var letters = text.split;
```
where `'.title'` can be any element that has text inside.
`split` and `innerText` don't have an autocomplete. Also, hovering over them display "any". Many more JS functions don't have autocomplete.

`document` and `querySelector` have autocomplete. Hovering over them displays some tool-tips.

I have tried using some JS extentions but none of them had autocomplete for what I wanted:
- JavaScript (ES6) code snippets
- JavaScript and TypeScript Nightly
- Visual Studio IntelliCode

I have had only one extension from the list above enabled at a time.

I have restarted the TS server and still no change.
I have never changed anything to IntelliSense nor I know how. I don't have any json file in my project's directory nor have I ever used one.

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

This also happens with VSC Insiders version.

I have found similar issues on this github but the only "fix" that was suggested was to use **JavaScript and TypeScript Nightly**, which I did and nothing changed.

**Comment by nrayburn-tech** [comment]
It looks like it works correctly, but there is a difference between Element and HTMLElement and I think that is causing the confusion here.

`document.querySelector()` returns a type of Element.  This does not have an innerText property.
If you use `document.getElementById()`, that returns a type of HTMLElement and has the innerText property.

https://developer.mozilla.org/en-US/docs/Web/API/Element
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement

**Comment by GeorgeFlorian** [comment]
I have instances when `map()` and `forEach()` and other methods don't work. What can cause that ?

**Comment by nrayburn-tech** [comment]
You would have to share an example, so that I can try to reproduce the problem.  It comes down to the types not being the same as what you expect.  This could be either an issue with vscode, or confusion on what type your function is actually returning.

This simple example returns the proper types and works as expected.  Methods autocomplete when accessing the array indexes.

```
const myNumbers = [1, 2, 3, 4];
const asString = myNumbers.map((val, num) => {
    return val.toString();
});
const asNums = myNumbers.map((val, num) => {
    return val;
});
const asMixed = myNumbers.map((val, num) => {
    if (val > 2){
        return val.toString();
    }
    return val;
});

asString[0].toLocaleLowerCase();
asNums[0].toFixed();
asMixed[0].toString();
asMixed[0].toFixed();

```

**Comment by GeorgeFlorian** [comment]
Here is the code that bugs me out:
```
function spanTitle() {
    let title = document.querySelector('.title');
    let text = title.innerText;
    let letters = text.split('');
    let spans = letters.map(
        letter => {
            let span = document.createElement('span');
            span.innerText = letter;
            return span;
        }
    );
    title.innerHTML = '';
    spans.forEach(x => {
        title.appendChild(x);
    });

    return spans;
}

let spans = spanTitle();
spans.sort( function() {return 0.5 - Math.random() } );

let spansToAnimate = spans.slice(0, 6);
spansToAnimate.forEach(
    x => x.classList.add('bounce')
);
```

From that code, the following methods did not autocomplete:
```
innerText - let text = title.innerText;
split - let letters = text.split('');
map - let spans = letters.map(
sort - spans.sort( function() {return 0.5 - Math.random() } );
slice - let spansToAnimate = spans.slice(0, 6);
forEach (the last one) - spansToAnimate.forEach(
```

**Comment by nrayburn-tech** [comment]
I believe that each of those issues stem from the `document.querySelector('.title')` issue.

Because `document.querySelector` returns a type of `Element`, `title.innerText` does not exist, so it is cast as `any`.  From here, everything else gets cast as `any` and causes the autocompletion to not work.

In your use case, it may never be an issue.  However, you are not checking that your title variable is an `HTMLElement`.  If you add that check, then the typechecking is fixed and autocompletion works.
Doing something like this fixes the autocompletion.
```
let title = document.querySelector('.title');
if (title instanceof HTMLElement){
    // Your code here
}
```

**Comment by GeorgeFlorian** [comment]
> I believe that each of those issues stem from the `document.querySelector('.title')` issue.
> 
> Because `document.querySelector` returns a type of `Element`, `title.innerText` does not exist, so it is cast as `any`. From here, everything else gets cast as `any` and causes the autocompletion to not work.
> 
> In your use case, it may never be an issue. However, you are not checking that your title variable is an `HTMLElement`. If you add that check, then the typechecking is fixed and autocompletion works.
> Doing something like this fixes the autocompletion.
> 
> ```
> let title = document.querySelector('.title');
> if (title instanceof HTMLElement){
>     // Your code here
> }
> ```

And this is normal ?
I figured that IntelliSense should've worked with all elements and also be smarter than me.
