### ISSUE TITLE
command 'xxx' not found for any extension.

### ISSUE THREAD

**Issue by rishavpandey43** [microsoft/vscode#93675]
- VSCode Version: 1.43.2
- OS Version: Linux x64 5.3.0-42-generic

I'm facing this with the latest new update I did on my machine.

There's a similar closed issue #38153, but unable to find an appropriate solution.

Steps to Reproduce:

1. run any of the keyboard shortcut  (e.g- Alt+w)
2. error popups `command 'command 'extension.htmlTagWrap' not found`

I tried it with almost every extension, and the same error is popping out.

![Error](https://user-images.githubusercontent.com/27219302/77837905-4bd79080-718c-11ea-93d5-51305dc4a8f1.png)

Does this issue occur when all extensions are disabled?: No

**New Update-** Every time I'm opening any saas file, an error is popping out **extension host terminated unexpectedly.** and then any of the commands is unable to execute.

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by rishavpandey43** [comment]
I figured out, there's some problem with **Color Highlight - 2.3.0** extension, uninstalling it completely fixed the problem.

**Comment by jrieken** [comment]
Thanks for the info. Please follow-up the author of that extension, it will help all user of it
