### ISSUE TITLE
MultiCursor: step through multiple cursor selection

### ISSUE THREAD

**Issue by giancarlopro** [microsoft/vscode#93672]
Hi, i would like to have a feature where i can step through each cursor using tab like what happens with snippets. When selecting multiple cursors with `CTRL + D` or `CTRL + SHIFT + L` i would like to transform those into snippet cursors, where i can change one by one hiting `Tab`.

Example:
```Python
dict.add(item|)
dict.add(item)
dict.add(item)
```
`CTRL + SHIFT + L`

```Python
dict.add(item|)
dict.add(item|)
dict.add(item|)
```

`CTRL + ALT + S`
> shortcut example: transforms into snippet cursors.
```Python
dict.add([item|])
dict.add([item])
dict.add([item])
```

Now i can change the first one, and hit tab to go to the next one.

I see myself pasting one line multiple times and then selecting one by one to change. So this would be a really nice feature at least for me. Wanna hear your thoughs on that. Maybe it's solved with a extension?

I want to develop this if it's the case, but wanna make sure it is needed/helpful.

**Comment by ArturoDent** [comment]
Have a look at the extension https://marketplace.visualstudio.com/items?itemName=danseethaler.tab-through-selections which allows you to tab one-by-one through multiple selections making changes if you wish.

**Comment by giancarlopro** [comment]
> Have a look at the extension https://marketplace.visualstudio.com/items?itemName=danseethaler.tab-through-selections which allows you to tab one-by-one through multiple selections making changes if you wish.

Thank you, gonna try it. But i still think this should be a editor feature. now i found #72926 and this is a duplicate, closing here.
