### ISSUE TITLE
Auto Update Extensions

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#9367]
Can/is there be a feature that I can enable/disable to automatically update extensions? I don't have that many extensions, and there are updates every single day sometimes multiple times per day, so it would be nice if it did it automatically.

**Comment by kendaleiv** [comment]
As part of this, would it be a good idea to remove the count of pending extension updates from the left bar (at least, if automatic extension updates is enabled)? Displaying the update count could invite an unnecessary interaction, since they'd be handled automatically anyhow.

**Comment by TheColorRed** [comment]
This has now been implemented, I will close this.

**Comment by joaomoreno** [comment]
Sweet.

**Comment by leocaseiro** [comment]
```ts
{"extensions.autoUpdate": true}
```
