### ISSUE TITLE
Executable named tar not found on path

### ISSUE THREAD

**Issue by Gdepablo** [microsoft/vscode#93676]
Issue Type: <b>Bug</b>

stack build C:\Users\Guille\Desktop\pdepreludat-master

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G   (4 x 3094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (1.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
cpp-helper|ami|0.0.5
c-cpp-project-generator|dan|1.2.0
vscode-ghc-simple|dra|0.1.16
gitlens|eam|10.2.1
haskutil|Edk|0.4.5
hoogle-vscode|jca|0.0.7
language-haskell|jus|2.7.0
cpptools|ms-|0.26.3
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Do you see this error if you run that same command outside of VS Code?

**Comment by Gdepablo** [comment]
> Do you see this error if you run that same command outside of VS Code?
Hello, fortunately my mistake was trying it in the VS Code. I had to go directly to the direct access of gitbash and run the commands there to 'unzip' the tar file. Then and only then I could mix boths
