### ISSUE TITLE
Deleted files on desktop

### ISSUE THREAD

**Issue by thejunglife** [microsoft/vscode#93670]
Issue Type: <b>Bug</b>

I have no clue how this happened but some how I saw a bunch of my files on my desktop on vs code... as desktop git? I didn't know what was going on... saw i discarded everything which was about 5000 files..... then now I lost a lot of files on my desktop some how?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (4.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.1.6
vscode-eslint|dba|2.1.1
prettier-vscode|esb|3.20.0
open-in-browser|tec|2.0.0

</details>

**Comment by joaomoreno** [comment]
> saw i discarded everything which was about 5000 files

What do you mean? How did you see this? Did you discard all your changes?
