### ISSUE TITLE
Support for Terminal Instance Titles

### ISSUE THREAD

**Issue by jxramos** [microsoft/vscode#93674]
At times I frequently populate a series of terminals in my VSCode instances. On windows at least it would be great to be capable of naming each terminal much like you can do in the command prompt with the title command.

Take a look at the attempt here to title the first terminal cmd window:
![Terminal--Title](https://user-images.githubusercontent.com/13857038/77837652-712eb500-7120-11ea-9507-d0ad2e1d283c.png)

and what the behavior of the regular command prompt looks like...
![image](https://user-images.githubusercontent.com/13857038/77837679-c66ac680-7120-11ea-9825-0ab54f0f1c17.png)

I think retaining the indexed currently executing command still makes sense, eg
> 1. cmd
> 2. cmd

However the title behavior that would help a lot would look like some text to the right I'd imagine, eg
> 1. cmd (TEST_TITLE)
> 2. cmd

**Comment by ArturoDent** [comment]
There is a `workbench.action.terminal.rename` command.  See https://code.visualstudio.com/docs/editor/integrated-terminal#_rename-terminal-sessions.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/22325

You can try this:

```
"terminal.integrated.experimentalUseTitleEvent": true
```
