### ISSUE TITLE
Windows: Both insider and normal version: Unable to open 'xxx': Assertion Failed: argument is undefined or null

### ISSUE THREAD

**Issue by so2liu** [microsoft/vscode#93679]
Both insider and normal version: 

Insider:
Version: 1.44.0-insider (user setup)
Commit: 6cf3dd97465b2f4f666b66758991d720e003b0f4
Date: 2020-03-27T06:00:06.803Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Normal version: 
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open any file with vscode
2. 
`Unable to open 'react-debug.md': Cannot read property 'other' of null.`
`Unable to open 'react-debug.md': Assertion Failed: argument is undefined or null.`
3. Already tried to delete `C:\Users\username\.vscode` and `C:\Users\username\.vscode-insiders`. It doesn't work. 
![image](https://user-images.githubusercontent.com/9153390/77844286-ccef5180-71a5-11ea-8d3d-6c711c1a9f28.png)

**Update**
4. When I deleted `settings.json`, vscode works again... 

Does this issue occur when all extensions are disabled?: Yes

**Comment by QuangVM** [comment]
Hi! I have problem exactly like this. I delete setting.json but It doesn't work. There is another solution for this? Thank you!

**Comment by nchchow** [comment]
I had the same problem with Normal VSCode, but Insider Version worked for me. 

Deleting settings.json from Normal Version also worked for me.

Location: $HOME/Library/Application Support/Code/User/settings.json

**Comment by ryparker** [comment]
Same issue here. This issue must not be resolved.

**Comment by kleysoares** [comment]
I just had the same issue and this is how I fixed:
go to -> C:\Users\[USER_NAMD]\AppData\Roaming\Code\User\settings.json
and look for `"editor.quickSuggestions": null`. Change the value to either `false` or `null`

I hope it helps you.

**Comment by sgesweinFusion** [comment]
> `"editor.quickSuggestions": null`

I got this line added going through the Settings user interface screens to Text Editor | Suggestions, and clicking "edit in settings.json" under Quick Suggestions. Removing this line entirely also gets around this issue.

**Comment by lonesome-rider** [comment]
> 
> 
> I just had the same issue and this is how I fixed:
> go to -> C:\Users[USER_NAMD]\AppData\Roaming\Code\User\settings.json
> and look for `"editor.quickSuggestions": null`. Change the value to either `false` or `true`
> 
> I hope it helps you.

This actually works.

**Comment by Sirlanri** [comment]
> I just had the same issue and this is how I fixed:
> go to -> C:\Users[USER_NAMD]\AppData\Roaming\Code\User\settings.json
> and look for `"editor.quickSuggestions": null`. Change the value to either `false` or `true`
> 
> I hope it helps you.

Thanks, it worked:)

**Comment by hwxjGItHub** [comment]
I have this problem, open vs code, open file display
Unable to open 'react-debug.md': Cannot read property 'other' of null.
Unable to open 'react-debug.md': Assertion Failed: argument is undefined or null.
Can't open settings.json in settings
I installed vs Code on D disk and couldn't find settings.json.
I hope you can help me

**Comment by McMacaron** [comment]
Why this issue is closed. I have spent with solving this whole evening. It is a bug

**Comment by nishchal215** [comment]
> > I just had the same issue and this is how I fixed:
> > go to -> C:\Users[USER_NAMD]\AppData\Roaming\Code\User\settings.json
> > and look for `"editor.quickSuggestions": null`. Change the value to either `false` or `true`
> > I hope it helps you.
> 
> Thanks, it worked:)



> I just had the same issue and this is how I fixed:
> go to -> C:\Users[USER_NAMD]\AppData\Roaming\Code\User\settings.json
> and look for `"editor.quickSuggestions": null`. Change the value to either `false` or `true`
> 
> I hope it helps you.

Thanks it worked :)
And for ubuntu users to edit settings.json go to this path: $HOME/.config/Code/User/settings.json.

You can check this website:   https://supunkavinda.blog/vscode-editing-settings-json

**Comment by MaxwellHarper** [comment]
Having the same problem:   cannot open any files in editor.  Maybe an extension corrupted something.  I have uninstalled and reinstalled multiple times and I keep getting the message below when I try to open - for example - an html file.

"Assertion Failed: argument is undefined or null."
