### ISSUE TITLE
Animate going to the end of file like Sublime

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/vscode#93681]
I had to recently download Sublime as VSCode couldn’t handle my 1.5MB minified file.

So while using it, I noticed a subtle difference.

Going to the end of the file using <kbd>CMD+DOWN</kbd>, there is a fast snappy animation so it feels smooth in Sublime while in VSCode, it doesn’t feel smooth.

Not a big issue, but still a little improvement :)

**Comment by IllusionMH** [comment]
Have you tried to set `"editor.smoothScrolling": true` in settings?

**Comment by deadcoder0904** [comment]
Woah, thank you @IllusionMH 

That did the trick 🙌
