### ISSUE TITLE
Step Over jumps to end of function when debugging TypeScript that uses async/await 

### ISSUE THREAD

**Issue by amcdnl** [Microsoft/vscode#9368]
**Environment**
- VSCode Version: 1.4.0-insider
- OS Version: Mac
- TypeScript Version: 2.0

**Steps to Reproduce**
1. Set a break point on a line of TypeScript code in an async function that uses the await keyword on the Promise result of another async function. Example:`const result = await doSomethingAsync(); console.log(result);`
2. Start debugging in VS Code by selecting a related launch profile in a TypScript project. See my example snippet below.
3. Run necessary code so that the debugger is stopped on the breakpoint from step 1.
4. Press F10 to step over the `doSomethingAsync` function.

**Example**

``` javascript
class Foo {
   async do() {
     console.log('before');
     const result = await doSomethingAsync(); //<= set breakpoint here
     console.log('after', result); // <= hit F10 and notice it doesn't go here
   }
}
```

**Expected Result**
It would proceed to the `console.log('after', result);`

**Actual Result**
It jumps the end of the function. In order to debug, you have to put a breakpoint on every like inside that async function.

This issue was discussed [here](https://github.com/Microsoft/vscode/issues/4798) regarding step into and was resolved by @weinand but did not address the jump issue after testing the new fix.

**Demo**
- Pull [petstore](https://github.com/swimlane/node-microservice-demo/tree/master/petstore)
- Set a breakpoint [here](https://github.com/swimlane/node-microservice-demo/blob/master/petstore/src/controllers/PetStoreController.ts#L28)
- Run Launch in VSCode
- Goto `localhost:8080/pets` in your browser and observe as you step into and over each function.

**Further Details**
The issue actually presents itself in both TypeScript and Babel situations. This issue has been raised to Source Map team, Babel, Mozilla, Chrome Debugging and to TC39. See:
- https://github.com/mozilla/source-map/issues/221
- http://discuss.babeljs.io/t/async-await-debugging-issues/132
- https://github.com/tc39/ecmascript-asyncawait/issues/93
- https://bugzilla.mozilla.org/show_bug.cgi?id=1238745

Chrome debugger claims to have support for this now - https://twitter.com/addyosmani/status/740155716401565696

**Comment by amcdnl** [comment]
@weinand any updates on this?

**Comment by mrmlnc** [comment]
@amcdnl, recently saw a message that @weinand is on vacation.

**Comment by roblourens** [comment]
There are some comments in #11645 - there's not much that we or a sourcemap can do about this. Native async/await stepping works as you'd expect now when debugging Chrome/Node, that's implemented by them.
