### ISSUE TITLE
Unable to download vs-code editor

### ISSUE THREAD

**Issue by BenyKammoun** [microsoft/vscode#93685]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by BenyKammoun** [comment]
Hi, i'm not sure that's the right place to ask but, for few days i tried to download and install the vs-code editor and got an error so i was unable to dowload it (I don't have network issues). Someone know what's going on (or mabe have a clue what's the problem)

**Comment by octref** [comment]
> got an error

What's the error?
