### ISSUE TITLE
Git: Support for repo

### ISSUE THREAD

**Issue by parsley72** [microsoft/vscode#93697]
I have a project that uses [git-repo](https://gerrit.googlesource.com/git-repo/) so it contains multiple repos. The only way I can find of supporting this in VSCode is to use [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) and add each repo as a separate folder within the workspace.

There should be a way of opening the root folder where the .repo directory is and having VSCode recognise this automatically.

**Comment by parsley72** [comment]
#87888 is a similar idea, but you'd want to check for a git-repo before searching the subdirectories.

**Comment by kilakewe** [comment]
+1

**Comment by Erik-Roth** [comment]
+1
