### ISSUE TITLE
Visual studio code loads very slowly

### ISSUE THREAD

**Issue by Erinay0** [microsoft/vscode#93690]
Issue Type: <b>Performance Issue</b>

it has been going on for a while now.
it occurs from startup.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    74	  2892	code main
    0	   171	  2988	   window (index.html - Frontend CHALLENGES - Visual Studio Code)
    0	    11	 14664	     watcherService 
    0	    11	 12300	       console-window-host (Windows internal process)
    0	   228	 19468	     extensionHost
    0	    37	 15832	       electron_node dbaeumer.js server.js 
    0	    27	 16004	       electron_node eslintServer.js 
    0	    38	 16200	       electron_node server.js 
    0	    34	 17016	       electron_node server.js 
    0	    52	 19036	       "C:\Users\OLAMI\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\OLAMI\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=19468
    0	    31	 19480	       "C:\Users\OLAMI\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\OLAMI\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=19468
    0	    57	 19560	       electron_node server.js 
    0	    34	 19936	     searchService
    2	    65	  3116	   window (Issue Reporter)
    0	    75	  3340	   shared-process
    0	    14	 18048	   electron-crash-reporter
    0	   141	 18516	   gpu-process
    0	    25	 18572	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - Frontend CHALLENGES - Visual Studio Code)
|    Folder (Frontend CHALLENGES): 521 files
|      File types: svg(174) jpg(128) png(65) md(42) gitignore(21) html(20)
|                  json(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.11.0
vscode-database|baj|2.2.0
simple-react-snippets|bur|1.2.2
solargraph|cas|0.21.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.34.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.1
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.3
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.4
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
vscode-toggle-column-selection|eri|1.0.6
bootstrap-4-cdn-snippet|eve|1.3.0
git-project-manager|fel|1.7.1
file-icons|fil|1.0.22
auto-close-tag|for|0.5.6
code-runner|for|0.9.17
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
vscode-peacock|joh|3.6.0
chat|kar|0.33.0
vscode-language-babel|mgm|0.0.26
vscode-docker|ms-|1.0.0
remote-containers|ms-|0.106.0
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.3.0
sublime-keybindings|ms-|4.0.6
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.1847
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
color-highlight|nau|2.3.0
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
polacode|pnp|0.3.4
vscode-css-peek|pra|3.0.2
gitlink|qez|0.5.1
ruby|reb|0.27.0
prettier-now|rem|1.4.9
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.8.0
vscode-stylelint|sty|0.84.0
sass-indented|syl|1.8.1
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
vim|vsc|1.13.1
vscode-wakatime|Wak|4.0.0
quokka-vscode|Wal|1.0.284
vscode-ruby|win|0.27.0
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
vscode-preview-server|yui|1.3.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

[prof-6da2.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4399090/prof-6da2.main.cpuprofile.txt)

[prof-6da2.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4399092/prof-6da2.renderer.cpuprofile.txt)

[prof-6da2.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4399097/prof-6da2.extHost.cpuprofile.txt)

**Comment by deepak1556** [comment]
@Erinay0 can you launch code with `--trace` and attach the log. Thanks!
