### ISSUE TITLE
tasks.json not refreshed

### ISSUE THREAD

**Issue by omartin2010** [microsoft/vscode#93691]
When I'm editing a task in `tasks.json`, it doesn't take my changes until I rename the task (change its `label`). And then if I try to run the task, in the menu, I actually see the old `label` that I just rename (even if it no longer exists).

**Comment by alexr00** [comment]
What version of VS Code are you using? Can you provide a screenshot of the menu where you see the old label?

**Comment by omartin2010** [comment]
Version info :
```
Version: 1.44.0-insider (user setup)
Commit: 6cf3dd97465b2f4f666b66758991d720e003b0f4
Date: 2020-03-27T06:00:06.803Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
here is a screenshot : 
![image](https://user-images.githubusercontent.com/11371870/77914237-9bd55680-7263-11ea-81e8-8cd9c0f1a1ee.png)
The tasks in my `tasks.json` include `launchTestingContainer`, `launchInferenceContainer`, `launchInferenceContainer-debug`, `stopInferenceContainer` and `stopTestingContainer`.

Tasks ending with `2`, `3` and `4` were only created because I was seeing the tasks not being properly run by the system. E.g. I was making changes to `launchTestingContainer` but in the output of the console, I was seeing the tasks running commands that were there prior to my edits. When I changed the name of the task, the it worked. But it also kept the task names in the list of tasks despite me deleting them.

**Comment by alexr00** [comment]
Thank you for filing this bug and for using Insiders! It will be fixed in the next Insiders build.

**Comment by omartin2010** [comment]
this is great! Glad you can help quickly! Looking forward to tomorrow’s upgrade :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by omartin2010** [comment]
Hi! Is it supposed to be fixed in this version :  
```
Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by alexr00** [comment]
Yes, it should be fix in that version.

**Comment by omartin2010** [comment]
I see the same behavior, tasks exist in the list and I actually can run them, even if they are deleted from the `tasks.json` file...

**Comment by alexr00** [comment]
If you change a task instead of deleting it does it run the updated task? There is a separate problem where deleted tasks stick around.

**Comment by omartin2010** [comment]
it's running the updated task. But deleted ones are lying around (and still runnable - not sure where they are cached - even if I restart VScode). I use it in remote mode, if that makes any difference. thanks!

**Comment by alexr00** [comment]
It should be greatly improved based on changes made for https://github.com/microsoft/vscode/issues/93931

**Comment by omartin2010** [comment]
appears to be solved for me now, thanks!
