### ISSUE TITLE
Lost language server diagnostics in v1.43 extension development host. Works in 1.42.

### ISSUE THREAD

**Issue by pythoulon** [microsoft/vscode#93695]
- VSCode Version: v1.43.2
- OS Version: Windows 10 Home 1903 (build 18362.720)

Steps to Reproduce:

I'm developing an extension that embeds a language server. In v1.42, the diagnostics reported by the server show properly in the Problem window:

![snap0219](https://user-images.githubusercontent.com/11643101/77854865-17e08780-71ed-11ea-9886-282edfaf5fea.png)

In v1.43, they don't:

![snap0220](https://user-images.githubusercontent.com/11643101/77854873-23cc4980-71ed-11ea-804f-b2aaae84d316.png)

Exact same code. I've debugged my server, and it reports the diagnostics properly in v1.43, except that they don't show.

Any idea?

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> Any idea?

No chances on our end, diagnostics are successfully working for those language I selfhost on and for those that I develop. You'll need to share a full repo sample for further investigations here

**Comment by pythoulon** [comment]
OK. Got it. When I launched the Extension Development Host (F5), I got the following message in the debug console of the Code instance that launched the EDH (hadn't seen it the first time):

`Notification handler 'textDocument/publishDiagnostics' failed with message: Cannot read property 'is' of undefined`

So I backtracked it and found that the line highlighted below fails because the DiagnosticCode property of object 'ls' is undefined...

![snap0224](https://user-images.githubusercontent.com/11643101/77990931-e23dba80-7322-11ea-9345-9c7882d7de25.png)

Which lead me to try and update my vscode-languageclient module... which solved the problem.

So apparently, there is a dependency on the latest version of vscode-languageclient in Code v1.43 that did not exist in v1.42 (?). Is there a way to avoid such quirks in the future ? Should I run `npm update` on my project everytime I upgrade Code ? Tips welcome... Thanks.

**Comment by dbaeumer** [comment]
@pythoulon actually this was a problem with me releasing 6.1.2 of the LSP client libs which were released from master and therefore broken. The new 6.1.3 fixed this. VS Code 1.43 had nothing to do with this (see also: https://github.com/microsoft/vscode-languageserver-node/issues/594)

**Comment by pythoulon** [comment]
@dbaeumer I do understand, but how come 6.1.2 worked on VS Code 1.42, but not on 1.43 ?... I must be missing something. Anyway, it works now, so all is fine, but I would appreciate some clarification on the matter, if you can spare the time and have an explanation... Thanks !

**Comment by dbaeumer** [comment]
`1.42.x` did not have support for complex diagnostics hence the if at line `32` was always true and the problematic code at line `35` got never executed.

**Comment by pythoulon** [comment]
Ok. That makes sense. Thanks for the clarification and long live VS Code... 😄
