### ISSUE TITLE
"Retry as Sudo" should honor NOPASSWD

### ISSUE THREAD

**Issue by charlesg99** [microsoft/vscode#93699]
Issue Type: <b>Bug</b>

To reproduce, create a linux user that is part of a group that can use the sudo command without password (NOPASSWD), then try to save a file that isn't writable without sudo privileges:

![image](https://user-images.githubusercontent.com/33044886/77858195-d8577280-71cf-11ea-82af-a579ec701313.png)

Currently, when clicking "Retry as Sudo", vscode prompts the user to input its password, even if he can use sudo without a password:

![image](https://user-images.githubusercontent.com/33044886/77858115-5ff0b180-71cf-11ea-8db3-a91e1d243f4b.png)

In this case, I think vscode shouldn't prompt for a password and honor the sudo configuration.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.5.13-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.48GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.3.11
gitlens|eam|10.2.1
php-debug|fel|1.13.0
docthis|joe|0.7.1
git-graph|mhu|1.22.0
vscode-docker|ms-|1.0.0
vsliveshare|ms-|1.0.1847
debugger-for-chrome|msj|4.12.6

</details>

**Comment by bpasero** [comment]
@charlesg99 we use `sudo-prompt` so I think you should ask there, but I found https://github.com/jorangreef/sudo-prompt/issues/58 which may explain a solution?

**Comment by charlesg99** [comment]
Hello bpasero! Thank you for your research and sorry about the noise, I wasn't aware that you're using a third party solution for sudo. Seems like the issue you mentioned indeed contains a workaround  using environment variables, although it feels like this should just work out of the box. Thanks!
