### ISSUE TITLE
Go to file - add option to exclude symbols

### ISSUE THREAD

**Issue by thematthopkins** [Microsoft/vscode#9369]
- VSCode Version: 1.3.1
- OS Version: OSX 10.11.5

When navigating to "Open Files and Global Symbols by name", I'm nearly always looking for a file.  Having symbols there adds duplicate results that are very rarely relevant, and slows things down.  Searching for MyClass usually comes up with:

- MyClass.cs (99% the thing I'm looking for)
- The class definition
- Usually some public properties that I've never found a use for navigating to

I'm also hoping that if there were an option to exclude symbols, we could have a lightning fast go to file like Sublime, instead of the search getting bogged down looking through some symbols database.

Thanks!

**Comment by weinand** [comment]
@thematthopkins bear with me, but to what  "Open Files and Global Symbols by name" are you referring to? I cannot find this command in VS Code 1.3.1.

**Comment by thematthopkins** [comment]
I should have referred to it as GoTo -> Go to File...

"Go to File" isn't 100% accurate though, because that's the feature I'm hoping for.  Typing "?" in the Go to File... input gives the more descriptive name of "Open Files and Global Symbols by name"

**Comment by texastoland** [comment]
Based on issues like #5954 and IME I'd prefer global symbol navigation separate from file navigation (as opposed to filtered).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4512
