### ISSUE TITLE
Incorrect Angular error

### ISSUE THREAD

**Issue by manu2504** [microsoft/vscode#93700]
Issue Type: <b>Bug</b>

I got an Angular/Typescript error that is not justified: "The pipe 'filter' could not be found".
In fact, the app compiles perfectly well and the pipe actually works.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|-psn_0_1081608|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.0
vscode-eslint|dba|2.1.1
vscode-ionic-snippets|fiv|2.1.0
code-runner|for|0.9.17
python|ms-|2020.3.69010
cpptools|ms-|0.26.3
java|red|0.58.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2

</details>

**Comment by manu2504** [comment]
PS: even after re-saving the concerned files, the error had not disappeared.
PS2: after restarting VSCode, the error disappears.

**Comment by mjbvz** [comment]
Is the error coming from your angular extension?
