### ISSUE TITLE
Memory RAM high comsuption

### ISSUE THREAD

**Issue by AndresJz** [microsoft/vscode#93704]
Issue Type: <b>Bug</b>

When I started to search some file by typing cmd + p the rg process is using too much ram memory  and my computer crashing. I didn't happen before  the last update version seems to be the root

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
gitlens|eam|10.2.1
rest-client|hum|0.23.2
ecdc|mit|1.3.0
vscode-docker|ms-|1.0.0
python|ms-|2020.3.69010

![imagen](https://user-images.githubusercontent.com/15618862/77864102-0050d100-71e4-11ea-9ace-ffb73fc33bc8.png)

</details>

**Comment by AndresJz** [comment]
**Update**

I got this working again downgrading to January Version.

Now I'm pretty sure that this is a 🐛

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by mjbvz** [comment]
And make sure to test with all extensions disable. If you only see this when extensions are enabled, one of them is causing this

**Comment by AndresJz** [comment]
Sorry after I did a downgrade I don't see this issue anymore, I'm using the same extensions, I disabled the auto-update to prevent possible issues. If I experienced something similar I'll post it again with this [data](https://github.com/Microsoft/vscode/wiki/Performance-Issues)

**Comment by mjbvz** [comment]
Ok, closing this issue for now but let us know if you see it again
