### ISSUE TITLE
save all tabs problem

### ISSUE THREAD

**Issue by imaniy1994** [microsoft/vscode#93707]
- VSCode Version: new version
- OS Version: windows

Steps to Reproduce:

1. save all tabs
[Record_2020_03_30_04_26_47_446.zip](https://github.com/microsoft/vscode/files/4400215/Record_2020_03_30_04_26_47_446.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please describe what is going wrong using text and provide steps to reproduce the issue

**Comment by imaniy1994** [comment]
> Please describe what is going wrong using text and provide steps to reproduce the issue

Hi, there is a bug i want to report
When i try to save multiple files with shortcut keys, some code from one file transfer to another file
For example several js lines from js file go to css file.

**Comment by imaniy1994** [comment]
Problem found

JS-CSS-HTML Formatter
https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter

**Please Remove :(**
