### ISSUE TITLE
Ibeam in terminal

### ISSUE THREAD

**Issue by sungle3737** [microsoft/vscode#93708]
First, 1.43.2 update `alt` + `click` feature is really great

### My request 
I use vscode in windows with git bash terminal
pure git bash terminal support ibeam cursor but i think vscode doesn't
It could be great if we can set ibeam or box or etc in **terminal**!

**Comment by Tyriar** [comment]
What do you mean by ibeam and box?

**Comment by sungle3737** [comment]
### Sorry I don't think they are official terms

My Intent of I-Beam was kind of `text cursor view type` in terminal which are supported at Hyper.js
![image](https://user-images.githubusercontent.com/27716524/78537722-dbcfa700-782a-11ea-91f4-991fc9e690bf.png)

And box shaped text cursor  is
 
![image](https://user-images.githubusercontent.com/27716524/78537911-29e4aa80-782b-11ea-93b4-97f0737935ff.png)


which are default in vscode
So I request I-beam shaped text cursor feature like normal editor for **precise** `alt` + `click`!

**Comment by Tyriar** [comment]
You can use this to get that cursor type:

```
"terminal.integrated.cursorStyle": "line"
```

Note though that the cursor won't follow when you do a selection as the cursor location is owned by the process in the terminal.
