### ISSUE TITLE
Documentation popup links are broken

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#93702]
The links that appear in the documentation popups are broken.
At least for those documenting the VS Code API.

![Capture du 2020-03-29 22-50-08](https://user-images.githubusercontent.com/15984272/77860741-11640700-7211-11ea-8fd0-bfdff5e2b134.png)

Steps to Reproduce:

1. Get this vscode demo project in your IDE, open at that line
https://github.com/microsoft/vscode-extension-samples/blob/0d75c547555a098f8438007c39ca432f819c5354/task-provider-sample/src/customTaskProvider.ts#L95
2. Put your cursor on `createFileSystemWatcher`
3. Click on a link in the "documentation popup" that appears
4. Observe the error

Version: 1.44.0-insider
Commit: 6cf3dd97465b2f4f666b66758991d720e003b0f4
Date: 2020-03-27T05:34:30.255Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Consequence of using markdown links for our docs.

We'd like to move to standard JS docs for these links. Upstream issue: https://github.com/microsoft/TypeScript/issues/35524

**Comment by mjbvz** [comment]
Closing this in favor of #120120, which tracks our plan for enabling these links in `vscode.d.ts`
