### ISSUE TITLE
Compact Folders: context menu uses the wrong folder path

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#93709]
Can reproduce in 1.43.2 and 1.44 insider.

Opening a folder with the following structure, and enable compact folders.
```
- learning
  - src
    - main
```

Contribute customized context menus via `contributes.menus-> explorer/context` in package.json.
Then hover at `src` or `main` folder to trigger the context menu action, the uri parameter in the command callback will always point to the same folder `main`.

**Comment by isidorn** [comment]
@testforstephen great catch, thanks for reporting this. I have pushed a fix and VS Code insiders from Friday should have the fix.

**Comment by testforstephen** [comment]
/verified

works in the latest insider version.

**Comment by isidorn** [comment]
Thanks!
