### ISSUE TITLE
VS Code Git sidebar does not highlight changed files 

### ISSUE THREAD

**Issue by alihassan1133** [microsoft/vscode#93701]
![image](https://user-images.githubusercontent.com/62854082/77859132-a34e1e80-71d5-11ea-9ba3-470c325ea112.png)

As you can see in the screenshot, I have made 2 changes to my files but they aren't actually highlighted in the sidebar. It's not a problem with my color scheme either, because I tried 4 different color schemes to see if the problem would go away, but it doesn't.

**Comment by vrinceanuv** [comment]
Same issue here after vscode updates :)

**Comment by joaomoreno** [comment]
@alihassan1133 Can you reproduce with any file in the repository? Also with other repositories in your system?

**Comment by otaithleigh** [comment]
I'm having this issue as well, and at least for me it appears to be related to symlinks. Opening the original directory in VS Code shows modified files and gutter decorations, opening the linked directory does not show highlights/decorations.

**Comment by joaomoreno** [comment]
@alihassan1133 Can you check if you have symlinks?
