### ISSUE TITLE
Cut & paste not working. Insert mysteriously goes on. Return key not working.

### ISSUE THREAD

**Issue by vonroga** [microsoft/vscode#93705]
- VSCode Version: 1.43.2
- OS Version: Windows 10 version 1909 build 18363.720

Steps to Reproduce:

1. Working in a .html document
2. Attempting to CTRL+ X to cut - does not cut selection.
3. Hitting return key sometimes just doesn't return. Insert turns on.
4. Hitting insert key sometimes doesn't turn off insert.

notes:
-Insert is not on in any other application.
-I have uninstalled VSCode and deleted appdata files, reinstalled, getting same problem.
-Keybindings in settings are all set up as normal.
-Upon re installation I have not installed any extensions.
-Even when I had installed extensions, they were wildly popular downloads and don't seem to be throwing any known issues that would explain this bug.

Does this issue occur when all extensions are disabled?: Yes/No
Yes. I cannot CTRL + X any selection inside my project.
![insert on without any reason](https://user-images.githubusercontent.com/61405141/77864625-8d912700-71de-11ea-9008-850e0877e8de.png)
![after ctrl x  selection stays put](https://user-images.githubusercontent.com/61405141/77864626-8e29bd80-71de-11ea-9d8b-87d36b2e8e69.png)

**Comment by vonroga** [comment]
Screenshot for windows doesn't let you see where insert has selected the closing bracket for that div tag.
Unsure how to show you that return key also not working. You'll just have to take my word for it.

**Comment by alexdima** [comment]
@vonroga From you screenshot, it is clear to me that you have installed the vim extension. When uninstalling VS Code, I believe extensions are maintained (can you confirm @joaomoreno?). You need to uninstall the vim extension, which changes the input in the editor to be like in vim.

**Comment by vonroga** [comment]
That seems to have done it. I guess this turns into a feedback request,
which is to make it so that the extensions are fully removed when removing
app data. It doesn't make sense to me that in-app add on installations
would still be sitting somewhere on my computer after uninstalling and
removing app data for VSC.

Regards,

Ryan Paranich

Owner, MossAway™ Services Inc.


p: *(778) 401-8144* <7784018144>

e: *ryan@mossaway.ca* <ryan@mossaway.ca>

w: *www.mossaway.ca <http://www.mossaway.ca> *


* <https://www.mossaway.ca/>
<https://www.bbb.org/ca/bc/victoria/profile/roof-cleaning/mossaway-roof-moss-removal-0047-235948777>*
*Proudly Serving Greater Victoria · Locally Owned & Operated · **Licensed** &
Insured*
*Roof Moss Removal <https://www.mossaway.ca/roof-moss-removal.html> · Roof
Moss Treatment <https://www.mossaway.ca/roof-moss-removal.html>** · Window
Cleaning <https://www.mossaway.ca/window-cleaning.html>*

ᐧ

**Comment by joaomoreno** [comment]
> @vonroga From you screenshot, it is clear to me that you have installed the vim extension. When uninstalling VS Code, I believe extensions are maintained (can you confirm @joaomoreno?). You need to uninstall the vim extension, which changes the input in the editor to be like in vim.

Confimed 👍
