### ISSUE TITLE
Ignore files/folders from problems

### ISSUE THREAD

**Issue by OoDeLally** [microsoft/vscode#93719]
I am aware this exact topic has been discussed here https://github.com/microsoft/vscode/issues/22289 , but it seems like it has been closed with a semi-satisfying solution, so I am reopening one, in the hope that the debate will take place again.
The proposed solution is to always have e.g. `!**/node_modules/**` in the filter. However I have two objections to this solution.
1- This filter input is supposed to be interactive and ease the developer's navigation among the various problem. Having to keep `!**/node_modules/**` all the time on top of the _actual_ filter seems like a big UX clog. 
2- This solution treats the symptoms, e.g. displaying the problem. Meanwhile, it still wastes vscode's computing time searching for problems in these folders.

The ideal solution would be for VSCode not to even bother searching for problems in these folders. In addition to be a cleaner approach, it would save some computing/reading time.

Imho, it should be, as proposed in some threads, a saved settings (per user or per-workspace). And it should not be part of the UI on the problem tile.

**Comment by OoDeLally** [comment]
Also, the problem count doesnt take the filter in account
![image](https://user-images.githubusercontent.com/1717629/77898337-45741200-727b-11ea-838b-d77e741b533d.png)

**Comment by gjsjohnmurray** [comment]
AFAIK the entries on the Problems tab all come from extensions (either built-in ones, or ones you added. Any extension may create instances of the `Diagnostic` class, push them into a `Diagnostics` array, then send them to VS Code.

There's a simple example [here](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#adding-a-simple-validation).

I think you need to discover which extension is producing the unwanted-by-you diagnostics from node_modules files, then configure that extension so it no longer does that. And if the extension doesn't give you a way to do that, raise the issue with the extension developer.

**Comment by gjsjohnmurray** [comment]
> 
> 
> Also, the problem count doesnt take the filter in account
> ![image](https://user-images.githubusercontent.com/1717629/77898337-45741200-727b-11ea-838b-d77e741b533d.png)
> 
> Even though the 16 claimed problems are all filtered out.

See https://github.com/microsoft/vscode/issues/22289#issuecomment-380872194

**Comment by OoDeLally** [comment]
> I think you need to discover which extension is producing the unwanted-by-you diagnostics from node_modules files, then configure that extension so it no longer does that. And if the extension doesn't give you a way to do that, raise the issue with the extension developer.

Makes sense. thank you!
