### ISSUE TITLE
Notebooks: fail to open in web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93716]
This call will fail in web:

https://github.com/microsoft/vscode/blob/1ec43773e37997841c5af42b33ddb180e9735bf2/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L106

I plan on removing the pieces of environment service that will not work in debt week, but for now we should fix this to enable notebooks in web.

**Comment by jrieken** [comment]
@rebornix We have `getPathFromAmdModule` and `getUriFromAmdModule`  which might be useful here: https://github.com/microsoft/vscode/blob/18c69d801317970b60c6e4a19aa03615f118e480/src/vs/base/common/amd.ts#L8

**Comment by bpasero** [comment]
Still does not work, there is more usages: https://github.com/microsoft/vscode/blob/6f558be495f02b0f5b5455cd708a050348fa4112/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L314

//cc @jrieken

**Comment by rebornix** [comment]
<img width="2109" alt="image" src="https://user-images.githubusercontent.com/876920/78410578-99eff800-75c1-11ea-838f-54bc7a8b51a9.png">
