### ISSUE TITLE
Completion Ordering for plugins 

### ISSUE THREAD

**Issue by Bunkaii** [microsoft/vscode#93710]
- [ ] 

Is your feature request related to a problem? Please describe.
I've noticed plugins that load first compared to slower ones, for example, the Kite plugin for VSC loads faster than and the Python plugin by Microsoft. Since Kite plugin loads faster, it ends up showing up at the bottom of the code snippet pop that comes up when you hover your mouse over portions of your code, such as, methods, objects etc...
_____________________________
Kite plugin CODE SNIPPETS
__________________________________________
Microsoft Python plugin CODE SNIPPET
__________________________________________

^ that is how I want the code snippets to show up. The only way I can currently achieve this is by disabling the Kite plugin, restarted vsc, and once all the other plugins are loaded I have to enable the Kite plugin. This way it will show up at the top. BUT, when I close and reopen vsc, the Kite plugin loads faster than the other plugins and therefore it ends up showing up in this order. 

__________________________________________
Microsoft Python plugin CODE SNIPPET
__________________________________________
Kite plugin CODE SNIPPET
___________________________

By being able to choose which plugin to load in the order that I want, I'll be able to control the order in which the plugin features show up when I hover over my code. Without, having to disable Kite plugin, reboot vsc, once all other plugins load then, enable Kite plugin. I want to avoid doing this repeatedly.

Describe the solution you'd like
Completion Ordering for plugins, The ability to tell Visual Studio Code to load plugins in a predetermined sequence so that plugin features, such as AutoComplete and Intelligent Code Snippets, show up in the order the User wants.

Describe alternatives you've considered
I have tried to see if the option was available within the plugin features themselves and I've also tried to look for the option within the setting of VSC.

Additional context
I've also tried to see why some methods don't show up for the AutoComplete feature in the Python plugin. For example, a lot of pandas methods do not show up and many of the methods don't have Intellisense code snippets. That is why I am trying to use Kite plugin as a backup for when Python Plugin doesn't provide a snippet.

https://www.reddit.com/r/vscode/comments/frfuuv/order_of_load_of_plugins/?utm_medium=android_app&utm_source=share

**Comment by jrieken** [comment]
>  Since Kite plugin loads faster, it ends up showing up at the bottom of the code snippet pop that comes up when you hover your mouse over portions of your code, such as, methods, objects etc...

That's not how it works. All completion item providers that are applicable are asked for completions and then one sorting is created. That sorting is either alphabetic (when there is no prefix) or the sorting depends prefix-based rank (note that extensions determine the prefix)

**Comment by Bunkaii** [comment]
> > Since Kite plugin loads faster, it ends up showing up at the bottom of the code snippet pop that comes up when you hover your mouse over portions of your code, such as, methods, objects etc...
> 
> That's not how it works. All completion item providers that are applicable are asked for completions and then one sorting is created. That sorting is either alphabetic (when there is no prefix) or the sorting depends prefix-based rank (note that extensions determine the prefix)

I don't fully understand what your saying.

**Comment by Bunkaii** [comment]
https://github.com/microsoft/vscode/issues/93758

**Comment by jrieken** [comment]
Please do not create a new issue but answer by question here

**Comment by Bunkaii** [comment]
Answer what? This seems to be for someone who's never worked with github
before.

I closed my previous one and made a new ticket as you mentioned and now the
bot closed my recent one also?

**Comment by Bunkaii** [comment]
Im just trying to offer help by requesting a feature that will make vsc
better Imo, why is this difficult, not that its your fault just saying it
seems confusing for someone new to this

**Comment by jrieken** [comment]
> Answer what? This seems to be for someone who's never worked with github
before.

This question: https://github.com/microsoft/vscode/issues/93710#issuecomment-605823491. You say that fast loading extensions end up showing the their completions at the bottom and that's not true. So, I am asking what makes you think so

**Comment by Bunkaii** [comment]
I have Kite plugin installed and also the Python vsc plugin by Microsoft.

If you have any of them, uninstall them and then, install the Python plugin
by Microsoft with intellisense feature and then install the Kite plugin.

Open up any code and hover your mouse over your code and you'll see the
Kite intelligent code sniffer show up above the intellisense code snippet
feature of the Python plugin by Microsoft.

After you confirm this is the case, close your visual studio code and
reopen it and once everything loads and there is no errors that need
checking. Hover over the same code and you'll see that the Kite snippet
shows below the Intellisense code snippet.

That's what made me think that vsc just stacks each plugin on top of each
other based on which one loads faster and that impacts the order in which
they show up in the code snippet pop window. Hope this makes sense.

**Comment by Bunkaii** [comment]
This is my first github post so it's been confusing but I closed my other
tickets or they got closed and here is the lastest, I hope it will not be
closed.

https://github.com/microsoft/vscode/issues/93761
