### ISSUE TITLE
Download Progress for Extensions

### ISSUE THREAD

**Issue by firesh-bakhda** [microsoft/vscode#93713]
Issue Type: <b>Feature Request</b>

Hi,

I am Firesh, a developer who utilize Visual Studio Code as much as i can for most of my projects and languages. However, for me, example, if you are on a slow network, the installation of extension do not show you progress of download and installation. 

It would be really helpful, if the download + installation progress (percentage or progress bar) is shown to help for users on slow networks. 

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
/duplicate

#56023
