### ISSUE TITLE
Search and File Watcher Exclusion not working on Ubuntu

### ISSUE THREAD

**Issue by austinrivas** [microsoft/vscode#93718]
- VSCode Version: 1.43.2
- OS Version: Ubunutu 18.04.4 LTS

Steps to Reproduce:

1. Run VSCode on ubuntu
2. Open a node project
3. Use fire extinguisher to put out the resulting fire

Does this issue occur when all extensions are disabled?: Yes

File exclusion from watchers and search are not working no matter the pattern.

I have tested this with the default exclusions.

Love the product and would like to continue using it once this is fixed.

Keep up the great work.

**Comment by roblourens** [comment]
Can you be more specific about the problem? You can use `code --status` to get info about which processes are using high cpu/memory. Also, please try starting with `code --disable-extensions` to check whether it still reproes.
