### ISSUE TITLE
Search: file search does not respect limit from quick open

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93715]
While working on quick open I noticed how the file search for very large repositories is very very slow. 

Quick open has an internal limit of 512 results, so my expectation is that after 512 results that are returned from RipGrep, we stop the search and present the results.

However, we seem to be waiting for RipGrep to finish before returning the results. I think that is less than ideal for large workpsaces. 

To reproduce:
* open a very large workspace (e.g. the parent of the folder that has all the development projects)
* add a console log statement with a counter to `fileSearch#matchFile`
* type a search in quick open

=> 🐛 you get a lot more results than 512

**Comment by chrmarti** [comment]
We want the 512 'best' results (not more, but we need to consider all results for this).

**Comment by bpasero** [comment]
@chrmarti I wonder if there should be another threshold where we simply stop looking for more accurate matches and return something back to the user so that the user can filter more.

**Comment by roblourens** [comment]
We could be looking at the number of potential matches that we get, and stop the search when we max out on potential matches. But, is that really an issue? If you start searching and type `a` then you will have to wait longer than necessary for your 512 results but typically people narrow down the search more without waiting right?

**Comment by bpasero** [comment]
Not sure it is an issue in most cases but it felt like a straight forward optimization for that particular case. I am not sure how we use RipGrep for file search but it seems to me that RipGrep itself only provides an option to return each and every file path and we do the matching ourselves. Once we match a certain number of files I think we should simply return to the user and not wait for more matches.

**Comment by roblourens** [comment]
If I understand the code correctly, we already do the filtering in parallel with the rg process running, and kill rg when we hit maxResults. I'm sure there's more optimization that can be done but I'm not going to be looking at this right now.
