### ISSUE TITLE
Can't replace same text with different case

### ISSUE THREAD

**Issue by gsscoder** [microsoft/vscode#93711]
Thank you for excellent project!

Simply what in subject.

![Capture](https://user-images.githubusercontent.com/1194228/77878236-2912ae00-7258-11ea-865f-14aa748fadb1.PNG)

Trying to replace `Something `with `something `has not effect (case sensitive activated).

Regards,
Giacomo S. S.

**Comment by ArturoDent** [comment]
I can't reproduce this unless I have the `Preserve Case` option enabled as well which it appears you do - it is difficult to see in the graphic?  Disable the `AB` option on the Replace row and see your result.

**Comment by gsscoder** [comment]
@ArturoDent,
lately the problem seems disappeared. I found **difficult to reproduce** it again. So I close the issue.
Thank you!
