### ISSUE TITLE
Test: dirty workspaces are indicated in recently opened

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93729]
Refs: https://github.com/microsoft/vscode/issues/92467

- [x] anyOS @weinand  
- [x] anyOS @Tyriar 

Complexity: 2

---

Dirty workspaces are either single-folder or multi-root workspaces that contain untitled files with changes or normal files with changes that are not saved. We typically restore all workspaces with dirty files because we restore all windows when you exit VSCode and start again. But there are cases where you can let VSCode NOT restore them:
* open some windows
* have dirty files in some or all
* File > Exit
* from the command line open code on a folder (`code-insiders <folder>`)

However, we still want people to find workspaces with dirty files to restore. As such, the list of recently opened workspaces will always show workspaces with dirty files.

![image](https://user-images.githubusercontent.com/900690/77897457-fbd6f780-7279-11ea-9d79-337f047d468e.png)

**Verification:**
* verify that we do NOT restore folders and workspaces with dirty files if you instruct code to open a specific folder as instructed above
* verify that the list of recently opened workspaces always indicates dirty workspaces (with a black dot where the close button is)
* verify that you cannot remove a workspace with dirty files from the picker without reviewing the files first and either saving or reverting them

**Comment by Tyriar** [comment]
Looks great, I still think we should show an indicator when possible (custom menus) in the open recent file menu though. And fallback to a regular " (has changes)" label or something when not possible, similar to how we fallback for hot keys.
