### ISSUE TITLE
Allow to search commands by keybinding in command palette

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9372]
- VSCode Version: Code - Insiders 1.4.0-insider (4d0b2f5f15bf7011d3a99888763a7b46a5953d95, 2016-07-15T12:35:33.467Z)
- OS Version: Windows_NT ia32 10.0.14372

Discovered the want for this when I typed Ctrl+B instead of Ctrl+V and triggered the Toggle Sidebar Visibility command . I wanted to know what command I had invoked so I could remember it in the future and I tried to search for Ctrl+B in the command palette but nothing came up.

Would like to be able to search for commands by hotkey to improve discoverability of exactly what happens when I sometimes type the wrong hotkey.

![image](https://cloud.githubusercontent.com/assets/494055/16890726/0e058cbe-4aa6-11e6-9fe8-1a8c9d5cff1d.png)

**Comment by bpasero** [comment]
This can be done from the keybindings editor and I think that is the right place:

![image](https://cloud.githubusercontent.com/assets/900690/26462884/d9f67d00-4182-11e7-9896-c73c01f2b730.png)

**Comment by dilijev** [comment]
Fair enough. Thanks.
