### ISSUE TITLE
The editor gets stuck when the mouse is over the code

### ISSUE THREAD

**Issue by adhope** [microsoft/vscode#93735]
Issue Type: <b>Bug</b>

<img key={val.productId} src={val.productImage} style={{ display: 'inline-block', width: '100%', height: '100%', margin: '5%'}} />

This is the possible code
Sometimes you can delete a few characters, and then the mouse can be used but the keyboard doesn't respond

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.3.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.34.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.7.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
terminal|for|0.0.10
vscode-mysql|for|0.4.0
beautify|Hoo|1.5.0
githd|hui|2.2.3
phpcs|ika|1.0.5
smarty|imp|0.3.0
vscode-psl|ing|1.11.3
path-autocomplete|ion|1.13.6
open-file-from-path|jac|1.3.3
RelativePath|jak|1.4.0
svg|joc|1.1.7
intellij-idea-keybindings|k--|0.2.38
vscode-language-babel|mgm|0.0.26
HTMLHint|mka|0.6.0
vscode-filesize|mkx|2.1.3
theme-monokai-pro-vscode|mon|1.1.15
vscode-language-pack-zh-hans|MS-|1.44.0
mssql|ms-|1.9.0
debugger-for-chrome|msj|4.12.6
php-docblocker|nei|2.1.0
material-icon-theme|PKi|4.0.1
java|red|0.58.0
vscode-xml|red|0.11.0
html5-boilerplate|sid|1.0.3
svg-preview|Sim|2.8.3
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.0.0
vim|vsc|1.13.1
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.4
html-css-class-completion|Zig|1.19.0

(14 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@adhope I cannot reproduce what you describe. I have created a new untitled file and I can delete and type fine:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/77961419-1345cd00-72da-11ea-9304-e270162e2dc7.gif)

Do you have additional steps to reproduce? Does the issue reproduce when disabling all extensions?

**Comment by adhope** [comment]
When I separate these properties into a single line, the problem disappears.
I close the editor and restart, and things get better temporarily, but they reappear when I delete characters or move the mouse quickly. At this point the mouse and keyboard can move, can copy and paste, but the keyboard in all the files are unable to type.
This might be related to my setup, right? I'm not sure.

**Comment by adhope** [comment]
@alexdima When I separate these properties into a single line, the problem disappears.
I close the editor and restart, and things get better temporarily, but they reappear when I delete characters or move the mouse quickly. At this point the mouse and keyboard can move, can copy and paste, but the keyboard in all the files are unable to type.
This might be related to my setup, right? I'm not sure.

**Comment by adhope** [comment]
@alexdima I tried to disable the available extensions in the status bar, and the problem persisted

**Comment by adhope** [comment]
I might have made a mistake, maybe because of my high CPU usage for some reason
