### ISSUE TITLE
Add support for filtering the explore pane via type-ahead search

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#9373]
- VSCode Version: `Version 1.4.0-insider (1.4.0-insider)`
- OS Version: `OS X El Capitan Version 10.11.5`

It would be great to have on-demand filtering the explorer pane to reduce the "noise" when working on a subset of files. For example, I usually work with VSCode open to the root of our repo (with many projects in it) and I am lately finding myself needing to update common things across the projects (say in package.json, project.json, etc), so right now I have to either scroll around in the explorer pane or use Goto->File -- which forces me to have to type the file name in over an over. If I could just filter the explorer pane to show all project.json files it would be quick and painless.

Thanks!

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4763
