### ISSUE TITLE
Slow performance when using Remote Desktop

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#93733]
Now that I have to work from home using Microsoft Remote Desktop, I am seeing significant delays and lag with vscode. 

The issue #5243 was closed because Remove development with vscode is now possible, but this does not work for my case.

If nothing is going to be done to fix it, can someone give me tips on what could improve it? I already tried disabling gpu acceleration, disabling some animations and stuff like that. But the performance did not change much.

Thanks

**Comment by bpasero** [comment]
I can recommend to give https://visualstudio.microsoft.com/de/services/visual-studio-online/?rr=https%3A%2F%2Fwww.google.com%2F a try that only requires a browser and no slow remote desktop thingy in between.

**Comment by psclkhoury** [comment]
@bpasero Thank you for the suggestion but I need to use RDC to access my desktop at work. Plus we have in house vscode extensions that I want to use, not to mention the compilers, the hardware, etc.

So I was looking for settings I can disable in vscode to improve performance since it is the only application that is being slow when using RDP.

**Comment by bpasero** [comment]
Understood, there is no specific setting to improve the performance for remote desktop connection. 

@deepak1556 are you maybe aware of something in Electron that could cause slowness over remote desktop connections?
