### ISSUE TITLE
Test task quick pick

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#93746]
Refs: https://github.com/microsoft/vscode/issues/90087

- [x] macOS @octref
- [x] linux @joaomoreno
- [x] windows @sbatten

Complexity: 4

---

The new task quick pick shows up from the "Run Task" command and from the ctrl/cmd+p type "task " quick access menu. macOS and linux testers, please test from the "Run Task" command, windows please test from the quick access menu.

- Test that your recently used tasks are still there. The way they are stored changed and they should be migrated.
- Test in a single folder with only extension contributed tasks. 
- Test in a single folder with only user defined tasks in a tasks.json.
- Test in a single folder with both extension contributed and tasks.json tasks.
- Test that the gear symbol shows up next to every task. Test that it opens the tasks.json so you can edit the task.
- Test that tasks with the `dependsOn` property set work properly and their dependent tasks are run correctly. Especially from the recently used section.
- Test the above from a multiroot workspace
- Test with a user setting task (Open User Tasks)
- Test a prelaunch task

**Comment by joaomoreno** [comment]
@alexr00 This seems bad: https://github.com/microsoft/vscode/issues/93925
