### ISSUE TITLE
Search editor: seems to register the same working copy multiple times

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93745]
![image](https://user-images.githubusercontent.com/900690/77910891-3055ae00-7290-11ea-9809-c7da80ef0466.png)

Not sure how I got into this state, I used the `es6.code-search` file in our repo and all editors are now closed but I cannot open that editor for the error shows up.

I think we should really move away from registering working copies for the search editor.

**Comment by bpasero** [comment]
Oh I just found steps:
* open that search
* click the refresh icon to update its contents
* click on SCM view
* click on the change

**Comment by JacksonKearl** [comment]
Ah, interesting. I will prioritize that debt item for next debt week.

**Comment by bpasero** [comment]
@JacksonKearl maybe at least for March look at how working copies are leaking, that sounds like a bug to me and will probably impact users.

**Comment by bpasero** [comment]
@JacksonKearl this seems fishy, you need to handle the disposable returned from this call:

https://github.com/microsoft/vscode/blob/f0e5bab3617d754bb3ff6e056e0ffd1e44980365/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L118

**Comment by JacksonKearl** [comment]
Okay, I don't think its a good idea to do the entire refactor this late in iteration but I can look into a minimal fix.

**Comment by JacksonKearl** [comment]
Added the `_register`, which means once a user closes the search editor diff views will work. Closing this for now given the workaround, the full issue will be a part of #89268.

For verifiers:
In vscode repo:

1. open `.vscode/searches/es6.code-search`
2. Modify and save 
3. Attempt to open the diff in SCM view.
4. See error.
5. **workaround** close the original editor, and try again to open diff in SCM, it should work.
