### ISSUE TITLE
Ability to scroll build output to first issue.

### ISSUE THREAD

**Issue by gwk** [Microsoft/vscode#9374]
- VSCode Version:
  1.4.0-Insider
- OS Version:
  OSX 10.11.5

With a basic `make` task, pressing the build keystroke causes output on the integrated terminal, which scrolls to the bottom. This is sane default behavior, but given that the terminal already autolinks to files in error lines (which by the way is absolutely fantastic!), it would be wonderful if it could scroll to the first error line.

My reasoning is that for a stream of build errors, it is best to address the first one by default, which is the least likely to be a spurious or secondary error.

Is it possible to configure a scrolling behavior for the integrated terminal, either as part of the task or perhaps a keystroke?

As always, thanks for the great work!

**Comment by Tyriar** [comment]
@gwk The terminal links to files on error lines? This is only at the feature request stage currently :confused: #7321

**Comment by gwk** [comment]
Using Insiders 4d0b2f5f15bf7011d3a99888763a7b46a5953d95  2016-07-15T12:30:04.682Z, I see absolute paths getting linkified, with a mouseover popup that suggests "Cmd + click to follow the link".

Example output:
```
swift build
Compile Swift Module 'Rappel' (9 sources)
/Users/gwk/work/rappel/src/Rappel/Lexer.swift:32:11: warning: ... 
```

**Comment by Tyriar** [comment]
@gwk within the terminal panel, not output panel? Can you paste a screenshot?

**Comment by gwk** [comment]
I'm talking about the build output from a task (in my case `make`, which is invoking `swift build`). So I guess "integrated terminal" is the wrong term.

In any case, given that linkifying in the output does work, this request still seems reasonable to me. What do you think?

**Comment by Tyriar** [comment]
Ah ok, yeah there is a feature called the "integrated terminal" as well :wink:

**Comment by alexr00** [comment]
This sounds like something that would be best solved by creating a problem matcher https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher. That way you can see your problems in the problems panel instead of having to scroll in the terminal.
