### ISSUE TITLE
Git changes and VBScript

### ISSUE THREAD

**Issue by reuvygroovy** [microsoft/vscode#93749]
When using VScode with vbscript the git functionality does not identifier changes made to the files so that I can commit and push the changes to source control. It works just fine with other extensions. Is there something that needs to be done?

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by reuvygroovy** [comment]
Started to work out of the blue. Weird. If it happens again I will reopen. Sorry, and thanks!
