### ISSUE TITLE
Test welcome content on custom tree views

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#93747]
Refs: https://github.com/microsoft/vscode/issues/92143 https://github.com/microsoft/vscode/issues/91269

- [x] anyOS @weinand

Complexity: 4

---

There's a new API which lets extensions contribute content to welcome views. We have finalized the API this milestone.

One reference implementation is the git extension which contributes certain welcome view contents to the scm viewlet, whenever no git is installed or no repository is open, etc. You can use the git extension and the https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample as starting points. 

Make sure your extension does not enableProposedAPI.
Test that:

You can contribute content to welcome views for a custom view (for example one of the custom views in the tree view sample).
Content supports Markdown style links (including title, href and tooltip) and new lines with \n
Links isolated in single lines are buttons by convention
Said content can be visible based upon a when clause
The content is only visible when the tree has no data and the tree view doesn't provide a message.

**Comment by weinand** [comment]
@alexr00 Everything works fine.
