### ISSUE TITLE
Cannot open vscode on centos 7.6 on terminal by type `code`

### ISSUE THREAD

**Issue by Siloen** [microsoft/vscode#93741]
- VSCode Version: 1.39.2
- OS Version: CentOs 7.6.1810

Steps to Reproduce:

1.I can open the program from 'Applications' shorticon
2.but when I open it on terminal by `code --verbose` ,I get 
```
No protocol specified
(code:29390): Gtk-WARNING **: 19:42:33.266: cannot open display: :0
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
This is not an issue with VS Code, most likely `DISPLAY` is not setup properly for the user on your environment.  Have you tried running other gui applications from the terminal ? Might want to ask around in https://forums.centos.org/ for solutions. Thanks!
