### ISSUE TITLE
[Insiders]: command '_executeDocumentSymbolProvider' not found when executing vscode.executeDocumentSymbolProvider command

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#93743]
At some point recently, the `vscode.executeDocumentSymbolProvider` command (documented [here](https://code.visualstudio.com/api/references/commands)) stopped working on Insiders, throwing the error above.

- VSCode Version:
```
Version: 1.44.0-insider
Commit: 13b38d2a494612ace32c4fb878824d6329d4c51e
Date: 2020-03-30T07:30:34.234Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```
- OS Version: macOS Catalina 10.15.3 (19D76)

Steps to Reproduce:

1. Create an extension that calls the `vscode.executeDocumentSymbolProvider` command, for example:

```ts
context.subscriptions.push(vs.workspace.onDidOpenTextDocument(async (d) => {
	try {
	const foo = await vs.commands.executeCommand("vscode.executeDocumentSymbolProvider", d.uri);
	} catch (e) {
		console.error(e);
	}
}));
```

This prints the following error:

```
[Extension Host] Error: command '_executeDocumentSymbolProvider' not found
    at e._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3606:469)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3606:350
    at processTicksAndRejections (internal/process/task_queues.js:85:5) (at /Users/danny/Dev/Dart-Code/out/dist/extension.js:28254:25)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

**Comment by jrieken** [comment]
The command is still there and also cannot be unregistered: https://github.com/microsoft/vscode/blob/7eee4d02e7e7b5251d226da41ad21efa50bd616c/src/vs/editor/contrib/gotoSymbol/documentSymbols.ts#L65. 

@DanTup Is that something you see on every run or was this a fluke?

**Comment by DanTup** [comment]
Weird. I noticed it in my CI test failures (only for insiders), and when I tried running it locally (using the code I pasted above) I saw the same thing. As far as I can tell, it's completely reproducible (I did search the code before raising in case it had been deliberately removed, and I found that line - but couldn't understand why it wasn't working).

Let me know if you can't repro and I'll try it on another machine.

**Comment by jrieken** [comment]
> Let me know if you can't repro and I'll try it on another machine.

Yeah, we have a bunch of tests for that command[1] and they seem fine (locally and on the build machines). https://github.com/microsoft/vscode/blob/7eee4d02e7e7b5251d226da41ad21efa50bd616c/src/vs/workbench/test/browser/api/extHostApiCommands.test.ts#L378

**Comment by DanTup** [comment]
I tried it on Windows in an empty extension and got the same error:

```ts
import * as vs from "vscode";

export function activate(context: vs.ExtensionContext) {
	context.subscriptions.push(vs.workspace.onDidOpenTextDocument(async (d) => {
		try {
			const foo = await vs.commands.executeCommand("vscode.executeDocumentSymbolProvider", d.uri);
			console.log('Good!');
		} catch (e) {
			console.log('Bad!');
			console.error(e);
		}
	}));
}
```

![Untitled](https://user-images.githubusercontent.com/1078012/77926244-ce03aa00-729d-11ea-8449-df67005c8ea2.png)

```
Version: 1.44.0-insider (user setup)
Commit: 13b38d2a494612ace32c4fb878824d6329d4c51e
Date: 2020-03-30T07:32:20.024Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Is it possible that file isn't importing imported in some cases, so the command isn't registered (but for your tests, maybe it is?). If you can't repro from source, how about in the shipped Insiders build?

**Comment by jrieken** [comment]
Indeed. Looks like @bpasero recent quick open refactoring made this file not being imported anymore.

**Comment by DanTup** [comment]
Out of interest - why wouldn't this have effected the tests? Do they somehow run differently?

**Comment by jrieken** [comment]
> Do they somehow run differently?

Those tests explicitly import said file: https://github.com/microsoft/vscode/blob/7eee4d02e7e7b5251d226da41ad21efa50bd616c/src/vs/workbench/test/browser/api/extHostApiCommands.test.ts#L43

**Comment by DanTup** [comment]
Ah, got it.

Does this mean if someone "cleaned up unused imports" in the original file, this issue could come back (and without causing test failures again)? If it's a common pattern, this seems quite risky. (I don't know if there's an easy way to avoid it though, I'm not familiar with this - just being a backseat-coder 😁)

**Comment by jrieken** [comment]
> Does this mean if someone "cleaned up unused imports" in the original file

no.

**Comment by DanTup** [comment]
Ok, though that wasn't really the focus of the comment. Being able to easily accidentally break the functionality while having all the tests continue to pass seems a bit dangerous (and isn't just hypothetical, it seems to be what happened here).
