### ISSUE TITLE
Remove tabstob in snippets after choice

### ISSUE THREAD

**Issue by BoomRaccoon** [microsoft/vscode#93740]
Description: There is a tabstop before and after the choice variable in custom defined snippets, I would prefer not having the tabstop after it. Reason is, you can add it manually if you want too but you can't omit it. People that don't need it have to double tab every time they want to go to the next tabstop.

Similar: [ #39579](https://github.com/microsoft/vscode/issues/39579)

Possible Solutions:
1. An option to change the behaviour in the settings or a key:value pair in the snippet file itself.
2. Remove the tabstop at the end of the choice.

Outcome:
So people like me could instantly jump to the next defined tabstop, while the ones that want the tabstop after the choice could just add an additional tabstop after the choice in the snippet.

**Comment by jrieken** [comment]
> There is a tabstop before and after the choice variable in custom defined snippets, I would prefer not having the tabstop after it

What you observe is correct but it's not a tab stop after choice elements, it's how completions work. E.g pressing tab accept them and moves the cursor at the end of the text.

**Comment by jrieken** [comment]
question: do you want tab to accept a completion and move to the next placeholder or should this happen for all completions-accept gestures, like enter or click

**Comment by BoomRaccoon** [comment]
I'd prefer the latter because it would be more consistent and intuative.
