### ISSUE TITLE
Split terminal follows symlink unless terminal.integrated.splitCwd is "initial"

### ISSUE THREAD

**Issue by m-thorsen** [microsoft/vscode#93753]
- VSCode Version: 1.43.3 (user)
- OS Version: Windows 10 18363, Ubuntu 18.04

Steps to Reproduce:

1. Open a project on a symlinked path
2. Open an integrated terminal
3. Set `terminal.integrated.splitCwd` to any value except "initial"
4. Split the terminal
5. The resulting split terminal follows the symlink and show the real path

Does this issue occur when all extensions are disabled?: Yes

---

Probably (?) related to #59291 #18837 

When splitting a terminal inside a symlinked path, the new terminal will follow the symlink and use the "realpath".  
This occurs only when splitting a terminal and when `terminal.integrated.splitCwd` has a value other than "initial", and never when creating a new integrated terminal.

**Comment by Tyriar** [comment]
Readlink added in https://github.com/microsoft/vscode/commit/fc860b8c0af

**Comment by Tyriar** [comment]
I don't believe it's possible to detect a shell's cwd when it's an unresolved symlink without running a command in the shell itself which we cannot do https://unix.stackexchange.com/a/659529/115410
