### ISSUE TITLE
Debug Console NEEDS a filter

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#93750]
Issue Type: <b>Feature Request</b>

There is a lot of extensions that overwhelm the debug console (including C# and Flutter extensions). The Flutter extension team blames VSCode for not having the proper API's to allow filtering.

On Flutter it's even a bit more complicated, because the guy who build the extension is not the same guy who build the Flutter plugin that is not the same guy who wrote the original native plugin that is spamming the debug console.

So, WE NEEED A FILTER ON VSCODE (a simple "contains" and "starts with") will do. It is not that hard to implement =(

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
@isidorn the new tree supports filtering and the LoadedScripts view even uses it to search in "invisible" parts of the tree. Could we not just enable the filter UI?

**Comment by isidorn** [comment]
Yeah the filtering is enabled in the debug console. Users can trigger it via cmd/ctrl + F.
Yeah it is a duplicate but this user is very persistant and keeps on reopening issues I close as duplictes. Thus I decided to leave this one open.

**Comment by weinand** [comment]
@JCKodel have you tried to use the existing filter functionality of the debug console?

**Comment by JCKodel** [comment]
> Yeah the filtering is enabled in the debug console. Users can trigger it via cmd/ctrl + F.
> Yeah it is a duplicate but this user is very persistant and keeps on reopening issues I close as duplictes. Thus I decided to leave this one open.

This user is very persistent because people like you don't realize that FIND is not the same as FILTER.

FIND is when you want to ONLY include the searched term.

FILTER is when you want to EXCLUDE the filtered term.

The problem is the spam nature of this dialog. I want to be able to FILTER **OUT** some specific lines, but see anything else (even those lines I don't EVEN REALIZE THEY EXIST YET, such as error messages.

Instead of saying "ThE uSeR iS vErY pErSistAnt", try to least understand the issue at hand. THAT'S WHAT LISTEN TO CUSTOMERS IS LIKE.

So, feel free to close this shit. Microsoft never heard user's opinion before, it was my mistake to let me believe you could have changed.

**Comment by JCKodel** [comment]
![image](https://user-images.githubusercontent.com/379339/78671212-5cd38080-78b5-11ea-8a2c-e4042b43f2cb.png)

I case you still don't understand, here's a drawing for you.

THIS IS WHAT FILTER IS LIKE.

**Comment by jerryzhoujw** [comment]
I have similar issue when I debug video player on android device.

I think this is a reasonably request which help filter logs which develop cares in case when develop can't do more config on logs from some libs.

**Comment by murr999888** [comment]
I will support the author of the thread.

In response to a request to make a debug panel filter in **VS Code**, JCKodel shows the Logcat filter in **Android Studio**.
It is perfectly!

**Comment by Elias-Graf** [comment]
Do we have access to the input/output/buffer of the debug console via extensions? If yes, I'm really surprised such an extension doesn't exist yet (or I haven't found it).

To give you an example my application has different services and each one has its "log tag". If I'm debugging a certain service, I don't want to be spammed by any other logs.

Here is a real world example:

```
[request] <Done in 187ms> fetching "https://example.com"
<WARNING> [test] cannot fill cache which was already filled
[request] <Done in 152ms> fetching "https://example.com"
[ViewFilterService] Resolved 1 waiting listener
```
I'd like to filter only "test" using something like `/\[test\]/gm`.

Of course, this is simplified quite a bit, because here it wouldn't be easier filter with your brain :D

**Comment by ArchDev** [comment]
Its actually really hard to get use of debug console in real world application which has lots of processes in. Basically, I have a wall of logs which produces faster than I can read and there is no reliable way for me to configure what I wanna see, searching is nice but it didn't really helps much as: I want to see only what I need, not search for what I need in tons of text

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/20838
