### ISSUE TITLE
Empty Viewlets cannot be drop targets

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93755]
1. Move all views in debug to another viewlet/panel so that debug is an empty viewlet.
2. Try to drop a view into the viewlet.

:bug: => there is no valid drop target.

**Comment by sbatten** [comment]
To Verify:
1. Open debug viewlet
2. Drag each view to the panel until you have an empty debug viewlet (or hide them all)
3. Attempt to drag another view into the debug viewlet
4. Verify that you can drag and drop a view into the empty viewlet.

**Comment by Tyriar** [comment]
Verified in d719bbd66c build.
