### ISSUE TITLE
css intellisense in html files seems broken

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#9375]
- VSCode Version: 1.3.1
- OS Version: OSX

Steps to Reproduce:

1. open a new html file 
2. type: 
`<html>
        <header>
                <style>
                          .test {
                                fo
                </style>
        </header>
  </html>`
3. put the cursor after fo and cmd+space

Expected: intellisense is shown. 
Actual: no suggestion. 
<img width="520" alt="screen shot 2016-07-15 at 8 12 11 pm" src="https://cloud.githubusercontent.com/assets/2146228/16892485/9d5dba40-4ac8-11e6-9967-49422f5ee86d.png">

**Comment by SirM2z** [comment]
Got the same problem

**Comment by aeschli** [comment]
A known regression, that will be fixed again when #8938 is completed (planed for August)

**Comment by maqboolkhan** [comment]
its really frustrating problem should be fix asap please
