### ISSUE TITLE
Automatic and friendly "english-please" label

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93756]
Today we have the `*english-please` label which we add to non-english issues. The bot then closes these issues. I like that but I think we can improve two things

* let the bot automatically detect the language
* let the bot reply in the authors language when closing issues

**Comment by JacksonKearl** [comment]
I can do you one better (in my opinion) #93763.

**Comment by jrieken** [comment]
Yeah, but there will be challenge of running that in our quota and then if the translation is bad we are in charge of it...

**Comment by JacksonKearl** [comment]
We get 2M characters per month of translation free. That's roughly 45 days of translating *every* issue right now, so it should be plenty if we're only translating non-english.

**Comment by jrieken** [comment]
Go for it - fingers crossed it's the best translation in town

**Comment by JacksonKearl** [comment]
6643e97666c1584319684f9620bb2041f9953cbf
