### ISSUE TITLE
showInputBox overwrites input with initial value when validation fails

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#9376]
- VSCode Version: 1.3.0, 1.4.0 commit 4d0b2f5
- OS Version: Windows 8.1 64bit

Steps to Reproduce:
```typescript
export function activate(activationContext: vscode.ExtensionContext) {
  vscode.window.showInputBox({
    value: 'initial-value',
    validateInput: (text: string) => text=='' ? '' : 'input must be empty'
  });
}
```
1. run the above extension
2. type a character into the input box
3. this will trigger validation failure
4. **bug:** the typed text will be replaced with the initial value
5. subsequent characters will not be replaced by the initial value
6. clear the text (satisfying validation and removing the error)
7. go to step 2 to repeat.

**Comment by jrieken** [comment]
Thanks for the repo and the details steps
