### ISSUE TITLE
Arranging order of plugins in code snippet popup window 

### ISSUE THREAD

**Issue by Bunkaii** [microsoft/vscode#93761]
Visual Studio Code option that will let the user arrange the order in which features of plugins show up in the code snippet window - (when you hover over code)

Example: Default order of plugins

CODE SNIPPET
Plugin 1
Plugin 2
Plugin 3

This feature option would allow the user to re-arrange this 'Default order' to whichever order they desire. Hopefully this makes sense, thanks.

**Comment by Bunkaii** [comment]
All the other feature issues are closed, this is not a duplicate of an open issue.

**Comment by Bunkaii** [comment]
I did, this feature would allow you to arrange the order in which you can view the feature of the plugins in the code snippet pop up window.

**Comment by jrieken** [comment]
@Bunkaii Please stop creating new issues! You can just leave a reply on existing issues. Anyways, the behaviour that you describe is against our design which is to sort the best matching suggestion to the top of the suggest list. The goods news that extension have control over this, so if there is something you want to be changes, in Kite for instance, then you should reach out to them.

**Comment by Bunkaii** [comment]
Sorry for the confusion around so many tickets, now I know how to properly submit a issue, thanks for all the help.

**Comment by Bunkaii** [comment]
Actually, while on this topic, is it noted that intellisense doesn't provide code snippets for many of the pandas methods? This is the reason why I have to run two plugins that do the same thing. When intellisense doesn't prove a core snippet example, I fall back to what Kite provides.
If I could get intellisense to work for all the methods, objects etc that would fix my problem!! Pleade let me know, thank you again.
