### ISSUE TITLE
Update sidebar section header colors for default themes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#93764]
## Current

<img width="80%" src="https://user-images.githubusercontent.com/35271042/77929458-8873bc80-725e-11ea-80f5-072e30e67bb4.png"/>

## Proposal

<img width="80%" src="https://user-images.githubusercontent.com/35271042/77930006-29627780-725f-11ea-96d3-b7855ec724c6.png">

**Comment by IllusionMH** [comment]
IMHO - harder to spot them now. Especially without more noticeable shadows (especially at the bottom of explorer tree)

Also might blend with Staged changes, Changes, and Untracked changes blocks (because they don't have background) if any extension adds sections to Source Control tab.

Debugger tab is even more loaded with sections that used frequently and difference in background helps.

**Comment by sandy081** [comment]
@misolori It seems more team members are liking this light weight sections. What do you think of making this change to some of the default themes?

@bpasero @jrieken FYI

**Comment by misolori** [comment]
Let's try this out and see what people think. I also now show the border in the first view (previously was hidden) since it looked really odd to not have the top border.

## Dark

![image](https://user-images.githubusercontent.com/35271042/79781619-93b48800-82f2-11ea-8915-ff451e83dbbb.png)

## Light
![image](https://user-images.githubusercontent.com/35271042/79781629-9a42ff80-82f2-11ea-9be2-122e8a80f66c.png)

**Comment by eamodio** [comment]
I like it better than now, but IMHO the borders are too strong.

**Comment by alexr00** [comment]
Looks good, but I'm not seeing that top border (above Open Editors):
![image](https://user-images.githubusercontent.com/38270282/80609591-902ea880-8a38-11ea-8591-f34d94eea1ce.png)

**Comment by bpasero** [comment]
That is intentional.

**Comment by misolori** [comment]
Yea, I forgot to update this issue after we updated but we did remove the top border after discussing it internally. Given your screenshot, I'll mark this as verified. Thanks!
