### ISSUE TITLE
Run smoke test

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#93768]
- [x] Windows @joaomoreno
- [x] macOS @misolori
- [x] Linux @connor4312
- [x] anyOS (Web) @alexr00

Complexity: 3

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by bpasero** [comment]
Given recent changes to make the smoke test more reliable, it will probably not run against stable. Please ignore the `--stable-build` option for now. Instead perform it manually:
* start stable on a fresh data dir once
* produce some UI state (opened editors) and dirty state (files, untitled)
* open insiders on the same folder and verify UI state is restored and dirty state as well

**Comment by bpasero** [comment]
@alexr00 looks like the web variant did not get a tester assigned
