### ISSUE TITLE
De-indenting multiple lines should remove a consistent number of spaces

### ISSUE THREAD

**Issue by mxmlnkn** [microsoft/vscode#93766]
Issue Type: <b>Bug</b>

This seems to be a regression for #677, which is locked.
Similary, I expect (de)indentation to apply the same number space changes to all lines and not one line getting 3 spaces removed while the other gets 4 removed.

Here is an example text:

```
    /****
     * wegweg
     */
    wergwe
```

When I deindent, I get:

```
/**
    * wegwe
    */
wergwe
```

I would have expected:

```
/**
 * wegwe
 */
wergwe
```

When I indent, I get:

```
        /**
        * wegwe
        */
        wergwe
```

I would have expected:

```
        /**
         * wegwe
         */
        wergwe
```

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-42-generic

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
theme-dark-plus-contrast|k3a|0.1.101
python|ms-|2020.3.69010
cmake-tools|ms-|1.3.1
cpptools|ms-|0.26.3

(4 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Please configure `"editor.useTabStops": false`, which will make indenting/unindenting not try to snap things to tab stops.
