### ISSUE TITLE
Test custom editors 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#93767]
Test for #77131

- [x] Windows @eamodio 
- [x] Linux @jrieken 
- [x] MacOS @bpasero 

Complexity: 5

---

**Summary**
The custom editor API is up for finalization. In this exploratory test plan item, I'd like you to try implementing a custom editor as if you were an extension developer (possibly try embedding an existing html+js library into a custom editor).

**Links**
- [Finalized API](https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L7974)
- [Draft extension samples](https://github.com/microsoft/vscode-extension-samples/tree/custom-editor-examples/custom-editor-sample)
- [Draft documentation](https://github.com/microsoft/vscode-docs/blob/custom-editors/api/extension-guides/custom-editors.md)

**Areas to focus on**

- API docs and intellisense (for both the TS api and contribution point)

    Do they make sense? Anything missing?

- Editing and basic saving

    Make sure undo, redo, and revert work for `CustomEditor` and `CustomTextEditor`. Make sure the VS Code UI updates correctly and that all fields on `CustomDocument` are updated correctly. Are there anything that prevents you from implementing your custom editor or that would simplify things?

- Hot exit and backup

    Make sure custom editors are properly restored when the window is reloaded

- The `Reopen with` command the the `workbench.editorAssociations` setting

    If there are multiple custom editors for a single resource, make sure you can use `workbench.editorAssociations` to configure which one is used by default

- Try finding cases where a custom editor behaves differently from our normal editors 

    Especially around renaming/deleting files and dirty states

**Comment by bpasero** [comment]
@jrieken @eamodio testing hot exit is best done installing the extension locally into VSCode as backups are not working 100% identical when running extension development vs. running normally. This applies to test based custom documents at least.

**Comment by bpasero** [comment]
I focused on non-text custom editors this time and felt it was a nice API to work with this time. I wrote a simple binary editor that allows to edit the first 3 bytes of any file (https://github.com/bpasero/vscode-custom-editor-bom). 

I was not using any of the fields in `CustomDocument` and would not know why I would need them. I felt I could implement the methods without the need to go into the document itself, but I probably also implemented a very simple custom editor. 

I ended up delegating each call for edits into my custom document, so I wonder why these methods are not simply provided as part of the custom document, maybe optional to be only implemented when you support editing.

**Comment by jrieken** [comment]
> I ended up delegating each call for edits into my custom document, so I wonder why these methods are not simply provided as part of the custom document, maybe optional to be only implemented when you support editing.

I am implementing an editor that opens zip-files and that allows to remove entries and share that feedback. Somehow `CustomDocument` and `CustomEditorEditingDelegate` compete against each other because they both try to encapsulate document knowledge. I would rather have methods on `CustomDocument` that I can optionally implement. Optionally because if I cannot implement hot-exit that I should be free to do so and we should have that gracefully, e.g by telling the user

**Comment by jrieken** [comment]
[editor-test.zip](https://github.com/microsoft/vscode/files/4410449/editor-test.zip) dumping my work-in-progress extension here. Getting a custom editor to show is really simple, editing is a not cool

**Comment by eamodio** [comment]
Tested TextDocument-backed custom editors -- looks good! I do wish there was a more direct way to listen to change events for a document, rather than having to use `workspace.onDidChangeTextDocument` but that is outside the scope of this.
