### ISSUE TITLE
API support to cancel showInputBox

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#9377]
Feature request: API support to cancel `showInputBox`. E.g. add a `vscode.CancellationToken` to its options.

Example use case: I've implemented a custom text search, using the `validateInput` option to update the search as the user types. Certain events cancel the search, in which case, the input box should disappear.

**Comment by jrieken** [comment]
makes sense

**Comment by jrieken** [comment]
@siegebell This just landed in master. Please try it out
