### ISSUE TITLE
Integrated terminal doesn't wait for confirmation

### ISSUE THREAD

**Issue by yankyhoffman** [microsoft/vscode#93775]
I have the setting `"terminal.integrated.confirmOnExit": true,` set to `true` to ensure that I don't have VSCode kill a terminal session without confirmation, however when I do close a VSCode instance (using `CTRL+SHIFT+W`) I get the fleeting glimpse of the confirm dialog but vscode just closes without asking for confirmation. If there is another open instance the confirmation dialog stays visible but the vscode instance is already killed.

- VSCode Version:
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic
- OS Version:
Ubuntu 19.10 (Gnome 3.34.2)

Steps to Reproduce:

1. Start process in integrated terminal.
2. Close VSCode

2 Screencasts from the issue
![vscode-integrated-temrinal](https://user-images.githubusercontent.com/41123800/77942261-57f54800-7289-11ea-94c3-03243903c37b.gif)
When having only a single instance open

![vscode-integrated-temrinal2](https://user-images.githubusercontent.com/41123800/77942316-6e9b9f00-7289-11ea-8fb3-0ec1dbaf8c33.gif)
When having multiple open instances

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by yankyhoffman** [comment]
Yes I just tried the insiders build and the bug is indeed fixed

**Comment by yankyhoffman** [comment]
Thanks
