### ISSUE TITLE
Make the editor toolbar buttons configurable

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#9378]
- VSCode Version: 1.3.1
- OS Version: Arch

Split editor has a dedicated button at the top-right of the editor. That functionality has never been a button I want. What I really do want very frequently though, is a move-editor-right button in that same place.
It would be nice if we could configure the button(/s) in that location.

**Comment by bpasero** [comment]
In theory with the work @jrieken does we could add an alternate action that does the move instead of split (e.g. when you press the Alt key while hovering over the button).

**Comment by jrieken** [comment]
Maybe a dupe of #9285. The ideas is that we will have something like `menus.json` which allows users to go the full mile. Challenge is that we still miss some underlying refactorings to really enable this

**Comment by gko** [comment]
Any updates on this?

**Comment by jrieken** [comment]
Closing this as duplicate of #9285
