### ISSUE TITLE
Test: Contributing a view container to the panel

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93785]
Refs: #41686 

- [x] windows @fiveisprime
- [x] macOS @chrmarti
- [x] linux @joaomoreno

Complexity: 2

---

This milestone, we lit up the ability for an extension to contribute a view container to the panel and thus a view directly to the panel. Much like contributing to the `activitybar`(see documentation https://code.visualstudio.com/api/extension-guides/tree-view#view-container), you can simply contribute to `panel`.

Test that you can:
1. Create a custom view container in the panel.
2. Contribute a custom view to the panel.
3. Move other views into your panel.
4. Move your views out of your panel.
5. Reset your view by right clicking its header when it is in a different location.

**Comment by joaomoreno** [comment]
@sbatten It would be great to have snippets in place so I could test the actual feature, instead of spending 90% of the time trying to scramble for right setup.

**Comment by joaomoreno** [comment]
For other testers:

```json
		"viewsContainers": {
			"panel": [
				{
					"id": "vc1",
					"title": "Joao",
					"icon": "icon.jpg"
				}
			]
		},
		"views": {
			"vc1": [
				{
					"id": "v1",
					"name": "JOao View"
				}
			]
		}
```

**Comment by joaomoreno** [comment]
Works great! 👏
