### ISSUE TITLE
Test: New Drag and Drop Feedback and View Relocation

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93786]
Refs: #92299 

- [ ] anyOS @eamodio
- [x] anyOS @sandy081

Complexity: 3

---

This milestone, the drag and drop feedback for views was changed to become more intuitive and support moving across panel, sidebar, and activity bar.

To Test:
1. Attempt to create various layouts by dragging and dropping them between the 3 parts.

Feel free to use the following as inspiration: [Achieve the following layout.pdf](https://github.com/microsoft/vscode/files/4405018/Achieve.the.following.layout.pdf)

**DO STEP 1 BEFORE CONTINUING TO PROVIDE UNBIASED FEEDBACK ON THE INTUITIVE NATURE**

2. Try dragging a view to make a new panel/activity bar icon by dragging a single view header to the panel/activity bar area (inserting it where you like).
3. Try dragging views into other containers.
4. Try dragging views into unopened containers by hovering the icon while dragging.
5. Try reordering views.
6. Try reordering composites.
7. Use the command `Move Focused View`. By default this has no keybinding, but it is necessary to bind it to use it since it depends on focus.
8. Play around, use the reset view location command by right clicking the view header or reset all view locations from the command palette.

**Comment by sandy081** [comment]
@sbatten Good job. I liked it.

**Comment by eamodio** [comment]
@sbatten Awesome work!
