### ISSUE TITLE
Extensions not showing

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#93783]
Issue Type: <b>Bug</b>

When clicking on the Extensions tab, none of my installed extensions are showing. (This same issue came up on the latest Azure Data Studio insiders update too)

![image](https://user-images.githubusercontent.com/13488/77949898-b6c0be80-7295-11ea-836c-417bbc2ac3fb.png)

Error in console:

```
  ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at e.removeItemFromDOM (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:477:131)
    at e._splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:470:593)
    at e.splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:470:328)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:31:107
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:31:94)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:906:425
    at t.EventBufferer.bufferEvents (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:102:214)
    at e.splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:906:392)
    at e.set model [as model] (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:914:276)
    at t.EnabledExtensionsView.setModel (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6478:16)
    at o (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6464:842)
```
VS Code version: Code - Exploration 1.44.0-exploration (2766badcb6c29445f5289033f1343f373802315c, 2020-03-27T21:34:34.236Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (2.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|15%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.2
githistory|don|0.6.3
auto-close-tag|for|0.5.6
output-colorizer|IBM|0.1.2
mads|mir|0.0.5
csharp|ms-|1.21.15
js-debug-companion|ms-|0.0.4
js-debug-nightly|ms-|2020.3.2717
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|4.0.1
msbuild-project-tools|tin|0.3.3
vscodeintellicode|Vis|1.2.6

(5 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
NOT a duplicate

**Comment by connor4312** [comment]
I see this as well 

![](https://memes.peet.io/img/20-03-acd89970-882c-4538-b18b-66ac673ed487.png)

Sometimes this:

![](https://memes.peet.io/img/20-03-ce0c063d-cd71-42e5-8d81-226e9d9264cd.png)

In all cases, I cannot view any extensions

**Comment by connor4312** [comment]
Seems like something cached locally. It continues if I use a different settings directory, and if I comment out all my user settings. But explicitly using a different user-data-dir fixes it.

**Comment by jtsom** [comment]
I'm seeing this problem in both Azure Data Studio:
Version: 1.17.0-insider
Commit: b23413d94421319b3e543f65a5adb0dce6027cc6
Date: 2020-03-31T05:47:50.065Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

and the Exploration version of VSCode:
Version: 1.44.0-exploration
Commit: 2766badcb6c29445f5289033f1343f373802315c
Date: 2020-03-27T21:34:34.236Z
Electron: 8.2.0
Chrome: 80.0.3987.158
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.4.0

Neither of which have an option for Settings Sync.

My latest VS Code Insiders does NOT have this problem and I do NOT have Settings-sync turned on.

**Comment by jtsom** [comment]
I was able to make the extensions show up in both VS Code Exploration and Azure Data Studio by adding this in the settings.json file, even though it's an unknown setting:
`"sync.ignoredExtensions": []`

That made the extensions show up and got rid of that error I was seeing. 

I had to also quit and relaunch the application also.

**Comment by sandy081** [comment]
Are you able to reproduce it in our insiders or stable version?

**Comment by jtsom** [comment]
As I mentioned above, I was NOT seeing the issue in the latest Insiders. I do not have the stable version installed, so can't speak to that. (The problem showed up with the Exploration VC Code and Insiders Azure Data Studio released 3/30

**Comment by connor4312** [comment]
I was on the latest insiders from the 30th. I didn't have the issue in stable, because as mentioned it seems to be some bad data in the user data dir which is different for stable.

**Comment by sandy081** [comment]
Sorry, I am not aware of those builds and I am not helpful as I can't repro.

**Comment by dinvlad** [comment]
I'm seeing this with the latest Exploration build..

**Comment by sandy081** [comment]
It is hard to fix an issue that does not happen on our insiders or stable. I am not sure what this exploration build is and what features it contain and does not. So please check if it happens on insiders or stable and provide steps to repro.

**Comment by dinvlad** [comment]
Mine is the exploration branch from https://github.com/microsoft/vscode/issues/74098 . It keeps being regularly updated, so I don’t think providing a specific version would help. To replicate, please download using the links from https://github.com/microsoft/vscode/issues/74098#issuecomment-540827368 and then force auto-update.
