### ISSUE TITLE
Cannot open absolute file with ctrl+p anymore

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#93793]
* on Windows, launch `yarn run watch`
* have a compile error somewhere
* select the file path from the console:
![image](https://user-images.githubusercontent.com/5047891/77962830-9f58f400-72dc-11ea-9673-862d8c7bedde.png)
* `C:/Alex/src/vscode/src/vs/workbench/browser/actions/layoutActions.ts(28,1)`

It always worked for me that I could select that and paste it in the Ctrl+P picker:

* on stable:
![image](https://user-images.githubusercontent.com/5047891/77962955-d4654680-72dc-11ea-8d4d-8c83df08db0d.png)
* on insiders:
![image](https://user-images.githubusercontent.com/5047891/77963015-ee068e00-72dc-11ea-9a8a-4fbbd5db4ff3.png)

**Comment by bpasero** [comment]
Good catch, a regression where I am not matching on the posix style separators properly. Should be fine with https://github.com/microsoft/vscode/commit/a19857db3dd522cb2d2f93c60206bbd71eab0144
