### ISSUE TITLE
Test Product Icon Themes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#93798]
Refs:  #92791

- [x] anyOS @alexdima
- [ ] anyOS @eamodio

Complexity: 4

---
Product icons themes allow theme authors to customize the icons used in our built-in views: all icons except file icons (covered by file icon themes) and icons contributed by extensions.

Internally all our product icons come from a icon font (codicon font), and each icon has a well-known name (e.g. codicon). Our view use icons by that name.

Product icons themes can assign new icons to these names. Again, the icons must come from an icon font. The product icon theme file specifies the font(s) it uses and maps its font characters to the icon names. 

Test that you can add a new product icon theme.

An example of a product icon theme can be found here:

- contribution: https://github.com/microsoft/vscode/blob/b2d0292a20c4a012005c94975019a5b572ce6a63/extensions/vscode-colorize-tests/package.json#L50
- theme file: https://github.com/microsoft/vscode/blob/master/extensions/vscode-colorize-tests/producticons/test-product-icon-theme.json

- create a new extension (no yeoman generator yet)
 - the extension needs to have proposedApi enabled
- add an entry to new contribution point `productIconThemes`
  - Test that you get code completion in the package.json
  - Test that the hover descriptions make sense
- create a new product icon theme file. Use suffix `-product-icon-theme.json` to get schema support when editing the theme file
  - Test that you get schema support 
     - code completion of all known icon names
 - if you open the extension in dev mode
      - the theme should be automatically be selected when the window opens
      - changes to the theme file should be applied live (the theme file is watched)
 - test that you can select the theme in the settings (`workbench.productIconTheme`)
 - test that you can select the theme with command `Preferences: Product Icon Theme`. 
 - on purpose no entry in the Settings gear or the global menu
- create a VSIX and install the theme in the extensions view.
   - test when the extension is installed you automatically get a theme selection picker
   - test that the extension view shows the `Set Product Icon Theme` button and context menu.

**Comment by eamodio** [comment]
@aeschli I can't seem to get this to work at all - either in debug mode or as a vsix. I'm sure I'm doing something wrong, but I can't tell what -- here is my repo: https://github.com/eamodio/vscode-amethyst-icon-theme

**Comment by aeschli** [comment]
Sorry, sorry, I made a silly error when adding the 'proposedApi' check. 

I pushed a fix (https://github.com/microsoft/vscode/commit/20b88fa0694cae8e46ffd305a1450ba58ae6065b) and triggered a rebuild. In the meantime please test out of source.

**Comment by aeschli** [comment]
@eamodio New insiders is out: Version: 1.44.0-insider
Commit: 20b88fa0694cae8e46ffd305a1450ba58ae6065b
Date: 2020-04-01T08:29:34.507Z

I verified that your theme is now available and works once you fix the font path (`"path": "./ElegantIcons.woff"`)

**Comment by alexdima** [comment]
Nice!

**Comment by eamodio** [comment]
Looks great, except for #94215
