### ISSUE TITLE
Test: Embedded language server documentation

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#93809]
Refs: https://github.com/microsoft/vscode/issues/47288

- [x] anyOS @aeschli 
- [x] anyOS @roblourens 

Complexity: 3

---

We have new documentation for implementing embedded language servers:

Please take a look at https://code.visualstudio.com/api/language-extensions/embedded-languages (you might need to read https://code.visualstudio.com/api/language-extensions/language-server-extension-guide as a preparation). Follow it through and open issues for things that's unclear/confusing to you. 
Also read the two samples at
- https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-embedded-language-service
- https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-embedded-request-forwarding

Make sure the implementation works on your machine and you can follow through the code.

**Comment by roblourens** [comment]
I also filed https://github.com/microsoft/azure-pipelines-vscode/issues/304 but I don't know if that's good advice or if there's a different way we should work around it, or even by making it more obvious in the vscode debug UI somehow.

**Comment by roblourens** [comment]
This would be less confusing if the sample extensions didn't duplicate built-in functionality, it sounds like it's already the plan to change that 👍
