### ISSUE TITLE
Test terminal link debugging

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#93806]
Refs: https://github.com/microsoft/vscode-js-debug/issues/387

- [x] macOS @egamma
- [x] windows @chrisdias

Complexity: 2

---

Please try this locally and through a remote workspace (SSH, WSL, VS Online). Note that web will not work, and should show an appropriate error message (https://github.com/microsoft/vscode-js-debug/issues/409).

`for (const workspaceType of ['local', 'remote']) {`

 - Have a workspace with some web app in it. A simple HTML file and JS script, or something complex like a React app, anything works.
 - Set a breakpoint in your web app code.
 - Open a debugger terminal from the command pallete
 - Start the app. To serve a static site, the `serve` CLI/package from npm is good.
 - Ctrl+click on the link to your app printed in the debug terminal, e.g. `http://localhost:8080`
 - Verify that a browser is opened, you can hit your breakpoint, and things behave normally.

`}`

**Comment by egamma** [comment]
Really nice!

Tested locally and using Remote Containers with the https://github.com/microsoft/vscode-remote-try-node sample.

**Comment by chrisdias** [comment]
Tested on Mac and on Windows with WSL. Looks great.
