### ISSUE TITLE
Argument Highlighting targeting wrong argument

### ISSUE THREAD

**Issue by Aaryan-M** [microsoft/vscode#93803]
Issue Type: <b>Bug</b>

In Python, create a function with multiple arguments. Make the name of one argument contain the name of a preceding argument.

For example:
```python
def foo(arg1, text, text_length, arg4):
    pass
```

When typing that function in Visual Studio Code, it attempts to help you by showing a little window showing all of the arguments, and also bolding and underlining the name of the argument you are currently entering. However, when you are at the argument with a name that shows up in the name of a following argument, the characters that make the name of the argument you are currently typing will be bolded in the name of the second argument.

For example:
When typing
```python
foo(<cursor>)
```
VSCode correctly displays: 
foo(**arg1**, text, text_length, arg4)

However, when typing:
```python
foo('this is arg1', <cursor>)
```
VSCode incorrectly displays:
foo(arg1, text, **text**_length, arg4)
Instead of:
foo(arg1, **text**, text_length, arg4)

![Screenshot (12)](https://user-images.githubusercontent.com/48146614/77970474-22f4ef80-72a1-11ea-821c-a928c77b68fc.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.95GB (4.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
code-runner|for|0.9.17
csharp|ms-|1.21.15
python|ms-|2020.3.69010
deepdark-material|Nim|3.2.1
indent-rainbow|ode|7.4.0
open-html-in-browser|pea|2.1.2
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1
vsc-material-theme-italicize|Ser|0.0.14

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
This is coming from the python extension.
