### ISSUE TITLE
[ASP.NET Core] Razor incorrect syntax when inside <script> tag

### ISSUE THREAD

**Issue by Bruno2049** [microsoft/vscode#93800]
- VSCode Version: 1.43.2
- OS Version: Windows 10 (version 1909)

Steps to Reproduce:

1. Add <script type="text/javascript"></script> tag to .cshtml file.
2. Add Razor code inside that tag (ex.: printscreen below)

![image](https://user-images.githubusercontent.com/6771565/77968283-e21bcb80-72de-11ea-8af1-79e2c628f58c.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes, the issue occurs the same way.

**Comment by alexr00** [comment]
Can you please provide a full copy/paste-able example?

**Comment by Bruno2049** [comment]
@alexr00 So this errors are shown in the **Page.cshtml__virtual.html** but I will attach a copy of the Page.cshtml

Here is the copy of the file: [Page.zip](https://github.com/microsoft/vscode/files/4415635/Page.zip)

**Comment by alexr00** [comment]
I am not able to see the same behavior. Are you sure you disabled all extensions?
![image](https://user-images.githubusercontent.com/38270282/78250216-d4896000-74ef-11ea-932a-08e33665da43.png)

**Comment by Bruno2049** [comment]
@alexr00 if I disable the only extension I have, that is the **C# extension from Microsoft**, the VSCode don't show any error, but with that extension disable the code isn't analized
