### ISSUE TITLE
Never show again storage keys are registered too late for syncing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93817]
Never show again storage keys are registered for syncing after the notification is shown. This is too late because the corresponding state is only synced (pulled) after the keys are registered and because of this these notifications are shown on other machine.

For example try out
- On first machine, Install a language pack on one machine 
- When the prompt comes, choose not to show it again
- On a second machine, enable sync

🐛 Prompt is shown

@bpasero 
~~Probably this a new kind of key for which state has to be synced always. I would probably introduce a new kind of keys called `non-versioned` which gets synced always. It means you do not need to provide version while registering.~~

Edit: I do not think above solution works as it only fixes for the dialog which will be shown after. Existing dialogs which are asked not to be shown will not be synced because their keys will never get registered. All do not ask keys shall be registered outside notification service by respective owners always.

**Comment by bpasero** [comment]
Yeah good catch, instead of registering from within the notification service, we need to move this out. That is unfortunate, because we will constantly have to make sure that these keys are synced once new ones are being added...

**Comment by sandy081** [comment]
Yeah that's necessary for syncing. For a moment I was tempted to have ignored list (other way around) like in settings, but I am worried that what if someone introduce a state storing paths or some sensitive info and forget to register it as ignored state.
