### ISSUE TITLE
Test extension/context menu contribution "extension" context key

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#93821]
Refs: #93206

- [x] anyOS @egamma
- [x] anyOS @dbaeumer

Complexity: 1

---

## Testing

Create an extension that contributes a menu item to the `extension/context` contribution point of the Extension Viewlet, and use the new `extension` context key to only show it for a particular extension.

**Comment by egamma** [comment]
Verified with the following contribution:

```json
		"menus": {
			"extension/context": [
				{
					"command": "extension.helloWorld",
					"when": "extension == ms-vscode.azure-account"
				}
			]
		}
```

**Comment by dbaeumer** [comment]
Just for completeness: the documentation needs to list the new `extensions/context` path and should also list the available groups inside the context menu (see https://code.visualstudio.com/api/references/contribution-points#contributes.menus)
