### ISSUE TITLE
launch.json - dynamic args and better env support

### ISSUE THREAD

**Issue by paulbouwer** [microsoft/vscode#93823]
## Description

> This issue is related to debugging a Go based application, but I see the feature as applicable to all languages.

A command line based application can often have complexity involved in the arguments that must be passed to it. The current options available in vscode around the `launch.json` file do not cater for some more advanced scenarios.

When debugging, it is useful to extract any sensitive credentials into an external file (e.g. `secrets.env`) so that these can be excluded via `.gitignore` and not committed to the repo. These variables should be easy to access in the `args` attribute if the application cannot accept them via environment variables.

The values for arguments sometimes have to be dynamically constructed via possibly complex mechanisms. The `args` attribute should allow for dynamic creation of an argument via an external process - possibly this is a task executing a script and capturing the output to use as the value for the arg.

## Example

Here is a real scenario we are trying to make work.

With the following files, we'd like the key value pairs in the `secrets.env` file made available as environment variables that are accessible in the `args` attribute.

So the `--secrets` argument under `args` should resolve the value for `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` present in the `secrets.env` file.

The `--attributes` argument under `args` is built on each debug execution by dynamically serialising an editable yaml file to json and substituting a number of environment variables in the contents.

This is not currently possible to achieve. Even tasks to not provide an approach to run a script and pull back the output into the value of the argument here.

**secrets.env**

```
AZURE_CLIENT_ID=<the client id value>
AZURE_CLIENT_SECRET=<the client secret value>
```

**launch.json**

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Application",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "program": "${workspaceFolder}/main.go",
      "envFile": [
        "${workspaceFolder}/secrets.env"
      ],
      "args": [
        "--secrets={\"clientid\": \"${env:AZURE_CLIENT_ID}\", \"clientsecret\": \"${env:AZURE_CLIENT_SECRET}\"}",
        "--attributes=<contents of file with ${env:VAR} references>",
        "--debug=true"
      ]
    }
  ]
}
```

## Desired Functionality

1. Ability to use `envFile` and have those environment variables available in `args`.
2. Ability to dynamically generate the value of an arg in `args` and also have the environment variables defined in `envFile` available to generator process for substitution.

## Related Issues

There is an existing issue related to using values from the `envFile` in `args`:

- [Issue #89825 - launch.json: values from envFile not substituted in args](https://github.com/microsoft/vscode/issues/89825)

**Comment by weinand** [comment]
As already explained in #89825 "envFile" is a node.js concept and not known to VS Code.
We have no plans to turn "envFile" into a VS Code concept.

For the "secret values" feature I suggest to create an extension that provides that functionality as a set of commands which can be used via the `${command:COMMAND_ID}` syntax in task.json and launch.json.

**Comment by dayothompson** [comment]
Hi Paul, I'm quite new to using VS code.
Is your solution only for service principal Authentication on Azure?
I'm using Power BI.

**Comment by paulbouwer** [comment]
I still see the ability to define secrets in an external file as valuable. This allows the secrets to be excluded from commits and still be pulled in to the args or env of the process being executed via the `launch.json` file.

The origin of the `envFile` is not as important as the workflow it enables across all languages.

@weinand - I'll have a look at how to implement this using commands. Thanks for the tip.
