### ISSUE TITLE
Folder created in %APPDATA% in Portable Mode

### ISSUE THREAD

**Issue by github-account1111** [microsoft/vscode#93828]
- VSCode Version: 1.43.2
- OS Version: Windows 10 1809 LTSC, 1909 (tested on both)

Steps to Reproduce:

1. Download and extract a zip of the latest version (1.43.2 at the time of writing).
2. Create a `data` folder inside.
3. Launch `Code.exe`.
4. A `Code` folder with an empty `Dictionaries` folder appears in `Roaming`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@bpasero @deepak1556 Are you aware of a `Dictionaries` folder from electron?

**Comment by bpasero** [comment]
First time I hear this folder name, no.

**Comment by deepak1556** [comment]
Thats from when electron switched to use chromium spellchecker https://github.com/electron/electron/pull/20692 , our custom build has the spellchecker disabled so this directory should never have been created, seems like some orphaned code path I missed. Will look into it next iteration.

**Comment by omnjpa27516** [comment]
Please fix it, thanks.

**Comment by smac89** [comment]
Just noticed the same thing on Linux. Portable mode seems to recreate `$XDG_CONFIG_HOME/Code/Dictionaries`. Even after deleting, it is recreated when I restart VScode

**Comment by Kein** [comment]
Reproduced on 1.53.2

**Comment by deepak1556** [comment]
This should now be fixed in latest insiders and upcoming stable `1.59`.

**Comment by github-account1111** [comment]
Okay! I'll lyk if it fixes it for me once stable rolls out.
