### ISSUE TITLE
Consider to remove border feedback when drop location is clear

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93839]
I find the border drop feedback visually quite overwhelming, given it is not needed in many cases. Should it only appear when needed? As for example in this case, why do I need to see it? Should it only show for when dragging view containers?

![Kapture 2020-03-31 at 10 15 04](https://user-images.githubusercontent.com/900690/78003148-84b46880-7338-11ea-8be2-3fe349aba346.gif)

**Comment by sbatten** [comment]
I would find it strange if we are not consistent. Eric suggested having a theme color for it which would allow a user/theme to hide it always if they find it not helpful.

**Comment by bpasero** [comment]
I don't like the looks especially because it is now different from editor drag and drop where we do not have such a border.

**Comment by sbatten** [comment]
Editor is different because we always "split" there and this is always "insert". However, what I can do is only use the border on collapsed views, (the major reason it exists)

**Comment by Tyriar** [comment]
Seems like a the way to go to show it only when it adds value, otherwise it's inconsistent with the editor.

**Comment by sbatten** [comment]
i'll try collapsed

**Comment by sbatten** [comment]
To Verify:
1. Try rearranging views inside a single view container (both sidebar and panel).
2. Note that only collapsed views in sidebar use the border feedback.
