### ISSUE TITLE
Offer a "Reset View Locations" on a container?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93836]
I am happy to find this action:

![image](https://user-images.githubusercontent.com/900690/78002533-abbe6a80-7337-11ea-9667-e7b4d92b3c17.png)

I wonder if there should be a similar action on the right click menu of an actual view container to reset all views that are inside back to the original?

![image](https://user-images.githubusercontent.com/900690/78002580-be38a400-7337-11ea-8f17-7e5ba400d94c.png)

**Comment by sbatten** [comment]
due to #96119, we now have a reset command from the container's perspective already, therefore after consideration, I am opting to not add this command to avoid cluttering the context menus

**Comment by sbatten** [comment]
If you feel strongly otherwise, let me know
