### ISSUE TITLE
Wording of default message in quick outline 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93840]
re https://github.com/microsoft/vscode/issues/93643

* trigger quick outline where it cannot be triggered
* see the message below, the last part reads weird

<img width="696" alt="Screenshot 2020-03-31 at 10 11 40" src="https://user-images.githubusercontent.com/1794099/78002819-08ba2080-7338-11ea-9edf-46eb846c7625.png">

How about

- The active text editor does not provide [symbols|symbol information|outline information]
- To go to a symbol, open a text editor with symbol information first

**Comment by gjsjohnmurray** [comment]
>     * To go to a symbol, open a text editor with symbol information first

If this option is preferred I suggest a slight variation:

* To go to a symbol, first open a text editor with symbol information.

**Comment by bpasero** [comment]
We actually need 2 messages:
* no editor or no text editor open
* text editor open but no symbol information

I went with:
* `To go to a symbol, first open a text editor with symbol information.`
* `The active text editor does not provide symbol information.`

**Comment by hamaney** [comment]
I find the new message missing some directions to where/how to provide some symbol information. Finally I figure out that I have to enable the c/cpp extension for the workspace.
