### ISSUE TITLE
Output as sidebar view: dropdown issues

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93841]
Moving the output as a view into the side bar, I see issues:
* clicking the dropdown collapses the view
* the dropdown looks a bit cramped

![image](https://user-images.githubusercontent.com/900690/78003300-bb8a7e80-7338-11ea-87f8-0e167aab4509.png)

**Comment by sbatten** [comment]
To Verify (on MacOS):
1. Move Output to Sidebar by itself and verify the channel selector functions and looks correct.
2. Move Terminal to the Sidebar by itself and verify the terminal selector functions and looks correct.
3. Repeat 1 and 2 when they are both in the same viewlet and the same panel.
