### ISSUE TITLE
DND: blurring editor area is not helpful for me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93849]
I find the blurring of the editor area rather distracting than helpful, especially after I got used to how things work, now when I start to drag a view e.g. in the panel, I see this large UI update everytime. 

I suggest to not have this feedback.

**Comment by joaomoreno** [comment]
This looks really distracting... I'm with @bpasero

**Comment by misolori** [comment]
I actually found it surprisingly helpful (wasn't expecting that). Maybe make it a setting for people to turn off?

**Comment by joaomoreno** [comment]
I get that feedback could be helpful... but blur? How about fading it out instead?

**Comment by sbatten** [comment]
It currently is fading out, but very slightly. When I experimented, I found that minimum blur + 3% dimming was the most subtle difference while still being helpful. Removing the blur will mean I have to dim it further or it's doing almost nothing in some themes. If you find a combination that you think feels nicer, I am open to it, but I believe having something here is valuable.

**Comment by joaomoreno** [comment]
@misolori to the rescue.

**Comment by sbatten** [comment]
A smoother version of the blur effect came in this milestone. Did anyone notice? Do people prefer it?

**Comment by joaomoreno** [comment]
I didn't notice, but I still dislike it. It's better, but the fact that it's blurry is really out of place with our sharp UI. If we keep it this way, please make the unblur animation much faster than what it is.

**Comment by bpasero** [comment]
Same

**Comment by sbatten** [comment]
will try a different variant during debt week without blur
