### ISSUE TITLE
Web: terminal shutdown cannot be long running

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93843]
This code causes trouble in web: 

https://github.com/microsoft/vscode/blob/a19857db3dd522cb2d2f93c60206bbd71eab0144/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L181

Since there is no long running shutdown, all I can do is to prevent the shutdown entirely.

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/commit/a86b990062465c1b82fce7b5259e9ee78d645c53 as workaround. Please check if there is any better solution possible.

**Comment by Tyriar** [comment]
Looks good to me, thanks.
