### ISSUE TITLE
Explorer: excluded files do not show dim when appearing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93844]
Refs: https://github.com/microsoft/vscode/issues/93298

This is using light+ theme:

![image](https://user-images.githubusercontent.com/900690/78004607-a0b90980-733a-11ea-8c62-a42409d713d5.png)

**Comment by bpasero** [comment]
Actually same for dark theme.

**Comment by bpasero** [comment]
Hm, this worked after window reload. Not sure maybe a timing issue.

**Comment by isidorn** [comment]
I can not reproduce this easily.
Do you have better steps: the only corner case I could hit is the following:
file has a git decoration color (let's say green) but it should be hidden. We show green, and you commit it. It is no longer green - but now it is not gray. Is this the same scenario you were hitting?

**Comment by bpasero** [comment]
Yeah cannot reproduce now either, not sure what happened.
