### ISSUE TITLE
Explorer: decorations are not dimmed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93847]
Refs: https://github.com/microsoft/vscode/issues/93298

I am not sure if that is intentional, but a decorated hidden explorer item that appears is not showing dimmed:

![image](https://user-images.githubusercontent.com/900690/78005420-d3afcd00-733b-11ea-800e-003d5fdba78e.png)

**Comment by isidorn** [comment]
This is intentional, decorations take higher priority which I think makes sense.
If you disagree feel free to reopen and we can make sure that the dimmnes takes priority
