### ISSUE TITLE
unregister handler for the 'type' command.

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#9384]
Feature request: provide an API to unregister a handler for the 'type' command.

If an extension only needs to register the 'type' for specific scenarios (e.g. only some editors), it is forced to handle it all the time and call 'default:type' to delegate back to vscode.

However, even a handler that immediately delegates back to 'default:type' introduces a lot of lag, and can cause characters to be entered out of order w.r.t. non-'type' editing commands like cursor movement, paste, etc.

**Comment by alexandrudima** [comment]
@siegebell That is an API we've added specifically with VIM extensions in mind. Perhaps your use-case can be implemented differently (i.e. not registering the `type` command?)

**Comment by siegebell** [comment]
@alexandrudima My use case is to implement [Visual Studio's incremental search](https://msdn.microsoft.com/en-us/library/f27e8wzh(v=vs.90).aspx), which allows the search term to be constructed "inline" without changing the focus away from the editor (see #9588 and #9444).

Alternatives to implementing this feature would be for vscode to directly support inline incremental search or else provide an inline text input function. At the moment, my search extension also supports `showInputBox` instead of registering the `type` command, but it is not quite the same experience.

**Comment by alexandrudima** [comment]
@siegebell There is also the option to make a PR against vscode, sounds like a cool feature.

**Comment by alexandrudima** [comment]
Upon further thought, there is a bug hiding in here. `registerCommand` returns a `Disposable` which, when disposed, should unregister your custom `type` handler and revert back to the built-in `type` handler.

@jrieken - we discussed about this.

**Comment by alexandrudima** [comment]
Nice!
