### ISSUE TITLE
Custom editors: what is a WebviewTextEditorProvider?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93858]
Refs: https://github.com/microsoft/vscode/issues/93767

In the help for custom editors I found `WebviewTextEditorProvider`:

> You should use this type of custom editor when dealing with binary files or more complex scenarios. For simple text based documents, use [`WebviewTextEditorProvider`](#WebviewTextEditorProvider) instead.

Shouldn't this reference the custom text editor API instead?

**Comment by mjbvz** [comment]
Fixed by a58a36b
