### ISSUE TITLE
Running `code --help` from integrated terminal opens an instance of VS Code

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#93855]
I'm using PowerShell (Windows) in the integrated terminal with the latest insiders. Run:
```
code --help
```
And instead of showing the cli help, it launches VS Code.

**Comment by Tyriar** [comment]
I can't reproduce, maybe there's a problem with your stable install?

**Comment by alexr00** [comment]
It only happens when I have the VS Code repo open. Not a real issue.
