### ISSUE TITLE
Must return promises/thenables?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93852]
re #93767

I cannot implement `openCustomDocument` sync, why?

**Comment by mjbvz** [comment]
Good suggestion.

All custom editor methods should probably return `Thenable<T> | T` (but not `ProviderResult<T>` since that allows undefined + null)

**Comment by mjbvz** [comment]
@jrieken Do you think methods like `.save` should also return `Thenable<void> | void`?

**Comment by jrieken** [comment]
Unsure for editing and friends. I stumbled over `open` because initially my implementation did nothing there
