### ISSUE TITLE
Use onView activation event instead of custom editor special event?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93856]
re #93643

We already have `onView` as activation event and I think would make sense to reuse that for custom editors.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/1794099/78007914-3ce50f80-733f-11ea-825d-fe52fee92916.png">

**Comment by mjbvz** [comment]
I feel it is better to keep these two events separate and explicit, the same way we have an `onWebviewPanel` activation event. With an event name like `onCustomEditor`, it is also immediately clear what the activation event is used for

Let me know if you feel strongly otherwise

**Comment by jrieken** [comment]
So strong feelings. Generally, I was surprised by the amount of activation events that there are. I like the comparison to `onWebviewPanel`
