### ISSUE TITLE
Custom editors: "viewType" should be "id" or "editorType"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93853]
Refs: https://github.com/microsoft/vscode/issues/93767

I find `viewType` to be confusing when registering a custom editor. I suggest to call it `id` or `editorId` to make clear this a) should be unique and b) is about editors.

**Comment by mjbvz** [comment]
`viewType` comes from the `WebviewPanel` api: https://github.com/microsoft/vscode/blob/a8f383a37cb9e91f695d48cf0222069d263c185a/src/vs/vscode.d.ts#L6707

I'd prefer to keep it for that reason but don't have strong feelings on a name like `editorId`
