### ISSUE TITLE
Custom editors: should class CustomDocument be abstract?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93866]
Refs: https://github.com/microsoft/vscode/issues/93767

> All custom documents must subclass `CustomDocument`

**Comment by mjbvz** [comment]
For basic editors that don't need to store any additional information on the document, you can just return `new CustomDocument(...)`. This is what our built-in image preview does

**Comment by bpasero** [comment]
Then update the JSDoc.
