### ISSUE TITLE
White flash during new instance launch

### ISSUE THREAD

**Issue by deadmeu** [microsoft/vscode#93869]
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-25T01:43:18.461Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.13-1-MANJARO
DE: XFCE4

Steps to Reproduce:

1. Launch an instance of VS Code
2. Observe the blinding white flash just before the window fully renders

Does this issue occur when all extensions are disabled?: Yes

Using `--disable-gpu` does not help either.

Here is a GIF of the effect in action:
![vscode-flash-disabled-extensions](https://user-images.githubusercontent.com/12111013/78008708-56a84600-7383-11ea-8c60-90d608a89e56.gif)
I have a laptop also running Manjaro XFCE4, which did **not** exhibit this behaviour (no flash of white) with the following version information:
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-17T09:32:31.598Z
Electron: 6.1.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.8-1-MANJARO

However, after updating the machine, the same issue (white flash on launch) presents itself. The version information for the updated machine (identical to the first version listed at the beginning of the ticket) is now :
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-25T01:43:18.461Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.8-1-MANJARO

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deadmeu** [comment]
I've just tested master and the issue is still present.

**Comment by bpasero** [comment]
Can you try with disabling the custom menu, via `"window.titleBarStyle": "native"`

**Comment by deadmeu** [comment]
Both `native` and `custom` options are causing the issue. Interestingly, when switched to `native`, I'm finding the context menu when clicking on the settings icon to also briefly flash white. This does not happen when the `window.titleBarStyle` property is set to `custom`:
![vscode-dev-flashing](https://user-images.githubusercontent.com/12111013/78030079-e6aab780-73a4-11ea-9fa8-53737235fa19.gif)

**Comment by bpasero** [comment]
Ok, this sounds Electron specific to me. Does it reproduce if you run "`code --disable-gpu`"?

**Comment by deadmeu** [comment]
Yep, still happens with the `--disable-gpu` option set.

**Comment by bpasero** [comment]
@deepak1556 does this ring any bell?

**Comment by deadmeu** [comment]
I think I may have been experiencing similar effects in some of my other programs running electron 7. Should I close this ticket and open one with the electron team instead?

**Comment by deadmeu** [comment]
https://github.com/electron/electron/issues/22826
https://github.com/electron/electron/issues/18184
These two tickets seem related to this issue.

**Comment by bpasero** [comment]
Yeah if that is the case, then we can mark this issue as upstream.

**Comment by deadmeu** [comment]
On the advice of a user's comment in https://github.com/electron/electron/issues/18184, I've compiled vscode targeting electron 8.1.1, and although I'm seeing lots of errors, the window is loaded enough to see that the white flashing issue has been **resolved** in electron 8.1.1. This includes both the main window on startup, and context menus (such as the native title bar File, Edit, Selection, etc. options) on cursor hover.

Any idea when we might see a vscode release targeting this version of electron? :smile:

**Comment by deepak1556** [comment]
@deadmeu thanks for testing with electron 8, but the issue you linked is wrt menu widget and native tiltebar and its still not fixed in electron 8. The white flash you are seeing on launch is a different issue. Can you try the following exploration build based on electron 8 and verify if the startup flash is fixed ?

https://az764295.vo.msecnd.net/exploration/2766badcb6c29445f5289033f1343f373802315c/code-exploration-1585360520.tar.gz

**Comment by deadmeu** [comment]
Hi @deepak1556, I've just tried out your build, and I can confirm that I am no longer seeing the startup flash. I am also not seeing any of the menu widget flashes:
![vscode-flash-fixed2](https://user-images.githubusercontent.com/12111013/78085844-7d0bc700-73ff-11ea-808b-65dddbb8cc82.gif)

**Comment by deepak1556** [comment]
Thanks for testing!

>  I am also not seeing any of the menu widget flashes:

Did you try with `"window.titleBarStyle": "native"` ?

**Comment by deadmeu** [comment]
Yes, the GIF I posted is using the native title bars.

**Comment by deepak1556** [comment]
I can still repro in exploration build the white flash in menu navigation with native titlebar on Ubuntu 18.04 parallels vm. I am tracking this in https://github.com/microsoft/vscode/issues/80798.

Not sure which electron commit fixed the launch issue, but good to know its fixed.

**Comment by deadmeu** [comment]
Interesting. I'm finding the issue is also fixed when targeting electron 8.0.0, which seems to contradict some of the comments people have left in the upstream ticket.

Also, thanks for your work getting this issue figured out, and in developing vscode :smile:

**Comment by jerry-sky** [comment]
The issue was resolved at some point in one of the insider builds of version `1.47`. Unfortunately, it got borked again in latest two builds (`1.47.0-1593508000` and `1.47.0-1593495868`).

In the build `1.47.0-1593413883` everything is fine – no flashing whatsoever, the program respects the global system settings. Instead of flashing white, the background of not yet fully loaded elements (new window instance, menu/ right-click popup) is the same as in the rest of the system.

**Comment by deepak1556** [comment]
Should be fixed in latest insiders.
