### ISSUE TITLE
Let "terminal" quick pick on terminals

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93865]
Refs: https://github.com/microsoft/vscode/issues/93641

Currently we only activate the terminal quick pick when the user types `term`.
I find this a bit hard to discover, should we also trigger when the user types `terminal`.
That way it will be more aligned with debug and tasks who use full names and not shortcuts?

**Comment by bpasero** [comment]
Unrelated to my changes, so unassigning myself. Change would be easy to do.

**Comment by Tyriar** [comment]
How would we handle this then? Just not show the alias?

![image](https://user-images.githubusercontent.com/2193314/78026618-cdf0c200-7310-11ea-8e73-943fd0368f94.png)

I don't think we need to do this considering `term` was selected as it's short and you type this out, we also have edt and ext as well so we should solve this there as well if we want to do that. But no one has asked outside afaik.

**Comment by isidorn** [comment]
Nobody will ask becuase users do not find this out imho
Yeah I would not render the alias there.

**Comment by bpasero** [comment]
To get both `term` and `terminal` to work you need to register both. I am not sure what the suggested solution is here really?

**Comment by Tyriar** [comment]
@isidorn I doubt users would just type in `terminal(space)` assuming it's going to go something without knowing about the feature (via docs or `?`).

@bpasero if we wanted to do this for terminal, we should also add an "editor" alias for "edt" and an "extension" alias for "ext". To do this it would probably be better to pass a `string | string[]` for `prefix` in `PickerQuickAccessProvider` to lessen the overhead? I don't think we should do this personally though.

**Comment by isidorn** [comment]
@Tyriar if users are aware of `debug(space)` and `tasks(space)` they are more likely to type in `terminal(space)` than `term(space)`

**Comment by bpasero** [comment]
The reason I picked `edt` over `editor` was to be a little less likely to collide with searching literally for a file called `editor`. It is not a perfect solution I agree, on the other hand I doubt a lot of people are actually typing `edt` vs. using a keybinding.

I think every quick picker can decide what prefix to use, there is no real rule currently.

**Comment by Tyriar** [comment]
I say we close this as users haven't asked for it, longer names are harder to use and it has more chance for collisions in go to file.
