### ISSUE TITLE
No way to drag & move file/directory to the top-level / project directory when the Files Explorer is filled from top to bottom

### ISSUE THREAD

**Issue by niieani** [Microsoft/vscode#9386]
- VSCode Version: all (including 1.4.0-insider)
- OS Version: OS X 10.11

Steps to Reproduce:

1. open a project which fills the entire Files Explorer from top to bottom (lots of files & directories)
2. there is now no way to drag&drop to move any file to the top-level / project directory - dragging below or above all the files can only allow dropping on the first or last directory present

Ways to fix:

1. allow dragging files to the project name, which is an always visible UI element
2. add a slight padding to the bottom of the files list in the Files Explorer, so there is always room to drag files out to the top-level after scrolling down

**Comment by wallverb** [comment]
Related https://github.com/Microsoft/vscode/issues/9346

**Comment by bpasero** [comment]
Yeah lets keep this in https://github.com/Microsoft/vscode/issues/9346
