### ISSUE TITLE
Add Folder to Workspace not working

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93861]
VS Code insiders
1. Open a folder
2. File > Add Folder To Workspace, or context menu Add Folder To Workspace
3. No effect 🐛 

I can not reproduce when running with out of source.
Investigating I see the `dialogService.showOpenDialog` being called [here](https://github.com/microsoft/vscode/blob/d7d1147d6b764a48b789000c03088ee9afabcd8a/src/vs/workbench/browser/actions/workspaceCommands.ts#L61)
So somethign seems to be off in the `dialogService`

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/78010009-28564680-7342-11ea-8209-ad3252b93a4a.png)

**Comment by bpasero** [comment]
Works for me. Not sure if @aeschli might have broken something with recent changes.
