### ISSUE TITLE
Quick access: creating new entry should be aligned between debug, terminal and tasks

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93864]
Refs: https://github.com/microsoft/vscode/issues/93641

Note how the terminal uses a nice + icon before the Create New Terminal.
I belive we should use the same icon before the Add Configuration for debug.

Also the tasks should ideally have a similar Add Task experience in theri quick access.

![Screenshot 2020-03-31 at 11 19 46](https://user-images.githubusercontent.com/1926584/78009647-9d754c00-7341-11ea-9d10-642b6f7642da.png)

**Comment by bpasero** [comment]
Unrelated to my changes, assigning respective owners.

**Comment by alexr00** [comment]
The Run Task command and "task " quick access are finally converged and I only show the "Configure Task..." option (which is the equivalent of add for tasks) when there aren't tasks already configured. I will put a + in front of the "Configure task..." so it matches.

**Comment by Tyriar** [comment]
@alexr00 for configure a gear would be more appropriate, no?

Also I see no "Configure Task..." option outside of the icon when you hit show all tasks?

![image](https://user-images.githubusercontent.com/2193314/78036225-e8319c80-731e-11ea-9298-06799800ef73.png)

![image](https://user-images.githubusercontent.com/2193314/78036265-f4b5f500-731e-11ea-971d-907964f4652e.png)

**Comment by alexr00** [comment]
@Tyriar I only show the "Configure Task..." option (which is the equivalent of add for tasks) when there aren't tasks already configured. A gear is more appropriate as it's what is used for the configure tasks button, but then it is not consistent with terminal. 

I do not feel strongly about whether an icon is added to Configure tasks, but it seems like no matter what it will not be consistent with terminal and debug. Because of this, I would prefer not to add an icon.

**Comment by Tyriar** [comment]
@alexr00 how about "+ Create a task" or "+ Configure a task"?

**Comment by isidorn** [comment]
Whatever you agree on I will happily align with in Debug :)

**Comment by alexr00** [comment]
I'll change it to "+ Configure a task". It will still only show if there are no configured tasks.

**Comment by alexr00** [comment]
Changed:
![image](https://user-images.githubusercontent.com/38270282/98386766-dea8a980-2050-11eb-956f-08b71ff85590.png)
