### ISSUE TITLE
Terminal Link Debugging: Doesn't respect default browser/opens 2 browser windows

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#93862]
Testing #93806

I'm testing on OS X and I have Safari as my default browser. 

Terminal linking now does the following:
- Trusted domain dialog appears
- Chrome is already opened
- Once the Trusted domain dialog is accepted, then safari opens as well.

**Comment by connor4312** [comment]
@Tyriar should the trusted link handler only appear if the request falls through any extension handlers?

**Comment by Tyriar** [comment]
This case mustn't be handled yet, I think I have all domains set as trusted.

**Comment by Tyriar** [comment]
Don't need to worry about this anymore as link providers shouldn't be affected by this.
