### ISSUE TITLE
Terminal Link Debugging: Trusted Domains Dialog gets in the way

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#93860]
Testing: #93806

Testing on OS X with Safari as the default browser.

I haven't configured any trusted domains and the trusted domain dialog is getting in the way. In particular it is non-blocking, that is the Chrome browser opens anyway. See the screenshot below.

Why isn't '0.0.0.0' not considered a trusted domain?

![image](https://user-images.githubusercontent.com/172399/78008966-a0bc0800-7340-11ea-91ad-34fbddc90eb3.png)

**Comment by connor4312** [comment]
In the linked commit, we rewrite 0.0.0.0 or :: -> localhost, which might have caused issues depending on the platform/browser. The prompt shouldn't pop at all, however--that part duplicates https://github.com/microsoft/vscode/issues/93862
