### ISSUE TITLE
HTML tag matching in php (template) files

### ISSUE THREAD

**Issue by felyx** [Microsoft/vscode#9387]
I do not really know if this is a bug or a missing feature but the one thing that keeps me from switching to VS Code is html tag matching in php/template files such as laravel blade files. Please add this feature or fix it if this is a bug, thank you!

**Comment by felyx** [comment]
Please, if someone could help with this issue that would be greatly appreciated, this is literally the only thing preventing me from using vscode :s

**Comment by roblourens** [comment]
#2915

**Comment by ssagga** [comment]
A work around I follow is manually switch the language mode at the bottom right toolbar to HTML when HTML tag matching is needed
