### ISSUE TITLE
"Turn on preferences sync" is a clunky name

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93877]
Refs: https://github.com/microsoft/vscode/issues/93799

I like that we use words and not an icon for clarity.
However "preferences sync" sounds a bit clunky. Why not just "Turn on sync"
Preferences sounds like settings, but I know it is more. Thus I think the wording could be improved. Especialy since we do not use this wording in other places.

![Screenshot 2020-03-31 at 12 01 01](https://user-images.githubusercontent.com/1926584/78014362-1e374680-7348-11ea-9174-be1843ab5875.png)

**Comment by isidorn** [comment]
I also find this clunky and would just call it Sync is On

![Screenshot 2020-03-31 at 12 12 57](https://user-images.githubusercontent.com/1926584/78014991-fe545280-7348-11ea-89c7-a67138ee0de1.png)

**Comment by gjsjohnmurray** [comment]
@isidorn it used to be *Turn on Sync* but was changed in #92990.

The doc screenshots haven't yet been updated though.

**Comment by isidorn** [comment]
Yeah I disagree with that change. Fyi @sandy081 
I do understand the motiviation there, however I just find Turn on Sync much cleaner.

**Comment by sandy081** [comment]
@isidorn 

> Especialy since we do not use this wording in other places.

We use Preferences in our product

<img width="640" alt="image" src="https://user-images.githubusercontent.com/10746682/78048578-34f69100-737a-11ea-95b6-9a0eb2f275ec.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/10746682/78048609-3fb12600-737a-11ea-8537-ec2aa9b51127.png">

Just using Sync without context is too generic and users did not understand what it is syncing. It is clear that we are syncing user preferences and hence this is called `Preferences Sync`.

**Comment by sana-ajani** [comment]
@sandy081 could we simplify "turn on preferences sync" to just "sync preferences"? I agree with Isi that the whole phrase sounds like a lot, especially written on a button

**Comment by sandy081** [comment]
`Sync Preferences` sounds to me a one time action. But this action will start syncing preferences automatically. 

>  I agree with Isi that the whole phrase sounds like a lot, especially written on a button

I too agree with that. My suggestion was to use an action with icon instead of big blue button. This will be lighter and do not show on face when I do not want to sync.
