### ISSUE TITLE
Turn on preferences sync does nothing if outdated storage

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93874]
Refs: https://github.com/microsoft/vscode/issues/93799

VS Code insiders, fresh data dir works just fine

However if I have VS Code insiders with user data dir where I enabled sync 2 weeks ago.
I see the "Turn on preferences" button. clicking on it does nothing. Could we at least offer to cleanse old state, since some of our users might have an outdated state like me and might be stuck now?

**Comment by sandy081** [comment]
> I see the "Turn on preferences" button. clicking on it does nothing.

Sorry I did not understand this. You did not see any notification that sync is turned on?

**Comment by isidorn** [comment]
Correct.

**Comment by sandy081** [comment]
Can you able to repro it? If so can you please provide the sync logs?

What is expected here is that, user shall see a notification at the end that sync is turned on.
