### ISSUE TITLE
Custom editors: onDidEdit should not have optional data

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93875]
Refs: #93767

It seems to me that `onDidEdit` should force to send the edit, but this typing allows `undefined` from the `fire` method:

![image](https://user-images.githubusercontent.com/900690/78014273-fea01e00-7347-11ea-831a-7887f6a5022e.png)

**Comment by mjbvz** [comment]
I believe the custom editor api typings are correct since they only use `Event`

This looks like a strict null error in our `EventEmitter` types. We should only let you omit the argument for `EventEmitter<void>`

**Comment by jrieken** [comment]
Yeah, that's an event emitter problem. Unsure when/why that happened...

**Comment by bpasero** [comment]
@mjbvz isn't https://github.com/microsoft/vscode/commit/1ed9dcda2664937e521cad980f886fedf6c9b25c a breaking API change?

**Comment by mjbvz** [comment]
Strictly perhaps, but not practically

This change will cause compile errors for extensions compiled with strict mode TS that were mistakenly calling `fire(undefined)`. However doing that was almost certainly a bug in their code. The old code will keep working just fine but now the error will be obvious

**Comment by bpasero** [comment]
That maybe deserves a shoutout in release notes.
