### ISSUE TITLE
Account UX feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93879]
Refs: #93799

Login to your Microsoft account

1. Clicking on the account thing shows my account and an option to sign in to another account. I do not find it obvious that if I want to logout I have to click on my account which will give me options. Consider adding word "manage" to the end or start of the account name
2. Once the account is cliked there is no placeholder text in the quick pick. I suggest to put some placeholder text so it is easier for users to understand what is going on, especaily screen reader users
3. If sync is not turned on, once I click on my acount offer me a third option to start syncing

**Comment by sana-ajani** [comment]
Agreed with 1) I didn't realize I could click on my "account" and then getting the quick pick to log out is an extra step. I would have thought there was an option to "sign out of current account" under "sign in to another microsoft account" in the account icon.

**Comment by RMacfarlane** [comment]
Closing, since we now show a submenu instead of having to click the account to bring up a quick pick
