### ISSUE TITLE
Custom editor scrollbar theme issue

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93871]
re #93767

I have a custom editor that shows zip-file-entires. Whenever there are two scrollbar a bright square appears at the bottom right

<img width="479" alt="image" src="https://user-images.githubusercontent.com/1794099/78011648-23929200-7344-11ea-8199-6113c066f5bf.png">

**Comment by mjbvz** [comment]
The bug also repros in our built-in image preview for more easy verification
