### ISSUE TITLE
The localisation needs improving.

### ISSUE THREAD

**Issue by septsea** [microsoft/vscode#93876]
Issue Type: <b>Bug</b>

To reproduce the bug, execute the following

1. Open Visual Studio Code - Insiders.
2. Install any localisation package if there is not any one.
3. Change the display language to any language different from English.
4. Click the 'Manage' icon on the lower left.
5. Notice that 'Command Palette' and 'Keyboard Shortcuts' are still in English.

![issue001](https://user-images.githubusercontent.com/57337516/78014191-2b6d2900-737a-11ea-887f-57e6ff2ddc92.png)

![issue002](https://user-images.githubusercontent.com/57337516/78014205-2f994680-737a-11ea-8b5b-c9527046c53a.png)

Though it does not affect users too much (the English used in VS Code is not hard to comprehend), it is still a drawback.

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:23:56.446Z)
OS version: Windows_NT x64 10.0.18363

**Comment by septsea** [comment]
Another bug concerning localisation. To reproduce it, just execute the following:

1. Open Visual Studio Code - Insiders.
2. Install any localisation package if there is not any one.
3. Change the display language to any language different from English.
4. Open 'Settings'.
5. Notice that 'Turn on Preferences Sync' is still in English.

**Comment by danyeh** [comment]
Thank you for your feedback!
Checked on 1.51. Already fixed.
