### ISSUE TITLE
Execute Notebook(run all cells) does not show progress bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93886]
#93742

Clicking on the Execute Notebook(run all cells) has no effect for me. None of my cells get run.
However if I simply do Execute Notebook Cell my cell gets nicely run

**Comment by jrieken** [comment]
It should... I have added that yesterday...

**Comment by isidorn** [comment]
I take that back. It works now. However it does not show progress (thus I originaly though it does not work + not rendering). Due to that renaming issue.
