### ISSUE TITLE
Notebooks: double click on empty area should open new cell

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93883]
https://github.com/microsoft/vscode/issues/93742

Double click on empty area should open new cell
Same as double click on empty editor area opens new untitled editor, double click on tab area opens new tab..

**Comment by misolori** [comment]
How about whenever we just `click` in an empty area it will add an empty cell and if you click away then the cell goes away?

**Comment by isidorn** [comment]
That would be a new patter which we do not use anywhere, also easily to misclick into a bad situation. I personally prefer double click as we do in other areas.

**Comment by rebornix** [comment]
@isidorn where do we support double clicking for inserting content? I didn't see this behavior in File Explorer.

**Comment by isidorn** [comment]
@rebornix watch expressions, tab title area, empty editor area, tunnels view

**Comment by roblourens** [comment]
This is technically kind of a pain to do, I think I need to put in a fake list row with a height of whatever height is remaining on the page after the other rows to capture the double click. And this might predate the toolbar for inserting cells even. I will move this to the backlog.

**Comment by roblourens** [comment]
I'm gonna close this, I don't think it's expected
