### ISSUE TITLE
Notebooks: icons need love

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93888]
Refs: #93742

Currently we use the following icons for notebooks. I see the followgin issues

1. Clicking on the Lock Cell Icon and holding the Icon gets cliped becasue there is not enough vertical space
2. We use the Continue icon for "Execute Notebook Cell". Which is wrong, we need a different icon here. Idealy the same one which we use on the left hand side. Which would just be a green triangle, which means execute everywhere we use
3. For Run all Cells we use a single green triangle which is wrong imho. We should use an icon which represents multiple, so for example mulitple green triangeles
4. Lock icon is the same icon which we use for Output do not scroll. I think we need a different icon here as it has a different meaning
5. We use an X to delete a cell. Why not a trash can just like the terminal uses it

![Screenshot 2020-03-31 at 13 28 12](https://user-images.githubusercontent.com/1926584/78021427-863f5a00-7353-11ea-98f3-e3169a1529c1.png)

**Comment by misolori** [comment]
I believe this is the plan for the icons in the editor toolbar:

![image](https://user-images.githubusercontent.com/35271042/78035646-3abe8900-731e-11ea-8598-9eb9283c84f0.png)

And these are the ones for the cell toolbar:
![image](https://user-images.githubusercontent.com/35271042/78036094-c3d5c000-731e-11ea-96bf-188daa5ceeea.png)


In terms of the lock icon representing lock scroll, the actual icon itself means lock and is very generic so we actually don't use it well in output.

**Comment by isidorn** [comment]
@misolori ok, we are aligned on the multiple play, looks good.
We could potential change the icon we use in output. Use the output icon with a small lock decoration?

**Comment by rebornix** [comment]
I updated the icons accordingly. For the lock icon update in output, please file new issues to track @isidorn .
