### ISSUE TITLE
Outline state is not getting synced

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93881]
Outline state is not getting synced

**Comment by jrieken** [comment]
I reverted my change. @sandy081 I think a better API would be be useful, e.g when using the storage service to globally store something that would be a good place for some metadata about sync'ing or not

**Comment by jrieken** [comment]
done via 195fdfc932858e34a37617b858b35fc24bd6908c

**Comment by sandy081** [comment]
Pinging @bpasero for the API suggestion.
