### ISSUE TITLE
VSCode performance issue (seems like something is leaking)

### ISSUE THREAD

**Issue by rianquinn** [microsoft/vscode#93889]
- VSCode Version: 1.43.2
- OS Version: Windows 10 (fully patched)

Steps to Reproduce:
1. Work for a while. The project I am working on has a couple hundred files (in C++), which seems large to me, but my guess is that is nothing compared to other projects at Microsoft. I am working in C++. As I work for a couple of hours, a lag begins to develop with each key pressed. At some times this lag can be as high as 1 second. 
2. The "on fire" icon is _not_ showing when this performance issue occurs, so as far as VSCode is concerned, its not working hard. 
3. If I close out of VSCode and reopen it (basically restart the app... not refresh it), the problem goes away for a couple of hours. But once again, as I work it tends to develop over the course of a couple of hours so I have to restart the app a couple of times a day. 

WRT to my hardware, I an running on an AMD 3990x with 256GB of RAM, so I don't think its a resource issue with my hardware. 

Does this issue occur when all extensions are disabled?: Have not tried, but I am not running a lot of extensions. I need some extensions to work just to get work done like C++, Auto Comment Blocks, Settings Sync and Spell Checker. I have disabled everything else including themes to verify.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by rianquinn** [comment]
I worked with this for several days with most of the extensions disabled and the problem is gone, so it must be an extension issue.
