### ISSUE TITLE
Sync: Error on keychain shows up when logging in to personal Live account

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93894]
Testing #93771 on Windows

![image](https://user-images.githubusercontent.com/22350/78022500-542ef780-7355-11ea-9538-6e677188064d.png)

Then, trying to sync: 

![image](https://user-images.githubusercontent.com/22350/78022580-7a549780-7355-11ea-998f-968b54404265.png)

Maybe a personal live account isn't supported?

**Comment by RMacfarlane** [comment]
Looks like there is a character limit on keytar for windows: https://github.com/atom/node-keytar/issues/112

**Comment by RMacfarlane** [comment]
Same root cause as https://github.com/microsoft/vscode/issues/108411, so closing this as a duplicate
