### ISSUE TITLE
Sync: Can't login using Github account

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93899]
Testing #93771 on Windows

I don't see any option to login with Github

![image](https://user-images.githubusercontent.com/22350/78023492-0915e400-7357-11ea-826d-9e9385635ac6.png)

**Comment by RMacfarlane** [comment]
I think you need to hit either "Sign-in options" or "Back" to get to the screen that has this option, which is not intuitive, but we don't control this UI and there isn't a way to land on that screen
