### ISSUE TITLE
Autocomplete based on open files

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#93895]
Adding auto-complete based on open files is very important future
It improves and speeds up workflow in any language
I think this option should exist in VSCode.

**VSCode team:** We are closing this because there is an extension
**Me:** No! Take a look ⬇

There is ONLY one [extension](https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete) on the market that doesn't work well.
Support has not fixed bugs, nothing is happening there.
To be honest, I don't see a chance to develop this plugin

So what do you think? 🤔

Currently only works in the current file:
![css](https://user-images.githubusercontent.com/30685349/78023050-429a1f80-7356-11ea-9d9d-da480debc593.gif)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Asuggest
