### ISSUE TITLE
Undo/redo does not play well with IMEs

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#9389]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Build 14388

Steps to Reproduce:
1. Switch to some IME, in my case Sogou Chinese keyboard or Microsoft Chinese keyboard.
2. Type something and undo/redo.

It takes many unnecessary undo/redo operations before I can get to the point of document I want, even if some of them does not seem to change the content of document at all.

**Comment by alexandrudima** [comment]
Related #9675

**Comment by rebornix** [comment]
This issue is obsolete and I can't reproduce any more. It should be fixed via https://github.com/Microsoft/vscode/commit/374c4e3e995dfa984a418f161bef3a908cb61e42 already.
