### ISSUE TITLE
Follow link in terminal syntax

### ISSUE THREAD

**Issue by Hezkore** [microsoft/vscode#93890]
I know that you can make the terminal follow a file and jump to a line by printing something like:
`d:/folder/file.txt:5`
That will jump to line 5.
But the compiler I'm writing an extension for prints things as:
`d:/folder/file.txt;5`
Notice the ; instead of :
Is there a way to make it jump to line 5 even when using ; ?
Otherwise I'd like to request that it somehow integrates with the Problem Matcher that I've already defined to figure this out.

**Comment by Tyriar** [comment]
Instead of supporting so many different formats I'm hoping to let extensions create their own handlers for these after https://github.com/microsoft/vscode/issues/91290 is done.
