### ISSUE TITLE
Results sometimes not rendered

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93892]
Refs: https://github.com/microsoft/vscode/issues/93742

1. Open a new notebook file, for example `isidor.github-issues`
2. Have the following cell
```
label:debug repo:microsoft/vscode milestone:"March 2020" sort desc by comments		
```
3. Run the query - no results get rendered 🐛 
4. Save the notebook file, close it, reopen it and re-run the query -> result get rendered

fyi @jrieken

**Comment by rebornix** [comment]
Probably in the core, similar to untitled file

**Comment by isidorn** [comment]
This works much better. However I still see one corner case:

1. Run the following bad query (which produces no results)
```
label:debug repo:microsoft/vscode milestone:"April 2020" sort desc by comments fakeee
```
2. Now run the following ok query (which produces resulsts)
```
label:debug repo:microsoft/vscode milestone:"April 2020" sort desc by comments
```

No results get rendered.
If I re-run the query under 2 all is good
Due to that re-opening the issue. Because now it is better removing from march milestone.

**Comment by jrieken** [comment]
@isidorn what you see is this https://github.com/microsoft/vscode/issues/94238. e.g when you append something after the sort-by-statement than it is not a sortby-statement anymore, but search text. You should have seen a change in the semantic highlights. We do this to still support search for these new keyword that we invented

**Comment by onyekaa** [comment]
Tried this out for the first time today, can verify that certain results didn't render completely.  It worked for the queries, but I had to click away to another tab then come back for the Markdown to be rendered, no reopening.  Unfortunately this also cleared my query cells. These was brought back by reopening the file.
