### ISSUE TITLE
GitHub notebook: better error printing

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93893]
Refs: https://github.com/microsoft/vscode/issues/93742

1. Open a new notebook file, for example `isidor.github-issues`
2. Have the following cell
```
label:debug repo:microsoft/vscode sort desc by comments		
```
3. Run the query mutiple times until GitHub throttles you
4. The error is not nicely printed

fyi @rebornix

**Comment by rebornix** [comment]
I'm wondering whether we can use the `CellErrorOutput` for this.

**Comment by jrieken** [comment]
I didn't look like a good match because (at time I checked) it was very specific to runtime errors, e.g wants a trace and so
