### ISSUE TITLE
Tab Not Working Correctly

### ISSUE THREAD

**Issue by chauhanvats3** [microsoft/vscode#93900]
Issue Type: <b>Bug</b>

While using editor portion, If I press Tab Key, It wont insert tab but instead takes focus to left sidebar.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.51GB free)|
|Process Argv|C:\Users\vatchauhan\Documents\Majesco\Customizations|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.21
vscode-eslint|dba|2.1.2
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
quicktype|qui|12.0.46
vscode-data-preview|Ran|2.0.0
java|red|0.58.0
LiveServer|rit|5.6.1
web-extension|Vai|0.1.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by jrieken** [comment]
Did you try F1 > Tab Key Toggles Focus
