### ISSUE TITLE
Sync: Global snippets are not synced

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93902]
Testing #93771 on Windows

1. Run `Preferences: Configure User Snippets`
2. Pick `New Global Snippets file...`, choose a name and add a snippet

🐛  This doesn't get synced to the cloud.

This works if I pick a language such as `coffeescript` instead, on step 2.

**Comment by chrmarti** [comment]
Same on Linux. Here it added a `.code-snippet` file extension while all others are `.json` files. Is that part of this issue?

**Comment by chrmarti** [comment]
Renaming the file to `foobar.json` made it work. It just takes while for it to be sent to the server and then pulled from there.

**Comment by roblourens** [comment]
Still reproes, @sandy081 the extension is `.code-snippets` not `.code-snippet` https://github.com/microsoft/vscode/commit/dfb7a5ebd3ad07208974286ea13d88c87960fddf#diff-b05d8f2d63cf7ae3ab66216054208dc3R420

**Comment by sandy081** [comment]
Good catch. Fixed it.
