### ISSUE TITLE
Icons in the quick pick are not horizontally centered

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode#93906]
The "gear" and the "trash" icons are not centered in their outlines

For example:
<img src="https://user-images.githubusercontent.com/3723951/77938342-437f7280-72be-11ea-963b-e5af57d2569c.png" />

Follow up issue of https://github.com/microsoft/vscode/issues/89443#issuecomment-606110158

```
Version: 1.44.0-insider
Commit: 13b38d2a494612ace32c4fb878824d6329d4c51e
Date: 2020-03-30T07:30:34.234Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```
Steps to Reproduce:

1. Hit <kbd>ctrl</kbd> + <kbd>~</kbd> 
2. `Create new integrated terminal`
3. Hit <kbd>ctrl</kbd> + <kbd>~</kbd>  (repeat step 1)
4. Hit <kbd>tab</kbd> 3 times (focus on the gear icon)  

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
This is actually a case with all icons in the quick pick:

![image](https://user-images.githubusercontent.com/35271042/78036903-aead6100-731f-11ea-96c2-87391f3b6e75.png)

FYI @bpasero looks like the `width` rule here is causing this:
https://github.com/microsoft/vscode/blob/17fa9b7cc0723d0479b1ede625eb38fd5640c5b8/src/vs/base/parts/quickinput/browser/media/quickInput.css#L247-L252

**Comment by misolori** [comment]
This should be fixed:

![image](https://user-images.githubusercontent.com/35271042/78038106-495a6f80-7321-11ea-850d-ad4801db88d6.png)

And in the recent menu:
![image](https://user-images.githubusercontent.com/35271042/78038168-5e370300-7321-11ea-9c1f-1b2bb5fde351.png)

**Comment by bpasero** [comment]
@misolori thanks!
