### ISSUE TITLE
Terminal's name has no focus indication

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode#93907]
There is no indication when the terminal's name gets / looses focus

![video1](https://user-images.githubusercontent.com/3723951/78024748-93634580-7361-11ea-975a-9dacbcc90db5.gif)

Follow up issue of https://github.com/microsoft/vscode/issues/89443#issuecomment-606110158

```
Version: 1.44.0-insider
Commit: 13b38d2a494612ace32c4fb878824d6329d4c51e
Date: 2020-03-30T07:30:34.234Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```
Steps to Reproduce:

1. Hit <kbd>ctrl</kbd> + <kbd>~</kbd> 
2. `Create new integrated terminal`
3. Hit <kbd>ctrl</kbd> + <kbd>~</kbd>  (repeat step 1)
4. Hit <kbd>tab</kbd> several times

Does this issue occur when all extensions are disabled?: Yes

**Comment by moshfeu** [comment]
Thanks nice bot. If it would cover this one I wouldn't create it 😆

**Comment by Tyriar** [comment]
I created one for this recently too: https://github.com/microsoft/vscode/issues/93916

/duplicate
