### ISSUE TITLE
Change "Turn on Preferences Sync..." item on Manage menu while transitioning from Off to On

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#93904]
After turning on sync, if I revisit the Manage menu (from the gearwheel) there's no indication that something is happening.

If I wait long enough before revisiting that menu it will have changed to "Preferences Sync is On".

Compare this with how the "Check for Updates..." entry behaves during download of an update.

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:23:56.446Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Following is shown while sync is being turned on...

<img width="337" alt="image" src="https://user-images.githubusercontent.com/10746682/80367594-ae0ada80-888b-11ea-8928-1395e768a909.png">
