### ISSUE TITLE
Allow to undo file operations done in the explorer

### ISSUE THREAD

**Issue by sijad** [microsoft/vscode#9390]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.5

Steps to Reproduce:
1. delete a file from explorer panel
2. there is no option to undo previous action

can be related to #4366

**Comment by pancho111203** [comment]
+1 Please add

**Comment by dmtaub** [comment]
very frustrating as accidentally moving a file is easy with some touchpads. No way to tell what happened, and need to go to git to resolve :(
second best would be disabling CUD operations in explorer

**Comment by tgdn** [comment]
There isn't either any sort of alert. On MacOS the trackpad can easily select a whole directory and move it some place else without having any alert or possibility to undo that change

**Comment by jabacchetta** [comment]
WebStorm is a good example of how to handle this. When explorer panel is focused, you can undo/redo folder/file operations.

**Comment by isidorn** [comment]
I have puhsed a change to tackle this. You can try it out in VS code insiders from tomorrow and let us know how it works for you. Thanks for the feedback!
