### ISSUE TITLE
Invalid regex is not shown to be invalid

### ISSUE THREAD

**Issue by DasJott** [microsoft/vscode#93903]
Issue Type: <b>Bug</b>

This regex: `([^?]+)\?([^:]+)\:(.*)` is supposed to find lines like the following:  
`res = foo?bar:baz`.
Instead it states: "No results"

I was told this exact same condition works under Windows. Both most recent versions, but different Electron versions. Maybe that's the thing?

[regex tester](https://regex101.com/r/Pb753i/1)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.4.27-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.36GB (0.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Is that inside the editor or global search?

**Comment by myfonj** [comment]
Backslash (`\`) before `:` should not be necessary in this context, and in this case removing it makes it work in text search.  It seems like a discrepancy compared to standard RegExp we know from JavaScript, where backslash-escaping non-control characters usually makes no difference:

```JavaScript
/a/.test('a') // true
/\a/.test('a') // true
```
In VSC text search it makes a difference:

![image](https://user-images.githubusercontent.com/1761395/78030089-dae9d180-7361-11ea-8af6-f2f5f78e3f64.png)

![image](https://user-images.githubusercontent.com/1761395/78030119-e63cfd00-7361-11ea-9b2a-8eada94c5616.png)


<details>
<summary>Version: 1.43.2.</summary><pre>
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.16299</pre>
</details>

---

(I'm not sure but I think that regex engine used for document and file text search is not "just vanilla JS" (ripgrep perhaps?), and I'm not even sure if 100% compatibility with JS regex peculiarities is a goal. Nice bug anyway, good catch!)

**Comment by DasJott** [comment]
It is regarding text search within the editor. Didn't try the global one.
I also already tried with backslash removed but never got it. I sense that the problem is in the *not* operator like `[^?]`. Exchanging that to a simple `.*` worked as expected.

**Comment by myfonj** [comment]
> I also already tried with backslash removed but never got it.
> I sense that the problem is in the [negated character class] `[^?]+`. Exchanging that to a simple `.*` worked as expected.

So in your case just removing the extra backslash from `\:` (resulting in regexp `([^?]+)\?([^:]+):(.*)`) yielded different outcome than expected? You had to further alter the negated character class or something?

It works for me, and I'd not expect this will be platform dependent:
![image](https://user-images.githubusercontent.com/1761395/78148168-cf1b0f80-7434-11ea-9b4c-84b62c0c4a76.png)

**Comment by DasJott** [comment]
Well, the same setting worked on Windows, but not in Linux.

**Comment by alexdima** [comment]
The JS engine throws when constructing the regular expression:
![image](https://user-images.githubusercontent.com/5047891/78161778-460cd400-7446-11ea-9acd-f0ec92b68a3e.png)

**Comment by alexdima** [comment]
Removing the unicode flags makes the regex valid: `new RegExp('\\a', 'ig')` works.

I think the validation code (that would display an error) forgets to use the unicode flag.
