### ISSUE TITLE
Welcome views are badly laid out when inside a panel

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93910]
Focus a welcome view. This is good:

![image](https://user-images.githubusercontent.com/22350/78025673-b807ef00-735a-11ea-91cf-959b69c38dba.png)

This is bad, notice the bottom "focus" border is missing:

![image](https://user-images.githubusercontent.com/22350/78025722-cb1abf00-735a-11ea-9ec2-a1112e6564f3.png)

Devtools reports that the welcome view is overstretching:

![image](https://user-images.githubusercontent.com/22350/78025824-f43b4f80-735a-11ea-8241-41a95382899b.png)

 I am sure this was OK one month ago, so maybe there were some changes to the panels/splitview, @sbatten ?

**Comment by sbatten** [comment]
repros in stable

**Comment by joaomoreno** [comment]
Here's the exact height right now:

![image](https://user-images.githubusercontent.com/22350/78125028-c57fb080-7410-11ea-846e-5951060023f8.png)
