### ISSUE TITLE
Clear notebook cell output has no effect

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93918]
Refs: #93742

1. Have the following cell and execute it
```
label:debug repo:microsoft/vscode milestone:"March 2020" sort desc by comments		
```
2. Click on the "Clear Notebook Cell Output" - no effect 🐛 
3. Click on the "Clear All Notebooks Cell Output" - works

![clear](https://user-images.githubusercontent.com/1926584/78027642-f9e66480-735d-11ea-9377-d690657c7ef6.gif)

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/563997c6de826b77a28181927ad5822c904438d0
