### ISSUE TITLE
Extension can show progress in foreign view

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#93911]
Testing https://github.com/microsoft/vscode/issues/93822

Not sure what your strategy around this should be but it looks like an extension can show progress in a foreign view. This works without problems:

```ts
	let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		vscode.window.withProgress({
			location: { viewId: 'npm'}
		}, (progress, token) => {
			let counter = 0;
			let interval: NodeJS.Timeout;
			return new Promise((resole, reject) => {
				interval = setInterval(() => {
					progress.report({ message: 'Hello', increment: 1});
					counter++;
					if (counter === 100) {
						clearInterval(interval);
						resole();
					}
				}, 100);
			});
		});
	});
```

**Comment by eamodio** [comment]
Yeah, though I'm not sure this is an issue that we should try to solve. @jrieken thoughts?

**Comment by jrieken** [comment]
Yeah, unsure... We also allow 3rd party extensions to contribute commands into views so IMO it makes sense to also allow them to show progress. There is some abuse potential but I believe extensions have good intentions.
