### ISSUE TITLE
Peek definition inside a peek does not work anymore

### ISSUE THREAD

**Issue by arnonshp** [microsoft/vscode#93914]
VS code used to be able to open several peek windows one inside the other.
After upgrading to version 1.43.2, this feature is broken. Instead, if I ctrl+click inside a peek window, a tab is opened with the first definition in the list.
I already verified that all my "Goto Location" settings are set to the default "peek" option.

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 3.16.0-10-amd64

**Comment by jrieken** [comment]
Because of space constraint we don't want peek inside peek inside peek. For one or two version we had a bug that would allow to trigger peek inside peek but this got fixed in the meantime

**Comment by arnonshp** [comment]
If that's the case then I'd expect that the ctrl+click inside the peek will change the peek which is already open and refresh the available definition list on the right, rather than opening the first one (which is not always the wanted one) in a new tab without any definition list...
