### ISSUE TITLE
Intellisense broken for large JS projects like cocos2dx-js

### ISSUE THREAD

**Issue by sachingarg05** [Microsoft/vscode#9391]
- VSCode Version: 1.3.1
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Create a new Cocos2x-JS project following steps on: https://github.com/cocos2d/cocos2d-x
  For example: cocos new -l js WebGame
2. Open project folder in VS Code.
3. Setup default jsconfig.json which doesn't exclude anything.
4. Ctrl+Space (autocomplete) and Cmd+Click (go to definition) don't work.
5. In ./main.js, try Cmd+Click on cc.view or cc.director. VS Code finds an empty reference to cc in Base64Images.js (var cc = cc || {};) and then can't find anything else in cc like cc.view or cc.director etc...

On opening the same project folder in webstorm, both ctrl+space autocomplete and cmd+click go to definition work as expected. So the problem is not with project or code structure etc.

The Visual Studio team has been working on improving support for Cocos2dx C++ projects.
  https://blogs.msdn.microsoft.com/vcblog/2016/07/12/cocos2d-x-visual-studio-android-project/

It will be great if VS Code can support intellisense for large javascript projects like Cocos2dx JS.

**Comment by dbaeumer** [comment]
Moving to TS team since they provide the language smartness for JS as well.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10141

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10142
