### ISSUE TITLE
Need an api to scroll till to a position

### ISSUE THREAD

**Issue by agrabhi** [Microsoft/vscode#9392]
Hi 

Is there any way to scroll a window to a position? I am using vscode.commands.executeCommand("cursorBottom"); as workaround to scroll to bottom. It doesnt work perfectly. Any better way?

**Comment by jrieken** [comment]
You should use [`TextEditor#revealRange`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L935)
