### ISSUE TITLE
Tasks: Do not select `Go back` by default, isolate it from the other options

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93923]
Testing #93746 on Linux

1. Open a folder with `package.json`
2. `Tasks: Run Task`
3. Pick `npm`

🐛 `Go back` should be separated from the rest using a separator. It should also probably not be the option selected by default.

![image](https://user-images.githubusercontent.com/22350/78028628-99582700-735f-11ea-89cd-953a5c4f8f4a.png)

**Comment by alexr00** [comment]
Added a separator and moved to the end.

**Comment by Tyriar** [comment]
@alexr00 up the top might still be good as it aligns with the simple file picker, just have the second item selected? Open recent does this as the most recently opened window is the current window.
