### ISSUE TITLE
Quick pick: Reported list length is 1 off

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93924]
https://github.com/microsoft/vscode/issues/93641

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

Repro with NVDA

1. Ctrl+P (announced: settings.json, recently opened, 1 of 196)
2. Up (announced: minimap.ts, recently opened, **195 of 196**)

**Comment by isidorn** [comment]
Seems like we will have to tune `getSetSize` and `getPosInSet` [here](https://github.com/microsoft/vscode/blob/d7d1147d6b764a48b789000c03088ee9afabcd8a/src/vs/base/parts/quickinput/browser/quickInputList.ts#L286)
I can look into this.

**Comment by Tyriar** [comment]
@isidorn I also noticed it only happens on large lists, not small ones. Maybe at the time the scroll bar comes in?

**Comment by isidorn** [comment]
@Tyriar woudn't bet on the scroll bar. Can you also reproduce it with other large lists like Extnesions view, Suggest widget etc...

**Comment by Tyriar** [comment]
It also happens in suggest widget, not extensions (tested with 22).

**Comment by isidorn** [comment]
Ok, might be a List Issue. Anyways moving to next milestone to look into then.
@joaomoreno might it be that the default list aria provider is off by one in some cases?

**Comment by isidorn** [comment]
Fixed by @joaomoreno with https://github.com/microsoft/vscode/commit/9e9ee4d3dd6c8988d098a8c9600725f67e875547
