### ISSUE TITLE
Quick pick: Ctrl+Home and Ctrl+End should go to the start and end of the list respectively

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93922]
https://github.com/microsoft/vscode/issues/93641

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

They do the same as home/end currently (work on the textbox).

**Comment by chrmarti** [comment]
Home/End work when you `tab` first to give focus to the list. While the focus is on the textbox, I expect Home/End to go to the textbox. (I suggest to leave this as it is.)

**Comment by bpasero** [comment]
@chrmarti I think Daniel asks for `Ctrl+Home` / `Ctrl+End` to work on the list if I understand correctly. 

But I see this as a feature request for the quick input widget itself, so moving off March.

**Comment by roblourens** [comment]
Should it be cmd on mac?

**Comment by Tyriar** [comment]
Probably cmd+up/down as that matches what happens in the editor? @chrmarti any reason quickInput.ts isn't using commands and context keys here?

**Comment by chrmarti** [comment]
Fixing by making CMD work on Mac. Converting these to commands is tracked with #98479.
