### ISSUE TITLE
untitled scheme in openTextdocument does not work as intended

### ISSUE THREAD

**Issue by agrabhi** [Microsoft/vscode#9393]
- VSCode Version:1.3.1
- OS Version: Windows 10 1511

var filepath = 'C:\\Users\\abhi\\documents\\abc.txt";  // abc does not exist
var fileUri = vscode.Uri.parse('untitled:' + filePath);
vscode.workspace.openTextDocument(fileURI).then(doc => {
            vscode.window.showTextDocument(doc);
});

the above code fails as openTextDocument throws with **Cannot read property 'length' of undefined** .

But if I change the uri statement to 
var fileUri = vscode.Uri.parse('untitled:' + path.sep + path.sep + filePath);  // path = require('path');
Then untitled file opens fine. but the name of file is **\\C:\\Users\\abhi\\documents\\abc.txt**

I am assuming there is a bug here. according to documentation first method should have worked.

**Comment by jrieken** [comment]
Right, the URI tries to lower-case the drive letter but is an issue with it has no leading slash.

**Comment by agrabhi** [comment]
when can I test this?

**Comment by jrieken** [comment]
Right now from source or in ~24h with the latest insider builds
