### ISSUE TITLE
Notebook top border for no defintion found cutoff

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93930]
Refs: #93742

Notebook, do a go to definition on a symbol which does not have a definition.
Notice the top border is cutoff on the message that no defintion could be found.
Same for other similar messages (like no references found) 

![Screenshot 2020-03-31 at 15 05 53](https://user-images.githubusercontent.com/1926584/78029655-3f586100-7361-11ea-81a7-5b11d572055d.png)

**Comment by isidorn** [comment]
This is not fixed for me with latest. It is fine to push out to next milestone imho.

![Screenshot 2020-04-30 at 12 01 27](https://user-images.githubusercontent.com/1926584/80698141-5910d380-8ada-11ea-9c88-c64b67f91aae.png)

**Comment by rebornix** [comment]
Good catch, the zindex needs to be applied to all overflowing content widgets.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/876920/80743280-8f962080-8ad1-11ea-8502-198852c3fd81.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/876920/80743413-c2401900-8ad1-11ea-985c-55f5a62c58e8.png">
