### ISSUE TITLE
Error navigation has one empty hop when switching between cells

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93937]
Refs: #93742

1. Have a notebook file, with multiple cells and each cell having an error
2. Navigate between errors via `F8`. Notice how after navigated to a new cell the error is not shown, it takes an additional `F8` to get the inline error widget

![nextError](https://user-images.githubusercontent.com/1926584/78031449-dde5c180-7363-11ea-8790-30af6b85a683.gif)

**Comment by rebornix** [comment]
My guess is F8 will reveal the second cell which triggers it be rendered and then it forgets to open the error peek view after being opened. I'm wondering why it works fine with F8 to another file.

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/cd0d6485221e0f0e89d04aa760b6110db925575f/src/vs/editor/contrib/gotoError/gotoError.ts#L398-L406

It's waiting for the editor to be open with editorService. @jrieken not sure if composite editor is hooked up with it too.

**Comment by jrieken** [comment]
hm, it should be hooked up but I am unsure if it returns an editor or the composite editor...
