### ISSUE TITLE
API: Contribution to viewsContainers.panel should show error when missing icon

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93939]
Testing #93785

There should be a squiggly error when missing an icon from a panel view container contribution:

![image](https://user-images.githubusercontent.com/22350/78031879-72e8ba80-7364-11ea-9812-59c8aeba9b1d.png)

Especially because it's an error at runtime:

![image](https://user-images.githubusercontent.com/22350/78031939-84ca5d80-7364-11ea-90a6-de4a2a30c3e1.png)

**Comment by sbatten** [comment]
fyi @sandy081
