### ISSUE TITLE
Cell naming feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93933]
Refs: #93742

I see the following issues with cell naming

1) "cell-0" I would prefer if this was shown as "Cell 0"
2) I would prefer if counting was started with 1, not 0 (more readable and like our columns in the editor)
3) User do not know how each cell is named. For example if you just press create new cell 5 times, in the end you will have order Cell 0, Cell 4, Cell 3, Cell 2, Cell 1. The newest cell always gets the highest number even if it is aftet the top one.  

To tackle 3 I suggest to not render the name of the Cell anywhere in the Notebook like now, but to make the names changable, your name depends on where you are in the list - your order.

**Comment by jrieken** [comment]
Should we then also render them as "Cell 1", without the name of the notebook, or like so "foo.github-issues Cell 1"?

**Comment by isidorn** [comment]
I belive with the name of the notebook to be consistent with our other UI where the editor name is always the main thing.
Thus "foo.github-issues Cell 1"

**Comment by jrieken** [comment]
I have tried the `foo.github-issues Cell 1` variant and another one: `foo.github-issues, cell 1` (which actually like better)

<img width="332" alt="Screenshot 2020-04-09 at 16 49 36" src="https://user-images.githubusercontent.com/1794099/78908287-2860ef80-7a82-11ea-8bc9-27a123d54aee.png">

<img width="367" alt="Screenshot 2020-04-09 at 16 49 49" src="https://user-images.githubusercontent.com/1794099/78908289-29921c80-7a82-11ea-9d93-e83278a2c9f7.png">

**Comment by isidorn** [comment]
Works for me. `foo.github-issues, cell 1` looks good.

**Comment by rebornix** [comment]
I like `foo.github-issues, cell 1` too.

**Comment by jrieken** [comment]
Closing this for now as people seem happy with the current approach
