### ISSUE TITLE
Do not allow to scroll beyond last result

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93940]
Refs: #93742

Currenty we allow to scroll all the way down after the last result

We should at least always show the last cell output and the last cell
This way the screen can be completly empty which I find werid

Another problem is when revaling the last cell (for example from the problems view) the last cell is shown all the way at the top with a large empty area after it.

**Comment by rebornix** [comment]
The idea that allowing you to scroll beyond the last cell is when you have a large cell at then end of the document, when you are re-executing the query and fetching the results slowly, the window will shift up and down often. The same concept is from the editor which allows you to scroll beyond the last line.

Agree that we should not scroll the last cell to the very top of the view.

**Comment by rebornix** [comment]
this can be disabled by `editor.scrollBeyondLastLine`.
