### ISSUE TITLE
Press Enter to manage your extensions."

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93948]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by Tyriar** [comment]
Weird, github created an issue half way through making this https://github.com/microsoft/vscode/issues/93949
