### ISSUE TITLE
Recently opened: "workspaces" vs "(Workspace)" is confusing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93942]
#93729

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

Using the example image from #93729:

![image](https://user-images.githubusercontent.com/2193314/78031923-0eecd480-7319-11ea-9e39-18f313c87705.png)

The blue "workspaces" label tells the user that all items in this group are workspaces, but then one of them is explicitly marked as a "Workspace". Should this be additionally separated into "files", "folders" and "workspaces" to avoid this? That way we could remove the (Workspace) indicator.

**Comment by bpasero** [comment]
@Tyriar I do not think separating between folders and workspaces is clever because I for example frequently switch between single folder workspaces and multi-root. This would basically prevent me from being able to quickly switch to the previous one.

**Comment by Tyriar** [comment]
Could it be "Folders and Workspaces" then? "Folders/Workspaces" could be even better but it's used in `view` to show hierarchy:

![image](https://user-images.githubusercontent.com/2193314/78056041-52efd180-7339-11ea-9f1a-d359d61f6650.png)

**Comment by bpasero** [comment]
Upon second thought, I am not sure explicitly calling out "folders" and "workspaces" is helpful to understand the intend. I think https://github.com/microsoft/vscode/issues/77718 is the discussion to have on this topic.

/duplicate https://github.com/microsoft/vscode/issues/77718
