### ISSUE TITLE
Page down should should not flash the top item in the list

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93946]
#93729

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

Minor issue obviously but it's would probably feel smoother if the top didn't flash whenever you press page down. This indicates to me that rendering is happening between the selection and scroll values are updated as a result of page down firing. Shouldn't they be done at the same time?

Holding page down showing the problem:

![dd72d180-3c9c-434b-8aa4-ae789e7d8470](https://user-images.githubusercontent.com/2193314/78032884-896a2400-731a-11ea-871c-7b6780197b5f.gif)

Pressing page down showing the problem:

![caa19ba4-f3e0-44e0-910b-7c71ee0214e3](https://user-images.githubusercontent.com/2193314/78033553-67bd6c80-731b-11ea-9ff7-2b1783704760.gif)

**Comment by joaomoreno** [comment]
It's pretty much the same what happens with the Windows file explorer. We can do better, tho!
