### ISSUE TITLE
Press Enter to manage your extensions doesn't do anything

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93949]
#93641

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

![image](https://user-images.githubusercontent.com/2193314/78035250-b3711580-731d-11ea-8e2a-f13a46840115.png)

ctrl+p, "ext ", enter

This doesn't do anything, it just keeps flashing?

**Comment by bpasero** [comment]
Does not reproduce for me, but then I wonder why the first item is not selected?

![image](https://user-images.githubusercontent.com/900690/78043512-ba2a7780-7373-11ea-8056-2575e3f79a1a.png)

@Tyriar do you have accessibility mode on?

**Comment by Tyriar** [comment]
Yes I had it on, I thought it was an informational label. If this is just an action to open the view it should say "Manage extensions", there are more ways to trigger it than just enter (touch, click).

**Comment by bpasero** [comment]
As for the issue of not selecting that item, we have https://github.com/microsoft/vscode/issues/93610

I leave it up to @sandy081 to change this label, it was unchanged from stable:

![image](https://user-images.githubusercontent.com/900690/78102819-8c811500-73eb-11ea-8278-c190322d1c2e.png)

**Comment by sandy081** [comment]
No plans to change.

**Comment by Tyriar** [comment]
Why? We don't tell the user to press enter on any commands in the command palette, right now it's inconsistent with literally every other quick access provider.

**Comment by sandy081** [comment]
Yah this is an information label and I like this way. There are no pickers like in other cases. Also I did not see any users complained about it.
