### ISSUE TITLE
Notebook actions are not rendered until clicking the notebook again

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#93952]
Testing #93742

* From the explorer, click on a notebook file
* Observe that notebook actions are not rendered
* Click the notebook tab title
* Observe that notebook actions are now rendered

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78037050-500dd480-736b-11ea-8a60-acbcf12afef5.gif)

**Comment by jrieken** [comment]
Maybe a focus issue?
