### ISSUE TITLE
Rename Directory fails after copy

### ISSUE THREAD

**Issue by ewlloyd** [Microsoft/vscode#9395]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.14390

Steps to Reproduce:
* In the Explorer pane, ctrl-drag a folder to its own parent, creating a copy (parent/foo => parent/foo.1). 
* Select the new folder (foo.1) and press F2 to rename it. Change the name, then press Enter.
  * _VS Code will pop an EPERM._
* Open Windows Explorer to the parent folder and attempt to rename the new folder (foo.1).
  * _This will fail with a message indicating that the folder is being used by another program._
* Close VS Code.
* Try again to rename the folder in Windows Explorer.
  * _This time it works._

**Comment by bpasero** [comment]
@ewlloyd are you using TypeScript?

**Comment by ewlloyd** [comment]
Yes, yes I am. It happened again today. The folder I tried to rename had a TypeScript source file in it.

**Comment by dbaeumer** [comment]
Duplicates https://github.com/Microsoft/TypeScript/issues/7762
