### ISSUE TITLE
Always spinning progress

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#93954]
Testing #93742

* Type `hello` in a new notebook
* Press play (at the left of the editor)
* Go through auth flow
* Progress is always spinning
* Reload the window
* Press play (at the left of the editor)
* Progress is always spinning

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78037522-f954ca80-736b-11ea-869c-600033f3aeea.gif)

**Comment by jrieken** [comment]
@alexdima the last output is saved with the notebook and hence restored. The search is indeed still running, will likely run for ages because all items matching "hello" are retrieved. Most likely you are throttled by now...
