### ISSUE TITLE
Horizontal view layout: Missing vertical divider

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#93965]
Issue Type: <b>Bug</b>

#93787

I'm missing a visual indicator of where the two views meet:
![image](https://user-images.githubusercontent.com/9205389/78043165-4b4d1e80-7373-11ea-91e9-dec706eda697.png)

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.37GB free)|
|Process Argv|-psn_0_3851180|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.49GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
vscode-eslint|dba|2.1.2
jupyter|don|1.1.5
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.1.1
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-pull-request-github-insiders|Git|2020.3.35461
rest-client|hum|0.23.2
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.1.1
python|ms-|2020.3.69010
remote-containers|ms-|0.109.0
remote-ssh-edit-nightly|ms-|2020.3.42660
remote-ssh-nightly|ms-|2020.3.42660
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
github-issues-prs|ms-|0.9.2
js-debug-nightly|ms-|2020.3.1017
debugger-for-chrome|msj|4.12.6
vscode-versionlens|pfl|0.25.0
vscode-yaml|red|0.7.2
vscode-open-in-github|sys|1.13.0
vscodeintellicode|Vis|1.2.6

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
To Verify:
1. Put multiple views in a panel.
2. Check that you can see the draggable sash
