### ISSUE TITLE
All built in views shall have predefined & unique icons

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93964]
Testing https://github.com/microsoft/vscode/issues/93786

I see all panel views have icons and when they are moved to activity bar these icons are shown. In the same way we shall also have unique icons for other predefined views. 

For eg: 

1. . Outline view 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/10746682/78043093-33759a80-7373-11ea-8bd0-16d208787800.png">

2. Open Editors

<img width="381" alt="image" src="https://user-images.githubusercontent.com/10746682/78043399-96ffc800-7373-11ea-9b2b-c9af3e29a5bf.png">

3. Timeline

4. Debug views

<img width="374" alt="image" src="https://user-images.githubusercontent.com/10746682/78043517-bb5ba480-7373-11ea-94f0-6e598d05dba6.png">

@misolori @jrieken @isidorn @eamodio  FYI

**Comment by misolori** [comment]
This one is hard because some feel like they need one (timeline, outline, npm scripts) but others don't (open editors, debug views, enabled/disabled/recommended extensions). For the ones that don't need one, we could re-use their parent icon?

**Comment by eamodio** [comment]
We should allow custom view to also contribute an icon as well.

**Comment by misolori** [comment]
@eamodio I believe that's the plan so far

**Comment by misolori** [comment]
Here's my suggestions so far (these already exist in [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)):
- Timeline => `clock`
- Outline => `symbol-class`
- NPM Scripts = > `code`

![image](https://user-images.githubusercontent.com/35271042/78071760-dec22780-7352-11ea-8684-874f7bb98eba.png)

**Comment by eamodio** [comment]
@misolori Timeline should be `history` right?

**Comment by misolori** [comment]
@eamodio sorry yea, they're mapped to the same icon (though the codicon preview page doesn't show that).

**Comment by isidorn** [comment]
@misolori you suggestion makes sense.
If we already have a nicely suited codicon we should use it.

**Comment by misolori** [comment]
@sbatten let me know if there is anything else you need from me.

**Comment by sbatten** [comment]
We will need #94617 for NPM Scripts @sandy081

**Comment by sbatten** [comment]
@misolori we now have everything we need to supply icons. all debug views are currently using the same icons and npm scripts needs an icon svg i think since it is an extension
