### ISSUE TITLE
Empty line in emmet with remove tag?

### ISSUE THREAD

**Issue by khanh97dev** [microsoft/vscode#93969]
Why remove tags in emmit, still empty line?

I wonder why every time the "remove tag" in emmet leaves an empty line, 
while those "expand abbreviation" create more lines.

![before-remove-tag](https://user-images.githubusercontent.com/33818840/78043921-2621d580-739e-11ea-9938-988cd9ae4b01.png)
![after-remove-tag](https://user-images.githubusercontent.com/33818840/78043926-27eb9900-739e-11ea-9df4-efc5d0fa338e.png)

If it is a bug, please fix it! Thanks!

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
