### ISSUE TITLE
scss scss scss!

### ISSUE THREAD

**Issue by biorz** [Microsoft/vscode#9396]
not support scss

**Comment by weinand** [comment]
@biorz VS Code provides basic scss support (syntax coloring etc.).
What additional support are you asking for?

**Comment by biorz** [comment]
@weinand Sorry, I just started to use the sass syntax language format, and now use the sass-indented color is normal.

**Comment by weinand** [comment]
@biorz sorry, but I don't understand what scss/sass support are you asking for.

**Comment by kieferrm** [comment]
Please reopen if you can provide a little bit more information. Thanks!

**Comment by biorz** [comment]
My English is not good I use the screenshots

![20160723085347](https://cloud.githubusercontent.com/assets/15077010/17074786/6f0ed2fa-50b3-11e6-91b1-9fe9eea33a45.png)
![20160723085532](https://cloud.githubusercontent.com/assets/15077010/17074787/70a09b80-50b3-11e6-8cc1-2be32d616f07.png)

**Comment by mrmlnc** [comment]
Very strange behavior in the squared on first screenshot. Most likely VS Code does not support `@at-root`. As I understand it, on the second screenshot you manually chose the language?

Sass is a language. SCSS is the syntax of this language. You don't need use this extension for SCSS syntax.

**Comment by biorz** [comment]
This is the installation of an expanded more language option, use after he was not wrong。

![qq 20160723092306](https://cloud.githubusercontent.com/assets/15077010/17074950/66d2a176-50b7-11e6-8312-1857cc00b328.png)

**Comment by mrmlnc** [comment]
@biorz, in this panel, Sass is a SCSS. The extension that you have installed is for Sass (syntax without braces).

You described the problem already exists in Issues tracker - #4524.

**Comment by mrmlnc** [comment]
@kieferrm, you can mark this question as a duplicate, if that makes sense. :dancer:
