### ISSUE TITLE
Custom views shall contribute icons for themselves

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93968]
Testing https://github.com/microsoft/vscode/issues/93786

Since views can be moved to activity bar, we shall allow custom views to contribute icons so that we can use them when they are moved to activity bar. Otherwise we can show default icon as today.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/10746682/78043879-31f8a200-7374-11ea-88ef-8ea1c45193dc.png">

**Comment by sbatten** [comment]
done by 6b4258e72491d474ced673085ff8693307fd8a79
