### ISSUE TITLE
Color themes apear blocky in empty regions of the editor window.

### ISSUE THREAD

**Issue by L0stLink** [microsoft/vscode#93977]
Issue Type: <b>Bug</b>

When you have a file open which contains text that leaves large parts of the open editor blank, the background color of the theme does not get applied to the empty space and the the editor tab looks blocky, a bit like color banding. 

the issue exists in both light and dark themes: pictured Dracula color theme and 

Issue as it appears in light themes (Pictured Gruvbox Concoctis Medium Light):
![vscode-color banding](https://user-images.githubusercontent.com/36127183/78045280-33839380-738f-11ea-8d88-8b61aee75fd9.png)

Issue as it appears in dark themes (Pictured Dracula color theme):
![vscode-color banding-dark](https://user-images.githubusercontent.com/36127183/78045300-38e0de00-738f-11ea-8d17-50661bd071cd.png)

The relevant areas have been outlined using red blocks, the original images are attached below as reference:
![dark](https://user-images.githubusercontent.com/36127183/78046282-667a5700-7390-11ea-962a-8aaf6eb29c1e.png)
![light](https://user-images.githubusercontent.com/36127183/78046286-68441a80-7390-11ea-9375-3789aa032694.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2505)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (2.76GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
githistory|don|0.6.3
gitlens|eam|10.2.1
docker-explorer|for|0.1.7
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
ruby-rubocop|mis|0.8.3
vscode-docker|ms-|1.0.0
python|ms-|2020.3.69010
vsliveshare|ms-|1.0.1847
ruby|reb|0.27.0
gruvbox-concoctis|whe|10.30.20
vscode-ruby|win|0.27.0

(2 theme extensions excluded)

</details>

**Comment by igormartimiano** [comment]
Can confirm that, same bug happening to me. Will help with any tracking info if needed.

**Comment by deepak1556** [comment]
@L0stLink @igormartimiano Do you observe any changes after the following

```
* Command Palette search for "Configure Runtime Arguments"
* Set "disable-color-correct-rendering":  false
* Restart
```

**Comment by igormartimiano** [comment]
@deepak1556  Just saw the discussion at #84690 before your reply, I previously have set `"disable-hardware-acceleration": true` and it was apparently fixed.

The following: 
`"disable-hardware-acceleration": false`
`"disable-color-correct-rendering": false`
Also seems to work.

**Comment by deepak1556** [comment]
Thanks for confirming!

**Comment by GrbavaCigla** [comment]
I have the same issue, is there a way to fix it and use hardware acceleration?
