### ISSUE TITLE
Optimize use of real estate with collapsed views

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#93970]
#93787

I understand the resistance towards having some sort of vertical label, but the use of real estate currently doesn't make sense. The space used for the collapsed view is much larger than would be needed for its label to be shown in full, yet the label is cut off:

![image](https://user-images.githubusercontent.com/9205389/78043953-46d53580-7374-11ea-8c63-fc7dae14fa89.png)

**Comment by sbatten** [comment]
@chrmarti in fact we would like to have the collapsed vertically, but a chromium bug prevented doing this the right way with proper locale support. https://bugs.chromium.org/p/chromium/issues/detail?id=1058859

**Comment by sbatten** [comment]
closing as dupe since I  used a different issue
