### ISSUE TITLE
Move view picker should have a title saying which the view to be moved

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93979]
Testing #93786

<img width="654" alt="image" src="https://user-images.githubusercontent.com/10746682/78045961-dda2f180-7376-11ea-9205-7031478ccd59.png">

The picker shall have title: `View: Move Variables`

**Comment by sbatten** [comment]
To Verify:
1. Bind a keyboard shortcut to `Move Focused View`
2. Use the keybind on a focused view. Verify that the quick pick has a title indicating the view that will be moved.
