### ISSUE TITLE
Moving a single view in container to a new container does not makes sense

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93975]
Testing #93786

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/10746682/78045579-6bcaa800-7376-11ea-9f12-2a1206d1afbb.png">

First option in the above pic should not be there even though it does nothing.

**Comment by sbatten** [comment]
To Verify:
1. Add a keybinding for `Move Focused View`
2. Move a single view to the activity bar, creating a container with a single view (e.g. timeline)
3. Ensure the view has focus and press your keybind to trigger `Move Focused View`
4. Verify that `New container in Side Bar` is not an option.
5. Repeat with a view in the steps 2-4 except moving a view to the panel and verifying `New Container in Panel` is not an option.
