### ISSUE TITLE
Shift + Ctrl + M - Should move focus to errors panel, even if it's already active

### ISSUE THREAD

**Issue by thematthopkins** [Microsoft/vscode#9397]
- VSCode Version: 1.3.1
- OS Version: OSX 10.11.5

Steps to Reproduce:
1. Open a .cs file
2. Introduce 2 syntax errors that will show up as problems
3. Use Shift + Ctrl + M to navigate to the first error an fix it
4. Attempt to use Shift + Ctrl + M to navigate to the next error

**Result:**
Errors panel is hidden

**Expected Result:**
Errors panel receives focus

**Comment by thematthopkins** [comment]
This was previously discussed in #8012, and #7540.  The decision then was to have consistency across panels w/ the command toggling visibility.  Focus would seem to be more keyboard nav friendly.  Even focusing the output panel would make sense rather than toggle, because I'd typically focus into it, then use page up/down for browsing.   I 100% agree w/ @sandy081's proposal in #7540

**Comment by sandy081** [comment]
Please provide your opinions / suggestions in already existing item #7540.

Duplicates #7540
