### ISSUE TITLE
Allow viewdescriptor to take containerName for when they are alone in a custom view container

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93972]
Testing #93786

<img width="582" alt="image" src="https://user-images.githubusercontent.com/10746682/78044779-67ea5600-7375-11ea-8b9c-a89e10f07ecf.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/10746682/78044799-70429100-7375-11ea-9ffb-fcf65a381642.png">

**Comment by sbatten** [comment]
Should outline have `Explorer` title when moved outside of Explorer? I think we cannot be consistent and thus we should just do one thing and allow renaming.

**Comment by sandy081** [comment]
I think we can allow an optional additional property on the view descriptor to have generated container name. Debug views then can provide that ?

**Comment by sbatten** [comment]
We allow containerIcon today, so I suppose containerName is analagous?

**Comment by sbatten** [comment]
allowed by 56b8c192051b277ed775332ae24a0ab3425e2947
