### ISSUE TITLE
Unnecessary drop feedback if the position is not changing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93971]
Testing #93786

![Kapture 2020-03-31 at 17 25 37](https://user-images.githubusercontent.com/10746682/78044318-cb27b880-7374-11ea-98d2-31a064348ed8.gif)

**Comment by sbatten** [comment]
i get that this is not telling you much, but even the editor does this and other apps I tested still show it as well in this case. i wonder if we should keep it just as consistency

**Comment by sandy081** [comment]
No hard opinions on this. Feel free to close it.
