### ISSUE TITLE
Editor cannot find ANY modules when files use '.es6' extension.

### ISSUE THREAD

**Issue by Symbitic** [Microsoft/vscode#9398]
- VSCode Version: 1.3.1
- OS Version: Fedora 24

Steps to Reproduce:

1. Rename an existing JavaScript file to use the extension '.es6' (e.x. rename 'server.js' to 'server.es6').
2. vscode will complain that every module (both local and node_modules) cannot be found. For example, given the following code:
```javascript
import Promise from 'bluebird';
import Router from './router.es6';
```
vscode will say that "Cannot find module 'bluebird'" and "Cannot find module './router.es6'. Removing the extension from the import statement (`import Router from './router'`) doesn't fix it.

Screenshot:

![vscode](https://cloud.githubusercontent.com/assets/9487468/16897452/b9e45ed0-4b77-11e6-999f-e2ecea7dfe59.png)

My jsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "es2015",
    "allowSyntheticDefaultImports": true,
    "noResolve": true
  }
}
```

Dev Tools Console did not display any warnings or errors, and I created the above screenshot while in --disable-extensions mode.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/TypeScript/issues/9551
