### ISSUE TITLE
Indicate dirty workspaces in "Open Recent"

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#93984]
refs #93729:

I have never used the "Open Recent" quickpick because I'm always using the "Open Recent..." menu. So I was really surprised that the dirty workspaces are not marked in that menu:

<img width="1294" alt="2020-03-31_17-54-50" src="https://user-images.githubusercontent.com/1898161/78047893-37a4b680-7379-11ea-85da-03da2abaff31.png">

but that they are only marked in the "Open Recent" quickpick.

**Comment by bpasero** [comment]
Yes, @Tyriar suggested the same. We cannot draw decorations in that menu, e.g. to indciate dirty state in the same way. One idea maybe is to have a submenu in there to list all workspaces with dirty files because the list can potentially be very large.
