### ISSUE TITLE
Only the first 1000 search results are available error

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#93983]
Testing #93742

* Run a query like `repo:microsoft/vscode label:bug assignee:alexdima`
* This shows a 422 status error message because it tries to fetch `https://api.github.com/search/issues?q=repo%3Amicrosoft%2Fvscode%20label%3Abug%20assignee%3Aalexdima&sort=undefined&order=desc&per_page=100&page=11`
* Even in a browser, when I open that page I see the following:
```
{
  "message": "Only the first 1000 search results are available",
  "documentation_url": "https://developer.github.com/v3/search/"
}
```

I don't know if I'm rate limited or something (due to searching for `hello` previously), but it looks like there is a hard limit of 1000 issues for this query.

**Comment by jrieken** [comment]
<img width="524" alt="Screenshot 2020-04-01 at 14 48 19" src="https://user-images.githubusercontent.com/1794099/78138979-0d5e0200-7428-11ea-934f-433b03e24d2e.png">
