### ISSUE TITLE
Inconsistent behavior between dirty files and dirty workspaces 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#93988]
refs #93729:

- open VS Code on a single file and make that file dirty
- quit VS Code
- start VS Code from command line with a folder passed as argument

Observe:
VS Code opens the folder (as requested) but another window shows the dirty file.

This behavior is different from the case with a dirty workspace, where only a single workspace is opened.

**Comment by bpasero** [comment]
Yes, intentional. The rationale is that you can never restore "empty" workspaces because you cannot open them from the OS. Folders and workspaces can be opened from the OS.
