### ISSUE TITLE
Multi query in quick open conflicts with task and term quick access

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93985]
1. `Ctrl+P`
2. Type `task myworkspace`
:bug: => You are in the task quick access menu so this will not work.

I'm assuming we will just live with this as it is a rare case but just documenting it.

**Comment by bpasero** [comment]
Yeah to be fair we have this "issue" since day one because you could have always searched for "task <space> myworkspace" and we simply normalized it to a query of "taskmyworkspace". 

Still, the task picker is in the way.
