### ISSUE TITLE
VSCode recommends the mssql extension for everything

### ISSUE THREAD

**Issue by acdha** [microsoft/vscode#93987]
Issue Type: <b>Bug</b>

I haven't used MS SQL Server in 15 years but every time I open a SQL file for my Postgres / MySQL / Hive projects VSCode tries to get me to install that extension.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 5, 4|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
language-prometheus|caa|0.1.2
systemd-unit-file|coo|1.0.6
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.2
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
prettier-vscode|esb|3.20.0
gitlab-workflow|fat|2.2.0
todo-tree|Gru|0.0.171
vscode-cfn-lint|kdd|0.10.17
restructuredtext|lex|122.0.0
terraform|mau|1.4.0
rainbow-csv|mec|1.6.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.0.0
python|ms-|2020.3.69010
cpptools|ms-|0.27.0
Go|ms-|0.13.1
sqltools|mtx|0.21.6
neuron-IPE|neu|1.0.4
vscode-yaml|red|0.7.2
vscode-ansible-linter|rup|0.14.0
rust|rus|0.7.0
preview-vscode|sea|2.1.0
crates|ser|0.4.9
stylelint|shi|0.51.0
fish-vscode|sky|0.2.1
rewrap|stk|1.9.1
vcl|tho|0.1.2
shellcheck|tim|0.9.0
sort-lines|Tyr|1.9.0
vscode-ansible|vsc|0.5.2
propertylist|zho|0.0.2

</details>

**Comment by sana-ajani** [comment]
Hi, thanks for reporting. It's hard to strike a balance for which extension to recommend when opening a .sql file, as we cannot tell if it is SQL server or MySQL. We balance it out by having an "important recommendation" for the mssql extension and "passive recommendations" for [vscode-database](https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-database) and [SQL Tools](https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools) extensions. You can click on the gear of the notification and click "don't show again". 

Discussion for this decision in a previous issue:
https://github.com/microsoft/vscode/issues/41368#issuecomment-516196125

**Comment by acdha** [comment]
Could “Don't show again” be more clear about whether it means “Don't suggest mssql for .sql files”, “don't suggest anything for .sql files”, or “don't suggest extensions for anything”?

**Comment by sana-ajani** [comment]
Two recent tweets about this too:
https://twitter.com/jbinsen/status/1301114423688470528
https://twitter.com/JLarky/status/1301242179092795392

@chrisdias thoughts on removing the "important" mssql recommendation and just leave the passive recommendation in?

**Comment by chrisdias** [comment]
fixed with 5177f0d777468ce08a31670ff6fe55b70f9b4a8a, mssql should not be an important recommendation, but instead will just show up in the recommended list (type `@recommended` in Extension view).
