### ISSUE TITLE
Views following last custom view

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#93981]
Issue Type: <b>Bug</b>

#93785

- Have a custom panel with two custom views.
- Move one of the custom views to a built-in viewlet (e.g., Debug).
- Move a built-in view (e.g., Variables) from that built-in viewlet (Debug) to the custom panel.
- Move the second custom view to the built-in viewlet (Debug).
-> The built-in view (Variables) also goes back to the built-in viewlet (Debug). 🤷‍♂ 

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.47GB free)|
|Process Argv|-psn_0_3851180|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.39GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js 12 & TypeScript|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.39GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.1.1
vscode-docker|ms-|1.0.0
remote-containers|ms-|0.109.0
remote-ssh-edit-nightly|ms-|2020.3.44100
remote-ssh-nightly|ms-|2020.3.44100
remote-wsl|ms-|0.44.2
debugger-for-chrome|msj|4.12.6
vscode-eslint|dba|2.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
I do not reproduce this issue, can you please confirm and capture a gif?

**Comment by chrmarti** [comment]
![Apr-03-2020 07-39-54](https://user-images.githubusercontent.com/9205389/78328084-912a0280-757e-11ea-9890-6a59fa3c30d8.gif)

Shows it with just one custom view. You see me first drag the built-in view to the panel and then the custom view to the viewlet. After that I wait and after a second or two the built-in view jumps back to the viewlet and the custom panel disappears because there is no view left. Code checked in at https://github.com/microsoft/vscode-remote-containers/tree/chrmarti/93981 just in case.
