### ISSUE TITLE
Be more specific about sync time in settings editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93990]
#93801

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

This:

![image](https://user-images.githubusercontent.com/2193314/78051996-57b18700-7333-11ea-9d78-91cc236ed1ba.png)

Reminds me of this in onenote:

![image](https://user-images.githubusercontent.com/2193314/78052044-6a2bc080-7333-11ea-84cb-39d3f2012e52.png)

The latter of which drives me crazy as it always lies to me and a restart to re-sync onenote is needed sometimes. Can we get the local time down to the second when you hover the last synced text?

**Comment by roblourens** [comment]
@Tyriar what are the current setup steps for Sync in OSS? I have the `configurationSync.store` setting set to whatever I tested it with a couple months ago but I don't see any Sync commands in the command palette. I can't remember where this is written down.

**Comment by Tyriar** [comment]
Here are the instructions:

https://github.com/microsoft/vscode-settings-sync-server#vs-code-oss

You might be missing the shared process part?

**Comment by roblourens** [comment]
Could just put the real time in a tooltip, if that helps

**Comment by Tyriar** [comment]
I think just the product.json change is needed to get it going in Code OSS.

`Last synced x seconds ago` would solve my problem.
