### ISSUE TITLE
Settings UI: Workspace has a lowercase w?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93993]
Not sure why it's lowercase and user is upper?

![image](https://user-images.githubusercontent.com/2193314/78053148-06a29280-7335-11ea-84f0-b5f67d68002a.png)

**Comment by roblourens** [comment]
Lol, did you do something weird? Not sure how that's possible

**Comment by Tyriar** [comment]
Not that I'm aware of, happens in remotes as well:

![image](https://user-images.githubusercontent.com/2193314/78055782-e674d280-7338-11ea-905c-e2380a6e8d88.png)
![image](https://user-images.githubusercontent.com/2193314/78055828-f68cb200-7338-11ea-9302-150940087f37.png)

**Comment by Tyriar** [comment]
Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
I tried on Windows too and don't see it. Could you set a breakpoint at this line in `preferencesWidgets.ts` and see if something crazy happens? Is the correct localized string retrieved and set as the action label?

`this.workspaceSettings = new Action('workspaceSettings', localize('workspaceSettings', "Workspace"), '.settings-tab', false, () => ...`

Or we can have a call and I can debug a bit

**Comment by Tyriar** [comment]
Was going to respond to this but I guess I forgot to hit the comment button. Pretty sure this is happening because of the en-GB language pack I'm using. Hit a similar issue in open recent.
