### ISSUE TITLE
Settings UI: Setting scopes shouldn't have title attributes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93994]
This hover adds nothing and just gets in the way:

![image](https://user-images.githubusercontent.com/2193314/78053215-21750700-7335-11ea-8353-5b820b7334ef.png)

**Comment by gjsjohnmurray** [comment]
@Tyriar see https://github.com/microsoft/vscode/issues/90981#issuecomment-588832480 and #91982 for how this hover is soon going to become useful.
