### ISSUE TITLE
Easier to turn off preferences sync

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#93999]
Testing https://github.com/microsoft/vscode/issues/93799

If I wanted to stop syncing on a certain account, I'd expect to do at the same place I turned on preferences sync in the settings UI. Maybe being able to click on the "last synced" time and open the quick pick where you can turn it off.

**Comment by roblourens** [comment]
I dunno, I don't expect turning off sync to be a common action but I would consider this. We have also discussed having a button at that spot that would open the command palette with all the sync-related actions, including Turn Off Sync, so that might address this too.
