### ISSUE TITLE
Settings UI: Tab navigating skips links in settings when moving from ToC to content

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93998]
![c48803cc-c910-451d-8aaa-359deb842ad4](https://user-images.githubusercontent.com/2193314/78053511-8f213300-7335-11ea-9370-1648cd9af8d9.gif)

**Comment by roblourens** [comment]
The code is going to the first control on purpose, because I figured that's what people want. But it probably makes sense to just follow tab order?

**Comment by Tyriar** [comment]
Yeah I assume that was the intent, it's weird that you press tab again and you select the link in the second setting though. Pressing down from the search box focusing the value is good as is since you're already skipping a bunch of things.

**Comment by roblourens** [comment]
Probably not going to change this outside of the more general work we are doing in the settings editor.
