### ISSUE TITLE
Extend the Search tab (Search Results) with Context Menu

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#9399]
The Search results has no Context Menu entries today. It shows files and lines, but you can only click to expand/collapse the results in file, remove a file from the list and navigate to one of the results (lines in file).

It would be interesting to have the same operations for files, that you can use in the Explorer tab, like `Open on the Side`, `Reveal in Explorer` and so on. And also, open a similar Context Menu API that was added to Explorer tab in vesion 1.3.0.

Thanks in advance

**Comment by sandy081** [comment]
duplicates #8594
