### ISSUE TITLE
Reconsider sync ignored icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93992]
#93801

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

I suggested this earlier, not sure what the reason is for going with the eye which imo is less clear as it can mean follow/watch as well. Wouldn't something like this be better as we already have a sync icon in the product?

![image](https://user-images.githubusercontent.com/2193314/78052510-1a012e00-7334-11ea-8c3b-c7db5975554a.png)

**Comment by sana-ajani** [comment]
Agree, I think the eye icon indicates you can click on it to sync again the slash on the icon would go away. Edge's icon is: 
![image](https://user-images.githubusercontent.com/9721254/78066162-6fecca80-7362-11ea-851b-dee3cce82677.png)

**Comment by misolori** [comment]
We did talk about using an alternate icon, I think the proposed one makes sense. How's this? This follows the same slash as the one from the ignored/hidden icon:

![image](https://user-images.githubusercontent.com/35271042/78072737-783e0900-7354-11ea-8bda-f3d424b9df77.png)

![image](https://user-images.githubusercontent.com/35271042/78074689-02d43780-7358-11ea-899b-da680f46b9b6.png)

**Comment by misolori** [comment]
@roblourens @sandy081 this icon is now part of codicons as `sync-ignored`:

![image](https://user-images.githubusercontent.com/35271042/78075168-e08ee980-7358-11ea-90d3-81b5637bd88f.png)
