### ISSUE TITLE
The sync ignored icon looks off in settings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93991]
#93801

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

It looks a little strange as it's straight surrounded by slanted text.

![image](https://user-images.githubusercontent.com/2193314/78052271-bc6ce180-7333-11ea-8d57-db0bd0cf53ef.png)

Why is sync special that it gets an icon there compared to other annotations?

![image](https://user-images.githubusercontent.com/2193314/78052364-dc9ca080-7333-11ea-831d-d2d08d77bd09.png)

**Comment by sana-ajani** [comment]
Yeah, I agree I think having the icon there in settings looks odd

**Comment by roblourens** [comment]
@misolori @sandy081  should we switch this to just an icon with a tooltip, like in the extension viewlet?

**Comment by sandy081** [comment]
Yeah.. just icon makes sense.

**Comment by misolori** [comment]
So it would look like this (no italics):

![image](https://user-images.githubusercontent.com/35271042/78193207-d808e280-742e-11ea-9eb3-b626b27f9a76.png)

**Comment by DanTup** [comment]
> should we switch this to just an icon with a tooltip, like in the extension viewlet?

Is it possible this tooltip could be a bit more detailed than just "Sync: ignored"? A few people have asked my why this is showing up against Dart settings (things like SDK paths) so I don't think it's very clear to the average user what this means (for most, it's not relevant).

**Comment by roblourens** [comment]
Adding a tooltip with a few more words would make sense. Just something like "This setting is not synced"?

**Comment by DanTup** [comment]
@roblourens the most recent person to ask me about it had no idea about VS Code's setting sync, so interpreted this as meaning the setting wasn't being applied from the file into the current VS Code session.

Maybe something like "This setting is not synced to other machines/remotes" and/or a link to https://code.visualstudio.com/docs/editor/settings-sync?

**Comment by Tyriar** [comment]
Should we only show it when sync is enabled? Alternatively it could have a link to the turn on sync command?

**Comment by roblourens** [comment]
> Should we only show it when sync is enabled

Oh, definitely that. I was thinking that was the case but I think I enabled it when sync _can_ be enabled.

**Comment by rzhao271** [comment]
There is no icon now. Instead, the indicator says "Not synced".
An example setting to view is `emmet.extensionsPath`.
