### ISSUE TITLE
"Go to symbol in workspace" no longer has "type to search for symbols" entry

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#94007]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/93636

1. Run  the command "Go to symbol in workspace" in the vscode repo (originally found when selecting it from the help picker, but repros no matter how it's called)

When no entries are found in stable, it previously had a "type to search for symbols" entry. Now there are no entries

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
I decided to remove these default entries as I found them to not be helpful. I am especially worried about accessibility that people may think there is a result. Imho the placeholder should provide sufficient information and we should not add fake results. The "Go to Line" and extensions picker is the only exception so far.
