### ISSUE TITLE
Settings UI: Support theming the line where user and workspace scopes can be selected

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94002]
This greyscale line looks off in my theme and it looks the same across all themes so I guess we can't theme it currently? Alternatively using transparent white (for dark) instead of opaque greyscale would be a good enough fix for me.

![image](https://user-images.githubusercontent.com/2193314/78053936-27b7b300-7336-11ea-9402-0291b178000c.png)

**Comment by roblourens** [comment]
It's the same color as the text above, and you can use `settings.headerForeground` does that do it for you?

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/78164935-2d81c700-7410-11ea-9f1d-d58d9ce21a50.png)

**Comment by Tyriar** [comment]
@roblourens I mean the grey line under Workspace in your screenshot.

**Comment by Tyriar** [comment]
It's the only dark color without a blue hue here:

![image](https://user-images.githubusercontent.com/2193314/78165395-1d61eb80-7400-11ea-8ccb-f514eeda3795.png)

Ideal:

![image](https://user-images.githubusercontent.com/2193314/78165474-38ccf680-7400-11ea-8210-c233fd575611.png)

**Comment by roblourens** [comment]
Oh right

**Comment by rzhao271** [comment]
It can now be themed with the key `settings.headerBorder`.
