### ISSUE TITLE
Writing login information to the keychain failed with error 'The specified item already exists in the keychain.'.

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#94005]
I keep getting this randomly

![image](https://user-images.githubusercontent.com/323878/78055711-8dfa0100-7349-11ea-8985-19e5fa4b8395.png)

**Comment by RMacfarlane** [comment]
@roblourens What version of macOs are you on?

**Comment by roblourens** [comment]
10.14.6. Oh wait, this is the mysterious error I was seeing a while back right? I should just update to Catalina, been putting that off for awhile.

**Comment by towry** [comment]
I got this error every time I unlock the computer in the morning at work. While the Code Insiders keep opening in the whole night.

<img width="454" alt="Screen Shot 2020-04-02 at 8 00 03 AM" src="https://user-images.githubusercontent.com/8279858/78197639-8016be00-74b8-11ea-8e48-5597c603febf.png">

**Comment by RMacfarlane** [comment]
Easy repro steps: Open VSCode and mash the "New Window" keybinding to get ~10 windows in a short period of time.

Each window reads the existing refresh token from keytar and refreshes, simultaneous writes to keytar cause this error.

**Comment by sampotts** [comment]
Also seeing this on Catalina 10.15.4:

```
Version: 1.44.0-insider
Commit: e8dbc5ea6092ba73ae70069d3e730f2cc56addff
Date: 2020-04-03T22:09:44.908Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by etetlow** [comment]
Same Issue on Catalina 10.15.4:

Version: 1.44.0-insider
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T21:42:32.364Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
