### ISSUE TITLE
Workspace symbols quick open do not highlight all query words

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#94009]
Version: 1.44.0-insider
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:22:34.682Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

Ref: #93645

Steps to Reproduce:

1. In vscode repo
2. Type query `#foo actions platform`
3. I would expect both `actions` and `platform` highlighted.

![image](https://user-images.githubusercontent.com/4033249/78058227-d2cb6b00-733c-11ea-9ab0-dbe8fe4c9661.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Quite a large change, needs verification. Now both workspace and editor symbol search will take each query input after the first to match on the container, e.g. a query like `foo bar xyz more` will  match `foo` on the symbol name and individually `bar`, `xyz` and `more` on the container.
