### ISSUE TITLE
Integrated Powershell terminal Freezing and intellisense absent in the editor

### ISSUE THREAD

**Issue by KeetsScrimalittle1** [microsoft/vscode#94006]
Version: 1.43.1 (system setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open VS Code and use 10 - 30 minutes
2. Integrated terminal unresponsive, Intellisense no longer working.  Also added 

"powershell.scriptAnalysis.enable": false

to my json file after reading other performance related issue suggestions.  Has not helped. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Settings JSON

{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "window.zoomLevel": 0,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "explorer.confirmDragAndDrop": false,
    "files.autoSave": "afterDelay",
    "powershell.powerShellDefaultVersion": "Windows Powershell (x64)",
    "editor.accessibilitySupport": "off",
    "workbench.iconTheme": "material-icon-theme",
    "files.encoding": "utf8bom",
    "terminal.integrated.rendererType": "dom",
    "powershell.scriptAnalysis.enable": false
}

After I open a VSCode PowerShell integrated terminal it works for maybe 10 - 30 mins but eventually it becomes unresponsive and currently intellisense in the editor no longer makes suggestions regardless of the integrated terminal working or not.  If I use the regular PowerShell terminal I can type fine.  Integrated terminal is frozen until I close it and launch another integrated terminal.  Not sure if something has changed recently in an upgrade or something as my integrated terminal formatting looks different lately, but i have not changed my json file except for adding: "powershell.scriptAnalysis.enable": false which i did after the issue started hoping it would help. This has been happening for about a month now and I have updated twice since it has started but nothing has helped.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
