### ISSUE TITLE
Duplicated interfaces in go to symbols in file

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9401]
- VSCode Version: Version 1.4.0-insider (1.4.0-insider)
- OS Version: OSX

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/1723815/16898179/460fdbec-4b9a-11e6-8181-064c69a9a483.png)

In 1.3.1 it seems fine:

![image](https://cloud.githubusercontent.com/assets/1723815/16898180/55fb492e-4b9a-11e6-8181-83d04ae2c1e1.png)

**Comment by dbaeumer** [comment]
This is what I see in 1.4 final:

![capture](https://cloud.githubusercontent.com/assets/1931590/17475565/e703a9e8-5d5b-11e6-94ef-6e8db57c55ad.png)

@wallverb please ping if you still see the issue

**Comment by wallverb** [comment]
@dbaeumer It's still the issue but I tracked down the reason - which is TypeScript 2.0 or 2.1.0

Here are the exact steps I did: (I have `nvm` installed)
1. `npm install --global typescript@next`
2. `tsc -v` => `Version 2.1.0-dev.20160808`
3. Edit VSCode settings and add `"typescript.tsdk": "/Users/{username}/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib"`
4. Create test.ts file with: 
```ts
export interface ITest {
    
}
export interface ITest2 {

}
export interface ITest3 {

}
```
Run `code test.ts`

Issue is in both insiders and final 1.4.0

![image](https://cloud.githubusercontent.com/assets/1723815/17478895/fee9b756-5d3c-11e6-8aaf-6470efec1d62.png)

**Comment by dbaeumer** [comment]
OK. Moving to the TS team then. Looks like a problem on their end.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10222
