### ISSUE TITLE
Hrule between different welcome view contributions?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94016]
Ref: #91269

It might be nice to insert hrules between welcome view contributions, currently it can be confusing which lines go together and the extension cant contribute their own hrules (even if they could that wouldn't work right as they dont know if something is above/below them.

![image](https://user-images.githubusercontent.com/8586769/78059931-951c1180-733f-11ea-8343-c022eaf0dffc.png)

**Comment by isidorn** [comment]
This is a fair idea, however it goes against the inital design of the welcome view content.
For now leaving it open as a feature request and we might reconsider it in the future if there is too much content and the welcome views get cluttertd.
fyi @joaomoreno
