### ISSUE TITLE
Debug progress bar fills up too quickly

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#94015]
Refs: https://github.com/microsoft/vscode/issues/92914

Seems like the bar is filled around 40-45% or so

```js
dap.progressUpdate({
  progressId: 'p1',
  message: String(percentage),
  percentage,
});
```

![](https://memes.peet.io/img/20-03-9895392a-39ef-4ed8-a0c9-c23e0e944220.png)

**Comment by isidorn** [comment]
Great catch. My 4th grade math was a bit off :)
