### ISSUE TITLE
Line picker does not automatically highlight line when editor input changes

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#94019]
ref #93636 

While verifying this:
"verify you can leave the picker open and focus another editor in the background and the picker still works (e.g. you can start from a non-text editor, open goto line picker and then click on a text editor while the picker is open to use it)"

- In the picker I had entered "12" which highlighted line 12 in the editor.
- when selecting another file in the explorer (and the line picker still open), line 12 in the new file is not automatically highlighted. 

I don't know whether this is the expected behavior.

**Comment by bpasero** [comment]
This should work now, there was a bad dispose of the decorations that lead to weird results. I can see this work like this now:


![Kapture 2020-04-01 at 12 12 54](https://user-images.githubusercontent.com/900690/78126008-252a8b80-7412-11ea-8563-f00132bf54e7.gif)
