### ISSUE TITLE
View picker not correctly update when moving views

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#94012]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/93636

1. Open quickpick and type `view ` to show view picker
2. Verify that "Outline" is shown under the "Sidebar / Explorer" section
3. Drag "Outline" from there to its own container in the panel
4. Open the view picker again, "Outline" is shown both under "Panel" and still under the "Sidebar / Explorer" section. I expected it to be removed from "Sidebar / Explorer"

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
This is not an issue with the new implementation, I copied the code over. Instead, the view picker needs to be made fit for the newly added support to move views. 

Code pointer: https://github.com/microsoft/vscode/blob/9e8080a9207eb605746996b641a2926418f4d9e0/src/vs/workbench/contrib/quickaccess/browser/viewQuickAccess.ts#L90

**Comment by bpasero** [comment]
@sandy081 thanks!
