### ISSUE TITLE
Opening "refactor preview" from view picker does nothing

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#94010]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/93636

1. Open quickpick and type `view ` to show view picker
2. Under the "Panel" section, select "Refactor Preview"

No view is revealed in the panel. Same thing happens in stable, so not a regression.

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
@jrieken might need your help, I see that "References" for example only appear if they appear in the side bar, but "Refactor Preview" is always there. Whatever you do to make this work nicely for "References" can we do the same for "Refactor Preview"?

**Comment by bpasero** [comment]
Alternatively we could allow to open this panel even if empty.

**Comment by jrieken** [comment]
References view is an extension and refactor preview is built-in. Not sure what the extension integration does better...

**Comment by bpasero** [comment]
@jrieken you possibly contribute a `when` condition which the picker evaluates here:

https://github.com/microsoft/vscode/blob/8084a58504f23b60654d4e9381821bc57660c9b2/src/vs/workbench/contrib/quickaccess/browser/viewQuickAccess.ts#L97

**Comment by jrieken** [comment]
I have that: https://github.com/microsoft/vscode/blob/15bdd26e460fb16ca3cca2202875de4d31863f4c/src/vs/workbench/contrib/bulkEdit/browser/bulkEdit.contribution.ts#L362

**Comment by bpasero** [comment]
Looks like I need to check on the `hideIfEmpty` property also for panels.
