### ISSUE TITLE
When conditions for welcome views not working

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94025]
ref #91269

I might be doing something wrong here, but I tried setting

```
{
				"view": "scm",
				"contents": "panel is at bottom",
				"when": "panelPosition = bottom"
			},
			{
				"view": "scm",
				"contents": "panel is at left",
				"when": "panelPosition = left"
			},

}
```

and confirmed that the panel position is bottom using the context key debugger, but neither contents appeared. Similarly tried with `"when": "activeEditor = workbench.editor.searchEditor"`  and "workbench.editors.textResourceEditor" and again no luck.

**Comment by isidorn** [comment]
Nice try, but you have to use ==
Example https://github.com/microsoft/vscode/blob/9e8080a9207eb605746996b641a2926418f4d9e0/extensions/git/package.json#L807
