### ISSUE TITLE
If progress is cancelled but does not manually emit an end event, the debug view remains 'busy'

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#94022]
Refs: https://github.com/microsoft/vscode/issues/92914

1. Have a progress event
2. Cancel it, and don't manually send a progressEnd after cancellation from the debug adapter
3. The debug view gets stuck as being "busy"

https://memes.peet.io/img/20-03-659125af-4489-4877-83c7-874ed6036e4e.webm

**Comment by isidorn** [comment]
This is designed behavior, since we can not assume that the debug adapter trully canceled the progress. 
I am open to suggestions here
Currently we will complete the progress if the session goes down, which is fair.

fyi @weinand

**Comment by connor4312** [comment]
I think a successful reply to the `cancel` method call from the debug adapter is probably enough of an acknowledgement. If the adapter says the 'cancel' call succeeded and didn't actually cancel the progress event, that's a bug on their side.
