### ISSUE TITLE
VSCode Debug C++, breaking point not working

### ISSUE THREAD

**Issue by freedomabcd** [Microsoft/vscode#9402]
- VSCode Version:1.3.1 
- OS Version:Ubuntu 14.04

I debug an C++ project onUbuntu 14.04. I run cmake to produce an executable file and setting VSCode config file. When I press F5 to debug, the program runs well, but it doesn't stop at breaking point!

my source code is in ${workspaceRoot}/InfiniTAM
executable file is in ${workspaceRoot}/build

My config file:
tasjs.json

{
    "version": "0.1.0",
    "command": "echo",
    "isShellCommand": true,
    "args": ["InfiniTAM!"],
    "showOutput": "always"
}

launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "launchOptionType": "Local",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/build/InfiniTAM",
            "args": ["Teddy/calib.txt", "Teddy/Frames/%04i.ppm", "Teddy/Frames/%04i.pgm"],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}/build",
            "environment": [],
            "externalConsole": true
        }
    ]
}

I will be very appriciate if you help me :)

**Comment by weinand** [comment]
VS Code does not have a builtin C++ debugger. Moving this issue to C++ repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscppsamples#104
