### ISSUE TITLE
viewsWelcome#view schema definition

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94028]
#91269

If I understand correctly, `viewsWelcome` is only enabled for `"view": "scm" | "explorer" | "debug"`. It'd be nice to include these in the json schema definition so developers know what to put in that field.

**Comment by alexr00** [comment]
It is available for all custom contributed tree views now! I deleted that from the schema this month :).

**Comment by isidorn** [comment]
@alexr00 but we should still offer `scm` `explorer` and `debug` and idealy have this open ended that when users put in anything else they do not get an error.
Not sure if possible to be done with a json schema
fyi @joaomoreno

**Comment by alexr00** [comment]
Yes, it is possible with json schema.
