### ISSUE TITLE
GitHub Auth Provider: redirect uri to code-oss from code-insiders

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#94027]
Version: 1.44.0-insider
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:28:37.335Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-72-generic

Testing #93813

Running the basic sample:

```ts
async function activate(context) {
	const scope = ['vso'];
	context.subscriptions.push(vscode.commands.registerCommand(
		"extension.helloWorld",
		async () => {
			const session = await vscode.authentication.login("github", scope);
			const token = await session.getAccessToken();
			vscode.window.showInformationMessage(`Got token ${token}`);
		}
	));
}
```

After signing in with my GH credential, I'm redirected to code-oss, although I launched this extension from code-insiders.

![image](https://user-images.githubusercontent.com/4033249/78063907-c566ae80-7345-11ea-96f3-f1b15bac1fa7.png)

Redirect URI was:

code-oss://vscode.github-authentication?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=8c5dca2e-c60f-4e9a-99fb-a2418a4b97eb

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
Updated the GH app, it should redirect to insiders now
