### ISSUE TITLE
Pass line number to custom editor when opening custom editors

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#94037]
@kieferrm as requested, creating a new issue.
Originally posted here https://github.com/microsoft/vscode/issues/77131#issuecomment-553310152

Please could you add support for line/column information to the custom editor.
E.g. when users open a file from VS Code (in problems pane or debug stackframe), it opens a file and goes to a specific line number.
We'd like to have this functionality in the notebook editor for DS functionality in the Python extension.

* This allows us to build a debugger using the VS Code UI (current plan is to build a debugger with a custom bare minimum UI, without stack frames, without variables, etc, i.e. without majority/any of the VS Code debugger UI).
* Would allow us to add support for notebook outline views
* This will also allow us to add support for linting (displaying problems related to python code in problems window).
& more.

**Comment by mjbvz** [comment]
There are two cases to handle:

- Opening a fresh custom editor at a specific line number
- Telling an existing custom editor to reopen at a specific line number

We could implement the first using the second, e.g. have a method we call to update the line number after creating the initial editor

Related API proposal:  #86146

**Comment by mjbvz** [comment]
I'm prioritizing finalizing custom editors so and will not have time to look into this for April

**Comment by mjbvz** [comment]
Closing this for now due to lack of feedback/additional usecases besides python's custom editors notebooks (which are better served by our notebook api)
