### ISSUE TITLE
Select All Occurrences Keyboard Shortcut Not Working

### ISSUE THREAD

**Issue by TheRealMikeD** [microsoft/vscode#94032]
Issue Type: <b>Bug</b>

In short, the keyboard shortcut for "Select All Occurrences" does not work for me.  I can only invoke that functionality by selecting it from the command palette.

Steps to repro:
1. Select a word in a code editor.
2. Press keys Cmd+Shift+L (on Mac)
3. Nothing happens.
4. Open command palette
5. Choose "Select All Occurrences"
6. Success

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 4, 3|
|Memory (System)|32.00GB (2.80GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
vscode-intelephense-client|bme|1.3.11
vscode-eslint|dba|2.1.2
xml|Dot|2.5.0
apacheconf-snippets|eim|1.3.0
auto-close-tag|for|0.5.6
vscode-apache|mrm|1.2.0
language-gettext|mro|0.1.1
php-docblocker|nei|2.1.0
material-icon-theme|PKi|4.0.1
markdown-preview-enhanced|shd|0.5.2
autoimport|ste|1.5.3

</details>

**Comment by alexdima** [comment]
@TheRealMikeD 
Which commands are bound to the desired key combination? Can you please post a screenshot?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by TheRealMikeD** [comment]
Hi Alex,

Looks like that key combo is bound to "Select All Occurrences of Find Match," which is correct, is it not?  That is the item that I select from the command palette, which works as expected.
<img width="1182" alt="Screen Shot 2020-04-01 at 4 05 13 PM" src="https://user-images.githubusercontent.com/7212311/78194928-4485e080-7433-11ea-868a-8fc6a8909285.png">

Thanks!
-Mike D.

**Comment by alexdima** [comment]
Thanks for following up so quickly. Can you please search for "cmd+shift+L" in the input box and post a screenshot?

**Comment by TheRealMikeD** [comment]
OK, here is the screenshot.  Looks like a few things are bound to that combination.
<img width="1199" alt="Screen Shot 2020-04-02 at 12 27 32 PM" src="https://user-images.githubusercontent.com/7212311/78293465-6fc50a00-74dd-11ea-88b9-ce211786b16a.png">
And now that I see that, it looks like what actually occurs is transforming to lowercase.  I don't remember if I added that explicitly, or maybe it was modified as a part of the theme I am using (is that possible?).

**Comment by alexdima** [comment]
@TheRealMikeD The Source shows `User` so it means that in your personal `keybindings.json` there is a rule to map `cmd+shift+L` to `Transform to Lowercase`. So that rule is overriding the default keybinding.

We do not keep a history of `keybindings.json`, so I'm afraid there is no way to find out when that rule got added. Simply remove that rule from `keybindings.json`.
