### ISSUE TITLE
Markdown cells have semantic highlighting

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#94038]
Testing #93742

* Create a new markdown cell in a github issues notebook
* Observe: the markdown gets semantic highlighting from queries:

![image](https://user-images.githubusercontent.com/5047891/78066437-3aada000-7395-11ea-9df1-3090be95ed8f.png)

**Comment by jrieken** [comment]
It's not semantic but the TM grammar

**Comment by jrieken** [comment]
For some reason, the cell language is github-issues when it's being created. Something with those commands is wrong...

**Comment by roblourens** [comment]
Hadn't noticed this. @rebornix I think the markdown cell text model is just picking up the language from the file extension, what's the right way to force it to be markdown? `setMode`? How do I get the language identifier?

**Comment by rebornix** [comment]
For markdown cell there is no language metadata so it falls back to file extension by mistake ... pushed a fix.
