### ISSUE TITLE
VS Code does not play nicely with Git Bash for Windows

### ISSUE THREAD

**Issue by jamesqo** [Microsoft/vscode#9403]
- VSCode Version: 1.3.1
- OS Version: Windows 10.0.10586

Frequently when I open a repository in VSCode and do some kind of operation from the command-line in [Git Bash](https://git-for-windows.github.io/), such as `git rebase`, `git commit`, etc. I will get this error message:

```
fatal: Unable to create 'C:/Users/James/Code/git/coreclr/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

Sometimes this conflict will mess up local changes I've made (e.g. once it caused Git to skip 2 commits while I was rebasing), which means I had to force-pull everything from the remote and start all over again.

The thing that's kind of strange about it is when I do a `rm .git/index.lock`, most of the times the file will no longer be present; it appears spontaneously *only* when I try to run a Git command from the terminal. Re-running the command once or twice seems to get rid of the error most of the time; however sometimes the `index.lock` file stays and I have to manually remove it.

Unfortunately, I wasn't able to get a consistent repro for this since it seems to only occur randomly when VSCode is open on the repository; but it's never happened after I closed the editor. (I haven't noticed any pattern even though this has been happening to me for months.) Nevertheless, it would be greatly appreciated if someone could take a look into this, even though I can't tell what's causing it.

Thanks! :)

**Comment by joaomoreno** [comment]
Thanks for the detailed issue!

As part of the fix for #901, we've disabled calling `git status` while Code is in the background. This will surely minimize these incidents.

Another thing you can make sure is to always get the [latest git version you can](https://git-scm.com/download/win).
