### ISSUE TITLE
Windows installer switch to disable auto-update

### ISSUE THREAD

**Issue by dsolodow** [microsoft/vscode#94031]
For the system installer, the auto-update requires admin privileges to complete. It would be nice if through a command line switch on the installer (or perhaps a registry key) we could disable the auto-installer so they aren't prompted for an update they can't install without elevation.

**Comment by joaomoreno** [comment]
Change the setting `update.mode` to `manual`.

**Comment by dsolodow** [comment]
Is that a command line parameter or are you talking about the preferences.json?
We're looking at making the application available via Software Center in ConfigMgr, and since our users don't have admin rights, the auto-updater won't get them anywhere.
Would hate to have to put a note for "after you install, go change this setting so you don't get prompted for updates you can't install"
