### ISSUE TITLE
Don't allow dragging the extension viewlet

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94030]
Refs: #93786

Since it can't be moved at all, we should block any dragging.

**Comment by sbatten** [comment]
it can be re-ordered

**Comment by eamodio** [comment]
Not the activity bar icon, the viewlet title.

![image](https://user-images.githubusercontent.com/641685/78154874-c3b2ee80-740a-11ea-8041-397079ffb06d.png)
