### ISSUE TITLE
Unclear how to edit markdown cell

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#94039]
Testing #93742

* I have created a new markdown cell, but now it is not possible to edit the cell contents anymore. I have tried:
* double clicking
* pressing enter
* right clicking
* looking for actions around the cell

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78066721-c0c9e680-7395-11ea-8edc-d674e84ccddf.gif)

**Comment by rebornix** [comment]
@roblourens did we remove the edit button for markdown?

**Comment by roblourens** [comment]
Yeah, lost that due to not considering the cellEditable default from the document.
