### ISSUE TITLE
Panel toggle commands no longer seem to work properly

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94035]
Refs: #93786

I have the following keybindings setup:
```json
    {
        "key": "ctrl+1",
        "command": "workbench.debug.action.toggleRepl"
    },
    {
        "key": "ctrl+2",
        "command": "workbench.actions.view.problems"
    },
    {
        "key": "ctrl+3",
        "command": "workbench.action.output.toggleOutput"
    },
```

And they no longer seem to work

**Comment by sbatten** [comment]
To Verify:
Default Keybindings for Panels:
Problems (Ctrl/Cmd+Shift+M)
Output (Ctrl/Cmd+Shift+U)
Debug Console (Ctrl/Cmd+Shift+Y)
Terminal (Ctrl+`)

1. Move all of these views to non-default locations (e.g. as views in the Activity Bar)
2. Use the keybindings above to focus/toggle the views. This will hide the sidebar/panel if the view is already focused like before.

**Comment by eamodio** [comment]
@sbatten I can't reproduce it anymore (and it only happen a few times -- but all back to back) but what happened was using (Ctrl+`) only toggled the panel, and didn't switch to the terminal. But once I toggled views on and off, I couldn't get it to happen again and everything works fine. Maybe some bad initial state?

**Comment by sbatten** [comment]
It's important that the views are not in their default position when testing. If you reset the view locations all would be well before and after the fix. If a new insiders has not been released since this afternoon my fix may not yet be in.

**Comment by sbatten** [comment]
I removed the verified label on the assumption that my fix has not yet shipped since I am on mobile I did not check. If I am mistaken, please re add.
