### ISSUE TITLE
Dropdowns in panel (with more than 1 view) are slightly too tall

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94040]
Refs: #93786

Its hard to see, but the bottom border of the dropdown is getting cut off:
![image](https://user-images.githubusercontent.com/641685/78066675-63b53d00-7363-11ea-995a-dc318cca17fc.png)

FYI, this looks fine in the sidebar

**Comment by sbatten** [comment]
To Verify (on windows/linux):
1. Move output or terminal to another panel with another view.
2. Verify the select box looks and functions correctly.
