### ISSUE TITLE
Activity bar dragging can be hard to see drop indicators

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94042]
Refs: #93786

![image](https://user-images.githubusercontent.com/641685/78066985-f3f38200-7363-11ea-8ca6-c67975de8ed9.png)

It might be nicer to just have the dragging be the icon rather then the whole box.

**Comment by sbatten** [comment]
I tried just the icon, but it becomes very hard to see what you are dragging when you move out and I have pretty much no control over the opacity, its all or nothing it seems with native dnd. As a compromise, I've shifted the icon out from under the cursor to alleviate this.
