### ISSUE TITLE
[rename on type] creates additional tag

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#94047]
Testing https://github.com/microsoft/vscode/issues/93808

Since the / tag is not highlighted, I didn't expect it to be part of the rename on type, but still thought I could delete the / and type it back again, was not expecting this:

![Kapture 2020-03-31 at 15 30 49](https://user-images.githubusercontent.com/9721254/78067960-a11aca00-7365-11ea-9a73-5d8f078e2f49.gif)

**Comment by aeschli** [comment]
Fixed by 362e49228c8ba5ae1d267f2789a474129e8c37ca
