### ISSUE TITLE
Quickopen match highlighting

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#94046]
Testing #93647

Now the `s` in `src` is highlighted, instead of using the `s` in `simple`

Stable
![image](https://user-images.githubusercontent.com/323878/78067348-2ef1b780-735c-11ea-8482-59ceddda2b87.png)

Insiders
![image](https://user-images.githubusercontent.com/323878/78067359-387b1f80-735c-11ea-814a-0268f01b27f5.png)

**Comment by bpasero** [comment]
Yeah good catch, I was not applying the same fuzzy matching when using multiple inputs. Now separating words with space will treat each word as an individual query that will match in the most optimal way on label and/or description.
