### ISSUE TITLE
Add new theme color for drag feedback indicator lines

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94041]
Refs: #93786

I would like to see 2 new theme colors -- 1 for the activity bar / panel header and one for the intra-sidebar/panel.

For example, I would want to be able to theme the white line here to be a lighter/brighter purple.
![image](https://user-images.githubusercontent.com/641685/78066276-9dd20f00-7362-11ea-9606-8a06cd0379ea.png)

And possibly a different color/brightness here as there is no background color in addition to the indicator.
![image](https://user-images.githubusercontent.com/641685/78066856-b4c53100-7363-11ea-84f8-eb7558bcf67e.png)

**Comment by sbatten** [comment]
@eamodio added 2 keys for the dnd in activity bar and panel titles. do you think we still need the keys for dnd border with views? that only shows up in the collapsed view and is using the active contrast border key to be themed. I'm always in favor of less keys if possible.

**Comment by eamodio** [comment]
@sbatten I think the border I was thinking about would be visible all the time (on the left) -- just like the top border color in the side bar. Could we just re-use that top border color?

**Comment by sbatten** [comment]
That would mean you would see 2 borders of the same color, yes?
