### ISSUE TITLE
Resizing terminal only resizes the active terminal instance

### ISSUE THREAD

**Issue by ahammar** [Microsoft/vscode#9405]
- VSCode Version: 1.3.1
- OS Version: Arch Linux 64-bit (kernel: 4.6.2-1)

Steps to Reproduce:

1. Switch to another terminal
2. Resize the terminal
3. Switch back
4. The first terminal is still the old size. You have to resize it again to make it update.

![terminal-resize-issue](https://cloud.githubusercontent.com/assets/88159/16900599/d1833262-4c28-11e6-8a73-21b2869e8cf0.gif)

**Comment by dehghani-mehdi** [comment]
Actually this was my fav. feature xD
