### ISSUE TITLE
Debug, UI/UX: Restarting a session in compound debugging expands other session call stacks too

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#94051]
Testing https://github.com/microsoft/vscode/issues/93297

1) Load some stack frames from multiple sessions S1, S2
2) Collapse the stack of one session, S1
3) Restart the session with expanded call stack view, S2
4) Notice the collapsed view of S1 is also shown

![ezgif com-optimize](https://user-images.githubusercontent.com/964386/78070068-06fc5700-7350-11ea-9f22-3360ef04761b.gif)

**Comment by isidorn** [comment]
Good catch. Agree this is not ideal, we should preserve expansion state explicitly set by user.
Assigning to April to investigate into a fix.

**Comment by isidorn** [comment]
Pushed a fix for this. Try it out with VS Code insiders from Wednesday and let me know how it goes. Thanks!
