### ISSUE TITLE
Decouple account management from settings sync

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#94050]
Testing #93811

By playing around with the new account management feature I logged in to two Microsoft accounts and a Github account:
![image](https://user-images.githubusercontent.com/6461412/78069018-b27dc980-7399-11ea-8a66-ba95241a93d9.png)

This looks really cool! So the idea is that this becomes a centralized place for managing the accounts I'm signed-in, correct? '

Settings sync would just one client of this, using one of the accounts. However, currently, settings sync seems to be more than just a regular client
- it pops up automatically when I logged in to a new account and ask to start settings sync. It shouldn't do that, maybe I just add an account for some other purpose.
- when I stop settings sync, it logs out from the account. It should prompt me before doing that. Maybe I want stay logged in for another feature.
- when turning on settings sync, it only proposes one of the accounts I've been logged in
![image](https://user-images.githubusercontent.com/6461412/78067826-a8f36200-7397-11ea-898b-9a8998d58441.png)
I would expect to also see my other account there. 'Use another account' brings me to a Microsoft web page like when creating a new account.

Feel free to close the issue if I misinterpreted the feature.

**Comment by sandy081** [comment]
/duplicate 

#94766
