### ISSUE TITLE
Writing login information to the keychain failed with error 'An invalid record was encountered.'.

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94056]
testing https://github.com/microsoft/vscode/issues/93811

```
Version: 1.44.0-insider
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:22:34.682Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
```

I signed into two accounts (cdias @ microsoft.com and chris @ diasfam.com), and then signed out of the microsoft.com account. The result:

![image](https://user-images.githubusercontent.com/1487073/78072845-a885a780-7354-11ea-9a13-fba9f44bb082.png)

**Comment by jthegedus** [comment]
I'm getting this error on Ubuntu 20.04 with my GitHub sign-in. I've only used the single account on this machine, so no idea why this started occurring.

**Comment by akshay-sf** [comment]
Using Ubuntu 20.04 with the latest VS code build. Although the error is slightly different.
![image](https://user-images.githubusercontent.com/53859456/95304283-02d26880-08a2-11eb-90a2-9e4391004a5d.png)

**Comment by davorpa** [comment]
Hi

I'm in the same situation

Any help will be apreciated

King regards

**Comment by EduardoSaverin** [comment]
@davorpa 
Try 
`sudo apt install gnome-keyring`

**Comment by davorpa** [comment]
@EduardoSaverin it's already installed. I have Ubuntu 20.04.1 LTS

**Comment by davorpa** [comment]
I **UPDATE**...

Magically solved for me. The way... first I login into official addon Github Pull Request and after enable sync for Github

**Comment by TylerLeonhardt** [comment]
I think the best we can do here is just add some retry logic as I've seen this every once and a while and reloading the window seems to work.

**Comment by TylerLeonhardt** [comment]
verification steps:

Turn on settings sync and log in with your Microsoft account... then log out... then log in... then log out... (repeat until you don't wanna do it anymore).

You shouldn't see the error above.
