### ISSUE TITLE
"statusBar/windowIndicator" and "menuBar/webNavigation" not included in intellisense

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#94054]
Testing https://github.com/microsoft/vscode/issues/93635

1. In an extension's `package.json`, start writing under "menus" in the contribution section. The new menu contribution points are not suggested:
![Screen Shot 2020-03-31 at 1 30 36 PM](https://user-images.githubusercontent.com/3672607/78072526-21383400-7354-11ea-823b-3135655bde94.png)

**Comment by bpasero** [comment]
I think this is intentional since those menus are proposed API.

**Comment by bpasero** [comment]
I added the entry for the web menu.

There seems to be more missing, also in SCM. Adding @joaomoreno 

Needs to be added to: https://github.com/microsoft/vscode/blob/8084a58504f23b60654d4e9381821bc57660c9b2/src/vs/workbench/api/common/menusExtensionPoint.ts#L124

**Comment by bpasero** [comment]
@aeschli is anyone using the "File" top level menu contribution point after all?

**Comment by aeschli** [comment]
@bpasero We removed the remote usage, so it's not used (to my knowledge)

**Comment by bpasero** [comment]
Ok then maybe we should remove it entirely.

**Comment by aeschli** [comment]
Remove the menuBar/file entry.
