### ISSUE TITLE
Auto Save is not working in notebooks

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#94052]
Testing #93742

* enable auto-save (File > Auto Save)
* type in a code cell
* observe dirty indicator which disappears only when saving with Ctrl+S

![image](https://user-images.githubusercontent.com/5047891/78071272-806e6680-739d-11ea-9db1-60ede34abcd1.png)

**Comment by bpasero** [comment]
@rebornix you will get this for free once Notebooks register as working copy via `IWorkingCopyService`. I am actually surprised how notebooks are not registering already, how do you deal with e.g. hot-exit so far?

**Comment by rebornix** [comment]
@bpasero we didn't do hot exit yet. We will hook it up in April, thanks for the pointer.

**Comment by bpasero** [comment]
@rebornix actually disregard my suggestion to register a working copy, as it seems to me a notebook is always backed by a single text file, is that true?

If so, then you should just resolve the text model (e.g. via text model resolver service and the `file` URI) and work on that. This model will register itself automatically as working copy and will:
* auto save (if enabled)
* backup (on shutdown)

**Comment by jrieken** [comment]
> ... it seems to me a notebook is always backed by a single text file, is that true?

We don't know that yet. As of today that's up to extensions to decide

**Comment by bpasero** [comment]
@jrieken then it seems you will have to do what custom editors are doing depending on the implementation:
* backed by text document: custom editor does NOT register a working copy
* not backed by text document: custom editor registers a working copy

The working copy service does not allow to register multiple working copies with the same exact resource btw because e.g. backups are associated with exactly one resource that needs to be unique.

**Comment by rebornix** [comment]
IMHO the notebook is close to Custom Editor. The GitHub issues notebook can be text document based but we are not sure yet if it's valid for Jupyter notebook and other potential notebook use cases. We can discuss this in April's API meeting.

**Comment by rebornix** [comment]
Test verify this issue, install the GH issues notebook extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks
