### ISSUE TITLE
Cannot drag scrollbar

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#94055]
Testing #93742

* click on the scrollbar
* try to scroll by dragging the scrollbar
* observe that over issue results the scrollbar cannot be dragged

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78072637-bf9db700-739f-11ea-9a4d-88a3b2e21fa6.gif)

**Comment by rebornix** [comment]
When the focus goes into the webview, the scrollbar no longer receives mouse move/drag events. We should probably emit mouse move (with mouse button pressed) from the webview and send them to the scrollbar.

**Comment by alexdima** [comment]
@rebornix An alternative would be for the scrollbar to emit some kind of event that it is currently dragging and then you can render a transparent `<div>` that captures mouse moves from the entire page.

In fact, I wonder if this isn't a bug already when dragging from an editor's scrollbar and moving the mouse over a webview?

**Comment by rebornix** [comment]
Yes, it’s a generic issue for webview and your solution should work for all webviews.
