### ISSUE TITLE
Preferences Sync in Settings editor

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94058]
testing https://github.com/microsoft/vscode/issues/93811

```
Version: 1.44.0-insider
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:22:34.682Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
```
I opened Settings and saw the option to `Turn on Preferences Sync`:

![image](https://user-images.githubusercontent.com/1487073/78073172-3a8db000-7355-11ea-83c4-35a7a7464073.png)

I'm in Settings, but it says "Preferences".  While I understand the more encompassing "Preferences", it seems weird that in settings it says preferences.  I think it would be OK to say here "Turn on Settings Sync" even though its more than just settings.  

Or, if possible, only sync settings when turning it on here, meaning only the `Settings` would be selected:

![image](https://user-images.githubusercontent.com/1487073/78073504-e20ae280-7355-11ea-80ce-21e317c96add.png)

**Comment by rebornix** [comment]
oops, my mistake.

**Comment by roblourens** [comment]
Preferences Sync is basically just the name of the feature not from what I understand. I will roll this into the continuing button/icon discussion in https://github.com/microsoft/vscode/issues/91601
