### ISSUE TITLE
"No authentication providers registered" message

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94053]
testing https://github.com/microsoft/vscode/issues/93811

```
Version: 1.44.0-insider
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:22:34.682Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
```

Start VS Code
As soon as you can, click on the Accounts icon in lower left corner.

Result: Get a `No authentication providers registered` message.

![image](https://user-images.githubusercontent.com/1487073/78072034-4a0bf980-7353-11ea-8c9a-a39e38fff955.png)

Clicking on it again, a few seconds later, I get `Sign in to Microsoft` so it is a timing problem.

Regardless, the message isn't friendly, not sure why we can't by default say something like `Sign in to Microsoft`.

**Comment by RMacfarlane** [comment]
The Microsoft authentication provider is an extension that takes some time to activate, when it does I add the "Sign in" context menu option. Until then you aren't able to sign in. I based this message on the "No source control providers registered" message show in the SCM viewlet while git loads.

Let me know if there's text you think would be clearer here

**Comment by chrisdias** [comment]
Ya, for the average person the "No source control providers registered" is hard to understand too :).

I would just default to "Sign in...". It's neutral and accurate.  If it expands to "Sign in with GitHub" or something else after a provider registers itself, that would just make it more accurate.

**Comment by RMacfarlane** [comment]
How about something like, "Loading..."? The reason I don't want to change it to "Sign in..." is that clicking it at this stage will do nothing. I could also just hide the icon from the activity bar until the command is available

**Comment by chrisdias** [comment]
"Loading..." seems fine then if nothing will happen when clicking on it.
