### ISSUE TITLE
NPM scripts: insert local node module bin folder into path

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94067]
Issue Type: <b>Feature Request</b>

With https://github.com/microsoft/vscode/issues/46696, extensions are able to modify environment variables for the integrated terminal. I'd love to have `node_modules/.bin` folder from current workspace temporarily in `PATH` when I'm using the terminal. It can be a feature of NPM Scripts extension.

```typescript
const collection = vscode.window.getEnvironmentVariableCollection();
const workspaceFolders = vscode.workspace.workspaceFolders;

if (workspaceFolders?.length) {
    collection.append('PATH', ':' + path.join(workspaceFolders[0].uri.fsPath, 'node_modules/.bin'));
}
```

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.2.0

**Comment by DetachHead** [comment]
it's insane that vscode doesn't do this by default and that this issue only has 2 upvotes. however i found out you can add relative paths to your `PATH` on both windows and linux:

```bash
PATH="./node_modules/.bin:$PATH"
```

**Comment by 1oglop1** [comment]
@alexr00 how is this out of scope? this is one of the reasons I am avoiding VSCode

**Comment by DetachHead** [comment]
a better workaround if you don't want to have to change your path globally or want to commit your workspace config, you can add this to your `.vscode/settings.json`:
```json
{
  "terminal.integrated.env.windows": {
    "PATH": "./node_modules/.bin;${env:PATH}"
  },
  "terminal.integrated.env.osx": {
    "PATH": "./node_modules/.bin;${env:PATH}"
  },
  "terminal.integrated.env.linux": {
    "PATH": "./node_modules/.bin;${env:PATH}"
  },
}
```

it seems obvious to me that vscode should just do this by default. webstorm does it

**Comment by hheimerd** [comment]
@DetachHead you need to replace ';' with ':'
>     "PATH": "./node_modules/.bin;${env:PATH}"
Also you can use `${workspaceFolder}` for to be sure, that you actually using workspaceFolder
```
{
  "terminal.integrated.env.windows": {
    "PATH": "${env:PATH}:${workspaceFolder}/node_modules/.bin"
  },
  "terminal.integrated.env.osx": {
    "PATH": "${env:PATH}:${workspaceFolder}/node_modules/.bin"
  },
  "terminal.integrated.env.linux": {
    "PATH": "${env:PATH}:${workspaceFolder}/node_modules/.bin"
  },
}
```

**Comment by DetachHead** [comment]
`PATH` is separated by `;` on windows. i didn't realize it's different on linux/macos
```json
{
  "terminal.integrated.env.windows": {
    "PATH": "${env:PATH};${workspaceFolder}/node_modules/.bin"
  },
  "terminal.integrated.env.osx": {
    "PATH": "${env:PATH}:${workspaceFolder}/node_modules/.bin"
  },
  "terminal.integrated.env.linux": {
    "PATH": "${env:PATH}:${workspaceFolder}/node_modules/.bin"
  },
}
```
