### ISSUE TITLE
getEnvironmentVariableCollection: not working when reloading the workspace

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94065]
Re #93601
I was running an extension with below simple setup, which modifies `PATH` when activated. The activation event for this extension is `*`.

```typescript
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
	const collection = vscode.window.getEnvironmentVariableCollection();
	const workspaceFolders = vscode.workspace.workspaceFolders;

	if (workspaceFolders?.length) {
		collection.append('PATH', ':' + path.join(workspaceFolders[0].uri.fsPath, 'node_modules/.bin'));
	}
}
```

For newly created Terminal, it works fine. If I create a terminal and then reload the workspace, the terminal will break restored but `PATH` is then not modified.

**Comment by rebornix** [comment]
Extensions can use `getEnvironmentVariableCollection(true)` to make sure when the window reloads, the environment variable is already there but it doesn't work if the extension wants to calculate the variable after its' activated, in which case it doesn't want any caching at all.

**Comment by Tyriar** [comment]
> Extensions can use getEnvironmentVariableCollection(true) to make sure when the window reloads, the environment variable is already there but it doesn't work if the extension wants to calculate the variable after its' activated, in which case it doesn't want any caching at all.

This is by design, using persistent=true will cache everything between reloads so that terminals aren't blocked by ext host and extension activation. An extension should want to reassess/reassign everything when it activates, if the collection is the same then when we do the UX side of this no indicator will pop up saying it's stale.
