### ISSUE TITLE
Not able to update PATH on windows using EnvironmentVariableCollection

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#94069]
Refs #93601

**Repro**
Try using `EnvironmentVariableCollection` to update the `PATH` on windows.

```ts
import * as vscode from 'vscode';

const key = 'PATH';

export function activate(context: vscode.ExtensionContext) {
    const collection = vscode.window.getEnvironmentVariableCollection(true);
    collection.append(key, ';some/other/_______fancy_______/path');
}
```

1. Run the extension
1. Open a new PowerShell terminal and run `$Env.PATH`

**Bug**
See the standard path printed, not the modified path

**Comment by Tyriar** [comment]
Nice find, didn't consider Window's case sensitivity, using `Path` works around it currently.
