### ISSUE TITLE
Unable to identify file in project hence not open it with relative path

### ISSUE THREAD

**Issue by qizhiyu** [microsoft/vscode#94068]
Issue Type: <b>Bug</b>

OS: windows 10
1. open a folder with git enabled
2. open and make change to one file, abc.tsx , notice the breadcomb is like 'src > abc.tsx > class'
3. click 'Source Control' on left tool bar
4. click 'Open file' next to the changed file abc.tsx

Expected: VS Code switches to the existing editor window of abc.tsx
Issue: Instead, VS Code opens another window with "D: > Code > abc.tsx ..." as breadcomb.

reopen filestwo windows of same file with absolute path and relative path respectively

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.82GB (21.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
vscode-jest-runner|fir|0.4.15
vscode-react-typescript|inf|1.3.1
import-sorter|mik|3.3.1
vscode-azureappservice|ms-|0.16.4
csharp|ms-|1.21.16
azure-account|ms-|0.8.8
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
autolaunch|phi|2.0.3
code-spell-checker-fullstack|rba|0.0.8
mob-timer|son|1.5.1
code-spell-checker|str|1.8.0
quokka-vscode|Wal|1.0.285
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by joaomoreno** [comment]
I can't reproduce. Are you in a network share? Do you have symbolic links?

Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by qizhiyu** [comment]
![4b7cd4f8-1969-4dd1-bdd5-a19aa30dd41a](https://user-images.githubusercontent.com/2202171/78180967-0be01880-74c0-11ea-8396-957db06b0519.gif)

I also tried with Insiders - 1.44.0 which has no such issue
![image](https://user-images.githubusercontent.com/2202171/78181058-3a5df380-74c0-11ea-9136-e132a6aa3a00.png)
