### ISSUE TITLE
User snippet not synced

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94072]
Re #93771

* Running Insiders with two different user-data-dir
* Configure User Snippet in the first Insiders, choose language JavaScript, uncomment the template
* Go to the second the Insiders, choose JavaScript, uncomment the template and also make some changes to it

Both Insiders said they are just synced but I didn't see them being merged or updated or conflicted.

**Comment by sandy081** [comment]
Can you please provide sync logs? It could be because of the complaint you made in #93771 that sync is not happening at all?

**Comment by rebornix** [comment]
False alarm.
