### ISSUE TITLE
Suggest: Indicate which account is syncing

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94076]
testing https://github.com/microsoft/vscode/issues/93811

When I'm signed into multiple accounts and click on the user icon, I can see the accounts but I don't know which one I am signed into for syncing.  I see this:

![image](https://user-images.githubusercontent.com/1487073/78081071-7e3be600-7364-11ea-8935-6d7dd635b753.png)

It would be more clear with something like this to know what I'm syncing with:

![image](https://user-images.githubusercontent.com/1487073/78081157-bd6a3700-7364-11ea-8f8c-cd81a2df8059.png)

**Comment by chrisdias** [comment]
and ideally if i am signed in but not syncing, i would like to know that...

**Comment by sana-ajani** [comment]
Or highlighting the currently signed in account.

**Comment by chrisdias** [comment]
hmmm @sana-ajani your comment raises a good point i think. all of the accounts are signed in, and the customer may be doing different things with each account (e.g. sync'ing on one, using gh PRs on another). So, saying that one of the accounts is syncing may not be right.  Maybe the answer is on the gear menu to show what account is syncing.  for example, "Sync is on (cdias@microsoft.com)"

**Comment by RMacfarlane** [comment]
This is covered with https://github.com/microsoft/vscode/issues/94635: there's now an menu item to view what extensions and features are using an account
