### ISSUE TITLE
Simplify the sync notification

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94079]
testing: https://github.com/microsoft/vscode/issues/93811

The message "Sync will happen automatically from now on" is a bit repetitive, especially the last part "from now on". That's the point of sync :).  

![image](https://user-images.githubusercontent.com/1487073/78082375-bbee3e00-7367-11ea-9c41-aac8b8a5bd35.png)

If we need a confirmation notification, it could simply say "Synchronization is turned on".

**Comment by sandy081** [comment]
No hard feelings.. changed to `Preferences sync is turned on`. 

Can change again if needed improvements.
