### ISSUE TITLE
Replace Box in Current File Truncated

### ISSUE THREAD

**Issue by deerawan** [Microsoft/vscode#9407]
- VSCode Version: 1.3.1
- OS Version: MacOS El Capitan 10.1

Steps to Reproduce:
1. Using default resolution 1440 x 900
2. Activate 3 split view / 3 groups
3. Show the sidebar
4. cmd + option + F to show replace dialog

Actual: dialog box truncated, hard to type text to be replaced

![image](https://cloud.githubusercontent.com/assets/1243921/16900657/4203c192-4c55-11e6-9256-0bf9cc29e419.png)

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/5861
