### ISSUE TITLE
Multiple prompts to "Turn on" syncing

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94078]
testing https://github.com/microsoft/vscode/issues/93811

I'm prompted 2x to sync when I force a sign on through the gear menu.

1. Make sure you are signed out
2. On gear menu, click on "Turn on Preferences Sync"
3. Get the following list that says "Sign in & Turn on"

![image](https://user-images.githubusercontent.com/1487073/78081983-c4924480-7366-11ea-9d0d-07ee12165c4b.png)

4. Click on "Sign in & Turn on"
5. Sign in to an account
6. Back in VS Code Im now presented with another confirmation dialog

![image](https://user-images.githubusercontent.com/1487073/78082017-dd9af580-7366-11ea-89ca-6dd0c5e76426.png)

7. Click on "Turn on"

8 Now, if I sign in with a different account from the last time I signed in, I get this dialog (even though I have signed in with this account before):

![image](https://user-images.githubusercontent.com/1487073/78082263-63b73c00-7367-11ea-80d4-f9a19245aa64.png)

9. Choose "Replace Local", now I'm back to the "Turn on" list

![image](https://user-images.githubusercontent.com/1487073/78082126-1c30b000-7367-11ea-8040-27749a4eaf0a.png)

In this flow, I had to click on "Turn on" at least 3 times, if you don't include the gear menu click.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/93805
