### ISSUE TITLE
Upgrade chromium to version 80 to support 30-bit color depth on Linux

### ISSUE THREAD

**Issue by luglio** [microsoft/vscode#94074]
Hello,

Chromium 78 in the 1.43.2 stable version fails to correctly render in a 30-bit color depth Linux desktop environment. The output is [like this](https://community.brave.com/t/wrong-color-rendering-on-30-bit-displays-on-linux-possibly-on-other-platforms/50266). VSCode is similarly affected. I'm not sure if a previous version worked but it seems the latest stable chromium now works well.

I tried a local compilation based on the 1.43.2 release, replacing the chromium and the electron to their latest stable versions. That solved the above problem on my PC (Manjaro, KDE).

I believe there's a growing need for such scenario so I wish it's considered in the near future.

Thanks

**Comment by deepak1556** [comment]
Our exploration builds are based on chromium 80, you can give it try. There is no timeline yet for when we are going to push for stable.

Download:
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/2766badcb6c29445f5289033f1343f373802315c/code-exploration_1.44.0-1585360228_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/2766badcb6c29445f5289033f1343f373802315c/code-exploration-1.44.0-1585360385.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/2766badcb6c29445f5289033f1343f373802315c/code-exploration-1585360520.tar.gz)

**Comment by charbelnicolas** [comment]
I just tried this on Arch Linux and the white menu flashes are gone! I hope this gets on the official stable release soon!

**Comment by luglio** [comment]
Happy and grateful to know the current insider build is working.

**Comment by deepak1556** [comment]
Fix will also be available in upcoming stable release.
