### ISSUE TITLE
Automatically stops executing node hapi.js project after 15 - 20 seconds. I have reinstalled VSCode several times. 

### ISSUE THREAD

**Issue by Aswin5010** [Microsoft/vscode#9408]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10240

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
@Aswin5010 I do not understand what you mean. Please provide detailed steps so that we can reproduce your problem.

**Comment by Aswin5010** [comment]
Really sorry its my code syntax error..!
