### ISSUE TITLE
Diff "context" not included in F7 diff mode

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94086]
ref #93301

With this diff, the reader wont give me the git "context" header of `export class FeatureRequestQueryer {`, even though it is included in the raw `git diff` output. 

```diff
@@ -14,10 +14,10 @@ export class FeatureRequestQueryer {
                private label: string,
                private reactionsRequired: number,
                private commentsOverride: number,
-               // private initComment: string,
-               // private warnComment: string,
+               private initComment: string,
+               private warnComment: string,
                private acceptComment: string,
-               // private rejectComment: string
+               private rejectComment: string
        ) { }
```

VSCode's rendering of the above diff:
![image](https://user-images.githubusercontent.com/8586769/78083640-eb527a00-736a-11ea-9976-e1eea2158a38.png)

macOS mojave voiceover

**Comment by isidorn** [comment]
This is simply how our diff algorithm works. Thus this would be a feature request against the diff algorthim to also include the context.
Thus also assigning to @alexdima 
For now assigning to Backlog.
