### ISSUE TITLE
Better read unchanged lines in F7 diff view

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94087]
ref #93301

With this diff, the reader will read

`private label: string original line 14 modified line 14`

it might be good to just notate that its unchanged?

`private label: string unchanged line 14`

```diff
@@ -14,10 +14,10 @@ export class FeatureRequestQueryer {
                private label: string,
                private reactionsRequired: number,
                private commentsOverride: number,
-               // private initComment: string,
-               // private warnComment: string,
+               private initComment: string,
+               private warnComment: string,
                private acceptComment: string,
-               // private rejectComment: string
+               private rejectComment: string
        ) { }
```

VSCode's rendering of the above diff:
![image](https://user-images.githubusercontent.com/8586769/78083640-eb527a00-736a-11ea-9976-e1eea2158a38.png)

macOS mojave voiceover

**Comment by isidorn** [comment]
@JacksonKearl makes sense. Agree with you. Assigning to April to look into polishing this then.

**Comment by jvesouza** [comment]
I will probably write a lot of nonsense, but since the lines are shown preceded by a - / +, wouldn't it be enough to just announce the line number?
I may be contaminated by the fact that I almost always used git in text mode.

**Comment by isidorn** [comment]
@jveszoua I believe that just announcing the line number would be far too concise and not enough for most users.

**Comment by MarcoZehe** [comment]
Agreed, many synthesizers may read the + sign, but not the - sign because it is also used as a dash. Granted, at some point all punctuation might be spoken by some users, but that is not always unambiguous. So speaking whether this is a deleted line or so is very important.
