### ISSUE TITLE
Better count changed lines in changes view with screen reader

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94085]
ref #93301

With this diff, the reader will tell me "10 lines changed", when really only 3 have. It seems to be including the unchanged lines in the diff hunk when counting the changed lines, which seems confusing.

```diff
@@ -14,10 +14,10 @@ export class FeatureRequestQueryer {
                private label: string,
                private reactionsRequired: number,
                private commentsOverride: number,
-               // private initComment: string,
-               // private warnComment: string,
+               private initComment: string,
+               private warnComment: string,
                private acceptComment: string,
-               // private rejectComment: string
+               private rejectComment: string
        ) { }
```

VSCode's rendering of the above diff:
![image](https://user-images.githubusercontent.com/8586769/78083640-eb527a00-736a-11ea-9976-e1eea2158a38.png)

macOS mojave voiceover

**Comment by isidorn** [comment]
Good feedback, however I think that is just how our diff computation algortihm works. And I think git would so something similar.
Also assigning to @alexdima to get his feedback on the matter.

**Comment by alexdima** [comment]
Well, that is what the number 10 in `@@ -14,10 +14,10 @@` stands for... That this is a diff chunk of length 10 lines in the old file content and of length 10 lines in the new file content... It could be that 1 or more lines in this chunk has been changed or deleted, or inserted, etc... but that is kind of the chunk length.

@isidorn The diff algorithm does not return 3 lines above and 3 lines below. The diff algorithm returns just the minimal diff. The padding is added [here](https://github.com/microsoft/vscode/blob/1deda3c776b3ce06e5c9099bf4b0a4283474d5eb/src/vs/editor/browser/widget/diffReview.ts#L397-L398), in the `diffReview.ts` which is built on top of the diff algorithm results. Perhaps we can change the message from "10 lines changed" to "diff chunk 10 lines long", I don't know...

**Comment by isidorn** [comment]
We can always tune the message. Assiging to April to look into if more can be done here.
