### ISSUE TITLE
Headers aren't aligned when split horizontally and collapsed

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode#94080]
Issue Type: <b>Bug</b>

#93787

1. Drag views into a single panel so that they are split horizontally
1. Collapse the headers

Expected: the headers are equal in height and position
Actual: the headers are sometimes equal in height and offset in vertical position

![headers](https://user-images.githubusercontent.com/1186948/78082435-dd4f2a00-7367-11ea-9f56-e404131a0e97.gif)

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:23:56.446Z)
OS version: Windows_NT x64 10.0.19587
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (6.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|12.17GB (11.71GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.16.4
vscode-azurefunctions|ms-|0.21.0
vscode-cosmosdb|ms-|0.12.2
azure-account|ms-|0.8.8
vsliveshare|ms-|1.0.1891
vscode-docker|ms-|1.0.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
yea this isn't great, the collapsing experience should be better in the panel, but i don't have an immediate solution.

**Comment by sbatten** [comment]
I think I misunderstood the issue you were reporting originally. I now see that Problems is slightly lower than Registries header. Can you try to repro today? There was some work done and it may have resolved the issue?

**Comment by fiveisprime** [comment]
Yep, this appears to be fixed.

**Comment by sbatten** [comment]
adding label as per @fiveisprime
