### ISSUE TITLE
Sync was turned off from another device prompt (when it wasn't)

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94083]
testing https://github.com/microsoft/vscode/issues/93811

When signing out of an account that is currently being used to sync settings, I get this dialog:

![image](https://user-images.githubusercontent.com/1487073/78082575-420a8480-7368-11ea-8a69-e11193ee88ef.png)

If I let this dialog sit open for a minute or two without clicking on either button, I get this notification:

![image](https://user-images.githubusercontent.com/1487073/78082648-65353400-7368-11ea-9e02-f649a598ece1.png)

I didn't turn off sync from another device, and if I did wouldn't that mean I chose the "Turn off sync on all devices and clear the data from the cloud" option?  Or, is there some way for me to turn off syncing on another device?

**Comment by sandy081** [comment]
> Or, is there some way for me to turn off syncing on another device?

There is not. Will investigate what's happening here.

**Comment by sandy081** [comment]
Trying on latest insiders I see same dialog on both instances

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/10746682/78179823-1e2b6980-7462-11ea-86ee-12834f81c5fe.png">

@RMacfarlane This dialog should not appear if user does not sign out manually.

**Comment by RMacfarlane** [comment]
There's another issue tracking the "turn off sync" dialog being shown here: https://github.com/microsoft/vscode/issues/94174

For the "Sync was turned off from another device" message, it looks like auto sync is stopped because there is no longer an auth token. @sandy081 should we distinguish this case and show a different notification?

**Comment by RMacfarlane** [comment]
Now, when you sign out of the account used for settings sync, a notification should be shown that settings sync has stopped.
