### ISSUE TITLE
Notebook: Missing command palette commands

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94098]
- new cell
- delete cell
- move cell up/down
- run cell
- switch rendered mime type for cell

**Comment by rebornix** [comment]
This can be done be adding `f1` to each action definition but we need to make sure that they all work fine when invoked from command palette.

**Comment by roblourens** [comment]
Did this for all except changing the output type, this isn't an action and should be refactored.

**Comment by roblourens** [comment]
Actually I don't think we can really do it for that because there are multiple outputs with different types and there is no concept of a "current output".
