### ISSUE TITLE
cannot reference $returnValue in logpoint

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94094]
testing https://github.com/microsoft/vscode/issues/93807

Not sure if this should work or not, but what the heck I'll give it a try!

![image](https://user-images.githubusercontent.com/1487073/78088377-d67ce300-7378-11ea-81da-f3962409510f.png)

In the debug console, I get this:

```
this is the ReferenceError: $returnValue is not defined
    at eval (logpoint-bce3f6f.cdp:3:5)
    at eval (logpoint-bce3f6f.cdp:7:3)
    at helloWorld (/Users/chris/src/test93807/index.js:6:16)
    at Object.<anonymous> (/Users/chris/src/test93807/index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by isidorn** [comment]
Living loco @chrisdias 
Though forwarding to @connor4312 since he is the author of that test plan item

**Comment by connor4312** [comment]
Thanks for the issue! Unfortunately this won't work because the $returnValue is only available after stepping over the return statement, but breakpoints can't be set there.

**Comment by kieferrm** [comment]
@connor4312 In  the following code
```js
function foo() {
    const val = [];
    for (let i = 0; i < 20; i++) {
        val.push(bar(i));      
    }
    return val;
}
 
function bar(i) {
    return {
        code: i,
        message: `msg ${i}`
    };
}
 
foo();
```
I can set a breakpoint on line 13. When this one is hit `$returnValue` is defined. However logpoints  referencing `$returnValue` fail and conditional breakpoints  referencing `$returnValue` are never hit. When are those conditions being evaluated? In this case I'd guess after the return value was evaluated.

**Comment by connor4312** [comment]
Ah, okay. I'll check on this.

**Comment by connor4312** [comment]
Fixed in the linked commit. Note that, as mentioned, you need to make sure the logpoint is set _after_ the `return` statement, since before it's evaluated the call frame's return value is not set. If compiling to js, the sourcemaps might already be set up like this.

![](https://memes.peet.io/img/20-05-5a4e62b8-3522-4633-8c17-38d2a602bc8f.png)
