### ISSUE TITLE
vscode not showing proper file icons on mac

### ISSUE THREAD

**Issue by rdt003** [microsoft/vscode#94093]
Python files are showing the proper icon, but other file types are showing the generic vscode icon.
All the files should be showing the proper icons as of version 1.28:
https://code.visualstudio.com/updates/v1_28

I checked my plist file and all the file extensions are set to the proper icns file, so idk why my files aren't showing the proper icons.

<img width="631" alt="Screen Shot 2020-03-31 at 5 49 50 PM" src="https://user-images.githubusercontent.com/34991529/78088093-0677b680-7378-11ea-99d0-1c49ebf6b6d0.png">

- VSCode Version:  1.43.2
- OS Version:  10.15.4

Steps to Reproduce:

1. Download vscode
2. View file extensions in finder, or anywhere else

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Seems like an issue of macOS. I would reach out in StackOverflow for an answer.
