### ISSUE TITLE
Notebook: Alt+Enter should not execute the cell

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94095]
1) create a new gh issues nb
2) enter text in first cell
3) Alt+Enter to add a new cell below
-> cell 1 runs but shouldn't

**Comment by roblourens** [comment]
This is bound to "execute and insert below". We don't have a keybinding to just insert currently. I think we are running low on combinations of modifiers + enter.

**Comment by roblourens** [comment]
Maybe I should add a default keybinding for a command to insert a cell below but I don't know if it should be for a code cell, or, the same type as the current cell, or the opposite type, or what.

**Comment by roblourens** [comment]
Added a keybinding for insert code cell above/below (and added some other keybindings from your list)
