### ISSUE TITLE
Timeline: exclude sources

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94106]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/93819.

There are several issues with the setting:
```
"timeline.excludeSources": [
        "git-history"
    ]
```

1) The name led me down a path to think that I can exclude folders in my workspace. 
2) How do I know which sources are available? 

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.0.0-1022-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (3.01GB free)|
|VM|0%|
</details>

**Comment by gregvanl** [comment]
Agree with 2. No IntelliSense to list available sources and no error if put in incorrect source name.

**Comment by eamodio** [comment]
I don't think there is any way to show intellisense here -- as the sources are dynamic, depends on runtime registrations by extensions.

Ideally users won't need to change the setting themselves, since the `Include: *` menu on the Timeline view sets it.

**Comment by eamodio** [comment]
@jrieken @sandy081 is there anyway to provide intellisense here?

**Comment by jrieken** [comment]
First: don't use arrays for these settings, always use object literals because they merge well. Not sure what the values is (extension ids?)... Anyways, this is how I dynamically compute the value set of the default-formatter enum: 

https://github.com/microsoft/vscode/blob/43bfc2cda0bf7e5f4d037d06e39754e878bc2a90/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L162

Simply keep a reference and the scheme-definition-object and update it later.

**Comment by JacksonKearl** [comment]
Considering removing config from settings in favor of storage service.

**Comment by roblourens** [comment]
How do I exclude a source, is there supposed to be a context menu item for it in the timeline? Also, were _all_ of the timeline settings supposed to be removed?

**Comment by lramos15** [comment]
> How do I exclude a source, is there supposed to be a context menu item for it in the timeline? Also, were _all_ of the timeline settings supposed to be removed?

No, I fixed that in a follow up PR after I noticed that in the code changes. Should be all there in the Settings UI.

To verify
1. Open a file
2. Open the timeline
3. Choose the filter icon to filter local history or git out of the timeline
4. Ensure they didn't update any settings and instead is persisted in storage
