### ISSUE TITLE
Suggestion: Clarify empty debug viewlet text

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94101]
testing: https://github.com/microsoft/vscode/issues/93806

The empty debug viewlet seems out of balance with the "Run and Debug" button at the top, centered, without any instructional text before it when there is a file open:

![image](https://user-images.githubusercontent.com/1487073/78088831-3f188f80-737a-11ea-8cc4-dc340579f304.png)

Compare this to when no file is open, where there is some introductory text above the "Run and Debug" button:

![image](https://user-images.githubusercontent.com/1487073/78088980-be0dc800-737a-11ea-9a4e-895b493e57f7.png)

The new text for the Node.js Debug Terminal, feels a bit like an advertisement ("...instantly debug JavaScript").  So, I suggest the following text and layout:

![image](https://user-images.githubusercontent.com/1487073/78089518-89027500-737c-11ea-905b-d2b44f650833.png)

**Comment by isidorn** [comment]
@chrisdias thanks for the feedback. The first part telling the users what the Run and Debug button do I am not a big fan of. Seems like noise and stating the obvious - I might be wrong but I would not change it now.
As for the Node.js Debug Terminal I am forwarding this to @connor4312 so he can decide

**Comment by chrisdias** [comment]
My kids' feedback suggests that the "Run and Debug" button isn't self-explanatory :).  

@misolori do you have any thoughts about the "balance" here?

**Comment by isidorn** [comment]
@chrisdias is everything clear to your kids after they read the new message :)
Also application is not applicable to all use cases, sometimes it is a script etc

**Comment by chrisdias** [comment]
@isidorn no, not yet. my first objective is to get you to add some text, then I can hack the text ;-)

**Comment by misolori** [comment]
I agree that the balance is off, though I get worried with these long texts on the empty viewlet. 

I do like the structure of instructions first and then showing the button actions.

**Comment by chrisdias** [comment]
agreed on too much text being less than helpful.

At the same time, I also noticed the first line of text in the empty explorer isn't super useful as compared to the button text.

![image](https://user-images.githubusercontent.com/1487073/78194606-7ea2b280-7432-11ea-8a4f-c65c6a3fc5bf.png)

going back to the balance thing, maybe having the button always be the width of the viewlet, or the text always being the width of the button would make it feel less out of balance.  

This feels better...
![image](https://user-images.githubusercontent.com/1487073/78194857-143e4200-7433-11ea-8d66-68009d0c7b6b.png)

than this...
![image](https://user-images.githubusercontent.com/1487073/78194883-1dc7aa00-7433-11ea-9776-6e96b27b5dc6.png)

**Comment by connor4312** [comment]
I tweaked the text for the Debug Terminal a bit ago. I think the remaining tweaks are in the layout/debug view itself, so reassigning.

**Comment by isidorn** [comment]
I can change the button to be the width of the viewlet, however than we can easily end up in this case as well
Apart from the width of the button I do not see any actionable items, or I am missing something @chrisdias ?

@misolori what do you think about button width?

![Screenshot 2020-11-09 at 16 18 17](https://user-images.githubusercontent.com/1926584/98559699-38a2ac80-22a7-11eb-9453-24013e6b55eb.png)

**Comment by misolori** [comment]
I've always felt like the max-width on buttons was odd so I'm in favor of removing it.

**Comment by isidorn** [comment]
Works for me.

**Comment by joaomoreno** [comment]
FYI: https://github.com/microsoft/vscode/issues/111744

**Comment by gjsjohnmurray** [comment]
Specifically, without a max-width on the buttons the welcome view of a viewlet that lives in the panel rather than the sidebar ends up with very wide buttons.

Maybe reintroduce max-width but also align the buttons left (or right if sidebar is on the right)?

**Comment by isidorn** [comment]
Yeah the current approach does not work for the panel. Once we have welcome views in the panel I would think about it. In the meantime if a user know how to drag views to panel then he probably is not having any welcome views, so I would not be too worried

**Comment by alexr00** [comment]
@isidorn, we have the ports view in the panel, and it has welcome views.

**Comment by alexr00** [comment]
And terminal does something with welcome views too.

**Comment by isidorn** [comment]
@alexr00 if the ports and terminal welcome view have these blue buttons then we should probably push some width capping via css.
