### ISSUE TITLE
Notebook: Clear active output does not work from command palette

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94102]
1) create a new gh issues nb
2) enter `repo:microsoft/vscode author:kieferrm`
2) run cell
3) clear output using the cell toolbar
-> nothing happens

(Command palette commands also don't have any affect but show an error notification.)

**Comment by rebornix** [comment]
/duplicate and already fixed in master, thanks!

**Comment by rebornix** [comment]
Reopen for the error notification from the command palette.

**Comment by rebornix** [comment]
The command is contributed by the extension so it only works when it's laid on the toolbar. To fix this issue properly (if we do want to show the command in the command palette), we need to expose `notebookEditor.activeCell` in the API.

**Comment by rebornix** [comment]
Fixed in master.
