### ISSUE TITLE
Problems with line/word wrapping

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#9410]
- VSCode Version: 1.4.0 insider
- OS Version: win10 build 14390

Steps to Reproduce:
![bug](https://cloud.githubusercontent.com/assets/7588612/16901119/44b5d8c8-4c6c-11e6-8d7d-451dfafc16de.gif)
1. inconsistent behaviors of indention
2. line numbers

my settings

```
"editor.wrappingColumn": 0,
"editor.wrappingIndent": "indent"
```

**Comment by alexandrudima** [comment]
This is something we might have fixed in the meantime, as this works as expected for me:

![9410](https://cloud.githubusercontent.com/assets/5047891/26586902/f75777f6-4550-11e7-8d6d-89b0c695499f.gif)
