### ISSUE TITLE
Timeline hover has empty line

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#94104]
- VSCode Version: 1.44 Insiders
- OS Version: Windows

Found while testing #93819

When you hover over a Timeline item, the hover displays an extra empty line between the timestamp and comment.  

![image](https://user-images.githubusercontent.com/12818376/78091257-2d86b600-7381-11ea-82d4-2e21cb00f16b.png)

Is this line filled in certain scenarios? It looks odd to have an empty line.

**Comment by gregvanl** [comment]
Looks like extra line per line break

![image](https://user-images.githubusercontent.com/12818376/78093124-58bfd400-7386-11ea-9726-a0f33b79a729.png)

**Comment by eamodio** [comment]
That is intentional -- I added a line break between the "meta-data" section and the commit message. And the commit message will render with any of its own line breaks.
