### ISSUE TITLE
Should Timeline Load More command have a hover?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#94110]
- VSCode Version: 1.44 Insiders
- OS Version: Windows

Found while testing #93819

While "Load more" is pretty self-explanatory, it would still be good to have a hover explaining what the command does in more detail.

**Comment by eamodio** [comment]
What do you think it should say? The GitHub PRs extension which uses this pattern, just says "Load more" when you hover.

**Comment by gregvanl** [comment]
How about "Load more timeline history"?

**Comment by eamodio** [comment]
Hrm, does that really provide any more value? Maybe for screen readers?

/cc @misolori

**Comment by misolori** [comment]
If we have something valuable to say like "Load XX more items", that would be nice to know how many it loads at a given time (if applicable).

**Comment by eamodio** [comment]
It's currently hard-coded to be 20, but that is somewhat approximate, as there are cases where it could be a less (and we don't know that until its loaded)

**Comment by misolori** [comment]
I think that's also why we don't show the number in the label on the GitHub extension. It does feel silly though to have the same text from the label in the title tooltip so I'd opt to make it more descriptive like @gregvanl suggests. We should also update this everywhere we show `load more` action labels.

**Comment by gregvanl** [comment]
How about "Display more timeline history" for the hover since that is what the user experience is.
"Load more" almost sounds like an implementation detail and feels "heavy" (like we're loading up the editor ;-) ).

**Comment by eamodio** [comment]
We are "loading" more -- it is a query that could take a while depending on the source.

**Comment by misolori** [comment]
I like how GitHub uses "Show More" instead:

![image](https://user-images.githubusercontent.com/35271042/78195116-c970fa00-7433-11ea-9c04-b2fa306bc8cd.png)

![image](https://user-images.githubusercontent.com/35271042/78195123-cd9d1780-7433-11ea-861d-5fcec86df9d2.png)

**Comment by eamodio** [comment]
😆 That's what I had originally and in GitLens -- but I changed it because everyone seemed to like `Load more` better (and its what we use in the GitHub PRs extension)

**Comment by eamodio** [comment]
I thought about having a bottom anchored link like that image, but it is a pattern we don't have currently, and I thought it might feel strange if there is a distance between the last item and the end of the list. And also if the last item isn't in view, do we hide it? Etc.

**Comment by eamodio** [comment]
Because it truly is a "load" and it can definitely take some time, I think `Load more` is more accurate than `Show more`

**Comment by eamodio** [comment]
I'm not convinced adding a tooltip here provides enough additional value -- if you feel strongly otherwise please feel free to re-open
