### ISSUE TITLE
Should Timelime Load More command have an icon?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#94111]
- VSCode Version: 1.44 Insiders
- OS Version: Windows

Found while testing #93819

It is a little hard to differentiate the Load More command from the history entries. Perhaps adding an icon to the entry would help users know it is a command. Maybe just a plus sign in front.

`+ Load More`

**Comment by eamodio** [comment]
I avoided adding an icon, because the timeline items themselves all have icons and I wanted to make this stand apart. Also the GitHub PRs and GitLens (soon) use this pattern with the same style.

/cc @misolori thoughts?

**Comment by misolori** [comment]
I'm not sure that an icon would help here, often times it adds more noise. I'd be in favor of not using one.
