### ISSUE TITLE
Code prediction fails in Windows for C++ even after using extensions

### ISSUE THREAD

**Issue by sgdgp** [Microsoft/vscode#9411]
- VSCode Version:1.3.1
- OS Version:Windows 10 build 10586

Steps to Reproduce:

1. I have included a bits directory inside the Microsoft Visual Studio official include directory. This bits directory is just a copy from the minGW source.
The purpose of the directory is that it contains the useful stdc++.h header file

2. But after doing so even though the editor shows no problem in including the files but it is not showing the functions of vectors or other data structures. There is no suggestion for code completion.

(I have clang installed so there is no issue because of clang) 

Also instead of using 'bits/stdc++.h' if I just use 'vector' the code prediction works fine.

Please look into it it's urgent.

**Comment by weinand** [comment]
@sgdgp please file against the C++ extension you are using.
