### ISSUE TITLE
TS: no error for passing undefined/null into objects.ts#assign

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94117]
This is causing exceptions when you pass `undefined` to [`assign`](https://github.com/microsoft/vscode/blob/1055a5330b9b524b571ed4daebbb7241cb9ea48d/src/vs/base/common/objects.ts#L116). 

Looking at the signature I would think it should show an error if you attempt to do so.

**Comment by mjbvz** [comment]
I think the error in in our typing, not with typescript. If you pass call `assign(undefined)`, TypeScript will infer `T = undefined`. Maybe our typings should have `T extends object` or a similar constraint?

Note that `Object.assign` has the same problem: https://github.com/microsoft/TypeScript/issues/35621

Assigning back to you @bpasero as I'm not sure who owns these object functions

**Comment by bpasero** [comment]
@mjbvz back to sender

![image](https://user-images.githubusercontent.com/900690/78110297-fb199f00-73fa-11ea-819a-094abc5bb965.png)

**Comment by mjbvz** [comment]
Pretty sure I just copied these from typescript.

Adding @jrieken since now that we have es6 support we should look moving to `Object.assign` instead

**Comment by jrieken** [comment]
@joaomoreno own that util and 'yes' with ES6 this isn't needed anymore

**Comment by joaomoreno** [comment]
We should not be using this at all now that we have ES6. It's just deprecated.

**Comment by jrieken** [comment]
@joaomoreno Understand this as a debt item to help people migrate away from it

**Comment by jrieken** [comment]
This now shows up in .vscode/searches/es6.code-search

**Comment by joaomoreno** [comment]
Thanks @jrieken.
