### ISSUE TITLE
TS: "Declare method" is really bad

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94118]
So many things wrong:

![image](https://user-images.githubusercontent.com/900690/78104405-75dcbd00-73ef-11ea-9543-2bddb9dabc2c.png)

* import uses a weird syntax
* I am not being asked for the visibility, it is just public by default
* `any` (!) is declared as return type??? I should be asked

**Comment by bpasero** [comment]
With this, it took me more keystrokes to fix the method compared to just writing it myself.

**Comment by mjbvz** [comment]
Please provide steps to reproduce this issue in the VS Code codebase so we can investigate

**Comment by bpasero** [comment]
@mjbvz in `commandsQuickAccess#CommandsHistory' add `this._register(this.storageService.onDidChangeStorage(e => this.onDidChangeState(e)));` into the `registerListeners`

**Comment by mjbvz** [comment]
Thanks. 

Point 1 is definitely a bug. I'll create a priority issues on TS for this

Point 2 is https://github.com/microsoft/TypeScript/issues/36249 but for declare method. I'll open a separate issue for that

For point 3, TS should try to infer the return type based on context. In this case, the listener is typed to return `any`. Here's an example that shows this behavior:

```ts
function onSomething(e: (x: number) => number) { } // change this to 'any' to compare behavior

class Foo {
  bar() {
    onSomething(() => this.baz())
  }
}
```

The intent of quick fixes is to fix the issue, so we've avoid requiring user input on them

**Comment by bpasero** [comment]
TS should never suggest `any`. Period :)

**Comment by mjbvz** [comment]
But in your example, it's our code that explicitly says the listeners may return `any`. We should change the return type of the listener if we don't want this to happen

**Comment by mjbvz** [comment]
1. https://github.com/microsoft/TypeScript/issues/37781

2. https://github.com/microsoft/TypeScript/issues/37782

3. Is as-designed since we use `any` in our code
