### ISSUE TITLE
VSCode Explorer Display Disorder

### ISSUE THREAD

**Issue by FremdSprach** [microsoft/vscode#94119]
Issue Type: <b>Bug</b>

In the Explorer Navigation Zone, the contents of "NO FOLDER OPENED" and "OUTLINE" might overlap with each other.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (104)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
vscode-django|bat|0.20.0
color-info|bie|0.5.1
markdown-mermaid|bie|1.4.2
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
compulim-vscode-closetag|Com|1.2.0
c-cpp-compile-run|dan|1.0.7
markdown-table-prettify|dar|2.4.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.2
githistory|don|0.6.3
jquerysnippets|don|0.0.1
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.4
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
json-tools|eri|1.0.2
prettier-vscode|esb|3.20.0
eventstudio|Eve|7.3.3
vscode-relative-line-numbers|ext|0.0.5
markdown-table-formatter|fcr|2.0.3
git-project-manager|fel|1.7.1
file-icons|fil|1.0.23
vscode-firefox-debug|fir|2.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
terminal|for|0.0.10
vscode-javac|geo|0.2.32
vscode-pull-request-github|Git|0.15.0
CppSnippets|har|0.0.14
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
path-autocomplete|ion|1.13.6
latex-workshop|Jam|8.8.0
intellij-idea-keybindings|k--|0.2.38
vscode-github|Kni|0.30.3
markdown-math|koe|0.1.0
vs-color-picker|lih|1.0.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.1.0
rainbow-csv|mec|1.6.0
markdown-formatter|mer|0.7.9
git-graph|mhu|1.22.0
code-beautifier|mic|2.3.3
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.15
mssql|ms-|1.9.0
python|ms-|2020.3.71113
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.42.4
cpptools|ms-|0.27.0
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.3.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.0.1
vscode-css-peek|pra|3.0.2
java|red|0.58.0
vscode-yaml|red|0.7.2
prettier-now|rem|1.4.9
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.5.2
code-spell-checker|str|1.8.0
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|2.0.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.0.0
vim|vsc|1.13.1
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.7.0
material-theme|zhu|3.2.5
html-css-class-completion|Zig|1.19.0

(20 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/30553808/78104769-501cdb80-7422-11ea-87e3-b035e157d4d3.png)

**Comment by isidorn** [comment]
Thanks for filling this, however there is already an issue which we plan to fix today https://github.com/microsoft/vscode/issues/93344
