### ISSUE TITLE
Wrong characters

### ISSUE THREAD

**Issue by Oliverxddd** [microsoft/vscode#94124]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Launch VSCode
2. Run terminal
3. Characters will be replaced with other characters wrongly. For example "Terminated" will be displayed as "Tehminated" instead.

Does this issue occur when all extensions are disabled?: Yes/No
No. I believe it is a problem with Live Server.

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo
