### ISSUE TITLE
saveAs doesn't have a cancellation token

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94125]
re #93767

save and backUp have...

https://github.com/microsoft/vscode/blob/d05e41bef84ffae0cc3685178950524e8c33fd99/src/vs/vscode.d.ts#L6893

**Comment by bpasero** [comment]
related/dupe: https://github.com/microsoft/vscode/issues/93913

**Comment by mjbvz** [comment]
I'll add this to the API but it won't be called for now
