### ISSUE TITLE
Security vulnerability updates KB4506163 and KB4506164 detected, unable to install

### ISSUE THREAD

**Issue by PaulTemp** [microsoft/vscode#94128]
Unable to reopen https://developercommunity.visualstudio.com/content/problem/660716/security-vulnerability-updates-kb4506163-and-kb450.html

Please create new ticket there and move my post with attachements.
Paulius Petkevičius Jan 07 at 01:54 PM

**Comment by jrieken** [comment]
This is VS Code, a different product than VS 2013 and VS 2015.

**Comment by PaulTemp** [comment]
Please, guys, then I need to install Visual Studio to raise a ticket. I do not use any of these VS Codes, I just cannot install updates for client servers. Could make a favor and register the case for me?
