### ISSUE TITLE
[Feature Request] Everything is a Tab

### ISSUE THREAD

**Issue by brillout** [microsoft/vscode#94122]
Just like in the browser: everything is a tab.
 - File source code is a tab
 - Search results is a tab
 - Terminal is a tab

Display different kind of tabs with different colors/symbols.
 - File source code "tab header" is blue
 - Search results "tab header" is green
 - Terminal "tab header" is yellow

Allow two/several tabs to be shown at the same time, i.e. split screen. For having terminal side-by-side with source code. Or three file source code side-by-side. Or search results side-by-side with whatever you want. Etc.

This would make vscode so much simpler!

(PS: I've just started using vscode, really like it so far!)

**Comment by sbatten** [comment]
The flexibility of our layout is currently undergoing work and has a long roadmap. The feature request here does align partially with what we envision and I will keep its spirit in mind as we continue to work towards something more flexible. Until then, I hope you don't mind that I close this issue as duplicate. To keep up with new work being done, you can checkout issues with the label `layout` or `workbench-views`

**Comment by brillout** [comment]
> I will keep its spirit in mind

I'm glad to hear that.

Thanks!
