### ISSUE TITLE
when picture changed, it's not changed in vs code

### ISSUE THREAD

**Issue by iEverX** [Microsoft/vscode#9412]
- VSCode Version: 1.4.0-insider
- OS Version: win10 10.0.10586

I use program generating some picture, when i changed code, picture changed, but in vs code, it stayed unchanged. 

Steps to Reproduce:

1.  generate a picture, open in vs code
2.  regenerate the same picture, with difference
3. picture should change, and it does in file explorer, but in vs code, it not

**Comment by weinand** [comment]
@iEverX I cannot reproduce the issue because I don't understand the steps from above:
what kind of picture are you talking about?

**Comment by iEverX** [comment]
@weinand 
I generate the picture by matplotlib. In vs code, I can preview the picture. Then I changed paramter and regenerate the picture with the same name, the picture now is different from the old one(in file explorer, i can see the new one). however in vs code, it was the same as the old one.

**Comment by weinand** [comment]
@iEverX and the picture produced by matplotlib is html?

**Comment by kieferrm** [comment]
Please reopen when you can provide us with a little bit more information. Thanks!
