### ISSUE TITLE
Go to definition should not always put line in center

### ISSUE THREAD

**Issue by httpdigest** [Microsoft/vscode#9413]
- VSCode Version:1.4.0-insider (commit 4d0b2f5)
- OS Version:Windows 7 x64

This is rather an ergonomy improvement request:
Currently, it is irritating that Ctrl+LMouse always makes the editor scroll the text to ensure that the jumped-to function declaration is in the middle of the editor area. Instead, the 'going to the declaration' should only apply the least amount of scrolling that is necessary to see the function declaration.
This means, that, if the function is already visible (just the user does not see it immediately), there should not be any scrolling applied, but just the jumped-to function declaration highlighted.
As it is currently, the scrolling is very irritating to the eyes of the user because he loses orientation, when in fact the jumped-to function declaration was just ten lines from the call site.

Steps to Reproduce:
1. Write a simple function A
2. Call that function from callsite C, which is just 15 - 20 lines away from A's declaration
3. Make sure that both A's declaration and C are visible in the editor area and there is sufficient lines to scroll up/down
4. Ctrl+LMouse click on C
5. Observe that the editor applies unnecessary scrolling, which disorientates the user, because A was already visible

**Comment by jrieken** [comment]
The command calls `editorService.openEditor` which seems to always reveal the location in the centre...

**Comment by bpasero** [comment]
@jrieken there is an editor option `revealInCenterIfOutsideViewport` which can be used to only reveal in center if the line is outside of the viewport. I do not think we should just change this by default but would need to introduce a new setting for that if people like the current behaviour (which most seem to do).

**Comment by jrieken** [comment]
> @jrieken there is an editor option revealInCenterIfOutsideViewport which can be used to only reveal in center if the line is outside of the viewport.

I know, I am not using that but the `openEditor`-method still does that

**Comment by bpasero** [comment]
@jrieken the idea is that you either not set anything and then we reveal in center or you set `revealInCenterIfOutsideViewport` and we would only reveal in center if outside viewport. 

I think revealing in center is a good default when you set a selection to the `openEditor` call and would not expect to introduce yet another option for it.

**Comment by jrieken** [comment]
Oh, that's a crazy name...
