### ISSUE TITLE
Attach config shows stop button, not disconnect.

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94137]
Have this config

```
	"name": "Attach to Extension Host",
			"port": 5870,
			"request": "attach",
			"restart": true,
			"skipFiles": [
				"<node_internals>/**"
			],
			"type": "pwa-node"
		},
```

* start and notice how for a split second the disconnect button shows, after that it becomes stop
* the same is for stop (which behaves like disconnect)

![Apr-01-2020 12-23-38](https://user-images.githubusercontent.com/1794099/78126978-a7677f80-7413-11ea-9f79-9cc753cc6a79.gif)

**Comment by connor4312** [comment]
I traced this to 

https://github.com/microsoft/vscode/blob/0e5a5fbd6872cca0a766add20e875565e242fa17/src/vs/workbench/contrib/debug/common/debugUtils.ts#L26-L28

It seems that we don't consider a session to be an 'attach' if it has a parent session. @isidorn git blames you--was there a reason behind excluding sessions with parents?

**Comment by isidorn** [comment]
@connor4312 thanks for tracking this down. This was probably an improper fix for some other issue - might be some node cluster corner case.
Since this code does not make sense I have removed it  and if things break in some other place that we properly fix it there.
