### ISSUE TITLE
Quick outline doesn't show containers anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94139]
re https://github.com/microsoft/vscode/issues/93643

* open stopwatch.ts from our source
* items like `stop`, `_now` dont have the container description anymore

**1.43 stable**
<img width="630" alt="Screenshot 2020-04-01 at 12 35 16" src="https://user-images.githubusercontent.com/1794099/78127928-535d9a80-7415-11ea-9a9d-8c881bb17a00.png">

**insider**
<img width="756" alt="Screenshot 2020-04-01 at 12 35 24" src="https://user-images.githubusercontent.com/1794099/78127930-548ec780-7415-11ea-9ee4-fa4045ae4c8a.png">

**Comment by bpasero** [comment]
Happy you found this, an oversight on how I  compute the container.

**Comment by jrieken** [comment]
🦅 👁
