### ISSUE TITLE
Semantic colors stick around when using (only) range provider

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94133]
re #93795

I have implement a range semantic tokens provider by simply using my document semantic tokens provider, e.g that I only have a range provider, none for the whole document. What I see is that colors aren't cleared, 

* have `foo OR bar` with `OR` being a semantic keyword. 
* remove ` bar`
* using the document provider -> OR isn't highlighted anymore
* using (only) the range provider -> OR keeps its hightlight, despite my provider being asked and it returning no tokens

<img width="473" alt="Screenshot 2020-04-01 at 11 16 10" src="https://user-images.githubusercontent.com/1794099/78120922-01177c00-740b-11ea-8dd5-6df77f4d533a.png">

Code reference for tweaking/swapping of providers: https://github.com/microsoft/vscode-github-issue-notebooks/blob/1642b00d930fcdbf806a1450476b29de2877b364/src/languageProvider.ts#L266

**Comment by alexdima** [comment]
@jrieken Can you please verify? The steps are:
* comment out the document semantic tokens provider
* have a query like `A OR B`
* delete the `B` such that `OR` is at the end
* `OR` should no longer by highlighted
