### ISSUE TITLE
Odd alignment with group labels and commands

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94131]
see attached screen shot

It looks weird that the first label keeps the indentation when not focused

<img width="699" alt="image" src="https://user-images.githubusercontent.com/1794099/78119561-ea702580-7408-11ea-8277-8f87ca7c4492.png">

**Comment by bpasero** [comment]
This was done intentionally to fix https://github.com/microsoft/vscode/issues/92489

But the more I see it, the more I am also not a big fan of that change anymore. 

However it looks good and better for these cases imho: https://github.com/microsoft/vscode/issues/92489#issuecomment-598100778

@chrmarti thoughts?

**Comment by bpasero** [comment]
Back to how it was: the group is only indented when actions are visible, but not when invisible.
