### ISSUE TITLE
Go to file - Offer highlighted file path

### ISSUE THREAD

**Issue by frobinsonj** [microsoft/vscode#94132]
A feature similar to what is described in https://github.com/microsoft/vscode/issues/42297, but it should not search for the highlighted text. Instead, when <kbd>CTRL</kbd>+<kbd>P</kbd> is pressed and there is valid path highlighted (relative to the focused editor), that file should be offered at the top of the results.

This could be displayed as below but read something like "highlighted path" and change or remove the icon:
![image](https://user-images.githubusercontent.com/16726902/78118026-471a1300-73fe-11ea-9c54-4eb50d8dd5a9.png)

Thanks.

**Comment by Spongman** [comment]
it would be great if it didn't require previously secting a path in the editor, but it just searched around the caret for valid filenames.

for example, if the text in the editor was:
```
/foo/bar/go|o    # the '|' is the caret in the word '|'
```
and this feature was activated and the following files existed in the workspace:

- a/b/goo
- a/bar/goo
- a/goo/bar

then the list would show the following, in order of longest match:

- a/bar/goo
- a/b/goo
