### ISSUE TITLE
Feature request: right-click file in Search pane to "Open to the Side"

### ISSUE THREAD

**Issue by mikehurl** [microsoft/vscode#94142]
As per the title, when I perform a search in the Search pane, I would like to be able to right-click a file in the results section and be provided with the option to open the file to the side. I couldn't find anything to suggest this is already possible with a setting or extension, so apologies if a solution is already provided 😊

**Comment by roblourens** [comment]
You can actually cmd+click to open a match to the side, which matches the explorer and other things, but we could have this in the context menu too.
