### ISSUE TITLE
Unfold subtree unfolds also siblings

### ISSUE THREAD

**Issue by viktorszekeress** [microsoft/vscode#94149]
Issue Type: <b>Bug</b>

When I place a cursor at the first character in the name of the method, and press Unfold a subtree, it actually unfolds other methods as well.
I would expect that only given method body block to get expanded.
![expand_subtree](https://user-images.githubusercontent.com/45604126/78136084-519ad380-7423-11ea-99e9-dfb08ed6b2c9.jpg)
![expand_subtree_02](https://user-images.githubusercontent.com/45604126/78136096-552e5a80-7423-11ea-93b1-8264bbb0ff7f.jpg)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-statusbar-debugger|fab|2.0.6
flutter-tree|mar|1.0.0
Kotlin|mat|1.7.1
java|red|0.58.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2

</details>

**Comment by aeschli** [comment]
What's the name of the command you use?
`Unfold All` : That's unfolding all ranges in the file (unrelated to the cursor)
`Unfold Recursive` ? That's unfolding all child ranges of the range at the cursor

**Comment by viktorszekeress** [comment]
It is Unfold Recursively.

**Comment by aeschli** [comment]
I'm not able to reproduce what you see. Can you provide a small code sample that shows it?

**Comment by aeschli** [comment]
Thanks for the project and the steps. I tried again, but was not able, but I'm not familiar with Dart/Flutter.
Can your reproduces without extensions? 

If it does not reproduce without extensions, please file against the Dart / Flutter extension.
