### ISSUE TITLE
Blinking cursor outline when selecting with mouse

### ISSUE THREAD

**Issue by EugeneDae** [microsoft/vscode#94144]
- VSCode Version: 1.43.2
- OS Version: macOS Catalina 10.15.3 (19D76)

Steps to Reproduce:

1. Select text with a mouse and pay attention to the cursor: its outline would repeatedly appear and disappear at the rate of your movement. This doesn't happen in any other text editors and looks ugly.

Cursor with outline:
![outline](https://user-images.githubusercontent.com/980835/78130781-9c681b80-7422-11ea-9d89-319c0e12bcde.gif)

Cursor without outline:
![no-outline](https://user-images.githubusercontent.com/980835/78130947-e5b86b00-7422-11ea-85c4-cf2395983669.gif)

If you select fast, the transformation happens fast as well, so most users probably don't notice it:
![cursor-opt](https://user-images.githubusercontent.com/980835/78130983-f79a0e00-7422-11ea-9a5f-d80da2fc4ad6.gif)

Here's TextMate for comparison — buttery smooth:
![cursor-tm-opt](https://user-images.githubusercontent.com/980835/78132095-ce7a7d00-7424-11ea-9776-8d2a53ef3939.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I believe the OS is doing that, but I don't know why.

**Comment by EugeneDae** [comment]
@alexdima The thin cursor is a custom cursor provided by VS Code:

![cursor-css](https://user-images.githubusercontent.com/980835/78143070-6a60b480-7436-11ea-8e44-2cf7dc519501.png)

Disabling this CSS rule fixes the issue for me.

**Comment by EugeneDae** [comment]
To whoever lands here from Google, if you want to fix the issue described above, install [Customize UI extension](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) and add the following to your settings.json:

```
    "customizeUI.stylesheet": {
        ".monaco-editor.hc-black.mac .view-lines": "cursor: text !important;",
        ".monaco-editor.vs-dark.mac .view-lines": "cursor: text !important;"
    }
```

I've been using this for a month or so without any issues.

**Comment by alexdima** [comment]
This special cursor came in via https://github.com/microsoft/vscode/pull/4654 for https://github.com/microsoft/vscode/issues/754 . It looks like macOS improved (possibly when they added support for dark OS themes?) and now they render a good text cursor by default.
