### ISSUE TITLE
View: Show {View Container} commands are not available for generated containers

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#94143]
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/10746682/78131853-04ffca00-741c-11ea-8912-2d4b42cc291f.png">

**Comment by sandy081** [comment]
@sbatten Any concerns in creating view container commands for generated view containers?

**Comment by sbatten** [comment]
I think the naming can be confusing if the generated view container has a name similar to original container

**Comment by sbatten** [comment]
also, wouldn't these show up in keybindings? there could be a lot of commands with weird ids

**Comment by sandy081** [comment]
Yeah, but when I create a new viewlet it is expected to assign a keybinding for it, just like other custom viewlets. Having weird id and name is implementation detail.

**Comment by sbatten** [comment]
@sandy081 With dynamic titles, I no longer see a viable user experience here. I think we should just recommend show view commands, lmk what you think.

**Comment by sandy081** [comment]
Agreed
