### ISSUE TITLE
Incorrect highlight on JS Regex.test negated

### ISSUE THREAD

**Issue by localnet** [microsoft/vscode#94140]
- VSCode Version: 1.43.1
- OS Version: Linux desktop 5.5.10-arch1-1

Steps to Reproduce:

1. Correct highlight on JS `Regex.test` not negated:
![regex-1](https://user-images.githubusercontent.com/25712886/78127851-290bdd00-7415-11ea-9894-75a877e82713.png)

2. Incorrect highlight on JS `Regex.test` negated:
![regex-2](https://user-images.githubusercontent.com/25712886/78127949-5e182f80-7415-11ea-92d3-f96fbe63ff96.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Looks like this is already fixed in insiders and will be in the next release.
