### ISSUE TITLE
vscode locking down folders

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#9414]
- VSCode Version: 1.4.0 insider (Commit: 4d0b2f)
- OS Version: Windows 10

Steps to Reproduce:

1. Open a git repo.
2. Copy a folder and paste it, then open any file in it and close the file.
3. Then try to rename or delete the folder.
3. Fails to delete/rename the folder.

I've made a GIF illustrating this bug. It might be related to vscode doing a git-status regularly as mentioned by @joaomoreno in #901 and #7963, but I'm not sure yet.
Also, this happens almost every single time, and the only way I've found is to close vscode, and go to the directory location and manually delete/rename it.

I also have webpack in my project, but this bug occurs with or without webpack actually running.

![vscode-bug](https://cloud.githubusercontent.com/assets/760112/16901521/2cabfde6-4c64-11e6-8acd-b6f5c448b76e.gif)

**Comment by ViktorHofer** [comment]
I'm also facing this issue with node_module directory. I have to close vscode to do an "npm update".

**Comment by joaomoreno** [comment]
@kumarharsh does this really reproduce with **any** file? Even a `*.txt` file?

cc @dbaeumer since it could be TS.

**Comment by kumarharsh** [comment]
@joaomoreno It's not happening with a `*.txt` file. It seems to be only happening when I touch a `*.js` file in that folder, so it could be the TS Server.

**Comment by dbaeumer** [comment]
This is in fact the tsserver and it dups https://github.com/Microsoft/TypeScript/issues/7762
