### ISSUE TITLE
CLI fails with `open: invalid option -- 'n'`

### ISSUE THREAD

**Issue by john681611** [microsoft/vscode#94141]
- VSCode Version: 1.43.2
- OS Version:  Linux x64 4.15.0-91-generic snap

Steps to Reproduce:

1. Try and open code using cli `code <folder>`
2. Receive Error
```
open: invalid option -- 'n'
Usage: open [OPTIONS] -- command

This utility help you to start a program on a new virtual terminal (VT).

Options:
  -c, --console=NUM   use the given VT number;
  -e, --exec          execute the command, without forking;
  -f, --force         force opening a VT without checking;
  -l, --login         make the command a login shell;
  -u, --user          figure out the owner of the current VT;
  -s, --switch        switch to the new VT;
  -w, --wait          wait for command to complete;
  -v, --verbose       print a message for each action;
  -V, --version       print program version and exit;
  -h, --help          output a brief help message.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Possibly the user changed the `code` command to be different from what we do.

**Comment by joaomoreno** [comment]
Definitely. The error complains about the `open` command.

@john681611 What does `which code` return?

**Comment by john681611** [comment]
@joaomoreno 
/snap/bin/code

**Comment by joaomoreno** [comment]
What snap did you install?

**Comment by john681611** [comment]
john@TyranDev stuffstr $ snap version
snap        2.44.1
snapd       2.44.1
series      16
elementary  5.1.2
kernel      4.15.0-91-generic
I have the CLI as well as the app

**Comment by joaomoreno** [comment]
Maybe `cat /snap/bin/code`?

**Comment by john681611** [comment]
Just responds gibberish

**Comment by john681611** [comment]
ok removed code from snap and I'm still getting the message. 
`which code` now responds blank

**Comment by john681611** [comment]
Fixed had this in my bashrc from a old machine.

```
#vs code
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
```
:man_facepalming:
