### ISSUE TITLE
No message when having no results

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94145]
re https://github.com/microsoft/vscode/issues/93645

* select text that's unlikely to occur as symbol name, like `=>`
* press `cmd+t` for workspace symbols
* :bug: there is no visible progress but also no message that nothing has been found

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1794099/78133920-91f85280-741f-11ea-8f20-c138ce71f9ab.png">

**Comment by bpasero** [comment]
Similar to https://github.com/microsoft/vscode/issues/94007

I decided to drop the "no results default pick" from pickers to align with what all pickers do when there are no results, e.g. for language mode:

![image](https://user-images.githubusercontent.com/900690/78135951-0f719200-7423-11ea-9dc7-62dc9eac6327.png)

I am not sure it is good to have inconsistency around this where some pickers always show a result and others do not.

Personally I feel the indication that no results match not very useful, but we can have a UX discussion if it should come back.

@chrmarti thoughts?

**Comment by jrieken** [comment]
To me there is a difference between pickers that are populated immediately (or very, very quickly) like commands or outline and those that can take a while to populate, like workspace symbol search

**Comment by bpasero** [comment]
I will bring this back for the following quick pickers:
* files (`Cmd+P`)
* symbols (`#`)
* commands (`>`)
* editors (`edt`)
* debug (`debug`)
* views (`view`)

Verification:
* go through these pickers and produce no results
* verify you see a meaningful message appearing (pressing enter will not close the picker though)
* verify you only see this message when you searched for something, not initially
