### ISSUE TITLE
PATH variable is reversed

### ISSUE THREAD

**Issue by MagicalBomb** [microsoft/vscode#94153]
Issue Type: <b>Bug</b>

on ITerm2+/bin/zsh:
=============
echo $PATH
>> /Users/magicalbomb/Anaconda/anaconda3/bin:/Users/magicalbomb/Anaconda/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

on VS Code Termina + /bin/zsh:
=============
echo $PATH
>> /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/magicalbomb/Anaconda/anaconda3/bin:/opt/anaconda3/condabin

This problem make me can't open python for conda, but open my MacOS built-in python2.7, especially inconvenient.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.71113
material-icon-theme|PKi|4.0.1

</details>

**Comment by MagicalBomb** [comment]
when I add this the following command to my user json settings file , the problem is sloved.
>>"terminal.integrated.inheritEnv": false

**Comment by Tyriar** [comment]
I just wrote up some extensive documentation on why this happens and the fix for it which will be up in the website docs soon https://github.com/microsoft/vscode-docs/commit/38653d4a30900deb037ea4e66dd1b7054c88abcf
