### ISSUE TITLE
Missing Object.entries() in IntelliSense for JavaScript

### ISSUE THREAD

**Issue by zjopy** [microsoft/vscode#94154]
- VSCode Version: 1.43.2
- OS Version: macOS 10.15.4

It seems that IntelliSense is missing the [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) function completely. This is weird, since being introduced with ES2017 it is pretty "old". I couldn't find any other issues on this.

Then I found this statement on [Languages - JavaScript](https://code.visualstudio.com/docs/languages/javascript)

> Since VS Code's JavaScript support doesn't understand ES7 constructs, features like IntelliSense might not be fully accurate.

However the `String.prototype.trimStart()` and `trimEnd()` methods from ES2019 are present. So this sentence seems to be a forgotten relict from the past. I [updated the docs](https://github.com/microsoft/vscode-docs/pull/3520), but I'm still wondering why `Object.entries()` is missing from IntelliSense?

(I know I could enable the TypeScript compiler for `.js` files, which would give autocomplete for `Object.entries()`, but I prefer the built-in IntelliSense since it doesn't give me red squiggly lines all over the place.)

Steps to Reproduce:

1. Create a `.js` file.
2. Type `Object.entries()`.
3. Watch how IntelliSense doesn't show it.

<img width="301" alt="proof" src="https://user-images.githubusercontent.com/33468089/78138541-59f50d80-7427-11ea-8eba-5c5eb6e1367b.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
You need to tell VS Code you are targeting with a newer JavaScript runtime that supports `Object.entries`.

To do this, in your [jsconfig](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson), set `"target": "es2019"` (or possible "es2017"):

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2019",
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by zjopy** [comment]
@mjvbz Thanks. But still why do newer language additions like `String.prototype.trimStart` show up by default without needing to enable anything while `Object.entries` does not. This does not make sense.

**Comment by zjopy** [comment]
@mjbvz Thanks. But that still doesn't explain why newer language additions like `String.prototype.trimStart` show up by default without needing to enable anything while the older `Object.entries` does not. This does not make sense.
