### ISSUE TITLE
Delete word forward/backward

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#9415]
- VSCode Version: Code Insiders
- OS Version: latest OS X

On Mac, a common shortcut across the OS is alt+backspace to delete backwards a word and alt+fn+backspace to delete forwards a word. However, this does not work in vscode.

**Comment by waderyan** [comment]
I have added this to the list of Sublime Text commands that are missing in https://github.com/Microsoft/vscode/issues/3776

Here are some animations I put together to capture the feature. 

Delete from cursor to end of line:

![delete_cursor_to_end_of_line](https://cloud.githubusercontent.com/assets/2449568/19566385/e9e73dec-969e-11e6-85c7-c02aa3bb6b57.gif)

Delete prefix to cursor:

![delete_prefix_to_cursor](https://cloud.githubusercontent.com/assets/2449568/19566386/e9e9ddae-969e-11e6-84ba-a094b4229f7b.gif)

Delete suffix from cursor: 

![delete_suffix_from_cursor](https://cloud.githubusercontent.com/assets/2449568/19566387/e9ea176a-969e-11e6-95aa-fdb38913fc84.gif)

**Comment by rebornix** [comment]
For deleting from cursor to the end of line, we have `ctrl+k` builtin.

For deleting word suffix, we have `deleteWordRight` which is bind to `alt+delete` by default. For deleting word prefix, it's `deleteWordLeft` command and `alt+backspace`.

**Comment by waderyan** [comment]
Should this be closed?

**Comment by rebornix** [comment]
@waderyan  I think so :)

**Comment by ramya-rao-a** [comment]
Removing the "bug" label.
