### ISSUE TITLE
Don't extend from MenuItemAction

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94159]
see https://github.com/microsoft/vscode/blob/2f984aad710215f4e4684a035bb02f55d1a9e2cc/src/vs/workbench/contrib/notebook/browser/contrib/notebookActions.ts#L563

⬆️ instead of that, just add a new menu and register a menu item for that command, no duplication required, UX state update etc all for free

**Comment by rebornix** [comment]
@jrieken is there any way to register an action without registering a menu first?

**Comment by jrieken** [comment]
Yeah, it's all just symbolic. Create a new menu id (exported) and register commands for that, then when rendering using the menu service to get the menu

**Comment by rebornix** [comment]
@roblourens I found that `ExecuteCellAction` is also extending `MenuItemAction` and it's used programmatically in cell renderers.

**Comment by roblourens** [comment]
Yeah, but the run cell area is not really a "menu" and nobody else should be able to contribute actions to it. If they do it will break the layout. It's just a special button. Thus it seems like an exception to the rule.

**Comment by roblourens** [comment]
Leaving the run button alone. Rewrote the between cell toolbar to be a real toolbar
