### ISSUE TITLE
constants.ts is heavy on bundle size

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94157]
There is `src/vs/workbench/contrib/notebook/browser/constants.ts` which defines a bunch of string constants, mostly command/action ids. That a quite wasteful pattern because those super long exported variables names cannot be minified. So, now an id like this `workbench.notebook.code.insertCellAbove` doesn't just count as 39 characters but 33 characters are added for its name, plus N*33 where N is number of references. That's quite heavy for a strings that are only used in a single file (no export needed) and often only used once (no variable needed)

**Comment by roblourens** [comment]
Didn't realize that. I moved the command IDs into notebookActions which is the only place they are used now. Lots of them are used multiple times or could be, so I kept them as variables.
