### ISSUE TITLE
Improve linux accessibility docs

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#94156]
https://code.visualstudio.com/docs/editor/accessibility#_linux

Currently we point to an issue on how to setup Orca from master. This is pretty informal and would be much better if we could point to some Orca documentation.
@joanmarie does orca website has a page on how to setup Orca from master that we could link to?

Also this does not seem to work with Ubuntu 19 so we should also mention that in our docs. @joanmarie are you aware of this limiation?

fyi @weinand

**Comment by joanmarie** [comment]
@isidorn All we have right now is https://gitlab.gnome.org/GNOME/orca/-/blob/master/README.md

As for Ubuntu, I wasn't aware of any limitations. As an aside, Ubuntu ships a modified version of Orca with changes to how settings are managed. I don't think they are actively maintaining those changes though.

**Comment by isidorn** [comment]
@joanmarie Thanks. However that link appeart to be broken for me. Due to that I have linked to your GitHub page here https://github.com/GNOME/orca

Here's the current text. Please let me know if you would like me to change anything and I will happily do that

```
Screen reader support for the editor is still work in progress because the accessibility implementation for Chrome on Linux is work in progress.
Thus there are a couple of things needed in order to have screen reader Orca working with VS Code:

* Make sure to use the latest version of Orca out of master. More details can be found on the [Orca page](https://github.com/GNOME/orca). We have tested it works with Ubuntu 18 and with Ubuntu 19 we have encountered issues.
* Make sure to have the setting `"editor.accessibilitySupport": "on"` in VS Code. You can do this using settings, or by running the **Show Accessibility Help** command and pressing `kbstyle(Ctrl+E)` to turn on accessibilitySupport.

After enabling that setting, VS Code should work with the Orca screen reader.
```

**Comment by joanmarie** [comment]
@isidorn Thanks! Mind adding other distros to the text? I can personally tell you that Fedora 31 works fine. And @jvesouza uses Arch I believe.

To be honest, some of the stuff in downstream Ubuntu (e.g. their downstream patch to use gsettings) seems to cause side effects that impact the Orca user experience. While I don't want to discourage existing Ubuntu users from trying VSCode + Orca, if a non-Linux user is setting up a vm to give things a spin, Ubuntu wouldn't be my first choice.

As for the Gitlab repo, I can confirm that at the present time it is down. But the link I provided is valid and normally works just fine. GNOME set up mirrors of all its official projects years ago whether we liked it or not, but I believe most of us are not using Github for our projects. :woman_shrugging:

**Comment by jvesouza** [comment]
I actually use arch as my distro. I abandoned ubuntu a long time ago.
I recently read on the orca list a report that VSCode also worked on fedora 30. The user needed to set the QT_ACESSIBILITy environment variable to 1.
This variable is also present in my environment but I'm not sure if it really needs to exist for VSCode to work.
I need to test.

**Comment by isidorn** [comment]
I have updated the link to point to the GitLab page since it is back online.

I have added Fedora 31, Arch Linux. 
Let me know if I should also add Fedora 30 and I should mention the QT_ACESSIBILITY flag.

Thanks!

**Comment by jvesouza** [comment]
If I remove QT_ACCESSIBILITY=1 but add ACCESSIBILITY_ENABLED=1 everything works as expected.
> 
if  I remove the three  environment variables chromium is inaccessible.
I am testing with chromium Version 84.0.4104.0 (Developer Build) (64-bit)

**Comment by joanmarie** [comment]
@isidorn It's probably a good idea then to the need to have one of the above three flags set in the user's environment independent of distro. It could be that Ubuntu is setting one of them just in case. :woman_shrugging:

**Comment by isidorn** [comment]
Great. I have added the following sentence
* If Orca is still silent try setting `ACCESSIBILITY_ENABLED=1` as an environment variable

I did not want to mention all three env vars to not overcomplicate things.
Thanks!
