### ISSUE TITLE
python Indentation of the current line is automatically reduced after line wrap

### ISSUE THREAD

**Issue by zergtul** [microsoft/vscode#94158]
![微信图片_20200401213520](https://user-images.githubusercontent.com/40799218/78143467-ea9c0f80-7460-11ea-89e0-2564b24080ee.png)
![微信图片_20200401213524](https://user-images.githubusercontent.com/40799218/78143482-ef60c380-7460-11ea-8c41-fd05cf4240c5.png)

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by zergtul** [comment]
sorry, add info:

Extension | Author (truncated) | Version
-- | -- | --
xml | Dot | 2.5.0
code-runner | for | 0.9.17
vsc-python-indent | Kev | 1.8.1
prettify-json | moh | 0.0.3
vscode-language-pack-zh-hans | MS- | 1.44.0
python | ms- | 2020.3.71113
cpptools | ms- | 0.27.0
java | red | 0.59.0
code-spell-checker | str | 1.8.0
vscodeintellicode | Vis | 1.2.6
vscode-java-debug | vsc | 0.25.1
vscode-java-dependency | vsc | 0.9.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.22.2
vscode-maven | vsc | 0.21.2
vscode-icons | vsc | 10.0.0
material-theme | zhu | 3.2.5

vscode version
版本: 1.43.2 (user setup)
提交: 0ba0ca52957102ca3527cf479571617f0de6ed50
日期: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
We need to file and the exact line number at which you press enter. Put yourselves in our shoes, should run OCR on the screen shot or type what's visible there?

**Comment by zergtul** [comment]
soory , add the file , at line 54 .
[result_static.zip](https://github.com/microsoft/vscode/files/4416086/result_static.zip)

**Comment by alexdima** [comment]
@zergtul I could not reproduce in a vanilla VS Code installation (no extensions & no settings). I press Enter at the end of line 54. Does this reproduce for you when disabling all extensions?

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78161255-77d16b00-7445-11ea-9f47-3eb588b79df2.gif)

**Comment by zergtul** [comment]
hello , i checked all plugin , the reason is : python indent , thanks!
