### ISSUE TITLE
Contribution point for timeline provider

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#94151]
Testing #93820

Why is not there a `package.json` contribution point for timeline provider? Following are the advantages

- I am not sure how I have to activate my extension if I only contribute timeline provider. Having a timeline contribution point can allow me to activate my extension when user starts using the timeline my extension contributes

- Also helps in displaying the feature contributions in extension editor view

**Comment by eamodio** [comment]
@sandy081: @jrieken and I talked about supporting this originally but felt that it was something that could be added later.

**Comment by jrieken** [comment]
Hm, not sure... Somehow timeline feels like master-detail, e.g you open an editor and the timeline shows its contents. With that usage-pattern it feels wrong to have an activation event. Then there is the 'Open timeline' command which is different... You could that command as activation event and all is good

**Comment by sandy081** [comment]
On what event shall an extension contributing a timeline should be activated?

**Comment by jrieken** [comment]
For instance these `onCommand:openTimeline` and  `onFilesystem:foo`

**Comment by eamodio** [comment]
@jrieken should we support an `onView:timeline` activation? Rather than a really specific point just for the timeline?

**Comment by jrieken** [comment]
Yeah, that would make sense

**Comment by lramos15** [comment]
To verify ensure that your extension that contributes a timeline can activate properly when the timeline is revealed via the `onView:timeline` activation
