### ISSUE TITLE
Tab key defaults to autocomplete in find and replace widget

### ISSUE THREAD

**Issue by sharkweek** [microsoft/vscode#94166]
## Description of Issue
Hitting the `tab` key after typing in the _Find_ textbox will automatically accept the autocomplete suggestion in the editor.

## Steps to Reproduce

1. Place caret on or in the middle of a word that may trigger autocomplete
2. Initiate _Find and Replace_ widget with `ctrl + h`
3. Input text in _Find_ textbox
4. Hit `tab` key

Result: first suggestion for autocomplete at the caret in the editor is accepted

> Note: this behavior seems fairly random. All I can confirm is that it happens the majority of the time for me. The only thing that seems to guarantee this won't occur is ensuring that the caret in the editor is on a character or word that won't trigger autocomplete (e.g. whitespace, numbers, comments, etc.) __before__ initiating the _Find and Replace_ widget.

## Expected Behavior
The `tab` key should move the focus from the _Find_ textbox to the _Replace_ textbox for input. No changes to the out-of-focus editor should be made until a search or replace is triggered.

## Machine Info
Version: 1.43.2
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393
Relevant settings: `"editor.tabCompletion": "on"`
Relevant extension: [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)

Does this issue occur when all extensions are disabled?: No, because the [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension is required for autocomplete to work in my case. I have not been able to discern if this is a VS Code issue or an issue with the extension because of this requirement.

**Comment by jrieken** [comment]
any chance that you are using tab completions, e.g `editor.tabCompletion`

**Comment by jrieken** [comment]
Indeed - we have a few keybindings that don't check that the editor has input focus
