### ISSUE TITLE
Ctrl + Tab not showing recently opened files after update to 1.3.1

### ISSUE THREAD

**Issue by varungupta85** [Microsoft/vscode#9416]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.4.0

Steps to Reproduce:

1. Open a few files
2. Press Ctrl + Tab and observe that only one file appears in the list. This was working fine before the update and a very crucial feature during development.

**Comment by varungupta85** [comment]
Any updates on this issue? Is there a way to move to the previous build without uninstalling and reinstalling so that I don't loose the plugins and other settings for vscode?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6605 explains how to get that old behaviour back.

**Comment by varungupta85** [comment]
Thanks!
