### ISSUE TITLE
File stuck untokenized

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#94160]
I was testing something else and I made a file really big. Now that I've reverted the change it still won't tokenize. I get a toast about it which offers to forcefully tokenize, but when I choose that option and reopen the file it still doesn't tokenize and gives me the same toast again.

![stuckUntokenized](https://user-images.githubusercontent.com/38270282/78146919-17d1c900-7433-11ea-96ef-2954b3bdee20.gif)

**Comment by alexdima** [comment]
@alexr00 The difficulty is that certain decisions about a text buffer are taken in the ctor and then cannot be changed currently. Two things that I can imagine going wrong:
1. Perhaps the setting could not be written to `settings.json`? Do you have `"editor.largeFileOptimizations": false` in your settings?
2. Perhaps the text model is not getting disposed when closing via `x`, but I doubt this, let's first check for 1.

**Comment by alexr00** [comment]
I do have `"editor.largeFileOptimizations": false`
I can't reproduce the issue anymore though.

**Comment by alexdima** [comment]
What could have happened is that closing the file via `x` would not dispose the model. This could happen if a file still has a reference created via `ITextModelService.createModelReference`

@bpasero What should we do here, the message I have is instructing users to reopen the file, but pressing `x` and opening it again didn't do that...

**Comment by bpasero** [comment]
@alexdima you can call `ITextFileService.files.disposeModel` with the resolved text file model to forcefully dispose it. This will work fine, unless the model is dirty (which is unlikely because all editors are closed).

**Comment by alexdima** [comment]
@alexr00 Above I was speculating about what could be the root cause, but I could never reproduce this. Have you seen this since then? Do you have any steps?

**Comment by alexr00** [comment]
I have not been able to repro this today.
