### ISSUE TITLE
Keep file highlighed in search in files

### ISSUE THREAD

**Issue by NN---** [microsoft/vscode#94161]
I search in files for some text.
Afterwards I navigate to a file in the middle of the list.
When I change the file go to next occurrence starts from the beginning (F4) same for go to previous starts from the end.

I would expect it to work as in other editors including Visual Studio, next occurrence navigates to the next file without starting from the beginning.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/20467
