### ISSUE TITLE
Timestamp labels are not shown always

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#94169]
Testing #93820

Timestamp labels are not shown always

<img width="798" alt="image" src="https://user-images.githubusercontent.com/10746682/78152238-d264ca00-7439-11ea-9d18-6ecc0d8e2078.png">

My sample is here - https://github.com/sandy081/userdata-timeline-sample

**Comment by eamodio** [comment]
@sandy081 Do you mean the timestamp, not the label? From your screenshot it looks like the label is always there. We hide duplicate timestamps.

**Comment by sandy081** [comment]
Yeah timestamp on the right. 

> We hide duplicate timestamps.
I see. It was confusing to me but why?

**Comment by eamodio** [comment]
To avoid repeated timestamps, that just look like visual clutter. https://github.com/microsoft/vscode/issues/91382

**Comment by sandy081** [comment]
Makes sense.
