### ISSUE TITLE
Duplicate context keys for input focus?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94168]
The editor has two focus states: 1) input focus (blinking cursor and 2) widget focus (focus is in find or peek). However, we have three context keys for this, just a few lines apart and my understanding is that 1) is duplicated

https://github.com/microsoft/vscode/blob/0c29fa309f4887bc7774fc3efeefc904d70353a6/src/vs/editor/common/editorContextKeys.ts#L11-L23

**Comment by jrieken** [comment]
Starting with @isidorn because your name is on those lines

**Comment by isidorn** [comment]
@jrieken there is difference, you can see it [here](https://github.com/microsoft/vscode/blob/a3d17e4184af2ceff0eb36ad2bc706f54163da4d/src/vs/editor/browser/widget/codeEditorWidget.ts#L1743)

textInpuFocus is true iff a focus is in any text of the editor
editorTextFocus is true iff a focus is in any text of a non simple widget editor
editorFocus is true iff a focus is on the editor widget - not in the text

Simple editor widgets are one liner editors like the debug console, scm input and so on.
So they are not duplicated. It is confusing yes, but I think we can not dump them now.

**Comment by jrieken** [comment]
😮 oh, I think that require a little more jsdoc then better naming, e.g `simpleEditorTextFocus`. However, feel free to close this

**Comment by isidorn** [comment]
Let's leave this open to improve jsdocs.
