### ISSUE TITLE
VSCode silently fails to update

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#94164]
Version: 1.44.0-insider (system setup)
Commit: 6cf3dd97465b2f4f666b66758991d720e003b0f4
Date: 2020-03-27T06:00:06.803Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click the settings gear
2. Click "Install Update..."
3. Click "Yes" when the Windows security popup appears
4. Wait for it to install...
5. Click "Update Now" to restart VSCode
6. The commit version stays the same and and the update notification reappears

**Comment by joaomoreno** [comment]
Odd. Can you reproduce if you uninstall and reinstall insiders?

**Comment by iansan5653** [comment]
I was actually able to resolve by rebooting my PC.
