### ISSUE TITLE
Timeline view is not getting refreshed after triggering change event

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#94172]
Testing #93820

Use my sample - https://github.com/sandy081/userdata-timeline-sample

- Open settings file
- Open time line view
- Do some changes to settings
🐛 Timeline view is not updated

I see that Timeline change event is triggered here - https://github.com/sandy081/userdata-timeline-sample/blob/820fee0dde9c173d95fd53016cfe38bb7eeea52b/src/extension.ts#L30

**Comment by JacksonKearl** [comment]
Possibly need to pass `reset:true` here? #94242

**Comment by eamodio** [comment]
There was a bug with `reset: false` which has now been fixed.
