### ISSUE TITLE
Only prompt about sync changes on the active window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94176]
When the user logs out, every window gets a modal prompt to turn off sync that needs to be actioned individually. When a user signs in after this, every window gets a quick open to select the account to sync.

This should only happen for the active window, if vscode is not focused, it should wait until it is to prompt for these.

**Comment by sandy081** [comment]
Will be handled here - https://github.com/microsoft/vscode/issues/94766

**Comment by RMacfarlane** [comment]
@sandy081 I would prefer to keep this issue separate so that I can close it independently of others. I find it easier to work with smaller, more specific issues, than having one large issue, I think this also makes verifying each piece easier

**Comment by RMacfarlane** [comment]
Misunderstood what the plan for https://github.com/microsoft/vscode/issues/94766 was, this was in fact handled there since we now no longer show these dialogs
