### ISSUE TITLE
Visual Studio Code freezes completely

### ISSUE THREAD

**Issue by jakubedzior** [microsoft/vscode#94179]
Issue Type: <b>Performance Issue</b>

Visual studio code freezes sometimes after compiling .c files, but a moment ago it happened by itself, without me doing anything.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    76	  5632	code main
    0	    24	  3544	   utility
    0	   210	  6980	   window (Tablica dziwne.c - Untitled (Workspace) - Visual Studio Code)
    0	    34	  1312	     searchService
    0	   135	  1804	     extensionHost
    0	    23	  2576	       c:\Users\jakub\.vscode\extensions\ms-vscode.cpptools-0.27.0\bin\cpptools.exe
    0	    11	 10000	         console-window-host (Windows internal process)
    0	    12	 10768	         "c:\Users\jakub\.vscode\extensions\ms-vscode.cpptools-0.27.0/bin/cpptools-srv.exe" 2576 0
    0	    37	  9676	     watcherService
    1	   261	 10048	   gpu-process
    0	    13	 12700	   electron-crash-reporter
    0	    70	 12720	   shared-process
    3	    66	 13572	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Tablica dziwne.c - Untitled (Workspace) - Visual Studio Code)
|    Folder (C files): 43 files
|      File types: c(22) exe(11) driveupload(8) cpp(1)
|      Conf files:
|    Folder (Python files): 20 files
|      File types: py(16) json(1)
|      Conf files: launch.json(1)
|      Launch Configs: python;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|1.0.7
python|ms-|2020.3.71113
cpptools|ms-|0.27.0
vscode-icons|vsc|10.0.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by TylerTV** [comment]
I am running into the same issue multiple times a day. 

However, I discovered that simply closing and opening my laptop unfreezes it everything though... so maybe it is something to do with what is being displayed to the screen?

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.87-07826-g55ab70aff690

**Comment by jrieken** [comment]
@TylerTV Also for you. Do this 👉 Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
