### ISSUE TITLE
Virtually prevent pushing code down when new lines are automatically added

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [microsoft/vscode#94173]
I would like an option to virtually prevent vscode from pushing down the current focused line when new lines are automatically added. For example, when I click to automatically add an import, vscode adds the import line and the current focused line is scrolled down. This causes a distraction because the line I'm working on is moved away even tho I didn't want to scroll.

Here is a gif showing how IntelliJ behavior when new lines are automatically added above the current selected line. Note that after the import statement is added the current line is virtually kept the same (the line number do change, of course, but the scroll is set to a new position in order to respect the old position):

![intellij](https://user-images.githubusercontent.com/12160864/78154479-b13cb300-7412-11ea-9a22-66e16a0bf3b3.gif)

The next gif show how vscode pushes down the code and loses the previous virtual position:

![vscode](https://user-images.githubusercontent.com/12160864/78154825-198b9480-7413-11ea-9dd5-0fd7bfef8f86.gif)

Would be possible to add an option to vscode behavior like IntelliJ in this situation?

**Comment by alexdima** [comment]
Technically, the editor does not scroll. The scrollTop is maintained. It just happens that everything is pushed down by the auto-import which inserts a line at the top of the file.

@jrieken This can be done from the outside if you know there are edits unrelated to the current cursor position in the suggestion e.g.:
```js
const scrollState = StableEditorScrollState.capture(this._editor);
// apply edits unrelated to current cursor position ...
scrollState.restore(this._editor);
```

**Comment by alpalla** [comment]
I'd like to help out with this! Any additional pointers would be appreciated.

**Comment by jrieken** [comment]
This is where the first potential edit happens: https://github.com/microsoft/vscode/blob/e1e47d3bdf7e07757d3b5c8dd57453db8d18667e/src/vs/editor/contrib/suggest/suggestController.ts#L276 and this is where it is done: https://github.com/microsoft/vscode/blob/e1e47d3bdf7e07757d3b5c8dd57453db8d18667e/src/vs/editor/contrib/suggest/suggestController.ts#L297. So, those two places should be used to capture and restore the scroll state

**Comment by jrieken** [comment]
to verify:

1. scroll down a bit
1. select a typescript suggestion that adds an import
1. make sure that the scroll position stays stable (lines aren't pushed down)
