### ISSUE TITLE
Leave panel open when ^` shortcut returns focus to editor

### ISSUE THREAD

**Issue by CameronBieganek** [microsoft/vscode#94177]
I use VS Code on macOS 10.14.6 for Python and Julia programming. Both extensions make use of an integrated interpreter/REPL. I often switch the cursor focus back and forth between the editor and the terminal using the `` ^` `` shortcut. It turns out that for this purpose, `` ^` `` and `⌘J` behave exactly the same, though I know that they are not always exactly the same. (For example, `` ^` `` will move focus from Problems/Output/Debug Console to the Terminal.)

The behavior that I find sub-optimal is that when the cursor focus is on the terminal and I hit `` ^` ``, then the focus switches to the editor _and the panel closes_. The sole purpose of the `⌘J` shortcut is to open and close the panel, so I think it would make sense if `` ^` `` did not close the panel when it switches the focus back to the editor. Then, if the user wanted to also close the panel at some later point, they can just hit `⌘J`. (Or you can use only `⌘J` if you always want the panel to close when you switch focus back to the editor.)

This modified behavior would make the `` ^` `` and `⌘J` shortcuts more decoupled from each other.

**Comment by Tyriar** [comment]
Add this to your keybindings.json file:

```
{ "key": "ctrl+`",                "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus" }
```

**Comment by CameronBieganek** [comment]
Thanks. Googling `workbench.action.focusActiveEditorGroup` took me to the following stack exchange questions (which I had seen before but forgotten about):

https://stackoverflow.com/questions/42796887/switch-focus-between-editor-and-integrated-terminal-in-visual-studio-code

https://superuser.com/questions/1270103/how-to-switch-the-cursor-between-terminal-and-code-in-vscode

Given the number of upvotes on those questions, it seems like it might be reasonable to make the behavior mentioned in my OP the default behavior. On the other hand, I'm now aware of the `cmd + 1` shortcut to move focus to the editor (`workbench.action.focusFirstEditorGroup`), so maybe that's good enough.

**Comment by CameronBieganek** [comment]
Ok, I see. `` ^` `` is actually bound to `workbench.action.terminal.toggleTerminal`, which is different from `workbench.action.terminal.focus`. The `workbench.action.terminal.focus` command is not bound to any keystroke by default. And of course toggling is different from moving the focus... So I guess that explains the existing behavior.
