### ISSUE TITLE
Outline highligh 

### ISSUE THREAD

**Issue by JuMach** [microsoft/vscode#94183]
Hi,

When you click on a symbol / function in the outline tab, that symbol is highlighted to indicate the position you are in (example: test_2() function).

![imagen](https://user-images.githubusercontent.com/40469528/78160857-d813dd00-7444-11ea-8363-1454f4a9c71f.png)

But, if you move to another symbol from the editor (not from the outline tab) that new symbol is not highlighted on outline tab (example: test_2() function to test_3() function).

![imagen](https://user-images.githubusercontent.com/40469528/78161003-18735b00-7445-11ea-99db-d145ff9aae94.png)

In this example, I've move from test_2() function to test_3() function, but the test_2() function is still highlighted on outline tab.

Would it be possible to "update" the highlight symbol where you are?

Thank you in advance!

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aoutline
