### ISSUE TITLE
 Failed opening file <REDACTED: user-file-path> for writing: Permission denied

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#94184]
Issue Id: <b>364a66f0-9c68-0e9d-eb21-6b19f219fd17</b><br /><br />*Versions* <br />- 1.43.2<br />-  26076a4de974ead31f97692a0d32f90d735645c0<br />-  64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed<br />-  6cf3dd97465b2f4f666b66758991d720e003b0f4<br />-  78a4c91400152c0f27ba4d363eb56d2835f9903a<br />-  86405ea23e3937316009fc27c9361deee66ffbf5<br />-  8795a9889db74563ddd43eb0a897a2384129a619<br />-  9579eda04fdb3a9bba2750f15193e5fafe16b959<br />-  ae08d5460b5a45169385ff3fd44208f431992451<br />-  c47d83b293181d9be64f27ff093689e8e7aed054<br />-  e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c<br />-  f359dd69833dd8800b54d458f6d37ab7c78df520<br />-  fe22a9645b44368865c0ba92e2fb881ff1afce94<br />-  073a24de05773f2261f89172987002dc0ae2f1cd<br />-  e6a45f4242ebddb7aa9a229f85555e8a3bd987e2<br />-  efd7548df65de8e775015b67863190e6bd4934fc<br />-  1df23554b2e3d5f1efc6fbc76ee61d3f7f186c6d<br />-  b7bfce30be3c30aa2c33fbe94fe82b81d4105668<br />-  17c6d123d212f90300429ecad3fc96fcec6e338f<br />-  13d7b3066ab6e8993f12c28b0ced297781055ffc<br />-  4c9161a3f125f5a788aafa73a4ecfcb27dcfc319<br />-  9c341b3d8f2f41277be6dd59e7f4e847e6b594ac<br />-  0926b534553f3ff2f0cff0a741550a97df199706<br />-  13b38d2a494612ace32c4fb878824d6329d4c51e<br />-  798481c7978af034b054e14ace4e471e7a83f665<br />-  b0791e5236f462fbb785e9a00319705607cefb9d<br />-  b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0<br />-  2f3fe9c9c36f935ec83113ef749d1a62ff7d07b6<br />-  5996fb81591e92fd0c547dc45e3f0350026d5962<br />-  708b019bb4e20f07cf89df9f1d943af3d38d7a70<br />-  c0eea2a712471a4d242d15704cfa968241d63280<br />-  d7d1147d6b764a48b789000c03088ee9afabcd8a<br />-  b0be0672c210f1fa76109ce675365bb785657e84<br />-  33c79d5ad447956814a2a3658029dffb9e28bae6<br />-  89cafb24e5d75a0c8d561a6cdd95e93b5679e152<br />-  1876b51870e30e9ba8f35dc0dcfaf49a3799a8ef<br />-  6ec6f9e3f4d17f0cef0480688a1f350b9141e567<br />-  d1c48c103cabc6e729f59787c0b9c86fb3d39e73<br />-  ef75c4bb445e5021065cf0012cfa2c66e55bfa16<br />-  0eebaf9ad23748baca2afc0da425650922bc23de<br />-  beaf391bc53136912e4f0bbdfb7844ad954247db<br />-  d72b2d372f5024a9193b37a3830bbbc459c0ef1b<br />-  705f01577dd37d6f17eaa683ab89b0c392fa1a7c<br />-  fc14315c37f3017af937270532ae2adfbdb6b45f<br />*Stack* <br />Error: Failed opening file <REDACTED: user-file-path> for writing: Permission denied<br />    at createRotatingLogger (\node_modules.asar\spdlog\index.js:34:9)<br />    at \node_modules.asar\spdlog\index.js:27:7<br />    at \node_modules.asar\mkdirp\index.js:48:26<br />    at FSReqCallback.oncomplete (fs.js:166:5)<br />

**Comment by sandy081** [comment]
These errors are caught and handled and different logger/output channels are created.
