### ISSUE TITLE
Ctrl+` broken

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94186]
Issue Type: <b>Bug</b>

Ctrl+` to toggle the terminal is broken. For me it flips to **Problems** and stays there.

VS Code version: Code - Insiders 1.44.0-insider (20b88fa0694cae8e46ffd305a1450ba58ae6065b, 2020-04-01T08:34:11.087Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_5776770|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.0.0-1022-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (3.06GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.2
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
regex|chr|0.2.0
vscode-svgviewer|css|2.0.0
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
graphviz-markdown-preview|gee|0.0.8
vscode-pull-request-github-insiders|Git|2020.4.911
mdmath|goe|2.4.0
crazy|kie|0.0.2
svgpreview|kis|0.2.0
rainbow-csv|mec|1.6.0
theme-monokai-pro-vscode|mon|1.1.15
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71113
remote-ssh-edit-nightly|ms-|2020.3.44100
remote-ssh-nightly|ms-|2020.3.44100
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
js-debug-companion|ms-|0.0.4
vscode-github-issue-notebooks|ms-|0.0.3
vsonline|ms-|1.0.1889
material-icon-theme|PKi|4.0.1
ruby|reb|0.27.0
vscode-xml|red|0.11.0
vscode-ruby|win|0.27.0

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can't reproduce here, does it happen regardless of what is focused or if you launch with `code --disable-extensions`? You could also check your keybindings.json

**Comment by Tyriar** [comment]
Related to views, fixed today according to @sbatten

**Comment by kieferrm** [comment]
@sbatten just helped tracking this down. I moved my terminal at some point in the past but moved it back to it's original position. Moving the terminal caused the keyboard shortcut to be broken. Resetting the view location using the context menu fixed the issue.

**Comment by sbatten** [comment]
To Verify:
1. Drag Terminal to the Side Bar
2. Drag Terminal to its original position in Panel (DO NOT RESET ITS VIEW LOCATION)
3. Use Ctrl+` to toggle terminal and verify it works
