### ISSUE TITLE
 byte length of Uint32Array should be a multiple of 4

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#94180]
Issue Id: <b>55be09d1-d47d-fb83-81f1-b25c0013f884</b><br /><br />*Versions* <br />- 1.44.0-insider (3/31/2020 8:07:17 AM)<br />*Stack* <br />RangeError: byte length of Uint32Array should be a multiple of 4<br />    at new Uint32Array (<anonymous>)<br />[/vs/workbench/api/common/shared/semanticTokensDto.ts#58:9 (_buff)](https://github.com/microsoft/vscode/blob/d7d1147d6b764a48b789000c03088ee9afabcd8a/src/vs/workbench/api/common/shared/semanticTokensDto.ts#L58:9 (_buff))<br />[/vs/workbench/api/common/shared/semanticTokensDto.ts#122:36 (decodeSemanticTokensDto)](https://github.com/microsoft/vscode/blob/d7d1147d6b764a48b789000c03088ee9afabcd8a/src/vs/workbench/api/common/shared/semanticTokensDto.ts#L122:36 (decodeSemanticTokensDto))<br />[/vs/workbench/api/browser/mainThreadLanguageFeatures.ts#712:14](https://github.com/microsoft/vscode/blob/d7d1147d6b764a48b789000c03088ee9afabcd8a/src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts#L712:14)<br />    at processTicksAndRejections (<REDACTED: user-file-path>:85:5)<br />

**Comment by alexdima** [comment]
AFAIK fixed since a long time
