### ISSUE TITLE
Feature Request : Navigation Bar like Visual Studio or Eclipse

### ISSUE THREAD

**Issue by gfrancischini** [Microsoft/vscode#9418]
Would be possible to add a navigation bar like visual studio or eclipse? 

Feature Navigation Bar - 
![8284 image_thumb_1 1](https://cloud.githubusercontent.com/assets/12496146/16911670/381f590a-4cb6-11e6-9456-0d4a67f43eff.png)

This bar should show function/methods of the current file.

I know that vscode support the ctrl + p + # to find symbols but this approach is not the best when you want to have a look over the entire class (or perhaps you dont know the method name)

**Comment by weinand** [comment]
@gfrancischini your link to some image does not work.

**Comment by adamvoss** [comment]
[`Ctrl+Shift+O`](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol) is a bit closer to the functionality your are looking for, but does not have the UI fixture you've requested.

**Comment by mihailik** [comment]
I have looked at the available services and API --- it's definitely doable.

Key points are [`ICodeEditorService`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/codeEditorService.ts#L14) and [`DocumentSymbolProviderRegistry`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L717).

`DocumentSymbolProviderRegistry` enables querying the document for symbols, which includes things like namespaces or functions, spanning large parts of text and nesting into each other.

`ICodeEditorService` gives access to the editor, and events such as editing and cursor movement, so navbar would know when to be updated. Additionally editor allows placing decorations over chunks of text. That's useful because you want to highlight 'breadcrumb' points in actual text, say when user puts mouse over navbar or parts of it.

The only remaining question is placing the navbar on screen. I'm not quite sure which part of the code has the layout of editor tabs.

One way or another I'm preparing to have a go at this feature. Any preliminary advice and suggestions are welcome!

**Comment by mihailik** [comment]
Opened PR #31162 with a prototype implementation, using services described above.

Advice on finalising the styles, and coding changes is highly appreciated!

**Comment by mihailik** [comment]
Updated PR #31162 with flashing symbol position, adding screenshot here too. Does it look good? Any feedback?

<img width="866" alt="screen shot 2017-07-25 at 08 17 47" src="https://user-images.githubusercontent.com/4041967/28587061-bd51c1bc-716d-11e7-812f-bfa936fe11bd.png">

**Comment by jrieken** [comment]
@isidorn Why did you close this? Since when do you take responsibilities in this area?

**Comment by isidorn** [comment]
@jrieken I went through all the UX issues because I felt there are a lot of issues that nobody payed attention to. Feel free to reopen.

**Comment by jrieken** [comment]
It's on our roadmap: https://github.com/Microsoft/vscode/wiki/Roadmap#workbench

**Comment by mihailik** [comment]
Ah that's true!
> Improve intra-file navigation (outline, bread crumb)

It was a bit disheartening to see this dropped, but to be honest my own effort fell silent for a while (backlog at day job) so I didn't have courage to complain.

Thanks for raising profile of this feature @jrieken , I'll push with what's been discussed on the <a href="https://github.com/Microsoft/vscode/pull/31162#issuecomment-331893820">prototype implementation thread</a> next week.

Hope no hard feelings, this is a huge project and admin friction is sometimes inevitable. Microsoft is doing stellar job managing community contribution on VSCode as well as relevant sister projects. Thank you!

**Comment by MiguelQueiroz** [comment]
This is nice and very handy, i had the same "pain" for long functions, where i don't know where i'm :) , it would be nice to read the stycky function name on the scroll page scope. Like the referenced issue shows above!

**Comment by worrel** [comment]
I'd also like to add that structure breadcrumbs/path can be very useful for nested data formats like JSON or XML.   IntelliJ and Chrome Dev Tools provide this.  For instance, when I'm looking at a giant Elasticsearch document or mapping dump where key names are re-used at different levels, it's invaluable to see that i'm on, say 

```something.results[3].item.name.nameItem.subKey.name```

These breadcrumbs can get very long, so being able to scroll horizontally over them or being able to copy the path to the currently highlighted node is very useful.

**Comment by jrieken** [comment]
We wanna explore this in June

**Comment by weinand** [comment]
@isidorn if we get some space for a navigation bar, we could consider to use this while debugging. E.g. we could try to place the debug toolbar there...

**Comment by isidorn** [comment]
@weinand might work, but let's first wait for the navigation bar :)

**Comment by weinand** [comment]
@jrieken sure, I understand. I just wanted to spark some UX thinking on our side because we have "improvements of the debug toolbar" on the June plan...

**Comment by jrieken** [comment]
We have a prototype and we will ship this in July

**Comment by jrieken** [comment]
A first version of this is in *todays* insiders build. You can enable it via `"breadcrumbs.enabled": true`. There are two modes, depending on you using tabs or not. When tabs are enabled breadcrumbs show as extra row below the tab and above the editor. When no tabs are enabled, the breadcrumbs shows more subtle, right of the editor title.

**Tabs & Breadcrumbs**

<img width="704" alt="screen shot 2018-07-12 at 11 52 08" src="https://user-images.githubusercontent.com/1794099/42626391-7fa2d762-85ca-11e8-998e-e0cd673a5636.png">


**No Tabs & Breadcrumbs**

<img width="828" alt="screen shot 2018-07-12 at 11 52 33" src="https://user-images.githubusercontent.com/1794099/42626402-842c740a-85ca-11e8-8cc8-799a46088083.png">

**Keybindings**

You can use the mouse and these keybinding to interact with breadcrumbs

* <kbd>Cmd+Shit+.</kbd> moves focus to the breadcrumbs
* <kbd>Esc</kbd> moves focus back into the editor
* <kbd>ArrowLeft</kbd> and <kbd>ArrowRight</kbd> select items in the breadcrumb
* <kbd>Enter</kbd> shows the picker
* <kbd>Shift+ArrowLeft</kbd> and <kbd>Shift+ArrowRight</kbd> move the picker

Remember, this is an early version and not yet everything works e.g. type to find. Still, give it a try and let us know what you think. #HappyCoding!

**Comment by usernamehw** [comment]
It looks and works pretty good from the start 👍 

Should there be a distinction (border, for instance) between folder-file / insides of the file?
![before](https://user-images.githubusercontent.com/9638156/42653775-1a38d156-861f-11e8-8619-019430703f55.png)

![after](https://user-images.githubusercontent.com/9638156/42653780-1eefc858-861f-11e8-8b00-550b50ed8e28.png)

Or highlighting current file (just like tabs):
![highlight_file_name](https://user-images.githubusercontent.com/9638156/42653800-30f05c8e-861f-11e8-9cd4-d85c430bc60e.png)

**Comment by qcz** [comment]
Can we have an option to hide the file path which I'm not interested in? It becomes very crowded very quickly when multiple columns of editors are open.

**Comment by jrieken** [comment]
> Can we have an option to hide the file path which I'm not interested in?

Yeah, the following things I have in my mind: `breadcrumb.filePath: 'on | off | onlyLast'` and `breadcrumb.symbolPath: on | off | onlyLast`.

**Comment by qcz** [comment]
@jrieken: This is the best solution! 💯

**Comment by bardware** [comment]
Is it populated with the data the outline view uses?

**Comment by Cryrivers** [comment]
Awesome stuff. Could it also highlight errors like Code Outline as well?

**Comment by smlombardi** [comment]
Mine are appearing in the wrong place:

<img width="1129" alt="screen shot 2018-07-13 at 8 00 04 pm" src="https://user-images.githubusercontent.com/835148/42718496-6914af12-86d7-11e8-8fa5-64a71df02801.png">

**Comment by jrieken** [comment]
> Correction: why not make Ctrl-Click jump to the breadcrumb position, and click open the menu?

👍 pushed a change to make Cmd/Ctrl+Click reveal the symbol in the editor. Also <kbd>Shift+Enter</kdb> will reveal the symbol instead of showing the picker. Updates 
https://github.com/Microsoft/vscode/issues/9418#issuecomment-404460635 accordingly.

**Comment by jrieken** [comment]
> Another suggestion: move [Find] field down below, or remove completely. It makes interaction less smooth

I have pushed the a change for *next* insiders (18 July) that hides the filter box initially and reveals it when starting to type. Like so

![jul-17-2018 11-03-28](https://user-images.githubusercontent.com/1794099/42807455-1f5574e2-89b1-11e8-9216-adfed0e81bdc.gif)

**Comment by mihailik** [comment]
Dark theme - the dropdown is really blending with editor. Consider a very faint border around it:

![breadcrumbs-no-border](https://user-images.githubusercontent.com/4041967/42809673-0cb41058-89ae-11e8-9ac2-2c0845f51084.png)

![breadcrumbs-with-border](https://user-images.githubusercontent.com/4041967/42809683-1229bd08-89ae-11e8-93a8-06e27f1a6b31.png)

**Comment by bardware** [comment]
> hides the filter box initially

How does the user know he can type to filter? Is there a tooltip or an icon or the like? Any hint?

**Comment by JacksonKearl** [comment]
Is there an action which I can bind to open up the topmost dowpdown? I'd like to use this to close #53279 by allowing a quick way to navigate from say `**/A.ts` to `**/media/A.css`, when there may be many files named `A.css` throughout the workspace and the file open quick pick wouldn't be able to distinguish between them.

**Comment by JacksonKearl** [comment]
It would be nice if the crumbs could be optionally hidden by default and only appear on the `Ctrl+Shift+.` trigger, then disappear again on `Esc` or a selection

**Comment by jrieken** [comment]
Closing this issue now because the biggest chunk of work is done and because we will ship this with the July release. Obviously, we aren't done but in the name of manageability we have added the [`outline`](https://github.com/Microsoft/vscode/labels/breadcrumbs)-label which tracks all remaining bugs and feature requests. #HappyCoding!
