### ISSUE TITLE
All extentions disappeared and can't install new ones

### ISSUE THREAD

**Issue by zean7760** [microsoft/vscode#94193]
Issue Type: <b>Bug</b>

`Cannot read property 'templateData' of null` shows when I search for extentions

VS Code version: Code - Exploration 1.44.0-exploration (2766badcb6c29445f5289033f1343f373802315c, 2020-03-27T21:34:34.236Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 16, 19|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
rainbow-end|jdu|0.7.5
rainbow-csv|mec|1.6.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.0.0
mssql|ms-|1.9.0
vscode-elixir-formatter|sam|0.2.0
trailing-spaces|sha|0.3.1
vscode-eex-snippets|ste|0.0.6
code-spell-checker|str|1.8.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
I do not know where and how you got this exploration build. Please repro it in our insiders or stable build and provide us the steps.
