### ISSUE TITLE
Quick fix popup may take the whole screen

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [microsoft/vscode#94190]
Would be possible to add an option to limit how many items are listed in the **Quick fix** popup before scrolling kicks in?

For example, when quick fixing a missing import for the `List` class in Java, vscode shows this:

![image](https://user-images.githubusercontent.com/12160864/78166238-d6d1b880-7422-11ea-92ff-5002b6628bdc.png)

This is of course overkill and scares the user.

In IntelliJ the suggestion popup takes up to 50% of the screen before enabling vertical scrolling.

There's also another issue with the Quick fix popup. When the popup is opened it will automatically select the item below the cursor pointer, which is bad because usually the first options are the better one, and the cursor may be pointing to the bottom of the list when the quick fix is opened. If I move the cursor, then it should highlight the item below it. Meanwhile, if the quick fix popup always open with the first item selected, then it would be easier and predictable to navigate and select it using just the keyboard, no matter where the cursor pointer is.

**Comment by sbatten** [comment]
after thinking about this, we would prefer to avoid scrolling the menu in most cases so adding conditions to make it more likely are out of scope. however, the java extension should probably not be doing the above.
