### ISSUE TITLE
Tabbing through changes view with screen reader causes changes view to indent

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#94199]
Refs #93301

1. Get into the changes view and focus on the first line
  ![image](https://user-images.githubusercontent.com/35271042/78172261-9a925e00-740a-11ea-885e-613acef5ed29.png)
2. Hit `Shift+Tab` to go to previous tabbed item
3. Hit `Tab` to go back to first line
4. :bug: Changes view starts getting indented every time you hit `Tab`
![image](https://user-images.githubusercontent.com/35271042/78172366-c7467580-740a-11ea-8106-a9e9423fa031.png)

**Comment by misolori** [comment]
This actually makes edits to the original file and is quite annoying. I would expect for this be a read-only mode.

**Comment by isidorn** [comment]
Very good catch, and yes we should fix. However this was always like this, thus not a regression and I prefer to fix next week assigning to august.
Thanks for filling good isues!
