### ISSUE TITLE
[lua] "goto" missing in Lua syntax highlighting

### ISSUE THREAD

**Issue by BinaryInk** [Microsoft/vscode#942]
When using the goto keyword, it is not highlighted, nor is the label selected.

Example:
```
function func()
     if this == that then
          do = this
          goto continueHere
     elseif this2 == that2 then
          ::continueHere::
     end
end
```

Ignoring the terrible example itself, the problem occurs on line 4 where no highlighting will occur. Line 6, where the label is, highlights correctly, however.

**Comment by aeschli** [comment]
This issue was moved to textmate/lua.tmbundle#5

**Comment by aeschli** [comment]
Fix for text mate and Monarch grammar delivered
