### ISSUE TITLE
[folding] CTRL + ENTER should add new line after folded block

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#94202]
Issue Type: <b>Bug</b>

When hit ENTER or CTRL+ENTER to create a new line after folded block, the block will unfold which did not happen in VS. Pretty annoying:(

(left: vscode, right: vs)
before ENTER or CTRL+ENTER:
![image](https://user-images.githubusercontent.com/24863266/78175921-3fa24a80-748e-11ea-8209-91ac019628af.png)

after ENTER or CTRL+ENTER:
![image](https://user-images.githubusercontent.com/24863266/78175884-31542e80-748e-11ea-8436-23514f9305f1.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.21.16
python|ms-|2020.3.71113
unity-tools|Tob|1.2.3

</details>

**Comment by aeschli** [comment]
The cursor position is just before the `...` ?
VSCode considers that inside the folded block.

**Comment by bao007fei** [comment]
> The cursor position is just before the `...` ?
> VSCode considers that inside the folded block.

cursor before `...` is not that useful, IMO behave like VS makes more sense.
