### ISSUE TITLE
Diff with previous version in sync activity view

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#94203]
Issue Type: <b>Bug</b>

#93771

Seeing a few empty diffs for settings and snippets:

![image](https://user-images.githubusercontent.com/9205389/78176445-c807f780-745c-11ea-8ac6-ef54b033f156.png)

Funny: When I enable 'Ignore leading / trailing whitespace' in that diff editor, that setting is toggled in the right part of the diff editor which I expected to be read-only.

VS Code version: Code - Insiders 1.44.0-insider (20b88fa0694cae8e46ffd305a1450ba58ae6065b, 2020-04-01T08:29:34.507Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|7.77GB (3.27GB free)|
|Process Argv|--disable-gpu --extensions-dir=/home/chrmarti/tmp/ext2 --user-data-dir=/home/chrmarti/tmp/user2 --no-sandbox|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
vscode-eslint|dba|2.1.2
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.1.1
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-pull-request-github-insiders|Git|2020.4.511
rest-client|hum|0.23.2
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.1.1
remote-containers|ms-|0.109.0
remote-ssh-edit-nightly|ms-|2020.3.44100
remote-ssh-nightly|ms-|2020.3.44100
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.8
azurecli|ms-|0.5.0
github-issues-prs|ms-|0.9.2
debugger-for-chrome|msj|4.12.6
vscode-versionlens|pfl|0.25.0
vscode-yaml|red|0.7.2
vscode-open-in-github|sys|1.13.0
vscodeintellicode|Vis|1.2.6

(1 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
I realize it might be showing the diff to the current state, not the diff between states.

Please make it show the diff that was applied at that point in time. Showing the diff to the current version is not intuitive.

**Comment by chrmarti** [comment]
Also show diffs for extensions and global state, these are missing. (Should that be a separate issue?)

**Comment by sandy081** [comment]
Is not the expected default is  to show the diff with current state? Showing diff between states is an advanced and separate action ?

**Comment by sandy081** [comment]
> Also show diffs for extensions and global state, these are missing. (Should that be a separate issue?)

Yeah they are not shown yet. Already have an issue for it.

**Comment by chrmarti** [comment]
From the way Wikis and GitHub comment's edit histories work, I expected the diff to be between the two states in the history - not between the old and the current state. 🤷‍♂

**Comment by sandy081** [comment]
I see.

**Comment by rchiodo** [comment]
@sandy081 do you have any repro steps?

**Comment by rchiodo** [comment]
THis is what I tried:
- Run with --user-data-dir
- Run without
- Turn on settings sync for both
- Verify sync diffs remote version

**Comment by sandy081** [comment]
Sorry for not providing the steps. Here you go:

- Turn on settings sync
- Try to sync up some settings. keybindings 
- Open Sync Data view - `F1 > Settings Sync: Show Synced Data`
- Browse settings / keybindings file in `Sync Data (Remote)` view
- Make sure the diff shows with previous version on left and current version on right side.
