### ISSUE TITLE
lsp-embedded-language-service only works on files that are saved

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#94204]
Testing https://github.com/microsoft/vscode/issues/93809

I was trying to use the sample by opening an untitled file and changing the mode to html, but it didn't work in that file. The readme should mention this.

**Comment by octref** [comment]
We now mention creating a `.html1` file in both samples:
- https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-embedded-language-service
- https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-embedded-request-forwarding
