### ISSUE TITLE
Can't be logged in into VSO and OAuth at the same time

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94206]
Testing: https://github.com/microsoft/vscode/issues/93813

I have two extensions to that to the same thing. Sources in https://github.com/kieferrm/testplan-items/tree/master/git-auth-test.

1) start insiders with those two extensions in the `extensions-dir`
2) F1 > GitHubAuth-Test1: Login with OAuth
3) walk through the browser flow
-> OAuth session starts
4) F1 > GitHubAuth-Test1: Show OAuth sessions
-> session shown
5) F1 > GitHubAuth-Test2: Show OAuth sessions
-> session shown
6) F1 > GitHubAuth-Test1: Login with VSO
7) walk through the browser flows
-> Session starts
8) F1 > GitHubAuth-Test1: Show VSO sessions
-> session shown
9) F1 > GitHubAuth-Test2: Show VSO sessions
-> session shown

10) F1 > GitHubAuth-Test1: Show OAuth sessions
-> no session available
5) F1 > GitHubAuth-Test2: Show OAuth sessions
-> no session available

The same happens when I switch OAuth and VSO.

**Comment by RMacfarlane** [comment]
fixed as part of https://github.com/microsoft/vscode/commit/917c420302a77222656f82690063c4c835da902c, session ids were colliding

**Comment by kieferrm** [comment]
@roblourens it's public now.
