### ISSUE TITLE
Codelens collides with code when using font zoom

### ISSUE THREAD

**Issue by spahnke** [microsoft/vscode#94200]
Version: 1.44.0-insider
Commit: 20b88fa0694cae8e46ffd305a1450ba58ae6065b
Date: 2020-04-01T08:34:11.087Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Use font zoom in e.g. a TypeScript class to zoom in to max zoom level
2. Observe that the codelens collides with the code

![image](https://user-images.githubusercontent.com/25029871/78172541-87a57b00-7456-11ea-880f-261ef37cf1b0.png)

I'm using Source Code Pro as font but can also reproduce with Menlo and Monaco; haven't tried other fonts. 

**Update**: Also just noticed that the codelens realigns as soon as you begin typing. If you then go back to the normal zoom level it's misaligned again until you start typing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aeditor-code-lens

**Comment by sh7dm** [comment]
I'm working on it, will submit a PR soon.

**Comment by spahnke** [comment]
I can't find any currently open issues with the above query, nor with a full text search with the keywords "codelens" or "code lens" that describe the same bug. I see several closed issues like #93367 or #88299 that never really got resolved because they weren't reproducible (all have the "needs-more-info" tag). There is #85093 that got fixed, but none of the issues mention font zoom at all.
