### ISSUE TITLE
Duplicate entries for trusted extensions for my account

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94207]
Testing: https://github.com/microsoft/vscode/issues/93813

After running through https://github.com/microsoft/vscode/issues/94206.

1) Go to Accounts in the activity bar
2) Choose the GH account
3) Select `Manage Trusted Extensions`
->
![image](https://user-images.githubusercontent.com/4674940/78179481-1e057c80-7416-11ea-9314-08b9a6b4a6ef.png)

**Comment by RMacfarlane** [comment]
fixed as part of https://github.com/microsoft/vscode/commit/917c420302a77222656f82690063c4c835da902c

**Comment by JacksonKearl** [comment]
Opening up for someone else to verify as the oauth `vscode-insiders` links are triggering my Windows Parallels instance to open 😐

**Comment by alexr00** [comment]
@RMacfarlane I can't verify this either. The url that VS Code tries to open for the 'loginWithReop' command doesn't appear to do anything.

**Comment by alexr00** [comment]
Got it to work by changing my default browser (I'm selfhosting Edge).
