### ISSUE TITLE
Feature request: auto scrolling and smart scrolling in the integrated terminal

### ISSUE THREAD

**Issue by cdsousa** [microsoft/vscode#94208]
Feature request: auto scroll (with a toggle button) and smart scroll lock (with a toggle in settings) for the integrated terminal, just like it exists for the output panel.

**Comment by Tyriar** [comment]
I don't think this is necessary ready the linked issue, discussion here https://github.com/julia-vscode/julia-vscode/issues/486#issuecomment-640604354

**Comment by Tyriar** [comment]
Closing as it can be fixed in the upstream repo.
