### ISSUE TITLE
Strange semantic highlight state

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94214]
Using theme Noctis Lilac https://marketplace.visualstudio.com/items?itemName=liviuschera.noctis

New typesctipt file with contents:
```ts
return new Promise((resolve, reject) => {
    const data = await this.tryRetrieveData();
    if (data) {
        resolve(data);
    } else {
        reject("No data!");
    }
});
```

Notice at first the resolve,reject call are the same color as tryRetrieveData. Then, after a small delay they become the same color as the parameters. I assume this is some semantic highlighting. However, in the token inspector window:
![image](https://user-images.githubusercontent.com/8586769/78184926-244c2680-741f-11ea-9c51-d074e36c1fde.png)
It lists their colors as #0095A9, which is the function call color that they originally had, not the parameter color.

**Comment by JacksonKearl** [comment]
Ref #91038

**Comment by JacksonKearl** [comment]
See also #94211

**Comment by alexdima** [comment]
Thanks, that's it. Let's track in #94211
