### ISSUE TITLE
Sorting of entries in the refactor preview puts checked items last instead of first

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#94210]
- VSCode Version: 1.43.2
- OS Version: Windows or others.

Steps to Reproduce:

1. See issue https://github.com/microsoft/vscode/issues/90664 , that says "We should make sure that categories with unconfirmed changes go atop, files should be sorted by name and changes by line number".

Expected: Our C/C++ extension would prefer the opposite behavior with the confirmed changes going on at the top, which is what was originally requested at https://github.com/microsoft/vscode/issues/77728#issuecomment-585985696 and what matches Visual Studio's C++ Rename preview:

![image](https://user-images.githubusercontent.com/19859882/78183200-57d98180-741c-11ea-8002-4497d14771af.png)

Was there a reason the opposite sorting was desired? Our Find All References UI (and our current Rename UI) puts the confirmed/checked references at the top, so flipping the order for rename is confusing to our users. In many scenarios, users just want to preview the confirmed/checked references, and they skip the other stuff, which is why we'd prefer the other types of unconfirmed/unchecked references to be at the bottom, since those types are less likely to be renamed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sean-mcmanus** [comment]
@vscodebot Not a duplicate.

**Comment by jrieken** [comment]
> Was there a reason the opposite sorting was desired?

The idea is that un-confirmed results need human eyes to check wether they should be included or not. For those that the computer is certain no check is needed, hence it is less important. That's the line of thought here. Disagreement?

**Comment by bobbrow** [comment]
I think part of the concern here is that the panel these results are appearing in is not very tall (by default), so the user is often presented with a bunch of empty check boxes as if the extension couldn't figure out any of the renames on its own. They'd have to scroll down to see that we had confidence about any of the rename candidates.  Putting the confirmed references at the top gives users more confidence in our extension's results.

Another option: Put the confirmed ones at the top and collapse the node?

**Comment by sean-mcmanus** [comment]
This is a visual before and after example of what we're concerned about:

After (confirmed at the bottom):
![image](https://user-images.githubusercontent.com/19859882/78303763-321eac00-74f2-11ea-9141-c79cfc1f90fe.png)


Before (confirmed at the top):

![image](https://user-images.githubusercontent.com/19859882/78303877-714cfd00-74f2-11ea-89b1-ec7864752df8.png)

**Comment by bobbrow** [comment]
> but to me it’s mostly about seeing/previewing what the rename will do as a 1st step, and then when that looks good I might look at the other stuff I might want to add (i.e. it’s the “read order” that makes sense to me).

This makes sense to me. I think the discussion here is whether rename "preview" should prioritize previewing what is about to happen (the confirmed references) or whether it prioritizes previewing what might be skipped by the operation.  I agree with @sean-mcmanus that it is about the former.

**Comment by sean-mcmanus** [comment]
Here's another reason why confirmed/checked references should be shown first for C++ -- 2 different objects of different types sometimes get confirmed as the same reference when they're not.
![image](https://user-images.githubusercontent.com/19859882/80746726-36c98680-8ad7-11ea-9f77-67de4645c1f1.png)

I filed VS bug https://developercommunity.visualstudio.com/content/problem/1014321/c-intellisense-find-all-references-confirms-refere.html , but I don't believe it's a regression and may be considered a "by design limitation", so I'm not expecting it to be fixed soon.
