### ISSUE TITLE
Wrong autocomplete order/selection

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9421]
- VSCode Version: 1.4.0-insider
- OS Version: OSX

Steps to Reproduce:

1. Create TypeScript file
2. Enter the following code
```
const test1 = 5
const test = {
    a: 1
}
```
3. Type `test.`

Problem:
VSCode will autocomplete with `test1.`

Here is the screenshot of what VScode highlights by default when `test` is typed in - and pressing `.` will select it (notice that order is incorrect - test1 should be below test)

![image](https://cloud.githubusercontent.com/assets/1723815/16903370/46230964-4c4a-11e6-8b5d-8324c715c617.png)

For comparison this is VSCode 1.3.1:

![image](https://cloud.githubusercontent.com/assets/1723815/16903374/55517c7c-4c4a-11e6-9187-ac95c9aa20ba.png)

Unfortunately it might be related to the project, because if I try to recreate it with empty project then it was fine.

**Comment by wallverb** [comment]
It seems like the issue is related to `editor.snippetOrder` setting

If it's set to `bottom`

here is the result:
![image](https://cloud.githubusercontent.com/assets/1723815/16903480/80b55e8a-4c4d-11e6-97f0-d3fff31def33.png)

If `editor.snippetOrder = 'normal'`
then

![image](https://cloud.githubusercontent.com/assets/1723815/16903485/9961ead4-4c4d-11e6-9e1a-7d07350a392c.png)

**Comment by jrieken** [comment]
`editor.snippetOrder` does not exist anymore

**Comment by joaomoreno** [comment]
@jrieken Then why assigning this to me instead of closing the issue?

**Comment by jrieken** [comment]
@joaomoreno because the **default** sort order is still as described

**Comment by joaomoreno** [comment]
@jrieken This is what I get on the latest Insider:

![image](https://cloud.githubusercontent.com/assets/22350/16979935/177b834a-4e64-11e6-9014-2e9d317adbeb.png)

**Comment by wallverb** [comment]
It's not happening to me anymore - so maybe it got fixed when `editor.snippetOrder` got removed :) Thanks

**Comment by wallverb** [comment]
@joaomoreno I'm sorry - but seems like it is still the issue - just don't know how to recreate :( 

If I have setting: `"editor.snippetSuggestions": "bottom"`
then look at wrong order:
![image](https://cloud.githubusercontent.com/assets/1723815/16989347/dfc59e74-4e61-11e6-9de6-c4ef25a85ec4.png)

If I have default setting: `"editor.snippetSuggestions": "inline"` then order is fine:
![image](https://cloud.githubusercontent.com/assets/1723815/16989375/fd0a9ebc-4e61-11e6-8a83-a0a20a689999.png)

Any chance for 'blind fix' ? :D

**Comment by joaomoreno** [comment]
@jrieken ?

**Comment by jrieken** [comment]
None of the suggestions shown in the above screen shot are snippet proposals (check the icon). It might be a side effect from the setting selecting a different comparator tho...

**Comment by jrieken** [comment]
Yep - there is an issue with the comparator when two suggest are of different type but none of them is a snippet.

**Comment by jrieken** [comment]
@wallverb I have pushed a more or less blind fix. It would be great if you can try with tomorrows insider update. Thanks

**Comment by wallverb** [comment]
I will - thanks a lot @jrieken
