### ISSUE TITLE
Searching for VS Live Share leads to a 2 year old limited preview blog, confusing users

### ISSUE THREAD

**Issue by senergin-msft** [microsoft/vscode#94217]
- VSCode Version: N/A
- OS Version: N/A

Steps to Reproduce:
1. Use Google, or Bing to search for "Visual Studio Live Share"
1. First result is a 2 year old limited preview announcement (https://code.visualstudio.com/blogs/2017/11/15/live-share), and not the official documentation / presentation of public feature https://docs.microsoft.com/en-us/visualstudio/liveshare/
1. User navigates to https://code.visualstudio.com/blogs/2017/11/15/live-share , update is small and is designed not to be the center of attention. User reads the page and thinks feature is not public.
1. Suggestion: Either SEO optimization, or a better update on the blog post to direct users to public official documentation.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrisdias** [comment]
please open an issue in the live share repository: https://github.com/MicrosoftDocs/live-share/issues/new/choose
