### ISSUE TITLE
StatusBarItem doesn't respect it's Command's title/tooltip

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94216]
Ref #22353
```ts
	const sbi = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
	sbi.command = {
		command: "workbench.action.tasks.runTask",
		title: 'Hello',
		tooltip: "tooltip",
		arguments: ['tsc']
	};
	sbi.show();
```

expect the title and tooltip to be reflected in the item. they aren't, they must be manaully re-set on the top level status bar item.

**Comment by mjbvz** [comment]
We take these properties from `StatusBarItem` itself. We discussed using a different type for `command` in #22353 but thought `Command` best documented the intention of the property

@jrieken Let me know if you think we should try falling back to use the `title` and `tooltip` from the command if they have not been set on the `StatusBarItem`

**Comment by JacksonKearl** [comment]
> but thought Command best documented the intention of the property

I agree that it documents the intent well, but some docstrings in Command make this confusing:

```ts
		/**
		 * A tooltip for the command, when represented in the UI.
		 */
		tooltip?: string;
```

**Comment by jrieken** [comment]
> @jrieken Let me know if you think we should try falling back to use the title and tooltip from the command 

Not a fan - I think the doc for the status bar should say what's ignore or used from the given command
