### ISSUE TITLE
Product Icons: iconDefinitions.font doesn't seem to work when there are multiple fonts

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94215]
Refs: #93798

I've tried having 2 font sources, and then for certain icons use one font or another, but it seem that only the first font in the `fonts` array is ever used.

**Comment by aeschli** [comment]
in the definition, do you specify the `fontId`? If left out, the first defined font will be taken
(at least that's the intention...)

**Comment by eamodio** [comment]
I didn't see a `fontId` property, but I did set the `font` property.

```json
{
	"fonts": [
		{
			"id": "elegant",
			"src": [{ "format": "woff", "path": "./ElegantIcons.woff" }],
			"style": "normal",
			"weight": "normal"
		},
		{
			"id": "font-awesome",
			"src": [{ "format": "otf", "path": "./Font Awesome 5 Free-Regular-400.otf" }],
			"style": "normal",
			"weight": "normal"
		}
	],
	"iconDefinitions": {
		"compare-changes": {
			"font": "font-awesome",
			"fontCharacter": "\\e030"
		},
		"git-commit": {
			"font": "elegant",
			"fontCharacter": "\\e030"
		},
		"activate-breakpoints": {
			"font": "font-awesome",
			"fontCharacter": "\\e030"
		}
	}
}
```

**Comment by eamodio** [comment]
I just tried using `fontId` instead and didn't see any change in behavior.

**Comment by aeschli** [comment]
It is `fontId`. The schema was wrong. I verified if works with two different fonts

**Comment by JacksonKearl** [comment]
Wasn't able to get font-awesome to show up as anything besides boxes, but thats likely an issue on my end. elegant seemed to work fine

**Comment by sbatten** [comment]
@JacksonKearl see my comment here https://github.com/microsoft/vscode/issues/94209#issuecomment-622025851
