### ISSUE TITLE
Semantic highlighting: range semantic tokens provider does not respect semanticHighlighting setting

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94211]
Issue Type: <b>Bug</b>

Currently in VS Code repo, I constantly see wrong temporary semantic colors in typescripts documents. They are flushed after scrolling 

*Weird red color for properties*
<img width="1757" alt="image" src="https://user-images.githubusercontent.com/876920/78183406-b4d53780-741c-11ea-8a22-5ee980b272dc.png">

*Colors flushed out when scrolling*

![Kapture 2020-04-01 at 13 33 22](https://user-images.githubusercontent.com/876920/78183844-6c6a4980-741d-11ea-8689-aeb01a44baf2.gif)

VS Code version: Code - Insiders 1.44.0-insider (20b88fa0694cae8e46ffd305a1450ba58ae6065b, 2020-04-01T08:34:11.087Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
vscode-pull-request-github-insiders|Git|2020.4.911
vscode-language-pack-zh-hans|MS-|1.44.1
remote-ssh-edit-nightly|ms-|2020.3.44100
remote-ssh-nightly|ms-|2020.3.44100
js-debug-nightly|ms-|2020.3.1617
vscode-github-issue-notebooks|ms-|0.0.4
vsliveshare|ms-|1.0.1891
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8

(4 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
What does the `Developer: Inspect Editor Token Scope` hover say?
What theme is it?
Anything in your settings (in particular `editor.tokenColorCustomizations`)?

**Comment by alexdima** [comment]
Do you use `"editor.semanticHighlighting.enabled": false`. I realize now the range provider does not respect that configuration option.

**Comment by rebornix** [comment]
`editor.semanticHighlighting.enabled: true` in my setup but I'm using my now theme *Nova*. I didn't see any issue with builtin themes.

**Comment by JacksonKearl** [comment]
I see this consistently in https://github.com/microsoft/vscode/blob/88d189b4791a199137bb9da0b0c36b8c544b9683/src/vs/workbench/contrib/search/browser/search.contribution.ts with theme Noctis Lilac https://marketplace.visualstudio.com/items?itemName=liviuschera.noctis

**Comment by alexdima** [comment]
Ok, so the bug is that the document range semantic tokens provider executes on themes which did not opt in to semantic coloring. (It also doesn't respect `editor.semanticHighlighting.enabled`).
