### ISSUE TITLE
Implement interface should be prioritized over remove unused declaration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94212]
The most common scenario when this appears I imagine is when the class is just being written (like I am now), so we should prioritize implementing the interface and have it first.

![image](https://user-images.githubusercontent.com/2193314/78184717-c6b7da00-741e-11ea-9147-7a90a856ba6d.png)

**Comment by mjbvz** [comment]
Example code:
```ts
export const a = 1;

interface IFace { abc: number }

class Foo implements IFace {}
```

**Comment by jrieken** [comment]
This is back with latest insider

<img width="521" alt="Screenshot 2020-05-20 at 10 55 37" src="https://user-images.githubusercontent.com/1794099/82426830-a0aacf80-9a88-11ea-9fb1-175ab9856e88.png">
