### ISSUE TITLE
Turning off settings sync does not persist

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#94223]
- VSCode Version: 1.44.0-insiders
- OS Version: Win 10

Steps to Reproduce:

1. Turn off setting sync
2. Observe that it seems to be turned off
3. Reload the window
4. Setting sync is turned back on

[Recording](https://memes.peet.io/img/20-04-c2711fd4-ec03-4b9f-9926-e56c3a8a458a.webm)

**Comment by sandy081** [comment]
@connor4312 I cannot repro it.. Are you able to repro it consistently?

**Comment by connor4312** [comment]
I was yesterday, but can't today. Maybe it's related to https://github.com/microsoft/vscode/issues/94221, which I got consistently yesterday but this morning seems fine.

**Comment by sandy081** [comment]
ok. Closing this.
