### ISSUE TITLE
Pressing the delete key inserts a tilde instead of deleting the highlighted character.

### ISSUE THREAD

**Issue by jtagcat** [microsoft/vscode#94224]
- VSCode Version: 1.43.2
- OS Version: Fedora 32
- Shell: zsh

Steps to Reproduce:
1. Open terminal
2. Type some text
3. Move the cursor between some text
Expected:
4. Press the delete key. The highlighted character will be deleted
Actual:
4. Press the delete key. A tilde (`~`) is inserted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What keyboard layout are you using? Also can you post a screenshot?

**Comment by jtagcat** [comment]
Estonian, keyboard layout doesn't seem to matter.
Only occurs while using zsh.

**Comment by Tyriar** [comment]
I can't seem to reproduce, can you show a screenshot?

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/78525102-b2306480-77c5-11ea-9bc3-785dbfea0ae2.png)
Still not sure, how this would help.

**Comment by Tyriar** [comment]
Seems like it's a general issue with your zsh config? https://superuser.com/a/1078653/205226, https://superuser.com/a/589629/205226
