### ISSUE TITLE
TypeScrypt highlighting gets confused on lambda functions

### ISSUE THREAD

**Issue by Kelmar** [Microsoft/vscode#9422]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.3.9600

If you define a class method as an lambda function instead of the normal syntax the syntax highlight can get confused if you use Allman style braces instead of K&R bracing.

Steps to Reproduce:

1.  Create a type script file and add a class.
2. Define a method in this class using the lambda syntax with Allman indenting:
```typescript
class MyType
{
    public myFunction = (): void =>
    {
        // From this point on the syntax highlighting will be confused as to where it is.
        var myVar = 5;
        console.log("Hello there!");
    }
}
````

If you define a function with K&R style braces it works okay:
```typescript
class MyType
{
    public myFunction = (): void => {
        // Syntax highlighting is OK now? :/
        var myVar = 5;
        console.log("Hello there!");
    }
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#216
