### ISSUE TITLE
Notebook: plain text format shows the query as result

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#94237]
Testing https://github.com/microsoft/vscode/issues/93742

* Create a notebook query `label:electron $repo is:open sort desc by comments`
* Toggle plain text mode
* Output is `label:electron repo:microsoft/vscode is:open, comments sort`

![ezgif com-optimize](https://user-images.githubusercontent.com/964386/78208024-2d0d1e80-7458-11ea-86cf-1ea30db0130a.gif)

**Comment by jrieken** [comment]
Yeah, that the design. The "output" is what would be needed to insert into the GH webpage. Still, this is a little debug. I'll simply remove it

**Comment by jrieken** [comment]
I have nuked the plain-text mode now
