### ISSUE TITLE
Notebook: find doesn't search in output

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#94239]
Testing https://github.com/microsoft/vscode/issues/93742

* Create a notebook with query `label:electron $repo sort desc by reactions`
* Search for some text that is also in the cell output
* Notice results are only highlighted for text in query cell

**Comment by rebornix** [comment]
Putting it in backlog first considering its complexity.

**Comment by rebornix** [comment]
I should explain its "complexity" in details. It's not totally impossible to implement search in the webview but the catch is how many bugs or limitations it has. 

Firstly, to archive the best result, we want to let the browser to do the search other than us traverse the tree as we might not able to handle cases like `<strong>W</strong>arn`. Most modern browsers implement `window.find` https://developer.mozilla.org/en-US/docs/Web/API/Window/find but it's not standard and the browser behaviors vary.

```
window.find(aString, aCaseSensitive, aBackwards, aWrapAround,
            aWholeWord, aSearchInFrames, aShowDialog);
```

Also not every browser implements all `flags`, e.g., Firefox doesn't support `aWholeWord`. As shown in the function signature, it doesn't support regex. We can implement a simple text (with case sensitivity support) like 

```js
const resultRanges = [];
if(window.find) {
  while(window.find(query)) {
    const range = window.getSelection().getRangeAt(0);
    resultRanges.push(range);
  }
}
```

This algorithm might be good for a lot of cases but not sure how much it can cover (90%, or 50%? It depends on output renderers). The drawback of this approach is the bugs browsers currently have for `window.find`, and also some attempt to kill this API completely:

* Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=672395
* Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=695564

IMHO it's a good API to start with but we might need a champion/ambassador for it to convince the browsers that it's a good API to have for web apps.

**Comment by rebornix** [comment]
Another challenge we have is we are only rendering outputs when it become visible. It means you can't search for things which are not rendered once yet (cell input is good though), even if you know they exist.

**Comment by nicocanali** [comment]
Is there any update on this issue (since it's still open)? 😄 🙏

**Comment by rebornix** [comment]
We now support searching cell outputs.

**Comment by nicocanali** [comment]
@rebornix thanks for the update!

Do I need to do anything special to enable this? For now, nothing seems to have changed (Insiders version as well) 🤔

**Comment by RyanBlace** [comment]
![vscode_jupyter_search](https://user-images.githubusercontent.com/33130663/207199600-d8a909ab-9a11-4845-b735-145e7f3ef4d1.png)
