### ISSUE TITLE
Tracked files showing as untracked in SCM

### ISSUE THREAD

**Issue by jessbowers** [microsoft/vscode#94232]
Issue Type: <b>Bug</b>

In the file explorer there are three files that are tracked by SCM (git) but show as untracked, with a U next to them. They are not in my .gitignore file and show in the git log.

for example:

`git check-ignore .editorconfig`
outputs nothing

however the file is both Green and has a 'U'

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
better-toml|bun|0.3.2
macos-modern-theme|dav|1.6.6
xml|Dot|2.5.0
EditorConfig|Edi|0.14.4
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
markdown-table-formatter|fcr|2.0.3
elixir-ls|Jak|0.2.25
plantuml|jeb|2.13.6
docthis|joe|0.7.1
Kotlin|mat|1.7.1
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.0.0
atom-keybindings|ms-|3.0.6
Go|ms-|0.13.1
vscode-graphql|Pri|0.2.14
java|red|0.58.0
vscode-xml|red|0.10.1
rust|rus|0.7.0
scala|sca|0.3.9
metals|sca|1.8.0
crates|ser|0.4.9
markdown-preview-enhanced|shd|0.5.2
vscode-open-in-github|sys|1.13.0
vscode-mermaid-editor|tom|0.4.4
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0
vscode-icons|vsc|10.0.0
debug|web|0.24.0

</details>

**Comment by joaomoreno** [comment]
What does `git status -u` return?

**Comment by jessbowers** [comment]
```
$ git status -u
On branch dev
nothing to commit, working tree clean
```

**Comment by jessbowers** [comment]
Restarting VS Code fixes the issue.

**Comment by joaomoreno** [comment]
Does it fix it forever? Can you still reproduce?

**Comment by jessbowers** [comment]
So far so good. I am unable to reproduce.
