### ISSUE TITLE
TypeScript / Solution prompts to Common Problems [Feature Request]

### ISSUE THREAD

**Issue by xooxdoo** [Microsoft/vscode#9423]
In Visual C#, I'm very used to visual studio prompting me solutions to common problems like adding variable declarations and creating a file with a template ready to be used.

I know TypeScript is lot different than C#, these prompts speed the development process a huge bunch.

IMHO, I would love to see/use :

**PROBLEM FIXES**

1. **Undeclared variables**: if a variable is not defined prompt me to add it either as a local variable a global variable or a global variable declaration
2. **Forgotten `this`**: I wish TypeScript would stop asking me to type `this` (or make it optional :ghost:), but no I forget it all the time, would love a fast way to refactor that (one click and boom :smile:); if there is a member with that name prompt me to refactor and add it
3. **Undeclared member values**: Also, after working with pure JS, you forget that you have to declare them in TypeScript
4. **Undeclared instantiated/extended classes**: if say in `new Texture("player.png")`, `Texture` is not yet declared prompt to add an implementation or a declaration for it
5. **Undeclared implemented/extended interfaces**: if say in `interface B extends A {}` or `class C implements A`, `A` is not yet declared prompt to add an a declaration for it
6. **Undeclared callable**: you know the gist, if its a function/method call ask me to declare it
7. **Declare in a new file**: would love for **4** and **6** to add the option to declare them in a separate file, just the class declaration as default and make the template configurable globally or per project

**PS**: please make it work also with Symbols

**CODE GEN**

1. **Genarate a constructor**<sup>*</sup>
2. **Generate getters and setters**<sup>*</sup>: C# property equiv.
3. **Generate getters**<sup>*</sup>
4. **Generate setters**<sup>*</sup>
5. **Extract method**: when a statement or more are selected, add extraction utility
6. **Generate method**
7. **Generate toString**
8. **Generate [Symbol.iterator]**

<sup>*</sup>: from member declarations

**PS**: in **2** here is what I meant;

```TypeScript
private _name: string;
public get name() { return this._name; }
public set name(value: string) { this._name = value; }
```

**Comment by dbaeumer** [comment]
Moving to the TS team which would provide these features.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10139
