### ISSUE TITLE
Terminal Cursor Jumps When Clearing

### ISSUE THREAD

**Issue by travistrue2008** [microsoft/vscode#94231]
- VSCode Version: 1.43.2
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Type some commands in the terminal, so that there are a few lines of content
2. Clear the terminal (terminal clears)
3. Type some text, and then backspace/delete some of the text

Expected behavior:
The text cursor moves back one space, removing the previous character.

Actual behavior:
The text cursor jumps to the bottom of the terminal pane leaving original text on the line it jumped from. The cursor retains its horizontal position, and character buffer of the current command, except it renders blank spaces instead of characters on the new line at the bottom.

Additional information:
There's a slightly older bug filed that is identical to this: [#88508](https://github.com/microsoft/vscode/issues/88508). It was deemed a duplicate to this ticket before being closed: [#75141](https://github.com/microsoft/vscode/issues/75141). That previous issue sounded like it might be related to Python, but the issue that I'm running into seems like a more general one. I can do this just typing commands into the terminal. I've tried switching between PowerShell and WSL, switching terminal renderers, and even reinstalling VSCode with no luck. This has been an issue for me since July, 2019 (9 months ago), but it doesn't seem like many other people are. Are there any fixes that I can do on my end?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Yes this is https://github.com/microsoft/vscode/issues/75141, this is because the backend that runs the terminal for us has its own view of the world and the clear is done just in VS Code. This works fine in a regular pty but not in an emulated one that may re-print the screen or re-position the cursor explicitly.
