### ISSUE TITLE
Notebook: query with large output freezes the editor for a few seconds on linux

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#94236]
Testing https://github.com/microsoft/vscode/issues/93742

* Create notebook query `label:electron $repo sort desc by created` -> this has 873 results
* Click `show more`
* Editor is frozen until the result is populated

It looks like `show more` is trying to display all the 873 results, maybe we can throttle that ?

**Comment by jrieken** [comment]
The editor shouldn't freeze because the rendering happens in a separate process. But, yes there is no virtual rendering or anything like that. Tho, for me this works pretty well with 1000 items

**Comment by deepak1556** [comment]
https://streamable.com/j8tq4r

For example in the above demo, there is a lag when I tried to collapse the outline panel after clicking `show more` and if I try to perform scroll outside the editor area, in the explorer area.

Maybe its specific to certain window operations that bubble up to embedding frame, like scroll, resize etc.

**Comment by jrieken** [comment]
wow - me this is all instant. Can you profile this please

**Comment by rebornix** [comment]
@deepak1556 can you try profile it? I'm wondering if it's because the resize listener in the webview attempts to send out enormous resize events. Otherwise it might be an Electron issue as I didn't see at all on macOS.
