### ISSUE TITLE
Get stuck when searching in big text file

### ISSUE THREAD

**Issue by thesby** [microsoft/vscode#94233]
- VSCode Version:1.43.0
- OS Version:macbook pro 2018, os mojave

Steps to Reproduce:

1.a big text file about 11MB
2.search a string in this file, the software will get stuck about 10 seconds
3.In the previous versions, I didn't find this problem.

Does this issue occur when all extensions are disabled?: No

**Comment by thesby** [comment]
I checked the monitor, process named "Code Helper(Render)" costs more than 100% CPU

**Comment by thesby** [comment]
If I just paste the full string I want to search at once, there is not stuck. But if I input the string with one by one char, the problem appears.

**Comment by thesby** [comment]
I sampled the process using mac sample function when getting stuck:

Sampling process 78745 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling Code Helper (Renderer) (pid 78745) every 1 millisecond
Process:         Code Helper (Renderer) [78745]
Path:            /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
Load Address:    0x1097dc000
Identifier:      Code Helper (Renderer)
Version:         ???
Code Type:       X86-64
Parent Process:  Electron [78732]

Date/Time:       2020-04-02 13:07:31.166 +0800
Launch Time:     2020-03-28 22:59:46.231 +0800
OS Version:      Mac OS X 10.14.5 (18F132)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         1.0G
Physical footprint (peak):  2.5G
----

Call graph:
    1540 Thread_31421640   DispatchQueue_1: com.apple.main-thread  (serial)
    + 1537 start  (in libdyld.dylib) + 1  [0x7fff703663d5]
    + ! 1537 ???  (in Code Helper (Renderer))  load address 0x1097dc000 + 0x13a5  [0x1097dd3a5]
    + !   1537 AtomMain  (in Electron Framework) + 84  [0x10982c654]
    + !     1537 ???  (in Electron Framework)  load address 0x10982a000 + 0xb2d4a4  [0x10a3574a4]
    + !       1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x3a01629  [0x10d22b629]
    + !         1537 ???  (in Electron Framework)  load address 0x10982a000 + 0xb2ddfc  [0x10a357dfc]
    + !           1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x55963ab  [0x10edc03ab]
    + !             1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x2281957  [0x10baab957]
    + !               1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x22ad138  [0x10bad7138]
    + !                 1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x2308348  [0x10bb32348]
    + !                   1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x2309521  [0x10bb33521]
    + !                     1537 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]  (in Foundation) + 280  [0x7fff4669b8ef]
    + !                       1537 CFRunLoopRunSpecific  (in CoreFoundation) + 455  [0x7fff444378be]
    + !                         1537 __CFRunLoopRun  (in CoreFoundation) + 1189  [0x7fff44437fb5]
    + !                           1537 __CFRunLoopDoSources0  (in CoreFoundation) + 195  [0x7fff444389eb]
    + !                             1537 __CFRunLoopDoSource0  (in CoreFoundation) + 108  [0x7fff44455029]
    + !                               1537 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__  (in CoreFoundation) + 17  [0x7fff44455083]
    + !                                 1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x230897f  [0x10bb3297f]
    + !                                   1537 ???  (in Electron Framework)  load address 0x10982a000 + 0x2246d7a  [0x10ba70d7a]
    + !                                     1484 ???  (in Electron Framework)  load address 0x10982a000 + 0x2309035  [0x10bb33035]
    + !                                     : 1484 ???  (in Electron Framework)  load address 0x10982a000 + 0x22acd1a  [0x10bad6d1a]
    + !                                     :   1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x22ac784  [0x10bad6784]
    + !                                     :   | 1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x229c7f2  [0x10bac67f2]
    + !                                     :   |   1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x3653d45  [0x10ce7dd45]
    + !                                     :   |     1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x3628efb  [0x10ce52efb]
    + !                                     :   |       1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x558a20a  [0x10edb420a]
    + !                                     :   |         1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x54c547c  [0x10ecef47c]
    + !                                     :   |           1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x54dc753  [0x10ed06753]
    + !                                     :   |             1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x5589cb2  [0x10edb3cb2]
    + !                                     :   |               1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x54c604e  [0x10ecf004e]
    + !                                     :   |                 1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x4569531  [0x10dd93531]
    + !                                     :   |                   1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x4b1e30e  [0x10e34830e]
    + !                                     :   |                     1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x4565d61  [0x10dd8fd61]
    + !                                     :   |                       1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x47f116d  [0x10e01b16d]
    + !                                     :   |                         1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f2567  [0x10dc1c567]
    + !                                     :   |                           1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f2419  [0x10dc1c419]
    + !                                     :   |                             1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f32ea  [0x10dc1d2ea]
    + !                                     :   |                               1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x47f13d9  [0x10e01b3d9]
    + !                                     :   |                                 1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x44bc891  [0x10dce6891]
    + !                                     :   |                                   1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x555a20b  [0x10ed8420b]
    + !                                     :   |                                     1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x463a9a5  [0x10de649a5]
    + !                                     :   |                                       1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x448687b  [0x10dcb087b]
    + !                                     :   |                                         1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x4491f48  [0x10dcbbf48]
    + !                                     :   |                                           1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x44865c2  [0x10dcb05c2]
    + !                                     :   |                                             1482 ???  (in Electron Framework)  load address 0x10982a000 + 0x44a63aa  [0x10dcd03aa]
    + !                                     :   |                                               1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x447a2ed  [0x10dca42ed]
    + !                                     :   |                                               + 1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f8e9a  [0x10dc22e9a]
    + !                                     :   |                                               +   1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f2567  [0x10dc1c567]
    + !                                     :   |                                               +     1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x4531102  [0x10dd5b102]
    + !                                     :   |                                               +       1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f240b  [0x10dc1c40b]
    + !                                     :   |                                               +         1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f3077  [0x10dc1d077]
    + !                                     :   |                                               +           1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f783d  [0x10dc2183d]
    + !                                     :   |                                               +             1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x43f82bd  [0x10dc222bd]
    + !                                     :   |                                               +               1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x3c36585  [0x10d460585]
    + !                                     :   |                                               +                 1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x3c38199  [0x10d462199]
    + !                                     :   |                                               +                   1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x3da8454  [0x10d5d2454]
    + !                                     :   |                                               +                     1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x3c61440  [0x10d48b440]
    + !                                     :   |                                               +                       1481 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)  (in Electron Framework) + 435  [0x10ac38d53]
    + !                                     :   |                                               +                         1481 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*)  (in Electron Framework) + 206  [0x10ae30c1e]
    + !                                     :   |                                               +                           1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x16070b5  [0x10ae310b5]
    + !                                     :   |                                               +                             1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e8da38  [0x10b6b7a38]
    + !                                     :   |                                               +                               1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e8dc5a  [0x10b6b7c5a]
    + !                                     :   |                                               +                                 1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e90681  [0x10b6ba681]
    + !                                     :   |                                               +                                   1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e90681  [0x10b6ba681]
    + !                                     :   |                                               +                                     1481 ???  (in <unknown binary>)  [0x2deeeea399]
    + !                                     :   |                                               +                                       1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e90681  [0x10b6ba681]
    + !                                     :   |                                               +                                         1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e90681  [0x10b6ba681]
    + !                                     :   |                                               +                                           1481 ???  (in <unknown binary>)  [0x2deeeea399]
    + !                                     :   |                                               +                                             1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e90681  [0x10b6ba681]
    + !                                     :   |                                               +                                               1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e90681  [0x10b6ba681]
    + !                                     :   |                                               +                                                 1481 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e90681  [0x10b6ba681]
    + !                                     :   |                                               +                                                   1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x1f65618  [0x10b78f618]
    + !                                     :   |                                               +                                                   ! 1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x1e9128d  [0x10b6bb28d]
    + !                                     :   |                                               +                                                   !   1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x3d8a999  [0x10d5b4999]
    + !                                     :   |                                               +                                                   !     1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x43db8e8  [0x10dc058e8]
    + !                                     :   |                                               +                                                   !       1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x43bb8cf  [0x10dbe58cf]
    + !                                     :   |                                               +                                                   !         1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x43bba1d  [0x10dbe5a1d]
    + !                                     :   |                                               +                                                   !           1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x45d86ba  [0x10de026ba]
    + !                                     :   |                                               +                                                   !             1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x45dfedb  [0x10de09edb]
    + !                                     :   |                                               +                                                   !               1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x49c1a88  [0x10e1eba88]
    + !                                     :   |                                               +                                                   !                 1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48ec39f  [0x10e11639f]
    + !                                     :   |                                               +                                                   !                   1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x49c190e  [0x10e1eb90e]
    + !                                     :   |                                               +                                                   !                     1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48fad4f  [0x10e124d4f]
    + !                                     :   |                                               +                                                   !                       1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48ee4dc  [0x10e1184dc]
    + !                                     :   |                                               +                                                   !                         1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48eff6b  [0x10e119f6b]
    + !                                     :   |                                               +                                                   !                           1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48f0376  [0x10e11a376]
    + !                                     :   |                                               +                                                   !                             1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48ec39f  [0x10e11639f]
    + !                                     :   |                                               +                                                   !                               1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48fada8  [0x10e124da8]
    + !                                     :   |                                               +                                                   !                                 1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48fa87e  [0x10e12487e]
    + !                                     :   |                                               +                                                   !                                   1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x491ccf8  [0x10e146cf8]
    + !                                     :   |                                               +                                                   !                                     1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x4921d51  [0x10e14bd51]
    + !                                     :   |                                               +                                                   !                                       1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x4922378  [0x10e14c378]
    + !                                     :   |                                               +                                                   !                                         1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x491813e  [0x10e14213e]
    + !                                     :   |                                               +                                                   !                                           1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48f55d2  [0x10e11f5d2]
    + !                                     :   |                                               +                                                   !                                             1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48f36ed  [0x10e11d6ed]
    + !                                     :   |                                               +                                                   !                                               1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48f510c  [0x10e11f10c]
    + !                                     :   |                                               +                                                   !                                                 1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x491810e  [0x10e14210e]
    + !                                     :   |                                               +                                                   !                                                   1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48f55d2  [0x10e11f5d2]
    + !                                     :   |                                               +                                                   !                                                     1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48f3701  [0x10e11d701]
    + !                                     :   |                                               +                                                   !                                                       1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x48f4523  [0x10e11e523]
    + !                                     :   |                                               +                                                   !                                                         1400 ???  (in Electron Framework)  load address 0x10982a000 + 0x49af413  [0x10e1d9413]
    + !                                     :   |                                               +                                                   !                                                           1323 ???  (in Electron Framework)  load address 0x10982a000 + 0x49b0b1d  [0x10e1dab1d]
    + !                                     :   |                                               +                                                   !                                                           : 1316 ???  (in Electron Framework)  load address 0x10982a000 + 0x3f477ad  [0x10d7717ad]
    + !                                     :   |                                               +                                                   !                                                           : | 1310 ???  (in Electron Framework)  load address 0x10982a000 + 0x3f5b334  [0x10d785334]
    + !                                     :   |                                               +                                                   !                                                           : | + 1305 ???  (in Electron Framework)  load address 0x10982a000 + 0x3f72cc4  [0x10d79ccc4]
    + !                                     :   |                                               +                                                   !                                                           : | + ! 1305 ???  (in Electron Framework)  load address 0x10982a000 + 0x3f5b173  [0x10d785173]
    + !                                     :   |                                               +                                                   !                                                           : | + !   1155 ???  (in Electron Framework)  load address 0x10982a000 + 0x3f5af67  [0x10d784f67]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : 938 ???  (in Electron Framework)  load address 0x10982a000 + 0x3f5fae8  [0x10d789ae8]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | 538 ???  (in Electron Framework)  load address 0x10982a000 + 0x3f5f191  [0x10d789191]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + 518 ???  (in Electron Framework)  load address 0x10982a000 + 0x5aed7e  [0x109dd8d7e]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + ! 518 ???  (in Electron Framework)  load address 0x10982a000 + 0x5aeb14  [0x109dd8b14]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   233 ???  (in Electron Framework)  load address 0x10982a000 + 0x5a99be  [0x109dd39be]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : 227 ???  (in Electron Framework)  load address 0x10982a000 + 0x574982  [0x109d9e982]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | 128 ???  (in Electron Framework)  load address 0x10982a000 + 0x5751b8  [0x109d9f1b8]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + 81 ???  (in Electron Framework)  load address 0x10982a000 + 0x5852d9  [0x109daf2d9]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! 59 ???  (in Electron Framework)  load address 0x10982a000 + 0x5853bf  [0x109daf3bf]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 35 ???  (in Electron Framework)  load address 0x10982a000 + 0x585af5  [0x109dafaf5]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 5 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fcd2  [0x109d69cd2]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | + 2 ???  (in Electron Framework)  load address 0x10982a000 + 0x57d280  [0x109da7280]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | + 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x57d270  [0x109da7270]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | + 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x57d277  [0x109da7277]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | + 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x57d282  [0x109da7282]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 4 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fe3f  [0x109d69e3f]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 3 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd13  [0x109d69d13]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 3 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd74  [0x109d69d74]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 2 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fc96  [0x109d69c96]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 2 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd1c  [0x109d69d1c]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fc9d  [0x109d69c9d]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fc9e  [0x109d69c9e]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fca3  [0x109d69ca3]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fca5  [0x109d69ca5]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fcb7  [0x109d69cb7]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fcbd  [0x109d69cbd]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fcc6  [0x109d69cc6]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fcd2  [0x109d69cd2]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd0d  [0x109d69d0d]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd17  [0x109d69d17]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd24  [0x109d69d24]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd34  [0x109d69d34]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fd77  [0x109d69d77]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fe45  [0x109d69e45]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fe46  [0x109d69e46]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : | 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x53fe4e  [0x109d69e4e]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 3 ???  (in Electron Framework)  load address 0x10982a000 + 0x585b99  [0x109dafb99]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 2 ???  (in Electron Framework)  load address 0x10982a000 + 0x585871  [0x109daf871]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 2 ???  (in Electron Framework)  load address 0x10982a000 + 0x5858dd  [0x109daf8dd]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 2 ???  (in Electron Framework)  load address 0x10982a000 + 0x5858fe  [0x109daf8fe]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 2 ???  (in Electron Framework)  load address 0x10982a000 + 0x585b92  [0x109dafb92]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x58587a  [0x109daf87a]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x585899  [0x109daf899]
    + !                                     :   |                                               +                                                   !                                                           : | + !   : | + !   : | + ! : 1 ???  (in Electron Framework)  load address 0x10982a000 + 0x5858b0  [0x109daf8b0]
Sample analysis of process 78745 written to file /dev/stdout

**Comment by alexdima** [comment]
@thesby Can you please share the regex that caused this? It might be a combination of the regex / file contents that triggers this behaviour.

**Comment by thesby** [comment]
I just search a timestamp "1585614866", and the regex function in search window is turned off

**Comment by thesby** [comment]
Actually, whatever I input in search window, the problem always occurs

**Comment by thesby** [comment]
Maybe the search program gets one char I input, and it gets stuck for a while. When it returns the result, but the input has changed, and it search again. So the program searches many times, I guess. It should interupt the previous search at once when I changes the search content.

**Comment by alexdima** [comment]
@thesby I cannot reproduce this. I have created a file that contains `1585614866` very many times such that it occupies 19MB:

[test.zip](https://github.com/microsoft/vscode/files/4421028/test.zip)

I then search for 1585614866 and VS Code works fine for me:
![image](https://user-images.githubusercontent.com/5047891/78249422-9b9cbb80-74ee-11ea-96e2-8670cb3dbd37.png)

**Comment by alexdima** [comment]
Are you by any chance using Search in Files ?

**Comment by thesby** [comment]
No, I just search in  one file.

**Comment by thesby** [comment]
And I diasables all plugins, the problems still occurs.

**Comment by alexdima** [comment]
@thesby I am sorry, I cannot reproduce with the given steps. Does it reproduce for you when opening the file I attached above and searching in that file?

**Comment by thesby** [comment]
I tried your file, no stuck.

**Comment by thesby** [comment]
Generate data using python:
```python
import numpy as np
data = np.random.uniform(-2, 2, (1024, 1024)).reshape((-1, ))
data_str = ','.join([str(x) for x in data])
with open('data.txt') as fid:
    fid.write(data_str)
````
Open the file `data.txt`, vs code will stuck on my computer unitl mac os reminds me "The window is no longer responding, you can reopen or close window or keep waiting"

**Comment by thesby** [comment]
I think it's really unnecessary to search while I am inputting. Starting search after I input all text and press enter will be better

**Comment by alexdima** [comment]
I can reproduce. This has to do with having a very long line which has a find match.

@isidorn 

To reproduce, open this file -- [data.txt.zip](https://github.com/microsoft/vscode/files/4531715/data.txt.zip) -- and open the find widget (cmd+f) and type `1`. VS Code will freeze (for about 2 minutes on my machine).

If I comment out [this line](https://github.com/microsoft/vscode/blob/4862602c4c3a14de76e24898c4d94a79210f7356/src/vs/editor/contrib/find/findWidget.ts#L425), then the freeze does not happen.

The root cause is that we use `getLineContent` and we put that unbounded in any way in the DOM for the aria label. In this case, the line is about 15MB, which causes the browser to freeze while doing the layout for the aria alert dom node. I think we should do some `substr` on the line content around the find match or something like that to reduce the aria alert size.

**Comment by isidorn** [comment]
@alexdima sorry about this! As you suggest I think we can tackle this on the aria alert side, since no user will listen to 15mb of text being read out. Thus all alerts should have a cap before they are put in the DOM.

**Comment by isidorn** [comment]
I can reproduce the issue with the file you attached.
I have tuned the lenght to 20000, since on my machine it is pretty responsive for that length and I think that is long enough that no user would want to hear a message that long.
If users complain we can always fine tune the number.
