### ISSUE TITLE
inspect does not return workspaceFolderValue

### ISSUE THREAD

**Issue by Almenon** [microsoft/vscode#94241]
- VSCode Version: 1.43.2
- OS Version: Win10

Steps to Reproduce:

1. set a setting at the folder level for an extension. I used python.

https://i.imgur.com/lEgvBcO.png
https://i.imgur.com/NxOnNJZ.png
https://i.imgur.com/dt2kGUn.png

2. try to read it with the API:
```typescript
const otherExt = "python"
const setting = "pythonPath"
const otherExtensionSettings = vscode.workspace.getConfiguration(otherExt, null)
const otherSetting = otherExtensionSettings.get<T>(setting)
console.log(otherSetting)
```

Expected result: folder value appears
Actual result: workspace/user value appears!

You can also use inspect to see that the folder value is not present for some reason
https://i.imgur.com/qvx7GJG.png

This problem might be related to https://github.com/microsoft/vscode/issues/31576

Does this issue occur when all extensions are disabled?: N/A

**Comment by sandy081** [comment]
You should pass the resource for which you are looking the configuration for to the api 

`vscode.workspace.getConfiguration(otherExt, resource)`

**Comment by Almenon** [comment]
@sandy081 Thanks, that does work for getting the workspace folder level configuration 👍 . 

However, there is also a bug with inspect. Inspect, as per the API, should retrieve all information, thus including workspacefolder level configuration. See https://i.imgur.com/qvx7GJG.png

**Comment by sandy081** [comment]
@Almenon do you have value set in the folder settings?

**Comment by Almenon** [comment]
@sandy081 yes. Please see first picture in my original post.

**Comment by sandy081** [comment]
Are you passing the `resource` value ?

**Comment by Almenon** [comment]
Oh right, same issue. Nevermind
