### ISSUE TITLE
Revisit allowing to collapse all views

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94249]
I find this especially weird in the panel:

![image](https://user-images.githubusercontent.com/900690/78215828-c0763c00-74b8-11ea-85e9-cc48223a74e8.png)

//cc @misolori

**Comment by misolori** [comment]
We did talk about potentially using icons in this case but not sure if this is any better:

![image](https://user-images.githubusercontent.com/35271042/78270669-fe2a9300-74bf-11ea-8b78-c83ca77dd7a2.png)

and vertically feels like it changes the aesthetics a lot:

![image](https://user-images.githubusercontent.com/35271042/78270757-1a2e3480-74c0-11ea-8e8d-12b9fc38dbd2.png)

I still the think the original idea is better (though we're waiting on a Chromium fix):
![image](https://user-images.githubusercontent.com/35271042/78271101-9fb1e480-74c0-11ea-9645-0443d2833dad.png)

So I'd opt for not allowing these to be collapsed in the meantime.

**Comment by bpasero** [comment]
Yeah my point was actually to always keep one view expanded. Even in the sidebar I am not seeing the advantage of collapsing all views...

**Comment by joaomoreno** [comment]
> and vertically feels like it changes the aesthetics a lot:
> 
> ![image](https://user-images.githubusercontent.com/35271042/78270757-1a2e3480-74c0-11ea-8e8d-12b9fc38dbd2.png)

I kinda like this!

**Comment by bpasero** [comment]
I think we are now talking about 2 things that are unrelated:
* how to represent collapsed views when in panel
* wether to allow to collapse all views or not

For 1) I like anything better than what we have today where we reserve space and thus the view is not fully collapsed. 

For 2) I would like to discuss this further why we support this in the first place.

**Comment by joaomoreno** [comment]
Merging with https://github.com/microsoft/vscode/issues/96584
