### ISSUE TITLE
Align drop feedback between views and editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94248]
Close this if this is already the case, but please check: the drop feedback when dragging views should imho look identical to editors in all theme variants. I think we support to set a color via theming (`EDITOR_DRAG_AND_DROP_BACKGROUND`) and it should use the same base color. 

![Kapture 2020-04-02 at 8 01 38](https://user-images.githubusercontent.com/900690/78215696-670e0d00-74b8-11ea-8816-1e451ae79c64.gif)

**Comment by sbatten** [comment]
same theme color is being used, thanks
