### ISSUE TITLE
Dark+ (default dark) Theme with Typescript type on multi lines issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9424]
- VSCode Version: 1.4.0-insider
- OS Version: OSX

Steps to Reproduce:

1. 
2. 
![image](https://cloud.githubusercontent.com/assets/1723815/16905168/ebad9906-4c6f-11e6-942a-2676e2b220c2.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#231
