### ISSUE TITLE
VSCode for Android tablet or desktop mode

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode#94243]
I have a Huawei Mate 20. It's EMUI 10 Desktop mode works great on monitor after docking via type-C port. I can browse in Microsoft Edge. I can SSH using Termius. I can get on Slack/Gitter to chat with other developers. I can use Microft Office suite which is intensively optimized for Desktop mode.

You know what's missing? An IDE. Now since VSCode allows remote coding via SSH remote extension. I wonder if it is feasible to port VSCode to Android desktop mode so that I don't really have to carry a laptop around all the time.

**Comment by tigerinus** [comment]
https://iphoneparadise.com/2020/04/20/xcode-may-be-coming-to-the-iphone-and-ipad-very-soon/

The game has just become more serious. 😸

**Comment by yume-chan** [comment]
See electron/electron#562.

While Electron has no plan to support Android (and iOS), it's impossible to run full Code on your mobile devices.

However you can try with Visual Studio Online, with the self-host mode. I had a success running it on Chrome for Android.

**Comment by tigerinus** [comment]
> See [electron/electron#562](https://github.com/electron/electron/issues/562).
> 
> While Electron has no plan to support Android (and iOS), it's impossible to run full Code on your mobile devices.
> 
> However you can try with Visual Studio Online, with the self-host mode. I had a success running it on Chrome for Android.

OK, fine... 🤦

**Comment by realsarm** [comment]
I guess that's an awesome feature ✨

**Comment by sana-ajani** [comment]
Hi, thanks for creating the issue. We have recently created Linux ARM builds, which can work on Chromebooks and Raspberry Pi. Unfortunately, supporting Android and publishing an APK is too out of scope for us.

**Comment by tigerinus** [comment]
To everyone interested in bringing VSCode around with your mobile device, you can consider postmarketOS which rips Android off from your tablet and replaces it with Linux (+GUI). If you happen to have an Android tablet with a keyboard, you are in luck.

**Comment by tigerinus** [comment]
> Hi, thanks for creating the issue. We have recently created Linux ARM builds, which can work on Chromebooks and Raspberry Pi. Unfortunately, supporting Android and publishing an APK is too out of scope for us.

Would you consider [this approach](https://dev.to/codeledger/how-to-get-visual-studio-code-to-run-in-termux-on-android-405j) to get VSCode running on tablets?
