### ISSUE TITLE
Allow customize the window title separator

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#94254]
The separator in `window.title` is a em dash but I would like to use my own "◆". Can I make a PR to add this?

**Comment by bpasero** [comment]
Why is this needed, can't you just define the full window title including your separator?

**Comment by muuvmuuv** [comment]
Yes but it will not make use of the "if clause" the separator variable provides. So it is only active if both variables, left and right, are present.

When I do that:

```
${remoteName} ◆ ${rootName} ◆ ${activeEditorMedium} ${dirty}
```

It results in:

```
◆ project ◆ package.json
```

Sorry I thought that would be clear. My bad.

**Comment by bpasero** [comment]
Makes sense. So this could be a setting where the value of the title separator can be defined as string?

**Comment by muuvmuuv** [comment]
Yes, that is what I was looking for. I can make a PR if I get some time today. 

I guess this is just finding where `window.title` is defined and add `window.titleSeparator` as `string` and place it at the line where the separator is defined?

**Comment by bpasero** [comment]
Yeah if you sketch something up we can talk about it in the PR.

**Comment by bpasero** [comment]
**Verify** using the new `window.titleSeparator` setting.
