### ISSUE TITLE
Unable to start VS Code Periodically

### ISSUE THREAD

**Issue by AvronNet** [microsoft/vscode#94255]
- VSCode Version: 1.43.0 or 1.43.1
- OS Version: Windows 10

Steps to Reproduce:

1. Use VS Code for months, install updates normally...
2. After a random restart of my machine i get 
![image](https://user-images.githubusercontent.com/8115899/78219377-b0ae2600-74bf-11ea-9a1d-42e0222a589b.png)
VS Code will not start at all, and the folder that the error is targeting does not exist on my machine.

This happened to me at least 4 time up until now. It forces me to uninstall VS Code completly and reinstall it. The irritating thing is that I have to set up my work environment from scratch each time and it takes at least 2-3 hours out of my work day.

Note: I postponed the latest VS Code update for a week maybe... could be related to the update check that fails and after that breaks something in the app or deletes the folder from the errror.

Please fix this
Possible similar issues #90447,  #92967

Does this issue occur when all extensions are disabled?: No

**Comment by AvronNet** [comment]
Update... I'm happy to say that this time... after uninstall and reinstall of newer version my environment setup persisted. So at least I didn't lose time on installing and configuring my plugins.

**Comment by joaomoreno** [comment]
Got it. If it fails again, you might want to disable background updates with `update.enableWindowsBackgroundUpdates` set to `false.`
