### ISSUE TITLE
Windows: Window dimensions are off when switching from HiDPI to regular DPI

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#94257]
Electron seems to mis-calculate the actual window size, when I switch from my HiDPI laptop screen to an external 1:1 DPI screen. This is visible when maximizing the window:

![image](https://user-images.githubusercontent.com/22350/78223726-a859e900-74c7-11ea-9dd6-6f37a223e380.png)

Notice the crop at the left and bottom. Creating new windows doesn't fix the issue.

Only restarting VS Code does the trick:

![image](https://user-images.githubusercontent.com/22350/78223742-b0198d80-74c7-11ea-97fe-641f568f8001.png)

This might happen only on custom titlebar, didn't try native yet.

@bpasero  @deepak1556 I wonder if this is known?

**Comment by deepak1556** [comment]
Yeah this is an issue with custom titlebar, native should workaround it for now. I plan to look at it next iteration.

/duplicate https://github.com/microsoft/vscode/issues/85592
