### ISSUE TITLE
Notebook themeing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94253]
Please do not forget to remove references to the theme (`vs-dark`) from CSS files, e.g. here:

https://github.com/microsoft/vscode/blob/d8e3cca049b1baa317ab9ef0d3f673b08e53d8fa/src/vs/workbench/contrib/notebook/browser/notebook.css#L373

Colors need to be themable.

**Comment by rebornix** [comment]
They are removed now as we don't actually use them. Will make sure they are customizable when we are polishing markdown previews in notebook.
