### ISSUE TITLE
'F' key not working

### ISSUE THREAD

**Issue by prateekj73** [microsoft/vscode#94250]
Issue Type: <b>Bug</b>

whenever iam using F key in any of my python files, there's a message below that 'F' is pressed waiting for other key..but it is not getting typed..Why is it so?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (0.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.2.64397

</details>

**Comment by alexdima** [comment]
@prateekj73 You might have created a chord keybinding that begins with `F`. Please check your `keybindings.json` file and remove any entries that are not necessary (`F1 > Open keyboard shortcuts (JSON)`)
