### ISSUE TITLE
'editor.suggest.showUsers' cannot be used as a language specific setting

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#94251]
pls see the screenshot below

![image](https://user-images.githubusercontent.com/172399/78218380-fa960c80-74bd-11ea-91d1-4363b0be44fb.png)

**Comment by jrieken** [comment]
@egamma that file looks a lot like TypeScript - despite the python icon.

**Comment by egamma** [comment]
@jrieken I've changed the language mode manually, pls see the language mode in the bottom right corner.

**Comment by jrieken** [comment]
Hm, still doesn't reproduce for me...

[Apr-17-2020 11-31-28.gif.zip](https://github.com/microsoft/vscode/files/4492070/Apr-17-2020.11-31-28.gif.zip)
