### ISSUE TITLE
Error in opening files with spaces

### ISSUE THREAD

**Issue by vishal5677** [microsoft/vscode#94256]
Issue Type: <b>Performance Issue</b>

I am using vscode to program in c language, but i always gets error files or directory not found whenever i run a file with space in its name. I think earlier it was all good but by mistake i might have changed some configurations. so please help me fixing the issue.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    73	  3524	code main
    0	   332	  1844	   gpu-process
    0	   244	  3796	   window (finding substring.cpp - dATA STRUCTURES - Visual Studio Code)
    0	     5	  8168	     console-window-host (Windows internal process)
    0	     6	 11392	     console-window-host (Windows internal process)
    0	    79	 11980	     C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   115	 15632	     extensionHost
    0	    28	  8936	       c:\Users\vishal567795\.vscode\extensions\ms-vscode.cpptools-0.27.0\bin\cpptools.exe
    0	    10	  4424	         console-window-host (Windows internal process)
    0	    12	  8456	         "c:\Users\vishal567795\.vscode\extensions\ms-vscode.cpptools-0.27.0/bin/cpptools-srv.exe" 8936 5
    0	    16	 18260	         "c:\Users\vishal567795\.vscode\extensions\ms-vscode.cpptools-0.27.0/bin/cpptools-srv.exe" 8936 2
    0	    30	 14520	       electron_node server.js 
    0	    55	 18032	       "C:\Users\vishal567795\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\vishal567795\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=15632
    0	    50	 16900	     C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    12	 17412	     watcherService 
    0	     6	 17428	       console-window-host (Windows internal process)
    0	    42	 17860	     searchService
    0	    65	  4048	   window (Issue Reporter)
    0	    26	 15612	   utility
    0	    13	 16936	   electron-crash-reporter
    0	    71	 17596	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (finding substring.cpp - dATA STRUCTURES - Visual Studio Code)
|    Folder (dATA STRUCTURES): 23 files
|      File types: exe(8) c(7) cpp(4) json(3)
|      Conf files: launch.json(1) tasks.json(1) settings.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
vscode-pfw|Bis|1.0.2
c-cpp-compile-run|dan|1.0.7
algorithm-mnemonics-vscode|dav|1.0.3
vscode-eslint|dba|2.1.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.20.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
code-runner|for|0.9.17
CppSnippets|har|0.0.14
vscode-gnu-global|jay|0.3.2
file-ext-switcher|Joh|3.2.0
clangcomplete|kub|1.0.1
ccpp-extension-pack|Leo|0.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-clang|mit|0.2.3
python|ms-|2020.3.71113
cpptools|ms-|0.27.0
LiveServer|rit|5.6.1
ionic-switch|shi|0.0.2
eco|th7|0.0.2
syntax-highlighting-for-html-template|vil|0.0.1
clang-format|xav|1.9.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
