### ISSUE TITLE
Where to ask architecture based questions?

### ISSUE THREAD

**Issue by Alanz2223** [Microsoft/vscode#9425]
I am sorry for possibly posting this at the wrong place. I would like to extend vscode, however I have a few questions related to its architecture. Do you guys have a slack or similar soft Q-A account? Stackoverflow is very strict on asking soft questions without well defined answers which is why I have come here.

I specifically want to know the way intellisense provides suggestions, and which files I should be interested in.

**Comment by weinand** [comment]
@Alanz2223 please ask here. 
I assume that you have seen the section `CompletionItemProvider` in https://code.visualstudio.com/docs/extensionAPI/vscode-api

**Comment by Alanz2223** [comment]
I have reviewed it but did not find anything relating to parameter hints. Do you know how comments have to be formatted so that they will appear when a suggestion is highlighted?

https://code.visualstudio.com/docs/editor/editingevolved#_parameter-hints

**Comment by kieferrm** [comment]
@Alanz2223 as an extension writer you can register a `SignatureHelpProvider`. They are responsible for showing the parameter hints.

That best way to deeply explore our API is to look at `vscode.d.ts` either in github or in the workspace you use to develop your extension. If you generated your extension with [yeoman](https://code.visualstudio.com/docs/tools/yocode), you can find the file in `node_modules/vscode`.
