### ISSUE TITLE
Task picker: returns separators as result even for no results

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94262]
I added infrastructure to show a label "No task match" when no results are returned from the quick pick and it does not work for the tasks picker because you seem to be returning still 2 picks with are of `kind: separator`. Would be great if separators could only be returned if there are actually picks.

**Comment by bpasero** [comment]
Alternatively you could just always return the "Show All Tasks" entry if none match.

**Comment by alexr00** [comment]
@bpasero is this when there is filter text and no matches, or the quick pick has no entries without filter text? If it's the latter, how do you get it to have no entries?

**Comment by bpasero** [comment]
@alexr00 I typed long enough so that no task would match the query
