### ISSUE TITLE
how to use acquireVsCodeApi post message in iframe ?

### ISSUE THREAD

**Issue by specialgirlgotoheaven** [microsoft/vscode#94266]
- VSCode Version:1.43.0
- OS Version:10.14.6

Steps to Reproduce:

1.
```
const panel = vscode.window.createWebviewPanel(
                'mues',
                'mues平台',
                vscode.ViewColumn.Three,
                {
                  enableScripts: true
                }
              );
              panel.webview.html = getWebviewContent();
    function getWebviewContent(){
     return '<!DOCTYPE html >
        <html lang="en">
        <head>
        <head>
      </head>
      <body>
          <iframe class="vscode-light" id= "iframetest" width="100%" height="100%" src="http://remote.yx.mail.netease.com:9500/muses/index.html#/resource/list" frameborder="0" >
          </iframe>
      </body>
      </html>;
    }
```
2.the webpage---`http://remote.yx.mail.netease.com:9500/muses/index.html#/resource/list`  is working for local html
3.Use  iframe to load the page In webview. The acquireVsCodeApi function is undefined. But it's ok with html string directly.

Does this issue occur when all extensions are disabled?: Yes

this question is same as `vscode.postMessage bug? #89694`https://github.com/microsoft/vscode/issues/89694

**Comment by mjbvz** [comment]
`acquireVsCodeApi` is intentionally only available in webview html itself, not globally in any page it loads.

If your webview wants to post a message from an iframe back to your extension, you should:

1. In the iframe, post a message to your outer webview
1. In the outer webview, forward the message back to VS Code using `vscode.postMessage`

**Comment by specialgirlgotoheaven** [comment]
"In the iframe, post a message to your outer webview" 
---use http request to post the message? Is there any other method?

**Comment by specialgirlgotoheaven** [comment]
> `acquireVsCodeApi` is intentionally only available in webview html itself, not globally in any page it loads.
> 
> If your webview wants to post a message from an iframe back to your extension, you should:
> 
> 1. In the iframe, post a message to your outer webview
> 2. In the outer webview, forward the message back to VS Code using `vscode.postMessage`

"In the iframe, post a message to your outer webview"
---use http request to post the message? Is there any other method?
