### ISSUE TITLE
VS Code eats terminal keyboard shortcuts

### ISSUE THREAD

**Issue by sportshead** [microsoft/vscode#94268]
- VSCode Version: 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94)
- OS Version: macOS 10.15.1

# Expected
VS Code to not eat keyboard shortcuts that start with <kbd>Ctrl</kbd> as it is used for the terminal often.

# Actual
VS Code eats keyboard shortcut

Steps to Reproduce:

1. Open terminal
2. Press <kbd>Ctrl</kbd><kbd>P</kbd><kbd>Ctrl</kbd><kbd>Q</kbd>
3. Observe how VS Code eats <kbd>Ctrl</kbd><kbd>Q</kbd>.

Does this issue occur when all extensions are disabled?: Yes

Possibly related: #24002

**Comment by sh7dm** [comment]
For me it does even the `Ctrl`+`P`

**Comment by gjsjohnmurray** [comment]
Is this cause by the `terminal.integrated.commandsToSkipShell` setting and its default values? See https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

**Comment by Tyriar** [comment]
There is also the `terminal.integrated.allowChords` setting now, this improved in the upcoming version I believe to cover this case.
