### ISSUE TITLE
Symbol icons could be so much more helpful

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#94263]
I've been using VS Code extensively for more than a year now, and I must say I still don't know the meaning of symbol icons:

![VS_icons](https://user-images.githubusercontent.com/1711539/78226262-bf023f00-74cb-11ea-9b1c-00d951238bf0.png)

IE, the only useful info that these icons convey me is that some symbols are of different kind. 

In contrast, IntelliJ's much simpler icons have a very clear meaning, even if you haven't used IntelliJ a lot:

![IJ_icons](https://user-images.githubusercontent.com/1711539/78226255-bdd11200-74cb-11ea-94cc-857c2e4db6dd.png)

`f` is field, `C` is class, `m` is method, `E` is enum, etc... 

I wish VS Code used such letter mnemonic scheme as well, it seems more useful for new and expert users alike. 

https://www.jetbrains.com/help/idea/symbols.html#
https://www.jetbrains.com/help/clion/icons-and-symbols.html#

**Comment by misolori** [comment]
These icons come from Visual Studio and we've had them from the beginning. I understand that some icons might not be useful/meaningful, but we are currently working on allowing extensions to provide their own custom icons to use throughout VS Code (see #92791) and I think this will help address this issue. Icons are subjective and what works for you might not work for others (and vice versa).

**Comment by matklad** [comment]
Subscribed to #92791, I believe it indeed can solve this issue in practice, thanks! 

Still, I'd like to push back a little against

> Icons are subjective and what works for you might not work for others

This is undoubtedly true, but I feel there's a meaningful fundamental difference between purely graphical icons, and mnemonics-based icons. And my gut feeling tells that significantly more people will intuitively understand mnemonics-based one. Which, naturally, doesn't mean that this benefit outweighs, eg, the benefits of not changing anything.

**Comment by misolori** [comment]
> Which, naturally, doesn't mean that this benefit outweighs, eg, the benefits of not changing anything.

This will likely be the biggest hurdle to changing the default. A good majority of users switch between VS and VS Code and this continuity is highly appreciated. So if the default ever changed it would affect a large majority. That's not to say we'd never change it, last year we did a [major icon overhaul](https://github.com/microsoft/vscode/issues/8017) that diverged from VS. But I honestly don't see us changing the default for symbol icons and is why we're open to allowing to change all the icons based on user preference.

@jrieken any thoughts?

**Comment by jrieken** [comment]
I understand both side - I can also not "understand" those icons but see that folks are used to them, likely for decades. Therefore I am also a little afraid to change the default, but we could ship an alternative, more logical, set out of the box and encourage users to try it. Personally, I have solved this problem like so: `"editor.suggest.showIcons": false`

**Comment by kjeremy** [comment]
The two concepts could always be combined. A small offset letter may be a nice complement to the current icon set.

**Comment by misolori** [comment]
I'll leave this up and see what the community thinks, will mark this as a backlog candidate.

**Comment by Shirsendu-Bairagi** [comment]
Definitely it will help

**Comment by kraistt** [comment]
I'll make a poorly sourced estimate that most of the users that use VSCode never or at least not continuously used Visual Studio; it will be great to have a default set (the current ones) and a more mnemonic set of icons as alternative.
