### ISSUE TITLE
HTML ISSUES 

### ISSUE THREAD

**Issue by Roobetterbeliveit** [microsoft/vscode#94264]
Issue Type: <b>Bug</b>

ALL  HTML INDEX MY CODE IS GONE, AGAIN!!!!!!!!!!!!!!!!!!!!!,why does keep on happening an how can i get it back???

The file has been working fine for the last two months, all i did today was right click on it to open it with code , when it did open it was completely blank. I opened the CSS and Java files they were completely fine but the index.html file is completely blank, once would be bad but this is the second time within a year it's done this, I'm probably partially to blame for not backing up the file after the first time, but irrespective of that this is all pretty inconvenient considering I'm on a tight deadline. 

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|23.80GB (19.02GB free)|
|Process Argv|D:\Web development\Project\HTML Files\index.re-up.html|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by Roobetterbeliveit** [comment]
> /needsMoreInfo
> 
> Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

I've done that , any help in fixing my problem?

**Comment by jrieken** [comment]
> I've done that

No - you have not updated the issue so that we can reproduce it nor follow what happened. How about some log files?

**Comment by Roobetterbeliveit** [comment]
I have updated the issue, I'm not quite sure what  you mean by log files?
Do you mean the original HTML index file?

**Comment by jrieken** [comment]
closing as not actionable
