### ISSUE TITLE
Inability to use snippet with snippetSuggestions set to false

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9426]
- VSCode Version: 1.4.0-insider
- OS Version: OSX

Steps to Reproduce:

1. Set `"editor.snippetSuggestions": false,`
2. Type snippet command that you know and try to use that snippet

Snippet does not show up in the suggestions box but one should be able to use it (like user could dismiss suggestion box if any is shown and hit Tab or something like that to use the snippet)

**Comment by jrieken** [comment]
Unsure if you are on an insider version which is done but `false` is not a valid value for that setting. It must be like this:

```
	/**
	 * Enable snippet suggestions. Default to 'true'.
	 */
	snippetSuggestions?: 'top' | 'bottom' | 'inline' | 'none';
```

and when set to `none` (the semantic equivalent to `false`) it means never ever show snippet suggestions, so do not expect them to show in the box
