### ISSUE TITLE
Shift+Enter doesn't insert suggestion when in notebook

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94270]
* open GH notebook
* trigger suggest like so (| is the cursor): `a|uthor:@me`
* shift+enter to insert with replace
* 🐛 cell changes

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode/issues/93099

**Comment by roblourens** [comment]
@rebornix should all of these that run in the editor use EditorContrib weight?
