### ISSUE TITLE
Cannot download OmniSharp

### ISSUE THREAD

**Issue by TheBlueSky** [Microsoft/vscode#9427]
Hello everyone,

I'm not sure if this is a VS Code or OmniSharp issue, so feel free to move it to the right repository if necessary.

When I open a .Net project, I get the following in Output window:

    [INFO] Starting OmniSharp at 'c:\Users\xyz\Documents\My Web Sites\SomeProject'...
    [INFO] Installing to C:\Users\xyz\.vscode\extensions\ms-vscode.csharp-1.2.2\.omnisharp
    [INFO] Attempting to download omnisharp-1.9-beta11-win-x64-net451.zip...

And it gets stuck there. Nothing is downloaded and my project doesn't have any kind of Intellisense (obviously).

Maybe this is relevant, and maybe not, but at work, we are behind a firewall and a proxy server (from Fortinet) that does strange stuff. One of which is using its own certificate for all HTTPS requests, which I faced an issue with when using an application that require a valid  certificate signed by trusted CA, or an application that uses certificate pinning technique.

- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Go behind our proxy.
2. Open a .Net project :)

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#579
