### ISSUE TITLE
[semantic highlighting] Don't color Math as a library.variable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#94275]
Refs: https://github.com/microsoft/vscode/issues/93802

Open a typescript file, select the monokai theme, have the following code snippet

```
const t = Math.random();
const p = Number.MAX_SAFE_INTEGER;
setTimeout(() => console.log('hello'));
setInterval(() => console.log('llalal'));
this._actionBar.push(new Action('diffreview.close', nls.localize('label.close', "Close"), 'close-diff-review codicon-close', true, () => {
			this.hide();
			return Promise.resolve(null);
		}), { label: false, icon: true });
```

Notice how `Math` `Number` and `Promise` are not colored the same. At least `Math` and `Number` should be exactly the same imho.
I see how one got the textmate `support.class` and another `support.const`. But from a user standpoint I find this weird.

![Screenshot 2020-04-02 at 12 28 34](https://user-images.githubusercontent.com/1926584/78239323-dc400900-74dd-11ea-944c-ab1fecd6264c.png)

**Comment by aeschli** [comment]
This has to do with that `Math` is just a variable while `Number` and `Promise` are classes.

**Comment by isidorn** [comment]
Then I guess this is expected behavior. I just found it surprising.

**Comment by aeschli** [comment]
Now we could define that support.variable gets the same color as as support.class, but there might be other variables in the default library where this might not be what users expect.
Alyternativky I can make a special rule for `Math`

**Comment by aeschli** [comment]
I would wait if more users find this a problem, if that's ok for you.

**Comment by isidorn** [comment]
Of course, let's wait for feedback. Thanks
