### ISSUE TITLE
Open dialog filter does not except a file extension of tar.gz

### ISSUE THREAD

**Issue by cazfletch** [microsoft/vscode#94277]
- VSCode Version: 1.39
- OS Version: mac

Steps to Reproduce:

1. set the open dialog options filter property to include `tar.gz`
2. run the extension code and try and select a `tar.gz` file. It will be greyed out

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
/needsMoreInfo

What are you doing? Is this a problem when authoring an extension? Iff so, please attach a sample. In all cases, clarify this issue

**Comment by cazfletch** [comment]
This is when authoring an extension
```
 const openDialogOptions: vscode.OpenDialogOptions = {
        canSelectFiles: true,
        canSelectFolders: false,
        canSelectMany: false,
        openLabel: 'Select',
        filters: { Packages: ['tar.gz', 'tgz'] }
    };

 const fileBrowser: vscode.Uri[] = await vscode.window.showOpenDialog(openDialogOptions);

```

**Comment by jrieken** [comment]
It seems that you need to use `gz` and not `tar.gz`. Since we only use an electron API for that, pretty please to file the this issue with them. Thanks
