### ISSUE TITLE
When running theme extension, theme only works every other time

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#94273]
refs #93804:

- create new color theme with yeoman
- open in VS Code
- run theme with F5
- stop extension
- run theme with F5
- stop extension
etc.

Observe:
the theme is only activated every other time

**Comment by rafaelrenanpacheco** [comment]
Don't know if this could be related, but the changes I make on my theme only starts to be applied if I change the current "Extension Development Host" to another theme, then back again to my theme. Only after that I can start modifying the theme and get it applied real time.

**Comment by aeschli** [comment]
@rafaelrenanpacheco Not related, but I found the issue and pushed a fix
