### ISSUE TITLE
Add gear with additional actions to extension detail page

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#94289]
![image](https://user-images.githubusercontent.com/35271042/78258409-0e3a7680-74b0-11ea-9546-a298ad0f70f5.png)

Currently from the extension detail page there is no way to access the additional actions from the gear menu so you have to go all the way back to the viewlet:

![image](https://user-images.githubusercontent.com/35271042/78258394-08dd2c00-74b0-11ea-97d7-d9d19e374cf4.png)

Proposal would be to add the gear menu after the uninstall button and surface those extra actions. We could also move the sync icon so they match:
![image](https://user-images.githubusercontent.com/35271042/78258804-991b7100-74b0-11ea-86ae-9f0951cbdd0c.png)

**Comment by sandy081** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/10746682/98559330-c5009f80-22a6-11eb-8139-57d681cd2ae5.png">
