### ISSUE TITLE
Auto search selected text after hotkey press

### ISSUE THREAD

**Issue by TeNNoX** [microsoft/vscode#94286]
In #46326 you already introduced the option to search-as-you-type.
As also already requested in the [issue's comments](https://github.com/microsoft/vscode/issues/46326#issuecomment-467295674):  
**Automatically search when you select text and press the hotkey** (`ctrl-shift-f`) - not require an additional `Enter`.

Might be related to #91901

**Comment by JacksonKearl** [comment]
Yes, we actually had that in 1.42, but it gave rise to more problems. #91901 is about resolving those.
