### ISSUE TITLE
javascript different highlighting when using a variable named `root`

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94284]
```javascript
const root = ""
const abc = ""
root
abc
```
![Code_2020-04-02_15-43-55](https://user-images.githubusercontent.com/30108880/78256582-0521c780-74f9-11ea-81f8-805ad185d8f6.png)

1.43.2

**Comment by mjbvz** [comment]
@aeschli Now that we have semantic highlighting, I'm going to remove the special scopes we used to set for node variables in the text mate grammar
