### ISSUE TITLE
卡死

### ISSUE THREAD

**Issue by sunchuanjun** [Microsoft/vscode#9429]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.选择一个项目文件加后，再打开一个文件，直接卡死。
2.卡死提示：窗口不再响应    可以 重新打开或关闭窗，或者保持等待。
3.选择等待没有用。
4.卡的前兆是，弹出一个消息框。HTML CSS Class conmpletion:Fetching css rules from css files,please wait.

**Comment by weinand** [comment]
@sunchuanjun please use English.

**Comment by sunchuanjun** [comment]
Can't speak English.  I use the translation.
1. Select a project file to add after, to open a file, directly.
2. Jammed tip: window can no longer response to open or close the window, or keep waiting.
3. Choose to wait.
4. Card precursor is pop up a message box.HTML CSS Class conmpletion:Fetching css rules from css files,please wait.

**Comment by mouslee** [comment]
(**_-for reference only-_**) @sunchuanjun @weinand 

Translate Chinese to English

1. vscode will stop responding when I select a project folder and then open a file.
2. popup warning: the window cannot respond, please close/reopen it or keep waiting.
3. there is no use to keep waiting.
4. a message box will pop up before vscode stops responding: `HTML CSS Class conmpletion: Fetching css rules from css files, please wait.`

**Comment by bang88** [comment]
@sunchuanjun 
You can disable the [HTML CSS Class Completion](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) extension,it will fixes your problem.

**Comment by kieferrm** [comment]
Please reopen if the problem is unrelated to the [HTML CSS Class Completion](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) extension.
