### ISSUE TITLE
[API] Support use of a custom icon in window.withProgress().

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#94295]
`window.withProgress()` in the VS Code API is useful, particularly in how it reduces the number of things you would have to do manually to get the same effect.  However, if you want to use a custom "spinner" icon then you cannot use `withProgress()`.  Ideally that would change, reducing the need to do (basically) the same thing in multiple different ways.

Having the function support custom icons would reduce the need to manually *try* to get the same effect:

```typescript
    const statusBarProgress = window.createStatusBarItem(StatusBarAlignment.Left);
    try {
        statusBarProgress.show();
        const req = ...;
        req.on('progress', (percent: number) => {
            statusBarProgress.text = `${icon} ${progressMessage} ${percent}`;
        });
    } finally {
        statusBarProgress.dispose();
    }
```

If `window.withProgress()` supported custom icons (e.g. through `vscode.ProgressOptions`) then that same could look more like this:

```typescript
    await window.withProgress({ icon, location: ProgressLocation.Window }, async (progress) => {
        const req = ...;
        req.on('progress', (percent: number) => {
            progress.report({ message: `${progressMessage} ${percent}` });
        });
    });
```

**Comment by jrieken** [comment]
> However, if you want to use a custom "spinner" icon

Why? Isn't that defeating the purpose of a unified UX for progress? Won't this confuse users if progress for foo looks different than progress for bar?

**Comment by ericsnowcurrently** [comment]
See https://github.com/microsoft/vscode-python/issues/10495.

**Comment by jrieken** [comment]
Adding @misolori for feedback. Generally, you should be able (already today) to add more icons, e.g just use it with the message but swapping the icon that indicates progress isn't possible today
