### ISSUE TITLE
Git "stage change" too slow/unresponsive

### ISSUE THREAD

**Issue by juliafalcao** [microsoft/vscode#94296]
Issue Type: <b>Performance Issue</b>

I'm trying to use the native source control features on VS Code to stage or revert changes before committing, through the "peek" view and the buttons. Reverting works okay (a bit slow but manageable), but "stage change" (the "+" button) is essentially unresponsive most of the time. This has always been the case for me, even in relatively short files (500 lines of code), and small changes such as maybe 4 modified lines. It rarely works, and most of the time just doesn't do anything and I give up after around a minute waiting. I even disabled GitLens, thinking some conflict might've been the cause for this, but it had no effect.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    85	 13368	code main
    1	   225	  3524	   window (main.py - pav (Workspace) - Visual Studio Code)
    0	    34	  4108	     watcherService
   16	    92	 18564	     extensionHost
    0	   180	 13572	       c:\Users\julia.f.falcao\.vscode\extensions\ms-python.python-2020.3.71113\languageServer.0.5.45\Microsoft.Python.LanguageServer.exe
    0	     9	 20348	         console-window-host (Windows internal process)
    0	    25	 25280	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=18564
    0	    12	 19256	     C:\Windows\System32\cmd.exe
    0	    11	 24744	     console-window-host (Windows internal process)
    1	    73	  4504	   window (Issue Reporter)
    0	   146	  6476	   gpu-process
    5	    58	 11752	   shared-process
    0	    23	 15060	   utility
    0	    13	 22276	   electron-crash-reporter
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
vscode-edit-csv|jan|0.2.6
vs-color-picker|lih|1.0.0
MagicPython|mag|1.1.0
python|ms-|2020.3.71113
indent-rainbow|ode|7.4.0
ayu|tea|0.18.0
material-theme|zhu|3.2.5

(9 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
How slow is running `git add FILE` in the console?

**Comment by juliafalcao** [comment]
Normal, almost instant. I've been using it all the time. The button, in contrast, takes at least (roughly) 10 seconds to respond, staging a 1-line change.

**Comment by joaomoreno** [comment]
I remember there were a few other users with this issue in the past (eg https://github.com/microsoft/vscode/issues/34898). As far as I remember we found nothing...

Since VS Code simply spawns git, this is very weird. During the whole time you're waiting, can you use something like Process Hacker to see if `git.exe` is already spawned? Or is the whole waiting time happening before we even spawn git?

**Comment by juliafalcao** [comment]
I can't download Process Hacker because I'm on a managed workstation and the firewall won't allow it... I tried to check the processes via Task Manager during a couple of tests, and besides one main instance of ```git.exe``` running at all times (PID doesn't change), as soon as I click the "stage change" button a couple more instances are immediately spawn for brief periods of time.

**Comment by joaomoreno** [comment]
Hm, they spawn instantly and run for a short moment, which is great. And Code will still take a bunch of time complete the operation? Did I get that right? Any chance other git.exe processes come up _right before_ Code completes the operation?
