### ISSUE TITLE
Regression reported by users of vscode debugger for unity

### ISSUE THREAD

**Issue by miniwolf** [microsoft/vscode#94291]
People are confirming that downgrading VSCode from latest to 1.42.1 solves problems with the debugger client. This being the case I come here to report the issue that has been introduced. There seems to be some regression.

There are several issues and I have also linked two stacktraces from these posts below that may point to some of these regressions:

https://github.com/Unity-Technologies/vscode-unity-debug/issues/160
- https://github.com/Unity-Technologies/vscode-unity-debug/issues/160#issuecomment-601460585

https://github.com/Unity-Technologies/vscode-unity-debug/issues/162
https://github.com/Unity-Technologies/vscode-unity-debug/issues/166
- https://github.com/Unity-Technologies/vscode-unity-debug/issues/166#issuecomment-606800662

**Comment by weinand** [comment]
The crash reported in the Unity issues mentioned above is
https://github.com/microsoft/vscode/issues/93223 which has been fixed 10 days ago.

Could you please try whether the problem is fixed in latest Insiders.

**Comment by miniwolf** [comment]
That seems to be fixing the issue. Thank you :) When will this be released?

**Comment by isidorn** [comment]
Next week. Thus closing this. Thank you.
