### ISSUE TITLE
Unusual Ctrl+Left_Arrow and Ctrl+Right_Arrow

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#943]
Pressing Ctrl+Left_Arrow and Ctrl+Right_Arrow moves the cursor to the next word.

If the cursor is farther right than the word and you press Ctrl+Left_Arrow, you move to the beginning of the word rather than to the end of the word like in VS, Notepad++, Sublime etc...

Ex: $=cursor

`b('hello');$` and Ctrl+Left_Arrow becomes `b('$hello');` rather than `b('hello$');`

If this is intended to be like this, it would be nice to have a preference to change it.

**Comment by Kroc** [comment]
I'd like to add that the problem I'm having with Ctrl+Left/Right is that for indented lines, it goes to the first word, not the first character on the line. (`|` is cursor)

```
|       //press ctrl+right
        //press| ctrl+right
```

**Comment by alexandrudima** [comment]
The initial issue is resolved with the February release:

Using Ctrl-Left:
```
b('hello');|
b('hello|');
b('|hello');
b|('hello');
|b('hello');
```

Let's track Ctrl-Right in #3577
