### ISSUE TITLE
Got VS Code Server failed to start when attempting to SSH to remote

### ISSUE THREAD

**Issue by JimmyCerone** [microsoft/vscode#94309]
- VSCode Version: 1.43
- OS Version: Windows Version 10.0.18363 Build 18363

Steps to Reproduce:

1. Attempt to remotely connection to a host via a gateway

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
