### ISSUE TITLE
Editor scrolling bar

### ISSUE THREAD

**Issue by clc1968** [microsoft/vscode#94304]
Hello, 
I run "Visual Studio Code" under linux Mint (KDE 4.13.2), programming in C language.
Sometimes the editor scrolling bar freezes (mouse left click), but mouse scrolling (on the code) still working.
My computer is not a "formula 1", and I guess (but not sure) it happens when CPU fan going crazy.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
