### ISSUE TITLE
Got prompted if I want to turn on sync although I signed in a different window

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94308]
1) Setting sync had kicked me out earlier today
2) I cancelled the 'do you want to turn off' dialog and restarted VS Code for update
3) After the restart I used the gear menu in one of my windows to turn on sync (maybe it said sign-in instead)
4) Went through the browser flow
-> all other windows show the following prompted now:

![image](https://user-images.githubusercontent.com/4674940/78279250-1accc800-74cc-11ea-9f3a-62dc567d928c.png)

**Comment by sandy081** [comment]
Shall be fixed by https://github.com/microsoft/vscode/issues/94766
