### ISSUE TITLE
Notebook run/stop cell should always be visible when hovering over output

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#94314]
![image](https://user-images.githubusercontent.com/35271042/78284127-c299c400-74d3-11ea-833e-0e92ab0bd202.png)

When you hover over the output the run/stop button disappears. This should always be visible when hovering the cell because output is part of it.

**Comment by JacksonKearl** [comment]
It looks like now the items will never hide if theres an output visible? 
Notice focus is in top editor but bottom still has its items visible.
![image](https://user-images.githubusercontent.com/8586769/80759746-a5fda580-8aec-11ea-940d-7f021cba9734.png)

**Comment by sbatten** [comment]
adding label as per @JacksonKearl's comment, would argue that is not correct behavior.

**Comment by JacksonKearl** [comment]
*agree?

**Comment by roblourens** [comment]
It looks like you are hovering it. Are you? Otherwise I can't repro an issue.

**Comment by JacksonKearl** [comment]
I'm not. Once the output appears, those widgets never go away

**Comment by roblourens** [comment]
How did you execute the cell and did you click inside the output? We have to do weird stuff to figure out whether you are hovering the output and I'm guessing it got stuck.

**Comment by JacksonKearl** [comment]
Can no longer repro

**Comment by JacksonKearl** [comment]
![Kapture 2020-05-01 at 9 27 59](https://user-images.githubusercontent.com/8586769/80821971-9898f780-8b8e-11ea-8b82-65da73577b72.gif)
Still seeing odd flickering if the cell being mousedover isn't highlighted:

**Comment by roblourens** [comment]
The hover decorations should still be there when you hover the output and it looks like that stopped happening for you. Does that repro consistently?

**Comment by JacksonKearl** [comment]
Not reliably, no.

I'm also seeing that the icons flicker between being shown between the two as I cross over the "insert cell" line:

![Kapture 2020-05-01 at 10 00 33](https://user-images.githubusercontent.com/8586769/80824180-c6803b00-8b92-11ea-9785-23e7137694fa.gif)

**Comment by roblourens** [comment]
That's weird

**Comment by roblourens** [comment]
Still can't repro. It's possible that there was a layout issue and cells were overlapping or something. Closing for now.

**Comment by joaomoreno** [comment]
Hmmmm 🤔 

![recording (15)](https://user-images.githubusercontent.com/22350/83756923-06de4780-a670-11ea-8222-47fe782df210.gif)

**Comment by misolori** [comment]
Still seeing this weirdness. Noticed that this happens when you re-run a cell and then move your focus outside of that cell. Hovering over the output shows this.

![Kapture 2020-06-04 at 8 44 52](https://user-images.githubusercontent.com/35271042/83778596-c7980280-a63f-11ea-8f59-cd81cd777915.gif)

**Comment by roblourens** [comment]
TODO I think this will just happen after the second time the cell is rendered, because the mouseenter/leave listeners are tied the first output id, not the cell id.
