### ISSUE TITLE
Files missing in VS Code explorer but not Windows explorer

### ISSUE THREAD

**Issue by flxsu** [microsoft/vscode#94315]
- VSCode Version: 1.43.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open project with multiple node modules installed
2. Browse to node_modules/.bin
3. Folder is empty on Windows (not on Mac)

Does this issue occur when all extensions are disabled?: Yes
![Capture](https://user-images.githubusercontent.com/11788526/78290552-2a77fb00-7524-11ea-90a9-b2de1566f2af.PNG)

I have NOT added any folder to my "Files: Exclude" setting.
In fact my VS Code settings on Windows are identical to my settings on Mac.
This issue does NOT occur on Mac.

The issue is not fixed on VS Code Insiders and is reproducible on a fresh installation. No extensions installed, nothing modified.
![Capture](https://user-images.githubusercontent.com/11788526/78291039-010b9f00-7525-11ea-9cc5-75b89a14c721.PNG)

**Comment by isidorn** [comment]
Can not reproduce.
F1 > developer tools > put a breakpoint [here](https://github.com/microsoft/vscode/blob/aef342f29090ac2f75bf99e2a90f5d47f3e01d4c/src/vs/workbench/contrib/files/common/explorerModel.ts#L282)
You can use a conditiaonl breakpoint to only stop when the ExplorerItem.name === .bin and figure out is the children array empty and how the folder gets resolved.
Thanks!

**Comment by flxsu** [comment]
I put the breakpoint where you said. It gets triggered by opening any folder EXCEPT node_modules/.bin

I recorded a small video showing it.
https://www.youtube.com/watch?v=F6wiCh6CM6I

**Comment by isidorn** [comment]
@fixsu thanks for investigating more. Can you maybe share that repository you are using so I also try to clone and reproduce it?

**Comment by flxsu** [comment]
So I did some more testing, it turns out that the issue only occurs with files without file extensions, in this case executables. I added a "test.txt" and sure enough - VS Code did see it.

Specifically in ExplorerItem.create(), raw.children[] only contains one child, namely "test.txt" and before I added it raw.children[] was empty.
![vscode bug](https://user-images.githubusercontent.com/11788526/78642370-ec2b6480-78b2-11ea-91d7-d7585e388f71.PNG)

**Comment by flxsu** [comment]
Yeah, I can provide you the repo. Should I upload it here?

**Comment by isidorn** [comment]
Do you have some settings / extensions which might influenct this? Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
If you can you can reproduce with insiders you can provide me the repo here.

**Comment by flxsu** [comment]
I found the cause!
The executables in node_modules/.bin are WSL symlinks. They are visible in Explorer.exe, cmd.exe sees them as "junctions" but they are apparently not normally accessible to various parts of the Windows API.

![image](https://user-images.githubusercontent.com/11788526/78644552-5265b680-78b6-11ea-8d34-497e51d41a95.png)
![image](https://user-images.githubusercontent.com/11788526/78644721-9c4e9c80-78b6-11ea-9baf-d8712b81e1db.png)

Seems this is a WSL issue and appears to not be completely fixed.
https://github.com/microsoft/WSL/issues/353
https://github.com/microsoft/WSL/issues/2683

**Comment by flxsu** [comment]
Enabling Windows 10 Developer Mode and reinstalling node_modules in WSL fixed it.
cmd.exe now sees the WSL symlinks as symlinks instead of junctions, and they are visible in VS Code.
![image](https://user-images.githubusercontent.com/11788526/78647289-a7a3c700-78ba-11ea-91ea-5ec9ceb064ba.png)

**Comment by isidorn** [comment]
Great. Glad you fixed the issue.
