### ISSUE TITLE
vscode not requesting the debugger for variables in debug mode

### ISSUE THREAD

**Issue by DridriLaBastos** [microsoft/vscode#94311]
I opened an issue in vscode-cpptools because nothing was happening in debug mode and it appears that it is a problem with vscode not requesting variables from the debugger [issue 5238](https://github.com/microsoft/vscode-cpptools/issues/5238): when I go in debug mode I cannot see my variables, and I can't use the commands of the debugger, I can only quit it.

<img width="1552" alt="Capture d’écran 2020-04-01 à 09 04 11" src="https://user-images.githubusercontent.com/19534959/78108531-e1c32380-73f7-11ea-8d77-29464c2630fc.png">

There is my launch.json:
```json-with-comments
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "clang++ - Générer et déboguer le fichier actif",
			"type": "cppdbg",
			"request": "launch",
			"program": "${fileDirname}/${fileBasenameNoExtension}",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"environment": [],
			"externalConsole": false,
			"MIMode": "lldb",
			"preLaunchTask": "clang++ build active file",
			"logging": { "engineLogging": true, "trace": true, "traceResponse": true }
		}
	]
}
```
and tasks.json
```json-with-comments
{
    "tasks": [
        {
            "type": "shell",
            "label": "clang++ build active file",
            "command": "/usr/bin/clang++",
            "args": [
				"-g",
				"--std=c++11",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "/usr/bin"
            }
        }
    ],
    "version": "2.0.0"
}
```

This is the log file produced by vscode

[output.txt.zip](https://github.com/microsoft/vscode-cpptools/files/4413763/output.txt.zip)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
llvm-tablegen|jak|0.0.1
eclipse-new-java-project|mel|1.0.1
git-graph|mhu|1.22.0
python|ms-|2020.3.71113
cpptools|ms-|0.27.0
vsliveshare|ms-|1.0.1891
java|red|0.59.0
vscode-xml|red|0.11.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2
vscode-todo-highlight|way|1.0.4
linkerscript|Zix|1.0.0

</details>

Steps to Reproduce:
I haven't seen yet a pattern to reproduce it. Even with me, sometimes the debugger works, sometimes it not

**Comment by WardenGnaw** [comment]
Additional information:

The debug adapter receives a `scopes` request so we can populate the `call stack` window, but we never get a `variables` request. So nothing will show up in the variables window.

From our logs we can see from the `scopes` request, we have variables in the frame:
```
variables=[
{arg="1",name="argc"},
{arg="1",name="argv"},
{name="V"},
{name="v1"},
{name="v2"},
{name="v3"},
{name="v4"},
{name="v5"},
{name="v6"},
{name="v7"},
{name="v8"},
{name="v9"},
{name="v10"},
{name="E1"},
{name="G1"}]
```

and they have values:
```
1: (6113) <-1020-var-create - - "V" --thread 1 --frame 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (6116) ->1020^done,name=\"var3\",numchild=\"8\",value=\"size=8\",type=\"std::__1::vector<VertexStruct, std::__1::allocator<VertexStruct> >\",thread-id=\"1\",has_more=\"0\"\n"},"seq":600}

```

**Comment by isidorn** [comment]
Ok so the problem is that the scopes are not displayed.

1. F1 > developer tools > do you see some errors in the debug console?
2. If no errors, if you put a breakpoint [here](https://github.com/microsoft/vscode/blob/aef342f29090ac2f75bf99e2a90f5d47f3e01d4c/src/vs/workbench/contrib/debug/browser/variablesView.ts#L233) and step a bit do you see the Scope nicely constructed or the array is empty

Thanks

**Comment by DridriLaBastos** [comment]
I have 1 error in the consol:
<img width="1170" alt="Capture d’écran 2020-04-03 à 07 58 18" src="https://user-images.githubusercontent.com/19534959/78330041-5c6c7a00-7583-11ea-9b30-1db693774b9f.png">

I tried to put a breakpoint, it steps one time and goes to getScopes, then it steps back, and when I step again, the execution continues without pausing

<img width="1170" alt="Capture d’écran 2020-04-03 à 08 13 02" src="https://user-images.githubusercontent.com/19534959/78330393-2b407980-7584-11ea-8c65-e6674615f6a5.png">

When I click the little red square to stop the debug session, it breaks, and I have another error:
<img width="1170" alt="Capture d’écran 2020-04-03 à 08 29 02" src="https://user-images.githubusercontent.com/19534959/78330982-68593b80-7585-11ea-9b1d-2ff1269abfdf.png">

**Comment by isidorn** [comment]
@DridriLaBastos Those errors are unrelated.
Thanks for trying to debug it, but it seems like you did not uncover anything which points to an issue.

@WardenGnaw you are saying that for `scopes` your extension recieves a request and it properly sends a result but nothing is displayed in vscode? So nothing suspicion seems to be going on with regards to DAP communication?
