### ISSUE TITLE
Notebook: Toggle Center Mode breaks the output

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94319]
Issue Type: <b>Bug</b>

Toggle Center Mode seems making changes to the DOM tree which breaks the webview

<img width="2162" alt="image" src="https://user-images.githubusercontent.com/876920/78297356-4065cb80-74e4-11ea-9b9d-d7c17592539e.png">

Note that it doesn't happen with Markdown Preview.

VS Code version: Code - Insiders 1.44.0-insider (d8e3cca049b1baa317ab9ef0d3f673b08e53d8fa, 2020-04-02T06:40:18.155Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.53GB free)|
|Process Argv|-psn_0_7681875|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
vscode-pull-request-github-insiders|Git|2020.4.2341
vscode-language-pack-zh-hans|MS-|1.44.1
remote-ssh-edit-nightly|ms-|2020.3.44100
remote-ssh-nightly|ms-|2020.3.44100
js-debug-nightly|ms-|2020.3.3117
vscode-github-issue-notebooks|ms-|0.0.4
vsliveshare|ms-|1.0.1891
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Toggle Center Layout will move the editor pane from one container to another, which breaks the webview. @isidorn are you aware of any events which I can listen to for the layout change?

**Comment by isidorn** [comment]
@rebornix there are currently no events when the centering happens.
There is a `onDidLayout` call [here](https://github.com/microsoft/vscode/blob/51edf4892b8ea1cabaf0e0a267ba23ffe187c712/src/vs/workbench/services/editor/common/editorGroupsService.ts#L169) which I believe gets fired whenever there is a lyout change. Not sure if that is too much but you can try to use it.
