### ISSUE TITLE
Auto attach for node.js is not working for all commandline calls

### ISSUE THREAD

**Issue by Zehelein** [microsoft/vscode#94318]
- VSCode Version: 1.43.2
- OS Version: Windows 10
- node.js version: 12.8.1

Steps to Reproduce:

1. Start debugging with the command `tsc-watch --onSuccess "node --inspect-brk=9229 -r dotenv/config dist/index.js"`
2. It starts up just fine and I can attach to the process with a simple VS code config like:
```
    {
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "port": 9229
    }
```

But it will not auto attach. I guess this is due to the fact that on Windows I need to use " as quotes. Maybe it is also possible to configure the pattern by which you find the --inspect-brk?

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
The existing auto-attach mechanism is soon to be replaced by the "JavaScript Debug Terminal" which should fix this issue.
I suggest that you try out the Preview JS Debugger in Insiders: https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger
