### ISSUE TITLE
Fail to update extension 

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#9431]
- OS Version: win 10
- vsce Version:1.7.0

When i run `vsce publish`,  it suggest `Successfully published`.However, the extension version is not updated correctly, but the `last update time` is right.

**Comment by joaomoreno** [comment]
What do you mean with the `last update time`? Can you show me a screenshot?

**Comment by Lonefy** [comment]
@joaomoreno 
screenshot
![image](https://cloud.githubusercontent.com/assets/7921431/16909471/86b33cfe-4d05-11e6-8fb0-b2c1b1549077.png)

**Comment by joaomoreno** [comment]
This issue was moved to Microsoft/vscode-vsce#107
