### ISSUE TITLE
[rename on type] API for languages beyond HTML

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#94316]
Continuing #88424, which implements the Synced Region feature for HTML.

We could offer an API and I can try doing it for JSX (#85707).

I tried running this feature in real programming languages such as TypeScript, but automatic mode creates a lot of confusion. For example:

```ts
const a = { b: 1, c: 2 }
a.b|
```

In automatic mode, when I'm deleting `b` and entering `c` to change from `a.b` to `a.c`, `b: 1` would also be changed. This is undesirable.

Nevertheless, having Cmd+Shift+F2 to live-rename in a for-loop etc would be very helpful.

This issue tracks the API proposal below:

```ts
/**
 * The rename provider interface defines the contract between extensions and
 * the live-rename feature.
 */
export interface OnTypeRenameProvider {
	/**
	 * Provide a list of ranges that can be live renamed together.
	 *
	 * @param document The document in which the command was invoked.
	 * @param position The position at which the command was invoked.
	 * @param token A cancellation token.
	 * @return A list of ranges that can be live-renamed togehter. The ranges must have
	 * identical length and contain identical text content. The ranges cannot overlap.
	 */
	provideOnTypeRenameRanges(document: TextDocument, position: Position, token: CancellationToken): ProviderResult<Range[]>;
}

namespace languages {
	/**
	 * Register a rename provider that works on type.
	 *
	 * Multiple providers can be registered for a language. In that case providers are sorted
	 * by their [score](#languages.match) and the best-matching provider is used. Failure
	 * of the selected provider will cause a failure of the whole operation.
	 *
	 * @param selector A selector that defines the documents this provider is applicable to.
	 * @param provider An on type rename provider.
	 * @param stopPattern Stop on type renaming when input text matches the regular expression. Defaults to `^\s`.
	 * @return A [disposable](#Disposable) that unregisters this provider when being disposed.
	 */
	export function registerOnTypeRenameProvider(selector: DocumentSelector, provider: OnTypeRenameProvider, stopPattern?: RegExp): Disposable;
}
```

**Comment by Matelasse** [comment]
@octref Would you be able to implement this for jsx please? @mattbierner this really is a huge quality of life improvement for relatively marginal effort. It deserves to be in the Iteration for this/next month imho

**Comment by pgfearo** [comment]
I would have been very interested in this API for the XML/XSLT editor extension I’m developing. However, I’m concerned about  synced regions being ‘opt in’ and also requiring other user intervention (when the command is invoked), so for the time being at least, the extension will provide its own synced XML tag renaming. People writing XML/XSLT in other editors are used to synced tag renaming just working by default and with no intervention on their part.

**Comment by ToddGrun** [comment]
Question: For stopPattern, would \S or [^\s] be a better default? Can stopPattern represent more than a single character?

**Comment by KamasamaK** [comment]
This looks to have been finalized in #109923

**Comment by aeschli** [comment]
Yes, correct. Closing as dup of #109923

**Comment by Ares9323** [comment]
> This looks to have been finalized in #109923

Can you please explain how to add more supported languages to this setting?
I tried to look at the changelog you posted and at the documentation but there is no example.

The setting recently changed from "editor.renameOnType" to "editor.linkedEditing" and I looked for both with no success.

I tried several parameters with "languages.registerLinkedEditingRangeProvider" from [this](https://github.com/microsoft/vscode/issues/109923#issuecomment-741866857) comment but none worked and I can't seem to find the correct syntax (I have version 1.52.1 as suggested but in the settings.json I see "Unknown Configuration Setting")

**Comment by aeschli** [comment]
Yes, you have to write an extension that registers a new LinkedEditingRangeProvider for a given language selector. That's done with the API `registerLinkedEditingRangeProvider`.

If the user settings `editor.linkedEditing` is enabled, the editor will ask your LinkedEditingRangeProvide for linked ranges. Changes to one linked range will be automatically applied to all linked ranges.
