### ISSUE TITLE
Changing git.path still points to old git config

### ISSUE THREAD

**Issue by spenoir** [microsoft/vscode#94326]
Issue Type: <b>Bug</b>

1. set git.path to non root git instance
2. notice after a while that git operations in vs code use the root git config

expected 
git config loaded relative to the git.path setting

actual
git root global config appears to be used

I came across this issue while using WSL on Windows 10. Perhaps we need a setting for git.globalconfigpath?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
What are the first few lines of `Git: Show Git Output`?
