### ISSUE TITLE
Explorer panel does not show Open button

### ISSUE THREAD

**Issue by namtrik** [microsoft/vscode#94325]
VS Code shows a command instead of Open button in explorer panel (pic related).

<img width="338" alt="Captura de Pantalla 2020-04-02 a la(s) 5 09 11 p  m" src="https://user-images.githubusercontent.com/44480034/78304775-1670d100-7505-11ea-93af-82e697c897d7.png">

- VSCode Version: 1.43.2
- OS Version: Mac OS Mojave

Steps to Reproduce:

1. Open VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is already fixed in `master` and Insiders.
