### ISSUE TITLE
Rename Preview "Group Changes By File" view doesn't show the reference type icon info

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#94323]
- VSCode Version: 1.43.2 and the latest Insiders.
- OS Version: Windows

Steps to Reproduce:

1. Invoke the Rename Preview somehow with results that types with icons. I used our internal C/C++ extension at https://github.com/microsoft/vscode-cpptools.

Actual: No reference type icons are shown

![image](https://user-images.githubusercontent.com/19859882/78301167-8d01d480-74ed-11ea-8385-31ee1130d6e1.png)

Expected: Type icons should appear. Hovering over the icon should show the type label. Otherwise the info is only available via the group by type view and it's a regressions compared to our previous custom UI.

![image](https://user-images.githubusercontent.com/19859882/78301518-0a2d4980-74ee-11ea-8f12-5fe02d7ce26c.png)

VS

![image](https://user-images.githubusercontent.com/19859882/78301763-6a23f000-74ee-11ea-9d13-80a8c28356c6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe update the title of this issue to clarify it's the **reference** type icons that are missing.

**Comment by jeanp413** [comment]
I'll take this up
