### ISSUE TITLE
I don't know if this is The right place, Can't install any extensions..

### ISSUE THREAD

**Issue by cardfaux** [microsoft/vscode#94322]
- VSCode Version: 1.43.2
- OS Version: Ubuntu 18

Steps to Reproduce:

1.Try to install any extension
2.

Does this issue occur when all extensions are disabled?: YES i don;t have any extensions. this has been a 2 day ordeal i completely uninstalled and reinstalled VSCODE, i changed my network files screwed then up, completely uninstalled my network manager. reinstalled another network manager. completely reinstalled my operating system thinking that would fix it and nope, everything on my whole computer is a fresh install and i can't even put eslint extension on my code editor. I have read common problems where ppl are behind proxies I am not I am using a direct connection, that is my connection. I have read blogs, watched videos, you name it i have done it trying to fix this. all i was trying to do was use a C# extension for .net core so i could use one editor instead of two and now i have literally just vs code installed from installing a brand new OS trying to fix this problem.
![failedVScode](https://user-images.githubusercontent.com/54493199/78301465-b37c3b80-74fe-11ea-802b-b3639fc2dda6.png)
![first-Network](https://user-images.githubusercontent.com/54493199/78301485-bf67fd80-74fe-11ea-9533-1a9f0735f3cc.png)
![second-network](https://user-images.githubusercontent.com/54493199/78301498-c55dde80-74fe-11ea-8b95-e0c93436b73f.png)
![third-network](https://user-images.githubusercontent.com/54493199/78301503-c989fc00-74fe-11ea-9c88-6e3b1596daa9.png)

**Comment by joaomoreno** [comment]
@cardfaux Check the file permissions on the `~/.vscode` folder. You might have them set to `root`. Change them to your user.

**Comment by cardfaux** [comment]
yes, The problem was a month ago i set a the theme to synthWave '84 or whatever it is and had to run vsCode as super user to set the neon dreams. and i figured after i restarted it it would go back to normal. I wasn't sure how to set it back to normal user. so looked up how i set it to root to begin with. this command set it to root sudo code --user-data-dir="~/.vscode-root. so i just ran sudo code --user-data-dir="~/.vscode-<username>. and set all my settings back to normal. Remember this was a fresh install so it didn't have the first plugin or theme set or anything and now it is just like it was yesterday. Just writing this in case anybody has the same problem this is how i fixed it

**Comment by cardfaux** [comment]
yes, The problem was a month ago i set a the theme to synthWave '84 or whatever it is and had to run vsCode as super user to set the neon dreams. and i figured after i restarted it it would go back to normal. I wasn't sure how to set it back to normal user. so looked up how i set it to root to begin with. this command set it to root sudo code --user-data-dir="/.vscode-root. so i just ran sudo code --user-data-dir="/.vscode-. and set all my settings back to normal. Remember this was a fresh install so it didn't have the first plugin or theme set or anything and now it is just like it was yesterday. Just writing this in case anybody has the same problem this is how i fixed it
