### ISSUE TITLE
Tab order in Search window is not optimal for some use cases

### ISSUE THREAD

**Issue by tomduncalf** [Microsoft/vscode#9433]
- VSCode Version: 1.3.1
- OS Version: OS X

I find the tab order in the search window is not optimal for the way I tend to use it – I primarily use search to find strings in certain types of files, so I might e.g. search for `user` in `*.ts`, then next I might want to search for `user-container` in `*.less`. 

In Atom and Sublime, the "files to include" field is one tab keypress away from the "search string" field, which makes doing this kind of search very easy. 

In VS Code, the tab order goes from the search string field to the three options (case sensitive, whole word and regex), then to the `...` expand link, and only then to the "files to include" box, so it takes five tab key presses to switch from "search string" to "files to include" (or a mouse move and click, but often that is less convenient). 

To my mind it would make sense for `tab` to first (or only?) tab through just the input fields, and to make use of keyboard shortcuts to enable/disable the options, although perhaps this is just me coming from Sublime/Atom. Alternatively, a separate keyboard shortcut could move through the input fields – in fact, it seems `Alt+Down arrow` will move from "search string" to "files to include", but not back again.

I'd be happy to try and implement this if you could advise on what a preferred solution (if any) might be!

**Comment by sandy081** [comment]
@tomduncalf This can be done in at least same number of key presses

When Files to include input box is open
- From search input box use <kbd>down</kbd> arrow to go to Files to include input box

When Files to include input box is hidden
- Use <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>j</kbd> to open Files to include input box
- Then press down arrow

May be in second case, it would  makes sense to focus in files to include input box when it is opened.

I hope this helps in navigating easily. IMO <kbd>tab</kbd> goes in the order of how elements are ordered makes sense.

**Comment by tomduncalf** [comment]
Ah, I didn't realise the down arrow moved through the fields! That's perfect, thank you :)
