### ISSUE TITLE
Impossible to resize maximized terminal panel

### ISSUE THREAD

**Issue by Gittenger** [microsoft/vscode#94337]
- VSCode Version: 1.43.2
- OS Version: Linux Mint

Steps to Reproduce:

1. Open terminal window
2. Maximize terminal window manually by dragging the resize helper to the top of the window.
3. Unable to resize terminal window back to a normal size because it's impossible to find the resize helper icon once the terminal window has been maximized.

This is made especially frustrating because the last size of your terminal is saved in your workspace. Meaning I can't simply restart the app to fix the problem. Meaning I'm stuck with a maximum-height terminal window in this project until I can find a workaround, making VSCode almost unusable.

I tried deleting everything in ~/.config/code/Local Storage but that didn't work. I tried window.localStorage.clear() in developer console but that didn't work. I tried >Clear editor history in the editor command prompt and that didn't work either. Short of creating an entirely new project and copying all my code over to that, I'm unsure what to do to work around this issue.

I'm updating to say I went ahead and copied the folder. It was a pretty large project but my OS is pretty quick so it didn't take too long. But that's the only workaround I know of if someone accidentally does this!

Although I've learned my lesson, this is a very bad UX, especially if you have a slower machine, so I'm writing this in hopes that the team can improve the resizing functionality of the terminal window in a future release. Thanks all.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Works for me:

![0c3b4884-71b8-4c03-b26c-d9d62f5c6d9d](https://user-images.githubusercontent.com/2193314/78385711-2b934180-7591-11ea-8402-d91a1d6054ae.gif)

There's the drag near the title bar and also the button. Maybe the dragger doesn't work when you're using native title bar?

**Comment by sbatten** [comment]
> Maybe the dragger doesn't work when you're using native title bar?

Yea that seems to be it. Bringing in @joaomoreno since this is similar to the sidebar in full screen situation.

**Comment by joaomoreno** [comment]
@sbatten I can't seem to find the duplicate... Can you find it and add the `grid-view` tag to it?

**Comment by sbatten** [comment]
found it https://github.com/microsoft/vscode/issues/92709
