### ISSUE TITLE
Make extensions section in extensions pack expandable/collapsible 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#94346]
From @jwarkentin in #89962

Make the section expandable with a button/link at the bottom middle or left of the list of extensions that just says "Show more" or "Show all extensions" or something to that effect? 

That way the readme is still visible but the user can choose to expand the extension list as part of the one scrollable content area.

**Comment by sandy081** [comment]
I do not think this will work because this will give only little space for the read me.

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/10746682/78862364-887e7400-7a37-11ea-87a4-276fdb8e7eda.png">

**Comment by jwarkentin** [comment]
The expandable/collapsible section should be part of the same scrollable area as the readme. Then it's not a problem at all. It should effectively be inserted as an expandable section within the readme.

**Comment by sandy081** [comment]
Read Me is rendered as a separate web view (iFrame) as it is Markdown. I think it is not easy to include extension packs in Read Me. Hence they are made separate sections. 

@mjbvz Any suggestions?

**Comment by mjbvz** [comment]
@sandy081 We control the rendering of the webview so you could add extension pack info inside of it: https://github.com/microsoft/vscode/blob/9f1aa3c9feecd04a79d22fd6752ba14a83b48f1b/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts#L320

I believe that would be the most simple fix

**Comment by sandy081** [comment]
I see.

**Comment by misolori** [comment]
I think a simple chevron next to the extension pack details to collapse it should do the trick.
