### ISSUE TITLE
Gitignore doesn't greyed out

### ISSUE THREAD

**Issue by ivanafanasyev** [microsoft/vscode#94344]
Issue Type: <b>Bug</b>

I have know idea why, but when I switched to MacOS VSCode stop make ignore files into grey color. It's happen only if you open .gitignore and resave it each time

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.2
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|3.20.0
terminal|for|0.0.10
next-js|fox|0.0.2
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.29
git-graph|mhu|1.22.0
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you give me steps to reproduce it, in a new clean repository?

**Comment by ivanafanasyev** [comment]
> Can you give me steps to reproduce it, in a new clean repository?

Sure. It's easy
1. You clone repo or create one
2. Create .gitignore, add files which should be ignored
3. Reopen VS Code, and this files doesn't greyed anymore. I still have white name color on them. Photo as an example
<img width="1197" alt="Снимок экрана 2020-04-07 в 11 19 51" src="https://user-images.githubusercontent.com/25664253/78646432-b6da4300-78c1-11ea-82d1-3b851d4790e5.png">

**Comment by joaomoreno** [comment]
https://stackoverflow.com/a/45400404

**Comment by ivanafanasyev** [comment]
Nice joke.... nice joke.
Of course I've tried it. And gitignore is work fine as gitignore file, and still doesn't tracking node_modules and etc.
It still doesn't work. Cause it is not the .gitignore issue or other git problem, it's certainly VS Code on OS X problem with file styles.

**Comment by ivanafanasyev** [comment]
It has been solved only when I made it manual in settings.json using next param:

```json
gitDecoration.ignoredResourceForeground: "color"
```

**Comment by ivanafanasyev** [comment]
> https://stackoverflow.com/a/45400404

I am talking about this param
gitDecoration.ignoredResourceForeground

It works only IF you open .gitignore and press save file few times. But when you reload your VS Code, you have to do this again and again for get color on your ignored files
