### ISSUE TITLE
Error message: Writing login information to the key chain failed, item already exists

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#94342]
This morning I've received the following notification multiple times. Reporting FYI

![image](https://user-images.githubusercontent.com/172399/78333186-a5bfc800-7589-11ea-8d84-25a182c7c60a.png)

**Comment by gjsjohnmurray** [comment]
@egamma Presumably you're either using Insiders or running from source. What version? And on what platform?

**Comment by gjsjohnmurray** [comment]
Maybe a dup of #94005

**Comment by RMacfarlane** [comment]
Thanks @gjsjohnmurray, this is a dup of #94005
