### ISSUE TITLE
showTabs: false creates "invisible" tabs

### ISSUE THREAD

**Issue by realyze** [Microsoft/vscode#9434]
- VSCode Version: 1.3.1
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:

1. Disable tabs (`workbench.editor.showTabs: false`).
1. Create a vertical split.
1. Open a few files in the editor (in one of the panes)
1. Hit `cmd+w`

It closes an "invisible tab", it doesn't close the whole pane as it used to.

This sucks mostly because I use two vertical panes. And every now and then, I want to close one of the panes to only have a big single editor window. Now in order to close one of the panes, I have to close a number of tabs which I can't even see.

**Comment by vstoykov** [comment]
I have the same problem after upgraded to 1.3.1. I'm on Ubuntu 14.04.

Now in order to unsplit I need to close all files that where opened in this split which sucks, because I don't want to close the files. I just want to unsplit.

**Comment by realyze** [comment]
Hello? Anyone? :-)

**Comment by bpasero** [comment]
As designed and no plans to change this currently. However we have related issues to mitigate this (e.g. allow to configure the close button to close all instead of one file).

You can always associate a keybinding to the close all command too.

**Comment by vstoykov** [comment]
I do not want to close the files. I want the previous behavior. When tabs are disabled to work as before.
Or as a workaround at least to move all opened files from current split to the one on left.

**Comment by realyze** [comment]
Well, I'd say claiming this works "as designed" is a bit of a stretch...unless said design states "implement annoying invisible tabs". ;-)

But regardless of this glitch - many kudos for creating the best editor for typescript around!

**Comment by realyze** [comment]
If I may suggest - having a `disableTabs: boolean` flag would IMHO be better (instead of `showTabs`).
