### ISSUE TITLE
Add Open With... to explorer context menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94347]
re https://github.com/microsoft/vscode/issues/93767

* I have a custom editor for JSON document
* In the editor's secondary title menu I see the 'Reopen with...' command
* I would expect something similar in the explorer's context menu

<img width="588" alt="Screenshot 2020-04-03 at 09 22 15" src="https://user-images.githubusercontent.com/1794099/78334881-d6edc780-758c-11ea-80f7-08223ab36468.png">

**Comment by mjbvz** [comment]
Also related to #95730
