### ISSUE TITLE
Notebook: "+Markdown +Code" clips cell title actions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#94356]
Pictures shows what I am talking about.
I got into this state by following steps from https://github.com/microsoft/vscode/issues/93920 thus moving cells around and hovering in the title area

![Screenshot 2020-04-03 at 11 20 04](https://user-images.githubusercontent.com/1926584/78344885-4f5c8480-759d-11ea-802d-639472696f00.png)

**Comment by rebornix** [comment]
already fixed.
