### ISSUE TITLE
hourly died on manjaro arch linux (aur installed)

### ISSUE THREAD

**Issue by vangohao** [microsoft/vscode#94352]
Issue Type: <b>Bug</b>

VSCode frequently died on my computer. It does not react and the minutes later kwin tells me the window have died and let me restart vscode. The menu(native) can react but the vscode resources died. Problem exists both on remote and local workspace.

VS Code version: Code - Insiders 1.44.0-insider (13b38d2a494612ace32c4fb878824d6329d4c51e, 2020-03-30T08:08:20.753Z)
OS version: Linux x64 5.4.28-1-MANJARO
Remote OS version: Linux x64 4.15.0-55.60

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|15.42GB (0.19GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pi|
|OS|Linux x64 4.15.0-55.60|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (2 x 2095)|
|Memory (System)|9.81GB (1.35GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cudacpp|kri|0.1.1
vscode-language-pack-zh-hans|MS-|1.44.1
remote-containers|ms-|0.110.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-language-pack-zh-hans|MS-|1.44.1
python|ms-|2020.3.71659
cpptools|ms-|0.27.0

</details>

**Comment by deepak1556** [comment]
Can you run with `--verbose --disable-extensions` and provide the output ?
