### ISSUE TITLE
Notebooks: top lock icon does not toggle and is confusing overall

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#94357]
Have a notebook file
Click on the top Lock icon.
The icon does not update, but all the cells get locked 🐛 

Also I am not a fan of the top lock action, I think it brings unnecessery ux complexity where a cell can be seen as unlocked on a cell level but still be locked. Imho this is confusing. I recommend to remove the top level action, and just have a command palette action which would call it on every cell

**Comment by connor4312** [comment]
For me the top lock icon doesn't do anything (and doesn't update the cell icons). I can open a separate issue for this if you would prefer. 

Recording: https://memes.peet.io/img/20-04-25268200-bdaf-4fee-9f61-cc3673a43e56.webm

**Comment by connor4312** [comment]
Nevermind, Peng just replied in DM that this is intended behavior of the Github notebook!
