### ISSUE TITLE
Preferences Sync doesn't work with keybindings from PC to Mac.

### ISSUE THREAD

**Issue by cmaughan** [microsoft/vscode#94355]
- VSCode Version: 1.44.0-insider
- OS Version: Win10 & Mac OS Catalina

Steps to Reproduce:

1. Add custom key bindings to keybindings.json
2. Use the new Preferences sync feature to sync
3. Note that the keybindings to no 'roam' between OS 

It seems that the keybindings written to the roam directory on Windows are not synchronised with the keybindings.json on the Mac.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
By default keybindings are synced per platform. Syncing keybindings across platforms is advanced and users have to opt in using setting 

<img width="349" alt="image" src="https://user-images.githubusercontent.com/10746682/78544441-706de100-77fa-11ea-81ca-97e3d0b418c4.png">
