### ISSUE TITLE
Extension prior versions not downloading

### ISSUE THREAD

**Issue by jstewart37** [microsoft/vscode#94350]
Apologies if this is raised in the wrong place. Originally raised on Ms-python.python git page, but been asked to raise with marketplace.

Unable to download versions of the Ms-python.python extension other than the latest and versions older than (or equal) to 0.3.23.

Examples:
Working:
https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2020.3.71113/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
Working:
https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/0.3.23/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

Not working:
https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2020.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
Not working:
https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2020.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
Not working:
https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2019.11.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

It seems that any non-latest versions which have the YEAR.RELEASE pattern are not working

**Comment by jrieken** [comment]
this repo is for Visual Studio *Code*

**Comment by jstewart37** [comment]
Are the above links not for the mspython.python vscode extension. If not, do you know where I can find the api url to download vscode extensions?

**Comment by jrieken** [comment]
I don't know this is also not the VS Code Python repo

**Comment by jstewart37** [comment]
I raised this initially with the extension owners. But they asked me to raise it with the vscode marketplace. 

I guess this is also the wrong place. But I have no idea how to raise a bug with the marketplace. 

Sorry for the inconvenience, I was just trying to raise a bug.

**Comment by gjsjohnmurray** [comment]
@jstewart37 maybe a pointer in https://github.com/microsoft/vscode/issues/15756#issuecomment-464252767 and the response that followed it.
