### ISSUE TITLE
Search results need more space than the side bar allows

### ISSUE THREAD

**Issue by tomduncalf** [Microsoft/vscode#9435]
- VSCode Version: 1.3.1
- OS Version: OS X

I believe that often, search results need more horizontal space to be truly useful than the sidebar allows, unless you expand the sidebar very wide (which then means less room for open files, and requires you to manually resize it bigger and smaller when going between search and editing, if you like to have the file tree open when editing).

My suggestion would be that search should have the option to display the results in a new tab, in a similar way to Atom or Sublime, or alternatively, the search pane could be relocatable to the bottom of the screen, so it would gain horizontal space in exchange for vertical.

**Comment by adigov** [comment]
search results need a separate tab, at least as an option. Current space is just too crowded - file name, file path, and results to make complete sense.

**Comment by ifeltsweet** [comment]
+1, absolutely, couldn't agree more.

**Comment by andrewdang17** [comment]
Even text wrapping would be nice, I always find myself resizing the sidebar

**Comment by omaressameldin** [comment]
I was wondering if this feature would be coming along anytime soon?

**Comment by swatibhartiya** [comment]
Need to add a feature to search for files within a directory

**Comment by goldo** [comment]
Would love it too! Thanks

**Comment by adamreisnz** [comment]
As soon as this lands I'll be able to switch from Atom to VSCode! 👍

**Comment by isidorn** [comment]
From tomorrow's insiders it is possible to put the search viewlet into the panel area using the setting
`"search.location": "panel"`
Please note that we did not yet polish the UX inside the settings view to use all these additional horizontal space. We plan to improve this next milestone, when we plan to polish this feature.
More details about what is done can be found in the PR https://github.com/Microsoft/vscode/pull/43833

**Comment by balta2ar** [comment]
@isidorn Is there a picture to see how it looks now (for those who aren't using insider's build)?

**Comment by isidorn** [comment]
<img width="1436" alt="screen shot 2018-02-23 at 11 00 00" src="https://user-images.githubusercontent.com/1926584/36588531-bc8712f6-1888-11e8-9429-2f3029fd1a50.png">

**Comment by dubeg** [comment]
Is there a way to add a keyboard binding to dismiss the search panel with escape?

I got...
```
    {
        "key": "escape",
        "command": "workbench.action.closePanel"
    }
```
But I'm missing the when clause. Is there something like `when: panelHasFocus `?
