### ISSUE TITLE
Show SCM/git gutter indicators in diffs view

### ISSUE THREAD

**Issue by penx** [microsoft/vscode#94365]
When in the [diffs view](https://code.visualstudio.com/docs/editor/versioncontrol#_viewing-diffs) for SCM/git (Source Control > click on changed file) it would be useful if the [gutter indicators](https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators) were shown, e.g. so that individual lines or chunks can be quickly discarded without switching views or manually copy and pasting.

i.e.
Show these tools:
![Screenshot 2020-04-03 at 12 20 21](https://user-images.githubusercontent.com/1027024/78355473-a5352a80-75a5-11ea-8081-c70079efa924.png)

When in this view:
![Screenshot 2020-04-03 at 12 20 10](https://user-images.githubusercontent.com/1027024/78355481-a8c8b180-75a5-11ea-9cdd-720b24142058.png)

**Comment by joaomoreno** [comment]
You can use the editor selection on the right-hand side, right click and run the Stage/Unstage Selected Changes actions.

**Comment by penx** [comment]
@joaomoreno thanks!

Is there any reason not to also have the gutter tools available in this view? It would mean users are presented with a more familiar interface. The options in the right click context menu are easily missed - in particular the fact you can't right click a deleted line in the right hand column, so you have to select or right click adjacent lines to make this work.

**Comment by joaomoreno** [comment]
I think the UI would just look cluttered since we could only render them on the right hand side, we can't make it span the entire diff editor width.

**Comment by penx** [comment]
@joaomoreno Agreed for smaller screens, but I think it'd be fine on a 1440px+ wide display.

Perhaps, if it's easy to implement, it could be behind a flag?
