### ISSUE TITLE
semanticTokenScopes produces wrgon mappin

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#94367]
Version: 1.44.0-insider
Commit: 20b88fa0694cae8e46ffd305a1450ba58ae6065b
Date: 2020-04-01T08:29:34.507Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.113

Problem: I am developing an extension which takes advantage of semantic highlighting, and looks like `"semanticTokenScopes"` selector matching is broken. Specifically, my pluging defines the mapping like this:

```
        "semanticTokenScopes": [
            {
                "language": "rust",
                "scopes": {
                    "attribute": [
                        "meta.attribute"
                    ],
                    "builtinType": [
                        "support.type.primitive"
                    ],
                    "lifetime": [
                        "entity.name.lifetime.rust"
                    ],
                    "typeAlias": [
                        "entity.name.typeAlias"
                    ],
                    "union": [
                        "entity.name.union"
                    ],
                    "keyword.unsafe": [
                        "keyword.other.unsafe"
                    ],
                    "keyword.control": [ // <- the interesting bit
                        "keyword.control"
                    ],
                    "variable.constant": [
                        "entity.name.constant"
                    ]
                }
            }
        ]
```

but somehow control styling is applied to all keywords, not only to control ones:

![image](https://user-images.githubusercontent.com/1711539/78357019-f696e700-75b0-11ea-9100-a467e0a5ce09.png)

![image](https://user-images.githubusercontent.com/1711539/78357041-01517c00-75b1-11ea-8a9d-d5619a448759.png)

Note that I also use a "zero" textmate grammar for rust, to make sure that there's no interference wit tm, but the same bug is observable with default rust grammar as well. 

Steps to Reproduce:

1. Install rust-analyzer [from source](https://rust-analyzer.github.io/manual.html#building-from-source)
2.  Enable semantic highlighitng with `{ "rust-analyzer.highlighting.semanticTokens": true, "editor.semanticHighlighting.enabled": true, }`
3. Observe all keywords colored as control keywords

**Comment by aeschli** [comment]
We have a set of default rules configured, and `keyword` currently goes to TextMate scope `keyword.control`: see https://github.com/microsoft/vscode/blob/9ed52e392858f0c1b47333680d81ac194ec644f4/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L499
You can overwrite that for rust, if you prefer:
```
"semanticTokenScopes": [
            {
                "language": "rust",
                "scopes": {
                    "keyword": [
                        "keyword"
                    ]
            }
]
```

**Comment by matklad** [comment]
Ah... Yeah, that explains the observed behavior. I wonder though, why default maps to keyword.control and not just to keyword?

**Comment by aeschli** [comment]
It comes from the built-in default themes where we differentiate between keywords ('if', 'function', ...) ('keyword.control') and operators ('and', 'not') ('keyword.operator'). So we basically interested in the  color that a theme gives to the the first set.

**Comment by matklad** [comment]
Hm, right, that makes sense. Textmate scopes are confusing,I hope we’ll transition to more consistent semantic selectors eventually. Thanks for the explanation!
