### ISSUE TITLE
Allow drag and copy opened files to any file explorer folder.

### ISSUE THREAD

**Issue by shirkerohit** [microsoft/vscode#94363]
- It would be really great to have an option to, simply drag an opened file in editor pane to a folder in file explorer.

As of now,  If we want to save a opened file in required directory, we need to go with save as function and then browse the required directory to save the file. This handy option will allow a simple productivity boost!

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by shirkerohit** [comment]
Thanks you for considering the feature request. I hope this get merged soon!

**Comment by shirkerohit** [comment]
This doesn't make any sense to me!

From being fairly feature request to being out of scope! The ask was, I have a file opened in editor and when I drag it across the file tree against a folder, It should get copied there (May be with a prompt!). What's out of scope in this ask? Editing file, saving it or what?

Anyways, Its a MS tool and You have all rights to reject any request and tailor the app as per your needs!

Happy coding!
