### ISSUE TITLE
Find better wording for switch to text editor gesture

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94368]
re https://github.com/microsoft/vscode/issues/93767

* This uses VS Code as hard-coded name, not the product name
* This reads a little cumbersome, why not "Text Editor" and as description (built-in)

<img width="361" alt="Screenshot 2020-04-03 at 13 46 27" src="https://user-images.githubusercontent.com/1794099/78357528-e8959600-75b1-11ea-9b4e-c354cf27d731.png">

**Comment by mjbvz** [comment]
Fixed by #94411
