### ISSUE TITLE
No call stack available ({_command}: {_error}).

### ISSUE THREAD

**Issue by xudongsxd** [microsoft/vscode#94364]
- VSCode Version:
- OS Version:

Steps to Reproduce:
Nodejs service, when I make a breakpoint in the debugging process, and then go to the breakpoint, the service automatically stops, and then re debugging, the service has been unable to start, no call stack available ({_command}: {_error}).

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
Your repro steps don't work for me: what is the "Nodejs service"? What is "re debugging"? Where does the "{_command}: {_error}" come from? 
Please provide reproducible steps and a screen shot of the error you are seeing.
