### ISSUE TITLE
Fedora 31: Getting graphics problem

### ISSUE THREAD

**Issue by soermejo** [microsoft/vscode#94361]
- VSCode Version: 1.43.2
- OS Version: Fedora 31 workstation inside virtualbox

Steps to Reproduce:

1. I Opened visual studio code and did something
2. Every time i was getting stranges black and blank window as i hover with the mouse to open the menu.

![20200403_120818](https://user-images.githubusercontent.com/21694707/78349981-b598d580-75a4-11ea-8f26-8612640de707.jpg)
![20200403_120735](https://user-images.githubusercontent.com/21694707/78350002-be89a700-75a4-11ea-9e75-d88fc313f6d4.jpg)
![20200403_120746](https://user-images.githubusercontent.com/21694707/78350028-c9dcd280-75a4-11ea-89ad-5ff325357cea.jpg)
![20200403_120759](https://user-images.githubusercontent.com/21694707/78350047-d19c7700-75a4-11ea-91d3-7a7d15ab6b2c.jpg)

All of them sometimes they works sometimes they are blank and black. It's really buggy.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you disable hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if it helps. Thanks!

**Comment by mathisgag** [comment]
> Can you disable hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if it helps. Thanks!

That worked for me, on the exploation build of visual studio.
