### ISSUE TITLE
Quick Pick: Items with `alwaysShow` which don't match input, should keep sorting

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#94373]
These first two fields have `alwaysShow`. When the input matches nothing they still show but their order is switched.

![ff9298ea-555b-4013-a5c5-269dd791908e (1)](https://user-images.githubusercontent.com/22350/78361206-5218a300-75b8-11ea-9303-2de915702fdb.gif)

Sorry @bpasero @chrmarti, not sure who takes this.

**Comment by smithjosh115** [comment]
I want at look at resolving this. Does it matter if "Create new branch..." or "Create new branch from..." comes first?
