### ISSUE TITLE
CTRL+Z shortcut doesn't work on French keyboard layout

### ISSUE THREAD

**Issue by anouarhassine** [microsoft/vscode#94374]
Am on Fedora 29 using two keyboard layouts: English (by default) and French. I have a French layout keyboard (AZERTY).

When using the French keyboard layout, undoing changes via the **Ctrl+Z** shortcut in VS Code doesn't work. Instead, it closes the file. To undo, I need to press **Ctrl+W** as _Z_ and _W_ keys are switched between QWERTY and AZERTY keaybord layouts.
This is very annoying. The same shortcut works fine in other apps I have (web browsers, text editors etc).

In the keyboard shortcuts screen I press **Ctrl+Z** and it detects and displays **Ctrl+W** as shown in the following screeshot:

![image](https://user-images.githubusercontent.com/12862424/78361143-344b3e00-75b8-11ea-8434-35f1c369ec7c.png)

- VSCode Version: 1.43.2
- OS Version: Linux x64 5.3.11-100.fc29.x86_64

Steps to Reproduce:

1. Switch to the secondary keyboard layout (Fr for me)
2. Edit a file
3. Press Ctrl+Z
4. VS Code detects a press on Ctrl+W; it attempts to close the file and prompts for saving changes

Does this issue occur when all extensions are disabled?: Yes

**Comment by anouarhassine** [comment]
Is there any update about this issue?

**Comment by alexdima** [comment]
@anouarhassine Have you seen the troubleshooting page at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/80215289-7d813180-863c-11ea-8837-59146395fb5d.png)
