### ISSUE TITLE
$workspaceRoot resolves to sub-project folder 

### ISSUE THREAD

**Issue by Miesvanderlippe** [microsoft/vscode#94378]
- VSCode Version: 1.43.2
- OS Version: Manjaro Kyria 19.0.2 (5.5.13-1-MANJARO)
 
Steps to Reproduce:

1. Create a code-workspace with multiple custom folders
2. Run the "echo" task with the ${workspaceRoot} variable
3. The task exits with the currently selected subfolder. 

Does this issue occur when all extensions are disabled?: Yes

So I have this workspace set-up: 

```
{
	"folders": [
		{
			"name": "REST Base-host Source",
			"path": "rest-base-host/rest_base_host"
		},
		{
			"name": "REST Base-host Tests",
			"path": "rest-base-host/tests"
		},
		{
			"name": "REST Base Source",
			"path": "rest-base/rest_base"
		}
	],
        "tasks": {
		"version": "2.0.0",
		"tasks": [
	                {
				"label": "echo",
				"type": "shell",
				"command": "echo ${workspaceRoot}"
			}
		]
	}
}
```
I'm trying to run a program in a specific sub-directory of my workspace. But when I run the echo task, it returns:

```
/home/[redacted]/vscode-workspace/rest-base-host/rest_base_host
```

**Comment by alexr00** [comment]
@Miesvanderlippe this is by design, as there is no way for a workspace file task to know which of your three folders you want otherwise. If you want to have it run in a specific folder you should move the task into the .vscode folder of that folder.

**Comment by Miesvanderlippe** [comment]
> @Miesvanderlippe this is by design, as there is no way for a workspace file task to know which of your three folders you want otherwise. If you want to have it run in a specific folder you should move the task into the .vscode folder of that folder.

Well, I don't _want_ to select any of the three folders. That's why I'm using workspaceroot, the root of the workspace. But it's not the root of the workspace, it's just a root of one of the projects.

**Comment by gjsjohnmurray** [comment]
@Miesvanderlippe I notice you are using relative paths in your XXX.code-workspace file. I assume that file is in your /home/[redacted]/vscode-workspace/ folder, correct? So it sounds like you want to be able to refer to the folder in which your workspace definition file is located, correct?

**Comment by Miesvanderlippe** [comment]
Yes. That is correct.

**Comment by gjsjohnmurray** [comment]
AFAIK there is currently no such variable. But #37421 covers the addition of an API to get the information you're looking for. Doesn't get it to you as a variable though.
