### ISSUE TITLE
Sort order for files in Explorer sidebar not natural/human

### ISSUE THREAD

**Issue by raikesy** [Microsoft/vscode#9437]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
    Open folder containing numerically labelled files:
        - 1.py, 2.py. 3.py ... 10.py, 11.py
Expectation:
    Files listed in explorer sidebar sorted in numerical order, as above (and as in Windows Explorer).
Actual outcome:
    Files sorted lexicographically:
        1.py, 10.py, 11.py, 2.py, 3.py ...
See https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/

**Comment by weinand** [comment]
@joaomoreno who owns the sorting?

**Comment by joaomoreno** [comment]
@bpasero 👍

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5066
