### ISSUE TITLE
Inline customEditor#selector?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94384]
Comparing the `customEditors` extension point with `languages`. They are similar but different in respect to `filenamePattern`. For languages it's a top-level properly, for custom editors it's nested inside an otherwise empty selector-element

<img width="465" alt="Screenshot 2020-04-03 at 16 14 16" src="https://user-images.githubusercontent.com/1794099/78369920-3caa7580-75c6-11ea-8ee4-e12a0686e21e.png">

**Comment by mjbvz** [comment]
The intention is that a single custom editor may match multiple different file types that you can't always write a single glob pattern for. Rather than requiring extension authors duplicate the entire custom editor entry for such cases, we take an array of selectors

**Comment by jrieken** [comment]
> The intention is that a single custom editor may match multiple different file types that you can't always write a single glob pattern for.

That's why for languages this is filenamePattern**s**, e.g an array of patterns and also an array of filenames.

**Comment by mjbvz** [comment]
I've intentionally modeled this after our document selector type. This capability may not be needed today but if we let custom editors define they only work on specific schemes for example—which seems reasonable—selector can become:

```json
"selector": [
    { scheme: "untitled", "filenamePattern": "*.png" },
    { scheme: "file", "filenamePattern": "*.png" }
]
```

So yes, you can inline the today but it's designed for future extension. There is not much downside IMO to using the slightly more verbose version today

**Comment by jrieken** [comment]
🤷‍♂ I give up
