### ISSUE TITLE
Add some environment variables on issues reported from Linux to help identify distro and desktop environment

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94388]
Advice from Canonical was to add these environment variables in issues reported from Linux.

```
DESKTOP_SESSION
XDG_SESSION_DESKTOP
XDG_CURRENT_DESKTOP
```

Example values:

```
DESKTOP_SESSION=ubuntu
XDG_SESSION_DESKTOP=ubuntu
XDG_CURRENT_DESKTOP=ubuntu:GNOME
```

**Comment by sh7dm** [comment]
Probably `XDG_SESSION_TYPE` should be reported too, since some issues can be related to running on Wayland with XWayland
