### ISSUE TITLE
Custom editor and filenamePatterns

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94383]
* have a custom editor that is registered for `*.json`-files
* play with it
* change its selector to `"filenamePattern": "**/settings.json"`
* :bug: still open all JSON files...

<img width="1044" alt="Screenshot 2020-04-03 at 16 12 20" src="https://user-images.githubusercontent.com/1794099/78369704-eb01eb00-75c5-11ea-8d1f-54257df36a65.png">

**Comment by mjbvz** [comment]
Yes for the `language` contribution, looks like we handle `filenamePattern` that contain a slash specially: https://github.com/microsoft/vscode/blob/3f0e5b4ab059cb6c05ecac091b652cfc50b9292f/src/vs/base/common/mime.ts#L32

We should do the same here
