### ISSUE TITLE
can't open intergrated terminal in dir ,named with chinese words

### ISSUE THREAD

**Issue by macaddr** [Microsoft/vscode#9439]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.open dir named with chinese words, eg: e:\pp\新项目
2.open,vscode in this dir^
3.ctrl+~

**Comment by Tyriar** [comment]
Duplicate of #7727
