### ISSUE TITLE
Animation is necessary for file explorer collapsing

### ISSUE THREAD

**Issue by mbscreater** [microsoft/vscode#94392]
Issue Type: <b>Feature Request</b>

Animation is necessary for file explorer collapsing.
We get confused in file exploring when we open and collapse the folders.
If you add the proper animations to the file explorer, we will work more comfortable.

(This point will get more important when we work in big framewors like Angular.)

Thanks.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by ZayRTun** [comment]
Yes, this animation is necessary. Sometimes it's just hard to focus while browsing the explorer when folders open and collapse suddenly.
Really wish, that this feature gets some serious consideration.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
