### ISSUE TITLE
There is a problem with the search results

### ISSUE THREAD

**Issue by sunbohong** [microsoft/vscode#94397]
- VSCode Version:1.43.2 (system setup)
- OS Version:Windows_NT x64 10.0.18363

Steps to Reproduce:

1.A **text** file(contain nul data)
2.Search a key.
3.Expect multiple results, but only one.

Does this issue occur when all extensions are disabled?: Yes

https://github.com/BurntSushi/ripgrep/blame/3d59bd98aaea776092168f8feaf5daeeaf743cbf/GUIDE.md#L182

Through debugging, I found the reason and solution.

When we search text file,vscode use ripgrep service,but it will treat this **text** as **binary** file.

https://github.com/BurntSushi/ripgrep/blame/3d59bd98aaea776092168f8feaf5daeeaf743cbf/GUIDE.md#L182

`rg -g 017311.txt keyword --debug`

```
WARNING: stopped searching binary file 017311.txt after match (found "\u{0}" byte around offset 133555)
```

In the **text** file,we should use the `--text`.

`rg -g 017311.txt keyword--text`

**Comment by BurntSushi** [comment]
You definitely do not want to enable something like this by default. This will cause all binary detection to be disabled and ripgrep will search every file even if it would otherwise be considered binary. Usually a text file does not contain NUL bytes.

**Comment by sunbohong** [comment]
> You definitely do not want to enable something like this by default. This will cause all binary detection to be disabled and ripgrep will search every file even if it would otherwise be considered binary. Usually a text file does not contain NUL bytes.

I have so many text files,which contain nul bytes 😭.
.So,i just want a optional flag whic can be passed to rg service.

我本地有很多的文本文件，（都包含nul bytes）.
所以，我希望能够提供一个机制（将"--text"透传给rg服务）

**Comment by roblourens** [comment]
I agree with @BurntSushi. And I don't want to expose this functionality with a setting, because vscode won't necessarily be able to display these results in the editor, and it will lead to a lot of confusing issues. So I suggest that you search for these files using `rg` in the terminal.
