### ISSUE TITLE
Wildcards on activationEvents.workspaceContains?

### ISSUE THREAD

**Issue by nicolocodev** [Microsoft/vscode#944]
Is there a way to use wildcards in `activationEvents.workspaceContains`? i mean, could i do something like:

```
"activationEvents": [    
    "workspaceContains:*.config"
  ],
```

**Comment by akaroml** [comment]
Just want to echo this feature request. We are developing an extension that should be triggered when there is *.ino files inside the workspace. This is for Arduino and its source files does not necessarily have the same file name (could be _anyname_.ino).
So the wildcard support is exactly what we need.
By the way, the activationEvents:['*'] seems like an overkill for this.

**Comment by DustinCampbell** [comment]
Yes, this is critical for C# in VS Code. We want to load on "*.cs" and "*.csproj" but can't do it without loading on "*". That's definitely overkill.

**Comment by enricosada** [comment]
Same for F# support with [ionide-fsharp](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp), is needed to load on ".fs" and ".fsproj" /cc @Krzysztof-Cieslak

**Comment by Krzysztof-Cieslak** [comment]
From my point of view (and I guess similar is true for C# extension) to get really smooth startup experinace I'd need 2 things:
1. Wildcards in `activationEvents.workspaceContains`
2. `activationEvents.workspaceContains` checking also sub-directories not only top level folder.
