### ISSUE TITLE
Terminal doesn't always render initially when using PseudoTerminal and task custom execution

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#94402]
- VSCode Version: Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

- OS Version:
OS: Windows_NT x64 10.0.19600

Steps to Reproduce:
Our extension registers a custom task provider and it provides tasks with custom execution and the following presentation options:
```typescript
{
            clear: true,
            focus: false,
            reveal: vscode.TaskRevealKind.Always
};
```

If the terminal "tab" is not already selected for some other reason (say power shell started, etc.) then when the task runs, the terminal dropdown displays the correct task name, but nothing renders.

Note that adding this simple code:
```typescript
        vscode.window.onDidOpenTerminal((t) => {
            t.show();
        });
```
Works around this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by GabeDeBacker** [comment]
@Tyriar & @alexr00 - any update on this? Our customers are starting to notice this issue more.

**Comment by alexr00** [comment]
@GabeDeBacker I'm not able to repro this now. There were some changes in showing tasks in 1.44, do you still see the issue there?

**Comment by Tyriar** [comment]
Fixed a similar issue recently https://github.com/microsoft/vscode/issues/94714

The problem there was that when an extension created a terminal and did not call show and then another terminal is shown, there were actually 2 terminal tabs visible at once, one not being drawn (the initial one) and one being draw but it was offscreen.

**Comment by alexr00** [comment]
That was probably it then. I tested in master this time so I had the fix for https://github.com/microsoft/vscode/issues/94714

**Comment by alexr00** [comment]
@GabeDeBacker can you check in Insiders and see if you still have the same problem?

**Comment by GabeDeBacker** [comment]
@alexr00  - Hey, sorry about not responding sooner. Checking now

**Comment by GabeDeBacker** [comment]
@alexr00 - I can confirm that this is indeed addressed in the insiders version. I'm closing this issue.
