### ISSUE TITLE
terminal scrolling speed is too slow

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#94405]
Issue Type: <b>Bug</b>

the scroll speed of the terminal window depends entirely on how tall the terminal window is.

repo:
- open a wsl terminal window
  `$ echo "Hello World!" > file.txt`
  `$ for i in {1..15}; do cat file.txt file.txt > file2.txt && mv file2.txt file.txt; done`
- make the terminal window as **short** as possible (2 lines tall):
  `$ time cat file.txt`
  `   real 12.123s`
- make the terminal window as **tall** as possible (~75 lines):
  `$ time cat file.txt`
  `   real 2m43.452s`

vscode is taking 2 1/2 minutes _just_ scrolling the window. that's about 92% of the time.

BTW: regular wsl bash in a native maximized conhost takes 7s.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (5.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1

</details>

**Comment by IllusionMH** [comment]
hmmm...
What value do you have in `terminal.integrated.rendererType`?
Difference is quiet noticeable with `dom` as reported, however `canvas` and `experimentalWebgl` has minimal difference in times and are 4-5s when I launch `wsl` in Git bash (default terminal).

P.S. Using Remote-WSL and terminal in VS Code everything looks immediate and `time` reports <1s even for `dom`

**Comment by Spongman** [comment]
yup, that was it. my `rendererType` was set to `dom` (not sure why). setting it to `canvas` brings the times down significantly.
