### ISSUE TITLE
Can't set key binding to control keys + space (Mac)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#94400]
Issue Type: <b>Bug</b>

Two problems:
1) The default binding for show parameter help for Mac is SHIFT+CMD+SPACE, but that combination is already taken by the system to change input language
2) vscode won't let me change that binding to something like SHIFT+OPT+CMD+SPACE

To repro 2):
1) Preferences->Keyboard shortcuts
2) select Trigger Parameter Hints
3) Dialog comes up to press the desired keyboard combination
4) Press SHIFT+OPT+CMD+SPACE
!) The dialog accepts SHIFT+OPT+CMD, but does absolutely nothing when you press the SPACE key with the control keys still down
<img width="570" alt="image" src="https://user-images.githubusercontent.com/6913354/78389025-dd813c80-7596-11ea-9fcc-957e62bd93d0.png">
I can use any other key (e.g. SHIFT+OPT+CMD+ENTER), but not SPACE.

<br>
VS Code version: Code - Insiders 1.44.0-insider (d8e3cca049b1baa317ab9ef0d3f673b08e53d8fa, 2020-04-02T06:40:18.155Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
todo-tree|Gru|0.0.171
vscode-antlr4|mik|2.2.3
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.16
vscode-dotnet-runtime|ms-|0.1.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
azure-account|ms-|0.8.8
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.8.5
vscode-yaml|red|0.7.2
tmcolor|sle|0.0.1
vscode-todo-highlight|way|1.0.4
arm-params-generator|wil|0.9.0

</details>

**Comment by alexdima** [comment]
@StephenWeatherford This works fine for me:
![image](https://user-images.githubusercontent.com/5047891/78535115-e9197100-77eb-11ea-8f06-dfb8563df30e.png)

If that dialog doesn't show it, it means we are not receiving the keybinding. So I believe you might have yet another system wide keybinding that prohibits this keybinding from reaching us. 

Please try disabling all the keybindings with Space from here and check again, or try using the Guest user:
![image](https://user-images.githubusercontent.com/5047891/78535283-2aaa1c00-77ec-11ea-8497-f018a75fc02c.png)
