### ISSUE TITLE
SQL apostrophe formatting

### ISSUE THREAD

**Issue by mtengmo** [Microsoft/vscode#9440]
- VSCode Version: 1.3.1
- OS Version: Windows 8.1
![sql-vscode](https://cloud.githubusercontent.com/assets/17195619/16916346/a964ec10-4cfc-11e6-8312-b8eeb3cbf1d6.JPG)

Steps to Reproduce:

1. Formatting of SQL color codes doesn´t handle alot of apostrophe. 
2. Code snippet:

update all_abwusers
set e_mail =   replace(
        replace(
            replace(
                replace(
                    replace(
                        replace(
                            replace(
                                replace(
                                    replace(
                                        replace(
                                            replace(e_mail,'' '', '''') 
                                        ,''å'', ''a'')
                                    ,''è'', ''e'') 
                                ,''é'', ''e'')
                            ,''ä'', ''a'')
                        ,''ö'', ''o'') 
                    ,''ù'', ''u'') 
                ,''ç'', ''c'') 
            ,'''''''', '''') 
        ,''`'', '''')
    ,''-'', '''')

**Comment by aharpervc** [comment]
Looks like backtick is escaping the quote. Related escape character issue: https://github.com/Microsoft/vscode/issues/5223

**Comment by aeschli** [comment]
Close as dup of #5223
