### ISSUE TITLE
`vscode-insiders` links being opened in Parallels instead of local instance

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94419]
Encountering this using the github auth flow initiated by:
```
vscode.commands.registerCommand('extension.loginWithRepo', async () => {
		const session = await vscode.authentication.login("github", ['repo']);
		const token = await session.getAccessToken();
		console.log(token);
	})
```

The auth succeeds than github tried to redirect me back to insiders by giving me a `vscode-insiders://...` URI, but this gets intercepted by Parallels instead of going through to my local VS Code. 

This is on latest insiders, and I'm pretty sure I've done this flow in the past and it worked fine. So I'm not sure if something has changed on the Windows box, my local box, or in VS Code.

**Comment by RMacfarlane** [comment]
Going to go ahead and close this since there haven't been any more reports of this, and to my knowledge nothing has changed about our protocol handlers
