### ISSUE TITLE
Combine extensions.ignoreRecommendations and extensions.showRecommendationsOnlyOnDemand

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#94416]
I feel it's rather confusing to have two distinct settings for filtering extension recommendations: What's the result if both are `true`?

So, I suggest to combine these to settings into a single one with three options (click triangle to unfold):

<details><summary>Recommend Extensions</summary>

- Never
- On demand only
- Always
</details>

**Comment by sana-ajani** [comment]
I think this is a good idea. It is confusing right now if both settings are enabled. Does ignore recommendations override show on demand? @sandy081 thoughts?

**Comment by sandy081** [comment]
I looked into the code and its very complicated to understand how each setting works. I like the simplification of this into one setting.

**Comment by sandy081** [comment]
Deprecated the setting `showRecommendationsOnlyOnDemand` in favour of following:

- Use extensions.ignoreRecommendations setting to control recommendation notifications. 
- Use Extensions view's visibility actions to hide Recommended view by default.
