### ISSUE TITLE
Multifolder workspace javascript import autocomplete not working(jsconfig.json)

### ISSUE THREAD

**Issue by ishpartko** [microsoft/vscode#94414]
Issue Type: <b>Bug</b>

Hi all, my vscode doesn't want to do an autocomplete(which I specified in jsconfig.json) when I work through workspace(two folders).

All working in single mode(one workspace folder), but if I trying add second folder to my workspace I don't get any suggestions in import statement.

**(multifolder workspace -- no path suggestions, only Tabnine tip)**
![изображение](https://user-images.githubusercontent.com/27618114/78405060-5a98ca00-7608-11ea-99ce-9728568e671b.png)

![изображение](https://user-images.githubusercontent.com/27618114/78405081-65ebf580-7608-11ea-84d0-89f4536a735f.png)

**(singlefolder workspace -- all good, as must be)**
![изображение](https://user-images.githubusercontent.com/27618114/78405196-a77ca080-7608-11ea-99ca-d838425814c7.png)

![изображение](https://user-images.githubusercontent.com/27618114/78405216-b2cfcc00-7608-11ea-8169-7da137c7da83.png)

```json
// jsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"]
    }
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.3.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.20.5
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.2
json-colors|Den|0.0.6
javascript-ejs-support|Dig|1.3.1
gitlens|eam|10.2.1
env-switcher|Eck|0.1.2
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.0.0
vscode-firefox-debug|fir|2.7.1
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
svg|joc|1.1.7
sublime-babel-vscode|jos|0.2.10
vscode-inline-sql|jtl|0.1.4
graphql-for-vscode|kum|1.15.3
vscode-vuex-peek|Mcb|0.7.2
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.42.4
debugger-for-chrome|msj|4.12.6
node-modules-resolve|nau|1.0.2
env-cmd-file-syntax|Nix|0.1.2
vetur|oct|0.24.0
docker-compose|p1c|0.3.5
vscode-graphql|Pri|0.2.14
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.1
vue-vscode-snippets|sdr|1.8.0
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|1.15.0
autoimport|ste|1.5.3
vscode-stylelint|sty|0.84.0
tabnine-vscode|Tab|2.5.2
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0
ReactSnippetsStandard|Tim|1.1.0
vscodeintellicode|Vis|1.2.6
vscode-svg-previewer|vit|0.5.1
rainbow-tags|vol|0.3.1
vscode-icons|vsc|10.0.0
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by ishpartko** [comment]
I forgot to add -- relative paths always work, but look at this horror. Would you then like to inherit a project with such paths from me?

![изображение](https://user-images.githubusercontent.com/27618114/78405609-836d8f00-7609-11ea-971f-dd11e57a8b7f.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Also, can you please share an small example workspace that demonstrates this issue?

**Comment by ishpartko** [comment]
Hi @mjbvz,

Thank you for your quick response!

Indeed, disabling all extensions helped fix the problem in `.js` files.

But in .vue files I found a new autocomlete error.

Essence:

1) **folder 1** - is the project's backend folder
2) **folder 2** - is the project's frontend folder
3) I disabled all extensions and enable only the  [Vetur extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur)
4) I opened the file .vue in the frontend folder (**folder 2**) and wrote import statement
5) I got in offers to import files/folders from the backend folder(**folder 1**)

Is this issue of vscode or the [Vetur extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur)?

I fixed this by *changing the folder order in workspace*(look's as vscode or vetur taking only the first folder in my workspace to show autocomplete suggestions). 

Please tell me if I need to write something else to describe the problem in more detail to solve it in my favorite editor.

**Comment by mjbvz** [comment]
Thanks for testing.

Yes, VS Code does not include builtin support for Vue so please file this against the Vetur extension
