### ISSUE TITLE
Console cursor disappears

### ISSUE THREAD

**Issue by max0x7ba** [Microsoft/vscode#9441]
- VSCode Version: 1.3.1
- OS Version: Linux Fedora 22, bash shell

Steps to Reproduce:
1. Press Ctrl+' to open a new Terminal.
2. Press up arrow to show the previous command from bash history.
3. Observe that the flashing cursor disappears.
4. Start typing to append to the command line, still no cursor.

**Comment by Tyriar** [comment]
@max0x7ba I can't seem to reproduce, would you be able to use dev tools (Help > Toggle Developer Tools) to inspect the element where the cursor is and take a screenshot? There is supposed to be a span with the `terminal-cursor` class.

**Comment by max0x7ba** [comment]
There is a span initially:
![terminal-cursor-present](https://cloud.githubusercontent.com/assets/765202/16923658/3b39bd3a-4d13-11e6-8b4f-0ed5ea7f20f5.png)

Then I press arrow-up key to bring up the latest command and the cursor disappears:
![terminal-cursor-absent](https://cloud.githubusercontent.com/assets/765202/16923662/3fb60904-4d13-11e6-8f6d-adb981d6049d.png)

And then I click arrow-left key and the cursor reappears:
![terminal-cursor-reappears-after-left-arrow](https://cloud.githubusercontent.com/assets/765202/16923667/42577030-4d13-11e6-81e3-83aece1bb68b.png)

**Comment by Tyriar** [comment]
@max0x7ba does un-maximizing, horizontally resizing and then trying to reproduce again make the cursor show up?

**Comment by max0x7ba** [comment]
@Tyriar Resizing the window to a smaller size and then back truncates the command prompt. I have to press ctrl-c to make bash re-display the prompt.

**Comment by Tyriar** [comment]
@max0x7ba I still can't repro this, can you try reproducing it on the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Tyriar** [comment]
Closing as there's still no repro (and there's an intuitive work around if it does happen, ctrl+c).
