### ISSUE TITLE
Opening a file via the folder breadcrumbs doesn't add it to the Recent File list

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/vscode#94418]
Issue Type: <b>Bug</b>

1. Open a file within a folder.
2. Use the breadcrumbs under the tab to navigate to a parent folder and select a different file to open. 

![image](https://user-images.githubusercontent.com/24302614/78411011-120aed80-75c3-11ea-93a6-6b4eecf0a8cb.png)

3. Optional: Click the tab to keep the file open.

![image](https://user-images.githubusercontent.com/24302614/78411022-1e8f4600-75c3-11ea-8cb5-51197ebd3df2.png)

4. Close the newly opened file.
5. Note: This file is not added to the recent file list:

![image](https://user-images.githubusercontent.com/24302614/78411052-349d0680-75c3-11ea-8491-e175de32657d.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19594

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.3
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-markdownlint|Dav|0.34.0
python|ms-|2020.2.64397
debugger-for-chrome|msj|4.12.6
vetur|oct|0.23.0
java|red|0.59.1
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.23
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.0

</details>

**Comment by bpasero** [comment]
File > Open Recent is being filled from:
* opening through File > Open
* external open (e.g. terminal)

**Comment by michael-hawker** [comment]
@bpasero is there a reason to not include the breadcrumb opens this way? Especially if I click the tab and make it stay open?

**Comment by bpasero** [comment]
We have a internal list of recently opened that we always update: `Ctrl+P` (look for recently opened to the top)
