### ISSUE TITLE
Wrong token colors display in editor

### ISSUE THREAD

**Issue by awerlogus** [microsoft/vscode#94422]
Issue Type: **Bug**

Description
---

When I pass number literal as a parameter of type parameter of function, the function and the type parameter are not colored as expected

![изображение](https://user-images.githubusercontent.com/24425566/78414498-5c28b900-762d-11ea-9206-7d0c50bd7f67.png)
![изображение](https://user-images.githubusercontent.com/24425566/78414884-6cda2e80-762f-11ea-96fd-d8df789abdb5.png)
![изображение](https://user-images.githubusercontent.com/24425566/78414891-7499d300-762f-11ea-9625-39f2e7128d7f.png)
![изображение](https://user-images.githubusercontent.com/24425566/78414895-7c597780-762f-11ea-9627-811ace0b60bc.png)

---

Version: 1.44.0-insider (system setup)
Commit: 0dbae2083aff6ff2190c8e2157be95458915d464
Date: 2020-04-03T05:44:09.945Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots
