### ISSUE TITLE
Selecting a problem in the Problems panel should activate already-opened editor.

### ISSUE THREAD

**Issue by sivy** [Microsoft/vscode#9442]
- VSCode Version: 1.3.1
- OS Version: OS X

Steps to Reproduce:

1. Open the Problems panel for a file with an open editor (ie `utilities.py`)
2. Switch focus to another editor stack (split view).
3. Click on one of the problems listed in the Problems pane.
4. A new editor opens with `utilities.py`, rather than switching to the currently open (but not active) editor.

**Comment by sandy081** [comment]
File be revealed if visible in one of the editor groups. Check this behavior in
- Problems view
- Search view
- Replace preview in Search
