### ISSUE TITLE
Tokenization and Lag time on save

### ISSUE THREAD

**Issue by kkashou** [microsoft/vscode#94425]
I am trying to format on save in vscode and everytime I save my jsx file I keep getting a warning "Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`."

- VSCode Version: 1.43.2
- OS Version: macOs Catalina Version 10.15.4

Steps to Reproduce:

1. Work on an jsx file
2. Cmd + s (Save) Then the issue hangs and won't format my file.

Does this issue occur when all extensions are disabled?: Yes

How can I solve this since it just happened on the last update. I even restarted my entire VSCODE with no extensions and it happens. I attached the error I get in the editor.

<img width="2025" alt="Screen Shot 2020-04-03 at 8 24 56 PM" src="https://user-images.githubusercontent.com/8713386/78417712-a9833700-75e9-11ea-9ded-5c477c606a48.png">

**Comment by gjsjohnmurray** [comment]
Did you try the suggestion of the warning message, setting a larger value on `editor.maxTokenizationLineLength` on the Settings page?

**Comment by kkashou** [comment]
Yeah and that still didn't do anything.

**Comment by gjsjohnmurray** [comment]
Can you post a file here that demonstrates the issue? Make sure it doesn't contain anything that should be kept private.

**Comment by kkashou** [comment]
@gjsjohnmurray  - Here is the file I am trying where it is not working.

[icons.jsx.txt](https://github.com/microsoft/vscode/files/4432451/icons.jsx.txt)

**Comment by alexdima** [comment]
@kkashou That notification shows when opening a file that contains a very long line. If you don't want to see the notification anymore, please click in the gear icon and click 'Don't show again'.
