### ISSUE TITLE
some time it dose not work properly

### ISSUE THREAD

**Issue by sajibmalek** [microsoft/vscode#94421]
Issue Type: <b>Bug</b>

PS G:\React Source Code\Class_16 State> npx create-react-app app
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Malek\AppData\Roaming\npm-cache\_npx\21996" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sajib Malek\AppData\Roaming\npm-cache\_logs\2020-04-04T00_47_47_764Z-debug.log
Install for [ 'create-react-app@latest' ] failed with code 1
PS G:\React Source Code\Class_16 State> 

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Could you specify how this is relate to VS Code editor itself?
If it's general question - please use StackOverflow
