### ISSUE TITLE
Codelens javascript extended class method is considered a reference to extender static method

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94429]
```javascript
class Y{
	foo(){}
}
class X extends Y{
	static foo(){}
}
```
```
"javascript.referencesCodeLens.enabled": true,
```
![Code_2020-04-04_09-35-26](https://user-images.githubusercontent.com/30108880/78421414-b6d70a80-7657-11ea-93d9-159de50a147d.png)
1.43.2

**Comment by pushkine** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [CodeLens : Class extending Array and overwriting its methods gets referenced globally (#93654)](https://www.github.com/microsoft/vscode/issues/93654)

(meta) you might want to filter issues from the same OP when looking for duplicates 🥰

**Comment by mjbvz** [comment]
Thanks! I confirmed the bug and will open a TS issue to track this

/cc @JacksonKearl On the meta feedback

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/37830 to track upstream
