### ISSUE TITLE
HTML Snippet not working

### ISSUE THREAD

**Issue by lesordinaires** [microsoft/vscode#94428]
- VSCode Version: 1.43.2
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. type html
2. html simple snippet not available for use anymore

Does this issue occur when all extensions are disabled?: Yes

This error occurred since the latest update.

I have reinstalled VSCode as well as extensions a few times, but it seems it's not working even when the default settings are untouched. Also, the file type was set to HTML.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
