### ISSUE TITLE
trouble starting VS CODE

### ISSUE THREAD

**Issue by elthunderbyte** [microsoft/vscode#94420]
Dear! I am new around here and the truth is I am a bit disoriented in how to ask.

I am having trouble starting VS CODE in its latest version. Attached is the capture. I have Win 7 32bit, 3gb RAM. I already installed and uninstalled it multiple times.

I read that the same thing happened to some of them but I cannot understand the solutions given.

Thanks since now!
![vscode](https://user-images.githubusercontent.com/63126781/78413475-f10bc200-75ed-11ea-8120-4ec531545c28.jpg)

**Comment by yzk23** [comment]
Hello, @elthunderbyte! 
I believe that this problem occurred because your Windows has only 3Gb of RAM.
Before opening VSCode, open the Task Manager and see in the performance tab how much RAM is left.
Then open VSCode and see how much RAM is left.

**Comment by elthunderbyte** [comment]
Acá adjunto dos capturas! Una al iniciar la PC y otra al abrir el VS CODE.

Qué piensan?
![rendimiento1](https://user-images.githubusercontent.com/63126781/78458630-4cd75900-7689-11ea-8508-e7ef620fa5ba.jpg)
![rendimiento2](https://user-images.githubusercontent.com/63126781/78458631-4ea11c80-7689-11ea-83ec-9786d5ccc6d1.jpg)

**Comment by jrieken** [comment]
Please start from the command line like so `code --prof-startup`

**Comment by elthunderbyte** [comment]
There I tried and got the same result. Attached screenshot:
![comando](https://user-images.githubusercontent.com/63126781/78599485-9d84b880-7827-11ea-88cf-0e24125c6a33.jpg)

**Comment by jrieken** [comment]
Please start from the command line like so code --prof-startup, not `code prof startup` (the dashed matter)
