### ISSUE TITLE
'${workspaceFolder}' can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name.

### ISSUE THREAD

**Issue by HeavenSky** [microsoft/vscode#94424]
- VSCode Version:
- OS Version:

Version: 1.44.0-insider
Commit: 0dbae2083aff6ff2190c8e2157be95458915d464
Date: 2020-04-03T05:52:10.484Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:

1.   debug a js file 
2.  popup an error
![image](https://user-images.githubusercontent.com/7927784/78417503-4f27bc00-7665-11ea-8160-987254fcd4b7.png)
below is my workspace config:
```json
{
	"folders": [
		{
			"path": "/Users/xxx/Desktop/repo/work"
		},
		{
			"path": "/Users/xxx/Desktop/repo/exec"
		}
	],
	"launch": {
		"configurations": [
			{
				"cwd": "${fileDirname}",
				"name": "LAUNCH",
				"program": "${file}",
				"request": "launch",
				"type": "node"
			}
		]
	},
	"settings": {}
}
```

Does this issue occur when all extensions are disabled?:  Yes

**Comment by HeavenSky** [comment]
as before, use my config to debug js file is OK, no popup and work fine. so Is there any change or config I don't know?

**Comment by isidorn** [comment]
Yeah, please try doing what the error is telling you to do. Scope the `${fileDirname}` and `${file}` with the name of your workspace. So for example

**Comment by HeavenSky** [comment]
@isidorn  are you sure that you said can work fine?
 it doesn't work for me ! 
i have the same popup error.

 I switch to the release version. 
yesterday it was OK,today this popup happen again.

**Comment by HeavenSky** [comment]
Now  there is no way for me to solve this problem. i tried you said, or other . But i can't resolve. it influence my daily debug and develop.
