### ISSUE TITLE
Full Restart for VS Code

### ISSUE THREAD

**Issue by joe-herbert** [microsoft/vscode#94423]
There should be a command to fully restart VS Code. I'm aware of the Reload Window command, but this isn't the same as closing all windows and reopening VS Code. The example of the difference I found is when changing the PATH Environment Variable on Windows, the terminal needs to be restarted to take effect. The Reload Window command is not sufficient to restart the terminal, meaning all open windows have to be manually closed and reopened. As someone who has lots of projects open at once, this is frustrating. Admittedly, this is the only difference I've found so far, so the solution could be that the Reload Window command should ensure the terminal is fully restarted.

Note: This is very similar to [Issue #79271](https://github.com/microsoft/vscode/issues/79271), which was closed and locked with an answer which didn't solve the issue.

---
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Shirsendu-Bairagi** [comment]
There should be a commend and also a option is file Menu to manually Restart
