### ISSUE TITLE
Insecure default location for customization files

### ISSUE THREAD

**Issue by Smit-tay** [microsoft/vscode#94436]
When creating a workspace, the *default* location for customized json files, such as tasks.json, launch.json, etc, should *not* be in the project source directory.

This is *BAD* default location, since a full refresh by a revision control system will wipe all those files out.

The current default behavior is just plain wrong.  The default location should be in the users profile area ($USER)/.vscode or similar

**Comment by jrieken** [comment]
We have two locations. One for user-settings (outside your project) and one for project-settings which are meant to be under version control and shared with the team.
