### ISSUE TITLE
SearchEditor: Add command to focus queryEditorWidget

### ISSUE THREAD

**Issue by kdnk** [microsoft/vscode#94439]
I want a command to focus on the queryEditorWidget in SearchEditor.
I use the SeachEditor feature with [VScodeVim](https://github.com/VSCodeVim/Vim) so I frequently use the ESC key. But I put the ESC to switch to normal mode but the cursor focuses on the queryEditorWidget.
I want to set another shortcut to do this but I can't.

I read source code and identified [the cause](https://github.com/microsoft/vscode/blob/6fded8a497cd0142de3a1c607649a5423a091a25/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L227) of the focus on queryEditorWidget by ESC.

If I could I want to add a configurable command like `search.action.focusQueryEditorWidget` to focus on the queryEditorWidget.

**Comment by kdnk** [comment]
@JacksonKearl  Can I contribute to this issue?

**Comment by JacksonKearl** [comment]
@kdnk I'm currently in the middle of a large refactoring of the search editor, which will almost certainly make merging any work you do difficult. However it should be completed in the coming days. 

I may end up fixing this as part of the refactoring, but if not I'll ping you when I'm done!

**Comment by JacksonKearl** [comment]
Hey @kdnk, refactoring is in. If you want to take this onn you can start by looking at how we declare actions here:

https://github.com/microsoft/vscode/blob/379e732c79e6cb0241f95f0e5e45b1dc2255e7ad/src/vs/workbench/contrib/searchEditor/browser/searchEditorActions.ts#L141

and how they get registered and assigned here:

https://github.com/microsoft/vscode/blob/379e732c79e6cb0241f95f0e5e45b1dc2255e7ad/src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts#L209

**Comment by kdnk** [comment]
Thanks! I'll work on it!

**Comment by alexr00** [comment]
When I run the command Search Editor: Focus Search Editor Query Widget nothing happens. I assume I need to take some action first that causes the widget to show. If the command isn't always applicable, it should have a when clause so that it isn't run from the command palette with no effect.

**Comment by JacksonKearl** [comment]
Thanks, fixed.

**Comment by isidorn** [comment]
Still happens. Steps
1. Open search editor
2. Click on Search Viewlet
3. F1 > focus search editor widget -> nothing happens

Also please rename the action to be calles
"focus search editor input"
We never have widget in our UI, it is an implementation details

**Comment by JacksonKearl** [comment]
Thanks, updated.

**Comment by isidorn** [comment]
Thanks, works fine now. Adding verified label.

**Comment by ArturoDent** [comment]
I note that the `when` clause has duplicated `inSearchEditor && inSearchEditor` for this command.

Version: 1.45.0-insider (user setup)
Commit: a0fe37870c42e0704a492cdc6b8550b4cf23f63c
Date: 2020-04-30T05:39:08.281Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19619
