### ISSUE TITLE
File Explorer Outline UI Glitch 

### ISSUE THREAD

**Issue by vinaysharma14** [microsoft/vscode#94431]
Issue Type: <b>Bug</b>

So, I'm using this VS Code:

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

You need to open VS code without any projects or files open. In the file explorer you'll see that the following messages "You have not opened a folder yet" and "The active editor cannot provide outline information" are overlapping above the button "Open Folder".

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
prettier-vscode|esb|4.0.0
rest-client|hum|0.23.2
debugger-for-chrome|msj|4.12.6
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.0.1
java|red|0.59.1
vscode-scss-formatter|sib|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

</details>

<img width="347" alt="Screenshot 2020-04-04 at 2 19 57 PM" src="https://user-images.githubusercontent.com/48080660/78423193-57dabb00-7682-11ea-9e1b-0c32887585dc.png">

**Comment by isidorn** [comment]
Thanks for filling this issue, however duplicate that is fixed in latest insiders. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
