### ISSUE TITLE
Codelens javascript keeps blinking on change

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94438]
```js
class X{
	class = undefined
	name = 'undefined()'
}
class Y{
	foo = 1
	bar = 0
}
```
```
"javascript.referencesCodeLens.enabled": true,
```
![UniqueTatteredFoxterrier-size_restricted](https://user-images.githubusercontent.com/30108880/78450495-26acbb80-767f-11ea-9b95-686d94bb3b2c.gif)
1.43.2

**Comment by mjbvz** [comment]
@jrieken TS returns results relatively quickly in my testing but VS Code core decided to clear the previous lens at some point while the updated lens is still being calculated. If the user is rapidly editing a document, this causes the flashing that @pushkine reported

**Comment by jrieken** [comment]
>  If the user is rapidly editing a document, this causes the flashing that @pushkine reported

@pushkine Is that GIF slow-mo or the actual typing speed?

**Comment by pushkine** [comment]
> > If the user is rapidly editing a document, this causes the flashing that @pushkine reported
> 
> @pushkine Is that GIF slow-mo or the actual typing speed?

hey it actually is slowmo, I reported the issue to gfycat
here is the original : https://giant.gfycat.com/UniqueTatteredFoxterrier.webm
