### ISSUE TITLE
Auto-Format hides lines

### ISSUE THREAD

**Issue by MiguelAtTweddle** [microsoft/vscode#94430]
Issue Type: <b>Bug</b>

After pressing Alt+Shift+F for auto-formatting the file some lines disappear without reason

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.79GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/mrodriguez/Documents/Own/IT/Python/CSV|
|Screen Reader|no|
|VM|27%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
arepl|alm|1.0.22
snapshot-tools|asv|0.4.0
atlascode|atl|2.4.11
vscode-eslint|dba|2.1.2
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.11
gc-excelviewer|Gra|2.1.34
format-python-docstrings|ian|1.2.1
csharpfixformat|Leo|0.0.84
AWK|lug|0.0.2
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.16
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.71659
remote-wsl|ms-|0.42.4
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
vscode-paste-image|mus|1.0.4
material-icon-theme|PKi|4.0.1
vscode-yaml|red|0.7.2
bash-debug|rog|0.3.7
code-settings-sync|Sha|3.4.3
pdf|tom|0.5.1

(2 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/26869871/78421500-82178300-7658-11ea-8eb7-841593a72494.png)

**Comment by jrieken** [comment]
/needsMoreInfo

What language? What formatter extensions?
