### ISSUE TITLE
Ctrl+Shift+P is not Working to open command pallete

### ISSUE THREAD

**Issue by ZOASR** [microsoft/vscode#94447]
Issue Type: <b>Bug</b>

using Ctrl+Shift+P to open the command pallete is not working 
I tried cheking the keyboard shortcuts using the record command option the command "ctrl+shift+p" doesn't register insted it shows like this "ctrl+shift+"
also i tried running 
`` code --disable-extensions``
but still the issue pretains

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.64GB free)|
|Process Argv|D:\CODE\Java_Script\Jquery|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
prettier-vscode|esb|4.0.0
live-p5|fil|1.4.2
code-runner|for|0.9.17
beautify|Hoo|1.5.0
bracket-peek|jom|1.1.2
rainbow-csv|mec|1.6.0
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
material-icon-theme|PKi|4.0.1
vscode-arduino|vsc|0.3.0
vscode-java-pack|vsc|0.8.1
quokka-vscode|Wal|1.0.285
better-align|wwm|1.1.6
material-theme|zhu|3.2.5

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ZOASR** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

the issue still happens in the insiders build

**Comment by ZOASR** [comment]
I discovered the issue a separate software was using up the shortcut preventing vscode from using it
