### ISSUE TITLE
improve incremental search

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#9444]
The current search function is very limited. In particular, it:
* Does not handle multiple cursors - it replaces all the cursors with the current search result.
* Has a separate focus from the text editor, which can be distracting to the user because they have to think about switching between editing and searching. In contrast, Visual Studio has a simple "inline" [incremental search mode](https://msdn.microsoft.com/en-us/library/f27e8wzh(v=vs.90).aspx) (ctrl+i) that maintains the focus in the editor, but captures the user's typing to create a search term. I propose that the user should be able to use either input mode; each has its advantages depending on the situation.
* Regular expression capturing groups are ignored (why not turn each captured group into its own selection?).

*Use case example:* when editing JSON, I find the multiple cursors very useful, but there are times when ctrl+left/right do not move all of the cursors to the correct position because of differences in word boundaries. I would like a way to advance each cursor to the next regexp match.

Two approaches to resolve this issue:

1. Search is an integral function of a text editor, so build these features in.
2. Maybe there are many ways of implementing search, so let the user pick a search extension that works for them. I have attempted to [implement this functionality as an extension](https://marketplace.visualstudio.com/items?itemName=siegebell.incremental-search), but here are some of the issues blocking me from making it a "nice" experience:
  * Add API support to hook into the existing search UI. I'm currently using `showInputBox` -- it works pretty well, but lacks a way to cancel the box (#9377), currently has funny behavior when validation fails (#9376), and does not allow adding buttons to toggle regexp or case sensitivity.
  * Either provide an "inline text input mode" API to temporarily capture text input normally directed toward an editor without a dialog popup or change of focus, or allow an extension to implement this itself. The latter would require an API to unregister handling of the 'type' command so as not to destroy the regular editing experience (#9384).

**Comment by kieferrm** [comment]
@siegebell  I'm a big fan of incremental search and miss it dearly. Do you mind splitting this issues in a couple of different ones? The choices to make are not necessarily mutually exclusive and it makes it easier for us to triage and make decision.

1. Ensure the current find window in an editor works well with multiple cursors
1. Support of capturing groups in find/replace in the editor (as well as the global find/replace)
1. More customizable input box
1. API to temporarily 'steal' keyboard input

**Comment by siegebell** [comment]
@kieferrm okay: #9584, #9587, #9588, #9590.

The API to temporarily 'steal' keyboard input is already supported, but is not usable until #9384 is resolved.

**Comment by kieferrm** [comment]
@siegebell thanks!
