### ISSUE TITLE
Lag when typing

### ISSUE THREAD

**Issue by LykourgosPap** [microsoft/vscode#94448]
Issue Type: <b>Performance Issue</b>

It happens almost every time, whole pc kinda lags, but mostly vscode becomes unresponsive, pressed keys are registered  5 sec after or pressed many times while they were pressed 1 time. It feels like pc is running out of memory? but seeing it from task manager it's always around 70%.

P.S tested with both normal conf and --disable-gpu but didn't noticeany difference

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 4219)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 4200)|
|Memory (System)|7.96GB (2.34GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    78	 14040	code main
    0	   304	  5508	   window (Running Extensions - 2020-project-1-LykourgosPap [WSL: Debian] - Visual Studio Code)
    0	    52	 13224	     extensionHost
    0	    28	 11128	       electron_node wslDaemon.js 
    0	     5	  4644	         C:\Windows\System32\wsl.exe -d Debian sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 0ba0ca52957102ca3527cf479571617f0de6ed50 stable .vscode-server 0  --disable-telemetry'
    0	     5	 11156	           C:\Windows\System32\lxss\wslhost.exe {4a584fbb-bb92-426d-b8ec-a0557f8817cd} 452 460 464
    0	    13	 14308	             console-window-host (Windows internal process)
    0	    11	 11392	           console-window-host (Windows internal process)
    0	   164	  5524	   gpu-process
    1	    72	  6876	   window (Issue Reporter)
    0	    25	 10908	   utility
    0	    66	 12956	   shared-process

Remote: WSL: Debian
CPU %	Mem MB	   PID	Process
    0	     0	   175	remote agent
    0	     0	   189	   watcherService
    0	     0	   207	   extensionHost
    0	     0	   220	     /bin/bash
    0	     0	   226	     /home/lyk/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/node /home/lyk/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=207
    0	     0	   244	     /home/lyk/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/node /home/lyk/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/server.js --node-ipc --clientProcessId=207
    0	     0	   273	     /home/lyk/.vscode-server/extensions/ms-vscode.cpptools-0.27.0/bin/cpptools
    0	     0	   304	       /home/lyk/.vscode-server/extensions/ms-vscode.cpptools-0.27.0/bin/cpptools-srv 273 0
    0	     0	   333	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	   334	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Debian|    Folder (2020-project-1-LykourgosPap): 129 files|      File types: h(21) c(18) o(17) a(8) rle(5) json(3) gif(3)
|                  gitattributes(1) gitignore(1) md(1)
|      Conf files: makefile(11) launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
cpptools|ms-|0.27.0
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
bracket-pair-colorizer|Coe|1.0.61
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.42.4
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
