### ISSUE TITLE
[Feature request] make explicit path directory text ctrl clickable on all file extensions by default

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94444]
This is from a nodejs crash debug.log file
![Code_2020-04-04_18-47-42](https://user-images.githubusercontent.com/30108880/78456711-8ddd6680-76a5-11ea-97db-a1f1aadeb2af.png)
( Artist impression, microsoft paint )
1.43.2

**Comment by isidorn** [comment]
Where are you actually opening those logs? Is that output, debug console, terminal, logs?

**Comment by pushkine** [comment]
> Where are you actually opening those logs? Is that output, debug console, terminal, logs?

npm task exiting with errno 1 links to a nodejs debug file in the terminal

**Comment by isidorn** [comment]
Can you post a picture which shows the whole vscode, that might help me. Thank you

**Comment by pushkine** [comment]
> Can you post a picture which shows the whole vscode, that might help me. Thank you
1) `npm init`
2) add `"scripts": { "test": "node ./undefined.js" },` to `package.json`
3) `npm run test`
4) ctrl click on the file linked in terminal

**Comment by isidorn** [comment]
Seems to be a terminal link detection issue, for now forwarding to @Tyriar

**Comment by Tyriar** [comment]
This is an existing feature, currently spaces in paths are not supported though.
