### ISSUE TITLE
Find and replace button no longer works after "cmd+enter" to replace all

### ISSUE THREAD

**Issue by danawoodman** [microsoft/vscode#94446]
It appears that when trying to do a find and replace and hitting `cmd+enter` to perform the replace, the replace button no longer functions.

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:

1. Use global search to find and replace some text (eg search for "hello world" and for replacement text, have "hello universe")
2. Hit enter to search
3. Go into the replace text field and hit cmd+enter
4. Now shows the search detail tab (this used to trigger the replace from what I remember?)
5. Close that tab and now try to execute the replace again

Result is the replace button does nothing. Have to reload the window for it to work again

![](https://p198.p4.n0.cdn.getcloudapp.com/items/DOu8zvlg/Screen%20Recording%202020-04-04%20at%2015.11.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jcogs** [comment]
I'm experiencing the same thing. As a work-around I've been using the "replace all" button for each individual file in the search results.

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by roblourens** [comment]
The shortcut is cmd+alt+enter, I think you are opening the search editor. But, there is a bug in this flow that breaks the replace button, and this should be fixed in 1.44. Please update and try again.
