### ISSUE TITLE
Move Caret Left/Right With Empty Selection Marks Document Unsaved

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/vscode#94456]
Issue Type: <b>Bug</b>

Open some file.
The file is marked saved (no circle at the X in the top)
Put the cursor somewhere, be careful to select nothing.
Execute one of the commands Move Caret Left/Right.
The document is marked unsaved.

In issue #82631 it's noted that these commands actually moving the selection around, but if the selection is empty they do nothing and shouldn't mark the document unsaved.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
I guess I am getting a model change event, how would the document get dirty otherwise. Moving to Alex.

**Comment by alexdima** [comment]
I cannot reproduce. The fix for #82631 only just shipped with 1.44.

@ChayimFriedman2 Can you please try reproducing with the latest VS Code (1.44) ?

**Comment by ChayimFriedman2** [comment]
No, that seems to be fixed in 1.44. The reason is probably another improvement: the commands do nothing when there is nothing selected now...
