### ISSUE TITLE
Problem when compiling a C project

### ISSUE THREAD

**Issue by VALefevre** [microsoft/vscode#94452]
- VSCode Version: 1.43.2.0
- OS Version: Windows 10, 18362.720

I can not run any C projects.
When I press 'f5', this happens: ![image](https://user-images.githubusercontent.com/62857908/78464505-ae7bdf80-76ea-11ea-94e6-b30821fafc29.png)
I have of course installed and enabled the C/C++ extension. I have also installed mingw and the correct files (gcc.exe and g++ exe) and have added the path to this folder in some settings in the properties of my computer, as a video said.
Nothing changes.
I don't know if I'm reporting a bug, or asking for help, but in both cases I would appreciate an explanation on how I could solve that!
Btw: I tried to totally uninstall and reinstall vscode, but it hasn't helped at all.
Btw ps: I can do ctrl+shift+B, it does nice things and then says "The terminal process terminated with exit code: 1". Then pressing 'f5' does the same as always (see attached screenshot)
Btw pps: the project can be compiled properly since it works very well with CodeBlocks

Does this issue occur when all extensions are disabled?: Yes.

Thanks in advance.

**Comment by razex89** [comment]
Hello sir, 
Have your looked on these?
https://code.visualstudio.com/docs/cpp/config-mingw
https://code.visualstudio.com/docs/cpp/launch-json-reference
