### ISSUE TITLE
Allow looping through quick fix menu suggestions

### ISSUE THREAD

**Issue by Ericnr** [microsoft/vscode#94451]
It would be a little better experience to be able to press arrow up when the first suggestion in the quick fix menu is highlighted, and have it loop to the last suggestion, and vice-versa. 

edit:
vscode version: 1.43.1
OS: macOS 10.12.6

**Comment by mjbvz** [comment]
What OS and VS Code version?

/needsMoreInfo

**Comment by Ericnr** [comment]
edited to add more info

**Comment by mjbvz** [comment]
We use the native MacOS context menu here which also does not support cycling through selections. Closing this as I don't think we can work around the issue
