### ISSUE TITLE
`workbench.view.alwaysShowHeaderActions` for notebook cells

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94455]
We have `workbench.view.alwaysShowHeaderActions` in the viewlet to make view actions not visible based on hover, but instead always visible. It would be nice to have this for notebook cell actions too. For some (including myself) UI elements coming in and out of visibility based on cursor movement is distracting and it would be nice to have a way to allow the actions to always be available. 

Perhaps this could be rolled in with `workbench.view.alwaysShowHeaderActions` to a new setting, like "workbench.reduceUIFlicker" or something.

**Comment by roblourens** [comment]
We do have settings to control the visibility of the cell toolbar now
