### ISSUE TITLE
VSCode crashes after pressing ctrl + j

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#94454]
Issue Type: <b>Bug</b>

I moved all views in panel to sidebar and VSCode crashed the first time I pressed ctrl + j to show panel. I can consistently repro this issue.

VS Code version: Code - Insiders 1.44.0-insider (e8dbc5ea6092ba73ae70069d3e730f2cc56addff, 2020-04-03T23:31:33.481Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sbatten** [comment]
To Verify:
1. Move all panels to the sidebar (panel will hide)
2. Press Ctrl+J
3. Check that the panel opens to an empty view e.g. (empty Terminal View) and that you do not crash.

We will iterate on a better UX next milestone.

**Comment by sbatten** [comment]
@sandy081 I made this change as the safest option for now. If you have a better solution that warrants another fix, please take over. Otherwise, will roll with this.

**Comment by sandy081** [comment]
Yah looks the safest fix for now. Seems panel is not ready to handle no active panels. Is there a follow up issue for this created?

**Comment by NotWearingPants** [comment]
@sandy081 but the panel *does* handle no active panels if you run the `Focus into Panel` command instead of `Toggle Panel` (<kbd>Ctrl</kbd>+<kbd>J</kbd>)

**Comment by sandy081** [comment]
Yeah there are some issues with it and it is not working always. Hence we did a safe fix for now. We are working on this with proper UX for next milestone.
