### ISSUE TITLE
Terminal does not to show an occurred error as a link

### ISSUE THREAD

**Issue by ebonat** [microsoft/vscode#94457]
Terminal does not to show an occurred error as a link.

Steps to Reproduce:

1. Run any Python code with any error and this error will not have any link to point to the line number where it occurred in the terminal. 

This is very important to click on the link and jump to the line of code where it's occurred. I'm using VS Code 1.43.2 release.

Thank you for your help.

**Comment by Tyriar** [comment]
Please provide OS distro/version and a screenshot of the error that doesn't get a link

**Comment by ebonat** [comment]
OS distro/version:

Version: 1.43.2 (user setup)
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Simple Python code:

import urllib
print("urllib: {}".format(urllib.__version__))

Error:

File "e:/Visual WWW/Python/1000_python_workspace/versions_check/src/versions.py", line 74, in main 
    print("urllib: {}".format(urllib.__version__))
AttributeError: module 'urllib' has no attribute '__version__'

The line:

File "e:/Visual WWW/Python/1000_python_workspace/versions_check/src/versions.py", line 74, in main 

should be a link to point to line 74 where the error occurred. this happens all the time with VS Code Version: 1.43.2

thanks for your help!

**Comment by Tyriar** [comment]
This is happening because of the space in the path which isn't supported yet but should be eventually.

**Comment by ebonat** [comment]
OK, so what do we do now? any work around available at this time?

**Comment by Tyriar** [comment]
Current workaround is to use double click to copy the URL and then ctrl+p to open the file

**Comment by ebonat** [comment]
The file is already open in VS Code!

**Comment by Tyriar** [comment]
If you're after go to line it's ctrl+g, 74

**Comment by ebonat** [comment]
OK - thanks!
