### ISSUE TITLE
TypeScript constructor find References

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9445]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Feature request:

Ability to `Find All References [Shift+F12]` when executing on constructor - right now it shows `No results`: 
![image](https://cloud.githubusercontent.com/assets/1723815/16923943/cae2bcd0-4cea-11e6-9aa8-5b13839d763e.png)

I guess it should show all `new MyClass(..)` references

**Comment by dbaeumer** [comment]
Agree. Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10131
