### ISSUE TITLE
HDR display settings

### ISSUE THREAD

**Issue by wVio** [microsoft/vscode#94462]
Windows 10 Pro 1909 18363.752 / NVidia 445.75 DHC / Color depth: 32bit / Output colol depth: 12bpc / Output color format: RGB / Ouput dynamic range: Full / 3840x2160 (native) / 60Hz
Windows 10 Display settings: HDR games and apps: on.
Every app runs and display correctly. (e.g. Visual Studio 2015 community edition)
VC 1.43.2 (user setup) display it is unusable for me, in Dark mode text are too dimmed. The only option I have is to run it by
**Code --force-color-profile srgb**

This problem persists for months, not only for these versions.

I cannot find any settings equivalent for this.

**Comment by deepak1556** [comment]
Thanks for the report, please follow https://github.com/microsoft/vscode/issues/88491
