### ISSUE TITLE
Auto import for Typescript in React

### ISSUE THREAD

**Issue by Kaos1105** [microsoft/vscode#94467]
Issue Type: <b>Bug</b>

Import suggestion not work at all. Oddly when i uninstall an extention and reload Visual Studio Code, it worked

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.94GB (6.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-sqlite|ale|0.8.1
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.901.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.2
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|2.7.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.0.0
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
angular2-switcher|inf|0.3.3
search-node-modules|jas|1.3.0
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|9.1.2
rn-full-pack|kel|0.7.0
vscode-language-babel|mgm|0.0.26
theme-monokai-pro-vscode|mon|1.1.15
vscode-cosmosdb|ms-|0.12.2
csharp|ms-|1.21.16
azure-account|ms-|0.8.8
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.0.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
gitblame|wad|3.2.0
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0
material-theme|zhu|3.2.5
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as caused-by-extension since it sounds like problem went away when you uninstalled one of them
