### ISSUE TITLE
Allow auto-save when editor loses focus even if file has not been modified!

### ISSUE THREAD

**Issue by PurifierPhoenix** [microsoft/vscode#94461]
The title basically says it all, but this is mainly to remedy the fact that some operating systems such as macOS don't update access times properly, so trying to filter out files that have been last accessed with say ls to pass as an argument for a compiler command doesn't always yield correct results.  However, when re-saving a file, even when it hasn't been modified works.

**Comment by sportshead** [comment]
You can use Auto Save `afterDelay` and set the time you want.

**Comment by Shirsendu-Bairagi** [comment]
Good feature

**Comment by PurifierPhoenix** [comment]
This may be hacky, but why not allow short-cut key bindings or commands to be invoked when an event happens. if we had settings such as "workbench.event.editor.outOfFocus": "ctrl+s" or "workbench.event.editor.outOfFocus": "File: save".
