### ISSUE TITLE
There are any plan to  support the command from bash for windows ? like git

### ISSUE THREAD

**Issue by vanntian** [Microsoft/vscode#9446]
- VSCode Version:1.3.1
- OS Version:windows 10 14390.0

bash for windows is awesome,but the current visual studio code does't support it.

**Comment by Tyriar** [comment]
Do you mean running vscode from it? Because that's not supported by the Windows feature. It runs native Linux apps so the Windows executable won't work. It also doesn't ship with a Windows system so you can't launch the Linux binary either (at least without a bunch of setup).

**Comment by rhires** [comment]
I think maybe it's the other way around: will there be a setting in VSCode where a Windows user can choose which terminal to use? Right now, I think it runs cmd by default, but idk if I can run PowerShell as the terminal, and now that bash is going to be available on Windows 10, will we be able to choose that instead of cmd?

**Comment by Tyriar** [comment]
@rhires it's been possible to do that from the start. Documentation was added recently, see https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

**Comment by rhires** [comment]
Thank you!!

**Comment by vanntian** [comment]
@Tyriar 谢谢（thank you！），from china

**Comment by techbykyle** [comment]
What about the git tab in VSC? It still wants me to use Chocolatey or git-scm. How do you point VSC to the native Ubuntu git?

Tried doing something like: "git.path": "C:\\Users\\Username\\AppData\\Local\\lxss\\rootfs\\usr\\bin". Did not work.

**Comment by Tyriar** [comment]
@techbykyle that's a different feature that I'm not familiar with, if you can't figure it out from the documentation you should file a different issue.
