### ISSUE TITLE
JSDoc block hinting broken for object methods using 'comma first' code style

### ISSUE THREAD

**Issue by alystair** [microsoft/vscode#94465]
- VSCode Version: 1.43.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Our codebases use and enforce the `"comma-style":[2,"first"]` eslint rule.

JSDoc blocks prior to functions within objects are being ignored. This is likely due to the jsdoc parser halting at the comma prior to the function - it should recognize this code style and work appropriately.

```js
let working = { // Comma last style - works as intended
	/**
	 * This jsdoc works.
	 */
	functionA(){ return true; },
	/**
	 * This jsdoc also works.
	 */
	functionB() { return false; }
};

let broken = { // Comma first style
	/**
	 * This jsdoc works.
	 */
	functionA(){ return true; }
	/**
	 * This jsdoc does not.
	 */
	, functionB() { return false; }
};
```
Steps to Reproduce:

1. After pasting the code above, start typing `broken.functionA(`, observe popup appears.
2. Do the same with `broken.functionB`. Popup does not appear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alystair** [comment]
@mjbvz where would I even start in the code base to contribute a fix for this? I feel it's more of a bug than a feature.

**Comment by mjbvz** [comment]
This is a non-trivial addition so we're gauging community interest. If a lot of people use this code style, we'd consider looking into supporting it better

(I personally had never seen that JS formatting style before your example)

**Comment by alystair** [comment]
Even if it's non-trivial I'd love to know if it's something I might contribute, could you provide a hint towards where the current implementation so I can review it?

**Comment by mjbvz** [comment]
We'd only consider adding this feature if enough user demand for it
