### ISSUE TITLE
Linux: Ctrl+Click Go to definition changed

### ISSUE THREAD

**Issue by alethenorio** [microsoft/vscode#94463]
Issue Type: <b>Bug</b>

Until recently I used to be able to Ctrl+Left mouse click to go to the definition of a variable/function etc... however as of late it instead adds another cursor. 

After some fiddling around I found out that Alt + Click goes to definition now instead.

I am unable to set it back (as there does not seem to exist a way to change mouse shortcuts in vs code)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3056)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.40GB (7.67GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.11.0
better-toml|bun|0.3.2
gitlens|eam|10.2.1
vscode-docker|ms-|1.0.0
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.42.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.27.0
Go|ms-|0.13.1
rust|rus|0.7.0
cfg-language-features|weg|1.0.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Any change that you fiddled with this setting `editor.multiCursorModifier`

**Comment by alethenorio** [comment]
Thank you for replying @jrieken 

I have to say that I did not fiddle with that setting, at least not recently when it was working fine.

I went ahead and disabled all my plugins except the Go support one just to make sure they were not playing around with my settings and the issue was still there.

I proceeded to dig into my user preferences and indeed I found this setting in there

```json
"editor.multiCursorModifier": "ctrlCmd"
```

I commented that out and now things are working as intended. I am fairly certain I did not touch that setting anytime recently and even if I did, as you can see, it was mapped to `ctrl` so the question is whether there is a bug when parsing that setting on Linux which changed behaviour recently?

**Comment by jrieken** [comment]
This setting has been added 3yrs ago: https://github.com/microsoft/vscode/blob/f913854bd66362a1350ea43c305ad92c151796bf/src/vs/monaco.d.ts#L2876. Pretty sure that nothing has changed.

**Comment by alexdima** [comment]
The setting is also changed when clicking in the menu on `Selection > Switch to Alt+Click for Multi-Cursor`.
