### ISSUE TITLE
Don't prompt to save file on close when autosave: onFocusChange

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94476]
Current flow when attempting to close a dirty editor when `"files.autoSave": "onFocusChange"`:

1. Close editor
2. Dialog: "Do you want to save the changes you made to ...?"
3. As soon as dialog opens, focus leaves editor and it autosaves

I think we can just skip 2 all together and have it save then close on attempt to close if `"files.autoSave": "onFocusChange"` is enabled. Especially given the confusing UX that `Don't Save` wont revert the autosave it just performed.

**Comment by sportshead** [comment]
So you're saying that you want the editor to save when the user clicks on the x?
Probably put a check here: https://github.com/microsoft/vscode/blob/6526fe0a1ade9d8f6e566811f4118191b84bf9f7/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1318
and here:
https://github.com/microsoft/vscode/blob/6526fe0a1ade9d8f6e566811f4118191b84bf9f7/src/vs/workbench/browser/parts/editor/editorActions.ts#L580

Don't know which one to add a check or maybe both? Can make a PR

**Comment by bpasero** [comment]
**Verification:**
* configure `autoSave: onFocusChange`
* make a normal editor dirty and verify you are not being asked to save when either closing that editor or closing all editors (e.g. from the "Open Editors" close all action)
* repeat the steps but this time have an untitled editor
  * closing the untitled editor should still prompt
