### ISSUE TITLE
Support cygwin in the default shell selector

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#94473]
Issue Type: <b>Feature Request</b>

Cygwin shell is not supported in vscode, would like to see this made available.

![cygwin](https://user-images.githubusercontent.com/439226/78504112-f45f9480-7738-11ea-8452-d47719b56d39.png)

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:40:52.685Z)
OS version: Linux x64 5.5.13-1-default

**Comment by IllusionMH** [comment]
Have you tried to add path to executable manually?

**Comment by Tyriar** [comment]
I tried adding cygwin to that dropdown a while ago but ran into problems as it needs special arguments to work and currently the "profiles" in the shell selector don't support args. See https://stackoverflow.com/questions/46061894/vs-code-cygwin-as-integrated-terminal for how to use it manually.

**Comment by rajinder-yadav** [comment]
@Tyriar Just a suggestion, maybe open a ticket requesting support for what you need to get cygwin working with vscode? I'm sure the cygwin team would welcome this.

I'll take a look at the link you provided, thanks.

**Comment by Tyriar** [comment]
@rajinder-yadav I don't think we need anything in particular, more of a problem on our end that the shell selector only sets the executable currently, not the args.

**Comment by rajinder-yadav** [comment]
@Tyriar the stackoverflow tip worked for me as a work-around thanks!

**Comment by TylerLeonhardt** [comment]
@meganrogge I noticed that cygwin isn't here:
![image](https://user-images.githubusercontent.com/2644648/112217591-f340a500-8bdf-11eb-8743-c5ce103c4804.png)
but it is here:
![image](https://user-images.githubusercontent.com/2644648/112217667-094e6580-8be0-11eb-9301-500c10e245ad.png)

is that expected? If so feel free to mark as verified

**Comment by Tyriar** [comment]
@TylerLeonhardt that's by design, the thinking here being that cygwin wouldn't be used as often as the others so you need to explicitly add it.
