### ISSUE TITLE
ts-jest aliases does not work: Cannot find module '@/server'.ts(2307) but code compiles normally

### ISSUE THREAD

**Issue by kuskoman** [microsoft/vscode#94474]
- VSCode Version: 1.43.2
0ba0ca52957102ca3527cf479571617f0de6ed50
x64
- OS Version: Windows 10 Education

Steps to Reproduce:

1. Create any TypeScript file
2. Install typescript, ttypescript, jest, ts-jest
3. IDE will show `Cannot find module <file> (2307)` for every file using moduleMappings

Example:
jest.config.js: 
```javascript
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/test'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest'
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@@/(.*)$': '<rootDir>/test/$1'
  }
}
```

part of the test file:

```typescript
import { DateTimeInput } from '@/generated/prisma-client'
import { startTestServer } from '@@/helpers/apolloInstance'
import prisma from '@@/helpers/prismaInstance'
import { createUser } from '@@/helpers/userHelper'
import { toPromise } from 'apollo-link'
import gql from 'graphql-tag'
```

every line using '@' or '@@' has a red underline and error message

![error image](https://i.imgur.com/cFNAdIE.png)

tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "dist",
    "lib": ["es6", "es7", "esnext", "dom"],
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "@@/*": ["test/*"]
    },
    "esModuleInterop": true,
    "plugins": [{ "transform": "typescript-transform-paths" }]
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"]
}
```

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment]
In the test file, run `TypeScript: Go to project configuration`. Does this open the correct `tsconfig`?

If so, can you please share a complete minimal project that demonstrates this issue?

**Comment by kuskoman** [comment]
Effect of `TypeScript: Go to project configuration`:
![error message](https://i.imgur.com/2vOdVRh.png)
![project screen](https://i.imgur.com/GzfLlaT.png)

@mjbvz I created a repository [example-vscode-error](https://github.com/kuskoman/example-vscode-error)

**Comment by mjbvz** [comment]
Thanks. This helped me understand the problem.

The issue is that the test file is not considered part of the `tsconfig` project. This is because the project sets:

```json
  "include": ["src/**/*.ts"],
```

so only files under `src` are considered to be part of that tsconfig project. If you want the `paths` to apply to your tests as well, make sure to also include the `test` directory in your tsconfig

**Comment by kuskoman** [comment]
@mjbvz I understand that you do not consider it as a bug, however your answer is not helpful and may be misleading for other people- adding test directory to include is workaround, not a solution. There is no reason to compile dozens of test files just to make IDE not throwing errors.
Jest (with ts-jest preset) and probably other test framework are able to use tsconfig.json to get path aliases, while their files are not included in tsconfig.
I would also mention thing that VSCode does not properly support Jest is even more annoying because of lack of easy ways to change it (at least I don't know any way to disable path errors for specific directory, without disabling rest of ts server features).

**Comment by mjbvz** [comment]
If you want that `paths` setting from a `tsconfig` to apply in a file, that file needs to be part of a `tsconfig` project. Either:

- Create another tsconfig under tests that also configures `paths`. Make sure the tests files are part of this
- Or create a `tsconfig.src.json` at the top level of your project and use that compile. This tsconfig can extend your `tsconfig.json` but should include files from `src`

VS Code itself is library agnostics so are not going to special case how we handle ts files that look like they might be jest tests
