### ISSUE TITLE
Keyboard shortcuts not visible in menu on Ubuntu

### ISSUE THREAD

**Issue by elentirmo** [Microsoft/vscode#9447]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:28:46.761Z)
- OS Version: Ubuntu Linux Xenial Xerus (16.04), with Linux x64 4.4.0-28-generic

Steps to Reproduce:

1. Start Visual Studio Code on Ubuntu
2. Open a menu, e.g. View
3. Notice that key bindings/shortcuts are not shown after each item.

Even though the shortcuts are not shown, they do work normally.

Other programs on Ubuntu (e.g. the file manager) show shortcuts as grey text beside the menu item label.

![image](https://cloud.githubusercontent.com/assets/5021259/16924803/5436b4ba-4d21-11e6-90f1-3a78cd26ee11.png)

**Comment by bpasero** [comment]
@Tyriar did you ever see this?

@elentirmo anything in the developer console?

**Comment by Tyriar** [comment]
Yes, I think this is an upstream issue. Chrome and Atom don't do it either but it is definitely possible on the OS as they show in `gedit`.

**Comment by elentirmo** [comment]
The only message in the developer console is this one:

> Conflict detected, command `workbench.action.output.toggleOutput` cannot be triggered by ctrl+shift+h due to workbench.action.replaceInFiles

Chrome and Chromium don't show keyboard shortcuts either.

**Comment by elentirmo** [comment]
I just checked on Ubuntu 14.04 (Trusty): shortcuts are visible in VS Code, Google Chrome and Atom. So it seems to depend on the Ubuntu version.

**Comment by elentirmo** [comment]
Similar bug in Atom: https://github.com/atom/atom/issues/11522

**Comment by elentirmo** [comment]
Reported in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=636718

**Comment by bpasero** [comment]
Thanks for linking the issues here 👍

**Comment by ewot** [comment]
Fixed in Ubuntu 16.10 rc. Seems like all chromium based applications are working for me now. :tada:

**Comment by elentirmo** [comment]
Since @ewot discovered that the issue is fixed in a more recent Ubuntu, it would seem likely that this was a Unity bug.
