### ISSUE TITLE
Support multiple saved sessions

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#94479]
When I close vscode with unsaved files it saves the session and exits without prompting to save. This is a great feature. However, if I have 2 instances of vscode open and I attempt to close one of them it prompts me to save. I'd like it to simply save the session like it does for the single instance case.

The same issue existing when running a single instance and attempting to switch to another folder or workspace.

It seems vscode nearly supports this capability already. Each folder or workspace I open remembers which editors are open, as long as they don't have unsaved changes. It's unclear why this doesn't extend to editors with unsaved changes, but I very much wish it did.

**Comment by Tyriar** [comment]
Use this setting to also how exit on "window close":

```
"files.hotExit": "onExitAndWindowClose"
```

**Comment by akbyrd** [comment]
Ah, I didn't catch the setting, thanks! Apologies for the unnecessary issue.
