### ISSUE TITLE
IntelliSense doesn't recognise PHP snippets inside HTML blocks

### ISSUE THREAD

**Issue by energylevels** [microsoft/vscode#94481]
- VSCode Version: 1.43.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create php snippet with "scope": "php,html"
2. Enter the trigger word inside a HTML block

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Please share the snippet, the html-file, the position at which you have tried, and how you have tried this

**Comment by energylevels** [comment]
I think I worked round this, I'm new to VSCode so learning/working my way through it. 

If I want to create a commonly used code snippet that includes PHP tags like:

`<?php include 'header.php'; ?>`

Then I need to put the snippet inside my html.json snippets file and intellisense will show it when cursor is inside a html block/code.

The alternative snippet for PHP blocks would be to add the following to my php.json:

` include 'header.php';`

I'm assuming that this behaviour is deliberate in VSCode ... Thanks for coming back to me.

**Comment by jrieken** [comment]
Yes - that's how it work.
