### ISSUE TITLE
Closing find widget while it is opening can disable it and leave it open

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#94485]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Press <kbd>F3</kbd> and <kbd>Escape</kbd> at the same time (but in that order)
2. The find widget will open but be disabled

Notes:
- You cannot use the widget or close it while it is disabled, until you "open" it again. also for some reason the "Find in selection" button still works.
- This also works with <kbd>Ctrl</kbd>+<kbd>F</kbd> instead of <kbd>F3</kbd>, but it's harder to press it together with <kbd>Escape</kbd> fast.
- From testing it seems that `findWidgetVisible` is `true` after pressing <kbd>F3</kbd>, and that it does change to `false` after pressing <kbd>Escape</kbd>, so vscode thinks the widget was closed, that's probably why it is disabled.

VS Code version: Code - Insiders 1.44.0-insider (e8dbc5ea6092ba73ae70069d3e730f2cc56addff, 2020-04-03T23:31:33.481Z)
OS version: Windows_NT x64 10.0.18363

Extensions: none

**Comment by NotWearingPants** [comment]
This isn't a duplicate of the suggested issues.

**Comment by rebornix** [comment]
F3 and then escape closes the find widget in latest Insiders, closing it for now but we can report if you are still seeing it.

**Comment by NotWearingPants** [comment]
This appears to be fixed in 1.52.
@rebornix Can you link to your PR and also explain why `setTimeout` is necessary here?
