### ISSUE TITLE
Activity Bar Icons don't show

### ISSUE THREAD

**Issue by munrodnz** [microsoft/vscode#94482]
- VSCode Version: 1.44.0-insider (user setup)
- OS Version: Windows 10 Enterprise 10.0.18363

Steps to Reproduce:

1. Start Visual Studio Code
2. No Icons except the default ones appear.
3. Not sure if there is something wrong with my User Profile in normal Code or Insiders
4. With the Extensions loaded I can hover over the Activity Bar where they should be and I can click on the link and start the extension just no icon being displayed.

Does this issue occur when all extensions are disabled?: No due to there be no Extensions with Icons needing to be loaded. I have tried it in the non-Insiders version and loading only one or two Extensions and the Icons don't work then either.

**Comment by sandy081** [comment]
- Does it reproduce if you reload the window?
- Can you please try using fresh user data dir. Start code from command line as follows
`code --user-data-dir <path to a temp user data dir>`
- Open Developer tools (Developer: Toggle Developer Tools). Go to elements tab and inspect the element. Let me know where the icons are located. See eg:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/10746682/77729242-772c7500-6ffe-11ea-8fb3-3c9205e65062.png">

Can you please open network tab and check what is being returned for this svg file?

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/10746682/78548278-d3fb0d00-7800-11ea-848d-1c6497529420.png">

**Comment by munrodnz** [comment]
Hey @sandy081 thanks for your help. I think I may have spotted the issue, another App is the Default for SVG files which may be causing VS Code to fail to display the Icon. You can see from the screen below the behaviour I am getting, this is in VS Code and the same happens in the Insiders version.

![image](https://user-images.githubusercontent.com/14269842/78608047-45e05e80-78b4-11ea-890b-1a653e776d56.png)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/92323
