### ISSUE TITLE
The terminal process terminated with exit code: 3221225477

### ISSUE THREAD

**Issue by Savinda1995** [microsoft/vscode#94499]
my vs code terminal wont open it closes with a message "The terminal process terminated with exit code: 3221225477"

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo specifically version and platform information. The About option of the Help menu might have a handy Copy button for this purpose.

Also look at #91044 and see if that issue matches yours.

**Comment by Savinda1995** [comment]
windows 10 
Version 1.43.2

**Comment by Savinda1995** [comment]
> 
> 
> /needsMoreInfo specifically version and platform information. The About option of the Help menu might have a handy Copy button for this purpose.
> 
> Also look at #91044 and see if that issue matches yours.

windows 10
Version 1.43.2

**Comment by gjsjohnmurray** [comment]
Please post your full Windows version string.
