### ISSUE TITLE
Does not display === markdown content correctly in Preview mode

### ISSUE THREAD

**Issue by vairamsvsjdo** [microsoft/vscode#94497]
- VSCode Version: 1.43.2
- OS Version: Windows_NT x64 10.0.19041

Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
Steps to Reproduce:

1.  [Add File Association](https://github.com/JayDevOps/testmd/blob/master/.vscode/settings.json)
```json
"files.associations": { 
  "*.asc": "markdown"
}
```
2.  [Added markdown in file](https://github.com/JayDevOps/testmd/blob/master/testgit.md)
```markdown
=== Recording Changes to the Repository
Normal Content
```
3. Ctrl+Shift+V To Preview in markdown, it does not respect heading.
4. [Whereas github is able to display content correctly]
(https://github.com/JayDevOps/testmd/blob/master/testgit.asc)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
VS Code requires [Commonmark](https://commonmark.org/) syntax. Use # characters to mark headings.

**Comment by vairamsvsjdo** [comment]
Yes you are correct. There is an extension already. It is just that extension has issues. I have created a ticket in that [repo, Asciidoc]{https://github.com/asciidoctor/asciidoctor-vscode/issues/293}
Thanks
