### ISSUE TITLE
Windows is painfully too slow to debug nodejs app

### ISSUE THREAD

**Issue by mauricionr** [Microsoft/vscode#9449]
VSCode take too much time to start debugging, some times didn't start the debug.

- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/2263551/16925019/8e13ceda-4cf8-11e6-843d-a559ddb4a050.png)

- OS Version:
Microsoft Windows [Version 10.0.14390]

Steps to Reproduce:

1. Open some nodejs project
2. Hit F5 to start debugging

![Too slow to debug](https://media.giphy.com/media/5l4Q9CZu6HIEo/giphy.gif)

Thankss!

**Comment by mauricionr** [comment]
I'm using node:

![image](https://cloud.githubusercontent.com/assets/2263551/16952369/4c0bb35c-4d9f-11e6-82a0-e91d47ebd8f3.png)

**Comment by mauricionr** [comment]
I got a new behavior, 

When i restart my computer i'm able to debug once,  after stop it i can't start debug again.

**Comment by weinand** [comment]
@mauricionr I cannot decypher the screenshot. Could you share the code so that I can try to reproduce the problem?

**Comment by mauricionr** [comment]
@weinand i could reproduce the same issue with this project [csnodeapi](https://github.com/mauricionr/csnodeapi)

**Comment by mauricionr** [comment]
I guess could be my windows 10 version, i switch to my vm and it works normaly

![image](https://cloud.githubusercontent.com/assets/2263551/16963196/9802e222-4dcb-11e6-9ee9-faa1438fe484.png)

**Comment by mauricionr** [comment]
@weinand i have an update available, i will update and check if this issue is fixed!

Thanks!!

**Comment by mauricionr** [comment]
@weinand i've updated my windows 10 insider preview to 

![](https://cloud.githubusercontent.com/assets/2263551/16963546/5935b7e8-4dcd-11e6-9ee5-10f294ae0c54.png)

Debugging normally now!

Thanks!

**Comment by weinand** [comment]
@mauricionr great to hear, thanks!
