### ISSUE TITLE
There should be an option to hide the menu bar.

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#945]

**Comment by alexandrudima** [comment]
Not sure if the fullscreen mode does this

**Comment by be5invis** [comment]
@alexandrudima Full screen mode indeed hides menu bar, but providing an option for normal mode is better.

**Comment by bpasero** [comment]
Sounds like a good area for a PR.

**Comment by rstat1** [comment]
If no one else is working on this, I'll take it.

**Comment by bpasero** [comment]
:+1:

**Comment by egamma** [comment]
It isn't on the December plan #917

**Comment by be5invis** [comment]
And well to avoid some inconvenience you can add a command to show the menu temporary.

**Comment by rstat1** [comment]
@egamma should I wait until January then? Or no?

**Comment by bpasero** [comment]
@rstat1 this just means we will not work on it so feel free to do the PR.

**Comment by rstat1** [comment]
So pull request #1090 is my attempt at adding this feature, please take a look and feel free to yell at me if I did it wrong :P

**Comment by bpasero** [comment]
This is Windows only.

**Comment by ristomatti** [comment]
@bpasero I couldn't find this from the backlog anymore. Is this issue still open? Also I didn't quite follow why the issue title was changed to target Windows only? I would really like to see this feature in Linux too!

One of the biggest reasons I like to use minimalistic editors is that I hate wasting screen space for stuff I will most certainly use through a keyboard or command palette. In case this is closed/removed from the backlog, should I create another feature request for it?

**Comment by bpasero** [comment]
From my testing the function I used to hide the menu did not work on Linux.

**Comment by ristomatti** [comment]
I figured that from the context but I don't see why that would affect this issue. The original issue reported by @be5invis had no platform defined IIRC. Maybe there's something I'm missing here but to me it seems like this issue is still a valid feature request (at least for the other platforms), and therefore should not be closed as the issue is not resolved.

I can report this separately as a multi-platform feature request in case that helps in some way (as this issue is already closed)?

**Comment by ristomatti** [comment]
I was tipped about the User Voice service on an another issue. In case it's of any help mapping GitHub issues and User Voice feature requests, here's a matching User Voice feature request: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8345181-hide-menu-bar

**Comment by bpasero** [comment]
Feel free to open a new feature request for linux

**Comment by bpasero** [comment]
Actually it seems that some Linux distros might support this feature so i could enable it for Linux too, but I cannot get it to work on Ubuntu 15 at least. @ristomatti would you be willing to try it out on your Linux distro?

**Comment by ristomatti** [comment]
@bpasero I'd be happy to do that. Just point me to the right direction what I need to do. Should I setup a Code development environment and then apply the pull request as a patch? Or is there a simpler way to do this?

**Comment by bpasero** [comment]
@ristomatti yes if you can setup VS Code to run out of sources on your Linux box, you can basically just flip the boolean flags for `isWindows` to `isLinux` here to give it a try: https://github.com/Microsoft/vscode/commit/c34d2e771bb3e372e912e081a8bd8879a92a8c91

**Comment by LiZhenNet** [comment]
I have hidden Menu Bar，but I do not konwn how to show it？keyboard shortcut？

**Comment by bpasero** [comment]
@LiZhenNet you can press the Alt key to bring it back briefly or F1 to find the command to toggle the setting back.

**Comment by yisk** [comment]
You should show a hint about "Alt" every time user hides menu. I just waste an hour searching for how to unhide the menu.

**Comment by bpasero** [comment]
We do that for our 1.0 release. You can always access any commands (including the menu toggle) from the command palette (Ctrl+Shift+P).

**Comment by Heather** [comment]
may you point where I can correct translation of this menu action

**Comment by bpasero** [comment]
You can file a bug on it.

**Comment by NiggyWizzyWoz** [comment]
How do I overwrite the behaviour of the alt key?? 

Tried this but didn't work:
keybinding.json:
	{
		"key": "alt",
		"command": "",
	}

**Comment by bpasero** [comment]
@NiggyWizzyWoz our next release adds a new setting `window.menuBarVisibility` that you can set to `hidden` to not show it even when you press Alt.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by paradigmist** [comment]
@bpasero  I have tried your solution, but the menu bar is still invoked by alt key.

**Comment by bpasero** [comment]
@paradigmist and how did you change the setting? to what value?

**Comment by paradigmist** [comment]
@bpasero 

```
{
    "window.menuBarVisibility": "hidden"
}
```

**Comment by bpasero** [comment]
It should work from our current insider build (1.10.0).

**Comment by vfhky** [comment]
You can edit the settings.json and append the configs blow.
`"window.menuBarVisibility": "toggle"`
Then you can use the key of Alt to switch.
