### ISSUE TITLE
not able to format sass file

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#9450]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:28:46.761Z)
- OS Version: Linux x64 4.4.0-31-generic

Steps to Reproduce:

1.  open a sass file
2. right click, shows not options for formatting.

**Comment by ramya-rao-a** [comment]
@calidion Are you trying to format .scss file or .sass file? SCSS formatting is provided by extensions. #9071 is tracking an existing issue around formatting scss files.

**Comment by aeschli** [comment]
Closing as SCSS formatting is provided by extensions

**Comment by calidion** [comment]
@aeschli  not found any useful extensions.

**Comment by calidion** [comment]
hope to make it core and enable the right click menu.
thanks.

**Comment by MeirionHughes** [comment]
This really should be added to core; I want to be able to right-click and choose format. Instead I have to rename the file the json and then do it.

**Comment by ramya-rao-a** [comment]
@calidion @MeirionHughes There are extensions that support formatting for scss files
[CSScomb](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-csscomb) or [stylefmt](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-stylefmt) can be used for formatting via the command pallette
You can right click "Format Code" using [style-formatter](https://marketplace.visualstudio.com/items?itemName=dweber019.vscode-style-formatter)

**Comment by MeirionHughes** [comment]
Nice that style-formatter is perfect. Should be added to default installs tbh. :P
