### ISSUE TITLE
Markdown Rendering drops '=' from relative paths

### ISSUE THREAD

**Issue by goessner** [microsoft/vscode#94508]
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. call in extension's `activate` function 
```js
vscode.commands.executeCommand('markdown.api.render', '[page=42](doc/myfile.pdf#page=42)').then(result => {
    console.log(`rendered markdown: ${result}`);
});
```
gives ...
```
<p data-line="0" class="code-line"><a href="doc/myfile.pdf#page42" data-href="doc/myfile.pdf#page42">page=42</a></p>
```
'=' character was dropped !

2. call in extension's `activate` function 
```js
vscode.commands.executeCommand('markdown.api.render', '[page=42](file://///server/path/doc/myfile.pdf#page=42)').then(result => {
    console.log(`rendered markdown: ${result}`);
});
```
gives ...
```
<p data-line="0" class="code-line"><a href="file://///server/path/doc/myfile.pdf#page=42" data-href="file://///server/path/doc/myfile.pdf#page=42">page=42</a></p>
```
'=' character was **not** dropped !

Does this issue occur when all extensions are disabled?:  Hmm ... extension is needed in this case.

**Comment by goessner** [comment]
#https://github.com/goessner/mdmath/issues/86

**Comment by iliazeus** [comment]
As far as I understand, all links in a markdown file are processed with a "normalizer". As part of the normalization, all uri fragments are "slugified":

https://github.com/microsoft/vscode/blob/f24a7ba4c732565316d5b3b07ef62242a5ec9f81/extensions/markdown-language-features/src/markdownEngine.ts#L254-L258

With a default "slugifier", it means, among other things, removing all punctuation:

https://github.com/microsoft/vscode/blob/f24a7ba4c732565316d5b3b07ef62242a5ec9f81/extensions/markdown-language-features/src/slugify.ts#L20-L32

@mjbvz, am I correct in thinking that the "slugification" is needed for links to headings in the current document to work (`[link](#my heading)`)? If so, a possible fix is to slugify only those uris that do not have authority and path parts.

**Comment by mjbvz** [comment]
Yes I don't think the slugifier should be run if the link points to a location that is clearly not a markdown file (such as the path ending in `.pdf`). It is however helpful to normalize links to other markdown files within your current workspace.

@iliazeus As as scoped fix, we could check `extname(uri.path)`. If there is a file extension, don't normalize the fragment. Does that sound good? Would you like to submit a PR that does this?

**Comment by iliazeus** [comment]
As far as I understand, that may break links to sections of other markdown files that do have an extension (`file.md#Section header`), but I don't see a good fix for that, other than hard-coding all possible markdown file extensions.

**Comment by iliazeus** [comment]
Would it be a valid feature request to have an API to guess language id based only on a resource uri?
