### ISSUE TITLE
vs/workbench/issueService depends on vs/code

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94505]
We typically do not allow to depend on `vs/code` from `vs/workbench` as none of the former should be bundled into the latter. Move it into `vs/platform` if you must depend on it

https://github.com/microsoft/vscode/blob/33dcd3028fc4d6f1a7fe1e6f8c1cc69337eff87b/src/vs/workbench/contrib/issue/browser/issueService.ts#L7

@jrieken I am actually surprised this does not trigger a import violation warning. Did we loose this support with the migration to ESLint?

**Comment by jrieken** [comment]
> Did we loose this support with the migration to ESLint?

No, but this usually is a config problem

**Comment by bpasero** [comment]
@jrieken any clues how to bring this back? I mean, in the `.eslint` rules file the `vs/code` layer is not allowed anywhere for `vs/workbench`.

**Comment by jrieken** [comment]
There is no bringing back, the rule-config are copies.
