### ISSUE TITLE
Moving view over panel as sidebar leaves wrong drop feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94502]
see:

![Kapture 2020-04-06 at 8 26 08](https://user-images.githubusercontent.com/900690/78528718-56270980-77e0-11ea-9a0c-1f06b46805bc.gif)

//cc @sandy081

**Comment by sandy081** [comment]
Good catch

**Comment by sbatten** [comment]
To Verify:
1. Move Panel to Right/Left
2. Try dropping a view into the panel.
3. Verify feedback is horizontally split instead of vertically.
