### ISSUE TITLE
Move serviceMachineIdResource into node layer

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94504]
Please do not pollute the common environment with node specific things unless we need/can support it for web as well.

https://github.com/microsoft/vscode/blob/33dcd3028fc4d6f1a7fe1e6f8c1cc69337eff87b/src/vs/platform/environment/common/environment.ts#L68

Move it into `INativeEnvironmentService` instead.

**Comment by sandy081** [comment]
/dupicate

This cannot be moved to node as there are other common (web/native) services depend on it. This is a known debt issue - https://github.com/microsoft/vscode/issues/83215
