### ISSUE TITLE
Select box background color broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#94507]
The select box in the panel header should have a white background:

![image](https://user-images.githubusercontent.com/22350/78535695-e408f180-77ec-11ea-894a-166381284ab5.png)

This is similar to the recent breakage with the simple editor widget background color in SCM and extensions views.

**Comment by sbatten** [comment]
To Verify:
1. Set `dropdown.background` to an obvious color.
2. Check that terminal and output select boxes are using these when they are in their default locations in panel.
