### ISSUE TITLE
[folding] folding indicators disappear

### ISSUE THREAD

**Issue by LaetitiaSaillard** [microsoft/vscode#94511]
Hello,
I lost my folding. I can't see the folding buttons and all my folded code is lost. Funny enough is the search still works but I can't see any code.
To reproduce : use the auto strategy on folding.
If I use the indentation strategy it works.
(on a HTML document)

**Comment by aeschli** [comment]
Can you add a screenshot?

**Comment by LaetitiaSaillard** [comment]
yes, here is with the indentation strategy
![image](https://user-images.githubusercontent.com/48448256/78562540-d7e75900-7819-11ea-9a14-749197afba31.png)
![image](https://user-images.githubusercontent.com/48448256/78562591-efbedd00-7819-11ea-8e86-bda9166464e6.png)

And here is with the auto strategy
![image](https://user-images.githubusercontent.com/48448256/78562620-fb120880-7819-11ea-871d-9633db34cae1.png)
![image](https://user-images.githubusercontent.com/48448256/78562691-0d8c4200-781a-11ea-917a-82bfb23a7701.png)

I have lost everything that is folded under the div "optTableaux"

**Comment by aeschli** [comment]
Can you put this in the settings: `"html.trace.server": "verbose"`
Open the output view, HTML Language Server` , look if there's a message for `foldingRange`

**Comment by LaetitiaSaillard** [comment]
OK, I got this :
[Trace - 15:37:19] Sending request 'textDocument/foldingRange - (494)'.
Params: {
    "textDocument": {
        "uri": "file:///..../index.html"
    }
}

**Comment by aeschli** [comment]
No response for 'textDocument/foldingRange` ? (`Received response 'textDocument/foldingRange`)

**Comment by aeschli** [comment]
Do you have steps to reproduce how you get in the situation?
Does it always show with the file? Any chance you can share the file?

**Comment by LaetitiaSaillard** [comment]
Hello,
Well I tried to reproduce the bug and couldn't, now it works.
I swear I'm not crazy !! Lol
I think we can thank Murphy and close this ticket.
