### ISSUE TITLE
Code folding breaks if JSON is unaligned

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9451]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:

Input:
![image](https://cloud.githubusercontent.com/assets/1723815/16925675/56629e76-4cf3-11e6-9da3-3dc19180bd4c.png)

Fold `test`

Output:
![image](https://cloud.githubusercontent.com/assets/1723815/16925683/60d26972-4cf3-11e6-9dc6-98f64cf66895.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/1723815/16925694/6b3e720c-4cf3-11e6-92e6-449fbfbdcb02.png)

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, know about JSON objects, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
