### ISSUE TITLE
terminal shell path

### ISSUE THREAD

**Issue by Asadnoor951** [microsoft/vscode#94528]
Issue Type: <b>Feature Request</b>

The terminal shell path "C:\Program Files\Git\bin\bash.exe" does not exist. 
I can't intigerate bash with terminal.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
This means the path doesn't exist, change your `terminal.integrated.shell.windows` setting. Did you configure it manually?
