### ISSUE TITLE
Opening a browser window from an extension

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#9452]
I am looking to open a browser window from an extension but it doesn't look like `shell.openExternal` is exposed in the extensions framework.  `shell` is from the `electron` package. Is there another way to open a browser window from an extension or does some work need to be done to expose shell.openExternal`?

**Comment by jsloyer** [comment]
Closing....  Documenting the solution below.

```
let open = require('open');
open('https://code.visualstudio.com/');
```

**Comment by cg-cnu** [comment]
No need to required a node module for this...
`vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://google.com'))`
