### ISSUE TITLE
Only prompt for restart/other models on the active window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94522]
General case of https://github.com/microsoft/vscode/issues/94176

This happened after a sync which changes title bar style (https://github.com/microsoft/vscode/issues/94520):

<img width="487" alt="Screen Shot 2020-04-06 at 4 30 48 AM" src="https://user-images.githubusercontent.com/2193314/78554276-b9547400-77bf-11ea-9f36-89103312e14b.png">

**Comment by sandy081** [comment]
@Tyriar Not sure what's your complain here? Are you saying we shall not show this dialog in all open windows when a settings that requires restarting is changed?

**Comment by Tyriar** [comment]
The same ask as https://github.com/microsoft/vscode/issues/94176, don't spam every window with a dialog when it can be actioned a single time on the foreground window. Often I cancel this one which means I need to cancel it for every window I have opened.
