### ISSUE TITLE
--disable-extension shows notification with non-working command

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#94532]
From source

- run `./scripts/code-cli.sh --disable-extensions .`
- a notification `All installed extensions are temporarily disabled. Reload the window to return to the previous state.` notification shows. Press reload.
- windows reloads, again without extensions and with the notification

I think the notification is useful, but should not not offer the reload.

**Comment by ericsnowcurrently** [comment]
@bpasero

related: #81653

**Comment by NotWearingPants** [comment]
For me, it doesn't matter whether you use the reload button in the notification or use the Reload Window command, both don't work as intended.
