### ISSUE TITLE
Support Need to create an app on the same UI model which VSCode uses

### ISSUE THREAD

**Issue by mubbasher** [Microsoft/vscode#9453]
Hi,

We have an app which was using V8 and now we started to switch to ChakraCore, so delighted... Our previous app was on Windows only and was using C#.

Now, we want to it to be portable on Mac and Linux. Since, we can see the VS code works on all platforms, can you please give us a hint how to use same application development model and UI which same crossplatform, which is being used for VSCode.

I appreciate, if some links or guide is provided...

Thanks

**Comment by Krzysztof-Cieslak** [comment]
VSCode uses GitHub's [Electron](http://electron.atom.io/) -  framework for creating native applications with web technologies like JavaScript, HTML, and CSS (or TypeScript as in case of VSCode). Electron is cross-platform, supports Mac, Linux and Windows. It's based on [Node.js](https://nodejs.org/en/)
