### ISSUE TITLE
Support custom TaskGroup

### ISSUE THREAD

**Issue by idoprz** [microsoft/vscode#94548]
I plan to create an extension that will show my tasks ordered by group. I also have many custom task providers, and I would like to create a custom TaskGroup for them.
Right now the API describes a constructor for [TaskGroup API](https://code.visualstudio.com/api/references/vscode-api#TaskGroup), but it is private, and I can't register it. 
I found this old [issue ](https://github.com/microsoft/vscode/issues/27575) but it doesn't seems to be up to date.

**Comment by alexr00** [comment]
@idoprz In the 1.44 release tasks are now grouped a little differently.

**Comment by idoprz** [comment]
> @idoprz In the 1.44 release tasks are now grouped a little differently.

Hi @alexr00,

As I understand tasks in quick-pick are now grouped by extension. My suggestion was to have some "logical" grouping like the "build", but with costume types, like "linters", "deploy", etc'..

**Comment by carlos-algms** [comment]
Any update on this?
