### ISSUE TITLE
Find by regular expression with backreference - not working

### ISSUE THREAD

**Issue by Kcko** [microsoft/vscode#94543]
Hi, i have two files with these strings

```getTemplate('aa')``` and ```getTemplate("aa")```

and backreference not works. Im trying $1, $0 , {$1}, \\1 etc...
```getTemplate\(('|")aa$1\)```

Can you tell me how is correct syntax in VSC? Is it supported?

![](https://bit.ly/2xajTim)

**Comment by IllusionMH** [comment]
You need to use `\1` instead of `\\1`

**Comment by Kcko** [comment]
@IllusionMH Excellent! Thx.

**Comment by IllusionMH** [comment]
Does it resolve problem?

Please close this issue if it's resolved.

**Comment by Kcko** [comment]
@IllusionMH yes! Where can i find more info about these advanced things?
I will close immeadiatelly (tomorrow)

**Comment by IllusionMH** [comment]
Find widget uses JS RegExp engine to perform search in single file.

Global search uses ripgrep under the hood.

**Comment by Kcko** [comment]
OK, thx!
