### ISSUE TITLE
autoReveal false isn't working

### ISSUE THREAD

**Issue by Siregar** [microsoft/vscode#94546]
Issue Type: <b>Bug</b>

Hi,
"explorer.autoReveal": false isn't working. If I hide the explorer and switch from one open tab to another open tab, it's always showing up. This happened after restarting my macbook. I guess VS code updated.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Siregar** [comment]
I hope this give help.
When switching between files (by shortcut or click) the hidden explorer shows up.

![bug](https://user-images.githubusercontent.com/31287148/78634332-0578e480-78a4-11ea-8e0c-77342ba0f894.gif)

**Comment by isidorn** [comment]
I think you have some extension which screws this up.
Please try with vscode insiders and with no extensions. Thank you
