### ISSUE TITLE
When extensions are enabled source control sticks to tree view

### ISSUE THREAD

**Issue by logxseven** [microsoft/vscode#94551]
- VSCode Version: 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50) x64
- OS Version: Linux mint 19.2

Steps to Reproduce:

Source view has changed to tree on its own and setting it to list does nothing.

![image](https://user-images.githubusercontent.com/9774613/78576949-467de400-7825-11ea-9ca8-80f4a9be6df7.png)

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
Do you have this toggle button?
![image](https://user-images.githubusercontent.com/6726799/78577813-8c877780-7826-11ea-965c-6c9bbb00f55a.png)

**Comment by logxseven** [comment]
@gjsjohnmurray  OMG it worked !
