### ISSUE TITLE
Convert default sendSequence actions to commands

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94557]
See commit in https://github.com/microsoft/vscode/issues/92021

**Comment by Tyriar** [comment]
To to make sure the follow keybindings all work on both mac and non-mac, note that the commands no longer exist by design:

Terminal: Delete Word Left

```
primary: KeyMod.CtrlCmd | KeyCode.Backspace,	
mac: { primary: KeyMod.Alt | KeyCode.Backspace }	
```

'Terminal: Delete Word Right'

```
primary: KeyMod.CtrlCmd | KeyCode.Delete,	
mac: { primary: KeyMod.Alt | KeyCode.Delete }	
```

Terminal: Delete To Line Start

```
primary: 0,	
mac: { primary: KeyMod.CtrlCmd | KeyCode.Backspace }
```

Terminal: Move To Line Start

```
primary: 0,	
mac: { primary: KeyMod.CtrlCmd | KeyCode.LeftArrow }	
```

Terminal: Move To Line End

```
primary: 0,	
mac: { primary: KeyMod.CtrlCmd | KeyCode.RightArrow }	
```

**Comment by roblourens** [comment]
ctrl+backspace still doesn't work for me on windows, it inserts `^W` I assume that's expected?

**Comment by Tyriar** [comment]
Yeah that's expected, depending your shell. For PS you need v7
