### ISSUE TITLE
debug.console.wordWrap on ubuntu version

### ISSUE THREAD

**Issue by DarkDeveloper-Plant** [microsoft/vscode#94560]
Hi
I tried `debug.console.wordWrap` to set `false` and restarted but it doesn't work on Linux version.
Version: 1.42.1
![Screenshot from 2020-04-06 23-03-14](https://user-images.githubusercontent.com/47008296/78594012-ca06f780-785c-11ea-879c-18704e3eee0c.png)

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
