### ISSUE TITLE
Sidebar overflow context menu does not appear when at bottom of the screen with multiple monitors

### ISSUE THREAD

**Issue by forivall** [microsoft/vscode#94561]
- VSCode Version: Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

(also reproduces on insiders)
- OS Version: macOS Mojave (10.14.6 (18G4032))

Steps to Reproduce:

1. Set up multiple monitors with a vertical layout
<img width="250" alt="Screen Shot 2020-04-06 at 10 58 44 AM" src="https://user-images.githubusercontent.com/760204/78593877-31408f80-77fc-11ea-9a03-0b578035c778.png">

2. Shrink the window small enough to get overflow for the sidebar items
3. Move the overflow button so that it is on the top monitor, right up against the seam between monitors.
4. Click the overflow button. The context menu does not appear

![Kapture 2020-04-06 at 11 08 33](https://user-images.githubusercontent.com/760204/78594137-98f6da80-77fc-11ea-9d4b-956da7cf8a0e.gif)

Expected Behaviour: (which is when the position of the overflow button is on the right hand side of the screen, where the bottom screen does not overlap)
<img width="151" alt="Screen Shot 2020-04-06 at 10 58 44 AM copy" src="https://user-images.githubusercontent.com/760204/78594353-00148f00-77fd-11ea-96e0-4d1c26305e1b.png">

![Kapture 2020-04-06 at 11 09 59](https://user-images.githubusercontent.com/760204/78594159-a44a0600-77fc-11ea-88a2-f8e393c46f65.gif)

Does this issue occur when all extensions are disabled?: Yes (checked with a freshly installed insiders build)

**Comment by deepak1556** [comment]
Can you check if this is still an issue with our [insiders](https://code.visualstudio.com/insiders) and [exploration versions](https://az764295.vo.msecnd.net/exploration/3c1b4bacbef4ab788f72059f56ef53e9aa7923bc/VSCode-darwin.zip) which come with newer runtime. Thanks!

**Comment by forivall** [comment]
I'm still able to trigger with insiders
```
Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:39:23.276Z (21 hrs ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

and the exploration version at the link you posted.

```
Version: 1.52.0-exploration
Commit: 3c1b4bacbef4ab788f72059f56ef53e9aa7923bc
Date: 2020-11-04T06:53:16.102Z (2 days ago)
Electron: 11.0.0-beta.17
Chrome: 87.0.4280.27
Node.js: 12.18.3
V8: 8.7.220.8-electron.0
OS: Darwin x64 18.7.0
```

**Comment by forivall** [comment]
I can no longer replicate on
```
Version: 1.82.0-insider
Commit: f125afbc800ec611f5a9ab1333c769832ce424b3
Date: 2023-08-21T05:34:23.256Z (14 hrs ago)
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0
CPUs: Apple M1 Pro (10 x 24)
```

So, an electron update has likely fixed this
