### ISSUE TITLE
Can no longer define search location in settings file

### ISSUE THREAD

**Issue by simonvanderveldt** [microsoft/vscode#94568]
The changes as described in https://github.com/microsoft/vscode/issues/89384 seem to indicate that it was a deliberate choice to make it no longer possible to configure the search panel location in the settings file. This is/was rather useful functionality that I'd very much like to have back.

Can configuring where the search panel opens be added back to the settings file?

**Comment by sbatten** [comment]
Is there a reason to have it in the settings file over local user data? Once it is moved with drag and drop we store and remember this.

**Comment by sbatten** [comment]
[Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) is currently in preview in Insiders and will soon be available in our Stable build. This syncing does include the view placement. Would this address your use case?

**Comment by simonvanderveldt** [comment]
Thanks for the info. Just looked at the docs, I don't think it addresses my use case.
I already have a working mechanism to configure all my applications (dotfiles in a repo) which I would like to continue to use, it has and continues to serve me well. Compared to a sync service I can choose what to sync, choose when to sync, describe why I made changes and revert (individual) changes if the need arises.
Apart from that I have no desire to have to login to an account to use an editor/get my settings synced.
