### ISSUE TITLE
View Header not shown in some cases when there are lots of view

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#94569]
Issue Type: <b>Bug</b>

**Repro**
1. With a window that is ~600px high
1. Have GitLens installed
1. In the VS Code codebase, trigger `GitLens: Git Commnds`
1. Select search and perform a search for a generic term such as `a`

**Bug**
This opened the GitLens view. The header (`GitLens`) is sometimes not shown. Here's stable on the left and insiders on the right

<img width="782" alt="Screen Shot 2020-04-06 at 1 23 56 PM" src="https://user-images.githubusercontent.com/12821956/78602255-fdb93180-780a-11ea-84fe-2e64a32932b0.png">

VS Code version: Code - Insiders 1.44.0-insider (e8dbc5ea6092ba73ae70069d3e730f2cc56addff, 2020-04-03T22:09:44.908Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|-psn_0_135201|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by sbatten** [comment]
Could this be caused by the changes you made around welcome view scrolling? @joaomoreno

**Comment by joaomoreno** [comment]
No, I don't think it is. This is the lack of overflowing behavior in splitviews combined with the browser automatically revealing the focused element. I've tried to fix this in many ways and I have failed repeatedly (eg periodically set `scrollTop` to zero). I'd close it as a duplicate of https://github.com/microsoft/vscode/issues/64188.

**Comment by sbatten** [comment]
@joaomoreno I do wonder why it doesn't repro in the previous stable (something @mjbvz tested I believe)
