### ISSUE TITLE
Breadcrumbs in peek widget

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#94563]
![image](https://user-images.githubusercontent.com/8586769/78595752-6a2e3380-77ff-11ea-8b36-34188867b20f.png)

Due to it's small vertical height, it can be especially hard to know where in a file a peek widget's result is. Having breadcrumbs (specifically the in-file ones) for the peek widget would help with this.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abreadcrumbs+label%3Afeature-request
