### ISSUE TITLE
Floating editor window

### ISSUE THREAD

**Issue by boyuanfang** [microsoft/vscode#94570]
Individual floating editor window that can be pinned on top.
Like what Visual Studio can do and most other IDEs.
This feature will be very useful for peeking code that does not need to be on a splitted editor and for multiple monitors.

![l5oAbZL](https://user-images.githubusercontent.com/32655525/78602770-dadb4d00-780b-11ea-9667-16e3380c84b2.png)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/10121
