### ISSUE TITLE
comma added to last item of object on save

### ISSUE THREAD

**Issue by jacky-ew** [microsoft/vscode#94579]
- VSCode Version: 1.43.2
- OS Version: macox

Steps to Reproduce:

1. open old files
2. on save, the ide adds commas on each last item on the file eg: { backgroundColor: "black", fontSize: 12, } <-- the last comma should not be there

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@jacky-ew What kind of files does this happen for? What's the value of your `editor.formatOnSave` setting?

**Comment by jacky-ew** [comment]
js files, im working on react-native.
`    "[javascript]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },`

**Comment by chnejohnson** [comment]
I have same problem completely today. I'm working on vue-cli.

**Comment by nrayburn-tech** [comment]
Check your prettier config.  There is a `trailingComma` setting that adds the trailing commas.
https://prettier.io/docs/en/options.html#trailing-commas

**Comment by chnejohnson** [comment]
@nrayburn-tech Thanks, it works.
It's prettier's auto upgrade to v2.0.0.
For me, There is another migration about arrow function parentheses.
https://prettier.io/docs/en/options.html#arrow-function-parentheses

Therefore, I add these two line in my vscode settings.json for turning back old version prettier settings.
```
 "prettier.trailingComma": "none",
 "prettier.arrowParens": "avoid"
```
