### ISSUE TITLE
'cmd' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Mce27** [microsoft/vscode#94575]
Issue Type: <b>Bug</b>

I had a print command in python 3.8.2 and got this:
C:\Users\matth\OneDrive\Documents\python> cmd /C "set "DEBUGPY_LAUNCHER_PORT=50929" && C:\Users\matth\AppData\Local\Programs\Python\Python38-32\python.exe c:\Users\matth\.vscode\extensions\ms-python.python-2020.3.71659\pythonFiles\lib\python\debugpy\no_wheels\debugpy\launcher c:\Users\matth\OneDrive\Documents\python\helloworld.py "
'cmd' is not recognized as an internal or external command,
operable program or batch file.

to clarify i have not messed around in the settings

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (7.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.71659

</details>

**Comment by RMacfarlane** [comment]
Hi @Mce27, can you check that system32 is included in your path? Start menu > search for "Environment variables" and select "Edit the system environment variables" > select "Path" > edit

C:\WINDOWS\system32 should be listed within the table

**Comment by Mce27** [comment]
That did it thanks. It was set somewhere else
