### ISSUE TITLE
emacs-like 'ctrl-u' keyboard command has no effect in editor

### ISSUE THREAD

**Issue by chadlavi** [microsoft/vscode#94576]
- VSCodium Version: 1.43.2
- Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
- Date: 2020-03-24T21:29:13.969Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.4.0

Steps to Reproduce:

1. confirm that common emacs-like keyboard commands work as normal:
    a. open any file in vscode and move the cursor to the middle of a line of text
    b. hit `ctrl-k`; you'll find that the text between your cursor and the end of the line is deleted
    d. hit `ctrl-a`; you'll find that your cursor moves to the beginning of the line
    e. hit `ctrl-e`; you'll find that your cursor moves to the end of the line
2. confirm that the `ctrl-u` keyboard command does _not_ work as normal:
    a. place your cursor in the middle of a line of text
    b. hit `ctrl-u`
    1. **EXPECTED**: all text between the start of the line and the cursor is deleted
    2. **ACTUAL**: nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
VSCode ships with some emacs-like keybindings, but not all of them.

There are keybinding extensions that others have written to emulate other editors. I just tried the most popular emacs one and it seemed to also not have anything bound for `ctrl-u`, so if that there isn't an extension that does this, you can also manually edit your keybindings with "Preferences: Open Keyboard Shortcuts" and changing the binding for "Delete All Left"

**Comment by chadlavi** [comment]
@RMacfarlane thanks for the explanation, but this is one of the most common emacs keybindings -- and for mac users, one that works on almost all text inputs. Why isn't the full set of keybindings possible to use?

**Comment by RMacfarlane** [comment]
@chadlavi I'm not sure of the exact history of this keybinding in VSCode, but the current default for this behavior, cmd backspace, also works for inputs on mac and is used by other editors. We try to choose keybindings that are used by convention and would be familiar to a wide audience.

For full emacs keybindings, please try installing a keymap extension: https://code.visualstudio.com/docs/getstarted/keybindings#_keymap-extensions
