### ISSUE TITLE
Centered Layout: use full width when displaying diff editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94574]
Issue Type: <b>Feature Request</b>

* Toggle Centered Layout
* When there is two editor groups, the centered layout is turned off
* When there is only one editor group, the centered layout is activated automatically
* When a diff editor is opened, it's still in centered layout however the width for editor group is too small for two editors side by side, even though they are in the same editor group.

VS Code version: Code - Insiders 1.44.0-insider (e8dbc5ea6092ba73ae70069d3e730f2cc56addff, 2020-04-03T22:09:44.908Z)
OS version: Darwin x64 19.2.0

**Comment by isidorn** [comment]
This is a fair feature request and something which we want to tackle.
When we automatically adjust the centered layout we could check the type of the active editor.

I am opening this for feature requests for now. Code pointer
https://github.com/microsoft/vscode/blob/9307e0546dc5bd16daedce355769f3767b2d9c59/src/vs/workbench/browser/layout.ts#L959

**Comment by rebornix** [comment]
It's pretty useful to myself so here is the PR https://github.com/microsoft/vscode/pull/94696

**Comment by isidorn** [comment]
@rebornix thanks for doing this 👏 

To verify:
1. Turn on centered mode (or zen mode)
2. Open a file in one group. Make sure that file is centered
3. Open a diff view -> make sure the full width is used so centering no longer active
4. Open a regular file again -> make sure it is centered
