### ISSUE TITLE
The C source code file named p5.c will be automatically recognized as a C ++ file

### ISSUE THREAD

**Issue by YongLeiLi717** [microsoft/vscode#94589]
Issue Type: <b>Bug</b>

新建文件，命名为p5.c，显示C++图标，编译时使用g++

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
doxdocgen|csc|0.6.0
code-runner|for|0.9.17
vscode-language-pack-zh-hans|MS-|1.44.0
cpptools|ms-|0.27.0
vscode-icons|vsc|10.0.0
material-theme|zhu|3.2.5

</details>

**Comment by YongLeiLi717** [comment]
![image](https://user-images.githubusercontent.com/32541545/78645848-b86c3100-78ea-11ea-9437-fc480ca991fe.png)

**Comment by RMacfarlane** [comment]
I'm not able to reproduce this problem. What are the file contents of p4 and p5?

**Comment by YongLeiLi717** [comment]
&nbsp;There is nothing in the file. In the new. C file, named p5.c is recognized as a c++ file.I don't konw what happened



---Original---

**Comment by RMacfarlane** [comment]
Do you remember if this happened immediately after you created it, or after doing something else like compiling? If you add another .C file is it recognized correctly? Can you try pressing "F1" and then running "Developer: Reload with Extensions Disabled"?

**Comment by YongLeiLi717** [comment]
I recorded a GIF file and reproduced the problem. The GIF file is in the attachment. I disabled all plug-ins, and the problem still exists.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rachel Macfarlane"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 上午10:53
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"Sentir曐曟"<841261550@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] The C source code file named p5.c will be automatically recognized as a C ++ file (#94589)





 
Do you remember if this happened immediately after you created it, or after doing something else like compiling? If you add another .C file is it recognized correctly? Can you try pressing "F1" and then running "Developer: Reload with Extensions Disabled"?

**Comment by aeschli** [comment]
What file icon theme is that?

Please attach your gif again through the GitHub web UI....

**Comment by YongLeiLi717** [comment]
![bug](https://user-images.githubusercontent.com/32541545/78784148-694ffa00-79d7-11ea-9018-4c39208e7b00.gif)
The Gif recorded in this mode "Developer: Reload with Extensions Disabled"

**Comment by YongLeiLi717** [comment]
I have provided GIF in GitHub.The Gif recorded in this mode "Developer: Reload with Extensions Disabled"


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Aeschlimann"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 下午5:05
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"Sentir曐曟"<841261550@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] The C source code file named p5.c will be automatically recognized as a C ++ file (#94589)





 
What file icon theme is that?
 
Please attach your gif again through the GitHub web UI....

**Comment by aeschli** [comment]
- do you have have any customfile associations in your user or workspace settings?
```
	"files.associations": {
		"*.c": "csharp"
	}
```
- can you open the developer tool (Help > Toggle Developer Tools) and inspect the icon's css rules?

![image](https://user-images.githubusercontent.com/6461412/78870451-70622100-7a46-11ea-8098-24bfc34e33cd.png)

**Comment by YongLeiLi717** [comment]
thanks,i have find it .
"files.associations":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"P5.C":&nbsp;"cpp",






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Martin Aeschlimann"<notifications@github.com&gt;; 
发送时间: 2020年4月9日(星期四) 下午3:43
收件人: "microsoft/vscode"<vscode@noreply.github.com&gt;; 
抄送: "Sentir曐曟"<841261550@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [microsoft/vscode] The C source code file named p5.c will be automatically recognized as a C ++ file (#94589)





  
do you have have any customfile associations in your user or workspace settings?
  	"files.associations": { 		"*.c": "csharp" 	}   
can you open the developer tool (Help &gt; Toggle Developer Tools) and inspect the icon's css rules?
