### ISSUE TITLE
Improve Go To References to remove chaff results

### ISSUE THREAD

**Issue by joeytwiddle** [microsoft/vscode#94585]
When I use `Go To References` I am usually looking for calls to a function, or uses of a variable.

The following results are not useful to me:

- The implementation (Usually that's where I started from! And if I really wanted this, then I would have selected `Go To Implementations`)
- The lines where the reference was imported

These results simply get in the way, slowing down my navigation.

In the case where there is only one call to a function, I get three results instead of one result (which could have been a direct jump without the preview popup, saving me a lot of time).

What I am looking for is the same behaviour as WebStorm, which helps me to quickly navigate to useful parts of the code.

However I can believe that some people might like to keep the existing behaviour. Therefore...

### Proposal 1

- Implement `Go To Useful References` which performs the suggested behaviour (removes imports and implementations from the results)

### Proposal 2

- Rename the current `Go To References` to `Go To All References`
- Implement the suggested behaviour as `Go To References`

I actually prefer the second proposal, and I think many others users might like it too, but it would be a change to the existing behaviour.

**Comment by jrieken** [comment]
> When I use Go To References I am usually looking for calls to a function, or uses of a variable.

There is "Call Hierarchy" for that. The rest is this: https://github.com/microsoft/vscode/issues/74237
