### ISSUE TITLE
TypeScript language region/endregion autocomplete superfluous slashes

### ISSUE THREAD

**Issue by reviewher** [microsoft/vscode#94580]
- VSCode Version: 1.43
- OS Version: OSX 10.5.3

Steps to Reproduce:

1. New file and set language to "TypeScript"
2. Type `//#` and select "#region"

Expected result `//#region`, VSC actually makes it `////#region`

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/92051
