### ISSUE TITLE
Debug hover jumping around

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#94581]
Repro 1

Debug this code

```js







function foo(a, b) {
	console.log(a);
}

foo(1, [{ b: [5]}])
```

- Breakpoint on the console.log
- Hover `a`, then move the cursor to `b`, without letting the hover go away
- The hover for `b` shows up in the wrong spot before it gets layed out to the right spot

![Apr-06-2020 20-58-47](https://user-images.githubusercontent.com/323878/78622126-ef3e3a80-7849-11ea-817f-4777e76edbf4.gif)

Repro 2 - including this because it looks much worse and it didn't look this bad in simpler examples

- Set a breakpoint in notebookTextModel.ts, in `$spliceNotebookCellOutputs`
- Open a notebook and execute a cell that has an output
- Hover cellHandle and splices

![Apr-06-2020 21-00-00](https://user-images.githubusercontent.com/323878/78622312-6ffd3680-784a-11ea-9ef6-5f18f98386de.gif)

**Comment by isidorn** [comment]
@roblourens thanks for filling the issue with such good steps. I have pushed a fix.
Now it works fine for me. Try it out and let me know how it works for you now.

**Comment by roblourens** [comment]
Seems fine in master, thanks!

**Comment by isidorn** [comment]
Great, adding verified label.
