### ISSUE TITLE
Search converts \r\n into linebreak when file is opened in Explorer panel

### ISSUE THREAD

**Issue by eggpa** [microsoft/vscode#94596]
Issue Type: <b>Bug</b>

Reproduction steps:
1. create folder "testsearch"
2. inside the folder create file "foo1.txt"
3. modify file to have content "foo\r\n" (first line contains text "foo" with CRLF line break and second line is empty)
4. open "testsearch" folder in VS Code
5. open Search panel and enable Regex
7. search for "foo\r\n"
8. it should display single result
9. switch to Explorer view and open "foo1.txt"
10. while file is open switch back to search
11. "foo\r\n" becomes "foo\<linebreak\>"

Before opening file:
![image](https://user-images.githubusercontent.com/40495747/78661481-87cecc00-78d7-11ea-9b48-faaa174b3470.png)

After opening file:
![image](https://user-images.githubusercontent.com/40495747/78661493-8b625300-78d7-11ea-8b2a-5fa9f16f8dad.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (20.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-yarn|gam|1.7.0
csharp|ms-|1.21.16
mssql|ms-|1.9.0

</details>

**Comment by roblourens** [comment]
I think this is because the match is highlighted in the editor, and when you switch back to the search viewlet, it copies the selected text into the search viewlet. Does that sound right?

There is actually a lot of discussion on how this should work in this issue, https://github.com/microsoft/vscode/issues/91901, and I will probably be making some changes soon, feel free to weigh in.
