### ISSUE TITLE
Reopened tabs should open in the same position as closed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9459]
- VSCode Version: Code - Insiders 1.4.0-insider (9c4890399293ee5c87c4f7bfb5405d120ea650c6, 2016-07-18T05:00:48.266Z)
- OS Version: Linux x64 4.4.0-31-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open several tabs, note the position of the active tab
2. Close the active tab
3. Reopen the tab using ctrl/cmd+shift+t, notice the tab is in a different position

**Comment by bpasero** [comment]
It does not work because it is not implemented (yet) :)

**Comment by bpasero** [comment]
Not straight forward, but happy for a PR. The code that manages recently closed editors is in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L213 and the suspect is `recentlyClosed`
