### ISSUE TITLE
Custom title: prevent new lines

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94594]
Steps to Reproduce:

1. bring a `\n` into the `window.title`
2. => 🐛 with custom title

![image](https://user-images.githubusercontent.com/900690/78656156-48987f00-78c7-11ea-9a33-9d43141a3099.png)

**Comment by sbatten** [comment]
To Verify:
1. Edit `settings.json` directly and use `\n\t\r` characters in `window.title` setting.
2. Verify these are replace with a space.

**Comment by bpasero** [comment]
Thanks!
