### ISSUE TITLE
Search incorrectly interprets CRLF line endings in opened files

### ISSUE THREAD

**Issue by eggpa** [microsoft/vscode#94595]
Issue Type: <b>Bug</b>

Summary: CRLF line endings in opened files are treated as LF line endings

Reproduction steps:
1. create folder "testsearch"
2. inside the folder create two files "foo1.txt" and "foo2.txt"
3. modify both files to have identical content "foo\r\n" (first line contains text "foo" with CRLF line break and second line is empty)
4. open "testsearch" folder in VS Code
5. press Ctrl + Shift + F to enable search panel
6. press Alt + R to enable regex search
7. search for "foo\r\n"
8. it should display two results, one in each file
9. click one of results to open the file
10. while file is open switch back to search and click refresh
11. opened file disappears from the result list

Additional note: searching for "foo\n" displays both results even though it should be 0 matches.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (20.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-yarn|gam|1.7.0
csharp|ms-|1.21.16
mssql|ms-|1.9.0

</details>

**Comment by roblourens** [comment]
Yeah, so the editor normalizes newlines to `\n`, but that only applies when a file is open. That means that you can't actually search for `\r` in an open editor, but we find that most people actually expect `\n` to match any sort of newline. When we search the disk, we try to make `\n` match `\r\n` but don't normalize away `\r`. That leads to this unfortunate inconsistency but I don't feel that it can be improved right now.
