### ISSUE TITLE
jsdoc comment @template {type} gets greyed out

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94608]
1.43.2
![Code_2020-04-07_15-50-36](https://user-images.githubusercontent.com/30108880/78677059-90c79980-78e7-11ea-9128-bff817caf693.png)

```js
/** @template X */
/** @template {string} Y */
```

**Comment by mjbvz** [comment]
Is `@template {string} Y` a valid JSdoc tag?

**Comment by mjbvz** [comment]
Actually found it here: https://github.com/google/closure-compiler/wiki/Generic-Types#declaring-a-bounded-generic-type

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/820 to track upstream
