### ISSUE TITLE
Possible duplicated Interface OpenIssueReporterArgs

### ISSUE THREAD

**Issue by videlalvaro** [microsoft/vscode#94606]
The interface `OpenIssueReporterArgs ` seems to be declared almost the same in two different places:

https://github.com/microsoft/vscode/blob/0b3aa0a6ea58a7cda4dfccd3322490b5241ef059/src/vs/workbench/contrib/issue/common/commands.ts#L8

and

https://github.com/microsoft/vscode/blob/0b3aa0a6ea58a7cda4dfccd3322490b5241ef059/src/vs/workbench/api/common/apiCommands.ts#L177

The only difference being that in the first one `extensionId?` is also optional.

Is this meant to be like this? Should I send a PR unifying this code?

**Comment by RMacfarlane** [comment]
This is intentional, one of these is for use from the extension API and one is for internal use. An extension calling the command must pass an `extensionId`, so it is required there. Internally, the issue reporter can be opened without this argument

**Comment by videlalvaro** [comment]
Thanks @RMacfarlane 

Are there docs somewhere where I can read more about the internals of VSCode?

**Comment by RMacfarlane** [comment]
There's a bit of information here https://github.com/microsoft/vscode/wiki/Source-Code-Organization

and looking at https://code.visualstudio.com/docs/getstarted/userinterface might be helpful for learning the names of UI pieces, which should be matched in code

**Comment by videlalvaro** [comment]
Thanks again :)
