### ISSUE TITLE
Two step quick open and open to side don't work well together

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94601]
* have editor A
* open file picker and do a file + symbol pick, `strings@isEmpt`
* the editor shows the preview for the new file
* press Cmd+Enter to open the symbol in a new editor column
* 😞 both column show the same, I have lost editor A in column 1

**Comment by bpasero** [comment]
Unhappy, I think we can do better.

**Comment by bpasero** [comment]
I pushed a change that will now simply restore any previous view state whenever the target is the side group, I think that should work OK

![Kapture 2020-04-07 at 16 38 20](https://user-images.githubusercontent.com/900690/78682429-3ed64200-78ee-11ea-9d7f-381517d92ab7.gif)
