### ISSUE TITLE
Output Not Shown When CodeLenses Provided for Active Document

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/vscode#94609]
- VSCode Version: 1.43.2 (user setup)
- OS Version: Windows 10 1809

Steps to Reproduce:

Having a CodeLensProvider registered which returns a non-empty array of codelenses for the current document interrupts displaying output in the output window.

My extension (jamespearson.al-test-runner) displays test results in the output window. If the setting to enable CodeLens is also enabled - and the provider returns some code lenses for the current document - then the output is not shown properly. I have to switch to another pane (e.g. terminal) and back to the output screen to see the results.

Does this issue occur when all extensions are disabled?: Not applicable

**Comment by jrieken** [comment]
Please share a repro sample
