### ISSUE TITLE
Selfhost: Can't use Chrome debugger in remote WSL

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#94607]
This is the VS Code selfhosting scenario I'm currently running at home: I run Windows but keep all code in WSL. I run `yarn` and `yarn watch` in WSL, so all the native modules are compiled for Linux. Which means I also run `./scripts/code.sh` which launches Code in WSL. I have the [VcXsrv](https://sourceforge.net/projects/vcxsrv/) X server running in Windows, which links the bridge and displays running windows of Code OSS. Here's how this looks:

![image](https://user-images.githubusercontent.com/22350/78675620-9cb25c00-78e5-11ea-9635-9fd08b944ff7.png)

Since the Remote WSL extension is awesome and ports are automatically shared between Windows and WSL, basically almost everything works great.  But I can't seem to get our Chrome launch configs to run at all. @weinand suspects this is because the Chrome debug extension runs on the UI side, not the workspace side.

First error I get is:

![image](https://user-images.githubusercontent.com/22350/78676023-2f52fb00-78e6-11ea-9d6a-295152b0ad00.png)

Two problems: it's picking the `.bat` and the remote path is broken. I then tried manually running `./scripts/code.sh --remote-debugging-port=9222` and attaching to it using the Chrome debugger. Despite taking a long time to attach, it eventually succeeds but lacks most functionality: I can't set breakpoints, for example.

Note that the Node debugger works: I can attach to the main and extension host processes, all that works nicely.

@roblourens I wonder if you have any thoughts on this? I would love to simply get our F5 scenario working: the `Debug VS Code Main, Renderer & Extension Host` config.

cc @dbaeumer @aeschli

**Comment by roblourens** [comment]
I'll look into it but it will probably be easier to get it to work with js-debug and the js-debug-companion, have you tried that setup yet? @connor4312

**Comment by roblourens** [comment]
Also with the old Chrome debug extension, you need to install it as a workspace extension, did you do that?

**Comment by connor4312** [comment]
js-debug will try to redirect the launch to the UI side as well. But we could have a property like `forceRunInWorkspace` to disable that redirection behavior.

**Comment by connor4312** [comment]
In today's nightly, you can add this `"browserLaunchLocation": "workspace"` to the launch config to tell js-debug launch the 'browser' workspace-side.

**Comment by joaomoreno** [comment]
> I'll look into it but it will probably be easier to get it to work with js-debug and the js-debug-companion, have you tried that setup yet? @connor4312

I did try, similar results.

> In today's nightly, you can add this `"browserLaunchLocation": "workspace"` to the launch config to tell js-debug launch the 'browser' workspace-side.

Awesome, will give it a try!

**Comment by joaomoreno** [comment]
@connor4312 This did nothing: 

![image](https://user-images.githubusercontent.com/22350/79241345-3e502500-7e73-11ea-8d26-7aa10ca264a9.png)

I've also enabled `debug.chrome.useV3`, is this the right setting to use?

**Comment by connor4312** [comment]
@joaomoreno try using `pwa-chrome` instead as the launch type. It looks like there's an unpublished changed (cc @roblourens) that enables useV3 for Chrome in remote (https://github.com/microsoft/vscode-chrome-debug/commit/8e9209da414aa90cfe9f2945e48d8d335295a230 -- we had that in there before js-debug learned to launch browsers in the UI).

**Comment by joaomoreno** [comment]
With `pwa-chrome` I get this:

![image](https://user-images.githubusercontent.com/22350/79302278-28cb1180-7eec-11ea-9f40-afe30f0c4627.png)

I get it independently of any setting value related to `v3`. I also get it independently of having `"browserLaunchLocation": "workspace"`, which still appears as a warning, even after changing the type to `pwa-chrome`.

**Comment by connor4312** [comment]
Make sure you're using the latest version of js-debug-nightly. That's coming from the companion extension which indicates that it's trying to run in the UI.

Maybe it'd be easier to do a quick Teams call if you run into more issues, feel free to drop some time on my calendar 🙂

**Comment by joaomoreno** [comment]
@connor4312 I'm using whatever's on Insiders. Currently that is `ms-vscode.js-debug-nightly@2020.4.817`.

**Comment by joaomoreno** [comment]
Yup, using the VSIX from the Marketplace and changing type to `pwa-chrome` and `"browserLaunchLocation": "workspace"` did it! Thanks!
