### ISSUE TITLE
Mac Book becomes very hot when using VS Code

### ISSUE THREAD

**Issue by adarshmadrecha** [microsoft/vscode#94600]
Issue Type: <b>Performance Issue</b>

I am running 2 instances of VS Code - Both of them have a NPM Task Running
1. Vue JS Serve
2. Node JS Nodemon

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	    74	 20318	code main
    2	    33	 20319	   gpu-process
    0	    16	 20321	   utility
   13	    66	 20334	   shared-process
    0	     0	 23517	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   205	 20542	   window (TaskStatus.vue — jamkuweb)
    0	    41	 20543	     extensionHost
    0	    57	 20956	       electron_node vueServerMain.js 
    0	     0	 20544	     /bin/zsh -l
    0	    25	 20545	     watcherService
    0	    16	 20644	     npm
   45	   475	 20645	       node /Users/adarsh/Documents/dev/jamkuweb/node_modules/.bin/vue-cli-service serve
    1	   164	 20581	   window (jamkuapi)
    0	     0	 20582	     /bin/zsh -l
    0	    33	 20585	     extensionHost
    0	    25	 20586	     watcherService
    0	    16	 20635	     npm
    0	    25	 20636	       node /Users/adarsh/Documents/dev/jamkuapi/node_modules/.bin/nodemon app
    0	    98	 23503	         /usr/local/bin/node app.js
   52	    57	 23515	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (jamkuapi)
|  Window (TaskStatus.vue — jamkuweb)
|    Folder (jamkuweb): 246 files
|      File types: vue(153) js(15) json(5) eot(5) svg(5) ttf(5) woff(5)
|                  woff2(5) DS_Store(3) png(2)
|      Conf files: package.json(1) settings.json(1) tasks.json(1)
|    Folder (jamkuapi): 196 files
|      File types: js(108) http(33) sql(12) json(6) DS_Store(4) md(3) env(1)
|                  gitignore(1) jshintrc(1) log(1)
|      Conf files: package.json(1) launch.json(1) settings.json(1)
|      Launch Configs: node(2);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
rest-client|hum|0.23.2
dotenv|mik|1.0.1

</details>

**Comment by RMacfarlane** [comment]
@adarshmadrecha Does this happen only when the npm task is running? How did you start the task? If you run the task outside of VSCode, does your mac book also become hot?

**Comment by adarshmadrecha** [comment]
Yes, you are right, it becomes hot only when NPM task is running. I tried running the task outside of vs code, it still became hot. Hence, this is not an issue of VS code. Thanks for point this out.
