### ISSUE TITLE
Golang can't find method definitions and references

### ISSUE THREAD

**Issue by chenyihui555** [microsoft/vscode#94616]
新增.go文件后。其他的go文件无法找到函数方法定义等

**Comment by yume-chan** [comment]
Translation:

> ## Golang can't find method definitions and references
>
> After adding .go files, other go files can't find method definitions etc.

**Comment by RMacfarlane** [comment]
@chenyihui555 Are you using the Go extension? What version of VSCode and what operating system are you using?

**Comment by chenyihui555** [comment]
> @chenyihui555 Are you using the Go extension? What version of VSCode and what operating system are you using?

操作系统是mac, 是最新版本的vscode

**Comment by RMacfarlane** [comment]
Please report this on the Go extension: https://github.com/Microsoft/vscode-go

The Go extension adds support for finding definitions and references
