### ISSUE TITLE
Python interactive variables function show that in some cases will produce a situation that does not meet expectations

### ISSUE THREAD

**Issue by p5ydn0** [microsoft/vscode#94615]
- VSCode Version:1.43.2
- OS Version:10.15.4

Steps to Reproduce:

When run below code:

```python
import numpy as np
import pandas as pd

# data is from kaggle Titanic Competition
data_train = pd.read_csv('data/train.csv')

g = data_train.groupby(['SibSp','Survived'])
df1 = pd.DataFrame(g.count()['PassengerId'])
df2 = pd.DataFrame(g.count()['Pclass'])
print(df)
```
**the python interactive variables** function can't achieve(display) the expected groupby effect.

the expected effect is like this(below is in Spyder):

![image](https://user-images.githubusercontent.com/25891214/78686391-8b893f80-7925-11ea-828d-c31dce3d1949.png)

but the VSCode variables effect is this:

![image](https://user-images.githubusercontent.com/25891214/78686491-ae1b5880-7925-11ea-8047-ceb24b63294d.png)

the left data is bad.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@p5ydn0 Can you reopen this issue on https://github.com/Microsoft/vscode-python? I'm sorry, I'm not able to move it there

**Comment by p5ydn0** [comment]
> @p5ydn0 Can you reopen this issue on https://github.com/Microsoft/vscode-python? I'm sorry, I'm not able to move it there

Thank you for your reply. I'm sorry I misplaced it. I will consider moving it to the issues of VScode-Python project. Thanks again.
