### ISSUE TITLE
Focus lost in notebook 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#94613]
- Focus code cell editor
- Open command palette
- Press esc
- Focus should be in the editor, but it's not, I'm not sure where it is

Not sure what's going on here, is something supposed to restore focus to the editor manually?

**Comment by rebornix** [comment]
I'm not seeing this issue on master

![Kapture 2020-04-07 at 10 23 40](https://user-images.githubusercontent.com/876920/78700698-a377a980-78ba-11ea-874b-03d8105675d0.gif)

**Comment by roblourens** [comment]
I dunno, yeah I guess it's fine now.
