### ISSUE TITLE
auto close tag doesn't work in vue file

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#94614]
- Version: 1.43.2 (user setup)
- Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
- Date: 2020-03-24T07:38:38.248Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. create and open a vue file
2. type `<div>`，doesn't auto close `div` tag

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by tjx666** [comment]
For now,VSCode supports auto close tag in js/ts file, why not consider support in vue file?

**Comment by octref** [comment]
Only extension can support it for Vue.

**Comment by SliverYuki** [comment]
> Only extension can support it for Vue.
> 
> 只有扩展才能为 Vue 支持它。

Why not consider providing file type(or language) configuration？Just like [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)
![image](https://user-images.githubusercontent.com/19161689/81517980-2cc54480-936f-11ea-8901-0b2f16d2e18e.png)
