### ISSUE TITLE
Semantic Highlighting can't be enabled to allow realistic previewing of external color themes. 

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode#94624]
- VSCode Version: VSCode - Insiders 1.44
- OS Version: MacOS

Steps to Reproduce:

1. In VSCode, open a file with a file-extension for a language with no TM Grammer or a very limited TM Grammar
2. Install an extension to provide semantic highlighting for this language/file-extension
3. Files in editor shows correct semantic highlighting for built in color themes
4. Attempt to preview external color themes by quickly switching through user color theme preferences
5. All external color themes show no semantic highlighting - it's not possible to preview semantic highlighting.
6. User settings override this, but only work for one named theme at a time (e.g. City Lights) this can not realistically be done for previewing many color themes :
```json
{
	"editor.tokenColorCustomizations": {
		"[City Lights]": {
			"semanticHighlighting": true
		}
	}
}
```
Does this issue occur when all extensions are disabled?: It affects a semantic highlighting extension so this must be enabled to reproduce. Other extensions make no difference enabled or disabled.

**Suggestion:** Provide an option to temporarily enable semantic highlighting for when each external color theme is currently selected in the command drop-down list, but not 'confirmed'.

If an external color theme is selected, the user could then be prompted if they wanted to enable semantic highlighting permanently for that theme.

Other solutions may also work.

**Comment by aeschli** [comment]
You could turn on semantic highlighting for all themes like that 
```
{
	"editor.tokenColorCustomizations": {
		"semanticHighlighting": true
	}
}
```
But in the end we give the theme the say over whether the theme is inteded for semantic highlighting. Override the theme and turn on semantic highlighting in the user settings is more like a advanced feature (It's like customizing a theme) and should not become a common thing that users specify when they select a theme. 

Therefore I don't think we should not have the preview theme picker also allow to set/unset semantic highlighting.

But I see your dilemma for your use case where you rely on semanticHighlighting to be on.

In this milestone we will reach out to to the top theme authors to adopt semanticHighlighting.
Maybe eventually we can set the default to true

**Comment by pgfearo** [comment]
OK, thank you. XSLT developers have had to wait a few years for syntax
highlighting in VSCode. Another month or two's wait for color theme support
is not too much of an issue I guess.

**Comment by aeschli** [comment]
Thanks for the feedback. Closing the issue.
