### ISSUE TITLE
Issue while repainting in cmd console

### ISSUE THREAD

**Issue by assafi** [Microsoft/vscode#9462]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

The following steps are probably the longest way of doing this, but this is what I did.
You can run any script that periodically repaints a certain line. (e.g. progress bar/percentage).

Steps to Reproduce:

1. Open the console window (ctrl+`)
2. Launch powershell
3. Use AzCopy.exe to copy a lot of files to azure blob storage. This command usually will list just a single line that will keep repaining with new info:

Finished: 555 file(s), transfer speed: 66.84 MB/s

instead of one line, it will spit a new line every few seconds (I assume the refresh cycle).

Finished: 555 file(s), transfer speed: 66.84 MB/s
Finished: 558 file(s), transfer speed: 68.31 MB/s
...

This can probably be done with other commands as well.

**Comment by Tyriar** [comment]
This is definitely an upstream issue and I'm not sure this can be fixed, it likely resides in winpty. The situation may have been improved in a newer version but vscode is currently on an older one as this is an indirect dependency.
