### ISSUE TITLE
Integrated terminal font rendering doesn't match editor

### ISSUE THREAD

**Issue by rolandcrosby** [microsoft/vscode#94623]
- VSCode Version: 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50)
- OS Version: macOS 10.14.6

Even when the same font family and size are configured for the editor and the terminal, the font rendering in the integrated terminal does not match the font rendering in the editor. In the attached example screenshot, I have the font for both set to 12pt Consolas, and my screen is non-retina. The character shapes, anti-aliasing, line height, and letter spacing are all different between the terminal and the editor.

![Screen Shot 2020-04-07 at 2 01 42 PM](https://user-images.githubusercontent.com/60245/78703560-64f0e780-78d8-11ea-96d6-ded1aaba8742.png)

Steps to Reproduce:

1. Ensure that the editor font family and font size preferences match the integrated terminal font family and font size preferences.
2. View some text in the editor and in the terminal and compare the rendering.

Does this issue occur when all extensions are disabled?: Yes. Attached screenshot has extensions disabled.

**Comment by rolandcrosby** [comment]
Nope, it's none of those.

**Comment by Tyriar** [comment]
You can change this setting to align rendering with the editor, you'll likely notes a shift in performance though.

```
"terminal.integrated.rendererType": "dom"
```

**Comment by rolandcrosby** [comment]
Thanks! The DOM rendering looks much closer, and I was able to get the terminal's line height to match the editor's as well by process of trial and error.

The horizontal spacing still appears slightly inconsistent by some fraction of a pixel. Is there a way to make it match exactly? See attached animation - the left side is perfectly aligned but the terminal text is slightly wider by the right edge.

![domterminal](https://user-images.githubusercontent.com/60245/78736444-2c263200-791b-11ea-94dd-22421bcdc766.gif)

Is making the terminal's canvas text rendering look like the editor's text rendering considered a non-goal?

**Comment by Tyriar** [comment]
Yes it's not a goal, performance is more important for the terminal as its text buffer is far more dynamic than the editor's.
