### ISSUE TITLE
Editor & Python console - Sharing exact syntax highlighting and color theme (similar to default in PyCharm)

### ISSUE THREAD

**Issue by Alcampopiano** [microsoft/vscode#94628]
Hello,

Thank you very much for VS code. 

In PyCharm, the Python console shares the exact syntax highlighting and color theme of the editor. This occurs automatically without any changes to the settings. For example:

![sc](https://user-images.githubusercontent.com/4624246/78709387-8c987d80-78e1-11ea-9573-541ac1b859ac.png)

In VS code, as far as I can tell, it is a lot more work (perhaps even impossible) to get the editor and Python console to share the same theme exactly. Out of the box we get the following, which is much less easy on the eyes.

![sc1](https://user-images.githubusercontent.com/4624246/78710256-07ae6380-78e3-11ea-97c8-f557f575f6a9.png)

For folks who work interactively in the console it is very helpful to have the equivalent theme in both areas. This may be especially true for beginners who can use the consistency between the editor and the Python console as a way to help them catch syntactical errors. 

From what I can understand from looking into this is that there are ways of customizing just about any property of the Python console if you know which properties you need to adjust. I am not able to easily determine how to take the exact properties of the editor theme, and reflect them to the Python console. 

Please let me know if I am missing something straightforward and if you think this would be a reasonable feature request.

**Comment by Tyriar** [comment]
The Python extension owns the Python experience in VS Code, please report to https://github.com/microsoft/vscode-python/

**Comment by Alcampopiano** [comment]
Thank you very much.
