### ISSUE TITLE
Terminal toggle (ctrl+`) doesn't always focus the terminal

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94629]
With a panel layout below:
![image](https://user-images.githubusercontent.com/641685/78712481-9d97bd80-78e6-11ea-8744-3d7eb6b12cf6.png)

The `workbench.action.terminal.toggleTerminal` command doesn't always focus the terminal. For example, if focus is in the debug console, the first time you press ctrl+\` it won't have a visible effect -- focus will still be in the debug console, but if you press ctrl+\` again, it will then focus the terminal

**Comment by sbatten** [comment]
fyi @Tyriar

**Comment by sbatten** [comment]
This was happening for many pairings of views.

To Verify:
1. Set keybindings for focusing all built-in panels (Debug, Terminal, Output, Problems) if you don't already have them.
2. Move all built-in panels into a single panel
3. Use the keybindings to move focus between all pairs in both directions.

Ensure focus moves with a single keybind press.
