### ISSUE TITLE
Gutter indicators don't appear for source from mapped network drive

### ISSUE THREAD

**Issue by danielavatamanu** [microsoft/vscode#94636]
- VSCode Version: 1.43.2 (system setup)
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Open folder from mapped network drive on Windows 7
2. No changes are shown in gutter: deleted/changed/new lines

![image](https://user-images.githubusercontent.com/2981566/78725063-58e84280-7937-11ea-9ee5-ec3da28cdfee.png)

Notes:
This does not reproduce in a desktop folder (not from mapped network drive)

![image](https://user-images.githubusercontent.com/2981566/78724743-c47de000-7936-11ea-9a6e-bb68c2e4161c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you show me the *full* contents of `Git: Show Git Output`?
