### ISSUE TITLE
Show active usage in accounts menu

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#94635]
When clicking on an account from the accounts menu, there should be an option like "Show Active Usage" that will display a list of features and extensions that have accessed a token for the account during this session

**Comment by RMacfarlane** [comment]
To verify:

1. Create an extension that uses one of the authentication providers:
```
		const session = await vscode.authentication.login("github", ['user:email']);
		const token = await session.getAccessToken();
		vscode.window.showInformationMessage(`Successfully logged with ${token}`);
```
2. After signing in, click on the account in the accounts menu
3. Choose "Show Extensions and Features using this Account", the name of the extension should be displayed

**Comment by aeschli** [comment]
Verified with steps above
