### ISSUE TITLE
Spaces in application name break Homebrew

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#94639]
- VSCode Version: 1.43.2
- OS Version: macOS 10.5 Catalina

Steps to Reproduce:

1. Add `/Applications/Visual Studio Code.app/Contents/Resources/app/bin` to `PATH` environment variable.

Does this issue occur when all extensions are disabled?: Yes

Specifically, the space in the `Visual Studio Code.app` name creates parsing problems for many `brew` commands.

... can we please rename the official app to something without spaces, like `VSCode.app`

**Comment by RMacfarlane** [comment]
@mcandre You can escape the spaces with "\\"

`/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin`
