### ISSUE TITLE
Cannot search and view symbols in outline that are inside export default object

### ISSUE THREAD

**Issue by kliput** [microsoft/vscode#94630]
- VSCode Version: 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
- OS Version: Linux x64 5.3.0-45-generic (Ubuntu 19.10)

Steps to Reproduce:

1. Create JS file with content:

```javascript
export default {
  foo: 1,
};
export const hello = {
  world: 2,
};
```

![image](https://user-images.githubusercontent.com/1345438/78715882-4f9eac00-791e-11ea-8173-435f7bbe444c.png)

2. The code outline and symbol search (Ctrl+Alt+O) will show: _default, hello, world (nested)_, while it should (as in previous VSCode versions): _default, foo (nested), hello, world (nested)_ - **foo is missing,** as well as other symbols if they were put inside default symbol.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/37877 to track upstream
