### ISSUE TITLE
Side loaded extensions don't prompt when outdated.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#9463]
- VSCode Version:1.3.1, 1.4.0-insiders
- OS Version:Windows 10

Steps to Reproduce:

1. Download ESLint extension version 0.10.17 using URL: https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/0.10.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
2. Rename .zip to .vsix and install the .vsix with File > Open File...
3. Restart VS Code and check that installed version is 0.10.17.  The current Marketplace version is 0.10.18 so should be prompted to update.  Check Show Outdated Extensions, nothing.

This also happens if you side load 0.10.18 and then change the version to 0.10.17.  VS Code doesn't detect the extension as outdated.

If you install 0.10.18 from Extension view, and change the version number to 0.10.17, it will be detected as outdated.

**Comment by gregvanl** [comment]
When an extension is side loaded, the __metadata field in package.json is null.

If installed through VS Code Extension view:
```json
	"__metadata": {
		"id": "583b2b34-2c1e-4634-8c0b-0b82e283ea3a",
		"publisherId": "29859a75-d81b-4f0e-8578-2c80ecee6f99",
		"publisherDisplayName": "Dirk Baeumer"
	}
```

side loaded: 

```json
"__metadata": null
```

**Comment by joaomoreno** [comment]
Yeah, this is as designed. Side loaded extensions are not _linked_ to the marketplace.
