### ISSUE TITLE
[snap] Environment variables exported in electron-launcher break children processes.

### ISSUE THREAD

**Issue by jasiekmarc** [microsoft/vscode#94632]
- VSCode Version: 1.43.2 (**snap**)
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open external terminal (Ctrl+Shift+C).
2. Type `evince`.
3. Evince (or any GTK application installed with apt package manager) crashes, because of `GDK_PIXBUF_MODULE_FILE` environment variable pointing to `$HOME/snap/code/common/...`.

Offending line: https://github.com/microsoft/vscode/blob/7489b38747b21313f27f0c09d35ca7015d8e5fbb/resources/linux/snap/electron-launch#L25

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This was fixed earlier this week: https://github.com/microsoft/vscode/issues/85344
