### ISSUE TITLE
mac support for Web browser marketplace integration

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#94641]
Please use URI's to communicate between the Web browser plugin marketplace view, so that mac users can click to download and install plugins into their VSCode application, just like Windows users.

**Comment by yume-chan** [comment]
I don't understand. Visual Studio Code marketplace is currently using `vscode:` schema to communicate with Code.

For example, click the `Install` button in the image below

![image](https://user-images.githubusercontent.com/1330321/78737797-fc127980-7982-11ea-8836-d31413954a4f.png)

will open `vscode:extension/streetsidesoftware.code-spell-checker`, which opens the extension page in my Code correctly on my mac.
