### ISSUE TITLE
integrated terminal colors are off (git-bash.exe)

### ISSUE THREAD

**Issue by zkxwpdam** [microsoft/vscode#94643]
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. install vscode (default dark+ theme, "terminal.integrated.minimumContrastRatio": 1,)
2. "terminal.integrated.shell.windows": "C:\\git-bash\\bin\\bash.exe",
3. open integrated terminal ➡️ colors are kinda off
😕 
![Capture](https://user-images.githubusercontent.com/16976424/78733988-555cb780-7947-11ea-9ddf-4ef4e0247d07.PNG)

Does this issue occur when all extensions are disabled?: Yes/

**Comment by Tyriar** [comment]
The colors are defined by the theme. You can also change them to whatever you want in settings like this:

```json
"workbench.colorCustomizations": {
    "terminal.ansiBlack": "#000000",
    // ...
}
```
