### ISSUE TITLE
Selected launch config from remote workspace file not persisted

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#94646]
- Open a multiroot remote workspace
- Have launch config "A" defined in the workspace config file
- Launch "A"
- Reload the window
- "A" is not selected anymore

Seems to work fine for single folder windows and local multiroot workspace launch configs so maybe it has to be remote + launch config in workspace file.

**Comment by isidorn** [comment]
@roblourens my suspicion is that on startup the remote is not resolved (since we resolve it asyncly) and somehow before that we try to select a launch config which is not yet there.
