### ISSUE TITLE
Drag Right Mouse to see the whole content of editor

### ISSUE THREAD

**Issue by Destroyer-LDB** [microsoft/vscode#94647]
I used to use Code::Blocks to develop C++, but now I use VS Code. I am used to a function of Code::Blocks--drag the right mouse to see the whole content of editor. But VS Code does not support it. I hope VS Code could have it.

**Comment by RMacfarlane** [comment]
@Destroyer-LDB Can you clarify? I'm having trouble understanding how it displays the whole content of the editor. Is it a zoomed out view of everything? Is it scrolling?
