### ISSUE TITLE
Cannot open folder as workspace after deleting it

### ISSUE THREAD

**Issue by liamwarfield** [microsoft/vscode#94644]
- VSCode Version: 1.43.2
- OS Version: Fedora 29

Steps to Reproduce:

1. Open folder in VS code: file->OpenFolder
2. $ rm -rf that/folder/
3. $ mkdir that/folder/
4. $ echo hi > that/folder/hi.txt
5. Open that folder again in VS code: File->OpenFolder

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
