### ISSUE TITLE
support syntax highlighting for json5

### ISSUE THREAD

**Issue by netexe** [Microsoft/vscode#9464]
- VSCode Version: 1.3.1
- OS Version: Win10

I config in setting.json:

```
"files.associations": {
    "*.json5": "json"
}
```

 But it's urgly.

Does vscode have syntax highlighting supporting for json5?

**Comment by lextm** [comment]
There is no existing one,

https://marketplace.visualstudio.com/search?term=json5&target=VSCode&sortBy=Relevance

So you might start your own,

https://code.visualstudio.com/docs/extensions/overview

**Comment by mrmlnc** [comment]
Resolved by https://github.com/mrmlnc/vscode-json5.

@kieferrm or @aeschli, please, close this issue.

**Comment by mjbvz** [comment]
Yes, please try the extension: https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-json5
