### ISSUE TITLE
jupyter notebook failed to launch

### ISSUE THREAD

**Issue by malsharawy** [microsoft/vscode#94648]
Issue Type: <b>Bug</b>
I ran jupyter lab on ,y ubuntu then the jupyter notebook in vscode gave me this error:
jupyter notebook failed to launch. Error: The Jupyter notebook server failed to launch in time [I 04:49:12.780 NotebookApp] The port 8888 is already in use, trying another port.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-45-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (10.00GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
printcode|nob|3.0.0

</details>

**Comment by RMacfarlane** [comment]
Hi @malsharawy, please file this issue against the Python extension here: https://github.com/Microsoft/vscode-python
