### ISSUE TITLE
Intelisense not working

### ISSUE THREAD

**Issue by navthi** [microsoft/vscode#94653]
Issue Type: <b>Bug</b>

After update, intelisense not working

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.0
npm-intellisense|chr|1.3.0
bracket-select|chu|2.0.1
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.2
githistory|don|0.6.3
es7-react-js-snippets|dsz|2.7.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
react-native-react-redux|EQu|2.0.3
html-slim-scss-css-class-completion|gen|1.5.23
rest-client|hum|0.23.2
Angular2|joh|9.1.2
node-module-intellisense|lei|1.5.0
json-to-ts|Mar|1.7.4
vscode-docker|ms-|1.0.0
cordova-tools|msj|1.9.3
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
react-proptypes-intellisense|OfH|1.0.3
java|red|0.59.1
vscode-yaml|red|0.7.2
javascript-typescript|sou|0.0.7
vscode-java-debug|vsc|0.25.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
ReactSnippets|xab|2.4.0
material-theme|zhu|3.2.5

</details>

**Comment by RMacfarlane** [comment]
@navthi For what language?
