### ISSUE TITLE
Cannot type in terminal

### ISSUE THREAD

**Issue by arielsumeruk** [microsoft/vscode#94659]
- VSCode Version:1.43.2
- OS Version:Windows_NT x64 6.2.9200

Steps to Reproduce:

1.Launch VScode and try and type anything in the terminal
2. I deleted and reinstalled VS code several times and the problem persists
I install vs code through anaconda 1.9.12

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by arielsumeruk** [comment]
Thanks Daniel
I did change the setting of "terminal.integrated.windowsEnableConpty": from
false to true but it does not make a difference, there is still no
response when I try and type in the terminal
kind regards
Ariel

**Comment by Tyriar** [comment]
@arielsumeruk you need to be on Windows 10 v1903 to use conpty as mentioned here https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423

**Comment by arielsumeruk** [comment]
Dear Daniel
Thank you for the response, but I do not understand. If the terminal does
not work when the setting is either true or False then how can it work? is
this not a different issue?

**Comment by Tyriar** [comment]
@arielsumeruk there are some quirks with the old system (sometimes it fails randomly, anti-virus can block etc.) and we've moved on to a vastly better one developed inside Microsoft. I recommend upgrading to Windows 10 to get on the new better supported backend.

**Comment by arielsumeruk** [comment]
Thanks Daniel
I believe that I am on the latest version, my last update was just over a
week ago. I have version 10.0.18362 build 18362 , Is it possible to get a
newr build?

**Comment by Tyriar** [comment]
Oh? You filled in Windows 8 though? 😕 

> OS Version:Windows_NT x64 6.2.9200

**Comment by arielsumeruk** [comment]
Ok I see what happened
In the visual studio about it has OS:windows_NT x64 6.2.9200 which what I
entered together with the VS code version
but when I checked after your email response in my computer setting it is
definitely windows 10.
[image: image.png]
[image: image.png]

**Comment by Tyriar** [comment]
Can you post a screenshot of what the terminal looks like and your settings.json file? You could also try trace logging to see how the terminal is launching https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by arielsumeruk** [comment]
Dear Daniel
I tried to do the trace logging by following the steps in the link you
sent  but after I select Developer: Open Log File...   nothing happens, no
log file opens
.
[image: image.png]

this is the content of the setting .json in the
..\AppData\Roaming\Code\User   directory
{
    "python.dataScience.sendSelectionToInteractiveWindow": true,
    "python.pythonPath": "C:\\Users\\Ariel\\Anaconda3",
    "terminal.integrated.inheritEnv": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.windowsEnableConpty": true,
    "editor.formatOnSave": true,
    "terminal.integrated.allowMnemonics": true,
    "terminal.integrated.automationShell.windows": ""
}

**Comment by Tyriar** [comment]
The screenshot didn't attach.

> "terminal.integrated.automationShell.windows": ""

This might be a problem.

>  "terminal.integrated.inheritEnv": false,

Also try change this.

**Comment by arielsumeruk** [comment]
Hi Daniel
Not sure what you are asking me. I was never able to sort the issue out. I
uninstalled and reinstalled VScode and anaconda several times but he
problem persists
kind regards
Ariel

**Comment by Tyriar** [comment]
Your screenshot did not attach as you replied via email and github doesn't support that. I also called out settings that you can try and change. Reinstalling VS Code won't remove your settings files.
