### ISSUE TITLE
Causes Latte Dock to freeze while VSCode open

### ISSUE THREAD

**Issue by TechnicalJohn** [microsoft/vscode#94651]
Issue Type: <b>Performance Issue</b>

STEPS TO REPRODUCE
1. Latte Dock running on left side, 1 KDE panel at top hosting system tray and clock, 4 virtual desktops.
2. open VSCode, 
3. Switching virtual desktops seems to initiate this behavior, as well as starting additional applications, like Calc
4. The animations of Latte and response become slowed by at least 2 seconds, sometimes even longer.
5. After closing VSCode, Latte immediately begins acting as expected without delays.

SOFTWARE/OS VERSIONS
Linux/KDE Plasma: Kubuntu 18.04
(available in About System)
KDE Plasma Version: 5.12.9
KDE Frameworks Version: 5.44.0
Qt Version: 5.9.5
Kernel Version: 5.3.0-7642-generic
OS Type: 64-bit
Hardware: Intel i7-4710MQ; 16GiB RAM
Latte Dock: 0.8.9
***VSCode***
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-7642-generic

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 3282)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.56GB (2.59GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  6049	code main
    0	    32	  6052	   zygote
    0	    80	  6074	   gpu-process
    0	    48	  6087	   utility
    0	   239	  6099	   window (Pipfile - PythonTuri - Visual Studio Code)
    0	   127	  6152	     extensionHost
    0	    48	  6168	     watcherService
    0	    48	  6185	     searchService
    0	   112	  6251	   shared-process
    0	     0	  6322	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  6323	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    96	  6300	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Pipfile - PythonTuri - Visual Studio Code)
|    Folder (PythonTuri): 8 files
|      File types: lock(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
cobol|bit|6.0.23
xml|Dot|2.5.0
gitlens|eam|10.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-circuitpython|joe|0.1.0
csharp|ms-|1.21.16
python|ms-|2020.3.71659
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.42.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.27.0
platformio-ide|pla|1.10.0
language-pde|Tob|1.4.1
material-theme|zhu|3.2.5

</details>

**Comment by deepak1556** [comment]
The slowdown is seen with https://www.electronjs.org/fiddle as well, can you open an issue in https://github.com/electron/electron using electron-fiddle as a minimal example app and link the issue here. Thanks!

**Comment by Rwantare** [comment]
I've been having this issue for months and only recently narrowed it down to VScode, since closing it makes the everything snappy again.
Similar setup, mobile Intel CPU with kernels over 5, kde + 18.04, and latte-dock laid out like unity.

**Comment by Rwantare** [comment]
> The slowdown is seen with https://www.electronjs.org/fiddle as well, can you open an issue in https://github.com/electron/electron using electron-fiddle as a minimal example app and link the issue here. Thanks!

The issue does not manifest when using fiddle. I've tested with 0.14.0-x64

**Comment by deepak1556** [comment]
@Rwantare which version of electron did you use in the fiddle ? Can you try electron version `7.1.11` ?

**Comment by Rwantare** [comment]
![image](https://user-images.githubusercontent.com/7354437/79672798-9749f100-81c4-11ea-97ee-a8150f36465d.png)
Using electron 7.1.11 doesn't trigger the slowdown.

**Comment by red0orange** [comment]
I have this issue too, now have solutions?

**Comment by Rwantare** [comment]
I had to nuke my Ubuntu install for other reasons, but after setting up a fresh Kubuntu 20.04 LTS, I have no issues. I wonder if the problems stemmed from switching between gnome and kde on 18.04.

**Comment by joe-habel** [comment]
I also am experiencing a similar freezing of latte dock when VSCode is open. I also just recently updated to Ubuntu 18.04 and installed kde via Kubuntu alongside gnome. 

However, after booting a Kubuntu 18.04 live image, installing latte-dock and code, this problem still persisted.

I can say that booting a Kubuntu 20.04 live image did eliminate the problem, so this is definitely isolated to something in Kubuntu 18.04.

**Comment by NNesh** [comment]
_Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-43-generic_

This VS Code (after updating) doesn't cause lags of the Latte-Dock for me on Kubuntu 18.04.

**Comment by TechnicalJohn** [comment]
Woohoo, I can confirm that it seems to be fixed!
