### ISSUE TITLE
Terminal font render size connecting external displays

### ISSUE THREAD

**Issue by aladinoster** [microsoft/vscode#94656]
- VSCode Version: 1.43.2
- OS Version: OS X 10.15.1

Steps to Reproduce:

1. Open VSCode, open a terminal
![Screenshot 2020-04-08 at 07 44 04](https://user-images.githubusercontent.com/9197388/78748773-1e010180-796d-11ea-952f-e26bedf0abcb.png)

2. Connect an external display, then the font renders in a small way 
![Screenshot 2020-04-08 at 07 43 26](https://user-images.githubusercontent.com/9197388/78748796-2a855a00-796d-11ea-8fa5-d06e1537a417.png)

3. Disconnecting the external display comes to this situation 
<img width="1399" alt="Screenshot 2020-04-08 at 07 42 57" src="https://user-images.githubusercontent.com/9197388/78748829-3e30c080-796d-11ea-8598-6b4c0a8ad9a2.png">

I'm currently using these settings for the terminal:
```
"terminal.integrated.fontFamily": "Source Code Pro for Powerline, 'SourceCodePro+Powerline+Awesome Regular'",
    "terminal.integrated.fontWeightBold": "600",
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.showExitAlert": false,
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.copyOnSelection": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.rendererType": "experimentalWebgl",
    "terminal.integrated.inheritEnv": false,
    "terminal.integrated.minimumContrastRatio": 4.5,
```

I've already read #28747, #6196 and it seems the problem is due to electron and only windows reported.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
I think this has been pulled in.
