### ISSUE TITLE
Shortcut Key For Task Shows Task List

### ISSUE THREAD

**Issue by vscode-pmaher** [microsoft/vscode#94654]
Custom keyboard shortcut for task shows task list instead of running task.

- VSCode Version: 1.4.32
- OS Version: Windows 10

Steps to Reproduce:

1. Create a task in C:\Users\<USERNAME>\AppData\Roaming\Code\User\tasks.json
2. Create a shortcut to run task

Does this issue occur when all extensions are disabled?: Yes

**Comment by vscode-pmaher** [comment]
I see a similar issue closed (#90344) - However, I have tried putting task in global task.json and workspace level task.json but with the same problem in both cases

**Comment by alexr00** [comment]
I can't reproduce this issue.
My task in user tasks:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo from settings",
            "type": "shell",
            "command": "echo Hello"
        }
    ]
}
```
My keyboard shortcut:
```json
	{
		"key": "ctrl+shift+alt+t",
		"command": "workbench.action.tasks.runTask",
		"args": "echo from settings"
	}
```

**Comment by vscode-pmaher** [comment]
My bad, for "args" in my shortcut I put the task command instead of label ... all working now:

`{
   "version": "2.0.0",
   "tasks": [
      {
         "label": "Open in Chrome",
         "presentation": {
            "reveal": "never"
         },
         "command": "Chrome Preview",
         "windows": {
            "command": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
         },
         "args": [
            "http://127.0.0.1/${workspaceFolderBasename}/${relativeFile}"
         ]
      },
      {
         "label": "Open in Firefox",
         "presentation": {
            "reveal": "never"
         },
         "command": "Firefox Preview",
         "windows": {
            "command": "C:/Program Files/Mozilla Firefox/firefox.exe"
         },
         "args": [
            "http://127.0.0.1/${workspaceFolderBasename}/${relativeFile}"
         ],
         "problemMatcher": []
      }
   ]
}`

`{
   "version": "2.0.0",
   "tasks": [
      {
         "label": "Open in Chrome",
         "presentation": {
            "reveal": "never"
         },
         "command": "Chrome Preview",
         "windows": {
            "command": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
         },
         "args": [
            "http://127.0.0.1/${workspaceFolderBasename}/${relativeFile}"
         ]
      },
      {
         "label": "Open in Firefox",
         "presentation": {
            "reveal": "never"
         },
         "command": "Firefox Preview",
         "windows": {
            "command": "C:/Program Files/Mozilla Firefox/firefox.exe"
         },
         "args": [
            "http://127.0.0.1/${workspaceFolderBasename}/${relativeFile}"
         ],
         "problemMatcher": []
      }
   ]
}

`//ARGS SHOULD MATCH THE "LABEL" VALUE OF TASK
[
  {
    "key": "ctrl+alt+f",
    "command": "workbench.action.tasks.runTask",
    "args": "Open in Firefox"
  },
  {
    "key": "ctrl+alt+c",
    "command": "workbench.action.tasks.runTask",
    "args": "Open in Chrome"
  }
]`

Thanks 👍
