### ISSUE TITLE
Missing output with clear then scroll

### ISSUE THREAD

**Issue by LOZORD** [Microsoft/vscode#9466]
- VSCode Version: 1.3.1
- OS Version: OSX Yosemite 10.10.5

This could be a mismatch in opinion for the behavior of `clear` or `Ctrl-L` and scrolling (as I believe I've seen this behavior on a Linux Mint machine), but here's my problem:

Let's say I have a lot of output from a certain command in the integrated terminal (mine uses bash). If I enter `clear` or `Ctrl-L`, the terminal gets cleared, which is good! However, if I scroll up, a chunk of output from the verbose command is missing (seems directly related to the height of the terminal window).

What I expected: Using _my_ default bash terminal on my Mac, the screen gets cleared, but if I scroll up, __all__ the output is still there.

Steps to Reproduce:

1. Open the integrated terminal (I supply the `-l` option in `settings.json` in order to use my `~/.bash_profile`)
2. Run a command with lengthy ouput (e.g. `ruby -e 'puts "START";100.times { |n| puts "Line #{ n + 1 }" };puts "END"'`)
3. Enter `clear`
4. Scroll up

With the terminal occupying around 80% of my screen height, I only got output of that Ruby command to around line 50 (i.e. I never see "END" after clearing).

If this is just a matter of terminal opinion, it might be nice to have an option in `settings.json` to define the clear/scroll behavior.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/sourcelair/xterm.js/issues/106
