### ISSUE TITLE
cmd+click open external websites confilcts with internal references

### ISSUE THREAD

**Issue by Cygra** [microsoft/vscode#94663]
- VSCode Version: 1.43.2
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. create a .js/.ts file with such code:

```javascript
const getUrlPrefix = env => 'www'
const getBaseUrl = env => `https://${getUrlPrefix(env)}.example.com`;
```

![image](https://user-images.githubusercontent.com/34186314/78752638-034b7e80-79a7-11ea-80ab-0777ba0dcd81.png)

2. `cmd + click` on the `getUrlPrefix` in the template string
The cursor will focus on the definition of `getUrlPrefix` and at the same time jump out an alert on the top asking whether to open the external website.

![image](https://user-images.githubusercontent.com/34186314/78752556-e7e07380-79a6-11ea-9f15-1383de9e209e.png)

It could be better that only open the external link when the clicked element has no definition.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
We do not evaluate javascript in the link detected.
