### ISSUE TITLE
No internet connection from integrated terminal when using a corporate VPN

### ISSUE THREAD

**Issue by yogeek** [microsoft/vscode#94660]
- VSCode Version: 1.43.2
- OS Version: Windows 10 Entreprise

Steps to Reproduce:

1. Disable VPN client
3. Search/Install extension in VSCode : OK
3. Open Integrated Terminal : internet connection OK (curl http://www.google.fr)
5. Enable VPN client
7. Search/Install extension in VSCode : OK
8. Open Integrated Terminal : internet connection KO

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@joaomoreno any insights?

**Comment by yogeek** [comment]
If it may help, here is some additionnal information : 
- the shell I used in my first post was "bash" (from git bash exe) but I have the same problem using "powershell" in VSCode integrated terminal
- I also have the problem in "git bash" or "powershell" outside of VSCode even if my internet connection in Chrome is working fine
- in VSCode bash integrated terminal, if a export "http_proxy" and "https_proxy" env vars with CNTLM details (`http://127.0.0.1:3128`) I can access internet.

So I do not understand :
- why VSCode is not picking the network config of my system ? (well it seems to be the case for extensions bu not for integrated terminal) Is it because the integrated terminal is only a view of external applications lie gitbash.exe or powershell.exe and VSCode has no way to pass network config to them ?
- why terminal applications (gitbash or powershell) cannot access internet whereas Chrome is able to with the network system config.

**Comment by joaomoreno** [comment]
> * I also have the problem in "git bash" or "powershell" _**outside**_ of VSCode even if my internet connection in Chrome is working fine

This seems unrelated to VS Code at all because of what's mentioned above.

> Is it because the integrated terminal is only a view of external applications lie gitbash.exe or powershell.exe and VSCode has no way to pass network config to them ?

Yes.

> why terminal applications (gitbash or powershell) cannot access internet whereas Chrome is able to with the network system config.

Don't know, but this is unrelated to VS Code. Stackoverflow is a great place to ask such a question.
