### ISSUE TITLE
Merge Conflict

### ISSUE THREAD

**Issue by luigiangelino** [microsoft/vscode#94669]
Issue Type: <b>Bug</b>

Merge Conflicts dont'work.
Only i can show git Log in output.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
google-translate|han|1.1.1
git-graph|mhu|1.22.0
git-merger|sha|0.4.1
vscode-scss-formatter|sib|2.0.0

</details>

**Comment by RMacfarlane** [comment]
@luigiangelino Can you provide some more details? What doesn't work, is a view not loading, or showing incorrect data?

Is this from the `git-merger` extension? Please try running the `Developer: Reload with extensions disabled` command, does the problem still happen?

**Comment by luigiangelino** [comment]
Thanks RMacfarlane,
i tried after put your command in palette.
But if i try to pull this is the result:
![Annotazione 2020-04-09 090208](https://user-images.githubusercontent.com/57905513/78867087-d51a7d00-7a40-11ea-82a3-d85463f64566.png)

We use Bitbucket by Atlassian for Git, and GitKraken, but i would try to use VS Code for everything. I like git graph to see the tree. So i would not to use Kraken.
Sorry for my english.

**Comment by RMacfarlane** [comment]
@luigiangelino This means that you have currently have changes so cannot pull. Either stash them or commit them.

Can you please provide more details about what isn't working with merge conflicts?
