### ISSUE TITLE
Renaming a folder fails

### ISSUE THREAD

**Issue by DarkLite1** [microsoft/vscode#94664]
Issue Type: <b>Bug</b>

1. Create a folder structure with lots of files and folders in it/.
(Ex. create several node prjoects with 'vue create project`)
2. Try to rename a project created by Vue.js or some other folder in the tree
> notice vs code freezes and the rename fails

VS Code version: Code - Insiders 1.44.0-insider (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T21:41:19.483Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|12.00GB (7.37GB free)|
|Process Argv|T:\Test\Brecht\Node.code-workspace|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.0
vscode-eslint|dba|2.1.2
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.1.1
rest-client|hum|0.23.2
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.6.0
dotenv|mik|1.0.1
vscode-cosmosdb|ms-|0.12.2
azure-account|ms-|0.8.9
powershell-preview|ms-|2020.3.2
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
angular-console|nrw|11.1.3
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
code-spell-checker|str|1.8.0
language-stylus|sys|1.11.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

This is is visible for 5 to 10 seconds after right clicking and renaming a folder:

![image](https://user-images.githubusercontent.com/10828570/78753556-417c7a00-7976-11ea-88a3-d3f1b8adcaa7.png)

Then it fails with this message:

![image](https://user-images.githubusercontent.com/10828570/78753582-4e996900-7976-11ea-94b9-453d18482554.png)

**Comment by octref** [comment]
Does this happen if you disable all extensions?

**Comment by DarkLite1** [comment]
I've just tested that for you like so:
```
code-insiders --disable-extens
```
When I then change a folder name it works. When I then try again to change the folder name, say after 10 seconds, it fails again like before. So I don't think it's related to an extension.

**Comment by octref** [comment]
I'm not sure if this is related to Windows file path limit. If you move the folder to `c:/` drive and rename, does it work?

**Comment by DarkLite1** [comment]
When I close vs code insiders and rename the folder in explorer it gets renamed without an issue. If I leave vs code insiders open and try to rename the folder in explorer it failes to saying that a process is using the folder. So IMHO it should be something within vs code insiders that is locking the folder.

**Comment by bpasero** [comment]
Please use https://docs.microsoft.com/en-us/sysinternals/downloads/handle to find out which process is locking the file or folder. If it is in use, there is nothing VSCode can do. And the fact that it works when you close VSCode indicates that maybe some extension locks it.
