### ISSUE TITLE
code formatting not working

### ISSUE THREAD

**Issue by yash2code** [microsoft/vscode#94661]
Issue Type: <b>Bug</b>

no idea

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:41.240Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|8.00GB (0.30GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.2
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.1.1
composer-support-client|Hyp|0.19.12
solidity|Jua|0.0.72
vscode-docker|ms-|1.0.0
Go|ms-|0.13.1
elmmet|nec|1.0.1
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1
language-stylus|sys|1.11.0
ReactSnippets|xab|2.4.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Also please test with all extensions disabled.
