### ISSUE TITLE
Upgrade version cause keyboard shortcuts conflicts

### ISSUE THREAD

**Issue by jkryanchou** [microsoft/vscode#94666]
- VSCode Version: 1.43.2
- OS Version: 10.14.6

Steps to Reproduce:

1. I have met the keyboard conflicts issues often when I have upgrade the VSCode to latest version.

    It always conflicts with the previous version shortcuts. Such as Go To FIle (cmd + p) is conflict with editor.action.triggerParameterHints. I couldn't trigger the shortcut normally. when I need to open another file.

**Comment by RMacfarlane** [comment]
Do you have any keymapping extensions installed? You can search `@category:keymaps @installed` in the extensions viewlet. Or, if you go to keyboard shortcuts and search for these keybindings, what do you see as the source?

<img width="1178" alt="Screen Shot 2020-04-08 at 3 28 08 PM" src="https://user-images.githubusercontent.com/3672607/78839591-a4d5ce80-79ad-11ea-9f7a-4e217707b9f1.png">

**Comment by jkryanchou** [comment]
@RMacfarlane 

Here are the cmd + p shortcuts, which are conflicts when I focus editor. The hot shortcut cmd + p always impress me on Go to File. I suggest that the main hot keys should not change often.

![image](https://user-images.githubusercontent.com/1206342/78851157-abb31e80-7a4b-11ea-814d-0d218660f67b.png)

**Comment by jkryanchou** [comment]
And here is another conflicts with the Go to Implementations.

![image](https://user-images.githubusercontent.com/1206342/78853428-6e518f80-7a51-11ea-9332-a284c326c0d8.png)

I'm so confused with that keybindings.

**Comment by jkryanchou** [comment]
?????? 

![image](https://user-images.githubusercontent.com/1206342/78853516-9c36d400-7a51-11ea-99e7-0874cc86416f.png)

Wish the major keybindings should not change often.

**Comment by ygerg** [comment]
I noticed this too and landed here: searching for `@category:keymaps @installed` showed that I somehow had IntelliJ keybindings installed, though I'm pretty positive that I've never installed them (as I've never used that IDE in the first place). 

Uninstalling the keybinding extension solved the problem.

**Comment by RMacfarlane** [comment]
@jkryanchou I was confused about the "Source" column, this will be "Default" if the keybinding is from VSCode or from an extension, or "User" if you have manually configured it. I don't have some of the commands in your screenshot, so I think they're coming from an extension. Can you try running `Developer: Reload with Extensions Disabled` to verify that it is an extension adding the keybindings?

**Comment by jkryanchou** [comment]
@RMacfarlane OK, I will try it later.
