### ISSUE TITLE
Do not create tasks.json when creating debug configuration for gcc build active file

### ISSUE THREAD

**Issue by NaLaDracip** [microsoft/vscode#94675]
- VSCode Version: 1.43.2
- OS Version: Ubuntu 18.04.4

Steps to Reproduce:

1. Install C/C++ extension ms-vscode.cpptools
2. Start debugging
3. Select environment: C++(GDB/LLDB)
4. gcc run and debug active file

A launch.json file is created but no tasks.json. I tried to do it by hand by going to Menu -> Terminal -> Configure tasks -> Create tasks.json file from template  I do not have such option for creating tasks.json for 'gcc build active file'

The instruction below is not relevant as the bug is related to the extension extension ms-vscode.cpptools.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
Please reopen this on the C/C++ extension: https://github.com/Microsoft/vscode-cpptools
