### ISSUE TITLE
Initializing JS/TS language features forever and eating all cpu time

### ISSUE THREAD

**Issue by tapz** [microsoft/vscode#94673]
Vscode uses almost all cpu time and tells it's "initializing JS/TS language features". This lasted the whole night and ongoing as we speak. Also get this message:

> The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.
> Source: TypeScript and JavaScript Language Features (Exten...

With extensions disabled, still uses 100% of BOTH of my cpu cores. Would be nice **NOT** to have this kind of multi-threading for just one task in one app. Also with extensions disabled it still tries to start the TS/JS extension. I can tell that other extensions are disabled, as the code coloring is different than with extensions enabled.

I have 5 vscode windows/workspaces open and this error is displayed only in one.

- VSCode Version: 1.43.2
- OS Version: Darwin x64 19.3.0

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:

1. Start vscode
2. Suffer

Does this issue occur when all extensions are disabled?: Yes

In MacOS, this is actually the following:

> open "/Applications/Visual Studio Code.app" --args --disable-extensions

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by tapz** [comment]
I'll read the instructions when I have some free time. Now I have disabled the JS/TS extension and my computer has never worker this fast. Cpu almost idle and low memory consumption. Goodbye jump to functions, but looks like it's worth it.

**Comment by mjbvz** [comment]
Please just share the output of `code --status` when the problem happens

**Comment by tapz** [comment]
I will. Once I have read the instructions how to do that in MacOS.

**Comment by tapz** [comment]
@mjbvz Here you go:

```
2020-04-13 01:43:21.032 Electron[32380:10732135] ApplePersistence=NO
Version:          Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS Version:       Darwin x64 19.3.0
CPUs:             Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)
Memory (System):  16.00GB (0.35GB free)
Load (avg):       158, 47, 19
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    3	    82	 75894	code main
   19	    49	 75899	   gpu-process
    0	    16	 75901	   utility
    3	   147	 75902	   window (create_my_table.sql — myappx (Workspace))
    0	    66	 75994	     extensionHost
    0	    33	 76246	       electron_node eslintServer.js 
    0	    16	 76095	     watcherService
    1	   131	 75903	   window (chat.js — mylib (Workspace))
    0	    66	 75997	     extensionHost
    0	    33	 76182	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=75997
    0	    49	 76183	       electron_node eslintServer.js 
    0	    16	 76093	     watcherService
    1	   197	 75904	   window (Screen1.js — mymobileapp (Workspace))
    0	    66	 75996	     extensionHost
    0	    33	 76124	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=75996
    0	    33	 76340	       /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /Users/tapani/.vscode/extensions/redhat.java-0.59.1/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /Users/tapani/Library/Application Support/Code/User/globalStorage/redhat.java/0.59.1/config_mac -data /Users/tapani/Library/Application Support/Code/User/workspaceStorage/db1616acc28520cf664c6ee18eea6381/redhat.java/jdt_ws
    0	    98	 89564	       electron_node eslintServer.js 
    0	    16	 76091	     watcherService
    2	   164	 75905	   window (webSocketServer.js — mynodeapp)
    0	    66	 75995	     extensionHost
    0	    82	 76294	       electron_node eslintServer.js 
    0	    16	 76092	     watcherService
    2	   180	 75906	   window (webpack.prod.config.js — mywebapp)
    0	     0	 29117	     /bin/zsh -l
    0	    66	 75998	     extensionHost
    0	    33	 76196	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=75998
    0	    16	 76197	       electron_node eslintServer.js 
    0	    16	 76094	     watcherService
    2	    66	 75983	   shared-process

Workspace Stats: 
|  Window (webpack.prod.config.js — mywebapp)
|  Window (webSocketServer.js — mynodeapp)
|  Window (Screen1.js — mymobileapp (Workspace))
|  Window (chat.js — mylib (Workspace))
|  Window (create_my_table.sql — myappx (Workspace))
|    Folder (scripts): 835 files
|      File types: pdf(334) xlsx(334) txt(63) sql(61) js(17) csv(7)
|                  DS_Store(2) eslintrc(1) gitignore(1) jshintignore(1)
|      Conf files: package.json(1)
|    Folder (mywebapp): 133 files
|      File types: png(37) js(33) DS_Store(7) svg(6) json(5) jpg(4) wav(4)
|                  ico(4) html(3) map(3)
|      Conf files: package.json(1)
|    Folder (mylib): 270 files
|      File types: js(249) DS_Store(1) env(1) eslintrc(1) gitignore(1)
|                  jshintignore(1) jshintrc(1) npmrc(1) sequelizerc(1) md(1)
|      Conf files: package.json(1)
|    Folder (mymobileapp): more than 27052 files
|      File types: hpp(14359) h(1058) cpp(382) xml(195) xcconfig(191) png(170)
|                  m(151) ipp(122) js(101) json(98)
|      Conf files: jsconfig.json(1) package.json(1) settings.json(1)
|                  makefile(1)
|    Folder (mynodeapp): 1793 files
|      File types: js(925) png(189) json(100) md(82) less(73) html(72) pug(37)
|                  css(21) DS_Store(7) sql(7)
|      Conf files: package.json(6) gulp.js(3) grunt.js(2) launch.json(1)
|      Launch Configs: node(2)

```

**Comment by mjbvz** [comment]
@tapz Did you run `--status` when the problem was occurring? 

I don't see any high cpu usage or a tsserver process (for JS/TS intellisense) in that output

**Comment by tapz** [comment]
@mjbvz Well, I don't know about processes, but immediately after I enabled the JS/TS extension, vscode ate all my cpu power. That's when I run code --status. Keeping it disabled and everything works smoothly.

**Comment by mjbvz** [comment]
The highest cpu usage I see listed from status is 19%. Where are you seeing the high cpu usage?

**Comment by tapz** [comment]
You think only 19% cpu usage would slow down everything in my computer?

<img width="271" alt="Screenshot 2020-04-14 at 2 57 45" src="https://user-images.githubusercontent.com/11726387/79209787-89a30d00-7e4c-11ea-9874-6120374d02cc.png">

**Comment by tapz** [comment]
Also, I really don't understand why vscode eats memory all the time. It starts from 2GB and grows slowly. Now it's 4GB.

**Comment by mjbvz** [comment]
Please share the process details. Which specific subprocess has the high cpu usage?

Also, be sure to test with extensions disabled. `--stat` shows that you had at least the java and eslint extensions enabled

**Comment by tapz** [comment]
Now it's almost 8GB. Really hungry app...

**Comment by tapz** [comment]
@mjbvz I installed the latest macOS update and restarted the computer again and now the JS/TS extension works. But still it seems to eat memory like a beast.

**Comment by mjbvz** [comment]
Please share the requested information

**Comment by jakebailey** [comment]
The above commit appears to have closed this issue rather than #94637 (which appears to be a typo in the last two digits).

**Comment by mjbvz** [comment]
Closing this as more information is needed however :)

**Comment by web2033** [comment]
@mjbvz 
I have something similar, not CPU intensive but just an annoying infinite loop.
It happens when I quickly move through project files. If I didn't stop on a first .js file and move on to say .css - it keeps like this. If I open .js file and wait for ~2s then it's initialized correctly.

![2020-04-29_204643](https://user-images.githubusercontent.com/11320080/80629238-3d1a1d00-8a5b-11ea-9dd2-92b7cd6e5426.jpg)

**Comment by smth** [comment]
I'm also getting the never ending "Initializing JS/TS language features", if I don't open a JS file.

v1.44.2, Windows 10.
