### ISSUE TITLE
Intellisense does not offer HTML close tags

### ISSUE THREAD

**Issue by ReMark-from-eMark** [microsoft/vscode#94670]
Issue Type: <b>Bug</b>

I am new to coding and this app. I am following a tutorial video and do not have the ability to have Intellisense offer my close tags in HTML in Visual Studio Code ver 1.43.2  The check is on for Intellisense. In a new file called test.html when I type h1 with <> surrounding it no offer to close with the /h1 surrounded with <> (I had to write this way to prevent header text displaying in this document),  is displayed but in the tutorial video that and many other suggestions are showing. All I get is a very simple and generic list like h1 paragraph etc..

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.90GB (7.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.20.0
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
pythonsnippets|frh|1.0.2
MagicPython|mag|1.1.0
python|ms-|2020.3.71659
vscodeintellicode|Vis|1.2.6
jinja|who|0.0.8

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Does this also happen if you run with all extensions disabled?

One way to do that is to open the Command Palette (e.g. by pressing F1), then start typing "reload" until you see "Developer: Reload With Extensions Disabled"

**Comment by RMacfarlane** [comment]
Can you check that the language mode is set to HTML? This is in the bottom right corner:
<img width="365" alt="Screen Shot 2020-04-08 at 8 42 58 AM" src="https://user-images.githubusercontent.com/3672607/78804679-4bea4400-7975-11ea-8750-7ca21be87f51.png">

This should have been set automatically when you saved the file, but I'm wondering if that failed

**Comment by ReMark-from-eMark** [comment]
Rachel, thank you for assisting me. I am sending a screenshot showing 
that setting. I had used this app for Py lessons briefly and some of the 
extensions may have caused something to break? I was thinking about 
running a thorough uninstall (with Revo?) and install clean. Do you 
think that might help me?

Mark Windsor
wxy@z8080.com

------ Original Message ------

**Comment by ReMark-from-eMark** [comment]
While not quite following your instructions I found 'disable all 
extensions', and that did nothing. But then I saw 'developer options to 
reload with extensions disabled', and BAM! that did it! I now see the 
/h1 automatically offered when I enter the hi in <>. Thank you soooo 
much!

Mark

------ Original Message ------

**Comment by ReMark-from-eMark** [comment]
Rachel John Murray suggested I try 'developer mode reload with all 
extensions disabled.. That worked! thanks to you both for helping.

Mark :-)

------ Original Message ------
