### ISSUE TITLE
Add namespace through Code snippet in Visual Studio Code

### ISSUE THREAD

**Issue by ganesanviji** [microsoft/vscode#94672]
I want to give the code snippet extension support for my custom blazor controls to add my codes in the Visual Studio Code editor (.razor files) for my customers. So, I have used the below link to implement this.

https://code.visualstudio.com/api/language-extensions/snippet-guide

Now, my custom code snippets have been added as I expected when to click the ENTER key after typing my prefix value. But, I want to add the namespace also for my controls which are added from the code snippet at the same time of code snippet added. In the above link that gives the options prefix, body and description only. There is no namespace option available. Could you please suggest to me how can I add the Namespace in the razor at the time of add the code snippets?

Also, I want to add the required assemblies at the same time to run my controls to reduce the manual work. Could you please suggest to me this also?

Thanks,
Ganesan R.

**Comment by moshfeu** [comment]
Maybe it's duplicate of #95026
