### ISSUE TITLE
Add "Close and save all" option

### ISSUE THREAD

**Issue by guillaume-f** [microsoft/vscode#94678]
Is it possible to add an option "Close and save all" when a lot of files have been updated ? 
If a use the "Close all" option, I have a popup to save the file for each files updated.

![close-and-save-all](https://user-images.githubusercontent.com/6624534/78772561-3c2d2880-7992-11ea-8c0f-bfdcb2c0c9fa.jpg)

Thanks in advance

**Comment by gjsjohnmurray** [comment]
Alternatively use the Open Editors panel. See #86375

**Comment by gjsjohnmurray** [comment]
Also related: #90231
