### ISSUE TITLE
Language-aware word wrap

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/vscode#94674]
Issue Type: <b>Feature Request</b>

VS Code already does word wrap much better than most other editors, by respecting indentation.

I think it can be made much better by incorporating a handful of language rules.

For example, if I have several services injected in my Typescript constructor, I may end up with a long line.

Word wrap presently makes it look like this

```typescript
  constructor(public app: MyApplicationService, private auth: AuthenticationService, private config:
ConfigurationService, private menus: MenuService) { 
    // Code here
  }
```

But it should be fairly easy to give a more pleasing result, like this:

```typescript
  constructor(public app: MyApplicationService, private auth: AuthenticationService,
  private config: ConfigurationService, private menus: CitadelMenuService) { 
    // Code here
  }
```
First, indentation makes sense. Second, the parameter declaration is kept together.

This becomes much more important when you're nested several levels deep. Take this example, which is already formatted according to most standards:

```typescript
export class SomeClass {
    // ...
    public loadValues() {
        this.http.get('https://example.com/some-web-service')
            .pipe(map(res => res.someProp = this.calculateSomeProp(res)))
            .subscribe(res => {
                if (res.someProp === this.injectedService.nestedObject.sampleValue && this.counter > 1) {
                    this.doSomethingImportant();
                }
            });
    }
}
```

But place it in a second or third pane, or stretch out the search results panel, and you can easily wind up with this actual example:

```typescript
export class SomeClass {
    // ...
    public loadValues() {
        this.http.get('https://example.com/some-web-service')
            .pipe(map(res => res.someProp = this.calculateSomeProp(res)))
            .subscribe(res => {
                if (res.someProp === this.injectedService.nestedObject.sampleValue &
                & this.counter > 1) {
                    this.doSomethingImportant();
                }
            });
    }
}
```

In this case, the indentation is spot on, but notice how the `&&` operator is split into two lines. I'm not going to reproduce the entire listing here, but that `if`-statment also gets wrapped like this:

```typescript
// ...
                if (res.someProp === this.injectedService.nestedObject.sampleValue && this.counter >
                1) {
                    this.doSomethingImportant();
                }
// ...
```

I understand that a long condition like the first one may not be possible to always keep on one line, but surely `this.counter > 1` can be wrapped as a unit?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

**Comment by odonyde** [comment]
I second the need for language-aware word-wrap and indentation, this would also significantly improve the readability of Markdown lists.

Currently wrapped text is aligned with the list item marker:
```markdown
- List item with longer text so that line
gets wrapped.
- Another list item.
```

Readability would improve greatly if it was aligned with the first letter instead:
```markdown
- List item with longer text so that line
  gets wrapped.
- Another list item.
```
