### ISSUE TITLE
Ctrl-C Ctrl-C not working

### ISSUE THREAD

**Issue by HenryMehta** [microsoft/vscode#94671]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by HenryMehta** [comment]
I upgrade VSCode this morning because it kept messaging me about a new version.  Once updating CTRL-C stopped working in the terminal windows.  If I do it twice (ie CTRL-C CTRL-C) it simply tells me that isn't a command.

I can no longer quite a program without killing the terminal window and opening a new one.  A right faff

**Comment by gjsjohnmurray** [comment]
When you press CTRL-C in a terminal window does any message appear on the status line?

**Comment by gjsjohnmurray** [comment]
Also, please use Help\About and copy the details to your clipboard, then paste them here.

**Comment by HenryMehta** [comment]
CTRL-C was pressed.  Waiting for second key of chord...

**Comment by HenryMehta** [comment]
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-96-generic

**Comment by gjsjohnmurray** [comment]
Check your keybindings. It looks like you have a chord entry (a sequence of more than one key-combinations) in which the first one is `Ctrl+C`

**Comment by HenryMehta** [comment]
I don't understand where to do that

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings
