### ISSUE TITLE
Option to expand computed TypeScript types on hover

### ISSUE THREAD

**Issue by MKRhere** [microsoft/vscode#94679]
When working with complex types, I often encounter types like this:

![image](https://user-images.githubusercontent.com/19621208/78776659-d9e61f00-79b5-11ea-865d-f8803c5ca206.png)

It's opaque enough that without understanding all the utils that are used and computing it in the head, it's hard to understand what type is being represented. I'd love to have a way to expand it into the fully resolved type, which in the case of the above example would be:

```TS
{
  a: number;
  b?: boolean | null | undefined;
  c: string;
  d: symbol;
}
```

The impl of actual utils I'm using are inconsequential; it's the same if we'd used `Pick`, `Omit`, or `Partial`. It'd be great to be able to expand computed types. I'm not sure whether the responsibility for this lies in VSCode or TypeScript, so if I should be moving this there, let me know :)

**Comment by MKRhere** [comment]
Update: I found this semi-decent hack that seems to force VSC/TSC to expand the types in some cases:

`type Id<T> = {} & { [P in keyof T]: T[P] };`

Wrapping a complex type with this mapped `Id` seems to work. I'll leave this here for anyone else who has the same problem, but I'd still like a solution without hacks.

**Comment by Eliav2** [comment]
also looked into this.
I've [asked a question in stackoverflow](https://stackoverflow.com/questions/62508909/vs-code-how-to-show-full-typescript-definition-on-mouse-hover?noredirect=1#comment110551926_62508909).
maybe we can get it from somewhere [here](https://github.com/microsoft/vscode/blob/919cf3630c6d1f4931ee340cb923d6f0d806486a/extensions/typescript-language-features/src/features/hover.ts#L40) in the vs code base?

**Comment by MKRhere** [comment]
@Eliav2 I believe adding `"noErrorTruncation": true,` to your `tsconfig.json` has the side effect of expanding `... n more ...` in your case.

The case I've asked about is to resolve complex types (maybe that's also part of your issue, but your question was about the 13 extra properties, so this should help you.

**Comment by Eliav2** [comment]
you are right. but this is still a workaround to this feature request.
thanks! that helped me a lot!

**Comment by lydell** [comment]
This works pretty well for me: https://stackoverflow.com/a/57683652/2010616

```ts
type Expand<T> = T extends infer O ? { [K in keyof O]: O[K] } : never;
``

**Comment by MKRhere** [comment]
@lydell I think this works similarly to the solution I'd posted above. It's a great hack; I'm not really sure of edge cases--and this feature should still ideally be added to VSCode itself given how useful it is.

**Comment by shian15810** [comment]
I have published a npm package for this: https://www.npmjs.com/package/type-expand

**Comment by glenjamin** [comment]
It might be nice to gate this behind a modifier key, so we can toggle between expanded and unexpanded while the tooltip is up.

**Comment by adi518** [comment]
This is incredibly painful. There's an [extension](https://marketplace.visualstudio.com/items?itemName=kimuson.ts-type-expand) that does exactly this, but it's half-arsed and stalls the editor.

**Comment by tehpsalmist** [comment]
https://stackoverflow.com/a/69223288/7872063 Current best hack-y workaround

**Comment by n8sabes** [comment]
Using `as const` with different failure return types, it would be high value to enable deeper insight beyond 160 characters. The hack-y workaround above does work but requires application with every update, or script to re-apply it.

**PLEASE PROVIDE THIS OR ALTERNATE METHOD OF VIEWING ALL RETURN VALUES.**

**Comment by n8sabes** [comment]
<h2>How to patch (on a Mac)</h2>

1. Open this file in VSCode : 
`/Applications/Visual\
Studio\ Code\.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js`

2. Search on: `defaultMaximumTruncationLength =`

3. Replace the value (160) with 800.

( Adapted from [StackOverflow](https://stackoverflow.com/questions/62508909/how-can-i-make-vs-code-show-full-typescript-type-definitions-on-mouse-hover/69223288#69223288). Special thanks to [Jeremy Caney](https://stackoverflow.com/users/3025856/jeremy-caney) and [LoveriusB](https://stackoverflow.com/users/16689682/loveriusb) )

**Comment by doberkofler** [comment]
@n8sabes Thank you for the details. Should this not be made the default in vscode or at least be configurable?

**Comment by n8sabes** [comment]
Hi @doberkofler, The **CORRECT FIX** is a true VSCode Setting from the team.

This hack is the best option I’ve found, but if you or anybody else knows of a better solution please post it.

I run VSCode Insiders, which updates frequently, so I wrote and shared the above auto-patch shell script.

_If the code changes in future builds, the regex in this hack will need to be updated._

**Comment by leite08** [comment]
Tried the workarounds below but no luck:
- edit `tsserver.js`'s `defaultMaximumTruncationLength` to 800+;
- add `"noErrorTruncation": true` to `tsconfig.json`.

The only one that "worked" is the `Expand/ExpandAll` type @lydell shared. I put it under quotes b/c changing our types to include it is not really a solution we're willing to adopt, so we keep it around as a `dev` env only tool to help debug complex types.

Would definitely be useful to have this as a VSCode, as a first-class-citizen config.

**Comment by MKRhere** [comment]
@leite08 truncation length is a fix to a different, but similar problem: when there are too many members in an object, and you get `{ ...18 more properties }`, that setting forces TS to expand the list.

Meanwhile, this issue and the solution that worked for you are related to complex types not being resolved by TS/VSCode so we can see what it actually means.

This has been in the backlog for quite a while (it is now in the bottom 20% of issues by age), would be great if team took it up, but understandably [the backlog is pretty long...](https://github.com/microsoft/vscode/milestone/8)

**Comment by vzakharov** [comment]
> This is incredibly painful. There's an [extension](https://marketplace.visualstudio.com/items?itemName=kimuson.ts-type-expand) that does exactly this, but it's half-arsed and stalls the editor.

This one didn’t work for me (nothing shows up in the types panel), but that one seems to be doing fine: https://marketplace.visualstudio.com/items?itemName=mxsdev.typescript-explorer

Example screenshot:

<img width="956" alt="Screenshot 2023-10-18 at 17 33 22" src="https://github.com/microsoft/vscode/assets/188197/c076bb30-d4e1-424e-a27b-f3109c3bcb73">

(I’m not affiliated in any way with the extension developer.)

**Comment by stefaanMLB** [comment]
I need exactly the opposite
```ts
async createPassword(login: string): Task<Doctor> {
}
```
becomes this useless lot in the tooltip, hiding the usefull infirmation that is in the jsdoc header

![image](https://github.com/microsoft/vscode/assets/50827063/d04c7569-a971-4c75-a2a5-b8676d8836ce)
It would be nice if the tooltip type were overridden by the `@returns`  jsdoc type indicator

**Comment by mjbvz** [comment]
Tracked upstream in https://github.com/microsoft/TypeScript/issues/59029
