### ISSUE TITLE
Destructive code action sorting

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#94684]
* declare a new class, make it implement an interface
* trigger code actions with the goal "implement interface"
* trust that this code action is on top, as usual
* 😠 code is gone

<img width="704" alt="Screenshot 2020-04-07 at 09 27 25" src="https://user-images.githubusercontent.com/1794099/78785818-13b02900-79a8-11ea-8c2c-21a054baa6fb.png">

**Comment by gjsjohnmurray** [comment]
Also #94212

**Comment by mjbvz** [comment]
Duplicate of #94212
