### ISSUE TITLE
Showing conda error in terminal

### ISSUE THREAD

**Issue by Vatsal-Malaviya** [microsoft/vscode#94680]
- VSCode Version:1.43.2
- OS Version: Windows 10 Home

Steps to Reproduce:
1.Install pylint
2.Run Python file with conda environment as Python: Select Interpreter

Path was automatically registered by choosing the environment name
![image](https://user-images.githubusercontent.com/31595943/78778997-d359a680-79b9-11ea-8967-fd75619e3053.png)
Terminal Output:
![image](https://user-images.githubusercontent.com/31595943/78779263-47944a00-79ba-11ea-9cff-3327360b94e6.png)

Although correct output is printed still an conda error message prequels the real output.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Vatsal-Malaviya** [comment]
error msg :
 conda activate gpuenv
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ conda activate gpuenv
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by RMacfarlane** [comment]
Does this happen in new terminals as well? It seems like the path wasn't updated to include "conda"

**Comment by Vatsal-Malaviya** [comment]
> Does this happen in new terminals as well? It seems like the path wasn't updated to include "conda"

Sorry if I am interpreting this wrong way, but by new terminal you mean the one on which python file automatically runs right? what do you mean by the path wasn't updated to include "conda" can you explain the process so that I may know if am missing something.
I have installed anaconda extension and in conda path in user setting, I have added path of python.exe present C:\Users\Vatsal\AppData\Local\Continuum\anaconda3\python.exe
![image](https://user-images.githubusercontent.com/31595943/78871317-263c6800-7a65-11ea-8314-3800ef0cd64b.png)
while keeping
![image](https://user-images.githubusercontent.com/31595943/78871395-41a77300-7a65-11ea-9cfb-b5ccdcd86ade.png)

**Comment by RMacfarlane** [comment]
Please reopen this on the python extension
