### ISSUE TITLE
Feature request: Multiple output panels

### ISSUE THREAD

**Issue by AndrewMorsillo** [microsoft/vscode#94681]
Looking at my editor right now there are 23 different items in the dropdown on the output tab. Only ~2-3 of those are actually relevant for my current work. It would be great if I could split those 2 or 3 important output streams into their own panels/tabs. 

Right now it's tedious if there's more than 1 important output stream at once -- I have to go to output, open the dropdown, locate the option I want out of 23, then click to switch any time I need to look at the other output stream. Depending on the task at hand this can happen quite frequently. It would be so much more useful to be able to split out those couple important output streams to top level tabs.

**Comment by MariusVB** [comment]
Critical feature to several workflows. When using the Arduino extension, it would be extremely helpful to have "Arduino" and "Serial Monitor" output side-by-side. Please prioritize this feature.

**Comment by Noah-Schoonover** [comment]
This is a crucial feature. Please.

**Comment by cr3ative** [comment]
Sadly, +1. When there are multiple important things happening across different "Output" windows, side-by-side is crucial. Switching between them constantly is silly.

**Comment by colinjcahill** [comment]
But what if we say _**please**_ really hard?

**Comment by dustinkeeton** [comment]
I will also say "please."

**Comment by mmcintyre123** [comment]
Please

**Comment by BMCDad** [comment]
I am also trying to use VSCode for Arduino programming and finding the limitations of the output panel a source of frustration.  For all of the flexibility built into the VSCode UI, this limitation is puzzling.

**Comment by strg-v** [comment]
+1

**Comment by Red007Master** [comment]
+1

**Comment by srikengames** [comment]
pretty please

**Comment by rev1204** [comment]
+1 please

**Comment by kasidev** [comment]
+1 Please. Also using it for arduino programming. It would be very usefull to have the Arduino output and the Serial Monitor side by side

**Comment by bartekpacia** [comment]
Why is this closed? We need this.

**Comment by snowfox-design** [comment]
Pretty please!

**Comment by ELLIOTTCABLE** [comment]
The VScode team prioritizes issues by vote-count on the OP. Please stop posting responses along the lines of `+1` or `Pretty please`, as this will not assist in getting this feature re-opened — but it *does* notify every. single. person. watching this Issue.

However, clicking the 👍 button on the original post *will*, so go ahead and do that, thanks!

**Comment by stereokai** [comment]
+1 on this feature. It could help a lot with debugging extensions

**Comment by lcarreras** [comment]
I would be very helpful, please

**Comment by stereokai** [comment]
@ELLIOTTCABLE you gave me a thumb down - do you disagree that multiple output panels could help with debugging extensions?

**Comment by lcarreras** [comment]
> @ELLIOTTCABLE you gave me a thumb down - do you disagree that multiple output panels could help with debugging extensions?

I think that he means posting "+1" will not be useful. Instead, give a "thumbs up" to the first comment: this (he thinks) will be most effective ;)

**Comment by stereokai** [comment]
@lcarreras clearly, but I actually provided a valid reason which hasn't been brought up in the thread so far, as opposed to the others which really are nothing but "+1", yet my response is the only one with a thumbs down

**Comment by WillsterJohnson** [comment]
over 4 years with nothing but support, yet it's closed.

@isidorn how exactly is this out of scope?
We already have the largely useless 'open in editor' option for output channels, why can't we organise and move them around the window in the same way we can with terminals?
