### ISSUE TITLE
Search exclude settings and ignore file are enabled, but it claims they're disabled

### ISSUE THREAD

**Issue by ncphillips** [microsoft/vscode#94689]
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Steps to Reproduce:

1. clone [tinacms](https://github.com/tinacms/tinacms/) repository
2. open repo in vscode
3. run `npm i`
4. CMD+SHIFT+F to full-text search the string: `useModal`  
    It keeps digging through all the `node_modules` and other ignored files.
    It says "Exclude settings and ignore files are disabled" but I confirmed that both the workspace and user settings have those things enabled.
    <img width="542" alt="image" src="https://user-images.githubusercontent.com/824015/78798336-3d108b00-798f-11ea-9987-7525c0b48424.png">
  

Does this issue occur when all extensions are disabled?: Yes/No

* Yes

**Comment by IllusionMH** [comment]
Looks like you have "Use Exclude Settings and Ignore Files" disabled (toggle in "files to exclude field").
![image](https://user-images.githubusercontent.com/1312662/78804312-a95bb080-79c8-11ea-95cf-d62adebc84af.png)

You need to make sure that it is enabled (has blue background).

**Comment by ncphillips** [comment]
AH! Thank you.

That is incredibly subtle. Nothing about that icon makes me think that's what it's for. 

At the very least it would be good for it to be possible to toggle this from the settings as well.

**Comment by IllusionMH** [comment]
As I see it - it should be quick toggle on/off so Settings might not be the best place (especially if still controlled by button in search as it is now).

However design proposed in https://github.com/microsoft/vscode/issues/65317#issuecomment-540821280 will make it more noticeable.
