### ISSUE TITLE
Revert to state on disk when undoing to the saved state and changes occured

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94685]
If a file gets updated while you're editing it, and you cancel that edit, the file will be stale and there is no indication it is.

setup `test.js`,
```js
   ;(async () => {
	const fs = require('fs').promises
	let v = 0
	try {
	    v = await fs.readFile('./hello.txt')
	} catch (e) {}
	fs.writeFile('./hello.txt', ++v)
   })()
```
run script `node test.js`, 
open newly created file `./hello.txt`, its content is `1`
type something in the file, like `x`

run script again, the content is `2`
you're still seeing `x` as you're editing it

cancel your edit `CTRL+Z`
you are now seeing `1`
reopen or run script again to see actual file content

1.43.2

**Comment by bpasero** [comment]
@pushkine can you clarify what you expect? do you expect that when you undo enough so that the file get's into saved state it loads the contents from disk if they changed?

**Comment by pushkine** [comment]
> @pushkine can you clarify what you expect? do you expect that when you undo enough so that the file get's into saved state it loads the contents from disk if they changed?

The solution in my opinion would be to insert the new state in the undo/redo history, because that's already how it works when the file updates, the previous state is pushed into the undo history. So if I undo to get to `previous` and `current` changes to next in the meantime, I'd expect

**Comment by pushkine** [comment]
_the editor displays stale content as new_
How is that a feature request ?
smh
