### ISSUE TITLE
Add CP852 support

### ISSUE THREAD

**Issue by ZaphyrVonGenevese** [Microsoft/vscode#9468]
I have to work with old programs written in CP852, but at this moment I can't with VSCode.

Are you interested in implementing that? If it is suitable for new contributors, I can make it. Just let me know.

**Comment by egamma** [comment]
@ZaphyrVonGenevese VS Code is using the iconv-lite module for its encodings https://github.com/ashtuchkin/iconv-lite/blob/master/README.md. This module doesn't support the CP852 encoding. 

To get support for CP852 you should consider contributing to this module, then VS Code can get the support from there.

**Comment by ZaphyrVonGenevese** [comment]
@egamma On the wiki page of supported encodings they state it is supported, then.
https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

It is under Single-byte > IBM > 852

**Comment by egamma** [comment]
@ZaphyrVonGenevese then I have to defer to @bpasero on why it isn't shown in the quick box

**Comment by bpasero** [comment]
Verifier: you should see the encoding in the encoding list and save/open it using that encoding.
