### ISSUE TITLE
Implement folding of brace-less arrow functions

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94694]
![Code_2020-04-08_17-24-16](https://user-images.githubusercontent.com/30108880/78802175-cdfe5b00-79bd-11ea-9cf8-24dcb2eef036.png)

duplicate of https://github.com/microsoft/TypeScript/issues/26661

this simple request has been pending for almost 2 years now

I really don't like being forced into a specific syntax to use basic text editor features

**Comment by RMacfarlane** [comment]
@pushkine Please comment on the original issue instead of creating a new one, thank you!
