### ISSUE TITLE
Refactoring does not use default formatter

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94691]
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
```json
"[javascript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
```
```js
const getMethod = (property) =>
	property instanceof BindingProperty
		? property instanceof QueryBinding
			? 'query'
			: property instanceof DocumentBinding
			? 'document_binding'
			: 'collection_binding'
		: 'property'
```
select all > right click > refactor > extract to function in module scope
the resulting function follows `Typescript and Javascript Language Features` formatting instead of the default
1.43.2

**Comment by mjbvz** [comment]
In your example, refactor and format are coming from two different extensions. Making the typescript refactor actions understand prettier style is out of scope

After refactor we could run format on the document automatically but this would result in odd flashes where the code shifts style after the refactoring is applied. Better to leave running format up to the user in my opinion

**Comment by pushkine** [comment]
Oh okay, I thought this could be fixed by calling `Format selection` before returning the generated code
