### ISSUE TITLE
Allow late port forwarding in Remote SSH

### ISSUE THREAD

**Issue by tcalmant** [microsoft/vscode#94692]
Hi,
Would it be possible to forward ports after starting the remote VS code server over SSH, like in Remote Containers?

Currently I open a tunnel with a new SSH connection from the host, but it would be nice to have that feature directly inside VS Code.

**Comment by roblourens** [comment]
You can, in the Remote Explorer viewlet, same as with Containers. Can you explain what issue you are having?

**Comment by tcalmant** [comment]
Hi,
OK, my bad, I haven't seen it in the Remote Explorer.

In fact, I look for all commands through the "Show All Commands" shortcut, using the English name of the command (here "forward port"), as it allows to find the command even when VS Code is in another language (here, French).
The issue seems to be that for the Remote SSH extension, the English name of the command is not available/searchable: I only see the translated version (which I have to know first to know what to find).
Also, those commands are not prefixed by "Remote-SSH:" like the others, which made me think they weren't available.

Sorry for the wrong issue then.

**Comment by roblourens** [comment]
Oh yeah, that's it. It won't be prefixed with Remote-SSH because it comes from vscode itself but we can make the English name show up too.

**Comment by roblourens** [comment]
FYI @alexr00 you can register those actions for the command palette with `ILocalizedString` if you want, I think that's how that works.

**Comment by tcalmant** [comment]
Thanks!
