### ISSUE TITLE
View DND: dropping into existing container is not discoverable for me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94695]
I could not easily discover the support for taking a view container and dropping it into another container:

![Kapture 2020-04-08 at 18 04 06](https://user-images.githubusercontent.com/900690/78806710-5a5f4c80-79c3-11ea-8ab1-dfec4722fb67.gif)

The 2 white bars look weird, I think:
* I would not expect the horizontal white bar in this case because my intent is to drop into the container
* I would expect the activity icon I am dragging over to show full drop feedback (I think as it used to be) to indicate that I am dropping into that container

//cc @sandy081

**Comment by sbatten** [comment]
I agree that this should be improved. Some comments:

1) Hovering over the center of an icon and having the sidebar switch to that viewlet does not change the drop behavior. It will still insert if you drop over the activity bar. This could change but currently the feedback indicates the actual behavior. 
2) I also like the idea of using the old bg hover effect to indicate that you can switch viewlets during hover. One idea might be that while you are hovering a specific icon, we fade in the bg color peaking at the point that the viewlet switches (potentially with a flash+reset at the end)

**Comment by sbatten** [comment]
Another idea based on sitdown discussion from today and details from @kieferrm:
1. Have the insert behavior only work at the edges of the icon.
2. In the middle of the icon, we use highlight bg to indicate this will go inside the view container.

We will probably want some delay or fade in on bg so re-arranging icons in the activity bar isn't noisy. 

We never had drop inside view containers before so this is a new interaction for our users. The current design was made in a way that used only drop interactions that we had before. So it may be weird if a user tries to move the explorer icon down and now has to avoid the center of an icon.
