### ISSUE TITLE
Can't make text smaller

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#947]
The text in Visual Studio Code is too large, and I want to make it smaller. However, the editor won't let me reduce the text beyond a certain size. I should be able to make the text smaller.

<img width="298" alt="screen shot 2015-12-02 at 4 27 22 pm" src="https://cloud.githubusercontent.com/assets/466713/11548467/96f58110-9911-11e5-95e9-2d797b613728.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by alexandrudima** [comment]
@pcgeek86 Are you referring to `editor.fontSize` setting or to the `View > Zoom out` action ?

**Comment by pcgeek86** [comment]
I'm just hitting `COMMAND + -` on my keyboard. The screenshot shows the smallest it will get.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by alexandrudima** [comment]
@bpasero Looks like this is the global zoom. I remember you mentioned you added a config setting to go below 100%

**Comment by bpasero** [comment]
Yes, the december release will have a new setting ´window.zoomLevel´
