### ISSUE TITLE
Colour clashing in editor

### ISSUE THREAD

**Issue by McAwesome123** [microsoft/vscode#94704]
Issue Type: <b>Bug</b>

Themes such as Tomorrow Night Blue and Red have a colour clash between sections with and without text or highlighting. Some other themes have this too, but it isn't as noticeable.
![image](https://user-images.githubusercontent.com/49949995/78811331-5be44100-79d2-11ea-99af-60ea1bb56ad2.png)
![image](https://user-images.githubusercontent.com/49949995/78811396-7f0ef080-79d2-11ea-828e-57bd499bf080.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
Same as #84690, #92209, #93977

**Comment by deepak1556** [comment]
Do you observe any changes after making following change

```
* Command Palette search for "Configure Runtime Arguments"
* Set "disable-color-correct-rendering":  false
* Restart
```
