### ISSUE TITLE
Codelens-type interface for jsdoc functions

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#94706]
I would like comments that vscode assumes to be documentation for a function to be collapsed next to its CodeLens references, such as to get something like
`12 references | documents 3 parameters and 1 return` 
where clicking on it reveals the comment, and collapsing it gets it back to its initial state.

Some (most?) people use jsdoc much more to provide metadata for their editor rather than to document things, for those people it only makes sense to hide it by default

Collapsing descriptions, `@param` and `@returns` for functions would already be a big step forward in my opinion, but I'd also eventually like to see the collapsing of `@type` one liners and the transformation of `@template` and `@typedef` into something more readable in the future.

VScode already does 3/4 of the type definition work by itself, slipping a `@type` to the missing ones shouldn't be a trade on readability

**Comment by mjbvz** [comment]
This sounds like a good extension candidate. If such an extension proves popular, we could look into moving it into code
