### ISSUE TITLE
Stop .code-workspace file from auto-updating with settings from my User file

### ISSUE THREAD

**Issue by enicol** [microsoft/vscode#94703]
Issue Type: <b>Bug</b>

After making unrelated changes to my User settings.json the *.code-workspace file in my monorepo imported the folllowing: 

``` JSON
    "workbench.colorCustomizations": {
      "activityBarBadge.background": "#eebbc3",
      "badge.background": "#ffa8ba",
      "extensionButton.prominentBackground": "#eebbc3",
      "statusBarItem.hoverBackground": "#5d8066"
    }
```

Every time I go to discard these changes, they auto-generate again moments later. The monorepo I'm working in is shared with my coworkers so I can't gitignore the file but I also can't begin to reason why this has started in the first place. 

I've searched issues and stackoverflow for similar behaviour but haven't come across anything that would explain why this is happening

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 6|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.0.0
project-manager|ale|10.11.0
cucumberautocomplete|ale|2.14.1
vscode-color|ans|0.4.5
vscode-apollo|apo|1.15.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-styled-jsx|bla|1.5.0
simple-react-snippets|bur|1.2.2
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.20.5
bracket-pair-colorizer-2|Coe|0.0.29
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.2
vscode-dash|dee|2.3.0
githistory|don|0.6.3
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.1.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
vscode-pull-request-github|Git|0.15.0
helium-icon-theme|hel|1.0.0
rest-client|hum|0.23.2
format-python-docstrings|ian|1.2.1
output-colorizer|IBM|0.1.2
docthis|joe|0.7.1
vscode-styled-sort|joh|0.0.7
vscode-styled-components|jpo|0.0.29
graphql-for-vscode|kum|1.15.3
git-indicators|lam|2.1.2
MagicPython|mag|1.1.0
web-accessibility|Max|0.2.82
dotenv|mik|1.0.1
language-gettext|mro|0.1.1
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
atom-keybindings|ms-|3.0.6
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
angular-console|nrw|11.1.3
color-tabs-vscode-ext|ore|0.10.0
material-icon-theme|PKi|4.0.1
vscode-react-refactor|pla|1.0.5
polacode|pnp|0.3.4
prisma|Pri|0.0.31
vscode-seedling-icon-theme|ras|0.5.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.1
sass-indented|rob|1.5.1
partial-diff|ryu|1.4.1
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
html5-boilerplate|sid|1.0.3
fish-vscode|sky|0.2.1
code-spell-checker|str|1.8.0
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.7.0

(22 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Can you reproduce this when running with all extensions disabled?

**Comment by enicol** [comment]
Is there a way to do that through the settings or does that need to be done manually?

**Comment by gjsjohnmurray** [comment]
One way is with the command `Developer: Reload With Extensions Disabled`

Another is to add the `--disable-extensions` argument to the commandline when you launch VS Code.

**Comment by enicol** [comment]
Just did it and realized ColorTabs extension was the culprit! Thanks so much for your help with this

**Comment by gjsjohnmurray** [comment]
You're welcome

/causedByExtension
