### ISSUE TITLE
Command + scroll change font sizes too fast on macOS

### ISSUE THREAD

**Issue by louis925** [microsoft/vscode#94709]
It is great that on macOS, Command + two fingers scroll can change the font size. However, it is way too sensitive on macOS touchpad. Lots of time I accidentally touch two fingers while trying to press Command, it immediately shrink the font size of the editor to very small. And, it is even harder to recover to the original font size quickly, because mac has weird momentum on the touchpad. 
Please consider reduce the sensitive or turn off scroll momentum when changing font size using Cmd + two finger scrolling on macOS! 
Thanks!

**Comment by RMacfarlane** [comment]
@louis925 On my mac, I can enable cmd + two finger scroll to zoom in and out, but it changes the zoom level of the entire screen instead of just changing the font size. Is this the feature you're talking about, or something else?

**Comment by louis925** [comment]
@RMacfarlane I think I have `editor.mouseWheelZoom` setting enabled. This only change the font in the editor. (If I disable this setting, cmd + two finger scroll do nothing on my VS Code)
