### ISSUE TITLE
TESTING WENT WRONG AFTER UPDATING, I AM STUDENT LEARNING NODE JS AND MONGODB

### ISSUE THREAD

**Issue by Tukei-david** [microsoft/vscode#94719]
Issue Type: <b>Bug</b>

Hey Dealers,

I am learning Node js and i am using visual editor as my tool. Today like 2 hrs from now i updated my visual editor while still following some tutorials of testing my task manager app codes but it returned an error that the server is timed out and the time given was 30000 ms. Does the new version as a bug or what? I can't even connect to my mongoDB compass database becouse it returns the same error and the internet is stable. Pleasehelp me, i will really appreciate me.

Stay home, Stay safe
David Tukei

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.6
vscode-icons|vsc|10.0.0

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Hi @Tukei-david, I'm not sure if this is a problem with VSCode or with something else. Can you share the code that is timing out and how you are running it? Can you also try going back to the old version and see if that fixes the problem? You can download it here: https://code.visualstudio.com/updates/v1_43

**Comment by Tukei-david** [comment]
Hey @RMacfarlane , i fixed the issue i didn't intitalize my mongodb database
Thank you

**Comment by RMacfarlane** [comment]
Great, glad to hear you got it working!
