### ISSUE TITLE
Git: Add

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/vscode#94713]
goal: add files with git

git smart commit allows you to select tracked, which is awesome, but then it appears there is no option to add an untracked file.

Option 1 : would be nice to add another 2 options to smart commit, "ask" and "tracked + ask". What ask would do when saving a file is it would pop up and say "would you like to stage this file" to which you could say yes or no. tracked+ask  would only do this for a new file. (note: tracked + ask is probably the only sane option)

Option 2: when git is detected, and you're in the file browser context menu git add should be present, also a keyboard shortcut should be added to allow you to add the current file.

Option 3: commit+choose files keyboard shortcut. This would pop up a dialog, in addition to the message you could checkbox which changed files to actually commit.

Honestly I think implementing all 3 of the options is the way to go. Worth saying that these are all feature of any Intellij IDE

**Comment by xenoterracide** [comment]
related, but not a duplicate, as what if I create a file outside of vscode.

**Comment by joaomoreno** [comment]
> goal: add files with git

I really don't understand this.

What do you want to do exactly? Give me a specific example.
