### ISSUE TITLE
The tab icon on the diff viewer does not change when switching between files of the same language.

### ISSUE THREAD

**Issue by teo-tsirpanis** [microsoft/vscode#94715]
Issue Type: <b>Bug</b>

1. In a git repo, change two files with a different icon in the Files view, _but of the same language_, like an `.xml` file and a `.csproj` file, with an extension like `vscode-icons`.
2. Go to the Source Control panel and select one of the files of step 1. Notice the tab icon in the diff viewer.
3. Now, select the other one.
4. The tab icon on the diff viewer does not change!

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aeschli** [comment]
I can reproduce. Likely a updating issue in the ResourceLabel
