### ISSUE TITLE
Does not automatically detect the language based on file name extensions

### ISSUE THREAD

**Issue by AnuragAmbuj** [Microsoft/vscode#9471]
- VSCode Version: 1.3.1
- OS Version: Windows Pro 10.0.10240

Steps to Reproduce:

1.  Open any file ( like somefile.java ) using VS Code by right clicking on that  file
2.  Using cmd
Create a new file using command
```
X:\> code somefile.java
```

**Comment by lextm** [comment]
I could not reproduce it on both Windows and OS X. In all cases .java files are identified as Java source file. Do you have any special extensions installed?

**Comment by AnuragAmbuj** [comment]
I have Java Debug (by DSnake), Java Language Support (by George Fraser) and Java Import Snippets (by Taiwo Kareem) installed.

**Comment by AnuragAmbuj** [comment]
Issue remains even after uninstalling those extensions.

**Comment by kieferrm** [comment]
Can't reproduce in stable 1.3.1 or insiders 1.4.0 on MacOS or Windows.

Out of the box (i.e. without any extensions installed) we consider files with the extensions `".java", ".jav"` as Java files and syntax highlight them appropriately.

You can use the `--disable-extensions` command line option to ensure no extension is loaded.
