### ISSUE TITLE
Open new terminal not fully working in web

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#94714]
- VSCode Version: 1.43.2
- OS Version: Debian GNU/Linux 9

Steps to Reproduce:

1. Go to online.visualstudio.com
2. Create an environment and connect to it
3. As soon as it loads, try opening a new terminal

Does this issue occur when all extensions are disabled?: Yes/No

The following is the output I see in the console

![image](https://user-images.githubusercontent.com/48293249/78827783-887b6700-7998-11ea-92f3-b5b7beec707c.png)

**Comment by Tyriar** [comment]
I'm confused, the red error is talking about the fit xterm.js addon which VS Code doesn't use? 😕 What is app.js?

The not implemented error throws in the web worker ext host by design.

**Comment by osortega** [comment]
@Tyriar the red error should be irrelevant to this. It was something I was testing independently, inside a VS Code webview.

The other errors are the ones I thought would be relevant for this issue. The problem is that sometimes VS Code seems to render wrongly the terminal.

This is how it looks like when it repros.

<img width="1097" alt="ghissue" src="https://user-images.githubusercontent.com/48293249/78839272-00538c80-79ad-11ea-9fca-964c89a08e2d.png">

It shows up as an empty terminal without the first line I would expect

**Comment by osortega** [comment]
This happens when resizing the terminal

![terminal](https://user-images.githubusercontent.com/48293249/78840207-08143080-79af-11ea-9b4d-4547b2a4850d.gif)

Seems to be some sort of rendering issue

**Comment by jkeech** [comment]
@Tyriar, I get this consistently on the first launch of a terminal in VSO, 100% of the time. Looking in the console, this error is reported when I first open the terminal with `Ctrl + Shift + C`:

```
ERR [object Event]: Error: [object Event]
    at Object.t [as ensureError] (https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:7:522)
    at s._createLoadError (https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:27:162)
    at s._onLoadError (https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:27:281)
    at i (https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:28:969)
    at Object.errorback (https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:29:313)
    at e.triggerErrorback (https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:13:955)
    at https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:13:659
    at HTMLScriptElement.i (https://online.visualstudio.com/static/web-standalone/d8e3cca/out/vs/loader.js:14:176)
```

![terminal-error](https://user-images.githubusercontent.com/746020/78843997-4e6e8d00-79b9-11ea-8a52-c6e5dfed0cac.gif)

**Comment by Tyriar** [comment]
I tried to reproduce but cannot. I see that error though. Why does mine say this not VS Online?

![image](https://user-images.githubusercontent.com/2193314/78895803-50216a80-7a24-11ea-88c8-5051d70f8f91.png)

Change since the gif was made?

**Comment by jkeech** [comment]
@Tyriar, I was using insiders, but it also reproduces in stable (added another gif).

![terminal-error-stable](https://user-images.githubusercontent.com/746020/78926997-ec626600-7a52-11ea-97f6-1fa264d3a5aa.gif)

If it helps, the browser is Microsoft Edge Version 83.0.467.0 (Official build) dev (64-bit), on Win10, but I'm also able to reproduce in Chrome Version 80.0.3987.163 (Official Build) (64-bit).

One thing I have noticed is that it only seems to happen if the bash terminal that is being opened is not the first terminal:

![image](https://user-images.githubusercontent.com/746020/78927579-fb95e380-7a53-11ea-8b2c-47c98c73109f.png)

**Comment by Tyriar** [comment]
Ok I can reproduce now, steps:

1. Connect to environment
2. Close terminal if it's open and reload
3. Wait a long time such that the VS Online terminal is created
4. ctrl+shift+`

**Comment by Tyriar** [comment]
It appears the terminal isn't getting the `active` class which means the terminal is `display: none`

```
.monaco-workbench .pane-body.integrated-terminal .terminal-wrapper.active {
    display: block;
    position: absolute;
    bottom: 2px;
    top: 0;
}
```

**Comment by Tyriar** [comment]
Local repro:

1. Run the terminal extension sample https://github.com/microsoft/vscode-extension-samples/tree/master/terminal-sample
2. Run the command "Terminal API: Create Terminal"
3. ctrl+shift+`
