### ISSUE TITLE
Go to File causes error "spawn ENAMETOOLONG"

### ISSUE THREAD

**Issue by doucette** [microsoft/vscode#94718]
Issue Type: <b>Bug</b>

1. Open a workspace for Unreal Engine 4.25.
2. Attempt to use "Go to File..." to open a file. I used NameTypes.h.
3. Observe the error "spawn ENAMETOOLONG" displayed in a floating notification in the lower right corner.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3970X 32-Core Processor  (64 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.87GB (106.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.14.5
remote-wsl|ms-|0.42.4

</details>

**Comment by doucette** [comment]
I retried on 1.44.0 and no longer see the "spawn ENAMETOOLONG" error, but still have no files listed in the box that comes up except for files that I've previously opened by browsing to them. The explorer tree shows the expected files. This did not happen with Unreal Engine 4.24, where the Go to File functionality worked as expected. I don't know what has changed between those versions that would impact this issue, otherwise I would try to fix it.

**Comment by bpasero** [comment]
Spawn seems like RipGrep to me.

**Comment by roblourens** [comment]
I have seen this before when there are tons of exclude patterns or you are searching in a long folder name, etc.

Can you do this:

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

This should include the exact command that we run to do the search which should show us why it is too long.

**Comment by roblourens** [comment]
> That leads to the excludePattern for the search being 42,720 characters in the log

Yikes, I guess that is the issue. I could probably handle this error better but it hasn't come up since I made some changes to compress the command. I am kind of confused about the project configuration that required someone to type out 651 exclude patterns though. If it was mine I would reorganize it, but I get it... 😁 

How about this - search will ignore patterns in a `.ignore` folder in the root of your workspace. You should be able to drop those patterns into a `.ignore` file, same syntax as `.gitignore`, and they will be respected without hitting this error. Let me know if that helps.

**Comment by doucette** [comment]
Thankfully, nobody had to type out 651 exclude patterns. Unreal Engine 4 generates its projects from C# configuration files. It automatically adds an exclude pattern for every module/plugin that is included in the project, and that list can get rather long for large projects. I think a `.ignore` file would meet our needs, and it would be easy to update our project file generator to create it. Thanks!

**Comment by roblourens** [comment]
Cool, let me know if it doesn't work out for you.
