### ISSUE TITLE
vscode.workspace.workspaceFolders is always undefined 

### ISSUE THREAD

**Issue by astoycos** [microsoft/vscode#94710]
- VSCode Version:1.43.0
- OS Version:Fedora 31

Steps to Reproduce:

1.Use the Yeoman Code Extension Generator 
2. make a new project 
3. Open the folder with ` code <folder name>`
4. Try and Print the `console.log(vscode.workspace.workspaceFolders)`, and then hit `F5` to compile and run

```
Congratulations, your extension "edge-developer-tools" is now active!
workspaceFolder:  undefined
```
The Resulting output is always undefined. 

 To check that the workspace var was being correctly set I make a task as follows 

```
{
			"label": "echo",
			"type": "shell",
			"command":
			  "echo workspaceFolder: ${workspaceFolder} \n workspaceRoot: ${workspaceRoot}"
}
```

After running the task It returns the expected output 
`workspaceFolder: /home/astoycos/vs-code-plugin/edge-developer-tools`

So the API is not reading the correct variables from the editor and I cannot access the root directory path in my extension's code

Thanks for the help!  

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by RMacfarlane** [comment]
When you launch the new window to debug the extension by pressing `F5`, have you opened a folder in that window? `vscode.window.workspaceFolders` will return the folders that are currently open in vscode itself. If you're trying to get the path to the extension code, you can use the `extensionPath` on the context the extension activates with: https://github.com/microsoft/vscode/blob/d91ca067cab6a9a52ba07feb50c9c800d0891552/src/vs/vscode.d.ts#L5407-L5410

**Comment by RMacfarlane** [comment]
@astoycos Please let me know if that doesn't solve your problem.

**Comment by astoycos** [comment]
Hey @RMacfarlane,

Thanks for getting back to me sorry for the late reply! So when I press `F5` I have to go and open a folder in the new window in order for the `vscode.workspace.rootPath` to work I understand that.  However when I try to mimic the following functionality (https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/extension.ts#L14) in my extension's code I get an error even before pressing `F5` 

![image](https://user-images.githubusercontent.com/23533892/79124626-baab1100-7d6a-11ea-8ae8-65d384f2958c.png)

So even in the Extension's source code window the variable `vscode.workspace.workspaceFolders` is not set.

**Comment by RMacfarlane** [comment]
@astoycos This is a warning from typescript, since `vscode.workspace.workspaceFolders` could be undefined in the case where no folder is open, its type is:
```
		/**
		 * List of workspace folders or `undefined` when no folder is open.
		 * *Note* that the first entry corresponds to the value of `rootPath`.
		 */
		export const workspaceFolders: ReadonlyArray<WorkspaceFolder> | undefined;
```
Likely you have `--strictNullChecks` enabled in TypeScript, which treats this as an error: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

To fix, you can check that `vscode.workspace.workspaceFolders` is not undefined before getting the first element

**Comment by astoycos** [comment]
Ok, Thanks!
