### ISSUE TITLE
Git: Offer to show the entire git commit output, when it fails

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#94711]
Issue Type: <b>Bug</b>

I'm using git pre-commit hooks via Husky to run the Prettier code formatter on my project. Sometimes I try to commit code that has a syntax error and when that happens the pre-commit hooks fail. If I commit from the terminal I get an informative error message like the following:
```shell
$ git commit -am "test"
husky > pre-commit (node v10.19.0)
Preparing... [started]
Preparing... [completed]
Running tasks... [started]
Running tasks for *.{ts,js,json,html,scss,md} [started]
prettier --write [started]
prettier --write [failed]
→
Running tasks for *.{ts,js,json,html,scss,md} [failed]
→
Running tasks... [failed]
Applying modifications... [started]
Applying modifications... [skipped]
→ Skipped because of errors from tasks.
Reverting to original state... [started]
Reverting to original state... [completed]
Cleaning up... [started]
Cleaning up... [completed]



× prettier found some errors. Please fix them and try committing again.

[error] packages\site\src\app\app.component.ts: SyntaxError: '{' expected. (9:3)
[error]    7 | })
[error]    8 | export class AppComponent
[error] >  9 |   title = "site";
[error]      |   ^
[error]   10 | }
[error]   11 |
husky > pre-commit hook failed (add --no-verify to bypass)
```

However when I commit via VSCode's built-in commands I get a much less informative error dialog which requires me to click "Open Git Log" and scroll back through a page or two of git output to find the detailed error message.
![image](https://user-images.githubusercontent.com/667716/78824730-d8fcbf80-79ac-11ea-869b-f2b8aee94167.png)

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (12.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.11.0
ng-template|Ang|0.901.0
spellright|ban|3.0.50
scratchpads|bue|0.0.7
find-related|eam|0.9.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.1.1
kotlin|fwc|0.2.11
todo-tree|Gru|0.0.171
rest-client|hum|0.23.2
search-node-modules|jas|1.3.0
svg|joc|1.1.7
escape-regexp|kir|1.0.0
vscode-commitizen|Kni|0.8.4
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
vscode-azureappservice|ms-|0.16.4
mssql|ms-|1.9.0
python|ms-|2020.3.71659
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.42.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.9
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1891
debugger-for-chrome|msj|4.12.6
java|red|0.59.1
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
vscode-open|san|0.1.0
reveal|smu|1.2.7
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vim|vsc|1.13.1
material-theme|zhu|3.2.5

</details>

**Comment by joaomoreno** [comment]
There is no format to the git output when this happens. So, we can't really process it and show it in a nice way.

I suggest to add another button to that dialog which opens a temporary read-only file with the entire contents of the result of `git commit`.

**Comment by diminutivesloop** [comment]
@joaomoreno I have a basic working version of the solution you described except I’m not sure how to open a file in read-only mode. Any pointers?

**Comment by joaomoreno** [comment]
You could generate a unique ID for that commit and create a URI which the [FSProvider](https://github.com/microsoft/vscode/blob/7456cf89275eafed422e82a9be72896df56033bf/extensions/git/src/fileSystemProvider.ts#L36-L36) would provide contents for.

**Comment by iliazeus** [comment]
@joaomoreno, wouldn't a [TextDocumentContentProvider](https://code.visualstudio.com/api/references/vscode-api#TextDocumentContentProvider) be a better fit here? It is easier to implement.

**Comment by diminutivesloop** [comment]
@joaomoreno I gave it a shot with `TextDocumentContentProvider` as @iliazeus recommended. Let me know what you think
