### ISSUE TITLE
Editor stays blurred when moving panels

### ISSUE THREAD

**Issue by nexes** [microsoft/vscode#94724]
Issue Type: <b>Bug</b>

When moving the different panels around, Problems, Terminal etc, the editor will have a blurred effect. This effect doesn't go away if I move a panel but put it back in the same place. Here is a GIF of the problem.

[blur problem](https://imgur.com/o1GX9Nc)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.56GB (17.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0
advanced-new-file|pat|1.2.0
rust|rus|0.7.0
find-then-jump|tra|1.0.4
vscode-icons|vsc|10.0.0
vim|vsc|1.13.1

(1 theme extensions excluded)

</details>

**Comment by miXwui** [comment]
I had this issue as well, seems like the "Multiple views in a single panel" feature doesn't work if the 3-dot-menu is shown, like below:
![image](https://user-images.githubusercontent.com/4538842/78838153-2d0ea080-79bb-11ea-80d1-1bed7222e932.png)

If the 3-dot-menu is shown, it will glitch and the editor will have that "blurred effect". To remedy this for now, I either:
1. Zoom out (Ctrl + - on Windows, probably CMD + -  on Mac)
2. Resize the window  

until the 3-dot-menu disappears, and then the feature should work.

**Comment by sbatten** [comment]
Thanks for reporting @nexes and the explanation @miXwui 

With the repro I discover that this happens when the number of panel tabs shrinks during the drag operation which seems to happen frequently when dragging Problems and Terminal.
