### ISSUE TITLE
An ability to easily import file or function from another file!

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode#94729]
Often you need to add stuff from files that are not exactly siblings to each other. It'd be really useful If I could do this:

1. Right click in a source file.
2. Click "Select for import".
3. Go to target file and Right click in there
4. Click "Import selected file"
5. import statement gets added at the top but under all other imports with something like `import  ___  from './d/a/c/d/File;`

Simple and non-disruptive.

Then you could go one step ahead, and simply select a function that is being exported and right click the export statement and do the same thing.

Thanks.

**Comment by techsin** [comment]
Not a duplicate. Closest one I found was drag and drop. I believe not only this approach is simpler but more useful.

**Comment by techsin** [comment]
This is fundamentally useful feature. Not something I'd like to have. The impact is deep and meaningful.

**Comment by mjbvz** [comment]
Sounds like a good fit for an extension! Take look at our extension authoring docs to get started

**Comment by techsin** [comment]
please reconsider this is needed on daily basis on large code base. autocomplete is useless if you multiple files or functions with same names as is the case in big projects.
