### ISSUE TITLE
'${workspaceFolder}' can not be resolved in a multi folder workspace

### ISSUE THREAD

**Issue by tahnik** [microsoft/vscode#94725]
- VSCode Version: 1.44.0
- OS Version: Windows 10 Pro 1909 Build 18363.720

Steps to Reproduce:

1. Create a workspace
2. Add a folder to that workspace.
3. Add a launch configuration "Node.js: Attach to Process" in the workspace file.
4. Start the debug session.

Here is my workspace file:

```
{
  "folders": [
		{
			"path": "."
		},
		{
			"path": "app"
		}
  ],
  "launch": {
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Attach by Process ID",
        "processId": "${command:PickProcess}",
        "skipFiles": [
          "<node_internals>/**"
        ]
      }

    ],
    "compounds": []
  },
  "settings": {}
}
```

Here is a screenshot of the error:

![image](https://user-images.githubusercontent.com/9964210/78838126-65c76d80-79ed-11ea-8572-a092f1576dbc.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by citrixv9** [comment]
`Version: 1.41.0-insider (user setup)
            Commit: a747d26
            Date: 2019-11-23T11:09:42.834Z
            Electron: 6.1.5
            Chrome: 76.0.3809.146
            Node.js: 12.4.0
            V8: 7.6.303.31-electron.0
            OS: Windows_NT x64 10.0.19025

            Steps to Reproduce:

            Using the TreeDataProvider API load a custom View into Explorer with icons
            Change out one of the icons on disk with another icon of the same name and path.
            Refresh the TreeDataProvider without a window reload.
            Note the icon with same URI will not change.
            Does this issue occur when all extensions are disabled?
            :This issue relates to an extension feature, therefore could not be tested without extensions.`

**Comment by zwaldowski** [comment]
I'm also seeing this in a workspace that already uses the `:` syntax; indeed, it still fails if I change the config to remove all `workspaceFolder` entirely.

**Comment by uullrich** [comment]
I also have the problem under Win 7, VS Code 1.44 and I am not able to debug a remote node process. I don´t have any ${workspaceFolder} variable entry in my configuration. It is also a multi folder workspace. Furthermore I don´t have problems to debug with the Chrome debug plugin.

With 1.43 my debug configuration worked without any problems. So I am using the previous version right now,

I hope these informations are helpful.

**Comment by isidorn** [comment]
Sounds like a regression, investigating...

**Comment by isidorn** [comment]
After some investigation the problem is the following for the workspace configuration our debug extensions appends the following attribute 
`__workspaceFolder:'${workspaceFolder}'`
And the configuration resolver properly tries to resolve this and complains becuase the scope of the folder is not specified.

Proposed fix: the node extension which adds this attribute should scope it if it sees that we are in a multi root folder. So instead of `${workspaceFolder}` use `${FOLDER_NAME:workspaceFolder}`.

Forwarding to @roblourens and @connor4312  as they might know more about the changes in node debug. Adding label regression and candidate.

**Comment by Whobeu** [comment]
Looks similar to a problem I was going to report. I am doing simple Node.js debugging without folders or workspace. Things were working fine in 1.43.2 but when I upgraded to 1.44 I started seeing popup errors related to missing ${workspaceFolder}. Downgraded to 1.43.2 and the error went away. Most likely related to this.

**Comment by weinand** [comment]
@isidorn is the syntax really "${FOLDER_NAME:workspaceFolder}" and not the rev

**Comment by isidorn** [comment]
@weinand you are correct as specified here https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder

**Comment by roblourens** [comment]
Oh. I think this is just so that we can apply defaults that contain `${workspaceFolder}` but we won't be able to pick a default for multi-root workspaces.

I could just not add that property if we are in a multiroot workspace? And I guess it should fail in a nice way if there is a `${workspaceFolder}` reference in a default that can't be resolved?

Is that right @connor4312 or do you remember if there's something else that I added this `__workspaceFolder` hack for?

**Comment by connor4312** [comment]
Currently js-debug needs `__workspaceFolder` for quite a few things. I'll take a look at making those places optional/noop, if you need an interim fix you could pick the first workspace folder (should be no 'worse' than making js-debug no-op)

**Comment by connor4312** [comment]
I've made changes in https://github.com/microsoft/vscode-js-debug/commit/4c29f9c08a59393e2a323dbbe2db1ac8ffe35e3b that should allow undefined workspaces for attach. Launch will still need a workspace folder set; in js-debug I derive this as `path.dirname(program)` if there's none set.

**Comment by roblourens** [comment]
I realized that previously we only set it when useV3 is set, now we set it all the time. I suggest that we just restore that setting check for the candidate.

**Comment by axeldavid** [comment]
Does anyone know of any temporary workaround that can be done locally until the fix has arrived?
I'm quite stuck.. can't run the debugger.

**Comment by zwaldowski** [comment]
@axeldavid You can either downgrade Code itself [to 1.43](https://code.visualstudio.com/updates/v1_43) or upgrade the node-debug extension to 1.44.5 by searching for `ms-vscode.node-debug` and selecting Manage > Install Another Version….

**Comment by axeldavid** [comment]
> @axeldavid You can either downgrade Code itself [to 1.43](https://code.visualstudio.com/updates/v1_43) or upgrade the node-debug extension to 1.44.5 by searching for `ms-vscode.node-debug` and selecting Manage > Install Another Version….

@zwaldowski Thanks a lot. I upgraded the node-debug extension and it works perfectly now.

**Comment by weinand** [comment]
VS Code 1.44.2 (with node-debug 1.44.5) is out now. This should fix the issue.

**Comment by tcarrio** [comment]
> VS Code 1.44.2 (with node-debug 1.44.5) is out now. This should fix the issue.

Can confirm that the latest release has fixed this :+1:
