### ISSUE TITLE
Folders for extensions in the activity bar

### ISSUE THREAD

**Issue by jos3s** [microsoft/vscode#94721]
I would like it to be possible to create folders on the Activity bar so that we can have two extensions sharing the full view
![Anotação 2020-04-08 181151](https://user-images.githubusercontent.com/50359547/78834111-70b9d800-79c4-11ea-844f-e644c17c0003.jpg)

**Comment by sbatten** [comment]
With today's stable release, you can now drag any views into the activity bar to create a custom container. You can then drop any combination of views from extensions or built-in to the new container. Does this sound like it satisfies your request?

Release notes on this feature are [here](https://code.visualstudio.com/updates/v1_44#_increased-view-placement-flexibility).

**Comment by jos3s** [comment]
Yes, I was happy with that option. My suggestion specifically is about the possibility of this extension display being split in two - similar to the code display in the upper and lower half - but with two extensions in order to share
an activity bar
![Anotação 2020-04-08 202421 (1)](https://user-images.githubusercontent.com/50359547/78842835-8a184f80-79d7-11ea-9468-0736eeb82283.jpg)
In this image two different extensions share the same view, so they become a group.

> Gistpad and the Snippets View

**Comment by sbatten** [comment]
Is this the result you are attempting to get?

![image](https://user-images.githubusercontent.com/6561887/78907812-0ccff780-7a36-11ea-98b7-9f7f530755da.png)

**Comment by jos3s** [comment]
Yes, exactly. So I can add extensions with similar goals in a single display making it easier to use them together

**Comment by sbatten** [comment]
Here's how to do that: With both extensions installed:
1. Click the GistPad icon.
2. Drag the Gists view over the Snippets icon in the activity bar, hold for a second until the Snippets view is visible.
3. Continue dragging the Gists view into the Snippets view and drop.

**Comment by jos3s** [comment]
Wow, I didn't know it was possible to do that. However, there is still a problem, there is no view of which extensions are together when this view is active, it would be interesting if the two icons were displayed in the sidebar like the example below
> 1/2

**Comment by sbatten** [comment]
@jos3s as you can probably tell, the more views you move, the more difficult it can be to handle what icon should be shown or how to represent this. We are actively working to simplify this and hope that we can make it as flexible and easy to understand as possible going forward.

**Comment by jos3s** [comment]
I understand, but as you still intend to make these changes, it would be interesting at least in the near future to be limited to two extensions and then be modified in a better way. But thanks for the help.
