### ISSUE TITLE
Add API command to reveal a file/folder in VS Code's explorer

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#94720]
**Feature request**
Add a command that reveals a file/folder in the VS Code explorer. This command should take the URI of the resource to reveal

I imagine the command should also highlight revealed file/folder so that is clear to users what has happened 

**Potential Use Cases**

1. In markdown files, when the user clicks on a link to a folder we reveal that, #91336
1. Link detection in the terminal. If a link to a folder is printed, clicking it should reveal the folder (@Tyriar)

**Comment by mjbvz** [comment]
Alternatively, make the `vscode.open` command reveal a folder in the VS Code explorer when called with a folder URI

**Comment by isidorn** [comment]
@mjbvz thanks for creating this. I just checked and there is already a command that does this. It is called `revealInExplorer`. Can you please try it out so we see if you can just use it or there is something missing.
I see we do not mention it in the [docs](https://code.visualstudio.com/api/references/commands) so that might be the only thing missing.

[Code pointer](https://github.com/microsoft/vscode/blob/379e732c79e6cb0241f95f0e5e45b1dc2255e7ad/src/vs/workbench/contrib/files/browser/fileCommands.ts#L290)

**Comment by mjbvz** [comment]
Thanks @isidorn. I tested that command but it doesn't quite have the behavior I'm looking for. Here's what I'd like the command to do:

- If the resource to reveal is in a collapsed folder, expand the parent folders so that the revealed file is visible
- Highlight the revealed file so that it is more visible to users
- Move the revealed file into view in the explorer

Right now, I looks like the existing command only handles the last part of this: Moving the revealed resource into view in the explorer

**Comment by isidorn** [comment]
@mjbvz Thanks for trying it out.
The command does all those three things for me. Here are my steps
1. explorer.autoReveal: false
2. Open some file nested deep inside some folders, for example `exlporerService.ts`
3. Collapse all in explorer, reload
4. Notice how the parent chaing of the explorerService is collapsed
5. Reval Active File in Side bar -> notice how all three things you expect happend. Also note how the Reveal Active File in Side bar calls the `revealInExplorer` command.

If you do not see this behavior I suggest you put a breakpoint [here](https://github.com/microsoft/vscode/blob/45b2a7e10243677801dc9da34a464b1a15f5df57/src/vs/workbench/contrib/files/browser/fileCommands.ts#L292) and investigate more.

**Comment by Tyriar** [comment]
@isidorn you mean `workbench.files.action.showActiveFileInExplorer` right? I've reported issues before about how it's sometimes flaky: https://github.com/microsoft/vscode/issues/69163

**Comment by isidorn** [comment]
@Tyriar those are unrelated to this I believe. That is an underlying tree issue.

**Comment by mjbvz** [comment]
Here's the code I used to test the `revealInExplorer` command for markdown

```diff
diff --git a/extensions/markdown-language-features/src/commands/openDocumentLink.ts b/extensions/markdown-language-features/src/commands/openDocumentLink.ts
index ef173b6085..8180e2dc2c 100644
--- a/extensions/markdown-language-features/src/commands/openDocumentLink.ts
+++ b/extensions/markdown-language-features/src/commands/openDocumentLink.ts
@@ -47,6 +47,9 @@ export class OpenDocumentLinkCommand implements Command {
 		const fromResource = vscode.Uri.parse(decodeURIComponent(args.fromResource));
 		const targetPath = decodeURIComponent(args.path);
 		const column = this.getViewColumn(fromResource);
+		console.log(targetPath + '');
+		vscode.commands.executeCommand('revealInExplorer', targetPath);
+		return;
 		return this.tryOpen(targetPath, args, column).catch(() => {
 			if (targetPath && extname(targetPath) === '') {
 				return this.tryOpen(targetPath + '.md', args, column);
```

Then in the VS Code docs, try clicking on a link in the editor, such as `![Preview themes from the Command Palette](images/themes/themes_hero.gif)`


This only scrolls the explorer in my testing, but does not select the item or expand its parent folders to make sure it is visible

**Comment by isidorn** [comment]
You are passing a `string`, that command expects a `URI`.
The following snippet in your example works fine for me
```
vscode.commands.executeCommand('revealInExplorer', vscode.Uri.parse(targetPath));
```

**Comment by mjbvz** [comment]
Oh nice! Sorry I missed the argument type here while looking over the code and debugging

I'll close this since that command does what I'm after
