### ISSUE TITLE
Possible regression: As of 1.44 cannot open multiple files from "Go to file..."  menu

### ISSUE THREAD

**Issue by rawfox** [microsoft/vscode#94726]
Description:
As of 1.44, I am not able to open multiple files from "Go to file..." menu (ctrl + p shortcut) when middle mouse clicked on them. I used it when opening similiar/dependent files (ts, html and css for component, etc.) As of 1.44 middle mouse click only opens last file clicked.

Steps to Reproduce:

1. Have dependented files (.html, .ts and .css) with same name.
2. Search for that name in "Go to file..." (ctrl+p shortcut).
3. Middle mouse click on multiple files.

- VSCode Version: 1.44
- OS Version: Windows_NT x64 10.0.18363

**Comment by rawfox** [comment]
I found that holding alt + middle mouse button does open multiple files in 1.44. If it is not regression please fill free to close it.

**Comment by bpasero** [comment]
**Workaround:** configure `"workbench.editor.enablePreviewFromQuickOpen": false` in settings.
