### ISSUE TITLE
The 'you forgot to paste' bot

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#94731]
I see a surprising number of issues that consist entirely of:

```
We have written the needed data into your clipboard because it was too large to send. Please paste.
```

Today I mark them as `needs more info`. Few of these issues get a response.

I'd like a the bot to detect these paste-less issues and either:

- Close them automatically as being invalid. Sorry but you have to meet some min bar when reporting an issue

- Prompt the user for more info

**Comment by JacksonKearl** [comment]
https://github.com/microsoft/vscode/issues/94841
