### ISSUE TITLE
Everytime there is an update, there is a problem with the installation - error 183

### ISSUE THREAD

**Issue by gradientus** [microsoft/vscode#94736]
Issue Type: <b>Bug</b>

Every single time, the update happens whether I want it to or not.  It gets stuck then I have to manually uninstall it, reboot the machine.  Every single time it is error 183.

Please fix this.  It's a huge time suck.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.45GB free)|
|Process Argv|C:\Users\gradi\OneDrive\Desktop\repositories\equalColumnsAndLeftovers|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.2
javascript-ejs-support|Dig|1.3.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.1.1
auto-rename-tag|for|0.1.1
stylelint-plus|hex|0.52.10
mssql|ms-|1.9.0
debugger-for-chrome|msj|4.12.6
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|10.0.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by gradientus** [comment]
Ok.  I have update.enableWindowsBackgroundUpdates set to false.
I've also set update.mode to manual.  

Thank you.
