### ISSUE TITLE
Action "merge all windows" gone after update to 1.44

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#94734]
- VSCode Version: 1.44
- OS Version: macOS 10.15.4

This happened after updating to 1.44.

Steps to Reproduce:

1. set `window.nativeTabs` to `true`, and restart
2. open command palette
3. search for action "merge all windows"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
@ryenus I'm having trouble finding where this was registered in the command palette before, do you remember what version you updated from? I still see it in the "Window" menu:
<img width="273" alt="Screen Shot 2020-04-09 at 9 46 22 AM" src="https://user-images.githubusercontent.com/3672607/78919704-24fc4280-7a47-11ea-9dc7-7929e00200ab.png">

**Comment by ryenus** [comment]
@RMacfarlane thanks for looking into this, I upgraded from **1.43.2**.

**Comment by bsdahl** [comment]
This is a breaker for me. I use the Native tabs command every day as a part of my workflow and VS Code feels broken without them.

All of the Native Tab commands are missing in the latest update.

- "New Window Tab"
- "Show Previous Window Tab"
- "Show Next Tab"
- "Move Tab to New Window"
- "Merge All Windows"

**Comment by sbatten** [comment]
looks like you updated the way these are contributed recently @bpasero

**Comment by bpasero** [comment]
I cannot reproduce this:

![image](https://user-images.githubusercontent.com/900690/79036818-39b61300-7bcc-11ea-9349-117a424242d2.png)

@sbatten what change are you referring to?

**Comment by bsdahl** [comment]
@bpasero the Native tabs commands are missing from the command palette. 

However they are still available by clicking on the Window menu in the top nav bar, as you can see. 

Previously, they were available in the command palette as well.

**Comment by bpasero** [comment]
Confirmed, easy fix.
