### ISSUE TITLE
objective-c cannot jump to definition

### ISSUE THREAD

**Issue by AsteriskZuo** [microsoft/vscode#94735]
- VSCode Version:1.44.0
- OS Version:macOS 10.14.6

Steps to Reproduce:

1.open vscode app
2.open project folder
3.open xxx.h (objective-c header)
4.open xxx.m(objective-c source)
5.modify xxx.h file language type into Objective-C
6.keyboard command + mouse left button not show link and can not jump to definition

![image](https://user-images.githubusercontent.com/11733363/78850411-bb316800-7a49-11ea-9324-508c95df42af.png)

![image](https://user-images.githubusercontent.com/11733363/78850497-f6339b80-7a49-11ea-9b7d-f6be8b876537.png)

Does this issue occur when all extensions are disabled?: No, C++no problem.
C++ extension is installed.

rmbp15zy:mobile-ffmpeg-4.3.1.mac.catalyst.2 asteriskzuo$ code --list-extensions
akamud.vscode-theme-onelight
azemoh.one-monokai
foxundermoon.shell-format
maelvalais.autoconf
mariomatheu.syntax-project-pbxproj
ms-vscode.cpptools
truman.autocomplate-shell
zhuangtongfa.material-theme

`
rmbp15zy:mobile-ffmpeg-4.3.1.mac.catalyst.2 asteriskzuo$ code --list-extensions
akamud.vscode-theme-onelight
azemoh.one-monokai
foxundermoon.shell-format
maelvalais.autoconf
mariomatheu.syntax-project-pbxproj
ms-vscode.cpptools
truman.autocomplate-shell
zhuangtongfa.material-theme
`

**Comment by AsteriskZuo** [comment]
1

**Comment by AsteriskZuo** [comment]
1. First of all, according to what you said, the problem caused by the extension plug-in, I disabled all the vscode plug-ins, but the problem has not been solved;
2. Again, I tried to use the newly downloaded vscode app, but the problem still exists;
3. Again, I switched to a MAC, and the problem remained.
Turns out: it wasn't the plug-in that caused the problem.

**Comment by yume-chan** [comment]
Visual Studio Code itself does not implement **any** go-to-definition features.

It's up to extensions to tell Code where the definitions are.

So, either the C++ extension doesn't know how to find definitions for Objective-C (and you are using the wrong extension) or C++ extension is not working correctly (please report to the C++ extension's issue tracker).

**Comment by AsteriskZuo** [comment]
Please see my second picture carefully，vscode had include objc extension for jump to definitions。 
"update-grammars.js"

**Comment by AsteriskZuo** [comment]
If vscode itself does not implement any go-to-definition features, Is objective-c folder extension in my second picture? If objective-c folder is extension, but I don't think I installed it.

**Comment by AsteriskZuo** [comment]
[objective-c.zip](https://github.com/microsoft/vscode/files/4463797/objective-c.zip)

this is objective-c extension.

**Comment by AsteriskZuo** [comment]
Can you tell me Which extension it is?
<img width="439" alt="Screen Shot 2020-04-11 at 08 31 15" src="https://user-images.githubusercontent.com/11733363/79031052-e2fe0880-7bce-11ea-80f3-aed1cd3b2270.png">

**Comment by AsteriskZuo** [comment]
I try redownload vscode app, open directory "/Users/asteriskzuo/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions", had include objective-c extension.
vscode default installed objectiv-c extension, but can not jump to definitions.
