### ISSUE TITLE
Single view activity bar messed if you move it to some panel

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#94733]
- VSCode Version: 1.44
- OS Version: MacOS Mohave 10.14.6

Steps to Reproduce:

1. Create an extension with a single view activity bar (I added my own package.json below for easier view)
2. Run the extension 
3. Moves its Activity Bar icon (not the panel) to the lower panel (the place you have Terminal, Problems, etc)
4. Moves back that panel to the activity bar. 

You will notice the activity bar icon is not the one provided with the extension, neither the name of the Activity Bar. It will use the name of the single panel registered

It occurred on my **Bookmarks** extension, and also on **Browser Preview** extension.

This is the piece of my `package.json`, where I define the **Bookmarks** Activity Bar.

```json
    "contributes": {
        "viewsContainers": {
            "activitybar": [
                {
                    "id": "bookmarks",
                    "title": "%bookmarks.activitybar.title%",
                    "icon": "images/bookmark-activity-bar.svg"
                }
            ]
        },
        "views": {
            "bookmarks": [
                {
                    "id": "bookmarksExplorer",
                    "name": "%bookmarks.views.Explorer.name%"
                }
            ]
        },
```

This is how the Activity Bar ended up. The lates `Explorer` and `Targets` items are the **Bookmarks** and **Browser Preview** extensions:

![Screen Shot 2020-04-08 at 22 53 20](https://user-images.githubusercontent.com/3781424/78849762-c48be780-79eb-11ea-9989-85a28dec1c1a.png)

Additional Question: Is there a way to _reset_ the activity bar state?

**Comment by alefragnani** [comment]
BTW, you can't drag & drop (to panels) multi-panel Activity Bars. Just each individual panel inside of it.

**Comment by alefragnani** [comment]
#not-a-duplicate of #85330

**Comment by alefragnani** [comment]
WOW! Just found how to _reset_ the activity bar state: `View: Reset View Locations` 🎉

**Comment by sbatten** [comment]
hi @alefragnani , thanks for reporting and I am happy you have found the reset view locations command. you can also right-click > reset view location on a single view. the behavior you are reporting is currently by design, but we are looking to be smarter going forward with icons and titles of containers.

**Comment by davidbarredo** [comment]
Hi @sbatten , for me as a user of an extensión this behaviour can't be named as-designed, because it could lead to lose the functionality of an extension just because I've moved it (drag and drop) to another panel. 

In my case not only the icon is lost, also the funcionality of the extension (https://github.com/alefragnani/vscode-bookmarks/issues/272#issuecomment-617156188)

**Comment by alefragnani** [comment]
Hi @davidbarredo , 

> In my case not only the icon is lost, also the funcionality of the extension (alefragnani/vscode-bookmarks#272 (comment)) 

What do you mean about that? Aren’t the bookmarks being displayed in its view anymore? When I detected the issue, the bookmarks remained working, just as before 😕 .

**Comment by davidbarredo** [comment]
Yes, I lost both the icon and the functionality 😐

**Comment by alefragnani** [comment]
Weird! 

Are the `Refresh` and `Colapse` buttons still available in the View? Don't the bookmarks appear in the View, when you toggle them in the editor?

I found this issue in 1.44.0 (Stable release), and didn't tested after that (right now we had 1.44.2 in the wild), neither using the Insiders.

**Comment by davidbarredo** [comment]
The sidebar was completely empty before the reset view operation

**Comment by alefragnani** [comment]
Ok, but are you saying before you first moved the Bookmarks View to another location, you had bookmarks in the panel, and the “moving” delete them?

**Comment by davidbarredo** [comment]
It happened in an empty project without any bookmarks. 

The problem is everything within the extension disappeared after moving it

**Comment by alefragnani** [comment]
Wow, better this way 😌

It may be fixed when the VS Code team revisit this feature.

**Comment by sbatten** [comment]
With current insiders, I have the bookmarks extension installed and can move it around and reset without losing functionality. You must still use the reset view location to regain the icon from the bookmarks extension after it has been moved. We are still looking into preserving the icon when we can.

**Comment by alefragnani** [comment]
I think the problem with the current approach of moveable panels is that extensions today, only define an `icon` to the Activity Bar, not the View itself. Then, when you move one of its views, VS Code don’t know its icon. Then, when it returns to the Activity Bar, VS Code thinks its empty (because it only expected Panels doing so) and display that default icon. 

I see two options to fix this issue (IMHO, it shouldn’t be labeled _as designed_):

* VS Code `inherits` the `viewContainers` icon to each `view` an extension defines (making all its `views` with the same icon) 
* Improve `viewContainers.view` entry point to support an icon, and use that icon, just like you do with `viewConainers.panels` when the user moves the view _alone_ to an empty Activity Bar.

Personally, I think the first idea should be a _fallback_ to the second one 😁

**Comment by sbatten** [comment]
@alefragnani we are considering both of these options. Since the second one requires action on extension authors parts, we want to make sure it is the approach we are set on before exposing it. We can tackle the fallback before then, however.

**Comment by alefragnani** [comment]
@sbatten thank you! At first sight, I would say both of my extensions would use the same icon on all of its panels, so in my case, the first idea would work perfectly. But I agree other users/extension developers would like the opportunity to have different icons for each panel.

Could you link the related issue here, so we can keep informed about its evolution?

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/issues/93968
