### ISSUE TITLE
YAML syntax highlight is wrong on keys that happen to be keywords

### ISSUE THREAD

**Issue by leafac** [microsoft/vscode#94738]
Issue Type: <b>Bug</b>

The keys are highlighted as keywords, for example, consider the keyword `on`:

```yml
on: push
all: Are
other: highlighted
keys: differently
```

<img width="141" alt="Screen Shot 2020-04-09 at 12 08 04 AM" src="https://user-images.githubusercontent.com/586813/78857017-3c5f0f80-79f6-11ea-9d76-22bd62ee640b.png">

(For example, you may see the `on` keyword as a key in the configuration for a GitHub Action.)

**Possibly related issued:**

- https://github.com/microsoft/vscode/issues/69171
- https://github.com/microsoft/vscode/issues/82300
- https://github.com/textmate/yaml.tmbundle/issues/17

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.3
prettier-vscode|esb|4.1.1
latex-workshop|Jam|8.8.0
code-spell-checker|str|1.8.0
code-spell-checker-portuguese|str|0.1.2

</details>

**Comment by alexr00** [comment]
Moved to the repo we get our yaml grammar from.
