### ISSUE TITLE
Temp change of color scheme on install is kind of jarring / annoying

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#94732]
I'll NEVER EVER EVER want the ISE color scheme in VSCode.  😛  Rather than just switching the whole color scheme (even if just temporarily), what if the extension popped up a notification asking if the user wants to try the ISE (light) color scheme **before** switching the color scheme.

**Comment by RMacfarlane** [comment]
@rkeithhill I'm not sure what you mean by ISE color scheme, what is that? It sounds like this is from an extension, if so, please close this issue and reopen it on the extension itself

**Comment by rkeithhill** [comment]
Whenever I switch back and forth between the PowerShell extension's stable and preview builds, I see this:

![image](https://user-images.githubusercontent.com/5177512/78933003-c6928c80-7a65-11ea-8a07-ed92074b4fff.png)

Maybe we could have a setting where we could disable this?

**Comment by RMacfarlane** [comment]
Please reopen this on the PowerShell extension: https://github.com/PowerShell/vscode-powershell

**Comment by rkeithhill** [comment]
Gah! I see what you are saying. I clicked on the wrong GH link.  Sorry about that.
