### ISSUE TITLE
Enable configuring Typescript Beta Language service

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#9473]
As Typescript language service support is built-in, users cannot enable Typescript language service from an alpha/beta/preview version. Although they can install and use the beta version for building the project. Please enable this configuration, so that language service can use preview/beta compilers, if installed on machine.

**Comment by kieferrm** [comment]
You can define the path to the beta version using the `typescript.tsdk` property in the workspace or user settings.
