### ISSUE TITLE
Using spaces in symbol (editor, workspace) picker can confuse results

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode#94742]
- VSCode Version: 1.44.0
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Create `test.md`
2. Enter `# foo bar` in the test.md
3. Try `⌘T`, type `foo`, VS Code find `test.md` 👍
4. Try `⌘T`, type `bar`, VS Code find `test.md` 👍
5. But if you type `foo bar`, VS Code says **`No matching workspaces symbols`** 🤔

In previous versions, there has been no problem.

I think this problem occurs because of the new features in VS Code 1.44: `Filter results by separating multiple queries with spaces` https://code.visualstudio.com/updates/v1_44

This is a great feature, but it seems to replace the previous feature.

Does this issue occur when all extensions are disabled?: Yes

**Comment by liyuhang1997** [comment]
Steps to Reproduce (Video): https://imgur.com/a/5ov3RJ9

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/30404#issuecomment-604924724

cc @bpasero

**Comment by bpasero** [comment]
Good catch.
