### ISSUE TITLE
Update featured extensions more often

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94745]
Refs: #93604

**Comment by RandomFractals** [comment]
This was a request I fielded, suggesting that 3rd party extensions in the Featured marketplace ribbbon should be rotated more frequently than once every one or two month to promote great extensions and developers contributing to vscode ecosystem.

I think doing it weekly or bi-weekly would be great. 

Another option to consider: extend Featured ribbon to show 3 pages of 6 tiles like Trending extensions are currently handled in marketplace.

Also, there still seems to be some selective pinning of trending extensions. I suspect those are being heavily promoted by your teams, but it's awkward to see an extension trending weekly 1st with lower download counts 1st in the list when you can see other extensions with more update downloads later on those trending rows.

**Comment by isidorn** [comment]
Thank you very much for your feedback, we have an internal issue tracking this and I will forward the feedback there.
However since we already have that issue I will go ahead and close this one
