### ISSUE TITLE
Error creating registry key ?

### ISSUE THREAD

**Issue by LambertWM** [microsoft/vscode#94749]
Issue Type: <b>Bug</b>

Sometimes (regularly I would say) Code gives this error message - I have no idea  what it means

Error creating registry key:
HKEY_CURRENT_USER\Software\Classes\Applications\Code.exe

RgCreateKeyEx failed: Code 1021 

ETCETERA - PS: why can't I post a screenshot ?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.60GB free)|
|Process Argv|C:\dev\darknet-master\cfg\yolov3.cfg|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.71659

</details>

**Comment by LambertWM** [comment]
Nice try, no cigar

**Comment by gjsjohnmurray** [comment]
I am able to paste a screeenshot into this "Write" box in GH, e.g.
![image](https://user-images.githubusercontent.com/6726799/78881040-2b41ed00-7a4e-11ea-9331-1faf186a51c0.png)

I'm using Firefox on Windows

**Comment by joaomoreno** [comment]
@LambertWM It would be great to see a screenshot. If you can't upload it to github, please upload it to another image service and link it here. Thanks.

When does the issue occur exactly?
