### ISSUE TITLE
Find a better way to deal with low star "reviews" without comment

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94743]
Refs: #93604

Low-star "reviews" are currently quite hidden from publishers -- they show up in a count, but you don't know they happen and you have no ability to follow up as to why and/or provide help. We should find a better way to deal with them

**Comment by RandomFractals** [comment]
one option I suggested worth considering was prompt developers who provide low star rating to include comments for extension authors to review and address.

**Comment by usernamehw** [comment]
There's also a bit similar scenario:

- User found a bug and made a review with 1 star
- The bug was fixed and the author wrote a reply saying so
- The 1 star review is still there years later

**Comment by RandomFractals** [comment]
@urbandove yeah, I've seen a lot of those too. I am not sure if users get notified when followup comment is posted, or developers just move on when their issue is addressed.

**Comment by fiveisprime** [comment]
I'd also like to see a banner that links to the extension's repo reminding the reviewer that bugs should be logged there rather in a review.

**Comment by RandomFractals** [comment]
additionally, I think it would be nice if review comments would would convert links to github issues to proper links instead of showing them as text since some devs do post links to the reported issue resolution via github issues or release tags.

**Comment by isidorn** [comment]
Created upstream issue https://github.com/microsoft/vsmarketplace/issues/151

**Comment by isidorn** [comment]
Closing since there is an issue on the marketplace tracking it.
