### ISSUE TITLE
Provide a telemetry story for extensions

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94748]
Refs: #93604

Currently we don't have a good telemetry story for extensions. We do provide a [telemetry library](https://github.com/Microsoft/vscode-extension-telemetry) for Application Insights, but it explicitly talks about "first-party" extensions, and might have GDPR issues because of its opt-in being based on the VS Code opt-in.

It would be great if extension authors could just get access to certain telemetry on the marketplace dashboard (or something like that) without requiring any specific instrumentation. It would also be great for extensions that wanted to go above and beyond that, we provided an API for this purpose. To help avoid every extension having a home grown (and bundled) solution, both bloating extension size and performance (as reporting can't be effectively batched).

**Comment by sana-ajani** [comment]
Related: https://github.com/microsoft/vscode/issues/14800

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/14800
