### ISSUE TITLE
Missing the first letter of folder name in path while running .py file in terminal

### ISSUE THREAD

**Issue by AskoldNebelskyi** [microsoft/vscode#94758]
- VSCode Version: 1.44.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open my virtual env for python programming (
2. Run the python file in terminal.
3. And this is it. Sometimes vscode miss a first letter of folder name in path while running
It does not happen everytime. Rarely, it's working fine. The first letter do not  miss and all is going good.

![image_2020-04-09_10-33-59](https://user-images.githubusercontent.com/49891135/78870326-9b507300-7a4e-11ea-89d9-515558108afe.png)
![photo_2020-04-09_10-40-49](https://user-images.githubusercontent.com/49891135/78870327-9c81a000-7a4e-11ea-98f2-3e5fed8ffb35.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Please reopen this on the python extension: https://github.com/Microsoft/vscode-python

Thank you!
