### ISSUE TITLE
Add "Close folder" on Welcome screen (if a folder is open)

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [microsoft/vscode#94755]
If the last thing I had opened is a folder, and I close and reopen VS Code again, it remembers the folder and also shows the welcome screen.

The welcome screen is ok, but let's show a link to close that folder.

![image](https://user-images.githubusercontent.com/668160/78862742-5cafbe00-7a38-11ea-95c7-20c12eda7739.png)

**Comment by gjsjohnmurray** [comment]
Please say more about your use-case. After you close the folder (using that option on the File menu, or by pressing its shortcut chord, 'Ctrl+K F' on Windows), what do you do next?

**Comment by bjorn-ali-goransson** [comment]
Then I'll open a file.

Den tors 9 apr. 2020 11:20John Murray <notifications@github.com> skrev:

**Comment by gjsjohnmurray** [comment]
So maybe the contents of the **Start** section of Welcome could be enhanced to show different options depending on current state, e.g.

**Case 1: Folder is open**
* View Explorer
* Add folder to create multi-root workspace...
* Open different folder...
* Close folder and open file...

**Case 2: Workspace is open**
* View Explorer
* Add folder to workspace...
* Open different workspace...
* Close workspace and open file...
* Close workspace and open folder...

**Case 3: Neither a folder nor a workspace is open**
* New file
* Open file...
* Open folder...
* Open workspace...

Perhaps the "New file" option should be appended to Case 1 and Case 2 for backward compatibility, though personally I think it's unusual to want to create a new unnamed file when working with a folder or a workspace.

**Comment by bjorn-ali-goransson** [comment]
Well, sometimes the workspace or folder is open only because I clicked the VS Code icon. So the intent of opening a ws or folder isn't really known.

BTW, never thought about what the "Add workspace folder" means previously but now when you mention it, I understand that it opens a workspace.

**Comment by gjsjohnmurray** [comment]
> Well, sometimes the workspace or folder is open only because I clicked the VS Code icon

If you know you want to start with an empty VS Code window rather than with whatever was open when you previously closed VS Code, look for the "New Window" option on the context menu of the VS Code icon.

> BTW, never thought about what the "Add workspace folder" means previously but now when you mention it, I understand that it opens a workspace.

The "Add workspace folder..." link on the current Welcome page is equivalent to the "Add Folder to Workspace..." option on the File menu. It doesn't **open** a workspace (a .code-workspace file). To do that, use the "Open Workspace..." command from the File menu.

**Comment by bjorn-ali-goransson** [comment]
Thanks for the tip, but sometimes you click on it assuming it to open
something else. But I digress. It's just a suggestion.

**Comment by MightyPen** [comment]
_Loosely Related Request:_ &nbsp; #96808 &nbsp; `https://github.com/microsoft/vscode/issues/96808`

- "Want `Close Folder` button in Explorer control"
