### ISSUE TITLE
:bug: has changed in the meantime  bulkEditService

### ISSUE THREAD

**Issue by taoqf** [microsoft/vscode#94754]
- VSCode Version:1.44.0, 1.43.2
- OS Version:Debian

Steps to Reproduce:

1. create a workspaceEdit
1. create a new file
1. aplly edit
1. create the same file again with overwite:true
1. apply edit (error throws out here)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Error seems to originate from bulk edit service.

**Comment by jrieken** [comment]
This is directly delegated to the text file service: https://github.com/microsoft/vscode/blob/8ad94ef2ac4d5f2921f6ed081b3c492f30a48413/src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts#L360

**Comment by bpasero** [comment]
Does not reproduce for me, code:

```ts
const edit1 = new vscode.WorkspaceEdit();
edit1.createFile(vscode.Uri.file('/Users/bpasero/Desktop/test-js/tslint.json2'));

vscode.workspace.applyEdit(edit1);

const edit2 = new vscode.WorkspaceEdit();
edit2.createFile(vscode.Uri.file('/Users/bpasero/Desktop/test-js/tslint.json2'), { overwrite: true });

vscode.workspace.applyEdit(edit2);
```

**Comment by taoqf** [comment]
What about insert some text before applyEdit? or sleep a while before second creation?

**Comment by taoqf** [comment]
This happens a lot in my project.

**Comment by jrieken** [comment]
> What about insert some text before applyEdit? or sleep a while before second creation?

This is not how it works. It's your responsibility to create repro-steps, not ours.

**Comment by bpasero** [comment]
I had tried with a timeout too, but could not. Exact steps of how to build the edit that causes this is needed.

**Comment by taoqf** [comment]
Then forget it, I don't think I could create repo-steps easily for now, I've changed to 'fs' now, and it works fine, and faster, thanks @jrieken @bpasero .
