### ISSUE TITLE
Allow extensions to contribute to the VS Code welcome page

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94750]
Refs: #93604

@alefragnani Can you provide more details on what you are looking for here?

**Comment by alefragnani** [comment]
Hi @eamodio ,

Sure, I’m talking about https://github.com/microsoft/vscode/issues/63152, created by @misolori to explore improvements in the Welcome Page. I added [this comment](https://github.com/microsoft/vscode/issues/63152#issuecomment-481538199), asking to be able to _contribute_ to some sections in the Welcome Page.

I found a few others issues which requests other improvements/customizations to the Welcome Page as well, like https://github.com/microsoft/vscode/issues/63057 And https://github.com/microsoft/vscode/issues/67600.

Thank you
