### ISSUE TITLE
Extenstions are not working

### ISSUE THREAD

**Issue by harshilparmar** [microsoft/vscode#94762]
After the last update of VS code,I can not use any extensions. Please help...

**Comment by gjsjohnmurray** [comment]
Please find out which of your extensions is causing the issue. Either disable all and then re-enable one at a time, or disable half of them to narrow the field faster (bisecting).

Similar to #94756

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/94807
