### ISSUE TITLE
workbench.explorer.fileView.focus became invalid in v1.44.0

### ISSUE THREAD

**Issue by wdscxsj** [microsoft/vscode#94761]
- VSCode Version: 1.44.0
- OS Version: Windows 10

I think the title says all. A workaround is really appreciated.

**Comment by sbatten** [comment]
@wdscxsj can you explain what you mean by invalid? this command is still working for me?

**Comment by wdscxsj** [comment]
@sbatten Sorry if I missed something, but this was the first weird thing for me after the update (same with `--disable-extensions`):

`keybindings.json`:

![Screenshot032](https://user-images.githubusercontent.com/863369/78954430-c5696a00-7b0e-11ea-8ca6-0561caf93dc8.png)

`Ctrl+k a` pressed:

![Screenshot033](https://user-images.githubusercontent.com/863369/78954437-cd290e80-7b0e-11ea-837c-4d8e84e1722c.png)

**Comment by sbatten** [comment]
@wdscxsj ah, I see the problem now. The command is not valid without an open folder. When you open a folder, this will work. The files view is not present until a folder is opened.

/cc @joaomoreno @isidorn

**Comment by wdscxsj** [comment]
@sbatten Thanks for the confirmation!

I suppose the focus on folder/project/workspace is too strong in recent releases. By definition VSCode is a text (source code) editor. It may feel like an IDE but still an Editor above all. Support for folder is insanely great, but that should not come at the cost of inferior UX of plain text editing. I remember how Visual Studio struggled to load a solution 15 years ago. Please don't turn VSCode from a lovely utility into a batteries excluded Visual Studio.

**Comment by sbatten** [comment]
assigning to @isidorn as he owns the explorer

**Comment by isidorn** [comment]
@wdscxsj please use `workbench.files.action.focusFilesExplorer` instead
@sbatten I believe the command the user is missing is a general view command. And I would suspect that due to your refactoring the command is no longer available before the view has been opened. So it seems like a general view issue imho

**Comment by sbatten** [comment]
I tested this on 1.38.1 from September which is well before my refactor work. It has been this way for quite some time, but I believe the general explorer focus command is the right command to use if you don't have folders open.

**Comment by isidorn** [comment]
Then closing as desinged since there is a workaround command. Thanks

**Comment by wdscxsj** [comment]
@sbatten Thanks for your suggestion of `workbench.files.action.focusFilesExplorer`, but don't we have `Ctrl+Shift+E` already? I used to call `workbench.explorer.fileView.focus` with a shortcut to show the "No folder opened" viewlet or the file tree, and call `outline.focus` with another shortcut to show Outline. Is there a better workaround for v1.44 and later?

**Comment by isidorn** [comment]
When I do fresh reload and Explorer viewlet is not shown, F1 > focus outline view still works just fine. And you can assign any keybinding to it.
Also Ctrl+Shift+E also works for the No Folder Opened case, so I do not really understand what is missing.

**Comment by wdscxsj** [comment]
@isidorn With this layout and configuration, may I still use `ctrl+k a` to directly expand the "No folder opened" viewlet?

![Screenshot037](https://user-images.githubusercontent.com/863369/79194952-0986a280-7e60-11ea-9ffe-4b351a44efd2.png)

**Comment by isidorn** [comment]
No I do not think you can. Since the Explorer is missing a command which expands the Explorer view.
I have added the command using the ID which you seemed to have used.
Try it out with vscode insiders tomorrow.
@sbatten fyi

**Comment by wdscxsj** [comment]
That's great. Thank you!

**Comment by sbatten** [comment]
I am not sure the new command is necessary. With no folder opened, the view has a different command that is already present.

```
    {
        "key": "ctrl+k a",
        "command": "workbench.explorer.fileView.focus",
        "when": "workbenchState != 'empty'"
    },
    {
        "key": "ctrl+k a",
        "command": "workbench.explorer.emptyView.focus",
        "when": "workbenchState == 'empty'"
    }
```

**Comment by isidorn** [comment]
@sbatten where are those commands registered? I could not find them when I did my change.

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/blob/4aba29719297ef9745357be50e4315ede58bbec9/src/vs/workbench/browser/parts/views/views.ts#L613-L632

**Comment by isidorn** [comment]
Aha, so my change simply forces the emptyView.focus to not have a special command, but to use the same one. I think that makes sense, since it is the same view for the user at the end.

**Comment by sbatten** [comment]
To Verify:
1. Open an empty window.
2. Attempt to set a keybinding with the keybinding editor for `workbench.explorer.fileView.focus`
3. Verify the keybinding works to focus the no folder opened view.
4. Open a workspace.
5. Verify the same keybinding works to focus the files explorer.

**Comment by wdscxsj** [comment]
That's better indeed. Thanks for your investigation!
