### ISSUE TITLE
VSCode opens Window instead of tab on opening file

### ISSUE THREAD

**Issue by Dr-Nuke** [microsoft/vscode#94767]
- VSCode Version:
Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
- OS Version:
Windows 10 / WSL Ubuntu 18.04

Steps to Reproduce:

1. open terminal
2. make a file: `touch deleteme.file`
3. edit file with VSCode: `code deleteme.file`
4. new window opens

Expected behavior:
4. new tab opens, not a new window

User settings in action:
```
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "window.openFilesInNewWindow": "off"
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
I cannot reproduce and I have ` "window.openFilesInNewWindow": "off"` configured.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Dr-Nuke** [comment]
> Can you try to reproduce with our nightly insider builds?
Yes. I just downloaded & installed
```
Version: 1.45.0-insider (user setup)
Commit: c12bd56a8886f31e353a45f5846f0a35a52f908e
Date: 2020-04-10T05:44:09.656Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```
running code `deleteme.file` (was a .csv file) in the fresh terminal openes the file in a new window that is detached from the original window. 
Then i checked that the option `window.openFilesInNewWindow` is set to `off`, which it was.
Then i entered `code deleteme.file --reuse-window` , and again a new window popped up
