### ISSUE TITLE
Paths in some git commands used improperly

### ISSUE THREAD

**Issue by HanabishiRecca** [microsoft/vscode#94769]
- VSCode Version: 1.44.0
- OS Version: Windows 10 / 1909

Steps to Reproduce:

1. Go to git repo with spaces in the path
2. Open some file diff
2. Look at git output console

Does this issue occur when all extensions are disabled?: Yes

E.g.
![изображение](https://user-images.githubusercontent.com/13597663/78884555-8b4b8a00-7a74-11ea-8dce-cc1835f6507c.png)

Paths sent without double quotes. As you can see even VS Code console has problems with distinguishing it.

And git also has problems with this in some cases. It can throw an error like
```
fatal: D:\Documents\Visual: 'D:\Documents\Visual' is outside repository at 'D:\Documents\Visual Studio 2019\Projects\WslShortcut'
```

Fix seems pretty simle, for example:
https://github.com/HanabishiRecca/vscode/commit/adb8f0dac964762a477468896f8a7d83119be2a1

After my fix it works properly:
![изображение](https://user-images.githubusercontent.com/13597663/78885408-f8135400-7a75-11ea-9acb-7cd8509d5ca0.png)

**Comment by joaomoreno** [comment]
> And git also has problems with this in some cases. It can throw an error like

It can... but does it? We don't need quotes since we're not invoking git.exe through a shell. Have you observed any error related to this at all? If so, can you provide steps for me to reproduce the issue?

**Comment by HanabishiRecca** [comment]
@joaomoreno, not really. My usage scenario is not intended a bit and synthetic.

I'm developing a program which connects Windows apps with WSL world. https://github.com/HanabishiRecca/WslShortcut
And the problem is the path conversion breaks when path is not wrapped in quotes. Because there is no proper way to distinguish it.

So if you will decide this fix is not necessary / not worth it - alright then.

**Comment by HanabishiRecca** [comment]
Wait a minute. This does not work at all.
![изображение](https://user-images.githubusercontent.com/13597663/79229319-41034800-7e7c-11ea-92a0-e41b910f02ed.png)

@joaomoreno, please, check this behavior by yourself. Are your sure this VS Code functionality was not entirely broken all this time?

**Comment by HanabishiRecca** [comment]
Also via cmd
![изображение](https://user-images.githubusercontent.com/13597663/79231123-051db200-7e7f-11ea-810f-26a23599322e.png)

**Comment by joaomoreno** [comment]
You're launching git from a shell. VS Code doesn't launch git from a shell, so it doesn't need quotes.

**Comment by HanabishiRecca** [comment]
Hmm, yeah, I've made the output logging inside VS Code itself. It's ok there.

![изображение](https://user-images.githubusercontent.com/13597663/79233218-f4227000-7e81-11ea-9715-81419d334f2a.png)

@joaomoreno, sorry for bothering.
