### ISSUE TITLE
inconsistency in "Javascript React" or JSX syntax highlighting with { bracket-enclosed expressions }

### ISSUE THREAD

**Issue by meows** [Microsoft/vscode#9476]
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-07-19T05:12:40.233Z)
- OS Version: Linux x64 4.2.0-42-generic

**Issue**: Inconsistent syntax highlighting with "Javascript React" or JSX with `{ bracket-enclosed javascript expressions }` depending on whether their enclosing JSX element have properties, like:

``` jsx
<Element id="aProperty">
    { thing.map(x => <div>{x}</div>) }
</Element>
```
or
``` jsx
<div className="aProperty">
    { thing.map(x => <div>{x}</div>) }
</div>
```

Which will highlight differently when the element properties are removed, like:

``` jsx
<Element>
    { thing.map(x=> <div>{x}</div>) }
</Element>
```
or
``` jsx
<div>
    { thing.map(x => <div>{x}</div>) }
</div>
```

**Comment by aeschli** [comment]
caused by #3008
