### ISSUE TITLE
VSCode crash

### ISSUE THREAD

**Issue by mikkym** [microsoft/vscode#94768]
Issue Type: <b>Bug</b>

Second time my VS Code is crushing. I didn't do anything special, just worked with my code. It showed me a little modal window with warning icon and one button. It was written there "VS Code Insiders - Window has crashed" or smth like this. After clicking on the button, the window was restarted and idk, maybe it's just coincidence, but my Windows was crushed too. And it's happened second time too. That's why i writing to you.

VS Code version: Code - Insiders 1.44.0-insider (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T21:41:19.483Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.2
githistory|don|0.6.3
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.1.1
terminal|for|0.0.10
vscode-styled-components|jpo|0.0.29
vscode-language-babel|mgm|0.0.27
postcss-language|mhm|2.1.0
theme-monokai-pro-vscode|mon|1.1.15
material-icon-theme|PKi|4.0.1
js-jsx-snippets|sky|10.1.0
material-theme|zhu|3.2.5

(3 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Can you provide the crash id of your vscode instance by performing the following steps.

* go to command palette > Open devtools 
* Again from the command palette > Log Storage Database Contents.
* Check the devtools console and you should see `crashReporter.guid` in the printed array
* Provide the value associated with it.

Thanks!

**Comment by mikkym** [comment]
Hi!
I did everything according to the guide, but the console was empty. Could this be due to the fact that I had an update after yesterday after closing?
But yesterday, after the crash, VS Code formed 2 files with the name "report"
Can it be useful?

**Comment by deepak1556** [comment]
> Could this be due to the fact that I had an update after yesterday after closing?

No that shouldn't affect, the crashreporter id is a persistent id. Can you attach a gif or video of what you tried, thanks!

> But yesterday, after the crash, VS Code formed 2 files with the name "report"

Most likely not so useful, but do attach it.

**Comment by mikkym** [comment]
Sorry, my bad.
Last time when i called **_Log Storage Database Contents_** - my console was empty.
Now i see array.
crashReporter.guid value is "48612400-cde8-473b-b987-13b53f988ec9"

**Comment by deepak1556** [comment]
Sorry @mikkym , I was unable to track down the crash report on our system. If the crash happens, can you attach the reports from the following location `C:\Users\...\AppData\Local\Temp\VSCode Crashes\reports`

**Comment by mikkym** [comment]
Sure.
Thank you
