### ISSUE TITLE
VSCode for Mac v1.44.0 not respecting `search.exclude` in settings.json

### ISSUE THREAD

**Issue by maxathanja** [microsoft/vscode#94776]
- VSCode Version: `1.44.0`
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. Add the folders to be excluded to `settings.json`, ie:
```
"search.exclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules": true,
    "**/node_modules/**": true,
    "**/.git": true,
    "**/dist/**": true,
    "**/temp/**": true,
   },
```

2. Search for something.

Does this issue occur when all extensions are disabled?: Yes

Explanation:
Latest update `1.44.0` of VS Code for Mac broke the `search.exclude` setting. One can see results from search-excluded results while searching globally.

Here is a screenshot:

<img width="1280" alt="vscode_1 44 0" src="https://user-images.githubusercontent.com/25719815/78891525-681edb80-7a70-11ea-8913-220cf3f67a1d.png">

**Comment by RMacfarlane** [comment]
@maxathanja Can you expand the search box with the button on the left, and then click the "..." to further expand it, and see if the "Use Exclude Settings and Ignore Files" button is highlighted within the "files to exclude" input?
<img width="394" alt="Screen Shot 2020-04-09 at 8 37 09 AM" src="https://user-images.githubusercontent.com/3672607/78913229-8ddebd00-7a3d-11ea-9601-41e04161a05c.png">

**Comment by maxathanja** [comment]
@RMacfarlane Please accept my endless gratitude!
I think I saw that 'Search Details' button for the first time. Must have toggled it somehow without knowing.
All is well!

**Comment by RMacfarlane** [comment]
Glad that fixed it!
