### ISSUE TITLE
Can't select recently visited file using arrow keys

### ISSUE THREAD

**Issue by Artur2** [microsoft/vscode#94775]
- VSCode Version: 1.44.0
- OS Version: Windows 10 Pro 1809

Steps to Reproduce:

1. Open some files in project/folder
2. Press Ctrl+Tab
3. Try to move around displayed list with arrow keys (↑, ↓)
4. See opened list scrolling instead of moving selection of file

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Artur2** [comment]
Video of reproducing - https://monosnap.com/file/Utk8gEgiS0INNGDqKOhjAZjYzQi68Q

**Comment by Artur2** [comment]
In Azure Data Studio shipped with VS Code version 1.42.0 everything fine

**Comment by gmccullo** [comment]
I get this too. It's pretty painful.

**Comment by bpasero** [comment]
We will try to get a fix into our recovery, thanks for noting.

**Comment by bpasero** [comment]
As a workaround you can configure these keybindings:

```
{
	"key": "ctrl+up",
	"command": "list.focusUp",
	"when": "listFocus && !inputFocus && inQuickOpen"
},
{
	"key": "ctrl+down",
	"command": "list.focusDown",
	"when": "listFocus && !inputFocus && inQuickOpen"
}
```

**Comment by Artur2** [comment]
Thanks, will wait for that :)

**Comment by Usman1395** [comment]
> As a workaround you can configure these keybindings:
> 
> ```
> {
> 	"key": "ctrl+up",
> 	"command": "list.focusUp",
> 	"when": "listFocus && !inputFocus && inQuickOpen"
> },
> {
> 	"key": "ctrl+down",
> 	"command": "list.focusDown",
> 	"when": "listFocus && !inputFocus && inQuickOpen"
> }
> ```
Hi...The code works pretty fine now....
Hi Could You Please let us know the code if we could use page up and page down with it too....
Like in previous versions....
Please....

**Comment by rohith** [comment]
> 
> 
> As a workaround you can configure these keybindings:
> 
> ```
> {
> 	"key": "ctrl+up",
> 	"command": "list.focusUp",
> 	"when": "listFocus && !inputFocus && inQuickOpen"
> },
> {
> 	"key": "ctrl+down",
> 	"command": "list.focusDown",
> 	"when": "listFocus && !inputFocus && inQuickOpen"
> }
> ```

I so regret not finding sooner my past few days were real hard struggle without this

**Comment by mikekov** [comment]
Maybe it's just me, but new behavior is still not correct... When I bring up "quick open" list and attempt to move current item, it does move, but at the same time content scrolls too! That makes it difficult to see what I'm selecting as all items scroll.

The workaround was to add this snippet to key bindings:

```
{
	"key": "ctrl+up",
	// "command": "list.focusUp",
	"when": "listFocus && !inputFocus && inQuickOpen"
},
{
	"key": "ctrl+down",
	// "command": "list.focusDown",
	"when": "listFocus && !inputFocus && inQuickOpen"
}
```
Note the commented out commands.

**Comment by Usman1395** [comment]
> Maybe it's just me, but new behavior is still not correct... When I bring up "quick open" list and attempt to move current item, it does move, but at the same time content scrolls too! That makes it difficult to see what I'm selecting as all items scroll.
> 
> The workaround was to add this snippet to key bindings:
> 
> ```
> {
> 	"key": "ctrl+up",
> 	// "command": "list.focusUp",
> 	"when": "listFocus && !inputFocus && inQuickOpen"
> },
> {
> 	"key": "ctrl+down",
> 	// "command": "list.focusDown",
> 	"when": "listFocus && !inputFocus && inQuickOpen"
> }
> ```
> 
> Note the commented out commands.

Hi....
If You ask me I would suggest going back to the previous version that worked and then update to the newer version when it comes and if the newer version still causes problem downgrade to the version that previously worked.

https://code.visualstudio.com/updates/v1_43

Go to this link and download this version that is 1.43.2 which is stable and is working .
I my self went back to this version because this one is working pretty good.
You just have to download the setup and install it nothing will get affected and just vscode version will change but everything else will remain same like your opened  tabs etc.
