### ISSUE TITLE
codeActionsOnSave as array opens browser tab?

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#94774]
- VSCode Version: 1.44.0
- OS Version: Ubuntu 16.04.5 (via remote SSH)

Steps to Reproduce:

1. Changed my config to:
```javascript
  "editor.codeActionsOnSave": [
    "source.organizeImports",
    "source.fixAll.eslint"
  ],
```
2. Make some changes in a file that ESLint tries to fix. I am using the Prettier plugin+config `"plugin:prettier/recommended"`.
3. It opens https://github.com/prettier/eslint-plugin-prettier#options 😆 

Yes, I know it sounds weird, but it is consitent. Restart of VS Code after changing from object to array also did not help.

Does this issue occur when all extensions are disabled?: Since I assume this is in combination with an extension, I'm not sure disabling is of any value.

**Comment by numToStr** [comment]
I am also facing this issue when eslint fixes the issue. It opens the doc of that issue.

**Comment by mjbvz** [comment]
Please file this against eslint. It should not be reading this setting value directly so changing it to an array should have had no effect
