### ISSUE TITLE
outline view not work

### ISSUE THREAD

**Issue by nanmingzhidian** [microsoft/vscode#94773]
In the outline View:
"The active editor cannot provide outline information."

VS Code version: Code 1.43.2 
OS version: Windows 7 x64

install VS Code many times, bug don't fix the bug.
can't use Shift + Ctrl + O

**Comment by nanmingzhidian** [comment]
Lua
not install any extention

**Comment by nanmingzhidian** [comment]
The first installation works, but there is no way to recover after a problem occurs

[UserName/.vscode] and [UserName/AppData/Roaming/Code] have been deleted

It won't work no matter how many times you reinstall it

**Comment by nanmingzhidian** [comment]
I just tried python and js and they don't work outline view

The computer I work on doesn't have Internet

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
