### ISSUE TITLE
Unable to open a file in VS Code with right click option

### ISSUE THREAD

**Issue by daseed** [microsoft/vscode#94781]
Issue Type: <b>Bug</b>

Hello,

Since a few days it is impossible for me to open a file from windows explorer, or even the desktop, by doing a right-click on the file and selecting the "Open in VS Code" option. 
The behavior is an error sound is playing and a message pops-up but disappear to quickly to see anything.
I had a look at the Event Viewer but no trace there.

Do you have any idea how to solve this ?

Many thanks for your help.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (14.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-data-class-generator|Ben|0.3.17
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
vscode-eslint|dba|2.1.2
xml|Dot|2.5.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.1
LogFileHighlighter|emi|2.7.1
prettier-vscode|esb|4.1.1
pubspec-dependency-search|eve|1.1.0
bloc|Fel|3.4.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.17
pubspec-assist|jer|0.3.6
vscode-styled-components|jpo|0.0.29
vscode-github|Kni|0.30.3
rainbow-csv|mec|1.6.0
graphql|mqu|0.1.2
vscode-scss|mrm|0.9.0
mssql|ms-|1.9.0
indent-rainbow|ode|7.4.0
vscode-versionlens|pfl|0.25.0
errorlens|Phi|1.1.3
material-icon-theme|PKi|4.0.1
vscode-graphql|Pri|0.2.14
vscode-icons|vsc|10.0.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by daseed** [comment]
After investigating a bit further, it appears that the problem is not what i thought.
Actually when i try to open a file with a right-click "open in VS Code" or even when i try to right click on the VS Code icon in the task bar to open a previously opened folder, and there is already an instance of VS Code open then the previously described behavior occurs.

**Comment by joaomoreno** [comment]
Can you reproduce if you restart your machine?

**Comment by daseed** [comment]
Hello,

As you can see on the video by following this link: https://drive.google.com/open?id=1vkThUflttnF-QxwA5uJ6-geUicopcivR
It does still exist after rebooting.

Best regards,

Pierre-emmanuel Legrain.
[https://lh6.googleusercontent.com/Do41g6j3MLO03zheDOdHuOxV7dZ9Hg2bsQrw6ZIWYasji9gMH9i8EkwKrHXHSLQ=w1200-h630-p]<https://drive.google.com/open?id=1vkThUflttnF-QxwA5uJ6-geUicopcivR>
bugVSCode.mp4<https://drive.google.com/open?id=1vkThUflttnF-QxwA5uJ6-geUicopcivR>
drive.google.com


________________________________
De : João Moreno <notifications@github.com>
Envoyé : mercredi 15 avril 2020 07:48
À : microsoft/vscode <vscode@noreply.github.com>
Cc : daseed <daseed@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [microsoft/vscode] Unable to open a file in VS Code with right click option (#94781)


Can you reproduce if you restart your machine?

**Comment by joaomoreno** [comment]
I can't seem to open that video link, could you put it on Youtube?

**Comment by daseed** [comment]
Hello Mister Moreno,

You can find it here: https://youtu.be/Ep1afl454oY

Best regards,

Pierre-emmanuel Legrain

________________________________
De : João Moreno <notifications@github.com>
Envoyé : vendredi 17 avril 2020 10:23
À : microsoft/vscode <vscode@noreply.github.com>
Cc : daseed <daseed@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [microsoft/vscode] Unable to open a file in VS Code with right click option (#94781)


I can't seem to open that video link, could you put it on Youtube?

**Comment by joaomoreno** [comment]
The error you're getting says

> A second instance of Visual Studio Code is already running as administrator. 

So this is https://github.com/microsoft/vscode/issues/86968

@bpasero cc because the alert comes and goes really fast, please watch the youtube video. You might wanna dig in to that.
