### ISSUE TITLE
git: format the commit messages

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#94782]
Generally I like to format the commit messages following some rules that I read in the following link:
https://chris.beams.io/posts/git-commit/

Basically the rules are as follows:

1. Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
4. Do not end the subject line with a period
5. Wrap the body at 72 characters

Would it be possible to implement in VSCode some configuration that would allow the implementation of some of these rules?

**Comment by RMacfarlane** [comment]
Hi @jvesouza, you can accomplish this using a git `commit-message` hook, a script that is run by git when you are committing that validates the commit message. https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
