### ISSUE TITLE
Codicon/ThemeIcon is misaligned in QuickPick

### ISSUE THREAD

**Issue by lesha-co** [microsoft/vscode#94787]
- VSCode Version: 1.43.2
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Create an extension using [tutorial](https://code.visualstudio.com/api/get-started/your-first-extension)
2. In that, use QuickPick with a button:

```
const addButton: QuickInputButton = {
  iconPath: new ThemeIcon("add"),
  tooltip: "tooltip",
};

const qp = window.createQuickPick();
qp.buttons = [addButton];
qp.show();
```

3. The `+` button is not vertically centered, see the [screenshot](https://i.stack.imgur.com/KoNti.png). It should be.

 

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
This is already fixed in the latest version of VSCode, 1.44.0. Please try updating. Thank you!
