### ISSUE TITLE
VS Code Fails During Update and Corrupts Installation

### ISSUE THREAD

**Issue by Stoicus** [microsoft/vscode#94791]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. VS Code automatically applies update.
2. Update fails with message that it cannot delete a needed file.
3. Uninstall VS Code
4. Download and re-install VS Code.
5. Receive this message:

![image](https://user-images.githubusercontent.com/33098523/78901759-6a684200-7a3e-11ea-9e4e-31ee09d36b22.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Hamster-0001** [comment]
I am experiencing the same issue without using any extensions. I keep having to reinstall VS Code everytime it tries to update.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
