### ISSUE TITLE
[Feature Request] Can we also have Timeline from the Explorer view be shown in the Git view?

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#94795]
Currently, in the latest March 2020 (version 1.44) release notes, Timeline view is now enabled by default in the Explorer view. Timeline can now display the commit history of the current Git branch that we checked out in the workspace.

However, Timeline is restricted to be viewable in the Explorer view, not in the Git view. As of this moment after updating to 1.44, all the Git view ever shows is the changes, the staged changes, and merge conflicts. There is no Timeline in the Git view. 

I believed it is really helpful for us to be able to see the commit history in Timeline, instead of having to jump back and forth between Git view and Explorer view for the Timeline.

Maybe there's an option for us to enable Timeline in the Git view? Please let me know if this is the case. It would be wonderful to be able to have the Timeline in the Git view. 

Thanks for considering.

**Comment by sbatten** [comment]
With 1.44, views can be dragged and dropped into other locations. This means you can drag timeline into the SCM (git) view. To do this, drag the timeline view header to the SCM view icon, hold until the SCM view shows, then move inside the scm view to drop the timeline view where you like.

**Comment by tommai78101** [comment]
Thanks!

**Comment by sbatten** [comment]
Sorry no that's not something we support at this time.
