### ISSUE TITLE
Problem with colors in the integrated terminal

### ISSUE THREAD

**Issue by svillar** [microsoft/vscode#94790]
- VSCode Version: 1.44.0
- OS Version: Debian testing

### Steps to Reproduce:

1. Run the following bash script in the integrated terminal
```
#!/bin/bash

LRED='\033[1;31m'
LPURPLE='\033[1;35m'
NC='\033[0m' # No Color

printf "\t${LRED}light red${NC}\n\t${LPURPLE}light purple${NC}\n"
```
### Expected output

Red and purple and rendered differently

### Actual output

Purple is rendered as red

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What theme are you using? Does it get better if you change the theme?

**Comment by svillar** [comment]
> What theme are you using? Does it get better if you change the theme?

Right, the problem is the theme I'm using (Zenburn). It does not happen with other themes. Thanks!
