### ISSUE TITLE
No audio rendering in IPython

### ISSUE THREAD

**Issue by bliep** [microsoft/vscode#94792]
- VSCode Version: 1.43.2
- OS Version: MacOS 10.15.3

Steps to Reproduce:

1. Run the following code in a IPython cell
2. Observe that the audio is grayed out.

```
import numpy as np
from IPython.display import Audio
Audio(np.random.rand(16000), rate=16000)
```

Does this issue occur when all extensions are disabled?: Yes

There have been numerous reports that the audio (and video) is not working in IPython cells, however I think the root cause are not the missing codecs reported in https://github.com/microsoft/vscode-python/issues/3405 and https://github.com/Microsoft/vscode-python/issues/3456. The example above does _not_ use a codec, just plain samples.

For anyone doing datascience with audio, this bug kills the use of IPython in VSCode.

btw, https://github.com/microsoft/vscode/issues/80196 is tagged wrongly as 'caused by an extension'.

**Comment by RMacfarlane** [comment]
@bliep This comes from the python extension, so please file it there: https://github.com/Microsoft/vscode-python
