### ISSUE TITLE
Terminal tab goes blank after exiting the terminal

### ISSUE THREAD

**Issue by numToStr** [microsoft/vscode#94793]
- VSCode Version: 1.44.0
- OS Version: Manjaro Linux 19.0.2
- Linux Kernel: 5.5.13

### Description
So, I am using [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh) with the [tmux](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/tmux) plugin enabled. When I exit the current terminal, it terminal tab goes blank but didn't close the tab.

This can be replicated by typing `exit` or pressing the `Kill Terminal` icon.
This is my tmux plugin configuration

```sh
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOCONNECT=true
ZSH_TMUX_FIXTERM=true
```

#### This is the first time I am facing this issue

Steps to Reproduce:

1. Use ohmyzsh with tmux plugin enabled
2. Copy & Paste the above tmux plugin config
3. Open terminal inside the vscode and try to exit the terminal

#### Before Exiting
![Screenshot_20200409_191441](https://user-images.githubusercontent.com/24727447/78901988-c1016a80-7a96-11ea-8326-dc8add802ce8.png)

#### After Exiting
![Screenshot_20200409_191514](https://user-images.githubusercontent.com/24727447/78902017-d080b380-7a96-11ea-9403-e5da21fddd72.png)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by numToStr** [comment]
I will check and report back to you.

**Comment by numToStr** [comment]
@Tyriar Is this issue fixed? I am still having this issue.

### Code version
```
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
```

**Comment by Tyriar** [comment]
@numToStr the insiders build I mentioned is 1.45.0
