### ISSUE TITLE
Option to not include new line in paste

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#94797]
When tripple clicking a line and then copy pasting it, the pasted text includes a line ending, therefore the cursor jumps to a new line after paste. If this is the intended behaviour, could we get a setting to turn it off? It gets quite annoying when copy pasting a lot of stuff around and having to delete the new line all the time

![ezgif-5-e61224a61088](https://user-images.githubusercontent.com/75278/78903022-e1233080-7a7a-11ea-8bb4-afa6cf6999bc.gif)

**Comment by ArturoDent** [comment]
Similar to https://github.com/microsoft/vscode/issues/61840

**Comment by Stanzilla** [comment]
@ArturoDent Tried that, sadly did not work as expected.

**Comment by ArturoDent** [comment]
What didn't you like about that macro on SO?

**Comment by Stanzilla** [comment]
It just did not work for me, was not copying the line I marked, but the line after.

**Comment by alexdima** [comment]
This is intentional and consistent with other code editors. 

Please also note that the initial issue is a bit misleading, I believe the gesture referred to is triple click, not double click.

**Comment by Stanzilla** [comment]
@alexdima yup, correct, thanks. And yeah I know it's intended, just wish there was an option to disable it.
