### ISSUE TITLE
vscode not killing child processes

### ISSUE THREAD

**Issue by azumikav** [Microsoft/vscode#948]
when you do child_process.spawn, the new process is a child of Code, but when Code quit the children process do not, is this intended?

**Comment by alexandrudima** [comment]
@azumikav are you spawning processes from an extension?

**Comment by azumikav** [comment]
yes.

**Comment by alexandrudima** [comment]
@azumikav The right think to do here is for VSCode to call `deactivate` on extensions on shutdown and for extensions to clean up on shutdown.

**Comment by alexandrudima** [comment]
With 98473e0e88cecd52ba44551d512efe445b6af11e, VSCode's extension host will now call `deactivate()` if extensions export it and call `dispose()` on `ExtensionContext.subscriptions` on shutdown, then will wait 1s before exiting
