### ISSUE TITLE
Maximized Panel on left breaks editor layout with opened webview

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#94805]
- VSCode Version: 1.44
- OS Version: macOS 10.15.4 

Steps to Reproduce:

> Explorer and actions on left

1. Have two files open in splitview (left|right)
2. Move panel to left
3. Maximize panel

Does this issue occur when all extensions are disabled?: Yes

![Bildschirmfoto 2020-04-09 um 17 00 37](https://user-images.githubusercontent.com/11534760/78909634-1e3ff080-7a84-11ea-8aeb-311554c3a171.png)

**Comment by sbatten** [comment]
I can do similar breakage by splitting (top/bottom) with the panel in its default location.

**Comment by mjbvz** [comment]
@sbatten Is this specific to webviews?

**Comment by sbatten** [comment]
in my testing, yes

**Comment by bpasero** [comment]
Looks bad, moving to April. I think @mjbvz needs to investigate first.

**Comment by bpasero** [comment]
This can still happen:
* sidebar hidden
* markdown source opened with preview split to the side
* maximize panel (from left)
* reload window

=> 🐛 

![image](https://user-images.githubusercontent.com/900690/80724931-b3258f00-8b02-11ea-8225-497af3cd418e.png)
