### ISSUE TITLE
Extension host terminated unexpectedlly

### ISSUE THREAD

**Issue by Abhay123png** [microsoft/vscode#94807]
Issue Type: <b>Bug</b>

Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:30:48.287Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 6.1.7601

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:30:48.287Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B980 @ 2.40GHz (2 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|1.88GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17
discord-vscode|icr|3.13.0
cpptools|ms-|0.27.0
sqltools|mtx|0.21.6
LiveServer|rit|5.6.1

</details>

**Comment by gjsjohnmurray** [comment]
Please disable all extensions, restart VS Code, then enable them one by one until you discover which one crashes the Extension Host (EH) process.

**Comment by RMacfarlane** [comment]
@Abhay123png Can you also copy-paste the output from the "Log (Extension host)" output channel?

**Comment by gjsjohnmurray** [comment]
@Abhay123png based on other reports my top suspect in your list of extensions is LiveServer.

**Comment by gjsjohnmurray** [comment]
#94860 reports antivirus interference with VS Code.

@Abhay123png are you using AV software? If yes, which one? Any sign of it having messed with VS Code files?

**Comment by Abhay123png** [comment]
> Please disable all extensions, restart VS Code, then enable them one by one until you discover which one crashes the Extension Host (EH) process.
 Yea I have done as you said but still not working 
well I have mailed you

**Comment by Abhay123png** [comment]
> @Abhay123png based on other reports my top suspect in your list of extensions is LiveServer.

Disabled all extensions and only enabled code runner but still same problem

**Comment by gjsjohnmurray** [comment]
@Abhay123png  any error messages in the Extension Host log in the Output panel?

**Comment by Abhay123png** [comment]
> Extension Host log in the Output panel

how to open  Extension Host log in the Output panel?

**Comment by Abhay123png** [comment]
> #94860 reports antivirus interference with VS Code.
> 
> @Abhay123png are you using AV software? If yes, which one? Any sign of it having messed with VS Code files?

Quick heal

**Comment by gjsjohnmurray** [comment]
> > Extension Host log


> how to open Extension Host log in the Output panel?

Click on errors and warnings numbers on status bar, even if they are zeroes. This will open the panel. Select its Output tab. Then use dropdown to go to EH log.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/94869#issuecomment-611901305 confirmed Quick Heal "repairs" a VS Code file. Please report this to the AV vendor as a false positive.

**Comment by Abhay123png** [comment]
> > > Extension Host log
> 
> > how to open Extension Host log in the Output panel?
> 
> Click on errors and warnings numbers on status bar, even if they are zeroes. This will open the panel. Select its Output tab. Then use dropdown to go to EH log.

is this what do you want to see? https://cdn.discordapp.com/attachments/610131188086079519/698061362613452850/IMG_20200410_121211.jpg

**Comment by Abhay123png** [comment]
> > > > Extension Host log
> > 
> > 
> > > how to open Extension Host log in the Output panel?
> > 
> > 
> > Click on errors and warnings numbers on status bar, even if they are zeroes. This will open the panel. Select its Output tab. Then use dropdown to go to EH log.
> 
> is this what do you want to see? https://cdn.discordapp.com/attachments/610131188086079519/698061362613452850/IMG_20200410_121211.jpg
@gjsjohnmurray help me

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

**Comment by vj21soni** [comment]
I am also getting same issue, i have removed all extension from VSCode and also uninstall and reinstall VSCode V-1.44 and also disable antivirus from my system, I was using QuickHeal anti virus but now its disable, i have tried many time, last 2 days, but bad luck, can you please let me know what i can do?
