### ISSUE TITLE
Seach not working

### ISSUE THREAD

**Issue by robertconstantin** [microsoft/vscode#94802]
Issue Type: <b>Bug</b>

the search on the workspace that I work it keeps loading without any result

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_7485219|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.11.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.2
vscode-instant-markdown|dba|1.4.4
git-extension-pack|don|0.1.3
githistory|don|0.6.3
gitlens|eam|10.2.1
vscode-codemetrics|kis|1.24.0
vscode-scss|mrm|0.9.0
team|ms-|1.161.0
vscode-yaml|red|0.7.2
salesforcedx-vscode|sal|48.8.0
salesforcedx-vscode-apex|sal|48.8.0
salesforcedx-vscode-apex-debugger|sal|48.8.0
salesforcedx-vscode-apex-replay-debugger|sal|48.8.0
salesforcedx-vscode-core|sal|48.8.0
salesforcedx-vscode-lightning|sal|48.8.0
salesforcedx-vscode-lwc|sal|48.8.0
salesforcedx-vscode-visualforce|sal|48.8.0
prophet|Sqr|1.2.1
sass-indented|syl|1.8.2
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by roblourens** [comment]
Can you give some more details, and see if this guide helps at all? https://github.com/microsoft/vscode/wiki/Search-Issues
