### ISSUE TITLE
fatal error : No such file or directory

### ISSUE THREAD

**Issue by Ewan-K** [microsoft/vscode#94806]
Issue Type: <b>Bug</b>

The "includePath" in c_cpp_properties.json is set as "${workspaceFolder}/**". The location of my souce file is workspace/code.cpp and the location of my header file is workspace/h/code.h. 
The compiler should search all the directory in my workspace recursively(due to my includePath setting), but it didn't.
The funny part is, intellisense can find the header file and it doesn't report errors(red wavy line) before running. The problem only happens when I press F5 and run.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (9.64GB free)|
|Process Argv|C:\Users\25740\Desktop\OOP VScode|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
color-info|bie|0.5.1
bracket-pair-colorizer-2|Coe|0.0.29
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|4.1.1
auto-rename-tag|for|0.1.1
vsc-python-indent|Kev|1.8.1
vscode-view-in-browser|kop|1.0.5
vscode-language-pack-zh-hans|MS-|1.44.2
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
veriloghdl|msh|1.0.5
vscode-css-peek|pra|3.0.2
code-spell-checker|str|1.8.0
vscode-icons|vsc|10.0.0
markdown-pdf|yza|1.4.4

</details>

**Comment by weinand** [comment]
Please file against C++ extension
