### ISSUE TITLE
Nim language icon

### ISSUE THREAD

**Issue by Jamyw7g** [microsoft/vscode#94800]
Issue Type: <b>Feature Request</b>

Add icon support for Nim language.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

**Comment by misolori** [comment]
Please file a request at the [seti-ui repo](https://github.com/jesseweed/seti-ui) as we use that library and don't make any modifications on our side.
