### ISSUE TITLE
Breakpoints are all unverified when debugging extensions if there is no network access

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#9481]
- VSCode Version: 1.4.0-Insiders and 1.3.1
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Open an extension project
2. Add breakpoints to `activate` function
3. Turn off network (Air plane mode), launch the extension from VS Code

If there is network access, the breakpoint is hit succesfully. If not, the breakpoint is never hit. Besides, when there is no network, when you launch the extension, the breakpoint icon on the gutter is red (meaning it's valid) but if you remove it then re-add a breakpoint, the newly added breakpoint is grey and the hint is saying `unverified breakpoint`.

I don't see this problem when debugging nodejs project, it onlys happens with extentions (repro this issue with VSCodeVim, Alex's Vim and vscode-encourage).

**Comment by weinand** [comment]
@rebornix the problem is with remote source maps. With extension host debugging VS Code does not have source maps built in but loads them from a CDN.

**Comment by rebornix** [comment]
@weinand thanks for the info. When there is no network, the breakpoint in output js file is also unverified. I think that's the only thing we need to improve. It sounds reasonale putting source maps in CDN.
