### ISSUE TITLE
`workbench.list.automaticKeyboardNavigation` setting is not respected

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#94818]
When I set `workbench.list.automaticKeyboardNavigation` to false typing while in the file explorer still triggers highlighting/filtering.

Appears to be a regression of https://github.com/microsoft/vscode/issues/68233

**Comment by joaomoreno** [comment]
I can't reproduce in the latest insider version. You forgot to add important details to your issue. Please respect the issue template.

**Comment by akbyrd** [comment]
Does not repro in 1.45.0 insiders.
