### ISSUE TITLE
Auto code completion feature is lost

### ISSUE THREAD

**Issue by partha0047** [microsoft/vscode#94811]
After the march 2020 update the auto completion feature is lost.
Live Serve extension is also not supported in this new update

**Comment by gjsjohnmurray** [comment]
If you disable LiveServer extension do the missing auto completion features start working again?

**Comment by gjsjohnmurray** [comment]
Maybe related to #94807

**Comment by RMacfarlane** [comment]
@partha0047 What programming language are you using?

**Comment by partha0047** [comment]
I'm using html ,css and javascript files.After the new update it says the
extension host terminated unexpectedly. Auto completion feature is also
lost.

**Comment by alexdima** [comment]
Duplicate of #94858
