### ISSUE TITLE
vscode intellisense not catch path when use absolute path with typescript 

### ISSUE THREAD

**Issue by DaoHuyTuan** [microsoft/vscode#94824]
- VSCode Version: 1.44.0
- OS Version: Macos 10.15.4 
- Typescript Version: 3.8.3

**Introduce**: i have been searching for this problem and i was read many issues you guys answer ``need more infomation`` so this time i want create this issues send to you more infomation to solve this problem 1 for all 

Steps to Reproduce:

1. ``npx create-react-app my-app --typescript``
2. ``npm run eject``
3. add this code into ``compilerOptions``
```js 
// tsconfig.json
  "baseUrl": ".",
  "paths": {
    "Images/*": ["Public/images/*"],
  },
```
full file ``tsconfig.json``
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "baseUrl": ".",
  "paths": {
    "Images/*": ["Public/images/*"],
  },
  "include": [
    "src"
  ]
}
```
4. add absolute path to webpack ``resolve.alias``  in``webpack.config.js`` 
``Images: path.resolve(__dirname, "../public/images"),``

```js
// webpack.config.js

module.exports = function (webpackEnv) {
... 
resolve: {
      modules: ["node_modules", paths.appNodeModules].concat(
        modules.additionalModulePaths || []
      ),
      extensions: paths.moduleFileExtensions
        .map((ext) => `.${ext}`)
        .filter((ext) => useTypeScript || !ext.includes("ts")),
      alias: {
        Images: path.resolve(__dirname, "../public/images"),
        "react-native": "react-native-web",
        ...(isEnvProductionProfile && {
          "react-dom$": "react-dom/profiling",
          "scheduler/tracing": "scheduler/tracing-profiling",
        }),
        ...(modules.webpackAliases || {}),
      },
      plugins: [
        PnpWebpackPlugin,
        new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),
      ],
    },
...
}
```

5. copy any image in ``public`` folder to new folder in ``public`` named ``images``
6. go into file ``config/paths.js`` edit ``appSrc`` into  ``appSrc: resolveApp("./"),``
> why need this ??
because i want test absolute path in vscode can suggest outside the ``src`` folder for my use case 
7. in ``App.tsx`` import that image with absolute path ``Images``
```js
import React from "react";
import "./App.css";
import logo from "Images/logo192.png";
function App() {
  return (
    <div className="App">
      <img src={logo} alt="logo" />
    </div>
  );
}

export default App;
```
8. run ``npm start`` 
**Result**: the result is image still display (which mean the config absolute path on webpack is working) but the vscode intellisense not suggest anything 
**Expect**: vscode intellisense suggest file path in absolute path and suggest the list file in folder 

Does this issue occur when all extensions are disabled?: yes
> if same this config but not using typescript vscode show the suggest work perfectly 

**Github**: https://github.com/DaoHuyTuan/vscode-intellisense-problem

**Comment by mjbvz** [comment]
Where are you triggering IntelliSense? In the import path? Could this be coming from an extension? I don't see any suggestions in this case
