### ISSUE TITLE
code-runner.run' not found

### ISSUE THREAD

**Issue by Chimaobi1122** [microsoft/vscode#94829]
Issue Type: <b>Bug</b>

Having a bug command 'code-runner.run' not found after updating my vscode to v1.44.o

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2020M @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.89GB (2.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17

</details>

**Comment by yume-chan** [comment]
It's usually caused by the extension not properly start.

Please check formulahendry/vscode-code-runner#393.

**Comment by gjsjohnmurray** [comment]
In the Output panel please review the log from the Extension Host. Any evidence of errors?

**Comment by Abhay123png** [comment]
> In the Output panel please review the log from the Extension Host. Any evidence of errors?

How to do this?

**Comment by gjsjohnmurray** [comment]
Click on errors and warnings numbers on status bar, even if they are zeroes. This will open the panel. Select its Output tab. Then use dropdown to go to EH log.
