### ISSUE TITLE
Add `list.expandAll` command

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#94820]
There's a `list.collapseAll` but no `list.expandAll`. I find myself wanting this capability when using list views occasionally. I imagine this would deprecate `search.action.expandSearchResults` but would apply to other trees views like the file explorer.

**Comment by akanz1** [comment]
Unfortunately I did not notice your issue here when I opened mine back in April

See https://github.com/microsoft/vscode/issues/95746

I believe both request the same functionality and could/should be merged?

**Comment by akbyrd** [comment]
Good call. https://github.com/microsoft/vscode/issues/88682 is the oldest and the most upvoted. Between the three issues there's likely enough support to cross the mythical 20 upvote mark.
