### ISSUE TITLE
`search.action.revealInSideBar` causes a warning

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#94827]
Not sure what it's supposed to do, but it just ends up showing a warning notification with "cannot read property 'resource' of undefined".

Also, typo in the name? Other commands don't seem to capitalize the 'B'

![image](https://user-images.githubusercontent.com/484784/78932486-68ad7700-7a5c-11ea-9370-57bc6f91903b.png)

Version: 1.45.0-insider (user setup)
Commit: 2225d77536d12fea2eda04930f431a5eb0930bba
Date: 2020-04-09T09:22:11.706Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It's supposed to open that file in the explorer. I see the issue.

**Comment by roblourens** [comment]
Oh, it only worked in the context menu item and never as a keybinding.

**Comment by akbyrd** [comment]
> Yeah I would prefer non-capitalized B but I don't want to change it now if people have set up keybindings for that ID.

Have y'all thought about versioning and auto-upgrading settings and keybindings? Being indefinitely constrained to all past mistakes doesn't seem ideal. Imho, a major consistency pass over context values would be a huge win for usability.

**Comment by roblourens** [comment]
Fixed and I left the ID since looking at other commands it seems that we are already inconsistent.

**Comment by roblourens** [comment]
I think that would be the right way to handle it, but I think these issues are usually quite rare.
