### ISSUE TITLE
Closing brackets between tags

### ISSUE THREAD

**Issue by tvarsis** [Microsoft/vscode#9482]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:
1. Typing `<div></div>` and places the cursor in between. 
2. Insert a { no closing curly brace is inserted and it looks like this `<div>{</div>`. However, if i add a space after and then move the cursor back one step the closing curly brace gets inserted correctly and the result looks like this `<div>{} </div>`

**Comment by formulahendry** [comment]
Agree. This should be fixed in VS Code. PR #9535 is sent.

**Comment by rebornix** [comment]
Let's merge this with https://github.com/Microsoft/vscode/issues/18120 as we already have good explaination there.

**Comment by PascalAOMS** [comment]
Still not fixed in `1.16.0` since the PR was not merged.
Drives me nuts.
