### ISSUE TITLE
HTML snippets not working

### ISSUE THREAD

**Issue by davidgms** [microsoft/vscode#94831]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

My VSCode does not show suggestions, emmets and snippets anymore and i dont know why. I formated my PC months ago and when i was coding again this feature just does not worked.  I searched everywhere how to fix this but without success. Please help?

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 4.15.0-1076-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|7.67GB (0.23GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    94	 25743	code main
    0	     0	 25746	   zygote
    0	    39	 25770	   gpu-process
    0	    71	 25783	   utility
    0	   291	 25794	   window (● index.html.twig - dealersites - Visual Studio Code)
    0	     0	 25838	     /bin/bash
    0	   220	 25865	     watcherService
    0	    16	 25944	     searchService
   12	    47	 25878	   shared-process
    0	     0	 29830	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 29831	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   102	 29800	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● index.html.twig - dealersites - Visual Studio Code)
|    Folder (dealersites): more than 40767 files
|      File types: png(2955) jpg(2731) js(2208) css(1893) php(1635) data(503)
|                  svg(319) scss(290) log(264) twig(228)
|      Conf files: package.json(5) gulp.js(3) makefile(2) settings.json(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
html-class-suggestions|And|1.0.7
jquerysnippets|don|0.0.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
twig-language-2|mbl|0.9.1
vscode-language-babel|mgm|0.0.27
vscode-docker|ms-|1.0.0
sublime-keybindings|ms-|4.0.6
highlight-matching-tag|vin|0.9.6
twig|wha|1.0.2

</details>

**Comment by gjsjohnmurray** [comment]
In the Output panel please review the log from the Extension Host. Any evidence of errors?

**Comment by RMacfarlane** [comment]
@davidgms We've seen a number of reports of antivirus software interfering with the latest release, if you're using Quick Heal, please see the discussion here on how to solve this: https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

If not, has this problem only started happening with the upgrade to 1.44? Can you try temporarily disabling all extensions with the `Developer: Reload with Extensions Disabled` command?

**Comment by djlee0721** [comment]
I just rolled back to Feb release (v1.44) - and the custom CSS snippets are now working but HTML snippets are still no good...

**Comment by octref** [comment]
I see `index.html.twig` file. HTML snippets won't work in TWIG files, unless you mark them as html files with `files.associations`.
