### ISSUE TITLE
Restart frame not working as expected

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9483]
Have the following code:

```js
console.log('hello world');
console.log('hello world 2');
```

Set a breakpoint on the second line, start debugging and once the breakpoint is hit restart frame. Notice that the frame is not restarted, but program hits an entry frame stop and continues till exit

![replayframe](https://cloud.githubusercontent.com/assets/1926584/16950213/5fe2fa46-4dbf-11e6-8f00-4af7cdf736fa.gif)

**Comment by weinand** [comment]
This seems to be a 'restart frame' bug in node < 5.11.
Restart Frame works beginning with 5.11.

**Comment by isidorn** [comment]
We should mention that in the release notes.
