### ISSUE TITLE
Can't format document

### ISSUE THREAD

**Issue by nathantorento** [microsoft/vscode#94836]
Issue Type: <b>Bug</b>

I can't format the document at all? Nothing works. 

![image](https://user-images.githubusercontent.com/44336802/78948172-e5ad1080-7a9d-11ea-9b8d-cc72cbe0e282.png)

Latest version of VSCode. 
Tried disabling all extensions.
Looked at ALL similar threads / bug reports.

Tried all combinations of these: 
- outside of a virtual environment
- within a virtual environment
- right-clicking then pressing format document
- typing the default format document shortcut
- typing a customized format document shortcut
- python.linting enabled and disabled 
- empty settings.json

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 5|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
In the Output panel please review the log from the Extension Host. Any evidence of errors?

**Comment by RMacfarlane** [comment]
Did this work in previous versions of VSCode?

**Comment by nathantorento** [comment]
No errors. Just, nothing happens. No output in the VSCode or computer
terminal either.

**Comment by nathantorento** [comment]
I downloaded VSCode a while back but never actually used it.
When I started it using it for the first time that day and encountered the
formatting error, I checked and my version was already the latest.
