### ISSUE TITLE
"Treat As Filetype" option

### ISSUE THREAD

**Issue by fredjohnston** [microsoft/vscode#94830]
When editing a file without an extension, or just working in an Untitled document, it would be great to say "Treat As Type" and put an extension, such as .py or .txt so that such things as "Toggle Line Comment" would behave in such manner (eg if .py, then Cmd+/ would produce # at start of line(s).  

Often, i REMOTELY edit a file, and having to first SAVE-AS (eg somefile.py), then do the edit, then SAVE-AS back to my non-extension or whatever file, then have to clean up the intermediate file, is a lot of work.

Fred Johnston

**Comment by IllusionMH** [comment]
You can achieve this with `Change Language Mode` command or by clicking on language (most likely Plain Text) in status bar.

Does it solve your problem?

**Comment by RMacfarlane** [comment]
Closing this issue, as `Change Language Mode` sounds like what you are requesting. Please let us know if that is not the case.
