### ISSUE TITLE
Add `.gitignore` file to `.vscode` folder

### ISSUE THREAD

**Issue by vijayphoenix** [microsoft/vscode#94835]
# Problem

VS Code automatically adds a `.vscode` folder which has some config files like `settings.json` etc

It is very problematic when this `.vscode` folder is created in a directory which is also git repository. 
We have to manually add `.vscode` in the `.gitignore` file to avoid them from been tracked by git.

# Proposed solution

Add an additional `.gitignore` file in `.vscode` folder. So, the new directory structure will be:

*  `.vscode`
   *  `.gitignore`
    * `Other files and folders`

Content of this `.gitignore` file.
```
$ !cat .vscode/.gitignore

*
```

This `.gitignore` file will avoid git from tracking `.vscode` files and folders.

If required, I will be happy to help

**Comment by RMacfarlane** [comment]
Hey @vijayphoenix, the `.vscode` folder is meant to be checked in and shared - the `settings.json` it contains is settings configured for the project. It also has debug and task configurations. As such, we do not want it to be automatically ignored by git.
