### ISSUE TITLE
Remove "support-objects" special variables highlighting in JS/TS grammars?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#94837]
**Problem**
The JS/TS grammar includes logic for highlighting specific words for globals such as `Array` and `JSON`

https://github.com/microsoft/vscode/blob/75c625d4218f71703b0766d070f892ced1b1110a/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L3493

I believe these were added to improve editing in cases where you only have basic highlighting. However, it's pretty easy to fool these, such as:

```js
{
    const Array = 1;
    console.log(Array); // Array is still highlighted as if it were the global `Array` here
}
```

With semantic highlighting, I believe we can now reliably detect when we are using a global such as `Array` vs using a local called `Array`

**Question**
@aeschli Can we remove all of these special cases from our text mate grammar and leave this up to semantic highlighting? The only one I'd probably like to keep is `arguments` since that is more like a keyword in modern JS

**Comment by mjbvz** [comment]
Upsides:

- Makes it so the highlighting no longer lies (see cases like `Array` above)

- Simplifies the grammar

Potential downsides:

- Could cause changes to the highlighting people see (if the are used to the existing colors and especially if they have disabled semantic coloring)

- Could cause a more noticeable flash when globals are recolored by semantic highlighting

**Comment by aeschli** [comment]
I would recommend against it. Users are very sensitive on highlighting changes. The swirl is not worth the simplification, given that we already have it.
Yes, semantic highlighting would bring them back, but not all themes have semantic highlighting enabled (yet).

The benefit of semantic highlighting will be to fix the lies...

**Comment by mjbvz** [comment]
ok, I'll leave them for now then
