### ISSUE TITLE
Add configuration (workspace) doesn't open debug configuration list

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#94844]
- VSCode Version: 1.44.0
- OS Version: Win 10 1909, 18363.720

Steps to Reproduce:

1. Open a multi root workspace
2. Launch panel -> Add configuration (workspace)...

Expected to see a dropdown list showing supported debug configurations (just like in single root mode). 
Actual behavior is that only the .code-workspace file gets focus.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Aha, for the the Add configuration (workspace) you would like the debug configuration providers to be called. This is a fair feature request, however not on the immedaite plan thus assigning to backlog.
We would be open to a pr that adds this. If you are intersted let me know and I can provide a code pointer

**Comment by xisui-MSFT** [comment]
@isidorn Sure I'd like to make the change. And it would be great if you can give me some code pointers.

**Comment by isidorn** [comment]
Here's a code pointer https://github.com/microsoft/vscode/blob/6ad9dd426e8ddd22b2e063498af378e28735017c/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L495

Thanks

**Comment by xisui-MSFT** [comment]
@isidorn After looking at the code, I found that the suggestions wouldn't pop up if the "configurations" field doesn't exist in single root mode as well. So I'm planning to add some code to insert launch configure lines when they don't exist. Since I didn't find anywhere in this code base inserting some texts at a certain position into a file, do you have an example (I think settings is already doing something like this)?

**Comment by isidorn** [comment]
@xisui-MSFT If you have an instance of an `editor` you could `editor.getModel().applyEdits` for example.
