### ISSUE TITLE
The editor is in the middle and there is a gap between the two sides

### ISSUE THREAD

**Issue by xiterjia** [microsoft/vscode#94845]
Issue Type: <b>Bug</b>

After upgrading VSC to 1.44, when I display two editors on the left and right, and close one of them, the editor will be centered with a gap on both sides, and restart and reload will not return to normal.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.11.0
px2rem|art|0.0.3
turbo-console-log|Cha|1.4.0
vscode-css-modules|cli|0.2.3
jsrefactor|cms|2.20.6
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.6.3
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.1.1
auto-rename-tag|for|0.1.1
code-runner|for|0.9.17
terminal|for|0.0.10
githd|hui|2.2.4
rest-client|hum|0.23.2
output-colorizer|IBM|0.1.2
autofilename|Jer|0.1.3
vscode-gutter-preview|kis|0.25.0
vscode-language-pack-zh-hans|MS-|1.44.2
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
polacode|pnp|0.3.4
quicktype|qui|12.0.46
vscode-sort-json|ric|1.18.0
sass-indented|rob|1.5.1
partial-diff|ryu|1.4.1
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.6.0
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0
stylus-supremacy|thi|2.13.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
quokka-vscode|Wal|1.0.285
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
material-theme|zhu|3.2.5

(5 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/3360879/78888209-bee9dc80-7a93-11ea-8e96-0538e34249d1.png)

**Comment by yume-chan** [comment]
Looks like you are in the "centered layout" mode, please try to run the `View: Toggle Centered Layout` command to exit.

**Comment by xiterjia** [comment]
Thank you very much, maybe I clicked it by mistake when I clicked to display the "Show Activity Bar"
