### ISSUE TITLE
Regular expression syntax reference

### ISSUE THREAD

**Issue by blueray453** [microsoft/vscode#94843]
Webstorm has regular expression syntax reference: https://www.jetbrains.com/help/webstorm/regular-expression-syntax-reference.html

So, do TextMate: https://macromates.com/manual/en/regular_expressions

It seems to me that regular expression syntax reference is far more crucial for vscode than those as vscode has major inconsistencies in search and replace as mentioned in https://github.com/Microsoft/vscode/issues/31491, https://github.com/microsoft/vscode/issues/36309#issuecomment-338345129, https://github.com/Microsoft/vscode/issues/8635#issuecomment-230318011 and others.

**Comment by roblourens** [comment]
I could probably spell this out in docs but it can basically be assumed to use plain JS regex syntax, there are just a small number of edge cases. But two of your three examples are fixed - we now support multiline search and lookbehind.

**Comment by blueray453** [comment]
@roblourens I think it should be documented what work in search in file and what work in search in files (though in ideal case those should be consistent). If you think it is mostly javascript regex (with just a small number of edge cases like around \r) then the documentation will be a half an hour work. But I highly doubt it as ripgrep fall back to pcre in some cases and do not fall back to pcre in some cases. Moreover you said in https://github.com/microsoft/vscode/issues/12185#issuecomment-611543483 that:

> replacement is implemented in VS Code, not ripgrep.

When someone code a feature, he should also let us know how that code function.

**Comment by roblourens** [comment]
I added some notes to https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support, and I will continue to flesh it out more as I come across more cases. Thanks for prompting me on this.

I don't want to add it to the main documentation because I think that only very advanced users need to worry about this, and our docs are more of a user guide and less of a list of every possible thing that can go wrong. I don't want to scare people away by making it sound complicated :D but I agree that it should be written down somewhere outside of github issues.

**Comment by blueray453** [comment]
@roblourens DuckDuckGO ?!?!

> I don't want to add it to the main documentation because I think that only very advanced users need to worry about this

What do you think about https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar? I had to learn EBNF to decode the syntax. I think documentation reduce complexity not increase it. 

> I don't want to scare people away by making it sound complicated :D

You are scaring a lot of us away be not giving us a proper documentation. Moreover, do you know what is common in previous two quotes: `I don't want to`. We need to realize that there are other people around us as well who might know better. 

This issue is about **regular expression syntax reference**. So I am not sure whether it was appropriate for anyone to close this issue just by writing an incomplete wiki note.
