### ISSUE TITLE
Screen reader gets trapped in Forms Mode when attempting to interact with various tools, gets trapped into Forms Mode on load and cannot use Escape to cancel out of Forms Mode (Accessibility)

### ISSUE THREAD

**Issue by GS-Avaluka** [microsoft/vscode#94847]
- VSCode Version: 1.44
- OS Version: Windows 10
-Screen Reader: JAWS 2019 (Yes, I know you only test with NVDA ... but NVDA has a Forms Mode, as well, and it may be affecting NVDA.)

Steps to Reproduce:
1. Load VSC.
2. As focus goes into Welcome page, Forms Mode is engaged and cannot be removed/disengaged with Escape key as usual.
3. Even if Forms Mode somehow gets disengaged after using a keyboard shortcut from the screen reader, attempting to use keyboard to interact with any button or listbox or link with the enter key seems to just engage Forms Mode and does /NOT/ actually activate the button/tool/link.
4. At this point the only thing I am able to do is Tab and Shift+Tab, along with some various keyboard shortcuts like Ctrl+M to change the tab behavior. I am unable to interact with anything that I tab to, nor can I disengage Forms Mode to browse properly.

Note: I work as a Web Developer for accessibility and, to me, it felt as though there was a parent container with a WAI-ARIA role of "application" somewhere which was essentially stealing focus. There are other roles that engage Forms Mode like this, expecting the control to have coded all keyboard interactions itself.

Does this issue occur when all extensions are disabled?: Yes/No
Was not able to check, as this bug makes VSC entirely useless to me, as I am unable to disengage Forms Mode to be able to use the arrow-keys to browse and interact with the editor as usual.

**Comment by isidorn** [comment]
@GS-Avaluka hi, thanks for filling this issue. We also want to improve JAWS support.
I can not reproduce this with NVDA. I also just installed JAWS and I can not reproduce it.

My steps:
1. Start JAWS (no configuration changed)
2. Start Visual Studio Code
3. Try to interact with Visual Studio Code via keyboard -> all works

What am I doing wrong?

We do have a parent container of the workbench with the `application` role. Code pointer https://github.com/microsoft/vscode/blob/45b2a7e10243677801dc9da34a464b1a15f5df57/src/vs/workbench/browser/workbench.ts#L321

fyi @leonardder for potential NVDA insight

**Comment by GS-Avaluka** [comment]
Hi there,

Thanks for the quick response.

I did some things on my end to see if it may be that I was on JAWS 2019. I updated to the most recent stable version of JAWS 2020 and tried again.

I am still getting the issue where I get trapped in Forms Mode, though I think it may be more in a specific area of the workspace.

Note that I have Forms Mode set to "Manual", which really shouldn't affecta nything - it just means I have to hit an extra keystroke to interact with the lement first before Forms Mode activates. The default is "Auto", which just means as soon as focus goes onto a forms mode-capable control, Forms Mode activates.

Steps:
1. Load Visual Studio Code.
2. The "Welcome" screen pops up. I ear the audio notification that Forms Mode has activated (a kind of bloop.)
3. Ctrl+W to close Welcome screen and enter main workspace page.
4. At this point I am still stuck in Forms Mode, though I've had one or two experiences where Forms Mode releases and lets me use arrow-keys (but this is short lived.)
5. Manually release Forms Mode (there is a keyboard shortcut for this - Numpad + if you have a keypad and are using Desktop keyboard layout ... otherwise you need to use the Keyboard Manager to assign a keyboard shortcut.)
6. Ctrl+End to get to bottom of Workspace.
7. Move upwards with the arrow-keys until you hear a button near the area where Problems are listed - I used "Close Panel" as an example.
8. Hit enter on "Close Panel". Forms Mode activates, locking keyboard access and not able to use Escape to release.

Thanks,
Kristen

**Comment by isidorn** [comment]
Thanks Kristen I still can not repro this. I am not a screen reader user, so I feel like this could best be answered by our accessibility community. Might you want to join our gitter accessibility channel https://gitter.im/Microsoft/vscode-a11y
If yes, I suggest to join and quickly ask your issue. The community might be able to help better than me.
If it turns out to be an issue on the VS Code side I would be happy to try to fix of course.
If you do not want to join the channel let me know and I can consult with some other screen reader users.. Thanks

**Comment by GS-Avaluka** [comment]
Hello,
Apologies for the late reply.

If you could ask other screen reader users, I'd much appreciate it. I may just be not explaining it adequately. As it is, though, 1.44.0 is not useable to me and I'm keeping 1.43.2 installed for now. Which is a shame, as I've not had any issues with accessibility up to this point other than a very minor loss of focus in the editor window sometimes (which was not a huge issue.)

You said you are using role="application" somewhere - do you have a specific reason for using this particular role? Role="application" basically tells the screen reader to relinquish all control to the application, and if you forget to code something with a keyboard interaction it can cause major problems since the screen reader is not handling anything. I've seen usage of role="application" cause the problems I'm having on other sites.

I used to be able to browse VSc's interface like a webpage, which let me use specific screen reaer keyboard shortcuts and arrow-key browsing. Whatever change was made that is causing the issue I am having is locking me into using whatever keyboard interactions you have coded for specific sections and not letting the screen reader react to anything once focus is locked into something. Yes, some actions work, such as tab and shift+tab and some limited arrow movement (I noticed it let me cycle through the buttons in some toolbar with the arrow-keys), but I am no longer able to use Ctrl+End to go to the bottom and view the extension I use for work.

Thanks,
Kristen

**Comment by isidorn** [comment]
@GS-Avaluka I believe the issue is that we introduced the role:application since everything worked fine for you in the previous version. I will ask the question in the community but you could join as well, that would be great.

**Comment by webczat** [comment]
Hmm, linux user here. Generally browse mode (not sure how it's called in jaws) is useful only in some cases. Normally you should be 98% of the time in forms mode and tabbing/shifttabbing, and arrowing through lists. Does this problem make it impossible also to navigate through controls in forms mode? That would be kinda interesting.

**Comment by GS-Avaluka** [comment]
Yes, if you didn't have role="application" in 1.43.2, but added it in 1.44.0 ... that would make it feasible that it is the issue, as it was exactly what I had assumed based on previous experience with this role.

Re: being able to navigate with tab/shift+tab and arrow keys in Forms Mode. Yes, in some situations it works - I did note I was able to use arrow-keys to navigate through a toolbar, etc. /However/, the problem being when it doesn't work ... it doesn't work very very badly. For example - if an extension maybe isn't expecting role="application" and doesn't have it setup that way, or if the 'enter' key is not properly transferring to a "click" action/event (JAWS does this automatically with certain roles like buttons, but won't do it if something with role="application" is on the parent div.)

Role="application" is a very very severe role due to it removing control from the screen reader entirely and really does not need to be used unless in very rare circumstances. Users technically should be able to use Browse/arrow-key navigation in addition to tab/shift+tab as they wish. I was able to use both in the previous version. I liked being able to use tab in some situations, but then be able able to skip to using some fo the shortcut keys JAWS uses (like 'r' to jump between regions to jump to the editor area faster.)

Roundabout way of saying that you shouldn't lock a user into Forms Mode unless absolutely necessary, and role="application" should not be deployed to a parent div of anything big, as then it will lock Forms Mode for every child control regardless of the fact if it was working just fine without role of application.

I assumed you guys were using Chromium-based web container or something similar for the workspace pages, etc., considering I was able to use webpage navigation shortcuts for all of it.

**Comment by isidorn** [comment]
@marcozehe fyi on the `application` role, since I believe we added it based on his recommendation. We can of course remove it if that is needed..
@GS-Avaluka vscode is built on top of Electron which uses Chrome underneath. So we use web technologies for rendering and thus webpage navigation should work.

**Comment by GS-Avaluka** [comment]
If you can remove it, I would recommend you remove it. It really only has a very narrow scope and only if you have an alien widget that does not conform to some other HTML-like element. Even then, it is better to stick to HTML elements if you can, or roles that conform to HTML elements - the screen reader/assitive technology has much better capabilities of knowing what to do with a specific HTML element than it does with role="application".
Here are a couple blog posts regarding role="application" and why it shouldn't be deployed, especially on a <div> element that contains many other widgets that are already conforming properly to HTML:
https://marcozehe.wordpress.com/2012/02/06/if-you-use-the-wai-aria-role-application-please-do-so-wisely/

https://a11yproject.com/posts/how-to-use-application-role/

**Comment by webczat** [comment]
neither nvda nor orca actually lock focus/forms mode. You land in it, but you are not locked in it. Although I believe this could be happening before in older version of one or both, not sure which.
I haven't met an extension requiring browse mode to really navigate, like having clickable entries. Generally orca does not have the behavior of clicking things on enter. The exception is things like html preview/similar stuff where some things could indeed be clickable (pdf preview of latex...).
As for quickly jumping to editor and things like that I believe there is a ctrl+b shortcut that will do that. For other things that require jumping out of forms mode... Doesn't jaws have some kind of separate key that can also be used to switch between modes on demand? Orca has insert+a, nvda has insert+space and it works even if esc or enter would not... Unless it does have such a shortcut and it doesn't work when role=application is used... that's indeed a problem.

**Comment by webczat** [comment]
as for request to remove it... vscode is an app and I navigate it mostly as non webapp unless browse mode is actually useful for specific things, and in that case any form of automatic switching to browse mode gets in my way, as I expect this to behave more like a desktop app except where I specifically need browse mode.

**Comment by MarcoZehe** [comment]
I am torn about this. I wasn‘t the one who recommended the application role in the first place, I recommended to add the role „document“ for some of the children which are web content. But many other parts of the editor are indeed not web content, but rich widgets, so I think the role „application“ has merit here. So the welcome page, for example, should switch to browse or virtual cursor mode automatically since it is wrapped in a „document“ role. The problem before role „application“ was that so many things required focus or forms mode that it became tedious to constantly switch browse mode off. And NVDA handles this very well.

**Comment by isidorn** [comment]
@MarcoZehe you are correct, I checked the older conversations and it was recommended by @leonardder
I am open to making a change, but let's wait for @leonardder feedback.
Also if we do not use the role `application` on the top element, which one should we use if we should use any at all?

**Comment by GS-Avaluka** [comment]
Regardless if it's an application, it's using web application code and it makes sense to leverage screen reader's behavior, not work against it like this.

The extension I use the most actually has links to Download/Upload remote files from a server - the problem I am running into is the fact that JAWS, when you focus or hit 'enter' on something that is forcing Forms Mode, uses 'enter' to turn on Forms Mode. Which ... fine. That seems to work alright if the widget being used is properly coded for it. But many are not. And I can exit Forms Mode manually with JAWS, but this does nothing to force the 'enter' to work on a link I need to click/activate in an Extension I use 100% of the time when using VSC.

I don't mind role="application", but if you have it deployed on a very high level parent div, it really needs to be deployed more selectively around each widget you want to use it with.

**Comment by GS-Avaluka** [comment]
Also - I am not sure how NVDA works, as I exclusively use JAWS, but certain WAI-ARIA roles JAWS will automatically swap to Forms Mode when you focus on it, as it is expected to need it for those things. (I believe things like toolbar, menu, tabs, etc.)

I understand the difficulty of trying to balance needs of many different screen readers, too. I'm not saying role="application" can't be used to streamline things for NVDA, but it'll have to be placed specifically so it only encompasses the widgets you want to use it with, or you'll run into this problem where extensions expecting a web-based interface aren't setup to use 100% Forms Mode and it is difficult to bypass.

**Comment by webczat** [comment]
well. there are indeed some cases where browse mode is more useful... as in, howers. you do ctrl+k ctrl+i and somehow for some weird reason land in focus mode and I have to switch, even though I am now reading things like documentation tooltip or a problem tooltip. Is that also something role=application causes? I specifically chose something that is not in an extension as an example here :)

**Comment by joanmarie** [comment]
> I don't mind role="application", but if you have it deployed on a very high level parent div, it really needs to be deployed more selectively around each widget you want to use it with.

I just said something quite similar a little while ago in #95032.

If we could figure out the containers where screen readers should just stay out of they way (not control navigation; just present results of it) and put `application` on them, that might solve several issues.

**Comment by isidorn** [comment]
Ok. That makes sense to me and it seems like we are getting aligned.
So we will remove the `role=application` from the top level workbench element.

However I do not know where screen readers should stay out of the way. Some potential ideas: 
* the editor - atm it has the `textbox` role but we could potentially put application on its parent
* lists (like the explorer, quick pick widget and most of our view) since we have native up / down navigation. Currently the lists have role `list`, `tree` or `listbox` but we could potentially put role application on their parents

Let me know what you think

**Comment by webczat** [comment]
probably fair. But someone more knowledgeable should likely comment...

**Comment by leonardder** [comment]
Well, as I was the one who introduced the discussion about role application in the first place, I should really mind my words from now on. However, just a thought to start with to clear things up for me.

I actually thought that the application role was in use before I started talking about it it in #93087. According to @isidorn in https://github.com/microsoft/vscode/issues/93087#issuecomment-601676906, application was already used for a top level element, which I confirmed. Wasn't this already the case in 1.43.2 and before, or did I misinterpret this?

**Comment by isidorn** [comment]
@leonardder I was the one who introduced it. You do not have to mind your words, feel free to share ideas and the responsibility is on me to decide what we change on the vscode side and what not. So thanks again for the great feedback and discussions! We did use the role `application` before just on a different element. Not on the top one, but on the one which contains our layout.
I have reverted to that old behavior so we see how it works now.

@GS-Avaluka can you please try this with VS Code insiders from Wednesday and let us know if it is better. Thank you

**Comment by joanmarie** [comment]
> Well, as I was the one who introduced the discussion about role application in the first place, I should really mind my words from now on. However, just a thought to start with to clear things up for me.

For the record, I thought role application at or near the top-most container also made sense given that (as I understand it) most of VSCode should be handled in focus / forms mode. And I think brainstorming on ideas with all stakeholders is a good thing. So please do *not* mind your words.

If @isidorn goes with our ideas, it's his fault. *grins*

**Comment by isidorn** [comment]
fyi @ggordon-vispero

**Comment by akash07k** [comment]
In my opinion too, removing role="application" altogether is not a good idea since it is a desktop app and some of the parts which behave like web content, should have role="document".

**Comment by isidorn** [comment]
@akash07k we did not fully remove the role application, we still set it on the `workbench` HTML element [here](https://github.com/microsoft/vscode/blob/aecef14e24b4c3643bb6025c75819be4a608be1f/src/vs/workbench/browser/layout.ts#L922).
So it is just one level below in the HTML chain where it was previosuly set. Hopefully this has fixed @GS-Avaluka originally issue.

**Comment by akash07k** [comment]
> @akash07k we did not fully remove the role application, we still set it on the `workbench` HTML element [here](https://github.com/microsoft/vscode/blob/aecef14e24b4c3643bb6025c75819be4a608be1f/src/vs/workbench/browser/layout.ts#L922).
> So it is just one level below in the HTML chain where it was previosuly set. Hopefully this has fixed @GS-Avaluka original issue.

Ok, Nice. :-)

**Comment by isidorn** [comment]
Based on user feedback this is fixed now, thus adding verified label.
