### ISSUE TITLE
empty file when Code is launched by jshell

### ISSUE THREAD

**Issue by gigaimage** [microsoft/vscode#94846]
- VSCode Version: 1.44.0
- OS Version: MacOS Catalina 10.15.4

Steps to Reproduce: See attached two screenshots - Vim vs Code. Steps are in screenshots. 

1.  Vim 
![Screen Shot 2020-04-09 at 5 35 01 PM](https://user-images.githubusercontent.com/1184087/78951953-c5268b80-7a88-11ea-8f27-d1ab99376742.png)

2. Code
![Screen Shot 2020-04-09 at 5 23 58 PM](https://user-images.githubusercontent.com/1184087/78951970-d079b700-7a88-11ea-8faa-bab3a622373a.png)

Does this issue occur when all extensions are disabled?: Yes/No : Don't know.

**Comment by bpasero** [comment]
Since I have no knowledge how JShell starts VSCode or how they behave, I am not sure how VSCode can help here. I suggest you report this against that product.

**Comment by gigaimage** [comment]
Thanks! 
Just for the info. JShell is a CL tool bundled in JDK
