### ISSUE TITLE
Check for update yields error of:  "Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode#94849]
- VSCode Version: 1.44.0 (user setup)
- OS Version: Windows 10 (version 1809)

Steps to Reproduce:

1. Initiate "check for update"

Today I was checking for an update to 1.43 and saw this error.  I downloaded the newer version of VS Code from the website, 1.44.0, and installed it.  I tried the "check for update" functionality again, but still saw this issue.  From the Log (Main) Output window is the following:

```
[2020-04-09 14:40:54.083] [main] [info] update#setState idle
[2020-04-09 14:40:54.083] [main] [info] update#ctor - manual checks only; automatic updates are disabled by user preference
[2020-04-09 18:09:02.870] [main] [info] update#setState checking for updates
[2020-04-09 18:09:03.546] [main] [error] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.asJson (C:\MyFiles\Apps\VSCode\resources\app\out\vs\code\electron-main\main.js:364:55)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-04-09 18:09:03.546] [main] [info] update#setState idle
[2020-04-09 18:09:59.366] [main] [info] update#setState checking for updates
[2020-04-09 18:09:59.467] [main] [error] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.asJson (C:\MyFiles\Apps\VSCode\resources\app\out\vs\code\electron-main\main.js:364:55)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-04-09 18:09:59.467] [main] [info] update#setState idle
```

I am using VS Code using the Remote functionality which is ssh into a CentOS machine.

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by EmbeddedBacon** [comment]
@joaomoreno, yes, for this particular machine I am behind a company firewall/proxy.

**Comment by joaomoreno** [comment]
Can you repro on 1.42? https://az764295.vo.msecnd.net/stable/c47d83b293181d9be64f27ff093689e8e7aed054/VSCode-win32-x64-1.42.1.zip

**Comment by EmbeddedBacon** [comment]
@joaomoreno , first, thanks for providing a self contained VSCode so I didn't have to install over my existing installation!  Second, I don't see that particular error when VS Code starts or tried to check for an update.  Though, to update it takes me to the download page.  Although, normally VS Code downloads and will install the update without having to download it manually when it opens the website.

**Comment by joaomoreno** [comment]
Oh so sorry... you are right... a self contained app won't do. You actually have to uninstall and install it from https://az764295.vo.msecnd.net/stable/c47d83b293181d9be64f27ff093689e8e7aed054/VSCodeUserSetup-x64-1.42.1.exe

Could you give it a try?

Related to https://github.com/microsoft/vscode/issues/93595, https://github.com/microsoft/vscode/issues/94862

**Comment by deepak1556** [comment]
@EmbeddedBacon can you launch code v1.44 with `--log-net-log=netlog.json` , perform the update check and attach the generated log file here. Thanks!

**Comment by deepak1556** [comment]
Also can you try our exploration build which comes with a newer runtime https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 and launch it with `--log-net-log=netlogexploration.json` and perform the same steps. Thanks!

**Comment by EmbeddedBacon** [comment]
Hello @joaomoreno and @deepak1556 , I will gather the information and provide feedback a little later today.  Thanks.

**Comment by EmbeddedBacon** [comment]
@joaomoreno, okay, uninstalled current version of VSCode then installed 1.42.1, didn't remove anything else from system so system still had my settings.  When loading or checking for update I didn't see the warning message

![image](https://user-images.githubusercontent.com/42427056/79621197-56b87d80-80c7-11ea-965e-2335563a85a2.png)

**Comment by EmbeddedBacon** [comment]
@deepak1556, I uninstalled version 1.42.1, then installed VSCodeUserSetup-x64-1.45.0-exploration. I launch Firefox, added the proxy info, closed VSCode then relaunch.  I did see the error

![image](https://user-images.githubusercontent.com/42427056/79622105-bf552980-80ca-11ea-9cbf-f55e9f9cf94d.png)

Here is the data captured from the console

C:\Users\xxxxx>"c:\MyFiles\Apps\VSCode\Code - Exploration.exe" --log-net-log=netlogexploration.json

C:\Users\xxxxx> 
Warning: 'log-net-log' is not in the list of known options, but still passed to Electron/Chromium. 
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/
electron/electron/issues/18397
[main 2020-04-17T23:39:47.362Z] update#setState idle 
(node:17612) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1) 
(node:17612) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1) 
(node:12032) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, 
see https://github.com/electron/electron/issues/18397.
(node:12032) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, 
see https://github.com/electron/electron/issues/18397.
(node:12032) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is depr
ecated, see https://github.com/electron/electron/issues/18397.
(node:12032) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is depr
ecated, see https://github.com/electron/electron/issues/18397.
(node:18536) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, 
see https://github.com/electron/electron/issues/18397.
(node:18536) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, 
see https://github.com/electron/electron/issues/18397.
(node:12032) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\oniguruma\build\Release\onig_scanner.node'. This is dep
recated, see https://github.com/electron/electron/issues/18397.
(node:12032) Electron: Loading non-context-aware native module in renderer: '\\?\c:\MyFiles\Apps\VSCode\resources\app\node_modules.asar.unpacked\oniguruma\build\Release\onig_scanner.node'. This is dep
recated, see https://github.com/electron/electron/issues/18397.
[main 2020-04-17T23:40:09.328Z] update#setState checking for updates 
[main 2020-04-17T23:40:09.822Z] update#setState idle 
[main 2020-04-17T23:40:17.407Z] update#setState checking for updates 
[main 2020-04-17T23:40:18.117Z] update#setState idle

**Comment by EmbeddedBacon** [comment]
Uninstalled VSCodeUserSetup-x64-1.45.0-exploration then re-installed 1.44.1.  Encountered the same error, launch VSCode with 

C:\Users\xxxxxx>"c:\MyFiles\Apps\VSCode\Code" --log-net-log=netlogexploration.json

C:\Users\xxxxxx> 
 Warning: 'log-net-log' is not in the list of known options, but still passed to Electron/Chromium. 
[main 2020-04-17T23:55:19.604Z] update#setState idle 
[main 2020-04-17T23:55:19.663Z] update#ctor - manual checks only; automatic updates are disabled by user preference 
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:33640) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:33640) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
(node:31896) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron
/issues/18397 for more information
[main 2020-04-17T23:55:59.567Z] update#setState checking for updates 
[main 2020-04-17T23:55:59.709Z] SyntaxError: Unexpected token < in JSON at position 0 
    at JSON.parse (<anonymous>)
    at t.asJson (c:\MyFiles\Apps\VSCode\resources\app\out\vs\code\electron-main\main.js:364:55)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[main 2020-04-17T23:55:59.713Z] update#setState idle

**Comment by deepak1556** [comment]
Thanks @EmbeddedBacon , its the same issue as https://github.com/microsoft/vscode/issues/94862 just with a different proxy service (micron). 

Can you also do the testing mentioned in https://github.com/microsoft/vscode/issues/94862#issuecomment-615227337 , after you load the page, open the devtools by going to `View -> Toggle Developer Tools` , then go to the `Network` panel
and click export `HAR` file.

**Comment by deepak1556** [comment]
Also the net log trace for the exploration build https://github.com/microsoft/vscode/issues/94849#issuecomment-615512795 is missing from your attachment, what you attached was for version `1.44.1` . Can you also attach this trace. Thanks!

**Comment by EmbeddedBacon** [comment]
@deepak1556, yeah, I didn't realize a log was actually created and was thinking you wanted the log from the console.  It wasn't until I remove 1.45 that I saw a file remained after the uninstall process.  Didn't think much of of it until later.  Also, if I ran the file "main.js" through https://beautifier.io/ and saved the results I don't see the problem.  The size grew, but the error went away.

**Comment by deepak1556** [comment]
Can you reinstall the exploration build and get the new netlog file ? It would help to identify what is the difference in requests.

**Comment by EmbeddedBacon** [comment]
@deepak1556 , I will do that now.  I did notice the recover 2 for 1.44 doesn't seem to have the issue, but I didn't see #93595 or #94862 in the list of changes.

https://github.com/Microsoft/vscode/issues?q=is:issue+milestone:%22March+2020+Recovery+2%22+is:closed

**Comment by EmbeddedBacon** [comment]
@deepak1556, okay, uninstalled 1.44.2 and installed 1.45.  Attached if the log you requested
[netlogexploration.zip](https://github.com/microsoft/vscode/files/4495827/netlogexploration.zip)

**Comment by deepak1556** [comment]
Thanks for the details so far, it was helpful. The root cause is same as  https://github.com/microsoft/vscode/issues/94862 , lets track it there.
