### ISSUE TITLE
Can't resize using the divider of outline view

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#94859]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Drag the outline view into any of the horizontal views (problems, output, debug console, terminal).
2. Cannot resize using the divider like other split views.

VS Code version: Code - Insiders 1.45.0-insider (2225d77536d12fea2eda04930f431a5eb0930bba, 2020-04-09T09:22:11.706Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sbatten** [comment]
@mattacosta this is a WIP and one of the issues we are still working on is the representation of collapsed views. When you drag `Outline` into a panel, it by default shows up as collapsed which is confusing itself. Being collapsed and it not being obvious is why you are seeing this behavior.

To fix, click the header of the `Outline` view that has the `>`. It should expand and allow you to resized much like the sidebar.
