### ISSUE TITLE
git gutter showing up inconsistantly

### ISSUE THREAD

**Issue by aquova** [microsoft/vscode#94851]
When editing a file under git source control, any changes made to a line should be highlighted in the git gutter, however in several of my repos, this has not been happening. However, I am able to make the git gutter appear if I open a file via "Go to Definition" (F12). If Go To Definition opens a file not currently open in the editor, then the newly opened file will display the git gutter. Opening the file via VSCode Explorer or File menu will not show this behavior. 

- VSCode Version: 1.44.0
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open a file under a file under git version control.
2. Edit the file, the git gutter should appear, yet does not.
3. Use 'Go To Definition' to open an unopened file.
4. Edit that file. The git gutter behaves as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Interesting. Can you figure out what is the difference between the repositories in which this works and the ones in which it doesn't?

Can you run `Git: Show Git Output` and see if you find any meaningful output? Namely with letter casing.

Are you editing files in a network location? Or in a path containing a symlink?

**Comment by aquova** [comment]
I haven't been able to see any rhyme or reason for when it works and when it doesn't. I looked at a few of my repos this morning, which several different language files (Python, Rust, Lua, Shell, PHP). All of them on my Ubuntu machine were not showing the git gutter. Opening the files with or without a .code-workspace had no affect, only the F12 option as previously mentioned. All of these are saved on my local disk and using symlinks vs no symlinks had no affect. The git sidebar also doesn't update automatically on a change, but if I go in and manually tell it to refresh, then it updates appropriately.

Here is the output of `Git: Show Git Output`. It does look a bit odd, as it is making several calls for `git rev-parse --show-toplevel`

```
Looking for git in: git
Using git 2.20.1 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: /home/aquova/git/agba
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
```

I did check out two of the repos on my Macbook, which is the same VSCode version and has the same settings.json. The git gutter seemed to be working correctly on the same files.

**Comment by AliabbasMerchant** [comment]
I am facing a similar issue. Have noticed that it occurs while opening folders under symlinks.

**Comment by joaomoreno** [comment]
Symlinks are not supported yet with git.

Pinging @aquova to check again for repro status.

**Comment by AliabbasMerchant** [comment]
Okay. But it is in the roadmap, I believe?  
If yes, I am willing to give it a shot over this week, and see what I can come up with.  
Should I do so?

**Comment by joaomoreno** [comment]
Here is the issue: https://github.com/microsoft/vscode/issues/5970

 I suggest starting with `good first issue` or `help wanted` issues instead.

**Comment by aquova** [comment]
I just double checked with and without opening via a symlink. There is no git gutter when I open a workspace through a symlink, however it does seem to be working when I open via the actual file path.
