### ISSUE TITLE
Outline view symbol icons are no longer colored

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#94855]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open up a file with a method.
2. See that the cube icon in the outline view is no longer purple.

VS Code version: Code - Insiders 1.45.0-insider (2225d77536d12fea2eda04930f431a5eb0930bba, 2020-04-09T09:22:11.706Z)
OS version: Windows_NT x64 10.0.18362

**Comment by misolori** [comment]
@bpasero @aeschli any idea why in OSS the color token rules are ordered differently than from our builds? See below for outline symbol icons/colors, `codicon-symbol-class` is ordered incorrectly in our build:

## OSS 

![image](https://user-images.githubusercontent.com/35271042/79012485-4169af00-7b1b-11ea-9cc2-5319a7bda0f0.png)

## Insiders

![image](https://user-images.githubusercontent.com/35271042/79012595-7ece3c80-7b1b-11ea-93b4-7e8cc06aa7b1.png)

I can get around this by placing an `!important` on the rule but that introduces other issues in other areas where we don't want color (like the activity bar).

**Comment by what2003** [comment]
same issue ,mac catelina 10.15.2 (19C57)

**Comment by bpasero** [comment]
@misolori you might want to ping @alexdima but I think our build is collecting all CSS rules into one file and I don't think the order will match with what you see when running out of sources. In general your CSS rules cannot be order dependent.

**Comment by alexdima** [comment]
That is correct, CSS rules across files is not guaranteed to be ordered in any meaningful way.
