### ISSUE TITLE
v1.45 broke Remote SSH

### ISSUE THREAD

**Issue by totszwai** [microsoft/vscode#94856]
Issue Type: <b>Bug</b>

1.44 works, just tested. But after updating to 1.45 Remote SSH just times out and will not show the prompt for password. You can only see the password prompt when it reaches the configured timeout.

VS Code version: Code - Insiders 1.45.0-insider (2225d77536d12fea2eda04930f431a5eb0930bba, 2020-04-09T09:22:11.706Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Probably #94816
