### ISSUE TITLE
v1.44.0 broke git.

### ISSUE THREAD

**Issue by sumitparakh** [microsoft/vscode#94858]
- VSCode Version: 1.440
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open any project which has git initialized.
2. You'll notice that the git toolbar is unable to detect it and ask to initialize repository(which is already initialized)

Does this issue occur when all extensions are disabled?: No

Message like this appears:-

![image](https://user-images.githubusercontent.com/4236211/78957791-f1332280-7b03-11ea-94ec-d509953034e6.png)

**Comment by sumitparakh** [comment]
Just noticed that most of the things are not working in this version 

![image](https://user-images.githubusercontent.com/4236211/78958424-a87c6900-7b05-11ea-8b76-3be82a5a8ba6.png)

**Comment by gjsjohnmurray** [comment]
Probably #94807.

Are you using AV software? If yes, which one? Any sign of it having messed with VS Code files?

**Comment by sumitparakh** [comment]
I'm using Quick Heals. But it works better with 1.43

**Comment by gjsjohnmurray** [comment]
Did Quick Heals quarantine or delete a VS Code file when you updated to 1.44 and tried using it?

**Comment by sumitparakh** [comment]
It was blocking extensionHost file. I've excluded it from Virus detection list and it is working now.

**Comment by Abhay123png** [comment]
> It was blocking extensionHost file. I've excluded it from Virus detection list and it is working now.

@gjsjohnmurray @sumitparakh  I have removed vs code from quick hill av pro virus detection but still same problem

**Comment by sumitparakh** [comment]
@Abhay123png That's weird. 
This is how i excluded this file (check screenshot) and it worked. Make sure that after excluding this file, you restart extension host or try to reinstall vscode again.

![image](https://user-images.githubusercontent.com/4236211/78973941-7d5a3f80-7b2e-11ea-9170-dade018018f8.png)

**Comment by Abhay123png** [comment]
> @Abhay123png That's weird.
> This is how i excluded this file (check screenshot) and it worked. Make sure that after excluding this file, you restart extension host or try to reinstall vscode again.
> 
> ![image](https://user-images.githubusercontent.com/4236211/78973941-7d5a3f80-7b2e-11ea-9170-dade018018f8.png)

I use quick heal av pro and I added like this : - https://cdn.discordapp.com/attachments/610131188086079519/698081818137591868/IMG_20200410_133711.jpg

**Comment by sumitparakh** [comment]
@Abhay123png Before excluding this file. Do following things in the same order:-

1) Close vscode 
2) Restore that file from Quick Heal (needs to be done)
> Open "**Quarantine & Backup**" 
> Click **View Files** 
> Search **extensionHostProcess.js** in the list 
> Select that file and click **Restore**.

![image](https://user-images.githubusercontent.com/4236211/78976176-45a1c680-7b33-11ea-88bf-4348a56f3575.png)

3) Add that file to exclusion list(which you've already done).

**Comment by Abhay123png** [comment]
> @Abhay123png Before excluding this file. Do following things in the same order:-
> 
> 1. Close vscode
> 2. Restore that file from Quick Heal (needs to be done)
> 
> > Open "**Quarantine & Backup**"
> > Click **View Files**
> > Search **extensionHostProcess.js** in the list
> > Select that file and click **Restore**.
> 
> ![image](https://user-images.githubusercontent.com/4236211/78976176-45a1c680-7b33-11ea-88bf-4348a56f3575.png)
> 
> 1. Add that file to exclusion list(which you've already done).

Thanks dude , It worked for me 
@sumitparakh @gjsjohnmurray

**Comment by Sjaynish** [comment]
> It was blocking extensionHost file. I've excluded it from Virus detection list and it is working now.

But how to do it sir!!! Will you please give me steps..

**Comment by Malaya2184** [comment]
go to the quick heal
->file folders
->exclude file folder from scanning
->add file i.e C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js
->save changes...
It is working perfectly....

**Comment by mrJapu** [comment]
Same problem with vscode 1.44.1 update

**Comment by rayeesh1986** [comment]
Thanks for the solution.

**Comment by varunvenky99** [comment]
Thank you :)
