### ISSUE TITLE
Can't use SSH

### ISSUE THREAD

**Issue by weaver712** [microsoft/vscode#94850]
ssh链接远程机器，只要弹出输入密码框，就会同时弹出链接超时的错误框出现

**Comment by yume-chan** [comment]
Translation:

> # Can't use SSH
>
> While connecting to remote machine via SSH, at the same time the password input dialog appear, the connection timed out error dialog will also pop up.

**Comment by gjsjohnmurray** [comment]
If you are using 1.45-insider then this is maybe #94816
