### ISSUE TITLE
Update: Proxy settings are ignored

### ISSUE THREAD

**Issue by keelung-yang** [microsoft/vscode#94862]
Issue Type: <b>Bug</b>

This bug existed in v1.43.
But after uninstalling v1.43, removing .vscode in my home directory, and Code in AppData, and then install v1.44 refreshly, still failed to check for updates.

![image](https://user-images.githubusercontent.com/20385450/78960915-20f12300-7b22-11ea-9a51-9e3ceba83c78.png)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by davidptwong** [comment]
Same here with 1.44. Update and install extension worked fine. Once bypass the corporate proxy, the problem was gone. 

2020-04-14 17:11:35.735] [main] [error] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.asJson (C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:364:55)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by joaomoreno** [comment]
@keelung-yang Are you behind a proxy? It seems you are.

**Comment by keelung-yang** [comment]
> @keelung-yang Are you behind a proxy? It seems you are.

yes

**Comment by joaomoreno** [comment]
Can you bypass the proxy for `update.code.visualstudio.com`?

**Comment by keelung-yang** [comment]
> Can you bypass the proxy for `update.code.visualstudio.com`?

No. proxy settings are setted by our IT team. Anyway, it should not crash.

**Comment by joaomoreno** [comment]
It does not crash, it reports an error.

Is this something new? For how long have updates worked for you before this error appeared?

**Comment by keelung-yang** [comment]
> It does not crash, it reports an error.
> 
> Is this something new? For how long have updates worked for you before this error appeared?

I don't think you need such info, since I've posted here 2 versions of vscode, and @davidptwong have posted souce lines exactly.

BTW, you can setup proxy to recure it by yourself. It's very easy to recur.

**Comment by davidptwong** [comment]
@joaomoreno 
I tested with 1.43.2 same problem
I did not test all versions in between but 1.41.1 (https://code.visualstudio.com/updates/v1_41) worked

**Comment by joaomoreno** [comment]
@davidptwong Can I ask you to test 1.41.1 right now? https://az764295.vo.msecnd.net/stable/26076a4de974ead31f97692a0d32f90d735645c0/VSCode-win32-x64-1.41.1.zip

Let me know how it goes, thanks.

**Comment by davidptwong** [comment]
@joaomoreno , your version worked OK

**Comment by joaomoreno** [comment]
@chrmarti @deepak1556 It seems electron broke some proxy stuff, I saw quite a few people complaining about this.

**Comment by deepak1556** [comment]
@keelung-yang @davidptwong can you launch code v1.44 with `--log-net-log=netlog.json` , perform the update check and attach the generated log file here. Thanks!

@joaomoreno this issue is different and also seems to be specific to windows, some version of the system proxy configuration is not respected, net log should reveal the issue.

**Comment by keelung-yang** [comment]
@deepak1556 
[netlog.json.log](https://github.com/microsoft/vscode/files/4492397/netlog.json.log)

**Comment by deepak1556** [comment]
Thanks @keelung-yang 

I don't see any issues with the proxy connection, pac endpoints are resolved and requests are completed.

<img width="667" alt="Screen Shot 2020-04-17 at 4 08 59 AM" src="https://user-images.githubusercontent.com/964386/79563269-4e2d5c00-8061-11ea-9d9d-c9a4db3f7a70.png">

But interesting bit is that the response to https://update.code.visualstudio.com/api/update/win32-x64/stable/2aae1f26c72891c399f860409176fe435a154b13 endpoint has a `content-type: text/html` which maybe why the json parse was failing. 

@joaomoreno  can we add some tracing info to log what response was received ?

@chrmarti do you have any other debugging suggestions ?

**Comment by keelung-yang** [comment]
@deepak1556  Our proxy provider is [zscaler](https://www.zscaler.com/). I'm not sure whether @davidptwong is using the same proxy.

But after uninstalling v1.44 and removing C:\\Users\\someone\\.vscode, I installed v1.41.1 and upgrade it to v1.44.2 by "Check for updates". And then, I checked it again, this issue fired again.

**Comment by deepak1556** [comment]
Yup this could be due to some proxy handling changes from electron/chromium as there was a version bump between 1.41 and 1.43. 

But before tracking that down, I would like to understand what response is sent from your proxy. In the netlog trace I see that all /GET requests to any JSON endpoint are returned with type `text/html`.

**Comment by keelung-yang** [comment]
@deepak1556 
```json
{
    "url": "https://az764295.vo.msecnd.net/stable/ff915844119ce9485abfe8aa9076ec76b5300ddd/VSCodeSetup-x64-1.44.2.exe",
    "name": "1.44.2",
    "version": "ff915844119ce9485abfe8aa9076ec76b5300ddd",
    "productVersion": "1.44.2",
    "hash": "4c207b5a6fd200f5c658bc975770db087abc2a26",
    "timestamp": 1587054337564,
    "sha256hash": "6479735184be6c3a2357ddae47743e85035c85cf4973854f0e78b8b0487dd8ed",
    "supportsFastUpdate": true
}
```

**Comment by deepak1556** [comment]
Can you try our exploration build which comes with a newer runtime https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 and see if the issue still happens there ?

**Comment by keelung-yang** [comment]
> Can you try our exploration build which comes with a newer runtime [#94074 (comment)](https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209) and see if the issue still happens there ?

No error ocurred on "Check for updates"

**Comment by deepak1556** [comment]
Great thanks!

One last testing, can you paste the output of loading https://gist.github.com/deepak1556/51a9d6e639906b3333d8edff1143ab17 into https://github.com/electron/fiddle/releases/tag/v0.14.0 and use electron version 7.1.11.

**Comment by keelung-yang** [comment]
Sorry. I'm off already. And no proxy used in home.

**Comment by deepak1556** [comment]
No problem, when you get back on the proxy please provide the about test result and also please perform `--log-net-log=netlog.json` with the exploration build. 

Thanks for testing info so far!

**Comment by keelung-yang** [comment]
@deepak1556 Here is netlog.json
[netlog.json.log](https://github.com/microsoft/vscode/files/4500836/netlog.json.log)

**Comment by chrmarti** [comment]
@keelung-yang Could you install https://az764295.vo.msecnd.net/insider/03a7223ee2a086bbcf028801da9370d5deff5093/VSCodeUserSetup-x64-1.45.0-insider.exe and try updating that while running with `--log-net-log=netlog.json`? If it doesn't work, could you check what is in the console? (`Help` > `Toggle Developer Tools`)

**Comment by s-kocher** [comment]
Electron v7.2.3 for current vs code version is may be enough (faster than v8 upgrade) ?
https://github.com/electron/electron/releases/tag/v7.2.3
```
Release Notes for v7.2.3
Fixes
Security: Ensure proxy object is created in the correct context a9bead2
```

**Comment by keelung-yang** [comment]
@chrmarti FYI.
[netlog.json.log](https://github.com/microsoft/vscode/files/4513355/netlog.json.log)

```shell
 [main 2020-04-22T01:42:12.910Z] update#setState idle
(node:12228) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12228) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12228) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12228) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:4940) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:4940) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
[main 2020-04-22T01:42:26.159Z] update#setState checking for updates
[main 2020-04-22T01:42:26.164Z] Error: net::ERR_NO_SUPPORTED_PROXIES
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
[main 2020-04-22T01:42:26.169Z] update#setState idle
[main 2020-04-22T01:42:42.913Z] update#setState checking for updates
[main 2020-04-22T01:42:42.922Z] Error: net::ERR_NO_SUPPORTED_PROXIES
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
[main 2020-04-22T01:42:42.924Z] update#setState idle
```

**Comment by deepak1556** [comment]
Thanks @keelung-yang 

The netlog shows that there is a change is proxy config that bypasses the initial proxy connection.

<img width="1385" alt="Screen Shot 2020-04-21 at 9 23 09 PM" src="https://user-images.githubusercontent.com/964386/79940346-55b08480-8416-11ea-86e6-24ab4a212ad2.png">


Looked further and this change was due to the setproxy api call we make https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L609

```
setProxy({
  proxyRules: '',
  proxyBypassRules: '',
  pacScript: ''
})
```

An empty config to setproxy, resets everything and tells the network stack to use direct connections.
@chrmarti can we protect against that ? That should fix the `net::ERR_NO_SUPPORTED_PROXIES` error.

**Comment by chrmarti** [comment]
This should only trigger if the `http.proxy` user setting or one of the `HTTP_PROXY`, `HTTPS_PROXY` or `NO_PROXY` environment variables is set. @keelung-yang Do you have one of these set?

(The idea behind this is that an empty value should be set when the user clears their `http.proxy` setting. This should not trigger if the setting is not set during startup. I'm adding 
 a trace log entry now.)

**Comment by keelung-yang** [comment]
@chrmarti I've set these three XXX_PROXY environment variables and no proxy settings in vscode.

**Comment by chrmarti** [comment]
@keelung-yang What do you have these variables set to? (It is new in 1.45 that we use these to configure Electron's network library.)

**Comment by keelung-yang** [comment]
@chrmarti FYI.
![image](https://user-images.githubusercontent.com/20385450/79947031-bfc33b00-84a3-11ea-931b-60ba5b23df31.png)

**Comment by chrmarti** [comment]
@deepak1556 It looks like setProxy doesn't handle the case where there are credentials in the URL. It might be best to just not call it in that case.

@keelung-yang Could you unset all 3 variables and retry? (Only for testing, I'm working on a fix.)

**Comment by keelung-yang** [comment]
@chrmarti I renamed them and reinstall vscode v1.45 for insiders. It updated successfully. But I've to keep these environment viriables which used by other softwares, such as python's pip.

[vscode_v1.45_insiders_netlog-no-proxy.zip](https://github.com/microsoft/vscode/files/4514382/vscode_v1.45_insiders_netlog-no-proxy.zip)

Our IE browser's proxy is setted by our IT teams. Maybe that's why vscode updated successfully even no XXX_PROXY envirionment variables are setted.

After installing
```shell
 [main 2020-04-22T07:04:00.822Z] update#setState idle
(node:11088) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:11088) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:11088) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:11088) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:13184) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:13184) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
[main 2020-04-22T07:04:12.631Z] update#setState checking for updates
[main 2020-04-22T07:04:13.113Z] update#setState downloading
[main 2020-04-22T07:04:55.968Z] update#setState updating
[main 2020-04-22T07:05:18.989Z] update#setState ready
```
After updating
```shell
 [main 2020-04-22T07:06:15.598Z] update#setState idle
(node:17052) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:17052) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:17052) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:17052) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:6576) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:6576) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
[main 2020-04-22T07:06:22.145Z] update#setState checking for updates
[main 2020-04-22T07:06:22.611Z] update#setState idle
```

**Comment by chrmarti** [comment]
@deepak1556 It looks like you were right on the forwarding of headers somehow playing into this.

@keelung-yang There will be a fix in tomorrow's Insiders build, the update should work for you with that also with the environment variables set.

**Comment by deepak1556** [comment]
> It looks like setProxy doesn't handle the case where there are credentials in the URL. It might be best to just not call it in that case.

@chrmarti oh yeah I completely forgot about that case, its something that chromium explicitly decided not to support https://bugs.chromium.org/p/chromium/issues/detail?id=16709, ignoring the setproxy api is a perfect solution for this.

> It looks like you were right on the forwarding of headers somehow playing into this.

Nice, might be able to verify with a proxy that relies on authentication headers. I will put together something later this week. But good to know this is finally pinned down :)

**Comment by chrmarti** [comment]
@keelung-yang Could you check if this is fixed in 1.45 insiders also with the environment variables set?

**Comment by keelung-yang** [comment]
> @keelung-yang Could you check if this is fixed in 1.45 insiders also with the environment variables set?

No error reported.

**Comment by chrmarti** [comment]
Thanks! Marking verified.

**Comment by keelung-yang** [comment]
@chrmarti On 1.45 I always got:
```shell
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (6758 KB)  Done!
Downloading package 'ClangFormat (Windows)' (794 KB)  Done!
Downloading package 'Visual Studio Windows Debugger' (13813 KB)  Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```
I'm not setting proxy in settings.json but in system environment variables. I also changed _Proxy Strict SSL_ to disabled, but still not works.

**Comment by alexravenna** [comment]
I'm suffering from this problem as of a few days now even though I'm using Insiders 1.45:
![image](https://user-images.githubusercontent.com/29532881/81538555-2b941780-936f-11ea-90a5-d6242b65d62d.png)

![vs_code_insiders_proxy](https://user-images.githubusercontent.com/29532881/81538851-9cd3ca80-936f-11ea-97ff-dea96c6670b0.gif)

I'm behind a corporate proxy so I have to have to have these environment variables set (HTTP_PROXY, HTTPS_PROXY, NO_PROXY). Any ideas?

It's a bit silly that this has disabled the possibility for VS Code Insiders to update itself 😅 .

**Comment by chrmarti** [comment]
@keelung-yang @alexravenna Is the proxy using some kind of authentication and do the environment variables include username and password?

Does it work when you clear the environment variables before launching VS Code?

**Comment by alexravenna** [comment]
> @keelung-yang @alexravenna Is the proxy using some kind of authentication and do the environment variables include username and password?
> 
> Does it work when you clear the environment variables before launching VS Code?

1. No, the environment variables in my case are just URLs pointing to my company's proxy server, they contain no authentication information.
2. I renamed the variables in system settings (I'm working under Windows, as you can see in my screenshot above), so they shouldn't be set when VS Code starts...and I still have the problem ☹️ .

**Comment by chrmarti** [comment]
@alexravenna Could you open a new issue? For the new issue: Does Chrome/Chromium work on your machine? What type of proxy is it (I see `ERR_NO_SUPPORTED_PROXIES` mentioned with socks.)

@keelung-yang Did the original problem come back or is the error you mention in your last comment new?

**Comment by keelung-yang** [comment]
@chrmarti It works now. Here are details:

- Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
