### ISSUE TITLE
Python IntelliSense not working

### ISSUE THREAD

**Issue by eax32** [microsoft/vscode#94864]
Issue Type: <b>Bug</b>

I have a workspace with separate python projects, all of them have symlinked folder with another python code. After openning 2-3 python files from different fodler IntelliSense stops working for previous oppened files.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3403)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.77GB free)|
|Process Argv|-psn_0_446573|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.34
python|ms-|2020.3.71659
Go|ms-|0.13.1
back-n-forth|nic|0.2.1

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Please reopen this on the python extension: http://github.com/Microsoft/vscode-python
