### ISSUE TITLE
Allow use of captured regex group in files-to-include and files-to-exclude fields of global search

### ISSUE THREAD

**Issue by daravi** [microsoft/vscode#94861]
In global search pane, one can use regex to search for something. You can also use the captured group in the "replace by" field. However, currently it is not possible to use these captured groups in the "files to include" and "files to exclude" fields.

Example use case:
I want to be able to edit all #include lines in different modules so that:
```
// file: module1/file1.h
#include "moduel1/file2.h" // want to replace with #include "file2.h"
// file: module2/file1.h
#include "module1/file2.h // don't want to replace this
```

**Comment by roblourens** [comment]
Sorry I don't understand why you wouldn't set "files to include" to "module1" or something, can you give an example of how this would work? It seems like you are asking for something self-referential becuase you have to decide which files to search in before you can search in them.

**Comment by daravi** [comment]
Hi roblourens thanks for your response. Because it can be module1 or any moduleN. It's just that the filename and the string have to match. You are right that it is self-referentiual but I think it is possible. Essentially I want to only accept the results if the matched group name appears in a certain way in the filename.
```
// file module1/a1.h
#include "module1/a1.h" // change to #include "a1.h"
#include "module2/b1.h // don't change
--------------------------------------------------
// file module2/b1.h 
#include "module1/a1.h // don't change
#include "module2/b1.h // change to #include "b1.h"
```
So if the feature was available I would do:
Search(regex mode): #include "(.+?)/\(w+?.h)"
Replace: #include "$2"
Files to include: $1

**Comment by roblourens** [comment]
Ok, I see the concept but it's not really practical to implement it with the way search works right now, sorry.
