### ISSUE TITLE
Possible to use `auditd` instead of `inotify` to watch file changes in Linux?

### ISSUE THREAD

**Issue by PantherJohn** [microsoft/vscode#94865]
I wonder if we will be able to use a custom file system watcher for `vscode` instead of the built-in `inotify`? `inotify` has a huge performance issue when it comes to large directory structures. ~~[`fanotify`](https://lwn.net/Articles/339253/)~~/`auditd` seem to be better alternatives.

**Comment by bpasero** [comment]
Yes, possible, but currently we have not enough resources to work on a new file watcher. For reference, we are using:
* [Chokidar](https://github.com/paulmillr/chokidar) on Linux if you open a single folder
* [NSFW](https://github.com/Axosoft/nsfw) on Linux if you open a multi root folder

I suggest you post this as enhancement to these libraries.
