### ISSUE TITLE
JSX formatter removes space between sentences in component plain text content.

### ISSUE THREAD

**Issue by joseph-iussa** [Microsoft/vscode#9486]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open a new file and save it somewhere as test.jsx.
2. Add the following content to the file: `<div>Sentence one. Sentence two. Sentence three.</div>`
3. Format the file.
4. The file will be altered to: `<div>Sentence one.Sentence two.Sentence three.</div>`

This also happens with question marks and exclamation points at the end of sentences.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript#9857

**Comment by joseph-iussa** [comment]
Can this issue be opened again? Microsoft/TypeScript#9857 has been closed.

**Comment by dbaeumer** [comment]
@joseph-iussa do you have any additional extension install. Can you reproduce this with starting code from a terminal passing `--disable-extensions`

**Comment by dbaeumer** [comment]
OK. I was still able to reproduce this on 1.8.10. I will annotate the TS bug can close this again.
