### ISSUE TITLE
Context menu callback function on custom panel receive an unexpected object in VSCode 1.44

### ISSUE THREAD

**Issue by SLdragon** [microsoft/vscode#94872]
Hi, team
In VSCode 1.44, context menu call back function would receive a object like below:
{
   isTrusted:"true"
}

Our context menu settings is like below:
```
"menus":{
   "view/title":[
      {
         "command":"azure-iot-toolkit.updateDistributedTracingSetting",
         "when":"view == iotHubDevices",
         "group":"azure-iot-toolkit-4@1"
      }
   ]
}
```

![image](https://user-images.githubusercontent.com/5545529/78969056-a384dd00-7b38-11ea-88aa-4e96683d50a8.png)

In previous version, it just received null

Is this by design or just a bug? It break our extension because we use this parameter to determine where it triggered.

**Comment by jrieken** [comment]
> In VSCode 1.44, context menu call back function would receive a object like below:

How about repro steps?

> Is this by design or just a bug? It break our extension because we use this parameter to determine where it triggered.

Generally, your extension must be fit for gracefully handling *any kind* of parameter, using the parameter to determine the trigger location is flawed.

**Comment by sandy081** [comment]
I cannot repro it with our sample here - https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample

Please provide us the repro.

**Comment by hbenl** [comment]
I stumbled across this issue as well with the Test Explorer extension.
Here's how to reproduce with the tree-view-sample:
* Remove [this line](https://github.com/microsoft/vscode-extension-samples/blob/663836611c7ee03f21433d7a347e2909e213c6cc/tree-view-sample/package.json#L163) in `package.json` (it doesn't happen when you set `"group": "navigation"`)
* Change [this line](https://github.com/microsoft/vscode-extension-samples/blob/663836611c7ee03f21433d7a347e2909e213c6cc/tree-view-sample/src/extension.ts#L24) to `vscode.commands.registerCommand('jsonOutline.refresh', offset => jsonOutlineProvider.refresh(offset));` - the expectation would be that `offset` will be `undefined`
* Set a breakpoint [here](https://github.com/microsoft/vscode-extension-samples/blob/663836611c7ee03f21433d7a347e2909e213c6cc/tree-view-sample/src/jsonOutline.ts#L27)
* Start the extension in the debugger, open the "JSON OUTLINE" view and select "Refresh" from its main menu

Voila:
![Screenshot_2020-04-14_18-38-10](https://user-images.githubusercontent.com/16060807/79250640-41511280-7e7f-11ea-94b9-f227acf5b384.png)

> your extension must be fit for gracefully handling any kind of parameter

\<rant\>
Sorry, but that is just close to impossible - what if I get a parameter that looks very similar to what I expect but is subtly different? The amount of validation that extension authors would have to do _every single time they interact with VS Code_ is just crazy.
A public API should be well-defined and not throw random stuff at anyone interfacing with it and telling them "you figure it out yourself, good luck with that".
\</rant\>

**Comment by jrieken** [comment]
> A public API should be well-defined and not throw random stuff at anyone interfacing with it and telling them "you figure it out yourself, good luck with that".

[`export function registerCommand(command: string, callback: (...args: any[]) => any, thisArg?: any): Disposable;`](https://github.com/microsoft/vscode/blob/8cad3f29a18742d776dbef0f1cb1a95ed026fb02/src/vs/vscode.d.ts#L7059) - I read a clear `...args: any[]` which is well defined and it means, it can be anything. Obviously we don't call this with random stuff but via the `executeCommand`-API any extension can invoke this command, any user can bind this to a keybinding etc etc

> Sorry, but that is just close to impossible - what if I get a parameter that looks very similar to what I expect but is subtly different?

Really? You are expecting objects from your domain, right? How about an instance-of check and if that fails do nothing or, if possible, have a default.

**Comment by hbenl** [comment]
> via the executeCommand-API any extension can invoke this command, any user can bind this to a keybinding etc etc

I don't expect the commands in question to be called "from outside", i.e. they should only by called from my own code or by VS Code's tree implementation. Of course I can't enforce this, but the fact that they don't show up anywhere in the docs and are excluded from the command palette should be a strong hint that these are considered internal and shouldn't be relied on in any way by others.

> I read a clear `...args: any[]` which is well defined and it means, it can be anything

Of course command arguments can be anything *in general*, but I would still expect to be able to rely on how VS Code's tree implementation calls commands. Otherwise extensions will break unnecessarily (even if they do so gracefully, the functionality would still become inaccessible).

> How about an instance-of check

... this is exactly what I ended up doing - I only realized *after* writing my rant that `instanceof` provides the perfect solution in this case (because I expect objects from my domain).

**Comment by SLdragon** [comment]
thank you @hbenl for your steps to repro the issue. 

Hi, @jrieken , my question is what's the purpose of this parameter _{ isTrusted: true}_? Only triggered from the context menu would contain this parameter, however, if I triggered from command palette, it would be null, if it is by design, please add some document about this parameter.

**Comment by jrieken** [comment]
> Hi, @jrieken , my question is what's the purpose of this parameter { isTrusted: true}

There is none and shouldn't be there -> ping @sandy081

**Comment by sandy081** [comment]
I really can't see this `{isTrusted: true}` with the given steps

<img width="985" alt="image" src="https://user-images.githubusercontent.com/10746682/79469518-8fd9ea80-8000-11ea-90c9-d9ac19f45486.png">

@jrieken Do you think if extensions can inject these parameters some how when commands are executed?

**Comment by jrieken** [comment]
No, there is no way to inject this. The {isTrusted: true} smells like markdown command links...

**Comment by sandy081** [comment]
It seems we need assistance from users that how this is getting added

**Comment by hbenl** [comment]
> I really can't see this `{isTrusted: true}` with the given steps

That's because you're using a Mac. I just checked and I can't reproduce it on a Mac either, but on Linux and Windows I can.

**Comment by sandy081** [comment]
@alexr00 Can you please try to repro and see where the unexpected args are coming from?

**Comment by alexr00** [comment]
I do see the arg:
![image](https://user-images.githubusercontent.com/38270282/79977940-65c07680-849f-11ea-8c22-78653261647f.png)

**Comment by alexr00** [comment]
The action bar `onClick` passes a `MouseEvent` as `context` here: 
https://github.com/microsoft/vscode/blob/fd85f8d631c8f6edded8cac46e6533f7903bb44b/src/vs/base/browser/ui/actionbar/actionbar.ts#L192-L192
That contains the `isTrusted` and it get's passed all the way through to the command.

**Comment by sandy081** [comment]
@bpasero any insights ?

**Comment by bpasero** [comment]
Is this maybe an issue with native contextmenu vs custom context menu? Does that make any difference?

To be clear: when running a extension command via context menu we are now passing `{isTrusted: true}` and before we did not? I only see this string being used with markdown?

**Comment by sandy081** [comment]
Yes, we were not passing this before. 

@alexr00 Can you please help in checking with native & custom context menu?

**Comment by itowlson** [comment]
I'm hitting this in the Kubernetes extension.  A command on the title bar of a custom view that was previously being invoked with no argument is now being invoked with this `{ isTrusted: true }` value and it has broken our users.  https://github.com/Azure/vscode-kubernetes-tools/issues/741  I can provide repro details if it would be helpful.

**Comment by alexr00** [comment]
When I set `"window.titleBarStyle": "native"` I do not get `{isTrusted: true}`

**Comment by jrieken** [comment]
@sbatten This seems to be an issue with custom menus and we should make sure we fix this for the next release.

**Comment by sandy081** [comment]
Thanks @alexr00 for checking this.

**Comment by sbatten** [comment]
@bpasero @jrieken I don't see how this could have been introduced in 1.44, so please review my fix. Based on the comment [here](https://github.com/microsoft/vscode/issues/55921#issuecomment-412708978) from long ago, I have removed the passing of the event used to create the action context altogether from both native and custom menus. This means only actions that provide a context will get one.

**Comment by bpasero** [comment]
I was about to comment and then saw https://github.com/microsoft/vscode/issues/55921#issuecomment-412757167 which is exactly what I still think. Passing the event as context into actions is bogus imho, so I like this change. It is hard though to find any code that relies on the event being passed in...
