### ISSUE TITLE
RPM does not work with RHEL 6.7

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#9487]
The RPM for RHEL 6.7 x64 does not work as it fails dependency checks.  The spec file for the rpm specifies glibc >= 2.15 while 2.12 is the latest thats available in RHEL 6.  I'll be opening a PR for the fix...

/cc @davebachmann

**Comment by jsloyer** [comment]
PR submitted with the fix

**Comment by Tyriar** [comment]
This check was added as RHEL 6 did not work, at least when built on our build system. This check is better than the ambiguous error that follows without it on distros derived from red hat 6.

You can see https://github.com/Microsoft/vscode/issues/3603 and https://github.com/Microsoft/vscode/issues/1056 for some back story on this, as well as our requirements page https://code.visualstudio.com/docs/supporting/requirements

**Comment by jsloyer** [comment]
@Tyriar is there any reason why you need 2.15 of glibc instead of 2.12?

**Comment by Tyriar** [comment]
@jsloyer that requirement was there before I joined the team so I'm not sure exactly. All my testing running on the latest RHEL6 at the time crashed vscode immediately. Are you running it on RHEL 6.7 without any problems?

**Comment by davebachmann** [comment]
@Tyriar it appears to be wanting a newer version of libnotify than RHEL 6.7 has so is not starting. 
error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

I only have  libnotify.so.1 from libnotify.x86_64 0.5.0-1.el6

**Comment by Tyriar** [comment]
@davebachmann unfortunately I don't have cycles to invest in this. PRs are welcome if you can improve compatibility with RHEL6, I don't think just downgrading the glibc dep version will be enough though.

**Comment by jsloyer** [comment]
Myself and @davebachmann are looking into it.

**Comment by jsloyer** [comment]
@Tyriar it seems vscode depends on libnotify4 but its not called out as a dep, I couldn't find a reference to it in the code base except in the debian build file.
