### ISSUE TITLE
Default theme not supported in settings anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94876]
Running out of sources:

![image](https://user-images.githubusercontent.com/900690/78972809-ecc03700-7b0e-11ea-92a7-a03edb0e5d0d.png)

**Comment by vainamov** [comment]
Happens to me with all color and icon themes installed. 
Also the items in the IntelliSense window and Go To Symbol popup have lost all of their color, which might be related to this. (See screenshots below)

<details><summary>VS Code Information</summary>

- Version: 1.45.0-insider (system setup)
- Commit: c12bd56a8886f31e353a45f5846f0a35a52f908e
- Datum: 2020-04-10T05:44:09.656Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- Betriebssystem: Windows_NT x64 10.0.18362
</details>

![grafik](https://user-images.githubusercontent.com/11841072/79000687-5d864400-7b4d-11ea-9b8d-c5bb2f5cf6d8.png)
![grafik](https://user-images.githubusercontent.com/11841072/79000728-755dc800-7b4d-11ea-9902-6f0b48003cc4.png)

**Comment by aeschli** [comment]
@vainamov I don't think that's related. I also can't see any colors missing. Can you file a new issue? Please annotate which theme your are using.

**Comment by aeschli** [comment]
@vainamov Your issue is a dup of #94855
