### ISSUE TITLE
Unused variable not grayed out

### ISSUE THREAD

**Issue by daichuchu70** [microsoft/vscode#94875]
打开淡化未使用的代码,定义的变量未被使用,变量名为什么不置灰呢,vue文件也是这样

**Comment by RMacfarlane** [comment]
> 打开淡化未使用的代码,定义的变量未被使用,变量名为什么不置灰呢,vue文件也是这样
>Open the code to dilute unused, the defined variable is not used, why the variable name is not grayed out, so is the vue file

@daichuchu70 
- What version of VSCode is this?
- Can you share the code that has this problem?
