### ISSUE TITLE
Feature : Multi-line status bar

### ISSUE THREAD

**Issue by cangSDARM** [microsoft/vscode#94870]
I use a lot of plugins, which makes the content of statusbar cut and becomes incomplete.
Like this:
<img width="1430" alt="截屏2020-04-10 14 19 40" src="https://user-images.githubusercontent.com/20441896/78968331-cf06c800-7b36-11ea-9d64-121e22983460.png">

I hope that users can control the number of lines, or simply drag the status bar like windows' taskbar.
Thanks!

**Comment by RMacfarlane** [comment]
@cangSDARM One thing you can do is right click the statusbar and hide the things you don't want to see, does that help at all?

**Comment by cangSDARM** [comment]
But for me, the purpose of so many plugins is just to see. I don’t think there is anything wrong with proposing as a feature.

**Comment by bpasero** [comment]
I think more realistic is https://github.com/Microsoft/vscode/issues/6651 and https://github.com/Microsoft/vscode/issues/35744

**Comment by cangSDARM** [comment]
I think that is also a solution and very helpful. Thanks

**Comment by shouyang** [comment]
Still would love to see this for portrait orientated monitor users.

**Comment by chavlji** [comment]
You mean neatly and clean like this? (custom CSS)

![Uploading Screenshot 2022-09-09 at 13.11.57.jpg…]()

**Comment by peter-kehl** [comment]
Hi @chavlji. The custom CSS you've used for your screenshot
- could it be applied with https://github.com/be5invis/vscode-custom-css?
- could you share the CSS, please? (The screenshot shows only a tiny portion.)
Thank you in advance.

**Comment by ylazy** [comment]
@peter-lyons-kehl This issue can't be solved using custom CSS. I tried. It's possible to split the status bar to two part or wrap it, but it also affect other panels. E.g. accordions will not work property. Because the responsive layout is controlled by javascript and css in a complicated way, so we can't use some simple js/css to solve this.
