### ISSUE TITLE
emmet abbreviation

### ISSUE THREAD

**Issue by mohammed634** [microsoft/vscode#94884]
- [ ] Issue Type: <b>Bug</b>

 my emmet is not working .i tried so many times .i re-installed the program still it wasnt working

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
emmet-jss|car|1.0.0
bracket-pair-colorizer|Coe|1.0.61
vscode-typescript-next|ms-|3.9.20200409
LiveServer|rit|5.6.1
vscode-jss-snippets|vis|0.2.2
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by RMacfarlane** [comment]
@mohammed634 Can you describe exactly what you are doing? What happens and what do you expect to happen?
