### ISSUE TITLE
source control doesn't show repositories

### ISSUE THREAD

**Issue by robertnicjoo** [microsoft/vscode#94881]
Issue Type: <b>Bug</b>

I can't get my repositories in source control

### Screenshot

![Capture](https://user-images.githubusercontent.com/8672823/78975084-8ef71380-7b3d-11ea-92c1-2d1dce17f480.PNG)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|9.91GB (4.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-tailwindcss|bra|0.2.0
vscode-eslint|dba|2.1.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vscode-firefox-debug|fir|2.7.2
vscode-ionic-snippets|fiv|2.1.0
kotlin|fwc|0.2.11
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
csharpextensions|jch|1.3.1
dotenv|mik|1.0.1
csharp|ms-|1.21.16
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
laravel-blade|one|1.20.0
material-icon-theme|PKi|4.0.1
polacode|pnp|0.3.4
vue-i18n|thi|1.2.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #94807 is relevant. An antivirus product is affecting a key 1.44 file.

**Comment by robertnicjoo** [comment]
@g-arjones so what should i add to my anti virus? **note** i only use windows default defender as anti virus didn't install any anti virus software.

**Comment by gjsjohnmurray** [comment]
@robertnicjoo then I doubt that your problem is caused by AV.

**Comment by gjsjohnmurray** [comment]
Maybe try reload with all extensions disabled. There is a Command Palette item to do that.

**Comment by robertnicjoo** [comment]
I installed VS Code again and disable/enable GIT extension. Now is working
