### ISSUE TITLE
'Preferences Sync' cannot be disabled.

### ISSUE THREAD

**Issue by septsea** [microsoft/vscode#94888]
Issue Type: <b>Bug</b>

1, Open VS Code Insiders.
2. Open the Command Palette.
3. Type 'sync off'. Click 'Preferences Sync: Turn Off' (or just click the option if it is shown).
4. Click 'Turn Off'.
5. Reload the window.
6. Note that 'Preferences Sync' is still 'enabled'.

![test1](https://user-images.githubusercontent.com/57337516/78981428-80ffbd80-7b52-11ea-8ddd-cad5ba92160d.gif)

VS Code version: Code - Insiders 1.45.0-insider (c12bd56a8886f31e353a45f5846f0a35a52f908e, 2020-04-10T05:44:09.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Looks like this is caused by this commit - 9f1aa3c9feecd04a79d22fd6752ba14a83b48f1b.

It enabled sync automatically in insiders

**Comment by sandy081** [comment]
@RMacfarlane  Thanks for fixing
