### ISSUE TITLE
Git on network drive broken after upgrade to 1.44.0

### ISSUE THREAD

**Issue by limenet** [microsoft/vscode#94882]
- VSCode Version: 1.44.0
- OS Version: Windows 10.0.18363

Steps to Reproduce:

1. Upgrade to 1.44.0
2. Open a project located on a network drive (e.g. `Z:\project-name` which points to `\\code.swift\code\project-name`)
3. Modify a file, e.g. `.npmrc`
4. Switch to Source Control
5. Observe
    1. The file cannot be added/diffed etc.
    2. The filename shown contains the network drive letter and/or the project name

When using the latest Insider (from Apr 09) with no extensions, the behavior is similar but slightly different:
1. The file can be added/diffed
2. The file cannot be unstaged

It appears that the first backslash in the path (after `Z:`) is discarded as is the `project-name` portion.

As implied by the title, the issue only occurs for the network drive projects and not for local projects on drive `C:\`. In those cases, the Git integration works like it did in 1.43.x and there is no smaller and greyed-out path portion visible next to the filename either.

Does this issue occur when all extensions are disabled?: Yes

Please let me know if you need any further information and Happy Easter!

**Screenshots**

(all taken using the same file)

1.44.0

![image](https://user-images.githubusercontent.com/474329/78976595-c43c3b00-7b16-11ea-98f2-8fafa4451c2e.png)

![image](https://user-images.githubusercontent.com/474329/78976731-11201180-7b17-11ea-8a17-1e100bafdaf2.png)

Insider

![image](https://user-images.githubusercontent.com/474329/78976624-d7e7a180-7b16-11ea-9da8-67e17578bcbe.png)

![image](https://user-images.githubusercontent.com/474329/78976654-e930ae00-7b16-11ea-84a6-5439140836f4.png)

Git Log:

```
> git ls-files --stage -- z:project-name\.npmrc
fatal: z:project-name\.npmrc: 'z:project-name\.npmrc' is outside repository at '//code.swift/code/project-name'
> git ls-files --stage -- z:project-name\.npmrc
> git branch
fatal: z:project-name\.npmrc: 'z:project-name\.npmrc' is outside repository at '//code.swift/code/project-name'
> git reset -q HEAD -- z:project-name\.npmrc
fatal: z:project-name\.npmrc: 'z:project-name\.npmrc' is outside repository at '//code.swift/code/project-name'
> git ls-files --stage -- z:project-name\.npmrc
fatal: z:project-name\.npmrc: 'z:project-name\.npmrc' is outside repository at '//code.swift/code/project-name'
> git ls-files --stage -- z:project-name\.npmrc
fatal: z:project-name\.npmrc: 'z:project-name\.npmrc' is outside repository at '//code.swift/code/project-name'
```

**Comment by eamodio** [comment]
@limenet I can't seem to reproduce this myself, but I could simulate the behavior you were seeing if there was a rogue trailing backslash -- so I've made a change that should hopefully resolve it. Can you please try out Monday's insiders build and see if the issue is resolved for you? Thanks!

**Comment by limenet** [comment]
@eamodio thank you for your quick fix!

Now the error messages don't appear anymore and it mostly works but vscode (Insider build from this morning) appears to be confused about the file location:

1. Open Insider
1. Drag & drop the project on the network drive (same as in the initial report)
1. Modify text file `.npmrc`

Git detects the change but lists the file under its full path and when clicking the "open file" icon it also opens it at the full path instead of the relative path respective to the workspace root:

![image](https://user-images.githubusercontent.com/474329/79216691-ea7f1500-7e4d-11ea-91a3-26db4076a9ca.png)

The first tab is from when I opened the file from the workspace, the second one from "open file" in the Git sidebar. Both tabs refer to the same file although the first (workspace) tab uses the drive letter `Z:\` and the second uses the network path `\\code.swift\...`.

**Comment by limenet** [comment]
/verified

Thank you very much!

**Comment by eamodio** [comment]
@limenet is the issue you mentioned here: https://github.com/microsoft/vscode/issues/94882#issuecomment-613367236 gone now too?

**Comment by limenet** [comment]
@eamodio yes, that issue is now gone as well!

**Comment by eamodio** [comment]
Awesome, thanks!

**Comment by eamodio** [comment]
Verify steps:

- Open a project located on a network drive (e.g. Z:\project-name which points to \\code.swift\code\project-name)
- Modify a file, e.g. .npmrc
- Switch to Source Control
- Observe
  - The file can be added/diffed etc.
  - The filename shown contains a relative path (not a wrong absolute path)

**Comment by sbatten** [comment]
Needed to update to git version `2.26.1.windows.1`, I was on `2.25.x`

**Comment by klaasnicolaas** [comment]
No idea if it is allowed to respond to a closed issue.

I have the same problems (can no longer make or stash commits) and use version 1.44.2 of VScode and Git version 2.26.2. Only when I downgraded Git to 2.24.x, I got no more errors with "is outside repository at ...".
