### ISSUE TITLE
Assertion Failed: argument is undefined or null

### ISSUE THREAD

**Issue by palashmalviya** [microsoft/vscode#94886]
Issue Type: <b>Bug</b>

Showing this message while clicking on any option the vscode,please help me out.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 5.3.0-46-generic

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/94931
