### ISSUE TITLE
Should problems view icon toggle sidebar?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#94889]
1. Drag problems view to the Side Bar
1. Click on the problems icon in Status Bar
1. It hides the View but doesn't toggle Side Bar

![demo](https://user-images.githubusercontent.com/9638156/78982220-5863cd80-7b2a-11ea-8894-ec9ab1df6971.gif)

VS Code version: Code - Insiders 1.45.0-insider (c12bd56a8886f31e353a45f5846f0a35a52f908e, 2020-04-10T05:44:09.656Z)
OS version: Windows_NT x64 6.2.9200

**Comment by roblourens** [comment]
For me, it still hides the view but not the sidebar

**Comment by sbatten** [comment]
@roblourens is the problems view by itself? or with other views?

**Comment by roblourens** [comment]
Oh, got it. I thought I had to be misunderstanding something.
