### ISSUE TITLE
The total number of search results changed when viewing one of the results

### ISSUE THREAD

**Issue by yoyo837** [microsoft/vscode#94880]
Issue Type: <b>Bug</b>

Please watch the recording

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.2
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|4.2.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.7.2
auto-close-tag|for|0.5.6
code-runner|for|0.9.17
todo-tree|Gru|0.0.171
vscode-codeowners|jas|1.1.1
vscode-language-pack-zh-hans|MS-|1.44.2
Go|ms-|0.13.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
vetur|oct|0.24.0
rust|rus|0.7.0
code-settings-sync|Sha|3.4.3
vscode-stylelint|sty|0.84.0
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|10.0.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

</details>

Video: [QQ20200410-160533-HD.mp4.zip](https://github.com/microsoft/vscode/files/4460518/QQ20200410-160533-HD.mp4.zip)

**Comment by JacksonKearl** [comment]
Hey sorry I haven't gotten to this, have you been able to reproduce this on a recent build of vscode?

**Comment by yoyo837** [comment]
It cannot be reproduced in version: 1.47.0, it may have been fixed. Thanks.

**Comment by JacksonKearl** [comment]
Thanks for reporting back :)

**Comment by yoyo837** [comment]
A similar problem appeared again...


[Screen record video-Jul-30-2020 12-37-10.mp4.zip](https://github.com/microsoft/vscode/files/4998811/Screen.record.video-Jul-30-2020.12-37-10.mp4.zip)

**Comment by JacksonKearl** [comment]
Thanks, the video helps.

**Comment by yoyo837** [comment]
May be related to the Chinese regular expression matching boundary.

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/88881612-716fc600-d262-11ea-98ce-ec6888ceff4c.png)

**Comment by JacksonKearl** [comment]
If you search within the editor (Cmd+F) for those strings, do you get results?

**Comment by yoyo837** [comment]
Thanks quickly reply. Pls See the new video. 

The query result is unstable, sometimes it is 4, 5, 6, 7, and it is different when I open the target file and when I don’t open it.

[Screen record video Jul-31-2020 09-43-17.mp4.zip](https://github.com/microsoft/vscode/files/5004578/Screen.record.video.Jul-31-2020.09-43-17.mp4.zip)

**Comment by JacksonKearl** [comment]
cc @roblourens @rebornix Looks like possible difference between ripgrep/JS regex on Chinese characters. Do you know if there's something open for this?

**Comment by rebornix** [comment]
I can't reproduce the issue locally, @yoyo837 could you please share the document in which you ran CMD+F but didn't get any result?

**Comment by yoyo837** [comment]
Sorry for my poor English, do you mean your need my project source code?

**Comment by yoyo837** [comment]
[some code files include 课时.zip](https://github.com/microsoft/vscode/files/5008324/some.code.files.include.zip)

characters: `课时`, Match whole word(Alt + W)

**Comment by roblourens** [comment]
Is this what I'm supposed to see? The second folder is empty

![image](https://user-images.githubusercontent.com/323878/89069707-84e56480-d328-11ea-90ba-51c8d9886835.png)

I can't repro this in the first folder. Do you have `files.encoding` set or any other settings?

**Comment by yoyo837** [comment]
There is only one folder in the zip file, which is part of the code file and can reproduce the search issue


Now in my Windows, it can also be reproduced, just like the mac computer in video record:
![image](https://user-images.githubusercontent.com/6134547/89070477-a8032900-d3a7-11ea-9424-75326ca4720c.png)

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

It has a newer version of the tool we use for search

**Comment by yoyo837** [comment]
Insiders version got the same issue.

Version: 1.48.0-insider
commit: c9a2f78283b6e5ef708fb8869e2a5adaa476e42f
Date: 2020-07-31T05:52:44.330Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by roblourens** [comment]
Oh, I didn't notice the "match whole word" option. This option is not very smart and can't understand what a "word" is in other languages. If you surround `课时` with spaces then it will match in the editor too. The reason the result first shows up then disappears is because it is matched by ripgrep but not by the editor. Some more details here: https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support but we can't really improve this, sorry for the confusion

**Comment by yoyo837** [comment]
No matter whether it is smart or not, shouldn't the results of search in the editor and global search be the same?

![image](https://user-images.githubusercontent.com/6134547/89125579-1106b000-d512-11ea-95e3-eb5da140a6bb.png)

This makes me a little frustrated, whatever, thanks for your explanation and patience.

**Comment by roblourens** [comment]
Ideally yes, but there will always be some odd edge cases like this one
