### ISSUE TITLE
python debug not working 

### ISSUE THREAD

**Issue by fangleigit** [microsoft/vscode#94894]
Issue Type: <b>Bug</b>

when I am using vs code to do python debugging, I always encounter the issue that F10 does not work during debugging. 
The issue might occur at different line of the code. I can provide more details if you needed

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (4.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular2|joh|9.1.2
vscode-docker|ms-|1.0.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.71659
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.6
java|red|0.59.1
vscode-yaml|red|0.7.2
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

</details>

**Comment by weinand** [comment]
@fangleigit what do you mean by "F10 does not work during debugging"?
What do you expect F10 to do and what is not working?

**Comment by fangleigit** [comment]
I should expect the step by step debugging. This issuse has gone when I update to the latest (Mar 2020) version
