### ISSUE TITLE
Hotkey to navigate between old and new code panel in the diff view

### ISSUE THREAD

**Issue by phmngocnghia** [microsoft/vscode#94892]
Location: diff panel (Image bellow)
![image](https://user-images.githubusercontent.com/36730355/78984008-87d90100-7b4f-11ea-82d8-713d794773b6.png)

Feature:
- Hotkey to switch between the old, and the new code panel in the diff view

Note:
- I used to create a feature request that got closed due to: it's not `request that is often asked for`. If you guys decide to reject it, would be really appreciate if your guys provide some technical information to help me to implement it.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/95068

**Comment by siddharth-krishna** [comment]
@phmngocnghia if you want this feature, please upvote #95068 :)
