### ISSUE TITLE
Bash terminals becoming unresponsive (Mac)

### ISSUE THREAD

**Issue by mark-feeney-sage** [microsoft/vscode#94895]
Issue Type: <b>Bug</b>

I have dotnet core projects loaded and I'm running dotnet test commands. I frequently end up with Terminal windows frozen and not accepting any typing after the commands have run. I have to kill the terminal window and create a new one each time.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-test-explorer|for|0.7.1
latex-workshop|Jam|8.8.0
docomment|k--|0.1.9
csharp|ms-|1.21.16
mssql|ms-|1.9.0
code-spell-checker|str|1.8.0
latex-utilities|tec|0.3.6

</details>

**Comment by Tyriar** [comment]
Are there any errors in devtool console (via help menu) when this happens? I haven't seen anything like this personally.

Your settings.json file would also be helpful.
