### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Nis41** [microsoft/vscode#94890]
Issue Type: <b>Bug</b>

When I open vs code it displays an error Extension host terminated unexpectedly and displays two buttons open developer tools and restart extension host but the error remains as it is while pressing the restart button. and all the extensions also not working.

I had uninstalled all the extension and clear the code folder in AppData and also cleared the extension folder as well then I reinstalled the vs code but the problem is as it is.

please help me out.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.2.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.17
python|ms-|2020.3.71659
cpptools|ms-|0.27.0

</details>

**Comment by gjsjohnmurray** [comment]
Maybe caused by antivirus. See #94807

**Comment by Nis41** [comment]
> Maybe caused by antivirus. See #94807

Yes, You are right....My Problem is solved now...Thanks a lot
