### ISSUE TITLE
Can't open or even create any files

### ISSUE THREAD

**Issue by Rompol** [microsoft/vscode#94899]
Issue Type: <b>Bug</b>

Hi there, something happened and I can't opene or create any files, always getting the same error:
Unable to open 'Untitled-1': Cannot read property 'other' of null.
Tried to uninstall everything and install back several times

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Rompol** [comment]
**That's what I see when I run code --verbose:**
[main 2020-04-10T15:48:07.064Z] Sending some foreground love to the running instance: 15152
[main 2020-04-10T15:48:07.074Z] Sending env to running instance...
[main 2020-04-10T15:48:07.178Z] Sent env to running instance. Terminating...
[main 2020-04-10T15:48:07.179Z] Lifecycle#kill()

**here is what I see in console:**
Unable to open 'Untitled-1': Cannot read property 'other' of null.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
doHandleOpenEditorError @ editorGroupView.ts:984
(anonymous) @ editorGroupView.ts:912
async function (async)
(anonymous) @ editorGroupView.ts:901
doShowEditor @ editorGroupView.ts:899
doOpenEditor @ editorGroupView.ts:882
openEditor @ editorGroupView.ts:818
openEditor @ editorService.ts:511
run @ fileActions.ts:144
triggerAndDisposeAction @ actions.ts:120
async function (async)
triggerAndDisposeAction @ actions.ts:105
(anonymous) @ actions.ts:95
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
open @ openerService.ts:46
open @ openerService.ts:161
async function (async)
open @ openerService.ts:154
open @ walkThroughPart.ts:192
(anonymous) @ walkThroughPart.ts:170

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Rompol** [comment]
This one works for me with no issues...

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Rompol** [comment]
![error](https://user-images.githubusercontent.com/49106757/79038246-3163d500-7bd8-11ea-8693-0745bccf8bff.png)
The same 
I also thought that it might be because of extensions (because it happened after I installed some). So I also tried to disable all of them and then do delete (folder), but also didn't help :(

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by Rompol** [comment]
Cool, now it works, now I can create and open files. But what would be the way to use extensions again? :)

**Comment by bpasero** [comment]
@Rompol just to make sure, with the command I gave you, you also used a fresh data dir. To verify this is really just about extensions, can you also try this: `code --disable-extensions` without the `--user-data-dir` argument.

**Comment by Rompol** [comment]
No, then it's not working, the same error

**Comment by bpasero** [comment]
@Rompol can you go back to the model of `code --disable-extensions --user-data-dir <directory> where <directory>` but this time try to copy as much of the environment over to reproduce as possible:
* settings
* keybindings
* extensions
* folder/workspace you open

To see if it isolates with that other user data folder.

**Comment by Rompol** [comment]
Not sure if I understand correctly what I should do here... can you please clarify?

**Comment by bpasero** [comment]
@Rompol you should be able to start 2 instances of VSCode, one as usual (with the issue) and one with the `--user-data-dir`. Then from the broken version can you copy over the settings (in its JSON form) to see if you can get the good version into a state where it gets broken? Trying to figure out what is causing this as it does not seem to be so easy to understand.

**Comment by Rompol** [comment]
@bpasero I'm getting this message _Unable to open 'settings.json': Cannot read property 'other' of null._
when I'm trying to open json files in settings. 
Tried to uninstall it (one more time) and install back, the same issue

**Comment by bpasero** [comment]
@Rompol any chance you could share the contents of your settings file? Particular I wonder about `editor.quickSuggestions` and possibly this being a duplicate of https://github.com/microsoft/vscode/issues/94931

**Comment by Rompol** [comment]
@bpasero ookay, finally I found the settings.json file I needed, I copied settings from vs-insider settings file, and now everything is working. Probably I did something wrong with this file... But anyway, it's working now, thanks for the great support!
