### ISSUE TITLE
Changes to files within hidden folder are not detected

### ISSUE THREAD

**Issue by mcgodan** [microsoft/vscode#94898]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Reopen https://github.com/microsoft/vscode/issues/92612

If you need more information on how to hide a folder please let me know

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
@mcgodan Please answer the questions from the previous issue:

> What do you mean by hidden folder? How do you hide a folder? Are there any symlinks involved? Can you show me the full content of Git: Show Git Output?

**Comment by mcgodan** [comment]
By hidden folder I mean a folder with a . (dot) preceding the name. On Linux/Mac environments they are hidden by default. In Windows you can alter the folder attributes to make it hidden.

There are no symlinks involved. 

I’ll get back to you with the git output but I doubt that matters.

Simply put, the git integration in vscode didn’t detect changes when my files were stored In a hidden folder named .git, renaming the folder to git solves the problem. 

I only logged the improvement in case anyone else notices the same issue, if there is a way for vscode to work within a hidden folder I imagine it may be useful.

**Comment by simonozzy** [comment]
I just had the same issue with a folder with a "." at the start:
\.Working folder\JScript_JSON
Simple to fix by renaming without the dot, BUT:
- this may not be possible for some
- it took me over an hour to work this out, as no error messages, it just doesn't refresh

**Comment by joaomoreno** [comment]
Moved to https://github.com/microsoft/vscode/issues/92612#issuecomment-613304204
