### ISSUE TITLE
Jsx format code bug

### ISSUE THREAD

**Issue by thhoang99** [Microsoft/vscode#9489]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. in return of jsx file, put `<div>(or <h2>,<h3>,<a>, ...)"(enter)"</div>` anywhere.

  ex: 
```
<h3>"
     "</h3>
```
2. format code (alt + shift + f)
3. format code will stop working till reset vscode.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript#9856
