### ISSUE TITLE
Quick open now matches any character (not continuous/ camel case)

### ISSUE THREAD

**Issue by zeroskyx** [microsoft/vscode#94891]
- VSCode Version: 1.44
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Open a project that contains multiple named tasks
1. Open quick-open with CTRL+P and type a something like `task re`
1. Observe the matched tasks

Expected result:

Only tasks with the letters `re` continuously in their name or that would match camel case `RE` (such as `ReadElement`) are matched and displayed

Actual result:

All tasks that merely contain the letters `r` and `e` (in that order) are displayed

![image](https://user-images.githubusercontent.com/7782966/78983792-2ef47300-7b25-11ea-8074-354781ace0a9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
cc @bpasero
