### ISSUE TITLE
Duplicated file name with case rename

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9490]
- VSCode Version: 1.4.0-insider
- OS Version: OSX

Steps to Reproduce:

Unfortunately I'm not able to reproduce easily

1. TS task was running
2. Created file `AwesomePlete.ts`
3. Renamed file to `Awesomeplete.ts`
4. VSCode shows both of the files here:
![image](https://cloud.githubusercontent.com/assets/1723815/16955467/bbed09ca-4da2-11e6-87ad-12a71e3936b3.png)

If I select `AwesomPlete.ts` it opens `Awesomplete.ts`
Restarting VScode does not help (not sure if vscode keeps some cache or something)

If I open this project in 1.3.1 then it does not have this problem

**Comment by chrmarti** [comment]
@wallverb we don't cache across sessions. Are you using a case-sensitive filesystem? (Check with `diskutil info /`.)

**Comment by wallverb** [comment]
Insensitive. I renamed file to something completely else and then back to `Awesomplete.ts` and it fixed the issue and cannot reproduce anymore. Pretty weird. Thanks :)
