### ISSUE TITLE
Unable to correctly select text in the current line on the terminal

### ISSUE THREAD

**Issue by DavBfr** [microsoft/vscode#94909]
- VSCode Version: 1.44.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. View / Appearance / Reset Zoom
1. View / Appearance / Zoom Out (2 times, yes it's small!)
1. Open the terminal tab
2. Fill the terminal up to the bottom of the window:
    ```shell
    ls -la /
    ```
3. Type something, like: `echo "hello vscode team"`
4. Select the text `vscode` you just typed, or part of the prompt

**Actual result:** the selection is erratic

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
I cannot repro, can you create a gif to show the problem? https://gifcap.dev/ works well for this

**Comment by DavBfr** [comment]
Sure.

![ezgif-7-60b4d5978ad4](https://user-images.githubusercontent.com/1387855/79007414-200fbf80-7b29-11ea-8ab5-6f8fb291363e.gif)

**Comment by DavBfr** [comment]
@Tyriar It's about the zoom level too. I use View / Appearance / Zoom Out one or two times.
With a regular zoom or bigger size, the issue disappears.

**Comment by Tyriar** [comment]
Ok I see what you mean, when I zoom out once ~50% of the last row's height is counted as "below the terminal" so it wraps to the end of the row.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/2833

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/commit/4f4cf765f146c51d15f6192bbbf5396a8f64d378

**Comment by DavBfr** [comment]
Thanks!
