### ISSUE TITLE
Integrated Terminal Error

### ISSUE THREAD

**Issue by mbscreater** [microsoft/vscode#94901]
Issue Type: <b>Performance Issue</b>

I run my commands in Windows cmd and it works correctly.
But when i write any command in integrated Terminal of vs code, it gives me Error.
Its notable that the errors in different examples (i.e. in different commands and different projects) are all similar.

![2020-04-10 (9)](https://user-images.githubusercontent.com/58517808/78990463-b8b73700-7b4b-11ea-8c3e-24914ce70d67.png)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.85GB free)|
|Process Argv|M:\TypeScript\Compile|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    83	 13268	code main
    0	    65	   792	   window (Issue Reporter)
    0	    14	  1792	   electron-crash-reporter
    0	    25	  2564	   utility
    0	   208	 11212	   window (01.js - Compile - Visual Studio Code)
    0	    35	  3412	     searchService
    0	    14	  7520	     watcherService 
    0	    11	 11260	       console-window-host (Windows internal process)
    0	   171	 17736	     extensionHost
    0	    34	  6648	       "D:\Program Files\Microsoft VS Code\Code.exe" "d:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=17736
    0	   118	 13016	       "D:\Program Files\Microsoft VS Code\Code.exe" c:\Users\Al-Mussaddigheen\.vscode\extensions\angular.ng-template-0.901.0\server --logFile c:\Users\Al-Mussaddigheen\AppData\Roaming\Code\logs\20200410T160423\exthost1\Angular.ng-template\nglangsvc.log --logVerbosity terse --ngProbeLocations c:\Users\Al-Mussaddigheen\.vscode\extensions\angular.ng-template-0.901.0\server,m:\TypeScript\Compile --tsProbeLocations c:\Users\Al-Mussaddigheen\.vscode\extensions\angular.ng-template-0.901.0,m:\TypeScript\Compile --node-ipc --clientProcessId=17736
    0	   114	 16832	       electron_node tsserver.js 
    0	    46	 12440	         electron_node typingsInstaller.js typesMap.js 
    0	    50	 19492	       electron_node tsserver.js 
    0	    33	 19736	       electron_node eslintServer.js 
    0	   238	 19372	   gpu-process
    0	    73	 21300	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (01.js - Compile - Visual Studio Code)
|    Folder (Compile): 6 files
|      File types: json(2) js(1) map(1) ts(1)
|      Conf files: tsconfig.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.901.0
armview|ben|0.4.0
vscode-eslint|dba|2.1.2
jquerysnippets|don|0.0.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
vs-ng-quick-switch|erh|1.0.7
prettier-vscode|esb|4.2.0
textusm|har|0.3.0
angular-bootstrap|her|4.0.9
beautify|Hoo|1.5.0
jquery-snippets|Hri|1.0.0
vscode-angular2-emmet|jak|2.0.3
svg|joc|1.1.7
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
ng-bootstrap-snippets|ktr|1.0.0
Angular-BeastCode|Mik|8.1.2
powershell|ms-|2020.3.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
angular-console|nrw|11.1.3
es6-css-minify|olb|3.3.2
codemap|ole|1.10.4
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1
svg-preview|Sim|2.8.3
third-eye|thi|5.3.2
lorem-ipsum|Tyr|1.2.0
vscode-icons|vsc|10.0.0
vscode-todo-highlight|way|1.0.4
map-replace-js|Yuk|0.2.2
html-css-class-completion|Zig|1.19.0

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is either a powershell profile issue or tasks not passing an execution policy? @TylerLeonhardt any insights with what's happening and what we should do if anything?

**Comment by TylerLeonhardt** [comment]
Odd... @mbscreater what is your execution policy set to? In a PowerShell prompt, run:

```
Get-ExecutionPolicy
```

Then in the integrated terminal of VS Code run the same.

**Comment by Tyriar** [comment]
This specifically happened while running a task which is launched a little differently to the terminal so it might differ from the terminal.

**Comment by mbscreater** [comment]
@TylerLeonhardt, i didnt understand what do you mean about "a PowerShell prompt", but i wrote "Get-ExecutionPolicy" in Terminal and this was the result:

![2020-04-11](https://user-images.githubusercontent.com/58517808/79036309-493d5800-7bdc-11ea-9b1d-79c795179ae5.png)

**Comment by mbscreater** [comment]
Another note that maybe is effective (but not sure), is how to i open my projects.
I dont open vsCode at the first to open the project; i directly go to the project folder via Windows File Explorer and then i right-click on folder and choose "Open With Code".
![2020-04-11 (1)](https://user-images.githubusercontent.com/58517808/79036610-1b0d4780-7bdf-11ea-8c68-239a86e1cae1.png)

Is it right to open the project on this way? (about its effects on Terminal working)

**Comment by TylerLeonhardt** [comment]
@mbscreater thanks for that info. It's very helpful.

Do you have [Developer Mode](https://www.howtogeek.com/292914/WHAT-IS-DEVELOPER-MODE-IN-WINDOWS-10/) turned on?

This will enable a few different things that make using Windows as a development OS better.

The important part of that tutorial is the part about setting the PowerShell execution policy.
![PowerShell setting](https://www.howtogeek.com/wp-content/uploads/2017/02/img_58a4c3af122f5.png)

Can you enable this and give it another try and let us know how it goes?

**Comment by mbscreater** [comment]
Thanks @TylerLeonhardt ...! Your guidance was the solution.

![2020-04-12 (6)](https://user-images.githubusercontent.com/58517808/79065392-32266500-7cc5-11ea-9877-3921a3590c39.png)

The Integrated Terminal problem, fixed just when i clicked "Apply" in PowerShell part where you said. But i didn't change anything. I even didn't turn on the developer mode, but fortunately it got fixed.

**Comment by TylerLeonhardt** [comment]
Glad to hear it! We can close this issue now, I think.

**Comment by mbscreater** [comment]
Yes, of course!
