### ISSUE TITLE
Angular Language Service is not a recommended extension when an Angular project is opened

### ISSUE THREAD

**Issue by richardthombs** [microsoft/vscode#94908]
- VSCode Version: 1.44.0
- OS Version: Windows 10 slow ring

Steps to Reproduce:

1. Open an Angular app in vscode
1. Go to the extensions tab
1. See that Angular Language Service is not among the recommended extensions

Does this issue occur when all extensions are disabled?: N/A

I think this is a big deal, because it makes using writing Angular apps in VSCode so much better.

**Comment by sandy081** [comment]
Language extensions recommendations are shown when you open corresponding files. In this case this will be triggered when you open files with following extensions

`**/.angular-cli.json,**/*.ng.html,**/*.ng,**/*.ngml`

**Comment by richardthombs** [comment]
@sandy081 I don't think those are accurate triggers. The Angular CLI does not create any of the files you mention there.

Currently the Angular CLI creates new projects with an `angular.json` file (note there is no `-cli` suffix), and all the HTML templates are created with plain old `.html` extensions.

So if you simple do `ng new test` and then `code .`, you will never get the extension recommendation regardless of which files you open.

**Comment by sandy081** [comment]
Ok seems the extensions are outdated. Will update them.

**Comment by richardthombs** [comment]
Thank you!

I don't suppose there's a way to trigger the recommendation simply by the _presence_ of a file in the Explorer window, rather than it having to be open? In my experience it is pretty rare to edit `angular.json`.

**Comment by sandy081** [comment]
You can use workspace recommendations - https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by sandy081** [comment]
To verify

- install angular cli `npm install -g @angular/cli`
- `ng new test`
- `code-insiders .`
- open `angular.json`
- Open Extensions View and make sure the recommendations show `Angular Language Service` extension
