### ISSUE TITLE
Search freezes computer when large files are present in workspace

### ISSUE THREAD

**Issue by RobMin** [microsoft/vscode#94903]
Issue Type: <b>Bug</b>

I have several big text files in my workspace (over ten files  ~10gb each). And when I try to search something globally whole computer stops working, I can't even move the mouse or open terminal, and probably all the files are loaded to memory. And also I have 'Max Memory For Large Files MB' set to 4gb

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|23.36GB (8.48GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
vscode-node-readme|ben|3.0.2
simple-react-snippets|bur|1.2.2
gitignore|cod|0.6.0
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
code-runner|for|0.9.17
gc-excelviewer|Gra|2.1.34
CppSnippets|har|0.0.14
smarty|imp|0.3.0
path-autocomplete|ion|1.13.6
search-node-modules|jas|1.3.0
markdownfromcsv|joj|1.0.6
ibm-assembler|kel|0.6.0
node-module-intellisense|lei|1.5.0
csharpfixformat|Leo|0.0.84
rainbow-csv|mec|1.6.0
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.16
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
vscode-typescript-tslint-plugin|ms-|1.2.3
hades-assembler|pir|0.0.1
material-icon-theme|PKi|4.0.1
typescript-hero|rbb|3.0.0
ruby|reb|0.27.0
sass-indented|rob|1.5.1
trailing-spaces|sha|0.3.1
ascii-plist|spe|1.0.3
autoimport|ste|1.5.3
vs-code-node-require|tgr|1.4.7
vsfire|tob|1.4.1
vscode-status-bar-format-toggle|tom|2.0.0
lorem-ipsum|Tyr|1.2.0
errorlens|use|3.1.0
vscode-ruby|win|0.27.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
That setting is not hooked up to search. I should either use that setting for search, or add a new setting.

**Comment by eleanorjboyd** [comment]
Closing as this issue is stale and the search feature area has had many improvements since 2020. If you feel this issue is still relevant, please create a new issue, with updated information as this will allow us to have an better discussion about the state of the product at the current moment. Thanks!
