### ISSUE TITLE
editor.action.moveCarretRightAction keybinding doesn't work in 1.44.0

### ISSUE THREAD

**Issue by viktorku** [microsoft/vscode#94904]
After I updated my VS Code to 1.44.0 version my custom `editor.action.moveCarretRightAction` keybinding doesn't work anymore. I also tried using different modifier keys but none of them work.

```
{
    "key": "shift+space",
    "command": "editor.action.moveCarretRightAction",
    "when": "editorTextFocus"
}
```

This is pretty important to me as I rely on this keybinding a lot when coding in flow. I checked a few other of my user-defined keybindings and they seem to work as they should.

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z (2 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. Configure the keybinding as posted above and try to use it.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by alexdima** [comment]
The implementation of the two actions had severe flaws and they got reimplemented last milestone. What exactly doesn't work for you? They work fine for me:

e.g.
```
    {
        "key": "alt+h",
        "command": "editor.action.moveCarretLeftAction",
        "when": "editorTextFocus"
    },
    {
        "key": "alt+l",
        "command": "editor.action.moveCarretRightAction",
        "when": "editorTextFocus"
    }
```

![Kapture 2020-04-13 at 23 16 25](https://user-images.githubusercontent.com/5047891/79162055-dc44e080-7ddc-11ea-9bc7-13b73843ab9e.gif)

**Comment by viktorku** [comment]
@alexdima moving a selection of characters does work for me just like on your gif, but I'd like to move just the carret to the right/left without any active selection. This has worked before and actually why I opened the issue.

**Comment by alexdima** [comment]
@viktorku I'm sorry, but that was a bug that got fixed. See #82958. In other editors, this command didn't do anything for an empty selection. So now the actions are no-ops when there is no selection. 

You can use `when` conditions to have it that the keybinding moves the cursor left when there is no selection:
```
    {
        "key": "alt+h",
        "command": "editor.action.moveCarretLeftAction",
        "when": "editorTextFocus && editorHasSelection"
    },
    {
        "key": "alt+h",
        "command": "cursorLeft",
        "when": "editorTextFocus && !editorHasSelection"
    }
```
