### ISSUE TITLE
workspace settings.json changes dont update in WSL unless you reload the window

### ISSUE THREAD

**Issue by GTMxCode** [microsoft/vscode#94905]
- VSCode Version: 1.44.0
- OS Version: Win 10 v2004 OS Build 19041.173

Steps to Reproduce:

1. open folder
2. open settings.json in .vscode folder
3. make a change, eg "editor.fontSize": 18 --> "editor.fontSize": 22
4. work space is not updated

Does this issue occur when all extensions are disabled?: Cannot disable extensions or else WSL doesnt work?

If you make alterations to the settings.json file in the .vscode directory within your project, the settings aren't updated unless you reload the window. However, if you make the settings changes in the settings UI , the changes are immediately reflected. 

Kind of minor I suppose but something that confused me for a little bit

**Comment by sandy081** [comment]
>However, if you make the settings changes in the settings UI , the changes are immediately reflected.

What settings are you changing from UI ? Workspace or User?
