### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by WhoAdarshPandya** [microsoft/vscode#94916]
in latest version extension host terminates unexpectedly
when i open dev tools it show something like
Error: ENOENT: no such file or directory, open 'c:\Users\DC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js'
t.log @ /C:/Users/DC/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:262

- VSCode Version:1.44.0
- OS Version:windows x64 latest

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Jagruttam** [comment]
Same issue with same VS Code version and Windows version.

I tried downgrading VS Code. Worked fine. Again it got the auto-updated and same issue.

Issue with the VS Code version.

**Comment by gjsjohnmurray** [comment]
Probably caused by false positive detection by your antivirus software.

See #94807 and linked issues.
