### ISSUE TITLE
Windows hangs with Clang Command Adapter and specific project.

### ISSUE THREAD

**Issue by Pugnator** [microsoft/vscode#94911]
Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install "C/C++ Clang Command Adapter" from VScode store, version 0.2.3
2. Specific project only workspace
3. start typing ```#include <``` 
4. System completely hangs. Even capslock has no effect 

I disabled extension one by one with VScode restart and it looks like the extension above is one to blame.
I see no useful info in the Windows Event Viewer. Nothing suspicious. 
The problem occurs for one project only.
If this bug should be reported to the extension's repo only, I'll do it.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by RMacfarlane** [comment]
Thanks for tracking this down! Yes, please report this in that extension's repo
