### ISSUE TITLE
Can't search in workspace that includes folder using a FileSystemProvider

### ISSUE THREAD

**Issue by SqrTT** [microsoft/vscode#94928]
- VSCode Version: 1.44.0
- OS Version: Ubuntu 18.04.4 LTS

Steps to Reproduce:

1. Open workspace with contains non default file system (file) but with provider defined in plugin
2. Try and search

Does this issue occur when all extensions are disabled?: Yes

```
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4376 No search provider registered for scheme: ccfs, waiting

(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4376
searchWithProviders @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4376

(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4375

processTicksAndRejections @ internal/process/task_queues.js:85
```

**Comment by SqrTT** [comment]
I as author of the extension which implements file system provider can't implement search provider since it's only in proposed API.

**Comment by roblourens** [comment]
Yes, this is proposed API.

https://github.com/microsoft/vscode/issues/73524
https://github.com/microsoft/vscode/issues/59921

**Comment by SqrTT** [comment]
it's is. but right now this is make issue in v1.44.0. Is that expected?

this is not duplicate since this don't ask for feature but rater bug related to this feature.

**Comment by SqrTT** [comment]
is that expected that users of my extension have to between choose to use file search or work with external file system?

**Comment by SqrTT** [comment]
@roblourens please reopen issue since it's not fixed and not duplicate

**Comment by SqrTT** [comment]
![image](https://user-images.githubusercontent.com/1271300/79014444-989b6e00-7b73-11ea-85e0-c23532f08af0.png)

**Comment by SqrTT** [comment]
@roblourens or @RMacfarlane please suggest how can I fix the issue `No search provider registered for scheme: ccfs, waiting` without using proposed API for v.1.44.0?

**Comment by roblourens** [comment]
I'm pretty sure this didn't work in old versions either, the API has never been stable.

**Comment by SqrTT** [comment]
let's start from scratch. Extension **don't** use search provider API (`TextSearchProvider` and `FileSearchProvider`).
Extension use `registerFileSystemProvider` and registers protocol `ccfs` this was working well for last two years, but starting v1.44.0 users with the extension face issue with broken search with mentioned in subject title.

I don't need proposed API. I need search working again.
At this point I can fix this only by drop off feature which relays on `FileSystemProvider`. 
Is there way to save feature?

**Comment by SqrTT** [comment]
@roblourens by the way: `workspace.registerFileSearchProvider` is not available in type definition but available in runtime. Is that ok? Does it means I can use it in to fix the issue?

![image](https://user-images.githubusercontent.com/1271300/79021536-7231fe80-7b84-11ea-9489-677cb06b08c8.png)

**Comment by RMacfarlane** [comment]
@roblourens Maybe this commit is the problem? https://github.com/microsoft/vscode/commit/0e219d4de273bfee5e401830c65abae18d2f0c3f

Would this cause search to wait indefinitely?

**Comment by roblourens** [comment]
Is this a multiroot workspace where one folder is a normal folder on disk and the second is from the separate scheme? I guess I see the issue then. If that's not it then I guess I don't understand what was being searched before, please explain.

**Comment by SqrTT** [comment]
correct, workspace has few folders in it with one "virutal" for `ccfs`
```json
{
    "folders": [
        {
            "path": "ecom-project"
        },
        {
            "name": "Sandbox - FileSystem",
            "uri": "ccfs://current-sandbox"
        }
    ],
    "settings": {}
}
```

**Comment by gjsjohnmurray** [comment]
@roblourens this 1.44 regression is likely to affect users of one of my extensions too. Please make the fix a candidate for the 1.44.1 recovery release.

**Comment by roblourens** [comment]
Yeah I see it. That change was a mistake, I agree that it should be a candidate.

**Comment by Feder1co5oave** [comment]
Hi, I'm getting the following log after the 1.44.0 update whenever I CTRL+P (**search hangs and does not show results**): 

```
[13934:0413/222622.335701:INFO:CONSOLE(4376)] "No search provider registered for scheme: gitlens, waiting", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (4376)
```

disinstalling, reinstalling gitlens or disabling extensions was of no help.
**Recreating the workspace worked.**

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T11:22:13.689Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-45-generic
```

**Comment by mttkay** [comment]
I'm having the same problem as @Feder1co5oave . I even uninstalled GitLens but the problem persists. Search is totally broken now.

**Comment by mttkay** [comment]
That said, how do I manually remove the GitLens search provider?

**Comment by roblourens** [comment]
This is fixed in Insiders but not stable yet.

**Comment by roblourens** [comment]
Verification steps: 

- Run the fsprovider sample from our extension samples repo
- Run the commands to create a MemFS workspce folder
- Add another workspace folder, some normal folder on your disk
- Do a search
- It should return results from the local folder and ignore the MemFS folder
