### ISSUE TITLE
Working with SCSS files causes unexpected restarts

### ISSUE THREAD

**Issue by KKacer** [microsoft/vscode#94925]
When working with SCSS files, trying to make my own library,
I face uncountable unexpected restarts/exits of the application.

At first I had too many extensions so almost deleted all, and just added around 5 famous ones, 
like Live Server, Live Sass Compiler and 2,3 more recommended ones, which pretty sure the issue shouldn't be related to them. And in both scenarios there were still enormous errors.
In my opinion parts of this issue may go back to "Live Sass Compiler" but I think some or maybe most of the issue may go to VSCode.
I really expect that VSCode make and have a generic/standard support for SCSS files.
When I edit my SCSS files, variable names, import names, there wouldn't take too many seconds that the app stops working and ask me for a reload!
When it can't find a SCSS library, a variable, etc it cause errors that can't handle any how.
Another thing that I blame VSCode is that, it can provide more control, and more features to allow users to debug such issues.
By the way pretty sure that most of these can be handled by VSCode itself.

Using latest version of Windows 10, latest version of VSCode.

please have a look at these 2 videos:
https://1drv.ms/v/s!AlScPmE9PLAKgRvcbuEvS43q4tFZ?e=PW2Har
https://1drv.ms/v/s!AlScPmE9PLAKgRrQcXX_QLjdcrOS?e=yBoIwo

**Comment by RMacfarlane** [comment]
@KKacer To rule it out, can you try running `Developer: Reload with Extensions Disabled` to temporarily disable the extensions and see if you still have the same problem?

Can you paste the text or post a screenshot of the app asking you to reload? When you say it restarts, do you mean that VSCode crashes, or do you see a notification about the extension host restarting, or something else?

**Comment by RMacfarlane** [comment]
Sorry! I somehow missed looking at your videos 🤦 

We have been getting a number of reports of the extension host crashing with the latest release due to a file being incorrectly flagged by antivirus software. Please see discussion on this here: https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

The window asking to restart seems like a different problem, I would try doing the same steps with extensions disabled

**Comment by KKacer** [comment]
@RMacfarlane thanks for the feedback,
I disabled Live Sass compiler and left that job for a 3rd party compiler outside VS, seems there is no issue.
Even when I posted this, I guessed disabling that extension may solve the issue, but as an opinion or idea, I think  VSCode may caught such errors that even an extension cause, so we be able to debug via some useful log information, which didn't exist. To continue I hope in some new versions you support SCSS more natively.
Currently I guess I may not have the issue, that was irritating though.
I experienced those 2 errors that you may saw in the video over 100 times while was creating my own SCSS library.
I have Eset Smart Security installed, and guarantee that wasn't related to it.
When those errors happen, there are some real errors inside my code, but even some aren't really errors I can say,
I changed a filename, a library, etc, some renamings, changing folders, re-organizing code or files, ...
and there are tens of imports, some files related to others,
but, what I expect is that the application shouldn't crash!
It should give me minutes even seconds to fix some recently changed/missed items in the code.
Again IMO it shouldn't crash! even better it could guide me by telling which file/variable is missing when it got more support for Sass.
After some crashes by following some paths and looking in detail several files, I may find that I needed an extra "../" for a lib out of 100 imports. But should the application crash?
VSCode is an editor, so I believe it should handle it, and I shouldn't move to NotePad++ to edit such lines to make the project working again.
So, Pardon me, guess can't go back and reproduce it or not have time to play with it.
Just wanted to provide this as something to note for its great developers.
Feel free to merge or manage this opened issue anyhow.
Regards.
