### ISSUE TITLE
No obvious way to disable Sync

### ISSUE THREAD

**Issue by GaryBoone** [microsoft/vscode#94927]
The new Sync preferences experimental feature notified me this morning to sign in to an account to enable syncing. There was no obvious way to make this notification go away. 

1. The pop-up for signing-in did not have a 'do not enable sync' checkbox. 
1. The menu item about Sync didn't include a submenu to not enable it. 
1. The gear icon with the (1) on it didn't have a way to not enable it. 
1. The gear icon didn't have a way to make the (1) notification go away. 
1. Looking in Preferences for something related to 'sync' did not find the feature or a way to make it stop.

It was only by searching the github issues that I learned to use cmd-shift-p and type "Preferences Sync" to find the disable command.

So there are a number of issues here about the notifications and default opt-in. But this bug is about the UI difficulty of turning it off:

1. Anywhere it can be activated, it should be possible to deactivate it.
1. Turning it off should appear in obvious places, like any menu where it's doing sign-ins.
1. Turning it off/on should appear in the normal preferences, where users are trained to look for such things.

**Comment by derkallevombau** [comment]
> It was only by searching the github issues that I learned to use cmd-shift-p and type "Preferences Sync" to find the disable command.

Thank you! That permanent (1) on the gear icon was really nasty!

**Comment by sandy081** [comment]
/duplicate

#94766
