### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by swapnadeepmohapatra** [microsoft/vscode#94936]
- VSCode Version: March 2020 (version 1.44)
- OS Version: Windows 10 (version 1909)

Steps to Reproduce:

1. On the launch of the VSCode, I get this error.

I have tried

- new installation, with and without any extensions.
- disabled git.
- ran as an administrator.
- tried all other ways mentioned in other issues.

Does this issue occur when all extensions are disabled?: Yes

**Comment by swapnadeepmohapatra** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Extension host terminated unexpectedly. (#94722)](https://www.github.com/microsoft/vscode/issues/94722)
> * [extension terminated host unexpectedly (#94804)](https://www.github.com/microsoft/vscode/issues/94804)

I tried every possible way mentioned in other issues but it didn't solve the error.

**Comment by RMacfarlane** [comment]
@swapnadeepmohapatra Are you using antivirus software? Please see https://github.com/microsoft/vscode/issues/94869#issuecomment-611901305

**Comment by swapnadeepmohapatra** [comment]
I am using Quick Heal but it's disabled. The virus protection is off. So it won't affect.

**Comment by gjsjohnmurray** [comment]
@swapnadeepmohapatra did you reinstall 1.44 after disabling Quick Heal?

**Comment by gjsjohnmurray** [comment]
More advice at https://github.com/microsoft/vscode/issues/94858#issuecomment-611924064 and subsequent posts

**Comment by swapnadeepmohapatra** [comment]
I reinstalled 3 times. Restated the PC multiple number of times. I even tried other methods from other issues but no effect.

**Comment by RMacfarlane** [comment]
@swapnadeepmohapatra Have you already tried the steps here? https://github.com/microsoft/vscode/issues/94858#issuecomment-611937137

**Comment by swapnadeepmohapatra** [comment]
Instead of disabling that Anti Virus. I uninstalled that and it got solved.... Thanks everyone for your suggestions and help.
