### ISSUE TITLE
Unable to add empty lines between buttons (commands) in Welcome Content in TreeView

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#94934]
- VSCode Version: 1.44
- OS Version: MacOS Mojave 10.14.6

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Define a `viewsWelcome` content, containing two commands in sequence, like the snippet bellow:

```json
    "viewsWelcome": [
      {
        "view": "projectsExplorerFavorites",
        "contents": "No projects saved yet.\n
                     In order to save projects, you have to open a folder or workspace first.\n
                     [Open a Folder](command:workbench.action.files.openFileFolder)\n
                     \n
                     [Open a Workspace](command:workbench.action.openWorkspace)\n
                     To learn more about how to use Project Manager in VS Code [read the docs](http://github.com/alefragnani/vscode-project-manager/#project-manager)",
        "when": "workbenchState == empty"
      },
```

> _the contents json is splitted just for viewing purposes. it is a single line entry in `package.json` file_

2. I will display this:

![Screen Shot 2020-04-10 at 14 23 57](https://user-images.githubusercontent.com/3781424/79009912-12613680-7b37-11ea-885b-0622a320d89b.png)

3. I tried a few alternatives to add an empty line between both commands (buttons), with no success (new line  `\n` , tab `\t` , html - empty space `&nbsp`, html - line break `<br/>` , html - paragraph `<p>`, with no success. It seems a limitation in the rendering engine. 

I'm  looking for something like this _(edited the html in DevTools)_:

![Screen Shot 2020-04-10 at 12 18 16](https://user-images.githubusercontent.com/3781424/79010090-90bdd880-7b37-11ea-9c88-566e9970c2eb.png)

You can see the same issue _(not exactly coding but visual)_ in the native **Source Control** view

![Screen Shot 2020-04-10 at 11 53 59](https://user-images.githubusercontent.com/3781424/79009711-8f3fe080-7b36-11ea-9eb8-a3a3278a3ddb.png)

Thank you

**Comment by isidorn** [comment]
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/94592 which is already fixed in insiders.
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by alefragnani** [comment]
That's it! Working perfectly in Insiders 👏 

Thank you!

**Comment by isidorn** [comment]
Thanks
