### ISSUE TITLE
Remember panel maximize state

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#94930]
I've found that I really like having the panel maximized now that it cleanly takes up the entire window. Text reflow in the terminal and resizing the panel are abysmal and the maximized panel mostly works around this issue. However, every time I open the panel it resets to the non-maximized state. I can't use the panel in a maximized state without having to execute two commands each time I want to interact with it: open the viewlet I want (search, terminal, console, etc) then maximize it..

I think the maximize toggle should be remembered instead of reset each time.

**Comment by sbatten** [comment]
@akbyrd using the `Toggle Maximized Panel` command will work even if the panel is closed so you can use this to get the panel opened directly to the maximized state, but I can see the request for this when using the `Open Debug Console` and similar commands.

**Comment by akbyrd** [comment]
Yea, that's precisely the issue. `workbench.action.toggleMaximizedPanel` will open the panel maximized, but only to whichever viewlet was last active. If I use something like `workbench.action.terminal.focus` the panel will open but be reset to the un-maximized state.

**Comment by jonahkagan** [comment]
I would love this change as well. In particular, every time I cmd+click a file path in the maximized panel it resets to the un-maximized state, which is super annoying.

**Comment by Kolobamanacas** [comment]
It would be very nice to have this feature. It is very convenient to have a shortcut to open and close terminal when needed. I use ctrl + ` to toggle terminal all the time. But indeed for some people including me it's more convenient to have terminal maximized. workbench.action.toggleMaximizedPanel does half the job and successfully opens terminal maximized, but then you still have to use mouse to hide it back.

**Comment by jagdishrajan** [comment]
I agree.  It is very helpful to keep working with the terminal panel in a maximized state and when switching between the editor and the terminal panel it should remember the terminal's last state.

**Comment by sbatten** [comment]
@rzhao271 and I are looking to fix this issue. One consideration we thought about when looking at the fix was cases where the active panel or other series of events might "break" the maximized panel state. For example,

1. Put search in panel
2. Put panel in maximized state
3. Run a search and select a result (thus opening the editor and unmaximizing the panel)

You must now remember to re-maximize the panel before closing it.

An alternative fix for this issue might be: a setting that sets the default opening state of the panel. "maximized" or "non-maximized". 
With the "maximized" state, every time the panel is opened it would be maximized.

Thoughts from those interested in this request?

**Comment by akbyrd** [comment]
That's a weird workflow. I think it makes equal sense to just close the panel if clicking a search result while it's maximized. Or just let it unmaximize and remember that. Either of those seem fine and potentially even preferable. Trying to remember that it "used to be" maximized seems strange and surprising. Remembering whatever the last visible state was seems like the predictable and intuitive thing.

Personally, I greatly prefer that it remember the last state I used, not just default to maximized.

I wouldn't want to optimize for an edge case workflow. Doubly so if that edge case workflow doesn't make a ton of sense in it's own right (selecting results while maximized).

**Comment by rzhao271** [comment]
Notes for testers: 

- See #107624 

Notes for documentation:

- There is now a `panel.opensMaximized` setting that provides various options for panel maximization behaviour.
