### ISSUE TITLE
Visual studio code is getting crashed

### ISSUE THREAD

**Issue by ifaizmohd** [microsoft/vscode#94932]
Issue Type: <b>Bug</b>

my vsc is getting crashed frequently.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.2
prettier-vscode|esb|4.2.0

</details>

**Comment by RMacfarlane** [comment]
@ifaizmohd Did this only start happening with the latest update? What are you doing when it crashes? Does it only crash for certain projects?

**Comment by ifaizmohd** [comment]
Yes I do get this error after updating it to the latest version and I am working on mern application, whenever I try to hit the npm start it crashes and it is very frequent like 8 to 10 times in a row untill you kill the task from task manager. 
Thanks in advance.

**Comment by igtm** [comment]
Same issue happen on only 1.44.0 ( `2aae1f2` ) version on MacOS Catalina

**Comment by deepak1556** [comment]
@ifaizmohd can you re-trigger the crash with latest stable, in that case you attach the crash reports from the following location `C:\Users\...\AppData\Local\Temp\VSCode Crashes\reports`
