### ISSUE TITLE
tab character is rendered as square

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#94939]
Issue Type: <b>Bug</b>

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 5.4.30-1-lts

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3969)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|31.31GB (2.51GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-hie-server|ala|0.0.37
better-toml|bun|0.3.2
ccls|ccl|0.1.28
vscode-eslint|dba|2.1.2
vscode-dash|dee|2.3.0
java-decompiler|dgi|0.0.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.2.0
file-icons|fil|1.0.23
code-runner|for|0.9.17
shell-format|fox|7.0.1
kotlin|fwc|0.2.11
godot-tools|gee|1.0.3
perl-outline|hit|0.0.6
hoogle-vscode|jca|0.0.7
vscode-peacock|joh|3.7.0
svn-scm|joh|2.10.6
language-haskell|jus|2.7.0
Lua|key|0.0.9
saltstack|kor|0.0.6
sftp|lix|1.12.9
bash-ide-vscode|mad|1.8.0
Lisp|mat|0.1.10
vscode-docker|ms-|1.0.0
vscode-language-pack-ru|MS-|1.44.2
csharp|ms-|1.21.16
python|ms-|2020.3.71659
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
gradle-language|nac|0.2.3
vscode-subword-navigation|ow|1.2.0
phoityne-vscode|pho|0.0.25
java|red|0.59.1
vscode-yaml|red|0.7.2
bash-debug|rog|0.3.7
rust|rus|0.7.0
vscode-hexdump|sle|1.7.2
shellcheck|tim|0.9.0
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
debug|web|0.24.0
jinja|who|0.0.8
clang-format|xav|1.9.0
vscode-proto3|zxh|0.4.2

</details>

![image](https://user-images.githubusercontent.com/7345761/79013399-540ed300-7b71-11ea-9999-f53bfe878a88.png)

Font config is default. Tried Hack font, the same.

**Comment by alexdima** [comment]
@Yanpas There are two characters used to render a tab:
* `→` - ['RIGHTWARDS ARROW' (U+2192)](https://www.fileformat.info/info/unicode/char/2192/index.htm)
* `￫` - ['HALFWIDTH RIGHTWARDS ARROW' (U+FFEB)](https://www.fileformat.info/info/unicode/char/FFEB/index.htm)

When the first one is too wide (it has a width larger than the width of one space), and there is only a gap of one space to render, we render with the second one. 

Can you please try copy-pasting the characters from here into your editor? Do these characters render OK in Chromium on this machine?

**Comment by Yanpas** [comment]
This charcter is not rendered in both vscode and chromium browser (81). Tried clearing fontconfig cache (fc-cache -r).

Tried many fonts - no luck
![image](https://user-images.githubusercontent.com/7345761/79166260-6e54e500-7ded-11ea-99dd-5e27a6828752.png)

**Comment by alexdima** [comment]
AFAIK, when configuring a font family, the OS will fall back to other fonts if a glyph is not found in the font. Normally, linux distributions come with some kind of system fonts that would contain this. I don't really know what those would be. What linux distribution are you using?

**Comment by Yanpas** [comment]
Arch linux.

here are all fonts I have installed https://gist.github.com/Yanpas/4fe95c77f66f9815376b3302ee5fe9dc

**Comment by alexdima** [comment]
The glyph substitution / font selection is not implemented in VS Code, we delegate the font rendering in the editor to Chromium. So I would seek help in the Chromium issue list or on stackexchange where I see some hits when searching for "linux substitution fonts".

I think the system is using a non-default font configuration, and somehow this glyph is no longer found in all the installed substitution fonts, all the ones with "fallback" in their names should be hit and used. Unfortunately, I lack the expertise to help track this down, since this is nothing that we implemented.

I'm sorry I can't really help further in this case, but if you figure out what's wrong with rendering that glyph, please comment here so others might benefit in the future.

**Comment by Yanpas** [comment]
Well, the problem is trivial. In the [link above](https://www.fileformat.info/info/unicode/char/FFEB/fontsupport.htm) there is a small list of fonts that support this symbol. There is only one popular and it is proprietary Arial font which is not preinstalled in any linux distribution, but exists on macos and windows. I downloaded http://www.quivira-font.com/downloads.php this font, ran fc-cache and this symbol is rendered now

![image](https://user-images.githubusercontent.com/7345761/79170161-39e62680-7df7-11ea-8977-c2cc55a1be92.png)

I'm sure that there are far better alternatives to this symbol.

**Comment by alexdima** [comment]
@YanPas I have tried a stock installation of ubuntu:

![image](https://user-images.githubusercontent.com/5047891/79207780-6e7ed000-7e41-11ea-9722-e284cedfab5e.png)

It is my belief that your system is using a non-standard font configuration. I can also try downloading arch linux and creating a VM to try it out.
