### ISSUE TITLE
Note the last position in Release Note

### ISSUE THREAD

**Issue by saxc** [microsoft/vscode#94945]
The release notes are very helpful.
i try out some of the functions directly.

If the tab is changed during a test and got back to the reles notes the file is reloaded, the last position is not remembered.

It would be helpful to remember the last position as long as the Relese Note Tab is open.

![ReleasNote](https://user-images.githubusercontent.com/7613585/79017202-0f833780-7b71-11ea-8f65-2c19fd933af6.gif)

i found old closed issues with the same theme from 2017-2018.
#34369 #58007 #39157 #45571

**Comment by gjsjohnmurray** [comment]
Related to #27498, for which I submitted PR #85982 and am awaiting feedback.

**Comment by madpipeline** [comment]
That PR has merge conflicts and no changes since start of October. Is it still active?

**Comment by prom00** [comment]
I've found this is still happening to me in version 1.52:

![releaseNotes](https://user-images.githubusercontent.com/46184489/102586273-1ef84e80-410a-11eb-8c2c-e56c67fb772d.gif)

**Comment by runxel** [comment]
This seems to be somehow "fixed"/regressed into #120322, where it now remembers the scroll position, but is also always slightly wrong with it. 😀

**Comment by mjbvz** [comment]
This was fixed with #115791, although as #120322 notes the restored position can be a bit off due to image loading
