### ISSUE TITLE
Project windows don't remember preferred dimensions

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#94944]
- VSCode Version: 1.43.2
- OS Version: Windows 10

Steps to Reproduce:

1. Close VSCode.
2. Reopen it.

Does this issue occur when all extensions are disabled?: Yes

Every time I close VSCode and reopen the same tired projects, the windows are in the wrong place at the wrong size. They're smaller than I left them. Builtin display, no external monitors involved.

Who the heck would want to run a text editor un-maximized anyway?

**Comment by RMacfarlane** [comment]
@mcandre Are you fullscreening VSCode before you close it? If so, please enable the setting "window.restoreFullscreen"

**Comment by ivan** [comment]
This happens for me all the time when I have several project windows (try 4 to repro), and I do not fullscreen VSCode before I close it.

- VSCode Version: 1.44.0
- OS Version: Windows 10 1909

**Comment by ivan** [comment]
This still happens with 1.45.0 for me, but only if VSCode is not in the foreground when it is being started. Start VSCode with multiple windows, immediately foreground something else, observe flashing taskbar buttons with incorrect window sizes.

**Comment by 5dao** [comment]
@ivan @RMacfarlane @mcandre 

this issue could be better choice

please vote it

#99415
