### ISSUE TITLE
"Getting code actions" pop-up doesn't specify which extension is slow

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode#94947]
**VSCode Version**: 1.45.0-insider c12bd56a8886f31e353a45f5846f0a35a52f908e x64

Is there a way to make it clear to the user which extension is causing the slow saves? We've been getting a lot of bug reports in https://github.com/microsoft/vscode-go about this, but in a majority of cases, users have found that another extension they've installed is actually causing the problem. One user debugged and discovered that the Spell Right extension was actually causing the issue, and when I tried to reproduce it, I saw the following pop up:

<img width="605" alt="Screen Shot 2020-04-10 at 1 01 41 PM" src="https://user-images.githubusercontent.com/5856771/79020174-1ea0c000-7b46-11ea-811f-a9266811e047.png">

From this image, it's not obvious that Spell Right is the issue, but the problem disappears once it's disabled.

**Comment by jrieken** [comment]
We don't know because everything is still in-flight. We cannot know that A waits for B or that B waits for A because nothing has finished yet and because this is a progress notification. However, the extension host log files will reveal which provider took how long.

**Comment by jrieken** [comment]
I have pushed a change that makes sure extension names are only shown once, that's all we can do. To get to the number after things have settled, use "F1 > Log Level > Trace" and then "F1 > Show Log > Extension Host Log"
