### ISSUE TITLE
Rubocop not working

### ISSUE THREAD

**Issue by juannodeb** [microsoft/vscode#94949]
Issue Type: <b>Bug</b>

I'm using rvm, trying to work with rubocop but none of the extensions and gems I've added seems to work.

I'm using ruby 2.7.0, rails 5.2.4.2, tried with rubocop and rubocop-rails gems and with ruby-rubocop, ruby, vscode-ruby extensions.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 5.3.0-28-generic snap

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
gitlens|eam|10.2.1
ruby|gro|0.1.0
ruby-linter|hoo|1.0.0
ruby-symbols|mig|0.1.8
ruby-rubocop|mis|0.8.3
ruby|reb|0.27.0
haml|vay|1.0.1
simple-ruby-erb|vor|0.2.1
Ruby-extension-pack|wal|0.0.4
vscode-ruby|win|0.27.0

</details>

**Comment by RMacfarlane** [comment]
@juannodeb Are you seeing any notifications about the extension host terminating?

**Comment by juannodeb** [comment]
@RMacfarlane I don't. It sometimes works as expected showing what's wrong on the problems tab, for example when I create a method with nothing on it. But on the other hand it says nothing when I just type random words on the file, leave unnecessary spaces, etc
