### ISSUE TITLE
Search only searching in open files

### ISSUE THREAD

**Issue by mittaljethwa** [microsoft/vscode#94942]
Issue Type: <b>Bug</b>

Open Folder in VS code
Attempt to search for text within project's root folder contents by clicking "Find in Folder"
When a file is open, any instances of searched text will appear
When a file is not open, any instances of searched text do not appear

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|0.6.0
todo-tree|Gru|0.0.171
vscode-docker|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.1.1
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0
vscode-yaml|red|0.7.2
c-cpp-definition-generator|rei|0.0.2
cmake|twx|0.0.17
vscode-capnp|xmo|1.0.0

</details>

Log (Window) trace:

> [2020-04-10 12:16:41.642] [renderer1] [trace] CommandService#executeCommand workbench.output.action.clearOutput
> [2020-04-10 12:16:41.644] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"workbench.output.action.clearOutput","from":"panel"}
> [2020-04-10 12:16:53.437] [renderer1] [trace] [text file model] load() - enter file:///Users/mjethwa/dev/MAC/code/tmac/apps/control/inc/ControlThreads.hpp
> [2020-04-10 12:16:54.162] [renderer1] [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"/Users/mjethwa/dev/MAC","external":"file:///Users/mjethwa/dev/MAC","path":"/Users/mjethwa/dev/MAC","scheme":"file"},"fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":true,"maxResults":10000,"type":2,"contentPattern":{"pattern":"m_fsmThreadIndex","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false,"userDisabledExcludesAndIgnoreFiles":true}
> [2020-04-10 12:16:54.168] [renderer1] [debug] SearchService#search provideTextSearchResults m_fsmThreadIndex, {"folder":"file:///Users/mjethwa/dev/MAC","excludes":[],"includes":[],"useIgnoreFiles":false,"useGlobalIgnoreFiles":false,"followSymlinks":true,"encoding":"utf8","maxFileSize":17179869184,"maxResults":10000,"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}
> [2020-04-10 12:16:54.169] [renderer1] [debug] SearchService#search rg --hidden --ignore-case --max-filesize '17179869184' --no-ignore --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'm_fsmThreadIndex' '.'
>  - cwd: /Users/mjethwa/dev/MAC
> [2020-04-10 12:16:54.169] [renderer1] [trace] telemetry/searchResultsFirstRender {"duration":6}
> [2020-04-10 12:16:54.171] [renderer1] [debug] SearchService#search No data from stdout
> [2020-04-10 12:16:54.171] [renderer1] [debug] SearchService#search No result from parser
> [2020-04-10 12:16:54.172] [renderer1] [debug] SearchService#search 
> [2020-04-10 12:16:54.172] [renderer1] [trace] SearchService#search: 10ms
> [2020-04-10 12:16:54.173] [renderer1] [trace] telemetry/textSearchComplete {"reason":"searchView","workspaceFolderCount":1,"endToEndTime":10,"scheme":"file","usePCRE2":false}
> [2020-04-10 12:16:54.188] [renderer1] [trace] telemetry/searchResultsShown {"count":4,"fileCount":2,"options":{"isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"duration":11,"scheme":"file","searchOnTypeEnabled":true}
> [2020-04-10 12:16:54.189] [renderer1] [trace] telemetry/searchResultsFinished {"duration":15}
>

**Comment by roblourens** [comment]
Can you check whether any tips in here help? https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by sslupsky** [comment]
I have noticed the same behaviour.  Search returns result only if the file is currently open.

**Comment by mittaljethwa** [comment]
@roblourens It resolved for me when I rebooted my system. Thanks!

**Comment by roblourens** [comment]
Please let me know if it happens again
