### ISSUE TITLE
"Open All Changes (with difftool)" doesn't do anything

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#94959]
Issue Type: <b>Bug</b>

When I run "Open All Changes (with difftool)" from SCM nothing happens on a repository with several clear modified files.

Not sure if it this would help but just in case, here's the `.gitconfig` file in my home directory:

```
[core]
    editor = code --wait
[diff]
    tool = default-difftool
[difftool "default-difftool"]
    cmd = code --wait --diff $LOCAL $REMOTE
```

VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T19:43:46.226Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (23.77GB free)|
|Process Argv|-psn_0_454767|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.4.11
vscode-database|baj|2.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.1
LogFileHighlighter|emi|2.8.0
shell-format|fox|7.0.1
seito-openfile|Fr4|1.8.5
mdmath|goe|2.4.0
gc-excelviewer|Gra|2.1.34
open-file-from-path|jac|1.3.3
latex-workshop|Jam|8.8.0
vsc-space-block-jumper|jmf|1.2.2
center-editor-window|kai|2.3.0
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
sqltools|mtx|0.21.6
highlight-dodgy-characters|nac|1.0.0
neuron-IPE|neu|1.0.4
vscode-ipython|pan|0.5.0
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.25.0
vscode-yaml|red|0.7.2
vscode-dired|rru|0.0.5
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-fileutils|sle|3.0.1
emacs-mcx|tut|0.18.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.0
org-mode|vsc|1.0.0
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by joaomoreno** [comment]
`Open All Changes (with difftool)` isn't a command provided by VS Code.

**Comment by amelio-vazquez-reina** [comment]
Thanks - apologies for the confusion. In case anyone lands here, I moved the Q [here](https://github.com/eamodio/vscode-gitlens/issues/1001).
