### ISSUE TITLE
Semantic highlighting: Arrow Function Parameter Destructuring not recognized as parameter

### ISSUE THREAD

**Issue by gaplo917** [microsoft/vscode#94957]
### Reproducing GIF
Please check the following reproducing GIF
![Kapture 2020-04-11 at 5 42 25](https://user-images.githubusercontent.com/5468398/79025267-d28e6380-7bb7-11ea-87be-d11de2176e09.gif)

### Expected: 
`aaa` and  `bbb` should have semantic token type `parameter` then the subsequent color should be highlighted as same as `acc`

## Details

- VSCode Version:
- OS Version:
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Steps to Reproduce (Sample Codes):
```
 function arrowFunctionTest() {
    const array = [{aaa: 1, bbb: '2'}]
    return array.reduce((acc, {aaa ,bbb}) => acc + aaa + Number(bbb), 0)
  }
```

**Comment by aeschli** [comment]
fixed by https://github.com/aeschli/typescript-vscode-sh-plugin/pull/4
(already in latest insiders)
