### ISSUE TITLE
MSSQL syntax still overpowers PostgreSQL scripts

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#94954]
- VSCode Version: Stable.
- OS Version: Windows 10 and macOS 10.15 Catalina.

Steps to Reproduce:

1. Write a PostgreSQL `.sql` file.

Does this issue occur when all extensions are disabled?: Yes

The default VSCode configuration for the built-in MSSQL plugin completely screws up PostgreSQL files. The parser gripes about how my .SQL files are not valid MSSQL and proceeds to underling nearly every token. There is no option to re-parse the file with PostgreSQL rules. No setting to force a PostgreSQL parser for all my `.sql` scripts by default. No GH linguist to properly detect which SQL flavor is in use.

Guess what, it's even a backup file clearly labelled with the word `PostgreSQL` in a standard `pg_dump -F p` machine generated comment on the second line. It couldn't be more obvious that this is NOT Microsoft SQL.

As a workaround, I am turning off MSSQL live warnings.

**Comment by Hong-Revo** [comment]
Did you try installing the [Postgresql extension](https://github.com/Microsoft/vscode-postgresql)?

**Comment by aeschli** [comment]
VSCode only defines basic language features for SQL (syntax highlighting, smart editing (brackets, comments, new lines). You can file an issue against the MSSQL extension to improve the way to work with PostgreSQL files, or simply disable it.
