### ISSUE TITLE
CodeLens allows for invalid classnames

### ISSUE THREAD

**Issue by x24git** [microsoft/vscode#94958]
In the [codelensController](https://github.com/microsoft/vscode/blob/6d0becaadff8df79bcaa3d8c649ec538e95f4902/src/vs/editor/contrib/codelens/codelensController.ts), there is an issue when the class name for the codeLens span element gets generated on line 70.
```javascript
this._styleClassName = hash(this._editor.getId()).toString(16); 
```
This hashing operation can on occasions result in a numerical character (0-9) being the first character in the class name. By CSS syntax rules, a CSS identifier is not allowed to start with a numerical value (without using the escaped character code sequence). This results in the codeLens not changing size to match the editor font size and can result in overlapping and mis-sized code lenses.

Later on in line 94, we can see the class name get applied to a style sheet
```javascript 
const newStyle = `
		.monaco-editor .codelens-decoration.${this._styleClassName} { height: ${height}px; line-height: ${lineHeight}px; font-size: ${fontSize}px; padding-right: ${Math.round(fontInfo.fontSize * 0.45)}px;}
		.monaco-editor .codelens-decoration.${this._styleClassName} > a > .codicon { line-height: ${lineHeight}px; font-size: ${fontSize}px; }
		`;
``` 

A simple fix would be to add an Underscore `_` before the hashed editor id. Something like this:
```javascript
this._styleClassName = '_' + hash(this._editor.getId()).toString(16); 
```

### Steps to Reproduce:

I was running into this issue in the monaco-editor by creating 10+ editors and noticed that after ~8 different editors, the code lens would not render correctly.

**Comment by jrieken** [comment]
Nice find!
