### ISSUE TITLE
No JS Runtime Errors while debuging

### ISSUE THREAD

**Issue by rydzek** [microsoft/vscode#94953]
I've had a long break since I've been develoing my extension. I remember that whenever I made some mistake (type error, reference error etc) I was able to ee that error in the debuging outbut. Right now no errors are show. Is this realy a bug or just something with my configuration? Please help.

- VSCode Version: 1.44.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a simple JS extension (yo code)
2. Add some code to generate an error (undefined function call should do)
3. Debug your extension (Hello world command)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you give a specific example? If there is a runtime error you will see it in the debug console.

**Comment by rydzek** [comment]
You can try by making a call to undefined function in Hello World command. Normally it should print a typical JS runtime error like:
UngaughtReferenceError: Call to undefined method XYZ.

**Comment by roblourens** [comment]
The thing is that it's not an unhandled error, because the vscode extension host actually catches the error. You should see a notification in the extension development host window with that error message. You would only see the error in the debug console if it was truly unhandled.

**Comment by rydzek** [comment]
Ok, thank you for explaining that. I was sure I saw those errors in the debug terminal. Well, sorry for my mistake.
