### ISSUE TITLE
Add support for Sasmung 49in monitors

### ISSUE THREAD

**Issue by TechGuyChris** [microsoft/vscode#94951]
Good day Microsoft VSCode team. I recently purchased a 49in ultrawide Samsung Monitor for coding. The VSCode does not seem to support Samsungs 'Easy Setting Box' software which is used to snap applications on to portions of the screen. Your other Microsoft products such as Office 365 (Outlook, Word, Excel etc) support this, however the VSCode app does not.

Can you build in support for this?

Here is a link to the monitor I purchased:
**Samsung**: https://www.microcenter.com/product/511198/samsung-c43j890-434-4k-uxga-120hz-hdmi-dp-curved-led-monitor

**Samsung Easy Setting Software**: https://displaysolutions.samsung.com/solutions/monitor-solution/easy-setting-box

Much thanks! 

TechGuyChris (Christopher)

**Comment by scath999** [comment]
Hi there,

Just got my own ultrawide, and not happy to see that this isn't supported.

I'm an IoT embedded systems developer working with three different platforms simultaneously - two hardware, one software. My current development schedule has me working more than 80 hours a week, developing code while managing a team of 3.

My previous solution of having three 27 in monitors, while functional, noticeably strains my neck. The ultrawide has relieved this issue, but your lack of support here makes setting up and rearranging my work environment a real pain.

Could you please rethink this? I'm not a streamer or hobbiest; I'm a professional that bought this solution specifically to solve a real problem.

**Comment by Gas-OCz** [comment]
> Hi there,
> 
> Just got my own ultrawide, and not happy to see that this isn't supported.
> 
> I'm an IoT embedded systems developer working with three different platforms simultaneously - two hardware, one software. My current development schedule has me working more than 80 hours a week, developing code while managing a team of 3.
> 
> My previous solution of having three 27 inch monitors, while functional, noticeably strains my neck. The ultrawide has relieved this issue, but your lack of support here makes setting up and rearranging my work environment a real pain.
> 
> Could you please rethink this? I'm not a streamer or hobbiest; I'm a professional that bought this solution specifically to solve a real problem.

If you are using windows 11, you can use win + z to arrange the windows

**Comment by scath999** [comment]
> If you are using windows 11, you can use win + z to arrange the windows

Hey there,

Thanks for the reply, but I'm using win10 and will not be moving to win11.
