### ISSUE TITLE
Notebook: Copy/Paste/Cut cells

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94956]
Issue Type: <b>Feature Request</b>

We may want to support copy/paste/cut cells but it's not as simple as what I imagined. `IClipboardService` allows us to store `resources` but it will break the File Explorer (because pasting notebook cells doesn't make any sense). We also need storage for cells which are cut and revive them when pasting.

cc @roblourens 

VS Code version: Code - Insiders 1.45.0-insider (c12bd56a8886f31e353a45f5846f0a35a52f908e, 2020-04-10T05:39:20.415Z)
OS version: Darwin x64 19.2.0

**Comment by roblourens** [comment]
I would imagine that only pasting file scheme resources into the explorer would work, and if I paste anything else, it just doesn't do anything?

**Comment by rebornix** [comment]
@roblourens yup. Now Copy a cell will put its source into the clipboard and we track copied cells internally in Notebook Service.

**Comment by rebornix** [comment]
Test verify this issue, install the GH issues notebook extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks

**Comment by isidorn** [comment]
This works fine thus adding verified label.
However created a follow up issue: https://github.com/microsoft/vscode/issues/96675
