### ISSUE TITLE
Set syntax highlighting for other extensions

### ISSUE THREAD

**Issue by katlimruiz** [microsoft/vscode#94950]
When the file is .js, the syntax and highlighting automatically sets it Javascript.
When the file is Dockerfile, the syntax is set as Docker
However, when you have another file like Dockerfile-web, I cannot assign Docker as syntax nor take advantage of plugins etc.
So in general you should be able to tell, this file is a "Docker" therefore everything works (Sublime Text has a command Set Syntax)

**Comment by RMacfarlane** [comment]
Hi @katlimruiz, you can configure this with the "files.assocations setting:
```
"files.associations": {
	"*.Dockerfile-web": "Docker"
}
```

You can also temporarily change the language mode of any file by using the "Change Language Mode" command or clicking on the language indicator in the bottom right on the status bar.
