### ISSUE TITLE
extension.node-debug.pickLoadedScript is not a valid command?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#94965]
In default keybindings json:

![image](https://user-images.githubusercontent.com/2193314/79030587-9d016000-7b4e-11ea-87f7-3bb1e152a9fc.png)

**Comment by weinand** [comment]
@roblourens the "pickLoadedScripts" action has been removed from vscode-node-debug because the LoadedScriptsView now supports filtering. Please remove the keybindings from the extensions.
