### ISSUE TITLE
Some menus are displayed in English after updating to the latest version 1.44

### ISSUE THREAD

**Issue by ayatokura** [microsoft/vscode#94969]
1. Update from settings to latest version as usual
2. Reload VS Code
3. Display VS Code menu 
4. Japanese should be displayed by Japanese extension, but some are displayed in English

[Troubleshooting]
1. Uninstall "Japanese Language Pack for Visual Studio Code" Extension
2. Reload
3. Install "Japanese Language Pack for Visual Studio Code" Extension
4. Reload
It didn't fix this issue.

[Environment]
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

[Extension]
Name: Japanese Language Pack for Visual Studio Code
Id: ms-ceintl.vscode-language-pack-ja
Description: Language pack extension for Japanese
Version: 1.44.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-ja

<img src="https://f3p2oq.by.files.1drv.com/y4mLgdKSG0SBaCBPfKEOIyNetYLEGarAzPLPIHAgIaYEgjjpvxLhPNohBN1DcIgkQWUcI0m-lp2_P6LMOqhHObnYCZQhtDCIPvpU6wZRguQKGyH_gkW5vdnk0X3dy4w005D7ZfqP9saLUdf_rjCAsAlx5YD3eOCmt6bemGLoTbBP7YfEG-t6jEKafm-uBXM_4yD8O3_gkNTItXrGMzirZlZ6g?width=1886&height=1502&cropmode=none" width="600">

**Comment by sbatten** [comment]
closing as I believe this has since been resolved
