### ISSUE TITLE
Suggestions cover over the options

### ISSUE THREAD

**Issue by Yonet** [microsoft/vscode#94964]
Issue Type: <b>Bug</b>

When typing in into an input box, suggestions cover over the most relevant choice. See image below:
![Screenshot (41)](https://user-images.githubusercontent.com/3523671/79030355-7858b880-7b4d-11ea-8001-dd0982bee8ba.png)

Thanks!

VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T18:12:33.780Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (50.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
SecurityIntelliSense|azs|0.8.0
azurite|Azu|3.6.0
LinkCheckMD|bla|0.3.1
gltf-vscode|ces|2.2.10
twitch-stream-notes-snippets|cla|0.0.1
vscode-markdownlint|Dav|0.34.0
docs-article-templates|doc|0.2.8
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.8
docs-linting|doc|0.0.2
docs-markdown|doc|0.2.63
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.46
docs-yaml|doc|0.2.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.2.0
vscode-firefox-debug|fir|2.7.2
rest-client|hum|0.23.2
vscode-lebab|jer|1.0.5
vscode-peacock|joh|3.7.0
unity-code-snippets|kle|1.3.0
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.2
vscode-azureappservice|ms-|0.16.5
vscode-azureeventgrid|ms-|0.1.1
vscode-azurestorage|ms-|0.9.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.0.0
vscode-devskim|MS-|0.4.119
csharp|ms-|1.21.16
sqlops-debug|ms-|1.3.0
python|ms-|2020.3.71659
vscode-ai|ms-|0.6.10
azure-deploy|ms-|1.0.5
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
autorest|ms-|2.0.1
azure-account|ms-|0.8.9
azure-sphere-tools|ms-|20.1.415071
azurecli|ms-|0.5.0
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0
github-issues-prs|ms-|0.9.2
powershell|ms-|2020.3.0
typescript-javascript-grammar|ms-|0.0.53
vscode-node-azure-pack|ms-|0.0.10
vscode-typescript-next|ms-|3.9.20200409
vscode-typescript-tslint-plugin|ms-|1.2.3
wordcount|ms-|0.1.0
vsonline|ms-|1.0.1968
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.5
debugger-for-chrome|msj|4.12.6
debugger-for-chrome-nightly|msj|2020.2.15300
debugger-for-edge|msj|1.0.14
vscode-sanddance|msr|1.2.12
vscode-streamdeck|nic|3.1.5
learn-module-creator|pat|0.2.0
vscode-unitymeta|PTD|0.0.7
vscode-yaml|red|0.7.2
code-spell-checker|str|1.8.0
unity-tools|Tob|1.2.3
unity-debug|Uni|2.7.5
usql-vscode-ext|usq|0.2.15
application-insights|Vis|0.4.2
azure-iot-edge|vsc|1.21.0
azure-iot-toolkit|vsc|2.16.0
vscode-arduino|vsc|0.3.0
vscode-iot-device-cube|vsc|0.2.0
vscode-iot-workbench|vsc|0.13.0
vscode-icons|vsc|10.1.0
WebTemplateStudio-dev-nightly|WAS|0.2.2007701

(2 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by RMacfarlane** [comment]
@Yonet I'm not sure what the source of these suggestions is, can you confirm if this is from an extension by running the `Developer: Reload with Extensions Disabled` command?
