### ISSUE TITLE
Unable to alt-click file paths beginning with \\?\ on Windows 10

### ISSUE THREAD

**Issue by connorskees** [microsoft/vscode#94961]
- VSCode Version: 
```
code-insiders --version
1.44.0-insider
ea935488ec0e5415d4205c1f33ba332fd417f85a
x64
```
- OS Version: `Microsoft Windows [Version 10.0.19592.1001]`

**Steps to Reproduce**:

```
cd %userprofile% 
mkdir foo && cd foo
echo bar > baz
echo %userprofile%\foo\baz VS \\?\%userprofile%\foo\baz
```

When I hover the former in the integrated terminal, I am given the option to alt-click to follow the path, but this does not occur for the latter. 

To verify that both paths are valid,
```
type %userprofile%\foo\baz
type \\?\%userprofile%\foo\baz
```
Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@connorskees I assume you mean within the integrated terminal?

**Comment by connorskees** [comment]
@RMacfarlane ah sorry for being unclear. Yes within the integrated terminal.

**Comment by Tyriar** [comment]
What does `\\?\` mean?

**Comment by connorskees** [comment]
@Tyriar `\\?\` [allows for paths above 256 characters in length](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation). The syntax also [disables all string parsing on the path](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).

It is used by the Windows API in a few places, namely [GetFinalPathNameByHandleA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlea#remarks) and [CreateFileA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#parameters). A few command line utilities I use use these functions to canonicalize paths.

**Comment by Tyriar** [comment]
Related: #21125

**Comment by connor4312** [comment]
@Tyriar one thing I found is that the literal string `\\?\%userprofile%\foo\baz` is linkified, but clicking on it tries to open the workspace folder as a file and shows the error notification "Unable to open '<workspace-folder-name>': File is a directory.". Echoing and clicking on the real path, though, works fine.

**Comment by Tyriar** [comment]
Nice find, it's being interpreted as a relative path.
