### ISSUE TITLE
When I Preview Markdown, I find Chinese cannot previewed correctly

### ISSUE THREAD

**Issue by Menma123** [Microsoft/vscode#9496]
- VSCode Version: 1.3.1
- OS Version: Windows10 HomeChina 10586

![default](https://cloud.githubusercontent.com/assets/16098030/16959723/0323fde6-4e19-11e6-9d63-96d367615468.PNG)
![2](https://cloud.githubusercontent.com/assets/16098030/16959724/0328bd90-4e19-11e6-8ee0-9bd09a4f0129.PNG)

**Comment by rebornix** [comment]
Weird, Those Chinese characters are transformed to Korean. I can't repro this with 1.3.1, can you provide your GitHub Page repo to us?

**Comment by Menma123** [comment]
@rebornix I tried other Computer and I cannot repro this. And, This wrong characters are not Korean, they are just look like Korean. I tried change the fonts and delete Profiles, but not work
What can I provide to help it?

**Comment by Menma123** [comment]
I tried copied the characters to MSWords, it shows correctly.

**Comment by kieferrm** [comment]
@Menma123 your last comment points to an encoding issue.

**Comment by mjbvz** [comment]
@Menma123 Can you check if this still repos. If it does, please provide the some example markdown that shows this behavior. Thanks.

**Comment by Menma123** [comment]
@mjbvz It is normal now

**Comment by mjbvz** [comment]
@Menma123 Glad to hear, thanks for reporting back. Closing this issue but please let us know if you run into any other problems
