### ISSUE TITLE
Unable to login to Github with 2FA

### ISSUE THREAD

**Issue by Hong-Revo** [microsoft/vscode#94967]
This just started happening today. I can't push changes to any Github repo. First it pops up the authentication GUI dialog box,

![image](https://user-images.githubusercontent.com/11328890/79033316-a9d69000-7bf0-11ea-8f6e-dc1f7470e376.png)

then asks for the 2-factor authentication input,

![image](https://user-images.githubusercontent.com/11328890/79033325-b955d900-7bf0-11ea-91ca-9a1cbb6ec8ae.png)

then it pops up the VScode input box asking for a username and password,

![image](https://user-images.githubusercontent.com/11328890/79033335-cbd01280-7bf0-11ea-9199-60022dc7d31b.png)

then it fails.

I can still push changes using the <strike>Github for Windows</strike> Github Desktop app without needing to login, so my credentials are clearly still present on my machine. It's only VSCode that can't find them all of a sudden.

Output:

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.26.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: c:\Users\hongo\Documents\GitHub\AzureQstor
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse test
> git rev-parse --symbolic-full-name test@{u}
fatal: no upstream configured for branch 'test'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :DESCRIPTION
> git ls-files --stage -- C:\Users\hongo\Documents\GitHub\AzureQstor\DESCRIPTION
> git config --get commit.template
> git cat-file -s 019290fd09e479399ca5cfb085102eddc7c1c190
> git check-ignore -v -z --stdin
> git push -u origin test
Logon failed, use ctrl+c to cancel basic credential prompt.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Azure/AzureQstor.git/'
```

- VSCode Version: 1.44.0 (system setup)
- OS Version: Win 10 1909

Steps to Reproduce:

1. Have an account that requires 2 factor auth
2. Try to push a commit.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Hong-Revo** [comment]
So, of course once I opened this issue, it started working again. After going through the login process, the push succeeded and then I got an email that a new PAT had been added to my account.

Can PATs go stale?

**Comment by RMacfarlane** [comment]
For GitHub, I don't think PATs expire. Is it possible you just entered the wrong username/password combo?

> remote: Invalid username or password.

If that was the problem, it would be nice to show an error message about it

**Comment by Hong-Revo** [comment]
I suppose the real question is why VSCode couldn't find the existing PAT. As mentioned, GH for Windows didn't have a problem.

**Comment by joaomoreno** [comment]
#20330
