### ISSUE TITLE
Extension host debugger shows compiled/minified symbols instead of sourcemapped version 

### ISSUE THREAD

**Issue by alexkreidler** [microsoft/vscode#94970]
Issue Type: <b>Bug</b>

Steps to reproduce: 

Try debugging an extension. I was debugging https://github.com/markis/vscode-code-coverage.

Run the `Launch Extension` task. Create some breakpoints.  [Mine were here](https://github.com/alexkreidler/vscode-code-coverage/blob/master/src/extension.ts#L122:L123).

Follow those breakpoints into part of the extension host API (by using the Step Into feature). In my case is was the Diagnostics Collection API: `diagnostics.set`.

Look at the debugger side panel. It should show minified symbols like `e`, `t`, etc, instead of the real symbols like `first` and `diagnostics`.

Additionally, while debugging inside the extension host, one cannot use the Debug Console to access any variables currently in scope. Allowing this could be quite useful, but I also see how it could open up vulnerabilities.

This may just be a limitation of the Debugger as it is currently, but I'd appreciate as detailed as explanation as possible.

Adding these capabilities would vastly improve extension development and handling weird edge cases with VSCode APIs.

Thanks for all your hard work everyone!

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 5.3.0-46-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor (16 x 3573)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.65GB (0.25GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.2
EditorConfig|Edi|0.14.5
debugger-for-chrome|msj|4.12.6
vscode-icons|vsc|10.1.0

</details>

**Comment by connor4312** [comment]
Sourcemaps have limited support for aliasing symbol names. If you've tried to debug minified code with sourcemaps on web apps before, for example, you probably have run into this problem as well. There's ongoing discussion between groups in Microsoft, Google, and others to create a replacement for sourcemaps that removes this limitation, among others, but realistically that's years away. If you need the ability to debug into internal VS Code sources, you can [run from source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run) and see the unminified code.
