### ISSUE TITLE
wordWrapColumn width calculation seems wrong for non-ASCII

### ISSUE THREAD

**Issue by deepestblue** [microsoft/vscode#94974]
Issue Type: <b>Bug</b>

1. Set
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 100,
1. Set viewPort width to approximately 100
1. Open long-running English text (e.g. attached English text in the Latin script) as a Plain Text file.
1. Notice word wraps around the width of the viewport.
1. Open long-running Tamil text (e.g. attached Tamil text) as "Plain Text" file.
1. Notice Tamil text is wrapped well before it hits the viewport end (only about 80% the viewport used)

Also repros with Telugu and Devanagari text.

[UDHR_Latin.txt](https://github.com/microsoft/vscode/files/4464066/UDHR_Latin.txt)
<img width="1440" alt="Latin" src="https://user-images.githubusercontent.com/5531915/79035753-50317f80-7b76-11ea-9463-d34135bb21b9.png">

[UDHR_Tamil.txt](https://github.com/microsoft/vscode/files/4464067/UDHR_Tamil.txt)
<img width="1440" alt="Tamil" src="https://user-images.githubusercontent.com/5531915/79035752-4f98e900-7b76-11ea-96c3-8ac76f50a298.png">

[UDHR_Telugu.txt](https://github.com/microsoft/vscode/files/4464068/UDHR_Telugu.txt)
<img width="1440" alt="Telugu" src="https://user-images.githubusercontent.com/5531915/79035751-4f005280-7b76-11ea-9d6a-971c453e56fb.png">

[UDHR_Devanagari.txt](https://github.com/microsoft/vscode/files/4464069/UDHR_Devanagari.txt)
<img width="1440" alt="Devanagari" src="https://user-images.githubusercontent.com/5531915/79035750-4b6ccb80-7b76-11ea-8c54-7a23a1e85042.png">

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.34.0
jshint|dba|0.10.21
pgsql|dou|0.1.3
EditorConfig|Edi|0.14.5
vscode-clang|mit|0.2.3
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
fontforge-vscode|xia|0.0.2

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Please use `"editor.wrappingStrategy": "advanced"`.
