### ISSUE TITLE
Show error/warning above the documentation on mouse hover

### ISSUE THREAD

**Issue by ronakg** [microsoft/vscode#94972]
Hi,

When I hover my mouse over an item with error/warning, I want to immediately see the error/warning rather than the documentation for that item. As of today, the documentation gets priority over error/warning, which doesn't make sense to me. Can you provide an option to switch this behavior?

Example:

The documentation for `Response` is shown by default (1st screenshot). But I'm interested in the warning, which is visible only after I scroll down (2nd screenshot).

<img width="575" alt="Screen Shot 2020-04-10 at 8 34 50 PM" src="https://user-images.githubusercontent.com/1058322/79035461-d4363800-7b73-11ea-97d7-6586f1e32627.png">
<img width="576" alt="Screen Shot 2020-04-10 at 8 35 05 PM" src="https://user-images.githubusercontent.com/1058322/79035465-d7312880-7b73-11ea-8b69-55b64bda24b9.png">

**Comment by octref** [comment]
I agree error should precede documentation.

**Comment by ronakg** [comment]
How do people vote for such feature-requests? Feels like such things get buried under the flood of issues that are posted here.

**Comment by CallumJHays** [comment]
Pretty please with :cherries:  on top? +1

**Comment by lf-** [comment]
relevant/may duplicate https://github.com/microsoft/vscode/issues/73120
