### ISSUE TITLE
PHP syntax highlighting (Dark / Dark+ default themes): "as" keyword in "foreach (... as ...)" gets wrong color

### ISSUE THREAD

**Issue by stakx** [microsoft/vscode#94978]
Issue Type: <b>Bug</b>

- VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
- OS version: Windows_NT x64 10.0.18362

#### Steps to Reproduce:

1. Select the Dark or Dark+ default theme.
2. Create a new empty file.
3. Change language mode to PHP.
4. Enter the following:

    ```php
    <?php
    foreach([] as $x) {
    }
    ```

5. Observe the colour of `as`. It should be coloured like a keyword, but isn't.

#### Possible cause:

This appears to be partly due to the PHP language grammar, which matches this `as` occurrence to the scopes named `constant.other` and [`keyword.operator.logical.php`](https://github.com/microsoft/vscode/blob/ef582f49ad69b5dfddc9e236a3eb501703a78c9f/extensions/php/syntaxes/php.tmLanguage.json#L716-L719) (instead of to some `keyword.other.???.php`, I suppose). The following custom settings appear to fix the problem (but I haven't yet determined what collateral damage, if any, this would cause):

```json
{
    "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
            "textMateRules": [
                {
                    "scope": "constant.other",
                    "settings": {
                        "foreground": "#c586c0"
                    }
                }
            ]
        }
    }
}
```

P.S. The mapping to [`keyword.operator.logical.php`](https://github.com/microsoft/vscode/blob/ef582f49ad69b5dfddc9e236a3eb501703a78c9f/extensions/php/syntaxes/php.tmLanguage.json#L716-L719) doesn't appear to make much sense in the first place. Is that by mistake?

**Does this issue occur when all extensions are disabled?:** Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
I'm not seeing the scope `constant.other` on `as` here. The scopes I have:
```
keyword.operator.logical.php
source.php
meta.embedded.block.php
text.html.php
```
Do you know where that scope is coming from?

**Comment by stakx** [comment]
> Do you know where that scope is coming from?

I didn't research this in detail, no. But I was under the impression that `constant.other` is a catch-all for identifiers that don't match anything more specific, such as type names that aren't prefixed by a namespace. (But I could be totally wrong on that.)

I identified `constant.other` simply by looking at a theme where `as` is correctly highlighted (e.g. Monokai), then grepping its source for the RGB hex value, and taking note of the `scope`s of the rules where that color value is specified.

**Comment by alexr00** [comment]
Can you run the **Developer: Inspect editor tokens and scopes** command and place your cursor in the `as`. That will give you the actual scopes for that token.

**Comment by stakx** [comment]
![image](https://user-images.githubusercontent.com/104481/79204510-f3b3b600-7e3c-11ea-89f8-29a262acbbdf.png)

**Comment by alexr00** [comment]
Do you have any extensions enabled?

**Comment by stakx** [comment]
> Do you have any extensions enabled?

Not for the above repro. (Well, except for the two built-in PHP extensions, I suppose; I made sure to disable all regular extensions visible in the extensions tab.)

**Comment by alexr00** [comment]
I can't repro those scopes at all. I think the scope `keyword.operator.logical.php` is not unreasonable, so I will not ask the grammar owners to change it. @stakx your settings change is a reasonable way for you to change the color for yourself.
