### ISSUE TITLE
PHP syntax highlighting (Dark / Dark+ default themes): "instanceof" gets wrong color

### ISSUE THREAD

**Issue by stakx** [microsoft/vscode#94979]
Issue Type: <b>Bug</b>

- VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
- OS version: Windows_NT x64 10.0.18362

#### Steps to Reproduce:

1. Select the Dark or Dark+ default theme.
2. Create a new empty file.
3. Change language mode to PHP.
4. Enter the following:

    ```php
    <?php
    if ($x instanceof Y) { }
    ```

   (Note I'm using an upper-case type name `Y` intentionally; this isn't the same issue as https://github.com/microsoft/vscode/issues/88441!)

5. Observe the colour of `instanceof`. It should be coloured like a keyword, but isn't.

#### Possible cause:

It appears that the themes don't contain a coloring rule for scope `keyword.operator.type.php`. The following custom settings appear to fix the problem:

```json
{
    "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
            "textMateRules": [
                {
                    "scope": [
                        "keyword.operator.type.php",
                    ],
                    "settings": {
                        "foreground": "#c586c0"
                    }
                }
            ]
        }
    }
}
```

**Does this issue occur when all extensions are disabled?:** Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
`instanceof` probably shouldn't be scoped as `keyword.operator.type`. I opened an issue in the repo that owns the grammar. https://github.com/atom/language-php/issues/388

**Comment by stakx** [comment]
Thanks! I didn't realise that these grammars were brought in from another project. Good to know!
