### ISSUE TITLE
Git output with user defined pager

### ISSUE THREAD

**Issue by HanabishiRecca** [microsoft/vscode#94988]
- VSCode Version: 1.44.0
- OS Version: Windows 10 / 1909

### The issue
Git allows user to set up a custom pager app. See [`core.pager`](https://www.git-scm.com/docs/git-config#Documentation/git-config.txt-corepager) option in git configuration.
And this can ruin VS Code communication with git. Commands such as `git show`/`git diff`/etc., which are uses pager, can truncate output or provide invalid output.

### How to fix it
VS Code just need to pass [`--no-pager`](https://www.git-scm.com/docs/git/2.26.0#Documentation/git.txt---no-pager) arg when calling git. To always receive the raw output.
For example here:
https://github.com/HanabishiRecca/vscode/commit/a13569c2aa886c831fdcd8b13cf4ea3ccc3d475a

**Comment by joaomoreno** [comment]
Good finding. Did you actually hit this issue in the wild?

**Comment by HanabishiRecca** [comment]
@joaomoreno, yes. Otherwise I probably would not have noticed it.

**Comment by joaomoreno** [comment]
Which features exactly do not work without this?

**Comment by HanabishiRecca** [comment]
For example, VS Code uses `git show :<file>` command to show the diff in the current file. When third party pager is defined and truncates the output, part of the file will be marked as newly added. But in reality the file isn't changed of course.
Or if you use entirely inproper program as pager, VS Code can show entire file as changed. Or show a total mess. Depends on what you've set up as pager.

**Comment by HanabishiRecca** [comment]
Small clarification: usually git can determine that command was run in non-interactive mode (not in the shell). But not always. This may vary in different circumstances and versions.
So this is more like to guarantee that git always send us the raw output.

**Comment by joaomoreno** [comment]
So, should we only add this argument in some commands and not all?

**Comment by HanabishiRecca** [comment]
I don't know really. [Official documentaion](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) says

> **`core.pager`**
This setting determines which pager is used when Git pages output such as log and diff. You can set it to more or to your favorite pager (by default, it’s less), or you can turn it off by setting it to a blank string:
> ```
> $ git config --global core.pager ''
> ```
> If you run that, Git will page the entire output of all commands, no matter how long they are.

So if considering this sentence
> **Git will page the entire output of all commands**

the answer is yes.

**Comment by avdg** [comment]
You can also use env variable `GIT_PAGER` instead that is set to a custom value for the vscode terminal

**Comment by joaomoreno** [comment]
> You can also use env variable `GIT_PAGER` instead that is set to a custom value for the vscode terminal

I like this much more than the current PR, wanna submit a PR?

**Comment by HanabishiRecca** [comment]
@avdg, yeah, seems like such solution will be better.

**Comment by avdg** [comment]
Not now, maybe in the weekend if nobody takes over. I have nothing checked out or build yet from vscode.

**Comment by avdg** [comment]
I'm myself unable to build the editor at the moment (I probably need to install more vscode stuff), feel free to test #95549 when able

**Comment by roblourens** [comment]
I can't repro the original issue in 1.44. I tried setting core.pager to several things that shouldn't produce the right result, and I see it respected when I run git commands in the terminal, but vscode still works ok. Tried `vim`, `head`, `code-insiders -`, don't see an issue. What were you using originally?

**Comment by HanabishiRecca** [comment]
@roblourens https://github.com/microsoft/vscode/issues/94988#issuecomment-613391615

**Comment by roblourens** [comment]
Yeah, I just wanted to figure out which circumstances those are. But it works fine for me on both mac and windows so I'll call it verified 🤷
