### ISSUE TITLE
same files show up twice in search results and go to file suggestions

### ISSUE THREAD

**Issue by MiLeung** [microsoft/vscode#94981]
- VSCode Version:  1.43.0
- OS Version: macOS 10.15.3

Steps to Reproduce:

1. search for a file using cmd+shift+f or cmd+p
2. Same file shows up twice (one UppercaseCamelCase and the other lowerCamelCase)
3. Seems to only happen with .go files (the UppercaseCamelCase file name is the real name)

Does this issue occur when all extensions are disabled?: Yes

<img width="592" alt="Screen Shot 2020-04-11 at 2 01 42 AM" src="https://user-images.githubusercontent.com/9166324/79039778-66e8ce00-7b98-11ea-8404-981cf8fbedda.png">

<img width="383" alt="Screen Shot 2020-04-11 at 2 02 15 AM" src="https://user-images.githubusercontent.com/9166324/79039789-79fb9e00-7b98-11ea-9f6b-6f5ac4070030.png">

**Comment by RMacfarlane** [comment]
@MiLeung Can you confirm that the lowercase version of the file doesn't actually exist on your file system?

**Comment by MiLeung** [comment]
Can confirm

**Comment by RMacfarlane** [comment]
@MiLeung Have you renamed these files recently and changed the casing? Can you try using the command `Clear Recently Opened`?

**Comment by MiLeung** [comment]
Thanks, that was it. I changed the file names a while ago and thought they would eventually stop showing up if I only opened the uppercase files.
