### ISSUE TITLE
cannot create a new file while choose a “t”-start file in the left panel

### ISSUE THREAD

**Issue by radiorz** [microsoft/vscode#94987]
- VSCode Version:1.44.0 （latest）
- OS Version:windows 1909（latest）

Steps to Reproduce:

1.On VS Code select File -> Open Folder and choose the folder you just created.
2.when choose a or b etc. file,it works
3.but when choose a t-start file（or s-start），it failed

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@radiorz I'm not able to reproduce this. What happens when you click on such a file? Is there any error notification? Can you run the command `Developer: Toggle Developer Tools` and report what is in the console there?
