### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by ayu-sh** [microsoft/vscode#94997]
/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Error: ENOENT: no such file or directory, open 'c:\Users\Hp\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js'
t.log @ /C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:262
/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3822 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ /C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3822
/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2855 Extension host terminated unexpectedly.
onDidChangeNotification @ /C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2855
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
vscodeexperiments.azureedge.net/experiments/vscode-experiments.json:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED
/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1611   ERR net::ERR_INTERNET_DISCONNECTED: Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3954 Error received from starting extension host
(anonymous) @ /C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3954
/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3954 timeout
(anonymous) @ /C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3954
/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at e.add (/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92)
    at e._register (/C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92)
    at /C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3954
add @ /C:/Users/Hp/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92

**Comment by RMacfarlane** [comment]
Duplicate, see discussion here: https://github.com/microsoft/vscode/issues/94858#issuecomment-611937137
