### ISSUE TITLE
Auto complete tags

### ISSUE THREAD

**Issue by jayharia** [microsoft/vscode#94995]
Issue Type: <b>Performance Issue</b>

my autocomplete tags arent working suddenly and my extension host live server also stopped working. can any one help?Does autocomplete has to do extension not working properly.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    80	  1924	code main
    2	   518	  4520	   gpu-process
    0	    13	 11436	   electron-crash-reporter
    1	    67	 15888	   window (Issue Reporter)
    1	    71	 18152	   window (undefined)
    0	   158	 28248	   window (Extension: Live Server - Desktop - Visual Studio Code)
    0	    11	 23832	     watcherService 
    0	    11	 51956	       console-window-host (Windows internal process)
    0	    29	 43368	   utility
    0	    70	 55352	   shared-process
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by RMacfarlane** [comment]
@jayharia Are you seeing a "Extension host terminated unexpectedly" notification?

**Comment by jayharia** [comment]
> @jayharia Are you seeing a "Extension host terminated unexpectedly" notification?

yes....it just popped all of a sudden...tried restarting it but no avail. Can you help me solve this problem?

**Comment by RMacfarlane** [comment]
Please try following the instructions here: https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

**Comment by jayharia** [comment]
thank you for the help ....the problem is being solved....

**Comment by RMacfarlane** [comment]
Great, glad you were able to fix it!
