### ISSUE TITLE
I suggest the token checker support Python 3.8

### ISSUE THREAD

**Issue by BornForFever** [microsoft/vscode#94999]
I tried the [Atom One Darker](https://github.com/christopherafbjur/vscode-theme-onedarker) theme just to find that the walrus operator `:=`(an operator to allow you to make assignments in an expression, see [PEP 572](https://www.python.org/dev/peps/pep-0572)) is highlighted as 2 different colors. And I tried inspecting tokens and scopes, and found that `:` and `=` were treated as 2 tokens.
![批注 2020-04-11 222317](https://user-images.githubusercontent.com/62426149/79046371-314cef00-7c43-11ea-89cd-8ec7dac5c2c7.png)
![批注 2020-04-11 222406](https://user-images.githubusercontent.com/62426149/79046374-33af4900-7c43-11ea-92bf-5da3e622da99.png)
I hope that the token checker can support Python 3.8.

**Comment by alexr00** [comment]
Moved to repo that owns the python grammar https://github.com/MagicStack/MagicPython/issues/204
