### ISSUE TITLE
Tyepscript beta 2.0 - Error still shown for Experimental Decorators (even with flag true in tsconfig)

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#9499]
- VSCode Version: **1.3.1**
- OS Version: **Win7**

Steps to Reproduce:

**1.** Typescript 2 beta installed & setup with `tsdk` in vscode settings.
![image](https://cloud.githubusercontent.com/assets/2574412/16962331/18aa3bee-4dbf-11e6-8f28-c1316f195089.png)

**2.** Experimental decorators flag set to `true`
![image](https://cloud.githubusercontent.com/assets/2574412/16962406/6f65e4ec-4dbf-11e6-9188-2ed283bd5673.png)

**3.** Use Decorator (Angular2 in this case) on a class, notice the error
```
import { Component } from '@angular/core';

@Component({ })
export class Home {
}
```

![image](https://cloud.githubusercontent.com/assets/2574412/16962365/374399d8-4dbf-11e6-9f26-befb8fd8e1b4.png)

**Comment by MarkPieszak** [comment]
The issue was that this was a module inside of a folder structure. Once I put an additional `tsconfig.json` in this folder with experimentalDecorators: true, it went away. But is this how it should be?

There was a top-level tsconfig that isn't coming down and effecting it.

**Comment by deadZedd** [comment]
Had the same issue, i just moved my tsconfig "down" a few levels in the hierarchy and it went away (note that my first assumption: that you need one tsconfigs per folder is false)

**Comment by MarkPieszak** [comment]
Did the same thing, I'm working with a multiple module setup so I had it differently at first, but whatever works!
