### ISSUE TITLE
Extension host terminated.

### ISSUE THREAD

**Issue by amrtya** [microsoft/vscode#94992]
From the last update, when I open VS Code they show me a notification like, "Extension Host terminated".  As result, 
1. all intellisense code is not working. 
2. Autocomplete is not  working.
3. Can't complete HTML tags & indentation.
4. Also cant restart extension host. 

Kindly fix this problem.

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/94807, please see the discussion here: https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765
