### ISSUE TITLE
.editorconfig indent_size ignored

### ISSUE THREAD

**Issue by StephenCleary** [microsoft/vscode#94998]
Issue Type: <b>Bug</b>

`indent_size` appears to be ignored.

Repro steps:

Create an `.editorconfig` file with this content:

```
root = true

[*]
indent_size = 2
```

Create an empty `test.js` file, and note that VSCode is using `Spaces: 4`.

I also tried turning off space autodetection in my workspace settings:

```
{
    "editor.detectIndentation": false
}
```

but VSCode persists in using `Spaces: 4`.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (23.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by robertrossmann** [comment]
VS Code does not natively recognise a `.editorconfig` file - you need to install an extension to have VS Code reflect your `.editorconfig` settings: [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig).
