### ISSUE TITLE
Extension Host terminating unexpectedly.

### ISSUE THREAD

**Issue by mdb2301** [microsoft/vscode#94996]
- VSCode Version: 1.44.0
- OS Version: Microsoft Windows 10 version 10.0.18363 Build 18363 

Description: I have found out that my antivirus application is removing the file <b>D:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js</b> 

which is resulting into failure of extension host. On checking the logs of antivirus, I found the file labeled as <b>JS.Nemucod.AF</b> 

[Virus Protection Report.txt](https://github.com/microsoft/vscode/files/4464653/Virus.Protection.Report.txt)

**Comment by RMacfarlane** [comment]
Duplicate, please see https://github.com/microsoft/vscode/issues/94858#issuecomment-611937137 for how to fix
