### ISSUE TITLE
Select current line

### ISSUE THREAD

**Issue by benkaiser** [Microsoft/vscode#950]
Basically I'd just like feature parity with Atom on this.

first ctrl+l: should select the current focussed line
repeated ctrl+l should extend the selection to the end of the next line

Currently what happens:
ctrl+l: nothing

I looked through the shortcut config and couldn't find anything to do this. I also was unable to find any action for this in the source code of vscode.

**Comment by Agetorp** [comment]
Me and my buddy have implemented this feature, pull request is coming up shortly

**Comment by harangue** [comment]
The standard implementation of this shortcut is Ctrl-L. Not that a rebind was hard, but why bind it to Ctrl-I?

**Comment by le717** [comment]
I have the same question. Even this issue requests binding to Ctrl-(lowercase) L. How did it end up at Ctrl-(lowercase) I?

**Comment by benkaiser** [comment]
Don't hate on them, they implemented the feature before I'd even submitted
the request! They're legends. Would just be nice to have the default
reminded though :)

**Comment by le717** [comment]
Trust me, I am not hating! This one feature is the highlight of the entire update for me. It'd just be nice if it were mapped to the universal shortcut by default. :)

**Comment by prashaantt** [comment]
The other thing that Sublime does very well here is select the newline character at the end of each line, which means super easy deletions of whole lines and moving up the remaining text. Please consider supporting this too.
