### ISSUE TITLE
Settings.json not highlighting hex colors.

### ISSUE THREAD

**Issue by rakibdev** [microsoft/vscode#95003]
I have customized workbench colors by changing settings.json.
In previous insider version 1.44.0, a small square box appeared as hex color preview.
Now those hex color not highlighting on Visual Studio Code Insider 1.45.0.

Here is settings image of v1.45.0

![Visual Studio Code Settings](https://i.ibb.co/Y8tgYSR/vs-code-settings.png)

**Comment by rebornix** [comment]
I saw this issue sometimes but now I can't reproduce it anymore on latest version. Can you help confirm that?
