### ISSUE TITLE
extension wont run

### ISSUE THREAD

**Issue by quantrpeter** [microsoft/vscode#95004]
Hi
   I am using latest vscode in windows 10, i am developing my own extension. I press F5 to run my extension, it works in the first time, vscode popup. Then i close it, and run it second time by pressing F5, in the status bar, it displays "building..." and run forever. No vscode is popup. I think it is a bug. Any workaround?
Thanks
Peter

**Comment by RMacfarlane** [comment]
@quantrpeter Can you share your `launch.json` file?

**Comment by quantrpeter** [comment]
i find the workaround, everytime i click F5, the new vscode haven't popup, i manuall resize the "terminal" window, then it comes up. Surely it is a bug but i am find now.
