### ISSUE TITLE
Flutter's hot reload not working since update 1.44

### ISSUE THREAD

**Issue by SharkatechRaf** [microsoft/vscode#95006]
- VSCode Version: 1.44
- OS Version: Catalina 10.15.4

Steps to Reproduce:

1. Open any flutter project with VS Code.
2. Chose any virtual device and go to: Run -> Run Without Debugging.
3. The Debug Console will output:
D/EGL_emulation( 5962): eglMakeCurrent: 0xdc929500: ver 3 0 (tinfo 0xdc948f40)
Lost connection to device.
Exited (sigterm)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
I know this is an issue with VSCode updating and not the extension, but can you open this on the extension to begin the investigation there? I don't know the details of this feature
