### ISSUE TITLE
Select all visible occurrences

### ISSUE THREAD

**Issue by kaba2** [microsoft/vscode#95007]
The editor currently has the feature "Select all occurrences", which selects all occurrences in the file. However, most of the time I find that what I really need is the set of occurrences that are visible in the editor, not in the whole file. I wish there was a way to do this.

**Comment by ArturoDent** [comment]
You can do it manually pretty quickly with the 

```
{
  "key": "ctrl+d",
  "command": "editor.action.addSelectionToNextFindMatch",
  "when": "editorFocus"
}
```
default keybinding.  Unfortunately if your cursor starts out below the first find match on the page, this command will start from the cursor - so make sure your cursor is at the top of the page before clicking/finding.

[Just in case you were unaware of this command.]

**Comment by kaba2** [comment]
If I understood correctly, I would put the cursor on the first occurrence of the word on the top, and the first Ctrl+D would add it to the selection. Then next Ctrl+D would add the next occurrence of that word to the selection. The problem with this is that if there is an occurrence below the current editor view, then eventually it will add that occurrence and also scroll the view, which I do not want.
