### ISSUE TITLE
Allow to disable persistent undo/redo stack

### ISSUE THREAD

**Issue by MrChocolatine** [microsoft/vscode#95000]
In the recent update 1.44 you enabled a persistant undo/redo stack:
https://code.visualstudio.com/updates/v1_44#_keep-undo-stack-when-reopening-files

Please, allow us to disable this to have the previous and basic behaviour as when we close a file and reopen it, we should not expect to have a history to undo/redo changes.

**Comment by leosdad** [comment]
Yes, please expose this as an option. In my case, I keep internal backups and I want the Undo/Redo history to be gone as soon as I close the file. In fact I'd also like to have the option to clear it at will, like some old-style code editors did (it was called Clear Undo history, I believe).
