### ISSUE TITLE
Obviously Not Important Bug About UX

### ISSUE THREAD

**Issue by ChayimFriedman2** [microsoft/vscode#95018]
This bug is OBVIOUSLY NOT IMPORTANT. But I noticed that the rounded edges of the selection rectangle are more rounded on right, and that hurt my eyes. So I zoomed in, and found out that the selection overflowing to the left somewhat. Here's the picture:

![image](https://user-images.githubusercontent.com/24700207/79053022-d74c2980-7c42-11ea-9702-640d12487c8b.png)
Theme: Dark+ (Default Dark)

You can see that the blue rectangle is overflowing to left and crossing the horizontal gray line. This is the reason that the rectangle seems to be more rounded on its right. So we should (must!) shrink the rectangle to fit the width.

**Edit:** Yes, I know. I'm bored.

**Comment by alexdima** [comment]
Does this reproduce when disabling all extensions?

**Comment by ChayimFriedman2** [comment]
@alexdima Yes.

Probably this is a problem with the CSS.

I made some research, and the issue seems to be double:

One - attached the HTML generated:

```html
<div style="position:absolute;top:4978px;width:100%;height:19px;">
  <div class="cslr selected-text top-left-radius bottom-left-radius top-right-radius bottom-right-radius" style="top:0px;left:15px;width:16px;height:19px;"></div>
  <div class="cigr" style="left:0px;height:19px;width:15.390625px"></div>
  <div class="cigr" style="left:15.390625px;height:19px;width:15.390625px"></div>
  <div class="cigr" style="left:30.78125px;height:19px;width:15.390625px"></div>
</div>
```

```css
/* The CSS was simplified */

.selected-text {
  background-color: <some-blue/gray>;
}

.cigr {
  box-shadow: 1px 0 0 0 #404040 inset;
}
```

![Untitled](https://user-images.githubusercontent.com/24700207/79166743-81b48000-7dee-11ea-83c6-7ddad4525515.png)

(There are colored decorations added by the excellent [Bracket Pair Colorizer extension](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2), ignore them. They just hide the rightmost `cigr`, but the problem exists anyway).

You can notice the `cigr`s are calculated each with width of 15.390625 pixels (high zoom; the number in normal mode will be much smaller), while the `cslr` is rounded down to 15 pixels. That in turn make a selection a little shorter than the real width.

The second problem is: we do not take into account the one pixel of the shadow (`cigr`). The first tab selection should start at 1 (not zero) and be 14.390625 (not 15.390625). The second starts at 16.390625 and same width, etc..

I'm working currently on another PR, but if you want to take that:

For the first problem - things are happened IMO at https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/lines/viewLine.ts#L92 and at https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/indentGuides/indentGuides.ts#L38.

For the second - if indentation guides are enabled (`EditorOption.renderIndentGuides`), and the selection is fully contained inside the indentation, we need to do the calculation.

**Comment by alexdima** [comment]
I would still like to reproduce before doing any changes. Here is how it looks like for me:

![image](https://user-images.githubusercontent.com/5047891/79213439-7a6e9000-7e49-11ea-9374-2b3a0bc2874e.png)

Can you please try again disabling all extensions and commenting out all settings to identify which combination of fontSize, zoomLevel, etc. help in reproducing.

**Comment by ChayimFriedman2** [comment]
```json
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.tabSize": 2,
    "editor.renderWhitespace": "all",
    "window.zoomLevel": 9,
    "workbench.activityBar.visible": false
}
```

Type some tabs then some non-whitespace character. For me, for the 1st tab selected I get the selection not adjacent the second indent guide, and somewhat hidden by the first. When selecting the second it is adjacent to the right, but overflows to the left and visible before the second indent guide. For the 3rd like the first. For the 4th like the 2nd. I don't know where the inconsistency come from.

And your image is too  blur. It seems you didn't zoom at all.

**Comment by alexdima** [comment]
This is caused by `window.zoomLevel`. Please do not use `window.zoomLevel` if you care about pixel perfect rendering.

`window.zoomLevel` is implemented by Chromium and is the same implementation like zooming in a website. This works under the hood by multiplying all the positions / dimensions we give with the zoom ratio and then the result is rounded to an integer. This breaks the assumption `x0 + width = x1` that we have, because zooming ends up doing something like `round(x0 * ratio) + round(width * ratio) ~= round(x1 * ratio)`. 

Therefore, sometimes things will be off by 1 px due to rounding when using zooming. There is nothing for us to do short of disabling zooming completely, which I often want to do but my team mates don't let me. The workaround is to use `editor.fontSize` which avoids the rounding problem.
