### ISSUE TITLE
Minimal support for JSON-LD files

### ISSUE THREAD

**Issue by alexkreidler** [microsoft/vscode#95013]
#56334 and #63270 already have requested better built-in support for JSON-LD by improving the JSON language features extension to include hover and completion for JSON-LD. That is not this issue.

I propose **minimal** support for JSON-LD, which basically just means when I open a `.jsonld` file or a file with the `application/ld+json` MIME type, it gets treated like normal JSON.

Right now when I do this, it doesn't detect the language at all and provides no syntax highlighting.

![jsonld-vscode](https://user-images.githubusercontent.com/11166947/79051703-bb736400-7bff-11ea-9b54-396f1218a6fd.png)

This should be very easy to implement, just by modifying the language contribution settings in the builtin JSON extension.

**Comment by aeschli** [comment]
I pushed a change that `.jsonld` is now associated to JSON
