### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by ShirshaDatta** [microsoft/vscode#95011]
Issue Type: <b>Bug</b>

I uninstalled all the extensions still it is showing the same thing. Then I uninstalled VS Code and then installed it again. Then I had to re-install the extensions chrome debugger for javascript , intellisense for javascript and react snippets . These extensions are always needed by me as I am a front-end developer. VS Code works fine after reinstallation but as soon as I close it and open it agan it shows the same problem. How do I fix this?

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by RMacfarlane** [comment]
Duplicate, instructions are here: https://github.com/microsoft/vscode/issues/94858#issuecomment-611937137
