### ISSUE TITLE
Hi I am using latest vs code's latest version in windows 10,  when i press F5 it was show error that "Extension host terminated unexpectedly" and after clicking on button "Restart Extension Host", i didn't get any response and no result is shown

### ISSUE THREAD

**Issue by jsdpr1503** [microsoft/vscode#95014]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ArturoDent** [comment]
Search through the closed issues.  Many recent ones about this.

**Comment by jsdpr1503** [comment]
VSCode Version: 1.44.0 (New
OS Version:
Steps to Reproduce:

Does this issue occur when all extensions are disabled?: Yes/No
