### ISSUE TITLE
"File: Reopen with..." does not trigger `didCloseTextDocument` to clean up 

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#95028]
Version: 1.45.0-insider
Commit: 44c5185373d5f209cd6c0b5d29a216fb801da34e
Date: 2020-04-10T19:43:46.226Z (1 day ago)
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

Using the new "File: Reopen with..." editor command to reopen a `Notebook` in `Text Editor` I expect this to:

* Send a [`didCloseTextDocument`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didClose) for each cell which triggered a different `didOpenTextDocument` notification previously.
* Send a single `didOpenTextDocument` for the "new" regular file

Today, only the latter is done (it sends a new `didOpenTextDocument`). This puts Language Servers into a bad state because they now have "two" of the same file that they are tracking.

cc @rebornix

**Comment by jrieken** [comment]
I have debugged this to a point at which I understand that the input is never disposed but I don't know why that is. Maybe the old editor needs to be explicitly closed?

**Comment by TylerLeonhardt** [comment]
I've noticed that after I do "File: Reopen With..." I've seen a 2nd tab of the same file in my instance of vscode.

It's not clickable so it's clearly a relic of something keeping the old file "open"

Hopefully that information helps.

**Comment by rebornix** [comment]
The input is a bit fat right now, we will move most logic (like working copy) to text model and then input can be disposed properly.

**Comment by rebornix** [comment]
Already fixed via the refactoring around `NotebookEditor/Document` events

* if a notebook editor is pinned/dirty, reopening in text editor, will not dispose inner text models
* if a notebook editor is not pinned/dirty, reopening in text editor will emit text document close events for all visible cells

**Comment by roblourens** [comment]
What I see now is that `onDidClose/OpenTextDocument` are never fired for notebooks, and are fired correctly for the text editor when switching between notebook/text editor. Is that correct?

**Comment by jrieken** [comment]
Yeah, that makes sense since we keep the notebook widgets alive for better restore on tab switch. The notebook widget will hold on to the notebook model which again holds on to text models.
