### ISSUE TITLE
Stop Visual Studio Code to watch for file changes

### ISSUE THREAD

**Issue by reob-info** [microsoft/vscode#95023]
- VSCode Version: all
- OS Version: Lubuntu based at Ubuntu 18.04

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

Why is not possible to disable the function of watch for file changes?

I would like to have this option to set at VSCode config file, or at least limit it for the actual folder.

**Comment by bpasero** [comment]
We have a setting `"files.watcherExclude"` to exclude folders from file watching.
