### ISSUE TITLE
Powershell Not Starting

### ISSUE THREAD

**Issue by DAD713** [microsoft/vscode#95025]
Issue Type: <b>Bug</b>

Only on my laptop

Either the regular powershell extension or the preview, I get this message.

The terminal process command 'C:\Program Files\PowerShell\7\pwsh.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command 'Import-Module 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\logs\1586645272-bfa96cd5-2d04-4961-bc7b-26577c3c85351586645268918\EditorServices.log' -SessionDetailsPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\sessions\PSES-VSCode-34072-157267' -FeatureFlags @() '' failed to launch (exit code: {2})

----

4/11/2020 6:47:52 PM [NORMAL] - Visual Studio Code v1.45.0-insider 64-bit
4/11/2020 6:47:52 PM [NORMAL] - PowerShell Extension v2020.4.1
4/11/2020 6:47:52 PM [NORMAL] - Operating System: Windows 64-bit
4/11/2020 6:47:52 PM [NORMAL] - Language server starting --
4/11/2020 6:47:52 PM [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\7\pwsh.exe
4/11/2020 6:47:52 PM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\logs\1586645272-bfa96cd5-2d04-4961-bc7b-26577c3c85351586645268918\EditorServices.log' -SessionDetailsPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\sessions\PSES-VSCode-34072-157267' -FeatureFlags @() 
4/11/2020 6:47:52 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\logs\1586645272-bfa96cd5-2d04-4961-bc7b-26577c3c85351586645268918\EditorServices.log' -SessionDetailsPath 'c:\Users\laxre\.vscode-insiders\extensions\ms-vscode.powershell-preview-2020.4.1\sessions\PSES-VSCode-34072-157267' -FeatureFlags @() 
4/11/2020 6:47:52 PM [NORMAL] - pwsh.exe started.
4/11/2020 6:47:52 PM [NORMAL] - Waiting for session file
4/11/2020 6:49:52 PM [NORMAL] - Error occurred retrieving session file:
Timed out waiting for session file to appear.
4/11/2020 6:49:52 PM [NORMAL] - Language server startup failed.
4/11/2020 6:49:52 PM [ERROR] - The language service could not be started: 
4/11/2020 6:49:52 PM [ERROR] - Timed out waiting for session file to appear.

VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T18:12:33.780Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.7.2
vscode-logicapps|ms-|0.2.33
vscode-edge-devtools|ms-|1.0.7
python|ms-|2020.3.71659
azure-account|ms-|0.8.9
powershell-preview|ms-|2020.4.1
vsliveshare|ms-|1.0.1947
team|ms-|1.161.0
debugger-for-edge|msj|1.0.14

</details>

**Comment by RMacfarlane** [comment]
Please file this on the PowerShell extension: https://github.com/PowerShell/vscode-powershell Thank you!
