### ISSUE TITLE
PHP class and primitive type function parameters scoped and highlighted identically

### ISSUE THREAD

**Issue by bakerkretzmar** [microsoft/vscode#95029]
Issue Type: <b>Bug</b>

PHP function parameters receive the exact same scope (and are therefore the same colour) whether they are classes or primitive types.

VS Code: class names should be yellow and other keywords purple, but both the `Request` and `bool` typehints are purple. They are both scoped:

```
storage.type.php
meta.function.parameter.typehinted.php
meta.function.parameters.php
meta.function.php
meta.class.body.php
meta.class.php
source.php
meta.embedded.block.php
text.html.php
```

<img width="598" alt="Screen Shot 2020-04-11 at 9 05 46 PM" src="https://user-images.githubusercontent.com/18192441/79058225-386eff80-7c39-11ea-8e9f-a9e0a5ecf057.png">

For comparison, in Sublime, the `Request` typehint, which is a class name, is yellow, and the `bool` one is purple. Scopes are a little different in Sublime, but notably the `bool` typehint does _not_ include `storage.type.php`:

<img width="594" alt="Screen Shot 2020-04-11 at 9 06 20 PM" src="https://user-images.githubusercontent.com/18192441/79058255-9bf92d00-7c39-11ea-899f-5f5c91ff72e6.png">

I understand that if this is actually a bug in the grammar I should send a PR to Atom's `php-language` repo, but is that what's happening here? Can anyone provide some more insight or point me to where I would start working on a fix?

Thanks.

---

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
better-phpunit|cal|1.5.2
disableligatures|Coe|0.0.8
macros|ged|1.2.1
customize-ui|ioc|0.1.34
monkey-patch|ioc|0.1.7
php-cs-fixer|jun|0.1.149
vetur|oct|0.24.0
advanced-new-file|pat|1.2.0
toggle|reb|0.0.1
laravel-artisan|rya|0.0.27
ayu|tea|0.18.0
errorlens|use|3.1.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Sorry for not responding, thanks for filing it upstream, looks like this is in progress

**Comment by bakerkretzmar** [comment]
@roblourens the upstream PR has been merged, do I need to submit one here now to run the update script and pull in the new grammar, or will that happen automatically? Thanks!

**Comment by roblourens** [comment]
Thanks for the ping. We do this periodically and I'll do it in December (we are stabilizing the November release this week), but I would accept a PR next week too.
