### ISSUE TITLE
Should not show consent prompt when resolving token after login

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#95020]
Issue Type: <b>Bug</b>

Use auth provider in an extension:
```
	context.subscriptions.push(vscode.commands.registerCommand('extension.login', async () => {
		const session = await vscode.authentication.login("github", ['user:email']);
		const token = await session.getAccessToken();
		vscode.window.showInformationMessage(`Successfully logged with ${token}`);
	}));
```

On login, a consent prompt is shown asking if the extension can login. Another prompt is shown for the get access token call. If login is OK'd, should not prompt a second time.

VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T19:43:46.226Z)
OS version: Darwin x64 18.7.0

**Comment by roblourens** [comment]
Is the "second time" when `session.getAccessToken` is called? Or is it when I run the command a second time? Because I see the same flow if I run the command twice, I assume that's ok.
