### ISSUE TITLE
Extension Host terminated unexpecteddly

### ISSUE THREAD

**Issue by utsav-dnana** [microsoft/vscode#95037]
Issue Type: <b>Bug</b>

Whenever I am launching my Vscode then  it shows an error called: "Extension Host Terminated Unexpectedly". I tried to disable all the extension and restarted it but it still showed the same error. Please help.
![Screenshot (36)](https://user-images.githubusercontent.com/63533736/79062513-b4f4f300-7cb8-11ea-9e5f-adae39ec3eb8.png)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (7.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.0
vscode-icons|vsc|10.1.0

</details>

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/95011#issuecomment-612478992
