### ISSUE TITLE
settings.json: $ref '/definitions/jsonObject' in 'vscode://schemas/launch' can not be resolved.

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#95033]
Surely this is a minor issue, inside `settings.json`, there's a warning at the first opening curly brace:

    $ref '/definitions/jsonObject' in 'vscode://schemas/launch' can not be resolved.

![image](https://user-images.githubusercontent.com/610161/79039652-5cb8e500-7c15-11ea-823b-5db14c22da5e.png)

- VSCode Version: 1.44
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. open Settings, or press `⌘ + ,`
2. the mentioned error appears in the Problems view

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
@isidorn is the "launch" schema the one from debug?

**Comment by isidorn** [comment]
I can not reproduce this using your steps.
@ryenus Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

@weinand yeah

Seems like a json schema issues, also assigning to @aeschli as he might have ideas.

**Comment by HeinBehrens** [comment]
I have the same issue.
![image](https://user-images.githubusercontent.com/1666074/79110928-6c4e4000-7d73-11ea-8f9b-d4912f4007ab.png)

**Comment by russelldias98** [comment]
I am getting the same issue too.

<img width="620" alt="Screenshot 2020-04-13 at 7 58 03 PM" src="https://user-images.githubusercontent.com/3706645/79128487-3a63ca80-7dc1-11ea-91fe-eea635072f95.png">

**Comment by kazek228** [comment]
Confirm from my side:
![lanchJsonVSCodeProblem](https://user-images.githubusercontent.com/31931510/79141467-22d51380-7dba-11ea-8d7a-2c61e34dd34a.JPG)

**Comment by timeswind** [comment]
same here

**Comment by ryenus** [comment]
@isidorn, I found it, disable the **AWS Toolkit** extension then restart, the error is gone.
But TBH I'm not sure if the error existed before updating vscode to 1.44, though.

**AWS Toolkit**: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode

**Comment by russelldias98** [comment]
> @isidorn, I found it, disable the **AWS Toolkit** extension then restart, the error is gone. I tried with latest Insider build.
> ~But TBH I'm not sure if the error existed before updating vscode to 1.44, though.~
> 
> **AWS Toolkit**: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode
> 
> The latest version of AWS Toolkit is `1.8.0`, which is problematic, meanwhile installing the previous version `1.7.0` from https://github.com/aws/aws-toolkit-vscode/releases/, then there's no such error.

Yes, I can confirm this fixed the issue for me.

**Comment by ryenus** [comment]
FYI, issue opened for AWS Toolkit: https://github.com/aws/aws-toolkit-vscode/issues/1027

**Comment by Luca-Terrazzan** [comment]
> @isidorn, I found it, disable the **AWS Toolkit** extension then restart, the error is gone. I tried with latest Insider build.
> ~But TBH I'm not sure if the error existed before updating vscode to 1.44, though.~
> 
> **AWS Toolkit**: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode
> 
> The latest version of AWS Toolkit is `1.8.0`, which is problematic, meanwhile installing the previous version `1.7.0` from https://github.com/aws/aws-toolkit-vscode/releases/, then there's no such error.

Solve for me as well, thanks!
