### ISSUE TITLE
Low-contrast color for "show x more: ..." button in callstack

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#95030]
![image](https://user-images.githubusercontent.com/323878/79058444-06a76a00-7c34-11ea-9d14-a6433b16e206.png)

Hard to read, was that on purpose?

**Comment by isidorn** [comment]
Yeah, since the Show 3 More appears dimmed. So now it is dimmed + blue for link color.
Though I do agree that the opacity is too hard, thus I have increased. Now it should be better.
Thanks
