### ISSUE TITLE
Create Project Error in Visual Studio Code

### ISSUE THREAD

**Issue by chavanshrikant** [microsoft/vscode#95034]
Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and platform. Also, if you are using VS Code on Windows what antivirus product do you use (if any)?

**Comment by chavanshrikant** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/63528928/79088294-d0670900-7d5f-11ea-959d-fb4f8b9aa6ef.png)

**Comment by chavanshrikant** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/63528928/79088354-fc828a00-7d5f-11ea-966a-2ac47b8026d2.png)

VSC  version 1.44.0
platform WINDOWS 10 
antivirus  QUICK HEAL
