### ISSUE TITLE
objective-c cannot jump to definition, I sure vscode support it by built-in.

### ISSUE THREAD

**Issue by AsteriskZuo** [microsoft/vscode#95031]
Please see [https://github.com/microsoft/vscode/issues/94735](94735)

**Comment by gjsjohnmurray** [comment]
See https://github.com/Microsoft/vscode-cpptools/issues/2533

AFAIK this is is the home of the built-in extension that provides VS Code's default C and C++ support.

**Comment by gjsjohnmurray** [comment]
And the built-in objective-can extension only implements syntax colouring

https://github.com/microsoft/vscode/blob/master/extensions/objective-c/package.json

**Comment by gjsjohnmurray** [comment]
/duplicate #94735 #94867 please do not open more duplicates

**Comment by AsteriskZuo** [comment]
https://github.com/microsoft/vscode/blob/master/extensions/objective-c/build/update-grammars.js
![Screen Shot 2020-04-13 at 16 04 22](https://user-images.githubusercontent.com/11733363/79104207-b4378c00-7da0-11ea-8067-625e1ea10300.png)

Doesn't this file already show that defined jumps are supported?

I don't understand why you shut it down every time you don't answer a question.

If I wrote it in the closed answer, you wouldn't see it.




> /duplicate #94735 #94867 please do not open more duplicates

**Comment by gjsjohnmurray** [comment]
No, that is GitHub telling you about code navigation in the files in GH.

**Comment by AsteriskZuo** [comment]
Finally, thank you for your patience.
