### ISSUE TITLE
The terminal cannot be opened in the workspace

### ISSUE THREAD

**Issue by Z-LL** [microsoft/vscode#95035]
Issue Type: <b>Bug</b>

Configuration information:
```
"terminal.explorerKind": "external",
"terminal.external.windowsExec": "‪D:\\software\\Git\\bin\\bash.exe",
"terminal.integrated.shell.windows": "D:\\software\\Git\\bin\\bash.exe",
```
Press the shortcut key directly, you can open git bash below. But right click on the workspace directory and select open in Terminal, it will prompt that the file cannot be found, and the path is correct.
How to deal with it?

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
Can you share a screenshot of the problem and your settings.json file?

**Comment by Z-LL** [comment]
> Can you share a screenshot of the problem and your settings.json file?

Sorry i just saw the news.
Shortcut key: ctrl + ` , Can be opened normally
![1](https://user-images.githubusercontent.com/27721325/79679909-8b9a1100-823c-11ea-9fa3-0307b0cf081b.png)
Shortcut key: ctrl + shift + c, error
![2](https://user-images.githubusercontent.com/27721325/79679920-b5ebce80-823c-11ea-9ec2-69f304cd458a.png)
Right click, open in terminal, error
![3](https://user-images.githubusercontent.com/27721325/79679934-d9167e00-823c-11ea-93d6-672f24a32064.png)

All configurations:

[settings.txt](https://github.com/microsoft/vscode/files/4498390/settings.txt)


THANKS.

**Comment by Tyriar** [comment]
This should work:

```
"terminal.external.windowsExec": "‪D:\\software\\Git\\git-bash.exe"
```
