### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Sumit-Chakole** [microsoft/vscode#95036]
Issue Type: <b>Bug</b>

I have gone through similar issue and confirm this issue is also due to quick heal have modified vs code extensionHostProcess.js file. (Very similar to issue- #94869)

My problem is I had uninstalled quick heal yesterday for some other issue. I have found that vscode couldn't found file extensionHostProcess.js, I opened the file location in file explorer and found file is renamed. (I was not aware that's done by quick heal that time). I renamed the file as it is needed. Original issue is gone but extension host still crashes.

I understand quick heal might have modified this file! **Is there any way I can regenerate this file** (I will surely whitelist this file as suggested in #94858 on reinstallation of quick heal)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.21
vscode-eslint|dba|2.1.2
prettier-vscode|esb|4.2.0
vscode-react-native|msj|0.14.2

</details>

**Comment by GunsRuth** [comment]
Rerun the installer(it won't forget your settings).
Also, do not rename instead go to quarantine in quck heal and exclude and restore the file.

**Comment by sumitparakh** [comment]
Hi @Sumit-Chakole  , If suggestion by @GunsRuth  doesn't work for you, I've uploaded content of extensionHostProcess.js [here](https://gist.github.com/sumitparakh/696472f8ebb164bc0e31d6b5529cab61)

Just copy it and paste it in your extensionHostProcess.js file as it is. 
Before doing that, make sure you take backup of that file first.

Let me know if it helps or not.

**Comment by Malaya2184** [comment]
i think you have some antivirus....
if you have quick heal total security  then
go to the quick heal
->file folders
->exclude file folder from scanning
->add file i.e C:\Users\(user file name e.g- hp...etc)\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js
->save changes...
It is working perfectly....

**Comment by Sumit-Chakole** [comment]
> Rerun the installer(it won't forget your settings).
> Also, do not rename instead go to quarantine in quck heal and exclude and restore the file.

Thanks for this! It worked :)
