### ISSUE TITLE
JSON language server error not showing error stack

### ISSUE THREAD

**Issue by ktjd123** [microsoft/vscode#95045]
- VSCode Version: 1.44.0
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. Don't know where this error is comming from since I can't check the stacktrace.
2. Open project with error
3. if i close code completly then reload code, this error is not showing.

Does this issue occur when all extensions are disabled?: No

**Comment by aeschli** [comment]
Can you add a screenshot?
