### ISSUE TITLE
Mode indication doesn't change when switching to prefs file

### ISSUE THREAD

**Issue by GaryBoone** [microsoft/vscode#95059]
Issue Type: <b>Bug</b>

I have open an Ansible file, a shell script, a text file, and a preferences file (settings.json). 

When I switch to the Ansible file, there's a mode indicator on the bottom status bar that changes to "ansible". When I click on the settings.json file, it remains on "ansible". When I click on the shell script, it changes to "shellscript". When I then click on the settings.json file, it remains on "shellscript". When I click on the text file, it changes to "plaintext". When I then click on the settings.json file, it remains on "plaintext". 

So, specifically, two ways to look at this problem:
1) The status doesn't change to the correct mode for the settings file.
2) The status shows the wrong mode for the settings file. 

I do have the Ansible and YAML extensions installed.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.3.0

**Comment by RMacfarlane** [comment]
I'm having trouble reproducing this - for me, the language mode indicator changes to "JSON with Comments" when settings.json is open. Can you share your settings, have you modified `files.associations`?

**Comment by bpasero** [comment]
@GaryBoone since I recently fixed an issue in this area, can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
