### ISSUE TITLE
Fail to install 'ms-python.python'

### ISSUE THREAD

**Issue by yanggehua** [microsoft/vscode#95052]
- VSCode Version: VS 1.45.0 insiders and 1.44.0 stable
- OS Version: Windows 10

Steps to Reproduce:

1. Go to Extensions panel
2. Select "Python" module (from microsoft)
3. Click install
4. Got error message: `Faile to install 'ms-python.python'`

I also tried manual installation. After downloaded the plugin and ran VS selector, it has the following error:
```
4/12/2020 11:05:34 AM - Microsoft VSIX Installer
4/12/2020 11:05:34 AM - -------------------------------------------
4/12/2020 11:05:34 AM - Initializing Install...
4/12/2020 11:05:34 AM - Extension Details...
4/12/2020 11:05:34 AM - 	Identifier         : python
4/12/2020 11:05:34 AM - 	Name               : Python
4/12/2020 11:05:34 AM - 	Author             : ms-python
4/12/2020 11:05:34 AM - 	Version            : 2020.3.71659
4/12/2020 11:05:34 AM - 	Description        : Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.
4/12/2020 11:05:34 AM - 	Locale             : en-US
4/12/2020 11:05:34 AM - 	MoreInfoURL        : 
4/12/2020 11:05:34 AM - 	InstalledByMSI     : False
4/12/2020 11:05:34 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
4/12/2020 11:05:34 AM - 
4/12/2020 11:05:34 AM - 	SignatureState     : Unsigned
4/12/2020 11:05:35 AM - 	Supported Products : 
4/12/2020 11:05:35 AM - 		Microsoft.VisualStudio.Code
4/12/2020 11:05:35 AM - 			Version : 
4/12/2020 11:05:35 AM - 
4/12/2020 11:05:35 AM - 	References         : 
4/12/2020 11:05:35 AM - Signature Details...
4/12/2020 11:05:35 AM - 	Extension is not signed.
4/12/2020 11:05:35 AM - 
4/12/2020 11:05:35 AM - Searching for applicable products...
4/12/2020 11:05:35 AM - Found installed product - Microsoft Visual Studio Professional 2013
4/12/2020 11:05:35 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
4/12/2020 11:05:35 AM - Found installed product - Microsoft Visual Studio Community 2015
4/12/2020 11:05:35 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
4/12/2020 11:05:35 AM - Found installed product - Global Location
4/12/2020 11:05:35 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

I suspect it is interfered by other VS installations.  

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)


Try installing the VSIX you downloaded using the command `Install From VSIX...` from VS Code.

**Comment by yanggehua** [comment]
I was following your instructions.  The last step seemed to work. So I use the command `Install from VSIX ...` and browse locally the downloaded file `ms-python.python-2020.3.71113.vsix`. The extension was then installed corrected (asking for a reload). 

There was no network problem. When I clicked on "Install" button inside the extension panel and when it failed, the only output I got was:
```
Installing Extension Python failed: Manifest is not found.  extensionsActions.ts:1752 
```

**Comment by sandy081** [comment]
Enable log level to trace using `Set Log Level` command and  please provide logs from here.
- View -> Open View… -> Log (Shared)

**Comment by yanggehua** [comment]
Strange. The installation of Python module in VSC goes well today. I did not encounter the same error previously. As I don't have a way to reproduce the bug with higher log level, I guess the only thing we can do is to just close the ticket.
