### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by ravi1997** [microsoft/vscode#95057]
Issue Type: <b>Bug</b>

I just installed it and dont have any extension installed in it.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ravi1997** [comment]
I have already reinstalled it and also removed the folder of extension.

**Comment by ArturoDent** [comment]
Look at the dups listed.  Probably your AV software, particularly if you use SelfHeal.

**Comment by gjsjohnmurray** [comment]
/duplicate. Thanks @ArturoDent
